### ISSUE TITLE
ctext auto-alias broken

### ISSUE THREAD

**Issue by StrangerFive** [Zrips/CMI#10]
Custom text (ctext) auto-alias is broken.  If a ctext file has \<AutoAlias\> set when the server boots, it doesn't work. But, if you "editctext" the file and click the second "[+]" twice (off and back on), then the auto-aliasing starts working for that file. But upon the next reboot, ctext auto-alias doesn't work again.

I'm running CMI 7.3.8.5 on the latest Spigot 1.12.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Will be fixed with 7.3.8.6+

**Comment by StrangerFive** [comment]
Thanks bud.  This issues page is a great idea.

**Comment by Zrips** [comment]
Say thanks to LogGits for this idea :)
