### ISSUE TITLE
Playtime in CMI is calculated wrong

### ISSUE THREAD

**Issue by DrexHD** [Zrips/CMI#1000]
**Description of issue or feature request:**
/playtimetop prints out inaccurate values
---
/playtimetop prints out exactly 1/3000 of the actual value:
[https://imgur.com/a/KGm9DAG](screenshot)
DrexHDs real playtime is 3421549 seconds and CMI says 1139 seconds which divided is about 3000

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  PlayTimeFromStats: true
  # When set to true, playtimetop list will be loaded on server startup
  PreloadTopPlaytime: false
```

---

Cmi Version `8.0.20.0`

Server Type `Spigot` 

Server Version `git-Paper-366`

**Comment by LogGits** [comment]
Ok I am also now experiencing this on build 8.2.0.0. Paperspigot build 456.

**Comment by Zrips** [comment]
Will be fixed with next update.
