### ISSUE TITLE
Please add something to sync economy data across bungee seevers

### ISSUE THREAD

**Issue by kn-km** [Zrips/CMI#1002]
**Description of issue or feature request:**
I set the mysql config to the same data base but the money could not sync.
wish to add a new feature to do it.

---
**Cmi Version (using`/cmi version`):** 
8.0.20.0

**Comment by 0xC1A551C** [comment]
Use mysql player data sync plugin

**Comment by HansscMe** [comment]
Mysql player data sync plugin could not sync the balance top in time,and could not support some offline trade plugins.
There may be many issues.

**Comment by HansscMe** [comment]
Mysql player data sync plugin could not sync the balance top in time,and could not support some offline trade plugins.
There may be many issues.
