### ISSUE TITLE
Question: Where to find Elevator Sign info?

### ISSUE THREAD

**Issue by Phyther** [Zrips/CMI#1004]
I have been looking in all the configs, and on the wiki, but all I can find it that the sign needs to have a header like it is in the config.yml. default is [CMIElevator] but putting this on the top line of the sign only gives me a message that the elevator sign was created, but otherwise does nothing.

**Comment by Baktus79** [comment]
Then you did it correct. To make it work you place another elevator sign above it or under it. Remember there must be a platform there to teleport to. Right click the sign to go up, and sneak+right click you go down.
