### ISSUE TITLE
Question: How can I stay in my current gamemode when teleporting to a different world?

### ISSUE THREAD

**Issue by Kalasky** [Zrips/CMI#1007]
**Description of issue or feature request:**

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

---

**Cmi Version (using`/cmi version`):** 
8.0.19.0
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
353

**Comment by 0xC1A551C** [comment]
Change this in multiverse?

**Comment by Kalasky** [comment]
How do I do that for certain players? Instead of changing the whole world to creative?
