### ISSUE TITLE
/vanish removes you from any teams

### ISSUE THREAD

**Issue by Royster0** [Zrips/CMI#1008]
When you go into vanish, its fine. But its when you come out of vanish, it removes you from any team you were in. Any way of fixing this?

**Cmi Version (using`/cmi version`):**
8.0.20.0

**Server Type (Spigot/Paperspigot/etc):**
PaperSpigot

**Server Version (using `/ver`):** 
Ver 385

**Comment by Royster0** [comment]
I can confirm that this is still happening Using Ver 8.0.23.0 and PaperSpigot Ver 444

**Comment by Zrips** [comment]
If issue still persists with latest version, please reopen this ticket.
