### ISSUE TITLE
Player death and repspawn events not working

### ISSUE THREAD

**Issue by doitliketyler** [Zrips/CMI#1009]
**Description of issue or feature request:**
I'm trying to apply night_vision on player respawn but it just doesn't work. I've tried many types of death and still the night_vision does not get applied. Thoughts?

---

**Cmi Version (using`/cmi version`):** 
8.0.20.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.13.1

**Comment by LogGits** [comment]
Can we see your configuration layout?

**Comment by doitliketyler** [comment]
Sure tho it would have nothing to do with that because I use it on other events and it works without issue.

https://pastebin.com/raw/WKDGb53i

**Comment by Zrips** [comment]
@doitliketyler 
You are lacking one extra line
`
  - delay! 1
  - cmi effect [playerName] night_vision 99 1
`
Without it effect command will gonna be performed before actual player respawn, but during it and player will not receive it. So you need slight delay to apply potion effect.
