### ISSUE TITLE
CMI Holograms doubling up glitch

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#1010]
**Description of issue or feature request:**
![image](https://user-images.githubusercontent.com/36227001/47405530-ccc46a00-d706-11e8-9d43-f4985f7625c2.png)

Happens when you edit a hologram from the text file then reload. Fixed when you re-join the server. Happens a lot for me.

**Cmi Version (using`/cmi version`):**  8.0.20.1

**Server Type (Spigot/Paperspigot/etc):**  papermc (name is no longer paperspigot)

**Server Version (using `/ver`):**  1.13.2

**Relevant plugins (Delete if this isn't needed):**

**Comment by LogGits** [comment]
This is because our holograms are packet based. Meaning it is rendered on the clients screen. So leaving the area or relogging will resolve this.

This only happens with `/reload`. We don't recommend using `/reload` + cmi has a `/cmi reload`
