### ISSUE TITLE
FactionsUUID and CMI

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#1012]
I noticed  using factions uuid and integrated economy, cmi save the factions as player on database and create duplicates....

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Attention! Found 1 duplicates in database. Same name, different UUID. This can cause some minor issues. Please remove one of them from database with /cmi removeuser [uuid] or /cmi removeuser duplicates
faction-3 0c1cb0fa-7d74-3a5d-a0f1-ef853b8cd907 last seen: Unknown
faction-3 673e065d-a5d1-4ef6-93d0-c333d62e54b8 last seen: Unknown
```

**Cmi Version (using`/cmi version`):** 8.0.20.1

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):**  1.13.2

**Comment by Zrips** [comment]
Will be addressing this issue with next build. If issue persists, please let me know.
