### ISSUE TITLE
Players Can Move Other Players Out of AFK

### ISSUE THREAD

**Issue by Kalasky** [Zrips/CMI#1017]
**Description of issue or feature request:**
Users should be able to go AFK without the worry of being moved out of it. Once they /afk other users shouldn't be able to push others out of afk or move them whatsoever - The person who AFK'd should be able to move out themselves not by another player. This defeats the purpose of being able to afk safely.

**Comment by LogGits** [comment]
This would be cool, a `PreventCollision: true`
