### ISSUE TITLE
Problem with CMI and ProtocolSupport

### ISSUE THREAD

**Issue by J0schlZ** [Zrips/CMI#1019]
https://github.com/ProtocolSupport/ProtocolSupport/issues/928

I tracked it down and i think CMI is the cause of the problem.
Is CMI sending invalid Dimension ID's? idk.

Does someone have an Idea?

**Comment by J0schlZ** [comment]
Is someone have the same issue?
I really really want to run ProtocolSupport on my Server :(

**Comment by J0schlZ** [comment]
Not cool. :(

**Comment by J0schlZ** [comment]
Can someone please help me?
I really need to use ProtocolSupport.
Not want to drop off CMI :(

**Comment by Zrips** [comment]
This should have been fixed in recent updates

**Comment by OverBrave** [comment]
Problem again started.

**Comment by therealatsuga** [comment]
Can confirm - apparentely only teammember are affected?

Server thread/INFO]: yaiiko lost connection: Internal Exception: java.lang.IllegalArgumentException: Unknown dimension network id 13
