### ISSUE TITLE
[Request] Option to get replied when in vanish

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1021]
**Description of issue or feature request:**
I would like to have the ability to be replied when in vanish. I know why it's disabled. It can be misused to discover a vanish staff player. Therefor I would like to be able to turn that off so staff can message a player in vanish and get a reply, without turning off vanish.

If staff needs to get out of vanish, then everybody starts to talk to the staff and intervene.

Preferable this option would be togglable via the `vanishedit`. So every staff player can decide for himself.

**Comment by LogGits** [comment]
This was added in `8.2.2.0`
