### ISSUE TITLE
/armorstand GUI major bug 

### ISSUE THREAD

**Issue by ArtNRG** [Zrips/CMI#1023]
**Description of issue or feature request:**
The /armorstand GUI can be used for item duplication.
---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.0.21.1-> 8.0.21.2

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
git-Paper-405 (MC: 1.13.2)

**Steps to reproduce the bug** 
1. Sit in minecart
2. Start moving somewhere and rapidly open the armor stand GUI
3. Let the minecart to bring you somewhere where the chunk containing the armor stand will be unloaded.
4. Take all you need from items section of the  GUI.
5. Move back to the armor stand and take the copy of your items.
The ways to move can differ.

**Comment by Zrips** [comment]
Will be fixed by limiting range after each click. Just in case this one happens.
