### ISSUE TITLE
Phantoms Spawning On Vanished Players - Feature Request

### ISSUE THREAD

**Issue by Kalasky** [Zrips/CMI#1026]
**Description of issue or feature request:**
If a staff member in vanish is watching over a player, phantoms shouldn't spawn because the vanished player hasn't slept for a few days. Phantoms should ignore vanished users.

**Comment by LogGits** [comment]
Phantoms are annoying and even spawn on creative players. This could relate to:
```
EntityTargetEvent
EntityTargetLivingEntityEvent
```
