### ISSUE TITLE
Renaming spawners with /cmi give doesn't apply given name

### ISSUE THREAD

**Issue by Flexxxxx** [Zrips/CMI#1027]
Using, for example "/cmi give Flex__Seal spawner 1 n &ePig_&fSpawner" gives a normal pig spawner, without the name that is specified in the give command. Using the exact same command, but changing the material to literally anything else, the name applies. 

---

---

**Cmi Version (using`/cmi version`):** 8.0.19.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.13.1-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Will be fixed with next update.
