### ISSUE TITLE
[BUG] Shulker Box Backpack Item Deletion

### ISSUE THREAD

**Issue by Lunna123** [Zrips/CMI#1033]
**Description of issue or feature request:**
When using the shulker backpack feature for the first time on a particular shulker box, if you shift click an item OUT of the shulker box, it registers this as you trying to crouch and automatically closes your inventory. As a result, whatever item you were trying to transfer from the shulker box backpack is lost forever. 

This issue goes away after subsequent uses of that particular shulker box as a backpack. If you get a new shulker box and use it as a backpack for the first time, the error occurs again.

There are no errors in console associated with this. A temporary work-around could be changing the key pressed to open a shulker-box as a backpack?

**Cmi Version (using`/cmi version`):** 8.0.21.3

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper (404) 1.13.2-R0.1-SNAPSHOT

**Comment by LogGits** [comment]
I cannot reproduce this. Can you try on the latest version of paperspigot and cmi. It would also be convenient if you could provide a video of this so we can see exactly how it's messing up.
