### ISSUE TITLE
I want more information about "world" command

### ISSUE THREAD

**Issue by beeng9** [Zrips/CMI#1035]
As far as I know, There is a /world (normal/nether/end/1/2/3...) (playername) (-s) command.
But, I have no information about this commands mechanism.

It seems like teleport to random place.
Sometimes teleport to 3500,2300... and sometimes to 20,50

I wonder about (-s).
Where does this variable affect to?

**Cmi Version (using`/cmi version`):** 
8.0.20.1
**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-f950f8e-0a81101 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):**

**Comment by LogGits** [comment]
As far as `-s` goes, it is the same thing used on a bunch of commands. It means silent, whereby the player wont see the message when they are teleported. I'm not too sure about the how /world teleports maybe @Zrips can lets us know 🙂

**Comment by Zrips** [comment]
World command teleports to defined or next world to same location. It can be some what "random" as nether has 8x smaller coordinate system
