### ISSUE TITLE
Players Losing Homes

### ISSUE THREAD

**Issue by Phyther** [Zrips/CMI#1036]
**Description of issue or feature request:**

Players lose homes when switching servers in a bungee network when both servers share the same MySQL database. I suspect this is the same issue with economy and other stored player data. 

Would it be possible to store such data per server in addition to per world?

**Cmi Version (using`/cmi version`):** 
8.0.21.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
 git-Paper-417 (MC: 1.13.2)

**Comment by Zrips** [comment]
CMI doesn't (currently) support bungee network, let alone same database to be used on multiple servers. So yes, you will loose homes and bunch of other stuff as this is not how CMI should handle player information. Create separate database for separate server as each CMI plugin should have its own database.
