### ISSUE TITLE
Question - Bungee placeholders

### ISSUE THREAD

**Issue by WarmasterCain55** [Zrips/CMI#1038]
I am trying to use hologram placeholders for bungee. Our server was recently setup for bungeecord and am currently testing it. Does CMI need any special adjustments for holograms to tie into the bungee placeholders? Any placeholder I try to put in just puts out a blank result.

**Comment by LogGits** [comment]
Are there any specific placeholders that you are trying to use(just need to test)?

**Comment by WarmasterCain55** [comment]
Here's one.
&4%cmi_bungee_total_[emerald]%
I am using that on a separate server then the server mentioned in the command above.  What comes up is nothing, it's just blank.

**Comment by Zrips** [comment]
%cmi_bungee_total_emerald%
This is the correct format for it. In general when you see [something] it will indicate that you need to replace entirety with some variable, brackets including.
