### ISSUE TITLE
Kit Limit Error?

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#1042]
**Description of issue or feature request:**
Having a weird thing happen with kits that have a limit on their use, but I may also be misunderstanding how it works -- it is my understanding that the limit on the number of times a kit can be used was per player -- is that not the case? Instead, when players try to claim a kit everyone is getting the "Can't use more than 1 time" error, even if they've never used the kit before.

Ideally this limit should be per player. Or if not, that seems like a strange limitation. I'm not otherwise getting any errors. I'm trying to grant these kits through interactive commands (run asPlayer!) but same results when they actually type the kit command. Am I doing it wrong?

Thanks!
---

**Cmi Version (using`/cmi version`):** 
8.0.21.2
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
git-Spigot-2474d93-e693496 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by mercurialmusic** [comment]
Right, but then they can use the kit an unlimited number of times. The limiter is there, I think, to limit how many times each person can use it. It's not working like that, instead imposing a global limit. The behavior is either broken or kinda strange.

**Comment by Zrips** [comment]
@mercurialmusic 
That could only mean that player got this kit before that. Each kit usage is recorded and counted towards usage amount. So if you are getting this message that means player already received this kit. It could be solved by renaming it to something completely new.
Will add new command to reset players kit usage counter.
