### ISSUE TITLE
Spawner requests

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#1043]
I'm currently trying to remove the need for SilkSpawners and I was hoping since CMI already has spawner settings that we could maybe add some more to it.

Currently on 1.13.2 this does not work:
/cmi give name mob_spawner:creeper

-Can we get a /givespawner command?
-Can we edit the name/lore format for spawners? 
-Can we also have a system that lets us craft spawners with a mob egg? 

I am also having an issue with /spawner. I keep doing /spawner cow but it tells me the target block must be a mob spawner. I'm looking at this spawner from all angles as well as holding one so I'm not sure how this is suppose to work (paper 1.13.2, CMI 8.0.21.4)
*Also the gui doesn't show up if you type /spawner

**Comment by LogGits** [comment]
Tested this on 1.13.2
`/cmi give <myusernamehere> mob_spawner:creeper` and i received a creeper spawner.
We have a `/cmi itemlore` and a `/cmi itemname` to change lore and name.

`/cmi customrecipe` can help you create a custom recipe.

Do you have essentials installed by anychance? It could be interfering.
