### ISSUE TITLE
/Ignore does not ignore messages on chat

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [Zrips/CMI#1045]
**Description of issue or feature request:**
/Ignore does not ignore messages sended on normal chat
---

**Cmi Version (using`/cmi version`):** 
8.0.21.4
**Server Type (Spigot/Paperspigot/etc):** 
paperspigot
**Server Version (using `/ver`):** 
1.13.1

**Comment by user127001** [comment]
config.yml:
###  # If set to true, players public message who is in your ignore list will not be shown
  IgnorePublicMessage: true ###

**Comment by user127001** [comment]
config.yml:
```# If set to true, players public message who is in your ignore list will not be shown
  IgnorePublicMessage: true

**Comment by LogGits** [comment]
I'm assuming this was resolved, If you are still having issues please open another issue.
