### ISSUE TITLE
McMMO party spy

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#105]
A feature that allows you to spy on the McMMO party.

This is the McMMO party event: 

https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/events/chat/McMMOPartyChatEvent.java

**Comment by Zrips** [comment]
This should be handled by McMMO itself or by some dedicated plugin. Its out of CMI feature range and what its meant to be.

**Comment by Sikatsu** [comment]
Theres a plugin that hooks into essentials socialspy, but if I were to switch to CMI this feature will be gone basically.
