### ISSUE TITLE
Crash with spigot 1.13.2 after some hours/random

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#1050]
**Description of issue or feature request:**
The server crash for this java error,  i was alone on the server standing in front to some cmi holograms and setting stuff, the crash keep to happening after some hours /random

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://gist.github.com/xion87/b484b5e1e76d91b00401c4171e45f647
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
default config using MYSQL
```

---

**Cmi Version (using`/cmi version`):** 
 8.0.21.4
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 

> [11:06:19 INFO]: This server is running CraftBukkit version git-Spigot-e4d0c66-1057710 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by xion87** [comment]
he fixed it with today release?

**Comment by Zrips** [comment]
@xion87 
Not as i'm aware of.
Do you have server log before this crash? What commands you performed? As it seems to be related to MySQL update, but cant pin point actual reason where it failed and why without additional information.

**Comment by xion87** [comment]
i just stay on front of a cmi holo without doing any command and it crashed, in other case a guy just typed /pets (of another plugin) and it crashed

**Comment by LogGits** [comment]
@xion87 does this happen on 8.2.0.0?

**Comment by xion87** [comment]
it seem fixed i think so

**Comment by LogGits** [comment]
Let me know if you experience this in the future 👍
