### ISSUE TITLE
Cant give GM perm to players

### ISSUE THREAD

**Issue by Duqino** [Zrips/CMI#1051]
**Description of issue or feature request:**

Trying to let players use /gm (gamemode) but perm is not working.

[![Screenshot from Gyazo](https://gyazo.com/29e404bb2653409a161054673e6006c0/raw)](https://gyazo.com/29e404bb2653409a161054673e6006c0)

tried -> 0 - 1 - Survival - survival - Creative - creative
And none of them work. The server keeps saying that i dont have perm for it.

cmi.command.gm.[gametype] - Allows to change game mode to particular type

---

**Cmi Version (using`/cmi version`):** 
[![Screenshot from Gyazo](https://gyazo.com/db77cd89c2e6e35a40c8ab8694cde03d/raw)](https://gyazo.com/db77cd89c2e6e35a40c8ab8694cde03d)

**Server Type (Spigot/Paperspigot/etc):** 
Spiot

**Server Version (using `/ver`):** 
1.13.2

Using Luckperms:

[![Screenshot from Gyazo](https://gyazo.com/e8b6fca79cf0106b4e72e9a7a4ef8881/raw)](https://gyazo.com/e8b6fca79cf0106b4e72e9a7a4ef8881)

**Comment by JohOply** [comment]
What appear in your console when player try the command? (missing perm would be display)

**Comment by Duqino** [comment]
[![Screenshot from Gyazo](https://gyazo.com/85a715d9e219ebc49c924769edda2f84/raw)](https://gyazo.com/85a715d9e219ebc49c924769edda2f84)

Thats what i get in console. Not strange just like normal because the server thinks i dont have the perms.

**Comment by JohOply** [comment]
I mean something like https://i.imgur.com/gOiY1ow.png

**Comment by Duqino** [comment]
https://gyazo.com/0d6f9ee5731a5520804534279c02ced5?token=9590c39803b4bc352663b776e2ac8597

Did not work.
I gave the perm to the player itself.

**Comment by JohOply** [comment]
I try **cmi.command.gm + cmi.command.gm.creative** // also **cmi.command.gm + cmi.command.gm.* ** they work on player himself (at least), so i don't know :x

**Comment by LogGits** [comment]
That is caused by Chatcontrol. Disable your chatcontrol's rule that blocks the /gamemode command.

**Comment by x1p** [comment]
CMI sometimes forgets a players perms too.
I have something similar. After reloading the permissions, it works again.
```
[12:07:53] [Server thread/INFO]: Player123 issued server command: /gm 1
[12:07:53] [Server thread/INFO]: Player123 doesn't have permission for: cmi.command.gm.creative
```
Although it has `cmi.command.gm.creative` via inheritance and has `cmi.command.gm.*` too.

**Comment by Duqino** [comment]
> That is caused by Chatcontrol. Disable your chatcontrol's rule that blocks the /gamemode command.

You are right. Turned off the commands rules option in the chatcontrole config file and its working now.

Thanks for the info and helping me out!!!!!!!!

**Comment by LogGits** [comment]
@x1p please make a new issue for that. Include permissions plugin in the issue report so we can test it appropriately 👍
