### ISSUE TITLE
Little issue: gm <myself> <gamemode> doesn't work

### ISSUE THREAD

**Issue by JohOply** [Zrips/CMI#1054]
**Description of issue or feature request:**
Hi
Little issue with gm command
- **/gm gamemode** works
- **/gm other_player gamemode** works
- **/gm myself gamemode** (it useful to use completion) doesn't work, no error, nothing in chat nor console, nothing happens 
---
**Cmi Version (using`/cmi version`):** 8.21.4

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-2474d93-ca22de3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by LogGits** [comment]
Interesting, `/cmi gm <username> [gamemode]` doesn't work for me when i use my own username either.

**Comment by Zrips** [comment]
Will be fixed with next update.
