### ISSUE TITLE
Question regarding last rank

### ISSUE THREAD

**Issue by FestusDM** [Zrips/CMI#1056]
Last rank still says "_____ can rank up!" This is the last rank, is there a place where I can disable (or get rid of) the "can rank up!" part? Screenshot of what I'm talking about in the link below.

https://i.imgur.com/f04flt0.png
---
**Cmi Version: 8.0.21.4**
**Paperspigot (426) 1.13.2-R0.1-SNAPSHOT**
**Vault version: 1.7.1-b91(CMIEInjector)**

**Comment by LogGits** [comment]
in `locale_EN.yml`

```yaml
      rankNameLine: ' &e------ &6[rankName] &e[rankupState] &e------'
      canRankup: ' &2Can rankup!'
```

**Comment by FestusDM** [comment]
Separate but yet related question...
Anyway to make the formatting of that screenshot different?
Is it also under `locale_EN`?
