### ISSUE TITLE
Quesition: Rank Related Questions

### ISSUE THREAD

**Issue by FestusDM** [Zrips/CMI#1059]
1. Any way we can customize what each rank command say?
Ex: When players type `/rankinfo`, it's a customized list of what that rank can do and not the default settings.
2. Anyway to make the formatting `/rankup` to something different? Is it under `locale_EN`? Because I can't seem to find it. https://i.imgur.com/WxmLRQZ.png

I'd like that to say...
```Your current rank: Visitor
Next rank: Scout
Rank up requirements:
Items: Stack of dirt
Progress Bar
-------------------

**Comment by FestusDM** [comment]
**Cmi Version: 8.0.23.0
Paper(444) 1.13.2-R0.1-SNAPSHOT
Vault version: 1.7.1-b91(CMIEInjector)**

**Comment by Zrips** [comment]
99.9% of locale lines are translatable and localed in a file. Some feedback messages for rankup command could be at rankinfo category.
