### ISSUE TITLE
[Suggestion] Vanish and /seen

### ISSUE THREAD

**Issue by iaxedu** [Zrips/CMI#106]
People are able to find out if staff is online by doing **/seen** even when they are in vanish. 

The suggestion is simple, a new permission that is required to see someone online with **/seen**. While being in vanish of course. 

perm: **cmi.command.seen.vanish**

**Comment by MCTyler** [comment]
Why not just negate the perm seen?

**Comment by Ew9304** [comment]
Because then players wouldn't be able to use /seen for other reasons, idiot.

**Comment by Zrips** [comment]
This will be fixed with next update
