### ISSUE TITLE
Xp Orbs Don't Flow Towards Any Player

### ISSUE THREAD

**Issue by delbertina** [Zrips/CMI#1061]
**Description of issue or feature request:**
After the release on the 29th, xp does not actually flow towards any player. It graphically does, but the player must go to the origin to pick it up. Must be an issue with how it checks for a player in vanish with that enabled. Issue persists with players that do and don't have vanish perms.
Someone on the discussion thread mentioned this, but never made a report.

---

**Cmi Version (using`/cmi version`):** 
8.0.21.4
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
427 - 1.13.2

**Comment by user127001** [comment]
I confirm this problem. Join.

**Comment by Zrips** [comment]
Will be fixed with todays update.
