### ISSUE TITLE
8.1.0.0 CMI ??? how ?

### ISSUE THREAD

**Issue by a7ssan** [Zrips/CMI#1064]
http://prntscr.com/li7pl0 

Is there 8.1.0.0 CMI ? lol

**Comment by Zrips** [comment]
Ignore this one, was thinking about pushing up version to 8.1.0.0 then reconsidered as it was not containing anything what would actually do this so changed back to 8.0.22.0 but it looks like i have uploaded "wrong" version... Anyhow, with today's version it will be back on track :)
