### ISSUE TITLE
Request | Stat Signs

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#1065]
So you already have most of the things in place to do this already, my thought was you could add a command, like /stats addsign {placeholder} {number} (/stats addsign %vault_eco_balance% 1) while looking at a sign. When the command is ran the sign will update it's text to the player's name and balance along with the skull above the sign updating to the player's head.

Please let me know if this doable, I know there are many ways of this being done but this is what I came up with.

**Comment by CloudeLecaw** [comment]
what you want is what dynamic sings allready do...
