### ISSUE TITLE
VersionIssues on newest 8.0.22

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#1066]
i think ist just an error in Plugin.yml Right? ;)

```
name: CMI
main: com.Zrips.CMI.CMI
version: 8.1.0.0
```

![image](https://user-images.githubusercontent.com/12080017/48493508-41815480-e82c-11e8-8817-f8fbedbcd053.png)

So may was your plan to Change for next Version to 8.1.0.0? :-) This suggest us a bigger new comming Feature *g*

**Comment by JohOply** [comment]
https://github.com/Zrips/CMI/issues/1064
