### ISSUE TITLE
Question about resetting stats.

### ISSUE THREAD

**Issue by kaimokene** [Zrips/CMI#1071]
Hello. I would like tho know how to properly reset stats so i can make the autorank into a already public server. I know i can delete the stats folder inside the world folder but auto rank still shows that i have that playtime i had before resetting.. It worked for one of my accounts though weirdly. Where does the plugin cache its playtime/stats?

**Comment by kaimokene** [comment]
I renamed the cmi.sqlite.db and it generated a new one and i still had the playtime that i had before resetting. Its real strange i would assume it would be either the stats folder in world and the cmi.sqllite.db i dont have mysql so that cant be it.

**Comment by LogGits** [comment]
Maybe you want `PlayTimeFromStats: false` to rely on cmi for these stats.

**Comment by kaimokene** [comment]
Setting this to true seemed to fix this.

**Comment by kaimokene** [comment]
Spoke too soon it did make it 0 seconds but it doesnt go up at all.

**Comment by kaimokene** [comment]
Could a command that resets all playtime be added? Its only playtime thats not being reset and when puttiing the PlaytimeFromStats: to true it will reset but it will also not count up with /playtime command.

**Comment by Zrips** [comment]
This should have been resolved with latest builds.
