### ISSUE TITLE
Q: Adding Homes To Players

### ISSUE THREAD

**Issue by Kalasky** [Zrips/CMI#1074]
Is there a permission that adds homes to players? Seems to only be a defining number. If a player has 5 homes I should be able to add to that with a permission; i.e. cmi.command.addsethome.3 would add three homes for a total of 8 homes.

**Comment by Kalasky** [comment]
That doesn't answer my question, I am aware of the permissions.

**Comment by TheoRetisch1** [comment]
just edit the permission per player xD

**Comment by Kalasky** [comment]
I am asking if there is a permission node that would add to a players amount of homes. Not sure what's so hard about the question, if you don't know how to help me don't respond at all. Perhaps CMI doesn't even have a permission node for adding homes.

**Comment by user127001** [comment]
@Kalasky 
It's pointless. And it seems not feasible in principle.
Suppose a player has 1 home point by default.
Then you add one more home point to it, and then one more and one more. The list of permissions will look like:
cmi.addsethome.1
cmi.addsethome.1
cmi.addsethome.1
Do you really think a plugin must count the number of permissions nodes?

**Comment by Kalasky** [comment]
That's not what I'm trying to do but okay.

**Comment by Kalasky** [comment]
Why would it not be able to count the number of homes. Just like every plugin, it can read hundreds of permissions on hundreds of players at once. Not sure what your point is.

**Comment by Kalasky** [comment]
For example, just like in other servers their stores have options to purchase more homes. When you purchase more homes from their server store it adds the sethomes to that player's account and adds it on from the number of homes that account already had in-game. This is old stuff, nothing new here. Very surprised none of you heard of this before.

**Comment by user127001** [comment]
@Kalasky 
You are right, there is nothing new here. The current functionality of the CMI plugin makes it easy to do this. But the way you are talking about (using the node permissions to add home points) is not applicable here and in any other plugins. Explore the page [CMI Specialized Commands](https://www.spigotmc.org/wiki/cmi-specialized-commands/) and you will learn many new things.

**Comment by Kalasky** [comment]
I am fully aware of specialized commands. How would this help me?
