### ISSUE TITLE
Feature request: Prevent villager from entering boats

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#1075]
Could you please add the possibility to prevent villager from entering boats? Villagers are neither monsters nor animals, so they are not affected by the current possibilities. This would help me because many people tend to disable Villagers with boats and this is not good for server performance at all. I know it's a very special feature that doesn't necessarily help everyone, but based on what already exists, it shouldn't be too much of an effort. Maybe you find time for it sometime, I would be happy. I enjoy your plugin keep it up!

**Comment by Zrips** [comment]
Will be added with next build
