### ISSUE TITLE
Feature request: Make "Sleeping Speedup" world related

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#1076]
Hejo,

I really love the idea that players can speedup night by sleeping in bed. It would be very helpful if you could make the rather cool feature "Sleeping Speedup" world related. Why? Now there are worlds to build on where the feature is useful, there are worlds to pursue professions where the feature fucks up some players and there are worlds with homemade adventure maps where the feature is highly obstructive. A compromise between these extremes is not possible, so the feature can only be used under adverse circumstances.

**Comment by user127001** [comment]
One question. You using default config?

config.yml:
```Sleeping:```

**Comment by TheoRetisch1** [comment]
Finally implemented in 8.7.7.3 thank you very much!
