### ISSUE TITLE
[QUESTION] /cmi give usage

### ISSUE THREAD

**Issue by kassadGLA** [Zrips/CMI#1077]
What is the syntax ```/cmi give``` command for giving an item with an attached command.

Regards.

**Comment by mercurialmusic** [comment]
Not helpful for what you're asking, but I've just done these with kits.

**Comment by user127001** [comment]
@mercurialmusic Thank you very much! Very useful information. Perhaps this will solve my problems. But for now I will leave my question here.

**Comment by Zrips** [comment]
There is option to save items for future usage. /cmi saveditems so you can save specific item with defined identification and then give it to a player. This is more simplistic approach then creating kit's
