### ISSUE TITLE
Block Particle

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1078]
is it possible that one can also set individual blocks of particles with CMI?

So far, I'm doing a special portal so you can give particle effects on blocks.

Once there was a plugin for it but abandoned. (Https://www.spigotmc.org/resources/block-particles.13877/)
But this one does not exist for the 1.13.x anymore like many other plugins
 Could you integrate something in Cmi?

Example / cmi block particle snow radius 20 ??

This would be so nice

**Comment by Zrips** [comment]
In general you can create portal in that area and disable teleportation or performing commands. Set particle to one you want and you have what you need.
