### ISSUE TITLE
IPBan setting incorrect reason

### ISSUE THREAD

**Issue by delbertina** [Zrips/CMI#1079]
**Description of issue or feature request:**
When ip banning a person it sets the reason as the username of who banned them. Previous IP bans from essentials display as expected, but after switching to CMI this occurs.

ipbanning a user
![https://i.imgur.com/XKUIw6S.png](https://i.imgur.com/XKUIw6S.png)
same ip trying to login with different account
![https://i.imgur.com/6gQRKNf.png](https://i.imgur.com/6gQRKNf.png)
Output from ipbanlist
![https://i.imgur.com/nosdlj9.png](https://i.imgur.com/nosdlj9.png)
(It is the same IP. Scratched it out for privacy reasons oc)

---

**Cmi Version (using`/cmi version`):** 
8.0.22.0
I know this isn't latest, but latest has no relevant changes documented so issue should persist.
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
442 1.13.2
**Relevant plugins (Delete if this isn't needed):** 
EssentialsX (technically relevant to this issue)

**Comment by Zrips** [comment]
Will be fixed with next update.
