### ISSUE TITLE
Giving Items // server hangs/crash

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1081]
**Description of issue or feature request:**
`/item` command can give yourself or someone else items.
When items exceed players' inventory, it drops near player. So far so good.
When a really high number is used, many items drop. This stalls the server load.

Example:
`/item snowball 100000`
Server crashes

Any number above 2304 (full inventory) is useless. Even with a empty invent. Some items which do not stack or stack with only 16 items. So you will never should have a reason to exceed 2304.
CMI should protect itself and the server not to give more items than needed. If higher numbers are required, you could always repeat the command.

**Cmi Version (using`/cmi version`):** 
CMI 8.0.23.0

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Comment by Zrips** [comment]
Good catch, will add hard limit to 36*maxStackSize
