### ISSUE TITLE
/back

### ISSUE THREAD

**Issue by vkaygaming** [Zrips/CMI#1082]
**/back /dback:**
Hi, in regards to cmi /back and /dback, i was wondering if both of these could be combined in /back and if it could prioritise /back over /dback. this is how it used to work in essentials with older versions and i'd like to regain this for the ease of my players.

**Comment by LogGits** [comment]
They are... Check out `/cmi checkperm back`, you can see a "cmi.command.back.ondeath" which allows a player to /back where they died along with regular /back locations 👍
