### ISSUE TITLE
glow and dye

### ISSUE THREAD

**Issue by vkaygaming** [Zrips/CMI#1083]
**/glow and /dye**

/cmi dye command is not recognised
/cmi glow WORKS but for instance /cmi glow red or green or any color does not change the color

**Comment by LogGits** [comment]
Ok Can we get some more info. 

What version of cmi are you using?
What server software are you using(e.g. paper/spigot)?
What version of that server software are you using?

**Comment by LogGits** [comment]
I am assuming this was resolved due to the lack of reply. Please make a new issue if you are still experiencing this.
