### ISSUE TITLE
/setworth Issue

### ISSUE THREAD

**Issue by LeeTheTech** [Zrips/CMI#1086]
So here's what I did:

1. /setworth and set a Dark Oak Sapling to $2.

2. Restarted server.

3. /worth on a Dark Oak Sapling and it was still worthless: https://gyazo.com/c41bbc62b42d75635cb521af49934d37

When I look in the worth.yml file it's listed as you can see here: https://pastebin.com/CVrG9geT

Not sure why only some items are affected but it seems to be all the items that had a number change to a name (Like dyes) 1.12 < 1.13.

Also if you do /setworth on one of those items the worth will show and be set but after a restart it no longer reads as a item with value.

Hope you can find the issue, while you're looking into it, it would be really cool if you could set the worth of a enchant itself. So if I set Sharpness I for $1000, a sword that had Sharpness I on it would gain $1000 in value when sold through /sell.

As always, you're awesome, love this plugin :)

**Comment by SirGoldman-git** [comment]
This is a still a issue with the last updated cmi version from today, could this please be looked into soon, a lot of items are not listed and all my servers run off this eco system. Getting reports daily at this point.

**Comment by Chalwk77** [comment]
I have the same exact issue.

**Comment by SirGoldman-git** [comment]
Its fixed, confirmed!! Thank you! Everyone can sell lapis once more! 💃
