### ISSUE TITLE
Suggestion: /furnace and /anvil

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1094]
It would be great if we could get /cmi anvil and /cmi furnace as an extra perk to give to players, just like /craft and /ec for workbench and enderchest.

**Comment by mrfloris** [comment]
<3 Friendly bump

**Comment by mrfloris** [comment]
please?
This would be quite awesome
_friendly bump_

**Comment by Zrips** [comment]
Anvils and furnaces are allot more complicated to make them work in same as workbench does, possible, but complicated.

**Comment by mrfloris** [comment]
Then don't worry about it. Locking thread.
