### ISSUE TITLE
Temporary saving /tpa and /tpahere locations

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#11]
This would allow players to /tpa and /tpahere other places to specific locations and being able to move away from that location and assure that the other player will be safely teleported to the location they requested. When the /tpa /tpahere request times out they are removed from the map. The map is also cleared upon restarts/reloads of the plugin.

**Comment by Zrips** [comment]
So you want to teleport players to current location on tpa/tpahere location offer? If so, this would open option for situations when players invite another to him while standing over lava pit or any other kill machine, destroy block, wait for him to teleport to you and watch how he is screaming in pain :) Yes, we can add this, but do we really want this?

**Comment by LogGits** [comment]
Oh thats a good point. Don't add this feature it could be lethal.
