### ISSUE TITLE
Kit cooldown issue

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#1106]
**Description of issue or feature request:** I utilise kits with cooldowns and groups. There is a group for ranks. When a user uses a kit it gives them a 4 day cooldown. for some reason this applies to all their kits and not just the main one. So when a player ranks up, If they have a cooldown on their current kit the new rank will also have a cooldown. For this, can we make it so cooldowns only apply to the kit that they used (in a weighted group). This would resolve the issue and also be alot more intuitive then adding a cooldown to the whole group. #644 somewhat has a request for this however I just wanted to make it, its own issue so it's easier to track.

**Cmi Version (using`/cmi version`):** 8.2.0.2

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** build 456 1.13.2

**Comment by Zrips** [comment]
Next update will have adjustments for weighted and kits in same group cooldown handling.
