### ISSUE TITLE
CMI sound

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#1109]
**Description of issue or feature request:** `if `/cmi sound` doesn't have a player or -all argument specified it doesn't send a sound at all to the player. By default, It should play the sound to the player who sent the command if they don't specify -all or a playername. For testing check out `/cmi sound ambient_underwater_enter`, it doesn't play, yet it does say that it played. When you add a playername or -all argument to the end of it, you will hear sound.

---

**Cmi Version (using`/cmi version`):** 8.2.0.2

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** build 456 1.13.2

**Comment by Zrips** [comment]
With next update player name will be optional and will play sound to command sender.
