### ISSUE TITLE
[Bug] Elevator wont always work

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#1110]
**Description of issue or feature request:**

Elevator wont always work. When some sign will work, others wont. And after a server restart the signs that didnt work before might work now. This only occur on the newer updates after 8.1.0.0. Not sure about 8.2.0.0 and 8.2.0.1.

**Cmi Version (using`/cmi version`):** 8.2.0.2

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Paper-459

**Comment by thenullmatrix** [comment]
Completely not working for Spigot 1.13.2 current version as of this post. Cmi version 8.2.2.0. It does say created elevator sign they just do not work with no errors given at all.

**Comment by Zrips** [comment]
Will be fixed with next build.
