### ISSUE TITLE
Minor Slab Error in Mirror

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#1112]
**Description of issue or feature request:**
Mirror isn't quite getting the correct placement for slabs. It's always placing them in the lower half of the block: http://prntscr.com/lobgjr (only using the x axis in this pic, crosshairs are on the "center")

**Cmi Version (using`/cmi version`):** 
8.2.0.2
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
git-Spigot-a1f2566-282dad1 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by mercurialmusic** [comment]
Also noticed that connecting blocks (e.g. walls) don't connect in the mirrored version. I only noticed it with walls but probably also true for glass panes, iron bars, fences, etc. I imagine this would be a much more difficult thing to do, though.

**Comment by Zrips** [comment]
Good point, will fix them including couple other issues related to blocks which should merge with nearby ones, like fences, glass panes, iron bars and so on
