### ISSUE TITLE
[API] Armor stands

### ISSUE THREAD

**Issue by Meldiron** [Zrips/CMI#1116]
I cant find any documenation to API,
how do I work with armorstands? I cant find method like getArmorstandManager()

**Comment by LogGits** [comment]
We dont exactly have an armorstand api. The armorstand manager in cmi is strictly designed for cmi's armorstand gui. You can still edit the armorstand using regular armorstand manipulation in spigot.

**Comment by Meldiron** [comment]
does CMI support executing command when player click on any line of hologram?

**Comment by Meldiron** [comment]
> Look into Interactive Commands using entities. I currently have my banking system set up with holograms where players can click on the hologram to sell items (IC runs the /cmi sell hand command) or click on a different hologram to withdraw items (IC opens our BossShop withdrawals shop).
> 
> The limitation of this is that it would be very difficult to distinguish between lines on a hologram since the armor stands are stacked quite close. It's not the line itself that the IC is attached to, but the invisible armor stand, hence why I use two different holograms to accomplish two different things. But it might get you closer to what you're looking for.

Thanks, I tried that but I keep getting message "Look at entity" no matter where I look. Im sure I was looking at bottom plate of armor stand and it didnt work (Im sure because I used spectator gamemod to look at it)
