### ISSUE TITLE
[Question] About Auto Ranking

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#113]
Hello!
For clarity I haven't purchased your plugin (Yet). 
I currently use AutoRank & lolmewnstats to create a linear ranking system based on players statistics, years ago I requested you bundle a statistics & auto-ranking system into your plugin, and I checked today and you have such a system to allow Automatically ranking a player based on their statistics! One of the major issues I have is that Autorank does not support multiple ranks like having a Donator that can still rank up the linear system, or staff allowing them to rankup using the linear rank system due to autorank only being able to view 1 rank as they use Vault, so if you are donator+rank1 it will only see the highest weight, so the donator rank, so first question:
(I use LuckPerms)

1. Does your auto-rank system allow Keeping a higher weight Rank i.e Donator rank, but allow the player to rank up through a rank system rank1>rank2>rank3 still? Like LuckPerms "Tracks".
2. Since I have an established community and an existing Rank System, if I were to convert they would need to carry off where each player currently is, Would your rank system be able to check what rank they are and know where they are in the ranking process?
3. I remember you saying you read statistics directly from the world statistics folder, is this still the case or do you store statistics in MySQL? I ask for 2 reasons.
    1. I want to be able to create a web UI to display player statistics, I used to have this, I put a lot of time into it, but the lolmewnstats  developer changed the database schema.
    2. At some point in the conversion from minecraft 1.7.2 or 1.8 Mojang messed up converting statistics in the world files, they fully broke it, it was a known bug, so my players statistics in their world file are not exact. Where as my MySQL table of data is.

Thank you.

**Comment by MCTyler** [comment]
Here is a snippet of my Rank System. Works Perfect with LuckPerms and you only need to just add the Groups to LuckPerms. It's Pretty Awesome!
Member:
  Enabled: true
  DisplayName: "&2Member"
  DefaultRank: true
  AutoRankup: true
  NextRanks:
  - Coal
Coal:
  Enabled: true
  DisplayName: "&0Coal"
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Iron
  MoneyCost: 25
  Commands:
  - "broadcast! &6[playerDisplayName] &eleveled up to Prison Coal Rank!"
  - "broadcast! &6[playerDisplayName] &eUse &a/rankup &eto Check your Stats."
  - "execute @a ~ ~ ~ /summon fireworks_rocket ~ ~ ~ {LifeTime:20,FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:1,Flicker:0,Trail:1,Colors:[I;11743532],FadeColors:[I;14602026]}]}}}}"
  - "execute @a ~ ~ ~ /playsound entity.player.levelup player @p ~ ~ ~ 1000000 0"
  - "lp user [playerName] group add coal"
  StatsRequirements:
  - "PlayTime:180"
  - "travel:1000"
  - "MonsterKills:zombie:3"
  - "MonsterKills:skeleton:1"
  - "MonsterKills:spider:1"
Iron:
  Enabled: true
  DisplayName: "&7Iron"
  AutoRankup: false
  RankupConfirmation: true
  NextRanks:
  - Gold
  MoneyCost: 500
  Commands:
  - "broadcast! &6[playerDisplayName] &eleveled up to Prison Iron Rank!"
  - "broadcast! &6[playerDisplayName] &eYou can now Warp to Iron Mine!"
  - "execute @a ~ ~ ~ /summon fireworks_rocket ~ ~ ~ {LifeTime:20,FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:1,Flicker:0,Trail:1,Colors:[I;11743532],FadeColors:[I;14602026]}]}}}}"
  - "execute @a ~ ~ ~ /playsound entity.player.levelup player @p ~ ~ ~ 1000000 0"
  - "lp user [playerName] group add iron"
  StatsRequirements:
  - "PlayTime:3600"
  - "travel:5000"
  - "blocksmined:coal_ore:1000"
  - "MonsterKills:zombie:10"
  - "MonsterKills:skeleton:10"
  - "MonsterKills:spider:10"

**Comment by MCTyler** [comment]
Please fix my Markup, Don't know how to on here :+1:

**Comment by LogGits** [comment]
@FrozenBeard I am going to assume this was resolved because of the wonderful response from @MCTyler. If have any other queries or still have questions regarding CMI please don't hesitate to make a new issue 🙂

**Comment by FrozenBeard** [comment]
So without a clear answer, im going to assume CMI does NOT save statistics in MySQL, I already have Statz as its needed to run AutoRank @MCTyler its a dependency. I was never asking to convert data from lolmewnstats, I asked HOW CMI pulled the data for stats, but as it uses the world file data, it will not be the right data as I mentioned earlier that Mojang screwed up statistics in a world conversion. 

Nobody answers my question no 1.
Nobody answers my question no 2.

So Im not sure why this was closed.

**Comment by Zrips** [comment]
@FrozenBeard CMI is not saving any statistics to data base, that would be overkill. its using official statistics file for all that. We could try to make direct compatibility with Statz plugin to extract statistics from them

**Comment by MCTyler** [comment]
I showed you the answer to Question 1 in my config file, run the command ``` lp group add ``` doesn't take away any rank. CMI doesn't handle Ranks explicitly it just allows LuckPerms to add groups VIA commands. If your looking at some system that's more complicated, GL.

**Comment by AbhigyanKr** [comment]
> I showed you the answer to Question 1 and 2 in my config file, run the command 1 `lp group add` d
> Here is a snippet of my Rank System. Works Perfect with LuckPerms and you only need to just add the Groups to LuckPerms. It's Pretty Awesome!
> 
> ```
> Member:
>   Enabled: true
>   DisplayName: "&2Member"
>   DefaultRank: true
>   AutoRankup: true
>   NextRanks:
>   - Coal
> Coal:
>   Enabled: true
>   DisplayName: "&0Coal"
>   AutoRankup: true
>   RankupConfirmation: false
>   NextRanks:
>   - Iron
>   MoneyCost: 25
>   Commands:
>   - "broadcast! &6[playerDisplayName] &eleveled up to Prison Coal Rank!"
>   - "broadcast! &6[playerDisplayName] &eUse &a/rankup &eto Check your Stats."
>   - "execute @a ~ ~ ~ /summon fireworks_rocket ~ ~ ~ {LifeTime:20,FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:1,Flicker:0,Trail:1,Colors:[I;11743532],FadeColors:[I;14602026]}]}}}}"
>   - "execute @a ~ ~ ~ /playsound entity.player.levelup player @p ~ ~ ~ 1000000 0"
>   - "lp user [playerName] group add coal"
>   StatsRequirements:
>   - "PlayTime:180"
>   - "travel:1000"
>   - "MonsterKills:zombie:3"
>   - "MonsterKills:skeleton:1"
>   - "MonsterKills:spider:1"
> Iron:
>   Enabled: true
>   DisplayName: "&7Iron"
>   AutoRankup: false
>   RankupConfirmation: true
>   NextRanks:
>   - Gold
>   MoneyCost: 500
>   Commands:
>   - "broadcast! &6[playerDisplayName] &eleveled up to Prison Iron Rank!"
>   - "broadcast! &6[playerDisplayName] &eYou can now Warp to Iron Mine!"
>   - "execute @a ~ ~ ~ /summon fireworks_rocket ~ ~ ~ {LifeTime:20,FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:1,Flicker:0,Trail:1,Colors:[I;11743532],FadeColors:[I;14602026]}]}}}}"
>   - "execute @a ~ ~ ~ /playsound entity.player.levelup player @p ~ ~ ~ 1000000 0"
>   - "lp user [playerName] group add iron"
>   StatsRequirements:
>   - "PlayTime:3600"
>   - "travel:5000"
>   - "blocksmined:coal_ore:1000"
>   - "MonsterKills:zombie:10"
>   - "MonsterKills:skeleton:10"
>   - "MonsterKills:spider:10"
> ```

Hey! Your answer really helped me. I am a newbie and I just wanted to know the procedure to add luckperms groups to CMI. Your help would be very helpful for me!
