### ISSUE TITLE
CMI break all shop/ecoomy system after some hours (iconomy)

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#1136]
I just noticed from when i installed cmi user complain with money reset (negative balance and then sometimes money come back) (i am using cmi+iconomy with mysql), i have some error messages with cmi at start and then a massive spam with iconomy

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://gist.github.com/xion87/61e49a79f8189414a66a42a02579f560
```

---

**Cmi Version (using`/cmi version`):**  8.2.1.0

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot

**Server Version (using `/ver`):**  1.8.8

**Relevant plugins (Delete if this isn't needed):** 
Iconomy, ItemFrameShop, Vault, CMI?

**Comment by LogGits** [comment]
Are you still experiencing this issue?

**Comment by xion87** [comment]
nope was solved time ago
