### ISSUE TITLE
 1.7.10 Guis

### ISSUE THREAD

**Issue by MSGAMONG8** [Zrips/CMI#1140]
**Description of issue or feature request:**
All the guis don't show any items in them

---

**Cmi Version:** 8.2.1.0

**Server Type:** Bukkit

**Server Version:** 1.7.10

**Comment by Zrips** [comment]
Tested on 1.7.10 version, GUI do show up. Could you be more specific which ones doesn't work for you?

**Comment by MSGAMONG** [comment]
The kits editor gui, warps gui and portals gui. Only the /inv gui works

**Comment by Zrips** [comment]
Could you send me server jar file or point to exact version you are using? As bukkit is not something i would recommend to use in general as Spigot has better optimizations and better performance then bukkit.

**Comment by LogGits** [comment]
@MSGAMONG Are you still having this issue?
