### ISSUE TITLE
automatic toll door

### ISSUE THREAD

**Issue by LovesAsuna** [Zrips/CMI#1143]
I think CMI. Adding an automatic toll door feature might be great, like a brand lock, just put a billboard on the door and write about it to create it. Players need to pay a certain amount of money to pass

**Comment by LogGits** [comment]
This is a great idea for a plugin, however, it is beyond the scope of this project. This would be a great addition to a plugin like https://github.com/rutgerkok/BlockLocker/issues and https://www.spigotmc.org/resources/blocklocker.3268/

**Comment by LovesAsuna** [comment]
Actually, what I'm trying to say is not a brand lock, but a door for players to have to pay to get through. For the economic development of the server
