### ISSUE TITLE
[Suggestion] Condense missing items

### ISSUE THREAD

**Issue by Drc-DEV** [Zrips/CMI#1145]
Condense bones in bone blocks
Condense clay in clay blocks

**Comment by Drc-DEV** [comment]
In order to make this even better, you could add a separate config for condensed items. "condense.yml" which has a map of all the condensed items in this fashion:

```
BONE:    # < The Result, converted in order
 - BONE_MEAL: 3  #< The possible inputs converted in order
BONE_BLOCK:    # < The Result, converted after the one before this
 - BONE_MEAL: 9  #< The possible inputs converted in order
 - BONE: 3
```

According to the configuration showed above, BONE_MEAL will be converted to BONE first, then BONE_MEAL and BONE will be converted to BONE_BLOCK after.

If you make condensed items configurable in this way or something similar, you will have no problems in future regarding "updating" or "fixing" stuff in the converter, as the end-user can fix it himself.

**Comment by Zrips** [comment]
Condense command will condense/uncondense items if they have appropriate recipes for it. So you simply need to create custom recipes which would condense bonemeal into boneblock and boneblock into bonemeal, same thing can be done with bones and bonemeal.

**Comment by Drc-DEV** [comment]
Thank you!
