### ISSUE TITLE
cmi rt error null.

### ISSUE THREAD

**Issue by DragonisOmega** [Zrips/CMI#1146]
**Description of issue or feature request:**

--- Cmi rt started not working after a system crash dealing with Citizens and denizens.
have had no issues till this mornings 2 am restart.  So I just wanted you to be aware of the error.
thank you keep up the great work.

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/j7ZaXqFs
```

**Cmi Version (using`/cmi version`):** 
v8.2.1.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.13.2

**Comment by LogGits** [comment]
This is resolved in the latest build of cmi (8.2.2.0). If you are still experiencing this issue please reply so i can reopen this.
