### ISSUE TITLE
Shift/Click Open Shulkers Should require container open

### ISSUE THREAD

**Issue by CeIebrimbor** [Zrips/CMI#1149]
CMI’s shulker backpacks are awesome, but many plugins (like GriefPrevention) prevent players from opening containers during combat to prevent gear manipulation. Unfortunately, the Shulker shift/click from CMI skips the container opening event.

**Could you add a container open event in order to shift/click open the shulkers?** 

That will fix all issues with GriefPrevention, PvPManager (or similar) plugins that listen for that event to block container access (or other reasons).

**Comment by mercurialmusic** [comment]
I understand the reason for this, but if added hopefully it would be a config option. My players use this quite a lot and may be in server builds or shops and need to get out currency stored in shulkers in places where they wouldn't have container perms. That would be a significant annoyance.

**Comment by Zrips** [comment]
Added combat timer which can be used to prevent shulker usage while in combat with another player. As there is no simple way to add event reading from other plugins, we will have to go with our own system for this.
