### ISSUE TITLE
Interactive Command not working

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#115]
IC works for regular players in my spawn perfectly fine, but it seems there is a small section or radius where IC cannot be ran by regular players (only ops) for unknown reasons. I cannot figure out why & have tried many things. There is a worldguard set but it covers a large area where IC works anyway. I have ran entitydata commands to remove invis armor stands within this area where IC is not working. Could this be the problem?

**Comment by LogGits** [comment]
Could be two things:
- Check your spawnprotection in server.properties and try setting it to 0. 
- Check the if there are multiple regions /rg info where the IC is in as one of them could have a bad flag configuration.

**Comment by 0xC1A551C** [comment]
I can verify it was spawn protection although I don't know how or why since I was far from 0x0x0.

**Comment by LogGits** [comment]
Fantastic, if you have any other issues please open another ticket 🙂
