### ISSUE TITLE
Flight Charge Not Working / Only works for OP's

### ISSUE THREAD

**Issue by DeadIntermediate** [Zrips/CMI#1151]
**Description of issue or feature request:**
So, I have enabled Flight Charge in the config. I noticed that on the wiki, doesn't really explain about how to use it, example, steps need to take in other a regular player need to. Or the Permission Nodes and command it needs.

I have noticed though when I do have charges when bought either EXP or Money, when in OP mode, it works just fine. Remove the OP and it gone, doesn't work anymore.

**Cmi Version (using`/cmi version`):** 
8.2.1.0

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
git-Spigot-e769fe4-5f5a676 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
There isint real wiki for it because its more or less straight forward. Enable flight charges, recharge yourself with /recharge command and you are good to go. There are no permission nodes needed for it to work.
