### ISSUE TITLE
Mail Command Uses Last Found Keyword

### ISSUE THREAD

**Issue by delbertina** [Zrips/CMI#1152]
**Description of issue or feature request:**

---
/mail send delbertina Hey can you read this?
Actual Command Sent = /mail read delbertina

/mail send delbertina Hey look at this clear!
Actual Command Sent = /mail clear delbertina

I have a feeling the command searches for the last keyword and not the first keyword it finds. It also does the same thing with some parameters for other commands like remove from /mailall. 

---

**Cmi Version (using`/cmi version`):** 8.2.2.0
(was happening before updating too)
**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 474 on 1.13.2
(was happening before updating to latest)

**Comment by Zrips** [comment]
Will be fixed with next update.
