### ISSUE TITLE
/Condense makes unintended items

### ISSUE THREAD

**Issue by delbertina** [Zrips/CMI#1153]
**Description of issue or feature request:**
---

\> be me
\> have stack of diamonds in inv
\> do /condense diamond
\> now have stack of 16 diamonds boots

Works also with /condense leather to leather boots.

I'm guessing it checks for the first result by like " \*diamond\* "" and "diamond_boot" comes before "diamond_block". Tho that wouldn't explain the leather one unless it does that regardless if there is a valid option in the first place. 

Maybe this is the intended behavior? In that case maybe a warning like "click to confirm making 16 diamond boots" like how pay works would help things.

---

**Cmi Version (using`/cmi version`):** 8.2.2.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 474 1.13.2

**Comment by Zrips** [comment]
Yea, this is not intended behavior. Will avoid skipping backwards conversion when condensing by name. This should prevent you from making items which cant be converted back to original form, like diamond boots can no longer be processed to get back diamonds. 
We could consider option to define what items should condense into what as some servers could have option to convert boots back to diamonds, what would make it confusing for plugin to determine if it should condense it into boots or blocks.
But next version should no longer have this issue, atleast for your situation.
