### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by LovesAsuna** [Zrips/CMI#1154]
I think CMI. Adding an automatic toll door feature might be great, like a brand lock, just put a billboard on the door and write about it to create it. Players need to pay a certain amount of money to pass.Actually, what I'm trying to say is not a brand lock, but a door for players to have to pay to get through. For the economic development of the server

**Comment by Zrips** [comment]
Its outside what CMI is, and you could already make this one happen with intractable command and specialized commands combined, by requiring particular amount of money and simply teleporting player to another side. Not as pretty as opening doors, but still achieves same thing.
