### ISSUE TITLE
Error using /unban

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#1157]
If someone uses the unban-command the following error appears:  https://pastebin.com/38HErm96
Hopefully you can fix that issue :)

PaperSpigiot: 1.12.2 #1273
CMI: 8.2.1.0

**Comment by Zrips** [comment]
Strange, this is some what related to recorded players last IP address. Will add fail safe for situations like this. Tho this should not happen in normal situations. My guess would be that you installed CMI on already running server which caused some "missing" data. Anyhow. Should be ok with next update.
