### ISSUE TITLE
Enhancement: Being able to have sethomes accessable using numbers

### ISSUE THREAD

**Issue by Royster0** [Zrips/CMI#1159]
Is it possible to add a feature where a player can type /home 1,2,3.... etc instead of typing out the home name? For example: Player has 4 sethomes called base, spawner, town, maps. They could type /home 2 and it would teleport them to their "spawner" sethome.

Thanks

Royster

**Cmi Version (using`/cmi version`):**
Version 8.2.2.0

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot 

**Server Version (using `/ver`):** 
Ver: 474 1.13.2

**Comment by mercurialmusic** [comment]
They could just name their homes 1,2,3,4.... 

What happens if someone names their third home /home 2? I have several players that number them already. This feature is already better than most other home plugins where you can just use /homes and click. It doesn't need to be super complicated.
