### ISSUE TITLE
[CMI] SEVERE SAVE ERROR WHILE SAVING

### ISSUE THREAD

**Issue by Ew9304** [Zrips/CMI#116]
Hello. I use MySQL for CMI and I am running on Spigot 1.8.8. I hope we can finally get this error fixed once and for all now that it provides more infrormation.

There were no errors or anything, The player went to bed and was AFK all night. Woke up in the morning and logged out, and then I got all these errors in the console. Coincidence? It seems as though CMI is still trying to save player data after logout, because 10 seconds later I get the error.

[12:24:21] [Server thread/INFO]: iamanangrysloth has left the game
[12:24:34] [Craft Scheduler Thread - 823/WARN]: java.lang.NullPointerException

**## Please see this paste for the full error log:**

https://hastebin.com/egoyemonuy.md

**Comment by LogGits** [comment]
@Ew9304 are you still getting these errors on the latest build?

**Comment by Ew9304** [comment]
Not a save error, but a very similar error (I believe) - I made a new issue for it about 30 mins ago.

**Comment by Ew9304** [comment]
Fixed
