### ISSUE TITLE
./tfly ./tgod - On world change

### ISSUE THREAD

**Issue by BiGUNMAN** [Zrips/CMI#1167]
**Description of issue or feature request:**

/cmi tfly (and /cmi tgod, I assume) both reset upon switching worlds (maybe it's a Multiverse thing, or maybe it's a world restriction in the CMI config). An option in the /cmi tfly (and tgod) command to continue operating upon world change, and a secondary option to continue working even though there is a world restriction, would be fabulous. Such as: /cmi tfly (player) 900 --bypassworldrestriction:true --stayonworldchange:true

**Comment by Zrips** [comment]
This should be tested without any other plugin to make sure that its not some 3rd party plugin changing players fly and god modes while changing worlds. When we will know which plugin causes this issue, we can fix it. Until then, cant really do anything about it at this point.
