### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#1169]
https://github.com/Zrips/CMI/issues/848

fix this bug ok?

**Cmi Version (using`/cmi version`):** 8.2.2.0

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.12.2

**Relevant plugins (Delete if this isn't needed):**

**Comment by LogGits** [comment]
Will be testing it soon and hopefully we can reproduce it 👍
