### ISSUE TITLE
Feature request: Clickable welcome message

### ISSUE THREAD

**Issue by ipozow** [Zrips/CMI#1170]
**Description of issue or feature request:**

It would be great to have clickable welcome messages and be able to customize the command when clicking it. Like the msg command when clicking someones' message

**Comment by TheWranger** [comment]
Isn't it already possible to turn CustomText's into JSON messages? If not, that should be added.

**Comment by Zrips** [comment]
You can create it with CustomText and show it to player when he joins server. So yea, @TheWranger pointed out correctly, its already possible to make.
