### ISSUE TITLE
Error with /back

### ISSUE THREAD

**Issue by ludvdber** [Zrips/CMI#1173]
**Description of issue or feature request:**

I deleted a map and I do /back and got it : [https://pastebin.com/uFqt1LvM](https://pastebin.com/uFqt1LvM) then the plugin denies all player commands and displays: "cannot send chat message"

---

**Cmi Version (using`/cmi version`):** 8.2.1.0 and 8.2.3.0

**Server Type (Spigot/Paperspigot/etc):** spigot

**Server Version (using `/ver`):** 1.13.2 CraftBukkit version git-Spigot-a1f2566-6a398ac 

**Relevant plugins (Delete if this isn't needed):** CMI, multiverse-core

**Comment by Zrips** [comment]
Will be fixed with next update. Tho this error would only persist until server restart.
