### ISSUE TITLE
CMI & TheNewEconomy odd interaction fix

### ISSUE THREAD

**Issue by OpalMoonstride** [Zrips/CMI#1174]
This may not quite be a bug but a poor interaction between CMI and TheNewEconomy plugin (economy replacement). If using TNE, admins should make sure the /bal /money /pay or any related economy slash-commands, are set to alias /cmi bal etc. CMI will override part of TNE partially, causing each to partially work, and partially fail.

CMI Alias config: https://pastebin.com/1CxG2WFh

---

CMI plugin version: 8.2.2.0-> 8.2.3.0

**Server Type (Spigot/Paperspigot/etc):** 

Server version: Paper("684bd2a") 1.13.2-R0.1-SNAPSHOT

Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
TNE version 0.1.1.8
TNE build 1Beta118

**Comment by Zrips** [comment]
Alias files is to set your alias to what you want and enable only what you need in your current setup. So you can disable or enable commands which could interfere with another plugin and avoid all this. Its quite complicated to add support for all plugins and prioritize some alias over others depending on what plugin you are using and which plugin should get priority.

**Comment by OpalMoonstride** [comment]
I wasn't talking about aliasing commands. I know how to do that. The problem was that TNE and CMI were both trying to function, and it was causing neither to function properly, and causing the server to crash. You may not be able to support every plugin, but Essentials lets other plugins take priority over its own and worked with TNE by letting TNE take priority. So, tell me again how you can't do the same.

I wrote this issue December 12th, 2018. You responded almost 9 months later, and this was for 1.13. Busy is one thing, but your timing is beyond lacking, and obviously too slow to do anything.

Doesn't matter though, I dumped your plugin. It's a mess. I can't control it enough for it to be stable, I can't fix it because you've gone so far as to obfuscate the error messages, and I can't disable parts which are inadequate for my purposes. Now, it shows that it's even worse to use since you take 9 months to answer an issue, and you closed it without clarification, when you didn't even understand the problem. I also get the impression you expected me not to answer and just go away since you waited so long. 

I hope you'll at least consider this a review of your plugin.
