### ISSUE TITLE
New sit feature for carpets breaks existing stairs

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1175]
**Description of issue or feature request:**
The new `CarpetsAsChairs` function got the stairs mixed up. To be able to sit on stairs requires `SlabsAsChairs: true` in order to use `StairsAsChairs: true`.
If slab is false, players can no longer sit on stairs.

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
none
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
This config makes players can sit on slabs but not on stairs:
```
  SitOnStairs: true
  StairsAsChairs: true
  SlabsAsChairs: false
  CarpetsAsChairs: false
```
This config makes players can sit on slabs and on stairs:
```
  SitOnStairs: true
  StairsAsChairs: true
  SlabsAsChairs: true
  CarpetsAsChairs: false
```
This config makes players can still sit on slabs but not on stairs:
```
  SitOnStairs: true
  StairsAsChairs: false
  SlabsAsChairs: false
  CarpetsAsChairs: false
```
---
**Cmi Version (using`/cmi version`):** 
8.2.4.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.13.2

**Comment by Zrips** [comment]
you are correct, there was some misspell in code which messed things up slightly, should be ok with next update.
