### ISSUE TITLE
[bug] Players can no longer sit after CMI upgrade.

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1178]
(repost from forum)
Players have the permissions in GroupManager, and the configuration yml file has is set to true I have not touched it, we've had this since 1.12.2's version 8.x of CMI. After last night's upgrade this stopped working. Players can still type: /sit, and that works. But empty-handed right clicking on stairs (valid ones, with nothing above them, etc) no longer works.  There is no error in the console.

```
- cmi.command.sit
- cmi.command.sit.stairs

SitOnStairs: true

>about
[00:29:19 INFO]: This server is running CraftBukkit version git-Spigot-140f654-b446cb5 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[00:29:19 INFO]: You are running the latest version
>about cmi
[00:29:20 INFO]: CMI version 8.2.4.0
[00:29:20 INFO]: Powerful server management tool
[00:29:20 INFO]: Website: https://www.spigotmc.org/resources/content-management-interface.3742/
[00:29:20 INFO]: Author: Zrips
>```

**Comment by Zrips** [comment]
All seems to work properly. Don't know from which version you upgraded, but there was additional addition to sit feature to limit range to 3 blocks to avoid some possible issues with jumping on chairs on which you should not have option to sit on. So you need to stand relatively close to chair to sit on it. Test it by standing near block. But will add option to define range for convenience sake.

**Comment by mrfloris** [comment]
Okay, I understand that. I will also try to upgrade later today when nobody is online to see if that resolves it. We haven't had issues with sitting on chairs regarding distance. I could run up to it, right click - and boom I am on it. It's like the action is completely cancelled or something. 

Here's a video of how it is right now one of our live servers, where it doesn't work at all on any chair, no blocks above it, nearby, etc. And I can be far away, nearby, on top of behind the stairs, any of them, and do not even get a lucky right click-sit, it's a 100% failure rate. Whereas usually, like I said, I get on it no problem. 

https://youtu.be/qgobqDEWSMw

I hope this video helps.
