### ISSUE TITLE
feature request: default nameplates

### ISSUE THREAD

**Issue by MothGirlMusic** [Zrips/CMI#1187]
your plugin allows a command to set nameplates [names shown above a players head]
 however it doesn't allow you to se a default prefix. i would like to be able to set a default prefix to show ranks and stuff before a players name.. above their head. thank you!

**Comment by mercurialmusic** [comment]
I'd definitely vote for this one. We currently use NametagEdit, which adds the prefix well enough. But bonus points if you're able to do it with prefix and nickname (in color!). :)

**Comment by MothGirlMusic** [comment]
thats exactly what we use, and exactly the reason i'm asking for this as well...  it'd be awesome if it's all done with CMI... less plugins.. less lag.. everyone wins.

**Comment by MothGirlMusic** [comment]
plus CMI already supports nameplates, why not make a "default" setting for it?

**Comment by user127001** [comment]
[TAB REBORN](https://www.spigotmc.org/resources/tab-1-8-x-1-13-2-reborn.57806/)

**Comment by MothGirlMusic** [comment]
> TAB REBORN

i dont think you read the issue. we already have a working plugin. we're asking for a CMI feature. to be able to have less plugins in our servers and since CMI already controls tablist too, then it should also control nameplates. which it does. but theres no "default option"... plus what you just linked me is for "tablists" only. i'm looking for nameplates.

**Comment by FrozenBeard** [comment]
+1
