### ISSUE TITLE
CText Permissions seems broken

### ISSUE THREAD

**Issue by Endothelium** [Zrips/CMI#1188]
Hello, it seems the permissions for the command cmi ctext is broken

My user doesnt have the permission `cmi.command.ctext`
My user does have the permission` cmi.command.ctext.jobs`

 When i enter /cmi ctext, the chat display all my ctext available.
When i enter /cmi ctext plot (for example), it display the ctext plot.txt, even i have only the permission ` cmi.command.ctext.jobs`.

I tried to set the permission `cmi.command.ctext` to false, but when i do this, i cant read any ctext, even if i have ` cmi.command.ctext.jobs` to true.

I am using spigot 1.13.2 and CMI 8.2.6.0

**Comment by Zrips** [comment]
in ctext editor you have [+] or [-] signs, find one which will set permission requirement to see and use that ctext. Without it anyone with base command to access ctext can see and use all of the ctext's
