### ISSUE TITLE
Attachcommand Breaking

### ISSUE THREAD

**Issue by log404** [Zrips/CMI#1192]
**Attachcommand limited use breaking:**
---

/cmi attachcommand
Breaking if you set to 1 limited use.
If I set limited use anything above all works but the last use.

---

** --------------------------------------------------
CMI plugin version: 8.2.6.0
Server version: Spigot 1.12.2-R0.1-SNAPSHOT
Vault version: 1.6.11(+)
--------------------------------------------------**

**Comment by Zrips** [comment]
Will be fixed with next update
