### ISSUE TITLE
Suggestion for Ctext advancements

### ISSUE THREAD

**Issue by log404** [Zrips/CMI#1193]
CText Advancement 
---

/cmi ctext (ctext:id) open:player target:player

target:player so you can do /cmi ctext info target:notch

What it will do is gather all that players placeholdersapi/cmi placeholders and send it to calling player.

---

 --------------------------------------------------
CMI plugin version: 8.2.6.0
Server version: Spigot 1.12.2-R0.1-SNAPSHOT
Vault version: 1.6.11(+)
--------------------------------------------------

**Comment by Zrips** [comment]
This was implemented in recent updates. Tho with simpler format. **/cmi ctext [cText] (playerName/all) (sourcePlayer)**
