### ISSUE TITLE
Feature Request : Custom Recipes 

### ISSUE THREAD

**Issue by thunderlight411** [Zrips/CMI#1195]
**Special items (custom NBT-tag) for use in recipes:**

Will be nice to use special items with custom NBT tag to be used in a custom recipe.
The plan is using for example a enchanted paper with a sword to gain a sort of legendary item.

Lets say we sell the user a paper with Sharpness 50 and let them use it combined with a wooden sword. to craft a wooden sword with special enchants.

when we craft the same item now the output have the correct enchants and NBT data but the input is not checked for NBT information.
So a plain paper with a wooden sword generate the same output as a enchanted paper.

not sure if this is a bug or not yet implemented but it will be nice if this can be done

**Comment by Endothelium** [comment]
Please add this feature

**Comment by Zrips** [comment]
Currently CMI used vanilla recipe handling, what means that it can only make recipes based on materials only as ingredients, no names, no lore, no nbt data will be recognized. For this to start working we would need completely separate engine to handle recipes with custom stuff on them. Not a priority at this point.

**Comment by mrfloris** [comment]
> Not a priority at this point.

pout
