### ISSUE TITLE
Enchantments Deleting

### ISSUE THREAD

**Issue by log404** [Zrips/CMI#1196]
Enchantments Deleting

---

[video explains it all](https://drive.google.com/file/d/1BqFBjhhH6yE9UnOB4MbgxZDuF-_xcUEt/view)

---

** --------------------------------------------------
CMI plugin version: 8.2.6.0
Server version: Spigot 1.12.2-R0.1-SNAPSHOT
Vault version: 1.6.11(+)
--------------------------------------------------**

**Comment by DragonisOmega** [comment]
kind of the same issue but mine happens when I go to another world.
it doesn't remove them only changes them.
https://www.youtube.com/watch?v=Ff6gJlXn-WU

**Comment by Zrips** [comment]
That's isint really explaining allot. Did you tested with only CMI present? Do you have any other plugin which could handle item enchants? 
As at this point is not been reproduced so issue origins are unknown.
