### ISSUE TITLE
[urgent] [bug] "last" command not working on /attachcommand 

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1197]
8.2.6.0 of CMI breaks attach commands.

The "last" command isn't executed. 
Which means if you have a stick with 1 usage, it just "goes away" the console says shadow command executed, but the thing it is supposed to do doesn't work.

If you have a stick for example with 3 x usage, to give someone an mcMMO level. They get it twice, the third time the stick goes away - they dont get the level. 

This is kinda ruining the christmas event where rare and unique things on the server suddenly dont work and we get loads of complaints.

Kinda irritating..

I installed spigot 1.13.2 latest nightly, and latest download from this thread, just 30m, ago, made a new server to test on, and can reproduce the issue, so it's not caused by other plugins. 

It worked before 8260.

https://youtu.be/5GXHQRTStDM

https://www.spigotmc.org/threads/20-off-sale-cmi-240-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much.48111/page-281#post-3256902

**Comment by mrfloris** [comment]
Oops, I just spotted this was reported before, i looked, but guess i overlooked it;
https://github.com/Zrips/CMI/issues/1192

**Comment by Zrips** [comment]
Reproduced and cause was found, will be fixed with next update
