### ISSUE TITLE
/nick works a bit funky

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#12]
I'm setting CMI up on a test server first before moving it to the main server and I noticed /nick kinda acts a bit weird

For example if you did /nick &cName

The name would be
< Name >

But the > arrow at the end would also be &c. And then the chat is also &c.

If you do /nick &cName&r it works correctly.

Is there a way to perhaps add the &r at the end of every nick command or something like that?

**Comment by Zrips** [comment]
Its all depends from your chat controlling plugin, check its format and reset all color codes with same &r after players name. There is no good reason to add that reset to nickname it self
