### ISSUE TITLE
Console error 1 minute after player logs in

### ISSUE THREAD

**Issue by Ew9304** [Zrips/CMI#120]
Spigot 1.8.8 - CMI 7.4.2.1

No errors all night, Player logs in and not even 1 minute later gives an error.

https://pastebin.com/W2SmyTPb

**Comment by Ew9304** [comment]
Okay so this error seems to happen on every player login or logout 

https://pastebin.com/nq254CpU

**Comment by LogGits** [comment]
Are you getting this error on version 7.4.3.0?

**Comment by Ew9304** [comment]
Seems to be fixed.
