### ISSUE TITLE
[Suggestion] Tab-complete nicknames and @names

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1200]
Per thread:

https://www.spigotmc.org/threads/20-off-sale-cmi-240-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much.48111/page-281#post-3257471

`Is there a way to allow people to tab-complete nicknames for players?`

`Additionally, I start using @name more and more in the chats, it would be cool if we could @MrF[tab] to get @mrfloris :)`

**Comment by Zrips** [comment]
Fun story... This was a actual feature on 1.12 and older versions, while 1.13+ servers broke it...  Will investigate if i can fix it from my end.
