### ISSUE TITLE
[Suggestion] World support for /cmi killall

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1201]
Could we get support for killall to run as a attachcommand / console !cc! so we can hook it to a adminShop or attach it to an item, and run it for all worlds, or just 1 world.

We want to let players buy the option to killall phantoms either around them, for all players, in the world they are, defined world, or all worlds. 

https://www.spigotmc.org/wiki/cmi-killall/

example: 

console: 
cmi killall -r:60 -p:[playerName]-w:wilderness -lightning -m:phantom
To allow killing phantoms around playername in wilderness world

Kill all mobs in world Wilderness
cmi killall phantom -w:Wilderness

Kill all phantoms around player BOB in world General
cmi killall phantom -w:Wilderness -p:[playerName] -r:60

Kill all phantoms for all players, in the whole of the world General
cmi killall phantom -w:General

**Comment by Zrips** [comment]
Next update.
