### ISSUE TITLE
remove showing coordinates with /cmi inv

### ISSUE THREAD

**Issue by melinstagibson** [Zrips/CMI#1202]
can we please remove the coordinates from the /cmi inv command. 

there are so many other alternatives, i dont see how they need to be shown there, i cant hand it out like this on a survival server. 

or atleast a seperate permission node like cmi.command.invsee.coordinates

**Comment by Zrips** [comment]
We can add extra permission for this. But why would you give access to this command for regular players in survival mode?

**Comment by melinstagibson** [comment]
i have a "helper" rank on the server who is  allowed to play like a normal player but has some permissions to try and catch cheaters, invsee included.
i cant have it show coordinates tho because its a vanilla/raid/grief server

thanks, would be amazing to see it so i wont have to find a workaround :)

**Comment by Zrips** [comment]
@melinstagibson 
Latest updated had new permission added cmi.command.inv.location which is required now to see players location in GUI
