### ISSUE TITLE
CMI Auto removes " from commands.

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#1207]
**Description of issue or feature request:**
CMI auto removes quotes from the eventcommand or customalias when ran. For example: I need the use the CommandDispatcher to dispatch commands across my network. For it to work I need to quote my commands that contain spaces.

- dispatch all "cmi broadcast test"

When this is ran using the customalias or eventcommand only the "CMI" part is ran due to the quotes being removed. 

**Cmi Version (using`/cmi version`):**  8.2.8.0

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  1.13.2

**Comment by Zrips** [comment]
Could not reproduce this one. Could you elaborate more. Is this for any command you perform, even like **cmi msg [playerName] dispatch all "cmi broadcast test"** or its only for this dispatch command?

**Comment by 0xC1A551C** [comment]
> 
> 
> Could not reproduce this one. Could you elaborate more. Is this for any command you perform, even like **cmi msg [playerName] dispatch all "cmi broadcast test"** or its only for this dispatch command?

I havent tested it on any other command, but so far only the dispatch command. The quotes are suppose to be there for a command containing spaces, but it does not work with CMI as CMI seems to remove the " quotes when the command is ran as a customalias or evencommand. 

It works when you add the msg and I see the quotes, but doesnt work when its just the dispatch command without cmi msg for some reason
