### ISSUE TITLE
Custom recipes - Eggs + permissions

### ISSUE THREAD

**Issue by JohnStriker** [Zrips/CMI#1208]
Hi there I have problem with custom recipes. 
I have "egg" with custom name and lore. If I use this egg as part of recipe in custom recipes editor, save it and then look for recipe, there is normal egg. What's the problem? Or custom recipes doesn't support custom items as part of recipe?

Is it possible to allow using custom recipes only for specific players? Is there any permission for it? If no, can you add this feature?

---

Cmi Version 8.2.8.0

Spigot

1.13.2

**Comment by Zrips** [comment]
For time being you cant use items with custom data attached to them as part of recipe. Recipe ingredients are been determined by item material type, nothing more. Blame Mojang for not making more advanced recipe system.
