### ISSUE TITLE
Mushroom Cow Egg - Works on Spawner

### ISSUE THREAD

**Issue by BiGUNMAN** [Zrips/CMI#1210]
**Description of issue or feature request:**
The Mooshroom cow isn't blocked from egg-clicking on a spawner. All other mobs are blocked 100% from what we've tested.

Double checked, even denied: cmi.egginteract.* to all players and the issue continues.
---

---

**Cmi Version (using`/cmi version`):** 
8.2.5.0

**Server Type (Spigot/Paperspigot/etc):** 
1.13.2

**Comment by Zrips** [comment]
Good point, it seem that Mojang cant decide if its a Mooshroom or Mushroom... Both values are valid while both are invalid depending from situation... Will be fixed with next version
