### ISSUE TITLE
Tablist AFK system

### ISSUE THREAD

**Issue by ConfuseN** [Zrips/CMI#1211]
**Description of issue or feature request:**
I would appreciate it if we could get a way to notify is a player is AFK or not on the tablist.
Maybe by replacing their rank with the tag [AFK] or graying out there name. I use to have a datapack that does this, however it was incompatible with your Tab list functionality. I would love to have you natively support such a feature!

Thank you!

**Comment by CypherPhyre** [comment]
This can already be accomplished by adding %cmi_user_afk_symbol% to the PlayerName section of the GeneralFormat or GroupFormat in the config.yml

This is how it looks for the one I use:
GroupFormat:
    '1':
      PlayerName: '&6%cmi_user_afk_symbol% &2{&r[playerDisplayName]
