### ISSUE TITLE
Relog Problem for Nether & End

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#1213]
Today we recogniced an error on our Server with Nethers and Ends of all world

**Description:**
- You went to a Nether or End world
- You log out
- You try to relog
**Result:**
First you see the the world for one secound
![25-12-_2018_21-57-33](https://user-images.githubusercontent.com/12080017/50427051-78bc3a00-089d-11e9-9589-595fe3bbe73e.jpg)

after it you just see the heaven anymore and you cant move
![25-12-_2018_21-55-32](https://user-images.githubusercontent.com/12080017/50427048-722dc280-089d-11e9-8a6c-a51df8e1389a.jpg)

![25-12-_2018_21-42-27](https://user-images.githubusercontent.com/12080017/50427056-8d003700-089d-11e9-9081-f4431b4902f9.jpg)

Also relog did not help because the error just is back then.

- We got this issus with CMI version 8.2.8.0 (with MySQL Database and latest Spigot 1.13.2 Server)
- We are not able to reproduce this on the TestServer on the HDD (may because there the Flatfile is used? :3)
- We could "fix" the problem with downgrading to Version 8.2.0.2

The Error was also present in versions before 8.2.8.0

We also have no cloue what causes this error, Just that with version 8.2.0.2 it does not appear.

May one of the Updates bring in this error?

**Comment by Blueeyestar** [comment]
I have the problem too ... since I can not use the current version of Cmi anymore.

**Comment by Zrips** [comment]
Issue with skin handling on none primary worlds. Should be ok with new version.
