### ISSUE TITLE
Broken beds

### ISSUE THREAD

**Issue by BeeRando** [Zrips/CMI#1214]
I'm not sure if this is a bug, or just an unintentional setting. Please make it so that when a bed is broken, the players home is removed. As it stands, someone can set a bed spawn right beside someones city, and raid them endlessly. If their bed is broken, they can still tp to that spot anyways. Breaking beds to remove peoples homes is a big part of survival pvp servers. Thanks! <3

**Comment by Zrips** [comment]
This should be working now.
