### ISSUE TITLE
Enchant names Disappearing

### ISSUE THREAD

**Issue by DeadIntermediate** [Zrips/CMI#1215]
**Description of issue or feature request:**
When players have a high enchanted pickaxe, name names would disappear and only would seems like they only have one enough, although, the other enchants are still on the tools.

---

---

**Cmi Version (using`/cmi version`):** 
http://prntscr.com/lzorrb

**Server Type (Spigot/Paperspigot/etc):** 
Spigot 

**Server Version (using `/ver`):** 
http://prntscr.com/lzorxo

**Comment by Zrips** [comment]
Would be nice to see picture of example how that looks like and what enchantment it had on it

**Comment by DeadIntermediate** [comment]
I tried to create a gif of it, but not it shows it working properly. 

It randomly happens. I'll see if it happens again.
