### ISSUE TITLE
[Request] AFK Reason

### ISSUE THREAD

**Issue by MrMorganCz** [Zrips/CMI#1216]
Would it be possible to add a placeholder for afk status? I would lik write /afk <reason> so that it is displayed Player <player> is afk now afk <reason> ...

**Comment by mrfloris** [comment]
There is

- %cmi_user_afk%
- %cmi_user_afk_symbol%

It would be nice if AFK reason was used a bit more. 

When someone does /afk reason, it would be nice if the chat displays the reason, and that we can use it in TAB with %cmi_user_afk_reason% (even if it is truncated to x characters) and stuff like that.

+1
