### ISSUE TITLE
[request] Order and edit of interactive commands

### ISSUE THREAD

**Issue by FaMa91** [Zrips/CMI#1219]
Hi,
we use your plugin from some months and we love the huge amount of features that CMI offers, so we would like to ask you some more improvements.
I'll open a new thread for each request, thank you for your work!

Interactive commands are very useful but somehow difficult in management when the amount of them increase significantly, so the request is to give them an order when the list is shown, alphabetically, in order of creation or what you prefer, the point is to have a clue on where to find the interactive command.

In addition to that we would like to have a command to edit directly the IC like for kits (cmi kiteditor edit KITNAME), in this way, if someone knows the name of the IC he doesn't need to find it in the list.

Thank you in advance!

**Comment by Zrips** [comment]
Its now ordered by distance if it contains any blocks attached to it. And if not, then by creation time. And you can edit them with /cmi ic commands [icName]
