### ISSUE TITLE
[Bug] Mirror 

### ISSUE THREAD

**Issue by Harveyplays02** [Zrips/CMI#1224]
**Description of issue:**
Mirror function does not work correctly on 1.12.2 servers with the latest update of CMI. It also hasn't been working for the past few versions. The issue is that it breaks blocks correctly, but it doesn't place blocks at all. It shows no errors in console.

---

**Cmi Version (using`/cmi version`):** 8.2.8.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.12.2

**Comment by Zrips** [comment]
Next update should fix this issue. And if it still happen, would be nice to know which blocks in particular are not working as now it should not work for some rotatable blocks but generic ones should work just fine.
