### ISSUE TITLE
Alias editor enhancement/simpler commands

### ISSUE THREAD

**Issue by BeeRando** [Zrips/CMI#1229]
Could we either a) Simplify commands, or B) Have a way to edit them with the alias editor? TO my knowledge, I can edit commands like /cmi spawn, to just be /spawn. However, I can not edit something like /cmi seen name, to just be /seen name, because there's no way to add like [playerName] or whatever, a target player, into the alias editor.

Here are some commands that I'd suggest being shortened. This is all so we don't have to keep telling people the commands and explaining it to players/new players, which gets very tiresome overtime. 

 - /cmi seen name, to be /seen name
 - /cmi msg name, to be /msg name
 - /cmi tpa name, tp be /tpa name
 - /cmi balance name, to be /balance name, /money name
 - /cmi money pay name number, to be /money pay name number 
(ik you can do /pay name, but also having it be consistent with the usage of the word money makes it simpler for people, people instinctively try /money pay name all the time on my server, cuse thats what they're used to)

If there was a way to alias edit target names into the command, so i could just do /cmi aliaseditor new seen [playerName]-cmi seen [playerName] for example, that'd make this so much easier. Unless there already is and I don't know about it, but I couldn't find anything about it on the support pages.

**Comment by Zrips** [comment]
@BeeRando 
**/cmi aliaseditor new seen-cmi seen $1-**
Which would mean that anything what goes after **/seen** will be included into **/cmi seen** command, in example **/seen Zrips** will translate into **/cmi seen Zrips** same thing can be applied for multiple variables like **/cmi aliaseditor new ms-cmi msg $1-** and after performing **/ms Zrips Hey hou!** it will result into **/cmi msg Zrips Hey hou!**
You can even switch variables places **/cmi aliaseditor new test-cmi msg $2 $1** and if you would do **/test one Zrips** it would result into **/cmi msg Zrips one**
