### ISSUE TITLE
[Request] Making FlightCharge set to False as default for players, maybe in config

### ISSUE THREAD

**Issue by SgtMorrigahnGaming** [Zrips/CMI#123]
I would love to see that Flightcharge would have it set to false as the default option, or having the possibility to set it to false in config. On our server, we are getting alot of players complaining about forgetting to turn it off, as when using Elytra, or double jumping, or doing a higher falljump, flightcharge is depleting whatever charge they have earned.
It's been requested many times if it would be possible to have it set as default off, and then players can activate it when they want to!
Biggest issue, apart from the jumping 4-5 blocks or more, is that most players are using the doublejump, rocket to fire up the Elytra. But by doing this, Flightcharge activates, and depletes, when they start hammering the keyboard to turn it off :D

**Comment by Zrips** [comment]
Will be added with next update
