### ISSUE TITLE
Suggestion: Command costs

### ISSUE THREAD

**Issue by BeeRando** [Zrips/CMI#1233]
Could we have the option to add a cost to a command? We enter the command we want in a section and the price for that command beside it. Essentials x has this pretty simply laid out in its config, and I'd love to see CMI have it also! It'd be a fantastic addition. Thanks! <3

**Comment by splops** [comment]
I think with customalias you could, check https://www.spigotmc.org/wiki/cmi-specialized-commands/

Theres a condition that sais moneycost or something

**Comment by BeeRando** [comment]
but how do I do that. Like lets say I want to add a cost of 5 coin to tpa, what would I do?I edit the alias.yml commands? or ingame editor? And with what? Like where do I put  hasmoney:[amount]!

**Comment by splops** [comment]
Remove the alias of tpa, add with customalias tpa command and put there moneycost:amount! tpa $1-

**Comment by splops** [comment]
If not working, +1 to your idea

**Comment by BeeRando** [comment]
So ingame? I type /cmi aliaseditor new tpa $1--moneycost:amount! cmi tpa $1-
