### ISSUE TITLE
[Request] attached command with cooldown 

### ISSUE THREAD

**Issue by SeanWalk** [Zrips/CMI#1235]
**Description of issue or feature request:**

---

hope /cmi attachcommand can use cooldown.

not only used times but also give cooldown to perform command
```

```

---

**Cmi Version (using`/cmi version`):8.2.8.0** 

**Server Type (Spigot/Paperspigot/etc):paper488** 

**Server Version (using `/ver`):1.13.2**

**Comment by splops** [comment]
I think you could with "cooldown:TIMEINSECONDS! <whatever thing>"

Example apple with attached command: /attatchcommand cooldown:60! asConsole! Cmi feed [playerName]

**Comment by SeanWalk** [comment]
> I think you could with "cooldown:TIMEINSECONDS! "
> 
> Example apple with attached command: /attatchcommand cooldown:60! asConsole! Cmi feed [playerName]

No you cant use Specialized Command in attatchcommand.
i had try that. it doesn't work

**Comment by Zrips** [comment]
Next update.
