### ISSUE TITLE
CustomAlias Bug

### ISSUE THREAD

**Issue by QuiquePineyro** [Zrips/CMI#1237]
Hello,

I want to report a bug, the bug its about the CustomAlias, I created a new command that have many commands in it and when I execute in the server as a player it works perfect, but the matter is I cant execute the command in other players, for example I create the command /test, that command have many other commands in it like execute titles, sounds and launch, but now I want to use the command /test in other player doing /test (player), but this commands doesnt work, I been testint it and the command just ejecute to the (player) if the CustomAlias only have a command, not many

Im trying to execute this command to other players: 

CustomAlias:
rtp:
Cmds:
- fromConsole! cmi sound item_bottle_empty -v:2 [playerName]
- fromConsole! cmi titlemsg [playerName] &e&l3
- delay! 1
- fromConsole! cmi sound item_bottle_empty -v:2 [playerName]
- fromConsole! cmi titlemsg [playerName] &e&l2
- delay! 1
- fromConsole! cmi sound item_bottle_empty -v:2 [playerName]
- fromConsole! cmi titlemsg [playerName] &e&l1
- delay! 1
- fromConsole! cmi sound entity_generic_explode -v:2 [playerName]
- fromConsole! cmi launch [playername] p:2 a:90
- delay! 1
- asPlayer! rc

And this command works well because only have one line:

CustomAlias:
ec:
Cmds:
- endc open $1-
  (I use the plugin EnderContainers for this command)

---

**Cmi Version
------------------------------------------------------------------------------
Versión de CMI: 8.2.2.0► 8.3.0.0
Versión del Servidor: Paper(1581) 1.12.2
Versión de Vault: 1.7.1-b91(CMIEInjector)
------------------------------------------------------------------------------ 

**Server Type: Paperspigot

**Server Version: 1.12.2

**Comment by Zrips** [comment]
Its not a bug in particular. As [playerName] will insert players name who performed command, so in case you performed it from console, this is not possible to be replaced. So in case you would want to perform this command on some one else with provided name, set it like

- fromConsole! cmi sound item_bottle_empty -v:2 $1
- fromConsole! cmi titlemsg $1 &e&l3
- delay! 1
- fromConsole! cmi sound item_bottle_empty -v:2 $1
- fromConsole! cmi titlemsg $1 &e&l2
- delay! 1
- fromConsole! cmi sound item_bottle_empty -v:2 $1
- fromConsole! cmi titlemsg $1 &e&l1
- delay! 1
- fromConsole! cmi sound entity_generic_explode -v:2 $1
- fromConsole! cmi launch $1 p:2 a:90
- delay! 1
- fromConsole! cmi rt $1

In this case /rtp Zrips will replace $1 with Zrips and perform commands from console. Keep in mind that current build doesnt have a way to determine which player should perform command as himself if you are performing alias from console. Will work on that one.
