### ISSUE TITLE
Feature Request. Remove the cmi before commands

### ISSUE THREAD

**Issue by cvaughn55** [Zrips/CMI#1239]
**Description of issue or feature request:**
I would suggust an option to remove having to type cmi before all commands. My server only has CMI as a server management system and it is annoying to not beable to just do something like /compass but instead be forced to do /cmi compass and ect. Never had do have a prefix like that back when we used Essentials, and I feel most players are confused because it is a bit illogical to have cmi as a prefix unless those commands conflict with some other super common command already on a server which is unlikely
unless the server is running multiple management plugins which makes no sense

**Comment by splops** [comment]
Edit the alias.yml file, thats all :)

**Comment by Zrips** [comment]
Yea, what splops said, you have 2 options, enable short alias in alias.yml for wanted commands or create your own with /cmi aliaseditor new compass-cmi compass $1-
