### ISSUE TITLE
blockstatus error

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#1240]
If you try the command /cmi blockstatus the attempt fails and an error appears in the log. The same applies to the /cmi blocknbt command. 

Error: https://pastebin.com/pKYVmkYB
Paper 1.13.2 - 489
CMI 8.2.0.0

**Comment by Zrips** [comment]
Should be fixed in latest build.

**Comment by TheoRetisch1** [comment]
Nice thank you!
