### ISSUE TITLE
[Bug?] /cmi sell gui takes renamed items and special items as regular

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1241]
It appears if you have renamed and custom items, items with lores etc, like a diamond called "super special diamond" with a lore of "dont lose this" and you put it in the /sell gui, that it will sell, because it gets recognized as a regular diamond. 

Some users tend to shift click or use those mods etc. And they end up in there, some items that don't sell like a bottom slab or other worthless stuff returns, but unique items either disappear, or they sell as a regular diamond (instead of ending up back in the inventory).

Could this be a bug, or is this on purpose? It would be nice if it recognizes it's not the 'raw' vanilla item and then refuse to sell it. 

Latest CMI and latest spigot. 1.13.2

**Comment by Zrips** [comment]
Its not on purpose or a bug. Its just simply checks items material and determines its price, if its worthless, it will be returned to owner, if its not, then it will be sold. We could maybe add extra checks, like prevent selling with particular lore in them or something in between those lines.

**Comment by mrfloris** [comment]
I would even be happy with a blacklist of sorts, where i can add itemname,itemlore items so things with words like *tokens* on them would not get sold. That would already solve 75%

**Comment by razorrider7** [comment]
This is already a feature in the config.yml, as far as I know it still works in 1.13.2...
```
Worth:
  # Defines lore that will prevent an item from being sold using /cmi sell.
  # Color codes and capitalization are being ignored
  BadLore:
  - Cannot be sold
```

**Comment by mrfloris** [comment]
> This is already a feature in the config.yml, as far as I know it still works in 1.13.2...
> 
> ```
> Worth:
>   # Defines lore that will prevent an item from being sold using /cmi sell.
>   # Color codes and capitalization are being ignored
>   BadLore:
>   - Cannot be sold
> ```

🐙 whattttt .... will go and test this as soon as i can! thank you, wow, can't believe i overlook, OH wAIt, there's only 500 features in this plugin :D haha

**Comment by Zrips** [comment]
When even developer cant remember features of his own plugin...
