### ISSUE TITLE
[Bug?] Elytra + sitting on stairs allows players to look through the world

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1242]
Latest CMI, when players are doing the action to fly and end up sitting on a chair, they end up being able to see through the world and find mineshafts, dungeons, etc. Obviously the cheatos abuse this to get a headsup and fly under the xray radar basically.

I'd appreciate it if this could perhaps be fixed? maybe if they 'fly' with elytra and try to sit, that it wont let them, or whatever is the combo causing this. 

```
- playerX: /cmi reply you know how you can sit, right?
 - playerX: /cmi reply if you fly with your elytras while trying to sit, your camera glitches into the stair
 - playerX: /cmi reply allowing you to look through the stone and giving you access to view all open air-pockets in the floor
```

Player stands in front of their stairs, make the action to fly, right click to sit i believe, and that's when this happens.

**Comment by Zrips** [comment]
Reproduced and will be fixed with next build. We will simply prevent option to sit while gliding with elytra

**Comment by mrfloris** [comment]
Thank you *so much*, I can't believe how quickly you were on fixing this, it really helps us.

**Comment by Zrips** [comment]
still quite few reports awaiting their turn.

**Comment by mrfloris** [comment]
> still quite few reports awaiting their turn.
Quality over quantity, so I don't mind if some things take longer than others. Thanks for sometimes going out of your way and not pushing stuff like this to the end of the list 💯
