### ISSUE TITLE
[ERROR] CMI Titles and TitleManager

### ISSUE THREAD

**Issue by Someone-NEW** [Zrips/CMI#1243]
Hello @Zrips I found that i have an ERROR in console with using last few updates, before i have no problem with cmi and i see this in last few days before this error has no exist, While im using CMI titles i delete plugin TitleManager https://www.spigotmc.org/resources/titlemanager.1049/ which is needed for SurvivalGames X https://www.spigotmc.org/resources/survivalgames.1351/ Like i say without TitleManager before work but now not anymore. Dou you change something there? If so can you please make or fix it so that can be compatible with SurvivalGames X plugin? So that titles can be used? This will help me a looot i realy dont need 1 more plugin for the same feature like CMI have.
---
**ERROR (DELETE IF YOU HAVE NO ERROR):**
####################
####################
```

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.3.2.0
Server version: Spigot 1.12.2-R0.1-SNAPSHOT
Vault version: 1.6.11(+)

**Server Type (Spigot/Paperspigot/etc):** 
Spigot 1.12.2

**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Checking version, please wait...
You are 387 version(s) behind

**Comment by Zrips** [comment]
Stuff like this should be done from SurvivalGameX side. You will need to use titlemanager if you want it to work properly. CMI titles are not related to this.

**Comment by Someone-NEW** [comment]
Thats realy sadly... Previously, it worked smoothly, and the last few versions did not. I thought you could do something. Developer from SG is inactive over 19w ago, and this is the second time, so I can not expect any support. I just hoped you could do more about Titles, I obviously made a mistake, so there are limits for you too. :(
