### ISSUE TITLE
[Request] money give with random amount

### ISSUE THREAD

**Issue by SeanWalk** [Zrips/CMI#1246]
**Description of issue or feature request:**

---

In give command has this

/cmi give Zrips sponge %rand/1-10%

Can u add this feature to make command like this to be available?

/cmi money give @a[distance=..5] %rand/500-999%

---

**Cmi Version (using`/cmi version`):8.3.1.0** 

**Server Type (Spigot/Paperspigot/etc):paperspigot** 

**Server Version (using `/ver`):1.13.2 488**

**Comment by Zrips** [comment]
Next update.
