### ISSUE TITLE
Unsafe msg warning or alternative nearby place to /back?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1249]
```
[17:56:53 INFO]: ST4TiK issued server command: /back
[17:56:54 INFO]: ST4TiK issued server command: /back
[17:57:04 INFO]: ST4TiK issued server command: /back
[17:57:04 INFO]: ST4TiK issued server command: /back
[17:57:05 INFO]: ST4TiK issued server command: /back
[17:57:05 INFO]: ST4TiK issued server command: /back
```

We noticed that players started to spam the /back button from CMI, and turns out after we asked them today why, that it wasn't because they weren't swapping between locations, but because it didn't work. 

We learned that when they were in lava and got out and /home (or maybe stayed in, i mean they claim they got out) or if they fly with elytra and end up in lava and die. And then to /back, that they cannot get back.

- Issue : They do not see there's an unsafe location or no location to /back to and then complain that /back is broken and create some drama about losing location or their stuff at that location.

- question : does CMI not already say they can't go /back, unsafe location? Because it's no longer showing, and I swear I've seen it before (can't find it in config.yml ??)

- Suggestion : If the /back is unsafe due to lava, would it be possible to place them nearby if there's a safe location nearby? Kinda like a mini- RTP nearby radius of 5 blocks? Usually unless it's a big lava lake, the nearby blocks are there, but /back doesn't seem to bring them there. And at least maybe have it say they can't get back because their location was in the air or in java and is unsafe?

- thought : maybe they can't go back, because they were in the air flying and /back doesn't have the location of them flying (and dying or flying into lava and then dying) ??

spigot 1.13.2
latest cmi (unless you just pushed out an update an hour ago, i haven't been to spigotmc yet)

**Comment by Zrips** [comment]
Sorry about this, some feedback messages have been missing when player tries to go back into unsafe location. Will be added back with next build.
