### ISSUE TITLE
CMI async with Database

### ISSUE THREAD

**Issue by Miracusa** [Zrips/CMI#1250]
**Description of issue or feature request:**
We use cmi on 2 servers wich are in a bungecord network. 
The problem is:
If a user is joining one of the servers, cmi dos not take the data from the database (wich is writen by the cmi on the other server), but will use some sort of cache or something and override the newer data with his old cached ones. It seems as if cmi only pulls data from the database if the server is rebooting,

We would like cmi to pull database data at least at user login instead of using his old cached ones and then overriding the actually newer ones.

Is there a way to deactivate this cache entierly?

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

```

**Cmi Version (using`/cmi version`): 8.3.2.0

**Server Type (Spigot/Paperspigot/etc):** Spigot /Bungecord

**Server Version (using `/ver`):** 1.13.2

**Comment by Zrips** [comment]
Disabling cache would cause lag spike when player joins

**Comment by Miracusa** [comment]
Ah ok. How do we avoid people loosing all money every time they join the lobby?

**Comment by Zrips** [comment]
By having separate table for storing players balance. Currently CMI doesn't support multiserver. At some point we could allow not to use cache system and load players data from database with slight delay after player logins (fun story, on bungee server while player switches servers he is for ~200ms on 2 servers at once...) or even add async data read to avoid lag spikes. But this would require additional tweaks as some features require player data to be loaded, obvious example would be /baltop. Tho, again, we can keep cache and try reloading player data on his join with delay to allow data from previous server to be saved into data base. Which again means that we will need to force player data save in he quits server.
