### ISSUE TITLE
CMI commands kick player for spamming if holding backspace

### ISSUE THREAD

**Issue by wispoffates** [Zrips/CMI#1251]
Using any CMI command ex: /msg type a decent amount after the /msg then hold backspace but do not delete the cmi command.  You will be kicked for spamming.  Sometimes it takes a few tries as the message was not long enough to trigger enough backspaced.

You do not need to send the command.

Cmi Version (using`/cmi version`):
cmi version=> [23:14:51 INFO]: --------------------------------------------------
[23:14:51 INFO]: CMI plugin version: 8.3.1.0-> 8.3.2.0
[23:14:51 INFO]: Server version: Paper("684bd2ad") 1.13.2-R0.1-SNAPSHOT
[23:14:51 INFO]: Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}(CMIEInjector)
[23:14:51 INFO]: --------------------------------------------------

Server Type: PaperSpigot

Server Version: 
This server is running Paper version git-Paper-"684bd2ad" (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Back Space should not trigger any events, like none at all. Tab can, but no other key should trigger any packets sent from user towards server. Could you provide short video demonstrating this one? And did you tested it with vanilla client with only CMI installed?
