### ISSUE TITLE
[Pull Request] Locale_EN.yml

### ISSUE THREAD

**Issue by pinkpig3777** [Zrips/CMI#1252]
**Description of issue or feature request:**
I had someone I know with very good grammar/spelling edit the Locale_EN.yml file. They fixed a lot issues for messages. For example, using "have" when "has" should be used, missing "a" or "the" in a message, little things like that. They may have missed some issues, but overall the file should be improved a lot. Additionally, I checked it with a YAML parser and there are no issues with Syntax. Then when I uploaded it to my server and reloaded the plugin there were no console errors either. 

Why am I asking you to accept this? Because I can tell English is not your first language and I want to ensure players can fully understand messages + make server messages look professional & clean. Basically this will save time for a lot of other people using the plugin from having to edit the locale file themselves to fix the mistakes.

**Please Note:** It is easy to misunderstand tone in a message. I am NOT in any way accusing your locale file of being bad or insulting you in any way. I simply meant that there is room for improvement, and this would help a lot of people. So please, consider adding it. Thank you! :)

**Updated Locale_EN.yml:** https://pastebin.com/Dk8YBapx

**Cmi Version (using`/cmi version`):** https://gyazo.com/4959a653ed80f2648f944e12eb5a056a

**Server Type (Spigot/Paperspigot/etc):** Spigot 1.13.2

**Server Version (using `/ver`):** CraftBukkit version git-Spigot-82e117e-2b2d084 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will have o look at it. Tho its older version as i can see some lines missing, and i did made some grammatical changes (had some help, duh) in recent updates, so default locale should be more... correct... But thanks anyhow.

**Comment by pinkpig3777** [comment]
Okay, wasn't aware of that at the time of posting. Anyways, thanks!
