### ISSUE TITLE
[Feature Request] Checking for water for /cmi rt

### ISSUE THREAD

**Issue by pinkpig3777** [Zrips/CMI#1254]
**Description of issue or feature request:**
Please add an extra option to avoid teleporting players into water (with /cmi rt) by checking what type of block is under target location. 

Thanks!
_______________________________________________________
**Cmi Version (using`/cmi version`):** https://gyazo.com/1064c0e8cf15a794db90247092071d89

**Server Type (Spigot/Paperspigot/etc):** Spigot 1.13.2

**Server Version (using `/ver`):** CraftBukkit version git-Spigot-82e117e-2b2d084 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
This was implemented with latest build
