### ISSUE TITLE
Warmup & Cooldown Bypass Perms Not Working

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#126]
Using the latest Spigot 1.12.2 build and CMI 7.4.3.0, with LuckPerms 4.1.25 permissions, although this has been around for quite a while. Can't seem to get the warmup and cooldown bypass permissions to work -- the warmups and cooldowns seem to work quite well themselves, but even our OPs are limited by them even when we specifically add the bypass permission nodes to the individual users. Have tried many variations in both the configs and the nodes, including restarts between each change and confirmed permission nodes are present with /cmi haspermission (see attached images).

Appropriate config sections below. Note that we keep them disabled when not testing since we haven't been able to get it to work! We've also tried all variations between (for example): cmi tpa :60 and tpa :60 and cmi tpa:60, etc. 

Cooldowns:
  Enabled: false
  List:
  - cmi tpa :60
  - cmi tpaccept:60
  - cmi home :60
  - cmi warp :60
  - cmi back:60
  - Feed:120

WarmUps:
  Enabled: false
  InformOnNoMove: false
  List:
  - cmi home :5:false
  - cmi warp :5:false
  - cmi tpaccept:5:false
  - back:3:false
  - tpa :5:false

![2018-03-13_22 16 19](https://user-images.githubusercontent.com/21208123/37380352-ab239ca2-270e-11e8-970d-d250ed9db7c5.png)
![2018-03-13_22 16 40](https://user-images.githubusercontent.com/21208123/37380353-ab2f4b2e-270e-11e8-954d-cfef570f570c.png)

**Comment by Zrips** [comment]
Should be fixed with next build
