### ISSUE TITLE
Glow not working

### ISSUE THREAD

**Issue by Rukes** [Zrips/CMI#1261]
Hey,
glow colors doesnt work, command `/cmi glow Rukes red` makes me glow white. Does not work with any color.

**Comment by pvpKingdoms** [comment]
Do you have a tab list plugin?

**Comment by Rukes** [comment]
Yes, I have, my own.

**Comment by Zrips** [comment]
This is know side effect when you have other plugins utilizing scoreboards. Its work in progress at this point.
