### ISSUE TITLE
[Request] make tpa works with playerDisplayNames

### ISSUE THREAD

**Issue by splops** [Zrips/CMI#1262]
**Description of issue or feature request:**

if player changes his Nick, players would still need to tpa them with his playerName, it would be awesome if cmi could detect nickname belongs to an user and redirects the tpa.

**Comment by Zrips** [comment]
Will be done with next update.

**Comment by splops** [comment]
Sorry for reopen, but nicknames with colors kick players with "Illegal characters in chat", is there a workaround?
