### ISSUE TITLE
Spawner Name Issue

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#1263]
When you use the command /cmi give {player} spawner:cow it gives the player a cow spawner but the spawner is just labeled "Spawner " until the player places it and breaks it.

This was tested on Spigot 1.13.2.
Cmi update: 8.3.3.0

**Comment by CaliDreams** [comment]
I have also been having this issue with the recent last couple CMI updates or so. I've been having to rename the spawners myself with /itemname or anvil, or place/break them.

**Comment by Zrips** [comment]
Should be ok with next update.
