### ISSUE TITLE
Update to UltraPermissions 4

### ISSUE THREAD

**Issue by DeadIntermediate** [Zrips/CMI#1264]
**Description of issue or feature request:**
I was able to get a part of the error code. I am using UltraPermissions version 4.0.0
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## https://pastebin.com/0fPNQu1a ##
####################
```

**Cmi Version (using`/cmi version`):** 
http://prntscr.com/m4b8c7

**Server Type (Spigot/Paperspigot/etc):** 
Spigot 1.13.2

**Server Version (using `/ver`):** 
http://prntscr.com/m4bbk9

**Relevant plugins (Delete if this isn't needed):** 
UltraPermissions 4.0.0

**Comment by Zrips** [comment]
Updated.
