### ISSUE TITLE
Add hoveritem compatibility with other chat plugins.

### ISSUE THREAD

**Issue by Segysmundo** [Zrips/CMI#1275]
We're using another chat plugin and was told the hoveritem feature only works with CMI's chat system. I would love to use this feature while still retaining my chat's plugin functionalities so it would be incredibly useful if you could make it compatible with the main chat plugins, eg. Deluxechat.

**Comment by Zrips** [comment]
Hover over feature requires for entire message line being replaced with JSON formatted one, chat message event itself should be canceled entirely and new message resend to everyone who should see it. So its more or less impossible to have compatibility with other plugins, especially if they are trying to add json messages of their own. Blame mojang for making this one so complicated.
