### ISSUE TITLE
Rankup command unlimited item duplication glitch/bug

### ISSUE THREAD

**Issue by abhisantos** [Zrips/CMI#1277]
WIth the command /rankup players can duplicate unlimited op items!
Just fill up your inventory and keep doing /rankup
Please see the video to understando how to do it: 
https://youtu.be/zjUHK9ra394

**Cmi Version (using`/cmi version`):** 
8.3.1.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
CraftBukkit 1.8.8

**Comment by Zrips** [comment]
Would be nice to have actual rankup.yml file for testing which would provide best and fastest approach in fixing this one. Will try to reproduce it, if i will fail it, i will need that file.

**Comment by Zrips** [comment]
Ok, reproduced some issue related to rankup. This should solve your reported issue with next update.
