### ISSUE TITLE
Money issue

### ISSUE THREAD

**Issue by ludvdber** [Zrips/CMI#1280]
**Description of issue or feature request:**
I use CMI with bungeecord.
In the server A, I give me 10$. When I go to the server B, I have 0$.
If I stop server B then server A and restart them I get 10$ in server A and B
If I have 10$ in the server A and 0$ in server B. I stop server A then B and restart them, I have 0$
I get the money from the last server I stopped

**Cmi Version (using`/cmi version`):** 8.3.4.0

**Server Type (Spigot/Paperspigot/etc):** spigot with bungeecord

**Server Version (using `/ver`):** 1.13.2 git-spigot-f56e2e7-98b862a

**Relevant plugins (Delete if this isn't needed):** CMI and vault from CMI

**Comment by Zrips** [comment]
CMI doesn't have multi-server support, yet.
