### ISSUE TITLE
Essential Suggestion: Bed homes deleted on bed break

### ISSUE THREAD

**Issue by BeeRando** [Zrips/CMI#1281]
This is essential for a survival PVP server. If someone breaks my bed, I should no longer be able to /home back to that location. As it stands this is a relatively game breaking issue that my server and perhaps some others face, as people can set their homes anywhere with no way of stopping them. This was a core feature in essentials and is how many survival servers opperate. Please add the ability in the config to have someones /home be deleted when their bed spawn is destroyed.

**Comment by Zrips** [comment]
Will be added with next update.
