### ISSUE TITLE
/cmi glow (color) and featherboard still having problems.

### ISSUE THREAD

**Issue by Segysmundo** [Zrips/CMI#1282]
If you have Featherboard installed and try to use /cmi glow (color) it will make you glow white.

Haven't been able to find out where the incompatibility is. Just letting you know it exists.

---

Cmi version 8.3.4.0
Paperspigot 1.12.2

Relevant plugins - Featherboard seems to be the plugin causing the glow color to not work.

**Comment by Zrips** [comment]
This is known issue, but the solution is not really known at this point.
