### ISSUE TITLE
chatresponse are very slow

### ISSUE THREAD

**Issue by linhux** [Zrips/CMI#1285]
**Description of issue or feature request:**
since the last upde is the chat response very slow.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**Cmi Version (using`/cmi version`):** 
8.3.4.0
**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
spigot1.13.2
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Could you elaborate more on this?
