### ISSUE TITLE
Tablist /cmi reload bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#1286]
![image](https://user-images.githubusercontent.com/5382252/51091111-ebe00e80-17c0-11e9-8c7e-1bd441acaecb.png)

if use

![image](https://user-images.githubusercontent.com/5382252/51091118-fbf7ee00-17c0-11e9-82ca-7c44318f4cca.png)

&f{cmi_user_balance_formatted}  ( BUG )

2. bug

CMI and DeluxeChat and PlaceholderAPI and MVdWPlaceholderAPI
see like conflict

![image](https://user-images.githubusercontent.com/5382252/51091384-192ebb80-17c5-11e9-9662-4768e7a094d6.png)
![image](https://user-images.githubusercontent.com/5382252/51091393-22b82380-17c5-11e9-8fcb-9bf14a3253a2.png)
![image](https://user-images.githubusercontent.com/5382252/51091400-2ea3e580-17c5-11e9-8ed2-84dc25263d16.png)

It won't happen in previous versions
fix it thank

**Cmi Version (using`/cmi version`):** 8.3.5.0 

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.12.2

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Well first of, error came from MVdWPlaceholderAPI itself when CMI requested translation of placeholder. But will make some changes to avoid using MVdWPlaceholderAPI if placeholder itself is from CMI. So that maybe should fix this issue you got. So test out with next update.
