### ISSUE TITLE
Bug: Latest bed home feature

### ISSUE THREAD

**Issue by BeeRando** [Zrips/CMI#1287]
**Description of issue or feature request:**
In the latest update, you made it so breaking a bed would remove the home. This however isn't working. It does teleport me now to the foot of the bed like stated, but breaking the bed won't remove the home. This has been tested on new homes set. I've set multiple new bed spawns and broken the beds to be sure before making this post. 

#####################################
#####################################
Relevant config section https://pastebin.com/kSk1y8eQ
Entire config incase it helps https://pastebin.com/ceJ1261C

Perms players have incase it helps?
- cmi.command.home
- cmi.bedhome

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.3.5.0
Spigot 1.13.2-R0.1-SNAPSHOT
Vault version: 1.7.1-b91(CMIEInjector)

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-a1ba5fe-b4230a9 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by BeeRando** [comment]
I've deleted every plugin except cmi, and luckperms. I'm still able to teleport to bed spawns even when the bed is broken, so I'm not sure what's interfering. For some reason the home isnt being deleted.

Here is the console log on start up
https://pastebin.com/7vgZe9Jy

**Comment by Zrips** [comment]
Will do some changes to hopefully fix that. Cant really reproduce at this point. If issue persists after next update, send me PM on Discord, will be faster conversation and easier to figure out whats causing this inconvenience.
