### ISSUE TITLE
CMI Rcon Support

### ISSUE THREAD

**Issue by Eifime** [Zrips/CMI#1289]
Currently CMI cannot return the results of Rcon execution correctly

**Comment by Zrips** [comment]
Could you elaborate more on this one? What you mean by "correct execution"? As o my testing i can send /heal zrips which will work without any trouble.

**Comment by Zrips** [comment]
Server version?

**Comment by Eifime** [comment]
paperclip 1.13.2

**Comment by Eifime** [comment]
Do you follow up on this question?

**Comment by Zrips** [comment]
This was fixed and you should receive feedback messages to rcon
