### ISSUE TITLE
#1286 still bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#1292]
![image](https://user-images.githubusercontent.com/5382252/51127989-ca832f00-1861-11e9-8093-b3726e757c8a.png)

https://github.com/Zrips/CMI/issues/1286
still no work

**Cmi Version (using`/cmi version`):**  8.3.6.0

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.12.2

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
You mentioned DeluxeChat, is this plugin been used for chat format or its completely controled by CMI alone?

**Comment by p82183645** [comment]
For chat format

see this : https://www.spigotmc.org/resources/deluxechat.1277/

**Comment by Zrips** [comment]
This only happens when you perform /cmi reload?

**Comment by p82183645** [comment]
@Zrips 
can you fix this?
8.3.7.1 still no fix

**Comment by Zrips** [comment]
I still need to reproduce issue. Everything works as it should on my test server. So something is different with your settup which causes this issue. More investigation is needed

**Comment by p82183645** [comment]
`formats:
  default:
    priority: 2147483647
    channel: ''
    prefix: '%vault_groupprefix%&6&lLv.&b&l%mvdw_placeholderapi_sap_default_currentlevel%&9%mvdw_placeholderapi_sap_default_currentprefix%'
    name_color: '&b'
    name: '%player_name%'
    suffix: '&7> '
    chat_color: '&f'
    channel_tooltip:
    - ''
    prefix_tooltip:
    - '&7*-----* &b%player_displayname% &7*-----*'
    - '&d♚ &6%mvdw_placeholderapi_kingdoms_kingdom%'
    - '&7: &6%marriagemaster_partner%'
    - '&7: &6%mvdw_jobsreborn_name_1%'
    - '&7: &6%mvdw_placeholderapi_sap_default_currentprefix%'
    - '&5: &6%vault_eco_balance_fixed%'
    name_tooltip:
    - '&7'
    suffix_tooltip:
    - ''
    channel_click_command: '/m %player_name% '
    prefix_click_command: '/tpa %player_name% '
    name_click_command: '/m %player_name% '
    suffix_click_command: ''`

**Comment by p82183645** [comment]
![image](https://user-images.githubusercontent.com/5382252/51355185-3d560980-1af1-11e9-8604-60599d272381.png)

**Comment by p82183645** [comment]
all no work

**Comment by p82183645** [comment]
@Zrips  can fix?

**Comment by Someone-NEW** [comment]
Hi @Zrips i have the same problem, now when i update CMI to latest version today i see that ALL placeholders wont working i see just %something...  And i think when you do some updates for MVdWblabla plugin this comes to stop working our placeholders with usin PlaceholderAPI and CMI, deluxetags and many many other plugins that uses placeholderAPI placeholders. NO one working now, Any idea?

**Cmi Version (using/cmi version):**
CMI plugin version: 8.3.7.3
Server version: Spigot 1.12.2-R0.1-SNAPSHOT
Vault version: 1.6.11(+)
**Server Type (Spigot/Paperspigot/etc):**
Spigot
**Server Version (using /ver):**
This server is running CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Checking version, please wait...
You are 413 version(s) behind
**Relevant plugins (Delete if this isn't needed):**
PlaceholderAPI

**Comment by p82183645** [comment]
@Zrips  hallo? no any fix

**Comment by Zrips** [comment]
Fix will come when i can reproduce this one, and at tis stage its not been reproduced. Will make some testing, but cant promise anything as you have different setup then my test machine and some other plugin could interfere with that.
