### ISSUE TITLE
[Bug] Home gui functionality

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1295]
**Description of issue or feature request:**

---
When a staff player executes `/home something playername123` and makes an error writing the correct home name `something` then this playername123 gets a GUI in front of him with his homes.

With this GUI, the player who is being investigated knows he is being watched or investigated. This reveals that staff is investigating a player!

Before 8.3.6.0 this would present the staff player the possible homes of that player as text.
Could this be fixed so staff gets that players' home in a GUI, instead of the player involved?

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Homes:
  Gui: true
```
---

**Cmi Version (using`/cmi version`):** 
8.3.6.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper 1.13.2 build 500

**Comment by Zrips** [comment]
Good point, will be fixed with next build.
