### ISSUE TITLE
[Bug] Random tp IgnoreWater and IgnoreLava

### ISSUE THREAD

**Issue by Segysmundo** [Zrips/CMI#1296]
Cmi Version: 8.3.7.0 
Server Versión: PaperSpigot 1.12.2

---

IgnoreWater and IgnoreLava don't seem to do anything, both are set to true and I can still randomly tp inside water and lava.

![image](https://user-images.githubusercontent.com/19178945/51204200-4c776480-1903-11e9-944f-bb75a20c5969.png)

**Comment by imhandmade** [comment]
I have been noticing this issue as well. Didn't know if it was just me or not.

**Comment by Zrips** [comment]
Och, issue with 1.12 version, its pain in ass to have backwards compatibility. Will be fixed with next version.
