### ISSUE TITLE
Power tools Help

### ISSUE THREAD

**Issue by Wakeeng** [Zrips/CMI#1297]
i was wondering, is it possible to allow players to use power tools without giving them the specific command? currently i am creating a few tools in game for people to find (stuff like fireball, lightning command etc) and when they attempt to use it just says that they dont have permission.

i am using cmi 8.3.7

**Comment by Zrips** [comment]
Some commands can be performed asConsole! other then this without giving permission to use command we can't determine if player should be allowed to perform that command or not. Atleast not at this point.
