### ISSUE TITLE
StatsRequirements listed in /cmi rankup but not detected when completed.

### ISSUE THREAD

**Issue by FlakMagnet** [Zrips/CMI#1298]
The StatsRequirements aren't being detected for rank-up requirements in-game.  I've verified that the relevant information is being recorded in each player's ```<minecraft-dir>/world/stats/*.json``` file, which is where I presume CMI is would look to find that information for rank-ups. When the player runs ```/cmi rankup``` it lists the requirements but not ones that have been completed per the stats .json file.

In the attached screenshot the player had crafted a crafting_table, furnace, and 8 torches prior to the ``/cmi rankup``` command being executed. After 5 minutes the command was re-run with no change aside from playtime and travel distance.
![screenshot_2019-01-15_21-39-06](https://user-images.githubusercontent.com/46733720/51222993-0a9feb80-190e-11e9-805d-26cad063530d.png)
(As an aside, I'd like to use ANY door as a requirement, but just saying "door" defaults to the spruce kind.)

From the server's logs I see:
```[01:45:54] [Server thread/INFO]: [CMI] Loaded (10) ranks into memory. Took 5ms```

**CONFIG SECTION:**
From ranks.yml
```
  StatsRequirements:
  - "PlayTime:3600"
  - "travel:1280"
  - "ItemPickups:dirt:64"
  - "ItemCrafts:door:1"
  - "ItemCrafts:torch:6"
  - "ItemCrafts:furnace:1"
  - "ItemCrafts:crafting_table:1"
```
May seem similar to this issue but I have reviewed the answer to that one already:
https://github.com/Zrips/CMI/issues/406

May be the same/related issue as this one:
https://github.com/Zrips/CMI/issues/561  (Edit - removed self-reference from this issue)

---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.3.7.0

**Server Type (Spigot/Paperspigot/etc):** 
Server version: Paper(500) 1.13.2-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 
[02:14:02 INFO]: This server is running Paper version git-Paper-500 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Press esc ingame, go to statistics and look up if you actually have recorded itemcrafts in there. As CMI will use vanilla statistic tracker for determining what player crafted. And vanilla statistic tracker is know for his incorrect data tracking for quite some time now. Will investigate what i can do about this one tho.
For doors, as of 1.13 every type of block has its own material name and its own ID, so it would be more difficult to track similar type of blocks and group them up. Possible, but do we really need it?

**Comment by FlakMagnet** [comment]
I've checked the statistics in-game, and the ones I would expect to be are recorded, just one example - 
![minecraft 1 13 2_002](https://user-images.githubusercontent.com/46733720/51261288-f09df180-197d-11e9-9c18-e7998e8778eb.png)  ... yet the Crafting Table requirement shown in the OP still isn't completed per /cmi rankup.  I'm assuming that the rankup requirements are => the defined amount, and not == that amount, in this case, a single crafting table.

As for the doors issue, maybe add a feature where it can be "any of these items" for a single requirement.
Example:
` - "itemcrafts:Dooor[spruce_door/oak_door/birch_door]:1"`
Meaning that if the player has crafted one of any of those kinds of doors then that requirement line is met.  The "Door" before the open-bracket could be to tell /cmi rankup what to list that requirement in it's output.  Let me know if you'd like a separate feature request for "any of these" itemcrafts requirement.

I am keeping mind that the above suggestion is moot if the StatsRequirements issue can't be figured out.

Thank you for the response!

**Comment by Zrips** [comment]
Hopefully with new version should be ok

**Comment by FlakMagnet** [comment]
Success!  Confirmation - 
![selection_006](https://user-images.githubusercontent.com/46733720/51275519-34095780-19a0-11e9-86b7-4919db3b6b37.png)

It dropped the "door is spruce door" behavior as well.
