### ISSUE TITLE
[Question/Request] Keep hunger no longer supported or not working?

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#1299]
**Description of issue or feature request:**

We used to have a feature (#348) to keep hunger after death, which was super useful on our SkyBlock server. That server has only recently reopened and we noticed the feature doesn't seem to be working anymore -- was that removed or perhaps it's just derping? I noticed that the old permission "cmi.hunger.keepafterdeath" is no longer listed in CMI's permissions list either. I would love to have that back again, if possible.

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.3.7.0-> 8.3.7.1 (still need to update to today's)
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-f56e2e7-0c715b3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) (also need to update)

**Comment by Zrips** [comment]
Permission is still listed in a list /cmi checkperm keepafterdeath
And this feature is still in action. It could me some derping going on, will make some changes to listen on lower priority and change hunger with bigger delay which should solve your issue.
