### ISSUE TITLE
Issue with Import from Essentials

### ISSUE THREAD

**Issue by DJKenzoDE** [Zrips/CMI#13]
i have in the Console performed this command: cmi importfrom essentials home warp nick money logoutlocation
and i have try to make it seperate with single argument e.q: cmi importfrom essentials home

this is the message output:
Usage: /importfrom [essentials] [home/warp/nick/logoutlocation/money]
* Import data from other plugins

**Comment by LogGits** [comment]
Was able to reproduce. It appears that the command isn't working when using it in console.

**Comment by Zrips** [comment]
Will be fixed with 7.3.8.6+ versions
