### ISSUE TITLE
Question: EventCommands -> joinServer

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/CMI#130]
How can I bring clickable content into the message that I have set when I enter the server

``
joinServer:
  Use: true
  List:
  - titlemsg [playername] &fWillkommen zurück [playername]
  - msg! [playername] &7========================================
  - msg! [playername] Herzlich Willkommen zurück [playername] (**_<- the name is unfortunately not displayed_**)
  - msg! [playername] &r
  - msg! [playername] Vote für HomeLandings.de! &6&l/vote&f (**_<-this shoud be clickable_**)
  - msg! [playername] Kontostand &7%vault_eco_balance_formatted% &f | &7%VotingPlugin_Points%
    &fVotepunkte
  - msg! [playername] Regeln -> &b/regeln &f| Forum -> &b/forum
  - msg! [playername] &7========================================

**Comment by LogGits** [comment]
> msg! [playername] Herzlich Willkommen zurück [playername] (<- the name is unfortunately not displayed)
use `[playerName]` to get the name to display.

**Comment by HomeLandingsDE** [comment]
Oki i will try

**Comment by mormoon** [comment]
What about sending a raw json message to display a clickable link?

tellraw [playerName] ["",{"text":"Vote für HomeLandings.de! ","color":"white"},{"text":"/vote","color":"gold","bold":true,"clickEvent":{"action":"run_command","value":"/vote"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Vote for rewards!"}]}}}]

**Comment by Zrips** [comment]
mormoon
2 options:
1. Create custom text and show it to player
2. Change " into \" while saving file, as yaml format is picky. 
`  - tellraw [playerName] ["",{"text":"Vote für HomeLandings.de! ","color":"white"},{"text":"/vote","color":"gold","bold":true,"clickEvent":{"action":"run_command","value":"/vote"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Vote
    for rewards!"}]}}}]`

**Comment by Zrips** [comment]
2 options.
1. Create custom text and show it to player.
2. Use that command, works for me.
