### ISSUE TITLE
SpawnerEditor | Error

### ISSUE THREAD

**Issue by Melowelsa** [Zrips/CMI#1300]
**Description :**
- When I open the `/cmi spawnereditor` and try to click on an item, it's not doing nothing except sending an error : **http://hatebin.com/tvqpkocesl**.

**Cmi Version :** 
- CMI plugin version: 8.3.6.0-> 8.3.7.1
- Vault version: 1.7.1-b91(CMIEInjector)

**Server Type (Spigot/Paperspigot/etc):** 
- git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Update to 1.12.2 as 1.12.1 is broken version and this command will not work on it.

**Comment by Melowelsa** [comment]
CMI plugin version: 8.3.7.1
Vault version: 1.7.1-b91(CMIEInjector)
git-Spigot-3d850ec-809c399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Still are getting an error : **http://hatebin.com/kjsymfvytq**.

**Comment by Zrips** [comment]
This cant be the case with latest 1.12.2 build as it contains all needed methods in it. Are you sure you are on latest 1.12.2 version?
