### ISSUE TITLE
[bug?] unknown world when trying to save inventory

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1301]
We use an alias /run to start a mini-game in another world. We tell it to save the player's inventory (just in case) send out a bossbar msg that they've joined the arena and then move them to that world. 

This worked fine until today's update, i get exception errors now when we use /run

(what i do notice is that when i type it in manually in the game: /cmi invsave someplayer, that i get the list with the last save there, so it seems to work manually, but not as fromConsole! ??)

https://pastebin.com/JrdEW0i8

```
[03:36:23 ERROR]: Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization
java.lang.IllegalArgumentException: unknown world
```
When i check the placeholder with cmi it finds the world.

pic of alias /run
https://i.imgur.com/6Lxq68c.png

The docs for cmi say this:
`/cmi invsave (playerName) (-s) - saves players inventory`
so there's no world to provide either somehow, and this worked fine in the past.

**Comment by Zrips** [comment]
It has todo with old player inventories load method. Before we have saved Location as object which would be easy to convert back when reading entry, but that introduced issue you have encountered now. Some time ago i changed that to actually save location as 1 string liner, which means that loading it will not cause this error to appear and i can then check for existing world and simply ignore and show that inventory even if world doesnt exist. While Minecraft server will scream that world doesnt exist.
Point is, that this error should be one time thing for player with older inventory saves and should fix itself with next save/load. Will do some extra changes for ti tho, just in case.

**Comment by mrfloris** [comment]
Thank you for the information, I understand this a lot better. And I am glad to read it's a one time thing that auto corrects itself. I can stop worrying about it ;) I appreciate the continued support.
