### ISSUE TITLE
New NickName Tab-complete

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#1302]
Can you please add a option to disable that feature? :)

**Comment by Zrips** [comment]
Will add with next update. Who curious, why do you need this one to be disabled?

**Comment by SirGoldman-git** [comment]
Well, first off I just simply don't like it, I only use Nick to change the color of a name, so when you tab-compete names it's just showing two sets of the same name, also if you try and use the nicked name when replying it will crash the players clinet telling them invald message sent in chat.
