### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by TeeKay1** [Zrips/CMI#1304]
I have multiple plugins hooked into the MySQL server so I know it works including Ultra Permissions and dont have issue. As of right now some table were created but some hasn't been and is throwing this error.  

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/XcMZawTb
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.7.3.1
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.13.2 R0.1 Snapshot
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Something funky is going on with your table name settup. how did you set it up? And is there any errors on start?

**Comment by TeeKay1** [comment]
No the only table I made was minecraft and then it created a sub table
called CMI_Asgard (servername)

**Comment by Zrips** [comment]
There should be 4 new tables, if you have default setup for prefix, then they should look like: cmi_inventories, cmi_users, cmi_playtime, cmi_playtimereward

**Comment by Zrips** [comment]
and CMI_Asgard? CMI doesn't create tables based on server name

**Comment by TeeKay1** [comment]
Everything was left default except for the database name which was changed
due to me changing the name for the database.

**Comment by Zrips** [comment]
can you provide startup log of CMI? As it seems to be some issues with table creation.

**Comment by TeeKay1** [comment]
I am double checking everything. I just looked at my table and nothing from
cmi is on this database. But Ultra Permissions is coming up. So I'm
thinking there is like 1 letter or number off in the config.

**Comment by Zrips** [comment]
Maybe password is wrong? database name?

**Comment by TeeKay1** [comment]
Yeah I'm thinking it's the password considering I'm using a 256 bit
encryption password

**Comment by TeeKay1** [comment]
I also change the the table prefix to CMI_asgard. Could that cause an issue

**Comment by TeeKay1** [comment]
https://pastebin.com/UWMxRBSK here is the setup i have in the config

**Comment by Zrips** [comment]
First point would be to avoid posting your mysql password on public platforms. Second thing, you could try making simpler password, which would not contain special characters which could mess things up. But in general if you have correct password and you have database named minecraft, it should work.
FYI You can always use sqlite system.

**Comment by TeeKay1** [comment]
I cant use the SQL lite system in a network though...right?

**Comment by TeeKay1** [comment]
So I changes the password and still getting the error. Not sure what's
wrong but ultra perms still works. How do I get the cmi start up documents?

**Comment by Zrips** [comment]
Can you show me server startup log related to CMI? And make sure you have minecraft database in your mysql. And sqlite in local file, tho why do you need it on network? CMI doesn't support, currently, multi server settup.

**Comment by Zrips** [comment]
Will post new version today with some changes related to database table creation which should solve your issue. Hopefully.
