### ISSUE TITLE
[Bug] hunger bar & god mode

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1305]
**Description of issue or feature request:**

---
When a player with GOD enabled has hunger and tries to eat, the hunger bar does not get full. Eating is possible, but food is not consumed and food bar does not get full.

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
none

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
none

---

**Cmi Version (using`/cmi version`):** 
8.3.7.1 but this is present for a while I believe
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.13.2

**Comment by Zrips** [comment]
This is minecraft "bug" by itself, its preventing food consumption while you are in vanilla God mode
