### ISSUE TITLE
inventory load issue.

### ISSUE THREAD

**Issue by MothGirlMusic** [Zrips/CMI#1310]
**Description of issue or feature request:**

the cmi.saveinv permission allows for saving inventory on death.. so naturally one would use the on death event in the eventCommands.yml for "  - moneycost:500#! cmi invload [playerName] [playerName] last" to allow players to basically save their items as long as they have enough money to pay for it. however doing this causes, on death like in lava.. the player just stays there dying over and over again until they have no more money. the cmi.autorespawn permission makes it a lot quicker, but same thing. the save inventory seems to teleport you to your last location [which in this case is unwanted] and cannot be turned off. 
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
it should be relevant, but there doesn't seem to be an actual config section for inventory saving.
```

---

**Cmi Version (using`/cmi version`):** 
**Server Type (Spigot/Paperspigot/etc):** 
**Server Version (using `/ver`):** 
![screen shot 2019-01-18 at 14 20 20](https://user-images.githubusercontent.com/1746550/51408301-3d272f80-1b2c-11e9-8f91-60f8ead01e3d.png)

**Comment by Zrips** [comment]
Would it be better to create IC or even clickable hologram in your spawn and players could choose to restore previous inventory or not? That would solve lava issue and players who died without loosing anything valuable will not waste money on restoring "nothing"

**Comment by MothGirlMusic** [comment]
That’s definitely interesting. I’ll check it out. Though since I had to fix the issue rather quickly I’ve been using another plugin that supports partial inventory losing and death taxes and all that I was trying to do and CMI doesn’t support.

———
73, KC1KSG
