### ISSUE TITLE
CMI/Towny incompability issue after 8.3.7.0

### ISSUE THREAD

**Issue by ArathiaMC** [Zrips/CMI#1312]
Hello @Zrips 

There is a major issue with towny and CMI in versions after 8.3.7.0.
It appears to not register balance properly in connection with towny.

When players (and operators) try to deposit money into the towny bank it will return with a message claiming they do not have the money - even though they do. I downgraded back to CMI version 8.3.7.0 and it works again so it's an issue with the versions newer than this.

Hoping for a quick fix.
Thanks

---
CMI Versions above 8.3.7.0
**Cmi Version (using`/cmi version`):** 

Paperspigot 504

1.13.2

CMI/Towny

**Comment by ArathiaMC** [comment]
Another issue I noticed is that you cannot check offline players homes in the most recent version after it is GUI based which you could with the text version.

**Comment by Drc-DEV** [comment]
Can confirm.

**Comment by Zrips** [comment]
Can confirm too. Will fix it, will have to make some hard coded support for towny plugin, but they do have "wrong" economy handling... 
Should be working correctly with next build.
