### ISSUE TITLE
Recipe Display issue

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#1314]
When you put a Water Bottle in for a custom recipe it shows a uncraftable potion when displaying in the menu. Crafting still works, its just very confusing for players.

https://gyazo.com/f7669c6fa8d6295fd89efbe85b556164

**Comment by Zrips** [comment]
They are limitations of what Minecraf recipe engine can do. Which includes incapability to separate anything beyond items material and sub data value, like 1 and 3 for Diorite. While potion doesnt have sub data and potion type is been defined in special way which will not be recognized correctly and only material itself will. At this point i can't really do anything unless i will came up with new recipe handling engine which would handle special item data.
