### ISSUE TITLE
Status Issue

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#1315]
Small issue, you updated CMI a long time ago claiming you fixed how HDD memory is read, after that update it no longer displayed correctly for me, the server I'm running has much more space lol
https://gyazo.com/d4e130dbb34018090ef2c5f9236c0b9b

Spigot 1.13.2
CMI: 8.3.7.3

**Comment by Zrips** [comment]
Yea, its a tricky thing to get around. For some settups one thing doesn't return correct value, for others another setup. Need to find one universal method in extracting correct disk independent if its Windows, linux or VPS with some funky setup.
