### ISSUE TITLE
Purging Issues

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#1317]
When Purge is set to true and its all setup to move the files to the specified directory, it just simply doesn't work. I have a few 100 players over the 90 day limit set, none of the files are getting moved. On boot cmi lets me know it scanned all the user data files, but never moves them.

https://gyazo.com/b1d23defe230ec8bf137618374d5e43c

https://gyazo.com/a55d13537919b32252f0dd208a7fd9af

https://gyazo.com/520742326fbab1ba6899a6a0148c3c28

Hope this can be solved, I'd really like to use this feature :)

**Comment by Zrips** [comment]
Show me your config file and what you have for purge setup set.
