### ISSUE TITLE
offline players homes are not shown with /homes (player) when gui enabled.

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#1318]
**Description of issue or feature request:**

/homes (offline player) no longer shows the players home in the new gui version.   Works fine for online players.

Assuming this is related to the fix for this: https://github.com/Zrips/CMI/issues/1295#

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
No errors

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Homes:
  # Open gui when using /cmi home command if you have more then one home in your saved list
  Gui: true
  # Homes groups to define max amount homes player can have. Permission: cmi.command.sethome.[groupname]
  # If players home group if not find then amount will be set to 1
  # To have unlimited homes use cmi.command.sethome.unlimited permission
  # In adition to this you can use simple numeric permission node cmi.command.sethome.[number] which will define max number of homes player can have
  Groups:
    default: 3
    member+: 4
    vip: 5
    pro: 5
    legend: 6
    ultra: 6
    titan: 8
    champion: 8
    emperor: 10
    mystic: 15
  # Requires cmi.bedhome permission node
  # When set to true by interacting with bed, regular home location will be created
  # When set to false vanilla bed home location will be set
  BedInteraction: false
  # Removes bed location when home location was created by clicking on that bed
  RemoveBedLocationOnBedBreak: true
  # When enabled, plugin will check if player can break block in that area before creating new home location
  # This allows to prevent setting homes in protected areas
  # Can be bypassed with cmi.command.sethome.bypass
  CheckBlockBreak: false
  # Name for default home location. By default its "Home"
  DefaultName: Home
---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.3.7.3 
Server version: Spigot 1.13.2-R0.1-SNAPSHOT 19.01 16:18:14
Vault version: 1.6.10(+)

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-f56e2e7-7fc66b2 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by x1p** [comment]
Confirm

**Comment by Zrips** [comment]
Mmmm, left out tiny part of code from initial update which was only made to show your own homes in GUI which was checking for security reasson if player is online, while now when you can check not only your own homes, this created issue. Anyways, will be fixed.
