### ISSUE TITLE
/home data seems to not be working

### ISSUE THREAD

**Issue by ImShook** [Zrips/CMI#1328]
**Description of issue or feature request:**

---Hello there! I am using CMI to run the basic commands of my server, including /home. On the first day of the server I did /rtp (the better random teleport plugin) and it brought be to around -5574905.593 74 27983040.512 (not exactly here, but this is where my base is currently and is only a few blocks away from where it actually teleported me). I set my home somewhere around there underground. I played for a little bit and eventually set a few more homes at my friends' bases, which were much much closer to the origin and spawn (around a few hundred to a few thousand blocks). However, after restarting the server I attempted to do /home but it brought me to -5574902.580 39.80949 21474836.470. It seems to be an isolated problem because people with there homes closer to the origin and spawn are able to get to their homes no problem. I could get to my homes near the origin no problem too. Another friend who had a home set a few thousand blocks away from my home has the same problem. I tested it again and it happens after every restart, whether I reset my home or not. I have no clue what is going on, and suspect the files must be corrupted in some way but I don't know. I would like some support with this issue.  

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## Console shows no error ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## I have no clue where the problem is. I don't know if you will have the time to 
look through it but here is my config: https://ufile.io/etnzz ##
#####################################
```

---

**Cmi Version ( 8.3.7.3):** 

**Server Type (Paper):** 

**Server Version (1.13.2-506):** 

**Relevant plugins (BetterRTP, GriefPrevention, Vault, WorldEdit, UltraPermissions):**

**Comment by Zrips** [comment]
Fixed
