### ISSUE TITLE
[Request] Modify Hit Delay

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#1332]
**Description of issue or feature request:**
**This isn't regarding the 1.9+ hit cooldowns**
Minecraft has a default hit delay of 20 ticks but it can lead to smoother combat to lower this by a few ticks (this is what servers with "Good Hit Detection" do) - it would be nice if we had some way to modify this delay within CMI without having to use other plugins. Many of the other plugins that do this are either bloated with other features or are no longer being updated.

**Comment by Drc-DEV** [comment]
It would be cool to have an overall solution for changing pvp behaviour. Somewhat similar to https://www.spigotmc.org/resources/knockbackmaster-⭐-professional-custom-knockback-and-hits-for-pvp.42721/

Hit Delay
Hit Cooldown
Knockback

**Comment by TheWranger** [comment]
I still really don't see the need to have a replacement for OldCombatMechanics built-in because of how well it does its job and how it isn't a small plugin like FastPot or NoHitDelay are.

**Comment by Drc-DEV** [comment]
Anyways OldCombatMechanics has a lot of bugs for me 1.13.2, so having a stable and well-done all in one pvp management system inside of CMI would be a better solution for me at least.
