### ISSUE TITLE
HomeGUI Bug?

### ISSUE THREAD

**Issue by MrMorganCz** [Zrips/CMI#1333]
Home GUI doesn't not work. (not react to click)

Server is running in offline mode
---

**Cmi Version (using`/cmi version`):** 
CMI 8.3.8.1
Spigot 1.12.2-R0.1-SNAPSHOT
Vault 1.6.11(+)

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 

This server is running CraftBukkit version git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Is this only for Home gui? And does those home locations are valid? And double check if you can use them with OP which could mean that there is something wrong with player teleportation to that location which could be unsafe or similar thing and player been prevented to teleport there.

**Comment by SmallSansSerif** [comment]
I also have this. Have confirmed it's same for OP and normal players. Text commands still work.

**Comment by MrMorganCz** [comment]
> Is this only for Home gui? And does those home locations are valid? And double check if you can use them with OP which could mean that there is something wrong with player teleportation to that location which could be unsafe or similar thing and player been prevented to teleport there.

It does not work  /home (GUI) so /homes (GUI) text display works without any problems. Other GUI from the plugin too. I will make a video and upload it to youtube ... (tomorrow)

**Comment by MrMorganCz** [comment]
> Isint this was fixed with latest build?

Yes it's fixed and it works. Thank you :)
