### ISSUE TITLE
[Error] /cmi search caused lag and crash

### ISSUE THREAD

**Issue by Segysmundo** [Zrips/CMI#1336]
Used **/cmi search oversize** and this error started spamming the console, eventually the server started lagging until it crashed.

[**Error**](https://pastebin.com/hserhzTF) <- Line 245 Server crash

Cmi Version: **8.3.7.3**

Server Type: **Paperspigot 1.12.2**

**Comment by Zrips** [comment]
Those messages seem to point out to older or newer versions of achievement files which been tried to load and failed at some point. Which one was it? Transfered from 1.11 or older version to 1.12.2 or from 1.13 to 1.12.2?

**Comment by Segysmundo** [comment]
From 1.11 to 1.12

**Comment by Zrips** [comment]
Will slowdown slightly search function to allow server to catch up with everything to avoid this freezing when we have to perform more actions then we usually do.
