### ISSUE TITLE
[Request] Message setting for warn, ban, tempban command

### ISSUE THREAD

**Issue by FestusDM** [Zrips/CMI#1339]
Currently when `/warn`, `/ban` `/tempban` is issued, it will send out a public message that the player has been warned/banned/tempbanned for a certain crime.

It would be awesome to have a feature that let admins chose if such messages will be displayed out in public chat or just message to the individual. 

Thanks for all the hard work.
---
**CMI Version: 8.3.8.1**
**Server Type: Paperspigot 1.13.2-R0.1-Snapshot**
**Server Version: 1.13.2**

**Comment by TheWranger** [comment]
Can't you do this silently like other commands by adding -s onto the end? Or do these commands not support that?

**Comment by FestusDM** [comment]
-s does work behind these commands but it doesn't automatically send a private message to the player that he's been warned.
Is that feature available automatically? Or only if we set up some kind of custom alias?

**Comment by TheWranger** [comment]
Didn't realize silently warning didn't send a message to the warn player. Definitely something that needs to be changed.
I don't really use CMI to handle punishments so nothing else I can give info on.

**Comment by Zrips** [comment]
@FestusDM Will fix that thing with warn. But for ban and temp ban you don't need to send message as that because they are getting kicked automatically from server with ban reason anyways.
