### ISSUE TITLE
World Guard Region Weather-Lock Broken

### ISSUE THREAD

**Issue by MCTyler** [Zrips/CMI#134]
The only other Plugin I can think of for Weather control is CMI. Is this the case?
![2018-03-15_07 07 06](https://user-images.githubusercontent.com/6390898/37462437-ec548ecc-281f-11e8-9879-1ace379f3e47.png)

**Comment by Zrips** [comment]
./cmi pweather
if its not set, then its not a CMI

**Comment by MCTyler** [comment]
Ok, Just have to wait for WG to Update I guess....

**Comment by MCTyler** [comment]
EDIT: It was the latest Version of WG 6.2.2 rolled back to 6.2.1 and all is well.
