### ISSUE TITLE
automatic get kicked by server

### ISSUE THREAD

**Issue by tianji1993** [Zrips/CMI#1342]
**Description of issue or feature request:**
server always kick me after typing part of commands while the autofill part generating, details see the screenshot
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**

error happens while CMI installed:
![abnormal_with_cmi](https://user-images.githubusercontent.com/5179956/51654767-56b8f300-1fd4-11e9-9a68-25a7ed47b2d9.gif)
error disappeared after CMI removed:
gif larger than 10MB so I upload it to my website:
http://tu.tianji.link/images/2019/01/24/normal_without_cmi.gif

---

**Cmi Version (using`/cmi version`):** 
8.3.8.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper(507) 1.13.2-R0.1-SNAPSHOT, latest WaterFall bungee.
**Server Version (using `/ver`):** 
Paper(507) 1.13.2-R0.1-SNAPSHOT, latest WaterFall bungee.

**Comment by tianji1993** [comment]
@Zrips could you help me?

**Comment by TheWranger** [comment]
What does the error say in english?

**Comment by tianji1993** [comment]
The server your were previously on went down, you have been connected to a fallback server

**Comment by Zrips** [comment]
Well you are using LuckPerms tab complete which causes that issue, so i would suggest to send this issue to developer of that plugin as i'm not really related here. I don't know how he handled permissions from CMI but they are in nice ENUM format so it should be relatively straight forward thing to handle. But in any case, update your LuckPerm plugin to latest version and if issue persists, get in contact with plugin developer (luckPerms)
