### ISSUE TITLE
Error in Locale_CN.yml

### ISSUE THREAD

**Issue by WOo0W** [Zrips/CMI#1348]
Lines 412 to 423 should be deleted.

![image](https://user-images.githubusercontent.com/24245520/51735539-a0800700-20c2-11e9-8d3b-2c380c2ce89e.png)

At line 523, `commandAddInformationHover` should be fixed.

![image](https://user-images.githubusercontent.com/24245520/51735719-1b492200-20c3-11e9-94c6-c399983ee819.png)

```yml
  commandAddInformationHover: |-
    &e[玩家名]可用于获取玩家昵称。要在命令中包含延迟,请键入: 
    &edelay 5!
    &e同时也支持特定指令。更多信息请参见
    &ewww.spigotmc.org/wiki/cmi-specialized-commands/
```
---

**Cmi Version (using`/cmi version`):** 8.3.8.1

**Comment by Zrips** [comment]
Thanks for pointing that one out, will remove them.
