### ISSUE TITLE
Statsedit <player> play_time

### ISSUE THREAD

**Issue by MCTyler** [Zrips/CMI#135]
I am not able to edit The Players PlayTime Stats. I try with the command above but that stat doesn't exist in tab complete except in cmi player info and trying to edit play_one_tick does nothing at all. I would assume 1 tick = 20 sec.

**Comment by LogGits** [comment]
Works for me. 
`/cmi statsedit [playerName] add play_one_tick 2000`

**Comment by LogGits** [comment]
:o This appears to be buggy. Typing `/cmi statsedit ToXiicalhebest take play_one_tick 2000 -s` causes my playtime to go up by 33 mins. Can't take time away from players.

**Comment by MCTyler** [comment]
I did 3 statsedit takes of 3000 ticks on myself and my PlayTime is still the same.
![screenshot from 2018-03-16 05-38-18](https://user-images.githubusercontent.com/6390898/37516517-62130258-28dc-11e8-8e62-ead14f8fb65d.png)

**Comment by MCTyler** [comment]
Would the Plugin Statz interfere?

**Comment by MCTyler** [comment]
@LogGits I'm thinking MySql might be the cause of all the problems with PlayTime. Players are reporting that they lose time when the server restarts. Is There a way I can export the MySql to the flatFile and just use that?

**Comment by Zrips** [comment]
Next version, should be fixed.

**Comment by MCTyler** [comment]
7.4.6.1 is bugged will wait for next version to confirm fix.
