### ISSUE TITLE
CMI right-clicking homes.

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#1350]
I have these settings disabled in config.yml

BedInteraction: false
  # Removes bed location when home location was created by clicking on that bed
  RemoveBedLocationOnBedBreak: false

It still tells me I created a home in chat when I right-click a bed. I want to disable home creation when clicking a bed. Thanks

**Comment by TheWranger** [comment]
Are you sure players don't have the permission to bypass?

**Comment by 0xC1A551C** [comment]
Thanks didn't realize there was a bypass permission since I was op.
