### ISSUE TITLE
[Bug] Hologram Edit Text Line + [ERROR] Hologram Command Deletion

### ISSUE THREAD

**Issue by Relaxing9** [Zrips/CMI#1358]
**Description of issue or feature request:**

When editing a hologram line and typing **cancel**, the hologram reader is not cancelling the action and instead is replacing the line with **"cancel"**

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**Image Example:**
[Imgur](https://i.imgur.com/hbHCRnl.png)

**Cmi Version (using`/cmi version`):** 8.3.9.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** Spigot 1.13.2-R0.1-SNAPSHOT

**Comment by Relaxing9** [comment]
Tried to delete a hologram command and by accidentally **double clicked** on it and got a nice long error in console.
[https://pastebin.com/UujHjEez](url)

**Comment by Zrips** [comment]
Will be fixed with next build.
