### ISSUE TITLE
[Support] 1.13.2 unbreakable?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1359]
In 1.12.2 we could use /cmi unbreakable, but now in 1.13.2 we're getting notified to use /cmi enchant, however, I am not sure how?

Would love to learn how to make an item never have durability go down so a player would never have to repair it.

**Comment by Zrips** [comment]
As of 1.13 version Mojang moved unbreakable meta data to basic enchantment and now you can enchant your tools to never loose durability. That old command are still valid, but you will get notification to use enchant command and you can simply use **/cmi enchant [playerName] unbreaking 1** command

**Comment by mrfloris** [comment]
Uhm, I am confused .. because enchant player unbreaking 1, will just give unbreaking 1 to the tool, using it the durability goes down, it will show as "unbreaking i", using /cmi unbreakable does work as a command, you get unbreaking 1 on the tool, but using the tool and durability will go down.

Maybe I don't understand this or am confused, but using 'unbreakable', i assume this means durability should not go down at all. So you never have to repair it. 

Heres' a video showing me using latest cmi + latest spigot 1.13.2 on a stone shovel where i used /cmi unbreakable and durability is going down. 

there's no /cmi enchant player unbreakable , and unbreaking 1 just gives durability 1. 

https://youtu.be/P4JUEDGkeeg

**Comment by Zrips** [comment]
Ok, this should not work properly with 1.13 servers, so unbreakable command is no longer deprecated and will work as in previous versions.
