### ISSUE TITLE
Spam errors

### ISSUE THREAD

**Issue by kforbro** [Zrips/CMI#1364]
**Description of issue or feature request:**
I make hologram with placeholders, but in console flood errors, when I'm near the money hologram. The kills hologram dont send errors
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR**
```
https://hastebin.com/idizupinez.md
```

**CONFIG SECTION:**
```
https://hastebin.com/ubejuzerup.bash
```

---

**Cmi Version (using`/cmi version`): 8.3.7.3** 

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): 1.12.2** 

**Relevant plugins (Delete if this isn't needed): PlaceHolderApi, Vault, Luckperms**

**Comment by Zrips** [comment]
Had to be fixed with latest builds.
