### ISSUE TITLE
/home GUI waiting time bypassed

### ISSUE THREAD

**Issue by Xylella** [Zrips/CMI#1365]
**Description of issue or feature request:**
If a player teleports to a home using the new **/home** GUI there's no waiting time, it's teleported instantly. It doesn't happen with the direct command **/home <HomeName>**

**Cmi Version (using`/cmi version`):** 8.3.9.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** CraftBukkit version git-Spigot-642f6d2-fbe3046 (MC: 1.12.29) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by AntoineHrn** [comment]
Got the same problem, so I confirm what she said

**Comment by Zrips** [comment]
Will be fixed with next build.
