### ISSUE TITLE
Kit preview "time in seconds" always has the same time as cooldown?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1366]
Technically I am asking this as support, is the preview supposed to show the time of 1 minute in 60 seconds, and not say cooldown: 1 minute, in seconds: 22 left before it can use again" Because the /cmi kit itself shows it with the cooldown and then the time left. Indirectly I kind of expected the preview to also use the time-left in seconds. 

If it is supposed to show the time left, then I guess this is a bug report?

https://youtu.be/3kXcNldK8o0

**Comment by Zrips** [comment]
Its not a bug by itself, it does show what it suppose too, in this case it shows kit delay in a formated way and a delay in seconds. It doesn't check what is the cooldown of that kit for that specific player. Duno if we actually need that, after all, you can see left cooldown on main GUI page already. It more like preview of kit setup, not what it is for you.
