### ISSUE TITLE
[Enhancement] Could you add logging for persistent chat?

### ISSUE THREAD

**Issue by OpalMoonstride** [Zrips/CMI#1369]
Persistent chat does not show in server logs, can you make it so that it does?

**Cmi Version (using`/cmi version`):** 3.9.2

**Server Type (Spigot/Paperspigot/etc):**  Paper spigot 

**Server Version (using `/ver`):**  1.13.2

I can see chat, unless it's persistent chat. It would be nice to at least send this to console for logging purposes / player complaints. Thanks!

**Comment by Zrips** [comment]
Will add extra output message into console when you have persistent chat enabled
