### ISSUE TITLE
New Gui Home -> Breaks warmups 

### ISSUE THREAD

**Issue by AntoineHrn** [Zrips/CMI#1373]
**Cmi Version (using`/cmi version`): Latest** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`): 1.13.2** 

All of my players can have no warmup for teleporting to homes by using the gui, they dont have any bypass permission

**Comment by Zrips** [comment]
Will be fixed with next build. Thanks for reporting.
