### ISSUE TITLE
Hologram GUI Derpyness

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#1375]
**Description of issue or feature request:**

The holorgram GUI is being a bit weird. I'd noticed in previous versions that while the GUI worked it sometimes needed a little extra attention when setting the hologram as interactable (once set it doesn't immediately work, have to go in a second time to set it again). Now it seems in the latest version I can't do much with the GUI with the interactable settings - had to edit from the yml file.

Example: https://youtu.be/963lRXjna_o

---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.3.9.3
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-f56e2e7-ad6070d (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Good point, some derpyness does happen now, will fix this one with next build.
