### ISSUE TITLE
[ERROR] Unhandled NPE

### ISSUE THREAD

**Issue by Relaxing9** [Zrips/CMI#1376]
**Description of issue or feature request:**
when running /cmi hat <random> got a null pointer exception in console see pastebin

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):** [pastebin](https://pastebin.com/6Czj666a)

**CMI Version (using`/cmi version`):** 8.3.9.3

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** This server is running CraftBukkit version git-Spigot-518206a-c4a67ee (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Relaxing9** [comment]
Another NPE, however its from another Event.

> ERROR Could not pass event InventoryClickEvent to CMI v8.3.9.3

[pastebin issue 2](https://pastebin.com/bUF9rn1H)

**Comment by Zrips** [comment]
First error was fixed with CMI8.3.9.4 update. For second one, will add some NPE catchers, but you got error in place where it should not happen in normal situations.
