### ISSUE TITLE
[Feature Request] Armorstand With Skins

### ISSUE THREAD

**Issue by Relaxing9** [Zrips/CMI#1377]
**Description of issue or feature request:**
Basically an option which allows a user to predefine the skin one armorstand uses, say you want to mimic a entity/mob and want to give it custom drops as equipment instead of having to put its skull as the head you can put equipment on it. Also would help if you wish to make an armorstand of a certain player and you would rather display their skin and not only their equip. Could be a skin request command then add the skin to the armorstand GUI.

**Comment by Zrips** [comment]
Armor stands are not the same as NPC which ones can only have skins.
