### ISSUE TITLE
Armorstand dupe

### ISSUE THREAD

**Issue by mab-ru** [Zrips/CMI#1379]
1. Open Armorstand GUI. Put item on head. Close GUI
2. Reopen GUI. You take the object with the left mouse and paint on the black glass and put in place (they will be 2) 
---
Cmi Version: 8.3.9.4
Spigot 1.13.2

**Comment by Baktus79** [comment]
I was just about to report the same. See the video below

---

https://youtu.be/QCB6vgc0Fw4

**Comment by mrfloris** [comment]
Thanks for reporting, I hope this gets resolved soon, meanwhile I've revoked armorstand editing from our higher groups.

**Comment by AntoineHrn** [comment]
Got the same issue.

**Comment by Baktus79** [comment]
#1399

**Comment by mrfloris** [comment]
Bumping for awareness as the dupe issue isn't fully fixed.
