### ISSUE TITLE
7.4.5.0 broke commandspy

### ISSUE THREAD

**Issue by tmellen** [Zrips/CMI#138]
We were excited to get /helpop back, but our staff members lost commandspy in this update. They could still do "/co l a:commands" through core protect, which showed them that players were typing commands... but they no longer saw them "live" in their chat boxes. They could still toggle the command on and off, but no "CSpy". Only OPs could see command spy messages.

Rolled back to 7.4.3.0 and command spy is working again for all staff.

**Comment by Zrips** [comment]
There was added additional permission node requirement cmi.security.admin to see all commands players are using, without it you will see only commands in list set in config file

**Comment by tmellen** [comment]
Ok thanks!! I didn't catch that.
