### ISSUE TITLE
Feature request: Commands as events

### ISSUE THREAD

**Issue by BeeRando** [Zrips/CMI#1382]
Basically, the ability to have a command as an event, which triggers certain things.

For example.
A player types a command, like /warp RomeArena.
Typing this command would issue one or multiple more commands to run.

For example
Eventcommand:
  Use: true
  Command: warp RomeArena
  List:
  - cmi money give BeeRando 10
  - cmi money take [playerName] 10

This ^ for example, is an idea my server had. A town can build a pvp arena, we can set a warp to it, and everytime someone warps there, they get paid. This event command option though could be used for so many other possibilities also.

**Comment by Zrips** [comment]
Not an option tho. But you do have aliaseditor, so disable alias in alias.yml for warp command, then create custom one with **/cmi aliaseditor new warp-cmi warp $1-** and add couple extra commands for it with + sign and you will have what you want.
