### ISSUE TITLE
tppos don't recognize username when username is number only

### ISSUE THREAD

**Issue by JokerLiuPro** [Zrips/CMI#1383]
**Description of issue or feature request:**

tppos don't recognize username when username is number only
For example:
**53421 is username**
cmi tppos 53421 -2703 21 1825 world_fm

It will teleport me to  X:53421 Y:-2703 Z:21 in World: world_fm

---

**Cmi Version (using`/cmi version`):** 8.3.9.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper(513) 1.13.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
I would strongly recommend to not allow users into server with only numbers in their names... That can and will cause more issues with multiple plugins. But will make fix for tppos command...
