### ISSUE TITLE
Ultra Permission and CMI wont work

### ISSUE THREAD

**Issue by kwab90** [Zrips/CMI#1384]
**Description of issue or feature request:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Default permissions wont go to the default rank and im unable to add them, the permission manager i use is UltraPermissions
---

**Cmi Version (8.3.9.4`):** 

**Server Type (11):** 

**Server Version (1.13.2):** 

**Relevant plugins (Ultra Permissions):**

**Comment by Zrips** [comment]
What default permissions we are talking here exactly?

**Comment by kwab90** [comment]
I’m sorry I’m just stupid I forgot to give the permission CMI.command

**Comment by Zrips** [comment]
cmi.command should be given for everyone by default unless its been negated by permission plugin itself. There have been some issues with that permission plugin as it tend to remove default permissions given by plugin... Will make some changes which should address this issue. And you can always try to add that permission to your permission plugin setup as a default one.
Test next version and give me a shout if its still and issue.
