### ISSUE TITLE
Nameplate colors

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#1386]
The only way I got nameplate colors to work with cmi was enabling a glow and turning it off. The nameplate prefix does not change the users's nameplate name color, could that be an option? Or is there another way to have colored nameplates without glows with cmi that I'm not aware of?

**Comment by Zrips** [comment]
Will add /cmi nameplate [playerName] -c:[color] to change name color without enabling glow effect. Tho glow will override this one, but on disable will keep predefined color.
