### ISSUE TITLE
[Feature request] Check if player have empty inventory

### ISSUE THREAD

**Issue by Angelfox28** [Zrips/CMI#1388]
I refer a question expressed on discord by Meldiron:
> Meldiron
> Is there a way to only do something in CMI if players inventory is empty?
> 
> /event
> - teleport to specif location (specific world) but only if player has empty inventory. If not, throw some error

My addition: Also including armor and second hand slots

This is a a good feature. Meaby can be a "CMI Specialized Commands" so it will be used in Portals, scheduler, etc..

**Comment by Zrips** [comment]
Next udpate
