### ISSUE TITLE
Feature Request: A Player Online Placeholder That don't count Vanished Players. 

### ISSUE THREAD

**Issue by RustyDagger** [Zrips/CMI#139]
Hello, Recently came across this issue where i have online players show on the TAB menu as a count 2/20 etc.
My issue Arises when vanished staff are still counted so there might be 10 players and 2 vanished staff online the Placeholder shows 12 but its not hard for players to count the list of players shown in the TAB menu for them to realize they only see 10 names thus the Usefulness of vanish is Limited,

maybe something like. %cmi_visible_player_count%

**Comment by LogGits** [comment]
I believe `%server_online%` does this already as it is a CMI placeholder. Let me know if it works for you. Keep in mind if your opped you will see the correct playercount.

**Comment by RustyDagger** [comment]
Not the case sadly I dont hand out OP on my server Thats what permissions are for.

Just tested it again with an alt account and me in vanish the player count still shows 2 players even when he cant see my name on the TAB list.

**Comment by LogGits** [comment]
Please update your CMI, @Zrips has added this in the latest build 🙂 "`%cmi_server_online% %cmi_onlineplayers_names% %cmi_onlineplayers_displaynames%` should ignore vanished players now"

**Comment by Andreychik32** [comment]
Haven't found this placeholder in wiki. Please add them there ASAP.

https://www.spigotmc.org/wiki/cmi-placeholders/
