### ISSUE TITLE
Interactive Commands

### ISSUE THREAD

**Issue by LovesAsuna** [Zrips/CMI#1390]
Interactive commands cannot use commands from other plugins

**Comment by mrfloris** [comment]
Make sure you run the command as a player, and if they are say `fromConsole! .. or !cc!` that those plugins support running commands as console. I use IC a lot and use commands from loads of plugins.

**Comment by LovesAsuna** [comment]
Could you make an example？ I want to set up "mv tp [playername]world" as console

**Comment by mrfloris** [comment]
Here's a video where I make a bedrock respond with left click to a player in survival, with and without console doing 'mvtp [playerName] world'

https://youtu.be/W0v7jnVJLl8

More information about cmi ic here; 
https://www.spigotmc.org/wiki/cmi-interactive-commands/

**Comment by Angelfox28** [comment]
You can also use /cmi tppos (playerName) [x] [y] [z] (world) (pitch) (yaw) (-rng:[range]) (-s) 

Teleports player to defined location. If -rng is defined, then player get teleported to random location by x and z locations from target location.

**Comment by LovesAsuna** [comment]
sometimes I want player use this to cross server

**Comment by LovesAsuna** [comment]
> Here's a video where I make a bedrock respond with left click to a player in survival, with and without console doing 'mvtp [playerName] world'
> 
> https://youtu.be/W0v7jnVJLl8
> 
> More information about cmi ic here;
> https://www.spigotmc.org/wiki/cmi-interactive-commands/



> 这是一个视频，我通过左键点击生存中的玩家做出基础回应，有和没有控制台做'mvtp [playerName] world'
> 
> https://youtu.be/W0v7jnVJLl8
> 
> 关于cmi ic的更多信息; 
> https://www.spigotmc.org/wiki/cmi-interactive-commands/

I have watched your video and I know how to set up.Thanks
