### ISSUE TITLE
[Support request] Multiple questions, Database structure, bungee, eco

### ISSUE THREAD

**Issue by slaapkopamy** [Zrips/CMI#1391]
**Description of issue or feature request:**
In this request i have multiple things so here is a little list where i need support for.
- Database structure: global or different database names.
- What kinda bungee support is there?
- Shop?
---

Hi there,

I asked in the discord server multiple times on different timestamps on people who use this plugin with the questions is it smart to connect cmi to a global database what sync everything to every single server in my network. But nobody can answer this so i got the tip to place it here as support request.

The question about global database is just about i don't want sync my eco balance with survival and skyblock since survival have another eco system then skyblock has. So it is not smart in my brains to sync that things. right? just in little words if i connect it to global what sync it with all servers?

The other questions is, i saw that the plugin does has portals build in but is it the portals like bungee portals or just only as warp portal? And the same thing as above, what kinda things does it sync with other servers in the network connected via mysql?

Shop.. I have used in the past essentials sign shop (build in) but my question is does cmi have a shop build in too? for example selling wood or what ever. If not what can i use it then? 🤔 

**Cmi Version (using`/cmi version`):** 
enabled on the server: 8.3.9.2
update downloaded: newest version (8.3.10.0)

**Server Type (Spigot/Paperspigot/etc):** 
spigot: 1.13.1 (all servers)

**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-2440e18-4228a56 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Current sate of plugin is ix between one table for all servers and each server should have its own. Best way to go is to have separate tables for each server as there is no 100% multiserver support currently. This will require allot more work to sync data across servers.
Bungee support is minimal, is some sense. But at same time you could have same database for multiple servers and players balance will be transferred across multiple servers, there are options to force save/load which enables this. But at same time, there are no forced sync mechanic which would sync actions from server A to server B while target player is on server C and so on.
Shop is tricky one, you could settup admin shop with dynamic signs and intractable commands feature. But currently there are no dedicated shop engine implemented, yet. 
Portals are universal, what that means that you can teleport to same server location or to another server on bungee network if that one has CMI installed. And it can perform any command you want, so it could simply send player to target server if you dont want to teleport him to specific CMI portal location on another server, which is possible. 
And for shop, you do have sellhand feature implemented. Normal shop (similar to essentials...) is planned to be added at some point.
