### ISSUE TITLE
Group Chat Format not working

### ISSUE THREAD

**Issue by odie8800** [Zrips/CMI#1393]
**Description of issue or feature request:** Group chat formatting doesn't work.  I see that there have been an issue with this in the past, yet it still doesn't seem to work and on that ticket there weren't any guidelines as to how to resolve this issue. I've added the correct permissions onto my groups.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):** Just uses 'GeneralFormat' format, instead.
```

![](https://i.gyazo.com/706eb9bf3d60354769fa1c5491b34edc.png)

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
![](https://i.gyazo.com/a1070f11736b3b9c05f51744d57e5317.png)

(I tried un-hash tagging the generalformat, but that didn't do anything either.)
```
---

**Cmi Version (using`/cmi version`):** 8.3.10.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.13.2 R1

**Comment by odie8800** [comment]
Fix found, you HAVE to use numbers for the [id]. However, it would be great if you could implement alphabets into the [id] in the future.

**Comment by Zrips** [comment]
Well it did said that you need to use numeric values, will add extra comment to make it more clear for others.
