### ISSUE TITLE
OP's don't show up on join/leave

### ISSUE THREAD

**Issue by Naschultz24** [Zrips/CMI#1394]
Players who have operator permissions (/op) will not show in chat when they join/disconnect.
I am using Ultra Permissions, and tried negating the disable message which made it appear in chat. However, if a player has operator permissions, regardless if I have negated the permission to them personally a message will still not show up in chat.

Cmi Version 8.3.9.4

Server: 1.13.2 Spigot

Server version: CraftBukkit version git-Spigot-fe3ab0d-162bda9 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Relevant plugins: UltraPermissions, not sure if that matters.

Also my first post, apologize if I formatted this incorrectly.

**Comment by Zrips** [comment]
If you have enabled custom login messages, then you will need to negate cmi.messages.disablelogin permission node to show login message as OP players has every permission by default.

**Comment by Naschultz24** [comment]
In the config i disabled the login/quit so it would show, enabled custom login messages, and I negated the perms to the groups and it works. However, i tried negating the perms on myself for example but it still would not show the message.
