### ISSUE TITLE
Autorank Converter?

### ISSUE THREAD

**Issue by kelso6969** [Zrips/CMI#1395]
**Description of issue or feature request:**
Autorank is used by a ton of people, and it lacks some basics. I've been eyeballing this plugin for a while now as it can replace 7-8 of my plugins, reducing the footprint by quite a bit!

I would love to see an easy way to convert playtimes from Autorank to CMI. 

Its MySQL based, which looks to be easily accessible.
MariaDB [minecraft]> select * from totalTime where UUID = '47ce7feb-e2eb-4d7a-af4f-f7edd9c62397';
+--------------------------------------+-------+---------------------+
| uuid                                 | time  | modified            |
+--------------------------------------+-------+---------------------+
| 47ce7feb-e2eb-4d7a-af4f-f7edd9c62397 | 11614 | 2019-02-06 23:01:28 |
+--------------------------------------+-------+---------------------+

I could easily write a script to pull this data and insert it into CMI after I look through table structures, but would love to save some time and not have to do this. :)
---
**Server Type (Spigot/Paperspigot/etc):**  Spigot
**Server Version (using `/ver`):** 1.13.2

**Comment by Zrips** [comment]
Why does autorank saves playtime? Its already been saved at player data file and at stats file.

**Comment by kelso6969** [comment]
it stores daily, weekly, monthly stats for leader boards. These are less important to me. So if you're able to use existing player data so ranks don't get screwed up, I guess I'm ok then.
