### ISSUE TITLE
[Bug] Armorstand editor dupe glitch

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#1399]
**Description of issue or feature request:**
The armorstand dupe glitch still exist on 8.3.10.0
See the video for description of the issue.

https://youtu.be/4Dw2Qor9oXw

The original dupe bug is gone and was fixed with this new update, but this dupe bug is still there.

---

**Cmi Version (using`/cmi version`):** 8.3.10.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 514 MC1.13.2

**Comment by SirGoldman-git** [comment]
Can confirm on last version.

**Comment by Zrips** [comment]
Thanks for informing about this. Partially rolled back previous changes made for it which introduced this glitch while solving other issue... Should be ok with next build. I hope this is last time...
