### ISSUE TITLE
Issues with the placement of player model with /ride

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#14]
When you are riding another player, the player that you are riding will not be able to see anything as your player model is half way in their head.

**Comment by Zrips** [comment]
Not really possible as players position is being controlled by minecraft it self, unless we would add one extra invisible entity in between players to get him higher. This would introduce more complex code and more possible bugs/issues.

**Comment by LogGits** [comment]
Ah ok I see, don't worry about this request.
