### ISSUE TITLE
[Suggestion] /warp toggle to keep old locations

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1400]
Currently when you change the location where a cmi warp ends, the warp disappears from the /warps overview, this is quite annoying and I can't find an option to 'keep' broken warps. 

We usually just switch an area over due to evens, season changes, themes, or updates. 

We would love to just open the broken warp and click on 'set new location' so we don't have to re-add it, customize it, position it in the overview etc, each month/time we change things.

**Comment by Zrips** [comment]
Could you elaborate more on this one? Changing destination of warps will not remove it from warps list. Or i'm misunderstanding whats going on with it? And what exactly are those "broken" warps?

**Comment by mrfloris** [comment]
We for example set a warp, but if we unload the world the warp is gone from the /warps menu the next time we restart the server.

Or if we have a warp but the player updates the area quite a bit and there's no air in that spot, it seems on server restart those warps disappear as well.

**Comment by Zrips** [comment]
Good point, found issue with that, should be fixed with next build. Warps will be ignored in warps gui/list but they will remain in records for future use.
