### ISSUE TITLE
Error support economy 1.13

### ISSUE THREAD

**Issue by annemettean** [Zrips/CMI#1403]
**Description of issue or feature request:**
CMI does not support balance coding in skript on 1.13, plz get det support, because I really want to use CMI on my server.

Can you update the Vault version to your plugin and update CMIEInjector? so it support 1.13 skript economy.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
CMI 8.3.10.0

**Server Type (Spigot/Paperspigot/etc):** 
Spigot 1.13.2

**Server Version (using `/ver`):** 
1.13.2

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
You will need to be more specific then this. Which plugin it is exactly? Link to it. 
And in general, every script based plugins are terrible at performance, so any other plugin would be allot better choose.
