### ISSUE TITLE
[Bug?] cmi cplaytime player always seems to display 0 seconds

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1405]
https://i.imgur.com/YfM6tkM.png

The previous hour is always 0 seconds, even though you are in the game for a minute, 15 minutes.. 

latest spigot, latest cmi build.

**Comment by Zrips** [comment]
its previous hour, what means that if your current time is 15:30 then previous time is between 14:00 until 15:00

**Comment by mrfloris** [comment]
Ok, I understand that. Thanks for explaining.
