### ISSUE TITLE
Worth For Spawners

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#1406]
Worth.yml
  SPAWNER>PIG: '2500.0'
  SPAWNER>COW: '2500.0'
  SPAWNER>CHICKEN: '2500.0'
  SPAWNER>SHEEP: '5000.0'
  SPAWNER>HORSE: '10000.0'
  SPAWNER>MULE: '10000.0'
  SPAWNER>ZOMBIE_HORSE: '400000.0'
  SPAWNER>SKELETON_HORSE: '15000.0'
  SPAWNER>VILLAGER: '500000.0'
  SPAWNER>SQUID: '500000.0'
  SPAWNER>PARROT: '100000.0'
  SPAWNER>MUSHROOM_COW: '25000.0'
  SPAWNER>POLAR_BEAR: '400000.0'
  SPAWNER>WOLF: '50000.0'
  SPAWNER>OCELOT: '50000.0'
  SPAWNER>RABBIT: '150000.0'
  SPAWNER>BAT: '75000.0'
  SPAWNER>LLAMA: '150000.0'
  SPAWNER>IRON_GOLEM: '400000.0'
  SPAWNER>SPIDER: '25000.0'
  SPAWNER>CAVE_SPIDER: '75000.0'
  SPAWNER>ZOMBIE: '10000.0'
  SPAWNER>SKELETON: '10000.0'
  SPAWNER>WITHER_SKELETON: '150000.0'
  SPAWNER>ENDERMAN: '400000.0'
  SPAWNER>ENDERMITE: '1000000000.0'
  SPAWNER>SILVERFISH: '1000000000.0'
  SPAWNER>STRAY: '25000.0'
  SPAWNER>WITCH: '150000.0'
  SPAWNER>CREEPER: '250000.0'
  SPAWNER>BLAZE: '100000.0'
  SPAWNER>SHULKER: '500000.0'
  SPAWNER>HUSK: '25000.0'
  SPAWNER>GUARDIAN: '250000.0'
  SPAWNER>PIG_ZOMBIE: '400000.0'
  SPAWNER>ZOMBIE_VILLAGER: '400000.0'
  SPAWNER>SLIME: '250000.0'
  SPAWNER>TURTLE: '100000.0'
  SPAWNER>DOLPHIN: '250000.0'
  SPAWNER>DROWNED: '50000.0'
  SPAWNER>PHANTOM: '500000.0'

https://gyazo.com/490ee69233ba99f45117c30bbfabfbb7

Every spawner is worth $2,500 when I run /worth on a spawner. Using latest version of CMI | Paper 521

**Comment by Zrips** [comment]
Next update will be fixed
