### ISSUE TITLE
Request - Greeting/Farewell message upon entering/leaving a defined area

### ISSUE THREAD

**Issue by WarmasterCain55** [Zrips/CMI#141]
I would like the ability to define an area, either like piggybacking off of world guard or some other kind of area selection, I would like the ability to set a message when you enter an area a message pops up and another message when you leave the area.

**Comment by mormoon** [comment]
Seems a little redundant when you have world guard allready installed. Since you can allready do that with worldguard.

https://worldguard.enginehub.org/en/latest/regions/flags/

**Comment by Zrips** [comment]
Well... interesting enough we do have portal system which should be named something like "area commands" or something. Its already performing commands when you enter that particular defined area, we could simply add option to perform commands when leaving it too. Will keep this in mind.

**Comment by WarmasterCain55** [comment]
Actually the reason why i ask is because despite our attempts, we cannot get that greeting/exit flags to work at all so I'm looking for alternatives.
