### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by MrApocalyptic** [Zrips/CMI#1412]
I was wondering if you could add an option to change the name of mob heads that are dropped, and to change the names of mob spawners for each mob like for example have a zombie spawner be &aZombie &fSpawner or a blaze spawner be &6Blaze &fSpawner. Thanks for you time have a great day =D

**Comment by Maevaen** [comment]
add also lore please, like this we can put the price of the spawner on lore, and + player cant edit it, so players cant sell fake spawner !

**Comment by Zrips** [comment]
Will add option to define custom names for custom mob heads with next update.
