### ISSUE TITLE
Elevator wont always work

### ISSUE THREAD

**Issue by Varipa** [Zrips/CMI#1416]
**Description of issue or feature request:**

---Elevator function is wrong!

**> **ERROR (DELETE IF YOU HAVE NO ERROR):**
> ```    [16:11:44] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.3.9.4
>     org.bukkit.event.EventException: null
>     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:955) [SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
>     at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
>     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
>     Caused by: java.lang.NullPointerException
>     at com.Zrips.CMI.AllListeners.PlayerListeners.findTeleportLocation(PlayerListeners.java:1117) ~[?:?]
>     at com.Zrips.CMI.AllListeners.PlayerListeners.PlayerInteractEvent(PlayerListeners.java:1073) ~[?:?]
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
>     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
>     at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
>     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[SpigotGit.jar:git-Spigot-e8ded36-acbc348]
>     ... 17 more**

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
I've always been the same as the tutorial, but he still has an error.

**Cmi Version (using`/cmi version`): 8.3.9.4 - 8.3.10.0

**Server Type (Spigot/Paperspigot/etc):** paperspigot 1596

**Server Version (using `/ver`):1.12.2

**Comment by Zrips** [comment]
Should be fixed with next update, tho i wonder which block was in particular which caused this issue. Could you show picture of those 2 places where signs have been located?
