### ISSUE TITLE
Warp other Player (as Mod / Admin)

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/CMI#142]
can you / cmi warp [player] [warpname] set that as a mod / admin warpen other players?

Currently I have "There is no warp by this name"

**Comment by Zrips** [comment]
Because warp name goes first and then player name, so **/cmi warp spawn Zrips**

**Comment by HomeLandingsDE** [comment]
oh my bad sorry - I had thought all along that it would be different - I'm sorry

**Comment by Zrips** [comment]
No problem, just don't forget that you can always double check commands capabilities with **/cmi warp ?**
