### ISSUE TITLE
[Issue] Variable "all" doesn't works in console

### ISSUE THREAD

**Issue by Angelfox28** [Zrips/CMI#1420]
I try to perform `cmi money take all 5%` from console but it doesn't works.
The issue is `all`

**Cmi Version (using`/cmi version`):** 8.4.0.0 also in 8.3.10.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper version git-Paper-1596 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
the issue actually is 5%. As to take that amount we need to check players balance. Will fix it with next update.
