### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Relaxing9** [Zrips/CMI#1425]
Was trying to create a jail, typed /cmi jailedit, and of course I do not have any jails, so I clicked the '+' and it gave me the syntax used to make a jail, upon evoking the syntax I got a null , on the bright side, it did not appear as an error in red font, but gave unnecessary console spam. However in game it showed in red "Internal Error has occurred..."

---

[pastebin](https://pastebin.com/85Cw3WrG)

---

**CMI Version (using`/cmi version`):** 8.4.0.1

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-b0f4c22-d5e9688 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by mercurialmusic** [comment]
Got the exact same when trying to make a portal.

**Comment by Zrips** [comment]
Will be fixed with next build.
