### ISSUE TITLE
Bungee Staff messages

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#1426]
Thank you very much for the update but I cant seem to get it working. Updated both servers with the new cmi version, enabled staffmsg bungee on both and restarted the proxy and both servers but still cant see staff messages sent from each server, only local chat.

I would like to note that the placeholders for cmi bungee stuff (current players online) is working fine.

So not sure what I'm doing wrong, some help would be nice! :)

**Comment by Zrips** [comment]
Damit, i must be drunk or something... Even tho i don't drink... Its working, when you have persistent staffmsg chat enabled... Will fix it with next build.
