### ISSUE TITLE
Request: /cmi exp permission changes

### ISSUE THREAD

**Issue by iaxedu** [Zrips/CMI#143]
**/cmi exp** has the permission **cmi.command.exp** sadly this permission allows you to add a number of choice to your own exp. Do **/exp 1000** and 1000 exp gets added, do **/exp 1000000** and yes also thats gets added. 

Please change it so that **/exp 1000** needs a permission from now on.

**Comment by MCTyler** [comment]
Why do Players need /exp? It show here....
![screenshot from 2018-03-22 14-41-00](https://user-images.githubusercontent.com/6390898/37794316-2a46ed8c-2ddf-11e8-95e9-477f7ace4a8b.png)
