### ISSUE TITLE
[offon] color code error

### ISSUE THREAD

**Issue by odie8800** [Zrips/CMI#1432]
**Description of issue or feature request:**
In the Locale_EN.yml file, the [offon] variable doesn't seem to accept color changes.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://gyazo.com/f555ff36d9e52a55c8be9d64f4132999
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
https://gyazo.com/770915ac15a24d16f39021c40fff94e9
```

---

**Cmi Version (using`/cmi version`):** 8.3.10.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.13.2 RO.1-SNAPSHOT

**Comment by odie8800** [comment]
Same error for [time], the color coding for this variable also doesn't work.

**Comment by Zrips** [comment]
They are separate variables by itself and you can find them at 
info_variables_Online
info_variables_Offline
in locale file. So if they have color codes already then it will not work when adding them separately. Remove color codes from base variables and then you can have them as you want for each output.
