### ISSUE TITLE
Feature request: Vanished players count placeholder

### ISSUE THREAD

**Issue by Andreychik32** [Zrips/CMI#1434]
As stated in #139, `%cmi_server_online%` doesn't work as supposed to. It just shows current player count with vanished players lile `%server_online%` does.

What I suggest:
Please, add something like `%cmi_vanished_player_count%` which will return **only vanished** player count or make `%cmi_server_online%` count **only non-vanished** players.

**Comment by Zrips** [comment]
This should return now player count depending on who you can see
