### ISSUE TITLE
Bungee question

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#1438]
Just wondering if there's a way to have ban, mute, tempban, go cross server or apply to every server?

**Comment by MrMorganCz** [comment]
Plugin is not very customized for use on bungee...
But if you use the same database so yes all the bans and punishment will apply elsewhere.
But it's much better to use a different punishment plugin than you do if you want to use bungee.

**Comment by Zrips** [comment]
Yea, Cmi is not 100% compatible with BungeeCord and things like bans will not apply on other servers. Atleast not at this moment.
