### ISSUE TITLE
False fly permission

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#144]
We are running a small server where only staff has permission nodes for /fly. Lately, when a new player joins for the first time and issues /fly command they are set to true even though they don't have the permission node for it.

**Comment by LogGits** [comment]
Output of `/cmi version`? Version of spigot/paperspigot? What permission plugin are you using (so i can attempt to replicate)? What is the output of `/cmi haspermission <player who can fly> cmi.command.fly`. Make sure you are using `cmi.command.fly` permission node.

**Comment by CypherPhyre** [comment]
It turns out that my other dev was trolling me and kept changing flight charge to true. No longer an issue.
