### ISSUE TITLE
Colored tab names disappear after logging off and also when using /v

### ISSUE THREAD

**Issue by Royster0** [Zrips/CMI#1442]
**Description of issue or feature request:**
I've noticed that since Version 8.3.10.0 players with colored tab names disappear when they log off and return to white when they log on. It was working fine in ver 8.3.9.4.

Also players with access to /v also lose their colored tab names, and this has been an issue for a while. Is this something that can be very easilly fixed? Especially the issue where they disappear after loging off and then logging back on

**Cmi Version (using`/cmi version`):** 
8.4.0.0
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
514

**Comment by Maevaen** [comment]
me i lose color on tablist but im the only who can see my name in blank ! the other player see my name colored !!

**Comment by Royster0** [comment]
Bumping as this was working prior to 8.3.10.0

**Comment by glorying16** [comment]
Also having this issue. I am not using any of the tab features for CMI, nor plugins to edit it at all. Im only using the vanilla scoreboard.

**Comment by Royster0** [comment]
Bumping again because this is somthing that is useful when working

**Comment by Royster0** [comment]
Bumping again because the color names in tab was working in a previous version. /v issue needs sorting ASAP as well

**Comment by glorying16** [comment]
Sadly still an issue. Also, this is not just with coloration but any scoreboard teams.

**Comment by glorying16** [comment]
For those of you who are not using any of CMI's tablist features, one of the more recent updates added a line in the Modules.yml for tablist. It is default to true. Changing it to false gave me back the tab list colors, which have stayed after logs and (im pretty sure) restarts. Chances are Zrips forgot to mention it in one of the large updates. 

> # Handling of tablist
# Applies for servers from 1.7.x and up
tablist: false
