### ISSUE TITLE
Feature Request on TimedFlight

### ISSUE THREAD

**Issue by kelso6969** [Zrips/CMI#1443]
**Description of issue or feature request:**

Currently, timed fly is bought with EXP, i use TimedFly which is less then stellar and buggy. I want people to be able to buy flight time, say 10 hours, for xxxx in game money. Looks like you mention this might come in the future, but this is my request to help push that. :)

"Players can buy fly charges by using exp or money (possible item thingy in future updates)."
https://www.spigotmc.org/resources/timedfly-3-mysql-support-1-8-1-13.48668/
thats the plugin I'd love to get rid of.

**Comment by Zrips** [comment]
/recharge will open gui where you can recharge flight points with EXP or Money. Values are adjustable in config file
