### ISSUE TITLE
permission plug-in compatibility

### ISSUE THREAD

**Issue by kadika66** [Zrips/CMI#1444]
---My default rank currently has the permission CMI.command As well as many cmi.spawn and cannot use / home / spawn / Warp 15.02 23:34:09 [Server] INFO In
![jpeg_20190216_162759](https://user-images.githubusercontent.com/12194400/52989899-242fc980-33cb-11e9-876a-c2142c07d37d.jpg)
![jpeg_20190216_162733](https://user-images.githubusercontent.com/12194400/52989904-27c35080-33cb-11e9-86bf-a69e14fc41eb.jpg)

finiteOnes doesn't have permission for: cmi.command this is my permissions plugin 
ultra permissions

**Cmi Version (using`/cmi version`):** 8.4.0.2 

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):** 1.13.2

**Relevant plugins (Delete if this isn't needed):** https://www.spigotmc.org/resources/ultra-permissions.42678/

**Comment by Zrips** [comment]
Will make some adjustments, but in general ultra permissions removing default permission nodes which should be given out by default as defined in CMI plugin.yml file... Blame ultra permissions for this issue...
