### ISSUE TITLE
[CMI] Plugin CMI v8.4.0.3 generated an exception while executing task 1860934 java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1445]
we have had a continuous loop with version 8.4.0.3 with these errors in our console !!

Spigot-Vers:CraftBukkit version git-Spigot-e8d3881-c24abab (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

https://pastebin.com/98JND1nh

**Comment by Zrips** [comment]
This originates from your permission plugin, to be more accurate from here
ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:220) ~[?:?]
Get in contact with that plugin dev to make some adjustments for it
