### ISSUE TITLE
Playtime Rewards Error

### ISSUE THREAD

**Issue by CaliDreams** [Zrips/CMI#1446]
**Description of issue:**
Running console error with CMI 8.4.03 from Playtime Rewards file. Some months back, I customized Playtime Rewards slightly adding a /msg under commands section and It's worked fine in all past versions for months - I've only just run into this error today upon updating CMI with version 8.4.03.

---

**ERROR:**
####################
####################
```

**CONFIG SECTION:**
```
#####################################
#####################################
```

---

**Cmi Version:**
8.4.03 

**Server Type:** 
Spigot

**Server Version:** 
git-Spigot-b0f4c22-2ced023

**Comment by Zrips** [comment]
Will be fixed with todays update

**Comment by CaliDreams** [comment]
Awesome, thanks!
