### ISSUE TITLE
Staffwatch (new feature idea)

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#145]
A new command that will switch player inventory into staff watch with will include stuff like random teleport to player, an GUI with list of players who in this time mine and may be other cool stuff for staff to make it more easy for them

**Comment by LogGits** [comment]
Sounds cool. I do think a player list setup is overboard, maybe a command that you input a username into like `/cmi punish <player>`(e.g.). In terms of teleporting to a player. Cmi has a command called `/cmi patrol` which will teleport you to a random player to "patrol" them. It wont teleport you to a player who has already been patrolled unless all players have been patrolled. When all players have been patrolled it will go back to the first player.
