### ISSUE TITLE
schedules.yml no longer accepts format colors

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1451]
CMI Version:8.4.0.4
Spigot: CraftBukkit version git-Spigot-e8d3881-c24abab (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Since the latest CMI version, schedules.yml assumes one more color code.
The codes are only written out and do not show a color.

BroadCastVote:
  Enabled: true
  MinPlayers: 1
  Delay: 3600
  Repeat: true
  Commands:
  - broadcast! &b&l████████████████████████
  - broadcast! &b&l█                                             █
  - broadcast! &b&l█ &e&lHabt ihr heute schon gevotet? &3/vote &b&l█
  - broadcast! &b&l█                                             █
  - broadcast! &b&l████████████████████████
BroadCastLottery:
  Enabled: true
  PerformOn:
    Noon:
      Hour: 12
      Minute: 0
    Afternoon:
      Hour: 15
      Minute: 0
    Evening1:
      Hour: 18
      Minute: 0
    Evening2:
      Hour: 19
      Minute: 50
    Evening3:
      Hour: 21
      Minute: 0
    Midnight:
      Hour: 0
      Minute: 0
  Commands:
  - broadcast! &c&l███████████████████████████
  - broadcast! &c&l
  - broadcast! &e&l Habt ihr schon LuLuLose gekauft? &2/lotto
  - broadcast! &e Verlosung findet jeden Samstag um 20:00 Uhr statt!
  - broadcast! &c&l
  - broadcast! &c&l███████████████████████████

**Comment by Zrips** [comment]
Thanks for reporting, test out new version, should be ok now.
