### ISSUE TITLE
Various Questions

### ISSUE THREAD

**Issue by FestusDM** [Zrips/CMI#1452]
Attempted to ask these questions on Discord support. With no answer after 2 weeks, I thought I would ask here.

Questions:
1. Within the `config.yml` file, I see that there's a section that allows you to set up speeding of time when players are sleeping. But I don't see where to set the actual percentage? Does `BaseSpeed: 100` mean that 100% of players online need to sleep in order for night to be skipped?
And what about `MinSpeed: 5`?

2. How do you place clickable fonts inside a custom text?
Example: `Click (here) to see our Discord!` With here being a clickable URL. 

3. With CMI's compass death boss bar feature, is there a way to only allow death points to show up? Or is that (at this point) not customizable?

Thanks for the help 
---

**Cmi Version: 8.4.0.5** 

**Server Type: Paperspigot** 

**Server Version: Paper version git-Paper-518**

**Comment by Zrips** [comment]
Well discord some times gets clustered with messages and some gets "lost".
1. Speed is defined in how many times its moves faster then usual. So in this case 100 will be 100x times or 10 000% of original speed. Need to add clear comments for it.
2.  <T>Click</T><T> (here)</T><URL>discord.com</URL><T> to see our Discord!</T>
3. Compass is EXPERIMENTAL feature i made while messing around with the code. So at this point there is no option to make that happen, but i can add it.
