### ISSUE TITLE
Chat Colors issue

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#1454]
**Description of issue or feature request:**

---
The issue is that if a player types in anvil a color for example &1Test, it will not color it with is nice and good however if that player with that custom name &1Test Kill a player our type [item] while holding the item everyone one will see it in that color that was specified. This wasn't the case on older updates if I remember it correctly. If player has no permission to write in colors he should not be able to do that. With my players don't 
#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
No Errors
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.4.0.5
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot 1.13.2(525)
**Server Version (using `/ver`):** 
1.13.2
**Relevant plugins (Delete if this isn't needed):** 
The only plugin I think might have to do something with this issue is chatcontrol pro

**Comment by mercurialmusic** [comment]
So the item doesn't show the color when renamed on the anvil (correct behavior), but in the death message (which CMI doesn't handle) it uses the color code? Definitely sounds like ChatControl Pro if that's what handles your death messages. A plugin that doesn't handle death messages wouldn't be able to strip the color codes from death messages.

**Comment by arturek1666** [comment]
You might be correct about the death message however I did also say that if you also hold that item with &1Test it will also display in color even if player has no permission to be able to use colors.

**Comment by Zrips** [comment]
Will be fixed with next build.
