### ISSUE TITLE
Anti-afk with 1.13.2 water bubbles.

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1456]
It would be quite fantastic if the anti afk could also detect people trying to bypass it by standing in block of water with soulsand and just get pushed around. Going afk instantly goes back to anti afk.

**Comment by Zrips** [comment]
Cant really reproduce this one with latest build. Do you have AntiAfkMachines enabled? And if you can reproduce with latest version and with this enabled, can you provide gif or video of it in action?

**Comment by mrfloris** [comment]
Ok, i will go double check everything and if I can still reproduce it ill record a video.

**Comment by mrfloris** [comment]
With the latest version, I am unable to go anti afk when idling in water bubbles. So I am content, closing this.
