### ISSUE TITLE
[Bug] Afk fires double chat event

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1458]
**Description of issue or feature request:**

---
After being AFK, and starting to chat again, it appears that the chat event is fired twice.
This is causing a duplicate message, which triggers chatcontrol.
This seems to be the problem why the chat is denied.
The issue is explained here: https://github.com/kangarko/ChatControl-Pro/issues/1076
This bug is investigated by the dev of ChatControl. He points out the source of the issue

> Alright so after I installed CMI, the chat event started to be fired twice. This is a bug in CMI, please report to its developer. I am glad we are onto something.

**ERROR (DELETE IF YOU HAVE NO ERROR):**

There is no error. ChatControl warns the player:
`Please do not repeat the same (or similar) message.`
The message is canceled, atlhough the player is not repeating any previous message.
ChatControl is configured 100% working.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

Test scenario
Test server: CMI + ChatControl
```
Afk:
  Enabled: true
...
  AutoAfkIn: 30
```

---

**Cmi Version (using`/cmi version`):** 
Doesn't really matter. This bug is present for a while.
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.13.2 build 524
**Relevant plugins (Delete if this isn't needed):** 
CMI 8.4.0.5
ChatControl 7.13.0

**Comment by Zrips** [comment]
By itself CMI doesnt fire chat message twice. Did you tested this one with CMI only to rule out issue with compatibility with ChatControlPro?

**Comment by x1p** [comment]
With or without chatcontrol, there is no double message. That was never the issue here.
With chatcontrol and similarity check disabled there isn't a problem either. This similary check works perfect. It detects perfectly when a message is similar to the previous. As long as the player is not AFK, there is no problem at all.

The problem starts when a player is AFK and starts a message which breaks the AFK state. Even with   `DisableOnPublicChat: false`
I'm not a dev. So I can only believe Kangarko when he says that there are 2 chat events. He apparently tested with CMI. (See the issue there). How can we solve this?

**Comment by Zrips** [comment]
Yea, he is actually correct, this is issue with paper spigot slightly different handling of chat message. Will do some adjustments to eliminate secondary event. Even tho its been canceled which should be checked by ChatControl, but lets make it better.
