### ISSUE TITLE
Feature Request: Setting % sleeping player before night speeds up

### ISSUE THREAD

**Issue by FestusDM** [Zrips/CMI#1460]
Currently you can only set a number of players to sleep before the night starts speeding up.

Request:
Ability to set a % of players who needs to sleep before speeding up the night. Example: Setting 15% of players need to sleep in order for night to speed up.
---
**Cmi Version:** 8.4.0.6
**Server Type: Paperspigot** 
**Server Version:Paper version git-Paper-518**

**Comment by Zrips** [comment]
Next update will be added
