### ISSUE TITLE
Resetting playtime rewards

### ISSUE THREAD

**Issue by Naschultz24** [Zrips/CMI#1461]
This isn't necessarily an issue/bug, but just wondering how I can remove all player data related to playtime at the least -

I've been resetting a skyblock server and it has old players who i'd like to reset playtime, as well as some staff and people who have been working on the server have claimed playtime rewards

Is there a way I can reset all of this and also allow them to reclaim playtime rewards? Thanks!

**Comment by Naschultz24** [comment]
Mini update - I was going through and resetting all worlds to begin with and that actually reset playtime itself. The playtime rewards seemed to show all rewards again, but after a while it went back to only showing Daily, Hourly, 7d, and 30d rewards although I appear to only have 33min in-game time. Not sure where it is still saving my other in-game time, but I also went in the regular config and set OneTimeAmount to 10 to ensure it would show. But the main thing I notice is that the times are off, like the default daily reward is over 2 days; same with the hourly. Screenshot attached on imgur: https://imgur.com/a/b4sgShv

**Comment by Zrips** [comment]
Playtime can be taken from a player data file or from player statistics file, you can define that in config file. To reset those values you will need to remove appropriate files or use playtime edit command in game. Other then this you have 2 types of rewards, one is repeating and will give you reward every x minutes, another is one time reward and will be given out only once when you reach appropriate time frame.
