### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by Angelfox28** [Zrips/CMI#1463]
1) Aesthetic bugs in portal commands
In preview doesn't show the correct color format. In this case i use "msg! [playername] &D&LYOU CAN'T PASS HERE"
Commands editor ----> http://prntscr.com/mp1l3o
When I use the portal the colors are shown correctly ----> http://prntscr.com/mp1ljg

2) I don't hear the sounds when i use elevator, I open a GUI, or i go to some my homes. 
I tryed with /cmi sound and they work. I don't know why.

3) Isn't a bug, but with the new Specialized command "ifempty", there is no feedback message if the player doesn't meet the requirement to have something empty. Can you add some message in locale_EN for each variables (hand/offhand/quickbar/armor/inv/subinv)?

 CMI plugin version: 8.4.0.6
 Server version: Paper(1596) 1.12.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
1. Will be fixed.
2. It can be that default sound is not present in your version, as you do run older server. Check your cofig file at bottom and adjust it to fit your version.
3. Will be fixed
