### ISSUE TITLE
CMIPvPStartEventAsync Event

### ISSUE THREAD

**Issue by Dampen59** [Zrips/CMI#1465]
**Description of issue or feature request:**

CMIPvPStartEventAsync fires only on the player who get attacked, and not on the player who attacks.

**Cmi Version (using`/cmi version`):** 

Latest

**Server Type (Spigot/Paperspigot/etc):** 

Paper 1.8.8

**Comment by Zrips** [comment]
Good point, will make some extra adjustments for it too.
