### ISSUE TITLE
Ability to modify a spawnertype with egg in left hand

### ISSUE THREAD

**Issue by DonSensiLeone** [Zrips/CMI#1466]
**Description of issue :** 

Ability to modify a spawnertype with egg in left hand despite to permission negated , this message shows up in console : Don_Sensileone doesn't have permission for: cmi.egginteract. ....  .i tried without permission first and with the negated one , same result, i can change spawnertype with left hand , this is maybe not a bug but just an easy thing to fix , i hope it to get fixed soon :)

**Cmi Version (using`/cmi version`):** **8.4.0.7**

**Server Type (Spigot/Paperspigot/etc):** **Paperspigot**

**Server Version (using `/ver`):** **Paper(527) 1.13.2-R0.1-SNAPSHOT**

**Comment by Zrips** [comment]
Will be fixed with next build
