### ISSUE TITLE
[Request] Custom Recipe improvment

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#1467]
**Description of issue or feature request:**
---
I would love to see an option to chose how quick the furnace will make the custom item, as for now is really fast, I would basically love to be able to chose how quick in furnace the item will be created.

**Comment by TheWranger** [comment]
Don't think this is possible. All items in Minecraft have the same smelting time.

**Comment by arturek1666** [comment]
It can't be as the added item to furnace is melted 50% faster. Than other original stuff.

**Comment by arturek1666** [comment]
![furnance](https://user-images.githubusercontent.com/1558228/53412560-97d06880-39c1-11e9-94ee-c5ad8aa4d370.gif)
How you can see it's not normal xD

**Comment by Zrips** [comment]
Will be added with next build
