### ISSUE TITLE
Incorrect merchant trade window

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#147]
When issuing /cmi merchant librarian I get a librarian labeled trade window, but the trades are random, ie butcher, blacksmith, toolsmith, farmer, etc.

**Comment by Zrips** [comment]
It's vanilla behavior by using official API when setting villagers profession, so cant really fix that one.

**Comment by CypherPhyre** [comment]
Then can you make it so that the command is only /cmi merchant instead of needing to select a type?
