### ISSUE TITLE
%cmi_user_balance_formatted% Problem

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1471]
CMI Version: 8.5.0.0

Since the latest CMI version the placeholder " %cmi_user_balance_formatted% " does not work anymore. So that the money amount is no longer displayed correctly.

**Comment by mercurialmusic** [comment]
This was working correctly for me with 8.5.0.0. Perhaps it might be useful if you provide additional info about your server version and the config section, what the desired outcome is and what's actually happening.

**Comment by Blueeyestar** [comment]
our spigot version:CraftBukkit version git-Spigot-3cb9dcb-40cbae4 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

IN CMI version : CMI8.4.1.0 **%cmi_user_balance_formatted%** is still in the table list. from CMI version : 8.5.0.0 the placeholder is no longer displayed

**Comment by Blueeyestar** [comment]
Does nobody have any idea why only this placeholder no longer works and everyone else does?

**Comment by Blueeyestar** [comment]
After 2 hours of searching I have found the problem!!!!!

It is due to the line : 
# Currency symbol to be used when showing balance or similar
    CurrencySymbol: €

If you put a $ sign instead of € as currency the placeholder will not be recognized anymore.

Please check why the dollar symbol is no longer recognized!

**Comment by LogGits** [comment]
Do you have cmi's vault installed?

**Comment by Zrips** [comment]
This will be fixed with next update
