### ISSUE TITLE
Rankup particle / rankdown

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#1474]
Is it possible to change the particle when a player ranks up with /cmi rankup? Currently it is the default green dust.

Is there also a way to run a command only when ranking down with /cmi rankdown so that it can alter the player permissions properly? Currently it just re-runs the commands for the rank that you rank down too which results in a permission rankup.

**Comment by Zrips** [comment]
Currently particles are in development mode but i could add option to define some things for them or even allow full control over them. Tho this would require separate wiki page as it can be quite complex thing.
For rankdown i can add -cmds and -cost variables to by default avoid performing commands or charging player while ranking down and allow to define them when we need to charge player or to perform commands. So basically, next update.
