### ISSUE TITLE
/recharge - feature is not enabled since upgrade to 8.5.0.0

### ISSUE THREAD

**Issue by kelso6969** [Zrips/CMI#1475]
After upgrade to 8.5.0.0 last night, /recharge states the feature is not enabled. I couldn't find it in the new Modules.yml. I even tried added it thinking it might have been a mistake but didnt help. Worked fine prior to 8.5.0.0 release.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```
No Error
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 8.5.0.0

**Server Type (Spigot/Paperspigot/etc):** spigot

**Server Version (using `/ver`):** 1.13.2-r0.1-snapshot

**Comment by tianji1993** [comment]
got same problem here, already set flightCharge: true in Modules.yml, whatever I restart my server how much times, the /recharge function still cannot work, shows this module didn't active.
**Cmi Version (using`/cmi version`):** 8.5.0.1
**Server Type (Spigot/Paperspigot/etc):** Paperspigot
**Server Version (using `/ver`):** Paper(548) 1.13.2-R0.1-SNAPSHOT

**Comment by tianji1993** [comment]
@Zrips

**Comment by Zrips** [comment]
Will post new update which will fix this one today.
