### ISSUE TITLE
Editplaytime for offline players

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#1477]
Hejo,

It would be very cool if it would be possible to edit the playtime for offline players with the editplaytime command. I unfortunately have to migrate hundreds of playtimes manually due to the loss of an old system. Of course this doesn't work properly if the players are not online! I will gladly donate 20 Euro if the feature comes in the next update! But I'm also grateful for any feedback if the feature is too special or too complex to implement and therefore won't come soon at all.

**Comment by mercurialmusic** [comment]
There's probably a lot that goes into it, but I agree this would be quite useful. Especially after some of our players time "rolled over" and we needed to add the time back for them to receive the playtime rewards again, fixing that has been difficult without this ability.

**Comment by Zrips** [comment]
Will make it work with next update.

**Comment by TheoRetisch1** [comment]
The update works great and saves so much work! I donated as agreed :)

**Comment by TheoRetisch1** [comment]
It only worked until the first reload/server restart. Now you can only edit your own playtime. See also #1675! Sad story :(
