### ISSUE TITLE
Can't edit commandblocks

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#1479]
With CMI version 8.5.0.2 on version 1.12.2 it is not possible to edit command blocks. All spigiot settings are set correctly, if you deactivate CMI the editing works.

CMI: 8.5.0.2
Paper: 1.12.2 #1597

**Comment by LogGits** [comment]
Are you opped when trying to edit the Command Block?

**Comment by TheoRetisch1** [comment]
Sure! -> Op-permission-level=4, enable-command-block=true.

**Comment by TheoRetisch1** [comment]
It has nothing to do with CMI permissions, which I have negated for a test user. But as soon as I deactivate CMI, the problem no longer exists. I just have Essentials running parallel for conversion purposes, could it have anything to do with that?

**Comment by TheoRetisch1** [comment]
The mistake has nothing to do with Essentials. It took a while, but I found out that the problem is with the Skin module. If you disable the skin module you can edit command blocks pretty well. With the same setup but version 1.13.2 the problem doesn't occur! 

Skin config: https://pastebin.com/kp4CfeMT

**Comment by TheoRetisch1** [comment]
The problem also occurs in a similar way under version 1.13.2. If the skin module is activated and you change your skin, you can no longer edit command blocks. This only works again if you remove the OP rights once and then reassign it. This bug makes the system quite unusable, unfortunately.

CMI version 8.5.4.0
Paper-597 1.13.2

**Comment by TheoRetisch1** [comment]
Fixed in 8.0.0.1Experimental! Thanks :)
