### ISSUE TITLE
Players with permission to edit signs, changes not accepting.

### ISSUE THREAD

**Issue by Royster0** [Zrips/CMI#1484]
I have an issue with where players have the permission node to edit signs, yet when they try to change it, it doesn't change it. In the console its saying that they tried to edit a non-editable sign. Why is this happening? They're trying to edit signs, that they've placed, and they still get the issue.

**Cmi Version (using`/cmi version`):** 
8.5.0.2
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
Ver: 544

**Comment by Royster0** [comment]
Bumping as this is a feature thats still not working

**Comment by Royster0** [comment]
Please fix this issue ASAP, as this is still not working. Bumping

**Comment by Zrips** [comment]
This should not be the issue at this point
