### ISSUE TITLE
Panimation from console not finding target player

### ISSUE THREAD

**Issue by smellyonionman** [Zrips/CMI#1485]
Using panimation from console yields "Can't find player by this name."  The same commands work in-game, though.  It'll need to work from console to really be useful for script driven events, if you could please!

**Comment by stifflered** [comment]
It would be really great if this could be supported. Trying to use panimation with interactive commands results in "Can't find player by this name."

**Comment by Zrips** [comment]
Will make some adjustments for it to work from console. After all, this is more or less experimental feature.
