### ISSUE TITLE
Bug? Keep getting Missing Locale in command.Class.Info.Uses

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1486]
```
/cmi attachcommand !limiteduse:1!;;!cc!cmi panimation circle;effect:reddust;dur:5;pitchc:5;part:10;offset:0,1,0;radius:1;yawc:5;color:rs;target:[playerName]
```
https://i.imgur.com/yEttQxd.png

```
>about
[23:56:21 INFO]: This server is running CraftBukkit version git-Spigot-3cb9dcb-0f708cb (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[23:56:21 INFO]: Checking version, please wait...
[23:56:21 INFO]: You are running the latest version
>about cmi
[23:56:23 INFO]: CMI version 8.5.1.1
[23:56:23 INFO]: Powerful server management tool
[23:56:23 INFO]: Website: https://www.spigotmc.org/resources/content-management-interface.3742/
[23:56:23 INFO]: Author: Zrips
>
```

**Comment by BoosterBots** [comment]
I am noticing the same issue with multiple attach commands 

 just copied and pasted the exact code from the attached commands wiki and got this http://prntscr.com/mteebk

/cmi attachcommand !limiteduse:3!;;!cc!cmi tfly [playerName] 60

When I right click to use the tfly on the feather I get http://prntscr.com/mteiw3

**Comment by CaliDreams** [comment]
Same thing for me, this was my command:

/cmi attachcommand !limiteduse:5!;;!cc!cmi tp [playerName] Cali_Dreams

(also tried the example commands directly from the website)

Using Spigot 3cb9dcb-1dbe87c (two versions behind)

and CMI 8.5.1.2

**Comment by TheoRetisch1** [comment]
I have the same problem! The descriptions above are already very meaningful.

**Comment by mrfloris** [comment]
*friendly weekly bump* <3

**Comment by BoosterBots** [comment]
Would love to get this fixed! Been trying to make these custom items for weeks now

**Comment by CaliDreams** [comment]
I still made a whole bunch of fun limited-use items for my server - if it's a limited use of 1, you can just erase the error lore it generates after attaching command by doing /itemlore without adding an actual lore message. Or add your own lore ofc. The items still work/respect the limited use(s) despite the annoying error in chat and lore.
I also found a way around the items thinking I've multi-clicked as well by simply defining "!left!" or "!right!" or both. Hope that helps till Zrips can find a fix!

**Comment by BoosterBots** [comment]
Awesome thanks a lot for this @CaliDreams I will try implementing this today! I have a few limited use items I made before which still have their item uses on them but all my new ones don't display. I will give this a go.

**Comment by stickmenz2** [comment]
Also having this issue.

**Comment by mrfloris** [comment]
```
Small typo fix for default delete locale line
```
Changelog for https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/update?update=268430

Update and see if this fixes your problems?

**Comment by stickmenz2** [comment]
Not fixed

**Comment by TheoRetisch1** [comment]
Nobody said it was fixed? xD

**Comment by SeanWalk** [comment]
Not fixed

**Comment by mrfloris** [comment]
Could someone please confirm they still have this issue, otherwise I am closing this ticket tomorrow.

I haven't seen these in a while and haven't heard anybody else mention it.

**Comment by Zrips** [comment]
This should be fixed and working correctly with latest builds
