### ISSUE TITLE
Tablist bug

### ISSUE THREAD

**Issue by DinoTK** [Zrips/CMI#1488]
**Hello!
I have a bug (I think) when the tablist updates, the nametag from the players change into these 2 formats in the images below.**

I want the first format, but it changes to the 2nd format when the tablist update.

![image](https://i.imgur.com/DgIJHyB.png)
![image2](https://i.imgur.com/Yb0U6vZ.png)
---

**Cmi Version:** 8.5.1.0

**Server Type: **Spigot

**Server Version:** 1.13.2

**Relevant plugins:** DeluxeChat, UltraPermissions, UltraTags, NametagEdit and CMI
**UltraPermissions, UltraTags, NametagEdit is required for each one to work properly**

**Comment by 0xC1A551C** [comment]
I dont understand what you are trying to say. Which names change into what format?

**Comment by Zrips** [comment]
You will have this issue if you have more then one plugin updating players display name. Disable one of them to keep desired format.
