### ISSUE TITLE
Cant find player with this name!

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#1489]
**Description of issue or feature request:**

cmi sound block_beacon_ambient -p:1.5 -v:0.9 spawnworld -2008.5 93 -1707.5

If you run that from console it will say
```
cmi sound block_beacon_ambient -p:1.5 -v:0.9 spawnworld -2008.5 93 -1707.5=> [03:16:57 INFO]: Can't find player with this name!
[03:16:57 INFO]: Playing block_beacon_ambient at spawnworld -2009:93:-1708
```

But it still plays and works.

**Cmi Version (using`/cmi version`):**  8.5.1.1

**Server Type (Spigot/Paperspigot/etc):**  paper

**Server Version (using `/ver`):**  1.13.1

**Comment by Zrips** [comment]
Will be fixed with next update
