### ISSUE TITLE
new cmi can't load

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#1497]
![image](https://user-images.githubusercontent.com/5382252/53713703-c6998380-3e86-11e9-9934-77d74e6eb3d9.png)

**Cmi Version (using`/cmi version`):** 8.5.1.1

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.12.2

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Will be fixed with todays update.
