### ISSUE TITLE
Specialized command that can bypass a permission

### ISSUE THREAD

**Issue by DaveDevil** [Zrips/CMI#1499]
**Description of issue or feature request:**

I was wondering for a specialized command that allow me to create items that temporaly bypass a permission.

Here's an example, similar to what I want to do:

I create a stick named "Thor's hand". I add the "cmi smite" command to the item, with a duration (30 uses). This way, the player can't smite where he's looking at because he's lacking the permission cmi.command.smite. I can't use "asConsole!" because it's impossible from console to smite where a player is looking at.

---

---

**Cmi Version (using`/cmi version`):** 8.5.1.2

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-b0f4c22-bc99dfe (MC: 1.13.2)

**Comment by Zrips** [comment]
bperm:[value][@][?][#]!
