### ISSUE TITLE
Armor Stand Command

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/CMI#15]
please add the command set to the Armor stand. which starts when the player clicks on the Armor stand. but it would be good for Armor to stand if the command is set to be edited so it can not be modify

**Comment by Zrips** [comment]
Can you explain this one more time, cant really get what behavior of armor stand you want exactly.

**Comment by TheTopCz** [comment]
I would like to add the function to run the command after clicking on the armor Stand...

**Comment by LogGits** [comment]
You can use `/cmi ic` for this 🙂

**Comment by Zrips** [comment]
Yea, if you want to perform commands on armorstand click, then simply use IC feature which can perform any command or commands on click.
