### ISSUE TITLE
./back issues

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#150]
Here's just a few things that /back gets effected by. Players complain about it constantly.

-Server auto teleport down feature if it suspects someone flying (this is the default feature and the AAC feature as well gets effected)
-Hitting the world border and it knocking you back
-Diamond elevators
-Eating chrous fruit
-Using an ender pearl

Not sure if these were intended, players have just been driving me up a wall. The essentials /back doesn't seem to get triggered by any of these. 

Note: Still on cmi 7.4.2.0, not sure if any of these are addressed in the newest but I don't believe they have been addressed.

**Comment by Zrips** [comment]
Will be addressed in next build.
