### ISSUE TITLE
[Enhancement Request] PAnimation Support in Kits

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#1506]
**Description of issue or feature request:**

Possibly related to #1485, I know it's still new and a work in progress, but we really love the panimation feature and would love to see it usable in kit commands with the {USERNAME} variable as a valid target (or [playerName] added to kits. :3) Currently it gives the same "Can't find player by this name" error.

That has been so much fun to play with, though, and thanks for adding it!

**Cmi Version (using`/cmi version`):** 
8.5.1.2
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-3cb9dcb-0f708cb (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will be working correctly with next build
