### ISSUE TITLE
[Suggestion] - Improving /cmi help

### ISSUE THREAD

**Issue by ghost** [Zrips/CMI#1507]
Hi there, the current /cmi help is very great because users can only see the CMI commands that they have permission to. But could it be also customizable so that it shows commands from other plugin that user has the permission to show? And the admin could customize the description and arguments for the command itself.

**Comment by Blackdigits** [comment]
Is bumping allowed here?

**Comment by Zrips** [comment]
In general thing like this should be done separately. You can simply use custom text feature which allows you to show bunch of information with pagination, hover over messages and so on. CMI is already checking bunch of permission nodes when player runs help command, tho it has some cache to prevent unneeded checks, but to have it to check for every other plugin is just overkill.
