### ISSUE TITLE
[Bug] Player collision

### ISSUE THREAD

**Issue by BeeRando** [Zrips/CMI#1511]
Player collision doesn't work. Players can still be pushed with it disabled. Even if both players have collision disabled, they will still be pushed. 

**Cmi Version (using`/cmi version`):** 
8.4.1.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
craftbucket spigot 1.13.2

**Comment by Zrips** [comment]
This can be issue with 3rd party plugin utilizing scoreboard teams. Cant really resolve this issue at this point.

**Comment by mrfloris** [comment]
We haven't done any updates to plugins besides keeping cmi current, player collision is no longer happening. The only scoreboard we have is from mcMMO, which has been the same for ages.

**Comment by Nesseley** [comment]
I also have an issue with collisions after updating CMI today. 
Before I updated playercollisions was working as they should, after updateing they no longer work. And I have to manually enable /playercollision for every player for it to work again.

**Comment by Drakanoiderna** [comment]
I made a test only cmi,  same problem i can walk true mincarts.  I did a new install first run it work but not 2 time i restart server.
