### ISSUE TITLE
Vote placeholder suggestion 

### ISSUE THREAD

**Issue by ozm8** [Zrips/CMI#1512]
Hello I have a suggestion. With the voting section of the cmi config add a placeholder so when it broadcasts a message when someone votes it can say where they voted/what site they voted on.

**Comment by TobiTechCZ** [comment]
If it's one such suggestion, I'm not going to open a new topic and post it here. I'd like to have a placeholder of %cmi_votetop_votes_[1-10]%, so that this is the number of votes.

**Comment by Zrips** [comment]
%cmi_votetop_[1-10]% was added in recent updates
