### ISSUE TITLE
Elevator Bug in gamemode 0 - block above sign needed

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#1516]
There must be a free block above the elevator sign. If there is no free block above the sign, you will not be teleported in gamemode 0. In gamemode 1 you are teleported even if there is no free block above the elevator sign. The elevators on the picture therefore only work in gamemode 1: https://imgur.com/a/XbUKfd9

_CMI plugin version: 8.5.1.2
Server version: Paper(1604) 1.12.2-R0.1-SNAPSHOT
Vault version: 1.6.1(CMIEInjector)_

**Comment by Zrips** [comment]
Will be fixed with next build
