### ISSUE TITLE
CMI Economy Injector load order

### ISSUE THREAD

**Issue by DaveDevil** [Zrips/CMI#1518]
**Description of issue or feature request:**

I converted an old skyblock server from essentials to CMI. Using CMI's vault, uSkyBlock have many bugs because it depends from original Vault.
Using Vault with CMI Economy Injector, then I have problems with EconomyBank, which loads before CMI injects the Economy, so it deactivates itself.

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Not an error. Part of log files, you can see that the EconomyBank
plugin loads before CMI Injector:

[Server] INFO [MysqlEconomyBank] Enabling MysqlEconomyBank v1.12.1
[Server] ERROR [MysqlEconomyBank] Warning! Vault installed? If yes Economy system installed?)
[Server] INFO [MysqlEconomyBank] Disabling MysqlEconomyBank v1.12.1
[Server] INFO [MysqlEconomyBank] MysqlEconomyBank is disabled!
[Server] INFO [CMIEInjector] Enabling CMIEInjector v1.0.2.1
[Server] INFO [CMIEInjector] Injecting CMI Economy
[Server] INFO [CMIEInjector] [Economy] CMI Economy found: Waiting

```
---

**Cmi Version (using`/cmi version`):** 8.5.1.2

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):** git-Spigot-596221b-9a1fc1e (MC: 1.12)

**Relevant plugins (Delete if this isn't needed):** 

EconomyBank: https://www.spigotmc.org/resources/economy-bank.7674/

**Comment by spannerman79** [comment]
@DaveDevil open up the CMI injector jar, edit plugin.yml and edit line 6 to `loadbefore: [ASkyBlock, AcidIsland, MysqlEcoBridge, MysqlEconomyBank]`

Original line `loadbefore: [ASkyBlock, AcidIsland, MysqlEcoBridge]`

Ensure you use something that can handle correct file editing (Notepad++, Atom, etc).

**Comment by DaveDevil** [comment]
This worked, thanks

**Comment by spannerman79** [comment]
Which method @DaveDevil ? So that @Zrips knows so that the `plugin.yml` can be updated for the injector if its needed to be changed within the injector jar.

**Comment by DaveDevil** [comment]
I added MysqlEconomyBank to line 6 in CMI injector

**Comment by Zrips** [comment]
Will be adding MysqlEconomyBank into line 6 for the injector, just for others to avoid this inconvenience.
