### ISSUE TITLE
Online/offline management permission

### ISSUE THREAD

**Issue by Rukes** [Zrips/CMI#152]
Hey Zrips,
I really like that possibility to manage any player, offline or online. I wanna allow Helper team manage only online player. Like open inventory or ender chest (primary) only if player is online, heal or enable fly, god only if player is onlike. This would be pretty nice to add, because Admins team will be allowed to manage offline players.

Thanks, Rukes.

**Comment by mrfloris** [comment]
Technically you could already do this by not granting them the permission, but using console commands with `ifonline:$1?#! cmi command $1` for custom alias like `/modinv playername` to let mods view inventory of set playername. 

while admins can just use the regular commands.
