### ISSUE TITLE
Player not visible in tabliste

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1520]
Spigiot Version: CraftBukkit version git-Spigot-3cb9dcb-77ca7ca (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

CMI Version: CMI v8.5.1.2

With our server it happens again and again when one logs in again that one cannot see certain users any more in the tab list. Only if you ask the user to log in again you can see him again in the tab list. Does the problem still have one ?

**Comment by BoosterBots** [comment]
I am noticing this at times with 1.12.2 as well. Running CMI CMI8.5.1.2

**Comment by Zrips** [comment]
Should not really happen anymore.
