### ISSUE TITLE
ItemWillBreak in Locale. Off by one? 

### ISSUE THREAD

**Issue by PsychoLynx** [Zrips/CMI#1522]
**Description of issue or feature request:**

Hello! I run a server with CMI to alert players when their tools are about to break, with the current message in Locale_EN:

ItemWillBreak: '!actionbar!&cYour [itemName] will break soon! ([current] uses left)'

The problem here is that the [current] durability variable seems to be off by one, either due to a bug or design - i.e., the message the player gets when their tool breaks is "Your [itemName] will break soon! (1 uses left)" instead of "(0 uses left)". If this is intended behavior, could an option be added to get a [current-1] placeholder, because it's driving some players (including myself) a bit crazy :)

Thank you kindly in advance!

**Comment by Zrips** [comment]
Will get fixed with next update
