### ISSUE TITLE
Don't set a backpoint for worldedit navigation jump tool

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#1524]
Worldedit is one of the most widely used plugins at all, and the navigation tool is correspondingly popular. If you click with the compass you can teleport a configured distance to the front. 
Unfortunately, a backpoint is set after each teleport. This should be turnable, otherwise the back function loses its sense. 

The option "BackMinDistance: 200" is only helpful to a limited extent, because the players often use the back function within their structures. After a longer test period it turned out that the players are more fucked up about a distance limitation than about the unpleasant compass port problems. 

So it would be awesome if you could deactivate the placing of a back location for the worldedit wand tool!

**Comment by spannerman79** [comment]
Just block/deny the permission node...

**Comment by TheoRetisch1** [comment]
Why should I take a player permission for a useful and popular feature. Both /back and compass port are given as part of a reward system. The players are much happier with a bad compromise than they would be with the final abolition. We should aim for a solution and not the elimination of a feature. "BackMinDistance" doesn't exist without reason, it was a compromise. Is your first reaction to a problem always the bin?

**Comment by Baktus79** [comment]
#1541

**Comment by Zrips** [comment]
@TheoRetisch1 In general BackMinDistance is a compromise for your issue. But will make some changes to exclude we jumping around with next version.

**Comment by TheoRetisch1** [comment]
That sounds awesome! The players will be delighted 👍
