### ISSUE TITLE
[Suggestion] /invlist more info

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#1525]
I would love to see how much of exp/level player had on death as it's a bit important information. Somewhere where player location is in /invlist
I did check that it is storing the exp on death as if you return the inventory to owner the exp is returning so that good but I would love to display the amount of exp when viewing :) player inventory on death

**Comment by Zrips** [comment]
When you open inventory to preview it, you can check exp he had on death. Its book icon on top.
