### ISSUE TITLE
Ensuring that players can’t run /cmi command

### ISSUE THREAD

**Issue by FestusDM** [Zrips/CMI#1528]
A couple people have asked this so I thought I'd submit something here.
 
Currently, players can run the `/cmi` command and they will see this:
[https://i.imgur.com/m4g8vyG.png](url)
Is there any way to prevent players from running this? 
Thanks for the help

---
**Cmi Version (using`/cmi version`): 8.5.1.3** 
**Server Type (Spigot/Paperspigot/etc): Paperspigot** 
**Server Version (using `/ver`): git-Paper-518**

**Comment by Zrips** [comment]
Well it is help page to list out all commands they have access too. Will add option to show generic "No command" when using /cmi without defining correct sub command.
