### ISSUE TITLE
Bug in item cost when renamed or with lore

### ISSUE THREAD

**Issue by FaMa91** [Zrips/CMI#1529]
Hi,
we made this custom alias:
  test:
    Cmds:
    - item:374-1#?! expcost:1395#?! moneycost:3000?#! perm:cmi.custom.exp?#! asConsole!
      cmi kit EXP [playerName]

this is meant to remove 3000 of money and 1 glass bottle to give a kit, it works well with vanilla items, but if the player has a glass bottle renamed or with a custom lore, the command gives kit without removing the item.

It should remove the item anyway, or fail as if player doesn't have the item.

Thank you.

```
**Cmi Version (using`/cmi version`): 8.5.1.2

**Server Type (Spigot/Paperspigot/etc): Spigot

**Server Version (using `/ver`): 1.12.2

**Comment by Zrips** [comment]
Will get fixed with next update.
