### ISSUE TITLE
Attachcommand questions

### ISSUE THREAD

**Issue by Rukes** [Zrips/CMI#153]
Well,
I dont know how to attach command on tool with clicked-player's name placeholder. With essentials powertools I can do this:
`/pt spawn {player}` (clicked player will be teleported to spawn).
How can I do this with CMI, without executing command from console, but from player with placeholder?
And second question, how can I remove ALL attached commands from tool? I didnt find it anywhere.

Thank you, Rukes.

**Comment by Zrips** [comment]
./cmi attachcommand cmi spawn
By default commands on click will be performed as it would be by player who used item
And to clear commands use /cmi attachcommand -c

**Comment by Rukes** [comment]
Okay, but how can I perform a command on clicked player? Like example, teleport clicked player to spawn?

**Comment by Zrips** [comment]
For this you can use !cc! variable so that command will be performed from console, like
/cmi attachcommand !cc!cmi spawn zhax

**Comment by Rukes** [comment]
I know, but I told you without executing it from console. If I allow support team executing commands from console, they will be allowed to do anything, so I wanna make it like essentials powertools, where commands are executed from player, where you can click any player and execute command with their name. Such like example `/pt spawn {player}` (clicked player will be teleported to spawn).

**Comment by Zrips** [comment]
Och, ok, now i got it. Will add separate variable to insert name of player you interacted with

**Comment by Rukes** [comment]
Nice! Thank you.
