### ISSUE TITLE
Cooldown timer is broken

### ISSUE THREAD

**Issue by impmallet** [Zrips/CMI#1530]
Issue: Cool downs never expire. For example, if I set a cooldown of 1 hour on /cmi home, no matter how long a player waits to run the command, it always says 1 hour remaining when the command is run. As I only started using this feature recently, I cannot say when this became an issue.

CMI plugin version: 8.5.1.3

Server Version: git-Spigot-3cb9dcb-8b1588e (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by impmallet** [comment]
I was testing other commands, and it appears that only /home is exhibiting this behavior.

**Comment by Andreychik32** [comment]
+1 for that. Same issue here.

**Comment by impmallet** [comment]
This is still an issue as of 8.6.1.0

**Comment by impmallet** [comment]
Still an issue as of 8.6.4.1

**Comment by Zrips** [comment]
Should be up and running with recent versions
