### ISSUE TITLE
Kicked whilst connection to survival: You can't login from this ip address 

### ISSUE THREAD

**Issue by AloneSpace** [Zrips/CMI#1533]
**Description of issue or feature request:**

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
Kicked whilst connection to survival: You can't login from this ip address 
####################
```
---

**Cmi Version (using`/cmi version`): CMI8.5.1.2** 

**Server Type (Spigot/Paperspigot/etc): Spigot** 

**Server Version (using `/ver`): 1.13.2** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by LogGits** [comment]
This could be potentially related to `/cmi lockip` try using `/cmi lockip ?` to get a list of the sub-commands.
