### ISSUE TITLE
Tab format issue

### ISSUE THREAD

**Issue by DinoTK** [Zrips/CMI#1538]
**The tab formatting is changing ...**

On my server I have 2 username formats:
One for the chat (with DeluxeChat and UltraPermissions) and one for the nick in-game (with UltraTags and NametagEdit, that adds the custom group hover above the head).

All these plugins work perfectly together, but when I put the cmi started with this problem.

And the problem is that these two formats are changing in the tablist, but I want to keep only one.
Video of my tablist:
**[Video](https://i.imgur.com/k837nGu.gif)**

**Cmi Version:** 8.5.1.3
**Server:** Spigot 1.13.2 
**Relevant plugins:** UltraPermissions, UltraTags, NametagEdit, DeluxeChat.

**Comment by Zrips** [comment]
DisplayName -> Change set to false to avoid CMI changing players display name if you have other plugins controlling this.
