### ISSUE TITLE
Kit cooldown time not working

### ISSUE THREAD

**Issue by abhisantos** [Zrips/CMI#1539]
**Description of issue or feature request:**
Kit cooldown time does not work on mysql. Even if I set cooldown for 30 days, when using mysql players can get the kits everyday with no cooldown...
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
No error
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
5.1.2
**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
1.8.8 snapshopt R01
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Do you perform server restart every day? If so, does that mean that players cant get kit and it shows correct cooldown timer until that restart? This can narrow down cause of issue
