### ISSUE TITLE
Prevent modify bypass

### ISSUE THREAD

**Issue by Rukes** [Zrips/CMI#154]
Permissions `cmi.command.inv.preventmodify` and `cmi.command.ender.preventmodify` are useful for ex. Admins team to prevent modify by support team. But admins cannot modify admins, can you add `.bypass` to both permissions to prevent support team modify admins team and allow admins team modify everyone (include admins team)?

I know its a bit silly, but needed. :joy_cat: 

Thanks, Rukes.

**Comment by Zrips** [comment]
Next update
