### ISSUE TITLE
Custom alias permission glitch

### ISSUE THREAD

**Issue by abhisantos** [Zrips/CMI#1540]
**Description of issue or feature request:**
The custom alias feature has a permission glitch!
When you set an alias for example for the /fly command, lets say, i set the alias /voar for the /fly command. Players with no /fly permission can use /voar and lfy without permission!
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
5.1.2
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.13.2
**Relevant plugins (Delete if this isn't needed):**

**Comment by spannerman79** [comment]
This is intended.

Using a custom alias is just remapping to the original command.

For example;
`/short` is an alias of `/somebigarsedlongcommand with nbt tags`, so when i send `/short` it executes `/somebigarsedlongcommand with nbt tags` and if `/somebigarsedlongcommand with nbt tags` has a needed permission node permissions are still checked.

**Comment by abhisantos** [comment]
I don`t think I expressed myself right..
So, if a player doesn`t have permission for /fly, i set an alias /aliaseditor new myfly-fly
what happened is, players without fly permissions were able to use /myfly  and fly normally...

**Comment by spannerman79** [comment]
I am not at my server console at the moment but if you use your permission managers debug you will be able to track down which permission node is being called.

**Comment by Zrips** [comment]
@abhisantos 
Well you are correct. This is some what glitch, tho you can avoid it by using full command name and not alias, as now you are creating alias for an alias which causes this issue. Will try to figure out where and why exactly it does this and fix it with next build.
