### ISSUE TITLE
[Bug] FlyAboveRoofLimitations does not detect Elytra flying

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1542]
**Description of issue or feature request:**

---
Flying with an Elytra will easily get you above the roof set by FlyAboveRoofLimitations.
Just fly with an Elytra + rockets or Trident + Riptide.

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION:**
```
WorldLimits:
  FlyAboveRoofLimitations:
  - world-500
```

---

**Cmi Version (using`/cmi version`):** 
8.5.1.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.13.2

**Comment by Zrips** [comment]
Will get fixed with next build
