### ISSUE TITLE
Things that dont work in Version 8.5.1.4

### ISSUE THREAD

**Issue by Royster0** [Zrips/CMI#1545]
Ok, these are things that seriously need to be addressed urgently as they dont work correctly:

1) Players in the tab list that have a team and color assigned are removed after they log off. This was working fine in Version 8.3.9.4
2) Players with the vanish permission are also removed from teams and color is removed when they execute the command. This hasnt been working for a while.
3) Players with the ability to edit signs, repeatedly get the issue that they cant edit them. The console shows that they tried to edit a non-editable sign. (Also this effects me and and have OP lvl 4)
4) Books show the color codes (Others have reported this)

Ive had to revert back to using 8.3.9.4 because the versions after break these, especially the tab list.

**Cmi Version (using`/cmi version`):** 
All versions from 8.3.10.0
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot Ver566
**Server Version (using `/ver`):** 
1.13.2

**Comment by Zrips** [comment]
1. By any chance you have disabled some of the modules which could be related to team color? Like name plates or something like that?
2. About which command we are talking here? /cmi vanish?
3. Can you provide more info on this one? Like are we talking here about /cmi se command or shift+right click?
4. Again, hard to understand what the issue is in particular. Should books not show color codes? Should they avoid to translate them when you creating one? As we do have permission node for it cmi.colors.books.[color] which allows usage of color codes in the books

**Comment by Royster0** [comment]
I have a test server which has the current version of CMI on and im using that to corrispond to the issues below:

1: Can confirm that module name plates is not disabled. Also noticed that when a player logs on, if you do /team list, CMI creates multiple teams like CMINP1, CMINP2 and so on, and allocates them to each player. Not sure when that happened but in 8.3.9.4 it only creates one team CMICol.
2: Yes, /cmi vanish or /v. When you use it, it removes the color in the tab. However, if you use /gamemode command, it doesnt remove the color.
3: They have the permission nodes to run the command /shifttoggleedit (didnt know there was a /cmi se command) and edit signs but when they shift click and try to edit the sign, it doesnt edit them and reverts them. Also if they used color codes, it even shows the color codes on the sign after the revert.(even if they have the perm to use colors on signs). Again I have OP lvl 4 and I get the same issue as them.
4: Books shouldnt show the color codes once they've been signed. I believe this is what the issue is. (as reported by others)

Please note that for points 1 and 2, im using the vanilla style commands. I am not using the CMI inbuilt tab.

**Comment by TheoRetisch1** [comment]
I can confirm the problem with editing signs.

**Comment by Royster0** [comment]
Looks like Ver 8.5.3.0 fixes the color codes in books issue :D So that leaves points 1, 2 and 3 to fix please.

**Comment by Royster0** [comment]
Bumping this as Parts 1,2 and 3 are still outstanding.

**Comment by Royster0** [comment]
Ok, can you please fix the 3 outstanding issues:

1: Players in the tab list that have a team and color assigned are removed after they log off. This was working fine in Version 8.3.9.4
2: Players with the vanish permission are also removed from teams and color is removed when they execute the command. This hasnt been working for a while.
3: Players with the ability to edit signs, repeatedly get the issue that they cant edit them. The console shows that they tried to edit a non-editable sign. (Also this effects me and and have OP lvl 4)

Especially issue 3 because that doesnt work properly at all and others have confirmed it doesnt.

**Comment by Zrips** [comment]
More or less all issues should be resolved now.
