### ISSUE TITLE
Mobhead in CMI version 8.5.2.0 

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1547]
In the CMI version 8.5.2.0 there are no more different heads displayed when entering /cmi mobhead.  Es only the standard heads are shown. When generating the customHeads.yml file, each head is now default:

sheep:
    DropChance: 1.0
    LowerWithEachDrop: 50.0
    Heads:
    - 100:**Default**:MTgzNjU2NWM3ODk3ZDQ5YTcxYmMxODk4NmQxZWE2NTYxMzIxYTBiYmY3MTFkNDFhNTZjZTNiYjjjjE3ZTdhIn19fQ===
    - 100:**Default**:YTU1YWQ2ZTVkYjU2OTJkODdmNTE1MTFmNGUwOWIzOWZmOWNjYjNkZTdiNDgxOWE3Mzc4ZmNlODU1M2I4In19fQ===
    - 100:**Default**:YWU1Mjg2N2FmZWYzOGJiMTRhMjZkMTQyNmM4YzBmMTE2YWQzNDc2MWFjZDkyZTdhYWUyYzgxOWEwZDU1Yjg1In19fQ===
    - 100:**Default**:MmFjNzRhMmI5YjkxNDUyZTU2ZmExZGRhNWRiODEwNzc4NTZlNDlmMjdjNmUyZGUxZTg0MWU1Yzk1YTZmYzVhYiJ9fX0=
    - 100:**Default**:YTAxNzIxNWM3ZjhkYjgyMDQwYWEyYzQ3Mjk4YjY2NTQxYzJlYjVmN2Y5MzA0MGE1ZDIzZDg4ZjA2ODdkNGIzNCJ9fX0= YTAxNzIxNWM3ZjhkYjgyMDQwYWEyYYYzQ3Mjk4YjY2
    - 100:**Default**:OTJhMjQ0OGY1OGE0OTEzMzI0MzRlODVjNDVkNzg2ZDg3NDM5N2U4MzBhM2E3ODk0ZTZkOTI2OTljNDJiMzAifX19

**Comment by Zrips** [comment]
Server version?

**Comment by Blueeyestar** [comment]
Spigot

CraftBukkit version git-Spigot-e6eb36f-d3ed151 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
That **default** is simply there as indicator where you can put custom head name. Default will default to default name. 
Tho general testing was done on 1.13.2 server which was working as it should. Will do some extra testing, maybe i skipped something.

**Comment by Blueeyestar** [comment]
I have created a server with CMI version : CMI8.5.2.0 
Otherwise I didn't put a plugin on it. So everything will be generated from scratch. When I now make /cmi mobhead the picture comes:

http://pic.lululand.de/upload/Webseite/2019_03_22_16.54.21.png

**Comment by thenullmatrix** [comment]
Yeah it just shows the Steve or Alex default skins  running current CMI 8.5.2.0 and running CraftBukkit version git-Spigot-cf694d8-8d8475f (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by x1p** [comment]
Confirmed.
Every skull dropped defined by customHeads.yml returns a "wonderfull" steve/alex skull.

**Comment by Zrips** [comment]
Should be working correctly with latest builds.
