### ISSUE TITLE
Feature request: do not reset mob head chance of dropping with server restart

### ISSUE THREAD

**Issue by Swede37** [Zrips/CMI#1548]
**I haven't tried it out yet, but loving the concept of the new mob head drops.

We have our server set for timed restarts, and it would be AWESOME if the chance didn't reset with the restart. Would it be possible to set it so it would reset at a configurable time ( ie: every month) instead?**

---

**Comment by Zrips** [comment]
That would require data saves and quite abit of them. As we would need to save not only entity type, but how many times you got its head. So even after short time we could have huge raws with data in them. As inconvenient it is, not really planing in adding feature like this. Atleast not in near future.
