### ISSUE TITLE
[BUG] same confimation of money transaction works twice. 

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#1552]
**Description of issue or feature request:**
The problem is that if you sending money and other person accepts that money with clicking on that green the second click should be canceled however instead if you click it again it will send another amount to the user. 
(It mostly means if you accept that second time it will take money again, I think after the first time of accepting it should not work at 2 time, with the same confirmation.
![Screenshot_1](https://user-images.githubusercontent.com/1558228/54852184-00bab000-4ce4-11e9-8e56-731e070d4243.png)

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

```
---
NO ERROR
---

**Cmi Version (using`/cmi version`):** 
8.5.2.0
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot 
**Server Version (using `/ver`):** 
1.13.2
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Was fixed in latest builds
