### ISSUE TITLE
Login message not showing on new member join

### ISSUE THREAD

**Issue by DinoTK** [Zrips/CMI#1554]
**When a new player enter on the server, the login message is not showing...**

This issue only happens with new players. If he exits and re-enter, then the login message appears normally.

---

**Cmi Version:** 8.5.2.0
**Server Version:** Spigot 1.13.2 
**Relevant plugins:** AuthMe

**Comment by Zrips** [comment]
You should have enabled FirstJoinMessage in config file if you wanted custom message when player joins server for the first time.
