### ISSUE TITLE
Signs disappearing on click or hit

### ISSUE THREAD

**Issue by abhisantos** [Zrips/CMI#1559]
**Description of issue or feature request:**
Signs are disappearing on click or single hit!
If you place a sign, write anything or don`t write nothing, then punch it once in gm 0 or click it, it instantly disappears.

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
No Errors on console
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
CMI 8.5.1.4
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
spigot 1.13.2
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Cant be related to cmi as it doesnt manipulate blocks visualization in general.
