### ISSUE TITLE
Bug with update 7.5.1.0

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#156]
Vanish stops working after updating. Vanish works fine in 7.5.0.0

**Comment by Zrips** [comment]
There was no changes related to vanish in latest build. So that's strange. What exactly doesn't work for you?

**Comment by CypherPhyre** [comment]
I was in vanish at the time of update. Prior to the update /v and /ve worked. After updating /v and /ve would not do anything. I would still be in vanish and unable to exit vanish mode.Vanish would still have the same restrictions as set from the /ve GUI. I could still use chat and other commands. Just anything related to vanish and vanish interactions would not work. Reverting back to the previous version and restarting the server fixes the problem

**Comment by Zrips** [comment]
Try out new version, it should have fixed issue you had.

**Comment by CypherPhyre** [comment]
The problem still persists even when I don't have vanish active at the time of update. Vanish does not work. 7.5.0.0 has working vanish function

**Comment by Zrips** [comment]
Still issue with CMI7.5.1.1 version after normal server restart?

**Comment by MCTyler** [comment]
When did you set those Alias's /v and /ve in the Alias.yml file? /vanish and vanishedit work fine here.
```
  # /cmi vanish $1-
  /vanish: true
  #  
  # /cmi vanishedit $1-
  /vanishedit: true
  #  
```

**Comment by CypherPhyre** [comment]
Ok so it is my custom alias's that are broken then

**Comment by LogGits** [comment]
Was able to reproduce this on the latest version using aliaseditor to create an alias `/v that is an alias of `/vanish`.
