### ISSUE TITLE
Question - Nameplates

### ISSUE THREAD

**Issue by agentlinz** [Zrips/CMI#1560]
- Is there a way to restrict/limit the number of characters allowed for a nameplate prefix and suffix (similar to how nicknames have a minimum and a maximum number of letters allowed)?

- Also, does CMIs chat filtering work on nameplates, too?

If either of these are not currently possible, I'd like to request this feature.  Many thanks :)

**Comment by Zrips** [comment]
Currently, no way to limit character length.  And no, chat filter doesn't work on name plates.
