### ISSUE TITLE
Feature Request: Disable Mob Spawns while afk

### ISSUE THREAD

**Issue by GrimPod** [Zrips/CMI#1561]
Would be cool if while a player was afk, they didnt spawn mobs around them, and chewing up the mob cap
I thought i had found a workaround for this by cuffing them, putting them into spectator mode and putting a bossbar to tell them to shift to exit  afk, as when u press shiift when cuffect, it still detects and unafks the player,
but when in spectator mode and cuffed, you still go down when pressing shift
this could be a way to implementing it, but would need to make sure they dont go thru a block or anything when in spectator mode

**Comment by mrfloris** [comment]
It would be quite fantastic to fight those players who join and minimize their game, and come back to earning 250k from their pig mob farms while being afk.

**Comment by Zrips** [comment]
Is it possible? Depends. With vanilla API, no. There is no way to know why entity spawned, for which player in particular. Some crude work arounds like you did is possible, but at same time changing players game mode sooner or later will result in some bugs, like in example if server would crash while player is in afk mode, he would stay in one even after its restarted. So some better approach would be needed.

**Comment by Zrips** [comment]
What i can add is /cmi tppos relative position teleport so /cmi tppos ~0 ~1 ~0 [playerName] would teleport player 1 block up

**Comment by GrimPod** [comment]
True, Good point, didn't think about if it crashed or went down
Could maybe make atm stored in a file then if server crashes, and reboot it could check if players were atk when they join and if so they would be in spectator so therefore put them back in survival
Relative tppos would be cool thou ( if that's not already a thing)

**Comment by GrimPod** [comment]
Actually the world limits would be able to prevent this

Thou they are still slightly bugged,
As when joining with fly it checks gamemode bypass instead of fly bypass
So if someone has access to fly, this would be a bad idea atm
