### ISSUE TITLE
Typo with CustomRecipes

### ISSUE THREAD

**Issue by AndieB220** [Zrips/CMI#1562]
**CustomRecipe Typo**
**ERROR**
```
In the CustomRecipe GUI the delete recipe button is spelled "Delate" not "Delete" nothing crazy but something to mention

**Comment by mrfloris** [comment]
It's been there since the start, I think I've mentioned this a few times on the forums, but hasn't been addressed yet. 

Voting up for fix! :D

**Comment by Zrips** [comment]
It is fixed.
