### ISSUE TITLE
[Suggestion] Permanent actionbar message on vanish

### ISSUE THREAD

**Issue by DinoTK** [Zrips/CMI#1565]
It's very important for a staff member to know if he is in vanish mode or not. And to know this, he needs to type every time the vanish command to test and then know if he can continue to, for example, examine hackers.

In order to facilitate this process, I thought that **implementing the vanish status in a permanent actionbar** would be extremely useful to staff members.

Currently, there is already an option to do this actionbar message on vanish in CMI in the language config, but this message desappears in seconds, being useless for us...

I hope you consider this suggestion **<3**

---

**Cmi Version:** 8.5.3.0 
**Server Version:** Spigot 1.13.2

**Comment by CypherPhyre** [comment]
This is already possible using the bossbar. It can be turned on from the /vanishedit gui
