### ISSUE TITLE
[Suggestion] CMI CLEAR additions.

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1568]
Hey there,

Could we get a few more additions to CMI CLEAR? This would be quite fantastic. 

First one: Can we get a timeout on the CLICK confirmation command, so when we 5 minutes later are in the `t` to chat and accidentally click the link, it will say:  this has expired, type /clear again.. - preventing accidental clicks later after say 12 seconds?

A few permissions such as 

```
cmi.clear
cmi.clear.others
cmi.clear.hotbar
cmi.clear.inventory
cmi.clear.armor
cmi.clear.offhand
cmi.clear.ender
```

This way we can negate or enable certain ones.

Like example, default group: (access to clear command, which will clear their inventory, and hotbar, but not their armor and offhand. 
cmi.clear
-cmi.clear.others
cmi.clear.hotbar
cmi.clear.inventory
-cmi.clear.armor
-cmi.clear.offhand
-cmi.clear.ender

Another example, creative group: (clears inventory, including hotbar and offhand, but can't clear their enderchest)
cmi.clear
-cmi.clear.others
cmi.clear.hotbar
cmi.clear.inventory
cmi.clear.armor
cmi.clear.offhand
-cmi.clear.ender

and staff members: (empties out a player completely, top to bottom)
cmi.clear
cmi.clear.others
cmi.clear.hotbar
cmi.clear.inventory
cmi.clear.armor
cmi.clear.offhand
cmi.clear.ender

**Comment by adamlaughlin** [comment]
I've also come today to request an "undo" argument.
I feel like I may eventually just hit enter before adding in the new arguments supported in CMI's 1.14 builds.

Would you mind saving the target's cleared inventory in a hidden slot? Making this feature toggleable could also save some server resources for those with other solutions / who don't care.

**Comment by mrfloris** [comment]
Happy with how cmi has clear currently, i am closing this ticket.
