### ISSUE TITLE
[Support] Duplicate alias: SPAWN

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1569]
Hi there, I hope to get some support on this. I am quite confused, and it's an old issue from the 1.12 days that is still in 1.13, and I can't figure it out still.

Upon startup of the server, I get duplicate alias for /spawn (and a few others), in config.yml of cmi I have spawn first join set to true, and that sorta stuff.

In alias, I have
```
  #  
  # /cmi spawn $1-
  /spawn: false
```
and in custom alias, there is only one entry for /spawn command, which is
```
  spawn:
    Cmds:
    - mv tp spawn
```

Even if i switch it around and remove the custom alias and set the alias.yml value to true for /spawn, and restart the server, it still says it.

I've checked with and without essentials jar there, but doesn't seem to be the issue.

Any location I forgot to check that it says this?

**Comment by mrfloris** [comment]
I actually have the same for donate.

alias yml /cmi donate: FALSE

custom alias yml /donate .. my command.

We use /donate for "you can donate through paypal'" and not what cmi wants to use it for.

but during startup we get 'duplicate alias', it's not duplicate, it's set to false!..

**Comment by Zrips** [comment]
Well we no longer showing those messages, was causing to much confusion what it does and why its there.
