### ISSUE TITLE
BUG: Flightcharge Used when /flyc set to false and /fly set to true

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#157]
When users travel from Survival world to Creative world, they start using flightcharge time in creative fly. It isn't until this is all used up, that they can do /fly and have it work properly.

This happens even if /flyc is disabled in survival before going to creative world, or if /flyc false is issued in creative world, then /fly true is enabled, and when flying, it still burns flight charge.

This happens whether or not flightcharge fly is enabled by default or not.

**Comment by Zrips** [comment]
Will do some changes with next update, test it out and if there will be issues still, report them.
