### ISSUE TITLE
[Support] 64 kits loaded msg, twice, during startup?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1570]
CMI loads on startup, at some point it mentions that 64 kits are loaded and it took x seconds
then other CMI stuff happens, and few seconds later it says again that 64 are loaded, and took y seconds.

```
[16:00:38 INFO]: [CMI] Loaded (64) kits into memory. Took 46ms
[16:00:38 INFO]: [CMI] Loaded (64) kits into memory. Took 23ms
```

Is this correct, or should it only say it once? Did I forget something in config.yml maybe?

**Comment by Zrips** [comment]
Will be fixed
