### ISSUE TITLE
itemname and itemlore can't find the specified player

### ISSUE THREAD

**Issue by ArtNRG** [Zrips/CMI#1573]
**Description of issue or feature request:**
I want to use these commands from the console:
/cmi itemlore [playerName] [linenumber] [new lore line]
/cmi itemname [playerName] [new name]

I receive the message that the player not found. The player is online, the nickname is correct.

---
**Cmi Version (using`/cmi version`):** 
8.5.4.0

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper(571) 1.13.2

**Comment by mrfloris** [comment]
Can confirm,

joined an alt to the game that's a regular player, made sure they were holding a regular crafted item without anything special on it in their main hand and typed in console:

```
[14:03:51 INFO]:  1MB Server » Welcome back townx ❤
>cmi itemlore townx 3 &6 test &r
[14:04:32 INFO]: Can't find player with this name!
```

Which resulted in player not found showing twice.

https://i.imgur.com/dXVy980.png

**Comment by Zrips** [comment]
Format was changed to -p:[playerName] when indicating player, just to simplify player name detection
