### ISSUE TITLE
[BUG] Flight Charge Safe Login

### ISSUE THREAD

**Issue by Cooperating** [Zrips/CMI#1576]
When players are falling and they log out and log back in quickly flight charge is automatically enabled, even in areas where flight is disabled and /flyc is not allowed.  It seems very similar to this permission: cmi.command.fly.safelogin - Safely lands player after relog if he is in air.  There is no option to disable this safe login feature for flight charge that I can see.  Players were given flight charge permissions and I added the permission -cmi.command.fly.safelogin, but it seems it does not apply to flight charge flight.

**Cmi Version (using`/cmi version`): 8.5.4.0** 

**Server Type (Spigot/Paperspigot/etc): PaperSpigot** 

**Server Version (using `/ver`): git-Paper-597 (MC: 1.13.2)**

**Comment by Zrips** [comment]
With next version will make it to require that permission node for flight mode to be enabled after relog.
