### ISSUE TITLE
[Suggestion] Remove invalid enchantments from an item

### ISSUE THREAD

**Issue by FreeMonoid** [Zrips/CMI#1577]
There seems to a machinery in place to distinguish between valid and invalid enchantments already with `/cmi enchant -onlyvalid`, maybe it can be extended?

For example, if I hold a sword with:

- Sweeping Edge
- Looting
- Lure
- Thorns

and run a command, maybe `/cmi enchant -keeponlyvalid`, I should end up holding a sword with:

- Sweeping Edge
- Looting

Thanks!

**Comment by mrfloris** [comment]
Technically you can hold the item and type: `/cmi enchant Looting 0` and `/cmi enchant Lure 0` to remove them. But yes, I understand what you mean.

**Comment by Zrips** [comment]
Next update.
