### ISSUE TITLE
[Bug] Loss of JSON color codes in 1.13.2

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#1578]
In version 1.13.2, JSON color codes are lost if for example a colored item is enchanted. With the same CMI version and setup but with version 1.12.2 this is not the case. The problem is clearly related to CMI, because the problem no longer exists when CMI is deactivated. This is of course a very annoying problem, because there are always complaints about it.

The problem can be reproduced as follows:
1) "/give @p minecraft:apple{display:{Name:"{\"text\":\"Apfel\",\"color\":\"dark_red\"}"}} 1"
Github deletes the "/". Here is a link to the correct command: https://pastebin.com/K6HqPcud
2) Enchant the apple in an anvil in gm1 with any book.
3) The removed apple will have lost its JSON color code.

CMI version 8.5.4.0
Paper-597 1.13.2

**Comment by TheoRetisch1** [comment]
I want to bump this issue because the loss of json formatting is a real problem when assigning cool items.

**Comment by TheoRetisch1** [comment]
Confirmed for 8.6.3.2. Can I contribute anything else to fix this bug? Do you need any further information?

**Comment by Zrips** [comment]
Reproduced and should be fixed with next build

**Comment by TheoRetisch1** [comment]
Aweseome! Thank you so much :)
