### ISSUE TITLE
[BUG] Sorting breaks Spectator game mode

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#1579]
**Description of issue or feature request:**

With Sorting enabled my admins are solid and can't pass thru anything. With Sorting disabled they can pass thru as normal.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

---

**Cmi Version (using`/cmi version`):** 8.5.4.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** CraftBukkit version git-Spigot-e6eb36f-51100db (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Yea, this feature will have to be disabled for time being. Seems to have some complications... More work is needed to be done before we can have this feature.
