### ISSUE TITLE
[Request] Better hidden support.

### ISSUE THREAD

**Issue by DutchUser** [Zrips/CMI#1580]
**Description of issue or feature request:**

Add proper support for vanished players, while they are hidden in TAB, they are not in /list and /afkcheck

I contacted the dev about this with Discord, and Spigot. Both ways i get ignored, so then here.

You can easly add support for it with this:

> Checking if a player is vanished on Bukkit (no dependencies required)
> ```
> private boolean isVanished(Player player) {
>         for (MetadataValue meta : player.getMetadata("vanished")) {
>             if (meta.asBoolean()) return true;
>         }
>         return false;
> }
> ```
> This code is supported by PremiumVanish, SuperVanish, VanishNoPacket and a few more vanish plugins.

Disclaimer:
- Please do not respond here and say "use cmi vanish", we do not use it for reasons. 
- To expand what i said above, CMI is a **premium** plugin. It should not force users to use its own things what have less things then a other plugin have. You change a plugin to upgrade it, not downgrade it.

**Comment by DutchUser** [comment]
https://github.com/Zrips/CMI/issues/1596

**Comment by Zrips** [comment]
Will make some changes to address this issue and to unify vanished player detection with metadata for convenience sake.
