### ISSUE TITLE
[Request] Nameplates

### ISSUE THREAD

**Issue by WhxteRabbit** [Zrips/CMI#1585]
Hello!

No issues here, just a little suggestion. (:

I thought it would be a neat idea to allow for prefixes and/or suffixes to go above or below the user's name on their nameplates. I don't believe this is already an option ( if it is I haven't realized or found out how to do it, unfortunately and if so, please send me in the right direction on the wiki, etc. ).

I just thought it was a nice little thing.
I, personally, enjoy having the prefixes above the player names. Simply because if the rank/prefix is long and so is the player's name? It just looks obnoxious when they're walking around with this huge long string of words/letters in a line above their head.

( Ignore the fact that everyone is stacked on one another. Lol. Just look at the nameplates. )

Example: https://image.prntscr.com/image/5daKy7zES5KVi8KtysvZ2Q.png

**Comment by Zrips** [comment]
/cmi nameplate (playerName) (-pref:[prefix]) (-suf:[suffix]) (-c:[colorCode])

**Comment by WhxteRabbit** [comment]
Hello!
I apologize if I didn't make myself quite clear on what I was attempting to suggest as a feature for the nameplates. I do understand how to add the prefix, suffix, namecolor, etc. above the heads. However, I would like to suggest a feature for nameplates where the _prefix_ can be **above** the player's name, rather than in front of it.

Hopefully this makes it more clear on what I am attempting to suggest.
And again, if this feature is possible, then please let me know how to properly display it as such.
Because I'm afraid I must have overlooked it on the wiki.

Thank you for your time.

Example: 
![Suggestion](https://user-images.githubusercontent.com/43273046/55603948-f7453500-5732-11e9-8cd2-ca84d6120e71.png)
