### ISSUE TITLE
Sign shift edit protection plugins support

### ISSUE THREAD

**Issue by Harveyplays02** [Zrips/CMI#1586]
**Description of issue or feature request:**

Adding this would allow support for WorldGuard, LWC, Griefprevention, and any other protection plugins you know to be able to stop a player from editing someone else's signs unless they have permission to.

---

**Comment by LogGits** [comment]
Also noted, CMI has issues with shift editing signs in worldguard regions and griefprevention claims even if the user is opped.

**Comment by Zrips** [comment]
Players who have access to place blocks in that area can edit signs with shift click. So protection plugins which adds limit like that should prevent editing signs.
