### ISSUE TITLE
[BUG] Bug Due to Tab List Grouping

### ISSUE THREAD

**Issue by FestusDM** [Zrips/CMI#1589]
Understand that tab list grouping is an experimental feature. Below are some bugs/issues that were found when tab list grouping was turned on. There were no errors.

- Players' skins changed to default skin.
- Players' icon inside tab list changed to default skin icon
- Names on top of players turned into 2 letters
-Staff are not able to change game mode and go through things 

All these issues were gone when tab list grouping was disabled.

**Cmi Version (using`/cmi version`): 8.5.4.1** 
**Server Type (Spigot/Paperspigot/etc): Paperspigot** 
**Server Version (using `/ver`):** git-Paper-597

**Comment by Zrips** [comment]
Strangely i cant reproduce this issue. I do know that there is one as i got couple reports about this. But on test server it simply worked as it should. Try testing newest version. There was some changes made for it on 1.13 servers, so it might solve some issues or all of them or none of them. Cant really say exactly until i figure out what is different between my setup and people who has this issue
