### ISSUE TITLE
Request for asOp! added to Specialized Commands

### ISSUE THREAD

**Issue by CaliDreams** [Zrips/CMI#1593]
**Description of issue or feature request:**

Request for asOp! to be added to the specialized commands

-Difference between that and running a command as console:
If you run it as console you can only run it on a player; you cannot force them to do a command that they don't have permission to currently

---

**Comment by Zrips** [comment]
This is not an option. Changing players OP status is as worst thing to do as you can. There is bperm variable which can bypass majority of CMI commands. But changing players OP status can result in terrible things if server would crash during command processing. Then you would have OP player running around. you can always add required permission to the player before performing that command and take it away after he did it. But at this point i will not risk by giving OP status to the players.
