### ISSUE TITLE
Hook CMI into PremiumVanish for hiding vanished player from CMI commands

### ISSUE THREAD

**Issue by TheBlueKingLP** [Zrips/CMI#1596]
**Description of issue or feature request:**
Hook "/cmi list" into PremiumVanish plugin so the command will not list players who is vanished.

**Comment by zykrahgaming** [comment]
upvote, this would be nice

**Comment by Zrips** [comment]
Will make small change which should solve this issue with PV plugin. If issue persists, reopen ticket or make new one. Then i will have to make bigger changes to make it work.
