### ISSUE TITLE
Incorrect Home GUI Blocks

### ISSUE THREAD

**Issue by delbertina** [Zrips/CMI#1597]
**Description of issue or feature request:**

---
Setting a home on some blocks shows an incorrect block in the GUI. Examples include un-dyed shulker showing up as purple shulker, wall torch, wall sign etc.

**Steps to Reproduce:**
1. /sethome on un-dyed shulker box
2. /homes and see purple shulker as gui block

---
**Cmi Version (using`/cmi version`):** 
8.5.4.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper dev 577 
(Not latest, but not that relevant imo)
**Server Version (using `/ver`):** 
1.13.2

**Comment by Zrips** [comment]
Will be fixed with next build.
