### ISSUE TITLE
[Bug] Shulkerbox with cmi.openshulker.shift illegal behavior

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1599]
**Description of issue or feature request:**

---
Opening a shulker box with shift right click makes it possible to place an empty shulker box within a shulker box. This is NOT vanilla behavior. A shulker box containing stuff can't be placed inside another shulker box luckily. But this should not be possible at all.

Permissions:
```
cmi.openshulker
cmi.openshulker.shift
```

---

**Cmi Version (using`/cmi version`):** 
8.5.4.1
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
1.13.2

**Comment by Zrips** [comment]
Well good point. Will make a change to prevent any shulker box being placed inside another shulker box even if its empty one. It wasnt really big issue, as only item stacks which doesn't qualify as a shulker box can be placed, but this can add some confusion. So lets prevent all of them and be done with that.
