### ISSUE TITLE
money lose

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#160]
My players had notice that they lose money for example one player use /money pay (player) (amount) and next day there was no money that was given by other player. Every night server is restarting by the way. But when restarting it should save players data and money. So why players losing money. This wasn't an issue before like 7 updates before xD or something like that 

Using paperspigot 1.12.2
Newest CMI

**Comment by Baktus79** [comment]
I have seen this once before myself. A player payed 100k to another player. The other player received the money, but when the server restarted hours later they where gone.

**Comment by LogGits** [comment]
Is this issue still present?

**Comment by arturek1666** [comment]
For me yes it's fixed.
