### ISSUE TITLE
Ignore doesn't work anymore

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#1600]
**Description of issue or feature request:**
/ignore command doesn't work. It does show a respond message, but that player's chat still shows
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####
---

**Cmi Version (using`/cmi version`):** 8.5.4.1

**Server Type (Spigot/Paperspigot/etc):** Paper 572

**Server Version (using `/ver`):** 1.13.2

**Comment by Zrips** [comment]
Are we talking about public chat or private one?

**Comment by blek-id** [comment]
I think it doesn't work on both. I tried both ways

**Comment by Zrips** [comment]
Are you using another plugin for private messages and/or public messages?

**Comment by blek-id** [comment]
Hi i updated CMI and it works now, :) sorry for the hassle
