### ISSUE TITLE
[Bug]Executing list command with Rcon is invalid

### ISSUE THREAD

**Issue by Eifime** [Zrips/CMI#1605]
Using Rcon to execute “cmi list” cannot receive data returned by the server,But the command has been successfully executed.The same problem arises when the “cmi gc” command is executed,There is no doubt that any order can be executed.Only CMI can't handle returns,This is achievable in Essentials.

Cmi Version (using`/cmi version`):8.3.2.0
Server Type (Spigot/Paperspigot/etc):Paperspigot
Server Version (using `/ver`):1.13.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Should be returning feedback messages correctly now
