### ISSUE TITLE
[bug] baltop bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#1608]
1. baltop bug
Whenever I use /baltop
There will be one more same name player on the leaderboard
Will increase indefinitely
This is very troublesome for me, has increased to more than 4,000
![image](https://user-images.githubusercontent.com/5382252/55929493-8381bb80-5c4f-11e9-9af9-e972ddf51bda.png)

2.
When I update the cmi plugin, all the home points of the record will disappear

These two questions seem to be a problem with CMI's preservation.
I have not encountered this problem before.

I am a genuine verification server

---

**Cmi Version (using`/cmi version`):** 8.5.6.0

**Server Type (Spigot/Paperspigot/etc):** spigot

**Server Version (using `/ver`):** 1.13.2

**Comment by x1p** [comment]
Did you eliminate the possibility that this might be a duplicate user?
(`removeuser duplicates`)

**Comment by p82183645** [comment]
This is obviously a bug.
The same user has appeared 1000 times faster

**Comment by p82183645** [comment]
any fix ?

**Comment by Zrips** [comment]
Should be working correctly now
