### ISSUE TITLE
cmi attachcommand !cooldown:15 in chat not working.

### ISSUE THREAD

**Issue by TasmanianNoob** [Zrips/CMI#1613]
Using the command /cmi attachcommand !cooldown:15 works but the chat message does not get sent, instead it sents this
![image](https://user-images.githubusercontent.com/37134698/56078169-40c70b80-5e28-11e9-9f94-414504ef2c4d.png) - I do not believe that this is an issue with only me as I saw someone posting about this a while ago but I might be wrong and if that is so could you please tell me what I have to do to fix this issue.

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/37134698/56078166-3b69c100-5e28-11e9-976c-c5291fc7c175.png)

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/37134698/56078162-2ee56880-5e28-11e9-91b3-dbb8ee523c86.png)

**Comment by Zrips** [comment]
it was small misspell in a code, should be outputting correctly now.
