### ISSUE TITLE
Migrating from mysql to sqlite

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1614]
**Description of issue or feature request:**

Is there a way to migrate the mysql database to the default locally saved sqlite?

There is no information about the migratedatabase command on the website.
There are no arguments described in the locale file.
When executed, leads to a crash. It seems that this only migrates from sqlite to mysql and not the other way around.

**Comment by LogGits** [comment]
Please provide the crashlog

**Comment by x1p** [comment]
FYI: CMI is correctly installed and connected to a mysql database
The command `cmi migratedatabase` was executed without any arguments. (I wonder if they exist)

https://pastebin.com/PfuZtRjt

**Comment by x1p** [comment]
Oh wait minute. It just works. I made a mistake myself. My bad.
