### ISSUE TITLE
/back After Died in Void or Lava, it Teleports me Back into the Void/Lava

### ISSUE THREAD

**Issue by TheBlueKingLP** [Zrips/CMI#1616]
**Description of issue or feature request:**
The issue is when I type /back after I died in the void or in lava, it teleports me back into the void or lava
What I expected is it will teleports me back to a safe location, which it will search for by checking for space below me then above me then around me like the one in the plugin Essentials.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**Cmi Version (using`/cmi version`):** 
8.5.6.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
git-Spigot-642f6d2-6103339 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSNOT)

**Comment by Zrips** [comment]
You need cmi.safeteleport permission node to be able to avoid such things as lava or a void when teleporting.
