### ISSUE TITLE
REQUEST: Regex Chat Based Notifications

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#162]
This would be similar to your chat filter, but instead of filtering out the word, you could use words or phrases, and then issue an announcement instead.

Someone says, "How do I give permission to build?"

We could regex permission or permission and build, to issue out a helpful response automatically to people, as most people don't like to read through pages and pages of commands, and tutorials.

Player says, "Do you have a shop", well, if "shop" is matched, we could have a helpful announcement, that could either be issued to the player only or to the entire server. (global education is good).

I'd called it "Chat Based Notifications".

It would be nice if it showed up in the console log, so we could make sure that indeed the expressions are matching as desired, or if we need to fine-tune our regex to make sure it is only responding to applicable chats we want them to match.

Edit: Perhaps ability to limit the number how often it could be matched, for example, "shop" could be matched 1 time every 5 minutes, that way it doesn't go overboard and spam people who get to talk about a particular subject that it matches.

**Comment by Zrips** [comment]
But you can do this already with something like
`      ChatBasedNotifications:
        Enabled: true
        Group: information
        Regex:
        - (How do I give permission to build?)
        ReplaceWith: ''
        BlockType: others
        msgToStaff: ''
        Commands:
        - cmi msg [playerName] !&2To get permission get in contact with staff`

**Comment by digitalcrowd** [comment]
Thanks. Had no clue about that, but it does do what I need it to do. The only thing I see is that the message that gets sent out to the player, broadcast or cmi msg, or whatever, shows up before the actual message they type gets displayed. It would seem more fluid if it showed up after the message they typed.

**Comment by Zrips** [comment]
With next update it will show after message, tho it will be not today as i did posted new version couple minutes ago.

**Comment by digitalcrowd** [comment]
One last question:

How do I make the regex case-insensitive

I tried:

- '/how do i.*(buy|sell)/i'
- 'how do i.*(buy|sell)/i'

But it just breaks the regex that did work:

- 'how do i.*(buy|sell)'

**Comment by Zrips** [comment]
(?i)(buy|sell)

**Comment by digitalcrowd** [comment]
This works well. Thanks so much.
