### ISSUE TITLE
[Bug] Light_Gray tag in custom head drop not working

### ISSUE THREAD

**Issue by TheBlueKingLP** [Zrips/CMI#1622]
**Description of issue or feature request:**

the "Light_Gray" tag for sheep is not working in the custom head drop config, but if I type "Light_Grey", it will drop the head.

---

**Cmi Version (using`/cmi version`):** 
8.5.6.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Comment by Zrips** [comment]
Checked multiple places and we have Light_Gray as a color tag, so it should be working with that one and it cant really work with "Light_Grey" as i dint even included that one in possible sheep variations.
