### ISSUE TITLE
Portal question

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1625]
How do you do?
I got a big island in the air. I want to make it so that the users are teleported back to a point when they jump into the empty one. So I made a huge portal with cmi vertical. My thought was that the users would fall down through the portal and then be teleported to a point before they clap on the ground and die. If I now throw myself down as an owner, I will be teleported from the portal to the point. But if a user jumps down he falls through the portal and hits the ground. What rights must the user have to be teleported through the portal?

**Comment by Zrips** [comment]
My suspicion is that you have set portal commands which will be performed in a way like player himself did, this means that you as OP with access to that command will get teleported while players will not. Simply use button which allows you to set teleport location and avoid using commands for that action. This will solve your issue.
