### ISSUE TITLE
cmi saveditems bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#1626]
if item &f 
![image](https://user-images.githubusercontent.com/5382252/56140793-2a5ab480-5fce-11e9-99e9-99296988323b.png)

save become
![image](https://user-images.githubusercontent.com/5382252/56140808-2f1f6880-5fce-11e9-8706-7afdfc3d6935.png)

---

**Cmi Version (using`/cmi version`):** 8.5.6.0

**Server Type (Spigot/Paperspigot/etc):** spigot

**Server Version (using `/ver`):** 1.13.2

**Comment by Zrips** [comment]
This is issue with minecraft itself, how its handling deserialization and serialization of the items.
