### ISSUE TITLE
[BUG] Spawner Charges

### ISSUE THREAD

**Issue by Spikey101** [Zrips/CMI#163]
I have it setup to give the player 3 spawner charges with a cooldown of 8 hours per charge. The first 2 charges work fine, but the third charge will destroy the spawner instead of dropping it and will use up the last charge. If I then try mining another spawner now that I have 0 charges it shows that I have no charges available. So something is wrong with the 3rd spawner charge O.o

Spigot 1.8.8 - Latest CMI - I use CMI to give spawners, manage spawners breaking,placing etc 

Here is a video:
https://www.youtube.com/watch?v=jBXLueFBv28

Here is my config (spawner area)
https://hastebin.com/qenalawipi.vbs

**Comment by Zrips** [comment]
Should be fixed with next build
