### ISSUE TITLE
/cmi glow gui

### ISSUE THREAD

**Issue by Yukyxy** [Zrips/CMI#1630]
**Description of issue or feature request:**
Hello the colors in the /cmi glow gui doesn't work, the color is still in white.
could you repair this please? :)

**Cmi Version (using`/cmi version`):** 
last version
**Server Type (Spigot/Paperspigot/etc):** 
spigot 1.13.2

**Comment by AntoineHrn** [comment]
Same here

**Comment by LogGits** [comment]
I cannot reproduce this. What build of spigot are you using (output of /version)?

**Comment by AntoineHrn** [comment]
I was using paperspigot, unsure of the build though

**Comment by Zrips** [comment]
This is somewhat know issue and its originating with compatibility issues with other plugins which uses scoreboard teams. Will be working on this at some point to fix it.
