### ISSUE TITLE
[Bug] Auto purge is pretty broken.

### ISSUE THREAD

**Issue by Remski01** [Zrips/CMI#1632]
**Description of issue or feature request:**

The auto purge seem to be broken. I've set it to 500 days. But there are still players that are offline for it seem to be 49 years. 

But the server keep saying it deleted 200 users on startup while is there is no Difference at all. (even after 3 restarts)

#####################################
#####################################
https://pastebin.com/zxwhWFeE
**WARNING:** It have "false" because its now disabled as it was doing nothing at all.

**Cmi Version (using`/cmi version`):**  8.5.6.0

**Server Type (Spigot/Paperspigot/etc):** Paper.

**Server Version (using `/ver`):** Build 621. (1.13.2)

**Relevant plugins (Delete if this isn't needed):** 

Edit reason: Its clear that you not going look into this, it this is may a one time thing. 

So i changed the issue to that the auto purge is just broken af.

**Comment by DutchUser** [comment]
Its still a issue 

**CMI version:** v8.5.6.0
**Server version:** Paper 1.13.2 (b632) (latest)

```
16.06 18:30:56 [Server] INFO Checking... 263/100
16.06 18:30:57 [Server] INFO Checking... 263/200
16.06 18:30:57 [Server] INFO Finished cleaning
```

That's the only thing i can found.

**Comment by DutchUser** [comment]
So i updated to a newer version.

**CMI version:** v8.6.5.4
**Server version:** Paper 1.13.2 (b632) (latest)

**Config part:** https://pastebin.com/earyYLQJ

Related startup logs:
```
30.06 16:44:33 [Server] INFO [CMIEInjector] Loading CMIEInjector v1.0.2.1
30.06 16:44:33 [Server] INFO [CMI] Loading CMI v8.6.5.4
30.06 16:44:41 [Server] INFO [CMIEInjector] Enabling CMIEInjector v1.0.2.1*
30.06 16:44:41 [Server] INFO [CMIEInjector] Injecting CMI Economy
30.06 16:44:41 [Server] INFO [CMIEInjector] [Economy] CMI Economy found: Waiting
30.06 16:45:37 [Server] INFO [CMI] Enabling CMI v8.6.5.4
30.06 16:45:39 [Server] INFO [CMI] 27 Enabled and 20 Disabled modules
30.06 16:45:39 [Server] INFO [CMI] LuckPerms plugin will be used
30.06 16:45:40 [Server] INFO [CMI] Loaded (46) regular alias into memory. Took 26ms
30.06 16:45:40 [Server] INFO [CMI] Started (SqLite) data base. Took 151ms
30.06 16:45:40 [Server] INFO [CMI] Vault was found - Enabling capabilities. Economy: CMIEconomy
30.06 16:45:40 [Server] INFO [CMI] Can't determine sound name for tag. Trying to defaulting to BLOCK_NOTE_HARP
30.06 16:45:40 [Server] INFO [CMI] Loaded (5) warning categories into memory. Took 0ms
30.06 16:45:40 [Server] INFO [CMI] Loaded (3) warning commands into memory. Took 0ms
30.06 16:45:40 [Server] INFO [CMI] Loaded (109) custom mob heads
30.06 16:45:40 [Server] INFO [CMI] Loaded (0) cooldowns into memory. Took 27ms
30.06 16:45:40 [Server] INFO [CMI] Can't find world with (Nieuweworld) name
30.06 16:45:40 [Server] INFO [CMI] Loaded (2) kits into memory. Took 6ms
30.06 16:45:40 [Server] INFO [CMI] Loaded (1359) Player data into memory. Took 128ms
30.06 16:45:40 [Server] INFO [CMI] Loaded (0) playtime records into memory. Took 0ms
30.06 16:45:40 [Server] INFO [CMI] Loaded (2) playtime reward records into memory. Took 0ms
30.06 16:45:41 [Server] INFO [CMI] Found dynmap
30.06 16:45:41 [Server] INFO [CMI] Votifier found. Enabling vote listeners
30.06 16:45:41 [Server] INFO [CMI] Registered events. Took 442ms
30.06 16:45:41 [Server] INFO [CMI] Loaded (0) event action commands into memory. Took 5ms
30.06 16:45:41 [Server] INFO [CMI] Updated (EN) language file. Took 310ms
30.06 16:45:41 [Server] INFO [CMI] Can't load worth value for woodplate
30.06 16:45:41 [Server] INFO [CMI] Can't load worth value for woodbutton
30.06 16:45:41 [Server] INFO [CMI] Can't load worth value for monsteregg
30.06 16:45:41 [Server] INFO [CMI] Can't load worth value for skullitem
30.06 16:45:41 [Server] INFO [CMI] Can't load worth value for netherbrickitem
30.06 16:45:41 [Server] INFO [CMI] Loaded (243) worth values into memory. Took 63ms
30.06 16:45:41 [Server] INFO [CMI] Loaded (12) warps into memory. Took 2ms
30.06 16:45:41 [Server] INFO [CMI] Vault permissions was found - Enabling capabilities.
30.06 16:45:41 [Server] INFO [CMI] PlaceholderAPI hooked.
30.06 16:45:41 [Server] INFO [CMI] PlaceholderAPI was found - Enabling capabilities.
30.06 16:45:41 [Server] INFO [CMI] McMMO was found - Enabling capabilities.
30.06 16:45:41 [Server] INFO [CMI] Cleaning.
30.06 16:45:41 [Server] INFO [CMI] Starting world timer.
30.06 16:45:41 [Server] INFO [CMI] Initializing world manager.
30.06 16:45:41 [Server] INFO [CMI] Loaded (17) skin cache entries into memory. Took 2ms
30.06 16:45:41 [Server] INFO [CMI] Found DiscordSRV
30.06 16:45:41 [Server] INFO [CMI] Version 8.6.5.4 has been enabled
30.06 16:45:41 [Server] INFO [CMIEInjector][Economy] CMI Economy hooked.
30.06 16:45:44 [Server] INFO Checking... 267/100
30.06 16:45:45 [Server] INFO Checking... 267/200
30.06 16:45:45 [Server] INFO Finished cleaning
```

**Comment by Zrips** [comment]
When you see that 49+ year offline time, it means that we could not detect player last online time. Will make some adjustments to include them into list for removal.

**Comment by Zrips** [comment]
Will update its handling and make feedback message more clear with next update

**Comment by DutchUser** [comment]
Hello.

I have version 8.6.6.1 and it still doesnt remove users that are more 49 year offline. And also the issue with 
```
06.07 22:49:23 [Server] INFO RemcoMC issued server command: /seen 9f3af433-f81a-447f-9f9a-af4e038255c7
06.07 22:49:23 [Server] WARN Invalid statistic in ./world/stats/9f3af433-f81a-447f-9f9a-af4e038255c7.json: Don't know what EntityHorse is
```

The stats file have this https://pastebin.com/khmEVPSR

The reason i suspects this have todo with the pruge is because all of them are 49+ years offline. Something what the purge should remove. And also. The counter still goes over what it says after the /. 

```
06.07 22:41:58 [Server] INFO [CMI] Checking... 272/99
06.07 22:41:58 [Server] INFO [CMI] Checking... 272/199
06.07 22:41:59 [Server] INFO [CMI] Checking... 272/272
06.07 22:41:59 [Server] INFO [CMI] Finished cleaning
06.07 22:41:59 [Server] INFO [CMI] Player data files removed: 1 Keeping: 271
06.07 22:41:59 [Server] INFO [CMI] Player stat files removed: 1
```

Settings havent changed. Would like to see this Open again as the main issue is still not fixed.

**Comment by Zrips** [comment]
"WARN Invalid statistic"
Is simply a warning, caused by having player statistic files transferred from different minecraft server version. This is warning created by minecraft itself and can be ignored.

**Comment by Remski01** [comment]
Yes. but as far i can see accounts that have this error are also accounts that is offline for 49 years, something what should be removed by the purge stuff, but the purge simply seem to ignore them.

Thanks for reopening this.

**Comment by Zrips** [comment]
Could you give me data file of one of those players who has 49 years of offline time? Something doesn't add up for me here, so i wonder what information does that file contains in your case.

**Comment by Remski01** [comment]
Seem that this was confussed with the issue that players shows up in baltop and then cant be find with /seen after the first issue was fixed with an recent update. 

Not sure how this could happen... Does /seen and /baltop dont look at the same place?

**Comment by Remski01** [comment]
Closed because i dont expect an respons to it.
