### ISSUE TITLE
Console Error when using a reason with /jail command

### ISSUE THREAD

**Issue by Zoneman1972** [Zrips/CMI#1634]
When you type a reason with the /jail command, it spams console with the attached error:

**ERROR (DELETE IF YOU HAVE NO ERROR):**

http://prntscr.com/ne2cyc

**Cmi Version (8.5.4.1`):** 

**Server Type (Spigot):** 

**Server Version (CraftBukkit version git-Spigot-f09662d-0e1cea5 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT):**

**Comment by LogGits** [comment]
You are using invalid usage.
`/jail [player] 1 day testing`
correct usage:
`/jail [player] 1day testing

Regardless, still and error and therefore marked accordingly.

**Comment by Zrips** [comment]
The issue got fixed, but yea, format was incorrect and would result into jailing player for a 1 second.
