### ISSUE TITLE
CMI Prewards resetting every day selective players

### ISSUE THREAD

**Issue by Shadorunce** [Zrips/CMI#1635]
**Description of issue or feature request:**
We're having an issue on our servers where the /prewards seems to resets everyday for specific players for one of the two servers, so far I'm not aware of anyone that gets prewards from both servers, nor have an issue with both resetting. 

The servers are connected through Bungee, so I'm not sure if that will have anything to do with it or not. I'm not sure how it's normally setup, but at least for us our prewards playtime counting are separate between Survival and Skyblocks.

This is happening with at least 16 players confirmed (there's several players that haven't connected to the other server and wouldn't have any playtime racked up), I haven't gone through and checked all players that have gone on both servers, but from our experience so far it's been everyone. Other than everyone can only get rewards from one server or the other, there hasn't been any other pattern that we've noticed. It hasn't mattered which server they accessed first, it hasn't mattered which server they first accepted rewards (if even gotten a chance to).

I am reachable via Discord which then I should be able to connect you with Co-Owner to provide any additional information if needed.
Can use https://discord.gg/aRjYDRk if you do choose to connect, when you connect, let me know and I'll give you the role for the "playtime-reward-support" channel I have for this.

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
[Player1 playtime and prewards, has played today, but resets everyday.](https://cdn.discordapp.com/attachments/564015533461078017/568901730968928257/2019-04-19_16.50.33.png)
[Player2 playtime and prewards, has not played today, but has recently.](https://cdn.discordapp.com/attachments/564015533461078017/568901730968928257/2019-04-19_16.50.33.png)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Sorry, I don't have access to this. If it's required I'll ask for it.
I can tell you that all rewards need to be manually claimed, and do/can stack.
```

---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.2.2.0-> 8.5.6.1
Server version: Paper(455) 1.13.2-R0.1-SNAPSHOT
Vault version: 1.7.1-b91(CMIEInjector)

**Server Type (Spigot/Paperspigot/etc):** 
Spigot? (Sorry, I don't have that access

**Server Version (using `/ver`):** 
Sorry, I don't have access to this. If it's required I'll ask for it.

**Relevant plugins (Delete if this isn't needed):** 
React 6.58

**Comment by Zenya4** [comment]
Hi,

I'm the Owner of the said server above and the OP is one of our admins. I'll be providing some additional context here:

Config: https://hastebin.com/cudoqaqepi.rb
Server type: `PaperSpigot`
Jar version: `Paper version git-Paper-455 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

Additional info:
- Running server on offline mode
- Running server through a proxy network (Waterfall)
- CMI Database on MySQL
- Issue only occurs for some players; seems to be more prevalent during peak periods

If possible, I would also like to know where this playtime reward data is stored in the database on MySQL as I can't seem to find it.

Regards,
Zenya

**Comment by Zenya4** [comment]
I managed to found an error in console that may be related to this issue.

`[09:42:17 WARN]: [CMI] Plugin CMI v8.2.2.0 generated an exception while executing task 1233922
java.lang.NullPointerException: null
at com.Zrips.CMI.Modules.PlayTimeRewards.PlayTimeRewardsManager$1$1.run(PlayTimeRewardsManager.java:118) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[Paperclip.jar:git-Paper-455]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[Paperclip.jar:git-Paper-455]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[Paperclip.jar:git-Paper-455]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]`

**Comment by Zenya4** [comment]
Hi,

We have found a temporary solution to fix this problem. By adding any amount of playtime to a player using `/editplaytime`, the prewards counter will start counting again for the player and it persists after restarts. I still feel this issue should be looked into and hopefully resolved in future builds, though

**Comment by Shadorunce** [comment]
> Hi,
> 
> We have found a temporary solution to fix this problem. By adding any amount of playtime to a player using `/editplaytime`, the prewards counter will start counting again for the player and it persists after restarts. I still feel this issue should be looked into and hopefully resolved in future builds, though

Sorry for the correction, but specifically it's when we add enough time for them to claim a preward is when it'll stay even past restart.

**Comment by Zrips** [comment]
Should be up and running with latest builds.
