### ISSUE TITLE
Control New-items in 1.14

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1636]
Good afternoon, but the 1.14 isn't out yet. But I wanted to ask cautiously if you can control certain new things with cmi? 

I find it poisonous for a server if users can transfer enchanted items to a book via the reading desk. 

or that you can get the xp back when you turn an enchanted item back. 
These are all new things in MInecraft that are really too op for a server. 

i would be happy if you can control this via CMI if certain new features are allowed or not.

Have a nice Easter I wish you

**Comment by Zrips** [comment]
Well after 1.14 gets out and those features are confirmed to be working as they are being presented now. Make a ticket here with list of game mechanics which should be changed and to what exactly and we can make that one happen.
