### ISSUE TITLE
(SUGGESTION) Hologram Addon

### ISSUE THREAD

**Issue by johnsoncui02** [Zrips/CMI#1639]
So I'm currently noticing that %enchanted% only works for the hologram say pickaxe and armor, it doesn't work for regular items. Could you make that a possibility?

**Comment by LogGits** [comment]
IT actually should work for any item. e.g.
i have it used like this for my vote area:
```yaml
ICON:tripwire_hook%enchanted%
```

Could you provide an example of your usage? If this is resolved please close the issue 👍

**Comment by johnsoncui02** [comment]
I tried doing ICON:CHEST%enchanted%
and the item didn't glow. as soon as i added the next line the item would start to disappear and come back again if i refresh CMI

**Comment by johnsoncui02** [comment]
confirmed that it's not glowing with chest

**Comment by Zrips** [comment]
Well maybe because chest cant have this glow effect? A simple test by trying to enchant chest results into none gloving one, so this means you can have it enchanted. Which in general is correct outcome.
