### ISSUE TITLE
cmi ranks not working as intended. 

### ISSUE THREAD

**Issue by dmnchild** [Zrips/CMI#1644]
ranks issues:
commands not being executed.
also TalkedToVillager and FishCaught do not seem to register no matter what method i try
(Under stats requirements as - "FishCaught:150" or stand alone: FishCaught: 150)

---

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
Default:
  Enabled: true
  DisplayName: "&7Guest&r"
  DefaultRank: true
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Novice
  StatsRequirements:
  - "ItemCrafts:iron_leggings:1"
  - "ItemCrafts:iron_helmet:1"
  - "ItemCrafts:iron_chestplate:1"
  - "ItemCrafts:iron_boots:1"
  - "ItemCrafts:diamond_pickaxe:1"
  - "blocksmined:iron_ore:150"
  - "boattravel:150"
Novice:
  Enabled: true
  DisplayName: "&DNovice&r"
  DefaultRank: false
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Squire
  Commands:
  - "broadcast &6[playerName] &eleveled up to Novice rank!"
  - "lp user [playerName] parent settrack votes novice" 
  StatsRequirements:
  - "ItemCrafts:enchanting_table:1"
  - "ItemsUsed:wheat_seeds:1"
  - "ItemsUsed:potato:1"
  - "ItemsUsed:carrot:1"
  - "travel:5000"
  - "ItemsUsed:obsidian:10"
  - "ItemsUsed:flint_and_steel:1"
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
CMI 8.5.6.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper-571
**Server Version (using `/ver`):** 
1.13.2
**Relevant plugins (Delete if this isn't needed):** 
luckperms, rest should be irrelevant.

**Comment by Zrips** [comment]
Both of those are been working with this setup on a 1.14.4 server without any issues. If this is still an issue for you, please let me know.
