### ISSUE TITLE
StopPlayTime = true resets the entire playtime

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#1645]
Setting the option "StopPlayTime" from false to true resets the entire previously collected playtime. As soon as a player leaves and returns, the playtime counter will be reset once without warning. From then on there will be no further resets, it will simply be counted from null on joyfully upwards. This is of course a catastrophe if you want to change the option while the system is running and continue to use existing playtimes. 

To eliminate the chaos, the possibility to edit the playing time for offline players would be fantastic ( see also #1477 ). I'd still like to pay a bonus for the feature, because correction, communication and appeasement are very high towards the community. 

CMI: 8.6.0.0
Paper: 1.13.2 #622
playtime config: https://pastebin.com/MwjTNL86

**Comment by Zrips** [comment]
Will make some changes to address this issue with next update.
