### ISSUE TITLE
Time freezing by itself

### ISSUE THREAD

**Issue by abhisantos** [Zrips/CMI#1648]
**Description of issue or feature request:**

Time is freezing by itself and if you try to unfreeze it or type any time command, the sun keeps rolling like crazy eternally making day and night all the time in less than one second.

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
No error in console.
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
CMI8.6.0.1
MI**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.8.8
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
What is your setup for time itself? As i can understand its not frozen. Are you using time speed up feature? Do you have smooth transition on?
