### ISSUE TITLE
GroundClean deletes primed tnt

### ISSUE THREAD

**Issue by Drc-DEV** [Zrips/CMI#1651]
CMI 8.5.6.1
Paper 1.13.2-R.01

/grounclean  deletes primed tnt from the server

> GroundClean:
>   WhiteList:
>   - DIAMOND_SWORD
>   - DIAMOND_HELMET
>   - DIAMOND_LEGGINGS
>   - DIAMOND_BOOTS
>   - TNT

**Comment by Zrips** [comment]
whitelist is only for items, while primed tnt is entity. Will exclude primed tnt by default with next update with option to include them with +tnt variable.
