### ISSUE TITLE
CMI AFK Event Causing Error on Console

### ISSUE THREAD

**Issue by Relaxing9** [Zrips/CMI#1654]
**Description of issue or feature request:**
When running the latest CMI Experimental build on a 1.14 Server, chatting in general is not triggering the removal of the AFK status, and will only get removed upon command evocation. There are no errors in game, but it causes the console to spam as seen in the pastebin below.

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**

[https://pastebin.com/uixcapuS](https://pastebin.com/uixcapuS)

---

**Cmi Version (using`/cmi version`):** 8.6.0.1

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-e4be9b0-5736cdc
(MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)
(Will be updating to the latest Spigot build soon)

**Comment by Zrips** [comment]
Should be fixed with next build
