### ISSUE TITLE
CombatLogX Compatibility and duplication bug

### ISSUE THREAD

**Issue by Zenya4** [Zrips/CMI#1655]
Description of issue:
CMI's feature to change spawners using [shift + right-click] allows duplication of items (spawn eggs) inside the GUI when used with the plugin CombatLogX [https://www.spigotmc.org/resources/combatlogx.31689/] when the user is in combat

---

ERROR:
`No details in console`

---

Cmi Version: 8.2.2.0

Server Type: PaperSpigot

Server Version: Paper version git-Paper-455 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Relevant plugins: CombatLogX [https://www.spigotmc.org/resources/combatlogx.31689/]

**Comment by Zrips** [comment]
Its issue with CombatLogX not processing correctly inventory open event 2 times in a row. Contact with that plugin developer so he could fix it. I cant really do anything from my end at this point.
