### ISSUE TITLE
You can't login from this ip address

### ISSUE THREAD

**Issue by MrWay** [Zrips/CMI#1659]
**Description of issue or feature request:**
Only i am unable to join one of my servers because of CMI. I am not banned and i can join using other account from my ip.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
You can't login from this ip address
```
---

**Cmi Version (using`/cmi version`):** 8.3.9.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):**  1.12

**Comment by mrfloris** [comment]
```
>cmi lockip
[15:54:51 INFO]: Usage: /lockip [playername] [add/remove/list/clear] [ip]
[15:54:51 INFO]: * Prevents logging into account from different ip
>
```

From console, type: cmi lockip YOURNAME list, to see if you have used lockip (and i guess it changed since) and then use clear or remove, to remove it.

**Comment by MrWay** [comment]
Cool! It works! Thanks.

**Comment by Larskrs** [comment]
Sorry for responding to an old issue, but this really helped me. I was wondering if it was possible to disable iplocks

**Comment by mrfloris** [comment]
You can simply not use the command. 
You negate the permission for the groups who should not be able to use it.

**Comment by LucasHervieu** [comment]
hello, i have this problem and lockip doesn't solve anything. it always tells me that my ip is blocked.

**Comment by mrfloris** [comment]
cmi lockip is the only way, or you are IP banned. if it's neither, then it's not a cmi issue
