### ISSUE TITLE
CMI not properly stripping colour

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#166]
when using the "+" to add to anything, cmi will not strip the colour of the players chat. Example, I have &6 chat, I type "SICON:%cmi_iteminhand_type%:%cmi_iteminhand_itemdata%" and it doesnt work. I check the file and its &6 in front. even when I click the "Click to paste old text. Type cancel to cancel action. Type remove to remove line". it shows the message with &6.

**Comment by Zrips** [comment]
Next version, fixed.
