### ISSUE TITLE
Damage not considered as move

### ISSUE THREAD

**Issue by FaMa91** [Zrips/CMI#1660]
When a player use any kind of tp (home, warp) when he moves the request is cancelled, but if it takes damage the tp works. We think that a player who take damage should be considered as if he is moving.

---

**Cmi Version (using/cmi version): 8.5.6.1

**Server Type (Spigot/Paperspigot/etc): Spigot 1.12.2

**Server Version (using /ver): CraftBukkit version git-Spigot-642f6d2-6103339 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
With next update we will take in player damage and use it in same way as his movement
