### ISSUE TITLE
(Question) Per item worth placeholder

### ISSUE THREAD

**Issue by johnsoncui02** [Zrips/CMI#1661]
So the current placeholder to display an item worth on hologram it's showing the total value of the entire stack for the item held.

I was wondering if it's possible to have a placehoolder laying somewhere around where it displays the worth per item rather than showing the entire worth of it. Meaning only showing the worth in 1 quantity even if the player is holding 64 of them in the hand.
![image](https://user-images.githubusercontent.com/23487437/56872957-6b49c480-69e3-11e9-8ac0-60a3f254f894.png)

**Comment by LogGits** [comment]
Havent tested it so let me know if it works but this is what I'm thinking:
`/cmi placeholders parse %cmi_equation_{cmi_worth_buy_stone}*3%`

**Comment by johnsoncui02** [comment]
not sure what that's able to accomplish, but it didn't seem to change the price of the stone.

**Comment by Zrips** [comment]
Next update will have %cmi_iteminhand_worth_one% to show worth of one item

**Comment by LogGits** [comment]
it should work:
https://gyazo.com/8283e2f9508599c75a9cbae294b96af2
