### ISSUE TITLE
/cuff bug

### ISSUE THREAD

**Issue by w1nst0nDEV** [Zrips/CMI#1665]
**Hello!** I'm here to report a small bug! On 1.8.8 Spigot, when you /cuff someone, and they click w or move their head, they start glitching out really bad. The plugin teleports them to where to player wanted to go when he click w/moved his head, then back to their original position. There are no errors in the console, and I am using the latest CMI version.

Players on my server get irritated when I cuff them because their screen glitches out. Is there any possibility you could fix this? **Thanks! :D**

**Comment by JustGamerr** [comment]
Yeah, I've noticed this issue with the command and it causes serious problems with teleportation glitches and then resulting in being kicked for flying, etc, as the plugin cancels the movement in a way that 1.8.8 doesn't like very much lol

**Comment by Zrips** [comment]
Will make some change to avoid canceling move event if they move down, so this will allow them to fall down properly.
