### ISSUE TITLE
A `cancel` option for cmi cmds:  lfix findbiome scan fixchunk etc

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1667]
There are quite a few resource intensive commands that also can take forever, it would be nice that when people use it incorrectly that we can cancel the event.

Maybe some of them actually have cancel, i wish i had the time right now to double check.

But things like panimation, scan, lfix, findbiome, and fixchunk, it would be nice if we can type:

/cmi fixchunk cancel, and any running fixchunk task gets cancelled. 

[edit] included panimation

**Comment by DonSensiLeone** [comment]
That is a very good idea especially for junior staff , not really used to admin cmds :)

**Comment by Zrips** [comment]
Will add this one with next update.
