### ISSUE TITLE
Hologram issues

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#167]
There is no way currently, to remove holograms ingame.

/cmi reload doesn't reload the holograms. 

Colours issues with Holograms &e turns to white (e.g.) And Stripping of colour wen inputing info is also not working #166 

ICON and SICON dont seem to work but i am assuming this is also related to #166 an example of this is: https://gyazo.com/823f8466f70f1d71bf2a419dc18461c6 

**EDIT: Can confirm that it is caused by not stripping colours correctly. As i removed the &c in the holograms.yml and restarted the server and it showed as a block.**

Aside from those few things its looking good.

Latest build, and on paperspigot 1372.

**Comment by HomeLandingsDE** [comment]
in addition, enchanted items are displayed normally and customheads like the plugin HeadDataBase are displayed as Steve heads
Can you chance this?

**Comment by Zrips** [comment]
@HomeLandingsDE 
Will add separate variable to grab exact item from players hand which will include all extra information about that item, like head texture and similar.
