### ISSUE TITLE
Custom alias "?" 

### ISSUE THREAD

**Issue by zeuzi** [Zrips/CMI#1670]
**Alias editor create a command on ?**
So my issue is i want to create a command when typing /? but its not working just reproduce it youll see

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`): 8.5.6.1** 

**Server Type (Spigot/Paperspigot/etc): Craftbukkit** 

**Server Version (using `/ver`): 1.13.2 ** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by zeuzi** [comment]
Fix for anyone with this problem until its fixxed: Edit /CMI/CustomAlias.yml and add: 
`  ?:
    Cmds:
    - fromConsole! msg [playerName] (text)`

**Comment by ZodoxMC** [comment]
hmm i cant really reproduce it, 

  ?:
    Cmds:
    - cmi ctext help

works for me but in the way that just /? links to my /help command

im quite unsure what exactly doesnt work for you

**Comment by Zrips** [comment]
This was fixed and should be in working condition with latest builds
