### ISSUE TITLE
Worldguard blocked-cmds

### ISSUE THREAD

**Issue by cosmicvibration** [Zrips/CMI#1671]
I've set a world guard region to block the /cmi tpahere command.  When I try the command, I get the world guard message "/cmi tpahere cosmicvibration is not allowed in this area " but the command still executes, sending a tp request to the player.

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**Cmi Version (using`/cmi version`):** 8.5.6.1 -> 8.6.0.3

**Server Type (Spigot/Paperspigot/etc):** spigot

**Server Version (using `/ver`):** 1.12.2

**Relevant plugins (Delete if this isn't needed):** world guard

**Comment by Zrips** [comment]
Commands seams to be blocked correctly now and they are not being performed if that happens.
