### ISSUE TITLE
tppos pitch and yaw inverted

### ISSUE THREAD

**Issue by kikelkik** [Zrips/CMI#1672]
**Description of issue or feature request:**
/tppos (playerName) [x] [y] [z] (world) (pitch) (yaw) (-rng:[range])
All other teleport commands (e.g. /minecraft:tp, /cmi tp) recognize the first parameter after coordinates as yaw-rotation followed by pitch-axis. Despite of the tppos command where the order of pitch and yaw parameters is inverted. 
This is very uncomfortable and not as intuitive as it could be.

**Cmi Version (using`/cmi version`):**  8.6.0.3

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** #622

**Comment by mercurialmusic** [comment]
You're right, but it's been like that for years and the problem with fixing it now is that my entire server was set up with the CMI order and that would be a massive pain in the backside to have to go through all of those and change them around. Likely the same for most users.

**Comment by Zrips** [comment]
At this point it would be quite inconvenient to switch them around, so we will have to keep it as it is.
