### ISSUE TITLE
How to break signs with Public Interactive Comands

### ISSUE THREAD

**Issue by Segysmundo** [Zrips/CMI#1673]
Hi there, I created some public interactive commands for people to use on their signs by using the **[ic:command]** on the sign's first line. But after creating them they can't break the signs since left click and right click are used to interact with the sign's action.

Could you add an option on interactive commands to only happen with right click so players can break the signs with left click like they normally would?

**Comment by Zrips** [comment]
it is possible by simply making them right clickable. This can be done by adding specialized commands special criteria as **click:right!** this will only perform command when player right-clicks sign, but they can still break it
