### ISSUE TITLE
Sitting doesn't work on prismarine stairs (any of the types)

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#1674]
**Description of issue or feature request:**

Sitting doesn't work on any of the three types of prismarine stairs.  It works fine on other stair types.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Animations:
  # Enable siting on stair block by clicking on them with empty hand or by looking and using command
  # Requires cmi.command.sit.stairs
  SitOnStairs: true
  StairsAsChairs: true
  SlabsAsChairs: true
  CarpetsAsChairs: false
  RemoveFromChairOnDamage: true
  # Player will sit on chair only after rapid double click
  DoubleClick: false
  # Delay in milliseconds between clicks to sit on chair when double click is enabled
  DoubleClickDelay: 200
  # Range in blocks from player to look up for valid chair block
  ChairRange: 4

---

**Cmi Version (using`/cmi version`):** 
 -------------------------------------------------- 
CMI plugin version: 8.5.6.0-> 8.6.0.3 
Server version: Spigot 1.13.2-R0.1-SNAPSHOT 
Vault version: 1.7.1-b91 
--------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-Spigot-1a3504a-a46fdbc (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
(final 1.13.2 build)

**Comment by mrfloris** [comment]
Hi there, 

I am on latest CMI version and 1.14.1 of Spigot and sitting on the 3 prismarine stairs seems to work for me. 

Given, I am in creative mode, and an operator. 

Maybe try upgrading and see if it has been resolved by now in a newer cmi build?

**Comment by Momshroom** [comment]
Works for me when I'm in creative mode, too... but not in survival... very odd.

**Comment by Momshroom** [comment]
It's working now.  Ty, Floris.
