### ISSUE TITLE
Create your own Votelist?

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1677]
Good afternoon, everyone.
This time it's not about a bug but rather a question to the Cmi community.

So far I use CMI but and the Vote interface. But to call the /vote LIste I still use the plugin Votelist.
But this causes problems in the 1.14. That's why I'm thinking if you can create such a Votelist with CMI?

At the moment the list looks like this when you make /vote:

![2019-05-02_14 26 54](https://user-images.githubusercontent.com/35557302/57075368-e2829f80-6ce6-11e9-83d0-6f6d086be8c0.png)

Now my question you can also do that with all the links with CMI ?

But the one instead of the long URL simply 
Vote 1
Vote 2
Vote 3......

is displayed as a link?

That would save me a plugin more thanks to CMI .

**Comment by TobiTechCZ** [comment]
Yes, using http://www.zrips.net/cmi/custom-text/ create custom text with url <T>Text</T><URL>www.google.com</URL> and create customalias in cmi

**Comment by Blueeyestar** [comment]
thanks, I'll take a look at it :)

**Comment by Blueeyestar** [comment]
**I guess I'm doing something wrong... Anybody know how to do it right?**

Voten:
    Cmds:
    - fromConsole! msg!<T>Text</T>< URL>www.google.com</URL>

**Comment by Baktus79** [comment]
What are you trying to do?

**Comment by Baktus79** [comment]
You can use `/cmi editctext`

Then you will get something like this
![image](https://user-images.githubusercontent.com/19745447/57327004-19551d00-710e-11e9-90b6-ae7167596ceb.png)

Yours will mostly be empty. Just click on the pluss sign, enter **vote**

Then add the lines you want to show when you type `/vote`
![image](https://user-images.githubusercontent.com/19745447/57327132-6cc76b00-710e-11e9-9ff6-c8dbc70864e6.png)

The image above look like this
![image](https://user-images.githubusercontent.com/19745447/57327253-b87a1480-710e-11e9-9a4d-cab1e832985d.png)

**Comment by Blueeyestar** [comment]
Very nice solution. I like :)
