### ISSUE TITLE
[Feature request] compass bossbar target with /cmi compass

### ISSUE THREAD

**Issue by kassadGLA** [Zrips/CMI#1678]
**Description of feature request:**

Add target to compass bossbar that was set using `/cmi compass` command. Like `home`, `spawn` and `death`.

Best regards.

**Comment by Zrips** [comment]
Target to where? Player? Location?

**Comment by user127001** [comment]
Any target that was set. If I set player as target - add this to compass bossbar with symbol 웃 (should be configurable), If I set lacation as target - ꖴ, etc.

**Comment by Zrips** [comment]
Will add an option to show compass target location. Tho no separation between player target and general location target.
