### ISSUE TITLE
error on 1.14

### ISSUE THREAD

**Issue by mmuziek** [Zrips/CMI#1679]
**Description of issue or feature request:**
gives massive error in console. i have no idea where it came from
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
##https://pastebin.com/L0NUL13n ##
####################
```
---

**Cmi Version (using`/cmi version`):**  8 6 0 3

**Server Type (Spigot)** 

**Server Version (using `/ver`):** 1.14-R0.1

**Comment by Zrips** [comment]
Should be up and running correctly with latest builds
