### ISSUE TITLE
cmi hologram remove??? Don't exist?

### ISSUE THREAD

**Issue by RustyDagger** [Zrips/CMI#168]
I think the title sums up this feature request my self and Admins have been trying to remove an Unwanted Holo for some hours we tried butchering it we tried using the armorstand editor but it just comes back the next reload we even deleted the save file for them and it was still there. Help!

Button to remove could be added in settings menu also.

**Comment by Zrips** [comment]
Well sorry for this, forgot to make one... Will be added with next build today with some extra fixes/adjustments.

**Comment by RustyDagger** [comment]
After tonight's update The delete button is now present on /cmi hologram But it does not work. I can see it is running the command from console but the stands are not being removed and nor is the Holo name on the /holograms list.

**Comment by Zrips** [comment]
@RustyDagger 
That's... Strange... i just retested to be sure that everything works as it should, and it does work. Holograms are being removed from all users, from list and from save file.

**Comment by RustyDagger** [comment]
your welcome to join our server and see for your self. its closed beta atm so ill have to pm you the IP on spigot. yeah we are just clicking the little red X and its not removing them. we was however now able to edit the holograms.yml and reload it with cmi reload.

**Comment by RustyDagger** [comment]
Strange I just tried it again and it worked.

**Comment by RustyDagger** [comment]
Ok found the cause its if it starts with a capitol you cant delete it.

**Comment by Zrips** [comment]
Och, good point, found small mistake, will be fixed with next build.

**Comment by RustyDagger** [comment]
Cool, yeah no big deal its workable at this point with the reload working now.
