### ISSUE TITLE
Rank Prefix problem

### ISSUE THREAD

**Issue by Asbestos12** [Zrips/CMI#1684]
**Description of issue or feature request:**
Im having problems with CMI. I tried installing CMI however my rank prefixes from PermissionsX have been removed/gone missing. They show up in the TAB but not in chat. Is there a way to fix this? 

---

**Cmi Version (using`/cmi version`): 1.12** 

**Server Type (Spigot/Paperspigot/etc): Spigot** 

**Server Version (using `/ver`): 1.12** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
If you want to use it for a chat message control, then you will have to set appropriate format to include players group prefixes with {prefix} and similar things.
