### ISSUE TITLE
Cooldown still counts on tp fail

### ISSUE THREAD

**Issue by CupcakeCrush** [Zrips/CMI#1686]
**Cmi Version (using`/cmi version`):** 8.6.0.3

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.14

I have a 30 second warmup and a 24 hour cooldown on /home. If a player does not have a bed and they use the /home command or they die, the cooldown starts. If the player moves during the warmup, the cooldown starts. The 24 hour cooldown will disallow the command /home to be used again for 24 hours even if the player never sucessfully teleports home or dies.

**Comment by Zrips** [comment]
With latest builds this should no longer happen.
