### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Zoneman1972** [Zrips/CMI#1687]
Can you possibly add a "requirement" option in the ranks.yml.

I would like to be able to have my players run the command /rules and view all the pages before being able to rankup.
Are you able to add a requirement for Command Run / Command Completed / Command Entered or similar please?

**Comment by Zrips** [comment]
Simply make use of permission requirement. Create rules pages with custom text feature and at last page make a button "Accept" which will perform console command and adds permission node (like cmi.readrules) to that player which will indicate that he read (yea, right, like anyone reads those ones) and accepted rules.
