### ISSUE TITLE
Random tp doesn't work 1.14

### ISSUE THREAD

**Issue by BeeRando** [Zrips/CMI#1691]
####################
####################

https://pastebin.com/mhhAr9Zp

**Cmi Version (using`/cmi version`):** 
8.6.03
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.14-R0.1-snapshot

**Comment by Zrips** [comment]
After today's update, test it, and if issue persists, inform me.
