### ISSUE TITLE
CMI crashes servers with errors

### ISSUE THREAD

**Issue by abhisantos** [Zrips/CMI#1692]
**Description of issue or feature request:**
Some errors of CMI are crashing alnd lagging the server.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
error 1: https://pastebin.com/4HVcB4Lk
error 2: https://pastebin.com/icvY4pCt
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.0.3
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.8.8
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
This will be fixed with next build. Today.
