### ISSUE TITLE
./time autorealtime doesn't work

### ISSUE THREAD

**Issue by Aero4K** [Zrips/CMI#1693]
**Description of issue or feature request:**
_Title says all_

**Cmi Version (using`/cmi version`):** 
_8.6.1.0_

**Server Type (Spigot/Paperspigot/etc):** 
_PaperSpigot_

**Server Version (using `/ver`):** 
_624_

**Comment by Zrips** [comment]
It does say something, but extra information is needed. What outcome are you getting when using that command? What time is indicated in chat and what it should be? Does it change time at all or is it frozen in one place?

**Comment by Aero4K** [comment]
Hi,
When typing /time autorealtime in-game, nothing is returned in the chatbox, nothing regarding the in-game time changes, and nothing is sent to the console. It seems to do nothing at all.

**Comment by Zrips** [comment]
My bad, in general, you are missing *start* or *stop* extra variable for it to pick it up as valid command, but will make changes to behave in the same way as using *start* variable when none is provided for autorealtime.
