### ISSUE TITLE
CMI error in console (Think it is MySQL)

### ISSUE THREAD

**Issue by Relaxing9** [Zrips/CMI#1697]
**Description of issue or feature request:**
For a while now, ever since I had 1.14, I had an error in the console, at first I thought it was something else but today when enabling plugins one by one I noticed it was caused by CMI. See [pastebin](https://pastebin.com/6KV7suhj) for further details. I also believe it is causing a server overload warning as well. (Annoying Spam of it)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**

[pastebin](https://pastebin.com/6KV7suhj)
(Line Numbers 464 & 465)

---

**Cmi Version (using`/cmi version`):** 8.6.1.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-1eece4f-68e72f6

**Comment by Zrips** [comment]
Its basic information that custom recipe failed to load for particular item. Try updating its recipe if you have imported old setup. Other then this, its not harmful error.
