### ISSUE TITLE
Bug between CMI and Crate Reloaded

### ISSUE THREAD

**Issue by Segysmundo** [Zrips/CMI#1699]
There seems to be a weird bug/interaction occurring between CMI's aliases and the command rewards in [Crate Reloaded'](https://www.spigotmc.org/resources/pro-crate-reloaded-mystery-crate-1-8-1-14-x.3663/)s crates.

If I set the original commands of any plugin inside a crate's rewards they are executed fine.

But if I create an alias for a command through CMI's custom aliases and use that alias as a reward inside the crate, when I open the crate the command is executed twice.

I informed Crate Reloaded's author too since I don't know which of the 2 plugins is causing this.

---

**Cmi Version (using`/cmi version`):** 8.5.6.1 (Version where you updated API and Alias handling)

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.13.2

**Relevant plugins (Delete if this isn't needed):** CMI and  [Crate Reloaded](https://www.spigotmc.org/resources/pro-crate-reloaded-mystery-crate-1-8-1-14-x.3663/)

**Comment by Zrips** [comment]
Will be redoing some of the alias handlings in general with next update which should solve issues like this one once and for all.
