### ISSUE TITLE
Add a command to uncuff

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#170]
I recently had an issue with one of my staff members cuffing a player and was unable to easily uncuff them. There is no direct command to uncuff. You have to do /cmi cuff <player> false for them to be uncuffed.

**Comment by LogGits** [comment]
Go into Alias.yml and change these values to true:
```
  # /cmi cuff $1-
  /cuff: true
  # /cmi cuff false $1-
  /uncuff: true
```
