### ISSUE TITLE
portal + random teleport?

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1711]
Is there any way that you can be teleported with the Cmi Random in the farm world? We use MultiWorld. We want the users at the spawn to go through a portal and be randomly teleported to the farm world.

**Comment by LogGits** [comment]
Our random teleport supports a world variable:
```
/cmi rt [playerName] [worldname]
```
in ur case `/cmi rt [playerName] farm`

**Comment by Blueeyestar** [comment]
Thanks, that's what I was looking for. The plugin is simply mega class

**Comment by Blueeyestar** [comment]
**setup a portal and add the command to the portal instead of a location.....**

I haven't quite understood that yet....
