### ISSUE TITLE
CMI Hologram ICONs floating into the sky.

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#1715]
When you create a hologram with an ICON:emerald the emerald will float into the sky like a balloon.

---

**Cmi Version (using`/cmi version`):** 8.6.1.1

**Server Type (Spigot/Paperspigot/etc):** Paper-8 

**Server Version (using `/ver`):**  1.14

**Comment by Ste3et** [comment]
I can confirm this kind of bug on my 1.14.1 Server i can reproduce this with the ICON:%iteminhand%

https://youtu.be/eENaguwdpx8

**Comment by Zrips** [comment]
Yea, this is confirmed issue and will be fixed with today's update.
