### ISSUE TITLE
[BUG] Internal Error for teleport commands on 1.8

### ISSUE THREAD

**Issue by Drc-DEV** [Zrips/CMI#1729]
**Description of issue or feature request:**

When doing teleport commands such as /spawn, /warp, /tp, /tphere ...  it throws an internal error in console, and throws a NoSuchMethodError in console.

---
```
####################
## PASTE ERROR HERE ##
####################
```
https://pastebin.com/ZCEbNGAv

---

**Cmi Version (using`/cmi version`):**  8.6.1.3
**Server Type (Spigot/Paperspigot/etc):** PaperSpigot 1.8.8 R.02-SNAPSHOT

**Comment by Zrips** [comment]
Should be fixed with todays update
