### ISSUE TITLE
/give hideflags

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#1730]
I would like the attribute hideflags added so that I can give an item with an enchantment to a player while the flags are hidden.

currently you have to use the command /cmi hideflags, but that means the player has to be holding the item in the hand which complicates things when you are giving the player multiple items.

**Comment by mrfloris** [comment]
I make a kit with the items I want, and then /cmi kit give it to the player on those commands and shops etc.

This way i can have any customized item (or items) given to the player, and if their inventory is full it will drop on the floor in front of them. 

`/cmi hideflags hide_enchants` etc..

**Comment by 0xC1A551C** [comment]
That is

> I make a kit with the items I want, and then /cmi kit give it to the player on those commands and shops etc.
> 
> This way i can have any customized item (or items) given to the player, and if their inventory is full it will drop on the floor in front of them.
> 
> `/cmi hideflags hide_enchants` etc..

That would be a really weird way for me to do it for when I have a crate that the player opens with random items I would need to make a bunch of kits.

For now I am using build in 1.14 give commands but they always change on update, and it would be really nice if CMI would add this since they already have attributes. Thanks though

**Comment by Zrips** [comment]
Well another option is to use saved items feature where you can save any item and give it to any player with single command. This can simply things then creating bunch of kits.
Other thing is that give command actually supports official give format when defining extra things. Something like {HideFlags:#}

**Comment by 0xC1A551C** [comment]
> {HideFlags:#}

I tried /give (username) diamond e sharpness:1 {HideFlags:1} which should hide the enchant flags but instead it removed the enchant altogether
