### ISSUE TITLE
%rand/1-20% not working with custom alias

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#1731]
Using %rand/1-20% in a custom alias (not tested anywhere else) does not work at all.

example:

asConsole! cmi warp %rand/1-20% [playername]

Paper 1.14
8.6.1.3

**Comment by mrfloris** [comment]
Cannot reproduce, sorry. 
https://youtu.be/ju2pd6Ant1k
latest Spigot 1.13.2 and latest CMI build.

**Comment by 0xC1A551C** [comment]
> Cannot reproduce, sorry.
> https://youtu.be/ju2pd6Ant1k
> latest Spigot 1.13.2 and latest CMI build.

It does seem to work with the give command, but try doing it with a warp command.

Lets say I have multiple warps labeled as mine1 to mine20. Now try to run the command /cmi warp mine%rand/1-20% it does not work.

**Comment by Zrips** [comment]
@0xC1A551C 
that %rand/1-20% is for give command mainly, if you want random number in others by using alias editor, then utilize **asConsole! cmi warp %cmi_random_1_20% [playername]** which is actual placeholder which can be found in placeholder list and will randomize warp from 1 to 20
