### ISSUE TITLE
cuff Serious bug (Please fix it now)

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#1732]
https://www.dropbox.com/s/yi1kxzcwcbfi3fc/Minecraft%202019.05.12%20-%2010.57.27.01.mp4?dl=0

see this

if player Once cuff , Use Trident
Will be copied indefinitely

Please fix it now

---

**Cmi Version (using`/cmi version`):** 8.6.1.3

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.13.2

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Cant reproduce, but i will add extra protection which will prevent item pickup while you are cuffed and shooting projectiles too. So that should solve this issue with next update
