### ISSUE TITLE
Cannot use [playerName], %player_name%, or {PlayerName} when creating a attached command

### ISSUE THREAD

**Issue by stifflered** [Zrips/CMI#1735]
**Description of issue or feature request:**

When attaching a command to an item, any instance of [playerName], %player_name%, or {PlayerName} in the command is replaced by the creator of the attached command. 

For example, my username is stifflered and I run this command to attach a command to an item:
`/attachcommand !limiteduse:1!;;!cc!cmi effect [playerName] fast_digging 30 1;;!cc!cmi effect [playerName] speed 300 1;;!cc!cmi sound entity_generic_drink [playerName] -v:100;;!cc!cmi titlemsg [playerName] %subtitle% &eYou feel energized.`

When any player users that item, the sounds and titles are sent to me rather than to the player. As you can see in the attached screenshot, the "[playerName]" tag is replaced with "stifflered".

![attachcommand](https://user-images.githubusercontent.com/5891184/57581295-f95d8a80-747a-11e9-8d18-10bc5cb059c8.JPG)

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

---

**Cmi Version (using`/cmi version`):** 
8.6.1.4

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
Spigot 1.14-R0.1-SNAPSHOT

**Comment by JGuerndt** [comment]
As a temporary fix, use the full command (/cmi attachcommand). It seems that when you do not use the alias, the placeholder works correctly. /cmi attachcommand !limiteduse:1!;;!cc!cmi effect [playerName] fast_digging 30 1;;!cc!cmi effect [playerName] speed 300 1;;!cc!cmi sound entity_generic_drink [playerName] -v:100;;!cc!cmi titlemsg [playerName] %subtitle% &eYou feel energized.

**Comment by Zrips** [comment]
Should we working correctly after next update.
