### ISSUE TITLE
Zrips.CMI.Modules.Portals.PortalManager.<init>

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1738]
CMI-Version: 8.6.1.4
Spigot:CraftBukkit version git-Spigot-f8e1ae2-a46ef53 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

I always have this message in the console, does anyone know what to do with it ? and how to remove it?

https://pastebin.com/hE7kv882

**Comment by Zrips** [comment]
Should no longer be present
