### ISSUE TITLE
/cmi ic Problem?

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1741]
Cmi-Version: 8.6.1.5

How do you do?
I have set up a button for the users where they can unlock themselves.
Actually the command is /rules

If you type it in the chat the Gui opens.

But this one I had always put on the button:

/cmi ic new free

Button selected 

then the command

rules

but lately nothing happens anymore. the command is not executed. has anything been changed?

**Comment by 0xC1A551C** [comment]
Check if the IC command is still attached to that block... CMI has a bug where IC blocks/entities vanish. Update your version too.

**Comment by Zrips** [comment]
Should be working now correctly.
