### ISSUE TITLE
enchantLimits no work ( check)

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#1745]
![image](https://user-images.githubusercontent.com/5382252/57521840-e56b3900-7353-11e9-900a-d360fc8e9d80.png)

enchantLimits no work , check

i set dig_speed: 3
still have dig_speed: 5

and
can you add /sethome , Can I use other languages? Chinese

like , /sethome 測試

**Cmi Version (using`/cmi version`):** 8.6.1.5

**Server Type (Spigot/Paperspigot/etc):** Ppaer

**Server Version (using `/ver`):** 1.13.2

**Relevant plugins (Delete if this isn't needed):**

**Comment by p82183645** [comment]
hallo , check thank
the no work 8.6.2.0

**Comment by Zrips** [comment]
Enchant limits only apply for enchant command, not enchanting in general.
And i can add option to define valid home name characters by utilizing regex format
