### ISSUE TITLE
cuff Serious bug still (Please fix it now)

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#1747]
https://github.com/Zrips/CMI/issues/1732#issuecomment-491572080

still bug
the playe cuff false , still copy
If you have been cuff, this will happen.

---

**Cmi Version (using`/cmi version`):** 8.6.1.5

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.13.2

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Players are been prevented from item pickup or projectile launch. So it should be some other plugin interfering here. Could you test it out with only CMI installed to confirm that this issue originates from CMI?

**Comment by p82183645** [comment]
> Players are been prevented from item pickup or projectile launch. So it should be some other plugin interfering here. Could you test it out with only CMI installed to confirm that this issue originates from CMI?


i test , is cmi bug
if player before cuff true , after /cuff false , the no cuff
the bug happen

**Comment by Zrips** [comment]
I can understand that its related to cuff command, but it could be that we have issue with another plugin which performs different actions while player is cuffed which creates this issue. So we need to test it to make sure that its CMI issue alone and not compatibility issue with another plugin. As currently i cant reproduce it as you cant pick up items from ground. i could not even reproduce before i could pick them. So something is interfering with correct CMI work, we need to figure out what exactly before i can fix it properly.

**Comment by p82183645** [comment]
> I can understand that its related to cuff command, but it could be that we have issue with another plugin which performs different actions while player is cuffed which creates this issue. So we need to test it to make sure that its CMI issue alone and not compatibility issue with another plugin. As currently i cant reproduce it as you cant pick up items from ground. i could not even reproduce before i could pick them. So something is interfering with correct CMI work, we need to figure out what exactly before i can fix it properly.

the player no cuff stats
the cuff false

**Comment by p82183645** [comment]
> I can understand that its related to cuff command, but it could be that we have issue with another plugin which performs different actions while player is cuffed which creates this issue. So we need to test it to make sure that its CMI issue alone and not compatibility issue with another plugin. As currently i cant reproduce it as you cant pick up items from ground. i could not even reproduce before i could pick them. So something is interfering with correct CMI work, we need to figure out what exactly before i can fix it properly.


can fix?

**Comment by Zrips** [comment]
I cant fix something i cant reproduce. You need to test it out without any other plugin, only CMI installed to make sure that its issue with CMI and not another plugin.

**Comment by p82183645** [comment]
> I cant fix something i cant reproduce. You need to test it out without any other plugin, only CMI installed to make sure that its issue with CMI and not another plugin.

my point is

If you use /cmi cuff for players, it works fine.

But if cancel the player's cuff
This player will have a BUG

Does not happen in cuff true state
Is happening in the false state

**Comment by Zrips** [comment]
What i can do at this point as i cant reproduce it. We can simply allow cuffed player to pick up items in normal way. This should solve your issue.
