### ISSUE TITLE
[Suggestion] Allow holograms to run commands.

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#1750]
This would be useful for scoreboards like this plugin which no longer really works properly: https://www.spigotmc.org/resources/holographic-scoreboard.2700/

**Comment by Zrips** [comment]
There is option to make holograms clickable (1.9+ servers) go to hologram Gui click on stick, then on bow, enter commands and you are done.

**Comment by mrfloris** [comment]
Hopefully this video helps explain it, I made it a while ago for some discord users who had questions;

https://www.youtube.com/watch?v=6Oc_pf4LHCw

**Comment by 0xC1A551C** [comment]
@Zrips @mrfloris 

I had a feeling you guys would say this lol however this isn't what I meant. I was hoping for a scoreboard type thing where the hologram would run the command and display the output like this:

![image](https://user-images.githubusercontent.com/36227001/57739509-b7923700-7668-11e9-87b2-26540257f499.png)

Some plugins don't support placeholder api but have a /pvptop kills command
