### ISSUE TITLE
Elytra Launch no item

### ISSUE THREAD

**Issue by SpookyPirate** [Zrips/CMI#1758]
**Description of issue or feature request:**

---

Hello. I would greatly appreciate it if you were to add an option for performing the elytra boost without requiring an item in your hand. There is another plugin on spigot (https://www.spigotmc.org/resources/superelytra-improved-elytra-flight.19382/) that does launching but I would like to avoid installing another plugin since cmi already has this ability. Some people in the comments of that section said that the launch is triggered while people are holding shift to avoid falling so a toggle command would probably be ideal. Another possible solution may be to break the launch from the boost mechanic to that you could require using a feather for boosts but be able to shift click while holding a rocket to launch. Thank you for all of your hard work and for making such an amazing plugin that will definitely be the go to essentials plugin for years to come.

**Comment by Zrips** [comment]
Will add option to define different item for launch and option to define material as AIR to avoid requiring any particular item for the action, boost or launch
