### ISSUE TITLE
CMI message shows two messages

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#1761]
Typing this command: /cmi msg (playername) !test will output two messages even though the ! variable should hide the message part if that makes any sense. My socialspy is disabled and set to false.

![Screenshot from 2019-05-14 21-45-52](https://user-images.githubusercontent.com/36227001/57749158-ce00b880-7691-11e9-8ab1-7561e6f83d16.png)

**Cmi Version (using`/cmi version`):** latest

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.14.1

**Comment by Zrips** [comment]
Well ! only removes senders name for receiver, if you are sending private message to yourself, then you will have double message. Sending this message to some one else, you will have generic message what you have sent (second line) and receiver will get clean message. Tested with latest CMI and 1.14.1 version
