### ISSUE TITLE
CMI Ranks send commands as operator instead of console.

### ISSUE THREAD

**Issue by omgitsAngus** [Zrips/CMI#1762]
**Description of issue or feature request:**
Hi there,

I would love the ability in the ranks.yml to set it that the commands are sent as an operator instead of console. I use luck perms to manage these groups for people switching from group to group and having permissions, and my console is constantly spammed with this: https://hastebin.com/icoxepisik.shell. I have contacted the LuckPerms developer and he has said it is because CMI sends these commands from console, sending the output of the message to console. If these commands were run by a non-existent operator, then theoretically these messages would disappear and I would be able to begin using console to manage the server again. This would be amazing. Thanks!
---

**Comment by Zrips** [comment]
Good idea is a good idea. Will make this one happen with next update.

**Comment by omgitsAngus** [comment]
Amazing, thank you!

While I have got your attention, I have got another idea that could be quite beneficial to ranks.

It would be good to be able to setup the commands so some commands don't happen if the player has a group or permission. E.g. this kinda setup.

  - "spawn [playerName]"
Console:
  - "[console] spawn [playerName]"
  - "[groupcheck:Member] spawn [playerName]"
  - "[permcheck:Member] spawn [playerName]"

Up to you, could be way harder than it's worth. Thank you!!

**Comment by Zrips** [comment]
Isint checking by group is more or less exact same thing as to check by permission node? You could always simply add some specific permission node to the group to indicate which one it is when checking if player has particular permission node. Or did i got it wrong in my head?

**Comment by omgitsAngus** [comment]
Theoretically yes, you could create a group and give it that permission, and make it a subgroup of the player. It would make more sense to allow for both as this could make you have to have extra groups or confuse some people when setting it up. Take this example as a really rare case:

Some players win their donor rank from a crate, which gives them everything in the rank except the permission to teleport to the donor mine.
When players buy the rank, it gives them the donor group and the permission for the donor mine.

Then, the command is just run for people in that donor group who had purchased the rank, and not those who had got it from winning it in a crate, drop party etc etc etc.
