### ISSUE TITLE
CMI [item] function not working in newest version.

### ISSUE THREAD

**Issue by QueenAngus** [Zrips/CMI#1763]
**Description of issue or feature request:**

Hi there,
In the latest version, [item] and [i] has stopped working throughout my server, though I have not changed the configuration files at all. I have restarted, switched to another plugin that worked fine but had bad formatting so I don't believe another plugin could be causing it. Really love this feature!!

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.20
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.12.2
**Relevant plugins (Delete if this isn't needed):** 
DeluxeChat, DiscordSRV (could maybe cause the issue)

**Comment by the456gamer** [comment]
I am pretty sure [I] only works with cmi handling chat AFAIK

**Comment by Zrips** [comment]
Like @the456gamer pointed out, you will need to have CMI chat handling and hover over messages enabled for this one to work correctly. It does work on 1.14.1 version with latest build as of my testing.

**Comment by omgitsAngus** [comment]
Hi there! Thanks for your response.

I haven't changed my CMI config in terms of these settings in a while and have been trying to test a few things to fix this issue. However, I still don't seem to be able to fix the chat issue. It could be another plugin causing the issue, but I am unsure. I couldn't find specifically "HoverOverMessages" in the config. Here is my CMI config: https://hastebin.com/texukedehi.coffeescript. Any advice would be awesome!! Thanks guys.

**Comment by the456gamer** [comment]
Just looked at your config
`Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: false
  # When set to true, regular and private messages (excludes clean messages) will have aditional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
  # To change default hover over messages seen on sent message, go to your locale file to Chat section
  ClickHoverMessages: false
  # Enables support for DiscordSRV plugin
  DiscordSRVPublicChat: true
  # Enables support for DynMap web chat
  DynMapChat: false
  # When set to false, each time you will use /r you will reply to person you previously sent message directly or to person who sent you message if there is none you have conversion before
  # When this set to true, players with /r will reply to person who last sent private message. This can result in confusion when using /r while getting private messages from multiple players
  ReplyToLastMessenger: false
  # If ReplyToLastMessenger is set to false, then timeOut will be taken into consideration to who you should reply
  # If you had conversation in last 120 seconds (default) then even receiving message from 3rd person, you will still reply to original player
  # If you had conversation in longer then 120 seconds period, then you will reply to latest person who send you a message
  LastMessengerTimeOut: 120
  # Defines regex when replacing url in chat with short word
  # Examples:
  # (https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})
  # ((http|https|ftp|ftps)\:\/\/)?[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?
  # ((http|https|ftp|ftps)\:\/\/)?[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?([^\s]+)
  LinkRegex2: (https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})
  # When set to true, particular variables in chat will be translated into items player are holding. List of variables belove
  HoverItems: true
  # Defines regex when replacing item line in chat with players item in hand information. Only works when CMI hover over chat format is enabled
  ItemRegex:
  - (\[item\])
  - (\[i\])`

Modify chat format is disabled

**Comment by omgitsAngus** [comment]
Even with modify chat format is enabled, it still doesn't work. And I had it working without that setting enabled previously

**Comment by the456gamer** [comment]
Enable that, and click hover format and try with deluxe chat disabled

**Comment by omgitsAngus** [comment]
Can confirm.. It is DeluxeChat causing this issue.

**Comment by Zrips** [comment]
Hover over messages are completely separate from chat messages. So in order to have them we have to disable chat message, which means that you cant really have 2 plugins controlling a chat in nice way without bigger issues.
