### ISSUE TITLE
cmi reload bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#1764]
if /cmi reload ,  SavedItems.yml no reload
check

**Cmi Version (using`/cmi version`):** 8.6.2.0

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):**  1.13.2

**Comment by Zrips** [comment]
You will need to be more specific with the issue here. Whats exactly is going on in your situation? Are you manually editing SavedItems and then reloading CMI?

**Comment by p82183645** [comment]
> You will need to be more specific with the issue here. Whats exactly is going on in your situation? Are you manually editing SavedItems and then reloading CMI?

yes

**Comment by p82183645** [comment]
> You will need to be more specific with the issue here. Whats exactly is going on in your situation? Are you manually editing SavedItems and then reloading CMI?

can you fix? /cmi reload can reload SavedItems

**Comment by Zrips** [comment]
This should be working now coorectly
