### ISSUE TITLE
Different points at home for the command and the bed

### ISSUE THREAD

**Issue by DarkFort** [Zrips/CMI#1765]
Add the ability to set different home point names for the /sethome command and bed.
The player puts an end through the command /sethome, then somewhere puts the bed and this point is replaced. It turns out that the player lost the point at home, which he put through the team.
 
I propose to add the following parameters:
DefaultName: home # default point at home when typing /sethome
DefaultNameBed: bed # default point at home when clicking on the bed

**Comment by Zrips** [comment]
Will add option to define a different name for bed locations
