### ISSUE TITLE
1.14.1 Bugs

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#1767]
Hello, back once more for another minecraft update! Found a few bugs!

- None of the new mobs support this command `/i spawner:Fox`, getting a error.

- If you toggle vanish your nameplate (if colored -c:) does not update, just stays white. 

Spigot: 1.14.1
CMI: 8.6.2.0

**Comment by Zrips** [comment]
Both issues should no longer exist with next version

**Comment by SirGoldman-git** [comment]
You the man!
