### ISSUE TITLE
[BUG] Tridents and Back

### ISSUE THREAD

**Issue by SeruhioX** [Zrips/CMI#1769]
Fix the option to prevent ground clean from removing thrown tridents and fishing_rod.

Fix to allow players to use back to return to their death location when they have the cmi.command.back.ondeath permission.

**Cmi Version (using`/cmi version`):** 
8.6.3.0

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot 1.13.2

**Server Version (using `/ver`):** 
624 (latest in 1,13,2)

**Relevant plugins (Delete if this isn't needed):** 

Maybe Multiverse Core

**Comment by SeDark** [comment]
The error of the tridents has been solved.

We have discovered the reason why the /back does not work correctly, apparently MaSuite is interfering with respawn, the spawn of that plugin has been replaced by the one of the CMI and it seems solved.


-----------------------------------------


The fishing rod is still picked up when it is done /groundclean while it is being fished.

**Comment by Zrips** [comment]
Ground clean now excludes trident and fishing rod
