### ISSUE TITLE
QUESTION: hologram

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/CMI#177]
How can I use a specific item as a hologram?
So an enchanted egg, for example, without it changes every time I take something different in the hand

**Comment by RustyDagger** [comment]
Just don't use the placeholders to set the ICON just type in the name of an item like STONE

from the Holograms Wiki Page:   ICON:[itemName/id]:[data] 
ICON:Stone:3 will show floating diorite.
SICON:Stone:3 will show floating diorite. that does not spin or move up/down it will just face the player like a hologram. 

as for setting the enchanted egg I don't think it supports that if it does its not documented well. the Glowing is a NBT tag and making all that complexity seems like a headache.

**Comment by Zrips** [comment]
@HomeLandingsDE what @RustyDagger said
You can show particular items like it is in example, but currently its not supporting enchant effects
