### ISSUE TITLE
New Specialized Command Suggestion

### ISSUE THREAD

**Issue by Harveyplays02** [Zrips/CMI#1770]
**Description of feature request:**

This new specialized command will be able to check the value of a placeholder for the target player, and if it returns true, it performs the command. It could contain checks, such as "==", ">", "<", "!=" to check variables against text or numbers. It would look something like: `checkPlaceholder:%cmi_user_name%==HarveyPlays02!`. This could be useful if you want to trigger certain events depending on data from placeholders, maybe from custom usermeta data. Examples of this usage could be: `checkPlaceholder:%player_deaths%>10! msg! [playerName] &cYou really need to stop dying.`

---

**Comment by Zrips** [comment]
next version.
