### ISSUE TITLE
New 

### ISSUE THREAD

**Issue by QueenAngus** [Zrips/CMI#1773]
**Description of issue or feature request:**
Hi! I'm using the new asFakeOp! on CMI 8.6.3.0 and it is still sending output to the console. Can you double check for me that this is the correct format? I tried looking on the wiki but couldn't find any documentation for how to use this feature.

C:
  Enabled: true
  DisplayName: "&6&lC&r"
  AutoRankup: true
  MoneyCost: 200000
  Commands:
  - "asFakeOp! lp user [playerName] parent add c"
  - "asFakeOp! lp user [playerName] parent remove b"
  - "asFakeOp! cmi rankset [playerName] C"
  - "asFakeOp! crazycrates give P Rankup 1 [playerName]"
  - "asFakeOp! lp user [playerName] group remove a"
  NextRanks:
  - D
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.3.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.12.2
**Relevant plugins (Delete if this isn't needed):**

**Comment by the456gamer** [comment]
AFAIK luckperms still broadcasts perm and group changes to console even if they are made by ops
