### ISSUE TITLE
/cmi sell gui and slimefun

### ISSUE THREAD

**Issue by Yukyxy** [Zrips/CMI#1774]
**Description of issue or feature request:**

Hello, Cmi worth sell (/cmi sell gui) does not make the difference between a vanilla item and slimefun items.
diamond vs. diamond synthetic slimefun fun.

Could you add slimefun support? please

**Cmi Version (using`/cmi version`):** ALL

**Server Type (Spigot/Paperspigot/etc):**  spigot

**Server Version (using `/ver`):** 1.13.2 / 1.14 / 1.14.1

**Comment by the456gamer** [comment]
If there is slimefun lore, add it to bad lore or banned lore or wherever it is. It will stop players from selling slimefun items

**Comment by Yukyxy** [comment]
i can't rename or add a lore with slimefun :(

**Comment by ksrawlot** [comment]
the456gamer meant add bad lore in config.yml for cmi 
like if slimefun custom item is a diamond named Infinity Diamond
then add infinity to badlore in config for cmi.
