### ISSUE TITLE
Request: Armed Armor Stands

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#178]
All armor stands spawn with arms attached by default. Can be enabled/disabled in config.
Something like this:
https://www.spigotmc.org/resources/armorstand-with-arms.29883/

Obviously a low priority request but I think I'd be cool for CMI to add something like this in the future.
Thanks

**Comment by LogGits** [comment]
Or permission node based auto spawning armorstands with arms with the config enable option included.

**Comment by CloudeLecaw** [comment]
hehe a nice idea :D.. pls also an Option for Default size and plate or not plate ;)

**Comment by LogGits** [comment]
Next build will include armorstand arms autoplace permission node.
