### ISSUE TITLE
cmi.command.pay permission

### ISSUE THREAD

**Issue by QueenAngus** [Zrips/CMI#1780]
**Description of issue or feature request:**
I have /pay disabled by default (or so I thought) for every player. They can win it in crates. Somehow, every player has permission to do /cmi money pay, but when attempting to do /cmi pay they cannot. Is there different perms for the two? How do i disable them both for default players? 
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
Latest
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.12
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
This got fixed
