### ISSUE TITLE
Jail error : Could not pass event ServerCommandEvent

### ISSUE THREAD

**Issue by JohOply** [Zrips/CMI#1782]
**Description of issue or feature request:** 
---

When jail command is typed like "jail Player 1 r:test", it generates an error (it seems because time is too short)
If no time parameter is set ("min", "sec", "day"...), use minutes by default, perhaps?

**ERROR (DELETE IF YOU HAVE NO ERROR):**

https://pastebin.com/T3NEpyPu

---

**Cmi Version (using`/cmi version`):** 8.6.3.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** This server is running CraftBukkit version git-Spigot-f09662d-a46fdbc (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will be fixed with next build
