### ISSUE TITLE
Cmi Custom Alias Cooldown "#" doesn't stop other commands in the list.

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1783]
Using the CMI custom alias for a command to let it run a variety of commands, .. limiting it with a check for cooldown and money, .. it does visually stop, and does say things like 'you are on a cooldown for 3 more seconds' and 'you do not have money', but the other commands still get executed.

```
  welcome:
    Cmds:
    - fromConsole! cooldown:5#?! moneycost:20#?! broadcast! &3 [playerName] welcome at $1
    - fromConsole! cmi sound item_trident_return -p:0.8 -v:0.8 [playerName]
```

For example the above /welcome, has 2 commands, the first one has the cooldown, stop everything if fails, give a msg if it fiails, etc.. and the same for the money.

That works.

But it still plays the sound. 

https://youtu.be/ciiN4Cs13Mg

**Comment by Zrips** [comment]
This seems to be working correctly now. If its still issue for you, give me a shout

**Comment by mrfloris** [comment]
Thank you - will look into this and test it early November when I have more time. Thank you for looking into this.
