### ISSUE TITLE
Request: Add options to jail config

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#179]
Add options to 1) Remove player inv to a chest true/false 2) Allow escaping true/false 3) If escaping set to true add guard mobs 4) Guard mob type. etc. Would allow more custom uses for the jail command.

**Comment by Drewflav** [comment]
a la Skyrim?

**Comment by CypherPhyre** [comment]
Something like that maybe. Just to make it a bit more versatile.

**Comment by LogGits** [comment]
CMI currently offers a jail experience that is far too complex and useful. With that being said, we will not be pursuing this issue as it is unnecessary. What you are describing should involve the use of an custom external plugin that hooks into cmi.
