### ISSUE TITLE
API Hologram Question

### ISSUE THREAD

**Issue by Ste3et** [Zrips/CMI#1793]
**Description of issue or feature request:**

Hello i have a question about the HologramAPI i want to let my players make a custom Hologram of her Chunk for that i write a own class who use your API

https://gist.github.com/Ste3et/bfcf8c04632aa071148bc52dbb010e74

this what i used to call my method inside:

HologramOwner holo = new HologramOwner(player.getUUID())
holo.addLine()

It works it create a new Hologram but the hologram lines are not be sendet to the player, can you give me some tips what i did wrong ?

**Comment by Zrips** [comment]
Start by checking out this page http://www.zrips.net/cmi/api/ there are explanation how to use hologram API, add lines, update it, relocate it and so on

**Comment by Ste3et** [comment]
Thank you @Zrips it works very nice now, respect for your huge documentory Website
