### ISSUE TITLE
Unable to place floating signs with 7.3.9.0

### ISSUE THREAD

**Issue by mormoon** [Zrips/CMI#18]
When running version 7.3.9.0, players are unable to place floating signs next to each other using shift+right click. 

Edit: It works fine with version 7.3.8.5

**Comment by mormoon** [comment]
Whilst this command works, it is not very user friendly. The player is't made aware that he is supposed to type a command. I'd rather have it the way it was. I've had several "bug" reports from my players that suddenly placing sings does not work anymore. I'd rather disable the sign-edit feature altogether now. 

This change of behavior is not mentioned in the update notes.

> Fix for ctext auto alias issue
Small change for default private message format to include reset color code before message
Fix for color codes in alias command name
Improvement for arnorstand editor to only allow editor where player can interact with armor stand
Extra exception catchers for IC saving and loading to find possible issues some users having
Fix for vanish issue when players can see vanished ones on certain situations
Fix for enderchest button not working in invsee GUI
Small fix for player login event error
Small fix for location loading
Moved save method to async mode what should remove CMI data base manager from your timers entirely as it should not effect server anymore. Did some testing, all seems to be working correctly. But keep your eyes just in case :)
Option to disable permission error message into console
More informative message in console when player doesn't have permission node
Fix for importfrom command performing from console

**Comment by LogGits** [comment]
I don't believe the behaviour was ever changed. Even for me it still functions as normal (currently intended). Although, In my opinion, I do think that shift editing signs should be disabled by default (not too sure if this is already configurable). 

[Suggestion] The user should type /toggleshiftedit to start editing signs and then when they type it again or leave the server it should get turned off again.

**Comment by mormoon** [comment]
Well, it works fine in version 7.3.8.5. Since 7.3.9.0 it doesn't. So, you saying a bug was "fixed" and it works as designed now? 

I don't know if this is al all possible, but maybe if you look at a sign for say, 2-3 secs a message appears in your chat and asks you what action you would like to take.
>Edit Sign >Copy Sign >Paste Sign

**Comment by LogGits** [comment]
@mormoon What exactly is broken? (just so we are on the same page)

**Comment by mormoon** [comment]
7.3.9.0 or higher
https://gfycat.com/UntidyLastingGadwall

7.3.8.5
https://gfycat.com/DependentWeeklyBluewhale

**Comment by LogGits** [comment]
Ah i see, this is default minecraft behaviour. Open up a survival singleplayer world and try this. I am assuming that it was a bug that was silently patched in a cmi update because of a change.

**Comment by mormoon** [comment]
That's why I said, that the "new" behavior is not at all user friendly. How an earth are users supposed to know that something that has worked before since the time signs got introduced in the game now requires a command to get it working. It does not make any sense. Either re-introduce the bug or make a more user friendly system with signs. For now I've disabled the sign edit feature completely, because how it now works, is not a Quality of Life improvement, but rather the other way around.

**Comment by LogGits** [comment]
Would you think this is a better structure?
`Shift edit would be disabled by default. The user should type /cmi toggleshiftedit to start editing signs and then when they type it again or leave the server it should get turned off again.`

Another method is to make `/cmi toggleshiftedit` a temporary editing tool and `cmi.signs.shiftedit` a permanent sign editing. E.g. the command would self disable after the user leaves and/or the server restarts.

@Zrips you could even remove permission nodes for `cmi.signs.shiftedit` and `cmi.signs.shifteditbypass`. Then rely solely on `cmi.command.toggleshiftedit` (could even be changed to `cmi.command.shiftedit` and the command could be `/shiftedit` to be more user friendly). The bypass permission node could be `cmi.command.shiftedit.bypass`. The usage of the tool could be setup so when the user leaves or the server restarts the user is nolonger shiftediting.

**Comment by Zrips** [comment]
Will set toggleshiftedit to false by default, so you will need to use this before you have option to edit signs with shift+right click
