### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Roper89** [Zrips/CMI#1800]
1) Your plugin does not know how to block the insertion of eggs in spawner.
2) ClickHoverMessages - You can not customize your command and assign it to the right mouse click and left.
3) You can not disable the starter kit for new players. [Example](https://i.imgur.com/3NI63eF.png)  - When deleting the name of the starting set, the config itself restores it.
4) Tag - You can not turn off the sound notification.

**Comment by the456gamer** [comment]
1.
Make sure that
```
Spawners:
    Interact:
        EggRequiresPermission: true
```
Is true
Then negate permission

2.
In custom text? That's a Minecraft limitation. The server just knows that it has been clicked. Unable to do without client mods

3.
Have you tried deleting the kit that it is trying to give, or make that kit empty, or not deleting config option fully, and instead setting it to '[]'?

**Comment by Roper89** [comment]
1) You are right, sorry.

2) I want to replace the command at the click. Now this `/msg` 
Example: I want to change to `/tpa %palyer%` 

3) Thanks, I will try to do:
Kit: []

**Comment by the456gamer** [comment]
2.
Different commands on left and right click in chat are impossible afaik

**Comment by Zrips** [comment]
2.. At moment its not possible to change suggested command when clicking on players name in chat. maybe later we will have that option.
3. Setting that to any none existing kit will disable it
4. /cmi tagtoggle
