### ISSUE TITLE
CMI high in timings

### ISSUE THREAD

**Issue by Dakotaa** [Zrips/CMI#1804]
**Description of issue or feature request:** My timings are showing very high reading from CMI with the PlayerChangedWorldEvent. Timings can be seen [here](https://timings.aikar.co/?id=e3cfdd807c634601ac5810d3e2d0b80a) from the fourth to twelfth intervals.

**Cmi Version (using`/cmi version`):** 8.6.1.5

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper (626) 1.13.2

**Comment by Zrips** [comment]
You have like ~190 teleportations between worlds every minute. I don't know what type is your server, but this is something what you should not have even with 100 players online. Will make some optimizations for this event, but you have more serious issue somewhere else.
