### ISSUE TITLE
Adding support for CMI

### ISSUE THREAD

**Issue by Rocologo** [Zrips/CMI#181]
Im the DEV of MobHunting and one of my users has asked if I could add support for CMI.

I have found the API (https://github.com/Zrips/CMI-API) but I cant find the methods I need to make MobHunting Holograms using your API.

I need methods to create & remove holograms, and to add / remove / edit the text lines.

This is how it looks when I have done it with the Holograms API

https://github.com/Rocologo/MobHunting/blob/master/src/one/lindegaard/MobHunting/compatibility/HologramsHelper.java

So I hope I can get your help to add support for CMI?

**Comment by MCTyler** [comment]
Please Bump this.

**Comment by LogGits** [comment]
@Zrips has updated the holograms section of the api: https://github.com/Zrips/CMI-API/tree/master/src/com/Zrips/CMI/Modules/Holograms Let us know if anything is missing 👍

**Comment by Rocologo** [comment]
@LogGits @Zrips I need a working jar file or a maven repository before I can try to compile my plugin with the new methods you have made? 

The Jar in the API section is still CMI7.1.3.0 which does not contain the methods?

**Comment by Zrips** [comment]
@Rocologo That's... True... Will recompile new version for it and update download link with never version.

**Comment by Rocologo** [comment]
I have added support for CMIHolograms now, but I need @MCTyler to test my new version because I dont have a CMI 7.6.2.0 myself

**Comment by Rocologo** [comment]
I could use more of your API (f.ex your Bossbar ) but I would need my own jar to test my code.

**Comment by Rocologo** [comment]
@Zrips 

You have added MobHunting to your softdependlist in plugin.yml

softdepend: [Essentials, ProtocolLib, LWC, Vault, mcMMO, PlayerVaults, PermissionsEx, PowerfulPerms, bPermissions, GroupManagerX, zPermissions, LuckPerms, PlaceholderAPI, Votifier, Multiverse-Core, MultiWorld, My_Worlds, TheWorld, dynmap, Jobs, MobHunting]

This is wrong. MobHunting must be loaded after CMI. SO I have added CMI to my softdependl list.

**Comment by MCTyler** [comment]
I did that...Sry, I was just trying out different things.

**Comment by Rocologo** [comment]
Fixed...

**Comment by Zrips** [comment]
@Rocologo Added you into CMI buyers list so you can download full version for testing and simpler debugging.
