### ISSUE TITLE
individual warp permissions are broken

### ISSUE THREAD

**Issue by impmallet** [Zrips/CMI#1813]
Description: When assigning a permission to a player to user a specific warp, such as cmi.command.warp.awarp it will not allow the player to use the permissions until the base permission cmi.command.warp is added. After adding the base permission however, the player is able to use all warps.

CMI VERSION: 8.6.3.0

Server Type: Spigot

Server Version: 1.13.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
By default all warps can be used by anyone with cmi.command.warp command, if you want to make warps accessible by specific command then use /cmi editwarp command and set permission requirement to true. other option is when creating warp point add **true** as variable, in example **/cmi setwarp test true** which will request cmi.command.warp.test permission node from player when using that warp point. 
There was small bug related to GUI, after next update it will open GUI automatically after you create new warp point by default, can be disabled in config file.
