### ISSUE TITLE
SSL/TLS Mysql Encryption Question

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#182]
I have a few questions about the "useSSL: false" setting within CMI.

`By default, MySQL programs attempt to connect using encryption if the server supports encrypted connections, falling back to an unencrypted connection if an encrypted connection cannot be established.`

If this is true, then why does CMI have the option to enable or disable SSL/TLS? 

Do plugins need something added to them to allow for mysql over SSL/TLS even if the mysql server & client both have certificates setup?

**Comment by Zrips** [comment]
It was simply added as of request for users to enable it or disable depending of what they want. How exactly it behaves is out of my knowledge bounds. If its automatically adjusts, then keep it at true and all should be just fine.
