### ISSUE TITLE
Adapt trading via CMI

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1821]
Is it possible for you to adapt the normal Villager and dealers via CMI at some point? like in the plugin which unfortunately doesn't work anymore? 

https://www.spigotmc.org/resources/custom-village-trades.25792/

That would be super so you could control the economy via CMI!

**Comment by JohOply** [comment]
I think it's not necessary to create many issues :)
https://github.com/Zrips/CMI/issues/1683
