### ISSUE TITLE
/unloadchunks   is not working on 1.14.1

### ISSUE THREAD

**Issue by Newpoman** [Zrips/CMI#1824]
/unloadchunks command does not unload chunks on 1.14.1

**Cmi Version (using`/cmi version`):** 
8.6.3.2

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
spigot 1.14.1-R0.1-snapshot

**Relevant plugins (Delete if this isn't needed):** 
multiverse?

**Comment by Blueeyestar** [comment]
**It works for me.**

Spigot-Ver: CraftBukkit version git-Spigot-03bd4b0-17da342 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

CMI-Version: CMI8.6.4.0

Plugin:Multiverse-Core-3.0.0-SNAPSHOT

**Comment by Zrips** [comment]
Its issue with minecraft version itself and not CMI. Every plugin which was dealing with chunk unloading are not working after 1.14 update...
