### ISSUE TITLE
 ClickHoverMessages not gefixt!

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1828]
CMI: CMI8.6.4.0

Spigot; CraftBukkit version git-Spigot-03bd4b0-17da342 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

**The Cmi output should solve the problem with ClickHoverMessages. Unfortunately the problem is still solved when ClickHoverMessages: true there are no more messages in Discord in the chat. Only if you set it to false again.**

CMI update: Updated/fixed DiscordSRV handling which includes formatted messages coming from discord to match ingame formatted ones.

**Comment by ConfuseN** [comment]
Having the same issue on the latest spigot builds for 1.14.2. Able to replicate

**Comment by Vankka** [comment]
Duplicate of #391
