### ISSUE TITLE
Last login location

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#183]
Is there a setting in cmi that forces the players to spawn at spawn on login? When I login I login where I logged off. Is CMI controlling this?

**Comment by RustyDagger** [comment]
CMI saves the location when you logout, and its vanilla that puts you back at the same location, However CMI lets you move the players location while they are offline And it will make them login where ever you set.

I had a bit of a look in the config and there are options to set a spawn point for respawn, /spawn and first join, But not for every join so maybe that could be a feature added for those that want it.

**Comment by HomeLandingsDE** [comment]
you can use eventCommands

joinServer:
  Use: true
  List:
- cmi spawn [playerName]
quitServer:
  Use: true
  List:
- cmi spawn [playerName]

**Comment by 0xC1A551C** [comment]
This works
