### ISSUE TITLE
Enchanting limit not working

### ISSUE THREAD

**Issue by Woggys** [Zrips/CMI#1835]
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```
"10 is higher than the maximum level of 5 supported by that enchantment."
This occurs when i try to do efficiency, the error occurs even if the limit is enabled/disabled.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

Enchanting:
  enchantLimits:
    # By disabling this, no limitation to enchanting will be applied
    Enabled: false
    MaxLevel:
      protection_fire: 4
      damage_all: 10
      arrow_fire: 1
      water_worker: 1
      arrow_knockback: 2
      loyalty: 3
      depth_strider: 3
      vanishing_curse: 1
      durability: 3
      knockback: 2
      luck: 3
      binding_curse: 1
      loot_bonus_blocks: 3
      protection_environmental: 4
      dig_speed: 10
      mending: 1
      frost_walker: 2
      lure: 3
      loot_bonus_mobs: 3
      damage_undead: 5
      fire_aspect: 2
      channeling: 1
      sweeping_edge: 3
      thorns: 3
      oxygen: 3
      riptide: 3
      silk_touch: 1
      impaling: 5
      protection_fall: 4
      arrow_damage: 5
      arrow_infinite: 1
---

**Cmi Version (using`/cmi version`):** "This is the final build for 1.13.2"

**Server Type (Spigot/Paperspigot/etc): Spigot

**Server Version (using `/ver`):1.13.2

**Relevant plugins (Delete if this isn't needed): CMI

**Comment by Zrips** [comment]
As comments for this feature indicates, it's only for **/enchant** command. If server limits and prevents you from enchanting items over defined vanilla limits, then it will be limited to that. Other then this, you can set PermissionLevelLimit to use permission based limits
