### ISSUE TITLE
[Bug]No afk kick for players who /sit on something

### ISSUE THREAD

**Issue by DonSensiLeone** [Zrips/CMI#1836]
Players who should be kicked for being afk can avoid it by sitting on a chair

**Cmi Version (using`/cmi version`): 8.6.4.0

**Server Type (Spigot/Paperspigot/etc):** Paper 624

**Server Version (using `/ver`):** 1.13.2

Edit : i got one more player who was afk just standing still and having in second hand a shield (if it has any link...and no change made in config.yml regarding to afk ), he was afk but never triggered the kick command

**Comment by Zrips** [comment]
Cant really confirm this one as it seems to be working correctly at this point. If you still having this issue, please let me know.
