### ISSUE TITLE
Problem with the Skin Tool

### ISSUE THREAD

**Issue by TheUnrealDoom** [Zrips/CMI#1838]
We got a problem with the Skin-Tool from CMI. After someone change his skin, it wont load on the Server. So other people can't see the new skin. With the manually skin update (/skin update [Name], it wont update. 
---

*CMI version 8.6.4.0** 

**Paperspigot:** 

**git-Paper-624 (MC: 1.13.2)**

**Comment by TheoRetisch1** [comment]
I'm facing the same problem. Players can no longer change their skins when the CMI skin module is enabled. Even after a restart the skin will not be updated.

**Comment by TheoRetisch1** [comment]
In version 8.6.4.1 the problem still exists.
Skins are not updated automatically. 
If it is done manually with the update command, other players will see the new skin. The player with the new skin will only see his new skin after a relog.

**Comment by TheoRetisch1** [comment]
The bug also occurs in version 8.6.5.1. Skins do not update automatically. In addition, the whole process is much slower than the players are used to from Mojang. Normally the new skin is available immediately, but with the /skin update command it is often only visible 30-60 minutes after the change.

**Comment by Zrips** [comment]
Will be adding some auto update functions to grab new skin information from Mojang servers.
