### ISSUE TITLE
Please let CMI join the Vault API

### ISSUE THREAD

**Issue by BackWheel** [Zrips/CMI#1839]
When I used the bentobox plugin, the plugin couldn't find support for the economic plugin. I asked the author of the Bentobox plugin that this was caused by CMI's lack of a built-in Vault API, so I hope to inject the Vault API into CMI.

**Comment by the456gamer** [comment]
is CMI economy enabled and are you using CMI's vault build (or injector)?

**Comment by Zrips** [comment]
@BackWheel You can use recompiled Vault or Vault injector, both can be found at plugins page. First option requires you to have less plugins, but if you want to have official Vault working with CMI, then injector is good way to go too. Other then this, i need to fork Vault and try to push out Vault update which would directly support CMI
