### ISSUE TITLE
CMI Economy not being recognised

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#184]
AcidIsland doesn't recognise CMI's Economy, even with CMIEInjector installed.
[05:37:53 WARN]: [AcidIsland] Could not set up economy! - Running without an economy. 

ASkyblock might also have this problem (haven't tested to see).

**Comment by MCTyler** [comment]
I think it would be best to have Tastybento Link up with CMI's API like I have requested with MobHunter.

**Comment by TheWranger** [comment]
I assumed since it was economy-related that it would fall under Zrip's job to fix.
"If you have issues with economy not being recognised by plugin, please inform with plugins name."
I'll open an issue with Tastybento and see what comes out of it.

**Comment by MCTyler** [comment]
It might be but I would like to see a more broad acceptance to CMI's Economy with all plugins like Essentials has achieved. Not sure where this should start.

**Comment by tastybento** [comment]
I just tap into Vault for economy support. I assume Vault is still accepting Pull Requests, in which case, submit one to them to have it include CMI.

**Comment by LogGits** [comment]
Yeah... I thought the same thing... https://github.com/MilkBowl/Vault/issues/713

**Comment by tastybento** [comment]
Right now, the error is thrown if econ is null:

```
    public static boolean setupEconomy() {
        RegisteredServiceProvider<Economy> economyProvider = ASkyBlock.getPlugin().getServer().getServicesManager()
                .getRegistration(net.milkbowl.vault.economy.Economy.class);
        if (economyProvider != null) {
            econ = economyProvider.getProvider();
        }
        return econ != null;
    }
```

I don't know how CMI intercepts calls to Vault, but maybe it's the getProvider() part? Is there any other approach to use in my plugin that would make it more compatible?

**Comment by Zrips** [comment]
Ok, will have to work on Vault fort to have normal compatibility with other plugins. But for now, issue is that AcidIsland loads after Vault and before CMIInjector, that results in "missing" economy system. No clue why they are loading plugins on STARTUP instead of normal way... Anyhow, simply adding AcidIsland int loadbefore for CMIInjector, solves issue and will push new version today.

**Comment by Zrips** [comment]
Recompiled Vault with full CMI economy support and you can find link on plugins page on top. So this one should be solved now for good.
