### ISSUE TITLE
Further DiscordSRV support

### ISSUE THREAD

**Issue by hamcoremusic** [Zrips/CMI#1841]
**Description of issue or feature request:**

I was wondering if it is possible to get DiscordSRV working with ClickHoverMessages enabled? I really want to take advantage of that and the [item] placeholder but also don't want to give up DiscordSRV. Please let me know of this is possible or not!

**Comment by TheWranger** [comment]
It's been broken for awhile now, https://github.com/Zrips/CMI/issues/391

**Comment by hamcoremusic** [comment]
It's not broken, it's just incompatible. I already know it doesn't work that's why I am REQUESTING to try and get it to work.
