### ISSUE TITLE
Command Cooldown resets (indefinitely)

### ISSUE THREAD

**Issue by CeIebrimbor** [Zrips/CMI#1843]
**Description of issue or feature request:**
When setting up command cooldowns in config.yml, most work fine. The /home command is an exception. The cooldown time continuously resets and never lets players run the command.

**Replicate:** Set cooldowns for /spawn and /home (I did 30 seconds). Run home and spawn back and forth. Spawn's cooldown will countdown, but home's cooldown keeps resetting back.

Unrelated to Bug:
Also, the cooldown should not reset if the warmup was cancelled due to movement/damage. Cooldown should only start if the command succeeds.

**CONFIG SECTION:**
```
Cooldowns:
permission node
  # Always use full command name and not its alias
  Enabled: true
  List:
  - cmi home:30
  - cmi spawn:30
  - cmi top:30

NOTE: I even tried cmi home :30 thinking it would be similar to the extra space needed for warmups, but no dice.
```

**Cmi Version (using`/cmi version`):** 8.6.4.0 

**Server Type (Spigot/Paperspigot/etc):** Paper 1.14.1 (build 50)

**Server Version (using `/ver`):** Paper version git-Paper-50 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

**Comment by impmallet** [comment]
I can confirm that this is still broken. I submitted a bug report for this months ago and it went ignored.

**Comment by Zrips** [comment]
Doing some work on this one. New and improved system should come out with today's update.
