### ISSUE TITLE
/cmi ic Problem

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1845]
CraftBukkit version git-Spigot-03bd4b0-fcb9f90 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

CMI:8.6.4.0

I can use /cmi ic 
no more commands from other plugins on signs or buttons. Which I think is more than a pity.
Can you fix it soon? because I urgently need the function. Otherwise a foreign plugin must use itself again to do that. what would be more than a pity

**Comment by 0xC1A551C** [comment]
It works for me? Upgrade your spigot version lol.

**Comment by Blueeyestar** [comment]
also for commands of foreign plugins??
