### ISSUE TITLE
[Feature] Enhance /cmi titlemsg with fadeIn, stay and fadeOut

### ISSUE THREAD

**Issue by Drc-DEV** [Zrips/CMI#1846]
The current command does **NOT** support setting **fadeIn**, **stay**, **fadeOut**. It is not that useful without these parameters, or **at least the "stay"** one, because fadeIn and fadeOut can easily be set to a default value of 5 ticks.

Could you please add these to the command? 

Example:
>  /cmi titlemsg [playerName/all] [stay] [fadeIn,fadeOut] [title %subtitle% subtitle]

**Comment by Zrips** [comment]
/cmi titlemsg [playerName/all] [title \n subtitle] (-in:[ticks]) (-out:[ticks]) (-keep:[ticks])
might not work on older server versions as this was added in latest minecraft servers only
