### ISSUE TITLE
bossbar hp

### ISSUE THREAD

**Issue by jbbpt** [Zrips/CMI#1851]
**Hello good afternoon my cmi works fine, but there is a problem in the bossbar when I battle with the mob does not disappear the percentage and the red heart as I do to correct thanks:**

**Comment by Zrips** [comment]
Could you provide a picture with example of whats going on?

**Comment by jbbpt** [comment]
![2019-05-29_22 21 56](https://user-images.githubusercontent.com/46502240/58592480-713ff900-8260-11e9-962e-0855035810c1.png)

**Comment by jbbpt** [comment]
![2019-05-29_23 03 12](https://user-images.githubusercontent.com/46502240/58594627-0bef0680-8266-11e9-8407-4b81ae92f453.png)
 dont desapiar only if i restart server.

**Comment by Zrips** [comment]
This is not a CMI feature, so issue is with another plugin you have which creates those fake armor stands all over the place

**Comment by jbbpt** [comment]
ok thank you
