### ISSUE TITLE
Home realblock not working!

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#1852]
The pickrealblock setting does not seem to work, and still stays as a wool color that changes constantly.

  # When set to true home icons in GUI will try to pick real blocks from that location for easy way to see which is which
  # When set to false, then random wool block will be used
  PickRealBlock: true

**Cmi Version (using`/cmi version`):** 8.6.4.0

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  1.14.2

**Comment by Zrips** [comment]
This was disabled due to issue with 1.14.2 server not being able to handle block type checks for unloaded chunks in reasonable times. It might be reenabled in future updates tho, if they fix that issue at their end.
