### ISSUE TITLE
Home Errors

### ISSUE THREAD

**Issue by kaniesha** [Zrips/CMI#1853]
**Description of issue:**
CMI throws up errors after people use their homes, often giving internal service errors and not working at all.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/89Hfc0kL

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.4.0

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
git-Spigot-093165d-ba575a5  ver 1.14.2-R0.1-SNAPSHOT

**Relevant plugins (Delete if this isn't needed):**
Multiverse https://ci.onarandombox.com/job/Multiverse-Core/

**Comment by Zrips** [comment]
Issue with minecraft version it self, as it seems. Should be in working condition now.
