### ISSUE TITLE
/home works without permissions when specifying home name

### ISSUE THREAD

**Issue by impmallet** [Zrips/CMI#1854]
Players are able to run the /home command if they specify the name of the home after the command. Example, a player could set their home of "Home" and then run /home Home and the command will also work, even if the player does not have the correct permissions to use /home. This also allows players to bypass any cooldown timers for /home (not that cool downs work properly for /home to begin with,  you should check the other bug report I submitted for this...)

Also, /home works even though I do not have an alias set for it in the customer alias config and it is disabled in the standard alias config.

I debugged the command usage using Luck Perms and I can confirm that it is calling the cmi plugin for this command as when the player issues /home it denies the command due to not having the permission node cmi.command.home.

CMI Version: 8.6.4.0

Server type: Spigot

Server Version: git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) This is a final build for 1.13.2.

**Comment by Zrips** [comment]
if they cant use /home then they cant use /home [homeName] plugin doesn't prioritize it by how many variables you have entered, it will check if you have base permission node before doing anything else.
There will be some changes related to command warmup/cooldown with next release, so check that one out, it could solve your issues you are having now.
And for alias, you can always enable one and /cmi reload is enough, but to properly disable it you will need to restart server. Then double check if you dont have customAlias set for home command which creates all this mess you are having.
