### ISSUE TITLE
Item with colored names reset

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1855]
CraftBukkit version git-Spigot-01d0f04-455023c (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

Cmi: 8.6.4.0

We have recently had the problem that items that have become unbenannz in the anvil are colored so they reset.
Example:

**&4this is a test&funny**

This is reset again in:

**?4this is a test?lfunny**

**Comment by Zrips** [comment]
This will be fixed with next build
