### ISSUE TITLE
[senderName]

### ISSUE THREAD

**Issue by kforbro** [Zrips/CMI#1856]
[senderName] doesnt work in broadcast command.

  broadcast:
    help:
      info: '&fSends special message to all players'
      args: (.) [message] (-w:[worldName,worldName])
      explanation:
      - If message starts with . then clean message will be shown
      - Worlds can be defined to broadcast messages only in those worlds
    info:
      format: '&9&l › &cОБЪЯВЛЕНИЕ: &f[message] &7(отправил: [senderName])'

**Comment by Zrips** [comment]
Will get fixed with next version
