### ISSUE TITLE
Alias config wont work!!

### ISSUE THREAD

**Issue by Chilliann** [Zrips/CMI#1860]
Ive set a few things to True so i dont have to use /cmi sethome ect so its /sethome but none of what ive set to True is working at all just says no command. Can post Alias.yml if needed but all ive done is set a few to True and reloaded the server after saving. Ive also given permission but doesnt work as OP either.. any ideas please?

**Comment by Zrips** [comment]
Show me your alias.yml file

**Comment by Chilliann** [comment]
https://pastebin.com/dZYGY43T
Im running latest CMI version and 1.13.2 spigot server

**Comment by the456gamer** [comment]
Use lowercase true, like the default false

**Comment by Chilliann** [comment]
Yeah I first started with lower case, then noticed in the info part it was a capital T and tried that, still didnt work

**Comment by the456gamer** [comment]
Is there any errors in console

**Comment by Zrips** [comment]
@Chilliann Why do you have 
```
#0 .
All aliases to used with this plugin. In example original command for going back to spawn is /cmi spawn
```
as a top line? 
Change it back to 
```
# All aliases to used with this plugin. In example original command for going back to spawn is /cmi spawn
```
or simply delete entire alias.yml and let it regenerate properly. And you should get big glaring error message when you are trying to start server or reload CMI with file like this one. So suggestion would be to always look at your console for any error messages and include them into report about issue you are having.

**Comment by Chilliann** [comment]
Thankyou! Fixed and working. Sorry I didnt notice that. Quick replies!
