### ISSUE TITLE
8.6.4.1 Unhandled exception executing command 'cmi' in plugin CMI

### ISSUE THREAD

**Issue by kaniesha** [Zrips/CMI#1862]
**Description of issue:**
Console showed error after player used /back
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://gist.github.com/kaniesha/d8b7ab35b9cda67eaf722cf9501e2295

```
---

**Cmi Version (using`/cmi version`):** 
8.6.4.1

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
git-Spigot-093165d-ba575a5  ver 1.14.2-R0.1-SNAPSHOT

**Comment by kaniesha** [comment]
Also, going through logs again and noticed the same thing as this: https://github.com/Zrips/CMI/issues/1859#issuecomment-497744232

**Comment by kaniesha** [comment]
Unhandled exception executing command 'cmi' in plugin CMI v8.6.4.2

https://gist.github.com/kaniesha/cb19b4786e45b68e5bb6b977b7146097

**Comment by Zrips** [comment]
Should no longer happen with newest minecraft version
