### ISSUE TITLE
Holograms are flickery

### ISSUE THREAD

**Issue by MisterZet** [Zrips/CMI#1865]
So I use every 4 seconds "holo#refresh" on the holograms I've created, and every time I refresh it flickers, I'm hoping that this can be fixed as soon as possible.

What I've noticed that you on "#refresh" hide the hologram till you update, what's the point of that?

**Comment by digitalcrowd** [comment]
I have noticed weird color changes too. Console is spamming color recipes as invalid on anything that involves CMI and text color changes in game. I made comment of this in passing and output in issue that I created recently.

**Comment by 0xC1A551C** [comment]
@MisterZet can you elaborate on how or where you use holo#refresh? CMI has built in hologram refreshing.

**Comment by Zrips** [comment]
@MisterZet 
**refresh()** does complete hologram refresh, which means its recalculating line position, line count, page count and so on. While update() will update lines without hiding them. This will not add or remove any lines while doing that. So depending on your need use one or another command. Some extra re-code of hologram handling would be needed to avoid flickering while changing line count
