### ISSUE TITLE
dback not accounted for back blacklist

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#1867]
**Description of issue:**
Player can still use /dback to go back to the world they died in. /dback should essentially have the same function for blacklisting as /back
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Snippet of config.yml for back blacklist
```yaml
    # List of worlds to whichones player can't go back with /back command
    BackBlackList:
    - event
    - dungeon
    - peaceful
```

BackBlackList should also account for /dback and not only /back

---

**Cmi Version (using`/cmi version`):** 8.6.4.1

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.13.2

**Comment by Bayminkk** [comment]
Why my  BackBlackList: word  doesnt work? But you can...

**Comment by Yukyxy** [comment]
Hello i need also that this bug will be fix @Zrips please

**Comment by JokerLiuPro** [comment]
Just give up, he ignore all the report about that issue
https://github.com/Zrips/CMI/issues/1290

**Comment by Zrips** [comment]
That black list was made for /back command only, so in general its not a bug. But will add support for /dback and we can use same blacklist. Next version.
