### ISSUE TITLE
/homes starts cooldown for /home

### ISSUE THREAD

**Issue by CeIebrimbor** [Zrips/CMI#1869]
**Description of issue:**
This comes after the last CMI update that addressed #1843. But now the use of /homes and /home when you have multiple homes (which opens GUI or prints to chat) counts as a successful used of /home and starts the cooldown.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
This creates the issue described above.
Cooldowns:
Enabled: true
List:
- cmi home:180

This makes cooldowns break for home.
Cooldowns:
Enabled: true
List:
- cmi home :180
```

---

**Cmi Version (using`/cmi version`):** 8.6.4.1

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper 1.14.2 build 58

**Comment by impmallet** [comment]
Confirmed. Also /cmi home is still resetting cooldown infinitely. Issue #1843 is NOT fixed.

**Comment by impmallet** [comment]
Also my players can still do /home (home name) and bypass all cooldown. Can you PLEASE finally fix this. It's making your plugin unusable.

**Comment by CeIebrimbor** [comment]
Still an issue. Not sure why attempts were made to remedy right after report, then after one failure attempt this issue is just kicked to the curb 😞

**Comment by impmallet** [comment]
> Still an issue. Not sure why attempts were made to remedy right after report, then after one failure attempt this issue is just kicked to the curb

I've been struggling with this feature for months. I don't think the dev really cares about it much.

**Comment by impmallet** [comment]
Still an ongoing issue.

**Comment by Olexorus** [comment]
Same problem here, would be awesome if it could be fixed

**Comment by Zrips** [comment]
This should be working correctly now
