### ISSUE TITLE
BUG: Console being spammed

### ISSUE THREAD

**Issue by gerardvanschip** [Zrips/CMI#1871]
Noticed high CPU usage so checked console and noticed this one repeating message.
[03:03:47] [Server thread/INFO]: Usage: /tp [playerName] (playerName)
[03:03:47] [Server thread/INFO]: * Teleports to player's location

They come every second and continue all day, well, till the log file gets too big and the server goes down.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** \
8.6.4.1

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
58

**Relevant plugins (Delete if this isn't needed):**

**Comment by gerardvanschip** [comment]
Installed 8.6.4.0 to see if that stopped it, nope, still doing it. My log file runs up to 500kb in minutes.

**Comment by 0xC1A551C** [comment]
I dont have this problem. Seems like a issue with your server as if something or someone kept running /tp without the extra variables

**Comment by the456gamer** [comment]
To add:
Someone or something in console.

**Comment by the456gamer** [comment]
What plugins do you have installed.

**Comment by Zrips** [comment]
Without error log cant really help out. but it should be working correctly with latest build.
