### ISSUE TITLE
heal all ignores permissions cmi.command.heal.others

### ISSUE THREAD

**Issue by thunderlight411** [Zrips/CMI#1873]
**Description of issue:**

Players without the permissions cmi.command.heal.others can still use the command /cmi heal all

When using /cmi heal [otherplayer] the player will receve a message that they dont have any permissions to do that

**Cmi Version (using`/cmi version`):** 
CMI version 8.6.4.1

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
git-paper-622(MC1.13.2)

**Comment by Zrips** [comment]
Got fixed
