### ISSUE TITLE
/cmi colors broken [1.14.2]

### ISSUE THREAD

**Issue by bartyrealms** [Zrips/CMI#1874]
**Description of issue:**
Colors does not display color codes anymore, only a couple of format codes.
![image](https://user-images.githubusercontent.com/42015460/58766185-96c35000-8549-11e9-94de-0a42f8620df9.png)

**Cmi Version (using`/cmi version`):** 
8.6.4.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-58 1.14.2

**Comment by digitalcrowd** [comment]
I can't duplicate this bug at least in a later release of Paper.

<img width="622" alt="Screen Shot 2019-06-03 at 5 53 37 AM" src="https://user-images.githubusercontent.com/337332/58796870-0d9d2f00-85c4-11e9-91c9-581ce0373d41.png">

**Comment by Zrips** [comment]
This seems to be issue with a client not processing correctly text if it contains &k variable on 1.14+ servers. Tho latest minecraft version seems to have fixed it.
