### ISSUE TITLE
Player mute doesn't persist after server restart

### ISSUE THREAD

**Issue by Lunna123** [Zrips/CMI#1875]
**Description of issue:**
If a player is muted and the server is restarted, the mute does not persist on server restart and the player is unmuted/can chat again once the server is restarted. It would be great if mutes could persist on server restart!

---

**Cmi Version (using`/cmi version`):** 8.6.4.1

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Paper-530

**Comment by Zrips** [comment]
With next update this will be fixed
