### ISSUE TITLE
/i spawner:Panda | Does not work

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#1878]
All other none 1.14 mob spawners are working but I cant use the command `/i spawner:{Panada/Fox/Ravager}`.

Getting this error:
https://pastebin.com/kz4gC6JT

CMI: 8.6.4.1
Spigot: 1.14.2

**Comment by Zrips** [comment]
Will be fixed with next build

**Comment by SirGoldman-git** [comment]
Resolved, you're a god, thank you!
