### ISSUE TITLE
Towny Baltop

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#188]
Still shows towns in the /baltop command. Thanks

**Comment by HomeLandingsDE** [comment]
just use Alias.yml 

set /baltop from CMI to flase

**Comment by 0xC1A551C** [comment]
I want baltop. it should work correctly

**Comment by LogGits** [comment]
Can we please get a screenshot of this along with a screenshot of the output of `/cmi version`, `/ver` and the version of towny that you are using. I can try and reproduce this if I have the necessary information 👍

**Comment by 0xC1A551C** [comment]
https://i.imgur.com/INvyKdg.png

Latest version of towny from palmergames. town_badlands is not a user.

**Comment by LogGits** [comment]
What version of spigot/paper are u using?

**Comment by 0xC1A551C** [comment]
The latest. Affects all versions within 1.12.2 at least to my knowledge. I have used tacospigot, spigot, and paperspigot. Shows it on every one.

**Comment by LogGits** [comment]
Zrips has added a filter that will block towns from appearing in the baltop, in the next update.
