### ISSUE TITLE
Glowing color

### ISSUE THREAD

**Issue by DampfWaffel** [Zrips/CMI#1880]
Hey,
the Glowing is working, but i cant change the colors. Its always white.
Is there some option in the config or something else?

Server-Version: Paper git-65

CMI: latest 8.6.4.2

Related Plugins: 
NameTagEdit-4.4.2
Citizens-2.0.25-b1701
LiteBoard-5.2.4
ProtocolLib-4.5.0-SNAPSHOT
Vault-1.7.2-b107 with CMIE-Injector-1.0.2.1

**Comment by Zrips** [comment]
It can be issue with compatibility with another plugin that uses teams to change specific information related to player, this could be nameTagEdit or liteBoard plugins. At this point there is no simple solution for it.
