### ISSUE TITLE
Glow Color

### ISSUE THREAD

**Issue by Woggys** [Zrips/CMI#1885]
/glow (name) (color) doesn't work. Only gives me yellow color
---

**Cmi Version (using`/cmi version`):** Final Build 1.13.2

**Server Type Spigot:** 

**Server Version (1.13.2):**

**Comment by mrfloris** [comment]
`/cmi glow (playerName) [true/false/color] (-s) - Sets players glow. Example: /glow Zrips red Permissions: cmi.command.glow.[color] - allows to set particular glow color`

Does it work if the player has the right permissions added and you use /cmi glow gui (and then say pick red or blue) or is it always yellow?

**Comment by Woggys** [comment]
Its always yellow

**Comment by 0xC1A551C** [comment]
same mine is always red for some reason

**Comment by splops** [comment]
Do you have namemanager/nametagedit? I think that plugins uses scoreboard data who handles glow color.

https://www.spigotmc.org/threads/glowing-entities-change-colour.128854/
Not the best source tbh.

**Comment by Zrips** [comment]
Glow color is dependent on player scoreboard team, which by itself controls bunch of other things and having couple plugins using scoreboard will result in something not working as it should. There is no real good solution at this point as scoreboard team system is... broken... to put it in simple terms. Mojang has to come up with better way to control such basic things as player glow color or name tags.
