### ISSUE TITLE
 Duplicated alias found which could cause some strange (harmless) behavior:

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1886]
**I recently got this message in the console. What can I do about it?
I had never had that before.**

04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: passwordcommand
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: serverstop
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: serverstop2
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: speedstop
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: speedstop2
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: hilfe
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: scheck
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: w
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: pm
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: 24
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: usermarkt
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: 12
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: Bank
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: 1
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: Farmwelt
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: Nether
04.06 06:43:14 [Server] Server thread/INFO [CMI] Duplicated alias found which could cause some strange (harmless) behavior: 2

**Comment by Blueeyestar** [comment]
###  As you can see, CMI has doubled it itself with other names! Is that the way it should be?

hilfe:
    Cmds:
    - cmi helpop $1-
  scheck:
    Cmds:
    - cmi cheque $1-
  w:
    Cmds:
    - cmi msg $1-
  pm:
    Cmds:
    - cmi msg $1-
  '24':
    Cmds:
    - st play Bank
  usermarkt:
    Cmds:
    - st play Usermarkt
  '12':
    Cmds:
    - st play Usermarkt
  Bank:
    Cmds:
    - st play Bank
  '1':
    Cmds:
    - st play Farmwelt
  Farmwelt:
    Cmds:
    - st play Farmwelt
  Nether:
    Cmds:
    - st play Nether
  '2':
    Cmds:
    - st play Nether
  '23':
    Cmds:
    - st play Anundverkauf
  anundverkauf:
    Cmds:
    - st play Anundverkauf
  '3':
    Cmds:
    - st play End
  end:
    Cmds:
    - st play End
  '8':
    Cmds:
    - st play Spawnmarkt
  Spawnmarkt:
    Cmds:
    - st play Spawnmarkt
  Zaubertisch:
    Cmds:
    - st play Zaubertisch
  '17':
    Cmds:
    - st play Zaubertisch

**Comment by Zrips** [comment]
Its more or less debug message which is as it says, harmless. Will hide it, as it seems that people get confused seeing it. In general this one appears when you do /cmi reload, this will not appear on regular sever start/restart.
