### ISSUE TITLE
Could not pass event InventoryClickEvent to CMI v8.6.4.2

### ISSUE THREAD

**Issue by kaniesha** [Zrips/CMI#1888]
**Description of issue:**
After a player used the /dispose command, this error popped up in console.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
Could not pass event InventoryClickEvent to CMI v8.6.4.2
https://gist.github.com/kaniesha/2db2d363fb24c3544904eb82d38e1cc6

---

**Cmi Version (using`/cmi version`):** 
8.6.4.2

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
git-Spigot-baafee9-043d31d

**Comment by Zrips** [comment]
Should be fixed with next build
