### ISSUE TITLE
Error When Player Join

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#1889]
**Description of issue:**

Errors

**ERROR (DELETE IF YOU HAVE NO ERROR):**
05.06 11:30:44 [Server] INFO UUID of player Sean_Lo is ca2f962f-6fb2-4c9d-9823-e4dba42830d6
05.06 11:30:44 [Server] ERROR Could not pass event PlayerJoinEvent to CMI v8.6.4.0
05.06 11:30:44 [Server] INFO java.lang.IllegalArgumentException: location.world
05.06 11:30:44 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.teleport(CraftPlayer.java:732) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.entity.CraftEntity.teleport(CraftEntity.java:489) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at com.Zrips.CMI.AllListeners.PlayerListeners.onPlayerFirstJoin(PlayerListeners.java:766) ~[?:?]
05.06 11:30:44 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor588.execute(Unknown Source) ~[?:?]
05.06 11:30:44 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:169) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:255) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1201) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-65]
05.06 11:30:44 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Cmi Version (using`/cmi version`):** 
8.6.4.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.14.2 paper-65

**Comment by Zrips** [comment]
Should be fixed with next build
