### ISSUE TITLE
Already connecting to server!

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#189]
When I run `/cmi server (name)` it says `Already connecting to server!` in red text. Is there any way to disable this, or edit the text to show in the action bar? I checked the locale files. Thanks.

**Comment by Zrips** [comment]
This is bungee or vanilla message, so cant really translate it.

**Comment by LogGits** [comment]
Closing this as it is related to bungee. I recommend downloading a packet filtering/modifying plugin to change this (ChatControl Pro could potentially do this with its packet filtering).
