### ISSUE TITLE
/cmi inv - Ender Chest view does not work.

### ISSUE THREAD

**Issue by Roper89** [Zrips/CMI#1890]
**/cmi inv** - **Ender Chest** view does not work.
if the player is **offline**, then when viewing Ender Chest our chest opens.
Spigot 1.14.2

We can see the contents of Ender Chest only when a player is **online**.

**Comment by mrfloris** [comment]
I've noticed in Spectator mode you can't click on the ender chest from cmi inv. but it works in creative mode. Could you perhaps check in 1.14.2 if that's perhaps the case, or do you mean it's completely stopped working, regardless of gamemode ?

**Comment by Zrips** [comment]
@Roper89 Does it result in same outcome whenn using /cmi ender [playerName] command? As this is exactly what it does. And what is the name of that player? As it could be related to funky name.

**Comment by Roper89** [comment]
@Zrips I tested on an older version, in the latest update this problem is not.

**Comment by Roper89** [comment]
@mrfloris I'm sorry, I noticed your question late.

**Comment by Roper89** [comment]
@Zrips The problem was due to the use of the plugin — [BetterEnderChest](https://www.spigotmc.org/resources/betterenderchest.2073/)

Please add the possibility of increasing slots for Ender Chest and inventory for premium players.
