### ISSUE TITLE
EXP Amount Way High w /invlist <player>

### ISSUE THREAD

**Issue by CupcakeCrush** [Zrips/CMI#1891]
**Description of issue:** When restoring an inventory that is saved on a Death Event, the amount of exp is calculated incorrectly. When using /cmi invlist <player>, and then loading that inve to the player with the GUI, they end up with SUBSTANTIALLY higher exp than they died with.

**Cmi Version (using`/cmi version`):** CMI 8.6.4.0

**Server Type (Spigot/Paperspigot/etc):** Latest Paper #629

**Comment by Zrips** [comment]
Can you give me example? From how much to how much does exp changed?

**Comment by Zrips** [comment]
Ok, nwm, found some small issue with exp calculation. Should be ok with next build.
