### ISSUE TITLE
Permission error.

### ISSUE THREAD

**Issue by Roper89** [Zrips/CMI#1893]
Permission `cmi.command.gm.[gametype]`  - does not work
It works **only** - `cmi.command.gm`

I want to use the command - `/cmi gm [nickname] [0/1/2/3 survival/creative/adventure/spectator]` 
I add permission - `cmi.command.gm.survival`
But if use the command - `/cmi gm survival`  I get a warning that I do not have permission - **cmi.command.gm**

**Comment by Zrips** [comment]
cmi.command.gm is a base permission node for you to use this command, everything else is optional and depends of what you want, but will need that base permission node. Test next version, it will contain some small changes related to gm command
