### ISSUE TITLE
[Halp!] How's your head?

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#1895]
**Description of issue:**
I'm 98% sure this **isn't** anything to do with CMI, probably my network settings because I'm a hosting n00b, but I can do about 7 player heads with the /cmi head command without issue, then all of a sudden the next one I do there's a massive lag spike, errors flying around, people sometimes time out - it's not pretty. It's been doing this the last 3 or 4 nights.

#BlameMojang? Or anyone have any idea what's going on? Any suggestions would be massively appreciated.

**ERROR:**
https://gist.github.com/mercurialmusic/bfb49b2346b62af7a07ddd0cbe438b7b

**Cmi Version:** 
8.6.4.2 (I know I'm behind)
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-f09662d-3697519 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by smmmadden** [comment]
I'd say it might be the build you're on as it is quite a few builds behind (174 to be exact) according to the version checker: https://spigot.club/checker#git-Spigot-f09662d-3697519 so that isn't helping the use case.  It could be a KB in CMI?, but this would help rule out what it is not.

Take a look to see if any of those issues look like what you're seeing and upgrade to a more recent version.

**Comment by mercurialmusic** [comment]
Thanks. I haven't been interested in taking the 1.14.x plunge yet, so I thought I was sticking with one of the last 1.13.2 builds for now (unless I'm totally misreading how those work), but still a good point.

**Comment by Zrips** [comment]
Well from error log it looks more like issue with limitations we have while trying to retrieve data from Mojang server. In general i cant really do anything about it as this is Bukkit code itself causing this issue and not CMI. Simply try to use this command in longer intervals.

**Comment by mercurialmusic** [comment]
That's also what I was thinking, but then I ran a bunch of updates in Ubuntu and it magically went away. Came here to close it and you beat me to it. :) Sorry for the ticket spam -- I know you don't get enough of these and always want more to go through!
