### ISSUE TITLE
CMI Causes server to crash

### ISSUE THREAD

**Issue by ghost** [Zrips/CMI#1899]
**Description of issue:**
---
CMI creates teams to scoreboard.dat, which somehow has memory leak and causes server to crash after a few hours.
**Cmi Version (using`/cmi version`):** 
[Sat, 8. Jun 2019 12:03:00 UTC INFO] CMI plugin version: 8.6.4.4
[Sat, 8. Jun 2019 12:03:00 UTC INFO] Server version: Spigot 1.13.2-R0.1-SNAPSHOT
[Sat, 8. Jun 2019 12:03:00 UTC INFO] Vault version: 1.6.11(+)

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Should no longer happen as now we are cleaning out scoreboard file from unneeded information.
