### ISSUE TITLE
QUESTION: %rand/%

### ISSUE THREAD

**Issue by GrimPod** [Zrips/CMI#190]
Quick question about the random specialised command 
What im wanting is to use the rand in warp command on in interactive command/block
EG - A sign that when clicked runs 
     - fromConsole! warp Entry%rand/1-4% [playerName]
so when clicked it teleports them to either
-Entry1
-Entry2
-Entry3
-Entry4
it currently failing saying that its not a valid warp name
(TESTED BELOW) Its not resolving the random number
and litterally trying to teleport me to "Entry%rand/1-4%"
![teletest](https://user-images.githubusercontent.com/12431998/38172513-c2a9d850-35f0-11e8-8e41-3825c5827a3c.jpg)

**Comment by LogGits** [comment]
I do like the idea of a random number placeholder, however, it should be setup a little differently. Maybe %random:1-10% for a random number between 1 and 10. Great suggestion 👍

**Comment by GrimPod** [comment]
Wasnt exactly a feature request i was reading the [Specialised Commands](https://www.spigotmc.org/wiki/cmi-specialized-commands/) page on the wiki and sawL

"[randomPlayer] placeholder can be used to get random online player name who doesn't have cmi.scheduler.exclude permission node. This can be used to give rewards for random players on particular time. In example: cmi give [randomPlayer] diamond %rand/1-5% will give random amount from 1 to 5 diamonds to random online player"

And figured it was a placeholder that would work anywhere, but only seems to work in the give command

**Comment by LogGits** [comment]
Yeah those placeholders were only for the give command. However, @Zrips has added this in the next update. It will support these placeholder for all uses. Its more of an enhancement but oh well xD
