### ISSUE TITLE
StopPlayTime = true resets the playtime

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#1900]
Setting the option "StopPlayTime" from false to true resets the entire previously collected playtime. 
The playtime is not set to zero, but to a much lower level. I guess it's the time a player has played since CMI has been running on the server. Anyway, it is no longer his actual and in many cases due to a conversion manually set playingtime.

CMI: 8.6.4.4
playtime config: https://pastebin.com/MwjTNL86
Paper 1.13.2 - 628

**Comment by TheoRetisch1** [comment]
The error still occurs, but rather randomly = not with all users. If you set StopPlayTime from false to true the playtime of some players will be set to a lower level as soon as they go afk. The playtime of almost all players was set manually before this option was changed, so it does not match the time from the player file. Is there anything else I can do to analyze the cause of the problem?   

CMI 8.6.75
Paper - 638

**Comment by TheoRetisch1** [comment]
Confirmed for version 8.6.14.0!

**Comment by Zrips** [comment]
Do you take playtime from stats folder or player data file? Basically what do you have set for **PlayTimeFromStats** in config file

**Comment by TheoRetisch1** [comment]
I set PlayTimeFromStats to false, so I use the CMI user data file. 
However, there seems to be a difference between the user data file and the playtime stored in the database?
I have adjusted a lot of playtimes via command before I tried to change the StopPlayTime to true.

**Comment by Zrips** [comment]
Minecraft saves player playtime in 2 places, player data file and player statistics. They could be different depending on some criteria, this is why we have that option. In addition, there is built in CMI playtime tracker which tracks playtime by specific hours and can provide more detailed information. That one cant really be edited at this point.

**Comment by TheoRetisch1** [comment]
Mhh ok! I can't fully understand the problem then, but the problem still exists. I'll summarize again:

Currently I have the following settings:
```
StopPlayTime: false 
PlayTimeFromStats: false
```

Everything works fine, some playtimes were edited by command in the past.

Now I want to set `StopPlayTime` to `true`. As soon as a player goes afk his playtime will be reset to a value X in 70% of the cases, which is some hours, days or weeks below the previous value. The reset only happens once. After the one-time reset, the playtime continues to count normally. However, there are too many values to compensate the problem manually. 

I think for a solution the question first arises, why does it change the playtime after changing StopPlayTime to true? Is there anything else I can do to help? 

CMI 8.6.15.5
Paper 1.13.2 - 652
