### ISSUE TITLE
wrong kit cool down

### ISSUE THREAD

**Issue by zykool** [Zrips/CMI#1905]
**Description of issue:**

**I made a ”Kit” use cooldown set 7days .
But the reality is cooling time only a day.**
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```
vip4:
  Description:
  - '&rxxxxxx'
  CommandName: vip4
  Weight: 4
  Enabled: true
  DropOnGround: true
  ShowDespiteWeight: false
  Delay: 604800
  MaxUsages: -1
  Icon:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND
    amount: 4
  IconOff:
    ==: org.bukkit.inventory.ItemStack
    type: BARRIER
  Slot: 3
  Conditions:
  - cmi.kit.vipu4
  Group: vip4
---

**Cmi Version (using`/cmi version`):** 
cmi 8645
**Server Type (Spigot/Paperspigot/etc):** 
paper1.12.2
**Server Version (using `/ver`):** 
java8 centos6.5
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Cant really reproduce this one and more information would be nice. Like actual pictures from ingame to check what cooldown is been shown when you used a kit or before that.
