### ISSUE TITLE
When Player ID is a number

### ISSUE THREAD

**Issue by zykool** [Zrips/CMI#1906]
**Description of issue:**
When player ID is a number run the "maxhp" command is not working:

"CMI maxhp 112233 add 1"

(playername:112233)
---
**Cmi Version (using`/cmi version`):** 
cmi 8645
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
1.12.2

**Comment by Zrips** [comment]
Will fix it with next build
