### ISSUE TITLE
Error in Consol

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/CMI#1909]
**ERROR (DELETE IF YOU HAVE NO ERROR):**
09.06 19:06:41 [Server] Craft Scheduler Thread - 30/WARN [CMI] Plugin CMI v8.6.4.2 generated an exception while executing task 1881
09.06 19:06:41 [Server] INFO java.lang.NoSuchMethodError: com.sk89q.worldedit.util.Location.toVector()Lcom/sk89q/worldedit/Vector;
09.06 19:06:41 [Server] INFO at com.extendedclip.papi.expansion.worldguard.WorldGuardExpansion.getRegion(WorldGuardExpansion.java:96) ~[?:?]
09.06 19:06:41 [Server] INFO at com.extendedclip.papi.expansion.worldguard.WorldGuardExpansion.onRequest(WorldGuardExpansion.java:64) ~[?:?]
09.06 19:06:41 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?]
09.06 19:06:41 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:377) ~[?:?]
09.06 19:06:41 [Server] INFO at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:457) ~[?:?]
09.06 19:06:41 [Server] INFO at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:368) ~[?:?]
09.06 19:06:41 [Server] INFO at com.Zrips.CMI.Modules.TabList.TabListManager$6.run(TabListManager.java:744) ~[?:?]
09.06 19:06:41 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
09.06 19:06:41 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
09.06 19:06:41 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
09.06 19:06:41 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
09.06 19:06:41 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
09.06 19:07:03 [Server] Craft Scheduler Thread - 34/WARN [CMI] Plugin CMI v8.6.4.2 generated an exception while executing task 1885
09.06 19:07:03 [Server] INFO java.lang.NoSuchMethodError: com.sk89q.worldedit.util.Location.toVector()Lcom/sk89q/worldedit/Vector;
09.06 19:07:03 [Server] INFO at com.extendedclip.papi.expansion.worldguard.WorldGuardExpansion.getRegion(WorldGuardExpansion.java:96) ~[?:?]
09.06 19:07:03 [Server] INFO at com.extendedclip.papi.expansion.worldguard.WorldGuardExpansion.onRequest(WorldGuardExpansion.java:64) ~[?:?]
09.06 19:07:03 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?]
09.06 19:07:03 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:377) ~[?:?]
09.06 19:07:03 [Server] INFO at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:457) ~[?:?]
09.06 19:07:03 [Server] INFO at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:368) ~[?:?]
09.06 19:07:03 [Server] INFO at com.Zrips.CMI.Modules.TabList.TabListManager$6.run(TabListManager.java:744) ~[?:?]
09.06 19:07:03 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
09.06 19:07:03 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
09.06 19:07:03 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
09.06 19:07:03 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
09.06 19:07:03 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Cmi Version (using`/cmi version`): Latest

**Server Type (Spigot/Paperspigot/etc): latest Spigot

**Server Version (using `/ver`): 1.14.2

**Comment by Zrips** [comment]
This is not a CMI issue, its issue with PAPI using outdated WorldEdit API or you having wrong version which PAPI doesn't support. Report this bug to PAPI developer
