### ISSUE TITLE
Rank specific item is defined not work

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#191]
If an block is specified in StatsRequirements, no count blocks, examples:
"BlocksMined:planks:30"
"BlocksMined:dirt:30"
"BlocksMined:bookshelf:10"

Not specified if it works, examples:
"BlocksMined:20000"

**Comment by Zrips** [comment]
Try performing full restart if new requirements are not been taken properly as its seems to work for me correctly.

**Comment by C4BR3R4** [comment]
It's the first thing I've tried and nothing.

**Comment by Zrips** [comment]
That's strange, Which mc version are you running?

**Comment by C4BR3R4** [comment]
Spigot 1.12.2-R0.1-SNAPSHOT #1544

**Comment by LogGits** [comment]
Cannot reproduce. Can you please provide your ranks.yml or atleast a rank we can test that is already setup. All these work for me except for planks but that is a mojang issue with not logging all types of a block just its base id.

**Comment by LogGits** [comment]
I am closing this issue as, it is an issue with Mojang's statistics logging system.
