### ISSUE TITLE
Longer display time for title! and subtitle!

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#1911]
Toward the end of 2018, you added a longer display time (5 seconds) to /cmi titlemsg, however when running a schedule.yml title! message, it displays for 1 second, not long enough to read. It would be nice if we could set the length of time, but if not 5 seconds would be better.

Thanks.

**Comment by digitalcrowd** [comment]
bump

**Comment by Zrips** [comment]
I can change that to 0.5 sec fade in, 4 sec staying and 0.5 sec fade out for specialized command title msg handling. With next update
