### ISSUE TITLE
CMI causing memory leak

### ISSUE THREAD

**Issue by RisenCloud** [Zrips/CMI#1912]
**Description of issue:**
our custom MaxRankUp plugin uses CMI commands for ranking people up. We have gotten another MaxRankUp plugin made and it's the same thing. We are getting a memory leak with your rank system. Crashes our server when it really shouldn't and it eats up all of our memory. Please look at it. Here is our timings report and the plugin is called MaxRankUp if you look at it. it also uses crates but I know how to fix the crates problem. Thanks! btw, it isn't an update issue, we have updated many times and it's still been here for since like version 8.5 or 8.4. Please fix. Thanks!
---

https://timings.aikar.co/?id=559384a11e694a23abcb967f15bf5843

**Cmi Version (using`/cmi version`):** 
8.6.4.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper Spigot
**Server Version (using `/ver`):** 
Paper Spigot 624 (1.13.2)

**Comment by Zrips** [comment]
Made some optimizations which should address some of that possible memory leaks. If issue persists after next update, please let me know.

**Comment by RisenCloud** [comment]
alright, thank you!
