### ISSUE TITLE
Can't join server or teleport

### ISSUE THREAD

**Issue by WindUnwaken** [Zrips/CMI#1913]
**Description of issue:**
Sometimes, player can't join server with errors.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**

https://pastebin.com/DYhXMAqR

```
**Cmi Version (using`/cmi version`):** CMI 8.6.4.5

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git spigot df0eb25-0309d17

**Comment by Zrips** [comment]
Why do you think its a CMI issue? As i cant see anything mentioned about it in error log. Did you tested it without CMI?
