### ISSUE TITLE
portal

### ISSUE THREAD

**Issue by LovesAsuna** [Zrips/CMI#1916]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```white using portals
![IJ0(S$I~`ODLS_D`H~IPTBY](https://user-images.githubusercontent.com/32810896/59189178-066db680-8bac-11e9-81c4-da2f4d72d437.png)


**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
#####################################
```

---

**Cmi Version (using`/cmi version`):8.6.4.5

**Server Type (Spigot/Paperspigot/etc):spigot

**Server Version (using `/ver`):1.12.2

**Comment by LovesAsuna** [comment]
![1](https://user-images.githubusercontent.com/32810896/59189250-30bf7400-8bac-11e9-88c2-da1c2c87eb6b.png)

**Comment by Zrips** [comment]
Are you running bungee cord network?

**Comment by LovesAsuna** [comment]
no,a local server

**Comment by LovesAsuna** [comment]
By the way,I have given you the complete Chinese translation

**Comment by Zrips** [comment]
Ok, this should be fixed with next build
