### ISSUE TITLE
Language update

### ISSUE THREAD

**Issue by LovesAsuna** [Zrips/CMI#1919]
I have updated the Chinese translation of the plugin to the latest
[Locale_CN.zip](https://github.com/Zrips/CMI/files/3275236/Locale_CN.zip)

**Comment by LovesAsuna** [comment]
This translation may be unfinished, and after a while I will release the full translation.

**Comment by Zrips** [comment]
Thanks, will update default one

**Comment by LovesAsuna** [comment]
Now I am giving you a complete Chinese translation.
[Locale_CN.zip](https://github.com/Zrips/CMI/files/3285262/Locale_CN.zip)
