### ISSUE TITLE
[Feature Request] Playtime Rewards/Points System

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#192]
I know this is on your radar already, mentioned in your "Time Flies" update, but I thought I'd make it official on the GitHub and add my two cents in case you're seeking input on what people are looking for. Namely me. =p

We currently use OnTime & OnSign to track playtime and handle rewards -- great plugins but they're ancient, abandoned, and already falling apart a little. I basically dread every Minecraft update lest they break entirely. What I really love about these, though, is their points system. I'm able to set a reward based on play time, which can also be items, but our servers award 1 point per hour played, [our reward scheme shown here](https://www.badwolfmc.com/rewards). Players can then spend these points however they choose (kits, ranks, permissions), and currently we have them hooked into CMI kits by console command as rewards, which works wonderfully. I know there are other points plugins and other playtime plugins, but so far OnTime is the only one I've seen that combines the two in synergistic bliss.

If implemented, it would also be dead useful to have an API for other plugins to hook into (I would definitely request that the BossShops dev hook into it so we could make the rewards available through our menu system). 

And while I'm asking for cake I might as well ask for frosting -- one important bonus of the OnTime points system is a reward for referring other players to the server. New players are able to run a one-time command that gives the referring player points (running the command adds a permission node to the new player so the plugin can deny any further attempts to run the command and abuse the points system). It's a great little way to get new players and reward referrals while also aiding in player retention. This would be partly possible already with CMI's conditional commands checking for existing permissions, but I'm not sure how we would be able to add points to the referring player unless there was a special command or variable placeholder (to target the correct player) for it.

Thanks as always, both for the consideration and your hard work!

**Comment by mercurialmusic** [comment]
The points system and being able to integrate those features with other CMI features is the core of this request, so no, it's not ready to be closed unless it won't be implemented. It's why Zrips also left it open, I think.

**Comment by CloudeLecaw** [comment]
my Question is what we can do with this Points?
a secound value, seperate to the economy if used?

**Comment by mercurialmusic** [comment]
Yes, separate from the economy and probably not dissimilar from the existing vote count. I currently have a similar (aging/dying, hence this request) system in place where my players automatically receive one point per hour played, which they can save up to turn in for all sorts of rewards, with a focus on rewarding play over larger amounts of time and saving up for their choice of more expensive, potentially OP, items rather than a diamond or a few bucks every hour. My current system also allows us to award points for helping out or referring other players, etc., and in some ways is more desired than our economy -- not long ago I asked for volunteers to help me with something and offered them either in-game money or points as a reward and they all chose points. You can see my current setup and some of the possibilities in the reward scheme I linked in my original post.

Point systems can also be tied into other plugins if there's an API -- for example I also use BossShopPro, which provides GUI-based server shops that can allow the players to choose their reward and pay for it based on the points system. 

Honestly, my current system has been hands down the best player retention tool I have. I hear people talking about saving up for such and such item and certainly they are more willing to help out new players or refer their friends when they know they could get points for it.

**Comment by CloudeLecaw** [comment]
i renember that kind of system from the plugin PlayerPoints that also gave the Option for this.

So this is a little rewards system u planed :) Points alone wont be enough, there must be a way too to work with this points :)
will be interesting to see if this is developed or not. My server is using no Economy but a little Pointsystem for small rewarditems would be a cool thing.
We will see :-)

**Comment by mercurialmusic** [comment]
The PlayerPoints plugin you mention was actually one of my backup plans, but even that was last updated in 2016 and is not aging well. There are a couple alternatives that I'm keeping my eye on, but many of those add bloat/mess with economy/aren't the straight-forward system I'm hoping for. Might not have a choice before long, though. But yep, keeping my fingers crossed.
