### ISSUE TITLE
/donate duplication bug

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#1922]
**Description of issue:**
Step to reproduce problem:
Player 1 and player 2
Player 1 /donate to player 2
Player 2 clicks the item at the same time when player 1 drops the item from inventory with Q

Result: Player 2 gets the item while there's a dropped item on player 1 resulting in duped item
---

**Cmi Version (using`/cmi version`):** 8.6.4.6

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** 1.13.2

**Comment by Zrips** [comment]
Cant reproduce this issue, as its most likely requires server lag and players with higher ping or something in between those lines. But will make some adjustments to luckily solve this issue with next build. If issue persists, reopen ticket.
