### ISSUE TITLE
Automatic respawn causes java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by MrSpock78** [Zrips/CMI#1923]
**Description of issue:**
If a player dies he does not automatically respawn without hitting the respawn button.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://pastebin.com/aEFWFUU0

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Permission:
cmi.autorespawn – Allows to respawn automatically

**Cmi Version (using`/cmi version`):** 
8.6.4.5
**Server Type (Spigot/Paperspigot/etc):** 
Paper(629) 1.13.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
By any chance this is not a standard world he is trying to respawn in? Like created one with multiverse?

**Comment by MrSpock78** [comment]
Yes the spawnpoint is in a world generated with multiverse. But a normal world.

**Comment by Zrips** [comment]
Ok, reproduced and should be fixed with next build
