### ISSUE TITLE
Inventory Click event error

### ISSUE THREAD

**Issue by cdmvirt** [Zrips/CMI#1924]
Inventory click event error

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**

https://pastebin.com/xfC4n1YG

**Cmi Version (using`/cmi version`):** 8.6.4.7

**Server Type (Spigot/Paperspigot/etc):**  1.14.2 #77

**Comment by Zrips** [comment]
Strange bug, will prevent it from happening, but in general this should not happen in regular situations.
