### ISSUE TITLE
CMI keepinventory op

### ISSUE THREAD

**Issue by Yamiru** [Zrips/CMI#1926]
hello, i have problem with Admins, OP,... if players not got permission cmi.keepinventory items drop this fine, but if admins,op, have (cmi.*, *) items not dropped.
I trying to change this to RequiresPermission: true, but same problem
I trying to remove all from cmi(default) (folder CMI), but same problem

------------------------------------------------------------------

> inv:
>   # Do you want to save the player's inventory on his death
>   SaveOnDeath: false
>   # When set to true, empty inventories (no items in inventory) will not be saved on players death
>   IgnoreEmpty: false
>   # If set to true then player should have cmi.saveinv permission node for inventory to be saved on death
>   RequiresPermission: false
>   # How many inventories, we will keep for each player
>   SavedInventories: 5

-----------------------------------------------------------------------------------
no errors
-----------------------------------------------------------------------------------

**Cmi Version: latest 8.6.4.7
**Server Type: Paperspigot
**Server Version: Paperspigot 1.14.2 #82
**Relevant plugins : LuckPerms-Bukkit-4.4.26

**Comment by Zrips** [comment]
Well if you give player all the permissions from CMI then there should be no surprise that he has all of them. I would recommend to add negated permission node for cmi.keepinventory and your permission plugin should pick it up and prevent inventory keeping on death for admins
