### ISSUE TITLE
cmi.fullserver.bypass not working

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#1927]
**Description of issue:**
cmi.fullserver.bypass doesn't seem to work. Tested on a test server with 2 players in a 1 slot server. The 2nd player can't join even when they have cmi.fullserver.bypass permission. (Checked with haspermission, using LuckPerms as permission manager plugin)
---

**Cmi Version (using`/cmi version`):** 8.6.5.0

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** 1.13.2

**Relevant plugins (Delete if this isn't needed):** LuckPerms 4.3.73

**Comment by Zrips** [comment]
Will add some extra changes to this particular handling which hopefully will solve your issue.
