### ISSUE TITLE
Home GUI sends error

### ISSUE THREAD

**Issue by starwarsfreak219** [Zrips/CMI#1929]
**Description of issue:**
I noticed that the home GUI will print out an error and not open, and it will tell users that an internal issue occured. I did some testing and found out that it was because of the fact that they were on the block double_stone_slab:8, which makes a double stone slab smooth at the edges. Please look into this. Thanks!
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/Y0T38TKy
```

**Cmi Version (using`/cmi version`):** 
8.6.5.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by starwarsfreak219** [comment]
Just thought I would also mention that /home functionality still works, just not with the GUI. I should also mention that I have PickRealBlock in the config set to true(which is by default).

**Comment by Zrips** [comment]
This should be in working condition now with latest builds
