### ISSUE TITLE
/seen 1.2.3.4    (/see ip issue)

### ISSUE THREAD

**Issue by dmnchild** [Zrips/CMI#1930]
So being used to essentials, someone /seen 1.2.3.4
It returned the standard Can't find player with this name.

Now, the console is spamming this error non stop, about 10 times per second. 
Ive removed the plugin, restarted, no error of course, put plugin back, restarted, and now its spamming it again still.

I have no clue where to go from here, since I would never imagine it can persist through a restart.

---

**Can't find player with this name! (in console)**
```


**Cmi Version (using`/cmi version`):** 
CMI8.6.5.0

**Server Type (Spigot/Paperspigot/etc):** 
Paper631

**Server Version (using `/ver`):** 
Paper-631 1.13.2

**Comment by dmnchild** [comment]
I was able to stop the spam by changing the Locale_EN.yml line regarding this to:
  NoPlayer: ''
But this is a bandaid to a bigger problem. Im baffled how this can persist through a restart, any help appreciated as I would actually like the error message in place.

**Comment by Zrips** [comment]
An actual error would help out to pinpoint the origins of that error.

**Comment by dmnchild** [comment]
> 
> 
> An actual error would help out to pinpoint the origins of that error.

At the time when i changed the language file, it was spamming whatever the default user not found. I have not fixed the language file to see if it still spams or not. It did only spam console, not in game. So just imagine whatever the default error is in language file for   [  NoPlayer: '(I forget original error message)   ] It would just spam that over and over, not an actual error. (instead of just posting once to terminal)
