### ISSUE TITLE
Placeholder for glows

### ISSUE THREAD

**Issue by ghost** [Zrips/CMI#1933]
Glows are really nice for cosmetics, and it would be a powerful feature if we can have placeholders corresponding to the glow the player has. 

---
### Detailed explanation what it should do and when and in what situations ###
 %cmi_user_glow% - The name of the glow that the player is using.
 %cmi_user_glow_color% - The color code of the glow that the player is using.

### Basic explanation why this feature is needed in CMI and how useful it would be to have it ###
 %cmi_user_glow% - Just a handy placeholder, useful for making custom playerholders or just displaying the specific glow.
%cmi_user_glow_color% - This with the glow GUI allows for better displayname custom colors without specifying it in a chat or permissions plugin.  Great for vanila servers with hardly any colors in chat, great for tablists, and for giving the players options choosing their color name.

**Comment by Zrips** [comment]
%cmi_user_glow_name%
%cmi_user_glow_code%
