### ISSUE TITLE
interactive commands variable with luckperms

### ISSUE THREAD

**Issue by mrigal-carp** [Zrips/CMI#1935]
am trying to use interactive command sign to give player clicking the sign a permission

http://prntscr.com/o27pn1 - sign text
http://prntscr.com/o27pxb - sign commands
http://prntscr.com/o27qfy - luckperms output
---

**Cmi Version (using`/cmi version`):** 
http://prntscr.com/o27tb0

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
http://prntscr.com/o27t4w

**Relevant plugins (Delete if this isn't needed):** 
-LuckPerms
-CMI

**Comment by Zrips** [comment]
Should be working as expected with next build
