### ISSUE TITLE
Light Fix not Working in 1.14.2

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#1936]
**Description of issue:**

As title.

**Cmi Version (using`/cmi version`):** 
8.6.5.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.14.2

**Comment by Zrips** [comment]
Know issue. 1.14 version had huge remake for light recalculations and old methods are simply missing from server and lighting are done in completely new way which is some what better but at same time prevents forced updates when we need it. Will have to disable this command for time being until i can find some work around for it, if there is any.
