### ISSUE TITLE
CMI and ReWorld

### ISSUE THREAD

**Issue by DarkFort** [Zrips/CMI#1937]
Holograms are sometimes displayed, and sometimes disappear.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## https://pastebin.com/yAfRh4v9 ##
####################
```

CMi 8.6.5.0

Paper(631) 1.13.2-R0.1-SNAPSHOT

**Relevant plugins (Delete if this isn't needed):ReWorld**

**Comment by Zrips** [comment]
Will add this plugin to softdepend and it should solve your issue

**Comment by DarkFort** [comment]
After updating CMI, the problem was not resolved. https://pastebin.com/D7jRmn50
