### ISSUE TITLE
Players can´t change their Skin

### ISSUE THREAD

**Issue by MrSpock78** [Zrips/CMI#1938]
**Description of issue:**
I enabled the cmi skin feature. But no player has access to it.
When a player changes the skin in launcher it is not updated on the server,
even when the player was never touched by "cmi skin".
The new skin is also not available via "cmi skin name".

**Cmi Version (using`/cmi version`):** 
8.6.5.0

**Server Type (Spigot/Paperspigot/etc):** 
Paper 1.13.2 (631)

**Comment by Zrips** [comment]
Is this regular or bungee server?

**Comment by MrSpock78** [comment]
Regular server. No bungee no offline mode.

**Comment by MrSpock78** [comment]
It seems CMI is saving every playerskin in skinsCache.yml, but it should only save skins changed with cmi skin?

**Comment by Zrips** [comment]
Yes, only when you use /cmi skin command they will be saved into skinsCache.yml file. Its just to prevent uneeded skin requests from mojang server which is limited to like 100 in one hour. So we have to cache them.

**Comment by MrSpock78** [comment]
My skinsCache is full of players that never were in touch with cmi skin.
https://pastebin.com/FYiG6hph
I only changed the skin of one player with cmi skin.

**Comment by Zrips** [comment]
What is set for your SteveOnOff in config file?

**Comment by MrSpock78** [comment]
Skins:
  # Enable or disable skin management
  Enabled: true
  # Applies skin to player automatically on his login to server if he doesnt have one already set
  # This will always set to skin by target player name
  AutoApply: true
  # Sets player sking to Steve when turning skin off and lets server to handle it
  # If its false, then skin will be changed to online one
  SteveOnOff: false
  # Requests from player specific permission for that skin cmi.command.skin.perm.[skinName]
  RequireSpecificPerm: false

**Comment by MrSpock78** [comment]
Update: When I use "/cmi skin Alex <player>" once then it does not update to Alex but to the actual player skin.

**Comment by Zrips** [comment]
It could be issue with your game client itself, as what i noticed that official client will show skins correctly while some cracked clients could show Steve skin even if you changed skin.
If issue still persists, reopen ticket, but will close it for now as it seems to be working correctly at this point.
