### ISSUE TITLE
AFK tag for /list

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#1939]
The list command provides a nice overview. The overview would be even better if players who are currently afk could be provided with a special symbol or be colored differently. An afk tag would e.g. clearly show who is currently accessible from the staff team without having to enter the afkcheck command ten times.

**Comment by Zrips** [comment]
Will add afk prefix for players who are in afk mode with next build

**Comment by LogGits** [comment]
@TheoRetisch1 This is not a bug report. This is already possible, see `List.info.playerF`
`playerF: '&f[playerDisplayName]'`
Add the afk symbol(`{cmi_user_afk_symbol}`) to this.

Result:
`playerF: '&f{cmi_user_afk_symbol}[playerDisplayName]'`

**Comment by TheoRetisch1** [comment]
Nice! Thank you very much for the update and the explanation. Sorry for the inconvience LogGits :/
