### ISSUE TITLE
Request: Add weight value to schedules 

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#194]
I have an auto announcer scheduled for every 10 minutes when players are on. This announcer currently has 6 lines of text and is using subtitle placement. I also have a Server restart countdown using the subtitle placement. This one is triggered manually. If I trigger it while the auto announcer is active, or if the auto announcer starts to run after I trigger the countdown, the lines of text overlap and looks bad. If you could add a weight value to the schedule to override and/or prioritize when manually triggering them. That would be great.

**Comment by Zrips** [comment]
Can you provide those 2 schedulers for testing so we can be on same page?
