### ISSUE TITLE
Chinese translation is wrong

### ISSUE THREAD

**Issue by LovesAsuna** [Zrips/CMI#1942]
![_~(Z57$1 LQZUP1NZ TL`FD](https://user-images.githubusercontent.com/32810896/59620529-a8b70c80-915f-11e9-8f3c-f912dcac3b78.png)
[Locale_CN.zip](https://github.com/Zrips/CMI/files/3297979/Locale_CN.zip)

**Comment by Zrips** [comment]
Got fixed
