### ISSUE TITLE
About AFK Detect

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#1946]
**Description of feature/improvement request:**
Improve AFK detect 
### Detailed explanation what it should do and when and in what situations ###
Some players will afk in spawner farm and enable anto click.
Afk detect won't Identify it as Afk.
### Basic explanation why this feature is needed in CMI and how useful it would be to have it ###
Just a update and it can really prevent those afks.

**Comment by Zrips** [comment]
Then set DisableOnInteract to false and player will be put into afk mode if he stands still and simply hits enemies without any movement
