### ISSUE TITLE
Skin Module Bug

### ISSUE THREAD

**Issue by domasjan123** [Zrips/CMI#1947]
**Description of issue:**
I using ProtocolSupport with CMI. My players can't join to server if CMI or Protocol support are enabled
I disabled Skin Module (defined <<<<) and downloaded SkinsRestorer. After I missed this error.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
On player join: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown dimension network id 12
Or: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown dimension network id 13

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
#####################################
Skins:
  Enabled: false  <<<<<<<<<<<<<<<
  AutoApply: false
  SteveOnOff: false
  RequireSpecificPerm: true

---

**Cmi Version (using`/cmi version`): 8.6.5.1

**Server Type (Spigot/Paperspigot/etc): PaperSpigot

**Server Version (using `/ver`): Paper-631 (MC: 1.13.2)

**Relevant plugins (Delete if this isn't needed): ProtocolSupport, Viaversion

**Comment by Zrips** [comment]
Got fixed
