### ISSUE TITLE
cmi ctext all has no permission node

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#1950]
**Description of issue:**
Player can use the command /cmi ctext textname all
When I checked the player permission for
/cmi haspermission playername cmi.command.ctext (this is true)
/cmi haspermission playername cmi.command.ctext.others (this is false)

I'm using LuckPerms for my permission management plugin
---

**Cmi Version (using`/cmi version`):** 8.6.5.1

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.13.2

**Relevant plugins (Delete if this isn't needed):**Luckperms 4.3.73

**Comment by blek-id** [comment]
Bump. This is still an issue

**Comment by rhar-hishine** [comment]
can be abused to spam the chat

**Comment by Zrips** [comment]
Fixed
