### ISSUE TITLE
Problem with tfly

### ISSUE THREAD

**Issue by Roper89** [Zrips/CMI#1952]
**1.**
I use `/tfly` and get the message: _Temporary fly mode is not enabled for player._
What am I doing wrong? I want to activate temporary fly.

I have permission:  
`cmi.command.tfly`  
`cmi.command.tfly.maxtime.30`

**2.**
Permission is still not working. — `cmi.command.gm.[gametype]`

**Comment by Roper89** [comment]
Please, help.
I want to give players the opportunity to activate a temporary flight for themselves.

**Comment by Fabrimat** [comment]
Use `/cmi tfly ?` to view the command info.

**Comment by Zrips** [comment]
/tfly 5m
gives fly for 5 minutes
/tfly 5h
gives fly for 5hours and so on
