### ISSUE TITLE
Messsages in CMIRanks Can't Be Translated

### ISSUE THREAD

**Issue by kn-km** [Zrips/CMI#1953]
**Description of issue:**
Hello,everyone.
I have a problem with CMIRanks.
I've translated all the lang files.But the messages in CMIRanks still not get translated.
like this:
![KL0SJ9B~__T9M%9V5QQV331](https://user-images.githubusercontent.com/13903138/59961810-4d926a80-950f-11e9-9135-44f91f0a7e45.png)

I'm waiting for solution.
Thank you !
---

**Cmi Version (using`/cmi version`):** 
8.6.5.1

**Comment by Zrips** [comment]
Those are the names of items, real names. To have them translated we would need one big file with all possible materials. This requires extra work to be done to have them translated to desired language.
