### ISSUE TITLE
Double message with ClickHoverMessages set to true

### ISSUE THREAD

**Issue by titidelaff** [Zrips/CMI#1958]
When I set ClickHoverMessages to true, all message in chat are double.

**Cmi Version (using`/cmi version`):** 
8.6.5.1

**Server Type (Spigot/Paperspigot/etc):** 
Paper632 

**Server Version (using `/ver`):** 
1.13.2

**Comment by Zrips** [comment]
Do you use any other plugin which could interfere with this one? And did you tested it without other plugins? As i'm running my test server with ClickHoverMessages enabled and dint experienced this issue on any minecraft version.
