### ISSUE TITLE
Issues with /cmi portals

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#196]
There is an issue with cmi portals. It appears that save changes in the cmi portals gui doesn't save and reload the portal. Therefore when I click the "redefine area from current selection" block and save, it doesn't save it. Additionally, setting particles to enabled/disabled doesn't work either with saving.

**Comment by Zrips** [comment]
There is button in left bottom corner to save changes. But will remove it and remake to save automaticaly on GUI close event.
