### ISSUE TITLE
1.14.3-pre4 crash after /home

### ISSUE THREAD

**Issue by minecraft7net** [Zrips/CMI#1964]
**Description of issue:**

player issue command /home and it can generate crash i have this on 4 server 1.14.3-pre4
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```
https://pastebin.com/m9uRygsF
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
[21:36:12] [Server thread/INFO]: [CMI] Loading CMI v8.6.5.1

**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
[21:36:09] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-f16400e-8a3d3f4 (MC: 1.14.3 Pre-Release 4) (Implementing API version 1.14.3-pre4-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Try using full 1.14.3 release and report back if issue is still there, as your error message doesn't even mention CMI and from that error message it looks more like minecraft failed to handle player teleport by itself, so this is most likely issue with minecraft version itself.
