### ISSUE TITLE
Alert time change

### ISSUE THREAD

**Issue by Fabrimat** [Zrips/CMI#1965]
**Description of feature/improvement request:**

---
When I set an alert on a player (with /cmi alert) it will last for just 24 hours, that would be awesome if I could change the time for like a week or set it to permanent (until when it will be removed).
Because I use it with my staff to report players who probably use cheats, but if the player doesn't log in for 24 hours the alert is lost and nobody recive it.

**Comment by Zrips** [comment]
Ok, with next update will add this one.
