### ISSUE TITLE
Teleport unsafe: suffocation with carpets

### ISSUE THREAD

**Issue by Fabrimat** [Zrips/CMI#1966]
**Description of issue:**

When a player does /home or /warp to a location where there is a carpet it says "Teleport location is unsafe. Suffocation" but a player can't suffocate with a carpet..
The problem wasn't in CMI 8.6.3.0.

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.6.5.1 BungeeCord 
Server version: Spigot 1.13.2-R0.1-SNAPSHOT
Vault version: 1.6.11(+)
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.

**Comment by Zrips** [comment]
Could you give a picture of that exact place? And does player have cmi.safeteleport? And SafeLocationDownThenUp set to true or false in config file?

**Comment by Fabrimat** [comment]
In the image the red carpet is where the warp is set.
![image](https://user-images.githubusercontent.com/13642582/60603745-a0450f80-9db6-11e9-8342-24f4991c40dc.png)

cmi.safeteleport: yes
SafeLocationDownThenUp = false

**Comment by Zrips** [comment]
@Fabrimat Home location set directly on top of carpet or it was set before putting down carpet? As i'm testing this one in all possible configurations, still getting teleported to target location, so something strange is going on here.

**Comment by Zrips** [comment]
Try testing it in open field, and test out with newest version. I need a way to reproduce this issue before i can find out what went wrong.

**Comment by Momshroom** [comment]
The same problem occurs with grass paths.

**Comment by Fabrimat** [comment]
I tried on a fresh server with just CMI and Luckperms installed.
CMI version 8.6.6.0.
Permissions enabled:
- cmi.command.warp
- cmi.command.warp.*
- cmi.safeteleport

Player is in Survival gamemode (does not work in Creative).
No matter if you first set the warp or place the carpet.

Op yourself, set the warp, place the carpet, deop yourself and do /cmi warp name.
![image](https://user-images.githubusercontent.com/13642582/60606106-05026900-9dbb-11e9-87a3-43b44eef0b81.png)

@Momshroom can't reproduce with grass paths.

**Comment by Zrips** [comment]
Found issue. It was not enough accuracy while finding safe location, instead of getting 76.0625 we got 76.06 while checking Y coordinates. Will be fixed with next version
