### ISSUE TITLE
Set up panimation through use of portal or interactive commands.

### ISSUE THREAD

**Issue by FestusDM** [Zrips/CMI#1967]
**Question: **
Trying to set up panimation with portals but it doesn't seem to work. Below is my `portals.yml` file (Panimation also doesn't seem to be working when I set up interactive commands, either...maybe I typed something wrong?):
```circle_particles:
    Loc: 52.0:66.0:-78.0:55.0:69.0:-77.0
    enabled: true
    effect: reddust
    showParticles: true
    Tp: world;54.99;66.5;-57.58;359.3;19.59
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 20
    particleHide: 0
    activationRange: 2
    commandsWithoutTp: true
    commands:
    - cmi panimation circle;effect:reddust;dur:900;pitchc:5;part:10;offset:0,1,0;radius:1;yawc:5;color:rs;target:[playerName]```

**Comment by Zrips** [comment]
try adding asConsole! at beginning of command

**Comment by FestusDM** [comment]
`    commands:
    - asConsole! cmi panimation circle;effect:reddust;dur:900;pitchc:5;part:10;offset:0,1,0;radius:1;yawc:5;color:rs;target:[playerName]`
Didn't work for both portals and interactive commands.

**Comment by Zrips** [comment]
This should be working now with latest build
