### ISSUE TITLE
CMI keeps editing tablist after disabling

### ISSUE THREAD

**Issue by DAmNRelentless** [Zrips/CMI#1968]
**Description of issue:**
CMI is still managing and editing the tablist although I disabled the tablist option in modules.yml. It also overwrites the plugin I am normally using to edit the tablist.
---

**Cmi Version (using`/cmi version`):** v8.6.5.2

**Server Type (Spigot/Paperspigot/etc):** Paper 112

**Server Version (using `/ver`):** 1.14.3

**Relevant plugins (Delete if this isn't needed):**
- CMI
- TAB

**Comment by DAmNRelentless** [comment]
Edit: seems like you have to disable the tablist feature in tablist.yml too so it is fully disabled. It works like that but I think that should be changed. Why would you need to disable the feature if the whole module is deactivated and shouldn't be loaded? So I keep this issue report open.

**Comment by Zrips** [comment]
Good point, will remove this section from tablist file and from now on it will fully depend from value set in modules.yml file
