### ISSUE TITLE
Pay command confirmation expiration to prevent scam

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1972]
**Description of issue:**
When a player pays another player he has to confirm the payment which is fine.
When the player clicks on the checkbox the payment is executed.
However, when the player accidently clicks twice on the checkbox, the payment is done also.
In fact: you can click endlessly. 

It would be wishful if the pay command can only be executed once per confirmation.
Just as a precaution to prevent scams.

---

**Cmi Version (using`/cmi version`):** 
8.6.5.2
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.13.2 & 1.14.3

**Comment by Zrips** [comment]
Ok, next update will allow to click that message only once.
