### ISSUE TITLE
Godmode - Hunger/Health bar

### ISSUE THREAD

**Issue by BiGUNMAN** [Zrips/CMI#1973]
**Description of issue:**
Cannot eat in godmode to replenish hunger bar. Hearts don't go up either (yes, godmode stops damage but still, why prevent people from replenishing their hunger bar and having their hearts go up).

---

**Cmi Version (using`/cmi version`):** 8.6.5.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.13.2: 631

**Comment by Zrips** [comment]
This is how minecraft handles immortal players, can't really allow to eat food and replenish hunger/health without changing entire god mode handling.
