### ISSUE TITLE
Illegal Characters in Chat

### ISSUE THREAD

**Issue by MidnightSugar** [Zrips/CMI#1974]
**Description of issue:**
Edit hologram text, and try to copy the line to chat. If it happens to be colored, it will kick me from the server.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
27.06 19:37:27 [Disconnect] User MidnightSugar has disconnected, reason: Illegal characters in chat
```

---

**Cmi Version (using`/cmi version`):** 8.6.52

**Server Type (Spigot/Paperspigot/etc):** Paper(114) 1.14.3-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 1.6.11(+)

**Comment by LogGits** [comment]
Please provide the hologram setup from the `holograms.yml` file and what line are you trying to edit.

**Comment by Zrips** [comment]
Cant reproduce at this point, colored lines can be copied into chat box without issues. So we still need that example you have exactly set for that particular hologram from holograms.yml file
