### ISSUE TITLE
/colors broken

### ISSUE THREAD

**Issue by MidnightSugar** [Zrips/CMI#1975]
**Description of issue:**
/colors doesn't show colors, only formatting

---

**Cmi Version (using`/cmi version`):** 8.6.5.2

**Server Type (Spigot/Paperspigot/etc):** Paper(114) 1.14.3-R0.1-SNAPSHOT

**Server Version (using `/ver`):** git-Paper-114 (MC:1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Could you give screenshot how it looks for you? As 1.14.3 shows it correctly. And make sure your locale is set correctly for this command. It should look something like
```
    info:
      List:
      - '&e***************************************'
      - '     &0&%0  &1&%1  &2&%2  &3&%3  &4&%4  &5&%5  &6&%6  &7&%7'
      - '     &8&%8  &9&%9  &a&%a  &b&%b  &c&%c  &d&%d  &e&%e  &f&%f'
      - '       &%k - &kMagic&r      &%l - &lBold'
      - '       &%m - &mStrike&r     &%n - &nUline'
      - '       &%o - &oItalic&r      &%r - &rReset'
      - '&e***************************************'
```
