### ISSUE TITLE
Sign Copy optional username

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#1976]
**Description of feature/improvement request:** Add an optional player variable to sign copy. Usage `/cmi sc [playerName]`

---
### Detailed explanation what it should do and when and in what situations ###
`/cmi sc [playerName]` should toggle the `/cmi sc` for a specific player. e.g. if i look at a sign and type `/cmi sc Larry` it will send my sc to larry meaning larry can left click to paste it onto a sign.
### Basic explanation why this feature is needed in CMI and how useful it would be to have it ###
It would allow quick simple sign copying. My usage is that i need to move a shop and to move each item via tp is too slow, and to manually type it is even slower. With two users, one I could use `/cmi sc [myUsername]` and the other user could just left click to paste on the sign. Simple and efficient.

**Comment by Zrips** [comment]
Next update
