### ISSUE TITLE
cmi.command.feed permission issus.

### ISSUE THREAD

**Issue by dryter97** [Zrips/CMI#1983]
**Description of issue:**

---
permission of cmi.command.feed not working at all and by this issus player got /feed permission by default

---

**Cmi Version: 3654:** 

**Server Type (Paperspigot):** 

**Server Version (git-Paper-624 MC: 1.13.2):**

**Comment by Zrips** [comment]
check players permission access with /cmi haspermission cmi.command.feed Zrips
and report its feedback, as by default only OP players should have access to this permission node
