### ISSUE TITLE
missing items at death

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1989]
cmi:  8.6.5.4

Spigot:CraftBukkit version git-Spigot-935adb3-bf0ea33 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

when you die in the game, not all items are dropped.
1/3 of the inventory is missing.
Is this a CMI bug or a spigot bug or is this the way it should be?

**Comment by Zrips** [comment]
CMI doesn't control how much you are dropping on death. In general its something i wanted to add in future, but currently its not a feature. So it must be some other plugin or even minecraft itself, would not be surprised if its minecraft, after all, its 1.14.3, its broken as hell.
