### ISSUE TITLE
Question on Ranks and Clickable Entities

### ISSUE THREAD

**Issue by T-Curry** [Zrips/CMI#1990]
**Question: **
Hi, I'm setting up ranks for my server and I was just wondering if I could add a requirement from another plugin that's not from jobs or mcmmo and how I'd go about doing that. Also, I've been trying to create clickable entities using citizens from the Citizens plugin and commands from other plugins will not work. I followed tutorials on how to do it and I do not know why it's not working. This plugin is really amazing but I was just wondering if I could get some help.
Thanks

**Comment by Zrips** [comment]
Requirements from another plugin should be hard coded, there are too many variables to have some universal method in doing that.
For Citizens, simply use Interactive commands, its /cmi ic you can attack any commands you want to NPC and perform them when clicked. You can check this wiki page for more information about its usage http://www.zrips.net/cmi/commands/interactive-commands/

**Comment by T-Curry** [comment]
So does that mean I can use requirements from other plugins or not (I'm not well-versed in coding language)?

**Comment by Zrips** [comment]
At this point you cant, there are some hard coded support, like Jobs or McMMO, you cant really add so simply new requirement from some another plugin. This would require quite a bit of recoding for this entire feature.

**Comment by T-Curry** [comment]
With the clickable entities, I enter the commands and it says that they've been added to the entity. However, they still do not work when I click on the entity
