### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by glorying16** [Zrips/CMI#1991]
Our database is somehow having a stroke and will switch user data for any random number of players. Trading the info for one player, and adding it to anothers UUID. So it somehow thinks there is a second UUID for the same name. I used a backup of the sqlite to fix it the first time, but this second time (the next day) luckily only one player was effected (at least at this point). Im not sure if this is an issue of CMI or of the sqlite. He can no longer access his own /homes and is set as the other players nick. If I do the /cmi removeuser or /cmi removeuser duplicates, I will lose the wrongfully edited players data.  Would we be safer moving to MySQL? Or could this still potentially happen again?

---

[CMI] Attention! Found 1 duplicates in database. Same name, different UUID. This can cause some minor issues. Please remove one of them from database with /cmi removeuser [uuid] or /cmi removeuser duplicates

**Cmi Version (using`/cmi version`):** 8.6.5.4

**Server Version (using `/ver`):** Spigot 1.14.3-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Are you running offline server? Did player changed his nickname? In general players data is directly attached to UUID, which by itself has 2 options: if you are running online mode, then its never changing even if you change your nickname, next, if you are running offline server and player changes name or even changes capitalization of the name, then new user will be created with different uuid. But issue comes when trying to separate 2 players with same name. I will need some actual examples of that player who lost his data and player which data he got, with name and UUID, we need to figure out whats causing this.
Moving to MySQL will not change anything as database only saves data and sqlite/MySQL are more more less identical when it comes to data save methods.

**Comment by glorying16** [comment]
Nope. We arent an offline server. Its taking one players information, and overwrites it to another players, but not really the UUID. So im not sure what makes it think there is a duplicate of UUID. Example: One minute Topher has his homes and his nickname, then the next he has Dino's, while Dino still has their correct data. When you open up the cmi.sqlite.db it lists the correct username and UUID, but will display the changed nickname and homes. Both times it happened it effected different players. The first time there were 3 or 4 people effected, and the second time there was only one. Im having a hard time locating the original one in my logs, it could have been a gradual thing (found 1 person in one log, then 2 in another etc. But I couldnt find a log with all the effected persons). But the second time it was after a crash and I found it in the start up logs. Ill see if I can find some better logs.

**Comment by glorying16** [comment]
Well, just restarted the server to update CMI and found this...

> 03.07 20:39:08 [Server] INFO Attention! Found 1 duplicates in database. Same name, different UUID. This can cause some minor issues. Please remove one of them from database with /cmi removeuser [uuid] or /cmi removeuser duplicates 
03.07 20:39:08 [Server] INFO SilentShadow_K 520aeb79-cf38-4b8f-8450-1aaa2965659c last seen: 22 hours 46 min 45 sec  
03.07 20:39:08 [Server] INFO SilentShadow_K fd75288a-d00e-44c2-9f45-cb6cd7e2f06a last seen: 22 hours 46 min 45 sec <

**Comment by glorying16** [comment]
This had been fixed for a while in one of the former updates, but seems to have resurfaced.

**Comment by glorying16** [comment]
If I use the command to clear out the duplicates, what would happen to the data? I dont want to clear them only to lose both peoples data.

**Comment by Zrips** [comment]
Removing duplicates will remove oldest one
