### ISSUE TITLE
Money permission bug

### ISSUE THREAD

**Issue by omgitsAngus** [Zrips/CMI#1994]
**Description of issue:**
There is a bug in the latest version, which allows anyone without any cmi.command.money.pay or cmi.command.pay to /cmi money pay other players. I cannot /pay as a default user, but ./cmi money pay does work and both these commands should theoretically share the same perm. I know the first group (which each other group inherits from) does not have cmi.command.money.pay
---
<img width="744" alt="Screen Shot 2019-07-02 at 1 48 28 AM" src="https://user-images.githubusercontent.com/11791722/60441852-f9545c80-9c6b-11e9-9ebf-7aa77ee08382.png">
<img width="646" alt="Screen Shot 2019-07-02 at 1 50 36 AM" src="https://user-images.githubusercontent.com/11791722/60441886-0a04d280-9c6c-11e9-8cdb-e197a7c2e53d.png">

> 
**Cmi Version (using`/cmi version`):** 
Latest
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.12.2

**Comment by Zrips** [comment]
Good point, will change it to require cmi.command.pay when using /cmi money pay [playerName] [amount]
