### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by colue** [Zrips/CMI#1999]
**Question: **
can someone look at this and tell me what im doing wrong

default:
  Enabled: true
  DisplayName: "&fIon"
  DefaultRank: true
  AutoRankup: true
  NextRanks:
  - Argus
  Commands:
  - "lp user [playerName] group add argus"
  - "broadcast! &6[playerDisplayName] &eleveled up to Argus rank!"
  StatsRequirements:
  - "PlayTime:600"
Argus:
  Enabled: true
  DisplayName: "&cArgus"
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Poseidon
  Commands:
  - "lp user [playerName] group add poseidon"
  - "broadcast! &6[playerDisplayName] &eleveled up to Argus!"
  StatsRequirements:
  - "PlayTime:60000"
Poseidon:
  Enabled: true
  DisplayName: "&9Poseidon"
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Apollo
  Commands:
  - "lp user [playerName] group add apollo"
  - "broadcast! &6[playerDisplayName] &eleveled up to Poseidon!"
  StatsRequirements:
  - "PlayTime:600"
Apollo:
  Enabled: true
  DisplayName: "&6Apollo"
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Hyperion
  Commands:
  - "lp user [playerName] group add hyperion"
  - "broadcast! &6[playerDisplayName] &eleveled up to Apollo!"
  StatsRequirements:
  - "PlayTime:600"
Hyperion:
  Enabled: true
  DisplayName: "&5Hyperion"
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Odysseus
  Commands:
  - lp user [playerName] promote rank
  - "broadcast! &6[playerDisplayName] &eleveled up to Hyperion!"
  StatsRequirements:
  - "PlayTime:4600"
Odysseus:
  Enabled: true
  DisplayName: "&6Odysseus"
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Endora
  Commands:
  - "lp user [playerName] group add odysseus"
  - "broadcast! &6[playerDisplayName] &eleveled up to Odysseus!"
  StatsRequirements:
  - "PlayTime:4600"
Endora:
  Enabled: true
  DisplayName: "&7Endora"
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Zeus
  Commands:
  - "lp user [playerName] group add endora"
  - "broadcast! &6[playerDisplayName] &eleveled up to Endora!"
  StatsRequirements:
  - "PlayTime:4600"
Zeus:
  Enabled: true
  DisplayName: "&eZeus"
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Psyche
  Commands:
  - "lp user [playerName] group add zeus"
  - "broadcast! &6[playerDisplayName] &eleveled up to Zeus!"
  StatsRequirements:
  - "PlayTime:4600"
Psyche:
  Enabled: true
  DisplayName: "&bPsyche"
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Uranus
  Commands:
  - "lp user [playerName] group add psyche"
  - "broadcast! &6[playerDisplayName] &eleveled up to Psyche!"
  StatsRequirements:
  - "PlayTime:4600"
Uranus:
  Enabled: true
  DisplayName: "&4Uranus"
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Gaea
  Commands:
  - "lp user [playerName] group add uranus"
  - "broadcast! &6[playerDisplayName] &eleveled up to Uranus!"
  StatsRequirements:
  - "PlayTime:4600"
Gaea:
  Enabled: true
  DisplayName: "&2Gaea"
  AutoRankup: true
  RankupConfirmation: false
  Commands:
  - "lp user [playerName] group add gaea"
  - "broadcast! &6[playerDisplayName] &eleveled up to Gaea!"
  StatsRequirements:
  - "PlayTime:4600"
Mod:
  Enabled: true
  DisplayName: "&9Mod"
  AutoRankup: true
  Commands:
  - "lp user [playerName] group add mod"

the plugin isnt autoranking up and does not seem to be setting the permissions or showing the prefix in chat or tab and get this error from console

03.07 19:37:25 [Server] Server thread/ERROR null
03.07 19:37:25 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'rankset Diablo1994 ion' in com.Zrips.CMI.Containers.CommandReg$ReflectCommand(rankset)
03.07 19:37:25 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:875) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
03.07 19:37:25 [Server] INFO Caused by: java.lang.NullPointerException
03.07 19:37:25 [Server] INFO at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:74) ~[?:?]
03.07 19:37:25 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
03.07 19:37:25 [Server] INFO ... 16 more

**Comment by Zrips** [comment]
Should no longer cause issues with latest builds
