### ISSUE TITLE
CMI and pets bug.

### ISSUE THREAD

**Issue by QueenAngus** [Zrips/CMI#2001]
**Description of issue or feature request:**
Hi there,
My current issue is with CMI and SimplePets. When somebody is wearing a pet on their head such as an ocelot, they cannot use the teleport command as it says it is an unsafe location.
Thanks! Any help would be amazing.
---

**Comment by Zrips** [comment]
Isint it saying that its unsafe and because of some "3rd party plugin"? 3rd party means that some other plugin, not CMI, blocked teleportation, which could mean that pet plugin itself blocks teleportations with pets on head
