### ISSUE TITLE
long loading during teleporting

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#2004]
CMI Version:8.6.6.0

Spigot: CraftBukkit version git-Spigot-d05d3c1-604c8bf (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

When I teleport to the spawn or home point it takes a few seconds until everything is set up. I fall into the void for a while until I reach the point where I wanted to go. or it takes a few seconds until everything is set up. Is this a CMI error? or another Mojang problem from the 1.14 series?
This problem did not exist a few days ago.

http://pic.lululand.de/upload/Webseite/2019_07_04_22.21.04.png

**Comment by Zrips** [comment]
Will do some testing, but in general 1.14.x versions are terrible when it comes to chunk loading. So most likely its a minecraft issue, but to make sure will do some testing.
