### ISSUE TITLE
Glow GUI color bug

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#2007]
**Description of issue:**
When changing color with /glow gui, color is only white. The bug has been here for a few versions, I'm very sorry that I have just reported this now.
---

**Cmi Version (using`/cmi version`):** 8.6.6.1

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** 1.13.2

**Comment by Zrips** [comment]
This is a compatibility issue with other plugins that uses scoreboard teams and there is no good solution at this point.
