### ISSUE TITLE
auto rank isnt working

### ISSUE THREAD

**Issue by colue** [Zrips/CMI#2012]
**Description of issue:**
https://pastebin.com/2Sv7zbXD 
thats the showing of how the ranks are set and i can give access to my server if you need to verify that auto rankup isnt working

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):8.6.6.1 

**Server Type (Spigot/Paperspigot/etc):1.14.3

**Server Version (using `/ver`):1.14.3

**Relevant plugins (Delete if this isn't needed):**

**Comment by Marlej-dev** [comment]
"lp user [playerName] group add gaea" is this a valid command in Lucky Perms?

**Comment by Marlej-dev** [comment]
"lp user [playerName] group add argus"
change it to
"lp user [playerName] parent add argus"
