### ISSUE TITLE
Can't CI players with all numbers for name

### ISSUE THREAD

**Issue by doesnotskate** [Zrips/CMI#2013]
**Description of issue:**
Users who have a name that only consists of numbers cannot have their inventories cleared using /ci (name). It will instead clear the inventory of whoever ran the command.
Example: Admin tries the command /ci 123
Admin's inventory gets cleared while 123's inventory stays in tact.
---

**Cmi Version (using`/cmi version`):** 
8.6.6.1

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot build 124

**Server Version (using `/ver`):** 
1.14.3

**Comment by Zrips** [comment]
Will be fixed with next build
