### ISSUE TITLE
CMI holograms and (maybe) tabs sending a LOT of packets and causing too many packets kick (viaversion)

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#2016]
I noticed a lot of time people are kicked for too many packets when they are close to a CMI holograms after some times using paperspigot 1.8.8 but the problem happen also with 1.13.2,  CMI: 8.6.6.1

**Comment by Zrips** [comment]
CMI holograms are packet based, but packets are been sent to player and not from player to server. There is only one instance for player to send packets to server which would be related to CMI holograms is when you have intractable holograms and player clicks on hologram more times then it would be possible in regular situations. So my guess would be that you have players with hacked client and with kill aura attacking buttons and sending bunch of packets in short time.

**Comment by xion87** [comment]
This happened in these following scenario:
Kitpvp - i have a leaderboard with 4 pages interactive (i got it at center of a map) player reported fighting, they get random disconected  when they are close to spawn.

Factions - i have a some simple holo indicating vip package and one with placeholder saying time played, here some player reported that was  just was afk and close to them and was kicked staying at spawn

Creative: i got a cmi holo interactive at spawn, sometmes when a player login it will be kicked for that, these kick never happen when you are out the range of the holos

**Comment by Zrips** [comment]
So hologram in factions is not intractable? If you would changed game mode to spectator you cant see ghost entity at hologram place?

**Comment by xion87** [comment]
![image](https://user-images.githubusercontent.com/3611852/60965952-742a1100-a317-11e9-8b27-a77dca1d1448.png)
I see this on factions on gm 3

**Comment by Zrips** [comment]
Och that's right, you still have fake armor stands which can be attacked by player with hacked client. This will not processed by CMI but hacked client could think that it might do it. Even tho they are invisible.

**Comment by xion87** [comment]
hacked client, like also legit client? like badlion ecc... ?

**Comment by Zrips** [comment]
Well there are multiple hacked clients with cheats, so its hard to say at this point if it was something with plugin, or was it player with kill aura enabled and logged into server while near some targets and got kicked because he sent bunch of packets

**Comment by xion87** [comment]
also staying 15 block far from the hologram and staying afk?  :/

**Comment by Zrips** [comment]
Tested out with 22 holograms, each has 20 lines which updates every tick. No issues with login or standing near them. So something strange is going on here. Maybe your anticheat plugin messes things up? What exact message players getting when they get kicked for too many packets?

**Comment by xion87** [comment]
the tooo many packet is from viaversion, i have to disable that  for now, the default limit is 800pps, but i happen sometimes i have peak of 3000 pps when close to hologram

**Comment by Zrips** [comment]
it could be due to some lag from players or server end which forces player to push out bunch of packets in one go. But without attempt to interact with holograms from player side, this should not increase packet count.

**Comment by xion87** [comment]
Solved was caused by bungee packet spam, that was patched recently
