### ISSUE TITLE
Big Button enables itself on all holograms

### ISSUE THREAD

**Issue by doesnotskate** [Zrips/CMI#2018]
**Description of issue:**  
After setting up holograms and using the editor to make sure big button is disabled, the option will enable itself for all holograms upon server restart or plugin reload.
---

**Cmi Version (using`/cmi version`):** 
8.6.6.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper build 124
**Server Version (using `/ver`):** 
1.14.3

**Comment by Zrips** [comment]
Will be fixed with next build
