### ISSUE TITLE
Request: Authentication Layer

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#202]
I wish there was an easy way to add it for some players that have issues with siblings using their accounts, especially, but not limited to Staff accounts. It would be self-managing for the player to activate it if they want it.

The player with this enabled, would be denied all chat and commands until they authenticate. Only /auth and /helpop and maybe /mail command would be allowed. So player could get help if their password doesn't work or whatever. Once they do /auth <password> and it checks out, then they can use the account normally as if it was not enabled, until they disconnect and log back in, having to /auth again.

```
#player level commands (examples)
/auth enable <newpassword> = Enables auth requirement when they login to use account with pass.
/auth disable <password> = Disables auth requirement for the account
/auth <password> = Authenticates their session if it has been enabled

#admin level commands (examples)
/auth enable <newpassword> <playername>
/auth disable <playername>
/auth status <playername> = shows if player has it enabled and date/time it was enabled
```

**Comment by CloudeLecaw** [comment]
if i understood this right this "auth" system is just usefull for onelinemode=false servers right? 🥉 

but still sounds nice for a server to need no extra authme plugin :)

**Comment by MCTyler** [comment]
I call it LogOut of the Computer... Really Guys?

**Comment by LogGits** [comment]
This is beyond the scope of the project. This type of thing can be achieved with a good permissions system and a spigot authentication plugin.
