### ISSUE TITLE
Custom Recipes not loading after server restart in 8.6.5.5+ (only happening in 1.14.3+)

### ISSUE THREAD

**Issue by DXUltimate** [Zrips/CMI#2023]
**Description of issue:**
Recipes are not loading on server load, requiring a customrecipe "update" without changing anything to fix them again.
---
**Cmi Version (using`/cmi version`):** 
8.6.5.5+ (is an issue from this version on, still is an issue on 8.6.6.1)

**Server Type (Spigot/Paperspigot/etc):** 
paper-120+ (currently on paper-124)

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-124 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

So I'm not sure what else to say about this, but whenever I perform a restart on the server, the custom recipes get unloaded and I have to go into the custom recipe creator, and "update" them in order for them to work again. I'm not sure why it does this happening, but, here's a report to investigate. =)

Potentially this could be a duplicate of #1084, but I'm not using MobHunting on my server, so it could be another conflict with something else. Please note this ONLY happened once 1.14.3 came out in paper/spigot. I offer my plugins list to help as well;

Plugins (42): Additions, AdvancedTimber, BetterRTP, ChestSort, CMI, CrateReloaded, CrazyAuctions, DiscordSRV, EnchantmentSolution, EnjinMinecraftPlugin, EpicCraftingsPlus, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, GadgetsMenu, HackedServer, HeadDatabase, Jobs, LockettePro, LogBlock, LuckPerms, Multiverse-Core, MythicMobs, NoSpawnerChange, PlaceholderAPI, QuickShop, ServerRestart, SimpleBackup, StaffChat, SuperbVote, TicketManager, TrollBoss, Vault, VeinMiner, ViaVersion*, Votifier, VotingPlugin, WorldEdit, WorldEditCUI, WorldGuard

EpicCraftings should have nothing to do with it, since it doesn't use the vanilla bench at all.

**Comment by Zrips** [comment]
Could you provide actual recipes.yml file or atleast recipe which failed to load? As currently after some testing all types of recipes are working after server restart. So maybe its related to particular type of ingredients or outcome. But i will need exact example which failed for you.

**Comment by DXUltimate** [comment]
Yup, sure thing.

https://pastebin.com/RT5Wym0y - recipes.yml

Most things are regular items, with the exceptions of compressed blocks. Those are just enchanted blocks. Note these recipes are registered in the custom recipes, but for whatever reason, they just don't appear until I "update" them. They, as in, all of the recipes listed in the yml here.

**Comment by Zrips** [comment]
Could it be that some other plugin removes them? Did you tried to run CMI without any other plugin to see if recipes are been loaded? Because tested out your recipes and they are loaded and i can craft them without any issues

**Comment by DXUltimate** [comment]
I will figure this out and get back to you about this. 

Thank you for all of your hard work on CMI over the years. I've been using it forever so please continue to update this plugin in the future. =D
