### ISSUE TITLE
CMI Nicknames not working properly - Urgent Help Needed

### ISSUE THREAD

**Issue by EnderGamingFilms** [Zrips/CMI#2025]
**Description of issue:**
I switched to this plugin fro essentials and I was using %essentials_nickname% for chat nicks to shown up. CMI works but if the player has never used nick they will not have a name in chat. Also if you do /nick off your name will also disappear in chat. No help from the discord so im posting here.
---
https://imgur.com/6VKW1o4
**Cmi Version (using`/cmi version`):** 
8.6.6.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper-Spigot
**Server Version (using `/ver`):** 
1.14.3

**Comment by the456gamer** [comment]
What chat plugin are you using?
Whatever it is, set it to display displayname

**Comment by Zrips** [comment]
@EnderGamingFilms You will need to use %cmi_user_display_name% if your chat plugin supports PlaceHoderAPI. If you are using CMI chat handling, then double check what you have set for DisplayName -> Format in config file and for Chat-> GeneralFormat or Chat -> GroupFormat which should contain {displayName} if you want to display players display name.

**Comment by EnderGamingFilms** [comment]
Alright display_name worked thanks.
