### ISSUE TITLE
PlayerChunkMap Error

### ISSUE THREAD

**Issue by JaydenJinx** [Zrips/CMI#2026]
**Description of issue:**
Check out the error. Doesn't cause any issues, just thought I'd report it.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://pastebin.com/HhvMjx44

**Cmi Version (using`/cmi version`):** 
8.6.5.1
**Server Type (Spigot/Paperspigot/etc):** 
Spigot 1.14.3

**Comment by Zrips** [comment]
This was fixed with latest builds
