### ISSUE TITLE
Recent CMI version will disable fly at login for any creative player

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#2027]
I noticed in recent versions of cmi, creative player will keep to have the fly disabled when he they login as creative mode, and they have to do /fly for enable it again, and it will work until the server restart. Happen in both test server and creative server running the 8.6.6.1
I am using mysql

**Comment by Zrips** [comment]
Server version? Don't forget to include server version when making a ticket.

**Comment by xion87** [comment]
it happen in both paperspigot 1.8.9 and 1.13.2

**Comment by Olexorus** [comment]
Happens for me to on Paper-127 1.14.3 and CMI 8.6.6.1

**Comment by Zrips** [comment]
@Olexorus reload or restart?

**Comment by Olexorus** [comment]
Reload

**Comment by xion87** [comment]
I noticed when i do /fly on sql table the Fly coloumn keep to stay to 0 instead to turn into 1

**Comment by xion87** [comment]
I confirm that i solved the problem turning off  these two option (i think it was forceloadonlogin option 
ForceSaveOnLogOut: false
# EXPERIMENTAL. This is not fully tested yet and some minor issues can happen when ussing on bungee network
# Player data will be loaded from database each time player joins server
# When its set to false then precached data will be uses which is more efficient
ForceLoadOnLogIn: false
