### ISSUE TITLE
Players lose access to their warps on server restart

### ISSUE THREAD

**Issue by JaydenJinx** [Zrips/CMI#2029]
**Description**
Owner of ALL warps changes to "Server" upon restart. Players can not delete their warp because they don't have ownership, but the warp still counts towards their max.

**Cmi Version (using`/cmi version`):** 
CMI 8.6.5.1

**Server Type (Spigot/Paperspigot/etc):** 
Spigot 1.14.3

**Comment by JaydenJinx** [comment]
It appears that player data just isn't saved. Here's my warps file: https://pastebin.com/6vr8Re8e

**Comment by JaydenJinx** [comment]
"test" warp is my own. It shows the owner as "JayJayJay175", but on restart, it won't.

**Comment by Zrips** [comment]
Next update will contain fix for missing creator for warps
