### ISSUE TITLE
HomeBeds don't work

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#2031]
on 1.14.3 paperspigot, and having the feature bedhome enabled, it don't work, clicking/sleeping on   the bed don't do nothing and don't create any homes regardess the enabled option. cmi 8.6.6.1 and mysql
Homes:
  # Open gui when using /cmi home command if you have more then one home in your saved list
  Gui: false
  # Homes groups to define max amount homes player can have. Permission: cmi.command.sethome.[groupname]
  # If players home group if not find then amount will be set to 1
  # To have unlimited homes use cmi.command.sethome.unlimited permission
  # In adition to this you can use simple numeric permission node cmi.command.sethome.[number] which will define max number of homes player can have
  Groups:
    Newbie: 2
    Advanced: 3
    Vip: 5
  # Requires cmi.bedhome permission node
  # When set to true by interacting with bed, regular home location will be created
  # When set to false vanilla bed home location will be set
  BedInteraction: true
  # Removes bed location when home location was created by clicking on that bed
  RemoveBedLocationOnBedBreak: true
  # When enabled, plugin will check if player can break block in that area before creating new home location
  # This allows to prevent setting homes in protected areas
  # Can be bypassed with cmi.command.sethome.bypass
  CheckBlockBreak: false
  # Name for default home location. By default its "Home"
  DefaultName: Home
  # Defines what characters you can use in your home names
  NameRegex: /([\p{L}-]+)/ug
  # When set to true home icons in GUI will try to pick real blocks from that location for easy way to see which is which
  # When set to false, then random wool block will be used
  PickRealBlock: true

**Comment by Zrips** [comment]
As that option indicates, you need cmi.bedhome permission node
