### ISSUE TITLE
Could not use /cmi skin

### ISSUE THREAD

**Issue by Dat225** [Zrips/CMI#2032]
**Question: **
I tried to set skin for player. However, it did not change anything.
Do I have to do any special setup for it to work? I have a network with bungeecord and paperclip servers. CMI is installed on the paperclip servers. I tried to change and wait for a few days as well but nothing happened.

Thanks,

**Comment by Zrips** [comment]
Sadly skins doesnt work on bungee network based servers, that one requires a different approach and will be working in the future to have this compatibility.
