### ISSUE TITLE
ranks.yml "MonsterKills" 

### ISSUE THREAD

**Issue by Nesseley** [Zrips/CMI#2034]
**Question: **
Can I make it so it checks for more than one mob?
- "MonsterKills:cow:500" I want to check kills for both cow and sheep. And add them together. Is this possible?

Example: - "MonsterKills:cow,sheep:500"

**Comment by CloudeLecaw** [comment]
No that not possible
you can make checks for cow and sheep and have both as requirments like 10 cows and 20 sheeps needed to be killed.
but you can add them like 10 cows/sheeps  must be killed.
but you could ask for animals killed... but this would not only inclue cows and sheeps...
