### ISSUE TITLE
Big Button enabling itself - now only on reload if server hasn't restarted yet

### ISSUE THREAD

**Issue by ghost** [Zrips/CMI#2037]
**Description of issue:**  
After setting up holograms and using the editor to make sure big button is disabled, the option will enable itself for any holograms that have had big button turned off since the last restart. I reported this issue a few days ago and it no longer occurs on server restart, only on reload, only if you haven't restarted the server since turning off big button on your specified holograms. Any holograms that already have big button off since before the last restart are now unaffected.

---

**Cmi Version (using`/cmi version`):** 
8.6.7.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper build 126
**Server Version (using `/ver`):** 
1.14.3

**Comment by Zrips** [comment]
Latest CMI build should record bigButton state into file, before this it was not saved properly so any changes have been temporary. Tested out to make sure that it does work as it should and it seems to be working correctly now. Setting bigButton to false will save that state. You might need to reset this state for holograms you want to have small button, but it should work correctly now
