### ISSUE TITLE
PlayerWakeUpEvent

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#2038]
**Description of feature/improvement request:**
I need an event to be able to hook into CMI's sleep function. Specifically i need to know when the sleep is over because of a successful nights sleep.

---
### Detailed explanation of what it should do, when and in what situation: ###
This event should say when a player wakes up.
### Basic explanation as to why this feature is needed and/or useful to have: ###
I need this event to be able to hook into CMI's sleeping for a custom project.

**Comment by Zrips** [comment]
Check for PlayerBedLeaveEvent at the morning times, CMI doesn't kick players from the beds when morning comes, server does that automatically.
