### ISSUE TITLE
Vanish Nameplate Update

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#2039]
**Bug:**
If you vanish and unvanish your nameplate will not update, color stays white until login without being vanished before you logout.

**Request:**
When in vanish can you have a option to display a message on the action bar stating "You are vanished" repeatedly? Obviously this is for helping the user know when vanished. :) 

**CMI:** 8.6.5.5
**Spigot:** 1.13.2

**Comment by HomeLandingsDE** [comment]
you can use the Vanisheditor - there are many settings and there you will also find the option with the Bossbar message "you are invisible"

**Comment by SirGoldman-git** [comment]
This vanish bug is still a issue on 1.14.4.

**Comment by Zrips** [comment]
This got fixed couple versions back
