### ISSUE TITLE
Bug: Update 7.6.3.0 Breaks chat format

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#204]
After the update players have had issues with the "[link}" catching spacing errors when they type. When I set ClickHoverMessages to false all preset chat color and formatting breaks. This wasn't an issue with 7.6.2.0

**Comment by digitalcrowd** [comment]
Issue remains in 7.6.3.1 as well. I was just going to report this:

This is a result of:
<img width="801" alt="screen shot 2018-04-04 at 3 06 03 pm" src="https://user-images.githubusercontent.com/337332/38331869-1f3162fc-381a-11e8-8faa-022eafe502a2.png">

Typing this:
<img width="342" alt="screen shot 2018-04-04 at 3 08 28 pm" src="https://user-images.githubusercontent.com/337332/38331877-2529bd12-381a-11e8-9aba-3452a97b22d4.png">

**Comment by LogGits** [comment]
Good catch, this is because the regex setup thinks it is a valid URL.

**Comment by Zrips** [comment]
Yea, good find, will make regex more picky while detecting links in chat. in next build will be fixed.
