### ISSUE TITLE
Increases all droprates by lootingrate percent per looting level when a enchanted weapon is used

### ISSUE THREAD

**Issue by 1425115471** [Zrips/CMI#2047]
Increases all droprates by lootingrate percent per looting level when a enchanted weapon is used。

**Comment by 1425115471** [comment]
I really hope your (CMI) has a function.

(LOOT_BONUS_MOBS) Enchantment increases the chance of falling head。
Increases all droprates by lootingrate percent per looting level when a enchanted weapon is used.

I personally sponsor you for 30. Can you add this feature?
So I can uninstall the PlayerHeads plug-in.

**Comment by Zrips** [comment]
This got implemented couple versions back. You can have bonus head drop chance depending on weapon enchant level.
