### ISSUE TITLE
Economy Balance Log

### ISSUE THREAD

**Issue by Ash10744** [Zrips/CMI#2049]
**Description of feature/improvement request:**

A command that's adds onto the economy commands you have that basically displays all the transactions the player has done.
(/cmi money log (playername/self)

---
### Detailed explanation of what it should do, when and in what situation: ###

Basically it will allow people to track scamming if it ever occurred, and also allow players to provide follow up proof of a transaction they have done.

### Basic explanation as to why this feature is needed and/or useful to have: ###

More moderation tools within the server, and allows for players to see their previous transactions.

Thank you for reading <3

**Comment by MrMorganCz** [comment]
Basically, it already exists, it's the moneyLog.yml file, and you need to enable LogEnabled: true in the configuration file

**Comment by Ash10744** [comment]
Is there an in game command to display it in game? That's what I wanted to request if not
