### ISSUE TITLE
Doubt townyChat/placeholders 

### ISSUE THREAD

**Issue by Sakanas** [Zrips/CMI#2051]
How does% cmi_user_rank% work in townychat?
I tried that way but it did not work.
`global: '{channelTag} %cmi_user_rank% {townytagoverride}{townycolor}{permprefix}{townyprefix}{modplayername}{townypostfix}{permsuffix}&f:{msgcolour} {msg}'`

**Comment by Zrips** [comment]
If towny chat doesn't translate PlaceholderAPI placeholders, then it will not work. Simple as that.
