### ISSUE TITLE
/cmi recipe has outdated recipes in 1.14

### ISSUE THREAD

**Issue by Flexxxxx** [Zrips/CMI#2054]
**Description of issue:** Recipes are not accurate to as 1.14. For example, it say to use bonemeal, sand, gravel, but with the 1.14 update, it's been change to white dye, sand and gravel.

---

**CMI Version:** 8.6.5.4 BungeeCord -> 8.6.7.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot (git-paper-121)
 
**Server Version (using `/ver`):** 1.14.3

**Comment by Zrips** [comment]
Recipes are taken directly from server database of items, CMI by itself doesn't contain any hardcoded recipes
