### ISSUE TITLE
CMI and Luckperm Prefix issue

### ISSUE THREAD

**Issue by HarmingBird** [Zrips/CMI#2055]
I am currently using Luckperms are my permissions manager on my sever. With that i also have CMI. Every-time i load CMI it will remove all prefixed and suffix from players/group
Please see photos below

![2019-07-14_19 59 09](https://user-images.githubusercontent.com/52881408/61182424-25131180-a672-11e9-9896-f62a849ee355.png)

**Cmi Version (using`/cmi version`):** 
8.6.7.1
**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
1.8-r0.1-SNAPSHOT
**Relevant plugins (Delete if this isn't needed):** 
![2019-07-14_20 00 23](https://user-images.githubusercontent.com/52881408/61182422-1d536d00-a672-11e9-9abd-05e35d5a670b.png)

**Comment by Zrips** [comment]
If you have CMI chat enabled, you will need to set it properly which would include players prefix and suffix with appropriate color codes. Or you can simply disable chat handling and leave it to be handled by another plugin entirely.

**Comment by ayushgameretawah** [comment]
what is the prefix to show rank in tab

**Comment by ayushgameretawah** [comment]
> 

what is the prefix to show rank in tab

**Comment by mrfloris** [comment]
> > 
> 
> what is the prefix to show rank in tab

I have given you the answer here; https://github.com/Zrips/CMI/discussions/6399#discussioncomment-1708714 and I have warned you to not spam here: https://github.com/Zrips/CMI/discussions/6386#discussioncomment-1708719
