### ISSUE TITLE
LootMobBonus lv grade

### ISSUE THREAD

**Issue by 1425115471** [Zrips/CMI#2058]
Hope that the original head of the (wither_skeleton) drop can also be affected.
--------------------
customHeads.yml
LootMobBonus:
  Enabled: true
  Lvl1: 0.03
  Lvl2: 0.06
  Lvl3: 0.09
  Lvl4: 0.12
  Lvl5: 0.15
  Lvl6: 0.18
  Lvl7: 0.21
  Lvl50: 1.5
-------------------
config.yml
      LootBonus:
        Enabled: true
        Lvl1: 1
        Lvl2: 2
        Lvl3: 3
        Lvl4: 4
-----------------
Excuse me, the author.
Is it more than lv3?
It won't work.
I hope that you can achieve more than lv3 can also work

**Comment by Zrips** [comment]
Was added with latest build
