### ISSUE TITLE
Question/Issue

### ISSUE THREAD

**Issue by KeyurNaidu** [Zrips/CMI#2059]
**Description of issue or feature request:**
Hello! I have recently installed CMI, however, is it disabling my suffix/prefix plugin (Permission plugin)? The suffixes created by that plugin doesn't appear anymore, only the nick! The permission plugin I have is luckperms, is there a way I could enable my suffix/prefix again and get it to work without CMI getting in its way? 

Many Thanks,
Keyur

---
**Cmi Version (using`/cmi version`):**  8.61.71

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot 

**Server Version (using `/ver`):**  GIT-Paper 616 (MC: 1.13.2)

**Comment by CoolGiy69** [comment]
I cannot use My LuckPerm At all it completely stopped all of my perms to my server i can't even OP myself

**Comment by colue** [comment]
you op your self from console, and with luckperms add the prefix and things you want to add works on mine

**Comment by Zrips** [comment]
If you have CMI chat handling enabled you have 2 options, ether configure it to include prefix suffix and all the colors or disable chat handling and allow another plugin do that.
