### ISSUE TITLE
Holograms doesn't show up when player hasn't moved

### ISSUE THREAD

**Issue by ColaIan** [Zrips/CMI#2067]
**Description of issue:**
Holograms only shows up when player move

---

**Cmi Version (using`/cmi version`):** 
8.6.7.3

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.14.3-R0.1-SNAPSHOT

**Comment by digitalcrowd** [comment]
This also happens with portal particles and has been an issue for a very long time. Same with animated dynamic signs. Although, holograms haven't been an issue for me.

**Comment by Zrips** [comment]
Should get fixed with next build.
