### ISSUE TITLE
attachcommand with limiteduse won't work

### ISSUE THREAD

**Issue by SeanWalk** [Zrips/CMI#2069]
**Description of issue:**

any attachcommand with limiteduse won't reduce usage when click at player and npc but still complete command

---
i have a one time use paper to get random money

and it won't take off

/cmi attachcommand !limiteduse:1!;;!silent!!cc!cmi money give [playerName] %rand/80000-12000%

https://i.imgur.com/W1mc8Jl.png

---

**Cmi Version (using`/cmi version`):** lastest

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-paper-131(1.14.3)

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
With next update you can use /cmi attachcommand !limiteduse:1!;;!silent!!cc!cmi money give [playerName] %cmi_random_80000_12000%
