### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by tedztar** [Zrips/CMI#2070]
Players can not use /tpa and other commands even tho they have been given the permission for it (cmi.command.tpa)

**Cmi Version (using`/cmi version`):** 8.6.7.3

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** Spigot 1.14.3-R0.1-SNAPSHOT

**Relevant plugins (Delete if this isn't needed):** Ultra Permissions

**Comment by Zrips** [comment]
In general cmi.command is given by default for everyone, cmi.command.tpa is needed, and finally you have cmi.permisiononerror which should be given for everyone and you can see exactly which permission node player is missing when hovering over error message. But as you are using UltraPermissions... Then you will have to add all of them manually... Or simply get better permission plugin, like LuckPerms which doesn't mess things up like that one...

**Comment by CloudeLecaw** [comment]
Well i can agree this point, i also just need to give/add ALL permissions to the groups because my private permisisonplugin does not accept the "given by defaults" ;)..sorry for the missleading information :)
