### ISSUE TITLE
Bungeecord Private Message Problem

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#2071]
**Description of issue:**
Bungeecord private message can't correct receive.
If I /m someone and I can see the message has been sent,
But the receiver in other server can't see the message.

---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
I have enabled the Bungeecord public/private message.

---

**Cmi Version (using`/cmi version`):** 
8.6.7.3
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.14.3

**Comment by Zrips** [comment]
New method involving separate plugin on bungee server should resolve this issue
