### ISSUE TITLE
[Very Low Priority] Multishot is mis-typed in /enchant

### ISSUE THREAD

**Issue by DXUltimate** [Zrips/CMI#2073]
**Description of issue:**
Super Minor issue, should be lowest priority as it is just a simple spelling mistake.
Multishot is mistyped. MULTSHOT where it should be MULTISHOT

**Cmi Version (using`/cmi version`):** 
8.6.7.1+

**Server Type (Spigot/Paperspigot/etc):** 
paperspigot

**Server Version (using `/ver`):** 
paper-127

**Comment by Zrips** [comment]
This should be correct with nevest versions.
