### ISSUE TITLE
Permission not working - cmi.colors.nickname

### ISSUE THREAD

**Issue by QueenAngus** [Zrips/CMI#2075]
**Description of issue:**
Hi there,
I use CMI placeholders to display nicknames in chat, and I have set permission to individual users using LuckPerms that will deny the use of any formatting colors or codes in nicknames. I set it to the player meaning that permission will override any other permissions that may be given in other groups for nickname formatting. I set the permission cmi.colors.nickname.* to false using LuckPerms, which is like negating it with PermissionsEx. The following screenshot shows that:

https://i.gyazo.com/5580a95a8d5272f9e39caa92913e8fd0.png

So with the permission, the player was able to use CMI nicks to set their nickname with bold, colors and underline as shown in the screenshot. I tried many different permissions such as negating cmi.colors.nickname.bold etc but none worked. I think the permission does not work properly. 

---

**Cmi Version (using`/cmi version`):** 
8.6.7.3
**Server Type (Spigot/Paperspigot/etc):** 
BungeeCord - All servers spigot 1.13.2
**Server Version (using `/ver`):** 
1.13.2
**Relevant plugins (Delete if this isn't needed):**
CMI

**Comment by omgitsAngus** [comment]
Also added cmi.colors.publicmessage.* false and people can still use colors, bold etc in public chat.

**Comment by omgitsAngus** [comment]
# If set to true then nickName will be filtered from color codes when player changes it
    # cmi.colors.nickname.[colorName]
    NickName: true

I have set this in my config, however now it has made it so all players cannot do any colors.

https://gyazo.com/7b515aade21d04b4d7ae54bb123ed020
https://gyazo.com/2b6fb81df08d69fb7dc43920c26a6865

I gave them all of these permissions and still no colors can be done at all.

https://gyazo.com/3a66b90544a268eb8b557e2ea71d54de

(Chat color is handled by another plugin, though players can still use color codes in chat unless I set it to filter in the config, then they cannot use them at all which is what I want but still adding cmi.colors.publicmessage.red does not allow them to use &4 in chat)

**Comment by Zrips** [comment]
Player doesn't have access to cmi.colors.[type].[colorname] permission nodes by default, so you must have given them at some point to the players. And negating them could be related to that same issue. If negation comes before direct given access to that permission node then it will allow to use it. In general check your permission plugin setup and remove any access to nickname colors and then give them out to those who should be able to use them.

**Comment by Zrips** [comment]
Same goes for cmi.colors.publicmessage.* By default player doesn't have access to it. So if you give out cmi.colors.publicmessage.* to everyone and then tried to negate it at a different place, you will have issues with that setup.

**Comment by Zrips** [comment]
&4 is darkred and not a red. You can check names with /colorlimits and hover over specific color code to get its name
