### ISSUE TITLE
/mute not Blocking Private Messages

### ISSUE THREAD

**Issue by hamcoremusic** [Zrips/CMI#2076]
**Description of issue:**
As reported by one of my Moderators, the person they muted was still able to send a private message to them.

I have the option to block private messages while muted enabled but it still went through.

---

**Cmi Version (using`/cmi version`):** 
Latest as of July 18th
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.14.3

**Comment by Zrips** [comment]
Go to config file and under Mute.DenyPrivateMessages set to true. Unless you are using different plugin to send private messages, then it will not really help and with current CMI state you cant prevent particular command usage while you are muted. Which could be added if that is really needed.
