### ISSUE TITLE
setworth

### ISSUE THREAD

**Issue by colue** [Zrips/CMI#2079]
**Description of issue:**

i set the worth in game and then the server restarts and its gone or have to reload the plugin
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 8.6.7.5

**Server Type (Spigot/Paperspigot/etc):** spigot

**Server Version (using `/ver`):** 1.14.3

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Will be fixed with next update.
