### ISSUE TITLE
Question for launch (or request?)

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#208]
Hey just wondering how to set up the launch like the gif? 
https://proxy.spigotmc.org/11a937b14b3b06bd00705d9263d8a0bc3c6cfcfe?url=http%3A%2F%2Fltcraft.lt%2Fwp-content%2Fuploads%2F2018%2F03%2F2018-03-23_11-55-36.gif
^That one

I got the command to launch but how do you set it like that via plugin? 

Anddd if thats not a thing can we get that added?

**Comment by LogGits** [comment]
This simply uses /cmi portals to run a command that performs cmi launch on the player. Zrips has it setup so that you land in another portal that launches you again into another portal etc.

**Comment by Zrips** [comment]
What @LogGits said :) Simply utilize portals to perform /cmi launch [playerName] {variables} and launch player to general direction you want, i did added option to launch player to particular location, like loc:115:123:245 which will always point to same block, tho launch power can be not enough but you can always adjust by what you want with p:4 or something like this. Point is that you have portals (aka area of effect) to play around and achieve allot of things you want.
