### ISSUE TITLE
CMI causing issues with AnimatedNames

### ISSUE THREAD

**Issue by starwarsfreak219** [Zrips/CMI#2081]
**Description of issue:**
Video of the issue: 
https://www.youtube.com/watch?v=eGpGD9AnC-c

Description:
I am currently migrating to 1.12.2 from 1.8. I have a minigames plugin called Paintball, and when the server is on 1.8.8, everything works fine. When a player joins on 1.12.2, everything seems fine, until the match ends or the player leaves the match. I use a plugin called AnimatedNames, which will display a prefix and suffix in the tab list and above the players name. When a player joins the arena and plays the Paintball gamemode, it works fine, but when the gamemode ends, or a player leaves, it seems to disable AnimatedNames for the specific player. I contacted the developer of AnimatedNames, and with the command **/animatednames debug** we have determined that CMI is the route cause. I tested the plugins AnimatedNames and Paintball without CMI, and it worked flawlessly. I noticed that some teams are created, which seem to be causing the interference with AnimatedNames. These two teams are CMICol and CMINP1. Here is a link to the debug info from AnimatedNames: http://paste.ubuntu.com/p/5GR6PhyV4M/

This seems to only happen to the players that are in an arena and the game ends, or the player is in an arena or a arena lobby, and leaves. It doesn't affect any other players that are on the server. Do you think you could look into this? Thanks in advance!

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

Modules.yml: https://pastebin.com/m2WU1FxP
config.yml: https://pastebin.com/WGrzRgxj
tabList.yml: https://pastebin.com/T425NtLH

---

**Cmi Version (using`/cmi version`):** 
8.6.7.5
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.12.2
**Relevant plugins (Delete if this isn't needed):**
**AnimatedNames(version 7.2.0):** https://www.spigotmc.org/resources/animatednames.2175/
**MVdWPlaceholderAPI(version 3.0.1):** https://www.spigotmc.org/resources/mvdwplaceholderapi.11182/
**Paintball(version 2.0.4):** https://www.spigotmc.org/resources/1-day-50-off-epic-paintball-new-crackshot-support-60-5-star-reviews-8-games-in-1.20276/

**Comment by Zrips** [comment]
Option to disable scoreboard teams will be added with next update, so change that and we will avoid any team manipulations which should solve your issue. Tho this will disable things like name plates, glow color or player collision commands
