### ISSUE TITLE
cmi money take bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#2082]
if player money 0 , use /money take 1000 , still can take
There should be an order for payment
Use for: some menu plugins

**Cmi Version (using`/cmi version`):** 8.6.7.5

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.13.2

**Comment by Zrips** [comment]
It doesn't take money, it will simply inform about changed balance, even tho it did not changed. We make that in case balance doesn't change, we will not show feedback message. next version.
