### ISSUE TITLE
Sleep Required Announcement

### ISSUE THREAD

**Issue by FestusDM** [Zrips/CMI#2084]
Ability to have a setting where player will be notified the amount of players that need to sleep before night speeds up.

---
As soon as 1 player sleeps, a message will show up inside all online player's chat box stating how many more players are needed to sleep in order to speed through nighttime. 

Useful for players to know requirements to sleep based on amount of players online.

**Comment by Zrips** [comment]
Will add this option, tho will have to limit broadcast messages to something like 30 seconds in between them, just to avoid spam
