### ISSUE TITLE
Prefix bug, chat disappears

### ISSUE THREAD

**Issue by DarkFort** [Zrips/CMI#2085]
Prefix bug, chat disappears
A bug occurs when there is a character in the prefix '%'  https://i.imgur.com/PLbMebH.jpg

---

https://paste.dizorin.ru/lJUDVCb
```
######################
## REPLACE WITH ERROR ##
######################
```

```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
 CMI: 8.6.7.5 BungeeCord                         
[09:21:18 INFO]: Paper(639) 1.13.2-R0.1-SNAPSHOT                
[09:21:18 INFO]: Vault: 1.7.2-b${env.TRAVIS_BUILD_NUMBER}(CMIEInjector) 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**
MyPrefix

**Comment by Zrips** [comment]
This is issue with minecraft itself not handling properly items with color codes in them.
