### ISSUE TITLE
Plugin will not load

### ISSUE THREAD

**Issue by GrayChief345412** [Zrips/CMI#2086]
CMI will not start at all and gives this error

---

> [12:19:05] [Server thread/INFO]: [CMI] Enabling CMI v8.6.7.3
> [12:19:06] [Server thread/INFO]: [CMI] 47 Enabled and 0 Disabled modules
> [12:19:06] [Server thread/INFO]: [CMI] PEX permission plugin will be used
> [12:19:06] [Server thread/INFO]: [CMI] Loaded (46) regular alias into memory. Took 7ms
> [12:19:06] [Server thread/INFO]: [CMI] Loaded (1) custom text's into memory. Took 1ms
> [12:19:06] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/mysql/jdbc/StringUtils
> [12:19:06] [Server thread/WARN]: at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:313)
> [12:19:06] [Server thread/WARN]: at java.sql.DriverManager.getConnection(DriverManager.java:664)
> [12:19:06] [Server thread/WARN]: at java.sql.DriverManager.getConnection(DriverManager.java:247)
> [12:19:06] [Server thread/WARN]: at com.Zrips.CMI.Modules.DataBase.DBConnectionPool.getConnection(DBConnectionPool.java:34)
> [12:19:06] [Server thread/WARN]: at com.Zrips.CMI.Modules.DataBase.DBDAO.<init>(DBDAO.java:486)
> [12:19:06] [Server thread/WARN]: at com.Zrips.CMI.Modules.DataBase.DBSQLite.<init>(DBSQLite.java:36)
> [12:19:06] [Server thread/WARN]: at com.Zrips.CMI.Modules.DataBase.DBManager.startSqlite(DBManager.java:142)
> [12:19:06] [Server thread/WARN]: at com.Zrips.CMI.Modules.DataBase.DBManager.start(DBManager.java:80)
> [12:19:06] [Server thread/WARN]: at com.Zrips.CMI.Config.load(Config.java:671)
> [12:19:06] [Server thread/WARN]: at com.Zrips.CMI.Config.load(Config.java:653)
> [12:19:06] [Server thread/WARN]: at com.Zrips.CMI.CMI.onEnable(CMI.java:1374)
> [12:19:06] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> [12:19:06] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
> [12:19:06] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
> [12:19:06] [Server thread/WARN]: at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
> [12:19:06] [Server thread/WARN]: at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
> [12:19:06] [Server thread/WARN]: at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380)
> [12:19:06] [Server thread/WARN]: at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
> [12:19:06] [Server thread/WARN]: at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
> [12:19:06] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
> [12:19:06] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
> [12:19:06] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710)
> [12:19:06] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641)
> [12:19:06] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481)
> [12:19:06] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
> [12:19:06] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [12:19:06] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
> [12:19:06] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
> [12:19:06] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
> [12:19:06] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
> [12:19:06] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
> [12:19:06] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910)
> [12:19:06] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903)
> [12:19:06] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
> [12:19:06] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887)
> [12:19:06] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820)
> [12:19:06] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [12:19:06] [Server thread/INFO]: [CMI] Unable to connect to the database: com/mysql/jdbc/StringUtils
> [12:19:06] [Server thread/ERROR]: Error occurred while enabling CMI v8.6.7.3 (Is it up to date?)
java.lang.NullPointerException: null

---

CMI version 8.6.7.5 (happens on older versions too)

Server version spigot

1.14.4R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Issue while loading SQLite type database. Make sure that your Host supports this format or switch to MySQL format.
