### ISSUE TITLE
Cats Being Replaced By Vindicators Issue

### ISSUE THREAD

**Issue by MrApocalyptic** [Zrips/CMI#2087]
Description Of The Issue - Pretty much when you type /cmi spawnmob cat it summons a vindicator instead of an actual cat, also in customheads when killing a cat it drops a vindicator head instead of a cat head.

**Cmi Version - 8.6.7.5** 

**Server Type - Paper(134) 1.14.3-R0.1-Snapshot**

**Comment by Seeroh** [comment]
I had the same issue, reported here: Zrips/Jobs/#480

**Comment by Zrips** [comment]
Well in minecraft you don't have cat's, you have ocelots. So plugin tried to find one by name, when it failed found best match which was vindi**cat**or. Will fix this one so we can spawn ocelots when we need a cat.

**Comment by Seeroh** [comment]
https://minecraft.gamepedia.com/Cat

Cats are a different entity than Ocelots in 1.14
