### ISSUE TITLE
Enchantment Book Giving

### ISSUE THREAD

**Issue by BiGUNMAN** [Zrips/CMI#2088]
**Description of issue:**
Command: `/cmi give enchanted_book 1 e (enchantment)`

Gives an abnormal enchantment book with &b as the color code instead of &e. This breaks normal enchantment books (and their use on anvils) as well as illegal enchantment books which some plugins support anvil-ing (because the NBT is different with the different item name).

Sidenote: On 1.12.2, you can't give out mushroom cow eggs - they default to a bat egg: `/cmi give spawn_egg:mooshroomcow` (the mushroom cows however do work on 1.13).
Note: I've tried multiple different ways of spelling the mob name.

---

**Cmi Version (using`/cmi version`):** 8.6.7.5

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper 1.13.2: 639

**Comment by Baktus79** [comment]
#2112 

I guess this ties in with my report as well

**Comment by BiGUNMAN** [comment]
I would guess Scavenger doesn't work for the reason listed above.

**Comment by Zrips** [comment]
Will be fixed with next update
