### ISSUE TITLE
Error in console.

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#209]
Latest CMI version with spigot 1.12.2

`
ERROR Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization 04.04 21:47:19 [Server] INFO java.lang.IllegalArgumentException: unknown world 04.04 21:47:19 [Server] INFO at org.bukkit.Location.deserialize(Location.java:612) ~[spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161] 04.04 21:47:19 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161] 04.04 21:47:19 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161] 04.04 21:47:19 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161] 04.04 21:47:19 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:443) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:519) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:443) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:519) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8] 04.04 21:47:19 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183) [spigot-latest.jar:git-Spigot-b6ecf3b-fb423b8]
`

**Comment by 0xC1A551C** [comment]
Also to add, getting "internal error occured ... " when running /cmi portals. Portals gui seemed to be messed up & buggy too. Changing particle amount caused there to be no particles, yet it shows 200. Activation range is not working at all - numbers not changing.

**Comment by 0xC1A551C** [comment]
The error seems related to CMI somehow, and happens whenever CMI is loaded, portal commands are ran, ect.

`INFO [CMI] Enabling CMI v7.6.3.2 05.04 19:38:38 [Server] ERROR Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization 05.04 19:38:38 [Server] INFO java.lang.IllegalArgumentException: unknown world 05.04 19:38:38 [Server] INFO at org.bukkit.Location.deserialize(Location.java:612) ~[paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161] 05.04 19:38:38 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161] 05.04 19:38:38 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161] 05.04 19:38:38 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161] 05.04 19:38:38 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:443) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:519) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:443) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:519) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:38 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183) [paperclip.jar:git-Spigot-b6ecf3b-1daee53]`

-------------------------------

` INFO [CMI] Registering events. 05.04 19:38:45 [Server] ERROR Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization 05.04 19:38:45 [Server] INFO java.lang.IllegalArgumentException: unknown world 05.04 19:38:45 [Server] INFO at org.bukkit.Location.deserialize(Location.java:612) ~[paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:45 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161] 05.04 19:38:45 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161] 05.04 19:38:45 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161] 05.04 19:38:45 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161] 05.04 19:38:45 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:45 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:45 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:45 [Server] INFO at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:45 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:45 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:45 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:373) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:45 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:357) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:45 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:498) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:45 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:45 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:45 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:38:45 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183) [paperclip.jar:git-Spigot-b6ecf3b-1daee53]`

**Comment by 0xC1A551C** [comment]
Then here is another error.


ERROR Could not pass event PlayerJoinEvent to CMI v7.6.3.2 05.04 19:40:08 [Server] INFO org.bukkit.event.EventException: null 05.04 19:40:08 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161] 05.04 19:40:08 [Server] INFO Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v7.6.3.2 05.04 19:40:08 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574) ~[paperclip.jar:git-Spigot-b6ecf3b-1daee53] 05.04 19:40:08 [Server] INFO at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:545) ~[?:?] 05.04 19:40:08 [Server] INFO at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:502) ~[?:?] 05.04 19:40:08 [Server] INFO at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:104) ~[?:?] 05.04 19:40:08 [Server] INFO at com.Zrips.CMI.Modules.EventActions.EventActionManager.performCommands(EventActionManager.java:53) ~[?:?] 05.04 19:40:08 [Server] INFO at com.Zrips.CMI.Modules.EventActions.EventActionManager.performCommands(EventActionManager.java:31) ~[?:?] 05.04 19:40:08 [Server] INFO at com.Zrips.CMI.Modules.EventActions.EventActionListener.PlayerJoinEvent(EventActionListener.java:44) ~[?:?] 05.04 19:40:08 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]

**Comment by Zrips** [comment]
I still need that portals.yml file and what command was performed before last error appeared? Its related to specialized commands.

**Comment by LogGits** [comment]
What world managing plugin are you using @0xC1A551C?

**Comment by LogGits** [comment]
I am assuming this issue was resolved. If you it persists please don't hesitate to make a new issue 🙂
