### ISSUE TITLE
Tag system enhancement

### ISSUE THREAD

**Issue by DaveDevil** [Zrips/CMI#2090]
Actually the tag system is very basic, with "@nickname" getting coloured and a sound heard by the tagged player.

I suggest to add a list of command that will be executed instead of a single sound, so server owners can choose what to do.

We can then add commands like /cmi sound, send a message like "%cmi_tag_sender% is looking for you!" to the player, and some particle effects, or whatever the fantasy suggest to the administrator.

**Comment by Zrips** [comment]
Will add with next update
