### ISSUE TITLE
CMI selection tool

### ISSUE THREAD

**Issue by romerocm** [Zrips/CMI#2091]
**Description of issue:**
Unable to do a selection with the CMI selection tool. (default being the wooden_shovel. Tried doing right/left clicks. I also tried defining it into another item (arrow) and still isn't working).

Been asking on discord for support but unable to confirm if this is an actual bug, but still reporting it just in case.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Selection:
  # Tool id to use for selection actions
  Tool: wooden_shovel
```

---

**Cmi Version (using`/cmi version`):** 
8.6.7.5
**Server Type (Spigot/Paperspigot/etc):** 
Spigot 1.14.3

**Comment by Zrips** [comment]
make sure that you don't have another plugin using same item as selection tool. Simply change to some random item and test it that way. Currently its all working as it should, so something is different with your setup.
