### ISSUE TITLE
/tphere does not work across dimensions

### ISSUE THREAD

**Issue by PsychoLynx** [Zrips/CMI#2092]
Hello! When I am trying to teleport a player from the Overworld dimension to the Nether or The End (or any other direction) using the /tphere command, the player is sent to my coordinates in their current world instead and not the dimension I am in. The /tpa command respects the correct dimension, however. I also tried EssentialsX's tphere-command which works correctly cross-world, so I am fairly confident this is a bug specific to CMI.

**Cmi Version (using`/cmi version`):** 
8.6.7.5 Bungeecord

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper(137) 1.14.4-R0.1-SNAPSHOT

**Relevant plugins (Delete if this isn't needed):**
Multiverse-Core Version: 4.0.0-b766

**Comment by Zrips** [comment]
tested out with 1.14.4 and multiverse plugin, with custom/vanilla nether and end worlds, both of them teleported player to correct world/dimension and position. So this is strange issue you are having. Did you tested it without any other plugin but only multiverse and CMI?

**Comment by PsychoLynx** [comment]
I did not. My apologies, I have had little energy as of late and II assumed that because EssentialsX tphere worked that CMI was bugged. I will try to find out what is causing the problem on my server and if not, I'll just stick to Essentials for teleport commands.

**Comment by PsychoLynx** [comment]
Okay. I found out that the actual tphere command works cross-world in CMI. However, I had redirected the /cmi tphere -command to /cmi tpohere in order to force teleport by default. The /tpohere command seems to be the one not obeying worlds.

**Comment by Seeroh** [comment]
CMI plugin version: 8.6.8.4
Server version: Paper(152) 1.14.4-R0.1-SNAPSHOT

Confirming that /tpohere does not work cross dimension.

**Comment by Zrips** [comment]
Should be working correctly now with latest build

**Comment by PsychoLynx** [comment]
Thank you kindly!
