### ISSUE TITLE
Any Armor Peace As Helmet

### ISSUE THREAD

**Issue by xxJinxedxx** [Zrips/CMI#2093]
**Description of issue:**
You can set any armor peace as a Helmet.
It will count the armor amount as it is, but you can put it on your head~

---

**Cmi Version (using`/cmi version`):** 8.6.7.5

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** 1.8.8-R0.1-SNAPSHOT

**Comment by the456gamer** [comment]
Feature of /hat, to put items on head naturally  (like a helmet)

**Comment by xxJinxedxx** [comment]
> Feature of /hat, to put items on head naturally (like a helmet)

Oh yeah, alright. I just didn't realize that it was build in like that.
Thanks.
