### ISSUE TITLE
/rankup particle effects should be able to be disabled or modified

### ISSUE THREAD

**Issue by Seeroh** [Zrips/CMI#2095]
**Description of feature/improvement request:**

Allow for particle effect on /rankup to be changed or disabled.

---
### Detailed explanation of what it should do, when and in what situation: ###

As it stands, /rankup does the GColumn particle effect
`  GColumn: circle;c:0,255,0;twist;part:5;r:0.75;pitch:90;move:0,0.1,0;rc:-0.02`

But there is no where to change this or disable it, without also disabling all other particle effects within the plugin.

This was brought up in issue #1474, but no change has occurred as of yet.

**Comment by x1p** [comment]
I must agree. I want it to be turned off as well.

**Comment by Zrips** [comment]
Will add option to define specific particle animation with option to set it to empty field to disable it if not needed.
