### ISSUE TITLE
Two portals within a short time - second one does not work for the next few seconds?

### ISSUE THREAD

**Issue by Nachtaktiv77** [Zrips/CMI#2097]
Hey,

Am I doing something wrong? I setup two portals which both perform commands.
If I walk through the first one everything is fine. If I walk through the second one within 2 or 3 seconds nothing happens. If I wait like 15 seconds through the second one it works :)

I don't know what I am doing wrong....

**Comment by Zrips** [comment]
Should be working correctly now with latest build.
