### ISSUE TITLE
Magic Spells plugin is trigging cmi perma fly after logout

### ISSUE THREAD

**Issue by WarmasterCain55** [Zrips/CMI#21]
So we recently discovered something. We have recently discovered that another plugin of ours, MagicSpells, is somehow triggering fly of people using a specific spell, which is /carpet which enables temp fly with particles. Here's what happens in order.

1. Player casts /c carpet
2. Spell is applied.
3. checked /cmi info and Fly is set to True
4. Spell ends and fly is set to false
HOWEVER
if the player logs out and logs back in during the spell duration, the fly remains and remains despite relog. And thus is the problem. I have to manually take it off of them.  It can be successfully repeated.  If you want like a short video demostrating it and showing the flag being set 

Any advice or plugin fix for this would be appreciated. We have 3 servers to manage and it's possible we're missing them and not realizing. Here's an album of before and after pics.  If this can't be fixed, is it possible for a node to prevent cmi flying from being triggered at all?

https://imgur.com/a/mT7WT

**Comment by LogGits** [comment]
Anything that turns on fly uses the player.setFlying(true). Cmi also utilises this. Try out /cmi tfly. It would probably be better if you could make the your magic carpet use /cmi tfly. Tfly is Temporary fly and disables when they log out. You could also look in the eventcommand.yml file and check when a user logs and set their fly to false ./cmi fly (playername) false.

**Comment by WarmasterCain55** [comment]
I will look into that.  Thanks for the response.

**Comment by LogGits** [comment]
I am assuming this is resolved. If it isn't please reopen this.
