### ISSUE TITLE
[Feature] Scavange

### ISSUE THREAD

**Issue by xxJinxedxx** [Zrips/CMI#2101]
**Description of feature/improvement request:**
Revert option for Scavange blacklist.
Very simple but yet very useful feature.

```
  BlackList:
    UseAsWhitelist: true/false
```
P.S. - Just want to add that this feature is really really good & nice to have. Thank you!
---
### Detailed explanation of what it should do, when and in what situation: ###
It is pretty much self explanatory, but it will use the balacklist as a whitlist for the items that can go in the scavenger. 
And if i may add here, a dummy item that will be as info for the gui and what it does.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Just plain simple and quick management of that feature for any given gamemode, e.g. survival, skyblock, factions and so fort.. Any one of these has its specific terms of gameplay under which items are the main grind goal of the player. With whitelist admins/owners will be able to configure that feature to their server needs much more easy and fast.

**Comment by Zrips** [comment]
With next update
