### ISSUE TITLE
Regex Chat Rule Match Reporting in Console

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#2103]
I have a number of regular expressions setup to filter words on the server. It works amazingly well, but I did get some false positives (my mistake), and it would be nice if it would generate a console message with what they typed (the entire line of chat) and which rule it was matched with. Then I could just grep out that line in the logs and it would be super simple. Because now I have to write a crazy multi-grep statement to narrow down what was said and it's only about 60% useful without taking up a lot of time to dig deeper. I thought I could just have the system send me a /mail with the [message] variable and the playername, and it does send me the /mail and the player name, but the [message] variable doesn't get expanded, it just remains [message] which actually might be a bug, not sure. [message] does work when it's sending the output to staff, but thats it.

**Comment by Zrips** [comment]
Will add option to each filter rule to output into console feedback message with some information related to this event.
