### ISSUE TITLE
Holograms (and maybe portals, signs..etc..) can't be edited ingame anymore

### ISSUE THREAD

**Issue by DonSensiLeone** [Zrips/CMI#2106]
Holograms (and maybe portals, signs..etc..) can't be edited ingame anymore in chat in latest version : 8.6.8.0 , it was working right back with earlier updates but not anymore with this one . (out of topic : the scavange thing is awesome :) ) 

Server version : 1.14.4 Paper build 146

**Comment by Zrips** [comment]
Can you elaborate on what exactly is not working with them? As of my tests i can edit holograms and portals with GUI without any issues. Maybe i'm not seeing something obvious, as i did some small adjustments to GUI handling when i was making scavenging as it required some engine tweaks which maybe could have caused some issues with GUI handling in other areas. but cant really detect any of them currently.

**Comment by DonSensiLeone** [comment]
Hum in fact i suspect an other plugin to intercept the chat before cmi can do , i have this trouble with an other plugin wich asks me to write in chat to modify something and it doesn"t work either.. i will come back and tell more if i succed to find the reason

**Comment by DonSensiLeone** [comment]
It was a conflict with a bungee plugin wich was intercepting the message before CMI , sorry for that..
