### ISSUE TITLE
Subtract and Add to "cmi effect" Error

### ISSUE THREAD

**Issue by xxJinxedxx** [Zrips/CMI#2107]
**Description of issue:**
Using subtract (-) or/and add (+) to `/cmi effect [playerName] nightvision +10` doesn't work.

---

**ERROR:**
 - https://hasteb.in/boqanele.bash (+) add
 - https://hasteb.in/tuxesomu.bash (-) subtract
---

**Cmi Version (using`/cmi version`):** CMI: 8.6.8.0

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** 1.8.8-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Should be fixed with next build
