### ISSUE TITLE
Custom Recipe amount reverts to only ONE.

### ISSUE THREAD

**Issue by imhandmade** [Zrips/CMI#2108]
**Cmi Version (using`/cmi version`): 8.6.8.0

**Server Type (Spigot/Paperspigot/etc): Paperspigot 

**Server Version (using `/ver`): 1.14.4 (146)

This has been happening since 1.14 release, actually...
https://gyazo.com/5c21018756e12b6a9de660e0f59955d7

**Comment by Zrips** [comment]
Blame Notch for making recipe engine like that. CMI uses original recipe engine, which means that its limited to 2 things when it comes to ingredients: material and count of them placed in a gird. You can only have one ingredient per slot  without special names or lores attaches to them. Maybe in future will spare some time and make new engine to be more friendly and support item amounts, custom names, lores and NBT data. But is a huge and complex algorithm to make.
