### ISSUE TITLE
Feature consistency of portals

### ISSUE THREAD

**Issue by GrimPod** [Zrips/CMI#211]
The portals part of cmi is kinda alone and outdated in the way things are done
When you do /portals new <name> 
(also kinda think it should just be 'portal' instead of 'portals') 
You then have to do /portals to bring up a list of all the portals
Which arent in pages so you can only see so many,
Then click the portal you want

Whereas everything else (holograms/warps) open their settings when you create them

**Comment by Zrips** [comment]
Next update
