### ISSUE TITLE
Inventory Duplication on Death with cmi.keepinventory

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#2110]
**Description of issue:**
Not sure if this is a Spigot bug or CMI, but in the [latest spigot build](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/3e7b3862c7d1c718a47d1d5e54de8e3ea5845bbf) players with cmi.keepinventory both keep and drop their inventories, duplicating everything. 

---
**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.6.8.1 BungeeCord
Server version: Spigot 1.14.4-R0.1-SNAPSHOT
Vault version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-1981d55-3e7b386 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by mercurialmusic** [comment]
So there's this: https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-14-4-development-builds.369724/page-81#post-3491206

It was also messing in Residences where keep inventory was set to true.

**Comment by Xardas88** [comment]
Same problem here.

**Cmi Version (using`/cmi version`):** 
8.6.8.2
CMI plugin version: 8.6.8.2
Server version: Paper(152) 1.14.4-R0.1-SNAPSHOT
Vault version: 1.7.2-b107(CMIEInjector)
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper version git-Paper-152 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by digitalcrowd** [comment]
This is a HUGE issue ZRIPS! :)

Please fix this... See the thread above, it has information on what should be called and what shouldn't, etc.

**Comment by Zrips** [comment]
Yea, will be fixed/updated with next version.
