### ISSUE TITLE
[Bug] I can not use enchantment books from scavanger

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#2112]
**Description of issue:**
Enchantment books collected from the scavanger can't be used on other items. With the use of an anvil it will refuse to recognize the enchanted book. If I give myself a book from gamemode creative, it works with the new book. Scavanger books, no.

---

**Cmi Version (using`/cmi version`):** 8.6.8.0

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** git-Paper-636 (MC: 1.13.2)

**Comment by xxJinxedxx** [comment]
Confirmed on the newer version too. Books won't work after scavenger.|

**Cmi Version (using/cmi version):** 8.6.8.1

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using /ver):** 1.8.8-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Will be fixed with next build
