### ISSUE TITLE
Sleeping Speedup is not working for my player but working on op

### ISSUE THREAD

**Issue by alan67160** [Zrips/CMI#2114]
**Question:** Sleeping Speedup is not working for my player but working on op

**Comment by Zrips** [comment]
Strangely speed up doesn't check any permission nodes, in general its doesn't even care about players itself, its only checking how many are currently sleeping and which world it is. Which server version is this? And double check if you sleep speedup meets requirements, like minimal amount of sleeping players.

**Comment by alan67160** [comment]
paper 1.14.4 v169
all cmi version

**Comment by Zrips** [comment]
This doesn't really help out in determining the cause of the issue. Did you tested this without any other plugin and only CMI? As it could be caused by another plugin canceling bed enter event or similar thing which would prevent night speed up from kicking in.

**Comment by Romaq** [comment]
In my case, I'm running Multiverse-Core (gate, Nether-gate, inventory) and CMI. When multiple people are on the server, sleeping appears to behave. With just a single player, sleeping DOES NOT appear to behave. I "think" CMI is just letting "natural" game sleeping take over, but Multiverse has time settings to make the day last longer. So a player gets the boot from bed, but time does not appear to have advanced. Technically, I think this could be considered a "Multiverse" sleeping bug, and I could verify this and make an appropriate bug report. But I thought I'd post my situation first, as it just might be related to what @alan67160 is seeing, and if "only one player is in the world" as a use case is something CMI would want to bother with. I'll go ahead and confirm the "one player" bug in Multiverse WITHOUT CMI to see if it's the actual bug, and if this helps @alan67160, that'd be cool!

**Comment by Zrips** [comment]
@Romaq 
If you have everyone on the server sleeping then it will behave in a vanilla way, which means that in a couple seconds entire night will be skipped. This is due to how Mojang made it work and i have no idea how we could disable this vanilla skipping of night.

**Comment by Romaq** [comment]
per https://github.com/Zrips/CMI/issues/2529, Vanilla does not advance the time to day if "/gamerule doDaylightCycle false", which CMI appears to set for TimeSpeed to work correctly. Vanilla will kick all players (or the one) out of the bed after 110 ticks without advancing the daytick timer.
