### ISSUE TITLE
Scavange blacklist not working properly

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#2115]
**Description of issue:**
Reverted blacklist to whitelist, and only have diamond tools on the list. But items like diamond, iron ingot. gold ingot and coal can still be scavanged.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  BlackList:
  - diamond_pickaxe
  - diamond_sword
  - diamond_shovel
  - diamond_hoe
  - diamond_axe
  # When set to true, balck list becomes whitelist and will allow scavanging of items defined in a blacklist only
  BlackToWhiteList: true
```

---

**Cmi Version (using`/cmi version`):** 8.6.8.2

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** 1.13.2

**Comment by Baktus79** [comment]
Your setup is wrong. If you want to blacklist for instance diamond to be retrieved from a diamond pickaxe, the it should look like this:

```
  BlackList:
  - diamond
  - gold_ingot
  # When set to true, balck list becomes whitelist and will allow scavanging of items defined in a blacklist only
  BlackToWhiteList: true
```

In the example above you wont retrieve both diamond and gold from an item.

**Comment by blek-id** [comment]
But I have BlackToWhitelist: true
doesn't that just change Blacklist to Whitelist? So only things on the list would be able to be scavanged?

**Comment by Baktus79** [comment]
If I would make it whitelist only diamond and gold could be retrieved. In a diamond pickaxe, diamond would be the only thing I would get. A stick would not be retrieved

**Comment by blek-id** [comment]
I think i'm not explaining myself correctly xD haha.

I'm trying to make it so that only diamond pickaxe, sword, axe and shovel is allowed to be scavanged, and nothing else. Isn't what I'm doing on the config correct?

What is the correct way to do so

**Comment by Baktus79** [comment]
ahh, I see, but I dont think you can do that yet. You should post a suggestion for a new feature :D

**Comment by xxJinxedxx** [comment]
@blek-id is doing it the right way. 
I also confirm this issue. Only the items that he had listed should be able to be scavenged, but ore materials can also be placed and scavenged even that `BlackToWhiteList: true`.

Items that bypass the restriction:
 - COAL (263)
 - COAL (263:1) // charcoal
 - DIAMOMD
 - IRON_INGOT
 - GOLD_INGOT

```
  BlackList:
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS
  - DIAMOND_SWORD
  - DIAMOND_AXE
  - DIAMOND_PICKAXE
  - DIAMOND_SPADE
  - BOW
  # When set to true, balck list becomes whitelist and will allow scavanging of items defined in a blacklist only
  BlackToWhiteList: true
```

Cmi Version (using/cmi version): 8.6.8.2

Server Type (Spigot/Paperspigot/etc): PaperSpigot

Server Version (using /ver): 1.8.8-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
It could have been left over from previous configuration, will make sure with next version that reloading config file clears out previous setup properly. So simply perform full server restart and it should solve your issue.
