### ISSUE TITLE
@ function

### ISSUE THREAD

**Issue by alan67160** [Zrips/CMI#2116]
**Description of feature/improvement request:** add @ function on cmi
---
### Detailed explanation of what it should do, when and in what situation: ###
so I can make a command block run command like this "/cmi sudo @p say hi"
### Basic explanation as to why this feature is needed and/or useful to have: ###
If cmi don't have @ function it will be difficult to use on command block

**Comment by Zrips** [comment]
Well you do have interactable commands feature which can perform commands from console or as player when you are interacting with block, lever, presure plate and so on

**Comment by LogGits** [comment]
An example of ur exact usage would be:
```
asPlayer! say hi
```
Utilise '/cmi ic' as Zrips mentioned.

**Comment by alan67160** [comment]
but if you can use command to run it
then you will be able to run command by stone

**Comment by Zrips** [comment]
Again, there is a feature that allows you to make any block interactable and at the moment you click it, it will perform defined commands. Thos @ type variables are only for minecraft itself and i cant find any way to retrieve specific player(s) from it when command block is triggered. its simply a limitations of minecraft and you can use built in interactive block system to get what you want.
