### ISSUE TITLE
Ability to disable teams feature

### ISSUE THREAD

**Issue by starwarsfreak219** [Zrips/CMI#2117]
**Description of feature/improvement request:**
Could you possibly add the ability to disable teams management? It seems to be the route cause of the issues discussed in this report: https://github.com/Zrips/CMI/issues/2081
---
### Detailed explanation of what it should do, when and in what situation: ###
Disabling team management in case other plugins deals with anything teams related. CMI conflicts with other plugins because of the teams feature.
### Basic explanation as to why this feature is needed and/or useful to have: ###
So if you have any plugins that are using the teams feature, or plugins that may be having conflicts with CMI because of the team feature, CMI doesn't override or cause those other plugins to bug out. Thanks in advance!

**Comment by Zrips** [comment]
Yea, i can add that option into config file with next update.
