### ISSUE TITLE
Give leather color

### ISSUE THREAD

**Issue by matahombres** [Zrips/CMI#2118]
In the give command not can change color leather. Example in minecraft vanilla:
`/give @p leather_helmet 1 0 {display:{color:3144374}}`
This command working, but when you like change color name. Example:
`/give @p leather_helmet 1 n &6Test l &3abc {display:{color:3144374}}`

Give helmet color but not with name

My proposed solutions:

**Solution 1:**

In the name leather armor have the color. Example:

`/give @p leather_helmet:3144374 n &3abc l &5abc`

**Solution 2:**

Create new id "c". This util for

`/give @p leather_helmet n &3abc l &5abc c #524676`

**Solution 3:**

Generate new id for a custom NBT vanilla tags

`/give @p leather_helmet n &3abc l &5abc v {display:{color:3144374}}`

My like solution is 2 but 3 is more versatility

**Comment by Zrips** [comment]
Will make a fix for this one, as currently NBT tag was taking priority and overriding any other changes done to the item, like custom display name, so with next update you should get correct item with correct display name, lore and color while using your original  **n &6Test l &3abc {display:{color:3144374}}** format
