### ISSUE TITLE
Sitting not working

### ISSUE THREAD

**Issue by Kyrobi** [Zrips/CMI#2119]
**Description of issue:**
When given all the correct permissions, the player should be able to sit on the stairs.
However, click the stairs will show that you've successfully sat in the stair, but you don't actually sit.

---

---

**Cmi Version (using`/cmi version`):** CMI: 8.6.8.2

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** This server is running Paper version git-Paper-"fe7ef7b5" (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
What output message are you getting when trying to sit down? And does your player have cmi.command.sit.stairs permission node? And double check if you have properly set chair blocks in config file
```
  SitOnStairs: true
  StairsAsChairs: true
  SlabsAsChairs: true
  CarpetsAsChairs: true
```

**Comment by digitalcrowd** [comment]
Stairs work for me, FYI.

**Comment by Kyrobi** [comment]
Looks like the permission I gave wasn't correct. Confirmed to be working now.
