### ISSUE TITLE
 Delete messages when teleporting to a site managed by third-party plugins

### ISSUE THREAD

**Issue by JavituRec** [Zrips/CMI#2121]
¿Can I delete messages when teleporting to a site managed by third-party plugins?

... may not be safe: third-party plugin.

**Comment by Zrips** [comment]
Duno how this is related to CMI itself, but if you would want to prevent messages appearing from another plugin, then you will have to intercept appropriate packets sent from server towards player. This can be done with ProtocolLib or by making your own packet listener.

**Comment by JavituRec** [comment]
No I did not explain clearly. When user tries to go to a warp or tp someone. Many times you receive the message of the place appearance may not be safe: third-party plugin from CMI. I want to delete that message.
