### ISSUE TITLE
[Big Bug] cmi.command.fly Not Be Checked

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#2123]
If a player types in /fly, permissions get checked for cmi.command.fly, and denies or allows correctly. If they type in /fly TheirOwnPlayerName, then fly is enable/disabled.

Using /lp verbose on, I was able to see the CMI isn't checking for the permission to fly or permission to give others fly. If the player types in /fly AnotherPlayerName, cmi.command.fly.others does get checked.

This happens ONLY when a CustomAlias.yml is defined for /fly...

```
  fly:
    Cmds:
    - perm:cmi.command.fly@! msg! [playerName] &c---------------------------------------------
    - perm:cmi.command.fly@! msg! [playerName] &aFly in Survial is available for Legend
      Rank Signups!
    - perm:cmi.command.fly@! msg! [playerName] &aFor more information go to &b/warp
      rank
    - perm:cmi.command.fly@! msg! [playerName] &c---------------------------------------------
    - perm:cmi.command.fly! cmi fly

```

If I disable the above and change fly to some other alias, then the permissions all work correctly. But with it enabled, it doesn't check.

This happens whether or not /fly is or isn't enabled in Alias.yml.

---

[20:48:06 INFO]: --------------------------------------------------
[20:48:06 INFO]: CMI plugin version: 8.6.8.2
[20:48:06 INFO]: Server version: Paper(152) 1.14.4-R0.1-SNAPSHOT
[20:48:06 INFO]: Vault version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[20:48:06 INFO]: --------------------------------------------------

**Comment by Zrips** [comment]
Should get fixed with next build. Your setup should work as expected without any need to change anything with it.
