### ISSUE TITLE
Run attachcommand as opped player

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#2124]
Add the possibility to run an attachcommand as an opped player. This is useful for commands that for example isnt support in console and you dont have access to, and minecraft vanilla commands like /summon.

**Comment by xxJinxedxx** [comment]
You can.
asFakeOp!
http://www.zrips.net/cmi/commands/specialized/

**Comment by Zrips** [comment]
@xxJinxedxx Well asFakeOp! will perform command as op player, but as none existing one, so in case command require something in particular from player, like target block, then it will fail. In general there is no way to allow to perform command without actually giving op to the player, which is as dangerous as it could get and i'm not really willing to make such risky feature at this moment.

**Comment by xxJinxedxx** [comment]
True, and its not really needed. There are many ways that one can bypass that.
@DrakePork e.g. 

/execute %player%~ ~ ~ /minecraft:summon Zombie ~ ~ ~
---
or with an offset for the player, where the zombie will summon to the player 3 blocks above, and so on...

/execute %player%~ ~ ~ /minecraft:summon Zombie ~ ~3 ~
---
These are supported by the console. For this part, `/minecraft:summon` you can use CMI to execute the command if you would like to.

**Comment by DrakePork** [comment]
Ah mkay. Thanks
