### ISSUE TITLE
Permission help

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#2125]
**Question: **
I can't seem to find the permission to deny /cmi ctext textname all. It's not on the wiki. Can you help me out?

**Comment by xxJinxedxx** [comment]
If there is no perm on the wiki for them, try using specialized commands or custom alias.

**Comment by blek-id** [comment]
How do I do so?

**Comment by blek-id** [comment]
Issue is, player seems to be able to do /cmi ctext textname all
the only permission they had is cmi.command.ctext

**Comment by xxJinxedxx** [comment]
`Extra conditions can be used to check opposite condition, inform player, cancel any further command performing actions if needed. Full variable can look something like `
`perm:cmi.testperm@?#! cmi heal [playerName]`
http://www.zrips.net/cmi/commands/specialized/

**Comment by xxJinxedxx** [comment]
Actually @blek-id , scratch all the above, it has a permission per ctext `cmi.command.ctext.[ctextname]`

**Comment by blek-id** [comment]
I think i'm not explaining myself correctly, sorry english is my 2nd language.

I have 20 custom texts available on my server. Some examples are: /discord, /vote. etc.
Player has permission -> cmi.command.ctext

Player seems to be able to force-send custom text to everyone on the server with the command:
/cmi ctext discord all
doing the command above will send discord custom text to everyone online.

I don't know how to negate this.

**Comment by xxJinxedxx** [comment]
Join the Discord.. https://discord.gg/dDMamN4

**Comment by blek-id** [comment]
Joined

**Comment by xxJinxedxx** [comment]
Confirmed.
CMI - 8.6.8.3
Players don't have `perm:cmi.command.ctext.others` by default, but it will not check if player executes `/cmi ctext [ctextName] all`.

**Comment by Zrips** [comment]
Will fix this one and **all** variable will require you to have cmi.command.ctext.others permission node to use
