### ISSUE TITLE
tpaall drags the 'gotrequest' from tpa, not tpahere as it should

### ISSUE THREAD

**Issue by RSLuke** [Zrips/CMI#2127]
**Description of issue or feature request:**

Everything is the title :
tpaall drags this message :
  tpa:
    help:
      info: '&eAsk the player if you can teleport to them'
      args: '[playerName] (playerName) (-c)'
    info:
      requestSent: '&eRequest sent to &6[playerDisplayName]'
      gotRequest: '&6[senderDisplayName] &erequests teleportation to you!'

IT SHOULD GET THIS ONE :
  tpahere:
    help:
      info: '&eAsks player to accept teleportation to your location'
      args: '[playerName] (playerName) (-c)'
    info:
      gotRequest: '&6[senderDisplayName] &erequests teleportation to them!'

---

**Cmi Version (using`/cmi version`):** On every CMI version I've used for months now (like 30 versions)

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.13.2

**Comment by AntoineHrn** [comment]
Just to say :
"Small fix for /tpaall hover over message"
If ever, it's not fixed, it wasn't the problem

**Comment by Zrips** [comment]
Will be fixed with next build
