### ISSUE TITLE
CMI vs Gringotts - money error

### ISSUE THREAD

**Issue by Victor75007** [Zrips/CMI#2133]
**Description of issue:**

Hello,

I got the long command when my players using _/repair_ command with repaircost.
This repair cost is 10 gold ingot.
I use custom alias for this cost.

Well, my players type _/repair_, and the CMI send some error to the console.
But no repair. And the plugin take the all gold what are at the player. 

I use Gringotts plugin for custom economy type.

Can you help me?
I am waiting for your answer

Thank you very much.
Best regards, 
Victor
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
 **https://pastebin.com/sxXei4Ad**
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
  repair:
    Cmds:
    - moneycost:10?! cmi repair [playerName] hand
#######################################
```

---

**Cmi Version (using`/cmi version`):**  8.6.8.4

**Server Type (Spigot/Paperspigot/etc):**  1.13.2 Paperspigot (639)

**Server Version (using `/ver`):** 1.13.2 Paperspigot (639)

**Relevant plugins (Delete if this isn't needed):** Gringotts, Vault

**Comment by Zrips** [comment]
Should no longer be issue. It might be the cause of usage of alias command which was redirecting to itself.
