### ISSUE TITLE
/cmi spawnmob cat spawns Ocelot instead of Cat in 1.14.X

### ISSUE THREAD

**Issue by Seeroh** [Zrips/CMI#2135]
**Description of issue:**

`/cmi spawnmob cat` as of 8.6.8.4 spawns an Ocelot on 1.14.X, instead of a cat, which is now a separate entity.

https://minecraft.gamepedia.com/Cat

**Cmi Version (using`/cmi version`):** 
8.6.8.4

**Server Version (using `/ver`):** 
1.14.4

**Comment by Zrips** [comment]
Fixed
