### ISSUE TITLE
CMI flightcharge wouldn't run out while teleporting

### ISSUE THREAD

**Issue by kaniesha** [Zrips/CMI#2138]
**Description of feature/improvement request:**
Flightcharge is currently depleted when players teleport via homes, warps or to each other while flying. Could there be a setting that would prevent that from happening?
---
### Detailed explanation of what it should do, when and in what situation: ###
Flightcharge depletion when teleporting: true/false

### Basic explanation as to why this feature is needed and/or useful to have: ###
I believe this setting would be useful in helping players who use flightcharge to not use up a lot of their currency/xp because of forgetting to land or disable flight.

**Comment by Zrips** [comment]
This got fixed
