### ISSUE TITLE
attachcommand run command twice

### ISSUE THREAD

**Issue by SeanWalk** [Zrips/CMI#2140]
**Description of issue:**

attachcommand click at npc or player will run command twice
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```

[12:07:12 INFO]: Giving 64 of Birch Wood () to SeanWalk
[12:07:12 INFO]: Giving 64 of Birch Wood () to SeanWalk

[https://i.imgur.com/F4h2Bt4.png](url)

```

---

**Cmi Version (using`/cmi version`):** 8.6.8.4

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper(156) 1.14.4-R0.1-SNAPSHOT

**Relevant plugins (Delete if this isn't needed):**citizens2

**Comment by Zrips** [comment]
Should be fixed with latest version

**Comment by 1425115471** [comment]
No repair
