### ISSUE TITLE
Attachcommands missing locale for command.Class.info.cooldown

### ISSUE THREAD

**Issue by Fabrimat** [Zrips/CMI#2141]
Doing /cmi attachcommand !cooldown:60!cmi ctext tutorial works fine, but if I try to spam the attached command i get "missing locale for command.Class.info.cooldown".

CMI plugin version: 8.6.8.4 BungeeCord 
Server version: Paper(156) 1.14.4-R0.1-SNAPSHOT

**Comment by kekke3r** [comment]
Can confirm this, happened also to me, seems like the plugin can't find the node "cooldown" in the Locale.yml
Here is the Locale_EN.yml (default) config for the attached commands: https://pastebin.com/LC75xhic
Error In Game: https://pasteboard.co/Iuu11CK.png
CMI plugin version: 8.6.10.0
Server version: Paper(169) 1.14.4

**Comment by FabianF2** [comment]
Same here. Would be nice to get this fixed as it makes the /attachcommand kind of useless. :/

**Comment by JoelDeadMach** [comment]
It's still not fixed for you guys right? I also have this issue...

**Comment by Zrips** [comment]
Will get fixed with next build
