### ISSUE TITLE
Crash server when use command /tppos

### ISSUE THREAD

**Issue by Fiks75** [Zrips/CMI#2142]
**Description of issue:**
Crash server when use command /tppos 1020033508 09832075 93158
Spigot 1.13.2. Please fix it.

---

ERROR:
```
https://pastebin.com/42Cfvt0E
---
Minecraft Crash Report:
https://pastebin.com/yh81J6u6
```

---

Cmi Version: 
02.08 06:26:39 [Server] INFO --------------------------------------------------
02.08 06:26:39 [Server] INFO CMI версия плагина: 8.6.8.4 BungeeCord
02.08 06:26:39 [Server] INFO Версия сервера: Spigot 1.13.2-R0.1-SNAPSHOT
02.08 06:26:39 [Server] INFO Версия хранилища: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
02.08 06:26:39 [Server] INFO --------------------------------------------------

Server Type: Spigot

Server Version: 
02.08 06:27:43 [Server] INFO This server is running CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will be fixed with next version
