### ISSUE TITLE
Vanish error

### ISSUE THREAD

**Issue by BeeRando** [Zrips/CMI#2145]
**Description of issue:**
It looks like when someone logs in, this error message appears in console
https://pastebin.com/LPKyBEET

8.6.5.1-> 8.6.8.4
0Spigot 1.14.4-R0.1-SNAPSHOT
Vault version: 1.6.11(+)

CraftBukkit version git-Spigot-9de398a-9c887d4 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by mercurialmusic** [comment]
Update your vault: http://www.zrips.net/wp-content/uploads/2019/07/Vault-1.7.3.jar

I'm not sure if that's what's doing it, but it looks like the issue here is with Dynmap not being able to talk to CMI, which could be a vault thing.  ¯\_(ツ)_/¯

**Comment by Zrips** [comment]
Got fixed
