### ISSUE TITLE
tpa cost

### ISSUE THREAD

**Issue by BeeRando** [Zrips/CMI#2147]
**Question: **
Hi. I'm trying to make tpa cost 500$. This is what I've got in the customalias yml

  tpa 1$:
    Cmds:
    - moneycost:500! tpa 1$

It works for /back, which I've put a 100 coin cost on. But I cant make the cost work for tpa. 

Ingame I do /cmi aliaseditor new tpa 1$-moneycost:500! tpa 1$

**Comment by the456gamer** [comment]
Do moneycost:500! cmi tpa 1$ instead

**Comment by BeeRando** [comment]
Hi, sorry I can't get it to work to cost money. What exactly should I be typing? 
/cmi aliaseditor new tpa-moneycost:500! cmi tpa 1$
that?

**Comment by Zrips** [comment]
@BeeRando 
/cmi aliaseditor new tpa-moneycost:500! cmi tpa $1
