### ISSUE TITLE
Unable to translate [autoTimeLeft] in `/cmi bossbarmsg`

### ISSUE THREAD

**Issue by Seeroh** [Zrips/CMI#2149]
**Description of feature/improvement request:**

Add place to translate [autoTimeLeft] within boss bar messages

---
### Basic explanation as to why this feature is needed and/or useful to have: ###

The placeholder automatically is formatted as
`&e[minute] &6min &e[seconds] &6sec `

WITH a space afterwards. This cannot be changed anywhere that I can see. The colors cannot be changed, and neither can the words, and the ability to change both of those would be fantastic.

Also, when the seconds hit zero, but there are minutes remaining, the seconds disappear, making the line change size, and then immediately change again, which looks bad. Like in the images attached.

![1m1s](https://user-images.githubusercontent.com/9147655/62437054-7acd5d80-b6f6-11e9-96e0-a4272fba0bdf.png)
![1m](https://user-images.githubusercontent.com/9147655/62437057-7d2fb780-b6f6-11e9-8c47-16c77db6afb6.png)
![59s](https://user-images.githubusercontent.com/9147655/62437062-802aa800-b6f6-11e9-80cb-7425c088499e.png)

If the time is over one minute remaining, it should KEEP the minutes and seconds placeholder. like this, to keep it looking nice. {Also would be nice if the seconds placeholder was always two digits, to keep it looking uniform.}

![1m0s](https://user-images.githubusercontent.com/9147655/62437096-a8b2a200-b6f6-11e9-83be-bc2cee03f368.png)

But when under 60 seconds, the minute placeholder should disappear.

**Comment by Zrips** [comment]
You can edit locale for time format. Will make that change to keep full time format when you have minor values at 0
