### ISSUE TITLE
CMI Portal Premium - 1.14.4 support??

### ISSUE THREAD

**Issue by smmmadden** [Zrips/CMI#2153]
@Zrips - been posting on Spigot for the CMI Portals with BungeeCord Support and on Discord for an update for this plugin, but not getting any responses.  Is it going to be updated or not?  I need to know so I can upgrade my servers to 1.14.4 with one that works.  Thanks!

**Comment by smmmadden** [comment]
@Zrips - is CMI Portal going to be updated for 1.14.4 or not?

**Comment by smmmadden** [comment]
@Zrips - last attempt to get a response before I mark this as no longer supported and find another option.

**Comment by Zrips** [comment]
Its no longer supported. Tho full CMi packet has this capability.
