### ISSUE TITLE
CMI Votifier Listener Timings

### ISSUE THREAD

**Issue by Dakotaa** [Zrips/CMI#2154]
**Question: **
Looking at my timings report, I see the CMI Votifier listener is one of the highest timings, even though I don't use CMI voting rewards at at..

[Image here](https://i.imgur.com/Ob66k8p.png).

Is it possible to disable the CMI votifier listener?

**Comment by Zrips** [comment]
Will make some adjustments to minimize this load. Tho just a reminder, its not a reward listener, its a listener for votes themselves.
