### ISSUE TITLE
/cmi playtime 2 not working

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [Zrips/CMI#2155]
**Description of issue:**

/cmi playtime 2 and all further are not showing anything

https://i.imgur.com/1A8DHOX.png
---

**Cmi Version (using`/cmi version`):** 
8.6.8.4
**Server Type (Spigot/Paperspigot/etc):** 
Pasper
**Server Version (using `/ver`):** 
1.14.3 b115
**Relevant plugins (Delete if this isn't needed):**

**Comment by EMcKee10** [comment]
I receive this bug as well. we are on 1.14.4
![2019-08-05_15 43 46](https://user-images.githubusercontent.com/26212961/62541779-14dcf500-b820-11e9-8628-b598e8134a3f.png)

**Comment by digishield** [comment]
I had the same problem. I switched my database to MySQL and it fixed.

**Comment by Kryniowesegryderiusz** [comment]
I have it on mysql already

sob., 10 sie 2019, 22:57 użytkownik digishield <notifications@github.com>
napisał:

**Comment by EMcKee10** [comment]
@xion87 what database did you previously use?
@Kryniowesegryderiusz check your databases available storage space, see if that has something to do with it.

**Comment by konsyr11** [comment]
Bug appearing over here too. Spigot 1.14.4

**Comment by EMcKee10** [comment]
@konsyr11 are you running the newest version of cmi?

**Comment by konsyr11** [comment]
10 days later...
@EMcKee10 no I am running 8.6.4.0
But aren't you running the latest? How come you still have the bug??

**Comment by Zrips** [comment]
fixed
