### ISSUE TITLE
Nametagedit + CMI buggy

### ISSUE THREAD

**Issue by JavituRec** [Zrips/CMI#2156]
**Description of issue:**

When use /vanish the tag is removed in tablist if you are using nametagedit. I have tablist disable in module.

**Cmi Version (using`/cmi version`):** 
8.6.8.4
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.14.4
**Relevant plugins (Delete if this isn't needed):**
Nametagedit

**Comment by mercurialmusic** [comment]
Which build of NTE are you using? The 1.14 versions are only in their [dev builds](https://ci.nametagedit.com/job/NametagEdit/). I use both together without issue. CMI also has this functionality, but I still need to play with it.

It might also be helpful if you included your config.

**Comment by JavituRec** [comment]
I am using last #56. The problem in tablist with cmi is than not order ranks and head rank neither.
