### ISSUE TITLE
Locale_ES didnt save

### ISSUE THREAD

**Issue by Yhenko** [Zrips/CMI#216]
Hi, when i restart the server, the Locale_ES.yml DIDNT SAVE. It is remade again and again, please, can u fix that?

**Comment by LogGits** [comment]
wait so when u edit the file, then save it, are you typing `/cmi reload` after these two steps? and if so when you type the `/cmi reload` command is it then resetting the Locale_ES.yml aswell? Also does it produce any errors? If so reply with the error along with what you changed so we can test it 👍

**Comment by Yhenko** [comment]
when i type /cmi reload, all the changes works propertly but when the server restart, the config comes back again to the default config :(, i solved it, copying all changes to Locale_EN and its save correctly.

Sorry for my bad english.

**Comment by LogGits** [comment]
Will be fixed in the next update 👍
