### ISSUE TITLE
Potions

### ISSUE THREAD

**Issue by BeeRando** [Zrips/CMI#2161]
**Question: **
Lets say I wanted to give myself a splash potion of levitation for say, 5 seconds, what would the command be for that? The wiki page doesn't go into detail about how to spawn custom potions.

**Comment by Rukes** [comment]
If there is not ´cmi effect´ command you can use vanilla ´effect´ command.

**Comment by BeeRando** [comment]
I'm not asking about an effect command. I'm asking how to make potions with different effects/durations.

**Comment by Zrips** [comment]
Effect durations are tied to effect itself, when we are talking about potion effects. You could have generic effect with different durations, but to have potion with one would require a completely different approach and override vanilla behavior.
