### ISSUE TITLE
panimations and merging installs

### ISSUE THREAD

**Issue by thecenters** [Zrips/CMI#2166]
1) How do I clear player animations from /cmi panimation

2) I have two servers running CMI that I'm trying to merge. Is this a current feature?

**Comment by thecenters** [comment]
Anyone?

**Comment by mercurialmusic** [comment]
1. What do you mean by clear? You want to delete the presets? Or you want to get rid of them while they're running? There's a built-in duration timer on them that should be used. Do they not otherwise stop after a server restart or player relog?

2. No, this is not a feature of CMI. That would be a little crazy. You can merge them manually though.

**Comment by thecenters** [comment]
I want a player animation to be set for like 9999 duration  and then be
able to remove it from the player with a command

**Comment by mercurialmusic** [comment]
Ah, yeah. I get that, but I'd also be careful with it -- seems like it'd be pretty resource heavy. Not sure about a clear command for those though.

**Comment by Zrips** [comment]
panimation is an experimental feature, its not really being attached to a particular player, its only follows him and in some cases its being displayed in particular place. This is why we have some hard coded timer limitations to avoid them running for extended periods of time. Some improvements will come with time.

Cant really say about that "merge" thing, some things like homes are defined by world name, so if you no longer have world with that name, then it will not work, obviously. But there is no dedicated feature/command to merge worlds.

**Comment by thecenters** [comment]
Multiple servers, with the exact file names, connected to a singular database, with different world names. The homes overwrite themselves when I change between servers.
