### ISSUE TITLE
Playtimetop pages empty besides page 1

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#2167]
**Description of issue:**
When doing /playtimetop and navigating through the pages, only page 1 has value

![image](https://user-images.githubusercontent.com/26654664/62690639-3ba15400-b9f7-11e9-9eb2-0abc34bd61ac.png)

---

**Cmi Version (using`/cmi version`):** 8.6.8.4 

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** 1.13.2

**Comment by Zrips** [comment]
Fixed
