### ISSUE TITLE
After Update to CMI 8.6.9.0

### ISSUE THREAD

**Issue by DarkFort** [Zrips/CMI#2170]
Error - https://pastebin.com/NBWK8fWj

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**[18:38:27 INFO]: This server is running Paper version git-Paper-163 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[18:38:27 INFO]: Checking version, please wait...
[18:38:28 INFO]: Previous version: git-Paper-152 (MC: 1.14.4)
[18:38:28 INFO]: You are running the latest version
**

**Comment by mercurialmusic** [comment]
Are you on a Bungeecord setup? If not you may need to disable that, or if so, did you also install the new Bungee plugin he mentioned in the changelog?

**Comment by DarkFort** [comment]
Yes, I have several servers and BungeeCord (Waterfall). There are a lot of mistakes. Here is another one https://pastebin.com/QjJHygbL

**Comment by mercurialmusic** [comment]
Strange. I haven't had any issues with it.

**Comment by Zrips** [comment]
Your first error is from v8.6.8.4 while the second one from v8.6.9.1 and your title mentions 8.6.9.0
In any case, with new bungee handling method while having CMIB on bungeeserver this should be resolved.
