### ISSUE TITLE
in the hell random tp bug  (need fix soon)!!!

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#2171]
/rt , in world_nether can't tp , Will be sent to the top of hell

**Cmi Version (using`/cmi version`):** 8.6.9.1

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.13.2

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
fixed
