### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by NyhmsQuest** [Zrips/CMI#2172]
**Description of issue:**
Whenver I or anyone else types in chat nobody can see it, but I can see the messages in console.
I have tried with both CMI handling chat and without CMI handling chat, both have same problem.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
https://pastebin.com/CtCKcrFg
```

---

**Cmi Version (using`/cmi version`):** 
CMI8.6.9.1
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper-163 (MC 1.14.4)

**Comment by JasperLorelai** [comment]
I have the same issue. I think it's connected to this: https://github.com/Zrips/CMI/issues/2165

Chat events are not being cancelled because they are visible on console. They are not being sent at all. On the issue linked CMI isn't sending certain messages.

**Comment by Zrips** [comment]
Tested out with latest build, all seems to be working as is should, try updating plugin to latest version. Chat is working and all editors mentioned works too, even with provided holograms file at #2165 issue report

**Comment by NyhmsQuest** [comment]
I am on the latest version, I'm on 8.6.9.1.
I tried disabling CMI entirely and the chat worked fine after that so to me it looks like a problem with CMI.

**Comment by JasperLorelai** [comment]
Which latest build? I tried updating to v8.6.9.1 but something's causing CMI to revert back to v8.6.8.4. If I load that version just specifically (it was saved locally) the problem persists. I could try disabling plugins one by one.

**Comment by JasperLorelai** [comment]
I started generating fresh configuration files to check if the problem was located there. I found that it had something to do with `config.yml`. Then I tried to check if any new features could be messing with chat but I didn't find anything related. After going through each property I found that having `ClickHoverMessages` set to true caused chat to break.

**Comment by NyhmsQuest** [comment]
Thank you JasperLorelai, setting that option to false fixed the problem for me too.
