### ISSUE TITLE
Downloadet the latest version CMI8.6.9.0 and my server log says [CMI] Enabling CMI v8.6.8.4

### ISSUE THREAD

**Issue by general2811** [Zrips/CMI#2173]
https://pastebin.com/9gzG91au

**Comment by digishield** [comment]
Same.

**Comment by JasperLorelai** [comment]
Fixed in **v8.6.9.4**.

**Comment by Zrips** [comment]
in general any time you see wrong version, it means that i forgot to update it in plugin.yml file. But in general you will get latest version, its only a version number which is outdated. Sorry about this one.
