### ISSUE TITLE
CMI 8.6.9.1 says I have 8.6.8.4

### ISSUE THREAD

**Issue by TDStewart** [Zrips/CMI#2176]
**Description of issue or feature request:**

---

**Cmi Version (using`/cmi version`):** 
8.6.8.4

**Server Type (Spigot/Paperspigot/etc):** 
Paper 166

I shutdown my server.
Downloaded the new 8.6.9.1 version of CMI.
Installed it and deleted the old 8.6.8.4 version.
Restarted the server.

Still tells me I have 8..6.8.4 installed even though the file is CMI8.6.9.1.jar

**Comment by azerwyn** [comment]
Verified.  plugin.yml in file (CMI8.6.9.1):
name: CMI
main: com.Zrips.CMI.CMI
version: 8.6.8.4
website: https://www.spigotmc.org/resources/content-management-interface.3742/
author: Zrips
api-version: 1.13
description: Powerful server management tool

**Comment by Regrave** [comment]
+1

**Comment by mercurialmusic** [comment]
This happens occasionally with CMI -- just ignore it and [go buy Zrips a coffee](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=9K3FS72W3SK5A) because the guy's a beast. No need to jump on such insignificant errors.

**Comment by JasperLorelai** [comment]
Fixed in **v8.6.9.4**.

**Comment by Zrips** [comment]
Happens from time too time when i forgetting to update plugin.yml file version number. You will get latest version, its only version number which is outdated
