### ISSUE TITLE
Drop spawner doesn't work

### ISSUE THREAD

**Issue by ludvdber** [Zrips/CMI#2177]
**Description of issue or feature request:**

Spawner doesn't drop with perms. 
worked in 8.6.8.0 

---
**Cmi Version (using`/cmi version`):** 8.6.9.1

**Server Type (Spigot/Paperspigot/etc):** Paper(166) 1.14.4-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
make sure that Spawners are not disabled in config file and that you have Break enabled. In general check config file responsible for spawner drop and follow its comments.
