### ISSUE TITLE
The /i command

### ISSUE THREAD

**Issue by BiGUNMAN** [Zrips/CMI#2182]
**Description of issue:**
The /i command (if mirroring Essentials) is not supposed to be a give command! It is supposed to always give the item to the player executing the command, which is why the following is **incredibly** frustrating.

The plugin will occasionally give the item you create in /i to a player. Example:
1. I execute the command `/i stone 1 n John` which should give me 1 stone named John
2. The item is given to the player Nivramnitsud
3. Image of command and it being given to player: https://i.imgur.com/fVki1mW.png

From my understanding the above is intentional, however, directly conflicts with the definition of the /i command (it's suppose to give you the item, not someone else).

---

**Cmi Version (using`/cmi version`):** 8.6.8.4

**Server Type (Spigot/Paperspigot/etc):** 1.12.2 

**Server Version (using `/ver`):** 1613

**Comment by Zrips** [comment]
Excellent point, will change this behavior and separate /cmi give into /cmi give and /cmi item commands where second one will only give item to command sender.
