### ISSUE TITLE
Add ability to disable votifier listener

### ISSUE THREAD

**Issue by Nekomitsuki** [Zrips/CMI#2183]
**Description of feature/improvement request:**
Add ability to disable Votifier functions in CMI in Modules.yml.
---
### Detailed explanation of what it should do, when and in what situation: ###
Basically, it will disable all vote functionalities used by Votifier in CMI.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Not everyone uses CMI as their primary Voting Listener and the Vote Listener in CMI is pretty resource taking as i saw in Timings.

![Screenshot_2](https://user-images.githubusercontent.com/45139953/62897544-cb2a6800-bd53-11e9-9d00-e23d9b8623ef.png)

**Comment by Zrips** [comment]
Made some optimizations for this listener to take a lot less resources, but on top of that will add option to disable it entirely in modules.yml
