### ISSUE TITLE
latest update breaks — /skin

### ISSUE THREAD

**Issue by Roper89** [Zrips/CMI#2188]
@Zrips 
Previously, a player with permission (cmi.command.skin) could change his skin using the **/skin (skinName)**
Why now, after the name of the skin, do you need to add your own name to **yourself** ? Example: /skin (skinName) (**playerName**) 
The player has only permission (cmi.command.skin) it does not allow other players to change the skin, then why specify the name?

Please return as it was before.

P.S. permission (**cmi.command.skin.others**) does not allow anything to be done. Only notifies of the need for permission (**cmi.command.skin**)

**Comment by Roper89** [comment]
sorry for my English. _(translate.google.com)_

**Comment by Zrips** [comment]
Will be fixed with next build
