### ISSUE TITLE
Portal teleport location can't be set

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2189]
Each time I click on the message to set the teleport position, it gives me this error:

http://prntscr.com/os60zx

Also when I remove a portal, it removes the portal yet says no portal exists under that name.

http://prntscr.com/os6200

CMI version: http://prntscr.com/os627r

**Comment by Godlycreations** [comment]
I am having the same issue as Sikatsu, all of my existing portals stopped working as well.

**Comment by Zrips** [comment]
Will make some adjustments, it seems to be failing in determining servers name for on a bungeenetwork and preventing any new location sets because of that.
