### ISSUE TITLE
UserMeta Command-  Enhancement please

### ISSUE THREAD

**Issue by GrimPod** [Zrips/CMI#219]
At the moment the user meta has limited use cases

You can "/usermeta <username> add <Key> <valuse>" a user meta for a player
But really it just sets to value of the <key> 
For example You cannot automatically increase a users meta by a certain number using a Interactive command/portal/alieseditor/etc

It would be nice if we could use 'add' to add a number to a users meta for say when a player uses a portal or command
Using lets say
/usermeta <username> add <Key> '%cmi_user_meta_<key>% + 1' or even just '+1'
then add a set to set it to a number

**Comment by Zrips** [comment]
Will be added with next update.
