### ISSUE TITLE
Error in chat, when a change the config file.

### ISSUE THREAD

**Issue by MrHoStille** [Zrips/CMI#2194]
**Description of issue:**
When i did change the config file, CMI commands : Holograms, IC, Placholders are broken in chat. But not in the console.

---

**Cmi Version (using`/cmi version`):** 
8.6.9.4
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
1.14.4
**Relevant plugins (Delete if this isn't needed):**
Custom skyblock plugin, custom crytoblock plugin, betterbrushes, Citizen, custom market plugin, HeadDatabase, F.A.W.E, custom gobrush plugin.

**Comment by Zrips** [comment]
Without any extra information then this cant really resolve this issue, if its issue a all. Make sure that you are saving file properly in utf-8 format as it is on creation. And if issue persists some error logs would be nice to see or any screenshots to have idea whats actually going on.
