### ISSUE TITLE
Teleport announcements broken

### ISSUE THREAD

**Issue by TheCynicalKitty** [Zrips/CMI#2195]
So if i send a tpa request to someone or any other request based teleport the receiving user doesn't get the request message alert.

Deleting the CMI folder and letting it make a new one fix's the issue BUT changing any settings break the receive announcement alert to other players, They can still teleport but without the player saying something they have no idea they have the request.

**Cmi Version (using/cmi version):**
8.6.9.4
**Server Type (Spigot/Paperspigot/etc):**
PaperSpigot
**Server Version (using /ver):**
1.12.2 Paper-1618

**Comment by chrsgddrd** [comment]
Also having this bug. Same criteria as above.

**Cmi Version**
8.6.9.4
**Server Type**
1.14.4 Paper Spigot 163

**Comment by Zrips** [comment]
Should be working correctly with latest build
