### ISSUE TITLE
CMI 8.6.9.4 Portals commands do not work.

### ISSUE THREAD

**Issue by tmellen** [Zrips/CMI#2201]
**Description of issue:**
Whether I set a teleport spot, or not, portal commands do not run. When I set a valid spot, I go there, but no commands.

**Cmi Version:** 8.6.9.4
**Server Type:** Spigot
**Server Version (using `/ver`):** 1.14.4-r0.1-snapshot

**Comment by tmellen** [comment]
More info from further testing: Portals with commands that are set to run, won't TP to valid spot. If I set commands off, then the TP works.

**Comment by Godlycreations** [comment]
Portals are fixed now in 8.6.11.0, I has having the same issue with that jar file.

**Comment by runelynx** [comment]
Portals not working in 8.6.12.1. 
Creating it works; then I get the message... 

![image](https://user-images.githubusercontent.com/5877481/65200653-84a7e780-da3c-11e9-90f6-6d5d136ed866.png)

So I go somewhere nearby and click that. Meanwhile, in console...

CrocodileHax issued server command: /cmi portals bungeeLoc TESTPORTALE bungee:Runic Paradise
CrocodileHax issued server command: /cmi portals bungeeLoc TESTPORTALE bungee:Runic Paradise
CrocodileHax issued server command: /cmi portals bungeeLoc TESTPORTALE bungee:Runic Paradise
CrocodileHax issued server command: /cmi portals bungeeLoc TESTPORTALE bungee:Runic Paradise

In-game, nothing is happening. 

Per the update log, I should not have to have CMI Bungee installed for this to work. :( 

![image](https://user-images.githubusercontent.com/5877481/65200677-a7d29700-da3c-11e9-82d4-67f07cbe5afb.png)

**Comment by runelynx** [comment]
![image](https://user-images.githubusercontent.com/5877481/65200685-b15bff00-da3c-11e9-9a59-d859a08150a6.png)

**Comment by Zrips** [comment]
It seems to be issue with a space in your server name, should get fixed with next version.

**Comment by runelynx** [comment]
😍
