### ISSUE TITLE
Server crashing on latest

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#2203]
**Description of issue:**
My server has been crashing when I updated my CMI and Residence to latest version

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/SrGwn5U5
```

---

**Cmi Version (using`/cmi version`):**  8.6.9.4

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  1.13.2

**Relevant plugins (Delete if this isn't needed):** Residence 4.8.7.2

**Comment by blek-id** [comment]
I think this one still has something to do with 
https://github.com/Zrips/Residence/issues/349

**Comment by Zrips** [comment]
Disable residence cleanup on removal. Will try to come up with better solution for this one. And this is entirely issue with residence and not CMI.
