### ISSUE TITLE
eventCommands.yml world change PRE vs POST

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2204]
Hey, 

This is not an issue, more a suggestion. I hope it's possible.

For example, we wish to force an inventory save when someone teleports between worlds. However, it gets executed post the world switch/teleport. Rather than before they teleport away. The inventories saved are therefor from the new world location rather than the previous world they were in. 

Is it possible (maybe it's just a techn limit?) that we can run the command before they get teleported away?

**Comment by mrfloris** [comment]
Friendly bump.

**Comment by Zrips** [comment]
playerPreWorldChange
new event command will be added to make it work in your desired way. As current system uses oficial event which seems to be fired after player teleports, this is why you had this issue. So extra event which will be fired before actual teleport will fix it.

**Comment by mrfloris** [comment]
I understand this better now and thank you!
