### ISSUE TITLE
TABlist not working

### ISSUE THREAD

**Issue by konsyr11** [Zrips/CMI#2206]
I have tablist enabled and configured properly in CMI config, but it won't appear in game. We only have the traditional player list. Is this a bug, or is there an actual way to solve this?

**Comment by JasperLorelai** [comment]
It's important to follow the issue format when submitting it. Tablists changed in the recent versions. Copy [this](https://github.com/Zrips/CMI/issues/new?assignees=&labels=bug+report&template=bug_report.md&title=) and fill it in, then edit your original post with the text - you don't have to open a new issue for this.

**Comment by konsyr11** [comment]
I have tablist enabled and configured properly in CMI config, but it won't appear in game. We only have the traditional player list.
---
#######################################
tabList.yml: [PasteBin](https://pastebin.com/wttSzfjp)
config.yml: [PasteBin](https://pastebin.com/qwehGR8i)
#######################################
**Cmi Version (using /cmi version`):** 
https://pastebin.com/qwehGR8i
**Server Type (Spigot/PaperSpigot/etc):** 
PaperSpigot
**Server Version (using /ver`):** 
Paper version git-Paper-172 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by konsyr11** [comment]
Fixed
