### ISSUE TITLE
Add Permissions for colors and formats anvil rename

### ISSUE THREAD

**Issue by Xardas88** [Zrips/CMI#2208]
**Description of feature/improvement request:**
add  permissions to limit the use of colors and format in anvil rename like already used for chat
---

### Basic explanation as to why this feature is needed and/or useful to have: ###
to deny the use of certain colors and formats.
Example use of the annoying format &k

**Comment by BiGUNMAN** [comment]
This issue exists with the cmi.colors.nickname.{color} permission node too. It's a bug as according to documentation you should be able to set specific colors but this doesn't work. If you set the node to .* it grants formatting (bold, strikethrough, etc) that cannot be denied by setting the permission node to false.
