### ISSUE TITLE
Placeholder Load Issue MVDW

### ISSUE THREAD

**Issue by GameHoundInteractive** [Zrips/CMI#2212]
**Description of issue or feature request:**

can you fix cmi so it does not take 800 years to load the server due to it adding custom placeholders to mvdw placeholder api. it only loads 1 placeholder a second and theres over a 100 place holders by CMI

**Cmi Version (using`/cmi version`):** 
8.6.9.4

**Server Type (Spigot/Paperspigot/etc):**  
 Paperspigot

**Server Version (using `/ver`):** 
1.14.4

**Comment by Prscyse** [comment]
I agree. This is happening to me too. I'm using the same version.

**Comment by Zrips** [comment]
It takes less then 1 second to load all of them with latest versions. So ether it was fixed from MVdWPlaceholderAPI end or something different with your setup. But it all works correctly with 1.14.4 version
