### ISSUE TITLE
Problem with $1 in aliases

### ISSUE THREAD

**Issue by Xylella** [Zrips/CMI#2213]
**Description of issue or feature request:**
When "$1" is into an alias it behaves like "$1-". 

---

**Cmi Version (using`/cmi version`):** 8.6.9.4

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** latest 1.12.2 version

**Comment by LogGits** [comment]
Oh i am also having this issue

**Comment by Zrips** [comment]
Will be fixed with next build
