### ISSUE TITLE
CMI problem

### ISSUE THREAD

**Issue by AndreiD2015** [Zrips/CMI#2214]
**Description of issue or feature request:**
Hello !
I have some problems with your plugin.
When i type /hologram or /cmi jaileditor or any other command, nothing is happen.
For example:
When a player execute /hologram, the command need to show a list with all holograms.
When a player type /clear, usualy it send a confirmation messaje, but nothing is happen.

All of this things work when the plugin run for the first time, but after some reloades or restartrs of the server, this is happen.

This is what happen when a player type /cmi jail editor
https://cdn.discordapp.com/attachments/591365067962843137/612219360244662302/Capture.PNG
At /hologam nothing is happen
No erros, not even a simple line 

--

**Cmi Version (using`/cmi version`):*8.6.9.4* 

**Server Type (Spigot/Paperspigot/etc):*Spigot 1.14* 

**Server Version (using `/ver`):*1.14* 

**Relevant plugins (Delete if this isn't needed):* CratesPlus, MVdWPlaceholderAPI, ClearLag, PermissionsEx, FeatherBoard, PlugMan, ViaVersion, YoloCraft, Votifier, |
ProtocolLib, ShopGUIPlus, WorldEdit, ChestCommands, LWC, WorldGuard, Jobs, RandomTP, PreciousStones, CMI, LiteBans, Vault *

**Comment by JasperLorelai** [comment]
Refer to this issue for a hotfix: https://github.com/Zrips/CMI/issues/2165

**Comment by Zrips** [comment]
Fixed
