### ISSUE TITLE
maintenance  in Bossbar?

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#2216]
hello, often I put the server into maintenance mode with Cmi. Unfortunately I always forget to turn it off..so the server is not accessible for hours. Is it possible to make the status maintenance work appear as Bossbar during this time? You would rather pay attention to that. Would be great if that would work.

**Comment by Zrips** [comment]
Next update.

**Comment by Blueeyestar** [comment]
Thank you :)
