### ISSUE TITLE
Jaillist doesn't open anything besides a yellow dashed line

### ISSUE THREAD

**Issue by NeverlandMC** [Zrips/CMI#2217]
**Description of issue:**
When issuing /jailist nothing appears, even after creating a jail. Running into similar issue with kits where nothing appears and just a yellow dashed line pops up

---

---

**Cmi Version (using`/cmi version`):**  Newest

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot

**Server Version (using `/ver`):** paper 146, 1.14.4

**Comment by NeverlandMC** [comment]
Adding to this /jailedit <nameOfJail> also shows this yellow line

**Comment by JasperLorelai** [comment]
The problem is probably doing the same for `/aliaseditor`, `/holograms`, etc. If it is, look into this issue for a hotfix: https://github.com/Zrips/CMI/issues/2165

**Comment by therealatsuga** [comment]
I have a similar Problem... I can't select the jail "area" with the wooden shovel. Creating a jail is impossible...

**Comment by Zrips** [comment]
Got fixed
