### ISSUE TITLE
Bungee questions

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2219]
**Question: **
I installed CMI bungee on the proxy and CMI on two of my servers (Survival & Creative)
After a restart everyone lost their homes. Is there anything that could possibly cause this? Did Creative overwrite Survival? 

And it also doesn't seem to sync nicknames.

**Comment by Zrips** [comment]
Dont use same database on multiple servers, you will have issues. Each server should have its own tables.
