### ISSUE TITLE
Nickname Colours?

### ISSUE THREAD

**Issue by GrimPod** [Zrips/CMI#222]
{Yes i know its colors in the permissions, im Australian)
So ive been trying remove the abilitiy for players to user certian colours in their nickname
Ive given out just cmi.command.nick and it seems to let me use all colour possibilities
even when i set 
cmi.colors.nickname.* to false
which should remove all colour possibilities
but doesnt
it doesnt seem to be checking for that node at all

![image](https://user-images.githubusercontent.com/12431998/38455138-d8fe5d54-3ab6-11e8-97b7-1ad1740db21f.png)

**Comment by MCTyler** [comment]
They DID NOT Leave out this Perm.....
```cmi.colors.[type].[colorname] - Allows color usage in particular areas. Types: publicmessage, privatemessage, nickname, signs```

**Comment by MCTyler** [comment]
What does cmi.colors.nickname.red / cmi.colors.nickname.blue to false do?

**Comment by GrimPod** [comment]
cmi.colors.nickname.red 
cmi.colors.nickname.blue 
Both seem to do nothing,
Also tried cmi.colors.nick.aqua coz as in screenshot it checks
cmi.command,nick and not nickname
also seems to do nothing

**Comment by Zrips** [comment]
By default regular player doesn't have access to nickname colors. Double check if you have Chat->Colors->NickName set to true. As this one will clenup players nickname from color codes to which players doesn't have access.
