### ISSUE TITLE
/tpo doesn't work

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2220]
If we use /tp it teleports us to the player, but using /tpo we end somewhere else. I think it doesn't work cross-world?

**Comment by Zrips** [comment]
Small bug, will be working with next build

**Comment by Sikatsu** [comment]
@Zrips 

Thanks for fixing it, it seems to be better but not completely fixed. 

When you use /tpo on a nickname it still doesn't seem to work, but if you use the minecraft name it does.

**Comment by Sikatsu** [comment]
Or it has to do with that you can teleport to offline players? Is there a way to turn that off?
