### ISSUE TITLE
/home throwing errors, people lost their homes

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2221]
**Description of issue:**
People lost all their homes and when they do /home it throws an error:

https://pastebin.com/F0H4jF96

Version: http://prntscr.com/oup147

**Comment by Sikatsu** [comment]
On startup it always says this, I have the feeling it resets the databases or something.

https://pastebin.com/3eBJSGgE

People lost their homes, economy ect and even their money.

**Comment by Zrips** [comment]
Fixed
