### ISSUE TITLE
Aliases not working

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2222]
**Description of issue:**
If there are more then one aliases in alias.yml, only the first will work.

For example here, only /status works, the others don't give ANY output nor an error message.

```
  # /cmi status $1-
  /status: true
  /gc: true
  /lag: true
```

CMI version: http://prntscr.com/oup381

**Comment by JasperLorelai** [comment]
Disable the alias for `tellraw`. It should fix most problems with aliases and raw messages that aren't being sent. Look into this issue for more information: https://github.com/Zrips/CMI/issues/2165

**Comment by Zrips** [comment]
got fixed
