### ISSUE TITLE
[Important] 8.6.9.5 is completely broken

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2223]
**Description of issue:**
All players can simply do /tpall and /tpallworld and they will all be teleported to his location, even tho the player doesn't have permission to use those commands. 

It also throws errors both for /tp and /tpa: https://pastebin.com/T1yAsfgQ

People are also unable to accept any teleport request, only the option to deny shows up as you can see here: http://prntscr.com/oup824

People are also unable to use any aliases set in alias.yml, only the default command works.

CMI version: http://prntscr.com/oup8k7

**Comment by Sikatsu** [comment]
/baltop doesn't even work, while /cmi baltop does. There are a lot of issues with this latest build. Reverting back solves it all.

**Comment by Zrips** [comment]
Fixed
