### ISSUE TITLE
CMI Portals disappear everytime the config is reloaded or server is restarted.

### ISSUE THREAD

**Issue by Speyrow** [Zrips/CMI#2224]
CMI Portals disappear everytime the config is reloaded or server is restarted.
---
https://hastebin.com/limazosawe.coffeescript
---

CMI Version: 8.6.9.5

Server Type: Spigot

Server Version: CraftBukkit version git-Spigot-093165d-ba575a5 (MC:1.14.2)

**Comment by Zrips** [comment]
You need to look at startup logs for any errors. This can be due to wrong formating in text file used to save portals which in case it fails should be moved into backup folder and reset to default (empty) one
