### ISSUE TITLE
world_nether random tp broken

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#2225]
world_nether random tp broken
Every time it will be sent to the top of the bedrock in hell.
please fix soon

and

cmi tab , can't auto command

**Cmi Version (using`/cmi version`):** 8.6.9.5

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.13.2 1.14.4

**Comment by Zrips** [comment]
Should get fixed with next build
