### ISSUE TITLE
editlocale isn't working in Linux server

### ISSUE THREAD

**Issue by NightPrimez** [Zrips/CMI#2228]
**Description of issue:**
Hello, i found some issue
"editlocale" feature isn't supported linux
when im trying to use it, it's not found any text

**Cmi Version (using`/cmi version`):** 
• 8.6.9.8 BungeeCord

**Server Type (Spigot/Paperspigot/etc):** 
• PaperSpigot

**Server Version (using `/ver`):** 
• git-Paper-157 (MC: 1.14.4)

**Comment by Zrips** [comment]
Will get fixed with next build
