### ISSUE TITLE
A /fix like essentials

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2230]
I would like to see a /fix command like Essentials, where I can set a price in the configuration when people use /fix to fix an item.

**Comment by Omarlatif** [comment]
So, there is a feature like it. It's /repair. But it would be nice to add a cost feature to it. Perhaps /repair hand would cost X - or /repair all would cost Y per item.

**Comment by Zrips** [comment]
Next update will have customizable option to set items repair cost which will depend on items worth, enchant cost and items condition itself.
