### ISSUE TITLE
Quartz in /condense

### ISSUE THREAD

**Issue by QueenAngus** [Zrips/CMI#2232]
**Description of feature/improvement request:**
Hi there, I have tried to make a custom recipe to make quartz into quartz block, however /condense will still not turn quartz into its block form. If it could be added to the condense list that would be amazing.

**Comment by Zrips** [comment]
You will need to create custom recipe which turns block into quartz to be used as uncondense path. We are requiring to have the option to condense and uncondensed items both ways before you can use that.
