### ISSUE TITLE
/ptime realtime Does not return player to real server time

### ISSUE THREAD

**Issue by Frostified** [Zrips/CMI#2234]
**Cmi Version (using`/cmi version`):**  Latest release 8.6.9.8

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.14.4

Pretty self expanatory. If you type /ptime realtime it does not return the player to the same time as the server says on /time. This is very broken and needs to be fixed immediately.

**Comment by Frostified** [comment]
a way to check this is changing the world time with /time and then typing /ptime realtime and seeing that it does not work.

**Comment by Zrips** [comment]
"realtime" sets players time to actual **real world** time which will be gotten from servers location. So changing servers time with /time command will change to some custom time, while **/ptime realtime** will set to real world time. So they will be different ones. If you want to disable player ptime to servers time, use **/ptime reset**

**Comment by Frostified** [comment]
> "realtime" sets players time to actual **real world** time which will be gotten from servers location. So changing servers time with /time command will change to some custom time, while **/ptime realtime** will set to real world time. So they will be different ones. If you want to disable player ptime to servers time, use **/ptime reset**

Please add this to documentation. There is nothing on this anywhere explaining that.
