### ISSUE TITLE
Massive timings issues from CMI (Important)

### ISSUE THREAD

**Issue by JoelDeadMach** [Zrips/CMI#2235]
**Description of issue:**
Hello, so my server is not released yet, and for us is performance always priority #1, and we always check timings a few times before release. and the first we noticed is that CMI is the ONLY plugins with a lot of timings, we really don't want to release with these timings, it's almost using 100% total of timings on the server...

Please fix this asap.
https://timings.aikar.co/?id=2ec1429e50044e3c924993763f679d01

---

**Cmi Version (using`/cmi version`):** 
```
 CMI: 8.6.9.8 BungeeCord
 Server version: Paper(174) 1.14.4-R0.1-SNAPSHOT
 Vault version: 1.7.2-b107(CMIEInjector)```


**Server Type (Spigot/Paperspigot/etc):** 
paperspigot

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-1616 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
```
>....=>.... [03:22:29 INFO]: Plugins (41): AuctionHouse, Bottles*, ChatControl, CMI, CMIEInjector*, CrateReloaded, CrazyEnvoy, CustomGUI, DeluxeTags*, eGlow, FabledSkyBlock, FeatherBoard*, HolographicDisplays, JetsPrisonMines, Lottery, LuckPerms, mcMMO, MFHoppers, Minions*, MorphRedeem, Multiverse-Core, MVdWPlaceholderAPI*, NetworkManager, NoHopperCraft*, PlaceholderAPI*, PlayerVaults, PlugMan, ProCosmetics, ProtocolSupport, ProtocolSupportLegacyChest, ProtocolSupportStuff, QuickShop, ShopGUIPlus, TradePlus, Vault, VoidSpawn, Votifier, WildStacker, WildTools, WorldEdit, WorldGuard```

**Comment by JoelDeadMach** [comment]
I was planning to release this server this weekend, fixed or not i use essentialsx if this stays like this.,

**Comment by Zrips** [comment]
Issue seems to be originating from Alias.ClearBaseCommands set this to false for time being, will have to investigate what's going on with it.

**Comment by Zrips** [comment]
Ok, next update will have that feature removed and replaced with new one, more efficient one.
