### ISSUE TITLE
Tellraw hover multiple lines

### ISSUE THREAD

**Issue by MrApocalyptic** [Zrips/CMI#2237]
Basically Just Wanted To See If You Could Add Multiple Lines In The Tellraw Command For Hover Maybe Like /cmi ctellraw <H>Test1\nTest2</H>, I've Tried To Put \n But It Doesn't Send A Message And Throws An Error In Console.

/cmi ctellraw all < T >Test< /T >< H >Test1\nTest2< /H >
21.08 15:35:54 [Server] INFO Expected whitespace to end one argument, but found trailing data
21.08 15:35:54 [Server] INFO ...[{"text":"Test1\nTest2"}]}}}]<--[HERE]

Thanks For Taking Time Out Of Your Day To Read This And Hopefully It Gets Added :D
Also For Some Weird Reason Github Wouldnt Show The < And > So I Had To Put A Space Between Them.

**Comment by JasperLorelai** [comment]
Maybe instead of `\n` you could add a `<Br>` for consistency?

**Comment by Zrips** [comment]
Should work correctly with next update by using \n
