### ISSUE TITLE
Spawning rainbow sheep doesn't work

### ISSUE THREAD

**Issue by FreeMonoid** [Zrips/CMI#2238]
`/cmi spawnmob sheep:rainbow` or `/cmi spawnmob sheep:adult:rainbow` spawns a regular sheep named `jeb_` that does not change its color.

Doing `/cmi entitynbt` on the spawned sheep:
![image](https://user-images.githubusercontent.com/49086127/63475756-e5b4bd80-c486-11e9-96d3-d06c1022e4e4.png)
![Screenshot 2019-08-22 at 02 34 31](https://user-images.githubusercontent.com/49086127/63475808-17c61f80-c487-11e9-98ba-5452db5b9b18.png)
![Screenshot 2019-08-22 at 02 34 43](https://user-images.githubusercontent.com/49086127/63475809-17c61f80-c487-11e9-9d2f-035eb38618d5.png)
![Screenshot 2019-08-22 at 02 35 42](https://user-images.githubusercontent.com/49086127/63475810-185eb600-c487-11e9-82f4-4df214cb7b10.png)

---

**Cmi Version (using`/cmi version`):** 
```
[02:41:00 INFO]: --------------------------------------------------
[02:41:00 INFO]: CMI: 8.6.10.0
[02:41:00 INFO]: Server version: Paper(175) 1.14.4-R0.1-SNAPSHOT
[02:41:00 INFO]: --------------------------------------------------
```

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
```
[02:42:47 INFO]: This server is running Paper version git-Paper-175 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[02:42:47 INFO]: You are running the latest version
```

**Comment by FreeMonoid** [comment]
Manually applying `jeb_` name with name tag to regular sheep works as expected (sheep starts to change color); doing `/cmi entitynbt` on it shows slightly different JSON for name:

![Screenshot 2019-08-22 at 02 58 25](https://user-images.githubusercontent.com/49086127/63476369-404f1900-c489-11e9-9bcc-bef8d8c51144.png)

**Comment by OpticFusion1** [comment]
CMI dev fucked up how they've applied the CustomName tag, that's why it broke

**Comment by OpticFusion1** [comment]
for future reference @Zrips apply what you want to a mob MANUALLY then get THAT mobs NBT, you'll have less issues that way since you'll know how it's properly down

**Comment by Zrips** [comment]
Well it did worked in older version and it never got updated to new one. Will check it out and fix it with next update.
