### ISSUE TITLE
Rainbow leather armour is not working when you put it in armour slot.

### ISSUE THREAD

**Issue by JoelDeadMach** [Zrips/CMI#2245]
**Description of issue:**
So when you put the item inside kiteditor (rainbow colored leather armour), and use /kit Starter for example it puts the colored leather inside the armour slots, but the rainbow armour is'n updating, when you remove it from slot and readd it it works. 

So can you fix this, that the rainbow armour also is working inside the armour slots itself when equiping the kit? Thanks!

**Comment by Zrips** [comment]
Should be working correctly now with latest builds
