### ISSUE TITLE
Deathmessages gets hidden even when set to -1

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#2247]
**Description of issue:**

Even though the autohidefrom is set to -1 messages still get hidden after the first death for everyone except for the player that dies.

---

**CONFIG SECTION):**
```
  DeathMessage:
    # Defines number of players from which to automatically start hiding death messages
    # Set to -1 to disable this
    AutoHideFrom: -1
```

---

**Cmi Version (using`/cmi version`):** 
8.6.10.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper(1618)
**Server Version (using `/ver`):** 
1.12.2
**Relevant plugins (Delete if this isn't needed):**
This is the only plugin that changes death messages.

**Comment by Zrips** [comment]
Then you must be having some other plugin that disables death messages. Try testing it without any other plugin and only with CMI. If you still have issue with CMI only, let me know.
