### ISSUE TITLE
/tfly not carry over to world switch.

### ISSUE THREAD

**Issue by JoelDeadMach** [Zrips/CMI#2248]
**Description of issue:**
Description of issue or feature request:

/cmi tfly (and /cmi tgod, I assume) both reset upon switching worlds (maybe it's a Multiverse thing, or maybe it's a world restriction in the CMI config). An option in the /cmi tfly (and tgod) command to continue operating upon world change, and a secondary option to continue working even though there is a world restriction, would be fabulous. Such as: /cmi tfly (player) 900 --bypassworldrestriction:true --stayonworldchange:true

And can you add /tfly on / off they can spare their fly.

**Cmi Version (using`/cmi version`):** 
8.6.10.0

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
1.14.4 Build 172

**Comment by Seeroh** [comment]
If you have worldlimits set and a player with remaining tfly enters a world where flying is not enabled, they can no longer fly, but tfly still ticks down for them. Then, if they re-enter the world where flying is enabled, they can no longer fly again.

**Comment by Sikatsu** [comment]
@Zrips so what would be the best way to have this fixed? If I give them the bypass permission, they can fly in worlds I dom't want them too.
