### ISSUE TITLE
Interactive Commands moneycost not working! DEADLY TO ECONOMY!!!

### ISSUE THREAD

**Issue by tmellen** [Zrips/CMI#225]
I have a sign shop that uses Interactive Commands. The following is currently not working:

  - moneycost:5000#?! msg [playerName] $5000 has been deducted from your account.
  - enchant [playername] efficiency 5

If I don't have $5000 it tells me I don't have enough money. If I do have $5000, it sends the MSG, then gives me the enchant... yet my balance remains the same.

This happens if I use CMI Injector on the old vault, or if I use the new recompiled vault.

Either way  -- any of my players can click on any of the signs in the magic shop and fill up on high-cost enchantments for free!!!

CMI version:    7.6.4.0
Vault version:  1.6.8 (from CMI spigot page)

**Comment by tmellen** [comment]
Note: Added workaround to every IC that uses "moneycost" by adding a final line that does CMI money take [playername] amount

It's broke in 7.6.3.2., also using CMI Injector.

**Comment by Zrips** [comment]
For time being you can rename to 
- moneycost:5000#?! cmi msg [playerName] $5000 has been deducted from your account.
This should be fixed with next build.
