### ISSUE TITLE
CMI causes console errors

### ISSUE THREAD

**Issue by konsyr11** [Zrips/CMI#2252]
Every time CMI starts or a command gets run, LOADS of errors come up in the console

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[PasteBin](https://pastebin.com/nU4q8p7D)
```
---
**Cmi` Version (using`/cmi version`):** 
8.6.4.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-798ea6a-2012f1e (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):**
All plugins: CoreProtect, CustomLoginMessages, LuckPerms, PluginConstructorAPI, WorldEdit, OldCombatMechanics, SimpleDonations, BlockLocker, ColoredChat, DragonDeathDrops, SleepCast, Vault, BanManager, Multiverse-Core, DiscordSRV, ChestCommands, DiscordSRV-Staff-Chat, bChatManager, CMI

**Comment by stashenko** [comment]
`'&f------------------------------`
should be like that
`'&f------------------------------'`

**Comment by stashenko** [comment]
you made a mistake in the file **tabList.yml**

**Comment by konsyr11** [comment]
Oh, ok. I will check that. If that is the case (which probably is) it solves my other issue too!
Thank you so much. I will close the thread if everything is ok

**Comment by konsyr11** [comment]
So, I went through the tablist.yml (which I knew there was something wrong with, as I could see "could not load tablist.yml" in the cosnole), but I cannot find that error. Everything is fine. TabList.yml attached below.
[tablist.yml](https://pastebin.com/YhQ3LSRyl)
@stashenko

**Comment by LogGits** [comment]
@konsyr11
