### ISSUE TITLE
Ungod in PvP

### ISSUE THREAD

**Issue by QueenAngus** [Zrips/CMI#2254]
**Description of feature/improvement request:**
Hi there,
I would love a way to disable people's god when they enter PvP, or at least a command to force a disable for God (not a toggle on/off) so I can make a 3rd party plugin force disable it.

Thanks!

**Comment by Zrips** [comment]
But you could simply perform **/cmi god [playerName] false -s** with your 3rd party plugin to disable god mode on that player. We could add some extra option in pvp config section to have it disabled automatically and maybe some permission node to bypass it in case some of the player should not be taken out of combat. And you do have custom events like CMIPvPStartEventAsync. And on top of that you have event commands which has pvpstart, where you could perform god command automatically when player enters combat mode, silently with -s.
