### ISSUE TITLE
balance reset randomly.

### ISSUE THREAD

**Issue by MothGirlMusic** [Zrips/CMI#2259]
**Description of issue:**
when players earn money or something after some time they have different balance values much lower than what they started with. a player who had 200k a moment ago now has 3k. another player who had 30k has now 300.

---

---

**Cmi Version (using`/cmi version`):** 
![屏幕快照 2019-08-26 07 03 46](https://user-images.githubusercontent.com/1746550/63686422-d5c31380-c7cf-11e9-89f7-0bb5b35bb800.png)

**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
![屏幕快照 2019-08-26 07 06 17](https://user-images.githubusercontent.com/1746550/63686513-10c54700-c7d0-11e9-8b16-79058d936935.png)

**Comment by Sikatsu** [comment]
I actually experience this aswell with some players. Aswell for duplicated users in baltop.

**Comment by LogGits** [comment]
When did this start happening?

**Comment by Sikatsu** [comment]
Been like that since I bought CMI 1-2 weeks ago. Not using CMIEInjector but the recompiled vault version.

**Comment by iTemmy** [comment]
I am also getting the balance reset, but it is happening to everyone on my server after a restart, it resets everyone balance back to the starting balance
06.09 14:25:27 [Server] INFO --------------------------------------------------
06.09 14:25:27 [Server] INFO CMI: 8.6.12.1 BungeeCord 
06.09 14:25:27 [Server] INFO Server version: Paper(163) 1.14.4-R0.1-SNAPSHOT
06.09 14:25:27 [Server] INFO Vault version: 1.6.11(+)
06.09 14:25:27 [Server] INFO --------------------------------------------------
Re-compiled Vault for economy
