### ISSUE TITLE
Option to disable offline teleportation?

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2261]
So I noticed when I use /tp or /tpo on a nickname, it sometimes randomly teleports me to a location. When using /realname <nickname> I found out it teleports me to a player who is offline. And not the player I wanted to teleport to which is online.

Is there a way to disable offline teleportation? So it doesn't teleport me to the wrong one each time.

**Comment by LogGits** [comment]
What are both online username and the offline users name? Also please provide the exact command usage that you used to teleport to the online player.

**Comment by Sikatsu** [comment]
So I wanted to teleport to someone called ''MartijnW''

But there is a player offline with a nickname that is ''Martijn''

http://prntscr.com/oxou49

When I used /realname Martijn it seems that /tpo Martijn teleports me to someone completely different who is offline, not the player who is online ''MartijnW''

It's a bit confusing, I just wanna teleport to online players, not offline players.

**Comment by Baktus79** [comment]
I don't think you can turn that off. I love the offline teleport function as I can teleport to players after they have disconnected. I got many reasons for why this is a great feature, but the number one reason is that it helps me as a server owner to do my job much easier.

**Comment by Sikatsu** [comment]
It's nice yes, but it would be nice perhaps instead of turning it off, that you can use parameters like -o for online players or something.

**Comment by sandwally** [comment]
# When this set to true by using any command, requiring players name, in case plugin cant determine player by given full name, then partial matches from online players will be used. In example: /cmi heal rips can heal player Zrips 
  # Useful when you have players with complicated names
  PartialPlayerName: true

With that on it looks like it's supposed to do as your want it, only to online players.

**Comment by Zrips** [comment]
Should work correctly now, online players are prioritized now even if we would have offline one with same name (different capitalization or something)
