### ISSUE TITLE
Merge /back and /dback

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2263]
Currently if you die and use /back it won't teleport you to the death location, you have to use /dback instead. Would it be possible to merge those commands together so it works for everything including death location?

**Comment by SeruhioX** [comment]
You can use cmi.command.back.ondeath for allow to back to death location with /back.

Regards

**Comment by Sikatsu** [comment]
It doesn't sent you to the exact death location like /dback so i'm not sure if that's the case.

**Comment by Zrips** [comment]
Giving player cmi.command.back.ondeath should be enough to allow him to return to his death location  with regular /back command

**Comment by Sikatsu** [comment]
Yup, I just didn't know when I made the ticket. You can close this one!
