### ISSUE TITLE
Kit menu improvements (hide attributes)

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2264]
**Description of feature/improvement request:**

It would be nice if you can hide attributes and enchants from showing in the lore.

http://prntscr.com/oxpver
http://prntscr.com/oxpvj2

And is it possible to add a space between the NAME and the LORE?

**Comment by sandwally** [comment]
Cmi's own "/cmi hideflags hide_attributes" seems to not remove mainhand text
You can do it by spawning the items with 
/i iron_axe {HideFlags:3} "Will hide enchants and attributes" 
And then you can add lore, enchant and name to the item.
Place it as a icon for your kit.

**Comment by Zrips** [comment]
This is actually an excellent point, will make some adjustments for GUI handling which will include a way to hide things like that as we dont need to show them in some specific areas like kit gui selection UI. Will add this with next update.

**Comment by Sikatsu** [comment]
Awesome! And a break between name and lore perhaps? :)

**Comment by Zrips** [comment]
@Sikatsu 
Well, i can add that, it's not like some 5 hour work, its literally lore.add("");

**Comment by Sikatsu** [comment]
Haha, awesome! Thanks :)
