### ISSUE TITLE
Wrong permission for /pweather freeze

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2266]
Not sure why, but for some reason /pweather freeze listens to pweather.others permission?

>.... [22:43:56 INFO]: ThijsLengkeek issued server command: /pweather freeze
>.... [22:43:56 INFO]: ThijsLengkeek doesn't have permission for: cmi.command.pweather.others

**Comment by sandwally** [comment]
Don't think you can freeze time with pweather and it's trying to use it on a player named Freeze

**Comment by Sikatsu** [comment]
Then it would be nice if pweather will also have freeze support :)

**Comment by Remski01** [comment]
I think its better for the /ptime command tbh, as /pweather effects weather, and /ptime effects time, and freeze would be more related to time.

**Comment by Sikatsu** [comment]
You're right! Then this is no longer an issue.
