### ISSUE TITLE
Force op using placeholders in commands

### ISSUE THREAD

**Issue by swervv** [Zrips/CMI#2268]
Players can force console and other players to perform commands (including /op) using placeholders in commands.

Players can do /(cmi command that has alias enabled) {placeholder}

Examples for op: 
`/me {command_asconsole:op swervv}`
`/msg swervv {command_asconsole:op swervv}`
`/kit {command_asconsole:op swervv}`

I have only been able to get this working with commands that have the alias set to true in CMI/Alias.yml 

Additionally the placeholders are parsed before the permission check so if a player doesn't have to have permission to do the command for the placeholder to be parsed.

Only immediate solutions I have found is to remove MVdWPlaceholderAPI which renders all of MaximMVdW's plugins unusable or remove the aliases of the commands from Alias.yml (this works but means all commands have to be executed using /cmi <command>) and restart the server.

Proof of method:
https://imgur.com/8G1tX9n

Plugins on server: (all latest version available on https://spigotmc.org using default* config files)
https://imgur.com/ew35yWb

Placeholder list:
https://www.spigotmc.org/wiki/mvdw-placeholders/

*cmi has all command aliases in CMI/Alias.yml set to true

**Cmi Version: 8.6.10.0** 

**Server Type: paperspigot** 

**Server Version: 1.12.2** 

**Relevant plugins: MVdWPlaceholderAPI**

**Comment by SeruhioX** [comment]
Yo can enter in config of the Maxim plugin like FeatherBoard, find and replace

update-method: "COMPATIBLE"

to 

update-method: "UPDATE_ONLY"

Remove command jar in folder modules inside featherboard/other plugins by maxim... and restart the server

It's a temporary solution

**Comment by Zrips** [comment]
Placeholder replacement will be disabled in alias commands for time being to avoid this issue.
