### ISSUE TITLE
BUG? /r does not seem to work properly

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/CMI#227]
hello Zrips

Some of my players report that the / r command would not work properly.
Again and again the message is sent to another player.
Often it should happen that this player is not online at all.

As an an example

Max1234 writes to Lisa2000: / msg Lisa2000 Hello nice to see you
Lisa 2000 answers: / r hei max

but in the chat comes the following:

Lisa 2000 -> Admin: hei Max

Somehow, something seems to be broken there. As soon as this problem occurs again I take screenshots of the chat and the console

**Comment by Zrips** [comment]
Its depends what displayname they have and what you have set as format for private messages. If Max1234  has displayname as Admin then you will see that **Lisa 2000 -> Admin: hei Max** simply doublecheck your locale file for formats hen receiving and sending private messages.

**Comment by LogGits** [comment]
Provide screenshots of this. Are you saying you want it to be like /r goes to the person who messaged you last?
