### ISSUE TITLE
Sitting through locked doors

### ISSUE THREAD

**Issue by BurntValentine** [Zrips/CMI#2273]
**Description of issue:**

When there is a carpet/slab/stairs behind a locked door (locked via LWC) you glitch through the door to sit down when you right click - I know there's the double click option that will help with this but would it be possible to stop this happening in general?

**Cmi Version (using`/cmi version`):** 

28.08 09:01:04 [Server] INFO --------------------------------------------------
28.08 09:01:04 [Server] INFO CMI: 8.6.10.0-> 8.6.11.0
28.08 09:01:04 [Server] INFO Server version: Paper(642) 1.13.2-R0.1-SNAPSHOT
28.08 09:01:04 [Server] INFO --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** Paper version git-Paper-641 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):** ModernLWC 2.1.5 (https://www.spigotmc.org/resources/modern-lwc-continuation-of-lwc.2162/)

**Comment by BurntValentine** [comment]
I assume this is still the case in 8.6.11.0 as I can't see anything in the changelog for this, but I shall update soon and close this if it's no longer an issue

**Comment by Zrips** [comment]
if doors are closed then player should not be able to interact with blocks behind it. Unless LWC doesn't cancel event properly in which case i cant really do anything about that from my end. Protection plugin should cancel even in which case player cant interact with a block behind doors.
