### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by FshJank** [Zrips/CMI#2278]
Spigot 1.14.4
Plugin version: 8.6.10.0

Hello I have a question I am using cmi in 1.14.4
and the silktouch doesn't seem to work 
I also wanted to know if you'd add the lfix option.
the command I get a message that in this version
lfix does not work
silktouch for spawners

**Comment by kassadGLA** [comment]
Confirm, `lfix` does not work with 1.14.x. May be 1.14 do not have longer problems with light?

**Comment by mercurialmusic** [comment]
Using silktouch with spawners works for me, but it is heavily permission-dependent. It would be useful if you posted the `Spawners:` section of your config along with the relevant snippets from your existing permissions plugin.

lfix isn't implemented in CMI in 1.14, but it isn't really necessary either...

**Comment by CaliDreams** [comment]
lfix is still very much in demand, for those of us still causing lighting issues with plugins such as FAWE (worldedit). I have them all over my heavily landscaped 1.15.1 spawn map with no way to update the shadows, as FAWE's built-in //fixlighting hasn't been implemented either, and probably won't be for a long time or ever, as they are still even just trying to power through all the wreckage 1.13's changes made for them. There's a separate plugin I've found for it, but only updated for 1.14.
