### ISSUE TITLE
totem bossbar cooldown show bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#2284]
![image](https://user-images.githubusercontent.com/5382252/63960645-92172500-cac1-11e9-82d1-e56b1ca75c35.png)

the totem bossbar Will not disappear 
Will increase indefinitely

**Cmi Version (using`/cmi version`):** 8.6.11.0

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.14.4

**Comment by TheoRetisch1** [comment]
I'm facing the same problem. The bossbar simply stops, the countdown does not expire. The bossbar disappears only after a Relog. The problem occurs by default when the totem cooldown is activated.  However, if a player enters /toggletotem once, the countdown will run down normally and the boss bar will disappear.

Paper 1.13.2 - 650
CMI 8.6.15.0

**Comment by KnifeKat** [comment]
![2019-12-13_13 56 06](https://user-images.githubusercontent.com/30131039/70828356-d5677c00-1db0-11ea-8d89-0a6cf62e4a79.png)


Same issue persists on CMI Version 8.6.16.3. 

Same as @TheoRetisch1 mentioned. The Bossbar stays forever after a death. Even after the 15min has passed. 

Only doing /totemtoggle does it repost a new Bossbar with the totem timer, to tick down until its recast.

**Comment by TheoRetisch1** [comment]
The bug is fixed in version 8.6.21.5, but now there is another problem #3065.
