### ISSUE TITLE
Using command heal

### ISSUE THREAD

**Issue by ZagyMC** [Zrips/CMI#2288]
When we add permission to a player to use /heal, he can use command /heal all aswell. This should not be possible. He cant use command /heal others, for example, u cant use command: "/heal Notch" without permission cmi.command.heal.others, but u can use command "/heal all with only permission cmi.command.heal. We would love to disable this option, so they could heal themself only.

---

**Cmi Version (using`/cmi version`):** 
CMI8.6.11.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.14.4

**Comment by Zrips** [comment]
Fixed
