### ISSUE TITLE
/repair - no permission?

### ISSUE THREAD

**Issue by ChitterChatter** [Zrips/CMI#2290]
Hi there. My players in legend group and above are unable to do /repair.  When they try, they get an error that states they don't have the permission.

I even added in a couple of the repair perms, the hand, all, armor. 

The group Legend is supposed to have /repair. Here are some pics. 

This is the groups repair perms.
![image](https://user-images.githubusercontent.com/28234726/63992511-0db4aa00-caa1-11e9-93e6-7278fd6bce0a.png)

I even tried adding it again....got this..
![image](https://user-images.githubusercontent.com/28234726/63992153-6d11ba80-ca9f-11e9-9d55-fadd466159df.png)

player goes to repair and gets this......
![image](https://user-images.githubusercontent.com/28234726/63992424-8d8e4480-caa0-11e9-849a-31040bbe0dfe.png)

Console says this......
![image](https://user-images.githubusercontent.com/28234726/63992620-8ca9e280-caa1-11e9-9029-f8cadf6071ee.png)

So, I even personally added the perm to her instead of the group add

![image](https://user-images.githubusercontent.com/28234726/63992668-c975d980-caa1-11e9-9c74-ccd0d189122b.png)

and I still got this....
![image](https://user-images.githubusercontent.com/28234726/63992646-aea36500-caa1-11e9-90ad-df54ef932536.png)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
My CMI config: 
[EHBV0FhN.txt](https://github.com/Zrips/CMI/files/3558268/EHBV0FhN.txt)

---

**Cmi Version (using`/cmi version`):** CMI 6.11.0

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot

**Server Version (using `/ver`):** 1,14,4

**Relevant plugins (Delete if this isn't needed):** LuckPerms

**Comment by natr566** [comment]
Is this the only command you have this issue with?

**Comment by ChitterChatter** [comment]
This started to work too. I don't know why it was doing that or what fixed it. Seems to better now. thank you for looking into it <3
