### ISSUE TITLE
Problem with Homes

### ISSUE THREAD

**Issue by Kryt3r** [Zrips/CMI#2293]
**Description of issue:**

all the home commands didn't work so well on my server. 
i can use the command **/sethome Test** for example, it creates the home "Test", but if i use the command **/home**, **/homes** or **/removehome Test** it calls me "There is no saved homes". same with **/cmi home** etc..
commands are set for players and i've tried it with OP

no console errors

---

**Cmi Version (using`/cmi version`):** 
8.6.11.0

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.14.4

**Comment by mercurialmusic** [comment]
Is other player data saving? Like economy balance or inventories? Any startup errors? And do you have any other plugins (like Essentials) that also save homes?

**Comment by Kryt3r** [comment]
had on start problems with the economy balance, but now it works without problems. 
i've many errors on start up from the server, created a post here -> https://github.com/Zrips/CMI/issues/2292
no... since i've bought cmi i've removed it from my server and all other plugins that are include in CMI
