### ISSUE TITLE
Attach/interactive commands does not work with specific command.

### ISSUE THREAD

**Issue by kassadGLA** [Zrips/CMI#2295]
**Attach/interactive commands does not work with specific command.**

Hello!
I have the BigDoors plugin installed, which has the following commands:

`closedoor <ID 1> <ID 2>...<ID X>`
`opendoor <ID 1> <ID 2>...<ID X>`

I can easily attach the `closedoor` command to any item or use it as an interactive command. But this does not work with the `opendoor` command. Both commands work as expected when I enter them manually in the game chat or in the console.

Best regards.
---

**Cmi Version (using`/cmi version`): 8.6.11.0** 

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): git-Paper-171 (MC: 1.14.4)**

**Comment by mercurialmusic** [comment]
I doubt this would be a CMI issue... have you tried using the asPlayer! or asConsole! [prefixes](http://www.zrips.net/cmi/commands/specialized/) on the attached commands? Since BigDoors explicitly does not support Paper it might otherwise be some issue there, but I'd bet using one of those prefixes would solve it.

**Comment by kassadGLA** [comment]
@mercurialmusic To be honest, I don’t see any logical connection between your comment and my problem.
Even if I try to attach or use as interactive command a `nonexistentCommand`, then CMI must try to execute it anyway. In this case, I just get the message "unknown command" in the chat or console, depending on the prefixes `asPlayer!` or `asConsole` (I tried all cases). In the case of the `opendoor` command, nothing happens.
As I wrote above, `both commands work as expected when I enter them manually in the game chat or in the console`. So no any issues with BigDoors plugin. I used exactly the same way of attaching or using as an interactive command like in the case of the `clososedor` command. Then `closedoor` - works, `opendoor` - no. This information is quite enough to understand that the command `opendoor` is not sent to the chat or the console.
Best regards.

**Comment by mercurialmusic** [comment]
CMI doesn't discriminate against commands. If one of them is working then likely the way you are doing the other or the way the other plugin registers the command is incorrect. Using the `asConsole!` (case sensitive) prefix will pass all information after the `!` directly to the console as if being run from the console itself. If the console recognizes your closedoor command but not opendoor when both are run from an attached command with the `asConsole!` prefix then it is an issue with the other plugin or your setup, not CMI. How a command is run matters. `asPlayer!` runs the command as if the player typed it themselves. `asConsole!` runs the command as if a command block or from console directly. What follows is then up to the plugin.

**Comment by kassadGLA** [comment]
Thank you very much for the detailed explanation of what I wrote above.

**Comment by kassadGLA** [comment]
Additional Information.
Put some item in the main hand and use the command:
```
/cmi attachcommand !cc!closedoor 1
```
Then use the item with the attached command. Console output:
```
[09:15:37 INFO]: [BigDoors] Door "1" cannot be closed as it is already closed!
[09:15:37 INFO]: kassad_gla issued acmd command: /cmi shadowcmd 879619225
```
Here we see a message from the target plugin. So everything is working fine.
_
Now put some other item in the main hand and use the command:
```
/cmi attachcommand !cc!opendoor 1
```
Then use the item with the attached command. Console output:
```
[09:22:52 INFO]: kassad_gla issued acmd command: /
```
Here we see in the case of the `opendoor` command CMI sends to the console just "/"
There is no doubt that the problem is on the side of the CMI.

Best regards.
