### ISSUE TITLE
Setworth GUI 0.1 broken

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#2297]
The GUI in /cmi setworth option for 0.1 does not work and sets the value to 1. The setworth also does not support quantities which is annoying when setting worth for existing shops that sell 16 or 64 quantities. 

Paper 1.14.4 
CMI 8.6.11.0

**Comment by 0xC1A551C** [comment]
Also the ids are pretty messed up: TURTLE_EGG>TURTLE   ACACIA_WOOD is LOG

**Comment by Zrips** [comment]
Should be working correctly now
