### ISSUE TITLE
/r and /msg issues

### ISSUE THREAD

**Issue by iaxedu** [Zrips/CMI#23]
While working on a server that was empty I noticed that my console spammed a personal conversation from another server in my network running CMI 7.3.10.0. I have 2 pastebin links that show what happens from both servers. And for some reason only this conversation got broadcasted to the console of the server I was working on. 

Server where I was working: [https://pastebin.com/6wTmHXVu](https://pastebin.com/6wTmHXVu)
Server where the conversation happened: [https://pastebin.com/URNQjvSC](https://pastebin.com/URNQjvSC)

This was the first time I noticed it was possible to hold a conversation with someone from that server but that didn't go very well it showed up as follow: [https://i.imgur.com/6PNH7O4.png](https://i.imgur.com/6PNH7O4.png) [https://i.imgur.com/Hu2LKOw.png](https://i.imgur.com/Hu2LKOw.png)

Searched for config options for bungee but couldn't find anything.

**Comment by LogGits** [comment]
@iaxedu is this issue still present in the latest build of CMI?

**Comment by iaxedu** [comment]
I do not see this in my console anymore :) Tho I did open another ticket with an issue that I've had for a long time now.

**Comment by LogGits** [comment]
Ok I am going to close this for now, if the issue persists please reopen this.
