### ISSUE TITLE
Tablist rank sort

### ISSUE THREAD

**Issue by JoelDeadMach** [Zrips/CMI#2300]
**Description of issue:**
Hi, So my question is since a few versions ago now randomly tablist does not sort ranks anymore on tab? why is this feature removed?
Now it's really disgusting on my tablist, and i hate that...

Can you please readd it?

---

**Cmi Version (using`/cmi version`):** 
8.6.12.0

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
1.14.4

**Comment by Zrips** [comment]
Tablist sorting requires some extra work and slightly different approach to solve some minor issues related to it. it will be readded in time.
