### ISSUE TITLE
The raw text <URL> tag does not escape color codes properly.

### ISSUE THREAD

**Issue by impmallet** [Zrips/CMI#2315]
**Description of issue:**
When using the raw text code in a custom text file, URLs that have an & in them are seen as a color code instead of being escaped as raw text.

Example Code:
`<T>Here</T><URL>https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=Z69DY8WSSPJ4Y&currency_code=USD&source=url</URL>`

This displays as follows:
![image](https://user-images.githubusercontent.com/35946139/64129034-97a59100-cd87-11e9-8b0e-f6709cedf816.png)

This caused the URL to not include required characters and is thus broken.

CMI Version: 8.6.12.0

Server Type: Paper

Server Version: Paper 183 1.14.4-R0.1-SNAPSHOT

**Comment by sandwally** [comment]
Might not work but try &&bb and &&cc until it's fixed

**Comment by impmallet** [comment]
> Might not work but try &&bb and &&cc until it's fixed

Didn't work, but thank you for the suggestion.

**Comment by impmallet** [comment]
Still broken as ever.  Wonder if this will ever get looked at.

**Comment by impmallet** [comment]
7 months since the initial report. Not a single acknowledgement by the dev.

Bravo, great support.

**Comment by impmallet** [comment]
This is. still broken! This affects pretty much anything other than the most basic links. How has this gone on so long???

**Comment by WolverStones** [comment]
It is necessary to realize that it is not easy to make such a plugin like CMI.  I recommend using discord it's a faster form of communication.

**Comment by impmallet** [comment]
> It is necessary to realize that it is not easy to make such a plugin like CMI. I recommend using discord it's a faster form of communication. https://discord.gg/dDMamN4

Of course I understand it is not easy, but this report has been open for 10 months, very close to a year, and I find it hard to believe it is that difficult to fix a text formatting issue vs some of the other more bizarre bugs that this plugin faces. I am not asking the world. Also, please keep in mind, that like anyone else using this plugin, we paid for it, asking for a working product is not unreasonable. I am not demanding new features, just that what is there works as intended.

Also, I have been on the discord, no one ever replies other than other members and they are often rude / unhelpful. Only the dev can help in this situation, and he does not check his discord.

**Comment by Zrips** [comment]
Getting fixed with next build.
I'm rare visitor on a discord because its usually filled with some distracting stuff. You can always send direct pm to me, which will be simpler to address instead of going throw multiple discord channels and scrolling throw hundreds of chat lines looking for something i might need to get my attention to. 
Sorry for long wait.
