### ISSUE TITLE
/cmi kitusagereset not work

### ISSUE THREAD

**Issue by kassadGLA** [Zrips/CMI#2318]
**Description of issue:**

`/cmi kitusagereset` does not work.
I created kit named `qwerty` with 3 times usage. Then used the command
```
/cmi kitusagereset qwerty kassad_gla
``` 
Nothing has happened. No any result output in chat or console. Then I tried use the kit all 3 times and again use the command. Again no any result output in chat or console and kit usage counter not reset.

Best regards.

---

**Cmi Version (using`/cmi version`): 8.6.12.1** 

**Server Type (Spigot/Paperspigot/etc): Paper(176)** 

**Server Version (using `/ver`): git-Paper-176 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)**

**Comment by kassadGLA** [comment]
I am solved problem using `cmi resetdbfields Kits -w:w -p:kassad_gla`, but I think this is not good solution.

**Comment by Zoneman1972** [comment]
I can confirm this is also happening on my server as well as the bypass permissions for 1 time use kits aren't working either. 
CMI Version 8.6.16.5
Server Version Paper (31) 1.15.1-R0.1-SNAPSHOT
