### ISSUE TITLE
CustomRecipe remove bug

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#2323]
**Description of issue:**
Hi,
My problem is that if I add recipe and than I will remove it, players can still craft that item even if I removed it and did /cmi reload, this issue can only get fixed by restarting server with sometimes can be annoyed, would it be possible to remove the recipe just by reloading plugin and not being required to restart the server.

CMI version: 8.6.12.1

Server Type: Paperspigot 1.14.4

**Comment by blek-id** [comment]
That is an intended thing. Recipe can only be removed by restarting

**Comment by arturek1666** [comment]
As this was intended I am closing the post.
