### ISSUE TITLE
Towny balance not showing up on /baltop

### ISSUE THREAD

**Issue by Nesseley** [Zrips/CMI#2325]
**Description of issue:**
My town doesn't appear on /baltop even tho it should.
Picture of balance: https://gyazo.com/d3dc0f5d978d824cac5189aaa9f2f073
I should be on place 8 here.

---

**CONFIG SECTION:**
```
`ExcludeStartingWith:`
`    - baltop`

Tried removing the blocked town- things that are there from default. Does not work.
```
---

**Cmi Version (using`/cmi version`):** CMI: 8.6.12.1

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** This server is running Paper version git-Paper-175 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by Sakanas** [comment]
can you solve it? I'm having the same problem :/

**Comment by Zrips** [comment]
This might have required for IncludeFakes to be enabled as none player accounts gets marked as fake ones by default and gets skipped to avoid cluttering baltop with random entries.

**Comment by Nesseley** [comment]
> This might have required for IncludeFakes to be enabled as none player accounts gets marked as fake ones by default and gets skipped to avoid cluttering baltop with random entries.

Yeah this issue was fixed a while back! Forgot about this ticket tho :)
