### ISSUE TITLE
7.6.5.0 wrong version/kills alias commands.

### ISSUE THREAD

**Issue by tmellen** [Zrips/CMI#233]
Description of issue or feature request:

#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR:
```
CMI 7.6.5.0 reports itself as being version 7.6.4.1
Also it replaced alias.yml with all aliases off.
```

Cmi Version (using`/cmi version`): 7.6.5.0
Server Type (Spigot/Paperspigot/etc): Spigot
Server Version (using `/ver`): 1.12.2-R0.1

**Comment by Zrips** [comment]
Fixed.
