### ISSUE TITLE
Spawners contdown even in creative and braeek spawners hand (not pickaxe )

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#2337]
I break spawners for hand and spawner drops (i'm an admin and do it in creative).

---

**Cmi Version newest** 

**Server Type: paper:** 

**Server Version 14.4 (we use so new we can :))** 

**Relevant plugins cmi, Residence,wildchest,wildstacker,epichhoppers,treefaller **

**Comment by Zrips** [comment]
Having bypass permission for spawner drop causes spawner to drop independent with what you break it.

**Comment by broken1arrow** [comment]
> Having bypass permission for spawner drop causes spawner to drop independent with what you break it.

See the title was right but not the text.

If you destroy a spawner with the wrong tool or with your hand, it takes a charge.

Is this a bug or can this be set?

**Comment by Zrips** [comment]
Well change should be taken in case spawner got destroyed and dropped independent of a tool

**Comment by broken1arrow** [comment]
> Well change should be taken in case spawner got destroyed and dropped independent of a tool

and if you wrong tool, so it not get dropped (if you not use chance)?

**Comment by broken1arrow** [comment]
> Well change should be taken in case spawner got destroyed and dropped independent of a tool

Soo do I need open new issue? 

I talk about when you use wrong tool or hand, it use one charge .

Is not so fun if I will remove a spawner for a player and it counts down charge.
