### ISSUE TITLE
moneycost! with interactive command does not work.

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#2342]
works
moneycost:150#! cmi heal [playerName]

does not take money
moneycost:150#! enter non-cmi command here

works
moneycost:150#! cmi

does not take money (using treasureeye plugin)
moneycost:150#! eye give [playername] 1

**Comment by Zrips** [comment]
Specialized commands works best with CMI commands, for money cost when using different commands can be achieved with help of new commandCost.yml file
