### ISSUE TITLE
Serious console error

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#2344]
![image](https://user-images.githubusercontent.com/5382252/64627453-413cf000-d422-11e9-8f38-e301ad6ab8e2.png)

Serious console error , check

**Cmi Version (using`/cmi version`):** 8.6.13.0

**Server Type (Spigot/Paperspigot/etc):**  paper 

**Server Version (using `/ver`):** 1.14.4

**Comment by Zrips** [comment]
For time being set DisableExpPickup to false in config file, will fix this error with next update
