### ISSUE TITLE
Playtime unexpectedly reset

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#2352]
**Description of issue:** Some of the players with a high playtime are reset to 0 when server is restarted. Playtime of the player is around 50 days, happened twice after I refunded his playtime, a restart, then his playtime is set back to 0 again.

---

**Cmi Version (using`/cmi version`):** 8.6.13.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.13.2

**Comment by Sikatsu** [comment]
Yep, same here. On 1.14.4

**Comment by blek-id** [comment]
Still happening on 8.6.13.4 @Zrips please help  us out

**Comment by IsRealMe** [comment]
Still happening on 8.6.24.0, looks like problem is rly old and dev doesn't care much about it...

**Comment by blek-id** [comment]
It's fixed on 8.6.24.0. No idea what you're talking about @IsRealMe 
he's been really active on fixing this bug.

**Comment by IsRealMe** [comment]
To be more specific, I suspect it happened to one of my players after he's got kicked for afk (feature of cmi also) and server restart.
