### ISSUE TITLE
All nicknames disappeared in 7.6.5.2

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#236]
Description of issue or feature request:
Whatever was fixed in 7.6.5.2 removed all of our nicknames from both tablist and chat (using VentureChat). We previously used "%player_displayname%" as the placeholder in the tablist and use '{prefix}{nickName}' for the nickname format. 

Changing the tablist placeholder to "%cmi_user_display_name%" solved the tab issue, but we couldn't figure out anything for nicknames. Tried several placeholders both in CMI and our chat plugin and nothing worked, with restarts between each try. Downgrading back to 7.6.5.1 solved the problem, nicks reappeared, etc. Left the new tablist placeholder since it worked.

ERROR:
No errors in console.

Cmi Version (using`/cmi version`): 7.6.5.2
Server Type (Spigot/Paperspigot/etc): Spigot
Server Version (using `/ver`): 1.12.2-R0.1-SNAPSHOT [Latest]

**Comment by Zrips** [comment]
Will revert back some changes previously made which had caused this one. Should work as before after todays update.
