### ISSUE TITLE
Cooldown bypass does not work for head command

### ISSUE THREAD

**Issue by runelynx** [Zrips/CMI#2361]
**Description of issue:**
Granting perm cmi.cooldownbypass.head to a user does not allow the cooldown bypass to work. 
The /head command still has a cooldown for them.

![image](https://user-images.githubusercontent.com/5877481/64901172-4df05c80-d64b-11e9-9b67-21c97f782b19.png)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
 
![image](https://user-images.githubusercontent.com/5877481/64901196-7c6e3780-d64b-11e9-8be0-88240dcca8cc.png)

```

---

**Comment by runelynx** [comment]
![image](https://user-images.githubusercontent.com/5877481/64901200-8859f980-d64b-11e9-8805-2aedf1afb662.png)

**Comment by runelynx** [comment]
Note that the cooldown is bypassed for ops.. so there is a perm that does it; the one listed in documentation is just incorrect.

**Comment by Zrips** [comment]
Permission mentioned in comments should be correct one, wiki page could have been some what outdated
