### ISSUE TITLE
Question about /cmi

### ISSUE THREAD

**Issue by maxmooshroom** [Zrips/CMI#2367]
Hello. I was wondering if there was a way to disable or get around /cmi being in front of every command (e.g. /tpa (name) instead of /cmi tpa (name). Thank you!

**Comment by jannikrouthe** [comment]
![image](https://user-images.githubusercontent.com/29755384/64957418-30123a00-d88d-11e9-8d5a-045db0eb17eb.png)
this file can you do it if you set it too true and restart :)
