### ISSUE TITLE
Bungee network sync dosn't work

### ISSUE THREAD

**Issue by BenjaminHoegh** [Zrips/CMI#2378]
Player data doesn't sync cross-server on a bungee network even when using a database, if you example set a nickname of a player, then join another server you have a 50/50 chance to keep the nickname, but if you switch the nickname off again then it doesn't sync to the other servers.

The sad thing is I really like how much control this plugin gives you, but there so many bugs and issues on bungee networks that I have hard to find a reason to use it

**Comment by AntoineHrn** [comment]
+1
homes/warps/tp/back won't work
economy won't have an offline support if there are offline payments.
