### ISSUE TITLE
MCMMO chat messages norregistering names

### ISSUE THREAD

**Issue by tmellen** [Zrips/CMI#238]
Description of issue or feature request:

#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR:
```
MCMMO no longer displays player names in it's partychat or admin chat. it just states "[] hello" instead of "[tmellen] hello" Affecting all player. Vault related?
```

Cmi Version (using`/cmi version`): 7.6.5.2
Server Type (Spigot/Paperspigot/etc): Spigot
Server Version (using `/ver`): 1.12.2_R0.1

**Comment by MCTyler** [comment]
I just switched back to the Injector. Messing with Vault is not the way to go since so many plugins rely on it.

**Comment by tmellen** [comment]
I switched to injector 1.0.3, and the original vault i was using before. still not working. :/ trying to figure out why.

**Comment by Zrips** [comment]
Will revert back some changes previously made which had caused this one. Should work as before after todays update.
