### ISSUE TITLE
Kit Colors

### ISSUE THREAD

**Issue by Aikowyjoov** [Zrips/CMI#2380]
**Question: ** Is there a way to edit each kits name and change the colors on the time from orange/yellow to something else?
![Screenshot_58](https://user-images.githubusercontent.com/55589558/65330625-4553d500-dbbb-11e9-80a1-e6712d016206.png)

**Comment by mercurialmusic** [comment]
Kit names can be changed either with /cmi kiteditor or in the kits.yml inside the CMI plugin folder.

The lore lines can be changed in /CMI/Translations/Locale_XX.yml, but they would be changed for all kits - you wouldn't be able to change the colors for individual kits. That would be a nightmare.

**Comment by Zrips** [comment]
Added option to define display name for kits
