### ISSUE TITLE
latest update possibly broke economy compatibility with other plugins

### ISSUE THREAD

**Issue by emanuelitor** [Zrips/CMI#2381]
**Description of issue:**

so i was using cmi build cmi version 8.6.13.1 with savagefactions just fine then i updated cmi to 8.6.13.2 and it broke depositing money in the faction bank... example command "f money deposit 100" so i switched back to 8.6.13.1 and it works again (didn't update any other plugin)
---

there is no error shown in console...
and i didn't change anything in config files

---

**Cmi Version (using`/cmi version`):** 
8.6.13.2
**Server Type (Spigot/Paperspigot/etc):** 
paperspigot
**Server Version (using `/ver`):** 
paper-192
**Relevant plugins (Delete if this isn't needed):**
savagefactions rc-6, cmi and vault 1.7.3

**Comment by Zrips** [comment]
Will test out and fixed version should come out today.
