### ISSUE TITLE
Random Teleport (rt) always tp to the same small area

### ISSUE THREAD

**Issue by quorn23** [Zrips/CMI#2384]
If i use /rt player world from my spawn world it always tps the people to the same area (about 4 blocks) 

I tried executing the command as player and in a portal as well, same effect.

On a side note, would be awesome if we can define a "center" and how many blocks max the random destination is.

---

**Cmi Version (using`/cmi version`):** 
8.6.13.4
**Server Type (Spigot/Paperspigot/etc):** 
Paper(192) 1.14.4-R0.1-Snapshot
**Server Version (using `/ver`):** 
git-Paper-192

**Comment by LogGits** [comment]
Please provide your config section for random teleporting.

**Comment by quorn23** [comment]
Looks like i needed coffee, totally forgot where i've seen the idea, in the config. Here you go

`RandomTeleportation:
  Worlds:
    # World name to use this feature. Add annother one with appropriate name to enable random teleportation
    world:
      Enabled: true
      # Max coordinate to teleport, setting to 1000, player can be teleported between -1000 and 1000 coordinates
      MaxRange: 1000
      # If maxcord set to 1000 and mincord to 500, then player can be teleported between -1000 to -500 and 1000 to 500 coordinates
      MinRange: 1000
      CenterX: 4640
      CenterZ: -102
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    world_the_end:
      Enabled: false
      MaxRange: 1000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    world_nether:
      Enabled: false
      MaxRange: 1000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    PVP:
      Enabled: false
      MaxRange: 1000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    Spawn:
      Enabled: false
      MaxRange: 1000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    Plots:
      Enabled: false
      MaxRange: 1000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    Market:
      Enabled: false
      MaxRange: 1000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
  # How long force player to wait before using command again.
  Cooldown: 5
  # How many times to try find correct location for teleportation.
  # Keep it at low number, as player always can try again after delay
  MaxTries: 20
  # List of biomes to exclude from random teleportation
  ExcludedBiomes:
  - Ocean
  - Deep ocean`

**Comment by quorn23** [comment]
Okay, the issue only happens if you set min and max to the same value. if i for example raise the max it works as intended.
