### ISSUE TITLE
Changing output in LOCALE_EN.YML file not working

### ISSUE THREAD

**Issue by tmellen** [Zrips/CMI#239]
Description of issue or feature request:

ERROR: Trying to change spy and staffmsg colors through locale_EN.yml file. Changing to light gray to not interfere with chat so much, and staffmsg to bright blue. Changes listed below. /CMI reload did not addrsss. Server reboot did not address. They are stuck at bright white for spy, and red for staff msg.
```
  socialspy:
    help:
      info: '&eToggle social spy'
      args: (playerName)
    info:
      msg: '&2Spy&7[&8[senderDisplayName] &7-> &8[playerDisplayName]&7]&r [message]'
      toggled: '&eSocial spy toggled to &6[state] &estate'

  staffmsg:
    help:
      info: '&eSends message to staff chanell'
      args: '[message]'
    info:
      message: '&2[Staff]&4[&7[senderDisplayName]&4]&r&c [message]'
```

Cmi Version (using`/cmi version`): 7.6.5.2
Server Type (Spigot/Paperspigot/etc): Spigot
Server Version (using `/ver`): 1.12.2R0.1

**Comment by CloudeLecaw** [comment]
have you setupo a custom langfile?
if you use the default they got reset each reload.

- setup a customfile for example EN-OWN in the config.
- create a copy of the langfile and call it LOCALE_EN-OWN.YML
- modify this file to your desires
- reload CMI

**Comment by tmellen** [comment]
They aren't getting reset -- they just aren't being used. I've had the same language file with color preferences for months, and semi-daily updates to CMI, and it's always read from the file. The current file has the current colors I want in it, but it's being ignored.

Making my own is a good idea, though. Thanks! I'll report back if that gets used properly.
