### ISSUE TITLE
If a player is in a different world, you can't /tpo to them although you can /tpohere the user to where you are.

### ISSUE THREAD

**Issue by Speyrow** [Zrips/CMI#2392]
It seems as though when you /tpo to a user if they are in a different world. You just tp to their location but in the current world, not to their world.

Although you can /tpohere them to you regardless of the world you or they are in.
---
**8.6.13.2** 

**Paperspigot(195)** 

**MC 1.14.4**

**Comment by mercurialmusic** [comment]
Duplicates #2191

**Comment by Zrips** [comment]
Fixed
