### ISSUE TITLE
Mob collision problem.

### ISSUE THREAD

**Issue by OverBrave** [Zrips/CMI#2395]
**Description of issue:**
Players can't push collision entity.

How did I know? 
The problem was solved when I deleted the CMI plugin.

Video:
https://streamable.com/g3j3t

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/47111280/65724684-9ed76a80-e0b9-11e9-90c4-c41aba0b7b61.png)

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/47111280/65724715-ad258680-e0b9-11e9-9b27-205e26e50026.png)

**Comment by LogGits** [comment]
What was the solution?

**Comment by mrfloris** [comment]
We are on the latest CMI and have this issue as well. Out of nowhere player collision is off, we can force it on and then those 2 players can push, but mob collision is off on each server restart.

@OverBrave you closed this, can you tell us how it's fixed?
