### ISSUE TITLE
Unclear instructions of scheduled commands

### ISSUE THREAD

**Issue by Juicymercat** [Zrips/CMI#2396]
**Description of issue or feature request:**

I have an issue/question when attempting to schedule a command to happen weekly at a specific time of day. The instructions on the wiki say you can schedule based on month, day, hour, minute, second. My understanding is that I could set it to a specific "day" of the month (ex: "7" for the 7th) or a specific month of the year (ex: "12" for December) However, It is unclear what the best way to handle a weekly scheduled command would be? Is there no "week" variable that could be out of 7 days (in order to make it every friday - "6" out of 7 days) or would I have to do 4 separate commands, each starting on the 7th, 14th, 21st, 28th of each month in order to make it weekly... I would much prefer an option to do every week at a specific day. Any suggestions?

**Comment by Zrips** [comment]
For defining day of week you will need to define day of week, like "Monday" or "Sunday"
