### ISSUE TITLE
custom alias/gringotts/repair

### ISSUE THREAD

**Issue by Victor75007** [Zrips/CMI#2397]
**Description of issue:**

hello

i have any problem with cmi.
when my player use the /repair command, or /cmi repair i get some error in console.
On the command are cost.
I use gringotts plugin "as" vault.
I use custom alias for this cost or command.

```
  repair:
    Cmds:
    - moneycost:10?! cmi repair [playerName] hand
  cmi repair:
    Cmds:
    - moneycost:10?! cmi repair [playerName] hand
``` 

Well, my players tried repair their armor, but these items not will be repaired.
but the command take their all money.

Sorry my english
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
https://pastebin.com/zaEdeFDe
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):**  8.6.13.4

**Server Type (Spigot/Paperspigot/etc):**  PaperSpigot

**Server Version (using `/ver`):** 1.13.2 - paper:639

**Relevant plugins (Delete if this isn't needed):**
Gringotts:
https://www.spigotmc.org/resources/gringotts.42071/

**Comment by Zrips** [comment]
Incorrect custom alias which redirects command to itself
