### ISSUE TITLE
Request: Add option to economy

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#240]
I would like to see added an option to set a charge or XP cost to use general commands as part of the economy. Right now spawners and flight have a charge option. It would help limit how often players can use commands such as jump, repair, feed, heal, tp, enchant etc. Make them earn the ability to use the commands through gameplay.

**Comment by MCTyler** [comment]
This sort of exists already with timed permissions and LuckPerms. (To avoid duplication of everything)

**Comment by CypherPhyre** [comment]
I am not looking to limit the command usage in a timed manner but to have a monetary, XP, or both cost to be able to use the commands. Much like with the flight charge or spawner charge, have a command charge option.

**Comment by MCTyler** [comment]
Yes, can all be achieved thru the use of Timed Perms and/or this feature added long ago https://www.spigotmc.org/wiki/cmi-attached-commands/.

**Comment by mercurialmusic** [comment]
You can accomplish this with [Custom Aliases](https://www.spigotmc.org/wiki/cmi-custom-alias/) and [Specialized Commands](https://www.spigotmc.org/wiki/cmi-specialized-commands/). This example is on the [Custom Alias Wiki](https://www.spigotmc.org/wiki/cmi-custom-alias/) and charges the player $20 every time they use the command. Look at the Specialized Commands list for more charge options like XP. The ? checks to see if the player has the money required and the # cancels the command if they don't.

Heal:
  - fromConsole! moneycost:20#?! cmi heal [playerName] -s
  - fromConsole! msg [playerName] !&2You just been healed by God's of minecraft!

**Comment by MCTyler** [comment]
What I was trying to say! Thanks,  and use it to Temp add a perms as Heal and charge for that duration as seen here in LuckPerms ```settemp <node> <true/false> <duration> [temporary modifier] [context...]```
Something like this....```fromConsole! moneycost:20#?! lp user [PlayerName] settemp cmi.command.heal true 10m```fromConsole! msg [playerName] !&2You can now heal yourself for 10 Minutes!```

**Comment by mercurialmusic** [comment]
Ooh, that is smart!

**Comment by CypherPhyre** [comment]
Not what I am trying to accomplish so I will look elsewhere. Thanks anyway.
