### ISSUE TITLE
Lift signs port players into the air or into the ground

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#2405]
Players are ported relative to the shield position when using a lift. This means that you now have to place lift signs at the correct player height: https://imgur.com/a/m2oPLfe
If you place them too low: https://imgur.com/a/nPgED9D
or too high: https://imgur.com/a/q8G0TKR
a player lands in the ground or falls down.
This behaviour is new, in the past it didn't matter where you placed the shield. The previous behaviour offered a lot more possibilities!

Paper 1.13.2 - 647
CMI  8.6.14.0

**Comment by TheoRetisch1** [comment]
Confirmed for version 8.6.21.5.

**Comment by Zrips** [comment]
Well it seems to be only for players with creative or spectator modes, will make some changes to fix this behavior for creative/spectator players. But do you experience this issue with regular players?

**Comment by TheoRetisch1** [comment]
You're right! When I reported it in 2019 it also affected the survival mode, but in version 8.6.21.5 this is no longer the case. Thanks that you will fix it for the other gamemodes as well :)

**Comment by TheoRetisch1** [comment]
With version 8.6.22.1 we are now back to the original stage. If the signs are not placed at eye level, you end up in the upper/lower floor. The examples from the original description are valid again. This happens permission independent in all three gamemodes survival, specator and creative. The bug occurs in version 1.13 as well as in version 1.15.
Should I open a new ticket or could you reopen this one for the sake of simplicity?
