### ISSUE TITLE
Rankup - AccountAge

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#2409]
It looks like "AccountAge" has a cap of 15 days. Anything past that seems to generate this:

[Server thread/INFO]: [CMI] Cant determine amount AccountAge:1728000‬

---

**Cmi Version (using`/cmi version`):** 
8.6.15.0

**Server Type (Spigot/Paperspigot/etc):** 
paper 1.14.4

**Server Version (using `/ver`):** 
paper-131 (yeahhh.. i should update)

**Comment by Zrips** [comment]
You simply had some invisible symbol, selecting end of it and pressing backspace removes it and everything works as intended
