### ISSUE TITLE
Request Add commandvariable "all"

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#241]
Description of feature request:

the **variable all** for commands.. - if no Playername is used and the all varriable is used the command apears to all players, in this cause we could use commands like the titlemsg for all players and single varriants too (without a playername)
i know this would made some commandsof cmi look a bit unnesseary..like cmi tpall (new: cmi tp all) or cmi tmb (new: cmi titlemsg all), or...cmi giveall (new: cmi give all)....etc... 

Sorry aggain for seeing you have a github so latly :3

**Comment by LogGits** [comment]
Great idea 👍 As you said, some commands do use an all variable but it would be very useful if all worked as a global variable.
