### ISSUE TITLE
Permissions Problems

### ISSUE THREAD

**Issue by BirminghamBoy** [Zrips/CMI#2411]
**Question: **
I've added the **cmi.signs.shiftedit** and **cmi.anvil.colors** permissions to my donator ranks, but they seem to have no effect. Any ideas as to how I could fix this?

**Comment by LogGits** [comment]
For `cmi.signs.shiftedit` also give them access to `/toggleshiftedit` that way they can toggle it on and off.

**Comment by BirminghamBoy** [comment]
> For `cmi.signs.shiftedit` also give them access to `/toggleshiftedit` using `cmi.command.toggleshiftedit` that way they can toggle it on and off.

Thanks, works now. Any idea about the anvil colours?

**Comment by LogGits** [comment]
I am assuming this was resolved. I wasn't able to reproduce this on the latest version 8.6.24.0. If you still have the anvil issue can you please reopen an issue using our new Bug report templates. Thanks a tonne :)
