### ISSUE TITLE
Elytra disappearing

### ISSUE THREAD

**Issue by IsRealMe** [Zrips/CMI#2418]
**Description of issue:**

When player has no permission to use elytra, on right click it says something like "You don't have permission" or whatever. But when player is trying to put on elytra via inventory elytra disappears.

---

**Cmi Version (using`/cmi version`):** 
8.6.14.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Should be resolved
