### ISSUE TITLE
Request Spawnerextastion

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#242]
Description of  request:

Suggestion: Mobspawner extansion

- a command to "transform" the handolded (or looking at?) mob_spawner into a Mobspawner that can be toggled on/off with a restone Signal (on/off) When the transforms Mobspawner is fires by redstone he is able to Spawn Monster, when the Redstone Signal turns off the transformed spawner stops Spawning Mobs.
Note: It is important that this feature is a command to transform and not automaticly effect all spawner. Else this would also effect natural spawners what is unwanted in survival.

command: **/cmi redstonespawner**
permission: **cmi.command.redstonespawner**
effect: turns handheld or looking at mobspawner into a redstone fired mobspawner
note: this does not mean Redstone should fire the spawn of athe mob, it just should enable/disable the spawnfunction of the spawner.

**Comment by CypherPhyre** [comment]
Like an on/off switch without the need for lighting?

**Comment by MCTyler** [comment]
Forge Mods has Powered Spawners, Is what Cloude is looking for. Would be kinda cool!

**Comment by CloudeLecaw** [comment]
Like an on/off switch without the need for lighting?

exectly ;)
Forge mod.... im still using spigot 1.12.2 :3

**Comment by CypherPhyre** [comment]
It would come in handy when say making an overworld blaze farm where they have a very high disabled light level requirement

**Comment by LogGits** [comment]
Hey, this is a cool idea! Unfortunately, we have no plans to make something like this in CMI. I highly recommend checking out a plugin called EpicSpawners which in update https://www.spigotmc.org/resources/epicspawners-the-ultimate-spawner-plugin.32430/update?update=198518 has added this exact feature. It's a great plugin, check it out 🙂
