### ISSUE TITLE
About Flight Charge

### ISSUE THREAD

**Issue by ProperSAMA** [Zrips/CMI#2420]
**Description of issue or feature request:**

Flight Charge is a great feature. Players like it very much.
But I don't want players to use them in certain worlds.
I did not find a configuration to disable it in the designated world.
What shall I do?Can you add a command that closes the specified player's flight mode? In this way, I may be able to close his flight mode when the player is transmitting.
Or use what you think is good. If a player flies in a dungeon, it's too boring.
---

**Cmi Version (using`/cmi version`):** 
8.6.13.2
**Server Type (Spigot/Paperspigot/etc):** 
CatServer(Similar to KCauldron. But CatServer is 1.12.2)
**Server Version (using `/ver`):** 
This server is running CatServer version git-CatServer-1.12.2-40f2af3 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2838)

**Comment by BearLeonLight** [comment]
WorldLimits found in the config.yml file
And add the world you want to ban in the settings below.

**Comment by BearLeonLight** [comment]
The preset is off, you have to open it yourself.

**Comment by ProperSAMA** [comment]
I set it like this,then reload:
```
  Fly:
  - Moon:False
```
When I teleport to Moon,Flight mode not closed.
I also tried "Moon: False", "Moon: True", "Moon: false", "Moon: true".
They're not working either.
Which of them is right? Maybe this feature can't be used in CatServer?

**Comment by ProperSAMA** [comment]
It seems that "False" is right.But it does not take effect outside the "world".
```
  Fly:
  - world:False
```

**Comment by BearLeonLight** [comment]
I have never used CatServer
Maybe the name of your map in CatServer is not called Moon, I know that the name of the MOD server map will be different from the original one.

**Comment by ProperSAMA** [comment]
"Nether" and "end" will have different names, but I don't know if the rest of the world will. 
I'll check this later.

**Comment by ProperSAMA** [comment]
I tried to set Moon to "DIM8" just as server set end to "DIM1". But that didn't solve the problem.
Maybe it's not a question of world names. In "/cmi gc", Moon is not shown as another name.
Now I have installed a plugin to detect "PlayerToggleFlightEvent" to solve this problem.

No similar problems have been found with other functions.Thank you for your reply!

**Comment by ProperSAMA** [comment]
"Worldlimit" also failed to achieve the expected effect in spigot.
When I set a ban on flying in the "world" world, then teleport to the "world" world.I can't fly, but I can still use "/flyc" to turn it on again.
When I set a ban on flying in the "test" world, then teleport to the "test" world.I don't need to do anything to fly.
CMI Version is  8.6.15.0. This function needs to be checked.
