### ISSUE TITLE
Rank Prefixes not showing up in chat. 

### ISSUE THREAD

**Issue by PuppyNomNom** [Zrips/CMI#2421]
Hi everyone, i'm unsure if this is a bug or not, but Rank Prefixes aren't showing up in chat, they show up in the tab list, when I go AFK, etc.

I'm using LuckPerms. any help would be very much appreciated. Thanks :)

**Comment by BearLeonLight** [comment]
Is there any other chat plug installed?

**Comment by BearLeonLight** [comment]
Can you give pictures? I don't understand ˊˇˋ

**Comment by BearLeonLight** [comment]
If you want to display the prefix, then you give the player, group prefix in LuckPerms.
Also install the PlaceholderAPI and enter
1./papi ecloud download LuckPerms
2./papi reload
You are going to show other prefixes. You can find Chat settings in config.yml to make adjustments.
I don't know if this is the answer you want.

**Comment by ayushgameretawah** [comment]
what is the prefix of cmi to show ranks in tab

**Comment by mrfloris** [comment]
> what is the prefix of cmi to show ranks in tab

I have given you the answer here; https://github.com/Zrips/CMI/discussions/6399#discussioncomment-1708714 and I have warned you to not spam here: https://github.com/Zrips/CMI/discussions/6386#discussioncomment-1708719
