### ISSUE TITLE
BungeeCord Message Cross Server

### ISSUE THREAD

**Issue by Mintycraft** [Zrips/CMI#2429]
**Description of issue or feature request:**
I'm having the problem of cross server chat with Bungeecord, we've got CMI installed on both servers and the proxy, we can message players but nothing about the cross server chat.
---

#####################################
#####################################
```
  BungeeMessages: true
  # Do you want to enable public messaging over bungeecord
  BungeePublicMessages: true
  # Do you want to enable staff messaging over bungeecord
  BungeeStaffMessages: true
---

**Cmi Version (using`/cmi version`):** 
8.6.15.0
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
1.14.4

**Comment by MrTrinax** [comment]
Got the same issue.
I'm able to do /cmi msg [message] [player], but public chat messages doesn't get sent cross network.

Got all possible Bungee variables in the configs enabled.

Server 1: 
CMI: 8.6.18.7 BungeeCord 
Server version: Paper(243) 1.14.4-R0.1-SNAPSHOT

Server 2:
CMI: 8.6.18.7 BungeeCord
Server version: PaperSpigot 1.8.8-R0.1-SNAPSHOT

**Comment by banit** [comment]
Probaly same Problem i had.. its not documented that you need a special permission cmi.bungee.publicmessages.server
i have the issue that i can see the chat but it gets doubled
