### ISSUE TITLE
Custom Alias Broken

### ISSUE THREAD

**Issue by Endothelium** [Zrips/CMI#2446]
Hello, if i create a custom alias like "/leave x".

If i run "/leave y" or "/leave z", it still run "/leave g".

Custom Alias seems to just ignore whats behind space. And it totally break the system and all the alias i already made.

I need to downgrade my cmi version to CMI8.6.9.7 to make my server work again.

**Cmi Version (using`/cmi version`):8.6.15.0** 

**Server Type (Spigot/Paperspigot/etc):Paper 1.14** 

**Server Version (using `/ver`):1.14**

**Comment by ogoo2997** [comment]
if you use the $1 or $1- in custom alias you create
for me it work great
these is mine custom alias ( /bm )
`asConsole! cmi toast all -t:goal -icon:diamond [playerName]: $1-`
players can type "/bm 123" and then show "123" on the top of screen

**Comment by Endothelium** [comment]
Hello,

No the X in "/leave x" alias isnt a dynamic variable.

For example, we have an alias we create as "/site discord" that show a message "https://discord.net".

If the user type "/site google" it still run the alias "/site discord" and display "https://discord.net" because what is behind "/site" (here discord) is not processed. It should display nothing, because the alias "/site google" doesnt exist.

What you are talking about is not the same use case, im not using dynamic variables ($1 etc....) to make dynamic output.
