### ISSUE TITLE
[Question] /cmi clear (what's possible?)

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2449]
For some reason I am pretty convinced I read somewhere a while ago that cmi clear had an update to help prevent certain items from the inventory to get deleted. For example: not the off hand, or not the armor, or only the inventory but not the hotbar. Or maybe skip renamed items - things like that.

I can't find any docs or info on this on zrips.net or spigotmc, and i really thought i read it somewhere in commands, permissions, or config, but can't find anything.

Either I am crazy or, could you perhaps explain this a bit better to me? 

Also, if none of this is in cmi and i am indeed crazy, could it be changed from question to feature request?

**Comment by Zrips** [comment]
Maybe something was lost in a translation. Currently you can remove specific items if you will provide what you want to remove, then you have option to request confirmation of removal. Other then this there is no filter in works which would keep particular items. We could add something like that, defined in config file or during removal, like for example **/clear -armor -weapons** which would remove everything except armors and weapons from your inventory. or something like **/clear +weapons** which would remove only weapons. Just a thought.

**Comment by mrfloris** [comment]
Thank you for the explanation. That would be rather awesome if we could do /cmi clear -hotbar  and /cmi clear +inventory (not armorsslots)

**Comment by Zrips** [comment]
Next update
