### ISSUE TITLE
[Tweak] /cmi tempban <TIME> - only seconds?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2451]
/cmi tempban x would be nice if that's not in seconds, so we can ban ppl for 3+ months, essentials for example uses /tempban x 60d to add a ban for 60 days.

`/cmi tempban badguy 60d`
`/cmi tempban badguy 1h being bad`

Would this be possible? Adding 3 months to someone is an impossible amount to add, i dont see it in the documentation that i can do days or weeks or months.

**Comment by Roper89** [comment]
add the possibility of a temporary ban on the command `/cmi ban 7d` - now it bans forever
Example:  
/cmi ban badguy 1h  - temporary ban
/cmi ban badguy - eternal ban.

**You have a vulnerability**. You can bypass "/cmi mute" using the command "/me"

**Comment by mrfloris** [comment]
> blah
can you create your own support ticket, this is a feature suggestion not a bug report.

**Comment by Zrips** [comment]
You can tempban people by using time format like 20m 30d or even 20y for 20 years of temp ban

**Comment by TATA82** [comment]
Hi CMI 9.7.10.3 Player banned 0 second
used command /ban Tester2 test

**Comment by mrfloris** [comment]
> Hi CMI 9.7.10.3 Player banned 0 second used command /ban Tester2 test

This is a different command,. /tempban vs /ban, and this is a new issue and not the same as the 2019 one. Please make it it's own issue ticket
