### ISSUE TITLE
security.key error

### ISSUE THREAD

**Issue by Connorbrow** [Zrips/CMI#2455]
**Question: **
Every time the server starts we get an encryption error, something to do with the security.key file?
Console spits this out https://pastebin.com/sYsdEnsX (fyi: the console is reversed)

Thanks,
Connor

**Comment by Zrips** [comment]
Was this resolved?

**Comment by Connorbrow** [comment]
I've changed the server hosting so I no longer have the issue. I believe it was related to the java version the host was using though.

**Comment by Zrips** [comment]
Was your original host location in US? As this seams to be related to their strict restrictions (worst than rest of the world...) when it comes to encryption keys. They dont like more complex keys and limit to only 16 characters, while CMI tried to use 32. Tho with next update it should no longer be issue, hopefully.
