### ISSUE TITLE
Vanishing and unvanishing breaks mob pushing

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#2456]
**Description of issue:**

After a player has been in /vanish, they can no longer push mobs at all EVEN after unvanishing.  This persists across relogs and only becomes fixed with a server restart... until they vanish again.
---
No console error.

No relevant config section

---

**Cmi Version (using`/cmi version`):** 
[14:14:10 INFO]: --------------------------------------------------
[14:14:10 INFO]: CMI plugin version: 8.6.15.0
[14:14:10 INFO]: Server version: Paper(209) 1.14.4-R0.1-SNAPSHOT
[14:14:10 INFO]: Vault version: 1.7.2-b107
[14:14:10 INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
[14:14:26 INFO]: This server is running Paper version git-Paper-209 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[14:14:26 INFO]: Checking version, please wait...
[14:14:27 INFO]: Previous version: git-Paper-192 (MC: 1.14.4)
[14:14:27 INFO]: You are 5 version(s) behind
>

**Comment by Drakanoiderna** [comment]
Have same problem and with mine carts.

**Comment by thunderlight411** [comment]
can confirm that this problem still exist in 8.6.15.6

13.11 20:08:11 [Server] INFO --------------------------------------------------
13.11 20:08:11 [Server] INFO CMI plugin version: 8.6.15.6 BungeeCord -> 8.6.15.7
13.11 20:08:11 [Server] INFO Server version: Paper(225) 1.14.4-R0.1-SNAPSHOT
13.11 20:08:11 [Server] INFO Vault version: 1.7.2-b107(CMIEInjector)
13.11 20:08:11 [Server] INFO --------------------------------------------------

**Comment by Momshroom** [comment]
Still broken in 8.6.16.3
https://prnt.sc/q5xbqk

**Comment by thunderlight411** [comment]
Still exist.
27.12 11:08:53 [Server] INFO --------------------------------------------------
27.12 11:08:53 [Server] INFO CMI plugin version: 8.6.16.4 BungeeCord 
27.12 11:08:53 [Server] INFO Server version: Paper(31) 1.15.1-R0.1-SNAPSHOT
27.12 11:08:53 [Server] INFO Vault version: 1.7.2-b107(CMIEInjector)
27.12 11:08:53 [Server] INFO --------------------------------------------------

workaround for this is to give player access the the command ***/cmi playercollision***
To let them push "Entities" again.

**Comment by Momshroom** [comment]
Still broken in 8.6.19.0 with paper 60 (1.15.1)

**Comment by pvvvo** [comment]
I wasn’t sure about reporting it as an issue because you can enable again the collision with mobs typing /playercollision

**Comment by thunderlight411** [comment]
problem still excist in CMI version 8.6.20.8
@Zrips can you give a eta for a possible fix?

**Comment by Zrips** [comment]
Fix is coming out with today's update.
