### ISSUE TITLE
Request: CMI Chat over BungeeCord

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#246]
Description of issue or feature request:

I wish that all CMI chat would work over BungeeCord, and not only /msg. I use Chatcontrol Pro to manage chat over BungeeCord, but would be very pleased to remove this and only use CMI for chat as well :D

And what do I mean by this?
If I am on server1, I would like to be a part of a conversation thats being held on server2, server3 and server4. I want a unified chat between them all.

**Comment by Drewflav** [comment]
Now THAT would be amazing!

**Comment by Zrips** [comment]
This was added at some point. My memory is too short to remember which version exactly.
