### ISSUE TITLE
ElevatorStaticIndicator not working in gamemode 0

### ISSUE THREAD

**Issue by SeruhioX** [Zrips/CMI#2461]
In gamemode 0 ElevatorStaticIndicator does't work but it works in gamemode 1.

My users have been complaining about this lately, and when I change my gamemode to survival I saw that it doesn't teleport me in front of the sign but in creative yes.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

```
  # Sets indicator when creating elevator signs. Its case insensitive
  ElevatorIndicator: '[Ascensor]'
  # Defines elevator type. If this is used on second line of sing, then player will be teleported directly in front of it instead of keeping original players x and z coordinates
  ElevatorStaticIndicator: '[*]'
```

---

**Cmi Version (using`/cmi version`):** 
8.6.15.0

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
1.13.2 624

**Comment by Zrips** [comment]
Will make some changes with next build. Cant really reproduce whats going on, but have general idea what could be.
