### ISSUE TITLE
/Groundclean define per world

### ISSUE THREAD

**Issue by Newpoman** [Zrips/CMI#2470]
can't figure out how to run the command for the new feature
Added option to define specific world when using groundclean command to only remove items from that world

**Comment by x1p** [comment]
The language file explains it
```
  groundclean:
    help:
      info: '&eClears server from unnecessary items'
      args: (+cb) (+cm) (+ci) (+b) (+tnt) (-w:[worldName])
      explanation:
      - +cm will include minecarts into cleaning
      - +cb will include boats into cleaning
      - +ci defines if you want to include weapons and armors
      - +tnt defines if you want to include primed tnt
      - +b broadcasts clear message to everyone
```

**Comment by Newpoman** [comment]
cool Thank you. Maybe I have to regenerate my language files? mine still says this
  groundclean:
    help:
      info: '&eClears server from unnecessary items'
      args: (+cb) (+cm) (+ci) (+b)
      explanation:
      - +cm will include minecarts into cleaning
      - +cb will include boats into cleaning
      - +ci defines if you want to include weapons and armors
      - +b broadcasts clear message to everyone

**Comment by Newpoman** [comment]
> 
> 
> The language file explains it
> 
> ```
>   groundclean:
>     help:
>       info: '&eClears server from unnecessary items'
>       args: (+cb) (+cm) (+ci) (+b) (+tnt) (-w:[worldName])
>       explanation:
>       - +cm will include minecarts into cleaning
>       - +cb will include boats into cleaning
>       - +ci defines if you want to include weapons and armors
>       - +tnt defines if you want to include primed tnt
>       - +b broadcasts clear message to everyone
> ```

I had to regenerate the language file.... Thank you so much for your help!!

**Comment by x1p** [comment]
If your question is solved, then please close this issue yourself. There is very little moderation here, unfortunately.
