### ISSUE TITLE
Missing locale

### ISSUE THREAD

**Issue by PlopHat** [Zrips/CMI#2479]
**Description of issue:**

Missing locale while adding !cooldown:<any number>!
---

https://i.imgur.com/pBcJ6cL.png

**Comment by splops** [comment]
No luck, same issue,  it is the locale when you do attatchcommand !cooldown:1!

**Comment by arturek1666** [comment]
Lol that's interesting when I have time will check out if I have the same issue xD

**Comment by arturek1666** [comment]
When I am doing it it's fine for me:
![image](https://user-images.githubusercontent.com/1558228/67787740-fd04be00-fa68-11e9-94fd-9c093454f106.png)
Do you have the newest version of plugin?

**Comment by arturek1666** [comment]
Can you send my your language file?. So i can check it out.

**Comment by arturek1666** [comment]
The CMI just got updated try that version :) for fix

**Comment by JoelDeadMach** [comment]
Same issue

**Comment by JoelDeadMach** [comment]
Cooldowns: '&eThis command is on cooldown for another &6[time]' its on my config but the message in chat says **https://i.imgur.com/XICrG3T.png**
