### ISSUE TITLE
Error server bungeecord with economy

### ISSUE THREAD

**Issue by Dual360** [Zrips/CMI#2484]
Good afternoon:

I have installed a server with bungeecord and 5 servers that hang from it. My server is in spigot.
CMI version: CMI8.6.15.3.jar

I have installed CMIB on bunguee and CMI on 3 servers.

I have a problem with the CMI and the economy (I have installed the vault version that you recommend on the zrips website). When I enter 2 different servers I have no problems. The economy works perfectly. The topic is on the third server. It does not detect the economy of the other two. I have been looking at the database and what happens to me is that when you create the user field it generates a uuid that does not exist. So I have two different users with the same name and it detects it as two different economies. The configuration of the third server is exactly the same as in the other two.

Could you help me.

Thank you.

**Comment by Zrips** [comment]
CMI database should not be used on more than one server, it doesnt support data sync, currently.
