### ISSUE TITLE
PAPI Placeholders doesn't work for first connected players

### ISSUE THREAD

**Issue by Daxxas** [Zrips/CMI#2487]
**Description of issue or feature request:**

PAPI Placeholders doesn't work for first connected players. Here is a screenshot to demonstrate my problem : https://i.imgur.com/Zhh0jXw.png. in this case, the %guilds_prefix% turns to nothing as it should, and %parangon_level% to 0.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
GeneralFormat: '&7%guilds_prefix% &9%parangon_level% &f{displayName} &7> &r{message}'
```

---

**Cmi Version (using`/cmi version`):** 8.6.15.0

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):** [18:31:15 INFO]: This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[18:31:15 INFO]: This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.

**Relevant plugins (Delete if this isn't needed):** PlaceholdersAPI

**Comment by Daxxas** [comment]
It is even worse now, I've updated to 1.14.4, with latest CMI, and prefixes doesn't work at all for new players

**Comment by Daxxas** [comment]
Any help on this ? :(

**Comment by Zrips** [comment]
If PAPI placeholders doesn't work then it should be resolved at PAPI end
