### ISSUE TITLE
Weblink not blocked in chat: bad regex?

### ISSUE THREAD

**Issue by ScuroK** [Zrips/CMI#249]
This Link was not blocked in chat using latest cmi version of today:
https://www.google.de/

Could you improve the weblink detection?

**Comment by MCTyler** [comment]
Google and Spigot are on the Whitelist, Just remove in the config.yml ```    WhiteList:
    - \bgoogle.\s?([a-zA-Z]{2,4})\b
    - \bspigotmc.\s?([a-zA-Z]{2,4})\b```

**Comment by ScuroK** [comment]
thanks alot @MCTyler 
is there also a way to allow "./" in chat. because sometimes players help each other how to use commands. and to not execute it they often write things like "./command is what you need"

thats very common on german servers.

**Comment by LogGits** [comment]
[![Screenshot from Gyazo](https://gyazo.com/ff1fb17480de2851b3d071cd574a195b/raw)](https://gyazo.com/ff1fb17480de2851b3d071cd574a195b)
Send your config layout for chat 🙂 Also what version of cmi are you using (/cmi version)? I know you said latest but its always good to be sure ❤️

**Comment by MCTyler** [comment]
```Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: true
  # When set to true, regular and private messages (excludes clean messages) will have aditional information when hovering over it (PlaceHOlderAPI supported) and can be clicked for quick reply option
  ClickHoverMessages: false
  # When set to false, each time you will use /r you will reply to person you previously sent message directly or to person who sent you message if there is none you have conversion before
  # When this set to true, players with /r will reply to person who last sent private message. This can result in confusion when using /r while getting private messages from multiple players
  ReplyToLastMessenger: false
  # Defines regex when replacing url in chat with short word
  LinkRegex: (?:(?i)(?:https?):\/\/)?(?i)(www)?(.)?[§&a-zA-Z0-9\\-]+(\.)([a-zA-Z]{2,4})\b([\S]+)?
  # Do you want to enable private messaging over bungeecord
  BungeeMessages: true
  # Used for simple chat messages. Optional variables: {prefix} {suffix} {group}. Supporting PlaceHolderAPI variables like %player_server%
  GeneralFormat: '{prefix}&f{displayName}&7: &r{message}'
  # Defines range of regular messages to travel
  # Set to -1 to disable range restriction
  GeneralRange: -1
  # Defines range of shout messages to travel
  # Shout messages should start with ! and player should have cmi.shout permission
  # GeneralRange should be enabled
  # set to 0 to shout across all worlds, -1 to disable
  ShoutRange: 200
  # Defines cost for each shout message
  ShoutCost: 0
  # Use numeric increments to separate groups from each other. If player has more than one, then line with higher number will be used
  # Add as many lines as you need too
  # cmi.chatgroup.[id] permnission node to use
  GroupFormat:
    '1': '{prefix}&2{displayName}&f: &r{message}'
  Colors:
    # If set to true then all public messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.publicmessage.[colorName]
    # Colors: black(&0), darkblue(&1), darkgreen(&2), darkaqua(&3), darkred(&4), darkpurple(&5), gold(&6), gray(&7), darkgray(&8), blue(&9), green(&a), aqua(&b), red(&c), lightpurple(&d), yellow(&e), white(&f), magic(&k), bold(&l), strikethrough(&m), underline(&n), italic(&o), reset(&r)
    PublicMessage: true
    PrivateMessage: true
    # If set to true, then color codes will get removed from text instead of leaving them if player dont have appropriate permission node for that color```
Edited just the chat portion.

**Comment by LogGits** [comment]
Is it possible if you could send a video of this so we can see whats happening? (maybe upload an unlisted video to youtube and provide a link to us here)

**Comment by ScuroK** [comment]
@LogGits can you pastebin your config please?

**Comment by ScuroK** [comment]
if i enable chat filter it even detects phrases containing "." as advertising :D

**Comment by MCTyler** [comment]
https://youtu.be/qeX4IcP9Awk

**Comment by MCTyler** [comment]
```
        # posible: none, orhers, all
        # Where 'none' means everyone will receive this message
        # 'others' means that sender will get message but not other players, this is usefull to prevent advertising and silently block it
        # 'all' means that no one will receive sent message
        BlockType: others
```
What does this section say?

**Comment by MCTyler** [comment]
This seems to work although I don't know the full details of what you want...
```
    WhiteList:
    - \bspigotmc.\s?([a-zA-Z]{2,4})\b
    - ./
```

**Comment by LogGits** [comment]
@ScuroK I am using a fresh config.

**Comment by ScuroK** [comment]
@LogGits 
enable chat filter and ipblock and type this in chat:
"some.random.words.ok." 
does it work?

**Comment by MCTyler** [comment]
Flag me as advertising.

**Comment by ScuroK** [comment]
@Zrips 
here is what i had to do in order to fix this problem:

ChatFilter:
    Enabled: true
    Deny:
      ipBlock:
        # If not set to true, this filter will not be used
        Enabled: true
        # Defines filter group and defines required permission node to bypass this filter: cmi.chatfilter.bypass.[groupName]
        Group: Advertising
        # Regex expresion to filter by. How to use regex https://regexone.com/
        Regex:
        - (https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})


that means only the new regex2 is working. the default regex for ipblock are buggy.

**Comment by ScuroK** [comment]
but open.spotify.com wont get blocked with this regex.

how could i add "open." ?

**Comment by ScuroK** [comment]
i must say essentials was much easyer to use. i never had to mess with it

**Comment by ScuroK** [comment]
going to reaopen this issue since the root of the problem is more clear now.
