### ISSUE TITLE
"/saveditem" command is make item display Italic

### ISSUE THREAD

**Issue by NightPrimez** [Zrips/CMI#2490]
**Description of issue:**

Im using Vanilla Item to saveditem but it's give Italic item display name :joy:
(Sry for bad eng)

https://imgur.com/a/0atcu69

**Cmi Version (using`/cmi version`):** 
8.6.15.4

**Server Type (Spigot/Paperspigot/etc):** 
paperspigot

**Server Version (using `/ver`):** 
1.14.4

**Comment by kassadGLA** [comment]
The same problem with kits. Also in the kits config in all `displayname` variables which starts with next color codes: `§f, §r, §l` automatically removing this color codes and then text was formatted as Italic. Issue was solved after server restart only. But the problem is urgent.
CMI 8,6,15,5

**Comment by Zrips** [comment]
resolved
