### ISSUE TITLE
Add a Bungee Broadcast command /bbroadcast

### ISSUE THREAD

**Issue by Drc-DEV** [Zrips/CMI#2491]
**Description of feature/improvement request:**

Add a command that broadcasts a message throughout all spigot servers with CMI under the same bungeecord instance (with the cmi bungee plugin installed of course).

---

Useful in order for admins to send messages with placeholders throughout the network, instead of using the default /alert.

**Comment by variananora** [comment]
Any updates on this?

**Comment by Zrips** [comment]
Next update
