### ISSUE TITLE
Bossmsg can't  reciprocal now

### ISSUE THREAD

**Issue by ogoo2997** [Zrips/CMI#2492]
i use this command to close server before but now -sec cant be "-"
`/cmi bossbarmsg all &cServer Close: [autoTimeLeft]! -cmd:"stop" -sec:-300 -c:red`
if you use this command now, it'll work now that like you set -sec:0, 

CMI: 8.6.15.4
paper-221

**Comment by RSLuke** [comment]
Same here

**Comment by x1p** [comment]
Same
