### ISSUE TITLE
Player time reset with secondary server

### ISSUE THREAD

**Issue by thecenters** [Zrips/CMI#2493]
Play time shows overall in cplaytime but with %cmi_user_playtime_hourst% it shows only the hours on the new server

Background: I created a new server and I'm using the same config for CMI on this new server. It's setup on Bungeecord.

![2019-10-31_13 05 29](https://user-images.githubusercontent.com/1264853/67982173-67d80580-fbdf-11e9-95e6-f78214ee6222.png)

![2019-10-31_13 05 48](https://user-images.githubusercontent.com/1264853/67982175-67d80580-fbdf-11e9-8adc-b0bdb0dd76dc.png)

**Comment by thecenters** [comment]
Update: Homes are also disappearing depending on which server someone players on the Bungeecord network

**Comment by mpdk** [comment]
Same problem here, after last update, some of the playertimes are reset, even tried to put the the time back manually in the world stats, and it worked. But got reset again.

**Comment by thecenters** [comment]
It's almost like this data is stored somewhere other than CMI_users and when they join a particular server, CMI changes their entire user entry in that table

**Comment by thecenters** [comment]
Fix to problem: Each server has to be connected to it's own separate table -- so they can't share the same nickname on multiple bungee servers. Kinda a bummer

**Comment by Zrips** [comment]
It was never indicated that CMI data is synched across multiple servers. This requires quite allot of work and allot of polishing to make it work as it should without creating more issues then resolving.
