### ISSUE TITLE
Interactive command reset/disabled

### ISSUE THREAD

**Issue by Victor75007** [Zrips/CMI#2494]
**Description of issue:**

I use lot of IC function on all servers of BungeeCord. 
These ICs are on the NPC what i created with Citizens.
These NPCs are on the 'Spawn'
I have a problen, when no player are on the spawn, these chunks doesn't loaded, then IC is will be "disable". Its will be turn off. 
If i teleport to the spawn, and i stand next to npc, and i type the '/cmi reload' command, then ic will be turn on again.
I have tried to use reload command in  schedule, but not works. 
The ICs need is necessary that the chunk been loaded..

Can you fix it?

sorry my english.

---

**Cmi Version (using`/cmi version`):**  8.6.15.3

**Server Type (Spigot/Paperspigot/etc):**  paperspigot

**Server Version (using `/ver`):**  1.12.2 - 1.13.2

**Relevant plugins (Delete if this isn't needed):** citizens

**Comment by Zrips** [comment]
Should be resolved
