### ISSUE TITLE
Tempfly isn't working if im changing gamemode

### ISSUE THREAD

**Issue by ArtifactyNight** [Zrips/CMI#2495]
**Description of issue:**

so.. i changing gamemode to adventure (add tempfly for 1 hour) and change to survival but i can't flying

**Cmi Version (using`/cmi version`):** 
8.6.15.4

**Server Type (Spigot/Paperspigot/etc):** 
paperspigot

**Server Version (using `/ver`):** 
1.14.4-R0.1 paperspigot

**Comment by Zrips** [comment]
When changing game mode to survival server disables players fly mode automatically which requires from player to reenable his tfly
