### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Yasuwa1** [Zrips/CMI#2497]
**My server is lagging horribly. I checked with my support team and we took a timings test. It located around CMI is what they said. this is the result https://timings.aikar.co/?id=9e4187e887734833b990c99aad75d97f**

CMI8.6.15.4.jar

**PaperSpigot:** 

**1.14.4:** 

**Probably not relevant but here is my plugin list. https://hasteb.in/honajuma.sql :**

**Comment by x1p** [comment]
Your timings is a little short and few people to conclude for me, but are you sure it's CMI? I would first look at Citizens.
Common advice: Dig into the modules.yml file and turn off as many things you don't need.

**Comment by Yasuwa1** [comment]
I completely removed citizens2, sentinels, and dtltraders. "All npc based plugins" and the timings report for entities lag got even worse. My ram was spiking from 15% to 95% rapidly.  I contacted my support channel once again, and they said the same thing. All of it is coming from a single plugin, and it looks like CMI. What do I need to provide for you to investigate?

**Comment by x1p** [comment]
I only gave my opinion, you don't need to convince me. I don't work for CMI. You have to ask the developer.

Furthermore, this might be interesting for you: https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/

**Comment by Zrips** [comment]
@Yasuwa1 
Your timings don't indicate any issues with CMI, you have different plugins taking allot more of server resources then CMI. Your timings report doesn't even indicate any issue with CMI in general. You have like 7 plugins before CMI which creates a bigger load. So maybe start from them.
