### ISSUE TITLE
Kit orders

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#25]
I don't believe I saw a way to do this in the plugin, if this exists already I do apologize.

Is there a way to organize the order that kits show up in the kit gui? 

I have them with different weights but that does not seem to make any difference in their order. I also created them in the order I wanted them but that is not the order they ended up in. Its also not following an alphabetical order either. 

The kit groups also do not seem to follow an order like that. So far they are together with their groups, I only just started the second group.

**Comment by Zrips** [comment]
There is button in kit editor on left bottom corner where you can define its position in GUI, by default its automatic and will place in "random" order. You can use this one to sort it out. Weight i being used when you have multiple kits with same command name to determine which one should be used.

**Comment by Kbryst** [comment]
Ahh ok that makes more sense thank you
