### ISSUE TITLE
Invisibility potion don't hide the player name tag

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#2500]
**Description of issue:**
I think the fix "Fix for nameplates not being reaplied when returning from vanish mode" it causing issue in 1.8.8, the invisiiblity potion will make the player disapear but the name tag will stay visible, also i see myself as traslucent ghost
![image](https://user-images.githubusercontent.com/3611852/68109192-31a1cb00-feea-11e9-8a00-2cc14b68cb75.png)
![image](https://user-images.githubusercontent.com/3611852/68109206-3cf4f680-feea-11e9-90bf-fcbdda502c20.png)

the issue is not present on CMI8.6.13.2

**Cmi Version (using`/cmi version`):** 
8.6.15.4

**Server Type (Spigot/Paperspigot/etc):**
Paper

**Server Version (using `/ver`):**
1.8.8

**Comment by xion87** [comment]
Any news?

**Comment by xion87** [comment]
Dude now i forced to upgrade cmi and there is the bug, when it will be fixed????

**Comment by xion87** [comment]
bump :( @Zrips

**Comment by the456gamer** [comment]
Can reproduce:
the default team (cmicol) has the option "seeFriendlyInvisbles" set to true.
when changing nameplate (or glow i'm assuming) it switches you out of the team, temporarily fixing the issue

**Comment by LogGits** [comment]
Scenario:
> Server gives out invisibility potions. CMI has placed everyone in a "seeFriendlyInvisibles:true" meaning all invisible people can see eachother (hence breaking invisibility potions)

Workaround:
`DisableTeamManagement: true`
Though (i could be wrong), this workaround may have potential sideeffects.

**Comment by Zrips** [comment]
This was known issue with 1.8.8 servers in general as of https://bugs.mojang.com/browse/MC-48730 bug report. This was fixed and is not an issue in later versions. If you want to hide those nameplates on 1.8.8 and older versions, you will need to set this DisableTeamManagement to true in config file or update your server to a newer version.

**Comment by LogGits** [comment]
To clarify, scenario 2 is fixed in the next milestone. scenario 1 is unfixable due to a minecraft bug as Zrips mentioned.
