### ISSUE TITLE
UltimateShops Item Support

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#2502]
**Description of feature/improvement request:**
Hello! I would like to request a feature to be added. Currently, CMI does not support UltimateShops item support.

Plugin: https://www.spigotmc.org/resources/ultimateshops-player-admin-item-shops-1-8-1-14-premium.64925/
---
### Detailed explanation of what it should do, when and in what situation: ###
Currently, CMI's "/cmi groundclean +ci" clears UltimateShops's shop item entity. It would be great if CMI push an update that runs the check utilities.isDisplayItem(Item i) on items before removing if UltimateShops is installed on a server.

### Basic explanation as to why this feature is needed and/or useful to have: ###
This would prevent UltimateShop's item entity to be removed by CMI's clearlag so that it players wouldn't have to re-create their shop. 

Thank you for your time! I hope this can be implemented soon! Cheers~

**Comment by Zrips** [comment]
I don't have access to that plugin so i cant really add support for it. And in general, that plugin could simply change its behavior from creating real items to a packet-based system that would solve this issue with CMI or any other plugin in general.

**Comment by BboyZeroOne** [comment]
I have sent you a copy of the plugin to your discord. Please take a look~

**Comment by Zrips** [comment]
Basic support will be added with next update
