### ISSUE TITLE
Backslash dupliacted in chat

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [Zrips/CMI#2503]
**Description of issue:**
CMI is duplicating "\" symbol, while sending on chat :/

---

**Cmi Version (using`/cmi version`):** 
06.11 23:44:17 [Server] INFO CMI plugin version: 8.6.13.1 BungeeCord -> 8.6.15.5
06.11 23:44:17 [Server] INFO Server version: Paper(209) 1.14.4-R0.1-SNAPSHOT
06.11 23:44:17 [Server] INFO Vault version: 1.6.11(+)

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
06.11 23:44:29 [Server] INFO This server is running Paper version git-Paper-209 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by mercurialmusic** [comment]
Can you provide context of what exactly is happening and when? Or you're getting that just in general chat?

**Comment by Kryniowesegryderiusz** [comment]
Yes, in general chat


pt., 15 lis 2019 o 17:33 mercurialmusic <notifications@github.com>
napisał(a):
