### ISSUE TITLE
Permission cmi.elytra doesn't work in 1.13.2

### ISSUE THREAD

**Issue by RSLuke** [Zrips/CMI#2504]
**Description of issue:**

Hello there, I've got 2 vanilla servers in 1.14.4 and one survival roleplay in 1.13.2, in the last one the permission cmi.elytra has no effect in it.

**Cmi Version (using`/cmi version`):** 8.6.15.4

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 1.13.2

**Comment by RSLuke** [comment]
Still a thing in CMI8.6.17.2 with Paper 1.13.2, works fine with Paper 1.15.1

For information, minecraft versions 1.14.x and newer lose 60% of performances with entities and chunks so they're cannot be used for production for any survival server with more than 30 players online. Don't drop support for 1.13.2 or Minecraft will be doomed soon.

**Comment by Zrips** [comment]
cmi.elytra given by default, negating it would prevent usage of Elytra.
Support for older minecraft versions will have to be dropped at some point anyways, we cant keep every single version in support for ever.
