### ISSUE TITLE
Usebug : Bypass cooldowns/warmups with /:[command]

### ISSUE THREAD

**Issue by RSLuke** [Zrips/CMI#2506]
**Description of issue:**

Hello there, my players can bypass any cooldown or warmup with commands starting with /:

**Cmi Version (using`/cmi version`):** 8.6.15.4

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 1.13.2

**Comment by banit** [comment]
Got the same Issue on Paper 1.14.4 with 8.6.16.3

**Comment by RSLuke** [comment]
Still a thing in CMI8.6.17.2

**Comment by Zrips** [comment]
@RSLuke Is this for CMI commands? Is this for custom alias or default ones?

**Comment by RSLuke** [comment]
Yeah it is for CMI commands, and this is for default ones and custom ones.

**Comment by Zrips** [comment]
Are you sure you have tested with latest version? As I have retested with 1.15 and 1.13 servers, both of them no longer allow you to bypass cooldown with /: so something is strange going on

**Comment by RSLuke** [comment]
I did, it is still an issue today with latest versions of CMI, latest build of Paperspigot 1.13.2

**Comment by Baktus79** [comment]
```yaml
WarmUps:
  Enabled: true
  InformOnNoMove: true
  List:
  - cmi tp :5:false
  - cmi back:3:true
  - cmi warp :3:false
  - cmi home :3:false
```
In this setup players can type /:back to bypass the warmup.
This is for CMI commands. I have not testet this for anything else, and I am using alias commands. If I make some aliascommands with the : in front of the aliasname, the : doesnt work anymore.

**Comment by RSLuke** [comment]
Any update on this issue ?

**Comment by Zrips** [comment]
Got a fix
