### ISSUE TITLE
ifempty:maininv-x! Incorrect calculation (Interactive command).

### ISSUE THREAD

**Issue by kassadGLA** [Zrips/CMI#2507]
**Description of issue:**

Hello!
To check amount of free slots, I must increase the value by `5`. For example, if I want `1` free slot will required, then I must specify the value `6`, if I want `2` free slots will required, I must specify the value `7`, etc:
```
ifempty:maininv-6! - will require 1 free slot.
ifempty:maininv-7! - will require 2 free slot.
...etc
```

Note. Notified messages contain the correct value (`[count]` placeholder in lang file), for example:
```
ifempty:maininv-6?! - will notify that 6 free slots are required, but in fact only 1 is required.
ifempty:maininv-7?! - will notify that 7 free slots are required, but in fact only 2 is required.
...etc
```
Best regards.
---

**Cmi Version (using`/cmi version`): ANY** 

**Server Type (Spigot/Paperspigot/etc): ANY** 

**Server Version (using `/ver`): ANY**

**Comment by Zrips** [comment]
Should be fixed with next version
