### ISSUE TITLE
CMI + DeluxeChat - AFK Message (This user is AFK and may not reply)

### ISSUE THREAD

**Issue by Spikey101** [Zrips/CMI#251]
I use Spigot 1.8.8 with the latest CMI and DeluxeChat (I have Bungee mode enabled in Deluxe Chat)

If a player is AFK and another player messages him, The player is not notified that he is AFK with a message like *Player is AFK right now and may not respond* 

How can I make this work with DeluxeChat?

**Comment by LogGits** [comment]
I would recommend contacting the developer of deluxechat to implement such a feature. They can hook into cmi's api and check if the player is afk and take the necessary steps to achieve this msg.
