### ISSUE TITLE
"/cmi seen" Detects vanished player last logout

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#2511]
**Description of issue:**
When a player /cmi seen an admin in vanish, it will show the admin's last logout time. 

Example: 
Admin comes online in Server A in vanish and teleport to Server B, after 10 minutes, when players uses the command /cmi seen (Admin), it would display the time when the Admin last logout off Server A and it would appear "Admin has been Offline since 10 minutes ago.".

**Cmi Version (using`/cmi version`):** 
CMI: 8.6.15.4

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
1.13.2 Paper Spigot(637)

**Comment by BboyZeroOne** [comment]
Hello, why is this closed? Is this issue fixed?

**Comment by RupticMC** [comment]
> Hello, why is this closed? Is this issue fixed?

Read the beginning.
https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/update?update=353146
