### ISSUE TITLE
Mail is not included in social spy.

### ISSUE THREAD

**Issue by DeusNinja** [Zrips/CMI#2513]
Players are able to use /mail to bypass social spy.

Also I didn't notice any method in the config to add /mail to a list of commands that would appear for social spy. May you please add this? 

 CMI plugin version: 8.6.15.5
Server version: Paper(225) 1.14.4-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Well its not a bug but will include mail into social spy with next update
