### ISSUE TITLE
Velocity support

### ISSUE THREAD

**Issue by natr566** [Zrips/CMI#2515]
**Description of feature/improvement request:**
Add support for velocity
---
### Detailed explanation of what it should do, when and in what situation: ###
Just like the bungee addon but for Velocity
https://www.velocitypowered.com/
### Basic explanation as to why this feature is needed and/or useful to have: ###
Because velocity is cleaner then bungee and it's great.

**Comment by mrfloris** [comment]
I see more people use velocity as they switch to paper, so makes sense to consider supporting it if it doesn't already.

**Comment by dyanakiev** [comment]
Bump?
