### ISSUE TITLE
Drop spawner doesn't work

### ISSUE THREAD

**Issue by Aureliiienn** [Zrips/CMI#2517]
Description of issue or feature request:

Spawner doesn't drop with perms.

**Comment by Aureliiienn** [comment]
Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
CMI plugin version: 8.6.15.7 BungeeCord

**Comment by ludvdber** [comment]
#2177
