### ISSUE TITLE
Cannot start CMI after update

### ISSUE THREAD

**Issue by mmuziek** [Zrips/CMI#2520]
**Description of issue:**
cmi wont start after the initial start it just disables itself after a error that doesnt make any sense

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
https://pastebin.com/WNsySu0P
######################


**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 
PAPER 214
**Server Version (using `/ver`):** 
1.14.4 R0.1

**Comment by Zrips** [comment]
Your error log doesn't really say much what happens as it looks like stripped-down version of real error. If you are using any plugin which modifies console messages, disable it. I need second part of that error log to know why it failed as current report doesn't even mention CMI in general.

**Comment by mmuziek** [comment]
i have deleted the entire CMI folder including the data files. it now starts working again however i think it had to do with the data file.
Since the yml files are put back by me after the reinstall and it still works ?

**Comment by Zrips** [comment]
If there was some miss format in yaml files, then this could have prevented CMI to load properly. But if its resolved now will close this ticket. If issue repeats, try to load server with CMI only and give me full error log
