### ISSUE TITLE
"tpbypass" toggle request

### ISSUE THREAD

**Issue by ThyV0001** [Zrips/CMI#2524]
**Description of issue or feature request:**

add a permission node, or a config option to toggle the /tpbypass feature for when a player is being teleported to an unsafe location. Id like to have the option to disable it.

This is happening to a lot of players on my server for when they are teleporting into long grass

**Comment by Zrips** [comment]
This is related to cmi.safeteleport permission node, which will prevent teleportation if its unsafe, if it is, then you have option to bypass it by performing that same /tpbypass command.
In general we would need to solve the issue with tall grass, but cant really reproduce it on 1.14.4. Could you give more information on this one? Like server version or maybe even a picture of aplace which was counted as unsafe which should be safe. And does your players have cmi.safeteleport?

**Comment by ThyV0001** [comment]
Im running a 1.12.2 Towny server, I was unaware that a safeteleport permission node was there, Ill take a look if this solves my problem.

**Comment by ThyV0001** [comment]
This solved my problem.
