### ISSUE TITLE
HP screws up when Inventory is restored, due to HP increasing gear.

### ISSUE THREAD

**Issue by Dracathio** [Zrips/CMI#2525]
**Description of issue:**
HP messes up when restoring someones inventory.
They end up with a permanent hp increase they shouldn't have.

---

**Cmi Version (using`/cmi version`):** 
8.6.15.4
**Server Version (using `/ver`):** 
Paper(175) 1.14.4-R0.1-SNAPSHOT
**Relevant plugins (Delete if this isn't needed):**
Mythic Mobs

**Comment by Zrips** [comment]
You will need to elaborate more on this issue. Like, restoring inventory from what? invload? How much hp player had before restore and how much after? Do you have players running around with less hp then normal?

**Comment by Dracathio** [comment]
> You will need to elaborate more on this issue. Like, restoring inventory from what? invload? How much hp player had before restore and how much after? Do you have players running around with less hp then normal?

I guess yea invload.  where it gives them back their inventory from a previous death, using /invlist playername
then clicking the loadinv for owner.
I currently have a player running around with 50 hp instead of 20

and /cmi maxhp set  doesn't seem to work.

**Comment by Zrips** [comment]
Both loading previous inv and setting maxhp works as intended. This might be an issue with another plugin interfering. 
What i could do is to add option to avoid saving hp state and restoring it when performing load command, this would skip any hp editing and should prevent this issue for you from happening again.

**Comment by Zrips** [comment]
Next update.
