### ISSUE TITLE
DiscrodSRV and AsyncPlayerChatEvent with CMI

### ISSUE THREAD

**Issue by xxJinxedxx** [Zrips/CMI#2526]
**Description of issue:**
Issue with the new update of DiscrodSRV and AsyncPlayerChatEvent with CMI when players chat.

---

**ERROR:**
https://paste.md-5.net/iyuyoriyaf.pl
---

**Cmi Version (using`/cmi version`):**  CMI v8.6.15.8

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.8.8-R0.1-SNAPSHOT

**Relevant plugins:**
https://www.spigotmc.org/resources/discordsrv.18494/

**Comment by Zrips** [comment]
Make sure you have latest DiscordSRV version. Will add some error catcher with next version to prevent this spam with unsupported DiscordSRV versions.

**Comment by xxJinxedxx** [comment]
> Make sure you have latest DiscordSRV version. Will add some error catcher with next version to prevent this spam with unsupported DiscordSRV versions.

Yes it is the latest. Actually this happen after the update of DiscordSRV to the lates/most recent version, which came few days ago.

**Comment by Zrips** [comment]
Interesting, it seems that something broke with DiscordSRV with latest build, in any case, will post new version today which should no longer have this issue.

**Comment by Zrips** [comment]
And just in case, try redownloading DiscordSRV file, as it can be the case that you got some what broken version of it while downloading, happens some times.

**Comment by smellyonionman** [comment]
I've been having the same issues on the last three versions of DiscordSRV, and have tested with each version of CMI since then, too.  It's consistently reproducible.  I suspect they just changed the class name.  I'm gonna go dig through their commits.

**Comment by smellyonionman** [comment]
[CommandBroadcast.java, line 72](https://github.com/DiscordSRV/DiscordSRV/commit/c89c2cbf0a1ab44e73b90da72475d52499e06366#diff-0fb381575da734854717e54554c213cdR72)

Looks like we're targeting text channel IDs differently in DiscordSRV now... I think we're the guilty ones.  I didn't update my config like they said.  I'm downgrading CMI and trying a fresh DiscordSRV config.  If its fixed, I'll recommend you roll this fix back.  Sorry : )
