### ISSUE TITLE
Invsave/Invload doesn't save or load armour

### ISSUE THREAD

**Issue by AudioPlugged** [Zrips/CMI#2531]
**Description of issue:**
The invsave command doesn't seem to be saving armour, I've tried it with the default config and it saved everything but the armour I was wearing, not sure if this is due to the version of my server. using invload doesn't return the armour and when checking a saved inventory the armour slots are empty.

---

**Cmi Version (using`/cmi version`):** 

CMI: 8.6.15.0 -> 8.6.16.0
(It's not fixed in the newest version according to the update blog)

**Server Type (Spigot/Paperspigot/etc):** 

PaperSpigot

**Server Version (using `/ver`):** 

Server Version: PaperSpigot 1.8.8-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Should be resolved
