### ISSUE TITLE
Server restart randomly causes customrecipe to stop working

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#2533]
All custom recipes sometimes stop working after a server restart. If you try to burn or craft a recipe, nothing happens. A reload of CMI does not solve the problem. There are no errors in the log. New and functional recipes can be added when the problem exists. Old recipes only work if you update them once.
A renewed server restart usually fixes the problem.

CMI 8.6.15.8
Paper 1.13.2 - 651

**Comment by TheoRetisch1** [comment]
*Edit* If the error occurs, custom recipes do not return XP. Updating the recipes does not help either, only a server restart restores the feature.

**Comment by Meldiron** [comment]
Same problem here, custom recipe desnt work for some reason. I use paper 1.14.4 and CMI 8.6.15.8

**Comment by TheoRetisch1** [comment]
Confirmed for version 8.6.16.4. A fix would be awesome! The players are a little fucked up :/

**Comment by TheoRetisch1** [comment]
Confirmed for version 8.6.19.8 - Paper 1.13.2 - 653. Very nasty bug :/

**Comment by TheoRetisch1** [comment]
The bug also exists in version 8.6.20.5. What information do you need to fix the bug?

**Comment by TheoRetisch1** [comment]
Confirmed for version 8.6.21.5 :/

**Comment by TheoRetisch1** [comment]
Why is the ticket closed? Has the bug been fixed?
