### ISSUE TITLE
/Glow colors not working

### ISSUE THREAD

**Issue by trickman325** [Zrips/CMI#2535]
**Description of issue:**
/glow will work for players that have perms but only white (default)
any other colour will not work even for ops of the server.
It does say in chat that the player has been changed to the colour but still does not work ingame on the player.

---

**Cmi Version (using`/cmi version`):** 8.6.15.8

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** spigot 1.14.4-R0.1-SNAPSHOT

**Comment by trickman325** [comment]
Bump

**Comment by mrfloris** [comment]
I have been able to give players the commands and the permissions, and through unique items we created with CMI we see them get the glow. Usually the color is correct. But when we teleport away or reconnect, it's all white. 

I haven't been able to pinpoint if this is vanilla mc, or caused by optifine, or some packet thing with cmi.

Wouldn't mind seeing this fixed either :)

**Comment by SlimeCody** [comment]
Bump this is still an issue, and would love to see it fixed!

**Comment by crunchward** [comment]
Can confim - 
Logs confirm perms.
I don't get the color at all even pre-teleport. It's always just white. Setting with the console nets the same results.
Tested with OP, no difference.
Tested without OP, permissions debugged via luckperms verbose, perms are confirmed:
```
[22:38:11 INFO]: [LP] VB > crunchward - worldguard.region.bypass.world - true
[22:38:11 INFO]: [LP] VB > crunchward - sv.worldedit.use - true
[22:38:11 INFO]: [LP] VB > crunchward - sv.towny.use - true
[22:38:11 INFO]: [LP] VB > crunchward - cmi.command - true
[22:38:11 INFO]: [LP] VB > crunchward - cmi.command.* - true
[22:38:11 INFO]: [LP] VB > crunchward - cmi.command.glow.color.blue - true
```
I'm on the latest release

**Comment by Blueeyestar** [comment]
Unfortunately, the CMI8.6.24.3 does not work either. Would be nice if this would be possible again soon.

**Comment by CloudeLecaw** [comment]
i can confirm this issue s still in last version of CMI

**Comment by mc-System404** [comment]
If your using TAB PREMIUM plugin follow this tutorial to make your /glow working 👍
https://github.com/NEZNAMY/TAB/wiki/How-to-make-TAB-compatible-with-glow-plugins
