### ISSUE TITLE
[Documentation] There is no documentation on how to change the server time zone

### ISSUE THREAD

**Issue by BNK3R-Patrick** [Zrips/CMI#2538]
**Description of issue or feature request:**

There is a general issue when browsing the documentation. By defautl there is server_time_HH:mm:ss placeholder in tabList.yml. 
It would be great

---

**Cmi Version (using`/cmi version`):** 8.6.16.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 226

**Comment by Zrips** [comment]
Time zone is used from server itself. So it's depending on server time zone and you might want to change that. Other then this we would need to do some extra updates to allow some manual overriding of time zone and change time accordingly.

**Comment by BNK3R-Patrick** [comment]
Server time is running in CET. CMI shows the Servertime in UTC. 
![image](https://user-images.githubusercontent.com/29790124/69786244-4f491400-11ba-11ea-96a9-1a5300dd2fd7.png)
