### ISSUE TITLE
CMI 8.6.16.2 doesn't work with LuckPrems 5

### ISSUE THREAD

**Issue by In77** [Zrips/CMI#2546]
**Description of issue:**
CMI v8.6.16.2 doesn't work with LuckPrems v5.0.9

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<img width="962" alt="Screenshot 2019-12-01 at 09 25 02" src="https://user-images.githubusercontent.com/44344308/69908061-a51cf680-141c-11ea-8a45-1027557f6081.png">

---

**Cmi Version (using`/cmi version`):** 
v8.6.16.2

**Server Type (Spigot/Paperspigot/etc):** 
Paper 

**Server Version (using `/ver`):** 
git-Paper-232 (MC: 1.14.4)

**Comment by Zrips** [comment]
Gets fixed with todays update
