### ISSUE TITLE
Announcer Setting

### ISSUE THREAD

**Issue by Aeyori** [Zrips/CMI#2551]
**Description of issue or feature request:**
Is there a way to disable the announcer part of the scheduler per player? Say if 1 player doesn't want to see it anymore then they can toggle it off, while it is still on for other players to see.
---

**Cmi Version (using`/cmi version`):** 
8.6.16.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.14.4

**Comment by Zrips** [comment]
Scheduler performs commands independent of what player has set in his settings. So currently no.
