### ISSUE TITLE
Sleep message improvement (less spammy)

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2554]
**Description of feature/improvement request:**

Currently the sleep message is spamming everyone on the server.

http://prntscr.com/q5n75b

Maybe it would be nice to put it into the actionbar or make it less spammy?

**Comment by LogGits** [comment]
Although i could be entirely wrong:
Some parts of the locale utilise the `actionbar!` variable to print messages into the actionbar.
e.g. `counter: '!actionbar!&6--> &e[time] &6<--'`

can you try this out and let me know how it goes

**Comment by Sikatsu** [comment]
I will try this soon and let you know, sorry for the delay.

**Comment by Sikatsu** [comment]
Sadly, that doesn't work. http://prntscr.com/qgrhgu

**Comment by Zrips** [comment]
This will get fixed and somewhat changed behavior on how we are handling things like this, so in general adding !actionbar! with next update should get you a desired results.

**Comment by Sikatsu** [comment]
Awesome, appreciated.

**Comment by Sikatsu** [comment]
@Zrips 

Would it be possible to have the message persistent when you are in a bed?
Currently it only shows a short time in the actionbar.
