### ISSUE TITLE
Attributes with give command using the same UUID

### ISSUE THREAD

**Issue by Fabrimat** [Zrips/CMI#2557]
When using the /cmi give command with the parameter "a" we can specify some attributes (like max health, movement speed, ecc).
The plugin should generate a random UUID because if the same UUID is used there will be conflicts between more items with the same type of attributes.
![image](https://user-images.githubusercontent.com/13642582/70089092-c72e9880-1617-11ea-84ae-880ecd38b4ca.png)

**Comment by Zrips** [comment]
Will make adjustment for this one
