### ISSUE TITLE
Teleportation to spawn after login

### ISSUE THREAD

**Issue by MrWay** [Zrips/CMI#2563]
**Question: **
Hey, I would like to ask if it is possible to set that player will be at his last position before disconnecting after reconnecting.

**Comment by the456gamer** [comment]
```Spawn:
  # Forces players to login in defined spawn point when logging into server
  SpawnOnJoin: false```


this is the default config

**Comment by CloudeLecaw** [comment]
you want them that they log in where they log out? then dont activate a teleport to spawn on login^^

Well all is said allready by the456gamer.

ticket can be closed
