### ISSUE TITLE
In 1.15, nothing in CMI works, the /cmi command is invalid

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#2569]
As you likely know, CMI doesn't work at all in 1.15.

---

**Comment by the456gamer** [comment]
thats because cmi hasn't been updated to 1.15 yet

**Comment by Zrips** [comment]
C'mon, be more patient! ^.^

**Comment by digitalcrowd** [comment]
LOL. It works now. Thanks man!
