### ISSUE TITLE
[Bug] Mobhead [4 bugs]

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#2575]
**Description of issue:**
`GUI`
- The gui `cmi mobhead` won't let you get to the second page
- The gui `cmi mobhead` won't let you get the head you clicked on, even with OP permission
- The command `cmi mobhead [mobtype] [player]` doesn't make the name like `Chicken's Head` instead the itemname is `Player Head`
- The heads are named like `&9Cow`, previously they were  `&eCow's Head` as if HeadDatabase takes control of the heads.

The problem lies in a partly conflict with HeadDatabase. This plugin shows `&9` blue names.
The version of HeadDatabase is irrelevant. It happens when CMI got updated from 8.6.16.3 --> 8.6.16.4
Btw: I use heads with codes from the minecraft-heads database and not the cmi codes. This used to work just fine up until version 8.6.16.3.

With CMI version 8.6.16.3, I get a `&eCow's Head`
With CMI version 8.6.16.4, I get a `&ePlayer Head`
In combination with the famous HeadDatabase plugin, I get a `&9Cow`

The problem with first 2 bugs lie in a conflict between CMI and CrazyCrates (v1.9.11).
Without CrazyCrates the gui is under control. With CrazyCrates the gui is blocked.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
There are no errors
```

---

**Cmi Version (using`/cmi version`):** 
8.6.16.4

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
1.14.4 
**Relevant plugins (Delete if this isn't needed):**
CMI
HeadDatabase
CrazyCrates (v1.9.11)

**Comment by x1p** [comment]
Unfortunately when you have upgraded to server version 1.15.1, like me, you are pretty much forced to update CMI to one of the latest versions.
So there is no choice but to accept these rather annoying bugs.

Now I don't like to ping anyone, but I feel I have no other choice than to ping @Zrips

**Comment by thenullmatrix** [comment]
I just have the Mobhead drops named Player head instead of <mobname> head.
