### ISSUE TITLE
[Important!] Teleport issue

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2578]
**Description of issue:**

Everytime I do /tpo <playername> without tab complete or without using the full name, I get teleported to the same location in the world. Doesn't matter which player.

The way I teleport (could be any name): http://prntscr.com/qbyosa
I always end up on these coords: http://prntscr.com/qbyonu

If I however teleport like this: http://prntscr.com/qbyozs
Then I am being teleported to the player.

**Comment by Sikatsu** [comment]
@Zrips Still happening, are you able to look into this? :)

**Comment by Zrips** [comment]
You might simply have player whose name is luuk and who is offline and you got teleported to his location. Try using **/cmi info luuk**

**Comment by Sikatsu** [comment]
Doesn't it prioritize online players? And why does it always sent me to the same coordinates then? Can't be that all offline players are at the exact same location? O.o

**Comment by Sikatsu** [comment]
./cmi info Luuk is indeed another player which has been offline for quite some time.

**Comment by Sikatsu** [comment]
Still happening on the latest version

**Comment by Sikatsu** [comment]
Still happening and it is a very annoying bug.

**Comment by BoosterBots** [comment]
I am running into this same issue when trying to teleport to a player that is located in a different world using the /tpo command. 
Running Paper version git-Paper-79 (MC: 1.15.2)
CMI 8.6.18.6

**Comment by Zrips** [comment]
Will be introducing some options to prioritize online players when using partial names.
