### ISSUE TITLE
Feature: Books

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#258]
I would love to be able to open book without needing of having the book in inventory instead to open after use a command?.

Would this be possible?

**Comment by mrfloris** [comment]
CMI now has `cmi getbook [cTextName] (playerName)` / `cmi ctext [cText] (playerName/all) (sourcePlayer)`

https://www.zrips.net/cmi/custom-text/

Hopefully this is what you're looking for. I saw this ticket still being open, and just happen to play with getbook myself today.

**Comment by the456gamer** [comment]
I would assume that op means opening the book without the item, using https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#openBook-org.bukkit.inventory.ItemStack-

Not sure how hard it is to implement, either directly or using cmi's api

**Comment by Exillium313** [comment]
Looking for this same feature actually, a book or gui that opens on command to display info.  GUI's I find to be tedious to make minor edits where a .txt like this would be much more user friendly.

**Comment by arturek1666** [comment]
This feature has now been added closing the comment.

Thank you

**Comment by arturek1666** [comment]
I had reopen it as this command on top is just giving you book and what I was looking is to open the book with command without giving the book to inventory.

**Comment by mrfloris** [comment]
> I had reopen it as this command on top is just giving you book and what I was looking is to open the book with command without giving the book to inventory.

```
> cmi checkcommand book
[13:37:50 INFO]: --------------------------------------------------
[13:37:50 INFO]: 1. openbook (cText) (playerName)
[13:37:50 INFO]: 2. book [Author/Title/Unlock] [value]
[13:37:50 INFO]: 3. getbook [cTextName] (playerName)
>
```
You can use getbook to get the book from a txt file 
You can use openbook to open the content from a txt file into a book (without getting the book)

**Comment by Zrips** [comment]
/cmi openbook
Will open ctext in a book format, so you can have preset books with hover over or clickable messages and open it as a book.
