### ISSUE TITLE
CustomHead feature - incorrect head names

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#2580]
Heads dropped by mobs are no longer clearly named as they used to be, they are now all called "Player Head". This is of course a significant downgrade in contrast to the previous behaviour. The customHeads.yml was not changed, there were only CMI updates.

Example:
before: https://imgur.com/a/UCNwur6
now: https://imgur.com/a/xgVNuJk

CMI 8.6.16.4
Paper 1.13.2 #652

**Comment by x1p** [comment]
Could be related to #2575
Something is changed since 8.6.16.4

**Comment by thenullmatrix** [comment]
Now they don't identify as a block for our auction system.  were the older ones that were named do.

**Comment by TheoRetisch1** [comment]
Fixed in Version 8.6.21.5 thank you :)
