### ISSUE TITLE
Add Brown Color Command

### ISSUE THREAD

**Issue by Relaxing9** [Zrips/CMI#2582]
**Description of feature/improvement request:**
Add **Brown Dye** "&"

---
### Detailed explanation of what it should do, when and in what situation: ###
With the Addition of **Brown Dye** in 1.14, we are able to make signs have a brown color when punching them on a sign in survival mode, can CMI add a color code so we can add it to Public Messages, Books, Private, Me, Nickname, Signs, and Books. (all whats displayed in /cmi colorlimits)
### Basic explanation as to why this feature is needed and/or useful to have: ###
Having this feature is having better aesthetics.

**Comment by mrfloris** [comment]
- In 1.14.x onwards, Ink sacs, bone meal, cocoa beans and lapis lazuli are now no longer considered dyes.
- Added black, white, brown and blue dyes.
- "Rose Red", "Dandelion Yellow" and "Cactus Green" have now been renamed to "Red Dye", "Yellow Dye" and "Green Dye", respectively.

source: wiki changelog 1.14

**Comment by Zrips** [comment]
Not really possible to be added as color codes are hardcoded into client
