### ISSUE TITLE
(atta chcommand )Serious error

### ISSUE THREAD

**Issue by 1425115471** [Zrips/CMI#2583]
cmi 8.6.16.4
spigot 1.13.2
#--------------------------------
Example
/cmi attachcommand !limiteduse:1!!silent!;;!cc!cmi give [playerName] 1

Bind to an item （Right click will only trigger once）
Bind to an item （Left click players will trigger twice）

**Comment by 1425115471** [comment]
I hope you can fix it. It's an amazing feature

**Comment by Zrips** [comment]
Fixed
