### ISSUE TITLE
[Spawner] Bee egg bug

### ISSUE THREAD

**Issue by HeliosOps** [Zrips/CMI#2585]
Player can change the spawner to bee by using bee spawn egg without permission.
I had turn on the EggRequiresPermission: **true** in configuration file.

Server version: Paper 1.15.1 #23
CMI Version: 8.6.16.4
CMIB Version: 1.0.0.3

**Comment by ScuroK** [comment]
same here!

**Comment by mrfloris** [comment]
Can confirm, happens here as well to players who shouldn't have the permission. 

It seems to be just bee, the other ones appear to have a permission:

fox
pillager
ravager
wandering trader & llama
panda
cat

**Comment by mrfloris** [comment]
Just checked, still happening in `CMI version 8.6.16.5`

**Comment by ScuroK** [comment]
Bug is still present yes.

**Comment by Zrips** [comment]
Will be fixed with today's update
