### ISSUE TITLE
Server crash due to CMI errors

### ISSUE THREAD

**Issue by jj136975** [Zrips/CMI#2587]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://hastebin.com/iwazejexul.md
```
---

**Cmi Version (using`/cmi version`):** 
Lastest
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.8.8

**Comment by Zrips** [comment]
Could you provide a customalias file? As it looks like you have some custom alias which points to itself which creates infinite loop and causes this issue. Need to determine which one it is and how it bypassed built in protection from situations like this as it should not allow you to make alias which could cause a loop.
