### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by QueenAngus** [Zrips/CMI#2590]
**Description of issue or feature request:**
Hi there! Any info on how to fix this issue? obviously it happens with CMI and discordsrv
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
####################
####################
https://pastebin.com/f1EpR42T

#####################################
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.15.17
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
1.13.2
**Relevant plugins (Delete if this isn't needed):** 
DiscordSRV

**Comment by Zrips** [comment]
Are you using latest version of DiscordSRV?
