### ISSUE TITLE
1.15.1 hologram issue

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2591]
**Description of issue:**
Holograms with multiple pages show random heads within the hologram.

http://prntscr.com/qfozfa

**Comment by PsychoLynx** [comment]
To add to this, it seems that holograms where "interactable: true" are not hiding the cube heads.

**Comment by mercurialmusic** [comment]
Seconding the cube heads.

**Comment by the456gamer** [comment]
Can confirm, also changing to small buttons change them to armour stands, and removing the hologram removes the extra entities

**Comment by Zrips** [comment]
Confirmed, fix is underway.
