### ISSUE TITLE
Rainbow Changing color code

### ISSUE THREAD

**Issue by trickman325** [Zrips/CMI#2592]
A color code that changes chat text just like the dye'd armor (rainbow)

---
So the code is the same as other normal color codes (&#) but will change the text colors the same why dyed armor does.

would be very cool to have in chat nicknames and also in holograms

**Comment by the456gamer** [comment]
it is only feasible in holograms, which is already implemented, as you cannot update chat messages once they are displayed
> from (the documentation)[https://www.zrips.net/cmi/holograms]

```Use &u color code to have random color which will change on each update```

**Comment by Zrips** [comment]
Chat messages can only have 16 colors, while dyed armor can have over 16 million of them. And as @the456gamer stated, you cant change colors in chat after they are displayed, which would require some over-complicated and heavy on server constant chat text resending method. At this point with current Minecraft API, will not invest time and effort to try to make some blinking text in chat. To much work for little result.
