### ISSUE TITLE
Armour stand editor spams command which triggers anti-spam

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#2594]
When you move the limbs of an Armour stand the method it uses commands to move each time, this sets off any anti-spam system that stops spamming commands in a period of time, for example I use ChatControl pro, if you try and change the limb position fast it will block you with 

> "You can only send 10 commands in the last 10 seconds."

Is there a way to make these changes to the armor stand without sending loads of commands from the user?

**Comment by Exillium313** [comment]
So add it to the whitelist for command spam so its not included in the commands watch for spam.... This is not a bug. ChatControl or CMI itself is limited your commands sent per 10 seconds. Simply find which one you have enabled, and find the whitelist for it and add /armorstand to bypass this.

**Comment by FrozenBeard** [comment]
@Exillium313 yes that is the obvious answer here. But it's either on or off. There is no whitelist, and yes I have requested they add it.

What you didn't understand from this ticket is the method to change the armour stands does not need to be a command each time, are you a developer of the plugin?

**Comment by Zrips** [comment]
Will remake its handling as its still using old deprecated method and can cause this issue. Wait for next update.
