### ISSUE TITLE
Bungee 1.15

### ISSUE THREAD

**Issue by jeannen** [Zrips/CMI#2596]
**CMI Bungee does not works properly on 1.15.** 

---

When going trough a portal A (Server A), the player is sent to the portal B (server B) as usual.
However, when the player is using the portal B (server B) nothing happens. He should be sent to portal A (server A).

So, it seems like it's working only in one direction, but both CMI and Paper version are the same, and it was working fine before.

When doing /cmi server serverA, a message tells me "Can't find server by this name" (but no error).

---

**Cmi Version: 8.6.16.4 Paper** 

**Server Type: Waterfall + Paper** 

**Server Version: Paper-31 1.15.1-R0.1 SNAPSHOT**

**Comment by jeannen** [comment]
(The server is properly cconnected trough bungee, since I can use portal to go from the server A to the B but not the oppsite, + Bungee's `/server` command is working on all servers

**Comment by jeannen** [comment]
I have this error when doing /portal, but it was already there before: https://pastebin.com/pHcw9D0z

Portals are present, they are just not working (and /serverlist is empty)

**Comment by Zrips** [comment]
Resolved

**Comment by jeannen** [comment]
For future reference, if someone is having the same issue: Bungee BackEnd was causing the issue, it needed to be updated
