### ISSUE TITLE
Towny Bank Cleared.

### ISSUE THREAD

**Issue by yaitsbilly** [Zrips/CMI#2597]
Used import command to bring everything over from essentials, everything but towns were imported. Noticed Essentials also save Towns bank bal to player files as well. All my town were set to 100 balance. I'm using MySQL and I can see players data but no town data is being imported.

---

CMI: 8.6.16.4
Server version: Spigot 1.14.4-R0.1-SNAPSHOT
Vault version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}

**Comment by Zrips** [comment]
Could you give me one or more files which had town data saved in it? In general import command doesn't check town data, even tho at this point i'm not even aware of which plugin this data would be from. Is this a Towny data?
