### ISSUE TITLE
Better description of cmi.command.tempban.max.[number] permission

### ISSUE THREAD

**Issue by espen96** [Zrips/CMI#2598]
I think the lack of an unit of time in the description of it is a bit annoying, it forces you to experiment to find out that the unit is seconds.

I would also like if the in-game message when you try to ban someone for longer than you are allowed could be better. Currently it lists the raw number, no indication of unit.
"You can't ban for longer than 86400"

I think it would be better if it would convert the number to a more useful one, breaking it up into a proper format easily read by humans.
example: "You can't ban for longer than 1d, 2h, 15m"

**Comment by Zrips** [comment]
Yea, will change that to include more useful time format
