### ISSUE TITLE
CMI not working with Ultra permission plugin

### ISSUE THREAD

**Issue by ZagyMC** [Zrips/CMI#2599]
CMI plugin with plugin Residence from zrips is not working with permission plugin Ultrapermissions.

---
Cmi Version 8.6.16.5

Server Type Paperspigot 

Server Version 1.15.1 

Ultra permissions

**Comment by Zrips** [comment]
Would suggest getting better permission plugin. But i will need more information on this one. UltraPermissions tends to take away default permission nodes, so you might need to add some of them manually for it to work correctly, again... What exactly is not working?
