### ISSUE TITLE
CMI doesnt work right with towny balance

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#26]
Converted essentials to cmi and it reset every town to default balance and does not let us add balance to the towns. Makes me wonder if towny taxes can take as well.  

Towny also uses iconomy with essentials (because essentials has some error) and we cannot convert the iconomy balance to cmi at all.

**Comment by LogGits** [comment]
Ok so correct me if I am wrong. You are requesting towny support and for `/cmi importfrom` to include iconomy so that you can import iconomy balance? 

Ensure you are using the latest build of essentials to lessen the chance of errors occurring when using importfrom.

**Comment by Kbryst** [comment]
No cmi doesn’t read towny balance at all and doesn’t work with towny. I have the injector and everything and it doesn’t work with towny

**Comment by LogGits** [comment]
Confirmed incompatibility with towny. `/t deposit` doesn't yield and results.

**Comment by Zrips** [comment]
This will be addressed and fixed with next update and added some more robust support for fake accounts.
