### ISSUE TITLE
Feature question & request: Player Shops

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#260]
I am looking for a good _Up to Date & Actively developed_Shops plugin to add to my server. I am wanting to know if this is something that is already planned for CMI? If not then could you add player shops of some kind? It could be implemented as either Sign Shop, Chest Shop, or as a GUI. I don't want to add another plugin to my server for this feather if it can be implemented here.

**Comment by CloudeLecaw** [comment]
Sorry to tell, but CMI has no Shopsystem it has an Economy with item values that can be used for Plugins like ChestShop if they hook with vault for example

**Comment by CypherPhyre** [comment]
I am aware that CMI does not have a shop system. I am wanting to know if there are any plans to add one before I download someone else's plugin. My goal is to limit the number of plugins I have when at all possible.

**Comment by CloudeLecaw** [comment]
a good question, i hope the moderators dont close this thread as others without really answering you :§

**Comment by MCTyler** [comment]
You can sell the items from your Inventory with sell hand or sell all after you set a worth and if you are real intuitive I'm sure you can make interactive signs that sell items.

**Comment by CypherPhyre** [comment]
The point of a shop system in this regard is so that the players can create shops as part of the economy. The sell hand and sell all only sell items to the server.

**Comment by MCTyler** [comment]
Zrips TradeMe plugin allows Players to sell items to each other, but I think that 1 is Premium too.

**Comment by CypherPhyre** [comment]
I have that one on the server already. When my server first started it did not have an economy. Only barter system. Players have asked for an economy, so I set that up. Now players are wanting to open shops. TradeMe does not offer that.

**Comment by MCTyler** [comment]
I like those shops where the items float above chests but that plugin is kinda laggy.

**Comment by CypherPhyre** [comment]
I like them too, but that aspect is not a requirement of what I am looking for. It could be anything like a Sign shop, Chest Shop, or even a GUI that a player can set up. The only requirement that the players want is that the 'Shop" can be used even when the owner of the shop is offline.

**Comment by tmellen** [comment]
CMI does not have that capability. I've created signs that sell goods with Interactivecommands that check for $, then /give the goods, but there's no way to validate that a player has the goods to sell and take them from the inventory to exchange money, and also no way for a player to set this up.

As a result, for player shops, I use the following. It's been going for 6 months without a single issue: https://www.spigotmc.org/resources/shop-a-simple-intuitive-shop-plugin.9628/

**Comment by MCTyler** [comment]
Ops not looking for Alternative. They want this to be part of CMI.
