### ISSUE TITLE
[BUG]Cmi kiteditor error

### ISSUE THREAD

**Issue by MERRYACS** [Zrips/CMI#2601]
report a CMI bug
I created so many kits there prob about 200+
and then when i type cmi kiteditor, i fallback to login server. i using the latest verison of CMI 8.6.16.4
and there is error in console:io.netty.handler.codec.EncoderException: String too big (was 33932 bytes encoded, max 32767)

**Comment by Zrips** [comment]
Got fixed by adding pagination
