### ISSUE TITLE
Players can cmi ctext system files like .DS_Store etc.

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2605]
the auto complete shows all files in the directory, so if you're on a cloud solution those will be there, the macos will have .ds_store, and there's a few others i think it's smart not to mention. 

i dont know how this works on various os, didn't have time to test, but fingers crossed they can't escape out of the directory like : `ctext ../../someplugin/mysql.yml etc.`

**Comment by the456gamer** [comment]
Tested on windows, file extensions are intact, looks like it just gets a complete list of files. Was not able to get a successful directory escape

**Comment by mrfloris** [comment]
Glad to hear, I couldn't reproduce it either. 

But yep, hidden system files like .ds_store and others shouldn't be an option for players, it should technically be limited to the stuff we set it to.

**Comment by Zrips** [comment]
Will be fixed with next build
