### ISSUE TITLE
Bug in the message

### ISSUE THREAD

**Issue by Scremonetu** [Zrips/CMI#2606]
Description of issue: The plugin does not forward messages from the language file

ban:
    info:
      message: '&cZostałeś zablokowany na tym serwerze!' **<------------------------**
      reason: '&cPowód: [reason]' **<------------------------**

Cmi Version: 8.6.16.5
Server Type: Paperspigot
Server Version: Paper-20 (MC: 1.15.1)

**Comment by Zrips** [comment]
Make sure that OverrideLoginMessage is enabled in config file
