### ISSUE TITLE
Bridge playtime -CMI Bungecord

### ISSUE THREAD

**Issue by favorit5503** [Zrips/CMI#2615]
Hi. I have a question. I have 2 server connected via bungeecord. Lets say S1 and S2. I have installed CMI on both server and on the bunge server. But i have a small problem with playtime rewards. If a player is on S1 the playtime is on the S1 and stays on the S1. If the player goes to S2 he has no playtime. Is there some way to bridg the playtime across all the servers? Btw. The servers are on a seperate MySQL database. (Becouse i prevously had only one MySQL database for the two servers and the homes got deleted randomly at server startups). Sry for the long problem :smile:

**Comment by Zrips** [comment]
Data sync across servers is in todo list, but is not present in current builds
