### ISSUE TITLE
Playtime placeholder

### ISSUE THREAD

**Issue by MADS0LADEN** [Zrips/CMI#2619]
**Description of feature/improvement request:**

Add a placeholder that shows the exact playtime like the command "/cmi playtime" shows
---
### Detailed explanation of what it should do, when and in what situation: ###
Output text like this
https://i.imgur.com/0OhoVOl.png
Or like this, maybe even 2 placeholders, one with the short names and one with long
https://i.imgur.com/mkBW9SU.png
### Basic explanation as to why this feature is needed and/or useful to have: ###
Im showing playtime on the scoreboard, but right now it shows the playtime of the statistics in Minecraft and i want to show the one where AFK time is subtracted from the playtime, aka the cmi playtime placeholder

**Comment by quorn23** [comment]
`%cmi_user_playtime_days%`
`%cmi_user_playtime_hours%`
`%cmi_user_playtime_minutes%`

Isn't those what you're looking for?
You can do /cmi placeholders in game to check all available.

**Comment by Zrips** [comment]
@MADS0LADEN 
	%cmi_user_playtime_days%
	%cmi_user_playtime_dayst%
	%cmi_user_playtime_hours%
	%cmi_user_playtime_hoursf%
	%cmi_user_playtime_hourst%
	%cmi_user_playtime_minutes%
	%cmi_user_playtime_minutest%

**Comment by MADS0LADEN** [comment]
I know all of those, i was thinking about 1 placeholder which combines all of them dynamically so if you have been online for 65 seconds it says "1 minute 5 seconds" or "1m 5s"

**Comment by Zrips** [comment]
Next update **%cmi_user_playtime_formatted%**

**Comment by MADS0LADEN** [comment]
it would be nice if the placeholder was formatted like this "8d 4h 12m 30s" and without colors
https://i.imgur.com/Yp0zTg6.png
maybe have 4 placeholders
1 like the one right now                         - **%cmi_user_playtime_formatted_color%**
1 like the one now but without colors   - **%cmi_user_playtime_formatted%**
1 with "d, h, m, s" with color                  - **%cmi_user_playtime_formatted_short_color%**
1 with "d, h, m, s" without color             - **%cmi_user_playtime_formatted_short%**
