### ISSUE TITLE
Tablist color and Join messages

### ISSUE THREAD

**Issue by lancce-Wolf** [Zrips/CMI#262]
Description of issue or feature request:

Hello everyone,
i dont know if this already exists, (i didnt find it so far)
but is it possible to make the names in the tablist show the actual player display name?
what i also would like is to set a custom join / leave message.
(Essentials had both features so it would be nice to add them into CMI)

Cmi Version: 7.6.6.1
Server Type: Spigot 1.12.2-R0.1-SNAPSHOT
Server Version: 1.5.6-b49(CMIEInjector)

**Comment by lancce-Wolf** [comment]
thank you for the reply, i found it now but the join messages arent changing???
even after a server restart they are still the same.
i had locale_DE setted in the config and changed the join / leave message in there,
i reloaded cmi then but the messages were the same. 
then i restarted the server and the locale_DE changed back to default?!
what i also tryed was to copy the locale_DE and put the text into the locale_EN and switched it to EN in the config, that also didnt work...

With the tablist thing, i got that to work but not completly. its not taking the placeholder from essentials groupmanager because i dont have essentials anymore since i moved to this plugin. but i can solve this myself by switching to a different permission plugin.I am going to switch to luckyPerms now, its finaly time after 5 years of using essentials :D

**Comment by lancce-Wolf** [comment]
so, i looked over the custom join / leave message and setted them like this:
`LogoutCustom: '&7[&4-&7] %luckperms_prefix%%player_displayname%'`
`LoginCustom: '&7[&2+&7] %luckperms_prefix%%player_displayname%'`
but i cant get them to work ingame, it still say: "Player" joined the game (in yellow)
i checked the config if the correct language is selected and it was correct.
what i also tried was to remove the [ ] because i thought they might conflict with the placeholder stuff from CMI but that didnt helped

**Comment by MCTyler** [comment]
This user closed a similar thread with this solution.....
####
Copied Locale_EN.yml to Locale_MY.yml. Set language to "MY" in the config. Works perfect.
####

**Comment by lancce-Wolf** [comment]
yea i know, and i tried this but it didnt helped.
it was in #239

**Comment by LogGits** [comment]
Bug relates to #216 and #239. 

I am able to reproduce this bug. For me when i restart my locale_(not en) gets reset. Are you all experiencing this aswell?

@lancce-Wolf are you changing the values. Then using /cmi reload and if it doesn't change the values does a restart reset the locale file?

Also if possible can you provide the section in your config labelled "Language" at the top, along with the name if your locale file.

**Comment by Zrips** [comment]
@lancce-Wolf did you enabled custom login and logout messages in config file?

**Comment by lancce-Wolf** [comment]
@Zrips i feel so embarrassed... i didnt see that before ._.
the config is soo big that you can get lost easily.

anyways it works now like i wanted it. i did it like this:
`  LogoutCustom: '&7[&4-&7] %luckperms_prefix%%player_displayname%'`
`  LoginCustom: '&7[&2+&7] %luckperms_prefix%%player_displayname%'`
and i also enabled the custom login and logout messages in the config.

i only have one question left,
is it possible to make a small "[AFK]" bevore the name that is shown in the tablist when a player is afk?

**Comment by lancce-Wolf** [comment]
never mind i found a solotion for the afk thing, the placeholder for this is called %cmi_user_afk_symbol%
and you can change the symbol in the locale file.

thank you all for the help i wish you a nice day :D
