### ISSUE TITLE
[Support] cmi killall -monsters

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2621]
Hey there,

Just a support question, when using -monsters to get rid of creepers and husks etc, is this everything, even npc types, or named ones with name tags? Or only unnamed ones that aren't an npc?

Is there a limit of arguments for /cmi killall creeper zombie husk ender.. etc? like 5 per line or 12?

Is there a way to limit killall to -monsters but just in 1 world? like -world:mine or -w mine or something ?

**Comment by Zrips** [comment]
no limit for variable count. -monsters will remove any entity which is internally considered as monster including slime ghast and phantoms. Basically any entity which can harm you.
For world limitations use (-w:[worldName]) variable
