### ISSUE TITLE
[Bug] 1.15.1 unmounting from sitting slides me through the floor

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2622]
**Description of issue:**

Right clicking on stairs to sit works, shifting (sneak) to unmount works but i tend to slide through the floor. The item below the stairs are solid block: oak planks.

---

https://youtu.be/Z8HGZErxCVM

---

**Cmi Version (using`/cmi version`):** CMI version 8.6.16.5

**Server Type (Spigot/Paperspigot/etc):** spigot 

**Server Version (using `/ver`):** This server is running CraftBukkit version git-Spigot-492a779-e7202cd (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
its due to multiple factors which sometimes causes this issue. One of those is server lag, so cant really reproduce it on my server. But thats irelevant. Will make some adjustments to teleport player in front of stairs instead of on top of them
