### ISSUE TITLE
Leaderboard duplicates

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2626]
**Description of issue:**
For some reason there are duplicates within the baltop and playtime leaderboards.
Possibly also with other leaderboards I don't currently use.

[Console] http://prntscr.com/qktj1d
[In-game] http://prntscr.com/p1me65
[In-game] http://prntscr.com/p1meba

I've removed duplicated users many times without luck.

A while back @Zrips and I have been working on this in DM on Discord, but it's still happening.

CMI: 8.6.16.5 BungeeCord -> [newVersion]

**Comment by Zrips** [comment]
Does new version solve baltop issue? playtime still uses old mechanic so that one should still have issue.

**Comment by Sikatsu** [comment]
Well, all duplicates that were there are still there. It doesn't remove existing duplicates I guess?

**Comment by Zrips** [comment]
Do you get any messages about duplicate entries when you start server?

**Comment by Sikatsu** [comment]
I don't and I removed them a couple of times with the command as well.

**Comment by Sikatsu** [comment]
![image](https://user-images.githubusercontent.com/5664135/72532359-8dd28500-3873-11ea-80a5-0ae0a4e1dbc2.png)

**Comment by Zrips** [comment]
This is what interesting, it seems to be somewhat same amount of money, slightly different tho. But at same time looked a code multiple times now and I have no idea who the hell and why its duplicating some of them when it should not be possible...

**Comment by Sikatsu** [comment]
Perhaps because it already duplicated them but didn't remove it? Page 4 and 5 have even more duplicates.

**Comment by Sikatsu** [comment]
I don't think it currently makes new duplicates, but would it be possible to remove any duplicated entries? The remove duplicated user command doesn't work for this case.

**Comment by Sikatsu** [comment]
@Zrips Hey, would you be able to look into this? My players would love it if the duplicated entries get removed in the leaderboards.

**Comment by LogGits** [comment]
@Sikatsu this may help you, let me know how it goes:
`/cmi removeuser [uuid/duplicates] - removes user from a database by uuid or all duplicates.`

**Comment by Sikatsu** [comment]
It doesn't, I've been talking with Zrips in DM at discord, he requested some information last month but I never got a reply to that.
