### ISSUE TITLE
editing armorstands using the GUI overwrites armor slots of a player with items from the armorstand GUI

### ISSUE THREAD

**Issue by Teriuihi** [Zrips/CMI#2627]
**Description of issue:**
Whenever anyone edits an armor stand one of the players (username: fgml, uuid: 02ecae2e-2253-4277-8ea5-0d6ae2fae993 ) gets items from the armorstand GUI in their inventory. They have never interacted with any of the armor stands we use and isn't anywhere near them at the time. We were able to repeatedly do this with different users using the armorstands.
---

**Cmi Version (using`/cmi version`):** 
8.6.16.5
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
git-Paper-33 (MC:1.15.1)

**Comment by Darko2117** [comment]
Happened to 4 players in total that we know of: fgml, DavidBry, EliteNK, JAIROZ1.
It happens both when we used /cmi armorstand and shift right click feature. The exact items player got instead of their armor are Left Arm Y: / Left Arm X: and 2 gray glass panes.

**Comment by Zrips** [comment]
Should get fixed with todays update
