### ISSUE TITLE
ClickHoverMessages doubling \

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#2629]
**Description of issue:**
When a player writes `Test \ Test` in public chat, the message is changed to `Test \\ Test`
When a player writes `Test \\ Test` in public chat, the message is changed to `Test \\\\ Test`
When a player writes `Test \\\ Test` in public chat, the message is changed to `Test \\\\\\ Test`

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Chat:
  ClickHoverMessages: true
```

---

**Cmi Version (using`/cmi version`):** 
8.6.17.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.14.4-1.15.1

**Comment by Zrips** [comment]
Should get fixed with todays update
