### ISSUE TITLE
ability to do /anvil

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#2631]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
The ability to do /cmi anvil (or /anvil) and have it open up a fully usable anvil gui. 
### Basic explanation as to why this feature is needed and/or useful to have: ###
I think it would be a cool and handy feature :)

**Comment by mrfloris** [comment]
Kinda duplicate: https://github.com/Zrips/CMI/issues/1094
(and yes, i still want this myself too hehe)

**Comment by Zrips** [comment]
Comming with next update
