### ISSUE TITLE
CMI Ranks is missing BlocksPlaced

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#2633]
Trying to convert from AutoRank to CMI ranks and got stuck where there is no BlocksPlaced count 
There is BlocksMined and ItemBreaks but there is no BlocksPlaced.
https://www.zrips.net/cmi/rankup-system/

**Comment by FrozenBeard** [comment]
@Zrips sorry for the ping, but any chance this could be added, this is the last restricton for me to move from 1.12.2 to 1.13+ to move my auto-ranking to CMI instead of my legacy plugins.

**Comment by Zrips** [comment]
Will be added with next build
