### ISSUE TITLE
/cmi afk "Internal Error" bug.

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#2637]
**Description of issue:**
When a player does /cmi afk, a message "An internal error has occurred while attempting to perform this command".

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://pastebin.com/9LxBJxUK

---

**Cmi Version (using`/cmi version`):** 
8.6.17.1

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
1.13.2

**Comment by Zrips** [comment]
Sorry about that, will get fixed with today's update.
