### ISSUE TITLE
attachedCommands Serious error

### ISSUE THREAD

**Issue by 1425115471** [Zrips/CMI#2638]
1.14.4 spigot
CMI8.6.17.1

================
Clicking (player) with bound items will not consume items, or trigger multiple times

for example：
/cmi attachcommand !limiteduse:1!;;!cc!mi sword JIAN_CHUJI_1 [playerName] 1
Normally, only one item will be given to the player
But if you click the player with the item bound to this command, many items will appear

**Comment by Zrips** [comment]
Can you elaborate on that "bound" part? Is this another plugin doing this? What type of item are you using in this case in particular?

**Comment by 1425115471** [comment]
I'm sorry, because my English is not good enough to express, I recorded a video to demonstrate this bug

[20200113_021947.zip](https://github.com/Zrips/CMI/files/4050969/20200113_021947.zip)

**Comment by Zrips** [comment]
Och ok, got basic idea what could be wrong with it. Lets me test it out and hopefully reproduce it so i can fix it

**Comment by 1425115471** [comment]
Thank you very much！！

**Comment by Zrips** [comment]
Ok, fix will role out with today's update.
