### ISSUE TITLE
New feature : inventory 

### ISSUE THREAD

**Issue by ludvdber** [Zrips/CMI#264]
Hello

I wonder if you could add to CMI or create a new plugin for a "per world inventory" because:

 firstly: i used to use multiInv plugin then mutliInv premium and the developer is not very active anymore and causes issues in the newest version.. so i tried per world inventory and multiverse-inventory and the developers are also inactive and have some issues 

secondly: you're a great and very active developer, I never had a problem with all your plugins and you are so fast with the support.

**Comment by MCTyler** [comment]
CMI doesn't handle any Inventories period, let alone PWI. Good Luck, I would like this too!

**Comment by mercurialmusic** [comment]
He's been setting the foundations of world groups for a while, but by the sheer scope of CMI, considering that would involve economies, inventories, and integrating all of the existing inventory features, etc., it may take a while. We're all excited for it, though.

All the same, while you're correct about Multiverse Inventories being inactive, PWI is still fairly actively developed at least. I use it successfully with CMI across 2 servers with many worlds and multiple game modes. Some other plugins can interfere with how they work, which I know PWI is developing workarounds for, but the plugin itself does what it's meant to. My PVP plugin dev, for example, successfully built in checks to make sure it played nicely with PWI across worlds, so if you do have plugins that interfere you can also ask those devs for fixes.

**Comment by ScuroK** [comment]
as long as PWI is still alive i dont see any need for it. otherwise i would love to see that.

**Comment by CloudeLecaw** [comment]
If CMI ever will have multiple invs this would mean the inventories are not saved anymore in the Players.dat file.

so it would be nice to let the owner choose if he want multible interfaces or if he want the simply saved ones in player.dat if he issus single worlds ;) (config option)

**Comment by ScuroK** [comment]
> If CMI ever will have multiple invs this would mean the inventories are not saved anymore in the Players.dat file.
> 
> so it would be nice to let the owner choose if he want multible interfaces or if he want the simply saved ones in player.dat if he issus single worlds ;) (config option)

PWI seems discontinued. so maybe this option could become interesting in the future. But i have seen Multiverse-Inventories is on the rise again. but who knows.
