### ISSUE TITLE
attachedCommands Serious error （cmi 8.6.17.3）Bug still exist

### ISSUE THREAD

**Issue by 1425115471** [Zrips/CMI#2640]
1.14.4 spigot
CMI8.6.17.3

================================
Sorry to bother you. The latest version of the error I submitted yesterday was not fixed successfully. It still exists after my test
https://github.com/Zrips/CMI/issues/2638

I'm very sorry, because my English is not good, I recorded a test bug for you
[20200114_010730.zip](https://github.com/Zrips/CMI/files/4054777/20200114_010730.zip)

**Comment by Zrips** [comment]
Releasing fix 2.0 with some general recode in how we are handling all this, so it should be ok with next update. Will do some extra testing to make sure.
