### ISSUE TITLE
Books broken

### ISSUE THREAD

**Issue by ScuroK** [Zrips/CMI#2647]
Description of issue:
All books handled by CMI are broken! Colors are totally messed up and if i unlock a book some text is just gone. please fix. thx

---

**8.6.17.3** 

**Paper** 

**Paper 1.15.1**

**Comment by ScuroK** [comment]
![2020-01-14_22 23 41](https://user-images.githubusercontent.com/10480144/72383956-d166ab00-371c-11ea-9cda-4d171cd0f9e5.png)
Before unlock -> Wrong color. Light green should be black and so on.

![2020-01-14_22 23 54](https://user-images.githubusercontent.com/10480144/72384005-e8a59880-371c-11ea-980f-510a1803f313.png)
After unlock -> Part of the text on the first page is gone.

**Comment by Zrips** [comment]
seems to be issue with book handling of 1.15.1 version in general. What suspect is that you have too many color codes which amount into longer then allowed length of one page, even tho you dont see those codes they are present in saved format. Will investigate this one and try to find out solution
