### ISSUE TITLE
Endportals not working (duplicate #161)

### ISSUE THREAD

**Issue by mormoon** [Zrips/CMI#265]
I'm not sure if i'm supposed to open a new ticket for this, but the problem described in [issue 161](https://github.com/Zrips/CMI/issues/161) is still there (ticket is closed, and I was unable to re-open the ticket.). Endportals are not working as of version 7.6.7.0

**Comment by MCTyler** [comment]
Vanilla MineCraft End Portals like in a fortress? I haven't made it that far yet, but just curious.

**Comment by MCTyler** [comment]
Op may have something else interfering. I finally found a fortress and mine worked too.

**Comment by CloudeLecaw** [comment]
my OPlist on Server is Empty :) because i dont work with OP, just with ManagedPermissionRanks like Admin, Player etc, just for Building i have a PluginMaker Rank that normaly is for devs and has full permission to all.

**Comment by MCTyler** [comment]
Cloud, When someone says **Op** in a Post that means **Original Poster.** Give me some of what your Smoking!

**Comment by CloudeLecaw** [comment]
OP is not known in Germany..not really. Here where i live the First Poster is allways known as 
TE (also TC) -> Thread-Ersteller (Thread-Creator)
but good to know…. 
anyway….. here is some of my Shishatabbaco for you^^

**Comment by mormoon** [comment]
The steps to reproduce are described in ticket [161](https://github.com/Zrips/CMI/issues/161)

In short,
You need paper-spigot 1360+ 
You need multiverse
And you'll need to have PreventCreation set to true in config.yml

**Comment by Zrips** [comment]
@mormoon did you tried this with newly created end portal? As previous versions could block initial portal creation and as it never was created, it would never teleport you.
I have no clue why paperspigot included end portal creation into nether portal creation event, messing things up, but it should work now

**Comment by mormoon** [comment]
Ehm, no. I did a drop-in replacement of the new version and run some some standard tests.  I'll try to re-create the portal.
