### ISSUE TITLE
Maxhp weird issue

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#2654]
**Description of issue:**
`/maxhp set {playername} 20` Gives the player 1 maxhp to a specific player that isnt the {playername} if 20 is used.

Same thing happens with `add {playername} 20`.
Oddly enough event `/maxhp set {myusername} 2` changes that specific user's maxhp and not mine. idk how to explain its weird af.

---

**Cmi Version (using`/cmi version`):** 8.6.17.1

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** Paper 1.14.4 build 236

**Comment by Zrips** [comment]
Will get fixed with next version
