### ISSUE TITLE
Problems with flying rights at CMI

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#2658]
Hello, I have a problem with the flying rights on my server.
The mods have the right cmi.command.fly on the main world.
I just don't want you to fly in the farm worlds. That's why I banned cmi.command.fly from PermissionEX.

The problem I have now is that a mod with flight rights turned on can go to the farm world in the farm world. The farm world takes over the flight rights

If a mod switches off the flying in the main world and then goes into the farm world, it is as it should be that he cannot switch it on or use it in the farm world.

How can I do it when a mod goes through the portal that automatically sets the flight rights to false. Because they don't do it by themselves.

Is there a solution that you can enforce that the flight rights in the farm world are off even if they are prohibited in permission Ex?

**Comment by the456gamer** [comment]
There are world limits, so you can dis allow flight in the farm world

**Comment by Blueeyestar** [comment]
under what can I set that?

**Comment by Blueeyestar** [comment]
great i found it Thank you for the info

**Comment by Blueeyestar** [comment]
The mods can still fly, have I set something wrong?


WorldLimits:
  # By setting to true fly and gamemode limitations per world will be aplied for player on world change if they dont have appropiate permission node
  Enabled: true
  # World list with default game modes
  # If player will have cmi.worldlimit.gamemode.bypass permission node, game mode wont be changed


  # Possible modes: creative, survival, adventure, spectator, 
  Gamemode:
  - world:Survival
  - Creativ:Creative
  # If player will have cmi.worldlimit.fly.bypass permission node, fly mode wont be changed
  Fly:
  - world:true
  - newnether:false
  - HoneyLand: false
  - Endyworld: false

**Comment by Blueeyestar** [comment]
The console writes: 17.01 17:28:37 [Server] INFO Mardelz issued server command: / fly
17.01 17:28:37 [Server] INFO Mardelzur has no Permissions f: cmi.command.fly

and yet I can fly .. I don't understand.................

**Comment by Relaxing9** [comment]
I see you have multiple worlds, what plugin are you using to allow that? Multiworld? Multiverse?

**Comment by Blueeyestar** [comment]
I use MultiverseCore

**Comment by Blueeyestar** [comment]
nobody here knows how I can fix the problem? :(

**Comment by Relaxing9** [comment]
Go into, your worlds.yml file in Multiverse then deny allowFlight in the world you don't want it to be allowed, that way upon teleport it may change the flight to false, another alternative is to force all your players who enter a no flight world, to switch their gamemode to survival.

**Comment by Blueeyestar** [comment]
Deactivating the solution in the MultiverseCore file Flying helped. Thanks alot :)
