### ISSUE TITLE
Wrong version listed on join

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#266]
After updating to 7.6.7.0 and restarting my server I still get the update notice saying 7.6.7.0 is now available! Your version: 7.6.6.2

**Comment by lancce-Wolf** [comment]
i have the same issue, i think they made a mistake but it should be fixed in the next version which will come later

**Comment by ScuroK** [comment]
same issue here.

**Comment by CloudeLecaw** [comment]
before:
![image](https://user-images.githubusercontent.com/12080017/38803988-21a2f360-4171-11e8-9ef4-596b6723c3b1.png)
![image](https://user-images.githubusercontent.com/12080017/38804020-34da1756-4171-11e8-8484-8cc86eff78b3.png)

manually fix of wrong shown version:
1. Extract the CMI7.6.7.0.jar with a Zipper like 7-zip
2. Open the Plugin.yml - and replace version: 7.6.6.2 with version: 7.6.7.0
3. save the file
4.  open the CMI7.6.7.0.jar with a Zipper (like 7zip)
5.  overwrite you modified plugin.yml (that is inside the extracted folder) with the plugin.yml inside the CMI7.6.7.0.jar (copy and paste  )
6.  copy the CMI7.6.7.0.jar back to your pluginsfolder and reload your CMI (serverrestart or pluginmanager)

after:
![image](https://user-images.githubusercontent.com/12080017/38804005-2d888514-4171-11e8-95c5-bca505f0a186.png)

**Comment by CypherPhyre** [comment]
The issue is fixed with 7.6.8.0
