### ISSUE TITLE
Unable to use most GUIs

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#2660]
**Description of issue:**

When I try to use /warp GUI to open edit warps GUI or travel, it just kicks me out of the menu. The same happens with /kit when trying to open edit or get a kit. /kiteditor is also not working and just kicks me out of the menu when trying to edit any items. /home GUI seems to be working fine though.

---

**Cmi Version (using`/cmi version`):**  8.6.18.0

**Server Type (Spigot/Paperspigot/etc):**  Paper(51)

**Server Version (using `/ver`):** 1.15.1

We're running Bungee if that affects it in anyway.

**Comment by Zrips** [comment]
Any errors? And did you tested this one with CMI only, just to rule out possible incompatibility wit another plugin?

**Comment by DrakePork** [comment]
After getting to test it further seems like the issue is happening due to a custom plugin we have, so I'll just close this issue.
