### ISSUE TITLE
/stats and /info displaying bottom text wrong

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#2661]
**Description of issue:**

After updating to the latest version the /stats and /info commands have had their previously bottom line moved a few lines up the text, and now looks like this: [https://imgur.com/a/XyPO3QP]()

---

**Cmi Version (using`/cmi version`):** 8.6.18.0

**Server Type (Spigot/Paperspigot/etc):** Paper(51)

**Server Version (using `/ver`):** 1.15.1

**Comment by Zrips** [comment]
Good point, will get fixed with next build
