### ISSUE TITLE
Invlist Problem

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#2665]
when I do an invlist with a player I can look at his inventory. But I can no longer teleport to the player's place of death when I click on the map symbol. Then always comes in chat I have no rights. This is only since the 8.6.18.1

**Comment by Blueeyestar** [comment]
I can also no longer edit the inventories of the users with / inv as owner. It also comes I have no rights

**Comment by Zrips** [comment]
Strangely those permissions have not been touched in last update. I did removed some default preset permissions and those have been causing issues with 1.14+ servers where you could not tab complete command. Will change things around so that OP player has access to those permission by default.
