### ISSUE TITLE
CMI Glow stays red

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#2673]
Using the glow command, the glow is always red.
---

**Cmi Version (using`/cmi version`):** 8.6.18.2 

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.15.1

**Comment by Zrips** [comment]
Try test it with only CMI, so we can rule out other plugin interferring

**Comment by therealatsuga** [comment]
I do have a similar issue. The glow color is the same as the displayname-color.

**Comment by mrfloris** [comment]
In another ticket (https://github.com/Zrips/CMI/issues/3310) someone mentioned they've done this to resolve it: `change the config option DisableTeamManagement to false`

Looking forward hearing if this is still an issue on latest CMI version and Paper 1.16.3 or 1.15.2

**Comment by mc-System404** [comment]
If your using TAB PREMIUM plugin follow this tutorial to make your /glow working 👍 
https://github.com/NEZNAMY/TAB/wiki/How-to-make-TAB-compatible-with-glow-plugins
