### ISSUE TITLE
Add -w world to killall command

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#2674]
Please add world support for the killall command. For example: cmi killall sheep -w world2 thanks

**Comment by Zrips** [comment]
/cmi killall (-monsters/-pets/-npc/-animals/-ambient/-named/-f/-lightning/-list/-m:[mobType]) (-r:range) (-s) (-w:[worldName])
You might need to update that locale line by removing it and letting to regenerate. This was added some time ago, but you still have old entry
