### ISSUE TITLE
Console flooded with exception errors after last upgrade

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2676]
**Description of issue:**
Woke up to this:
https://hasteb.in/hocogaru.cs
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

got migraine, woke up to this, just reporting it, sorry for not filling out the form. 

spigot 1.15.1 latest cmi.

**Comment by Zrips** [comment]
Pushing out hot fix soon for this one
