### ISSUE TITLE
AFK Teleport (AFK Cafe) 

### ISSUE THREAD

**Issue by Dominiik001** [Zrips/CMI#2677]
**Description of feature/improvement request:**
I would like an AFK teleport for the CMI plugin
### Detailed explanation of what it should do, when and in what situation: ###

II mean that as soon as the plugin recognizes that someone is afk, he will be teleported to the point where, for example, you set with / setafktp. We want to teleport our members to an AFK Cafe as soon as they are afk. That would be a suggestion from me. There is something like a plugin, but it only works with Essentials / X.

And if you leave this region (you would have to set with Worldguard first), you are out of AFK mode again

### Basic explanation as to why this feature is needed and/or useful to have: ###
I find the function useful for people who do not want people who have to go to afk not to be killed very quickly or something like that in an AFK house they would be safe and can be relaxed afk.

**Comment by Dominiik001** [comment]
mrfloris
yes it works thanks for the help, I found this function.

**Comment by Dominiik001** [comment]
Now you can go afk but as soon as one of the positions is over then nobody else can be teleported to the AFK House because of the player colisions there is no region to add so that you have no colision or something?

**Comment by mrfloris** [comment]
```
  # Disables afk on interaction
  DisableOnInteract: true
```
Maybe play around with this (toggle it to false)

**Comment by Dominiik001** [comment]
No not working

**Comment by Zrips** [comment]
@Dominiik001 
use something like /cmi tppos [playerName] 0 67 0 LT_Craft -rng:25
This will teleport player to that location while randomizing its location up to 25 blocks. So you can place players in there with lower chance for them to overlap. This will no be bullet proof, but it should be more then enough to put like 15 afk players without overlapping them in most cases

**Comment by Zrips** [comment]
Och, and will add some extra check for this command to try and avoid placing player over each other if possible.
