### ISSUE TITLE
Alias not working

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#2678]
**Description of issue:**
Alias not working. Just the default Minecraft Unknown command message
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
https://pastebin.com/448EnK8s
```

---

**Cmi Version (using`/cmi version`):** 
8.6.18.2
**Server Type (Spigot/Paperspigot/etc):** 
paperspigot
**Server Version (using `/ver`):** 
paperspigot 1.15.1 (jan 18th from serverjars.com)

**Comment by mrfloris** [comment]
Does it show it's not working, but it actually works when they press enter?

**Comment by Insprill** [comment]
Nah, it just gives the "unknown command. Type /help..."

**Comment by Insprill** [comment]
whoops, there was no space before the true on one line messing up the whole file :| my bad
