### ISSUE TITLE
Anvil command still creating errors

### ISSUE THREAD

**Issue by MidnightSugar** [Zrips/CMI#2679]
**Description of issue:**
8.6.18.1 fixed most of the errors I have been getting, unfortunately when an item is put into the gui it is throwing the following error.

---

**ERROR**
https://pastebin.com/PJ98nCvk

---

**Cmi Version (using`/cmi version`):** 8.6.18.2

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Git-Paper-58

**Comment by Zrips** [comment]
Should get fixed with next build
