### ISSUE TITLE
Broken Link in CMI Wiki 

### ISSUE THREAD

**Issue by EchocallingEarth** [Zrips/CMI#2683]
The Command section of the CMI Wiki has a broken link in it:

https://www.zrips.net/cmi/commands/

"info (playerName/uuid)
Show players information
cmi.command.info.ip is required to see players ip address. To see players country you will need THIS file to be present in CMI folder" →(see image)

![broken link](https://user-images.githubusercontent.com/47970978/72784008-c8cb1480-3bf5-11ea-948e-99ab8bfaf474.PNG)

Link goes to this domain page → (see image)
![Screenshot (28)](https://user-images.githubusercontent.com/47970978/72784120-12b3fa80-3bf6-11ea-9fd9-fd9d5e48ca68.png)

Any other information required please let me know. 

Thanks Echo

**Comment by Zrips** [comment]
Fixed
