### ISSUE TITLE
CMI Ranks - FromLastDeath incorrect timer

### ISSUE THREAD

**Issue by Verdux** [Zrips/CMI#2685]
The tracking of FromLastDeath is incorrect in /rankup but correct in /cmi stats however it doesn't allow players to rank up due to the timer in /rankup being different

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  StatsRequirements:
  - 'FromLastDeath:21600'
  - 'blocksmined:500000'
  - 'MonsterKills:10000'
  - 'SleeptInBed:100'
  - 'FishCaught:500'
  - 'ItemEnchanted:50'
```
Screenshot to show them both for the player "Morphie"
http://prntscr.com/qqym9f
---

**Cmi Version (using`/cmi version`):** 
8.16.8.3
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.14.4

**Comment by Zrips** [comment]
Good catch, will be fixed with next version
