### ISSUE TITLE
/anvil (player) error

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#2687]
**Description of issue:**
If you type /anvil <player> when their offline it spits out an error

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/TMWhaRC8
```

**Cmi Version (using`/cmi version`):** 
8.6.18.3
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
Paper version git-Paper-60 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will get fixed with next version
