### ISSUE TITLE
cmi custom recipe error

### ISSUE THREAD

**Issue by arts7493** [Zrips/CMI#2688]
**Description of issue:**
Tried to load unrecognized recipe: bukkit:7036a5bc-0025-412e-834f-fd08a0f9c369 removed now.
Tried to load unrecognized recipe: bukkit:7036a5bc-0025-412e-834f-fd08a0f9c369 removed now.
bukkit error when player join

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** last version

**Server Type (Spigot/Paperspigot/etc):**  paper

**Server Version (using `/ver`):** 1.15.1

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
This doesnt say allot or anything about bug itself or where its originating. Check your customRecipes file for any posible issues or even remove it entire to make sure that its originating from CMI. And if you upgraded your minecraft version, you might need to recreate some of the recipes. Without any extra information, cant really help out.
