### ISSUE TITLE
Hit Counter and Multiple Names

### ISSUE THREAD

**Issue by EtherGamer** [Zrips/CMI#2690]
**Question: **
Hello, I just bought CMI recently so I'm kinda mew to it, but is there to remove the hit counter on mobs because due to it, it's causing the hologram to stay and making the player see it all over the place.

Second, if there was a way to remove the player multiple name, for example "tpa %player%, when using it and when the player has a nickname, it shows the realname and the nickname. Thank you in advance!

**Comment by Zrips** [comment]
hit counter is not part of CMI. it could be that some another plugin uses CMI hologram API to achieve this. So it would be nice to know which plugin it is so i could test it out and see if there is some issues with that plugin in particular.
For nick name in tabcomplete, go into config file and under NickName->IncludeInTabComplete set it to false

**Comment by EtherGamer** [comment]
Ahh thanks and I found the the bug on the hit counter hologram, It was MMOItems damage indicator that shows the hologram, I'm using Spigot 1.14.4 just in case if there was just a bug on that version, Thank you!
