### ISSUE TITLE
Free Item Signs

### ISSUE THREAD

**Issue by ZEROOblivious** [Zrips/CMI#2691]
**Feature Request:**

Essentials use to have the sign thing where you can do ;

[Free]
writable_book 

and it would give an infinite amount of books; Can this be a CMI Feature as well? 

![image](https://user-images.githubusercontent.com/32251194/72952471-f8962b80-3d5f-11ea-82d6-7266e5fc50f3.png)

**Comment by mercurialmusic** [comment]
You can already do this with CMI's Interactive Commands. Place a sign and write what you want on it, then create a new IC with the give command. Can also implement cooldowns, etc. 

See: https://www.zrips.net/cmi/commands/interactive-commands/
Also: https://www.zrips.net/cmi/commands/specialized/

**Comment by ZEROOblivious** [comment]
Thank you that's very helpful!
