### ISSUE TITLE
/tempipban | reason is not displayed.

### ISSUE THREAD

**Issue by Roper89** [Zrips/CMI#2693]
In the config — reason: &6Reason: **[reason]**
But instead of the reason, **[senderDisplayName]** is displayed.
Example:  https://i.imgur.com/SxNKGa5.jpg
This is when using `/tempipban`, with `/tempban` there is no such problem.

P.S. If you login with another nickname, the reason will be shown.

**Comment by Zrips** [comment]
Will get fixed with next build
