### ISSUE TITLE
Bossbar Compass Duplicating

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#2696]
**Description of issue:**
Bossbar compass randomly duplicates. So there is for a few seconds 2 compasses but only 1 works then the frozen one goes away. Happens completely randomly.

---

---

**Cmi Version (using`/cmi version`):** 
8.6.18.3
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper(67) 1.15.2 (happened on 1.15.1 to)

**Comment by Zrips** [comment]
What update interval do you have set for?

**Comment by Zrips** [comment]
Anyways, will make some changes to minimize the probability in getting double compass. if it repeats, let me know.
