### ISSUE TITLE
ArmorStand Interface Duplicate

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#2697]
**Description of issue:**
If a player is editing armorstand with /armorstand, and another player break the armorstand,
the items on armorstand will drop, but the edit interface won't close until the player click an item on it.
(The item be clicked will drop out, so the item duplicated)

---

**Cmi Version (using`/cmi version`):** 
8.6.18.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.14.4

**Comment by Zrips** [comment]
Pushing out hotfix
