### ISSUE TITLE
Player teleported into a lava pit under their /back location.

### ISSUE THREAD

**Issue by Darko2117** [Zrips/CMI#2698]
**Description of issue:**
A player was on a boat in the middle of the ocean, teleported somewhere, and when they did /back it teleported them into a lava pit directly under the boat they were on.
https://cdn.discordapp.com/attachments/514922300601008128/669322305331003412/2020-01-22_00.24.25.png
https://cdn.discordapp.com/attachments/514922300601008128/669322303196102675/2020-01-22_00.24.39.png
https://www.youtube.com/watch?v=Cdhmattwkgk

---

**Cmi Version (using`/cmi version`):** 
8.6.18.2
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
git-Paper-58 (MC: 1.15.1)

**Comment by Zrips** [comment]
Does that player have cmi.safeteleport permission node? And what do you have set for SafeLocationDownThenUp in your config file?

**Comment by Darko2117** [comment]
Yes for the permission and SafeLocationDownThenUp: false

**Comment by Zrips** [comment]
Cant really reproduce this one at this time. It could be issue with CMI or it could be issue with minecraft itself, as it tends to teleport player into empty space if you are trying to get teleported inside a block. In general if player doesnt have cmi.safeteleport permission node, then he will simply be teleported to exact location without checking for possible empty spaces, so no relocation are been done in this case. Atleast it should not be.
