### ISSUE TITLE
Keep tfly between worlds

### ISSUE THREAD

**Issue by Superola86** [Zrips/CMI#2699]
The ./tfly command was made to give temp fly till the players flytime ends or the player logs out.
The player also looses the tfly if the player changes world, the time is still there but the player cant fly.

**Comment by mrfloris** [comment]
As an option, yes, I would love this, but pls do leave it off by default. We're using this for events etc, and would love to reset back to no temp fly if they leave early so they dont abuse this and fly in skyblock or survival world.

If there's a `-keep` toggle for true/false, that would be super handy.

**Comment by Sikatsu** [comment]
I would like this too. I have players that switch to the spawn world for their vote keys and already lose their temp fly. @Zrips
