### ISSUE TITLE
Cmi jump Addition

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#27]
A command called `/cmi jump` that lets you teleport to the block that you are looking at. in addition to this you could also make it so if you have `/cmi jump (user)` it makes the user jump/teleport to the block that you are looking at. Both have seperate permissions. `cmi.command.jump` and `cmi.command.jump.others`

Maybe even a `cmi.command.jump.override` that stops them from being jumped from others

**Comment by Ew9304** [comment]
This would be a great addition. I would love to use this command, but for Essentials it is bugged as players can /jump extremely far and there is no way to limit how many blocks they can /jump

**Comment by LogGits** [comment]
:o yeah a predefined limit (in config) would be a great addition to such a feature.

**Comment by Zrips** [comment]
Next update.
