### ISSUE TITLE
wrong informations on /seen

### ISSUE THREAD

**Issue by ScuroK** [Zrips/CMI#270]
I imported the playerdata and from minecraft and essentialsx.
 for most users /seen works fine.
But on other users i get wrong informations. it always tells me they were seen 48 years X X X ago.
no errors in game or in the console.

![2018-04-15_21 23 10](https://user-images.githubusercontent.com/10480144/38782461-1663d94c-40f4-11e8-9994-e4a7ba402630.png)

Cmi Version (using`/cmi version`): 
7.6.7.0
Server Type (Spigot/Paperspigot/etc): 
Spigot 1.12.2
Server Version (using `/ver`): 
b6ecf3b-9060bfa

**Comment by ScuroK** [comment]
i guess the user havent been online since our switch to CMI.

**Comment by CloudeLecaw** [comment]
you really saw 7.6.70 with /cmi Version?^^
i downloaded 7.6.7.0 today and Version was showing me it is 7.6.6.2 because in 7.6.7.0 they forgot to Change the Plugin.yml Versionnumber ;)

**Comment by ScuroK** [comment]
i did not take the version number from /cmi version but from spigot.

**Comment by Zrips** [comment]
Well yea, player never logged in after CMI got installed, but will make some changes to grab that information from player file with next update.
