### ISSUE TITLE
One player gets wrong time stats from CMI

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#2700]
**Question: **
Something go wrong if cmi lost connection to database.

One player gets his time reset (rest of the players is not effected), we fix it before, take old backup off stats. 

But this time is not work i´m try delete stats file and CMI reset all, but not the time (is stay on 1 day as it do before i´m delete stats file). Rewards get broken because it see the time is wrong. 

I´m not replace play-data file, i´m think we do it last time (is only think i´m not change this time).

So i´m guess something get broken in stats ore play-data file so cmi cant red it.

**Comment by broken1arrow** [comment]
I´m find were cmi take playtime and it not from vanilla stas is from player-data file.

I´m guess the file get corrupt when server crash.

So lock for Spigot.ticksLived (divide it whit 20 so get you sek). Im think was is this not cunt AFK time like vanilla do so thats way cmi not use stats for time.

**Comment by Zrips** [comment]
You can change from where CMi takes playtime in config file. Simply change PlayTimeFromStats to true or false depending what you want it to be.
