### ISSUE TITLE
[playerDisplayName] not working

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2702]
**Description of issue:**

When I use ''/pweather playername reset'' it works fine:

![image](https://user-images.githubusercontent.com/5664135/73019652-4a07ee80-3e24-11ea-93af-c89c2f9c15ce.png)

When I use ''/pweather reset'' it doesn't work:

![image](https://user-images.githubusercontent.com/5664135/73019671-5724dd80-3e24-11ea-80dd-ac2043c26b40.png)

@Zrips not sure why this happens, but I believe the ''gotreset'' is never being used?

**Comment by mrfloris** [comment]
P in pweather is "player weather", not global.

```
/cmi pweather (playerName) [sun/rain/reset] (-s)
```

The documentation indeed implies (playerName) the legend at the top says () = optional. 

So /pweather (/cmi pweather) should refer back to the player who executes it (if they have this permission).

Yeah, seems like a bug. 

However, I can't seem to reproduce it.

<img width="282" alt="Screenshot 2020-01-26 at 13 48 29" src="https://user-images.githubusercontent.com/28841349/73135459-903a9900-4042-11ea-86b8-cfa57baa4fc9.png">

I can do this successfully:
```
/cmi pweather mrfloris sun
worked

/cmi pweather reset
worked

/cmi pweather mrfloris sun
worked

/cmi pweather reset
worked
```

<img width="262" alt="Screenshot 2020-01-26 at 13 50 07" src="https://user-images.githubusercontent.com/28841349/73135473-c841dc00-4042-11ea-8ebd-0515c44e3dc0.png">

Additionally, using this, also worked for me.
```
/cmi pweather rain
worked, it rained

/cmi pweather sun
worked, it became sunny again

/cmi pweather rain
rain again..

/cmi pweather reset
worked, it reset, and became sunny again
```

If you have any information on how to reproduce this, please let us know?
What are you running? Spigot? Paper? Which version? And which version of CMI?

**Comment by Zrips** [comment]
@Sikatsu 
Its some what a bug and not really. In general original lines which doesnt contain any variable like [playerName] might not be able to translate it. As original line for this one dint contained it, it is some what broken. Will fix it and make it work in both situations.

**Comment by Sikatsu** [comment]
Hmm if it's originally not in the line, I think I made a mistake on my end too. Thanks for fixing it though!
