### ISSUE TITLE
Cannot Auto-complete /ignore w/ Perms

### ISSUE THREAD

**Issue by EnderGamingFilms** [Zrips/CMI#2705]
**Description of issue:**
Hey so I found a bug. When you enable the /ignore command in Alias.yml it doesn't actually let players auto tab complete it.
---

**Cmi Version (using`/cmi version`):*8.6.18.4* 

**Server Type (Spigot/Paperspigot/etc):*Paper(57) 1.15.1-R0.1-SNAPSHOT* 

**Server Version (using `/ver`):*1.15.1*

**Comment by Zrips** [comment]
You might need full server restart for it to included dully into tab complete list.
