### ISSUE TITLE
The display of a variable has broken.

### ISSUE THREAD

**Issue by Roper89** [Zrips/CMI#2708]
1)
The variable `[time]` does not work for tpa: **banned**.
It does not work ONLY in the **/tpahere**, when you use /tpa it works.

screenshot: https://i.imgur.com/rBMreko.png

2) 
The variables `[senderDisplayName]` / `[playerDisplayName]` do not work for tpdeny: **youDenied**.
I can’t indicate in the message to whom the request was denied.

**Comment by mrfloris** [comment]
About 1.

What does one have to do to get the banned: can't send request for x time, to work?

Is this when there's a cooldown on the tpa command? I am trying to reproduce this but can't seem to figure out when that msg is showing up.


About 2.

<img width="559" alt="Screenshot 2020-01-26 at 13 30 46" src="https://user-images.githubusercontent.com/28841349/73135233-19040580-4040-11ea-81fd-98bd038234f8.png">

Same here, I tried adding what i seen at other places, there's no entry to parse that for this phrase. It's not there originally either (so probably why).

**Comment by Roper89** [comment]
> I am trying to reproduce this but can't seem to figure out when that msg is showing up.

You must use /tpahere and the other player must deny. You should repeat the /tpahere command and then you will see this message.

**Comment by Zrips** [comment]
Wil get fixed with next build
