### ISSUE TITLE
cmi.bossbar.hpbar – does not work

### ISSUE THREAD

**Issue by Roper89** [Zrips/CMI#2709]
![Даша1](https://user-images.githubusercontent.com/30005257/73135895-d569c580-4058-11ea-8c40-c63e941ffbd8.png)
When I use `HpBarEnabled: true` — all players display HpBar
When I use `HpBarEnabled: false` — all players do not display HpBar

`cmi.bossbar.hpbar` — Permission does not change anything.

**Comment by mrfloris** [comment]
Tried it on paper 1.15.2 with cmi 8.6.18.4 with hpbarenabled to true, and the players having that permission node.

when they hit a mob the top of the screens hows the hp health bar of the mob.

can't reproduce. 

Can you try giving the group the permission again and then /stop the server and start it again and hit a mob in survival mode?

**Comment by Zrips** [comment]
@Roper89 
/cmi checkperm hpbar
As it says, its only rechecks permission access every minute, for efficiency sake. So this might be your issue.

**Comment by Roper89** [comment]
I don’t understand what I have to do so that the bossbar is visible only to players with permission.
My settings: HpBarEnabled: false  and given permission  `cmi.bossbar.hpbar`  for premium players.
 @Zrips does this work for you?

> rechecks permission access every minute

I do not see the bossbar at all. Not a minute later, not 15, not a day later.
