### ISSUE TITLE
Condense request (and a bug)

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#271]
So we have iron nugget to ingot to block.

Bug:
Doing /uncondense if it cannot fit in the inventory doesn't look like its dropping the extra on the ground.

Request:
Is there a way to get it to only uncondense a step down each time the command is used?
iron block -> iron ingot -> iron nugget (/uncondense twice)

**Comment by Zrips** [comment]
Hmmm, yea, small bug with inventory overflow not dropping correct amount on ground. Next update should be fixed and for that iron block -> iron ingot -> iron nugget its already doing this, you need to uncondense twice to get from iron block to nuggets
