### ISSUE TITLE
 /cmi give mob_spawner - not working

### ISSUE THREAD

**Issue by Roper89** [Zrips/CMI#2710]
/cmi give mob_spawner - not working
No longer issued.
-------------------------------------------------------
The problem is resolved.
Please add the correct description of the command.
(The correct  command /cmi give spawner)

**Comment by mrfloris** [comment]
`/cmi give spawner` works for me.
You can also include the mob type;
```
>cmi give mrfloris spawner:zombie
[17:41:10] [Server thread/INFO]: Giving 1 of Spawner (Zombie Spawner) to mrfloris
>
```

**Comment by Roper89** [comment]
@mrfloris, You have helped me :) 
I missed that the issuing command was changed.
The site https://www.zrips.net/cmi/commands/ is given the old description 
/cmi give **mob**_spawner:creeper

**Comment by Zrips** [comment]
its some what a bug, even tho its a legacy material name, it still should be supported. So will fix it with next build. Tho you can use that spawner:creeper for simplicity and being up to date
