### ISSUE TITLE
[Support] Does /cmi kick support multiple lines?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2712]
I see in-game if i use cmi kick that it wraps \n to a new line, but the player doesn't get that, it's just plaintext to them after they get kicked, on their screen.

```
/cmi kick player please go away \n you are annoying
```

player sees:
```
please go away \n you are annoying
```

in-game it shows:
```
player got kicked: please go away
you are annoying
```

Either it's not supported, not working as it is supposed to (bug?) or i dont know how to do this.

**Comment by Zrips** [comment]
Small bug, will be fixed with next build
