### ISSUE TITLE
 [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.4

### ISSUE THREAD

**Issue by SilkPenny** [Zrips/CMI#2714]
My console and logs are severely spammed with versions of the following error.  At the same time, the server is experiencing consistently low TPS of around 10-15 (at times lower) and I cannot tell if the TPS drop is triggering the error...or if the error is causing near-constant low TPS.  No warnings or errors in startup logs.

I cannot diagnose what is happening. 

ERROR TITLE:  [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.4

ERROR FULL:  Repeats with rare pauses; could not copy all
https://pastebin.com/hQYrgcqT

CONFIGS:  https://pastebin.com/GUGgKhmu

CMI VERSION: 8.6.18.4

SERVER:  PaperSpigot 1.15.X (formerly 1.15.1; error persisted after updating to 1.15.2 today)

**Comment by Zrips** [comment]
Seams to originate from me.rerere.matrix.IIIIiIiiIi no idea what plugin it is, but will add some extra fail saves to prevent errors like this in the future.
