### ISSUE TITLE
PermisionOnError: false - does not work

### ISSUE THREAD

**Issue by Roper89** [Zrips/CMI#2715]
PermisionOnError: true / false — players always see what resolution is missing, regardless of the settings.

![Даша3](https://user-images.githubusercontent.com/30005257/73142792-dd028c00-40a3-11ea-9b6f-305b68e1b83c.png)

**Comment by Zrips** [comment]
As comments above this setting says, players with cmi.permisiononerror permission node will still see missing permission node. If you want to hide it entirely you will need to set this to false and to negate cmi.permisiononerror for players who should not see missing permission node
