### ISSUE TITLE
Help pages broken when language is RU

### ISSUE THREAD

**Issue by dinfyru** [Zrips/CMI#2718]
/cmi help - Russian default translate is broken. All pages are the same. In the Russian translation file, the necessary translations are present

![image](https://user-images.githubusercontent.com/10163112/73199846-ac276300-4146-11ea-93d5-cc3a4913ddc9.png)

---
Paper - 1.15.2, build 67
CMI - 8.6.18.4

**Comment by Zrips** [comment]
This seems to be issue with translation file. Some one mistranslated it... Will fix it, tho you will need to update it manually at this point.
`command:
  help:
    output:
      usage: '&eИспользуй: &6%usage%'
      cmdInfoFormat: '[command] &f- &e[description]'
      cmdFormat: '&6/[command]&f[arguments]'
      helpPageDescription: '&e* [description]'
      explanation: '&e * [explanation]'`
