### ISSUE TITLE
Request extansion for killall

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#272]
I know the kickall command was added in last update :)

Wanne ask if it is possible to extand the TAB-completation with the entynames of monsters and animals
this is how it currently looks:
**example why it would be nice to have**
/cmi killall Endermite .... or /cmi killall En[TAB][TAB]  and u have it..

Also if u type "nonsense" after killall it automaticly does a "cmi killall" and kills all...was that wanted?
![image](https://user-images.githubusercontent.com/12080017/38835374-9dd2f0b6-41cb-11e8-9f92-8c4cb486b714.png)

currently it looks like this and u have to mannually tipp all monster and animals but [mobType] is one of the Tab options 🥉 
![image](https://user-images.githubusercontent.com/12080017/38835192-184bc346-41cb-11e8-9d0d-89dc652c01d7.png)

For the Result: Currently u get a measshe how much mobs where removed... nice but it realy
would be cooler to see "what" was removed.. 
Example: your type /cmi killall -parrots 20
 Then it would be nice to have the Measssge
 as feedback: X parriots killed.

currently the feedback looks a bit wrong in my eyes..
![image](https://user-images.githubusercontent.com/12080017/38835764-5c7ebf72-41cc-11e8-9812-241c4edea563.png)
i know a zombie is a monster too... but the command was send to kill Zomboes not "all" monsters..
you know what i mean? :3

Finalyly the killall should be compatible with the -s option. Speciyl when u let a commandblock execute it permanently. the Result spamms the console a bit ;)
![image](https://user-images.githubusercontent.com/12080017/38838660-8a838df2-41d7-11e8-81d7-939ee959130a.png)
i tried adding the -s but the console still sees it 🥉 
![image](https://user-images.githubusercontent.com/12080017/38838707-cb067dd0-41d7-11e8-8b55-24603bab4808.png)

**Comment by Zrips** [comment]
Okey, next update.
