### ISSUE TITLE
RemoveLable doesn't work

### ISSUE THREAD

**Issue by TheGamingChris** [Zrips/CMI#2720]
**Description of issue:**
RemoveLable doesn't work. I can't do (for example) /back . Only /cmi back works

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
  RemoveLabel: true

---

**Cmi Version (using`/cmi version`):** 
8.6.12.4
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
git-Spigot-56f8471-6567017 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):**
CMI

**Comment by Zrips** [comment]
RemoveLable Is not made to remove /cmi if you want to use short commands, then you will need to enable them in alias.yml command
