### ISSUE TITLE
Bug with placeholder %cmi_user_maxperm_[corePerm]_[defaultValue]%

### ISSUE THREAD

**Issue by fhebuterne** [Zrips/CMI#2721]
Hi,

I'm using CMI on last version and on 1.15 server, and i want to use this placeholder %cmi_user_maxperm_[corePerm]_[defaultValue]% on BossShopPro, it work perfectly with CMI permissions but it doens't work with other permissions like lands.ownlands.NUMBER or test.test.NUMBER (it show default value), do you have any solution please ?

I have this command in my BossShopPro :
broadcast test %cmi_user_maxperm_lands.ownlands_5%

Base perm is : lands.ownlands.1

And my test user has : lands.ownlands.20 in my server context (i'm using LuckPerms).

Sincerely,
Fabien

**Cmi Version (using`/cmi version`):**  8.6.18.4

**Server Type (Spigot/Paperspigot/etc):**  Paper version git-Paper-23 (MC: 1.15.1)

**Comment by Zrips** [comment]
Well it wasnt made to support permissions from other plugins, but we can update this one. Should work correctly with next build.
