### ISSUE TITLE
1.15.2 sign edit not working

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2725]
**Description of issue:**

- When I change a sign and click on ''Done'' it will just change back to what it was.
- If I place a sign with color codes, try to edit it and click on ''Done'' it will reset to what it was, but it'll break the color code and just show it on the sign as ''&4Test''.
- Also seems that you can't change the color if you used minecraft's mechanic to change the sign color.

CMI 8.6.18.5
Paper 83

**Comment by Zrips** [comment]
Use newest version 8.6.18.6, it had fix for sign editing.
