### ISSUE TITLE
Getting charged for repairs with off in Config

### ISSUE THREAD

**Issue by BoosterBots** [Zrips/CMI#2727]
**Description of issue:**

I am getting charged for repairing an item even though inside the config I have CostsMoney set to false.

Screenshot showing repair cost being taken: http://prntscr.com/qunozl
Screenshot showing my config repair section: http://prntscr.com/qunplq
---

Running Paper version git-Paper-79 (MC: 1.15.2)
CMI 8.6.18.6

**Comment by Zrips** [comment]
You are not being charged, its only message which shows it. Will fix.
