### ISSUE TITLE
Editing armor stands replaces a random person's armor with armor stand gui items.

### ISSUE THREAD

**Issue by Darko2117** [Zrips/CMI#2729]
https://github.com/Zrips/CMI/issues/2627

Same issue still exists. This time it happened to players named 5up3rZ and 57a when we tested it.
The previous issue was closed but the bug still remains.

**Cmi Version (using`/cmi version`):** 
8.6.18.5
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
git-Paper-84 (MC: 1.15.2)

**Comment by Zrips** [comment]
Any way to consistently reproduce this issue? As with curent released version i can reproduce it any longer.

**Comment by Darko2117** [comment]
For us it's very consistent, it happens every single time. Shift right clicking an armor stand and changing it the tiniest bit is enough for the bug to occur. You could test it on our server if you think it would help.

**Comment by Zrips** [comment]
Would be nice, as i cant reproduce it, so maybe its an issue with another plugin compatibility

**Comment by Darko2117** [comment]
My discord is Daki#6572. I'll send you the IP there and come online when you're available.

**Comment by Zrips** [comment]
You can find me at http://discord.gg/dDMamN4 send me a private message and i will join it
