### ISSUE TITLE
NullPointerException on PlayerInteractEvent

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#2730]
**Description of issue:**

I'm randomly getting spammed with the error below. Don't know whats causing it but looks like something with the offhand from what I can tell about the error.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://hastebin.com/ayasulateb.sql
```

**Cmi Version (using`/cmi version`):** 8.6.18.6

**Server Type (Spigot/Paperspigot/etc):**  Paper(85)

**Server Version (using `/ver`):** 1.15.2

**Comment by Zrips** [comment]
Originates from rerere.matrix plugin, duno what it is or what it does, but its creating some messed up date related to player inventory. Will issue fix, but would be nice to know which plugin this is and what it does.

**Comment by DrakePork** [comment]
https://www.spigotmc.org/resources/matrix-anticheat-advanced-cheat-detection-1-8-1-12-1-13-1-14-1-15.64635/
