### ISSUE TITLE
Give command does not work when giving mod item

### ISSUE THREAD

**Issue by sumdream** [Zrips/CMI#2733]
**Description of issue:**
Hi,I am using CMI in Catserver(Forge+bukkit),CMI work correctly in old version.But in new version CMI,When using give command  to give player mod item,it always give player an STONE. Sry for my poor English.

---

**Cmi Version (using`/cmi version`): 8.6.18.6** 

**Server Type (Spigot/Paperspigot/etc): [CatServer(Forge+Bukkit)](https://github.com/Luohuayu/CatServer)** 

**Server Version (using `/ver`):1.12.2**

**Comment by Zrips** [comment]
Some extra information would be nice, like, any errors?

**Comment by sumdream** [comment]
The console doesn't have any error information. Give vanilla item is  correctly.

**Comment by sandwally** [comment]
I guess it's a generated give command from sites like https://www.digminecraft.com/generators/give_fireworks_rocket.php
If you create a rocket with additional effects and copy the command you will get stone as default and the formatting of the command wont work.
