### ISSUE TITLE
Cmi and world border conflict crash

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#2734]
**Description of issue:**
So I keep getting this error/crash whenever someone is right near the world border (plugin: worldborder).  

I'm not sure if its CMI or not, I'm not the best at reading these errors. This did start happening in 1.14 and is still an issue on 1.15.2 (paper spigot)

I do also have  the selection visualizer plugin but we did disable it to make sure it wasn't that.

https://pastebin.com/Q2tmKK6r

**Cmi Version (using`/cmi version`):** 
8.6.18.
**Server Type (Spigot/Paperspigot/etc):** 
paper 1.15.2  - 84
**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**
Worldborder

**Comment by Zrips** [comment]
It's Selection Visualizer which seems to be causing this issue. I will fix it and post a new version soon.

**Comment by Zrips** [comment]
Och, and check your Selection Visualizer Cylinder update interval settings, it might be issue with extremely low numbers of updates and huge amounts of particles.

**Comment by Kbryst** [comment]
This part right?

`    Cylinder:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 119;136;153
        Cap: 200`

File's just the default file

**Comment by Zrips** [comment]
Well its a default ones, but you will need to check player personal settings too. But will make some extra tests just in case its calculation is not as optimized as it should be with cylinders in such sizes

**Comment by Kbryst** [comment]
I can just disable the world border thing right?

WorldBorder: false
