### ISSUE TITLE
Feature Request Vanish Rank Tracking

### ISSUE THREAD

**Issue by ZEROOblivious** [Zrips/CMI#2739]
Greetings,

Does this plugin have compatibility with a separate Vanishing Plugin? 
https://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/

---
Recently noticed with CMI Rank System whenever the Requirement of Playtime is needed, a user who is in Vanish it does not track their playtime on the server.

Would help my staff team while being in Vanish be able to complete their Rank Requirements.

Question: Does it track the playtime while using CMI Vanish?

**Comment by Zrips** [comment]
Playtime is tracked and taken from player data file or player stats file. If its not adding playtime while they are vanished, then check you vanish plugin settings, as it most likely prevents player time from being accumulated while player is vanished.
