### ISSUE TITLE
ghost?

### ISSUE THREAD

**Issue by hc119** [Zrips/CMI#274]
how to remove ghost ?, ghost appear only in default player not staff, and appear in tablist too but not in staff

**Comment by Zrips** [comment]
What exactly you are talking about here?

**Comment by hc119** [comment]
in default player, there is the purple nick in tablist, when in the night and alone, that ghost with purple nick disturb player, if we look to them behind us he always hindering, that gave our player uncomfortable playing

**Comment by LogGits** [comment]
lol screenshots plz.

**Comment by CloudeLecaw** [comment]
sounds like the anticheat detection of some plugins that work with ghost entities or players

**Comment by hc119** [comment]
that's ghost soo agile, like he has a special animation when hindering, not like a normal player, and we can hit it if we crouch, then he runs away

**Comment by CloudeLecaw** [comment]
What ever u have there (still sounds like a Herobrine troll, or a bugged feature of some Anticheat Plugin) CMI Never has touched the NPC Features of Minecraft, so there cant spawn a ghost from CMI.
Try to disable your anticheat and look if this bug remains...oh and pls..no ghost Reports anymore...

**Comment by Zrips** [comment]
@hc119 Yea, what @CloudeLecaw  said, CMI doesn't have any code related to NPC, atleast which would currently be working. So this issue is from another plugin and completely unrelated to CMI. Most likely some trollish plugin or some one messing around with you with OP account or something.
