### ISSUE TITLE
PlayerInteractEvent to CMI v8.6.18.8

### ISSUE THREAD

**Issue by recycie** [Zrips/CMI#2741]
Have error and server freeze crashed

> [00:34:43] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.8
> java.lang.NullPointerException: null
> 	at com.Zrips.CMI.Modules.Afk.AfkListener.isSameDirection(AfkListener.java:246) ~[?:?]
> 	at com.Zrips.CMI.Modules.Afk.AfkListener.PlayerInteractEvent(AfkListener.java:312) ~[?:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor695.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-89]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-89]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-89]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-89]
> 	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:458) ~[patched_1.15.2.jar:git-Paper-89]
> 	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:425) ~[patched_1.15.2.jar:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.BlockRedstoneOre.stepOn(BlockRedstoneOre.java:36) ~[patched_1.15.2.jar:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.Entity.move(Entity.java:628) ~[patched_1.15.2.jar:git-Paper-89]
> 	at me.rerere.matrix.nms.versions.v1_15_r1.NMS_V1_15_R1$ME_15_R1.iiIiiiiIII(Unknown Source) ~[?:?]
> 	at me.rerere.matrix.iiIiIIiIiI.a(Unknown Source) ~[?:?]
> 	at me.rerere.matrix.iiIiIIiIiI.iiIiiiiIII(Unknown Source) ~[?:?]
> 	at me.rerere.matrix.IiiIiiiIii.iiIiiiiIII(Unknown Source) ~[?:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor367.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-89]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-89]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-89]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1115) ~[?:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:86) ~[patched_1.15.2.jar:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-89]
> 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-89]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

---

Cmi Version 8.6.18.8

**Server Type Paperspigot

**Server Version 1.15.2

**Comment by Zrips** [comment]
Should get fixed with next version. And issue originates from your Matrix anticheat plugin.
