### ISSUE TITLE
CMI takes to long to load/start

### ISSUE THREAD

**Issue by abhisantos** [Zrips/CMI#2744]
**Description of issue:**

CMI takes to long to load/start! It takes like **153000** miliseconds to load.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
CMI8.6.18.2.jar or any other version
**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
1.8.8
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Well startup log would be nice to have. After all, i did added timers how long it takes to load a particular part of plugin, so this could indicate which part is heaviest.
