### ISSUE TITLE
bossbarHP bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#2746]
if the very high damage , bossbarHP damage can't show Correct value
please check, Happened recently

**Cmi Version (using`/cmi version`):** 8.6.18.8

**Server Type (Spigot/Paperspigot/etc):** paper 

**Server Version (using `/ver`):** 1.14.4

**Comment by Zrips** [comment]
What is that value? Any pictures?

**Comment by p82183645** [comment]
> What is that value? Any pictures?

![image](https://user-images.githubusercontent.com/5382252/74094883-5a59e200-4b23-11ea-9f56-eaa81290338d.png)

happen 1.14.4
if you damage A lot more than monster health, the happen
no show Right damage
my damage 10000
