### ISSUE TITLE
About Vault's dependencies

### ISSUE THREAD

**Issue by BackWheel** [Zrips/CMI#2747]
When I run the server using the Vault plugin that comes with CMI, it always issues this warning:

[13:37:25 WARN]: [Vault] Loaded class com.Zrips.CMI.Modules.Economy.Economy from CMI v8.6.18.8 which is not a depend, softdepend or loadbefore of this plugin.

**Comment by mrfloris** [comment]
This is something that got updated in Spigot 1.15.2 more recent releases. 

It's unrelated to CMI (in a way), this happens for things like PlaceHolderAPI as well, and a few other plugins that work together. 

The Spigot JIRA discussion about this can be found here:
https://hub.spigotmc.org/jira/browse/SPIGOT-5546
