### ISSUE TITLE
Ask for permission Node

### ISSUE THREAD

**Issue by ansontsang1112** [Zrips/CMI#2748]
I wanna ask if I assign the permission node **cmi.command** and my players can use /**:**<command> to override the setting. How can I block the **:** with another permission node?

**Comment by mrfloris** [comment]
I really remember reading something about this in either another github issue or changelog, and I cannot find it now. I really want to know as well. I thought it was fixed rather recently, but I can't find it at all. Been searching for nearly 17 minutes now.
