### ISSUE TITLE
[Enhancement] Specificity in IC Sign Permissions 

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#275]
Description of feature request:
So for starters, **thank you**. Those IC Signs are exactly what I've been wishing for but didn't want to bother requesting.

Much like cmi.command.warp.[warpname], though, it would be highly useful to be able to specify permissions for IC signs that players are able to create, i.e. cmi.interactivesign.[ICname]

For example, I have interactive commands for /cmi disposal that I'd want to let players create for themselves, but they should not have free reign to create signs for the rest of our ICs (nor do I even want them to know what they are!).

Thanks as always for your brilliant work!

Cmi Version (using`/cmi version`): 7.6.10.0
Server Type (Spigot/Paperspigot/etc): Spigot Latest
Server Version (using `/ver`): Spigot 1.12.2-R0.1-SNAPSHOT

**Comment by MCTyler** [comment]
Yea just an extra node in Perms. Can these be added in plugin.yml? as a interim?

**Comment by MCTyler** [comment]
Plugin.yml won't work, he'll have to code these Perms in. :(

**Comment by mercurialmusic** [comment]
I'm just referring to ICSign creation, not IC creation itself. In theory players would only be able to create the ICSigns that you specifically gave them permission to create. If you have an IC that ops someone or allow players to create ICs then gave players the global ICSign creation permission, then in theory, yes, they'd be able to op themselves depending on how the IC was created in the first place (whether run as player or from console). But the only security flaw I see, both currently and with specific permissions, would be admin error.

**Comment by Zrips** [comment]
IC utilizes specialized commands which by default doesn't allow OP or DEOP commands to be performed in general. So that's should be more or less safe. But its always a risk from administration in creating something what could make a mess at end.

**Comment by MCTyler** [comment]
Sounds Like IC Signs are the equivalent to Command Blocks, if I understand correctly.

**Comment by MCTyler** [comment]
It appears based on my study that IC **is** checking Player Perms. You never really answered my question. If The players did not have the sell all permission, I.E. Type the command, then the sign is just a sing with words on it right?

**Comment by MCTyler** [comment]
Brain Fart...Sorry...this does run as console and only checks it for Perms....
```
tpkill:
  Location:
  - ==: org.bukkit.Location
    world: world
    x: 618.0
    y: 69.0
    z: -489.0
    pitch: 0.0
    yaw: 0.0
  Commands:
  - tppos 513 65 -491 [playerName]
  SignLines:
  - tpkill
  - ' '
  - ' '
  - ' '
```
```
[14:29:22 INFO]: [LP] VB > internal/console - cmi.command - true
[14:29:22 INFO]: [LP] VB > internal/console - cmi.command.tppos.others - true
```

**Comment by Zrips** [comment]
Will be added with next update. Specific permission requirement for IC signs.
