### ISSUE TITLE
Issue with tag system not working properly

### ISSUE THREAD

**Issue by pvvvo** [Zrips/CMI#2750]
Description of issue: All the tag system is enabled, but it doesn't work. When I tag for example: @RandomUser1, other player can hear it and he is not even tagged, doesn't matter who I tagged this other player gonna still hear it. And it choose randomly the player who can hear the sound.

Tag config:
##########################################################################
Tag:
    # Enable or not tag system. This will inform player with his name mentioning in public chat if name have @ in front of it
    Enabled: true
    # When this is set to true, any player mentionings in public messages will be colorized and player will get informed as usual
    # This is allot more heavier on server than usual tagging with @, so enable if you know what you are doing
    HardCoreMode: true
    # Determines color of taged user name in chat with @ in front of name/nickname. Sender should have cmi.tag.color
    Color: '&6'
    # Commands to be performed when player is tagged
    # Variables like [playerName] will be replaced with tagged player name
    # You can use [senderName] to include player name who tagged
    CommandsOnTag:
    - fromConsole! cmi sound block_note_block_pling -p:1 -v:100 [playerName]  ##
##########################################################################

---

CMI version: 8.6.18.8
Server type: Paper 
Server version: Paper version git-Paper-243 (MC: 1.14.4)

"Relevant plugins" (Don't know if this matter, but I will type the plugins who control chat): 
-> TownyChat (Version: 0.63)

**Comment by Zrips** [comment]
Will get fixed with next build
