### ISSUE TITLE
Totem active/warmup particle aura

### ISSUE THREAD

**Issue by MrTrinax** [Zrips/CMI#2751]
**Description of feature/improvement request:**
Option to display particles around the player when totem warmup is active.

---
### Detailed explanation of what it should do, when and in what situation: ###
When the player uses Totem, particles will appear around the player or when the player moves to indicate it is active.

### Basic explanation as to why this feature is needed and/or useful to have: ###
This feature would make PvP more fair and give it a more tactical feeling as players can visually plan out the fight as they are able to see if their opponent has the totem warmup active or not.

**Comment by Zrips** [comment]
Will be added with next version
