### ISSUE TITLE
Unusable items when attached commands on them

### ISSUE THREAD

**Issue by JohnPolyStriker** [Zrips/CMI#2753]
**Description of issue:**
I attached command on bow, crossbow, trident and shield. The command is executed after using the left mouse button. So the right one is free. I thought the items could still be used. Bow for shooting etc. But it can not be. Fishing rod executes the command even when using the right button, even if the command is set only for the left button.
It's fine that I can't place block if is attached command on it but items like bow etc. can be usable

---

**Cmi Version (using`/cmi version`):** 
8.6.18.8
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.15.1

**Comment by Zrips** [comment]
Good point, will change its behavior slightly and will allow item usage with button which dint performed any command. So you can have command on left click and shoot with right click
