### ISSUE TITLE
Editing books sometimes results in cursor displacement and client crash

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#2755]
**Description of issue:**

When editing a written book that is not yet signed, sometimes causes the cursor to be displaced (show at the wrong spot in the book).  When this happens, and you backspace at the end of the book, the client crashes with the error below.  After this has happened, opening that book and going to that page will crash the client consistently.
Both errors seem related to color codes (when it happens you've seen them being deleted)
The player writing or editing the book does NOT need to have color perms NOR does the book need to include actual colors for this to happen

This seems related to these other tickets: #2647 and #2603 but unlike 2603 it does not require the book to predate 1.15.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
The game crashed whilst keypressed event handler
Error: java.lang.StringIndexOutOfBoundsException: String index out of range: 61
```

---

**Cmi Version (using`/cmi version`):** 
[10:18:31 INFO]: CMI plugin version: 8.6.18.8
[10:18:31 INFO]: Server version: Paper(60) 1.15.1-R0.1-SNAPSHOT
[10:18:31 INFO]: Vault version: 1.7.2-b107

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
[10:19:09 INFO]: This server is running Paper version git-Paper-60 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
[10:19:09 INFO]: Checking version, please wait...
[10:19:10 INFO]: Previous version: git-Paper-51 (MC: 1.15.1)
[10:19:10 INFO]: You are 2 version(s) behind

**Comment by Momshroom** [comment]
Full crash report in client: https://pastebin.com/WYttEb7A

**Comment by Momshroom** [comment]
Video demonstration of crash: https://www.youtube.com/watch?v=MPxpDZbq9R8
The error code in that client crash:  https://pastebin.com/p9gNLzHQ

**Comment by Zrips** [comment]
This was bug in a client
