### ISSUE TITLE
How to disable ban/kick messages for normal players

### ISSUE THREAD

**Issue by BNK3R-Patrick** [Zrips/CMI#2756]
**Question: **
How can I disable ban messages for normal players?

**Comment by Zrips** [comment]
Normal players? You can add -s variable which will not print out any feedback messages but still sends message to the sender.

**Comment by BNK3R-Patrick** [comment]
Yes, for example on auto kick i don't want the kick message to be broadcasted

**Comment by Zrips** [comment]
So add **-s** to the command and it should be hidden
