### ISSUE TITLE
Can't show % in Locale file.

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#2759]
**Description of issue:**

When I want to show percentage sign in publicHover, the sign will cause some placeholders broken.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Chat:
  # Use \n to add new line
  publicHover: '&aSlimefun: &b%slimefun_researches_title% &7( &a%slimefun_researches_percentage_researches_unlocked% % &7) \n&eTime: &6%server_time_hh:mm:ss% \n \n&a> Click %vault_prefix%%player_name%'
```
---

**Cmi Version (using`/cmi version`):** 
8.6.18.7
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.15.2

**Comment by Zrips** [comment]
I will need real example with a pictures. As this is currently working correctly and you can show % in hover over messages

**Comment by coco0325** [comment]
https://imgur.com/a/WYyYhuD

**Comment by Zrips** [comment]
Och ok, now i got it. Will be fixed with next version
