### ISSUE TITLE
/tree tallspruce spawning birch

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#2760]
**Description of issue:**
when you do **_/tree tallspruce_** it spawns a birch tree
Might be with other trees not sure
---
---

**Cmi Version (using`/cmi version`):** 
8.6.18.8
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
paper-90 1.15.2

**Comment by Zrips** [comment]
There is no such thing as tallspruce in 1.15.2. This most likely caused by plugin like WorldEdit which has same command and which overrides tabcomplete by adding wrong tree types. 
Will issue some bug fix to properly override original command and its tabcomplete, so we could have correct tree names
