### ISSUE TITLE
Crash server. Errors Log4j2-TF-1-AsyncLogger and SpecializedCommands

### ISSUE THREAD

**Issue by Fiks75** [Zrips/CMI#2761]
Description of issue:
When start server and player join in console errors

```
https://pastebin.com/i89rLsSd
```

Cmi Version: CMI v8.6.19.0

Server Type: paperSpigot 1.13.2/1.14.4

Server Version: This server is running Paper version git-Paper-655 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
07.02 07:02:57 [Server] INFO Previous version: git-Paper-653 (MC: 1.13.2)
07.02 07:02:57 [Server] INFO Checking version, please wait...
07.02 07:02:58 [Server] INFO You are running the latest version.

**Comment by Zrips** [comment]
it could be issue with some specialized command point to itself which creates infinite loop. Check your event commands and what are you performing when player joins.

**Comment by Fiks75** [comment]
> it could be issue with some specialized command point to itself which creates infinite loop. Check your event commands and what are you performing when player joins.

But the previous version CMI8.6.18.8 works fine.

**Comment by Zrips** [comment]
Will have to revert back recent changes made for this part of code. Tho cant really reproduce issue at this point and would be nice to know which commands are been performed when player joins, just to narrow down possible causes of he issue.

**Comment by Fiks75** [comment]
I added this command in CustomAlias.yml file:
https://pastebin.com/7gDjLyh7

After adding custom alias all the CMI commands go to the / cmi panimation command
After the command / cmi reload the server crashed

**Comment by Zrips** [comment]
Avoid using alias like this, do something like **/animation hearth** instead of **/cmi panimation hearth** will have to test this one out in any case. And you can test out newest version, reverted back recent change related to alias handling.

**Comment by Fiks75** [comment]
I changed **/cmi panimation hearth** to **/animation hearth** in CustomAlias.yml file.

Result: 
CMI v8.6.19.0 - works fine.
CMI v8.6.19.1 - works fine.

Thank your.
