### ISSUE TITLE
Player Disconnect Error

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#2765]
**Description of issue or feature request:**
Throws this error when on player disconnect, no idea why (Its from the bungeecord plugin)
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/gQr4vKUH
```

---

**Cmi Version (using`/cmi version`):** 
8.6.19.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-93 1.15.2

**Comment by Zrips** [comment]
Resolved
