### ISSUE TITLE
Cooldown on attached command with !left! or !right! prevents item usage and regular usage of item triggers cooldown

### ISSUE THREAD

**Issue by NightFuryStrike** [Zrips/CMI#2768]
**Description of issue:**
I was trying out the new features of attached commands, and I noticed the following issues:

**Bug 1:** Using an item normally (for example swinging a sword that has a command attached to !right! click) will trigger the !cooldown! on the item without running the command. Expected behavior is that the cooldown would not be triggered and nothing would happen because it was only attached to !right! click

**Bug 2:** If an item with an attached command is on !cooldown!, such as a bow with a command on !left! click, regular usage of the item is prevented during the cooldown period. Bows will not fire and swords will not do damage and instead will show remaining cooldown on action bar every time the item is used, even if !left! or !right! was used. Expected behavior is that the item will remain usable while it is on cooldown if a command is not assigned to the mouse button that is used for normal use of the item.

I use attached commands frequently on my server for custom items, weapons, and spells/scrolls, so having these issues fixed would be appreciated so I can expand what can be created with attached commands. Thanks!
---

**Cmi Version (using`/cmi version`):** 8.6.19.1
**Server Type (Spigot/Paperspigot/etc):**  Paper 93
**Server Version (using `/ver`):** 1.15.2

**Comment by Zrips** [comment]
Should be fixed
