### ISSUE TITLE
Colors usage

### ISSUE THREAD

**Issue by PoulpinSky** [Zrips/CMI#2770]
**Description of issue:**
No matter what color permissions you set for a group, it keeps access to all colors

---

**Cmi Version (using`/cmi version`):** CMI: 8.6.19.1

**Server Type (Spigot/Paperspigot/etc):** Paper(1618)

**Server Version (using `/ver`):**  1.12.2-R0.1-SNAPSHOT

**Comment by PoulpinSky** [comment]
Any update ?

**Comment by Zrips** [comment]
You will only have access to all colors if you have wild card permission node like cmi.colors.nickname.*
