### ISSUE TITLE
[Bug] Random teleport inside walls

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#2775]
**Description of issue:**
When using the random teleport I often being teleported into a wall. Sometimes inside a wall, and sometimes a half block down. Seems like its always some few blocks under the surface.

---

**Cmi Version (using`/cmi version`):** 8.6.19.1

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** paper-93 (1.15.2)

**Comment by mrfloris** [comment]
Did this started to happen only recently? Because when we use /rtp from BetterRTP it happened as well. We tried cmi rt and this seems to work, but if you're saying it started to happen for you as well, then I wonder if should convert to cmi for it. Sorry if I misunderstand your report and it's a different kind of teleport issue.

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/807a677e9a59929e27ac1991c3fa1cf6a2ec0f4d

**Comment by Baktus79** [comment]
Yes, this happend very recently just right after a Paper update. As of the link you have provided it seems that something broke on the new changes done to the `getHighestBlockYAt`

**Comment by mrfloris** [comment]
Friendly bump, I still notice people reporting this on Discord and DM, I haven't recently tested this because I still use BetterRTP plugin which has this fixed now (can't wait to ditch it for /cmi rt)

**Comment by Va1a** [comment]
I believe the issue actually only occurs with players in creative mode. after doing some testing, while I was in survival and not flying, no issues arose.

**Comment by mrfloris** [comment]
<img width="1392" alt="Screenshot 2020-04-03 at 18 36 44" src="https://user-images.githubusercontent.com/28841349/78384225-1393e000-75da-11ea-8769-d837ff7b4b4c.png">

still happening in CMI plugin version: 8.6.21.2 and spigot 1.15.2

```
>ver
[18:37:15] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-a03b1fd-bbe3d58 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[18:37:15] [Server thread/INFO]: Checking version, please wait...
[18:37:16] [Thread-58/INFO]: You are running the latest version
>
```

**Comment by BoosterBots** [comment]
Some of my players and staff are reporting the same issues recently.

 Here is what one of them mentioned: "Whenever I /rt in the resource world it either says its unsafe because of the void or teleports me to a cave. I've tried four times. Twice I was in a cave and twice it said it was unsafe."

**Comment by Zrips** [comment]
Should get fixed with todays update.
