### ISSUE TITLE
Warp GUI page warmup separate from /warp command

### ISSUE THREAD

**Issue by CaliDreams** [Zrips/CMI#2778]
**Warp GUI page warmup separate from /warp command**

---
### Tried:
- cmi.command.warppages.cooldownbypass
- cmi.command.warppages.warmupbypass
- cmi.cooldownbypass.warppages
None of these work. I also do not have it in the config warmup/cooldown section -

This is all that's currently in my warmup list:
  List:
  - cmi tpa :3:true
  - cmi tpahere :3:true
  - cmi back:3:true
  - cmi warp :3:true
  - cmi home :3:true ###

###The GUI is so much nicer to see than the list! And the list is irrelevant at this point with command suggestions turned on. I think I asked about this once before and one of those permission nodes worked, but now they do not. It's quite frustrating as a player to simply turn a page in the warps menu and have to wait three seconds in between when they can just tab through options - but then they don't see the custom descriptions! ###

**Comment by Zrips** [comment]
Wil be fixed with next update
