### ISSUE TITLE
Holograms API not removing holograms properly

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#2782]
**Description of issue:**
When creating a hologram through CMI's Hologram API, and removing the hologram after x seconds, the hologram will still be present, until the user has re-logs. The hologram data is removed from /cmi holograms, but it creates a client-side error that still shows the hologram.

The following are my code to create the hologram
https://paste.md-5.net/imirupusor.java
---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):**  PaperSpigot

**Server Version (using `/ver`):** 1.15.2

**Comment by Zrips** [comment]
Fixed
