### ISSUE TITLE
Unknown Dimension Network Id 12

### ISSUE THREAD

**Issue by Jishrocks** [Zrips/CMI#2786]
Title Says it all, while using ProtocolSupport.

**Comment by Zrips** [comment]
And yet its not even close to being enough for figuring out why this happen.
Server version?
Any errors in console?
Which client version was used? 
Are you using multiworld plugin? 
Any additional information related to that would be nice too.

**Comment by Jishrocks** [comment]
Server Version 1.15.2
Errors : No
Client : 1.15.2
Only Multiverse

**Comment by therealatsuga** [comment]
We have the same problem, but network ID 13 was shown. Same client, no error, multiverse used, paper server. The weird thing about it: only team members were affected. We could not figure out the reason for this.

**Comment by Jishrocks** [comment]
Same here, only staff team members affected.

**Comment by Jishrocks** [comment]
Found the bug, its caused by CMI Skins

**Comment by J0schlZ** [comment]
So.. Why you don't tell us your solution?
@Jishrocks

**Comment by Jishrocks** [comment]
The solution was disable skins

**Comment by Getblock** [comment]
This is also an issue for me... I just updated from 8.6.18.6 to 8.6.19.9

The only plugin i have is multiverse 4.1.0
Server version is paperspigot 1.15.2

**Comment by Zrips** [comment]
should be resolved
