### ISSUE TITLE
ShowBeeHiveInformation it does not work

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#2788]
Version: Paper version git-Paper-102 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

CMI: 8.6.19.2

Unfortunately you cannot see how many bees are inside or what level the honey is. it always stays on: honey level 0/5 bees inside 0/3. Even if I put the beehives new, nothing changes, even if bees fly in or honey drips out

**Comment by thenullmatrix** [comment]
Same issue here.

**Comment by mrfloris** [comment]
Confirmed; zrips said this:

It's because of beehive, it wasn't included in the check. 

I suspect the next cmi build could have this included to complete it. 

Nests show up correctly for me though.

**Comment by Zrips** [comment]
Fixed
