### ISSUE TITLE
Glow GUI not customizable

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2793]
**Description of feature/improvement request:**

Can't change the GUI name, nor the item names/lore. Also it shows the attribute of +3 when on body, I think that should be hidden.

![image](https://user-images.githubusercontent.com/5664135/74371154-9ff30500-4dd8-11ea-9e02-8b6d672edf2f.png)

@Zrips

**Comment by Va1a** [comment]
how did you even get this gui? what's the command?

**Comment by CloudeLecaw** [comment]
glow (playerName) [true/false/color/gui]

so to open the GUI simple use  /cmi glow gui   in simplest case
