### ISSUE TITLE
TP command color codes buggy

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2795]
**Description of issue:**

Color codes are not applied when it splits on 2 lines, looks a bit bad in terms of design.
Also noticed the line ''Cancelled'' when you cancel a teleportation looks a bit basic, the only feedback message you get is ''Cancelled'', a better design would be ''Teleportation request has been cancelled''

![image](https://user-images.githubusercontent.com/5664135/74448981-2876b180-4e7c-11ea-8cb4-0789e662c93d.png)

**Comment by LogGits** [comment]
This is a minecraft json formatting thing. They dont carry colours over new lines. A solution would be to use `\n` at the end of your teleport message. This would result in the tick/cross being put on a new line with formatting.

**Comment by Sikatsu** [comment]
Other plugins don't have this issue, and if they had, they did fix it after I mentioned. sing \n is just not an optimal way, ever thought of different screen sizes? I can optimize it for mine, but how about for others?

Was hoping for a proper fix here as well, definitely since it's the core plugin on a server.

**Comment by Zrips** [comment]
@Sikatsu 
Should be fixed with next build

**Comment by Sikatsu** [comment]
Thanks!!
