### ISSUE TITLE
CustomAlias, message in console

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#28]
When a "CustomAlias" is used, a message appears on the console indicating that a command has been written that does not exist.

Sorry, bad english.

**Comment by LogGits** [comment]
By default cmi runs commands as the console. If you want to specify to run it as a player use `likePlayer!` in front of the alias. Unknown command message implies the alias has commands in it that aren't registered commands meaning the command doesn't exist. You could also post the alias from inside the custom alias yml file into the github if you are still having trouble with this 🙂

**Comment by LogGits** [comment]
I am assuming this is resolved, If you are still having this issues please reopen this.
