### ISSUE TITLE
Potion Type must not be null

### ISSUE THREAD

**Issue by Fiks75** [Zrips/CMI#2802]
When player write command give potion in console error

---

ERROR:
```
https://pastebin.com/piQrsmM6
```

CMI: 8.6.19.3 BungeeCord

Paper(102) 1.15.2-R0.1-SNAPSHOT 

Paper version git-Paper-102 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Should be fixed with next build
