### ISSUE TITLE
Custom mobheads 

### ISSUE THREAD

**Issue by thenullmatrix** [Zrips/CMI#2805]
**Description of issue:**
The Custom Mobheads .yml file overwrites changes at reload. I am trying to either markout or remove wither skeleton head drops due to some of our players are getting confused between the types. When I remove the lines in the file and save it stays removed until Cmi is reloaded then lines get replaced back into the file.

---

**Cmi Version (using`/cmi version`):** 
CMI ver 8.6.19.3
**Server Type (Spigot/Paperspigot/etc):** 
Spigot 1.15.2
**Server Version (using `/ver`):** 
Spigot-c574e08-708be69 (MC: 1.15.2)

**Comment by Zrips** [comment]
If you want to clear out possible head drops, set it to 
`    Heads: []`
