### ISSUE TITLE
CMIB Error

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#2807]
**Description of issue:**
Error on Waterfall

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/ddm5X3uB
```

**Cmi Version (using`/cmi version`):** 
CMI 8.6.19.3
CMIB 1.0.0.3
**Server Type (Spigot/Paperspigot/etc):** 
Waterfall, Paper
**Server Version (using `/ver`):** 
1.15.2

**Comment by Zrips** [comment]
Should get fixed with next version
