### ISSUE TITLE
Random Teleport kills

### ISSUE THREAD

**Issue by Va1a** [Zrips/CMI#2809]
**Description of issue:**
The /rt (random teleport) command sometimes results in player death. The chunks do not load fast enough resulting in the player actually falling through the world, instead of being suspended on the surface. They then end up dying. 

---

**Cmi Version (using`/cmi version`):** 
8.6.19.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper (Paperspigot)
**Server Version (using `/ver`):** 
Paper(105) 1.15.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Will try to force chunk loading before player gets teleported. Next update should have fix for this one and if it repeats, let me know.

**Comment by Va1a** [comment]
@Zrips this is still an issue as of version 8.6.19.5 
Just ran the command twice, both times I fell through the world...
