### ISSUE TITLE
Player's collision enable automatically when you become visible again.

### ISSUE THREAD

**Issue by pvvvo** [Zrips/CMI#2811]
When you do `/vanish` and then become visible again, the player's collision persist disabled unless you type `/playercollision`. It'd be nice if they were synchronized.

Need it just to improve automatization.

**Comment by thunderlight411** [comment]
it's already reported as a bug : https://github.com/Zrips/CMI/issues/2456

**Comment by Zrips** [comment]
Fix is coming out with today's update.
