### ISSUE TITLE
gamemode change when hit with a fishing rod (FishingHook) while the player is in vanish

### ISSUE THREAD

**Issue by thunderlight411** [Zrips/CMI#2814]
When a player is vanished and got caught with a fishing rod the gamemode of that player changes to spectator mode.
---
**Cmi Version (using`/cmi version`):** 
8.6.19.4
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):**  
git-Paper-112 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
You literally cant hook vanished player, tested on 1.15.2 server. This can be caused by another plugin and not by CMI
