### ISSUE TITLE
Bossbar compass messages when disabled

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#2817]
**Description of issue:**
When the boss bar compass is disabled in the config, if you type /togglecompass it still says "Boss bar compass got enabled/ disable"

---

---

**Cmi Version (using`/cmi version`):** 
8.6.19.5
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-112

**Comment by Zrips** [comment]
Will fix with next update
