### ISSUE TITLE
Sit Armorstand Bug

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#2818]
**Description of issue or feature request:**

If a player leave server while sitting, the armorstand will keep exist.

---

**Cmi Version (using`/cmi version`):** 
8.6.19.4
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.15.2

**Comment by Zrips** [comment]
Will make some adjustments which should minimize or eliminate from this happening again
