### ISSUE TITLE
The ability to create several hover lines in custom text

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#2819]
**Description of feature/improvement request:**

Basically the ability to for example do \n in a <H></H>. You can currently do this, but it also pastes the hover msg onto the next line of the customtext.

---
### Detailed explanation of what it should do, when and in what situation: ###
if you added <H>Test \n Test2</H> to a customtext, when hovering over the text it should should Test on line 1 and Test2 on line2, without pasting Test2</H> onto the next line of the custom text.

### Basic explanation as to why this feature is needed and/or useful to have: ###
This feature would be useful to have to create custom texts with several lines of hover messages.

**Comment by Zrips** [comment]
You can do this already with something like 
/cmi ctellraw Zrips <T>Line 1\nLine 2 of line 1\n</T><H>Hover1</H><Next><T>Line 3</T><H>Hover 2</H>
Same format applies for custom text.
