### ISSUE TITLE
cant using asFakeOp! in Interactive Command

### ISSUE THREAD

**Issue by NightPrimez** [Zrips/CMI#2821]
**Description of issue:**
Edited:

i cant using command run by player without permission op (asFakeOp!)
so i just test execute command by "asFakeOp! say test"

it's showing " [CMIFakeOperator] test"

so.. i need to make PLAYER run command isnt CMIFAKEOPERATOR

if can do this.. what should i do
---

**Cmi Version (using`/cmi version`):** 
8.6.19.5

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
• 1.14.4
• 1.15.2

(i have 2 servers and difference versions)

**Comment by Zrips** [comment]
This is not how fakeOp works. When you are using asFakeOp! variable, then fake player which is OP will perform that command. This is why you got that feedback message. If you want to give access to something like that you have couple options here, first one would be to perform command asConsole! and add [playerName], which can be not as usefull in your situation, another option would be to use bypass permission variable, like "bperm:some.test.permission?#! cmi fly" so in this case if player has permission node as some.test.permission then he can perform this one. Tho this will only work on CMI commands.
