### ISSUE TITLE
Missing bossbar using crossbow with firerockets

### ISSUE THREAD

**Issue by FaMa91** [Zrips/CMI#2822]
Hi,
using the crossbow to launch explosive firerockets deals damage to entities but the bossbar doesn't show up.

Regards,
FaMa

**Cmi Version (using`/cmi version`):** 8.6.19.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.14.4

**Comment by Insprill** [comment]
Try using the latest version: https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/updates

**Comment by Zrips** [comment]
Can't really be fixed currently as shoot firework doesn't include shooters information, while every other projectile does.
