### ISSUE TITLE
[Feature Request] AFK Players disable Mob Spawning

### ISSUE THREAD

**Issue by MrAmos123** [Zrips/CMI#2827]
**Description of feature/improvement request:**
Prevent mobs from spawning around set AFK players. This would disincentivise AFK Mob Farming.

---
### Detailed explanation of what it should do, when and in what situation: ###
Prevent mob spawning from natural spawns or spawners when the player is set as AFK.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Disincentivising AFK Farming. I have a 40% AFK/Playtime ratio and this would considerably lower the AFK population. 

Let me know if you need to know anything else.

**Comment by Zrips** [comment]
Will add with next update
