### ISSUE TITLE
FirstJoinMessage not firing.

### ISSUE THREAD

**Issue by glorying16** [Zrips/CMI#2829]
The FirstJoinMessage is not firing for new players. It is enabled in the config, and the custom message is set in the locale. Im honestly not sure at what point this stopped, but players have said they noticed it being gone for a while. I do use custom join and leave messages through chat control, but they dont have a first join message option, so I cant see it being a conflict there. There are no errors, or messages in console logs.

---

**Cmi Version (using`/cmi version`):** 8.6.19.5

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.15.2-R0.1- SNAPSHOT

**Relevant plugins (Delete if this isn't needed):** Chat Control Pro ver. 8.6.4

**Comment by Zrips** [comment]
You might have disabled customMessages module in your modules.yml file. Will move this even listener to another class to avoid this issue in future.
