### ISSUE TITLE
/tell not includable in socialspy?

### ISSUE THREAD

**Issue by ScuroK** [Zrips/CMI#283]
/tell is not a cmi command but i want to include it in socialspy. essentials had a config option to manualle add commands to socialspy.

is this possible in cmi? i only saw the command spy feature but i dont want to mix those features.
if not possible yet, could you please add an option to include other commands in socialspy please?

**Comment by tmellen** [comment]
why not use CMI's built in tell commands? Set up an alias for "tell" to run "cmi msg $1-"... Whenever someone does "/tell bob Hi" you'll see it in CMI, and bob will get the msg.

**Comment by ScuroK** [comment]
right! thx alot :D
