### ISSUE TITLE
Custom recipe bug

### ISSUE THREAD

**Issue by pvvvo** [Zrips/CMI#2830]
**Description of issue: When I create a custom recipe that for example, gives you 1 diamond per 64 planks it doesn't work, and it only put 1 planks instead of 64.**

[Video](https://youtu.be/LJB6fEAUBAc)

**Cmi Version (using`/cmi version`): 8.6.19.5 BungeeCord** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`): Paper(243) 1.14.4-R0.1-SNAPSHOT**

**Comment by Zrips** [comment]
CMI uses vanilla recipe engine which means that we can only utilize 1 variable for recipe: material name. It doesn't support amount, you can put multiple same ingredients into separate fields, but you cant have one field with more than 1 as ingredient. This would require complete rewrite of recipe handling engine.
