### ISSUE TITLE
CMI bungee kicks people server B when server A restarts

### ISSUE THREAD

**Issue by trickman325** [Zrips/CMI#2833]
When you restart one server connected through bungee it kicks people off the other servers.
this only happens when bungee is enabled in the config. 
if you disable it on the server, restarting the other servers leave players where they are and does not kick them.

There is no error i console when this happens

CMI version:
8.6.19.5 bungeeCord
CMIB Version:
1.0.0.4

paper 1.15.2
Paper(118) 1.15.2-R0.1-SNAPSHOT

**Comment by trickman325** [comment]
@Zrips

**Comment by Zrips** [comment]
Looking into it

**Comment by Zrips** [comment]
Using latest BungeeCord, can't reproduce the issue. Are we talking about /reload or about full server restart? Some more information whats going on and maybe message player gets when he gets kicked would be nice to have in trying to figure out what caused this. And did you tested this one on some test enrivment where you could reproduce this issue constantly? As it might be some strange behavior due to spigot configuration i dont have on my test machine.

**Comment by trickman325** [comment]
@Zrips A full server restart.
it only happens with bungee enabled in config :/
Most of the time its players connected on my hub being kicked when the other servers are restarted.
this is the error players get sent when it happens.
![kick error](https://user-images.githubusercontent.com/58171146/75453721-72a57a00-59c8-11ea-9af6-1db604cfad54.JPG)

**Comment by Zrips** [comment]
Do you have CMIB plugin on your bungee server?

**Comment by trickman325** [comment]
Yes, I have it on my proxy 
@Zrips

**Comment by trickman325** [comment]
Any advancement?? @Zrips

**Comment by PryPurity** [comment]
I actually have never had this problem before, and I am using the latest of everything...

**Comment by Zrips** [comment]
@trickman325 
This checked it, no idea why its doing what its doing. This can be an issue with multiple plugins interacting with each other and not a direct result of CMI. Without you fully testing it by removing every plugin possible from both servers and bungeecord and checking if issue still persists, we cant know if this issue actually originates from CMI or this is only a result of another plugin interfering with something what CMI does. At this point i have no idea as i cant reproduce it with my settup and as other doesnt have this issue ether, this will mean that your specific config setup and specific plugins might be the cause. Without knowing which ones exactly i cant move any further then this.I cant fix something i cant reproduce as issue.
