### ISSUE TITLE
Nickname sync

### ISSUE THREAD

**Issue by Callial** [Zrips/CMI#2834]
**Question: **
So we have three servers hooked together with bungee, and we have global chat working. Now we just want a way to sync nicknames across those servers without syncing inventories or other server-specific things. Someone suggested MySQL but the data stored in the SQL tables includes inventories and player locations. Currently, we have each server setup with its own table in the MySQL database but, the nicknames don't sync as they are stored in different tables for each server. Are we just overthinking things?

**Comment by Zrips** [comment]
This is on a todo list. Currently, we don't have cross-server sync feature and it's requiring more work to be done to have it working in a way it would be usable. So in short, we cant sync them currently but it might be possible in the future.

**Comment by Callial** [comment]
What about for punishments, like banning and muting, or would those fall under the same category?
