### ISSUE TITLE
cmi lag

### ISSUE THREAD

**Issue by arts7493** [Zrips/CMI#2837]
**Description of issue:**

![image](https://user-images.githubusercontent.com/3336813/75341708-588c6e80-58d8-11ea-903a-8d1db233f970.png)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
lastest
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
1.15.2
**Relevant plugins (Delete if this isn't needed):**

**Comment by Insprill** [comment]
1) "latest" doesn't help, Zrips needs an actual version as CMI is always being updated.
2) Zrips also needs an exact server version, not just 1.15.2. So for example, Paper-120.
3) That usage is fine. Go into the modules.yml file and disable any features you're _not_ using to reduce the total performance impact.

**Comment by Zrips** [comment]
@arts7493 
repost this issue correctly, with included link to timings. As i cant see any issue with your current ones. There is some what jump on warmup management, but its one time use, so its not relevant as i cant even know what command was performed to cause that.
