### ISSUE TITLE
aliaseditor breaking commands in bossbarmsg when going to edit alias

### ISSUE THREAD

**Issue by Callial** [Zrips/CMI#2839]
**Description of issue:**

When editing a command alias for a bossbarmsg, http://prntscr.com/r86gip when you click to edit it and paste it into the chatbox, it adds slashes "/" that break the command. Here is what happens when I click to paste it to edit.

`cmi bossbarmsg all Server Restarting in [autoTimeLeft]! -cmd:\"cmi sendall hub;;restart\" -sec:-60 -c:red`

---

**Cmi Version 8.6.19.6** 

**Server: Spigot** 

**Server Version (using `/ver`): http://prntscr.com/r86irj**

**Comment by Zrips** [comment]
Will get fixed with next update
