### ISSUE TITLE
Permission to Create Elevator Sign,

### ISSUE THREAD

**Issue by RustyDagger** [Zrips/CMI#284]
Description of issue or feature request:

Would be really useful to have a separate permission node to create the elevator sign than to use it. That way staff can make them and players can only use them, Currently we can't stop them making them at all.

**Comment by Rukes** [comment]
Yea, its good idea have permissions `cmi.elevator.use` and `cmi.elevator.create`.
Another enhancement can be, than if I click sign it will teleport me exactly to second block in frond of sign. Would be nice if teleportation change only Y coord. Cuz if that second block is air it will teleport not exactly at sign Y coord (without fly).

Explain images
[Clicking sign](http://prntscr.com/j8v68y), [teleported](http://prntscr.com/j8v6j3).

**Comment by LogGits** [comment]
This has been added. `cmi.elevator.use` is now the permission for using the elevator sign and `cmi.elevator.create` is now used for creating an elevator sign.

This will be added in the next update along with keeping the same x,z,yaw,pitch values.
