### ISSUE TITLE
/kitpreview not working

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#2840]
**Description of issue:**
Kit preview isn't working, the alias or the normal command. Just says "Can't find kit by this name"

---

---

**Cmi Version (using`/cmi version`):** 
8.6.19.6
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper-120 1.15.2

**Comment by Zrips** [comment]
you actually need to provide kit name you want to preview. In general you have option to preview kit while you have kit GUI open and then you right click it. /kitpreview is only an alias from more compex **/cmi kit [kitName] -preview** command.
