### ISSUE TITLE
Equationint and maxperm placeholder

### ISSUE THREAD

**Issue by banit** [Zrips/CMI#2845]
As it seems the maxperm or equationint placeholder do not function correctly with some? or all not cmi permissions

ptarget:$1! lp user $1 permission set backpack.size.%cmi_equationint_{cmi_user_maxperm_backpack.size_2}+1%

will not set the permission "backpack.size.3" but it will set "backpack.size.%cmi_equationint_{cmi_user_maxperm_backpack.size_2}+1%"

cmi 8.19.6
paper 1.15.2-112
luck perms 5.0.72

**Comment by Zrips** [comment]
Tested your command by creating custom alias with it, all works as intended and players getting increased backpack permission node with each usage. How did you exactly performed this specialized command?

**Comment by banit** [comment]
I could not get it to work with Custom Alias, but tried with kit and it worked
