### ISSUE TITLE
[crashed server ->] Unhandled exception occurred in onPacketSending(PacketEvent) for CMI

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#2847]
**Description of issue:**
Unclaimed some chunks in factions then did /f map, and then CMI spit this out and crashed my server

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/iEfLd9z7
```

---

**Cmi Version (using`/cmi version`):** 
8.6.19.6
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper-121 1.15.2

**Comment by Zrips** [comment]
Do you have enabled increased view range or preview mode? As only those two uses this packet

**Comment by Insprill** [comment]
pretty sure increased view range was on for me

**Comment by Zrips** [comment]
Will be disabling for time being increased view range, as this one seems to require complete rework for new minecraft versions.
