### ISSUE TITLE
Request: DiscordSRV support

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#285]
If it is not too much trouble, could you add support for DiscordSRV integration

**Comment by Zrips** [comment]
What exactly is this support should include?

**Comment by CypherPhyre** [comment]
DiscordSRV integration support would allow server "owner's" to connect a Discord Bot to MC throw the chat channels. Providing 2-way chat between the MC server and Discord server. Also allowing for monitoring of MC console output on Discord. Limited MC console commands can be issued through Discord, such as Tps, Stop, List. You would need to get in contact with @Scarsz regarding the CMI API on account that CMI is premium. Here is a link to the DiscordSRV discord https://discord.gg/rRKBec also here is the Spigot link for DiscordSRV https://www.spigotmc.org/resources/discordsrv.18494/

**Comment by CypherPhyre** [comment]
CMI has been mentioned many times on the DiscordSRV discord by others wanting this integration. It would allow a discord Bot to send 2-way chat messages on specified chat channels set up in a config.

**Comment by Zrips** [comment]
Will push initial version. Never used it, so for now i have no clue what should work and how exactly. But for now you will have tools to send messages from discord and to discord.

**Comment by CypherPhyre** [comment]
Thanks. One step closer to being a true All-In-One

**Comment by CypherPhyre** [comment]
All seems to be working. No longer need another chat plugin for this integration. Please contact @Scarsz when you can about the integration so that they can work out the official support on their end as well. Thanks again
