### ISSUE TITLE
Unknown Dimension Network Id 12

### ISSUE THREAD

**Issue by Getblock** [Zrips/CMI#2850]
**Description of issue:**
I recently updated from CMI8.6.18.6 to CMI8.6.19.6.

After the update, some players on the server including me could not login anymore since we kept getting that error.

No error being thrown in console

I just downgraded to my old version for everyone to be able to play without any issues.
**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/43926892/75537123-6a455180-5a51-11ea-990f-8f7a6174f103.png)

**Relevant plugins (Delete if this isn't needed):** Multiverserse Core https://ci.onarandombox.com/job/Multiverse-Core/

**Comment by Zrips** [comment]
This should have been resolved with 8.6.19.7 version, so update to latest 8.6.19.11 version
