### ISSUE TITLE
[Bug Report] After sitting on the bed, you can sit in the air by breaking the bed. - ★

### ISSUE THREAD

**Issue by geumu** [Zrips/CMI#2852]
**Bukkit**: Paperspigot 1.13.2
**Plugin**: CMI 8.6.19.5
**Bug severity**: ★
**Explanation**: After sitting on the bed, you can sit in the air by breaking the bed.
**Video**: https://youtu.be/K1YQVswGqHg

**Comment by Zrips** [comment]
From when beds are counted as chairs? As i cant remember adding anything like this into CMI

**Comment by pvvvo** [comment]
@Zrips /sit on a bed and breaking it.

**Comment by Zrips** [comment]
Will be fixed with next build
