### ISSUE TITLE
Vanish Messages/LANG Files

### ISSUE THREAD

**Issue by ZEROOblivious** [Zrips/CMI#2853]
In the YML of Locale_EN.yml for the Vanish Section

  vanish:
    help:
      info: '&eVanish player'
      args: (playerName/list) (on/off)
    info:
      **vanished: 'You are now Vanished'
      unvanish: 'You became visible'**
      targetVanished: '&6[playerDisplayName] &ehave vanished'
      targetUnvanish: '&6[playerDisplayName] &ebecame visible'
      list: '&e[place]. &6[playerDisplayName] &e(&6[offon]&e)'
      noVanished: '&eThere are no vanished players'
++++++++++++
The Bolded Section does not allow the normal [playerName] to display as its self telling the player that they are now "Vanished" 
![image](https://user-images.githubusercontent.com/32251194/75564344-f89de100-5a19-11ea-8757-b9dd94822ab0.png)
I've also tried sender name since the user is the one performing the command 
![image](https://user-images.githubusercontent.com/32251194/75564398-0c494780-5a1a-11ea-86d4-b64380be0b93.png)

---
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

  vanish:
    help:
      info: '&eVanish player'
      args: (playerName/list) (on/off)
    info:
      vanished: '[playerDisplayName]&a is now Vanished'
      unvanish: '[playerDisplayName]&a Became Visible'
      targetVanished: '&6[playerDisplayName] &ehave vanished'
      targetUnvanish: '&6[playerDisplayName] &ebecame visible'
      list: '&e[place]. &6[playerDisplayName] &e(&6[offon]&e)'
      noVanished: '&eThere are no vanished players'

---

**Cmi Version (using`/cmi version`):** 
8.6.19.6
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
git-Paper-241 (MC: 1.14.4)

**Comment by Zrips** [comment]
Wil be fixed with next version.
