### ISSUE TITLE
Can I add a user's head from the hologram?

### ISSUE THREAD

**Issue by PhracKko** [Zrips/CMI#2854]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###

The various user guides and systems require a number of milestones to attract the user's attention.

Among them, I really liked the hologram item display.
I want to improve accessibility so that I can right-click it to display the menu to the user.

But ICON:%iteminhand% is literally changed by the hands of the user.
It's not actually a single user's head...

But it's a perfect plug-in! I'm sorry for pursuing perfection...

Thank you.

### Basic explanation as to why this feature is needed and/or useful to have: ###

I want to fix the head of the user to ICON:[] of the holographic system.

bellow is my youtube video URL.

https://youtu.be/5XhfWh2L29Y

**Comment by Zrips** [comment]
Short answer: **ICON:head:Zrips**
tho this will only work from 1.10 and up, due to strange handling of floating icons in older versions.

**Comment by PhracKko** [comment]
> 짧은 대답 : **ICON : head : Zrips**
> 이전 버전의 플로팅 아이콘을 이상하게 처리하기 때문에 1.10 이상에서만 작동합니다.
> 또는 **ICON : head : % cmi_user_name %** 으로 훨씬 더 **화려할** 수 있습니다 **.**

amazing...

**Comment by PhracKko** [comment]
> Short answer: **ICON:head:Zrips**
> tho this will only work from 1.10 and up, due to strange handling of floating icons in older versions.
> Or you can be even more fancy with **ICON:head:%cmi_user_name%**

Amazing...
