### ISSUE TITLE
Can't Tab Names Properly

### ISSUE THREAD

**Issue by Addfire** [Zrips/CMI#2855]
As the tittle says, you **can't tab player names properly at all** when trying to talk to them. It'll default to whatever order it wants so players are forced to type out a players name.
**_https://gyazo.com/05bd8ddd3aefc27c665c1f8ac1a97808_**

**Paper Spigot:** 

**1.8.8** 

Please keep in mind that this happens on **1.8.8 and on 1.14.4** so I'm certain this most likely happens on every version (At least Paper Spigot wise). This has been **happening for months** (since day one of purchasing).

**Comment by Zrips** [comment]
Just tested on 1.8.8, all seams to be working as intended. Did you tested this on a clean server without any other plugin to rule out possible issue with compatibility with another plugin? And are we talking about /msg command which is alias which was enabled in alias.yml file?

**Comment by Zrips** [comment]
And maybe you could give example how tab complete looks like in general for you or its completely blank?

**Comment by LogGits** [comment]
As there was no response i am assuming this was resolved. If you are still having this issue could you open a new ticket that addresses the Zrips responses (will probably make it easier for him to investigate - saving time)
