### ISSUE TITLE
Server crashes instantly when I join

### ISSUE THREAD

**Issue by therealatsuga** [Zrips/CMI#2857]
**Description of issue:**
See title. 

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://codeshare.io/ayRnZ0 
```

**Cmi Version (using`/cmi version`):** 
8.6.19.6 (but also occured with 8.6.19.5

**Server Type (Spigot/Paperspigot/etc):** 
Paper 
**Server Version (using `/ver`):** 
1.15.2 ver 121
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Should be up and running with next version
