### ISSUE TITLE
Vanish Features

### ISSUE THREAD

**Issue by ZEROOblivious** [Zrips/CMI#2859]
Auto-Join on Vanish: When you're first setting up vanish, you log-in not in vanish. There's no auto-join on vanish. If you have this permission node or configuration, this would be nice. 

---
When you log-in the Plugin instantly puts you in Vanish if you're part of the permission node or Configuration. 

### Basic explanation as to why this feature is needed and/or useful to have: ###
To log-in vanished when you first get access to vanish. 
When giving someone the permission node when offline, they login not hidden.

**Comment by Zrips** [comment]
You can simply perform **/cmi vanish (playerName)** to put that player in vanish mode even if he is offline and even if he doesn't have permission to this command, after that he will join in vanish mode.
