### ISSUE TITLE
Error when loading CMI Ranks 

### ISSUE THREAD

**Issue by Yuliansky** [Zrips/CMI#286]
Description of issue or feature request:

ERROR:
```
####################
## https://i.imgur.com/YrPd6pv.png ##
####################
```

Cmi Version (using`/cmi version`): **7.6.10.1**
Server Type (Spigot/Paperspigot/etc): **Spigot**
Server Version (using `/ver`): **1.8.8-R0.1**

Thank you in advance,
Yulian

**Comment by MCTyler** [comment]
(A little advice to receive better support)
Please don't post a Pic of error. Copy and paste the error from the console into Space provided above.

**Comment by LogGits** [comment]
Will be fixed in the next build.
