### ISSUE TITLE
/tpa SelfPlayerName TargetPlayerName can force teleport TargetPlayer to current position

### ISSUE THREAD

**Issue by tianji1993** [Zrips/CMI#2860]
**Description of issue:**
/tpa SelfPlayerName TargetPlayerName 
This command can force teleport TargetPlayer to current position.
Let's say my player name is **Tianji**, and I build a trap, then I want to kill another player called **Worthykazoo**,  so I just send:
/tpa Tianji Worthykazoo
and then I got a notice "Worthykazoo send a teleport request [!] [X]"
then I click [!], player Worthykazoo teleported to my location, trap active, player Worthykazoo get killed without any agrees on his side.

---

**Cmi Version (using`/cmi version`):** 
CMI version: 8.6.19.6
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper(62) 1.15.1-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Good catch, will fix this with next build
