### ISSUE TITLE
Bar display error when invisible

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#2861]
Cmi:8.6.19.7
Paperversion: Paper version git-Paper-121 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

If you are invisible on the server and log out, then log back into the game, there is always a bar ad that you are invisible. They collect

![2020-02-29_20 42 21](https://user-images.githubusercontent.com/35557302/75614034-7e15b400-5b34-11ea-84dd-822bf550deba.png)

If you then end invisibility, the ads will not go away

**Comment by pvvvo** [comment]
Same here, if I hit something no matter if i am visible or not, the bossbar doesn't dissapear anymore, even if I rejoin.

**Comment by Zrips** [comment]
Should be running correctly with latest build
