### ISSUE TITLE
Ranking up automatically without setting it up

### ISSUE THREAD

**Issue by pvvvo** [Zrips/CMI#2862]
I created a rank with autorankup set to true, then I deleted the autorankup with the purpose to rank up with the command / rankup, but I'm still ranking up automatically.

**Cmi Version (using`/cmi version`) 8.6.19.7 BungeeCord:** 

**Server Type (Spigot/Paperspigot/etc): Papersigot** 

**Server Version (using `/ver`): Paper(243) 1.14.4-R0.1-SNAPSHOT**

**Comment by Zrips** [comment]
You might need to perform full restart for those changes to kick in, but will have a look if i can update code to avoid need to perform such action and basic reload would be enough.
