### ISSUE TITLE
Tppos does not work on usernames with only numbers

### ISSUE THREAD

**Issue by delbertina** [Zrips/CMI#2864]
**Description of issue:**
I'm using an IC that teleports players somewhere using /tppos [playerName] # # # and whenever a player who's name only has numbers tries to use it it does not work. Prints in console `Can't find player with this name!`. Usually the player leaves when the IC doesn't work for them so I dont have a way of testing other than observing this happen for 2 different players. `2097` today and `00001001` over a year ago. 

---

**Cmi Version (using`/cmi version`):** 
8.6.19.5
**Server Type (Spigot/Paperspigot/etc):** 
Paper Spigot
**Server Version (using `/ver`):** 
1.15.2 Paper build #118

**Comment by Zrips** [comment]
Due to the fact that you might be entering coordinates and not player name with that first variable, we will need to utilize -p:[name] format, so like /**cmi tppos -p:2564 123 63 56 world**
