### ISSUE TITLE
Paper Money

### ISSUE THREAD

**Issue by ZEROOblivious** [Zrips/CMI#2865]
Paper Money with the CMI Economy. Allows people to trade paper money for roleplay/shop purposes.

---
Command would be /withdraw to withdraw your balance onto a piece of paper. You would right-click the paper to deposit the money back into your account/vault balance. 

Its just an additional idea that players can trade their money without doing /money pay etc. Its more for roleplay purposes.

**Comment by banit** [comment]
you have Cheque's in Cmi   /cheque Amount to create a paper with this worth

**Comment by ZEROOblivious** [comment]
Never knew this. Thank you, ill just set up a custom alias for this.
