### ISSUE TITLE
Ability to change warp GUI format

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#2867]
**Description of feature/improvement request:**
The ability to change the warp name/lore in the locale files for the warp GUI.

---
### Detailed explanation of what it should do, when and in what situation: ###
A place in the locale files where you can edit how the warp name & warp lore in the warp GUI. Currently you can only change the warp GUI title. You can currently add a custom item to the warp which has custom lore/name, but what I am asking for is the ability to edit the auto lore/name of the warps.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Useful to have so you dont need to change every warp to have a custom item and having  to disable auto lore if you want to have a custom name on the item.

**Comment by Zrips** [comment]
Next update
