### ISSUE TITLE
[Suggestion] Additional control over CMI WARPS

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2868]
This is a community created list of suggestions, based on the things I've read on the forums / discord or from private conversations, etc. 

Personally, I'd love to see an extended version of the warps feature within CMI, so here is a summary of items that's hopefully possible for the (near) future. 

`/cmi editwarp <name> <new_name>`
A quick and easy way to fix a potential typing error, of course, it must check if the new_name isn't already in use to remain unique.

`/cmi editwarp <name> (name change in the gui)`
When we either middle click in /warps or do /cmi editwarp name and the gui opens, it would be nice if we could also rename the warp from within here. Instead of having to remove the warp first, and re-add it. Potentially forgetting set permissions, icons, or slot locations. etc. 

`Ability to add color to warp names`
I see a lot of requests for warp names to have colors, if not only to help organize and group, but also to help make a menu of names match the 'theme' of a server. A lot of people seem to just want to remove `&o` to get rid of italics for example.

`Ability to group warps`
We currently use different pages to organize the warps gui menu, we have first page as server warps, second and third as player warps, and then events after that, etc. 
It would be nice if we create a warp we can give it a group name, if the group doesn't exist; add it as a new one, .. otherwise append it to that groupl
For example: `/cmi setwarp <name> -g:groupname` `/cmi setwarp spawn -g:worlds` or `/cmi setwarp bobby -g:players`
This would allow us to do the next suggestion:

`Ability to open the warps gui for a group`
It currently is a paginated view of 'global' warps, everything.. this could easily be hundreds on busy bungee servers, it would be nice if there's groups for server stuff, player stuff, event stuff, mini game stuff, that we could open the gui from our own menu (say bossShopPro) to just the stuff we want. We could have buttons for all | server | players | events | minigames, player clicks for example on the events one and it runs the command:
`/cmi warps events`
if they would click or type on minigames or whatever group, it will be opening the gui with pagination of just those grouped items as previously suggested/setup.
`/cmi warps minigames`

`Ability to add titles to menubar, so we could at least paginate with titles?`
Whatever comfortable way this could be, but the ability to call page 1, `server warps`, and page 2: `/warps players`, and page 3 `&6 orange warps` etc. Grouping as mentioned above, would could use the title of the group for this.

'More control over which lores to show, and/or to customize it`
It would be rather fantastic that besides showing or auto generating lores, that we could turn off default lores, and using `/cmi editwarp` that we could set our own lores. 
`/cmi editwarp <warp> -lore:Everything behind it will be \n a lore name \n over &63&r lines`
Or a typical green `+` icon that when we click, we can add another line of lore.

** If anybody has any further suggestions, please post them, or at the least if you agree, give this a thumbsup to help upvote the suggestion(s). **

**Comment by mrfloris** [comment]
Additionally; 
https://github.com/Zrips/CMI/issues/2867
(we posted at the same time haha)

**Comment by cryoten** [comment]
I'd like players to be able to edit their own warps instead of all warps.

The two permissions would be:
`cmi.command.editwarp`
`cmi.command.editwarp.bypass`

Additionally, it'd be nice to control what players can edit in their own warps. Regular players shouldn't be able to have access to `Requires permission to use` and `Show without permission`, and perhaps we may want to disable players editing the warp slot.

**Comment by Zrips** [comment]
More or less everything got/gets implemented.
