### ISSUE TITLE
[Suggestion] /cmi sethome <name> block|int

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2869]
I understand that with 1.15.2 the ability to get data from unloaded chunks is in the way of properly showing a recognizable and specific block/material, and has issues because of this. Fine :) So be it. 

What would be rather cool is the /sethome to work as it does right now, but if we type `block` behind it, that it checks what block we're standing on, and uses that as the material for the player's home in /homes.

I am standing on grass, and i type: `/sethome base`, it will just be how it was yesterday ..
But in a (near?) future version, if i type: `/sethome base block`, it will see that i am standing on `grass_block` and stores that value. Now, in the future, when i type: /homes, i can see the grass block and remember it's my base. It doesn't have to remote pull the data from unloaded chunk. 
And my /homes isn't a random mess of carpet and glass and wool blocks. 

Any entry that's "old" and doesn't have block set, is null, so the old randomized block can show for that slot. 

Additionally, if it's not block, but integer value, it could represent the slot in /homes. Allowing players to set their most used homes to a specific slot?

`/cmi sethome base 25`
( i understand this is therefor limited to just page 1 .. , but that's the most used page anyway )

**Comment by Zrips** [comment]
Next version
