### ISSUE TITLE
Command /cmi money take  not working with percents.

### ISSUE THREAD

**Issue by Eiple** [Zrips/CMI#2870]
Hello, as the tittle says the command  /cmi money take  not working with percents.
for example if I use /cmi money take 10% it only takes 10 from player not 10%. 
I have a server on paper 1.15.2 plus CMI version 8.6.19.9.

**Comment by Zrips** [comment]
Will get fixed with next version

**Comment by Eiple** [comment]
Getting this console error when using the command on last update 
Version: 8.6.20.0
[https://prnt.sc/rb4gc8](url)

Command works, console prints this error.
