### ISSUE TITLE
Language file place holder not working cross server

### ISSUE THREAD

**Issue by trickman325** [Zrips/CMI#2871]
the "[servername]" placeholder for the language file only works for the players on the same server with you. other bungee servers that can see the message get the placeholder in full not the server name that the msg is being Sent from.

So when having it in staffmsg otherservers see:
 “[servername] trickman325> hello”
But people on the same server see:
“[Hub] trickman325> hello”

Language files for all servers being used as the same.

---

CMI version:
8.6.19.5 bungeeCord
CMIB Version:
1.0.0.4

paper 1.15.2
Paper(118) 1.15.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Should get fixed with next version

**Comment by trickman325** [comment]
@Zrips 
The new update isnt correct, it says whatever server the receiver is on not the server which the sender is on.
