### ISSUE TITLE
Be able to use Hoveritems even with ClickHoverMessages is set to false

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#2873]
**Description of issue:**
If I have enabled:
  ClickHoverMessages: true
   HoverItems: true

The DiscordSRV will not display chat in discord becouse of thoes 2 settings is there a way to enable howevereitems and still be able to use chat in discord?. I don't really want to chose one over another,
I did see plugins that had %item% working even with discordSRV enabled etc. So it should also work in CMI
---

---

**Cmi Version (using`/cmi version`):** 
1.7.3-B
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.15.2
**Relevant plugins (Delete if this isn't needed):**
DiscordSRV 1.18.4

**Comment by PryPurity** [comment]
This is a feature request, not a bug report.

**Comment by arturek1666** [comment]
I would not say it's a feature request as this feature already exists, it just don't work when specific settings are turned on to make discordSRV work. So it's more like an issue then feature xD

**Comment by BurakDorman** [comment]
DiscordSRV takes "chat messages that sent by players" to send over the Discord.
The way of showing a message changes when you enable hover messages. When enabled, player's chat message is cancelled and another raw message is shown by the console with player's prefix, name etc.

**Comment by Zrips** [comment]
Test out new version which should work properly with discord and hover over messages
