### ISSUE TITLE
/balance reveals vanished users

### ISSUE THREAD

**Issue by e101stella** [Zrips/CMI#2875]
**Description of issue:**

---

Currently, players can do /cmi balance (partial user name) to determine if staff are joined but vanished.

For example say I wanted to check if Zrips was online, I would do /cmi balance zr 
If Zrips is online it tells me the balance, if not I get a message saying "Can't find player with this name!"

Been using SuperVanish for the vanish plugin rather than CMI Vanish module

---
**Cmi Version:** 8.6.19.5

**Server Type:** Paper 118

**Server Version:** 1.15.2

**Relevant Plugins:** Vault, ProtocolLib, SuperVanish

**Comment by Zrips** [comment]
Ok, seams that figure out a solution for this one and it should apply for the majority of commands. Should we working with next version as expected.
