### ISSUE TITLE
could you add an automatic rewrite / sethome function.

### ISSUE THREAD

**Issue by Denias3** [Zrips/CMI#2876]
**Description of feature/improvement request:**

Hello, could you add an automatic rewrite / sethome function.
For example, I have one point at home with the name "Home", and I want to change it to another place with the same name, but I do not want to delete the name of the home.
Or if this function is, could you tell me how to enable it?

**Comment by pvvvo** [comment]
It is already possible: `cmi.command.sethome.overwrite – Allows to overwrite existing home location`

**Comment by Zrips** [comment]
**/cmi checkperm home** third entry
So its already possible, just as @pvvvo pointed out. Just try to remember **/cmi checkperm**,  **/cmi checkcommand** and **/cmi placeholders** as those can give you quite allot of information about existing features
