### ISSUE TITLE
Thread lock and crash

### ISSUE THREAD

**Issue by Drc-DEV** [Zrips/CMI#2878]
**Description of issue:**

Can't replicate this, but it always happens when people do /msg to an offline player which has logged out just a couple of seconds before. 

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/Pu605G5b
```
---

**Cmi Version (using`/cmi version`):**  v8.6.19.10

**Server Type (Spigot/Paperspigot/etc):** Paper version git-Paper-122 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Server Version (using `/ver`):** server version 1.15.2

**Comment by Drc-DEV** [comment]
Example of how this happens usually:

- Player1 logs out
- Player2 executes: /msg Player1 sometext
- Crash

**Comment by Drc-DEV** [comment]
Another crash log: https://pastebin.com/ba7URw9N

**Comment by Zrips** [comment]
Will issue a fix with the next version, so it should no longer be an issue

**Comment by Drc-DEV** [comment]
@Zrips another crash, this time triggered by a /tp command with a wrong name as an argument,
in the log the correct name would be MrKopHe, while the name performed in the command is mrkop

https://pastebin.com/mMNSZLzs

**Comment by Drc-DEV** [comment]
This last crash was on CMI 8.6.20.2 with the same paperspigot version

**Comment by Drc-DEV** [comment]
I think something's wrong in the getUser call from CMI that triggers that crash.
