### ISSUE TITLE
Balances over 10 million getting displayed as 1.000E7

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#2879]
**Description of issue:**
When someone has over 10 million instead of it getting displayed as 10.000.000 it gets displayed as 1.000E7.

---

**Cmi Version (using`/cmi version`):**  8.6.19.9

**Server Type (Spigot/Paperspigot/etc):**  Paper-121

**Server Version (using `/ver`):** 1.15.2

**Comment by Zrips** [comment]
Which economy system are you using? Because if it's not CMI (which seams to be the case), then it will only use what your economy plugin returns in formated format. CMI doesn't have issues showing up balances up to 92 000 000 000 000 000

**Comment by DrakePork** [comment]
The economy plugin I'm using is CMI.

**Comment by Zrips** [comment]
Then try setting lines in config file to these
`    MoneyFormat: '###,###.00'`

**Comment by DrakePork** [comment]
Ah now it works. Seems like if yoy have
`MoneyFormat: '###.###,00'` it displays numbers above 10 million as 1.000E7

**Comment by Zrips** [comment]
Its because you have an incorrect format. if you cant to replace . with , in a format, then use SwitchPlaces config option which can be found slightly lower then previous config section.

**Comment by DrakePork** [comment]
Ah okay. Thanks
