### ISSUE TITLE
[senderPrefix] from console returns [senderPrefix]

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#2880]
**Description of issue:**
In the translations file, if you have [senderPrefix] but the sender is Console/ server, then it says "[senderPrefix] server" instead of just "server" or something.

---

---

**Cmi Version (using`/cmi version`):** 
8.6.19.6
**Server Type (Spigot/Paperspigot/etc):** 
Papersigot
**Server Version (using `/ver`):** 
Paper-123 1.15.2

**Comment by Zrips** [comment]
Should be fixed with next version.
