### ISSUE TITLE
Armorstand editor will not re-open

### ISSUE THREAD

**Issue by spathizilla** [Zrips/CMI#2881]
When trying to use the armorstand editor on a previously set armorstand, it just keeps repeating the message when using **/armorstand last** and does nothing when using **/armorstand near** if the armorstand is invisible. In the past it would allow editing correctly

---
**Cmi Version (using`/cmi version`):** 8.6.9.10

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** [03:22:43 INFO]: This server is running Paper version git-Paper-122 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Cant reproduce this one. Can you give me an exact state of that armorstand? Is it interactable and all that jazz. And it might be some issue with another plugin creating some stands closer to you which are invalid for editing. So testing without any other plugin and only CMI would be recommended to do.

**Comment by spathizilla** [comment]
Standard default stand:
/cmi armorstand last - broken - does nothing and keeps repeating the help message
/cmi armorstand near - works - opens the armorstand editor as expected

Set default armor stand to invisible and close the editor:
/cmi armorstand last - broken - does nothing and keeps repeating the help message
/cmi armorstand near - broken - does nothing at all, no message.

**Comment by spathizilla** [comment]
Looks like this is caused by another plugin somewhere - was thinking furniturelib but that isnt the problem. I can get around the issue using another plugin to edit the stands for now.

**Comment by LogGits** [comment]
Did you /cmi reload or restart your server between tests?

**Comment by Zrips** [comment]
@spathizilla 
Could be nice to know which plugin caused this issue exactly so we could fix it properly for others.

**Comment by Zrips** [comment]
Added some changes for last and near variables which should resolve some of the issues you had.
