### ISSUE TITLE
[Suggestion] Armor stand copy

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#2885]
**Description of feature/improvement request:**
I want a feature that allows me to copy the layout of one armor stand to another.

---
### Detailed explanation of what it should do, when and in what situation: ###
Just like the sign function where you use the `/cmi sc` command and left click on the source armor stand and left click on the target armor stand. Then the armor can get the same layout as the source. Same arm position, same leg position and same head position, and so on.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Would be really nice if I was to set up many armor stands with the same pose. I'm going to save a lot of time with this instead of adjusting each one.

**Comment by Zrips** [comment]
Ok, next update
