### ISSUE TITLE
[Suggestion] ranks.yml supporting BlocksPlaced for auto rankup

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2889]
As suggested originally by quite a few on Discord, DM, and recently on spigotmc; 

The ability to also rank up players automatically based on blocks placed.

So we can reward our builders, etc.

**Comment by Zrips** [comment]
Well its actually "ItemsUsed" but i can see from where this confusion comes from, will add a way to recognize "BlocksPlaced" as "ItemsUsed" and that's that.

**Comment by FrozenBeard** [comment]
Original: request #2633

**Comment by FrozenBeard** [comment]
ItemsUsed is surely the items that you use, aka when you break a pick, and blocks placed would be separate?

**Comment by Zrips** [comment]
Mojang decided to record them under same statistic, what we can do at best is to check if material is a block or not, if its a block then you have place count, if its not, then its used. Anyways, with next update you will have nice option to use "new" BlocksPlaced

**Comment by FrozenBeard** [comment]
Oh Mojang! Full of surprises. Thank you @Zrips this is the last thing i'm waiting on to move away from Autorank!
