### ISSUE TITLE
Playtime seconds placeholder

### ISSUE THREAD

**Issue by Drc-DEV** [Zrips/CMI#2890]
Description of feature/improvement request:

Most of the servers use Leaderheads for their top leaderboards, this plugin, like many others, require placeholders which display the seconds, in order to parse it as time, while cmi only provides placeholders in minutes/hours. I'm talking especially about the cmi_user_playtime placeholder.
So, my suggestion is to add also a seconds placeholder in order to solve this issue

**Comment by Zrips** [comment]
next update
