### ISSUE TITLE
private homes are not displayed

### ISSUE THREAD

**Issue by richie199** [Zrips/CMI#2891]
**Description of issue:**

Hello, 
after the update to version 8.6.20.0 the private homes are no longer displayed in gui.
---

---

**Cmi Version (using`/cmi version`):**  8.6.20.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):**  1.13.2-R0.1

**Comment by Zrips** [comment]
Check the new version and let me know if that helped.

**Comment by richie199** [comment]
The problem is no longer there, thank you.
