### ISSUE TITLE
<AutoPage> in ctext is broken

### ISSUE THREAD

**Issue by ArtNRG** [Zrips/CMI#2899]
**Description of issue:**
\<AutoPage\> in a CustomText file is not adding the auto pagination. The big file is shown without any pages.

**Cmi Version (using`/cmi version`):** 
CMI version 8.6.20.2
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper version git-Paper-126 (MC: 1.15.2)

**Comment by Zrips** [comment]
I need example of your file. And you should use ingame editor if you are not familiar with the accurate file format it should be in.
