### ISSUE TITLE
Kits Placeholders & Home Priced

### ISSUE THREAD

**Issue by LordDarmix** [Zrips/CMI#29]
Good Afternoon.

It's been a few weeks since we changed to CMI for the best, but we are missing some features that we were using before.

We would like to ask for an "Individual Kit Cooldown" and an "Individual Kit Availability" placeholders.
I know that you offer a self made GUI to choose the kit you want, but we already had a custom menu that shows just the "#" available kits in a fancy way, and we would like to keep that.

We also had a problem with the money cost of warping to homes. We tried using a custom alias to make players pay for warp, but in the end they got charged as they are or are not warped home.

Thanks for your time, and have a nice day.

**Comment by Zrips** [comment]
How would those placeholders look like while outputting results? Cooldown in regular time format? Availability in "Available" "Not available"? Any extra details would help to implement this sooner.

**Comment by LordDarmix** [comment]
The cooldown could be just like in your GUI, showing d/h/m/s if posible (I guess thats regular time format).

Availability, I was thinking in returning "true" or "false", checking for it if you have permission to use the kit, and after that checking if that kit is in cooldown.

As soon as I can test a few more times, I'll explain better the problem I had with the money.

**Comment by LogGits** [comment]
> As soon as I can test a few more times, I'll explain better the problem I had with the money.

@LordDarmix any news on this?

**Comment by LordDarmix** [comment]
The charging problem has been solved. It was just some wrong lines.

Sorry for the delay.
