### ISSUE TITLE
Players Still Losing Inventory When Server Restarts While Players Online

### ISSUE THREAD

**Issue by MCTyler** [Zrips/CMI#290]
Description of issue or feature request:

#### does not get saved and when server restarts, inventory is lost.

04:26:23 INFO]: CMI plugin version: 7.6.10.0-> null
[04:26:23 INFO]: Server version: Paper 1.12.2-R0.1-SNAPSHOT
[04:26:23 INFO]: Vault version: 1.6.10(+)

**Comment by Zrips** [comment]
Any way in actually reproducing this one repeatably?

**Comment by MCTyler** [comment]
Seems to just be random.....It was pretty close to the player acquiring these items (30 sec) when the server was restarted so maybe it just takes awhile to save players data. Still not good.

**Comment by MCTyler** [comment]
Can't reproduce.....
