### ISSUE TITLE
Nameplate

### ISSUE THREAD

**Issue by Juiceqad** [Zrips/CMI#2903]
please fix the problem with displaying nameplate, nameplate is not displayed on the server, when you use vanish, then nameplate is reset

**Comment by Zrips** [comment]
Server version?

**Comment by Zrips** [comment]
Nvm, should be fixed with next build.

**Comment by Juiceqad** [comment]
1.15.2 version 12.03.2020, 13:32, "Zrips" <notifications@github.com>:
Server version?
