### ISSUE TITLE
Thread lock and crash - part2

### ISSUE THREAD

**Issue by Drc-DEV** [Zrips/CMI#2905]
**Description of issue:**

Usually happens when people do a CMI command which requires a playerName input and input an incomplete/nonexistant player name, so this most probably is related to the way CMI parses the player names.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
First crash (/tp command with incomplete username) : https://pastebin.com/mMNSZLzs
Second crash (/invsee command with incomplete username) : https://pastebin.com/BY80hFS2

**Cmi Version (using`/cmi version`):**  v8.6.20.2

**Server Type (Spigot/Paperspigot/etc):**  Paper version git-Paper-126 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Server Version (using `/ver`):** server version 1.15.2

A similar issue (https://github.com/Zrips/CMI/issues/2878) was fixed for the /msg and /r command in the latest version, but apparently the main culprit that causes this wasn't fixed, so this is not a duplicate issue.

**Comment by Zrips** [comment]
Will issue new and different fix with a different approach. It seems to be issue mainly with 1.15 servers and some changed minecraft API which locks world data file.
