### ISSUE TITLE
Homes are not saving data!!

### ISSUE THREAD

**Issue by general2811** [Zrips/CMI#2911]
why did cmi not save homes??
sql db says NULL in the homes tab
every server restart, with save-all command, deletes all homes on the server!
 perms i set are: cmi.command.sethome; cmi.command.removehome; cmi.command.homes; cmi.command.home; cmi.command.sethome.2
latest plugin version with luckperms and paper 1.15.2 #128

**Comment by magnus-frost** [comment]
Also experiencing this issue.

**Comment by Zrips** [comment]
Are we talking about /cmi saveall command here?

**Comment by magnus-frost** [comment]
My issue is player homes not saving in general. 

Latest cmi version using MySQL.
waterfall proxy using cmi bungeecord connector.
paper-129 MC 1.15.

Imported player data from essentials -> after import all homes show up -> upon MC server restart all homes disappear from database.

**Comment by hyronical** [comment]
Also receiving this issue as well. 
- Latest Version of CMI using MySQL
- Paper-129 (1.15.2)
And same as the one above, using CMIB with Waterfall Proxy. 

I've tried creating a new database but still faced with the same isssue. Upon starting the server from a restart/stop, the world names in the Homes field becomes "null". 

![Screenshot_11](https://user-images.githubusercontent.com/45529739/76262244-e6d8fb00-62af-11ea-82b1-dd7b3cdb1310.png)

**Comment by general2811** [comment]
nope we are talking about the "server command" save-all on server stop!
and the same problem like the other two above.

**Comment by Zrips** [comment]
@magnus-frost How did data looked in database before server restart?

**Comment by Zrips** [comment]
Will issue a fix related to this issue with next update

**Comment by general2811** [comment]
that's a joke right? the homes are still not fixed!!! my users are starting to get mad
