### ISSUE TITLE
Price will changed after reload

### ISSUE THREAD

**Issue by YTRemRem** [Zrips/CMI#2912]
**Description of issue:**
After Reloading server with /cmi reload the worth change without editing it, this only happens to lapis... 

---
https://www.youtube.com/watch?v=DuG5OLpbs2k
---

**Cmi Version (using`/cmi version`):** 8.6.20.2 (BungeeCord)

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** Spigot 1.8.8-R0.1-Snapshot

**Comment by Zrips** [comment]
Will be fixed with next version
