### ISSUE TITLE
Play Time Rank Ups

### ISSUE THREAD

**Issue by redeye008** [Zrips/CMI#2913]
**Description of issue:** Any reward tier after 7 days doesn't show up in /prewards nor does it give the rank. Even with the default config file.

---

**CONFIG SECTION:** PlayTimeRewards.yml

https://pastebin.com/0adzKm5F

---

**Cmi Version (using`/cmi version`):** 8.6.20.2

**Server Type (Spigot/Paperspigot/etc):** spigot

**Server Version (using `/ver`):** 1.15.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
What does it say in database under playtimereward table?

**Comment by redeye008** [comment]
Sorry, this is as far as I could get on my own. If this is not what you need please let me know
https://gyazo.com/d0498f891fd60934ae87ddadb181ebd6

**Comment by Zrips** [comment]
Strange. With default file i can see them correctly. Make sure that you dont have PlaytimeRewards->RequiresPermission set to true or that player has appropriate permission node cmi.prewards.[name] to actually be able to get that reward.

**Comment by redeye008** [comment]
RequiresPermission was set to false however setting it to true and then giving the correct permissions seemed to fix this issue. Thank you
