### ISSUE TITLE
$0.00 being displayed as $.00

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#2914]
**Description of issue:**
All balances between $0.00 and $0.99 gets displayed as $.00, $.99 instead of $0.99.
Tested it on a fresh install of the plugin on a local server and it still happened.

---

**Cmi Version (using`/cmi version`):** 8.6.20.2

**Server Type (Spigot/Paperspigot/etc):** Paper (126)

**Server Version (using `/ver`):** 1.15.2

**Comment by Zrips** [comment]
Go to config file and under Economy->Global->MoneyFormat change it into ###,##0.00
