### ISSUE TITLE
Inform player OnDurabilityLoss for armor

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#2917]
**Description of feature/improvement request:**

It would be very nice if worn armor could inform the player

---
### Detailed explanation of what it should do, when and in what situation: ###
Players would like to be informed if their armor is about to break. At this moment, only tools which are held in the players hand, will trigger this `OnDurabilityLoss` notification.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Most armor are heavily enchanted.
Armor is always on the player.
Players forget to check the durability.
If armor breaks, players will be sad.

**Comment by Zrips** [comment]
ok, next update
