### ISSUE TITLE
Issue With Modifying Player Inventory

### ISSUE THREAD

**Issue by Xuwznln** [Zrips/CMI#2919]
Hello, I have a plugin that modify item lores with protocollib. It wont modify it in the server but in the packet. So actually, the modified lore can be only seen in client. But when I try using /inv to have a look at the player's inventory, these lores will become true. I guess that cmi will accept all lores modified by client when using /inv and just like in creative mode. So can you add an option that survival gamemode could only take or put items instead of accepting all things from client?
Sorry for my English and really thanks for your attention!

CMI 插件版本: 8.6.20.0 BungeeCord -> 8.6.20.2
服务器版本: Paper(122) 1.15.2-R0.1-SNAPSHOT
Vault 版本: 1.7.2-b107

Paperspigot

git-paper-122

**Comment by Zrips** [comment]
CMI doesn't take anything from a client, if you have modified items then it means that another plugin actually modifies them, atleast client side. CMI only shows actual items that target player has in their inventory, it doesn't add anything or change anything about them, its a direct copy of an item.
