### ISSUE TITLE
Notarget cmd not working on console

### ISSUE THREAD

**Issue by Feeriix** [Zrips/CMI#2921]
**Description of issue:**

cmi notarget is not finding the player if executed from console.
Getting "Can't find player with this name!"

Running the command in-game works.

---

**Cmi Version (using`/cmi version`):** 8.6.20.3

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** git-Paper-129 (MC: 1.15.2)

**Comment by Zrips** [comment]
Will be fixed with next build
