### ISSUE TITLE
CommandSpy and SocialSpy

### ISSUE THREAD

**Issue by Callial** [Zrips/CMI#2924]
**Question: **
So I have tried giving my staff all perms related to commandspy and socialspy located on the permissions section of your website. I started with just cmi.command.commandspy and cmi.command.socialspy and they could toggle and it said true but they could not see anything being sent from normal players other than normal chat. I have since tried adding literally every perm related to either commandspy or socialspy to the staff rank and it still won't work. Am I doing something wrong? Signspy works just fine, and I have the cmi wildcard perm and commandspy and socialspy work for me. But I don't know why it isn't working for my staff.

**Comment by Zrips** [comment]
This is only when you use /cmi msg command to talk with another player, so staff members could see their conversation if they want too. If you have another plugin controlling private messages, then this will not work.

**Comment by Callial** [comment]
We are using cmi msg, we have no other chat formatter installed. But socialspy and commandspy just won't work unless you have the cmi.* perm. I can only assume it means there is a perm I am missing for both of them but I cannot find it

**Comment by Zrips** [comment]
Ok, try doing something like this: make sure that player A has social spy enabled with **/cmi socialspy** then with player B send a private message to player C with command **/cmi msg C Hey** and check if player A can see that message. Because i cant find anything in the code what would prevent this one from happening other then not having socialspy enabled or not using CMI private message command.

**Comment by Callial** [comment]
That's about what I thought as well which is why I was extremely confused, we did try that to no avail but I will try to get some more tests done later today. We aren't using any other chat formatters and so it may be a conflict elsewhere. I will keep you updated here and if I can't find anything over the next few days I will close this and submit a bug report with the proper info :)

**Comment by LogGits** [comment]
Can you please provide the permission plugin(&version) that you are using & the version of cmi.

**Comment by Zrips** [comment]
@Callial I would suggest to try testing this without any other plugin, like only CMI and some permission plugin you have. As this will rule out any possibility of compatibility issue with another plugin which might intercept message event and cancel it or something like that

**Comment by Callial** [comment]
Socialspy suddenly started working but not commandspy we have updated to the latest version of CMI the 8.6.20.5. We are using LuckPerms V5.0.78. I tried removing all plugins except the CMI and LuckPerms. My main has cmi.* and can see all commands ran by other players when commandspy is true. My staff manager cannot even though he has cmi.command.commandspy. He can toggle it and it says it is toggled to true, but he cannot see commands run by players. We have an alt with the default rank running the commands so it shouldn't have a bypass. 

I have tried setting cmi.command.commandspy.hide and cmi.command.commandspy.bypass to a forced false on the default rank and that did not fix it. I tried setting them to true, the bypass did nothing the hide hid the commands from my cmi.* permission. I have tried setting both of those to true and false on my staff manager as well to no avail.
http://prntscr.com/rfwbqp
http://prntscr.com/rfwdbd

**Comment by Callial** [comment]
So I think I figured it out, I don't think the permission nodes are working properly. We have a sudo op through luckperms. We disabled vanilla op and required it to be done through luckperms. That is the only difference I can think of between the two ranks. Could you let me know exactly what perms 'should' work to get command spy working?

**Comment by Callial** [comment]
I have found the solution, it was the cmi.security.admin perm and after searching that in the config I was able to find the command list section. If I might suggest. You should put more info on what the cmi.security perm does on the website as it sounds like something not related at all.
