### ISSUE TITLE
Temporary God on join

### ISSUE THREAD

**Issue by Sotlol1** [Zrips/CMI#2925]
I have checked the documentation and the config files and can't find anything about it. So if it already exists do tell me.

---
With server resource packs enabled players that log on can be killed by mobs while the resource pack is loading. So it would be a good feature in CMI if we could give players temporary god every time they join with a customizable time. But if this already exists I'm sorry for making this, I just couldn't find anything after looking for hours.

**Comment by BurakDorman** [comment]
Use eventCommands like this:
- cmi god [playerName] true -s
- delay! 5 # it will delay 5 seconds
- cmi god [playerName] true -s

Or just teleport players to the protected spawn zone on join event.

**Comment by Zrips** [comment]
@Sotlol1 
You can use @BurakDorman suggestion or you can use same event command and perform /cmi tgod [playerName] 5
which will give player a 5 second god mode with a timer in action bar to indicate when it ends
