### ISSUE TITLE
Thread lock and crash - part3

### ISSUE THREAD

**Issue by Drc-DEV** [Zrips/CMI#2926]
**Description of issue:**

Related to #2905  and #2878 
Seems like the latest fixes did not work that well.
Another crash log: [crashlogCMI.txt](https://github.com/Zrips/CMI/files/4312889/crashlogCMI.txt)

Seems like the problem is still there.

Usually happens when people do a CMI command which requires a playerName input and input an incomplete/nonexistant player name, so this most probably is related to the way CMI parses players.

Cmi Version (using/cmi version): v8.6.20.3

Server Type (Spigot/Paperspigot/etc): Paper version git-Paper-126 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Server Version (using /ver): server version 1.15.2

**Comment by Zrips** [comment]
Ok, one more attempt. Will post 8.6.20.4 version today or tomorrow and lets see if that one resolves this one. As now its pointing to completely irrelevant part of the code, which is quite strange, but give me idea why this could have been happening in new 1.15 servers. Lets hope, fingers crossed.
