### ISSUE TITLE
TP Jail

### ISSUE THREAD

**Issue by istarengwa** [Zrips/CMI#2931]
**Question: **
Hello, I can not find how to make the point of teleportation outside the jail. The explanation in the wiki doesn't explain it either. I do not know if there is a special order after clicking on [tp], if it is necessary to click somewhere, if it is necessary to put the coordinates in the chat. I did not find any solution :/

Help me please.

**Comment by LogGits** [comment]
Type /jailedit [jailname] then once you are in the location you want to teleport to, click the [tp] button and it will set the outside teleport location to ur current location.
https://gyazo.com/a37a1888c8ad4d11b5a970c87b33c8ef
