### ISSUE TITLE
Variable to /condense command

### ISSUE THREAD

**Issue by ArcadeFighter** [Zrips/CMI#2932]
**Description of feature/improvement request:**
Add variable to /condense **-all**
---
### Detailed explanation of what it should do, when and in what situation: ###
When you have a lot ingots in inventory it's little anoying to use multiple times /condense

### Basic explanation as to why this feature is needed and/or useful to have: ###
It's useful when players have some iron golem farms and they have chests full of ingots and players need to pasting a lot /condense command, so they will use /condense -all and whole inventory will condense their ingots to blocks easily.

**Comment by Zrips** [comment]
Its already by default condenses all items in your entire inventory without using any extra variables. So I'm confused here

**Comment by ArcadeFighter** [comment]
Oh, nvm, i am dumb, sorry.
