### ISSUE TITLE
Homes are still not saving data!!

### ISSUE THREAD

**Issue by general2811** [Zrips/CMI#2933]
**Description of issue:**
why did cmi not save homes??
sql db says NULL in the homes tab
every server restart, with save-all command, deletes all homes on the server!
perms i set are: cmi.command.sethome; cmi.command.removehome; cmi.command.homes; cmi.command.home; cmi.command.sethome.2
latest plugin version with luckperms and paper 1.15.2 #128

**Cmi Version (using`/cmi version`):** 
8.6.20.4
**Server Type (Spigot/Paperspigot/etc):** 
paper 
**Server Version (using `/ver`):** 
1.15.2 #128

**Comment by Zrips** [comment]
Do you have multiverse plugin? Or any other plugin which would create custom worlds?

**Comment by general2811** [comment]
no idea why but after the 2nd restart everything works now

**Comment by general2811** [comment]
yes working with multiverse, and no other plugin who is manage homes on the server!

**Comment by Zrips** [comment]
So it's still doesn't work? As you closed this ticket before. And if you are using multiverse plugin. Which one exactly is this? And do you perform some world load/unload during server run? And, if you set home location in an original world without having any other home, does it save correctly?

**Comment by general2811** [comment]
it is the mainworld, do not test the other one! 
only worlds who get loaded are the 4 farmworlds from multiverse.
[https://pastebin.com/WfL7SRTL](url)
this is the multiverse config!

**Comment by TheoRetisch1** [comment]
I'm facing the same problem:
Paper 1.15.2 #384
CMI 8.7.5.0
Multiverse-Core 4.1.0-b775
