### ISSUE TITLE
Tipped arrow and potion in ICON

### ISSUE THREAD

**Issue by ZConnorZ** [Zrips/CMI#2935]
How can I put the id of potions or arrows in a hologram?
If you use 440: {Potion: "minecraft:harming"}, you will get an arrow without effect.

You can try to find the right arrow through 440: ID for example 440:3, but in the latest version of CMI (8.6.20.5) now this does not work, all items have the same texture.

Paper: 1.15.2
CMI: 8.6.20.5

**Comment by Zrips** [comment]
With next update you can use ICON:tippedarrow:harm
