### ISSUE TITLE
CustomRecipes does not hold item name, item lore, and nbt data like it claims it does

### ISSUE THREAD

**Issue by Jager67** [Zrips/CMI#2936]
Ability to Use Modified Materials for Recipe (crafting mats with: itemlore, itemname, Attributes, etc) @CloudeLecaw

Im trying to make custom spawner recipes but it saves the cow  head as a player_head, and clears any items that have an enchantment, or custom name.

---

---

CMI: 8.6.20.5 BungeeCord
Server version: Paper(126) 1.15.2-R0.1-SNAPSHOT
Vault version: 1.7.2-b107(CMIEInjector)

**Comment by Zrips** [comment]
I'm not aware of any part of plugin description which says that ingredients will retain custom data. You can create recipes by only using materials, as this is vanilla behavior which only accepts one item per field without any other variables, while result can be any item, with or without NBT data, custom lore and so on. This is limitations of minecraft recipe engine.

**Comment by SenseiMunchkin** [comment]
[https://www.zrips.net/wp-content/uploads/2019/02/customrecipe7.png](url)
