### ISSUE TITLE
CustomText <SC>Suggested text</SC> wipes your chat, not pasteing in the suggested text.

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#2937]
From the Docs

> <SC>Suggested text</SC> - is replacement for command and it will paste text into chat field when clicked

There is a problem with this, it does not paste in the suggested text, it wipes what you have in your text box and replaces it.

Can we please just have it paste in.

**Comment by Zrips** [comment]
It's not a bug, it's vanilla behavior of minecraft itself. It will replace your current text you have in your chat field with what it was set to be. There is no way (as i'm aware) to actually add to currently entered text new one. If you know any plugin or actual java code that could do this, i will happily add this to the plugin.
