### ISSUE TITLE
Give Rainbow Dye Armor

### ISSUE THREAD

**Issue by redeye008** [Zrips/CMI#2938]
**Question:**
Is there a way to issue the player with a piece of rainbow leather armour as a given command? As I want to use the armour in a "crate" but I don't want the player to have to be holding the armour for it to work.

**Comment by kadenscott** [comment]
I'm assuming CMI applies NBT data to the leather armour to detect whether or not it's supposed to be rainbow, so you could just copy that NBT data in whatever crate plugin you're using.

**Comment by redeye008** [comment]
Thank you I will give this a try.

**Comment by Zrips** [comment]
@redeye008 You can utilize command /cmi saveditems where you can save any item which can be given out to anyone later on with simple command. This includes giving item with NBT data in it. While you do have option to use player name in /dye command, but this will require from player to actually hold leather armor in their hands, which can be not so convenient.
