### ISSUE TITLE
logged-in player data is deleted when execute migratedatabase command

### ISSUE THREAD

**Issue by ethernetcat** [Zrips/CMI#2939]
**Description of issue:**
Running migratedatabase when a player is on the server will cause the logged-in player's data to be migrated incorrectly and be deleted.
I found this problem in migrating from MySQL to SQLite.
If a player is not logged in, their data will be migrated successfully.

**Cmi Version (using`/cmi version`):** 
CMI 8.6.20.4

**Server Type (Spigot/Paperspigot/etc):** 
git-Paper-132

**Server Version (using `/ver`):** 
1.15.2

**Comment by Zrips** [comment]
Will add an extra check to make sure that no one is online before migrating, just to avoid issues like this in future.
