### ISSUE TITLE
Egg spawner changing !!! IMPORTANT !!!

### ISSUE THREAD

**Issue by LoToRTv** [Zrips/CMI#2940]
Hello, player can change the spawner from EGG, cmi.egginteract.* false donthelp

cfg: https://hastebin.com/uquvewaduv.coffeescript

8.6.20.5 BungeeCord 

Mc:1.15.2

git-Paper-120

Plugins (23): AAC, CloudNet-Bridge*, CMI, CoreProtect, CustomEnderChest, EpicWorldGenerator, FeatherBoard*, HeadDatabase*, JPremium*, LimitPillagers, LiteBans, LuckPerms, MobFarmManager, MVdWPlaceholderAPI*, MysqlPlayerDataBridge, PlaceholderAPI, ProtocolLib, Residence, serid, StackMob, Vault, VillagerOptimiser, WorldEdit

**Comment by Zrips** [comment]
Check if player has access to cmi.egginteract.[mobType] permission node with /cmi haspermission cmi.egginteract.[mobType] to make sure that he doesn't have access from somewhere else.

**Comment by LoToRTv** [comment]
https://imgur.com/a/SpwXzJ0 all ist ok no perms fix bug pls ?

**Comment by Zrips** [comment]
Try testing this with CMI only, as this might be caused by some other plugin interferring

**Comment by LogGits** [comment]
Wasn't able to reproduce this, closing due to lack of response. If you still have this issue please open a new ticket.
