### ISSUE TITLE
tpaWarmup not working

### ISSUE THREAD

**Issue by MarcussGTX** [Zrips/CMI#2953]
**Description of issue:**
Using tpaWarmup is not working in 8.6.20.5, it just teleports you instantly after accepting.
Works fine in 8.6.20.4

CurrentLoc:true may also not work, hard to test on 8.6.20.5, but it does not work on 8.6.20.4.
It acts like it is set to false

---

**CONFIG SECTION:**
```
    TpaTime: 60
    # Defines time in seconds for player being teleported after tpa or tpahere is being accepted
    TpaWarmup: 3
    # Defines if player can move when tpa or tpahere is being accepted
    TpaMove: false
    # Defines time in seconds for blocking player teleport offers after denying their request
    TpaBlock: 120
    # Defines time in seconds for bypassing prevented teleportation to unsafe location
    TpBypass: 15
```

---

**Cmi Version (using`/cmi version`):** 
CmI 8.6.20.5

**Server Type (Spigot/Paperspigot/etc):** 
git-Paper-133 (MC: 1.15.2)

**Server Version (using `/ver`):** 
git-Paper-133 (MC: 1.15.2)

**Comment by XXY218** [comment]
Me too, Players no longer have to wait to teleport...This issue also occurs in 8.6.20.5

**Comment by aenaveen** [comment]
Same here, This also occurs in 8.6.20.6 as well.

**Comment by aenaveen** [comment]
Same here as well, on CMI 8.6.20.5 Paper 1.15.2 B#143 (both latest as of 22/3/2020

**Comment by aenaveen** [comment]
I put the GlyphHead on it and put a long 5-second delay, and then I watched the player use /tpa and the warmup happens for the request itself, so after a 5-second delay I get the request and then when I accept they teleport immediately.

**Comment by Sikatsu** [comment]
@Zrips I have this issue as well. Hope you can look into this.

**Comment by Zrips** [comment]
Will be fixed with todays update
