### ISSUE TITLE
/cmi gamerule only opens "world" GUI

### ISSUE THREAD

**Issue by Drc-DEV** [Zrips/CMI#2958]
**Description of issue:**
/cmi gamerule does not allow to specify world, and if I'm in a specific world other than "world" it will only display the GUI for "world"

---

**Cmi Version (using`/cmi version`):** 8.6.20.5
**Server Version (using `/ver`):** Paper(130) 1.15.2-R0.1-SNAPSHOT

**Comment by Steev93** [comment]
Hey Drc-DEV,

Do you have these?
http://prntscr.com/roc0lh

Can you provide a screenshot of what you see when you do /cmi gamerule
