### ISSUE TITLE
[Request] Death logger

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#296]
Description of issue or feature request:

I have a suggestion for a feature :smile: 
It would be very nice to have a death logger. This is how I see it:
A player dies. He says that he died because of a heavy server lag of some kind and would like to have all he's gear back. I can then type /cmi deathlog zrips and get some information on how he died, where he died, and I can get the inventory he had when he died.

**Comment by Zrips** [comment]
So basically option in config file inv->SaveOnDeath set to true?

**Comment by CloudeLecaw** [comment]
u know u have a simliar thign allreasy + a way to restore it?
just save the inventories on death (may last 10)

**Comment by Baktus79** [comment]
wow, I totally forgot about that feature :smiley: I think this will do just fine. Thanks for the help
