### ISSUE TITLE
Homes getting deleted for random members at random times

### ISSUE THREAD

**Issue by cayoten** [Zrips/CMI#2963]
**Description of issue:**
 Occasionally, the homes of only **some** of my members will be deleted. I am using MySQL for data storage, and there are no errors. It seems to happen at random, and only to select members.

---

**Cmi Version (using`/cmi version`):** 8.6.20.5 (BungeeCord also used)

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):**  Paper-137 Version 1.15.2

**Comment by RWolfyo** [comment]
Can confirm (Same setup as above) happen to like 3 people randomly.

**Comment by mrfloris** [comment]
I've given @Zrips a poke on Discord, maybe he has time (soon) to review this. It's also not the first time I see this being reported on Discord chat.

**Comment by general2811** [comment]
me too! 
`https://github.com/Zrips/CMI/issues/2933`
