### ISSUE TITLE
Custom Enchant levels not working

### ISSUE THREAD

**Issue by codingvincee** [Zrips/CMI#2965]
**Description of issue:**
When using `/cmi enchant efficiency 2048` on a diamond pickaxe, the mining efficiency is equal to an enchantment of level 5. This goes for any enchant level above 5.

---

**Cmi Version (using`/cmi version`): 8.6.20.2** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`): git-Paper-142 (MC: 1.15.2)**

**Comment by Zrips** [comment]
That's not a bug with CMI, that would be issue with how Minecraft handles enchantments above certain level
