### ISSUE TITLE
Placeholder %server_time%

### ISSUE THREAD

**Issue by mare-on** [Zrips/CMI#2969]
Hi, there is one placeholder called **%server_time_[timeFormat]%**.

This placeholder shows an actual time in real world... yes but... no.
It Shows actual time of the zone where the physical server is located.

I would be really happy for some extra attribute to define timezone or grant new placeholder where you can define this. Because I would like to use this placeholder on my server but his physical location is in different country - different timezone and time offset is -2 hours. I am not able to change the timezone of the physical server due to more servers and services running on him and there is no other option.

CMI is really powerful plugin and I love it, so I would be happy if somebody could stay for a while and try to think about this extension of this placeholder.

**Comment by Zrips** [comment]
ok, next update will have something like **%server_time_[timeFormat]_[timeZone]%** which can be used like **%server_time_HH:mm:ss_GMT+5%**
