### ISSUE TITLE
Portals sometimes don't activate commands when you enter

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#2973]
**Description of issue:**
Sometimes portals randomly won't activate commands.  I'll jump into the same portal 5 times and it'll work 4 times and then not the 5th.

The commands on the portal in question:
https://prnt.sc/rkd0wz

The portal is one you fall into.  I initially thought maybe people were falling through it before it could activate, so made it deeper... that didn't fix it so I put barriers at the bottom.. people will sometimes fall into it, land on the barrier and just stay there, but other times those same players fall in and teleport properly in the same location.  The server does not appear to be lagging.  

Any suggestions?  My best idea right now is to put another portal under it and hope the second one catches them...

---

No error

Config not relevant

---

**Cmi Version (using`/cmi version`):** 
8.6.20.5

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper 132 (1.15.2)

**Comment by pvvvo** [comment]
It seems is and issue about view distance of the portals. I did reproduce it changing the view distance of the portal to 1 and then falling into it, the portal didn't render so it didn't execute any command.

**Comment by Zrips** [comment]
Issue is with portal check interval. You might have it set to high enough for player being able to pass throw portal without triggering next check. Will add some changes to check more frequently when player falls, as this usually creates faster moving players which have a bigger chance to shoot throw portal.
