### ISSUE TITLE
Nametagged pets

### ISSUE THREAD

**Issue by IsRealMe** [Zrips/CMI#2976]
**Description of issue:**

When player using a nametag on a pet (wolf, cat, parrot e.t.c.), the pet owner cannot see it's name, but other players can. This does not apply for "not tammed" mobs, then it's working fine.

---

**Cmi Version (using`/cmi version`):** 
8.6.20.6
**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Should be fixed with next build.
