### ISSUE TITLE
CMI Console Spam NPE

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#2977]
**Description of issue:**
Console spam by CMI plugin

**Cmi Version (using`/cmi version`):** 
8.6.20.6

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
1.15.2 - git-Paper-133

Logs:
https://pastebin.com/P6H9j2s3

**Comment by Zrips** [comment]
Should be fixed with next build
