### ISSUE TITLE
tpahere not working

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#2979]
**Description of issue:**
When any player sends a tpahere request to a non-admin player, and the player accepts, it warms up properly, warns the player not to move, shows the teleportation particles... and leaves the player where they were.   If the person receiving the request is an admin, it works properly.  It shows no permission fails either way.  It seems to be failing on a warmup bypass check:
https://prnt.sc/rl0448
but the player is NOT moving.

---

No error present

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
https://pastebin.com/gmbGjQdM
```

---

**Cmi Version (using`/cmi version`):** 
8.6.20.6

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper 132, 1.15.2

**Comment by Zrips** [comment]
Cant reproduce at this point. Try removing cmi.safeteleport from regular player if he has one or if you have possibility, try running server with only CMI and your permission plugin just to rule out any possibility of interference from another plugin preventing teleportation.

**Comment by Momshroom** [comment]
Yes, I can reproduce it with only CMI and LP loaded and, no the regular player doesn't have cmi.safeteleport.

**Comment by Momshroom** [comment]
I still get the error in the latest CMI (8.6.20.9) with only CMI and LP loaded:
https://youtu.be/KfVm3baUFas
Dadshroom (the regular player here) does not have cmi.safeteleport:
https://prnt.sc/ropwhv

**Comment by Momshroom** [comment]
If I give the regular players cmi.command.tpahere.warmupbypass then they can actually be teleported by tpahere

**Comment by Zrips** [comment]
This should be working now, if not let me know.

**Comment by Momshroom** [comment]
This isn't working in 8.6.21.5
