### ISSUE TITLE
[Suggestion] BlockCommand module

### ISSUE THREAD

**Issue by TheRobLP** [Zrips/CMI#2981]
**Description of feature/improvement request:**

A new command, for example /blockcommand, which will let blocks execute commands on klick, and/or touch.

### Detailed explanation of what it should do, when and in what situation: ###
After execution of the command it will let you klick any block to define it as "CommandBlock". When left or right-klicking this block it will execute a command, depending on the klicking method. It can also be configured to work when running over it.
---
### Basic explanation as to why this feature is needed and/or useful to have: ###
This would, for example be usefull to create for example JumpPads (on touch method), or a Mailbox (opens a custom mail GUI on right-klick for example). Honestly, there are many possibilities as to how this could be usefull.

**Comment by Zrips** [comment]
Interactable command **/cmi ic** does exactly this. You can attach any comment to any block or entity and perform it when player clicks it or triggers by stepping on pressure plate and similar.
