### ISSUE TITLE
Random Teleport still kills players

### ISSUE THREAD

**Issue by Va1a** [Zrips/CMI#2983]
**Description of issue:**
Players still die in many cases when running /cmi rt (random teleport command). I think perhaps this can be fixed by giving the player a high level of resistance potion effect immediately when they are teleported, wait a few seconds, then teleport them to ground level, as it seems the plugin cannot detect ground level before the new chunk is generated, so the player falls through the world.

---

**Cmi Version (using`/cmi version`):** 
CMI 8.6.20.6
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot 
**Server Version (using `/ver`):** 
Paper-137 (1.15.2

**Comment by mrfloris** [comment]
This sounds like this bug report;
https://github.com/Zrips/CMI/issues/2775

**Comment by Zrips** [comment]
Should get fixed with today's update
