### ISSUE TITLE
/baltop doesn't cache prefixes

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#2984]
**Description of issue:**
In the translation file, if you have [prefix][playerName]... and you do /baltop, it doesn't show prefixes for people who aren't online. if they logon and you run the command again, the prefixes show.

---

**Cmi Version (using`/cmi version`):** 
8.6.20.6
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper 1.15.2 build 143
**Relevant plugins (Delete if this isn't needed):**
Luckperms

**Comment by Steev93** [comment]
Try running a LP placeholder "%luckperms_prefix%" if you are using LP to run this?

**Comment by Zrips** [comment]
It doesn't really work without actually saving them into database. You can test this one with luckperms and check player information when he is offline. Prefix is none existent until player logs in. For some strange reason LuckPerms doesnt even allow to get offline player information by UUID... We are storing players prefix after he logs in, then we can have it even if he is offline, but at the moment without extra saving into database some quite low priority information, we cant really do anything about it.
