### ISSUE TITLE
Custom messages

### ISSUE THREAD

**Issue by DivergingMC** [Zrips/CMI#2985]
**Question: **
Hello, so i recently bought the plugin and I am trying to setup custom messages. Is there a way to automatically put the prefix of my server before ALL cmi messages? for example when a user types /cmi fly, i want it to say: ServerName >> Fly enabled.

If so, how can i do this for all my messages without going through each one individually? Thank you!

**Comment by Zrips** [comment]
Not really, i mean, not all messages needs a prefix, so we cant simply slap on every message this one in hopes that it will look good. Basic example would be a list, you will have something like "ServerName 1. Zrips
ServerName 2. Zhax"
And so on. So you will need to add !prefix! variables to the lines you want to add your prefix, which can be defined at first line in your locale file.
