### ISSUE TITLE
[Suggestion] Crates

### ISSUE THREAD

**Issue by TheRobLP** [Zrips/CMI#2986]
**Description of feature/improvement request:**
Loot crates (per-block definable) that can be opened with "keys". 
---
### Detailed explanation of what it should do, when and in what situation: ###

After opening a crate with a "key" it would have an animation to randomly give out an item (or command) whos chances can be configured by admins. It would come with an fully-fledged Admin GUI with settings such as particle effects, Hologram editor, crate item manager, etc.. Also, just in case: I have read the rules for Premium ressources, and it´s only prohibited to sell a plugin which primary focus is Crates. However in CMI this would only be a feature like the many great others that are present there.

### Basic explanation as to why this feature is needed and/or useful to have: ###

It would be usefull for example if you wanna reward players for doing tasks, for example reaching certain achievements, or participating in events, that will give them joy and excitment over which item they could get.

**Comment by Va1a** [comment]
There is actually a really good free crate plugin available Rob, it's called GoldenCrates. Search it on spigot.

**Comment by TheRobLP** [comment]
Oh wow... I didn´t know that Night has made a Crates plugin. Thanks so much for the suggestion, Ill check it out :-)
