### ISSUE TITLE
Playtime / Playtimetop resets itself for just a single user every time

### ISSUE THREAD

**Issue by Tsumitsuki** [Zrips/CMI#2987]
Tittle says it i guess.

Some day the playtime just resets itself on ONE player on our server. Not Everyone! Just this one player!
It startet again at 0 and now he is on 10 days again. But there are about 50 days missing. He should be on 60 days by now.

So we tryed to fixed it via "/cmi editplaytime" and even via editig the db but it's going back to the time befor editing after a few seconds, everytime.

eg. he's on 10 days and we add 50 days via cmi editplaytime.
it says 60 days if we check with playtime.
if we check 1 minute later it says 10 days again (+1min if he's online right now). 

We edited the db while the server was off but same result. still 10 days.

Sometimes the 60 days on playtime stays until the next server restart.
But even if it stays for a while in the playtime top it's still at 10 days while the playtime for the player itself shows 60 days. And resets to 10 min after server restart again.
---

I dont know whats causing this and have no ideas to fix it.
It's only this one player.
I can't immagine it's the 50 days cause other servers have players with way higher playtimes.
Dont know if it hast reset on exactly 50 but defenetly somewhere about it.

Stuff:

CMI plugin version: 8.6.20.6
Server version: Paper("49fdb182") 1.15.2-R0.1-SNAPSHOT
 Vault version: 1.7.3-b

**Server Type** 
Paper

**Server Version (using `/ver`):** 
git-Paper-"49fdb182" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
 Plugins (58): AdvancedRegionMarket, BuycraftX, ChatFeelings, Chunkmaster, Citizens, ClickDye, CMI, ConsoleSpamFix, CoreProtect, CraftBook, CrazyCrates, CustomGUI, DisplayShops, dynmap*, Dynmap-WorldGuard*, EasterEggs*, FeatherBoard*, FlyingCarpet, GameModeInventories, GrubenCore, HeadDatabase*, HungerKeeperPlus*, Jobs, KixsAutoAnnouncerPremium, Landlord, LibsDisguises, LiteBans, LuckPerms, MarriageMaster, mcMMO, MeltDown, Minepacks, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MVdWPlaceholderAPI*, MythicMobs, PlaceholderAPI, PlayerVaults, PlayerVaultsGUI, PlugMan, PremiumVanish, ProtocolLib, ProtocolSupport, Quests, SignTracker, SuperLuckyBlock, SuperTrailsPro*, TogglePvp*, TokenManager, Vault, VeinMiner, Votifier, WorldBorder, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags

**Comment by Zrips** [comment]
In general CMI doesn't modify playersplaytime and it only uses stored playtime in players data file or in players statistics file, depending from which place you take this one. Do you have StopPlayTime enabled in your config file?

**Comment by Tsumitsuki** [comment]
Ok. Don't know where the playtime is taken from. Maybe i'll find it myself.

And yes. StopPlayTime on AFK is on.

**Comment by Zrips** [comment]
Try out latest build as there was some changes related to StopPlayTime which maybe could be the cause of your issue. If issue still persists, let me know.

**Comment by Tsumitsuki** [comment]
After updating cmi and SET the time again via editplaytime the PlaytimeTop is correct but the individual Playtime is resetting itself after a serverrestart to the value bevor the edeting.

> playtime Tsumitsuki
[12:42:06 INFO]: --------------------------------------------------
[12:42:06 INFO]: * Total play time: 13 days 32 min 13 sec
[12:42:06 INFO]: * Joined on: 05/09/18 20:39:06
[12:42:06 INFO]: --------------------------------------------------
> playtimetop
[12:42:13 INFO]: ----- TopPlaytime -----
[12:42:13 INFO]: 1. User - 62 days 12 hours 20 sec

**Comment by TheoRetisch1** [comment]
I have exactly the same problems or rather the same change in the problem that Tsumitsuki mentioned about four days ago. This ticket describes the same problem as the one I documented in #1900.
