### ISSUE TITLE
Vanished Players dont bypass Teleport sounds

### ISSUE THREAD

**Issue by Exillium313** [Zrips/CMI#2989]
While in vanish a player pointed out he could hear me teleport to him, so my suggestion is to remove sounds from teleporting, and any other that may be applicable for vanished players.

---
Have 1 player OP'd and in Vanish and another with no special permissions, have default player have sounds on, and OP player TP, default player should hear CMI's preset Teleporting sound and would know someone teleported to him.

Further helps admins to be fully invisible, when needed.

**Comment by Zrips** [comment]
Which sounds are we talking about in particular? Because CMI will only send sound to player who teleports if that is enabled. Vanilla teleport doesn't cause any sound.

**Comment by Exillium313** [comment]
To be honest I do not know, I dont play with sounds on at all.  I just had a player ask in global chat after I teleported to him in vanish if someone had teleported to him, because he heard an abnormal sound.
  I will do some further testing, I looked through the settings and didnt see anything so I thought it was something I just overlooked.

**Comment by Zrips** [comment]
Strange, would be interesting to know what sound he heard.

**Comment by Exillium313** [comment]
Turns out it was another plugin, sorry about that.
