### ISSUE TITLE
Uncondense issue

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#299]
cmi 7.6.9.0 paper spigot

I had posted before about requesting uncondense to go from blocks to nuggets instead of block > ingot > nugget but was told its a feature already. But I found the reason why I didn't know it was a feature!

So if you for example have a stack of gold blocks in your inventory. With one gold ingot. When you run /uncondense it turns all of it into nuggets. 

The nuggets do hit the ground correctly now but I just wanted to know if there is any way to prevent them from fully uncondensing if there is the one stray ingot.

**Comment by Zrips** [comment]
Should be fixed with next build.
