### ISSUE TITLE
Sitting in jail (literally)

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#2992]
**Description of issue:**
Teleporting out of jail doesn't work when player is sitting.
How to reproduce:
- Make a jail
- Place a chair (stairs) inside the jail area
- Player is jailed
- Prisoner sits down on stair and waits for the jail time to end
- Jail time ends, player is no longer sitting.
- Player is not teleported. Player is still inside jail area.

---

**Cmi Version (using`/cmi version`):** 
8.6.20.8
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.15.2

**Comment by Zrips** [comment]
Getting fix with next build
