### ISSUE TITLE
When using /homes {username} multiple pages defaults back to the user running the command.

### ISSUE THREAD

**Issue by malaeus** [Zrips/CMI#2994]
**Description of issue:**

When using /homes {username} to view another players homes (even as OP) , if the user has more than one page of homes. when you click to go to a new page. it defaults back to the users home list who ran the command. and if the user does not have multiple pages it shows a blank page. 
no errors present on console
---
i posted this on discord, but forgot to make a ticket. 
thank you

CMI: 8.6.20.8
Paper(135) 1.15.2-R0.1-SNAPSHOT
 Vault version: 1.7.3-b

**Comment by Zrips** [comment]
Will be fixed with next update
