### ISSUE TITLE
CMI interacting with VoidChest 4.1.6

### ISSUE THREAD

**Issue by Shin1gamiX** [Zrips/CMI#2995]
**Description of issue:**
When both VoidChest and CMI are enabled, and CMI has any DisabledEnchantment in it's list and that is valid, VoidChest's UMaterialClass will break, throwing NoClassDefFoundErrors.

---

**ERRORS**
https://pastebin.com/raw/pKnnTpxk

---

**CONFIG SECTION:**
DisabledEnchants.yml file, only happens if there is a valid enchantment in the list.

---

**Cmi Version:** 
8.6.20.8

---

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

---

**Relevant plugins::**
[VoidChest 4.1.6](http://www.spigotmc.org/resources/65576/)

**Comment by Zrips** [comment]
This should be resolved by VoidChest plugin as its not handling properly enchants which could not exist

**Comment by Shin1gamiX** [comment]
Could you please elaborate on how a NoClassDefFoundError is thrown, apart from the NPE ones, only whenever the DisabledEnchants feature of CMI is being used?

**Comment by Zrips** [comment]
CMI removes recorded enchant from server cache, which means that in case VoidChest precached enchants beforehand and then doesn't check if they still exist, you will have error like this. CMI doesn't block enchantments when you disable them, it literally removes them from entire server.
