### ISSUE TITLE
VanishEdit

### ISSUE THREAD

**Issue by Steev93** [Zrips/CMI#2996]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###

To allow a global vanish edit.
If not in the config, so all vanished players can have the flashlight, the vanish boss bar and glow when in vanish.

Then have a /vanishedit, of course, as we do now for those staff members that can edit it.

### Basic explanation as to why this feature is needed and/or useful to have: ###

Be useful to see when a user is vanished or reminded the user they are in a vanished position.

**Comment by Zrips** [comment]
Will add an option to define default values in config file with next update
