### ISSUE TITLE
Spanish language updated

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#2998]
**Spanish language updated to CMI 8.6.20.9**
https://mega.nz/#!SV8lyJKI!z2RRSE482sa4J-UBZoSa3gxZYREsxvFlvjGc2r52XRE

I have updated the Spanish language file to the latest version of CMI, as I have been doing for the last few years, but Zrips, is not including them in the updates, that's why I'm exposing it here.

PS. I have been sending you the files by private message. The last one here https://www.spigotmc.org/conversations/cmi-spanish-language-update.393491/
I want to think that this is not the right place, since I found in the last change log: https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/update?update=324606 that Zrips has included a "supposed" update of the ES language file, based on my work by another user.

**Comment by Zrips** [comment]
Private messages on spigot can be missed by me, sorry about this, will include your version with next update. You can get in contact with me throw discord with a private messages.
