### ISSUE TITLE
Color Code issues

### ISSUE THREAD

**Issue by Pendragon1111** [Zrips/CMI#3]
Some /msg related bugs:
http://prntscr.com/i7yrqw /tell looks like this, no other message commands do.
https://prnt.sc/i7yrpk people on the recieving end of a player with bold in their nickname see this. (using luckperms for prefixes and a number of other things)
/r only responds to the last person who messaged you. i dunno if this is intentional, but if it is, i'd very much like an option to change it to the last person YOU messaged, instead.
if this is already a config option, please point it out to me; i've been unable to find it.

color code permissions are also a bit broken. nobody has the node to use black or magic (&k) but they can use it in /msg and in /nick.

**Comment by Zrips** [comment]
/tell is not a CMI command, its vanilla one. You can create custom alias to redirect it to CMI
For bold text, simply add &r for chat format to reset any special text formater.

**Comment by LogGits** [comment]
Negate the permission: `minecraft.command.tell` if issues persist with minecraft related commands you can also negate the permission `minecraft.command.*` or even `minecraft.*`.

**Comment by Pendragon1111** [comment]
To note, we do have &r in chat formatting. We tested a number of different things, including using &f instead of just &r.
Just uploaded the newest version of cmi, the bug persists. Here is:
https://pastebin.com/BCCXEnub Our entire config file. 
https://pastebin.com/M5dvNrE4 The chat section of the config file above.

**Comment by Zrips** [comment]
Tested with your settup, still same results, its simply works. Which server version are you running? Any other chat control plugins? Tested without any plugin but only CMI?

**Comment by LogGits** [comment]
@Zrips I was able to reproduce. This may be related to nickname.
https://gyazo.com/a3fb4f242efbc617295451d2b82d2367
I set my name to &c&lhi and my message was in bold.

**Comment by Zrips** [comment]
Ok skipped one small thing, we are talking about private messages here. You have to change private message format in locale file
`      TargetMsg: '&7[&8[senderDisplayName] &7-> &8me&7]&r&f [message]'
      SenderMsg: '&7[&8me &7-> &8[playerDisplayName]&7]&r&f [message]'`
will change default ones to this. This fixed "issue"

**Comment by Pendragon1111** [comment]
This worked, thank you very much!
