### ISSUE TITLE
[REQUEST] Custom name and permission per customrecipe

### ISSUE THREAD

**Issue by PryPurity** [Zrips/CMI#300]
Description of issue or feature request:

Allow custom recipe names, and allow players who have permission access to using those recipes

#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR (IGNORE IF YOU HAVE NO ERROR):
```
####################
## PASTE ERROR HERE ##
####################
```

CONFIG SECTION (IGNORE IF NOT RELEVANT):
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

Cmi Version (using`/cmi version`): 
Server Type (Spigot/Paperspigot/etc): 
Server Version (using `/ver`):

**Comment by CloudeLecaw** [comment]
i also posted this Problem once in the spigot discussion but may noone was interested in it^^

i saw that for current custom recipes ist not possible to use items that have names or Lores as recipes materials.

normaly i wanted a "modified" goldnugget + a Silktouch 1 picaxe  to craft the   pickaxe with silktouch 2
the result was they could use a normal goldnugget and a normal picaxe to craft the silktouch 2 picaxe @.@...

**Comment by imhandmade** [comment]
Interesting, I did not know of this, I need to test that out now..

**Comment by GrimPod** [comment]
Didnt know of this feature until now, how do you make custom recipes?

**Comment by CloudeLecaw** [comment]
cmi has a whole GUI Editor for this :§
**/cmi customcripe**

**Comment by Drc-DEV** [comment]
Any news about this feature? would be really useful @Zrips

**Comment by Daxxas** [comment]
Yep! I would love to have that too

**Comment by Drc-DEV** [comment]
Please @Zrips this has been in the To do list for over a year :P

**Comment by Omarlatif** [comment]
If possible to add lore / extra NBTs to it. @Zrips <3

**Comment by CloudeLecaw** [comment]
> If possible to add lore / extra NBTs to it. @Zrips <3

this is also one thing what i ment with "modified items" ;-)

other ntbs, enchants, extra names, lores, etc.. as materials

**Comment by Exillium313** [comment]
Bump, Would love this!

**Comment by Sikatsu** [comment]
@Zrips will this be added in the next release, since it was closed?

**Comment by CloudeLecaw** [comment]
no u have not read the last update log right?

**Comment by Sikatsu** [comment]
I have, the update was posted after my message ^^
