### ISSUE TITLE
Silent chests in PremiumVanish unvanish

### ISSUE THREAD

**Issue by MADS0LADEN** [Zrips/CMI#3000]
**Description of issue or feature request:**
CMI does still open chests silent when unvanished (PremiumVanish)

When i join the server i automatically go into vanish, maybe that has something to say.

---
**Cmi Version (using`/cmi version`):** 
https://i.imgur.com/f8LGKuD.png

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
https://i.imgur.com/AcjvjY3.png

**Relevant plugins (Delete if this isn't needed):** 
PremiumVanish

**Comment by Zrips** [comment]
You might still have silentchest toggle on, try using /cmi silentchest to toggle it off, and if it still reenables after you use unvanish, then try setting silent chest to false in your vanish editor from CMI /cmi vanishedit this will be labeled as (Noisy chest's) set it to true, aka green wool.

**Comment by MADS0LADEN** [comment]
That fixed it, thanks! :)

**Comment by MADS0LADEN** [comment]
this was not the problem, the problem is that cmi does not unvanish the player when PremiumVanish is unvanishing the player.
I am joining the server in vanish, i think that is the reason why.
