### ISSUE TITLE
Server crash using placeholderAPI in a hologram

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#3002]
**Description of issue:**
Whenever I try to use placeholders in a hologram from placeholderAPI, the complete server crashes with the error below. @Zrips I hope you can look into this soon, it seems rather important.

https://pastebin.com/SwK2ixms

**Comment by Zrips** [comment]
Doesn't look like its CMI issue, as stacktrace points to placeholderAPI which points to me.A5H73Y.Parkour plugin which fails to update placeholder. You can try to get in contact with this plugin developer to figure out what went sideways.

**Comment by Sikatsu** [comment]
Oh really, that's odd. Well thanks for looking into it!
