### ISSUE TITLE
Lots of Warn on console startup log.

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#3006]
**Description of issue:**
Lots of Warning on server console startup logs.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://pastebin.com/C32Hyceb

**Cmi Version (using`/cmi version`):** 
8.6.20.8

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
1.15.2 - git-Paper-133

**Comment by Zrips** [comment]
You have a misformatted tablist.yml file. 
You can check your file if it's correctly formated with a site like this https://yaml-online-parser.appspot.com/
