### ISSUE TITLE
Remember /fly preference after world switch

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#3007]
**Description of feature/improvement request:**

If players have /fly on in the survival world and they switch to the nether where fly is disabled and then they go back to the survival world, fly is still disabled. Could you make it so the fly preference will be remembered? If they go back to the survival world, fly will automatically enable again?

**Comment by Steev93** [comment]
Curious... Wouldnt this be a multiverse control stopping this? As I can switch worlds and fly is still on?

**Comment by Sikatsu** [comment]
I indeed have fly set to false in multiverse. Otherwise players were able to bypass and use fly in worlds they shouldn't be able to fly in using /back or falling in the void and quickly relogging.

> allowFlight: 'false'

**Comment by Zrips** [comment]
Should be working now as intended.
