### ISSUE TITLE
/nick - diffrent name capitilization

### ISSUE THREAD

**Issue by StarozytnySky** [Zrips/CMI#3009]
**Description of issue: When player set own nick /nick can set a diffrent capitilization name. Player only have permission "cmi.command.nick" and "cmi.colors.nickname.*" example. player have nick Test and can set TESt **

**Cmi Version (using`/cmi version`): 8.6.19.3** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`): paper-1.12.2 # 1618**

**Comment by Zrips** [comment]
This is not a bug, player is allowed to change the capitalization of a nickname, he is not allowed to change to a completely different one. We maybe could add a separate permission node or config option to restrict capitalization change, but in general, it doesn't really make a big impact

**Comment by StarozytnySky** [comment]
if it possible would be great, seperate this other permission.
