### ISSUE TITLE
[bug] weird new exception error on /cmi invcheck (or restore inventory click)

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3015]
very strapped for time, but didn't want to Not report it, so here it is

https://hasteb.in/qazofupo.bash

spigot 1.15.2 yesterdays release of cmi

i checked offline player who died and timed out, i click 'restore for owner', and before i went offline myself because im supe rstrapped for time, i noticed that in console, so dumping it here before leaveing sorry for inomplete report

**Comment by Zrips** [comment]
Bug related to player being offline, should be fixed with next version
