### ISSUE TITLE
Cmi near point question/request

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#3016]
**Description:**
`/cmi near` shows nearby players. Clicking the nearby players name forces the player to type `/cmi point <locationhere>`. Players on our server don't use point command can we get this configurable/togglable. 

---

**Cmi Version (using`/cmi version`):** 8.6.20.6

**Server Type (Spigot/Paperspigot/etc):** paper 1.15.2 build 132

**Comment by Zrips** [comment]
Toggle, in config and some extra tiny change with next update.
