### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by Steev93** [Zrips/CMI#3017]
**Description of issue:**
Place holder for Kits ,  {USERNAME} is broken when issuing commands, saying player not found when they re online.

> Items containing {USERNAME} {DISPLAYNAME} {KITNAME} {WORLDNAME} {RANDOMPLAYER} variables in display name or lore will be replaced automatically to appropriate values when player gets kit.

---

**Cmi Version (using`/cmi version`):** 
8.6.20.9
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-137

**Comment by Zrips** [comment]
{USERNAME} is only for item name or item lore, not for giving out to a specific player. Unless i'm missing something here. What command did you use exactly to give kit to this player? Because in general you will need [playerName] variable in commands.

**Comment by Steev93** [comment]
I will try that tomorrow!! I did ask in discord chat but no one knew the answer. This is for the crate plugin giving them a custom key

**Comment by Zrips** [comment]
well you are using crate plugin to give something, this is not something what should even be related to CMI plugin.

**Comment by Steev93** [comment]
That has worked! Somehow missed this when doing the config. Thanks! :)
