### ISSUE TITLE
Teleport commands do not execute teleport

### ISSUE THREAD

**Issue by spathizilla** [Zrips/CMI#3018]
With teleporting commands like /warp and /home, in 8.6.21.0, they will execute any required warmup time and then not actually teleport the player. No errors are displayed both in game or on console. This was not an issue in previous versions.

[20:14:01 INFO]: CMI: 8.6.21.0 BungeeCord
[20:14:01 INFO]: Server version: Paper(155) 1.15.2-R0.1-SNAPSHOT
[20:14:01 INFO]: Vault version: 1.7.3-b

**Comment by Zrips** [comment]
Test new version 8.6.21.1, should be in working order
