### ISSUE TITLE
Cannot open offline inventories or interact with offline players at all when using a custom world directory

### ISSUE THREAD

**Issue by NightFuryStrike** [Zrips/CMI#3019]
**Description of issue:**
When using a custom world folder (such as by defining it in bukkit.yml), the plugin cannot access offline player data at all, and all commands involving offline players do not work, such as offline inventories. 

This issue started for all CMI versions beyond 8.6.20.2, most likely when this change was implemented:

- "New fix with a different approach to deal with a new issue on 1.15 servers when we are trying to get offline player data file"

Unfortunately due to this, I am stuck using CMI version 8.6.20.2 until this is fixed.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
To reproduce this issue, add the following to a new line in **bukkit.yml** under settings, and then make a folder with the name "worlds" in the server's main directory, and move your worlds into that folder (or allow the server to generate a new world in that folder):
```
settings:
  world-container: worlds
```
![image](https://user-images.githubusercontent.com/56176412/78189596-b583c300-7448-11ea-88a8-1deffc1843b2.png)

---

**Cmi Version (using`/cmi version`):** 
8.6.20.3 - 8.6.21.0

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper-155 (Minecraft 1.15.2)

**Comment by Zrips** [comment]
Good point here, will be fixed with next build.
