### ISSUE TITLE
Issue with cooldown:[TimeInSec]!

### ISSUE THREAD

**Issue by GrimPod** [Zrips/CMI#302]
Description of issue or feature request:

Specialised commands cooldown check doesn't seem to do anything
just seems to allow it every time

CONFIG SECTION (IGNORE IF NOT RELEVANT):

  test:
  - cooldown:5! cmi heal [playerName]

Cmi Version (using`/cmi version`): 7.6.10.1
Server Type (Spigot/Paperspigot/etc): Spigot 1.12.2
Server Version (using `/ver`): 1.12.2

**Comment by GrimPod** [comment]
well ive tried using it in a Custom alias, that gets ran by an item with the command attached, 
but ive also tried using it just in general with custom alias,
Tried to do 
- cooldown:60#! cmi heal [playerName]
- cmi feed [playerName]
(this is the moneycost example jut replaced money cost with the cooldown)
i tested it with a player with and without permission for both commands
-the one with permission and it healed and fed every time
=The one without permission got healed EVERYTIME and didnt have permission for feed 

So therefore according to the specialised commands page
   > if command starts with cooldown:[timeInSec]! then that line or any following ones (if defined) will have cooldown before reusing it. Example: cooldown:5! cmi heal [playerName] will heal player, but not more frequently than every 5sec.
This doesnt work as intended

**Comment by LogGits** [comment]
Confirmed not working. @GrimPod are you trying to delay the command's output or actually give a cooldown so they cant use the command after x seconds?

**Comment by GrimPod** [comment]
Trying to give it a cooldown so players can only do it every x seconds
 Tried setting it for the heal and feed in the cooldown section of the config but since its commands players don't have perms too I have to do it fromConsole! I believe this is also why the cooldown! won't work
Also tried just setting the cooldown! for the customalias in the config, which didn't work

**Comment by MCTyler** [comment]
Confirmed, Does not work in InteractiveCommand either.....
```
  Commands:
  - asConsole! cooldown:10! cmi counter start c:world:-1204:90:1120 t:5 -f r:100 msg:PvP_Start!
```
