### ISSUE TITLE
Limiteduse tag not working

### ISSUE THREAD

**Issue by mare-on** [Zrips/CMI#3020]
Hi, I want to create tool for changing time to day by using /cmi attachcommand, the full comamnd is: "cmi attachcommand !left!!cc!!limiteduse:3!cmi time day [worldName]" and... it doesn't work :/ When I'm using command "/cmi attachcommand !left!!cc!cmi time day [worldName]" it works great but there might be some issue about !limiteduse! tag.

I'm using:
CMI-8.6.21.1
Paper(143) 1.15.2-R0.1-SNAPSHOT
Vault 1.7.3

**Comment by NightFuryStrike** [comment]
Try /cmi attachcommand !limiteduse:3!;;!left!!cc!cmi time day [worldName]

**Comment by mare-on** [comment]
Oh thank you, this separation works

**Comment by mare-on** [comment]
I think we can now close this issue ;)
