### ISSUE TITLE
[Bug Report] '/cmi saveditems get' Issue - ★★★★

### ISSUE THREAD

**Issue by geumu** [Zrips/CMI#3023]
**Bukkit**: Catserver 1.12.2
**Plugin**: CMI8.6.21.1
**Bug Severity**: ★★★★
**Explanation**: Mod items cannot be summoned through saveditems. CMI8.6.15.0 can be summoned.
**Video**: https://youtu.be/INdbWdHbm74
**Pastebin**: https://pastebin.com/1zrVw29D

Thanks for your support
**Donate**: https://imgur.com/u9tqdQJ

**Comment by Zrips** [comment]
Should be fixed now.
