### ISSUE TITLE
Last update broke the tppos

### ISSUE THREAD

**Issue by RSLuke** [Zrips/CMI#3026]
**Description of issue:**

What happens when I click on the sign with this command :
https://puu.sh/Fsdsa/0e50c009a4.png
[14:40:21 INFO]: 0wayne has been teleported to (politicraft,0,64,1).
My IG ID is : __Lukee__ not 0wayne

With portals :
https://puu.sh/FsdtP/42388ba37f.png
[14:42:04 INFO]: Location defined incorrectly!

**Cmi Version (using`/cmi version`):** CMI8.6.21.1

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** [14:42:36 INFO]: This server is running Paper version git-Paper-651 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[14:42:36 INFO]: Previous version: git-Paper-650 (MC: 1.13.2)

**Comment by Zrips** [comment]
This might be due to recent change which would have accepted player name as a regular variable and -p:[name] type variable, which was made to accurately indicate players name. Will revert some previous changes and wee will have to keep this -p:[name] format
