### ISSUE TITLE
Home command teleport 'home unsafe' suffocation 8.6.21.1

### ISSUE THREAD

**Issue by SmallSansSerif** [Zrips/CMI#3027]
**Description of issue:**

On 8.6.21.1 noticed that players get a 'home is unsafe' suffocation message when they teleport now if there's carpet on the block.  So think something is more sensitive or broken.

**Cmi Version (using`/cmi version`):** 
8.6.21.1

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper version git-Paper-158 (MC: 1.15.2)

**Comment by x1p** [comment]
Indeed Very annoying bug.

**Comment by Zrips** [comment]
This should get fixed with todays update
