### ISSUE TITLE
Issue saving player money

### ISSUE THREAD

**Issue by AerWyn81** [Zrips/CMI#3028]
**Description of issue:**

Hi, since version 8.6.20.9 every time the server reboots, players lose or regain their money. There are **no errors** in the logs when stopping and starting the server. We have economy activity via CMI and database connection.

---

**LOG**
At restart :
```
[21:31:17] [Server thread/INFO]: [CMI] Disabling CMI v8.6.20.9
[21:31:17] [Server thread/INFO]: [Vault][Economy] CMI Economy unhooked.
[21:31:18] [Server thread/INFO]: [CMI] Closed db connections
```

At start : https://pastebin.com/XDqcDkHF

Money history of lambda player : 
Lost :
```
21:22:33 player lost -0.0 (43152.59)
21:22:33 player lost -0.0 (43152.59)
//RESTART
21:38:44 player lost -0.0 (28521.4)
21:38:44 player lost -0.0 (28521.4)
```

Regain:
```
19:11:23 player got 2937.59 (60162.85)
19:11:23 player got 2937.59 (60162.85)
19:11:36 player lost -0.0 (60162.85)
19:11:36 player lost -0.0 (60162.85)
19:12:03 player got 1393.19 (61556.05)
19:12:03 player got 1393.19 (61556.05)
19:12:13 player lost 60000.0 (1556.04)
19:12:13 player lost 60000.0 (1556.04)
19:12:22 player lost -0.0 (1556.04)
19:12:22 player lost -0.0 (1556.04)
21:14:57 player lost -0.0 (1556.04)
21:14:57 player lost -0.0 (1556.04)
21:30:09 player lost -0.0 (1556.04)
21:30:09 player lost -0.0 (1556.04)
//RESTART
22:01:41 player got 100.0 (55879.25)
22:01:41 player got 100.0 (55879.25)
```

---

**Cmi Version (using`/cmi version`):** 
CMI8.6.21.1
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Git-Paper-155 (latest)
**Vault Version :**
v1.7.3
**CMI Economy config :**
https://pastebin.com/q6JBQzw2

**Comment by Zrips** [comment]
Could you provide entry from a database related to this player? How does it look like at Economy column?

**Comment by AerWyn81** [comment]
Hi, the issue seems to occur "randomly" on different players every day. Yesterday morning, after the reboot, a player had lost his money, this morning he had no problems. 

Here are the data (up to date) for the player who had problems yesterday morning:
| id  | player_uuid                          | username  | nickname | LogOutLocation                             | DeathLocation                              | TeleportLocation                          | teleportToggled | Homes                                                 | LastLoginTime | LastLogoffTime | TotalPlayTime | tFly | tGod | Glow | Ips | Cuffed | AlertUntil | AlertReason | JoinedCounter | LockedIps | pTime | Kits                     | Charges | Cooldowns | Balance           | Notes | Rank | TagSound | SignShiftEdit | Spy | CommandSpy | BannedUntil | BannedAt | BannedBy | BanReason | Ignores | Vanish | Economy            | Mail | FlightCharge | UserMeta | Flying | Votifier | Jail | JailedUntil | FakeAccount | PlaytimeOptimized | flightChargeEnabled | noPayToggled | JailReason | Skin | SignSpy | Collision | NamePrefix | NameSuffix | Warnings | msgToggle | NameColor | Muted |
|-----|--------------------------------------|-----------|----------|--------------------------------------------|--------------------------------------------|-------------------------------------------|-----------------|-------------------------------------------------------|---------------|----------------|---------------|------|------|------|-----|--------|------------|-------------|---------------|-----------|-------|--------------------------|---------|-----------|-------------------|-------|------|----------|---------------|-----|------------|-------------|----------|----------|-----------|---------|--------|--------------------|------|--------------|----------|--------|----------|------|-------------|-------------|-------------------|---------------------|--------------|------------|------|---------|-----------|------------|------------|----------|-----------|-----------|-------|
| 337 | 69e6b12e-4806-492c-b268-f704cfd3e66a | jbdb81    | NULL     | world:0.53:100.0:0.43:1.88:1.02            | end:-201.68:-230.89:1549.12:9.29:72.78     | end:710.77:19.0:655.14:65.24:239.51       | 0               | home%%end:-1161.69:80.0:980.3:20.85:292.09;bed%%re... | 1585917894393 | 1585874824342  | 402795800     | NULL | NULL | NULL |     | 0      | NULL       | NULL        | 0             | NULL      | -1    | NULL                     | NULL    | NULL      | 19660.8           | NULL  | NULL | 1        | 0             | 0   | 0          | NULL        | NULL     | NULL     | NULL      |         | NULL   | CMIGlobal%%19660.8 | NULL | NULL         | NULL     | 0      | 0        | NULL | NULL        | 0           | 0                 | 0                   | 0            | NULL       | NULL | 0       | 1         | NULL       | NULL       | NULL     | 0         | NULL      | NULL  |

Here's the data from another player who had problems this morning:
| id  | player_uuid                          | username  | nickname | LogOutLocation                             | DeathLocation                              | TeleportLocation                          | teleportToggled | Homes                                           | LastLoginTime | LastLogoffTime | TotalPlayTime | tFly | tGod | Glow | Ips | Cuffed | AlertUntil | AlertReason | JoinedCounter | LockedIps | pTime | Kits                     | Charges | Cooldowns | Balance           | Notes | Rank | TagSound | SignShiftEdit | Spy | CommandSpy | BannedUntil | BannedAt | BannedBy | BanReason | Ignores | Vanish | Economy           | Mail | FlightCharge | UserMeta | Flying | Votifier | Jail | JailedUntil | FakeAccount | PlaytimeOptimized | flightChargeEnabled | noPayToggled | JailReason | Skin | SignSpy | Collision | NamePrefix | NameSuffix | Warnings | msgToggle | NameColor | Muted |
|-----|--------------------------------------|-----------|----------|--------------------------------------------|--------------------------------------------|-------------------------------------------|-----------------|-------------------------------------------------|---------------|----------------|---------------|------|------|------|-----|--------|------------|-------------|---------------|-----------|-------|--------------------------|---------|-----------|-------------------|-------|------|----------|---------------|-----|------------|-------------|----------|----------|-----------|---------|--------|-------------------|------|--------------|----------|--------|----------|------|-------------|-------------|-------------------|---------------------|--------------|------------|------|---------|-----------|------------|------------|----------|-----------|-----------|-------|
| 957 | 065437e7-b80f-423a-91f6-969db1b2dc0e | LeRoiAtsu | NULL     | melodya:-0.48:67.0:10.3:12.73:-191.27      | melodya:-2629.54:60.44:4061.5:-6.74:252.11 | melodya:-4561.3:77.0:2048.69:23.24:158.85 | 0               | Home%%melodya:-2650.71:68.0:4059.83:40.2:358.79 | 1585867430536 | 1585878305329  | 10866150      | NULL | NULL | NULL |     | 0      | NULL       | NULL        | 0             | NULL      | -1    | 1Mois-X-1%%1585868936354 | NULL    | NULL      | 6148.599999999988 | NULL  | NULL | 1        | 0             | 0   | 0          | NULL        | NULL     | NULL     | NULL      |         | NULL   | CMIGlobal%%6148.6 | NULL | NULL         | NULL     | 0      | 0        | NULL | NULL        | 0           | 0                 | 0                   | 0            | NULL       | NULL | 0       | 1         | NULL       | NULL       | NULL     | 0         | NULL      | NULL  |
| 958 | 065437e7-b80f-423a-91f6-969db1b2dc0e | LeRoiAtsu | NULL     | melodya:-2647.15:67.5:4060.3:14.54:-309.03 | melodya:-2642.24:65.0:4059.69:84.6:1.65    | nether:59.26:25.0:66.3:47.25:-281.69      | 0               | Home%%melodya:-2643.77:67.0:4059.28:48.0:-59.54 | 1585917980135 | 1585919457763  | 21624350      | NULL | NULL | NULL |     | 0      | NULL       | NULL        | 0             | NULL      | -1    | NULL                     | NULL    | NULL      | 465.5             | NULL  | NULL | 1        | 0             | 0   | 0          | NULL        | NULL     | NULL     | NULL      |         | NULL   | CMIGlobal%%465.5  | NULL | NULL         | NULL     | 0      | 0        | NULL | NULL        | 0           | 0                 | 0                   | 0            | NULL       | NULL | 0       | 1         | NULL       | NULL       | NULL     | 0         | NULL      | NULL  |

It looks pretty serious, we have about 150 duplicates entries in the database...

Today no errors CMI startup log : https://pastebin.com/KkqyTyf1
And no errors at stop : 
```
[05:02:36] [Server thread/INFO]: [CMI] Disabling CMI v8.6.21.1
[05:02:36] [Server thread/INFO]: [Vault][Economy] CMI Economy unhooked.
[05:02:36] [Server thread/INFO]: [CMI] Closed db connections
```

**Comment by Zrips** [comment]
Will be pushing out new version in next hour or so which should resolve issue with duplicates, tho you might need to perform duplicate cleaning with /cmi removeuser duplicates
if issue persists after next update, let me know.

**Comment by AerWyn81** [comment]
Hello again, sorry for reopening the issue. 

The money issue persists and even the command `/cmi removeuser duplicates` to remove duplicate players in the database, there are still about 150 duplicates left. 

During the execution of the command `/cmi removeuser duplicates` after the previous patch, only 7 entries were affected and deleted.
