### ISSUE TITLE
Private message through servers

### ISSUE THREAD

**Issue by pvvvo** [Zrips/CMI#3029]
**Description of issue:**
When you send a private message to another player of another server of the bungee with socialspy it says [playerDisplayName]

![image](https://user-images.githubusercontent.com/60686272/78317566-01ae3080-7539-11ea-8598-e88648bc2eb8.png)

**Cmi Version (using`/cmi version`): 8.6.21.1 - CMIB 1.0.0.4** 

**Server Type (Spigot/Paperspigot/etc): Tuinity 1.15.2** 

**Server Version (using `/ver`): Tuinity build 31**

**Comment by Zrips** [comment]
Will be fixed with next update
