### ISSUE TITLE
Already connecting to server!

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#303]
Description of issue or feature request:

#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR (IGNORE IF YOU HAVE NO ERROR):
```
####################
## PASTE ERROR HERE ##
####################
```

CONFIG SECTION (IGNORE IF NOT RELEVANT):
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

When I run /cmi server (servername) it says "Already connecting to this server!" 4 times in a row. It also seems to teleport me 4 times for some reason then tells me I logged in from another location. Is there any way to disable this message as well?

Cmi Version (using`/cmi version`):  7.6.12.0
Server Type (Spigot/Paperspigot/etc):  Latest Paper
Server Version (using `/ver`):  1.12.2

**Comment by 0xC1A551C** [comment]
3 servers with 4-6 players on the one I was on where i ran /cmi server. 0 players on the other two servers.

**Comment by Zrips** [comment]
Will make some simple changes, tho its strange that its behaving like this while using official API for that. Anyhow, test todays new version and come back if issue will be still there.
