### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by EchocallingEarth** [Zrips/CMI#3031]
**ArrayIndexOutOfBoundsException**

> [00:35:09 WARN]: java.lang.ArrayIndexOutOfBoundsException: 117
> [00:35:09 WARN]:        at org.sqlite.core.CorePreparedStatement.batch(CorePrepa
> a:130)
> [00:35:09 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.setInt(JDBC3P
> .java:329)
> [00:35:09 WARN]:        at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerMana
> [00:35:09 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBD
> [00:35:09 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DB
> )
> [00:35:09 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBMa
> [00:35:09 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.r
> a:84)
> [00:35:09 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncT
> ncTask.java:54)
> [00:35:09 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapp
> edulerReportingWrapper.java:22)
> [00:35:09 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
> [00:35:09 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
> [00:35:09 WARN]:        at java.lang.Thread.run(Unknown Source)
> 

_CMI version 8.6.21.1
Paper
15.2_

**Comment by Zrips** [comment]
Your error log is cut off, i need rest of it, especially part which follows after PlayerManager.savePlayerToDB(PlayerMana

**Comment by EchocallingEarth** [comment]
Due to a server outage issue, we lost our logs dating before 4/5/2020. This means I can not pull this exact log and our server is offline at the moment as we attempt to fix the issue that caused our outage. As soon as I am able to get our servers back online I will retest and provide a full log. Thank you for your attention to this matter.
