### ISSUE TITLE
Vanish Edit

### ISSUE THREAD

**Issue by Steev93** [Zrips/CMI#3033]
**Question: **

Now, this is the only plugin on the server handling /vanish but some reason when a users does vanish... The vanish boss bar only shows for some... Not all, or even for staff. No one has had access at all to /vanishedit 

Unsure if there is something that has been changed I don't know, Updated this, Added bossbar and flashlight. Doesn't seem to work for all at all...

**Comment by Zrips** [comment]
I needed to mention this, but it could not "work" if player already had its settings saved before hand. So you defaults will only apply if player had no saved settings for vanish mode.

**Comment by Steev93** [comment]
Is there anyway to wipe old settings?
