### ISSUE TITLE
/ignore or /cmi ignore not working

### ISSUE THREAD

**Issue by ChitterChatter** [Zrips/CMI#3037]
**Description of issue:**

Hi there, I have been told by my players that /ignore or /cmi ignore is not working.  The players do have the permission cmi.command.ignore

---
I don't have any errors, it just doesn't work.

---

**Cmi Version (using`/cmi version`):**   CMI8.6.21.1

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** 1.15.2

**Comment by DrakePork** [comment]
They might mean that it doesnt ignore the global chat, as that is an option you can enable/disable

**Comment by Zrips** [comment]
By default players you are ignoring you can still see their messages in global chat, you can enable this in config file. Other then this while you ignore someone, they cant send you private messages, send tp requests and similar things
