### ISSUE TITLE
[8.6.21.2] [paper-121+] Kits not being named correctly on new kit creaton in game

### ISSUE THREAD

**Issue by DXUltimate** [Zrips/CMI#3038]
**Description of issue:**

https://puu.sh/Ft06R/1ff0b6156b.png

Blocky symbols appear in the game after creating a new kit. More blocky symbols appear if you use capitalization in the kit names.

---

**Cmi Version (using`/cmi version`):** 

8.6.21.2

**Server Type (Spigot/Paperspigot/etc):** 

Paperspigot (paper 121+)

**Server Version (using `/ver`):** 

Previous version: git-Paper-121 (MC: 1.15.2)

**Comment by DXUltimate** [comment]
Additional image as shown in the GUI

https://i.imgur.com/SVULhPb.png

**Comment by Zrips** [comment]
My guess is that you have some chat plugin which modifies text you enter into chat box which contains some extra information which should not be present. Try testing without any plugins, so we could determine which one causes this and maybe even solution how we could fix it

**Comment by Zrips** [comment]
Will be using new system for getting chat entry, which maybe will resolve your issue, if not, let me know.
