### ISSUE TITLE
kitpreview shows armor badly 8.6.21.2

### ISSUE THREAD

**Issue by Caufland** [Zrips/CMI#3039]
**Description of issue:**

after entering kitpreview, the entire armor is not displayed, only the pants themselves     :D

here's a screenshot of what it looks like

https://ibb.co/9bypT94

**Cmi Version (using`/cmi version`):** 
CMI: 8.6.21.2 BungeeCord
Server version: Spigot 1.15.2-RO.1-SNAPSHOT
Vault version: 1.7.3-b(CMIEInjector)

**Server Type (Spigot/Paperspigot/etc):** 

spigot/bungeecord

**Server Version (using `/ver`):** 

git-Spigot-a03b1fd-95db423 (MC: 1.15.2) (Implementing API version 1.15.2-RO.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will be fixed with next build
