### ISSUE TITLE
kitcdreset and kitusagereset for all players

### ISSUE THREAD

**Issue by HuntingYoshi** [Zrips/CMI#3044]
**Description of issue or feature request:**
I was trying to reset the cd or usage for a specific kit for all player using console
but it return either player not found if trying to replace the player by @a or all
and if i dont input a player it will just do the same as just inputting /cmi kitcdreset
If a bug i'd like it fixed if its not a bug then it's a feature request

---

**Cmi Version (using`/cmi version`):**
8.6.21.1

**Server Type (Spigot/Paperspigot/etc):**
Paper(155)

**Server Version (using `/ver`):**
1.15.2

**Comment by Zrips** [comment]
Will add option to reset kit cd for everyone with next update
