### ISSUE TITLE
Problem about CMI brushing items

### ISSUE THREAD

**Issue by XiangZi-Sun** [Zrips/CMI#3047]
VehicleWorkArround in CMI:
Whether you set true or false, the mount will be teleported
Turn off VehicleWorkArround and see if the mount will teleport
No matter how it is set, it will be sent
Alpaca can be transported above the bedrock layer to brush items
But this setting in CMI is invalid, whether you set true or false will be transmitted
And can't interfere with physical transmission events
Today, I found that a player on my server has been riding an alpaca back and forth in the bedrock layer of hell.
But I do n’t understand the principle
I looked at his house and found a box of latent image boxes, full of diamond blocks and the like, and the end crystals all have 3000+
At least 8.16.x-the latest version of CMI, have this problem!
However, in the lower version of CMI, changing false to FALSE will not teleport
No lower version has tried

**Comment by Zrips** [comment]
This config option in general never got finished to begin with. If you want to prevent from players teleporting with mounts, then you will need to take away cmi.teleport.with.[entitytype] permission node from players.
