### ISSUE TITLE
Server Placeholder Breaks for staffmsg when used from other backend server on bungee network

### ISSUE THREAD

**Issue by RustyDagger** [Zrips/CMI#3048]
**Description of issue:**
I understand this is a very weird use case and a little tricky to get your head around. so ill do my best to explain.

network setup.
     [B]     
[S]      [G] 
All 3 have the respective CMI plugins both S and G are running the normal cmi and B is the bungee running the bungee CMI.

Now if server [G] runs the console command "staffmsg noob"
and a staff member is in server [S] this is what they see.

[Staff][[Senderdisplayname]] noob

however if the staff member was on the same server as the console that the command was ran on it shows up as 

[Staff][Server] noob 

https://i.gyazo.com/09700970853bbf88f6b4f1e267513930.png
---

---

**Cmi Version (using`/cmi version`):** 
https://gyazo.com/defcbb6e3371345bec54a5a2393b80a4

**Server Type (Spigot/Paperspigot/etc):** 
Bungee Network with paperspigot servers.
**Server Version (using `/ver`):** 
https://gyazo.com/32e6245b78e6265c60d6c7b7561f7b55

**Comment by Zrips** [comment]
Confirmed, will be fixed with next update
