### ISSUE TITLE
Custom crafting is Breaking, other crafting plugins. Option to disable PLEASE!

### ISSUE THREAD

**Issue by RustyDagger** [Zrips/CMI#3049]
**Description of feature/improvement request:**
Cmi's handling of custom crafting is piss poor ( sorry I love cmi but it really is BAD ) its utterly useless because for over 2 years its not had the ability to check the data of the items being used to make sure its correct this leads to unnammed items being used inplace of named items making cheating possible, so id be very surprised if its a heavy used feature. 

Now is also messing with another crafting system ( from custom items by jojodmo ) that plugin has a system to prevent the above mentioned issue but CMI is stepping all over it and allowing it still.
tested on a server with cmi and a server without to confirm this.

This issue is kind of a duplicate of but expanded to disable... #2800 
---
### Detailed explanation of what it should do, when and in what situation: ###
Turn off all Custom Crafting code. from the modules file.
### Basic explanation as to why this feature is needed and/or useful to have: ###
so it stops breaking other plugins that do a better job.

**Comment by Zrips** [comment]
Custom recipes creates real recipes and adds them to the server recipe list. Everything after this is handled by server itself. Custom recipes can only accept as ingredients material name and where it should be located in crafting window, thats it. This is not CMI limitation, this is minecraft limitation. For this to handle it completely and check items name, lore or any other information i would need to recreate entire recipe handling engine and improve on it to make it possible. At this point i have no plans in creating this inside CMI, maybe as a separate plugin at some point, but this feature remains basic.

**Comment by RustyDagger** [comment]
Other plugins have done this feature for them self thats great BUT CMI IS BREAKING THAT PLUGIN!
I need a way to disable cmi's custom crafting

If you wish i can prove cmi is breaking the other plugin. something in CMI is allowing things to be crafted that the other plugin stops. I need a way to turn off CMI from touching crafting. 

I dont want you to fix your crafting i want to disable it.

**Comment by RustyDagger** [comment]
YOUR priority that you are using to check the items in the grid is Taking that event and stopping other plugins using it,

**Comment by Zrips** [comment]
I will happily fix/add disable button to something what could actually control crafting, but CMI doesnt do that. I'm literally registering new recipe with official API
`Bukkit.getServer().addRecipe(recipe);`
and that's that. I'm not listening to any events related to crafting which would prevent you from getting results. Maybe some other part of code causing some compatibility issues, but not custom recipes.

**Comment by RustyDagger** [comment]
its not stopping me getting results its allowing recipes that are not ment to work to work. its like the other plugin cant cancel the grabbing of the output item.

**Comment by Zrips** [comment]
it is possible that we have some compatibility issue which is not really a fault of ether plugin. But in general this is not caused by custom recipe in particular, it maybe could be caused by another part of code, but without actual extensive testing i cant really say anything certain about this one. But once again, it is 4MB plugin, but i cant recall any code which would manipulate anything related to crafting table, especially manipulation of crafting results. I have only one instance in entire plugin PrepareItemCraftEvent which basically prevents item pickups if you have crafting window open and which only works when glitch protection is activated. other then this, i have no idea.
