### ISSUE TITLE
Time played based statistics

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#305]
No longer any way to show the player total time based on the statistics.

For the ranks system to work properly, I need the system to use the time played according to the statistics and not the traked by CMI.

CMI 7.7.0.0
Spigot 1.12.2-R0.1-SNAPSHOT #1557
CraftBukkit version git-Spigot-eadd615-bea5a84 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
@C4BR3R4 
So what results are you getting with 
PlayTimeFromStats: true
setting?

**Comment by C4BR3R4** [comment]
Yes.

**Comment by Zrips** [comment]
"Yes" is not a answer for question what results you are getting :) When set to true you should get same playtime you can see when pressing ESC button and going into statistics. Does those match?

**Comment by MCTyler** [comment]
It does Match.

**Comment by C4BR3R4** [comment]
Sorry answer. Yes same playtime.

The problem was when changing the configuration, the changes were not applied until the server was restarted. Using the command /cmi reload does not apply the changes.

**Comment by Zrips** [comment]
@C4BR3R4 Yea, playtime is not being updated for offline players and full restart is needed. This is simply to lower down load when checking data for offline player which requires file loading what is not end of world, but in case you would perform playtimetop and would want to load playtime for 20k+ players, that would take quite some time to process. 
Closing this one.
