### ISSUE TITLE
prewards showing incorrect timings

### ISSUE THREAD

**Issue by Weymouth87** [Zrips/CMI#3050]
**Description of issue:**
I have my rewards configured as follows https://pastebin.com/Z7sAV1eh However, when i use /prewards the timings are incorrectly shown. For example, my hourly reward (set to 3600 seconds) shows its ready in over an hour. Shown here: https://prnt.sc/rt285g

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
hourly1:
  DisplayName: "&7Hourly reward"
  AutoClaim: true
  Description:
  - "&2Get reward for every hour you are online"
  - "&2Free heal and 10 coins into your pocket"
  PayEvery: 3600
  Commands:
  - asConsole! cmi heal [playerName] -s
  - asConsole! eco give [playerName] 10
daily1:
  DisplayName: "&7Daily reward"
  AutoClaim: true
  Description:
  - "&2Get reward for every 24 hours of playtime"
  - "&2250 coins into your pocket!"
  PayEvery: 86400
  Commands:
  - asConsole! eco give [playerName] 250
6hour:
  DisplayName: "&f6 hour reward"
  AutoClaim: false
  Description:
  - "&2Get reward for 6 hour's you have been online"
  - "&250 coins into your pocket!"
  PayFor: 21600
  Commands:
  - asConsole! eco give [playerName] 50
12hour:
  DisplayName: "&f12 hour reward"
  AutoClaim: false
  Description:
  - "&2Get reward for 12 hour's you have been online"
  - "&2100 coins into your pocket!"
  PayFor: 43200
  Commands:
  - asConsole! cmi money give [playerName] 100
7days:
  DisplayName: "&f7 day reward"
  AutoClaim: false
  Description:
  - "&2Get reward for 7 days you have been online"
  - "&21000 coins into your pocket!"
  PayFor: 604800
  Commands:
  - asConsole! eco give [playerName] 1000
30days:
  DisplayName: "&f30 day reward"
  AutoClaim: false
  Description:
  - "&2Get reward for 30 days you have been online"
  - "&25000 coins into your pocket!"
  PayFor: 2592000
  Commands:
  - asConsole! eco give [playerName] 5000

---

**Cmi Version (using`/cmi version`):**  8.6.21.2

**Server Type (Spigot/Paperspigot/etc):** Paper(102) 1.15.2

**Server Version (using `/ver`):** 1.15.2

**Relevant plugins (Delete if this isn't needed):**
Not sure if any of these could be causing the problem so uncluded just incase.

Plugins (55): Advanced_Drop_Party, BetterBees, BetterRTP, ChatColor, ChatReaction, ClearLag, CMI, Coins, CoreProtect, CustomRecipeAPI, DeepStoragePlus, DeluxeChat, DeluxeTags, Disenchant-2, Doorbells, EditableSign, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EssentialsXMPP, FurnaceNotify, Graves, GriefPrevention, HolographicDisplays, HolographicScoreboard, IngotBlock, LeaderHeadsRevamped, LuckPerms, MeltDown, Minepacks, MiniaturePets, MiningBlocks, MoonGenerator, MovingDevApi, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, MyDog, Parrots, PlaceholderAPI, PlugMan, ProtocolLib, RainbowBlocks, Referral, ShopChest, TabList, TreeGravity, UltraCosmetics, Vault, WorldBorder, WorldEdit, WorldGuard, zDiscord

**Comment by rybuilder23** [comment]
i have the same problem on 1.16.4 
https://postimg.cc/gXc72znc

my reward is set for 4 hours 
but it shows the player needs to wait 7 hours
