### ISSUE TITLE
Elevator sign doesn't teleport up

### ISSUE THREAD

**Issue by therealatsuga** [Zrips/CMI#3051]
The elevator signs only do work "downstairs". Sometimes it's not possible to teleport upwards, doesn't matter if the location is safe. 

**Cmi Version (using`/cmi version`):** 
8.6.21.2 Bungeecord
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
126
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Will issue some fix related to this with next update. If issue remain for you, could you make another ticked and provide a picture of exact location which one dint worked for you when teleporting up.
