### ISSUE TITLE
Error MySQL new player

### ISSUE THREAD

**Issue by istarengwa** [Zrips/CMI#3053]
**Description of issue:**

when a new player connects to my server, I have this error in my console

**ERROR (DELETE IF YOU HAVE NO ERROR):**

https://pastebin.com/n3ZEmFQD

**Cmi Version (8.6.21.2):** 

**Server Type (Paperspigot):** 

**Server Version (162):**

**Comment by Zrips** [comment]
Can you show me startup log of CMI? Or atleast indicate exact version/type of your mysql database?

**Comment by istarengwa** [comment]
Mysql database : https://pastebin.com/cda43rAr

log CMI : https://pastebin.com/LifPYCYc

**Comment by Relaxing9** [comment]
I have the same error https://pastebin.com/RyBti1pa on CMI Version 8.6.22.0, my case is different since the player fails to get added due to not being whitelisted though. 
![image](https://user-images.githubusercontent.com/41935047/79020109-ed27f480-7b45-11ea-90e0-23f48d9adc3b.png)

**Comment by istarengwa** [comment]
Still on a new player today 

https://pastebin.com/Cfvah2iP

**Comment by Zrips** [comment]
Should be resolved
