### ISSUE TITLE
[Feature Request] Placeholder for /glow

### ISSUE THREAD

**Issue by MrPranklez** [Zrips/CMI#3059]
**Description of issue or feature request:**

Add a placeholder for /glow. So if you would like players to have their displayname in chat or in the tablist have the same color so this could be done using the placeholder

example: %cmi_glow%

**Cmi Version (using`/cmi version`): 8.6.21.5** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`): git-Paper-145**

**Comment by mrfloris** [comment]
I am on CMI `8.6.22.1` currently and `/cmi placeholders` (page 5) has glow placeholders.
<img width="506" alt="Screenshot 2020-04-12 at 04 15 58" src="https://user-images.githubusercontent.com/28841349/79058947-7c332a80-7c74-11ea-9b2a-539497ff299d.png">

**Comment by MrPranklez** [comment]
already implemented
