### ISSUE TITLE
Bad regex for "ipblock" and "open." not blocked in web links. + bypass permission not working.

### ISSUE THREAD

**Issue by ScuroK** [Zrips/CMI#306]
Description of issue or feature request:

I found that if i enable "ipblock" for the chat filter, phrases like this get blocked in chat: "some.word.with.dots"

Here is what i had to do in order to fix this problem. I had to remove the default regex from the ipblock-section and copy the "regex2" from above like this:

```
ChatFilter:
Enabled: true
Deny:
ipBlock:
# If not set to true, this filter will not be used
Enabled: true
# Defines filter group and defines required permission node to bypass this filter: cmi.chatfilter.bypass.[groupName]
Group: Advertising
# Regex expresion to filter by. How to use regex https://regexone.com/
Regex:
- (https?://(?:www.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9].[^\s]{2,}|www.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9].[^\s]{2,}|https?://(?:www.|(?!www))[a-zA-Z0-9].[^\s]{2,}|www.[a-zA-Z0-9].[^\s]{2,})
```
So now my whole config looks like this:
https://pastebin.com/xBJCszeZ

Now "some.word.with.dots" wont get blocked anymore BUT players are still able to post links by using "**open.linkhere**" in the beginning of the weblinks.

How can "open." be blocked aswell? And could you change the default "ipblock" value to a working regex? 

Can you please improve the weblink and ip- blocking system and make it more user friendly?

And **another** problem is that i cant post links in chat even i have the bypass permission for advertising AND im OP. 

Cmi Version (using`/cmi version`):
7.7.0.0
Server Type (Spigot/Paperspigot/etc): 
Spigot 1.12.2

**Comment by ScuroK** [comment]
@Zrips some feedback would be nice. 
I really need a working solution to block links but not the normal chat

**Comment by Zrips** [comment]
@ScuroK Well there comes that thing that you have "some.word.with.dots" what should be legit sentence, even if its malformed. But then how we could separate it from actual spam link? like "spam.google.com" which is in same form. In general players should understand that writing one longer sentence with appropriate formatting is way to go and not bunch of words stacks together and separate with dots to look exactly like link. 
There are some regex online you could try to use and maybe find one you like. But there is no perfect one as you will always have to trade something out to get something back.
More strict regex will result in more detection, but this will increase false/positives while letting to use "some.word.with.dots" will result in some link spams.

**Comment by Zrips** [comment]
Try out this regex
`[a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,|_|\/)\s?([a-zA-Z]{2}|aero|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel)\b`

**Comment by ScuroK** [comment]
@Zrips 
how about an additional option to force spaces after a "."
this would not stop links from appearing in chat but makes them unclickable. Just like essentials removed the dows within links. this would be an easy option for those who dont want to mess arround with regex.

And another problem is that i cant post links in chat even i have the bypass permission for advertising AND im OP. can you have a look on it please?

**Comment by ScuroK** [comment]
i mean you could do it like this:
if letters or numbers follow a "." it shall replace "." with ". "

if other symbols follow (for example "-.-") it should keep it like it is.

**Comment by Zrips** [comment]
That replacement you can achieve with regex. 
For links, double check if you have access to permission with /cmi haspermission [playerName] cmi.chatfilter.bypass.Advertising

**Comment by ScuroK** [comment]
Or do you have a regex for me that just blocks links (including „open.link“) 
and nothing but links?

**Comment by MCTyler** [comment]
Wasn't that EXACTLY @Zrips statement?

**Comment by ScuroK** [comment]
well then.. if nobody is able to solve it im gonna use a working plugin for it..

**Comment by ScuroK** [comment]
uisng this works just fine:
https://www.spigotmc.org/resources/antiadvertiser.47506/

and no need to mess around with regex.

**Comment by Zrips** [comment]
@ScuroK that AntiAdvertiser doesn't require regex simply because its not allowing you to change it. its still using one when detecting urls, its just hard coded into plugin. And its using generic regex which will not detect simple bypasable links like google(dot)com.
Thing is that i did tested with Luckperms plugin and links are being blocked when you don't have cmi.chatfilter.bypass.Advertising and you can post links with that permission node. Given directly or throw permission group.
As complex regex looks, its only way to detect links in text. Default regex should detect most of them.

And can you repaste your current config section for chat filter?

**Comment by ScuroK** [comment]
@Zrips Did you recently change anything. AntiAdvertiser cant block links anymore and i get this "[LINK]" replacement.

**Comment by MCTyler** [comment]
Why not just BAN the Players violating the rules?

**Comment by ScuroK** [comment]
i know you want to be helpful MCTyler but its not very helpful if you comment every phrase people write in here. better do this on the forum.

**Comment by ScuroK** [comment]
i think i found the cause of my original problem:

if the regex for short word- replacement is the same like the one in the chatfilter section it seems to be conflicting.

**Comment by ScuroK** [comment]
jup now it works.

**Comment by MCTyler** [comment]
This is a forum.

**Comment by ScuroK** [comment]
i found the permissions problem:
i could not bypass because i had replaceWith: '  ' instead of ''.
after changing this it works.

closing this ticket for now because its full of irrelevant comments.
