### ISSUE TITLE
Database issues

### ISSUE THREAD

**Issue by Angrydave1987** [Zrips/CMI#3060]
Hello, i am unsure if this is more of a question or a bug.

I am currently experience issues with mobs/animals becoming non responsive anywhere in the world (they still move around as normal, but do no target player (almost as if we're in creative mode) my server difficulty is on hard, this has recently only just happened. only setting that has been touched recently was doing portals and some particles. other than that, cmi has been in from day 1 weeks ago and never an issue.

Cmi Version @ the time was 8.6.21.2
Paper version 162
ServerMC version 1.15.2

Attached is my database.  and also attached my CMI folder (minus the database)
[cmi.sqlite.zip](https://github.com/Zrips/CMI/files/4440927/cmi.sqlite.zip)
[CMI.zip](https://github.com/Zrips/CMI/files/4440935/CMI.zip)

**Comment by mrfloris** [comment]
Usually when people come to me saying that it all seems perfectly fine but mods are just frozen in time, it turns out clearLagg or some other optimization tps fixing plugin is triggered when tps hit a dip and they disabled move event

**Comment by Angrydave1987** [comment]
I will have a look, but i have no clearLagg plugins on my server. 

Paper.yml / spigot.yml / bukkit.yml are all default settings (only thing that has changed is i allowed 0tick farms to work) which won't effect anything.
