### ISSUE TITLE
New players not given kit

### ISSUE THREAD

**Issue by spathizilla** [Zrips/CMI#3061]
**Description of issue:**
When a new player joins the server they are usually given the Newbie kit (per default config). However this does not happen with 8.6.21.5. I even tried giving them cmi.kit.newbie without success but they could then later do /kit newbie.

**CONFIG SECTION:**
```
Newbie:
  # Kit name to give for new players joining server
  Kit: Newbie
```

---

Paper version git-Paper-161 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
CMI v8.6.21.5

**Comment by pvvvo** [comment]
Oh, same here, i thought it was my mistake.

**Comment by WhatsTheBadNews** [comment]
Same issue on my server

**Comment by spathizilla** [comment]
Also tested on a complete barebones server to discount any plugin conflicts. No newbie kit given on first join.

**Comment by InDirectVariant** [comment]
Same issue on my server

**Comment by SmallSansSerif** [comment]
I can confirm this too.

**Comment by XXY218** [comment]
Same issue on my server

**Comment by Sikatsu** [comment]
Can confirm

**Comment by mrfloris** [comment]
`Fix for recent update disabling first join kit give out`
Please upgrade to `CIM 8.6.22.1` or newer and see if it's fixed?
The changelog implies this should be sorted out now.

**Comment by InDirectVariant** [comment]
Issue resolved on my server

**Comment by Zrips** [comment]
Should be fixed
