### ISSUE TITLE
/near command not pointing

### ISSUE THREAD

**Issue by pvvvo** [Zrips/CMI#3062]
Command /near it's supossed to point a player when you click the name, i checked if it was the permission and is not that, even with OP or cmi.* can't click the players name displayed to show me the way, it was working before tho. I also checked my config.yml in the near section and it was okay.

**Cmi Version (using`/cmi version`): 8.6.21.5** 

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): 162**

**Comment by RustyDagger** [comment]
there was something about /point in a recent update something about it not pointing exactly to a player but just towards? maybe he broke it but i think its just changed.

**Comment by Zrips** [comment]
In recent updates /near will not point to the player if you have set Approximate in config file. As it defeats entire purpose of having approximate distance to the player if you can point to him with pinpoint accuracy. Well, i can some what rollback change and make this one optional, in case you still want to point directly to the player. Next update.
