### ISSUE TITLE
Bungee Chat not working

### ISSUE THREAD

**Issue by Ahmadh26** [Zrips/CMI#3067]
**Question: **
Hello, i have a bungee network and have CMI installed on my servers along with CMIBungee on my bungee. the bungee chat isn't working although it has been enabled in the config of all the servers. what could be the issue?

i've attached my current config file. i'm running the latest version found on spigot website.

servers are running paper-166, with minecraft version 1.15.2.

[config.zip](https://github.com/Zrips/CMI/files/4443135/config.zip)

**Comment by RustyDagger** [comment]
Mine is also not working but i put that down to me using a chat manager ( deluxe chat ) its not something I was super keen on so no big loss for me.

is your /staffmsg working across the network? and what about /cmi msg <player>

**Comment by Ahmadh26** [comment]
Rusty, You are the reason i bought CMI!! thank you for showing me this amazing plugin :) !! (I'm Jayy btw if you remember me on discord)
Yes msg and staffmsg work cross server but not the normal text. i used to have multichat but i removed it in favour of CMI... trying to make it work

**Comment by RustyDagger** [comment]
Oh cool :D  Iv taken a quick look at your config all seems good ( is the chat formatting working like colors placeholder etc locally?) also make sure you have both Servers with the config settings set the same. I know my staff msg didnt work until I did that. I dont think moduls.yml has any thing related to bungee in it im out of ideas :/

**Comment by Ahmadh26** [comment]
Yes the formatting is working, i have exactly the same config on all the servers as i edited everything locally and then started the upload to the servers (basically uploaded the same configs everywhere along with modules and other files) .. 

i really don't want to revert back to multiChat 0_0

**Comment by mrfloris** [comment]
Jay, can you share your CMI's config.yml and modules.yml file please? (attach to ticket as .zip maybe)

**Comment by Ahmadh26** [comment]
any update on this? :/
