### ISSUE TITLE
Issues when player join and MYSQL tables

### ISSUE THREAD

**Issue by maxlehot1234** [Zrips/CMI#3069]
**Description of issue:**
Hi Zrips, I have an issue sometimes when players join the server:
https://gist.github.com/maxlehot1234/39b529cbd3db4be7e141355d5193082a

**Cmi Version (using`/cmi version`):** 8.6.21.15

**Server Type (Spigot/Paperspigot/etc):** PapermC 1.15.2 build 161

**Server Version (using `/ver`):** Java 11

Thanks again

**Comment by maxlehot1234** [comment]
Anything on this, since it occured a lot of times per day

**Comment by maxlehot1234** [comment]
@Zrips 

Anything on this. Its quite weird to have this error in the console each time a NEW player join

**Comment by Zrips** [comment]
Should be resolved
