### ISSUE TITLE
CMI x2 private message on same server

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#307]
CMI version: 7.7.0.0
Server Type (Spigot/Paperspigot/etc):  Newest paperspigot 
Server Version (using `/ver`): 1.12.2
No console error.

If players type /msg on server where players is on the same server he get's the message 2 times xD. However if you message between the bungee so from survival to skyblock for example it send only one message xD.

![cmi issue](https://user-images.githubusercontent.com/1558228/39366450-dc1afd74-4a2b-11e8-966e-d718b4ec464d.png)

**Comment by Zrips** [comment]
Will try to reproduce and determine cause of that tomorrow.

**Comment by Zrips** [comment]
Should be fixed with next update today.
