### ISSUE TITLE
Players can copy Admin sign shops with "/cmi sc"

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#3070]
**Description of issue:**
Players can use the command "/cmi sc" to duplicate any admin sign shop. The sign shop would work since its a duplicated sign. They should not have access to sign copy any admin related sign shop.

---

**Cmi Version (using`/cmi version`):** 
8.6.21.5

**Server Type (Spigot/Paperspigot/etc):** 
Paper Spigot

**Server Version (using `/ver`):** 
git-Paper-155 (MC 1.15.2)

**Relevant plugins (Delete if this isn't needed):**
https://www.spigotmc.org/resources/chestshop.51856/

**Comment by mrfloris** [comment]
Isn't SC a tool for staff and not for players? 
I don't know how cmi would know if one sign is any different than another, unless it's made with cmi itself (but i dont think sc would check for that)

**Comment by BboyZeroOne** [comment]
Well, it could also be a tool for players isn't it? Unless I'm wrong. Regardless, it shouldn't copy signs from other plugins.

**Comment by kadenscott** [comment]
It has no way to know that a sign is from another plugin though.

**Comment by Zrips** [comment]
Will introduce somewhat workaround for this one, should help out

**Comment by BboyZeroOne** [comment]
Hmm, the latest update still allows players to /sc on admin shop signs though.
