### ISSUE TITLE
elevator broken

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#3072]
use cmi elevator Send up Teleport , Won't appear in the right place

**Cmi Version (using`/cmi version`):** 8.6.21.5

**Server Type (Spigot/Paperspigot/etc):**  paper

**Server Version (using `/ver`):**  all ver happen

**Comment by p82183645** [comment]
8.6.22.0 still broken

**Comment by mrfloris** [comment]
`Fix for elevator signs wanting to place you to low or to high if you are in creative/spectator mode`
The .0 implies it's fixed, can you try 8.6.22.1 and see if it's still happening to you in creative/survival ?

**Comment by thunderlight411** [comment]
elevator is not working when there is no rooftop above the latest sign

**Comment by Zrips** [comment]
A secondary update is coming out today with some minor changes.
