### ISSUE TITLE
The compass is not working properly

### ISSUE THREAD

**Issue by Ksewedo5** [Zrips/CMI#3074]
I have configured the plugin in such a way that the player must hold a compass in his hand so that the dragon bar is displayed. The dragon strap does not disappear when the item changes
Google Translator

Config: https://pastebin.com/ZSTVMjYM
Cmi Version: 8.6.20.8
Server Type : Paper(143) 1.15.2-RO.1-Snapshot

**Comment by Ksewedo5** [comment]
During further tests I came across another error, the bar began to disappear ... but sometimes several bars appear
![Screenshot_1](https://user-images.githubusercontent.com/54962940/78786547-3858d080-79a9-11ea-9f68-143b3997df10.png)

**Comment by Zrips** [comment]
Should be fixed with next update
