### ISSUE TITLE
cmi rt issues since update 

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#3078]
**Description of issue:**

cmi rt is now almost always killing my players by porting them into walls. 

---

**Cmi Version (using`/cmi version`):** 
Started 8.6.21.3, currently on 8.6.21.5

**Server Type (Spigot/Paperspigot/etc):** 
paper 1.15.2

**Comment by mrfloris** [comment]
Hi there,

I believe the .4 release had this fixed?

Can you upgrade to the latest version .22.1 or newer, and see if it is fixed for you now? Looking forward to hear if it's resolved for your server.

**Comment by Zrips** [comment]
.4 did had some fixes related to this and new version will have some extra ones, so update to the latest one and if issue persists, let me know.
