### ISSUE TITLE
Teleport to other Wolds and send other 

### ISSUE THREAD

**Issue by jannikrouthe** [Zrips/CMI#3079]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###

I Will like to have /tpw so we cant teleport to a other wold and a /tpw %player% %wold% so we also Can send other players

**Comment by mrfloris** [comment]
```
/cmi rt
/cmi tpallworld
/cmi tppos
/cmi tpopos
/cmi world
and /cmi tp / tpa
```

These all support world teleporting?

You can make a custom alias to use /tpw if you want, with a command like:
`asConsole! cmi tppos -p:[playerName] 100 70 100 %world% -rng`

```
tppos (-p:playerName) [x] [y] [z] (world) (pitch) (yaw) (-rng:[range])
Teleports to location

-p: will define player you want to teleport. This will require you to have cmi.command.tppos.others permission node

-rng: will teleport at random location from center point by given radius

x, y and z can be in relative coordinates. In example /tppos ~0 ~1 ~0 will teleport you 1 block up
```

**Comment by CloudeLecaw** [comment]
i agree with mrfloris a tpw normaly is not needed because all current TP commands allready support the worldargument.
