### ISSUE TITLE
Teleport thinks half-slabs are unsafe and triggers /tpbypass 

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#3081]
There is an issue with all teleport thinking half-slabs are dangerous, and triggers /tpbypass 

Video:
https://www.youtube.com/watch?v=caXyCADWUfY

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 1.12.2 Paper

**Server Version (using `/ver`):** 8.6.21.5

**Comment by Zrips** [comment]
Should be working correctly with latest builds
