### ISSUE TITLE
/jump command not working properly

### ISSUE THREAD

**Issue by pvvvo** [Zrips/CMI#3082]
**Description of issue:**
I changed the config.yml in the section of jump to 25 and now isn't working.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
##   Teleport:
    SafeLocationDownThenUp: false
    ToSpawnBefore: false
    SwitchPlaces: true
    CurrentLoc: true
    JumpDefault: 25  ##
#######################################
```

---

**Cmi Version (using`/cmi version`): 8.6.22.0** 

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): 165**

**Comment by Zrips** [comment]
Good point, will fix this with next update
