### ISSUE TITLE
Tab completion for offline player

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#3084]
The writing of player names is not always easy. Some players mix up a disastrous alphabet soup. For this reason it would be very cool if one could tab complete offline players. Since the playerdata folder is very well populated, one might consider to only add tab completion for players who were online in the last 24 hours. 
What do you think about the idea? Is it technically realizable without further ado?

**Comment by Zrips** [comment]
Yes and no. I mean, we could store player names who played in last X hours, this is not hard. But we could be looking at hundreds or even thousands of possible entries on a bigger server, which means that we will need to send to client all this information when they will want to tabcomplete some ones name. Maybe if we would keep this optional or even automatically resize it if list of players gets over treshold, but still. Its quite a big list to be sent each time.
