### ISSUE TITLE
Placeholder Holograms

### ISSUE THREAD

**Issue by Steev93** [Zrips/CMI#3087]
**Question: **

Just mentioned the placeholder commands for "head" were wrong, Please advise of correct format as this seems to work?

http://prntscr.com/rxbmgw

`Wild:
  Loc: World;-18.67;128.22;0.48
  Interval: 1.0
  Range: 25
  RangeExtra: 25
  Spacing: 0.3
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&a&k***&r &5&l%cmi_user_name% &5Jump in &a&k***&r'
  - '&a&k***&r &u&lWILD PORTAL &a&k***'
  - ICON:head:%cmi_user_name%`

**Comment by Zrips** [comment]
This should be working correctly, tho your last line missing ' at beginning, maybe it copy/paste error, but still, if there is none in your config file, add it.
