### ISSUE TITLE
Warp Signs

### ISSUE THREAD

**Issue by Steev93** [Zrips/CMI#3088]
**Description of feature/improvement request:**
Can you make it a lot easier to create Warp Signs, like essentials, can but with CMI?

---
### Detailed explanation of what it should do, when and in what situation: ###
An easier and shorter method

### Basic explanation as to why this feature is needed and/or useful to have: ###
Great for warp signs for players to use

**Comment by mrfloris** [comment]
You can give players the permission `cmi.interactivesign.[icname]` like `cmi.interactivesign.warps`
And make an interactive sign like `/cmi ic` that's called warps, with the command `asConsole! cmi warp $1 [playerName]` (and set it to public:true and requires permission)

Now when a player makes a sign with the first line [warps] and the second line planet

Then when someone interacts with it, they will teleport to warp planet

You have to make it once, then players with the permission to place signs for warps easily.

Additional permissions for creating warps can be done for commands like /cmi setwarp.

https://youtu.be/Z-z0qKmJnMk

**Comment by Steev93** [comment]
> You can give players the permission `cmi.interactivesign.[icname]` like `cmi.interactivesign.warps`
> And make an interactive sign like `/cmi ic` that's called warps, with the command `asConsole! cmi warp $1 [playerName]` (and set it to public:true and requires permission)
> 
> Now when a player makes a sign with the first line [warps] and the second line planet
> 
> Then when someone interacts with it, they will teleport to warp planet
> 
> You have to make it once, then players with the permission to place signs for warps easily.
> 
> Additional permissions for creating warps can be done for commands like /cmi setwarp.
> 
> https://youtu.be/Z-z0qKmJnMk

You make this heaps easier, but how do I make the signs work without having to do [ic:warps]
http://prntscr.com/rxqmuv

**Comment by mrfloris** [comment]
```
InteractiveCommands:
  # Regex used in recognizing public interactive commands used in signs
  # Default format is [ic:[icName]] in example [ic:trash]
  # If you want clean format use regex like: (\[([a-zA-Z0-9]+)\])
  SignRegex: (\[([a-zA-Z0-9]+)\])
```
config.yml

**Comment by Steev93** [comment]
> ```
> InteractiveCommands:
>   # Regex used in recognizing public interactive commands used in signs
>   # Default format is [ic:[icName]] in example [ic:trash]
>   # If you want clean format use regex like: (\[([a-zA-Z0-9]+)\])
>   SignRegex: (\[([a-zA-Z0-9]+)\])
> ```
> 
> config.yml

Is there a way to make this a permanent color so it always goes to a blue or red or something as atm I'm doing

&1[Warps]

**Comment by mrfloris** [comment]
I think you can change the lines of text in that same editor, so upon placement, it will replace the sign with the preset text, i think.. worth testing. have fun!

**Comment by Zrips** [comment]
@Steev93 
Like mrfloris said, you can do all this and then simply change sign lines in same IC editor to something like
![image](https://user-images.githubusercontent.com/10416201/79109449-049ef180-7d81-11ea-9cbb-e356a1015ad9.png)
which by itself will colorize sign with has lines like
![image](https://user-images.githubusercontent.com/10416201/79109501-21d3c000-7d81-11ea-86e2-8bec276d2d87.png)
into this
![image](https://user-images.githubusercontent.com/10416201/79109525-2f894580-7d81-11ea-8a35-2583ed9dee45.png)
