### ISSUE TITLE
[Suggestion] Could /seen display months as well?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3091]
Currently it seems if someone's been away over 365 days, it becomes 1 year. It doesn't however say that 37 days ago was 1 month and 1 week ago.

It has year / days / hours
It doesn't seem to have years / months / weeks / days / hours.

**Comment by Zrips** [comment]
In general its to shorten output line. Having something like: **1 year 5 months 6 days 3 hours 25 minutes 55 seconds** can be quite long line, we could even get rid of years and end up with basic: **521 days 3 hours 25 minutes 55 seconds** and its using same generic time formating which is used across entire plugin for simplicity sake. If you have a better idea how to show bigger dates in relatively short format, i will gladly change it.
