### ISSUE TITLE
Vanish

### ISSUE THREAD

**Issue by Steev93** [Zrips/CMI#3093]
**Description of issue:**
When players are in vanish, they can build in their own regions for some reason?

Also /vanish [PlayerName] off

Only turns off vanish for me not for the player I have selected. 

---

**Cmi Version (using`/cmi version`):** 
8.6.22.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-137

**Comment by Zrips** [comment]
Actually it turns vanish mode correctly, its only feedback message which shows incorrect name, will fix that with next build.

**Comment by Zrips** [comment]
Och and for building in their own regions. I have no idea why its a bug if they can build in their own regions.
