### ISSUE TITLE
GeoLite

### ISSUE THREAD

**Issue by Steev93** [Zrips/CMI#3096]
**Question: **
`  AutoDownload:
    # In case you dont have GeoIP.dat it will be downloaded automatically on server start. Restart can be needed for it to take effect
    GeoIp: true
    # In case you dont have GeoLiteCity.dat it will be downloaded automatically on server start. Restart can be needed for it to take effect
    GeoLiteCity: true`

How do I enable it so it shows me what country they joined from?

**Comment by Zrips** [comment]
If you have it downloaded then you can see players location when you use /cmi info [playerName] command, same thing applies when using placeholders

**Comment by Steev93** [comment]
I do have it downloaded and Cmi Info shows nothing.

**Comment by Zrips** [comment]
Did you checked on yourself while having server on your own pc? Because location is determined by IP address and in case you are playing on local machine, we cant really determine your location.

**Comment by Steev93** [comment]
Nah it's on a server,

cloud-land.net

http://prntscr.com/rybzg7
http://prntscr.com/ryc0o8

**Comment by Steev93** [comment]
Also using /cmi info
http://prntscr.com/rycejv
