### ISSUE TITLE
spawnmob stuff like name and effect not working on passenger

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#3097]
**Description of issue:**
When trying for example to do the actual example for the command;
 `/cmi spawnmob sheep:adult:rainbow ps:chicken:baby:n-Chick_on_Sheep q:10 sp:10 hp:50s:2`

it does not give the passenger baby chicken a name. It also doesnt work with effect. Havnt tried any of the others.

---

**Cmi Version (using`/cmi version`):** 8.6.21.2

**Server Type (Spigot/Paperspigot/etc):** Paper (162)

**Server Version (using `/ver`):** 1.15.2

**Comment by Zrips** [comment]
Will be fixed with next build
