### ISSUE TITLE
Modular plugin

### ISSUE THREAD

**Issue by BackWheel** [Zrips/CMI#3098]
In the case of using CMI plug-in for a long time, I have to say that this is a very good plug-in. It has very versatile functions and can save a lot of extra plug-in needs. But this also caused a problem behind the plug-in, that is, the burden caused by too much content. Although the current CMI plug-in content is very rich, but for some people these functions may be redundant. Therefore, I think modularity is one of the options that can be considered.

To put it simply, modularization is to split the functions of the current plug-in into components (I have seen similar plug-ins including Bentobox and Sunlight), so that users can choose specific components to install on the server according to the functions they need. I think the benefits of modularity may be the following:
1.Users can choose according to the functions they need to avoid loading unnecessary functions 
   and speed up the plug-in activation time, etc.
2.Can greatly reduce the size of the plug-in
3.Easy management and bug feedback

Although this is a good idea, but I also know that CMI development may still want to modularize it is a very large and complex project, for plug-in developers may not have so much time and energy to make, But I still hope to see the emergence of modularity in the future CMI .(maybe CMI 9.0.0.0?)

**Comment by Zrips** [comment]
We do have option to disable specific modules, other then this, yea, going into modular architecture at this point will require quite a bit of work and some rework on base code. Something whats pops into my head straight away is a locale file. We have locale lines for each command, in case you dont have module installed then locale line should not really exist, but then at same time we cant really make a locale file in a way as it would be like free for all, where you could add a bunch of none used stuff and create files whith even more redundant information in it. And then you have some cross over usages where one feature uses something from another. I could separate some more isolated things into their own files, but still, this requires quite allot of thinking and reconsidering what should go where
