### ISSUE TITLE
User can not send public messag from mainsrv to gamesrv

### ISSUE THREAD

**Issue by valenvaio** [Zrips/CMI#310]
- cmi.bungee.publicmessage.mainsrv
- cmi.bungee.publicmessage.gamesrv

User can not send public messag from mainsrv to gamesrv.

Op can not see message send by user. User can see massage send by Op.

CMI 7.7.0.0

**Comment by Zrips** [comment]
Sorry for typo. it should be 

- cmi.bungee.publicmessages.mainsrv
- cmi.bungee.publicmessages.gamesrv

permission nodes. With S 
keep in mind that **/cmi checkperm bungee** ingame will always give you correct permission node
