### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by pvvvo** [Zrips/CMI#3100]
I lost all my edited translation folder (Locale_ES), it resetted... I literally spent so much time personalizing it.

**Cmi Version (using`/cmi version`): 8.6.22.1** 

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): 183**

**Comment by Zrips** [comment]
Translation files could be reset if there was misinformation issue with it, in which case it should have been moved into backup folder and you should have error in your console informing about this
