### ISSUE TITLE
item translation in chat.

### ISSUE THREAD

**Issue by Ahmadh26** [Zrips/CMI#3101]
**Description of issue:**
HoverItems doesnt work as intended. when i use `%i%` or `[item]` it doesn't translate to the item i'm holding. that doesnt work with public chat, whispers or msgs. However it does work in staffmsgs only. 

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
 HoverItems: true
  # Defines regex when replacing item line in chat with players item in hand information. Only works when CMI hover over chat format is enabled
  ItemRegex:
  - (\%item\%)
  - (\[item\])
  - (\%i\%)
```

---

**Cmi Version (using`/cmi version`):** 
8.6.22.1 BungeeCord

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper(162) 1.15.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
For this feature to work you need to have CMI chat handling to be enabled, and to be more accurate, hoverOver messages should work. Other then this, i cant really determine cause. It might be that you are using some another plugin to handle public or private messages, as of testing with 1.15.2 all seams to be working correctly.
