### ISSUE TITLE
Worldguard bypass antibuild

### ISSUE THREAD

**Issue by resitancedude** [Zrips/CMI#3103]
**Description of issue:**

Since I uploaded the plugins, there a lot of issue with worldguard flag. Even with protection with worldguard, sometime player can break protected area. There is no error from the console, player disconnect and reconnect, they cant build, that's very not usefull, Can someone help ?

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`): 8.6.22.1

**Server Type (Spigot/Paperspigot/etc): SPIGOT 

**Server Version (using `/ver`): !.15

**Comment by Zrips** [comment]
How is that related to CMI? Cmi doesn't control protection of blocks.
