### ISSUE TITLE
Warmup commands are not working with non-CMI commands in Interactive Commands

### ISSUE THREAD

**Issue by DaveDevil** [Zrips/CMI#3104]
**Description of issue or feature request:**

I put a command in a sign, it's a mycommand registered cmd. If I put " :8:false" at the end of the command, the warmup is not started and the command is executed immediately:

asConsole! teleport_to_arena [playerName] :8:false:GlyphHead

---

**Cmi Version (using`/cmi version`):** 8.6.21.5

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** build 136 version 1.15.2

**Comment by Zrips** [comment]
They are working, but you are trying to achieve some strange behavior here. Warmup is applied to defined command, while you want to apply warmup and perform command from different source. having simple **teleport_to_arena [playerName] :8:false:GlyphHead** will apply warmup when player performs **/teleport_to_arena something** warmup feature doesn't support redirection of command performed. 
If you want to have cooldown like this on command which will redirect it somewhere, you can utilize custom alias editor, create command name you want and add command like
**cooldown:5?! asConsole! teleport_to_arena [playerName]**
