### ISSUE TITLE
Separated permissions for mail command

### ISSUE THREAD

**Issue by DaveDevil** [Zrips/CMI#3105]
**Description of feature/improvement request:**

Add separated permissions for /cmi mail clear, /cmi mail read, /cmi mail send

---
### Detailed explanation of what it should do, when and in what situation: ###

I would allow players to only read mails sent by the staff, or to allow only VIP players to send mail to others

### Basic explanation as to why this feature is needed and/or useful to have: ###

Adding cmi.command.mail permission unlocks all mail commands.

Without a .send permissions, there are 2 cases:
1. none can read emails, so this function is useless
2. everyone can send emails, even newbies, and they can spam to players

**Comment by Zrips** [comment]
ok
