### ISSUE TITLE
Can teleport to home on slab

### ISSUE THREAD

**Issue by PoulpinSky** [Zrips/CMI#3106]
**Description of issue:**
My players can't teleport themself on his home when their home is in slab (double or simple)

---

**Cmi Version (using`/cmi version`):** 8.6.22.1

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper(1618) 1.12.2-R0.1-SNAPSHOT

**Relevant plugins (Delete if this isn't needed):** CMI

**Comment by Zrips** [comment]
Getting fix with next build
