### ISSUE TITLE
items in /anvil get deleted if players inv is full

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#3107]
**Description of issue:**
items in /anvil get deleted if players inv is full

https://gyazo.com/1fbe4d27c60c5b1b5d076845cd16eca4

---

---

**Cmi Version (using`/cmi version`):** 
8.6.22.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper(183) 1.15.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Could you elaborate more on this issue? As your video doesnt really show whats going on exactly and i cant reproduce this issue at this moment.
