### ISSUE TITLE
/fixchunk progress disappears if you relog

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#3108]
**Description of issue:**
If you do /fixchunk and leave the server and rejoin, the progress bar disappears

---

---

**Cmi Version (using`/cmi version`):** 
8.6.22.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper(183) 1.15.2

**Comment by Zrips** [comment]
Should be resolved with next build
