### ISSUE TITLE
/cmi give carrot <- not working

### ISSUE THREAD

**Issue by Baw-Appie** [Zrips/CMI#3113]
**Description of issue:**
When /cmi give carrot is executed, only a message is displayed and no item is actually given.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
[https://pastebin.com/4xFQAuN8](https://pastebin.com/4xFQAuN8)

---

**Cmi Version (using`/cmi version`):** 
8.6.22.1
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
git-Paper-1618

**Comment by Zrips** [comment]
Will be fixed with next build, tho correct usage will be /cmi give carrots, as carrot is not an item which can be given.
