### ISSUE TITLE
Socialspy hide permission

### ISSUE THREAD

**Issue by trickman325** [Zrips/CMI#3114]
**cmi.command.socialspy.hide** permission.
Commandspy and signspy both have it i dont know why social doesnt

This is so myself and my admins can talk about higher server isseus without our mods seeing what we are talking about.

P.S. i have tried added the .hide after in the current version 8.6.22.1 and it failed (so there is nothing behind the scenes working)

**Comment by trickman325** [comment]
@Zrips

**Comment by Zrips** [comment]
next update
