### ISSUE TITLE
/seen not showing correct value

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#3119]
**Description of issue:**
All the players on my server has 3 years and 62 days of online hours

---

**Cmi Version (using`/cmi version`):** 8.6.22.2

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot 184

**Server Version (using `/ver`):** 1.15.2

**Comment by blek-id** [comment]
https://prnt.sc/s0py3o image for reference

**Comment by x1p** [comment]
Same. Following.

`/whois` information seems to be correct though.

**Comment by Exillium313** [comment]
Getting the same thing, I'm on latest CMI version too

**Comment by WhatsTheBadNews** [comment]
Same issue on my server

**Comment by CloudeLecaw** [comment]
fixed in CMI_8.6.23.0 - pls close

**Comment by Zrips** [comment]
Fixed
