### ISSUE TITLE
Add an /itemdb command

### ISSUE THREAD

**Issue by tedztar** [Zrips/CMI#3120]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
When running the command it shows all the relevent information about the item, Including the spigot/Bukit item name and value.
### Basic explanation as to why this feature is needed and/or useful to have: ###
Would be useful for doing config files for plugins that need the spigot name and not the vanilla name, such as Shop GUI +

**Comment by variananora** [comment]
CMI does have /iteminfo tho..
