### ISSUE TITLE
./seen issue

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#3122]
**Description of issue:**
After newest update the /seen shows the wrong time 
Plugin version:
Paperspigot 1.15.2

**Comment by Sikatsu** [comment]
![image](https://user-images.githubusercontent.com/5664135/79566164-62e61000-80b2-11ea-81cb-c954cb257602.png)

**Comment by mrfloris** [comment]
Can confirm on spigot too.

**Comment by FestusDM** [comment]
Confirming issue on Paperclip, also.

**Comment by CloudeLecaw** [comment]
we can confirm this too

**Comment by SilkPenny** [comment]
Also happening on our server...

**Comment by pvvvo** [comment]
Same here.

**Comment by variananora** [comment]
can confirm also same with #3119

**Comment by NightFuryStrike** [comment]
Can confirm, CMI 8.6.2.22 & Paper-195
![image](https://user-images.githubusercontent.com/56176412/79672860-ed5e6a80-81ab-11ea-99e6-3f85e872dab5.png)

**Comment by ChitterChatter** [comment]
![image](https://user-images.githubusercontent.com/28234726/79677440-68bd1d80-81a6-11ea-8ad4-e931e33b8d95.png)

I am getting the same on my server - ps, that player is online now.
I too have CMI 8.6.2.22 and Paper as well.

**Comment by RedAlphard** [comment]
![photo5827787892573975265](https://user-images.githubusercontent.com/19147055/79693670-53122b80-826c-11ea-828b-c21a19fa3cb4.jpg)

Confirm bug, 
while the command cmi info/cmi whois shows the correct date
CMI 8.6.2.22
Paper 1.15.2 - 199

**Comment by CloudeLecaw** [comment]
Duplicated https://github.com/Zrips/CMI/issues/3119

**Comment by arturek1666** [comment]
Issue has been fixed
