### ISSUE TITLE
gmc command bug

### ISSUE THREAD

**Issue by diskotekastar** [Zrips/CMI#3125]
**Description of issue:**
When you press TAB on the "/ gmc" command, gamemode types appear instead of players.
Here I send photo:
https://ctrlv.cz/TXng

---

**alias.yml configuration:**
https://ctrlv.cz/7yje
```

---

**Cmi Version (using`/cmi version`):**  8.6.22.1

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):**  1.12.2

**Comment by Zrips** [comment]
Its due to how this specific alias is handled, but will include player names into tab list
