### ISSUE TITLE
[feature request] adjust home locations if unsafe

### ISSUE THREAD

**Issue by ScuroK** [Zrips/CMI#313]
Can you please add an option to teleport players to a higher nearby location if a home is unsafe. 
i think the /bypass solution is not good enough. 

because:
if a player does not have build permission where he set the home and someone builds something. there he will always die when using this home and bypasses the warning.

if there is a cave under the home it will bring him there BUT if not he will die.
thats why i suggest to teleport him to blocks ABOVE the home location.

- essentials did a quite good job in adjusting teleport locations.
- griefprevention's /trappen function works fine and teleports the player to a higher block.

maybe you could see how they did it ;)

**Comment by Zrips** [comment]
Next update should contain some additional checks for possibility to teleport up if there is no safe location down.

**Comment by Zrips** [comment]
Maybe, maybe. Well will add option to switch between check order so you can check for safe place going up before checking down.
