### ISSUE TITLE
An extremly weird bug with WorldLimits and fly flag from WorldGuardExtraFlags and level-name

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#3130]
**Description of issue:**
Yeah so I have no clue why or how this bug would even take place in the first place, but if you add fly flag from WorldGuardExtraFlags to a region which does so you can then fly in that region, if you then relog inside the region you can no longer fly. This only occurs if WorldLimits is enabled and the level-name (in server.properties) is not "world". If I disable WorldLimits it will then work. the world "world" is also not being specified inside Fly in WorldLimits. However if I set level-name to "world" and have WorldLimits enabled with no change to anything within WorldLimits it now works? The other world name in question is "empty". If I remove CMI it also works as intended with you being able to fly after relogging inside of the region.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

https://pastebin.com/Ynpi0u6Cl

---

**Cmi Version (using`/cmi version`):** 8.6.22.2

**Server Type (Spigot/Paperspigot/etc):** Paper (161)

**Server Version (using `/ver`):** 1.15.2

**Relevant plugins (Delete if this isn't needed):** WorldGuardExtraFlags

**Comment by Zrips** [comment]
Should be resolved with next update
