### ISSUE TITLE
Weird absurd /seen times after updating to CMI 8.6.2.22

### ISSUE THREAD

**Issue by variananora** [Zrips/CMI#3133]
**Description of issue:**
Weird absurd /seen times after updating to CMI 8.6.2.22

![image](https://user-images.githubusercontent.com/34732414/79635657-56d67d00-819c-11ea-9b85-e5803c2d068e.png)

---

**Cmi Version (using`/cmi version`):** 
8.6.2.22

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper-194 (MC: 1.15.2)

**Comment by pvvvo** [comment]
same here.

**Comment by variananora** [comment]
Sorry for the duplicates for #3119 and #3122
