### ISSUE TITLE
LOW TPS

### ISSUE THREAD

**Issue by AsiK111** [Zrips/CMI#3134]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
``` LOW TPS

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
#######################################
```
Task: UserEvents$4(Single) -  381.74%	Pct Tick

I bought your "pseudo plugin" and i have a lot of lags on my server. Tps fall to 2 by your plugin. Please fix this. This shit plugin i  lost a lot of players through this plugin.
FIX THIS !

I pay it, I require it
---

**Cmi Version (using`/cmi version`):**  latest

**Server Type (Spigot/Paperspigot/etc):** spigot

**Server Version (using `/ver`):** 1.15.2

**Comment by Zrips** [comment]
Actual timings would be nice to have. And something more to go on then simply giving one line from your tps which doesn't say anything on what's going on. It might be issue with plugin, it might be issue with your settup, I have no idea and I can't debug it without any actual information.
