### ISSUE TITLE
TPS drops caused by CMI

### ISSUE THREAD

**Issue by Repo92** [Zrips/CMI#3138]
**Description of issue:**
I have TPS drops caused by CMI

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
https://timings.aikar.co/?id=d7f1e873bb074456983365c01dabf501#timings

```

---

**Cmi Version (8.6.22.2):** 

**Server Type (Paperspigot):** 

**Server Version (1.15.2-R0.1-SNAPSHOT):**

**Comment by Zrips** [comment]
I would suggest to look into multiverse inventories, as from timings it shows that its being triggered at moment player is warped to another world, which by itself creates load on server. CMI is not the cause, CMI simply performed action after which another plugin created a load, in this case its simple teleport to another world event.

**Comment by Repo92** [comment]
Thank you for interest, I will try to get help somewhere else then :)

**Comment by Zrips** [comment]
What actions do you perform with players inventories when they change world?

**Comment by Repo92** [comment]
Multiverse-Inventories I using only for keep separate inventories per world, because I have two modes, skyblock and survival. To be honest I didn't set it up, I just putted it in the plugins folder and that's it
