### ISSUE TITLE
TPS drop with CMI

### ISSUE THREAD

**Issue by Caufland** [Zrips/CMI#3139]
**Description of issue:**
tps fall through cmi is the only plugin marked in any way at times and this are screenshot with timings
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://user-images.githubusercontent.com/63148059/79687791-087fb780-824a-11ea-8d03-5fae2ab22e6d.png
https://user-images.githubusercontent.com/63148059/79687792-09b0e480-824a-11ea-90e9-87fe6f03a52a.png
https://user-images.githubusercontent.com/63148059/79687793-0a497b00-824a-11ea-8678-06bb4c118f5a.png
https://user-images.githubusercontent.com/63148059/79687796-0ae21180-824a-11ea-8247-67f4aa52d35b.png

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
https://github.com/Zrips/CMI/files/4498991/CMI.zip

**Cmi Version (using`/cmi version`):** 
8.22.2

**Server Type (Spigot/Paperspigot/etc):** 
spigot

**Server Version (using `/ver`):** 
1.15.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Should be resolved with latest versions
