### ISSUE TITLE
hasexp and hasmoney

### ISSUE THREAD

**Issue by StrangerFive** [Zrips/CMI#314]
Thought I remembered you mentioning way back about hasmoney and hasexp specialized commands, but there's no mention of them on the wiki.  They did get implemented, didn't they?  If so, can you add them to the wiki?

Are there any other specialized commands missing from the wiki?

Is there a way to execute a command if player does NOT have enough exp or money?

**Comment by Zrips** [comment]
Updated wiki, those variables are present just wiki was not updated
