### ISSUE TITLE
/msg duplicate bug

### ISSUE THREAD

**Issue by Ahmadh26** [Zrips/CMI#3142]
**Description of issue:**
When a player on my server runs a `/msg` command the message being sent is duplicated. i have noticed this happens when the users use the player's nickname instead of username in the `/msg`
eg:
if my nickname on the server is `nick` and my username is `user`:
when they do `/msg nick test` the message command is run twice (see screenshot attached).
when they do `/msg user test` it runs normally as it should.

i have attached a screenshot, along with my config file. 
![chat](https://user-images.githubusercontent.com/57562297/79702996-74e1d180-82b1-11ea-83dd-3078e5f99780.png)

[config.zip](https://github.com/Zrips/CMI/files/4500537/config.zip)

---

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.6.22.2 BungeeCord

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Server version: Paper(162) 1.15.2-R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment]
well i also had this bug once - there i was my own fault i make  a mystake in the  permission management XD

**Comment by Ahmadh26** [comment]
> well i also had this bug once - there i was my own fault i make a mystake in the permission management XD

What mistake was it?

**Comment by CloudeLecaw** [comment]
i was added in two groups (no parents or inheritance)
each group had his own chat permission for CMI and negations of the other groups

**Comment by Zrips** [comment]
Should be resolved
