### ISSUE TITLE
/seen command showing "Online since 3 years ago"

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#3145]
**Description of issue:**
Seen command is showing that all players have been online since 3 years ago.

---
![image](https://user-images.githubusercontent.com/29175884/79751066-421bf580-8312-11ea-9019-09f22276f232.png)

---

**Cmi Version (using`/cmi version`):** 8.6.22.2

**Server Type (Spigot/Paperspigot/etc):** Ppaer (201)

**Server Version (using `/ver`):** 1.15.2

**Comment by Fabrimat** [comment]
Same here
But the /cmi info command works fine and displays the correct time

**Comment by CloudeLecaw** [comment]
Duplicated of https://github.com/Zrips/CMI/issues/3119  ;)
