### ISSUE TITLE
All the commands are unknown

### ISSUE THREAD

**Issue by wavyethan** [Zrips/CMI#3146]
When I first installed CMI, all the commands are "unknown" like if i type /balance., It says that the command is unknown. Every command is disabled except the ones that start with /cmi

**Comment by Ahmadh26** [comment]
Enable aliases then restart your server. 
Go to CMI folder, alias.yml (or aliases.yml) and enable the aliases you want to use. Basically let's you do the command without doing /CMI at the start

**Comment by CloudeLecaw** [comment]
> Enable aliases then restart your server.
> Go to CMI folder, alias.yml (or aliases.yml) and enable the aliases you want to use. Basically let's you do the command without doing /CMI at the start

This is correct. all commands start with CMI so /cmi command unless u enabled the aliases in alias.yml without this you cant use the short commands.
