### ISSUE TITLE
/seen command is broken - says 3 years for everyone

### ISSUE THREAD

**Issue by runelynx** [Zrips/CMI#3147]
**Description of issue:**
/seen says 3yrs+ for everyone - online or offline. This was working on my last build, 3.19 something... updated to latest today and this happened.
![image](https://user-images.githubusercontent.com/5877481/79762246-1edc5080-82e8-11ea-8395-435aeb2a10e7.png)

![image](https://user-images.githubusercontent.com/5877481/79762311-37e50180-82e8-11ea-95a0-04acf887b10f.png)

---

 

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/5877481/79762335-3fa4a600-82e8-11ea-8c21-3ccff8a38138.png)

**Comment by Fabrimat** [comment]
Same here
But the /cmi info command works fine and displays the correct time

**Comment by Fabrimat** [comment]
Duplicated of #3145

**Comment by CloudeLecaw** [comment]
fixed in CMI_8.6.23.0 - pls close

**Comment by Zrips** [comment]
Fixed
