### ISSUE TITLE
/Vanishedit prevent chatting

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#3149]
**Description of feature/improvement request:**
A way to prevent a vanished player from typing messages in chat (not commands). 
---
### Detailed explanation of what it should do, when and in what situation: ###
through /vanishedit, there should be a way to prevent the person from typing messages in chat.

### Basic explanation as to why this feature is needed and/or useful to have: ###
I find myself accidentally typing in chat and giving away the whole vanished aspect.

**Comment by Zrips** [comment]
next update
