### ISSUE TITLE
Logging in while in air

### ISSUE THREAD

**Issue by cryoten** [Zrips/CMI#3151]
**Question: **
When logging out while in the air, I'm automatically put into `/fly` and this is quite frankly bothersome. This only happens to operators. For regular players, they continue falling after they log in and take damage. I gave players the safelogin permission but they still take damage.

How can I disable damage and also stop operators from automatically being put into fly?

**Comment by Zrips** [comment]
if you are in midair while logging into game, for safety reasons you will be put into fly mode if you have access to fly command. Another thing, is that you might have another plugin which could override players fly state, like multiverse, which might want to disable player fly mode when he joins the server.

**Comment by cryoten** [comment]
Is it possible to disable this for admins as it's a bit excessive?

For example, a regular jump would put me into fly mode. Standing on a boat, or even sitting in a boat will trigger it too. These are things that shouldn't cause fall damage.

Plugins I have are CMI, CoreProtect, Griefdefender and LuckPerms.

**Comment by Zrips** [comment]
I Will be doing some changes related to this with next update, let me know if you will have issues after it.
