### ISSUE TITLE
Problem with target selector variables in command blocks

### ISSUE THREAD

**Issue by sofy1801** [Zrips/CMI#3156]
**Description of issue:**
Hi, my problem is that when I use a cmi command in a commanblock I cannot use minecraft target selectors (@ p, @ a, @ e ...), it just says "Can't find player with this name!". 
I'm in 1.14.4 but I also tried it in 1.12.2 and it works fine in that version. 

**Cmi Version (using`/cmi version`):**  8.6.22.2
**Server Type (Spigot/Paperspigot/etc):** Paperspigot
**Server Version (using `/ver`):** 1.14.4

**Comment by Zrips** [comment]
Well, i can add somewhat support for @p and @r variables. Next version.
