### ISSUE TITLE
/whowas saying "cant find player with this name"

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#3160]
**Description of issue:**
/Whowas no longer working after latest update, doesn't recognize any names, tried a UUID too.

---

**Cmi Version (using`/cmi version`):** 8.6.23.0

**Server Type (Spigot/Paperspigot/etc):** Paper (208)

**Server Version (using `/ver`):** 1.15.2

**Comment by Zrips** [comment]
its actually issue with changed mojang API which was introduced recently. In any case, will be fixed with next update.
