### ISSUE TITLE
Actionbar duration

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#3161]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Messages from the `translation file` using the `!actionbar!` method to push a message to a player are gone with a blink of an eye. You can't even read the message or it's already gone.

I would like to set the length that it takes before the action bar fades away and disappears

### Basic explanation as to why this feature is needed and/or useful to have: ###
This is way to fast for young players (kids) with slow reading capabilities.
This is very annoying for dyslexic players or players with some form of autism.
The message is simply not read causing them to miss important messages.
Even for experienced players it is missed often depending of the colors of the background.

Only real alternative could be plain chat messages but this is not an option when chat is busy.

**Comment by CloudeLecaw** [comment]
of u work with !actionbar! then u also need to work with delay ;)
!actionbar! Message 1
!delay 5
!actionbar! Meassage 2
!delay 5

does this work for u?=

**Comment by x1p** [comment]
It concerns the translation file for entries like:
`  ItemWillBreak: '!actionbar!&eYour item (&6[itemName]&e) will break soon! &e[current]&6/&e[max]'`
or the mail notification:
`gotMail: '!actionbar!&eYou received mail from &6[senderDisplayName]'`

I assume this does not support adding delays and re-sending a second message.

**Comment by Zrips** [comment]
Next update
