### ISSUE TITLE
Placeholder %cmi_user_maxhomes% not working as expected

### ISSUE THREAD

**Issue by AerWyn81** [Zrips/CMI#3162]
**Description of issue:**

Hi, we have an issue with the placeholder : https://i.imgur.com/W0TBJJI.png. Not showing properly.

Thanks :)

---

**Cmi Version (using`/cmi version`):** 
8.6.23.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.15.2

**Comment by Zrips** [comment]
Try testing with /cmi placeholders parse %cmi_user_maxhomes%
If this outputs correct value then it simply doesnt translate in this particular place, for which i cant give a guarantee that it will be as it depends on which plugin shows this message and where.

**Comment by AerWyn81** [comment]
The command output : https://i.imgur.com/7G7gewX.png

In our configuration, we display this placeholder in the message when a player tries to create a home and can't anymore.

**Comment by Zrips** [comment]
Ok, some what issue with placeholder translation in some of the messages. Should be working correctly with next update.
