### ISSUE TITLE
CMI 8.6.23.0 failed to download something "java.net.SocketException: Connection reset"

### ISSUE THREAD

**Issue by In77** [Zrips/CMI#3163]
When I upgrade the CMI to the version 8.6.23.0
Console will report warning about it failed to download something
I searched the Change log and SpigotMC page, but I still don't know what is the plugin need to download.
The Server is in China.
<img width="1015" alt="Screenshot 2020-04-22 at 22 29 53" src="https://user-images.githubusercontent.com/44344308/79995382-beb4fc80-84e9-11ea-94c0-764f0f770f87.png">

**Comment by Zrips** [comment]
its nothing serious, it simply failed to download locale files from github. Will make some changes to prevent this "scary" message from appearing and will simply display an informational message.
