### ISSUE TITLE
Sit On Stairs (Kicked for Flying)

### ISSUE THREAD

**Issue by yimyum** [Zrips/CMI#3164]
**Description of issue:**
cmi.command.sit.stairs kicks you most of the time when you sit.

---

---

**Cmi Version (using`/cmi version`):** 
8.6.22.2
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper("af00b80d")

**Comment by SGlance** [comment]
Not a bug.

**Comment by yimyum** [comment]
https://gyazo.com/a1fecf0c1bd603759934fd1f2010687d
https://gyazo.com/4a7900c4465204a85ab279d2b6af981a
Well i hope it's not an intended feature...

**Comment by Zrips** [comment]
@yimyum 
This could be a result of your anticheat plugin which doesnt process correctly players who are riding armorstands. Test this by temporarily disabling your anticheat plugin, when that gets confirmed, ether check itsconfig file for posible fix over there or get in contact with plugins developer so he could fix it. CMI doesnt do anything fancy with this feature, it simply creates invisible armorstand and places player on top of it which should not be counted as flying
