### ISSUE TITLE
/patrol command

### ISSUE THREAD

**Issue by pvvvo** [Zrips/CMI#3167]
When you use /patrol it doesn't teleports you exactly to the player position like /tp
Sometimes it teleports you to a higher position of the player if, for example he's in a cave.

**Cmi Version (using`/cmi version`): 8.6.23.1** 

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): 208**

**Comment by Zrips** [comment]
Will be fixed with next version
