### ISSUE TITLE
God mode takes people through nether portals instantly

### ISSUE THREAD

**Issue by e101stella** [Zrips/CMI#3168]
**Description of issue:**
Basically as title, when a player is in /cmi god, they go through nether portals instantly otherwise it behaves as it does in vanilla. Doesn't produce any console errors or anything like that

---

**Cmi Version (using`/cmi version`):** 8.6.23.1

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.15.2 Paper-206

**Comment by Zrips** [comment]
Can't really do anything about this as this is what server itself does with players who cant receive damage. Threats them as players being in creative mode, no idea why they did like this, but it is what it is.
