### ISSUE TITLE
SafeLocationDownThenUp not working right

### ISSUE THREAD

**Issue by ScuroK** [Zrips/CMI#317]
I just tested the new "SafeLocationDownThenUp: false" option.

the ceiling of our spawn is 63 blocks high. players will however tp to the ceiling instead of reaching the spawn point. 
but there is plenty of space for the player xD it should only do this if spawn point is unsafe (less than 2 blocks of space for the player)

**Comment by tmellen** [comment]
This happened in my house when I enabled this, too. I was suddenly on my roof. I switched it back, did a /cmi reload, and typed the home command again -- safely in my house this time, not on it.

**Comment by ScuroK** [comment]
It acts to extreme.

**Comment by Zrips** [comment]
Will be fixed with next build.
