### ISSUE TITLE
Issue with /head

### ISSUE THREAD

**Issue by AerWyn81** [Zrips/CMI#3171]
**Description of issue:**

On the command /head Titan : https://pastebin.com/kLBdWfuR

**Cmi Version (using`/cmi version`):** 
8.6.23.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.15.2

**Comment by Zrips** [comment]
Should get fixed with next update. This was due to changes Mojang implemented recently which broke some parts of plugin related to skins.

**Comment by Zrips** [comment]
tested out with 1.15.2 paperSpigot #214 version, everything works as expected. At this point i have no idea why its failing for you in specific. Which version of spigot are you using exactly?

**Comment by AerWyn81** [comment]
Okay, I just tried it again just now and everything works... I don't understand everything, but the problem is solved.

Using latest build, 213.

**Comment by Zrips** [comment]
This might have been issue with old cache still being present which should have been updated automatically with recent update, but might have still failed on first usage.
