### ISSUE TITLE
Issue with Selection Visualizer (lastest)

### ISSUE THREAD

**Issue by jj136975** [Zrips/CMI#3174]
Hey, I'm gettin an error when I try to use Selection Visualizer. As there are no VS repository, a discord staff member told me to post the error here.

 https://pastebin.com/h0NEj433

I'm using PaperSpigot 1.8.8 with worldedit, jobs reborn, worldguard and FactionUUID.
I think that the error come from the fact the plugin try to use a perticle methode that isn't existing on Spigot 1.8.8.

**Comment by mrfloris** [comment]
I told him to post this here, even though category is CMI

**Comment by Zrips** [comment]
Fixing with next release
