### ISSUE TITLE
API Issue

### ISSUE THREAD

**Issue by InamineDev** [Zrips/CMI#3175]
**Description of issue:**
I'm trying to use the CMI API in my plugin for the holograms, and I can create and delete the holograms fine, but the holograms are meant to follow the player around for a few seconds, and then delete.
When I try to set the location of the hologram it doesn't move. When the player moves, the hologram stays in the original location, and then will teleport once before deleting.
It says that the hologram.refresh() method does not exist, which is what the api instructions say to use to update the location. 
Is there a different method to use?
I know with the hologram.remove() it's not that, it's CmiHologram.getHologramManager.removeHologram(hologram) or something, which isn't on the API page, so I'm wondering if it's something like that, or if the API is just missing this method

---

---

**Cmi Version (using`/cmi version`):** 
8.6.23.2
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.15.2
**Relevant plugins (Delete if this isn't needed):**
PlayerEmotesPro is the plugin I'm trying to add it to

**Comment by Zrips** [comment]
Current code was not made to display moving holograms. I will add a special method which will superficially move hologram around which best possible performance. Tho this will limit hologram move range to actual hologram view range set in it. As i dont want to perform heave recalculations of its location on each move, but you can always relocate it with extra method when player is near edge or out of update range. Anyways, next update will have simple CMIHologram#superficialMoveTo(Player player, Location loc) method

**Comment by InamineDev** [comment]
Seems this method still isn't in the API, should I be using the full plugin as the external resource? Using the latest API linked from the CMI page it doesn't show up.
