### ISSUE TITLE
Persistent issue with /head

### ISSUE THREAD

**Issue by AerWyn81** [Zrips/CMI#3178]
**Description of issue:**

Despite updating the plugin to the latest version, the problem seems to persist.
https://pastebin.com/5s49UncY

[#3171](https://github.com/Zrips/CMI/issues/3171)

**Cmi Version (using`/cmi version`):** 
8.6.23.2
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
155

**Comment by Zrips** [comment]
Closing this as of duplication. Will address the previous one.
