### ISSUE TITLE
Mirror + Shulkers = Duplication

### ISSUE THREAD

**Issue by darkmagic101** [Zrips/CMI#3179]
**Description of issue:**

When placing shulkers during mirror it failed to take the box out of my inventory and placed one on the ground anyway.  Also placed a 2nd one that is empty probably since I had 2 shulkers in my inventory.  I was able to not only duplicate shulkers, but also duplicate the items inside.  

My suggestion is to:
1. Not allow shulkers to be able to be used with mirror.
or
2. Have a way to limit what type of blocks can be mirrored.

BTW I am a mod on the server and do not have access to the config file, if there is a way from the config I do not know about it.

Thank You!

**Comment by Zrips** [comment]
Will fix this issue with next update
