### ISSUE TITLE
geoip location -  city

### ISSUE THREAD

**Issue by valenvaio** [Zrips/CMI#318]
Can you add geoip location to /cmi info?

**Comment by Zrips** [comment]
Its already there. Hover over players ip and you will see country.

**Comment by valenvaio** [comment]
i see only (--), no country and city.

**Comment by Zrips** [comment]
You need to have http://ltcraft.lt/wp-content/uploads/2018/03/GeoIP.dat this file. Will need to make some auto downloader for this one.

**Comment by valenvaio** [comment]
Is geoip.dat coming from authme or essentials plugins?

**Comment by Zrips** [comment]
None of those, its official free database of IP's and countries for purpose liek this.

**Comment by valenvaio** [comment]
Ok. Thanks! It's work. Can you add city info from ip? 
Essentials can show this info from geoip.
