### ISSUE TITLE
Sit in the stairs in 1.12.2 (no kick)

### ISSUE THREAD

**Issue by Victor75007** [Zrips/CMI#3180]
**Description of issue or feature request:**
Hello,

I have a problem with CMI.
When somebody sit down on the stairs, they will sit "aside"...
Example in the picture

https://i.imgur.com/iFRuAYA.png

The armor stand is a little higher, like the sit-point of stairs.
---

---

**Cmi Version (using`/cmi version`):** 8.6.23.3 

**Server Type (Spigot/Paperspigot/etc):** Paper spigot

**Server Version (using `/ver`):** Paper(1613) 1.12.2-R0.1-SNAPSHOT
BungeeCord -> 8.6.23.2
Vault version: 1.7.2-b107(CMIEInjector)

**Comment by Zrips** [comment]
Should be fixed with next build
