### ISSUE TITLE
Auto Changing orientations for Warps/(maybe homes)!

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#3181]
Auto Changing orientations for Warps/(maybe homes)!
A lot of us have player marketplaces where users can setup shop, one of the biggest issues with warps is that its bias to whoever is in front of the warp, a way to solve this would be to have a feature so per warp you can make it change its orientation in 180 degrees every X amount of time, So for example every hour the warp direction you face a new direction in the 180 degrees.

I would use this for my marketplace warps, but others could use it for their hubs to face a different mini game

Another use could be for games when dropping people into arenas.

Optional: Add a random orientation feature, so each time someone uses the warp their orientation is in a random direction instead of rotating clockwise.

This could even be a feature for peoples /homes, if they wanted it.

**Comment by Zrips** [comment]
Next update, but only for warps.
