### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Relaxing9** [Zrips/CMI#3182]
**Description of issue:**
When running the command /lastonline (large number) server stopped responding and crashed

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**

[latest.log](https://github.com/Zrips/CMI/files/4532121/latest.log)

---

**Cmi Version (using`/cmi version`):** 8.6.23.3

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-2040c4c-893ad93

**Comment by Zrips** [comment]
Should be fixed with next version
