### ISSUE TITLE
Command /kitusagereset {kit} {nick} isn't working

### ISSUE THREAD

**Issue by Sergix7720** [Zrips/CMI#3183]
When I try to reset the usage of a kit to a player it just doesn't do anything, the console don't show anything either.
---

Cmi Version: 8.6.23.3

Server Type: spigot

Server Version:1.15.2

**Comment by Zrips** [comment]
I have no idea if you misspelled, but the actual command is /kitcdreset  [kitName] [playerName]

**Comment by Sergix7720** [comment]
No, the command you said resets the cools down. The one I say reset the usage limit, for example if the kit has an usage of 5, if the player has already used 5 times the kit, the commands guide says this /kitusagereset {kit} {nick} reset that ussage for the player.
