### ISSUE TITLE
Server Freeze from CMI tab complete?

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#3184]
**Description of issue:**
I don't know how to reproduce it, but this happens on my server once, so might as well just report it and see if this is something fixable

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://paste.md-5.net/ogacakiren.md
```
---

**Cmi Version (using`/cmi version`):** 8.6.23.3

**Server Type (Spigot/Paperspigot/etc):** Paperspigot 214

**Server Version (using `/ver`):** 1.15.2

**Comment by Zrips** [comment]
Will be optimized with next build. This is related to ban list. My bet is that you have quite few entries in your records which caused some unexpected loads while checking some data.
