### ISSUE TITLE
After going in to vanish, entity pushing doesn't work most of the time

### ISSUE THREAD

**Issue by kelso6969** [Zrips/CMI#3186]
**Description of issue:**
After using /vanish, and becoming visible again, you are often unable to push entities (while visible). For example, pushing villagers. I've not been able to determine what causes it to work and not work, but if you login and don't vanish, you don't have the problem. I've also tested removing the vanish permission and the problem never occurs.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```
***I've not changed this section***
Vanish:
  # Defines default states of vanish edit options for players
  # This will not have any effect if player already edited his vanish mode with vanishedit command
  Defaults:
    damageToEntity: false
    playerDamage: false
    itemPickup: false
    mobAggro: false
    interaction: false
    noisyChest: false
    informOnLeave: false
    informOnJoin: false
    nightVision: true
    bossbar: true
    afkcommands: false
    PrivateMessages: false
    relogDisable: false
---

**Cmi Version (using`/cmi version`):** 
[Sat, 25. Apr 2020 12:54:35 MDT INFO] CMI plugin version: 8.6.23.2 BungeeCord -> 8.6.23.3
[Sat, 25. Apr 2020 12:54:35 MDT INFO] Server version: Paper(205) 1.15.2-R0.1-SNAPSHOT
[Sat, 25. Apr 2020 12:54:35 MDT INFO] Vault version: 1.7.3-b
**Server Type (Spigot/Paperspigot/etc):** 
paperspigot
**Server Version (using `/ver`):** 
I some how broke this command and it no longer works. I'm using paperspigot 
papermc.jar -> paper-205.jar

**Comment by kelso6969** [comment]
found others
https://github.com/Zrips/CMI/issues/2811
https://github.com/Zrips/CMI/issues/2456

close as duplicate

**Comment by Zrips** [comment]
Fix is coming out with today's update.
