### ISSUE TITLE
Command cmi rt does not work correctly

### ISSUE THREAD

**Issue by richie199** [Zrips/CMI#3187]
Hello

The command /cmi rt %playername% %worldname% teleports the player to the end of the world or rarely directly to the spawn of a world where the command was executed.

The spawn of the world is located at coordinates -8602 72 -14905

Richie
---

**Cmi Version (using`/cmi version`):**  8.6.23.3

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot

**Server Version (using `/ver`):**  git-paper-214 (MC: 1.15.2)

**Comment by Zrips** [comment]
What is your setup for random teleportation in your config file?

**Comment by richie199** [comment]
Oh, there was something wrong with the setting. Last time, the coordinates were slightly off.

Thanks for the help.

The problem is solved.

Richie
