### ISSUE TITLE
fly disabled when someone receives the command from a plugin

### ISSUE THREAD

**Issue by TimHarrio** [Zrips/CMI#3188]
Hello,
Fly disabled when someone receives the command from a plugin.
When a player receives a tfly (example: cmi tfly <USER> + 1h he instantly receives the message "You can fly 1h" then then "You can no longer fly"

---

**Cmi Version (using`/cmi version`):** 
8.6.22.2

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-211 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
This could only be issue with another plugin disabling fly mode at moment player gets fly mode enabled. tested out on 1.15.2, works as expected, player can fly for a determined time period.
