### ISSUE TITLE
Homes are broken

### ISSUE THREAD

**Issue by Sergix7720** [Zrips/CMI#3189]
I Have serious problems, my users homes have been leading them to places underground and in those cases dying sofocated, and also being teleported to completly random locations. I enter and saw the DB tables of homes and I saw that every single broken home they get this number in X or Z 2.147483647E7.
This is the complete info in the DB and as you can see the home "Home1" is broken.
Home1%%survival:2.147483647E7:68.0:2.147483647E7:1.63:51.34;Jhoana98%%survival:5176.18:81.0:2563.66:15.76:-105.37;Arenas%%arboles:-8.33:34.0:-539.83:7.08:-91.92

Anybody else having this problem? And what that could be, because Right now a more than 20 of my players are reporting that they are dying sofocated in their homes.
---

**Cmi Version :8.6.23.3

**Server Type:Paper

**Server Version: 1.15.2

**Comment by aitechhkn** [comment]
I have the same problem, this bug came out when using the latest version of cmi

CMI Version: 8.6.23.3
Server Type: PaperMC
Server Version: 1.15.2 #216 (Latest Paper Version)

**Comment by Zrips** [comment]
@Sergix7720 
What are the limitations of your server map size wise? As numbers like 2.147483647E7 points to max value of Integer.

**Comment by Sergix7720** [comment]
30 000 000 but I have a home at those cordinates an there isn't any problem with my home, looks like my account haven't been affected by this bug yet.

**Comment by Zrips** [comment]
@Sergix7720 
Testing. For time being you could try negating or taking away cmi.safeteleport permission node to teleport players to exact location it was set and avoid checking for safe one, atleast until i can determine cause of this issue.

**Comment by Sergix7720** [comment]
Well if I do that I thing there is going to happen that they will still teleport to the same place, because the problem is that the cordinates saved in the DB are changed to that number '2.147483647E7', so they teleport to that number of cordinates actually 2.147... Still I'm going to try it!

**Comment by Zrips** [comment]
Issue with those coordinates will be resolved with next update. But i was talking about main issue where people died from suffocation. Unless this was the result of coordinate issue. Is your players have access to cmi.safeteleport permission node?

**Comment by Sergix7720** [comment]
Ohh ok I get it, sorry English is not my main languaje, yes they have it, I will take it away.

**Comment by Zrips** [comment]
But is this an issue with only those homes which coordinates got broken or with every home?

**Comment by Sergix7720** [comment]
With only the ones which coordinates got broken.

**Comment by aitechhkn** [comment]
all players on the server can't use /home and can only use /homes
I have added the cmi.safeteleport permission, but nothing changes

**Comment by Zrips** [comment]
@aitechhkn 
Any errors? And are you using chat based home list or GUI?

**Comment by aitechhkn** [comment]
no error, but player use /home doesn't teleported

**Comment by aitechhkn** [comment]
before the update using version 8.6.22.0 there were no problems
when it updates to 8.6.23.3 I get this problem

**Comment by aitechhkn** [comment]
Oh I found the problem, in this version /home does not directly teleport to the default Home, they must use /home Home to fix that I disable /home in alias.yml and use /cmi aliaseditor new home-cmi home Home

I think it's a bug /home

**Comment by Zrips** [comment]
@aitechhkn 
In case you have more than one home then you will need to provide home name, if not provided it should print out home list into chat or open home gui where you can pick home where you want to go.

**Comment by aitechhkn** [comment]
no, my player have one home not more

**Comment by Sergix7720** [comment]
Just in case it is needed, I think the homes just get bug when they are over 20000000 cordinates.

**Comment by Sergix7720** [comment]
It got fixed with the next update you published, thanks!
