### ISSUE TITLE
Can't teleport to coords/player within 200 blocks

### ISSUE THREAD

**Issue by supersnellehenk** [Zrips/CMI#3191]
**Description of issue:** Not being able to teleport to players/coordinates within 200 blocks. No errors in the console. When the teleport does work it gives a `moved too quickly!` warning in the console.

**Example**: Stand on (0,4,0) on a flatworld, TPPOS to (0,4,5) and it does not actually teleport you. Same with teleporting to a player standing on (0,4,5). When the player is standing on (0,4,200) the teleport does work. Same goes for TPPOS. Vanilla teleporting does still work with /teleport.

---

**Cmi Version (using`/cmi version`):** 8.6.23.3

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper(220) 1.15.2

**Comment by Zrips** [comment]
Och, its must be issue with ToSpawnBefore set to true in your config file while you dont have spawn point set. Will fix it with next build, meanwhile, you can ether set spawnpoint with /cmi setspawn or disable ToSpawnBefore in config file.
