### ISSUE TITLE
ClearInventory

### ISSUE THREAD

**Issue by TechnicalBro** [Zrips/CMI#3192]
**Description of feature/improvement request:**
ClearInventory command addition

---
### Detailed explanation of what it should do, when and in what situation: ###

Clears the players inventory when executed like in essentials.

### Basic explanation as to why this feature is needed and/or useful to have: ###

If you're going to clone essentials it's required.

**Comment by Whiteshiro278** [comment]
I think that this feature is already in the plugin

**Comment by LogGits** [comment]
1, CMI is not a clone of essentials. To say otherwise is an insult.
2, `/cmi clear` with confirmation has existed for a long time now.
