### ISSUE TITLE
Homes deleting when group changes

### ISSUE THREAD

**Issue by Ahmadh26** [Zrips/CMI#3193]
**Description of issue:**

When a user group changes, their homes get deleted or removed .. is there a way to prevent that?
---

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.6.22.2 BungeeCord -> 8.6.23.4

**Server Type (Spigot/Paperspigot/etc):** 
Server version: Paper(201) 1.15.2-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 
Server version: Paper(201) 1.15.2-R0.1-SNAPSHOT

**Comment by LogGits** [comment]
Can you confirm this happens on 8.6.23.4?

**Comment by Zrips** [comment]
@Ahmadh26 
Homes are not attached to players group or particular permission node. What does database look like for players who lost their homes? As i cant recal any code i would have made to remove homes even if total count was over allowed limit of their permission group. Homes can only be removed when removing them manually with a command.

**Comment by Ahmadh26** [comment]
@Zrips 
I downloaded the user data as a YAML. One of my users who had 14 homes has only 3 in the database for some reason, and I know for sure they had 14. 
This happened after a server restart.
They had 14 homes for 2 days.
Their group changed from VIP to member and back to VIP on the day the homes got lost. 

@LogGits 
Will test on a local server today and let you know.

**Comment by Zrips** [comment]
@Ahmadh26 
Do you have multiverse plugin? If so, was those homes in a world which is not a default one but created by that multiverse plugin?

**Comment by Ahmadh26** [comment]
@Zrips 
No, i have a bungee network consisting of 4 servers and all of them are linked to a MySQL database.

**Comment by Zrips** [comment]
I hope that they are not linked to same exact tables in that mysql. Do they?

**Comment by Ahmadh26** [comment]
i think they are 0_0

**Comment by Zrips** [comment]
There is a reason why we have this line near MYSQl setup
`  # ATTENTION! DON'T USE SAME DATABASE TABLES FOR MORE THEN ONE SERVER, YOU WILL HAVE UNEXPECTED ISSUES. EACH SERVER SHOULD HAVE ITS OWN DATABASE TABLE SETUP`
Data sync across servers will be implemented, but you cant use one table for more than one server.

**Comment by Zrips** [comment]
So i guess this will resolve your issue, will close this ticket.

**Comment by shovelbug** [comment]
having same issue, I setup playtime rewards as such
12hour:
  DisplayName: "&f12 hour reward"
  AutoClaim: true
  Description:
  PayFor: 43200
  Commands:
  - asConsole! lp user [playerName] parent set member
 so once a player hits 12 hours of in game playtime they rank up from default to member with luck perm
 but when they rank up it deletes their homes that are saved.....it only does this when they change usergroups....and only when it comes from the playtime rewards executing, if i just run /lp user [playerName] parent set member it promotes the user but the homes do not delete
 i also notice that the promote sometimes happens a second time like it will have promoted (using example name emmbo2 at 12 hours gametime but then it will promote emmbo2 again at 3 days playtime
