### ISSUE TITLE
Warn/Error SQL Operation not allowed on closed connection

### ISSUE THREAD

**Issue by AerWyn81** [Zrips/CMI#3196]
**Description of issue:**

---

This is an issue that appeared without any particular context and has spam / log + 15 MB of logs and required a server restart to fix the problem. This is the second time this error appears. There doesn't seem to have been any problem connecting to the database related to our host, but I can potentially ask them. We have enabled force saving data when a player disconnect, could this be the cause?

https://pastebin.com/kTFWScWX

---

**Cmi Version (using`/cmi version`):** 
8.6.23.3
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
211

**Comment by Zrips** [comment]
Will make some adjustments for data saving which should resolve this issue
