### ISSUE TITLE
Unexplained conflict with CMI bungee chat

### ISSUE THREAD

**Issue by vc606** [Zrips/CMI#3197]
**Description of issue:**

Discordsrv1.9 seems to conflict with CMI bungee chat, causes abnormal display on cross-server chat.

For example: 
Server B can see texts from Server A, but texts from Server B cannot be seen in Server A, or they cannot see each other.

I’m using the latest version and tried to reboot for several times and they still not working normally.
After recently updating cmi and Discordsrv, players reacted to this question.
config:
  DiscordSRV:
    Enabled: true
  BungeeMessages: true
  BungeePublicMessages: true
  BungeeStaffMessages: true

---

**Cmi Version (using`/cmi version`):** 
CMI 8.6.23.4 
**Server Type (Spigot/Paperspigot/etc):** 
paper-226
**Server Version (using `/ver`):** 
1.15.2 
**Relevant plugins (Delete if this isn't needed):**
 DiscordSRV-Build-1.19.0-SNAPSHOT-1587980975

**Comment by Ahmadh26** [comment]
I use discordsrv 1.9 and it's working fine on my bungee server and CMI. Does your members have permission for public bungee messaging on both servers? (cmi.bungee.publicmessages or something like that)

**Comment by Zrips** [comment]
@vc606 
This could be due to some failings in determining player amount in target servers. How many players you have in server A and server B when this happens usually?

**Comment by vc606** [comment]
About 20 to 40 players, this problem only recently happened

**Comment by vc606** [comment]
> @vc606
> This could be due to some failings in determining player amount in target servers. How many players you have in server A and server B when this happens usually?

https://github.com/Zrips/CMI/issues/3197#issuecomment-620014690

**Comment by vc606** [comment]
I spent some time today testing deleting viaVersion and deleting the MythicMobs mentioned above is still wrong and unable to chat, currently I have to find other bungee chat pluglin

**Comment by vc606** [comment]
Today I spent a lot of time upgrading to the latest version of 1.16.1 and cmi, and bungee chat seems to be much better. I can often see other servers chatting normally, but occasionally I can’t see it.

**Comment by Zrips** [comment]
Latest versions should have resolved most of the issues, if you still experiencing some of them, please let me know.

**Comment by vc606** [comment]
@Zrips 
Currently, my server bungee jumping chat is still often abnormal (usually some conversations are lost and not displayed)  This problem has bothered me for a long time
,Use -Dfile.encoding=utf-8 to increase my server startup parameters
Could it be caused by language coding?

BungeeMessages: true
BungeePublicMessages: true
BungeeStaffMessages: true


server:
Waterfall-377
paper-136 (1.16.1)
CMI8.7.8.0
config: 
https://pastebin.com/sH1Piser

Permissions:
GroupManager+
https://www.spigotmc.org/resources/groupmanager-1-7-1-16.40615/

https://upload.cc/i1/2020/09/30/Cpxe1g.jpg
