### ISSUE TITLE
BossBar is Seizure-Inducing in 8.6.23.5

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#3199]
**Description of issue:**
Not getting an error, unfortunately, but the HP BossBar as of today's update is persistent, stuck on the last mob killed, often flashing, and sometimes stacking. A relog seems to fix the error until something else is damaged. It's quite... distracting.

---

**Cmi Version (using`/cmi version`):** 8.6.23.5 BungeeCord

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-2040c4c-893ad93 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by blek-id** [comment]
And it lowers down TPS significantly as well.
![image](https://user-images.githubusercontent.com/26654664/80443441-70648b00-8939-11ea-81c6-c4e9bdc10d40.png)

**Comment by x1p** [comment]
I'm not getting a bossbar at all with for example vanish

**Comment by Zrips** [comment]
Fix is coming out with today's update.
