### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/CMI#32]
after uploading the new version to the server, an error occurred in my console
https://pastebin.com/MEmWQJC8

**Comment by LogGits** [comment]
This error is occurring in version 7.3.12.0. What multiworld managing plugin are you using?

**Comment by TheTopCz** [comment]
Multiverse-Core-2.5

**Comment by Zrips** [comment]
Its failed to load portal file. Can you paste it here so we can test out what and why failed? It will not have impact on plugin work, but there was no change done for portals in last couple updates. And issue seems to be comming from server it self. Try updating or downgrading your server if you did recent update.

**Comment by LogGits** [comment]
@TheTopCz any news on this? Is this error still occurring on the latest build?

**Comment by TheTopCze** [comment]
I'm sorry, I forgot to write off. Anyway, I did not show this error in latest build
