### ISSUE TITLE
[Suggestion] Prevent commands while sleeping (To help fix Spigot bug)

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3201]
Not saying this plugin has this, but with loads of plugins on the server and CMI being the core manager for many servers. I am hoping it would be possible to consider for CMI to include an option in config.yml for server owners to set from default false to true, to help prevent players from entering (certain) commands while they're sleeping. 

This is in relation to these types of issues: https://hub.spigotmc.org/jira/browse/SPIGOT-5637

When a player is asleep, I see on reason for them to enter commands, people are free to convince me otherwise in this github thread. I think chatting and /msg and /r is fine for example, but dealing with /vote and /marketplace and /pvpkit or whatever is something they can do when they're done sleeping.

**Comment by Zrips** [comment]
Ok.
