### ISSUE TITLE
Bossbar performance issue

### ISSUE THREAD

**Issue by AerWyn81** [Zrips/CMI#3205]
**Description of issue:**

Hi, we have a performance issue (19 tps -> 14/11/9/7/10/14) with messages in bossbar (flyc) :
https://i.imgur.com/WbetQdV.png

---

**Cmi Version (using`/cmi version`):** 
8.6.23.5
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
226

**Comment by Zrips** [comment]
Update to latest version, issue should get resolved with it.
