### ISSUE TITLE
Sleeping BossBar

### ISSUE THREAD

**Issue by mare-on** [Zrips/CMI#3207]
**Description of issue:**
When the night is over... sleeping bossbar is still here and sometimes there is not only one.. but two of them even while sleeping.

Images: [https://imgur.com/a/OokAxEW](https://imgur.com/a/OokAxEW)

**Cmi Version:** Latest 8.6.23.6
**Server Type:** Paper
**Server Version:** 1.15.2

**Comment by x1p** [comment]
I have to confirm this. For some players, the bossbar doesn't disappear when the day has started

**Comment by Zrips** [comment]
This should be resolved with next update
