### ISSUE TITLE
/fix alias

### ISSUE THREAD

**Issue by Mahieuq** [Zrips/CMI#3208]
I would like a /fix alias for the /cmi repair command, it is faster to type and most people are already used to /fix from plugins like essentialsx ect.

**Comment by Mahieuq** [comment]
Yea just found out that you can create your own aliases, so uhmm just close this I'm sorry.

**Comment by mercurialmusic** [comment]
There's a close button \/ right down there \/ where you can do that yourself as creator of the issue.

**Comment by Mahieuq** [comment]
> 
> 
> There's a close button \/ right down there \/ where you can do that yourself as creator of the issue.

Thank you! (I'm new on github so sorry)
