### ISSUE TITLE
public bungee message issue and idea :)

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#321]
CMI version: 7.7.1.1
Mc: 1.12.2 paper-spigot 

My request is  to add a function to disable the public bungee message
And now the problem: 
The problem is that if i have permission to false however  others can still see my messaging on other server even if i did set not to :( that's why a option to disable that in config would be nice. I do have a rank that has * permission but as show in image I don't have permission to that command, and no i have no op just rank with * so i am not really sure why when I message players on other server can see my messages :( 
- cmi.bungee.publicmessage.survival:
    value: false
- cmi.bungee.publicmessage.skyblock:
    value: false
- cmi.bungee.publicmessage.lobby:
    value: false
- cmi.bungee.publicmessage.*:
    value: false

Image that i don't have permission for that:
![issue](https://user-images.githubusercontent.com/1558228/39494528-a7f915ba-4d8e-11e8-8bf1-dc262b51b460.png)
However even if it say false it still shows my public messages on skyblock server :(

**Comment by Zrips** [comment]
Yea, its a cmi.bungee.publicmessages.skyblock permission node, you have cmi.bungee.publicmessage.skyblock there is S missing. Tho screen capture shows that you don't have access to that correct permission node. Strange. Will add option to disable public messages entirely with next build and you double check if you give correct permission nodes.

**Comment by arturek1666** [comment]
Just wanted to say that on the update info it say:
Added option to send public messages cross servers with cmi.bungee.publicmessage.[servername] permission node. So with bungeecord and appropriate permission node, you can talk in public chat cross servers.
With no S xD that's the reason i make mistake
