### ISSUE TITLE
Alias for /alert Does not Tab Complete or Work

### ISSUE THREAD

**Issue by RageYT** [Zrips/CMI#3210]
**Description of issue:**
I enabled all the aliases for the commands and tried using **/alert** but it didn't seem to work nor had any tab completes.

---

**Alias.yml**
```
  # /cmi alert $1-
  /alert: true
  #  
```
---

**CMI Version (using`/cmi version`):** 8.6.23.4 

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** Paper version git-Paper-143 (MC: 1.15.2)

**Comment by Zrips** [comment]
You might need to perform full server restart before this alias takes fulls effect. For tab complete, it dint had any, but will add player name completion for it with next version.
