### ISSUE TITLE
There's not enough information or tutorials available

### ISSUE THREAD

**Issue by tribrix** [Zrips/CMI#3213]
**Question: ** I am having issues making interactive holograms, setting commands to portals and wouldnt know where to start with particle effects on warps. The information is vague on the website and I can only find 3 videos on youtube that are outdated.

**Comment by Zrips** [comment]
To make clickable hologram, open its GUI and click on a stick icon. And thats that. You might need to relog for it to take appropriate effect but you should see effects when you click on it. After that you can set commands which should be performed which can be edited throw same gui by clicking on bow.
Warp particle effects can be defined at bottom of config file under TeleportEffects->Warp where you have 2 extra sections: From, To. Where you will need to define name of created effect which can be found just above that in Particles section. Just insert particle name and you are done.
This uses panimation command/feature where you can create particle animations and use them in teleportions or in general purpose areas. As example would be 
```
  Warp:
    From: 'TpUp'
    To: 'TpDown'
```

**Comment by tribrix** [comment]
Thank you
