### ISSUE TITLE
/Shadowmute command

### ISSUE THREAD

**Issue by kekke3r** [Zrips/CMI#3214]
Description:
When applied on a player he will still be able to send and recieve chat or send /msg but the rest of the players will not see what the given player is writing and will not recieve any /msg coming from that player.

Commands:
/shadowmute [playerName] [time]: shadowmutes a player without letting him know
Could be unmuted with the /unmute [playerName] command

Why this feature could be useful:
For muting several toxic players that just like to spam or insult without letting them know, if you only mute or jail or ban them they could re-enter in the server (if it is in offline mode) with another account and continue to annoy other players. If they feel ignored (because they don't know they are shadowmuted) they will probably leave the server for good.

**Comment by Zrips** [comment]
Next version
