### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Pixelidon** [Zrips/CMI#3215]
**Description of issue:**
My server console keeps getting spammed with the error "Can't find a world with this name!" even after a fresh install of CMI. I'm not using Multiverse and all my worlds are correctly linked to CMI (can use any CMI's commands with no issue while on my server and see the GUI properly).

---

**ERROR:**
```
[Server thread/INFO]: Can't find a world with this name!
```
---

**Cmi Version:** v8.6.23.6

**Server Type:** Spigot

**Server Version:** CraftBukkit version git-Spigot-a03b1fd-5838285 (MC: 1.15.2)

**Relevant plugins:** WorldEdit, AsyncWorldEdit, WorldBorder, WorldGuard, EpicWorldGenerator, Luckperms, Vault, SelectionVisualizer, Dynmap

![server_paths_](https://user-images.githubusercontent.com/64536046/80613059-0e8d4980-8a3d-11ea-9120-52415d1f80a6.PNG)

[latest.log](https://github.com/Zrips/CMI/files/4552526/latest.log)

[config.txt](https://github.com/Zrips/CMI/files/4552533/config.txt)

**Comment by Zrips** [comment]
This message appears when we cant determine world by provided location. As i cant really test EpicWorldGenerator i cant say whats going on with it. 
When does this error start appearing? On player login or straight after server startup?

**Comment by Pixelidon** [comment]
Hello, I managed to find what caused this issue, it was a command runned by a commandblock which has been overrighted by CMI, changing the arguments needed to efficiently run it.
