### ISSUE TITLE
Rt portals

### ISSUE THREAD

**Issue by MaybeG** [Zrips/CMI#3216]
**Question: What Happen With my Portals is not working with RT , But old world can use the rt new world cannot to use rt **

**Comment by MaybeG** [comment]
rt %cmi_user_name% Wild [ Working ]
rt %cmi_user_name% Wildness [ Not Working ] [ New World ]

**Comment by Zrips** [comment]
Try using [playerName] variable instead

**Comment by LogGits** [comment]
@MaybeG if this was resolved feel free to close the issue 🙂
