### ISSUE TITLE
Warp tab completion does not work reliably

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#3217]
Since Sunday's tabcomplete optimization (version 8.6.23.4) it's no longer possible to complete all warps via tab. This affects both new and old warps. There is no recognizable pattern. For some warps the tabcomplete work for others not. For example, /warp Atlantis will tab complete, but /warp Auction House will no longer tab complete.

CMI 8.6.23.6
Paper 1.15.2 - 217

**Comment by Zrips** [comment]
Hmmm, in general i added limitations in how many tabcompletes we would send to the player, this was added to avoid insane amounts of data being sent. But it looks that limitation was to much of a limitation. Will increase it

**Comment by TheoRetisch1** [comment]
Thank you it works well in the latest version 👍
