### ISSUE TITLE
Chat Lock Up + No Teleportation

### ISSUE THREAD

**Issue by InDirectVariant** [Zrips/CMI#3218]
**Description of issue:**
After the most recent update, our chat has been intermittently locking up with a message stating "You can't send chat messages.". At this moment we are not sure of the exact cause, but we have narrowed it down to either the new anti-bed commands or the new homes optimization. We think that maybe mistyping the name of a home or simply doing /homes is causing the lock.

---

**Cmi Version (using`/cmi version`):**  8.6.23.6 Bungee

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Tuinity-"cc29709"

EDIT 29-04-2020: We have now realized that teleportation using /home and /tppos (at the very least) doesn't work. Users are unable to actually teleport. No errors are being thrown in our console.

**Comment by Zrips** [comment]
This message you provided doesn't seem to be from CMI itself, so this will be caused by another plugin. 
For teleportation, do you have ToSpawnBefore set to true in config file?

**Comment by InDirectVariant** [comment]
We have ToSpawnBefore marked as False.

We've narrowed down the issue to another plugin blocking teleportation between worlds and then blocking chat messages. 

Thanks for the tip on the message not coming from CMI, that's what helped us narrow it to another plugin.

All the best!
