### ISSUE TITLE
Fly mode turned on for ground logins

### ISSUE THREAD

**Issue by delbertina** [Zrips/CMI#3219]
**Description of issue:**
This is different than #3151 

Updated from 8.6.22.1 to 8.6.23.6 and now everyone with /fly permissions login with fly mode turned on and no message in chat notifying them of this. This is happening when logging in on flat ground. When denying the safelogin perm this behavior no longer persists.

It would be nice if players were notified when put into fly mode on login and also if safelogin would not put players in fly mode when they login on the ground. : )

---

**Cmi Version (using`/cmi version`):** 
8.6.23.6
**Server Type (Spigot/Paperspigot/etc):** 
Paper 1.15.2 Build # 227
Also tested on Tunity 1.15.2 d23eae4

**Comment by Zrips** [comment]
Excellent point. Will make some adjustments and it should be working as expected.
