### ISSUE TITLE
Crafting slots are dropped on death

### ISSUE THREAD

**Issue by sibraxlis** [Zrips/CMI#3221]
**Description of issue:**
Crafting slots are dropped when you die even if you're set to keep your inventory. This is something I wasn't having happen with essentials. I'm using craftslot commands to store items there.

**Cmi Version (using`/cmi version`):** 
8.6.23.6
**Server Type (Spigot/Paperspigot/etc):** 
Tuinity 1.15.2-R0.1-SNAPSHOT (Paper spigot)
**Server Version (using `/ver`):** 
tuinity version git-Tuinity-"e4674f4" (Git-paper-217 MC 1.15.2)
**Relevant plugins (Delete if this isn't needed):**
CraftSlotCommands

**Comment by Zrips** [comment]
I need link to this plugin you are using to achieve this functionality. Can't really find it, unless I'm blind.
