### ISSUE TITLE
[Request] Clickable /dback command function!

### ISSUE THREAD

**Issue by PhracKko** [Zrips/CMI#3226]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
The / dback command telports to the previous location after the user dies. Rather than typing this command, I would like to add a function that replaces / dback by clicking and moving the user's dead location when it appears in the chat( x, y, z ).
### Basic explanation as to why this feature is needed and/or useful to have: ###
I think these little functions are the charm of CMI.

**Comment by Zrips** [comment]
Ok.
