### ISSUE TITLE
World freezing at particular time in night

### ISSUE THREAD

**Issue by vicllow** [Zrips/CMI#3228]
**Description of issue:**
Ok. So when i am on the server, in the world is always night. I tried commands like:

/time unfreeze
/gamerule doDaylightCycle true

But after few minutes, time in the world is back where it was before i performing that command. I don't know what to do.

---

**Cmi Version (using`/cmi version`):** 
Command don't work
Using CMI 8.6.23.6

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
Paper version git-Paper-227 (MC: 1.15.2)

**Comment by Zrips** [comment]
you might have autorealtime turned on, try performing /time autorealtime stop
