### ISSUE TITLE
Block Color Code Nicknames

### ISSUE THREAD

**Issue by Jaimss** [Zrips/CMI#3230]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Right now, my players can set their nicknames to `&f`, which gives them an invisible name basically, and I would like to disable it.
Current Config: https://hastebin.com/piqoromuno.coffeescript
I have tried blocking it using the `ValidNicknameRegex` as well as the `NickName.BlackList`, however I can't seem to get it to stop players from using `&f`, `&3`, etc.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Above.

**Comment by Zrips** [comment]
have you tried taking away **cmi.colors.nickname.white** permission node from them?

**Comment by Jaimss** [comment]
Yes they shouldn't have permission for nickname colors.

**Comment by Zrips** [comment]
They shouldn't or they don't have?

**Comment by Jaimss** [comment]
Idek what I did. I fiddled around with a bunch of settings and got it working it seems.
I think they may have had one of the bypass permissions for some reason.

Only thing is now, the `ValidNicknameRegex` doesn't seem to be working (or I just don't know any regex). Mine is set as: `ValidNicknameRegex: '[a-zA-Z0-9]'`, and players are still able to nick as stuff like `***` and `----`.

**Comment by Jaimss** [comment]
Nevermind I solved it. I had to do `ValidNicknameRegex: '[^a-zA-Z0-9]'`

**Comment by Jaimss** [comment]
Oh wait how do I block formatting like `&o`, `&l`, etc?

**Comment by LogGits** [comment]
@Jaimss Try `(?i)&[a-fk-or0-9]` that should block all chatcolours with lowercase & uppercase. Leme know if it works (havent tested it but it should work in theory)

**Comment by Jaimss** [comment]
My regex should only be a-z, A-Z, and 0-9 characters.

They do not have any of the colors.nickname permissions. and `cmi.colors.nickname.*` is "Hard set to false" by my perms plugin.

Everything I need to be blocked is blocked, except they can use formatting and colors in their name for some reason. I am not having the issues anymore with setting nicks like `&f` or `&3` to bypass it. They can still do `&4Test` `&oTest` etc.

**Comment by Jaimss** [comment]
I just made my own nickname plugin.
