### ISSUE TITLE
CustomText to Book underlined words

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#3232]
**Description of issue:**

When the /cmi getbook command is used to get the book, the underlined words do not appear.

-----------------------
**CMI Version: 8.6.24.0**
**Server Type: Spigot**
**Server Version: 1.15.2-R0.1-SNAPSHOT**
**Vault Version: 1.7.2-b107**

**Comment by Zrips** [comment]
Should be resolved now
