### ISSUE TITLE
Sleeping doesn't exclude vanished players

### ISSUE THREAD

**Issue by cryoten** [Zrips/CMI#3235]
**Description of issue:**
When players are sleeping, players who are vanished are not excluded. It will repeatedly say skipping entire night, but the night will not skip.

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.6.24.0
Server Version: Paper(227) 1.15.2-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 
git-Paper-199 (MC: 1.15.2)

**Comment by Zrips** [comment]
Good point. Will fix it.
