### ISSUE TITLE
Sleeping Notice skipping entire night

### ISSUE THREAD

**Issue by thenullmatrix** [Zrips/CMI#3236]
**Description of issue:**

If one player is in the overworld and all the other players are in the nether or end. It displays skipping entire night to all players.
---

---

**Cmi Version (using`/cmi version`):** 
8.6.24.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.15.2
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Och, will exclude other worlds.
