### ISSUE TITLE
CMI social spy private message placeholder bug.

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#3237]
**Description of issue:**
At random times, the placeholders for /cmi socialspy does not displayer player names

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://imgur.com/a/i0WMYCG

Both commandspy and socialspy are shown in the image between two different conversations by different players during the same time.

---

**Cmi Version (using`/cmi version`):** 
8.6.23.6

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot 1.15.2

**Server Version (using `/ver`):** 
Paper(226) 1.15.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Are those messages from bungee network or local ones?

**Comment by BboyZeroOne** [comment]
local

**Comment by Zrips** [comment]
Will be making some changes, if issue persists after next update, let me know.
