### ISSUE TITLE
CMI Ignore bug.

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#3238]
**Description of issue:**
/cmi ignore does not work.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://imgur.com/a/VfhLdC7

Image shows the list of players ignored with '/cmi ignore' but I would still be able to see their chat messages.

---

**Cmi Version (using`/cmi version`):** 
8.6.23.6

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot 1.15.2

**Server Version (using `/ver`):** 
Paper(226) 1.15.2-R0.1-SNAPSHOT

**Related Plugin**
Deluxe Chat (May be involved with this)
https://www.spigotmc.org/resources/deluxechat.1277/

**Comment by Zrips** [comment]
Go to config file and change **IgnorePublicMessage** into **true**

**Comment by Zrips** [comment]
And make sure sender don't have **cmi.command.ignore.bypass** permission node, which can bypass this.

**Comment by BboyZeroOne** [comment]
I think this should be enabled by default.
