### ISSUE TITLE
Wrong Intger

### ISSUE THREAD

**Issue by Steev93** [Zrips/CMI#3239]
**Description of issue:**
http://prntscr.com/s9l9kq

Showing wrong name or wrong placeholder or the target name??

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```

**Cmi Version (using`/cmi version`):** 
8.6.24.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-214
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
You are performing command /fly if Dredlore is online, which in this case worked as it should have. If you wanted to change Dredlore fly mode then you should have added his name like **/ifonline Dredlore fly Dredlore**

**Comment by Steev93** [comment]
@Zrips  I did this and that command "/ifonline Dredlore fly Dredlore" But it shows my name after chat

Eg. Here, http://prntscr.com/s9llf3

I typed the command twice
