### ISSUE TITLE
Vanish interact and block break

### ISSUE THREAD

**Issue by Federico2806** [Zrips/CMI#3241]
Hi, i`ve a problem with the Vanish, i can break block and interact with door etc even with them disabled in the /vanishedit.

Another thing, is there a way to set the default thing disabled and enabled in /vanishedit? For example i want that everyone in vanish have nightvision on, is it possible to set this as default?

Sorry for bad english.

**Cmi Version: 8.6.24.0

**Server Type: Paperspigot

**Server Version: Paper(98) 1.15.2-R0.1-SNAPSHOT 

**Relevant plugins: StaffPlus (For vanish inventory and back-to-pos tp)

**Comment by Zrips** [comment]
Why would you not want to be able to break blocks or interact with objects? It is something you would do intentionally after all, and having extra checks for each block break, place and interaction only add bunch of extra checks while all of this is based on player actively performing those actions while he is in vanish mode. 

For defaults, go to config and you have vanish section where you can define default values for each of those.

**Comment by Federico2806** [comment]
Yes, i want that player cant interact with nothing and cant break nothing by default in vanish. After this they can interact by the vanishedit if its needed. is it possibile?

**Comment by CloudeLecaw** [comment]
yes?
  Defaults:
    damageToEntity: false
    playerDamage: false
    itemPickup: false
    mobAggro: false
    interaction: false
    noisyChest: false
    informOnLeave: false
    informOnJoin: false
    nightVision: true
    bossbar: true
    afkcommands: false
    PrivateMessages: false
    relogDisable: false
    noMessages: false

Dont give thenm Access to vanishedit!
Thse setting onl work aslong the have not changed it with vanishedit
if they allready chaged it then u need to change their settings with vanishedit
