### ISSUE TITLE
Weird home removal behaviour

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#3242]
**Description of issue:**
Opening another user's homes using `/homes {user}` then shift rightclicking to remove the home removes the home. It then opens the player who typed the command's homes instead of reopening `{user}`'s homes.

---

**Cmi Version (using`/cmi version`):** 8.6.23.6

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.15.2 build 226

**Comment by Zrips** [comment]
Will be fixed with next version
