### ISSUE TITLE
Tp idea

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#3243]
**Description of feature/improvement request:**
It could be a good idea to make it so when a player types /tp but doesn't have permission to use the command, automatically make it use `/tpa` (or `/tpahere` (if they use /tphere)). 

---
### Detailed explanation of what it should do, when and in what situation: ###
Would apply to people typing /tp or /tphere without permission. If the player has permission to /tp and /tphere it should function as normal. Otherwise it would register the command usage as a /tpa or a /tpahere.

### Basic explanation as to why this feature is needed and/or useful to have: ###
It's more of a Quality of Life Improvement.

**Comment by CloudeLecaw** [comment]
i like the idea! <3

**Comment by mercurialmusic** [comment]
I'm a fan. People are constantly trying /tp instead of /tpa. It's a little silly.

**Comment by Zrips** [comment]
Will be added with next update.
