### ISSUE TITLE
Regex wrong when url is longer?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3244]
Hello, i tied to setup a filter urls postet in the Chat.

They should be marked as [Link] without the issues that if you What thinks like Hallo.Hello that this
counts as link
here is my used RegEx:

`LinkRegex: ((http|https|ftp|ftps)?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|(http|https|ftp|ftps)?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})`

my Problem:

if i use a shorter http. htpps, or ftp or ftps link it works fine, but with a longer link i have an issues.

![image](https://user-images.githubusercontent.com/12080017/80912945-fa995e80-8d40-11ea-9a3b-9beae49be8d5.png)
This happens with this link
https://www.mc.lululand.de/wiki/index.php/Features:Events

i also tried:
![image](https://user-images.githubusercontent.com/12080017/80913178-f4a47d00-8d42-11ea-9bf8-576c8e025f22.png)
http://mc.lululand.de
looks like there is a problem because of one more dots in the links? :3

So what is my problem

Note: Why i am not using this?
`((http|https|ftp|ftps)\:\/\/)?[a-zA-Z0-9\-]+\.[a-zA-Z]{2,3}(\/\S*)?`

This one has the Error when Someone wrties like "Hey das ist.aber toll"
then ist.aber is shown as [Link] - i count this as an issues because of this regex.

mybe u know an other regex that creats all to [link] no matter what comes after if it starts with http://, https,//, ftp://, www., or ftps://,?

**Comment by LogGits** [comment]
Try with:
```
`(?i)(\w*:\/\/)?(\w*\.){2,}\S*`
```
`?i` makes the check case insensitive
`(\w*:\/\/)?` checks for anything that has `://` (the ? makes this check optional)
`(\w*\.){2,}` checks for website stuffz (test.com) with recurring subdomains added
`\S*` gets the rest of the string before a whitespace

**Comment by CloudeLecaw** [comment]
Oh this works great so long so i just need something if someone just write a link  with "www."
like   www.google.de

**Comment by LogGits** [comment]
no problem im glad you were able to find a good one 🙂
