### ISSUE TITLE
Chatrooms

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#3248]
Hello, I always have users chatting in groups about everything possible. I often wish that you could go to your own chat room. At first I thought it would work with / chat but that is only possible for 2 people. Would it be possible for users to create their own chat room? or that the / chat command allows more than 2 users?

I also don’t want to use a new plugin because I fear that it could overlap with Cmi

**Comment by Zrips** [comment]
Okey.

**Comment by Blueeyestar** [comment]
huge thanks that it worked so quickly .. I'm really impressed with what you can do !!

**Comment by Blueeyestar** [comment]
great that my idea with the chat room worked so quickly. Now I still have little difficulty with it. with / chat NAME I create a room. I thought it should be called / chat chatRoomName NAME. The problem is I can no longer invite users into the room because they simply create the room with the name. and no rooms are shown in / chat list.
