### ISSUE TITLE
CMI Kits Console error.

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#3250]
**Description of issue:**
Getting console errors despite kits.yml was never touched and kept as default.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Console Error:
https://pastebin.com/fuKegxWa
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Kits.yml
https://pastebin.com/aBUJRiFr
```

---

**Cmi Version (using`/cmi version`):** 
8.6.24.1

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
1.13.2

**Comment by SenseiMunchkin** [comment]
Maybe try deleting the file and letting it refresh? I checked a copy of kits.yml in my directory and you're missing a lot of settings. If you've never touched this file, it may be lacking features that were added/updated on in newer versions.

**Comment by BboyZeroOne** [comment]
Alright, let me try that out.

**Comment by Zrips** [comment]
You commented out only tiny part of every single kit you have there, which created invalid yaml file. Things like this cant be used, ever. Ether comment out every single line, remove them entirely or simply set kit to disable mode. Otherwise you will have issues like this.
```
#Newbie:
  CommandName: Newbie
```
