### ISSUE TITLE
Glow Effect on items

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3254]
When an item got enchanted it normaly get a nice glow effect.

![Snag_17a210e5](https://user-images.githubusercontent.com/12080017/81122612-85d94680-8f31-11ea-83b3-2941645305b5.png)

Is it possible to add a "new" enchantmant that just gives the Item the enchant glowing like seen in the picture without adding an enchantment skill on it? :)

Finaly with this items could get a nice glow effect - for further useage (like a special item)

**Comment by Blueeyestar** [comment]
that would really be a great effect I also wish for :)
