### ISSUE TITLE
Nether Roof Prevention

### ISSUE THREAD

**Issue by FestusDM** [Zrips/CMI#3256]
**Question: **
 I know that CMI has a way of preventing players going to the Nether roof under
```
  # Will teleport players down from nether 'roof'
  PreventPlayersOnNetherRoof: true
```
Is there any way to set how far they teleport or is this an all or nothing kind of thing?

**Comment by CloudeLecaw** [comment]
The Netherroof is count for the Nether and start at a high of 129 only in the nether ;)
This high can only be changes with other plugins, but if you dont use this then this just means that player cant go to thi Y-High inside the nether. this is value that normaly cant and dont need to be changed (Nether roof is at 128 so it starts at 129)

**Comment by Zrips** [comment]
@FestusDM 
Players will be teleported down, if possible. If not then we will teleport them to spawn location.
