### ISSUE TITLE
Anvil color permission not working

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#3258]
**Description of issue:**

The anvil color permission does not work, when you try to add a colorcode within the anvil menu, it will just add it to the name.

![image](https://user-images.githubusercontent.com/5664135/81166972-b900f180-8f94-11ea-8d8e-dd1e1758457b.png)

CMI 8.6.24.1

**Comment by CloudeLecaw** [comment]
What permissions have you used? and what was setup in your config?
usually its just the permisison "cmi.anvil.colors"

**Comment by Sikatsu** [comment]
Thanks for your response, it turned out the module was set to false. xD
