### ISSUE TITLE
[REQUEST] nightvision command

### ISSUE THREAD

**Issue by lancce-Wolf** [Zrips/CMI#326]
Description of issue or feature request:

hello everyone, i would like to suggest a feature for CMI.
a command where you can toggle nightvision, like /cmi nightvision or /cmi nv
would be usefull to give this to builders with the needed permission node. like cmi.command.nightvision
so they can toggle it on and off

Cmi Version (using`/cmi version`): 7.7.1.2
Server Type (Spigot/Paperspigot/etc): Spigot
Server Version (using `/ver`): 1.12.2

**Comment by tmellen** [comment]
currently you can use "/cmi effect nightvision". Works like a charm!

**Comment by lancce-Wolf** [comment]
ye but that is only temporary, a command like this would be pretty usefull tho

**Comment by LogGits** [comment]
This can be done using the /cmi customalias command.

**Comment by lancce-Wolf** [comment]
okay i got it to work,
i used this command to turn nightvision on for 1 hour:
`/cmi aliaseditor new nvon-cmi effect night_vision [playerName] 3600`
and to turn it off i used:
`/cmi aliaseditor new nvoff-cmi effect [playerName] night_vision clear`
so i can now turn it on with `/nvon` and turn it off with `/nvoff`
but how can i set the permissions for these commands?

**Comment by HomeLandingsDE** [comment]
> 
okay i got it to work,
i used this command to turn nightvision on for 1 hour:
/cmi aliaseditor new nvon-cmi effect night_vision [playerName] 3600
and to turn it off i used:
/cmi aliaseditor new nvoff-cmi effect [playerName] night_vision clear
so i can now turn it on with /nvon and turn it off with /nvoff
but how can i set the permissions for these commands?



i use this with spaces betwen - /nv on | /nv off - super simple

**Comment by CloudeLecaw** [comment]
okay i got it to work,
i used this command to turn nightvision on for 1 hour:
/cmi aliaseditor new nvon-cmi effect night_vision [playerName] 3600
and to turn it off i used:
/cmi aliaseditor new nvoff-cmi effect [playerName] night_vision clear
so i can now turn it on with /nvon and turn it off with /nvoff
but how can i set the permissions for these commands?
a

one of the easy Question here i love u^^
here  Little Suggestion and i hope u udnerstand how to use it for your command
use the commandalias.yml for this
```
  non:
  - perm:cmi.command.customalias.non! cmi effect $1 night_vision 1800
  - perm:cmi.command.customalias.non! cmi effect $1 water_breathing 1800 5
  noff:
  - perm:cmi.command.customalias.non! cmi effect $1 night_vision clear
  - perm:cmi.command.customalias.non! cmi effect $1 water_breathing clear
```
now u have two command "/non" and "/noff" they turn on nightvision and water breathing
but only if oyu have the permision: **cmi.command.customalias.non**

i hope this helps, if u want to know more About this then read this page:
https://www.spigotmc.org/wiki/cmi-custom-alias/
