### ISSUE TITLE
Global/local chat spy

### ISSUE THREAD

**Issue by div2005** [Zrips/CMI#3260]
There is a 'cmi.chat.rangebypass' permission that allows people with it to see and send messages from any distance on the server. However, this can become inconvenient to use for supervision of local chat to prevent abuse and server rule violation. This is because it removes the ability to write in local chat. Chat differentiation is very useful if server moderators/administrators need to convey some information for nearby players.
Summary: Add a permission or command that allows spying on local chat across the server  without messing with ability to sent local and global messages separately.

**Comment by CloudeLecaw** [comment]
have you tried to use ! before?
