### ISSUE TITLE
Totem cooldown does not apply well.

### ISSUE THREAD

**Issue by ApYukiple** [Zrips/CMI#3261]
Totem:
  RemoveFromInventory: true
  Cooldown:
    Use: true
    Time: 600

No matter how many times you set it, the totem function goes into a wrong state when you restart the server.
Setting this to true in the command does not apply to players who join the server with only the command user, and the cooldown limit does not work.

**Comment by Zrips** [comment]
Totem cooldown is not being saved and will not transfer over server restart, it never was made with intention to have its cooldown transfered over, this would require aditional collumn in database.

**Comment by ApYukiple** [comment]
What? RemoveFromInventory: true will work for all players but cooldown will not work. If you do / toggletotem yourself and you don't have true, no cooldown will be applied.
This will not limit cooldowns to players who do not use the command, and new players can avoid cooldowns.
Please give me a wiki or tutorial on how to make it true for all players.

**Comment by Zrips** [comment]
Och, sorry, i misunderstood your report, will fix it with next update.

**Comment by ApYukiple** [comment]
thankyou!

**Comment by ApYukiple** [comment]
Latest modified version: 8.6.24.3

I confirmed that the cooldown was done properly.
There is one problem.
The boss bar is not displayed.
If set to true in / toggletotem, the boss bar appears and is working fine,

Is it a specification? Is it a bug?

**Comment by Zrips** [comment]
That command only toggles bossbar, you can turn it on or off, but it should not effect cooldown itself when doing so

**Comment by ApYukiple** [comment]
That is, if you want to give the player permission to toggletotem and know the cooldown seconds. Does that mean you have to execute the command yourself and set it to true?

Players will not see the bossbar seconds when the cooldown is applied.

The cooldown seems to be applied because the chat says totem usage was denied due to its cooldown time.

Is it a bug?

**Comment by Zrips** [comment]
By default everyone should see bossbar cooldown, after you toggle it, then it will be hidden, cooldown should still be applied as before, only bossbar message is no longer visible. 
Tho only now i realized that i need a clarofication on which server version you are running, as bossbar only works on 1.9 and up.

**Comment by ApYukiple** [comment]
That setting is now reversed.
Cooldowns apply, but bossbar seconds are not displayed.
After using the command, it will be ture and the bossbar will be displayed.

I have built and used the latest spigot.
  1.15.2 spigot last

With or without op permission, bossbar does not appear and cooldown seems to be applied in both cases.

![2020-05-11_03 08 57](https://user-images.githubusercontent.com/48202134/81506956-d89d6e80-9334-11ea-8f4a-94b609ceeea0.png)

**Comment by Zrips** [comment]
Cooldown should be applied in any case, op or not. This command is only visual one, it will only toggle bossbar visibility on and off, nothing more.

**Comment by ApYukiple** [comment]
As in the image, the participant players will not see the bossbar. But as you can see in the chat section, it says that it is in the process of cooling down.
![4d309d6cacdfdb8b85fcc901b7ded920](https://user-images.githubusercontent.com/48202134/81507200-aa209300-9336-11ea-9f69-c75b6498f6df.png)
