### ISSUE TITLE
Sitting levitation

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#3262]
**Description of issue:**
When a player sits on a chair, then breaks the block, he sits in mid air

How to reproduce:
- Player places a chair a few blocks above surface
- Places 2 blocks besides the chair
- Removes the middle block and replaces it with a piston
- Extend piston
- Removes all blocks
- Player still levitates in sitting position in mid air.
![Screenshot_20200507_151721](https://user-images.githubusercontent.com/28690790/81299064-f4bfb800-9075-11ea-8c7c-533eaaa1789a.png)
![Screenshot_20200507_151736](https://user-images.githubusercontent.com/28690790/81299087-fa1d0280-9075-11ea-97c0-1430c585208d.png)
![Screenshot_20200507_151751](https://user-images.githubusercontent.com/28690790/81299095-fe492000-9075-11ea-8118-fa1c90ec4948.png)

---

**Cmi Version (using`/cmi version`):** 
CMI 8.6.24.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-251 (MC: 1.15.2)

**Comment by CloudeLecaw** [comment]
arr this is no bug. Its normal and also this report is more like a trollscrenaio 🗡️ 

I would not say this is a bug this is trolling. and has nothing to do with regular useage

What you can do is not allow others to interact when sit (that didnt prevent the not sitting friend from trolling)

**Comment by x1p** [comment]
I presume you mean the setting `RemoveFromChairOnDamage: true`
I have that one on `true` as well just like you.
Nevertheless the sitting behaves like that.
The chair is probably not recognized because the piston moved it.

I'm not sure how to prevent these trolls.
I was hoping the armorstand can have gravity or the moved block would cause "damage" or the chair could be recognized if broken once moved.

I'm all ears for suggestions

**Comment by CloudeLecaw** [comment]
`RemoveFromChairOnDamage: true`
This setting has nothing to do with the chair
It tell you if the player shoud get up from the chair if he take damage (may from a zombie next to him or a player that hits him)

Currently there is no Protection or anything to prevent this kind of Pistontroll.
Noone ever thought about why someone should remove the chairblock at the moment your sitting on it.
What may could be added: **Chair is protected from moving + destroying** when someone sits on it.

This also would pervent your problem and is the may only logical solution and may easier to create for a further version then changing the whole chairworking process.


If you think this feature is nessesary **please create a Feature Request not a bug report** :-3
with a name like "Protection for Chairs" and make a little description why you think this feature would be nessesary. Also you may can link to this allready created bug report.
