### ISSUE TITLE
Mob Name

### ISSUE THREAD

**Issue by DJDhuster** [Zrips/CMI#3269]
Hello, I want to ask is it any possibility to change mob name to translated one in my language. Particuraly I care about name in ranks requirement, for example instead of Mob kills: Pig, I want to have Mob kills: name of  entity in my language

**Comment by CloudeLecaw** [comment]
The answer is yes this is possible ;) look in your language file

**Comment by DJDhuster** [comment]
I’ve already changed it, but it doesn’t change names in ranks requirements

**Comment by CloudeLecaw** [comment]
scan u post a screenshot? :3

**Comment by DJDhuster** [comment]
Yep, sure thing [
![prove1](https://user-images.githubusercontent.com/65013573/81499590-fe8f2880-92cc-11ea-8db5-c19ae3050e68.png)
![prove2](https://user-images.githubusercontent.com/65013573/81499594-064ecd00-92cd-11ea-9c74-3f5f36a8e6e0.png)
![prove3](https://user-images.githubusercontent.com/65013573/81499605-11096200-92cd-11ea-9da2-2497f00263d8.png)


](url)

**Comment by Zrips** [comment]
Small bug, will be fixed and you should see translated names in rankinfo from now on.
