### ISSUE TITLE
[FR] setwarp enchancement

### ISSUE THREAD

**Issue by GrimPod** [Zrips/CMI#327]
Description of issue or feature request:

It would be really nice if there was another variable option in the /setwarp command
This True/false Variable would tell it whether or not it would auto generate the lore for the warp GUI

Cmi Version (using`/cmi version`): 7.7.1.2
Server Type (Spigot/Paperspigot/etc):  Spigpt
Server Version (using `/ver`): 1.12.2

**Comment by GrimPod** [comment]
In the setwarp command itself
/cmi setwarp [warpName] (true/false) (hand) (slot)
Currently there's:
 - name,
 - true/false - for needs the perm nodeZ
 - hand - to set it as the item in the hand,
 - slot for where in the GUI
What im thinking is why is there option to set the icon to the item in their hand, but no to keep its name+lore, which auto lore gen replaces with the cords of where it warps you to
it would be to just have another open for 
 - lore - which would keep the name of the item + lore, done simply by making it toggle the auto lore gen off

**Comment by Zrips** [comment]
Next update should support this one.
