### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by tribrix** [Zrips/CMI#3270]
**Question: **
Just wondering what might be causeing this players online console spam.

> 08.05 21:57:29 [Server] INFO ========================
> 08.05 21:57:29 [Server] INFO Players online 0/100
> 08.05 21:57:29 [Server] INFO ========================
> 08.05 22:00:29 [Server] INFO ========================
> 08.05 22:00:29 [Server] INFO Players online 0/100
> 08.05 22:00:29 [Server] INFO ========================
> 08.05 22:03:29 [Server] INFO ========================
> 08.05 22:03:29 [Server] INFO Players online 0/100
> 08.05 22:03:29 [Server] INFO ========================
> 08.05 22:06:29 [Server] INFO ========================
> 08.05 22:06:29 [Server] INFO Players online 0/100
> 08.05 22:06:29 [Server] INFO ========================
> 08.05 22:09:30 [Server] INFO ========================
> 08.05 22:09:30 [Server] INFO Players online 0/100
> 08.05 22:09:30 [Server] INFO ========================
> 08.05 22:12:30 [Server] INFO ========================
> 08.05 22:12:30 [Server] INFO Players online 0/100
> 08.05 22:12:30 [Server] INFO ========================
> 08.05 22:15:30 [Server] INFO ========================
> 08.05 22:15:30 [Server] INFO Players online 0/100
> 08.05 22:15:30 [Server] INFO ========================
> 08.05 22:18:30 [Server] INFO ========================
> 08.05 22:18:30 [Server] INFO Players online 0/100
> 08.05 22:18:30 [Server] INFO ========================
> 08.05 22:21:30 [Server] INFO ========================
> 08.05 22:21:30 [Server] INFO Players online 0/100
> 08.05 22:21:30 [Server] INFO ========================
> 08.05 22:24:30 [Server] INFO ========================
> 08.05 22:24:30 [Server] INFO Players online 0/100
> 08.05 22:24:30 [Server] INFO ========================

**Comment by CloudeLecaw** [comment]
be sure this has to do with CMI? :3
i would search first in the sheduler.yml if you have actived some stuff like this.

**Comment by Zrips** [comment]
This is caused by some external plugin which calls player list to make sure that server is still online. You can try using Multicraft->DisableList: true in case you are using Multicraft hosting
