### ISSUE TITLE
switchplayerdata is broken (i thik the api too)

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#3271]
**Description of issue:**
do /switchplayerdata playerA playerB
it say >....=>.... [14:46:54 INFO]: Use: /switchplayerdata [sourcePlayerName/uuid] [targetPlayerName/uuid]

---

---

**Cmi Version (using`/cmi version`):**  8.6.24.0 

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  Paper(239) 1.15.2-R0.1-SNAPSHOT

**Comment by xion87** [comment]
Any news about this?

**Comment by xion87** [comment]
![image](https://user-images.githubusercontent.com/3611852/83399614-cc6f7300-a401-11ea-9dd8-1676f3435354.png)
Still broken with latest release -_-

**Comment by xion87** [comment]
yeah keep to update the plugin and adding new feature instead fixing

**Comment by Zrips** [comment]
Fixed
