### ISSUE TITLE
bug in portal edit menu

### ISSUE THREAD

**Issue by Grizzly90** [Zrips/CMI#3273]
**Description of issue:**

while editing a portal:

i've clicked on "bei fehlender Berechtigung benachrichtigen". The green stained glass didn't changed and the "Teleport to exact bungee location" was replaced with the red stained glass for  "bei fehlender Berechtigung benachrichtigen"=false i can change the state of this config by clicking on both glass blocks.

https://ibb.co/f03BC66
https://ibb.co/6nCT6qZ

---

**Cmi Version (using`/cmi version`):** 
8.6.24.1
**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
1.15.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Will be fixed with next version
