### ISSUE TITLE
SF Elevator on Use TEXT

### ISSUE THREAD

**Issue by ZEROOblivious** [Zrips/CMI#3274]
**Description of issue:**
Its possible that CMI is logging the TEXT of the user when they are interacting with the Slimefun Elevators. 
![image](https://user-images.githubusercontent.com/32251194/81419441-3b67ed80-911c-11ea-9613-67178633745b.png)

---
Steps to Reproduce:
Use a SF Elevator, when you click on what floor you want, it teleports you, and it shows up in chat. 

```
12:40 Zediply : written_book:open - slimefun:floor1
12:41 Zediply : oh
12:41 Zediply : yeah and it definitely isnt the whole naming thing bc thats not what i was doing
12:41 Zediply : was just using it
12:42 ShadowOfDucks: wb
12:42 Pulchra_Vulpes: thanks
12:47 Zediply : written_book:open - slimefun:floor1
```
---

CMI: 8.6.24.1
Server version: Paper(260) 1.15.2-R0.1-SNAPSHOT
Vault version: 1.6.11(+)

https://github.com/TheBusyBiscuit/Slimefun4/issues/1888
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/
CS-CoreLib vDEV - 85 (git 4a7fce52)
Slimefun vDEV - 497 (git 4131a90)
Installed Addons (1)
ExoticGarden vDEV - 44 (git c8cccc60)

**Comment by CloudeLecaw** [comment]
actual logging is not possible. I also wanne se a logger for interactions or chat or commands or other things. may this will come one time :-)

**Comment by ZEROOblivious** [comment]
Do you think this is not a CMI issue? I've spoke with SF in the provided links and he says this is a chat plugin most likely. 
[list.txt](https://github.com/Zrips/CMI/files/4600482/list.txt)

But really I don't have any chat relating plugins except for CMI, GP, & DiscordSRV.

**Comment by ZEROOblivious** [comment]
I know that DiscordSRV still puts down what you're writing when using CMI Holograms. 

"Type the TEXT" since it doesn't have a / infront of the text, DiscordSRV posts it in Discord, constantly have to delete the text in discord lol, that's a separate issue, but im thinking it can be related to this

**Comment by Zrips** [comment]
This is not a CMI issue, atleast i cant recall any code which would do this. 
Could you elaborate more on "DiscordSRV still puts down what you're writing when using CMI Holograms."?

**Comment by ZEROOblivious** [comment]
A New report will be created instead.
