### ISSUE TITLE
[item] shows hidden "flags" / Attributes

### ISSUE THREAD

**Issue by the456gamer** [Zrips/CMI#3275]
**Description of issue:**
When Using [item] in public, or private message, the hidden attributes (like enchantments) are shown in chat.

![image](https://user-images.githubusercontent.com/42748092/81453542-b1527000-9181-11ea-9b47-a540a3ecd53f.png)

![image](https://user-images.githubusercontent.com/42748092/81453554-bd3e3200-9181-11ea-86a6-9ce87bbb95aa.png)

![image](https://user-images.githubusercontent.com/42748092/81453673-1efe9c00-9182-11ea-9001-c8dc08552625.png)

![image](https://user-images.githubusercontent.com/42748092/81453577-d3e48900-9181-11ea-92b6-0454552cf6be.png)

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/42748092/81453601-e65ec280-9181-11ea-8de2-f48697451534.png)
/version

**Server Type (Spigot/Paperspigot/etc):** 
![image](https://user-images.githubusercontent.com/42748092/81453623-f9719280-9181-11ea-873e-afe0c2a4a640.png)

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/42748092/81453628-fbd3ec80-9181-11ea-97c5-28286fc2bd14.png)

**Comment by mrfloris** [comment]
Confirmed on spigot 1.15.2 and paper 1.15.2 on my servers

**Comment by Zrips** [comment]
Will be fixed with next version

**Comment by mrfloris** [comment]
Thank you!
