### ISSUE TITLE
CMI aliaseditor

### ISSUE THREAD

**Issue by OrangeCat555** [Zrips/CMI#3276]
When using aliaseditor with a 2 word command it has some issues such as; not being able to delete the command and not being able to edit the commands it does when performed. 
When trying to delete my command 'sf open' it performs this in console /cmi aliaseditor sf__open remove and does not change anything. The click to change its commands doesn't perform anything.

No errors.

---

8.6.24.1

PaperSpigot

Paper git-Paper-137, MC: 1.15.2

**Comment by Zrips** [comment]
Will make some changes related to this, but in general adding and removing custom alias requires full server restart or you might encounter some issues like this.
