### ISSUE TITLE
DiscordSRV | CMI Hologram TEXT Display

### ISSUE THREAD

**Issue by ZEROOblivious** [Zrips/CMI#3277]
**Description of issue:**
When creating a hologram, and you are adding TEXT to the hologram, the text you're adding is also appearing with DiscordSRV inside community discords. We have to delete our messages when making holograms. 

---
Steps to Reproduce:
Create a Hologram
Add TEXT to the hologram 
The TEXT you input into the chat-bar displays through Discord with the DiscordSRV plugin. 
![image](https://user-images.githubusercontent.com/32251194/81471820-dcf54a80-91c1-11ea-860d-145228758b03.png)

![image](https://user-images.githubusercontent.com/32251194/81471824-e088d180-91c1-11ea-9561-c04b82a75275.png)

![image](https://user-images.githubusercontent.com/32251194/81471864-2d6ca800-91c2-11ea-96bb-4416f6b92b98.png)

---

CMI: 8.6.24.1
Server version: Paper(260) 1.15.2-R0.1-SNAPSHOT
Vault version: 1.6.11(+)
DiscordSRV 1.18.4

**Comment by Zrips** [comment]
Check your discordsrv config file and make sure you have RespectChatPlugins set to true.
