### ISSUE TITLE
Chair gone, unsit

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#3278]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###

See situation:
https://github.com/Zrips/CMI/issues/3262
In short:
Player sits on chair.
Chair is moved by piston and/or broken by anyone.
Player floats/sits in the air.
Preferable: It would be nice to kick the player from his chair as the chair is no longer valid.

### Basic explanation as to why this feature is needed and/or useful to have: ###
It looks strange to see someone float in a sitting position without chair.

Further information: see issue #3262

**Comment by CloudeLecaw** [comment]
i agree this would be a nice feature. that the player does not sit in the air. Well may this happens not very often but it look glitchy when the player sits in the air like in #3262

**Comment by Zrips** [comment]
Will add some extra checks, tho this  wont be 100% bullet proof due to how minecraft handles players sitting on entities
