### ISSUE TITLE
[REQUEST] Command to purge homes per world

### ISSUE THREAD

**Issue by Yhenko** [Zrips/CMI#328]
Bad english, im so sorry :(
Hi, im requesting a command to clear homes in determinated world, like /cmi purge [options (Home)] [World] 
Cmi Version (using`/cmi version`): 7.7.0.0
Server Type (Spigot/Paperspigot/etc): Paper
Server Version (using `/ver`): 1.12.2 Paper 1409

**Comment by LogGits** [comment]
Look into resetdbfields.
```
Usage: /cmi resetdbfields [collumnName]: (-w:[worldName]) (-p:[playerName])
* Resets particular database collumns to default value
```
