### ISSUE TITLE
Database batch save issue

### ISSUE THREAD

**Issue by AerWyn81** [Zrips/CMI#3280]
**Description of issue:**

Hi, a database backup error appears randomly and spam the server console until reboot. The error is made for each field in the database, for each player. The database is accessible, there is no problem on this side.

https://pastebin.com/pFZaqG54

**Cmi Version (using`/cmi version`):** 
8.6.24.1
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
262

**Comment by Zrips** [comment]
Is your mysql database on same server or some remote one? As it looks like your connection between servers got disconnected which would result into something like this.

**Comment by Zrips** [comment]
And side note, try updaing your Mysql database version in general.

**Comment by AerWyn81** [comment]
I'm going to check for a mysql update on our host to see if it solves the issue.
