### ISSUE TITLE
Illegal characters in home name

### ISSUE THREAD

**Issue by Teriuihi** [Zrips/CMI#3281]
**Description of issue:**

A player set a home using the following command: `/sethome M&S&M`. This seems to have created a home that displays in the database as `M&S§m%%115survival:-1422.41:67.0:5453.34:10.94:301.93`. When doing /cmi home and clicking on this home you get kicked for _Illegal characters in chat_. In game the home displays with a strikethrough through the next comma as you can see in the attached image 
![image](https://user-images.githubusercontent.com/38841986/81484139-b7108a00-9243-11ea-8d26-24167bad41ce.png)

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/38841986/81484154-d3acc200-9243-11ea-8dee-17cc70f0ad53.png)

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/38841986/81484176-f2ab5400-9243-11ea-8f71-9c10c201a8a1.png)

**Comment by CloudeLecaw** [comment]
&S is invaled because & tells the chat to use a colorcode so &S is an invailted colorcode and therefor not shown^^

**Comment by Teriuihi** [comment]
It kicks whoever clicks the home off the server for illegal characters in chat (because it sends the command with the color code as that player. & needs to be properly escaped or it's use should be prevented by the plugin

**Comment by Zrips** [comment]
@Teriuihi 
Will fix with next update. Meanwhile if you want to have quick fix, go into config file, under Homes category change NameRegex into "[^a-zA-Z0-9\-\_]"
