### ISSUE TITLE
Incorrect teleport point calculation for horse teleportation

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#3285]
If you have the permission _cmi.teleport.with.horse_ and you telport back and forth on a world with a horse (e.g. using warps or homes) you always end up in the ground. The best way to free yourself from the misery is a relog. The horse will not be damaged. 

If you teleport between worlds (also by warps or homes) the teleport works. You get not stuck in the ground.

CMI 8.6.24.2
Paper 1.15.2 - 264

**Comment by Zrips** [comment]
Should be fixed with next version
