### ISSUE TITLE
Teleporting (warps/home) at very high altitude (falling to death)

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#3291]
**Description of issue:**

Teleporting by means of /homes or warps causes the player to fall from very high altitude (around y=256)
The problem happens randomly and when the player changes world.

Problem started since CMI 8.6.24.3

---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Optimizations:
  Teleport:
    SafeLocationDownThenUp: false
```
It's probably related to this setting which worked fine so far.
Nvm Changing this to true, doesn't make it better: players fall through floors/still teleport to y=256.

---

**Cmi Version (using`/cmi version`):** 
CMI8.6.24.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-268 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by x1p** [comment]
This is game breaking and player annoying @Zrips 
I have to revert to previous build + configs and annoy players again to reboot. :cry:

**Comment by Zrips** [comment]
Interestingly enough there was no changes done related to teleportation like this. Anything special about those locations? Did target location was inside ground?

**Comment by x1p** [comment]
It might be related to an upstream of paper.
I'm investigating
