### ISSUE TITLE
/se can bypass Lockette sign protection

### ISSUE THREAD

**Issue by trickman325** [Zrips/CMI#3292]
The signedit command /se can bypass lockette protection signs :/

it there anyway to get support for this please as this is game breaking on my server....

---

CMI Version: 8.6.24.3

Server Type: PaperSpigot

Server Version: 1.15.2

Relevant plugins: 
Lockette Pro
https://ci.nyaacat.com/job/LockettePro/

**Comment by Zrips** [comment]
For time being disable access to this command.

**Comment by Zrips** [comment]
Tested out on 1.15.2, could not edit sign. Em i missing something here?
