### ISSUE TITLE
Timed Reset of Phantomtimer when laying in bed

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3294]
When more then one player (what is in most casses) play on a server they mostly have the problem they cant sleep in bed at nigh...well they can but it has not effect.

The problem is not of the skipping of the night, this is not wanted by many servers and is totally fine.

the problems are the phantoms. after 3 days without real sleeping they start to attack you and the timer does not get resetet.

So is it possible to add a reset of the Phantomtimer for the sleeping player when they may sleep 5 secounds in a bed at night?
Maybe the "sleeptime" can be also configurable - this also would be nice :-)

A feature like like in CMI would really help many players on the server and im sure on other servers too :-)

**Comment by glorying16** [comment]
This is interesting because on my server you only need to interact with the bed, not a full sleep cycle. But im pretty sure I havent changed any settings to make that happen. Unless its another plugin making that happen?

**Comment by CloudeLecaw** [comment]
So on your sever they just need to have to sleep for maybe a secound in bed at night to reset the 3-day timer of the phantoms?

Well i will check this aggain today, may there where some changes made allready and i havent noticed. If there is then we can tell our players to sleep in a bed quickly. this would definatly solve the problem for us. i will report later and close the ticket if this allready works fine now :-)

Thanks for this information <3
