### ISSUE TITLE
Totem Cooldown bossbar is not working.

### ISSUE THREAD

**Issue by SnowBees** [Zrips/CMI#3296]
In the last update, we fixed a bug that does not apply cooldown. Thank you.
However, the seconds are not displayed in BOSS BAR even during the cooldown.
Last time, the author said that the default state is ON, but the default state is still OFF.

I'm sorry in some places in Japan, but I took a video because it's difficult to explain with images.

https://youtu.be/cUrZuFwXRtc

**Comment by Zrips** [comment]
Will be fixed. Bossbar should be enabled by default, for some reasson it become disabled by default...
