### ISSUE TITLE
Ground clean not removing items

### ISSUE THREAD

**Issue by sibraxlis** [Zrips/CMI#3297]
Ground clean is leaving behind a TON of items.

![image](https://user-images.githubusercontent.com/25861695/81623373-30c18880-93a8-11ea-8474-fc672cc75d1d.png)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
GroundClean:
  # List of item types not to be removed on ground clean action
  WhiteList:
  - itemType
```

---

**Cmi Version (using`/cmi version`):** 
8.6.24.2
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
273
**Relevant plugins (Delete if this isn't needed):**
Clearlag (What I'm hoping to remove) removes the items.
![image](https://user-images.githubusercontent.com/25861695/81623415-5353a180-93a8-11ea-9e8c-e1320e270946.png)

**Comment by CloudeLecaw** [comment]
have you tried the argument for armor items?

**Comment by CloudeLecaw** [comment]
groundclean (+cb) (+cm) (+ci) (+b)
```
Clears server from unnecessary items

+cm will include minecarts into cleaning
+cb will include boats into cleaning
+ci defines if you want to include weapons and armors
+b broadcasts clear message to everyone
so it musst be /cmi groundclean +ci
```

**Comment by sibraxlis** [comment]
Looks like that did it, thanks!

**Comment by ZhiaiOvO** [comment]
How can I disable this feature？

**Comment by CloudeLecaw** [comment]
> How can I disable this feature？

its not a feature its just a command. cmi doesnt do this on its own. you nees to execute the command or run it in a schedule
so there is nothing to disable.
if you dont wanne use it, disable it in alais.yml and dont give permission for the command.

Note: vanilla, spigot and it forks do a clean of items in loaded chunks on its own after x secounds. the time is depending on your configured cleaning time. the default is after 5 or 10 minutes after the item was dropped. but at the end this has nothing to do with cmi.
