### ISSUE TITLE
Editing warp using gui. does not save settings.

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/CMI#33]
please fix the saveup editing warp, because when I set up not to show lore and restart the server, so the configuration restarted (I did it over gui)

(the latest version of the plugin)

**Comment by LogGits** [comment]
Can confirm this bug. Regardless of what its changed to, restarting will cause these values to reset.

**Comment by LogGits** [comment]
Let me know if this resolves your problem :)

**Comment by TheTopCz** [comment]
I set it up: false 
But when I close the gui menu and restart the server or use /cmi reload, so it returns to true at all warp ...

**Comment by LogGits** [comment]
@Zrips was able to confirm this as a bug and said it will be fixed in the next CMI build (tomorrow). If this issue persists after the next update please reopen the ticket 🙂
