### ISSUE TITLE
little problem with /ignore

### ISSUE THREAD

**Issue by ludvdber** [Zrips/CMI#330]
Hello,
I discovered that when we do /ignore all, it doesn't show the name of the ignored players
it show: Now you ignoring [playerDisplayName]

Cmi Version (using`/cmi version`):  7.7.1.2
Server Type (Spigot/Paperspigot/etc):  spigot
Server Version (using `/ver`): CraftBukkit version git-Spigot-2086bb0-1988d7f (MC: 1.12.2)

**Comment by LogGits** [comment]
Confirmed:
/cmi ignore all
outputs:
```
Now you ignoring [playerDisplayName]
```

This should be changed to:
```
You are now ignoring everyone.
```

**Comment by LogGits** [comment]
Side note, @Zrips 
/cmi ignore username
says:
```
You no longer ignoring username
```
Change this to:
```
you are no longer ignoring username
```
if the user is not ignored it will say the ^ message

**Comment by LogGits** [comment]
Resolved in next build.
