### ISSUE TITLE
Enchant command isn't working

### ISSUE THREAD

**Issue by EgidioBezerra** [Zrips/CMI#3300]
**Description of issue or feature request:**

Enchant command isn't working

![image](https://user-images.githubusercontent.com/24907760/81732140-64fb7e80-9466-11ea-8020-c57988bbd6bb.png)

![image](https://user-images.githubusercontent.com/24907760/81732384-ccb1c980-9466-11ea-8e90-cb67bb37040f.png)

**Comment by CyreX12** [comment]
same :(

**Comment by CyreX12** [comment]
I think it will be fixed in the next update.

**Comment by CloudeLecaw** [comment]
I can agrree this

since CMI8.6.24.3 the enchant names are shown but woere not wering
and with CMI8.6.24.4 the enchant command totally broke and nothing happens anymore.

In both cases you see the chatinfo the item was enchanted in chat.

**Comment by CloudeLecaw** [comment]
could you laber this as a bug report? Else it wount be seen so good
