### ISSUE TITLE
Displayname without nick not working 

### ISSUE THREAD

**Issue by Korinocho** [Zrips/CMI#3302]
I just configured CMI to use nicknames, but if i use the nickname placeholder, it shows me nothing. It only shows up if i put some nickname

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

DisplayName:
  If you have 3rd party plugin changing players display name, set this to false
  Change: true
  Format of players display name. By default only nick name will be visible, if its set, if not, then players name
  Possible custom varibales: {prefix} {suffix} {nicknameprefix}
  Supports placeholders
  Format: '{nickName}'

---

**Cmi Version (using`/cmi version`):** 8.6.24.4

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper version git-Paper-161 (MC:1.15.2) R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment]
have you tryed playerDisplayName?

**Comment by Korinocho** [comment]
Well, thanks! Didnt saw the playerdisplayname in the placeholders. My bad!
