### ISSUE TITLE
Play a noise from interactive sign?

### ISSUE THREAD

**Issue by sibraxlis** [Zrips/CMI#3303]
**Question: **
I'm trying to set an interactive command to play a noise but can't quite figure it out. I've tried: 
  - cmi sound enchant_thorns_hit 1.5 1 [playerName]
- cmi sound enchant.thorns.hit 1.5 1 [playerName]
 but neither worked.
- playsound minecraft:enchant.thorns.hit master [playerName] 291 38 412 1 1.5
 works but I'd rather not get hit with the console

![](https://media.discordapp.net/attachments/526402563847880725/708583685456396288/unknown.png)
 spam every time someone hits the button.

**Comment by Zrips** [comment]
Pitch and volume is defined with extra variables.
cmi sound enchant_thorns_hit -p:1.5 -v:1 [playerName]
And you might want to add asConsole! sp entire line should look like
`asConsole! cmi sound enchant_thorns_hit -p:1.5 -v:1 [playerName]`
