### ISSUE TITLE
random teleportation request

### ISSUE THREAD

**Issue by mangguoyo** [Zrips/CMI#3304]
Sorry,My English is not good and I am using a translation software to communicate with you.

My server does not need random teleportation features, For some reasons, many worlds need to be created. Every time the world is created, the configuration file will write the random teleportation configuration,So can you add an option to disable the random teleportation features

thanks

**Comment by CloudeLecaw** [comment]
cmi allready has this for most TP commands. pls look in the wiki for this ;)

**Comment by Zrips** [comment]
Will add with next update
