### ISSUE TITLE
FPS drops with holograms

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3305]
**Description of issue:**
Hi, when I use holograms and more lines... or more pages, there is so much arrmor stands and it causes too much players lags... Could you please optimise it somehow? I think, it shouldn't do.

---

---

**Cmi Version (using`/cmi version`):** 
[17:57:36 INFO]: CMI plugin version: 8.6.24.4 BungeeCord

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
[17:57:36 INFO]: Server version: Paper(282) 1.15.2-R0.1-SNAPSHOT

Btw I think it's really needed  to fix it somehow... Holographics Displays don't use so much armor stands and if you don't fix it somehow, I have to switch to another plugin, but I like CMI holograms so much...

**Comment by Volgeop** [comment]
![unknown (3)](https://user-images.githubusercontent.com/18662086/81836167-651d7c00-9543-11ea-9638-cd96c621b171.png)
![unknown (2)](https://user-images.githubusercontent.com/18662086/81836172-664ea900-9543-11ea-83ea-a5a4a8ef0b8f.png)

**Comment by Zrips** [comment]
Armor stands are there to actually show those lines in the air, we literally cant do anything else. You will need to optimize your hologram count and spread them more evenly and lover activation range if you have quite few lines in them. Other than this, i might have a look, but in general there is not much to optimize as we need atleast one armor stand for one line of text and in case of clickable holograms we need to add magma cubes.

**Comment by Volgeop** [comment]
And holographics display also use so much armor stands?  And even if I set lover activation range, entities will be there still so there will be still fps drops, no?

**Comment by Zrips** [comment]
Give me example of your holograms you have set which causes this load for you.

**Comment by Zrips** [comment]
One armor stand per line. You might have had less active holograms with holographicdisplay plugin, which looked like it had better performance.

**Comment by Zrips** [comment]
maybe i could add some extra options to adjust hologram activation area, which would allow you to have holograms behind a wall without actually turning them on.

**Comment by Volgeop** [comment]
Just two holograms in this area (and you can't view both, there is probably good distance).

[holograms.zip](https://github.com/Zrips/CMI/files/4623211/holograms.zip)
Look, I also give here my holograms file.

![unknown (2)](https://user-images.githubusercontent.com/18662086/81837297-f7724f80-9544-11ea-9807-f55c51ffa9be.png)
![unknown (3)](https://user-images.githubusercontent.com/18662086/81837303-f80ae600-9544-11ea-8edd-0b5337c39087.png)

**Comment by Volgeop** [comment]
The problem is that I have spawn as tree, so there will be probably more holograms in the chunk later... now there are just two and it causes FPS drops... and I have normally very good fps... I have ryzen 5 2600x and 24gb ram... + ssd, I didn't notice fps drops before

**Comment by Zrips** [comment]
Will test it out tomorrow, got some basic idea and might come up with some posible optimization for it

**Comment by Zrips** [comment]
Having spawn in a tree would involve bunch of leaves around you, which usually is a heavy thing on client to deal with. Can comment tho on actual cause, but will do some testing.

**Comment by Volgeop** [comment]
Thanks, I will try it instantly when it will be released. I'm trying to have very smooth server and now I also make smooth bottom of spawn island to prevent FPS drops. Btw tree spawn had also Hypixel few years before. I hope it wouldn't be main problem.

**Comment by Zrips** [comment]
Tho i wonder, what fps do you get with holograms on and with them off?

**Comment by Volgeop** [comment]
I have it locked on 60 fps, but normally I have around 100-200 maybe? And after there are micro lags and it drops on 6 fps for half of second or something like this... you probably know, what I mean by micro lags. 

It are primary fps drops, for ex. from 60 (locked) I have 22, 10 or 6... just tested it now to fly around it.

My friend has normally 200 fps and it drops him to 90 there, not so bad.

**Comment by mrfloris** [comment]
I can reproduce this, you'd really have to add like a dozen lines of text to a hologram and have like 4+ holograms nearby to get it to drop, but I was able to do it. 

I cannot confirm this is vanilla minecraft, or something spigot/paper related, or specifically cmi. 

Armorstands ARE entities after all... The same goes for having 50 chests filled with items and putting lockette signs on them, the fps in the are WILL drop. Or having a storage room with shulker boxes with stuff and having item frames with items on them. The fps WILL drop as well. 

https://youtu.be/qE54EKCtpJQ
and
https://youtu.be/8M8bJQBCU28

**Comment by Volgeop** [comment]
Here is my testing... for me, it's worse FTP drops, but just on trees and just where are holograms.... And there is place ONLY with 3 holograms with single line... http://leteckaposta.cz/181748296

**Comment by Zrips** [comment]
@Volgeop 
Tested couple things out. Holograms does effect your fps, by quite a bit. but this is common issue across every hologram plugin outhere, tested holographicdisplays to be sure and same issue persists. 
Have you simply tested same movement around while having holograms disabled?

**Comment by Volgeop** [comment]
Tested and yeah, it lags too a llittle bit... But why? Do you think it could be barrels or so many lanterns... or leaves?

**Comment by Zrips** [comment]
It looks more like some issue with chunk loading. It might even be issue with a client and not with server itself. hard to say without actually testing your environment. But you can  check if its related to chunk change, as there was issue with that with some versions. Click f3+g and check when you are getting those freezes, if they happen when you change chunk, then you have basic issue with minecraft client and minecraft version in general.

**Comment by Volgeop** [comment]
But in another chunks it works... It's just in chunks around tree... on other servers it doesn't happen neither.

**Comment by Zrips** [comment]
Go into game mode 3, it might show you some hidden entities which might be the cause of all this, maybe.

**Comment by Zrips** [comment]
Closed the ticket, but i'm still curious what is causing issues in your situation, just for future reference if it will come up again.

**Comment by Volgeop** [comment]
Looks Zrips... I tried F3+G and Spectator, I tried remove leaves and this chunks is really bad even when I went into them.... I tried cmi fixchunk but nothing.... What do you suggest to fix it please? I really don't know what to do with it...  http://leteckaposta.cz/541144877

**Comment by Zrips** [comment]
setup test server, get your world on it with all plugins and everything, basically a copy of it.
Then use worldedit and try regenerating chunks around you, which will destroy everything, but atleast you will know if its related to that. 
You could try removing items from ground, as some times you can encounter bug where you have arrows spawning in one spot and you can accumulate thousands of them. 
Another option would be simply changing server version, like try testing on 1.15.0 and use different client. 
Another option, remove every single plugin and check if issue is fixed. Atleast you will know if its related to a plugin or not.

**Comment by Volgeop** [comment]
Tried remove plugins and only this were on server: HyperDrive, IPWhiteListBukkit, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI*, Vault, VoidGenerator. So I probably should pregenerate it? I have server only on 1.15.2 and just one (maybe few) chunks is laggy.

**Comment by Zrips** [comment]
Only keep plugins which are required for this world to exist. Or even better, remove all of them and if you have custom world, rename it in data folder to default name which should make it load without any plugins. You have to determine if this is caused by plugin or not. After that you can move further with this investigation

**Comment by Volgeop** [comment]
Btw tried to put this map on another server and it didn't lag.... and on my server it still causes lag spikes http://leteckaposta.cz/668568711. I will try remove it completely, I tried also ground clean, remove map and upload again and nothing...
