### ISSUE TITLE
Add command editing to scheduler

### ISSUE THREAD

**Issue by glorying16** [Zrips/CMI#3309]
It would be great to be able to edit the announcer in the schedule.yml with ingame commands. This would allow my staff to be able to make edits as needed, without needing console access. 

Something like /schedule announcer add|remove|edit blahblahblah. There could be a corresponding number to each message making it easier to select for removing or editing. Or even JSON editing. Perhaps also have a preview option, to list out all the messages and how they look?

**Comment by CloudeLecaw** [comment]
pls add a GUI and command to edit all files config and all language files. thx...

**Comment by glorying16** [comment]
I could be reading into this, or just not understanding from some of the broken english, but that seemed like a fairly hostile comment. I am simply making a "feature request" which is part of the development of this plugin. Zrips can add and not add what they want, its their choice, but that doesnt mean I (or others) cant ask for a feature. And, though I dont know much about developing a plugin, I dont feel im asking for a huge thing. If I knew how to do it myself I would, as im sure most people would with any feature of any plugin. I also dont see where I asked for GUI...

As I said in the original post, I would like my staff to be able to make these edits themselves (with chat based commands) without me having to do it personally. I do not just give out console access, and I do not want to. But we run events that change phases on specific days and the announcer lets the players know about these changes, and serve as reminders. These would be part of a normal auto broadcast, or "scheduled announcement". Unfortunately I am not always able to be here to change it when it needs to be changed, seeing as I work a fulltime, and part time job, and do occasionally like to do things outside of the server and work, like spend time with my family. I obviously know about the announcer because im asking for a change to be made to it. Most of the suggestions I made were based off of an old (and obsolete) super basic plugin that we used before. Which seeing as its obsolete, is why I now have a need for the feature. Of course like most, I would rather use less plugins, and have smaller features incorporated into larger plugins.

**Comment by CloudeLecaw** [comment]
What i mean is there is allready an announcer in the Shedule u just need to enable it
look inside shedulers.yml and simpls add this

```
Announcer:
  Randomize: true
  Enabled: true
  Delay: 300
  Repeat: true
  Commands:
  - msg! [allPlayer] There is so much to do
  - msg! [allPlayer] Meassage 2
  - msg! [allPlayer] Meassage 
```

When you reload CMI u have an announcer that is Announcing all 300 secounds one of the lines listed in commands, this also can be broadcasts if you like this more.

**Comment by glorying16** [comment]
I know all of this, but it still requires _me_ to be the one to do it. Im asking for a way for my staff to be able to do it without having console access because they dont have it. The request is asking for a change to the already existing system.

**Comment by CloudeLecaw** [comment]
But the request is not usefull like this
not every server has the Shedule Announcer.
You asked for **/cmi schedule announcer add|remove|edit**

More sensfull in your case would be.
**/cmi schedules [schedules} add|remove|edit**
may with a extra permission that allowed to define what schedules are allowed to add/remove/edit

This would allow ingame management of schedules. and not only of an announcer that may just only each 10th server has set up...

**Comment by glorying16** [comment]
Yeah.... Thats pretty much what I asked for... The parts you added to it dont change what I asked for, and dont change its ability. I gave that command as an example, not a cemented command. So you really could have just made that addition without dismissing what I asked for to begin with.
