### ISSUE TITLE
[Error] players move to spawn point after enter the server from cmi portal

### ISSUE THREAD

**Issue by valenvaio** [Zrips/CMI#331]
Which command turns off the players moving to the spawn after they enter the server from cmi portal(bungeecord)?
At the moment, the player for <1 sec is on the last place after entering the server and then moves to spawn. If players enter the server from /cmi server servername they not go to spawn.

**Comment by valenvaio** [comment]
CreativeSrv:
Loc: 2700.0:75.0:-2217.0:2702.0:80.0:-2217.0
enabled: true
effect: reddust
showParticles: true
bungeeServer: CreativeSrv
bungeeLocation: world_creative;-851.5;91.0;-2779.5;-92.4;-0.59
particleAmount: 20
particleHide: 0
activationRange: 16
commandsWithoutTp: false
commands:
- cmi effect [playerName] blindness 2 1 -s


**Delete** _-851.5;91.0;-2779.5;-92.4;-0.59_ in line _bungeeLocation: world_creative_. And after that player not auto tp to spaewn.

**Comment by LogGits** [comment]
havent been able to test this. However, if this is the case, by default it should teleport the user to spawn if a location doesn't give any co-ords.
