### ISSUE TITLE
/glow not working

### ISSUE THREAD

**Issue by mooshlandia** [Zrips/CMI#3310]
Hello. /glow is not fully working. Only the white color works. All colors do not work when typing /glow (color) or /glow gui and selecting a color. This issue has been going on for several months so it's not a new issue for me. At first it worked but then stopped, then worked again, and so on and so forth until it no longer worked. I believe the reason all of this is happening is because of CMI not working with certain plugins or other plugins interfering with it. I narrowed it down to a plugin called TAB and literally every scoreboard plugin I can find. I tried Scoreboard Revision, Animated Scoreboard, and Infinite Scoreboard. When I have no scoreboard plugin installed there is no issue. Also I should mention I now just use CMI's built-in TAB feature. I have spoken to some people with scoreboard plugins and they are not having the same issue, though I have seen others post about similar issues that I am having on discord. When my server is running every plugin I have installed besides the scoreboard plugin then /glow has no issues. As soon as the scoreboard plugin is enabled it breaks /glow. It could be another one of my plugins that is interfering with basically any scoreboard plugin which is then in turn messing with CMI. That's my guess but I really don't know a lot about how plugins work. Here's my latest.log. Note that the plugins that say .jarD are disabled. They are not causing problems. This was an issue before they were installed or disabled. When I simply disable Infinite Scoreboard (the one I currently use) /glow works again.

[latest (3).log](https://github.com/Zrips/CMI/files/4625941/latest.3.log)

I'm using CMI version 8.6.24.4 (note this has been going on for so long so I doubt the version is the problem).

I have a PaperSpigot server

I am running version git-Paper-280 (MC:1.15.2) 

Infinite Scoreboard (full plugins list is in latest.log (ignore the plugins that have a jar that appears as .jarD)

**Comment by CloudeLecaw** [comment]
#3295

**Comment by maxmooshroom** [comment]
@CloudeLecaw Thank you but that article does not relate to my issue.

**Comment by mrcoffee1026** [comment]
Same issue... leaving out the scoreboard stuff, I don't know anything about that: v8.7.6.0
From how the plugin responds, it accepts 2 arguments max where either the first is the playername if you do not want to affect yourself, and the second is either true/false... which it will toggle if omitted.  "gui" or specifying color... which it will suggest while typing the command, it will simply ignore.  Color is always white, there is only on or off and no method of accessing a gui for this feature.
Paper-135 (1.16.1)

**Comment by mrcoffee1026** [comment]
Oh nevermind I just had to change the config option DisableTeamManagement to false and now it works.

**Comment by mc-System404** [comment]
If your using TAB PREMIUM plugin follow this tutorial to make your /glow working 👍
https://github.com/NEZNAMY/TAB/wiki/How-to-make-TAB-compatible-with-glow-plugins

**Comment by CloudeLecaw** [comment]
And where do you have to set this up?
```
Groups:
  _OTHER_:
    tagprefix: '%vault-prefix%%cmi_user_glow_code%'
```
? 
In your permission Systems? In the cmi config (where?)

**Comment by mc-System404** [comment]
in tab premium config! But this only if you use this plugin:  https://www.spigotmc.org/resources/tab-1-5-x-1-16-x-premium.83967/
(free version as well)

**Comment by CloudeLecaw** [comment]
our missleading the players this does not has anything to do with the issue

i read the description now and this glow fix there is just to make the glow for this plugin work.
but it does not fix the problem from cmis glow

**Comment by mc-System404** [comment]
glow works fine for me latest spigot/cmi versions! U can test by yourself removing all plugins except cmi and test /glow again ! 
Thats how i found my problem !

**Comment by CloudeLecaw** [comment]
Create a CMI conection to MYSQl and test aggain you will see^^

**Comment by mc-System404** [comment]
Im using mysql and glow work PERFECT FOR ME ! I know CMI has a built in tab , but not a scoreboard or animated name !
So im just using another plugin that does animated name, tab and scoreboard for me ! (and NO , its not my plugin).
I answered to this thread cause i had problem with glow, and i found a fix, so i shared with everyone how i fixed it for me !
Thats all ! TIP: try cmi glow without any other plugin installed and u will see it works (with mysql).
