### ISSUE TITLE
Does sign edit check for build permissions?

### ISSUE THREAD

**Issue by sibraxlis** [Zrips/CMI#3314]
**Question: **
Basically just want to give my donors the ability to use sign edit, but only for areas they are allowed to build in, is this possible?

**Comment by Zrips** [comment]
Plugin checks if player can create sign in this location by firing BlockPlaceEvent event. If he cant, then he cant edit text on it. But in general this should be tested with your protection plugin to make sure that it is working correctly with yout setup.
