### ISSUE TITLE
STILL BROKEN - SafeLocationDownThenUp: false

### ISSUE THREAD

**Issue by ScuroK** [Zrips/CMI#332]
Cmi Version (using`/cmi version`): 
7.7.2.0
Server Type (Spigot/Paperspigot/etc): 
Spigot 1.12.2

@Zrips @LogGits 
This is what happens if you use: **SafeLocationDownThenUp: false**

1. Set **home** on top of the trap door.
![2018-05-04_22 30 55](https://user-images.githubusercontent.com/10480144/39651291-9849f62a-4feb-11e8-8d35-2b86b16e179a.png)

2. You will teleport here. But actually there is no reason for it. there is enough space above the trap door. its a safe location!
![2018-05-04_22 31 08](https://user-images.githubusercontent.com/10480144/39651839-c6bc2870-4feb-11e8-8c15-4081174e442f.png)

**Comment by ScuroK** [comment]
why does it think the home location is unsafe??

**Comment by Teronox** [comment]
I have the problem too, it's very frustrating, never had such problems with essentialsX.

**Comment by MCTyler** [comment]
Can't you just set the Spawn 1 block above the Floor?

**Comment by ScuroK** [comment]
im not talking about spawn. im talking about homes of players.

**Comment by MCTyler** [comment]
Maybe it reads that trap door as a fluid block. :), IDK, I have never seen this.

**Comment by ScuroK** [comment]
I have hd this with ither blocks aswell in the earlier version. For example with glass block.

The check mechanism if a home point is safe or not does not work if you use
„SafeLocationDownThenUp: false“

No matter what block the trap door is! There is enough place to stand on. Thats it. Its a safe location but cmi think its not.

I think @Zrips is able to fix this.

**Comment by Teronox** [comment]
It would cool, if Zrips can fix this.
I mean it is a server security gap, because normal player can go with the sethome-methode through locked trapdoors.

**Comment by Zrips** [comment]
Will be reworking safe location detection to include closed trap door as solid block while open as empty one. And some other stuff

**Comment by ScuroK** [comment]
thanks alot @Zrips 
i think its good to be quite tolerant in terms of the definition of a "safe location" if there is enough space (air) for a player and its not lava i think it should be fine.

its better to have a player falling down somewhere from time to time than players going to wrong places even the home point was safe.

**Comment by RustyDagger** [comment]
Iv had massive issues with what ever changes you have made over the last few versions, I have a maze in my spawn and about 30 warps set for it I manually went and set all the locations to the dead center of the block but now i have players spawning inside leaf blocks and above the glass thats 3 blocks above them.

it was working fine before the latest changes, Whats more is it seems to be trying to teleport the player more than once. I have a permission I assign the players whilst in the maze to cancel the teleport event and send them a message 


the no tp permission is because my players were doing a glitch where they would /tpa a player then enter the maze and have the other player accept to get out of the maze with out using /exit ( causes issues with stats and was leaving the /glow assigned to them.) ( maybe all tpa pending should cancel when a player teleports ( they TP into the maze. )

So no doubt my No tp permission messing with CMI aint helping but it was still working proior to the changes.

**Comment by Zrips** [comment]
@ScuroK Well that's the main question. Should we teleport player up or down throw solid blocks. In example is you home location is at Y=60 and all blocks from 55 to 65 are solid ones. Should we teleport player up, down or throw error message that there is no safe location and teleportation will result into suffocation and allow to bypass that and teleport to that location anyways?

**Comment by ScuroK** [comment]
@Zrips my suggestion is to teleport the player up if there is no space at the home location. I think essentials even just teleported to the nearest safe location possible.

But the main issue right now is that cmi detects the location as unsafe even it is safe (see my screenshots) if „up“ is enabled.

I dont like the players getting a warning. I would like to have it just the way essentials did it. Automatic detection and ajust.
Maybe not just up ir down, but also left right (but thats not so important to me)

But again: the main issue us the detection.

**Comment by ScuroK** [comment]
You can try essentialsx and you will see how good it works.

**Comment by MCTyler** [comment]
Just copy and paste the entire Home code from X into CMI, huh?

**Comment by RustyDagger** [comment]
and how does going up and down not create the same issues for gliching players THROUGH floors or ceilings, 

side note:
THROW is used when tossing something, its not got the meaning you are using it as. example using it correctly 
I watched a child Throw a ball.

**Comment by LogGits** [comment]
Here is my take. There is no actual way to prevent players from glitching into other users bases without some sort of region defining tool. The essentials method is simple to add as it does x y and z safe location checks. This can be added but if it is added, the onus is on the server owners to ensure they are fully aware of this. If a server is fully aware of this they can add preventative measures such as lockette. 

The question is, do u guys care that people will be able to glitch into other users bases if an essentials safe location check method is added?

**Comment by RustyDagger** [comment]
Id be happy with just placing them where its set If unsafe send them a warning and tell them to do the command again within 30 seconds to tp any way. if they set dumb homes its their own fault. If its a warp then they should be telling someone that has the ability to fix it to do so.

**Comment by RustyDagger** [comment]
Iv downgraded my cmi version because 30 warps that are safe are teleporting players up above the glass above them and inside leaf blocks near them.

**Comment by MCTyler** [comment]
Warps or Homes? @ScuroK got on me cause I used the word Spawn. When did he change it that it made it Break?

**Comment by RustyDagger** [comment]
Im down 2 versions at this point, It was the changes to safe tp so all teleports are effected warps homes spawn tpa's if it teleports its now dicky.

**Comment by MCTyler** [comment]
I don't have any really tight warp areas so I may not exp. issues.

**Comment by RustyDagger** [comment]
yeah all mine are in a maze so its 1 block wide, Iv centered all the teleports on the middle of a block. still didnt help.

**Comment by ScuroK** [comment]
Dont forget: We now have chorus fruits to go through walls.
Thats why i think this point is not so important. And if a server owner really want to avoid it, he need to work with worldguard flags anyway. there is a entry flag aswell.

Just saw the new update for detection. Will test it out tonight.

**Comment by ScuroK** [comment]
Finished testing. Latest version works perfectly fine!

**Comment by ScuroK** [comment]
Closing
