### ISSUE TITLE
McMMO hearts replacing name on bossbar

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#3320]
**Description of issue:**
When using McMMO, if you hit a mob and the hearts show up, it replaces the name on the bossbar. here's a clip of it: https://vimeo.com/user115619951/review/419211946/29fd754c2d

---
---

**Cmi Version (using`/cmi version`):** 
8.6.25.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-282 (MC:1.15.2)
**Relevant plugins (Delete if this isn't needed):**
McMMO

**Comment by Zrips** [comment]
Bossbar uses entity display name, if McMMO modifies it then it will change in bossbar too. Not a CMI bug in particular.

**Comment by mrfloris** [comment]
I believe in the play mcMMO server nossr50 has fixed this. If you haven't upgraded mcMMO yet, try that first.
