### ISSUE TITLE
Send updates language file

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#3322]
**Question: **
Where should I send the updated language file (Locale_ES.yml), so that Zrips can include them in future versions?

PD:  I've been sending the language files: private message, on GitHub, discord, etc. and it hasn't been updated for months.

[https://mega.nz/file/mMUVEKTY#jlS88T5nv2w2OBz4BJw3pE8pYqHoywdVoFvRMa_oKyU](url)

**Comment by CloudeLecaw** [comment]
pls close and download latest: 8.6.25.1
