### ISSUE TITLE
Portal Features 

### ISSUE THREAD

**Issue by Aeyori** [Zrips/CMI#3323]
**Description of feature/improvement request:**
Toggling whether portal particles are visible based on a player’s permissions.

Or 

Knockback on the player if they do not have access to portal. 

---
### Detailed explanation of what it should do, when and in what situation: ###
If the player has access to the portal, allow for the player to be able to see the portal particles.
If the player does not have access to the portal, then particles do not show up. 

Alternatively, if particles are on and player doesn’t have access to the portal, the player will get knocked back from the portal like in world borders. 

### Basic explanation as to why this feature is needed and/or useful to have: ###

Quality of life features for portals to add for more customization.

**Comment by Zrips** [comment]
Added
