### ISSUE TITLE
inbuilt Alias

### ISSUE THREAD

**Issue by boboy6** [Zrips/CMI#3326]
#**Question: ** 

I Understand that there are inbuilt alias In this plugin however I have them all turned on and they dont seem to be working Im just wondering if I missed something 

Thank you for your time

**Comment by CloudeLecaw** [comment]
the file u are search for is alias.yml
other aliases can be created with customalias inside customalias.yml or by command if ur not confirm with file editing

**Comment by boboy6** [comment]
yes this is the file Ive already edited however they still do not work and just come up as an unknown command when you try to use them on the server

**Comment by CloudeLecaw** [comment]
also after restart?

**Comment by boboy6** [comment]
yup

**Comment by boboy6** [comment]
I have the required perms set so this is also not the issue

**Comment by boboy6** [comment]
and there are no conflicting plugins that I can see either
