### ISSUE TITLE
Jail time in CMI Info

### ISSUE THREAD

**Issue by RedAlphard** [Zrips/CMI#3329]
Hello;
I wish that in the / cmi info {player} command in the jail section if it is on, it must show me the remaining time and the name jail?
Is this already present? do I have to make a change in the message file or in the config.yml?
A separate command would also suit me

At the moment I use the command / cmi jaillist but after exceeding 100 players it is difficult for me to read them due to the limitation of the game chat

RedAlphard

**Comment by IngSorre97** [comment]
Yeah a command jail info would be great,jail list is functional but after a while it makes itself so long the chat won't even hold it all, if the player is one of the firsts jailed i can't even see it

**Comment by RedAlphard** [comment]
Thanks to the new update, I can view what I want;
I really appreciate this update; thanks for the wonderful work you do.

I close;
RedAlphard
