### ISSUE TITLE
How to display a clickable teleport message when a user dies (and more)

### ISSUE THREAD

**Issue by PhracKko** [Zrips/CMI#3331]
**Question: **
In the event of a user's death under the authority of a general user,
How do I display clickable messages teleporting to the previous location?

This is known as a function related to /dback, and although dback permissions have been added to all ratings, messages that return to them upon death will not be displayed to the general user.

and also..how to pay a certain fee for each click of this message?

**Comment by CloudeLecaw** [comment]
Create a custom alias for this

**Comment by PhracKko** [comment]
> 이 호버, 클릭 가능 및 실행 비용에 대한 사용자 정의 별명을 작성하십시오.
> https://www.zrips.net/cmi/commands/specialized/
> 
> 1 단계에서 비용이 많이 드는 명령을 작성하십시오.
> 2 단계에서 langfile에 표시된 dearhmessage를 클릭시 사용자 정의 별명을 실행하는 호버 메시지 + clickaable로 편집하십시오. 이제 플레이어에게 사망시 사망 장소를 볼 수있는 권한을 부여하면됩니다. 끝난



> Create a custom alias for this hover, clickable and moneycost for execute.
> https://www.zrips.net/cmi/commands/specialized/
> 
> In step 1 you create the command that has a money cost.
> In step 2 you edit the shown dearhmessage in the langfileas a hover message + clickaable that is executing the custom alias on click. Now you just need to give players the permission to see the deathlocation on death. Done

thank you!
