### ISSUE TITLE
Using /cheque with no arguments gives a permission error even if you have cmi.command.cheque

### ISSUE THREAD

**Issue by nichogx** [Zrips/CMI#3334]
**Description of issue:**
Players who have the cmi.command.cheque permission get a no permission error instead of the "correct usage: /cheque <amount>" message. They can correctly create cheques with /cheque <amount>.

---

**Cmi Version (using`/cmi version`): 8.6.25.0** 

**Server Type (Spigot/Paperspigot/etc): Paper 283** 

**Server Version (using `/ver`): 1.15.2**

**Comment by Zrips** [comment]
Should be resolved
