### ISSUE TITLE
NBT Support

### ISSUE THREAD

**Issue by Dalethium** [Zrips/CMI#3335]
It would be amazing if the mirror command and /worth command supported nbt and block data, for example, player skulls are set to steve heads in both of those.

**Comment by Dalethium** [comment]
Also another thing that I'd love to support it would be custom recipe inputs.

**Comment by mrfloris** [comment]
Custom items in setworth support is also requested here https://github.com/Zrips/CMI/issues/1572

**Comment by blakedj012** [comment]
Custom items with Modsupport  would be nice
