### ISSUE TITLE
[Request] Info from Console

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#3339]
**Description of feature/improvement request:**

---
Love the new info functionality! ...at least in game. It's kinda useless from console. 

Is it possible to split the two or detect where the command was run from and provide the old functionality from console? Particularly useful for getting IPs.

Thanks!

**Comment by Zrips** [comment]
This will be worked on as i realized that console will not get all the information we provide in game with hover over message quite early in recoding of this command. Will be upgraded with next release.
