### ISSUE TITLE
CMI Tablist - Unable to parse all placeholders

### ISSUE THREAD

**Issue by Ash10744** [Zrips/CMI#3340]
**Description of issue:**
Not all placeholders are parsing tab list. (Sorry I use so many in my tab list)

Worked in older versions but this specific version it does not anymore
https://i.imgur.com/Fcm738L.png

---

```

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
https://pastebin.com/VP60gDWc
```

---

**Cmi Version (using`/cmi version`):**  8.6.26.0

**Server Type (Spigot/Paperspigot/etc):**  Paper(243) 1.14.4-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 
https://i.imgur.com/E3uyHzz.png

**Comment by mrfloris** [comment]
And you've setup luckperm's ecloud extension?
<https://github.com/lucko/LuckPerms/wiki/Placeholders>
```
/papi ecloud download LuckPerms
/papi reload
```
and when you set `%luckperms_prefix%` and parse it with `/cmi placeholder parse %luckperms_prefix%` you get the expected result ? but the meta ones don't work?

CMI has this in the changelog from a few releases ago:
`Some minor update to complex placeholder handling`

Maybe upgrade your cmi to the latest again and test to see if that resolved it. 
I've poked zrips to see if he has time to look into this. But we will see first if updating cmi resolved it.

**Comment by Ash10744** [comment]
Mhm it is all setup !

**Comment by Ash10744** [comment]
It is parsing some of the luck perms placeholders but not them all.

**Comment by Zrips** [comment]
if its parsing some of them, then you have working hook, if its not parsing all of them, then its ether luckperm plugin issue or you have incorrect placeholders.
