### ISSUE TITLE
[Request] info command deathlocation

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#3341]
**Description of feature/improvement request:**

I would love to see the last death location of a player.
It used to be in the old setup only a little hidden.
The new setup doesn't check for the permission too.

---
### Detailed explanation of what it should do, when and in what situation: ###
Show the players' last death location too.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Useful for staff to solve issues with players who dropped  a precious item upon death.
We don't want them to be able to execute dback or back.

**Comment by CloudeLecaw** [comment]
If you saving inventoryies of your players (cmi option) you can use a nice command for this
/cmi invcheck [Playername] there u see deaths + locatons + inventory the player had.

![image](https://user-images.githubusercontent.com/12080017/82390947-5b62af80-9a40-11ea-8600-cafc40271533.png)

![image](https://user-images.githubusercontent.com/12080017/82391004-79301480-9a40-11ea-9696-b407f99e7782.png)

with cmi.deathlocation you are able to post the deathlocation in chat when player die once too.

**Comment by x1p** [comment]
Nice. I didn't know that.
Although a little complicated. I'll join that request anyway.
