### ISSUE TITLE
Icon Heads not pulling correct skin from placeholder variable name

### ISSUE THREAD

**Issue by 404uam** [Zrips/CMI#3342]
When using `ICON:head:%cmi_user_name%` or `ICON:head:%cmi_votetop_[1-10]%`. The head icon is generated but the correct skin is not pulled. The default skin is used.

---

---

**Cmi Version (using`/cmi version`):** 8.6.26.1
started around ver 8.6.24.4 / 8.6.24.3

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.15.2-R0.1-SNAPSHOT
git-Spigot-2f5d615-d07a78b

**Comment by mrfloris** [comment]
<img width="1392" alt="Screenshot 2020-05-20 at 22 07 53" src="https://user-images.githubusercontent.com/28841349/82492368-5c4e1c80-9ae6-11ea-9cc8-c4a0d2e35f96.png">

**Comment by 404uam** [comment]
Still broken as of CMI V. 8.6.26.3

**Comment by Zrips** [comment]
Confirmed, will be fixed with next build.
