### ISSUE TITLE
Horse teleportation changes the horse attributes

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#3343]
If one has the permission _cmi.teleport.with.horse_ and teleports with a horse, the horse will not store all of it's values. Only the speed is stored, the number of hearts and the jumping height changes randomly after each teleport.

CMI 8.6.26.1
Paper 1.15.2 - 282

**Comment by TheoRetisch1** [comment]
Confirmed for version 8.6.26.3 :/

**Comment by TheoRetisch1** [comment]
Confirmed for version 8.6.26.4 :/

**Comment by CloudeLecaw** [comment]
Confimed for 8.6.26.4 can paper #3180

**Comment by TheoRetisch1** [comment]
The permission is quite at the top on zrips.net (https://www.zrips.net/cmi/permissions/):
![CMI perm](https://user-images.githubusercontent.com/24480321/82913970-3fdf3380-9f6f-11ea-8462-e465abd0085b.PNG)
You can also find the permission ingame using the command `/cmi checkperm teleport` :)

**Comment by TheoRetisch1** [comment]
Confirmed for version 8.6.26.5 :/

**Comment by CloudeLecaw** [comment]
agree

**Comment by TheoRetisch1** [comment]
Confirmed for version 8.6.26.9 :/

**Comment by Zrips** [comment]
Should be resolved with next version
