### ISSUE TITLE
Feature request for chat

### ISSUE THREAD

**Issue by NineTown** [Zrips/CMI#3344]
Hello! There impossible to change location of shout icon (deafult is [S]). I need to change position of it (between prefix and nickname).

Can you please add my requested feature for several next updates? Thanks.

P.S. - glowing with any colors exept white (/glow) is not working on latest paper builds ;D

**Comment by mrfloris** [comment]
```
  # Defines range of shout messages to travel
  # Shout messages should start with ! and player should have cmi.chat.shout permission
  # GeneralRange should be enabled
  # set to 0 to shout across all worlds, -1 to disable
  ShoutRange: 200
  # Defines cost for each shout message
  ShoutCost: 0
```
It would be nice if we'd get an additional option in config.yml like we have for money symbol..

```
# Changes ability to move the Shout prefix to the end of the message.
ShoutPlacing: '[prefix][message]'
```

**Comment by Zrips** [comment]
Next version, you can use {shout} in chat format section
