### ISSUE TITLE
/cmi ptime dOwn instead of dAwn

### ISSUE THREAD

**Issue by MrPranklez** [Zrips/CMI#3347]
```
"/cmi ptime down" is spellt wrong would need to be "/cmi ptime dawn" also prompts the message that the time can't be set to this value (no matter which one is being used)
```

---

**Cmi Version (using`/cmi version`): 8.6.26.1** 

**Server Type (Spigot/Paperspigot/etc): tuinity (fork of paperspigot)** 

**Server Version (using `/ver`): git-Tuinity-"003c5b3" **

**Comment by Zrips** [comment]
Och, this should not even exist, will remove tab complete for it and replace with correct "morning" value. Thanks for reporting.
