### ISSUE TITLE
Unnecessary suggesting commands in info command

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3348]
**Question: **
Hello, isn't it unnecessary to suggest commands like (/tppos) etc. when player uses /info command and then click on Death / Pos / Bed it suggests him /tppos command. But... when player doesn't have permission to /tppos, why should it suggest?

**Comment by CloudeLecaw** [comment]
this is not unnescesary this

normaly no player should have access to the info command!
the line under it is the permission that is needed so the admin knows what permisisons are needed
to execute the command.

**Comment by Zrips** [comment]
Will be fixed with next update
