### ISSUE TITLE
Placing blocks with /cmi mirror in survival eats one extra block

### ISSUE THREAD

**Issue by xRebellion** [Zrips/CMI#3349]
**Description of issue:**
Hello, there is a minor bug within the /cmi mirror in survival. It seems to eat one extra block everytime you place a block. It always eats "Used block + 1". For example you mirror X to Z and Z to X, it's supposed to only use 4, but it uses 5 blocks from the inventory instead.

Also, a little bit of a minor typo:
![image](https://user-images.githubusercontent.com/32483348/82476282-fd919e80-9af7-11ea-82ce-3823df3498df.png)

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 
(I suppose this is enough)
![image](https://user-images.githubusercontent.com/32483348/82475906-6e848680-9af7-11ea-90e3-d21b01bfb512.png)

**Comment by mercurialmusic** [comment]
Confirming. Getting the same both with placing and breaking - seems to eat an extra block when breaking blocks as well. On CMI 8.6.26.3 using CraftBukkit version git-Spigot-2f5d615-d07a78b (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT).

**Comment by Zrips** [comment]
Will be fixed with next build
