### ISSUE TITLE
Repair Protections

### ISSUE THREAD

**Issue by v3Monsta** [Zrips/CMI#3352]
### Description of feature/improvement request: ###
Maybe I'm missing something but, currently, if I have an IC repair anvil setup to charge a player $15k to repair an item in their hand, the command doesn't take into account whether or not the item needs to be repaired. Instead, it sneakily takes the money from the users balance and it appears that nothing happened to them when, in reality, it's taken $15k with no feedback message.
---
### Detailed explanation of what it should do, when and in what situation: ###
The command should check if the player's item in hand needs to be repaired in the first place and, if so, send a message stating that the item is already fully repaired.

Note: I am referring to console running the /repair hand command on a player here as I have not tested the regular command.
### Basic explanation as to why this feature is needed and/or useful to have: ###
I explained above about why this seems like unintended behaviour but just to add to it, the only way a player would figure out what happened is when they keep spam clicking the IC thinking the server might be lagging, only to realize that it was working all along when the plugin sends the "not enough money" feedback message.

**Comment by Zrips** [comment]
New command cost feature can be used now to avoid charging when command fails
