### ISSUE TITLE
Spawn at first login

### ISSUE THREAD

**Issue by dodoflix** [Zrips/CMI#3355]
**Description of issue:**
Player's spawning in overworld at first login even i setspawn and setworldspawn at my lobby world (After they dead they will spawn at lobby)

**Cmi Version (using`/cmi version`):8.6.26.2

**Server Type (Spigot/Paperspigot/etc):paper

**Server Version (using `/ver`):1.15.2

**Comment by 404uam** [comment]
What does your config.yml look like? Find the spawn priority and post it here

**Comment by Zrips** [comment]
Should be resolved now with latest builds.
