### ISSUE TITLE
Teleporting to above the nether ceiling will teleport to bedrock

### ISSUE THREAD

**Issue by cryoten** [Zrips/CMI#3356]
**Question: ** When using TPA, Back or Home to teleport to a location above the bedrock ceiling in the nether, it will always teleport the player onto the bedrock floor of the ceiling. 

This appeared at some point after 8.6.24.1 - I updated to the latest today and it started occuring.

Is this an intended feature and is there a setting to disable it?

**Comment by Zrips** [comment]
Should be resolved by now
