### ISSUE TITLE
A way to color TPS placeholders?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3358]
Would it be possible somehow to set a color for a range of TPS so we can use it in-chat / tab / items / signs / etc ?
```
19->20 - default color
17->19 - orange
0->17 - red
```
Or whatever seems reasonable.

**Comment by Tanguygab** [comment]
%server_tps_1_colored%?

**Comment by CloudeLecaw** [comment]
you have these when you are using the extansion Server from hte Placeholder API

```
%server_tps%
%server_tps_1%
%server_tps_5%
%server_tps_15%
%server_tps_1_colored%
%server_tps_5_colored%
%server_tps_15_colored%
```
these allow you colors like u wrote above

**Comment by Zrips** [comment]
%cmi_tps_[range]_colored% from next version
