### ISSUE TITLE
Error. Warp gui show only 9 warp.

### ISSUE THREAD

**Issue by valenvaio** [Zrips/CMI#336]
Error. Warp gui show only 9 warp.

**Comment by LogGits** [comment]
Cmi version? Are there any errors in console? Can we see some screenshots (if possible)?

**Comment by MCTyler** [comment]
![screenshot from 2018-05-07 19-32-26](https://user-images.githubusercontent.com/6390898/39731485-77d9fe64-522d-11e8-825d-4c205cba4451.png)
This is using the Latest Version. That's more than 10.

**Comment by MCTyler** [comment]
Your Missing the Slot Info, See my Warps.yml I added above.
```
IcePlainSpikes:
  Location: world;1370.09;109.0;7895.23;245.04;-10.2
  Slot: 18
```

**Comment by CypherPhyre** [comment]
If you set a warp to slot 54 the full gui will open

**Comment by MCTyler** [comment]
Can we Please try to read instructions before posting issues? Too much to ask?

**Comment by valenvaio** [comment]
Of course I tried. And since I asked, I did not find an answer.

**Comment by valenvaio** [comment]
After recovery slot info it worked! Thank you.
