### ISSUE TITLE
Array support in /entitynbt

### ISSUE THREAD

**Issue by Fabrimat** [Zrips/CMI#3360]
Arrays in the entitynbt command are not shown correctly
You can try this on villagers with a job:
![immagine](https://user-images.githubusercontent.com/13642582/82690649-e3250580-9c5c-11ea-8c22-bb0e78efe8d6.png)
Didn't test with /itemnbt

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.6.26.2 BungeeCord  SqLite-> 8.6.26.3
Server: Paper(307) 1.15.2-R0.1-SNAPSHOT
CMI economy: True Vault: 1.7.3-b CMI Chat: False
Modules -> 43 enabled 7 disabled: worldLimits, tablist, votifier, vanish, playerChatTag, homeInteractions, bossBarCompass

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper version git-Paper-307 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will be fixed with next version
