### ISSUE TITLE
switchplayerdata not saving to database

### ISSUE THREAD

**Issue by codingvincee** [Zrips/CMI#3361]
**Description of issue:**
Critical and painful bug:
using cmi switchplayerdata doesnt just remove the old UUID-bound account, it also doesn't save the new one into the database.

All my players who have been switched lost all their CMI related stats.

---

**Cmi Version (using`/cmi version`):**  8.6.24.3 BungeeCord -> 8.6.26.3

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Build 261 - 1.15.2

**Comment by Zrips** [comment]
Should be resolved with latest builds
