### ISSUE TITLE
Lift signs port players  into the ground 

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#3365]
If the lift signs are at ground level and you teleport upwards you will end up in the floor block. When teleporting down, the player position is calculated correctly. The bug occurs in all gamemodes equally.
![Lift](https://user-images.githubusercontent.com/24480321/82732533-1b385100-9d0e-11ea-82d0-78b1a68ef617.png)

CMI 8.6.26.3
Paper 1.15.2 - 300

**Comment by Zrips** [comment]
Will be fixed with next build

**Comment by TheoRetisch1** [comment]
Thanks 👍
