### ISSUE TITLE
Votes are "autocompleted" - Player can get multiple Voting rewards by shortening his Playername

### ISSUE THREAD

**Issue by therealatsuga** [Zrips/CMI#3366]
You can receive multiple rewards if you enter your name in abbreviated form on the voting page. CMI completes the name and gives out multiple rewards. The longer the player name is, the more rewards the player can receive. 

It would be useful, if the Playername isn't autocompleted when receiving a forwarded Vote. 
---

**Cmi Version (using`/cmi version`):* latest

**Server Type (Spigot/Paperspigot/etc): Paper 309

**Server Version (using `/ver`): 1.15.2

**Relevant plugins (Delete if this isn't needed):NuVotifier

**Comment by Zrips** [comment]
Should be fixed with next build.
