### ISSUE TITLE
Add the missing features from EssentialsX /worth and /setworth to CMI.

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#3367]
Suggestion: Add the missing features from EssentialsX /worth and /setworth to CMI.

1. Allow /worth to search items that you do not have with /worth stone
2. Allow /setworth setting the worth of an item without owning it with /setworth stone 0.006

Make it the same as EssentialsX :

```
/worth <itemname>|<id>|hand|inventory|blocks> [-][amount]
/<setworth [itemname|id] <price>
```

**Comment by Zrips** [comment]
Will add first, but second one is already possible with /cmi setworth stone -s:0.99 tho it was missing tabcomplete or you have had older locale which dint contained this variable.

**Comment by FrozenBeard** [comment]
Awesome, thanks.
