### ISSUE TITLE
DiscordSRV broken in CMI 7.7.2.0

### ISSUE THREAD

**Issue by tmellen** [Zrips/CMI#337]
Description of issue or feature request:

Latest version of CMI (7.7.2.0) breaks DiscordSRV compatibility.

Chat from Minecraft to Discord doesn't work on the latest version of CMI. When returning to a previous version (7.7.1.1), chat from Minecraft to Discord works again. This is the only change made, backing out the update of CMI 7.7.2.0 to restore function of DiscordSRV.

**Comment by GrimPod** [comment]
Not working here either but to add
The Discord to minecraft is working.
And all events are happening from minecraft to discord,
Eg, Start/Stop, Join/Leave, Achivements  + Deaths

The only part that isnt happening is minecraft chat going to discord

**Comment by 2beFlo** [comment]
Can confirm the same Issue. Even more funny. Instead of sending messages to the Discord chan I got them displayed at my dynmap.

**Comment by LogGits** [comment]
This should be fixed in the latest update. Are you guys still having this issue?

**Comment by CypherPhyre** [comment]
Can't speak for the others but it is working fine for me.

**Comment by 2beFlo** [comment]
Is fixed for me.

**Comment by GrimPod** [comment]
Fixed
