### ISSUE TITLE
Adding commands to a stick doesn't work. 

### ISSUE THREAD

**Issue by HyenaGodKing** [Zrips/CMI#3370]
I reached zrip discord and tried many variations of commands to see if it would work but that didn't end up working to add the commands. I want to add commands on a stick so that when you hit a player with a stick the commands on the stick will happen to the player you hit. This was the command I was suppose to do while holding the stick; /cmi attachcommand asConsole! perm:cmi.pp! cmi sudo [interactedPlayer] town leave;;lp user [interactedPlayer] parent set slave;;ta town add [interactedPlayer] Guantanamo;;t spawn [interactedPlayer] I added this to the stick but when I hit someone it just makes them go to the group "slave" 

After doing that the only command that actually worked was the command where the players group would change to slave. I never had a problem with CMI until now. I have a bunch of IC's that work fine and the actual plugins commands are correct I'm just wondering what can I do to add those commands to the stick?

CMI version: 8.6.26.2

Server type: Paper

1.15.2

Plugins;
Lucky Perms
Towny
essentials
SkinsRestorer

**Comment by Zrips** [comment]
AS of recent change in how attached commands work, you are trying to utilize specialized commands. Issue would be with this settup that only first commands get permission requirement while others doesnt. This is due to how attached commands are processed, which needs to be updated, if possible.

**Comment by HyenaGodKing** [comment]
Thank you for informing, I'm just wondering when that possibly will be updated?

**Comment by CloudeLecaw** [comment]
Have you tried to do asConsole! And perm check for each command?

**Comment by Zrips** [comment]
This should be fixed with next build
