### ISSUE TITLE
Use COMMAND as teleport cause

### ISSUE THREAD

**Issue by NoChanceSD** [Zrips/CMI#3371]
**Description of feature/improvement request:**
---
Hi, basically in my plugin i'm trying to detect and block teleports caused by commands such as /tpa, /back, etc. For this i'm checking if the TeleportCause equals COMMAND which works fine for plugins such as Essentials but not for CMI which has PLUGIN as the cause.
### Detailed explanation of what it should do, when and in what situation: ###
When teleporting a player through any command, specify the TeleportCause as being TeleportCause.COMMAND.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Better compatibility with other plugins.

**Comment by Zrips** [comment]
Ok.
