### ISSUE TITLE
Mob farm manager is broken

### ISSUE THREAD

**Issue by msmanui** [Zrips/CMI#3372]
SOLVE  MOB FARM MANAGER WITH LASTES VERSION OF PAPER.... SYNC CHUNK LOADING SCREW MOBFARMMANAGER...

https://timings.aikar.co/?id=694cd10b8679408ead2a5745dc7aa13d

#mfm #needsUPGRADE

**Comment by Zrips** [comment]
Just a "silly" question here. Why do you have your auto clean scheduler set to 1 second? Even comment section recommends you to keep it above 30 seconds. This forces plugin to recalculate every single chunk around every single player online for any mobs who are over limit, which can be quite heavy task especially when you have 87 people online. Change it to default 30 seconds and check what results you will have with it.

**Comment by CloudeLecaw** [comment]
i allread wrote mobfarmmanager has a broken bug

**Comment by msmanui** [comment]
> Just a "silly" question here. Why do you have your auto clean scheduler set to 1 second? Even comment section recommends you to keep it above 30 seconds. This forces plugin to recalculate every single chunk around every single player online for any mobs who are over limit, which can be quite heavy task especially when you have 87 people online. Change it to default 30 seconds and check what results you will have with it.

I dont have it has to do with the interval as i used to have 100 people online (2 weeks ago) and in the timings the mobfarmmanager wasnt like this time. What did broke MFM was some updates of the lastest versions of paper (might be async chunks)

**Comment by Zrips** [comment]
Test new version and make sure you have auto clear set to decent amount, tho with latest version i'm forcing it to be atleast 30 seconds.
