### ISSUE TITLE
Virtual chests and boat passengers

### ISSUE THREAD

**Issue by tribrix** [Zrips/CMI#3373]
**Question: ** Is there a backpack/ virtual chest feature? 
There's mention of a shulker box on the features page but I can't figure it out.

**Comment by tribrix** [comment]
On my server players can't be passengers in boats, they teleport back. I looked at the cmi config and I have false set on all 3 "PreventEntityBoatEnter:" options, monsters, animals and villagers. Is this a bug?

**Comment by Zrips** [comment]
Shulker backpack can be opened if you shift+right click when you are holding one or you will click on one in your inventory with shift+right click. You will need cmi.openshulker.shift  for first action and cmi.openshulker for second. 
For boat passengers this could be cause by different plugin as i cant reproduce this one currently.
