### ISSUE TITLE
Hologram import isnt persistent

### ISSUE THREAD

**Issue by Korinocho** [Zrips/CMI#3375]
After importing holograms from Holographic Displays without any error, they wont be consistent, so after a plugin reload or server restart they are gone.

---

**Cmi Version (using`/cmi version`): 8.6.26.3

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper 301 (MC:1.15.2) R0.1-Snapshot

**Relevant plugins (Delete if this isn't needed):** Holographic Displays V2.4.2

**Comment by Zrips** [comment]
Good point, will fix it. Its somewhat bug from changes in default hologram behavior where they have been saved by default, but now you need to specify that. This is in case some one using CMI API to display holograms and forgets to specify that holograms should not be saved. Anyways, thanks for reporting.
