### ISSUE TITLE
Schedule command not working correctly

### ISSUE THREAD

**Issue by sibraxlis** [Zrips/CMI#3378]
**Description of issue:**
The bossbar is not being displayed before the server restarts, command is also behaving weirdly in the config.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
When I reload CMI:
  - cmi bossbarmsg all Server restarting in [autoTimeLeft]! -cmd:"restart" -sec:-60 -c:red
Becomes:
  - cmi bossbarmsg all Server restarting in [autoTimeLeft]! -cmd:"restart" -sec:-60
    -c:red
```

---

**Cmi Version (using`/cmi version`):** 
8.6.23 MySQL
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
 273

**Comment by Zrips** [comment]
Got fixed
