### ISSUE TITLE
Problem with nickname and edit sign

### ISSUE THREAD

**Issue by ludvdber** [Zrips/CMI#338]
Description of issue or feature request:

When a player set a nickname with underline, the underline is set on the chat, see on the screenshot for a better understanding 
[Screenshot here](https://image.noelshack.com/fichiers/2018/18/6/1525533401-underscore.png)

my second problem is that we can't edit the sign

Cmi Version (using`/cmi version`):  7.7.2.0
Server Type (Spigot/Paperspigot/etc):  spigot
Server Version (using `/ver`): 1.12.2

**Comment by WarmasterCain55** [comment]
I can second this happening.  It also happened to a group whose formatting was Italics. *which was quite funny to see*

**Comment by LogGits** [comment]
Can we get the the group format that group @ludvdber and your group format @WarmasterCain55? It would be very helpful 👍 

Also in terms of sign editing are you referring to the rightclick to edit signs?

**Comment by ludvdber** [comment]
yes, the right click to edit signs 

for the nickname, I found the solution, in the config.yml there is a default space after the ":" and when it is deleted, the problem is solved
in these lines:

  GeneralFormat: '&a[%player_world%]&f{jobs}{prefix}{displayName}&f: &r{message}'
GroupFormat:
    '1': '{prefix}&f{displayName}&f: &r{message}'
    '2': '{prefix}&f{displayName}&7: &r{message}'
    '3': '{prefix}&f{displayName}&8: &r{message}'
