### ISSUE TITLE
Ip location is no longer shown

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#3380]
Unfortunately since the cmi version 8.6.26.3 it is no longer possible to see where the user comes from. no matter who I try it with, there is only a green line to be seen.
You used to see the country and approximate place of residence, but now you see nothing.

![country](https://user-images.githubusercontent.com/35557302/82759014-7fc8de00-9dea-11ea-9bed-111ed3d7ebdf.png)

**Comment by CloudeLecaw** [comment]
I can agree with this i also saw just these two strips. Looking in the langfile Shows me two placeholders. These where working before cmi got the new Infocommand overview

**Comment by Zrips** [comment]
Yea, its a bug, will be fixed with next build.
