### ISSUE TITLE
IP Info  AFK state change ?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3381]
When getting the /cmi info from a user and you klick on the AFK in the list
Then the player is set not afk anymore each time u click it.
he also does not to be really afk for this

![Snag_2f2a823](https://user-images.githubusercontent.com/12080017/82764784-c41ba480-9e11-11ea-9873-43675368fd96.png)

Looks like there is no swap between AFK - NOT AFK
its just -> not AFK

**Comment by Zrips** [comment]
Yea, its simply performs checkafk command, but its not needed, will remove it.
