### ISSUE TITLE
Chatroom "Playername" creates invite // invite argument

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#3386]
**Description of feature/improvement request:**
The current invite is not logical
I hereby request to split the invite to a separate argument.

---
### Detailed explanation of what it should do, when and in what situation: ###
Current situation:
Player Steve makes a chatroom by executing `chat Steve`
Player Alex joins too by executing `chat Steve`
Steve gets an invite to join the Steve chatroom he already is in. Weird but ok.
Then Hellen joins the chatroom. She does `chat Steve`.
Steve gets his third invite for his own chatroom he already is in.
This goes on for every player joining the party. The name of the chatroom to reproduce this behavior is equivalent of a player, or just a part of an online player.

I think it's best if the invite is moved to a separate command/argument.
Example:
`/chat invite playername` to invite "playername" to join the chatroom the executing player  this is in.

### Basic explanation as to why this feature is needed and/or useful to have: ###
The current behavior is not logical and spams invites to the player with an equivalent name as the chatroom.

**Comment by CloudeLecaw** [comment]
i also would like to see an invite command maybe clickabble to accept/deny in chat too

**Comment by Blueeyestar** [comment]
That would be a sensible extension.

**Comment by Zrips** [comment]
Okey, will change its behavior. Wanted to keep old one, but it creates more issues than it solves.

**Comment by Blueeyestar** [comment]
You did a great job with it. For a long time I was looking for a chat plugin which is simple but so effective. I would also mention this on the spigot main page that you can create your own chat rooms with CMI. is a big added value in my eyes.
Thank you very much and keep it up. You are great

**Comment by CloudeLecaw** [comment]
great job!
