### ISSUE TITLE
Attachedcommands

### ISSUE THREAD

**Issue by banit** [Zrips/CMI#3387]
Update 8.6.26.3 broke my existing attachedcommands. 
with floris i found out that commands used to work like this:

"/attachcommands cmi heal" 
this worked fine for roughly 9 months now after the update i have to use the same command but with asPlayer! because the command will get used in the console by default wich wasnt the case before
"/attachcommands asPlayer! cmi heal" 
wich wouldnt be a issue for new items but i need either a fix or a way to migrate roughly 200+ items to this change. 

Paper 313 (1.15.2)
CMI 8.6.26.3

**Comment by banit** [comment]
Another issue i noticed if you are using the !cc! variable it will print out either unknown command or if you dont use it it will print out you dont have permission

https://i.vgy.me/k9dYPY.png

**Comment by CloudeLecaw** [comment]
what cc should be?

**Comment by banit** [comment]
its not about better, its about it worked this way for 9 months in wich i created tons of items with commands, wich lost their function bc in some updates zrips changed the way it works

**Comment by banit** [comment]
Occours on 8.6.26.4 aswell

**Comment by CloudeLecaw** [comment]
could you paste the command you attached? just 1-2 examples or us an errorlog if there is any`?

**Comment by banit** [comment]
https://i.vgy.me/8t2S98.png
this is one example... its /copy because the command would be //copy (world edit) 

another one more cmi related would be
https://i.vgy.me/KPNH0P.png
first one does not work anymore
second one does work

**Comment by Zrips** [comment]
Valid point, will fix this one. As we did moved to more complex method with specialized command handling, some issues surface from time too time, but we will iron this one out.
