### ISSUE TITLE
Maintenance optional extansion on/off /true/false) var

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3390]
Suggestion:   cmi maintenance **(-m:[true/false])** (message)

We created two custom alias that are changing the maintenance mode
at set a servermodt so players note the current state of the server allready at the serverseletionscreen.

![image](https://user-images.githubusercontent.com/12080017/82878745-35f00d00-9f3c-11ea-8f79-cf6cf3493263.png)
![image](https://user-images.githubusercontent.com/12080017/82878782-456f5600-9f3c-11ea-94c8-f06744fbd391.png)

and
![image](https://user-images.githubusercontent.com/12080017/82878857-5e780700-9f3c-11ea-82fa-eb0ce41d7337.png)
![image](https://user-images.githubusercontent.com/12080017/82878909-7780b800-9f3c-11ea-8c0b-c6e415149eeb.png)

So we designed two commands:
/wartung (means maintenance starts)
and /online (means maintenance ends)

Problem: the maintains command itself is just "swarping between maintenance ture/false
So the customalias that should turn on the maintenance can be wrong used to turn it off
and equal to that the costomalais that should turn in off can be used wrong to turn it on

a optional var for this command would be nice like true/false before the meassge.
then you could design the custom alias's to just set the maintenance true or false
(even if it is true or false allready)

if the var is not set it simply should swarp like it does now to keep compatiblity to the current useage for all server that use the swapmethode normaly :)

**Comment by Zrips** [comment]
Okey
