### ISSUE TITLE
Working with the menu on 1.7.10

### ISSUE THREAD

**Issue by LoopRich161** [Zrips/CMI#3391]
I enter any command related to kits and get this error, the menu is not called
Error with menu: 
https://pastebin.com/Rr9K6Gf4
https://pastebin.com/dMEmtgL9
https://pastebin.com/bNT0YAGQ
https://pastebin.com/FAUs6KwK
https://pastebin.com/x99GSZgf
https://pastebin.com/4yf3aL1d
My core: Thermos 1.7.10 latest build
My plugins: CoreProtect, LuckPerms, WorldEdit, Playtime, CombatLog, VoxelSniper, PlaceholderAPI, ClearLag, iConomy,  WorldBorder, Vault, CloseInventoryInTeleport, Multiverse-Core, ProtocolLib, WorldGuard, HolographicDisplays, QuickShop, CMI

Can you please fix this? I really like this plugin and I really do not want to leave it!

**Comment by LoopRich161** [comment]
https://imgur.com/lAjqzLC

**Comment by LoopRich161** [comment]
I tried the latest version (v8.6.26.5) and there are the same errors.

**Comment by CloudeLecaw** [comment]
i hope you know that Thermis is many other forks are not supported?

We could be happy that Paper (Paperspigot) and Spigot are supported

**Comment by LoopRich161** [comment]
I will wait for the answer of the developer. I hope he tries to recreate my situation and solve the problem.

**Comment by CloudeLecaw** [comment]
What is your situation that you need to run an 4 years outdatet serverversion?:3

All your listet plugin are allready made for 1.8+and even higher

**Comment by Zrips** [comment]
@LoopRich161 
Will make some changes related to your error logs, but in general CMI was not built to support 1.7.10 thermos and with time it will be less and less compatible which with next minecraft version could be dropped entirely due to possible huge changes in that version by itself. Test out next version and let me know if you still have issues.
