### ISSUE TITLE
wrong version number for the updater?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3392]
![image](https://user-images.githubusercontent.com/12080017/82920207-4d002080-9f77-11ea-8bb1-fcd505f3a280.png)

**Comment by the456gamer** [comment]
this is due to the spigot api caching requests
im pretty sure this is duplicated, but i cant find one right now

**Comment by Zrips** [comment]
When you are getting messages like this, it simply means that it ether dint updated at spigot end or I forgot to properly update its version in plugin.yml file, in any case its temporary issue.
