### ISSUE TITLE
Can't make multiple portals, There overriding eachother /Colliding?

### ISSUE THREAD

**Issue by ablac** [Zrips/CMI#3394]
**Description of issue:**
I created a Portal that goes to my Server (Creative) from by server (Lobby) this portal works great, but if i select another area to make a new portal, and run /cmi portals new survival it says cant create portal is colliding, and then deletes the creative portal and moves it to the new location where the survival portal should be. and this happens every single time. no matter how far away you are.

**Cmi Version (using`/cmi version`):** 
8.6.26.5

**Server Type (Spigot/Paperspigot/etc):** 
PaperMC

**Server Version (using `/ver`):** 
Paper version 313 MC 1.15.2

**Comment by ablac** [comment]
in order to make multiple portals, I have to create a portal, finish editing it, then reload CMI and this will allow me to select a new area to make a new portal.

**Comment by LagSquad** [comment]
Having the same issue. I have noticed the portal will continually resize with new selected positions. So when you select a new cuboid to make a new portal, it collides since the other portal is still stuck in your selection. Relogging seems to also 'unctick' the portal from the selected cuboid, allowing you to select a new one. Have an example up on streamable.

 https://streamable.com/rd6bl7

**Comment by ablac** [comment]
If you do /cmi reload after making each portal (it’s kinda annoying) but that will allow you to make another portal

**Comment by LagSquad** [comment]
Yes, same with re-logging for me. Yes, it is also kinda annoying.

**Comment by Zrips** [comment]
Will be fixed with todays update.

**Comment by LillithaCT** [comment]
Hi, I've updated CMI to 8.6.26.7 but portals are still broken.
When i try to create a portal in farmworld_nether it creates a portal in farmworld. And when i delete the portal named nether-farmworld and try to set a new portal it collides with the deleted portal

**Comment by ablac** [comment]
> Hi, I've updated CMI to 8.6.26.7 but portals are still broken.
> When i try to create a portal in farmworld_nether it creates a portal in farmworld. And when i delete the portal named nether-farmworld and try to set a new portal it collides with the deleted portal

You should make a new issue post, cause A) this post is closed
And B) its a different issue.
