### ISSUE TITLE
Version 8.6.26.5 causes info section of attached commands in locale to disappear

### ISSUE THREAD

**Issue by NightFuryStrike** [Zrips/CMI#3396]
**Description of issue:**
After updating to 8.6.26.5, the info section of the attached commands part of the locale/translation disappears and causes things such as cooldown messages to fail and say "missile locale".

The following outlined in red is what gets deleted after updating to 8.6.26.5 within Locale_EN in the Translations folder:
![image](https://user-images.githubusercontent.com/56176412/82956805-fd762080-9f87-11ea-829b-5bb211c180e3.png)

**Cmi Version (using`/cmi version`):**  8.6.26.5

**Server Type (Spigot/Paperspigot/etc):** Paper Build 318

**Comment by Zrips** [comment]
Will be fixed with next build. Was an issue with some experimental code when it comes to deal with such lines.
