### ISSUE TITLE
SelectionVisualizer - Copy causes server to crash

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#3399]
The newer builds of FAWE cause the server to crash when copying larger selections. Without SelectionVisualizer the size of the selection is no problem at all. In addition, version 1.13.2 never had problems with much larger selections. So it is not a general performance problem, but a new bug. It is also not due to the no-tick-view-distance of paper.

Error: https://pastebin.com/Pj0bf7yt

_How to reproduce_:
Copy 10 million blocks (sometimes it also happens with a clipboard of just 600k blocks) 

FAWE - 252 (https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
Paper 1.15.2 - 318
SelectionVisualizer 3.0.0.7

**Comment by Zrips** [comment]
Will push out new version. Tho they did changed something with WE API which started to cause this issue. Strange.

**Comment by TheoRetisch1** [comment]
Thank you, it works well 👍
