### ISSUE TITLE
Specific warp permissions

### ISSUE THREAD

**Issue by LordDarmix** [Zrips/CMI#34]
Hi there.

I'm trying to make specific warp permissions giving this permission to players as they complete a quest:

- cmi.command.warp.example

So from then, players can't warp to example using "/cmi warp example" neither using a custom alias for that purpose.
We get the "You don't have the permission for using that command" message.

Thanks for your time.

**Comment by MCTyler** [comment]
Did you enable it in the config?
`Gold:
  Location: world;669.19;71.0;-486.39;-93.58;4.94
  ReqPerm: true
  Slot: 3
  Item:
    type: GOLD_ORE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §6Prison Mine Gold
      lore:
      - §5Warp to Prison Mine Gold Level
      enchants:
        DURABILITY: 10
      ItemFlags:
      - HIDE_ENCHANTS`
Notice the ReqPerm: true?

**Comment by LogGits** [comment]
@LordDarmix The user will also need the permission node `cmi.command.warp` to be able to use the warp command.

**Comment by Zrips** [comment]
You can always see missing parmission in console or by hovering over error message if player has cmi.permisiononerror permission node.

**Comment by LordDarmix** [comment]
Thanks to the three of you.

We just noticed the node in the console. We also enabled it in the config.

I was searching for some way to allow players to use specific warps, not them all just by adding the cmi.command.warp node.

By the way the problem is solved. Thanks a lot.
