### ISSUE TITLE
 City info from geoip. 

### ISSUE THREAD

**Issue by valenvaio** [Zrips/CMI#340]
Can you add city info from ip?
Essentials_geoip plugin can show this.

**Comment by HomeLandingsDE** [comment]
I think that goes too far!
You already have IP and country, how do you need as server owner (admin) the city where the player lives?

I think that would be questionable!

**Comment by ScuroK** [comment]
well if he got the ip he anyway can find out the city doesnt he?

xD

**Comment by MCTyler** [comment]
I was thinking the ame thing about 30 features ago... :100:

**Comment by valenvaio** [comment]
I think that Russia is a big country and knowing only the country is extremely sad. The esential_geoin plugin issued such information from a file similar to the geoip.dat. It was very convenient for support and communication with users. But this plugin does not work without the mother-plugin. And Essential is no longer needed, since there is the CMI.

**Comment by CloudeLecaw** [comment]
this "from City Thing is nonsense. Why? because mostly (here in Germany for example) we are connected with an Provider and when we make this "where are we scan" then it tell us "you are in Dresden" because there is the next Station where the IP is connected from the Provider. so this What City Thing is totaly nonsense and just tells you where the Provider is where ppl are connected.

**Comment by valenvaio** [comment]
The provider is in the same city or region as the user. It's enough. Our server is played by people from at least 30 large cities of Russia. Some cities are more than 1000 km away. In Russia, the city is determined with probability close to 100%.
The city info function is convenient for administration and interesting for players when they see where other players come from. I do not see much difficulty in getting this information from the second file in analogy with the country. I can provide the file.

**Comment by CloudeLecaw** [comment]
ist enough to see the Country. you really give your Players the Information in what cities the other Player life?.. unbeliveable. So one Question: what can you do if one is saying "No hide my City, i  dont wnat others so see them? You must willing this. or u have an Agreement where execly is written down "if u Play on the Server your willing to Show all others the City where u life"  or something else…  an owner can really get Problems if he offers personal data to others. and giving it away. (if all and read them it is a give away to all) May your just had the luck, that for the Moment noone was saying anything aggainst it.. but this day can come.

Even if Russia is big. USA is also big and they all speak english even if they have their dialects.

**Comment by ScuroK** [comment]
I think its a but rude to calle it nonsence. Even i dont see a need for this i can understand the wish. 

But maybe you can find a seperate plugin for it.

**Comment by MCTyler** [comment]
If your that worried just use [Whois ](https://whois.icann.org/en)information on the Web.

**Comment by valenvaio** [comment]
It is inconvenient to use whois. Moreover, in the case of entering information about the city, the moderator may not be available information about the ip player. What is more important for privacy, if you are so worried about it. But there are social networks, dynamic ip, proxy, VPN. And for a long time already there is no your privacy.

If the plugin is positioned as a replacement for essentials why not expand the functionality? He already displays the country, can you add the field to the city? And make this setting customizable and bound to permission.

**Comment by CloudeLecaw** [comment]
As Zrips valencaio
Zrips NEVER said it is a replacement
This ust just comercial fan blabla because so many user of CMI notic that CMI has so much functions and also more. But it never was called official a Replacement.

Say NO to GeoIP!

**Comment by valenvaio** [comment]
After all, I would like to hear the opinion of Zrips.

All with a holiday on May, 9th.
![img5](https://user-images.githubusercontent.com/38116174/39807064-157d2c2a-5384-11e8-9949-1c499b878cf2.jpg)
![66let2](https://user-images.githubusercontent.com/38116174/39807067-17c9727c-5384-11e8-852e-a30b6a9ed501.jpg)

**Comment by CloudeLecaw** [comment]
hm may this is one of the reason why in europe noone has a fee day in 9.05
This whole nazi Germany Thing is an old oudated model and has Nothing to do with the Germany of today. Today most Germans are happy that we got no naziGermany. so ist just normal that we dont mind and dont even thought once, in a day like this anymore, and specily dont celebrate it. Im 45 Years now, and never heard of your glorius day that you celebrate each year on 9.may.. an i am german… never mind...the star in your secould pic Looks cools just the black White Background of this old outdated armystuff is Nothing for me..
for us the 09.05 has absolutly no significance ...sorry :3

**Comment by valenvaio** [comment]
CloudeLecaw:
> Zrips NEVER said it is a replacement for Esentials
> He just said it has simliar functation and Features and even more.

However, the main page of the plugin says the following:
> This plugin is made to be all in one plugin for server management and replace multiple outdated plugins. It can fully replace Essentials/EssentialsX and contains simple conversion commands to transfer old player data to new system.

**Comment by ScuroK** [comment]
i just hate how many people write shitty troll comments on the CMI issues page.

**Comment by CloudeLecaw** [comment]
Thank you ZrIps for this Statement: <3

> Long story short. CMI is not a Essentials. You can compare features if you want, but this is not a d*ck measuring contest. CMI does majority stuff what Essentials can, Essentials does something what CMI currently is not. Comparing them will not be productive way. Look at CMI as a plugin for your server, not a plugin which should do exactly same things as Essentials and something more.
> Will have to close this one as this is more appropriate for forum section and not for github.

original post can be foudn here:
https://github.com/Zrips/CMI/issues/354

**Comment by LogGits** [comment]
Added in latest patch. User will need permission to see users ip to see the geoip info. You will need to hover over the ip in `/cmi info`.
