### ISSUE TITLE
Private Chat Rooms

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#3400]
**Description of feature/improvement request:**
I had notice that chat rooms had improved nice, however I would love to be able to create private chats, so if player is not invited he will not be able to join (Obviosly that should be an option)
Maybe /chat create (name) (value) example /chat create test private 

### Basic explanation as to why this feature is needed and/or useful to have: ###
This feature would be usefull to stop not wanted players to join to your group and just make a mess in their chat or something on thoes lines.

**Comment by CloudeLecaw** [comment]
Well if Player is not invited how will be know the chatroomname?

**Comment by arturek1666** [comment]
Well there is something like /chat list with shows all the chats and you can just join it xD 
![image](https://user-images.githubusercontent.com/1558228/83123136-7e3e3500-a0cc-11ea-9d02-7fa90f865252.png)

**Comment by CloudeLecaw** [comment]
chat list only works if you have permission for that..just by the way. Why players should have this? to see where everyone is?

**Comment by arturek1666** [comment]
Ok I see thanks for explainig closing this

**Comment by CloudeLecaw** [comment]
Your idea is gave a good hint what is mssing - privacy for players

mostly this can be handled  with permissions :)

So i made a new request #3406 for asking to add ome more permissions to this chat command feature so players can have more pricacy
