### ISSUE TITLE
Prevent Villager Spawn Iron Golem

### ISSUE THREAD

**Issue by yimyum** [Zrips/CMI#3401]
**Description of feature/improvement request:**
Villagers spawn iron golems allowing iron golem farming. Other plugins such as mob stacker prevent this from being out of control, but unfortunately with Mob Farm Manager it seems like it can't prevent iron golem farms from being out of control. Even if you limit iron golems most iron golem farms are tower based so it means nothing, meaning they just fall out of chunk and they don't get deleted faster than they die.
---
### Detailed explanation of what it should do, when and in what situation: ###
If you want villagers and iron golems but you don't want villagers to spawn iron golems then i suggest preventing natural spawning iron golems from villager gossip, but allowing building golems and potentially golem spawners maybe? not that any server with this function would have golem spawners.
### Basic explanation as to why this feature is needed and/or useful to have: ###
For some golem iron farms using villager gossip you can have an entire double chest of iron ingots in mere minutes. There's no function in this plugin to prevent this since the way they're usually built to function.

**Comment by CloudeLecaw** [comment]
Why dont set iron Golem to 1 in the config?

**Comment by Zrips** [comment]
I can definitely add option to disable iron golem spawning in villages trow natural means while keeping generic built of them.
