### ISSUE TITLE
Placeholders for top 10 !number! of votes

### ISSUE THREAD

**Issue by thomaboehi** [Zrips/CMI#3402]
**As we have separate placeholders for money:**
```
%cmi_baltop_money_[1-10]%
%cmi_baltop_name_[1-10]%
```
It would be great to have this for the votes, I tried with ParseOther Placeholders, but doesn't work.

```
%cmi_votetop_name_[1-10]%
%cmi_votetop_count_[1-10]%
```

**Comment by CloudeLecaw** [comment]
Didnt you know there is a topvote allready?

**Comment by thomaboehi** [comment]
I know all placeholders, and I know the plugin by heart, I translated it. Yes this is what I want.

**Comment by CloudeLecaw** [comment]
hmm i translated it too^^

**Comment by thomaboehi** [comment]
That wasn't the point... -.-

**Comment by CloudeLecaw** [comment]
You got a placeholder wirh last update. May wanne close?
