### ISSUE TITLE
Tpa [Accept] clickable area (and Tpahere too)

### ISSUE THREAD

**Issue by emanondev** [Zrips/CMI#3403]
**Description of issue:**
After /tpa <player>
Target player reiceve a message with 3 components which are: [message][accept clickable area][deny clickable area]

Each component is supposed to have his own hover message and his own click action, which is no click action at all for [message] component.

Due to BaseComponent from spigot bug, [message] inherith [accept clickable area] click action, so clicking the message result into accepting the teleport, several players reported of accepting the teleport by mistake with unpleasant conseguences for their gameplay.

Proposed solution 1:
Clicking accept / refuse do suggest the command  instead of executing it, as a doubleconfirm solution which should avoid any mistake.
This could also be added as a togglable option on config file, allowing to choose if direct execution is preferred over suggestion for tpa command or viceversa, allowing old behavior to be maintained for who prefer it as it is right now.

Proposed solution 2:
To fix BaseComponent mistake [message] component should have his own action to avoid it from inheriting other component's actions, that action might still be something which result into doing nothing.

Note: similar issue exist for /tpahere

**Comment by CloudeLecaw** [comment]
Is this a bug report? It sounds more like a request...

**Comment by Zrips** [comment]
@emanondev 
Couple things. Server version? Currently by default message and accept button performs command and doesn't suggest it. I can change that and remove it to avoid confusion, it was just to simplify accepting teleport requests.

**Comment by emanondev** [comment]
The Server is Tuinity version git-Tuinity-"121cca1" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
(a Paper fork, but this mistake on BaseComponent[]/ComponentBuilder is present on Spigot and any Spigot).

I know directly executing the command on click might be faster, but if your home location is your biggest secret (Vanilla like server) a double check might be a life saver. 
A creative server of course won't need confirmation by suggestion so the command may be executed directly on click.

The ability to toggle this choice should satisfy both server type.

**Comment by Drc-DEV** [comment]
I have the same issue on plain paper 1.15.2

**Comment by Zrips** [comment]
This was resolved
