### ISSUE TITLE
On every vote server stops

### ISSUE THREAD

**Issue by Andoz** [Zrips/CMI#3408]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```

My error is here: https://pastebin.com/raw/zfMsxd3p

```

---

**Cmi Version (using`/cmi version`):** 8.6.26.6

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):** Skript, nuVotifier

**Edit:** I have tried to write on nuVotifier help before but they are sure that their plugin is not causing the error. https://github.com/NuVotifier/NuVotifier/issues/190

**Comment by Zrips** [comment]
Check what commands you are performing, because server doesnt stop because of CMI, it only starts performing commands which fails to be processed by your script plugin as indicated in a log ch.njol.skript
