### ISSUE TITLE
Add possibility to disable safe tp

### ISSUE THREAD

**Issue by Phoetrix** [Zrips/CMI#3410]
**Description of feature/improvement request:**
Hi! I have an event in my server who works fine with Essentials.
Since I use CMI I have a problem with the safe TP. My event consist to tp a player in the air (so considering to an unsafe location by the plugin) but the plugin tp the player on the ground.

I do some tests as OP in Minecraft 1.15.2 (with last version of the plugin) and when i'm in creative mode, tp in the air works, and tp in the air also work when I have god mode enabled.

I also test the setting "SafeLocationDownThenUp" in config.yml in true/false and nothing change.
Is it possible to add this option in the configuration? I really need it :)

Thank you in advance!

**Comment by Zrips** [comment]
You could simply negate cmi.safeteleport permission node entirely or temporarily when teleporting player to this special location.

**Comment by Phoetrix** [comment]
Thank you very much! My problem is solved! :D
