### ISSUE TITLE
New command /chat delete <ChatName>

### ISSUE THREAD

**Issue by FaMa91** [Zrips/CMI#3415]
It would be useful having a command to delete chats or we'll be overwhelmed of useless chats.

---
### Detailed explanation of what it should do, when and in what situation: ###
If I'm alone in a chat and I would like to delete it I could perform /chat delete <ChatName> and I'll be kicked and the chat disappear.

If a chat is empty, it'll be deleted after a while

### Basic explanation as to why this feature is needed and/or useful to have: ###

Without this feature we'll be overhelmed of useless chats

**Comment by CloudeLecaw** [comment]
if you leave a chatroom and noone is in it gets deleted automaticly

**Comment by FaMa91** [comment]
I tried, but I can join again, even if chat was empty

**Comment by CloudeLecaw** [comment]
if u join it aggain u open it aggain ;)

**Comment by FaMa91** [comment]
So what's the point having /chat create?

**Comment by CloudeLecaw** [comment]
You create the chat with it. But if you leave the chat then its closed/deleted there cant exists empty chatrooms

**Comment by FaMa91** [comment]
> if you leave a chatroom and noone is in it gets deleted automaticly

If a chat is deleted, it should be like it's never existed (more or less).

> if u join it aggain u open it aggain ;)

So it's not deleted, it's only "closed" in some way.

> You create the chat with it. But if you leave the chat then its closed/deleted there cant exists empty chatrooms

Closed and deleted are 2 different things, if I open a chat, someone can write in it, if I close a chat, I can reopen it, if I delete a chat, it doesn't exist anymore, unless I create it again

**Comment by FaMa91** [comment]
One of the recent updates added the function to delete empy chat after an amount of time you can choose in setup, so this request is no more needed. Thank you
