### ISSUE TITLE
groundclean remove fishing_hook

### ISSUE THREAD

**Issue by FaMa91** [Zrips/CMI#3418]
groundclean remove fishing_hook, so for a player seems that he stopped fishing for no reason.

Putting it in the whitelist doesn't work, probably because entities can't be whitelisted.

Best solution would be to have a whitelist for entities, not only items.
---

**Cmi Version (using`/cmi version`):** 2.6.26.7

**Server Type (Spigot/Paperspigot/etc):** paper(284)

**Server Version (using `/ver`):** 1.15.2

**Comment by CloudeLecaw** [comment]
![Snag_9512d7](https://user-images.githubusercontent.com/12080017/83405676-5244eb80-a40d-11ea-8b4a-a818d43deef1.png)
 cant agree with you

**Comment by FaMa91** [comment]
thank you for the tips, but I didn't said "fishing_rod" I said "fishing_hook".

If you are fishing, groundclean will remove the bobber and the player have to recast it.

**Comment by CloudeLecaw** [comment]
A photo would be nice. You mean the fishingwire gets Removed. Welll how often your doing grundclean that players nees to rethrow their rods each time?

**Comment by FaMa91** [comment]
I scheduled it every 20 minutes but I'll remove it soon. Anyway it's a minor bug to fix.

**Comment by FaMa91** [comment]
Yes, I mean fishing wire and fishing bobber

**Comment by Zrips** [comment]
Will be fixed with next build
