### ISSUE TITLE
Request: Selective inv view block

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#342]
Could you add permission node required to view inv by groups? Have an issue where players are able to not only see their inv but the inv of others. This includes staff in other game modes and when staff are in vanish

**Comment by MCTyler** [comment]
[05:26:06 INFO]: 1. cmi.command.invcheck
    [05:26:06 INFO]: 2. cmi.command.invcheck.edit

    cmi.command.invcheck.bypass

Add this Perm?

**Comment by MCTyler** [comment]
But if admin has bypass no one can check so you only need 1 perm instead of umpteen Million groups.

**Comment by Zrips** [comment]
Its over complicated and unneeded thing to have multiple groups for inventory check when you can prevent inv check with permission already.
