### ISSUE TITLE
Glitched custom portal particle effects

### ISSUE THREAD

**Issue by tzllzl** [Zrips/CMI#3420]
**Description of issue: When creating new portals occasionally the particle effect glitches, as shown below. This seems to occur more frequently at large X/Z coordinates.
![problem](https://user-images.githubusercontent.com/66190350/83342978-00904a00-a2c3-11ea-8844-a34b4222934d.png)
**

---

**Cmi Version (using`/cmi version`): CMI 8.6.26.7 SqLite** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`): git-Paper-325 (MC 1.15.2)** 

**Relevant plugins (Delete if this isn't needed): CMI**

**Comment by Zrips** [comment]
Will be fixed.
