### ISSUE TITLE
"cmi skin" command is still allowed (+tabcomplete) even when it is disabled

### ISSUE THREAD

**Issue by Qveshn** [Zrips/CMI#3423]
CMI8.6.26.6.jar

config.yml\Skins\Enabled: false
Modules.yml\skin: false

But I can still type "/cmi skin" and it displays help. Tab complete also works.
After "/cmi skin <playername>" it shows that function is unavailabled.

I expected this command to be completely excluded from the list when disabled.

Is it a bug?
Also what difference between `config.yml\Skins\Enabled: false` and `Modules.yml\skin: false`?

**Comment by CloudeLecaw** [comment]
one is the modul itself that it works (the one in modules.yml)
and in config its the command handler where to save and manage skins

**Comment by Zrips** [comment]
@Qveshn 
Well its some what bug, will remove config section from config file and will make it properly disable skin command if module is disabled
