### ISSUE TITLE
can't build in spawn when someone is OP'd

### ISSUE THREAD

**Issue by Ahmadh26** [Zrips/CMI#3427]
**Description of issue:**
my builders/admins cannot build in a range of 15 blocks of where i set the worldspawn   (where i do /setfirstspawn /setspawn) IF someone is OP'd on the server. when everyone is DE-op'd they can build normally

---
Here is a video of it.

https://youtu.be/olM_RVYMhUs
---

**Cmi Version (using`/cmi version`):** 
CMI: 8.6.26.7 BungeeCord SqLite
CMI economy: True Vault: 1.7.3-b CMI Chat: True
Modules -> 42 enabled 9 disabled: flightCharge, ranks, votifier, moneyCheque, skin, elytraBoost, spawners, spawnerCharge, elytraLaunch

**Server Type (Spigot/Paperspigot/etc):** 
Paper(284) 1.15.2-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 
Paper(284) 1.15.2-R0.1-SNAPSHOT

**Relevant plugins (Delete if this isn't needed):**
BungeeTabListPlus, CMI, CMIPaperLib, CoreProtect, DiscordSRV, DiscordSRV-Staff-Chat*, GriefDefender, LibsDisguises, LuckPerms, PlaceholderAPI, ProtocolLib, Vault, WorldEdit, WorldGuard

**Comment by CloudeLecaw** [comment]
have you took a look in your server properties?^^

**Comment by Ahmadh26** [comment]
> have you took a look in your server properties?^^
> 
> What ever you a telling here if the OP thing has nothing to do with CMI
> CMI is not setting permission rankand is not handling OP or not OP nd also it has nothing to do with your protection.
> 
> you should check your other plugins if you use otherswhat is creting is issue. check your CoreProtect, or yourGriefDefender or your Worldhaurd what went wrong here.
> 
> my Olso updating paper to latest 326 helps too? you should really try.
> you would see your error also will happen without CMI on your server.
@CloudeLecaw 
I have been having this issue for ages, but i recently discovered it's CMI because i moved the spawnpoint, when i did that the issue happened on the new spawn point and CMI handles that.
I've had it also before adding Griefdefender/worldgaurd as far as i remember.

i'll try removing CMI and see if it still happens later on today and post an update here

**Comment by CloudeLecaw** [comment]
lol but belive me cmi does not handle anything that has to do with building protection soyour issues is somewhere elese;)
But you can also wait for ZriPs the Dev to tell you that.

**Comment by Zrips** [comment]
CMI doesn't control block breaking any shape or form around spawn points or anything like that. Server itself will protect area 16 blocks in range around worldspawn. Check your server config options, you can start from server.properties and check spawn-protection section. 
But no, this doesn't originate from CMI, its basic spawn area protection by server itself or another plugin.
