### ISSUE TITLE
cmi economy commands are still enabled after disabling economy and do bad things

### ISSUE THREAD

**Issue by Qveshn** [Zrips/CMI#3428]
CMI8.6.26.6.jar

config.yml\Economy\Enabled: false

But commands like `/cmi money ...` `/cmi sell` `/cmi worth` are still enabled!
They do not change balance, but they are enabled and some of them do some bad things.
For example
`/cmi sell` (stone in hand)
> Earned 0.39 by selling 1 items. New balance 0.0

Balance is not changed - it is good, but the stone has disappeared - it is bad!
Expected that "economy" commands must be disabled when economy is disabled in config.yml

**Comment by CloudeLecaw** [comment]
you know that is is nonsense?
If you use no economey then dont give your players permission to this comamnds

**Comment by CloudeLecaw** [comment]
pls close this bug report :)

**Comment by Qveshn** [comment]
Please, tell me what does `config.yml\Economy\Enabled: false` mean?
What for this option does exist if I can always disable it via permissions?

IMHO: I still think that this is a bug. May be it is not blockker, critical or major bug.
May be it is trivial, but it is still a bug

If you say, I will close this issue 😟 
But I would like @Zrips to take a look at it

**Comment by CloudeLecaw** [comment]
Its allows you to use CMi fir Economy or not. If you say fasle thia just means you dont use economy or have an other plugin for your server economy cms just xont take care if it if u have seld it to false.  BUT this does NOT mean its commands dont work. In you current idea cmi could be the only existnng economy

**Comment by Qveshn** [comment]
😟
