### ISSUE TITLE
[Request] Can GUI for /cmi gamerule make blue items interactable?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3430]
Currently when we use 

`/minecraft:gamerule spawnRadius`
it says for example 15
`/minecraft:gamerule spawnRadius 155`
changes it to 155

Then seeing what cmi has:
`/cmi gamerule`
shows a menu with new value 155, so that works
`/cmi gamerules spawnRadius 44`
opens the gui and it shows the value is set to 44

querying it with `/minecraft:gamerule spawnRadius` tell us it's indeed set to 44.

So that works, but the blue items in the gui menu don't seem to be interactable. I can't click or shift click them to increase them by 1 or 10 (on shift).  Or right click to remove 1 or shift right click to jump in steps of 10.

Either we're doing something wrong, or it used to work and is now broken, or if it's not implemented, then I guess this is a feature request

**Comment by CloudeLecaw** [comment]
This feature aktually not inside. but would be a nice addition :) i  like this idea! :)

**Comment by Zrips** [comment]
Should be in working order with next update
