### ISSUE TITLE
Сhat filter does not work correctly

### ISSUE THREAD

**Issue by archroot** [Zrips/CMI#3431]
Does not block messages through:
/msg
/cmi msg
/cmi replay

![image](https://user-images.githubusercontent.com/41123605/83423753-1bce9700-a434-11ea-9d94-1bd0563e2873.png)

Also, chat is not filtered by other plugins if ClickHoverMessages is enabled: true

Example:
https://github.com/DenAbr/ChatGuard/releases

[16:17:36 INFO]: Версия плагина CMI: 8.6.26.7 SqLite
[16:17:36 INFO]: Server: Paper(333) 1.15.2-R0.1-SNAPSHOT
[16:17:36 INFO]: CMI economy: Да Vault: 1.7.3-b(CMIEInjector) CMI Chat: Да 
[16:17:36 INFO]: Modules -> 49 enabled 2 disabled: tablist, votifier

**Comment by CloudeLecaw** [comment]
write down your chatfilter pls^^
The Chatfilter is made to work with CMIs chatsystem..there is no garantie that is works with other chatplugins if they dont hook correcly into CMI

**Comment by Zrips** [comment]
Will add option to check private messages by same rules as it would apply to public chat
