### ISSUE TITLE
[Request] Command to clear item name, Command to clear item lore

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#3432]
Could we please get a command to clear an item name and a command to clear item lore, that i could then use to attach to a sign that players could pay to use?

**Comment by Zrips** [comment]
asConsole! cmi itemname -p:[playerName] remove
asConsole! cmi itemlore -p:[playerName] remove
Tho keep in mind that with lore command you will only remove first line, but you can always repeat this action to remove all of them or you can define which line specifically should be removed

**Comment by FrozenBeard** [comment]
@Zrips Slight issue, if the item does not have a lore and you run the remove, it just adds the lore "Remove", but it does not do that with itemname.

Could we get this fixed please? Then this is working with items with 1 lore line can be removed.
