### ISSUE TITLE
DiscordSRV Integration

### ISSUE THREAD

**Issue by DarkFort** [Zrips/CMI#3433]
**Please tell me how to make only global chat appear in Discord?
![image](https://user-images.githubusercontent.com/25278617/83438554-49263f80-a44a-11ea-8bd4-69cf06a0af43.png)
![image](https://user-images.githubusercontent.com/25278617/83438582-56dbc500-a44a-11ea-8ed8-8ed6fa3c356c.png)
Perhaps here you need to specify the name of the chat? Then what is the name of the global chat?
![image](https://user-images.githubusercontent.com/25278617/83438683-812d8280-a44a-11ea-898e-450213d63743.png)

 **

**Comment by thecenters** [comment]
You need a chat plugin that can handle multiple chatrooms

**Comment by Ahmadh26** [comment]
I've been searching for the name of the global, local and admin chat for ages. i don't think they use channel names. commenting to see if zrips replies and if there actually is a channel name.

**Comment by Zrips** [comment]
Added with latest build
