### ISSUE TITLE
DiscrodSRV Placeholders Dosn't work

### ISSUE THREAD

**Issue by Tsumitsuki** [Zrips/CMI#3434]
Description of issue:

DiscordSRV Changed some stuff with the 1.19.0 update
Since than the papi-placeholders dosn't work any more.
Everything else works finde with papi. 
The DiscordSRV Team couldnt find anything wrong on their side. They assumed a problem with CMI.

While sending from MC to DC
Message send in MC: [Global] Owner Tsumitsuki: t 
Message recived in Discord: %vault_prefix%Tsumitsuki:  t

both ventureChat and DSRV have the vault_prefix set.

toggle CMIs DiscordSRV Support setting dosn't changed anything

---

Cmi Version: 8.6.26.7 MySQL

Type: Paperspigot

Server: git-Paper-194 (MC: 1.15.2)

Relevant plugins: CMI, DiscordSRV (1.19.0), PlaceholderAPI (2.10.6), Vault (v1.7.3-b), VentureChat (2.18.6)

**Comment by Blueeyestar** [comment]
I also had problems but was fixed with the DiscordSRV-Build-1.19.1-SNAPSHOT. Please test it with it and then it should work again

https://snapshot.discordsrv.com/

Maybe it helps. It helped me because 1.19.0 didn't work for me

**Comment by CloudeLecaw** [comment]
I can agree that the last one was broken but the snapshot solved it.

**Comment by Tsumitsuki** [comment]
newest 1.19.1 snapshot from discrodSRV fixed it.
