### ISSUE TITLE
Silent Chests Inventory Issues

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#3437]
**Description of issue:**
Seems to be some weird inventory glitches in the recent CMI 8.6.26.8 release with vanish and silent chests. When in vanish and silent chests is true (noisy chests false) items placed in chests are immediately deleted when placing them into a chest. When silent chests is false (noisy chests true) items (and stacks) are duplicated when clicked on inside the chest (similar to the middle mouse button action).

No error in console.

**Cmi Version (using`/cmi version`):** 8.6.26.8
**Server Type (Spigot/Paperspigot/etc):** Spigot
**Server Version (using `/ver`):** CraftBukkit version git-Spigot-2f5d615-1b2830a (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by thecenters** [comment]
Same for me using the latest version of Paper

**Comment by Silyputy** [comment]
1 Version back on Paper and i had the same problem.

**Comment by Zrips** [comment]
This should be resolved with todays update
