### ISSUE TITLE
Vanish

### ISSUE THREAD

**Issue by AlfreDGR** [Zrips/CMI#3438]
**Description of issue or feature request:**

When someone puts on vanish it works perfectly but when you take off the vanish (the message that it is off comes out) it continues to be and does not take off
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.26.8
**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by CloudeLecaw** [comment]
vanish (playerName/list) (on/off)
If you having issue like that why not try the on off Argument?

**Comment by AlfreDGR** [comment]
I put the argument off and continue with the vanish since the error was generated in the last update in the previous one works correctly

**Comment by Zrips** [comment]
@AlfreDGR 
If you are getting errors in console, it would be nice to see them. And it would be nice to know what exactly remains after you turn vanish off, picture would be nice.

**Comment by AlfreDGR** [comment]
There are no errors in the console but for example if you put vanish on, it works well but if you put it off, you are still vanish even if it comes out in the chat that you are no longer in vanish

**Comment by Zrips** [comment]
So players cant see you when you leave vanish mode? Have you tested this without any other plugin to make sure its not some compatibility issue with one of your plugins?

**Comment by AlfreDGR** [comment]
It is not a problem with any of my plugins. This error appeared when I installed the latest update on 8.6.26.8. I solved it by reinstalling the old 8.6.26.7

**Comment by Fiks75** [comment]
Same problem. The player turns on the vanish, then disables the vanish and this does not work. In fact, the vanish does not turn off and you can not put or take objects from the chests.
CMI 8.6.26.9

**Comment by AlfreDGR** [comment]
In the last update dont repair vanish, you can test that in my server if you want. I can give you OP and use the vanish, and now gm 3 its bug with 8.6.26.9

**Comment by Fiks75** [comment]
Same problem. The player turns on the vanish, then disables the vanish and this does not work. In fact, the vanish does not turn off and you can not put or take items from the chests.

**Comment by Nildrak** [comment]
Can confirm reverting back to CMI 8.6.26.7 fixes the issue

**Comment by SmallSansSerif** [comment]
Can also confirm a bug. Seems like vanish is off however you still get the opened silently message with no chest open noises, no item removal as if you were in vanish. Rolled back to version 8.6.26.7 to restore normal vanish and chest open and item behavior.

**Comment by Zrips** [comment]
Should be resolved now
