### ISSUE TITLE
Mute

### ISSUE THREAD

**Issue by AlfreDGR** [Zrips/CMI#3439]
**Description of issue or feature request:**

When your silence is a player, I can't speak on the chat, that's fine, but I can speak for silence and speak for help.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 
8.6.26.8
**Relevant plugins (Delete if this isn't needed):**

**Comment by CloudeLecaw** [comment]
This is normal because admins have a bypass for silence

**Comment by AlfreDGR** [comment]
I mean that people without the bypass can do it, I know that people with op can violate it but it is happening with normal users

**Comment by Zrips** [comment]
Muted players will only be stopped from talking in public chat. You can still send private messages and talk in chat rooms. You can set DenyPrivateMessages to true in config file if you want to prevent private messages from muted players.

**Comment by AlfreDGR** [comment]
Ok I saw, now they cannot speak via msg, but they can use helpop to speak to us. Couldn't you add some option to disable helpop in mute?

**Comment by CloudeLecaw** [comment]
so they missuse the helpop feature? awww but only people with the permission can see the helpop chat

**Comment by AlfreDGR** [comment]
a blacklist for comamnds while muted Very nice idea!!!
