### ISSUE TITLE
Give Potion

### ISSUE THREAD

**Issue by DJDhuster** [Zrips/CMI#3440]
**Question: **
Hello,
How to give yourself a specific potion?
I mean how to set power and duration if i want speed 2 potion for example

**Comment by CloudeLecaw** [comment]
give (playerName) [itemname] (amount)
Give item to player

Example:

 /cmi give stone
/cmi give Zrips stone 5 n Stonehenge
 /cmi give stick e knockback:1
 /cmi give Zrips sponge l Got_item_on:_%date/YY/MM/dd-HH:mm:ss%
 /cmi give Zrips sponge 1 e Knockback:%rand/1-5%
 /cmi give Zrips sponge %rand/1-10%
 /cmi give sponge a maxhealth:5:mainhand
 /cmi give diamond_sword unbreakable
 /cmi give mob_spawner:creeper
 /cmi give minecraft:diamond_helmet 1 0 {ench:[{id:0,lvl:100},{id:2,lvl:100},{id:34,lvl:100}]}

You see giving potion with effect x and time z is possible just needs a bit of metadata entering

**Comment by DJDhuster** [comment]
I'm using the 1.15.2 version

**Comment by CloudeLecaw** [comment]
> /cmi give potion:speed-true-true  i thought he also wants the "level and time"

**Comment by Zrips** [comment]
@CloudeLecaw 
Potions doesn't have specific option to define time and level, you can have ether have basic potion or have it with 2 extra things: upgraded, extended. This is why we have those 2 true's which would indicate level 2 potion with extended time.

**Comment by DJDhuster** [comment]
And is it any possibility to also change name of potion in the command? Cuz now every potion is called Water Bottle

**Comment by DJDhuster** [comment]
And is it any possibility to make two word name. Cuz Now every potion is called Water Bottle and I want to switch it to specific name
