### ISSUE TITLE
Bug with private messaging across Bungee Servers

### ISSUE THREAD

**Issue by DaveDevil** [Zrips/CMI#3441]
**Description of issue:**
1. Setup a bungee network with CMIB and 2 paper servers 1.15.2 with CMI

2. Activate BungeeMessages

3. Player1 joins Server1, Player2 joins Server1.
   Player1 does: /cmi msg Player2 Hello friend!
   Player1 sees this output: [me -> Player2] Hello friend!
   Player2 receives this: [Player1 -> me] Hello friend!

3. Player2 moves to Server2
   Player1 does: /cmi msg Player2 Hello again friend!
   Player1 does not see any output message          <--- HERE'S THE ISSUE!!!
   Player2 receives this: [Player1 -> me] Hello again friend!

---
##################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
**config.yml**
  BungeeMessages: true
  BungeePublicMessages: false
  BungeeStaffMessages: true
  GeneralFormat: '%player_server%&f{displayName}&7: &r{message}'

**Locale_EN.yml**
    info:
      TargetMsg: '&7[&8[senderDisplayName] &7-> &8me&7]&r&f [message]'
      SenderMsg: '&7[&8me &7-> &8[playerDisplayName]&7]&r&f [message]'

```

---

**Cmi Version (using`/cmi version`):** 
CMIB 1.0.0.4
CMI: 8.6.26.7 BungeeCord  MySQL-> 8.6.26.8
Server: Paper(283) 1.15.2-R0.1-SNAPSHOT
CMI economy: False CMI Chat: True 
Modules -> 50 enabled 1 disabled: votifier

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
git-Paper-283 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by DaveDevil** [comment]
It seems it solved itself after a reboot of all servers and bungeecord

**Comment by DaveDevil** [comment]
After some days of tests, I can confirm the bug is still present

**Comment by Zrips** [comment]
Should be resolved with latest builds
