### ISSUE TITLE
/stopfire disabled after restart

### ISSUE THREAD

**Issue by Ahmadh26** [Zrips/CMI#3443]
**Description of issue:**
i have /stopfire enabled on my servers, whenever the server restarts it gets disabled and have to re-enable it,

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.6.26.7 BungeeCord SqLite-> 8.6.26.9
**Server Type (Spigot/Paperspigot/etc):** 
Server: Paper(284) 1.15.2-R0.1-SNAPSHOT
**Server Version (using `/ver`):** 
git-Paper-284 (MC: 1.15.2)

**Comment by CloudeLecaw** [comment]
Stop fire is no cmi command..

**Comment by Ahmadh26** [comment]
Ah damn, why did I think it was CMI. Sorry for wasting your time.
