### ISSUE TITLE
New line in ctext hover is broken

### ISSUE THREAD

**Issue by Dalethium** [Zrips/CMI#3446]
**Description of issue:** Using the ctext <H> feature, when you put a new line it both prints the new lines to hover, and breaks the hover text back into the <T> tag, see attached screenshot:

![SX-All-QHb9Xo4Hw3-1437](https://user-images.githubusercontent.com/22735418/83702999-253a3980-a5c3-11ea-8919-4edc376f59be.png)

**CONFIG SECTION**
```
<T>[2]</T><H>Enabled Craftbook features: \nVariables\nFootprints\nAI\nAmmeter\nBetterLeads\nBookcase\nBetterPlants\nJackOLantern\nJukebox\nMapChanger\nNetherrack\nPaintingSwitcher\nSnow</H><Next>

```

---

**Cmi Version (using`/cmi version`):** 
8.6.26.8
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-333 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Fixed
