### ISSUE TITLE
Attached Commands !cc! requiring ;; at the end

### ISSUE THREAD

**Issue by Kirrasio** [Zrips/CMI#3447]
In attached commands, it's now requiring ;; at the end of the !cc! for it to read commands. It says "There is no command by this name!" if you simply do !cc!command

---

03.06 23:13:29 [Server] INFO CMI plugin version: 8.6.26.0 BungeeCord -> 8.6.26.9
03.06 23:13:29 [Server] INFO Server version: Paper(283) 1.15.2-R0.1-SNAPSHOT
03.06 23:13:29 [Server] INFO Vault version: 1.7.3-b(CMIEInjector)

**Comment by Zrips** [comment]
Fixed
