### ISSUE TITLE
Migrating from sqlite to mysql not working properly

### ISSUE THREAD

**Issue by doitliketyler** [Zrips/CMI#345]
Description of issue or feature request:
I would like to switch from using sqlite to mysql but when I tried this with the /migratedatabase command on one of my servers it did not preserve the old sqlite data like the players economy balance or home locations. Am I missing a vital step here or is this a bug?

Cmi Version (using`/cmi version`): 7.7.2.0
Server Type (Spigot/Paperspigot/etc): Spigot
Server Version (using `/ver`): 1.12.2

**Comment by LogGits** [comment]
This issue should be resolved in the next update 🙂 Let us know if you still have issues.
