### ISSUE TITLE
BossBar Compass duplicating/stacking on screen

### ISSUE THREAD

**Issue by steven-archer** [Zrips/CMI#3451]
BossBar Compass duplicating/stacking on screen

Not sure how to reproduce issue (possibly after dying or relogging)

![image](https://user-images.githubusercontent.com/23382181/83748733-a380f500-a630-11ea-9050-4f77c3a2f080.png)
![image](https://user-images.githubusercontent.com/23382181/83748748-a8de3f80-a630-11ea-8b70-c49d9eefff89.png)

---

**Cmi Version (using`/cmi version`):** 
 CMI: 8.6.26.8
 SqLite-> 8.6.26.9
 (was also happening in previous versions too)

**Server Type (Spigot/Paperspigot/etc):** 
 Paper

**Server Version (using `/ver`):** 
 Paper version git-Paper-334 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
What update interval you have set for it?
