### ISSUE TITLE
/back Command Bug.

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#3455]
**Description of issue:**
When a user uses the command /back, they will **teleport to the second last location instead.**

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Nothing in config section that allows me to claim all.
```

---

**Cmi Version (using`/cmi version`):** 
8.6.26.9

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
git-Paper-322

**Comment by CloudeLecaw** [comment]
This is what back is for. For getting to lasr death point use dback

**Comment by BboyZeroOne** [comment]
Its not last death point, but last teleport point.

**Comment by CloudeLecaw** [comment]
Sorry.. i corrected my answer i tested both

**Comment by BboyZeroOne** [comment]
Okay, for example:
I'm at Point A now, then lets say I tpa/tp/warp/wild to somewhere else which is Point B. And then I proceed to teleport to another location Point C with the said commands but I plan to go back to Point B with /back, but instead it teleports me back to Point A.

**Comment by CloudeLecaw** [comment]
Ok this sound really Stränge. Your using a mysql database?

**Comment by BboyZeroOne** [comment]
"Your using a mysql database?"
sqlite

Actually even after 15 seconds, it stills teleport me to my second last location. Let me test this out in different case scenario.

**Comment by BboyZeroOne** [comment]
Apparently, I think this got to do with tp bypass permission in some cases where it says unsafe locations when there isn't actually. Thus tp-ing players to the second last location.

**Comment by Zrips** [comment]
Should be fixed with next update
