### ISSUE TITLE
Quests Requirement to rankups

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#3456]
**Description of feature/improvement request:**
Add support for the quests plugin by PikaMug, and add the ability to have quests as a rankup requirement.

---
### Detailed explanation of what it should do, when and in what situation: ###
When a player is trying to rank up, one of the requirements for the rankup is doing a quest. So the player has to do the quest before being able to rankup.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Would be useful to have if you wanted players to have to do a quest to rankup.

**Comment by CloudeLecaw** [comment]
You can setup requirements for rank up. For the quest thing i suggest a plugin like quests. There u can setup quests and use the rankup command as reward

**Comment by DrakePork** [comment]
This is about having the ability to have quests as a requirement for a rank up @CloudeLecaw, not adding a rankup command as a reward to the end of a quest. It also clearly states in the feckin message if you had bothered reading that "Add support for the quests plugin by PikaMug".

**Comment by CloudeLecaw** [comment]
ah so you want to design Quests in the quest plugin and the rank up requirment should ask if the quest is done right?
Does  "quests plugin by PikaMug" has an option to list or placeholder or a database or something where you can see that a quests is done?

Something like that would be needed because it would not so good if CMI would create a whole database for finished quests for each player...

**Comment by mrfloris** [comment]
If the plugin makes it possible to give the user a permission when they do not have a question, or are doing a question or have completed a question.. you could use permissionrequirement in cmi rankup to check against. Might be a cheaty way around for now.

**Comment by DrakePork** [comment]
@CloudeLecaw all quests a player completes gets saved in a file yes.

@mrfloris I did think about that yeah but would look a bit bad and be a bit confusing if it said you needed to get a permission not a quest

**Comment by CloudeLecaw** [comment]
in a file?
this is not so good. 
you need a output for a hook
like quest:questname:done   yes-no
better would be a permisison but i see the quests does not support this

May you can ask the Quests dev to create a command where you can get true/false outputs for asking for a quest

**Comment by DrakePork** [comment]
It does have placeholders for if a quest is completed.
