### ISSUE TITLE
Skin not removing

### ISSUE THREAD

**Issue by WarmasterCain55** [Zrips/CMI#346]
A player that I have used cmi skin on is unable to change it on the server in which i have skinned her. If she logs into another server after changing it on the MC site, it'll show the proper skin however she is stuck witht he skin she had after cmi skin off name her on the server that I did it on.  We tried resetting the skin via the MC site, tried uploading a new skin, same issue.  I am admin and I used it on a normal player.

I successfully replicated this on an alt of mine and I cannot get it to change on that server.
```

Cmi Version (using/cmi version): 7.7.20
Server Type (Spigot/Paperspigot/etc): Paper 1.12-r0.1 snapshot
Server Version (using /ver): 1.12

**Comment by CloudeLecaw** [comment]
normaly CMI sets the Skin each time.

Normaly it should work like this:
/cmi Skin NAME -> <your Skin on thsi Server will set to this Name (only on this Server and allways even if you Change your Skin)
/cmi Skin off NAME -> <your Skin you got from the Minecraftdatabase will be shown aggain on the server

**Comment by WarmasterCain55** [comment]
Doing /cmi skin playername off - fails quoting unable to find player
doing it in reverse results in a very fast glitch where it tries to change but reverts back

![ex 2](https://user-images.githubusercontent.com/20137850/39771953-7e370536-52b9-11e8-8dd4-6e1d5752135d.png)
![ex 1](https://user-images.githubusercontent.com/20137850/39771954-7e5bc592-52b9-11e8-96ae-bcdce37f95dd.png)

Here is the mcname of the player.  https://namemc.com/profile/Archfiend_Mercy.1

Here she is on another server.

![ex 3](https://user-images.githubusercontent.com/20137850/39772027-b2973184-52b9-11e8-9f42-36692ce66470.png)

**Comment by WarmasterCain55** [comment]
Here is a live demostration of what i am facing
https://www.youtube.com/watch?v=xozWudfXZgU

**Comment by CloudeLecaw** [comment]
i really see Nothing to fix... it works fine on my Server. if u want you are invited to my Server to test it ;)

**Comment by LogGits** [comment]
:o woops wrong tag. You are using the command incorrectly.

Use: `/cmi skin <skinUsername/off> <playerName>`

**Comment by WarmasterCain55** [comment]
Did you not see the video?  I Cannot Get the stupid skin off. According to the command, unless I am somehow doing it wrong. 

/cmi skin off - when doing it in the affected player, only results in the skin glitching before turning to the stuck skin. 

Doing /cmi skin off playername produces the same result. 

Doing /cmi skin playername off - produced a can’t find player. 

So please, enlighten me on the correct wording if this was not it.

**Comment by CloudeLecaw** [comment]
have you tried to also clear the Essentiasl skindata ?
would be a bit uncool if its the Essentials skin that is causing that

**Comment by WarmasterCain55** [comment]
we’ll try to look for it. Would you happen to know where it might be?

**Comment by WarmasterCain55** [comment]
I have good news. We cleared the skin cache and the problem skins has reset themselves.

**Comment by WarmasterCain55** [comment]
So here’s the deal 24 hours later,  Yes the skins reset however it will not actually change the skins despite our attempt.  My owner has been away all day so I haven’t had the chance to get his method yet.  Would there be anyway you can code in a purge command to undo any cmi actions toward a player?

Thought of the day:

“Until such time the world ends, I intend to live as though it intends to spin on.”

**Comment by WarmasterCain55** [comment]
SO I wanted to post with an update.  We installed the latest version with that skin adjustment but no progress has been made and I’m having trouble with the resetdbfields command as it seems to not like what I’m typing.

like i'm doing - /cmi resetdbfields Skin -w:2015-World -p:Archfiend_Mercy
also tried /cmi resetdbfields Skin -p:Archfiend_Mercy
doesn't work.

Thought of the day:

“Until such time the world ends, I intend to live as though it intends to spin on.”

**Comment by LogGits** [comment]
Oh my apologies, I didn't realise you tried the command correctly. It seems to update the skin but not to an accurate skin. Does that user have a custom nickname?

**Comment by WarmasterCain55** [comment]
Two of them did, I removed one and tested, same result.  1 didn’t and she is still having the same issue.

**Comment by Zrips** [comment]
This had to be fixed.
