### ISSUE TITLE
error in console. Shown on Scrin

### ISSUE THREAD

**Issue by Denias3** [Zrips/CMI#3460]
**Description of issue:**
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
error in console. Shown on Scrin


**Cmi Version (using`/cmi version`):** 
CMI 8.6.26.7

**Server Type (Spigot/Paperspigot/etc):** 
Paper 331

**Server Version (using `/ver`):** 
no
![image](https://user-images.githubusercontent.com/36571895/83917859-498f4500-a780-11ea-9081-4407b8c1b84e.png)

**Comment by mrfloris** [comment]
<img width="1301" alt="Screenshot 2020-06-06 at 03 02 51" src="https://user-images.githubusercontent.com/28841349/83932362-37be9980-a7a2-11ea-8dbc-7a93102ed00c.png">


use valid scoreboard prefix values to avoid errors like these, i guess. 

i think the whole scoreboard (nameplate + prefix etc, including color codes) have a techn limit by mojang studios set to 32 characters. 

"mrfloris" in `&4` red is therefore already 10 characters.
adding ddddddddd will just go beyond 32 chars.

**Comment by Denias3** [comment]
I understood. But shouldn't it be handled so that players cannot make such a mistake?

**Comment by Zrips** [comment]
Should be fixed with next version
