### ISSUE TITLE
ChatColor block

### ISSUE THREAD

**Issue by IcEeM** [Zrips/CMI#3461]
**Description of issue:**
I would like to block for all users to use chat color codes, i gave them cmi.colors.publicmessage.white + cmi.chatcolor.white but they can still use &5Hello and it displays "Hello" with the color. Is there anyway to block it? I have in chatmanager default color &f so I dont know where is the problem

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Colors:
    # If set to true then all public messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.publicmessage.[colorName]
    # Colors: black(&0), darkblue(&1), darkgreen(&2), darkaqua(&3), darkred(&4), darkpurple(&5), gold(&6), gray(&7), darkgray(&8), blue(&9), green(&a), aqua(&b), red(&c), lightpurple(&d), yellow(&e), white(&f), magic(&k), bold(&l), strikethrough(&m), underline(&n), italic(&o), reset(&r)
    PublicMessage: true
```

---

**Cmi Version (using`/cmi version`):** 
8.6.21.1

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.8.8

**Relevant plugins (Delete if this isn't needed):**
ChatManager

**Comment by mrfloris** [comment]
If you give a player the permission you're allowing them to use it.

negate the permission, (set to false in luckperms for example, or use a - (dash) right in front of it in groupmanager or some others) 

take the permission awayn, and they shouldn't be able to use it, unless they're perhaps operator or have a bypass permission.

**Comment by CloudeLecaw** [comment]
Also uye color use Negations of your chatmanager plugin

**Comment by IcEeM** [comment]
> Also uye color use Negations of your chatmanager plugin

I negated them - ChatManager.Formats.All + ChatManager.Colors but they can still write colored.



> If you give a player the permission you're allowing them to use it.
> 
> negate the permission, (set to false in luckperms for example, or use a - (dash) right in front of it in groupmanager or some others)
> 
> take the permission awayn, and they shouldn't be able to use it, unless they're perhaps operator or have a bypass permission.

Already negated them but they can still write colored

**Comment by CloudeLecaw** [comment]
what abvout the CMI colorcode permissions?

**Comment by IcEeM** [comment]
/lp group default permission set cmi.colors.* false - I made it but they can still type in chat colored and the cleanup + publicmessage is setted to true but nothing happened

**Comment by CloudeLecaw** [comment]
hm maybe chatmanager is not working correct anymore? the chatmanager is not supported anymore since a few years now.. but ok
I see your using Lucky Perms righr?
Then why dont use the power of it?
ake a Permission scanning and type some colored meassages then you see all permissions your server and plugins is asking for

**Comment by Zrips** [comment]
Will lower down chat listener to try intercept chat message before your chat plugin takes over, if this will not resolve your issue, then you might want to get into contact with developer of your chat plugin and ask feature like that from his plugin.
