### ISSUE TITLE
Damage Indicator Holograms not working properly

### ISSUE THREAD

**Issue by F3hliks** [Zrips/CMI#3465]
**Description of issue:**
The Damage Indicator Holograms are not being removed if the Entity dies from Suffocation, Drowns, dies from Fall-Damage or gets healed.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
No Error in Console
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
DEFAULT CONFIG!
Only TabList.yml changed. shouldn't make a difference
```

---

 ---------------------------------------------------------------------------
CMI: 8.6.26.9 BungeeCord  SqLite
Server: Tuinity 1.15.2-R0.1-SNAPSHOT
 CMI economy: True Vault: 1.7.3-b(CMIEInjector) CMI Chat: False
 Modules -> 50 enabled 1 disabled: votifier
 ----------------------------------------------------------------------------

**Server Version (using `/ver`):** 
This server is running Tuinity version git-Tuinity-"6f9ca4f" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
https://imgur.com/jQWIZ4j

**Comment by F3hliks** [comment]
![2020-06-06_16 32 21](https://user-images.githubusercontent.com/55054659/83946808-5f017f00-a813-11ea-8602-a42628ebe3a6.png)

**Comment by Zrips** [comment]
Damage indicators are not part of CMI. Check plugin responsible for this, maybe MCMMOItems or something like that.
