### ISSUE TITLE
Give Enchanted Book

### ISSUE THREAD

**Issue by DJDhuster** [Zrips/CMI#3468]
Hello, is it possible to give a player specific enchanted book with /give command? And if it is possbile how to do it?

**Comment by CloudeLecaw** [comment]
i just renmber the vanilla 1.13+ way

/minecraft:give Cloude_Lecaw enchanted_book{StoredEnchantments:[{id:feather_falling,lvl:4}]} 1

**Comment by mrfloris** [comment]
> Hello, is it possible to give a player specific enchanted book with /give command? And if it is possbile how to do it?

Yes, this is possible with /cmi give, 

vanilla
```
/give @s enchanted_book{StoredEnchantments:[{id:piercing,lvl:3},{id:blast_protection,lvl:3}]} 1
```

cmi give
```
/cmi give mrfloris enchanted_book {StoredEnchantments:[{id:piercing,lvl:3},{id:blast_protection,lvl:3}]}
```
cmi also has "e" as parameter:
```
/cmi give mrfloris enchanted_book e unbreaking:5
```
(gives unbreaking V book)

Just adjust accordingly. 


<img width="1382" alt="Screenshot 2020-06-09 at 15 27 17" src="https://user-images.githubusercontent.com/28841349/84153077-ba2ab000-aa65-11ea-968a-11bff0cf9ae3.png">
<img width="448" alt="Screenshot 2020-06-09 at 15 27 11" src="https://user-images.githubusercontent.com/28841349/84153091-bd25a080-aa65-11ea-891e-b57450489ee2.png">

**Comment by CloudeLecaw** [comment]
@ DJDhuster  if ithis works for you (and it should) pls dont forget to close this question-issue from you ;)

**Comment by Zrips** [comment]
Fixed
