### ISSUE TITLE
$2 is not seen

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3469]
tried to create a custom alias
that replaces the give command of vanilla for books so i could get individuall working enchantbooks with a short command.

`/minecraft:give Cloude_Lecaw enchanted_book{StoredEnchantments:[{id:sharpness,lvl:4}]} 1`

```
  genchant:
    Cmds:
    - minecraft:give Cloude_Lecaw enchanted_book{StoredEnchantments:[{id:$1,lvl:$2}]} $3
```
there is a problem the secound argument is not seen by CMi this is an issue. The third one is

then i tried: **/genchant sharpness 4 1**

![Snag_6e9c651](https://user-images.githubusercontent.com/12080017/83956396-e96ed080-a85d-11ea-8918-d7b30d73314a.png)
$1 - is palced as sharpness correct
$2 - is placed as $2 but it should be placed 4
$3 - is placed as 1 corret

**Comment by Zrips** [comment]
Good catch, will be fixed with next update
