### ISSUE TITLE
Permission to keep experience on death

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#347]
A cool feature that Essentials has that I think CMI should have.
People with the permission `cmi.keepxp` don't lose their experience on death.

Thanks

**Comment by CloudeLecaw** [comment]
this cool feature is in CMI since a Long time ;) with a permisison and setting
pls close this post :D

cmi.keepinventory - Allows to keep inventory after death
cmi.keepexp - Allows to keep exp after death
u see also Keep inventory is possible.
and now pls close it ;)
