### ISSUE TITLE
Customize power limit of the launch command

### ISSUE THREAD

**Issue by Phoetrix** [Zrips/CMI#3471]
**Description of feature/improvement request:**
Hi!

Is it possible to increase the power limit of the /cmi launch command?
This is 5 per default, I dunno why there is a limit but I really need more power.

Can you add a parameter in the config to edit the launch power limit?

Commands I use:
- /cmi launch p:5 Phoetrix (Works)
- /cmi launch p:6 Phoetrix (Not works)

**Comment by CloudeLecaw** [comment]
Define it in config maybe :) is there no Option for the maximum?

**Comment by Phoetrix** [comment]
I search for this option, I don't see anything for that.
I ask help in the "Zrips Plugins" Discord and some people say me the same, they don't see any parameter for this. :/

**Comment by CloudeLecaw** [comment]
:/

**Comment by Zrips** [comment]
@Phoetrix 
Minecraft has set max velocity limits so we cant use big numbers here. Your best solution would be to make custom alias and perform 2 commands of launch with small delay. There is no way to increase velocity of the player at this point.
