### ISSUE TITLE
Tablist AutoInterval (Update time)

### ISSUE THREAD

**Issue by MaxWainer** [Zrips/CMI#3475]
_### Description of feature/improvement request:_
Milliseconds in update interval must remove problem with animations in tablist. Now animations are can be too fast (0) or too slow (1-n s.) and looks like bad. This little feature can solve this problem.
---
_### Detailed explanation of what it should do, when and in what situation: ###_
**It can be used in: 
1.** Sometimes, when you want to add animation to nick interval 0 is too fast and 1 is too slow.
If you add milliseconds in "AutoInterval", Like:
AutoInterval:
 Seconds: 0
 MSeconds: 7
Or AutoInterval: 0.7
**It shoud do:
1.** It could add more possibilities in tablist update and do animations cooler
### Basic explanation as to why this feature is needed and/or useful to have: ###
To create smoothly animations

P.S Sorry for my english. I am from Russia...
 If someone have question how I add animations to tab and nickname: PlaceholderAPI-JS-Expansion and guide from wiki.

**Comment by CloudeLecaw** [comment]
you have a tablist update intervall allready

**Comment by MaxWainer** [comment]
> you have a tablist update intervall allready
> 
> adding millisecounds is no good idea, secounds is enough if you want a stable preformance
> as bigger the amount of secounds, as better your server preformance.
> the current tablist of CMI is not for animated tabs!
> 
> why you thought CMI supports animations in tab? maybe your using a animated tablist plugin?

To animate prefixes and suffixes in tablist I use CMI and PAPI-JS. I can drop animation.js placeholder and little video how it looks like with 1 second and 0 seconds.

**Comment by CloudeLecaw** [comment]
hm im no friend of javascript placeholder this is mostly to buggy

i prefer using the cmi default once that have a big array allready.
why you need a blinky blinky tablist? ^,^
nothing for bigger servers, just a tps killer

**Comment by MaxWainer** [comment]
To animate header and footer, I use Tab plugin (MVDW). 

[2020-06-08 16-39-34.zip](https://github.com/Zrips/CMI/files/4746279/2020-06-08.16-39-34.zip)
JS script:
![image](https://user-images.githubusercontent.com/53620097/84037328-1975bb00-a9a7-11ea-9100-3700ecef5cbf.png)


0:00-0:06 (0 secnods) / 0:08-0:37 (1 second)

**Comment by MaxWainer** [comment]
> hm im no friend of javascript placeholder this is mostly to buggy
> 
> i prefer using the cmi default once that have a big array allready.
> why you need a blinky blinky tablist? ^,^
> nothing for bigger servers, just a tps killer

Sometimes it looks like cool. Heavy load, not a problem. :d

**Comment by MaxWainer** [comment]
Adding ticks or ms in AutoInterval can kill problem with this. Bigger servers can disable this function by setting it to total number (1.5 - 1)

**Comment by CloudeLecaw** [comment]
everything in cmi is is defined in Seocunds
also the MINIMUM time is a tick and this is 50 millisecounds

**Comment by MaxWainer** [comment]
Okay, if it possible. Can Zrips add ticks on update interval? And 1 more question. «but maybe ZrIps can add the decimal number after the point so it will be compatible with current format.
so numbers like 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9 are accepted too» is 0.1-0.9 are on the list?

**Comment by Zrips** [comment]
@MaxWainer 
Issue with tablist in general is that we dont know when its been opened or closed. Which means that tablist information is update constantly even if you never look at it. So lets imagine 100 players online, 0.1 update rate with multiple placeholders. What we have is 1000 packets sent every single second while at same time sending 1000 requests to update placeholders. 
1 second interval was intentional to avoid possible issues with performance impact. Even 1 second is more than enough and should be lowered down. 
Blame Mojang for not creating appropriate packet when players open tablist.
