### ISSUE TITLE
Issue with %cmi_equationint_...% with lastest CMI version

### ISSUE THREAD

**Issue by fhebuterne** [Zrips/CMI#3476]
**Description of issue:**

Hello,

We have a critical issue with %cmi_equationint_...%, it doensn't work with CMI latest version.
We using to increment claims for players with PlayTimeRewards.
Maybe It cause an error in console (I'm not sure there is a link) , please check pastebin link.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/Q54ysK1G
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```

You could test with luckperms with lands, and using this in PlayTimeRewards in command section ;

asConsole! lp user [playername] permission set lands.chunks.%cmi_equationint_{cmi_user_maxperm_lands.chunks_10}+10% true

Config file : https://pastebin.com/CbTwKiTQ

It work perfectly before update.
Now, it perform set without any number to permissions.

```

---

**Cmi Version (using`/cmi version`):** We updated from 8.6.24.1 to 8.6.26.9

**Server Type (Spigot/Paperspigot/etc):** Paper 1.15.2 (latest)

**Server Version (using `/ver`):** Build 339 from Paper 1.15.2

**Comment by Zrips** [comment]
Will be fixed with next update
