### ISSUE TITLE
Delete nether/end and teleport to a home will kill you

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#3477]
**Description of issue:**

If you delete the nether/end and players will teleport to their homes set in those worlds, they will die in lava instead of the teleport being cancelled due to it being unsafe.

**Comment by CloudeLecaw** [comment]
why u have not teleported all players (also offline players out of the world before?

**Comment by Sikatsu** [comment]
I wasn't aware of such a command, but that's nice to know. But what I meant is, there is something wrong with the ''unsafe teleportation'' check, because it should however cancel a teleport to a place where there is lava direct under it. I didn't mean ''get teleported out by itself''

**Comment by CloudeLecaw** [comment]
i know there is something wrong with the ''unsafe teleportation'

very often when players on our server do /spawn it tels them the teleport is not save, so they need to do it a secound time. it does not happen every time. and when it does they mostly do not stand on a step or carpet or in water or... they stand on normal blocks.
