### ISSUE TITLE
Option for players to keep hunger after death

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#348]
Add an option that makes players keep their current hunger level even after they die, similarly to how HungerKeeperPlus does it.
https://www.spigotmc.org/resources/hungerkeeperplus.23589/

Thanks

**Comment by valenvaio** [comment]
So that the player does not die for the sake of restoring hunger. Good function.

**Comment by TheWranger** [comment]
Will be really useful on SkyBlock type servers.

**Comment by MCTyler** [comment]
@ScuroK Pot calling the kettle Black?

**Comment by valenvaio** [comment]
It is inconvenient to use whois. Moreover, in the case of entering information about the city, the moderator may not be available information about the ip player. What is more important for privacy, if you are so worried about it. But there are social networks, dynamic ip, proxy, VPN. And for a long time already there is no your privacy.

If the plugin is positioned as a replacement for essentials why not expand the functionality? He already displays the country, can you add the field to the city? And make this setting customizable and bound to permission.

**Comment by CloudeLecaw** [comment]
for SkyBlocktype Server...so what u want? not getting hungry or not loosing hunger?
So when hunger is full it will lallaways be full?...as far as i know many Protectionplugins have a function like this ist mostly a flag like canhunger.
Redprotect and Worldguard for example can this

**Comment by Zrips** [comment]
Next update will have this feature.
