### ISSUE TITLE
Version command

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3481]
**Description of issue:**
When I use version and some plugin, it doesn't work.... Look at the picture: https://media.discordapp.net/attachments/719922009848676393/719928625549410344/unknown.png

---

---

**Cmi Version (using`/cmi version`):** CMI: 8.6.26.10 BungeeCord MySQL-> 8.6.26.9 

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**   This server is running Paper version git-Paper-342 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by CloudeLecaw** [comment]
Have you actived /Version for cmi innthe alias cmd.?

**Comment by Volgeop** [comment]
Yeah it's activated... and when I use it on server without CMI it normally works... but with CMI it still spam what the command do.

**Comment by mrfloris** [comment]
Paper and Spigot both use: `ver pluginName`, and cmi might use `version`, but it's output is from `cmi version`
```
# /cmi version $1-
  /version: true
```
Set this to false. Start the server up.

**Comment by Volgeop** [comment]
Yeah, works then... but shouldn't /cmi version PluginName (and alias /version) work too?

**Comment by Zrips** [comment]
@Volgeop 
Command usage is **/cmi version** and nothing more, this will output information about CMI version and some extra details which helps out in debugging. If you want to get versions of other plugins you can use /version [pluginName] command.

**Comment by Volgeop** [comment]
Yeah but than should be alias disabled by disabled by default
