### ISSUE TITLE
cmi Note command has no Tabcomplet and added notes get dupplicated each relog

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3485]
the CMI note command has no tab complete or it is broken.
So be usefull for staff and co this would be a needed extra.

**cmi note (playerName) [add/remove/clear/list] (id/note)**
![Snag_339da17](https://user-images.githubusercontent.com/12080017/84324975-09fa9b80-ab7a-11ea-962d-26ed575ee534.png)

CMI version: CMI_8.6.26.11
PaperSpigot 1.15.2 Build 339
.
.
.

Next bug:
When you add a entry and the player logs off then the entry got doubled each time..
![Snag_33cf689](https://user-images.githubusercontent.com/12080017/84325186-83928980-ab7a-11ea-88c5-690840dd2622.png)
1, i added a note /cmi note Cloude_Lecaw add player Swears

![Snag_33dfcfd](https://user-images.githubusercontent.com/12080017/84325267-ab81ed00-ab7a-11ea-94ed-8f4bb284719d.png)
2. i checked with /cmi note Cloude_Lecaw

3. i log off
4, i relog and check aggain with /cmi note Cloude_Lecaw
![Snag_33f4730](https://user-images.githubusercontent.com/12080017/84325360-dec47c00-ab7a-11ea-8547-804944314759.png)

5. i relog and check aggain with /cmi note Cloude_Lecaw
![Snag_340959a](https://user-images.githubusercontent.com/12080017/84325461-116e7480-ab7b-11ea-895b-f53364ffd1e8.png)

6. etc,, next time it will be 8 entries... and so on

i checked aggain it has nothing to do with the check after relog
it does this every login...

The error seems to be come from MySQL database,
could you check if this is a bug or may database is just currpted? :3
before someone asks...no no errrors in the log or console about this :3

**Comment by Zrips** [comment]
Will be fixed with next version
