### ISSUE TITLE
Variables for commands

### ISSUE THREAD

**Issue by ghost** [Zrips/CMI#3487]
**Description of feature/improvement request:**

I propose adding the @a, @e, @p, @r, @s variables to all CMI commands for player and entity.
Also if you can add the variables for them. Example: @a [distance = .. 5]; @e [type = minecraft: zombie]; @r [gamemode =! creative]; etc ...

---

**Comment by CloudeLecaw** [comment]
so where you suggest thus command where a Argument like this does not allready exists? For command blocks these variables u wrote allready work if that is waht you want

**Comment by Zrips** [comment]
@Goddesu 
Those special variables require origin location, which in general can only be used from command block. But even then, command blocks already uses their own player detection by special variables you can add into it. CMI supports some what @p and @r variables when performing command from command block.
