### ISSUE TITLE
Lore Support and Smooth Custom Items Search

### ISSUE THREAD

**Issue by slipstricker** [Zrips/CMI#3490]
Create a comand named /recipe gui so players can see all crafts that the server created (not vanila ones), the player will have a permission cmi.command.recipegui and will be able to see all custom crafts. Also add support to lore items
---
This is necessary bcs it will help the player that wants to see the custom crafts without knowing the name and will see only the custom ones, not vanila, also lore will give more options to edit items. I believe it will be a nice feature if added.

**Comment by CloudeLecaw** [comment]
We allready have a custom ceripe editor /cmi customrecipe.
This editor could need a permission like cmi.command.customrecipe.list

With this permission a chatgui should pop up where players can see all recipes

The customrecipe editor may could get a new argument /cmi customrecipe list
If entering then players see the gui with all custom recipes.

It would be the ownetw job then to create a custom alias that is executing /cmi customrecipe list like /recipe if that is Wanted

I see so reason for created a whole new command to this.

**Comment by slipstricker** [comment]
the /cmi customrecipe list
command does not work

**Comment by OverBrave** [comment]
This feature should definitely be.
