### ISSUE TITLE
[¿BUG?] "cmi.keepexp" permission doesn't work

### ISSUE THREAD

**Issue by Deathroner** [Zrips/CMI#3491]
**Description of issue:**

This permission I plan to leave it to the VIP ranges, but at the time of applying and testing it, it does not work.

I checked if inventory is maintained, but experience restarts after dying.

What can I do to avoid this?

**Cmi Version (using`/cmi version`):**  8.6.26.10

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.15.2

**Relevant plugins (Delete if this isn't needed):** LuckPerms

**Comment by CloudeLecaw** [comment]
jep cmi.keepexp does not work but when you have cmi.keepinventory  then it saved exp and inv on death. 

i reported this issues a longer time ago seems noone was interested in until today

**Comment by Zrips** [comment]
@Deathroner 
Make sure that you have specifically set permission nodes, as simply being OP will not help out or having wild card permission node. You can check that with **/cmi haspermission Zhax cmi.keepexp** which should output something like "Hard set to true by some plugin"
Tested on latest paperspigot 1.15.2 version, all works as intended. Try testing this feature with CMI and luckperms alone to make sure there is no interference from another plugin.
