### ISSUE TITLE
'Itemfilter' for CMI

### ISSUE THREAD

**Issue by VimaMT** [Zrips/CMI#3493]
**Description of issue or feature request: Add /itemfilter GUI to CMI**

Several months ago one of the servers I played on had an /itemfilter command which brought up a GUI in which players could drop items that they did not want to pick up while they dropped them from mining, digging, or cutting. They would just leave those items on the ground behind them.  Please consider such a feature for CMI.

**Comment by CloudeLecaw** [comment]
you mean a itempickup filter. So when they put in Cobble they dont picup cobble right?

Nice idea, it would be nice if you could make some idea how todesign this:)

**Comment by VimaMT** [comment]
I think you have a good grasp of what I am looking for. I was not thinking of anything world-specific, but I would not object.  😀
