### ISSUE TITLE
Towny Advanced issues

### ISSUE THREAD

**Issue by NightPrimez** [Zrips/CMI#3494]
**Description of issue:**
in now, money wasn't lost when im dying but it's displaying im lost money
so i need to make money is lost when dying
https://media.discordapp.net/attachments/581163022874050569/720917776944070706/unknown.png

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Economy:
  # Enable or disable CMI economy in general
  # In case CMIInjector is present, then this will be set to true automatically.
  Enabled: true
```

---

**Cmi Version (using`/cmi version`):** 
8.6.26.11

**Server Type (Spigot/Paperspigot/etc):** 
SSSpigot (paper fork)

**Server Version (using `/ver`):** 
1.15.2

**Relevant plugins (Delete if this isn't needed):**
- Towny Advanced
- Vault 1.7.3

**Comment by Zrips** [comment]
Tested out, seams to be working correctly for me. Check if you have recompiled Vault version or Injector from plugins page for economy to work fully with other plugins. Other than this post output from /cmi version and what it shows on server startup for Towny plugin which should include which economy it recognized. Will close ticket for now, but you can still respond to this one if issue still persists.
