### ISSUE TITLE
cmi give enchantmentbook command not working when using customalias?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3496]
i created a customalias called: genchantment
```
  genchant:
    Cmds:
    - cmi give $1 enchanted_book {StoredEnchantments:[{id:$2,lvl:$3}]} $4
```

the command i tried to use was /genchat Cloude_Lecaw sharpness 3 2

This means:

$1 - Cloude_Lecaw <- Playername
$2 -  sharpness <- enchant
$3 - 3 <- level
$4 - 2 <- amount

result...
![Snag_14577e2](https://user-images.githubusercontent.com/12080017/84570474-050e3580-ad8e-11ea-88ae-44393f9d19f3.png)

i get one enchant book without any enchants on it and also just 1...
What have i dont wrong?

The match this i tried a secounds one
```
  genchantvan:
    Cmds:
    - minecraft:give $1 enchanted_book{StoredEnchantments:[{id:$2,lvl:$3}]} $4
```

using enchantvan Cloude_Lecaw sharpness 3 2
![Snag_147df5d](https://user-images.githubusercontent.com/12080017/84570528-633b1880-ad8e-11ea-9f69-2a20f448f81d.png)
the vanilla version works fine (also got 2 books) so the problem is not the $-placeholders....

Well maybe its because its just a customalias but the when using the CMI version of the custom alias i hoped it will also take over the real tabcomplet of the places so i can TAB the enchants to the desired one, but it does not. maybe because its the give commands... but ok..

have i done something wrong with the useage of the CMIs give comands or is this an issue?
It i used the command wrongly pls tell me and i can close this issue :)

**Comment by Zrips** [comment]
In general you can fix that by simply moving quantity before tag, so like 
cmi give $1 enchanted_book $4 {StoredEnchantments:[{id:$2,lvl:$3}]}
But will make it work both ways with next version
