### ISSUE TITLE
Falling through blocks on teleportation

### ISSUE THREAD

**Issue by Gymblonski** [Zrips/CMI#3497]
**Description of issue:**
So from when i started the server people started getting this issue when on teleportation 
they get spawned in the middle of block, or fully through it and die.
This is really hard to test because it happens to 20-30% of the people
and also doesn't happen every teleportation, its totally random. Making it
even hard to start testing what is causing it. Looks like it starts happening more
on higher player count but I cant be  sure for that since it was happening on lower than 
10players.
What I have done is changed few .jars and the issue is still happening.
TPS is always 20, 

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.6.23.6 BungeeCord -> 8.6.26.11
**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 
PaperSpigot 1.8.8-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Should be resolved now.
