### ISSUE TITLE
cmi maxhp -s flag not working when executed from console

### ISSUE THREAD

**Issue by xRebellion** [Zrips/CMI#3498]
**Description of issue:**
Using /cmi maxhp with -s flag does not work on console (it shows the usage message instead). 
Using it from a player's perspective works okay, though.
![image](https://user-images.githubusercontent.com/32483348/84575273-1d09a780-add6-11ea-9d29-67d2561e284b.png)

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**
![image](https://user-images.githubusercontent.com/32483348/84575249-f0559000-add5-11ea-9701-8a1164ae2d53.png)

**Comment by Zrips** [comment]
Will be fixed with next update
