### ISSUE TITLE
Players can use /rtp while cuffed

### ISSUE THREAD

**Issue by hotspuraz** [Zrips/CMI#3499]
Players are able to use /rtp to escape staff while cuffed. I believe floris tested and confirmed this is an issue.

---

**CONFIG SECTION:**

Cuff:
  Mute: true
  AllowedCommands:
  - msg
  - r
  - helpop
  - cmi msg
  - cmi reply

---

**Cmi Version:** 8.6.27.0

**Server Type:** Paper-350

**Server Version:** 1.15.2

**Relevant plugins:** WildTP

**Comment by Zrips** [comment]
This should be fixed as of 8.6.27.0 version. Will add some one more small change to minimize change in some plugins not taking into consideration if even is canceled. Other than this, it could be that WildTP listens for command event at a lowest level which means that i cant really prevent this plugin from performing command if its processing it before CMI is even notified about performed command.

**Comment by hotspuraz** [comment]
Unfortunately, it hasn't fixed the issue. I will look for an alternative method of random teleporting to see if it is just the plugin. Thanks
