### ISSUE TITLE
Portals do not recognize worlds

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#3500]
**Description of issue:**
When players use portals to another world, the commands will not be executed before leaving the world. I have tried this with several different worlds but always the same. Also noticed that if I use a portal to another world and created a new portal in that same world, then the portal was created on the same coordinates but in the previous world I came from.

I use Multiverse when setting up multiple worlds.

---

**Cmi Version (using`/cmi version`):** 8.6.27.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 350 (1.15.2)

**Comment by CloudeLecaw** [comment]
how you create portals by the way?

normaly you create a portal frame and set a target frame with the seltions tool

Then you have a two way portal between start and target

it does not matter where this targt is but if u dirfed it it means u was there allready.

on out server all portals to the farmwels, nether, end, evemworlds , etc work like that - port to other worlds and this without any issues

mi Version (using/cmi version): 8.6.27.0

Server Type (Spigot/Paperspigot/etc): Paper

Server Version (using /ver): 350 (1.15.2)

**Comment by Baktus79** [comment]
Yes, I know how to create a portal :)

**Comment by CloudeLecaw** [comment]
but u wrote there is problem when the player pass it when the target is in an other world? 🥉 

i saw no issues there if the player has the permission

**Comment by Baktus79** [comment]
I have registered this as an error because it does not work as intended.

**Comment by Baktus79** [comment]
It's probably hard to explain what's really going on. I'll make a video later today showing what I'm talking about.

**Comment by Baktus79** [comment]
[Click here for video](https://youtu.be/6_wD2z2tkKs)

**Comment by CloudeLecaw** [comment]
wow stange behavior

i tried the same creating two portals one to worldA target worldB
and one from worldB target to worldA

there was no problem with it.
Have you tried to make sure no other plugin is interrupting?

i would tried the same on testserver on your local PC
just with your permission system plugin + Multiverse + CMI  - and see if this also reapears

**Comment by Baktus79** [comment]
I haven't debugged it correctly yet, but yes I find it disturbing too.

**Comment by Zrips** [comment]
Will be fixed with next build
