### ISSUE TITLE
FieldAccessException Console Spam

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#3502]
**Description of issue:**
This Error Spawns permanantly in Console

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**

[14:55:17] [Craft Scheduler Thread - 33/WARN] []: FieldAccessException: No field with type java.util.List exists in class PacketPlayOutWorldParticles.
--
2 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216)
3 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195)
4 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.lishid.orebfuscator.hook.ProtocolLibHandler$1.onPacketSending(ProtocolLibHandler.java:123)
5 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
6 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
7 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
8 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
9 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334)
10 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296)
11 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378)
12 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
13 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343)
14 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313)
15 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
16 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
17 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:198)
18 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:149)
19 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1336)
20 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(NetworkDispatcher.java:214)
21 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.Zrips.CMI.NBT.v1_12_R1.playEffect(v1_12_R1.java:1715)
22 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.Zrips.CMI.Modules.Portals.PortalManager.showParticlesForPortal(PortalManager.java:169)
23 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.Zrips.CMI.Modules.Portals.PortalManager.access$3(PortalManager.java:101)
24 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at com.Zrips.CMI.Modules.Portals.PortalManager$1$1.run(PortalManager.java:93)
25 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
26 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
27 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
28 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
29 | [14:55:17] [Craft Scheduler Thread - 33/WARN] []: at java.lang.Thread.run(Unknown Source)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):**  8.6.27.0

**Server Type (Spigot/Paperspigot/etc):** Catserver 

**Server Version (using `/ver`):** 1.12.2

**Comment by CloudeLecaw** [comment]
This looks luke an error of incompatible protocollib. Have you tried also posted there and searched for latest Versionen suitable to your server version?

**Comment by blakedj012** [comment]
Yes i have the latest Version from Spigot installed.

**Comment by CloudeLecaw** [comment]
and what version of Protocollib?

**Comment by blakedj012** [comment]
https://ci.dmulloy2.net/job/ProtocolLib/

The latest Dev Build. With ProtocolLib 4.5.1 is the same.

**Comment by CloudeLecaw** [comment]
But u ha e the latest Version for 1.12.2? The ltest dev version are for 1.13+...

**Comment by blakedj012** [comment]
The last version on Spigot is also from the 1.8 - 1.15 and it has the same bug. I think the dev version is also from the 1.8 - 1.15 

He writes it on the spigot page that you should use this version for 1.12.2.

**Comment by Zrips** [comment]
Issue is with using CatServer which is not officially supported platform which by itself has completely different classes and methods for some of the stuff which breaks entirely. There was similar report at protocolib with same exact issue. Will have a look, but cant promise anything.

**Comment by blakedj012** [comment]
No the error is gone. I use now Protocollib 4.3.0 and all works. Thank you
