### ISSUE TITLE
Warmup glitch

### ISSUE THREAD

**Issue by abhisantos** [Zrips/CMI#3504]
**Description of issue:**
When players do commands that use warmup, for example /tpa, /warp, etc, after they are teleport their chat keeps forever spamming ''you were teleported..'' 
The only solution for now was to disable all warmups and restart the server.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 

CMI8.6.26.9

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.8.8

**Comment by Zrips** [comment]
I need more information on this one. Can you provide locale file responsible for the messages you are receiving and what you have had setup for warmups? Or atleast point out which exact locale line was repeating.

**Comment by abhisantos** [comment]
The message is ''you teleported to''
Also abou tpa, after you the player accepts your request and you teleport,
you get stuck and can't walk and particles keep showing, like in the image
http://prntscr.com/t1n8jt

Em ter., 16 de jun. de 2020 às 08:21, Zrips <notifications@github.com>
escreveu:

**Comment by Zrips** [comment]
Doesn't really provide much of a information about this issue. Could you provide warmup section from config file?
