### ISSUE TITLE
New Version of CMI is Losing it's Warps from Old Config - Crashes server

### ISSUE THREAD

**Issue by VimaMT** [Zrips/CMI#3505]
**Description of issue or feature request:**

```
 I upgraded from version 8.6.26.11 to version 8.6.27.0 of CMI. If I reset one of my worlds using World Reset Plus the pre-existing warp to that world gets messed up. I time out and the server goes down. If I replace the old version of CMI and restore the world again, it works alright.

---

**Cmi Version (using`/cmi version`): 8.6.27.0** 

**Server Type (Spigot/Paperspigot/etc):Paperspigot** 

**Server Version (using `/ver`):git-Paper-334 (MC: 1.15.2)** 

**Relevant plugins (Delete if this isn't needed): WorldResetPlus 1.0.7**

**Comment by VimaMT** [comment]
Oh joy!  This is another one of those where multiple plugins have to be working together to cause my issue. I stuck the relevant modules onto a test server, and I had no such issues.  I will research this one more and try to provide more useful details.

**Comment by VimaMT** [comment]
Ok ... able to duplicate it on the test server, but unless someone else has the same issue I am not going to push this one. It is always a fun time trying to figure out which of about 50 plugins work together to cause the issue.  I was able to fix it by deleting the warps and recreating them.  I'll leave this open long enough for someone to read it and close it.  :-)

**Comment by VimaMT** [comment]
I am also having to remove my homes and recreate them.

**Comment by VimaMT** [comment]
Going back to old version, and I'll get out of this thread.

**Comment by Zrips** [comment]
Will make some slight changes related to this. But some extra information could have been nice, like crash report or example of warps file or anything what could help out in determining what actually went side ways. In any case, you can test next version or send some extra information over discord pm.
