### ISSUE TITLE
[Suggestion] The ability to ban usernames/uuid before they've ever joined. 

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3506]
```
>cmi ban userA Malicious behavior is not welcome
>cmi ban userB Malicious behavior is not welcome
>cmi ban userC Malicious behavior is not welcome
>cmi ban userD Malicious behavior is not welcome
>cmi ban userE Malicious behavior is not welcome
>cmi ban userF Malicious behavior is not welcome
>cmi ban userB Malicious behavior is not welcome
 Can't find player with this name!
 Can't find player with this name!
 Can't find player with this name!
 Can't find player with this name!
 Can't find player with this name!
 Can't find player with this name!
 Can't find player with this name!
```

I understand they're not in the database, but there's a `banned-users.json` file that Spigot/Paper checks which should be updated. 

We currently use our own tool to make sure the users we wish to block before they've even join, but it would be a lot easier and handy for bungee servers as well, if cmi can set the ban.

**Comment by Zrips** [comment]
Next update, atleast for ban command, temp ban is still dependent on user being real.

**Comment by mrfloris** [comment]
I only need it for perm bans, this is great. Thank you <3
