### ISSUE TITLE
EXP and Money Charge For Custom Recipes

### ISSUE THREAD

**Issue by MCTyler** [Zrips/CMI#351]
Description of issue or feature request:
```
I would like to use Custom Recipes for Creating Spawners but I need to 
be able to Charge Exp and Money for crafting the Recipe so it will be 
"less OP". 
I have made this request before but it seemed to be buried in requests. Please re-review. 
Also, The ability to add custom fuel to furnace recipe would also be a nice addition!
``` 
Thanks for your consideration!
#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR (IGNORE IF YOU HAVE NO ERROR):
```
####################
## PASTE ERROR HERE ##
####################
```

CONFIG SECTION (IGNORE IF NOT RELEVANT):
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```
[15:19:09 INFO]: CMI plugin version: 7.7.2.0-> 7.7.3.0
[15:19:09 INFO]: Server version: Spigot 1.12.2-R0.1-SNAPSHOT
[15:19:09 INFO]: Vault version: 1.6.10(+)

**Comment by CloudeLecaw** [comment]
hm may this is not Right request here, but sonds for good for me to announce it.


in Addition to MCTylers request, i want the Option to be able to use modified materials for the custom recipes :) (crafting mats with: itemlore, itemname, Attributes, etc)

**Comment by MCTyler** [comment]
Gonna close/reopen this, Been too long since request.
