### ISSUE TITLE
CMI x Tuinity Bug

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#3511]
**Description of issue:**
"Internal error has occurred" when using latest version of CMI 8.6.27.0 on latest version of Tuinity git-Tuinity-"7c03cbe". 

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/X1Qtnuwc
https://pastebin.com/yZbdkFTf
https://pastebin.com/zdX8ENPb
``

---

**Cmi Version (using`/cmi version`):** 
CMI 8.6.27.0

**Server Type (Spigot/Paperspigot/etc):** 
1.15.2 Tuinity

**Server Version (using `/ver`):** 
git-Tuinity-"7c03cbe

**Relevant plugins (Delete if this isn't needed):**
None

**Comment by BboyZeroOne** [comment]
Also happened on Paper
https://pastebin.com/PJfPF8Qk

**Comment by CloudeLecaw** [comment]
Is this a fork of paperspigot? Im. Not sure if Zrips wanne take a look into this if your using a server away from the official once (paperspigot, spigot, bukkit)

**Comment by Zrips** [comment]
@BboyZeroOne 
Issues originates from sqlite drivers you have on your host server. You will ether gonna need to update those or even downgrade which doesn't have this bug or switch to mysql database type system for CMI. I cant really fix this one from my end.

**Comment by BboyZeroOne** [comment]
Any idea what this means? 
'[SQLITE_ERROR] SQL error or missing database (no such table: dual)'

https://pastebin.com/DcaruqSn

**Comment by BboyZeroOne** [comment]
> @BboyZeroOne
> Issues originates from sqlite drivers you have on your host server. You will ether gonna need to update those or even downgrade which doesn't have this bug or switch to mysql database type system for CMI. I cant really fix this one from my end.

Any idea what this means?
'[SQLITE_ERROR] SQL error or missing database (no such table: dual)'

https://pastebin.com/DcaruqSn

**Comment by BboyZeroOne** [comment]
When I tried using /cmi migratedabase, this happened.

https://pastebin.com/GcfXp3q2

**Comment by BboyZeroOne** [comment]
I believe /cmi migratedatabase somehow deleted all my users data from sqlite...

**Comment by CloudeLecaw** [comment]
Well this is normal because they should be converted to your mysql now after the Migration.

**Comment by BboyZeroOne** [comment]
What is normal? The user data got deleted or the missing database (no such table: dual)' @CloudeLecaw

**Comment by CloudeLecaw** [comment]
Nono, its not normal that the database got lost from mysqllite. Normaly when you enabled mysql then the sqlite file is no longer readed by cmi. Only if you change back. However the current contant of the old data should not be deleted by itself. But sometime wrong driver or stange connections can create crazy errors. That is why each effected database should be backuped before trying a Migration

**Comment by BboyZeroOne** [comment]
Seems like the migration isn't working properly as it should, as it did not transfer player data but instead deleted all user data from sqlite.

**Comment by CloudeLecaw** [comment]
Have your tried this aggain with an other mysqlite database? There are a big bunch of free to use sqlsites that offer ppls mysql sites for testing.

**Comment by BboyZeroOne** [comment]
Yes, apparently all sqlite were affected. Here

https://imgur.com/a/BD7ERx9

**Comment by BboyZeroOne** [comment]
I checked mysql database and no user data were transferred either

**Comment by BboyZeroOne** [comment]
I believe this got to do with /migratedate, can you please take a look again at it just in case @Zrips

**Comment by CloudeLecaw** [comment]
So this means the mysql database failed to create the tables?

**Comment by BboyZeroOne** [comment]
Not too sure, but either way user data was cleared from the process.

**Comment by BboyZeroOne** [comment]
No, I have not tried any other test site before migration

**Comment by BboyZeroOne** [comment]
Currently facing exact same issue with this ticket #2630 @Zrips

**Comment by BboyZeroOne** [comment]
Can someone open this ticket? Since this issue isn't actually fixed.
