### ISSUE TITLE
Wireless Redstone

### ISSUE THREAD

**Issue by ablac** [Zrips/CMI#3512]
I would love to see the ability to make wireless redstone in CMI. There used to be an amazing plugin called Wireless Redstone but its no longer being made, and I loved that plugin.

Super simple create a sign.
Create a Transmitter
1.  [WRT]
2. Number (This is the channel)

Create a Receiver sign
1. [WRR]
2. Number (Channel number to listen to)

I believe this would be a great addition to CMI, and would make people that do lots of redstone work over large builds much easier!

**Comment by CloudeLecaw** [comment]
Well this is exact what the plugin wireless rrstone does

**Comment by ablac** [comment]
I highly doubt he would implement it without permissions FYI, but I’m not saying to implement it as a garbage dump, I I just used wireless Redstone as an example. Because there’s Literally only one wireless Redstone plugin that’s still getting updated, and it’s terrible, yet it has tens of thousands of downloads. I know Zrips can do it right.

The other thing with wireless Redstone is if your going long distance there’s Thousands of Block updates just in a 3 block Redstone wire. Using wireless redstone reduces those massive amounts of block updates.

And if not signs then maybe attach it to levels, buttons, pressure plates and just toggle them wirelessly. There’s tons of ways to implement it.

**Comment by CloudeLecaw** [comment]
Hm if i use a redstone wire then uts over after sime blocks bcause the chunks are not loaded anymore ;)
