### ISSUE TITLE
CMI autotab complete bug

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#3517]
**Description of issue:**
I'm not sure what is wrong but cmi has an autotab complete bug on the latest Paper git-Paper-353

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/fS5ESuFm
https://pastebin.com/DXzLpCkJ
```

---

**Cmi Version (using`/cmi version`):** 
8.6.27.2

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
1.15.2 git-Paper-353

**Comment by Zrips** [comment]
Try performing full server restart. As of testing and looking at your error log, it looks more like an issue with plugin not being correctly loaded on startup than actual bug. Could not reproduce this issue on 1.15.2 git-Paper-353, so something else is going on in your situation.
