### ISSUE TITLE
Tfly & Invcheck : Permissions

### ISSUE THREAD

**Issue by TimHarrio** [Zrips/CMI#352]
Hi,
It's just in the "wiki" is not written.
I don't find the permission for look if a player fly "/tfly <player>" (it's work with permission "*" but not with cmi.command.tfly)
And permission "cmi.command.invcheck" and "cmi.command.invcheck.edit" don't work, I have added to admin but admin don't have access to "/invcheck <player>.
Thank you.

**Comment by CloudeLecaw** [comment]
![image](https://user-images.githubusercontent.com/12080017/39799456-9260ebca-5364-11e8-8267-804170fdc6af.png)

![image](https://user-images.githubusercontent.com/12080017/39799470-a6a0dd16-5364-11e8-8ce5-0dcf50822c01.png)

you see there are 3 permisisons needed for tfly
**- cmi.command
- cmi.command.tfly
- cmi.command.tfly.give**

About invcheck? That command does not exist...what command do you mean?

**Comment by TimHarrio** [comment]
I successed to do work /tfly <player> (for check if he use the tfly) but invcheck still not work. I have do everything what you have say.

**Comment by CloudeLecaw** [comment]
hm tested it aggain with all the permission i wrote above in a Fresh permisison Profil and it works fine for me...
![image](https://user-images.githubusercontent.com/12080017/39816099-7dce5a04-539a-11e8-8bfe-95f44c134562.png)

![image](https://user-images.githubusercontent.com/12080017/39816116-8d3e82ac-539a-11e8-8cc8-0d7fda7ab9ce.png)

have u also set - cmi.command.invlist?

**Comment by CloudeLecaw** [comment]
here aggain all needed permsions for full fuction of this
**- cmi.command
- cmi.command.invcheck
- cmi.command.invcheck.others
- cmi.command.invcheck.edit
- cmi.command.invlist
- cmi.command.invload
- cmi.command.invload.others**

**Comment by LogGits** [comment]
I am assuming this was resolved. If you are still having this issue please don't hesitate to reopen an issue or respond to this one.
