### ISSUE TITLE
/tree not functioning as intended

### ISSUE THREAD

**Issue by e101stella** [Zrips/CMI#3520]
**Description of issue:**
Long and short of it, is that doing /cmi tree oak, or any variation of tree, will always result in a birch tree being spawned. 

Not a massive problem, just annoying that it doesn't work for anything other the birch trees currently x.x

---

**Cmi Version (using`/cmi version`):** 8.6.27.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot 

**Server Version (using `/ver`):** 1.15.2, Paper v353

**Comment by CloudeLecaw** [comment]
Great catch 😂 never noticd because im using worledits tree command all the time

**Comment by Zrips** [comment]
@e101stella 
There is no such thing as "oak". if you want one you will need to use "tree" as a tree type. But will make some changes to include more options when defining tree types with next update.
