### ISSUE TITLE
Sometimes Getting TPS Causes Error

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#3523]
**Description of issue:**

Sometimes entering /tps might got error.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
java.lang.NullPointerException: null
	at com.Zrips.CMI.utils.Lag.getTPS(Lag.java:26) ~[?:?]
```

**Cmi Version (using`/cmi version`):** 
8.6.26.11

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot 350

**Server Version (using `/ver`):** 
1.15.2

**Comment by Zrips** [comment]
Will be fixed with next version.

**Comment by coco0325** [comment]
[23:47:13 WARN]: java.lang.NullPointerException
[23:47:13 WARN]: at com.Zrips.CMI.utils.Lag.getTPS(Lag.java:31)

It happening again.
CMI version 8.7.6.6
Paper(149) 1.16.2-R0.1-SNAPSHOT

**Comment by coco0325** [comment]
Sometimes it happens.

java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.List.get(int)" is null
    at CMI9.1.4.7.jar//com.Zrips.CMI.utils.Lag.getTPS(Lag.java:31)

CMI 8.1.4.7
Purpur 1.17.1
