### ISSUE TITLE
/attachcommand doesn't appear to be working

### ISSUE THREAD

**Issue by destro174** [Zrips/CMI#3524]
**Description of issue:**
```
/attachcommand !left!plot delete;;!right!plot confirm
```
One of our mods has been using this to attach commands to a stick, but it stopped working after updating CMI to a newer version.

---

**Cmi Version (using`/cmi version`):** CMI: 8.6.27.2 BungeeCord MySQL-> 8.6.27.3

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** This server is running Paper version git-Paper-334 (MC: 1.15.2)

**Comment by Zrips** [comment]
Do you mean that old items no longer work or new ones? As of testing, everything seams to work as it should at this point.

**Comment by destro174** [comment]
This is no longer an issue in latest version
