### ISSUE TITLE
/SPAWN /HOLOGRAM /PORTALS NOT WORKING AFTER RESTART

### ISSUE THREAD

**Issue by DarrienNN** [Zrips/CMI#3528]
**Description of issue or feature request:**

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## [Sat, 20. Jun 2020 00:13:44 SGT INFO] XiiaoOnE_ issued server command: /portals
[Sat, 20. Jun 2020 00:13:44 SGT ERROR] null##
####################
```

```

---

**[Sat, 20. Jun 2020 01:01:26 SGT INFO] --------------------------------------------------
[Sat, 20. Jun 2020 01:01:26 SGT INFO] CMI: 8.6.27.3 BungeeCord  SqLite
[Sat, 20. Jun 2020 01:01:26 SGT INFO] Server: Tuinity 1.15.2-R0.1-SNAPSHOT
[Sat, 20. Jun 2020 01:01:26 SGT INFO] CMI economy: False Vault: 1.7.2-b107 CMI Chat: True 
[Sat, 20. Jun 2020 01:01:26 SGT INFO] Modules -> 51 enabled 0 disabled: 
[Sat, 20. Jun 2020 01:01:26 SGT INFO] --------------------------------------------------** 

**Server Type: TUINITY** 

**This server is running Tuinity version git-Tuinity-"7c03cbe" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Tuinity-"d8b8905" (MC: 1.15.2)
You are 5 version(s) behind* 

**SkQuery/Asynceworldedit/tuske**

**Comment by mrfloris** [comment]
In CMI's `alias.yml` file, do you have these broken commands set to true or false?
```
/spawn
/portals
/hologram
```
And what does it show in console, when you try them through CMI itself?
```
/cmi spawn
/cmi portals
/cmi hologram
```

**Comment by DarrienNN** [comment]
After  i add this skquery/tuske/asynceworldedit my server cmi stopped working properly
if i add these 3 plugin my server will have this issues: **spawn point is not set!** portals will write internal error, and for hologram, the hologram will not showing until u type /hologram and click those hologram until they show back 

Replying>>
In CMI's alias.yml file, do you have these broken commands set to true or false?

/spawn **TRUE**
/portals **TRUE**
/hologram **TRUE**

**Comment by DarrienNN** [comment]
Replying>>
And what does it show in console, when you try them through CMI itself?

/cmi spawn **[Sat, 20. Jun 2020 01:13:56 SGT INFO] Darrien_ issued server command: /spawn**(but in game keep say "spawn point is not set"
/cmi portals **[Sat, 20. Jun 2020 00:13:44 SGT ERROR] null**
/cmi hologram **[Sat, 20. Jun 2020 01:13:43 SGT INFO] Darrien_ issued server command: /hologram **[Sat, 20. Jun 2020 01:13:43 SGT INFO] Darrien_ issued server command: /hologram**

**Comment by mrfloris** [comment]
`arrien_ issued server command: /spawn(b`

that's /spawn, 

What do you get when you use `/cmi spawn Darrien_` (or whatever player you're testing it with)

Did you ever set spawn and firstspawnpoint with cmi, is it configured in config.yml?
`/cmi setspawn`
`/cmi setfirstspawn`

`/cmi portals [Sat, 20. Jun 2020 00:13:44 SGT ERROR] null`
i dont see the command being entered

`/cmi hologram **[Sat, 20. Jun 2020 01:13:43 SGT INFO] Darrien_ issued server command: /hologram `
same again, i see /hologram, not /cmi hologram.

**Comment by DarrienNN** [comment]
[Sat, 20. Jun 2020 13:23:38 SGT INFO] Darrien_ issued server command: /cmi portals
[Sat, 20. Jun 2020 13:23:39 SGT ERROR] null
[13:23]
[Sat, 20. Jun 2020 13:23:42 SGT INFO] Darrien_ issued server command: /cmi spawn
[Sat, 20. Jun 2020 13:23:43 SGT INFO] Darrien_ issued server command: /cmi spawn Darrien_
[13:23]
[Sat, 20. Jun 2020 13:23:48 SGT INFO] Darrien_ issued server command: /cmi hologram

**Comment by DarrienNN** [comment]
https://imgur.com/a/fDfFDsW
This images that i screenshot, infront me alot hologram. But after add skquery stop showing

must type /hologram and click 1 by 1 hologram that i create then will show back
https://imgur.com/a/9awQNML

**Comment by DarrienNN** [comment]
Hey i found the issues from where already!
That issues from : Holographicdisplays

**Comment by DarrienNN** [comment]
i use holographicdisplays because my server using fabledskyblock and need holographicdisplays(Addon) to work leaderboard

**Comment by mrfloris** [comment]
Thank you for all the additional information. I will give zrips a poke and see what he might think.

**Comment by Zrips** [comment]
@DarrienNN 
Would be nice to have those error logs, as having basic line 
[Sat, 20. Jun 2020 13:23:39 SGT ERROR] null
doesn't say anything what actually failed. There should be long error after it. if there is none, then you will need to disable plugins which manipulates console messages so it would output full error log. After this we can continue investigating what actually failed
