### ISSUE TITLE
ifinportals:[value][@][?][#]!

### ISSUE THREAD

**Issue by thomaboehi** [Zrips/CMI#3529]
**Description of feature/improvement request:**
Specialized command: ifinportals:[value][@][?][#]!
---
### Detailed explanation of what it should do, when and in what situation: ###
This specialized commands should check if a player is still in the portals when the commands is executed.
### Basic explanation as to why this feature is needed and/or useful to have: ###
I'm using CMI Portals on my server for my PVP Map, there are Zones and players have for example to stay 10 seconds in a zone (portals) to get a food drop.

But I want them to still be in the zone (portals) when the drops is executed.

This is my actual configuration:
`
    commands:
    - perm:gopvp.recharge.lime! cmi msg [playerName] !-&cYou must wait %luckperms_expiry_time_gopvp.recharge.lime%
    - perm:gopvp.recharge.lime@#! cmi bossbarmsg [playerName] Drop in [autoTimeLeft]! -cmd:"ifinworld:gopvp?! cmi give [playerName] wheat 12" -sec:-10 -c:red
    - delay! 2
    - lp user [playerName] permission settemp gopvp.recharge.lime true 2m
`

**Comment by Zrips** [comment]
Will add
