### ISSUE TITLE
Change tablist name when AFK

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#353]
Add an `afkName` option beneath `PlayerName` that defines what their name will display as when they are afk (also would like an option to enable/disable this feature).

Thanks

**Comment by CypherPhyre** [comment]
You can do this in the GroupFormat section to indicate if they are AFK or not in the tab
PlayerName: '&6%cmi_user_afk_symbol% &2{&r[playerDisplayName]&2}'
