### ISSUE TITLE
command statsedit / cmi_equationint / statsedit placeholder

### ISSUE THREAD

**Issue by LoToRTv** [Zrips/CMI#3532]
1. Command "cmi statsedit NAME set/take kill_entity cow 5" [cow or other entite]
Error: Changed from 0 to 0 value for Monster kills (cow)
"set" works only message set 0 to 0
"take" not works set all time zero 

it works for other things like open_chest 

2. next %cmi_equationint_ only works from cmi placeholder other not working like %cmi_equationint_{cmi_equationint_%statistic_kill_entity:cow}+{cmi_equationint_%statistic_kill_entity:pig}%

3. want to ask existing placeholder like %cmi_kill_entity_pig% or other stats from /cmi stats player

CMI: 8.6.27.3 SqLite
Server: Paper(347) 1.15.2-R0.1-SNAPSHOT
CMI economy: True Vault: 1.7.3-b CMI Chat: True
Modules -> 49 enabled 2 disabled: tablist, votifier

 CMI, CMIPaperLib, DeluxeMenus, DisplayShops, EffectLib*, FastAsyncWorldEdit, FeatherBoard*, HeadDatabase*, IridiumSkyblock, LuckPerms, Multiverse-Core, MysteryBoxes, PlaceholderAPI, ProtocolLib, ShopGUIPlus, Vault, VoidGenerator, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by CloudeLecaw** [comment]
All placeholders with cmi are mostly only for cmi and can be ridden just in cmi. If you wanne use these placeholder outside of cmi then you need to ask the dev of the other plugin to make hia plugin comfirmal witz cmi's placeholders.

**Comment by Zrips** [comment]
statsedit will be fixed, its only visual bug
your placeholder **%cmi_equationint_{cmi_equationint_%statistic_kill_entity:cow}+{cmi_equationint_%statistic_kill_entity:pig}%** is broken. You have % in middle of placeholder which breaks everything. You can only have {} inside placeholder if you want to have placeholder inside placeholder.
