### ISSUE TITLE
Tfly command

### ISSUE THREAD

**Issue by QueenAngus** [Zrips/CMI#3538]
**Description of issue or feature request:**
When giving players the cmi.command.tfly perm, they can both go /tfly to see how much temporary flight they have left, and also use /tfly (time) to give themselves more time. My request is simple, separate perms for these so that people can see how much time they have left but not modify their own time. 

Thanks.

**Comment by CloudeLecaw** [comment]
Nice idea. This should be also possible for tgod :)

**Comment by mrfloris** [comment]
Technically someone could make a /flytime command that uses the placeholders to visualize time remaining. But I agree, splitting up the tfly permissions so they can't set the tfly but they can check the tfly, seems like a logical expansion. 
Placeholders that can be used in action-, bossbar msgs, etc. are:
```
%cmi_user_canfly% (true/false - can they fly?)
%cmi_user_flying% (true/false - are they flying?)

%cmi_user_tfly% (integer - time in seconds remaining until tfly expires)
%cmi_user_tfly_formatted% (string - formatted time until tfly expires)

/flytime could be like so:
msg! [playerName] Temp fly ends in (%cmi_user_tfly% seconds) %cmi_user_tfly_formatted%
```

**Comment by CloudeLecaw** [comment]
Yeap also a nice idea for tgod :)

**Comment by Zrips** [comment]
Will add permission node as cmi.command.tfly.admin which will allow to manage time, but without it will only output current tfly state
