### ISSUE TITLE
Hide teleport effects when a player is in a vanish or has an invisibility effect

### ISSUE THREAD

**Issue by DarkFort** [Zrips/CMI#3539]
I propose to improve the functionality of the TeleportEffects parameter. Effects are displayed when a player is in a vanish or has an invisibility effect. This must be hidden so that no one will notice the player.

**Comment by CloudeLecaw** [comment]
If the vanish and effects come from cmi teleportation commands then i agree with you :)

**Comment by DarkFort** [comment]
> If the vanish and effects come from cmi teleportation commands then i agree with you :)

Yes, from the CMI plugin. TeleportEffects parameter in the config

**Comment by mrfloris** [comment]
> If the vanish and effects come from cmi teleportation commands then i agree with you :)

You could have checked this yourself, open the config.yml up and find the teleporting section. 
To contribute to the bug report or feature request, it would be nice to have a 'i checked, it indeed shows, i think this is more a bug than a feature' versus: yeah nice. 

Not trying to sound mean..

**Comment by CloudeLecaw** [comment]
I agree, nothing else to say. I got the same result

**Comment by Zrips** [comment]
Its a bug'ish or simply incomplete feature. As there are quite few things interconnecting i cant really think about all of them from the start. But will adjust its behavior to avoid showing up particles when you teleport while being in vanish mode
