### ISSUE TITLE
Issuses CMI is no Replacement - or is it?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#354]
how often we look in this issues now we all very often will see the Statment from some users:

CMI is a Replacement for Essentials
CMI is a Replacement no for Essentials

In my eye ist not a Replacement, it is an Option with many cool and also more Features.
Many of These cool Features are working simliar or better but i never would call CMI as a Replacement.
I can understand everyone that stop using Essentials because of the massive Features that CMI has.

What is your optinion? Is it one or not?
Also a Statment  of our Developer ZrIps would be nice ;)

**Comment by Zrips** [comment]
Long story short. CMI is not a Essentials. You can compare features if you want, but this is not a d*ck measuring contest. CMI does majority stuff what Essentials can, Essentials does something what CMI currently is not. Comparing them will not be productive way. Look at CMI as a plugin for your server, not a plugin which should do exactly same things as Essentials and something more.

Will have to close this one as this is more appropriate for forum section and not for github.
