### ISSUE TITLE
CMI Bungee isn't updating the placeholders on another server that are on different machine.

### ISSUE THREAD

**Issue by variananora** [Zrips/CMI#3542]
**Description of issue:**
CMI Bungee isn't updating the placeholders on another server that are on different machine.

**Screenshots:**
Server Survival (Machine A):
![image](https://user-images.githubusercontent.com/34732414/85379306-d3ebed00-b565-11ea-9f8e-bcd47d87345f.png)

Server Skyblock (Machine B):
![image](https://user-images.githubusercontent.com/34732414/85379270-c898c180-b565-11ea-9fa0-25cb0f7270d0.png)

**Cmi Version (using`/cmi version`):** 
Server Survival: 8.6.27.3
Server Skyblock: 8.6.27.3
Server Bungee: 1.0.0.4

**Server Type (Spigot/Paperspigot/etc):** 
Tuinity + Waterfall

**Server Version (using `/ver`):** 
1.15.2

**Comment by CloudeLecaw** [comment]
can you reproduce this problem with spigot/paperspigot?

Tuinity or Waterfall are no official forks of spigot, so i think Zrips will just look into it if you can reproduce this with spigot too (or with paperspigot)

**Comment by variananora** [comment]
Recreated with Spigot and Bungeecord, same result...
Extra note: I'm using pterodactyl and the Bungeecord is listening at main IP address (1.2.3.4:25565 - Machine A), meanwhile Survival server is (127.0.0.1:25567 - Machine B) and Skyblock (5.6.7.8 - Machine B)

**Comment by Zrips** [comment]
@variananora 
You do have CMIB plugin on your bungee main server? and have you got "CMIB proxy plugin detected" on your servers?

**Comment by variananora** [comment]
Sorry for the late reply, I tested all of it with the latest CMI (8.7.4.0) and the problem still occurred.


> @variananora
> You do have CMIB plugin on your bungee main server? and have you got "CMIB proxy plugin detected" on your servers?

Yes, I have CMIB (1.0.0.4) and it shows `[CMI] CMIB proxy plugin detected`

Sometimes the placeholder updated but stuck, like this:
CMI says there are 12 players, but in reality, there are more than 12 players.
![image](https://user-images.githubusercontent.com/34732414/88632135-617aa980-d0dd-11ea-8678-50dd120885af.png)

![image](https://user-images.githubusercontent.com/34732414/88632192-70f9f280-d0dd-11ea-9f43-fa6e5550a503.png)

**Comment by variananora** [comment]
Closed because it's resolved somewhere on the latest build.
