### ISSUE TITLE
can't disable modules "nameplates"

### ISSUE THREAD

**Issue by NightPrimez** [Zrips/CMI#3543]
**Description of issue:**
so.. i set `namePlates: false` in modules.yml but it's still can using command or features

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# Handles player name plates
# Applies for servers from 1.7.x and up
namePlates: false
```

---

**Cmi Version (using`/cmi version`):** 
8.6.27.3
**Server Type (Spigot/Paperspigot/etc):** 
SSSpigot (PaperSpigot fork)
**Server Version (using `/ver`):** 
1.15.2

**Comment by CloudeLecaw** [comment]
Even after server restart?

**Comment by NightPrimez** [comment]
> Even after server restart?

yes

**Comment by Zrips** [comment]
Small bug, should properly disable nameplate handling with next update
