### ISSUE TITLE
plugin inquiry

### ISSUE THREAD

**Issue by Stoniasawsome** [Zrips/CMI#3546]
**Description of feature/improvement request:**

---
### Basic explanation as to why this feature is needed and/or useful to have: ###

you advertise your plugin as a full essentials replacement. we are missing quite a few things tho, like the chat portion of essentials. permissions for the coloring and formatting of nicks. we only have perms for nick, not nick color and nick format so everyone can use color. also theres no firework command. There is no signs perms for color and format only sign edit. there is no perm for heal or feed cooldowns. there is no /unlimited. also there is no perm for disabling fall damage per player/group and i cant /cmi give myself diamondpickaxe 1 efficiency:5 name:test lore:test im aware i can rename these with a separate command but this poses a problem when i have signs and shop items that use that command. i also like to add {playername} and {date} to my items that donators buy, but i cant do this with your plugin. THis is the command inside the essentials kit.yml that i use to give players named, lored items with their name and date of purchase on them 
                                   diamondhelmet 1 name:&e&l[&a&lL&2&lu&a&ln&2&la&a&lt&2&li&a&lc&e&l]_&aHelmet
      protection:5 fire_protection:5 unbreaking:5 lore:_|&a{USERNAME}_|&a{DATE}.                                                                        
            its a very good plugin so far though, ive removed so many plugins i had to have without your plugin. thanks for your time

**Comment by CloudeLecaw** [comment]
> `you advertise your plugin as a full essentials replacement.`

No we advertice its even better but noone said that everything is replaced.
So close issue ;)

**Comment by Stoniasawsome** [comment]
not that im trying to stir trouble but... your plugin does say that "It can fully replace Essentials/EssentialsX"


-----Original Message-----

**Comment by CloudeLecaw** [comment]
No one cares aboth this, u oaid for a plgin that CAN fully replace Essentials and do it even better
Go to essentials or read the wickii, think about ths itself
and then close this issue. 

this tread here is really not what githhub is for, your the only one in the world that use github for this messing with essentials go in the essentials discord if this is still alive,

, i willl report this ticket to the admins now to close this,

**Comment by Stoniasawsome** [comment]
this is not an attack... its a legit question... it does in fact say... This plugin is made to be all in one plugin for server management and replace multiple outdated plugins. It can fully replace Essentials/EssentialsX and contains simple conversion commands to transfer old player data to new system.

in that description does it not say a full replacement? its really not who are you? are you zrips? whats your problem...? i was just asking a question is "question" not an applicable option for github? calm yourself... you didnt have to reply if you arent zrips if you are zrips then wtf dude show some compassion for people who cant understand your plugins info. its not a full replacement if it dont come with /unlimited. this was not intened to be an arguement so stop trying to make it one... jesus and feel frree to report me, am i suppose to feel scared or threatened by that?
-----Original Message-----

**Comment by Stoniasawsome** [comment]
also i dont know how to close it, so YOU do it


-----Original Message-----

**Comment by CloudeLecaw** [comment]
ok ;)

**Comment by Stoniasawsome** [comment]
good answer... i see youre a bright one... i really hope youre not zrips cause if you are, youre a disgrace to your own great plugin


-----Original Message-----

**Comment by CloudeLecaw** [comment]
read the main side of this githut next time

> CMI Issue Tracker
> This is the official CMI issue tracker.
> 
> Aside from issues you can also request features for CMI here.
> 
> If you are having any issues regarding payments and/or other private matters, please message Zrips on Spigot.

**Comment by Stoniasawsome** [comment]
lol a stubborn arrogant one i see. no problem dickhead! will do!


-----Original Message-----

**Comment by CloudeLecaw** [comment]
> lol a stubborn arrogant one i see. no problem dickhead! will do!
> […](#)
> -----Original Message----- From: CloudeLecaw <notifications@github.com> To: Zrips/CMI <CMI@noreply.github.com> Cc: Stoniasawsome <myke169@aol.com>; Author <author@noreply.github.com> Sent: Wed, Jun 24, 2020 8:38 pm Subject: Re: [Zrips/CMI] plugin inquiry (#3546) read the main side of this githut next time CMI Issue Tracker This is the official CMI issue tracker.Aside from issues you can also request features for CMI here.If you are having any issues regarding payments and/or other private matters, please message Zrips on Spigot. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

uff....
