### ISSUE TITLE
followed with player name will give item from its hand /give

### ISSUE THREAD

**Issue by LoToRTv** [Zrips/CMI#3547]
Hello, it was possible to add command like /cmi give [playername] +mainhand 5  followed with player name will give item from its hand.

it's quite illogical that command /giveall have this option...if I want to give something to a specific player, I can't

**Comment by LoToRTv** [comment]
and fix /cmi reload for customalias not workings

**Comment by Zrips** [comment]
For custom alias to properly update you might need full server restart due to their complex handling

**Comment by Zrips** [comment]
Will add new variable with next update
