### ISSUE TITLE
wrong deathinventories?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#355]
when im do /invcheck Cloude_Lecaw

i get the Long list with the saved inventories but now i clicked one

![image](https://user-images.githubusercontent.com/12080017/39816484-af9d0822-539b-11e8-8e90-48c0333e7b12.png)

this is the inventorie of an other Player....how can this happen?

![image](https://user-images.githubusercontent.com/12080017/39816553-e22ab9ba-539b-11e8-960c-7b83d3fa194d.png)

**Comment by LogGits** [comment]
Are you still having this issue? If so, would you be able to provide a video or a gif of this issue? I have been unable to reproduce this on the latest build.

**Comment by CloudeLecaw** [comment]
im nor confirmal with making Videos or animted gives but i can do some step by step screenshots 🥉 

![image](https://user-images.githubusercontent.com/12080017/40112992-2904f2b2-5908-11e8-8ab5-70cfb0c3674f.png)

![image](https://user-images.githubusercontent.com/12080017/40113008-3ce779f8-5908-11e8-8d3a-9a328c01dd2b.png)
The Inventar is from player NouLex - nr22

![image](https://user-images.githubusercontent.com/12080017/40113042-5aaafde8-5908-11e8-991b-ce4c168fb0ff.png)
![image](https://user-images.githubusercontent.com/12080017/40113058-69359332-5908-11e8-8492-7bc5ea70485c.png)

it does not matter what nr i choose the inventores are idenicall and allways from this Player.
may there got something wrong in the db?

**Comment by Zrips** [comment]
Do you have warning message on startup that you have duplicated users by same name just different capitalization? As this could be source of issue

**Comment by CloudeLecaw** [comment]
no duplicates warnings
