### ISSUE TITLE
OneKey Update

### ISSUE THREAD

**Issue by MSGAMONG8** [Zrips/CMI#3550]
**Description of feature/improvement request:**
The ability to update the plugin to a newer version straight from the game, like this
![Screenshot_4](https://user-images.githubusercontent.com/40808609/85647117-0567d400-b69e-11ea-94db-1295cd3b9fc3.png)

---
### Detailed explanation of what it should do, when and in what situation: ###
Once a new CMI update is released, server admins should get a notification in chat will the ability to update it using an in-game command/clicking on a text like in the screenshot above. Once the admin clicks on the update button, the server downloads a new version of CMI, deletes the old one and reloads CMI

### Basic explanation as to why this feature is needed and/or useful to have: ###
This feature will make it easier and quicker for server admins to update CMI to a newer version

**Comment by CloudeLecaw** [comment]
This will may not work, often cmi Updates have a new name + require a server restart.

**Comment by Zrips** [comment]
On top of this, CMI is paid plugin, for anyone to have something like this you will need public access to some file server, which would be easy way to breach security. So no go on this one.

**Comment by SlyTheFloof** [comment]
lol

**Comment by CloudeLecaw** [comment]
Zrips is right about this.
Having an automatic button would require a free acess somewhere, that could be missued to leak allways latest Version from others. A dev also could develop plugina here that downloads allways last Version of the plugin to people that have not bought it. And even if not, onced a leaked version with this update would come to private sites, would give the priate the ability to allways update to latest version.  So its good that a feature like this will never be released.
