### ISSUE TITLE
1.16.1 Feature Request - /itemframe

### ISSUE THREAD

**Issue by OverBrave** [Zrips/CMI#3556]
Added 2 different statuses for item frames.
1- not break
2- Invisibility

Can you add a supported command for them?

**Comment by CloudeLecaw** [comment]
Hm so the next one wants this for signs... And for flowers maybe the breaking on is better a thing for a protectionplugin like residence? About the other thing frame dont have the abillity to be invissible by the Minecraft Code. Im not sure if this is possible to manageby cmi or any other plugin. Next question would be how to remove a frame if it would be invissible?

**Comment by OverBrave** [comment]
{EntityTag:{Invisible:1b}} or {EntityTag:{Invisible:0b}}
{EntityTag:{Fixed:1b}} or {EntityTag:{Fixed:0b}}

**Comment by CloudeLecaw** [comment]
and this works for frames? i never saw an invissible frame...

**Comment by OverBrave** [comment]
This features its coming in 1.16 update. If you look patch notes, can you see.
I already said:
/itemframe visible : If looking item frame and if visible, set to invisible, otherwise oppenent
/itemframe fixed : If looking item frame and if breakable, set to unbreakable, otherwise oppenent

**Comment by Zrips** [comment]
next update **/cmi itemframe (visible/fixed)**

**Comment by CloudeLecaw** [comment]
its there now but its not workin^^

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/85948630-9bc81e00-b95a-11ea-87d0-49857955e813.png)

**Comment by CloudeLecaw** [comment]
jep thats what i also issuesd

**Comment by Zrips** [comment]
Introduced typo in a code with last minute change which broke invisibility toggle... Will fix it

**Comment by CloudeLecaw** [comment]
it broke all argument after /cmi itemframe
