### ISSUE TITLE
Vanishing player's Chest Inventory View not updated when a normal player shift-moved item in the same chest

### ISSUE THREAD

**Issue by cvrunmin** [Zrips/CMI#3557]
**Description of issue:**
A vanishing player(Player A) is viewing a chest inventory, and another player(Player B) opens the same chest. Player A's inventory view would not be updated when Player B shift-moves items into/out of the chest. Then when Player A does anything to the inventory view (e.g. clicking outside of the Chest Gui), items in A's view will be synced back to B, which could duplicate items.

---

**Cmi Version (using`/cmi version`):** 
8.6.27.4 BungeeCord MySQL
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper(350) 1.15.2-R0.1

**Comment by CloudeLecaw** [comment]
Well have u tested this? I would assume that if a opens the chest aggain he will se the updated container stuff. Also you can prevent interacting while vanished.

**Comment by cvrunmin** [comment]
I would however assume that server moderator would do anything weirdo. This might be a rare case, but this causes item duplication, so I think this issue should be reviewed
