### ISSUE TITLE
For all norwegians out there - Locale_NO.yml

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#3559]
**Description of feature/improvement request:**
I have translated the entire language file into Norwegian. Download using the link. This can also be added to the CMI project if desired.

[https://drive.google.com/u/0/uc?id=1TlWttbHfvwMazGdEs8tRTOQbWyBIfz25&export=download](https://drive.google.com/u/0/uc?id=1TlWttbHfvwMazGdEs8tRTOQbWyBIfz25&export=download)

---

**Til alle nordmenn:** Jeg har oversatt hele språkfilen til norsk. Last ned ved bruk av linken. 
[https://drive.google.com/u/0/uc?id=1TlWttbHfvwMazGdEs8tRTOQbWyBIfz25&export=download](https://drive.google.com/u/0/uc?id=1TlWttbHfvwMazGdEs8tRTOQbWyBIfz25&export=download)

**Comment by Zrips** [comment]
Thanks, will add it to default package for everyone to enjoy.
