### ISSUE TITLE
Permission for using [item], Hover Items, and Item Regex.

### ISSUE THREAD

**Issue by Bettanation** [Zrips/CMI#3561]
**Description of feature/improvement request:**
Permission for using [item], Hover Items, and Item Regex.
---
### Detailed explanation of what it should do, when and in what situation: ###
allow to give a permission to use [item] in chat.
### Basic explanation as to why this feature is needed and/or useful to have: ###
for donor ranks or so certain ranks can show off their items and others cant.

**Comment by Frostified** [comment]
Whats the point of a feature request if it hasnt been looked at in over 3 months?
Jesus christ
