### ISSUE TITLE
Add placeholder

### ISSUE THREAD

**Issue by diskotekastar** [Zrips/CMI#3565]
** Description of the improvement request: **
Hello,

I have an idea to add a placeholder "%no_vanished_online%" this placeholder would show the number of online players, but would not count the vanished players.

---
### Basic explanation of why this feature is needed and / or useful for obtaining: ###
This feature is useful so that, for example, the number of online players can be seen in the tab, except for vanished players

**Comment by CloudeLecaw** [comment]
this is normal allready in cmi

**Comment by diskotekastar** [comment]
I would like to ask through which placeholder this can be viewed. (Using the PlaceHolderAPI plugin)

I have the plugin updated to the latest version, but in TAB it looks pretty weird

![image](https://user-images.githubusercontent.com/61634734/86646723-c6137e80-bfdf-11ea-854d-b78909e9daac.png)
