### ISSUE TITLE
hologram colors with 8.7.0.1

### ISSUE THREAD

**Issue by MichelleBellez** [Zrips/CMI#3567]
**New Hex code colors don't work in holograms:**
It'll let you put in the Hex code and it'll show correctly in the chat. But it tries to turn it into the old color codes when displaying it on a hologram 

**Cmi Version (using`/cmi version`):** 
8.7.0.1
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.16.1

**Comment by Zrips** [comment]
Yea, because holograms are doesn't support hex code, well its entity name plate which doesn't support it. Cant really do anything about it. Unless its some how possible and i'm not aware of.
