### ISSUE TITLE
new command cmi itemframe is not working

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3568]
![Snag_6db162f](https://user-images.githubusercontent.com/12080017/85891370-3d326100-b7ef-11ea-86f4-2c8c1f490e18.png)

The command cmi itemframe seems to do nothing it just print ou a chat meassge "enabled" thats all..

all 3 status just give you the info "enabled"
doesnt make really sense... so i assume its a bug

**Comment by Zrips** [comment]
Will be fixed with next build

**Comment by CloudeLecaw** [comment]
are the aother 2 argum,ents also fix in the next build? :-)
