### ISSUE TITLE
Add support for Prisma

### ISSUE THREAD

**Issue by Verdux** [Zrips/CMI#3569]
Add support for Prisma plugin so we can have custom color codes to avoid our language files getting too messy filled with {#555555} everywhere.

Plugin is similar concept to Vault, a universal place for plugins to hook into and players will be able to change up all their color codes a lot more efficiently. Simple to implement and doesn't break anything already existing.

See here: https://www.spigotmc.org/resources/prisma.80713/

**Comment by Zrips** [comment]
Color remapping will be coming in the future, having dependency is not a solution. Currently color codes are in early stage and it will improve with time. Check next update
