### ISSUE TITLE
Tablist Sorting based on Group

### ISSUE THREAD

**Issue by MrAmos123** [Zrips/CMI#3571]
**Description of feature/improvement request:**

---
I want the ability to sort players based on their group list and would rather not use some 3rd party plugin when CMI does 90% of the TAB list functionality I want, except for sorting.

You even have `cmi.tablist.X` except there's no useful way to use this because you can't do like `%cmi_tablist_sort_by_weight%` or something.

Please allow us to sort the tablist by `cmi.tablist.X` permission or some other method that's in-house.

https://i.imgur.com/hFYqTG5.png

**Comment by thecenters** [comment]
I second this.

**Comment by CloudeLecaw** [comment]
Yeah i know what you mean you want a sorted tablist where owners and admins are listed first andnmay mods after and after this may Vips and players at the end. Right? Maybe a hook witch the permission system would be possible to sort by your permission groups.  This also may be a nice solution then sorting with the current tab group permission.

**Comment by MrAmos123** [comment]
> Yeah i know what you mean you want a sorted tab list where owners and admins are listed first andnmay mods after and after this may Vips and players at the end. Right? Maybe a hook witch the permission system would be possible to sort by your permission groups. This also may be a nice solution then sorting with the current tab group permission.

There's already a permission node in CMI "cmi.tablist.X" replacing X with the weight you want. It has no use from what I can tell.

Give each group a different weight.

if there was some placeholder %cmi_tablist_sort_by_weight% which you put before your name prefix in `PlayerName` in TabList, then easy. Done. 

I don't mind how it's done, but it makes no sense to me to go out of my way to get a 3rd party plugin when this does 90% of the functionality already.

**Comment by CloudeLecaw** [comment]
It allows you to have differnt tabs shiwn to each group its no weight
