### ISSUE TITLE
Shift editing signs does not work

### ISSUE THREAD

**Issue by Frostified** [Zrips/CMI#3573]
**Description of issue:**
Shift editing signs does not work.

---

**Cmi Version (using`/cmi version`):** 
8.7.0.1 latest
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.16.1

**Comment by Zrips** [comment]
Sign editor does open, sadly it doesn't contain existing text of sing. This is issue with minecraft itself and i dont think there is a fix for it as it should be fixed on client side.
And just FYI by default shift clicking sign will not work, you need to toggle it with /cmi toggleshiftedit
