### ISSUE TITLE
KeepXP on death does not work or permission does not work

### ISSUE THREAD

**Issue by Frostified** [Zrips/CMI#3574]
**Description of issue:**
KeepXP on death does not work or permission does not work

---

**Cmi Version (using`/cmi version`):** 
8.7.0.1 latest
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.16.1

**Comment by mercurialmusic** [comment]
This is working normally for me on CMI 8.7.0.3 using git-Spigot-0287a20-2fe6b4a (MC: 1.16.1). You've posted a couple issues now with permissions, so it might be worth a look into your permissions plugin instead. Which permissions plugin are you using and what version?

**Comment by Frostified** [comment]
> This is working normally for me on CMI 8.7.0.3 using git-Spigot-0287a20-2fe6b4a (MC: 1.16.1). You've posted a couple issues now with permissions, so it might be worth a look into your permissions plugin instead. Which permissions plugin are you using and what version?

Thats great they are working for you mercurialmusic! But not so much for me. And your using 2 versions above mine. Your comment about permissions is irrelevant if your not even using the same build. I have used the same permissions plugin for going on 10 years with no issues. I am going to update my CMI and Spigot build and try again.

**Comment by Zrips** [comment]
@Frostified 
Wild guess, is it UltraPermissions?
And check if player has access to permission with /cmi haspermission Zrips cmi.keepexp
Which will output what CMI sees and we will know if its correctly been recognized or there is some issue with that

**Comment by Frostified** [comment]
> @Frostified
> Wild guess, is it UltraPermissions?
> And check if player has access to permission with /cmi haspermission Zrips cmi.keepexp
> Which will output what CMI sees and we will know if its correctly been recognized or there is some issue with that

PermissionsEX is what ive allways used. As it never changes and uses 1 flat file.
I will do some testing when i get back home.

**Comment by Zrips** [comment]
@Frostified 
Och and another side note, test it with only CMI and PEX installed, just to rule out any other plugin overriding exp drop after CMI disabled it, which could be actual cause of this issue.

**Comment by Frostified** [comment]
I was using cmi.keepxp instead of cmi.keepexp. User error
