### ISSUE TITLE
Feature Request - vote (democracy)

### ISSUE THREAD

**Issue by Blackdigits** [Zrips/CMI#358]
Description of issue or feature request:
Hi there, can you please add a feature that allows the player to vote for a punishment for other player? Like a vote kick / mute / ban / jail etc?

**Comment by 0xC1A551C** [comment]
Everyone would vote ban lol

**Comment by TheWranger** [comment]
I like this idea, however I think this would work better if we got to customize ourselves what commands would activate after a certain type of player vote.
This way we could have a customizable vote tempban or vote tempmute system.

**Comment by LogGits** [comment]
Thank you for the suggestion. Currently, we have no intention of adding such a feature. However, maybe when all the issues are resolved, we will start to investigate this 🙂
