### ISSUE TITLE
ClickHoverMessages breaks private chat formatting newline to lose coloring

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#3580]
**Description of issue:** 
Private chat formatting is broken when the second line starts
Screenshot what I would expect:
![Screenshot_20200627_124645](https://user-images.githubusercontent.com/28690790/85920481-69dc8c00-b874-11ea-8c03-9d684f9cbf8a.png)
Screenshot how it actually is:
![Screenshot_20200627_124712](https://user-images.githubusercontent.com/28690790/85920484-79f46b80-b874-11ea-9f29-8749be92ff70.png)
The cause is the config option `ClickHoverMessages: true`. As soon as this is set to true, the second line of the message got a reset to white coloring

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Config file:
```yaml
Chat:
  ModifyChatFormat: true
  ClickHoverMessages: true
```
Translation file:
```yaml
  msg:
    info:
      TargetMsg: '&6[&e[senderDisplayName] &6-> &cMe&6]&r&7 [message]'
      SenderMsg: '&6[&cMe &6-> &e[playerDisplayName]&6]&r&7 [message]'
```

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.7.0.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.15.2 build 372

**Comment by kassadGLA** [comment]
Can confitm with CMI 8.7.0.2. The issue related with any case when a text auto moving at new line.

**Comment by Zrips** [comment]
should be fixed with latest .5+ version
