### ISSUE TITLE
Vanish error

### ISSUE THREAD

**Issue by sketrick** [Zrips/CMI#3581]
https://pastebin.com/yybgd4K0

CMI 8.7.0.1

Spigot 1.16.1

git-spigot-6f4ff1b-d424351
1.161-r0.1

**Comment by mrfloris** [comment]
Get new buildtools.jar and rebuild spigot with git-Spigot-6f4ff1b-983305b (MC: 1.16.1) and upgrade to 8.7.0.2 and try again. 
I believe i've seen this before and it has disappeared for me when i updated my spigot build.
