### ISSUE TITLE
/cmi glow gui not working (but it does in /cmi glow color)

### ISSUE THREAD

**Issue by Blandix** [Zrips/CMI#3584]
**Description of issue:** /cmi glow gui shows white glow. But /cmi glow color works fine.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**

Not an error, this is the console message with gui setting

`Blandix issued gui command: /cmi glow Blandix darkpurple=com.Zrips.CMI.Containers.CMIChatColor@3fce6c20`

And this with no gui setting, directly from command

`Blandix issued server command: /glow darkpurple`

---

**Cmi Version (using`/cmi version`):** 8.7.0.1

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** 1.15.2 Build 371

**Comment by CloudeLecaw** [comment]
duplicated https://github.com/Zrips/CMI/issues/3295

**Comment by Blandix** [comment]
> duplicated #3295

No, it's not. You have another issue. Did you tried updating? I had no issue with cmi until this version

**Comment by Zrips** [comment]
Fixed
