### ISSUE TITLE
/setwarp on an existing warp should update its location, not wipe it.

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#3585]
In essentials if you use /setwarp existingwarpname on a warp that already exists, it will JUST update its location, but in CMI it wipes it and creates it as a new warp, we have a /warp event that moves a lot, and having to go through the GUIs is a long process, we have setwarp already, lets slightly change how it works with existing warps.

**Comment by CloudeLecaw** [comment]
When i do setwarp it overrides the old on..

**Comment by Zrips** [comment]
Well interesting point, i can definitely update commands behavior and try to keep as much of old data as possible if warp already exists by provided name. 
Next update
