### ISSUE TITLE
Clean messages !- breaks \n combination.

### ISSUE THREAD

**Issue by kassadGLA** [Zrips/CMI#3586]
**Description of issue:**
---
Issue with command **cmi msg [playerName] !-[message]**
If message starts with **!** or **!-** then the **\n** symbol combination, which does a newline, stops working.
Examples:
**>cmi msg kassad aaa\nggg** result:
```
[sender->me] aaa
ggg
```
**>cmi msg kassad !aaa\nggg** or **>cmi msg kassad !-aaa\nggg** result:
```
aaa\nggg
```
---
**Cmi Version (using`/cmi version`): 8.7.0.2** 

**Server Type (Spigot/Paperspigot/etc): PaperSpigot** 

**Server Version (using `/ver`): git-Paper-370 (MC: 1.15.2)**

**Comment by Zrips** [comment]
Fixed with latest builds
