### ISSUE TITLE
/cmi rt making a GC lag

### ISSUE THREAD

**Issue by PhracKko** [Zrips/CMI#3589]
**Description of issue:**
is title

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```
[](https://www.youtube.com/watch?v=5QU6_jDAXOc&feature=youtu.be)

https://www.youtube.com/watch?v=5QU6_jDAXOc&feature=youtu.be
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################

```
https://pastebin.com/qQT9VQmp

**Cmi Version (using`/cmi version`):** 
 8.7.0.2

[13:44:15 INFO]: &
[13:44:15 INFO]: CMI plugin version: 8.7.0.2 BungeeCord  SqLite
[13:44:15 INFO]: Server: Paper(372) 1.15.2-R0.1-SNAPSHOT
[13:44:15 INFO]: Modules -> 51 enabled 0 disabled:
[13:44:15 INFO]: &

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 
[13:18:21 INFO]: This server is running Paper version git-Paper-372 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[13:18:21 INFO]: Checking version, please wait...
[13:18:23 INFO]: Previous version: git-Paper-354 (MC: 1.15.2)
**Relevant plugins (Delete if this isn't needed):**
![123](https://user-images.githubusercontent.com/61553558/85938107-dd4dce80-b944-11ea-8ca4-531ddac43bc8.png)

**Comment by Zrips** [comment]
If you have world which is not pregenerated then it might cause a lag spike until plugin finds suitable location which will require chunk generation to be done before it can check it.

**Comment by PhracKko** [comment]
> If you have world which is not pregenerated then it might cause a lag spike until plugin finds suitable location which will require chunk generation to be done before it can check it.

oh so Im doing wb fill  89.3%....

thank you
