### ISSUE TITLE
(Feature/Suggestion) Placeholder Within a placeholder

### ISSUE THREAD

**Issue by johnsoncui02** [Zrips/CMI#3590]
Hi I was wondering if I could fit a placeholder within a placeholder.

I want to use %cmi_random_[from]_[to]%

and I was wondering if I could do %cmi_random_[%placeholder2%]_[%placeholder3%]%

**Comment by Zrips** [comment]
%cmi_random_{%placeholder2%}_{%placeholder3%}%
