### ISSUE TITLE
Crash CMI 8.7.0.0

### ISSUE THREAD

**Issue by Meattekn** [Zrips/CMI#3592]
```
**[12:50:57] [Server thread/ERROR]: Could not pass event PlayerBedEnterEvent to CMI v8.7.0.0
You'd need to speak to CMI
Also, the stack trace is cut off, there is a JVM flag to tell it to dump more lines from what I recall**
```

CMI 8.7.0.0 (1.16.1)
Paper 1.16.1

Crash spammin in console!

**Comment by Zrips** [comment]
I cant fix issue if i dont have any actual information about it. Crash log or error log is needed or atleast to give some extra information related to player entering bed. Like night speed up options. Anyways, will close this ticket. Create new one with more information if you still have this issue.
