### ISSUE TITLE
Color codes not working in books

### ISSUE THREAD

**Issue by RispyCZ** [Zrips/CMI#3593]
**Description of issue:**
Color codes not working in books even if player has op or perms
**Cmi Version (using`/cmi version`):** 
8.7.0.2
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper 10 1.16.1-R0.1-SNAPSHOT

**Comment by BboyZeroOne** [comment]
I can agree with this. Permission does not appear in luckperm's permission list
![perm](https://user-images.githubusercontent.com/51330952/85950185-ef079400-b98d-11ea-8417-df8729af10a6.png)

**Comment by CloudeLecaw** [comment]
you mean cmi.colors.book.(color?)
same to anvil
cmi.colors.anvil.(color?)

**Comment by Zrips** [comment]
Colors have been disabled in 1.15 due to some issues with minecraft strange handling mechanics, i can tho re enable them with 1.16 as it seam to be working correctly now.
