### ISSUE TITLE
Hex color codes in nickname - chat don't reset message color (public chat)

### ISSUE THREAD

**Issue by hamcoremusic** [Zrips/CMI#3597]
**Description of issue:**
When using HEX code in a nickname, the chat message that follows copies the last HEX color.

Screenshot: http://prntscr.com/t7y64z

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
 GeneralFormat: '{prefix}&f{displayName}&7: &f{message}'
```

---

**Cmi Version (using`/cmi version`):** 
8.7.0.3
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.16.1-R0.1-SNAPSHOT

**Comment by hamcoremusic** [comment]
Looks like you need to use the HEX to reset the chat instead of &r. I didn't do it in the config but I added it to the end of my nickname. I used {#FFFFFF}.

**Comment by hamcoremusic** [comment]
Update: I added {#FFFFFF} into the `GeneralFormat: '{prefix}&f{displayName}&7: &f{message}'` and it still didn't work.

**Comment by hamcoremusic** [comment]
Updated ticket to latest CMI version (tested)

Example here: https://gfycat.com/BluePoliticalIberianbarbel

**Comment by hamcoremusic** [comment]
Issue might be coming from this bug: https://github.com/Zrips/CMI/issues/3610

**Comment by Zrips** [comment]
Will be fixed with next build

**Comment by hamcoremusic** [comment]
Looks like this is still an issue in 8.7.0.4.

Here is my config line: `GeneralFormat: '{prefix}&f{displayName}&7: &f{message}'`

Again it's taking the color of the nickname from /nick (I did `/nick {#00DFDF}HAMCORE`) and the following chat remained blue instead of changing to white. Only way of fixing it is adding white HEX to the end of it: {#FFFFFF}

**Comment by hamcoremusic** [comment]
Just saw the new update, I will test it later tonight.
