### ISSUE TITLE
%cmi_user_maxperm...% doens't work with lastest CMI

### ISSUE THREAD

**Issue by fhebuterne** [Zrips/CMI#3599]
**Description of issue:**
Hello,

With last CMI version and paper 1.16.1, %cmi_user_maxperm_[corePerm]_[defaultValue]% doens't work anymore in BossShopPro, it show directly in text (check my screenshot please). 

Could you fix this please ?

Sincerely,
Fabien

EDIT : It works in TAB Header (with TAB plugin) so i don't know if the issue is link with CMI or BossShopPro.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Issue screenshot : https://i.fabien-hebuterne.fr/X9G4Z2Wp_28-06-2020_18-54-34.png
```

---

**Cmi Version (using`/cmi version`):** 8.7.0.2

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot 1.16.1

**Server Version (using `/ver`):** git-Paper-10 (MC: 1.16.1)

**Comment by Zrips** [comment]
Make sure that you have working placeholderAPI plugin and that BossShopPro actually working as it should with 1.16 version, as placeholder is translated correctly and processed as it should. You can test it with /cmi placeholders parse %cmi_user_maxperm_cmi.test_1% or using /papi parse %cmi_user_maxperm_cmi.test_1% both return correct values, so its an issue with shop plugin.
