### ISSUE TITLE
CMI Elevator

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#36]
Just a small issue with /back. 

Using a elevator plugin (iron/diamond block to teleport up or down to another iron/diamond block) will change the /back to that spot. So if you go up stairs then /back it just puts you downstairs on the elevator block.

**Comment by LogGits** [comment]
/Back in CMI is set when a user teleports (PlayerTeleportEvent). Considering that the elevator plugin is teleporting the plugin up and down it is triggering the event and thus the back location is set. Im not too sure how this can be avoided. 

It could be possible if setting the /back location triggers an event. If that is done, the author of that plugin can simply hook into cmi and cancel the event of setting the back position.

Side note: A SetPlayersPreviousLocationEvent would be a very useful event. It could also be used for public/custom plugins that utilise teleporting and don't want to affect back locations.

**Comment by Kbryst** [comment]
Would there be a way to get that block elevator feature added to cmi?

One less plugin lol. All it has is configurable block used, distance between the blocks, and use sound.

**Comment by Ew9304** [comment]
Yup, this would be cool. Just with [UP] and [DOWN] signs :)

**Comment by LogGits** [comment]
Latest build.
