### ISSUE TITLE
SEVERE SAVE ERROR WHILE SAVING PLAYER DATA (DeathLocation)

### ISSUE THREAD

**Issue by Phoetrix** [Zrips/CMI#3601]
**Description of issue:**
Hi !

I got a very critical error with the database of CMI.
In column 'DeathLocation' in the 'CMI_users' table, some of my users are death in a deleted world called "dragon_box" so the critical error happend with these players and all datas are never saved for them.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
28.06 21:12:59 [Server] INFO [CMI]  SEVERE SAVE ERROR WHILE SAVING Metafysike PLAYER DATA (DeathLocation)
28.06 21:12:59 [Server] WARN java.lang.IllegalArgumentException: World unloaded
28.06 21:12:59 [Server] WARN at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
28.06 21:12:59 [Server] WARN at org.bukkit.Location.getWorld(Location.java:112)
28.06 21:12:59 [Server] WARN at com.Zrips.CMI.Containers.CMILocation.updateWorld(CMILocation.java:49)
28.06 21:12:59 [Server] WARN at com.Zrips.CMI.Containers.CMILocation.toString(CMILocation.java:125)
28.06 21:12:59 [Server] WARN at java.lang.String.valueOf(String.java:2994)
28.06 21:12:59 [Server] WARN at java.lang.StringBuilder.append(StringBuilder.java:131)
28.06 21:12:59 [Server] WARN at com.Zrips.CMI.PlayerManager.proccessForSaveField(PlayerManager.java:1332)
28.06 21:12:59 [Server] WARN at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:1116)
28.06 21:12:59 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:686)
28.06 21:12:59 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:395)
28.06 21:12:59 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:286)
28.06 21:12:59 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
28.06 21:12:59 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
28.06 21:12:59 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
28.06 21:12:59 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
28.06 21:12:59 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
28.06 21:12:59 [Server] WARN at java.lang.Thread.run(Thread.java:748)
28.06 21:12:59 [Server] WARN java.lang.IllegalArgumentException: World unloaded
28.06 21:12:59 [Server] WARN at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
28.06 21:12:59 [Server] WARN at org.bukkit.Location.getWorld(Location.java:112)
28.06 21:12:59 [Server] WARN at com.Zrips.CMI.Containers.CMILocation.updateWorld(CMILocation.java:49)
28.06 21:12:59 [Server] WARN at com.Zrips.CMI.Containers.CMILocation.toString(CMILocation.java:125)
28.06 21:12:59 [Server] WARN at java.lang.String.valueOf(String.java:2994)
28.06 21:12:59 [Server] WARN at java.lang.StringBuilder.append(StringBuilder.java:131)
28.06 21:12:59 [Server] WARN at com.Zrips.CMI.PlayerManager.proccessForSaveField(PlayerManager.java:1332)
28.06 21:12:59 [Server] WARN at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:1116)
28.06 21:12:59 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:686)
28.06 21:12:59 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:395)
28.06 21:12:59 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:286)
28.06 21:12:59 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
28.06 21:12:59 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
28.06 21:12:59 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
28.06 21:12:59 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
28.06 21:12:59 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
28.06 21:12:59 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

**Cmi Version (using`/cmi version`):** 
CMI: 8.7.0.2 MySQL
Server: Paper(350) 1.15.2-R0.1-SNAPSHOT
CMI economy: True Vault: 1.7.3-b(CMIEInjector) CMI Chat: False 
Modules -> 46 enabled 5 disabled: customMessages, firstJoinMessages, votifier, vanish, playerChatTag

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-350 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-332 (MC: 1.15.2)
You are 23 version(s) behind

**Comment by CloudeLecaw** [comment]
Ceitical error: world unloaded.

What else to say..

**Comment by Phoetrix** [comment]
What does this reply mean? This is not a problem that I can fix myself.

**I said it in my description of the issue.. The world when some players are dead has been deleted... (so the error 'world unloaded' is not even precise)**

I use a system where I delete some worlds to reset them (automatic reset system) so I really need a fix for this error because it happens everytime for players who are die in a reseted world then their datas are no longer registered until the next restart of the server.. :/

**Comment by CloudeLecaw** [comment]
and this is the problerm

the plugin tries to get date like for /back or /dback  command and others for for a world that does not  exists anymore.
it gets any entry for "Deletedworld" maybe u can ask the dev of the plugin that developed this

This is waht your doing:
- player plays in world1 - cmi take note like position and other that will be saved
- Player dies is world 1
- world gets deleted -> his deathpoint and lastt known cords are still this deleted world
- cmi tried to save the deathcord and maybe last backcord
- cmi sees this world does not exists anymore and cant use it for the command
- - cmi trows this issues because u deleted the world

its recomment for you to disable all loggings of positions and deathcords for cmi with your database to avoid this

there are tree possible ways:
1. the dev of your plugin waits a bit with  the worlddeleting so cmi can take the data before the world gets deleted
2. cmi finds a way to
3. you setup CMI not to log kords in the playerdatabse specially not the once for dback and back

**Comment by Phoetrix** [comment]
This is not the first ticket on which you propose solutions for me so thank you @CloudeLecaw :)

I use some features of CMI where the DeathLocation is used like /back /dback as you mentionned but also the compass boss bar and maybe others.
Of course this solution will solve my issue probably but it is a shame that I need to disable some cool features to avoid this error.

That's why I created this ticket, maybe @Zrips is able to ignore every location from a deleted/unloaded world and this will prevent for issues so don't need to disable some features

**Comment by CloudeLecaw** [comment]
maybe :)

**Comment by Zrips** [comment]
Will introduce some extra checks related to this issue to avoid errors or atleast to avoid failing to save data when we cant detect world which was saved before it was removed. Next update.
