### ISSUE TITLE
Head values not saving correctly in kits when updating

### ISSUE THREAD

**Issue by LoJoSho** [Zrips/CMI#3603]
**Description of issue:**

When upgrading from 1.15 -> 1.16, head values didn't save correctly.

---

```
https://hastebin.com/zirofekopa.shell
```

---

**Cmi Version (using`/cmi version`):** 

7.0.1

**Server Type (Spigot/Paperspigot/etc):** 

Spigot

**Server Version (using `/ver`):** 

Spigot 1.16.1

**Comment by CloudeLecaw** [comment]
have you tried compiling newest Spigotversion?
in the first SpigotVersions there was an issues with heads, also in the first Papers
They should be fixed now in both.

**Comment by LoJoSho** [comment]
Will try that now :)

**Comment by Zrips** [comment]
Should be resolved
