### ISSUE TITLE
Modded Item won't stay in kit after /cmi reload or server restart

### ISSUE THREAD

**Issue by Krosta8** [Zrips/CMI#3604]
**Description of issue:**
I am using CMI with Mohist (hybrid for paperspigot and forge).
I put a few modded items in a kit and it is giving me everything exactly, as it should, but when I do /cmi reload (or restart the server), one of the modded items dissapear from the kit. (Not all of the modded items, just one specific, every time).
I can see the kit saved correctly in kits.yml, but after the cmi reload or server restart, the item dissapeared.

The item, which is dissapearing is RESETUTILITIES_DARK_STONE_BRICK. Tried /cmi itemnbt on it - "Item does not contain any NBT data"

I also tried suggestion from mod on Discord server:
Added it to kits.yml and copy the file. then /stop the server, then open the yml file and make sure it's there, if not, then use that copy. Then start the server... The item dissappeared.

Tried to did more testing and it looks like, that the problem is with the name.
Modded item, which have "_" in the name, won't stay in the kit after reload or server restart.
Also found out, that with /cmi iteminfo, all modded items show this:
![image](https://user-images.githubusercontent.com/30801575/86005540-148bb080-ba15-11ea-826c-0ce45f7ce97b.png)

---

**CONFIG SECTION:**
https://gist.github.com/Krosta8/dc1f47dbb2885cec161bb003239b0f2c

---

**Cmi Version (using`/cmi version`):** 8.7.0.2

**Server Type (Spigot/Paperspigot/etc):** Mohist-paperspigot

**Server Version (using `/ver`):** Mohist version 1.12.2-310ebdb (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2847)

**Comment by CloudeLecaw** [comment]
have you tried compiling newest Spigotversion?
in the first SpigotVersions there was an issues with heads, also in the first Papers
They should be fixed now in both.

**Comment by Krosta8** [comment]
With your suggestion, I report this problem to Mohist aswell, maybe dev from Mohist can confirm that.
I can't do this by myself, never done this before.

**Comment by CloudeLecaw** [comment]
- you download on spigot the buildtools.jar file
-you create with an texteditor of your choice a batchfile (like.create.bat) in the same direcotry where you saved your buildtools.jar
- wrote this containt inside the batchfile with the texteditor and save it
```
java -jar BuildTools.jar --rev 1.16.1
pause
```
- execute the batchfile with doubleclick, a black window open where you will see many many stange things ;)
-now simply wait until the commandwindow tells you its done.
-  you find the latest spigot compile in the folder where you executed the batchfile

you can check how much colpiled versions your behind by using the command /ver
Specialy now at the beginning of 1.16.1 there are a few new build each day, later when most is stable  the intervall will be lesser

**Comment by Zrips** [comment]
CMI is not made to support modded servers, if something works, cool, but in general its made to support spigot/paperspigot/tuinity and similar builds/forks. Modded servers are to different for me to make compatibility with all of them.

**Comment by CloudeLecaw** [comment]
Lol i didnt saw he really is using forge. Well i could tell you before that cmi does not Support items created by Mods
Maybe one if the reason why many devs develop extra a plugin a secound time just for forge sponge etc..

**Comment by Irgendwer01** [comment]
@CloudeLecaw the  reason many ppl are using mohist over sponge is:
1) the compatibility of spongeforge with mods is damn bad
2) spongeforge is an API ontop of forge, I mean why an extra API ontop of it????
3) paper is definetly better written than spongeforge and the compatibility and performance of such forge bukkit hybrids is 1000 times better than spongeforge

**Comment by CloudeLecaw** [comment]
maybbe maybe but this does still not mean that CMI supports it
