### ISSUE TITLE
Final chat color is continued into text when using it in a nickname

### ISSUE THREAD

**Issue by KieranGateley** [Zrips/CMI#3608]
When using the custom colors in a nickname, the final one is carried through into chat, as shown in the screenshots attached. The color also appears to be applying until the first regular color code. The nickname was set as such `/nick {#55cdfc}C{#f7a8b8}el&fe{#f7a8b8}st{#55cdfc}e`
![chat](https://user-images.githubusercontent.com/6613271/86045993-597b0b80-ba44-11ea-825e-e17eb48692d1.png)

---

CMI: 8.7.0.2 SqLite
Server: Paper(21) 1.16.1-R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment]
Post your chatformat?
