### ISSUE TITLE
Toast Command Cause Error

### ISSUE THREAD

**Issue by Xuwznln** [Zrips/CMI#3611]
As the title says.

Console Error Log: https://pastebin.com/EjkBSHVG

CMI 8.7.0.1-8.7.0.3

Paper 1.16.1 Build19-26

**Comment by Zrips** [comment]
This originates from minecraft creating issue when serialising advancement. Cant really do anything about it until fix is issued.

**Comment by Zrips** [comment]
Ok, next update will have this one fixed. You might need to update spigot to latest build.
