### ISSUE TITLE
Colors bug 1.15.2

### ISSUE THREAD

**Issue by NineTown** [Zrips/CMI#3613]
**Description of issue:**

There is bad colors naming in /glow gui (see pic. 1)
And chat bug - if text start from next line there deafult &f color - but im using &7 (see pic. 2)

Pic. 1 - https://sun9-52.userapi.com/GZxMTAKzhYLwab8YZNvgLGYfgQxOCzijMvMXqA/XB_WurjD1sw.jpg
Pic. 2 - https://sun9-55.userapi.com/KehWtQ8lrrHNMvQ2Xio86_VC8Jj_RGkYjW8jXQ/6Xnv3fkXk3c.jpg

**Cmi Version (using`/cmi version`): 8.7.0.3** 

**Server Type (Spigot/Paperspigot/etc): PaperSpigot (SSSpigot fork)** 

**Server Version (using `/ver`): 1.15.2**

**Comment by CloudeLecaw** [comment]
dont worry, i thought thats how it has to be xD

u can click the colors..
maybe a Paperonly issues but with üaüer your just getting a white glwoing no matter what you choose by gui or command

**Comment by Zrips** [comment]
Will be fixed with next build
