### ISSUE TITLE
Developer Issue (Plugin conflict)

### ISSUE THREAD

**Issue by OnlyNoobDied** [Zrips/CMI#3615]
I am the author of a gadget plugin which the plugin will gives you an item to let you launch specific effects. However, several users reported to me that they can drag/move the gadget item into CMI menu. 

I made several changes in my event listener(InventoryClickEvent) to prevent player to move the gadget item but somehow server with CMI plugin can bypass it. I also change the event priority to Monitor but the issue still the same.

This issue also happens to armor slots.

You can refer to these two issues.
https://github.com/OnlyNoobDied/GadgetsMenu/issues/688
https://github.com/OnlyNoobDied/GadgetsMenu/issues/785

**Comment by Zrips** [comment]
Did you successfully reproduced this issue with latest CMI builds? Or maybe you know a way to reproduce it with a constant rate? I cant reproduce this issue currently on 1.16 server with latest versions of CMI and your plugin.
In general if InventoryClickEvent is canceled then its canceled, item will not move. So i don't know how you handle inventory clicks, but in general if you have player with open GUI of yours, then cancel event.

**Comment by OnlyNoobDied** [comment]
I will ask the users to try reproduce the issue with the latest build.

**Comment by Zrips** [comment]
And just noticed that i can move item from players head to inventory with /hat command which then prevents item from being moved anywhere else. Why arent you removing items in player inventory if they have ones which cant be moved? As you do detect them already, so why not simply remove them when they click on it?

**Comment by OnlyNoobDied** [comment]
Would you mind sending me a temporary premium access CMI plugin to let me test it? You can send the file thru email: yapzhenyie2014@gmail.com

**Comment by Zrips** [comment]
Give me your spigotmc name and i can add you to buyers list and you can test it properly

**Comment by OnlyNoobDied** [comment]
Username: yapzhenyie
Thanks a lot.

**Comment by Zrips** [comment]
Added, you can test it now

**Comment by OnlyNoobDied** [comment]
Received, thank you.
