### ISSUE TITLE
Config file lost comments - CMI 8.7.0.4

### ISSUE THREAD

**Issue by hamcoremusic** [Zrips/CMI#3616]
**Description of issue:**
The config.yml file now has no comments to describe the different config lines. 

---

Config: https://pastebin.com/RqY1bQ6n

---

**Cmi Version (using`/cmi version`):** 
8.7.0.4
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-1.16.1-27

**Comment by Zrips** [comment]
simple /cmi reload can fix this, but will have a look at it to avoid this in future.
