### ISSUE TITLE
Updates Messed Up

### ISSUE THREAD

**Issue by MothGirlMusic** [Zrips/CMI#3618]
![Bildschirmfoto 2020-06-30 um 14 03 11](https://user-images.githubusercontent.com/1746550/86160968-8da10b80-bada-11ea-96bd-79a8b1614a41.png)

**Comment by Zrips** [comment]
spigotmc might take some time until it updates its cache with correct plugin version. This message will disappear in time by itself. But will add some extra checks to make sure that its actually needs to be shown.
