### ISSUE TITLE
panimation stop isn't working

### ISSUE THREAD

**Issue by thecenters** [Zrips/CMI#3619]
If a player has multiple panimations on, then "/panimation stop" only applies to 1 of the animations, leaving the other particles still active.

Also, can a command like "/panimation stop target:thecenters" work? This way it can be executed as a server command without giving the player permission for panimation.

Using 8.7.0.5

**Comment by Zrips** [comment]
You can use **/cmi panimation stop Zrips** and it will stop particles on target player. Tested out and all particle effect related to player got disabled properly with one command. Something else might be an issue or those particles are not directly attached to the player. Actual panimation strings could help out in determining why its not working for you. But currently its not a bug i could fix.

**Comment by thecenters** [comment]
circle;effect:reddust;dur:9999;pitchc:5;part:5;offset:0,1,0;radius:1;yawc:5;color:255,0,0;target:[player]
circle;effect:reddust;dur:9999;pitchc:5;part:5;offset:0,1,0;radius:1;yawc:5;color:255,255,255;target:[player]
circle;effect:reddust;dur:9999;pitchc:5;part:5;offset:0,1,0;radius:1;yawc:5;color:0,255,0;target:[player]

I have a command that applies these three panimations all at once. using **/panimation stop thecenters** only 1 of the panimations actually stops.
