### ISSUE TITLE
MaxCommandChainLength set in config.yml

### ISSUE THREAD

**Issue by Cryper** [Zrips/CMI#3621]
**Description of feature/improvement request:**
It would be great if CMI will get a option to set the "maxCommandChainLength" instead of override it. I set it via gamerule to 1024. But i cant do more than 256.
So its impossible to execute a command thats longer, even with the console its not possible
---

**Comment by CloudeLecaw** [comment]
And you can execute vanilla command now with the. Lenght of 1024¿

**Comment by Cryper** [comment]
I can execute the vanilla command , but it work affect anything. If i set it to 1028 , the command cant be longer than 256.

**Comment by CloudeLecaw** [comment]
so its a minecraft bug itself ;)
There nothing Zrips could do here if he dont wanne write an extra "chace" that saved the 256 lines until the result is not equal 256 anymore and then print all out at once.

i had something like this once with a chatplugin and you where able this way to make long chats over 20000 words at once

**Comment by CloudeLecaw** [comment]
your interepreting thsi command gamerule also wrong way

> maxCommandChainLength | Determines the number at which the chain command block acts as a "chain". | 65536 | Int | Yes | Yes
> -- | -- | -- | -- | -- | --

This means u shorted the value allready ad by default its allready 65536, so if your amximium is still 256 then this just means this feature of minecraft itself does not work.
This also jsut wiorks for chains like in a command block used
like "If playerLvl2 then kill Player else heal player"  this is a chain that is meant with this gamerule

**Comment by Cryper** [comment]
I tried the long command on a vanilla spigot server. First i tried it with maxCommandChainLength 256 . And the command dont work, cause it was to long.
After that i changed maxCommandChainLength to 1028. And the command worked.  

I know that this is made for Commandblock etc. but if i enable CMI , the command block stops at 256 too. So CMI do override this
