### ISSUE TITLE
unknown dimension network id 

### ISSUE THREAD

**Issue by Drc-DEV** [Zrips/CMI#3622]
**Description of issue:**
Using CMI 8.7.0.5, I get this error when trying to login
![immagine](https://user-images.githubusercontent.com/33911680/86177684-59077100-bb27-11ea-8f6a-4e7ab78b7ae5.png)
Server: paper 1.15.2

**Comment by CloudeLecaw** [comment]
Thus dies not really look like a cmi Problem... Why you thinking cmi is creating thus issue? You trieded to login to a nit existing bungee World?
