### ISSUE TITLE
/give command not accepting spaces

### ISSUE THREAD

**Issue by trickman325** [Zrips/CMI#3624]
/give has stopped accepting spaces in name and lore for items making it very hard to give a custom item through commands

For example
_/give Trickman325 diamond_helmet {display:{Name:"\"Test name\"",Lore:["\"Test lore\""]},Enchantments:[{id:protection,lvl:4},{id:unbreaking,lvl:3}]}_
Will give a plain diamond helmet

but

_/give Trickman325 diamond_helmet {display:{Name:"\"Test_name\"",Lore:["\"Test_lore\""]},Enchantments:[{id:protection,lvl:4},{id:unbreaking,lvl:3}]}_
Will give the correct enchanted diamond helmet but the name and lore will have the underscores

**doing _/cmi give_ has the same output**

**Cmi Version (using`/cmi version`):** 8.7.0.2 (no note of being fixed in the newer versions)

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** Paper(372) 1.15.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Will fix it with next update
