### ISSUE TITLE
This is currently broken. witing for fix from spigot builds and colors chat

### ISSUE THREAD

**Issue by fidzhikovsky** [Zrips/CMI#3626]
**Description of issue or feature request:**

---

```
Spaming of chat "This is currently broken. witing for fix from spigot builds" to absolutely all the players on the server.
![image](https://user-images.githubusercontent.com/67680853/86216841-4b81d380-bb87-11ea-9c35-1aa017023e9d.png)
And Color in the chat no working, tab nice work but the chat only works at the beginning of the color.
![image](https://proxy.spigotmc.org/b77a32e3f4a7f3c0e587b25d898cbd2ca23af21e?url=https%3A%2F%2Fsun9-71.userapi.com%2Fa-pBsLtNbX8qUmNcKPylaWj5n3TZVzxmKACiqg%2Fb0doh5VIfTw.jpg)
```

**Cmi Version (using`/cmi version`):** last 8.7.0.5

**Server Type (Spigot/Paperspigot/etc):** Paper 27 1.16.1

**Server Version (using `/ver`):** 1.16.1

**Relevant plugins (Delete if this isn't needed):** 
![image](https://user-images.githubusercontent.com/67680853/86217386-132ec500-bb88-11ea-888a-2af227002c9d.png)

**Comment by CloudeLecaw** [comment]
one Question:

> Economy: For CMI economy to properly work you will need one of two solutions: 
> 1. Is to use recompiled Vault version from HERE which has direct support for CMI economy and will have best compatibility with other plugins. 
> 2. Use economy injector from HERE which will add CMI economy support to any Vault build.
> Both methods are valid but second one can have small issues with plugins which would tend to load straight after Vault loads and before injector himself. 
> P.S. Don’t forget to enable Economy in config file.

Why your using Vault 1.7.3 (the Zrips CMI Version) + CMI ijector?

The description tells us to use CMIInjector + official valut that is 1.7.2  or   just the Zrips Edited Version for CMI Vault 1.7.3   but not both at once. This may can created unaspected errors

**Comment by Zrips** [comment]
Toast message will be fixed with next version.
Chat colors will be updated with next version.

**Comment by fidzhikovsky** [comment]
> one Question:
> 
> > Economy: For CMI economy to properly work you will need one of two solutions:
> > 
> > 1. Is to use recompiled Vault version from HERE which has direct support for CMI economy and will have best compatibility with other plugins.
> > 2. Use economy injector from HERE which will add CMI economy support to any Vault build.
> >    Both methods are valid but second one can have small issues with plugins which would tend to load straight after Vault loads and before injector himself.
> >    P.S. Don’t forget to enable Economy in config file.
> 
> Why your using Vault 1.7.3 (the Zrips CMI Version) + CMI ijector?
> 
> The description tells us to use CMIInjector + official valut that is 1.7.2 or just the Zrips Edited Version for CMI Vault 1.7.3 but not both at once. This may can created unaspected errors

cmi enjector off in config.yml

**Comment by CloudeLecaw** [comment]
then you dont ened to list the plugin or u can even delet it because its not used and needed with version 1.7.3 ;)

**Comment by fidzhikovsky** [comment]
> then you dont ened to list the plugin or u can even delet it because its not used and needed with version 1.7.3 ;)

Yeah, I just forgot to do it...
