### ISSUE TITLE
Attached command !consume! shows unknown command message to players.

### ISSUE THREAD

**Issue by xRebellion** [Zrips/CMI#3629]
**Description of issue:**
Hello, it seems like items with !consume! option causes the player to have the "unknown command" message whenever they use the item. I tested it with !consume!;;!cc! <command>. The command still gets executed, but on the player side there's this unknown command.

---
![image](https://user-images.githubusercontent.com/32483348/86265831-866b2200-bbee-11ea-8b50-ae852581c9f0.png)
![image](https://user-images.githubusercontent.com/32483348/86265881-96830180-bbee-11ea-8053-0892e31d8f28.png)

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/32483348/86265921-a4d11d80-bbee-11ea-8d7d-cb5023d3a0e2.png)

**Comment by CloudeLecaw** [comment]
This is normal when you dont use the silent option.

**Comment by xRebellion** [comment]
The KeepInventory Replenished is intended, but the unknown command isn't. The unknown command is basically a modified spigot.yml : messages.unknown-command: '&7[&c!&7] &cUnknown Command!'

**Comment by CloudeLecaw** [comment]
Could you post the command you attached?

**Comment by xRebellion** [comment]
/cmi attachcommand !consume!;;asConsole! cki cooldown [playerName] refresh
Ah, it seems like the !consume! option is causing it. I'll update the issue title

**Comment by Zrips** [comment]
Will be fixed with next update
