### ISSUE TITLE
panimation stop isn't working (new details)

### ISSUE THREAD

**Issue by thecenters** [Zrips/CMI#3630]
circle;effect:reddust;dur:9999;pitchc:5;part:5;offset:0,1,0;radius:1;yawc:5;color:255,0,0;target:[player]
circle;effect:reddust;dur:9999;pitchc:5;part:5;offset:0,1,0;radius:1;yawc:5;color:255,255,255;target:[player]
circle;effect:reddust;dur:9999;pitchc:5;part:5;offset:0,1,0;radius:1;yawc:5;color:0,255,0;target:[player]

I have a command that applies these three panimations all at once. using **/panimation stop thecenters** only 1 of the panimations actually stops.

Seems like the stop command breaks down if a player has multiple panimations stacked

**Comment by Zrips** [comment]
Reproduced, will be fixed with next update
