### ISSUE TITLE
On join random teleport to random location

### ISSUE THREAD

**Issue by kieran737** [Zrips/CMI#3631]
**Question: **
Evening,

We are currently facing an issue where when a player joins the server they get teleported to a random location when you connect you can quickly see your last location then you're teleported, we have tried removing all other plugins and the problem still persists along with resetting the config files. We have also tried resetting the worlds can get the same result. Even when players join the nether world on rejoining they get teleported back to the overworld, the only thing that seems to resolve the issue is if we uninstall cmi from the server.

There is nothing in the console indicating a malfunction. 

We're running PaperMC build 34
Waterfall build 358
CMI version 8.7.0.6

Thanks in advance for any advice.

**Comment by Zrips** [comment]
First thing would be to temporary reset CMI files and check if issue persists. If not, then you have issue with some configuration. It could be event command file or something else. But some investigation is needed to determine whats going on exactly and why they are teleported.
