### ISSUE TITLE
Scan of invissible frames

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3632]
With the last Updates we got a wonderfull Feature. The abillity to make frames invissible. 

A little Problem may can accur afer some time. 
You or some admin may place 20 incisible itemframes but did nit attached some items to it. 
So noone Knows or sees the itemframes anymore. If the admin now take a look over after a while he has no good chance to find the frames anymore. A command extension would be nice. 

**/cmi itemframe scan (radius).** 

The command may could output a chatlist with all found hidden frames in the radius.
**_Nummer - Kords - Status_**   _-  (Nummer is a follow numer 1,2,3,4,5, Kords are the cordinations of the found frame, Status can be hidden in green or red (true/false))_
When clicking on a entry of the list, you would get teleported to the location. 
When SHIFT + Click an entry in the list it you would toggle the invissle status of the itemframe shown with the green or red word hidden)

Why this is needed? We need management to also find may forgotten or unwanted placed hidden itemframes,
we have no barriaritems thats Shows us all hidden itemframes while we are holding it in hand, like this happend with the barriarblock

**Comment by Zrips** [comment]
Added
