### ISSUE TITLE
Still color bug in 1.15.2

### ISSUE THREAD

**Issue by NineTown** [Zrips/CMI#3634]
Here a fixed bug (https://github.com/Zrips/CMI/issues/3613) in public chat with 2nd line text colors. But in private chat there is still same issue.

---

**Cmi Version (using`/cmi version`): 8.7.0.6** 

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): 1.15.2**

**Comment by CloudeLecaw** [comment]
have you checkt your config?

**Comment by Zrips** [comment]
Yea, extra small bug. Will issue fix for it.
