### ISSUE TITLE
AttachCommand not Working Correctly

### ISSUE THREAD

**Issue by Xuwznln** [Zrips/CMI#3635]
**Description of issue:**
When you use !left! or !right! tag without !cc!, the command is still issued on server side but not player side.
And I have a question, is updating item in player hand cause command to be issued if no tag like !left! is assigned?

CMI 8.7.0.6
Paper-1.16.1-27

**Comment by Zrips** [comment]
Confirmed. Will be fixed.
Updating items will not cause commands being performed. Only interaction or item consumption triggers commands if they fit defined criteria like left click
