### ISSUE TITLE
Clickable holograms

### ISSUE THREAD

**Issue by QuiquePineyro** [Zrips/CMI#3637]
**Description of issue:**

The clickable part of the holograms it doesn't work the version 1.15.2, I been testing it manny times resetting the files of CMI and doesn't work
---

---

**Cmi Version (using`/cmi version`):** 
8.7.0.6
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
Paper(374) 1.15.2

**Comment by Zrips** [comment]
I will need more information on this one. How did you tested it? Have you tried to generate buttons automatically? Have you tried to relog or restart server?

**Comment by QuiquePineyro** [comment]
I made this video showing how the clickable hologram doesn't work

https://streamable.com/enkp02

**Comment by Zrips** [comment]
Ok, reproduced. Should be fixed with next release
