### ISSUE TITLE
cmi checkcommand, no display translation

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#364]
**/cmi checkcommand** no display translation strings. See [screenshot](https://s19.postimg.cc/cpqmxrygz/javaw_2018-05-10_08-57-37-92.jpg).

_Version CMI: 7.7.5.0
Version Server: Spigot 1.12.2-R0.1-SNAPSHOT | CraftBukkit version git-Spigot-2086bb0-1988d7f (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)_

**Comment by LogGits** [comment]
By default if there is no translation, cmi will use english. Are you saying that the `/checkcommand` doesn't show any translation? Even if it is set in your config? Il mark this as a bug as i think thats what you are suggesting.

**Comment by Zrips** [comment]
Will be fixed with next build.
