### ISSUE TITLE
New /SETHOME locations are overwritten after the server restarts

### ISSUE THREAD

**Issue by AlekseyVideman** [Zrips/CMI#3642]
----------------------------

New players run the /sethome command and until the server restarts /home runs.
Probably CMI didn't save new /sethome locations?

-----------------------------

Data storage: SqLite

Cmi Version: 8.7.0.6

Server Type: Paper

Server version: 1.16.1

Log: https://pastebin.com/aYFfsnic

**Comment by Zrips** [comment]
By any chance you have some multiverse plugin and players have their homes set in custom world?

**Comment by AlekseyVideman** [comment]
> By any chance you have some multiverse plugin and players have their homes set in custom world?

No. Players play in the World

**Comment by Zrips** [comment]
I need some more information about this issue. As i cant reproduce it currently and saved homes remain as they should without any issues. How does your database look like? Do you have saved homes in there? Is this limited to everyone or only to few players? Does any other information about player is saved properly? And what commands was used exactly to create homes? like extra variables to define material, location slot number and similar

**Comment by AlekseyVideman** [comment]
CMI used the MySql data storage. The server moved to another hosting. I execute /migratedatabase and a message appeared in the console: "Successfully". CMI was switched to SqlLite. When the server was restarted, CMI output information about creating new cells to the sqlite database. But I already have a database with information about players...why did CMI replace everything with empty cells?

I made mysqldump and built a db from an sql file.

Old players have /homes, but new players don't.

Maybe CMI can't write new data because the database is corrupted?

Version: 8.7.0.7

**Comment by Zrips** [comment]
There should be some error messages in case it failed to saved data. But in general sqlite should not have issues when saving. Do new players get their data inserted into database? Like a new entry with their name and uuid and something extra about them, or are they missing all the data entirely?

**Comment by AlekseyVideman** [comment]
Playtime, money, UUID, and hunger statistics of players are recorded and saved after a reboot. I don't understand what's going on...

For some reason, only /home point is not saved

**Comment by Zrips** [comment]
Playtime is not really saved in database, atleast its not being used by CMI for any in game actions, its more for usage in a web page in case you need it, actual playtime is taken from player data file or player stats file depending which one you will pick in config file

**Comment by AlekseyVideman** [comment]
I exported the newly generated DB to sql format and did the same with the old DB file.

Instructions from the new database for creating tables and cells were copied to the old database,and everything worked.

/sethomes, playtime, id, are now saved.

The old table (it was generated after executing the /migratedatabase command) had this script for creating a "users" cell: https://pastebin.com/St2QckuM

And in the newly generated: https://pastebin.com/ffAxcL0C

Also, the old database did not have the "sqlite_sequence" table"

The problem is solved.
