### ISSUE TITLE
Still (really still) color bug in chat Minecraft 1.15.2

### ISSUE THREAD

**Issue by NineTown** [Zrips/CMI#3644]
https://github.com/Zrips/CMI/issues/3634 - Original

Im using hover messages.

Pic - https://sun9-12.userapi.com/4gEY_w6RmeigHqlwEySye7wOjBDmMQfy1gsopA/mstFDAIOjJg.jpg
---

**Cmi Version (using`/cmi version`): 8.7.0.7** 

**Server Type (Spigot/Paperspigot/etc): Paper (SSSpigot fork)** 

**Server Version (using `/ver`): 1.15.2**

**Comment by impmallet** [comment]
+1 I have this issue as well on 1.15.2 with CMI 8.7.0.7

**Comment by Zrips** [comment]
Give me exact text line you used

**Comment by impmallet** [comment]
> Give me exact text line you used

There is no exact text line... ANY private message that wraps to the 2nd line causes the 2nd line to lose the private message formatting.

If there are specifics you want from my config file, let me know.

**Comment by Fiks75** [comment]
Same problem https://imgur.com/wfgQfE4

**Comment by impmallet** [comment]
![image](https://user-images.githubusercontent.com/35946139/86526189-9b4dec80-be5e-11ea-9570-dca280d6bf94.png)

**Comment by Zrips** [comment]
Tested out with hover over enabled and without, tested with colorized text and without, tested with hex and old formats. Getting same results, entire line is colorized properly. 
I need your private message format and i guess you have ClickHoverMessages enabled in config file?

**Comment by Fiks75** [comment]
> Tested out with hover over enabled and without, tested with colorized text and without, tested with hex and old formats. Getting same results, entire line is colorized properly.
> I need your private message format and i guess you have ClickHoverMessages enabled in config file?

Yes. in config file ClickHoverMessages enabled. 
I set ClickHoverMessages false. It good work https://imgur.com/n1Bh3Zh
The problem in ClickHoverMessages.

**Comment by impmallet** [comment]
I was also able to alleviate the issue by disabling ClickHoverMessages.

I would like to also note that I discovered that this affects not just private messages, but any chat message that exceeds 1 line.

**Comment by Zrips** [comment]
Should be resolved with latest builds
