### ISSUE TITLE
[item] not working on latest version

### ISSUE THREAD

**Issue by kelvin-junilson** [Zrips/CMI#3646]
**Description of issue:**
When using [item], on any item it wouldn't show and will spit out an error instead

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://paste.md-5.net/siqegexinu.sql
```

---

**Cmi Version (using`/cmi version`):**  8.7.0.7

**Server Type (Spigot/Paperspigot/etc):**  PaperSpigot #375

**Server Version (using `/ver`):** 1.15.2

**Comment by Zrips** [comment]
Confirmed, and will be fixed.
