### ISSUE TITLE
Hard Crash Watchdog from CMI Teleportation Module

### ISSUE THREAD

**Issue by austin4195** [Zrips/CMI#3647]
**Description of issue:**

Server experienced a hard crash due to the watchdog shutting down the main thread. CMI Teleportation module appeared in the thread dump.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/VDn9GGaM
```
---

**Cmi Version (using`/cmi version`):** 8.7.0.6

**Server Type (Spigot/Paperspigot/etc):** 1.16.1

**Server Version (using `/ver`):** git-Paper-41 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Strange error, it seams to be related when CMI send basic API request to get a chunk. Anyways, will issue small change to the code to avoid this one in the future.
