### ISSUE TITLE
Request, language translation console messages

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#365]
This is a request to add strings that translate the output messages of the [console](https://pastebin.com/yp9c5Vtx).

_Version CMI:_ 7.7.4.0
_Version  Server:_ Spigot 1.12.2-R0.1-SNAPSHOT | CraftBukkit version git-Spigot-2086bb0-1988d7f (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
_Version Vault:_ 1.6.6-b67

**Comment by LogGits** [comment]
The whole reason for this addition is to help monitor CMI, its performance and help find issues. Therefore, we don't have any plans to allow the alteration of this unfortunately.
