### ISSUE TITLE
PAPI placeholders as a condition in specialized commands.

### ISSUE THREAD

**Issue by kassadGLA** [Zrips/CMI#3650]
Hello!
Suggestion:
Add opportunity to use PAPI placeholders as a condition in specialized commands.
```
 papi_%somePlaceholder%:[value][@][?][#]!
```

Best regards.

**Comment by CloudeLecaw** [comment]
whats the sense of having a placeholder as condidition to exectue a command?

**Comment by kassadGLA** [comment]
> 
> 
> whats the sense of having a placeholder as condidition to exectue a command?
> 
> cmi does not even support this for his own placeholders because it make no sense
> 
> what you tryig to do?maybe there is an other way to do what ou want

I will give an example:
Suppose I want to use a player level as a condition. And for the level system I use a third-party plugin. In this case, it is possible to obtain a player’s level only using the PAPI placeholder.

**Comment by Zrips** [comment]
check:[value1][==|>|>=|<|<=|!=][value2][?][#]!
I might have forgot to update page with this one... You can check conditions by numeric values or string type. So something like 
**check:%cmi_user_name%==Zrips?!** msg! [playerName] $1 |%cmi_user_itemcount_{cmi_iteminhand_type}%|
is a valid specialized command and will only be performed when players name is Zrips
