### ISSUE TITLE
Teleport Error

### ISSUE THREAD

**Issue by annemettean** [Zrips/CMI#3651]
**Description of issue:**
When you try to use tp commands through CMI. Nothing happen and you will not be teleported.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Console Error: https://pastebin.com/E0qUSCwJ
Ingame Error: https://pastebin.com/0mu0DqcS
```

---

**Cmi Version (using`/cmi version`):** 
8.7.0.9

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.13.2

**Comment by CloudeLecaw** [comment]
how you tried to get to this world?

**Comment by Zrips** [comment]
Should be resolved with next update
