### ISSUE TITLE
CMI Not Working MC:16.1 | CMI:8.7.0.9

### ISSUE THREAD

**Issue by JohnWalkerQ** [Zrips/CMI#3652]
**Description of issue:**
Plugin does not work. The command /cmi   does not work.

I downloaded the latest version off the plugin and also downloaded the api.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
05.07 01:02:58 [Server] WARN Legacy plugin CMI v7.1.3.0 does not specify an api-version.
05.07 01:02:54 [Server] WARN Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
05.07 01:02:53 [Server] ERROR Ambiguous plugin name `CMI' for files `plugins\CMIAPI7.6.2.0.jar' and `plugins\CMI8.7.0.9.jar' in `plugins'

```
---

**Cmi Version (using`/cmi version`): 8.7.0.9  | However it says it's loading 7.1.3.0 | Also it does not let me do /cmi version** 

**Server Type (Spigot/Paperspigot/etc): Paper 16.1** 

**Server Version (using `/ver`): git-paper 47, api version 1.16.1-R0.1-snapshot**

**Comment by dragontekgaming** [comment]
Why don't re remove CMIAPI1.6.2.0.jar and try to restart the server?

**Comment by Zrips** [comment]
Remove API plugin, its not for a live server, its for development, which by itself is quite outdated and i need to update it at some point. Only leave latest CMI jar file you downloaded from spigotmc site and it will work.
