### ISSUE TITLE
Custom item name bug

### ISSUE THREAD

**Issue by GothkittyGirl** [Zrips/CMI#3654]
is this a CMI issue? https://puu.sh/G3Lq9/143d117a52.png

[11:56 PM]
happens when player change worlds

---

**Cmi Version (using`/cmi version`):** 8.7.0.9

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** CraftBukkit version git-Spigot-ccb012a-b6a876b (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by CloudeLecaw** [comment]
No its an issues for some items after changing from 1.15.2 to 1.16.1 when some plugins where not up to date i also had this problem with some  items. 

Its no cmi problem and should not exist anymore (to new items) old once are not effected if you loaded or change the plugin from it after a 1.16.1 patch of the plugin 🥉 
We had the same problem to all of our Mailboxes and backpacks and also Travelgears. but after updating and restoring the data from backup all was fine.

**Comment by GothkittyGirl** [comment]
weird it still happening on my server and we just had a fresh wipe of all items.... ooooh wait the crate they have 1.15.2 items in them....... so i need to redo those items for them to be fixed as well?

**Comment by CloudeLecaw** [comment]
have u created this items with a plugin that is compatible for 1.16.1?
If yes you have to redo them

But there is a change not all of them broke after the plugin for creation is updated
some players where kind eough to listen not to touch or use items that might broke until the plugin for it is updated.
these item often have a change to survive (not if they took it in their enderchest :( )

**Comment by GothkittyGirl** [comment]
yes plugin is updated! i will redo those items now

**Comment by GothkittyGirl** [comment]
ok nope still doing it so i guess its not the plugin i thought it was?

**Comment by CloudeLecaw** [comment]
well what plugin your using?

Test something:
use No CMI just your plugin to creat the items
then go to nether by netherportal

Wht happens?

**Comment by GothkittyGirl** [comment]
well its mostly custom name/colored items from cmi and "advanced enchants" and "goldencrates" but seems to be fine going to the nether just some reason it randomly breaks names on things even things ive not renamed with color but have custom enchants on them. the enchants still work just the names are like the image above

**Comment by GothkittyGirl** [comment]
oh sorry meant to answer your test. 

created item with both named and unnamed: their fine
wen to the nether/creative even changed gamemode same world and still fine. so if it happens again ill be clueless as to what causes it

**Comment by GothkittyGirl** [comment]
Does seem to still happen just random when it will. ive looked all over and also removed CMI and waiting  a hour to see if it would happen again but with removing CMI it hasnt happened. So im thinking it might actaully be CMI doing it...

**Comment by Zrips** [comment]
Without some debugging at your end this cant really be solved as it seams to be specific issue in your specific situation with your specific setup. CMI in general doesn't modify item names or lore if not asked to do so. Lore itself seams to be from another plugin which controls special enchants. So it could be ether caused by that plugin or simply compatibility issue in general.
