### ISSUE TITLE
New &u tag for holograms not working on static holograms

### ISSUE THREAD

**Issue by kristouffe** [Zrips/CMI#3657]
**Description of issue:**
If you have a static hologram without any refresh interval, the color will never change. In the previous version of &u tag, the color changed even when it was a static hologram.
I don't know if this is how it should work or if it has become a bug.

**Cmi Version (using`/cmi version`):** 
CMI: 8.7.0.9
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-67 (MC: 1.16.1)

**Comment by Zrips** [comment]
This is how it should work. Holograms which doesn't have update will not update anything in holograms to save server resources. I could add some extra checks to force in auto updates in case there is a line with &u but then this would only create possibility for some one making line with some heavy duty placeholder and &u in front of it and then complaining why their server is running slow. Simply add update rate to your hologram and it will properly update it.
