### ISSUE TITLE
Recepe is buggy, it get reset every time player log in and ignore nbt data

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#3658]
**Description of issue:**
Evey time after server restart and player login, he get custom recipe removed and it even ignore nbt data

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
05.07 15:50:31 [Server] ERROR Tried to load unrecognized recipe: bukkit:ba5fbac5-b67a-49a3-94e8-c9c52345d0ce removed now.
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
8.7.0.9 Mysql

**Server Type (Spigot/Paperspigot/etc):** 
Papermc

**Server Version (using `/ver`):** 
353 15.2 (even older version has same bug, far back too 14.4)
Even new 68 1.16.1
**Relevant plugins (Delete if this isn't needed):**
CMI

**Comment by CloudeLecaw** [comment]
Recipe works fine, the result can have meta but for materials there just are vanilla (unmodified) materials like stone, redsrone, wheat, etc...

**Comment by broken1arrow** [comment]
> 
> 
> Recipe works fine, the result can have meta but for materials there just are vanilla (unmodified) materials like stone, redsrone, wheat, etc... This is writen also in the wiki so its no bug. If you setup other materials then they gerlt canillaitems aftee closing rhw custom recipe gui
> 
> For the workbench recipe it normal that Informationen you crafted it gets los after relog. This is a problem of Minecraft not of cmi itself, because the vanilla recipe managementnhas no plaxe foe. Custom recipe

Way not do it like some custom plugins? They have support for NBT and not lose custom recipe (we has bind it to custom hoppers and chest).

**Comment by CloudeLecaw** [comment]
Well can bei but thats the cmi Statement at the Moment, we need to life with this.

**Comment by broken1arrow** [comment]
> 
> 
> Well can bei but thats the cmi Statement at the Moment, we need to life with this.

Therefore we need bring it up to he some make the plugin.

**Comment by CloudeLecaw** [comment]
Requests for this are made allready ;)

**Comment by Zrips** [comment]
CMI Custom recipes uses vanilla recipe engine, so no support for custom NBT data at this moment.
