### ISSUE TITLE
%cmi_user_country_code% display country

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#366]
Placeholder %cmi_user_country_code% display country instead of country code, after updating to cmi 7.7.4.0

_Version CMI:_ 7.7.5.0
_Version  Server:_ Spigot 1.12.2-R0.1-SNAPSHOT | CraftBukkit version git-Spigot-2086bb0-1988d7f (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
_Version Vault:_ 1.6.6-b67

**Comment by LogGits** [comment]
This will be fixed in the next build.
