### ISSUE TITLE
Sign edit not working correctly in 1.16

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#3662]
**Description of issue:**

On 1.16, the sign text is being removed, so it's just like replacing a sign rather then an actual edit.

CMI 8.7.0.9 paper (44)

**Comment by Zrips** [comment]
Yea, known issue. No idea if its possible at this point to properly insert existing text into players UI throw packets or other means, but at this point minecraft doesn't include existing text from signs, which is strange at best.

**Comment by Zrips** [comment]
https://bugs.mojang.com/projects/MC/issues/MC-192263?filter=allopenissues
reported issue to Mojang and its client sided one. So we will have to wait for the fix.

**Comment by Sikatsu** [comment]
Alright, thank you for looking into this!
