### ISSUE TITLE
(8.7.0.9) (Bug) (1.16.1) [playerDisplayName] variable doesn`t work

### ISSUE THREAD

**Issue by AlekseyVideman** [Zrips/CMI#3664]
Hello!

Bug: "[playerDisplayName]' variable is not displayed in the /baltop, /list commands...

For example:
/BALTOP displays a list of player balances without player nicknames,
/AFK displays a message: "is AFK" ( user message..."broadcasts! [playerDisplayName]" )

Server: Paper, 1.16.1
CMI version: 8.7.0.9

**Comment by Zrips** [comment]
baltop and list shows correct player display name. Maybe you have 
```
DisplayName:
  # If you have 3rd party plugin changing players display name, set this to false
  Change: true
```
disabled which could cause some issues and would not update players display name with correct one.

**Comment by AlekseyVideman** [comment]
Can this be a permission plugin? For Example LuckPerms

I disabled it and still does not display the player's nickname:

"- - - - - Top-Balance ----- 
1. (here should be a nickname): 1,002,501. 00
2. : 850,200.00"

**Comment by AlekseyVideman** [comment]
It works. Sorry to bother you :)
