### ISSUE TITLE
IP bug with /checkaccount

### ISSUE THREAD

**Issue by Xiri99** [Zrips/CMI#3667]
**Description of issue:**
Whenever I do /checkaccount <name> a whole list pops up where it says that a ton of players is sharing the same IP.
Even with my account, it shows a list of users that are according to this plugin sharing my IP when they live on the other side of the planet.

---

**Cmi Version (using`/cmi version`):** 8.7.0.4

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper-374

**Relevant plugins (Delete if this isn't needed):** LiteBans, LuckPerms, CMI

![afbeelding](https://user-images.githubusercontent.com/64747336/86635944-04a33c00-bfd4-11ea-82cb-86120f6d5f1f.png)

**Comment by Zrips** [comment]
Which ip would that be exactly?

**Comment by Xiri99** [comment]
This is with any IP on our server, it doesn't matter what person you do after the /checkaccount command, it always ends up spamming

**Comment by Xiri99** [comment]
Just looked more into it and it seems like the IPs always start with 217. or 51.

**Comment by Zrips** [comment]
It could be that some internal software on your host changes their ip while CMI reads them and attaches to the player, in which case its the same one for everyone. In any case, we need to do some extra investigation here to get to the actual cause

**Comment by Xiri99** [comment]
Alright thanks
