### ISSUE TITLE
Placeholder for displaying online players without counting vanished players

### ISSUE THREAD

**Issue by diskotekastar** [Zrips/CMI#3671]
Hello,
I would need to know the placeholder to display the number of online players, but not to count the vanished players.
Using PlaceHolderAPI

Thank you Best regards,
Dj_Nejk

<img width="623" alt="tab" src="https://user-images.githubusercontent.com/61634734/86766870-6c489e00-c04b-11ea-83d6-de2e51ca9003.PNG">

**Comment by Zrips** [comment]
%server_online% provided by CMI excludes vanished players
