### ISSUE TITLE
/vanishedit isn't registered command

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3674]
**Description of issue:**
---

Hi, command /vanishedit isn't in tabcompletion and isn't registered even when I use this in alias:
```
  # /cmi vanishedit $1-
  /vanishedit: true
```
---

**Cmi Version (using`/cmi version`):** 8.7.0.10

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 1.16.1 paper 77

**Comment by Volgeop** [comment]
Or maybe is? Now I see it, wtf.

**Comment by CloudeLecaw** [comment]
Changing of alias.yml and new customalais are just seen in tab review after a restart. Cmi reload is not enough there.

**Comment by Volgeop** [comment]
But it was enabled long time before. But not it works... so I will close it.
