### ISSUE TITLE
CMI /SPAWN(GOT DELETED) /HOLOGRAM(NOT SHOWING) /PORTALS(INTERNAL ERROR OCCURED)

### ISSUE THREAD

**Issue by DarrienNN** [Zrips/CMI#3675]
**Question:  I Ask this thing alot time in discord and nobody want to reply why? (My Question: After i add these few plugin "Slimefun (Addons: Chestterminal/LiteXpansions/ExoticGarden) / advancedregionmarket / ultimateshops / mypet / holographicdisplays / and more << not all plugin got problem  but too much i lazy to check already. After i add these plugin my server cmi straight not working | What not working? > /spawn (Spawn point is not set!) /hologram (Not Showing) /portals (Internal Error Occured < I swear to god before i add these plugin my server cmi still working well**

SERVER START LOG https://pastebin.com/Mz4j1Cqt

Server using 1.16.1 Tuinity This problem on 1.15.2 also have same problem {Already try use spigot / paper, still same have error}

this problem already 3Months (I cant update anything in my server unless i use EssentialsX)

**Comment by DarrienNN** [comment]
https://imgur.com/a/ocn21LK

**Comment by CloudeLecaw** [comment]
Could you also post rhe console log?

**Comment by DarrienNN** [comment]
[Wed, 8. Jul 2020 12:37:32 SGT INFO] Darrien_ issued server command: /spawn
[Wed, 8. Jul 2020 12:37:32 SGT INFO] XiiaoOnE_ issued server command: /remove enchant
[Wed, 8. Jul 2020 12:37:35 SGT INFO] Darrien_ issued server command: /portals
[Wed, 8. Jul 2020 12:37:35 SGT ERROR] null

**Comment by Zrips** [comment]
Change your server from Tuinity to paperspigot. And i have no idea from where you got 1.16.1 tuinity as official version is still at 1.15.2
FYI you have multiple errors during startup which you need to check out. Other than this i can only see weird issue with your server where CMI loads before Multiverse-Core does which should not happen in a normal server as its been set to download after it, to allow for custom worlds to be loaded so we can recognize them as valid ones. 
Recommendation would be to switch to paperspigot and test this with CMI and multiverse-core alone to make sure that issue is gone or still persists, as currently i cant reproduce your issue.

**Comment by DarrienNN** [comment]
I get tuinity version from their discord + i said already in there i tried use paperspigot jar and problem still same

**Comment by DarrienNN** [comment]
and also new issues... 
> If staff type /commandspy and when i login my staff can see my password
before cannot

**Comment by Zrips** [comment]
@DarrienNN 
Negate cmi.command.commandspy.bypass for your staff members or include login command into blacklisted in config file under Command->Spy section
Will make some changes related to failure when loading holograms in world which doesn't exist, yet, to post pone some actions and do them when world is loaded. This should resolve issues your are having with that. Even tho CMI should be loaded after multiverse loads worlds, but it doesn't do in your case.

**Comment by DarrienNN** [comment]
FIXED thanks

**Comment by DarrienNN** [comment]
my fixed mean commandspy

**Comment by DarrienNN** [comment]
I tried run CMI only without multiverse core, but still have the problem

**Comment by DarrienNN** [comment]
i also running my server with paperspigot

**Comment by Zrips** [comment]
Och, just noticed that missing worlds have not been created by multiverse core but by Slimefun... Will add it as softdepend which will resolve that issue. But at same time will add some extra method which should be more universal method in loading holograms or portals when world is not loaded yet.

**Comment by DarrienNN** [comment]
So how do i need to fix this problem?

**Comment by DarrienNN** [comment]
Just now it worked perfectly, but after i add holographicdisplays then have problem again

**Comment by Zrips** [comment]
Wait until next release, will be posting new one shortly enough

**Comment by DarrienNN** [comment]
Ok i see

**Comment by DarrienNN** [comment]
Hi i saw cmi just updated is the new update will fix those issues?

**Comment by Zrips** [comment]
It should, i mean, i dont have your particular situation to test them on, but made some changes which allows us to have holograms, portals in custom worlds which dint existed during startup. And included slimefun which was main cause of those missing holograms to begin with. So it should be, test it and let me know how it goes

**Comment by DarrienNN** [comment]
It now working well, but now if i add holographicdisplay the problem will come again

**Comment by Zrips** [comment]
What do you mean exactly. After adding hologram with /cmi hologram command what happens exactly?

**Comment by DarrienNN** [comment]
I mean cmi hologram spawn portals work fine now but if i add HOLOGRAPHICDISPLAY then the problem will come again {spawn point is not set} {hologram not showing} {portals internal error occurred}

**Comment by DarrienNN** [comment]
Hmm

**Comment by Zrips** [comment]
if you are getting internal error messages i will need to see those console messages you are actually getting which will clarify whats going on. Without them i cant help you.
