### ISSUE TITLE
Chatcontrol errors (something with CMI lib)

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3677]
**Description of issue:**
Hi, I'm getting big errors in chatcontrol due to something related to CMI. 

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**

From console: https://hastebin.com/junatoteva.md
From ChatControl Error file: https://hastebin.com/beboqehemi.pl (btw it's so big to paste on pastebin whole)

---

**Cmi Version (using`/cmi version`):**  8.7.0.10

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  Paper 79 (1.16.1)

**Relevant plugins (Delete if this isn't needed):** ChatControl the newest beta version

**Comment by MaxWainer** [comment]
Try to use 8.6.6 version of ChatControl. You also need to report this bug to ChatControl support too.

**Comment by Volgeop** [comment]
I already did. And I'm beta testing version and I'm in contact with authors.... if I should switch to older version, then all of my configuration will broke.

**Comment by MaxWainer** [comment]
Try this on your test server (Like localhost or something similar). I think it's chatcontrolpro issue, not CMI

**Comment by Volgeop** [comment]
Author already fixed. https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro%E2%84%A2-format-and-filter-your-chat-1-7-10-1-16-1.10258/updates Thanks Zrips for helping.
