### ISSUE TITLE
[Request] Option to completely remove a vanilla recipe

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#368]
Similar to how these plugins do it:
https://www.spigotmc.org/resources/reciperemover.56216/
https://www.spigotmc.org/resources/reciperemover.54979/

**Comment by TheWranger** [comment]
Obviously, removing certain recipes can cause errors with advancements (I blocked hoppers using recipe remover and even though I had advancements completely disabled via spigot.yml, I still got a random advancement error code in console when I started the server up), so it's up to you if you really want to add something like that.

**Comment by MCTyler** [comment]
Seems better suited for WorldGuard?

**Comment by TheWranger** [comment]
How would I go about doing this with WorldGuard?

**Comment by MCTyler** [comment]
Just blacklist use of a recipe item. Suggestion....
```
Deny hopper
[hopper]
#ignore-perms=my.own.madeup.permission
#ignore-groups=admins,mods
on-use=deny,tell

**Comment by MCTyler** [comment]
So you need to edit the Spigot/Minecraft code? How would CMI achieve that? JC...

**Comment by TheWranger** [comment]
I linked two plugins that are capable of doing it.

**Comment by MCTyler** [comment]
Obviously my suggestions of disabling is not gonna work so I will quit replying. I honestly don't think he will add something that strips code out of Spigot like that. That Plugin has only 23 downloads ever.

**Comment by TheWranger** [comment]
Completely understandable.
