### ISSUE TITLE
CMI Error on load

### ISSUE THREAD

**Issue by haeiven** [Zrips/CMI#3684]
**Description of issue:**
CMI is having an error while loading in 1.8, this is happening since CMI 8.7.0.10

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://paste.soleria.eu/aweqohugid.md
```

---

**Cmi Version (using`/cmi version`):** 8.7.0.11

**Server Type (Spigot/Paperspigot/etc):** StellarSpigot 1.8.8

**Comment by Zrips** [comment]
Will be fixed with next release
