### ISSUE TITLE
Visual improvements to the "Perm:" part of /rankinfo

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#3685]
**Description of feature/improvement request:**
Improve how the "Perm:" part of /rankinfo looks as right now its a bit "buggy".
![Capture](https://user-images.githubusercontent.com/29175884/87082492-a74cfc00-c21a-11ea-9835-c775125418f6.PNG)
It is a bit hard sometimes to see the difference between the permissions you need to get so improvement is to add like a comma or a | between each perm text so instead of `Fly test Fly test` it would be `Fly test, Fly test` or `Fly test | Fly test`.

As you can see on the screenshot theres for some reason a double space between Perm: and the permissions due to the Perm: in the lang file being defined as " Perm: ", so basically just by default have perm as " Perm:". 

---
### Detailed explanation of what it should do, when and in what situation: ###
Should do what it says above.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Would make the Perm part of /rankinfo look better.

**Comment by Zrips** [comment]
Will do, with next update
