### ISSUE TITLE
Spawner percentage to break message

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3689]
**Description of feature/improvement request:**
Hi, maybe you could add message when players are mining spawn, then it shows them message for ex.: 'There's only 10% change on dropping this spawner".

---
### Detailed explanation of what it should do, when and in what situation: ###
When will player mine spawner it should show him message that he doesn't have 100% change to drop spawner, but for ex. just 10%. Depens on     BaseDropChance: 10 in config.

### Basic explanation as to why this feature is needed and/or useful to have: ###
It would be useful, because players think that they can't drop spawners and they don't know that there's something like "change" for dropping. If they won't drop it for the first time, they think, that spawners can't be dropped. If there will be message, they will know how big is chance etc.

**Comment by CloudeLecaw** [comment]
what kind of interactions would this be?
It would need an Event like LookingAt.Spawner

if you implemnt this? you can also do these for the beenstocks and beehives?
Looking at that is telling the fill value so you dont need to click it...

looking at furnaces to see current burning state...
looking at brewstand to see current brewing state.

well...someone more ideas where this would be usefull?

**Comment by Volgeop** [comment]
Yeah, it would be nice if you just could look at them. But atleast maybe when you hit it by pickaxe?

**Comment by CloudeLecaw** [comment]
when you hit by pickaxe - diamond - eff5.. what you think how long it would take before it would breake? 10ms? ;)
and rightclick... since MC has the secound had on rightclicks this can be an option but not if you have plaveable items in your secound hand ;3

**Comment by Zrips** [comment]
Currently spawner is dropped by more or less fixed rate when you define it in config file by setting drop change in general. We could print out that information when you click on spawner, but it would simply show same value taken from config file.

**Comment by Volgeop** [comment]
Yeah, that's enough @Zrips . And couldn't be printed somehow better also while mining and not so annoyingly?

**Comment by CloudeLecaw** [comment]
Annonyly? Your haveto break 100 of spawner ls a day? :P

**Comment by Volgeop** [comment]
If I have 5% chance, players can main it very often... it will be good to make it as actionbar message for example.

**Comment by Volgeop** [comment]
Hi, how it looks @Zrips ?

**Comment by Volgeop** [comment]
Could it be added as soon as possible, for ex. this week in some build?

**Comment by CloudeLecaw** [comment]
Maybe this whould take a while. There are million other things to look at and also to fix. And belive me, you Feature will not added be fast by asking each week for it 👍  also Zrips just said "he could do something but he never said he will add it. Could and do are two different things ;)

**Comment by Zrips** [comment]
Will do some improvements on this system, as it seams to be causing some confusion from time to time.
