### ISSUE TITLE
Some bugs with /tpa and /back

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#369]
Cmi Version: 7.7.6.0
Server Type : paper

Players have reported that sometimes when they do /back or accept a /tpa request they end up above or below the target location. I've had players somehow port into their own blaze grinder (which was above their mark) and die.

I just updated to this version this morning and started getting these reports.

**Comment by LogGits** [comment]
Can confirm I'm also having this issue

**Comment by Kbryst** [comment]
It seems to be slabs. Like any type. From what I've been told.

**Comment by Zrips** [comment]
isint this got fixed at some point? If its still an issue, reopen issue ticket
