### ISSUE TITLE
Kicking players while sit

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3690]
**Description of issue:**
---
Hi, sometimes when players sit for ex. on stairs etc. then they're kicked. It's probably due to allow-flight: false in server properties, but it shouldn't be enabled probably and players shouldn't be kicked for floating after sitting.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[12:14:57 WARN]: FixBixCZ was kicked for floating too long!
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
This in server properties could solve it, but I think it's dangerous due to cheaters.
```
allow-flight=true
```

---

**Cmi Version (using`/cmi version`):**   8.7.0.11

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  : 82, 1.16.1

**Comment by CloudeLecaw** [comment]
interesting we are sitting a few hours sometimes on the server and never got kicked until now...
maybe a paper issues? (wrong meassuring of what velocity? maybe false messuring fpr false/possitive of an anticheat plugin?)

**Comment by Volgeop** [comment]
You have to probably spam sitting on multiple stairs. It kicked my player already 3* for a while.

**Comment by CloudeLecaw** [comment]
hm at the moment no spam here (spigot latest 1.16.1) when someone sit 🥉 
Sorry i cant reprduce this, maybe Zrips has an idea

**Comment by Volgeop** [comment]
It's maybe with combination of Brewery plugin. I discovered it happens when players are sitting on barrels (just sometimes).... but they normally sit on stairs there. This is how barrels look https://imgur.com/undefined.

**Comment by Zrips** [comment]
CMI simply puts player on top of armorstand when he sits. This is basic entity mounting mechanics. You will need to retest this one and check if by any chance armor stand is not being removed by another plugin which could cause some issues with that. Other than this, it should not happen in normal situations.
