### ISSUE TITLE
"&" colour code replacing issues

### ISSUE THREAD

**Issue by Harveyplays02** [Zrips/CMI#3696]
**Description of issue:**
Any chat message sent by CMI seems to have trouble replacing `&` colour codes in certain scenarios. An example is below:

**Location:**
config.yml -> Chat.GeneralFormat
**String:**
`&8«&6S&8» %cmi_user_display_name%&r %cmi_user_meta_chatcolor%%cmi_user_meta_isbold%%cmi_user_meta_isitalic%%cmi_user_meta_ismagic%%cmi_user_meta_isstrike%%cmi_user_meta_isuline%{message}`
**Expected Outcome (returned with `/papi parse me <exactly the same string as locale line above>`):**
![image](https://user-images.githubusercontent.com/40532510/87210900-258aca80-c30f-11ea-95c8-0f446feedf2a.png)
**Actual Outcome:**
![image](https://user-images.githubusercontent.com/40532510/87210766-b57c4480-c30e-11ea-9beb-b3d6588bd5b3.png)

**It seems like there's a few issues:**
1. If a string is followed by an `&r` it will replace the previous whole word that isn't a special character with reset format?
2. Randomly replaces any modifiers in chat to not exist at all? (Not sure about this one. All of those usermeta placeholders are cleared if not used, and if they are used, it contains a colour code or modifier and nothing else. It's basically just a bodged chatcolour plugin rather than using a plugin just for chat formatting for donators, staff, etc).
3. There may be more issues, however I haven't found any more than the current 2.

---

**Cmi Version (using`/cmi version`):** 8.7.0.11

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper 86 1.16.1

**Relevant plugins:** LuckPerms (latest build), Vault (latest CMI built version from Spigot homepage), PlaceholderAPI (2.10.6)

**Comment by Zrips** [comment]
Could you give me exact text players display name and text you used? As now its hard to understand from your examples where prefix ends and actual message starts

**Comment by Harveyplays02** [comment]
Sure:
**Prefix:** `&8«&6&lServer Manager&8» &6&l `
**NickName:** `&4&o&lH&6&o&la&e&o&lr&2&o&lv&3&o&le&7&o&ly`
**Suffix:** ` &8«&6&lTesting Multiple Words&8»`
**Chat Colour:** `&6&l&o`
**Whole Chat Line:** `&8«&6S&8» &8«&6&lServer Manager&8» &6&l &4&o&lH&6&o&la&e&o&lr&2&o&lv&3&o&le&7&o&ly &8«&6&lTesting Multiple Words&8»&r &6&l&oTest`

**Comment by Zrips** [comment]
Ok, reproduced, should be fixed with next version
