### ISSUE TITLE
/sethome [name of home] tnt -p prints "An internal error"

### ISSUE THREAD

**Issue by iamtheRichie** [Zrips/CMI#3697]
**Description of issue:**

When trying to create a private home with a TNT as the icon, the following error appears on the console. inGame gets "An internal error..."

The command is: /sethome [name of home] tnt -p

Whether capitalized or not, the error only occurs with TNT.

Sincerely, Richie

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
[https://pastebin.com/1Qqw7LGv](https://pastebin.com/1Qqw7LGv)

---

**Cmi Version (using`/cmi version`):** 8.7.0.11

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):**  git-Paper-374 (MC: 1.15.2)

**Comment by Zrips** [comment]
Seams to be issue while having player with name of tnt which is being used as source location while not having correct logout location saved for this player. Will make it to prioritize material name over player name which will resolve your issue here
