### ISSUE TITLE
Use EntityBlockStorage.getMaxEntities() instead of the const int 3 for Bee Hive Handle

### ISSUE THREAD

**Issue by kn-km** [Zrips/CMI#3698]
**Description of issue:**

![Z02OQ2}9174(A8UVA{F Z8V](https://user-images.githubusercontent.com/13903138/87220262-ebfca280-c394-11ea-9c32-c7f2b5002c1d.png)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```
none
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
8.7.0.11
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot 1.16.1
**Server Version (using `/ver`):** 
 Paper version git-Paper-86 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):**
none

**Comment by Zrips** [comment]
Well first of all, not a bug, its more feature enchantment. Second, this only works with 1.16 servers as 1.15 doesn't have this method. And third, well, will actually change current behavior to make it work with dynamic max bee count. Anyways, thanks for pointing this one out, dint even know that it could have more than preset max amount.
