### ISSUE TITLE
removeuser

### ISSUE THREAD

**Issue by HiJackerRZ** [Zrips/CMI#3700]
**Description of issue:**

A player god banned and now I can't unban him! It apears in banlist but when i do /unban player is says that player is not banned! Player can't join the server!
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## https://hastebin.com/olobekivoc.md ##
######################
```

---

**Cmi Version (using`8.`):** 

**Server Type (Paperspigot):** 

**Server Version (using `1.16.1`):**

**Comment by CloudeLecaw** [comment]
If he ia not listed, you can try the vanilla /padon command to unban him, have you tried this?

**Comment by HiJackerRZ** [comment]
Yes! Not working

dum., 12 iul. 2020, 13:42 CloudeLecaw <notifications@github.com> a scris:

**Comment by CloudeLecaw** [comment]
Then they ts not cmis fault. Cmi is using the banlist if vanilla too. It has no extra banlist. So if the vanilla unban pardon does not work it means yout server or one of your plugins creating this issues. There is no reason for cmi blocking playerlogin. Cmi dies not have this Feature. You may cwn check the ipbanfile too? Maybe he was ipbannee...

**Comment by HiJackerRZ** [comment]
I have deleted all the ban list! It worked when i did that! Anyway I recive
that error when i do removeuser

dum., 12 iul. 2020, 13:52 CloudeLecaw <notifications@github.com> a scris:

**Comment by CloudeLecaw** [comment]
But remove user diea nit ban...

**Comment by Zrips** [comment]
As error indicates and what actual command help page says, you need to use UUID and not player name. This is security measures to avoid deleting some one elses data by name which would be the same as some one elses with different uuid.
