### ISSUE TITLE
Open Armorstand Edit GUI By API

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#3704]
**Description of feature/improvement request:**
Can open armorstand gui for player by CMI API.
Like openArmorstandGUI(Player, ArmorStand)

### Basic explanation as to why this feature is needed and/or useful to have: ###
I need to control which armorstand player can edit.

**Comment by CloudeLecaw** [comment]
So you want to know the Event that is fired when the gui opens right?

**Comment by coco0325** [comment]
I don't, I just want to open a gui for the player with the specific armorstand.

**Comment by CloudeLecaw** [comment]
But Armorstand are not bound to any player, this would need a database for saving all amorstands and their owners

**Comment by Zrips** [comment]
CMI.getInstance().getArmorStandManager().openEditor(player, armorStand, true);
