### ISSUE TITLE
CheckForNameChange isnt triggering only when they change their name, it triggers every time they log in

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#3707]
Paper 1.12.2
CMI 8.7.1.1

CheckForNameChange does not trigger only when someone changes their name, it triggers the command every single time someone logs in.

It should only trigger the command IF someone has changed their username since their last login (If they have logged in before)

**Comment by Zrips** [comment]
Well good point, will make those adjustments.
