### ISSUE TITLE
[Request] System to block AFK Fishing

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#371]
Implement a system to block users from automatically fishing while they are afk, threw the use of AFK machines or hacked clients. A simple way to do this would be to force players to move X blocks and change their angle slightly after X fishing sessions.
A configurable system like this is what I'm talking about:
https://www.spigotmc.org/resources/noafkfishing.29634/

**Comment by LogGits** [comment]
Great suggestion. Unfortunately cmi already has this feature. Look inside the afk section of the config relating to smart interact and make sure its enabled.

**Comment by TheWranger** [comment]
I don't think you understand what I mean.
`SmartInteractCheck` stops players from bypassing the afk check by fishing, but what I want is a system that stops players from using machines to continuously fish in the same spot without doing anything.

**Comment by CloudeLecaw** [comment]
great i idea, i also use an AntiAFKFishing Plugin that Forces Players to move X blocks (config) to be able to use the fishingrod aggain, after they catched something
[NoAFKFishing+](https://www.spigotmc.org/resources/noafkfishing.29634/)
