### ISSUE TITLE
Bossbar Compass duplicating

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#3710]
**Description of issue:**
The bossbar compass gets put up ~5 times when joining the server (and if you don't move for a bit and then come back), however they don't always go away. Sometimes they all do sometimes none do sometimes only a few do.
https://imgur.com/Bdoge29
https://imgur.com/h70x9zV
---

---

**Cmi Version (using`/cmi version`):** 
8.7.1.1
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper-89 1.16.1

**Comment by Zrips** [comment]
Should be resolved with next update, hopefully.
