### ISSUE TITLE
The 'a' modifier in /cmi give no longer working.

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#3714]
The 'a' modifier in the `/cmi give` command doesn't seem to be working on 1.16.1. Even the example on the wiki, `/cmi give sponge a maxhealth:5:mainhand` currently just gives a plain old sponge.

We've been using these for some OP rewards, specifically an example of one we use:
`cmi give [playerName] elytra 1 n &8Krillitane_Wings e protection:4,mending:1,unbreaking:3 a armorToughness:2:chest,armor:8:chest l &5Freshly_Oiled! l &5Belongs_to:_&r%cmi_user_nickname%`
Works perfectly for everything except for the armor modifier. This was working in 1.15.2, not sure about in previous 1.16.1 builds -- only just noticed it tonight when a player tried to claim the reward and complained about it.

Thanks! :)

No errors in console when running the command.

**Cmi Version (using`/cmi version`):** 8.7.1.1

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-c3a49df-b0c6dfe

**Comment by Zrips** [comment]
As of testing all seams to be working as before. Default `/cmi give sponge a maxhealth:5:mainhand` worked out and your example give correct item with correct attributes. Could have been temporary issue with minecraft itself.

**Comment by mercurialmusic** [comment]
Maybe this is turning into a question then. I'm still not able to get this to work, but now it prints this in console, which it either didn't before or I missed it:

```
> [23:02:39] [Server thread/INFO]: CesarMC13 issued server command: /cmi give CesarMC13 sponge a maxhealth:5:mainhand
> [23:02:39] [Server thread/WARN]: Unable to create attribute: null
```

Is there some setting that could be interfering? I don't have anything else that alters items or attributes that I know of. 

Now on CMI 8.7.3.4 and git-Spigot-0509002-7c03d25.

**Comment by Zrips** [comment]
Ok, as of testing, this looks to only be issue when using spigot. You can switch to paperspigot which doesn't have this issue.
Will do some investigation why its failing on their system, but cant promise that it will get fixed on it.

**Comment by mercurialmusic** [comment]
Lol. I've been saying for years that I refuse to switch to Paper. If you say to do it, I will trust you.
