### ISSUE TITLE
Players able to interact with "chair" armorstands with /armorstand near

### ISSUE THREAD

**Issue by Harveyplays02** [Zrips/CMI#3716]
**Description of issue:**
When sitting down (either by using `/sit` or actually right clicking a stair, carpet, etc), people are able to use /armorstand near on the armour stand they're sat on, and are able to modify it. Not really sure if this is possible to fix?

---

**Cmi Version (using`/cmi version`):** 8.7.1.1

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** Paper 1.16.1 Build 90

**Comment by Zrips** [comment]
Will get fixed with next build
