### ISSUE TITLE
Add permission node for itemname with color code restriction

### ISSUE THREAD

**Issue by johnsoncui02** [Zrips/CMI#3718]
basically add a permission node for cmi.command.itemname

but with something like cmi.command.itemname.nocolor

to restrict players from using color codes when renamining items. They would all essentially be defaulted to white colors.

**Comment by CloudeLecaw** [comment]
Without the anvil color permissions they are not allowed to use colors on anvil

**Comment by johnsoncui02** [comment]
I'm referring to the command /itemname specifically.
