### ISSUE TITLE
[Request] Option to automatically hide item attributes

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#372]
Similar to how this plugin does it:
https://www.spigotmc.org/resources/attributehider.10604/

**Comment by LogGits** [comment]
Are you talking about `/cmi hideflags [playerName] hide_attributes` ? check out `/cmi hideflags [playerName] <presstab it will tell you all the available options>`

**Comment by TheWranger** [comment]
No, I want a system that when enabled, automatically hides attributes on certain items (whatevers set in the config), without having to run any commands.

**Comment by TheWranger** [comment]
I changed my mind, I don't think CMI will benefit overall from adding this.
