### ISSUE TITLE
Chat colors broken since update 8.7.2.0

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#3722]
CMI-Version:8.7.2.1

since the update: 8.7.2.0 the chat format has been broken. the text in the chat has the same color as the prefix. Although other values are entered in the config.

  GeneralFormat: '{prefix}{displayName}&f: &r{message}'

![grafik](https://user-images.githubusercontent.com/35557302/87458565-77cb3480-c60a-11ea-85c0-9d976d5aa7cf.png)

**Comment by Zrips** [comment]
Should be resolved with .2 version
