### ISSUE TITLE
Crash instantly with UltimateStacker when rendering in the holograms

### ISSUE THREAD

**Issue by sirmuskrat** [Zrips/CMI#3723]
**When you render in a stacked Spawner of UltimateStacker it insta crashes. Also /cmi fixchunk instantly crashes. If possible finding a fix would do wonders for our network!**

---
Error at bottom (repeats rapidly)
https://pastebin.com/Nbkm8Zga

---

**Cmi Version (using`/cmi version`):** 
Latest and 8.7.2.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot versions 8-,84,90,91 
**Server Version (using `/ver`):** 
git-paper-91 1.16.1
**Relevant plugins (Delete if this isn't needed):**
UltimateStacker and CMI

**Comment by Zrips** [comment]
Well first of all you have issue with plugins\ConsoleSpamFix\config.yml file
Hard to say what exactly is going on, but in general when you perform this command there should not be any players online and even better approach would be to disable any other plugin while CMI scans throw chunks. As now it seams to encountered chunk map lock.
Will make some small changes, should help out .

**Comment by sirmuskrat** [comment]
I know you closed this, but it's not only when I'm looking through fix chunk. When the server runs CMI and UltimateStacker in isolation, just those plugins, nothing else. It crashes when players render those chunks with UltimateStacker things in them. I was using /cmi fixchunk to load/test the crashes more efficiently

**Comment by sirmuskrat** [comment]
Also the issue with consolespamfix is something I mistyped in the config. Fixing later. That was not a variable when we were testing the crashes. I removed all plugins and isolated just CMI and UltimateStacker as the issue duo
