### ISSUE TITLE
Custom Text <URL> tag adds extra http://

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#3724]
**Description of issue:**
I realize this may not be a bug and might have been intended as helpful, but my Discord blew up tonight after the update to CMI 8.7.2.1 (I'm guessing from 8.7.2.0 since I skipped that one) about all of our links suddenly being "broken" in game. Turns out CMI is adding an extra `http://` in front of all links that use the `<URL>` custom text tag as shown here: http://prntscr.com/thy0sx.

Example custom text here:
https://gist.github.com/mercurialmusic/eed38b0f49ecd340c4fcc3658c233e93

The issue persists in CMI 8.7.2.3. While I can simply remove the prefixes from my many links to wiki articles, vote sites, etc. (and I did with some in the mean time), I always prefer to use the SSL certificates I worked so hard to set up as it's way more secure. I also think automatically including that prefix might be confusing for those of us above the age of, say, 12, who know how to format a URL. =p I would definitely appreciate a reversion to the previous (and less confusing) behavior.

---

**Cmi Version (using`/cmi version`):** 8.7.2.3

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-05da6fa-b0c6dfe

**Comment by Zrips** [comment]
Somewhat bug, will fix this one with next update
