### ISSUE TITLE
Alias check: functionality does not appear to work with boolean placeholders

### ISSUE THREAD

**Issue by theconezone** [Zrips/CMI#3725]
It does not appear to currently be possible to check boolean placeholders in custom aliases using the check: functionality. I do not know if I am doing this wrong, or if it's some kind of issue.

For instance, the following will never run:

check:%cmi_user_inpvp%==true! msg! [playerName] You are in pvp.

I have also tried the following:

check:%cmi_user_inpvp%==True! msg! [playerName] You are in pvp.
check:%cmi_user_inpvp%! msg! [playerName] You are in pvp.
check:%cmi_user_inpvp%==1! msg! [playerName] You are in pvp.

This obviously works, but is useless because %cmi_user_inpvp% can never be True:

check:%cmi_user_inpvp%!=True! msg! [playerName] You are not in pvp.

This functionality seems pretty important, because it is currently the only way to detect if a player is actively in pvp via aliases (without some kind of crazy hackery using events and permissions/metadata).

---

**Cmi Version (using`/cmi version`):** CMI: 8.7.2.3 SqLite

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** git-Paper-"94315dad" (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
issue would be with the fact that default pvp state output contains colors. So you can ether update that and include correct color codes or simply wait until next version where i will exclude color codes before comparing if possible.

**Comment by theconezone** [comment]
I believe I will wait, thank you.
