### ISSUE TITLE
[Minor] ToggleShiftEdit Preferences Don't Persist After Restart

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#3726]
**Description of issue:**
Probably related to changes made with #3676, and I understand there's an underlying Minecraft issue as well, but using `/cmi toggleshiftedit` does **not** save the toggle preference over a restart. Seems to be fine over a simple relog, but a restart resets it, which is super weird.

---

**Cmi Version (using`/cmi version`):** 8.7.2.3 (& CMIB1.0.0.4 if it matters)

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-05da6fa-b0c6dfe

**Comment by mercurialmusic** [comment]
Sorry for all the reports lately. New MC versions are so much fun!

**Comment by Zrips** [comment]
Reproduced, will be fixed with next version
