### ISSUE TITLE
Error when player does /tpa

### ISSUE THREAD

**Issue by YTMrSnipa** [Zrips/CMI#3729]
>.... [07:19:23 INFO]: kubikula8888 issued server command: /tpa PsychoKid>.... [07:19:23 ERROR]: Parameters:net.minecraft.server.v1_16_R1.PacketPlayOutChat@d3f9ed6[a=TextComponent{text='', siblings=[TextComponent{text='', siblings=[TextComponent{text='Request sent to PsychoKid', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='', siblings=[TextComponent{text=' [X] ', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=gold, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=ClickEvent{action=RUN_COMMAND, value='/cmi tpa PsychoKid -cancel-'}, hoverEvent=HoverEvent{action=<action show_text>, value='TextComponent{text='', siblings=[TextComponent{text='Cancel', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}'}, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}components=<null>b=SYSTEMc=00000000-0000-0000-0000-000000000000]>.... [07:19:23 ERROR]: Parameters:net.minecraft.server.v1_16_R1.PacketPlayOutChat@34885de[a=TextComponent{text='', siblings=[TextComponent{text='', siblings=[TextComponent{text='kubikula8888 requests teleportation to you!', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=HoverEvent{action=<action show_text>, value='TextComponent{text='', siblings=[TextComponent{text='You have 2 min to accept this request', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}'}, insertion=null, font=minecraft:default}}, TextComponent{text='', siblings=[TextComponent{text=' [✔] ', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=yellow, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=ClickEvent{action=RUN_COMMAND, value='/cmi tpaccept kubikula8888'}, hoverEvent=HoverEvent{action=<action show_text>, value='TextComponent{text='', siblings=[TextComponent{text='Accept', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}'}, insertion=null, font=minecraft:default}}, TextComponent{text='', siblings=[TextComponent{text=' [X] ', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=dark_green, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=ClickEvent{action=RUN_COMMAND, value='/cmi tpdeny kubikula8888'}, hoverEvent=HoverEvent{action=<action show_text>, value='TextComponent{text='', siblings=[TextComponent{text='Deny', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}'}, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}components=<null>b=SYSTEMc=00000000-0000-0000-0000-000000000000]

Happens only when player does /tpa [player]
i think its an issue with the buttons
using latest version

**Comment by Zrips** [comment]
Test next .4 version and if issue persists create a new ticket, but include server version and exact plugin version you are using as "latest version" doesn't really say anything.

**Comment by YTMrSnipa** [comment]
kk
