### ISSUE TITLE
Formatted signs are cleared when signediting

### ISSUE THREAD

**Issue by LegendaryJay** [Zrips/CMI#3730]
Step 1: 
Make sign like this:
&3This
&3is
&3a
&3sign

step 2:
sneak right click - sign is cleared

step 3:
exit - sign is updated
---

**Cmi Version (using`/cmi version`):** 
8.7.1.1

**Server Type (Spigot/Paperspigot/etc):** 
paper 90

**Server Version (using `/ver`):** 
1.16.1

**Comment by Zrips** [comment]
This is issue with client, will have to disable this feature for 1.16.1 for time being until Mojang fixes it. It was reported to them and they closed ticket as resolved, so maybe with 1.16.2 this will work as usual.
