### ISSUE TITLE
some commands seem not to work for interactive commands - no creation..

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3731]
*We are using this plugin:
[TimeIsMoney](https://www.spigotmc.org/resources/time-is-money.12409/)

We tried to create a Sign- attached to an interactive command.
when clicking on the sign the command **/atm should be executed for the player without having him permission to this
i tried it with 

> - asFakeOp! atm

-> nothing

trying this:

>   - bperm:tim.use! atm

gives me consoleoutput "only players can use atms"

What i need it a qay that the player execute this command even if he has no permission when he click the sign.

When you have permission to is and typ /atm   then the ATM Opens normaly..

**Comment by Zrips** [comment]
Not a bug. asFakeOp! will perform command from a fake player object, not as a player who initiated this command, this is why nothing happens. bprem is only for CMI commands.
To make this /atm command to work without having permission to it, you would ether need this atm command to support player name which could be performed from console or to do some funky stuff where you add temp permission node to use this command, perform command and then revoke

**Comment by CloudeLecaw** [comment]
our problem is - we wanne design this as interactive command to a sign.
So the logic would be splited into 3 command-steps right?

> - asConsole! give permission
> - asPlayer! open the atm
> - asConsole take permission

**Comment by Zrips** [comment]
Yea, ether that or you might have option to give out temporary permission for a second which will get revoked automatically. If /atk doesn't support player name, then there isint any other solution at this moment than giving out temporary access to this command throw permissions

**Comment by CloudeLecaw** [comment]
hm so i just need to find a wayy for the PEX so keep this give and take of permission silently, else it would not look so nice in console because a lot of playerse use the atms.
Does CMI has any options here?
