### ISSUE TITLE
Bungee Chat

### ISSUE THREAD

**Issue by SheerHuangJin** [Zrips/CMI#3737]
Is it possible to add Tab player name acquisition for CMI Bungee?

I mean use the Tab key on the keyboard to list the player names of other subservers

When cross-service private chat, there is no obvious message to send tips, hope to improve

**Comment by Harveyplays02** [comment]
Yes, this is already possible. Head to `config.yml` on all servers, and find in the `BungeeCord` section an option called `NamesInTabComplete`, and set it to true. This will now make all visible players able to be tab completed, but not if they're vanished (from my experience). Hope this helps :)

**Comment by SheerHuangJin** [comment]
> 是的，这已经是可能的。前往所有服务器上，并在节中查找名为 的选项，并设置为 true。这将使所有可见的玩家能够完成选项卡， 但如果他们消失了 （从我的经验）， 则不是。希望这有助于:)`config.yml``BungeeCord``NamesInTabComplete`

oh thanks
