### ISSUE TITLE
Color code formatting problem

### ISSUE THREAD

**Issue by naikyys** [Zrips/CMI#3738]
**Description of issue:**
Wazzup, I have problem with color code formatting. 

When I use /broadcast &7Hello &lWorld &7how are you doing?
- It looks like: Hello **World how are you doing**

Someone already told me: uSe &r To rESeT cOloR fOrmaTting.
- I never did it, hope its just problem of CMI.

**Cmi Version (using`/cmi version`):** 8.7.2.3

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.16.1 latest version

**Comment by Harveyplays02** [comment]
This is also the case for any other formatters (italics, underline, etc).

**Comment by Blandix** [comment]
Also when you're using a nickname with three or four bolds, all chat of that person looks like bold, even on /info.
![image](https://user-images.githubusercontent.com/43183267/87732461-69645080-c7a3-11ea-8d22-f30ba564ccbb.png)

**Comment by Zrips** [comment]
This should have been fixed with .5 version
