### ISSUE TITLE
Accepting command with fees (cost for command usage)

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3739]
**Description of feature/improvement request:**
---
Hi, when people execute commands on where are set cost, it doesn't give them any warning about cost usage and automatically take their money.... Maybe you could add something like: "This command has cost XX per usage, do you wanna really use it?" option.

### Detailed explanation of what it should do, when and in what situation: ###
When will player executed command with cost it should ask him if he really wanna pay for this command.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Because if player know price of the command they may won't pay for using it.

**Comment by Volgeop** [comment]
Hey @Zrips my players wanna refund due to this.... It's really needed add message when they have to confirm the cost they will pay for command usage.

**Comment by Zrips** [comment]
Will be added with next build
