### ISSUE TITLE
TPS missing spaces between values

### ISSUE THREAD

**Issue by Harveyplays02** [Zrips/CMI#3740]
**Description of issue:**
TPS seems to not have a space character between the different TPS stats in green a the top, however it did before in the previous version.
![image](https://user-images.githubusercontent.com/40532510/87584228-14f29f80-c6d5-11ea-9a1a-39ee7d0b2155.png)

---

**Cmi Version (using`/cmi version`):** 8.7.2.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper 1.16.1 latest build

**Comment by Zrips** [comment]
Good catch, will be fixed with next build
