### ISSUE TITLE
Messages are in boldness / striped since recent updates

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#3741]
**Description of issue:**

As of a recent update, some of my messages have boldness or are striped through.

      topLine: '&7&m-----&6 Bal top &7&m-----'

![image](https://user-images.githubusercontent.com/5664135/87586815-6bfe7180-c6e1-11ea-852b-07524f64d4c7.png)

      gotRequest: '&3[senderDisplayName] &7vraagt een teleportatie verzoek naar zijn
        locatie.'

![image](https://user-images.githubusercontent.com/5664135/87586830-77ea3380-c6e1-11ea-97f4-c271f95afb8f.png)

**CMI Version:** CMI: 8.7.2.3

**Comment by OverBrave** [comment]
I have some problems, always bold in server.
![image](https://user-images.githubusercontent.com/47111280/87641412-bb2fbb00-c750-11ea-9eb1-80efb65d4c00.png)

```
<AutoPage><AutoAlias><NoReqPermission>
<T>&3&lSon&b&lCesurlar</T>

&9&l(!) &6Şuan lobi sunucusundasınız,
&6oyun sunucularımıza erişmek için
&5Portal &6veya &7NPC&6'yi kullanabilirsiniz!

<T>&5● &aEğer ki direk sunucu seçicisini açmak istiyorsan üstüme tıkla!</T><H>Sunucular'ı görmek için üstüme tıkla!</H><C>scmenü</C>
```

Or chat messages
![image](https://user-images.githubusercontent.com/47111280/87641560-f205d100-c750-11ea-8a97-4c5b7259b4f8.png)
```
  GroupFormat:
    '1': '{prefix}{displayName} &8&l» &b{message}'`
```

![image](https://user-images.githubusercontent.com/47111280/87641813-4dd05a00-c751-11ea-8c6d-0087e1b8eea1.png)
```
    info:
      TargetMsg: '&c&l(!) &d[senderDisplayName] &8-> &5Sen &a&l» &e[message]'
      SenderMsg: '&c&l(!) &5Sen &8-> &d[playerDisplayName] &a&l» &7[message]'
```



Or pm
![image](https://user-images.githubusercontent.com/47111280/87641590-0053ed00-c751-11ea-97cb-d85839f9cca0.png)

All its bold!

**Comment by Zrips** [comment]
Will be fixed with next build
