### ISSUE TITLE
Click hover in public chat now runs command instead of suggesting it

### ISSUE THREAD

**Issue by Harveyplays02** [Zrips/CMI#3743]
**Description of issue:**
When you click someone's name when using public chat, the `/msg <name>` command is ran instead of suggested to the player.

**Cmi Version (using`/cmi version`):** 8.7.2.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper 1.16.1 Latest Build

**Comment by OverBrave** [comment]
Yes, i have same problem.

**Comment by Zrips** [comment]
Will be fixed with todays update
