### ISSUE TITLE
[MobFarmManager] TPS Drop

### ISSUE THREAD

**Issue by msmanui** [Zrips/CMI#3744]
![15fe83b8380309c4ae7e054d56d99174](https://user-images.githubusercontent.com/63617395/87589762-20859c80-c6bc-11ea-9f04-30eb17e4d3b3.png)

I did check the config and cant find the interval:600 so, its coming from the internal plugin. 

My inteval is:  30

**Comment by LogGits** [comment]
Can you please provide the MFM version, type of server (paper/spigot AKA /version output).

**Comment by msmanui** [comment]
> Can you please provide the MFM version and type of server (paper/spigot AKA /version output).
Version MFM: MobFarmManager1.5.6.0
Version server: git-Tuinity-"8c60245"

**Comment by msmanui** [comment]
https://timings.aikar.co/?id=51c599d2c8b74f04b59f44b7d4644771
Check this timiing... Its literraly lagging the server. Something with async

**Comment by msmanui** [comment]
By the owner of tuinity:
Spottedleafhoy a las 20:45
"should pass the timings and tell em to stop sync loading chunks"

**Comment by Zrips** [comment]
@msmanui 
This 600 interval corresponds to your 30 second auto cleanup setup. Ether lower its count or lower chunk radius. Or atleast provide extra information about your actual setup you have currently. As in case you have ~80 people online with 30sec interval where we are rechecking huge amounts of chunks by big chunk radius, we will have some performance issues.

**Comment by msmanui** [comment]
> @msmanui
> This 600 interval corresponds to your 30 second auto cleanup setup. Ether lower its count or lower chunk radius. Or atleast provide extra information about your actual setup you have currently. As in case you have ~80 people online with 30sec interval where we are rechecking huge amounts of chunks by big chunk radius, we will have some performance issues.

My interval was every 60 seconds, so... 
""should pass the timings and tell em to stop sync loading chunks""

Recode to async and would fix the lag.
