### ISSUE TITLE
Show item in chat is not working

### ISSUE THREAD

**Issue by notynote** [Zrips/CMI#3748]
**Description of issue:**
when player tried to use %i% or [item] the color produce 

[CMI] Failed to show json message with packets, using command approach 
Invalid chat component: Unterminated object at line 1 column 576 path $[2].hoverEvent.value

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**

https://pastebin.com/UGEYCJ7u

---

**Cmi Version (using`/cmi version`):** 
8.7.2.

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
Paper(91) 1.16.1-R0.1-SNAPSHOT

**Comment by OverBrave** [comment]
I have same issue in 8.7.2.4

**Comment by Zrips** [comment]
Will be fixed with todays update
