### ISSUE TITLE
Horses stats are changing when they teleport

### ISSUE THREAD

**Issue by horsecraft** [Zrips/CMI#3752]
players are reporting that horses when they teleport their stats are changing. Here’s a video example,

https://www.youtube.com/watch?v=5tFYuohvGhQ

**Comment by Zrips** [comment]
More information is needed. Atleast provide server version and any errors you might have got in a console while teleporting with horse.

**Comment by horsecraft** [comment]
1.16.1 paper spigot latest version - no errors in console.

**Comment by Zrips** [comment]
Will make some changes related to this. Test next version and let me know if issue persists. For time being will close ticket.

**Comment by Kalasky** [comment]
Still an issue in 1.18.1, when a player teleports with a horse it gets extra hearts as demonstrated in @horsecraft's video.
![image](https://user-images.githubusercontent.com/42560806/147839500-6f473b87-d9d3-4002-88a7-00e5e21b966a.png)
I am recieving no errors in the console
CMI: 9.1.0.4 
CMILib: 1.1.4.4
Server: Paper(108) 1.18.1
