### ISSUE TITLE
CustomText 

### ISSUE THREAD

**Issue by AlfreDGR** [Zrips/CMI#3755]
**Description of issue:**

Before in the customtext the links work without having to put <URL> www.google.com </URL> for example. People clicked and opened the link, but after an update, people cannot open the links with or without <.URL.>.
A greeting!

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
8.7.2.5
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-93
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
You want to be able to click on a link even when you dint defined one as such while using customtext formatting?

**Comment by AlfreDGR** [comment]
Before you could click without the <URL> or with it but now in no way

**Comment by AlfreDGR** [comment]
For example I put <URL>https://discord.gg/SaVqFRy</URL> And dont work

**Comment by AlfreDGR** [comment]
<.URL.>https://discord.gg/SaVqFRy<./URL.>

**Comment by AlfreDGR** [comment]
Without the dots

**Comment by Zrips** [comment]
Will be added/fixed with next build

**Comment by AlfreDGR** [comment]
I have the link and dont work

**Comment by Zrips** [comment]
Show me the link you have

**Comment by AlfreDGR** [comment]
https://discord.gg/SaVqFRy

**Comment by Zrips** [comment]
It does work for me. Show me entire ctext line you have for this link or is it a basic text line?

**Comment by Zrips** [comment]
nwm, it should be fixed with next build and we should properly detect links in generic texts now
