### ISSUE TITLE
\n is translated to next line in the public and private messages but isn't in ctextraw command

### ISSUE THREAD

**Issue by variananora** [Zrips/CMI#3756]
**Description of issue:**
\n is translated to next line (enter) in the public and private messages but is not translated in ctextraw command.

Public Chat:
8.7.2.3 and prior:
![image](https://user-images.githubusercontent.com/34732414/87783338-74c88200-c85e-11ea-90b5-781241e28bae.png)
8.7.2.4 and later:
![image](https://user-images.githubusercontent.com/34732414/87783404-90338d00-c85e-11ea-8386-b9f7bcbb51e8.png)

ctextraw command:
8.7.2.3 and prior:
![image](https://user-images.githubusercontent.com/34732414/87783445-a80b1100-c85e-11ea-92e8-c28a3c37a365.png)
8.7.2.4 and later:
![image](https://user-images.githubusercontent.com/34732414/87783448-a9d4d480-c85e-11ea-980e-d1aec2e5ad12.png)

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Chat:
  ModifyChatFormat: true
  ClickHoverMessages: true
```

---

**Cmi Version (using`/cmi version`):** 
8.7.2.5 (Also applied to 8.7.2.4)

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
1.16.1 Build 92

**Comment by Zrips** [comment]
Will get resolved with next update
