### ISSUE TITLE
Mirror Mode in Survival consuming too many blocks

### ISSUE THREAD

**Issue by MikeHollisJr** [Zrips/CMI#3758]
Mirror mode consumes 1 too many items in survival despite the chat saying otherwise

Enter Survival
Setup Mirror mode
Place a block

Chat says the correct amount, inventory consumes one more.

CMI: 8.7.2.5 BungeeCord  SqLite
Server: Paper(79) 1.16.1-R0.1-SNAPSHOT
CMI economy: True Vault: 1.7.3-b CMI Chat: True
Modules -> 50 enabled 1 disabled: votifier

**Comment by mrfloris** [comment]
This was reported here: https://github.com/Zrips/CMI/issues/3349 but it seems it's still an issue in 1.16.1

**Comment by Zrips** [comment]
Will be resolved with next build
