### ISSUE TITLE
[Feature] /give items with attached commands

### ISSUE THREAD

**Issue by ScuroK** [Zrips/CMI#376]
Could you allow to /give items with attached commands?

This would allow servers to give players special reward items for example one time commands etc.

**Comment by CloudeLecaw** [comment]
hm yeah for the Moment u just can attach command to an item and in step two give this item to a Player in some choosen way (must be able to save the metadata of the items)

**Comment by ScuroK** [comment]
@Zrips is this possible from a technical point of view?

**Comment by CloudeLecaw** [comment]
hm may not with the current Version. but for a dev like ZrIps Nothing is impossoible ;)
Maybe a extra database where giveaways are saved...or something like that.. i thinks there are many nice Options. just a Question of time :)

**Comment by Zrips** [comment]
@ScuroK Everything is possible from technical point of view.

**Comment by Zrips** [comment]
7.7.11.0 update, if that is not what would work for you. Well repost this request for future updates with maybe different approach.

**Comment by ScuroK** [comment]
@Zrips can you give me an example how to /give an item (to another player) that runs a command?

**Comment by Zrips** [comment]
@ScuroK 
get item in your hand, perform **/cmi attachcommand asConsole! cmi heal [playerName]** then save it with **/cmi saveditems save healing** then you can give it to player with **/cmi saveditems give [playerName] healing**

**Comment by ScuroK** [comment]
thx! I will try it out tonight
