### ISSUE TITLE
Rankup System 2 branche's on the same time? 

### ISSUE THREAD

**Issue by rybuilder23** [Zrips/CMI#3762]
**Question: **
Is it possible to Advance with the Rankup System  on 2 branche's on the same time?

i created 2 branche's but when a player has all the requements he gets nothing.
Someone any idea's?

My rank file.
https://pastebin.com/x8tsjH9B

When a player is the Default rank He or she can pick **boer** or **mcmmo_power_10** but not both.
And He or she can only pick one branch at a time.

**Comment by Zrips** [comment]
This is by design, you can branch out but you cant have multiple ranks at same time, that would introduce extra complexity and tracking, so for time being only one rank can be active.
