### ISSUE TITLE
Save error

### ISSUE THREAD

**Issue by AlfreDGR** [Zrips/CMI#3763]
**Description of issue:**

[CMI] SEVERE SAVE ERROR
>.... [14:34:58 WARN]: java.util.ConcurrentModificationException
>.... [14:34:58 WARN]: at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
>.... [14:34:58 WARN]: at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
>.... [14:34:58 WARN]: at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
>.... [14:34:58 WARN]: at java.util.HashSet.<init>(HashSet.java:120)
>.... [14:34:58 WARN]: at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:411)
>.... [14:34:58 WARN]: at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:286)
>.... [14:34:58 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
>.... [14:34:58 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [14:34:58 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>.... [14:34:58 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [14:34:58 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [14:34:58 WARN]: at java.lang.Thread.run(Thread.java:748)
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
8.7.2.6
**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Should get resolved with next build
