### ISSUE TITLE
Vault Issues

### ISSUE THREAD

**Issue by SilkPenny** [Zrips/CMI#3764]
With Vault 1.7.3, every plugin requiring an economy is disabling itself upon startup.  I am on CMI 8.7.2.6. and CMI economy is set to true.  This is our survival server.  ShopGUI+ is throwing console errors, but most plugins just do not work.

Oddly, this is not happening on our skyblock server.  The skyblock server has CMIEconomyInjector installed, but the survival server does not.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################

Upon startup: 
[Server] INFO [CMI] Vault was found but economy engine is missing. Use one from list provided in https://dev.bukkit.org/bukkit-plugins/vault/
[Server] INFO Vault was found but not economy plugin, you will have limited economy support

Console errors currently shown with ShopGUI+
https://pastebin.com/DCmduswa

Console errors currently shown with HeadDatabase
https://pastebin.com/XS0z2Tdf
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
Economy:
Enabled: true
#######################################
```

---

**Cmi Version (using`/cmi version`): 8.7.2.6.

**Server Type (Spigot/Paperspigot/etc): PaperMC #88

**Server Version (using `/ver`): 1.16.1 

**Relevant plugins (Delete if this isn't needed):  Disabled are ShopGUI+, UltimateShops, GriefPrevention (buying claimblocks), MySqlEconomyBank, Headdb (some features), Enjin.  Most throw internal errors not shown in console, or just do not work.

**Comment by Zrips** [comment]
Posted new recompiled vault with CMI support and alternatively updated Vault injector. You can get download links at main plugin page or at zrips.net

**Comment by SilkPenny** [comment]
I already have Vault 1.7.3 - are you saying I need to add the CMIEconomyInjector?

**Comment by Zrips** [comment]
As stated on a plugin page on top of it you will need ether a injector plugin or recompiled Vault version. Both of them will get you same result. Will try to push out to the official repo of Vault Cmi compatibility, so we might have official one and ditch existing work arounds.
