### ISSUE TITLE
Auto-update

### ISSUE THREAD

**Issue by WIBOR2002222** [Zrips/CMI#3766]
Hello, it would be nice if you put a system so that the CMI updates are done automatically (this directly download and change the .jar)

Thank you !

**Comment by variananora** [comment]
Duplicate of #3550

**Comment by Zrips** [comment]
At this point there will not be auto updater feature. If i will figure out decent way to achieve this without publishing some direct download link and avoid pirated versions being auto updated will add that.

**Comment by SlyTheFloof** [comment]
pog idea
