### ISSUE TITLE
All teleportation above nether roof no longer works. 

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#3767]
**Description of issue:**
I know there was a change in 8.7.2.7 to fix people teleporting on top of the nether roof with /random or /back, but now it seems that ALL teleportation above the nether roof has broken, including homes, elevators, tpa, and admin tp commands to a player. Instead it only puts players 1 block below bedrock at the highest. 

---

**Cmi Version (using`/cmi version`):** 8.7.2.7

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-d4cbb64-2361cb8

**Comment by Zrips** [comment]
Well, in general players should not be allowed to be on a roof of nether, but i can see where this could be an issue. Will rollback some partial changes related to this.
