### ISSUE TITLE
little Error on /cmi info Offlineplayer

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3768]
>.... [05:01:17 INFO]: Blueeyestar issued server command: /cmi info ___MaxiuS___
>.... [05:01:17 WARN]: java.lang.NullPointerException
>.... [05:01:17 WARN]: at com.Zrips.CMI.commands.list.info$1.lambda$0(info.java:549)
>.... [05:01:17 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
>.... [05:01:17 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
>.... [05:01:17 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291)
>.... [05:01:17 WARN]: at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
>.... [05:01:17 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
>.... [05:01:17 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
>.... [05:01:17 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [05:01:17 WARN]: at java.lang.Thread.run(Thread.java:748)

![Snag_4308109](https://user-images.githubusercontent.com/12080017/87866096-8fdde380-c97d-11ea-98a7-51b8c2badbb8.png)

**Comment by Zrips** [comment]
Will be fixed
