### ISSUE TITLE
Really buged playtime

### ISSUE THREAD

**Issue by Blandix** [Zrips/CMI#3769]
**Description of issue:** I dont know what else to do. Some weeks ago, an user suddenly went from 16 days to 235 days on playtimetop. I fixed it, was okey. The same day another user went from 15 days to 0, i've also fixed it (always with /editplaytime command). Now a user went from 18d to 15 hours. I've fixed it, TWICE, but he goes again to 15 hours. I don't know what else to do. All other users are okey. I'll put the last shut down, the last start, and mi config.

Last shut down: https://pastebin.com/akNEtteb
Last start: https://pastebin.com/EEssnD43
Config: https://pastebin.com/BtvLaSS9

---

**Cmi Version (using`/cmi version`):** CMI8.7.2.7

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** git-Paper-371 (MC: 1.15.2)

**Comment by Zrips** [comment]
Most likely caused by Afk->StopPlayTime: true configuration section. Will make some changes for this method. If issue persists after next update, let me know.

**Comment by Blandix** [comment]
> Most likely caused by Afk->StopPlayTime: true configuration section. Will make some changes for this method. If issue persists after next update, let me know.

@Zrips 
It's still happening, at least on 8.7.2.8, so i'll deactivate StopPlayTime for now
