### ISSUE TITLE
Vault Economy Support Still Broken 

### ISSUE THREAD

**Issue by Joshinn-mc** [Zrips/CMI#3770]
**Description of issue:**
Even on latest build (Vault Fixes), vault still seems to be having issues hooking in properly and working with other plugins.

I am running CMI 8.7.2.7 and the latest Vault download from the "read more" of that update, but things like ShopGUI+ are skipping right past my "enabled" CMI balance and will only read from the balance that is displayed when I disable CMI economy.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```

NOTE: Not actually an error, but a full log of startup.
https://pastebin.com/fduHwXKH
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# Language file you want to use
Language: EN
Economy:
  # Enable or disable CMI economy in general
  # In case CMIInjector is present, then this will be set to true automatically.
  # Attention! For economy to work properly with other plugins you will need ether an injector or recompiled Vault version. 
  # You can find both option at top of plugins page
  Enabled: true

This config setup will not hook into something like ShopGUI+ etc, however if I set that to disable and see my regular vault balance, that is what ShopGUI+ tries to read.
```

---

**Cmi Version (using`/cmi version`): 8.7.2.7** 

**Server Type (Spigot/Paperspigot/etc): Latest Tuinity (Just a paperspigot fork)** 

**Server Version (using `/ver`): 1.16.1**

**Comment by Joshinn-mc** [comment]
https://discordapp.com/channels/452792793631555594/526402563847880725/734339233581498378

More relevant testing. This is using the OG vault that just released + CMIEInjector.

Does not respect the CMI economy, only if I disable it.

**Comment by Joshinn-mc** [comment]
Test 1: The modified vault from the latest CMI update link. Did not work.

Test 2: The modified vault from the latest CMI update + CMIEInjector. Did not work.

Test 3: The OG vault update that got pushed + CMIEInjector. Did not work.

Only test that ever worked was disabling CMI economy.

**Comment by Zrips** [comment]
First of all, you have quite few error messages in your startup log. Second, there is a line
**[02:15:12] [Server thread/INFO]:   Vault was found - Enabling capabilities. Economy: Gem**
which doesn't indicate that CMIEconomy is recognized but rather **Gem** 
Disable all plugins except CMI Vault permission plugin and your shops plugin and check if startup message properly indicates that CMI economy is enabled, you should get message like
**[12:37:36 INFO]:   Vault was found - Enabling capabilities. Economy: CMIEconomy**

**Comment by Joshinn-mc** [comment]
Pointing out that “Gem” thing might have given me a clue for what is causing this, thanks.
