### ISSUE TITLE
Tab complete displays other commands

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#3771]
**Description of issue:**

For some reason in /tpa stuff like afk, back etc shows up in tab complete, rather then just online players.

![image](https://user-images.githubusercontent.com/5664135/87879076-aec58f80-c9e8-11ea-9178-b7bc1e7e136a.png)

**Comment by YourRapiddeath** [comment]
The same with us. With **/cmi tps** works perfectly but without cmi before it no longer works

**Comment by mercurialmusic** [comment]
Can you provide a little more info like any other plugins that might affect tab completion, server version, cmi version, etc.? Testing this on Spigot with CMI 8.7.3.0 works as expected. I know Paper does some funky things with tab completion though.

**Comment by Sikatsu** [comment]
This was fixed and broke again on a later update. Now player names don't show at all anymore.

![image](https://user-images.githubusercontent.com/5664135/88968360-80c93080-d2af-11ea-9b62-723181f4bfbe.png)

**Comment by Zrips** [comment]
Yea, that was a thing, temporary, then it got disabled for time being, but i will re enable which should bring back normal tabcomplete behavior back, that fixed version.
