### ISSUE TITLE
Residence fly bug with   Fly:   - world:false

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3772]
**Description of issue:**
---
Hi, when you have Residence on server and players set /res set fly true, they normally can fly. BUT when they rejoin they can't even if it's set to fly true.... They have to use /res set fly true to fly again. So it bugs with rejoining and server restarts. And now, what causes it? CMI fly option in config.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Fly:
  - world:false
```

---

**Cmi Version (using`/cmi version`):**  
```
[19:10:02 INFO]: CMI: 8.7.2.7 BungeeCord MySQL
[19:10:02 INFO]: Server: Paper(100) 1.16.1-R0.1-SNAPSHOT
[19:10:02 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: False
[19:10:02 INFO]: Modules -> 38 enabled 13 disabled: customMessages, mirror, tablist, skin, cmiPlaytime, eventCommands, playerChatTag, ranks, firstJoinMessages, selection, attachedCommands, warmup, namePlates
[19:10:02 INFO]: --------------------------------------------------
```

**Server Type (Spigot/Paperspigot/etc):**  Paper 

**Server Version (using `/ver`):** git-Paper-100

**Relevant plugins (Delete if this isn't needed):** Residences

**Comment by Zrips** [comment]
If you have disabled fly in a world then you have disabled fly in a world. But will push out fix for residence to avoid this issue.

**Comment by Volgeop** [comment]
Ok, bcse when I enable fly (set world:true) it sometimes bugs and players can fly also outside residence.... Maybe also avoid bugging fly out of residence @Zrips ?

**Comment by Zrips** [comment]
You are enabling fly mode to true in CMI while keeping it false in residence? Can you clarify this one.

**Comment by Volgeop** [comment]
Hm, when players fly in their residences and there is fly: world:true in CMI, sometimes when players use for ex. /rt then they can fly.... it's probably not caused by bug in residence, because my player was on spawn, where is fly disabled normally, he used /rt and then he could fly.... after relogin he couldn't. Is it due to world:true in CMI? But it should be always enabled, no? Or how does it exactly works?
