### ISSUE TITLE
Unlimited ores with /uncondense

### ISSUE THREAD

**Issue by MrNova** [Zrips/CMI#3774]
**Description of issue:**
When you enchant boots with the new soulspeed enchantment, if you do /uncondense, you can get infinite ores back. The boots don't vanish.

---

**Cmi Version (using`/cmi version`):** 
8.7.2.8
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.1

**Comment by Zrips** [comment]
strangely enough with 8.7.2.8 /uncondense doesn't even really work. There was some issue with that with latest build and it will be resolved with next version, but that doesn't really explain your issue. In any case, test new version when it will come out and let me know if you still gonna have same issue.
