### ISSUE TITLE
All players kicked on player death

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#3777]
**Description of issue:**
This one is very odd might be more of a question than a bug. I was only able to reproduce it on one of my servers, but in CMI 8.7.2.8 every time any player died, all players were kicked from that server. No errors in console and [this printed on their screens](https://prnt.sc/tkvdax). Rolling back to CMI 8.7.2.7 fixed the issue. 

---

**ERROR:**
Sorry it's all I got: https://prnt.sc/tkvdax

---

**Cmi Version (using`/cmi version`):** CMI 8.7.2.8

**Server Type (Spigot/Paperspigot/etc):** Spigot 

**Server Version (using `/ver`):** git-Spigot-d4cbb64-2361cb8

**Comment by Zrips** [comment]
Have you tested this with CMI only? As this could be caused by another plugin not processing json messages correctly.

**Comment by mercurialmusic** [comment]
I think it was something else, and sorry. Still wasn't able to reproduce it even copying the CMI files from that server to a tester.
