### ISSUE TITLE
/condense Doesn't work

### ISSUE THREAD

**Issue by Anaton546** [Zrips/CMI#3778]
**Description of issue:**
When doing /condense when you have stuff in your inventory that can be condensed (nuggets, ingots), It says Thereis nothing in your inv to condense, even though you do.

---

**Cmi Version (using`/cmi version`):** 
8.7.2.8
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-paper-40 (mc: 1.16)

**Comment by Zrips** [comment]
Will get fixed. Small issue when material name is not provided
