### ISSUE TITLE
Multiverse World Alias

### ISSUE THREAD

**Issue by Srborjaa** [Zrips/CMI#3781]
**Description of feature/improvement request:** Show world alias in chat

---
### Detailed explanation of what it should do, when and in what situation: ###
If the world is called "Nether" and I want to see "&4Nether" (world alias) in chat, I could use it

### Basic explanation as to why this feature is needed and/or useful to have: ### 
I don't know if it can already be done, but If so don't know how.

**Comment by CloudeLecaw** [comment]
You can use the placeholder and use a colorcode before.

**Comment by Srborjaa** [comment]
I know, but what I want is, for example:

"&6Spawn" - to show the name as gold
"&cNether" - to show the name as red
"&dEnd" - to show the name as purple

**Comment by CloudeLecaw** [comment]
Ah so you want diffent colors for different worlds i see. Well i Know some Protectionplugins like Redprotect have this Feature and also offer the colored placehoders but i dont know if cmi can manage this... Well what would work is using a random custom color.... But i kniw thats not what you want ;0

**Comment by CloudeLecaw** [comment]
Haveing a suggestion... 

Install plaverholderapi and Install the multiverse extension for its placeholders

https://api.extendedclip.com/expansions/multiverse/

**Comment by Srborjaa** [comment]
> 
> 
> Haveing a suggestion...
> 
> Install placerholderapi and Install the multiverse extension for its placeholders
> This offers you
> %multiverse_world_name_colored%
> So you would have the same colord shown from multiverse
> 
> PlaceholderAPI command for Multiverse-Core:
> /papi ecloud download multiverse
> 
> Placholders you can use after installing and after server restart :
> %multiverse_world_alias%
> %multiverse_world_all_property_names%
> %multiverse_world_generator%
> %multiverse_world_name%
> %multiverse_world_name_colored%
> %multiverse_world_permissible_name%
> %multiverse_world_time%
> %multiverse_world_animals_spawn_enabled%
> %multiverse_world_monsters_spawn_enabled%
> %multiverse_world_access_permission%
> %multiverse_world_adjust_spawn_enabled%
> %multiverse_world_allow_flight_enabled%
> %multiverse_world_auto_heal_enabled%
> %multiverse_world_auto_load_enabled%
> %multiverse_world_bed_respawn_enabled%
> %multiverse_world_color%
> %multiverse_world_currency%
> %multiverse_world_difficulty%
> %multiverse_world_environment%
> %multiverse_world_gamemode%
> %multiverse_world_hunger_enabled%
> %multiverse_world_player_limit%
> %multiverse_world_price%
> %multiverse_world_seed%
> %multiverse_world_style%
> %multiverse_world_type%

Solved, thanks!

**Comment by CloudeLecaw** [comment]
Dont forget to close the request :)
