### ISSUE TITLE
Non-formatted actionbar text

### ISSUE THREAD

**Issue by Srborjaa** [Zrips/CMI#3783]
**Description of issue:**  I have the actionbar messages like:` '!actionbar!&2¡Tienes recompensas pendientes por reclamar! /prewards'` for the rewards and` '!actionbar!&6¡Whoosh!'` for the random tp, but they are always shown in white color

https://i.gyazo.com/cc445cb0770d87b0764f53e72e164692.png

**Cmi Version (using`/cmi version`):**  8.7.3.0

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot

**Server Version (using `/ver`):** Paper(379) 1.15.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Thanks for pointing this one out. For some reason actionbar messages in older servers doesn't support current json format. Tho it seams to be only one place where its not working properly. 
Will be fixed with next build.
