### ISSUE TITLE
/cmi spawn and /spawn

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [Zrips/CMI#3784]
Hey i need help with your plugin, when you type "/spawn" it doesnt work... but when you type "/cmi spawn" then it works can you help me how to fix it ?

Alias.yml 
/cmi spawn $1-
  /spawn: true

**Cmi Version (using`/cmi version`): 8.7.3.0

**Server Type (Spigot/Paperspigot/etc): Spigot

**Server Version (using `/ver`): 1.16.1

**Comment by CloudeLecaw** [comment]
Have you tried restart the server in first case? Canages in alias yml only work after a server restart. Same to autocomplet if custom alias. Cause command just get registriert on serverstart

**Comment by Sh3r1ffCZ** [comment]
Yes, I tried restart, but nothing changed

**Comment by CloudeLecaw** [comment]
Ok thats stange, on oir server the spawn command works normal. ;( maybe you have a plugin that tries to prevent tab completation for players?
You should try first a clean Testserver with just your permission plugin and cmi and look if the same issue accurs there too.

**Comment by Zrips** [comment]
@Sh3r1ffCZ 
Make sure that you don't have custom alias set to spawn command and test it without any other plugin to rule out possible issue with another plugin overriding default behavior.

**Comment by Sh3r1ffCZ** [comment]
Im tried start server only with plugin CMI and it works... but i dont know why. On version 1.15 works everything perfectly. Thanks
