### ISSUE TITLE
Un/Condensing sandstone mix up

### ISSUE THREAD

**Issue by rikyriky232** [Zrips/CMI#3788]
**Description of issue:**

Uncondensing works for sandstone (It turns into sand) Which should not work at all

Condensing doesn't work for sand (Turning it into sandstone) 

It's both switched up

---

**Cmi Version (using`/cmi version`):** 8.7.3.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot 1.16.1 

**Server Version (using `/ver`):** git-Paper-101 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Will be fixed with next update
