### ISSUE TITLE
Color Permission Changed

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#3789]
**Description of issue:**
Some permissions related with colors were changed, which made me hard to deal with.
For instance, the permission "cmi.command.glow.color.dark_red" was worked, but now only 
"cmi.command.glow.color.darkred" works.
I need the support of the former permission format.

**Cmi Version (using`/cmi version`):** 
8.7.2.8
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.15.2

**Comment by Zrips** [comment]
ok
