### ISSUE TITLE
[Selection Visualizer] doesn't work with Grief Defender

### ISSUE THREAD

**Issue by MikeHollisJr** [Zrips/CMI#3790]
This may be better suited to a feature request, but I'll let you judge, Grief Defender is the premium successor to Grief Prevention and is made by the same group of people.

SV doesn't recognize GD as being installed and does not visualize its selections. I chose bug to label it since it is essentially the same plugin.

![image](https://user-images.githubusercontent.com/1078934/88065917-2f94a080-cb3b-11ea-84df-29d19d60fc6a.png)
![image](https://user-images.githubusercontent.com/1078934/88066209-7e423a80-cb3b-11ea-844c-c1e9ecd89387.png)

**Comment by Zrips** [comment]
Not a bug if you have different plugin. And yes, different. Same plugin would be when you have same plugin, having new one even if its based on old core while having new name ans i guess new API entirely is not a bug by itself.
