### ISSUE TITLE
Riptide and /pweather

### ISSUE THREAD

**Issue by Tolmikarc** [Zrips/CMI#3793]
**Description of issue: Players who have the ability to use /pweather, which is supposed to be a cosmetic command, are given the unfair advantage of being able to use riptide while it is only raining for their client. If it is possible so that pweather does not affect the use of riptide and still behaves as it would for the current global weather that would be amazing.**

**Cmi Version (using`/cmi version`): 8.7.2.3** 

**Server Type (Spigot/Paperspigot/etc): Paper(379)** 

**Server Version (using `/ver`): 1.15.2-R0.1-SNAPSHOT**

**Comment by CloudeLecaw** [comment]
If you gave them power to setup personal weather then you give them power to do unfair things. Thats the reason fir not giving to them.. Pweather is no cosmetical thing players should have like been able to use colors

**Comment by Zrips** [comment]
This is Vanilla minecraft issue and it was already addressed and there is no real fix for it. Even appropriate riptide event is not fired when you have player with pweather set while player still can riptide. Without actual event we cant properly process player and prevent riptiding as its basically client sided at this point.
