### ISSUE TITLE
error npc (Citizens v2.0.26-SNAPSHOT (build 1865) 

### ISSUE THREAD

**Issue by enderluffy** [Zrips/CMI#3796]
**Description of issue:**

---

**ERROR: **
```
######################
## as soon as i kill a npc (citizen version v2.0.26-snapshop (build 1865)) there but an error: Unable to pass PlayerDeathEvent 
      event to CMI v8.7.3.1

      I you but a pastebin for the error code: https://pastebin.com/yQLN0njP ##
######################
```

---

**Cmi Version (using`/cmi version`):  8.7.3.1** 

**Server Type (Spigot/Paperspigot/etc):  Spigot 1.5.2-R0.1-Snaphot   ** 

**Server Version (using `/ver`):  231**

**Comment by CloudeLecaw** [comment]
Pls try Update to latest cmi and latest Citizens2 build

**Comment by Zrips** [comment]
Will be fixed with next build
