### ISSUE TITLE
AFK and being vanished 

### ISSUE THREAD

**Issue by singaporemath** [Zrips/CMI#3797]
Hello,

I wanted to be able to use the manual AFK command as a way for my staff members to be able to mark themselves as AFK. I setup the AFK system in the config, however I noticed that when one of my staff members are in '/cmi vanish' and they attempt to do '/cmi afk', it does not send the "You are in AFK Mode" message. It only shows that message when you are out of 'cmi vanish' and then try and do 'cmi afk'. Is there something in the config that I am overlooking? Is it possible to allow vanished players to use the afk command?

**Comment by CloudeLecaw** [comment]
Have you checked that using afk command ins config is true in vanish?

Vanish:
  # Defines default states of vanish edit options for players
  # This will not have any effect if player already edited his vanish mode with vanishedit command
  Defaults:
    damageToEntity: false
    playerDamage: false
    itemPickup: false
    mobAggro: false
    interaction: false
    noisyChest: false
    informOnLeave: false
    informOnJoin: false
    nightVision: true
    bossbar: true
    afkcommands: true
    PrivateMessages: false
    relogDisable: false

This only work if you stuff has not edit thier vanishmode allready with cmi vanishedit. There they can also enable using afk commands

**Comment by singaporemath** [comment]
> Have you checked that using afk command ins config is true in vanish?
> 
> Vanish:
> 
> # Defines default states of vanish edit options for players
> # This will not have any effect if player already edited his vanish mode with vanishedit command
> Defaults:
> damageToEntity: false
> playerDamage: false
> itemPickup: false
> mobAggro: false
> interaction: false
> noisyChest: false
> informOnLeave: false
> informOnJoin: false
> nightVision: true
> bossbar: true
> afkcommands: true
> PrivateMessages: false
> relogDisable: false
> 
> This only work if you stuff has not edit thier vanishmode allready with cmi vanishedit. There they can also enable using afk commands

I cannot find those in my config. What .txt is it in?

**Comment by CloudeLecaw** [comment]
yes;)
