### ISSUE TITLE
Flying at login - a CMI issue?

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/CMI#38]
Have since several updates already the problem that players can fly the new joinen / rejoin the  #game.

We have created the group [GUEST] for "Default" players and they do not have the right to fly.
Unfortunately, I keep watching new players strangely fly

by /cmi Info [player name] I find out that there is: can fly: true
![unbenannt](https://user-images.githubusercontent.com/36611372/36629343-f87b2654-1954-11e8-9c5a-6958eb0e99d8.JPG)
But where did they get the right?
Also with some players, who already played some time on the server this problem was noticed.

Even after a reload (which can occur from time to time), every online player gets the right to fly afterwards
how can you turn this off and is there a general solution?
We have already negated the rights for fly in PermissionsEX.

/pex user [player name] add -cmi.command.fly
or.:
/pex group [groupname] add -cmi.command.fly

**Comment by LogGits** [comment]
It is generally advised not to reload a server (should be restarting instead). I also think this could be related to #22 . If a User doesnt have access to /fly they shouldnt even be able to fly. You could try using the eventcommands.yml file join and leave commands as `cmi fly [playerName] false`.

**Comment by Zrips** [comment]
Will do some changes and hopefully that will solve issue.

**Comment by HomeLandingsDE** [comment]
> You could try using the eventcommands.yml file join and leave commands as cmi fly [playerName] false


But that would mean that the server team is thrown out of the flymode with every login / logout and must always type /fly again.

**Comment by LogGits** [comment]
> But that would mean that the server team is thrown out of the flymode with every login / logout and must always type /fly again.

You can use cmi specialised commands to check if they have permission to fly. if they don't have permission to fly it could set their fly. Also this is reportedly fixed in the latest build please update and let us know if the issue persists 🙂

**Comment by HomeLandingsDE** [comment]
short information from us:

In the last few days we have turned off the flying with the FirstJoin / Join / Quitevents - all who were allowed to fly had to enter / fly each time - but the problem could not be solved otherwise.

After the update from 7.3.13.0 to 7.3.13.1 it seems to have been fixed.
I still watch it and will report if it changes.
