### ISSUE TITLE
using a CMI portal breaks users /back

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#3805]
When a user goes through a CMI portal, it removes their /back location. This should not be setting their last location. People do not expect their back location to be wiped to a portal they went though.

**Comment by Zrips** [comment]
yea, i can make some slight change and ignore portal teleportation event and exclude from back location records. Next version

**Comment by FrozenBeard** [comment]
Thanks @Zrips !

Do I need to enable this in the config somewhere? I updated the plugin and back still goes to the portal location.

**Comment by Zrips** [comment]
Do you teleport players with portal itself or throw commands set in portal? And how exactly did you tested this?

**Comment by FrozenBeard** [comment]
I use the portal teleport system, I don't use commands to teleport them in portals.

I tested this by teleporting to a location, then walking up to a portal and walking through it then doing `/back` to see if it would send me to the last place I teleported or if it put me in front of the portal and it put me at the portal.

Im using paper 1.12.2.
