### ISSUE TITLE
Bossbar Compass duplicating (#3710)

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#3806]
**Description of issue:**

https://github.com/Zrips/CMI/issues/3710 - Still happening

https://imgur.com/ZoFsiOC

---
---

**Cmi Version (using`/cmi version`):** 
8.7.3.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper 1.16.1 (Build 108)

**Comment by Zrips** [comment]
I need your bossbar setup config section.

**Comment by Zrips** [comment]
Will issue new update, will remake some parts of the code as it looks like old method doesn't really want to work properly. Test next version and it should resolve this issue once and for all.
