### ISSUE TITLE
Command cost doesn't work for custom alias

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3808]
**Description of issue:**
---
Hi, command cost doesn't work for custom alias.... When I have for ex. command /respawn in custom alias, how could I make cost for usage of this command when it doesn't work in commandcost.yml?

---

**Cmi Version (using`/cmi version`):** 8.7.3.3

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  1.16.1

**Comment by Zrips** [comment]
This is not a bug. I might need to add clarification to the commandCost file, but currently command costs only work for base CMI commands due to the complexity in how we handle them. Custom alias is completely different system and we could only have it on some rudimentary level where we would charge money in most cases even if command was not successfully performed but simply for attempt to perform it. 
Its in todo list

**Comment by Volgeop** [comment]
I see you added it.... but i'm having another problem. I have this:
```
  invrespawn:
    Cmds:
    - asConsole! perm:cmi.keepinventory! perm:group.helper! cmi msg [playerName] ! {#lochmara}Zachovávání
      inv bylo zapnuto, &lnyní je vypnuto.
    - asConsole! perm:cmi.keepinventory! perm:group.helper! lp user [playerName] permission
      set cmi.keepinventory false server=survival
    - asConsole! perm:cmi.keepinventory@! perm:group.helper! cmi msg [playerName] !!
      {#lochmara}Zachovávání inv bylo vypnuto, &lnyní je zapnuto.
    - asConsole! perm:cmi.keepinventory@! perm:group.helper! lp user [playerName] permission
      set cmi.keepinventory true server=survival
```

And it will take players money even if he doesn't have specific permissions..... couldn't it somehow check conditions for executing it? Or couldn't there be atleast message for player that he doesn't have permission to use this command? There isn't really nothing when he executes it, only that it will cost him XXX €.  https://ctrlv.cz/jdbz @Zrips

**Comment by Zrips** [comment]
This is the thing, having specialized commands introduced allot more complexity to the command cost check. I might try to improve upon it, but its relatively complex thing to handle properly, especially when you have multiple conditional command lines where one could proceed and another could fail while end result could be success or fail in general depending on what type of line fails and what it contains and which one processes successfully.

**Comment by Volgeop** [comment]
And @Zrips when I set command cost to /spawner command and player just open second page it take his money even if he didn't change spawner.... could be fixed somehow?

**Comment by Zrips** [comment]
@Volgeop Not at the moment, as currently we are sending command with page number to change page, which means that we have command which looks to be valid for being charged, while its not. Will have to think about some work around for this one

**Comment by Volgeop** [comment]
Ok, I'm closing it, you can change some commands and do tweaks too, I will be happy.
