### ISSUE TITLE
Gamerule "doWeatherCycle false" still shows ground particles

### ISSUE THREAD

**Issue by InDirectVariant** [Zrips/CMI#3810]
**Description of issue:**
When the gamerule "doWeatherCycle" is set to False (including via the GUI) the rain does not fall from the sky but the particles of the splashing water still appear on the ground.

---

**Cmi Version (using`/cmi version`):** 8.7.3.1

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** git-Paper-91

![2020-07-22_21 25 09](https://user-images.githubusercontent.com/8107418/88244646-6f09dc80-cc62-11ea-9adf-926546477494.png)
![2020-07-22_21 25 17](https://user-images.githubusercontent.com/8107418/88244647-6fa27300-cc62-11ea-9072-f134ba5ef2c2.png)

**Comment by Zrips** [comment]
This is client or minecraft server bug, not CMI.
Just just for future posts, you need to include actual server version and not only build number. In this case i guess it was 1.16.1, i guess.
