### ISSUE TITLE
Non-formatted messages' second line items

### ISSUE THREAD

**Issue by Srborjaa** [Zrips/CMI#3811]
**Description of issue:** Some words become unformatted when the messages get another line, even if I put the &X color in all the words.

![imagen](https://user-images.githubusercontent.com/29895095/88267711-816f2f00-ccd1-11ea-9ba3-34fb3f201bfe.png)

**Cmi Version (using`/cmi version`):** 8.7.3.3

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper(380) 1.15.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Confirmed, will get fixed.
