### ISSUE TITLE
cmi reply doesn't work bungee wide

### ISSUE THREAD

**Issue by gaRt3n** [Zrips/CMI#3812]
**Description of issue:**
Private messages which are send via /cmi reply won't go to the last written user on an other server.
---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.7.1.1 §eBungeeCord  MySQL-> 8.7.3.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`): ** 
git-Paper-89 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will be fixed with next version
