### ISSUE TITLE
Wrong permissions written in config.yml (cmi.command.[comandName].warmupbypass)

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#3813]
Setting up warp warmups to work the same as teleport warmups, and in the config it says to use
```cmi.command.[comandName].warmupbypass```
When the permission is actually
```cmi.warmupbypass.[commandname]```

Not sure if my config just hasnt been updated in a long time, or this is in all configs, but thought I would report it anyway.

**Comment by Zrips** [comment]
Thanks for pointing that one out. Will update comment section. Some time ago we did had previous format but it was changed to avoid some of the issues related to old format.
