### ISSUE TITLE
When moving a portal, keep its settings.

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#3814]
When I move a portal, its settings reset, the particles, how many particles etc. its really annoying when I re-define an area and its settings have to be re-set.

**Comment by Zrips** [comment]
But it does keep its current settings, checked code itself and retested ingame. Only area is changed.

**Comment by FrozenBeard** [comment]
It dousnt keep the amount of particles you set

**Comment by Zrips** [comment]
Go it, will get fixed. Currently default particle amount was calculated automatically depending on selection area to avoid having too little on bigger selection and too much on smaller ones, but at same time it created this issue where new zone definition recalculated particle amount.
