### ISSUE TITLE
Rankup issues

### ISSUE THREAD

**Issue by naikyys** [Zrips/CMI#3815]
Hello I would like report that /rankup stats are not counting correctly for example: When I jump I have still in /rankup zero jumps.. When I updated to the newest version of CMI (8.7.3.3) that issue happened. When I downgraded back to 8.7.3.1 it was all good again.
---

**Cmi Version (using`/cmi version`):** 8.7.3.3

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Newest version of Paperspigot

**Comment by kieran737** [comment]
I can also verify we're also suffering from the same issue, using version 8.7.3.4

**Comment by Zrips** [comment]
Reproduced, will be fixed with next build.
