### ISSUE TITLE
Use player head texture IDs for holograms

### ISSUE THREAD

**Issue by the456gamer** [Zrips/CMI#3817]
**Description of feature/improvement request:**
Use a provided head texture id for holograms (if it doesn't already)

---
### Detailed explanation of what it should do, when and in what situation: 
A hologram with a line of
`ICON:head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTdiNDE2ZDM2Yjc1NjE3Mzk4ZDdiYjNjZThkYjhhNzRiZDVlMzE0MTgyNTM3NzhjN2E2ZmU4NTQ5ODY3MSJ9fX0=`
Should create a new hologram line. With a head of the specified texture

### Basic explanation as to why this feature is needed and/or useful to have:
Permanently allow custom heads, even if a player changes their skin away from the original

**Comment by Zrips** [comment]
Will add with next update
