### ISSUE TITLE
Integrated option (armor stands)

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3819]
**Description of issue:**
---
Hi, when you set integrated option to enabled in armor stands editor and then click again on armor stand, then armor stand disappear....

https://streamable.com/632u0m

---

**Cmi Version (using`/cmi version`):** 
[23:35:18 INFO]: --------------------------------------------------
[23:35:18 INFO]: CMI: 8.7.3.4 BungeeCord MySQL-> 8.7.3.5 (downloaded 8.7.3.5 but didn't restart yet, but by changelog didn't fix)
[23:35:18 INFO]: Server: Paper(111) 1.16.1-R0.1-SNAPSHOT
[23:35:18 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: False
[23:35:18 INFO]: Modules -> 38 enabled 13 disabled: customMessages, mirror, tablist, skin, cmiPlaytime, eventCommands, playerChatTag, ranks, firstJoinMessages, selection, attachedCommands, warmup, namePlates
[23:35:18 INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** git-Paper-110 (MC: 1.16.1)

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Cant reproduce this on git-Paper-111 (MC: 1.16.1). Try testing it without any other plugin and with only CMI. And if armorstand disappears, try switching to spectator mode to check if armor stand completely got removed or simply became invisible.

**Comment by Volgeop** [comment]
On my second server after setting them to integrate then I can't click on them again, they are like freezed.

**Comment by Zrips** [comment]
This option translates into "Interactable" which means that switching this one you will no longer be able to interact which this armor stand. In case you cant to change its settings use **/armorstand near**

**Comment by Volgeop** [comment]
And can I somehow disable changing into interactable for players? For ex. denying permission or somewhere in config? @Zrips

**Comment by Zrips** [comment]
cmi.command.armorstand.interactable

**Comment by Volgeop** [comment]
And what is interactable used for? To prepare armor stand and then disabling interacting with it? But when using residences, it's probably isn't needed?

**Comment by Zrips** [comment]
Its not needed, you might want to create some armor stands somewhere which should not be interactable at all, even by OP players, as some accidents happen. So you can disable interaction with armorstand and you will no longer take or put items into armor stands when clicking on them. its just an option, i keeped it there because minecraft API allows us to do it, so why not.
