### ISSUE TITLE
/feed all and /heal all consistancy.

### ISSUE THREAD

**Issue by variananora** [Zrips/CMI#3823]
**Description of feature/improvement request:**
Make /feed all to just says "You have fed x players." like /heal all
---

### Basic explanation as to why this feature is needed and/or useful to have: ###
Just to make it consistent and less spammy.

![image](https://user-images.githubusercontent.com/34732414/88458275-1a12d400-ceb7-11ea-95ae-e48e9df05fff.png)

**Comment by Zrips** [comment]
Approved
