### ISSUE TITLE
New 2 placeholder

### ISSUE THREAD

**Issue by OverBrave** [Zrips/CMI#3824]
%world_players_[worldName]% - How many in any world
%cmi_user_daily_votecount% - How many daily vote of player

**Comment by CloudeLecaw** [comment]
The first ine you can have allready with placeholder api :)
%world_<world>_players%

**Comment by OverBrave** [comment]
%world_<world>_players% its only for essentialsX

second one i using CMI vote feature. Not anyone.

**Comment by variananora** [comment]
You can use the Multiverse's placeholder I believe

**Comment by OverBrave** [comment]
Has not have how many player in any world.

**Comment by variananora** [comment]
Ah, sorry. It was %server_online_<world>% do `/papi ecloud download server` first tho.

**Comment by OverBrave** [comment]
Yeah, CMI before update add this support. But daily count of vote contiunes.

**Comment by CloudeLecaw** [comment]
your right cmi currently has no counter for daylie vote
so i suggest creating Voteplaceholders like the plugins
[OnTime](https://dev.bukkit.org/projects/ontime), [VotingPlugin](https://www.spigotmc.org/resources/votingplugin.15358/) or [VoteRoulette](https://dev.bukkit.org/projects/voteroulette) does.

On our server we solved this problem with using VoteRoulette and loaded the placeholders with PlaceholderAPI
/papi ecloud download VoteRoulette

But i know your asking for a CMI internal solution for getting placeholders for daylie, weekly and monthly votes - maybe tops + user speciffic
VotingPlugin would fullfill this job. may you can give it a try? ;-)

**Comment by OverBrave** [comment]
I do not think. Because i already using CMI feature. All systems based on. I can't change.

**Comment by CloudeLecaw** [comment]
dont worry we all use CMI thats why we are here ^,^

**Comment by Zrips** [comment]
Will add %cmi_user_dailyvotecount% with next update
