### ISSUE TITLE
MaxHP

### ISSUE THREAD

**Issue by slipstricker** [Zrips/CMI#3825]
After setting maxhp 10 on someone, that person clicks with food in hand maxhp goes back to 20

https://www.youtube.com/watch?v=mfisCDDIM6s
---

**Cmi Version (using`/cmi version`):** 
CMI: 8.7.3.5 BungeeCord  MySQL
Server: Paper(111) 1.16.1-R0.1-SNAPSHOT
INFO CMI economy: True Vault: 1.7.3-b(CMIEInjector) CMI Chat: False 
INFO Modules -> 48 enabled 3 disabled: tablist, ranks, skin

**Comment by Zrips** [comment]
No reproducible at this point. This could be and most likely is caused by another plugin interfering and reseting players maxhp. Clean Paper(111) 1.16.1 doesn't contain this issue.
