### ISSUE TITLE
EssentialsXChat chat-radius feature into CMI

### ISSUE THREAD

**Issue by Tomi010817** [Zrips/CMI#3827]
I've been reading the plugin description at Spigot, but haven't found anything related to chat features like EssentialsXChat. I'm really convinced of buying CMI on some of these days specially because of its MySQl support, but also for that big amount of incredible features to enjoy. 

---
### Feature Description:
**With the chat-radius features included on CMI, you could do things like,**
- Setting a chat-radius to people, with a configurable message when no one reads their message (that message being able to get disabled)
- A (configurable) symbol to chat in global, by default "!" exclamation mark.
- A prefix for when someone talks in local chat form and a prefix for when someone talks globally, be able to edit them on how they look.
- Permission required to shout messages using the symbol defined to chat globally.
- Permission so that you can spy what people chat even if you are out of their chat-radius. (currently what I'm writing next, isn't on essentialsxchat, but it would be very great if there was a setting on CMI to choose whether you need to have socialspy enabled to view other players chat out of your radius bypassing the permission required)
- Be able to set a cost for each global message you send. With a bypass permission.
- Be able to set a cooldown for each global message you send. With a bypass permission.
- A placeholder for "[Local]" prefix chat format, and a placeholder for "[Global]" prefix, so you can add it or not on your chat-format plugin whether you prefer it or not.

Hope you liked the idea! Cheers

**Comment by Zrips** [comment]
This is already a thing, you can have local chat range and you can have separate shout range when using ! at begging of message and you can charge money for using shout messages. There isint really a cooldown for for global messages, yet.

**Comment by Tomi010817** [comment]
Hello Zrips!! First time talking to you. I've used most of your plugins and I got to say that you do an awesome job and I enjoy all of them.

---
O! Very happy to know that. Didn't expected to see that feature already in there xD

Good luck!
