### ISSUE TITLE
/scan for inventories-enderchests

### ISSUE THREAD

**Issue by Srborjaa** [Zrips/CMI#3828]
**Description of feature/improvement request:** /scan for inventories and enderchests.

---
### Detailed explanation of what it should do, when and in what situation: ###
Now the /scan command can track objects that are in containers, but it could be a good idea to scan also the players' inventories and enderchests.

### Basic explanation as to why this feature is needed and/or useful to have: ###
For example, if a server has an enchanted emerald renamed as a "Token" and it serves to buy unique items in the server, we could track them and see if a player has duplicated them as a consequence of a bug, for example.

I don't know if it's possible to track thrown items, but it could also be a nice idea.

Thanks :)

**Comment by Zrips** [comment]
To check players inventories and ender chests for items use /search command. Works in similar way as scan command.
