### ISSUE TITLE
Feature Request - Sell stick

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#383]
Feature request to add a sell stick with uses.
(Click a chest and sell hand everything that can be sold in there)

So like /sellstick give name 20 (that would give them a sell stick with 20 uses)

It would be awesome if it had configurable text

This kind of thing would need to check things like faction/towny perms and locks so totally understandable if it would be better skipped right now.

**Comment by LogGits** [comment]
Thank you for your suggestion. This is not something we plan on implementing into the plugin at this current time, though, we may investigate this in the future.
