### ISSUE TITLE
bukkit/spigot command.yml alias allows players to bypass warmup

### ISSUE THREAD

**Issue by bluekelp** [Zrips/CMI#3834]
**Description of issue:**

When adding  
``` 
spawn:
- cmi warp spawn
``` 
to the bukkit `command.yml` file to give the alias `/spawn` for `/cmi warp spawn`, players are able to bypass the warmup (set like `- cmi warp :10:false`) in CMI's `config.yml`.

If the command alias is defined like `- warp spawn` it also bypasses (e.g., "cmi" does not need to be specified because CMI is aliasing `/warp` to `/cmi warp` per `Aliases.yml`)

So trying to alias warps to top-level commands via `command.yml` allows players to bypass warmups and teleport immediately. 

Typing `/warp spawn` or `/cmi warp spawn` results in the correct expected warmup. Somehow the alias bypasses CMI's warmup.

I noticed this as early as 8.7.0.4 and with other spigot versions. Reported when the latest version did not fix it. 

---

**Cmi Version (using`/cmi version`):** 8.7.4.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** ```[Sun, 26. Jul 2020 22:47:21 EDT INFO] This server is running CraftBukkit version git-Spigot-9639cf7-7c03d25 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[Sun, 26. Jul 2020 22:47:21 EDT INFO] Checking version, please wait...
[Sun, 26. Jul 2020 22:47:21 EDT INFO] You are running the latest version
```

**Comment by CloudeLecaw** [comment]
Why your using this? Cmi also has this in alias. Yml for spawn

**Comment by Zrips** [comment]
@bluekelp 
There isint much to fix here. First of all, you have alias file where you can define alias. Second, you have custom alias where you can create alias like this on a fly. Third, you can simply add
`  - spawn:3:false`
to warmup list and it will work as it should.
