### ISSUE TITLE
/back is aliased even with Alias.yml tells CMI not to

### ISSUE THREAD

**Issue by bluekelp** [Zrips/CMI#3835]
**Description of issue:**

`/back` is aliased even when set to false in `Alias.yml`. I am not able to find a permission node to prevent players from executing it so my only option is to set a very very long warmup so players cannot use it.

The global `/back` command should not be aliased when CMI is told not to alias it.

I also expect a permission node to be present, like more other commands, so it can be limited to just some players/ranks.

I know `/back` is being aliased/handled by CMI and not another plugin because it results in the CMI warmup for users who type it.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
`Alias.yml`: 
```
  # /cmi back $1-
  /back: false
  /cback: false
  #
```

---

**Cmi Version (using`/cmi version`):** 8.7.4.0

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):** 

```
[Sun, 26. Jul 2020 22:47:21 EDT INFO] This server is running CraftBukkit version git-Spigot-9639cf7-7c03d25 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[Sun, 26. Jul 2020 22:47:21 EDT INFO] Checking version, please wait...
[Sun, 26. Jul 2020 22:47:21 EDT INFO] You are running the latest version
```

**Comment by CloudeLecaw** [comment]
cmi.command.back and cmi.command.cback
.....
