### ISSUE TITLE
Group format gradient

### ISSUE THREAD

**Issue by Rafalll** [Zrips/CMI#3836]
**I suggest adding the possibility of adding a gradient to the group format. It would make things easier and look very nice. Would not need to use {#red>}Some random text {#green<>}which changes{#blue<} because the group format would immediately change color. 
Example:**
```
  GroupFormat:
    '1': '[Default] {displayName} > {#green>} {message} {#yellow<}'
    '2': '[Vip] {displayName} > {#red>} {message} {#corn<}'
```

**Currently, this option does not work because an error is shown on the console.**

**Comment by Zrips** [comment]
Due to how messages are handled we will need separate section to define how message should be colorized. but yea, this is something on my todo list

**Comment by Rafalll** [comment]
Okay thanks. I hope to you add it quickly :) Many people who use CMI will like this.

**Comment by CloudeLecaw** [comment]
we also wished this effect for some of our groups xD
but we know its not possible at the moment
