### ISSUE TITLE
Whitelist Worlds

### ISSUE THREAD

**Issue by AlfreDGR** [Zrips/CMI#3838]
**Description of feature/improvement request:**

---
### Basic explanation as to why this feature is needed and/or useful to have: ###

In eventcommands you could add in the playerWorldChange section a list of worlds in which the assigned commands work. I say this because on my server I use it to remove the fly when they go to the nether world but of course if I have other normal worlds the fly is also removed and it would be a relief for them that they are not putting / fly all the time instead of only in the nether and in the end

**Comment by CloudeLecaw** [comment]
you can do this allready with a simple check :)

**Comment by CloudeLecaw** [comment]
You can disable them by using the frist of the two commands and use the frist aggain with all worldnames where you want fly to be disabled

**Comment by dragontekgaming** [comment]
Some permissions plugins will also do this, Like Luckperms you can give the permission in the overworld/end, but they don't have it in the nether.

**Comment by CloudeLecaw** [comment]
Most permission plugins suport permission by world. His Problem is he needs ti execute a command on changing to the worlds  ecause hus players run from the allowed fly world (i aspect it the main World) to the nether and still have fly on. So he needs the trigger that disables fly on entering of this world.

**Comment by CloudeLecaw** [comment]
Plasse dont forget to close this ticket :)
