### ISSUE TITLE
Commandspy missing commands.

### ISSUE THREAD

**Issue by tmellen** [Zrips/CMI#384]
Random commands aren't appearing in commandspy. At first it was RTP (handled by BetterRTP). This command was always in command spy output. Then /cmi home stopped appearing. Sometimes things do appear, sometimes they don't... If I check coreprotect's command log, I can see commands that I never saw in chat.

I believe this happened with the last version's fix to DiscordSRV no longer working.

Cmi Version (using`/cmi version`): 7.7.6.0
Server Type (Spigot/Paperspigot/etc):  spigot
Server Version (using `/ver`):  1.12.2

**Comment by Zrips** [comment]
Is this happen always or random? Is this related to any particular player or for everyone? As you do have cmi.command.commandspy.hide permission node to hide from being spied upon. And you do have command spy filter in config file. Double check all those and give shout back.

**Comment by tmellen** [comment]
![javaw_2018-05-23_16-16-24](https://user-images.githubusercontent.com/32602474/40448852-bc3d00f0-5ea4-11e8-9e0a-ca25a215b3b6.png)

This is on 7.7.8.0 now...

This always happens, for every player. I know nobody can see my commands because of commandspy.hide, but nobody else has that.

Example below, Player AutumnEmber logged on, typed the following:

/list
/rtp (did not show up)
/back  (did not show up)
/home
/back (did not show up)
/back (did not show up)

The Coreprotect data is under that (in reverse order) in the screenshot, so you can see what she typed.

The spy area in the config file is below (I added cmi staffmsg so staff wouldn't see double all the time):

  Spy:
    # Commands in this list will not be shown when command spy is enabled for player for security/privacy reasons
    BlackListed:
    - cmi staffmsg
    - register
    - login
    - l
    # Players without cmi.security.admin will only see commands from this list with command spy feature
    CommandList:
    - cmi spawn
    - cmi tp
    - cmi tpa
    - cmi heal
    - cmi feed
    - cmi fly

**Comment by tmellen** [comment]
The weird thing -- /home is aliased to /cmi home, and /back is aliased to /cmi back, but they don't show. /list is aliased to /cmi list, and it shows. /rtp has no alias...

**Comment by tmellen** [comment]
Also: The console lists the commands:

[INFO] AutumnEmber[/73.146.155.245:62245] logged in with entity id 868421 at ([world]-83.74913070547674, 67.0, 373.5601198661469)
[INFO] AutumnEmber issued server command: /list
[INFO] AutumnEmber issued server command: /rtp
[INFO] AutumnEmber issued server command: /back
[INFO] AutumnEmber issued server command: /home
[INFO] AutumnEmber issued server command: /back
[INFO] AutumnEmber issued server command: /cmi back

So it looks like /back and /cmi back neither show.

**Comment by tmellen** [comment]
Ok. Figured it out. It's any command added to a warmup.

RTP was working fine, added a warmup, and can no longer see it in commandspy.

cmi back is also in my warmUps.

**Comment by tmellen** [comment]
Closing this and re-opening with that info as new.
