### ISSUE TITLE
Commad not work

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#3841]
**Description of issue:**
I try get help from floris, but he don´t understand the error properly. 

/cmi attachcommand !limiteduse:4!;;!cc!cmi rt [playerName] !;;!cc!cmi sethome hem [playerName]
This work !limiteduse:4!;;!cc!cmi rt [playerName]
and this !cc!cmi sethome hem [playerName] work, but not a combo of this two commands.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
27.07 22:02:10 [Server] INFO Can't find player with this name!
27.07 22:02:10 [Server] INFO You correctly created the home with name of hem!
```

**Cmi Version (using`/cmi version`):** 
8.7.4.0 mysql
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
110
**Relevant plugins (Delete if this isn't needed):**
cmi

**Comment by variananora** [comment]
Incorrect format, you inserted an extra `!` at the end of `cmi rt [playerName]`
It should be like this: `/cmi attachcommand !limiteduse:4!;;!cc!cmi rt [playerName];;!cc!cmi sethome hem [playerName]`

**Comment by Zrips** [comment]
Simple error in formatting, as @variananora pointed out, you have extra ! which causes for command to fail. Separation of commands/options is ;; some specific options are defined by surrounding with !! while specialized commands uses similar  format where you will have condition which ends with ! like hasperm:cmi.command.heal! or asPlayer! and similar.

**Comment by broken1arrow** [comment]
> 
> 
> Incorrect format, you inserted an extra `!` at the end of `cmi rt [playerName]`
> It should be like this: `/cmi attachcommand !limiteduse:4!;;!cc!cmi rt [playerName];;!cc!cmi sethome hem [playerName]`

He was not so clear on this on his wiki. Can i set a delay between this command?

**Comment by variananora** [comment]
I believe you can't. You can try to make a custom alias to make it happen or make a feature request for a delay.

**Comment by broken1arrow** [comment]
> 
> 
> I believe you can't. You can try to make a custom alias to make it happen or make a feature request for a delay.

Yes that work fine, but how i do if i want a permission to use it? 

Also if i set permission, it say in console Can't find player with this name!, when i try like !cc! or asConsole! , with out permission /cmi attachcommand randomteleport work, but not /cmi attachcommand !cc!randomteleport or /cmi attachcommand !cc!randomteleport [playerName]
