### ISSUE TITLE
Players cannot make homes or teleport above the nether roof

### ISSUE THREAD

**Issue by thetrueprime** [Zrips/CMI#3844]
Problem
---
Even when this config option is set to false, players are still unable to teleport to players or make homes above the nether roof. 
Is there another option that is affecting this, or permission players need?

**CONFIG SECTION:**
```
  # Will teleport players down from nether 'roof'
  PreventPlayersOnNetherRoof: false
```

---

**Cmi Version (using`/cmi version`):** CMI: 8.7.2.6 BungeeCord

**Server Type (Spigot/Paperspigot/etc):**  paperspigot

**Server Version (using `/ver`):** git-Paper-99 (MC: 1.16.1)

**Comment by dragontekgaming** [comment]
Have you tried updating CMI/Paper? Both should be as up to date as possible.

**Comment by CloudeLecaw** [comment]
This normal and called netherroof protection. Without permission they cant tp rhe netherroof. Thus is a feature to prevent glitching up to the netherroof, what is a glitch. If you want this for your players give them the bypass.

**Comment by Zrips** [comment]
@thetrueprime 
Cant reproduce this one at this moment. As of testing i can properly teleport to the nether roof and create homes and teleport to them without any issues even if they are located above nether roof. Test it without any other plugin to make sure that its not a another plugin causing this.
