### ISSUE TITLE
Players stop flying on relog

### ISSUE THREAD

**Issue by Crazzyguyy** [Zrips/CMI#3845]
if a player if flying with /fly then relogs, even though their fly mode stays on they still start falling.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  # If player will have cmi.worldlimit.fly.bypass permission node, fly mode wont be changed
```

---

**Cmi Version (using`/cmi version`):** 
8.7.4.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-117

**Comment by CloudeLecaw** [comment]
Thusbisses come from multiverse ir PerWorldInventory not from cmi ;)
Without bypass permission you cant fix it.

**Comment by Zrips** [comment]
@Crazzyguyy This can be caused by another plugin changing players fly mode. You might need to retest this without any other plugin.
