### ISSUE TITLE
Cmi Gamerule 1.16.1

### ISSUE THREAD

**Issue by Victor75007** [Zrips/CMI#3846]
**Description of issue:**

Hello,

I've tried setup the world gamerule with cmi, but i got an error.
'"An internal error occurred while attempting to preform this command"'

---

**ERROR :**
```
https://pastebin.com/XC3r43Kx
```
---

**Cmi Version (using`/cmi version`):**  8.7.4.0 

**Server Type (Spigot/Paperspigot/etc):** Paper spigot with Bungeecord

**Server Version (using `/ver`):** This server is running Paper version git-Paper-116 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
This will be fixed with next update
