### ISSUE TITLE
New Voteplaceholder does not work - just shows 0

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3849]
The new placeholder %cmi_user_dailyvotecount% only showing 0 on our server?
We registerted a few votes on our server today....

![Snag_192d5bb](https://user-images.githubusercontent.com/12080017/88724652-2a32e980-d12b-11ea-9c2e-32e9b80ba852.png)

![Snag_19358a7](https://user-images.githubusercontent.com/12080017/88724696-3e76e680-d12b-11ea-90f0-3cc14fa00731.png)

![Snag_1959df3](https://user-images.githubusercontent.com/12080017/88724936-97df1580-d12b-11ea-98c2-f35d0eb88b7d.png)

![Snag_19817cd](https://user-images.githubusercontent.com/12080017/88725161-f7d5bc00-d12b-11ea-9d99-6c868594141d.png)
last pic shows the plaers votes before and after the vote. just to show that CMI is increasing so also counting it correctly.
seems like the placeholde just dont work

**Comment by Zrips** [comment]
If you dint set max daily votes then it will not show up, you need to enable daily vote limit for this to start counting them, otherwise we will ignore it entirely.

**Comment by CloudeLecaw** [comment]
You mean this option in the votifer section?

`  MaxVotesInADay: 0`

so we are having 7 votes - that can be preformed once a day. So we need to set this to 7?
I hope this does not delet the votelists? and topvote lists where some users allready have a few 1000 votes collected :3

**Comment by Zrips** [comment]
Yes, this should be set to 7 which will indicate that you cant have more than 7 votes in a day. And no, it will not delete old vote count, its separate calculation entirely.
