### ISSUE TITLE
No permission to do buttonteleport

### ISSUE THREAD

**Issue by CitrusFruit** [Zrips/CMI#385]
Description of issue or feature request:

I am OP and have * but it's saying I have no permissions to teleport to a players location.
Even double checked with LuckPerms and it's showing I have the permission -
https://i.imgur.com/vgXxXz8.png

ERROR (IGNORE IF YOU HAVE NO ERROR):
https://i.imgur.com/Qrk6W47.png

Cmi Version (using`/cmi version`):  7.7.6.0
Server Type (Spigot/Paperspigot/etc): Spigot
Server Version (using `/ver`): Latest 1.12.2

**Comment by LogGits** [comment]
Confirmed. Double output of "You don't have permission!".

**Comment by LogGits** [comment]
Should be fixed in the next build. Let us know if its still an issue.
