### ISSUE TITLE
No Color Support (Hex or RGB) in EventHandler, Scheduler, ect

### ISSUE THREAD

**Issue by kiloRs** [Zrips/CMI#3850]
**Description of issue:**
The Hex format {#XXXXXX} currently doesnt produce the selected color in the eventhander and scheduler.
It produces the minecraft colors (which arent even similar).
I did notice that the color blue I used seem to work, but another color diverted to green.
Im kind of confused how this could be happening but would request it to be fixed?

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
You dint provided server version and no actual examples what you used and where exactly. 
Just FYI hex colors are for 1.16+ servers only. tested event commands and scheduler, bot processes colors correctly at this point. So if you still having issues, please open ticket with more information about it
