### ISSUE TITLE
bug CMI + PaperMC with aqua_affinity enchant

### ISSUE THREAD

**Issue by hitakiller** [Zrips/CMI#3852]
**Description of issue:**
When moving an item with aqua_affinity enchant from a slot to another in inventory, this enchant disappear from item.
I've test this issue with many cmi version to find where it appears.
This issue only happen with CMI and paper, i've tried with a barebones server (only paper), with Paper + CMI and with spigot + CMI. It happened on CMI + Paper but NOT on CMI + Spigot.
Versions of CMI tested : 8.7.1
---
No error in console.
No config option with "aqua_affinity".
---

**Cmi Version (using`/cmi version`): 8.7.1 (and have tested olders with same results)** 

**Server Type (Spigot/Paperspigot/etc): Papermc 1.16.1 #80 (tested avec paper #123, same result)** 

**Server Version (using `/ver`): 1.16.1 #80 and #123 (latest stable)** 

**Relevant plugins (Delete if this isn't needed): Only cmi + Vault during testing**

**Comment by variananora** [comment]
Can't replicate with CMI 8.7.4.1 with Paper 1.16.1-128
Try to update your CMI.

**Comment by hitakiller** [comment]
Seems to function with a reset of config, thank you for your help !
