### ISSUE TITLE
/give command not converting color codes

### ISSUE THREAD

**Issue by trickman325** [Zrips/CMI#3856]
@Zrips 
**Description of issue:**
/give command is not converting colour codes in both name and lore values

this is the command being used:
`cmi give %player% diamond_boots {display:{Name:"\"&4&lNether Walkers\"",Lore:["\"&8&m&l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l \"","\"&7Tier: &bThe Bifrost &6August 2020\"","\"&8&m&l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l &l \""]},Enchantments:[{id:mending,lvl:1},{id:unbreaking,lvl:3},{id:fire_protection,lvl:10}]}`

This is the outcome
![givecommand](https://user-images.githubusercontent.com/58171146/88875700-14294400-d265-11ea-827c-8f0b8cf20479.png)

-------------------------------------------------------------------------------
**Cmi Version (using`/cmi version`):**  CMI 8.7.4.1

**Server Type (Spigot/Paperspigot/etc):** Paper(378) 

**Server Version (using `/ver`):** 1.15.2-R0.1-SNAPSHOT

**Comment by variananora** [comment]
Never used that syntax, but it worked using another one.
`cmi give variananora diamond_boots n &4&lNether_Walkers l &8&m&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_ l &7Tier:_&bThe_Bifrost_&6August_2020 l &8&m&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_&l_ e mending:1 e unbreaking:3 e fire_protection:10`

**Comment by Zrips** [comment]
Will be fixed with next version
