### ISSUE TITLE
Featurerequest  %cmi_user_city%.

### ISSUE THREAD

**Issue by valenvaio** [Zrips/CMI#386]
Could be nice to have %cmi_user_city%. Can you do that?

**Comment by CloudeLecaw** [comment]
what is the sense of %cmi_user_city%? to see the cityname? wasnt that allready manges now by permission?
Your placeholder sounds like u want a Profil for all....

**Comment by valenvaio** [comment]
What is the sense of %cmi_user_country%? to see the countryname? Relax already CloudeLecaw. Or, paranoia, this is our everything? :)

**Comment by Zrips** [comment]
Next version should have it.
