### ISSUE TITLE
%cmi_user_dailyvotecount% does not work in shedulers

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3860]
Well the thread sais all^^
%cmi_user_dailyvotecount% does not work in shedulers
would be nice if you can fix this.

**Comment by Zrips** [comment]
Not a bug in particular. there is fundamental issue with placeholders in schedulers where we need to have them in 2 separate modes where in one case we need to replace placeholders before passing them to the command, like player name, while in another case we should not replace placeholders before passing it to the command, best example would be bossbar messages where we need actual placeholder in title and not a translated version of it. Currently we have first variation working, we cant have both of them unless i can think of some weird work around for this issue
