### ISSUE TITLE
Consistency for cmi check* commands

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3863]
Hi there :)

When you do /cmi checkcommand meow, it will return nothing since there's no meow commands, but it will show 'something' with a pagination thingy. But the cmi checkperm meow command, it returns nothing when there's nothing, and says "there were no permissions found" and looks different. 

They're kiiiinda the same type of commands, so kindly requesting (to mainly satisfy my ocd probably) to have the same type of output for both commands when there's nothing to report back. 
<img width="986" alt="Screenshot 2020-07-31 at 08 27 37" src="https://user-images.githubusercontent.com/28841349/89006907-fe208f80-d307-11ea-9a85-1372e0fefe4f.png">

**Comment by Zrips** [comment]
Agreed
