### ISSUE TITLE
problem with certain ranks not working

### ISSUE THREAD

**Issue by Anaton546** [Zrips/CMI#3865]
I have 7 ranks in my ranks.yml file, and in /cmi ranklist, but for some reason in /cmi ranklist and in the info of the rank, it says the 3 last ranks are all a "last" rank, meaning it doesn't automatically upgrade you to them, even though they all have a "next rank: " 
![image](https://user-images.githubusercontent.com/67478887/89014500-3e8b0800-d31e-11ea-8753-ef22e55dd034.png)
![image](https://user-images.githubusercontent.com/67478887/89014534-4d71ba80-d31e-11ea-9db3-6560f6e0f6de.png)

Ranks.yml (needed to be a zip to upload here):
[ranks.zip](https://github.com/Zrips/CMI/files/5005848/ranks.zip)

**Cmi Version (using`/cmi version`):** 
8.7.3.3
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
git-paper-40 (1.16.1)

**Comment by Zrips** [comment]
You have typo in your ranks file
**nextRanks** change into **NextRanks** for those last 2 ranks
