### ISSUE TITLE
AFK bypass fix Request

### ISSUE THREAD

**Issue by w41k3r26** [Zrips/CMI#3867]
**The players are able to bypass auto afk even when set to smart mode**

So recently I made auto afk kick for a 20 mins due to players afking at massive farms and causing tps lag. But then i found that just by using an auto clicker, they just put on/put off a piece of armor to bypass the auto afk which in turn dosn't kicks them.

Would be happy to see a fix in the next update or any suggestion to tackle this issue.

Thanking- w41k3r#1371

**Comment by CloudeLecaw** [comment]
At the. Moment you can bypase afk in many ways. Some stand on a piston and let them move uo and down for a sec conecting to a clock. This also breaks afk

**Comment by w41k3r26** [comment]
> At the. Moment you can bypase afk in many ways. Some stand on a piston and let them move uo and down for a sec conecting to a clock. This also breaks afk, when the char is moving thus is breaking afk. There need to be some adjustme ts that sees if the player is interacting too, not just by moveing the Charakter. 

Yea. So in conclusion, the afk system could be improved.

**Comment by Crazzyguyy** [comment]
https://youtu.be/T1qU93y2QR4
https://youtu.be/0l5nNtvFWQA

2 others

**Comment by Zrips** [comment]
getting fix with next version
