### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AlfreDGR** [Zrips/CMI#3869]
**Description of issue:**
net.minecraft.server.v1_16_R1.ReportedException: Loading entity NBT
>.... [07:15:49 WARN]: at net.minecraft.server.v1_16_R1.Entity.load(Entity.java:1824)
>.... [07:15:49 WARN]: at net.minecraft.server.v1_16_R1.WorldNBTStorage.load(WorldNBTStorage.java:91)
>.... [07:15:49 WARN]: at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.loadData(CraftPlayer.java:857)
>.... [07:15:49 WARN]: at com.Zrips.CMI.NBT.v1_16_R1.getPlayer(v1_16_R1.java:190)
>.... [07:15:49 WARN]: at com.Zrips.CMI.Containers.CMIUser.getPlayer(CMIUser.java:418)
>.... [07:15:49 WARN]: at com.Zrips.CMI.Containers.CMIUser.getPlayer(CMIUser.java:410)
>.... [07:15:49 WARN]: at com.Zrips.CMI.commands.list.saveall$1.run(saveall.java:72)
>.... [07:15:49 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
>.... [07:15:49 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [07:15:49 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>.... [07:15:49 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [07:15:49 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [07:15:49 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [07:15:49 WARN]: Caused by: java.lang.IllegalStateException: EntityPoseChangeEvent may only be triggered synchronously.
>.... [07:15:49 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595)
>.... [07:15:49 WARN]: at net.minecraft.server.v1_16_R1.Entity.setPose(Entity.java:378)
>.... [07:15:49 WARN]: at net.minecraft.server.v1_16_R1.EntityLiving.entityWakeup(EntityLiving.java:3440)
>.... [07:15:49 WARN]: at net.minecraft.server.v1_16_R1.EntityHuman.wakeup(EntityHuman.java:1297)
>.... [07:15:49 WARN]: at net.minecraft.server.v1_16_R1.EntityPlayer.wakeup(EntityPlayer.java:1196)
>.... [07:15:49 WARN]: at net.minecraft.server.v1_16_R1.EntityHuman.entityWakeup(EntityHuman.java:1323)
>.... [07:15:49 WARN]: at net.minecraft.server.v1_16_R1.EntityPlayer.loadData(EntityPlayer.java:274)
>.... [07:15:49 WARN]: at net.minecraft.server.v1_16_R1.Entity.load(Entity.java:1737)
>.... [07:15:49 WARN]: ... 12 more

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by mrfloris** [comment]
Can you share the output of these two commands please?
```
/ver
/cmi version
```

**Comment by AlfreDGR** [comment]
Checking version, please wait...
>.... [12:29:39 INFO]: Previous version: git-Paper-129 (MC: 1.16.1)
>.... [12:29:39 INFO]: You are running the latest version

**Comment by AlfreDGR** [comment]
>....=>.... [12:29:53 INFO]: --------------------------------------------------------
>.... [12:29:53 INFO]: Versión de CMI: 8.7.5.1 SqLite
>.... [12:29:53 INFO]: Server: Paper(130) 1.16.1-R0.1-SNAPSHOT
>.... [12:29:53 INFO]: CMI economy: Activado Vault: 1.7.3-b CMI Chat: Desactivado
>.... [12:29:53 INFO]: Modules -> 51 enabled 0 disabled:

**Comment by AlfreDGR** [comment]
This error appear all time

**Comment by mrfloris** [comment]
Do you know what happens in the game that triggers this error to come up?
If a feature not working in the game, and then this shows? For example when someone places an armor stand, or copies one, or tries to /cmi ride, or maybe sleeps in a bed or is flying with elytra?

**Comment by Zrips** [comment]
Error seams to be caused by a player in a bed while he is offline. Will make some fix to mitigate this issue.
