### ISSUE TITLE
[information] Duplication of the public message

### ISSUE THREAD

**Issue by valenvaio** [Zrips/CMI#387]
Аfter installation https://www.spigotmc.org/threads/chatlog.29502/

There is a duplication of the public message, if the players on different servers. 
Bungeecord. 
CMI. 
Public message over bungeecord = true.

```
message
%1$s message
```

**Comment by valenvaio** [comment]
https://www.spigotmc.org/threads/chatlog.29502/page-15#post-3003566

**Comment by LogGits** [comment]
Are you still having this issue on the latest build?

**Comment by valenvaio** [comment]
Yes. Having.

Solder: message
%1$s: message

**Comment by LogGits** [comment]
This should have been resolved by now, are you still experiencing thins in 8.2.0.0?

**Comment by Baktus79** [comment]
#1183
