### ISSUE TITLE
Virtuellmenu

### ISSUE THREAD

**Issue by Katzatrophe** [Zrips/CMI#3870]
The funktion /anvil und /workbench for:

- furnace | /furnace
- brewing_stand | /brewingstand
- enchanting_table | enchantingtable
- smoker | /smoker
- blast_furnace | /blastfurnace
- cartography_table | /cartographytable
- fletching_table | /fletchingtable
- grindstone | /grindstone
- smithing_table | /smithingtable
- stonecutter | /stonecutter

**Comment by RSLuke** [comment]
Up
