### ISSUE TITLE
Tab vanish

### ISSUE THREAD

**Issue by KingsRequin** [Zrips/CMI#3871]
**Description of feature/improvement request:**
i would like to request the ability to hide vanish inline with %cmi_bungee_current_[serverName]%
---
### Detailed explanation of what it should do, when and in what situation: ###
At the moment when a player in Vanish is connected the players see the number of players online, even those in Vanish.

### Basic explanation as to why this feature is needed and/or useful to have: ###

I find that logical because the vanish is used to not be seen by other players.

Thanks !

**Comment by Zrips** [comment]
Will do
