### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Relaxing9** [Zrips/CMI#3873]
**Description of issue:**
NPE when trying to do a hex color on glow

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**

[https://pastebin.com/tFMNeKsg](https://pastebin.com/tFMNeKsg)

---

**Cmi Version (using`/cmi version`):**  CMI: 8.7.5.1

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-9639cf7-8fb6585 (MC: 1.16.1)

**Comment by Zrips** [comment]
You cant have hex colors on glow, sadly. It only supports predefined old colors. Will fix error to prevent this one from showing up for others
