### ISSUE TITLE
Can the entity information on a horse (Speed/Jump) be more clear?

### ISSUE THREAD

**Issue by farisjaclyn** [Zrips/CMI#3874]
Can the entity information on a horse (Speed/Jump) be more clear?

---
Hello, I'm curious if we can make the entity information on the horse more clear. 
![entity info](https://user-images.githubusercontent.com/46360512/89111650-0a970c00-d41e-11ea-8fba-5c54e5c23df3.JPG)

Suggested Display Info,

Horse: 3.55 block Jump 7.65 Block Speed per 1 Second

Thank you.

**Comment by CloudeLecaw** [comment]
You know u can translate this to you desire in langfile?

**Comment by farisjaclyn** [comment]
> You know u can translate this to you desire in langfile? Just look there for Horse and design to your liks

Thank you. Where is the "Langfile" located? I'm not seeing it.

**Comment by CloudeLecaw** [comment]
I  the subfolder called translations ;) if you have not changed your language in config the  its thr en.yml file

**Comment by Zrips** [comment]
99.7% of text you see printed by plugin is translatable. There might be some specific places where i dint bother to include those into locale file, but in general everything is.
