### ISSUE TITLE
UnCondensing hay block issue

### ISSUE THREAD

**Issue by rikyriky232** [Zrips/CMI#3875]
**Description of issue:**

If you uncondense hay block, it will produce wheat while retaining the original item being uncondense. Basically, the hay block does not disappear after uncondense. (It should be deleted to avoid duplication)

-

![image](https://user-images.githubusercontent.com/40695735/89111686-6b106280-d48b-11ea-8582-b80aeaffe6aa.png)

**Comment by Zrips** [comment]
Will be fixed with next version
