### ISSUE TITLE
Custom text repeating line if text is one line?

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#3876]
**Description of issue:**
I had a custom text that repeats its second line twice, that's supposed to not be doing that.
Here is the ctext file that I used to test it out.
https://paste.md-5.net/ihibetikeh.xml
---

**Cmi Version (using`/cmi version`):** 8.7.5.0

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot

**Server Version (using `/ver`):** 1.15.2 build 354

**Comment by CloudeLecaw** [comment]
Posting the link like this is not so good.
Have you tried <T>Votelink to our site</T><URL>yourvotelink</URL>
?

**Comment by Zrips** [comment]
@blek-id 
Will fix issue with duplicated url, but in general it is recommended to use appropriate format which is allot more flexible and you cat get allot better looking results. For example
`<T>Vote for us!</T><H>Click To Vote!</H><URL>https://minecraft-mp.com/server/218963/vote?username=[playerName]</URL>`
