### ISSUE TITLE
Add Support To Enchant Modded Items

### ISSUE THREAD

**Issue by RupticMC** [Zrips/CMI#3877]
**Description of feature/improvement request:**
Add the ability to enchant modded items (only tested on 1.7.10, have not tried for 1.12 but I assume 1.12 has even less support for modded) like essentials is able to.
---
### Detailed explanation of what it should do, when and in what situation: ###
When doing /enchant with a modded item in hand, you should be able to add any enchantment you want.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Useful to put those enchantments on modded items like a pickaxe from Biomes O Plenty.

Gives an error when trying... https://paste.helpch.at/ojujecexud.apache

**Comment by CloudeLecaw** [comment]
you forgot to inform us about the server and CMI-Version your using,.....

**Comment by RupticMC** [comment]
> you forgot to inform us about the server and CMI-Version your using,.....

Cmi Version (using/cmi version):
8.7.5.0
Server Type (Spigot/Paperspigot/etc):
UraniumMC (Basically a better version of Thermos/Cauldron for modded 1.7.10) Uses Spigot...
Uranium version 1710-dev-5-B271-31d6587
Server Version (using /ver):
dev 1.7.10-R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment]
sorry.
CMI does not Support Versions lower then 1.8 anymore..
