### ISSUE TITLE
[Support Question] Can't find an information after /cmi info command was updated.

### ISSUE THREAD

**Issue by w41k3r26** [Zrips/CMI#3878]
After a recent update, the command `/cmi info` was updated, the contents were condensed, and after the update i wasn't able to find the info on PLAYER'S FIRST JOIN DATE. This feature is extremely useful to me for checking requirements for my staff, would be glad to receive help.

Thanking: `_w41k3r#1371`

**Comment by Zrips** [comment]
Its under IP section. As this information isint so useful and rarely looked at, it was moved to different section to avoid cluttering.
