### ISSUE TITLE
Specialized command crashing - Residence and CMI conflict?

### ISSUE THREAD

**Issue by IgnisCraft** [Zrips/CMI#3879]
**Description of issue:**

Spigot Watchdog Thread/ERROR com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:470)
spammed 10000 times and my server crashes. Every time i use a /residence command.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

its crashing on both 8.7.5.1 & .2

**Server Type (Spigot/Paperspigot/etc):** 
originally paperspigot 131, but the crashing started coming when we tried to revert back to spigot 1.16

**Server Version (using `/ver`):** 
above 
**Relevant plugins (Delete if this isn't needed):**
Residence, CMI

**Comment by CloudeLecaw** [comment]
May it woulde be nice to know whats your current server version, cki version and residence version. Use cmis /cmi version to get informed about. U can paste the Screenshot of it if you dont wanne rewrite the output ;)

**Comment by Zrips** [comment]
Well, error log would be nice to see. But from what you said it should be stack-overflow issue where you have specialized command performing itself which creates infinite loop. Check your specialized command setup, or custom alias, somewhere you have set for /residence to perform /residence which by itself performs /residence and so on.
