### ISSUE TITLE
MOTD Bug

### ISSUE THREAD

**Issue by insanegyros** [Zrips/CMI#3883]
**Description of issue or feature request:**

When I run command `/cmi setmotd <fancy_colored_motd>`, after restart, weird characters appear *(screen below)*. Every restart from then doubles the amount of those characters.

**ERROR:**
![obrazek](https://user-images.githubusercontent.com/34373776/89271682-5378db80-d63d-11ea-8a7e-e3fffda5cb6f.png)

**Cmi Version (using`/cmi version`):** 
CMI 8.7.5.2

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
git-Paper-131

**Relevant plugins (Delete if this isn't needed):** 

- ChestProtect
- CMIPaperLib
- CoreProtect
- Herochat
- LuckPerms
- MaxBansPlus
- PlaceolderAPI
- PlugMan
- ProtocolLib
- Vault

**Comment by Zrips** [comment]
Could you give exact example of your motd?

**Comment by insanegyros** [comment]
> Could you give exact example of your motd?

I used `/cmi setmotd &l&3JND &bSemi Vanilla`. At beginning it saved okay, displayed okay, but after restart it started adding that mess and ended up like `\u00C2\u00A73\u00C2\u00A7lJND \u00C2\u00A7bSemi \u00C2\u00A71Vanilla` in the server.properties.

**Comment by insanegyros** [comment]
![obrazek](https://user-images.githubusercontent.com/34373776/89389859-42e06800-d706-11ea-89c3-de8c89395522.png)
Nope, I am not adding these myself...

**Comment by Zrips** [comment]
Cant reproduce this ones at the moment. You will have to test this one without any other plugin but CMI only and if issue persists then shutdown server, rename CMI folder into CMI_Backup, start server and retest again if issue persists. CMI doesn't do active motd changes. those can only be activated with command, so something is doing that, it could be CMI with some automated commands or another plugin. But at this point i cant reproduce and it should not originate from CMI in general.
