### ISSUE TITLE
Warps/Kits not being saved to file on '/cmi reload' or server restart

### ISSUE THREAD

**Issue by InfinityAspire** [Zrips/CMI#3885]
**Description of issue:**
When using the in-game GUIs to create and customise warps and/or kits, upon reloading CMI or rebooting the server, the warp and/or kit will revert to whatever it was when it was first created, disregarding all changes made to it.

---

**Cmi Version (using`/cmi version`):**
8.7.5.2

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
Paper 1.16.1 Build 131

**Comment by Zrips** [comment]
tested kits and warps, both gets saved properly and loaded with next server restart.
