### ISSUE TITLE
Prices bug

### ISSUE THREAD

**Issue by redbourd** [Zrips/CMI#3886]
Hello,
I have Jobs Reborn 1.16.1 but it happens that the prices displayed in / jobs browse and the prices in the config are different. It's the same when I break the block I don't win the same ...
Is this a version bug? If so, when will it be settled?
https://cdn.discordapp.com/attachments/526402919826849804/740239152359931944/unknown.png
https://cdn.discordapp.com/attachments/526402919826849804/740239339119837209/unknown.png
https://cdn.discordapp.com/attachments/526402919826849804/740242433148846221/unknown.png

**Comment by Zrips** [comment]
This is CMI github, please post this ticket at Jobs
