### ISSUE TITLE
If player has no bedhome, cmi go thru list of spawns and use all

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#3887]
If player not have bedhome, it go true the ReSpawn: list Instead of select next it fire of all you have in the list. I use two homeLocation becuse of testing (but if i have only one homeLocation it same problem).

So it use all this and not detect homeLocation work (it teleport player to he´s home and seconds later he is in spawn).
    - bedLocation
    - homeLocation
    - delay! 5
    - homeLocation
    - delay! 5
    - spawn
    - worldSpawn

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
ReSpawn:
  # Time in seconds to make player immortal after he respawns
  # Can be used to prevent respawn camping
  # Set to 0 if you want to disable it
  Immortality: 5
  # If you want 3rd party plugin to handle player respawning, simply set this to false and reload plugin
  Enabled: true
  Global:
    # Defines respawn order if defined world is not present in Specific list
    # Possible respawn locations: anchor, bedLocation, spawn, homeLocation, worldSpawn, warp![warpName]
    # Spawn is preset spawnlocation with /cmi setspawn command, that location should have RespawnLocation set to true
    # bedLocation is location set by interacting with bed, BedInteraction should be set to false and players requires cmi.bedhome to set bed location
    # homeLocation is location set by player which is with default (Home) name, if that one doesnt exist then first in the list will be used if possible
    # worldSpawn is location preset to this world, this is not CMI location but default world spawn location
    # warp![warpName] can be any valid warp you set for players to be teleported, they will bypass any requirements for that warp
    PriorityOrder:
    - bedLocation
    - homeLocation
    - spawn
    - worldSpawn
  # Defines respawn order for defines worlds
  # Remove world if you want to leave respawn handling for server or 3rd party plugin
  Specific:
    Midgardsaga:
    - bedLocation
    - homeLocation
    - delay! 5
    - homeLocation
    - delay! 5
    - spawn
    - worldSpawn
    Midgardsaga_nether:
    - worldSpawn
    - bedLocation
    - homeLocation
    - spawn
    Midgardsaga_the_end:
    - bedLocation
    - homeLocation
    - spawn
    - worldSpawn
#######################################
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
8.7.5.3
**Server Type (Spigot/Paperspigot/etc):** 
papermc
**Server Version (using `/ver`):** 
131
**Relevant plugins (Delete if this isn't needed):**
CMI

**Comment by broken1arrow** [comment]
I send a video. when player get fist killed, he come first to the home he set and second to spawn. 

https://www.youtube.com/watch?v=uiSPl8N6YnE&feature=youtu.be

**Comment by Zrips** [comment]
Dont use delay! 5 its not for setting respawn priorities

**Comment by broken1arrow** [comment]
> 
> 
> Dont use delay! 5 its not for setting respawn priorities

I only do it for testing, it not work if i use this below ether. You can you try it, it not work as it should (it work fine before, I not know when it breaks). most players have a bedhome, but if you dont. You end up in spawn.
Midgardsaga:
- bedLocation
- homeLocation
- spawn
- worldSpawn

**Comment by broken1arrow** [comment]
If someone get this problem, check multiverse core (if you have it install). I have to remove all worlds beside the Multiverse world in the world.yml. 

I don´t know if it big downsides with this, but fix players home are more importan (I have send a bugreport too Multiverse-Core).
