### ISSUE TITLE
When players use any TP command, the first attempt always fails

### ISSUE THREAD

**Issue by ZeeRaider** [Zrips/CMI#3888]
When a players requests another player to TP to them or asks to TP to another player, the first time they enter the name of the player this wish to tp with, the "player is offline or doesn't exist" error happens every time.
I use AdvancedTeleport to handle my teleports and this was working just fine before CMI, now it doesn't matter if I use cmi tp or at tp, the error occurs.

---

**Cmi Version (using`/cmi version`):** 8.7.5.1
<img width="1440" alt="Screenshot 2020-08-05 at 04 08 24" src="https://user-images.githubusercontent.com/67307800/89367602-5d4c1e80-d6d1-11ea-81a5-8fa32e1b9021.png">

**Paperspigot

**Server Version (using `/ver`):** 

**AdvancedTeleport

**Comment by mrfloris** [comment]
If you don't want CMI to handle the teleporting, you have to make sure the related commands in CMI's Alias.yml file are set to false. So another plugin has access to these commands as usual. 
If another plugin for example uses /tpa, but CMI now installed has /tpa as well and might be enabled by default, this can be conflicting.

**Comment by CloudeLecaw** [comment]
Hm we noticed a simliar behavior since a few years with the teleport to the spawn. Very often on first attempt it tell the Position would not be save, on secound attempt it works. Since we se no way to fix this behavior we accepted the fact that you have to type /spawn twice sometimes.

**Comment by ZeeRaider** [comment]
I’ve since decided to change how my server handles people wishing to tp to each other so, this bug isn’t as relevant to me anymore.
That being said, this is a fairly major but and would get very irritating very quickly if I were relying on it for my server.
It is something that perhaps needs looking into, especially given that this seems specific to CMI.

**Comment by Zrips** [comment]
All those messages from your picture are from different plugin than CMI. While error message about unsafe location should only be output when you use CMI teleportation commands. So which plugin actually handles teleportations?

**Comment by ZeeRaider** [comment]
That is true - the things being, even when you use /cmi tp commands, it throws the same error on the first attempt.
This has only started since moving from essentialsX to cmi, with the same configuration with regards to using another plugin to handle teleporting.
The plugin that handles teleporting usually is AdvancedTeleport - but I have a GUI configured for my players and don't use alias commands, as such, when they click to teleport to another player, it executes the full command (e.g /cmi tphere <player types player name here> rather than the short alias of /tphere.
I've tested this every which way, so making the guy execute the command as CMI, the same result.

The only way that alias setup should have any impact is if I'm using short commands and it's conflicting, however - the same applies whichever plugin you specify to handle the teleports.

I hope that makes sense.

**Comment by Zrips** [comment]
Should no longer happen
