### ISSUE TITLE
MySql settings

### ISSUE THREAD

**Issue by ghost** [Zrips/CMI#389]
Hello,
I have asked serveral times on spigot discussion but still havent seen an answer.
So i ask it here: how can i make my CMI with MySql but only sync some stuff.
Nickname, Rank, mails, but not theire money, inventorys gamemodes etc.
In some other plugins i know you can change the names of the tables where the info gets saved into and that way you can make it to save it in different tables but for the stuff you want not to sync.

**Comment by LogGits** [comment]
As far as I am aware this is not possible. Thought it does seem like a useful feature.

**Comment by dangerORclose** [comment]
Yes this is possible have a look at the litebans settings file for example. That also does it that exact way. Now we are stuck with cmi to sync all or nothing so basically i don't see the usefull part of it atm. With that it would be excellent. Sync what you want with the servers you want.

**Comment by LogGits** [comment]
I was referring to it not being possible with cmi currently. It is still a great feature and will add an extra level of functionality.
