### ISSUE TITLE
Anti-AFK

### ISSUE THREAD

**Issue by Crazzyguyy** [Zrips/CMI#3890]
There is a simple anti-afk machine (2, actually)

https://youtu.be/T1qU93y2QR4
https://youtu.be/0l5nNtvFWQA
---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**

https://pastebin.com/Kv8BztMe
---

**Cmi Version (using`/cmi version`):** 
8.7.5.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-131 (MC: 1.16.1)

**Comment by Crazzyguyy** [comment]
I could add that the redstone machine does put the player afk, but i assume when they move to another block it puts them out, so they go afk for a fraction of a second.

**Comment by CloudeLecaw** [comment]
Duplicated thread

**Comment by Zrips** [comment]
getting fix with next version
