### ISSUE TITLE
Optimization CMI

### ISSUE THREAD

**Issue by WIBOR2002222** [Zrips/CMI#3892]
Is it possible to optimize CMI? (or unless it comes from me)

https://ibb.co/jgf0V44

**Comment by CloudeLecaw** [comment]
What you wanne Optimize? Each sever has its own settingsfile. If there would be an optimizer you would not need settings ;)
What can be recomment.. Disable modules thatnyou dont use or that are taken by other plugins. Take good care that you gave all groups correct permissions. Check twicw onn setting up you have all settings made correct suited to your server and worlds.

**Comment by WIBOR2002222** [comment]
Thanks for this information, I’ll look

**Comment by WIBOR2002222** [comment]
What's "twicw onn" ? Where can I set this up?

**Comment by Zrips** [comment]
You have something set for a scheduler which takes more server resources. Check what you have set for scheduler and optimize it.
