### ISSUE TITLE
Error when killing Citizens/Sentinal NPC

### ISSUE THREAD

**Issue by Verdux** [Zrips/CMI#3895]
I get this error in my console (sometimes) when a player kills an aggressive NPC on my server.

Error: https://pastebin.com/n2BKFF26

Paper [378]: 1.15.2
CMI: v8.7.5.3
Citizens version 2.0.27-SNAPSHOT (build 2060)
Sentinel version 2.1.5-SNAPSHOT (build 360)

**Comment by Zrips** [comment]
Should be fixed with next version
