### ISSUE TITLE
CMI spawner feature clashing with other plugins

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#39]
Can we get an option to fully disable anything cmi has with spawners? 

Its overlapping other plugins (even with the correct permissions) and still not working correctly. 

(all the spawners are pigs now)

**Comment by Kbryst** [comment]
Also a bug, all players have permission to place spawners but they are reverting back to pigs when they try. If they don't have permission to place spawners it places them and reverts them to pigs.

**Comment by MCTyler** [comment]
I recommend Just switching to CMI for Spawner support. Can you give us a reason to do a workaround so it will work with a outdated plugin?

**Comment by Zrips** [comment]
Well i can simply add option to completely disable any spawner handling, Which will include any drop, charge, spawner change, and so on, handling.
