### ISSUE TITLE
Possible bug winth inventories

### ISSUE THREAD

**Issue by Kubson6969** [Zrips/CMI#3901]
Since we have CMI for some reason idk doesn't happens to everyone but some players when they join to the servers their inventory it's empty and I had to retore it to them, there's no crash. I have InventoryRollback plugin just in case.

Paper spigot 1.16.1
Last version of CMI.

**Comment by CloudeLecaw** [comment]
You know that cmi dies not manage (store) inventories? They are saved wherebthey are allways saved. So the issue must be on an ither site ;)

**Comment by CloudeLecaw** [comment]
Did you know that relog also solves Problems like this in Most cases? 😉

**Comment by Zrips** [comment]
Cmi doesn't change players inventories if not specified. It could save them on players death and it can restore to previous saved state, but it doesn't manipulate players inventories on player join.
A way to reproduce this issue consistently would be nice to know and testing with only CMI installed to know that this originates from CMI would be nice too.
