### ISSUE TITLE
Request New Alias /oi for /cmi inv & /oe for /cmi ender

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#3904]
Quick simple one, adding `/oi` for **O**pen **I**nventory as an alias to `/cmi inv`

Also `/echest` & `/oe` For alias for `/cmi ender` From people that have used Essentails / OpenInv in the past and are used to these commands!

Thanks!

**Comment by Markusi13** [comment]
I second this. It would be so much more conconvenient.
Please add it 😄

**Comment by Zrips** [comment]
I can add, 30 second update. Tho you do have option to create custom alias if you want something like that. But for convenience sake will add for alias.yml file
