### ISSUE TITLE
Enchant level with tab-complete doesn`t work

### ISSUE THREAD

**Issue by levarar** [Zrips/CMI#3907]
After switching to a newer version of the CMI, the tab-complete broke when writing a command /enchant + name enchanment, example:
![image](https://user-images.githubusercontent.com/68510813/89665026-b211b400-d8e0-11ea-9572-2ce6eab82edb.png)
![image](https://user-images.githubusercontent.com/68510813/89665055-bb028580-d8e0-11ea-961e-38c5c9419b94.png)
+ Also I would like to remove unnecessary names of enchantments that do not correspond to the language that I have chosen (Russians):
![image](https://user-images.githubusercontent.com/68510813/89665153-e4231600-d8e0-11ea-9515-8cf9305700e6.png)
On the older version 8.7.4.1 there is no such problem, the list of plugins is the same

---

**8.7.5.3:** 

**Tuinity **

**Tuinity 1.16.1-R0.1-SNAPSHOT**

**Comment by levarar** [comment]
Im try update CMI to 8.7.5.5 - same problem

**Comment by Zrips** [comment]
Should get resolved with next update
