### ISSUE TITLE
FlyCharge and trampoline

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3911]
**Description of issue:**

---
Hi, when you're using some trampoline plugin (I'm using this https://www.spigotmc.org/resources/trampolin-plugin-config-1-7-1-15.72627/) then it take player's flied block from flycharge when they're "threw" into air from trampoline. Can you somehow fix it please? And I don't think author of trampoline can, because he's inactive and this is the only one trampoline plugin that works without errors etc. Please, could you try to do something with this? Players are losing they charged blocks when jumping on trampoline.

---

**Cmi Version (using`/cmi version`):**  
```
>.... [23:04:20 INFO]: CMI: 8.7.5.5 BungeeCord MySQL
>.... [23:04:20 INFO]: Server: Paper(133) 1.16.1-R0.1-SNAPSHOT
>.... [23:04:20 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: False
>.... [23:04:20 INFO]: Modules -> 38 enabled 13 disabled: customMessages, mirror, tablist, skin, cmiPlaytime, eventCommands, playerChatTag, ranks, firstJoinMessages, selection, attachedCommands, warmup, namePlates
>.... [23:04:20 INFO]: --------------------------------------------------
```
**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  git-Paper-132 (MC: 1.16.1)

**Relevant plugins (Delete if this isn't needed):** https://www.spigotmc.org/resources/trampolin-plugin-config-1-7-1-15.72627/

**Comment by Zrips** [comment]
What can i do is to prevent charge deduction when player lands on a slime block and exclude players with immortality. So it should resolve your issue. Next update

**Comment by Volgeop** [comment]
Hopefully it supports CraftBook bounce blocks too @Zrips ? Didn't test it yet

**Comment by Volgeop** [comment]
Yeah, doesn't work for Craftbook. IN config you have to put BounceBlocks to enabled mechanisms and then in mechanisms you should have something like this:
    BounceBlocks:
        blocks:
        - minecraft:slime_block
        - minecraft:black_wool
        sensitivity: 0.1
        auto-blocks:
            slime_block: 1,1,1
            black_wool: 0,1,0

You put sign under slimeblock or black wool with text [Jump] on second line and on third 10... it took player 110 to player
