### ISSUE TITLE
%cmi_user_display_name% broken after most recent update.

### ISSUE THREAD

**Issue by ablac** [Zrips/CMI#3914]
**Description of issue:**
When using the Tab Menu, %cmi_user_display_name% no longer works with most recent version update.

---

---
**Cmi Version (using`/cmi version`):** 
**Server Type (Spigot/Paperspigot/etc):**
**Server Version (using `/ver`):**
![image](https://user-images.githubusercontent.com/1701232/89739495-f1054e00-da35-11ea-97a3-42535f2230f4.png)

**Relevant plugins (Delete if this isn't needed):** 
PlaceholderAPI
BungeeTabListPlus

![image](https://user-images.githubusercontent.com/1701232/89739476-d0d58f00-da35-11ea-9bec-a49ded9ecb4a.png)

**Not that its really needed, but plugin list for possible compatibility issues:** 
![image](https://user-images.githubusercontent.com/1701232/89739510-2a3dbe00-da36-11ea-88a8-aba9f97d9788.png)

**Comment by OverBrave** [comment]
Yeah, not only "%cmi_user_display_name%"
Some placeholders broken.
![image](https://user-images.githubusercontent.com/47111280/89739657-356f0900-da8b-11ea-862f-994382f2b17a.png)

**Comment by Zrips** [comment]
Posted new version, was issue with PlaceholderAPI and new placeholder recognition system failing to work properly. Should be fixed now and in working order. Sorry for inconvenience.
