### ISSUE TITLE
Issue with hexcode color permission

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#3916]
**Description of issue:**

I found out the hexcode permissions with just letters, rather then a combination of letters and numbers, do not work
Like in the image below

**Permission tested:** cmi.colors.nickname.DDEEFF

![image](https://user-images.githubusercontent.com/5664135/89742891-39f0ed00-da9e-11ea-821e-8f25c58d78a9.png)

**Comment by CloudeLecaw** [comment]
This only wirks for public meassage

**Comment by Sikatsu** [comment]
That is not true, it works with nicknames too (as I requested the feature with him in DMs)

**Comment by CloudeLecaw** [comment]
Normaly it should work wuth als types but its not introduced yet ;)

**Comment by Zrips** [comment]
Will be fixed with today's update
