### ISSUE TITLE
Allow hexcolor usage to be seperated from magic, italc, bold, etc. permission

### ISSUE THREAD

**Issue by ChiboYen** [Zrips/CMI#3917]
**Description of feature/improvement request:**
Currently, if I were to allow people to nick using colors, they would have to be given "cmi.colors.nickname.*", this is unsightly sometimes as it is hard telling who is who if you use magic characters. If I could allow only color usage through something like "cmi.colors.hex" without allowing modifications to the format of the nickname, it would make chat less annoying.
---
### Detailed explanation of what it should do, when and in what situation: ###
Cmi.colors.[type].hex could allow only hex color usage without allowing bold, underline, magic, etc text

### Basic explanation as to why this feature is needed and/or useful to have: ###
If I could allow only color usage through something like "cmi.colors.hex" without allowing modifications to the format of the nickname, it would make chat unable to be filled up with magic unreadable nicknames.

**Comment by CloudeLecaw** [comment]
You can eo this allready check the cmi Update history

**Comment by ChiboYen** [comment]
I appreciate your time in telling me what I may have done wrong. I have tried assigning cmi.colors.nickname.* and assigning negating permissions (I use luckperms, so "false" permissions) and it did not work, I have also tried to give the permission weights. The issue is that CMI does not check for negated permissions if someone has the cmi.colors.nickname.* (I used luckperms verbose to confirm this).

Your post proves my exact problem, I would like to be able to either:
1) Have a all hex color permission without modifiers (magic, bold, etc.)
2) CMI check to see if any are negated perms (cmi.colors.magic set to false)

**Comment by CloudeLecaw** [comment]
Interesting...
I did it with pex.. 
1. Negating the Magic. One
2. Giveing me the rest (all colorperms)
Was working fine.. And i was unable to use the Magicformater
Well i try it aggain today with luckperms and tell you my result.. 
Really would wonder if this will not work with LP. 
But lets see :)

**Comment by ChiboYen** [comment]
LuckPerms is pretty much the industry standard, even pex's bukkit page redirects you to LP. Lemme know if you can reproduce the issue on luckperms, thanks

**Comment by Zrips** [comment]
Issue would be that player has wild card permission node, which is checked before anything else, so in case player has that one then we are not even bothering to check anything else in the text which can include quite few permission checks, so for performance sake we are skipping that if player already have every permission node. 
In general i would STRONGLY recommend to avoid using wild card permission nodes and give out specific ones. Even now with hex color support you will have people with crazy looking nicknames and you might want to have a control over that.
