### ISSUE TITLE
Latest CMI broke Alias via DiscordSRV

### ISSUE THREAD

**Issue by Relaxing9** [Zrips/CMI#3918]
**Description of issue:**
When running any alias in discord console, this error is generated in the console see below:

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
[https://pastebin.com/LFVFRL16](https://pastebin.com/LFVFRL16)

---

**Cmi Version (using`/cmi version`):** CMI: 8.7.5.7

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-9639cf7-f622793 (MC: 1.16.1)

**Relevant plugins (Delete if this isn't needed):** DiscordSRV 1.19.1

**Comment by Zrips** [comment]
Will be fixed with today's update
