### ISSUE TITLE
CrateReloaded can't seem to trigger CMI commands

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#3923]
**Description of issue:**

Updated to the latest version last night, and for some reason CrateReloaded seems to give this error now with certain rewards:

[11:33:08 ERROR]: [CrateReloaded] Was not able to execute /money give Sikatsu 3500. Check if the plugin is up to date?

**Comment by CloudeLecaw** [comment]
Have you tried it with /cmi money give too? /money is just an alias.. May there is an issue with it..

**Comment by Zrips** [comment]
"Latest version" is not really a version number. Doesn't seam to be an issue with other plugins performing alias commands at this moment. You might want to test this by using full command in case there is an issue with alias itself. If that doesn't help then some debuging needs to be done. As i don't have access to this plugin, cant really do anything like that myself at this moment.

**Comment by Sikatsu** [comment]
It's not a version number indeed, CMI: 8.7.5.8 BungeeCord.
Adding /cmi in front of it fixes this issue, but the alias worked on 5 versions earlier. 

If it's too hard to debug I will keep it with cmi in front of the command ^^

**Comment by CloudeLecaw** [comment]
money works fine on 8.7.5.8 could you check aggain your alias.yml?

**Comment by Sikatsu** [comment]
Money works fine, but no longer in cratereloaded.
I just use /cmi money for now and that works ^^

**Comment by Zrips** [comment]
@Sikatsu 
Well we need to know if its issue with alias handling from another plugin or its simply issue with alias being disabled or something similar

**Comment by Sikatsu** [comment]
I doubt it's because of alias handling from CrateReloaded, as it used to work a few updates ago and CrateReloaded didn't get an update, only CMI. But I could just use /cmi in front of it to fix it, or, if we really want to fix it, how could we debug it further?

**Comment by Zrips** [comment]
@Sikatsu 
Test this with another alias commands, especially with some more unique like /afkcheck or similar. We need to know if this issue with all alias commands or with some particular ones.
