### ISSUE TITLE
Sitting desync

### ISSUE THREAD

**Issue by JanPlazovnik** [Zrips/CMI#3929]
**Description of issue:**
When sitting down and changing your skin using the SkinsRestorer plugin, you are "ejected" from your sitting position but the server still thinks you're there. You can roam around but other players will see you as if you were still sitting normally. If they attack you or if you press shift, you get teleported back, and sitting is properly disrupted. Although, you can't interact with players or chests if they're not in range of your actual sitting body.

**Cmi Version (using`/cmi version`):** 
```
>.... [22:53:25 INFO]: CMI: 8.7.5.5 SqLite-> 8.7.5.8
>.... [22:53:25 INFO]: Server: Tuinity 1.16.1-R0.1-SNAPSHOT
>.... [22:53:25 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: False
>.... [22:53:25 INFO]: Modules -> 39 enabled 12 disabled: cuffed, tablist, ranks, portals, jail, elytraBoost, silentChest, vanish, namePlates, elytraLaunch, homeInteractions, bossBarCompass
```
**Server Type (Spigot/Paperspigot/etc):** 
Tuinity

**Server Version (using `/ver`):** 
```
=>.... [22:51:32 INFO]: This server is running Tuinity version git-Tuinity-"650532a" (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
```
**Relevant plugins (Delete if this isn't needed):**
SkinsRestorer [https://www.spigotmc.org/resources/skinsrestorer.2124/](url)

**Comment by Zrips** [comment]
This is not CMI bug, this is bug with SkinsRestorer plugin not properly updating players position with packets when we have player who is riding something. You will need to report this issue to SkinsRestorer developer as he should fix that at his end.
