### ISSUE TITLE
CustomText Copy to Chat without removing current chat

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3932]
We tried to create a smile page with custom text
`<T>&6&l☺</T><H>click on the smilie to paste in in chat</H><SC>:)</SC>`
we are working with filter that replace :) with  ☺

Our Problem if player write a text and klick on the smilie of the Customtext the text gets deleted and the smilie gets pasted
Is it possible to add something like <SSC> so that the think behind it get pasted behind and not replaced

![Snag_1c926411](https://user-images.githubusercontent.com/12080017/89836493-2a89a680-db67-11ea-8c05-e5e861a34db8.png)

![Snag_1c926dd5](https://user-images.githubusercontent.com/12080017/89836498-2bbad380-db67-11ea-8a88-d47351fdb001.png)
the text before got deleted :(

**Comment by mrfloris** [comment]
I wonder if this might be a technical limitation with what you can do with the api. Not sure you can actually mix and match

**Comment by the456gamer** [comment]
can you try shift clicking?
iirc it might work like that client side

**Comment by the456gamer** [comment]
yeah
> `insertion`
    String - contains text to insert. Only used for messages in chat. When shift is held, clicking the component inserts the given text into the chat box at the cursor (potentially replacing selected text). Has no effect on other locations at this time.
from https://wiki.vg/Chat

**Comment by CloudeLecaw** [comment]
i was suggesting this because i see no opion that i can past it into the text without deleting existing text

**Comment by the456gamer** [comment]
So did shift clicking the text work?

**Comment by CloudeLecaw** [comment]
no it does not the like get removed

**Comment by Zrips** [comment]
Will update wiki page, but we do have option to use <SI>:)</SI> which when shift+click will insert text into chat window without replacing existing one. This is limitation by minecraft and we cant really have only left click to add text, we need to use shift+click configuration
