### ISSUE TITLE
Playtimetop and AFK

### ISSUE THREAD

**Issue by levarar** [Zrips/CMI#3935]
Greetings, can you tell me how you can make sure that if a player goes to AFK, his time is in /playtimetop not included in this time rating, thanks.

**Comment by Zrips** [comment]
If you want to stop adding playtime to the player when he goes into afk mode then you could simply set afk->StopPlayTime in config file which will do that. Unless you want to hide player from playtimetop when player goes afk, which would be a strange request

**Comment by levarar** [comment]
Can you please give an example of how to enter the afk->StopPlayTime into the config.yml?

**Comment by levarar** [comment]
Problem solved
