### ISSUE TITLE
Tab-complete doesn't work with /msg

### ISSUE THREAD

**Issue by naikyys** [Zrips/CMI#3936]
Hey I would like to report that /msg won't tab-complete the name of the player. There are things like: warn,warps,world,weather and more.

---

**Cmi Version (using`/cmi version`):** CMI8.7.5.8

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** latest version

**Comment by CloudeLecaw** [comment]
if you have permission to cmi msg and no plugin that disturbs your tabcompltation like some anticheat plugins try then the msg works fine

![image](https://user-images.githubusercontent.com/12080017/89893524-cc95a700-dbd8-11ea-899d-f6c258a687f5.png)

**Comment by Zrips** [comment]
@naikyys 
You might have some interference from other plugins which tries to use those alias commands and overrides tab complete, try testing without any plugin but CMI only to rule out possible interference.
