### ISSUE TITLE
Dupe with kitpreview

### ISSUE THREAD

**Issue by ToxicPeople** [Zrips/CMI#3941]
**Description of issue or feature request:**

---Hello, I have an issue, the problem is that I enabled the kitpreview to the users and they began to dupe in one way, from one moment to another (because it coincides that there were blocks as kit icons) they began to remove the blocks and transform them into blocks normal.

**Cmi Version (using`/cmi version`):** 

 Versión de CMI: 8.7.5.1 BungeeCord  SqLite► 8.7.5.8
 Server: Paper(110) 1.16.1-R0.1-SNAPSHOT
 CMI economy: Activado Vault: 1.7.3-b(CMIEInjector) CMI Chat: Activado
Modules -> 51 enabled 0 disabled:
**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-110 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by CloudeLecaw** [comment]
What blocks you mean? (Screenshot?)
Have you made sure this also is possible with your server+cmi+permission Systems, without any others plugins Interrupting?

**Comment by Zrips** [comment]
@ToxicPeople 
I need more information here. Where exactly they take items from and how? Any way to consistently reproduce this issue? Is this only applies to the kit preview?

**Comment by ToxicPeople** [comment]
These photos are from before the user who took them transformed them into normal blocks.

=========================================================================
Kit preview dupe

![kitpreviewdupe2](https://user-images.githubusercontent.com/63988556/90019740-d4a72280-dc7c-11ea-81ae-0422acb46cf6.png)
![kitpreviewdupe](https://user-images.githubusercontent.com/63988556/90019746-d670e600-dc7c-11ea-94ce-f63589e9582a.png)
=========================================================================
Glow Gui Dupe

![glowguidupe](https://user-images.githubusercontent.com/63988556/90026204-01f7ce80-dc85-11ea-8147-b0955c3187ab.png)


and not, not are visual bugs.

**Comment by the456gamer** [comment]
what was happening at the time?
was everyone in survival mode?
did the server get /reloaded? (or anything else that would have effected it)
did the server lag?

**Comment by ToxicPeople** [comment]
never reload, i stop the server bc i don t like plugman or pluginreload.
yes, all in survival mode
no, normaly we have 18 tps

**Comment by CloudeLecaw** [comment]
hm i just see some open inventories and some craftingwindows of your server where players klicking.. this does not really look like a dupe..

like zrips said we need to know what happens here so zrips can reproduce this issue

**Comment by ToxicPeople** [comment]
give me some hours, im in class

**Comment by Zrips** [comment]
@ToxicPeople 
Will add some extra layer of protection from possible issue like this. But we still need actual method they managed to take out items from GUI so we can properly patch it out.
