### ISSUE TITLE
Option to sort Ctexts on listing

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3944]
at the moment ctext on using the command seems to get sorted by an order logic that i dont understand but it is definatly not by alphabet
mybe you could add something so we can show them from A - Z in alphabeticly order
this would make more sense like the current listing that seems to look a bit random (even if its allways listet in the same order..)

![Ctext help](https://user-images.githubusercontent.com/12080017/89986762-4f703d80-dc7d-11ea-98ef-8db5eda545b4.jpg)
Info: i assigned my /help as cmi customalais to /cmi ctext so when a player typs /help he gets listet the ctexts :)

**Comment by Zrips** [comment]
Will make it to be sorted more or less alphabetically, but in general it will maintain its order from now on.
