### ISSUE TITLE
execute other command when no command-argument is used - It is possible?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3946]
At the moment i try to design a new help with the ctexts.
i assignt the cmi ctext command with a customalias to /help
so long the pages work and just one problem is remaining.
now i have a little problem and dont know how i can solve this

i want: 
when the player used /help - the Mainpage (i called it help.txt) should be shown
when the player use /help ARGUMENT - the page ARGUMENT should been shown

What currently is working - 
whenthe player uses for example /help rules 2 it opens the rules.txt on page 2
The /help aslso has TAB-completation because this is what ctext does has

what does not work:
when the player uses /help i get the main listing of all arrivle ctexts.
what i want: it should open the ctext help.txt in ths case.

here is the customlias that might must be change for what i want.
```
  help:
    Cmds:
    - cmi ctext $1 $2
```

can someone help me with that or tell me if its possible to do this?

**Comment by Zrips** [comment]
Well some fix is needed, but what you could do is set couple alias
multiple of them would be with alias as: 
**help rules
help commands
help kits**
and so on
While one extra would be as 
**help ?**
Which will point to main help page which can show usage of help command or print some base information, which will get triggered when player mistype sub command. So typing in **/help** or **/help somethingRandom** will point to same main help page. And when you will have multiple alias with set you will have appropriate tab complete for those too. In any case, this will be possible to do with next update
