### ISSUE TITLE
[BUG] Wrong Update Notification Again

### ISSUE THREAD

**Issue by ScuroK** [Zrips/CMI#395]
7.7.7.1 gives me a wrong notification about the version again. It tells me there was a never version even i already updated.

**Comment by CloudeLecaw** [comment]
jup :-) and i think this will be fixed in next Version ;)
If u want u can update in manually by editing the versionnumer in Plugin.yml ;)

**Comment by MCTyler** [comment]
Doesn't hurt anything except if you Have OCD.
