### ISSUE TITLE
Bug tp

### ISSUE THREAD

**Issue by WIBOR2002222** [Zrips/CMI#3950]
When running the /tp <player> command, if the player is on the water, it will be tp on the bottom of the water (instead of tp on the player’s location)

**Comment by CloudeLecaw** [comment]
This is normal as it tries to find a safe spot. The water is no solid Block and therefore no save Block. So it checks for the next save Block that mostly is on the ground if the sea.

**Comment by Zrips** [comment]
Will make some adjustments to place player on top of water if tp location is set there
