### ISSUE TITLE
from console execute commands shown as shadowcommands?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3952]
`<T>&6&l/help smilie  &c»&7  nutzbare Chat-Smilies</T><H>Hier Klicken um eine Liste im Chat nutzbarer Chat-Smilies zu erhalten.</H><CCI>cmi ctext smilie [playerName]</CCI>`

This is the ctext  i use...

now when i click the CCI then it works ingame but the console has a strange entry
![Snag_37783db](https://user-images.githubusercontent.com/12080017/90076349-c64e1a80-dcff-11ea-816a-7870133ba914.png)

i noticed all CCI entries have this kind of "shadowcommand"
well i would understand this for a OneTime command like descripted for CC
but why for CCI? is it possible to get/see the real used command in console?

```
<C>cmi heal</C> - represents command to be performed when clicking text. Performed by player.
<CC>cmi heal [playerName]</CC> - represents command (from console) to be performed when clicking text. Player can click this only once.
<CCI>cmi heal [playerName]</CCI> - represents command (from console) to be performed when clicking text. Player can click this as many times as he wants.

```
Is there any way to disable shadowcommands?

**Comment by Zrips** [comment]
Shadowcommands are separate ones and its a temporary redirection when we are performing something unusual with a command then it should be done in general. No way to disable it without loosing some of the functionality. I could add some extra information to it and indicate what was performed exactly
