### ISSUE TITLE
cmi.keepexp not keeping numeric levels, only the fraction of a level

### ISSUE THREAD

**Issue by Isaiah-labs** [Zrips/CMI#3954]
players given the permission cmi.keepexp only keep the smaller portion (the bar) of their experience. the number exp level disappears.

---

**Cmi Version (using`/cmi version`):** 
8.7.5.5
**Server Type (Spigot/Paperspigot/etc):** 
paper 
**Server Version (using `/ver`):** 
Paper(135) 1.16.1-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Cant reproduce at this moment with latest minecraft build. And CMI only informs server itself that player needs to keep their EXP after they die, so if this is bugged then it will originate from minecraft itself and nor from CMI specifically.
