### ISSUE TITLE
CustomText

### ISSUE THREAD

**Issue by WIBOR2002222** [Zrips/CMI#3957]
Hello, is it possible to add custom commands to CustomText like, for example, the MyCommand plugin?

For example, the player can enter the command /discord and it opens the custom text where there is the information about the discord

**Comment by CloudeLecaw** [comment]
I see you understood what ctext can do. And yes it possible ti write some Text, may with a nice hover and if you klick in it the discord link an be executed as URL or postet into chat its clall uo ti you :)
To open this ctext create a custom alias that opens the ctext. Liked  asConsole! Cmi ctext Discord [playerName]    thus wouod open the ctexr for the players eveb if he normaly has no permission to ctexts :)

**Comment by Zrips** [comment]
@WIBOR2002222 
As @CloudeLecaw explained, you can use ctext to create nice looking text which clickable parts which would perform commands you want. After which you can ether enable auto alias for this ctext or create your own with aliaseditor.
