### ISSUE TITLE
[REQUEST] Received mail advancement pop-up

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#396]
Add a configurable advancement pop-up for 1.12+ servers for when a user receives mail, similar to how ChatControl handles it with private messages (pic below).
![5569a4ffcf716c05396d11b4d48a532627646237](https://user-images.githubusercontent.com/24642838/40235539-f57d9e84-5aed-11e8-8f5e-74c70a41b81a.gif)
https://www.spigotmc.org/resources/♣-chatcontrol-pro-format-and-filter-your-chat.10258/

**Comment by LogGits** [comment]
If this is added maybe a `/cmi advancementmsg <player> <msg>` command so this can be utilised for a wider range of things. Also I propose a `MailSendEvent` and `MailRecieveEvent` for `eventcommands.yml`. With this, actions can be performed when a user receives a message or sends a message.
