### ISSUE TITLE
daeily Voterecord get resetet on each server restart

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3962]
Well we thought the placeholder should show us the amount of votes when enabled  for the last 24 hours.
but when the server is restarted the amount get resetet even if you allreaady voted :3

**Comment by Zrips** [comment]
Votes timers are not saved in database, so after restart you will loose data from past votes. Saving data like this would require separate table to be added where we would track every vote for ip and when it was performed. At this point its not a bug, its simply not a feature
