### ISSUE TITLE
" CMI GLOW " have some bug.

### ISSUE THREAD

**Issue by d0nghan** [Zrips/CMI#3967]
**Description of issue:**
/cmi glow gui 's color picking doesn't work at all.

---

---

**Cmi Version (using`/cmi version`):** 
8.7.5.8

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot with bungeecord

**Server Version (using `/ver`):** 
1.15.2-R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment]
It does not work in paper you need spigot for this. In paper you just get a white glow

**Comment by CloudeLecaw** [comment]
Its not really a bug where CMI can handle

It does not work in paper you need spigot for this. In paper you just get a white glow
Just search ing the github filter of CMI for "glow" and u will see this is an really old related issues allready and may never can be fixed. - 

https://github.com/Zrips/CMI/issues/3310  or https://github.com/Zrips/CMI/issues/2535   or https://github.com/Zrips/CMI/issues/3295

 you will find more if you search deeper^^
if u agree u can close this ticket ;)..if not let it open...it will be open like the others ...may forever^^
