### ISSUE TITLE
Alias variable ? not working

### ISSUE THREAD

**Issue by RispyCZ** [Zrips/CMI#3969]
**Description of issue:**
When I use alias variable "?" for subcommands instead of having alias with different subcommands I have alias "command ?"

---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  res ?:
    Cmds:
    - ctext res

---

**Cmi Version (using`/cmi version`):** 
8.7.5.5
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-135

**Comment by Zrips** [comment]
Test this with atleast 8.7.5.9 as that version got fix for alias like this.

**Comment by RispyCZ** [comment]
Nope still not working on version 8.7.6.2
