### ISSUE TITLE
[MobFarmMananger] LAG

### ISSUE THREAD

**Issue by msmanui** [Zrips/CMI#3970]
If u see "Plugins" and goes to mfm, its takes a lot of ms (101)

https://timings.aikar.co/?id=3f63bf002b9941cda004a7b0673eed68#timings

**Comment by Zrips** [comment]
Will investigate, but from first look at timings you have ~70 players online and you have solid 20fps. MFM might tend to increase its usage in case there are bunch of things for it to do, with 70 players and depending on your config setup, this could be some what normal load. But will check it to make sure.

**Comment by Zrips** [comment]
Should be improved with next update. Found something i can optimize related to your report.
