### ISSUE TITLE
Version not working

### ISSUE THREAD

**Issue by dragontekgaming** [Zrips/CMI#3975]
**Description of issue:**
/cmi version produces a line of -, but does not show the version.

**Cmi Version (using`/cmi version`):** 
8.7.6.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
git-Spigot-9639cf7-8fb6585 (1.16.1)

**Comment by mrfloris** [comment]
Duplicate https://github.com/Zrips/CMI/issues/3948

**Comment by Zrips** [comment]
This will get fix soon ennough
