### ISSUE TITLE
CMI overrides worldGuard blocked-commands

### ISSUE THREAD

**Issue by Kubson6969** [Zrips/CMI#3981]
CMI 8.7.6.1
PAPER 1.16.1

When you deny commands in a WorldGuard region and then you use any cmi clickable message you receive the message "You can't <command> in this region" but it still works.  I have Parkour plugin and when you're in a arena you can't use tp commands but this plugins overrides any other one and lets players leave the arena without using the /parkour leave command they can use home or any other tp that this plugin has "I fixed it using exit deny for the region flag"

The parkour plugn im using: https://www.spigotmc.org/resources/parkour.23685/
 and world guard last version too.

**Comment by Zrips** [comment]
Tested with latest worldguard, while i have no idea what exact settup you have in your situation, but setting something like *allowed-cmds cmi heal* for a region blocks every command without any issues as i can see. Could you provide exact example of your setup and which exactly clickable messages you could have pressed to get outcome?

**Comment by Kubson6969** [comment]
Example: https://imgur.com/a/AfX6wMV
It's weird, you have to set your region flags correcly to prevent this. Gif shows using the command /warp <warp> doesn't work but if you use the /warps list (going to spawn first and using /warp) then going to a place where's that command blocked and if you click the warp name it works. But I think we can fix it just setthing some flags correclty, It's not something serious, I just wanted to mention it.

**Comment by Zrips** [comment]
I still need your exact setup for blocked commands in this region of yours as i cant reproduce it at this moment, all commands are blocked, with hover over messages or not, i cant teleport to spawn from inside of region with blocked commands. So something is different with your setup
