### ISSUE TITLE
Holograms no more colored

### ISSUE THREAD

**Issue by DaveDevil** [Zrips/CMI#3982]
**Description of issue:**

Holograms are all white. See attached files

![screen3](https://user-images.githubusercontent.com/21291475/90322541-dfe89f80-df55-11ea-9b50-aeb59bd86e28.png)
![screen1](https://user-images.githubusercontent.com/21291475/90322542-e0813600-df55-11ea-908e-414012518fe4.png)
![screen2](https://user-images.githubusercontent.com/21291475/90322543-e119cc80-df55-11ea-9fd6-9b15f7702c33.png)

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.7.6.0 BungeeCord CMIB  SqLite-> 8.7.6.1
Server: Paper(101) 1.16.1-R0.1-SNAPSHOT
CMI economy: No CMI Chat: Yes 
Modules -> 51 enabled 1 disabled: votifier

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 

git-Paper-101 (MC: 1.16.1)

**Comment by Zrips** [comment]
Cant confirm this one at this point. Try testing it without any other plugin or simply update your server, as you have 33 versions old build on your hands
![screen3](https://i.imgur.com/qB3oXfA.jpg)
