### ISSUE TITLE
Selection Visualizer - Worldborder visibility is broken if radius > 3200

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#3983]
The Worldborder is no longer visualized by particles. Actually, the border should be shown to the player with flame particles just before he or she meets it (https://imgur.com/a/yg022Jy). This feature does not work anymore. The Worldborder is just completely invisible. 
The problem occurs with the default Worldborder version (https://www.spigotmc.org/resources/worldborder.60905/), as well as with the fork of Puremin0rez, which is probably used by everyone who is sane (https://www.spigotmc.org/resources/worldborder-pures-fork.81706/). In version 1.13.2 the feature works. In newer versions unfortunately not. Have a great day :)

config: `WorldBorder: true`
Paper 1.16.1 - 134
WorldBorder 1.16 (https://www.spigotmc.org/resources/worldborder-pures-fork.81706/)

**Comment by Zrips** [comment]
Tested out this one, seams to be working just fine on 1.16.1 134 and using that sane version of WorldBorder. Did you set world border properly? As you might accidentally used minecraft worldborder command instead of this plugins one. Doing something like **/worldborder:wb set 100** will ensure that you used command from correct plugin.
But yea, it is working with round or square type borders

**Comment by TheoRetisch1** [comment]
Sorry for the late answer, I was abroad. I have to specify the problem: The worldborder is only not displayed if the radius is larger than 3200, smaller worldborders are visualized without problems. Since I normally set a worldborder of 4000 blocks I did not notice this. Could you please reopen the ticket?

**Comment by Zrips** [comment]
ok, now things got cleared out and reproduced your issue. It was all about border being a circle and being above 3200 blocks in range when issue started to popup. Got fixed, will post new version today with a fix

**Comment by TheoRetisch1** [comment]
Thank you 💯
