### ISSUE TITLE
Specialized commands support in kits

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3987]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, couldn't you add way to define specialized commands (for actionbar, title etc.) in kits? And other ways that are available in specialized commands.

### Basic explanation as to why this feature is needed and/or useful to have: ###
It could be useful, if you wanna make for you kits for ex. title, actionbar or so many different options from specialized kits. For ex. I wanna make for my kit newbie special title and subtitle.

**Comment by Zrips** [comment]
But its already supported, you can print out title messages or anything you want with help of specialized commands. You simply need to set them in a kit for commands as to be performed when you get one. Just tested out to be sure, all works as supposed.
