### ISSUE TITLE
Cmi color

### ISSUE THREAD

**Issue by KingsRequin** [Zrips/CMI#3988]
**Description of feature/improvement request:**

Create placeholder which works the same as `{#e60000>} hello world{#00e6a1 <}`.
Something like `%cmi_color_{#e60000>}_hello world_{#00e6a1 <}%` (Or another format)
---
### Detailed explanation of what it should do, when and in what situation: ###

I don't know if it's possible, but it could be useful for some plugins that can't do gradient.

### Basic explanation as to why this feature is needed and/or useful to have: ###

I personally use VentureChat for the moderation system.
And it is impossible to make gradients for example.
Likewise for the tab with other plugins.

Thank you !

**Comment by Zrips** [comment]
Okey %cmi_color_[text]% it is

**Comment by SbirTeo** [comment]
Was this feature added?
