### ISSUE TITLE
We need a change on warp command

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#3989]
At Essentials, it's so that I can warp people to a point as an OR. That works on CMI too. But if I only want to give a user the warp privilege for one warp point, I have to set all warps to require that privilege. And then I give the user the permission for the one warp point with cmi.command.warp.hub in my example.

Unfortunately I can't simply enter /warp anotherwarppunkt user as OP then. So this warppoint is not exised.

**in greater detail:**

So I have two warp points. Test1 and Test2

Both are set without any required authorization.

I can enter /warp Test2 playername as OP. 

Now I want to give a player only the access for Test1. For this I have to set both warp points to require a permission. 

But then I cannot enter /warp Test2 playername as OP. With Essentials this works without problems. I hope you understand what I mean.

**Comment by Zrips** [comment]
i guess i got what you want. So basically if warp requires permission to be used, you want to be able to send target player to this warp even if target player doesn't have access to that warp but you as player with access to warp and access to teleport other players to warps do have. Is this what you meant, then it will be made to work with next version.

**Comment by blakedj012** [comment]
That's exactly what I mean. Thank you for your work.
