### ISSUE TITLE
[Request] -s Option for mute and mutechat

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#399]
currently we have no unmute command... but we could trick it.
example: 
we mute the chat for 2 hours
/mutechat 2h -> all gwet informed that the chat is muted for 2 hours...fine so long..
now we want to unmute the chat so we can use
/mutechat 1s to overwrite the old time and set it to be unmuted after a secound.
but in chat u see this meassge aggain that the chat is muted for one secound.
so a -s Option would be nice
then we could do /mutechat 1s -s then the chat is unmuted after a secound then without
any new information in the chat.

**Comment by Zrips** [comment]
Next update
