### ISSUE TITLE
Exp stuck 

### ISSUE THREAD

**Issue by StarozytnySky** [Zrips/CMI#3990]
**Description of issue:** When player have 0 exp and i give him exp command /exp PLAYER give 1 and repeat this command to exp player 358. Then when you give player /exp PLAYER give 1 he doesn't recive exp.
Exp stuck in 358 exp

**Cmi Version (using`/cmi version`):** 8.7.6.1

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot

**Server Version (using `/ver`):**  1.13.2

**Comment by Zrips** [comment]
Seams to be minecraft bug itself as CMI properly grabs all the values from the player, but around 358 up to around 390 it doesn't process values properly and adds one less then it should. Will add some what work around for this bug, but in general this originates from minecraft itself.
