### ISSUE TITLE
Interactive Commands bugs

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#3992]
**Description of issue:**

Issue 1) I made 2 signs, one [Trash] and one [Repair].
Player has access to only CREATE [Trash], so if player tries to make a [Repair] one, it will say the player has no permission.
However, the sign will then automatically use one the player has access for, which is [Trash], but the sign will be blank.

Issue 2) If you have only one home for example called ''hello'', and you have a sign like [Home] test, it will teleport you to the single home you have, ''hello'' rather then it being denied.

Issue 3) If you place two signs under eachother, like [Trash] and [Repair], both will open the /dispose menu.. might be related to the same coordinates?

**Comment by CloudeLecaw** [comment]
Iuuse1 - is irritating what you want - you should better screenshot it with a description

Iusse 2 - its normal if you have no other home and use a wrong name the first simliar found one is taken, that is how CMi hndle wrong inputed commands. you can try it with using /cmi hme u will se that /cmi home will be executed - that the same princip.

iusue 3. i cant reprudice this - when i tested this i got one open the disopse menue and the other sign did the repair command.
             may u made something wrong at creating? (like looking at the wrong sign on creation?

issue 4: you forgot to paste your used CMI and Server Version ;)  This should be allwas done with each ticket to make sure your using latest Version of CMI and your server (dont write "im using latest version" - use versionnumers your using)

**Comment by Sikatsu** [comment]
Issue 1: I am fine if it uses the sign you have access to, in this case [Trash], but it would be nice if the sign won't be blank and act as [Trash], for the user experience.

Issue 2: I understand, but hoped I could make that different using signs.

Issue 3: Can't reproduce it as easy either, but I definitely had this bug yesterday.

Issue 4:

[13:53:19 INFO]: --------------------------------------------------
[13:53:19 INFO]: CMI: 8.7.6.1 BungeeCord MySQL
[13:53:19 INFO]: Server: Paper(135) 1.16.1-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
All issues will get resolved with next update
