### ISSUE TITLE
/findbiome teleports behind wolrdborder

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3993]
**Description of issue:**

---
Hi /findbiome command teleports behind worldborder. I think that it should only work between border? Same for  /scan etc.
---

**Cmi Version (using`/cmi version`):**  8.7.6.1

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  346

**Comment by Zrips** [comment]
Will make it take into consideration world border for findbiome command, tho /scan should still work on all chunks even if they are outside, so that stays as it is

**Comment by Volgeop** [comment]
And maybe /locate command if you can handle it too somehow?

**Comment by Zrips** [comment]
locate? You want custom alias for findbiome?

**Comment by Volgeop** [comment]
No I mean normal /locate to show villages etc. just within world border.
