### ISSUE TITLE
Cooldowns without space and with

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3998]
**Description of issue:**

---
Hi, the problem is, when I add cooldowns without space and then with space, and I expect that it will be different. So I expected that players can use /repair, and then get cooldown 1800, but I though that they can also use /repair all and /repair armor, but they can't, because it takes cooldown for whole repair to 1800s. And btw repair and repair hand is same, so wanna make somehow merged cooldown for it. But mainly, wanna allow players using also /repair hand, then /repair all, then /repair armor. If normal /repair wasn't same as /repair hand, I don't have to put it here, but because it's same, I have to put it to cooldowns too.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  - cmi repair:1800 #for default repair command, because it's same as repair hand, I wanna cooldown 30 min
  - cmi repair hand:1800 #for hand I wanna 30min
  - cmi repair all:86400 #for all I wanna 1 day
  - cmi repair armor:3600 #for armor I wanna 1 hour
```

---

**Cmi Version (using`/cmi version`):** 8.7.6.1

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 
```
[17:06:12 INFO]: This server is running Paper version git-Paper-135 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[17:06:12 INFO]: Checking version, please wait...
[17:06:12 INFO]: Previous version: git-Paper-134 (MC: 1.16.1)
[17:06:12 INFO]: You are running the latest version
```

**Comment by CloudeLecaw** [comment]
try using the open on on last place, else you take the time for all argument before setting special once (this is included b the first=
so try.. let us know if it works ;) well with chat filters its also like this...so maybe this works allready
```
  - cmi repair hand:1800 #for hand I wanna 30min
  - cmi repair all:86400 #for all I wanna 1 day
  - cmi repair armor:3600 #for armor I wanna 1 hour
  - cmi repair:1800 #for default repair command, because it's same as repair hand, I wanna cooldown 30 min
```

**Comment by Volgeop** [comment]
No... this way when I do /repair, then I have to wait 1800s until using repair and repair hand again... But now, when I wanna do /repair all for ex., I have to wait 1 day! But I didn't use it....

**Comment by CloudeLecaw** [comment]
but that is what you have defined there, so there is no error
1800 for repair hand, one say for repiar all, 3600 for repianr armor
and 1800 for repair  including simple /repair
if you dont want this u have to define what you want correctly

**Comment by Volgeop** [comment]
1. Cooldowns in example you gave me doesn't work.
2. It doesn't take players money if they use repair all prob.
3. There are any messages that it was repaired....

I think that still would be great if default cooldowns: handling could be improved for this cases.

**Comment by CloudeLecaw** [comment]
> 1. Cooldowns in example you gave me doesn't work.
> 2. It doesn't take players money if they use repair all prob.
> 3. There are any messages that it was repaired....
> 
> I think that still would be great if default cooldowns: handling could be improved for this cases.

u never said it should cost money*lol*
i tested the cooldown for customaliases it works fine, but in case u want money this example will not work :§

**Comment by Volgeop** [comment]
Yeah my repair costs money.

And I did it as no admin, I tested it as player.

**Comment by CloudeLecaw** [comment]
but its really simple to work with your wants in customalias dont be shy to play with it to fullfill your needs

like
```
  repair all:
- perm:cmi.command.customalias.repair! cooldown:1800! moneycost:500#! perm:cmi.command.customalias.repair! asConsole! cmi repair all [playerName]
```
a simple repair replacement for repair all with cooldown, moneycost and permissions you see working with spezialed commands is really no big magic

**Comment by Volgeop** [comment]
But there's still problem that CMI repair command has dynamic price depending on how much it's broken and if it's enchanted.

**Comment by CloudeLecaw** [comment]
have you setted up a cost for it?

**Comment by Volgeop** [comment]
IDK, I now tested it.... with examples you gave me, with cooldowns: changes in config. with customalias changes, with perms changes, with alias disabling.... but I can use /repair hand without cooldown.... so I don't understand it. Also, I can't use normal /repair.....

**Comment by CloudeLecaw** [comment]
chaning of values sometimes need a server restart, maybe that is your problem?
i see no reason, else you have some permission to bypass a cooldown...

hmmm.. your in plyer group and your not *oped? ,,,strengh..
i tried the cooldowns here to and they worked normal
really strengh..  maybe a 3rd one that can give a suggestion?

**Comment by Volgeop** [comment]
The only problem here is when it costs money and player items are repaired from console, then player can't confirm anyhow if he really want repair these items for this cost....

**Comment by Volgeop** [comment]
@Zrips I saw that you made change:

> Some improvements relating to cooldown recognition when it comes to commands with same core prefix, like /fix and /fix all and /fix hand now all can have their own cooldowns

But it still didn't solve this issue exactly, cause when I have:
```
  - cmi repair:300
  - cmi repair hand:300
  - cmi repair all:86400
  - cmi repair armor:3600
```

then when using /repair, and then /repair all, it says that cooldown was already executed even when player executed just /repair. Could this be also somehow fixed?

**Comment by Volgeop** [comment]
Btw all repair commands are broken now from the latest update, /repair hand, all etc. ddoesn't work, cooldown is activated, money are taken but nothing is repaired @Zrips

**Comment by Volgeop** [comment]
Solved with the latest ver
