### ISSUE TITLE
Standard Color Codes with latest two Releases

### ISSUE THREAD

**Issue by VimaMT** [Zrips/CMI#3999]
Are standard color codes (&a, &b, &3, etc.) still working with the latest two releases?

I use Paper 1.16.1, Build #135, Luckperms, Vault, ProtocolLib, PlaceholderAPI, CMI and CMI Injector in a brand new system. No configuration has been done.

The older standard color codes are working with version 8.7.6.0 of CMI. They do not work with 8.7.6.1 or 8.7.6.2.

I am entering my text and color codes through chat.

I'm running OpenJDK 11.

**Comment by VimaMT** [comment]
I forgot ... I also have standard Vault installed along with the CMI injector.

**Comment by Zrips** [comment]
There was small issue with that in latest builds, you might want to test next version and if issue persists let me know. Other than this, double check that you have access to the colors with /cmi colorlimits command
