### ISSUE TITLE
ASkyBlock not recognizing cmi economy.

### ISSUE THREAD

**Issue by weaves7** [Zrips/CMI#40]
ASkblock does not recognize the CMI economy. I did have Askyblock working with essentialsx but it is no longer installed since i am replacing essentials with CMI. I do have the economy set to true in the CMI config.yml and Askyblock config.yml is set to use economy. I have the latest versions and CMIEInjector installed. Could it be the order that the plugins are loading/enabling?
Startup: https://www.hastebin.com/dehidequsi.sql
Thanks.

**Comment by Zrips** [comment]
Small issue, will have to update injector to load before ASkyBlock plugin as its wants lo load before all plugins.
