### ISSUE TITLE
Colors permission wont  work

### ISSUE THREAD

**Issue by Korinocho** [Zrips/CMI#4001]
Any user can use colors in chat
Even if i negate the permission cmi.colors.*.* and so...
Had to downgrade to 8.7.5.1 from 8.7.6.2 (was lazy to test all the versions and went to the last used wich was working)
They just can use colors

**Cmi Version (using`/cmi version`):** 
8.7.6.2

**Server Type (Spigot/Paperspigot/etc):** 
Paper 1.16.1 #134

**Server Version (using `/ver`):** 
git-Paper-134

**Comment by Zrips** [comment]
Should get resolved with next update

**Comment by Korinocho** [comment]
Thanks!
