### ISSUE TITLE
Colors on public chat

### ISSUE THREAD

**Issue by Keendi** [Zrips/CMI#4006]
**Description of issue:**

When players with permission and OP use colors on chat ex. &a&lTest, the message didn't format colors :((((

**Cmi Version (using`/cmi version`): 8.7.6.2** 

**Server Type (Spigot/Paperspigot/etc): tuinity-paperclip 1.15.2** 

**Server Version (using `/ver`): 1.15.2**

**Comment by Zrips** [comment]
You ether need to use CMI chat control or to enable Colors->PublicMessage config section which will colorize chat colors. Other than this you might want to check out your /cmi colorlimits to make sure that you have access to specific colors
