### ISSUE TITLE
[Request] Improved sleeping

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#401]
Add an improved sleeping system:

- Instead of requiring all players to be asleep in order for the night to pass, a configurable percentage of people are required to be asleep.
- Players that are AFK are excluded from the percentage.
- Vanished players are excluded.
- Players with a certain permission are excluded.
- Additional configurable setting: Instead of the night being skipped when the required percentage of players are asleep, the night will simply go by at a faster (configurable?) rate.
- Configurable announcements when set amounts (or percentages) of people are asleep, reminding others that they can do the same and sleep away the night.

Similar to https://www.spigotmc.org/resources/better-beds.1824/

**Comment by Miclebrick** [comment]
My input: If e.g. 50% of people are not sleeping, the night goes by twice as fast, and if 25% are not sleeping, then the night goes by 4x as fast. In other words, the speed is multiplied by 1/(percentNotSleeping)

**Comment by TheWranger** [comment]
Could also use an optional (can be disabled in config) boss bar to display the amount of people sleeping out of the amount needed.

**Comment by TheWranger** [comment]
This was partially added in 7.8.5.0.
Still work like to see:

- Option to exclude vanished players
- Option to exclude AFK players
- Maybe when a player is sleeping, a boss bar is present that displays how many people are sleeping?

**Comment by Zrips** [comment]
@TheWranger 
Its in base condition currently and improvements will be made for it. Made it at end of day, so dint had much of time to add extra features to it.
Any suggestion will be considered and will add all of yours.

**Comment by TheWranger** [comment]
Yea, just wanted to make an easy to list of remaining features to add.
