### ISSUE TITLE
Teleport location

### ISSUE THREAD

**Issue by JanPlazovnik** [Zrips/CMI#4010]
### Detailed explanation of what it should do, when and in what situation: ###
When a player teleports to another player, CMI should place the initiator on the ground (safe location) instead of mid-air. Could be by default or as a config option.

### Basic explanation as to why this feature is needed and/or useful to have: ###
This feature would prevent players from accepting TPA requests while flying and bring death upon the poor soul who had initiated the holy grail that we call teleportation. This is a problem due to TP killing and scamming players on survival servers.

**Comment by Zrips** [comment]
Do they have cmi.safeteleport permission node?

**Comment by JanPlazovnik** [comment]
Oh, I was not aware that was a thing. And I guess neither was floris since he suggested we open a feature request. It works after adding the permission node. Maybe you could add a comment pointing this out somewhere in the teleport section of the config?
