### ISSUE TITLE
haspermission -> if yes, execute cmd

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4014]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, do you think that you could add way to execute command, if haspermission check for permission node was useful? So if player has permission, then the command could be executed.
### Basic explanation as to why this feature is needed and/or useful to have: ###
 I need it for Jobs, where I wanna give players VIP kit on particular level, but it doesn't support permission group check... so I can't give it now to only vip players. if you could add executing cmd, then I can simply use haspermission [player] group.vip cmd lp user [player> permission set XXX server=survival.

It could work somehow like haspermission [player] {cmd} - optional

**Comment by Zrips** [comment]
Check specialized command section, you can make it to check for specific permission node and execute command(s) if criteria is valid
https://www.zrips.net/cmi/commands/specialized/
You might need to create new alias or go throw different methods to utilize this feature, but in general you can already do it.

**Comment by Volgeop** [comment]
Yeah, I though about creating custom alias, but this way I have to create custom alias for every kit. But ok, I can do it this way, I just though it will be more easier if I can just add there one command like this instead of making custom alias for every kit.
