### ISSUE TITLE
Spaces in Nameplates

### ISSUE THREAD

**Issue by antb0t** [Zrips/CMI#4015]
**Description of feature/improvement request:**
Add a way to allow Nameplates to have spaces in the prefix and suffixes
---
### Detailed explanation of what it should do, when and in what situation: ###
Currently there is no way to have a Nameplate "[Admin] Antb0t" because you cannot have spaces in the command and thus forces you to have your nameplate as [Admin]Antb0t which is not good in my opinion.  Kind of defeats the purpose of the prefix and suffixes for nameplates.

**Comment by Zrips** [comment]
Will introduce small change to this and we will have option to add space by using underscore like _ when you will want a space and in case you will want actual underscore you can use double __ which will result into _

**Comment by CloudeLecaw** [comment]
i hope this does not affect real playernames....
like mine
Cloude_Lecaw  im sure some plugins/commands wont be happy with Cloude__Lecaw
