### ISSUE TITLE
ctext <CCI> doesnt work any more 

### ISSUE THREAD

**Issue by Feldmarschall** [Zrips/CMI#4017]
**Description of issue:**

Since the last CMI updates the console command doesnt work any more. Like <CCI>cmi heal [playerName]</CCI>. Nothing happens. <CC> </CC> works fine. 

---

**Cmi Version (using`/cmi version`):** CMI - 8.7.6.3

**Server Type (Spigot/Paperspigot/etc):** Paper - 384

**Server Version (using `/ver`):** 1.15.2

**Comment by Zrips** [comment]
Will be fixed with next build
