### ISSUE TITLE
[Request] Custom Recipes can accept ANY damage varient

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#402]
Allow us to configure custom recipes so that they will accept ANY damage variant of a block.
        ==: org.bukkit.inventory.ItemStack
        type: WOOD_STEP
        damage: ANY

Could be used to make something like this, where a single recipe is configured to accept any variant of STONE:
![image](https://user-images.githubusercontent.com/24642838/40278028-cb15c20e-5c6c-11e8-9e72-4f5975136cd5.png)

**Comment by MCTyler** [comment]
https://github.com/Zrips/CMI/issues/351

**Comment by TheWranger** [comment]
@MCTyler No, that isn't what I'm suggesting.
I want to be to make a single recipe for a stone pickaxe that can accept any variant of stone.

**Comment by MCTyler** [comment]
Looks like what @https://github.com/CloudeLecaw is EXACTLY asking for. Irregardless, they are similar requests and need to be linked. Sorry if it offends you to link similar requests.

**Comment by TheWranger** [comment]
CloudeLecaw is asking for the ability to set specific requirements for item recipes (things like item lore, durability, item name, attributes, etc.)

I'm asking for the ability to set up recipes so that they will accept ANY damage variant instead of just 1 like they currently do.
We're asking for two completely different things.

**Comment by MCTyler** [comment]
Variants in Recipes.....Ok.

**Comment by MCTyler** [comment]
No need to close, when you link them they all get combined....
