### ISSUE TITLE
[MobFarmManager] Serveral bugs

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#4025]
When you don't give support in right thread, so I try here like others had done.

In last three versions from 1.5.7.0 It ignore config for animals. 

version 1.5.6.0 is broken too (it not remove some type of mobs), so only working version for me is 1.5.5.3.

And has a bug when squid fail to go true the nether portal (working better in 1.5.5.3). The problem start in 1.5.6.0 

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

https://pastebin.com/yN7911B3

**MobFarmManager Version (using`/MobFarmManager version`):** 
1.5.7.2
**Server Type (Spigot/Paperspigot/etc):** 
papermc
**Server Version (using `/ver`):** 
1.16.1 version 133
**Relevant plugins (Delete if this isn't needed):**
MobFarmManager, cmi 7.6.0, jobs-v4.16, ultrapermission

**Comment by Zrips** [comment]
It would be nice to know which monsters exactly causing you issues. Tho looking throw config i can see that you have auto clean with grouped chunks enabled and you have squids set for a group with salmon and cod, which is at 12 in 3x3 chunks. So you might have your issue with that. 
Iron golem spawning is limited then it comes to iron golem spawning in villages during raids, which is disabled in your case. You do limit them throw general limiter which seams to be working just fine.
So yea, i need some specifics for your situation, whats not working in which specific situations to test it out properly and determine possible causes

**Comment by broken1arrow** [comment]
So no fix for the plugin listen if you set settings on false.

If i use , it limit mobs ether way.

EntityGroups:
  Animals:
    Use: false
    Limit: 10
    List:
    - Pig
    - Cow
    - Horse
    - Rabbit
    - Sheep
    - Chicken


and squid i use this, it is a normal river biome and use portals.
![2020-08-27_00 17 32](https://user-images.githubusercontent.com/16368286/91362441-ca4b6380-e7fa-11ea-8878-1e18bc5780f5.png)

**Comment by broken1arrow** [comment]
So i understand now way @Zrips has problem to get the issue, you need to overflow with mobs. only mob some work is creapers. I put up a video.

https://www.youtube.com/watch?v=gNPN2CHT77A&feature=youtu.be

**Comment by CloudeLecaw** [comment]
Animals are not made to pass the gates. just a few mobs can pass it like pigs. if you want mobs passive nether portals you need an exrea plugin. so thisis no issue for MFM

**Comment by broken1arrow** [comment]
> 
> 
> most Animals are not made to pass the gates by the minecraft vanilla code. just a few mobs can pass it like monster and sometimes pig does.
> if you want passive mobs to pass nether portals you need an exrea plugin. so thiis no issue of MFM
> You will see without MFM you will have the same result that the quids dont come to the other side.
> 
> This is called a bukkit bug and is well known since 1.7.2 allready, but never fixed ;)
> Some worldmanager like multiverse-netherportals can also cause this kind of issues to other mobs

If i remove MFM, it work fine. You see first zombie pass true, but when clean start to show it never stop clean.

I send image and i not spawn all this mobs and no other player can do it (only me on the server).

![2020-09-12_11 48 12](https://user-images.githubusercontent.com/16368286/92992811-dd924a80-f4ed-11ea-9864-d863e831e6a5.png)

**Comment by broken1arrow** [comment]
i post new video no mfm on

**Comment by broken1arrow** [comment]
> 
> 
> most Animals are not made to pass the gates by the minecraft vanilla code. just a few mobs can pass it like monster and sometimes pig does.
> if you want passive mobs to pass nether portals you need an exrea plugin. so thiis no issue of MFM
> You will see without MFM you will have the same result that the quids dont come to the other side.
> 
> This is called a bukkit bug and is well known since 1.7.2 allready, but never fixed ;)
> Some worldmanager like multiverse-netherportals can also cause this kind of issues to other mobs

Soo https://youtu.be/AMrh33NkyTU no all players in vanilla has always option to make a squid portal farm, you can or shall even put thru villagers i not try if MFM even bug this out.

**Comment by broken1arrow** [comment]
@CloudeLecaw 

So what do you really mean?

Because without MFM it works fine to send any mobs through the portal.

If you mean that events in MFM cause a bug then clear the command bugs and try to clear entities that do not exist?

Because it runs it in a loop until I restart the server, it worked better in 1.5.5.3 (not quite good), but it dropped through some entities if you set the mobcap on atleast 12.

So try it yourself if you do not believe me, because it works great without the plugin get through them but they disappear in the portal

**Comment by broken1arrow** [comment]
So no multiverse installed and you can see squid goo true first. So not blaming on some random bug. @CloudeLecaw 
https://youtu.be/1x0zAu8EK14

**Comment by Zrips** [comment]
Should be resolved with next release.
