### ISSUE TITLE
[Request] Better Minecarts

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#404]
Right-clicking minecarts with a block that can go inside of it (Chest, Furnace, etc.) turns the minecart into that type.

This would work really well since in vanilla when a special type of minecart (Chest, Furnace, etc.) is broken, it doesn't drop that type of minecart and instead drops the normal minecart alongside whatever was inside of it.

Permission node based.

**Comment by LogGits** [comment]
Great idea 🙂 I added in that it should be dependent on permission nodes.

**Comment by Zrips** [comment]
Next update
