### ISSUE TITLE
Bug Report with Afk

### ISSUE THREAD

**Issue by AlfreDGR** [Zrips/CMI#4049]
**Description of issue:**

In Afk mode in the config it sets the option that spawner mobs cannot appear while afk, but they do.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
 PreventMobSpawning:
    # When enabled we can prevent mob spawning near players who are afk
    Enabled: true
    # Prevents natural mob spawning
    # This can be more on heavy side of the server as it will try constantly to spawn in monsters near afk players
    Natural: false
    # Prevent mob spawning from spawners
    Spawners: true
    # Usually responsible for spawning in iron golems
    VillageDefence: true
  # Disables exp pickup while afk
  # Attention! Because of weird minecraft handling of exp orbs, best way is to set orb to 0exp and allow it to be obsorbed
  # So by enabling this exp obsorbed by afk players will have no effect
  DisableExpPickup: false

---

**Cmi Version (using`/cmi version`):** 
8.7.6.4
**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
I did tested your config, everything seams to be working correctly, no monster spawns from monster spawner while you are afk. And just a reminder that in case there is some one else nearby who is not afk then monster spawn will not be prevented.

**Comment by CloudeLecaw** [comment]
He also should try with paper 141 since this is the frist official Release of paper

**Comment by AlfreDGR** [comment]
In Afk mode in the config it sets the option that spawner mobs cannot appear while afk, but they do. Tested in paper 1.16.3 #202

**Comment by CloudeLecaw** [comment]
work fine here without any issue the mobs FROM SPAWNER did not spawn when i when afk, the regular mobs on world that spawn normaly spawn, i hope u also just tested spawners and not regular mobs^^

**Comment by AlfreDGR** [comment]
Well, I have tried it and if they spawn and I have no error in the console and the config I have since they cannot spawn and spawn

**Comment by Zrips** [comment]
As this is isolated case will need to close this ticket. Just keep in mind that mobs could spawn in if some one is nearby who are not afk or you simply have some custom plugin which spawns in mobs instead of general method.
