### ISSUE TITLE
A problem with a jail, prisoners move to other cells when I restart the server

### ISSUE THREAD

**Issue by MdoubleM** [Zrips/CMI#4050]
**Question: Why my prisoners move to other cells when I restart the server? **
Hello, I have a problem with a jail I have created in my server. I have the region define and the cells too. And I have jailed some players. There are 40 cells and I have jailed players in the last cells: 40, 39, 38 and 37. Everything is good but when I restart the server, the prisoners go to the first cells: 1, 2, 3 and 4. Why is that happening?

**Comment by Zrips** [comment]
Because cell id was not been saved so players got put into cells in a row. Will fix that with next update and we will put players into appropriate cells after server restart
