### ISSUE TITLE
Hexcode nickname bugged in tab completion

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#4052]
**Description of issue:**

---

When I want to use my private message system from another plugin (which has support for CMI nicknames) the hexcodes are being shown as well.

![image](https://user-images.githubusercontent.com/5664135/90984464-65330c00-e575-11ea-90f6-b19ee211155d.png)

---

[19:16:42 INFO]: CMI: 8.7.6.4 BungeeCord SqLite
[19:16:42 INFO]: Server: Paper("dccaf59a0") 1.16.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Then plugin which uses that needs to use something like CMIChatColor.stripColor(NickName) which will return clean player name without color codes.
Other option would be to save players nick name in a raw format which would look something like
§x§f§f§9§0§5§0Mar§x§d§d§e§e§f§fis
But if we have plugin which already hooks into CMI then it could simply use this basic method to clear out color codes if it needs too. Or use CMIChatColor.translate(NickName) to get this wonky text and then clear it out from unwanted color codes. But in general this needs to be done from your chat plugin side.
