### ISSUE TITLE
%rand/1-1000% for EXP command too

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4053]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, could you add this placeholder to exp command? And maybe other ones from money command. In money we have options: money [pay/give/take/set] [playerName/all/alloffline] [amount/%rand/1-1000%/1%[min-max][playerName]] (-s)

So what about to add this option to exp too?

### Basic explanation as to why this feature is needed and/or useful to have: ###
This is useful when we wanna put this to our shops or crates. As money, players can get random amount and it's mysterious. Same would be great for EXP. Don't wanna give them exact number for it.

**Comment by CloudeLecaw** [comment]
You can allready. Do this. You just need to create a custom alais that gives Player some xp money or what ever and there you can use the random placeholder

**Comment by Zrips** [comment]
Will add %rand/10-20% for convenience sake
