### ISSUE TITLE
Hologram lag

### ISSUE THREAD

**Issue by XXY233** [Zrips/CMI#4059]
**Description of issue:**
When I upgraded from paper1.16.1 to paper1.16.2, the TPS became very, very low. When I disabled the Hologram module, the TPS became normal.

The first timings: https://timings.aikar.co/?id=7dae0621810240c1bd0537493e5e3c85#timings

There are only timings of CMI: https://timings.aikar.co/?id=5b160f3788c445358e2df6f221a95a54#timings

Console error: https://pastebin.com/YDi9CdHd

---

**Cmi Version (using`/cmi version`):**  8.7.6.6

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot 1.16.2-R6

**Server Version (using `/ver`):** 1.16.2

**Comment by Zrips** [comment]
Disable hologram which displays player top playtime until next release which will introduce fix for this issue
