### ISSUE TITLE
Rank sistem - ItemCrafts

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#406]
Some objects specific to the ItemCrafts requirement do not recognize them individually.

Example:
```
  StatsRequirements:
  - "PlayTime:604800"
  - "ItemCrafts:2000"
  - "ItemCrafts:diamond_sword:1"
  - "ItemCrafts:diamond_shovel:1"
  - "ItemCrafts:diamond_pickaxe:1"
  - "ItemCrafts:diamond_axe:1"
```
If I make a sword, shovel, pick and axe.
Counts 4 crafting global items. But does not count the shovel individually.

It also happens with many other items.

[https://s19.postimg.cc/swi9tgdeb/captura_1526912716.jpg](https://s19.postimg.cc/swi9tgdeb/captura_1526912716.jpg)

-----------------------
_**Version CMI: 7.7.8.0**
Version  Server: Spigot 1.12.2-R0.1-SNAPSHOT | CraftBukkit version git-Spigot-2086bb0-1988d7f (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Version Vault: 1.6.6-b67_

**Comment by CloudeLecaw** [comment]
Shovel is wrong
DIAMOND_SPADE   is right
look here for items
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
