### ISSUE TITLE
Disable tp to vanished players

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#4060]
I think it is very important. We need a permission that players with teleport rights can't teleport to invisible players by simply writing their name.

Essentials has some permissions for but not cmi.

**Comment by Zrips** [comment]
We can definitely add permission to that. Tho, side note, well question. Why would you have some one with a permission to teleport to the player who is vanished without his permission? What i mean is usage of /tp when there is commands like /tpa, which would mean that you have some one with /tp command access who can teleport to anyone on server including vanished people which should only be for staff members. Unless its some lobby type server where teleporting to the player doesn't really impact on gameplay.
Anyways, will add extra permission requirement for /tp command, if there are other commands which would need similar thing, let me know.

**Comment by blakedj012** [comment]
Yes on my server you can buy VIP with ingame money. And the highest VIP may teleport to players without their permission. Unfortunately I can't hide as an OP when I'm invisible on the server because the user with the tp gets out to me that I'm on the server.

Thanks for your mega and fast work on this plugin!
