### ISSUE TITLE
Tab complete for edit sign (Like EssentialsX)

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#4063]
https://www.spigotmc.org/resources/essentialsx.9089/updates

essentialsx just added Tab-complete for their sign editing command, where it completes with what was existing on the sign.
Can you please add this to your version.

**Comment by CloudeLecaw** [comment]
What is the differences to sign copy?

**Comment by TomLewis** [comment]
You look at the sign and use the command and it will auto fill in your chat to edit that existing sign, not a new one.

**Comment by CloudeLecaw** [comment]
you have a command /cmi se [Linenumber] Text....

**Comment by Zrips** [comment]
@TomLewis 
If you are talking about /cmi se having option to tab complete what is on a sign, then yea, i can add that. Next update.
