### ISSUE TITLE
Bug with Login/Logout custom message

### ISSUE THREAD

**Issue by WIBOR2002222** [Zrips/CMI#4068]
Since the update, there is a problem, we see each time 2 messages to say that the players connected to the server.

Additional information, I have enabled FakeLoginMessage (with the vanish)

Image :
https://ibb.co/4tMSRYG

**Comment by thomaboehi** [comment]
Est-ce que t'as fait ça dans eventCommands.yml ou dans config.yml pour les gens qui rejoignent?

**Comment by WIBOR2002222** [comment]
@thomaboehi Dans la config, enfin, dans le fichier de traduction (Locale_FR)

**Comment by WIBOR2002222** [comment]
If I update version 8.7.6.4 of CMI, it’s good. I can’t update it too no, it will redo the bug

**Comment by CloudeLecaw** [comment]
Why not simple disable the fake login/loggoff meassage?

**Comment by WIBOR2002222** [comment]
I am also obliged not the staff gets spotted when they are in vanish

**Comment by Zrips** [comment]
Reproduced, will be fixed with next update
