### ISSUE TITLE
ampersands in chat

### ISSUE THREAD

**Issue by Crazzyguyy** [Zrips/CMI#4070]
**Description of issue:**
when players that cant use colors type a "&" it shows up as "%Rep%1"
when players that can use the "&" but cant use Hex codes the ampersand just doesnt show
when players can use both "&" and Hex codes the "&" shows up correctly

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Chat section:
https://pastebin.com/cmWiY1CC
```

---

**Cmi Version (using`/cmi version`):** 
8.7.6.7
**Server Type (Spigot/Paperspigot/etc):** 
PaperMC
**Server Version (using `/ver`):** 
git-Paper-137 (1.16.1)

**Comment by Crazzyguyy** [comment]
all of /cmi version: https://imgur.com/a/C4vV7EF

**Comment by Zrips** [comment]
issue originates from having 
```
      WhiteList:
      - ''
```
Change it to 
```
      WhiteList: []
```
or wait for next update which will take into consideration situations like this one
