### ISSUE TITLE
Permission cmi.colors.[type].[colorname] is not working on versions 8.7.6.1+

### ISSUE THREAD

**Issue by EndyHell** [Zrips/CMI#4071]
Permission cmi.colors.[type].[colorname] is ignored on CMI versions 8.7.6.1 and later.

Example of colored chat message, player doesn't have permission cmi.colors.publicmessage.*:
![image](https://user-images.githubusercontent.com/17434079/91199667-d7872600-e706-11ea-928a-33bc6a503348.png)

CMI version: 8.7.6.1+

Server Type: PaperSpigot

Server Version: Paper-372 (MC: 1.15.2)

**Comment by Zrips** [comment]
Retest with latest build and if issue persists, please provide config section from Chat->Colors which determines if we want to clear color codes or not. And some extra information would be nice to know. Like output of /colorlimits and are you using CMI chat handling or another plugin for it?

**Comment by EndyHell** [comment]
Looks like I accidentally set Colors.PublicMessage to "false", that's why permission wasn't working for me. Sorry for inconvenience, the problem is now solved.
