### ISSUE TITLE
CMI custom recipes break on restart

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#4073]
**Description of issue:**
My cmi custom recipes (used mostly for condense) are breaking on server restart. 

"There is nothing in your inventory that can be condensed"

When I open the gui for the custom recipes, they are all there and look correct. I simply click the "update" button and it fixes for players until the server does its daily restart. There are no errors in console. This started happening when we went from 1.15.2 to 1.16.1. I am unsure what CMI version the issue started with.

**Cmi Version (using`/cmi version`):** 
8.7.6.6

**Server Type (Spigot/Paperspigot/etc):** 
paper, 1.16.1

**Server Version (using `/ver`):** 
paper 136 - 1.16.1

**Comment by Zrips** [comment]
Could you provide one of the examples you have setup for condense command which doesn't work after server restart? And did you tested this one with 1.16.2 version? As currently i cant reproduce issue. Tested with melon which doesn't have recipe to split it into slices, worked before and after restart. tested with recipe which doesnt have recipe ether way, still worked before and after restart.
And you could try testing this without any other plugin, in case one of them removes recipes on server startup.

**Comment by Kbryst** [comment]
We haven't rolled to 1.16.2 yet, so this is still on 1.16.1

Melon is one of ours as well, but I don't know if it broke. I'm seeing glowstone dust to glowstone, and quartz to block as the most noticed by players when it breaks.

I am a bit limited on testing due to some covid stuff going on, it may take me till Monday before I can run it on a clean server. My gut reaction is I think a plugin called "Ultimate Drugs" is clashing with it.

Ultimate Drugs has its own custom recipes, /cmi recipe shows them (unsure if its suppose to). I'm getting a lot of bug reports with this plugin (things like simple permissions not working correctly) so my gut says this is the issue.

**Comment by Kbryst** [comment]
On testing I found the plugin "BetterEnd" is the plugin that is doing something to it.

https://www.spigotmc.org/resources/betterend-premium-rethink-the-end-dimension-again.81158/

I'll report it to that dev now.

**Comment by dfsek** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-6084
This is the source of the issue. executing `/minecraft:reload` has the same effect, all recipes added via Bukkit#addRecipe are disabled

**Comment by Zrips** [comment]
As issue doesn't really originate from CMI and its issue with Minecraft itself, we will have to wait for solution from that end. But in general /minecraft:reload should not be performed, full server restart needs to be done instead.
