### ISSUE TITLE
XP error after falling into deactivated end portal

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#4076]
An error occurs when XP falls into a disabled end portal and the XP disappears. There are no problems with players or other items, if they enter the end portal they just stay there as desired. If one disables CMI, the error does not occur and the XP is preserved.

error: https://pastebin.com/UdjXJ7uh
bukkit.yml: `allow-end: false`
CMI 8.7.6.7
Paper 1.16.1 - 135 and Paper 1.16.2 - 141

**Comment by Zrips** [comment]
Error mainly originates from paperspigot, as this is not an issue with spigot. But figured out where issue originates and how to fix that. So it should work as intended with next version.
