### ISSUE TITLE
Duplicate login (and maybe logout) message

### ISSUE THREAD

**Issue by Gayytis** [Zrips/CMI#4077]
**Description of issue:**
When you join the server, it sends twice the login message. I'm not able to test the logout but i think it does the same

---

**Cmi Version (using`/cmi version`):**  latest

**Server Type (Spigot/Paperspigot/etc):** Papier

**Server Version (using `/ver`):** Paper-138

![image](https://user-images.githubusercontent.com/65625456/91232300-1f21a800-e72f-11ea-986c-448001717861.png)

**Comment by Zrips** [comment]
Got fixed with latest build
