### ISSUE TITLE
Can i somehow use the currency as way to buy items like a shop?

### ISSUE THREAD

**Issue by Pipenguim** [Zrips/CMI#4078]
**Question: **
I've seen other servers have signs on a chest that you can click, and it'll automatically take money out of your balance, and you get the item.
I want to set up a better way to buy things in shops, so it this possible?

**Comment by CloudeLecaw** [comment]
You speak of plugisn like ChestShop and ShopChest
This is not a part of cmi ;)

With CMI you can design interactive commands that are attached to signs
what they could do:
- Check if you have X Amount of Money - then Take this Money and give you X Amount of Items
- Check if you have X Amount of Item - then Take the Item and give you X Amount of Money
