### ISSUE TITLE
Rank configuration file is not reset at plug-in reload

### ISSUE THREAD

**Issue by lanessNet** [Zrips/CMI#408]
Once rank.yml is set and reloaded

/ ranklist is normally recognized

Commands such as / rankinfo or / rankup do not reload

**Comment by MCTyler** [comment]
Reload is never a suitable fix and should never be thought to work. Sry if you were informed otherwise.

**Comment by LogGits** [comment]
@MCTyler I think @lanessNet is talking about `/cmi reload`. Though, @lanessNet if you are using `/reload` than we cant help you here as you shouldn't be using this command with cmi.

**Comment by MCTyler** [comment]
Yea, I understand /reload and how it won't reload CMI with vault.

**Comment by lanessNet** [comment]
Can not you reload the CONFIG file yet? It's a really good plugin, but I think it's a disadvantage.

**Comment by MCTyler** [comment]
Yes, the config file loads just fine. We are awaiting answer as to ranks/etc that depend on Vault but if I understand right @LogGits it should work too.

**Comment by LogGits** [comment]
This should work if you are using CMI's vault located [here](http://ltcraft.lt/wp-content/uploads/2018/09/Vault1.6.11.jar) @lanessNet if you are still experiencing this issue please let me know so i can reopen this, or make a new issue request with the new layout so we can get some more info 👍
