### ISSUE TITLE
Tfly timer goes negative

### ISSUE THREAD

**Issue by VitSun666** [Zrips/CMI#4080]
**Description of issue:**
If the player receives tfly for certain ammount time and leaves the server before the flight time is over, then the timer continues to decrease even after reaching 0. If the player rejoins the server fly time keeps decreasing and doesnt reset to zero, therefore any tfly +time command will result in timer reset and wasted fly time. Also the timer will reset after secont rejoin to the game.

[Video example.](https://youtu.be/FyYA9fmoWvE)
---

**Cmi Version: 8.7.5.5** 

**Server Type: Paperspigot** 

**Server Version: git-Paper-131 (MC:1.16.1)**

**Comment by LindAn79** [comment]
yes i have the problem too!

**Comment by Zrips** [comment]
Confirmed. Will fix it with next release
