### ISSUE TITLE
./cmi homes "There is no saved homes" should offer to make one.

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#4081]
1. When a player has no homes and uses /cmi homes or /cmi home when they do not have any homes set, a new GUI should pop up with 1 icon in a GUI that says "Set new home", they can click this and it will run /sethome.

**Comment by CloudeLecaw** [comment]
When a player klicks /home and has no homes set it will be displayed in chat. why not simply redefine the langfile text and tell him to use /sethome to set first home?

**Comment by TomLewis** [comment]
Because **people do not read**.

7 years running a server, and the BEST way to get someones attention is to pop something up in their face. If its posted in chat and you have 50+ people online, its gone, they are not watching chat like a hawk looking for messages.

Sure if you only have 5 players on this might work, IF they read.

Plus its way way more user friendly. and its very basic to implement. this isn't a big ask, don't be negative for such a simple quality of life improvement. you are also not the developer.

**Comment by CloudeLecaw** [comment]
i still see no nessesary for this. Not everything needs a gui!

If player has no homes its enough to tell him he has no homes and use sethome - that what ALL others do too.
noone opens a belazzygui for him to force him to set home now

What u suggest is forcing a player to set home just because he has no homes and tried /home

**Comment by broken1arrow** [comment]
Personally text middle of the screen is better and a gui (he not need to close gui and only have a text for some seconds). 

I have set up a random teleport some give a starter home (because some left the server after get to spawn 2/3 times, because they don't know better :)). They are to lazy to put down a bed or remove it after they sleep (is soo fun how some players behave).

But hey I try not force players too much. They can remove start home (if they learn the commands or read the chat) :)

**Comment by TomLewis** [comment]
@CloudeLecaw 

> by the way your right im not the developer but the fact that u opened 4 tickets with 4 suggestions and all 4 to little things releated to homes instead of one ticket where u combined your ideas will result in one thing
Your treads will be forgotten ;)

**No.** That is not how tickets work. Its 1 ticket PER idea or PER issue, so they can be easily tracked, easily closed once there done.

Also, they got implemented and are live, so you can thank me for my suggestions.

![Screenshot 2020-08-29 11 14 29](https://user-images.githubusercontent.com/144046/91634529-fb898680-e9e8-11ea-9bcc-ee1c003cc16b.png)

Please stop being passive aggressive, You are wrong and you do not listen.

Obviously different servers have different needs, and like I told you I run an active survival for 7 years, and it has players that play on it, I wrote a script to see how many players have homes and its barely any, because the message is lost in chat.

If a user **DOES NOT** have a single home set, **WHEN THEY RUN** `/sethome`  **THEN** it opens up a GUI.

You have not understood at all.

**Comment by broken1arrow** [comment]
> 
> 
> @CloudeLecaw
> 
> > by the way your right im not the developer but the fact that u opened 4 tickets with 4 suggestions and all 4 to little things releated to homes instead of one ticket where u combined your ideas will result in one thing
> > Your treads will be forgotten ;)
> 
> **No.** That is not how tickets work. Its 1 ticket PER idea or PER issue, so they can be easily tracked, easily closed once there done.
> 
> Also, they got implemented and are live, so you can thank me for my suggestions.
> 
> ![Screenshot 2020-08-29 11 14 29](https://user-images.githubusercontent.com/144046/91634529-fb898680-e9e8-11ea-9bcc-ee1c003cc16b.png)
> 
> Please stop being passive aggressive, You are wrong and you do not listen.
> 
> Obviously different servers have different needs, and like I told you I run an active survival for 7 years, and it has players that play on it, I wrote a script to see how many players have homes and its barely any, because the message is lost in chat.
> 
> If a user **DOES NOT** have a single home set, **WHEN THEY RUN** `/sethome` **THEN** it opens up a GUI.
> 
> You have not understood at all.

If you run a bigger server, you most have a gui plugin? Way not use customalias to link /sethome to a menu you make?

Or use customalias and make this command /sethome home.

Is it a big issue if player not use homes (is more players get a harder time, if they not try to learn)? Is not many custom servers some not use a plugin for homes.

If it was your idea with gui for use icons, was good but not well thought out (i have to create new issue on this).

**Comment by TomLewis** [comment]
@broken1arrow If you run a bigger server, you most have a gui plugin?

Oh shit I actually do! deluxe menus.
It would get a big complex with logic mind, as it only needs to open a GUI if they have none, so it first needs to check they have none, as CMI already has a GUI for homes that exist already, im trying to bridge the gap between Text & the GUI that already exists.

Yes, its a learning curve, I have many other guides in place already.

What im saying is, **IF** we had the *option* in the config, to turn on opening a GUI to make a new home **IF** they player does not have any **THEN** We could trigger this with other plugins (Like putting down their first chest in GriefPreventon)

**Comment by CloudeLecaw** [comment]
you know that you can check the amount of guis allready?

creat a custom alias that checks for gui amount !=0 execute comment 1 anf 2nd command that get executed if homeamount ==0

**Comment by TomLewis** [comment]
> 
> 
> a gui is still an unnessesary even if may possible way.
> CMI offers other sulltions for this problem allready
> Sorry may my last post wasnt so helpful (may i had a bad day^^)
> So i will give you now one little sulution for this that is one way how you can release this without this extra GUI thing needed
> 
> **todo:**
> 
>     * disbale home in alias.yml
> 
>     * create a custom alias called home that checks for home amount ==0 execute comment 1 and 2nd command that get executed if homeamount !=0  (== - equal  != - not equal)
> 
> 
> **placeheolder needed for this checks:**
> %cmi_user_homeamount%
> 
> **affected files:**
> 
>     1. alias.yml
> 
> 
> ```
>   # /cmi home $1-
>   /home: false
> ```
> 
>     1. custom alias,yml
> 
> 
> ```
> CustomAlias:
>   home
>     Cmds:
>     - check:%cmi_user_homeamount%==0! cmi sethome
>     - check:%cmi_user_homeamount%==0! cmi home
>     - check:%cmi_user_homeamount%!=0! cmi home
>   home ?
>     Cmds:
>     - check:%cmi_user_homeamount%==0! cmi sethome $1-
>     - check:%cmi_user_homeamount%==0! cmi home $1-
>     - check:%cmi_user_homeamount%!=0! cmi home $1-
> ```
> 
> **what will happen?:**
> 
>     * If Player has not set a home (homemount ==0) a home is created and he gets teleported to the home
> 
>     * If Player has set a home allreay (homemount !=0) he gets teleported to tge home
> 
>     * In both cases if arguments are used behind (?) then it follows the same procudcure just with the arguments behind
> 
> 
> Why does this work even if there are two ==0 checks?
> It works because CMI is working like a basic line interepreter so it starts UP to DOWN like in old basic programming lanuages
> .
> .
> _i renember u spoke of userfriendly automatism things right? this sounds for me more userfriendly then forcing to a GUI where the player needs to create something extra_
> 
> **more infos:**
> for more information about how creating custom alias i recomment
> https://www.zrips.net/cmi/commands/specialized/ and https://www.zrips.net/cmi/commands/custom-alias/
> and maybe for placholders https://www.zrips.net/cmi/placeholders/
> you will see there are many many ways allready in CMI where we can build wonderfull things with it :)

This is a solution! But its a bit hacky, and I'm sure not as fast as if it were just built into the plugin as its using placeholderapi extensions which do not load as soon as the server starts up.

**Comment by CloudeLecaw** [comment]
im not sure if placeholderAPI is required since this is a playerholder come from CMI itself. but usually im suing the PlaceholderAPI and never tested it without. but you could give it a try.
as far as i know the tabcomplet for this mostly needs a restart of the server.
