### ISSUE TITLE
./cmi homes near:10 Have [X] Icon to delete home.

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#4083]
In the display for the `./cmi homes near:10` have an icon for delete `[X]` in chat next to it like you do with holograms etc. When you click it, it auto fills out the chat with the command to delete the home, so to not accidentally delete someones home.

**Comment by CloudeLecaw** [comment]
if the home gui is open you can delet it with SHIFT + RIGHTCLICK
or use the remove command

**Comment by TomLewis** [comment]
Thats not what I said. Look properly at what I said.

/cmi homes **near:10** 

Do you see the word "near", this is entirely separate.

**Comment by CloudeLecaw** [comment]
what is the sens of scaning for homes near someone?
i dont see the sense of scaning the whole playerdatas homes for homes near someone

**Comment by Zrips** [comment]
Next update
