### ISSUE TITLE
./cmi mail clicking a mail auto fills chat with ./mail send <username> 

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#4084]
When you click a mail sent to you in /cmi mail, it should auto fill chat with `/mail send <username> ` to quickly reply to them.

**Comment by CloudeLecaw** [comment]
why you need to autoreply? ;)

I think you mean when you click on a mail it should automatocly fillin char the command for a reply mail?

a nice idea :)

**Comment by Zrips** [comment]
Next update
