### ISSUE TITLE
Colors wont work with nameplates

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#4085]
**Description of issue:**
It does not work to put colors on nameplates.
I have tried the following:
* `/cmi nameplate Baktus_79 -pref:[Owner]_ -c:&4`
* `/cmi nameplate Baktus_79 -c:&4`
* `/cmi nameplate Baktus_79 -pref:&4[Owner]_`

None of the above works. It will add the prefix and suffix, but the color will always stay white.

---

**Cmi Version (using`/cmi version`):** 8.7.6.7

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 145 (1.16.2) and 387 (1.15.2)

**Comment by CloudeLecaw** [comment]
can you reproduce this issue with spigot too?
i renember a simlar bug ith the glow command that is related on using paperspigot...

**Comment by Baktus79** [comment]
This is my fault! Players reported seeing colors on nameplates. I use Wurst on my own server as a staff tool, and as long as I have it enabled, the colors do not work. When I turn it off, the color is there. Sorry for the interruption!

**Comment by CloudeLecaw** [comment]
Wurst... The hacker clients for cheating on servers....? 🤣

**Comment by Baktus79** [comment]
As a server owner and staff, Wurst is actually a very good tool. You would be amazed at how many other cheaters you catch.

**Comment by CloudeLecaw** [comment]
Is this a plugin? can you post its spigot or bukkit link?

I just know Wurst as a hacked client that many cheaters use to cheat on servers well what a luck that most good anticheat can forbut this hacked clients like wurst^^

but i never heared a plugin is called like that

**Comment by Baktus79** [comment]
No, this is not a plugin. Had it not been for dishonest players, it would not have been necessary to use it. But unfortunately we do not live in a perfect world. If you want to know more about it feel free to contact me privately. I do not think it is appropriate to share information here regarding Wurst nor is Wurst what I want to promote.

**Comment by CloudeLecaw** [comment]
ok^^
i just hope that your anticheat can block wurst 👍 
In our not perfect world every 3rd player use Wurst or a Loader for Mods :3..Well we are happy that most oft them are able to block for servers today
