### ISSUE TITLE
CMI Overrides other plugins

### ISSUE THREAD

**Issue by Skizzles** [Zrips/CMI#4090]
**Description of issue:**
CMI overrides other plugins like Litebans when used via console or discordsrv.
---
Hello when attempting to use console to ban someone /ban CMI overrides the ban even when Litebans is present. I have Litebans setup on bungeecord and CMI on Paper, this only happens when litebans runs on Bungeecord (Otherwise I have to update 20 modes with Litebans).
Is it possible to have CMI recognize /ban belonging to Litebans and to stop it from using its own built in ban feature. I did not see any config option to disable any moderation things like kick/mute/ban.

**Cmi Version (using`/cmi version`):** 
8.7.6.7
**Server Type (Spigot/Paperspigot/etc):** 
Paper Spigot
**Server Version (using `/ver`):** 
Paper 148 1.16.2-R0.1-Snapshot
**Relevant plugins (Delete if this isn't needed):**
LiteBans, DiscordSRV

**Comment by CloudeLecaw** [comment]
u can handle this is you know how^^
1. disable the ban command in custom alais.
2. if this is not enough then reate a customalais for ban that leads to litebands

for further version it might would help to add this to modules so the owner can disable it (cmis ban/ipban/iptempban/tempban/unban) ;)

**Comment by Zrips** [comment]
@Skizzles 
Disable /ban alias in alias.yml file and it will resolve your issues. if you will still have them after disabling alias, let me know.
