### ISSUE TITLE
Economy (money) -> database --> mysql

### ISSUE THREAD

**Issue by gethertv** [Zrips/CMI#4093]
Hi, plugin CMI is connect to database (mysql), so i have table in CMI_user name Balance.
Problem is when i change vault balance in database example on (Balance: 200). In game when i write /money or /cmi money im only have 0$ . Problem is CMI dont autoload/autorefresh Balance from database? 

Database works is true, all table create all player add to CMI_user etc.
But problem is autoload money when im play.

1/2 month ago all works, i mean when i change money from exmaple from 200 to 50 in game after 1-5second i have 50$
But last time dont works this.

Why i need autorefresh?
Because on my page
http://blowcraft.pl/case.php
i have option like Caseopen from money game.
But when player buy Key to case from example 100$
in database he get -100$ and on page to, but in game i have this same money before buy key.

Srry for engliish is not perect but i think you know what i mean

**Comment by Zrips** [comment]
I would strongly recommend to use rcon method which will send command to the server and then it will perform it properly. Changing balance in database is bad way to do things as you might have player online and depending on save delay you could overwrite current balance with older one. While performing command with help of basic rcon setup this will be avoided as money will be added to the balance and then saved properly to the database. 
Other than this you could enable ForceLoadOnLogIn in dataBaseInfo file, which will force load data from database when player logs in, but again, this is not recommended to do. Rcon is the way.
