### ISSUE TITLE
Sometimes Getting TPS Causes Error

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#4096]
```
[23:47:13 WARN]: java.lang.NullPointerException
[23:47:13 WARN]: at com.Zrips.CMI.utils.Lag.getTPS(Lag.java:31)
```

It happening again.
CMI version 8.7.6.6
Paper(149) 1.16.2-R0.1-SNAPSHOT

_Originally posted by @coco0325 in https://github.com/Zrips/CMI/issues/3523#issuecomment-682308441_

**Comment by Zrips** [comment]
Hmmm, strange one, but this points to more obvious line of code so will do some changes to fix this one.

**Comment by coco0325** [comment]
It is happening again.
CMI version 9.2.2.0
Purpur 1.17.1-R0.1-SNAPSHOT
