### ISSUE TITLE
Nice idea to give players a gui, but it has some sideeffekts

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#4098]
We use 
cmi sethome $1 block and the gui show up even if it not needed (so if you already use a block the gui not needed).

But this not even work asConsole! cmi sethome hem $1 green_bed 

First command give a block you stand on (if you only close the gui), but not the second command it is bind to a item and use alias same as the first command?

Nice if the gui had a perm too (if some players not want the gui or server owner not want you use the gui or you need pay for get the gui).

**Cmi Version (using`/cmi version`):** 
8.7.6.8

**Server Type (Spigot/Paperspigot/etc):** 
papermc 
**Server Version (using `/ver`):** 
148 1.16.2

**Comment by Zrips** [comment]
Can argue with that. Will fix issue when you already provide material and ui still opens and will add permission requirement to see this icon picker
