### ISSUE TITLE
Console spam shift rightclick spawner

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#41]
Having this spam console when a user shift + rightclicks a spawner:
https://gyazo.com/56473d32ffdb1db2e3821d18201e1d55

**Comment by TheTopCz** [comment]
Does the group have this Permission allowed?

**Comment by LogGits** [comment]
nope, this is a bug causing it to be logged to console. Meaning if a player just shift rightclicks a spawner it will spam console which isn't ideal.

**Comment by Zrips** [comment]
Well its not a bug, just some unintended behavior. Will fix this and remove those messages from console  to be more cleaner.
