### ISSUE TITLE
Inventory save not working correctly

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#4100]
When i save my inventar and cleared then the saved inventar is cleared to.

Latest CMI and Paper

**Comment by Zrips** [comment]
Will make some changes related to that, cant reproduce issue, but noticed possible cause. 
But for future, when reporting bugs you need to provide more information than this. Like command you used to save or a way you tested it.

**Comment by blakedj012** [comment]
Ok i will do that. Sorry
