### ISSUE TITLE
%server_time_format_timezone% placeholder doesn't work :/

### ISSUE THREAD

**Issue by mare-on** [Zrips/CMI#4102]
For a couple of last updates placeholder "%server_time_H:mm_GMT+2%" doesn't work.
I just tried to use "Europe/Prague" instead of "GMT+2" but nothing changed.

Last build where this formatted placeholder worked was CMI 8.7.5.8

**Comment by Zrips** [comment]
what does /cmi placeholders parse %server_time_H:mm_GMT+2% output for you? Correct time?

**Comment by mare-on** [comment]
Nope, the result is: %server_time_H:mm_GMT+2%

After removing "GMT+2" it gives me the result but it's behind due to physical server location with different timezone.

**Comment by mare-on** [comment]
Newest update fixed this issue, thanks ;)

**Comment by mare-on** [comment]
Hey, after server restarting the format is again not working :/

Output is again in format %server_time_H:mm_GMT+2% and no real time...

**Comment by mare-on** [comment]
It's really weird. One time it works other not.

After another restart it's working but it's very unstable.

**Comment by Zrips** [comment]
This could indicate issue with your java version or your server nor processing properly date like this. CMI code doesn't change, if it works once it should work for rest of the server run, if it doesn't then it should not. But if you have placeholder which randomly works and some times is not, then something is wrong with your internal setup. Show me your output from /cmi status

**Comment by mare-on** [comment]
Hi, in this moment I've got this placeholder replaced by placeholder "%localtime_timezone_<TimeZoneID>,<SimpleDateFormat>%" from PAPI. Becsuse of this placeholder works fine, there is no issue from the server side, the problem must be somewhere in CMI parsing. I think there is no usefull info from /cmi status for this... the server is running on Linux and uses Java v 1.8.

**Comment by Zrips** [comment]
Found possible cause of this issue, tho you got replacement for this placeholder, you could retest it with next update if it got resolved properly and its no longer an issue i should worry about.

**Comment by mare-on** [comment]
Hi, I tested the latest version of CMI 8.7.6.12 but unfortunately the result is still the same :/
So for this time I will stay on PAPI solution and I will re-test it with some future update of CMI,.

Thanks for your effort and don't worry about that, it can be a little piece of shit.

**Comment by mare-on** [comment]
Latest version of CMI 8.7.6.14 looking good, for this time the placeholders works, many thanks for fix ;)

**Comment by mare-on** [comment]
Hi, in the latest version of CMI v 8.8.0.3 this placeholder doesn't work... again :/
I'm using  "%server_time_H:mm:ss_GMT+1%" in Tablist.yml file and the result in game is "%server_time_H:mm:ss_GMT+1%" instead of time...
