### ISSUE TITLE
§x in console when a player uses a hex code

### ISSUE THREAD

**Issue by MrMcyeet** [Zrips/CMI#4104]
**Description of issue:**
When a user uses the new hex color codes, console logs `§x` instead of (idk what would go there in console normally).

For instance, we have a user who's `/nick` is `&0LOTHARIO&{#red>}sn&{#white<>}ea&{#blue<}ky` and he comes up in console as [See attached picture]
<img width="345" alt="gfdsfdgfsgfsdfgsd" src="https://user-images.githubusercontent.com/68966344/91605731-8b222d00-e936-11ea-903b-601ba40d10d6.PNG">

The black `LOTHARIO` is expected, because his nick color is `0`, but the `§x` (i dont think) isnt
---

**Cmi Version (using`/cmi version`):** 
8.7.6.7

**Server Type (Spigot/Paperspigot/etc):** 
Paper(141) 1.16.2-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 
Paper version git-Paper-141 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
We currently only use cmi for our chat and /nick

**Comment by Zrips** [comment]
This is not CMI bug in particular, its issue with minecraft not processing hex color codes properly and not cleaning out §x. I might have some solution to minimize this issue, but in general this needs to be done from spigot/paper side
