### ISSUE TITLE
/worthlist

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4105]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, what about command like /worthlist that will show in GUI (or atleast text) the prices of items that could be sell by players? 

### Basic explanation as to why this feature is needed and/or useful to have: ###
My players are asking for list of worth items... so this would be great.

**Comment by Zrips** [comment]
Will do
