### ISSUE TITLE
 Cross server chat not available

### ISSUE THREAD

**Issue by ShenMac** [Zrips/CMI#4106]
Cross server chat not available

**Comment by Baktus79** [comment]
This does not tell me much and a response to your statement is "Yes it is available and there is no bug". To comprehend what your problem is, I depend on you using the template that was presented to you before you wrote this bug report.

**Comment by Zrips** [comment]
@ShenMac 
Without actual explanation whats going on i cant help you out. 
on side note, you need to enable BungeePublicMessages in config file if it got disabled. And players need to have cmi.bungee.publicmessages.[servername] permission node which will represent to which servers player message needs to be sent. And both servers need to have CMI installed. Other than this, cant help out without additional information.
