### ISSUE TITLE
Placeholder requirement for rankup

### ISSUE THREAD

**Issue by titidelaff** [Zrips/CMI#4109]
Add placeholder requirement for the rankup system.

**Comment by Zrips** [comment]
Can you elaborate on this one? What placeholder and what requirement?

**Comment by titidelaff** [comment]
Example:
  Enabled: true
  DisplayName: '&2Example'
  DefaultRank: false
  RankupConfirmation: true
  AutoRankup: true
  MoneyCost: 1000
  Commands:
  - broadcast! &6[playerDisplayName] &ea rankup en &2Grand-Ecuyer!
  StatsRequirements:
  - PlayTime:3600
  NextRanks:
  - Example2
  **PlaceholderRequirements:
  - %myplaceholder%>100
  - %skyblock_islevel%>100**
