### ISSUE TITLE
Issue with the /hologram command

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#411]
Hi I had notice a small problem with holograms, if there is more holograms then 10 I can't go to the next page. Not sure why as there is no error in console ;(.

Find also problem that sometimes when editing block in /ic when trying to delete some of them they don't delete. Also I try to add /ic to a frame but no resuls is it posible to do that as it don't work.

**Cmi Version (using`/cmi version`):** 
7.7.8.1/7.7.8.2

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
1.12.2

**Comment by mercurialmusic** [comment]
Can confirm. Typing out the command to try to manually go to the next page also just brings up the first page again.

**Comment by arturek1666** [comment]
Find also problem that sometimes when editing block in /ic when trying to delete some of them they don't delete. Also I try to add /ic to a frame but no resuls is it posible to do that as it don't work.

**Comment by mercurialmusic** [comment]
As for frames, remember that those are entities, not blocks. I haven't tried adding one as an IC, but if it can be added it would be with the "add entity your are looking at" button.

**Comment by arturek1666** [comment]
Yea I did press add entity and nothing is happening.

**Comment by Zrips** [comment]
Should be fixed with next build, both issues.
