### ISSUE TITLE
Totems being used even if pvp is disabled

### ISSUE THREAD

**Issue by hotspuraz** [Zrips/CMI#4110]
I use the pvp manager plugin on my server and have totems enabled even if they're not in your hand. When a player has pvp off and takes damage from another player that would normally kill them, a totem is still used even though they cannot take damage. 

**Cmi Version (using`/cmi version`):**  8.7.5.1

**Server Type (Spigot/Paperspigot/etc):** Paper-385 

**Server Version (using `/ver`):** 1.15.2

**Relevant plugins (Delete if this isn't needed):** CMI, PvP Manager

**Comment by Zrips** [comment]
Confirmed, will be fixed with next update
