### ISSUE TITLE
How do I configure cmi world

### ISSUE THREAD

**Issue by jaydut** [Zrips/CMI#4111]
How is /cmi world supposed to be configured?

The relevant worlds were automatically generated in the RandomTeleportation: Worlds: section but only the current world and the default ones show in the autocomplete list.

Trying to change worlds that are not in the autocomplete list but that are in the config says either 'already here' or 'can't find player with this name', depending on if i provide a player name or not.

The server is using paperspigot for 1.15.2 with latest cmi and bungee.

**Comment by CloudeLecaw** [comment]
![Snag_32e1248](https://user-images.githubusercontent.com/12080017/91646912-c1ee6500-ea54-11ea-97c1-4c6446f664af.png)

what do you mean?
What plugin your suing to load the other worlds?
we are using multiverse-core for this.

cmi detects the worlds automatcly and they are listed in /cmi world command there

**Comment by jaydut** [comment]
I wasn't aware that cmi requires another plugin to be able to teleport you to them.
I was concerned about using multiverse since it hasn't been updated in a year, so I was trying to use cmi standalone.
Do you know of any other plugins similar to multiverse?
- Thanks for the help.

**Comment by CloudeLecaw** [comment]
Multiverse works fine on 1.16.2 server even its not updated so long i ecomment use the dev version not the official one
https://ci.onarandombox.com/job/Multiverse-Core/789/artifact/target/Multiverse-Core-4.1.1-SNAPSHOT.jar

**Comment by jaydut** [comment]
Oh thanks I didn't see that multiverse had an update channel, I'll try that out.
