### ISSUE TITLE
Weird TPS

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#4112]
**Description of issue:**
![image](https://user-images.githubusercontent.com/22321097/91650131-5933d680-eaae-11ea-8858-b995fadd1b40.png)
The TPS of 3~30sec shows a weird max value 0.0

---

**Cmi Version (using`/cmi version`):** 
8.7.6.9
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.2

**Comment by CloudeLecaw** [comment]
Looks like your placeholders for min and Max habe been swaped...

**Comment by coco0325** [comment]
> Looks like your placeholders for min and Max have been swaped...

I checked the translation file.
It's like '&7Max: [max] &7Min: [min]'.

**Comment by Zrips** [comment]
Locale is fine, small issue with the code, nothing serious, will make some adjustments and this should not repeat.
