### ISSUE TITLE
Personal Weather / Time Changing to a default value on Server Restart

### ISSUE THREAD

**Issue by Skizzles** [Zrips/CMI#4114]
**Description of issue:**
Personal Time/Weather is constantly unsyncing with the actual time, I have new players join and their ptime is set wrong but since they have no permissions staff have to change it for them.
---

**Cmi Version (using`/cmi version`):** 
8.7.6.9
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.2
**Screenshots:**
https://screenshots.skizzles.me/JIWA4/gOSidIPe60.png
https://screenshots.skizzles.me/JIWA4/bIGoTeZO19.png
https://screenshots.skizzles.me/JIWA4/PewiSuFA82.png

**Comment by Skizzles** [comment]
Bump

**Comment by Zrips** [comment]
Should be working properly with next version
