### ISSUE TITLE
Flight does not turn off after reaching 0 on the tfly timer.

### ISSUE THREAD

**Issue by VitSun666** [Zrips/CMI#4117]
**Description of issue:**
Flight does not turn off after reaching 0 on the tfly timer, players can fly indefenetly, ability to fly doesn't dissapear even after several relogs. 
For those flying players /cmi tfly *playername* returns: Temporary fly mode is not enabled for player.

---

**Cmi Version: 8.7.6.9** 

**Server Type: Paperspigot** 

**Server Version: git-Paper-159 (MC:1.16.2)**

**Comment by CloudeLecaw** [comment]
as a temperoray fix when the player log in you may could add a check to the eventCommand.yml on joinServer

`check:%cmi_user_tfly%!=0 fly [playerName] false -s`

this would disable fly if the tfly is 0
little problem: this also disaled fly on login for staff that may is allways allowed to fly..

lets hope the tfly issues get fixed soon

**Comment by Zrips** [comment]
Confirmed, will push out fixed version today.
