### ISSUE TITLE
Increase PlayerDeathEvent priority in SaveInvListener

### ISSUE THREAD

**Issue by NathanWolf** [Zrips/CMI#4119]
I would appreciate a change to the priority of the PlayerDeathEvent listener in SaveInvListener.

I have a plugin that can swap a player's inventory in/out. It is always restored on death.

However, since the inventory save listener's priority is LOWEST there is no way for my plugin to swap the inventory back to the real survival one before it gets saved by CMI.

---

Personally I think HIGHEST or even MONITOR makes sense for this listener since it should be the last thing that happens to the inventory after death, but anything but LOWEST would fix my issue.

This will give other plugins a chance to do whatever they need to do to a player's inventory after death but before it is saved by CMI.

**Comment by the456gamer** [comment]
it also makes sense to save it exactly as it was when the player died tho

**Comment by NathanWolf** [comment]
In the case of my plugin it definitely does not. 

I guess alternately, is there an event that gets fired when the inventory is saved? That would also help me out.

**Comment by NathanWolf** [comment]
And for what it's worth, I'm hoping I have fixed this on my side by using `load-before` but I haven't heard back from the user who was having the issue yet. I still think that giving plugins a chance to intervene if they need to is a good idea, LOWEST just locks everyone in and is not very flexible.

**Comment by CloudeLecaw** [comment]
You know that cmi can save inv on death and also not just one inv? It can save as much as u have defined and also restore them

**Comment by Zrips** [comment]
@NathanWolf 
You can still override players inventory if your plugin loads before CMI does, which means that your plugin will register its listener before CMI and will process them first, which in general is done by load-before. I set it to lowest to make sure that we have exact inventory player had when he died, at best i could move it slightly up to the LOW which should not have any noticeable impact and you can interject with your code on lowest level and perform your changes then if needed. 
Next update.

**Comment by NathanWolf** [comment]
Thank you!
