### ISSUE TITLE
At random points using /spawn or /home will teleport to a previously visited location

### ISSUE THREAD

**Issue by 27chandler** [Zrips/CMI#4121]
**Description of issue:**
At random points using /spawn or /home will teleport to a previously visited location (possibly the /back location)

This seems to affect 1/10 players who trigger it accidently in some unknown way. Once triggered, the player cannot /home or /spawn without arriving to their /back location instead, once at the /back location they are able to run the command again to go to the intended destination.

Players report they can temporarily fix the bug by relogging.

The player can be seen at the intended destination by other players whilst the bug is active for a frame before appearing at the wrong location.

---

---

CMI 8.7.6.9

PaperSpigot

Paper-148 (MC: 1.16.2)

**Comment by Zrips** [comment]
You will need to test this one without CMI as this is not something i ever got a report about and CMI doesn't cache previous locations in any sense, so it cant really take previous location in a normal situation. And some more extra information would be nice to know, like exact location they got teleported instead, if it was /back location or something else as i cant really debug it by current information or even confirm that this issue exists or originates from CMI

**Comment by 27chandler** [comment]
We've found it somehow also affects enderpearl teleportation as well. Since it doesn't appear to affect admins its possible it could be the anticheat on our server acting up. If I can confirm that then I will leave a comment here notifying you its not due to CMI.

**Comment by Zrips** [comment]
It could be anticheat, as its most likely saving some previous locations of players, tho confirmation would be nice if its CMI or if its not, so we can resolve this issue and close this ticket.

**Comment by 27chandler** [comment]
I can confirm it was the anticheat thinking players were hacking.
