### ISSUE TITLE
Blocked messages are not blocked

### ISSUE THREAD

**Issue by Crazzyguyy** [Zrips/CMI#4122]
**Description of issue:**
When player sends a message with a blocked word in chat, the message is not seen in-game, but is seen in my linked Discord chat.
When a player sends a message with a blocked word in a /msg DM, then the players still get the message with the blocked word

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
https://pastebin.com/VmvRBAWd
```

---

**Cmi Version (using`/cmi version`):** 
https://imgur.com/XzVKGiy
(8.7.6.9)
**Server Type (Spigot/Paperspigot/etc):** 
PaperMC
**Server Version (using `/ver`):** 
git-Paper-191 (1.16.2)
**Relevant plugins (Delete if this isn't needed):**
CMI
DiscordSRV?

**Comment by CloudeLecaw** [comment]
Have you enabled to use the filter in msg too?

**Comment by Crazzyguyy** [comment]
Yes, its enabled
And DiscordSRV support says it's because CMI still sends the message, just doesn't show it. Many people there thought this bug had been fixed

**Comment by Zrips** [comment]
@Crazzyguyy 
Well... In general DiscordSrv needs to ignore AsyncPlayerChatEvent with empty list of recipients, as this is what was done when you have filter type set to All. Event itself is not canceled, but recipient list is cleared out, so no one should receive this message. So in general DiscordSrv needs to add basic empty list check and not show message in a chat Chanel when that happens.
In general CMI no longer sends specific messages to discord throw DiscordSrv, it only processes messages and allow DiscordSrv to finish its handling. 
What i can do is to cancel event in case we have this type of filter which will stop messages from appearing in discord.

**Comment by Crazzyguyy** [comment]
So your adding something to fix this, or shall I messeage DiscordSRV again?

And what about the /msg?
