### ISSUE TITLE
Tab compete suggests commands players don't have permission for

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#4123]
**Description of issue:**
CMI suggests some commands even though players don't have the permission for.
Example:
This alias suggests it to all players despite having the appropriate permission:
```
  # /cmi info $1-
  /info: false
  /whois: true
```
Where as this command only suggests it to players with the appropriate permission:
```
  # /cmi whowas $1-
  /whowas: true
```
I don't have a complete list of all commands but I do have gathered my short list:
```
  - craft
  - day
  - delwarp
  - dusk
  - enderchest
  - fspeed
  - invsee
  - morning
  - night
  - rain
  - scopy
  - skull
  - storm
  - sun
  - v
  - whois
  - wspeed
```
There is not really a logic behind why certain commands work and others not.
Example:
```
  # /cmi workbench $1-
  /workbench: true
  /wb: false
  /craft: true
```
workbench is only suggested to players with permission where craft is suggested to all players. Other commands do not have more than one equivalent and are also suggested to players without permission. So there is no logic (to me) what type of alias is falsely suggested.

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.7.6.9 MySQL

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.1
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Confirmed. Should be in correct working order with next update.
