### ISSUE TITLE
Leather horse armor dosent change color when you use `/cmi dye rainbow` on it

### ISSUE THREAD

**Issue by MrMcyeet** [Zrips/CMI#4125]
The title says it all, not sure if this is impossible or just a bug, but the command runs and says that it enabled the custom color mode when you hold leather horse armor and do `/cmi dye rainbow`

**Comment by Zrips** [comment]
Because it should not do that. Rainbow armor is based on player object as we need to track constantly when some one puts armor on him. Tracking entities would introduce whole loot of checks and constant tracking which isint really something we need at this time.
