### ISSUE TITLE
CMI mirroring random places in world

### ISSUE THREAD

**Issue by kirito255** [Zrips/CMI#4128]
**Hello, I have a problem because I noticed that when you use a mirror with two people, it sticks buildings that have been built with its use in random places in the life, please investigate the matter and solve the problem:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```
Hello, I have a problem because I noticed that when you use a mirror with two people, it sticks buildings that have been built with its use in random places in the life, please investigate the matter and solve the problem
---

**Cmi Version (using`/8.7.6.9`):** 

**Server Type (Spigot):** 

**Server Version (using `/1.16.2`):**

**Comment by Zrips** [comment]
i will need more information on this one. Mirror is based on player, so it cant interfere with other players when they have mirror enabled. Any way to reproduce this issue consistently?
