### ISSUE TITLE
CMI consuming a lot since last update.

### ISSUE THREAD

**Issue by Kubson6969** [Zrips/CMI#4129]
Today we updated CMI to last version (8.7.6.10) Paper 1.16.1 and timings says is consuming a lot, with only 5 players, normally we have 20-25 players and there's no problem with timings. 

Timings: https://imgur.com/a/7qJIn5Y
https://imgur.com/a/ueqU68M

**Comment by Zrips** [comment]
You have /scan command running in background which is really heavy on the server and will lag it out while its running. I would recommend to avoid using it while players are online or set its speed to lowest numbers server can handle without loosing tps, even tho this feature will try to keep its speed at max server can handle, but you will experience some lag spikes. So simply dont use scan feature without auto speed turned on and set speed to 1 or any number which would provide stable tps.
