### ISSUE TITLE
CMI customalias permission forced

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#4130]
**Description of issue:**
Hey, on the latest version it seems the customalias permission is forced, even if you do not have it set to use a perm.

Sikatsu doesn't have permission for: cmi.customalias.craft

Also when you have a custom alias it sometimes shows this with subbase in front of it:

[11:13:49 INFO]: Sikatsu issued server command: /c
[11:13:49 INFO]: Sikatsu doesn't have permission for: subbase.command.workbench

---

[11:15:38 INFO]: CMI: 8.7.6.10 BungeeCord MySQL
[11:15:38 INFO]: Server: Paper(161) 1.16.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Confirmed, reworked some internals to properly request appropriate permission node for sub main alias. And yea, we can call alias in alias.yml which are no the first ones in the list as a sub main alias, which are handled slightly differently than main ones. 
In any case, will push out new version with fix.
