### ISSUE TITLE
dupplication with armorstand

### ISSUE THREAD

**Issue by hitakiller** [Zrips/CMI#4131]
**Description of issue:** Using armor stand editor to dupe items

**Cmi Version (using`/cmi version`):** tested on 8.7.6.7 and 8.7.6.9

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-paper-173

**Comment by Zrips** [comment]
Have you tested this without any other plugin and only CMI installed? As currently i cant reproduce this issue on same server version with your provided walk-throw. So something is different

**Comment by Zrips** [comment]
And what i noticed that you got action bar message when you clicked armorstand with nametag and item in armorstand disappeared for a second. Which plugin did that?

**Comment by hitakiller** [comment]
I've test with cmi, vault from cmi and that's all

**Comment by hitakiller** [comment]
There's my latest.log with last try (succesfull at 2nd try).
https://pastebin.com/EKbWVyDt

**Comment by Zrips** [comment]
Thats the thing, my test setup is made of minimal amount of plugins too, yet i cant reproduce your issue. Doing some extra testing to confirm this issue.

**Comment by LogGits** [comment]
This has been reproduced and @Zrips is working on a fix. Thanks for the heads up @hitakiller (just editing this post to remove reproduction methods).

**Comment by Zrips** [comment]
Will be fixed with todays update

**Comment by hitakiller** [comment]
Thank's for your help ! Have a good day
