### ISSUE TITLE
Internal cmi aliases ask for cmi.customalias.[alias] permission

### ISSUE THREAD

**Issue by kekke3r** [Zrips/CMI#4132]
Description of issue:

After updating CMI to the lastest version 8.7.6.10 I noticed that players can't execute anymore commands such as /r (reply) or /ec (enderchest) because the plugin asks for the cmi.customalias.[alias] permission. I'm aware of the fact that customalias created with /aliaseditor (with the "permission needed" flag true) need the specific permission to be executed, but what i'm talking about are the internal cmi aliases that are listed in the alias.yml file. In my server the nodes in that file are all (almost) set to true and by config the "cmi" word is not needed to execute the cmi command, all worked fine since the lastest update.
---

ERROR:
```
>.... [15:20:26 INFO]: kekk3r doesn't have permission: cmi.customalias.r
>.... [15:20:32 INFO]: kekk3r doesn't have permission: cmi.customalias.gmc
```

CONFIG SECTION:

alias.yml file:
https://pastebin.com/9R16httd

---

Cmi Version: 8.7.6.10

Server Type: Paper

Server Version: 1.16.2-R0.1-SNAPSHOT, Build:174

Relevant plugins: LuckPerms 5.1.93 (permission managment plugin)

**Comment by digitalcrowd** [comment]
I can verify this is happening.

**Comment by kekke3r** [comment]
Version 8.7.6.11 fixed it, tested and it's all good, thanks zrips!
Closing the issue
