### ISSUE TITLE
Placeholder %cmi_user_homeamount% does not update when we remove a world.

### ISSUE THREAD

**Issue by VimaMT** [Zrips/CMI#4134]
I am using %cmi_user_homeamount% in my tablist. I have noticed that, if I delete a world using multiverse or hyperverse, the number of homes in that placeholder does not change to reflect the new reality.  I had set homes in those worlds which were deleted, but CMI does not appear to know that those worlds no longer exist. It shows the original number of homes, even though I can no longer get to them.  Those old homes simply do not show up in the /homes GUI.

---

01.09 10:51:32 [Server] INFO CMI: 8.7.6.10 SqLite
01.09 10:51:32 [Server] INFO Server: Paper(163) 1.16.2-R0.1-SNAPSHOT
01.09 10:51:32 [Server] INFO CMI economy: True Vault: 1.7.3-b131(CMIEInjector) CMI Chat: True 
01.09 10:51:32 [Server] INFO Modules -> 42 enabled 10 disabled: schedule, ranks, votifier, shulkerBackpack, holograms, spawners, spawnerCharge, silentChest, vanish, homeInteractions

**Comment by CloudeLecaw** [comment]
this is normal. the home from our deleted worlds just get updated after a restart of your server. because this is when homes and warps are loaded

**Comment by VimaMT** [comment]
It is still there after several restarts.

**Comment by CloudeLecaw** [comment]
then this needs a fix

**Comment by VimaMT** [comment]
I do not know if it matters how we delete the worlds. I did not use an /mvdelete.  I simply deleted the world directory and manually removed the world files for multiverse.

**Comment by CloudeLecaw** [comment]
but not while the server is runnig....this would be a caos...

**Comment by VimaMT** [comment]
I always take the server down for stuff like this.  :-)

**Comment by Zrips** [comment]
Should show accurate home count with next update
