### ISSUE TITLE
Tab completing certain alias commands

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#4136]
**Description of issue:**
Some alias commands are not visible anymore to who has the permission to execute.
Example:
```yaml
  # /cmi enchant $1-
  /enchant: true
  #  
  # /cmi ender $1-
  /ender: true
  /ce: false
  /ec: false
  /cend: false
  /enderchest: true
  /oe: false
  /echest: false
```
`/enchant` is suggested in the tab complete
`/ender` or `/enderchest` not.
It isn't something with permissions because even OP doesn't see the commands. And turning on verbose to see if it needs permissions doesn't reveal a missing permission.

This is the opposite of my issue #4123

Another example:
```yaml
  # /cmi whowas $1-
  /whowas: true
  #  
  # /cmi workbench $1-
  /workbench: true
  /wb: false
  /craft: true
```
Should suggest via tab complete: `/workbench` and `/craft`. None of these 2 are suggested. However `/whowas` is suggested correctly.

CMI v 8.7.6.10 works a bit better, despite strange `cmi.customalias.` permission.

---

---

**Cmi Version (using`/cmi version`):** 
8.7.6.11
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.1

**Comment by Zrips** [comment]
Retested and it does seam to work correctly at this point. Player with access to base command with something like cmi.command.ender has access to /ender and /enderchest, same thing applies to workbench. Tested this on 1.16.2 and 1.16.1 version, dint encountered any issues. Have you tried to run this with CMI only in case another plugin overrides tabcomplete for you?
