### ISSUE TITLE
Colors Permissions not listening

### ISSUE THREAD

**Issue by ablac** [Zrips/CMI#4138]
I have CMI.Colors.* set to false, and when doing /colorlimits it shows that there not able to do any colors at all, yet in practice it lets them run color codes no problem.

![image](https://user-images.githubusercontent.com/1701232/91901562-41e31d80-ec55-11ea-8f83-51885204eab3.png)

**Comment by the456gamer** [comment]
is there any other relevant plugins

**Comment by ablac** [comment]
The only plugins I'm using that would effect it are LP and CMI which i use for the chat. But here is my PL list. The only reason i have MASuite is due to Cross Server Teleport, cause CMI doesn't support this.

![image](https://user-images.githubusercontent.com/1701232/91910224-74941280-ec63-11ea-9a6d-b42d6226930e.png)

**Comment by the456gamer** [comment]
is ultra customiser chat formatting enabled
does it still happen if you remove some of the plugins

**Comment by ablac** [comment]
I got rid of all plugins except Citizens, Luckperms, and CMI
![image](https://user-images.githubusercontent.com/1701232/91910892-b7a2b580-ec64-11ea-8f2e-3222883d984b.png)

![image](https://user-images.githubusercontent.com/1701232/91910904-c25d4a80-ec64-11ea-8c4a-ab2aaea0c15f.png)

**Comment by the456gamer** [comment]
What is the [s] prefix? Is that just the message format/user prefix or are you in some kind of channel

Also, don't live load plugins. Stop the server, remove them, and restart
*Backups*

**Comment by ablac** [comment]
Yes thats in CMI, i put the [S] there its to differentiate servers

**Comment by ablac** [comment]
I rebooted to get them reactivated, just disabled them*

**Comment by the456gamer** [comment]
Then remove or rename them, so they don't get loaded at all (including plugin manager)

**Comment by ablac** [comment]
Eek, I’ll be able to do that tomorrow.

Sent From my iPhone
Keith Swoger

**Comment by Zrips** [comment]
@ablac 
Did you enabled Colors-> PublicMessage in config file? As this one will determine if we will do anything with chat colors when player uses them in public messages. This will change with next update, as this is not intended behavior and will change in a way that when its disabled color will be returned in normal way as &5 and similar

**Comment by ablac** [comment]
Hey Zrips, that was set to false, I changed it to true, and did CMI reload, I’m currently on my phone though, and will test it when I get home, and let you know.

**Comment by CloudeLecaw** [comment]
Dont forget to close the ticket if it worked for you ;)
