### ISSUE TITLE
[request] Add Items as Optional Usage Requirement

### ISSUE THREAD

**Issue by wanhe886** [Zrips/CMI#414]
For the interactive commands, it will be really great if you can add a "take item" feature. Right now it can only take money. 

If it is able to take blocks and items, it can mostly replace the scriptblock plugin.

We already have **moneycost:[amount]!** and **expcost:[amount]!**. Adding a "**itemcost:[2 10]! or itemcost:[grass 10]**" (need 10 grass blocks) will be nice!

**Comment by CloudeLecaw** [comment]
This also would be a nice feature for noEconomy Servers like mine

**Comment by Zrips** [comment]
next update
