### ISSUE TITLE
CMI v8.7.6.11 - plugin is disabled

### ISSUE THREAD

**Issue by kadika66** [Zrips/CMI#4142]
**Description of issue:**
So I installed worldborder and dynmap everything seems to be working once I have it set up I start a radius rinder of 500 blocks about 10 minutes later the server times out and now CMI dynmap and LightAPI are all disabled and displaying nearly the same console error whenever you use any of their commands

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```cmi https://pastebin.com/6Y62Db0x
   dynmap https://pastebin.com/W2VNpTWM
   lightapi https://pastebin.com/KyKzt2Vu

**Cmi Version CMI v8.7.6.11 

**Server Type Paperspigot

**Server Version Paper version git-Paper-174 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT) 

**Relevant plugins dynmap lightapi cmi

**Comment by CloudeLecaw** [comment]
try without lightapi ;)

**Comment by kadika66** [comment]
cmi is still disabled

**Comment by kadika66** [comment]
removeing dynmap fixed but i want to use dynmap so if we can fix it i would like that

**Comment by CloudeLecaw** [comment]
So the problem is with dynmap? Well this plugin usually has nothing to do with cmi.

**Comment by kadika66** [comment]
Individually they both work but not together they don't. I'm actually using luck permissions not group manager and I'm sure these circumstances are unique I just don't understand why its happening

**Comment by CloudeLecaw** [comment]
Yeah this really is an unique issues. Have you tried it with a total clean new Testserver?

So just Luckperms + dynmap + cmi and the latest paper. With a fresh server (so no preconfigured folder)

**Comment by Zrips** [comment]
None of the error logs mention CMI, if plugin is not working and you are getting error on each performed command from CMI then you have faulty plugin load. We will need actual error log from that, otherwise we cant really help out here.
