### ISSUE TITLE
Bug Portals

### ISSUE THREAD

**Issue by WIBOR2002222** [Zrips/CMI#4144]
Hello, I use Paper in 1.16.2 and I also use the latest version of CMI (8.7.6.11). For the last few days, I can't create portals because it is impossible to select the location of the portal. First, I use the /portals new command and then I select the area with the wooden shovel but it doesn’t matter at all. No messages and nothing in the console.
I want to point out that my old portals still work, the command is well executed by passing in.

**Comment by Zrips** [comment]
No idea how you created portals before, but creation of them is first of all selection of area where portal needs to be created, by default its woodenshovel, alternatively you can use commands **/cmi select pos1** and **/cmi select pos2** and then perform **/cmi portals new myPortal** command which creates portal and opens portal edit UI where you can adjust some settings of it.
