### ISSUE TITLE
[Performance] Interactive commands manager loading sync

### ISSUE THREAD

**Issue by Fabrimat** [Zrips/CMI#4147]
Interactive command manager loads all the locations blocks in the main thread causing the server to freeze when having a lot of them.
I have more than 200+ and it takes more than 30 seconds on startup and on /cmi reload to fully load.
Making it async on Paper and splitting the loading across more chunks on Spigot would be a thing.
Thanks

**Comment by Zrips** [comment]
Will make some improvements for loading times with next release
