### ISSUE TITLE
radius broadcast / world broadcast

### ISSUE THREAD

**Issue by levarar** [Zrips/CMI#4148]
Add the ability to use Broadcast in a specific radius or world

**Comment by CloudeLecaw** [comment]
Thats a shout what you want, there u cannspcify radius. Probleme if broadcast is u have no defined Center and it's broadcast to All worlds.

May thought about using shouts instead of broadcast?

**Comment by Zrips** [comment]
@levarar 
You do have option to broadcast to specific world already with (-w:[worldName,worldName]) for range, will add that with next update
