### ISSUE TITLE
custom command for attached commands items

### ISSUE THREAD

**Issue by Stoniasawsome** [Zrips/CMI#4149]
**Description of feature/improvement request:**

  I think it would be productive to have a special feature for "custom commands".
For example: When i make a cool item with an attached command, i have  no way to get this item into circulation, unless i add it to something that allows drag and drop custom items, like a loot crate, and kits or something. or personally hand it to someone. If there was a feature where i could use a command to pull that attachedcommand item from a file, to get it into circulation it would be great.
 example:
Make an item with an attached command 
Hold the item with the attachedcommand
 type, example: /cmi applycustomcommand [mycustomcommand].
 Then if the command /cmi mycustomcommand is used, you get that item with the attachedcommand
If we had something like that then the possibilities would truly be endless for attachedcommands and it could be implemented many different ways to make life more interesting. Ive looked for plugins like this and the last one was from like 1.12 and its called myitems
Thanks for your time

**Comment by Stoniasawsome** [comment]
thats not what i meant. i already have attached items, but no way to give them to players besides crates or kits, a simple command that would spawn your attachedcommand item on demand. like if i had an item with an attachedcommand i would like a command to say "give player specific item with attachedcommand".

**Comment by CloudeLecaw** [comment]
Why dont create a kit with the item, and give the kit by customalais? You also could add some requirements to this based in spezialzed commands.

For item command templates use a little nice Tool called Editor ;) 

You can create interactive commands or custom alais with requirements that Player can use like a command for money or with permission. Or a sign that attch the command to hold item of the player without giving them permission to it

**Comment by broken1arrow** [comment]
> 
> 
> Why dont create a kit with the item, and give the kit by customalais? You also could add some requirements to this based in spezialzed commands.
> 
> For item command templates use a little nice Tool called Editor ;)
> 
> You can create interactive commands or custom alais with requirements that Player can use like a command for money or with permission. Or a sign that attch the command to hold item of the player without giving them permission to it
> 
> Clearest solution at the Moment, give a kit silent with a custom alais that has requirements so not everyone can use it (this also can be moneycost or what ever, and it also can includee a placeholder vor variable1 what could be a playername z used after the customalais)
> 
> Then you could typ /customalias player
> And the player will get the item. May Add some nice meassage to him as secound command in the customalais so the player sees a Text like "You got the great gigaitem, use it wise because you just can use it 3 times."
> 
> Ask if you may need help with this ;) then i could post you some codelines for the kit and the customalais if needed.
> 
> Or do you have 1 Millionen items that needs to be presaved somewhere?

Or use saveditems :) You can use customalias to that to :) run the command as console or give players perm for 5 seconds and a give command.

**Comment by Stoniasawsome** [comment]
hey thanks for your help, this seems logical. ill try it and copy paste this conversation for future reference! Thanks again!

**Comment by Zrips** [comment]
@Stoniasawsome 
As people pointed out, you can use **/saveditems save uberitem** and then when needed you would simply do **/saveditems give uberitem -t:[playerName]**
