### ISSUE TITLE
Console spam after commands and randomly

### ISSUE THREAD

**Issue by trickman325** [Zrips/CMI#4150]
**Description of issue:**

Getting console spam from cmi and placeholder connection by the looks of it.
Was happening randomly and also after commands and force /spawn on player join

**ERROR:**
https://pastebin.com/arEPKG5k

---

**Cmi Version (using`/cmi version`):** 8.7.6.11

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper(175) 1.16.2-R0.1-SNAPSHOT

**Relevant plugins (Delete if this isn't needed):** PlaceholderAPI version - 2.10.9

**Comment by Zrips** [comment]
Next update should not have this issue

**Comment by trickman325** [comment]
@Zrips issue remains on 8.7.6.12
https://pastebin.com/U14v9ee5
