### ISSUE TITLE
Loose Flightcharges when i go through portal

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#4152]
I think this is a bug if you walk through portals with flightcharges you lose the number of blocks the portal is probably distanced. But when I fly through it nothing happens. It would be better if you never lose flightcharges when you go through a portal.

Latest Paper and CMI

**Comment by Zrips** [comment]
What type of portal are we talking here?

**Comment by blakedj012** [comment]
You CMI Portals

**Comment by Zrips** [comment]
Give me your flight charge config section and do you use provided teleport mechanics of portals or do you use command to teleport player to another location?

**Comment by blakedj012** [comment]
FlightCharge:
  # When set to true, each time player gets flight charge or relogs, his fly mode will be toggled on
  # If set to false, then players will have to manually turn on flight with /cmi flyc
  EnabledByDefault: true
  # When set to true, in event of player changing his game mode from survival/adventure to creative/spectator his flight charge  mode will get disabled
  # Same applies when changing game mode from creative/spectator to survival/adventure
  AutoSwitch: false
  # How much it costs for one recharge point in exp points. Value can be in decimals, like 0.2 but it cant be equal or lower than 0
  # Set to 0 to disable this type of recharge
  ExpRechargeCost: 1.0
  # How much it costs for one recharge point. Value can be in decimals, like 0.2 but it cant be equal or lower than 0
  # Set to 0 to disable this type of recharge
  MoneyRechargeCost: 1.0
  # Defines maximum amount of charge player can have
  # One charge is one traveled block while flying
  # if player doesn't move, then one charge for each second while hovering
  MaxChargeLevel: 10000
  # Defines multiplier when player doesn't move but is hovering. For each second player hovers.
  # Set to 0 to disable
  DeductOnIdling: 1.0
  # If this is set above 0, then player will loose defined amount of charges each second they are flying instead of traveled blocks
  # Set to 0 to disable, which will deduct charges for traveled blocks
  DeductOnlyForTime: 0.0
  # Defines multiplier when player falls down of charge to be taken
  # This only effects when player falls from above 3 blocks of hight
  # In example if player falls from 10 blocks height, then 7 * 2 = 14 charges will be taken
  # This is to prevent avoiding no penalty from jumping from cliffs
  # Set to 0 if you want to disable it
  DeductOnFallMulti: 2
  # Defines if you want to damage player when he falls down from higher than 3 blocks height
  # This will not kill player even if he would drop from 200 block height, but will leave him with 1 hp
  # This will only effect players who jumped down and not those who disabled fly mode in mid air
  DamageOnFall: true
  # DamageOnFall should be enabled for this to work
  # This will define if you want to damage player when he deactivates fly mode in mid air
  DamageOnToggle: false
  # DamageOnFall should be enabled for this to work
  # This will define if you want to kill player if fall damage if higher than his health amount
  KillOnFall: false
  # When color name is defined then at moment player starts flying with flight charges, he will start glowing
  # Set this to 'none' if you want to disable it
  GlowColor: none

and i use the normal teleport mechanics from cmi portals

**Comment by blakedj012** [comment]
Hmm why its so big?

**Comment by Zrips** [comment]
Should be resolved with next update

**Comment by blakedj012** [comment]
Thanks i have testet now. So it does not draw off any more or not so much. Because the problem is when you go through a portal with flightcharges you arrive at the new location in flight mode. So you float in the air and lose now always about 5 FLightcharges. 

So you walk through a portal but you float in the air at the new location and lose some again.

**Comment by blakedj012** [comment]
No all is ok. I have set the Teleports new and now im not more stand in the air when im teleport.
