### ISSUE TITLE
Holograms causing performance leak

### ISSUE THREAD

**Issue by BBSnowIce** [Zrips/CMI#4153]
**Description of issue:**

I'm using CMI holograms and I noticed performance issue when there are more than 10 players, viewing same holograms, it's not client side but well server side, I've got many tps loss due to cmi holograms (that's what i conclude from a timings report) . Could hologram management maybe be async ?

---

**Cmi Version (using`/cmi version`):** 
8.7.6.13
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
git-Paper-1618 (MC: 1.12.2)

**Comment by Zrips** [comment]
Part of it is in async, but biggest question would be: What do you show in them? What i mean that hologram performance is directly related to how you setup them. if you have big update range and frequent one while at same time you have some heavy placeholders in holograms from some external plugins, then you might have issues related to performance. But we cant really update holograms entirely in async, especially when we have placeholders, as not all of them can be accessed in async without causing issues. 
More information is needed.
