### ISSUE TITLE
Auto Updater

### ISSUE THREAD

**Issue by ablac** [Zrips/CMI#4154]
Hey Zrips! I love the fact that your so active with CMI but sometimes it can be quite the challenge staying up to date with CMI, it would be really awesome if you could add a way to update the plugin while the server was live, or possible even automatically when a new version is released. It’s already able to check for new versions and display a message.

Myself and I imagine a bunch of other server owners would love to see something like this.

**Comment by CloudeLecaw** [comment]
This is normal. When new Version of a plugin is Released the Update Systems of the spigot servers need a while before they recocnized that the Update is there. Mostly u see Update to one Version earlier then on login. There is nothing Zrips can do there. All you can do is check if the faulty meassage still apears on next day. Normaly it should be done with in max. of 24 hours

**Comment by ablac** [comment]
My server and i would assume most servers already do a nightly restart though. It would be nice to automatically download newest version, and then on the next reboot replace the jar file with the downloaded file. I don't believe this would be that challenging to implement, and could save server owners a ton of time. I believe the hardest part would be limiting who has access to the downloads.

I'm assuming on premium Purchases that Spigot Puts a secret code into the jar files to verify that it was purchased? At least that's what a few other premium devs told me... but if that's true you could use that to verify that its a legit purchase, or even pull it directly from spigotmc

**Comment by CloudeLecaw** [comment]
If the plugin is downloaded on spigot direcly.. but if a server downloads it.. where spigot does know who downloaded it?

**Comment by ablac** [comment]
There’s ways to do it though, maybe you have it link directly to Zrips development server and download directly from there, but checked an API key issued by a bot in discord, or even better requires the Server IP to allow for download from a dev server. And it’s really just a matter of building a system to verify that CMI was purchased, which he already has in place on discord if I’m not mistaken.

**Comment by LogGits** [comment]
This is beyond the scope of the project. Auto-updaters for premium plugins sound easy but have alot of hidden complexities that take ALOT of time to get right.
