### ISSUE TITLE
Search global not working

### ISSUE THREAD

**Issue by kweber1** [Zrips/CMI#416]
We are having an issue with a global search for an item.

The item is found when a radial search is done, but when a global search is done it does not work.

We tried saving the world and restarting to make sure the chunks are saved, yet it still did not find the item.

We did the default diamond blocks search that is found on your wiki.

After testing more, doing a radius of 2000 or more also did not work, but doing a radius of 1000 and less worked.

**Cmi Version (using`/cmi version`):** 
7.7.8.2

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
Paper version git-Paper-"f1a5652" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Test out new version which should be posted today, and if issue persists, reopen or repost issue. But there will be some changes related to scan feature with next build.

**Comment by kweber1** [comment]
Still did not work
