### ISSUE TITLE
pre 1.16 colors don't translate

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#4160]
**Description of issue:**

Custom join/ quit messages at least pre 1.16 colors don't get translated (& format)
works in chat though

---

**Cmi Version (using`/cmi version`):** 
8.7.6.13
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
paper -184 1.16.2

**Comment by mrfloris** [comment]
I've also noticed if you use like msg! [playerName] &b blah &e blah in aliaseditor, that they show as plaintext now.

**Comment by x1p** [comment]
Same.
Since these `msg! [playerName] &bblah blah` are used in important stuff, it's pretty annoying.
Workaround: `§`

**Comment by kekke3r** [comment]
Can confirm it, I like the new color features but i really don't want to change all the old color codes with the new ones, at least not all of them at the same time :S

**Comment by Zrips** [comment]
Should be resolved now, posted hot fix

**Comment by mrfloris** [comment]
Fixed! :)
