### ISSUE TITLE
Per World option for sleeping feature.

### ISSUE THREAD

**Issue by KasearMC** [Zrips/CMI#4161]
can you please add a per world option for the feature that speeds up the night cycle when a certain amount of players are sleeping?
https://pastebin.com/KAriwSdu

i want to use this feature but i only want it to work in one world. 

something like 

EnablePerWorld: true
--AffectedWorlds:
----world
----world3

**Comment by CloudeLecaw** [comment]
When you sleep in a world normaly you get day straight without Animation.... Speed up does not apply automaticly.  I think what you want is different day/night times for different worlds right?

**Comment by Zrips** [comment]
Will add with next update
