### ISSUE TITLE
Different TPS

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#4162]
**Description of issue:**
The TPS in /cmi status and /cmi tps show different value at same time.

I sent those two commands at almost the same time, but the results were completely different.

![image](https://user-images.githubusercontent.com/22321097/92317823-99a7cd00-f037-11ea-96bb-db190dbcb096.png)
![image](https://user-images.githubusercontent.com/22321097/92317826-9f051780-f037-11ea-83c3-ca94562ed3c7.png)

---

**Cmi Version (using`/cmi version`):** 
8.7.6.10
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.2

**Comment by Zrips** [comment]
Good catch, will be fixed with next version
