### ISSUE TITLE
Question about Definition for item:[data]! ? 

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4164]
> If command starts with item:[item:)data](-amount)! then command will get performed if player has enough defined items. Example: item:stone:1-12! will require 12 granite blocks for command to be performed. 

Is it possible to define an item that is needed when it has other itemname or a lore? 

If it is can you post an example? (pls dont answer with just "yes it is without example")

**Comment by Zrips** [comment]
Not currently. Its using general format to recognize item from provided string, which currently only includes material name, amount and/or type, for example spawner:zombie can be recognized, nut not item name or lore, i need to think of simple format when defining item information which would not include any spaces in it but could be allot simpler than json Mojang requires you to remember
