### ISSUE TITLE
Empty %cmi_user_prefix% w/ UltraPermissions

### ISSUE THREAD

**Issue by mare-on** [Zrips/CMI#4166]
Hi,
on my server I'm using [UltraPermissions](https://spigotmc.org/resources/42678) and since v4.7.8 they have changed the method of delivering the prefixes... they are using special placeholder called: %uperms_prefix% which unfortunatelly needs plugin [PlaceholderAPI](https://spigotmc.org/resources/6245) to work.

I'm using the latest version of CMI 4.7.6.14 which can't recognize prefixes from this plugin :/
Parsed output of the placeholder: %cmi_user_prefix% is empty.

I don't need to use any extra plugin like PlaceholderAPI only for handling the prefixes so is there any chance that CMI could handle this special prefix from UltraPermissions?

This issue is 50:50 a bug but also a suggestion. I think that CMI is designed to recognize any type of prefix from any permissions plugin. UltraPermissions is modern and robust so it would be sad that CMI will be not supposed to recognize their prefix method.

**Comment by CloudeLecaw** [comment]
Cmi can get the prefix and suffixe from any but to garantee work its recomment to use the placeholderAPI you said your allready using it.

So if CMI does not see them now with uperms_prefix used in the chat format then this looks like a bug. Its not garantee that the cmi_user_prefix will see then all in all cases of all permission plugins. Same to suffix

**Comment by Zrips** [comment]
First of all, suggestion: get a better permission plugin. 
Second, its nice when developers completely changes their API in a minor version update... Because why not...
Third, will update UP support to fit new API which should properly return players groups, prefix or suffix
