### ISSUE TITLE
Clear Issue

### ISSUE THREAD

**Issue by Cryper** [Zrips/CMI#4167]
**Description of issue:**

Since one version (i dont know which one . Between 8.7.6.6 - 8.7.6.14) The command /clear wont work correct. With Version 8.7.6.6 i can clear a specific item from the Inv. But with Version 8.7.6.14 i delete the whole inventory

**Cmi Version (using`/cmi version`):** 

8.7.6.6 Test Server 
8.7.6.14 Main Server

**Server Type (Spigot/Paperspigot/etc):** 

PaperSpigot

**Server Version (using `/ver`):** 

Paper-184 (1.16.2 MC)

**Comment by Zrips** [comment]
What command exactly are you using? Retested on 1.16.2 with basic /clear stone-10 and /clear stone while having items in inventory, including some stone, then correct amount (10 and 1) got removed without touching any other item.

**Comment by Cryper** [comment]
I execute the Command via Console. Try to clear a Written Book Author:Server . (/clear [playerName] written_book{Author:Server})
Works fine if i execute it. But if the Console do it, the whole inv get erased

**Comment by Zrips** [comment]
och, so you have incorrect format here. What i mean that  written_book{Author:Server} isint supported as valid format and doesn't get recognized as valid item in which case inventory gets cleared out. No idea why it worked for you ingame, most likely another plugin took over this command, but this should not work with format like that. 
Will make some adjustments to accept format like this with future updates.
