### ISSUE TITLE
Ranking system

### ISSUE THREAD

**Issue by DragonisOmega** [Zrips/CMI#4168]
**Description of issue:**
The ranking system only shows that people have broken blocks after a restart.
when my players log in and break blocks or items the ranking system counts them.
if they leave and comeback the only way they can get block breaks again is if I restart the sever.

It's been going on for a bit just haven't had time to report it.
small enough server to just do a restart.  Now it's starting to annoy
cause I am not onhand 24 -7 to do a restart for people.
---

**Cmi Version (using`/cmi version`):** 
8.7.6.12
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
1.16.2

**Comment by Zrips** [comment]
tested out with 1.16.2 server, seams to be working properly. 
Could you check if /stats updated with correct values. And check what it shows in players statistics window ESC->Statistics
And could you test it without any plugin and only CMI? As CMI takes statistics from Minecraft records and doesn't perform any tracking by itself, it only returns values Minecraft recorded in its statistics database. So something prevents new statistics being recorded after player relogs
