### ISSUE TITLE
CMI Bungee set teleport location no success message

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#4174]
When i set a portal from server to another server i dont get a success message when i set the portal over the chat message.

Latest Paper & CMI

**Comment by Zrips** [comment]
Do you have CMI on both servers? if you dont, ether add CMI to both of them or use command to send players to target server, it might not send to exact location, but it can atleast send to target server.

**Comment by blakedj012** [comment]
Yes i have portals over server works. But i dont get a success message. Like a normal Portal

**Comment by blakedj012** [comment]
I mean this message
https://gyazo.com/2b4f2fd24fb7c6be6b014b18a2081ca9

**Comment by Zrips** [comment]
Och, so its working, but it simply doesn't show confirmation message that it was successfully set?

**Comment by Zrips** [comment]
Will add feedback message when portal location is set properly on source server

**Comment by blakedj012** [comment]
yes thanks sorry for late answer
