### ISSUE TITLE
add sender to CMIUserBalanceChangeEvent

### ISSUE THREAD

**Issue by kikelkik** [Zrips/CMI#4176]
**Description of feature/improvement request:**

---
I'd like to hook into CMI when an economy player transaction is made in order to introduce a transaction fee (extra cost of transaction amount in percent). 
To get this work, the CMIUserBalanceChangeEvent is lacking of the sender. 
Maybe it might be better to introduce a new CMIUserBalanceTransactionEvent so this will only be fired if the sender is a player.

**Comment by Zrips** [comment]
At best what i can introduce is source of transaction when it was made with /pay command, other actions in general will not provide source, especially if its originating from another plugin.

**Comment by CloudeLecaw** [comment]
> CMIUserBalanceChangeEvent Will include source user if possible when money transaction is performed, to indicate who looses or gains money from this transaction. This is just indicator in case you want to perform some actions on it. Currently only applies to /pay command

may this ticket can be closed? ;)

**Comment by kikelkik** [comment]
Alright thanks, I‘ll close this ticket 👍
