### ISSUE TITLE
%server_online% works correctly only inside the CMI

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#4178]
**Description of issue:**

Placeholder %server_online% counts vanished players. Players can easily guesss that there are some vanished players if they count the number of players in tab and compare that with the value of the placeholder. When run `/cmi placeholders parse %server_online%` it will show the correct number only for the internal use of CMI, but the value exposed to the other plugins like TAB will be incorrect.

**Cmi Version:** 
8.7.6.16
**Server Type:** 
Paper
**Server Version:** 
Build 185
**Relevant plugins:**
PlaceholderAPI

**Comment by CloudeLecaw** [comment]
When you have placeholderAPI and also installed the server extansion then other plugins should be able to use it too

> 
> /papi ecloud download Server
> 
> Lets you get information about the server.
> 
> %server_name%
> %server_online%
> %server_version%
> %server_max_players%
> %server_unique_joins%
> %server_uptime%
> %server_ram_used%
> %server_ram_free%
> %server_ram_total%
> %server_ram_max%
> %server_tps%
> %server_tps_1%
> %server_tps_5%
> %server_tps_15%
> %server_tps_1_colored%
> %server_tps_5_colored%
> %server_tps_15_colored%
> %server_online_<world>%
> %server_has_whitelist%
> %server_total_chunks%
> %server_total_living_entities%
> %server_total_entities%
> %server_time_<SimpleDateFormat>%
> %server_countdown_<SimpleDateFormat>_<time>%
> e.g. %server_countdown_dd.MM.yyyy_01.01.2020

**Comment by radiant-ai** [comment]
I did not say it does not work entirely, I said that it shows incorrect values.

The problem persist for a couple of months already. Just to make it clear:
I have 2 players in server: OP and a Dummy. OP vanishes and Dummy has no permission to see it.
As OP I run:
`/papi parse OP %server_online%` and get 2,
then I run:
`/papi parse Dummy %server_online%` and still get 2.

Using TAB plugin and %server_online% it shows 2 players for Dummy and 2 players for OP. While there is only one player in a tab list.

All of this was done using PAPI 2.10.9 and the latest version of Server expansion (2.3.1).

**Comment by CloudeLecaw** [comment]
because one player is vanished and the TAB sees that but server_online sees the true amount

**Comment by radiant-ai** [comment]
_%server_online% works correctly only inside the CMI_
Yeah, it would be fine if I used CMI tablist, but I use another plugin

**Comment by CloudeLecaw** [comment]
Maybe the other plugin phrases it wrong. i see no Point where CMI can handle here. May you have ti write the other dev.

**Comment by radiant-ai** [comment]
If I get a response that it works as intended I will create a feature request to bring back the %cmi_server_online% which will expose the correct number of players to other plugins.

**Comment by Zrips** [comment]
@radiant-ai 
Well its actually a good point related to those placeholders, as they have been added originally to replace some internally used placehoders in case you dint downloaded correct papi extension. But in this case when we need to process data in a specific way, we might want to have dedicated placeholder from CMI. As any placeholder which doesnt start with CMI will not get processed by CMI outside it. So solution is simple %cmi_server_online% with next update
