### ISSUE TITLE
/Colors aren't showing replaced colors

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4179]
**Description of issue:**

---
Hi, the problem is, as you can see on screenshot, that command /colors is broken and doesn't show replaced colors.
https://imgur.com/VXbC3ho

---

**Cmi Version (using`/cmi version`):**  8.7.6.14

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  Paper 184, 1.16.2

**Comment by CloudeLecaw** [comment]
This is fixed allready in 8.7.6.14 or higher

**Comment by Zrips** [comment]
This was fixed in recent versions.
