### ISSUE TITLE
Placeholder for sign lines in IC-Editor broke

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4181]
![Snag_83fdcb](https://user-images.githubusercontent.com/12080017/92539167-f75b3580-f240-11ea-923e-a8f52ace3113.png)

U see name and lines are empty even if u edited them with the ICEditor

**Comment by Zrips** [comment]
You will need to be more specific here. What lines are empty? What should you expect to see? If you dint defined sign line in sign editor then we will not modify assigned sign in any way, atleast not those lines which doesn't have defined text.

**Comment by CloudeLecaw** [comment]
When i attach an ic to a sign then i am able to edit the lines. Normaly when i edit them then i see the line of the sign that u have edited with the i Editor. That Was how it worked before. I klicked one editline klicked in the frist an after entering the text i saw the change on the sign and in the Editor it also was listed then. At the moment the sign line changes but the gui Shows the empty line still.

**Comment by LogGits** [comment]
Can you provide either a step by step process or a video to reproduce this. I tried creating a sign with the exact same text and formatting that you used. I tried with wall signs and regular signs. A video showing how to reproduce this from scratch or a detailed step by step process would be helpful (e.g. step 1: x, step 2: y, etc)

**Comment by CloudeLecaw** [comment]
ok
1. i create the IC-command
![image](https://user-images.githubusercontent.com/12080017/92595270-60c06000-f2a4-11ea-8b4e-aabbeb486332.png)

2. i place a Sign and look at it
![image](https://user-images.githubusercontent.com/12080017/92595602-eba15a80-f2a4-11ea-9d13-2a578cd0f8d7.png)

3.  i klick there to get to Block/Entity part of the IIC-Editor
![image](https://user-images.githubusercontent.com/12080017/92595860-45098980-f2a5-11ea-8312-313eb3196594.png)

4. i click the 1. + to add the Block i am looking at
![image](https://user-images.githubusercontent.com/12080017/92596139-a598c680-f2a5-11ea-9c64-e2e4424e616e.png)

5. i click Edit SignLings to edit the lines of the sign that was added
![image](https://user-images.githubusercontent.com/12080017/92596272-ded13680-f2a5-11ea-813c-f9bd142eabc4.png)
GUI now looks like this:
![image](https://user-images.githubusercontent.com/12080017/92596358-fd373200-f2a5-11ea-87c3-650991cab4ed.png)

6. klick on the first line that is called [befehle] what means command....(why its called command there? I enter in Chat &3hey You. this should result in having %3hey you in line 1
![image](https://user-images.githubusercontent.com/12080017/92596625-61f28c80-f2a6-11ea-8ccb-589c361dc3bf.png)

7.
Result: Change is taken on the sign.
unter it there is the SignLineMenue showing the wrong thing...
![image](https://user-images.githubusercontent.com/12080017/92596706-89495980-f2a6-11ea-8fa0-1591d92cf2e9.png)

You now could klick on line2,3,4 and change them too it does not matter.

**Comment by Zrips** [comment]
@CloudeLecaw 
Noticed that you have [Name] on top, which should have been replaced with IC name. It looks like you have some issues with your file translations. by your provided example it doesn't even look like you even using this same locale as your provided one has correct `      titleC: ' &e--- &6[name] '` double check that you are using correct locale and its set to this file and not another one

**Comment by CloudeLecaw** [comment]
i am using
Locale_DE.yml

```
# Language file you want to use
Language: DE
Economy:
```

and the lines i posted u where from thisfile...

**Comment by Zrips** [comment]
lines 700 and 701, change to
```
  commandTitle: ' &e--- &6[name] &e---'
  commandList: ' &e[command]  '
```

**Comment by CloudeLecaw** [comment]
fixed. Thank you for pointing this out <3
