### ISSUE TITLE
Shortened Format for Baltop Placeholders

### ISSUE THREAD

**Issue by trickman325** [Zrips/CMI#4183]
**Description of feature/improvement request:**

I would love to have the **%cmi_baltop_money_[1-10]%** as a shortened format version.
something like **%cmi_baltop_money_formatted_[1-10]%**

---
### Detailed explanation of what it should do, when and in what situation: ###

Returns the same as %cmi_baltop_money_[1-10]% but in a k,m,b... and so on format.
Same as **%cmi_user_balance_formatted%** does (10.0k)

### Basic explanation as to why this feature is needed and/or useful to have: ###

I have a hologram baltop leaderboard on my op prison server and players having $5b is just a spam of numbers
it would just clean it up for people who have large economys

**Comment by Zrips** [comment]
Simple addition, will add with next update
