### ISSUE TITLE
The instruction requires an underbar.

### ISSUE THREAD

**Issue by EndlessLegends** [Zrips/CMI#4187]
**Description of issue:**
---
If there is no underbar in the item name of the "/cmi giveall" command, a number is requested.
/cmi giveall **totemofundying** 1 n test l test offline

= **&cPlease use numbers!**

/cmi giveall **totem_of_undying** 1 n test l test offline

= **complete!**

system
---

**Cmi Version (using`/cmi version`):** 
8.7.7.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
git-Paper-186 (mc:1.16.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will be fixed with next build
