### ISSUE TITLE
If the target's name is a number, it is not recognized as a player.

### ISSUE THREAD

**Issue by EndlessLegends** [Zrips/CMI#4189]
**Description of issue:**
Target selectors'[playerName], [playerdisplayName], [etc...]' do not recognize a player named 123456789.

cmi portals edit wild 0
->
cmi tppos [playerdisplayName] 7.5 64 21.5 overworld
->
NumberName player go to portals
->
The player cannot be found.
---

**Cmi Version (using`/cmi version`):** 
8.7.7.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
paper-186 build

**Comment by Zrips** [comment]
As /tppos command help page says, to define player which needs to be releported you need to use -p:[playerName] in this case it would be 
`cmi tppos -p:[playerName] 7.5 64 21.5 overworld`
And avoid using [playerdisplayName] for command variables as some display names could prevent user from being teleported or command being performed on him in general, so [playerName] is a safer option
