### ISSUE TITLE
TPS in placeholder doesn't match with /tps command

### ISSUE THREAD

**Issue by RispyCZ** [Zrips/CMI#4190]
**Description of issue:**
TPS in placeholder are 12 but in /tps 20 and server isn't lagging at all. So quite confused about it :)

**Cmi Version (using`/cmi version`):** 
8.7.6.7
**Server Type (Spigot/Paperspigot/etc):** 
Paper 
**Server Version (using `/ver`):** 
186

**Comment by Zrips** [comment]
This was fixed with .10 version
