### ISSUE TITLE
Make totem of undying give the same effects from 1.16

### ISSUE THREAD

**Issue by NeuTraLZero** [Zrips/CMI#4192]
**Description of feature/improvement request:**
Make totem of undying give the same effects from 1.16
---
### Detailed explanation of what it should do, when and in what situation: ###
Make totems give the same effects from 1.16 when RemoveFromInventory is set to true and/or add an option to adjust effects duration or turn them on/off seperately
### Basic explanation as to why this feature is needed and/or useful to have: ###
This can be very useful especially since totems that are used any where in the inventory doesn't give the fire resistance like how they do in 1.16+ or if you might want to adjust some effects so that totems aren't too overpowered

**Comment by Zrips** [comment]
I can add vanilla fire resistance to the effect list and add option to define duration's of those effects. Next udpate
