### ISSUE TITLE
How i alter cmi so it not change gamemode for mods and admin

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#4193]
***Question: ***
I have add this cmi.worldlimit.gamemode.bypass and it not work, is still change from creative to survival.

**Comment by Zrips** [comment]
This could be caused by another plugin overriding this game mode, usually its multiverse plugin or similar. You might want to test it without any other plugin and CMI only to make sure that issue originates from CMI

**Comment by broken1arrow** [comment]
It is thrue, Hm I think multiverse was off on the server i try on, so yea likely the issue (thanks i think it solve now).
