### ISSUE TITLE
TPS Command Issue

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#4195]
**Description of issue:**
https://pastebin.com/u2BXszuu after /tps
Maybe use Math.min(a,b)?

**Cmi Version (using`/cmi version`):** 8.7.7.0

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  1.16.2

**Comment by Zrips** [comment]
Its just a left over debug message which needed to be removed. In any case, will be fixed with next version.
