### ISSUE TITLE
CMI disables if Dynmap disables

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#4196]
**Description of issue:**
If an error occurs when Dynmap is starting and it disables, that also causes CMI to throw an error and disable as well.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/QXJNwP02
```

---

**Cmi Version (using`/cmi version`):** 
8.7.7.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper - 192 - 1.16.3
**Relevant plugins (Delete if this isn't needed):**
Dynmap

**Comment by Zrips** [comment]
Will be fixed with next version
