### ISSUE TITLE
Scanning slows down after the last update. TPS is always shown as 0.00, resulting in only 1 scan speed

### ISSUE THREAD

**Issue by NeuTraLZero** [Zrips/CMI#4198]
**Description of issue:**
Scanning slows down after the last update. TPS is always shown as 0.00, resulting in only 1 scan speed

---
**Cmi Version (using`/cmi version`):** 
8.7.7.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper build 192
**Server Version (using `/ver`):** 
1.16.3

**Comment by Zrips** [comment]
Will be readjusting tps calculation with next version.
