### ISSUE TITLE
Scanning makes the scanned area not saved by the game at all

### ISSUE THREAD

**Issue by NeuTraLZero** [Zrips/CMI#4199]
**Description of issue:**
After scanning, all affected chunks that's been scanned will not be saved at all even after auto-saving or executing /save-all command. Restarting the server will return all the blocks to where it was before scanning

---
**Cmi Version (using`/cmi version`):** 
8.7.7.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.3 git-paper-195

**Comment by Zrips** [comment]
Could you elaborate on a command you used for this particular action? Did you replaced items in containers?

**Comment by ChiboYen** [comment]
Had this happen once, can confirm its present

**Comment by Zrips** [comment]
Should be fixed now
