### ISSUE TITLE
motd welcome message on player login broken

### ISSUE THREAD

**Issue by StrangerFive** [Zrips/CMI#42]
Hey, zrips, when you fixed the ctext auto alias, you broke the welcome message.  It won't print anymore when player logs in.  I'm talking about this line specifically in the config...

```
# Defines name of customtext on players login to server. To disable just set name to non existing customText
Motd: welcome

```

ctext file named welcome.txt used to print fine in 7.3.8.5, but doesn't print as of 7.3.9.0.

**Comment by StrangerFive** [comment]
Oh, and here's some more problems that need to be fixed...
1. If you do "cmi reload", then the welcome motd starts working (see above).
2. However, after a "cmi reload", all the ctext auto-aliases stop working.
3. After a full server restart, the welcome motd stops working, but all the ctext auto-aliases work as expected.

Eh, maybe I'll just stop using all these special features and do everything through custom aliases and commands.yml -- ugh.

**Comment by Zrips** [comment]
Should be fixed with next build
