### ISSUE TITLE
FirstSpawn Issue

### ISSUE THREAD

**Issue by DJKenzoDE** [Zrips/CMI#420]
i make a firstspawn for new users and i have checked the config and the config is okay but the new users spawn for 1/2 seconds and then teleport to another location or it spawn the new user direct to another location  (location=world) because the firstspawn and the another location are different worlds

cmi version: 7.7.8.2
server: spigot
version 1.12.2

**Comment by LogGits** [comment]
Do you have multiverse installed?

**Comment by DJKenzoDE** [comment]
yes i have multiverse installed

**Comment by LogGits** [comment]
You may have to /mv setspawn and also set the spawn world to the correct world in the multiverse config.yml 

`firstspawnworld: `
