### ISSUE TITLE
/pweather is broken and randomly locks to sunny weather

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#4205]
**Description of issue:**

A lot of players on all servers complained that arrows and mobs do not burn in sunlight. I was thinking that it was a paper/spigot bug until I got a complaint about lightning strikes in sunny weather. I started looking into it and discovered that somehow everybody including me had a personal weather set to `sun`. I'd given everybody a permission and adviced to run `/pweather reset`. The next day the problem reoccured (probably because of the daily server restart).

Not sure which version of CMI started to cause the problem with the personal weather, but it was discovered only a couple of days ago and we do frequent CMI upgrades.

---

**Cmi Version (using`/cmi version`):** 
8.7.7.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-185

**Comment by radiant-ai** [comment]
The problem still persists in 8.7.7.2, a lot of players complain that monsters are not burning in sun and bees are not flying. They just cannot see the true weather until they reset the personal weather.

**Comment by Zrips** [comment]
CMI only changes pweather if command is performed. Double checked code, and yes, only one place has code to change players weather, and its a command. So without triggering command poweather will not be set and in general, and pweather should be reset automatically by server after restart. So something else ether triggering pweather command or does its own weather set.

**Comment by radiant-ai** [comment]
Hello. I managed to track down the issue. It is really not a CMI issue. It was caused by a WorldGuard weather-lock flag set to clear. It was caused because the PlayerMoveEvent was disabled in WG config and thus WG failed to update players' weather. Sorry for bothering. But now you know what can cause such an issue if you get similar tickets.
