### ISSUE TITLE
Minecraft Version 1.16.3 is not supported 

### ISSUE THREAD

**Issue by RoselleNelson** [Zrips/CMI#4206]
**Description of issue:**
---
Minecraft Version 1.16.3 is not supported 
Server Logs: (Error occurred while enabling CMI v8.7.7.1 (Is it up to date?))

---

**Cmi Version (using`/cmi version`):** 
8.7.7.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-195

**Comment by NeuTraLZero** [comment]
I am running the same Paper build and encounter no issues running CMI

**Comment by CloudeLecaw** [comment]
We are running cmi 8.7.7.1on paper 1.13.2 Build 195. So your Problem must be somewhere else. Have you tried a clean cmi folder? And have you aspect that some servers thrown annerror on first eun of cmi? (but this is not disabling cmi...)

**Comment by Zrips** [comment]
@RoselleNelson 
We need actual error logs to know why it dint started up
