### ISSUE TITLE
When players vote offline they receive ALL RANKS rewards without permission

### ISSUE THREAD

**Issue by Frostified** [Zrips/CMI#4209]
**Description of issue:**
When players vote offline they receive ALL RANKS rewards without permission. In my config section below they receive ALL RANKS rewards even if they are a member rank without the permissions. Going offline tricks the system or something?

Voting while the player is online results in the correct rewards being given....

**CONFIG SECTION :**
Votifier:
   When set to true votifier votes will be counted for player
  CountVotes: true
   Number of votes one IP can make in last 24 hours
   Set it to 0 to have unlimited amount
  MaxVotesInADay: 0
   Cooldown between votes from same service
   In most cases voting service will have its own cooldown setup
   But if you need extra one to prevent rapid voting you can define time in seconds over here
  GeneralCooldown: 0
   When set to false, commands on sucessfull vote will not be performed
  PerformCommands: true
   Defines commands to be performed when player votes
   Supports specialized commands and placeholders
   [serviceName] variable can be used to insert address
  CommandsOnVote:
  - cmi broadcast !&5[playerDisplayName] &6just voted with /vote and got a diamonds,
    vote keys, and money!
  - cmi give [playerName] diamond
  - cmi money give [playerName] 2000
  - crate give to [playerName] VoteKey 1
  - perm:cmi.vote.dobule! cmi give [playerName] diamond 1
  - perm:cmi.vote.double! cmi money give [playerName] 2000
  - perm:cmi.vote.double! crate give to [playerName] VoteKey 1
  - perm:cmi.vote.double! cmi broadcast !&5[playerDisplayName] &6just got $2,000 and,
    1 extra key for being a donor(&5/support)
  - perm:cmi.vote.triple! cmi give [playerName] diamond 2
  - perm:cmi.vote.triple! cmi money give [playerName] 4000
  - perm:cmi.vote.triple! crate give to [playerName] VoteKey 2
  - perm:cmi.vote.triple! cmi broadcast !&5[playerDisplayName] &6just got $4,000 and,
    2 extra keys for being a donor(&5/support)
  - perm:cmi.vote.five! cmi give [playerName] diamond 4
  - perm:cmi.vote.five! cmi money give [playerName] 8000
  - perm:cmi.vote.five! crate give to [playerName] VoteKey 4
  - perm:cmi.vote.five! cmi broadcast !&5[playerDisplayName] &6just got $8,000 and,
    4 extra keys for being a donor(&5/support)
---

**Cmi Version (using`/cmi version`):** 
8.7.7.1

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.16.3

**Comment by Zrips** [comment]
issue is with inability to check if offline player have permission access. There is small bug related to this, but in general if you want to give out rewards by permission node while player is offline, this will not really be possible at this point. Some what solution would be to give out some generic reward in case player is offline while voting, which by itself would encourage players to log into server before voting. With next version you can use something like
```
  - cmi broadcast !&5[playerDisplayName] &6just voted with /vote and got a diamonds, vote keys, and money!
  - cmi give [playerName] diamond
  - cmi money give [playerName] 2000
  - crate give to [playerName] VoteKey 1
  - ifoffline:[playerName]! cmi give [playerName] diamond 1
  - ifoffline:[playerName]! cmi money give [playerName] 2000
  - ifoffline:[playerName]! crate give to [playerName] VoteKey 1
  - ifoffline:[playerName]! cmi broadcast !&5[playerDisplayName] &6just got $2,000 and, 1 extra key for being a donor(&5/support)
  - ifonline:[playerName]#!
.......
```
Where you would give 1 diamond and 2000 and vote key and broadcasted message when player is offline and in case he is, we would stop performing any following commands which requires from player to be online to be processed properly

**Comment by Frostified** [comment]
> issue is with inability to check if offline player have permission access. There is small bug related to this, but in general if you want to give out rewards by permission node while player is offline, this will not really be possible at this point. Some what solution would be to give out some generic reward in case player is offline while voting, which by itself would encourage players to log into server before voting. With next version you can use something like
> 
> ```
>   - cmi broadcast !&5[playerDisplayName] &6just voted with /vote and got a diamonds, vote keys, and money!
>   - cmi give [playerName] diamond
>   - cmi money give [playerName] 2000
>   - crate give to [playerName] VoteKey 1
>   - ifoffline:[playerName]! cmi give [playerName] diamond 1
>   - ifoffline:[playerName]! cmi money give [playerName] 2000
>   - ifoffline:[playerName]! crate give to [playerName] VoteKey 1
>   - ifoffline:[playerName]! cmi broadcast !&5[playerDisplayName] &6just got $2,000 and, 1 extra key for being a donor(&5/support)
>   - ifonline:[playerName]#!
> .......
> ```
> 
> Where you would give 1 diamond and 2000 and vote key and broadcasted message when player is offline and in case he is, we would stop performing any following commands which requires from player to be online to be processed properly

Its not that hard to check if a player is offline and cancel the vote event.  And that is possible, its quite easy to check if a player has a permission. The permissions are stored in a file, not on the user. I have many plugins that work with player permissions while they are offline. What your telling me is you dont have a solution, so im going to full disable your voting handling and get another plugin. I really shouldnt have to change my config, its as simple as checking if the player is offline and if so canceling it. I will be looking into other voting plugins.

**Comment by Frostified** [comment]
Fixed this problem by coding another plugin and disabling your voting handler. Thanks for all the help....
`    @EventHandler(priority=EventPriority.HIGHEST)
public void onVotifierEvent(VotifierEvent event){
           Vote vote = event.getVote();
           String username = vote.getUsername();
           String service = vote.getServiceName();
           Player player = Bukkit.getPlayer(username);
                if(player != null) {
                    if(!player.isOnline()) {
                          Bukkit.getLogger().log(Level.INFO, "[FrostyVotes] Service Error for {0}! The field {1} was invalid or the player wasn''t online!", new Object[]{service, username});
                          return;
                          }
                        }
                    else {
                      Bukkit.getLogger().log(Level.INFO, "[FrostyVotes] Service Error for {0}! The field {1} was invalid or the player wasn''t online!", new Object[]{service, username});
                      return;
                    }`
