### ISSUE TITLE
Toggle compass status doesn't save between server restarts

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#4211]
**Description of issue:**
/togglecompass status doesn't save between server restarts

---

---

**Cmi Version (using`/cmi version`):** 
8.7.7.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-196 (MC: 1.16.3)

**Comment by Zrips** [comment]
Will be fixed with next release
