### ISSUE TITLE
no Tabcompletation for unmute

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4213]
![Snag_11e34b70](https://user-images.githubusercontent.com/12080017/93262474-94b7eb80-f7a4-11ea-9e6e-48413632351d.png)

Like in thread allready CMI unmute command has no Tabcompletation

![Snag_11e45faf](https://user-images.githubusercontent.com/12080017/93262574-be711280-f7a4-11ea-877e-b5d99819d599.png)

**Comment by Zrips** [comment]
Not really a bug, more like missing feature, but will fix/add it with next update
