### ISSUE TITLE
Trying to disable magic and black fonts in color chat. 

### ISSUE THREAD

**Issue by FestusDM** [Zrips/CMI#4217]
**Question: **
Hi,

I've been trying to disable magic and color black for players but so far, nothing worked. I checked LP and 
`cmi.colors.publicmessage.black` and `cmi.colors.publicmessage.magic` are both set to false.

Is there something I'm doing wrong here? Or maybe something I'm missing? 
Thanks for the help.

**Comment by CloudeLecaw** [comment]
Check your permission file what step is done first with a file Editor. In most cases ppp habe all colorperma and try to negate after what will not work.
Check in the file that the Negation comes first. Dont use the webgui Editor for this because it listsnthe permission in an other order.

**Comment by Zrips** [comment]
@FestusDM 
In case player has access to wild card color permission node like cmi.colors.publicmessage.* then it will bypass other checks. If you want to limit some colors, then give out specific access to specific colors except black and magic

**Comment by FestusDM** [comment]
Will give that a shot, thanks!
