### ISSUE TITLE
Server TPS showing its fine with CMI commands but lagging with paper/spigot commands

### ISSUE THREAD

**Issue by 27chandler** [Zrips/CMI#4218]
**Question: **
Using CMI's /lag shows 20tps, but using /tps for paper or spigot instead shows a much lower number.
![image](https://user-images.githubusercontent.com/19729460/93405949-614d8d80-f886-11ea-8df6-eb493d11b272.png)
In the screenshot it shows at the top the cmi command's output, and at the bottom the spigot/paper one. I'm not sure why they are contradicting each other.

For reference, this is what CMI's /tps command shows.
![image](https://user-images.githubusercontent.com/19729460/93406033-98bc3a00-f886-11ea-8882-ea2583b72668.png)

**Comment by Zrips** [comment]
Which CMI version is this?

**Comment by 27chandler** [comment]
CMI 8.7.7.0
Paper 1.16.3

**Comment by Zrips** [comment]
Update to latest one, this was addressed in latest build
