### ISSUE TITLE
CMI preventing players from leaving sign text

### ISSUE THREAD

**Issue by doitliketyler** [Zrips/CMI#4223]
**Description of issue:**
I have a region that allows placement of wall signs which works except CMI is preventing players from leaving text on the sign. I've tested this thoroughly with just the 3 plugins installed.

**Cmi Version (using`/cmi version`):** 
8.7.7.2 Sqlite

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
1.16.3

**Relevant plugins (Delete if this isn't needed):**
Worldguard & WorldguardExtraFlags

**Comment by CloudeLecaw** [comment]
Try it without Worldguard and take a look if signs are still not editable. Also i recomment to give your players permission fir the right click feature for signs there in this region.

**Comment by Zrips** [comment]
@doitliketyler 
I need flag list you have set for this region you tested on or a walk throw how to setup test region which contains this issue.

**Comment by Zrips** [comment]
Tested out and with some basic setup, like allowing oak_sign placement and allowing use flag access, you can place sign with text without any issues. So something else is going on with your setup and we need to find out what exactly causing this one

**Comment by doitliketyler** [comment]
Ok. I tried use and no go but then I tried interact instead and I think that did the trick. I was under the impression that flag was only for levers and vehicles but I guess it means signs too? I still dont know why it worked without CMI enabled but at least it works...shrugs. I'll keep an eye on it but thanks for testing and at least pointing me in the right direction.
