### ISSUE TITLE
/setfirstspawn doesn't appear to work.

### ISSUE THREAD

**Issue by MrLogano** [Zrips/CMI#4224]
When setting the first spawn for new players joining the server, it doesn't appear to work, and instead spawns new players against the default world spawn. 

If I force players to the spawn upon joining the server, they first join at the default worldspawn (not first spawn) and are then moved to the point set with /setspawn.

Tried multiple times, by deleting player data, and then joining again as a "new player" with no change. 

---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.7.6.16 BungeeCord CMIB SqLite-> 8.7.7.2
Server: Paper(196) 1.16.3-R0.1-SNAPSHOT

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
git-Paper-196 (MC: 1.16.3)

**Comment by Zrips** [comment]
Have you tested this with CMI only to rule out any other plugin overriding first spawn point?

**Comment by MrLogano** [comment]
I have not yet tried it on it's own, but the server was running with only a small number of plugins, none of which affects spawning.

Plugins currently running:
Plugins (18): AdvancedHelp, BungeeTabListPlus, Citizens, CMI, CMIPaperLib, CoreProtect, DiscordSRV, EZRanksPro, HeadDatabase*, ImageOnMap, LuckPerms, PlaceholderAPI, ProtocolLib, TheNewEconomy, Vault, ViaBackwards, ViaVersion, VoidGenerator

**Comment by Zrips** [comment]
Could not reproduce this one. If you are still having this issue try opening new ticket, but try to test it out without any other plugin but CMI only.
