### ISSUE TITLE
colorpicker

### ISSUE THREAD

**Issue by SmajliceKsM** [Zrips/CMI#4225]
I tried colorpicker after a long time and I don't know if it's just me shift+click option that works. It used to be that I could add another color by clicking, now I have to write that code to be able to do more...

Video: (https://youtu.be/V9BtGgtWlM4)

**Cmi Version (using`/cmi version`):** 
8.7.7.2

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
Paper(197) 1.16.3-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Seams to be working as intended. Shift+left mouse click does add color code into chat without any issues. So no idea what exactly is going on in your situation.
