### ISSUE TITLE
Automatic flight recharge

### ISSUE THREAD

**Issue by EkonC** [Zrips/CMI#4226]
**Description of feature/improvement request:**

---
I would like to suggest an addition of a command that would automatically recharge flight charge.
### Detailed explanation of what it should do, when and in what situation: ###
When a player issues command /autorecharge (exp/money), their flight charge will be automatically recharged and they won't be sent to the ground (or void/lava) when their flight charge is depleted.
### Basic explanation as to why this feature is needed and/or useful to have: ###
Players can die when their flight charge is depleted and they don't realise it (in the End it may teleport them to void and in Nether to lava). It would also be more convenient for the players who don't want to recharge it every time.

**Comment by Zrips** [comment]
Should be up and running with next version
