### ISSUE TITLE
Selection Visualizer - No particles when selecting with the wooden axe

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#4227]
If you set pos1 and pos2 with the wooden axe in cuboid mode, the selection is not visualised by particles. If you set at least one of the points via command the visualisation works.

_SelectionVisualizer 3.0.2.3
Paper 1.16.3 build 198
FAWE 1.16 build 371_

**Comment by CloudeLecaw** [comment]
all fine the selectitem is wooden shovel not worldedits woodenexe. for have worldedit selection with woodenaxe you need a premium plugin like zrips selection virtualiser, but not its still not the cmi selection ;)

**Comment by CloudeLecaw** [comment]
hmm looks like u landet in the wrong github this plugin had its own section

**Comment by TheoRetisch1** [comment]
I would be happy about a fix, since setting the position with the wooden axe is the most frequently used feature :)

**Comment by TheoRetisch1** [comment]
Maybe this error is related to this is issue: https://pastebin.com/s1XZ4Nvv

**Comment by TheoRetisch1** [comment]
This is still an issue. Since setting the position with the wooden axe is the most frequently used feature it makes the plugin quite useless.

SelectionVisualizer 3.0.3.0
Paper 1.16.4 build 288
FAWE 1.16. build 446

**Comment by TheoRetisch1** [comment]
Confirmed for
SelectionVisualizer 3.0.3.1
Paper 1.16.4 build 318
FAWE 1.16. build 449

Since it is this feature most people use/want it would be awesome if you could push a fix. I bet it's a FAWE timing problem again xD

**Comment by CloudeLecaw** [comment]
With normal Worldedit it worka fine.
May u need to ask the Fawe dev for Support.
Pos1 and pos2 ahow me the selected particels with normal Worldedit seletion tool. We also use paper 1.16.4 Build 314 (so just 4 versions behind yours)

**Comment by TheoRetisch1** [comment]
Your recommendation certainly makes sense for a basic bug procedure. But at this particular issue it certainly doesn't lead to the desired result:
1. This a problem which is on the side of SelectionVisualizer and not FAWE. FAWE calculates new selections in the async mode, which can lead to a slight delay and is certainly the cause of the problem. Zrips has made several adjustments in the past to ensure compatibility with FAWE for exactly such problems and I hope he will do it again. The purpose of FAWE is not to perform asynchronous tasks in the same way as WE does, that is exactly the main difference between the two. Surely the compatibility commitment means an extra effort that Zrips has been making for years.
2. SelectionVisualizer is a premium ressource and nobody at FAWE will ensure compatibility with a resource that is not open source. This is a understandable procedure, which is also being followed by other plugins like Jobs Reborn.

So I am quite sure that I'm in the right place and I'm looking forward to a fix :)

**Comment by TheoRetisch1** [comment]
This is still an issue with FastAsyncWorldEdit version 1.16 build 474

**Comment by TheoRetisch1** [comment]
Confirmed for version 3.0.3.2!

**Comment by TheoRetisch1** [comment]
Confirmed for Paper 1.16.5 - 440 + Selection Visualizer 3.0.3.2 +  FAWE 578. Basic selections with the wooden axe are still not visualized.

**Comment by TheoRetisch1** [comment]
Unfortunatly the problem still exists for Paper-468 + Selection Visualizer 3.0.3.2 + FAWE 598. Basic selections with the wooden axe are still not visualized.

**Comment by Zrips** [comment]
Confirmed. Issue relates to the change how FAWE handles entire world edit mechanic and how its being recognized by entire minecraft system. Should be up and running properly with next update.
