### ISSUE TITLE
make [item] work for socialspy

### ISSUE THREAD

**Issue by MrMcyeet** [Zrips/CMI#4228]
**Description of feature/improvement request:**
When you have social spy enabled, and someone does [item] in a `/msg` it just says `[item]` and not the actual item

Not sure if this is a bug, or an oversight, or what lol, but IMHO it should be a thing

---
### Detailed explanation of what it should do, when and in what situation: ###
If craig did `/msg sarahcookie Look at this [item]`
Currently the socialspy message would just say `Look at this [item]` and not, for instance `Look at this [Dirt 41x]`

### Basic explanation as to why this feature is needed and/or useful to have: ###
Useful to see what players are `/msg`ing to eachother

**Comment by Zrips** [comment]
Good point, will fix this one, tho its not really a bug, just lack of feature
