### ISSUE TITLE
Feature /compact (EssentialsX)

### ISSUE THREAD

**Issue by Teyir** [Zrips/CMI#4229]
Hello,

EssentialsX has a very great feature: /compact

The /compact compact all my blocks in my inventory to a block.

If I have 256 Gold Ingot and I make /compact I lost my 256 gold ingot and I have 28 Gold_Block and 4 Gold_Ingot.

---
This is some screens

1: My inventory → https://prnt.sc/ukj7nk
1: When I make /compact → https://prnt.sc/ukj7zu

2: My intentory → https://prnt.sc/ukj8ap
2: When I make /compact → https://prnt.sc/ukj8fh

Thank you very much.

I think this is a great feature for CMI

**Comment by Zrips** [comment]
/condense /uncondense 
This will do what you want. 
Keep in mind that this will work on items which have a way to be compacted and expanded back, so things like melons might need extra custom recipe to be added, but general items like gold ingots will work out of the box.
