### ISSUE TITLE
CMI cancelling chat formatting

### ISSUE THREAD

**Issue by Korinocho** [Zrips/CMI#4231]
In the 8.7.7.2 version, cmi started blocking my chat formatting. After updating to 8.7.7.3 the problem is still there. I had and have all the CMI chat formatting disabled and it still happen. I can confirm that its CMI because if i disable it with my plugin manager plugin, this wont happen anymore.
---

**Cmi Version (using`/cmi version`):** 
8.7.7.3, with CMIB and MySql.
**Server Type (Spigot/Paperspigot/etc):** 
Paper 193 (1.16.3)
**Server Version (using `/ver`):** 
1.16.3
**Relevant plugins (Delete if this isn't needed):**
Chat plugin: Venturechat (same happening with ChatControl in a testlab)

**Comment by Korinocho** [comment]
And saying chat formatting i mean colors and &k, &r, and so...

**Comment by Zrips** [comment]
In 8.7.7.2+ i dint really did any changes related to color management. There was change previously relating to that tho. Try checking Chat->Colors->PublicMessage section and toggle it off. Other than this, it would be nice to know what exactly is going on in your situation. Does it colorize text when it should not or does it not colorize then when it should or does it strip down colors or something?

**Comment by Korinocho** [comment]
Yhea, sorry about that. It was not much info. Actually i have Colors>PublicMessage:false (never changed this). I write some color/format code (&2Test) for example and it will just add a space before the word and it will remain the color it was.
![image](https://user-images.githubusercontent.com/21372197/93779017-e0cbbb80-fbfc-11ea-9efb-86bb6a197e61.png)

**Comment by Zrips** [comment]
This looks more like a color code cleanup which can be found at Chat->Colors->CleanUp->publicmessage set it to false if you want to keep color codes intact in case player doesn't have access to them.

**Comment by Korinocho** [comment]
Its a problem that appears after 8.7.6.16. Tried changing versions and this problem appear with 8.7.7.0

**Comment by Korinocho** [comment]
Its still happening in 8.7.8.0. If i put CleanUp to true, it simply wont add any color and with false it will write literally "&2Test" in the chat. Even with OP. I dont know why it started interfering with the chat.

**Comment by Korinocho** [comment]
Looks like its solved in 8.7.8.2
