### ISSUE TITLE
Spawn when unjailed

### ISSUE THREAD

**Issue by Gayytis** [Zrips/CMI#4234]
**Description of feature/improvement request:**

Auto teleport to spawn or latest location after unjail

---
### Detailed explanation of what it should do, when and in what situation: ###

It would teleport the jailed player to the spawn when he got unjailed, after a certain amount of time or after being /unjail

### Basic explanation as to why this feature is needed and/or useful to have: ###

Bc player get stuck inside the cell, that's not very practical

**Comment by CloudeLecaw** [comment]
you can set the unjail teleport location llready. Set it to the place where your spawn is..done ;)

**Comment by Zrips** [comment]
@Gayytis 
As @CloudeLecaw pointed out you can already set unjail location. By default player will not be moved from cell so you need to set location outside cell or jail entirely for players to be teleported to after jail time expires.
