### ISSUE TITLE
Sleep speedup doesn't always work

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#4235]
**Description of issue:**
Sometimes when you get in a bed, it doesn't trigger the sleep speedup until you get out & back in

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
https://pastebin.com/DwMwPG1f
```

---

**Cmi Version (using`/cmi version`):** 
8.7.7.4
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-203 (1.16.3)

**Comment by Zrips** [comment]
Any way to consistently reproduce this issue? Tested with your configuration, cant reproduce issue at this point. How many players you had online in that particular world when this happen? I know you cant really know exact number, but some approximate number would be nice to have.

**Comment by Insprill** [comment]
At the time 3 players, it seems to happen though with at least 2. Its really intermittent when it happens so its a little tricky to reproduce.

**Comment by Insprill** [comment]
Sometimes it works every time: https://vimeo.com/464801208
And other times it takes multiple tries before anything happens: https://vimeo.com/464801396

That was done with 4 players online, 1 AFK.

CMI version 8.7.8.0
Paper-214 (1.16.3)

**Comment by Insprill** [comment]
@Zrips could you look into this issue? It happens so often. like I showed above it's really random when it happens, but it's almost "per night" as in some nights it doesn't work at all, others it works every time.

**Comment by Zrips** [comment]
Made some changes in last version, test it out and if you still experiencing this issue, let me know. Just make a new ticket.
