### ISSUE TITLE
Teleporting Bug

### ISSUE THREAD

**Issue by Ayon224** [Zrips/CMI#4236]
**Description of issue:**
When a player teleports it will not generate the chunks and they will only see black
and a message saying cannot send chat message
started when I moved to 1.16.3
**Cmi Version (using`/cmi version`):** 
8.7.7.4

**Server Type (Spigot/Paperspigot/etc):** 
paper

**Server Version (using `/ver`):** 
Paper 202 1.16.3

**Comment by Ayon224** [comment]
Only relogging will load the world and fix the problem

**Comment by Zrips** [comment]
Have you tested this with CMI only? Just to rule out possible issues from another plugin. As this doesn't look to be common issue as quite few runs same 1.16.3 but doesn't experience this issue of yours.

**Comment by ChiboYen** [comment]
Can confirm issue is present in 1.16.3, with no other plugins other than luckperms and CMI

**Comment by Momshroom** [comment]
Try updating paper.  The latest build reverted some changes in chunk loading.

**Comment by Zrips** [comment]
Should be working properly with latest builds
