### ISSUE TITLE
Format code replacement bug

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#4237]
**Description of issue:**
When a color code is devided by spaces, the second space is replaced/deleted
Example:
`&cBlah &b test` is converted into `Blah _ test` instead of `Blah _ _ test`
`&7&l   &r &eBlah &7&l   &r` is converted into `---Blah ---` instead of `--- Blah ---`
So {space}{colorcode}{space} is translated into  {space}{colorcode}
In order to get the desired formatting, it's needed to add another space: {space}{colorcode}{space}{space} which feels a bit odd.

---

---

**Cmi Version (using`/cmi version`):** 
8.7.7.4

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
1.16.3

**Comment by Volgeop** [comment]
For me colors don't work neither.... But I'm using chatcontrol for it, but when removing CMI, it normally works. Now it just replaces "&X" character, but doesn't color text.

**Comment by CloudeLecaw** [comment]
Have enabled it in config?

**Comment by Zrips** [comment]
Should be resolved with next build
