### ISSUE TITLE
Auto respawn is causing moving from blocks on SkyBlock, SkyGrid etc.

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4241]
**Description of issue:**

---
Hi, the problem is, that when I use permission for auto respawn, then there's spawned "hologram" or something like this on location where player spawns... and it moves player from 1 block to void.... For ex. I was discovering what's problem with SkyGrid, when player dies it teleports him above on block, but due to auto respawn it moves him 1 block father and player falls down... Same with SkyBlock etc.

---

**Cmi Version (using`/cmi version`):** 8.7.7.4

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** Paper 202, 1.16.3

**Comment by Volgeop** [comment]
Author of plugin fixed it somehow by changing teleportation coordinates, but I think that there shouldn't be interactable armor stand, that could move you after auto respawn.
