### ISSUE TITLE
World border stairs sit bug

### ISSUE THREAD

**Issue by OverBrave** [Zrips/CMI#4242]
https://streamable.com/cse7qi

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/47111280/94006384-6c358000-fda8-11ea-92ce-328fe78146e2.png)

**Comment by CloudeLecaw** [comment]
lol  why the haeck you have stairs on your worldborder? XD
its just normal that  the char may pass the worldborder with this buzt if your using a plugin like WorldBorder then u get knocked back (or get wapred spawn) when you stand up.
So i dont see this as a critical reason ;)

**Comment by OverBrave** [comment]
Thats it island border :D . But can't detect them. If CMI detect worldborder on near, it can be blocked.

**Comment by CloudeLecaw** [comment]
so this means cmi does not see the skyblock border?

**Comment by OverBrave** [comment]
ıhmm, i think yes.

**Comment by Zrips** [comment]
Should be fixed with next udpate

**Comment by OverBrave** [comment]
The problem has not been fixed.
