### ISSUE TITLE
playtime-/votetop commands show who is vanished by colouring players

### ISSUE THREAD

**Issue by Olexorus** [Zrips/CMI#4246]
**Description of issue:**

CMI's playtimetop and votetop commands show if a player in the list is online by showing the rank of the player if and only if they're online. This makes it possible for people to see when staff members are vanished (I'm using PremiumVanish, not the built in vanish).
Also imo the different colours don't look great in the list in general, even without this problem I'd really appreciate an option to disable this behaviour and just have every player in the list be the same colour without their rank shown.

---

**Cmi Version (using`/cmi version`):** 8.7.7.4 (latest as of writing this)

**Server Type (Spigot/Paperspigot/etc):** Paper 

**Server Version (using `/ver`):** git-Paper-204 (1.16.3, latest as of writing this)

**Relevant plugins (Delete if this isn't needed):** PremiumVanish, there are more plugins but I don't think any of them are relevant

**Comment by Zrips** [comment]
its not a bug in particular. What i mean is that in case player is offline we cant really update and get his display name which might require some placeholder updates or getting prefixes nick names and so on. So if player dint logged in then we will use general plain name/nickname and when player is online we will update that visual representation. Will do some changes and will start recording last display name into database so we can use that in all possible situations which will prevent from being recognized that you logged in and should properly always show your display name as it should be, more or less.
