### ISSUE TITLE
What did I do wrong here? it says [needed] instead of the cost

### ISSUE THREAD

**Issue by ylhs403-2019** [Zrips/CMI#4248]
**Question: **
What did I do wrong here? it says [needed] instead of the cost for /rankup
![d2](https://user-images.githubusercontent.com/58499863/94170802-5de97180-fe45-11ea-8c32-68e02d02fd18.PNG)

**Comment by CloudeLecaw** [comment]
What does your langfile sais?

**Comment by Zrips** [comment]
You have variable in a locale line which doesn't support that type of variable. If locale line doesn't have variable (exception might apply to global variables mentioned at top of file) then it will not be translated. That [needed] variable is specific for each criteria and there cant be one usage for all requirements. So yea, simply remove it.
