### ISSUE TITLE
Change how colour permissions work

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#4250]
**Description of feature/improvement request:**
Change the colour permissions so that one would be able to give someone cmi.colors.publicmessage.* and then set cmi.colors.publicmessage.red to false for that player, and they can then use any colour except for red. If you do this at the moment it will just ignore the false permission.

---
### Detailed explanation of what it should do, when and in what situation: ###
If a player has cmi.colors.publicmessage.* and has cmi.colors.publicmessage.red set to false, it should then allow the player to use all colours except for red.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Would be helpful if you wanted someone to have access to all colours but not access to italic or bold.

**Comment by CloudeLecaw** [comment]
First set to false, then give * check your Luckperms file for that with an Editor

**Comment by DrakePork** [comment]
Ah so negate before the main permission. Didn't know that. The red colour was just an example, I was more wondering around bold and italics and stuff.

**Comment by Zrips** [comment]
Will do some changes related to this permission handling, as this seams to be common misunderstanding.
