### ISSUE TITLE
Fly on world change bypass permission doesn't work, gamemode bypassing is needed

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4252]
**Description of issue:**

---
Hi, when I have set in config this:
```
  # If player will have cmi.worldlimit.gamemode.bypass permission node, game mode wont be changed
  # Possible modes: creative, survival, adventure, spectator, 
  Gamemode:
  - world:Survival
  - world_nether:Survival
  - world_the_end:Survival
  - MiningWorld:Survival
  # If player will have cmi.worldlimit.fly.bypass permission node, fly mode wont be changed
  Fly:
  - world:False
```
in world limits, I have to give players gamemode.bypass permission to stop disabling fly on world change... but it should be fly.bypass permission, no? When I tried this one, or when I tried set there Fly: [], it still didn't work. So, the solution should be that when I give them fly.bypass, then they should bypass it and normally can fly when they used fly command and when they change world... don't wanna give them gamemode bypass, cause it's risky.
```


**Cmi Version (using`/cmi version`):** 8.7.7.4

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** Paper 204 1.16.3

**Comment by Volgeop** [comment]
Did someone tried to test too?

**Comment by dalandis** [comment]
Hello. This still doesn't seem to work.
