### ISSUE TITLE
Death Respawn 

### ISSUE THREAD

**Issue by Karagra** [Zrips/CMI#4253]
Even with respawn, spawn and everything related by firstspawn set on death it is still respawning me at my first spawn location even while using another plugin to try to specify spawns and setting that plugin to take the highest priority.

---

RespawnLocation: false

---

8.7.7.4

Paper

1.16.3

https://www.spigotmc.org/resources/savagegraveyards.63050/

**Comment by Zrips** [comment]
Duplicated
