### ISSUE TITLE
[Bug] Going in god in/out of god mode in creative makes you take damage.

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#4255]
**Description of issue:**
By going into creative mode and toggling on and off your god mode you can then take damage and it will treat the god mode as regular survival fly. The specific damage I was taking in creative with god mode set to false after I toggled it was fire damage from lava.

---

**Cmi Version (using`/cmi version`):** https://paste.helpch.at/vupisizivi.md

**Server Type (Spigot/Paperspigot/etc):** Purpur, fork of PaperSpigot.

**Server Version (using `/ver`):** https://paste.helpch.at/piqodonawu.css

**Comment by Zrips** [comment]
Good catch, will issue with next update
