### ISSUE TITLE
[Question] A question about setting Motd in game without restarting in CMI.

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#4256]
**Question: **
Is there a way I can make the motd not get "cut" or "shortened" when I try to add extra spaces using the ingame set motd command. 

Currently it cuts the motd off and it ends up being put to the left of the screen in the server list when I try to have it in the middle or something.

**Comment by Zrips** [comment]
Not with current build, but this is good point, will add option where you can create spaces by using _ so "_ _ _ _ _ Server 1.16.3" will result into "          Server 1.16.3" Minecraft filters out extra spaces by default, so we cant really use input with bunch of spaces, so underscore will be the solution. Just keep in mind that __ results into actual _ so you need space after each _ to get desired result
