### ISSUE TITLE
CMI Feature Questions

### ISSUE THREAD

**Issue by FestusDM** [Zrips/CMI#4257]
**Question: **
Just curious about these...

1. Does CMI have something where I type a word then it turns into another word inside public chat?
2. Does CMI keep a record of all tempbans and bans? If so, where would I find that?

**Comment by Zrips** [comment]
1. Chat filter is built in, in case you want to censor particular words.
2. CMI doesn't store bans, it only uses Minecraft ban system itself, so no records about previous bans. We do keep track of warnings player got.
