### ISSUE TITLE
-s for vanish command

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4259]
sometimes it can be usefull if you vanish or unvanish other if this would have a -s option
The targe should get no feedback in that case

**Comment by Zrips** [comment]
But target already doesn't get feedback message if some one else changed his vanish mode

**Comment by CloudeLecaw** [comment]
> But target already doesn't get feedback message if some one else changed his vanish mode

good to know^^

What about the Bossbar if used normaly?..
When vanished this once sais in bossbar "Vanished"  So the target definatly notice
