### ISSUE TITLE
Bug with beds

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#426]
**Description of issue or feature request:**
Destroying/left-clicking a bed sets the users CMI home. This should be changed so that CMI homes are only set when interacting with beds.
**Cmi Version (using`/cmi version`):** 
7.7.9.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.12.2 (Build #1427)

**Comment by TheWranger** [comment]
CMI will also set the home even if the bed is in the nether and would normally explode.

**Comment by Zrips** [comment]
With next update it should be fixed.
