### ISSUE TITLE
Using an anvil (not /anvil) on an item with a repaircost of 40 or more forces creative mode when combining.

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#4264]
**Description of issue:**

When you use an anvil (not the /anvil command) to combined to swords, the player is put into the creative mode with unlimited levels. When you exit the anvil GUI, the player is returned to survival mode.

This does not happen with the /anvil command.
---

---

**Cmi Version (using`/cmi version`):** 8.7.8.0

**Server Type (Spigot/Paperspigot/etc):** paper-206

**Server Version (using `/ver`):** 
CMI: 8.7.8.0 MySQL
Server: Paper(206) 1.16.3-R0.1-SNAPSHOT
CMI economy: True Vault: 1.7.3-b CMI Chat: True 
Modules -> 51 enabled 0 disabled:

**Comment by CloudeLecaw** [comment]
this bug seems not to come from CMI. we also use all anvils normal and use swords on the anvil to repair them. there is no reason for CM to put you in creative mode... have you made sure its cmi that is causing this?

**Comment by CypherPhyre** [comment]
This has been tested with just CMI installed. This happens with any item that has a repair cost of 40 or more set.

**Comment by CloudeLecaw** [comment]
cant reprocude is, so we might need to wait about any hint of maybe Zrips :(
sorry cant help there

**Comment by CypherPhyre** [comment]
This is still an issue after updating to
Paper-214 and CMI 8.7.8.1

CMI: 8.7.8.1 MySQL-> 8.7.8.0
Server: Paper(214) 1.16.3-R0.1-SNAPSHOT
CMI economy: True Vault: 1.7.3-b CMI Chat: True 
Modules -> 51 enabled 0 disabled:

**Comment by Zrips** [comment]
Unlimited mode got disabled due to similar issues relating to it. To many variables are at play for this feature to work without causing more issues then it would resolve in general.
