### ISSUE TITLE
Bypass BaseDropChance from spawners or ideally permission like basedropchance.X

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4265]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, could you please add way to BaseDropChance from mining spawners? It could work like when you have two worlds - one for mining and one for normal game, then there we can set by permission in which world will be chance bypassed (or permission to set specific change to specific worlds) and in which will be for ex. just 3%. Because I wanna in my mining world to drop chance 3%, but in my main 100%, because when they will place it in main world and they wanna to move it, they can loose it even if they got spawner from special crate.

### Basic explanation as to why this feature is needed and/or useful to have: ###
To solve issue mentioned up. I need to prevent big amount of spawner dropping in mining world, and way to drop all spawners placed by players on 100% in main world.

**Comment by Volgeop** [comment]
But the best solution will be if you add way to set specific percentage via permission... to let also different % for different ranks.

**Comment by Volgeop** [comment]
Hi @Zrips , what do you think about it please? I don't know now how to solve it without this...

**Comment by Volgeop** [comment]
Hi @Zrips , what do you think about it please? I don't know now how to solve it without this...

**Comment by Zrips** [comment]
Will get added with next upadte
