### ISSUE TITLE
How to move the player database

### ISSUE THREAD

**Issue by TopPyEiEi** [Zrips/CMI#4267]
**Question: **
I changed the version of "CMI" from the old version to the new "CMI". How can I migrate the player database?

**Comment by CloudeLecaw** [comment]
> **Question: **
> I changed the version of "CMI" from the old version to the new "CMI". How can I migrate the player database?
what kind of "old version" u used before? - a bit more detail would be helüfull
Normally u dont need an extra migration process here so there is no migration for that.
if you updated from old CheckMyInventory to ContentManagementInterface  then the amount of before saved data would be really really small. i dont recomment this kind of migration.

When allready used ContentManagementInterface and your database is not currupted then all should work in todays database too. If you used mysql before - use same mysqldatabase, if you used the sqlite before copy the old file over the new (while server is offline)

**Comment by CloudeLecaw** [comment]
you also can import the playerdatas from your worldfolder with
`cmi importoldusers -> Imports users from playerdata folder in main world folder. Server can suffer lag spike during import`
but this does not import data from old cmi to new cmi :3
