### ISSUE TITLE
Spawn /cmi tree with bee nest?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#4268]
Is it possible to force the 1.16.3 engine to spawn a tree With the bee nest in it? They are super sporadic, but it would be nice to get them with a guarantee.

**Comment by CloudeLecaw** [comment]
yes a optional bee argument would be nice xD
 /cmi tree (treetype) (small|normal|large|wild) (beenest)

small - a small tree
normal - the normal size
large - the big 2x2 trees
wild - only some trees like oak can have this

![image](https://user-images.githubusercontent.com/12080017/94430865-d9745700-0194-11eb-9da7-aa91590cf01c.png)
the picture shows two wild oak trees. u see they are much bigger then usal oak trees

you can force the build of them by placing 2 stacked walls next to a sappling and fire a bunch of bonemeal on it (or simply wait) they need longer then the normal tree to grow.
![image](https://user-images.githubusercontent.com/12080017/94431266-569fcc00-0195-11eb-9d1a-5c6f51273321.png)
