### ISSUE TITLE
Donate items amount message bug

### ISSUE THREAD

**Issue by EkonC** [Zrips/CMI#4272]
**Description of issue:**
When I sent a donation of 64 spruce logs to a player and he accepted it, in the chat it wrote down that I donated Spruce LogX11. The amount of logs in the players inventory before the donation was 11. Player got all 64 logs.
![2020-09-27_14 36 24](https://user-images.githubusercontent.com/62595403/94365296-f004aa80-00cf-11eb-9d51-e28aee28d5b7.png)
Similar message was delivered to the player as well.
![unknown](https://user-images.githubusercontent.com/62595403/94365374-b5e7d880-00d0-11eb-95d2-ec1932cd9fef.png)

**Cmi Version (using`/cmi version`):** 
8.7.8.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper 189, MC 1.16.2

**Comment by EkonC** [comment]
It happened more times when the player already had some amount of the donated item in the inventory

**Comment by Zrips** [comment]
Should be in working order with latest builds
