### ISSUE TITLE
scan seems not work corrlcy

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4274]
i tried to search for netherite_chestplate in a radius of 200

1. All result where just container with written books in it
2. The scan result seems to be over 2000 blocks instead of 200... why?

![image](https://user-images.githubusercontent.com/12080017/94371618-20603f00-00f8-11eb-93e0-63df883cfa06.png)

Description of Scan in wiki..
>Scans defined range or entire map for particular items in all possible containers.
>
> SubCommands:
>     – stats – show current scanning stats
>     – pause – pause scanning
>     – continue – continue scanning
>     – stop – stop scanning
>     – stopall – stops all active scannings
>     – speed [amount] – set current scan speed
>     – autospeed [true/false] – set autospeed turned off or on
>     – messages [true/false] – set message output to off or on
>     Variables:
>     id [id:data]
>     q [minimum quantity]
>     r [range in chunks] – option to use g instead of number to scan entire map
>     n [item name]
>     l [item lore]
>     h uses info from item in hand
>     e [enchantname]
>     elvl [enchantminlevel]
>     oversize
>     purge – removed found items, this feature should be enabled in config file
>    
> 
> Example:
>     /scan id 52 r 30
>     /scan id diamond_block r g q 32

**Comment by Zrips** [comment]
Material detection should be working correctly now, tho you looked by item name and not by material type in your example. For scan range. At some point (100 chunks) it switches to global scan by default as that one is more efficient when it comes to bigger area search as it can skip faster regions which doesn't contain any generated chunks in it, while using range forces script to go in spiral pattern through all chunks and check if chunk is generated or not.
