### ISSUE TITLE
Extra Voting Rewards Issue

### ISSUE THREAD

**Issue by FestusDM** [Zrips/CMI#4275]
**Question: **
Players have reported that they are not getting the extra voting rewards due to full inventory. Is it supposed to give players the rewards anyways, even if they got a full inventory?

**Comment by CloudeLecaw** [comment]
I think no, finally the reward is a command, when inventory is full it get response that inventory was full or it drops item infront of them. There is no quene for this. A solution would may be to give them access to a special kit an the access gets removed when they take the kit. You could design a customalias that give them all kits where they have access to. Also its possible to add onetime kits that stucks in the amount of useage if they take it once. So if they vote for 6 sites they can take the kit also 6 times.
Well this is just a suggestion but does not prevent them from not getting a reward item if the inventory is full allready.
