### ISSUE TITLE
Loosing rank on server change

### ISSUE THREAD

**Issue by titidelaff** [Zrips/CMI#4281]
**Description of issue:**
I have a problem with rank system over 2 servers.
On my first server, player rankup, if he join second server he loose rank on both server.

![image](https://user-images.githubusercontent.com/23405363/94407280-91910800-0173-11eb-9e76-edf36da9e41c.png)

**Comment by Zrips** [comment]
Ranks are not synched across multiple bungee servers. Same thing applies for more or less everything else.
