### ISSUE TITLE
gradiant coloring for user permissions

### ISSUE THREAD

**Issue by Scorpionvssub** [Zrips/CMI#4287]
**Question: **
I have given the ability for players to change their names, even so far as using <hex>(name)

But when trying to allow the gradiant version that doesnt work except for ops(or those with *)

Which permission is used for the gradiant? again they can change color but not gradiant.

**Comment by CloudeLecaw** [comment]
Use behind the permission  .hex

**Comment by Scorpionvssub** [comment]
Thats the thing, they have .* but gradient wont be allowed, so i dont think you get my meaning :P they can use /nick }{#00000} but not the {#0000>....version

**Comment by CloudeLecaw** [comment]
you mean they cant do this?

`cmi nick {#red>}Clou#green<>}_Lec{#blue<}aw Cloude_Lecaw`

**Comment by Scorpionvssub** [comment]
nick {#carribean_green>}Name Here{#blue_charcoal<}

yea

**Comment by CloudeLecaw** [comment]
Changes player name

To change into different nick name: cmi.command.nick.different This allows to change name by only changing its colors but not actual name itself.

**Comment by Scorpionvssub** [comment]
they have the different permission... they have the colorpermission they have all permissions i could find related to coloring that made sense to have. they have the length too... so something else is clearly missing

**Comment by CloudeLecaw** [comment]
give me a secound i check it out for u

**Comment by Scorpionvssub** [comment]
Think i need to categorize all perms since players are allowed to change to any name using any color version but cmi is overly complicated wiki doesnt help here either

**Comment by CloudeLecaw** [comment]
I agree the wiki sometimes seems to be outdated

**Comment by Scorpionvssub** [comment]
which perms do you use all together for the average user to nickname themselves including ALL color combo's, see where mine may differ ifyou say yours work

**Comment by CloudeLecaw** [comment]
i got the anser we searched for nick^^

but see self

![Snag_50ef48b](https://user-images.githubusercontent.com/12080017/94595722-7c0f0180-028b-11eb-8959-d83c3e6c5d60.png)

**Comment by Scorpionvssub** [comment]
thats a pain in the ass to do it like that...

**Comment by CloudeLecaw** [comment]
what i ment is you can use cmi.colors.nickname.*  not  cmi.colors.nick,* does not exist

**Comment by Scorpionvssub** [comment]
Thanks ill try them later 👍

**Comment by Scorpionvssub** [comment]
Thanks pal, that worked! it wont allow the names for people but it will allow the #00... color stuff + > etc

**Comment by CloudeLecaw** [comment]
i also noticed that these names often not work. so best choice is mostly using the #colorcodes
allow them to use /cmi colorpicker
with SIFT + Click they can paste the #Colorcodes into chat.
![Snag_5bedce4](https://user-images.githubusercontent.com/12080017/94614348-53483580-02a6-11eb-855b-4787a198995c.png)
permission is cmi.command.colorpicker command is /cmi colorpicker    (may u write a nice customalias for this)

**Comment by Scorpionvssub** [comment]
yea seems names have an unnamed perm or something idk haha, maybe a  bug idk.

![image](https://user-images.githubusercontent.com/12249763/94614651-cbaef680-02a6-11eb-9745-184b183d29ba.png)
but got it hahaha
