### ISSUE TITLE
Findbiome teleports above nether roof

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4288]
**Description of issue:**

---
Hi, the problem is that Findbiome command teleports above nether roof, when I use there nether biome.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Even if this is set to true, findbiome teleports above nether roof...
```
  # Will teleport players down from nether 'roof'
  PreventPlayersOnNetherRoof: true
```

---
---

**Cmi Version (using`/cmi version`):** 8.7.8.0

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** Paper 204, 1.16.3

**Comment by CloudeLecaw** [comment]
What the problem with it? As player you dont have the permission for this. So allnfone here. If a player reaches the roof he gets teleported to the next free space under it. So whats your Problem with this? As admin the nether is 256 high and you can be and build over 128 so all fine.

**Comment by Volgeop** [comment]
The problem is that I allowed it to vip players, bit it teleports them above nether and won't teleport them down then. I want normally to teleport them down to the book, not on nether roof

**Comment by CloudeLecaw** [comment]
Is this option set to true?

>   PreventPlayersOnNetherRoof: true

**Comment by Volgeop** [comment]
Yes, as I mentioned on the beginning of issue, I have set this to true.

**Comment by CloudeLecaw** [comment]
so how should you thing this should be solved without interrupping in the current way for others where it teleports then to next free place unter the roof..

hm what a bout a height/location setting
so suggestion:

```
  # Will teleport players down from nether 'roof'
  PreventPlayersOnNetherRoof: false
  #Wenn players teleported down from nether roof then CMI tries to teleport to next found save place at the defined height (Y)
  # value can be loc:(X:Y:Z:world)  or height:(0-256), loc teleport to speciffic location. if world is not set current world will be taken.
  #high tries to teleport player to next save layer at defined height in nether
    TeleportToSpeciffic: height:125
```

Default value would be height:125 to suit to the current "old" behavior that most servers use and have at the moment.
