### ISSUE TITLE
Error occurred while enabling CMI v8.7.8.0 (Is it up to date?)

### ISSUE THREAD

**Issue by Sayyah2000** [Zrips/CMI#4289]
**Question: **
Hello people I bought the cmi plugin yesterday but eveytime i lunch my server  get this error : Error occurred while enabling CMI v8.7.8.0 (Is it up to date?) everything loads up execpt cmi plugin I deleted cmi files and delete jar files but It did not help me
![Capture](https://user-images.githubusercontent.com/72106167/94613640-2d6e6100-02a5-11eb-82d4-60fec03b81c0.PNG)

**Comment by CloudeLecaw** [comment]
Do you use the Paperclib Add that is needed for paper?

**Comment by Sayyah2000** [comment]
> Do you use the Paperclib Add that is needed for paper?
> ![image](https://user-images.githubusercontent.com/12080017/94615306-d61dc000-02a7-11eb-8cf3-f988e8676d8f.png)
> Whatch for the jar inside cmi\Libs
> 
> This Add is needed for PaperSpigot
> i dont know if it comes directly with cmi^^

Yes I do have that
![Capture](https://user-images.githubusercontent.com/72106167/94615546-3f053800-02a8-11eb-9135-579be33bb275.PNG)

**Comment by CloudeLecaw** [comment]
does this appear every start it was notmal that this happens on first start with PaperMC

**Comment by Sayyah2000** [comment]
Yes it comes sadly back I restart it many times and I deleted the cmipaper but the error comes back

**Comment by CloudeLecaw** [comment]
hmm also with 8.7.7.4?

im asking because in the patchnotes there was something writen that he changed the behave from the cmipaperlib on first start. may this fix broke something when its not fully implemnted..

`Small fix related to first startup which could have produced one-time error while copying over cmipaperlib file`

**Comment by Sayyah2000** [comment]
yes it shows the same message with 8.7.7.4 version 
![Capture](https://user-images.githubusercontent.com/72106167/94617106-7c1dfa00-02a9-11eb-8bf4-ebedb07b8b36.PNG)

**Comment by CloudeLecaw** [comment]
https://hastebin.com/atipadagic.md

**Comment by Sayyah2000** [comment]
its wierd man... these are my plugin btw can it be my plugins that stop the cmi to load maybe? 
![Capture](https://user-images.githubusercontent.com/72106167/94617526-ff3f5000-02a9-11eb-9b04-be4af98146b9.PNG)
![Capture2](https://user-images.githubusercontent.com/72106167/94617528-ffd7e680-02a9-11eb-8c9b-beea4ece8ed1.PNG)

**Comment by CloudeLecaw** [comment]
Could you do a test?
Setup a Testserver with Just CMI + your Permission system (nothing else)
just to make sure its not an other plugin that is interacting here

**Comment by Sayyah2000** [comment]
https://hastebin.com/ukipelavav.md

**Comment by CloudeLecaw** [comment]
Did i see this right?
you use a PerWorldPluginLoader?   Myles.PWP.TransparentListeners.PerWorldPluginLoader.

aggain....
Could you do a test?
Setup a Testserver with Just CMI + your Permission system (nothing else)
just to make sure its not an other plugin that is interacting here

Also the latest log would be nice there to see if there are issues on loading
i recommand hastebin for this https://hastebin.com/ (because it looks nicer then pastebin^^)

**Comment by CloudeLecaw** [comment]
Or at least try WITHOUT the PerWorldPlugins v1.2.4
this plugin i also tried and is caused more issues then uses with most of our plugings

**Comment by Sayyah2000** [comment]
yes am gonna try without wait a sec

**Comment by Sayyah2000** [comment]
oh it works now ! thank u♥

**Comment by Sayyah2000** [comment]
https://hastebin.com/aduzegerod.md

**Comment by CloudeLecaw** [comment]
jep that what i thought, i also run in this issues when i tested arround with https://dev.bukkit.org/projects/perworldplugins  and also with https://www.spigotmc.org/resources/perworldplugin.65089/

vut CMI was not the only one that was causing issues with them :3

**Comment by Sayyah2000** [comment]
yeah feels bad now i cant use perworld plugin

**Comment by CloudeLecaw** [comment]
totday most is handles by permisisons by world and nealry all permission plugins can do this. i hope the lost of this over 5 years not maintained plugin is not to hard for you

**Comment by Sayyah2000** [comment]
thanks man !
