### ISSUE TITLE
RGB colors after updating the plugin to 8.7.8.0 from 8.7.7.4 don`t work

### ISSUE THREAD

**Issue by levarar** [Zrips/CMI#4290]
After updating the plugin to 8.7.8.0 from 8.7.7.4, RGB stopped working in chat, I tried it with my config and with the config generated by the plugin itself, rgb does not work.
Chat plugin - Chatty
The RGB works on signs, holograms, announcements, but not chat

---
config:
![image](https://user-images.githubusercontent.com/68510813/94641860-1c484300-02eb-11eb-8cc2-50d1335db0fb.png)

**Cmi Version (using`/cmi version`):**  8.7.8.0

**Server Type (Spigot/Paperspigot/etc):**  Tuinity

**Server Version (using `/ver`):** 1.16.3

**Relevant plugins (Delete if this isn't needed):** 
![image](https://user-images.githubusercontent.com/68510813/94641772-d3908a00-02ea-11eb-97ea-b3fb8d117df1.png)

**Comment by mercurialmusic** [comment]
I've been trying to figure out what I was doing wrong with this, too, and I'm not sure that it's not me, but I'm struggling with similar. I use VentureChat and the modify chat remains false. Legacy color codes and **single** hex codes work fine, but gradients are completely messed, letters end up with a bunch of brackets in the middle, like: t{}e{}s{}t.

On git-Paper-207 (MC: 1.16.3) with CMI 8.7.8.0 and CMIB1.0.0.4.

**Comment by ZEROOblivious** [comment]
> 
> 
> I've been trying to figure out what I was doing wrong with this, too, and I'm not sure that it's not me, but I'm struggling with similar. I use VentureChat and the modify chat remains false. Legacy color codes and **single** hex codes work fine, but gradients are completely messed, letters end up with a bunch of brackets in the middle, like: t{}e{}s{}t.
> 
> On git-Paper-207 (MC: 1.16.3) with CMI 8.7.8.0 and CMIB1.0.0.4.


This is also happening on my server. Gradients are not working in chat, but they work in Broadcast/Holograms/Etc. 
![image](https://user-images.githubusercontent.com/32251194/94727474-c85e4e00-032c-11eb-803a-103fdac25ebf.png)

**Comment by ZEROOblivious** [comment]
The Example Gradients in https://www.zrips.net/cmi/hex-colors/
Use to work before update.

Now it does this: (Ive put it in broadcast to show Gradients work in other ways)
![image](https://user-images.githubusercontent.com/32251194/94727535-df9d3b80-032c-11eb-93ca-da68c5ff02f2.png)

**Comment by Zrips** [comment]
Should be working properly with next build

**Comment by mercurialmusic** [comment]
Yes! Thank you!
