### ISSUE TITLE
API Colorpicker system

### ISSUE THREAD

**Issue by Scorpionvssub** [Zrips/CMI#4292]
**Description of feature/improvement request:**
I'm unsure if this is already possible, but seeing the wiki on api sections there seems to be no real easy way to hook into the colorpicker system.
---
### Detailed explanation of what it should do, when and in what situation: ###
For example:
While cmi has "prefix" and other settings i'd like my own plugin to be able to hook into cmi when i wanna create a custom prefix or other text and simply push <#color><text><#color> to get a gradient version returned by cmi.

### Basic explanation as to why this feature is needed and/or useful to have: ###
While this is but 1 request for api extensions, allowing more api features to the public would make this plugin be much more useful and supported by a majority of existing plugins that currently cant or refuse to do so.

**Comment by Gilmee** [comment]
Aren't you just describing the /colorpicker command that is already in CMI? Info on it found here https://www.zrips.net/cmi/hex-colors/ All you have to do is click the colour you want and it adds it into the text bar.

**Comment by Zrips** [comment]
@Scorpionvssub 
If you want for CMI to process hex color codes then simply do 
```
String translated = CMIChatColor.translate("{#cancan}text");
String translated = CMIChatColor.translate("{#cancan>}text{#red<}");
```
Simple as that. Other than this, i have no idea what you mean by color picker.

**Comment by Scorpionvssub** [comment]
Curious cause utils.CMIChatcolor throws ClassNotFoundException when trying to use it ingame.

But yea, i ment exactly that

**Comment by Zrips** [comment]
@Scorpionvssub 
If you are using github repo, that will not work, its terribly outdated and CMIChatColor was moved to its own class with complete rework how it works and similar. If you want to use it and get correct paths, you might need to add CMI ad a library for time being until API repo is updated properly. Tho its not that easy to do for 4MB plugin without actually exposing actual code of plugin
