### ISSUE TITLE
Random Teleportation Event

### ISSUE THREAD

**Issue by istarengwa** [Zrips/CMI#4293]
**Description of issue:**
Hello, when players do "/rt" random teleportation works correctly, but i put rt in first server login and death events, and it shows me 100% of cases that the teleport location is not on. I even try to set the "cmi.safeteleport" permission to players, but it doesn't work.

**Cmi Version (using`/cmi version`):**  8.7.8.0

**Server Type (Spigot/Paperspigot/etc):** Purpur-747

**Server Version (using `/ver`):**  1.16.2

**Comment by Zrips** [comment]
You need to have some delay before trying to teleport player when he tries to log into game or after his death. You can delay commands by adding 
- delay! 5
to delay commands by 5 seconds
