### ISSUE TITLE
Scavenge/salvage anvil enchanting

### ISSUE THREAD

**Issue by EkonC** [Zrips/CMI#4295]
**Description of issue:**
---
Command **/scavenge** or /salvage doesn't remove certain nbt from sword. This command only removes enchants but as you know, enchanting in anvil gets more and more expensive over time. When you salvage/scavenge the item, **the cost of anvil enchanting is still the same as before,** even with no enchantments, so players can't enchant their scavenged items over again because it's too expensive.

**Cmi Version (using`/cmi version`):** 
8.7.8.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.2 (Paper 189)

**Comment by Zrips** [comment]
Good point, will update code to take into consideration this. next update
