### ISSUE TITLE
Error with DiscordSRV

### ISSUE THREAD

**Issue by AbhayRojas** [Zrips/CMI#4296]
**Description of issue:**
Hello, I got an error with the DiscordSRV and it looks like is related to CMI

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://paste.gg/p/anonymous/f050a982e39148748c4efc4d74377333
```
---

**Cmi Version (using`/cmi version`):** 
8.7.8.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
git-Paper-204 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
https://www.spigotmc.org/resources/discordsrv.18494/

**Comment by CloudeLecaw** [comment]
On our Server we went back to 1.91.1 because 1.20 of disord is causing many issues and erors on our server too.

**Comment by Zrips** [comment]
Should have been resolved with latest discordsrv builds
