### ISSUE TITLE
[Bug] Kit limits are being wacky.

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#4298]
**Description of issue:**
I'm not sure when this started since we typically use our kits to facilitate rewards or game mechanics and don't often use the cooldown or limit system, but somewhere along the way all of the kit cooldowns and usage limits have become entirely global across all of the players. So if I want everyone to be able to get a kit one time each, we're not currently able to since if the kit has a limit of one it will now only be given to one player and no more. This is only true when the players are running the commands themselves (when they have permission of course) -- I am still able to give it to them manually using the command. There is otherwise no feedback message being sent.

Similar is true for the cooldowns, they also seem to be global, although players are at least getting a feedback message saying they can't use it for another couple minutes or whatever (even though they hadn't used it, someone else had a few minutes prior).

Only found out tonight since it's our 4 year anniversary and none of the kits were working!

**ERROR:** No errors shown, unfortunately.

**Cmi Version (using`/cmi version`):** 8.7.8.0

**Server Type (Spigot/Paperspigot/etc):** Paper/Waterfall

**Server Version (using `/ver`):** git-Paper-207 (MC: 1.16.3) (I'm 2 versions behind, will update tomorrow)

**Comment by Zrips** [comment]
Kit usage amount cant really be shared across multiple users as its directly dependent on users object. After going through code it could only be issue with another plugin improperly setting players kit usage times while using same object for others and creating this issue. Will make some changes to avoid issues like this in future. If that doesnt resolve your issue, please let me know.

**Comment by mercurialmusic** [comment]
Thanks for looking into this! Seems to be fixed now, but out of curiosity, what else might have altered that? Is it a scoreboard thing or would it be something that directly alters the CMI database? I don't know of anything else that might do the latter -- which makes me a little nervous.
