### ISSUE TITLE
[feature request] jail command

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#43]
I would also love to a see a jail-command like the one you can find in essentialsX. It should supends players activities and teleport them. Basically its the cuff-command combined with a teleport to a location. We never ban people but send them into a jail where the can ban themself using an electric chair. Unfortunatly a jail-function is very hard to accomplish with CMI at the moment.

**Comment by LogGits** [comment]
So you want the player to loose all abilities to interact with blocks and chat. The user would get teleported to a defined jail location and when there unjailed they are teleported to spawn?

So similar to essentials, would such a feature be reliant on the server owner/admins to ensure that the jailed user cant get out of the jail?

**Comment by Ew9304** [comment]
Yes please add this feature with the command "/cmi jail playername <time>" where it will put him in jail at the default jail location set by "/cmi setjail" and when his sentence is up he will be teleported to the location defined with "/cmi setunjail" 

Please don't make it neccessary to type the jail name in the command, I only use 1 jail. 

All commands should be disabled, except for the ones added to a whitelist, such as /helpop

**Comment by 2beFlo** [comment]
Hey there, 
the jail-system is the only thing that we do miss after changing from essentials to CMI.

As far as the functionality goes @Ew9304 has said it all. There are (one ore more) defined places where the player is ported. He losses the option to leave that place with commands like /home /spawn or /tp(a). Furthermor - as far as essentials goes - the player is able to move within the location (Cell in a Jail e.g.).

-F

**Comment by digitalcrowd** [comment]
I was going to make the same /jail request. I would only add there needs to be a time-limit of like 3h or 1m or 5d, or whatever and players in jail would know how long they have left in jail when they try to issue commands that they no longer have access too. It should allow servers to set what commands players have access too while in jail.

**Comment by LogGits** [comment]
The latest updates have introduced a new jailing system with cells etc. Great suggestion guys, thanks a tonne!
