### ISSUE TITLE
when no staff are online and someone uses /helpop send a message saying no staff are online and to post on the discord.

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#4302]
Can you have a check for if a player uses `/helpop` and no staff are online? And to simply give them a message that we can customize in the languages file.
This way I can set the message to tell them to use our discord as there are no staff online.

**Comment by Insprill** [comment]
Already exists as pointed out by @CloudeLecaw. It's in the lang file.

**Comment by TomLewis** [comment]
Found it.
