### ISSUE TITLE
when no staff are online and someone uses /helpop send a message saying no staff are online and to post on the discord - ALLREADY CAN BE DONE in language file  Line: commands -> helpop -> info -> offline:

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4305]
Sorry first for created a new request thread, but since some users think its needed to block others this seems to be needed...

original thread from a user that blocked me for no reason is #4302

> when no staff are online and someone uses /helpop send a message saying no staff are online and to post on the discord

i decided to still answer him and _**this reuqest will be closed by me, because its a responce after the user of the original request closed his ;-) If its clsoed i trullly aspect that he got the answer from my Title head or has read read my request ticket ;)**_

The question of #4302  was:
> Can you have a check for if a player uses /helpop and no staff are online? And to simply give them a message that we can customize in the languages file.
> This way I can set the message to tell them to use our discord as there are no staff online.

look in your langfile.. im wondering that you missed this...

```
  helpop:
    help:
      info: '&eSends message for help to staff members'
      args: '[message]'
      explanation:
      - Requires cmi.command.helpop.inform too see messages
    info:
      message: '&c[Help]&4[&7[senderDisplayName]&4]&r&c [message]'
      feedback: '&c[Help]&7Your question was submitted to online staff'
      offline: '&c[Help]&7There are no staff members currently online, try later'
```

Edit line Line: offline This line is getting to the player when no other with permission for helpop inform is online.
So use the measssage to go to discord there
you also can use Hovers and clickables to tdesign the answerline like a ctext with clickable content

Well here an example how i designed the line on our helpopsite when no staff is online..well u might see we also leading them to our discord if noone of staff is there..you see the idea itself from your original request was not really new *g* ;)

      offline: <T>{#b32000}&lL{#b36000}&lu{#719900}&ll{#569900}&lu{#009950}&ll{#008059}&la{#009099}&ln{#005999}&ld {#b32000}&lD{#b36000}&li{#719900}&ls{#569900}&lc{#009950}&lo{#009099}&lr{#005999}&ld{#0047b3}&ll{#005999}&li{#009099}&ln{#009950}&lk</T><H>Hier klicken um eine Einladung zum LululandDiscord zu erhalten.</H><URL>https://discordapp.com/invite/ydGyyTg</URL>

**Comment by CloudeLecaw** [comment]
look in your langfile next time before

```
  helpop:
    help:
      info: '&eSends message for help to staff members'
      args: '[message]'
      explanation:
      - Requires cmi.command.helpop.inform too see messages
    info:
      message: '&c[Help]&4[&7[senderDisplayName]&4]&r&c [message]'
      feedback: '&c[Help]&7Your question was submitted to online staff'
      offline: '&c[Help]&7There are no staff members currently online, try later'
```

Line: offline

**Comment by Insprill** [comment]
you could've just commented on his, no need to create another one. you should probably close this.

**Comment by CloudeLecaw** [comment]
> you could've just commented on his, no need to create another one. you should probably close this.

u have not read the thread ;)
i cant because he blocked me for answering to his thread. Once blocked your blocked for all threads of a user

**Comment by Insprill** [comment]
Ah my b
