### ISSUE TITLE
EXP Stuck

### ISSUE THREAD

**Issue by StarozytnySky** [Zrips/CMI#4308]
**Description of issue:** When player have 0 exp and i give him exp command /exp PLAYER give 1 and repeat this command to exp player 1522. Then when you give player /exp PLAYER give 1 he doesn't receive exp.
Exp stuck in 1522 exp. after you must give player 2 exp ( /cmi exp give %player% 2 ) then player receive 1 exp 
Previous will be problem with 358 exp.
https://github.com/Zrips/CMI/issues/3990

**Cmi Version (using`/cmi version`):**  8.7.7.4

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot

**Server Version (using `/ver`):**  1.13.2

**Comment by CloudeLecaw** [comment]
first of ll pls check if you have this isses also with cmi 8.7.8.1

**Comment by Zrips** [comment]
Its a general issue with minecraft failing to process exp in low quantities... No idea why its failing on such basic task... Will make some additional changes to make sure this doesn't repeat.
