### ISSUE TITLE
Scavenge doesn't respect special item names, lores and use not vanilla recipes

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4314]
**Description of issue:**

---
Hi, I wanted to use scavenge feature, but there's problem with it. because it can break some items into special ingredients which are used to craft special items. I mean when you have normal diamond hoe, and you put it into scavenge gui, then it can break into ingredients needed for special Slimefun diamond hoe named Diamond Combine Hoe (https://imgur.com/tCAOGCe). I think it could work only for VANILLA RECIPES, atleast there should be option for it. And mainly, it should probably respect when item has special name and lore... and if player puts there BASIC diamond_hoe without any nbt, name and lore... it should break into normal diamond hoe and not to special ingredients for special diamond hoe. Same for many other items.

---

**Cmi Version (using`/cmi version`):**  8.7.8.0

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  204, 1.16.3

**Relevant plugins (Delete if this isn't needed):** for ex. Slimefun with many addons (sensitible toolbox for example), Bossland, Magic etc. - plugins using custom recipes

**Comment by CloudeLecaw** [comment]
Vanilla also allows you to use modified Items, Slimefun is doing nothing else. It modifies a vanilla item with name, lore and maybe some other NTB data. it does not create a new items ;)
So its normal that CMI thinks this is the vanilla diamond hoe.
The some problem you have with recipes if you try to create custom recripes with modified item materials. it will not work and CMI converts them back to the vanilla variant of it.

**Comment by Volgeop** [comment]
So there isn't any way that for ex. scavenger couldn't use nbt tags for ex? Same could be for recipes, to exclude nbt tags (option).

**Comment by CloudeLecaw** [comment]
Yout got it, currently there is none

**Comment by Zrips** [comment]
Will make some changes relating to this to try and find best match
