### ISSUE TITLE
[Issue] Sitting on boats (allows sitting anywhere you want)

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#4317]
**Description of issue:**
Get a boat place it down anywhere, do /sit and remove the boat (you are now flying, or sitting on water.. Wherever you put it, it should work really)

---

**Cmi Version (using`/cmi version`):**  https://pastebin.com/4686PbTE

**Server Type (Spigot/Paperspigot/etc):**  Purpur, (fork of PaperSpigot)

**Server Version (using `/ver`):** https://pastebin.com/531VdESu

**Comment by Zrips** [comment]
For time being we will have to live with this small issue due to how minecraft handles armor stands which are used to place player into sit animation.
