### ISSUE TITLE
Can't find world with this name!

### ISSUE THREAD

**Issue by alexvermaning0** [Zrips/CMI#4322]
**Description of issue:**
it spamms the console with
[22:42:22] [Server thread/INFO]: Can't find world with this name!
i know its a world only thing as we copyed the chunk as schematic and pasted it to the exact location on same seed. but don't know whats cousing it. maybe you can and find out why.

and bacuse i worked hard on it i would rather not loose it.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[22:42:22] [Server thread/INFO]: Can't find world with this name!
```

---

**Cmi Version (using`/cmi version`):**
CMI v8.7.8.0 

**Server Type (Spigot/Paperspigot/etc):** 
paper 
**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-214 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT

Log: https://pastebin.com/fas8BQPW
world: https://www.dropbox.com/s/qef0im492ee0iau/16%20cold.zip?dl=1
cords: 297 70 848

**Comment by CloudeLecaw** [comment]
to be honnest..this does not really look like a cmi problem..

**Comment by alexvermaning0** [comment]
thanks for the help. the mobs problem was a fix by pasting it in a new world but i didn't know commandblock output was changed by CMI as i have CommandBlockOutput false.

**Comment by CloudeLecaw** [comment]
the command block output was not changed but the commands they tried to use are taken from cmi. and cmi needs a worlds you can avoid this by ussing the orginal command minecraft:command instead of just command
