### ISSUE TITLE
Incorrect color in /colors

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#4324]
**Description of issue:**
When you do `/colors`, Yellow (`&e`) shows as dark aqua (`&3`)
![image](https://user-images.githubusercontent.com/52843537/95049645-2934b000-06b8-11eb-9126-418db87b2b3d.png)

---

---

**Cmi Version (using`/cmi version`):** 
8.7.8.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-214 (1.16.3)

**Comment by CloudeLecaw** [comment]
Change it in your languhae file. you or someone else designed it wrong there^^

**Comment by Insprill** [comment]
yeah I see it, didn't realize it was in there. this lang is from almost a year ago so it must've been wrong at the time it was created :P
