### ISSUE TITLE
Don't suggest playernames if lacks perm ~.other

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#4325]
**Description of issue:**
If a player executes a command, player names are suggested after the command despite not having the `~.other` permission.
![Screenshot 2020-10-05 112335](https://user-images.githubusercontent.com/28690790/95063416-979c6100-06fe-11eb-91fa-ed089e3d16dd.png)

It should first check if the player has the `~.other` permission before suggestion player names behind a command.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
CMI:
```yaml
Nickname
  IncludeInTabComplete: false
BungeeCord
  NamesInTabComplete: false
```
Paper settings:
```yaml
suggest-player-names-when-null-tab-completions: false
```

---

**Cmi Version (using`/cmi version`):** 
Irrelevant in this case but it's 8.7.8.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.3

**Comment by CloudeLecaw** [comment]
this is abehavior you have in many commands. even if there is nothing behind it.
Its just a coincidence that in case of CMI there can be playernames after^^

This happens to a lot of plugins + near to all aliases
i dont think there is anything we can change about this.

**Comment by x1p** [comment]
Many other plugins don't suggest anything after the main command. I can give numerous examples. It's very hard to find an example of a plugin that suggest player names on every main command.
It's not a side effect on aliases as well. I can make an alias via commands.yml and it will not suggest player names.

**Comment by CloudeLecaw** [comment]
- create aliases for a plugin of your choice - you can design them with cmi or in the comamnds.yml of your main folder.
You will see the behavior will repeat there. that is what is used when using /command  from cmi an alias
CMI allready made it better als sees if it has arguments that needs to be used there and allows you to choose them.

the real command is /cmi command. and this should only show this behavior if a player argument is possible if there is an .others possible.

**Comment by x1p** [comment]
No command.yml will not suggest player names since this is disabled in my paper config as stated above
```yaml
suggest-player-names-when-null-tab-completions: false
```
Only if this is set to true, then it would.

Once it is inside CMI by means of CustomAlias.yml or Alias.yml, then CMI suggests player names as valid arguments.

**Comment by CloudeLecaw** [comment]
So with the main command you also get a playername suggest even if you dont have the  .other permissions?

**Comment by x1p** [comment]
Yes indeed

**Comment by CloudeLecaw** [comment]
That means something seems to be broken. Usually it just shows what you have permission for then

**Comment by x1p** [comment]
> Usually it just shows what you have permission for then

Indeed. If you don't have the permission, so won't see the command.
This issue is about the arguments behind the command. And that doesn't seem to be checked.

**Comment by Zrips** [comment]
This is not really a bug but simply lack of feature or basic improvement on current system. By default command which have player name as possible tab complete will suggest player name for tab complete without checking if player who tries to tab complete have access to particular permission node. Will play around this and it should be resolved with next update
