### ISSUE TITLE
Kit Items w/ Lore

### ISSUE THREAD

**Issue by ZEROOblivious** [Zrips/CMI#4329]
I'm having a problem with my /kits with lore on them disappearing on death in all dimensions. I've tested basic enchanted items with no custom name or lore and it drops on death, I've attempted a kit with custom name & no lore, the items don't drop. Its LORE specific items that disappear on death. 
Any idea on what's causing this issue? For now ill be removing the lore from all the kits so this doesn't keep happening; but gave a list of plugins, let me know if there's a compatibility issue with any of them, etc?

---
![image](https://user-images.githubusercontent.com/32251194/95105355-0977a900-0705-11eb-9a24-d4f61009d835.png)
![image](https://user-images.githubusercontent.com/32251194/95105406-214f2d00-0705-11eb-9327-085bc5e1547c.png)

**Comment by Zrips** [comment]
You will need to test this one by yourself by starting with a empty server and CMI only installed to make sure that its actually originates from CMI. Other than this i cant really say what could cause item removal based on lore, cant recall any code in CMI which could do anything like this.

**Comment by ZEROOblivious** [comment]
Understood,

Thank you for the response Zrips.
I'll do it the old fashion way.
