### ISSUE TITLE
mcMMO Top Placeholders Expansion

### ISSUE THREAD

**Issue by TheExceed** [Zrips/CMI#4330]
Placeholders to show rank # and the player name coinciding with that the rank # for mcMMO top skills
For all skills, including power level. Support for holograms.

---
Details:
%mcmmo_rank_<skillname>_<#>%
%mcmmo_rankplayer_<skillname>_<#>%

Example:
%mcmmo_rank_powerlevel_1% - will return the highest power level in mcMMO (integer)
%mcmmo_rankplayer_powerlevel_1% - will return the player name with highest power level in mcMMO (string)

Example 2:
%mcmmo_rank_powerlevel_2% - will return the 2nd highest power level in mcMMO (integer)
%mcmmo_rankplayer_powerlevel_2% - will return the player name with 2nd highest power level in mcMMO (string)

Why:
Allows creating mcMMO Top holograms for people to view by adding these placeholders to the hologram.
Also allows the hologram to be more customizable than the default /mctop in-game command.

**Comment by Zrips** [comment]
Isint this should be added by MCMMO and not CMI? I mean, those placeholders are completely from MCMMO plugin and if they add support for it then throw placeholderAPI CMI can grab correct values and display them on holograms. So ether MCMMO needs to add support for it or placeholderAPI as it already have some support for most common plugins in any case, but this is not something what CMI needs or should have.
