### ISSUE TITLE
AFK StopCoutingPlaytime

### ISSUE THREAD

**Issue by Ut5dere** [Zrips/CMI#4332]
Hello, I have a little question for you.
I have CMI on my server and I need one thing, If player is offfline, to stop counting his Playtime, what should I do for it?
I have this in my config, but it doesnt work.
Afk:
  # Enable or disable auto afk system entirely
  Enabled: true
  # Prevents jumping in one place to avoid afk status
  PreventJumping: true
  # Prevents damage while afk
  PreventDamage: true
  # Defines how often in seconds plugin will check for afk players state
  CheckInterval: 10
  # When set to true, players playtime counter stops
  # As of nature how this system works you can see +-1second jumping up and down while checking players playtime
  StopPlayTime: true
Thanks.

**Comment by Zrips** [comment]
If player is offline, then playtime is not counted by default

**Comment by Ut5dere** [comment]
I need this, if player is online, count his time, if player is online and afk, dont count his time.
