### ISSUE TITLE
Disable afk module disables /serverlist

### ISSUE THREAD

**Issue by Giloh** [Zrips/CMI#4336]
Setting afk to false in modules.yml causes /cmi serverlist to not be recognised.
This is unexpected behaviour to me. It isn't mentioned next to the afk comment in modules.yml and it's not mentioned on the zrips.com commands page.

---

**Cmi Version (using`/cmi version`):** 
8.7.8.2, 8.7.7.1

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 216

**Comment by CloudeLecaw** [comment]
aww this is a bug /cmi serverlist usually has nothing to do with /afk :3

**Comment by Zrips** [comment]
Will be fixed with next version
