### ISSUE TITLE
Hex Color Permission

### ISSUE THREAD

**Issue by Plum1111** [Zrips/CMI#4337]
**Description of feature/improvement request:**
Basically just a permission for hex colors so that you can restrict who can use them and who can't.

---
### Detailed explanation of what it should do, when and in what situation: ###
If they have the permission they can use them and if they don't they can't. It would work like the current color code format (cmi.colors.[type].[colorname]) but in colorname it would simply be 'hex' like cmi.colors.privatemessage.hex

### Basic explanation as to why this feature is needed and/or useful to have: ###
Useful if you want a certain rank to only be able to use hex colors

**Comment by CloudeLecaw** [comment]
Negate all you dont want them and give the starpermission after cmi.colors.privatemeassage.*
On other groups just give the choosen color permissions you want.

**Comment by Plum1111** [comment]
> Negate all you dont want them and give the starpermission after cmi.colors.privatemeassage.*
> On other groups just give the choosen color permissions you want.
> For the other groups just give what permissions they are allowed to use.
> Dont forget that color permissions contain also the bold, italic, underlinednand and obscured (magic) permission.

This was already tried and it doesn't work.
