### ISSUE TITLE
Disable flight while in combat (with monsters too)

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4340]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, can you add way to disable flight when people are in combat, also with monsters?

### Basic explanation as to why this feature is needed and/or useful to have: ###
Will be useful to stop players "cheating" with fly and killing everything, bosses etc.

**Comment by Zrips** [comment]
Next update
