### ISSUE TITLE
[Bug] Console spam with placeholders in holograms

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#4343]
**Description of issue:**
Massive repeated console spam when players are near holograms that have placeholders. Unclear which might be triggering it, but pretty much all of the ones we use in holograms are CMI placeholders such as vote top, playtime top, etc. Happy to do some more digging to narrow it down if you're not sure what's causing it. Not seeing any issues in game, just the spam and a pretty big CPU drain.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://gist.github.com/mercurialmusic/94086481d2904467ed8875d27b286bde

---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.7.8.2 BungeeCord CMIB SqLite
CMI economy: True Vault: 1.7.3-b CMI Chat: False
Modules -> 49 enabled 2 disabled: ranks, skin

**Server Type (Spigot/Paperspigot/etc):** Paper/Waterfall

**Server Version (using `/ver`):** Paper version git-Paper-220 (MC: 1.16.3)

**Comment by Zrips** [comment]
Should be fixed with next release
