### ISSUE TITLE
Error loading 

### ISSUE THREAD

**Issue by Sinimatic** [Zrips/CMI#4345]
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
#############################
## https://pastebin.com/a0zVyQhm ##
#############################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`) 8.7.8.2:** 

**Server Type (Spigot/Paperspigot/etc): Paper version git-Paper-207 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)** 

**Server Version (using `/ver`): 1.16.3**

**Comment by Zrips** [comment]
Redownload plugin and perform full server restart.
