### ISSUE TITLE
Please add %cmi_lastrandom_[from]_[to]%! for later useage. 

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4346]
I want to design a command that gives player on execute some random XP
After doing this they should get an Infomation in title or bossbar (You got X XP)
Therefore i would need the possibillity to repeat the content of a random amount generated placeholder (we talk about the placeholder %cmi_random_[from]_[to]%)

Well the first part is easy because it can be designed allready

cmi exp [playerName] add %cmi_random_10_50%

would add the a random amount of 10 to 50 XP to the user.

The the secound part cant be done at the moment without something like an other placeholder? that saves the last %cmi_lastrandom_[from]_[to]% as a fixed value
so it can be used in later textes.

example:

cmi bossbarmsg [playerName] -sec:5 -t:5 -n:gotXP -p:100/100 You got %cmi_lastrandom_10_50% XP

Here the placeholder %cmi_lastrandom_[from]_[to]% (in this case %cmi_lastrandom_10_50%) should print out the last value of %cmi_random_10_50% to be able to use it for other texted after
choosing the random amount.

With this we could design many nice things that are based on random generated values.

Curently we have

```
%cmi_random_player_name%
%cmi_random_[from]_[to]%
%cmi_lastrandom_[playerName]%
```

so for playernames we have this allready :-)

**Comment by Zrips** [comment]
%cmi_lastrandom_Zrips% returns last value used in %cmi_random_[from]_[to]% placeholder. So if you generated random EXP then you can use placeholder to print out amount of exp player got. 
```
asConsole! cmi exp give [playerName] %cmi_random_1_10%
asConsole! cmi msg [playerName] !Got %cmi_lastrandom_[playerName]%exp
```

**Comment by CloudeLecaw** [comment]
Your a Genius, that was execly what i need. I thought it return last playername if random playername was choosen. Thank you <3
