### ISSUE TITLE
Command allready in useage - block it

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4347]
When player executes a command that follows a little "skript" then he should not be able to use it until it is still running

One simple example from an Test-IC:

```
TestSign:
  Commands:
  - msg! [playerName] in 5 Secounds you get the next meassge
  - delay! 5
  - msg! [playerName] in 5 Secounds you get the next meassge
  - delay! 5
  - msg! [playerName] in 5 Secounds you get the last meassge
  - delay! 5
  - msg! [playerName] Done- this was the last meassge.
```

When the player now clicks on the sign he should not be able to run the command aggain until the whole process is done

Maybe an optional meassage that informs him "You running this command allready, Please wait until its finished."

If not possible i also could add cooldowns to prevent this.
but it still would be nice to be able to block that while a command is still running its content. specially on "skripts" you designed with interactive or atteched commands or custom alias.

Here example with a cooldown even that its not what i wanted

```
TestSign:
  Commands:
  - cooldown:15#! msg! [playerName] in 5 Secounds you get the next meassge
  - delay! 5
  - msg! [playerName] in 5 Secounds you get the next meassge
  - delay! 5
  - msg! [playerName] in 5 Secounds you get the last meassge
  - delay! 5
  - msg! [playerName] Done- this was the last meassge.
```

**Comment by Zrips** [comment]
Next update
