### ISSUE TITLE
wrong permisison asked for when custom alias is using /command instead of /cmi command

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4349]
we designed a custom alias for /cmi helpop what is /hilfe

so players can use /hilfe Their text ingame

Problem: In chat i see a strange wrong permission that is asked for
Like you can see it asks for base.command.helpop
Should'nt all cmi commands ask for cmi.command.(commandname)?
![image](https://user-images.githubusercontent.com/12080017/95586226-ae192400-0a40-11eb-917d-bc0905c1ec8b.png)

why i use /cmi helpop Text it is correct
![image](https://user-images.githubusercontent.com/12080017/95586270-bffac700-0a40-11eb-9d3e-afdf5e34b26e.png)

Why the customalias created with CMI asked for this base.command.X permission?

I could fix the problem but the reason is still a bug:
Problem comes for example when you create a custom alias and use the alias in it instead of the real command
create an custom alias like
- testcommand
- let it execute "helpop $1-"
Result - instead of You dont have permission cmi.command.helpop  you get - you dont have permission base.command.helpop

Well this can be prevented when let the custom alias executing the cmi (command) instead of command.

**but the fact that it shows  base.command.(command)  instead of  cmi.command.(command) in the console is a bug that may can be fixed too :-)**

**Comment by Zrips** [comment]
Should be fixed with next update. Tho its strongly recommended not to use alias in customalias to prevent some possible stackoverflow issues in case you will utilize alias of alias which is alias of same first alias. Which happen couple times already with people reporting issue like that.
