### ISSUE TITLE
Tablist aint working..

### ISSUE THREAD

**Issue by DutchUser** [Zrips/CMI#435]
**CONFIG SECTION (DELETE IF NOT RELEVANT):**

(https://pastebin.com/5cYjzbDR)

**Cmi Version (using`/cmi version`):** 
30.05 15:43:27 [Server] INFO Vault version: 1.5.6-b49(CMIEInjector)
30.05 15:43:27 [Server] INFO Server version: Spigot 1.12.2-R0.1-SNAPSHOT
30.05 15:43:27 [Server] INFO CMI plugin version: 7.7.11.0

**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-7754231-94b0980 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

https://postimg.cc/image/5386v7047/

(Issue is that playernames are gone, and only the head you can see.)

**Comment by LogGits** [comment]
```
  GeneralFormat:
    PlayerName: ' %cmi_user_afk_symbol%[playerDisplayName]'
```

That PlayerName in your config is set to ` `` `. Change it to this and it should be fixed. Let me know if this fixes it.

**Comment by DutchUser** [comment]
Yes its fixed, Thanks :D

I have an other issue too. But will open an other thing about it.
