### ISSUE TITLE
/cmi info shows same IP address for every player

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#4358]
**Description of issue:**

When I run /cmi info <player> I always get the same ip address: 221.192.199.49 for every player. I get this even in my local server when I run it on myself. /checkaccount still gives the right values.
---

**Cmi Version (using`/cmi version`):** 
8.7.8.2
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
220
**Relevant plugins (Delete if this isn't needed):**

**Comment by CloudeLecaw** [comment]
looks like from your serer your connection ports over a china server even with this is just a lead of the track line over china

![Snag_6a127a](https://user-images.githubusercontent.com/12080017/95674478-c314c500-0bb0-11eb-9dfd-7fc97858dd1f.png)

but looks like cmi stops there and does not go to the end pf the track.
This is how your connection track seems to be setup

YOU/YOUR Players -> somewhere -> CHINA -> maybe somewhere -> END
well if this goes over the whole world you should aspect a bit higher pings
have you tried a ping test? (it should not be higher then 30)

**Comment by x1p** [comment]
The /cmi info displays the wrong information. Don't get fooled.
See issue: https://github.com/Zrips/CMI/issues/4331

The real IP addresses are noted correctly in the database.
If you happen to save it to a mysql, you can view the raw information there.
Use the bungee/litebans information for now until this bug is solved.

**Comment by radiant-ai** [comment]
@CloudeLecaw your analisis is interesting, but I said that I have same issue in both localhost and prod server, those are on different ends of Earth and I doubt that the whole Earth is connected through China...

**Comment by CloudeLecaw** [comment]
China is everywhere :P

**Comment by Italoplcl** [comment]
https://github.com/Zrips/CMI/issues/4331

**Comment by Zrips** [comment]
Will be fixed with next release
