### ISSUE TITLE
Uncondense Works on Items Without an Uncondensing Recipe

### ISSUE THREAD

**Issue by JGMinimule** [Zrips/CMI#4359]
**Description of issue:**
The following /uncondense recipes have started working without a custom recipe allowing them:

- Sandstone --> Sand
- Blue Ice --> Packed Ice
- Packed Ice --> Ice
- Quartz Block --> Quartz

There may be other recipes that we haven't discovered yet, but they may stem from the same root issue.
/condense does not work to reverse these recipes.
If there is any more information that I can provide you with, let me know and I will do my best to get it.
---

**Cmi Version (using`/cmi version`):** 8.7.6.11

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Paper-220 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will be fixed with next update
