### ISSUE TITLE
Cross-server portals do not teleport after server restart

### ISSUE THREAD

**Issue by Giloh** [Zrips/CMI#4361]
If the target server of a portal has restarted, the first player to go through will not be teleported to the desired position, and will not run the portal commands.

https://pastebin.com/PAFLA3Mf

---

**Cmi Version (using`/cmi version`):** 8.7.8.3

**Server Type (Spigot/Paperspigot/etc):** paper 223

**Comment by Zrips** [comment]
Should be fixed with next update
