### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4363]
**Description of issue:**

---
Hi, my server crashed from some reason, there's mentioned CMI at the beginning. And it didn't happen before, maybe something in new ver?
**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://pastebin.com/H3Z2ReXN

---

**Cmi Version (using`/cmi version`):** 8.7.8.3

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 214

**Comment by Zrips** [comment]
Something related to player inventory save into database on player death. Could be a dropped connection to your mysql server. If it repeats, let me know, but if this is first time you see it and doesn't really repeat, then its just a fluke.
