### ISSUE TITLE
Add support for "all" or [allPlayers] for admin commands like /afkcheck

### ISSUE THREAD

**Issue by GenSecrets** [Zrips/CMI#4364]
**Description of feature/improvement request:**
On the server i admin for, we have about 20~ ish staff members total, and an avg of 100 players on at a time. Some commands like `/afkcheck` don't have support for "all" or `[allPlayers]` and can only take `[playerName]`. This also applies to trying to run it through custom alias such as `allPlayers! cmi afkcheck [allPlayers]`

---
### Detailed explanation of what it should do, when and in what situation: ###
Staff member could run `/afkcheck all` and it checks all online players on the server, and just runs `/afkcheck <player>` on every online player and reports that to the staff members chat.

### Basic explanation as to why this feature is needed and/or useful to have: ###
With an abundant amount of online players, it's challenging to run `/afkcheck` or other admin commands on every single one individually. Running an "all" variant would give a report of all online players and reduce time spent drastically.

**Comment by CloudeLecaw** [comment]
U forgot a little thing in your custom alias type asPlayer! Before then it should work

**Comment by GenSecrets** [comment]
Afraid not, i had tried that and similar ones the other day with no dice. Just now tried it again and no luck still

Here is an example of a few of the variations i have tried 
![20201012_012719.jpg](https://user-images.githubusercontent.com/34498632/95708456-51795d00-0c2a-11eb-9d1e-ab173a9b1e0a.jpg)

I also attempted with different variations using "all" and "[playerName]" as well in place of "[allPlayers]"

**Comment by CloudeLecaw** [comment]
hm i just took a look at this
In example: allPlayers! cmi heal [allPlayers] will heal everyone who is online.
How the result of AFK Check looks like?
lets see
```
  afkcheck:
    help:
      info: '&eÜberprüfe den AFK-Status eines Spielers'
      args: '[playerName]'
    info:
      feedback: '&e[playerDisplayName]&e: &6[status]'
      feedbackInactive: '&eInaktiv seit &6[time]'
      feedbackReason: '&7[reason]'
```

Well here u see the reason why this does not work
the result is not made for more then one player executing this for each online would spam the chatlist
for having all a new list may would be needed
where all players online art listet
```
Player - inactiv/activ
Player2 - inactiv/activ
Player3 - inactiv/activ
.....
```
and when Hovering over the names you would see the inactive time and the reason if set
and when hover

**Comment by Zrips** [comment]
Listing active players is quite pointless, but will add option to list all inactive ones in some basic list
