### ISSUE TITLE
New combat mechanism to disable fly - don't give fall damage when player falls

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4365]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, when the combat starts and player's fly got disabled, could you add protection from fall damage for them?

### Basic explanation as to why this feature is needed and/or useful to have: ###
Cause when players are flying and are shot by skeleton for ex. or by blaze in Nether, they'll fall down and they're mostly killed by fall damage, maybe protection for the first fall damage when their fly got disabled?

**Comment by Zrips** [comment]
Will add
