### ISSUE TITLE
AnvilReportLimit causing dupe ability

### ISSUE THREAD

**Issue by hitakiller** [Zrips/CMI#4367]
Hello, I've an issue with Cmi's module : anvilUnlimitedRepair. This modules allow players to dupplicate their inventory.
I don't know if it's intentionnal or needed to function properly so i post here.

**Description of issue:**
When a player use an anvil to repair an item over vanilla natural limit, this player's gamemode is changing to creative and that allow him to dupplicate with middle click his inventory.

To reproduce :
1. Take an item with a repaircost superior as vanilla limitation (tested with "RepairCost (Int): 63")
2. Put you in gamemode survival
3. Open an anvil GUI with right-click
4. Your heart dissapear, you're in gamemode creative
5. middle-click on an item inside your inventory to dupplicate it, just like you can do in creative gamemode.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
modules.yml

# Handling of anvil unlimited repair
# Applies for servers from 1.9.x and up
anvilUnlimitedRepair: true
```

---

**Cmi Version (using`/cmi version`): 8.7.8.3** 

**Server Type (Spigot/Paperspigot/etc): Paper(223) 1.16.3-R0.1-SNAPSHOT** 

**Server Version (using `/ver`): git-paper-223** 

**Relevant plugins : CMI**

Is there a way to allow this module without allowing creative's inventory edit ?

Thank's in advance for your support, have a good day !

**Comment by Zrips** [comment]
That game mode change is only client side and not server side, so there should not be any way to middle click on item. Did some testing and cant reproduce this issue on 1.16.3. Have you tested this without any plugin but CMI only? Just to make sure this issue originates from CMI in particular and this is not some weird compatibility issue with another plugin.
