### ISSUE TITLE
Horse riding teleport does not work, no error message

### ISSUE THREAD

**Issue by abc605521864** [Zrips/CMI#437]
**Description of issue or feature request:**

Horse riding teleport does not work, no error message

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
VehicleWorkArround: false/true

**Cmi Version (using`/cmi version`):7.7.11.0

**Server Type (Spigot/Paperspigot/etc):Spigot/Paperspigot

**Server Version (using `/ver`):1.12.2

**Comment by LogGits** [comment]
did you set the correct permission nodes?

`cmi.teleport.with.[entitytype]`
e.g. 
`cmi.teleport.with.horse`

Also was this working and broke for you or was it never working for you? in terms of the `false/true` and `Spigot/Paperspigot` are you saying it doesn't work no matter what server software you are using and what the config's value is set to?

**Comment by arturek1666** [comment]
I have same issue with the horses. Even as OP and with all permissions the horse don't teleport with me. :(

**Comment by CloudeLecaw** [comment]
On Our Server we also Need the Extraplugin [HoseTPWithME](https://www.spigotmc.org/resources/horsetpwithme.8186/)

I hope one day the Horseteleport is working correct in CMI too so we can go away from this Plugin :§

**Comment by Zrips** [comment]
If issue still persists with latest versions, please let me know. And test this feature on your server without any other plugin which could block entity teleport/spawn events
