### ISSUE TITLE
Attached Commands 

### ISSUE THREAD

**Issue by slipstricker** [Zrips/CMI#4371]
**Description of issue or feature request:**
when we create Attached Commands with !right!!cooldown:10!
Cooldown activates when left click

example command: /cmi attachcommand !right!!limiteduse:10!;;!right!!cooldown:10!;;!right!!cc!effect [playername] fast_digging 30 1
---

**Cmi Version: 8.7.8.3** 
**Server: Paper(221) 1.16.3-R0.1-SNAPSHOT**

**Comment by CloudeLecaw** [comment]
Well your command was design a bit messy.. would wonder if this will work


Attched command als all kind of specialzed comamnd work like a LINE Interepreter from left to Right, from up to down where conditions are checked

So may you see your double tribble and more offten check for rightclock..why?

Well take a look into the wiki aggain and u may see why your command was wrong dessignt ..
https://www.zrips.net/cmi/commands/attached-commands/

So here is a bit more locial order + cleaned up your command abouve


example command:
`/cmi attachcommand !right!;;!cooldown:10!;;!limiteduse:10!;;!cc!cmi effect [playername] fast_digging 30 1
`

This would check now in this order:
- check was is right clicked?  YES - NO
- is for cooldown  reached?  YES - NO
- can item be useded?   YES - NO
- execute command as cc

**Comment by slipstricker** [comment]
I'm trying to say that cooldown is activated by clicking with any button "left or right"

**Comment by Zrips** [comment]
Should be working correctly with next update
