### ISSUE TITLE
Restricting Flightcharge in certain regions/areas

### ISSUE THREAD

**Issue by Zoneman1972** [Zrips/CMI#438]
I would like to be able to restrict players from flying in certain areas/regions/worlds eg: the end and nether and envoy and pvp arenas.

Can you please add this function either through WorldGuard regions or some other way that would enable me to activate the restriction.

Thanks again for all your hard work on this plugin.

**Comment by MCTyler** [comment]
If @zrips doesn't.....Use the **NoFlyZone** Plugin.
