### ISSUE TITLE
Command fees problem with spaces (cooldown overwriting it)

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4380]
**Description of issue:**

---
Hi, I wanna report issue, that when I set mentioned example in the file command fees this` cmi itemname :1000:true` to prevent taking money from just /itemname info page, then under cooldowns: section in config I have: `cmi itemname :43200`, again to prevent triggering cooldown when just they wanna see help page. 

And now the problem. Problem is, when you have these settings.... and use /itemname <something>, then command fee is triggered, so I'll accept it, and then instead of command being executed, then it's overwrited by cooldowns: section, so the command isn't executed, item isn't removed, I paid and I have to wait next 12 hours.... Will give you examples with similar commands I tried it with.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Cooldowns: in config (these commands which show without space just help page)
```
  - cmi itemname :43200
  - cmi ptime :3600
  - cmi pweather :300
  - cmi merchant :3600
```

In command costs:
```
- cmi merchant :600:true
- cmi itemname :1000:true
- cmi pweather :200:true
- cmi ptime :200:true
```

Btw when I didn't use space in command costs, it worked, like you implemented here I think "Fix for cooldown being triggered when performing command with cost set on it", but this is still the issue. Same when you use delay! n custom alises, still problem there with command fees combination, but this is mentioned here https://github.com/Zrips/CMI/issues/4243

---

**Cmi Version (using`/cmi version`):** 8.7.8.4

**Server Type (Spigot/Paperspigot/etc):** Paper, 1.16.3

**Server Version (using `/ver`):** 228

**Comment by Zrips** [comment]
Will be fixed with next version
