### ISSUE TITLE
Wrong order of items in kits

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4383]
**Description of issue:**

---

Hi, I have issue with wrong order in kit command. When I edited it via kiteditor and changed order, it should be like this: https://imgur.com/UvFOjMR, you can see the shovel should be one item above. But when players gets it, they normally gets it like this: https://imgur.com/undefined

---

**Cmi Version (using`/cmi version`):** 8.7.8.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 228

**Comment by Zrips** [comment]
Items in action bar slots (4th row) will be placed into appropriate slots if there is a free one. Anything else what is in last 3 raws will be simply placed into players inventory, in which case it will be placed into first empty slot and in your case it was that one just belove it which created this "issue". Will adjust the code to try and place every item into defined slots if possible, as i cant really see a reason why it should not at this point.

**Comment by Volgeop** [comment]
Ok, I wanted another slot order for my newcommer's kit, because I'm giving other items through commands there and wanted them in the first main slot bar. And when kits were giving it theree first and didn't respect order, other items were given to other slots of inventory.
