### ISSUE TITLE
Typo in spawner section

### ISSUE THREAD

**Issue by ViaSnake** [Zrips/CMI#4386]
Typo in the Spawner section.
`When set "tp" false,`

config.yml line 936
```
    # When set tp false, exp will not be dropped from broken spawner independent if spawner it self is being dropped
```

---

**Cmi Version** 
8.7.8.4

**Comment by CloudeLecaw** [comment]
Great catch it should be xp not tp :-D

**Comment by Zrips** [comment]
Will fix this one, thanks for noticing
