### ISSUE TITLE
CMI and GadgetsMenu Miniatures conflict with Armor stand editor

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4387]
**Description of issue:**

---

Hi, when I summon GadgetsMenu (Premium) miniature and then right click on it with shift, then I can open it's armor stand editor, but it probably shouldn't happen to miniatures (pets). https://streamable.com/5bvdef Proof is here. Will be nice, if you could somehow prevent it, it's also consuming all items when it's clicked.
---

**Cmi Version (using`/cmi version`):** 8.7.8.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 228

**Relevant plugins:** https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-16-3-premium.62831/

**Comment by CloudeLecaw** [comment]
These Miniatures are baby amorstands so its normal that cmi thinks they are... Right an armorstand if you have the permission for shift rightclick it.
Well im not sure but this maybe cab be fixed from both sites, have you also informed the gadjets menue dev?

**Comment by Volgeop** [comment]
Yea, I informed GadgetsMenu dev too, so let's see his response on it.

**Comment by Zrips** [comment]
@Volgeop 
Inform GadgetsMenu dev that he simply needs to listen to PlayerArmorStandManipulateEvent and cancel it if this was done on one of his armor stands. This will resolve this issue at his end and i will not need to create 50+ compatibilities with every single plugin which wants to protect armor stands in some or another way.
