### ISSUE TITLE
Bug report for item:[itemdata](-amount)! <

### ISSUE THREAD

**Issue by tsnorara** [Zrips/CMI#4389]
**Description of issue:**

---

**Among specialized functions, item:[itemdata](-amount)! recognizes and takes the item normally, but when the item is renamed, it only recognizes and does not take the item. in your discord I uploaded the photos and GIFs on October 16th.(If you have a solution to this, please comment) **
```
######################
## item:[itemdata] (-amount)! ##
######################
```

---

**Cmi Version (using`/cmi version`):** 
8.7.8.3 sqLite
**Server Type (Spigot/Paperspigot/etc):** 
Paper(655)
**Server Version (using `/ver`):** 
1.13.2

**Comment by Zrips** [comment]
You will need to be more specific. What does command look exactly and what does item look like, best would be to have itemnbt data shown with /cmi itemnbt just o know exactly which ones bugs out for testing. Currently cant reproduce issue, so something is different with your setup.
