### ISSUE TITLE
./kit request or question

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#439]
I didn't see this in the documentation but is there a way to give people permission to just view a kit? Orrr can we get that added? Like just preview not actually use it or anything.

**Comment by LogGits** [comment]
Well `/cmi kit` and right clicking a kit should work but I am getting a strange bug so i will label:
Bug (seems to close the preview inventory instantly):
https://gyazo.com/8c115851293e84dbeb1f50498cf79b4a

there is also `/cmi kit [kitname] -preview`

**Comment by Kbryst** [comment]
But they need permission to access the kit in order to preview correct? I just want them to be able to preview it without being able to claim it

**Comment by LogGits** [comment]
Yes currently, I think a preview permission would be really useful. Something like `cmi.kit.[kitname].preview`, could also be used as `cmi.kit.*.preview` to preview all kits.

**Comment by GrimPod** [comment]
No bug like that here with the auto closing gui,

And as for the previewing the kit, weve done a workaround,
We have made 2 kits for every rank, 
The first having a red concrete block to simulate you cant get this one, but you can still preview it 
and the 2nd being when they can it has green concrete to show they can
Each rank has the 1st kit perms(the useable one) up until its rank, then the 2nd kit perms for all higher ranks

This also is kinda fun to play with, as you can make extra little things, like
the tools in our kit have some funny lore on them, but in the preview kit we dont put them on 
just an extra little thing xD
[![Screenshot from Gyazo](https://gyazo.com/dd853dcc94d2c7cb4ede842dd3154236/raw)](https://gyazo.com/dd853dcc94d2c7cb4ede842dd3154236)

**Comment by GrimPod** [comment]
Also you could technically had a condition atm
So that way they could acess the preview but then if they tried to redeem they wouldn't meet the condition

**Comment by RustyDagger** [comment]
I own the server with Grim, Our preview kits use the conditions to stop them claiming the preview.
Granted our permission system is a 3 group system so at any given time a player could be in upto 3 groups. weights come into play alot when setting something like that up. For example I am in Default Dragon and Owner groups. Default is a group every one has. any additional perms come from another group added.

CMI is very powerful if you are willing to spend the time setting it up, for example we made a whole Random number powerd maze with just warps and portals and a tiny bit of custom placeholder code. the end result you would think is ran by a plugin on its own.

**Comment by Kbryst** [comment]
Wouldn't that make them show up on the /kit gui? I was kinda hoping that it wouldn't unless they can actually claim the kit

**Comment by GrimPod** [comment]
In a regular kid you can just make it require perm node to use/see/preview it
We wanted people to see/preview what they could get all times without them being able to get/use them
Which is what ur original issue was about,
"I didn't see this in the documentation but is there a way to give people permission to just view a kit? Orrr can we get that added? Like just preview not actually use it or anything."

**Comment by Kbryst** [comment]
I just want them to preview it with a command and not in their gui. In the gui they should only really see what kits they CAN claim

**Comment by GrimPod** [comment]
Well I believe that when u click to preview a kit it does just run a command 
So get that command and done 
I beleive it is a bit of a weird one thou with multiple tags 
So an easier way to do it would be to make a custumalias that just runs that command as the player 
That way you can set the command

**Comment by Kbryst** [comment]
I get that part, makes total sense. I tried it out and I do see what you mean.

But the problem still is that it will show up in their gui of all the kits

**Comment by GrimPod** [comment]
Ok so we have a kit named 'Fling' on my server
not all players can get it, only ones with the cmi.kit.fling permission node assigned to them or their group
when they have this node, they can get and preview the kit

If they dont have this permission node they cant see the kit in /kit therfore thyey cant preview it, 

I got on just for you and made an alias for you, 
My alias is test, all it does is
`fromConsole! cmi kit fling [playerName] -preview`

All this does is as console, runs the kit preveiw command for the player that runs /test
I could now also make it 
`fromConsole! cmi kit $1 [playerName] -preview`
This would allow someone to do /test <kitname>
And it would run that command from console for the person that types in the command for the kit they type in, 

Im srsly not sure what is so hard about this

**Comment by Kbryst** [comment]
I think I haven't gotten the point across.

I want them to be able to preview it like /kit kitname -preview but then NOT have it in their GUI when they do /kit. 

I understand what you are saying, I am stating that when you do it that way it is still in their GUI. 

The point was to be able to preview it WITHOUT it in the gui. I don't want it to sit with the kits they CAN use in the same gui.

**Comment by GrimPod** [comment]
[https://youtu.be/BRnceJpJ3kU](url)
