### ISSUE TITLE
High timings?

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4390]
**Question: **
Hi, aren't these values in timings https://timings.aikar.co/?id=e82a7f689a13449a8b4f9e1fba4125eb about inventory and chat manager from CMI a quite bit high? If yes, could be somehow improved?

**Comment by Zrips** [comment]
CMI isint directly causing those reported lag spikes, its only triggering some events, like player quit event which was triggered by kicking out afk player after which you have bunch of plugins doing their thing and adding to the timings where you have CMI as a original cause. 
ChatControl and PlayerWorldPro takes allot more resources than CMI, even tho CMI is responsible for quite a few things.
