### ISSUE TITLE
CMI loading legacy data on non legacy servers

### ISSUE THREAD

**Issue by YouHaveTrouble** [Zrips/CMI#4391]
**Description of issue:**

"Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!"

There is legacy data (pre 1.13) loaded on 1.13+ servers. This impacts performance of other plugins that iterate or switch on the legacy values as Material class essentially doubles in size.

---

**Cmi Version (using`/cmi version`):** 
 8.7.7.0

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-196 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
It was kept there for better backwards compatibility, but at this point we can remove this from 1.16+ servers as people should have transitioned to new system by now. Will update code to avoid this.

**Comment by YouHaveTrouble** [comment]
1.13+ servers shouldn't have any legacy data loaded at this point, it only slows down stuff
