### ISSUE TITLE
Random Warnings spamming console

### ISSUE THREAD

**Issue by b01w** [Zrips/CMI#4394]
**Description of issue:**

Legit have 0 Clue, this warning is just spamming my console atm
---

https://pastebin.com/r9CMNBLC

---

**Cmi Version (using`/cmi version`):** 8.7.8.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** gi-paper-189 1.16.2

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Should be fixed with next build
