### ISSUE TITLE
Kit Bug

### ISSUE THREAD

**Issue by slipstricker** [Zrips/CMI#4395]
**Description of issue:**

Hello so, i found an issue with this lastest version of the plugin, my server has some kits but normally players would only acess one. With this new update now the players were able to acess all the kits. The message does appear saying that they don't have permission to do so on chat but they can get the items. So, how can i fix that?
---
**Cmi Version:** 
 CMI: 8.7.8.4
**Server Type:** 
 Paper(231) 1.16.3

**Comment by Zrips** [comment]
Ok, seams to be related to permission usage where you have set permission to use kits command name instead of config name which got confused in the code. Should be working properly with next update.
