### ISSUE TITLE
ArmorStand duplication bug

### ISSUE THREAD

**Issue by Ste3et** [Zrips/CMI#440]
**Description of issue or feature request:**

ItemStack duplication on shift left/rightclick itemswap from items of ArmorStands

https://www.youtube.com/watch?v=gTIFhlgcnkk&feature=youtu.be

cmi version: 7.7.9.0

server-type: Spigot 1.12.2-R0.1-SNAPSHOT (git-Spigot-2086bb0-8cc5a7e)

**Comment by Zrips** [comment]
Next update will have something what should fix this issue. Its quite strange one tho and more related to minecraft handling canceled clicks.
