### ISSUE TITLE
/info isn't tab completed for regular players

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4400]
**Description of issue:**

Hi, my players have permission to use cmi.command.info and in alias.yml is also set:
```
  # /cmi info $1-
  /info: true
```

But players still don't see /info in tab completion, even if they have permission for it and when they execute it, it normally works.
---

**Cmi Version (using`/cmi version`):** 8.7.8.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 228

**Comment by CloudeLecaw** [comment]
![image](https://user-images.githubusercontent.com/12080017/96419343-4b6c1900-11f4-11eb-8dbc-16030a00d0c7.png)

**Comment by CloudeLecaw** [comment]
Here i has a quick responce with octylFractal.
https://github.com/EngineHub/WorldEdit/issues/1568

he wrote:

> WorldEdit is probably overriding the command as a whole, the end user needs to manually unregister the WorldEdit one using commands.yml, or Spigot/Paper needs to learn to pick commands per-player.
> This isn't something we can particularly fix on our side, we've been using /info for ages but due to conflicts like this and Essentials, we're removing it in the future for /tool info. However, this won't occur for at least a few months, so one of the workarounds above should be used.

> Likely because Spigot/Paper tracks both commands, realized that one couldn't execute, and skipped to the one that could. Nothing we control.

**Comment by Zrips** [comment]
Due to how minecraft handles registered commands this is no longer possible as it seams. Will keep this in mind, but for time being we will have to deal with it.
