### ISSUE TITLE
Bypass command restriction from Combat

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4402]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, when i'm admin and something attacks me, I can't use also any commands... Would be nice if you add way to just blacklist some as I mentioned, but in this issue I wanna suggest you to bypass this list of commands, because as admin I really don't need to wait 15s before I can use any commands due to combat.

### Basic explanation as to why this feature is needed and/or useful to have: ###
When something attacks me when I'm testing something, then I can't use any commands...

**Comment by Zrips** [comment]
cmi.pvp.cmdBypass

**Comment by Volgeop** [comment]
Thanks, would be nice also this https://github.com/Zrips/CMI/issues/4399
