### ISSUE TITLE
Portals configuration GUI doesn't work

### ISSUE THREAD

**Issue by FaMa91** [Zrips/CMI#4403]
after the last update, portals to bungee server for 1.15.2 works well, but I can't edit portals from GUI, I'm editing directly from files.
Other GUIs like hologram are good.

---

**Cmi Version (using`/cmi version`):** 
8.7.8.4
**CMI Bungee:**
1.0.0.4 
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-385 (1.15.2)

**Comment by Zrips** [comment]
Will close this ticket as without any actual error log or example of hologram which dint worked i cant help out here. Open new ticket and if you have any information relating to this issue would be nice to have in determining what went sideways.
