### ISSUE TITLE
[Question] Is there a way I can replace the /tell command with the format of /msg?

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#4404]
**Question: **
Is there a way I can replace the /tell command with the format of /msg?

**Comment by Kbryst** [comment]
Oh hey its you again,

Use the aliaseditor. Do you want to fully disable tell as a feature or do you want both tell and msg to work?

**Comment by CloudeLecaw** [comment]
Yes there is simply create a custom alais for that and deny the bukkit permission for tell

**Comment by AZFire1** [comment]
Awesome, thank you very much.
