### ISSUE TITLE
[Feature Request] (Maybe) Per World Inventories as that would be useful to have in CMI

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#4405]
**Description of feature/improvement request:**
Per World Inventories are bassically self-explanatory and allow you to have it so players have per world inventories or maybe per gamemode inventories (configurable). I think this would be nice and possibly useful to have in a plugin such as CMI. I think this is a small feature and would definitely fit CMI.
---
### Detailed explanation of what it should do, when and in what situation: ###
When you either switch to a (configured) world or gamemode you're inventory changes to a previously saved one from when you were in that gamemode.
### Basic explanation as to why this feature is needed and/or useful to have: ###
This is a simple feature and I think it would be useful to have if you were wanting to switch to a building world for example and didn't want all your stuff to move with you and just start building..

**Comment by CloudeLecaw** [comment]
There are plugins like PerWorldInventory-KT that do this job allready very well :)
