### ISSUE TITLE
Economy doesn't calculate third decimal place in display.

### ISSUE THREAD

**Issue by Drafyr** [Zrips/CMI#4406]
**Description of issue:**
So everything works fine wiht the calculating. But when rendering a third decimal place I.E. 0.001 it doesn't display in the balance as a hard calculation. It displays a 0 at the end always; unless you reach the next tier of the 2nd decimal value I.E. 0.010. Is there no fix for this?

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```
 Whichever config I need to upload let me know. I'm sure this is a common issue. 👍 

#######################################
#######################################
```

---

**Cmi Version (using`/cmi version`):** 

8.7.8.3

**Server Type (Spigot/Paperspigot/etc):** 

Paper Latest

**Server Version (using `/ver`):** 

See attached file
![unknown](https://user-images.githubusercontent.com/48322205/96365920-64e06880-1101-11eb-8b5a-efd2c99a904d.png)

**Comment by CloudeLecaw** [comment]
what you have defined as format in the config? for 3 decimals it should be
    MoneyFormat: '###,###.000'

**Comment by Drafyr** [comment]
Alright! As long as the values aren't going to waste. :) 👍

**Comment by CloudeLecaw** [comment]
no they are not wasted the real amount of mone you have has a lot of decimales

if you look into the datafiles you see that some players have strange balnces like

xxx,xxx.352346234656878  beause some plugins like Jobs Reborn for example can give these small values ;)
finnaly it allways runded down like in the real world^^
so if your MoneyFormat is : '###.###,00'  and you have 99.999,99999 $
then it will show 99.999,99999 until u earched the next 0,00001 $ Then it raised up to 100.000,00000 $ what would be shown with this format as 100.000,00 $
You see MoneyFormat is just made to not confuse the one that is looking at the numbers ;)

**Comment by Zrips** [comment]
Excellent point, will issue fix for this one.
