### ISSUE TITLE
config.yml Combat: section (possibly bug consideration)

### ISSUE THREAD

**Issue by dmnchild** [Zrips/CMI#4408]
Enable/Disable for Combat: options separately for player, and mob.

---
### Detailed explanation of what it should do, when and in what situation: ###
We should have options to enable or disable each individually.

### Basic explanation as to why this feature is needed and/or useful to have: ###
We don't lock people into combat mode unless its against another player. This is making players not be able to /back and target and kill mobs that may have killed them. Thus making them have to wait out the timer to go grab their gear. It would be nice to have separate timers and enable/disable for each (along with the command and such settings as already there.

**Comment by Zrips** [comment]
You can simply disable all the options relating to pve combat in config file which will not block command usage or fly disabling or show boss bar message.
