### ISSUE TITLE
Custom Aliases - Execute random command from the list?

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4409]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, could you add option to make list of commands in one custom alias and there add something like Random! and then one of the commands listed below will be executed? Can't be just commands, could be also just one words or texts.

### Basic explanation as to why this feature is needed and/or useful to have: ###
For ex. if we wanna make custom alias to give random reward from event, this could be useful, then when we'll have custom alias to transform to youtuber, we'll want choose just one word from the list, where will be names of youtubers. There could be for ex. command to set player's name, like name [playerName] and then random![name,name,name] for ex. in this format, also will be acceptable for commands, if we use - random![give [playerName] xxx xxx xxx, give [playerName] yyy yyy] etc.

**Comment by CloudeLecaw** [comment]
You can do this allready with a work arround 
First you create a little msg with a randomnumber from let say 1 to 5
After that you create 5 check if it 1 2 3 45 command and if this is true then execute the command

**Comment by CloudeLecaw** [comment]
You put then instead the msg

**Comment by Volgeop** [comment]
Ok, works. thanks
