### ISSUE TITLE
Cant find player with this name! Name is only numbers

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#4412]
CMI 8.7.8.4
Paper 1.16.3

I have a pretty weird feature where a player can't use a command I have and I believe its because his username is only numbers. 

>.... [10:13:16 INFO]: Can't find player with this name!
>.... [10:13:17 INFO]: Can't find player with this name!
>.... [10:13:17 INFO]: Can't find player with this name!
>.... [10:13:18 INFO]: Can't find player with this name!
>.... [10:13:18 INFO]: Can't find player with this name!
>.... [10:13:19 INFO]: Can't find player with this name!

So what I have is an alias that opens a ctext as a book for them, it runs `fromConsole! cmi openbook $1- [playerName]`.

He's the only player it happens to, I can't recreate it at all. His username is "291204". No letters in it at all.

**Comment by EndlessLegends** [comment]
number name === -p:[playerName]

**Comment by Kbryst** [comment]
I don't understand the reply or the intention of the reply. Sorry

**Comment by Zrips** [comment]
issue with numeric name, will be fixed with next build
