### ISSUE TITLE
Symbols in custom text files not displaying correctly

### ISSUE THREAD

**Issue by EkonC** [Zrips/CMI#4414]
**Description of issue:**
---
I created a custom text and **it doesn't show « and » symbols correctly**.
---

**Cmi Version:** 
8.7.8.4 BungeeCord CMIB MySQL
**Server Type (Spigot/Paperspigot/etc):** 
Paper (240)
**Server Version (using `/ver`):** 
1.16.3-R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment]
Have you tried it with coeect useasge for all players?

**Comment by EkonC** [comment]
Thank you for the help with this issue. I hope they will solve those symbols not displaying correctly.

**Comment by EkonC** [comment]
Okay seems the problem was not in CMI
