### ISSUE TITLE
[Feature Request]  Command to teleport holograms to yourself (if not already a thing)

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#4415]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
This would be a command that allows you to teleport holograms that already exist to yourself, there have been many times I've messed up in the position I want the hologram to be and have had to delete and re-create the hologram itself just to get it in the right place I need it to be at. I think this could be extremely useful as there are some holograms that are really long and have multiple pages which are hard to move around, and this would make it far easier.
### Basic explanation as to why this feature is needed and/or useful to have: ###
This feature would make moving holograms much easier. As I previously said, it would help a lot in the moving process of a bigger hologram as it would stink if you needed to re-create the hologram each and every time you wanted it slightly moved. As I said in the title, I don't know if this already exists so I'm sorry if I didn't look at the documentation thoroughly enough.

**Comment by Zrips** [comment]
Hologram editor UI and clock icon will relocate hologram to your current position. And yes there is a hologram UI, by default you will need to click on "---- <Open settings gui> ----" which is above text lines. And that UI offers more accurate hologram placement by adjusting X Y or Z coordinates in increments and includes quite few other main features relating to holograms, like hiding holograms which are behind walls and all that jazz
