### ISSUE TITLE
Rankup/Hologram (Rankup - Porgress normal are |||||||||||| but mine now changed to ???????????????) (Hologram UP And Down also changed to ?????????????????) how do i fix this problem

### ISSUE THREAD

**Issue by DarrienNN** [Zrips/CMI#4416]
**Why my cmi having this issues?? **
![image](https://user-images.githubusercontent.com/58543201/96676639-6085ab00-13a0-11eb-984b-1b00c56b9001.png)
![image](https://user-images.githubusercontent.com/58543201/96676661-6da29a00-13a0-11eb-913b-97d6cae00a55.png)

**Comment by DarrienNN** [comment]
thanks problem fixed, problem come from translation Locate_EN.yml

**Comment by CloudeLecaw** [comment]
Maybe there was a currpted Symbol when you manuell editeded and saved the local file. This Specialy can happen to some ASCII onces if the file is not saved correctly innthe right Format (or if it become currpted by an update for no real reason)

Glad you found the issue allready by yourself

**Comment by Zrips** [comment]
Most likely caused by incorrect file encoding which made all special symbols none recognizable which usually results into ? or even more weird symbols appearing all over the place. Default encoding is utf-8
