### ISSUE TITLE
Error, some players can't open their mail

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#4418]
**Description of issue:**
When using /mail read for some players it occurs in an error: https://pastebin.com/tWui0iey

**Cmi Version (using`/cmi version`):** 

[10:37:02 INFO]: CMI: 8.7.8.4 BungeeCord  MySQL
[10:37:02 INFO]: Server: Tuinity 1.16.3-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Should be fixed with next version
