### ISSUE TITLE
[Request] /Glow command expansion.

### ISSUE THREAD

**Issue by DutchUser** [Zrips/CMI#442]
Hello.

Could the Glow effect can be expanded with the next option?
- Add an option in the config to enable or disable that you can the player through blocks if he is glowed.

**Comment by TheWranger** [comment]
Wouldn't something like this be pretty performance heavy to do?
There's no way to do this in vanilla as far as I know.

**Comment by Zrips** [comment]
That would require constant check for blocks between each two players and then manipulate glow effect with packets. So yea, not really and option i would want to invest time in trying to implement it.

**Comment by LogGits** [comment]
Could a CMI portal be used to do this (run a command)?
