### ISSUE TITLE
Tab complete for CustomAlias

### ISSUE THREAD

**Issue by hamcoremusic** [Zrips/CMI#4421]
**Question: **
I am wondering if there is a way to carry over a tab complete for an alias.

For instance, if I make `h` work as `home`, is there a way to bring up home names in the tab completion?

Thanks!

**Comment by CloudeLecaw** [comment]
if you design it with custom alias then it works like that

**Comment by hamcoremusic** [comment]
Ah the variable placement makes sense. Thank you very much!
