### ISSUE TITLE
If you make armorstand invisible you cant open gui or pick items

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#4422]
**Description of issue:**

If you make invisible armorstand you can´t open gui and can´t pick items (you have to kill the armorstand). 

**Cmi Version (using`/cmi version`):** 
8.7.9.0
**Server Type (Spigot/Paperspigot/etc):** 
paper 
**Server Version (using `/ver`):** 
184
**Relevant plugins (Delete if this isn't needed):**
CMI

**Comment by broken1arrow** [comment]
> /cmi armorstand near

I know the command and i get no errors. Armorstands when i make invisible it stop exist for CMI, I don´t know what cause it.

**Comment by Zrips** [comment]
As mentioned in #4432 issue, currently cant reproduce issue, could be issue with compatibility with another plugin. If you have way to test it with CMI only could help out in ruling out this one

**Comment by broken1arrow** [comment]
@Zrips  

Sry was an other plugin some use invisible armorstand to show text and he not think the plugin even look all other armorstand some are invisible some is not connected too his plugin.

Took several hours to find the plugin some cause this.
