### ISSUE TITLE
launch loc

### ISSUE THREAD

**Issue by Haczyn** [Zrips/CMI#4424]
**Description of issue:**
Command launch with loc doesnt work. just make normal launch. 
I report it because i have that problem. And i saw on discord someone have it too. 
So I've been trying to make a portal that launches a person to a determined location. I have the portal run "asConsole! cmi launch [playerName] loc:-9275:120:9806" and all it does is make me do a small hop in the direction I'm looking... Can anyone help?

**Cmi Version (using`/cmi version`):** 
CMI: 8.7.8.4 BungeeCord MySQL-> 8.7.9.0
**Server Type (Spigot/Paperspigot/etc):** 
Server: Paper(1618) 1.12.2-R0.1-SNAPSHOT
**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by CloudeLecaw** [comment]
i also noticed this that thought that is what launch may should do. so i stoped stesting arround with the launch command.
i also hoped that it launchen the player to the location like sitting in a canon. but i was wrong too about that..

or this is really a bug with launch^^

**Comment by Zrips** [comment]
That location variable only launches player to certain direction with approximate strength, i need to dig out some actual code which is responsible for players trajectory from which i could calculate how much strength and on which angle we need to launch player. Its not a bug, its just lack of feature.
