### ISSUE TITLE
portal bunge

### ISSUE THREAD

**Issue by pinuxio** [Zrips/CMI#4428]
**how do i set portals with bungecoord exactly?: **

**Comment by CloudeLecaw** [comment]
Setup a portal without output location and innthe command you use the cmi server command to send them to an other bungecord

**Comment by pinuxio** [comment]
In what command

**Comment by CloudeLecaw** [comment]
Portals will work over bungeecord network and you can teleport players across your servers. How to setup portal? It cant be simpler. Make portal, open portal UI, click on set location button and you will get message in chat box. Travel to desired location, same server or on bungee (both servers should have CMI) and click on that message. You are done. Thats it… Travel to location and click on chat. No commands, nothing. Just like that.
Portal commands will work over bungee network and will be applied after player is teleported.

**Comment by CloudeLecaw** [comment]
You mean you dont know how to open the portal ui?

**Comment by pinuxio** [comment]
I don't know how to set the portals locally, only that when I go to the other bungeecord server where I have installed cmi does not give me the command in chat, so I wanted to know if it was possible What to do exactly

**Comment by CloudeLecaw** [comment]
- use wooden shovel to mark the portal corners
- /cmi portals new Test1
-/cmi Portals edit Test1
- mark the button for set output of Portal
- teleport to your bungee server to the right location where the portal should lead
- click in chat (on the words) to set the target location

Done

**Comment by pinuxio** [comment]
but I have to create the same portal also in the destination world?

to view the chat I always use cmi

**Comment by pinuxio** [comment]
so, here I describe the procedure step by step. in the Hub I create the portal as I have always done, then I press enter and it gives me the message I do not click anything and I execute the command cmi server (servername) and I move to the server, only there it does not give me the message to set the arrival point of the portal

**Comment by CloudeLecaw** [comment]
So you had the meassge in chat allrealy to click the portal to get target location right? (after pressing the button in the gui)
then you move to the other server and fly walk or tpto the other location. - fine so long.
normaly if you press T now you still should see your old chat.... Does your chat got cleared on sending you to other hub?

**Comment by pinuxio** [comment]
The problem is that when I go to the server where I have the towny and cyclic above the yellow writing it tells me there is no portal with this name

**Comment by pinuxio** [comment]
![Immagine 2020-10-22 141002](https://user-images.githubusercontent.com/57964445/96869884-63e86780-1470-11eb-91cc-561c61947ca9.png)

**Comment by CloudeLecaw** [comment]
Portal1:  ![image](https://user-images.githubusercontent.com/12080017/96876138-5afb9400-1478-11eb-87a0-505b854a5877.png)

Now klick it.  Now you see this in chat:
![image](https://user-images.githubusercontent.com/12080017/96876250-84b4bb00-1478-11eb-8797-413575531c11.png)

Now go to your other server your traget location
![image](https://user-images.githubusercontent.com/12080017/96876847-381daf80-1479-11eb 9882-8ba9ad4b4fb2.png)

When you reached it press T you still should see your chat.
klick it.
![image](https://user-images.githubusercontent.com/12080017/96877152-93e83880-1479-11eb-9639-0813e8da85fd.png)

done.

**Comment by pinuxio** [comment]
**step 1 portal**
![step01](https://user-images.githubusercontent.com/57964445/96879871-d95a3500-147c-11eb-9dab-9c4081d18c2a.jpg)
**step 2 set portal**
![step02](https://user-images.githubusercontent.com/57964445/96879942-e9721480-147c-11eb-8801-e99cd3e03d59.jpg)

**step 3**
![step03](https://user-images.githubusercontent.com/57964445/96880084-0f97b480-147d-11eb-9051-c47a024acbb5.jpg)

**step 4 result**
![step04](https://user-images.githubusercontent.com/57964445/96880157-23dbb180-147d-11eb-90ad-448b14323b9a.jpg)

**Comment by pinuxio** [comment]
i connected the two servers with aegis which is much more secure than bungee

**Comment by CloudeLecaw** [comment]
Hm but IT Looks Like cmi dies mit Work Witz your Others Server together..you also installed the bungecorecmi Part in the Bungee parts.
?

**Comment by pinuxio** [comment]
No and to tell the truth I don't even know how to do it

**Comment by CloudeLecaw** [comment]
Without the cmibungee in wach Server Features Like Portals and snyc between the Servers will mit Work thats what the cmi Wiki sais

**Comment by pinuxio** [comment]
In which folder should I put the bongie cmi file?

**Comment by CloudeLecaw** [comment]
Into the plugins folder of your bungee servers

**Comment by pinuxio** [comment]
in the bubgee folder, in the hub folder and in the towny folder?

**Comment by CloudeLecaw** [comment]
Hmm normaly in the towny

**Comment by pinuxio** [comment]
I am attaching the log
[latest.log](https://github.com/Zrips/CMI/files/5424489/latest.log)

**Comment by pinuxio** [comment]
still the same mistake. but the plugin is:
CMIB1.0.0.0.jar?

**Comment by CloudeLecaw** [comment]
hm no it should be a bit higher 1.0.04  you get it on the cmi wiki

**Comment by pinuxio** [comment]
i solved it, just put the file ... in the main folder ie bungee.
I suggest putting it in the portal guide

**Comment by CloudeLecaw** [comment]
it should be annouced in the about while where they told how to setup bunge. i know Zrips wrote something there allready. but you see it seems to be no understandable enough in all cases :)

Good that you solved it :-)
