### ISSUE TITLE
Flight Charge

### ISSUE THREAD

**Issue by abc605521864** [Zrips/CMI#443]
**Description of issue or feature request:**

About the Flight Charge
Players in a teleport in flight will use up all their energy

**Cmi Version (using`/cmi version`):7.7.11.1

**Server Type (Spigot/Paperspigot/etc):TacoSpigot/Paperspigot

**Server Version (using `/ver`):TacoSpigot 1.12.2-R0.1-SNAPSHOT

**Comment by MCTyler** [comment]
Are you asking for this or saying this happens?

**Comment by abc605521864** [comment]
This problem has occurred

**Comment by MCTyler** [comment]
@Zrips If you do change this feature, please make it a toggle. I like it if a user tries to TP while flying that they forfeit all remaining charges they have left. It would be better to block all TP while flying but this may be difficult.
