### ISSUE TITLE
Improvement for /hat

### ISSUE THREAD

**Issue by Remski01** [Zrips/CMI#4431]
**Description of feature/improvement request:**

Add an head slot checker for /hat
---
### Detailed explanation of what it should do, when and in what situation: ###
Add something that checks if player have an helmet on or not, currently. If you have nothing on you head or no helmet and you inv is full and use /hat it says the inventory is full. (see down bellow)
### Basic explanation as to why this feature is needed and/or useful to have: ###
This makes no sense at all. It doesnt need an inventory slot if player have nothing on his head.

**Comment by Zrips** [comment]
Will fix this with next build
