### ISSUE TITLE
Cannot Edit Invisible Armorstands

### ISSUE THREAD

**Issue by orangepeelsss** [Zrips/CMI#4432]
**Description of issue:**
When you select invisible under the armorstand GUI, you can't edit the armorstand any further. 

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
ArmorStands:
    # When set to true, the plugin will check if the player can manipulate armor stand by sending fake block place event and checking if any plugin would want to prevent this action
    # This can help out to minimize the possibility for players to manipulate armor stands when they don't have build permission in an area where armorstand is standing
    CheckBlockPlace: false
```

---

**Cmi Version (using`/cmi version`):** 
8.7.8.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-209 (MC: 1.16.3)

**Comment by broken1arrow** [comment]
Hi have same experiences, no mater CMI version. I miss to update my issue, but for me it was a plugin some block the access.

Have you more plugins on your server?

https://github.com/Zrips/CMI/issues/4422?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDEyNjMwMzMyMTc6MTYzNjgyODY%3D#event-3905941343

**Comment by Zrips** [comment]
Testing without any other plugin could help out in figuring out which one creates issues. Currently i cant reproduce this issue, so some another plugin must be interfering.

**Comment by thomaboehi** [comment]
Hi.

I created an armor stand long time ago and edited it with CMI. I toggled it invisible, and since can't edit it... All my stuff is on it since then XD

If you want to give it a try on my server, I can give you the permission on a cloned server.

**Comment by Zrips** [comment]
@thomaboehi 
Have you tested on a server with only CMI present? And you do have **/cmi armorstand near** command which will select closest armor stand if you cant click on it manually.
