### ISSUE TITLE
NickChangeEvent on Listener API

### ISSUE THREAD

**Issue by Renzoez** [Zrips/CMI#4433]
Hi, 

So we are trying to catch an attribute same as NickChangeEvent on the Listener of Essentials on CMI API.
But all that we can find is NickManagerEvent and NameListener.

We need an attribute same as NickChangeEvent(essentials) on the API.

Here's some quote of the code.

`
@EventHandler
    public void onPlayerChangeNickname(NickChangeEvent event) {
        Player p = event.getAffected().getBase();
        if (p.getUniqueId().toString().equals(this.plugin.getSlayerUUIDString())) {
            this.plugin.getServer().getScheduler().runTaskLater(this.plugin, new Runnable() {
                public void run() {
                    net.indiopikaro.kiana.indiodragons.CMIListener.this.plugin.replaceArmorStand();
                }
            }, 2L);
        }
    }
`

We are currently working with CMI 8.7.9.0 version.

The server type is PaperSpigot 1.16.3.

Thanks for the help.

**Comment by Zrips** [comment]
CMIPlayerNickNameChangeEvent with next update
