### ISSUE TITLE
moneylog invalid balance

### ISSUE THREAD

**Issue by SottaByte-Ham5teak** [Zrips/CMI#4435]
**Description of issue:**
moneylog file does not log the right amount of money if the money is higher than  2.147483647E7(total)
(haven't tested the transferred amount . that might be bugged aswell)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
22/10/20 07:31:21 Skaian got 1000.0 (2.147483647E7)
22/10/20 07:31:23 Skaian got 120000.0 (2.147483647E7)
22/10/20 07:31:23 LouieG4mer lost 120000.0 (97291.14)
22/10/20 07:31:23 LouieG4mer lost 120000.0 (97291.14)
22/10/20 07:31:23 Skaian got 120000.0 (2.147483647E7)
```
I did check the sql and player had 34392312.0421875 

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/66127848/96992404-b724ed80-1536-11eb-9864-9f904f2af773.png)

**Comment by CloudeLecaw** [comment]
You should also take a look what is the higesz amount in your cmi config

**Comment by CloudeLecaw** [comment]
34392312.0421875 does not sound like a vailed value if cmis MoneyFormat is used... The default is something like xxxxx.xxx,xxxxxxx so the question is what is loged in your mysql and why? Or does this point is for the comma and the numbers behind are decimales? Then you should check that you have choosen the right Format for this in config too

**Comment by Zrips** [comment]
Will be fixed with next build
