### ISSUE TITLE
Command Feedback for /chat invite [playerName]

### ISSUE THREAD

**Issue by thomaboehi** [Zrips/CMI#4436]
**Description of feature/improvement request:**
I tought it was a problem from the french translation but when we do /chat invite [player] there is no feedback that says "You sent an invitation to [player] to join the chat [chat]."

Would be very nice 👍 
---
### Detailed explanation of what it should do, when and in what situation: ###
/chat invite [player]
**Feedback**: "[player] has been invited to the chat [chat]."

### Basic explanation as to why this feature is needed and/or useful to have: ###
Better for players, so they know the command executed well.

**Comment by mrfloris** [comment]
Yeah, would be nice.

**Comment by VimaMT** [comment]
Feedback ... good.  👍

**Comment by Zrips** [comment]
Feedback... goooooood

**Comment by mrfloris** [comment]
Excellent, chat updates today!
