### ISSUE TITLE
Home on location that was built up

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4437]
**Description of issue:**

---
Hi, when one of my player died and was teleported to home in one world that resetted, then he was teleported to blocks, because previously there were normally plains and now there were hills, so he was killed by these blocks, but I think there should be check before teleporting?

---

**Cmi Version (using`/cmi version`):** 8.7.9.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 240

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
You will need to give cmi.safeteleport for the players if you want to check for safe locations before teleporting them over there
