### ISSUE TITLE
Legacy Material Support is still initialized on 1.16.3 server

### ISSUE THREAD

**Issue by YouHaveTrouble** [Zrips/CMI#4438]
**Description of issue:**

Legacy Material Support is still initialized on 1.16.3 server. The positioning of the actual line of legacy init tells me that problem was fixed in one place, but remained in some other one. 

https://pastebin.com/PzmkT1Dh

---

**Cmi Version (using`/cmi version`):** 
8.7.9.0

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-196 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

server with CMI as only plugin and cleared plugins folder, so no old configs.

**Comment by Zrips** [comment]
Confirmed, should be up and working with next version as it should.
