### ISSUE TITLE
[Issue] CMI does not work with PremiumVanish (afk part)

### ISSUE THREAD

**Issue by DutchUser** [Zrips/CMI#444]
**Cmi Version (using`/cmi version`):** 
30.05 15:43:27 [Server] INFO Vault version: 1.5.6-b49(CMIEInjector)
30.05 15:43:27 [Server] INFO Server version: Spigot 1.12.2-R0.1-SNAPSHOT
30.05 15:43:27 [Server] INFO CMI plugin version: 7.7.11.0

Hello. As now the plugin PremiumVanish does not work correctly with CMI. 

When a player is in vanish and standing still(or use /afk) he get put into afk, with message and all. Can this be fixed? :D (Players in vanish should be ignored by the afk... part of cmi)

**Comment by MCTyler** [comment]
CMI handles it's own /Vanish. I suggest uninstalling the other Vanish plugin because it's no longer needed. It will free up some Memory and Drive Space!

**Comment by DutchUser** [comment]
I prefer PremiumVanish.

Anyway, CMI allready ignore players while vanish, only not in the afk part.

**Comment by MCTyler** [comment]
CMI Handles AFK Vanished Players just fine depending on your Perms. If you are Op or Players have over-ride, they will get notifications of Vanish AFK otherwise they will not.

**Comment by DutchUser** [comment]
No. It does it not, I just tested it again. The other player do not have OP, nor does his rank have OP.

Please dont say me that it works fine while i can see it does not work.

Just to show it does not works here is the permssion group.
https://pastebin.com/JhVuJVeV

**Comment by MCTyler** [comment]
Sry, I was saying it works fine **without** Premium Vanish. Zrips will have to look into that issue.

**Comment by MCTyler** [comment]
Here is Video Proof CMI works fine...
https://youtu.be/_mxX4B5OEDU

**Comment by MCTyler** [comment]
<iframe width="560" height="315" src="https://www.youtube.com/embed/_mxX4B5OEDU" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

**Comment by DutchUser** [comment]
https://postimg.cc/image/r98f38ebb/

**Comment by MCTyler** [comment]
Like I said, It's the Premium Vanish Plugin issue. (We do not need any more proof) As you can see in my video CMI vanish AFK settings by itself is fine. Zrips will need to address this.

**Comment by DutchUser** [comment]
Did i say that the CMI Vanish part itzelf is broken? No. I did not say that, i said that CMI is not %100 working with PremiumVanish... 

"Hello. As now the plugin **PremiumVanish does not work correctly with CMI**.

When a player is in vanish and standing still(or use /afk) he get put into afk, with message and all. Can this be fixed? :D (Players in vanish should be ignored by the afk... part of cmi)"

Please read it better next time. 

Anyway, yes Zrips should look into this... Also because its only the afk part what does not work with PV, all other things works fine, (vanish related things)

**Comment by LogGits** [comment]
@DutchUser I think the easiest option would be to get the PremiumVanish developer to hook into CMI and use the various shift events to cancel the afk. It's very easy to utilise CMI's:
- CMIAfkEnterEvent
- CMIAfkLeaveEvent
- CMIAfkKickEvent

Ask him if he can add support for cmi using the above listed events 👍

**Comment by tmellen** [comment]
Turn of the AFK msg from being announced?

**Comment by DutchUser** [comment]
How does this fix it? I do want to use the afk message, but as LogGits allready said, i asked the dev of PV if he can hook into CMI. (No respons so far)

**Comment by mercurialmusic** [comment]
The PremiumVanish dev fixed this on his end. Should be safe to close.

**Comment by DutchUser** [comment]
Meh, not fully. The player get ignored by the auto afk, yes. But when he do /afk players still see that he went into afk. I know its a small detail. But can this maybe be fixed please?

**Comment by DutchUser** [comment]
Closed, not important enough, its fixed in the autoafk.
