### ISSUE TITLE
last Version of CMI 8.7.9.0 breaks Redprotect Permission 

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4440]
Since we updated to CMI 8.7.9.0 e noticed it blocks our owners from creating regions with Redprotect.
When we went back to CMI 8.7.8.4 All work fine. So something in the Update from 8.7.8.4 to CMI 8.7.9.0 breaks it
With breaking i mean that Admins habe no permissions anymore to create manage or delet zones..

`https://www.spigotmc.org/resources/redprotect-anti-grief-server-protection-region-management-1-7-1-16.15841/`

![image](https://user-images.githubusercontent.com/12080017/97039584-f5d59a80-156c-11eb-8294-5e2789242212.png)
This line comes from CMI

**Comment by Zrips** [comment]
If this line comes from CMI then it would mean that CMI performed some command. Is this an alias? From where does it originate?

**Comment by CloudeLecaw** [comment]
well you where where it was preformed from an aliias... shame on me 🥉 
The alias was there since months but it never worked...now it works since your last fix of 8.7.9.0
Sorry for the confusion
