### ISSUE TITLE
Show playtime in /info command

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4441]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, I wanna to suggest you adding playtime to /info command.
### Basic explanation as to why this feature is needed and/or useful to have: ###
I think that it's also basic information about player and it could be included there.

**Comment by Zrips** [comment]
You can see players playtime while hovering over his name in output message
