### ISSUE TITLE
Critital error on start : cmi colums deleted

### ISSUE THREAD

**Issue by RSLuke** [Zrips/CMI#4442]
**Description of issue:**

On update, 3 columns were deleted, the server couldn't start, I had to manually add these columns.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[20:07:48 WARN]: java.sql.SQLException: Column 'ToggleBBCompassOff' not found.
[20:07:48 WARN]: java.sql.SQLException: Column 'DisplayName' not found.
[20:07:48 WARN]: java.sql.SQLException: Column 'AFRecharge' not found.
```

---

**Cmi Version (using`/cmi version`):** 8.7.9.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.13.2 Paper

**Comment by Getblock** [comment]
Encountered this issue also, Mine started however all the data that was processed during the uptime was not saved into the database due to database errors.

Updated from: 8.7.6.7 to 8.7.9.0

Server version: 1.16.3 paper

**Comment by Zrips** [comment]
In general that was no changes in the last updates relating to those columns. So something else went wrong. Was there any actual errors during startup or during work time which would be related to database? And just to make sure, both of you running mysql database type?

**Comment by Getblock** [comment]
Hello, this part here is when it started throwing off errors in startup: https://pastebin.com/idCZwP3i

I am running MySQL database type

**Comment by Zrips** [comment]
@Getblock 
By any chance you have exact database type and version?

**Comment by Zrips** [comment]
In any case, did some digging around the code responsible in detecting if column already exists, added some completely new checks which should resolve this issue once and for all.

**Comment by Getblock** [comment]
mysql  Ver 15.1 Distrib 10.3.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2


The issue seems to persist even after version update posted in spigotmc

**Comment by Zrips** [comment]
@Getblock 
Do you experience same errors as before or they are different ones?

**Comment by Getblock** [comment]
@Zrips This a new and additional error on top of the one i sent earlier

https://pastebin.com/f6zRC4wu

**Comment by RSLuke** [comment]
my db : 10.1.47 (10.1.47-MariaDB-0+deb9u1)

**Comment by Getblock** [comment]
The CMI_users table was created on an older version of MariaDB and was using the COMPACT row format instead of DYNAMIC, which became the default in MariaDB 10.2

Changing the row format fixed the startup error: alter table CMI_users ROW_FORMAT=DYNAMIC;

This has resolved the issue for me
