### ISSUE TITLE
Warmups don't work on 8.7.9.0

### ISSUE THREAD

**Issue by RSLuke** [Zrips/CMI#4443]
**Description of issue:**

Warmups just stopped working on 8.7.9.0

---

**Cmi Version (using`/cmi version`):** 8.7.9.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.13.2

**Comment by RSLuke** [comment]
Edit : Doesn't work in 1.16.3 Paper as well

**Comment by Zrips** [comment]
Confirmed, will be fixed with next update

**Comment by SmallSansSerif** [comment]
I'm having problems with command warmups and warmups on command aliases on the latest CMI version 8.7.9.1 running on Paper/Tuinity 1.16.3

Home seems to work but **spawn** and warps don't.

  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: false
  showBossBarInfo: false
  List:
  - cmi tp :3:false:GlyphHead
  - cmi back:3:false:GlyphHead
  - cmi warp :3:false:GlyphHead
  - cmi home :3:false:GlyphHead
  - cmi spawn:3:false:GlyphHead
  - resource:3:false:GlyphHead
  - crates:3:false:GlyphHead
  - nresource:3:false:GlyphHead
  - market:3:false:GlyphHead
  - shop:3:false:GlyphHead
  - shops:3:false:GlyphHead
  - store:3:false:GlyphHead
  - pvp:3:false:GlyphHead
