### ISSUE TITLE
[Issue] Cooldowns I have don't work with aliases I have set for the commands I set the cooldown to.

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#4445]
**Description of issue:**
Below, I pasted both the config section of "Cooldowns:" as well as the "/feed" alias from the Alias.yml file. The description of the issue is, if I directly do "/cmi feed" and there is a cooldown in place for it, and do it again right after (before the cooldown ends) the cooldown will stop me from doing it again. I noticed if I try to do "/feed" which is an alias of "/cmi feed" it will not register the cooldown for it and I can spam it as much as I want. Just to summarize what I just said, directly doing "/cmi feed" (while having a cooldown for it) does have a cooldown but doing the alias for it (/feed) doesn't register it having a cooldown for some reason. I don't understand why, or how.. It may be a configuration issue, though I don't think I had this issue before the latest update. I don't know how this could even be an issue, as I think all the command "/feed" does is make you execute "/cmi feed". Let me know if I misconfigured something or just generally messed up. Thanks

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
 - https://pastebin.com/jgHbBrVY https://pastebin.com/1bDBAL1q
```

---

**Cmi Version (using`/cmi version`):** 
https://pastebin.com/vyDUNM8w
**Server Type (Spigot/Paperspigot/etc):** 
Purpur -) Fork of PaperSpigot
**Server Version (using `/ver`):** 
https://pastebin.com/xQWNmt99
**Relevant plugins (Delete if this isn't needed):**
CMI, CMIPaperlib

**Comment by Zrips** [comment]
Confirmed, should be resolved with next build
