### ISSUE TITLE
Sponge Port

### ISSUE THREAD

**Issue by jettrainz** [Zrips/CMI#4446]
I have been using CMI for a while now and I absolutely love it. It is a very well written plugin and the migration from essentials was seamless...this is sounding more like a review...

I would like to see a Sponge version of CMI, as I have started up a modded server and the only "essentials" plugin out there is Nucleus. Nucleus is not a bad plugin, but I personally like CMI better.

**Comment by CloudeLecaw** [comment]
this will not be happen^^
