### ISSUE TITLE
Toggle shift edit not working for non-OPs

### ISSUE THREAD

**Issue by ghost** [Zrips/CMI#445]
Hi there, I just gave a permission for my player, permission name is : cmi.signs.shiftedit,
he could do the command, but yet he can't edit any signs. He is in his own Residence, and I even tried giving him cmi.signs.shifteditbypass. Nothing worked. But when I do, i can shift click signs easily. Is there something I'm doing wrong?

**Cmi Version (using`/cmi version`):**  7.7.10.1

**Server Type (Spigot/Paperspigot/etc):**  paperspigot 1416

**Server Version (using `/ver`):** 1.12.2

**Comment by LogGits** [comment]
Give the permission for `cmi.command.toggleshiftedit` this allows the user to toggle shiftedit on and off, essential to allow for building with signs. The command they would use is `/cmi toggleshiftedit` or `/toggleshiftedit` if you have the alias.yml file setup correctly.

**Comment by MCTyler** [comment]
@LogGits I Added cmi.command.toggleshiftedit to Permission Wiki on Spigot....That Permission file needs some work, it's all out of alphabetical order. I'll try if I can find time.

**Comment by Blackdigits** [comment]
Hi there, the problem seems to still be here. The player has the permission cmi.command.toggleshiftedit already, and when he typed /cmi toggleshiftedit, it says Enabled shift sign editing. But he still can't edit any signs. I gave him OP after, and with toggleshiftedit enabled, it works

**Comment by Blackdigits** [comment]
@MCTyler @LogGits Bump. Sorry

**Comment by MCTyler** [comment]
I was just editing the Wiki, I did't fix your error, Sry :D

**Comment by Blackdigits** [comment]
Who could fix the error? :') @MCTyler

**Comment by MCTyler** [comment]
@LogGits @Zrips

**Comment by Blackdigits** [comment]
Bump! Sorry for bumping @LogGits @Zrips

**Comment by xion87** [comment]
It not working also for ops. Paperspigot 1.12.2 and latest CMI
it trow this error when i try to edit the sign
https://gist.github.com/xion87/412a956a1b2d8e5af3eca9479ccc2f01

**Comment by LogGits** [comment]
If i recall correctly this was fixed a while back versions. If not, please reopen an issue.
