### ISSUE TITLE
'Player' Mobs getting stuck on tablist

### ISSUE THREAD

**Issue by daoshii** [Zrips/CMI#4451]
**Description of issue:**

Most 'player' mobs are getting removed from tablist but occasionally some are getting stuck on there, People who play for a few hours slowly see the list build up even more even though the mob is already dead it still doesn't get removed.
---

---

**Cmi Version (using`/cmi version`):** 8.7.9.0

**Server Type (Spigot/Paperspigot/etc):**  paper 223 1.16.3

**Relevant plugins (Delete if this isn't needed):** No other tab plugins

**Comment by Zrips** [comment]
No idea about what type of mobs you are talking here or which place exactly. Some actual examples would be nice to have, pictures would be even better.

**Comment by daoshii** [comment]
Its a mob disguised as a player..
And theyre being added to the tablist.
Like how NPCs can be disguised as a player.

Normally, The plugin removes anything disguised as a player thats not a real player. However occasionally it is not removing an NPC thats disguised as a player, or a mob that's disguised as a player. It doesn't matter what type of mob it is, It could be a Zombie disguised as a player, Or a chicken disguised as a player.

As far as Citizens NPCs go, I have no idea what they originally are, a villager, an armor stand?

**Comment by Zrips** [comment]
CMI doesn't modify contents of tablist, atleast not a list itself. it can change header or footer, change player look shown in tablist, but it will not add new ones or remove anyone from it at this moment. If you have plugin which creates fake players with packets or throw direct approach then it might fail to remove all of them from tablist. You might want to check Citizens plugin github and report this issue.
