### ISSUE TITLE
CMI incompatible/breaks Spartan Anticheat

### ISSUE THREAD

**Issue by Abstract-Programming** [Zrips/CMI#4452]
**Description of issue:**
CMI breaks Spartan Anticheat by sometimes causing the player to receive significantly more false positives and will even kick them. It also prevents proper user checks for some hacks. 

My ops have been testing this to get a more detailed report, however, we believe it's due to certain CMI player checks.

I have also heard that there are some issues with CMI interfering with some other anti-cheat plugins.

Is this a known issue? If so are there any intentions to resolve it (by being able to disable CMI checks or otherwise)?

---

**Cmi Version (using`/cmi version`): 8.7.9.1** 

**Server Type (Spigot/Paperspigot/etc): Paper build 299** 

**Server Version (using `/ver`): 1.16.3** 

**Relevant plugins (Delete if this isn't needed): Spartan Anticheat build 370**

**Comment by Zrips** [comment]
Anticheat plugins are complicated by its nature already. CMI does in some situations extra checks by triggering some events which could be looked as some invalid actions, but... Those events need to be fired. One of the examples would be editing armor stands with GUI which fires 2 events which checks if player can actually modify this armor stand which could be protected by some protection plugin. So firing up some events gets us information about player being able to modify this armor stand in this specific area. Another example would be with sign edit, block place event is fire before opening UI which ensures that player have right to place signs in this area.
Its not a bug from CMI in particular, its issue with compatibility with plugins which are picky with events which are fired in some unusual situations even tho those dint originated from hacked clients. 
Issue is not really well known as i cant really see reports about issue with anti cheat plugins.

**Comment by Abstract-Programming** [comment]
Ok, that makes sense. Would it be possible if it is not already to disable functions of CMI? Like being able to disable the armor stands among other things? (or allowing players to toggle the compass)
