### ISSUE TITLE
small tweak to the /afkcheck commands locale.

### ISSUE THREAD

**Issue by Remski01** [Zrips/CMI#4453]
### Detailed explanation of what it should do, when and in what situation: ###
Have an seprate line for `/afkcheck <player>` and `/afkcheck all` Currently the first uses the line `feedback:` where the second uses `feedbackList:` and then `feedback:`, as face value it looks fine, hoewever. This way have an flaw where if you want lines to have prefixes sich as`[CMI]` its inpossible to have it here. because adding an prefix to `feedback:` breaks the `feedbacklist:`, but adding an prefix to `feedbackline` doesnt show the prefix when using just `/afkcheck <player>` as it then only show `feedback:`. This could be fixed adding something like `playerfeedback` for when using `/afkcheck <player>`.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Because the currently way have a flaw where the fix should be easy to be added and shouldnt be too much work.

**Comment by Remski01** [comment]
Have an other one related to `/cmi afkcheck all`, add an line that shows when no player is afk, as it currently just returns zero/nothing what is confussing.

**Comment by Zrips** [comment]
Ok. Next update
