### ISSUE TITLE
Combat Timer breaks PvPManager

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#4454]
Out of the blue a random "Combat Timer" appeared on my server. It appears to be CMI that added this, stopping PvPManager from displaying its combat tagged information in hotbar.

How do I fully disable your Combat system? I want to use PvPManager?

**Comment by Zrips** [comment]
Config file-> Combat-> Mob-> ShowBossBar
Config file-> Combat-> Player-> ShowBossBar
CMI uses its own combat racking methods and should not have anything in common with PvPManager
