### ISSUE TITLE
[Question] Is there a permission to give players to allow them to teleport with their rides?

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#4455]
**Question: **
Is there a permissions to give players to allow them to teleport with their rides? I looked through the cmi permissions and couldn't find anything, I could've just missed it. As, currently when I teleport with my ride and am a default player it seems that I need some permission as it works fine when I have the "*" perm.

**Comment by CloudeLecaw** [comment]
yes

**Comment by Zrips** [comment]
You can use **/cmi checkperm teleport** to check for permissions relating to teleport. cmi.teleport.with.[entitytype]
