### ISSUE TITLE
Custom alieses with spaces what's permission?

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4457]
**Question: **
Hi, when I have custom alias:
```
  sell all:
    Cmds:
    - asPlayer! cmi sell all
    Perm: true
```
What's permission for it? I tried: cmi.customalias.sell.all, cmi.customalias.sell_all, cmi.customalias.sell all and nothing worked....

**Comment by Volgeop** [comment]
Ok sorry, it was sellall

**Comment by CloudeLecaw** [comment]
In a customalias the best is you defined the permission
With perm:cmi.commamd.customalias.yourwishpermission! 
Well it also can be cmi.wishpermission! but i recomment the longer one. If you define it with the longer way then you know exactlY what this permissions is for when you set it up
