### ISSUE TITLE
Cant set nickname to anything

### ISSUE THREAD

**Issue by FoxWithSox** [Zrips/CMI#4458]
**Description of issue:**
When a player sets their nickname to anything it changes their nickname to CMIPlayerNickNameChangeEvent

---

**Cmi Version (using`/cmi version`):**  CMI version 8.7.9.1

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):**  CraftBukkit version git-Spigot-57bbdd8-55a78ff (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
![image](https://user-images.githubusercontent.com/25159633/97098792-7c66a680-1657-11eb-91aa-be704d75d441.png)

**Comment by Zrips** [comment]
Fixed
