### ISSUE TITLE
Warmups got broken after update

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#4459]
**After updating to 8.7.9.1 all warmups dissapeared when players run /spawn /warp /home commands. Warmups still work if they use UI to select home or warp.**

---

**Cmi Version (using`/cmi version`): 8.7.9.1** 

**Server Type (Spigot/Paperspigot/etc): Purpur 1.16.3-R0.1-SNAPSHOT** 

**Server Version (using `/ver`): git-Purpur-796**

**Comment by RSLuke** [comment]
Same issue here

**Comment by Zrips** [comment]
Should be fixed with next update
