### ISSUE TITLE
/more error

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#446]
**Description of issue or feature request:**
If a number is defined when using /more, instead of setting the current item in hand to that defined amount, it will generate a new item.
Result of '/more 3'
![image](https://user-images.githubusercontent.com/24642838/40851733-9f5e2090-660b-11e8-959f-87efd0e9e2fc.png)
![image](https://user-images.githubusercontent.com/24642838/40851768-b5276e0e-660b-11e8-96fe-876292650eb7.png)

**Cmi Version (using`/cmi version`):** 
7.7.11.1
**Server Version (using `/ver`):** 
Paperspigot 1431 (1.12.2)

**Comment by Zrips** [comment]
Issue with none stackable items. Will make some basic work around this one.
