### ISSUE TITLE
Combat mode bar when player hits any mob

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#4460]
**Bossbar "Combat mode" appears for a while when player hits any mob while this function is disabled.**

---

**Cmi Version (using`/cmi version`): 8.7.9.1** 

**Server Type (Spigot/Paperspigot/etc): Purpur 1.16.3-R0.1-SNAPSHOT** 

**Server Version (using `/ver`): git-Purpur-796** 

UPD:
Seems like this one has some conflicts with PvPManager plugin.

**Comment by Zrips** [comment]
You need to disable bossbar in Combat->Mob->ShowBossBar section if you don't want to see it. And there cant really be a conflict with PvPManager as CMI doesn't use it in any shape or form.
