### ISSUE TITLE
/tp /tpo /tphere do not tabcomplete without cmi.command.tp.others

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#4463]
**/tp /tpo /tphere do not tabcomplete without cmi.command.tp.others (and I don't want some staff to be able to teleport players to each other)**

---

**Cmi Version (using`/cmi version`): 8.7.9.1** 

**Server Type (Spigot/Paperspigot/etc): Purpur 1.16.3-R0.1-SNAPSHOT** 

**Server Version (using `/ver`): git-Purpur-796**

**Comment by Zrips** [comment]
Confirmed, will get fix with next build
