### ISSUE TITLE
Baltop playernames not showing if not connected

### ISSUE THREAD

**Issue by RSLuke** [Zrips/CMI#4464]
**Description of issue:**

In /baltop, only names from players that have connected are shown, otherwise it's only their balance without a name

---

**Cmi Version (using`/cmi version`):**  CMI8.7.9.1

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.13.2

**Comment by Zrips** [comment]
Same issue relating to database Column being none null value but empty field. Should be fixed with next version.
