### ISSUE TITLE
Some names don't appear in connexion messages

### ISSUE THREAD

**Issue by RSLuke** [Zrips/CMI#4465]
**Description of issue:**

Randomly some name don't display when the players connect to the server. Maybe players who have a nickname ?

---

**Cmi Version (using`/cmi version`):**  CMI8.7.9.1

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.13.2

**Comment by Zrips** [comment]
Are we talking about custom join message here?

**Comment by RSLuke** [comment]
Yes, it always worked until now but it's only 1 player out of ten, and the message is shown but not the username so maybe this is the same problem I reported with nicknames ?

**Comment by Zrips** [comment]
So place in text which should contain username shows as empty while rest of the text appears normally?

**Comment by Zrips** [comment]
Tho this might be related to your previous issue with database, players display name could have been set to empty field in database and i need to consider this option when displaying players display name. Should be working correctly with next version.
