### ISSUE TITLE
Alias editor question (or chat request)

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#447]
Just getting a bit lost in the alias editor and I'm not sure if it will even work for this.

So for cmi chat you have /msg but it doesnt cover /tell /whisper or /w. So is there a way to add all of them in the alias editor? I tried doing:

/cmi aliaseditor new tell-cmi msg $1-

So that covered /tell but now I can't add /whisper or /w to the alias editor

**Comment by mercurialmusic** [comment]
You can manually add these to the customalias.yml:

whisper:
  - cmi msg $1- (actually you might want "$$1" - https://bukkit.gamepedia.com/Commands.yml)
