### ISSUE TITLE
Option to turn off the combat modus related things.

### ISSUE THREAD

**Issue by Remski01** [Zrips/CMI#4470]
### Detailed explanation of what it should do, when and in what situation: ###

Add an option in the config or modules to turn off the combat modus related stuff.

### Basic explanation as to why this feature is needed and/or useful to have: ###

Because we dont need and dont want it, also think an option to turn it off would make others who have the same issue happy.

If this is allready a option, where can we disable it.

**Comment by Zrips** [comment]
Everything is located in config file under Combat section, simply set everything to false and you are good to go. I did changed default values to be disabled by default as it seams to be some what common issue.

**Comment by Remski01** [comment]
I'm talking about the bossbar thing, it will show up.

https://i.postimg.cc/3NDpyFqz/2020-10-25-15-35-24.png

**Comment by Remski01** [comment]
@Zrips
