### ISSUE TITLE
Question about "/near"

### ISSUE THREAD

**Issue by Remski01** [Zrips/CMI#4471]
**Question: **
Was trying to look for the setting for the max distance, noticed the permission node info said there is one. But Cant find it anywhere... Where is it?

**Comment by Zrips** [comment]
Suggestion would be to use checkperm command in case you are looking for some permission node like **/cmi checkperm near** which returns results and includes **cmi.command.near.max.[blocks]**

**Comment by Remski01** [comment]
Looks to be an Luckperms issue then... Might come back to this if it itsnt.
