### ISSUE TITLE
Clear command, delete item with lore and name. 

### ISSUE THREAD

**Issue by WolverStones** [Zrips/CMI#4472]
**Question: **

Hello, I have a question for the /clear command if I want to delete only a certain item, for example coal, so I use `/cmi clear coal:2` which deletes 2 coal, but it can be done so that it will only delete an item that has some lore and name?

**Comment by CloudeLecaw** [comment]
clear (playerName) (item(-amount)) (-s) (+clearType)


you see this does not support names or lores at the moment just vanilla items

**Comment by CloudeLecaw** [comment]
may u can create a feature request for this :)  the idea itself is good to clear an item with unwanted name or lore or enchant in some situations

**Comment by CloudeLecaw** [comment]
ah i see you did allready ^^^
https://github.com/Zrips/CMI/issues/4481
