### ISSUE TITLE
Tab completion in commands where it shouldn't be

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4473]
**Description of issue:**

---

Hi, since one update, I don't remember from which one exactly, but it's month ago... there was a "bug" that CMI started overwriting specialzied crates tab completion from some reason. It was when you changed something related to this. Here is image, when I type /scrates command, previously it suggested me normally their tab completions, but now CMI overwrites it.... https://imgur.com/3jE7Oao

---

**Cmi Version (using`/cmi version`):** 8.7.9.1

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 240

**Relevant plugins (Delete if this isn't needed):** SpecializedCrates

**Comment by Zrips** [comment]
Tested with latest SpecializedCrates plugin, tab complete works as it should. You might want to double check if you dont have any custom alias created which could interfere with tab complete or test it on a test server with default config files.

**Comment by Volgeop** [comment]
Maybe it's due to
  sell ?:
    Cmds:
    - asPlayer! cmi sell gui

Or what could be wrong in custom aliases?

**Comment by Volgeop** [comment]
It happens probably after /cmi reload.

**Comment by Zrips** [comment]
Tried /cmi reload and tried server reload, still works properly. Could you try testing this with CMI and SpecializedCrates only to make sure its not a issue with another plugin interfering?

**Comment by bobhenl** [comment]
OH, you have to enable @Zrips . It's due to /scrates has also /sc sub alias, but when I use /scrates, it prob. shouldn't give me list of CMI commands, when it's not just /sc, or?
```
  # /cmi sc $1-
  /sc: true
```

**Comment by bobhenl** [comment]
Solved cause you've added way to enable or disable tab in alias.yml.
