### ISSUE TITLE
Players can get above nether roof

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4478]
**Description of issue:**

---
Hi, I wanna report that my players found way to get above nether roof. All they need is to place cobblestone (or any block) on Bedrock and then walk on it... without touching bedrock they won't be teleported, do you think that you could somehow prevent it please?
![2020-10-25_22 58 12](https://user-images.githubusercontent.com/18662086/97120171-9ebef980-1715-11eb-89af-8483cfcbb413.png)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  # Will teleport players down from nether 'roof'
  PreventPlayersOnNetherRoof: true
```

---

**Cmi Version (using`/cmi version`):** 8.7.9.3

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 240

**Comment by CloudeLecaw** [comment]
Why not simply reduce the build high of nether to 128 to prevent this?

**Comment by Zrips** [comment]
Did some testing, cant really remain on top of nether roof, if you have this option enabled player gets teleported down if possible. You might want to set spawn point with **/cmi setspawn** just as backup location where player gets teleported in case we cant find any valid location underneath them.

**Comment by Volgeop** [comment]
https://streamable.com/cfrtlz here is video, I tried it using /back and somehow place blocks under me.

**Comment by CloudeLecaw** [comment]
u saw what haooebd when you tried to move? 😜
