### ISSUE TITLE
BlockLocker/QuickShop modifications with /se

### ISSUE THREAD

**Issue by thomaboehi** [Zrips/CMI#4479]
**Description of issue:**
Player that have the cmi.command.se permission can modify QuickShop's signs and BlockLocker's signs. QuickShop is not that an issue but BlockLocker is really bad.

And another issue with the signs:
players that have the permission `cmi.signs.shiftedit` set to false can still edit signs with juste a right click, no shift.

---

**Cmi Version (using`/cmi version`):** 
8.7.9.3 
**Server Type (Spigot/Paperspigot/etc):** 
PaperMC
**Server Version (using `/ver`):** 
1.16.3
**Relevant plugins (Delete if this isn't needed):**
QuickShop Reremake https://www.spigotmc.org/resources/quickshop-reremake-1-16-ready-say-hello-with-rgb.62575/updates
BlockLocker https://www.spigotmc.org/resources/blocklocker.3268/

**Comment by Zrips** [comment]
CMI only allows sign editing when you shift+right click, if you can edit signs with only right clicks this will not be a CMI feature.
Will make some changes relating to /se command and shift clicking which should resolve your issue if those plugins properly checks SignChangeEvent. Next update

**Comment by rockitseven** [comment]
I was wondering if this was fixed? I currently have the same problem, but don't want to negate the sign edit permission as our players love it!
