### ISSUE TITLE
/recipe something doesn't show NBT in ingredients (special names, lores etc.)

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4482]
**Description of issue:**

---
Hi, when you use /recipe something and there are special items needed for crafting special items, so for ex. when you use Magic you need apprentice helmet  (leather helmet, but in /recipe it's shown as normal leather helmet, not with special name), but result item is normally shown with special name.... Why aren't ingredients shown with special naems too?  A lot of player is then a little bit disappointed cause there are more special crafting recipes, from Slimefun etc. and there aren't any special names, lores and nbt in ingredients so they that recipe doesn't work.

---

**Cmi Version (using`/cmi version`):** 8.7.9.3

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 246

**Relevant plugins (Delete if this isn't needed):** for ex. Slimefun and it's addons, Magic, Boss Land etc.

**Comment by CloudeLecaw** [comment]
This is no issues
its still a not existing feature
we asked for this a few times now and the answer was everytime "no just vanilla items as ingredients for the moment"

**Comment by Volgeop** [comment]
Maybe could be finally changed? Because imagine that there are bunch of Slimefun addons and other plugins and it's disappointing then.

**Comment by CloudeLecaw** [comment]
https://github.com/Zrips/CMI/issues/1825

**Comment by Volgeop** [comment]
But as I see the issue is old one year, maybe this year we can do this 😅

**Comment by CloudeLecaw** [comment]
but  it is still no bug report its a feature request ;)

**Comment by Zrips** [comment]
Duplicate
