### ISSUE TITLE
Custom alias is activated for random player, why?

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4483]
**Question: **
Hi, why when I type just "cletani", then thy tfly is activated for random player in console? Or IDK for which one, but it's activated for someone else than those who executed it.
```
  cletanimod:
    Cmds:
    - asConsole! ptarget:$1! cooldown:1?# cmi tfly $1 5m -s
    - asConsole! ptarget:$1! cmi ctellraw $1 <T>&c&lRádce &f» &fBylo ti aktivováno
      &emoderátorské létání &fpo dobu &e5 min&f. Aktivuj opětovným použitím.</T>
    Perm: true

```

All I want is, when they don't specify there name and they type just "cletani" (in english it's timed fly for 5m), then it will be given to this person who executed it, not for the random one.

**Comment by CloudeLecaw** [comment]
because you have not set a permission for it
so add a requested permission befiore you first line like
```
  cletanimod:
    Cmds:
    - perm:cmi.command.costumalias.cletanimod#! asConsole! ptarget:$1! cooldown:1?# cmi tfly $1 5m -s
    - asConsole! ptarget:$1! cmi ctellraw $1 <T>&c&lRádce &f» &fBylo ti aktivováno
      &emoderátorské létání &fpo dobu &e5 min&f. Aktivuj opětovným použitím.</T>
```
in your example you execute a command as console without adding a request permission
the # behin this check above chancel all after until the end of the alias if player does not have the permission

**Comment by broken1arrow** [comment]
> because you have not set a permission for it and execute cosnole commands after (the console allways has all permission)
> setting perm: true via the custom alias editor does not really work like that.
> What works is a requested permission befiore you first line and cancel all actions if condition is not true like
> 
> ```
>   cletanimod:
>     Cmds:
>     - perm:cmi.command.costumalias.cletanimod#! asConsole! ptarget:$1! cooldown:1?# cmi tfly $1 5m -s
>     - asConsole! ptarget:$1! cmi ctellraw $1 <T>&c&lRádce &f» &fBylo ti aktivováno
>       &emoderátorské létání &fpo dobu &e5 min&f. Aktivuj opětovným použitím.</T>
> ```
> 
> the # behin this check above, cancel all after it until the end of the custom alias if player does not have the permission
> Innyour custom alias you settet perm true.. I never used this in a customalias so i cant tell you if this even works for custom alias...
> Also the wiki does not mention about this. Did you copied this may from interactive commands?
> 
> Here u find the basics for custom alais
> https://www.zrips.net/cmi/commands/custom-alias/

Is not how it work CloudeLecaw , check how it work ingame. It is how  Perm: true work and you have to give players cmi.command.costumalias.cletanimod or what your commands name is, like this cmi.command.costumalias."random command name".

Way is not stand in wiki, is for the plugin make this line auto and is explained ingame how this perm work. 

And he ask way one player activates and another player get tfly instead and if it not what he mean, 
so it's probably a bug that prevents perms from working on custom aliases.

**Comment by CloudeLecaw** [comment]
asConsole! ptarget:$1! this does not work from ingame only from console directly

> ptarget:[name]! is special variable only usable from console. This will use target player when replacing placeholders or checking conditions. In example, having custom alias like /givehomes with command as 
> 
> ptarget:$1! lp user $1 permission set cmi.command.sethome.%cmi_equationint_{cmi_user_maxperm_cmi.command.sethome_1}+1%
> then you can use /givehomes Zrips from console to perform command which will add new permission node for a Zrips by those particular placeholders. In this case it will increase max home limit by one.

**Comment by broken1arrow** [comment]
> asConsole! is nonsense combined with ptarget:$1! this does not work from ingame only from console directly
> what the user tries he is to execute a command asConsole and use ptarget
> The ptarget is also not needed for the commands he execute
> 
> and here is the problem
> 
> pasted from wiki:
> 
> > If command starts with asConsole! then command will be performed from console. This can be used in ares like customAlias which by default performs commands like player if not defined specifically to be performed as console.
> 
> > ptarget:[name]! is special variable only usable from console. This will use target player when replacing placeholders or checking conditions. In example, having custom alias like /givehomes with command as
> > ptarget:$1! lp user $1 permission set cmi.command.sethome.%cmi_equationint_{cmi_user_maxperm_cmi.command.sethome_1}+1%
> > then you can use /givehomes Zrips from console to perform command which will add new permission node for a Zrips by those particular placeholders. In this case it will increase max home limit by one.
> 
> what he should try is remove the asConsole and try the command from console directly
> for the alias i recomment to remove the ptarget ompletly as its not needed in this case
> Also i suggest exchange the 5m and make is secounds -> 300 secounds
> **tfly [playerName] (timeInSec) (-s)**
> What about the cooldown?.. cooldown:1?# this menas if the cooldown is not 1 (1 secounds?) then break it up...
> 
> ```
>   cletanimod:
>     Cmds:
>     - asConsole! cooldown:1?# cmi tfly $1 300 -s
>     - asConsole! cmi ctellraw $1 <T>&c&lRádce &f» &fBylo ti aktivováno &emoderátorské létání &fpo dobu &e5 min&f. Aktivuj opětovným použitím.</T>
>     Perm: true
> ```
> 
> then he can use it ingame

I think he need use [playername] or fakeOP! for it work.

**Comment by CloudeLecaw** [comment]
`If command starts with asFakeOp! command will get performed as a player who has OP. This is slightly different then asConsole! as you will not receive any feedback message and server will process command like it was done by real player. **Keep in mind that this will not perform as player who initialized command, but as completely different fake OP player.**`
this would work with $1 but not with fake op. but the commands he use can be used asConsole! without any problem too

well i forgot the ! in the cooldown where he forogt the end of each condition the !
  cletanimod:
    Cmds:
    - asConsole! cooldown:1?#! cmi tfly $1 300 -s
    - asConsole! cmi ctellraw $1 <T>&c&lRádce &f» &fBylo ti aktivováno &emoderátorské létání &fpo dobu &e5 min&f. Aktivuj opětovným použitím.</T>
    Perm: true

**Comment by Volgeop** [comment]
Even when I use your the latest example, then fly is activated for random player when don't specify nickname....

**Comment by broken1arrow** [comment]
> Even when I use your the latest example, then fly is activated for random player when don't specify nickname.... SO when I use just /cletanimod, then it's activated for one of the players, not me. I wanna if I don't specify player name (because it sometimes happens to moderators) to activate fly for me.
> 
> ```
>   cletanimod:
>     Cmds:
>     - cooldown:1?#! asConsole! cmi tfly $1 300 -s
>     - asConsole! cmi ctellraw $1 <T>&c&lRádce &f» &fBylo ti aktivováno &emoderátorské
>       létání &fpo dobu &e5 min&f. Aktivuj opětovným použitím.</T>
>     Perm: true
> ```
> 
> [12:28:09 INFO]: Renzotom issued server command: /cletanimod
> [12:28:09 INFO]: Hráči S1M0N jsi nastavil režim létání na 5 min

If i´m not wrong $1 not work when use asConsole!, only for player commands like asPlayer! and fakeOP! because it run from a player. 

I never get it work if I not use asConsole! cmi tfly [playername], because the console don´t know ho run the command in the first place. But for my It not even run the command only say player not fund if I use $1

**Comment by CloudeLecaw** [comment]
this is not correct because this command your executing from ingame ;)

**Comment by Volgeop** [comment]
Yeah your console works as expected... but now, how can I make this works?
```
  cletanimod:
    Cmds:
    - cooldown:1?#! asConsole! cmi tfly $1 300 -s
    - asConsole! cmi ctellraw $1 <T>&c&lRádce &f» &fBylo ti aktivováno &emoderátorské
      létání &fpo dobu &e5 min&f. Aktivuj opětovným použitím.</T>
    Perm: true
```
If player use just /cletanimod to activate tfly for him and not for ranodm player?

**Comment by broken1arrow** [comment]
> Yeah your console works as expected... but now, how can I make this works?
> 
> ```
>   cletanimod:
>     Cmds:
>     - cooldown:1?#! asConsole! cmi tfly $1 300 -s
>     - asConsole! cmi ctellraw $1 <T>&c&lRádce &f» &fBylo ti aktivováno &emoderátorské
>       létání &fpo dobu &e5 min&f. Aktivuj opětovným použitím.</T>
>     Perm: true
> ```
> 
> If player use just /cletanimod to activate tfly for him and not for ranodm player?

As I say try
```
cletanimod:
    Cmds:
    - cooldown:1?#! asConsole! cmi tfly [playername] 300 -s
    - asConsole! cmi ctellraw [playername] <T>&c&lRádce &f» &fBylo ti aktivováno &emoderátorské
      létání &fpo dobu &e5 min&f. Aktivuj opětovným použitím.</T>
    Perm: true
```

**Comment by CloudeLecaw** [comment]
no. even when you use it ingame or not $1 is Argument of the used command
and if use type ingame /command this is test
then also if used asConsole! then the console execute this andnfir the console also this is $1is is Argument $2 and test is Argument $3

what is true as console you just can use [playerName] if the custom alais comea from cmi.
there it works fine
i use this allready in many commands where i execute a command but dont want to give the player access to the main command itself. 
asConsole! is a good solution here.

Problem only comes if the command das not Support playername or does not have it. 

in the examole used about all is fine with using [playerName]

for me it sounds like you habe not tested it.
the behavior you descripte where playername does not work sounds more like a problem from other alais plugins or from executed from console direcly.

on our server near 80% of all button are execute as console or from console (like in ics)
if u need to execute as player there then u need asPlayer!
but because its handled in cmi you can use
for example try an custom alais with
asConsole cmi warp Testwarp [playername]
it will work fine
if using $1 instead of [playerName] here
then you need to type /customalias playername
the differences will be that in case you forgot playernae in the custom alais with $1 nothing will happen because the conaole cant warp

**Comment by CloudeLecaw** [comment]
if you wish to have a custom alais that get executed for  you and also for other Players just ask ;)
its not so hard to design with specialized commands. 
its just a check from arg1
if arg1 exist do that command
if arg1 does not exist then do this command

**Comment by broken1arrow** [comment]
> no. even when you use it ingame or not $1 is Argument of the used command
> and if use type ingame /command this is test
> then also if used asConsole! then the console execute this andnfir the console also this is $1is is Argument $2 and test is Argument $3
> 
> what is true as console you just can use [playerName] if the custom alais comea from cmi.
> there it works fine
> i use this allready in many commands where i execute a command but dont want to give the player access to the main command itself.
> asConsole! is a good solution here.
> 
> Problem only comes if the command das not Support playername or does not have it.
> 
> in the examole used about all is fine with using [playerName]
> 
> for me it sounds like you habe not tested it.
> the behavior you descripte where playername does not work sounds more like a problem from other alais plugins or from executed from console direcly.
> 
> on our server near 80% of all button are execute as console or from console (like in ics)
> if u need to execute as player there then u need asPlayer!
> but because its handled in cmi you can use
> for example try an custom alais with
> asConsole cmi warp Testwarp [playername]
> it will work fine
> if using $1 instead of [playerName] here
> then you need to type /customalias playername
> the differences will be that in case you forgot playernae in the custom alais with $1 nothing will happen because the conaole cant warp
> some commands are made that playername ia optionnal but if you work with $1 and the command is from console then an Argument is needed in the customalais too.
> the question is what the designer here wants..
> dies he want a command that can be executed only for the player that uses it? or is it a more administrativ command where the admin can use it for others players. well you can use the playername equal script to execute it once for you and once for the other depending if you used an Argument or not. it not so hard to create.
> Zrips made it really great easy for us users to creat massive amount of ways to handle with commands with the specialzed commands.

If it no other way forward you can use two options ether asfakeOP! or give player true customalias a temp perm for a 
a few seconds. If [playername] not work you can try %player_name% or %player%.

**Comment by CloudeLecaw** [comment]
asfakeOP! sound better then it is thebecuae the executer is not the player you there u need to work with vars

**Comment by Zrips** [comment]
This is actually a bug, will make some basic fix to prevent from command firing on "ramdom" player when you dint provided necessary data for ptarget variable

**Comment by Volgeop** [comment]
Ok @Zrips ,  and should I change it somehow or let it as it was at the beginning?
