### ISSUE TITLE
Anvil command text format breaks jeb_ and Dinnerbone

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#4485]
**Description of issue:**
The `jeb_` and `Dinnerbone` nametag feature is a well know minecraft easter egg feature.
However, the way you make a nametag is relevant if this works or not.

How to reproduce:
A real anvil makes a nametag in this way:
![Screenshot_20201026_195234](https://user-images.githubusercontent.com/28690790/97216237-d1282f80-17c5-11eb-8289-d4a9563d0f04.png)
CMI anvil makes this type of nametag:
![Screenshot_20201026_195358](https://user-images.githubusercontent.com/28690790/97216278-e0a77880-17c5-11eb-9785-97c20ad0b72c.png)
Note that their nbt info is different, but applied on an animals, they work and look the same.
However a jeb_ nametag made by a real anvil works, and the other won't.
![Screenshot_20201026_200851](https://user-images.githubusercontent.com/28690790/97217135-1dc03a80-17c7-11eb-8484-13513c4f8f66.png)

---

**Cmi Version (using`/cmi version`):** 
8.7.9.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.3

**Comment by CloudeLecaw** [comment]
This normal and was added by cmi to be able to see modfi of name take for the jeb_ and dinnerbone u nees to use the anvil. So all fine here

**Comment by Zrips** [comment]
@x1p 
This is not a CMI bug in particular. This is issue with minecraft on spigot (?) level using different format when item name is changed. As you have already noticed extra stuff is added to item name even tho method to change item name dint changed code wise, but with recent minecraft versions this broke apart as easter egg doesn't recognize this new format. 
I can just imagine that i will see this "bug" report for next year or so until we get appropriate fix from spigot, but at this point i'm not really in interest to fix something at my end which needs to be fixed and spigots.
