### ISSUE TITLE
Commands Disappearing

### ISSUE THREAD

**Issue by VimaMT** [Zrips/CMI#4486]
**Question: **
I'll start out with some questions.  This will be rather long.

First, my production setup:

CMI: 8.7.9.0 SqlLite-> 8.7.9.3
Server: Paper(246) 1.16.3-R0.1-SNAPSHOT
CMI economy: True Vault 1.7.3-b131(CMIEInjector) CMI Chat: True
Modules -> 51 enabled 0 disabled:

Ok, I've tried to update CMI to version 8.7.9.3 on the prod server. Most of my commands disappear. They are simply not there any longer. The player no longer sees them.

Questions:
1) Where does the user data come from ... the home data? Is this a CMI database, or is it saving them in a world playerdata file?
2) Do you know of any other thing that I may be missing?

**Comment by VimaMT** [comment]
I need to edit that ... I tried to put my basic CMI setup over on the test server, not the Essentials Setup. Sorry.

**Comment by VimaMT** [comment]
I was finally able to duplicate this on a test server. I had not moved all my plugins over in my previous tests. One more question:  Did something change in the way commands are registered outside of the CMI plugin?

I have been using a plugin called Plugin Hide Pro (PLHide Pro) to only show those commands that players need to see to them. I am using the exact same version of it after the CMI update as before it ... but for some reason it does not recognize the CMI commands after the CMI upgrade.  If I disable PLHide, my CMI commands work, and I see homes.

PLHide is working alright with other plugin commands ... CoreProtect works alright through it.

**Comment by CloudeLecaw** [comment]
Depending on your config homesbare saved innthe mysqllite file in the. Db database or on your mysql server innthe tables there.

**Comment by VimaMT** [comment]
Why the change between versions of CMI?  Did CMI change?

**Comment by VimaMT** [comment]
I tried SuggestionBlock and I tried NoPlugins. Both of them acknowledged that the commands were there. Plugin Hide does not see those same commands after I upgrade from CMI: 8.7.9.0  to CMI 8.7.9.3.  I did not change Plugin Hide.  This means that something changed with CMI.

But, I'll talk with the author of Plugin Hide and ask him if he will please test with the latest CMI.
