### ISSUE TITLE
Starting up: [CMI] Failed to load worth for: ACACIA_SAPLING

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#4488]
**Description of issue:**

Loading CMI it complains about legacy_raw_fish and acacia_sapling. 

I don't care about the legacy fish either, so I removed it from worth.yml, but acacia_sapling is still valid.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[CMI] Failed to load worth for: ACACIA_SAPLING
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
worth.yml

worth:
  ACACIA_BOAT: '1.23'
  ACACIA_BUTTON: '0.23'
  ACACIA_DOOR: '0.49'
  ACACIA_FENCE: '0.39'
  ACACIA_FENCE_GATE: '0.31'
  ACACIA_LEAVES: '0.39'
  ACACIA_LOG: '1.0'
  ACACIA_PLANKS: '0.23'
  ACACIA_PRESSURE_PLATE: '0.48'
  ACACIA_SAPLING: '0.31'
  ACACIA_SLAB: '0.11'
  ACACIA_STAIRS: '0.36'
  ACACIA_TRAPDOOR: '0.74'
  ACACIA_WOOD: '1.31'
```

---

**Cmi Version (using`/cmi version`):** 
```
> cmi version
[06:30:26 INFO]: --------------------------------------------------
[06:30:26 INFO]: CMI plugin version: 8.7.9.3 SqLite
[06:30:26 INFO]: Server: Paper(247) 1.16.3-R0.1-SNAPSHOT
[06:30:26 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: True
[06:30:26 INFO]: Modules -> 50 enabled 1 disabled: flightCharge
[06:30:26 INFO]: --------------------------------------------------
>
```

**Server Type (Spigot/Paperspigot/etc):** 
```
> ver
[06:30:34 INFO]: This server is running Paper version git-Paper-247 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[06:30:34 INFO]: Checking version, please wait...
[06:30:34 INFO]: Previous version: git-Paper-246 (MC: 1.16.3)
[06:30:34 INFO]: You are running the latest version
>
```
<img width="638" alt="Screenshot 2020-10-27 at 06 31 02" src="https://user-images.githubusercontent.com/28841349/97260880-fe083100-181d-11eb-9108-c82c9249fcaf.png">

If i /stop the server, and manually remove the acacia sapling from the worth.yml and start the server, then in-game use /cmi setworth while holding acacia sapling and set the value for it again (which btw, is no longer possible to do 0.31, only 0.3) then it adds it back to worth.yml as `  ACACIA_SAPLING: '0.3'`

[edit] I also just noticed that despite it adding it to the worth.yml itself, you can't sell acacia saplings in /sell either.

**Comment by mrfloris** [comment]
untested, but i saw quartz block suddenly being worthless and can't be /sell sold.
still have to check, but just in case it's also borked, reporting

**Comment by broken1arrow** [comment]
For me is all banners and ACACIA_SAPLING

Working fine older versions.

**Comment by Zrips** [comment]
Should be working correctly with next update

**Comment by mrfloris** [comment]
Excellent, thank you.
