### ISSUE TITLE
Cmi Unbreakable.... breaks? or vanishes...

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#4489]
**Description of issue:**

Randomly, while using an item with unbreakable... it vanishes. Like it breaks.

I've been able to get it to happen twice to me now. No errors in console, and it happened to me only while I was using the item, and flagged for afk by cmi. I was mining, and then the pick was just gone. Both times I had the pickaxe for an extended time, and had used it quite a bit already and while flagged for afk. 

**Cmi Version (using`/cmi version`):** 
8.7.9.3 - has been an issue for at least 2 weeks on older versions

**Server Type (Spigot/Paperspigot/etc):** 
Paper spigot - 1.12.2 and 1.16.3
(It happened on both servers, I recreated on 1.12.2 and could not recreate on 1.16.3)

**Server Version (using `/ver`):** 
paper 240 - 1.16.3
paper 1616 - 1.12.2

**Comment by CloudeLecaw** [comment]
Usually the afk has nothing to do with unbreakeable items. If you Enchant item with the cmi unbreakeable command they never loose dura. They should also not disappers for no reason... Be sure that cmi caused this issue?

**Comment by Kbryst** [comment]
The items were made using CMI unbreakable.

**Comment by Zrips** [comment]
How exactly did you recreated this issue on your server? And have you tested it with CMI only to make sure this issue originates from it and not another plugin?

**Comment by Kbryst** [comment]
So currently as it stands I have tested it on 3 servers, 2 are live production servers and one was just cmi on my home computer.

I have been able to recreate it, I am still unsure how exactly. I keep afking and coming back to it gone from my hand. 

The server on my home computer, windows 10 1.16.3 paper
The live production servers are 1.12.2 and 1.16.3 on i forget which linux whatever whatever

**Comment by Zrips** [comment]
I cant recall any code which would actually remove items from players in any case. As you tried with default CMI settings, could you retest that without CMI at all? As CMI doesn't remove items in general and definitely not by items flags so it could be some internal minecraft bug which removes items like that after some period of time.

**Comment by Kbryst** [comment]
Sure, I will have to test after the 12th, traveling for work currently.

**Comment by Kbryst** [comment]
Unfortunately I will need to stop testing, I will reopen this and continue when I can. I am so sorry about that.
