### ISSUE TITLE
2 decimals money

### ISSUE THREAD

**Issue by Yukyxy** [Zrips/CMI#449]
how we add 2 decimals for my economy? please

**Comment by MCTyler** [comment]
I have no (USA) Pennies showing so this is my format....
```
  # Format used for displaying money
  MoneyFormat: '###,###'
```

**Comment by mercurialmusic** [comment]
I have two decimals in my config:
`  # Format used for displaying money
  MoneyFormat: '###,###.##'`
And it still shows up rounded to one decimal place as well, so while it hasn't been an issue it is mildly annoying.

**Comment by Zrips** [comment]
`  MoneyFormat: '###,###.00'`
Will always show fraction and its enough to do /cmi reload for new format to be taken.
