### ISSUE TITLE
Vanish players can you see on dynmap 

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#4491]
Vanish players can you see on dynmap.

If i login in vanish (I have not try if I set my to vanish), you can see me on dynmap, if i open /vanishedit set one random thing on and off I get invisible (not vanish on and off i try for example "can deal dmg to others").

**Cmi Version (using`/cmi version`):** 
8.7.9.3 
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
184 1.16.2
**Relevant plugins (Delete if this isn't needed):**
cmi, dynmap

**Comment by CloudeLecaw** [comment]
Have you disabled seeing vanhisg people in dynamp config?

**Comment by broken1arrow** [comment]
> Have you disabled seeing vanhisg people in dynamp config?

Has not bee a issue in older version of cmi and if you get it working if trigger something in vanish, is it a CMI error.

**Comment by Blueeyestar** [comment]
I can confirm that. It is the same with us.

**Comment by CloudeLecaw** [comment]
i agree this comes from 8.7.9.3..fixed with 8.7.9.2 *lol*

**Comment by Zrips** [comment]
Should be fixed with next update

**Comment by broken1arrow** [comment]
I´m slow to update but, fork fine even in 8.7.10.3.

**Comment by CloudeLecaw** [comment]
hehe...yes because it was fixed allready some version ago ;)

**Comment by broken1arrow** [comment]
> hehe...yes because it was fixed allready some version ago ;)

Yes I know, but not always when developers say it fixed. Is it fixed, so I got the time to check it too day :)
