### ISSUE TITLE
Global chat 

### ISSUE THREAD

**Issue by Deltazura** [Zrips/CMI#4495]
Hello, i'm using AdvancedMobArena to create a game, and when i join a game, i have the party chat (AdvencedMobArena), but when we talk, we talk in the global chat too.

![image](https://user-images.githubusercontent.com/21087810/97488017-fbacf080-195d-11eb-9d77-9fbe83cc41b2.png)

I didn't have this problem with essentials, i had this problem when i changed to CMI :/

---
Config of chat section : https://pastebin.com/LSsyW2WC
```

---

**Cmi Version (using`/cmi version`) : 8.7.9.3** 

**Server Type (Spigot/Paperspigot/etc) : Spigot** 

**Server Version (using `/ver`) : git-Spigot-a99063f-8ea9b13 (MC : 1.15.2)**

**Comment by Zrips** [comment]
Dont really have a version to test it out properly, but did some changes relating to chat messages handling and it should be working properly with next update. If you still experience same issue let me know.

**Comment by Deltazura** [comment]
> Dont really have a version to test it out properly, but did some changes relating to chat messages handling and it should be working properly with next update. If you still experience same issue let me know.

Hi, i steel have the same problem : 
![image](https://user-images.githubusercontent.com/21087810/97912347-fa5c3900-1d4c-11eb-96c8-dd07b55cecc6.png)
