### ISSUE TITLE
Warp breaks after restart

### ISSUE THREAD

**Issue by xReplicate** [Zrips/CMI#4497]
Every single time our server restarts the warp breaks. When using the warp you get the error that the target world can't be accessed. It gets fixed when you place the warp again. 

---

**Cmi Version:** 8.7.9.3

**Server Type:** Paper

**Server Version:** 1.16.3

**Comment by nitewing76** [comment]
You should include the lines for that warp...this would eliminate the possibility of a syntax error or a glitch when the warp was set.

**Comment by xReplicate** [comment]
Halloween:
  Location: Halloween2;-130.86;63.0;-130.71;93.01;15.16
  ReqPerm: true
  Creator: 1e51dd70-c567-4621-9524-5f8975e09abe

**Comment by nitewing76** [comment]
Alignment matters...so is it:

`Halloween:
Location: Halloween2;-130.86;63.0;-130.71;93.01;15.16
ReqPerm: true
Creator: 1e51dd70-c567-4621-9524-5f8975e09abe`

-or-
(2-space indention on the lower lines)
`Halloween:
   Location: Halloween2;-130.86;63.0;-130.71;93.01;15.16  
   ReqPerm: true
   Creator: 1e51dd70-c567-4621-9524-5f8975e09abe`

Capitalization also matters, so pls confirm your world is Halloween2, not halloween2.

idk the solution...these are just things the dev will wonder.  The more information he can have, the better.

**Comment by nitewing76** [comment]
Alignment matters...and GitHub doesn't make it easy.  Is there a 2-space indention on the lower lines? Capitalization also matters, so pls confirm your world is Halloween2, not halloween2.

idk the solution...these are just things the dev will wonder. The more information he can have, the better.

**Comment by xReplicate** [comment]
Yes the indent is present. I also double checked the world name.

**Comment by Zrips** [comment]
@xReplicate 
What type of multi world plugin are you using to create those custom worlds?

**Comment by xReplicate** [comment]
We don't have a multi-world plugin in that server. I used plotsquared to setup the world itself and then I used /cmi world to switch to it and place the warp.
