### ISSUE TITLE
title! and subtitle! flags 

### ISSUE THREAD

**Issue by ipozow** [Zrips/CMI#4499]
**Description of feature/improvement request:**
It would be great to have the (-in:[ticks]) (-out:[ticks]) (-keep:[ticks]) flags in the specialized commands for title! and subtitle! like in the /cmi titlemsg command. 
---
### Basic explanation as to why this feature is needed and/or useful to have: ###
Useful so players can reach to read all the message before it disappears and still use the full potential of specialized commands.

**Comment by CloudeLecaw** [comment]
you have allready

**Comment by ipozow** [comment]
Is not possible, I wanted to use it in the schedules so I can show it to everyone that meets the requirements and I can't do that with the titlemsg command. It would be perm:some.perm! cmi titlemsg [playerName] <message> and the flags, but playerName isn't a possible variable in the schedulers and allPlayers won't do the trick since it would send the message to everyone if only one online player has that perm

**Comment by CloudeLecaw** [comment]
with the normal cmi command an the variable all instead of playername

**Comment by ipozow** [comment]
Is working fine on my server.   
It looks like this: - perm:anuncios.grupo! title! {#Gold}message
if I don't have that permission it doesn't show to me

**Comment by CloudeLecaw** [comment]
hm well good that it works even if it ahould not, so just lets hope it does. not het fixed one day :D

**Comment by ipozow** [comment]
It doesn't work like that. Look at the config: “#   If command starts with perm:[permissionNode]! then command will get performed **if player** has permission node. This will not work when we dont know who is target player. In example: perm:cmi.announce.vip! broadcast! Hello vip guys”

**Comment by CloudeLecaw** [comment]
your wrong and i prved it allready

BroadcastVoteReminderTest:
  Enabled: true
  MinPlayers: 1
  Delay: 5
  Repeat: true
  Commands:
  - perm:cmi.announce.vip! broadcast! Alle die das hier sehen, haben die richtige Berechtigung.

now i prodcasted to normal player + me and owner the sheduler

Result
![Snag_370c25d](https://user-images.githubusercontent.com/12080017/97768361-c8678e80-1b22-11eb-8c9d-2236fa3e87ea.png)

i have the permisison
owner has his
player not

the is prove that i was right
the perm asked for is the executer and this is the Scheduler that is allways console with all permission

**Comment by ipozow** [comment]
“This will not work when we don't know who is target player”. With title! and subtitle! we know who is target player. With broadcast! we don't.
