### ISSUE TITLE
Accept repair cost by entering /repair command again

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4502]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, my players are complaining about they have to click on repair command message to confirm the cost they have to pay, but they would rather just enter the command again. Would it be possible please?

### Basic explanation as to why this feature is needed and/or useful to have: ###
Players are complaining about clicking on command, when they use pickaxe and it breaks so many times and they have to click into chat rather than typing /repair, it's annoying for them.

**Comment by Zrips** [comment]
But it is already made in a way where you can repeat same command to confirm action.

**Comment by Volgeop** [comment]
In repair command it isn't done this way, cause repair is only in config and it's done another mechanism probably, players have to click on it.

**Comment by Volgeop** [comment]
![image](https://user-images.githubusercontent.com/18662086/98558199-71418680-22a5-11eb-89dc-1cd0784a51b3.png)

"repairConfirm" string message, When I repeated command....

**Comment by Volgeop** [comment]
Added in the latest ver
