### ISSUE TITLE
Uncondense and Condense issues are still present

### ISSUE THREAD

**Issue by Getblock** [Zrips/CMI#4503]
**Description of issue:**

#4359 #3788
Both issues above is still an issue apparently, 

Uncondensing items through `/uncondense` is fixed however you are still able to do them by typing the item name after the command such as `/uncondense sandstone`. This also applies to packed ice and other items below.
- Sandstone --> sand
- Packed Ice --> Ice
- Blue Ice --> Packed Ice
- Wool --> String
- Quartz Block --> Quartz

Another issue with condense is that you are not able to condense sand to sandstone without typing the item after the command. `/condense sand`

cmi version:  8.7.9.3 MySQL

This server is running Paper version git-Paper-220 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Comment by nitewing76** [comment]
imho _/condense_ and _/uncondense_ should only change between nuggets <--> ingots/items <--> blocks....items and blocks for which smaller parts actually exist (iron/gold, gems, glowstone, redstone, kelp, and others). Not for such things as sand vs sandstone and ice.  Doing so over complicates and conflates the plugin.   But if these are to remain, then requiring the extra argument (_/condense [arg0]_) is a good thing. 

There needs to be a list of all items/blocks which are affected by these commands (not much more can be said without knowing). There also should be config options to white/blacklist these items independently.  And possibly a module setting to allow disabling any blocks/items which go beyond the historically normal _/block_ and _/ingot_ functions.

**Comment by Zrips** [comment]
@Getblock 
Well this is not a issue in particular as i did this more or less intentionally. Not using item name will condense/uncondense items which have backwards recipe, while in case  you will decide to use items name then it will do it even it there isint recipe to revert this change as player intentionally defined which item needs to be changed. I might change this behavior with next update to make it more consistent with provided material or not just to avoid confusion like this in future.
