### ISSUE TITLE
Sudo [item]'s into peoples chat

### ISSUE THREAD

**Issue by MrMcyeet** [Zrips/CMI#4505]
**Description of feature/improvement request:**
When you do `/sudo XYZplayerName c:[item]` it should take the item thats in the person doing `/sudo`'s hand, and NOT take the item from the person getting sudo'd hand.

---
### Detailed explanation of what it should do, when and in what situation: ###
If the user SarahCookie did `/sudo MrMcyeet c:Look what i got [item]` it should take the item currently in SarahCookie's hand and put it into chat as MrMcyeet, so if Sarah was holding dirt and MrMcyeet was holding stone, in chat it would say `<MrMcyeet> Look what i got [Dirt]` But currently it would say `<MrMcyeet> Look what i got [Stone]`

### Basic explanation as to why this feature is needed and/or useful to have: ###
Useful for when forging chat as someone else. currently, it takes the item that THEY have in their hand. It'd be cool to force [item]'s in chat as someone else.

**Comment by Zrips** [comment]
Not really possible with current setup as item into chat being processed on completely different stage after sudo itself have been sent. New variable would be needed by itself, maybe something like [Zrips:item] which would use provided name as a source, but that would not resolve issue and would only create new one where players could show items from some one else inventory, permission check is needed, but we cant know whose permission we need to check when we do sudo on a chat message.
So yea, in short: will not be added.
