### ISSUE TITLE
CMI not doing anything other than being NULL

### ISSUE THREAD

**Issue by Zlemoncurd** [Zrips/CMI#4506]
/cmi doesn't work just says "An internal error has occurred"

---

Error [3:02:01 ERROR]: null 

![image](https://user-images.githubusercontent.com/70798945/97768900-6131f480-1b8b-11eb-895c-3428d08237ba.png)

CMI Version 8.7.9.3 

Server Type Paper 1.16.3

Server Version Paper version git-Paper-251 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Comment by MrMcyeet** [comment]
When you do `/pl` is CMI red?
If so, what does your startup log say about CMI?
Does it say anywhere in it that CMI is disabled? 
If so, either paste your log here so I can help ya figure out why, or if you want, you could probably just see why

**Comment by nitewing76** [comment]
You probably have a typo or alignment error in the config or locale. copy+paste them at [this link](http://yaml-online-parser.appspot.com/).  But it will tell you why in the console...usually near the end and begins with "Caused by "

When a plugin has so many users and only 1 person is experiencing an error with the base command, it is never accurate to presume the plugin itself is the problem. ;)

**Comment by Zlemoncurd** [comment]
@MrMcyeet 
[latest.log](https://github.com/Zrips/CMI/files/5469844/latest.log)

**Comment by Zlemoncurd** [comment]
@nitewing76 My CMI doesn't have a config am I missing a file?

**Comment by nitewing76** [comment]
The last line of the log is a big indicator...
`[Server thread/WARN]: Can't keep up! Is the server overloaded? Running 72131ms or 1442 ticks behind`

72.131 seconds behind...that's a record afaik. lol  A server should not take 10 minutes to load...don't worry, you are not the only one I've responded to tonight that has a 10-minute startup time.  You don't have too many plugins, so PerWorldPlugins causing all of your problems and it's useless. Use permissions to control things...just add _world=<the world name>_ to the end of the permissions command.  So if you want all players to have _/fly_ in only one world, do _/lp group <group name> permission set cmi.command.fly true world=<the name of the world>_.  If you already have perms loaded, use _/lp editor_ and you can add Context in a web browser (click in the far right column).

CMI is not even loading....there are many files it should load for you. If deleting PerWorldPlugins doesn't help...remove all plugins except WorldGuard, LuckPerms, and CMI...then try again. If that doesn't work, delete CMI, re-download it, and try again.

**Comment by Zrips** [comment]
@Zlemoncurd 
Will issue some what fix, it should allow you to load CMI properly even with that error, but in general it should not have happen. My guess is that CMI plugin doesn't have write permission on your server and failed to create some required files. You might want to look into that.
And you have some other plugins failing on you too, so you might want to check those one too.

And just noticed something here, you started server at 21:54:25 and it finished loading at 22:32:25. That's like 38 minutes of server startup when it needs to be like 20-40 seconds depending on plugin count. You have some bigger issues with your sever in general as this is just over the top long loading times.
