### ISSUE TITLE
PreventMobSpawning is  active even if it is rejected in config

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#4510]
**Description of issue:**

If players go AFK mobs stop spawning, I has never turn this on.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
no errors
```

---

**Cmi Version (using`/cmi version`):** 
8.7.9.3
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
184
**Relevant plugins (Delete if this isn't needed):**
cmi

**Comment by Zrips** [comment]
If you have PreventMobSpawning->Enabled set to false then being in afk mode will not effect mod spawning, that just not possible by the code. Your issue in particular could be related to vanish mode which could prevent mob spawning too, if player is not in vanish when this issue happens then you might want to double check if this actually is disabled or test this with CMI only to make sure that this originates from CMI and not another plugin. 
Closing ticket for now, if you will still experience this issue, let me know.

**Comment by broken1arrow** [comment]
@zrips ofc not vanish on, was players some complain the spawners not work if they are afk. 

Only plugin some had with no spawning is cmi and mob farm manger.. I can try only cmi.

**Comment by Zrips** [comment]
@broken1arrow 
Maybe its MFM, but then, MFM doesn't check players afk state and CMI will not do anything if that check is disabled. So something strange is going on
