### ISSUE TITLE
/give + enchanted glint (glow)

### ISSUE THREAD

**Issue by nitewing76** [Zrips/CMI#4514]
What is the syntax to hide enchants with _/cmi give_? Or any other method to apply enchanted glint (glow) to an item. _/cmi hideflags hide_enchants_ only works if they are holding the item in their hand, so it's not conducive with _/give_.

**Comment by Zrips** [comment]
You can utilize generic tags. So to get item with enchant and hide it you can perform: **/cmi give stone e power:5 {HideFlags:1}**
