### ISSUE TITLE
placeholder not properly converted in chat prefix

### ISSUE THREAD

**Issue by Tom25W** [Zrips/CMI#4515]
CMI does not properly convert placeholders in the prefix ( https://imgur.com/a/6ce62y1 )
The prefix ":admin:" should be converted by cmi to the admin plate as seen in the Luckperms player info menu.
After asking in the Luck Perms discord, they forwarded me to CMI as Luck Perms only sends the placeholder (:admin:) to CMI.

**Plugin Version CMI8.7.9.3
Spigot Server
```
>ver
[09:09:08] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-2740d5a-890130b (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
```
MC Version 1.16.3 
Item Adder**
https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-itemsadder%E2%9C%A8custom-items-huds-guis-mobs-3dmodels-emojis-blocks-wings-hats-liquids.73355/
**BetterRanks (Item Adder addon)**
https://www.spigotmc.org/resources/ranks-betterranks-with-custom-textures-itemsadder-addon.84852/
**Luckperms**
https://www.spigotmc.org/resources/luckperms.28140/

**Comment by Zrips** [comment]
About which placeholder are we talking here exactly?

**Comment by CloudeLecaw** [comment]
he wants the word Admin with the red backound like lucly perms showa it in chat
