### ISSUE TITLE
Nametag jeb_ does not work when got from saved items

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4516]
When you save a nametage for the jeb_ effect in saved items it does not work when you take it with saved items get

for Dinnerbone it works fine :)

spigot 1.16.3 B-251,   CMI 8.7.9.3

**Comment by Zrips** [comment]
Not a bug with CMI in particular, issue with spigot item serialization method adding extra nbt data which prevents from "jeb_" to work as it should. Could be fixed from my end but that would require quite a work around and nbt manipulation just to change nbt to correct format for this specific thing to start working. Spigot bug.

**Comment by CloudeLecaw** [comment]
well we are using paper
i take an anvil and call the nametag jeb_
at this state it works fine. 

now i tired to save it /cmi saveditems save A name
. 
fine

now i tried to get my nametag
/cmi saveditems get name

i got the nametag that i used before the jeb_ obe that was working before.
now it does not work anymore.. 
is this because cmi gave it with a command? 

the crafted one was working fone before saved/get it with the cmi saveditems.. 

so what i understood from yoir answer. in case of jeb_ saving it in the cmi saveditems makes the item currepted because the spigot code assa some ntb... right?
