### ISSUE TITLE
Add the ability to prevent jailed players from destroying blocks

### ISSUE THREAD

**Issue by diskotekastar** [Zrips/CMI#4517]
Please add an option to prevent imprisoned players from destroying blocks

**Comment by CloudeLecaw** [comment]
Is this neessarry?
Most Servers create a little Subzone to rheir prison where the players cant build and usually this is enough ;)
your having no Protectionplugin?

**Comment by diskotekastar** [comment]
I use a plugin on my survival server for a closed number of players and there are no territory protections, such as the residence plugin or the worldguard plugin. I believe that this option suits more people.

**Comment by CloudeLecaw** [comment]
hm but. most servers do that with a protection plugin ;)

well you may can build your prison at the world spawn. 
in serverproperties you can define a radius where only Operators could build. create your prison there if you dont wanne use a protection plugin

**Comment by mrfloris** [comment]
Almost every server has worldguard installed, they could just make a region or warp for the jail. That way players can visit /warp jail still, but jailed players can't get out of their cells.

**Comment by CloudeLecaw** [comment]
I agrree with mrfloris. Nearly Esch Server hast a Protektion Plugin installed.worldguard, residence,redprotect,Grieg Prävention,and so on.

So i See this Features of adding Blockbreak to jails AS unnessary too
But the OP ist still freue to ASK for it, but i think this request here become forgotten ;)
