### ISSUE TITLE
Can add compatibility with Chunky Border to Selection Visualizer?

### ISSUE THREAD

**Issue by mA0w0** [Zrips/CMI#4519]
There is a free plugin called Chunky, which is similar to WorldBorder.

You can add the same world boundary as WorldBorder with the add-on that adds a boundary called ChunkyBorder.

Is it possible to add compatibility with ChunkyBorder?

**Comment by mrfloris** [comment]
Chunky is basically replacing worldborder, it's fantastic, from the author who currently gives us lwc extended, so yes, pls do !

**Comment by Zrips** [comment]
Okey

**Comment by mrfloris** [comment]
Thank you!
