### ISSUE TITLE
Item Specialized Command Error with Portals

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#452]
This is probably me doing it wrong or in a way that's not supposed to work -- so I guess it's either a feature/enhancement request or a bug or both? 

I saved an item using CMI SavedItems (included below) then am trying to use that as a "key" to get through a portal (commands below) using the new item specialized command as a condition. That's probably where I'm going wrong, so if the SavedItems don't translate to the item specialized command that would be my enhancement request, or otherwise if there's a way to include the data we need directly within the specialized command I would appreciate some guidance on syntax.

Anyway, when going through the portal with my current setup it succeeds every time whether the player has the item or not, and it's **not** consuming the item, then I also get the error here: https://pastebin.com/jvs3JZpj

Portal commands:
item:AtlantisKey:1#?!
cmi effect [playerName] blindness 2 1 -s
asPlayer! warp HeartofAtlantis

**ERROR:**
https://pastebin.com/jvs3JZpj

**SavedItems.yml:**
AtlantisKey:
  Item:
    type: NETHER_STAR
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §3Placeholder Key to the Heart of Atlantis

**Cmi Version (using`/cmi version`):** 
7.8.0.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.12.2 git-Spigot-2086bb0-8cc5a7e

**Comment by Zrips** [comment]
Your initial item requirement is wrong. There is no such item as "AtlantisKey" currently you can only request item by material, data value and amount. Your AtlantisKey seems to be item custom name which is not supported, this is why you are getting this error message. Tho will add some fail safe for it and print out error message into console to inform about wrong item information.
