### ISSUE TITLE
/cmi chat extra features

### ISSUE THREAD

**Issue by the456gamer** [Zrips/CMI#4526]
**Description of feature/improvement request:**
---
to add several new subcommands and improve staff and server experience
/chat force - to force a player into a private chat channel as staff
a way to stop players leaving /chat ?
a way to stop players using the prefix to speak in global while in /chat
a placeholder for the current chat channel
/chat settings
chat persistance - i know this has been requested before, this is just for completeness

### Detailed explanation of what it should do, when and in what situation: ###
/chat force should  make the player leave their current chat room, join the executers current chat (or specified chat channel)

ideally there should be a toggleable way, maybe for the room that people in there cannot leave (bar people with permission)

/chat settings as a way to toggle these settings, like the -private flag, prevent leave, prevent global, and persistance (and maybe a way to tranfer the owner)

the placeholder should just say the players current chat channel. maybe other placeholders for number of users in a room, and some settings (like private)

chat persistance should ignore the 1 hour idle / no person limit, and keep it over reboots (maybe discord intergration if possible)

### Basic explanation as to why this feature is needed and/or useful to have: ###

to use /chat as more of a staff/control tool, and the placeholders could be used to create custom, pretty ui/gui/scordboard/tablist/alias/whatever

**Comment by mrfloris** [comment]
Yeah, I'd love to have more staff control for /chat rooms. 

If we can talk to a private with the staff, away from the global chat, the player might be muted or cuffed already, or in jail, and we might wish to /chat force player, and it would be nice if the player then shows up in the room we've created (even if it is private). 

Right now i have 
```
asPlayer! cmi chat invite $1
asConsole! cmi sudo $1 /cmi chat join $2
```
But when they're muted, cuffed, jailed, etc, i'd have to give them access to things that are beyond their scope, they'd just use it to make their own priv rooms for friends and continue their hate speech etc. 

So if an internal force command would be able to deal with this, yay..

**Comment by broken1arrow** [comment]
> Yeah, I'd love to have more staff control for /chat rooms.
> 
> If we can talk to a private with the staff, away from the global chat, the player might be muted or cuffed already, or in jail, and we might wish to /chat force player, and it would be nice if the player then shows up in the room we've created (even if it is private).
> 
> Right now i have
> 
> ```
> asPlayer! cmi chat invite $1
> asConsole! cmi sudo $1 /cmi chat join $2
> ```
> 
> But when they're muted, cuffed, jailed, etc, i'd have to give them access to things that are beyond their scope, they'd just use it to make their own priv rooms for friends and continue their hate speech etc.
> 
> So if an internal force command would be able to deal with this, yay..

You can use temp perm if it only for force a player to other chatrooms :)

**Comment by CloudeLecaw** [comment]
about global
. why u not simply disable their shout permission to able to use     !
Then they cant write to global while in a Chatroom

**Comment by mrfloris** [comment]
That sounds like patching a thing, rather than having a solution. 

This is a feature suggestion though.

**Comment by the456gamer** [comment]
> about global
> . why u not simply disable their shout permission to able to use     !
> Then they cant write to global while in a Chatroom 

But it's not really using the normal "shout" thing, it's just pushing it into main chat I think

**Comment by Zrips** [comment]
Next update

**Comment by CloudeLecaw** [comment]
What happend with the placeholder?.. Does he exist?
