### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by XBlowmPow3r** [Zrips/CMI#4527]
hello, I have a problem, we bought cmi to use it on a network, the plugin was not put on bungeecord, but c and a problem, from the skypvp you see the towny chat only of the owners then those with all the permissions, but not the other way around; so from towny to skypvp you see the chat and from skypvp to towny no, I tried to disable cmi, and the result was the expected one, the problem was no longer
how do I solve?

cmi version 8.7.8.4

Paper 1.16.3 (SkyPvP) Twinity 1,16.3 (Towny)

1.16.3

**Comment by CloudeLecaw** [comment]
well for cmi to work u need cmi + cmi bungeecord installed. see innthe wiki.
Well this does not count for your town Chat see in this plugin what you need to do.
Cmi need to be on All servers if u want to n Connect the Feature of it. without it just like u installed it on a single Server

**Comment by XBlowmPow3r** [comment]
you didn't understand what I mean, I don't want to see the op chat of the other server, but I still see it, I see the [Owner] chat, ps your staffer on discord told me to open the ticket

**Comment by Zrips** [comment]
@XBlowmPow3r 
You can always double check for any permissions relating to the topic by using something like /cmi checkperm bungee
Which returns results including **cmi.bungee.publicmessages.[servername]** So if you want to prevent messages going to specific server you will need to negate permission for OP players, if you dont want to send public messages at all then simply disable it in config file under BungeePublicMessages section.
