### ISSUE TITLE
/se gradient

### ISSUE THREAD

**Issue by levarar** [Zrips/CMI#4532]
./se works incorrectly when working with gradients

1. /se 1 &f12:00 {#00d8e6>}Стульчики{#a1d5e6<}
![image](https://user-images.githubusercontent.com/68510813/98225924-62d23280-1f66-11eb-9abf-f4f6074e7c7b.png)
2. /se 2 &f12:00 {#00d8e6>}Стульчики{#a1d5e6<}
![image](https://user-images.githubusercontent.com/68510813/98225975-6ebdf480-1f66-11eb-96cf-905b995315c9.png)

**Cmi Version (using`/cmi version`):** 8.7.10.0

**Server Version (using `/ver`):** 1.16.3 Tuinity

**Comment by CloudeLecaw** [comment]
nice catch

**Comment by Zrips** [comment]
This is actually looks more like a minecraft bug as NBT data contains correct information but it displays it incorrectly for some reason. Will do some testing but it could be unfixable from my end

**Comment by Zrips** [comment]
Ok, 40 minutes later and bunch of messing around, should be working correctly with next update
