### ISSUE TITLE
Worthlist name GUI

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4534]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, could you add way to set /worthlist GUI name? I mean the name displayed in the top of the chest.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Because players can open it and forget what it is. I think it's useful.

**Comment by Zrips** [comment]
Will add
