### ISSUE TITLE
ignoring players does not work

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4535]
ignore (playerName/uuid/all)
Ignores player

cmi.command.ignore.bypass – to bypass ignore list

i added a player to irgnore list
but i still see his chats in game

![Snag_3c2249](https://user-images.githubusercontent.com/12080017/98281625-443b5e00-1f9d-11eb-8aa2-5ccf7d0a2409.png)

**Comment by mrfloris** [comment]
Are you operator? Maybe players can't ignore ops.

**Comment by CloudeLecaw** [comment]
I Tester IT with Player Rank too

**Comment by CloudeLecaw** [comment]
fixed   IgnorePublicMessage in config was set on false
