### ISSUE TITLE
spawn bungecoord

### ISSUE THREAD

**Issue by pinuxio** [Zrips/CMI#4539]
**Hi, I have a problem with bungecoord. having set the portals when I enter the server via the portal I would like the players to respawn in the exact point where they were when they logged out. I apologize for my bad english but i use google translator: **

**Comment by Zrips** [comment]
Its some what a bug. Button to toggle this option was missing from UI. With next update it will be fixed. Another option can be to simply perform **/cmi server [playerName] survivalServer** command when player enters to send him to that server if you are not interesting in exact location. But in any case, with next update you will have extra button to toggle behavior like that on and off

**Comment by pinuxio** [comment]
tnx

**Comment by pinuxio** [comment]
I saw the update, but unfortunately I can't set it as I would like. I deactivate :(
