### ISSUE TITLE
Warn

### ISSUE THREAD

**Issue by qwer2415wy** [Zrips/CMI#4541]
```
Legacy plugin CMIEInjector v1.0.2.3 does not specify an api-version.
```

---

**Cmi Version (using`/cmi version`): 8.7.10.2** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`): 1.16.4**

**Comment by mrfloris** [comment]
You can ignore this, this is done to help it to keep working when you update vault etc. 

It's just a new warning that spigot has introduced to inform people of this, but it's the same as before. And innocent. It has no impact on it working.

Now if you upgrade to 1.17 it should still work, without having to wait for a new version, unless there's enough changes in vault and 1.17 for example that this stops working and requires a small update.

**Comment by qwer2415wy** [comment]
Ok Thx
