### ISSUE TITLE
Very annoying issue with /unban

### ISSUE THREAD

**Issue by DutchUser** [Zrips/CMI#455]
**Cmi Version (using/cmi version):**
30.05 15:43:27 [Server] INFO Vault version: 1.5.6-b49(CMIEInjector)
30.05 15:43:27 [Server] INFO Server version: Spigot 1.12.2-R0.1-SNAPSHOT
30.05 15:43:27 [Server] INFO CMI plugin version: 7.7.11.0

**How can i disable the cmi /unban**
**I have** 

```
  # /cmi unban $1-
  /unban: false
```

**and have it changed in /cmi aliaseditor** 

```
  unban:
  - litebans:unban
```

**My mods now need to use** /litebans:unban **instead just** /unban

**The other one's(/kick/ban etc,) do work fine.**

**Comment by DutchUser** [comment]
Also noticed that after installing CMI the tab complete is not working anymore, going test it on our test server to be sure...

**Comment by MCTyler** [comment]
TBH you have too many plugins that are duplicating what CMI does. Until you work out or remove all this other stuff your gonna have issues. Why did you originally install CMI to begin with?

**Comment by DutchUser** [comment]
I'm dont going talk to you lol, dont act so stupid,

**Comment by Zrips** [comment]
@DutchUser There are 2 places which controls alias, Alias.yml and CustomAlias.yml. Check both files for possible /unban alias been registered. Disabling and full server restart should fix all conflicts with alias.

**Comment by DutchUser** [comment]
Its in there(CustomAlias.yml)

  unban:
  - litebans:unban

**Comment by DutchUser** [comment]
as side note, when i only do **/unban** it works, **however** when i put an name behind **/unban** it does nothing.

**Comment by tmellen** [comment]
Dutch -- to make your command pass the name behind it make it look like this:

  unban:
  - litebans:unban $1-

That means it's going to pass the command arguments are the command has been given (such as the player names).

**Comment by DutchUser** [comment]
Thanks, it works now <3
