### ISSUE TITLE
Silent chest: Shulkerboxes inside shulkerbox

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#4551]
**Description of issue:**
Normally, you can't put a shulker box inside another shulker box.

When in vanish and you open chests silently, you can make nested shulker boxes.
The cause is probably the inventory (GUI title) is marked as "Chest" instead of "Shulker_box"

When it's opened by shift right click, it recognizes it correctly as "{Color} Shulker box"

---

---

**Cmi Version (using`/cmi version`):** 
8.7.10.2
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.3

**Comment by Zrips** [comment]
Will get a fix with next build
