### ISSUE TITLE
Armor stand editor - duplication glitch

### ISSUE THREAD

**Issue by ArtNRG** [Zrips/CMI#4554]
**Description of issue:**
The armor stand editor can be used to duplicate items.
Steps to reproduce:
1. Place an armour stand.
2. Open the stand editor, place shulker box in the stand's helmet slot.
3. Close the editor and teleport somewhere far from that stand. 
4. Wait about 15 seconds while the world chunks around the armour stand will be unloaded.
5. Teleport back to the armour stand.
6. Execute command /cmi armorstand last.
7. Take the shulker box and close the editor.
8. The shulker box stays on the armour stand, take it without an editor.
9. Now you have two similar shulker boxes.

By the way. You can also break the armour stand after 8 step and be able to open it using /cmi armorstand last

**Cmi Version (using`/cmi version`):** 
CMI version 8.7.10.3
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
Paper-348 (MC: 1.15.2)

**Comment by broken1arrow** [comment]
> **Description of issue:**
> The armor stand editor can be used to duplicate items.
> Steps to reproduce:
> 
> 1. Place an armour stand.
> 2. Open the stand editor, place shulker box in the stand's helmet slot.
> 3. Close the editor and teleport somewhere far from that stand.
> 4. Wait about 15 seconds while the world chunks around the armour stand will be unloaded.
> 5. Teleport back to the armour stand.
> 6. Execute command /cmi armorstand last.
> 7. Take the shulker box and close the editor.
> 8. The shulker box stays on the armour stand, take it without an editor.
> 9. Now you have two similar shulker boxes.
> 
> By the way. You can also break the armour stand after 8 step and be able to open it using /cmi armorstand last
> 
> **Cmi Version (using`/cmi version`):**
> CMI version 8.7.10.3
> **Server Type (Spigot/Paperspigot/etc):**
> paper
> **Server Version (using `/ver`):**
> Paper-348 (MC: 1.15.2)

I have see this too, but I was in creative (in older versions) and have not investigate it closer.

**Comment by CloudeLecaw** [comment]
ive seen this too, wenn we dont give our players permission to called the last amorstand so i never cared abount invest more time into it..

**Comment by Zrips** [comment]
Confirmed, reproduced and fixed. Which by itself give idea why Interactive Commands on entities could stop too. So possible 2 fixes here.
