### ISSUE TITLE
/glow issue regarding nametags

### ISSUE THREAD

**Issue by Yertled** [Zrips/CMI#4555]
**Description of issue:**
We have an issue on our server, where if our nametag is for example &cAdmin &4PlayerName, our /glow color does not change from the default white glow. But when we disabled the config "change-nametag-prefix-suffix: " and made it false, it fixed the /glow issue, but our nametags changes the color to the color of the glow.
Is this intentional? Seems like a bug to me, any way of fixing this?
Appreciate any help and feedback.

**Cmi Version (using`/cmi version`):** 
8.7.10.3 SqLite
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper 261

**Comment by CloudeLecaw** [comment]
"change-nametag-prefix-suffix: "

where u found that?
our cmi config does not have this...

**Comment by Yertled** [comment]
> "change-nametag-prefix-suffix: "
> 
> where u found that?
> our cmi config does not have this...

My bad, we are using the plugin called TAB to get custom nametags. There is a config in there that is interfering with glow.
https://www.spigotmc.org/resources/tab-1-5-x-1-16-4-premium.83967/
TAB [1.5.x - 1.16.4] PREMIUM 2.8.8

**Comment by CloudeLecaw** [comment]
hm i renember to ppl use it when they have problems with the nametag management of glow

**Comment by EkonC** [comment]
https://github.com/NEZNAMY/TAB/wiki/Behind-the-scenes:-Why-nametags-affect-sorting-and-glow-color

**Comment by Zrips** [comment]
@EkonC 
Not a bug in particular. Issue comes with glow handling in general as Mojang made it dependent on players scoreboard team which by itself controls multiple things which includes prefix and suffix. Its some what know compatibility issue and for time being we will have to live with this weird behavior until some changes come to the glow handling in general from Mojang side.
