### ISSUE TITLE
/shoot largefirreball - 2r

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4558]
**Description of issue:**
Hi, there's wrong tab completion - /shoot largefirreball - 2r, it should be just fireball, like in /shoot smallfireball

---

**Cmi Version (using`/cmi version`):** 8.7.10.3

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 261

**Comment by CloudeLecaw** [comment]
hehe yeah th name there is largefirreball instead of largefireball
Great Catch!

**Comment by EkonC** [comment]
I can confirm this

**Comment by CloudeLecaw** [comment]
Well Trips Said allrady the spelling will be fixed with one of the next Updates :)

**Comment by Zrips** [comment]
Some upgrade for shoot command is coming out with next version.
