### ISSUE TITLE
Shoot type permissions?

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4559]
**Question: **
Hi, what are shoot type permissions please? Luckperms show me just arrow, others and fireball, but there's smallfireball and largefireball (btw wrong permission largefi**rr**eball) - reported in another issue), but it doesn't suggest me another tab completions like witherskull etc., so my question is, are they exist?

And why it suggest me just cmi.command.shoot.fireball instead of cmi.command.shoot.largefireball and smallfireball?

**Comment by CloudeLecaw** [comment]
larerfireball = fireball

**Comment by Volgeop** [comment]
oh, it was confusing. And then there's shulkerbullet and witherskull too? Because in the latest update there was mentioned:

> New permission node as cmi.command.shoot.[type] to allow usage of specific shoot types. Fun side note, shulker bullet could be nice addition for players as paid command which can track players if target is provided, could even be used as tactical advantage in pvp situations. Just an idea for you to play around.

So I expect that we can use another types too, but from some reason luckperms doesn't suggest them

**Comment by CloudeLecaw** [comment]
Try If You can shoot it before. If You can then. Its
cmi.command.shoot.[type]
The list for types You find here:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html

Well might be funny to Test If You can shoot a cow... :-D

**Comment by Zrips** [comment]
@CloudeLecaw 
You cant shoot cow's, those are not projectiles.
@Volgeop 
Will fix spelling

**Comment by Volgeop** [comment]
And about projectiles, why there's suggested just fireball and arrow? Can I use there witherskeleton, shulkerbullet etc. as well?

**Comment by CloudeLecaw** [comment]
The witherskeleton ist no Projectile ;) I also Know cows are Not *g*
The bullet of the shulker should be use able :)
