### ISSUE TITLE
/gamerule <world> <gamerule> <value>

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4561]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, could you try make one of these things please:
1. Add way to execute /gamerule <specific_world_name> with tab completion to open specific world gamerule page. May also with permission cmi.command.gamerule.<world>
OR
2. Allow setting gamerule with normal vanilla command, where we can also specify specific gamerule and value if we provide these information, so: /gamerule will still open gamerule menu, but /gamerule doFireTick (tab completion could be included) true will set specific gamerule in actual world. May if we can specify world too, would be probably good option, something like /gamerule <world> <specific_gamerule> <value>
THE BEST SOLUTION
If you can combine it, so we can make /gamerule -> open normal actual menu of gamerule of worlds
/gamerule <world> -> open menu of gamerules on specific world page
/gamerule <world> <gamerule> <value> - set specific gamerule value in specific world

### Basic explanation as to why this feature is needed and/or useful to have: ###
This feature could be very useful when you have a lot of worlds on your server and it's so difficult and annoying to click over and over through so many pages (52 here) for ex. from first page to the last one, and then again back.... when you wanna for ex. "copy" gamerules from first page to the latest, it's annoying to click over all these pages.
![image](https://user-images.githubusercontent.com/18662086/98532870-8d7ffc00-2282-11eb-96c3-58a2d324e815.png)

Now, why I have so many worlds? Cause I have Player worlds plugin, so for me it's difficult to set normal worlds gamerules when I have to click over all player worlds in gamerule list. Also... would be nice if I could add players permission to edit gamerules in their own world, so if you could add cmi.command.gamerule.<world>, and maybe cmi.command.gamerule.<world>.<gamerule> (best option), I could allow them to set gamerules in their own world and this would be fantastic too. Cause now I can't imagine how can I let players set gamerules only in their world.... by normal vanilla command, I can allow command /gamerule only in their world, but with actual CMI mechanism they can set via /gamerule gamerules for ALL worlds, not only for their world... So for now I can't do this probably and I would be happy if you try to improve it for better usage by admins (I still think that we should be able to use normal /gamerule <gamerule> <value> atleast, cause it's sometimes faster than click over GUI pages and then search specific gamerule in the list) and also if you could try to help me support setting gamemodes in player worlds.

PS: Maybe you can also add back button, so from first page you can go to the latest page if it's possible.

**Comment by CloudeLecaw** [comment]
You allready can do this with cmi in tabcomplete.
Whats your issued with ist?

**Comment by Zrips** [comment]
Will make some adjustments to be more convenient

**Comment by Volgeop** [comment]
Btw edited post with [] instead of <>, maybe read it again please, I didn't know that <> disappeared.

**Comment by CloudeLecaw** [comment]
Ohh now your Suggestion makes more sense😆

**Comment by Volgeop** [comment]
Don't know why are < > removed sometimes, but I mentioned it happened already in another web editor
