### ISSUE TITLE
VanishListener lags with minecart

### ISSUE THREAD

**Issue by Kapitowa** [Zrips/CMI#4562]
**Description of issue:**
Server laggy with this event.
![image](https://user-images.githubusercontent.com/62211966/98539943-8ff44d00-22a6-11eb-99cc-3dcd8b11aa2a.png)

**Cmi Version (using`/cmi version`):** 
8.7.10.3
**Server Type (Spigot/Paperspigot/etc):** 
Tuinity (fork of paperspigot)
**Server Version (using `/ver`):** 
1.16.4

**Comment by Zrips** [comment]
2 392 943 922 collision events? You might want to investigate what causing this, tho i will have a look what i can optimize relating to this event in particular.
