### ISSUE TITLE
Autorecharge not working

### ISSUE THREAD

**Issue by EkonC** [Zrips/CMI#4565]
**Description of issue:**
Autorecharge is not working for one of my players. I tried to do exactly the same he did in this video but couldn't reproduce it. For me it works perfectly.
https://ctrlv.tv/LIQ5

**Cmi Version (using`/cmi version`):** 
8.7.10.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper(253)
**Server Version (using `/ver`):** 
git-Paper-253 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Wild guess, he disabled autorecharge by using /autorecharge off or similar. Simply inform him to use /autorecharge money which should reenable it.
