### ISSUE TITLE
Not Async WarmUpManager

### ISSUE THREAD

**Issue by Kapitowa** [Zrips/CMI#4567]
**Description of issue:**
Not async event, sometimes server have lags.
![image](https://user-images.githubusercontent.com/62211966/98575444-aa442000-22d2-11eb-9904-dec438cbc6d7.png)

Can you do this event async?
---
config:
![image](https://user-images.githubusercontent.com/62211966/98575989-52f27f80-22d3-11eb-8e42-0ca79d2c6bc1.png)
---
**Cmi Version (using`/cmi version`):** 
8.7.10.2
**Server Type (Spigot/Paperspigot/etc):** 
tuinity (for of paper)
**Server Version (using `/ver`):** 
1.16.4

**Comment by Zrips** [comment]
Lag comes not from warmup manager itself but from commands its performing after warmup ends. In this case would be random teleportation which can be heavy on server especially if you don't have pre generated world.
