### ISSUE TITLE
Going semi-open source

### ISSUE THREAD

**Issue by Wertik** [Zrips/CMI#4568]
**Question:**

Due to how many open issues there are and how much this plugin covers, I think it would be a great step forward to provide source to at least a closed circle of developers to help speed up fixing issues and implementing more new features.

So my question is, do you agree and will you do it?

**Comment by CloudeLecaw** [comment]
u may shoudl wrote Zrips diectly in discord and not creat a ticket for this ;)

**Comment by Wertik** [comment]
> u may shoudl wrote Zrips diectly in discord and not creat a ticket for this ;)

Well it's a general suggestion and here it can gather opinions from others. AlsoI doubt Zrips would ever see my DM. His discord has to be spammed hard.

**Comment by Wertik** [comment]
A good implementation of this would be creating a bounty system similar to what Songoda does. But I bet people will fix issues and/or implement new features even for free.

**Comment by MoonSoD** [comment]
Well, looking at the current number of issues (990) the suggestion seems pretty on point. Possibly a big leap forward for CMI.

**Comment by GcGoat** [comment]
Going semi-open source on a paid plugin is a strange way to do things. I mean, yea, there are people who could fix things better then i do or help out in fixing most minor things, as those can take as much time in testing as bigger ones while fix itself could be quite simple. Thing would be in actually properly setting things up for some random people to have access to actual source code. Even tho CMI is not obfuscated, so its not like i'm hiding its code or something... But well, again, circling back to the main point, its a paid plugin and having someone to help out on its development for free is some what strange. 
Tho, it is interesting idea.

**Comment by Zrips** [comment]
Going semi-open source on a paid plugin is a strange way to do things. I mean, yea, there are people who could fix things better then i do or help out in fixing most minor things, as those can take as much time in testing as bigger ones while fix itself could be quite simple. Thing would be in actually properly setting things up for some random people to have access to actual source code. Even tho CMI is not obfuscated, so its not like i'm hiding its code or something... But well, again, circling back to the main point, its a paid plugin and having someone to help out on its development for free is some what strange. 
Tho, it is interesting idea.

**Comment by the456gamer** [comment]
There are some projects that have successfully implemented this, by only providing compiled jarsfiles to those who pay, because most people would pay for the convenience of having a jarsfile premade

**Comment by Wertik** [comment]
Yeah, you're talking about a good point, I've been thinking about this too. But that's also why I suggested going only "semi-". What you could do is pick out a closed group of developers throughout the community, who are insterested and are skilled enough to help you maintain the project on a bigger scale. (only talking about 5-10, maybe even less people)

About people working for free on a paid plugin, this is your choice and theirs. You sure make some money from your plugins (or just CMI), so a better model for this would be probably doing bounties and let people pick a bounty, or rather do it for free.

Setting this up could be as simple as creating a private discord server with a join room (for requests and getting a role), then on github either setting up an organization (better for access maintanence than single contributors).

Now, more points I'd like to make is that you could use this to learn a bit more about how to work in a team. It also opens up a way to meet more developers. There have been a lot of teams and orgs forming up recently, if you meet the right people, you could take your plugins even further.
