### ISSUE TITLE
[Feature Request] Remove/Increase walkspeed/flyspeed max limit

### ISSUE THREAD

**Issue by DaniDipp** [Zrips/CMI#4570]
**Description of feature/improvement request:**
Remove or increase the limit of `10` from the `/cmi walkspeed` and `/cmi flyspeed` commands.

---
### Detailed explanation of what it should do, when and in what situation: ###
Currently, the maximum speed of `/cmi walkspeed` and `/cmi flyspeed` is `10`, even with the `cmi.command.walkspeed.*` & `cmi.command.flyspeed.*` permissions.
It would be cool if this limit could be removed (maybe with a warning in the config, if there are stability concerns) or increased to like 100 if flat out removing it is not possible.

### Basic explanation as to why this feature is needed and/or useful to have: ###
From Essentials, my friends and I are used to a speed of 10-15 for quickly getting around. And they always remind me that Essentials could do this before I switched us over to CMI ^^

**Comment by CloudeLecaw** [comment]
have you ever moved with flyspeed 10?...
well good luck with speed 100.... *lol*
there is a reason for this. The reason is no server can create a chunks faster you would stuck in a area of unloaded chunks with a milliosecounds of moving

**Comment by DaniDipp** [comment]
I didn't mean to say that I would use flyspeed 100. I meant that I'd like the option for server operators to set their own limit based on their individual experiences, preferences and server hardware.

**Comment by CloudeLecaw** [comment]
But 10 is more then enough even with the strongest Hardware. with 10 you fly a few 1000 Block within a few secounds.faster then your pc can setup chunks. Have You ever tried speed 10?
The normal Player has speed 1 and you allready can set it higher with a decimal number. High then the current 10.0 does not really make sense. Even if you have an ultimate hyper server.

**Comment by DaniDipp** [comment]
> But 10 is more then enough even with the strongest Hardware.
That's a very subjective statement. If there is no technical reason for using this specific number as a limit, why not let people choose one they are most comfortable with in their current situation, even if it's just 11 or 15?

**Comment by CloudeLecaw** [comment]
15 would be a breaker, no Matter how strong the Hardware is. Having values like 15 just would let the next one come and wanting 20 and so on..
No 10is a sensfull limit allready.more Speed is just swirlling of pixels

**Comment by Zrips** [comment]
Its hard limited by server itself. Player cant have bigger speeds than 10, otherwise that could introduce issues with server not keeping up with players movement. 10 is already more than enough in most case. Other than this, you can suggest this to Mojang, as this limit was set by them, or by spigot team or someone, no idea, but its limited at server end and not CMI.
