### ISSUE TITLE
[Question] Just some questions about migrating CMI to a MySQL database.

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#4571]
**Question: **
If I migrated my database from SQLite to MySQL and used this across a network would it be able to transfer bans across the network, I know this is a dumb question. I'm assuming it can, just want to make sure.
I know it says to not touch them if you don't know what they do. I am just curious as to what exactly AutoReconnect, UseSSL, and verifyCertificate do in the server.
Would the balances of players be stored in the MySQL database if I migrate, and would that mean players balances would be the same over all servers? Or, would they be separate.

This question could be asked better with this: What kind of data to CMI store inside it's database?

**Comment by AZFire1** [comment]
Can the UseSSL possibly replace BungeeGuard? Just guessing :p

**Comment by CloudeLecaw** [comment]
Cmi stores nearly all impotant data in the MySQL that it does.
Some are usually not stored Like skins.
If u wanne see what is storedninnit the best You can do is setup your mysql. Start the server join once, and then you wil see the tables itbcreates.

But to your Questionen. Yeah if all your bungies connected to the same mysql then all have the same balances.

**Comment by Zrips** [comment]
As stated in databaseinfo file mysql cant be used to sync data across multiple servers, you will risk getting some issues if you did that. One table needs to be for one server at this moment. If you dont need mysql to use it as a access point from outside, like showing on a web page, then there is no real point in converting. sqlite ir more than enough and its allot simpler to make backups of it and restore when needed
