### ISSUE TITLE
[Question] Can't find where to edit this specific thing in the lang file.

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#4574]
**Question: **
![image](https://user-images.githubusercontent.com/67762583/98620499-272bc580-22e4-11eb-8e16-fb397f34c416.png)

![image](https://user-images.githubusercontent.com/67762583/98620393-04011600-22e4-11eb-9dab-f63c3c59fce9.png)
The ranks are shown as gold, I can't find where I could change that. Would anyone be able to help, it's probably in plain sight though I missed it.

**Comment by CloudeLecaw** [comment]
You find it in the rank.yml not in the language File

**Comment by Zrips** [comment]
Small inconvenience. It was hard codded to set its color to gold. Will update that part. but in general you can use rank display name to set its color. If you want it to be different then simply wait for next version which will allow to properly set its color in locale file under rankinfo->nextRanks locale section
