### ISSUE TITLE
[Question] How do I get the "kickreason" section of CMI land file to work?

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#4575]
**Question: **
Currently, whenever someone gets kicked they just get kicked for the default reason like a minecraft kick. I'd like to use the CMI kick reason section of the lang file. I looked through the config.yml, I noticed there was a "OverrideLoginMessage" thing for Bans where CMI overrides the login "banned" message with it's own. I couldn't find a section like that for kicks where CMI overrides default kick messages. 

![image](https://user-images.githubusercontent.com/67762583/98628567-a4ac0180-22f5-11eb-8863-62d300da220b.png)

**Comment by CloudeLecaw** [comment]
If You write /cmi kick Player2 the Default reason from langfile is taken
If you write/cmi kick Player2 Kicked for this then "Kicked for this is the reason that will be posted to chat amd playerGotKickedScreen ist

**Comment by AZFire1** [comment]
If I type "/kick (name)" the default reason is "&eKicked from server" in the lang file though what is shown to me is "Kicked by an operator"

**Comment by CloudeLecaw** [comment]
make sure your custom alais leads to kick else you execute the vanilla /kick (alias.yml)```
  # /cmi kick $1-
  /kick: true
also try /cmi kick to make sure no other plugin is overwriting it.
kicked by an operator sounds like the vanilla command

**Comment by AZFire1** [comment]
I do have the alias enabled. It is CMI kick. It still says I was kicked by an Operator rather than the default reason.

**Comment by AZFire1** [comment]
By any chance could I have you look over some previous issues I've made so I could just get them all solved?

**Comment by Zrips** [comment]
If you are using CMI kick command which could be tested by using full command like **/cmi kick Zrips** then default message will be shown which is defined under defaultMessage section in locale file. In case you will provide some text while kicking player, like for example "/cmi kick Zrips &cBad boy" then this message will be shown to the player. If you are getting different results while using alias command then that would mean that another plugin overrides kick message. And even then, test this without any other plugin as there is actual bukkit event as PlayerKickEvent which could be modified and resulting kick message could be changed in it which would override CMI set message.
