### ISSUE TITLE
Shoot - double names in tab completion, missing tab completion and leash_hitch doesn't work

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4576]
**Description of issue:**

---
Hi, since the latest CMI update you introduced many new ways to /shoot entities... but there are some problems.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
![image](https://user-images.githubusercontent.com/18662086/98668797-ace55a80-2350-11eb-90aa-268f0c7f1540.png)
![image](https://user-images.githubusercontent.com/18662086/98668817-b40c6880-2350-11eb-9aac-54c91a20f66b.png)
![image](https://user-images.githubusercontent.com/18662086/98668836-bb337680-2350-11eb-96de-459fe1e646e1.png)
![image](https://user-images.githubusercontent.com/18662086/98668948-e7e78e00-2350-11eb-9b0f-80e38be85c2e.png)
Probably with _ it's from previous version. But then I'm confused if I should use for ex. witherskull or wither_skull in cmi.command.shoot.[witherskull/wither_skull/??].

Leash hitch doesn't work neither... it shows just help page.
![image](https://user-images.githubusercontent.com/18662086/98668979-f6ce4080-2350-11eb-980f-b47752dcb014.png)

And for 2 newly added "entities" into shoot mentioned in the latest release notes:

> Added enderpearl, splashpotion, firework, dragonfireball and then said, hell with it, have all of them, so added every other entity out there. So now you can shoot pig's if you want too. And keep in mind that entities can be defined in similar way as you can with spawnmob command, so /cmi shoot pig:baby will shoot baby pig. Entities will not suffer fall damage after you shoot them, so you can go crazy with that.

There's missing tab completion for splashpotion and firework, so it seems that these two doesn't even exist.
![image](https://user-images.githubusercontent.com/18662086/98669052-19f8f000-2351-11eb-9eca-879f7078c91f.png)
But both of them works.

---

**Cmi Version (using`/cmi version`):** 8.7.10.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 265

**Comment by Zrips** [comment]
Will fix those. Tho its only visual bug. You can still use /shoot splashpotion and similar, its just  absent from tabcomplete

**Comment by Volgeop** [comment]
And about permission, is it correct with _ or without? Like shulker_bullet or shulkerbullet?
