### ISSUE TITLE
Way to let usage of /mirror for normal players - for ex. as perk for VIps

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4577]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, I wanna suggest, as I asked here https://github.com/Zrips/CMI/issues/4573, that could be option in config that will make onew new condition for mirror - players with gamemode survival/adventure would need material to use this feature. So, they won't have unlimited material and couldn't duplicate blocks etc. with it, cause /mirror will only works if they will have enough material (for ex. 3 stacks of cobblestone) in inventory, when the material would be consumed or would miss, then it should stop mirroring. Would be nice if it will be as config option, or may built by default (players with survival and adventure will automatically need material to use /mirror).

Also important would be to make /mirror accept protections, like from Residences, may WorldGuard etc.

### Basic explanation as to why this feature is needed and/or useful to have: ###
It could be useful for ex. as perk for premium ranks, cause we could allow them to build easier some symetric buildings and I think it could help them and simplify them their work.

**Comment by Zrips** [comment]
Have you tested this in survival mode? As there is already a code which will take blocks from your inventory to place them when mirroring things

**Comment by Volgeop** [comment]
No, that's why I opened https://github.com/Zrips/CMI/issues/4573 and asked, I didn't get how it exactly work, but I'll try to test it again.

**Comment by Volgeop** [comment]
OK, then closing and moving to https://github.com/Zrips/CMI/issues/4581, seems it works as it should, but there are issues.
