### ISSUE TITLE
Full rules system

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#458]
A rules system where players are forced to agree to the /rules upon joining.
An additional command to add would be /rulesreset which forces everybody to accept the rules again upon joining the server (this is good if the rules get updated/changed).

**Comment by tmellen** [comment]
Force everyone to join the server as a noob with no perms, and the last line of the rules says "to agree with these rules type "/agreed" and have /agreed be an alias to rankup to a real rank which allows for all your real perms for /rtp/spawn/home/etc etc etc?

**Comment by TheWranger** [comment]
I considered something like but that I still believe this should be properly implemented as feature. I want to restrict players from being able to do anything on the server (move, talk, etc.) and I think it would be inefficient to rely on permission groups for this.

**Comment by LogGits** [comment]
Sorry for the late reply, there are plugins capable of achieving this and due to time constraints we will not be adding this feature.
For more info: https://www.spigotmc.org/resources/accept-the-rules-1-9-1-15-x-forces-players-to-read-and-accept-your-rules.53775/
