### ISSUE TITLE
/cmi info and /seen do not work with offline players

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#4582]
CMI-Version: 8.7.10.4

Paper version git-Paper-267 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

Since we have problems with the Msql database, we wanted to switch back to sqlite. Now we have found that you can only access the data for online players. For offline players, /cmi info and /seen do not work. is that wanted so that he doesn't ask offline players?

with / cmi info nothing comes up and with / cmi seen comes the last time it was online. But otherwise you could always click on the name and the info file always appeared. but this doesn't work

Once the player has been to the server, his data can also be queried offline. To do this, however, the player must have been online at least once after the database transfer. You have no access to offline players. Is it wanted like that?

**Comment by Zrips** [comment]
If there isint actual player data file in your world folder then it might fail at loading players data. Tho that would mean that you have cleared player data files. Have you done any changes relating to that?

**Comment by Blueeyestar** [comment]
no as soon as I reactivate Mysql he has access to it again. As I said, users only have to be online once, then they have direct offline access to the file

**Comment by Zrips** [comment]
So user files do exist in world folder, you just switch between database types? But that doesn't really make any sense as there should not be any difference between those types. That's some strange issue you have here. Player file is loaded by player UUID which is saved in a database, so converting into another database system should not have any effect on that action in particular.
