### ISSUE TITLE
BUG [item]

### ISSUE THREAD

**Issue by Rompepitas** [Zrips/CMI#4583]
What happens is that when I use [item] on a shulker that contains renamed items with gradient colors it automatically kicks you off the server. As evidence I attach a video.

[https://www.youtube.com/watch?v=HIrDp_gfssQ&ab_channel=Blotcraft]
---
`11.11 14:06:44 [Server] ERROR Could not pass event AsyncPlayerChatEvent to CMI v8.7.10.4
11.11 14:06:44 [Server] INFO java.lang.AssertionError: java.io.UTFDataFormatException: encoded string too long: 144135 bytes
11.11 14:06:44 [Server] INFO at com.google.common.io.ByteStreams$ByteArrayDataOutputStream.writeUTF(ByteStreams.java:584) ~[patched_1.16.3.jar:git-Paper-208]
11.11 14:06:44 [Server] INFO at com.Zrips.CMI.Modules.BungeeCord.BungeeCordManager.sendPublicMessage(BungeeCordManager.java:366) ~[?:?]
11.11 14:06:44 [Server] INFO at com.Zrips.CMI.Modules.NickName.NickNameListener.AsyncPlayerChatEventRawConverter(NickNameListener.java:205) ~[?:?]
11.11 14:06:44 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor538.execute(Unknown Source) ~[?:?]
11.11 14:06:44 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-208]
11.11 14:06:44 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.3.jar:git-Paper-208]
11.11 14:06:44 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-208]
11.11 14:06:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-208]
11.11 14:06:44 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.chat(PlayerConnection.java:1821) ~[patched_1.16.3.jar:git-Paper-208]
11.11 14:06:44 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.3.jar:git-Paper-208]
11.11 14:06:44 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.3.jar:git-Paper-208]
11.11 14:06:44 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
11.11 14:06:44 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
11.11 14:06:44 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
11.11 14:06:44 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
11.11 14:06:44 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
11.11 14:06:44 [Server] INFO Caused by: java.io.UTFDataFormatException: encoded string too long: 144135 bytes
11.11 14:06:44 [Server] INFO at java.io.DataOutputStream.writeUTF(DataOutputStream.java:364) ~[?:1.8.0_252]
11.11 14:06:44 [Server] INFO at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323) ~[?:1.8.0_252]
11.11 14:06:44 [Server] INFO at com.google.common.io.ByteStreams$ByteArrayDataOutputStream.writeUTF(ByteStreams.java:582) ~[patched_1.16.3.jar:git-Paper-208]
11.11 14:06:44 [Server] INFO ... 15 more`

Cmi Version (using`/cmi version`): CMI version 8.7.10.4

Server Type (Spigot/Paperspigot/etc): Paper

Server Version (using `/ver`):Paper version git-Paper-208 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Latest paper version is git-Paper-253, so you are 45 versions behind. I cant resolve issue which is none existent in newest version. Update your server to latest paper version and if you will still have issue open new ticket and provide exact command you used for that item. Other than this as of testing i cant bug it out, new version seams to remove bigger item names so its resolving this bug, even tho its already mainly on server side and not CMI.
