### ISSUE TITLE
Find why spawners not work when players is AFK

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#4584]
When players are AFK, the spawners turn off. 

The reason is when a player are in vanish, it cancel spawn of spawners for other players not mater where vanish player are on the map. I have done massive search for the issue. 

**Cmi Version (using`/cmi version`):** 
 8.7.10.4 and  8.7.10.3
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
184
**Relevant plugins (Delete if this isn't needed):**
cmi

**Comment by CloudeLecaw** [comment]
You know you can disable spawning of mobs of spawners in the config? Have you disabled it?

**Comment by broken1arrow** [comment]
OFC I have check soo it is not true @CloudeLecaw . I think is the change zrips made at vanish player can not spawn mobs. 

The players some get the problems are not vanish, only normal players. So ether zrips have to fix it or remove mobSpawning in vanish.

I have två reasons way

1. because if a server uses this, the player can either command or stand still by detecting if there are invisible staff online (through it ends spawn mobs, although most players do not notice it, but know some are so sharp that they would figure this out).

2.If you have not turned on it to stop spawning mobs for ordinary players, this setting for vanish should not affect normal players who are afk.

```  PreventMobSpawning:
    # When enabled we can prevent mob spawning near players who are afk
    Enabled: false
    # Prevents natural mob spawning
    # This can be more on heavy side of the server as it will try constantly to spawn in monsters near afk players
    Natural: false
    # Prevent mob spawning from spawners
    Spawners: false
    # Usually responsible for spawning in iron golems
    VillageDefence: false```

**Comment by Zrips** [comment]
Reproduced, should be fixed with next build
