### ISSUE TITLE
DisableEnchant does not prevent villager trading for disabled enchantment books

### ISSUE THREAD

**Issue by 27chandler** [Zrips/CMI#4587]
**Description of issue:**
When an enchantment is disabled using /disableenchant it can still be gained from trading with villagers
---

**Cmi Version (using`/cmi version`):** 
8.7.10.4
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
Paper-253 (MC: 1.16.3)

**Comment by CloudeLecaw** [comment]
but have u ever traded a book from a villager? ;)
When you have it it become a ordinary book:3

**Comment by 27chandler** [comment]
I just tested again, the villager trading for a thorns I book still gave me (and regular players) the book without converting it into a default book

**Comment by 27chandler** [comment]
I did some extra testing and it turns out it may be an issue with the disable enchantment feature not removing the disabled enchant if the player moves the item using shift clicking

**Comment by 27chandler** [comment]
Just to add, as long as the player shift clicks an enchanted book to move it through their inventory, it does not reset itself to a blank enchant book (the same goes for armour with the disabled enchant)
