### ISSUE TITLE
Combat Mode issue

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#4589]
**Description of issue:**

Since a couple of weeks after players teleport and try to kill a mob, sometimes the mob gets a nametag.
I am not entirely sure this is from the Combat Mode, nor if it's related to teleporting. As I don't have access to my own laptop till next week and this is a report from multiple players.

![image](https://user-images.githubusercontent.com/5664135/98993842-4a968080-252f-11eb-873e-fcdf333a7abf.png)

**Comment by Zrips** [comment]
CMI doesn't enable mob tags in any shape or form, so this should be unrelated to CMI in general and definitely not related to combat mode. You might want to test this on some test server with CMI only or atleast reproduce it some what on consistent basis, but in general, this should not be originating from CMI.
