### ISSUE TITLE
Issue with PERMSSIONS

### ISSUE THREAD

**Issue by PretendBullet50** [Zrips/CMI#459]
I am having an issue with CMI! Basically, I use PEX and have PREFIXES! I am trying to make CMI a FULL REPLICA of ESSENTIALS but unfortunately, I cant with this error! When I remove essentails PEX will not display the PREFIX. When I install Essentails and Esstails Chat it works again! Is there someehere in a file i mieesed for CMI or another pkug in I am supposed to use?

**Comment by TheWranger** [comment]
Make sure `ModifyChatFormat` is set to true.

**Comment by PretendBullet50** [comment]
Where would this be?

**Comment by PretendBullet50** [comment]
Ok so it partally working! However the Suffix wont show is this normal? How do I make the suffix show?

**Comment by TheWranger** [comment]
Take a look at general format `GeneralFormat`, you can choose where you want the suffix to be by adding in {suffix}

**Comment by PretendBullet50** [comment]
Worked Thank You

**Comment by MCTyler** [comment]
Please READ all the CMI overview and WIKI prior to posting issues.
