### ISSUE TITLE
/fix still adding a cool down for both /fix all, hand, etc

### ISSUE THREAD

**Issue by Skizzles** [Zrips/CMI#4590]
**Description of issue:**
/cmi repair continues to add a cooldown for all instances of repair.
---

**CONFIG SECTION:**
```
  Enabled: true
  List:
  - cmi heal:300
  - cmi feed:300
  - cmi repair all:86400
  - cmi repair hand :10800
  - cmi repair:10800
```

---

**Cmi Version (using`/cmi version`):** 
8.7.10.4
**Server Type (Spigot/Paperspigot/etc):** 
Yatopia (Paper fork)
**Server Version (using `/ver`):** 
1.16.4-R0.1-SNAPSHOT
**Relevant plugins (Delete if this isn't needed):**
N/a

**Comment by Volgeop** [comment]
Yeah can confirm that.

**Comment by Skizzles** [comment]
@Zrips Sorry for @ but any update? you had stated it was fixed in a previous release but it still does not work.

**Comment by tankinnwow** [comment]
I can confirm i am having the same issue. In order to give someone '/repair hand" The cooldowns are giving me a migraine. I had to find a plugin to handle some of the CMI commands that are giving me issues with cooldowns
