### ISSUE TITLE
Experience Placeholders

### ISSUE THREAD

**Issue by TheExceed** [Zrips/CMI#4591]
I would like to request placeholders for players experience.
I understand PAPI Player Expansion has these however, they do not have a current amount of EXP.
Their player xp placeholder returns the percentage to next level.
This is important for a Quest I want to create.
There are 4 placeholders I would like:

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
**Current Experience Amount** - returns integer 
Current Amount of Exp the player has
%cmi_user_current_exp%

**Experience to next level** - returns integer
Experience needed for next level
%cmi_user_exp_to_next_level%

**Experience % to next level** - returns a formatted %
Experience needed for next level
%cmi_user_exp_to_next_level_percent%

**Experience Total** - returns integer 
Total experience since joining
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

**Comment by Zrips** [comment]
Will add with next update

**Comment by TomLewis** [comment]
@Zrips 
1. This isnt on https://www.zrips.net/cmi/placeholders/
2. When I give a user exp CMI displays it wrong, im on Paper 1.12.2 and when I do /exp give <user> Essentials shows the correct Exp but CMI does not, I gave a user 1000 exp to test it and in CMI it shows as 3!
3. Are there Level placeholders as it seems to show levels correctly in /cmi exp
