### ISSUE TITLE
fromConsole! and asConsole! ?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4593]
Inside the wiki customalias there are example that introduce fromConsole!

> Alias with delay in commands:
> – fromConsole! cmi launch [playerName]
> – delay! 3
> – fromConsole! cmi launch [playerName]

looking into Specialized Commands inside the wiki there you only find asConsole! but no information about fromConsole!

i renember we allready using some custom alias that using fromConsole! But since its not defined in Specialized Commands could it be that the alias simply executes asConsole! ? or does fromConsole! really exists and its just missing in the wiki?

**What i aspect:**
fromConsole! - starts a custom alias or comand complety from console even if its follow by other commands they will be executed from console..
asConsole! - starts a custom alias or single command only as it would be executed directly from console but not directly from console. 
Diffference? asConsole! just exectes the current line as console, fromConsole! start all following commands from Console.
asConsole the executer is still the player - fromConsole the executer is the console

**Comment by Zrips** [comment]
There is no difference, fromConsole! is an old variable and it was changed to asConsole! to match asPlayer! variable when that got added, tho fromConsole! and asConsole! will work in any case. I might need to check where old format is still shows up and update that to avoid confusion.
