### ISSUE TITLE
BUG [ITEM] part 2

### ISSUE THREAD

**Issue by Rompepitas** [Zrips/CMI#4594]
Hello now I have updated the paper and I still have the same error. The server configuration is the default so I don't understand what it could be. In turn, I also reinstalled the CMI and it keeps giving me the same error with the same message. And all of this is caused by putting [item] in a shulker that contains many items with degraded renames.

`13.11 10:29:37 [Server] ERROR Could not pass event AsyncPlayerChatEvent to CMI v8.7.10.4
13.11 10:29:37 [Server] INFO java.lang.AssertionError: java.io.UTFDataFormatException: encoded string too long: 144125 bytes
13.11 10:29:37 [Server] INFO at com.google.common.io.ByteStreams$ByteArrayDataOutputStream.writeUTF(ByteStreams.java:584) ~[patched_1.16.4.jar:git-Paper-275]
13.11 10:29:37 [Server] INFO at com.Zrips.CMI.Modules.BungeeCord.BungeeCordManager.sendPublicMessage(BungeeCordManager.java:366) ~[?:?]
13.11 10:29:37 [Server] INFO at com.Zrips.CMI.Modules.NickName.NickNameListener.AsyncPlayerChatEventRawConverter(NickNameListener.java:205) ~[?:?]
13.11 10:29:37 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor511.execute(Unknown Source) ~[?:?]
13.11 10:29:37 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-275]
13.11 10:29:37 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Paper-275]
13.11 10:29:37 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-275]
13.11 10:29:37 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-275]
13.11 10:29:37 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:1920) ~[patched_1.16.4.jar:git-Paper-275]
13.11 10:29:37 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1835) ~[patched_1.16.4.jar:git-Paper-275]
13.11 10:29:37 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1773) ~[patched_1.16.4.jar:git-Paper-275]
13.11 10:29:37 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.4.jar:git-Paper-275]
13.11 10:29:37 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
13.11 10:29:37 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
13.11 10:29:37 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
13.11 10:29:37 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
13.11 10:29:37 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
13.11 10:29:37 [Server] INFO Caused by: java.io.UTFDataFormatException: encoded string too long: 144125 bytes
13.11 10:29:37 [Server] INFO at java.io.DataOutputStream.writeUTF(DataOutputStream.java:364) ~[?:1.8.0_252]
13.11 10:29:37 [Server] INFO at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323) ~[?:1.8.0_252]
13.11 10:29:37 [Server] INFO at com.google.common.io.ByteStreams$ByteArrayDataOutputStream.writeUTF(ByteStreams.java:582) ~[patched_1.16.4.jar:git-Paper-275]
13.11 10:29:37 [Server] INFO ... 16 more`

**Cmi Version (using`/cmi version`):8.7.10.4 BungeeCord  SqLite** 

**Server Type (Spigot/Paperspigot/etc):Paper** 

**Server Version (using `/ver`):Paper(275) 1.16.4-R0.1-SNAPSHOT**

**Comment by Zrips** [comment]
Ok, reproduced, issue with minecraft silly item parser when it comes to json type format which includes bunch of unnecessary code... Should be fixed with todays update.
