### ISSUE TITLE
Equation Placeholder w PAPI

### ISSUE THREAD

**Issue by TheExceed** [Zrips/CMI#4597]
Hello, it seems there is an issue with papi placeholders being used in the equation placeholder for CMI.
`**Only placeholders starting with %cmi_ will be used by PlaceHolderAPI, but all of them can be used by CMI in most of places.**`

Here is a cmi placeholder in the equation.
https://prnt.sc/vitw7c

Here is a PAPI placeholder.
https://prnt.sc/vitwoo

Here is the same PAPI placeholder in the equation.
https://prnt.sc/vitx90

Here is another PAPI placeholder.
https://prnt.sc/vity4f

Here is another PAPI placeholder in the equation.
https://prnt.sc/vitxpz

Tried it with several numeric placeholders, none worked.

**Comment by Zrips** [comment]
Will be fixed with next build
