### ISSUE TITLE
How do I get LuckPerms Prefixes/Suffixes working with CMI? 

### ISSUE THREAD

**Issue by ravearcade** [Zrips/CMI#4598]
**Question: **

None of my luck perm prefixes and suffixes are working when I have CMI installed on my server. I'm running 8.7.10.5 on a 1.15.2 paper server. I saw in an old thread to turn off chat handlings but I don't see it in the config.. Ideally I I would use ChatControl for chat formatting and luck perms for permissions with CMI for everything else. 

Any help would be greatly appreciated.

**Comment by CloudeLecaw** [comment]
Simply with PlaceholderAPI installed ;)

```
LuckPerms
/papi ecloud download LuckPerms

%luckperms_groups%
%luckperms_primary_group_name%
%luckperms_group_expiry_time_<groupname>%
%luckperms_in_group_<group>%
%luckperms_has_groups_on_track_<track>%
%luckperms_first_group_on_tracks_<tracks>%
%luckperms_last_group_on_tracks_<tracks>%
%luckperms_lowest_group_by_weight%
%luckperms_highest_group_by_weight%
%luckperms_prefix%
%luckperms_prefix_element_<element>%
%luckperms_suffix%
%luckperms_suffix_element_<element>%
%luckperms_context_<contextkey>%
%luckperms_has_permission_<permission>%
%luckperms_inherits_permission_<permission>%
%luckperms_check_permission_<permission>%
%luckperms_expiry_time_<permission>%
%luckperms_inherits_group_<group>%
%luckperms_on_track_<track>%
%luckperms_inherited_expiry_time_<permission>%
%luckperms_meta_<meta key>%
```

**Comment by Zrips** [comment]
Ether use global variables like [prefix] [suffix] in a locale file, or use CMI placeholders like %cmi_user_prefix% %cmi_user_suffix% or use PAPI plugin to extract placeholders directly from LuckPerms
