### ISSUE TITLE
Improving /iteminfo

### ISSUE THREAD

**Issue by Tom25W** [Zrips/CMI#4601]
When using /iteminfo, the command prompts a message in chat, telling the user what item he is holding. Currently, this does not support any additional Information like a custom model data.

Add a new line that tells the user what custom item model id he is holding

It will then actually give me relevant and useful information about my item. 

Heres a picture of me using a custom item from Items Adder:
![2020-11-14_20 07 43](https://user-images.githubusercontent.com/31009575/99155157-b7d41e00-26b5-11eb-97fa-bbf844f6fb59.png)

**Comment by mrfloris** [comment]
Does /cmi itemnbt give you the additional info you're looking for perhaps? (Sorry, I have very little with modded items)

**Comment by Zrips** [comment]
Will add, simple addition, but yea, you could get that information with /itemnbt command, tho it can be not as convenient as it showing up in iteminfo window
