### ISSUE TITLE
Fly disabled on login

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#4602]
If you stand on the ground with fly enabled and you relog, fly is disabled instead of still enabled. It works fine when you logout when flying in the air though.

CMI 8.7.10.5
Tuinity 1.16.4

**Comment by CloudeLecaw** [comment]
This is nothing new ;)
To prevent this check your Multiverse settings, per world inventory settings or manage it with the login event command with checking players flyspeed or allow fly ifninnworld orninngamemode x

**Comment by Sikatsu** [comment]
That works for me too, unless you logout while standing on the floor with fly enabled. It's actually a recent change in CMI that caused this as it worked fine before..

**Comment by Zrips** [comment]
@Sikatsu 
Reenabling flight mode is directly dependent on players access to cmi.command.fly and cmi.command.fly.safelogin permission nodes. Tho i might remove second requirement as its some what not related
