### ISSUE TITLE
cooldown and delays timings

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4604]
Its just a small question.

Even if its written nowhere i renember that you told us in a thread that we can use delays smaler then 1 secound in specialed commands

well something like
delay 0.1!  for 1/10 secound....
now i wish i could have some simliar for cooldowns

So my question is:
Is it possible to use a cooldown condition like
cooldown:0.2!  -> would be 2/10 secound...

**Comment by Zrips** [comment]
Cooldowns work in seconds, entire system is set to work in full seconds for simplicity sake. I cant imagine where having cooldown with fractions would make big difference but for now its only in full seconds.

**Comment by CloudeLecaw** [comment]
Well we have a few players with old mouses that donsome kind of contact ticking. When they click onna signnit happens that minecraft let them do the interaction twice. First i tried it with delay. But then when their mouse tickers the commands get executed + they get the meassage wait command is allready executed (the specialed while running line) 
With cooldown! you can prevent this meassage.
In our case we talk about a sell sign where players allways sell amount of 1. So when they want to sell 10 and they allways need to wait 1 secound the whole processs seem very long. 
Our target is to avoid the double execution because of contact prelling (tickering) of some mouses.

May any Suggestion?
