### ISSUE TITLE
Load-UP NPE, Enchant Error-NPE

### ISSUE THREAD

**Issue by klaidoshka** [Zrips/CMI#4606]
**Description of issues:**

`1st issue) Server loads up and console is spammed for ~2secs(?) about the NPE error, it didn't exist in 8.7.10.4 CMI version.`
`2nd issue) After using enchant command on the hands with no equipment/tools, there comes error with no output.`

---

**ERRORS:**
```
##############################################################
1)# Load-UP NPE: https://pastebin.com/wKhzg9z0
2)# Enchant (main-hand) Error : https://pastebin.com/2XptWWBG
##############################################################
```

---

**• Cmi Version (using`/cmi version`):** `8.7.10.5`

**• Server Type (Spigot/Paperspigot/etc):** `PaperSpigot 1.8.8`

**• Server Version (using `/ver`):** `This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`

**Comment by CloudeLecaw** [comment]
paper 1.8.8 ....awww i realy hope one day people will update their relicts 👍 

but ok
have you tried to do this with a fresh cmi folder on a clean server?
Also try to redowload the jar

**Comment by klaidoshka** [comment]
> 
> 
> paper 1.8.8 ....awww i realy hope one day people will update their relicts 👍
> 
> but ok
> have you tried to do this with a fresh cmi folder on a clean server?
> Also try to redowload the jar

"Reclics" Haha, yeah, we're going to update to 1.16.X (together with CMI) in half-year or so... but for now the "testings" are going in 1.8.8 server 😊

.jar was absolutely new, but I still redownloaded it, used it on a fresh, clean server with no plugins - still the same.

**Comment by CloudeLecaw** [comment]
really strange we are also using this on our server (1.16.4 paper)
and even on a new tetserver i cant reproduce this (mean also with clean folder)

**Comment by klaidoshka** [comment]
> 
> 
> really strange we are also using this on our server (1.16.4 paper)
> and even on a new tetserver i cant reproduce this (mean also with clean folder)
> 
> where these NPEs come frome? on your server? may special items or something in cmis foldeR? :3

But are you on 1.8.8 Paper though? q_q
Because we are, so maybe that's the problem.. 😅

I have no idea where these NPEs come from, just pasted them into pastebin and gave the link 😓
It's happening on the load-up (and also "2nd issue" - when enchanting bare hand).

**Comment by CloudeLecaw** [comment]
hm i could setup a 1,8,8 paper small server and take a look - lets see

**Comment by Zrips** [comment]
Small bug, in general it only toss out error message but should not have any impact on actual plugin work. Will issue fix with next update
