### ISSUE TITLE
Towny's bankruptcy eco accounts are not created when towns move into bankruptcy.

### ISSUE THREAD

**Issue by SmallSansSerif** [Zrips/CMI#4607]
Creation of new town debt economy account (somewhat new feature in Towny) does not happen when towns falls into debt. Apparently there is something that you have to allow on your end that you already do for town and nation accounts. Those accounts work fine. Just need to get this new debt one working.

From what I understand it uses a similar format to the towns and nation eco accounts with debt- prefix before the town name.

@LlmDl had DM'd you back on Oct 2 about it and had not heard back. Can you make contact with him to resolve this as soon as possible?

<img width="522" alt="Screen Shot 2020-11-15 at 12 26 51 PM" src="https://user-images.githubusercontent.com/4984139/99191912-dda50580-273d-11eb-91fa-e1c2099ce2d3.png">

<img width="458" alt="Screen Shot 2020-11-15 at 12 17 10 PM" src="https://user-images.githubusercontent.com/4984139/99192152-46d94880-273f-11eb-87a6-a0b1213f0202.png">

---

CMI version 8.7.10.5
Tuinity version git-Tuinity-"957a2ef" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Towny version 0.96.3.4
Using the CMI build of Vault 1.7.3

**Comment by Zrips** [comment]
Should be fixed with next release
