### ISSUE TITLE
PERMSSION NOTES NOT WORKING AT ALL

### ISSUE THREAD

**Issue by PretendBullet50** [Zrips/CMI#461]
I have done the proper nodes based on the info I could do via google and here is what I have so far HOWEVER NOW ONE PERSON CAN USE THESE! Am I doing it wrong? 
![image](https://user-images.githubusercontent.com/29534385/40909704-131d8c48-679f-11e8-835b-6eaf5fad43c9.png)

**Comment by MCTyler** [comment]
If you need help with a Permission System, It might be best to contact the Author of "that" plugin. It looks like you use Obsolete Pex, so good luck.

**Comment by PretendBullet50** [comment]
Do you have a recmondation a Server Permission plug in?

**Comment by PretendBullet50** [comment]
I am tryin gto use LuckPerms but  its not wroking with CMI at all! ITs wroking with ESS-X but not CMI
Been on thier support site all night

**Comment by TheWranger** [comment]
This isn't the place to be asking about this. 

If you really want a recommendation, use Luck Perms,

**Comment by PretendBullet50** [comment]
I want to use LuckPerms but it not working! I have been in Support with them and they said to come to you guys for help!

**Comment by MCTyler** [comment]
https://github.com/lucko/LuckPerms/wiki

**Comment by Zrips** [comment]
@PretendBullet50 PEX is still in working condition and it should be completely fine with CMI.
What i can see from your example is that first of all you have funky permission node like cmi.command. which is not even a permission node. Next, you have only one actual permission node to use one command, its a spawn. All commands require base permission node to use it, like cmi.command.home or cmi.command.gm or cmi.command.sit and so on. You can check posible permission nodes ingame with /cmi checkperm [keyWord]
