### ISSUE TITLE
New bug when AFK on breaks block

### ISSUE THREAD

**Issue by OverBrave** [Zrips/CMI#4611]
**Description of issue:**

Last update:
```
Extra check for afk mode when player breaks block
```
This update, i think broke somethings
Look this, this players AFK on cobblestone generator and breaking blocks and CMI always saying:
"Player is now AFK, Player is no longer AFK."

![image](https://user-images.githubusercontent.com/47111280/99216838-c02c7600-27e7-11eb-8094-f86a1c11f407.png)

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/47111280/99216997-10a3d380-27e8-11eb-8c35-936e0d37dd78.png)

**Server Type (Spigot/Paperspigot/etc):** 
![image](https://user-images.githubusercontent.com/47111280/99217008-18fc0e80-27e8-11eb-9001-30e7d7d50ca0.png)

**Comment by Zrips** [comment]
Should be fixed with next build
