### ISSUE TITLE
Error with Multimap i think

### ISSUE THREAD

**Issue by Ashdeuzo** [Zrips/CMI#4615]
I have a problem with hologram from cmi, when i restart my server hologram don't work and i have an error.
Holograms are not in default map (like world, nether and end). I use multiverse-core for multimap. When i am on the map i /cmi reload and hologram work

---

Error : 
https://paste.helpch.at/bebipuhoxo.sql
https://paste.helpch.at/adenuqific.rb

---

CMI 8.7.10.5
Multiverse-Core 4.2.2 and tested with 4.2.3
Server Type: Paper 1.16.4 build: 282

**Comment by Zrips** [comment]
Should be resolved with next update
