### ISSUE TITLE
Combine chestplate and elytra

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#4616]
**Description of issue or feature request:**
This is a suggestion from one of my players, rather then installing a small seperate plugin for this I thought to suggest it here and see whether you are interested in adding such feature.

Their idea is an option so you can combine the chestplate and elytra.

**Comment by Zrips** [comment]
Sorry but no, this would require quite few things to be handled just to get this merge of items.

**Comment by Sikatsu** [comment]
Yeah, I thought so aswell!
