### ISSUE TITLE
/enchant - tab completion based on item

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4618]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, I wanna suggest tab completion based on item for command /enchant, so when you'll use /enchant cmd when holding pickaxe, it will suggest you efficiency, silk touch, unbreaking and other enchants related to this item. Same for other items.
### Basic explanation as to why this feature is needed and/or useful to have: ###
It will be useful to know which enchants could be used for specific items.

**Comment by Zrips** [comment]
Well some none standard effects could be applied in any case. You do have option to simply write **/cmi enchant** which will output list of valid enchants for that item, you can even click on each to get quick suggestion in adding that enchant

**Comment by bobhenl** [comment]
Oh, I didn't know, thanks.
