### ISSUE TITLE
Prevent placeholder to be parsed on private message

### ISSUE THREAD

**Issue by kelvin-junilson** [Zrips/CMI#4620]
**Description of feature/improvement request:**
Currently when players are entering a placeholder while messaging a player, a value of the placeholder will be parsed with the messaged player as the target. For example :
`/msg Zrips %cmi_display_name%` will turn into `[me->Zrips] Zrips`
---
### Detailed explanation of what it should do, when and in what situation: ###
There should be an option on the config to prevent placeholder to be parsed

### Basic explanation as to why this feature is needed and/or useful to have: ###
There are some plugins that would provide useful information through placeholderAPI about other player that needs to be kept private.

**Comment by CloudeLecaw** [comment]
On our server we changed the me with senderName in langfile.

Ifnyoubdint want this msg format (may in a custom alais or attachee command or interactice command, then use msg! [playerName] instead of cmi msg [playerName] then u dont have the command format...just a measage to target without anything before

**Comment by kelvin-junilson** [comment]
I don't think that you understand what I meant. I have no problem with the message format, I have a problem with the message parsing the placeholderAPI into an actual value.

To put it more simply say:

`/msg Zrips %example_bank_plugin_money%`
I don't want this to be parsed into
`[me->Zrips] $100.00`, and I wanted it to stay like this `[me->Zrips] %example_bank_plugin_money%`

**Comment by Zrips** [comment]
Next update

**Comment by CloudeLecaw** [comment]
ohh so you want a placeholder to printout in chart instead of prasing it it?
Well and what you do if other want to print it out? you shoud be able to have both options
maybe the unfraised with %%placeholder%% and the other with %placeholder%
