### ISSUE TITLE
Can't use portal riding other entities than Horse

### ISSUE THREAD

**Issue by BBSnowIce** [Zrips/CMI#4623]
**Description of issue:**
The title says everything, it is possible to use portal riding a hors but not if we are riding other kind of entities (Spider, Armorstand, etc...), it's a bit annoying with some custom mounts.

---

---

**Cmi Version (using`/cmi version`):** 
8.7.8.3
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
git-Paper-1618 (MC 1.12.2)

**Comment by Zrips** [comment]
While riding not natural mounts player doesn't trigger regular PlayerMoveEvent which is used to detect when player enters portal area. So without that event we cant do anything about you entering portal area. Heavy solution would be to run timer and check players position every second or even more often, which would be huge impact on servers performance. So no real solution for this until Minecraft (spigot?) adds this event while moving around on another entity
