### ISSUE TITLE
Error with warp and multimap

### ISSUE THREAD

**Issue by Ashdeuzo** [Zrips/CMI#4624]
Same problem like https://github.com/Zrips/CMI/issues/4615
With warp.

Error :
No error, just return "There is no saved warps"
Work when i cmi reload

CMI 8.7.10.8
Multiverse-Core 4.2.2 and tested with 4.2.3
Server Type: Paper 1.16.4 build: 282

**Comment by Zrips** [comment]
Will make some changes relating to this, tho at this moment i cant really reproduce your issue with Multiverse-Core and custom worlds. If issue persists after next update, please open new ticket with extra information, like your custom world setup, information where your warp points are located.
