### ISSUE TITLE
Holograms ICON

### ISSUE THREAD

**Issue by 849025143** [Zrips/CMI#4627]
When I use ICON:stone
The stone is turning
I want him to stop spinning, like levitation.
It's like this picture
https://gyazo.com/2c997b6cc6f49e91c4675570fcd42a31

**Comment by EkonC** [comment]
I think this is not possible according to how Minecraft behaves. You could maybe use invisible itemframe for something similiar.

**Comment by 849025143** [comment]
> 根据“我的世界”的行为，我认为这是不可能的。你可以用看不见的项目框架来做类似的事情。

OK, I tried not to use mod, he returned to normal.Thank u EkonC
