### ISSUE TITLE
Home GUI, Icon still shows

### ISSUE THREAD

**Issue by Alejandro-Sosa** [Zrips/CMI#4628]
Whenever setting your home with /sethome it still asks for a icon. This is with gui set to false in the config

---

**Cmi Version:** 8.7.10.8 

**Server Type:** Purpur

**Server Version (using `/ver`):** This server is running Purpur version git-Purpur-839 (MC: 1.16.4)

**Comment by EkonC** [comment]
Set `cmi.command.sethome.iconpicker` permission to false

**Comment by CloudeLecaw** [comment]
Jup thats it negate the permission and you dont have the feature

**Comment by Alejandro-Sosa** [comment]
Guess that works but a config option would be better so when i'm opped i dont have to deal with it aswell.

**Comment by CloudeLecaw** [comment]
op is a rilikt from vanilla.
You should handle all with an owner/operator rang by your permission plugin
in this rank you can negate the pemission before giveing yourself the '*' permission

**Comment by Zrips** [comment]
I can prevent from OP players getting this UI open by default, tho as was said, you can simply negate permission node.
