### ISSUE TITLE
Wrong name of the hand in 1.12.2 in %cmi_iteminhand_realname% placeholder

### ISSUE THREAD

**Issue by KyroOW** [Zrips/CMI#4632]
**Description of issue:**

The name of the hand in the placeholder %cmi_iteminhand_realname% returns "Piglin Brute Spawn" in 1.12.2.

https://i.imgur.com/lBdGdgU.png

**Cmi Version (using`/cmi version`):** 8.7.10.4

**Server Type (Spigot/Paperspigot/etc):** Paper 1.12.2 build 1618

**Comment by Zrips** [comment]
Should be fixed with next build
