### ISSUE TITLE
TAB Sorting/Alignment.

### ISSUE THREAD

**Issue by klaidoshka** [Zrips/CMI#4637]
**Description of feature/improvement request:**
```
A feature to sort tab players by their names or groups.
```
---
### Detailed explanation of what it should do, when and in what situation: ###
It would just sort out the player names in the tab by their groups or by the letters A-Z;a-z;Aa-Zz.

For example, if we start with the groups, then we could put "Player" group to the bottom of the list and then their names would be sorted out one by one, starting from Aa to Zz, while Mods/Admins would be in the upper list.

### Basic explanation as to why this feature is needed and/or useful to have: ###
I believe many (some? Welp, in my region - many) servers are using groups in their tablist, so this feature could be useful for the users (server owners) to keep their tab simple, clean, sorted out _without additional plugins_.

However, if you don't want to spend time on this or think that it's just better to get another plugin for TAB, let me know! 👀

**Comment by EkonC** [comment]
Duplicate https://github.com/Zrips/CMI/issues/3571, https://github.com/Zrips/CMI/issues/2671, https://github.com/Zrips/CMI/issues/931, https://github.com/Zrips/CMI/issues/653
You can use this plugin for that feature as of now: https://www.spigotmc.org/resources/tab-1-5-x-1-16-4.57806/
But make sure to be careful: https://github.com/Zrips/CMI/issues/4555

**Comment by klaidoshka** [comment]
Sorry about the duplicate... haha... Will try to search-up similar topics next time 👀
Thanks for the answer though.

**Comment by CloudeLecaw** [comment]
Thank you EkonC :D  so i dont need to Point this Out aggain like in the other tablist request ;)

**Comment by EkonC** [comment]
> Thank you EkonC :D so i dont need to Point this Out aggain like in the other tablist request ;)

No problem mate 😄
