### ISSUE TITLE
[Feature Request] Ability to set a specific pickaxe requirement to mining spawners added to silk touch mining spawners requirement.

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#4640]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Add a pickaxe requirement for mining spawners. For example, you have a list of available pickaxes used to mine spawners and you allow mining spawners with 2 pickaxes which are in the list. For example, diamond, and iron pickaxe. This requirement would be added onto the requirement of silk touch. 
### Basic explanation as to why this feature is needed and/or useful to have: ###
As I said above, another requirement or step to mine spawners (like silk touch). This requirement will allow you to set only specific pickaxes to be allowed to be used to mine spawners. Again, this would be added onto the silk touch requirement.

**Comment by CloudeLecaw** [comment]
Why you dont simply define anpickaxe with silktouch level 2 and define in cmi that silktouch 2 is needed to be able to mine the spawner?
