### ISSUE TITLE
flyc not take charge if dmg is off

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#4641]
**Description of issue:**

MCmmo not work properly if you have dmg on, so I have only take charge when you fall (my thought is players get some kind of punishment).  

But is not work as I thought or is a bug.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  # Defines multiplier when player falls down of charge to be taken
  # This only effects when player falls from above 3 blocks of hight
  # In example if player falls from 10 blocks height, then 7 * 2 = 14 charges will be taken
  # This is to prevent avoiding no penalty from jumping from cliffs
  # Set to 0 if you want to disable it
  DeductOnFallMulti: 3
```

---

**Cmi Version (using`/cmi version`):** 
8.7.10.8
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
184

**Comment by Zrips** [comment]
No idea how McMMO processes player damage event, but in case its checking for player ability to fly when this happens, then it will get ignored. EntityDamageEvent is fired when player falls appropriate distance to get any damage even when he has fly mode enabled, but i'm not familiar with McMMO code to say exactly whats going on their side. Will make small adjustment on my side, maybe that will resolve your issue, maybe not. If not, then you might want to try contacting McMMO developers for any advice whats going on and maybe they could give some information what i should do on my end if for some reason its not enough to have EntityDamageEvent for them.

**Comment by broken1arrow** [comment]
> No idea how McMMO processes player damage event, but in case its checking for player ability to fly when this happens, then it will get ignored. EntityDamageEvent is fired when player falls appropriate distance to get any damage even when he has fly mode enabled, but i'm not familiar with McMMO code to say exactly whats going on their side. Will make small adjustment on my side, maybe that will resolve your issue, maybe not. If not, then you might want to try contacting McMMO developers for any advice whats going on and maybe they could give some information what i should do on my end if for some reason its not enough to have EntityDamageEvent for them.


I tried to get an answer from him before I post this on github.
see if this helps what he answered, always problems get good answers from DEV, usually always refer your problems to others : /
https://github.com/mcMMO-Dev/mcMMO/issues/4314#issuecomment-725632611

**Comment by broken1arrow** [comment]
@Zrips 

Sry i´m soo late :) but it seams too work (has not have time to turn on dmg and try it out before now).

I will see how it work for other players, But if it more problem i will tell you :)
