### ISSUE TITLE
Spectator in Tablist

### ISSUE THREAD

**Issue by mare-on** [Zrips/CMI#4642]
Hello, CMI has a lot of options for vanish but when I am using a stupid spectator mode, people can know that because of gray transparent overlay in Tablist. My question is... Is there any option to disable this gray transparent overlay using CMI or it's a feature what CMI doesn't have?

**Comment by Zrips** [comment]
Its a vanilla behavior. Simply modifies player name when he is in a spectator mode. This could be some what avoided by intercepting appropriate packet sent to the player and modifying some values in it. Or you could simply go into vanish mode and hide your name entirely. But at this moment its not possible to achieve with CMI without adding extra code to it.
