### ISSUE TITLE
Offline users have "Can Fly: True" as of 7.7.11.1

### ISSUE THREAD

**Issue by tmellen** [Zrips/CMI#465]
When checking /cmi info of users, anyone that's logged on since Friday has CAN FLY being listed as a true state. If a user logs on, it immediately flips to false, but upon logoff, it's back to true again:

```
[INFO] **
[INFO] * Display name: AutumnEmber (AutumnEmber)
[INFO] * OP: False God: False Can fly: True (Not flying)
[INFO] * Sprinting: False Sneaking: False
[INFO] * Game mode: Survival Speed: Fly 1 Walk 1
```

Is this supposed to happen?

**Cmi Version (using`/cmi version`):** 7.7.11.1
**Server Type (Spigot/Paperspigot/etc):** Spigot
**Server Version (using `/ver`):** 1.12.2

**Comment by Zrips** [comment]
Doesn't seem to be common issue as of that update. And cant reproduce it currently. Double check if you don't have any commands been performed on player login or maybe you have set fly mode on in particular worlds throw config file?

**Comment by LogGits** [comment]
I tested this and it works as intended. Let me know if you are still experiencing this on build 8.2.2.0+.
