### ISSUE TITLE
Gamerule Reseting

### ISSUE THREAD

**Issue by monkeymouse1** [Zrips/CMI#4657]
**Description of issue:**
When i do /gamerule and set doDaylightCycle true in about 10 seconds it gets reverted back to false. please help

---

```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
8.7.10.8
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper 253 1.16.3
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Try using **/time unfreeze** or **/time realtime stop** some another time option simply overrides your changes in game rules
