### ISSUE TITLE
Reached Max Warps Bug

### ISSUE THREAD

**Issue by NyhmsQuest** [Zrips/CMI#4658]
**Description of issue:**
Players get a message saying they've reached max warps when they shouldn't have, I've been players permission to set 6 warps but some are capped at 4 and get a message saying they reached max warps. I have an idea it's because as admin/op I've force deleted some warps from that player and the plugin doesn't know that player then removed the warp and thinks they're still at the cap of 6 when in reality they have 4 set.
I gave players this permission: `cmi.command.setwarp.6`

---

**Cmi Version (using`/cmi version`):** 
8.7.10.8
**Server Type (Spigot/Paperspigot/etc):** 
Tuinity 1.16.4-R0.1-SNAPSHOT
**Server Version (using `/ver`):** 
Tuinity version git-Tuinity-"ed9e0c4" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Force removed? Can you be more specific what you did to remove warps? Was this a general removewarp command?

**Comment by NyhmsQuest** [comment]
I did /delwarp <name>

**Comment by Zrips** [comment]
Can you reproduce this issue consistently?

**Comment by NyhmsQuest** [comment]
Yes everytime I delete a players warp it's like the plugin think that player still has a warp and counts towards the players max warps

**Comment by Zrips** [comment]
Are you sure that player doesn't have any other warps under his name? Did some testing and it seam to work correctly. You might have some "hidden" warps which are in different category. Check warps.yml file and count how many times players uuid repeats under Creator section

**Comment by NyhmsQuest** [comment]
I have 2 official warps set by me the op on the server.
I just checked warps.yml and the player only has 4 warps created, I checked all the UUID's and only found 4.

**Comment by Zrips** [comment]
Does max limit gets resolved after you restart server?

**Comment by Zrips** [comment]
Will make some changes relating to that with next build, if issue persist after it let me know.
