### ISSUE TITLE
/back puts them on top of the world

### ISSUE THREAD

**Issue by Yertled** [Zrips/CMI#4659]
**Description of issue:**
When a player dies, and uses /back, they get sometimes sent to the top of the world (build height limit).
So after a normal death, on the ground, in caves, in their homes, etc, they then do /back and get teleported to the top of the world. (No blocks up there, just air)
Then they fall to their death.

We have only gotten reports of this issue from new players on our server, their first death.
I have tried to reproduce it, but no success.

Cmi Version (using/cmi version):
8.7.10.8
Server Type (Spigot/Paperspigot/etc):
Tuinity 1.16.4-R0.1-SNAPSHOT
Server Version (using /ver):
Tuinity version git-Tuinity-"ed9e0c4" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will make some adjustment for this one to avoid teleporting at the top of world. Tho could not reproduce this issue, so if it repeats after next update, let me know.
