### ISSUE TITLE
Money give command can't give money to offline player.

### ISSUE THREAD

**Issue by smartmadio** [Zrips/CMI#466]
**Description of issue or feature request:**
/money give command can't give money to offline player.

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

**Cmi Version (using`/cmi version`):** 
7.7.11.1
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
Paper(1418) 1.12.2-R0.1-SNAPSHOT

**Comment by smartmadio** [comment]
Vault 版本: 1.5.6-b49(CMIEInjector)

**Comment by Zrips** [comment]
@smartmadio What feedback message are you getting?

**Comment by smartmadio** [comment]
solved
