### ISSUE TITLE
tempfly placing people in lava

### ISSUE THREAD

**Issue by Yertled** [Zrips/CMI#4660]
**Description of issue:**
Once tempfly expires, it can put you in lava.
Example: A player on my server had their tempfly expired when he was afk standing in a tight spot with a torch, and he was TPed 50 blocks underground INTO a pool of lava, and I could re-create this perfectly every time, and the issue was the torch. I do believe tempfly counts torches/tall grass, etc as solid blocks, therefore avoiding it.
But it should NEVER place someone in lava no matter the issue.

Cmi Version (using/cmi version):
8.7.10.8
Server Type (Spigot/Paperspigot/etc):
Tuinity 1.16.4-R0.1-SNAPSHOT
Server Version (using /ver):
Tuinity version git-Tuinity-"ed9e0c4" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Good point, will make some adjustments with next version
