### ISSUE TITLE
New duplication glitch

### ISSUE THREAD

**Issue by MrMcyeet** [Zrips/CMI#4662]
**Description of issue:**
Items with custom lore `added with a plugin like uber enchant or epic rename` do not get taken when doing `/cmi uncondense`, but it still gives you the uncondensed items.

For instance, if im holding a diamond block, and do `/lore Hi!` or `/uadd lore Hi!` then while still holding that diamond block do `/cmi uncondense` it will give me 9 diamonds and not take the diamond block

**Video clip of the bug**
https://youtu.be/wPe-V3ePmuo

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.7.10.8 BungeeCord

**Server Type (Spigot/Paperspigot/etc):** 
Tuinity --> (https://github.com/Spottedleaf/Tuinity)
*`(Its a fork of paper)`*

Tho, this bug is reproduceable on paper

**Server Version (using `/ver`):** 
Tuinity version git-Tuinity-"ed9e0c4" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
UberEnchant --> https://www.spigotmc.org/resources/uberenchant.19448/
Epic Rename --> https://www.spigotmc.org/resources/epicrename.4341/

**Comment by mercurialmusic** [comment]
Confirming this without any other plugins that modify lore, but using CMI to add a lore to a diamond block, /uncondense will uncondense the item but leaves the original item, creating an infinite source of whatever is being uncondensed. Pretty major!

**Comment by mercurialmusic** [comment]
Also confirmed that this works with any renamed items, including items that players rename in an anvil. Rename a diamond block in an anvil and voila! Infinite source of diamonds. We had to remove permissions for the command until this can be fixed. Definitely huge.

**Comment by MrMcyeet** [comment]
@Zrips

**Comment by MrMcyeet** [comment]
So uhh... 
Yall come around here often?

**Comment by mercurialmusic** [comment]
He'll get to it.

**Comment by Zrips** [comment]
Got to it, was fixed few versions back which basically prevents any item with lore or custom name being condensed or uncondensed.
