### ISSUE TITLE
Rankup progress bar stuck on 99.46% 

### ISSUE THREAD

**Issue by DarrienNN** [Zrips/CMI#4667]
**Rankup progress bar stuck on 99.46%**

---

**https://pastebin.com/7VALq5UY**

---

**CMI 8.7.11.1** 

**Yatopia** 

**git-Yatopia-"23b9293" (MC: 1.16.4)**

**Comment by DarrienNN** [comment]
And why when i ask something on discord, my question will never get respond..........

**Comment by broken1arrow** [comment]
> **Rankup progress bar stuck on 99.46%**
> 
> **https://pastebin.com/7VALq5UY**
> 
> **CMI 8.7.11.1**
> 
> **Yatopia**
> 
> **git-Yatopia-"23b9293" (MC: 1.16.4)**

With rank and have you image on the problem?

**Comment by Zrips** [comment]
@DarrienNN 
Hard to help out when you provide minimal amount of information. Main thing to know would be: Which rank? If progress is stuck at certain point, what does rank info say? Does it indicate any missing criteria or does it show all in green?
