### ISSUE TITLE
/ride command paired with /sit

### ISSUE THREAD

**Issue by w41k3r26** [Zrips/CMI#4668]
**Description of issue:**

---
![2020-11-30_11 43 40](https://user-images.githubusercontent.com/64218536/100575858-f9460980-3302-11eb-8f79-8c406d929f9e.png)

Let's say player A is riding player B. Now while riding player A type /sit. Player B does /shakeitoff, now the player A is left flying in the air. 

---

**Cmi Version 8.7.10.5** 

**Server Type Purpur** 

**Server Version git-Purpur-848 (1.16.4)**

**Comment by Zrips** [comment]
In general you are not able to use /sit while you are not on ground. But i can add extra check just in case, for this specific situation.
