### ISSUE TITLE
Gamerule Broken

### ISSUE THREAD

**Issue by monkeymouse1** [Zrips/CMI#4669]
**Description of issue:**

 Closed my issue before but still no fix.  if i do cmi time i see a (-) and (+)
I then do cmi time unfreeze and the (-) goes away and then in about 5 seconds it comes back. 
Also doing gamerule doDaylightCycle keeps going from true to false.
Is there a way for me to keep mysql database for money and homes but delete the reset?
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 
paperspigot
**Server Version (using `/ver`):** 
1.16.3
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
(+) indicates that you have set auto real time in this world, you can check that by hovering over (+), basic **/time autorealtime stop** will resolve your issue.
