### ISSUE TITLE
Two kit issues

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#4678]
**Description of issue:**
I have a single-use kit, but when you are a higher rank (or used the kit) this kit doesn't show up and instead shows an empty slot.

![image](https://user-images.githubusercontent.com/5664135/100990574-508de900-3552-11eb-9274-22241c0ce618.png)

As operator however it does show up, but with the line ''You can't get this more then one time''.
Not sure if it's a bug or if I am missing something, but could I make it the same for players? 
That empty slot kinda ruins the design of the kit menu right now.

![image](https://user-images.githubusercontent.com/5664135/100990691-774c1f80-3552-11eb-8911-991c9466f7c4.png)

Also these options seem to be reverted, as kits I can not use are green and kits I can use are red.

```
      nameCanUse: '&a[kitName]'
      nameCantUse: '&c[kitName]'
```

![image](https://user-images.githubusercontent.com/5664135/100990820-9f3b8300-3552-11eb-8055-43d304b1c67d.png)

**Comment by Zrips** [comment]
In general this is default behavior as there is no point in showing kit in UI when you cant use it anymore. I can add extra option to include it into UI even if you cant use it which would resolve your issue with it being invisible

**Comment by Sikatsu** [comment]
I understand it's default behaviour, but I don't understand what the purpose is of ''You can only get this one time'' if the kit will no longer show up, but for design purposes I prefer if it stays haha! Thanks :)

**Comment by Sikatsu** [comment]
Did you also see the inverted can and can't use names?

**Comment by Zrips** [comment]
Yea, both things will get fixed/updated
