### ISSUE TITLE
Create table printed on first start

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#4679]
**Description of issue:**
When you start CMI for the first time, or when the SQLite database doesn't exist, it prints out the entire `CREATE TABLE` statment.
https://pastebin.com/hbMUdikG
---

---

**Cmi Version (using`/cmi version`):** 
8.7.11.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-284 (1.16.4)

**Comment by Zrips** [comment]
Its not a bug, its more or less debug message and only visible when new tables/columns are created in case we would need to determine if new column or table actually got created during startup is you start experiencing issues later on. Simply ignore it.
