### ISSUE TITLE
Toast placeholder not working

### ISSUE THREAD

**Issue by OverBrave** [Zrips/CMI#4682]
**Description of issue:**
Placeholder not working when using with CMI toast command.
![image](https://user-images.githubusercontent.com/47111280/101058111-d84d1500-359d-11eb-802f-e02e275c5772.png)

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/47111280/101058156-e307aa00-359d-11eb-847e-b7aee1f3ecff.png)

**Comment by Zrips** [comment]
Due to some current limitations this will only work when sending toast to one player and not using ALL as variable, should resolve most cases, atleast until future update.
