### ISSUE TITLE
Typo in Locale files

### ISSUE THREAD

**Issue by nemmynaomi** [Zrips/CMI#4685]
**Description of issue:**
Noticed a typo in Locale files, and doing ctrl+f in a text editor- found out there are multiple of these typos.

If this is not a typo, and both "work", forgive me- However both are used instead of just one.
Example being Line 2203 in a newly generated Locale_EN.yml, `newBanned: 'Banned '`

---

**CONFIG SECTION**
```
# DEFAULT CONFIG
# Line 1024 in a newly generated Locale_EN.yml for this version
      banedSilent: '&7[&8Silent&7]&6[playerDisplayName] &egot banned by &6[senderDisplayName]
        &efor: &6[reason]'
# There are more "baned" typos
```

---

**Cmi Version:** 
8.7.11.0 (I'm aware 8.7.11.2 is out, but I do not own the plugin, rather configure it, apologies if this has already been fixed.)
**Server Type:** 
Paper
**Server Version:** 
git-Paper-288 1.16.4-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
It is a typo, but as long this is just for section indication and not for locale itself, we are good, for now. Updating those name might reset existing lines, which would only confuse people. But will try to avoid repeating this typo in future.
