### ISSUE TITLE
ctellraw command

### ISSUE THREAD

**Issue by nemmynaomi** [Zrips/CMI#4686]
**Description of issue:**
- The first argument of `/cmi ctellraw` does not suggest playernames / nicknames.
- The second argument of `/cmi ctellraw` suggests- not just anything, but a lot of stuff that does not even work. (Due to not containing any text tags.)
- Unlike the rest of every CMI command I've used so far, `/cmi ctellraw ?` does not seem to work.
- `/cmi ctellraw` does not throw any errors when an invalid second argument is provided, or when no second argument is provided. (Assuming this is less of a bug and more it was never gotten around to)

---
(Apologies for the server name in here, I don't feel like editing it out of a gif at 9:45pm)
![An example of everything described above](https://user-images.githubusercontent.com/72463576/101115140-de98bc80-35b0-11eb-8a8c-36b6449c2201.gif)

**Cmi Version (using`/cmi version`):** 
8.7.11.0 (I'm aware 8.7.11.2 is out, but I do not own the plugin, rather configure it, apologies if this has already been fixed.)
**Server Type:** 
Paper
**Server Version:** 
git-Paper-288 1.16.4-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Will fix tab complete issue. For ? variable, in general not providing any variable will work in same way as you would use ? while this will not work for some of the commands which could actually contain it, like **/broadcast ?** which could be actual message and not requirement to print out help page.
