### ISSUE TITLE
Tab complete can expose users IP addresses under certain circumstances

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#4687]
**Description of issue:**
I haven't done much with the new tab complete feature, but it seems that certain command combinations can expose all sorts of data including player IP addresses and most CMI command variables to ALL players. I'm not sure how many commands it's present on, but we found it specifically on the `/me` command when a player types /me [any character], then hits space. They are then presented with a rather long list of options including the aforementioned IP addresses. A security/privacy issue to say the least!

---

**Cmi Version (using`/cmi version`):** 
8.7.11.2 BungeeCord 
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-312 (MC: 1.16.4)

**Comment by Zrips** [comment]
/me doesn't include any tab completes in general. Is this custom alias of yours or default one behaving in a way it should not? Cant reproduce this issue at this point.
