### ISSUE TITLE
Combat | command ignored

### ISSUE THREAD

**Issue by bvc0115** [Zrips/CMI#4688]
It seems that cmi is ignoring players using /warp (name) command while players are still tagged.
I've been testing it with /home (name) and they can also use it while in combat. It seems that command with space are being ignored. Besides, I have a cooldown for these commands so maybe cmi attempts to block them but these commands are not executed immediately?

---

**Cmi Version: 8.7.11.2`** 

**Server Type:  Fox Spigot** 

**Server Version : 1.8 R3**

**Comment by Zrips** [comment]
I will need your Combat config section for testing. But currently i cant reproduce this issue. Commands are blocked properly independent if they have cooldown or not

**Comment by bvc0115** [comment]
There is no need for that anymore. I realized that cmi is doing fine, there is other plugin that is not currently blocking all cmds from cmi. Since you already fixed the combat tag after dying I don't have any other request or issue.
Thank you for your time.
