### ISSUE TITLE
Playtime still being counted during afk.

### ISSUE THREAD

**Issue by w41k3r26** [Zrips/CMI#4690]
**Description of issue:**
The `StopPlayTime: true` and auto AFK also working fine but playtime doesn't stop during afk.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
`Afk.StopPlayTime`
```

---

**Cmi Version : CMI v8.7.11.2** 

**Server Type : Purpur** 

**Server Version: git-Paper-259 (MC: 1.16.4)** 

![image](https://user-images.githubusercontent.com/64218536/101126450-89e15a00-3621-11eb-995e-5cdc75a906a0.png)

![image](https://user-images.githubusercontent.com/64218536/101126353-51da1700-3621-11eb-9ef0-345188b0a4ba.png)
![image](https://user-images.githubusercontent.com/64218536/101126368-5b637f00-3621-11eb-803e-988ae280ac2f.png)
![image](https://user-images.githubusercontent.com/64218536/101126395-661e1400-3621-11eb-90e3-fb27ff523ae0.png)

**Comment by bobhenl** [comment]
For me not, when I use /playtime <player>

**Comment by w41k3r26** [comment]
> For me not, when I use /playtime

Its /cplaytime

**Comment by CloudeLecaw** [comment]
You created an issue because the request was not answered? #4670

**Comment by Zrips** [comment]
@w41k3r26 
/cplaytime is separate system which is only meant to be used for checking when player was online and its not being used for any other action. Playtime is stopped for general playtime usage in any other place.
