### ISSUE TITLE
Tab completion annoyance "-g:"

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#4699]
**Description of feature/improvement request:**
My players find the `-g:` argument really annoying.
There is no way this can be blocked using additional plugins

---
### Detailed explanation of what it should do, when and in what situation: ###
Example:
`/warp spawn` (and all other publicly available warps)
![Screenshot_162009](https://user-images.githubusercontent.com/28690790/101284246-4f252080-37df-11eb-8332-ce16c25e947c.png)
I don't use groups at all. (I don't understand the use case. It's not explained somewhere.)

I tried hiding it by:
- using thirt party plugins to block certain tab suggestions. No luck.
- using custom aliases. No luck.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Players are annoyed by this useless tab suggestion.

**Comment by CloudeLecaw** [comment]
Its not just the -g we also get suggesstet vars for custom alias even they have nothing tondo with the command.

**Comment by mercurialmusic** [comment]
Related to #4687

**Comment by Zrips** [comment]
Agreed, will remove that one.
