### ISSUE TITLE
Improvement of warp permission structure

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#47]
I have a feature/improvement request. It would be very useful, if commandblocks/the console could execute warp commands for a player without the need of giving the player the permission for the warp. One has just way more opportunities if the use of a warp is limited to a commandblock execution.

Also if one player „warps“ another player both player need the permission to use the warp. The system would be way more useful if just the player who is send to the warp needs to have the permission to go there.

Keep up your great work, I appreciate it .

**Comment by Zrips** [comment]
Will add support for console and second part is actually already working like that, warp is being picked by player who is being teleported, so if he doesn't have permission to that warp, you can't teleport him there.
