### ISSUE TITLE
Server crash (unloaded world)

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4701]
**Description of issue:**

---
Hi, my server crashed. For the first time there was mentioned CMI in stack trace, then there were several errors of other plugins after restart (included cmi), and then next crash.

1. Crash with mentions of CMI: https://pastebin.com/TADhtUhu
2. HyperDrive plugin mentioned after restart: https://pastebin.com/6gzVAeVv
3. CMI mentioned again after restart https://pastebin.com/1DhCBv0s
4. Magic mentioned too https://pastebin.com/CiLNFPTq
5. Next crash https://pastebin.com/GjndXwbb

Before 3. crash: https://pastebin.com/55R39PxH

Maybe could be due to PlayerWorldsPro (https://www.spigotmc.org/resources/%E2%AD%90-playerworldspro-%E2%AD%90-nether-and-the-end-support-async-loading-expiration-1-8-1-16-4.72113/updates) plugin? They did update yesterday and it was also with unloaded worlds. But may there's something to fix in CMI too.
![image](https://user-images.githubusercontent.com/18662086/101284817-31a58600-37e2-11eb-92a0-fe45d9c00c27.png)

---

**Cmi Version (using`/cmi version`):** 8.7.11.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 312 (1.16.4)

**Relevant plugins (Delete if this isn't needed):** Slimefun mentioned, HyperDrive mentioned, Magic mentioned, but maybe mainly PlayerWorldsPro

**Comment by bobhenl** [comment]
Btw, author already added API if you could try to hook there somehow or try solve another way. https://github.com/HeroPwP/PlayerWorldsPro-Issues/raw/main/PlayerWorldsProAPI.jar https://www.spigotmc.org/resources/%E2%AD%90-playerworldspro-%E2%AD%90-nether-and-the-end-support-async-loading-expiration-1-8-1-16-4.72113/updates

**Comment by Zrips** [comment]
Should be resolved with next build
