### ISSUE TITLE
Homes at deleted worlds not visible in /homes GUI

### ISSUE THREAD

**Issue by kikelkik** [Zrips/CMI#4702]
**Description of issue:**
Homes directing to worlds that don't exist anymore aren't shown in the /homes GUI.
This leads to a missleading GUI title (It says "7/10" but I only see 5 icons because 2 homes point to a deleted world) and rubbish in the cmi_users db.

---

**Cmi Version (using`/cmi version`):** 
8.7.11.1

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
Paper#294 1.16.4-R0.1-SNAPSHOT

**Comment by bobhenl** [comment]
I think it's good that they aren't seen there, but they should be deleted probably.

**Comment by kikelkik** [comment]
Well of course, but it's lot easier to implement when you just show all icons. So if a player tries to tp to such a home, he'll already receive an appropiate error message so he will delete his home on his own.
You could also delete a home instantly when a player tries to use it the first time.

**Comment by TheoRetisch1** [comment]
Confirmed for version 8.7.12.1.

**Comment by Zrips** [comment]
Issue with auto removal would be the cases when world is simply not loaded but home location should remain. Like some plugins will load world which is meant to be for specific player, if world was not loaded when player opened UI then his home would get removed which is no go. What i can do is to actually include those homes into UI but add extra indication that location is in none existing world, just to be more convenient.
