### ISSUE TITLE
Hexcodes bug in /give

### ISSUE THREAD

**Issue by xReplicate** [Zrips/CMI#4703]
When using hexcodes in /give they don't get used.

For example:
The command: /give xReplicate Netherstar l {#C30022}De_ster_voor_bovenop_de_kerstboom
yields:
![image](https://user-images.githubusercontent.com/73534050/101291459-29147600-3809-11eb-9fc9-f9200e15baa9.png)

More lore lines with hexcodes will skip all previous lines
The command: /cmi give xReplicate Netherstar l {#C30022}De_ster_voor_bovenop_de_kerstboom l _ l {#13CC4E}[Limited_Edition] l {#036F3E}Kerst_2020
yields: 
![image](https://user-images.githubusercontent.com/73534050/101291494-88728600-3809-11eb-8bfd-95729806af1b.png)

---

The Warning appears in console:
```
[21:15:21 WARN]: com.mojang.brigadier.exceptions.CommandSyntaxException: Expected '{' at position 0: <--[HERE]
```
---

**Cmi Version:** 8.7.11.2

**Server Type:** Tuinity

**Server Version:** 1.16.4

**Comment by mercurialmusic** [comment]
Confirming. Not really a bug since I don't think it was ever added, but it would be really nice to have if possible.
