### ISSUE TITLE
Prewards are included when player is jailed

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4706]
**Description of issue:**

---
Hello, shouldn't be prewards excluded when the player is jailed?
**ERROR (DELETE IF YOU HAVE NO ERROR):**

---

**Cmi Version (using`/cmi version`):** 8.7.11.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 312

**Comment by Zrips** [comment]
Well, good point, will prevent this from happening in the future.
