### ISSUE TITLE
Elevator Y level Minium Annoyance.

### ISSUE THREAD

**Issue by RustyDagger** [Zrips/CMI#471]
So my map has flat bedrock ( not that uncommon when using paper spigot.) so my Y levels are safer at the bottom of my map than most. 

I was trying to make an Elevator to the bottom and ran into this issue. It seems CMI WONT teleport me down to the lift sign if the sign is under Y level 5 Here is a Gif One sign at Y level 4 and one at Y level 5
I can go down to the one at 5 but not the one at 4 despite it being safe.

https://gyazo.com/724cf7e663bdc78e7029745a54968aea

**Comment by Zrips** [comment]
Will lower down minimal Y to 1 from 3.
