### ISSUE TITLE
MYSQL Error

### ISSUE THREAD

**Issue by FrancyMak** [Zrips/CMI#4711]
**Description of issue:**
After modifying CMI the MySQL database no longer works. I tried to completely delete the database and recreate it from scratch, but nothing.
I use the use of MYSQL 8.0.22

---
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-CMI_users CONVERT TO CHARSET utf8' at line 1
```

---

**Cmi Version (using`/cmi version`):** 
 Versione di CMI: 8.7.11.2 BungeeCord 

**Server Type (Spigot/Paperspigot/etc):** 
Paper(312) 1.16.4-R0.1-SNAPSHOT
**Server Version (using `/ver`):** 
1.16.4

**Comment by Zrips** [comment]
Incorrect table prefix. It cant contain -
