### ISSUE TITLE
Error when using multiple lines for alert

### ISSUE THREAD

**Issue by w41k3r26** [Zrips/CMI#4712]
**Description of issue:**

When using multiple lines in locale_EN.yml `alert.info.inform` the Reason line is displayed twice.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
info:
      inform: 
      - '&c&l------------------------'
      - '&dAlert for - &r[name] &dlogged in!!'
      reason: '&dFlag reason: &r[reason]\n&c&l------------------------'
```

---

**Cmi Version): CMI: 8.7.11.2** 

**Server Type: Paper Fork- Yatopia** 

**Server Version: Yatopia 1.16.4-R0.1-SNAPSHOT** 

![image](https://user-images.githubusercontent.com/64218536/101335208-e604e200-389e-11eb-909d-0b35f2fa719b.png)

**Comment by Zrips** [comment]
Will be fixed with next build
