### ISSUE TITLE
cmi.keepexp is not compatible with PerWorldInventory

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#4719]
**Description of issue:**
The permission `cmi.keepexp` doesn't work if the plugin PerWorldInventory is active. On death the EXP are reseted. Without PerWorldInventory the feature works smoothly.
Since PerWorldInventory is a widely used inventory management plugin, it would be aweseome if you could make it compatible. Of course I also reported the bug to PerWorldInventory (EbonJaeger/perworldinventory-kt#228).

**CMI Version:** 
8.7.11.2

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version** 
1.16.4 build 319

**Relevant plugin**
PerWorldInventory 2.3.2 (https://github.com/EbonJaeger/perworldinventory-kt)
PWI config: https://pastebin.com/nk97p9nY
PWI world settings: https://pastebin.com/iDfFPiQH
There are no errors in the log.

**Comment by mercurialmusic** [comment]
This might be down to your config options or permissions (are they per world instead of global?) since I use CMI and PWI and haven't experienced this -- it works as it should. Also using Paper.

**Comment by TheoRetisch1** [comment]
Thank you for the advice, I will look into that again :)

**Comment by TheoRetisch1** [comment]
Mhh I can't get it to work. I only set one global perworldinventory permission for a luckperms group: `perworldinventory.bypass.*`
and didn't used any other pwi-Permission at all. Config adjustments don't help me either :/
@mercurialmusic would you be so kind to send me your config and tell me which permissions you have set 🥇?

**Comment by Zrips** [comment]
If player has cmi.keepexp then CMI will simply tell to server at his death, that he needs to keep his exp, which is listened at a NORMAL level. If another plugin overrides this behavior at some point after this was done, then you will have to check that plugin specifically. Simply find a way to disable PWI exp drop handling entirely and let CMI to take over it. other then this, its not a bug, just miss configuration.

**Comment by Baterka** [comment]
@Zrips can you add config value for it? So we can select CMI to take over? I am not sure how event handling works if both plugins have HIGHEST priority but I think it can be possible to override it.
