### ISSUE TITLE
Uncuff doesn't tab complete player names

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4720]
**Description of issue:**

---
Hi, it's few days since I saw that uncuff command doesn't complete player names, it did before, but it stopped few days ago.
![image](https://user-images.githubusercontent.com/18662086/101490582-d8b12b80-3962-11eb-9ccc-2ef81fe53ca3.png)

---

**Cmi Version (using`/cmi version`):** 8.7.11.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 318

**Comment by Zrips** [comment]
Will be fixed with next release
