### ISSUE TITLE
check:$1==''! = check for empty $1 (argument)

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4721]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hello, could you please add way to check for empty argument? I have something like:
```
  ping:
    Cmds:
    - 'check:$1==NULL! asConsole! cmi ctellraw [playerName] <T>&eVyužití: &6/ping &f<jméno_hráče></T><SC>/ping </SC>'
    - check:$1==NULL#! cooldown:1?#! asConsole! cmi ctellraw [playerName] <T>&c&lPing &f» &fKontrola
      pingu hráče $1. &eNajeď &fmyší pro tipy.</T><H>&7Má-li špatný ping, tak doporučujeme
      zkusit &evypnout stahování &7či jiné &ehry nebo programy&7, které žerou internet.\n\n&7Má-li
      problém s lagy, poté doporučujeme stáhnout &e/optifine &7(klikni pro odkaz)
      či vyzkoušet příkaz &e/optimize&7, jenž je od &b&lVIP&7.</H><SC>/optifine</SC>
    - delay! 5
    - asConsole! cmi sound block_note_block_pling [playerName] -p:1.5 -v:0.7
    - 'asConsole! cmi bossbarmsg [playerName] -s:1 -a:2 Ping: %player_ping_$1%
      -t:2 -p:1 -c:green -n:myping'
    - delay! 5
    - 'asConsole! cmi bossbarmsg [playerName] -s:1 -a:2 Ping: %player_ping_$1%
      -t:2 -p:1 -c:green -n:myping'
    - delay! 5
    - 'asConsole! cmi bossbarmsg [playerName] -s:1 -a:2 Ping: %player_ping_$1%
      -t:2 -p:1 -c:green -n:myping'
    - 'asConsole! cmi bossbarmsg [playerName] -s:1 -a:2 Ping: %player_ping_$1%
      -t:2 -p:1 -c:green -n:myping'
```
So it would work like.
```
check:$1==False! asConsole! cmi msg [playerName] Syntax: /command <playername>
check:$1==False#!
asConsole! cmi msg [playerName] You have provided parameter $1
```
As you can see, I've tried "false, false, null, NULL, '' and anything didn't work".

### Basic explanation as to why this feature is needed and/or useful to have: ###
Cause when I wanna use /ping for myself + /ping <player> (I mean ping from this alias), I can't do this... So I've decided to try solve it this way when I'll respond to just /ping that he has to provide /ping <player>, but as you can see it doesn't work.

So, could you please add way to define empty argument?

**Comment by CloudeLecaw** [comment]
What you wannw Check for?
Check for nothing?...null...?

**Comment by bobhenl** [comment]
I tried already ping ?: and ping: but I didn't let it work from some reason.  Could you give me example please?

And about null, I wanted to check if $1 (the first argument - name) is empty.

**Comment by Zrips** [comment]
Should we working with next update. Dint considered situation when comparison like this could be needed.
