### ISSUE TITLE
Command on log-in

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#4722]
**Description of feature/improvement request:**
Can we get a section in the config for running commands to a player on log-in?
---

I really like how we can define a customtext (motd) in the config that runs for players, it would be nice to also be able to run a few more commands with that. Adding a second ctext perhaps for certain holidays, or for what I would like to do which is fix some gimped enchants on log-in. (Enchant system seems to break with potion effects, but has a command that can be applied to the player to fix them. Running it on login for the player would just remove that extra step and really ad some quality of life)

*Would need options to run as player and run as console, which I'm pretty sure CMI already handles easily.

**Comment by CloudeLecaw** [comment]
Have you tookna look allready on the eventcommands.yml? You can define everything there on Login. Commands, ctexts, meassages.
You really should take a look into it.also full Specialized commands are supported there. So u can Script everything....
