### ISSUE TITLE
Make using hex colours less clunky

### ISSUE THREAD

**Issue by DeaDCorEx** [Zrips/CMI#4727]
**Description of feature/improvement request:** It would be nice to not have to put "&" between each number in the hex code make it same as or similar to how essentials does it (&#326794) instead of (&x&3&2&6&7&9&4)

---

this would be useful to have because it is more user friendly, easy to use, and faster than the current method because you can copy/paste the code directly from the google colour picker rather than having to format it after pasting. 

Thanks for your time, I wouldappreciate it a lot if you could add this

**Comment by CloudeLecaw** [comment]
Why doing this?  You can use normal heycolors allready l..take a look at /cmi colorpocker

**Comment by Zrips** [comment]
@DeaDCorEx 
No idea what you even mean here. CMI uses {#6600cc} format to define hex color code, which can even be a name like {#red} your provided example is default minecraft hex color code handling, that one is not CMI but minecraft itself. CMI simplifies that into short one, as shown above. And as @CloudeLecaw pointed out, you can use /colorpicker to pick color you want which will provide hex color code for usage inside CMI plugin. We are not Essential and we are not using their format for basic reasons like options to use short hex codes like {#60c} which is the same as {#6600cc} or use named ones like {#fuchsia} or even define gradient ones by adding > or < or <>
More information at [https://www.zrips.net/cmi/hex-colors/](https://www.zrips.net/cmi/hex-colors/)
