### ISSUE TITLE
Container data does not save after /cmi scan

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#4730]
**When I run /cmi scan and teleport to containers to remove stuff all my changes to containers are not saved when I teleport to some remote point (e.g spawn) and get back to the area scanned.**

How to reproduce:

1. Go to some player's storage.
2. Run /cmi scan id something r 10
3. Remove any items you want
4. Teleport to spawn, so the chunks where you scanned unload.
5. Go back to storage and...
See that everything you removed is still in there,

---

**Cmi Version (using`/cmi version`):8.7.11.2** 

**Server Type (Spigot/Paperspigot/etc):Purpur (though happens on Paper as well)** 

**Server Version (using `/ver`): This server is running Purpur version git-Purpur-883 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)**

**Comment by radiant-ai** [comment]
The issue appears to exist for a lot of months, previously I was thinking that I was blind until today I removed exactly same items with exactly same nbt data 5 times and still failed.

**Comment by Zrips** [comment]
Should be fixed with next build. And this issue seams to be in recent minecraft versions due to some internal changes relating chunk unloads when no players are around.
