### ISSUE TITLE
Custom Mob Heads - missing criteria options

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#4737]
The custom head drops are a fantastic feature, but some mob differentiations don't work. It would be great if these could be added to complete the game experience.
The following differentiation criteria do not work, if you try to set them with the `-c` parameter, the affected head is not dropped at all:

- Differentiation between rabbits of different colours
- Differentiation between the brown and the red mushroom cow
- Differentiation between the peaceful and the aggressive bee
- Differentiation between the normal fox and the snow fox
- Differentiation between the normal and the brown Panda

CMI -  8.7.11.3
Paper 1.16.4 - build 323

**Comment by Zrips** [comment]
Will add with next udpate

**Comment by TheoRetisch1** [comment]
Thank you very much 💯 !
