### ISSUE TITLE
Hiding ? when disabling tab / custom tab alias in customalias.yml

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4739]
**Question: **
Hi, I have question, I've made this custom alias sell ? to always open sell gui menu even when player type for ex. /sell sss, then it will open him menu. But I wanna try to hide ?, if it's possible. As I saw with new addition of custom tab completion / disabling the one, it may be possible now? But I don't know how, so that's why I'm asking here. So I wanna disable this ? in /sell tab completion:
![image](https://user-images.githubusercontent.com/18662086/101990010-6b740200-3ca4-11eb-9461-6c19bb2580e6.png)

Tried this:
```
  sell ?:
    Cmds:
    - asPlayer! cmi sell gui
    Tab: false
```
But didn't work. Or may there will be better solution now to make what I want?  Here is why I did this method https://github.com/Zrips/CMI/issues/4271.

**Comment by CloudeLecaw** [comment]
i can agree and also have this problem. but at the moment the answer is no u cant hide it

**Comment by CloudeLecaw** [comment]
no changes in that section
