### ISSUE TITLE
Change /suicide death cause

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#474]
Currently /cmi suicide uses the CUSTOM death cause, this should be changed to the SUICIDE death cause to make things easier to configure and manage from other plugins (death messages).

**Comment by Zrips** [comment]
Well actually it is currently on SUICIDE cause

**Comment by TheWranger** [comment]
Alright, I'll close this for now then and if I get confirmation my issue is coming from CMI, I'll reopen this.

**Comment by TheWranger** [comment]
I have tested with both ChatControl and DeathMessagesPrime and whenever a player dies from /suicide a CUSTOM death message will be displayed instead of a SUICIDE death message.

**Comment by Zrips** [comment]
Next update will contain appropriate last damage cause for the player
