### ISSUE TITLE
CustomHeads are not translated

### ISSUE THREAD

**Issue by thomaboehi** [Zrips/CMI#4741]
**Description of issue:**
Custom heads are given to players in english. I'm on a french server, and we translated all the mobs, but still the custom heads are in english.

---

**Cmi Version (using`/cmi version`):** 
8.7.11.3

**Server Type (Spigot/Paperspigot/etc):** 
PaperMC

**Server Version (using `/ver`):** 
1.16.4

**Comment by CloudeLecaw** [comment]
LoL
You know u have a file to translate this and there is nonfrench template for that.

**Comment by Zrips** [comment]
Will be fixed with next build
