### ISSUE TITLE
CMI Rankup - Blocks Mined/Placed bug.

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#4742]
**Description of issue:**
When players mine a block, the "/rankup" command statistics for both "block mine" and "block place" increases by +1. For "block place", it is normal.

https://drive.google.com/file/d/1O5igxdvEBzJ-xw2ajcx3nTmziJ6I7ylN/view
---

**Cmi Version (using`/cmi version`):** 
CMI 8.7.11.3

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
Paper version git-Paper-267 (MC: 1.16.4)

**Comment by Zrips** [comment]
CMI uses statistics from minecraft itself, if those doesn't match what it should then i cant really resolve it at my end as CMI doesn't perform any active tracking
