### ISSUE TITLE
Flight enable

### ISSUE THREAD

**Issue by Juiceqad** [Zrips/CMI#4747]
When you go to the worlds, the flight turns on automatically

**Comment by CloudeLecaw** [comment]
You can do this allready

**Comment by Juiceqad** [comment]
You do not understand, when a player switches between worlds, he turns on flight (automatically)

**Comment by CloudeLecaw** [comment]
then disable it in your multiverse or cmi config or disable it by eventcommand.

**Comment by Zrips** [comment]
@Juiceqad 
This would be caused ether by world limits feature which can toggle fly mode on or off when changing to the world, by event commands or by something what tigers fly mode change in general or by another plugin entirely. CMI doesn't change fly modes if not instructed to do so.
