### ISSUE TITLE
Little locale improvements.

### ISSUE THREAD

**Issue by Remski01** [Zrips/CMI#4748]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Seprate/improved locale lines.

### Basic explanation as to why this feature is needed and/or useful to have: ###

Seprate line for:
`requestSent:`. Example: `tpahereRequestSent:` and `tpaRequestSent:`

Seprate lines for the toggle command when being used by an player is used **on** player by an admin.

Example:
If the player used `/tptoggle` he just get the `feedbackNoTp:` line, the player that is.
If an Admin used `/tptoggle <player>` he get line `AdminfeedbackNoTp:`, the admin that is the player dont see it.

Thanks for adding the other things i asked before but then never responded to it. Havent noticed they were added, noticed it after checking the open Github issue's.

**Comment by Zrips** [comment]
Will do. Tho till avoid adding "keep" variable, that one would require some extra things to be done and different handling of command when saving. So just to simply it, for now we will not have it.

**Comment by Remski01** [comment]
Ya, the Toggle improvemts stuff can be forgetten for now. I asked for them because we were working on PlayerSettingsUI, but it have been delayed for an unknown time. 

The seprate lines for toggle commands is just because the context between someone using it on himself and a admin using it on someone is much different. And the tpa thing just because its more logical to have seprate lines as it can be conufssing to see the same text for 2 different commands.

**Comment by Zrips** [comment]
Usually when i'm reusing same locale i'm just trying to make it more compact, feedback messages are similar in general, they might be different if you need too, but in general they do output same thing. But its not hard to separate them if there is a need for it.

**Comment by Remski01** [comment]
So, that was quick! Thanks for that. However. And to be clear, it was me not saying it, but i kinda meaned this also for `/msgtoggle` and `/paytoggle` 😅 

Would be awesome if you could take those in the next update when you release it. Sorry not saying it before, and thanks for the quick update about the `/tptoggle` 😀
