### ISSUE TITLE
Add NicknameChangeEvent to the API

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#4752]
### Detailed explanation of what it should do, when and in what situation: ###
Add a `NicknameChangeEvent` to the API with methods to get the player, their previous nickname & new nickname.

### Basic explanation as to why this feature is needed and/or useful to have: ###
There are a few actions I would like to perform when a player updates their nickname and I don't have a good way to do it, so adding a NicknameChangeEvent would make life so much easier :)

**Comment by Zrips** [comment]
CMIPlayerNickNameChangeEvent
Which includes CMIUser object and new nickname, which can be ether modified or event itself can be canceled to stop from command being performed.

**Comment by Insprill** [comment]
Is there a newer version of the API jar? That doesn't exist with 7.6.2.0
