### ISSUE TITLE
Playtimereward can't auto claim

### ISSUE THREAD

**Issue by qq851411536** [Zrips/CMI#4756]
**Description of issue or feature request:
playtimereward can't auto claim

---

**Cmi Version (using`/cmi version`):8.7.12.0

**Server Type (Spigot/Paperspigot/etc):Spigot

**Server Version (using `/ver`):1.12.2,1.16.4

**Comment by Zrips** [comment]
Double check if you dont have PlaytimeRewards.RequiresPermission enabled which would prevent rewards being given out to players without appropriate permission node. This is in config.yml file.
