### ISSUE TITLE
Aliases for msg, reply, broadcast, etc.

### ISSUE THREAD

**Issue by DavidSelberg** [Zrips/CMI#4759]
**Question: **
Hey everyone, I've been trying to figure out a way to make commands accessible without "cmi" at the start.

For most commands, I can just use the alias editor and do something like "/cmi aliaseditor new reply-cmi reply $1" but with these commands it will only have the first word of the message.

Does anyone know of a way to make these commands work?

Thanks in advance!

**Comment by CloudeLecaw** [comment]
U beedbti use $1-

**Comment by Zrips** [comment]
@DavidSelberg 
Well you have 2 options, ether use aliaseditor if you want to have something more custom, if not, simply go into alias.yml file and enabled alias for commands you want to remove "cmi" prefix
