### ISSUE TITLE
Can't disable elytra right click sounds

### ISSUE THREAD

**Issue by MicleBrick** [Zrips/CMI#476]
I have rocket boots on my server that use gliding. With CMI, it plays an annoying sound if you right click while flying. I can't figure out how to disable it in the config.

**Comment by Miclebrick** [comment]
It plays it if you right click with an item while gliding

**Comment by Miclebrick** [comment]
Still getting this issue. It's extremely annoying.

**Comment by Miclebrick** [comment]
Is there seriously nothing I can do to disable this..?

**Comment by LogGits** [comment]
This doesn't seem to be an issue with cmi. Disable all plugins except for cmi and if this issue persists reply to this and i will reopen it.
