### ISSUE TITLE
Attached Commands Fail with Console Spam

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#4760]
**Description of issue:**
In CMI 8.7.12.0 attached commands seem to be working only once then failing with console error, true for both existing items and new items created in this version and regardless of attached command option or item used. Tried with both items that normally have a use and items that don't (like blaze rod). Items like the Knowledge Book were consumed on right click (as they would be with normal use but this didn't happen previously with attached commands). Failure after the first use occurred regardless of the limiteduse option, left or right click, command execution method, and regardless of CMI vs. other command.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://gist.github.com/mercurialmusic/3ef7474ec4544d1cda8c2fb661ec6d1a

---

**Cmi Version (using`/cmi version`):** 8.7.12.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-Paper-325 (MC: 1.16.4)

**Comment by Zrips** [comment]
Will issue fix with todays update
