### ISSUE TITLE
[URGENT]player not getting any damage,with +2 more bugs

### ISSUE THREAD

**Issue by wonyoungb** [Zrips/CMI#4761]
**Description of issue:**
Player not getting any damage with any components also didn't execute commands for votifier after update
lastly cmi don't took new sql info even execute command cmi reload

---

NO ERROR LOGS

```
Check video what I posted on discord 
https://cdn.discordapp.com/attachments/789405802120871958/789405866289397770/BeiXzWJgsM.mp4
---

**Cmi Version (using`/cmi version`):** 
[17:26:21] [Server thread/INFO]: --------------------------------------------------
[17:26:21] [Server thread/INFO]: CMI: 8.7.12.0 MySQL
[17:26:21] [Server thread/INFO]: Server: Spigot 1.16.3-R0.1-SNAPSHOT
[17:26:21] [Server thread/INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: True
[17:26:21] [Server thread/INFO]: Modules -> 54 enabled 0 disabled:
[17:26:21] [Server thread/INFO]: --------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-Spigot-57bbdd8-dea4138 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):**
votifier

**Comment by wonyoungb** [comment]
[https://cdn.discordapp.com/attachments/789405802120871958/789405866289397770/BeiXzWJgsM.mp4
](url)

**Comment by wonyoungb** [comment]
https://cdn.discordapp.com/attachments/789405802120871958/789405866289397770/BeiXzWJgsM.mp4

**Comment by Zrips** [comment]
Not much to go on. Have you tested this with CMI only? Have you modified DamageControl in config file?

**Comment by wonyoungb** [comment]
yes after I remove sql playerdata on cmi it's fixed few moments no I didn't modified dc in config even idk where that file is

**Comment by Zrips** [comment]
What you mean by "few moments"? Issue goes away if you reset players data? And that option is located in config.yml file

**Comment by wonyoungb** [comment]
yeah issue goes away when reset player data but that keep appears somehow again.
I didn't changed config that section

**Comment by Zrips** [comment]
Try testing this with CMI only, if issue persist, reset CMI configuration files and/or player data. This looks to be some issue with configuration settings. Cant really say what it is as its seam to be limited to your server only, which means its ether CMI configuration fault or not a CMI fault in general or some other weird behavior

**Comment by wonyoungb** [comment]
Somehow playerdata was broken so I deleted and restarted server.
That hp bug is fixed but that sql, and votifier is still not working
