### ISSUE TITLE
IllegalArgumentException Spam

### ISSUE THREAD

**Issue by Skizzles** [Zrips/CMI#4762]
**Description of issue:**
Console is being spammed with illegalargumentexceptions, as well as /give commands are not working.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/WWPWxujW
https://pastebin.com/VsqpNmw4
```

---

**Cmi Version (using`/cmi version`):** 8.7.12.0

**Server Type (Spigot/Paperspigot/etc):** Yatopia (Paper fork)

**Server Version (using `/ver`):** 1.16.4-r0.1

**Comment by Zrips** [comment]
This will be fixed with todays update. In hour or so.
