### ISSUE TITLE
Cuff muting option doesn't work with ChatControlRed

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#4768]
**Description of issue:**
If one sets the option "Mute" to true in the config under "Cuff" a cuffed player can still write when ChatControlRed is in use. With the `/cmi mute` command the mute works using ChatControlRed.

**Cmi Version (using`/cmi version`):** 
8.7.12.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper + Tuinity 
**Server Version (using `/ver`):** 
1.16.4
**Relevant plugins (Delete if this isn't needed):**
ChatControlRed version 10.1.9

**Comment by Zrips** [comment]
Should be resolved with next build

**Comment by TheoRetisch1** [comment]
It works thank you very much 💯
