### ISSUE TITLE
Silent "/cmi rt" command

### ISSUE THREAD

**Issue by mare-on** [Zrips/CMI#4769]
When I'm trying to use command: **/cmi rt [player Name] -s** nothing happening. In console it says "Command not found". After removing "-s" command works but players are notified.

**Cmi Version:** 8.7.12.1
**Server Type:** Paper 1.16.4-325
**Server Version:** 1.16.4

**Comment by Zrips** [comment]
Not all commands support -s variable and as **/rt ?** output indicates, there isint **-s** variable. Will add with next build.
