### ISSUE TITLE
[Issue] Removing user from database.

### ISSUE THREAD

**Issue by DutchUser** [Zrips/CMI#477]
**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 
30.05 15:43:27 [Server] INFO Vault version: 1.5.6-b49(CMIEInjector)
30.05 15:43:27 [Server] INFO Server version: Spigot 1.12.2-R0.1-SNAPSHOT
30.05 15:43:27 [Server] INFO CMI plugin version: 7.7.11.0

So. I used the command /cmi removeuser [uuid]

Then it says this in the console
`Player data was not found for uuid b9a9b794-49b6-491f-8893-7af03bd35ccd`

However, before i used the command i was enable to check the uuid in /whois <uuid> 
So it do exist. After that error it also gone from as example /whois.

However, when he joins again. He is back where he was, nothing has changed. And the /whois magicly works again on him.

I hope this can be fixed, as i need this to check something with the first spawn location. Because we allready said that it was fixed 2 times, and i want to be sure about it instead just saying it should work.

**Comment by DutchUser** [comment]
Console log stuff: https://pastebin.com/stjXSEKD

**Comment by LogGits** [comment]
This should be resolved in the latest builds. If not, please let me know 🙂
