### ISSUE TITLE
CMI Player Death Lagging Server

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#4771]
**Description of issue:**
When a player dies, the entire server will lag about 20-30secs and console will output lots of errors.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/x0tB6Jda
```

---

**Cmi Version (using`/cmi version`):** 
8.7.12.1

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
git-Paper-267 (MC:1.16.4)

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Should be resolved with next update. Tho this issue originates from trying to load players inventory from your database, which fails to process data in a reasonable amount of time. You might want to look into that.
