### ISSUE TITLE
/hat BUG with ProCosmetic Plugin

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#4772]
**Description of issue:**
When a player opens up procosmetic GUI, and select the cosmetic, they then use /hat and it will "force" that item to a hat. I have talked to the plugin dev and he said it isnt from his side. Please take a look.

Video:
https://user-images.githubusercontent.com/51330952/102756251-892f1e80-43aa-11eb-9689-48e56e706d2f.mp4
Image:
![ps](https://user-images.githubusercontent.com/51330952/102756274-90eec300-43aa-11eb-98d9-4c58132e6fbb.png)

---

**Cmi Version (using`/cmi version`):** 
8.7.12.1

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
git-Paper-267 (MC:1.16.4)

**Relevant plugins (Delete if this isn't needed):**
ProCosmetics
https://www.spigotmc.org/resources/procosmetics-280-cosmetics-treasurechests-eula-compliant-1-8-1-16-support.49106/

**Comment by Zrips** [comment]
/hat command will put any item you are holding in your hand as a hat. I don't have access to procosmetics plugin so i cant test it out and make any special support for it at this moment. 
In general i maybe could add option to define item name/lore which should not be allowed to be placed into head slot. Other than this, its not a bug.

**Comment by BboyZeroOne** [comment]
I could share the plugin file with you with the permission from the developer.

**Comment by Zrips** [comment]
If developer allows to share, then yea, i might get something after testing it. Tho even basic /itemnbt command could give some clues what i could check for and use that as indication that item should not be allowed to be placed in players head slot, if procosmetics dev uses any NBT tags

**Comment by BboyZeroOne** [comment]
I have sent you a pm via discord regarding the plugin.

**Comment by Zrips** [comment]
Will add option to prevent item placement which contains lore. This will be more general protection without need to define specific text which could be some what complicated to get every single possible variation.
