### ISSUE TITLE
IncludeInTabComplete (nick) -> still persists, extra info

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4774]
**Description of issue:**

---

Hi, this is reaction to https://github.com/Zrips/CMI/issues/4704. I've tried it on fresh server also unhooked from bungee with just these 3 pls:
![image](https://user-images.githubusercontent.com/18662086/102801384-740bbd00-43b5-11eb-806f-73c03773c737.png)
Now, when I try tab complete in normal chat, there aren't nicknames:
![image](https://user-images.githubusercontent.com/18662086/102801409-7c63f800-43b5-11eb-8fc5-e08b08aa0988.png)
Then, when I try /msg there also aren't 
![image](https://user-images.githubusercontent.com/18662086/102801450-884fba00-43b5-11eb-809b-7fe07c829f8a.png)
(default vanilla command, but it should maybe overwrite it? Same on another server, i'm using chatcontrol, but it should also overwrite it to show nick?)

Then finally it works only when using /cmi msg
![image](https://user-images.githubusercontent.com/18662086/102801519-9ef61100-43b5-11eb-92fa-e7a7ff2d5bc8.png)

So, the problem with normal /msg is probably it's overwritten by normal MC behavior or by ChatControl etc. when it's not alias, but shouldn't it be suggested everywhere?

Then, why it's not suggested in normal chat when tabbing?

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
default settings
```

---

**Cmi Version (using`/cmi version`):** 8.7.12.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 337, 1.16.4

**Comment by Zrips** [comment]
public chat suggests player names as this is default vanilla behavior and due to recent changes in Bukkit API i cant modify that list and include players nicknames. This is an issue from 1.13 and up. We can modify tabcompletes for commands, but regular chat tab complete might require some funky packet handling to modify it. So for now, we will have to live with what we got
