### ISSUE TITLE
/back is really broken

### ISSUE THREAD

**Issue by Yertled** [Zrips/CMI#4776]
**Description of issue:**
A majority of my players are having issues with the /back command. Most of the issues are spawning in the air after doing /back. I am talking at the top limit of the world. Y 256.
I believe it's mainly after a death occurs

---

**Cmi Version (using`/cmi version`):** 
8.7.12.1 SqLite
**Server Type (Spigot/Paperspigot/etc):** 
Tuinity
**Server Version (using `/ver`):** 
Tuinity cc34294

**Comment by Zrips** [comment]
Will make some adjustments to prevent from this happening in the future.
