### ISSUE TITLE
Selection Visualizer /svis wg showing wrong area

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#4777]
**Description of issue:**
After having bought and tested selection visualizer, I noticed that it shows the correct area for WorldEdit when you're selecting an area, however if you use WorldGuard to define a region in that area, then go into the region and do /svis wg or specify the name with /svis wg <name>, if its a polygon region its missing 1 block height on the top, and if its a cuboid its missing 1 block height on the top and is also missing1 block to the south and east.

---
Screenshots:
Cuboid WorldEdit: (Region shown correctly)
![2020-12-21_19 24 39](https://user-images.githubusercontent.com/29175884/102809981-d61af100-43ba-11eb-9168-9a1626be50ba.png)
Cuboid WorldGuard: (Region missing 1 block at the top, 1 block to the south and 1 block to the east)
![2020-12-21_19 25 02](https://user-images.githubusercontent.com/29175884/102810028-e59a3a00-43ba-11eb-88a3-46b17097cc7c.png)
Polygon WorldEdit: (Region shown correctly)
![2020-12-21_19 27 26](https://user-images.githubusercontent.com/29175884/102810071-f9de3700-43ba-11eb-9c15-c5332d35a87c.png)
Polygon WorldGuard: (Region missing 1 block at the top)
![2020-12-21_19 27 56](https://user-images.githubusercontent.com/29175884/102810085-006cae80-43bb-11eb-99fe-eecbbd318fc4.png)
---

**Selection Visualizer Version:** 3.0.3.1

**Server Type (Spigot/Paperspigot/etc):** Paper (Build 337)

**Server Version (using `/ver`):** 1.16.4

**Relevant plugins (Delete if this isn't needed):** WorldEdit & WorldGuard

**Comment by Zrips** [comment]
Thanks for reporting, will fix it.
