### ISSUE TITLE
Selection Visualizer not being activated when selecting worldguard region

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#4778]
**Description of issue:**
When selecting a region in worldguard the particles for the region isnt being shown, and you have to do /svis wg <region> to get the particles to show. I don't know if thats a bug or not but it feels like that would be a feature that would have been in the plugin.

---

**Selection Visualizer Version:** 3.0.3.1

**Server Type (Spigot/Paperspigot/etc):** Paper (Build 337)

**Server Version (using `/ver`):** 1.16.4

**Relevant plugins (Delete if this isn't needed):** WorldEdit & WorldGuard

**Comment by Zrips** [comment]
What exactly do you use to select area? Tool or command? If command, which one in particular?

**Comment by Zrips** [comment]
I guess you are talking about /rg select commands, will add support for those ones too.
