### ISSUE TITLE
[playerDisplayName] issue in AFK message

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#4780]
**Description of issue:**
For some reason for a couple of players (including me), the [playerDisplayName] placeholder doesn't show the nickname of a player from a third party plugin (ChatControl Red on Mc-Market). Yet for other players it works fine.

```
[23:01:29 INFO]: CMI: 8.7.12.1 BungeeCord  MySQL-> 8.7.12.2
[23:01:29 INFO]: Server: Tuinity 1.16.4-R0.1-SNAPSHOT
```

**Comment by Zrips** [comment]
Hmm, hard to say exactly, could be basic issue with lack of display name update triggers. Will recheck code and try to add couple of those which should update players display name more often.

**Comment by Sikatsu** [comment]
Alright, mine and some others never seem to update at all. It works for 3/4 of the times though! Thanks :)

**Comment by kangarko** [comment]
@Zrips let me know if that's an issue on your side or our. We call player#getDisplayName directly each time so we are not caching the result

**Comment by Sikatsu** [comment]
@Zrips @kangarko Seems it was an issue within CMI, as this one is solved in CMI's latest release! ^^
