### ISSUE TITLE
Selection Visualizer version number not updated

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#4788]
**Description of issue:**
Version check hasnt been updated after the newest update.

---
![asgsdfhsdfhsdfh](https://user-images.githubusercontent.com/29175884/102904928-58162300-446a-11eb-90db-b3b5db5bcf8a.PNG)

**Comment by Zrips** [comment]
It will be updated automatically, spigotmc has some delay until it updates cache with new version number.
