### ISSUE TITLE
Armorstand BUG/Compatibility with ProCosmetic plugin

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#4796]
**Description of issue:**
Players can place an item on an armorstand using procosmetics item/gadget etc from the selector and take it out like normal. You may watch the video as reference.

Video:
https://user-images.githubusercontent.com/51330952/102966041-08972c00-452a-11eb-97e7-d1ef8221bf29.mp4

---

**Cmi Version (using`/cmi version`):** 
8.7.12.3

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
git-Paper-267 (MC:1.16.4)

**Relevant plugins (Delete if this isn't needed):**
ProCosmetics

**Comment by BboyZeroOne** [comment]
Related to #4772

**Comment by Zrips** [comment]
This actually needs to be fixed by procosmetics dev as he needs to cancel armorstand interaction if player holds item from his plugin. CMI only allows to modify items throw GUI, while placing head on armorstand is vanilla behavior
