### ISSUE TITLE
Duplication bug with the command: /cmi uncondense

### ISSUE THREAD

**Issue by MisterFrans** [Zrips/CMI#4799]
**Description of issue:**
Hello,

Players with the /cmi uncondense can duplicate by making the command on a renamed block or ingot. When the player makes the command, the block/inglot is not removed from the inventory but the items are still given.

Thanks in advance for the patch and happy holidays.

---

**Cmi Version (using`/cmi version`):** 8.7.12.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.16.4 (Paper-342)

**Comment by radiant-ai** [comment]
I think this should be fixed ASAP

**Comment by Zrips** [comment]
Got a fix in recent updates
