### ISSUE TITLE
Addition/Placeholder

### ISSUE THREAD

**Issue by MCTyler** [Zrips/CMI#48]
Could you Please add a Placeholder for CMI Ranks? This would be very useful!  Right Now, I had to use LuckPerms and add Prefixes for those Groups which is really unnecessary since the ranks are just used in the Prison Ladder and do not need to be an actual group, the players just need to be associated to that group for WorldGuard Region association.

**Comment by Zrips** [comment]
Will be added with next build

**Comment by MCTyler** [comment]
The one you added doesn't work and broke some others like %cmi_user_balance%

**Comment by Zrips** [comment]
Double check this one with /cmi placeholders because for me all placeholders working correctly and i'm getting correct output with %cmi_user_balance%

**Comment by MCTyler** [comment]
I did. I even opened up a new ticket. How do we make our own?

**Comment by Zrips** [comment]
Do you have PlaceHolderAPI installed? CMI will not translate placeholders on other plugins, it will only work if you have PlaceHolderAPI and those plugins support it.

**Comment by MCTyler** [comment]
Yes, I have PlaceholderAPI. The user balance was working yesterday before your update.
