### ISSUE TITLE
/editwarp won't let me interact with any of the icons.

### ISSUE THREAD

**Issue by tmellen** [Zrips/CMI#480]
**Description of issue or feature request:**

As of 7.8.3.0,   /editwarp won't let me change anything. I can't change the icon of warps, placement, etc.

**Cmi Version (using`/cmi version`):** 7.8.3.0
**Server Type (Spigot/Paperspigot/etc):** Spigot
**Server Version (using `/ver`):** 1.12.2

**Comment by LogGits** [comment]
Are you still having this issue?
