### ISSUE TITLE
/nickname not updating unless you relog

### ISSUE THREAD

**Issue by Firosee** [Zrips/CMI#4802]
So for some reason, currently, nicknames only update once you relog, else they do not update atall. 

If you use the %player_displayname% placeholder in placeholderapi, nicks dont update until someone relogs, and if i use %cmi_user_nickname% if i do ./nick off, it sets it to nothing.

**Cmi Version (using`/cmi version`):** 8.7.12.4

**Server Type (Spigot/Paperspigot/etc):** Paperspigot 1.12.2

**Server Version (using `/ver`):** 1.12.2

**Relevant plugins (Delete if this isn't needed):**None, tested with just CMI, its vault addon & placeholderapi and this issue still exists.

**Comment by Firosee** [comment]
My suggestion is to either make the %player_displayname% update, or make it so doing ./nick off sets your nickname back to default, and not to just "".

**Comment by Zrips** [comment]
Well i cant fix another plugin placeholder, but i can make it to return players name in case you dont have set nick name for CMI placeholder which resolves your issue. This was implemented few versions back, so it should be up and running.
