### ISSUE TITLE
Suggest other permissions for command/cmi rmc

### ISSUE THREAD

**Issue by DreamMiu** [Zrips/CMI#4803]
If you accidentally leak the ID on the back，brush items BUG

**Comment by Zrips** [comment]
rmc generates random id which will be only valid ether for one time use or until server restarts or player relogs, depending on situation. Leaking ID which requires direct access to console is not that dangerous. And we do need some identification for commands which doesn't actually exist but we are waiting for player to perform it by clicking on something, usually chat message.
