### ISSUE TITLE
Votifier module doesn't turn off

### ISSUE THREAD

**Issue by EkonC** [Zrips/CMI#4804]
**Description of issue:**
When I turned off the votifier module in modules.yml, it was still working. I had to set commands that are performed to none.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# Handles votifier system
# Applies for servers from 1.7.x and up
votifier: false
```

---

**Cmi Version (using`/cmi version`):** 
8.7.12.4
**Server Type (Spigot/Paperspigot/etc):** 
Paper(344)
**Server Version (using `/ver`):** 
Paper version git-Paper-344 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):**
NuVotifier, VotingPlugin

**Comment by Zrips** [comment]
Confirmed, will be fixed with next build.
