### ISSUE TITLE
QuickShop Compatibility

### ISSUE THREAD

**Issue by EkonC** [Zrips/CMI#4806]
**Description of issue:**
QuickShop automatically generates signs when it creates shops but when the player edits the sign with shift and then removes the shop, it doesn't automatically remove the sign. Could you please prevent editing the QuickShop signs in CMI?

Here is the procedure to reproduce it:
1. Create a shop (left-click with item you want to sell)
2. edit the sign with shift edit
3. remove the shop
4. destroy the sign

---

**Cmi Version (using/cmi version):**
8.7.12.4
**Server Type (Spigot/Paperspigot/etc):**
Paper(344)
**Server Version (using /ver):**
Paper version git-Paper-344 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):**
QuickShop Reremake
https://www.spigotmc.org/resources/quickshop-reremake-1-16-ready-say-hello-with-rgb.62575/updates

**Comment by Zrips** [comment]
Will add option to define top sign line in which case we will prevent its editing with shift clicking which should resolve your issue

**Comment by EkonC** [comment]
Hello, this didn't really solve the issue because QuickShop doesn't use a shop prefix.
