### ISSUE TITLE
/glow colors aren't tab completed

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4808]
**Description of issue:**

---

Hi, I have problem that players don't know which colors they could exactly use in /glow. I think that in /glow <tab> should be shown /glow <colors/playerNames>. 

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/18662086/103138259-14712280-46d1-11eb-918e-63571ec3807a.png)

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/18662086/103138262-1935d680-46d1-11eb-8994-99f8a1e15dcc.png)

**Comment by Zrips** [comment]
Should be resolved with next release
