### ISSUE TITLE
Glow color is resetting after rejoin

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4809]
**Description of issue:**

---

Hi, I have problem that glow color is resetting after player rejoins. So if he uses /glow yellow and rejoins, he has white again... For one second he has yellow, but then it turns back to the white color.

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/18662086/103138259-14712280-46d1-11eb-918e-63571ec3807a.png)

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/18662086/103138262-1935d680-46d1-11eb-8994-99f8a1e15dcc.png)

**Comment by Zrips** [comment]
Could be caused by another plugin overriding glow color, which by itself is dependent on player teams, so could be one of your scoreboard plugins or related ones. Its known issue and until Mojang releases better way to handle glow color we will have to live with this some what broken system.

**Comment by bobhenl** [comment]
Oh noticed it's caused by https://www.spigotmc.org/resources/nametagedit.3836/, any idea how to fix it with plugin? Author already doesn't support it.

**Comment by bobhenl** [comment]
Oh followed this manual and fixed it https://github.com/NEZNAMY/TAB/wiki/How-to-make-TAB-compatible-with-glow-plugins, maybe could be useful, or you may will know better solution for it too
