### ISSUE TITLE
CommandCost.yml absolutely broken

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4810]
**Description of issue:**

---

Hi I have problem with commands yml... they are absolutely broken and doesn't work. I have set cost for command /armorstand, player try to use it, there's message for him that it costs 400€, but when he use it again it opens him menu without taking money... and this is happening to all commands in commandcost.yml section, so it absolutely doesn't work. 
![image](https://user-images.githubusercontent.com/18662086/103139357-a3833800-46db-11eb-8e4c-2378918b64f6.png)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
https://pastebin.com/qz4nSzHa
---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/18662086/103139367-c31a6080-46db-11eb-8a87-56084b55937f.png)

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/18662086/103139375-cb729b80-46db-11eb-91c1-4219750369a4.png)

**Comment by RafalKedziora** [comment]
Check if you enabled economy in config.yml and if you have Vault or CMI economy plugin. One of this plugins is required.

**Comment by bobhenl** [comment]
I have it enabled, but it doesn't take any costs, try it yourselves

**Comment by RafalKedziora** [comment]
I use this option on my server and it works.
