### ISSUE TITLE
Cannot redefine portals to different worlds

### ISSUE THREAD

**Issue by ViaSnake** [Zrips/CMI#4813]
**Description of issue:**
When try to redefine a portal set in world A to world B from the GUI, the world name in portals.yml is not changed.

---

**Cmi Version:** 8.7.12.4

**Server Type:** Paper

**Server Version:** 1.16.4 git-Paper-314

**Relevant plugins:** Hyperverse

**Comment by Zrips** [comment]
Should get a fix with next build
