### ISSUE TITLE
Tab complete on CMI is broken

### ISSUE THREAD

**Issue by ChiboYen** [Zrips/CMI#4814]
**Description of issue:**
Tab complete on the latest CMI is broken
/invsee does not suggest player names, /give and /i don't suggest item names anymore

**Cmi Version (using`/cmi version`):** 8.7.12.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.16.4

**Comment by Zrips** [comment]
Should be resolved with next update.
