### ISSUE TITLE
Spawners mine much faster than in vanilla.

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#4815]
**Description of issue:**

While I personally do not have a big issue with this. I hear back from players, and other CMI customers on Discord, that the Spawners we mine break too fast. There's quite a bit of customization with CMI Spawners. Some have a drop chance, others should break, some can't be picked up with a silk, others have a special tool for it we can configure. Etc. But a regular spawner as far as the user is concerned, that breaks when you mine it. For example in a mineshaft a spider spawner or something, it is a hit or two with a pick and poof it's gone. Sometimes this causes accidental breaking. 

It would be nice if the time is like the default time or close to it. 
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):**  any recent

**Server Type (Spigot/Paperspigot/etc):** spigot/paper

**Server Version (using `/ver`):** n/a but we're on 1.16.4 i guess

**Relevant plugins (Delete if this isn't needed):** n/a

**Comment by Zrips** [comment]
CMI doesn't control block breaking speeds, maybe there is hidden option to get this in case you are trying to break spawner placed by player as CMI have some small effect on that action, even tho its quite generic action which only changes spawner entity spawn type. In any case, without actual confirmation that there is actual difference between spawner breaking with CMI installed and without there is not much to do.

**Comment by mrfloris** [comment]
Okay, thank you for looking into it.

**Comment by broken1arrow** [comment]
> CMI doesn't control block breaking speeds, maybe there is hidden option to get this in case you are trying to break spawner placed by player as CMI have some small effect on that action, even tho its quite generic action which only changes spawner entity spawn type. In any case, without actual confirmation that there is actual difference between spawner breaking with CMI installed and without there is not much to do.

In vanilla it take at lest 1 seconds to break a spawner, but with cmi it instamine it (i try now in 1.16.4 and it is much better an was before). 

So I don´t know if it was vanilla issue/paper issue or if newer update from cmi fix it.

But you get no xp when break a spawner (when you break it and not pic it up).
