### ISSUE TITLE
[Issue] /recipe for AIR

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#482]
When using /recipe on AIR, it displays a somewhat bugged-out recipe. This should be changed so that it simply says it couldn't find any recipes.
**Cmi Version (using`/cmi version`):** 
7.8.3.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1441 1.12.2

**Comment by LogGits** [comment]
Great find and a `Unable to find a recipe. Please hold an item in your main hand.` message should be printed if they use the command with nothing in their hand.

**Comment by Zrips** [comment]
Will be fixed with next build.
