### ISSUE TITLE
General Support

### ISSUE THREAD

**Issue by Fargus5** [Zrips/CMI#4823]
Hello, I bought CMI
I was reading the plugin spigot page presentation at the first line where u suggest to download some packets for economy and for geolocalization.

just to inform u that links doesn't work
as for example: http://www.zrips.net/wp-content/uploads/2020/07/CMIEInjector1.0.2.3.jar

anyway... I logged in your discord but I didn't received an answer from anyone so I try to ask it here.
I just would like to buy Selection Visualizer too... but  I just have only one question after have readed the whole feature explanation on the main page...
This plugin works using FAWE in Paper 1.16.3 ???? thanks a lot for your prompt answer

**Comment by Zrips** [comment]
Thanks for pointing this one out. Seams to be small issue with https and http links. Should be in working order now.
SelectionVisualizer should work properly with FAWE if you get any issues you can always send a pm over discord.

**Comment by Fargus5** [comment]
ok thanks :)
