### ISSUE TITLE
Portal not working 

### ISSUE THREAD

**Issue by AuroraCraftSG** [Zrips/CMI#4825]
**Description of issue:**
Portal not working for bungee
When I created a new portal and set command 
server Survival,it didn’t teleport me to server 
And console appear error of unknown command,type /help for help

bungeecord: true
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):8.7.12.4

**Server Type (Spigot/Paperspigot/etc):paper 1.16.4

**Server Version (using `/ver`):1.16.4

**Comment by Zrips** [comment]
Use appropriate command like `asConsole! cmi server Survival [playerName]` this will make sure to perform command from console and send player to target server without actually giving player access to server command. Otherwise you might simply forgot to enable alias for server command in alias.yml
