### ISSUE TITLE
Pweather

### ISSUE THREAD

**Issue by Ellendyra** [Zrips/CMI#4826]
**Description of issue or feature request:**
The weather on our server is out of sync even though we have never set our pweather. The time also seems out of sync as well on occasion for players. If you reset your /pweather then you can see the rain but next time it rains I often find you have to reset it again. This is occurring for all my players even though they are not even allowed access to that command in the first place.
 
---

---

**Cmi Version (using`/cmi version`):** 
29.12 22:30:46 [Server] INFO --------------------------------------------------
29.12 22:30:46 [Server] INFO CMI: 8.7.12.0 SqLite-> 8.7.12.4
29.12 22:30:46 [Server] INFO Server: Paper(282) 1.16.4-R0.1-SNAPSHOT
29.12 22:30:46 [Server] INFO CMI economy: True Vault: 1.7.3-b CMI Chat: True 
29.12 22:30:46 [Server] INFO Modules -> 52 enabled 2 disabled: votifier, cmiPlaytime
29.12 22:30:46 [Server] INFO --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
29.12 22:31:23 [Server] INFO This server is running Paper version git-Paper-282 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
29.12 22:31:23 [Server] INFO Checking version, please wait...
29.12 22:31:24 [Server] INFO Previous version: git-Paper-342 (MC: 1.16.4)
29.12 22:31:24 [Server] INFO You are 70 version(s) behind
**Relevant plugins (Delete if this isn't needed):** 
29.12 22:31:48 [Server] INFO Plugins (79): Backpacks, BestTools, BetterBees, BetterConcrete, BetterFarming, BlockLocker, BookShelf, BountyHunters, Brewery, BuycraftX, ChatBrawl, ChestCleaner, Citizens, CitizensCMD, CMI, CMIPaperLib, CoreProtect, CraftedBy, CrateReloaded, DeluxeTags*, DiscordSRV, DragonEggDrop, DynamicShop, EnhancedCrafting, EntityTrackerFixer, Epidemic, ExperienceTome, FastLeafDecay, Faucet, FeatherBoard*, GoldenEnchants, HeadDatabase, HorseTpWithMe, ImageOnMap, InvUnload, IronNuggets, Jobs, LiteBans, LuckPerms, MapTeleport, MarriageMaster, MCEmojis, mcMMO, MessageAnnouncer, MobFarmManager, Multiverse-Core, Multiverse-Portals, MVdWPlaceholderAPI*, NBTAPI, NexEngine, NPC_Destinations, OuroborosMines, Petting*, PhatLoots, PL-Hide, PlaceholderAPI, PlayerReport, PlayerWarps, PlugMan, ProtocolLib, Quests, QuickShop, RandomTeleport, ResourceWorld, SaveRodOfficial*, Sentinel, ShopGUIPlus, SurvivalInvisiframes, SurvivalPlus, SwimmingHorses, Towny, TownyFlight, TownyNameUpdater, UpgradeableSpawners, Vault, Vouchers, WorldEdit, WorldGuard, WorldGuard-Towny*

**Comment by Zrips** [comment]
CMI only changes players weather in one single place, weather command. So its ether being triggered by some other means or another plugin changing players weather. You might want to look around your plugins to test out which one could change it, but its not an issue with CMI in general, worst case, something triggers weather command from CMI plugin, but you need to fix that trigger.
