### ISSUE TITLE
Armor Stan editor items fly out when you close the armor stand editor.

### ISSUE THREAD

**Issue by Ellendyra** [Zrips/CMI#4827]
**Description of issue:**
When using the armor stand editor all the wool, paper, etc pops out when you close the menu. These items do disappear but if you place them before opening like a chest or something you get to keep it. 

---

---
**Cmi Version (using`/cmi version`):** 
29.12 22:30:46 [Server] INFO --------------------------------------------------
29.12 22:30:46 [Server] INFO CMI: 8.7.12.0 SqLite-> 8.7.12.4
29.12 22:30:46 [Server] INFO Server: Paper(282) 1.16.4-R0.1-SNAPSHOT
29.12 22:30:46 [Server] INFO CMI economy: True Vault: 1.7.3-b CMI Chat: True 
29.12 22:30:46 [Server] INFO Modules -> 52 enabled 2 disabled: votifier, cmiPlaytime
29.12 22:30:46 [Server] INFO --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
29.12 22:31:23 [Server] INFO This server is running Paper version git-Paper-282 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
29.12 22:31:23 [Server] INFO Checking version, please wait...
29.12 22:31:24 [Server] INFO Previous version: git-Paper-342 (MC: 1.16.4)
29.12 22:31:24 [Server] INFO You are 70 version(s) behind
**Relevant plugins (Delete if this isn't needed):** 
29.12 22:31:48 [Server] INFO Plugins (79): Backpacks, BestTools, BetterBees, BetterConcrete, BetterFarming, BlockLocker, BookShelf, BountyHunters, Brewery, BuycraftX, ChatBrawl, ChestCleaner, Citizens, CitizensCMD, CMI, CMIPaperLib, CoreProtect, CraftedBy, CrateReloaded, DeluxeTags*, DiscordSRV, DragonEggDrop, DynamicShop, EnhancedCrafting, EntityTrackerFixer, Epidemic, ExperienceTome, FastLeafDecay, Faucet, FeatherBoard*, GoldenEnchants, HeadDatabase, HorseTpWithMe, ImageOnMap, InvUnload, IronNuggets, Jobs, LiteBans, LuckPerms, MapTeleport, MarriageMaster, MCEmojis, mcMMO, MessageAnnouncer, MobFarmManager, Multiverse-Core, Multiverse-Portals, MVdWPlaceholderAPI*, NBTAPI, NexEngine, NPC_Destinations, OuroborosMines, Petting*, PhatLoots, PL-Hide, PlaceholderAPI, PlayerReport, PlayerWarps, PlugMan, ProtocolLib, Quests, QuickShop, RandomTeleport, ResourceWorld, SaveRodOfficial*, Sentinel, ShopGUIPlus, SurvivalInvisiframes, SurvivalPlus, SwimmingHorses, Towny, TownyFlight, TownyNameUpdater, UpgradeableSpawners, Vault, Vouchers, WorldEdit, WorldGuard, WorldGuard-Towny*

**Comment by Zrips** [comment]
Wool or any item from UI at moment of close cant pop out. atleast not in a normal situation. This looks more like other plugin dropping items existing in your top inventory on inventory close. Test this without any other plugin but CMI only to make sure its an issue with CMI or not. If it not, then add half of the plugins back and retest, if issue came back, remove half of them, if there isint any issue, then return half of remaining plugins. Rinse and repeat until you get to the one which causes this issue.
