### ISSUE TITLE
[ISSUE] Chat being DUPED

### ISSUE THREAD

**Issue by PretendBullet50** [Zrips/CMI#483]
Chat is being DUPED to other servers!
I am running a BungeeCord Server and the Server Chat is being sent to other servers on the network! I haven't enabled this even know it was a thing... This only started after I installed CMI... In the server I'm chatting in it looks fine but in the server being duped, this is what it looks like!

For Example: In the Survival Server when people chat it will show like in the picture below in the hub a entierly different server...

![screen_shot_2018-06-08_at_22 00 44](https://user-images.githubusercontent.com/29534385/41179309-29cce050-6b1f-11e8-8cf0-04944d4de819.png)

**Comment by LogGits** [comment]
What is the output of `/cmi version` (all messages). This was a bug with an older version of cmi, let us know if this happens on the latest build.

**Comment by PretendBullet50** [comment]
Sorry for the delay been working my 2 jobs... I will let you know tommrow or very late tonight.

**Comment by PretendBullet50** [comment]
Sorry for the SUPER LATE reply! My PC was having issues and could not load in!

Here is my current set up! I have 4 servers!
- Proxy (No CMI)
- Survival (No CMI)
- Hub (Yes CMI)
- Project (Yes CMI)

I do not have MySQL set up in the CMI config file but all the servers are hosted off of one 8 GB Server but separated via ports in Docker!

In the First pic below you will see my HUB SERVER also the pic in the original post is from hub!
![image](https://user-images.githubusercontent.com/29534385/41496624-dfeab3f6-70f8-11e8-9c3a-657445aa11e0.png)

In this next PIC is from my Project Server! I am aware it is an OLDER version but it's the ONLY stable version that will keep the server running! If I try to update it AT ALL it will crash within 5 sec of a user joining. (More about this is a sec)
![image](https://user-images.githubusercontent.com/29534385/41496631-21734fea-70f9-11e8-9b57-ff6f8c2a2e52.png)

Now when a Player CHATS in the Project Server it goes to the HUB!
For Example: If I say "Hi" or anything in Project it shows up Normally in Project but it ALSO goes to HUB an ENTIERLY DIFFERENT SERVER, it says it twice exactly shown in the pic above!

I have tried to update to Project Server but as I mentioned before it Crashes! I mean it will load fine but as soon a Player joins it crashes within 5 sec! I have uninstalled one plugin at a time to find the issues and it was CMI causing it! I then go back to the last build that was working and I have no issues with the crashing part!

So at this point, I come on here hoping to get some help! I am also again sorry for the SUPER LATE REPLY! I have just been having issues with the PC just got it working!

**Comment by LogGits** [comment]
Have you tried using cmi's version of vault?

**Comment by PretendBullet50** [comment]
No,I didn't know you guys had your own Vault Plug-In. Would this be on your spigot page?

**Comment by MCTyler** [comment]
![capture](https://user-images.githubusercontent.com/6390898/41689893-91c34936-74b8-11e8-8695-4bca48403e41.PNG)

**Comment by MCTyler** [comment]
Never got pass the Download Button Huh?

**Comment by PretendBullet50** [comment]
Ok I'll try that when I get home and let you know
