### ISSUE TITLE
Get Steve's head when doing /head or /cmi head 

### ISSUE THREAD

**Issue by ChitterChatter** [Zrips/CMI#4831]
**Description of issue:**

When anyone does /head or /cmi head, or even /head [player]  we always get Steve's head, not the players head.  No errors, just get Steve's head. 
---

---

**Cmi Version (using`/cmi version`):**   8.7.12.1

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  Paper(319) 1.164 -R0.1-Snapshot

**Relevant plugins (Delete if this isn't needed):**  We do have head database plugin (/hdb), as well as Slimefun, Exotic Garden and some Slime Fun addons. None of these plugins are causing any issues, and all the decorative heads through all of these are working as they should be and the head textures are proper.

**Comment by Zrips** [comment]
Seams to be related to new minecraft API relating to player profile data. In any case, will get a fix with next build.
