### ISSUE TITLE
Feature Request: Nickname placeholder without colour

### ISSUE THREAD

**Issue by Alejandro-Sosa** [Zrips/CMI#4837]
Simply put i want to control the colour on players names in tablist but the colours are in the way. However i don't want to revert using their ign for confusion sake.

A placeholder that shows the nickname but strips it of any colour would be very useful and a welcoming addition.

**Comment by Zrips** [comment]
Wrong section, feature requests need to be put into discussion section as it was mentioned in a ticket template.
