### ISSUE TITLE
/armorstand command + middle click on name change -> cantClick string message

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4841]
**Description of issue:**

---

Hi, when someone tries to edit armor stand name with middle click to edit it's name, there's cantClick sstring message. It doesn't appear when you click with shift on armor stand, just when using /armorstand.

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/18662086/103449595-969db000-4caa-11eb-9a26-23b418b82e49.png)

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/18662086/103449596-9b626400-4caa-11eb-84fa-0117d1ea640e.png)

**Comment by Zrips** [comment]
What do you mean by saying middle mouse click to edit its name? Is this another plugin?

**Comment by bobhenl** [comment]
No I mean this button:
![image](https://user-images.githubusercontent.com/18662086/103460625-072ee600-4d18-11eb-9ad5-172414cf1dfe.png)

Middle click to edit it's name, in armor stand editor, but only happens if you go there via /armorstand.

When you go there by shift + right clicking on armor stand, this message won't appear

**Comment by Zrips** [comment]
Should be fixed with next build
