### ISSUE TITLE
Nested placeholders

### ISSUE THREAD

**Issue by kforbro** [Zrips/CMI#4842]
**Description of issue:**
Placeholders with nested placeholders don`t work properly in holograms. In other plugins and in "/papi parse me" works fine.
![image](https://user-images.githubusercontent.com/39985355/103453725-ebaee580-4ced-11eb-8818-edb26ad5a18f.png)

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Lines:
- '%parseother_{leaderheads_name_statisticplayerkills_alltime_1}_{vault_prefix}%%leaderheads_name_statisticplayerkills_alltime_1%'
```

---

**Cmi Version (using`/cmi version`):**  8.7.12.2

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot

**Server Version (using `/ver`):**  git-Paper-352 (MC: 1.16.4)

**Relevant plugins (Delete if this isn't needed):** PlaceholderAPI

**Comment by Zrips** [comment]
Does it work with **/cmi placeholders parse** command?

**Comment by kforbro** [comment]
> Does it work with **/cmi placeholders parse** command?

No.

`%parseother_{leaderheads_name_statisticplayerkills_alltime_1}_{vault_prefix}%` returns %parseother_kFor_Admin% instead of Admin

**Comment by AerWyn81** [comment]
Same issue here.

**Comment by Zrips** [comment]
Should be in working condition with next update.
