### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by kforbro** [Zrips/CMI#4854]
**Description of issue:**
I use the Command whitelist plugin so that players only have access to certain commands. But this plugin does not work correctly with CMI commands due to the features of CMI aliases. This can be avoided by adding CMI commands to the commands.yml from Paper, but because of this, the tab complete arguments do not work. The developer of Command whitelist said that this is a problem on the CMI side and he can't do anything about it.

```
Ah, I know exactly what are you talking about now. It's not a bug on my side, CMI aliases do not register as commands. Instead, they make player execute /cmi .

You can solve this by setting up aliases in bukkit's commands.yml and turning off CMI aliases.
There is literally no way for me to react to this type of plugin behavior.
```
```
I did indeed reproduce the issue. commands.yml is the go-to alias creation and the fact that cmi tab completions are not working indicate that they're most likely done incorrectly, just like commands. You can open a bug report about this for CMI, but I doubt zrips will do anything about it.
```

https://github.com/YouHaveTrouble/CommandWhitelist/issues/12
https://github.com/YouHaveTrouble/CommandWhitelist/issues/13
---

**Cmi Version (using`/cmi version`):** 8.7.12.2

**Server Type (Spigot/Paperspigot/etc):** Paper(352) 1.16.4

**Server Version (using `/ver`):** Paper(352) 1.16.4

**Relevant plugins (Delete if this isn't needed):** [CommandWhiteList](https://www.spigotmc.org/resources/commandwhitelist-spigot-1-8-1-16-bungeecord-waterfall.81326/)

**Comment by CloudeLecaw** [comment]
Cmi allready Jus give you tab completation and listet help for all commands you have permission for.
So whats your Problem with it?
If u gave Access to a command the player has this Inntab completation. Some u can negate to avoid players see them in tab completation.

**Comment by kforbro** [comment]
> Cmi allready Jus give you tab completation and listet help for all commands you have permission for.
> So whats your Problem with it?
> If u gave Access to a command the player has this Inntab completation. Some u can negate to avoid players see them in tab completation.

If you make aliases to CMD commands via commands.yml from Paper, then tabcomplete arguments will not work.

**Comment by CloudeLecaw** [comment]
If you make aliases to CMD commands via commands.yml from Paper, then tabcomplete arguments will not work.

make them in custom alias aor use the once in alias.yml inside cmi folder

if you mae them in commands.ml this is a problem that accounts to 99% of all plugins
CMI cant do anything there

**Comment by kforbro** [comment]
> > If you make aliases to CMD commands via commands.yml from Paper, then tabcomplete arguments will not work.
> 
> make them in custom alias or use the once in alias.yml inside cmi folder
> 
> if you mae them in commands.yml in th servers mainfolder this is a problem that accounts to 99% of all plugins
> CMI cant do anything there.
> im also not recommand to use them,
> use them only if you have no limitaed arugments after or just need the playername argument after - the only thing that commands.yml supports

What if I need a Command Whitelist that doesn't support CMI aliases because those aliases don't register as commands?

**Comment by CloudeLecaw** [comment]
use custom alias for that thata a cmi feature
custom alais dont need to be cmi commands

**Comment by kforbro** [comment]
> use custom alias for that that's a cmi feature
> custom alais dont need to be cmi commands
> 
> Well looks like your getting in conflict somewhere.
> If you cant solve it u may need to be a bit more detailed about your problem.
> 
> * what does not work like you want it.
> * what should happen
> * what commands are effect.
> * how you thought it should work
> * what you tried
> 
> all with codelines so we can see what your trying to do
> then we may can help and try to see what cmi can do here :-)
> 
> Just saying "something does not work" is not enough

I use the CommandWhitelist plugin to hide plugins and commands that players don't use. CommandWhitelist`s config:
```
messages:
  command-denied: "&fNo such command."
  ... others messages

commands:
  # Permissions that control what commands players can use
  # you can add unlimited amount of whitelists

  # this will be automatically given to players by default
  default:
    - menu
    - warp
    - /wand
    - /sel
    - /expand
    - rg
    - region
    - g
    - guild
```


The developer of the CommandWhitelist plugin said that this problem occurs because CMI aliases do not register as commands. He advised me to make aliases via Paper`s commands.yml. And it works, but tabcomplete arguments don't work for these aliases.
Players will be able to use only those teams that are on the list. When entering other commands, they will receive the message "No such command".
![image](https://user-images.githubusercontent.com/39985355/103529149-34090780-4e96-11eb-939e-1355a838f523.png)
![image](https://user-images.githubusercontent.com/39985355/103529175-3ec39c80-4e96-11eb-98e6-f149fc59525f.png)


But this plugin conflicts with aliases made in CMI. Players get the /warp command, but they get a "No such command" message when they send it
![image](https://user-images.githubusercontent.com/39985355/103529398-a5e15100-4e96-11eb-8876-0a49ea2ea2fb.png)
```
CustomAlias:
  warp:
    Cmds:
    - cmi warp $1-
```

**Comment by kforbro** [comment]
> > use custom alias for that that's a cmi feature
> > custom alais dont need to be cmi commands
> > Well looks like your getting in conflict somewhere.
> > If you cant solve it u may need to be a bit more detailed about your problem.
> > 
> > * what does not work like you want it.
> > * what should happen
> > * what commands are effect.
> > * how you thought it should work
> > * what you tried
> > 
> > all with codelines so we can see what your trying to do
> > then we may can help and try to see what cmi can do here :-)
> > Just saying "something does not work" is not enough
> 
> I use the CommandWhitelist plugin to hide plugins and commands that players don't use. CommandWhitelist`s config:
> 
> ```
> messages:
>   command-denied: "&fNo such command."
>   ... others messages
> 
> commands:
>   # Permissions that control what commands players can use
>   # you can add unlimited amount of whitelists
> 
>   # this will be automatically given to players by default
>   default:
>     - menu
>     - warp
>     - /wand
>     - /sel
>     - /expand
>     - rg
>     - region
>     - g
>     - guild
> ```
> 
> ![image](https://user-images.githubusercontent.com/39985355/103529149-34090780-4e96-11eb-939e-1355a838f523.png)
> ![image](https://user-images.githubusercontent.com/39985355/103529175-3ec39c80-4e96-11eb-98e6-f149fc59525f.png)
> 
> But this plugin conflicts with aliases made in CMI. Players get the /warp command, but they get a "No such command" message when they send it
> ![image](https://user-images.githubusercontent.com/39985355/103529398-a5e15100-4e96-11eb-8876-0a49ea2ea2fb.png)
> 
> ```
> CustomAlias:
>   warp:
>     Cmds:
>     - cmi warp $1-
> ```
> 
> The developer of the CommandWhitelist plugin said that this problem occurs because CMI aliases do not register as commands. He advised me to make aliases via Paper`s commands.yml. And it works, but tabcomplete arguments don't work for these aliases.
> Players will be able to use only those teams that are on the list. When entering other commands, they will receive the message "No such command".

This happens with any commands associated with CMI aliases
