### ISSUE TITLE
[request] Reintroducing the Essentials' powertool

### ISSUE THREAD

**Issue by wanhe886** [Zrips/CMI#486]
Sorry for the double posting.

Since CMI is trying to replacing Essentials, why not also introducing Essentials' powertool features, which let you bind command to a item. 

Right now CMI can only bind command to an individual item, when player loose it, they loose it forever. If powertool is introduced, they can just get another same item and they are good to go.

**Comment by TheWranger** [comment]
In my opinion, CMI handles it far better so if this gets added, we should still be able to switch back to the current system.

**Comment by wanhe886** [comment]
Just add powertool as a separate feature, instead of replacing the individual command bind.
