### ISSUE TITLE
%cmi_user_cleannickname% doesn't display anything when no nick set

### ISSUE THREAD

**Issue by Alejandro-Sosa** [Zrips/CMI#4866]
The placeholder %cmi_user_cleannickname% doesn't display the users name whenever a nick isnt set.

**Cmi Version (using`/cmi version`): 8.7.12.6** 

**Server Type (Spigot/Paperspigot/etc): Paper**

**Comment by Zrips** [comment]
That's kind of a point of placeholder like that. But in general i can change its behavior in addition to %cmi_user_nickname% and return players name if nickname is not set
