### ISSUE TITLE
cmi removeuser duplicates destryos the server to 1tps and crashes.

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#4868]
CMi tells me to run `cmi removeuser duplicates` but when you do, its so badly optimized with large data sets it crashes the server. Same for anything that scans all users / import from other plugins, it always crashes the server. I have 300k users.

**Comment by Zrips** [comment]
Will add some extra optimizations. Tho this should have caused issues in case you have quite few duplicates which needs to be purged out, including removal of files.

**Comment by TomLewis** [comment]
Since making this post I'm closer to 350,000 players in the database now!
