### ISSUE TITLE
Horse Speed Stat using /cmi entityinfo may be miscalculated

### ISSUE THREAD

**Issue by farisjaclyn** [Zrips/CMI#4869]
Hello! I run a horse themed MineCraft server where horse stats are _extremely_ important to players.

We believe the /cmi entityinfo may be slightly off with the speed of a horse. 

On a fan wiki site, it says that the highest speed a horse can have is 14.23 blocks/second. We have found horses that have speeds higher than that when we use the /cmi entityinfo command. All horses bred in-game were done in survival without commands/summons/command blocks. I have reached out to MineCraft technical support trying asking if the speed of a horse changed in 16 but I haven't really gotten much of a response.

![horse speed entity info](https://user-images.githubusercontent.com/46360512/103688338-4c8d2680-4f57-11eb-8e01-b1ee91daf730.JPG)

I had a player create this google sheet demonstrating the way the speeds should look compared to our old system and your /cmi entity info system.

https://docs.google.com/spreadsheets/d/1zc0ZuIzavBzv1SaghfDL9ixADqU27GTtWvZ-UBjuUUU/edit#gid=1904193270

We believe there may have been a slightly miscalculation done. I understand this can seem a little hypercritical. The players on my server noticed this and love comparing their horse's stats for the best, so for them it really matters.

Thank you for your time,

Faris

---

**Cmi Version (using`/cmi version`):** latest

**Server Type (Spigot/Paperspigot/etc):** paper - latest

**Server Version (using `/ver`):** 1.16.4

**Comment by farisjaclyn** [comment]
I should mention - this specific horse actually was spawned via a horse egg item that admin sold. The player spawned the horse from the egg while in survival mode.

**Comment by Zrips** [comment]
Yea, it was tiny bit out of place. Dint known that it will be a noticeable issue when it comes to such small differences. Will be fixed with next build.
