### ISSUE TITLE
Add /clearinventory command with alias /ci

### ISSUE THREAD

**Issue by Fiks75** [Zrips/CMI#487]
Please add the /clearinventory command with alias /ci as in Essentials.
In your plugin, alias /ci works together with the command /cmi inv. It is not right.
 
CMI plugin version: 7.8.3.0
Server version: Spigot 1.12.2-R0.1-SNAPSHOT
Vault version: 1.5.6-b49
CraftBukkit version git-Spigot-2086bb0-8cc5a7e

**Comment by LogGits** [comment]
I also agree with this. The `/ci` default alias should be used for `/clearinventory`, not `/inv`.

**Comment by arturek1666** [comment]
Not really big deal with this fix I have to say
Ehh really just go to the Alias.yml disable the:
  /ci: true to /cmi: false

Go to CustomAlias and add:
  ci:
  - re clearinventory $1-

This is not that hard to change your self :)
I mean I am not against the change but for now you can do that :) and what you want you will have :) without waiting for update.

**Comment by CloudeLecaw** [comment]
u can create an alias for /cmi clear...

**Comment by Zrips** [comment]
Will make this happen
