### ISSUE TITLE
8 args maximum instead of 9 before in alias commands

### ISSUE THREAD

**Issue by BBSnowIce** [Zrips/CMI#4879]
**Description of issue:**
It seems impossible to use more than 8 arguments in custom alias, previously, it was possible to go up to 9. (Maybe going to more than 9 ?)

---

**Cmi Version (using`/cmi version`):** 
8.7.12.7
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
git-Paper-1618 (MC: 1.12)

**Comment by CloudeLecaw** [comment]
Usually u can use more if needed... 
What command ubdesgined that needs that big amount?

**Comment by BBSnowIce** [comment]
A command with weighted probabilities, I could not use more than 9 arguments in the past (what I mean by arguments are the ones marked with $n with n, the index +1).

**Comment by Zrips** [comment]
@BBSnowIce 
Can you give actual example of your command you are trying to perform?

**Comment by BBSnowIce** [comment]
Here is the test command I made, the ninth argument is not parsed when `/test 1 2 3 4 5 6 7 8 9` executed
```yml
CustomAlias:
  test:
    Cmds:
    - msg! [playerName] $1 $2 $3 $4 $5 $6 $7 $8 $9
```

**Comment by Zrips** [comment]
Got it, relatively simple fix and should be back in working order. And this was due to introduction of $0 variable which shifted max allowed number by one and we lost last one
