### ISSUE TITLE
"you can't perform this action in this area"

### ISSUE THREAD

**Issue by ChiboYen** [Zrips/CMI#4880]
When a player tries to do /sethome, they are met with "you can't perform this action in this area" yet there is no worldguard region or anything that would prevent the command, therefore the issue is due to CMI and is a bug.

---

**Cmi Version (using`/cmi version`):** 8.7.12.7

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.16.4

**Comment by CloudeLecaw** [comment]
What is your config designt too? May you created an areanwhere the command is notnallowed...

**Comment by ChiboYen** [comment]
There is no area that I created in the area

**Comment by Zrips** [comment]
If you see message from completely different plugin when player performs command, its not a bug with CMI. Determine from which plugin this message originates and double check if its not blocking commands in entire world or something.
