### ISSUE TITLE
Uncondense dupe glitch

### ISSUE THREAD

**Issue by Nekomitsuki** [Zrips/CMI#4884]
**Description of issue:**
Using uncondense on renamed item by /rename (for example Iron Block) doesn't remove blocks but creates iron ingots. Also affects Slimefun.
Doesn't work with condense.
![image](https://user-images.githubusercontent.com/45139953/104093555-76ae5380-528b-11eb-881a-2eaa48ea3b81.png)

---

**Cmi Version (using`/cmi version`):** 8.8.0.0

**Server Type (Spigot/Paperspigot/etc):** Yatopia leaflight branch

**Server Version (using `/ver`):** 1.16.4

**Comment by Zrips** [comment]
Noted, will issue fix with next update
