### ISSUE TITLE
[Issue] /toast not supporting metadata

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#489]
**Description of issue or feature request:**
/toast does not support item metadatas. Can't use things like ink_sack:2

**Cmi Version (using`/cmi version`):** 
7.8.3.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Build 1441 - 1.12.2

**Comment by Gasha666** [comment]
its working, i tested.. you are using wrong name

you can use ID: 351 or ink_sack   or even its enough just to put ink

**Comment by TheWranger** [comment]
That has nothing to do with it, /toast isn't recognizing item meta datas.
ink_sack:2 is supposed to show a cactus dye when it shows a default dye, I also tested this with SKULL_ITEM.
