### ISSUE TITLE
Homes migration issue with 1.12.2

### ISSUE THREAD

**Issue by AerWyn81** [Zrips/CMI#4893]
**Description of issue:**

CMI throwed an exception when user used command /homes (see exception details below). 
We tried a migration on a 1.16 test server, that's worked but not with a server in 1.12. I guess that a problem where world does not exist and cmi cannot retrieve the highestblockAt for homes. 

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```
https://pastebin.com/YkziRhhj

---

**Cmi Version (using`/cmi version`):** latest

**Server Type (Spigot/Paperspigot/etc):**  Paper 1618

**Server Version (using `/ver`):**  1.12.2

**Comment by Zrips** [comment]
Should be fixed with next version.
