### ISSUE TITLE
Permission Node Confusion

### ISSUE THREAD

**Issue by Royster0** [Zrips/CMI#4897]
Not sure if this is a typo or intentional but on page 1 when you type /cmi checkperm, the 2nd entry is cmi.colors.[type].*2

What is the *2 bit for? I understand the rest of the node but the *2 bit is confusing me.
---
![CaptureCMI](https://user-images.githubusercontent.com/44376499/104200225-4ea42900-5420-11eb-82ba-9d4524db5e4f.PNG)

**Cmi Version: 8.8.0.1

**Server Type Paper

**Server Version: Ver 399

**Comment by CloudeLecaw** [comment]
Thie is is a wildcard for all colors that end with 2 (all hexcolors)
in your permissionsystem u need to define the type or youallready use the wildcart cmi.colors.* what would include all types all also the *2

**Comment by Zrips** [comment]
Its actually a typo, that 2 should not be there. Will remove with next update
