### ISSUE TITLE
[Request] /cmi kill command

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#490]
Add a /cmi kill command where we can define what the death cause will be. /cmi suicide should be kept separate.

**Comment by CloudeLecaw** [comment]
a bit mire specifiy for a request would be cool. like
**cmi kill [suicide/Player] (reason)** ? 
permission: **cmi.command.kill**  and **cmi.command.kill.others**
   so u have Option for suicide and kill others
also add an -s Option for doing it silent.. not every Player must know an admin or console killed him^^

if No reason is set up then a Default reason (config) is choosen
if no suicide or Playername is choosen then a Default Option (config?) should be choosen
also thought abotu respecting Nicked Players ;)

**Comment by TheWranger** [comment]
There's no need to add a suicide feature to /CMI kill.
The death cause is the internal death cause, not a reason for the player dying.

**Comment by CloudeLecaw** [comment]
i see that it may iss more simply to use spigot Default death reasons...may make sense for analytiscs or what after.
and no it does not make sense to Keep suicide seperate. /kill without Argument kills you and done
so you can kill yourself and others (with extra permision) and if an admin Forgets to use Arguments ist his own fault if he kill hisself.

There is no reason for an extra suicide command

**Comment by TheWranger** [comment]
I disagree, we need too commands:
/suicide (what we currently have)
/kill <PLAYER> <SPIGOT_DEATHCAUSE>

/kill should be used for killing people with cusom causes, /suicide should be left alone.

**Comment by CloudeLecaw** [comment]
**/cmi suicide (playerName) (-s) - Kill your self or target player** 
permisisons:
cmi,command.suicide   and  cmi.command.suicide.others.


i see the kill Option for suicide and others is done allready and a kill alais u can create by yourself (CustomAlias)

i see no reason for adding the DeathReason. Why should you? For printing out a faked DeathReason when you killed someone?

pls close this page, because the wanted Option is allready there.

**Comment by TheWranger** [comment]
1. There are several good reasons for setting a custom death cause, not only is this important for debugging but this is also really good for allowing us to control what death message appears.
2. Here's spigots list of internal death/damage causes: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/event/entity/EntityDamageEvent.java#280
3. Esssentials doesn't allow you to change what death cause /kill uses.

**Comment by CloudeLecaw** [comment]
> Esssentials doesn't allow you to change what death cause /kill uses.

jep because ist not nessesary
