### ISSUE TITLE
/me is not displaying correctly

### ISSUE THREAD

**Issue by Royster0** [Zrips/CMI#4900]
/me is not displaying the prefix correctly. This only seems to be an issue with /me. This doesn't happen in chat, pm's etc

![Me not working](https://user-images.githubusercontent.com/44376499/104353204-92219480-54ff-11eb-8323-fc1a30c68a31.PNG)

![me2](https://user-images.githubusercontent.com/44376499/104353229-95b51b80-54ff-11eb-8e21-0b2df2bcc0b8.PNG)

**Cmi Version: 8.8.0.2

**Server Type: Paper

**Server Version: Ver 403

**Comment by Zrips** [comment]
Should be in working order with next update
