### ISSUE TITLE
CMI is causing a high tick on NBT related stuff 

### ISSUE THREAD

**Issue by Lorenzostuy** [Zrips/CMI#4901]
**Description of issue:**

https://timings.aikar.co/?id=4a4c30ab0ac94c4994fe48b74c093cf8
CMI Is causing a high tick on NBT stuffs (Most likely MMOItems)

**Cmi Version (using`/cmi version`):** 
https://gyazo.com/1e7ec2c220836786401f188287f7bf9e
(CMI 8.8.0.1)

**Server Type (Spigot/Paperspigot/etc):** 
Tuinity

**Server Version (using `/ver`):** 
git-Tuinity-"09997a6"

**Relevant plugins (Delete if this isn't needed):**
Since someone said it potentially had to do with NBT stuff, MMOITEMS since I'm running ~500 Custom items.

**Comment by Zrips** [comment]
Its relating to items with attached commands to them. Do you have any of those floating in the server? As this only indicates 9 triggers which resulted in some chunk loading in sync. So you might have item with attached command which loads chunk for some reason. More information is needed to determine what exactly caused this or if its even an issue with attached commands or its simply being shown because you have item with heavy command attached to an item

**Comment by Lorenzostuy** [comment]
> Its relating to items with attached commands to them. Do you have any of those floating in the server? As this only indicates 9 triggers which resulted in some chunk loading in sync. So you might have item with attached command which loads chunk for some reason. More information is needed to determine what exactly caused this or if its even an issue with attached commands or its simply being shown because you have item with heavy command attached to an item

Well that makes sense, I was testing the server performance by randomly teleporting various times and that was done through an powertool with fawe/worldedit not entire sure if I removed fawe at that time. So yes I was using an item that executed the /rtp command. So my question now is:  Is there a difference between executing an command myself so I just type in chat "/rtp" or if I attach an command to an sword for example which executes the "/rtp" command.

if that's the case then I was most likely wrong.

**Comment by Zrips** [comment]
Well, depends if it was CMI rt command or another plugin. Attached command will perform attached command to the item, which by itself will report in timings as a lag cause, which is some what correct but at same time isint. It only triggers command, if its a heavy one then it will show in timings that attached command created load on server, which is not really the case, it only triggered command which caused load on server. If you used CMI rt command, then I might need to check that one for possible optimizations.

**Comment by Lorenzostuy** [comment]
It wasn't the CMI random teleport feature it was from an external plugin, how ever this wont be used by other players so can I assume that i'll be safe from this kind of lag that occurred as aforementioned.

**Comment by Zrips** [comment]
It should be just fine, if it triggered heavy command it was a reason why it showed up in timings. For generic usage it lightweight feature and you will not notice its impact on server performance, everything depends on what kind of commands you will be performing with this feature.
