### ISSUE TITLE
selection visualizer - middle mouse click

### ISSUE THREAD

**Issue by Fargus5** [Zrips/CMI#4907]
![image](https://user-images.githubusercontent.com/20026629/104771095-fd729d00-5771-11eb-9458-75b1840e94ff.png)

hello, for those that doesn't have a mouse and so a middle click? how we can modify this?

I'm using a portable pc and middle click doesn't exist.

**Comment by Zrips** [comment]
What type of pc do you have in particular which doesn't have middle mouse click? Now I'm just curious. And to answer to your question, middle mouse click is hard coded and you cant change its behavior. I could change things around to make that possible, but in general this is terribly narrow issue. Maybe just get a mouse with a middle click? It is a useful feature in game in any case.

**Comment by Fargus5** [comment]
Is portable pc with a touchpad...
ok thanks in any way to take time to explain this 👍🏻
