### ISSUE TITLE
Additional permissions for cmi.command.gm.others

### ISSUE THREAD

**Issue by Kapitowa** [Zrips/CMI#4908]
Please add new permissions:
- cmi.command.gm.creative.others
- cmi.command.gm.survival.others
- cmi.command.gm.adventure.others
- cmi.command.gm.spectator.others

**Comment by CloudeLecaw** [comment]
These allready exist

**Comment by Kapitowa** [comment]
cmi.command.gm.others.* don't work

**Comment by CloudeLecaw** [comment]
cmi.command.gm.others.* don't work

it has no effect withoutthe oters!

**Comment by Kapitowa** [comment]
You can check, it's not working, if I need command /gm 0 _nick_ to be blocked.

**Comment by Zrips** [comment]
Some general changes can be applied to get better permission handling when it comes to player game modes. next update
