### ISSUE TITLE
[item] no wok  Please fix it for very many versions

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#491]
[item] no wok 
Please fix it for very many versions

**Cmi Version The latest version
:** 

**Server Type paper:** 

**Server Version 1.12.2:**

**Comment by LogGits** [comment]
Confused. Can we get some context? What is [item] for? is it the command /item?

**Comment by RustyDagger** [comment]
Im guessing they mean [item] in chat and it shows the current item your holding. I didnt know CMI had that.

**Comment by TheWranger** [comment]
Nice description 👍

**Comment by p82183645** [comment]
Cmi does have this feature, added by the author
But it has not worked

WTF error report?
I hate you

**Comment by Gasha666** [comment]
For me its working, i'm on PaperSpigot 1.12.2

try using this

  HoverItems: true
  # Defines regex when replacing item line in chat with players item in hand information. Only works when CMI hover over chat format is enabled
  ItemRegex:
  - (\%item\%)
  - (\[item\])
  - (\%i\%)

**Comment by TheWranger** [comment]
Not sure why you're getting upset over it being marked as an bug report, what did you expect it to be marked as.
Nobody can reproduce your issue so there's nothing Zrips can do unless you supply as with more info.
1. You could perhaps give us your entire chat formatting config in a pastebin
2. Disable other plugins that might be conflicting to CMI to track down the issue

It's impossible for anybody to even reproduce your issue, therefore it's impossible to fix.

**Comment by CloudeLecaw** [comment]
[item] is the placeholder for item in hand. this placeholder is new and was allready reported as not working - mens he is not showing in the Chat when you use it. Also it should be able with this placeholder to hover over the Name to see the data of it (name,lore,atrubutes etc) therefor the Chat and mc mut support hovertextes.

finnaly just to day ist not reported by Zrips in the patchlogs that [item] was fixed so normaly ist not nessesary to report is aggain ;)

**Comment by Zrips** [comment]
For [item] to work you will have to use CMI chat handling and hover over messages feature should be turned on. Its special handling of messages and it cant go throw other chat handling plugin. So in case you are using 3rd party plugin for chat handling with hover over messages, i cant really do anything about that.
