### ISSUE TITLE
Gradients with &x formatting

### ISSUE THREAD

**Issue by Isaiah-labs** [Zrips/CMI#4914]
Hi!

I'm currently using CMI's usermeta to store a color that a player has selected so players are able to choose what chat color, name color, etc. that they have at all times. I'm currently attempting to let players select two gradient colors in the {#RRGGBB>} and {#RRGGBB<} formats, but when those codes are stored in usermeta, they get parsed as {&x&r&r&g&g&b&b>} which then turns into {>} or {<}, resulting in the last two characters "<}" or ">}" to be the selected color. 

Is there anyway we could see gradients applied using the &x formatting as well? Ideally, &x&r&r&g&g&b&b> and &x&r&r&g&g&b&b< should work, but regardless I just am hoping that the usermeta colorcodes get parsed properly.

Thanks!

**Comment by Zrips** [comment]
Can you give actual example in how you set meta data and where you are using them? As of basic testing i can properly colorize players nickname based on user meta set with usermeta command

**Comment by Isaiah-labs** [comment]
After some more testing, it seems to work when I enter the command myself (but I don't want to give regular players usermeta command permission) but when the command is entered through the console, the colors seem to be translated into that &x format rather than staying {#RRGGBB>}.
