### ISSUE TITLE
ClickHoverMessages: true is duplicating chat messages

### ISSUE THREAD

**Issue by Dagrond** [Zrips/CMI#4915]
**Description of issue:**
Option "ClickHoverMessages: true" is duplicating messages on global chat when I try to use other plugin for chat channels (in this case KingdomsX). When I'm entering chat channel from kingdomsX, both CMI global message and KingdomsX channel message is showing up. After changing ClickHoverMessages to false, problem is dissapearing. But I want CMI's hover messages on global chat, and properly working (without hover ofc) channels from KingdomsX

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
  ClickHoverMessages: true

**Cmi Version (using`/cmi version`):** 
 8.8.0.0

**Server Type (Spigot/Paperspigot/etc):** 
Yatopia (paper fork)

**Server Version (using `/ver`):**  
1.16.4

**Relevant plugins (Delete if this isn't needed):** 
KingdomsX

**Comment by Zrips** [comment]
When you have enabled ClickHoverMessages chat message event gets disabled and completely new type of message is being sent to the players. If you have another plugin controlling public chat messages then it might duplicate it. For this you will need better support from KingdomsX with option to disable public message handling from their end. Cant really resolve this issue from my end.

**Comment by Dagrond** [comment]
Yeah, I know that, but I was wonder is this possible for CMI to check if another plugin is cancelling chat event, and if so, cancel CMI's chat message aswell. This would solve that issue.
