### ISSUE TITLE
NetherPortal.PreventCreation bypassing with permission partly not working

### ISSUE THREAD

**Issue by Androkai** [Zrips/CMI#4916]
**Description of issue:**

I have a 1.16.5 (same on 1.16.4) server with latest Paper, CMI and Hyperverse.

On the server I have a main world and an additional set of farm worlds (otherworld, nether, end).
With the changes in Bukkit since Minecraft 1.16.2 that requires you to have nether portal creation enabled in server.properties for the PlayerPortalEvent to be fired I'm using CMI's `NetherPortal.PreventCreation` setting to prevent portal creation in my main world while allowing it via `cmi.netherportalbypass` permission in the farm worlds.

Everything is working fine this way for activating a portal with a lighter. I can see that the permission is checked and the portal is activated. My problem is when entering the portal. CMI seems to deny creation of a portal in the other dimension while "PreventCreation" is enabled. This is also only a problem if no portal exists in the other dimension so far. If there is already an open portal in the other dimension teleport works fine. I also see that there is no permissions check while entering a portal so maybe the bypass option is not implemented for that part. Having "PreventCreation" disabled everything works as expected (but it's also possible to create nether portals in my main world again).

Please note that I use Hyperverse for multiworld support. It allows linking non main world dimensions via a "nether" flag:
```
/hv flag farmworld nether farmworld_nether
/hv flag farmworld_nether nether farmworld
``` 

---

**CONFIG SECTION:**
```yml
NetherPortal:
  # Can prevent nether portal creation entirely. Option to bypass with cmi.netherportalbypass
  PreventCreation: true
```

---

**Cmi Version (using`/cmi version`):** 8.8.0.3

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-Paper-431 (MC: 1.16.5)

**Relevant plugins (Delete if this isn't needed):** [Hyperverse](https://ci.incendo.org/job/Hyperverse/30/artifact/Core/target/Hyperverse-0.10.0-SNAPSHOT.jar)

**Comment by Zrips** [comment]
That feature only controls portal creation it will not do anything while you trying to use one and teleport to another world.

**Comment by Androkai** [comment]
Too bad, I was hoping to at least get a new clue, since the "PreventCreation" option in my setup reproducibly has some effect on subsequent success/failure in portal creation and usage. Unfortunately but understandably, CMI behaves like a black box here.

Thanks anyway for the answer. 👍 I will go back and look for it tonight. I'll probably have to build myself a couple of minimal priority listeners for the respective events and hope that I can get something out of the output.

This problem is really driving me crazy. I will update the ticket afterwards and most likely close it.

**Comment by Androkai** [comment]
I'm sorry, research took a day longer but I have more information now:

I learned that entering a portal will also trigger a `PortalCreateEvent` if no portal exists in the other dimension. With some listeners with different priority on that event I can report that CMI is canceling this `PortalCreateEvent` event if `PreventCreation: true` resulting in no `PlayerTeleportEvent` being called after and in consequence a non functional portal. Activating a portal with a lighter also calls a `PortalCreateEvent` which is not being cancelled and I also see a permission check happening which is missing for the same event while entering a portal.

I conclude that CMI listens for the `PortalCreateEvent` and depending on whether a portal is activated or entered, it ends in a different state where no permission check is happening and the event is being canceled. I therefore ask that you take another look at the problem based on the new information.

**Comment by Zrips** [comment]
Hmmm, yea, this new information is helpful, tho now i need to rethink entire system as PortalCreateEvent doesn't provide actual player who created this portal, so i'm looking around portal for players with flint&steel who might have been creators of this portal. But how we would find who initiated creation of portal if its from another end as portal location can be quite different even if we would convert coordinates. So how would we find correct source portal and correct player who initiated this action, i have no idea. Will have to dig around, maybe there is attached information to the portals where they actually lead which could be used. Who knows.

**Comment by Zrips** [comment]
Well talked to soon... Seams that PortalCreateEvent actually got extra method to get player who initiated portal creation. So i can use that one.

**Comment by Androkai** [comment]
Another solution for this specific case I see is checking for the different `CreateReason` since it should be `OBC_DESTINATION` (old API) or `NETHER_PAIR` (new API) in this case and `FIRE` in the one that should be blocked (Haven't tested if it really is the case through). So if the reason isn't `FIRE` you'll just pass it thru.

**Comment by Zrips** [comment]
Well did some changes relating to this, as i can determine player who initiated portal creation, well atleast in most cases as its still not detecting who did that if it was through dispenser, but for that i can use old method. In any case it seams to be working more accurately now. Tho permission is checked by the player in source world, so this might be some what issue, unless we would add new permission node to limit per world creation which in general could block portal creation into one side but not the other way around. Anyways. Next update.

**Comment by Androkai** [comment]
Thx
