### ISSUE TITLE
Using AFK Attack

### ISSUE THREAD

**Issue by dalandis** [Zrips/CMI#4920]
Using https://www.curseforge.com/minecraft/mc-mods/afk-attack-fabric?__cf_chl_jschl_tk__=860a51435e3c99f9c4664e0bdceca7dcab11a4f0-1610959910-0-AeLM66t4CT5j6bEygduZv46WznaayAG6NP27yfLbzcu2v67-jjbCWAvzL7p5sdSgEc5PbU9c0kpUz-hR7STpijYQQA1Ic1vWn9s6ss1tgcKMUM-aKcb07K3zd6gLxCwWWg9583WtOPEJcrTqYP9n2YmhOzypHIklURYqbFVIQwBWD1HHq5kM4dgFDwnjpCNYltiV9TWL-utxqzxQopV-_LMNNYCV_yMMm_RLUYSPykVCNp28DEryei_BIc8VKedf7F5-Ltt5zTPAAZ61isB6LCZRG8ysCjIw7Ni0J6_KxjSG243AgZXrUXwWJF7FSwFxtOzCSV_8cGm4xDZsCieqzIwnE48eV3lk2IA27vMknZ1zwcFs9neq59jwSbmqW4Nxwgeoe7lqmaFMPTZmNYrGc9Y1PgrrQd1o5WdVbAhW9Cn1 modification does not interrupt the AFK

demonstration - https://www.youtube.com/watch?v=KWjuM7KYhxg&feature=youtu.be

---

**Cmi Version (using`/cmi version`): 8.8.0.2

**Server Type (Spigot/Paperspigot/etc): bungeecord + yatopia

**Server Version (using `/ver`): git-Yatopia-"99e3c5d" (MC: 1.16.4)

**Relevant plugins (Delete if this isn't needed): AdvancedAchievements, AdvancedBan, BungeeTabListPlus, BungeeTeleportManager, Chunkmaster, CMI, CMILib, CMIPaperLib, FastAsyncWorldEdit (WorldEdit), HeadDatabase, LogBlock, LuckPerms, MysqlPlayerDataBridge, NoMobGriefing, PlaceholderAPI, ProtocolLib, SkinsRestorer

**Comment by Zrips** [comment]
Make sure that you have DisableOnInteract. Will add extra check, but as you have specific modded server which is not officially supported and I don't have time to setup your specific environment to test things, it might help or not. We will see with next update.

**Comment by dalandis** [comment]
<img width="325" alt="Снимок экрана 2021-01-18 в 16 01 28" src="https://user-images.githubusercontent.com/15212686/104913041-7eb27580-59a6-11eb-85ac-7936f7e710b7.png">

This is of course true.

The AFK stops correctly for a normal sword swing.
Doesn't work with this modification.

I will definitely check. Thanks for your hard work.

**Comment by dalandis** [comment]
Oh yes. This is not a server mod, it is only a client mod. The server does not support mods, yatopia is a fork of paper.
