### ISSUE TITLE
Custom Recipe Permissions

### ISSUE THREAD

**Issue by w41k3r26** [Zrips/CMI#4922]
The title explains itself.
The idea is to have the permission enabled for the custom recipes to be accessed by the groups, similar to the custom alias.
This might be a bit of work, but should be worth it. I have seen this in action with some outdated custom recipe plugins, would be very neat to have it in CMI.

Thank you! Even if this doesn't make through to a final build, do share your views below :)

**Comment by Zrips** [comment]
Feature requests goes into "discussions" section not "Issues"

**Comment by w41k3r26** [comment]
I am still confused as to why the feature request an option in issues? I'll post this in discussions anyway.
