### ISSUE TITLE
Suggestion: More Enderchest slots based off permission.

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#4923]
Give people more enderchest storage based off permission. 
Example of existing plugin:
https://www.spigotmc.org/resources/custom-enderchest.8868/

 My worry with using another plugin is I use /oi from CMI, And I like being able to click the enderchest, I dont want to have to use another command from another plugin to edit enderchests just to get more slots.

Could be (from other plugin example);
```
cmi.ender.slots.0 - For 9 slots(1 raw) EnderChest size
cmi.ender.slots.1 - For 18 slots(2 raw's) EnderChest size
cmi.ender.slots.2 - For 27 slots(3 raw's) EnderChest size
cmi.ender.slots.3 - For 36 slots(4 raw's) EnderChest size
cmi.ender.slots.4 - For 45 slots(5 raw's) EnderChest size
cmi.ender.slots.5 - For 54 slots(6 raw's) EnderChest size
```

**Comment by Zrips** [comment]
Feature requests goes into "discussions" section not "Issues"

**Comment by TomLewis** [comment]
Whoops and i was the one that asked you to setup discussions! my bad! Ill re-create it there.
