### ISSUE TITLE
Bug with dupe spawners

### ISSUE THREAD

**Issue by ReformedHooper** [Zrips/CMI#4924]
Once the player has not explored the smelter pickaxe in the slimefun and still mines the spawner around so they duplicate .. This error is in cmi as I have now tried silkspawners, mineablespawners and it doesn't happen with these plugins .. Is it possible to fix it somehow?

---

Cmi Version (using`/cmi version`): 8.7.11.1

Server Type (Spigot/Paperspigot/etc): yatopiamc

Server Version (using `/ver`):  1.16.5

**Comment by ReformedHooper** [comment]
As soon as a player starts mining with this pickaxe and has not tested this pickaxe, the spawner is still in place and breaks at the same time ... so it is duplicated.

**Comment by ReformedHooper** [comment]
https://user-images.githubusercontent.com/62069758/104953378-96015b00-59c6-11eb-98ed-1452e3fc04a1.mp4

**Comment by CloudeLecaw** [comment]
First of all you ma should try cmi 8.8.0.3..
Does the issue acxur here too?

**Comment by ReformedHooper** [comment]
Yes, I tried the latest version on localhost and need my config?

**Comment by CloudeLecaw** [comment]
No just the spawner related part

**Comment by ReformedHooper** [comment]
Spawners:
  # If you experiencing issues with spawner handling, set this to true to avoid any spawner manipulations from CMI side
  # This will disable features like, spawner placement, spawner drops, spawner charges and so on
  FullDisable: false
  Break:
    # Enable or disable spawner handler for spawner break
    # If enabled player will get spawner if using silktouch pickaxe and have cmi.dropspawner permission node
    # If player has cmi.dropspawner.nosilk permission node, player is not required to use silk touch pickaxe to get droped spawner
    Enabled: false
    # If set to true, player will need to have particular permission node to break and get particular spawner.
    # In example: player should have cmi.dropspawner.pig to break pig spawner and get it dropped, or cmi.dropspawner.zombie to get zombie spawner
    RequiresExactPermission: false
    # When set to false, exp will not be dropped from broken spawner independent if spawner it self is being dropped
    # When set to true exp will be dropped only if spawner is not
    DropExp: false
    # Minimal silktouch level required to get spawner back
    SilkTouchLevel: 1
    # Number in percentage from 0 up to 100 for a spawner to be dropped when you break one
    BaseDropChance: 100
  Place:
    # Enable or disable spawner handler for spawner place
    # If enabled player will place spawner depending from what it is by its type
    # If disabled then spawner will be placed in normal way and it will allow other plugins to handle its placement
    Enabled: true
    # If set to true, player will need to have appropriate permission node to place spawner by its type
    RequiresPermission: false
    # RequiresPermission should be set to true for this to work. If set to true, player will need to have particular permission node to place particular spawner.
    # In example: player should have cmi.placespawner.pig to place pig spawner, or cmi.placespawner.zombie to place zombie spawner
    # If set to false, then player will need to have basic cmi.placespawner permission to place any type of spawner
    RequiresExactPermission: false
  Interact:
    # When set to true, players trying to change spawner with monster egg will require appropriate permission node
    # In example: player should have cmi.egginteract.pig to change spawner into pig, or cmi.egginteract.zombie to change into zombie spawner
    EggRequiresPermission: true
  # If set to true, spawners will have chance to be dropped when destroying with tnt
  TnTExplosionDrop:
    use: false
    # Chance in percentage for spawner to drop
    Chance: 30
  # If set to true, spawners will have chance to be dropped when destroyed by creeper
  CreeperExplosionDrop:
    use: false
    Chance: 30
    
 Now I have it turned off so that spawners don't duplicate.

**Comment by Zrips** [comment]
Well... As of some investigation, slimefun dev seams to use BlockBreakEvent on Monitor level and then cancel it if conditions is not meet, which is not go as Monitor level listener should only monitor outcome and not change it. Will try to fix this from my end, but in general this needs to be addressed by slimefun dev and event priority should be changed from MONITOR to HIGHEST.
