### ISSUE TITLE
Equation & EquationInt placeholders not working

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#4927]
**Description of issue:**
the placeholders %cmi_equation_[equation]% and %cmi_equationint_[equation]% do not work on the latest version.
![asdasdasd](https://user-images.githubusercontent.com/29175884/105089753-7127e900-5a95-11eb-9020-d607c6e76999.png)

---

**Cmi Version (using`/cmi version`):** 8.8.0.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.16.4

**Comment by Zrips** [comment]
Do you have CMILib installed?

**Comment by DrakePork** [comment]
yes

**Comment by Zrips** [comment]
Confirmed. Should be back in working order with next update.
