### ISSUE TITLE
alias instead of main command is pasted on /cmi info

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4928]
we disabled the alias tppos on our serer in alias.yml

but not we cant really quick use the teleports of /cmi info anymore because the aloas tppos is pasted to chat instead of /cmi tppos

![Snag_8de33ef](https://user-images.githubusercontent.com/12080017/105110156-48681980-5abe-11eb-853e-d96d73a7c25f.png)

i have this can be changed to /cmi tppos

**Comment by Zrips** [comment]
Next update
