### ISSUE TITLE
Teleport Issues and feature

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#493]
Hi I had notice that even when there is a place and I teleport player even if there is space for player to teleport it sends him to the top. So for example player is in mine and he mines 2 blocks high and player teleport other player to him and it teleport to the top instead to him. 

Also maybe add so if teleport player is in gamemode 3 it ignores the save location as if he is in gamemode 3 nothing will really happen to that player.

**Cmi Version (using`/cmi version`):** 
7.8.3.0

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.12.2

**Comment by CloudeLecaw** [comment]
haveu tried it with this Setting?
  Teleport:
    # When true then while checking for safe location, we will try to determin it goind down and if it fails, then up from target location
    # When set to false, then first of all location above target location will be checked, then down
    SafeLocationDownThenUp: true

**Comment by arturek1666** [comment]
Not looked at that thx for info. Did not see that before. xD

**Comment by arturek1666** [comment]
However when I teleport to player with gamemode 3 and i have gamemode 3 when teleport it teleports not to that player but somewhere else. For me if it's gamemode 3 it should teleport to that player anyway if it's unsafe.

**Comment by CloudeLecaw** [comment]
hm definaly yes.
My sever has not so much Players so i mostly can use the gm3 hotbar Buttons to teleport to them.

**Comment by LogGits** [comment]
@arturek1666 are you still having the teleport issue with it teleporting you above?
Also @Zrips this would be a good idea to make safeTeleport ignore `Spectator` and `Creative` modes 👍

**Comment by arturek1666** [comment]
The  teleport issue is fixed when changed the settings so yea that part is fixed :).

**Comment by Zrips** [comment]
Next update will teleport players with gm 1 and gm 3 to exact target location.
