### ISSUE TITLE
velocity proxy support

### ISSUE THREAD

**Issue by BearLeonLight** [Zrips/CMI#4930]
Velocity agent does not support Bukkit API, so I can’t install CMIB on it and will get an error, but I currently use Velocity instead of BungeeCord.

**Comment by CloudeLecaw** [comment]
Offically there is just a support for Spigot

We could be happy that Zrips also supports a fork called PaperMC.

many others asked allready for different forks support. 
Hopefully the answer will be the same as allways..
no;)

**Comment by BearLeonLight** [comment]
Ok
Because he only does not support Bukkit code.
Can I try to compile the original file with you

**Comment by CloudeLecaw** [comment]
Your not allowed to decompile CMI by your own. 
This is not allowed for all premium resources
Its also not allowed to create "own forks" of a premium souce

**Comment by BearLeonLight** [comment]
I know that I am asking here, thank you for your answer, I have to give up using velocity

**Comment by Zrips** [comment]
CMI currently based on BungeeCord type system which by itself only provides some small changes.

**Comment by StrangeOne101** [comment]
It may be worth revisiting in future. PaperMC is discontinuing their fork of Bungee (Waterfall) and is now only developing Velocity. 

Velocity still has the same plugin channels Bungee has. So it'd still be possible to port to Velocity. But Waterfall is only getting a few updates for later Minecraft version before being dropped completely now
