### ISSUE TITLE
Unhandled exception executing command 'cmi' in plugin CMI v8.8.0.3

### ISSUE THREAD

**Issue by Fargus5** [Zrips/CMI#4931]
Good Morning,

I found 2 errors in console

https://log.mtxserv.com/bRzDs9h#L5174

https://log.mtxserv.com/bRzDs9h#L4408

If you know what could be the problem related to CMI ?

Thanks in advance

**Comment by CloudeLecaw** [comment]
1. your GuiPlus plugin seems to have a Problem with cmi. You should inform the GuuiPlus dev about.
Its also possible you defined a wrong GuiPlus GUI with cmi content in it.
2.  Your plugin MYcommand seems not tonsupport cmis speziales commands. Its also possible aggain here that you defined a wrong syntax for the commamd that Mycommands tried to execute.
Also here you should inform the MyCommands ddev if you can agree that the error is.not from your configuration site.

**Comment by Zrips** [comment]
Seams to be caused by other plugins, mainly by your MyCommands plugin passing over wrong CommandSender type, I can fix first error from my end, but second one isint really related to CMI.
