### ISSUE TITLE
Order the players in the tablist and scoreboard

### ISSUE THREAD

**Issue by Gayytis** [Zrips/CMI#4933]
Hi! I think it would be really handy to have something in the tablist.yml that would allow you to order the players according to their rank.
For example : 
I'm an administrator and a player is a default rank that we'll call Builder. He will be before the administrator rather than after when his rank is lower.
Either that, or put a permission like for example cmi.tablist.order.1/2/3, and so on.

Also, it would be nice to be able to put a scoreboard compatible with PlaceholderAPI, a bit like the premium version of the "TAB" plugin by NEZNAMY which allows it.
These additions would allow me to have only CMI for all that and it would really be a +

Thank you !

**Comment by CloudeLecaw** [comment]
Long wished mybay most often asked for (10 times now?). Well may it comes now after 3 years of asking for it?
Well.. Hope never dies :P

**Comment by Gayytis** [comment]
Hope it will be added soon

**Comment by Zrips** [comment]
This should be in discussions section and it was already asked quite few times.
