### ISSUE TITLE
Anchor not discharge

### ISSUE THREAD

**Issue by alan67160** [Zrips/CMI#4935]
**Description of issue:**
---

https://minecraft.gamepedia.com/Respawn_Anchor
as Minecraft vanilla version each respawning will use up one charge, even if it's done by another player but on CMI respawn system does not use any charge

---

**Cmi Version (using`/cmi version`):** 

```
CMI version: 8.8.0.3 BungeeCord  MySQL-> 8.8.0.4
Server: 1.16.5 1.16.5-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled 
Modules -> 50 enabled 4 disabled: armorstand, ranks, votifier, holograms
```

**Server Type (Spigot/Paperspigot/etc):** 

```
Paperspigot fork (SSSpigot)
```

**Server Version (using `/ver`):** 

```
This server is running SSSpigot version SSSpigot-1.16.5-20210119-5b9c6cb (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```

**Comment by Zrips** [comment]
Should be resolved with next update
