### ISSUE TITLE
☯ [Bugs & Suggestions] ☯

### ISSUE THREAD

**Issue by Gasha666** [Zrips/CMI#494]
I have few suggestions and bugs..

Timer for actionbar, maybe for title/subtitle message too?
Timer for /cmi point (how long particle will last)

BUG with CMI IC
example i put 10 itemframes and i am not able to set IC on them, i am only able to set on two out of 10 item frames, i tried for 3 hours, every time i only was able to set IC on two out of 10-15 itemframes, when i press on others its saying that entity is already IC  but its not, i can see the list of blocks/entites what have interactive command, only showing two

Not able to open links when someone sending links using /cmi mail
Also same thing is when someone sending links on /cmi helpop and staff chat (won't open links)

Fix for Scan?
i'm not sure if /cmi scan work correctly or doesn't work? i used it in past it was working, now i place chest in front of me with item in it, and had same item in my inventory (paper- 339) and i tried scanning ID but didn't found any item, i tried lore, itemname everything but didn't succeed in item-search(scan)

Little bit better/more advanced hovering system (better explanation at least)
I would love to start using hovering system because its so cool, but i don't know how to use it correctly, i tried many times didn't succeed

For /toast you explained that you cannot remove that first page or change title,which is moyang thing.. can you maybe make faster switch to second page (that will avoid showing that hard code non-translatable title text)

on second page there is no hard-coded titles

it would be better if particles from /cmi effects are optional, i'm talking about NightVision,Invisibility
i'm using 24/7 NightVision on server and there are those bubbles from effect, at the begging they were okay, but after monthes and monthes seeing those bubbles its become pretty annoying

It would be very useful if there is cool command to turn auto run for player or auto jump, or multiple jumps
https://www.spigotmc.org/resources/inifinitejump-double-jump-triple-jump-infinite-jump.51522/

CombatLog feature (execute certain commands if player left during combat against player)
when spawning mob with /cmi spawnmob ability for custom mobs to drop certain items or (execute certain commands)

- ability to edit torso on armor stand editing

- ability to keep certain chest open (visually)

if attach command is set !left! or !right! that means that only needs to work with that mouse key, because
pressing second key will use limited-use and do nothing

there is bug not updating player name even if he change multiple times or even using /tablistupdate, not updating until he say something in chat..

example, i change player's rank and type /cmi updatetablist still showing same, i tried /cmi reload, still showing same, tried many other things,even if he goes AFK, neither then its chaning, nothing update his name until he start talking in chat..

there is bug when player is riding you and he leaves server
i got message that i cannot enter any message in chat, it last whole time no matter what i try to do, until i relog

add warn system (5 warns = more serious punish command, example perm ban)

80% people using LiteBans plugin, but recently CMI got all punish commands, even better, just missing Warn system, if you add nice warn system then people will be able to stop using LiteBans plugin and only use CMI

ability to use more then 1 item when creating custom recipe example i would like to add few amount of certain item to be needed
for custom recipe, now i can only set amount 1, if i put stack, it will only accept it as 1..i want to accept it as amount i actually set

maybe ability to block/remove certain recipes

maybe optional message or placeholder to show player on join example
"You was on server last time before 46 days (maybe date?,but its not important)" 

Ability for skins to use previous skin (i didn't meant on original player's skin) i think just on previous skin that player had, 
Example player purchased some skin ingame and i have system for COPS,GANGS,JOBS where i created that when player is cop and go on duty got cop skin, after he goes off duty, he still have that cop skin, if there command to set previous skin it would be useful (it doesn't need to save multiple previous skins, just one last previous skin, then i'll be able to return players previous skin they had)
This could be used for many things

Ability to use -s (silent) in /cmi back and /cmi dback [playerName] now always giving them message and i'm using back command for many things, please add ability to not send message to user when teleporting him back

add /cmi lay command when you added sit you saw how many people were happy, lay is even more FUN

anti-xray alert, since there is block tracking and everything, it could be easly used to alert owners if player is having more diamond ore breaked then he should, that would be ultra useful

i know this is for CMI section, but you are also owner of Mob Farm Manager can you fix in MFM when player is not allowed to place armor stand to not take his item, to just inform him that he is not able, but he shouldn't lost item if he didn't place it, not making much sence to lose item if he wasn't able to place it, most of players when they are not able to place press 10 times more, and then they lost items and then they asking for them later

and add some limitation to bigger range example to effect mobs on larger area (example whole world) or bigger areas, i don't know how i can now set for example that in area of 100 is able to be only 10 mobs

now i set all limitaiton to 5 mobs, but its only per chunk, i tried setting use groupedchunks on so it check for larger area, but its still not what i wanted i want example

i would like to have in area of 100 =  only 10 mobs
and in whole world to be example max 200 mobs (without counting exluded) (now i'm getting few thousands of mobs if there is thousand chunks loaded) example i set only 5 pigs per chunk but players load 1000 chunks and then there is thousands of pigs

maybe adding something like

  worlds: all
  distance: 100
  max-amount: 10

would be useful or something more advanced
and ability to bypass limitation on placing Armor Stands, i want limitation for players but not for me as OP

Please try to add at least some of those, i'll be very thankful and i'm pretty sure everyone would be pretty happy, i'm sure we could make group donation amd get you some extra money so you be able to spend more hours on improving CMI

**Comment by TheWranger** [comment]
If /toast is going to be sped up, that should be configurable.

**Comment by Zrips** [comment]
@Gasha666 
What exactly you performed when looking for item and where exactly that item was in. Chest? Trapped Chest? It does work when i did some testing and finds items correctly by id or from hand. So some extra debugging is needed.

**Comment by Zrips** [comment]
@Gasha666 
What you mean about that "hovering" thingy? What exactly are you talking about?

**Comment by Zrips** [comment]
@Gasha666 
For toast, its terribly coded from Mojang side and its terribly limited what you can do with it. You can only change icon, change type of top text and add text to be shown after that top text which by itself will be automatically transferred to second page if its too long... That's it... Everything else is hardcoded client side.

**Comment by Zrips** [comment]
@Gasha666 
Name updates are limits to certain actions as it can get quite heavy on server if it would be performed constantly.

**Comment by Zrips** [comment]
@Gasha666 
I'm still lost about which "Hovering" system are you talking about? Chat hover messages?

**Comment by Gasha666** [comment]
Okay sorry, Yes i'm talking about Chat hover messages

Yes in config there is
information when hovering over it (PlaceHOlderAPI supported) and can be clicked for quick reply option
  ClickHoverMessages: true

where i'm able to use that CMI hover system? i saw that i'm able to use that hover system in /cmi ctext but not understand it how to use it completely yet

**Comment by Zrips** [comment]
@Gasha666 
Its for public, private, staff or op help chat so when you hover over players message you can see some info, like sent time (by default). You can add additional information, maybe rank, balance or anything else. Its supports placeholders, so you can add anything you want.
You can find appropriate locale line under Chat->publicHover

**Comment by Zrips** [comment]
@Gasha666 
For MFM, there is a reason why its hard limited to 5 chunks range if i'm not mistaken. It can be quite heavy on server to check hundreds of chunks and group up all entities and count how many of them there are on each check.

**Comment by Gasha666** [comment]
@Zrips 

1. Yeah i know about that hover in lang file, i'm using it since the begging..i'm not talking about that i'm talking about this 

<T>Text</T><H>Hovertext</H><C>command</C><SC>Suggested text</SC>

<CC>
<CCI>
<URL>

i don't know where i am able to use that

2. Is it okay if i use EntitySpawn and AutoClean Chunk radius: 3-4 for both
now i'm using 2..will increasing it to 3-4 be beneficial for performance? (i know it will clean mob but it will check chunk) what is your suggestion


i'm trying to find which will be most beneficial for performance, my tps is always 20 so its hard to say which one will work better for performance

**Comment by Zrips** [comment]
@Gasha666 
1. There is wiki for custom text thing. https://www.spigotmc.org/wiki/cmi-custom-text/ atleast this is how i named that feature and those things are made specifically for it.
2. In general players visit chunks where mobs spawn. In example mob spawner has 16 blocks activation range, so you need to be 1 chunk away from it to activate, so in general 2 chunk range should be enough. Increasing chunk range, increases amount of chunks we have to cheack each time. 1 chunk radius is 1 chunk only, 2 is 9, 3 is 25, 4 is 49 and so on.
