### ISSUE TITLE
killall radius seems to be broken in commandblocks..

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4942]
we tried this command in a commandblock
`killall -monsters spider -r:30`

Effekt: All spiders from all loaded chunks are deleted

we also tried
killall -monsters spider 30.... same effekt

so i assume this radius featrue is broken in last cmi version
![Snag_40c62d1](https://user-images.githubusercontent.com/12080017/105270076-6ce2f500-5b95-11eb-9a23-40cf81e0abd8.png)

`>.... [03:00:59 INFO]: ingegesammt getötet: 35 (Spider: 35)
`

**Comment by Zrips** [comment]
Should be fixed with next build
