### ISSUE TITLE
/nameplate don't parse placeholders

### ISSUE THREAD

**Issue by Dagrond** [Zrips/CMI#4944]
command /nameplate is not parsing placeholders when run from game or console. F.e. /cmi nameplate -pref:%cmi_user_ping% will not be parsed and nameplate will look like: %cmi user ping%Zrips.
BUT
running exactly the same command from eventCommands.yml, placeholder will parse and nameplate will look like: 53Zrips.

**Comment by Zrips** [comment]
Its due to the "issue" that _ is used to indicate empty space, if you want for this placeholder to work simply use double _ like **/cmi nameplate -pref:%cmi__user__ping%** which will convert into correct placeholder format.
