### ISSUE TITLE
EquationInt showing 0 for all placeholders

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#4948]
**Description of issue:**
%cmi_equationint_[equation]% and %cmi_equation_[equation]% work fine if the equation is 5+5, however if the equation is for example %cmi_equationint_{cmi_user_maxperm_cmi.command.sethome_1}+1%, then it will always show 1 instead of the actual number, or %cmi_equationint_{cmi_random_10_100}+10% will always show 10 as the placeholder isnt being registered and is just put to 0.

---

**Cmi Version (using`/cmi version`):** 8.8.0.5

**Server Type (Spigot/Paperspigot/etc):** Paper(337)

**Server Version (using `/ver`):** 1.16.4

**Relevant plugins (Delete if this isn't needed):** CMILib

**Comment by Zrips** [comment]
Yea, broken check for placeholders inside placeholders. Seams to be fixed now. Check out next version and let me know if this is still causing any issues for you.
