### ISSUE TITLE
Enchantement Formattings

### ISSUE THREAD

**Issue by Fargus5** [Zrips/CMI#4954]
Hello, could you add something that fixes the high-level enchantment formatting of enchantments in minecraft. From Efficiency enchantment.level.100 to Efficiency 100 ?

**Comment by Zrips** [comment]
This is client sided issue as there are nothing above level 10 to be shown properly. Without adding extra lore line and pretend that its enchant level one while hiding original one we cant do anything about it. You might make a ticket at Mojang's site as they could implement simple fix for it with next update
