### ISSUE TITLE
Analytics Annual Join

### ISSUE THREAD

**Issue by RedAlphard** [Zrips/CMI#4957]
Hello everyone,
Cmi records the first entry of each player and the game time that can be viewed using the command cmi info and cmi cplaytime, Now these data could be grouped in some way in order to check the monthly income without checking every single one player when did he join? maybe with a GUI like cplaytime? and then it would be interesting to know at what times the players play with a cplaytime of all the players grouped into one so as to have an estimate of the period and time of greatest turnout? CMI records this data and I would like to understand if it can somehow be grouped and averaged.

**Comment by Zrips** [comment]
cplaytime was  more or less just fun experiment to have some more accurate tracking when player was only and for how long. Its not really used anywhere else at this point. Sorting all that data to get some most active data could be a thing, tho checking entire database and sort all of that into specific things could be some what heavy task. Will keep that in mind.
And just FYI this is wrong section, this section only for issue reports, questions like that should be going into discussions section.
