### ISSUE TITLE
No movement individual Warps

### ISSUE THREAD

**Issue by Fiks75** [Zrips/CMI#496]
I put the warp /setwarp pvp. The other player also set the warp /setwarp pvp. As a result, my warp pvp went to him.
Do so that the player who placed his warp was unavailable for movement or removal by other players.

CMI plugin version: 7.8.3.0
Server version: Spigot 1.12.2-R0.1-SNAPSHOT
Vault version: 1.5.6-b49
CraftBukkit version git-Spigot-2086bb0-8cc5a7e

**Comment by CloudeLecaw** [comment]
you both set a warp called /setwarp PVP?...normaly creating warps with same name is not allowed and should throw the meassage that this warp allready exists...

**Comment by Zrips** [comment]
cmi.command.warp.redefine permission node is required to redefine existing warps
