### ISSUE TITLE
About disableenchant

### ISSUE THREAD

**Issue by abc605521864** [Zrips/CMI#497]
**Description of issue or feature request:**

Forbidden enchantments are only hidden, not actually deleted
It is not valid to disable enchantment when an item is in a chest or on the ground
enchant are not deleted but hidden

**Cmi Version (using`/cmi version`):7.8.3.0

**Server Type (Spigot/Paperspigot/etc):Spigot

**Server Version (using `/ver`):Spigot 1.12.2-R0.1-SNAPSHOT

**Comment by TheWranger** [comment]
Item attributes can't be deleted, this is a Minecraft thing.

**Comment by abc605521864** [comment]
I changed it, is it hidden enchant rather than properties

**Comment by CloudeLecaw** [comment]
normaly Players cant see the hidden enchants - so even if they find an item with the disabled enchantment on it, normaly they would throw it away.
Also i noticed when for example "Mending" is hidden..have u tried an item with it? you would see u will not have the mending effect anymore. Dont know if this counts for all disabled  enchantments...

**Comment by abc605521864** [comment]
The disabled enchant is hidden when the item is in the chest, but it still works

**Comment by CloudeLecaw** [comment]
Bestway to prove this may would be a disabled mending or silktouch.

example: if silktouch is disabled and not seen on the item, then normaly u should not be able to mine
Stone without getting cobble….. also the silktouch should not been shown. if it is shown on an item in a chest it should get "hidden" latestly after u try to use it ;)

**Comment by abc605521864** [comment]
I have recorded a video, please view
https://youtu.be/AeJdD3u8xxU

**Comment by Zrips** [comment]
@abc605521864 
Do appropriate server restart after disabling it or atleast relog, as it could take some time to update items and if you want it to be instant and you will be enabling/disabling enchants, that is another talk and additional things needs to be added.

**Comment by abc605521864** [comment]
@Zrips 
Disable enchants and restart the server, but problems persist

**Comment by Zrips** [comment]
Will add extra method to remove enchant entries from items when player closes inventory. As it seems to keep some enchants even tho they are disabled.

**Comment by blek-id** [comment]
Sorry for bringing this up. Tools that already has an enchantment on it, for example mending when found via fishing or end city or a treasure chest will still have mending for some reason. It didn't show but when they get exp the item repairs itself
