### ISSUE TITLE
Failed to start and throws the server

### ISSUE THREAD

**Issue by koyere** [Zrips/CMI#4972]
**Description of issue:**
I installed the latest version and it gave me this error and the server does not work.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
##https://pastebin.com/u8JKH1ng
 ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
CMI v8.8.0.6

**Server Type (Spigot/Paperspigot/etc):** 
Paper version git-Paper-416 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Server Version (using `/ver`):** 
Paper version git-Paper-416 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
As first lines indicate, failed connection with database, you might check your configurations or simply use SqLite for simplicity if you don't really need some external database.
