### ISSUE TITLE
Custom Death Message

### ISSUE THREAD

**Issue by hamcoremusic** [Zrips/CMI#4976]
Hello!

I am trying to customize the death message but I can't find how to do it in the locale or the config. Is this possible in CMI?

Thanks!

**Comment by CloudeLecaw** [comment]
U cant, there is no custom deathmessages in cmi

**Comment by hamcoremusic** [comment]
Ah okay! Thank you anyway :) Would love to see it available soon,

**Comment by Zrips** [comment]
When we will move to CMILib we can start talking about new features like that

**Comment by gerardvanschip** [comment]
Hey @Zrips your June 2021 version of CMI has a deathmessages config file but it seems to ignore whatever is in there. That a bug or?

**Comment by Zrips** [comment]
Its a bug that you have those messages. Feature is not done yet and in later versions those are no longer generated until feature is completely finished.

**Comment by gerardvanschip** [comment]
That explains, will stop hitting my head on my desk 😉

Thanks for the instant reply, appreciate it.

**Comment by CloudeLecaw** [comment]
It was not implemeted
 But hey u can start with Translation and writing lines allready like a pre-work so its done when it is added :D

**Comment by Zrips** [comment]
The fact that its not done yet i could result in path changes which could result in reset, so i would not be in such hurry to start translating them or adding new lines as they might get removed. Well, if you do, keep a copy of the file.
