### ISSUE TITLE
Money can reach over 

### ISSUE THREAD

**Issue by flofydech** [Zrips/CMI#4979]
Hi, im trying to set a huge amount of money to my player. But when i restart CMI will set the money to 92.233.720.368.547.760 . I think the plugin don't allowed to reach this number.

######################
No error in log
######################
    CONFIG :
Economy:
  # Enable or disable CMI economy in general
  # In case CMIInjector is present, then this will be set to true automatically.
  # Attention! For economy to work properly with other plugins you will need ether an injector or recompiled Vault version. 
  # You can find both option at top of plugins page
  # ATTENTION! If you disabled CMI economy while server was running, you will need to perform full server restart for this to take correct effect and avoid any issues while getting players balances
  Enabled: true
  # Determines if player needs to confirm money payment by clicking on chat message
  Confirmation: false
  # Set to true if you want to log money transfers between players
  LogEnabled: false
  log:
    Unknown: true
    Transfer: true
  # Determines max amount of cheque player can create
  # Set it to 0 to remove limit
  MaxChequeValue: 0
  PaymentWithShorts:
    # When set to true players will be able to make payments by using short amount formats like 10k which results into 10000 and similar
    # In addition 10.2k will result into 10200
    Allow: false
    # List of suffixes we should accept and into what amount it results into
    # Only one letter is acceptable when defining suffix
    values:
    - k-1000
    - m-1000000
    - b-1000000000
    - t-1000000000000
    - q-1000000000000000
  BalTop:
    # List of players to exclude from baltop list
    Exclude:
    - Notch
    # When enabled baltop list will show short money values, like 12.5M instead of 12501234
    DisplayWithShorts: false
    # List of names to exclude from baltop
    # Can be used to filter out towny towns
    ExcludeStartingWith:
    - town_
    - town-
    - towny_
    - towny-
    # When set to true some fake accounts will be included into baltop list
    # This should include some previously marked accounts as fake which have been created for town usage or similar things
    IncludeFakes: false
  Global:
    # Starting amount of money players will have
    StartingAmount: 0.0
    # Minimal amount, can go into negative if needed
    MinimalAmount: 0.0
    # Maximal amount of money player can have. Set to -1 to disable this limit
    MaximumAmount: 1.0E45
    # Defines amount until player can send to another player
    # This can prevent annoying spam some players would want to create by sending tiny amounts of money
    MinimalPay: 0.5
    # Defines if you want to allow payments with fractions
    # if this is disabled then payments will be limited to whole numbers and in case player provides number with fraction we will round number down
    Fractions: false
    # Currency symbol to be used when showing balance or similar
    CurrencySymbol: ⛁
    # Format used for displaying money
    MoneyFormat: '###,###'
    # Converts long numbers to short ones, like 12305122 to 12.3m
    UseShortNumbers: false
    # Suffixes for short numbers
    ShortNumbersSuffixes:
    - ''
    - k
    - m
    - b
    - t
    - q
    # Replaces to western format where decimals are separated by , and thousands by . In example 1,000,000.00 changes to 1.000.000,00
    SwitchPlaces: true
    # Placing of currency symbol
    Placing: '[money] [symbol]'
#######################################
Version of cmi : Cmi 8.8.0.5
#######################################
Server version : Paper 1.12.2
#######################################
./ver : https://i.imgur.com/hlUyaH0.png
#######################################

**Comment by Zrips** [comment]
This is basic limitation when it comes to some internal optimizations. You should avoid numbers like that in general as quite few plugins might break due to unusual values over generic 9,223,372,036,854,775,807 which is max value for Long type number.
