### ISSUE TITLE
[Request] Playercollision config or -s

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#498]
We have this command:

/cmi playercollision (playerName) [true/false]

is it possible to create a config for the Default for this? or a -s Option so we can
use this in the eventcommands? :)

Finally it should be a suitable way to set it up by Default
so a config or -s Options would be the best way for it (like -s the command on firstjoin for example)

**Comment by Zrips** [comment]
You can use -s, its just missing from variable list.
