### ISSUE TITLE
Combat section - way to reverse allowed commands to disallowed

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4982]
Hi, please I want to suggest way to reverse the allowed commands list to disallowed commands. Cause then players are complaining that I didn't list all useful commands, and there are bunch of normal commands that should work. There are only few that I want to disallow to players and will be much easier than list all combinations of commands which could be allowed. So way to make it as blacklist will help more. Thanks

**Comment by Zrips** [comment]
Next update
