### ISSUE TITLE
I want to completely disable IP logging

### ISSUE THREAD

**Issue by Milo161** [Zrips/CMI#4984]
I am setting  "Record: false" under the IP section of the config.yml, however /cmi info still logs IPs. I'm trying to disable ip logging completely, as I have a different plugin that handles IPs. This method doesn't seem to be working, how can I disable any sort of ip logging in a database of this plugin?

---

Cmi Version: 8.8.0.7

Server Type: Paperspigot 

Server Version: Paper-434 1.16.5

**Comment by Zrips** [comment]
Will be resolved with next update
