### ISSUE TITLE
Server uptime placeholder?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4986]
Hi Zrips, what about adding server uptime placeholder that could be also formatted to just hours, seconds, minutes etc.? Wanna use it in check and server_uptime from PAPI shows minutes and seconds and I can't use it for comparing :/ Something similar like is in /lag command, but also with way to show just hours, like server_uptime_hours, etc.

**Comment by CloudeLecaw** [comment]
You can use the formatted one too?

**Comment by bobhenl** [comment]
Which one? And how can I used formatted one in a check?

**Comment by bobhenl** [comment]
New update almost solved it, I just need one value to use it in check command, so ideally for ex. just seconds or minutes, like %cmi_server_uptime_seconds% or something like this to allow us compare it and use in schedules & custom alias.

**Comment by Zrips** [comment]
Will add, next update
