### ISSUE TITLE
Something similar to [randomPlayer] but way to don't repeat in one cmd?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4989]
Hi, what about a little enhancement for [randomPlayer] that will allow us to don't repeat same players in one command when it's used multiple times there in command (multiple lines)? Something like urandomPlayer -> unique random player, similar to unique cooldown that was added few updates earlier? Or another way to do this?

btw i've now noticed that [randomPlayer] doesn't work in customalias, so rather placeholder cmi_random_player_name like cmi_random_unique_player_name

**Comment by Zrips** [comment]
[randomPlayer] variable is for schedules specifically so for specialized commands you do need to use placeholder. What i can do is to add %cmi_lastrandom_player_name% which would output previously generated random player name, while %cmi_random_player_name% generates unique player name which can be same

**Comment by bobhenl** [comment]
Yeah this would be great. And with new cmi random player name the lastrandom get overidden, right? This is super idea, will be glad for addition, it will help in custom alias.

But btw may you could add way to define own variable there too
