### ISSUE TITLE
Teleport API request

### ISSUE THREAD

**Issue by iaxedu** [Zrips/CMI#499]
Hello, we are requesting two separate teleportation events.

TpRequestEvent: Fires when a user sends a teleport request to another user and before that user receives the request (/tpa, /tpahere)
- Must be cancellable.
- Chat messages for this should only appear if the event is not cancelled.
- Must be able to distinguish between different types of teleportation requests (preferrably through the already available TpAction enum, like TpAction.tpa, TpAction.tpahere, etc).

TpEvent: Fires right before a player teleports via a teleportation command (/spawn, /home, /tpa, etc)
- Should have the exact same features as PlayerTeleportEvent plus:
- Must be able to distinguish between different types of teleportation requests (preferrably through the already available TpAction enum, like TpAction.spawn, TpAction.home, TpAction.tpa, etc).

I hope you could add these :)

**Comment by LogGits** [comment]
Well `TpRequestEvent` would be unnecessary as it could probably be put in a `CMITeleportEvent` as an enum. Regardless, great idea 👍

**Comment by short1der** [comment]
Any news on this? This feature would be very helpful?

**Comment by Zrips** [comment]
Working on it

**Comment by Zrips** [comment]
Next update should contain what you wanted.
