### ISSUE TITLE
/nick &x invisible nick

### ISSUE THREAD

**Issue by iBuseWinner** [Zrips/CMI#4996]
**Description of issue:**
1) Write something in the chat
2) Use /nick &x
3) Write another message
4) Use /nick off
5) Again write message
![image](https://user-images.githubusercontent.com/44753872/106186945-07ef5680-61b6-11eb-9605-8d75d54da536.png)

---

**Cmi Version (using`/cmi version`):** 
8.7.12.4 BungeeCord

**Server Type (Spigot/Paperspigot/etc):** 
Yatopia

**Server Version (using `/ver`):** 
git-Yatopia-10 (MC: 1.16.5)

**Comment by Zrips** [comment]
Will address this one, tho this is due to player having permission node for cmi.command.nick.bypass.length but will make extra check for empty nicknames, just in case

**Comment by iBuseWinner** [comment]
Players already have cmi.command.nick.bypass.length set to false in LuckPerms, but still can use this magic.
Also, /nick &x&x&x allows to set invisible name too.
