### ISSUE TITLE
DAMAGED

### ISSUE THREAD

**Issue by Lorenzostuy** [Zrips/CMI#4997]
**Description of issue:**
Whenever someone is hit the message DAMAGED occurs in the console.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[21:40:50 INFO]: DAMAGED
[21:40:51 INFO]: DAMAGED
[21:40:51 INFO]: DAMAGED
[21:40:51 INFO]: DAMAGED
[21:40:51 INFO]: DAMAGED
[21:40:51 INFO]: DAMAGED
```

---

**Cmi Version (using`/cmi version`):** 
CMI 8.8.0.8

**Server Type (Spigot/Paperspigot/etc):** 
Purpur

**Server Version (using `/ver`):** 
git-purpur-960

**Comment by Zrips** [comment]
Doesn't look to be message from CMI. If issue persists with next version, please test it out with CMI only and if issue is still there let me know. But at this moment i cant see anything what could be sending this message.
