### ISSUE TITLE
GUIs not renaming items

### ISSUE THREAD

**Issue by HeyWinkeyFace** [Zrips/CMI#4998]
**Description of issue:**
CMI GUIs (kit editor, warps etc) 
are not renaming any place-able blocks (things like wool) other items (golden ingot, potions) are fine.

---

**Cmi Version (using`/cmi version`):** 
8.8.0.8 / CMILib 1.0.0.2

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
I don't have permission... will try to figure out.

See attached image for an unnamed item.
![1](https://user-images.githubusercontent.com/40117770/106215341-bc7d7e00-619e-11eb-9827-d45d74f5452b.png)

**Comment by Zrips** [comment]
Try resetting your locale file as items could not be renamed in case of locale file not having appropriate lines or they being set to empty fields.

**Comment by VOrlando520** [comment]
Can verify that regenning the locale did not fix the issue.

**Comment by Zrips** [comment]
This is more than strange, as all buttons been processed in same exact way and it would only result in showing actual item name if items name or lore was not defined at all, which in general cant really happen as I look at code. 
What locale are you using? Is this same exact issue across all kits? What version of server you have?

**Comment by Mythicals** [comment]
Having the same issue. Using Magma version 537f1d6 on Minecraft 1.12.2. Updated to the latest version of CMI.
![image](https://user-images.githubusercontent.com/12033800/106527076-ad574280-64b4-11eb-9a8d-4f8cd1c441d3.png)

**Comment by VOrlando520** [comment]
> Having the same issue. Using Magma version 537f1d6 on Minecraft 1.12.2. Updated to the latest version of CMI.
> ![image](https://user-images.githubusercontent.com/12033800/106527076-ad574280-64b4-11eb-9a8d-4f8cd1c441d3.png)

Turns out it isnt a CMI issue, its a magma issue with not being able to apply meta tags on tile entities such as wool, etc. It only happens with magma, works fine on mohist and other hybrids.
