### ISSUE TITLE
Permissions system for customaliases

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#5]
I have a command that restarts the server in a fancy way. With a count down and everything. It uses `fromConsole!` tag. At the moment as it currently stands any user who uses the command can restart the server. I want to give the custom command to specific people. Is it possible to add a custom `permission: *permhere*` tag to customaliases? This addition would allow server owners to create custom commands/aliases like their own emojis for example and put permission nodes on them and give them to specific ranks aswell (Example). Love the plugin, keep up the great work!

**Comment by Zrips** [comment]
Well... If you can utilize fromConsole! tag, then this means you are using specialised commands, this means you have option for perm:[value][?][#]! tag which will limit alias usage based on permission node. So simple tag like perm:cmi.uberrestart?#! will limit usage and players should have cmi.uberrestart permission node to use it. If they don't have it, message will be shown and rest of command after this tag will not be performed.
