### ISSUE TITLE
Permission error 

### ISSUE THREAD

**Issue by PotassioK** [Zrips/CMI#5003]
when a player tries to use a command without permission the error is sent twice, and I can not remove that when someone passes with the mouse over the error gives the missing node

**Cmi Version 8.8.0.8** 

**Server Type (tuinity):** 

**Server Version (1.16.5):**

**Comment by Zrips** [comment]
I need actual example of command, what error message you are getting and what permission node was reported to be missing.

**Comment by PotassioK** [comment]
It happens with all the commands that players do without permission. I can't give you a specific example.

**Comment by Zrips** [comment]
Well at this moment i cant reproduce this issue and no one else seam to report this. It could be an issue with another plugin duplicating commands which results in double error message. But in general double message should not appear in normal situations. You could test it out by removing all plugins except CMI to make sure its issue with CMI and any extra information would help out to figure out what could cause this if its originating from CMI
