### ISSUE TITLE
Issue with Custom Crafting Recipe with Enchanted items

### ISSUE THREAD

**Issue by ondrasek14** [Zrips/CMI#5006]
Custom recipe with enchanted items not works...

Crafting Recipe
![11](https://user-images.githubusercontent.com/78275173/106365119-abb24100-6333-11eb-98af-d781d35bc52a.PNG)

In crafting table
![22](https://user-images.githubusercontent.com/78275173/106365127-b8cf3000-6333-11eb-9bbe-ae062a2c3302.PNG)

**Cmi Version (using`/cmi version`):** 
8.8.0.7 CMILib 1.0.0.2
**Server Type (Spigot/Paperspigot/etc):** 
Tuinity
**Server Version (using `/ver`):** 
Tuinity 1.16.4

**Comment by broken1arrow** [comment]
He has not add support for nbt.

**Comment by Zrips** [comment]
CMI uses vanilla recipe engine which only supports material type and amount as ingredients, you can have custom item as result but input can only be clean items.
If you need this specific feature you might want to look around for specialized plugins as this requires completely new system to be implemented.
