### ISSUE TITLE
/hologram <name> doesn't show text just open GUI option

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5011]
**Description of issue:**

---

Hi, when you use /hologram <name>, there is just shown open GUI option and not option to edit text (actual lines and + for adding new line).
![image](https://user-images.githubusercontent.com/18662086/106400450-b5fd3980-641e-11eb-97b3-1f78e5647d41.png)

---

**Cmi Version (using`/cmi version`):** 8.8.0.9

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 1.16.5, 17

**Comment by Zrips** [comment]
Will be fixed with next build
