### ISSUE TITLE
add option to toggle flightcharge's bossbar 

### ISSUE THREAD

**Issue by RookieAND** [Zrips/CMI#5012]
I use flightcharge feature. and I show amount of player's charge in scoreboard. not bossbar.
So It's good to add option to toggle bossbar option I think. (like bossbar : true or false)

and It's better to disabled flightcharge option per world. I use playerChangeWorld event to disable flightcharge some world. But It's not flexible I think.

**Comment by Zrips** [comment]
Will add option with next update
