### ISSUE TITLE
Toggle global / local chat in chat feature

### ISSUE THREAD

**Issue by RookieAND** [Zrips/CMI#5013]
I knew there's local chat option and shout option by adding ! in front of chat.

But It's too complicated to use shout option I think. So I suggest to add toggling global / local chat command.

**Comment by mrfloris** [comment]
I really miss having the ability to chat per world, local radius, and switch back to a global chat. 

I really like shout, broadcast, msg, global chat, and the chat room. But knowing im having a mining party and being able to chat about that without disrupting the global chat is really nice. as well as chatting only to the ones nearby.

**Comment by CloudeLecaw** [comment]
u know request here got ignored? This here is jsut for issues
send them here aggain: https://github.com/Zrips/CMI/discussions

**Comment by mrfloris** [comment]
Not ignored, they can be moved to ^ that location.

**Comment by CloudeLecaw** [comment]
They will be to keep the issues clearer. I renember actual over 700 teads where moved there allready.

**Comment by broken1arrow** [comment]
He close the issues, if it in wrong section (what he say).
