### ISSUE TITLE
Option to limit [item] and %item% in chat to only one per message to prevent kicks

### ISSUE THREAD

**Issue by NightFuryStrike** [Zrips/CMI#5014]
**Description of issue:**
Greetings, I was wondering if we could get the ability to only have one [item] display in chat instead of multiple, because my players are doing things like "[item][item][item][item][item][item][item][item][item][item][item][item][item][item][item][item][item][item][item][item][item][item][item]" in chat which is causing people to get kicked.

A config option to filter out extra/repeated [item]'s from messages would solve this issue.
Thank you.

---

**Cmi Version (using`/cmi version`):**  8.8.0.8

**Server Type (Spigot/Paperspigot/etc):** Paper-445

**Server Version (using `/ver`):** 1.16.5

**Comment by Zrips** [comment]
Will be fixed with next build
