### ISSUE TITLE
cmi broadcast

### ISSUE THREAD

**Issue by XBlowmPow3r** [Zrips/CMI#5015]
Hello. i noticed that the broadcast command of cmi is very heavy, is there a possibility that you consider doing it asynch multithreaded? I made a script that automatically sends message using cmi broadcast. and missing 7 lines at a time, this brings the tps to 15 for a second, I am also sending you the timings report.
![1](https://user-images.githubusercontent.com/73916775/106472757-4da46b80-64a3-11eb-8738-07d84bb0760d.PNG)
thank you very much for considering =)

**Comment by CloudeLecaw** [comment]
U can do it a bit smarter with using /cmi ctellraw all <T>yourtext</T>
This should be smarter then sending 7 Broadcasts...

**Comment by mrfloris** [comment]
> U can do it a bit smarter with using /cmi ctellraw all yourtext
> This should be smarter then sending 7 Broadcasts...

CMI is more than welcome to adapt to this method. :)

**Comment by CloudeLecaw** [comment]
Next time pls ask here
https://github.com/Zrips/CMI/discussions

**Comment by Zrips** [comment]
I can move to async, but this is mostly relating to the issue that you have placeholders in the messages you are sending out and each placeholder takes time to be processed. Moving this action into async is some what risky as not all plugins which placeholders you will use might like it being called in async. Well, we will see if there wont be issues.
