### ISSUE TITLE
Cmi Play TIme Won't Increase

### ISSUE THREAD

**Issue by Speedspencer** [Zrips/CMI#5028]
**Description of issue:**
- Player Reports that their playtime will not increase at all 
I'm not sure if this causes it but I receive io.netty.handler.timeout.ReadTimeoutException in my console when players online
---

**Cmi Version (using`/cmi version`):** 
version 8.8.1.0
**Server Type (Spigot/Paperspigot/etc):** 
Purpur
**Server Version (using `/ver`):** 
git-Purpur-956

**Comment by Zrips** [comment]
Vanished player playtime will not increase until he returns from vanish mode which will shown actual playtime, this doesn't mean it was stopped it will only stop updating while player is in vanish mode. Other than this it could be that player was in afk mode and you have StopPlayTime enabled.

**Comment by Speedspencer** [comment]
I did not vanish and my players didn't too, about afk option, I turn off afk system and it still not increase. the times did not increase for a week  https://imgur.com/a/YFxsmFl

**Comment by Speedspencer** [comment]
Edit Play time won't work either, it just says https://imgur.com/a/9ELGof9
