### ISSUE TITLE
Hologram ICON Duplication Glitch On Server Reload

### ISSUE THREAD

**Issue by AKATONYEXILE** [Zrips/CMI#503]
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
##When you reload the Server with /reload then the ICONS will get duplicated if there is more than one hologram with the same ICON/TEXT. Only Server restart will fix the issue no error log in console.##
####################
```

**Cmi Version (using`/cmi version`):7.8.3.0** 

**Server Type (Spigot/Paperspigot/etc):Spigot** 

**Server Version (using `/ver`):1.12.2-R0.1-SNAPSHOT**

**Comment by TheWranger** [comment]
Not really a valid bug.
/reload causes issues with tons of plugins, you should really avoid using it.

**Comment by LogGits** [comment]
This is a visual glitch. We don't advise using `/reload`. This "bug" is fixed by either rejoining the server or leaving the chunk and coming back.
