### ISSUE TITLE
alias commands in warmups

### ISSUE THREAD

**Issue by JaTiTV** [Zrips/CMI#5033]
Visit https://github.com/Zrips/CMI/discussions/new to post question
Posting questions in ticket section could result in their removal.
Can alias commands be added to warmups?

**Comment by AZFire1** [comment]
As it states, posting questions in ticket section could result in their removal so I don't recommend you post questions here.

And, yeah I think alias commands can be added to warmups, just it's not recommended, use the actual CMI provided command to effect all aliases "/cmi <command>". The alias should work though.

**Comment by Zrips** [comment]
@JaTiTV 
You will need to provide full command and not alias for warmup to kick in.
