### ISSUE TITLE
Could not pass event CMIArmorChangeEvent to CMI v8.8.1.0

### ISSUE THREAD

**Issue by koyere** [Zrips/CMI#5035]
**Description of issue:**
Error that is generated over and over again in the console.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/Lsf1VpA1
```
---

**Cmi Version (using`/cmi version`):** 
CMI v8.8.1.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper version git-Paper-449 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Should be fixed with next update
