### ISSUE TITLE
[Command Abuse] Tpa/Tpahere combined and cancelled

### ISSUE THREAD

**Issue by emanondev** [Zrips/CMI#5037]
**Description of issue:**
Player A & Player B:

Player A issue /tpa B
Player A issue /tpahere B
Player A cancel last tp request (disable the tpahere)
Player B click on chat to accept the /tpahere of A (which was disabled by A)
Player A gets teleported as if Player B accepted the tpa

why is it a bug? Player A obtain the secret base location of B and will be able to grief it, but B never accepted the tpa request!

Proposed solution 1: when A cancel a tp request to B, A also cancel every previous tp request made to B
Proposed solution 2 (alternative): different commands to accept tpa and tpahere

---

---

**Cmi Version (using`/cmi version`):** 
Versione di CMI: 8.8.1.0 BungeeCord CMIB  SqLite
CMILib: 1.0.0.2 

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper(457) 1.16.5-R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment]
suggestion 1..
use a protection plugin, then A cant grief anything from B. so the land wherehe got tped is useless for him.


i tried to replicate You description... it ended up with irititating me..

1. Player A issue /tpa B
 - Player B gets Request - he can cancel or accept -> ok
2. Player A issue /tpahere B
- a good question would be by he can use that command but ok..
- Player B gets  a request -  he can sancel or accept -> ok
3. Player A cancel last tp request (disable the tpahere)
- how player A can cancel it? he never got a request.. Just player B got one.
- but ok player A channel the option to get request from others (also Player B)
4. Player B click on chat to accept the /tpahere of A (which was disabled by A)
-  Player B clicks now on accept - why he does this when he decided to cancel before?.. but ok..
- Player B clicks accept now... why not the requuest is just disabled for Player A that means Player B cant sent a reuqest anymore to Player A - not opposite
5. Player A gets teleported as if Player B accepted the tpa
- he clicked on accept to he accepted - this is not really an issue. the question should be by he accepted? but ok

What we see here is more tring to find an issue in something that sounds more like wrong habbit of players
if i decide to cancel i dont accept it in next stage no matter how often an other tries it.
and if i complety dont want it then i disable it (like player A did - noone can use /tpa A on him anymore)

**Comment by Zrips** [comment]
@emanondev 
Will make some adjustments for tpaccept command to take into consideration to which one you are accepting too to avoid things like you mentioned here
