### ISSUE TITLE
CMI-API from Spigot is extremely outdated

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#5041]
**Description of issue:**
The CMI-API jar you can download from the Spigot page is extremely outdated and missing a lot of the features. Should probably update that :P

**Comment by Zrips** [comment]
There is github repo for more up to date usage. That one is... Outdated... To put it simply... Tho CMI will get some huge code trimming soon due to CMILib coming out, so I might remake both of those at same time. Thanks for reminding me about that one.
