### ISSUE TITLE
I lost all my configure files when I update CMI

### ISSUE THREAD

**Issue by thebladeofflame** [Zrips/CMI#5050]
I lost all my configure files when I update CMI
8.8.0.6 -> 8.8.1.0
Why I saw nothing on the plugin's web page to tell me backup the configure files before I update CMI?
I just saw the update information urge me to update CMI,but I never saw any infomation to told me I should backup my configure files before I update CMI?

**Comment by mrfloris** [comment]
You can drop in the latest jar and update, it shouldn't get rid of files.

That said, it IS common practice (and common sense) to back up your data before making changes, not just for cmi, but also for your other data, plugins, servers, services, scripts, modules, libraries, api, etc. 

Not having a backup results in being unable to roll back your test server. 

Not having a test server to try your customizations on also means a risk of having data loss on a production server.

I just grabbed an old 1.15.2 backup from last year and it has a very old cmi build and data.

I put the latest jar there and updated other plugins and 1.16.5 spigot and run the server, cmi updated fine, no files were purged or reset.

**Comment by Zrips** [comment]
CMI doesn't override old files it will auto update existing one with new entries or remove none existing ones. File reset can only happen if you have miss format in them and it was forced to be reset. In which case you can find old file in FileBackups folder under specific name and time when this backup was made which you can then fix and copy over to correct place for it to be loaded in.
