### ISSUE TITLE
Combat -> way to start combat only if player attacks, not when he's attacked

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5055]
Hi, I have reports that when players build or something like that and then are shot by skeletons and phantoms, they fall down... But I can't allow fly in combat due to players were using it with fighting and then it was so easy.

So what about way to start combat only (config option) when player attacks mob/ another player? And not when he's attacked?

**Comment by dkalaxdk** [comment]
It is?
Search for:
![image](https://user-images.githubusercontent.com/13720707/107204944-94431a00-69fd-11eb-8640-d403eeb2d29b.png)

**Comment by Zrips** [comment]
You might want to simply disable pve combat mode, otherwise disabling victim marking when mob attacks player would make it irrelevant in any case. Or atleast avoid disabling fly in pve combat or try enabling DisableFallDamage which should prevent one fall damage after they got shoot by mob.

**Comment by bobhenl** [comment]
Sad that includeVictim won't work, cause I wanted to let pve mode enabled as mentioned, because I think it's a little bit unfair (and if I disable fly then it's a little bit more unfair) that players can easily kill monsters (mainly if I have bosses around the world). About fall damage I had disabled it, but people still mark it as not comfortable when they are shot down by skeleton or phantom.
