### ISSUE TITLE
CMI chat still handles colours when CMI chat = false

### ISSUE THREAD

**Issue by dkalaxdk** [Zrips/CMI#5058]
**Description of issue:**
CMI chat still handles colours, even when modifyChatFormat = false
As seen in the images below, the cmi.colors.publicmessage.* still has an effect on whether or not you can use colours, even though CMI chat = false.
---
**Cmi Version (using`/cmi version`):** 
Included in the pictures:

![image](https://user-images.githubusercontent.com/13720707/107266104-5964d480-6a45-11eb-9db0-df369221099b.png)

![image](https://user-images.githubusercontent.com/13720707/107266136-62ee3c80-6a45-11eb-96ea-22577c5b8165.png)

---

**Relevant plugins (Delete if this isn't needed):**
No other chat managing plugins.

**Comment by Zrips** [comment]
You need to disable chat colorization and not chat message modifications. Those are separate from each other. 
Chat -> Colors -> PublicMessage: False
This will disable public message colorization
