### ISSUE TITLE
/recipe isn't tab completed

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5075]
**Description of issue:**

---

Hi, I just wanna report that /recipe isn't tab completed and that it could be really cool if there's tab complete like in /give cmd.

---

**Cmi Version (using`/cmi version`):** 8.8.1.1

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 1.16.5, 17

**Comment by CloudeLecaw** [comment]
Inagreeba tab completation there would be nice. A lot of servers use other languages and u need to know and type the english itemname each time manually

**Comment by Zrips** [comment]
Added
