### ISSUE TITLE
Warmup taking too many tick

### ISSUE THREAD

**Issue by AuroraCraftSG** [Zrips/CMI#5076]
**Description of issue:**
There are performance issue on cmi warm up

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```
![Screenshot_7](https://user-images.githubusercontent.com/67474322/107675709-4ff09c00-6cd3-11eb-815a-3e352896f81b.png)

**Cmi Version (using`/cmi version`): 8.8.1.0

**Server Type (Spigot/Paperspigot/etc):paper

**Server Version (using `/ver`):1.16.5

**Comment by Zrips** [comment]
Will make some small changes to try and improve performance, but in general warmup isint that heavy by itself, but commands performed after timer runs out might be which could be cause of this seemingly heavy method while its only the command itself which took more time then its needed.
