### ISSUE TITLE
cmi_user_afk does not sync over bungee but cmi_user_prefix does

### ISSUE THREAD

**Issue by Ace0fspadev** [Zrips/CMI#5083]
**Description of issue:**

cmi_user_afk placeholder does not sync over bungee, but cmi_user_prefix does.
- i wanted a tablist plugin wich is only installed on bungee to show the afk status
- the cmi_user_prefix is working fine in the tablist
- 
---

**How to reproduce?**
- try to access the cmi_user_afk placeholder on your bungeecord server

---

**Cmi Version (using`/cmi version`):** 
8.8.1.1

**Server Type (Spigot/Paperspigot/etc):** 
Paper and waterfall

**Server Version (using `/ver`):** 
git-paper-467 (1.16.5)

**Relevant plugins (Delete if this isn't needed):**
- cmi
- cmilib
- cmib
- bungeetablistplus

**Comment by Ace0fspadev** [comment]
cmi_user_afk does not return true, it returns §2true

**Comment by mav2020** [comment]
I know this is old, but it is worth checking the color as AceOfspadev mentions. On mine it returns gold (also had to use §6, not &6), meaning I used:
`condition: ${player cmi_user_afk} == "§6True"`
