### ISSUE TITLE
TPPOS playervar is missing in tabcompletation

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5085]
The command should have a var to tp player...
well the var works but tabcomplet is missing in it..

This is all i get suggestet from Tabcomplet - the playername suggestion is missing. Also u cant add the playername
because then next suggestion is Y instead of X and then Z.... instead of Y .. and so on...

here complet tabcompletation i get
![Snag_270810c0](https://user-images.githubusercontent.com/12080017/107826668-8be43980-6d85-11eb-8cb3-18a494e0b2b4.png)

![Snag_272bf4fb](https://user-images.githubusercontent.com/12080017/107829929-05325b00-6d8b-11eb-925c-b534538ee59d.png)

**Comment by Zrips** [comment]
Due to how player variable is handled, which requires -p: as prefix i cant really add it at this moment. Some improvements for tab complete is in order, but for now we will have to live with what we have

**Comment by CloudeLecaw** [comment]
> Due to how player variable is handled, which requires -p: as prefix i cant really add it at this moment. Some improvements for tab complete is in order, but for now we will have to live with what we have

-p: is needed?
why i can use manually then /cmi tppos Cloude_Lecaw 200 100 200 world   with success?
There we use the playername directly instead of -p:playername..  Thats confussing me a bit..
