### ISSUE TITLE
Toast and titlemsg bug

### ISSUE THREAD

**Issue by Mcdikmen** [Zrips/CMI#5088]
**Description of issue:**

If i try to run "toast" or "titlemsg" command, it gives the langs 4307 and 4313's info line message.
---

I added my problem in video.

https://youtu.be/3_4L_LpEO9E

**Cmi Version (using`/cmi version`): 8.8.1.1

**Server Type (Spigot/Paperspigot/etc): Paperspigot

**Server Version (using `/ver`): 1.16.5

**Relevant plugins (Delete if this isn't needed):**

**Comment by CloudeLecaw** [comment]
Have u checked your langfile? Sometimes on updating, specialy from older versions the file can become currpted.

**Comment by Mcdikmen** [comment]
I didn't touch my lang file. Here is the EN and TR version's lines:

https://imgur.com/pEM44B8
https://imgur.com/94HJcqc

**Comment by Zrips** [comment]
Hmmm, issue with locate. Will fix at my end and you will need to ether regenerate entire TR file by removing it or do it manually by replacing [mesajın] with [message]

**Comment by Mcdikmen** [comment]
I dont want to change all my language pack cuz off little bug. I did the manual replacing but it line changed "[mesajınız" to "[message]".

https://prnt.sc/101uazf
https://prnt.sc/101ubkb

@Zrips
