### ISSUE TITLE
/back and /home locations in the nether near the ceiling (not necessarily near the roof) STILL put the player on the nether roof. (Yes, still)

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#5089]
**Description of issue:**
My ticket #3859 was closed last night with the comment that this should be fixed in recent versions.  It is not.  I've just replicated the issue in CMI 8.8.1.1 on Paper 446 (1.16.5).

Thank you for your work on the plugin. :)

Info from last ticket:
---
Description of issue:
The issue is described in #3761 #3761 which was closed, but I'm still having this issue, as described after the ticket was closed on that ticket, now continuing to have it on paper 128 and CMI version 8.7.4.1

Description on original ticket: Description of issue:
Players doing /back and /home to locations in the nether are sometimes put on the nether roof. These players are NOT being teleported back down by the function that should teleport players off the roof and they ARE nearly instantly killed by the void damage setting, making going /home or /back to the nether a very risky prospect. Can safe teleport please be made not to teleport players to the nether roof?

Thank you :)

Comment after ticket closed:
Thx for the improvement, but this is still happening in CMI 8.7.3.4 when players are very close to the ceiling in the nether:
https://www.youtube.com/watch?v=6WjMhr2_P0M
Please note that while I am close to the ceiling there, I'm not that close to the roof. (You can see my coordinates on my mini-map display and I'm at about 106. My nether roof is at 128.

Another server owner's comment after ticket closed:
My 2 players just died cause they were tped to the roof on /home where they get void damage
---
___

---

**Cmi Version (using`/cmi version`):** 
[14:50:42 INFO]: --------------------------------------------------
[14:50:42 INFO]: CMI plugin version: 8.8.1.1 MySQL
[14:50:42 INFO]: CMILib: 1.0.0.2 
[14:50:42 INFO]: Server: Paper(446) 1.16.5-R0.1-SNAPSHOT
[14:50:42 INFO]: CMI economy: False Vault: 1.7.3-b131 CMI Chat: False 
[14:50:42 INFO]: Modules -> 46 enabled 8 disabled: spawnerProximity, flightCharge, disabledEnchants, mirror, ranks, moneyCheque, spawners, spawnerCharge
[14:50:42 INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
[14:52:06 INFO]: This server is running Paper version git-Paper-446 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
It seams that Minecraft server itself teleports player to top location by default when there is no free space as I'm teleporting player to exact location yet he ends up on a different level then he should.

**Comment by Zrips** [comment]
Will make some small change relating to this. Cant really reproduce your issue in particular, but this indicated possible issue when you are in tight locations especially on 1.16 servers. Test next version and if issue persists, let me know.

**Comment by Momshroom** [comment]
It's fixed. Ty!!
