### ISSUE TITLE
2 BossBar compass issues.

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#5090]
**Description of issue:**
Issue 1:
If you have the config option "RequireCompass" off, players will be able to view the compass at all times, and will not be able to toggle it off.. Is the permission "cmi.command.togglecompass" not a permission which also allows the use of the compass in the first place? Is the use of the compass allowed by default maybe? If it is, I think it should be changed, and a permission required instead.
Issue 2:
This could be interpreted as both an issue, and a suggestion. Currently, with the compass, if you have an off-world compass, somewhere in a different world, and you have the compass showing your homes, and death locations on, it will still show them in the compass. I think it would be nice if these would detect if you are off-world and remove them from the compass until you go to the world again.

---

**CONFIG SECTION:**
https://bin.bloom.host/miduhefiqa.yaml

---

**Cmi Version (using`/cmi version`):** https://bin.bloom.host/igehacakag.yaml

**Server Type (Spigot/Paperspigot/etc):** Purpur, yes I've tried on Paper.

**Server Version (using `/ver`):** https://bin.bloom.host/rozavivoko.md

**Comment by Zrips** [comment]
cmi.command.togglecompass this is permission node for command which can be used to toggle on and off boss bar compass in case you don't want it to be shown for that player. When you have permission node starting with cmi.command it will indicate that its directly tided to some command which name usually follows this prefix.
For location issue, yea, will fix that with next release.

**Comment by AZFire1** [comment]
As I said, if you have cmi.command.togglecompass permission node set to false to people, AND you have the always-on option set to true, it ignores whether players have perms half the time and displays them the compass anyways.. It's an issue, it doesn't work correctly @Zrips

**Comment by Zrips** [comment]
What do you mean with "always-on"? Where did you found this option?

**Comment by AZFire1** [comment]
Not always-on I just didn't remember the exact config option. If you have the "RequireCompass" off I meant.

**Comment by Zrips** [comment]
But i'm still lost here. cmi.command.togglecompass only effects command usage, it will not disable bossbar it will only prevent usage which allows to toggle bossbar on and off. If players before hand disabled bossbar then it will not appear. I cant pin point actual issue here, whats going on in what specific situation. 
Compass should always appear if feature is enabled and ether player holds compass when one is required or when player moves.  There are no permission node attached directly to this feature as it never went through full development and is still in some what experimental state. 
Or are you having players who can sometimes see bossbar compass and something they cant without changing anything?

**Comment by AZFire1** [comment]
Okay, since this only affects command usage. What I mean is, I have this command and permission specifically negated for all default players. I'm treating this command as a perk for higher luckperms groups. Since I find having the perk only able to be used when players are holding the compass pointless, I changed it to not require a compass to function ("RequireCompass" false). Setting this to false made it so all players, whether they have the permission "cmi.command.togglecompass" or not, randomly start seeing the compass. A few of my default grouped players saw this and asked how they could disable it. The only way they could disable it is with the toggle command, which they do not have perms for. My possible solution is to have the compass off by default for all players, which I assume is what you already have. Or, maybe require separate permissions to see the compass added onto being able to toggle the compass? For me, it's on by default for everyone unless toggled off. It's truly strange as I notice this only happens roughly 70% of the time as I have some of my players report they don't see the compass. In conclusion, what you said here "Or are you having players who can sometimes see bossbar compass and something they cant without changing anything?" sums up what I'm trying to say.

I also have a separate side suggestion. Is there a chance you could add a configuration option to allow changing the refresh rate of the compass bossbar as you have for the tablist? I'd love to make it smoother for myself. Or if you can, could you please make it smoother when looking around?

**Comment by Zrips** [comment]
There is update rate which can be defined in config file, but currently I'm capping it at 200ms I think, as it could be some what heavy on server if you start updating it every tick. I could remove that cap, but then i might get people complaining that this thing creates load on server... 
For compass, well, will have to look into it, checking permission node isint best thing to have, but option to pick default behavior could be added

**Comment by AZFire1** [comment]
You could remove the cap, keep the update rate at what you have it right now, but add a warning in the config file saying that it could cause lag below x.

I'd appreciate an option to pick default behaviour :)

**Comment by AZFire1** [comment]
but option to pick default behavior could be added

^^, when do you think you'll have time to add this? I'm looking forward to it :)

**Comment by AZFire1** [comment]
@Zrips
