### ISSUE TITLE
/glow not allowing colors

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#5095]
Version 8.8.0.9
Paper 1.12.2

./glow will work, but it will only glow white, none of the other commands for it work, It will only Toggle true/false if I try and use a color, if I try and color someone else, I cant open the GUI.

There are no errors, it just always processes any command as True/False.

**Comment by Zrips** [comment]
This can be caused by another plugin overriding glow color or in case you have disabled team management in config file then it will only toggle glow on and off as glow color is directly tied to team management feature.

**Comment by TomLewis** [comment]
Its disabled for a reason.
`When this is set to true features like glow color, player collision, name plates will stop working and CMI will avoid doing anything related to player teams`
I *think* I disabled it because of CMI messing with my name plate formatting, either that or it was tab names or something I already have setup to do with name formatting in-game.
