### ISSUE TITLE
If link contains #, Custom Text URL will not work.

### ISSUE THREAD

**Issue by ViaSnake** [Zrips/CMI#5098]
**Description of issue:**
Custom Text URL may not work under certain conditions.
If the URL contains a `#` in the middle, the URL will not work.
See below for an example.

---

`CustomText/example.txt`
```
<T>This is example.</T><H>URL does not work.</H><URL>https://google.com/#/test</URL>
```

---

**Cmi Version (using`/cmi version`):** 8.8.1.1

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-Paper-457

**Comment by CloudeLecaw** [comment]
U have related urls with #?

**Comment by ViaSnake** [comment]
> 
> 
> U have related urls with #?
> In yml the # is introducting a note

It seems that my testing was inadequate. It worked fine on the server with a clean install again. It seems that for some different reason it was not working.
I apologize for the inconvenience.
