### ISSUE TITLE
Broke Placeholders

### ISSUE THREAD

**Issue by MCTyler** [Zrips/CMI#51]
The one you added (%cmi_user_rank%) doesn't work and broke some others like (%cmi_user_balance%)

**Comment by MCTyler** [comment]
>cmi placeholders
[20:08:36 INFO]: --------------------------------------------------
[20:08:36 INFO]: 1. %cmi_user_charges_left%
[20:08:36 INFO]: 2. %cmi_user_charges_max%
[20:08:36 INFO]: 3. %cmi_user_charges_time%
[20:08:36 INFO]: 4. %cmi_user_charges_cooldown%
[20:08:36 INFO]: 5. %cmi_user_display_name%
[20:08:36 INFO]: 6. %cmi_user_nickname%
[20:08:36 INFO]: 7. %cmi_user_name%
[20:08:36 INFO]: 8. %cmi_user_cuffed%
[20:08:36 INFO]: 9. %cmi_user_god%
[20:08:36 INFO]: 10. %cmi_user_afk%
>

**Comment by C4BR3R4** [comment]
Also missing:
%cmi_user_canrankup%
%cmi_user_currentrank%
%cmi_user_nextranks%

**Comment by MCTyler** [comment]
@Zrips said this works on His end, is there a file I need to recreate or something?

**Comment by Zrips** [comment]
Don't check them from console, they are not being translated in that way. Use ingame.

**Comment by MCTyler** [comment]
So they are not going to work on my scoreboard anymore? Where will they work?
![2018-02-27_06 05 52](https://user-images.githubusercontent.com/6390898/36727852-620ee494-1b84-11e8-85d9-206a16d8c18a.png)

**Comment by LogGits** [comment]
Was able to reproduce this on CMI version 7.3.14 with placeholder api version 2.8.3. 
https://gyazo.com/d0a0bdf576b04275ff898f74ca1bc83a

@MCTyler What version of placeholder are you using. Also please report the output of `/papi parse %cmi_user_display_name% returns %cmi_user_display_name%` I recommend downgrading to `7.3.13` until this issue is resolved.

**Comment by MCTyler** [comment]
[12:26:58 INFO]: EODCrafter issued server command: /papi parse %cmi_user_display_name% returns %cmi_user_display_name%

**Comment by MCTyler** [comment]
Yea, That fixed the Players balance but of course the rank placeholder doesn't work....
![capture](https://user-images.githubusercontent.com/6390898/36728961-278b494e-1b88-11e8-80e9-ca7d5f140c90.PNG)

**Comment by LogGits** [comment]
> Yea, That fixed the Players balance but of course the rank placeholder doesn't work....

The downgraded version doesn't have this feature. The best bet is waiting for the next update which should hopefully resolve this issue 🙂

**Comment by Zrips** [comment]
Will work with next update

**Comment by MCTyler** [comment]
Perfect! Thank you soooo much!
![capture](https://user-images.githubusercontent.com/6390898/36741797-a33cc234-1bab-11e8-8f49-ce16bfe86e25.PNG)
