### ISSUE TITLE
Glow command cost doesn't work

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5101]
**Description of issue:**

---

Hi,  I wanna report that when I set this in command cost.yml:

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
- cmi glow :2000:true
- cmi glow false:0:false
```

Then when player choose color from GUI it doesn't work, cause it sends to console
[23:16:09 INFO]: Mastereve issued gui command: /cmi glow Mastereve darkpurple
[23:16:09 INFO]: Mastereve issued gui command: /cmi glow Mastereve gui

![image](https://user-images.githubusercontent.com/18662086/108128699-7173ce00-70ad-11eb-9f80-adccf6bd5781.png)

It's probably due to there are used 2 different commands, first to set color and second to open GUI again. But then I can't use glow command cost on it... And also **glow color isn't set then** and hopefully the money aren't taken.

---

**Cmi Version (using`/cmi version`):** 8.1.1.1

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 27

Alternative solution could be if you will allow use us playername there:
```
- cmi glow [playerName] :2000:true
- cmi glow [playerName] gui:0:false
- cmi glow false:0:false
```

**Comment by Zrips** [comment]
Gets a fix with next version
