### ISSUE TITLE
Combat -> is activated with armor stand and other entities

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5102]
**Description of issue:**

---

Hi, I wanna report that combat mode is activated too when you destroy armor stand and other entities like these. I think that they should be exempt, maybe as option in config.

---

**Cmi Version (using`/cmi version`):** 8.8.1.1

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 27

**Comment by Zrips** [comment]
Will be fixed with next build
