### ISSUE TITLE
Scavenge still works a little bit weird

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5104]
**Description of issue:**

---

Hi, scavenge command still works a little bit weird. When I use obsidian for scavenge, there isn't any vanilla recipe so it uses this one, but it could be used for infinity loop of gold, feather and obsidian.... as you can see on these two images
![image](https://user-images.githubusercontent.com/18662086/108187374-ae23e180-710e-11eb-8030-52cea016a63e.png)

![image](https://user-images.githubusercontent.com/18662086/108187381-aebc7800-710e-11eb-81af-b4d46d3820b2.png)

And I don't need any Angelic Block, I just need to put there normal obsidian. I still think that would be nice if items with lores and names are a little bit more respected here. So if player put there normal obsidian it probably won't be marked as Angelic block and it shouldn't scavenge to anything.

---

**Cmi Version (using`/cmi version`):** 8.8.1.2

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 27

**Relevant plugins (Delete if this isn't needed):** STB (Slimefun addon)

**Comment by Zrips** [comment]
Good point, dint considered situation when you might salvage item which doesn't have original recipe, will be fixed with next build
