### ISSUE TITLE
Unknown Error related to use of Warps

### ISSUE THREAD

**Issue by EchocallingEarth** [Zrips/CMI#5106]
Error notification in console when player uses Warp command

**[08:53:45] [Server thread/INFO]: RemIsDaBest issued server command: /warp PlayerShops
[08:54:16] [Server thread/INFO]:  ERROR!
     Error Message: Entity referenced is null!** 

CMI Version 8.8.1.2

Server Type Paper 

Server Version 1.16.5

Additional information upon request.

**Comment by EchocallingEarth** [comment]
And further continues when using /homes as well
[07:48:38 INFO]: RemIsDaBest issued server command: /warp PlayerShops
[07:49:16 INFO]: RemIsDaBest issued server command: /home
[07:49:27 INFO]:  ERROR!
     Error Message: Entity referenced is null!
[07:49:27 INFO]:  ERROR!
     Error Message: Entity referenced is null!
[07:49:27 INFO]:  ERROR!
     Error Message: Entity referenced is null!
[07:49:27 INFO]:  ERROR!
     Error Message: Entity referenced is null!
[07:49:27 INFO]:  ERROR!
     Error Message: Entity referenced is null!
[07:49:31 INFO]:  ERROR!
     Error Message: Entity referenced is null!
[07:49:31 INFO]:  ERROR!
     Error Message: Entity referenced is null!
[07:49:31 INFO]:  ERROR!
     Error Message: Entity referenced is null!
[07:49:47 INFO]:  ERROR!
     Error Message: Entity referenced is null!

**Comment by Zrips** [comment]
Doesn't look to be related to CMI directly. What it looks like that there is some bug server side relating to entities, CMI only teleports player to the location and it might trigger some errors when chunk is loaded and some entities have something incorrect set for them. You might check some NPC plugins you have on your server.
