### ISSUE TITLE
Restart server saving sethome point problem

### ISSUE THREAD

**Issue by vc606** [Zrips/CMI#5107]
**Description of issue:**

restart the server restarted, some players' sethome points on my server were reset. (The new starting point is lost, and the deleted point reappears.)

I found this problem a while ago and it can’t be improved after updating to the latest version 

The data format is mysql. 

---

**Cmi Version (using`/cmi version`):**CMI8.8.1.2

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.16.5

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
By any chance you are using same database table for multiple servers? As it was indicated not to do that in database config file due to possible issues like that.

**Comment by vc606** [comment]
Yes, I currently use multiple servers for the same database. Should I change to create a new database for each server?
Will the newly created server player settings affect it?

**Comment by Zrips** [comment]
I did included this into dataBaseInfo.yml file
`  # ATTENTION! DON'T USE SAME DATABASE TABLES FOR MORE THEN ONE SERVER, YOU WILL HAVE UNEXPECTED ISSUES. EACH SERVER SHOULD HAVE ITS OWN DATABASE TABLE SETUP`
You NEED to use different tables for different servers if you want to avoid issues like that. Data across bungee network is not synched, for now, so you cant simply use same database to store data from multiple servers, it will override existing data with new one and might reset when player changes servers. Separate them.
