### ISSUE TITLE
Basically doesn't works at all in Thermos 1.7.10

### ISSUE THREAD

**Issue by iLaloxYT** [Zrips/CMI#511]
**Description of issue or feature request:**
The plugin barely can do something using Thermos 1.7.10. I guess Zrips haven't tested the plugin using that actually pretty known .jar.

I wish I could list all the bugs I've found, but there's so many that I'd never end, the best way you can get them is testing it out by yourself I guess :(

It's really sad :(

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
OMG, almost everything returns an error :(
```

**Cmi Version (using`/cmi version`): 7.8.3.0 ** 

**Server Type (Spigot/Paperspigot/etc): Thermos** 

**Server Version (using `/ver`): This server is running Thermos | https://github.com/CyberdyneCC/Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.58 (MC: 1.7.10) **

**Comment by MCTyler** [comment]
https://github.com/CyberdyneCC/Thermos

**Comment by iLaloxYT** [comment]
But I've seen complex plugins perfect working in this version, I tought you could handle it. Lol

**Comment by tmellen** [comment]
Thermos was last updated 2 years ago. It's not about "handling it". It's about putting forth the effort to change code to support something dead, along with everything else that isn't dead. The effort is better spent supporting the living, not the zombies.

**Comment by CloudeLecaw** [comment]
>  But I've seen complex plugins perfect working in this version, I tought you could handle it. LolU wont belive it but there are also a Hand of Plugins out today that also support Spigot 1.6.4 ;)
but like tmellen and MCTyler allready said, to ask for Thermos Support is like you would ask to make CMI compatible for Spigot 1.6.4 -  It does not work the aforth..and by the way.. Thermos is not so well known anymore. It become forgotten for most...

**Comment by Zrips** [comment]
@iLaloxYT Thermos is dead platform, its heavily modified 1.7.10 version which doesn't have bunch of basic methods. CMI is huge and to have support for dead platform i would have to implement special support for it by disabling bunch of features which are not possible on that specific platform and remake some of them to have appropriate methods used by that platform. 
Soon we will get 1.13 and there is more up to date moded servers which if not working properly can be supported as they have some potential. 
So sorry, but no go on this one.
