### ISSUE TITLE
Holograms around ground entities

### ISSUE THREAD

**Issue by Paistecrafter** [Zrips/CMI#5111]
Hello, there seems to be an issue on my server with ground entities having hologram nametags. Though I am not 100% sure, I do strongly suspect CMI is responsible since it is the only plugin I have to my knowledge with hologram capabilities. I cannot seem to find any reference to this conundrum online, and was wondering if there's something in config that can be done to disable this. I have included screenshots for clarity. Thanks a lot for the help.
![2021-02-18_13 14 24](https://user-images.githubusercontent.com/79278575/108405750-7a6cb880-71ef-11eb-8b99-7474c8b31da9.png)
![2021-02-18_13 18 41](https://user-images.githubusercontent.com/79278575/108405755-7b9de580-71ef-11eb-819d-e07652a5dc4e.png)

**Comment by CloudeLecaw** [comment]
cmi cant do this

Your using an itemStacker?

**Comment by Paistecrafter** [comment]
> cmi cant do this
> 
> Your using an itemStacker?

hmm, not that I'm aware of, but I'll find out for sure. Thank you

**Comment by CloudeLecaw** [comment]
in first case you may can setup a testserver where ust your CMI and your permissionsystem is installed nothing else.

Then you know if this is coming from CMI or not

**Comment by Paistecrafter** [comment]
> in first case you may can setup a testserver where just your CMI and your permissionsystem is installed nothing else.
> 
> Then you know if this is coming from CMI or not

found issue, was from another plugin. thanks a lot for the help
