### ISSUE TITLE
Possible Item-Duplication when using Shulker-Backpacks

### ISSUE THREAD

**Issue by J0schlZ** [Zrips/CMI#5112]
**Description of issue:**

We got a duplication-issue since we use ChestSort along with Shulker-Backpacks from CMI.

Steps do reproduce:
You have 2 shulker-boxes in your inventory, (box-A, box-B)
Put box (B) into hotbar, slot 1
Put box (A) into hotbar, slot 2
Put some stuff to duplicate (e.g. diamons) into box (A)
Open box (A) with SHIFT+Rightclick from your Inventory (CMI-Backpacks-Feature)
Double-click an empty slot in your hotbar (bottom-bar of inventory-gui)
The content of box (A) is copied into box (B)

**Cmi Version (using`/cmi version`):** 
8.8.1.2

**Server Type (Spigot/Paperspigot/etc):** 
PaperMC

**Server Version (using `/ver`):** 
1.16.5 (Build: 470)

**Relevant plugins (Delete if this isn't needed):**
https://www.spigotmc.org/threads/1-8-1-16-chestsort-api.334121/

**Comment by CloudeLecaw** [comment]
But without chestsort this duplication did not happen? U should inform the Chestsort dev too may he can fix this on his end.

**Comment by J0schlZ** [comment]
> But without chestsort this duplication did not happen? U should inform the Chestsort dev too may he can fix this on his end.

Yes. I already did this. Since i got no answer i decided to aks here.

**Comment by Zrips** [comment]
This needs to be fixed from sort plugin side as i cant simply add support for dozens of different sort plugins out there.

**Comment by mfnalex** [comment]
> > But without chestsort this duplication did not happen? U should inform the Chestsort dev too may he can fix this on his end.
> 
> Yes. I already did this. Since i got no answer i decided to ask for it here.

I didnt reply? You only opened the issue on the ChestSort repo 18 hours ago

**Comment by J0schlZ** [comment]
> > > But without chestsort this duplication did not happen? U should inform the Chestsort dev too may he can fix this on his end.
> > 
> > 
> > Yes. I already did this. Since i got no answer i decided to ask for it here.
> 
> I didnt reply? You only opened the issue on the ChestSort repo 18 hours ago

I posted it at Spigot Forums some days ago.
Didn't know you're using Github-Issues.

**Comment by mfnalex** [comment]
> > > > But without chestsort this duplication did not happen? U should inform the Chestsort dev too may he can fix this on his end.
> > > 
> > > 
> > > Yes. I already did this. Since i got no answer i decided to ask for it here.
> > 
> > 
> > I didnt reply? You only opened the issue on the ChestSort repo 18 hours ago
> 
> I posted it at Spigot Forums some days ago.
> https://www.spigotmc.org/threads/1-8-1-16-chestsort-api.334121/page-27#post-4082248
> 
> Didn't know you're using Github-Issues.

Sorry I don't use the Spigot discussion really often since almost everyone switched to reporting bugs on my discord, I'll have a look at the issue.

**Comment by J0schlZ** [comment]
Thank you

**Comment by mfnalex** [comment]
Why was this closed without any reason?

**Comment by CloudeLecaw** [comment]
it was closed because of

> This needs to be fixed from sort plugin side as i cant simply add support for dozens of different sort plugins out there.

**Comment by mfnalex** [comment]
Same for me. ChestSort properly removes the items and adds them back in the correct order using the Spigot API. No idea why CMI doesn't detect it.

**Comment by CloudeLecaw** [comment]
> Same for me. ChestSort properly removes the items and adds them back in the correct order using the Spigot API. No idea why CMI doesn't detect it.
Maybe because the ChestSort doesnt use the SpigotAPI and uses its own methodes?^^
take a look at the code - you will see :3
