### ISSUE TITLE
%cmi_user_nickname% won't be clean

### ISSUE THREAD

**Issue by jing-shiun** [Zrips/CMI#5114]
"The placeholder %cmi_user_cleannickname% doesn't display the users name whenever a nick isnt set.

Cmi Version (using/cmi version): 8.7.12.6

Server Type (Spigot/Paperspigot/etc): Paper"

Can you guys change this back?
Or add some new placeholers like %cmi_user_nickname_clean%
Because my server want to make nickname and username on same chat/tab!
Please

**Comment by Zrips** [comment]
You need to update CMI as this was updated with latest builds and in case nick name is not set then original players name gets returned.
