### ISSUE TITLE
warps failing to edit

### ISSUE THREAD

**Issue by GrimPod** [Zrips/CMI#512]
Issue with warps not allowing options to be changed, including:
icon, autolore, officon,reqperm,showwithoutperm, settingNewLocation
Only one working is slot

**Cmi Version (7.8.3.0`):** 

**Server Type (Spigot):** 

**Server Version (1.12.2:**

**Comment by mercurialmusic** [comment]
Confirming this with CMI 7.8.4.0 as well, but not sure when it started. Went to edit a warp last night and had to remove it and redo it from command only. Possibly related to the GUI fix?

**Comment by GrimPod** [comment]
Fixed
