### ISSUE TITLE
I dont want to change all my language pack cuz off little bug. I did the manual replacing but it line changed "[mesajınız" to "[message]".

### ISSUE THREAD

**Issue by Mcdikmen** [Zrips/CMI#5121]
I dont want to change all my language pack cuz off little bug. I did the manual replacing but it line changed "[mesajınız" to "[message]".

https://prnt.sc/101uazf
https://prnt.sc/101ubkb

@Zrips

_Originally posted by @Mcdikmen in https://github.com/Zrips/CMI/issues/5088#issuecomment-782621440_

**Comment by Zrips** [comment]
Damn, my bad, found misspelling in the code. Ether wait todays update or update those 2 lines with [messsage] yes all three S this will get resolved with next update, but for time being you can test it out with this small change.

**Comment by Mcdikmen** [comment]
Thank u, I'll wait the update. 👍
