### ISSUE TITLE
Loosing inventory after dead?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5125]
**Description of issue:**

---

Hi, sometimes happens that players loose their inventory from some reason. It mostly happens when they fall from the high. i've tried discovered if it couldn't be caused by something with fall damage or something with combat mode, but I didn't get it still yet. Same when they teleport to home and then they are satisfied (and this shouldn't happen too probably).

I know that you probably can't solve this right now, may you could try to check something with fall damage or combat if it's not related, but what I wanna to ask, if you could add at least something for debug it more? Or maybe to /invlist add new line if items were dropped on the ground? We have coreprotect etc... but there isn't listed if items were dropped, only when they're picked up. We don't know how to solve this... So if you could add something for debugging this I will be glad. Or may if you will found where's the problem, but as mentioned IDK if it'S related to CMI, it only happens sometimes and we can't reproduce it even when we've tried it multiple times. We don't even know if players are not lying to us, but it seems they aren't.

---

**Cmi Version (using`/cmi version`):** 8.8.1.2

**Server Type (Spigot/Paperspigot/etc):**  Yatopia

**Server Version (using `/ver`):** 25

**Relevant plugins (Delete if this isn't needed):** [17:21:33 INFO]:  Plugins (131): AntiRaidFarm, AuctionMaster, AuthMe, BestTools, BetterBees, BlockRegen, Boss, BossShopPro, Brewery, BungeeTabListPlus, CMDispatcher, CMI, CMILib, CMIPaperLib, Captchas, ChatControlRed, ChatEmojis, ChestSort, Chunkmaster, ClickDye, CollaborationRedirect, ColoredEnderChests, ConsoleSpamFix, CoordinatesHud, CoreProtect, CraftBook, CraftBook5, CraftingStore, CrazyEnchantments, CreativeItemControl, DefensiveTurrets, DeluxeTags, DiceFurniture, DiscordSRV, Drop2Inventory, Drycell, DyedBackpacks, DynaTech, ERCoupons, EcoPower, ElectricSpawners, Emailer, ExoticGarden, ExtraGear, ExtraHeads, ExtraTools, FeatherBoard, FluffyMachines, FoxyMachines, FurnitureLib, GadgetsMenu, GeneticChickengineering, GlobalWarming, HeadDatabase, HotbarPets, HyperDrive, InfinityExpansion, InteractionVisualizer, InvUnload, InvisibleItemFrames, InviteSystem, Jobs, JukeBox, JumpAndRuns, Kotlin4MC, LibsDisguises, LightAPI, Liquid, LiteBans, LiteXpansion, LuckPerms, MVdWPlaceholderAPI, Magic, MobCapturer, MobFarmManager, MultiVIP, Multiverse-Core, NBTAPI, NametagEdit, NoCheatPlus, NoteBlockAPI, Oh_the_dungeons_youll_go, PhysicsToGo, PlaceholderAPI, Plan, PlayerWorldsPro, ProtectionLib, ProtocolLib, PvPToggle, Regionerator, Residence, RestrictedCreative, SAML, SFCalc, SecuredNetwork, SelectionVisualizer, SensibleToolbox, ServerUtils, Shopkeepers, SkinsRestorer, Slimefun, SlimefunOreChunks, SlimefunWarfare, SlimyTreeTaps, Sockets4MC, SoulJars, SoundMuffler, SpecializedCrates, SuperLog, TerraformGenerator, TimeVote, TokenManager, TradeMe, TranscEndence, TreasureHunt, TryMe, UltimateFishing, UltimateTimber, Vault, ViaBackwards, ViaBoundingBox, ViaRewind, ViaVersion, ViewDistanceTweaks, VoidGenerator, VotingPlugin, WorldEdit, XPBoost, antiRedstoneClock, dynmap and spark

Don't know if something could be more relevant. I don't have anything to clear items like clearlag, only MobFarmManager etc.

**Comment by Zrips** [comment]
Are we talking about cmi.keepinventory permission node here?

**Comment by bobhenl** [comment]
No players without this permission. Just something to help investigate

**Comment by Zrips** [comment]
Then I have no idea. If we are not talking about cmi.keepinventory permission node acting strangely but you have another plugin controlling this, then I have no idea how I should help you out here. Try investigating plugin which actually controls players inventories on their death if you dint give players CMI permission then CMI does nothing relating to it.
