### ISSUE TITLE
I set the players sethome limit to 1 but default players can still have a 2 homes.

### ISSUE THREAD

**Issue by Mcdikmen** [Zrips/CMI#5127]
**Description of issue:**

I set the players sethome limit to 1 but default players can still have a 2 homes.

https://cdn.discordapp.com/attachments/526402563847880725/812756440200249376/Screenshot_1.png
https://cdn.discordapp.com/attachments/526402563847880725/812756885212102666/unknown.png

**Cmi Version (using`/cmi version`): 8.8.1.3

**Server Type (Spigot/Paperspigot/etc): Paperspigot

**Server Version (using `/ver`):** git-Paper-469 1.16.5

**Relevant plugins (Delete if this isn't needed):

**Comment by Zrips** [comment]
You might simply have permission node inherited from somewhere else which allows more homes. With next update you can use 
**/cmi haspermission [playerName] cmi.command.sethome.***
Which will output min and max values for this permission node. 
Did some testing and it seam to work properly when player has permission node for 1 home. So if you still have same issue after testing it with next update, please open new ticket, for now closing this one.

**Comment by Mcdikmen** [comment]
It's solved, so thank u. :)
