### ISSUE TITLE
Player prefix isn't used by weight {prefix}

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5128]
**Description of issue:**

---

Hi, I wanna report that prefix for ex. in AFK messages isn't used by weight. For ex. in Luckperms I have set:
![image](https://user-images.githubusercontent.com/18662086/108605689-19dba800-73b6-11eb-856d-7a0f16eb6532.png)

![image](https://user-images.githubusercontent.com/18662086/108605692-1e07c580-73b6-11eb-9e08-ec1ba2aaa3b5.png)

As you can see on the second image I have bigger weight in prefix but it uses weight of groups instead of weight of prefixes. Player has in chat TikToker, but in AFK message he has NEOVIP due to {prefix} placeholder.

---

**Cmi Version (using`/cmi version`):** 8.8.1.3

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 25

**Comment by Zrips** [comment]
In general CMI uses official API provided by LuckPerms which returns heaviest prefix.
And you have heavier prefix in first group even tho group is heavier in second image, so it seams that prefix is used by its weight and not by group. You might want to adjust that if you want to get correct prefix.
