### ISSUE TITLE
itemcmdata & /itemnbt values aren't copyable

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5130]
**Description of issue:**

---

Hi, I wanna report that these values aren't copyable, which can be useful when you need to get some datas to put it for ex. in configs etc

---

**Cmi Version (using`/cmi version`):** 8.8.1.3

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 25

**Comment by Zrips** [comment]
This is more like a feature request then bug report. But in any case, will add option to paste into chat selected line. Next update.
