### ISSUE TITLE
CMI Vanish doesn't support DiscordSRV list command

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5131]
**Description of issue:**

---

Hi, I wanna report that CMI vanish isn't respect in DiscordSRV, due to:

> there is, `vanished` metadata key
> but CMI probably doesn't use it

```
# DiscordChatChannelListCommandEnabled: whether the command is enabled
# DiscordChatChannelListCommandMessage: the command people can type to get the player list
# DiscordChatChannelListCommandExpiration: time in seconds until a sent player list message is automatically removed by the bot. set to 0 to disable expiration.
# DiscordChatChannelListCommandExpirationDeleteRequest: whether or not to delete the message of the person that originally requested for the player list
#
DiscordChatChannelListCommandEnabled: true
DiscordChatChannelListCommandMessage: "/list"
DiscordChatChannelListCommandExpiration: 10
DiscordChatChannelListCommandExpirationDeleteRequest: true
```

Could you please support it? Otherwise vanished users are visible in this list cmd :/

**Cmi Version (using`/cmi version`):** 8.8.1.3

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 25

**Comment by amarcais53** [comment]
@Zrips we need an updated it’s been almost 1 years since this has been reported is this is still actually a bug

**Comment by bobhenl** [comment]
yeah @Zrips , please, still waiting for it

**Comment by amarcais53** [comment]
@bobhenl this as been fixed on latest update , Zrips added the vanish metadata missing

**Comment by bobhenl** [comment]
Yeah, solved, thanks!
