### ISSUE TITLE
CMIArmorChangeEvent bug

### ISSUE THREAD

**Issue by P-JungMin** [Zrips/CMI#5133]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
(My native language is not English, so I used a translator. Please let me know if there is anything you don't understand.)
In survival mode, right-click with armor in hand, and if another plug-in cancels the event, the armor won't fit, but CMIArmorChangeEvent will work.

below is my code:
```
```java
	@EventHandler(priority = EventPriority.MONITOR)
	public void onArmorChangeEvent(CMIArmorChangeEvent e) {
		if(e.isCancelled()) return; //I tried 'ignoreCancelled', but it didn't work properly, so I changed it this way, but it was still the same.
		Player p = e.getPlayer();
		NBTTagCompound oldNBT = NBT.getNBT(e.getOldArmorPiece());
		NBTTagCompound newNBT = NBT.getNBT(e.getNewArmorPiece());
		if(oldNBT.hasKey(Const.BOOTS_SPEED)) {
			p.setWalkSpeed(0.2f);
		}
		if(newNBT.hasKey(Const.BOOTS_SPEED)) {
			p.setWalkSpeed(0.2f*newNBT.getFloat(Const.BOOTS_SPEED));
		}
	}
```
---

**Cmi Version (using`/cmi version`): 8.8.0.7** 

**Server Type (Spigot/Paperspigot/etc): PaperSpigot** 

**Server Version (using `/ver`): git-Paper-1618 (MC: 1.12.2)** 

**Relevant plugins (Delete if this isn't needed): Speed Boots plugin (I made it for my server)**

**Comment by Zrips** [comment]
Will move CMIArmorChangeEvent into EventPriority.HIGH instead of being without set one which i think results into it being at normal or even lower than this. basic issue would be that plugin which cancels event does that after CMI checks for armor change event and its just bypasses that. Next update.
