### ISSUE TITLE
Invsave -> saved message string doesn't show right ID

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5139]
**Description of issue:**

---

**LANG SECTION (DELETE IF NOT RELEVANT):**
```
  InventorySave:
    info: '&8Info: &8[playerDisplayName]'
    saved: .... [id]
```
Hi, I wanna report that this section in language doesn't work as it should, as you can try /invsave <player>, then you won't see the right ID there. It wrote me ID 0, but it was saved with ID 12.

---

**Cmi Version (using`/cmi version`):** 8.8.1.3

**Server Type (Spigot/Paperspigot/etc):**  Yatopia

**Server Version (using `/ver`):** 25

**Comment by Zrips** [comment]
Should be fixed with next build
