### ISSUE TITLE
TPA issue

### ISSUE THREAD

**Issue by Jochyoua** [Zrips/CMI#5147]
**Description of issue:**
For some reason, players are not getting a response back when they execute tpa commands.
The target receives a prompt as normal, but the executor doesn't receive any messages at all.
**Cmi Version (using`/cmi version`):** 
8.8.1.4
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-484 1.16.5

**Comment by Zrips** [comment]
What do you have set for tpa command in your locale under requestSent section?

**Comment by Jochyoua** [comment]
It's occupied with "!prefix! &7Request sent to &3[playerDisplayName]"

**Comment by Zrips** [comment]
You might want to reset this line by removing it entirely and let it regenerate. Tho it should not really effect anything. Testing without any other plugin could help out too in determining what causes this issue.

**Comment by Jochyoua** [comment]
Thank you :)
I whipped up a fresh server install and it seems that the issue isn't present with that install but for some reason it does it on one of my servers even though I have no other chat-alternating plugins with the same configurations between any of them. Is there any config option that would allow tpa requests but not receive messages? This happens to both OP and non-op players

**Comment by Zrips** [comment]
Issues like that need to be tested on your end by ether disabling plugins until issue is resolved, so we atleast will know which plugin interferes or trying to reset all config files of CMI to make sure that its issue with configuration from CMI.

**Comment by Jochyoua** [comment]
I completely forgot about this issue, I'll do some testing later on
