### ISSUE TITLE
ctellraw missing <Next> 

### ISSUE THREAD

**Issue by w41k3r26** [Zrips/CMI#5151]
**Description of issue:**
The command `ctellraw` is failing to use <Next> . I want to be able to make announcements with ctell raw and schedules but due to lack of <Next>, I am having to use multiple lines of ctellraw which makes the text look very illogical.

---

**Cmi Version (using`/cmi version`): 8.8.1.4** 

**Server Type (Spigot/Paperspigot/etc): Yatopia** 

**Server Version (using `/ver`):1.16.5**

**Comment by Zrips** [comment]
Dont know what you mean exactly with "look very illogical" but in general you dont need to use <Next> to add multiple text sections, thing like this **/cmi ctellraw Zrips <T>text\n</T><H>Hover</H><T>text2</T>** produces 2 lines where one has hover over and second is in second like without hover. I need exact example you are using and what results you are getting

**Comment by CloudeLecaw** [comment]
<next> is mostly just usefull if u want to design a book in ctext
