### ISSUE TITLE
&l, &n, &k, &m in /glow

### ISSUE THREAD

**Issue by iBuseWinner** [Zrips/CMI#5154]
**Description of issue:**
Players can use &l, &n, &o, &m, &k in /glow <color> command
![image](https://user-images.githubusercontent.com/44753872/108885162-82c25a80-7618-11eb-8a84-e5919ba01640.png)
![image](https://user-images.githubusercontent.com/44753872/108885251-a1285600-7618-11eb-8167-ac11118d621e.png)

---

**Cmi Version (using`/cmi version`):** 
8.8.1.3

**Server Type (Spigot/Paperspigot/etc):** 
Yatopia

**Server Version (using `/ver`):** 
1.16.5

**Relevant plugins (Delete if this isn't needed):**
TAB by _Neznamy_ & PAPI (%cmi_user_glow_code%)

**Comment by Zrips** [comment]
Good point. Will be fixed with next update.
