### ISSUE TITLE
Jail does'nt working.

### ISSUE THREAD

**Issue by Mcdikmen** [Zrips/CMI#5155]
**Description of issue:**
I am trying to jail somebody but it gives me this error: "The player doesn't jailed. Look at the target's jail name"
https://imgur.com/fpSr1HD
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```


**Cmi Version (using`/cmi version`):** 8.8.1.4

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.16.5

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Have you created jail with /cmi jailedit command?

**Comment by Mcdikmen** [comment]
Yes, i have 2 jails. Created by wooden shovel. Tried both of them but not working.

https://imgur.com/XfLAAjg

**Comment by Zrips** [comment]
You still need to add cells to each jail. Every jail needs to have atleast one cell where players will get put when they are jailed, when jail itself is just a grouping of those cells for purposes like preventing player from leaving jail area but players can be placed in different cells.

**Comment by Mcdikmen** [comment]
I uploaded a video about this bug:

https://youtu.be/zuqyHrttAvs

**Comment by Zrips** [comment]
You added more jails, you need to add cells. When you have jail list **/cmi jailedit** then click on a jail, it will open another window where you can define actual cells. It will basically output message like
![image](https://user-images.githubusercontent.com/10416201/109013541-f9646400-76bb-11eb-9581-04d6c62e6660.png)
and then you simply need to stand inside jail area and click on [+] which will create new cell and you will have it looking like
![image](https://user-images.githubusercontent.com/10416201/109013636-0f722480-76bc-11eb-8091-b670aee2e94b.png)
after that you can add more cells to the jail, as many as you want. And then when you do /jailist it will indicate how many cells each jail has and how many people are jailed in that jail. 
You simply miss understood that you are creating jails and not jail cells, as we can have unlimited amount of jails which can contain unlimited amount of cells.

**Comment by Mcdikmen** [comment]
Oh, i got it. I am so sorry about taking your time. Yours faithfully, have a nice day. :)
