### ISSUE TITLE
Gradient bug?

### ISSUE THREAD

**Issue by Zuixik** [Zrips/CMI#5158]
Hi, 
I have a problem with the grantient. When I make a gradient and I want it to be bold, it doesn't work.

Screenshots:
![image](https://user-images.githubusercontent.com/61326124/108938358-3d218400-7650-11eb-8544-6683ac6ece79.png)
![image](https://user-images.githubusercontent.com/61326124/108938404-50345400-7650-11eb-8797-c9edde118649.png)

**Comment by Zuixik** [comment]
For the TAB plugin, the gradient works in bold
![image](https://user-images.githubusercontent.com/61326124/108938696-dd77a880-7650-11eb-9e0e-dfd93f1fe597.png)

**Comment by Zrips** [comment]
Updating code to properly support this one with next build
![image](https://user-images.githubusercontent.com/10416201/109004687-c2895080-76b1-11eb-9e68-18d5ccf32973.png)
