### ISSUE TITLE
Placeholder for showing if there are 2 users from same IP

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5164]
Hi, I wanna suggest placeholder that will show us if there are 2 users online from same IP. Or if they have ban. I would like to use this mark in my tab list.

**Comment by AZFire1** [comment]
There's literally a warning that tells you to post feature requests in https://github.com/Zrips/CMI/discussions

I know you did not miss it cause you deleted it... You're feature request will get deleted if you do not move it there, this is not the place for feature requests. It is strictly for bugs. @bobhenl
