### ISSUE TITLE
Right shift click editing + NoCheatPlus

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5166]
**Description of issue:**

---

Hi, when my players use right shift click to edit, they can't edit lines properly due to nocheatplus. Author of this plugin told me to report it to you.

https://streamable.com/clshd0
https://streamable.com/wilp3r

---

**Cmi Version (using`/cmi version`):** 8.8.1.5

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 25

**Comment by CloudeLecaw** [comment]
looks like your protection allowed signedit in this area ;)
If not action is cancelt

**Comment by bobhenl** [comment]
I have residence plugin and it's residence of this player.

**Comment by CloudeLecaw** [comment]
but if its anticheat that is causing this, then normaly the anticheat dev should handle here...

there a lot of anticheat plugins its a bit to much to write compatibility to all of them.
Better way would be if anticheat fixed it.
With just CMI signs work fine.

**Comment by bobhenl** [comment]
their reply was 
![image](https://user-images.githubusercontent.com/18662086/109173161-d4d3bf00-7783-11eb-9041-0164b15a4a0d.png)

And yes, it happens only with CMI cause it's  the feature of CMI. So IDK. But I can disable this check maybe, this cheat isn't probably used very often.

**Comment by Zrips** [comment]
Should be resolved with next version.
