### ISSUE TITLE
Adding of Level 0 Enchant

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5172]
At the moment using Level 0 removes an Enchant from an Item.
I wanne add a Lure Level 0 Enchantmant to an Item.

Why? i found out that some plugins that let items glow
simply give their item a enchant level 0 (lure mostly) and simply hide the enchant after to have a glowing item..

So it it possible to add a Level 0 enchantment? Maybe Ownname or Lure 0?
Problem is: accually CMI does not allow adding a level 0 enchantment.
with the give command it would be possible... `{Enchantments:[{id:lure,lvl:0}],HideFlags:1}`
but with enchant it issnt at the moment.
At the moment when i use Level 0 at an item enchantment with the cmi enchantment command then the enchantment got removed from item...

![Snag_853016a](https://user-images.githubusercontent.com/12080017/109219472-f484da80-77b7-11eb-8d37-106f4b843e34.png)  ![Snag_85429ad](https://user-images.githubusercontent.com/12080017/109219631-21d18880-77b8-11eb-9278-7193370f6574.png)

![Snag_853802f](https://user-images.githubusercontent.com/12080017/109219556-0797aa80-77b8-11eb-8c33-d97d8a8ca6d4.png)  ![Snag_853c98c](https://user-images.githubusercontent.com/12080017/109219589-12ead600-77b8-11eb-81f8-bf13d2003419.png)

![Snag_854c3ab](https://user-images.githubusercontent.com/12080017/109219701-39a90c80-77b8-11eb-89e6-966a1f826f24.png)  ![Snag_8553fe0](https://user-images.githubusercontent.com/12080017/109219750-4cbbdc80-77b8-11eb-9369-b7e012ca304b.png)

**Comment by AZFire1** [comment]
Clever ^^, I'd want this feature so I could have commands like "/itemglow on/off" which don't effect anything on the item. :)

**Comment by CloudeLecaw** [comment]
Its allways done by giving an enchantant and hide it,

Some plugins managed it to give a lvl 0 enchant on it
with cmi you can gave a worthlesss enchant like Lure 1 and hide it with the hideflags command.

but still lvl 0 would be nicer

**Comment by CloudeLecaw** [comment]
moved to discussions
