### ISSUE TITLE
New Placeholder

### ISSUE THREAD

**Issue by roy0510** [Zrips/CMI#5173]
Hello, I hope you are well,
I want to send this suggestion, which is to create a new placeholder **%cmi_user_rank_displayname%**" that serves to detect the `Displayname` of the `ranks` and another that detects the `Name`

since currently when using **%cmi_user_rank%** it does not detect the `Displayname` (_which would be a custom name_).

> For name rank: **%cmi_user_rank%** 
> For Displayname rank **%cmi_user_rank_displayname%**

_I do not know if currently there will be said placeholder, and in "https://www.zrips.net/cmi/placeholders/" I have not got more_

Thanks in advance.

**Comment by AZFire1** [comment]
This already exists..... There are:
%cmi_user_rank_name% - %cmi_user_rank% (show name)
%cmi_user_rank_displayname% (show displayname)
