### ISSUE TITLE
custom NBT support for kits

### ISSUE THREAD

**Issue by iTzVirtual00** [Zrips/CMI#5177]
It would be useful to have support for custom NBT in kits. For example:
`/minecraft:give @s minecraft:diamond_sword{mynbt:"{USERNAME}"}`

When a player request the kit that nbt will become `mynbt:"playername"`.
Thanks.

**Comment by Zrips** [comment]
Use commands section in kit editor and add command like 
`asConsole! cmi give [playerName] diamond_sword {mynbt:"[playerName]"}`
