### ISSUE TITLE
Prewards Resets After system Restart.

### ISSUE THREAD

**Issue by red0fireus** [Zrips/CMI#5178]
**Description of issue:**

Prewards resets after a server restart. Not sure if this is an intentional feature but It seems like a bug to me.

I created a reward that rewards players every 48 hours. There playtime counter goes down and works but after a server restart the time goes back to 48 hours. 

It's basically impossible to complete because I have an automatic server restart every night.

---

**Cmi Version (using`/cmi version`):** 

CMI: 8.8.1.5 SqLite

**Server Type (Spigot/Paperspigot/etc):** 

Yatopia 1.16.5

**Server Version (using `/ver`):** 

1.16.5

**Comment by Zrips** [comment]
Should be resolved with next build
