### ISSUE TITLE
problems with pex

### ISSUE THREAD

**Issue by pinuxio** [Zrips/CMI#5179]
hi, I have a problem in the file permissions I added the following permissions to a category:

    **- cmi.command.gm.creative
    - cmi.command.gm.spectator
    - cmi.command.gm.survival
    - cmi.command.gm.adventure**

but they say they don't have permits. how do i solve?

**Comment by CloudeLecaw** [comment]
U forgot cmi.command.gm

**Comment by Zrips** [comment]
If users have **cmi.permisiononerror** then you can always check exact missing permission node when hovering over error message. but in general you are missing **cmi.command.gm** and in case you want to set some ones else game mode you will need **cmi.command.gm.others.[gameMode]**

**Comment by pinuxio** [comment]
so cmi.command.gm should be put the same?

**Comment by CloudeLecaw** [comment]
u got it
