### ISSUE TITLE
Private chatroom invites

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#5180]
**Description of issue:**
When inviting a player to a private chat room, the target player can't join the room.

Problem 1:
This player got an invitation and clicks on the message.
So the player has an invite and still CMI says that the player can't join because the invite was missing

Problem 2:
The invited player sees his own name in the message:
`TargetPlayer123 invites you to join chat room: Secret`
As if he invites himself.
The player who send the invite sees the correct message:
`Invited TargetPlayer123 to join chat room: Secret

**How to reproduce:**
Player_1 executes:
1. /cmi chat create Secrete -private
2. /cmi chat invite Player_2 Secret

Player_2:
1. receives message: `Player_2 invites you to join chat room: Secret`
2. Clicks on this
3. receives message: `Chat room is private and you don't have invitation
4. by clicking on the invite, the console shows `Player_2 issued server command: /cmi chat join Secret`. If this was accepted, anyone could entered a private room by just typing this without a proper invite.

---

**Cmi Version (using`/cmi version`):** 
CMI 8.8.1.5

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.5

**Comment by Zrips** [comment]
Will be fixed with next build
