### ISSUE TITLE
Sign bold

### ISSUE THREAD

**Issue by Zuixik** [Zrips/CMI#5181]
Good day,

It is not possible to write on the sign in bold with a gradient.
![image](https://user-images.githubusercontent.com/61326124/109365059-90821500-7890-11eb-85bb-69ffe6896469.png)

**Comment by CloudeLecaw** [comment]
It is?
first use the granient then use &l on last row

**Comment by Zuixik** [comment]
![image](https://user-images.githubusercontent.com/61326124/109367851-8ca5c100-7897-11eb-9879-00f01c0e1feb.png)

**Comment by Zuixik** [comment]
In chat

**Comment by Zuixik** [comment]
![image](https://user-images.githubusercontent.com/61326124/109367886-a47d4500-7897-11eb-9f7d-4587082e7bac.png)

It works just fine in the chat, but not on the signs

**Comment by CloudeLecaw** [comment]
Problem seeems your server

![Snag_e1bf522](https://user-images.githubusercontent.com/12080017/109368587-edce9400-7899-11eb-80cf-06b34ecaf231.png)

**Comment by Zuixik** [comment]
Very sorry.
I didn't realize I had an old version :/
