### ISSUE TITLE
riptide is working when using /pweather rain

### ISSUE THREAD

**Issue by MCLimited** [Zrips/CMI#5182]
**Trident with riptide works with /pweather rain:**

When it's not raining you are not able to use riptide in the air.
![sun](https://user-images.githubusercontent.com/18746382/109378482-3bb3be00-78d3-11eb-8afe-31a64f4d1cb5.png)

Pweather is for player based weather and not for the whole server. When someone does /pweather rain (so the personal weather), the player is able to use riptide enchantment while its not actually raining.

![rain](https://user-images.githubusercontent.com/18746382/109378513-74ec2e00-78d3-11eb-80f2-abbdeeb03aae.png)

**Cmi Version (using`/cmi version`): 8.8.1.5** 

**Server Type (Spigot/Paperspigot/etc): paperspigot** 

**Server Version (using `/ver`): 1.16.4 - 411**

**Comment by Zrips** [comment]
Its a "bug" with minecraft itself and currently there is no reasonable fix for it. Riptide is allowed when player is in rainy situation independent if its server side or only player side, while at same time when its on player side appropriate riptide event is not fired so we have no real means to detect this action to block it.
