### ISSUE TITLE
launch command bug with the -noDamage flag

### ISSUE THREAD

**Issue by we67iop** [Zrips/CMI#5183]
Description of issue: the Launch command, when used with the -noDamage flag will cause the player to have their next fall damage event cancelled if they land in water

Steps to reproduce the bug: use the launch command with the -noDamage flag, make sure you land in water, then swim back to land, tower up in the air and jump off, you won't take damage.

**Cmi Version (using`/cmi version`): 8.8.1.5** 

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): git-Paper-"3dadd97bb"**

**Comment by Zrips** [comment]
Should be fixed with next build
