### ISSUE TITLE
Attached commands !limiteduse:[amount]! on stackable items useses reset bug

### ISSUE THREAD

**Issue by we67iop** [Zrips/CMI#5184]
**Description of issue: When using attached commands on a stackable item, if you have two of those items with the attached command and the same number of uses, you are able to fully use 1 item in the stack, at which point the 2nd item in the stack will have its uses reset to its original amount**

Steps to reproduce: Attach a command to a stackable item and give it any amount of uses, get two of the item you just made, use them both so they have some uses missing and are both on the same amount of uses left(else they aren't stackable), then stack them, then use up all the uses on one of the items, the left over item in the stack will have its uses reset to the original amount that you set when you made the item. 

Cmi Version (using/cmi version): 8.8.1.5

Server Type (Spigot/Paperspigot/etc): Paper

Server Version (using /ver): git-Paper-"3dadd97bb"

**Comment by Zrips** [comment]
Good point. Will fix with next update.
