### ISSUE TITLE
moneyLog: duplicate entries

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#5187]
Description of issue:
moneyLog files contain duplicate entries for transactions caused by ChestShop. You tried to fix this issue once in version 8.8.0.7 but the issue still occurs.

Excerpt:

```
28/02/21 00:00:09 BarSerkr got 20,14 CT (13.623.401,46 CT)
28/02/21 00:00:09 BarSerkr got 20,14 CT (13.623.401,46 CT)
28/02/21 00:00:29 BarSerkr got 40,27 CT (13.623.441,73 CT)
28/02/21 00:00:29 BarSerkr got 40,27 CT (13.623.441,73 CT)
28/02/21 00:00:49 BarSerkr got 120,82 CT (13.623.562,55 CT)
28/02/21 00:00:49 BarSerkr got 120,82 CT (13.623.562,55 CT)
28/02/21 00:01:09 BarSerkr got 241,64 CT (13.623.804,19 CT)
28/02/21 00:01:09 BarSerkr got 241,64 CT (13.623.804,19 CT)
28/02/21 00:01:29 BarSerkr got 120,82 CT (13.623.925,01 CT)
28/02/21 00:01:29 BarSerkr got 120,82 CT (13.623.925,01 CT)
28/02/21 00:01:49 BarSerkr got 241,64 CT (13.624.166,64 CT)
28/02/21 00:01:49 BarSerkr got 241,64 CT (13.624.166,64 CT)

```
As you can see, entries are just duplicates (total amount of a player only changes each 2nd entry).

Cmi Version (using/cmi version): 8.8.1.5

Server Type (Spigot/Paperspigot/etc): Paperspigot

Server Version (using /ver): git-Paper-466 (MC: 1.16.5)

Relevant plugins (Delete if this isn't needed): ChestShop version 3.12-SNAPSHOT (build 274)

**Comment by Zrips** [comment]
Will make extra change for this one, should resolve it, fingers crossed

**Comment by TheoRetisch1** [comment]
The issue is resolved! Thank you very much 👍
