### ISSUE TITLE
Grouped kit cooldown bug

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#519]
Grouped kits apply cooldown to all kits. E.g. if there is a group of kits called builder and I click use a kit. The cooldown I receive is for all kits in that group.

**Comment by CloudeLecaw** [comment]
awwww Thank you LogGits, i reported this Problem also a Long time ago but never got a solution.
Thanks for marking this now as a bug <3

**Comment by LogGits** [comment]
@CloudeLecaw Cheers for letting me know 👍

Closed as relates to 244.
