### ISSUE TITLE
Tabcomplete placeholders not working

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#5199]
**Description of issue:**
The command tppos usually tab completes coordinates and worlds.
This is broken since CMI 8.8.1.3
It now shows the words: `currentx, currenty, currentz, worlds currentpitch, currentyaw`
![Screenshot_CMI_playerholders](https://user-images.githubusercontent.com/28690790/109484898-48761480-7a81-11eb-8f05-d4f667293183.png)
Instead of how it used to be:
![Screenshot_CMI_playerholders2](https://user-images.githubusercontent.com/28690790/109485638-35177900-7a82-11eb-9bbd-c5d299277cf9.png)

---

**Cmi Version (using`/cmi version`):** 
CMI 8.8.1.3 and higher

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.5

**Comment by Zrips** [comment]
Gets a fix with next build. Switched to new tabcomplete handling and forgot to change actual variable format for it to work as it should...
