### ISSUE TITLE
Attached commands issue with !right!

### ISSUE THREAD

**Issue by we67iop** [Zrips/CMI#5200]
When I make an attached command item using this command `/cmi attachcommand !cooldown:5!;;!limiteduse:0!;;!right!!cc! _attachTOOLBOX [playerName]` right click uses the item as expected however left click doesn't use the item, but still puts it on cooldown. Pressing Q drops 1 item in the stack and put the the item on cooldown. 

Is this a bug or am I doing something wrong

**Comment by Zrips** [comment]
You need to specific where you want to apply cooldown, for this case it should look like 
`/cmi attachcommand !right!!cooldown:5!;;!limiteduse:0!;;!right!!cc! _attachTOOLBOX [playerName]`
