### ISSUE TITLE
Money log - empty values (0 money)

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5202]
Hi, this is OK that in log is shown this (when player doesn't get any money, it just shows 0?
27/02/21 13:49:28 cracule got 0,00 ⛃ (176.438,63 ⛃)
27/02/21 13:49:28 cracule got 0,00 ⛃ (176.438,63 ⛃)
27/02/21 13:49:32 cracule got 0,00 ⛃ (176.438,63 ⛃)
27/02/21 13:49:32 cracule got 0,00 ⛃ (176.438,63 ⛃)

**Comment by Zrips** [comment]
This can be rounded up value where player received tiny amounts which dint changed general look of it but still got like 0.000001 or something similar

**Comment by bobhenl** [comment]
Even when player is offline?
