### ISSUE TITLE
/tgod grants invincibility after taking damage, even when it's off.

### ISSUE THREAD

**Issue by Crysillion** [Zrips/CMI#5203]
Using CMI.

If you give a player /tgod, let's say for all of 5 seconds, they'll be in godmode for 5 seconds. Great!

If that player then takes damage from a mob, lava, or anything at all when /tgod expires (at any point after it expires), they become immune to damage. Running /god and /tgod shows them as having neither active, but they still can't take damage. Only relogging fixes it.

Upon me not using /tgod anymore, this issue never ever happened again, so it's 100% that command being bugged.

**Comment by Zrips** [comment]
Will be fixed with next build
