### ISSUE TITLE
Tree Feller and Mirroring Crash

### ISSUE THREAD

**Issue by TheNylox** [Zrips/CMI#5206]
Hello i have a problem. If someone try to use "Three Feller", mcmmo skill, with Mirror Activated it crash the server

Console Errors : https://pastebin.com/8vcHhCBJ (and more of this for a total of 20k error lines)
Ingame Error : https://cdn.discordapp.com/attachments/526402563847880725/816302031148023808/unknown.png

Cmi version : 8.8.1.0

Tuinity 1.16.3 

Relevant Plugins: CMI, mcmmo

**Comment by Zrips** [comment]
Confirmed. Should be fixed with next build
