### ISSUE TITLE
CMI chat format repeated reply after updating the latest paper

### ISSUE THREAD

**Issue by vc606** [Zrips/CMI#5207]
**Description of issue:**
After updating to the latest version of the paper, cmi chat will repeat the speech. Lowering it back to paper-470 is normal. It may be that the Paperspigot has changed something.

**Cmi Version (using`/cmi version`):** 8.8.1.5

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** r paper-1.16.5-507

**Comment by MiniDigger** [comment]
This was introduced in paper-507, we are currently looking at fixing it

**Comment by Zrips** [comment]
@vc606 
For time being go back to 506 version. Its ether gets fixed with next paper builds or I will have to rework chat system to make it work with new chat system paper introduced in 507. In any case, thanks for pointing this out, we are looking into it.

**Comment by JRoy** [comment]
fixed in https://github.com/PaperMC/Paper/commit/60e92c061b01295a4ef2b21272de75bd6a33f11b
