### ISSUE TITLE
Please add support WorldGuard Extra Flags

### ISSUE THREAD

**Issue by Fiks75** [Zrips/CMI#521]
When there is a flag in the region godmode : DENY, the god mode is not disabled. Please add support plugin [WorldGuard Extra Flags](https://www.spigotmc.org/resources/worldguard-extra-flags.4823/)

CMI plugin version: 7.8.3.0
Server version: Spigot 1.12.2-R0.1-SNAPSHOT
Vault version: 1.5.6-b49
CraftBukkit version git-Spigot-2086bb0-8cc5a7e

**Comment by CloudeLecaw** [comment]
may i am wrong, but this does not Sound like what CMI should be handeled for.

For example: I use RedProtect and if i deny Godmode there then it is disabled even if CMI handles the Godmode normaly.
Have u asked in the Worldgaurd Extra Flags discussion for supports CMIs Godmode?...

**Comment by Fiks75** [comment]
Yes. CMI not support Worldgaurd Extra Flags, specifically Godmode.

**Comment by CloudeLecaw** [comment]
why it should? Worldguard Extra Flags would need Support for CMI then, not the other way..

**Comment by Zrips** [comment]
@Fiks75 
CMI only changes game mode on particular actions, like performing command or changing world. So are those players teleporting from one world to another and you have settup forced game mode for particular worlds?

**Comment by CloudeLecaw** [comment]
so it still sounds like a Problem of your rotection Plugin, worldgauird in that case.

i made an example with my protection Plugin
In RedProtect i let Server commads execute on Region Enter that enbale godmode and fly and + clear inventory and on leaf disable godmode, fly

worked fine. i entered my Region,  got godmode, fly and inventory got cleared
i left the Region, and godmode got disabled and fly too

so it more seems to be a Problem of your Protection Plugin that is does noit work ;)
may there is also a Worldguard Solution for executing command (as console or Server), i havent used Worldguard a Long time.

**Comment by MCTyler** [comment]
Different Plugin @CloudeLecaw Look at this https://www.spigotmc.org/resources/worldguard-extra-flags.4823/
