### ISSUE TITLE
Fall damage consumes a Flight Charge.

### ISSUE THREAD

**Issue by Crysillion** [Zrips/CMI#5212]
Title pretty much explains it. If I jump off a cliff (not flying at any point!) and take fall damage, it deducts a Flight Charge.

**Comment by Zrips** [comment]
Check config file FlightCharge->DeductOnFallMulti and set it to 0 if you want to disable this. Tho I would recommend to leave it at some value just to avoid abuse of it by players having free no fall damage bypass if they have a single flight charge. Just a recommendation.
