### ISSUE TITLE
Color codes and placeholders do not load correctly

### ISSUE THREAD

**Issue by Hazugg** [Zrips/CMI#5214]
with cmi update 8.8.1.6, they are showing message from the labels, apparently they are not handling well the color codes and the "placeholder" labels on the console and within the game I have validated that the color codes are not display correctly, only for elements that had already been generated

![image](https://user-images.githubusercontent.com/31551514/109858070-5f576b00-7c29-11eb-9d68-2886beae446b.png)

**Comment by CloudeLecaw** [comment]
you better should pst the line of your langfile too

**Comment by Zrips** [comment]
@Hazugg 
Retest with latest CMI and paper builds as there was issue with paper failing to properly handle hex color codes. Should be resolved now
