### ISSUE TITLE
CustomRecipes - BUG

### ISSUE THREAD

**Issue by Adreez** [Zrips/CMI#5215]
**Description of issue:**
Hello i found bug in CMI with making custom crafting recipes. I was created new recipe with custom named items(Lore + Name) if i was saved the recipe and opened it again items with custom names renamed to basic minecraft items. Then i was think what can happend this bug i was trying customrecipe in workbench but items instead of that have customname i can use air or vanilla item but item that has been in crafting output has name, lore and everything. I was trying this bug on my official mc server and later i was trying this bug on my private pl testing server and same thing.

This was my recipe:
![image](https://user-images.githubusercontent.com/78606862/109861977-34d4d480-7c60-11eb-8aea-38bc1e9bbdd6.png)
![image](https://user-images.githubusercontent.com/78606862/109862006-3bfbe280-7c60-11eb-934f-14d1737ff726.png)

This is what happend after updating recipe:
![image](https://user-images.githubusercontent.com/78606862/109862120-58981a80-7c60-11eb-8eab-2be19b68fe8f.png)
![image](https://user-images.githubusercontent.com/78606862/109862133-5e8dfb80-7c60-11eb-83f6-60dab5b07041.png)

In workbench:
![image](https://user-images.githubusercontent.com/78606862/109862838-318e1880-7c61-11eb-9e5f-68f04ade0a0d.png)

Sorry for this "low-budget" description and photos but i didn´t have too much time to write this ticket.

I didn´t found any error messages.

**Cmi Version (using`/cmi version`):**
8.8.1.5
8.8.1.6

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):**
![image](https://user-images.githubusercontent.com/78606862/109861556-b5df9c00-7c5f-11eb-81ee-691d1f417178.png)
![image](https://user-images.githubusercontent.com/78606862/109861121-3d78db00-7c5f-11eb-923e-de17e5f3074e.png)

**Comment by CloudeLecaw** [comment]
Z cant use midified itens as materials. These become Vanilla Version of it after saving the recipe. This is notna bug its a Missing Feature

**Comment by Zrips** [comment]
Not a bug, this is limitation of Minecraft recipe handling
