### ISSUE TITLE
WorldLimits – fly is taken from residences in worlds which aren't listed here

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5216]
**Description of issue:**

---

Hi, I have problem that I use player worlds plugin and I have so many worlds that I can't list here. Now there's problem when someone has residence and has there allowed fly and players go there... and there's set fly to true... then they teleport outside of residence (to world which isn't listed here, BTW when you disable world limits and teleport from this residence you can fly outside of it too.... which is weird and I think it's not how it should behave) and they can fly... 

My suggestion on solution is somehow solve, why is residence fly persisting for players which don't have ANY CMI fly permission... when they teleport outside of residence where's fly flag allowed, OR add way to allow here usage of default:True/False -> for setting it for all other worlds - defaultly, and then change it for the worlds listed below.

But I think the first solution may be better, but both of them could be implemented.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  # If player will have cmi.worldlimit.fly.bypass permission node, fly mode wont be changed
  Fly:
  - world:False
  - SurvivalSpawn:False
  - MiningWorld:False
  - BossLand:False
```

---

**Cmi Version (using`/cmi version`):** 8.8.1.6

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 25

**Relevant plugins (Delete if this isn't needed):** Residences, PlayerWorldsPro (isn't necessary, cause if you disable worldlimits and teleport outside of residence with fly tag enabled, then you can fly outside of it too...)

Just btw it isn't needed to use PlayerWorldsPro plugin, I think that you can create new world that wouldn't be listed here and then teleport there from residence and you could fly...

**Comment by Zrips** [comment]
Resolved with latest residence build
