### ISSUE TITLE
Useage of ptarget

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5217]
Could u give me some hints and suggestions why and when its usefull to use parget?

Example:

```
  givemoney:
    Cmds:
    - ptarget:$1! asConsole! money give $1 %cmi_random_40_300%
```
and
```
  givemoney2:
    Cmds:
    - asConsole! money give $1 %cmi_random_40_300%
```

in both cases a "thrid" persin would write /givemoney NAME or /givemoney NAME    - in both cases NAME would be $1 and the result would be the same...

so why it is usefull and specialy when? to use this ptarget:$1! ? :3
If the player does not need to use his name what is different to [playerName] then?

**Comment by Zrips** [comment]
Answered in discord
