### ISSUE TITLE
The permissions doesn´t work with ultrapermissions

### ISSUE THREAD

**Issue by Skyfighter1** [Zrips/CMI#522]
**Description of issue or feature request:**
Hey my Problem is that the permissions doesn´t work with my permissions plugn ultrapermissions. The only permission which work is cmi.* or cmi* ....

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):**

**Comment by Skyfighter1** [comment]
What can I do?

**Comment by TheWranger** [comment]
1. Put in what your versions are.
2. Link to ultrapermissions to make it easier for Zrips to fix
3. Wait for a fix?

**Comment by Zrips** [comment]
@Skyfighter1 
Server version, CMI version, Ultraperm version
