### ISSUE TITLE
Players can use Trident Riptide when they have /pweather toggled to rain

### ISSUE THREAD

**Issue by KarlPro123** [Zrips/CMI#5220]
**Description of issue:**

Hey. We found that when players have their pweather set to rain, they can use the trident with riptide enchantments to jump with it, but its not actually raining. Is it possible to fix this somehow?

**Cmi Version (using`/cmi version`):** 

8.8.16

**Server Type (Spigot/Paperspigot/etc):** 

Paper 

**Server Version (using `/ver`):** 

v457 Paper

**Comment by AZFire1** [comment]
Can't be fixed. Please close this issue, and just scroll through the recent closed issue, this has been reported many times before..
