### ISSUE TITLE
Custom alias with two words?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5221]
Hi, I wanted to create this alias but it overwrite whole /res (residence) command... so players can't use then /res create etc. from some reason. Any idea why?

```
  res chat:
    Cmds:
    - asPlayer! residence rc
```

Also i've tried this 

```
  warp spawn:
    Cmds:
    - asPlayer! spawn
```

and it doesn't work neither...

**Comment by CloudeLecaw** [comment]
all right here whats the problem? ;)
We also ue many many custom alias with a extra vrabiale.
they are also tab complete :-)

**Comment by Zrips** [comment]
@bobhenl 
Everything seam to work as it should. Tried your example with residence plugin and its properly redirects to /residence rc when performing /res chat while keeping rest of the residence commands in working order. Without your actual custom alias file cant really say whats going on exactly, but it does seam to work correctly
