### ISSUE TITLE
Player prefix isn't used by weight {prefix}

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5226]
**Description of issue:**

---

Hi, I'm reopening ticket https://github.com/Zrips/CMI/issues/5128 cause I asked on LP Discord and there should be everything OK with luckperms.

I've tried /papi parse Testers %luckperms_prefix%
![image](https://user-images.githubusercontent.com/18662086/110080211-7497db00-7d8a-11eb-8545-a09e3bcfccb9.png)

then I've tried /placeholderapi parse Testers %cmi_user_prefix%
![image](https://user-images.githubusercontent.com/18662086/110080282-85485100-7d8a-11eb-956b-f736e963d11e.png)

Then when you look to LP editor it seems everything to beright:
TikToker group:
![image](https://user-images.githubusercontent.com/18662086/110080603-f7209a80-7d8a-11eb-8fa6-646192faa06f.png)
![image](https://user-images.githubusercontent.com/18662086/110080689-1b7c7700-7d8b-11eb-85b9-4875319c4b04.png)

NEOVIP  (different prefix) group:
![image](https://user-images.githubusercontent.com/18662086/110080636-01db2f80-7d8b-11eb-8046-93c722ff26c3.png)
![image](https://user-images.githubusercontent.com/18662086/110080664-0dc6f180-7d8b-11eb-96ef-1857ae509ba2.png)

Got responses by authors:

> then LP is being correct
> idk what CMI is doing to display it wrong

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
I've tried using prefix in autoafk and there it is wrong.
```
  AutoAfkCmds:
  - cmi broadcast !&7*[&e☽&7] {prefix} [playerDisplayName] je AFK.
```
![image](https://user-images.githubusercontent.com/18662086/110080980-89c13980-7d8b-11eb-92c9-0354544226e9.png)

If I use this:
```
  AutoAfkCmds:
  - cmi broadcast !&7*[&e☽&7] {cmi_user_prefix} [playerDisplayName] je AFK.
```

It works then:
![image](https://user-images.githubusercontent.com/18662086/110080988-8b8afd00-7d8b-11eb-97d0-ccf927487234.png)

---

**Cmi Version (using`/cmi version`):** 8.8.1.7

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 25

**Relevant plugins (Delete if this isn't needed):** LuckPerms

**Comment by Zrips** [comment]
i'm lost here. Your command examples for afk should utilize actual placeholders, which plugin translates {prefix} variable? As that one isint from CMI as it should have been [prefix] or better %cmi_user_prefix%
Try parsing that placeholder with /cmi placeholders parse {prefix}
which will output message with indication which plugin actual translated it, well atleast indication if it was CMI or PAPI. 
Did some testing, everything seam to work as it should, tried to change weights and tested with papi parser and with CMI, values are returned same across the board.

**Comment by bobhenl** [comment]
![image](https://user-images.githubusercontent.com/18662086/110212162-59b48c00-7e9a-11eb-8b23-3384fddf6731.png)


![image](https://user-images.githubusercontent.com/18662086/110212164-5a4d2280-7e9a-11eb-8e90-8cec6975f88d.png)


![image](https://user-images.githubusercontent.com/18662086/110212165-5b7e4f80-7e9a-11eb-944e-39b06b3b33e7.png)

**Comment by Zrips** [comment]
resolved
