### ISSUE TITLE
Billboards won't work correctly with CMI plugin.

### ISSUE THREAD

**Issue by smartmadio** [Zrips/CMI#5228]
I have Billboards ,Vault and CMI plugin installed on my server.

When I rent a billboard and try to snake and place a sign on billboard to change the content of it, nothing happened.But when I disabled CMI plugin, the billboard will work correctly.Seems there's a bug with it.

Hope it could be fixed ,thanks :)

Server version: paperspigot 1.16.5
CMI version: 8.8.1.5
Billboards version: v2.3.1

```
Modules.yml:
dynamicSigns: false
```

---

**Cmi Version:** 8.8.1.5

**Server Type:** Paperspigot

**Server Version:** 1.16.5

**Relevant plugins:** Billboards v2.3.1

**Comment by smartmadio** [comment]
This's billboards' author's reply, hopes this issus could be solved.Thanks:)

> I am not familiar with CMI. But from the feature list at their plugin page, they seem to have a feature called 'self updating signs'. There may also be other sign related features. Maybe their implementation of these features conflict with Billboards. However, CMI is closed source, so I can't check if this is the case, or what exactly the conflict is here.

My current guess is that maybe the CMI plugin forcefully cancels the interaction or block placement of the sign. The Billboards plugin relies on the sign being placed, so that Minecraft opens the sign editor for the player. The Billboards plugin already tries to enforce that the sign for editing a billboard is getting placed (for example to override protection plugins such as WorldGuard). But plugins may still be able to forcefully prevent this sign from getting placed. Maybe this is what is happening here.

 

But without access to CMI's source code I can't look into the issue or propose any solutions for how to best resolve this incompatibility. Your best bet is to contact the autors of the CMI plugin to look into the issue. If the issue actually is about forcefully preventing the sign placement, maybe they can be less strict about that, or limit it to specific signs only.

**Comment by Zrips** [comment]
I need exact link to the plugin for testing as there are bunch of Billboard plugins and one i found is only meant for 1.15 and lower. Might be that one. On top of that i need actual way to reproduce this issue with actual actions i need to take as i'm not familiar with that plugin how it works or even what it should do and when

**Comment by smartmadio** [comment]
Thanks!

**Billboards' link:** https://dev.bukkit.org/projects/billboards/issues

Steps to reproduce this issue:

1. Build a server using PaperSpigot 1.16.5 with Billboards ,Vault and CMI plugin (enable CMI economy feature).
2. Put a sign on the wall.
3. Pointing at the sign and use '/billboards' command to set the sign as a billboards sign.
4. Take a sign in hand.
5. Snake and put sign on the billboards sign.
6. Type words in the sign.
7. If billboards could work correctly,the words on billboards sign should change to what you have typed in step 6.

**Comment by Zrips** [comment]
Och ok, its an issue with sign edit interfering with this billboards attempt to modify text on sign. Will make small change to resolve this one.
