### ISSUE TITLE
change color

### ISSUE THREAD

**Issue by pinuxio** [Zrips/CMI#5230]
hi, i would like to change the color of the suffix and text for each group, does it exist with cmi?

**Comment by Zrips** [comment]
If talk goes about chat message handling then you will need to check config file under chat section. There is option to define different formats depending on players permission node

**Comment by pinuxio** [comment]
which part exactly?

**Comment by pinuxio** [comment]
I've been trying for 4 days but the result doesn't change

**Comment by pinuxio** [comment]
> Se si parla di gestione dei messaggi di chat, sarà necessario controllare il file di configurazione nella sezione chat. È possibile definire diversi formati a seconda del nodo di autorizzazione dei giocatori

I've been trying for 4 days but the result doesn't change
