### ISSUE TITLE
EventCommand [playerKill] and [playerDeath] result in double triggers

### ISSUE THREAD

**Issue by jiajunmao** [Zrips/CMI#5231]
hey, this should be a simple feature request. Is it possible to make the playerDeath not being triggered if it is a playerKill event?

**Comment by Zrips** [comment]
Playerdeath event should be fired every time player dies. While playerKillPlayer event is fired when one player kills another player. So in general both events needs to be fired. What i could do, at best, is to add SourceCommands for playerDeath which would be fired only when player was killed by player, this by itself can allow you to use only playerDeath event and simply add **check:[playerName]!=NULL!** for commands to only trigger when player died from none player and SourceCommands will only trigger when there is player killer
