### ISSUE TITLE
Non-Existant Home triggers command cooldown 

### ISSUE THREAD

**Issue by kronusdev** [Zrips/CMI#5240]
**Description of issue:**
I have set a cooldown on the use of /home and one of my players tried to use it on a home that didn't exist and it triggered the cooldown even though he didn't teleport. I don't see anything relevant in the config that would have prevented this.

---

**Cmi Version (using`/cmi version`):** 8.8.1.7

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** 967

**Comment by CloudeLecaw** [comment]
could you post your cooldown from config?

**Comment by Zrips** [comment]
Will make some general adjustments to avoid opening home UI if you provided home name which is incorrect. In general when wrong name is provided then we open home UI, but that one should not have triggered cooldown. In any case, new approach will prevent situations like this in future.
