### ISSUE TITLE
Custom alias with spaces aren't in tab completion?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5243]
**Description of issue:**

---

Hi, I wanna report that when you make command in custom alias with space, then it's not added to tab completion, at least when it's some other plugin command, like Residence.
![image](https://user-images.githubusercontent.com/18662086/110226605-1cc7b400-7ef1-11eb-8b50-0afb953c5c8a.png)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  res chat:
    Cmds:
    - residence:res rc
  res ?:
    Cmds:
    - residence:res $1-
```
Tried without res ?, also tried with asPlayer! at the beginning of both etc.

---

**Cmi Version (using`/cmi version`):** 8.8.2.0

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 25

**Comment by Zrips** [comment]
Should have been fixed with latest version
