### ISSUE TITLE
/chat doesn't work

### ISSUE THREAD

**Issue by iBuseWinner** [Zrips/CMI#5245]
**Description of issue:**
When I write /chat, I get help for this command.
When I write /chat [playerName/off] (for e.g. /chat Player1), I get help for this command.
When I write /cmi chat, I get tip: create, list, listrooms, etc
![image](https://user-images.githubusercontent.com/44753872/110241411-a31bde80-7f61-11eb-98ec-13d8e7e2e07c.png)

So this command doesn't work.

Or I need to use CMI Chat?
![image](https://user-images.githubusercontent.com/44753872/110241467-fa21b380-7f61-11eb-8b97-82e09948f66f.png)

---

**Cmi Version (using`/cmi version`):** 
8.8.1.3

**Server Type (Spigot/Paperspigot/etc):** 
Yatopia (also tested paper)

**Server Version (using `/ver`):** 
git-Yatopia-1.16.5-33

**Comment by CloudeLecaw** [comment]
Cmis chat feature is for CMIs Chat. u got it. if u dont use u also cant use its chat features
(colors, chattooms, etc) the command works fine u need to use like u see it in your tab completation /cmi chat Argument (playernname/chatroom  u find these all in the wiki. so all fine here. if u dont work with CMis chat and chatrooms u can disable the command in alias.yml too

**Comment by Zrips** [comment]
@iBuseWinner 
You will need to use defined sub commands to create chat room before joining it with correct format. Its not a one general chat where everyone talks to everyone, its separate chat room for anyone who has permission to create chat rooms. Creates personal spaces for smaller groups to talk with each other.

**Comment by iBuseWinner** [comment]
Ow, maybe it was old language...

Now it works. Thank you!

**Comment by CloudeLecaw** [comment]
may u where affected by the currption of some lang strings.. this happend abit longer time ago.
but not everyone noticed because not everyone uses all cmi commands ;)
