### ISSUE TITLE
Ctext doesn't accept right all arguments?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5246]
**Description of issue:**

---
Hi, I wanna report that not all arguments used in command are replaced in ctext. Some of them are, as you can see the first line of message was replaced, but not all of them. The next second aren't. I will give you screenshot + my example

**CTEXT (using nextpages):**
```
<T>&c&lEventy &f» &f1. výherci eventu[&e$1&f] &e$2 &fjsi dal &e%cmi_random_1_7%. &fze &e7 &fodměn.</T> -> number 5
<NextPage>
<T>&c&lEventy &f» &fHráč &e$2 &fvyhrál &fevent &e$1 &fa získal &enáhodnou odměnu&f! Účastni se příště taky!</T><H>&cKlikni pro informace o eventech.</H><SC>/eventy</SC> -> number 3
<NextPage>
<T>&c&lEventy &f» &fZa &evýhru &fv eventu[&e$1&f] jsi získal &enáhodnou odměnu&f!</T><H>&eDěkujeme za účast!</H -> number 4
```

Custom alias example:
Just btw, usage of the command: /eventrewardeasier [event] [firstWinner|X] <secondwinner|X> <thirdWinner|x>, now I used just /eventrewardeasier event firstwinner
![image](https://user-images.githubusercontent.com/18662086/110242456-934acd00-7f56-11eb-8f7d-da2c89f8de33.png)
```
    - check:$2!=x! asConsole! allPlayers! cmi ctext prikazy [allPlayers] 3 -> this may don't work due to all players
    - check:$2!=x! ifonline:$2?! asConsole! cmi ctext prikazy $2 4 -> but why this doesn't work, if number 5 works?
    - check:$2!=x! ifoffline:$2?! asConsole! mail send $2 &c&lEventy &f» &fZa &evýhru
      &fv eventu[&e$1&f] jsi získal &enáhodnou odměnu&f!
    - check:$3!=null! check:$3!=x! asConsole! cmi ctext prikazy [playerName] 5
```

FUll custom alias code of this alias: https://pastebin.com/nJnzjLdB

So the problem is that when using arguments they didn't get everytime replaced from some reason...

---

**Cmi Version (using`/cmi version`):** 8.8.2.0

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 25

**Comment by Zrips** [comment]
Give me your ctext file

**Comment by Zrips** [comment]
Ok, so whats going on here is that first line is a result of command being performed and message is sent to player and we are replacing variables as they should be, while rest of the messages comes from ctext command which doesn't process it properly as ctext doesn't support variable like that translation. Solution would be to change 
`    - check:$2!=x! asConsole! allPlayers! cmi ctext prikazy [allPlayers] 3`
into
```
    - check:$2!=x! asConsole! cmi ctellraw all <T>&c&lEventy &f» &fHráč &e$2 &fvyhrál
      &fevent &e$1 &fa získal &enáhodnou odměnu&f! Účastni se příště taky!</T><H>&cKlikni
      pro informace o eventech.</H><SC>/eventy</SC>
```
in this case we will properly replace variables with provided ones and it will be shown to all users

**Comment by bobhenl** [comment]
I wanted to change ctellraw to ctexts like we discussed here https://github.com/Zrips/CMI/issues/5136.

But as mentioned I was confused that the first message was replaced even if it's ctext too.
![image](https://user-images.githubusercontent.com/18662086/110798051-0ebfbd80-827a-11eb-8a4f-7af0e08a9981.png)

```
<T>&c&lEventy &f» &f1. výherci eventu[&e$1&f] &e$2 &fjsi dal &e%cmi_random_1_7%. &fze &e7 &fodměn.</T> -> number 5
<NextPage> -> text in ctext
    - check:$3!=null! check:$3!=x! asConsole! cmi ctext prikazy [playerName] 5 -> text in custom alias, and it works here
```
