### ISSUE TITLE
Could you please translate the game into Slovak please?

### ISSUE THREAD

**Issue by PLASTAR2748** [Zrips/CMI#5247]
Could you please translate the game into Slovak please?

**Comment by CloudeLecaw** [comment]
Did u know that users translated the other language too?
You want it slovak? Then translate it on your own.
create a copy of the original EN File inside the translation folder called Locale_EN-yml
![image](https://user-images.githubusercontent.com/12080017/110291822-9ee8d300-7fec-11eb-803a-c55a213d2d2d.png)
rename it to Locale_SL.yml

trans translating the file-
if you finished copy it into the translation folder.
it would be nice if you send your Slovak translation to Zrips. then he can add it into the official CMI version for others.
Niote: Thats the way how all translation where integrated into current CMI Version.
Dont asspect from the dev to translate into your language on its own.
Help the community and start translating :-)

**Comment by Zrips** [comment]
@PLASTAR2748 
Translations are done by people who actually knows how to properly translate it. I could simply run it through automatic google translate, but that will produce some weird outcomes at best.
And just FYI we do have SK type translation which as i know is Slovakian one, you can check it here 
https://github.com/Zrips/CMI/blob/master/Translations/Locale_SK.yml
it will be downloaded automatically on first plugin run and then you can use it by changing EN into SK in your config file.
