### ISSUE TITLE
Problem with teleports, lagging

### ISSUE THREAD

**Issue by naikyy** [Zrips/CMI#5251]
Hello, I wanted to ask, if its possible that CMI is lagging my server, when I startup the server after a crash and instantly like about 50 players join the server, they can't teleport to home, they can't /spawn, they can't /warp, /back. Sometimes they can but they are teleported after random time like I feel its buggy or lagging. 

Anyways, TPS are stable: 20, tick durations about 40-200ms, nothing bad and timings are not good, I would be happy if you can tell me whats wrong because im sad, that its lagging when im using very good dedicated server with optimazitions and plugins are lagging it.

Timings report: https://timings.pl3x.net/?id=a698283452104a2887383cf42230bd2e#timings

Server version: Purpur, latest dev
CMI: Latest

**Comment by Zrips** [comment]
Where are those teleport target locations actually located at? As it might be that server needs to load in entire world before teleporting player to it if target location is located in unloaded map or some custom one. In general teleportations are done in async, atleast latest stage of it to minimize possible load on server.

**Comment by naikyy** [comment]
Its usually location like homes, farms or places that players already visited. But if the server is loaded after crash the places are not loaded I think but what can you do, like yeah, load the entire map after restart to make teleports smooth but thats unreal.
