### ISSUE TITLE
Portal Command on Missing Permission

### ISSUE THREAD

**Issue by jiajunmao** [Zrips/CMI#5254]
Hey, just wondering that it is possible to add a feature where I can define a set of commands to be executed upon denial entry to a portal for missing a permission node. Currently all portal share the same deny message and it would be great if we can customize deny command for each custom portal (send a cmi ctext, teleport elsewhere, etc., etc.)

**Comment by CloudeLecaw** [comment]
you can costumize the executes command by asking if player has permission for it before starting a command.
