### ISSUE TITLE
Teleport on lava when using /rt

### ISSUE THREAD

**Issue by borjxrroyo** [Zrips/CMI#5260]
**Description of issue or feature request:** Teleport on lava when using /rt

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://i.gyazo.com/243588ec52ce59c5e94d4e3d4586e2ec.png

```

**Cmi Version (using`/cmi version`):** 8.8.1.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.16.5

**Comment by borjxrroyo** [comment]
I would like to suggest having more active staff on Discord, I know that people have their things to do, but almost always I ask I don't get a response because they're busy or afk.

**Comment by CloudeLecaw** [comment]
Have u set safeteleport permission?

**Comment by Zrips** [comment]
@borjxrroyo 
Need more information on this one. What settings are you using for random teleportation? Does it ignore lava blocks? Was this in regular nether world?

**Comment by borjxrroyo** [comment]
I used IgnoreWater: true and IgnoreLava: true. And yes, that occured in a regular nether world.

**Comment by borjxrroyo** [comment]
> Have u set safeteleport permission?
> 
> > cmi.safeteleport – Prevents teleportation to unsafe locations

Maybe the issue is due to that?

**Comment by CloudeLecaw** [comment]
give it a try :-)

**Comment by borjxrroyo** [comment]
Doesn't work

**Comment by Zrips** [comment]
Should be fixed with next version
