### ISSUE TITLE
Permission not working: cmi.cooldown.[some_command].[timer]

### ISSUE THREAD

**Issue by regix1** [Zrips/CMI#5262]
I'm using Lucky Permissions. The list of my commands are below that need a cooldown.
List:
  - cmi home :5

If I add the permission node: cmi.cooldown.cmi_home_.30 to a group the cooldown is still 5 seconds.

**Comment by CloudeLecaw** [comment]
U need to set 30 and give yourself a permission of 5

**Comment by red0fireus** [comment]
That makes so much more sense, thank you.

I feel that should be explained in the config file better. I was so confused

**Comment by CloudeLecaw** [comment]
your absolutly right about that. It should be a line in the cooldown description in the config file.
