### ISSUE TITLE
0,00 values in money log multiple times per player with same final value

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5266]
**Description of issue:**

---

Money log: https://pastebin.com/SNNQRqPu

Try to search for:` Renzotom got 0,00 ⛃ (407.381,03 ⛃)` -> **6 times**, exactly same value there.... Why should there be logged 0,00 even if it's 0,00005? But I don't know for what I could get these moneys.... I really don't have any idea, but maybe you could add there like minimal value or something like that, but I think this is necessary to log.

And when you search for:
![image](https://user-images.githubusercontent.com/18662086/110932542-f019ff00-832b-11eb-89da-a93ab729853f.png)
There's really so much values there.

And this is the most weird... `cracule got 0,00 ⛃ (306.438,63 ⛃)` -  ### 9 times, and player wasn't even online!
```
seen cracule
[12:11:11 INFO]: ~Craculka je Neaktivní už 20 dnů 14 hod 4 min 16 sek !
```
**He isn't active for 20 days, 14 hours**... and it's logged there everyday.... Why? **Why there's logged something for user that isn't online and earn just 0,00?** And I don't even know for what he earns it.

---

**Cmi Version (using`/cmi version`):** 8.8.2.2

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 33

**Comment by Zrips** [comment]
Its been rounded. If you got 0.000002 its still a transaction which gets recorded and final balance could take some time to change. Not recording them could be an option, but at same time its better to know if there are bunch of tiny transactions, after all, its still a  transaction caused by some plugin.
