### ISSUE TITLE
Moneys get lost after crash from some reason

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5267]
**Description of issue:**

---

Money log: https://pastebin.com/SNNQRqPu

Player lost money here from some reason and it isn't logged (probably due to server crash, but this shouldn't happen...):

This is from the log exactly how it goes after:

```
12/03/21 10:53:22 VojtaanoBook lost 0,00 ⛃ (54.065,69 ⛃)
12/03/21 11:30:38 VojtaanoBook got 52,00 ⛃ (4.674,50 ⛃)
```

Here's crash log (due to specialized crates - bug already fixed [2021-03-12-9.log.gz](https://github.com/Zrips/CMI/files/6129581/2021-03-12-9.log.gz), sorry it's file due to large file

And here's actual log after crash (sorry again file):
[latest.zip](https://github.com/Zrips/CMI/files/6129598/latest.zip)

So you can check where the money disappeared... Hopefully just for this player and not for all of them.

---

**Cmi Version (using`/cmi version`):** 8.8.2.2

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 35

**Comment by Zrips** [comment]
There is slight delay between transaction and new data being saved into database. Logs are recorded straight away as its using completely different method which is allot simpler in a sense that its only adding new entry at end of file, which is fast. While player data gets recorded into actual database and that gets slight delay to batch actions and avoid performing multiple updates in a second which can happen with some of the plugins dealing with income. Your best solution would be to lower save delay, but in case of server crash something might be rolled back in any case.
