### ISSUE TITLE
You can't login from this ip address

### ISSUE THREAD

**Issue by dragon12a** [Zrips/CMI#5270]
Hello,
I had no problem with anything so far, but today one player send me this connection error:

Kicked whilst connecting to csurvival: You can't login from this ip address.

I tried to find the problem but I can't really find it,. The only thing I found was something about CMI with /lockip on GitHub about this problem, but that wasn't the issue. At least what I tried.. I would really appreciate any help.

**Comment by Zrips** [comment]
Try using **/lockip [playrName] clear** this should clear any ip locks if player set it accidentally.

**Comment by Zrips** [comment]
Try using **/lockip [playrName] clear** this should clear any ip locks if player set it accidentally.
