### ISSUE TITLE
TotalUsers does not reset with Database deletion?

### ISSUE THREAD

**Issue by Skizzles** [Zrips/CMI#5271]
**Description of issue:**
When fully deleting the CMI database on a specific mode, the totalusers does not change instead it just adds onto the count for each rejoined player that was deleted.
---
https://screenshots.skizzles.me/wAnA3/cowIgasa92.png

**Cmi Version (using`/cmi version`):**  8.8.2.2

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** 1.16.5

**Comment by CloudeLecaw** [comment]
Have u spezified that playerfiles should be deleted to with correct path name?
If u just deletbthe database - have u Setup that information nare taking from playerfiles?
Also you might use other plugins (also your permission system) that stores data of the players?

Removing them from cmi database is limited
Ro cmi database or cmi database + their playerfiles.
For all other plugins that store Informationen you need to do this seperatly if needed.
