### ISSUE TITLE
Broken Armorstand Gravitation

### ISSUE THREAD

**Issue by mare-on** [Zrips/CMI#5276]
**ISSUE:**
Gravity flag for armorstand is not working. Armorstand is levitating in both cases when gravity is disabled or enabled.

**ERROR:**

Enabled Gravitation:
![gravity](https://user-images.githubusercontent.com/16023709/111030671-d9df7200-8403-11eb-8a16-11a6e96b6c5e.png)

Levitating Armorrstand:
![levitate](https://user-images.githubusercontent.com/16023709/111030651-c502de80-8403-11eb-88bf-0cafa853afe1.png)

**CMI VERSION:** 8.8.2.2

**SERVER TYPE:** Paper

**SERVER VERSION:** 1.16.5-b470

**Comment by Zrips** [comment]
Armor stand has "interactable" disabled, which by itself makes armor stand skip any physics checks. You should have button under gravity if you have access to it, if not then you will need some one with access to that button to enable interaction and it will drop down.
