### ISSUE TITLE
/se doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#5277]
**Description of issue:**
The command `/se [SignLine] [Text] ` doesn't work under the [Paper Adventure System](https://github.com/PaperMC/Paper/pull/5289). Nothing happens when you try to edit a sign: There is no chat output, the sign doesn't change and there is no error in the log.

---

**Cmi Version (using`/cmi version`):** 
CMI 8.8.2.2
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-547 (MC: 1.16.5)

**Comment by CloudeLecaw** [comment]
Have u enabled it in alais.yml? Else use /cmi se

**Comment by TheoRetisch1** [comment]
Yeah I enabled it in the _Alias.yml_. I used the command for at least one year. It just broke after updating to the new Paper Adventure system. 
```
  /se:
    Enabled: true
    Tab: true
```

**Comment by Momshroom** [comment]
I'm having the same issue.  /se broke for us recently after working for years.
I'm using Paper 546 and CMI 8.8.2.2, but it's been broken for us for a few versions.

**Comment by arturek1666** [comment]
I can confirm the /se don't work, well the /se 1 (text) works but /se 2 or /se 3 /se 4 don't :(

**Comment by TheoRetisch1** [comment]
Confirmed for version 8.8.2.3 :/

**Comment by Zrips** [comment]
Confirmed. Will be fixed with next version.
