### ISSUE TITLE
Make /enchant better and a Bug with hex names

### ISSUE THREAD

**Issue by b01w** [Zrips/CMI#5279]
What Ive written to the dev of ecoenchants which uses your plugin to enchant items using /enchant:

Currently when using CMI, it reads the "Name:" in the yml as the enchant name, but could you add an option in the config to make it only read the yml's file name since I have added hangul lettering which uses custom icons, and I cant just simply find the 5000 letters in the hangul alphabet to enchant my pickaxe, so would be amazing to make it only use the yml file name if you could toggle it in the main config that would be amazing!

He has replied that I would need to ask for enchantment keys since when I try to enchant a pickaxe with curse of decay, since I have resource pack symbols I cant just enchant with "curse_decay" I have to type out the whole enchantment. So could you possibly add it so I dont have to?

https://cdn.discordapp.com/attachments/736919111807795252/820369772365479966/unknown.png
https://cdn.discordapp.com/attachments/736919111807795252/820369876496941116/unknown.png

**Comment by b01w** [comment]
Whenever you use hex coloured enchantments with ecoenchants, since cmi has to convert those hex colours into the weird text letter such as "§" whenever you want to /enchant with that letter it then kicks you for "Illegal characters in chat" meaning you cant enchant anything with that custom enchant since you just get kicked.

**Comment by b01w** [comment]
Auxilor says that CMI needs to add a feature to use enchantment keys instead of using the names for them since with ecoenchants it uses hex colours and when cmi converts it you get kicked when you type it in.

**Comment by Zrips** [comment]
Enchant names should not contain any special characters in any case. Enchant name should be purely made of A-Z characters

**Comment by Zrips** [comment]
Will make a fix to accept enchants like that, but again, its a bad practice to include special characters into enchant name which gets used internally in a code which never was made to handle names like that. As long as it works it should work.
