### ISSUE TITLE
[Request] Double doors

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#528]
When a player right clicks a double set of wooden doors, they both open or close at the same time.
Both doors have to be made of the same material and the both have to be placed so that the handles are sitting next to each other.
![image](https://user-images.githubusercontent.com/24642838/41771622-1622c494-7659-11e8-8e43-d64707d7ef23.png)

**Comment by CloudeLecaw** [comment]
is this the part of CMI?, 
My used protect plugin "RedProted" has this Option in it.
There it is a flag called "smart.door"

> smart-door: 
> Allow players with door or build permissions to open iron doors/trapdoors without redstone, and open all types of doors as double doors.

**Comment by MCTyler** [comment]
So Does LWC which I'm sure Op is aware of.

**Comment by LogGits** [comment]
This is beyond the scope of the project and as mentioned can be achieved by many plugins including but not limited to: https://www.spigotmc.org/resources/auto-door-closer-and-opener-1-12-x-1-13-2.44093/
