### ISSUE TITLE
Can't join with another name...

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5280]
**Description of issue:**

---

Hi, my players cannot join to server (today at the morning) due to this message:
![image](https://user-images.githubusercontent.com/18662086/111043072-e2a26900-8440-11eb-811d-22a2c8419bde.png)
```
  cantLoginWithDifCap: '&cCan''t login with different name capitalization! Old name:
    &e[oldName]&c. Current: &e[currentName]'
```
Look there, there are two different names, it's not just capitalization...

And it happened to multiple players...

+ two players had same name in tab & chat, but the first one was named differently normally and when he was sent to another server it got fixed. (double user ProchynQa)
![image](https://user-images.githubusercontent.com/18662086/111043126-357c2080-8441-11eb-9f71-d535991837b3.png)

```
  # When set to true players with same name but different capitalization will be denyied from joining server to avoid possible issues. In example if on first day player Zrips joined server and on second day player zRips tries to join server, he will be rejected
  # RECOMMENDED to keep this at true
  PreventDifferentCapitalizationNames: true
```

---

**Cmi Version (using`/cmi version`):** 8.8.2.2

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 33

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Should get resolved with next build
