### ISSUE TITLE
Shulkerbox backpack perk active, can't place shulker boxes using shift + right click

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#5285]
**Description of issue:**
When you have the shulkerbox backpack permission, you are unable to place shulker boxes using shift + right click.

Could this be a toggle for players to turn on and off?

**Cmi Version (using`/cmi version`):** 8.8.2.2

**Server Type (Spigot/Paperspigot/etc):** Tuinity 1.16.5-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Well good point in general, will make small adjustment to only open shulkerbackpack when you click air and not another block
