### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by pinuxio** [Zrips/CMI#5286]
hi, I wanted to put the repair all command to a group, what permissions should I give since it doesn't work with cmi.command.repair?

**Comment by CloudeLecaw** [comment]
U have to give them
Cmi.command
Cmi.command.repair
And cmi.command.repair.all ?

Next time pls check you console first.
There you see missing permissions.
Also you can use the cmi hasepermission command

Cmi hasperm [player] cmi repair all
Then u get a responce what permissions the player needs.
