### ISSUE TITLE
[Issue] Sign copying

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#529]
When using /cmi sc, it copies the sign that is standing in front of you, not the one you are looking at.

Paperspigot 1466
CMI 7.8.5.0

**Comment by Zrips** [comment]
Its takes first sign block in direction you are looking. Its just behavior of block finder. Allot more complicated algorithm should be implemented to get exact block you are looking at

**Comment by TheWranger** [comment]
@Zrips If that's the case, why don't you rework how sign copying is handled so it works like this:
Command is used
Playing clicks the sign they want to copy

Instead of copying the sign that the player is looking at.
