### ISSUE TITLE
problem with /shoot

### ISSUE THREAD

**Issue by vkolasa** [Zrips/CMI#5293]
**Description of issue or feature request:**

When you shoot a trident with /shoot it makes a valid trident that can be picked up.

/shoot does not have Tab options for commands while /shootarrow DOES have tab options, no matter what you choose it will always shoot an arrow.

**Cmi Version (using`/cmi version`):** 
8.8.2.0
**Server Type (Spigot/Paperspigot/etc):** 
paperspigot
**Server Version (using `/ver`):** 
paper470

**Comment by Zrips** [comment]
/shootarrow isint CMI command, atleast not a default one. So i need to know what custom alias you are using for it if its even from CMI in general. 
For tridents, i can add extra check to prevent their pickups
