### ISSUE TITLE
Disable chat module entirely

### ISSUE THREAD

**Issue by TGTGamer** [Zrips/CMI#5294]
**Description of issue:**

Unable to disable chat functions leading to duplication of messages. 

![image](https://user-images.githubusercontent.com/11413796/111462627-8d06de80-8716-11eb-8a3f-6a01091e20a4.png)

Disabled all plugins except the following and still got the error
```
CMI8.8.2.2
CMILib1.0.0.2
HeroChatPro
Vault-1.7.3
```
![image](https://user-images.githubusercontent.com/11413796/111462569-7e202c00-8716-11eb-89f5-bec03d5c1a0e.png)

![image](https://user-images.githubusercontent.com/11413796/111465033-7f9f2380-8719-11eb-97a9-575607b7bd09.png)

[latest.log](https://github.com/Zrips/CMI/files/6156118/latest.log)

Was discussed in discord - See messages: https://discord.com/channels/452792793631555594/526402563847880725/821679041089896448

**Comment by mrfloris** [comment]
CMI Config on discord was shared, it showed false, but /cmi version gave true as output. I've pointed out to /stop the server and set it to false, etc. and start it up. And to update paper, 553 is currently the latest. This apparently also didn't resolve it. 

I never use hero chat, i am 100% on cmi chat (though i did wish local, world, and global chat were a thing in cmi btw HINT HINT). But I can't test this, and real life is super hectic today as well. argh.

From what i gather on discord they've really done their best to try and disable cmi chat, and without cmi the double msgs go away. 

I've seen more people in the past report these double msgs, but they never follow up how they've resolved it.

**Comment by TGTGamer** [comment]
Chat Transcript. Closed:

```
Floris (afk this week) — Today at 12:12 PM
Thank you, i've linked zrips as well.
he's more capable of running an instance maybe with some debug msgs injected to see where it might come from. without hero chat it seems when i turn off cmi chat that VANILLA mojang chat is there.
i dont get double msgs, but i dunno what happens if i would install hero chat. (so that part doesn't help you)
when i turn on cmi chat, the vanilla chat goes away and i am left with cmi chat. for me this works. of course. (also doesn't help you, but .. it's the best i can test)
@TGTGamer In the cmi config.yml what is the value for:
ClickHoverMessages:
and
HoverItems:
under the chat: section

TGTGamer — Today at 12:17 PM
ClickHoverMessages: true
HoverItems: true

Floris (afk this week) — Today at 12:17 PM
Ah, okay. it might be best if you dont use cmi chat to leave these json things to off, /stop , set the false, save and start
see if clickhovermsgs to false will remove the duplicated
There are 2 options, one is to disable chat handling, which handles its format, and another is to create hoverover messages, which will convert existing chat message into hover over. If they disabled first one while keeping hoverover messages, that could caused some duplication [when using other chat apps that dont support cmi hoverover]. 

TGTGamer — Today at 12:26 PM
Yeah that seems to have solved it
Still a bug that it is applied even though chat is disabled

Floris (afk this week) — Today at 12:29 PM
One feature is to add hover over - other chat plugins could decide to utilize this, if they dont, it can cause duplication msgs yes. Glad we figured out which setting causes the problem. Maybe CMI will update in the future to better deal with this, and other plugins could perhaps support it if that's possible for them.
````
