### ISSUE TITLE
Invsee tab-complete not working right

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#5299]
**Description of issue:**
When I use /invsee it shows me a list of players, but once I type one letter the tab-complete stops.
![image](https://user-images.githubusercontent.com/5664135/111643611-61abee80-87ff-11eb-8c8d-e2a1e37081a8.png)
![image](https://user-images.githubusercontent.com/5664135/111643637-65d80c00-87ff-11eb-9877-89fb365c6d4b.png)

[15:34:26 INFO]: --------------------------------------------------
[15:34:26 INFO]: CMI: 8.8.2.2 BungeeCord  MySQL
[15:34:26 INFO]: CMILib: 1.0.0.2 
[15:34:26 INFO]: Server: Tuinity 1.16.5-R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment]
May because u used a b instead of a B?

**Comment by Sikatsu** [comment]
It happens even if I'd do it the right way, unfortunately

Op vr 19 mrt. 2021 15:08 schreef CloudeLecaw ***@***.***>:

**Comment by CloudeLecaw** [comment]
hmm seems like not all servers are effefect by this

![image](https://user-images.githubusercontent.com/12080017/111798397-52de3e00-88ca-11eb-86b8-547a88e2c430.png)

ass u can see all fine here

**Comment by Zrips** [comment]
It could be issue with Tuinity if they are doing some funky stuff with their tab complete

**Comment by Sikatsu** [comment]
According to spottedleaf they don't change that, nor do I have issues with tab complete with other plugins..

**Comment by Zrips** [comment]
@Sikatsu 
Do you have any other plugin on that server which could override tab complete for that command? As if its broken for on command then it should be broken for all of them, but if its only one single command then it could be another plugin overriding its behavior

**Comment by CloudeLecaw** [comment]
Have you checked this with spigot, your permission system + cmi , no other plugins and then the same Setup Just with your tunity? 
Its also could be that one of your plugins creates this behave..

**Comment by Sikatsu** [comment]
I do not have any plugin which has invsee features.

This issue occured after a recent CMI update that made changes to the tab completion system.

Will have to test later if needed. ^^

**Comment by Zrips** [comment]
Should be fixed
