### ISSUE TITLE
Issues after using cmi switchplayerdata

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/CMI#53]
hei I have transferred the data from my first account to the new account - unfortunately, something was somehow transferred that my current player is still regarded as the old account (name / nickname / surcename)

Thus, I can not use commands from CMD blocks with @p
because the game tells me: this player is offline

Player A: old account
Player B: New account

i use the command /cmi switchplayerdata PlayerA PlayerB

Now I want to play with PlayerB normal but the system tells me I am (erroneously) PlayerA

Have a CMD block set up with the following command

give @p 1 1
So at the push of a button, I should now get a stone. But since I'm not recognized because the system thinks I'm PlayerA nothing happens.

**Comment by Zrips** [comment]
Is both players have same name just different capitalisation?

**Comment by HomeLandingsDE** [comment]
All the same only the join-Date is Different

**Comment by Zrips** [comment]
you could try to use /cmi removeuser oldUUID to remove old user from database and its files. As currently you have 2 users with different UUID's but same names, as we have to add users by their name into cache by converting name to lowercase for faster search when we are looking by name. This causes issue when plugin finds user by name, but its not "correct" one.

**Comment by HomeLandingsDE** [comment]
seems to have worked - thanks
