### ISSUE TITLE
Skin issues based off of inital use

### ISSUE THREAD

**Issue by WarmasterCain55** [Zrips/CMI#530]
**Description of issue or feature request:**

Was told to reopen a new issue.
Just recapping - server was updated to the ver containing skin commands.  Tried it on myself, an alt, another player.  Since then, the skins becomes stuck.  Doing all the remove commands causes it to flash before returning.  Flushing out the skin cache will refresh the proper skin but i still have the same problem.  Here is a gif of it.

https://gfycat.com/MasculineRewardingIberianbarbel

**Cmi Version (using`/cmi version`):** 7.8.4.0

**Server Type (Spigot/Paperspigot/etc):** Paper 1.12

**Server Version (using `/ver`):** 1.12

**Comment by WarmasterCain55** [comment]
So I tried out the update command on a fresh server, nada and now the skin on that server is bugged.  Tbh i'm just getting tired of it.

**Comment by banit** [comment]
i have the same issue with the latest version. cant get rid of a skin of a player..

**Comment by Zrips** [comment]
Skins:
  SteveOnOff: true
