### ISSUE TITLE
Unbreakable disappear issue

### ISSUE THREAD

**Issue by YTRemRem** [Zrips/CMI#5300]
**Description of issue:**
When using /cmi unbreakable the item will first apply unbreakable and disappear after a few second

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
No error display in the console
```

---

**Cmi Version (using`/cmi version`):**  8.8.2.2

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** 1.16.5

Video: https://is.gd/ijxHys

**Comment by Zrips** [comment]
This looks more like you have another plugin which cleans items from specific enchantments which can include unbreakable one or you even have unbreakable enchant disabled with /disableenchant which then clears out enchants from items when you click on them
