### ISSUE TITLE
{DATE} placeholder

### ISSUE THREAD

**Issue by Stoniasawsome** [Zrips/CMI#5303]
Im having an issue with my kit items/custom items.
I use advancedenchantments to add custom enchants to my items then i hide the lore from those enchants so players cant see that those are on there. i made the whole set of custom items with custom enchants added unbreakable then hideflagged it.
i used the kiteditor and just dropped the item in after i made it. one example item looks like this.
![2021-03-18_14 23 26](https://user-images.githubusercontent.com/13128666/111677411-93b85300-87f5-11eb-905d-77bed3a3ddd6.png)

 I then realized there was no way to add a date and name placeholder to the item like this one has
cause i had dropped that item into the editor and didnt use a kit command to create the item. so i went to the kits yml and started looking for answers. i noticed that dropped items have different looking configs so i added a couple of fake lines of lore on a new item like this
![2021-03-18_13 55 38](https://user-images.githubusercontent.com/13128666/111677651-ccf0c300-87f5-11eb-8d81-556ebaaf80e8.png)
then i went back into that kit items config and tried changing "test" to have the [playerName] and %date/MM/dd/YY% (this is the placeholder ive found to work with kit commands) instead of saying test.
this is an example of a kit i use the %date/MM/dd/YY% in to get it to work.
![2021-03-18_13 53 34](https://user-images.githubusercontent.com/13128666/111678071-3ffa3980-87f6-11eb-93f4-596108ece56f.png)
this item does not have the special enchants attached to it tho cause i just made this with a cmi give command from within the kiteditor.
so anyways i changed that kit items lore i replace "test" with date and playername and this is what came out
![2021-03-18_10 36 19](https://user-images.githubusercontent.com/13128666/111678312-86e82f00-87f6-11eb-8e51-5d0843f9e611.png)
the [playerName] placeholder worked, but not the date. i tried many different things in that spot and nothing worked. i downloaded papi and tried a bunch of those time related placeholders and nothing worked.

so i went on your help chat and someone told me to try adding an attachedcommand so i tried that with this command
/cmi attachcommand !safelimiteduse:1!;;bperm:cmi.command.itemlore! cmi itemlore 6 [playerName];;bperm:cmi.command.itemlore! cmi itemlore 6 &a%date/MM/dd/YY%
(i tried several placeholders and different options like asFakeOp, and oping the player, ect) this still wont show the actual date because the "player" cant use this placeholder, only the console, and ive found that that date placeholder only works in a kit command (cmi give) and can only be run by the console. I tried making the item with a kit command adding the date, then adding attachedcommands but was quickly shut down by common sense. even if i make the item with the name and date by use of command, i have to attach commands to that item in hand so if i do that then all the items will have my name on it cause im the one who opened the kit to put the attachedcommands on the item. Just to be clear, theres NO other way besides the kiteditor command, cmi give. ive found that will produce a date like ive shown in my screenshots. i cant put that placeholder on the itemlore and stick it back in the editor only the playername works.
 

is there a "[Date]" placeholder for those items dropped into kiteditor that will work like %date/MM/dd/YY% does in my kiteditor commands. If not can we please have one of those?

i dont know if it matters but advancedenchantments uses the {player} placeholder like essentials.

**Comment by Zrips** [comment]
Well what i can do is simply parse placeholders in kits name or lore before giving them to the players which should resolve your issue and you will have most customizations you might want. Next update should properly parse them and you can use %server_time_MM/dd/YY% to avoid having PAPI for that same task.

**Comment by Stoniasawsome** [comment]
Awsome! Youre great
im also a fan of that /se fix that i hadnt reported yet

**Comment by Stoniasawsome** [comment]
thats gonna save me so much time, sanity, and effort. For that i donated a few bucks
