### ISSUE TITLE
Items do not drop when closing /anvil GUI with full inventory

### ISSUE THREAD

**Issue by Skizzles** [Zrips/CMI#5313]
**Description of issue:**
When a player is using /anvil, the items do not drop from the GUI if the menu is closed.
https://youtu.be/bAAkgy6yPes
---

**Cmi Version (using`/cmi version`):** 8.8.2.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.16.5

**Relevant plugins (Delete if this isn't needed):**
None

**Comment by Zrips** [comment]
Confirmed. Will be fixed with next version.
