### ISSUE TITLE
Offline Commands Issue

### ISSUE THREAD

**Issue by MasonKidder345** [Zrips/CMI#5322]
**Description of issue:**
Every time I try to do a command for an offline player like /cmi info <player> it doesn't give me an error it just tells me to do /cmi info <playername/UUID> so it won't work when I try to do it for players that are offline but works when I do it with players that are online. Same with cmi inv, cmi heal, cmi invcheck, and many more commands that are supposed to work offline. Also the offline commands do not work for some players

---

---

**Cmi Version (using`/cmi version`):**  8.8.2.3

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.16.5

**Comment by Zrips** [comment]
Could you check your player database and check FakeAccount column. What do you have them set to?

**Comment by MasonKidder345** [comment]
Player database for cmi? Where is that located by any chance?

**Comment by Zrips** [comment]
Is this applies to all players or only some of them? If only some, do you have PrioritizeOnlinePlayers enabled or disabled in your config file?

**Comment by MasonKidder345** [comment]
Uh to only some, and I have it as disabled. Do I enable it?

**Comment by Zrips** [comment]
Keep it disabled. I need to determine why its failing in your particular situation.
Is your server running offline mode? And if you have specific players on which commands are failing, do you have similar users in database? Maybe even duplicates which have same name but different name capitalization like Zrips and zRips ?

**Comment by MasonKidder345** [comment]
My server is online, I have like 5 total people (including me) that have logged onto that server and all the offline commands only work for two people in total and if you would like I can get more people on and just try the offline commands work for them as well. And for example when I do /cmi info to a player and it doesn't work in chat it just says "Usage: /info [playerName/uuid] * Show players information. When I do /tp to that player the command just doesn't work, doesn't give me anything in console or anything in chat I have used like their name with their capitalization and it still doesn't work. Also any offline command that you can do to a player to some work and some don't but when they get online those commands work for them and as soon as they log off it stops working for them, but no I do not have similar users in the database.

**Comment by MasonKidder345** [comment]
So also I had a new player join yesterday right and there's this player that when I would do /cmi info it wouldn't work  but now it does, and when I do it to the new player that joined and like a few others it doesn't work. So I don't know if this like information will help in anyway but I don't know what's causing this? Do you think maybe if I restarted the player data by deleting the cmi.sqlite.db ?

**Comment by MasonKidder345** [comment]
Ohhh I figured it out, so my main world I am using myworlds and the main world is "world" and according to the developer I can't really delete it but so I went to its playerdata it was empty probably because I deleted it sometime back then I teleported that player to the main world and they went offline and it works so I guess that was the issue. Thank you so much!
