### ISSUE TITLE
Invsave/DeathInv method doesnt save Armor (1.8.8)

### ISSUE THREAD

**Issue by iLoopBreak** [Zrips/CMI#5325]
**Description of issue:**
At least on 1.8.8 servers, the invsave method (involving /invsave, and death inventory saving) doesn't properly work as it doesn't save the armor. I guess it is wrong due to using a method which works on newer versions but doesnt return the whole inventory, not sure how what are you doing internally. I have tested with no plugins (Tested but wouldnt made sense if it had worked), and it still has the same problem.

---

![2021-03-22_18 05 00](https://user-images.githubusercontent.com/17530116/112029123-3136be00-8b39-11eb-9c5e-ab9bc50eb5cc.png)
![2021-03-22_18 05 06](https://user-images.githubusercontent.com/17530116/112029125-31cf5480-8b39-11eb-969b-859429185304.png)

---

**Cmi Version (using`/cmi version`):**  8.8.2.3

**Server Type (Spigot/Paperspigot/etc):** Paper (Tested on normal spigot jar too)

**Server Version (using `/ver`):** PaperSpigot-"4c7641d" (MC: 1.8.8)

**Comment by Zrips** [comment]
Should be resolved with next update
