### ISSUE TITLE
/armorstand command works in residences where players don't have permissions

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5326]
**Description of issue:**

---

Hi, I wanna report that players can use /armorstand command in Residences even when they don't have access to some flags. I had to allow them flag container, cause they need the container flag when they click on it to execute an action (for ex. I have an armor stand that teleports players to the wild), so they needed the container flag to be set to true. But now I discovered they can do /armorstand and they can edit armor stands there.... even when the container is set to false. But may check for another flag then container or allow command usage on click on armour stands without triggering container flag (so it could be still set to false and there won't be the message in chat).

---

**Cmi Version (using`/cmi version`):** 8.8.2.4

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** 1.16.5

**Relevant plugins (Delete if this isn't needed):** Residences

**Comment by Zrips** [comment]
Should be resolved
