### ISSUE TITLE
asPlayer! but with permissions?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5328]
Hi, how could I please let this work?
```
  role info ?:
    Cmds:
    - asFakeOp! lp user $1 parent info
```
It should work like you enter /role info <player_name> and it should execute by you command /lp user <player_name> parent info... but I need to execute it even when players don't normally have perms to /lp command. So any idea how to do it? I can't use asPlayer in this case.

And just btw... asFakeOp or asConsole is wrong cause it doesn't print the lp message to the player, but into the console.

**Comment by CloudeLecaw** [comment]
as fake OP does not work for that try this
Try to give him a timed permsision for the command.
```
  role info ?:
    Cmds:
    - perm:cmi.command.customalias.roleinfo#! asConsole! lp user $1 permission settemp luckperms.user.parent.info true 2
    - delay! 0.2
    - asPlayer! lp user $1 parent info
```
The command now get executed if someone has the permision `perm:cmi.command.customalias.roleinfo`
The command first gives him a timed permission for parent info for 2 secounds in first step
In The secound step is a short delay the so permission plugin has a bit time to register the adding of the new timed permission.
The thrid step it executing the parent info command,
The last lastep - > After 2 secouns he looses the permission to execute this command.

May your server is fast enough that you can reduce the time to one secound :)
