### ISSUE TITLE
Command to Open a Link for an other player

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5329]
When you enter a url in chat then you can klick it.
a window opens where u got asked if you want to open this link in your browser.

**Problem:**
The text must be "added" to chat and the player needs to cklick it first before he get this window. this looks a bit unprofessional special sometime if the link is the only think you want to give to the player. also some player dont understand that they need to klick it in chat.  (specially jungers)

What we would need is a command that shows this link window directly for other players.

There would be many many options to design nice things specialy with attached commands or with interactive and console.

Also this way players often dont need these unnicly looking "extra links in chat" just to get the Chaturl link to get the question if they wanne open it in their brower.

**suggested command:**
`cmi showurl [playername] [URL] (-s)`

Example:` /cmi showurl Cloude_Lecaw www.google.com -s`
**Effect on Screen of Cloude_Lecaw:**
![Snag_202994e](https://user-images.githubusercontent.com/12080017/112063776-3825f680-8b62-11eb-9bdf-dbf215f3fb01.png)

**Comment by Blueeyestar** [comment]
> 
> 
> When you enter a url in chat then you can klick it.
> a window opens where u got asked if you want to open this link in your browser.
> 
> **Problem:**
> The text must be "added" to chat and the player needs to cklick it first before he get this window. this looks a bit unprofessional special sometime if the link is the only think you want to give to the player. also some player dont understand that they need to klick it in chat. (specially jungers)
> 
> What we would need is a command that shows this link window directly for other players.
> 
> There would be many many options to design nice things specialy with attached commands or with interactive and console.
> 
> Also this way players often dont need these unnicly looking "extra links in chat" just to get the Chaturl link to get the question if they wanne open it in their brower.
> 
> **suggested command:**
> `cmi showurl [playername] [URL] (-s)`
> 
> Example:` /cmi showurl Cloude_Lecaw www.google.com -s`
> **Effect on Screen of Cloude_Lecaw:**
> ![Snag_202994e](https://user-images.githubusercontent.com/12080017/112063776-3825f680-8b62-11eb-9bdf-dbf215f3fb01.png)

that would be really great if there was something like that.

**Comment by Blueeyestar** [comment]
that would be really great if there was something like that.

**Comment by Zrips** [comment]
Not possible as this entire interaction if client sided and without some special mod which would perform most of the action we cant force URL open on players screen without him actually triggering this event manually by clicking on chat message or using book
