### ISSUE TITLE
Why we have /cmi pay?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5331]
When looking into the commandlist u may notice fast
CMI has
/cmi money pay   -`cmi money [pay/give/take/set] [playerName/all/alloffline] [amount/%rand/1-1000%/1%[min-max][playerName]] (-s)`
and
/cmi pay   - `pay [playerName] [amount] (-s)`

well both seems to do the same...

So why we have an extra pay command here?

Would it be simplier to have /pay in alias.yml leading to  /cmi money pay $1-?

In the Wiki the money command is not very descriptd with its permisions
Also you can just type /cmi money to show your balance...
you find cmi.command.money   and cmi.command.money.others
but this command would beed some more permission.. or are they allready exist?

- cmi.command.money
- cmi.command.money.others
- cmi.command.money.pay
- cmi.command.money.set
- cmi.command.money.set.others
- cmi.command.money.give
- cmi.command.money.give.others
- cmi.command.money.take
- cmi.command.money.set.others

if these permission allready exist then this would mean the command /cmi pay itself is totally unneeded.. So why it exists?

**Comment by Zrips** [comment]
/pay was a part of /money command some time ago, but due to the fact that /pay is one of those often used commands and people might want to give access to pay but not to any other action relating to money, its simpler for me and users to have it separate.
