### ISSUE TITLE
Broken website icons

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5334]
**Description of issue:**

---

Hi, I just wanna report that on this page are broken icons  https://www.zrips.net/cmi/commands/specialized/
![image](https://user-images.githubusercontent.com/18662086/112196947-d4f09e80-8c0b-11eb-94f5-33fbdcd0eaf6.png)

**Comment by CloudeLecaw** [comment]
No... 
it must be your connection or your computer or your browser that is translating the site uncorrect

![image](https://user-images.githubusercontent.com/12080017/112270193-9eea0380-8c79-11eb-80e2-2dec621994d2.png)

**Comment by bobhenl** [comment]
Oh, I¨ve tested it with another browse... with Google Chrome & Brave, so I thought it's global.

**Comment by Zrips** [comment]
@bobhenl 
Your browser seam to trying interpret specific combinations as emoji's or something in between those lines. Not really a broken image issue, just browser miss behaving.
