### ISSUE TITLE
[Request] - Gate feature

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#534]
Something that would be very neat is a gate feature. See images below for what I am talking about. 

![image](https://user-images.githubusercontent.com/19745447/41809908-8a616c1a-76f5-11e8-9eb8-776619a8ac28.png)
![image](https://user-images.githubusercontent.com/19745447/41809925-b1daa432-76f5-11e8-8e48-019e2d644998.png)

Should work like this:
Build the structure and place ironbars inside the frame. Place a sign on the block left/right for the ironbars and write [gate] op the first line. Left click on the sign to operate.

**Comment by Baktus79** [comment]
The images is not a real plugin. This is built only for demonstration

**Comment by arturek1666** [comment]
If I remember there was plugin that was doing it. If this would be added I would recommend to do a bit more than that as there is plugins that can do that so my idea is to add more than that example:
when done [gate] you can actually click on the sign and when clicked you get GUI with functions like:
Gate usage: Private, Public, Only Friends
By able to add friends to the specific gate so they can open if it's setup only friends
Daley for how quick the gate will open and close. 

This is just my idea :) I had notice that CMI has a lot of GUI stuff so that would match to the plugin more ;). Our not even a sign but maybe a button or pressure plate

**Comment by Baktus79** [comment]
I haven't search around for it. I used a plugin back in the day that did this, but that plugin included a lot more features that I did not need. I try to keep my plugin count low so it won't contain a lot of stuff that I dont need. If something like this would be included to CMI...another feature without adding more plugins :D

And yes, I really do like what your suggestions @arturek1666 
Would be cool if something like this could be something more than what I described.

**Comment by TheWranger** [comment]
@arturek1666 @Baktus79 I think the plugin you're thinking of is CraftBook. If so, CraftBooks is designed to be incredibly modular (only the mechanics you enable are loaded), I myself only use 1 feature from it.

**Comment by arturek1666** [comment]
Baktus79 I don't really think more plugins matter. If they are optimized by the way if you have plugins that are not optimized than yes more plugins will make server lag. For me I try to not go over 45 plugins. And server is fine and always see /timings paste to check if any added plugin makes server less stable.

TheWranger yea that's craftbook you are 100% write :) thx for reminding me this

**Comment by Baktus79** [comment]
@arturek1666 You are correct about that, but then you can never know for sure if the plugin is optimized or not. I do have a lot of plugins on my server, 59 to be exact. The previous server I owned it broke when it passed 70 plugins. Im not sure why that would happen, but it really did. I never found out why. But then again it might be because of optimization. haha, I know what you are gonna say! "Why in the &%$§ are you using that much plugins?" Well, I really do like to have a server that will engage the players with lots of features. Not too much but just enough. 

And yes, the plugin I used to use are Craftbook. But I cant remember it was such modular as @TheWranger  describes. I'll take a look at it again. But yeah, other plugins can do the job, but would be cool if this would be a feature in CMI as well.  CMI has become the new all-in-one, the everything you need plugin.

**Comment by LogGits** [comment]
This is beyond the scope of the project. There are a few gates plugins avail including skripts that can achieve this.
