### ISSUE TITLE
MySQL saving and "/stop" command

### ISSUE THREAD

**Issue by mare-on** [Zrips/CMI#5340]
**Description of issue:**
If there is any player on server and my server stops, the column "LastLogoffTime" in table "cmi_users" is not updated and database tells that player is still online while the server is offline. I observe this problem for more than 20 last cmi builds and still no inner fix is coming so finally Im reporting that.

---

**CONFIG SECTION:**

**dataBaseInfo.yml**
```
AutoSaveInterval: 10

ForceSaveOnLogOut: true
```

---

**Cmi Version (using`/cmi version`):** 8.8.2.5

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.16.5-b564

**Comment by mare-on** [comment]
Please, can somebody from support team do something with this issue?
It's simple problem with simple fix and it's already there for 8 days.

**Comment by Zrips** [comment]
Should be fixed with next build
