### ISSUE TITLE
Help with Specialized Commands "$1" in Check: {Nested}

### ISSUE THREAD

**Issue by red0fireus** [Zrips/CMI#5343]
I have this example here: 
  test:
    Cmds:
    - asConsole! ptarget:$1! check:%parseother_{$1}_{luckperms_check_permission_world.ban}%==yes!
      ctellraw [playerName] <T>&cTesting Testing</T>

I can't get this to work and I think it has something to do with the $1 in the placeholder. Is there a way to make it work? 

Thank you.

This might be considered a feature request if you can't use $1 in the check: portion of a alias.

**Comment by red0fireus** [comment]
- asConsole! ptarget:$1! check:%otherplayer_hasperm_$1_perm_world.ban%==true!
      ctellraw [playerName] <T>&cYou must define a player name !</T>

changing it to this seemed to work. For anyone interested.

**Comment by CloudeLecaw** [comment]
why your nested placeholder has no {}?
