### ISSUE TITLE
CMI Bungee portal commands not activating AFTER teleport

### ISSUE THREAD

**Issue by hamcoremusic** [Zrips/CMI#5347]
**Description of issue:**
As stated in the Portal documentation

>Portal commands will work over bungee network and will be applied after player is teleported.

This actually isn't happening. It is activating the command BEFORE the teleport happens.

For example, I have the portal issuing the command `asConsole! cmi spawn [playerName]` and when you walk through the portal, it teleports you back to spawn AND THEN teleports to the other server.

---

**Cmi Version (using`/cmi version`):** 
8.8.2.6
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-169 1.16.5
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
You might have enabled "Perform commands without valid teleport location" which derping out entire process, if you have bungee location set and command which needs to be performed after player gets teleported. Will make some changes to resolve this specific issue. Tho you do have option to directly teleport to bungee server. If you have set teleport location to destination bungee server and added extra command which teleports player to spawn, then it does perform it in order. If you added both commands into general command list, then it will get performed in a row independent what those commands actually does.
