### ISSUE TITLE
Teleport to location via /inv cmd even without perms

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5349]
**Description of issue:**

---

Hi, I wanna report that my helpers have only this permissions:
![image](https://user-images.githubusercontent.com/18662086/112705469-33817b00-8e9f-11eb-8672-1de30fa7b2d3.png)
(they're missing cmi.invedit or permission to /tppos or /tp... and they still can teleport using /inv cmd.... via location icon. When they click on it it shows that they're missing cmi.invedit, but it teleprots them. I think it should check if they can use this OR tppos perm or TP perm or something like that).

---

**Cmi Version (using`/cmi version`):** 8.8.2.6

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** 1.16.5

**Comment by Zrips** [comment]
Should be resolved with next update
