### ISSUE TITLE
Serious copy BUG

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#535]
When the backpack is full
Use
Cmi attachcommand !limiteduse:1!;;!cc!cmi money give [playerName] 150
The item

Left click on NPC
This unlimited use of organic rates occurs

Please watch from movie 1:30

https://www.dropbox.com/s/d3gq6w162yr5q9w/Minecraft%202018.06.24%20-%2003.08.03.06.mp4?dl=0

**Cmi Version (using`/cmi version`): 7.8.6.0

**Server Type (Spigot/Paperspigot/etc): paper

**Server Version (using `/ver`): 1.12.2

**Comment by Zrips** [comment]
Could you provide more info on NPC itself? What is that UI you are opening, what plugin is that and is this only issue when using that UI in particular?

**Comment by p82183645** [comment]
![image](https://user-images.githubusercontent.com/5382252/41859806-94a80112-78cf-11e8-9f7c-9e8b93733612.png)

other problems

**Comment by p82183645** [comment]
GUI use CrazyCrates
NPC Citizens 2.0.22
The use of organic rates in every NPC occurs

And when the stacking of items is restricted
Use will cause an infinite stack of words

Example: Restricted use: 1

Holding x64 for each use
Lore add Restricted use: 1 infinite stack

**Comment by Zrips** [comment]
Last 2 issues should be fixed, tho still waiting for some extra information on original issue.
