### ISSUE TITLE
Enchanting | ERROR / BUG?

### ISSUE THREAD

**Issue by roy0510** [Zrips/CMI#5350]
Good day,

Although it is true, having the **enchantLimits** in **false** one could enchant a with numbers higher than normal (by command)

And that is the problem, that I currently have that option in **false**

and using command I should put enchant for example: **sharpness 10**, but it does not work, a message tells me that the maximum enchantment is 1.

```Enchanting:
  enchantLimits:
    # By disabling this, no limitation to enchanting will be applied
    # This only applies for enchant command not for natural enchanting
    Enabled: false

**Comment by Zrips** [comment]
Changing this option required full server restart. Will fix it with next version to update properly when you reload config file.
