### ISSUE TITLE
Players are loosing helmet + leggings when teleporting via /cmi inv

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5354]
**Description of issue:**

---

Hi, I've tried reset the whole CMI configuration & also use just basic plugins:
![image](https://user-images.githubusercontent.com/18662086/112738138-748d9400-8f60-11eb-96d7-cde4de416ab3.png)

and there's a really important bug. When you teleport to someone with /cmi inv -> and then paper icon, their helmet & leggings disappear. Here is a video:  https://streamable.com/ieqbv4

Just a note, I first thought it's related to https://github.com/Zrips/CMI/issues/5349, but players lose these two items even when I teleport to them with * permission, so it's not related to it, but I will be glad if both issues will be fixed.

**IMPORTANT NOTE: You have to teleport from another world**

---

**Cmi Version (using`/cmi version`):** 8.8.2.6

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** 1.16.5

**Relevant plugins (Delete if this isn't needed):**Mentioned above

**Comment by Zrips** [comment]
Will make some adjustments to this particular UI handling part, tho it should not have effected player your are teleporting too. But we will see if next update resolves this for you.
