### ISSUE TITLE
Players can't fly even when they have fly true on world change

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5356]
**Description of issue:**

---

Hi, I want to report that even when by /info <player_name> he can fly... he can't after teleporting to another world.

It's due to GAMEMODE world limits, but I think that game mode world limits shouldn't break fly world limits, or?
These were my world limits for fly and player teleported from the world "world" to the world "MiningWorld" and he cannot fly there even when he should by /info cmd. I've also tried to give him cmi.worldlimit.fly.bypass but it didn't help.
```
  Fly:
  - BossLand:False
  - EndMobTrap:False
```

What helped was when I've set:
```
  Gamemode:
  - world:Survival
  - world_nether:Survival
  - world_the_end:Survival
  - MiningWorld:Survival
  - SurvivalSpawn:Survival
  - BossLand:Survival
```
to:
```
  Gamemode:
  - BossLand:False
  - EndMobTrap:False
```
SO I've disabled world limits for game mode in world "world" and world "MiningWorld". But I think this is a bug... cause why we can't limit their game mode and let them normally fly after world change?

---

**Cmi Version (using`/cmi version`):** 8.8.2.6

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** 1.16.5

**Comment by broken1arrow** [comment]
> **Description of issue:**
> 
> Hi, I want to report that even when by /info <player_name> he can fly... he can't after teleporting to another world.
> 
> It's due to GAMEMODE world limits, but I think that game mode world limits shouldn't break fly world limits, or?
> These were my world limits for fly and player teleported from the world "world" to the world "MiningWorld" and he cannot fly there even when he should by /info cmd. I've also tried to give him cmi.worldlimit.fly.bypass but it didn't help.
> 
> ```
>   Fly:
>   - BossLand:False
>   - EndMobTrap:False
> ```
> 
> What helped was when I've set:
> 
> ```
>   Gamemode:
>   - world:Survival
>   - world_nether:Survival
>   - world_the_end:Survival
>   - MiningWorld:Survival
>   - SurvivalSpawn:Survival
>   - BossLand:Survival
> ```
> 
> to:
> 
> ```
>   Gamemode:
>   - BossLand:False
>   - EndMobTrap:False
> ```
> 
> SO I've disabled world limits for game mode in world "world" and world "MiningWorld". But I think this is a bug... cause why we can't limit their game mode and let them normally fly after world change?
> 
> **Cmi Version (using`/cmi version`):** 8.8.2.6
> 
> **Server Type (Spigot/Paperspigot/etc):** Tuinity
> 
> **Server Version (using `/ver`):** 1.16.5

Has you multiverse?
