### ISSUE TITLE
wrong permission. /cmi money pay

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5358]
When using the command
**/cmi money pay** it asks for  permission to the command cmi.command,pay
This is wrong.
[i wrote in an other thread](https://github.com/Zrips/CMI/issues/5331  allready why it should be cmi.command.money.pay....

The wrong answer is "they do the same, so same permission.

The question is why? cmi money pay is its own comand. (part of the money command that has give, set, pay, take argument)

**Comment by Zrips** [comment]
/cmi money pay redirects into /cmi pay as this command got introduced later on as dedicated one for this action specifically while before that it was built into money command as an actual sub command. As this just redirects you to another command, you will need access to that command to perform this action. In general i can remove that requirement as its a regular none admin command and if you have access to /money command you can have access to basic payments
