### ISSUE TITLE
Сhat is not recorded in logs

### ISSUE THREAD

**Issue by Augmented-Bersy** [Zrips/CMI#5371]
So after i delete DeluxeChat and replace it with CMI chat everithing that my players type didn't record in server logs. 
Here is how it looks: https://bin.birdflop.com/febocopope.css
There is nothing after player nickname. 
When i disable CMI chat it works fine.

There is no errors or so.
Here is starting logs if needed: https://bin.birdflop.com/guvufirohu.yaml

Here is the whole chat section in config: https://bin.birdflop.com/ufanomutus.yaml

**Version CMI:** 8.8.2.7 SqLite
CMILib: 1.0.0.2 
Server: Purpur 1.16.5-R0.1-SNAPSHOT
CMI economy: Yes Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Yes
Modules -> 44 enabled 11 disabled: disabledEnchants, tablist, ranks, playerCombat, headDrop, skin, sitAnimation, jail, elytraBoost, namePlates, elytraLaunch

**Server Type:** Purpur v.1022

**Server Version:** 1.16.5

**Relevant plugins:** Plugins (70): AAC5, AACAdditionPro, AACPlus, Additionalmechanics, AdvancedMonthlyCrates, AnnouncerPlus, AsyncWorldEdit, AuctionHouse, AuthMe, BetterRTP, BottledExp, ChatBrawl, Chunky, Citizens, Clicker, ClickSort, CMI, CMIEInjector*, CMILib, CoreProtect, DeathMessages, DeluxeCombat, DeluxeCombat_Addon_WG*, DeluxeMenus, Denizen, dynmap*, Dynmap-WorldGuard*, eco, EcoBosses, ExtraContexts, FastLogin, GSit, HeadDatabase, InventoryRollback, ItemSoulBind, Jobs, LangUtils, LiteBans, LoneLibs, LuckPerms, MiniMOTD, MobArena, MobArenaExtension*, Multiverse-Core, MVdWPlaceholderAPI*, MythicMobs, PetBlocks*, PL-Hide-Pro, PlaceholderAPI, Plan, PlugMan, ProtocolLib, RestrictedCreative, RevoltCrates, SelectionVisualizer, Shopkeepers, SkinsRestorer, spark, SupremeItem, TAB, TitleAdvanced*, TreeAssist, Vault, VoidGenerator, Votifier, VoxelSniper, WorldEdit, WorldGuard, WorldGuardEvents*, WorldGuardExtraFlags

**Comment by Zrips** [comment]
You forgot to add {message} variable inside GeneralFormat. Tho while i'm at it will make it to be more optional. But to fix this issue before next release simply add it and it will fix missing messages in console
