### ISSUE TITLE
Death message

### ISSUE THREAD

**Issue by 849025143** [Zrips/CMI#5373]
**Description of issue:** The death message does not replace the default message

#######################################
#######################################
```

---

**Cmi Version (using`/cmi version`):** 8.8.2.7

**Server Type (Spigot/Paperspigot/etc):** paperspigot

**Server Version (using `/ver`):** 1.16.5

**Comment by Zrips** [comment]
Because it should not do that. CMI doesn't replace default death messages, not currently anyways.
