### ISSUE TITLE
Missing "message:" option for tempban and wrong outputs  of bans.

### ISSUE THREAD

**Issue by Computerjul** [Zrips/CMI#5385]
When a players gets temporarily banned it shows the "message:" that is defined in locales_en.yml  for permanent ban or permanent ip ban but it doesnt show the message for temporary bans. Here are the details from the locales_en.yml
```
  ban:
    help:
      info: '&eBan player'
      args: '[playerName] (reason) (-s)'
      explanation:
      - cmi.command.ban.bypass - to bypass ban
    info:
      # Make sure that OverrideLoginMessage is enabled in config file
      message: '&4Permanently Banned!'
      reason: '&c/n [reason]'
      defaultReason: '--------------------'
      messageToAll: '&6[playerDisplayName] &egot permanently banned'
      banedSilent: '&7[&8Silent&7]&6[playerDisplayName] &egot banned by &6[senderDisplayName]
        &efor: &6[reason]'
      noSelfBan: '&cYou can''t ban yourself'
      cantBan: '&cYou can''t ban this player'
```

```
  ipban:
    help:
      info: '&eBan ip'
      args: '[ip/playerName] (reason) (-s)'
      explanation:
      - cmi.command.banip.bypass - to bypass ban
    info:
      message: '&4Permanently Banned!'
      reason: '&c/n [reason]'
      defaultReason: '--------------------'
      messageToAll: '&6[playerDisplayName] &egot permanently banned'
      banedSilent: '&7[&8Silent&7]&6[playerDisplayName] &egot ip banned by &6[senderDisplayName]
        &efor: &6[reason]'
```

```
  tempban:
    help:
      info: '&eTempBan player'
      args: '[playerName] [timeValue] (reason) (-s)'
      explanation:
      - Ban max range depends on cmi.command.tempban.max.[amount]
      - cmi.command.tempban.max.unlimited - allows to ban for as much as you want
      - In case player doesn't have any, 60 sec will be max value
      - 'Example: '
      - /cmi tempban zrips 5m For swearing
    info:
      messageToAll: '&6[playerDisplayName] &egot temporarily banned for: &6[time]'
      banedSilent: '&7[&8Silent&7]&6[playerDisplayName] &egot tempbanned by &6[senderDisplayName]
        &efor: &6[time] &ereason: &6[reason]'
      time: '&e/n Unbanned in &6[time]'
      badTime: '&cTime is defined incorrectly'
      badTimeRanges: '&cYou can''t ban for longer than [time] &6([seconds])'
  tempipban:
    help:
      info: '&eTemp ban ip'
      args: '[ip/playerName] [time] (reason) (-s)'
      explanation:
      - cmi.command.banip.bypass - to bypass ban
    info:
      message: '&4Temporarily Banned!'
      reason: '&c/n [reason]'
      defaultReason: '--------------------'
      messageToAll: '&6[playerDisplayName] &7got temporarily banned for &7[time]'
      banedSilent: '&7[&8Silent&7]&6[playerDisplayName] &7got temp ip banned for &7[time]&7:
        &6[reason]'
```

As you can see there is no "message:" option for tempban config. But it is available for tempipban config you can see at the bottom and i set it to show "Temporarily Banned". But when i tempban or tempipban someone it takes the "message:" from the ban and ipban section at the top for permanent bans and shows "Permanently Banned" but still shows the "messageToAll" for temporarily ban. Its a little bit weird. I tried to add the missing "message:" option manually for the tempban but that doesnt work and disappears after i restart the server or reload config. Here is a screenshot of the banscreen and console output which shows it. 

[EXAMPLEIMAGES](https://imgur.com/a/5YdvwoI)

Also when you execute the ban command the first kick screen of the banned player doesnt show the set "message:" it only shows a reason. It only shows the "message:" after the player tries to reconnect. Like this: 

[EXAMPLEIMAGES](https://imgur.com/a/VqFyUdO)

---------------------

Thank you for your time and effort you put into this. A fix for **all** of the mentioned problems and bugs would be awesome as this is important for me. :)

Best regards

**Comment by Zrips** [comment]
Will make some changes relating to all 4 ban commands. If I missed something, let me know. Closing this ticket.
