### ISSUE TITLE
Empty message when login in vanish

### ISSUE THREAD

**Issue by Xardas88** [Zrips/CMI#5387]
**Description of issue:**
When a vanish player login an empty message appears in the chat.
it does this only when the login message is disabled
---

**Cmi Version (using`/cmi version`):** 
8.8.2.6
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.16.5
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
You might have another plugin printing out join message which gets set to empty field if we want to disable it, which is normal vanilla behavior. Try disabling some of the plugins, especially relating to chat management to figure out which one in particular causes this
