### ISSUE TITLE
Holos on Plotsquared

### ISSUE THREAD

**Issue by JamesBach93** [Zrips/CMI#5394]
Hey, i use Plotsquared v5 on my Paper Server 1.16.5 i want replace the Signs into Holograms.
But they dont work :/. Can you add the Ability for this ? :) 

Here is the Plugin for the Holos 
https://www.spigotmc.org/resources/holoplots.4880/

Greetings

**Comment by CloudeLecaw** [comment]
im confused.. your using an other plugin for holograms and report that they do not work?...

Whats with the regular CMI hologramms that cmi commanes with? you can attack them to ics..

**Comment by Zrips** [comment]
@JamesBach93 
You might want to ask developer of that plugin to add CMI support. There are no plans in adding features which are dependent on another plugin and made for that plugin specifically and not CMI.
