### ISSUE TITLE
staffmsg showing when staff is not logged in (AuthMe)

### ISSUE THREAD

**Issue by Albert481** [Zrips/CMI#5395]
How to prevent staffmsg from showing for unauthenticated players?

**Comment by CloudeLecaw** [comment]
they need permission to see staffmgs

**Comment by Albert481** [comment]
Someone can log into my account (Owner) and see staffmsgs without logging in with authme.

> they need permission to see staffmgs

**Comment by CloudeLecaw** [comment]
why you dont prevent this if your using a server with onlinemode false then you need a  authme plugin that is working and kicks all if password is wrong

and if your having a server with onlinemode true and someone else log into your account then u gave away your unique Mohjang Account passwort that is needed to login into the launcher and play

**Comment by Zrips** [comment]
Well, we do have option to protect account by defining which ip can log into it. Other than this i cant make support for every single plugin out there who might want to allow some one to log into game and have all permissions as staff member while he decides to enter password. This is huge security risk. I can understand that there isint any other way for offline type servers to validate users, but at same time we will have to live with this small compatibility issue.
