### ISSUE TITLE
Titlemsg not working properly

### ISSUE THREAD

**Issue by EkonC** [Zrips/CMI#5398]
**Description of issue:**

Hello, I recently created a new server with a pure CMI configuration, but /titlemsg command doesn't work properly for me.
When I used "/titlemsg EkonC Hello \n Test", it wrote Hello Hello (in both lines as seen on screenshot)

![2021-04-03_11 34 40](https://user-images.githubusercontent.com/62595403/113474645-66b0a500-9471-11eb-9ad3-487f8490aa57.png)

https://discord.com/channels/452792793631555594/526402563847880725/826234131942998017
This bug was reported here on your Discord by another player as well.

The weird thing is that this bug is not on all of my servers, on some of them it works perfectly, on one of them /titlemsg doesn't work but an onJoin command which uses titlemsg works and on another two, it doesn't work. I will list all the servers down here with relevant info:

Auth:

- CMI 8.8.2.8
- Purpur-1049 (MC: 1.16.5)
- /titlemsg works

Lobby:

- CMI 8.8.2.7
- Purpur-1049 (MC: 1.16.5)
- /titlemsg doesn't work, onJoin titlemsg works

Survival:

- CMI 8.8.2.7
- Purpur-1049 (MC: 1.16.5)
- /titlemsg works, onJoin titlemsg works

Dungeons:

- CMI 8.8.2.8
- Purpur-1038 (MC: 1.16.5)
- /titlemsg works

Badlands:

- CMI 8.8.2.10 (didn't work on 8.8.2.8/8.8.2.7 either)
- Purpur-1051 (MC: 1.16.5), didn't work on Purpur-1049 either
- /titlemsg doesn't work, onJoin titlemsg doesn't work

---

(this is the info for the server where it completely doesn't work)

**Cmi Version (using`/cmi version`):** 

CMI: 8.8.2.10 BungeeCord CMIB  SqLite
CMILib: 1.0.0.2 
Server: Purpur 1.16.5-R0.1-SNAPSHOT
CMI economy: False CMI Chat: True 
Modules -> 53 enabled 2 disabled: tablist, votifier

(btw version on the screenshot is not the version of the server the issue is on)

**Server Type (Spigot/Paperspigot/etc):** 

Purpur

**Server Version (using `/ver`):** 

This server is running Purpur version git-Purpur-1051 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Purpur-1049 (MC: 1.16.5)

**Relevant plugins (Delete if this isn't needed):**
Probably not relevant but just to make sure:
BungeeGuard, Citizens, CMI, CMILib, CoreProtect, LuckPerms, Matrix, PlaceholderAPI, ProtocolLib, Residence, SkinsRestorer, TAB, TradeMe, TradeShop, Vault

**Comment by CloudeLecaw** [comment]
you format of using titlemsg is a bit wrong.
best is if your using the correct format.

here a little example

cmi titlemsg MyPlayername Hello&f:&f \n&f&lThis is your Hellomsg. -in:20 -out:20 -keep:30

**Comment by EkonC** [comment]
Yeah, the format was all correct. It was fixed with the last CMI version but thanks for trying to help.
