### ISSUE TITLE
Random slimes when use /ride in specific biomes

### ISSUE THREAD

**Issue by iBuseWinner** [Zrips/CMI#5401]
**Description of issue:**
When player use /ride on other player in biome where slimes can spawn (such as swamp), player see that he rides slime
(Player report this bug, so screenshots made by him)
![image](https://user-images.githubusercontent.com/44753872/113502698-95dd1a00-9536-11eb-87bb-48be0bc886c1.png)

---

**Cmi Version (using`/cmi version`):** 
8.8.2.2

**Server Type (Spigot/Paperspigot/etc):** 
Purpur

**Server Version (using `/ver`):** 
[11:11:10 INFO]: This server is running Purpur version git-Purpur-1047 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by iBuseWinner** [comment]
@Zrips ??

**Comment by Zrips** [comment]
Will add extra protection, but this looks more to be caused by another plugin, as slime should not be that big when spawned on player head, size should be more or less same as players head.
