### ISSUE TITLE
CMI Launch In Portals

### ISSUE THREAD

**Issue by Ash10744** [Zrips/CMI#5402]
**Description of issue:**

Cmi Launch doesn't seem to be working on the latest update.

Proof of designated area:
![pLw2ozu](https://user-images.githubusercontent.com/16086663/113511996-81ab1400-955a-11eb-9f64-5f1f6e3181a9.jpg)

Proof of command:
![vgnGgGM](https://user-images.githubusercontent.com/16086663/113512008-94254d80-955a-11eb-81c9-c7c54ae3c663.png)

Me attempting to enter the area:
![Fh6D1Tl](https://user-images.githubusercontent.com/16086663/113512033-b8812a00-955a-11eb-95a3-aa1f2008d5c2.gif)

---

---

**Cmi Version (using`/cmi version`):** 
![ndICTWM](https://user-images.githubusercontent.com/16086663/113512065-d9e21600-955a-11eb-8894-51f83b259e68.png)

**Server Type:** Paper Spigot

**Server Version (using `/ver`):**
![h14vvb0](https://user-images.githubusercontent.com/16086663/113512223-80c6b200-955b-11eb-870a-0989185e856e.png)

**Comment by Ash10744** [comment]
I changed the particles to love to show I am in the correct area also:
![YnTaWXz](https://user-images.githubusercontent.com/16086663/113512355-342fa680-955c-11eb-9e16-31c59c1a1d10.png)

**Comment by Zrips** [comment]
Do you have 
![image](https://user-images.githubusercontent.com/10416201/113853362-dc807d80-979d-11eb-96e3-dcfb2b279e6d.png) enabled?
