### ISSUE TITLE
Holograms

### ISSUE THREAD

**Issue by Zuixik** [Zrips/CMI#5406]
Good day,

When I restart the plugin via /cmi reload, the holograms are not reloaded. And it also causes problems when restarting the whole server

**Comment by CloudeLecaw** [comment]
what kind of problems?

**Comment by Zuixik** [comment]
When you enter the cmi reload command, holograms are not read back.

**Comment by CloudeLecaw** [comment]
and no errors in the console?

**Comment by Zuixik** [comment]
What Server Version are you using? Yatopia (1.16.5)
What CMI-Version are you using? latest (But because it doesn't work, I went to 8.8.1.5)
Any other plugins that try to work with Holograms? All other plugins work
Cmi and server version can be checked with the /cmi version command.

**Comment by CloudeLecaw** [comment]
Oh i dont know if Zrips will take a look in this. Yatopia is one of the 1000's unsupoorted forks..

But you can give it a try, may Zrips want to take the time to take or look (or he close the ticket direcly... who knows..)

For now i just can tell you that the reloading of the hologramms is working nice on a paper 1.16.5 server. (i havent tested forks of it now)

**Comment by Zuixik** [comment]
I know it works properly on papermc. But I have a server where those holograms normally work with Yatopia forks. I tried to copy it but it just doesn't work.

**Comment by Zrips** [comment]
Will make some changes for better hologram update when you reload cmi, as it was updating them but you had to move around for new updated lines to appear properly which could have derped out in some situations with some specific hologram setups. Should be in working order with next update.
