### ISSUE TITLE
Issues with CMI portals/pads

### ISSUE THREAD

**Issue by Augmented-Bersy** [Zrips/CMI#5407]
**Descriprion:**

**1.** I have 2 portals wich execute command: "betterrtp:rtp player [playerName] Wild" - it's worked at previous versions. Now when player came into portal nothing happens. But there is something in console.

**2.** I have 5 launchpands. Some of them didn't work anymore, some worked, and one of them make strange things. 
GIF - https://gfycat.com/ru/fragrantdeficientisabellinewheatear

This portal glitch - "cmi launch [playerName] p:2.2 a:20"
This portal work fine - "cmi launch [playerName] p:3 a:55"
This portal didn't work - "cmi launch [playerName] p:2 a:55"

---

**Errors:**

When I step into portal with "betterrtp:rtp player [playerName] Wild" i have an issue tracked in logs.

Here it is: https://bin.birdflop.com/ejeyisuhoc.properties

---

**Version CMI**: 8.8.2.10 SqLite
CMILib: 1.0.0.2
Server: Purpur 1.16.5-R0.1-SNAPSHOT
CMI economy: Yes Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Yes
Modules -> 44 enabled 11 disabled: disabledEnchants, tablist, ranks, playerCombat, headDrop, skin, sitAnimation, jail, elytraBoost, namePlates, elytraLaunch

**Server Type**: Purpur v.1022

**Server Version**: 1.16.5

**Relevant plugins**: Plugins (70): AAC5, AACAdditionPro, AACPlus, Additionalmechanics, AdvancedMonthlyCrates, AnnouncerPlus, AsyncWorldEdit, AuctionHouse, AuthMe, BetterRTP, BottledExp, ChatBrawl, Chunky, Citizens, Clicker, ClickSort, CMI, CMIEInjector*, CMILib, CoreProtect, DeathMessages, DeluxeCombat, DeluxeCombat_Addon_WG*, DeluxeMenus, Denizen, dynmap*, Dynmap-WorldGuard*, eco, EcoBosses, ExtraContexts, FastLogin, GSit, HeadDatabase, InventoryRollback, ItemSoulBind, Jobs, LangUtils, LiteBans, LoneLibs, LuckPerms, MiniMOTD, MobArena, MobArenaExtension*, Multiverse-Core, MVdWPlaceholderAPI*, MythicMobs, PetBlocks*, PL-Hide-Pro, PlaceholderAPI, Plan, PlugMan, ProtocolLib, RestrictedCreative, RevoltCrates, SelectionVisualizer, Shopkeepers, SkinsRestorer, spark, SupremeItem, TAB, TitleAdvanced*, TreeAssist, Vault, VoidGenerator, Votifier, VoxelSniper, WorldEdit, WorldGuard, WorldGuardEvents*, WorldGuardExtraFlags

**Comment by Augmented-Bersy** [comment]
1. Figure out, that CMI has nothing to do with it. I updated BetterRTP and it now has this issue. 

2. Launchpads still didn't work properly

**Comment by Zrips** [comment]
Could be issue with anticheat trying to block sudden player movement. Currently cant reproduce this glitch on a clean server.
