### ISSUE TITLE
 Tags are not hidden above the player's head

### ISSUE THREAD

**Issue by catfishua** [Zrips/CMI#5408]
Description of issue:
Good afternoon, I have such a problem, my CMI blocks hiding tags above the player's head that I want to hide using the NametagHide plugin, but when I hide tags using the NametagHide plugin, CMI simply does not allow me to do this (the CMI plugin is like as if deliberately shows tags (nicknames) above the player's head) and shows tags that, as it were, should already be hidden, I have already climbed all the settings and I have not seen anything, I will be grateful for your help

Cmi Version: CMI version 8.8.1.5

Server Type: SSSpigot (fork based on Paper mc plus crossed with Tuinity)

Server Version: SSSpigot version SSSpigot-1.16.5-20210404-21ed970 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Relevant plugins: NametagHide

**Comment by Zrips** [comment]
Can you point to exact NametagHide plugin you are using? And this could be relating to basic compatibility issue as stuff like this including glow gets handled by one thing which can be modified by multiple plugins which breaks things

**Comment by catfishua** [comment]
Good afternoon, I can only provide you with these plugins, because one plugin is samopis, and the second plugin, unfortunately, was removed from the spigotmc.org site, so keep NametagHide the first plugin to hide tags over the player's head, and the second plugin self-written NickNameCheck along with source code. I hope you find a solution to this problem.
[NickNameCheck.zip](https://github.com/Zrips/CMI/files/6271846/NickNameCheck.zip)
[NickNameCheck-1.0.zip](https://github.com/Zrips/CMI/files/6271848/NickNameCheck-1.0.zip)
[NametagHide.zip](https://github.com/Zrips/CMI/files/6271852/NametagHide.zip)

**Comment by Zrips** [comment]
Made some adjustments which should be some what a batter solution, not perfect one, but it will handle it more properly with next update.
