### ISSUE TITLE
[item] brekas spawners itemdata

### ISSUE THREAD

**Issue by WindUnwaken** [Zrips/CMI#541]
**Description of issue or feature request:**

If player holds cave spawner or other type, then type [item]
spawner missed its itemdata, and changed to pig spawner

**Server Type (Spigot/Paperspigot/etc):** 
spigot 1.12.2

**Comment by Zrips** [comment]
[item] only reads item information, its not manipulating it by itself. Did you tested this one with only CMI installed?
