### ISSUE TITLE
Error soport

### ISSUE THREAD

**Issue by heccttor** [Zrips/CMI#5410]
**Description of issue:**
I have a problem that every so often produces an error

---

**ERROR (DELETE IF YOU HAVE NO ERROR):** https://pastebin.com/UNawQEt6
```https://pastebin.com/UNawQEt6
######################
## REPLACE WITH ERROR ##
######################
```

---

**Cmi Version (using`/cmi version`):**  8.8.2.10

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):**  1.16.5

**Relevant plugins (Delete if this isn't needed):**  Plugins (27): 40ServidoresMC, ArtMap, ChestShop, CMI, CMIEInjector, CMILib, CombatLogX, CoreProtect, DinoVoteRewards, eGlow, EnjinMinecraftPlugin, GoldenCrates, Jobs, JPremium, LuckPerms, MyCommand, NexEngine, PlaceholderAPI, ProCosmetics, ProtocolLib, SecuredNetwork, Towny, TownyChat, Vault, VotePartyPlus, Votifier, WorldEdit

**Comment by CloudeLecaw** [comment]
Why you think this issue is comming from cmi?

**Comment by Zrips** [comment]
Will make some changes relating this, if you still experience same issue with next update let me know.
