### ISSUE TITLE
Destroy item when /rt (bug)

### ISSUE THREAD

**Issue by Baschounette** [Zrips/CMI#5411]
**Description of issue or feature request:**

Hi, a bug to report : 
when I use the command /rt (randomteleport), an item in my hotbar is destroy.
---

**Cmi Version (using`/cmi version`): 8.8.2.10** 

**Server Type (Spigot/Paperspigot/etc): Spigot ** 

**Server Version (using `/ver`): 1.16.5 **

**Comment by CloudeLecaw** [comment]
may an other plugin took over /rt?
like "remove trash".....?

**Comment by Baschounette** [comment]
nop, i d'ont have it, i search in my 60' plugin in my server, i dont find why an item is destroy when I do /rt

**Comment by Zrips** [comment]
/rt should only teleport player without any modifications in players inventory as there is no need to do so. You might want to test it out with CMI only while other plugins are disabled to make sure that issue actually comes from CMI and not another plugin removing item for some reason. If issue persists, then temporary renaming CMI folder into CMI_backup and starting server again could determine if issue is with specific setup of yours, which could include event commands and similar. 
Its not enough information to determine if there is issue or what issue in particular. Any specifics about removed items?
