### ISSUE TITLE
Placeholder for maintenance

### ISSUE THREAD

**Issue by JaTiTV** [Zrips/CMI#5412]
Could you add a placeholder that you can display for example in a hologram or in another plugin that supports PlaceholderAPI if a server from the network is in maintenance mode or not? Or does this already exist? For example %cmi_maintenance_<server>%

**Comment by CloudeLecaw** [comment]
Why anplaceholder? Why not simply design your hologramm to show this text when you maintain a server? You can create a lovly customalais for that, that checks what Servername u used and react in the correct hologramm for each.
