### ISSUE TITLE
Red numbers with CMI

### ISSUE THREAD

**Issue by naikyy** [Zrips/CMI#5413]
Hey, could I ask why there are red numbers with some warp action from CMI? I think it can affect performance so I came here with some possible help, thank you!

Timings: https://timings.pl3x.net/?id=2cb473eb12e3486db95c8ee24ab0db52#timings

**Comment by Zrips** [comment]
Do you have warp points in worlds which could be unloaded and then load process started when some one starts teleporting over there?

**Comment by naikyy** [comment]
What do you mean? Aren't all the warps unloaded and are they loaded when the player is ported there? I got 10 warps which are somewhere in the world but how to deal with that?

**Comment by Zrips** [comment]
What i meant is that some plugins which creates custom worlds could unload entire world to free up memory in which case when player tries to teleport to this world, then entire world needs to be loaded before hand. If this is not the case then something else might effect efficiency of teleportation

**Comment by naikyy** [comment]
Do you know exactly what plugin could do that? Im using Multiverse for creating another worlds.

**Comment by naikyy** [comment]
But this is not OK, since I updated to the last newest versions I got these numbers for no reason I have no clue whats the problem and what can I do for it, its doing micro lags on the server and its doing only with Zrips plugins: https://timings.pl3x.net/?id=c31134fa7cf04c3fabaa87cf3c41c545#plugins
