### ISSUE TITLE
8.8.3.0 | IllegalStateException Spam

### ISSUE THREAD

**Issue by UltimateGamer200** [Zrips/CMI#5417]
**Description of issue:** I recently updated CMI to version 8.8.3.0 and today, I noticed while I was online that the console was spamming me a lot of exceptions until no one was online. I feel maybe the new Bungee method that was added to the update may have something to do with this issue. I tried disabling BungeeCord support as well and that didn't fix the issue.

**ERROR:**
```
While there is at least one player online, these exceptions spam to the console.
https://pastebin.com/1jxi9gKy
```

**Cmi Version:**
CMI: 8.8.3.0 BungeeCord  MySQL
CMILib: 1.0.0.2 
Paper(584) 1.16.5-R0.1-SNAPSHOT
CMI economy: False Vault: 1.7.3-b131 CMI Chat: False 
Modules -> 53 enabled 2 disabled: tablist, playerChatTag

**Server Type** Paper 

**Server Version:** 1.16.5

**Comment by Zrips** [comment]
Should be fixed with next build
