### ISSUE TITLE
CMI Glow color dependand on Prefix-Ending?

### ISSUE THREAD

**Issue by xmorose** [Zrips/CMI#5423]
**Description of issue:**
I always wondered why i always glow in red and never in another color, turns out its my username color set in the Prefix-Ending.
![Screenshot_15](https://user-images.githubusercontent.com/53750990/114089583-9cf98480-98b6-11eb-9c2d-4b7b70264c0e.png)
![Screenshot_14](https://user-images.githubusercontent.com/53750990/114089604-a256cf00-98b6-11eb-83ac-457198167c06.png)
As you can see in the screenshots, the user first has the Username-Color Green, then White and the Glowcolor changes with it. I tried giving the user the color Gold in  these cases, it just ignores the color and forces it on the username-color apparently.

 I manage username-colors because of Formatting-issues over the ending of the prefix. In this case:
prefix.2.&0&l[&x&8&0&f&f&0&0&lSamurai&0&l] &x&8&0&f&f&0&0 (Green color)
prefix.2.&0&l[&x&8&0&f&f&0&0&lSamurai&0&l] &x&f&f&f&f&f&f (White color) 

Would be great if you could stop the Glow-effect affecting the username color (seems like that happens too, that you set /cmi glow x red and the username just changes to red) 

and

that it doesnt depend on the ending of the prefix anymore so i can set a glowcolor that is completely custom and has nothing to do with the username color at all :o

Thank you for reading!

**Cmi Version (using`/cmi version`): 8.8.3.0, CMILib 1.0.0.2

**Server Type (Spigot/Paperspigot/etc): Paper 1.16.5

**Server Version (using `/ver`): git-Paper-576 1.16.5

**Comment by CloudeLecaw** [comment]
this would be great

**Comment by Zrips** [comment]
Issue is that minecraft overrides players name color if you have colored glow enabled, so having blue glow and red name isint really possible, atleast I don't know any simple solution for it.

**Comment by CloudeLecaw** [comment]
Hm its it possible to use a "placeholder" that is 0 by default and when glow set it setting the color at the end of the name?
So it doesnt matter what color the name has?
