### ISSUE TITLE
Ongoing problems, still..

### ISSUE THREAD

**Issue by naikyy** [Zrips/CMI#5424]
Hey, you maybe know me already, im sorry for still asking about the red numbers, but I really have to say that why the hell I have just problems with Zrips plugins. What can I do?

Please check my timings: https://timings.pl3x.net/?id=90038df7e9a04200944f81647f4535ae#plugins and if you can, tell me what can I do, im hopeless that I can fix that by my own. Still problems and big numbers with plugins: **CMI, TradeMe and Jobs**. There is nothing to do about it and I really need help with that.

Most I can see something like WarmUpManager, but I have no clue what is wrong with that, I have no WarmUps enabled.

**Comment by Zrips** [comment]
Warmup manager will trigger commands after its timer is up, so any command which was set to be performed after certain warmup will show up in timings under that section. Its not that warmup itself caused load, its commands which got performed dragged it down and it seams to be mostly teleportation events which are usually most heavy things as we have to load in chunks before player gets teleported to target location, which again gets put under same warmup section. Will investigate what could be optimized to lower those numbers down.

**Comment by naikyy** [comment]
Yes, I know how Warmup works, but in config.yml I got enabled to false, so thats weird. Should I try to disable the module to false? I am not using Warmup actually.

**Comment by naikyy** [comment]
Okay, I disabled warmup in modules.yml, seems to be fixed but last two problems are: https://i.imgur.com/qwNEidj.png

1) com.Zrips.CMI.commands.list.rt$1$1
2) Command: CMI:cmi - but there I really have no idea what to do.. :D

**Comment by Zrips** [comment]
Rt command requires for plugin to check quite few things to find best location to place player before teleporting him there, so it might be on heavy side by its nature. 
cmi:cmi is how minecraft handles them by default, cant really do anything about this at this moment.
