### ISSUE TITLE
Warp remove Group

### ISSUE THREAD

**Issue by JaTiTV** [Zrips/CMI#5426]
Warp remove Group
---

if i want to remove a warp from a group with via the gui and then enter remove in chat then it puts the warp in the group remove

---

Cmi Version: 8.8.2.10

This server is running Paper version git-Paper-581 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 3 version(s) behind
Previous version: git-Paper-416 (MC: 1.16.4)

**Comment by Zrips** [comment]
Should work better with new version and new warp edit list
