### ISSUE TITLE
White(&f) is Missing in Public/Private Color Message Permission

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#5427]
**Description of issue:**
White(&f) is Missing in the public and private message section of the result of /cmi colorlimits
Also, these two permisssions cmi.colors.publicmessage.white and cmi.colors.privatemessage.white are not included in cmi.colors.publicmessage.* and cmi.colors.privatemessage.* .

![image](https://user-images.githubusercontent.com/22321097/114195639-38582b80-9983-11eb-99db-9952b313f922.png)

---

**Cmi Version (using`/cmi version`):** 
8.8.3.0
**Server Type (Spigot/Paperspigot/etc):** 
Tuinity
**Server Version (using `/ver`):** 
1.16.5

**Comment by CloudeLecaw** [comment]
its not missing your "japanise?" letters are just interrupping

Best way is you correct it by yourself in the langualgae file.
Open your used langfile (what lang you useing u see in config.yml in the fist lines.
```
# Language file you want to use
Language: DE
```
here the original parts from the langfile

```
  colors:
    help:
      info: '&eShows all possible colors'
      args: (playerName)
    info:
      List:
      - '&e***************************************'
      - '     &0&%0  &1&%1  &2&%2  &3&%3  &4&%4  &5&%5  &6&%6  &7&%7'
      - '     &8&%8  &9&%9  &a&%a  &b&%b  &c&%c  &d&%d  &e&%e  &f&%f'
      - '       &%k - &kMagic&r      &%l - &lBold'
      - '       &%m - &mStrike&r     &%n - &nUline'
      - '       &%o - &oItalic&r      &%r - &rReset'
      - '&e***************************************'
```

**Comment by CloudeLecaw** [comment]
i cant agree this
![Snag_f183964](https://user-images.githubusercontent.com/12080017/114265109-4fccfe00-99ef-11eb-988a-a4322a53f1b4.png)
![Snag_f18791d](https://user-images.githubusercontent.com/12080017/114265120-59566600-99ef-11eb-8589-2a69336272a0.png)

**Comment by Zrips** [comment]
All color codes and permission for them get generated using same code, so if its missing in one place it should be missing in all of them and vise versa. You might simply have negated permission node for while color usage for those specific places, while it not really matter for chat messages as they default to white anyways so you might simply never noticed that it is missing. 
Doesn't seam to be issue at this point.
