### ISSUE TITLE
Chat Issue

### ISSUE THREAD

**Issue by kristian198** [Zrips/CMI#5428]
**Description of issue:**
The point is, when I write in the chat url / web page with www or words with dots, for example: idk.idk.idk. It happens that he distorts the following words

![screen](https://user-images.githubusercontent.com/82224070/114199180-5e1a0c00-9954-11eb-8678-6708e972681d.png)
---

**Cmi Version (using`/cmi version`):**
8.8.3.0

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):**
git-Paper-582 (MC: 1.16.5)

**Comment by CloudeLecaw** [comment]
Its Just the default filter, you might need to edit your regex

**Comment by kristian198** [comment]
Hello, I have this filter turned off overall. Would you be able to send me a given regex that allows all urls?

**Comment by CloudeLecaw** [comment]
well you could try ours its not perfect but works for most

`  LinkRegex: (?i)((http|https|ftp|ftps)\:\/\/|www\.)(\w*\.)?[a-zA-Z0-9\-]+\.[a-zA-Z]{2,3}(\S*)`

**Comment by kristian198** [comment]
Okay, thank you and I really appreciate your help.
