### ISSUE TITLE
[Request] Option to exclude AFK time from playtime altogether

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#543]
An option to just exclude AFK time from CMI playtime altogether.

**Comment by Gasha666** [comment]
If that feature is going to be added would be cool if its going to show how much time did player spent while being AFK

maybe on /cmi cplaytime

**Comment by CloudeLecaw** [comment]
hm currently if the Player is AFK detected by CMI it does not Count for his time the time he is AFK.
so if he Plays 5 minutes and stand 2 weeks afk ingame then his playtime still would be 5 minutes… so yes a value that would Show us "he was afk now for two weeks" just for informing...would be cool

**Comment by TheWranger** [comment]
@CloudeLecaw CMI does include AFK in the play time, I think you're getting confused with how CMI filters AFK time from playtime reward requirements

**Comment by LogGits** [comment]
Cmi's playtime calc's do take into account afk time. There should be the config option `StopPlayTime: true`
