### ISSUE TITLE
Request:  Hologram API

### ISSUE THREAD

**Issue by SubliminalChaos** [Zrips/CMI#5430]
Hello, I have made requests of two dev of other plugins in the last month and they both told me the CMI API is not current, here is the one conversation I could find easily, with the developer of a really nice Roulette plugin:

>    Hi!
 >   Yes I understand your concern, someone already asked for CMI holograms support, the problem with it is that the API of CMI 
>  is outdated af, unfortunately there's nothing I can do but wait until Zrips update it.
>    That being said, I'll do my best to contact him.
>    Regards (y)

> AgustinEzequiel2, Mar 18, 2021 Last edited: Mar 18, 2021

I have no idea if the API is out of date, but since 2 devs have mentioned it - maybe you could add "update api" to what I am sure is a long to-do-list.  Please.

- Chaos

(It seems such a waste to add Holographic Displays to server on top CMI...)

**Comment by Zrips** [comment]
Its update now.
