### ISSUE TITLE
Specialized Commands not work on portals

### ISSUE THREAD

**Issue by RedAlphard** [Zrips/CMI#5431]
Hello,
the asConsole! or asFakeOp! they do not work on the Portal, with Interactive Command they work correctly, is it a desired thing?
The console does not report anything to me, not even something to signal the execution of the command.

**Cmi Version (using`8.8.3.1`):** 

**Server Type (Paper/Waterfall):** 

**Server Version (using `585`):**

**Comment by CloudeLecaw** [comment]
asFakeOp does not work in many many many cases monstly the otherplugins dont accept this

So paste your portal and i would belive its not a cmi command that should be executed ...rihght? ;)

**Comment by RedAlphard** [comment]
So if i run "asConsole! say Hello" the console does nothing, same thing if i do "asConsole! cmi broadcast Hello", no message either way, i use portals for almost everything so i know how it works if they changed that system I am not aware of it.

**Comment by CloudeLecaw** [comment]
you really should post your portal else we cant say aynthing but a broadcast asConsole! is not nessesary because the normal command allready is executed like that.
