### ISSUE TITLE
Ability to create your own GUI menus

### ISSUE THREAD

**Issue by Sav9El** [Zrips/CMI#5433]
I really want the CMI plugin to be able to create my own GUI menus, it would be very convenient and useful, so I am writing about it.

**Comment by jiajunmao** [comment]
There is another plugin called DeluxeMenu that can do this. No need for CMI to reinvent the wheel.

**Comment by CloudeLecaw** [comment]
> There is another plugin called DeluxeMenu that can do this. No need for CMI to reinvent the wheel.

i agree with that, we also use this plugin and it has perfect abilities to create own GUI menues in an easy way.

**Comment by mrfloris** [comment]
This isn't a bug, please post suggestions in the Discussion section on github.
