### ISSUE TITLE
Anvil: "Too expensive" although user has perm

### ISSUE THREAD

**Issue by pepechante28** [Zrips/CMI#5437]
**Description of issue:**

Even if people have "cmi.anvil.nolimits" perm. The message continues to appear as can be seen in the pic. (Also, I'm opped)
- I have a custom enchants' plugin, however, no matter if the item has or not those enchants, "too expensive" comes out anyway.

![image](https://user-images.githubusercontent.com/82343665/114322983-1ed4f200-9af1-11eb-82ef-58daf46aac99.png)

> With custom enchants:
>![image](https://user-images.githubusercontent.com/82343665/114323455-4cbb3600-9af3-11eb-8293-f1c536898e62.png)

> Without:
>![image](https://user-images.githubusercontent.com/82343665/114323573-d2d77c80-9af3-11eb-9e7e-4b7db291d760.png)

---

**CONFIG SECTION:**

> Dunno if might help, however this is the setup on modules.yml
> `anvilRenameColor: true`

---

![image](https://user-images.githubusercontent.com/82343665/114323153-01ecee80-9af2-11eb-9f2b-8af2815e9af9.png)

**Relevant plugins: LuckPerms (v.5.3.3), Golden Enchants (v2.10.1)**
**Proof of having the perm:**

![image](https://user-images.githubusercontent.com/82343665/114323710-77f25500-9af4-11eb-9598-dd05c1e15029.png)

**Comment by Zrips** [comment]
This feature got disabled few versions back due to some issues. Risk is not worth a reward at this point. Will update wiki.
