### ISSUE TITLE
[Reqest] Cost to run commands

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#544]
Ability to set a cost/tax for certain commands (configurable like command delays are).
Also
- /tpa system should have its own configurable cost (like it has an option for delays)
- An additional option that sets it so that if the player doesn't have a certain amount of money in their balance, the cost is ignored. Example: If a player doesn't have $1000 or more in their balance; they don't have to pay the cost/tax.

**Comment by MCTyler** [comment]
I'd like to link these 2 with this please.....
https://github.com/Zrips/CMI/issues/351
https://github.com/Zrips/CMI/issues/390

**Comment by TheWranger** [comment]
Alright, my bad, I'll close this.
(Though, 351 has nothing to do with what I want)

**Comment by MCTyler** [comment]
351 Money charge for a thing...Semi-related.
