### ISSUE TITLE
AFK players freeze

### ISSUE THREAD

**Issue by Tweeter1990** [Zrips/CMI#5452]
is there a value to set when player in afk then he´s freezed and can´t move from other players

Greetings Tweeter1990

**Comment by CloudeLecaw** [comment]
yes you can do this
ismply use the command `cmi playercollision (playerName) true -s ` when afk start and `cmi playercollision (playerName) false -s ` when afk ends.

**Comment by Tweeter1990** [comment]
Thank you very much for the fast answer

I tried this and dosen´t have a difference the command "cmi playercollision [playerName] true -s" doesen´t work
maybe you have a possibility to fix that or any other idea

Greetings Tweeter1990

**Comment by Zrips** [comment]
@Tweeter1990 
You might want to check config file and enable PreventPushing option. It might be some what derpy due to how minecraft now handles player pushing, but you should not be able to move player out of his original block area.
