### ISSUE TITLE
When you do /cmi suicide with a totem of undying you get 4 extra hearts

### ISSUE THREAD

**Issue by astomnll** [Zrips/CMI#5453]
when you do /suicide with a totem you get 4 extra hearts... im trying to fix this with a custom command but cant figure out what place holder works, please fix this like add a command from console if you have a totem in your hand or offhand this command happend

> cmi ctellraw [playername] <T> &cYou Cannot Use This Command With A Totem Of Undying In Your Hand </T>

**Comment by Zrips** [comment]
Will make some checks to prevent command usage while holding totem
