### ISSUE TITLE
How do I add mod items to worth.yml?

### ISSUE THREAD

**Issue by dd880602** [Zrips/CMI#5459]
worth:
  cgm:mini_gun:'10000'

The item cannot be added correctly!
what should I do?

**Comment by CloudeLecaw** [comment]
u cant that simply
its just for simple items
for mod items u need a shop plugin

**Comment by the456gamer** [comment]
I'm not 100% on how bukkit (and by extension cmi) handles modded blocks, but what if you try the cmi set worth command ingame?

**Comment by Zrips** [comment]
this cgm:mini_gun:'10000' isint even valid yaml format so it should fail in any case. For moded item handling, well, it will not work as entire plugin is based on vanilla items and uses internal itemdatabase to parse them. 
Modded servers introduce too many variables for plugin in size like this to handle all of them, this is why plugin doesn't support any of them. If something works, then it works, but when it comes to things like this, it will struggle to recognize custom items.
