### ISSUE TITLE
Gradiented link doesn't work

### ISSUE THREAD

**Issue by AkuaFite** [Zrips/CMI#5467]
**Description of issue:**
When link is between hex gradient ( {#fff000>}LINK{#ffffff<} ) it doesn't work when smb click on it.
Doesn't work:  ![image](https://user-images.githubusercontent.com/81054821/115712001-86523380-a374-11eb-90dc-482309507fde.png)
Works:  ![image](https://user-images.githubusercontent.com/81054821/115712050-966a1300-a374-11eb-843a-03b369860cde.png)

---

**Cmi Version (using`/cmi version`):** 
8.8.3.5
**Server Type (Spigot/Paperspigot/etc):** 
Tuinity
**Server Version (using `/ver`):** 
git-Tuinity-"94f025a" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by CloudeLecaw** [comment]
Jep better u use a ctellraw and use single hex colors there ;) then u can use <URL>link</URL> behind and also a nice hover if u want

**Comment by AkuaFite** [comment]
> Jep better u use a ctellraw and use single hex colors there ;) use` <T>Your link with sinhle hex colors for each symbol</T>`. You can also add a nice hover `<H>Hovertext</H>` if u want after the text. Then use. `<URL>link</URL>` behind and. Done your clickable hexcolored link is ready :)
> 
> Here a little example
> 
> ```
> cmi ctellraw [playerName] <T>{#b32000}&lL{#b36000}&lu{#719900}&ll{#569900}&lu{#009950}&lN{#008059}&le{#009099}&lw{#005999}&ls</T><H>Hier klicken um den Link für die LuluNews zu erhalten.</H><URL>http://mc.lululand.de/wiki/index.php/Features:News</URL>
> ```
Can I send it to all players at once, like broadcast! in announcer schedule?

**Comment by CloudeLecaw** [comment]
yes with "all" instead of [playerName] that how we designt all our bradcasts too^^
