### ISSUE TITLE
hex color

### ISSUE THREAD

**Issue by SmallFood1026** [Zrips/CMI#5473]
My English is not very good, sorry
I want to ask cmi
How to Disable hex
I did not give permission but the player can use hex

**Comment by Zrips** [comment]
Check /colorlimits in general if you give permission with wild card, ending with *, then players will have access to all colors including hex

**Comment by SmallFood1026** [comment]
![問題1](https://user-images.githubusercontent.com/75075197/115899383-459c0c80-a491-11eb-8d8f-96cabd6938c7.PNG)
![問題2](https://user-images.githubusercontent.com/75075197/115899401-4a60c080-a491-11eb-8902-91381db9cc72.PNG)
But I did not give permission at all

**Comment by Zrips** [comment]
You can always disable colors from public messages in config file under Colors->PublicMessage section

**Comment by SmallFood1026** [comment]
I just want to make color codes available to VIP
If you set PublicMessage false
Players can use

**Comment by Dracathio** [comment]
> I just want to make color codes available to VIP
> If you set PublicMessage false
> Players can use

So, I take it you must be using some form of permission plugin right?  Such as LuckPerms?

There should be a permission node for colors for CMI, so what you do is you put that permission node in the default ranks, then you make the permission false.  This is how you stop others from being able to use a feature when a plugin doesn't wish to work properly.  Then you go and make the VIP permission node as true.

**Comment by CloudeLecaw** [comment]
Wenn it is set to false then everyone can use it. if you set it to true then you need the permissions to use it
