### ISSUE TITLE
Cost of home command bug.

### ISSUE THREAD

**Issue by pupshadow** [Zrips/CMI#5475]
**Description of issue:**

Hello my issue starts with when you do /home and it will tp you to your home but not charge you when you have it setup in the command cost. 

It charges for when you do /homes and then select the bed but if you just do /home without even selecting bed it bypasses the cost of the command.

I have cmi being the only plugin that deals with home itself.

**Cmi Version (using`/cmi version`):** 

CMI: 8.8.3.5 SqLite
[02:18:01 INFO]: CMILib: 1.0.0.2
[02:18:01 INFO]: Server: Paper(602) 1.16.5-R0.1-SNAPSHOT
[02:18:01 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: True
[02:18:01 INFO]: Modules -> 52 enabled 3 disabled: ranks, votifier, portals

**Server Type (Spigot/Paperspigot/etc):** 

Paper

**Server Version (using `/ver`):** 

This server is running Paper version git-Paper-602 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 23 version(s) behind
Previous version: git-Paper-584 (MC: 1.16.5)

**Relevant plugins (Delete if this isn't needed):**

Plugins (51): AdvancedNMotd, AntiXRay, AutoRestart*, BentoBox, ChestSort, ClearLag, CMI, CMILib, CoreProtect, DeadChest, dynmap*, eZProtector, EZRanksPro, floodgate, Geyser-Spigot, Harbor, Holograms, Lands, LibsDisguises, LuckPerms, LWC, MineConnect, MoneyFromMobs, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MythicLib, MythicMobs, MythicMobsExtension, PlotSquared, PlugMan, ProtocolLib, PureTickets, ServerSigns, ShatteredCore, ShatteredScrolls, SkinsRestorer, StaffFacilities, TreeAssist, Vault, ViaBackwards, ViaRewind, ViaVersion, Vivecraft-Spigot-Extensions, VoidGenerator, WarpSystem, WorldBorderAPI, WorldEdit, WorldGeneratorApi, WorldGuard, WorldGuardEvents

**Comment by Zrips** [comment]
Will make some changes relating how we handle home command without provided home name. Should be in working order with next update
