### ISSUE TITLE
perms for asConsole!

### ISSUE THREAD

**Issue by levarar** [Zrips/CMI#5476]
Problem with permission for /cmi attachcommand, CMI doesn`t require perms, example, 
/cmi attachcommand !cc! cmi heal Player - perms cmi.command.attachcommand.cc
/cmi attachcommand asConsole! cmi heal Player - what is the permission for this args? (asConsole!) ?

I want deny players to be able to write from the console through /cmi attachcommand
Also i want to deny next specialized commands:
asFakeOp!
kickall!
allPlayers!

**Comment by CloudeLecaw** [comment]
U only need permission when creating it not when using it when it has cc u need to use it just correct not like in your example

**Comment by Zrips** [comment]
@levarar 
Attached commands utilizes specialized commands, so if you really want to use permission check you can use **perm:[permission]!** check. other than this, asConsole! is meant to perform command in same way as it would be done from console, so permissions are checked against console and not the player who initialized this command.
