### ISSUE TITLE
[Request] Option to auto-remove used potion bottles

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#548]
An option that automatically removes empty bottles from players inventories after they've drunk a potion.

**Comment by TheWranger** [comment]
There should also be some sort of permission associated with it.
Either a bypass permission or a required permission that players must have for used bottles to disappear.

**Comment by tmellen** [comment]
But they are reusable!

**Comment by TheWranger** [comment]
Not if you're running a duels server or a server where people cant brew potions.

**Comment by CloudeLecaw** [comment]
like The Wranger said allready.
a feature like this would need a Bypass permission so you dont kick all survivalserver is their asses ;)

**Comment by TheWranger** [comment]
It would also have a toggle option in the config.
