### ISSUE TITLE
Infinite teleportation: /tpa

### ISSUE THREAD

**Issue by ohAleee** [Zrips/CMI#5486]
**Description of issue:**

When a player accepts a tpa, the one present in the video happens: the player is continuously teleported to the same point. When I tried to take the vanish off because I went to see what was going on, he didn't take the boss bar off

[https://vimeo.com/541583675](url)

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/36593455/116071767-93319880-a68e-11eb-9239-d2877fcebc01.png)

**Server Type (Spigot/Paperspigot/etc):** 
Tuinity

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/36593455/116071805-9cbb0080-a68e-11eb-943c-26e1decdcc01.png)

**Comment by Zrips** [comment]
You will need to retest this with default configuration to rule out any custom alias or event command or something else creating this effect. If that doesn't help, try testing with CMI only to rule out interference from another plugin

**Comment by mrfloris** [comment]
8.8.2.x is quite outdated, especially for 1.16.5 it can really help to update to 8.8.3.x
