### ISSUE TITLE
Add Most Differentiation for Vanish

### ISSUE THREAD

**Issue by ItLucifer-MRPG** [Zrips/CMI#5494]
When you give a player the perm to see vanished people, you can see their whole body, and it can be hard to tell who is vanished and who isnt, If you could add something to show they are vanished, like make their body invisible but you're able to see their head, and maybe change how you see their name in tab by making it translucent or something (gray it out). I would make seeing who is vanished and who isnt alot easier, especially in a server where you give players vanish as a perk of a rank, etc.

**Comment by CloudeLecaw** [comment]
u allready can do this
its called the vanished state ;)
