### ISSUE TITLE
/home not brining up GUI

### ISSUE THREAD

**Issue by xxirs** [Zrips/CMI#5497]
Set 
Homes:
  # Open gui when using /cmi home command if you have more then one home in your saved list
  Gui: true

In config.yml, set multiple homes in game and type /home. It should bring up the GUI instead it goes to the first created home.

LATEST
AIRPLANE
Airplane-"bbd689a" (MC: 1.16.5)

**Comment by CloudeLecaw** [comment]
Have you given permission for
cmi.command.home and cmi.commands.homes?

**Comment by xxirs** [comment]
Yes they have cmi.command.home and cmi.command.homes

**Comment by xxirs** [comment]
Tested already works the same with paper or spigot.

**Comment by CloudeLecaw** [comment]
ok i can agree this now it definalty is a bug from last version

We have it now to /home does not open the GUI it ports to the first home

![Snag_1c709b05](https://user-images.githubusercontent.com/12080017/116300474-396cc380-a79f-11eb-832c-5fdcfcd09838.png)

**Comment by Zrips** [comment]
Confirmed, will be fixed with next build
