### ISSUE TITLE
[Bug] BedInteraction 

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#550]
Even when `BedInteraction` is set to `false` in config, users with `cmi.bedhome` are still able to set their CMI homes by interacting with a bed.

**Comment by CloudeLecaw** [comment]
that is normal ;)

**Comment by Zrips** [comment]
@TheWranger When its set to false, while interacting with bed you will set bed location by using official bukkit API. That means that players can respawn at bed after death, but it will not be saved as Home location by CMI itself. Well, exactly what comment section says.
