### ISSUE TITLE
/reply working for messaging with vanish people

### ISSUE THREAD

**Issue by SaintDevastatoR** [Zrips/CMI#5502]
Hello,

I would like to request a feature. It this moment it is possible to toggle the possibility of sending a private message to a vanished player. I would like to request the option to make it possible that people cannot message vanished people but are able to use /reply to reply to a message from a vanished player.

Kind regarts,

SaintSDevastatoR

**Comment by CloudeLecaw** [comment]
To let this work its not enough to just block reply. You also need a feedback meassage for it like. "That player is not online" else it would be no god feature. Epse if i reply a vanished player and there is no reaktion innchat, then i would know "ok hes there but its blocked"

**Comment by Zrips** [comment]
Okey
