### ISSUE TITLE
Comparator missing from tab complete

### ISSUE THREAD

**Issue by Verdux** [Zrips/CMI#5507]
Comparator doesn't show up in tab complete when doing /cmi recipe command, typing it and pressing enter will show the recipe.

![image](https://user-images.githubusercontent.com/53581936/116473185-c92d7300-a86e-11eb-9191-0e7d210c0211.png)

---

**Cmi Version (using`/cmi version`):** 
8.8.3.2 (slightly out-dated I know but I did check changelog)
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.5-582

**Comment by CloudeLecaw** [comment]
Wanne know why its missing?
 Becaue itsnname is not comperator
Its redstone_comperator
Allways use the itemnreal names notnthe displayednnames Ober item

**Comment by CloudeLecaw** [comment]
This ticket might can be closed, or doesnt it show Ou the redstone_comperator in the cmi recipe list?
Well if it doesn't pls post used cmi and server version first :)

**Comment by Zrips** [comment]
@Verdux 
In general it is named as redstonecomparitor, but will make some small changes to include some specific material names
