### ISSUE TITLE
Name of renamed containers doesn't show while in vanish

### ISSUE THREAD

**Issue by Grizzly90** [Zrips/CMI#5510]
**Description of issue:**
Name of renamed containers doesn't show while in vanish. The name only shows "Chest"

---

**Cmi Version (using`/cmi version`):** 8.8.3.6

**Server Type (Spigot/Paperspigot/etc):** Paper
**Server Version (using `/ver`):** git-Paper-631 (MC: 1.16.5)

**Comment by Zrips** [comment]
CMI doesn't modify item lore or names or anything like that while you are in vanish, you might want to check your other plugins or your client, but this is not related to CMI features.

**Comment by Grizzly90** [comment]
Please recheck yourself.

Paper server, only cmi. 
The name of a placed is displayed correct while not in vanish... But while in vanish it only shows chest. Also chests which are not renamed show "chest" instead of "Truhe", which is displayed as it should while not in vanish
