### ISSUE TITLE
Question about Kits

### ISSUE THREAD

**Issue by Snele** [Zrips/CMI#5515]
I want the kit to give a random book with enchantments (or with certain enchantments, but of different levels). 
How do I do this?

**Comment by CloudeLecaw** [comment]
u can do this by command inside the kits use the give command for it with random placeholder for the lvl
for the enchant u cant

**Comment by Snele** [comment]
It's a pity that can't give out random enchantment :(

**Comment by CloudeLecaw** [comment]
randomized command just can be done in the scheduler not in kits
same for random enchantsments. - not in kits for now - not with cmi.
