### ISSUE TITLE
cmi plugin: fixchunk all, not work and all commands related to this 

### ISSUE THREAD

**Issue by nazgool97** [Zrips/CMI#5518]
I can not do it!
when i write the command: fixchunk all
writes this error

Cmi Version: 8.8.3.6

Server Type: Spigot

Server Version 1.16.5

![изображение_2021-05-01_082004](https://user-images.githubusercontent.com/83346984/116771836-0738bb80-aa56-11eb-87df-2a57d051c24e.png) 
plugins
![Снимок экрана 2021-04-28 143023](https://user-images.githubusercontent.com/83346984/116771608-95f90880-aa55-11eb-822a-d5fae65eb2ca.png)

**Comment by mrfloris** [comment]
Yes, fix chunk is not a 1.16.x feature, it's still in cmi for people on older versions, from what i understand.

**Comment by nazgool97** [comment]
it won't work on 1.16 ?

**Comment by CloudeLecaw** [comment]
> it won't work on 1.16 ?
jep you it. the fix chunk command does not work on 1.16.+ servers
If you have an older server then you can use it.

**Comment by Zrips** [comment]
Due to changes in minecraft API in recent versions chunkfix no longer works in those. So its still a thing for older version, but not for recent ones, atleast until i can think of new approach for it.
