### ISSUE TITLE
[Request] Ability to change biome names in locale

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#552]
Ability to change the names of biomes in commands such as `/cmi pos`.

**Comment by CloudeLecaw** [comment]
so it is still a palceholder that gets replaces with the name of the Biom.. hm finaly i would say this is no good idea, we have near 75 biomes.... so near 75 new names and all other plugins work with biome names of the Client (or server?) (english by default i think) 
sO use the english names… i realy see no sense in renaming them, but ok like allways the dev has to decide^
jippi , have a other language Region in /cmi pos...so why? without a hook or anything the translated Information is a bit useless and if a Player of other Clientlanguage joins your Server he has no idea what your /cmi pos Infos tells there if he is not confirm with the lang. Maybe a Clientside Translation of biomnames would make more sense?
