### ISSUE TITLE
Incompatibility between combat commands & warm-ups

### ISSUE THREAD

**Issue by xxirs** [Zrips/CMI#5520]
Set in combat portion of config.yml
    BlockCommands: true
    AllowedCommands:
    - cmi spawn
    - cmi back
    - cmi dback
    MakeBlackList: true

Setup warmups in config.yml as follows
WarmUps:
  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: false
  showBossBarInfo: false
  List:
  - cmi spawn:5:false:GlyphHead
  - cmi back:5:false:GlyphHead
  - cmi dback:5:false:GlyphHead
________________________________________________________________________________

If you change either one of the warmups to have a space for exmaple ----->
cmi spawn:5:false:GlyphHead becomes cmi spawn :5:false:GlyphHead the command will now be disallowed when combat tagged however the command then becomes instant. Is this an intended feature or bug? Is there a way to make it respect the warmup + combat tag?

---

![versioncmi](https://user-images.githubusercontent.com/47906826/116786943-0c523680-aa67-11eb-8e49-506ed9d8e01e.png)

**Comment by xxirs** [comment]
@Zrips

**Comment by Zrips** [comment]
This will be fixed with next build
