### ISSUE TITLE
CMI ranks not showing jobs names

### ISSUE THREAD

**Issue by VojtechAdam29** [Zrips/CMI#5522]
**Description of issue:**
so in cmi ranks if there is job requirement it dont work, i have requirement miner:2 and im on level 2 and nothing

---

**Cmi Version (using`/cmi version`):8.8.3.5** 

**Server Type (Spigot/Paperspigot/etc):PaperSpigot** 

**Server Version (using `/ver`):git-Paper-390**

**Comment by mrfloris** [comment]
Can you includes your miner job so we can confirm the unique name?

**Comment by VojtechAdam29** [comment]
so in rank i have this
```
  JobsRequirement:
  - Miner:2
```

and in file Jobs/jobs/miner.yml i have this

```
Miner:
  fullname: Horník
```

**Comment by Zrips** [comment]
Issue with Jobs plugin in general. Issue fix at that end and will change code at CMI end to be more robust.
