### ISSUE TITLE
CMI chat (Global and local)

### ISSUE THREAD

**Issue by Snele** [Zrips/CMI#5525]
I want chat to be white (&f) when players write to the global chat, and gray (&7) when they write to the local chat.
Can you tell me how to do this? (This will help better navigate  in chat)
There are a lot of settings for the chat and I'm confused :(

**Comment by CloudeLecaw** [comment]
Simply define the chat format in config use the &7 and &f before the world massage.
You also can define a different format for each group :)

**Comment by Snele** [comment]
Thank you for telling me everything in detail, but I still can't separate the local and global chat by color.
It turns out either always white or gray.
Separating the colors into groups is not what I need...

**Comment by CloudeLecaw** [comment]
define your description of global chat
define your description of local chat

**Comment by Zrips** [comment]
@Snele 
You can change locale file section **shoutPrefix** into something like`   shoutPrefix: '&2'` and then for chat format add {shout} like
`  GeneralFormat: '&8[&8]&r %cmi_user_nickname%&r&f: &7{shout}'` and you should get green text when shout is sent and general color when its not a shout type message
