### ISSUE TITLE
Bungee wide player balance

### ISSUE THREAD

**Issue by WarWolf-1** [Zrips/CMI#5528]
It would be really nice to have support for synced balance across bungee. Can it be done?

**Comment by CloudeLecaw** [comment]
U know the solution allready rigth? Its called using a mysql database that all Our servers of your bungeenhave access too

**Comment by WarWolf-1** [comment]
Database config file clearly advises against sharing databases
"# ATTENTION! DON'T USE SAME DATABASE TABLES FOR MORE THEN ONE SERVER, YOU WILL HAVE UNEXPECTED ISSUES. EACH SERVER SHOULD HAVE ITS OWN DATABASE TABLE SETUP"

**Comment by CloudeLecaw** [comment]
Sharing means not using them at the same time.
Its a good solution. Without mysql u should not think of bungee anymore ;)

**Comment by WarWolf-1** [comment]
So you're saying it is ok to share the cmi database between bungee servers because the player is only connected to one of the servers?

**Comment by WarWolf-1** [comment]
But if 2 servers can't use the database at the same time, then the player balance can not be synced between 2 servers...

**Comment by CloudeLecaw** [comment]
U need an example now why its not possible?:)
- First the player cant be logged in at two servers at once.
- when he joins server a and sets 29  homes and give hisself 20000 milliin and leave
Then he also has 29 homes and 20000 millin on your server that might hasba total other concept
If you count one bunggee Network where the network itself is a whole server. Therr is no reason for notnsharing. The player still will be only one server. Abd if he has 20000 milln on serverpart a it might be wanted he also has it on serverpart b

**Comment by WarWolf-1** [comment]
But what if I only want to share balance and not other data like homes?

**Comment by CloudeLecaw** [comment]
This Share all and just use balance on other part of your bungee

**Comment by WarWolf-1** [comment]
Understandable, but maybe dev can enable us to only share certain features?

**Comment by CloudeLecaw** [comment]
Maybe he can add something there in the CmiBungee Extansion like he made it with modules. :)
