### ISSUE TITLE
cmi merchant

### ISSUE THREAD

**Issue by noxidevad** [Zrips/CMI#5532]
After searching in the cmi discord and even the most experienced user MrFloris hasn't interacted with this command, and with no documentation or anything in the .yml's, my question is

Is there anyway the trades can be locked, seems as if when you trade with a villager and close the gui, up-reopening the gui the trades reset (presumably because it's essentially a new villager)

This could potentially be a fun command to use for server, and i'd love to use this on my server. 

Additional queries
- Can the items be changed/limited
- Is it possible to create custom loot tables (ie for slimefun etc kinda things)
- Can the costs etc be adjusted
- With is the soul purpose of the command

Thanks
N0xid-Ev4D

**Comment by CloudeLecaw** [comment]
No you cant block trades. U need a plugin for that at the moment. But feel free to write a request :)

**Comment by noxidevad** [comment]
Morning
 Thanks for the quick reply and suggestion (will look at that plugin after work) 

Guess i will go ahead and request this as a feature

Thanks :)
