### ISSUE TITLE
cmi merchant

### ISSUE THREAD

**Issue by noxidevad** [Zrips/CMI#5534]
As from my question - https://github.com/Zrips/CMI/issues/5532

I would like to request a new feature to be introduced within CMI. that involves using /cmi merchant

Ability to create potential custom villagers (that can sell exactly what we wish them to sell, ie custom items such as Slimefun)
Ability 
Ability to edit the merchant gui (in-game potentially) kinda like your gui's already inside cmi like the kit editor
Ability to lock trades so users do not lose trades within that particular villager
Ability to have an admin type villager so 

Future perhaps
Ability for players to create there own villager shops.

Hopefully managed to explain myself well,

**Comment by CloudeLecaw** [comment]
Sounds like the plugin shopkeepers :)
