### ISSUE TITLE
Combatmode not working with warmup-commands

### ISSUE THREAD

**Issue by xmorose** [Zrips/CMI#5537]
**Description of issue:**

---

Combatmode not working with commands that have a warmup time
/spawn has a warmup time of 5 seconds, combatlog is 10 seconds
every command is getting blocked EXCEPT /spawn, that ones going through all the time

Removed the warmup time and it blocked the command
```
---

**Cmi Version (using`/cmi version`):** : 8.8.3.0, CMILib 1.0.0.2

**Server Type (Spigot/Paperspigot/etc):** Paper 1.16.5

**Server Version (using `/ver`):** git-Paper-586

**Comment by Zrips** [comment]
Should be fixed with next build
