### ISSUE TITLE
A placeholder that displays the time remaining for the schedule to take effect.

### ISSUE THREAD

**Issue by LvXP0** [Zrips/CMI#5547]
Visit https://github.com/Zrips/CMI/discussions/new to post new idea or suggestion
Posting new suggestion in ticket section could result in their removal.

I hope there will be a placeholder that shows the time remaining for the custom schedule to work in seconds, minutes, and hours.

ex) %cmi_schedule_\(scheduleName)\_remain_s%, %cmi_schedule_\(scheduleName)\_remain_m%, %cmi_schedule_\(scheduleName)\_remain_h%

**Comment by CloudeLecaw** [comment]
Nice idea ;D

**Comment by Zrips** [comment]
%cmi_schedule_nextin_[schedName]%
%cmi_schedule_endat_[schedName]%
Its thing already
