### ISSUE TITLE
bug with use potion "night_vision"

### ISSUE THREAD

**Issue by dimk-o** [Zrips/CMI#5557]
Description of issue: **when using the night vision potion, at night, everything turns black, as in the screenshot**
![unknown](https://user-images.githubusercontent.com/64072348/117600611-ef97bc00-b154-11eb-8562-1ae3e70e65ab.png)

Cmi Version : **8.8.3.10**
Server Type : **PaperSpigot**
Server Version : **git-Paper-642 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)**
Relevant plugins : **CMI only**

**Comment by CloudeLecaw** [comment]
This does not come from cmi
We are using night potion too and it works fine.
might you play with a coruppted ressourcepack? 🥉 
try night potion without CMI pls to see what happens....

**Comment by Zrips** [comment]
CMI doesn't control potion effects in any shape or form. You might want to double check this with a clean client and not modded one and with default resource pack.
