### ISSUE TITLE
Bug /setwarp

### ISSUE THREAD

**Issue by Sakanas** [Zrips/CMI#556]
**Description of issue or feature request:**
When using the /setwarp Survival command he created several warps.

[https://i.imgur.com/3h8X4AY.jpg](url)
[https://i.imgur.com/sI2c4Rb.png](url)

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## There are no errors in the console ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## DEFAULT CONFIG ##
#####################################
```

**Cmi Version (7.8.8.2`):** 

**Server Type (Paper(1471) 1.12.2-R0-SNAPSHOT):** 

**Server Version (1.12.2):**

**Comment by MCTyler** [comment]
Drag and Paste Pics on Here. Both those Links broke.

**Comment by Sakanas** [comment]
do not click on the link, copy the link
