### ISSUE TITLE
Name of renamed containers doesn't show while in vanish

### ISSUE THREAD

**Issue by Grizzly90** [Zrips/CMI#5560]
**Description of issue:**

as you obviously don't read reply to closed issues ( #5510  ) and I can't reopen the issue:

Server with paper and cmi only: I can't see the name of a renamed chest while in vanish. It also says "Chest" instead of "Truhe"(Minecraft in German) while in vanish. 

Please try it yourself: rename a chest. place the chest. Open the chest while in nomal mode an while in vanish.

**Comment by Zrips** [comment]
Ok ok, original ticket was a misunderstanding of actual issue. Reproduced it now and it should be resolved with next update. Sorry for inconvenience.
