### ISSUE TITLE
Variable no boolean in language file strings

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#5565]
**Description of issue:**
In the following strings of the Spanish language file, we have to use the variable equivalent to "Enabled or Disabled" instead of boolean for the result to be correct:
[command.fly.info]
[command.flyc.info]
[command.glow.info]
[command.god.info]
[command.playercollision.info]

---

**Cmi Version (using`/cmi version`): 8.8.3.10** 

**Server Type (Spigot/Paperspigot/etc): Paper(640) 1.16.5-R0.1-SNAPSHOT** 

**Server Version (using `/ver`): git-Paper-640 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)**

**Comment by Zrips** [comment]
Ok, got it now. Will redirect it to use "Enabled" "Disabled" lines instead of "true" "false" which will be more obvious what those do anyways and will be more appropriate for places its been used anyways.
