### ISSUE TITLE
Panimations break after some time

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#5568]
**Description of issue:**

After some uptime particle animations get broken and do not show particles in a desired way. Right after launch they work fine, but after ~10 hours of uptime players noticed that they got twisted in a weird way. I launched the local server to test and the animations work as intended. 

The broken animations are `custom1` and `custom3`, they are used when player teleports **from** or **to** home/warp locations respectively. Animation `custom2` is not affected.

`/cmi panimation` has exact same broken behaviour.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  custom1: circle;effect:end_rod;part:5;r:1.5;pitch:90;off:0,0.25,0;twist;maxd:5.0;move:0,0.3,0;fixed
  custom2: circle;effect:end_rod;part:2;r:0.25;pitch:90;off:0,0.25,0;rc:0.02;twist;maxd:5.0;fixed
  custom3: circle;effect:end_rod;part:5;r:1.5;pitch:90;off:0,5.0,0;twist;maxd:5.0;move:0,-0.3,0;fixed
```

---

**Cmi Version (using`/cmi version`):** 
8.8.3.10
**Server Type (Spigot/Paperspigot/etc):** 
Purpur (fork of Paper and Tuinity)
**Server Version (using `/ver`):** 
git-Purpur-1061 (MC: 1.16.5)

**Comment by Zrips** [comment]
Could you elaborate more on how exactly they look when they get broken? Like an image of some sorts or description.

**Comment by radiant-ai** [comment]
> Could you elaborate more on how exactly they look when they get broken? Like an image of some sorts or description.

Hello, this is very weird case. After the restart this issue did not reappear anymore.

However as per how they looked like. The `custom1` animation should be a circle moving up around the player starting at their feet, but in broken state it was appearing over the head and moving diagonally. `custom3` animation should've started over the player head and move down, but instead it was stuck at their feet.

As this issue does not appear anymore you can close it if you had no more similar reports.

**Comment by Zrips** [comment]
Will keep this report in mind, but at this point doesn't seam to be an issue for others. Maybe it was caused by some internal one time error which messed up those effects, who knows, hard to say anything extra about this without actual reproducible way.
