### ISSUE TITLE
CustomHeads drops pickup

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#5575]
CustomHeads drop heads. These heads appear to drop just like natural mob drops.

Prob. about 9 months ago, the heads suddenly could no longer be picked up by plugins that can automatically pickup mob/block drops. Something in CMI is changed what bypasses this.

Samples of these plugins that can automatically pickup mob and block drops:
- VKautopickup
- Drop2Inventory

I would like to restore this behavior so all drops including the CustomHeads to be picked up automatically by the player.

**Comment by Zrips** [comment]
As of testing Drop2Inventory seam to work as it should, getting head directly to inventory.

**Comment by Zrips** [comment]
You might have detect-legacy-drops disabled or something. Test with default config file as it was working out of the box.

**Comment by x1p** [comment]
I see now. It's a block drop instead of a mob drop. Although it's a mob that drops.

**Comment by Zrips** [comment]
I'm not modifying mob drops, as that one is more complex than simply dropping item on ground when its needed, so some plugins might not catch it and might fail to send item to players inventory.

**Comment by x1p** [comment]
Thank you very much for this rapid well explained response. This makes our player happy. Solved.
