### ISSUE TITLE
Wrong string use

### ISSUE THREAD

**Issue by Korinocho** [Zrips/CMI#5578]
Using the Spanish translation, if you want to overwrite an existing Warp, it use the english string instead of the spanish one:
![image](https://user-images.githubusercontent.com/21372197/118347163-60edbb00-b517-11eb-9646-f34a8942270e.png)
Maybe its not pointing the right string.

**Comment by Korinocho** [comment]
@C4BR3R4 Puedes confirmarlo tu esto

**Comment by Zrips** [comment]
@Korinocho 
You might still have outdated locale or atleast that line is. Simply update your locale file with newest one from github or remove it and let it to be redownloaded. This will resolve your issue

**Comment by C4BR3R4** [comment]
> 
> 
> Using the Spanish translation, if you want to overwrite an existing Warp, it use the english string instead of the spanish one:
> ![image](https://user-images.githubusercontent.com/21372197/118347163-60edbb00-b517-11eb-9646-f34a8942270e.png)
> Maybe its not pointing the right string.

Lo pruebo y te lo confirmo esta tarde.

**Comment by C4BR3R4** [comment]
> 
> 
> > Using the Spanish translation, if you want to overwrite an existing Warp, it use the english string instead of the spanish one:
> > ![image](https://user-images.githubusercontent.com/21372197/118347163-60edbb00-b517-11eb-9646-f34a8942270e.png)
> > Maybe its not pointing the right string.
> 
> Lo pruebo y te lo confirmo esta tarde.
> ¿Que comando has usado?

![imagen](https://user-images.githubusercontent.com/4703920/118371600-9644e800-b5ad-11eb-860e-2e69d78fcfbd.png)
Te confirmo, como indica @Zrips que debe ser un problema relacionado con tu archivo de idioma.

**Comment by Korinocho** [comment]
Uh, ok. I will try deleting the localization file because im on the latest one
