### ISSUE TITLE
[Request] Infinite elytra flight

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#558]
Unlimited elytra flight for users with a certain permission.
Should replace plugins such as https://www.spigotmc.org/resources/superelytra-improved-elytra-flight.19382/

**Comment by 1ZQ** [comment]
With this Concept you need to make it, so the game says your going almost strait down, but going up, Do NOT make it so it teleports you slowly forward.

**Comment by Zrips** [comment]
With next update there will be extra permission node for this
