### ISSUE TITLE
worth.yml - MC 1.14 CustModelData support.

### ISSUE THREAD

**Issue by SubliminalChaos** [Zrips/CMI#5580]
Zrips, thank you for updating the hologram API - the developers for both plugins now support HolographicDisplays (old crappy way) AND CMI (save me having to have HolograhicDisplays plugin).

I notice that some plugins (CrateReloaded), although they say they do not support nbt/custom model data, if I use the 1.14 format for custom model data it works!!  Unfortunately, with CMI it does not.  I know adding support for nbt/custom items would be a huge undertaking, but I wonder if it could just easily (unknowingly like CrateReloaded) support the basic (mc 1.14) support for custom model data, so that this portion of the worth.yml file might sell my custom tomato, rice and other seeds - like this:

worth:
  WHEAT_SEEDS: '1.35'
  WHEAT_SEEDS{CustomModelData:1}: '3.22'
  WHEAT_SEEDS{CustomModelData:2}: '2.96'
  WHEAT_SEEDS{CustomModelData:3}: '3.02'
  WHEAT_SEEDS{CustomModelData:4}: '2.63'
  WHEAT_SEEDS{CustomModelData:5}: '2.97'
  WHEAT_SEEDS{CustomModelData:6}: '3.41'
 
If possible to do, without taking too much time from what I am sure is a never-ending to-do-list, it would be wonderful.  Thank you.

**Comment by CloudeLecaw** [comment]
Like written a lot of times now. This is not possible with Worth.yml and may not will be added.
Worth.yml is just for a basic worth of vanilla unmodded items.

**Comment by SubliminalChaos** [comment]
Thank you, will look to close, thank you.  Can find no shop plugin to appropriately support, thus the interests, I suspect.

**Comment by SubliminalChaos** [comment]
Closing.
