### ISSUE TITLE
No names after updating to 8.8.4.2

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#5582]
**Description of issue:**
After updating `%cmi_user_nickname%` placeholder is empty. /patrol and /tpa commands show no names. /near command also doesn't show usernames. Server jar was not updated.

---

**Cmi Version (using`/cmi version`):**
8.8.4.2

**Server Type (Spigot/Paperspigot/etc):**
Purpur

**Server Version (using `/ver`):**
Purpur-1105 (MC: 1.16.5)

**Comment by radiant-ai** [comment]
Looks like any command that displays player name in output no longer does it, all player names are blank.

**Comment by Zrips** [comment]
/patrol doesn't have player name as option, or any variable in general.
/near only could suggest range of 100 and player name is not even a thing for it
%cmi_user_nickname% seams to return players name correctly if nick name is not set.
/tpa does include players name. 
You will need to retest all of this with a full server restart.

**Comment by radiant-ai** [comment]
> /patrol doesn't have player name as option, or any variable in general.
> /near only could suggest range of 100 and player name is not even a thing for it
> %cmi_user_nickname% seams to return players name correctly if nick name is not set.
> /tpa does include players name.
> You will need to retest all of this with a full server restart.

Update 1:
Players who never connected to the server after the update are not affected:
![image](https://user-images.githubusercontent.com/43506080/118533705-ffdc0800-b70d-11eb-81bc-a92323f93ad9.png)
Update 2:
The problem is that `cmi.sqlite.db` file have something missing in it after the update. The deletion of this file restored displaying of player names, but it is not the way to fix it in an active server with a lot of players.

**Comment by radiant-ai** [comment]
Update 3:

The issue was caused by the other plugin. I will contact the author about this problem. For some reason it did something weird with CMI db.

**Comment by radiant-ai** [comment]
If someone has similar issue you can relay them there: https://github.com/kangarko/ChatControl-Red/issues/1007
