### ISSUE TITLE
Close to death and /heal

### ISSUE THREAD

**Issue by iBuseWinner** [Zrips/CMI#5583]
**Description of issue:**
When you close to death and use command /heal you will be immortal.
![image](https://user-images.githubusercontent.com/44753872/118390160-4827f700-b636-11eb-8610-93844f058191.png)

---

---

**Cmi Version (using`/cmi version`):** 8.8.3.10

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** git-Purpur-1082 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by CloudeLecaw** [comment]
and you let normal players use heal? ;D

**Comment by iBuseWinner** [comment]
> and you let normal players use heal? ;D

Not for all players ofc...

**Comment by CloudeLecaw** [comment]
well interesting thing, could you reproduce this with spigot too? i was not able to reproduce it with paper 1.16.5 nor spigot 1.16.5..

**Comment by Zrips** [comment]
@iBuseWinner 
Could you elaborate more on this "immortality"? Do you mean that players can save themselves by using heal before they die or that there is a bug which causes players to become literally immoral?

**Comment by iBuseWinner** [comment]
> @iBuseWinner
> Could you elaborate more on this "immortality"? Do you mean that players can save themselves by using heal before they die or that there is a bug which causes players to become literally immoral?

They becomes literally immportal

**Comment by Zrips** [comment]
@iBuseWinner 
Could you maybe produce a video showing this effect? Or atleast show output of /cmi info [playerName] as heal command should not make anyone imortal as its only setting its hp. Will do some testing, but it seams to be quite isolated bug which can be hard to reproduce.

**Comment by Italoplcl** [comment]
![2021-05-17_19 45 59](https://user-images.githubusercontent.com/58242083/118735834-3f3e4d80-b80f-11eb-8c5b-1caabd6e63e2.png)

**Comment by CloudeLecaw** [comment]
what we see in this pircture?
a player that is dieing at the moment and an other one that is sneaking to him?

**Comment by iBuseWinner** [comment]
> @iBuseWinner
> Could you maybe produce a video showing this effect? 

I'll ask player who tell about this bug
