### ISSUE TITLE
Nonsens will be suggested after the 3rd argument in /r  T9?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5584]
whem i am using the /r command to write back
after the 3rd argument the chat seems to suggest ALL worlds he might found somewhere..
like a Mobilfone T9...
is there any chance to disable this behave of tabcomplete?

![Snag_127b6bc6](https://user-images.githubusercontent.com/12080017/118415016-3121ed00-b6a8-11eb-95f8-824a7d39a7de.png)

![Snag_127b973b](https://user-images.githubusercontent.com/12080017/118415022-37b06480-b6a8-11eb-9b6d-35afe57ab5e2.png)

![Snag_127bc2a0](https://user-images.githubusercontent.com/12080017/118415026-3e3edc00-b6a8-11eb-8d62-a683e521b17e.png)

![Snag_127c67d9](https://user-images.githubusercontent.com/12080017/118415043-57e02380-b6a8-11eb-900c-491f3fa9b51a.png)

**Comment by Zrips** [comment]
Try testing this with CMI only, currently cant reproduce this issue and it would be nice to know if this originates from CMI or is this compatibility issue.

**Comment by CloudeLecaw** [comment]
ok i will try to reproduce it when i am home.
just wondering that it is affecting /r  but not /cmi reply :§
but i will test it and tess you my results
