### ISSUE TITLE
Spawn on Join Permission

### ISSUE THREAD

**Issue by MrNutman** [Zrips/CMI#5585]
Visit https://github.com/Zrips/CMI/discussions/new to post new idea or suggestion
Posting new suggestion in ticket section could result in their removal.
I can see in the config of CMI that you have a spawn on join option for true or false. Please could you make this permission based so that users with a bypass permission do not get teleported to spawn on join.

**Comment by CloudeLecaw** [comment]
You can add a joinevent and ask if playername is in choosen group (permission group) then spawn. If he is not, then nothing Happens.

**Comment by MrNutman** [comment]
> You can add a joinevent and check if playername is in choosen group (permission group) then spawn. If he is not, then nothing Happens.
> Use the eventCommands.yml for that :)
> Example:
> 
> ```
> joinServer:
>   Enabled: true
>   Commands:
>   - check:%cmi_user_group%==player! cmi spawn [playerName] -s
> ```
> 
> This would check if the joined player is inside group player. If he is then he gets to spawn
> 
> Thus works fine with a plugin like pex. I dont.know if plugins like luckperms or others might need an other placeholder...

Ah ok, I am rather new to using this plugin so was not aware I could use a 'check' as part part of the join server event. I will give it a try thank you. I do use luckperms so will have a play around with the placeholders and see which one I need

**Comment by CloudeLecaw** [comment]
You can take a look here what you can use.
Well most of the specialized commands
https://www.zrips.net/cmi/commands/specialized/

**Comment by Zrips** [comment]
Will add cmi.spawnonjoin.bypass permission node for convenience sake
