### ISSUE TITLE
Dupe when used /hat and someone killed you

### ISSUE THREAD

**Issue by iBuseWinner** [Zrips/CMI#5588]
**Description of issue:**
When you used /hat (for e.g. shulker with items) and other player kills you we get 2 shulkers (sometimes)

---

---

**Cmi Version (using`/cmi version`):** 8.8.3.8

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** This server is running Purpur version git-Purpur-1098 

**Relevant plugins (Delete if this isn't needed):** idk but I think that AdvancedEnchantments helps this bug

**Comment by Zrips** [comment]
Will prevent shulker boxes with items in them to be used as hats, but this seams to be more an issue with another plugin dropping items on ground on players death in some situations in addition to actual drop. You will need to retest this and atleast get some consistent way to reproduce this issue, tho at minimum this needs to be confirmed to originate from CMI by testing without any other plugin present but only CMI.

**Comment by iBuseWinner** [comment]
Hey @Zrips I found this version of bug description 
https://youtu.be/3NZefmcMJj8

**Comment by iBuseWinner** [comment]
And some player told me another way to dupe.

Wear iron helmet and take shulker with items.
When shulker in hand use /hat and when helmet in hand just right click on it.
With some chance will be dupe.


So your fix isn't working, I still can wear shulker with items in it.
