### ISSUE TITLE
OpenShulker.Shift broken

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#5589]
**Description of issue:**
CMI `8.8.4.3` breaks opening Shulker boxes by shifting.
Worked fine under `8.8.4.2`

Permission `cmi.openshulker.shift` is true`
Nothing else has changed since.
Double checked by testing on a test server.

---

**Cmi Version (using`/cmi version`):** 
8.8.4.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.5

**Comment by iBuseWinner** [comment]
Confirm.

Using Yatopia version git-Yatopia-ver/1.16.5-115 and CMI 8.8.4.3


It working with some shulkers (maybe they are old and because of that they working :/)

**Comment by Zrips** [comment]
Will get fixed with next update. Old shulker boxes should still work, just new ones got ignored.
