### ISSUE TITLE
MOTD is not showing multiple lines

### ISSUE THREAD

**Issue by stifflered** [Zrips/CMI#559]
I have been using /setmotd successfully for quite a while with no problems.

As of today, when I type `\n` in the motd, it does not separate the text onto a second line. It just shows the `n`. When I type `/n`, it breaks the lines up in the chat correctly, but then when I exit the server and look at the MOTD on the server list, the lines are not separated and the `n` shows again.

![setmotd](https://user-images.githubusercontent.com/5891184/42124009-4e93910a-7c21-11e8-9cf1-a34e04c8b8ff.PNG)

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**Cmi Version (using`/cmi version`):** 7.8.7.2

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.12.2 642f6d2-fbe3046

**Comment by CloudeLecaw** [comment]
i tested with the line that Guddina-tim shows us… works fine.
so may you have an other problem...Maybe a permissionthing (the eveil cause of most issues :3)?

> /cmi setmotd &a&lWelcome to &2&lTreeCrafters Online!\n&cTC Plugin temo disabled. Don't place new Pylon

![image](https://user-images.githubusercontent.com/12080017/42203739-0538c878-7ea0-11e8-9538-2b71c8e0a53b.png)
![image](https://user-images.githubusercontent.com/12080017/42203773-1e8f93f6-7ea0-11e8-9f0d-912f7078c6ca.png)

tested it and seems to work fine
![image](https://user-images.githubusercontent.com/12080017/42203885-6921ffe4-7ea0-11e8-9a6e-c2df7aa4ed81.png)

**Comment by Guddina-tim** [comment]
It's the strangest thing. This hasn't happened until the last few days. I
tried different variations of \n and /n, with spaces before and after and with
no spaces, and still the same results. When I use /n it will show the line
breaks properly in chat, but not on the server list page. When I run \n it
always shows an "n" where the line break should be. I am OP, so there shouldn't
be a permission issue.
Will try a few other things later and report back.  





On Tue, Jul 3, 2018 2:08 AM, CloudeLecaw notifications@github.com  wrote:
i tested with the line that Guddina-tim shows us… works fine.
so may you have an other problem...Maybe a permissionthing (the eveil cause of
most issues :3)?

/cmi setmotd &a&lWelcome to &2&lTreeCrafters Online!\n&cTC Plugin temo disabled.
Don't place new Pylon




tested it and seems to work fine

**Comment by Guddina-tim** [comment]
Also, sorry I missed your request Zrips. Here are the command variations I've tried:

```
/setmotd &a&lWelcome to &2&lTreeCrafters Online! &cTC Plugin temp disabled. Don't place new Pylons.

/setmotd &a&lWelcome to &2&lTreeCrafters Online! \n &cTC Plugin temp disabled. Don't place new Pylons.

/setmotd &a&lWelcome to &2&lTreeCrafters Online! /n &cTC Plugin temp disabled. Don't place new Pylons.
```

**Comment by CloudeLecaw** [comment]
could u do us a favor and use  /cmi setmodt ...just to be sure its not an essentials or other plugin that is doing that

**Comment by Guddina-tim** [comment]
Here is my plugin list. I don't use Essentials, BUT using /cmi setmotd actually worked correctly. It may be an updated version of a plugin I'm using which modifies some chat output. I'll look into that. If you see any suspicious plugins on this list, I'll be grateful for the pointer.

![pl](https://user-images.githubusercontent.com/5891184/42269635-462a7f80-7f44-11e8-8939-42bfe5468723.PNG)

**Comment by CloudeLecaw** [comment]
Who, intersting setup of plugins...
to be honest i dont know most of them so i have no idea what is interacting there,
on my server it would be easy to analyse by simply enabling the permscanner and see that reacts all on entering the setdmodt.

for no i just can recomment to check the following
file: Slias.yml
here the option should be
```
  # /cmi setmotd $1-
  /setmotd: true
```
