### ISSUE TITLE
/Skins puts players in "Creative" mode unless they die

### ISSUE THREAD

**Issue by strahil211** [Zrips/CMI#5592]
**When using /Skin, /Skins, /Skin update, or /Skin off
players are put in to this Fake Creative mode and can't get out of it unless they die.
Skins change and work perfectly but it is very inconvenient when the only way to get back into survival mode is to die each time, is this intentional or a bug?**

---

---

**Cmi Version (using`/cmi version`):** 8.8.4.4

**Server Type (Spigot/Paperspigot/etc):** Airplane

**Server Version (using `/ver`):** 1.16.5

**Comment by strahil211** [comment]
Not sure if it makes a difference but I am using 
git-Airplane-"5fab6a2" (latest as of time of this post) and Java 16

**Comment by strahil211** [comment]
Switched to Paper, Removed all Plugins except CMI, problem is still there.
Will continue down the rabbit hole to figure out what it might be.

**Comment by strahil211** [comment]
Ruled out Java 16 as the cause, tried Java 14 and Java 11 and problem still there

**Comment by rockitseven** [comment]
I have exactly the same problem. I am on paper 1.16.5

**Comment by Zrips** [comment]
Gets a fix with todays update
