### ISSUE TITLE
Custom aliases parse placeholders from player inputs

### ISSUE THREAD

**Issue by Lukos31** [Zrips/CMI#5593]
**Description of issue:**
Custom aliases parse placeholders from player inputs

Ordinarily players should be unable to access placeholders from commands, however using inputs from custom aliases it is possible to parse them. If certain placeholder expansions are installed, this could create a security issue, as seen in the example below:

![image](https://user-images.githubusercontent.com/69782564/119155679-94d65c80-ba92-11eb-956d-62d5fbae4dcd.png)
This uses the "parseother" and "player" expansions to grab any online player's IP address

Even without the use of expansions, it's possible for an attacker to create combinations of placeholders that drain server performance (eg. recursive loops).

Some solutions could be either preventing placeholders from being parsed through custom alias arguments entirely, or an option for each alias to choose whether or not placeholders can be parsed (some people may want to be able to parse placeholders through commands as admins, so an option defaulting to false may work best for everyone)

---

**Cmi Version):** 
8.8.3.9
**Server Type:** 
Paper/Spigot
**Server Version:** 
Paper-645
**Relevant plugins:**
Placeholder API

**Comment by Zrips** [comment]
Should be resolved with next update
