### ISSUE TITLE
Teleport location unsafe and people spawning in the ground

### ISSUE THREAD

**Issue by SSenZ0** [Zrips/CMI#5599]
### **Description of issue:**

we've found a VERY weird bug with 2 mods called underground biomes and Stygian End: Biome Expansion
whenever you set a home on one of the blocks from these mod and you teleport there, it teleports you into the ground to the first other block it can find that isnt from these mods.
at first we thought it was just a one time bug but then we also noticed that whenever you try to teleport to someone who's standing on block from these biomes it tells you this.

Teleport location is unsafe. Void

---

### **Cmi Version (using`/cmi version`):** 

CMI: 8.8.4.4

### **Server Type (Spigot/Paperspigot/etc):** 

Server: Mohist 1.12.2-R0.1-SNAPSHOT

### **Server Version (using `/ver`):** 

Mohist version 1.12.2-204 (MC: 1.12.2) API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2855

**Comment by SSenZ0** [comment]
as it turns out this is affecting more blocks from other mods too.

**Comment by Zrips** [comment]
Plugin isint made to support moded blocks as those might not have needed information about actual block size or type in general. Will make some changes relating to this, but cant promise that it will fix actual issue you are having here.

**Comment by SSenZ0** [comment]
> Plugin isint made to support moded blocks as those might not have needed information about actual block size or type in general. Will make some changes relating to this, but cant promise that it will fix actual issue you are having here.

Alrighty, thank you for considering looking into it, much appreciated.
