### ISSUE TITLE
/editwarp bug

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#56]
Using /editwarp sets that warps location to your own even if you do not click the "set new location button"

*I was only changing the custom icon, auto lore to false, and changing the slots in the gui when I realized every warp I was editing was being moved to my current location. I did not use the "set new location" button or accidentally click it. I am able to recreate this while making sure I do not click that button.

Also a note when you use /setwarp to set the location of an existing warp it resets its gui. Not sure if that is intended.

**Comment by Zrips** [comment]
Should be fixed with next update.
