### ISSUE TITLE
ClickHoverMessages including user prefix

### ISSUE THREAD

**Issue by Qinak** [Zrips/CMI#5601]
**Description of issue:**

When clicking on a user in chat to message them their rank prefix is included.

---

**CONFIG SECTION:**
```
  ClickHoverMessages: true
```

---

**Cmi Version (using`/cmi version`):** 8.8.4.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 720

**Relevant plugins:** LuckPerms-5.3.21

**Comment by Zrips** [comment]
Will extra variable as [playerNickName] which one can be used in ClickSuggestions section in config file which should return more appropriate suggestions when you click to reply and should not include prefix
