### ISSUE TITLE
Rank requirement ItemCrafts and ItemDropped

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#561]
In the Ranks config the plugin does not recognize ItemCrafts and ItemDropped for objets like bookshelf, hay_block, wood, etc.

```
  StatsRequirements:
  - "PlayTime:18000"
  - "MonsterKills:PIG:30"
  - "MonsterKills:COW:30"
  - "MonsterKills:CHICKEN:30"
  - "BlocksMined:STONE:50"
  - "ItemCrafts:WOOD:30"
  - "ItemCrafts:HAY_BLOCK:10"
  - "ItemCrafts:BOOKSHELF:6"
```

-----------------------
_**Version CMI: 7.8.7.3**
Version  Server: Spigot 1.12.2-R0.1-SNAPSHOT | CraftBukkit version git-Spigot-2086bb0-1988d7f (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Version Vault: 1.6.6-b67_

**Comment by FestusDM** [comment]
I'm having the same issue. List of things (tested thus far) that aren't registering/recognized:
Item craft (Wooden Door)
Item craft (Torch)
Item craft (Furnace)
Item craft (Crafting Table)
Items: Torch, Furnace

---
**CONFIG:**
```
ItemRequirement:
  - "dirt:64"
  - "oak_door:1"
  - "torch:6"
  - "furnace:1"
  - "crafting_table:1"
StatsRequirements:
  - "ItemCrafts:oak_door:1" 
  - "ItemCrafts:torch:6" 
  - "ItemCrafts:furnace:1" 
  - "ItemCrafts:crafting_table:1" 
```

---

**Cmi Version: 8.0.21.4** 
**Paperspigot (426) 1.13.2-R0.1-SNAPSHOT**
**Vault version: 1.7.1-b91(CMIEInjector)**

**Comment by FlakMagnet** [comment]
Suggestion:  Please test with version 8.3.7.1.  Might be fixed as of today.

**Comment by Zrips** [comment]
It is recognized with latest build.
