### ISSUE TITLE
Placeholder %cmi_user_group% broke in 8.8.4.5

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5611]
in latest CMI Version 8.8.4.5
the placholder %cmi_user_group% seems to be broken.
the placeholder was working fine until Version 8.8.4.4.
i havent checked if other placeholder might be broken too...

![Snag_2c8d9fd](https://user-images.githubusercontent.com/12080017/119560417-38ca4b80-bda4-11eb-8e83-7cd8b9805fa8.png)
i dont know why its shows as %|cmi_user_group|% (or %Icmi_user_groupI% ?) ...i checked it twice now
the placeholder we use is %cmi_user_group%
chaning back to 8.8.4.4 and 8.8.4.3 (because of the other issue i wrote above with the fake gamemode)
let the placeholder work fine aggain.

the codeline where we used it in custom alias is:
```
    - perm:cmi.command.customalias.gruppe#! check:$2==%cmi_user_name%! msg! [playerName] &b&lDu &6warst Rang:&6 &c&l%cmi_user_group% &6und bist jetzt Rang:&6 &2&l$1&6.
    - check:$2==null! msg! [playerName] &b&lDu &6warst Rang:&6 &c&l%cmi_user_group% &6und bist jetzt Rang:&6 &2&l$1&6.
```
Until 8.8.4.4 it was showing the Pex Permission group we where in without any problems.
We are using them in a custom alias.
in 8.8.4.5 i read in the patchlog you did some changes to placeholders in custom alias...
this might be the reason for the break?

![Snag_2d8f6ce](https://user-images.githubusercontent.com/12080017/119562501-af684880-bda6-11eb-909f-2ba93e908d2b.png)

**Comment by Zrips** [comment]
Will be fixed.
