### ISSUE TITLE
god mode

### ISSUE THREAD

**Issue by LivingDarkness** [Zrips/CMI#5615]
god mode can be activated in crative but cannot be disabled, it would be convenient to be able to disable it in creative as well.

it would also be useful that when a player enters god mode and he lacks hearts / hunger as soon as he enters god mode, both hunger and life are regenerated to the maximum.

**Comment by Zrips** [comment]
There is internal bug with minecraft itself if you try to disable god mode while being in creative mode. This protection was added to specifically prevent from issues like this happening, so until minecraft fixes this internal issue we cant allow god mode being disabled while you have creative or spectator mode
