### ISSUE TITLE
Can't find player with this name! (flightcharge -> null)

### ISSUE THREAD

**Issue by Akari-37** [Zrips/CMI#5616]
CMI 8.8.4.6
Paper 1.12.2-1618

`/cmi flightcharge (add/take/set/show/expcharge/moneycharge/recharge) (playerName) (amount)`

When the player's name is all numbers
> Can't find player with this name! (flightcharge -> null)

 Like this #4412

**Comment by Zrips** [comment]
Should be fixed with next build
