### ISSUE TITLE
pweather -s still seems not to be working correct...in 8.8.4.6

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5618]
the command i execute on an ic is
`cmi pweather [playerName] rain -s`
in game its fine but the console throws a feedback

![image](https://user-images.githubusercontent.com/12080017/119729451-f755a100-be74-11eb-8fca-5b37098bec5a.png)

![Snag_8213473](https://user-images.githubusercontent.com/12080017/119729487-03416300-be75-11eb-9c5b-057941605cc4.png)

**Comment by Zrips** [comment]
Will make some adjustment for it with next version
