### ISSUE TITLE
inv bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#562]
use /cmi inv id 
Quantity will not be updated instantly

Example: x64 arrow
Use /cmi inv id (view the player's backpack will not be updated immediately)
Consumption x1
Still showing x64
Until you re-use the instructions to view

**Cmi Version (using`/cmi version`):**  7.8.7.3

**Server Type (Spigot/Paperspigot/etc):**  paper

**Server Version (using `/ver`):**  1.12.2

**Comment by Zrips** [comment]
Strange, inv command is not been performed async and quantity should be correct straight after UI opens. Could you maybe make a video or gif showing this issue? As i cant reproduce it currently.

**Comment by p82183645** [comment]
you have 7.8.8.0 fix it 
thank
