### ISSUE TITLE
Hex Codes Issue

### ISSUE THREAD

**Issue by ItLucifer-MRPG** [Zrips/CMI#5620]
Im having an issue with Hex codes, when I or anyone else on my server tries to use hex codes within their nickname it either doesnt work, or breaks their nickname, when I try to /nick {#e60000}Lucifer it comes up in chat as this https://gyazo.com/4b120257ec934b55357ba83a61334594

**Comment by ItLucifer-MRPG** [comment]
Im using the most recent update, 8.8.4.6

**Comment by CloudeLecaw** [comment]
hm i tried 
 `/cmi nick {#cc2500>}Cloude{#e68773<>}_Lecaw{#e6c8b8<} Cloude_Lecaw`
result
![Snag_8b1fa96](https://user-images.githubusercontent.com/12080017/119743880-1a8b4b00-be8b-11eb-9798-41704d924fd3.png)

are you using CMI chat Modul?
and if so you have enabled colored nicks in config?

**Comment by ItLucifer-MRPG** [comment]
Yeah, Hex codes were working for a while, but I noticed they've stopped after I updated to the most recent version

**Comment by CloudeLecaw** [comment]
Could you try
`/cmi nick {#cc2500>}Luci{#e68773<>}fer{#e6c8b8<} Lucifer`

just to see what happens? :-)

**Comment by ItLucifer-MRPG** [comment]
I think the issue is with the alias, as it works with any colour with /cmi nick but /nick breaks the colour completely

**Comment by iBuseWinner** [comment]
Why you used | in hex?
/nick {#RRGGBB} without any symbols
![image](https://user-images.githubusercontent.com/44753872/119879696-297a0800-bf34-11eb-9bfe-5d733e66c08c.png)

**Comment by levtey** [comment]
This has started happening to me as well after updating from 8.8.4.4 to 8.8.4.5, and has persisted through to 8.8.4.6

**Comment by ItLucifer-MRPG** [comment]
> Why you used | in hex?
> /nick {#RRGGBB} without any symbols
> ![image](https://user-images.githubusercontent.com/44753872/119879696-297a0800-bf34-11eb-9bfe-5d733e66c08c.png)

Im not, it automatically puts it in there when I use a hex code from /colorpicker

**Comment by HiddenThesis** [comment]
> > Why you used | in hex?
> > /nick {#RRGGBB} without any symbols
> > ![image](https://user-images.githubusercontent.com/44753872/119879696-297a0800-bf34-11eb-9bfe-5d733e66c08c.png)
> 
> Im not, it automatically puts it in there when I use a hex code from /colorpicker

Yeah, I am also getting the same bug with my server as well. It's automatically putting "|" in the name and not changing the color. Hopefully this is an easy fix.

**Comment by AutumnUwU** [comment]
An issue im having is literally NONE of the stuff works permissions wise, i give people cmi.colors.nickname.hex or cmi.colors.nickname.* and it doesn't work properly. And if you do something like deny cmi.colors.publicmessage.hex, It denies it from everything. Not just publicmessage therefore being broken.

**Comment by mrfloris** [comment]
Hi there, I've just downloaded Tuinity, CMI and run a fresh instance. The only changes I've made is true for chat: and true for hoverable msgs. And I've opped myself. Not other plugins.

It works fine when you prefix the commands with /cmi, it doesn't when it is an alias like /nick or /msg

<img width="718" alt="Screenshot 2021-05-28 at 07 45 22" src="https://user-images.githubusercontent.com/28841349/119936280-34ab5300-bf89-11eb-80fb-a66a479675b6.png">
<img width="1215" alt="Screenshot 2021-05-28 at 07 44 45" src="https://user-images.githubusercontent.com/28841349/119936289-36751680-bf89-11eb-86aa-99b38a174107.png">
<img width="493" alt="Screenshot 2021-05-28 at 07 44 37" src="https://user-images.githubusercontent.com/28841349/119936295-37a64380-bf89-11eb-86ae-22dfb78bea00.png">

yeh, i can reproduce this on Tuinity 

<img width="779" alt="Screenshot 2021-05-28 at 07 48 03" src="https://user-images.githubusercontent.com/28841349/119936314-41c84200-bf89-11eb-849d-5dce97187932.png">
<img width="1095" alt="Screenshot 2021-05-28 at 07 47 21" src="https://user-images.githubusercontent.com/28841349/119936321-442a9c00-bf89-11eb-8e82-e0ec7f506f9b.png">
<img width="741" alt="Screenshot 2021-05-28 at 07 47 15" src="https://user-images.githubusercontent.com/28841349/119936324-44c33280-bf89-11eb-9b4f-a517228e2ed6.png">

I checked with the latest Paper build, and I get the same, also works there. like it does on tuinity. 

<img width="723" alt="Screenshot 2021-05-28 at 07 51 12" src="https://user-images.githubusercontent.com/28841349/119936520-9a97da80-bf89-11eb-892f-073f20c2ccda.png">
<img width="1089" alt="Screenshot 2021-05-28 at 07 51 59" src="https://user-images.githubusercontent.com/28841349/119936532-9d92cb00-bf89-11eb-89eb-06dfe2406280.png">

**Comment by CloudeLecaw** [comment]
We had this problem in last Version with placeholders in Custom alais too. Lools like hexcolorcodes are effected tonby this |-Problem

**Comment by b01w** [comment]
Yep also having this issue now, on the latest version too, any news on when this is going to be fixed? Quite frustrating haha

**Comment by ChiboYen** [comment]
Can confirm, having this issue as well

**Comment by Kbryst** [comment]
The new version today states it fixes it, but it didn't fix it for me.

**Comment by CloudeLecaw** [comment]
does /cmi nick for for you? @Kbryst 
do you use cmi chat and cmi tab for that?

**Comment by mrfloris** [comment]
> The new version today states it fixes it, but it didn't fix it for me.

Everything that is reported is still broken for you? We're going to need more info. 

Can you do /cmi version and share the FULL output as it is now? And the same for /ver

And provide exactly what you type that you're trying for /nick, /msg, and /broadcast, etc? and show how it doesn't work?

Lack of info helps nobody "doesn't work" can't get more than a response like this, or a simple: make sure you're up to date.

**Comment by Kbryst** [comment]
I removed the jar, did a few restarts, put it back, now it works fine. It was prob an issue with my system. Apologies for the confusion.
