### ISSUE TITLE
Dissapears items when player hold and /inv

### ISSUE THREAD

**Issue by iBuseWinner** [Zrips/CMI#5627]
**Description of issue:**
When Player1 take item with LC (left click)
E.g.
![image](https://user-images.githubusercontent.com/44753872/119993761-9a70fc80-bfd4-11eb-904b-3b71a9ae2b83.png)

And Player2 use command /inv Player1
This item disappears

---

**Cmi Version (using`/cmi version`):** 8.8.4.4

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** 
[15:53:35 INFO]: This server is running Purpur version git-Purpur-1135 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 3 version(s) behind
Previous version: git-Hyalus-202 (MC: 1.16.5

**Comment by CloudeLecaw** [comment]
why you let view inyour players inventories and let them take their items out?
sounds like a great server to troll each other and take out everyones items.
if the Admin or who ever took out an item with LC he had a reason for doing this. So its ok when it really disapears in unsuported server forks ;)

**Comment by iBuseWinner** [comment]
> why you let view inyour players inventories and let them take their items out?

Just to view, not to take items :/
Why you think that view == edit?

**Comment by iBuseWinner** [comment]
> Mousehold items are saved nowhere. what is the reason why you thought they disapear. inv loads the inventory slots not a mousehold anywhere item... so blopp it may dispears.

Because of that item clears from inventory? Nice.

**Comment by CloudeLecaw** [comment]
U said:
- P1 does invsee p2
- p2 holt now item with left mouse
- P2 niw does invsee p1
- In your Pictures we see p2 holding Item of inventory of p1 with Mouse what means he can take items out. 

This should not be possible for the viewer.
So finaly this means u gave permission or your server or other plugin creates this currption.

On spigot + permsystem + cmi your issues is nit reproduceable becauae p2 cant even take the item with LS in his mouse.

**Comment by iBuseWinner** [comment]
> In your Pictures we see p2 holding Item of inventory of p1 with Mouse what means he can take items out.

Example what I mean. It isn't /inv

**Comment by Zrips** [comment]
@iBuseWinner 
Confirmed, will be fixed with next update
