### ISSUE TITLE
"Remove" wont remove warp name

### ISSUE THREAD

**Issue by Korinocho** [Zrips/CMI#5629]
If you try to use the "remove" name in a Show Name of some warp it will put "remove" as the warp name instead of removing it.

Steps to reproduce:
1. Create a new warp
2. Change the "Show name" of the warp
3. Try to change the "Show name" again (it will tell you to put "cancel" to cancel and "remove" to remove the name)
4. Write "remove"
5. The new name is "remove"

Its not critical

CMI 8.8.4.6
Paper 1.16.5 (#713)

**Comment by Zrips** [comment]
You might have some what outdated locale line relating to this. Most recent one doesn't include option to remove it only to cancel action. Its not a bug in particular, but i might need to modify it in future to allow display name removal in case you no longer want to use one
