### ISSUE TITLE
/inv dupe

### ISSUE THREAD

**Issue by iBuseWinner** [Zrips/CMI#5633]
**Description of issue:**
When Player1 fast change his items (with push number) and Player2 use /inv Player1 and fast close it item from Player1's offhand gets into Player2's crafting.
Video: https://youtu.be/OmdGUVaiSXk

(For those who is CloudeLecaw: Players don't have permission to edit inventories)

---

**Cmi Version (using`/cmi version`):** 8.8.4.4

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** git-Purpur-1135 (MC: 1.16.5)

**Comment by CloudeLecaw** [comment]
You also should not give them inv see ;)

**Comment by iBuseWinner** [comment]
> You also should not give them inv see ;) - bug fixed

Nice fix. Stop answering in my issues plz.

**Comment by b01w** [comment]
> You also should not give them inv see ;) - bug fixed

What an idiotic response, I second this bug lets hope zrips fixes it.

**Comment by Zrips** [comment]
Should be fixed with next update. Please inform me if issue persists.

**Comment by iBuseWinner** [comment]
@Zrips not fixed.

**Comment by iBuseWinner** [comment]
@Zrips

**Comment by iBuseWinner** [comment]
@Zrips ?????

**Comment by dkalaxdk** [comment]
> 
> 
> @Zrips ?????

I think the better way would be to reopen the issue, if this is something you can do (Dunno if it is a permission thing)
If not, i would create a new issue, and then add this as a reference in it.

**Comment by iBuseWinner** [comment]
I can't reopen it because Zrips closed it

**Comment by CloudeLecaw** [comment]
reopen means creating a new and posting with #number  to this thread
