### ISSUE TITLE
Cooldown after the failed /dback

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#5634]
**Description of issue:**
When players try to return to death point e.g in lava pool. They enter the `/dback` command, but then are requested to enter `/tpbypass` to confirm their intentions to tp to unsafe location. The problem is that the command gets into cooldown after the first use and players cannot get back to pick up their items.

---

**Cmi Version (using`/cmi version`):** 
8.8.4.6
**Server Type (Spigot/Paperspigot/etc):** 
Purpur
**Server Version (using `/ver`):** 
git-Purpur-1141 (MC: 1.16.5)

**Comment by Zrips** [comment]
Can you show me your cooldown setup? As /dback cooldown should not get triggered in case it fails, as it does on my test server. If it says that you need to tpbypass it should not put dback into cooldown

**Comment by radiant-ai** [comment]
Ok, I will retest everything and if I indeed have it still broken I will
get back to you with the configs.

**Comment by radiant-ai** [comment]
Unconfirmed during the testing
