### ISSUE TITLE
Cross-Service Issues

### ISSUE THREAD

**Issue by JustinBery** [Zrips/CMI#5639]
I have a database connection on the server. When the player changed the name on server A and went to server B. The name is back in the file!
Including rank level. Upgrade in server A to server B will be back to the file without synchronization!

**Comment by dkalaxdk** [comment]
CMI does not, in and of it self allow any sorta synchronization.
You would need an external plugin to sync.
If you have connected both servers to the same DB, you are just asking for them to not behave well.
See top of databaseInfo.yml:

`# ATTENTION! DON'T USE SAME DATABASE TABLES FOR MORE THEN ONE SERVER, YOU WILL HAVE UNEXPECTED ISSUES. EACH SERVER SHOULD HAVE ITS OWN DATABASE TABLE SETUP`

**Comment by Zrips** [comment]
@JustinBery 
Just like @dkalaxdk pointed out, there isint any sync implemented at this moment, we have some cross server data sharing relating to messages and vanished players, but there isint full blown data sync. And if you are using one database for multiple servers, make sure each one has its own tables, you cant have one table used for multiple servers as it will overwrite data without any sync.
