### ISSUE TITLE
AFK subtitle isn't translated

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5642]
**Description of issue:**

---

Hi, I translated AFK subtitle on my own (created my own ones), but in game I'm still getting old ones. It's happening since AFK subtitles were added.

**CONFIG SECTION (DELETE IF NOT RELEVANT):** - Locale file
```
    info:
      # This only determines message in title message and not message shown in chat. For chat message check config.yml file
      afkTitle: '&eJsi AFK'
      afkSubTitle:
      - '&2Nejez tolik sušenek!' -> this is the message on the following screenshot
      - '&2Pěkný den pro procházku'
      - '&2Afk, znovu?'
      - '&2Kam jako jdeš?'
```
Image:
![image](https://user-images.githubusercontent.com/18662086/120224932-a4993200-c244-11eb-92da-ee95ec2b3d21.png)

---

**Cmi Version (using`/cmi version`):** 8.8.4.7

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** 1.16.5

**Comment by Zrips** [comment]
Confirmed, will be fixed with next update
