### ISSUE TITLE
CMI AFK subtitle cannot be translated

### ISSUE THREAD

**Issue by VojtechAdam29** [Zrips/CMI#5643]
**Description of issue:**
So recently was added to CMI afk messages but it cannot be translated, when i transleted it in my language nothing happened. This only happens to subtitle, not title. https://prnt.sc/13n5kdb

---

**Cmi Version (using`/cmi version`):**8.8.4.7 

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** git-Paper-686 (MC: 1.16.5)

**Comment by Zrips** [comment]
Will be resolved with next update
