### ISSUE TITLE
CMI Holograms

### ISSUE THREAD

**Issue by VojtechAdam29** [Zrips/CMI#5644]
**Description of issue:**
Holograms keeps randomly dissapearing. https://ctrlv.tv/uVHu

---

**Cmi Version (using`/cmi version`):**  8.8.4.7

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** git-Paper-686 (MC: 1.16.5)

**Comment by Zrips** [comment]
Should be fixed now with latest release
