### ISSUE TITLE
clear username itemname-number does not work in console

### ISSUE THREAD

**Issue by SakuraNep** [Zrips/CMI#5648]
**Description of issue:**

the /clear command does not work correctly when used from the console example commnad: (clear username itemname-number) it will clear the whole inventory and not the item that is entered.

---

**Cmi Version (using`/cmi version`):** 
8.8.4.7
**Server Type (Spigot/Paperspigot/etc):** 
paperspigot
**Server Version (using `/ver`):** 
Paper version git-Paper-720 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Could you provide exact example you used? And just to make sure its clearing using CMI and not another plugin, try using full command as /cmi clear Zrips stone-10

**Comment by SakuraNep** [comment]
tested it and it works indeed if i put CMI infront of it! thank you.
