### ISSUE TITLE
Hex color nicknames aren't working: nicks get the codes with added |

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#5653]
**Description of issue:**
After a recent update, I can no longer give people hex nicknames:

I enter:
/nick {#7fffd4>}Per{#7da98d<>}ry{#717486<} Perry 
OR /cmi nick ....
and get:
https://prnt.sc/13xadgd

I initially got told that I couldn't use that as a nickname, then gave myself the bypass perm and started getting told that the nick was too long and exceeded the 16 characters allowed. "Nickname is too long. Max is 16 symbols" After giving myself the length bypass perm as well, I get this as a nick.  LP isn't showing me failing any perm checks, so I don't think it's still a permission issue and it worked without all the extra permissions before.  Even opping myself doesn't fix it.  The problem is the same with normal hex codes without the gradient.

Using /cmi nick does not fix it.  (I've read the other issue)

I've got cmi.colors.nickname.* perms

I can use the hex codes in chat with no issues.

I've tried having the filtering in the config set to both true and false

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
    # If set to true then nickName will be filtered from color codes when player changes it
    # cmi.colors.nickname.[colorName]
    NickName: false  
   # (Note, I've also tried this with true... same result)
  # If set to true, players public message who is in your ignore list will not be shown
```

---

**Cmi Version (using`/cmi version`):** 
[18:58:19 INFO]: --------------------------------------------------
[18:58:19 INFO]: CMI plugin version: 8.8.4.8 MySQL
[18:58:19 INFO]: CMILib: 1.0.0.2 
[18:58:19 INFO]: Server: Paper(756) 1.16.5-R0.1-SNAPSHOT
[18:58:19 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[18:58:19 INFO]: Modules -> 48 enabled 8 disabled: spawnerProximity, flightCharge, disabledEnchants, mirror, ranks, moneyCheque, spawners, spawnerCharge
[18:58:19 INFO]: --------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper version git-Paper-756 (MC: 1.16.5)
**Relevant plugins (Delete if this isn't needed):**

**Comment by CloudeLecaw** [comment]
you need to set them to true so cmi can handle colorcodes

**Comment by Momshroom** [comment]
I'm not using CMI's chat module and I *thought* I'd tried changing NickName to true... but apparently the change didn't get saved. Thank you, it's working now, though the wording in the config comment sounds like it works the other way around.
