### ISSUE TITLE
View another players ignore list

### ISSUE THREAD

**Issue by Royster-85** [Zrips/CMI#5654]
Not sure if this is actually a bug or something that isn't available, but I don't see a setting where you can view another players /ignore list. There has been some instances where this would be handy to have, especially for mods/staff.

---

**Cmi Version (using`/cmi version`):** 8.8.4.8

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Ver 759

**Comment by Zrips** [comment]
Will add extra variable as (-p:[playerName]) to have this functionality
