### ISSUE TITLE
/Rankup issue for pre existing players.

### ISSUE THREAD

**Issue by Geekmakes** [Zrips/CMI#5656]
I've got ranks in Luckperms and I'm working on upgrading over to cmi from Essentials and EzranksPro. I don't want to reset player ranks in luckperms but I do want to use the rankup system in CMI. However after I setup the perms "cmi.rank.Member1" etc. its still only allowing you to rank up from default even if their rank is way higher in luckperms already. 
 
In EZRanksPro for /rankup and it uses permissions set to the players group to pick the next rankup needed.(ezRankup.rank.(name)  I'm assuming that's how it was intended to work with cmi with  "cmi.rank.(Name)"
 
I could have set something up wrong or it could be a misunderstanding, but it seems like using /rankset is the only way around this issue for pre-existing players. It works flawlessly for new players or after the player has there corresponding /rankset.

Thanks!

![2021-06-04_11 17 03](https://user-images.githubusercontent.com/16181272/120824457-7bb7bc00-c526-11eb-8ce6-40a0a5ce2a6d.png)

**Comment by Geekmakes** [comment]
If anyone else has this bug a quick bandaid is to add 
```
joinServer:
  Enabled: true
  Commands:
  - cmi rankset [playerName] %vault_rank%
```
to the events folder
you'll need papi and vaults placeholders.

**Comment by Zrips** [comment]
Entire rank system was based on recorded current player rank and not based on actual permission node. This will be addressed with next update where you can have more permission based system by enabling it in config file
