### ISSUE TITLE
time command - world argument (placeholder) broken?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5661]
im using /cmi time 7000ticks plotworld

it sets to time correct in plotworld but the placeholder shows the current world

![Snag_7057a4](https://user-images.githubusercontent.com/12080017/120904667-aa7c8200-c64d-11eb-8d70-7dfdec4b7f1e.png)

So command works correct means the weather was set in plotworld - just the placeholder is the wrong world (the world where i was currently in when i executed the command)
![Snag_714689](https://user-images.githubusercontent.com/12080017/120904691-ced85e80-c64d-11eb-91a2-fc6eb7457ab4.png)

**Comment by Zrips** [comment]
Gets a fix with next build
