### ISSUE TITLE
/cmi setblock

### ISSUE THREAD

**Issue by ItLucifer-MRPG** [Zrips/CMI#5662]
A cmi version of /setblock where you can add more details, like specific worlds for a specific amount of time, etc 

Ive been using alias to set a specific block to be a redstone block to allow alias work to enable command block but ive noticed that it only works if you're in the specific world with the command block

 I feel like a command like this will make things like that alot easier

**Comment by CloudeLecaw** [comment]
nice idea.. but pls not only worrld args

` /setblock [material:meta] (from x,y,z) (to x,y,z) (world) (-s)`

this might be usefull..
if no cords are given the actual cord is taken to place the material there
