### ISSUE TITLE
!left! doesnt work with [interactedPlayer]

### ISSUE THREAD

**Issue by ItLucifer-MRPG** [Zrips/CMI#5663]
I was trying to make a sword that can kill anyone you left click on, and I noticed that when i tried to make it work with left click like a normal sword would it doesnt work

**Comment by Zrips** [comment]
Tested with diamond sword and this command
/cmi attachcommand !left!cmi kill [interactedPlayer];;!right!cmi heal [interactedPlayer]
works like a charm, left click kills and right heals
