### ISSUE TITLE
warp.getCreatorName() return black nick if it gradient

### ISSUE THREAD

**Issue by iBuseWinner** [Zrips/CMI#5675]
**Description of issue:**
When player using gradient in his nick it shows as black in warp.getCreatorName()

---

**Cmi Version (using`/cmi version`):** 8.8.4.8

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** 1.16.5

**Relevant plugins (Delete if this isn't needed):** Custom to check player's warps and near warps

**Comment by Zrips** [comment]
This method returns colorized name. You might want to debug it by checking what exact output you are getting, as it looks like it simply fails to properly process hex color codes in your situations and outputs it as a plain old color format instead. Did some testing and gradient nicks get returned properly.
