### ISSUE TITLE
/cmi saveall bug

### ISSUE THREAD

**Issue by SouirTommer** [Zrips/CMI#5678]
**Description of issue:**

``[CMI] Plugin CMI v8.8.4.8 generated an exception while executing task 744772
08.06 18:58:58 [Server] INFO java.lang.NullPointerException: null
08.06 18:58:58 [Server] INFO at com.Zrips.CMI.Modules.SavedInv.SavedInventoryManager.saveInv(SavedInventoryManager.java:265) ~[?:?]
08.06 18:58:58 [Server] INFO at com.Zrips.CMI.Modules.SavedInv.SavedInventoryManager.saveInv(SavedInventoryManager.java:254) ~[?:?]
08.06 18:58:58 [Server] INFO at com.Zrips.CMI.Modules.SavedInv.SavedInventoryManager.saveInv(SavedInventoryManager.java:245) ~[?:?]
08.06 18:58:58 [Server] INFO at com.Zrips.CMI.commands.list.saveall$1.run(saveall.java:95) ~[?:?]
08.06 18:58:58 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1131]
08.06 18:58:58 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1131]
08.06 18:58:58 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1131]
08.06 18:58:58 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
08.06 18:58:58 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
08.06 18:58:58 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?]``

**Cmi Version (using`/cmi version`):** 
8.8.4.8
**Server Type (Spigot/Paperspigot/etc):** 
Purpur
**Server Version (using `/ver`):** 
1.16.5

**Comment by Zrips** [comment]
Should be resolved with next update
