### ISSUE TITLE
[Request] '/cmi unmute' and '/cmi unmutechat'

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#568]
Add a `/cmi unmute` command for easily unmuting muted players and a `/cmi unmutechat` command for easily unmuting the server chat.

**Comment by CloudeLecaw** [comment]
you can creat simple commanaliases for this :)

unmute:
  - perm:cmi.command.unmute! cmi mute $1 1s -s
unmutechat:
  - perm:cmi.command.unmutechat! cmi mute 1s -s

these comamnds unmute silent after 1 secound so its like a unmute

**Comment by TheWranger** [comment]
Would be more efficient to add a `/cmi unmute` and `/cmi unmutechat` so we can properly send messages to people about them being unmuted. Muting for a second is a quick workaround for the issue.

**Comment by Zrips** [comment]
Both commands will be available with next udpate
