### ISSUE TITLE
Cmi enderchest command glitching with elitepet

### ISSUE THREAD

**Issue by jahangir6969** [Zrips/CMI#5680]
When using the elitepet chest pet with cmi /enderchest command it dupes the items. 

https://pastebin.com/3aLmub5x

8.8.4.9

paper-1.16.5-636

![image](https://user-images.githubusercontent.com/59332632/121246593-3df5c300-c899-11eb-8d12-88b2f8bb37c5.png)

Elite pets: https://www.spigotmc.org/resources/elitepets-create-your-own-pets-25-custom-effects-17-premade-pets-eggs-10-sale.83484/

Here is the proof of the glitching: 
https://youtu.be/l3HVUaANoNo

![image](https://user-images.githubusercontent.com/59332632/121246837-785f6000-c899-11eb-82e4-e58a1ccb44a8.png)

**Comment by CloudeLecaw** [comment]
Have you tried updating paper
..you Screenshot seems to be old.
Paper 1.16.5 is on build 775
Your screenshot say its just 9 versions behind.

**Comment by Zrips** [comment]
I have no access to this plugin to perform any kind of tests to determine that its caused by it or that issue originates from CMI in general

**Comment by jahangir6969** [comment]
> Have you first tried updating paper?
> Paper 1.16.5 is on build 775
> Your screenshot also say your 139 versions behind.... (release date of your version was 2021-04-30) - So may one of this 139 versions after until today fixed your issue allready..? Pls trie this first.
> [latest version u find here:](https://papermc.io/downloads)
> 
> The video did not really say anything.. we just see a player throw away items... and he did something to duplicate them... infront of a cactus...

I have updated the paper and still an issue.

**Comment by jahangir6969** [comment]
> I have no access to this plugin to perform any kind of tests to determine that its caused by it or that issue originates from CMI in general

I will tried to contact the plugin owner and see if they can help out.

**Comment by Splodgebox** [comment]
> I have no access to this plugin to perform any kind of tests to determine that its caused by it or that issue originates from CMI in general

Add me on discord, Splodgebox#3490 and I'll give you a copy

**Comment by Zrips** [comment]
@jahangir6969 
Issue got determined, its unrelated to CMI and @Splodgebox should issue a fix for ElitePets soon enough.
