### ISSUE TITLE
CMI ChatGroup gradient

### ISSUE THREAD

**Issue by BeNOISY** [Zrips/CMI#5684]
**Description of issue:**
When using color gradient, ingame chat bugs out, chat is in one color and nick with preffix are not shown, without using gradient only using color(does not matter whether it is mc or hex) chat is showing correctly.  https://ctrlv.link/dtUJ

```
GroupFormat:
    '1': '{prefix}&f{displayName}&7: {#b3a28f>}{message}{#d7b8e6<}'
    '2': '{prefix}&f{displayName}&7: &r{message}'
    '3': '{prefix}&f{displayName}&8: &r{message}'
```
---

**CMI version 8.8.5.0** 

**Purpur** 

**Purpur version git-Purpur-1156 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)**

**Comment by mrfloris** [comment]
Try moving it away from `GroupFormat:` and keep that `{message}` and below that in `GroupMessageFormat:` try to customize the `{message}` there. See if that solves it for you.

**Comment by Zrips** [comment]
@BeNOISY 
Message format is defined in a section below actual chat format. Due to complexity how message is handled we need separate section where we will define exact format of actual message.
