### ISSUE TITLE
CMI placeholder not working Lastes version

### ISSUE THREAD

**Issue by golfmaichai1** [Zrips/CMI#5685]
CMI placeholder not working with old Paper version
I can't upgrade current version of Paper because some plugin will get bug 
so I'm waiting for other plugin update somehow I need to use CMI too can you help
fix this issue I don't want to use old version of CMI :(

**Cmi Version (using`/cmi version`):** 
8.8.5.0

**Server Type (Spigot/Paperspigot/etc):** 
Paper(587)

**Server Version (using `/ver`):** 
1.16.5

**Relevant plugins (Delete if this isn't needed):**
![ภาพถ่ายหน้าจอ 2564-06-10 เวลา 13 21 42](https://user-images.githubusercontent.com/45531631/121474823-d487c880-c9ee-11eb-890b-1b9dd4121037.png)

**Comment by golfmaichai1** [comment]
![Uploading ภาพถ่ายหน้าจอ 2564-06-10 เวลา 13.23.57.png…]()

**Comment by CloudeLecaw** [comment]
Well..time to update to paper 775 or newer?

**Comment by golfmaichai1** [comment]
https://pastebin.com/2baeVKaX

MMocore
Companion 
GlowAPI

will bug after update

**Comment by golfmaichai1** [comment]
![ภาพถ่ายหน้าจอ 2564-06-10 เวลา 13 52 18](https://user-images.githubusercontent.com/45531631/121478433-36e2c800-c9f3-11eb-8ece-e4a6631c3e1b.png)

I think the paper version is not solve this problem I'm trying to update lasted paper version 
and lastet CMI Version now it have the same issue what should I do ?

**Comment by CloudeLecaw** [comment]
be sure the placeholder is %player_name%?

**Comment by CloudeLecaw** [comment]
Could you rename your issue?
You showned us in Screenshots now allready that this sems to be a from chat Problem in old and newer paper Version ;)  so the TE is confusing.

**Comment by golfmaichai1** [comment]
oh okay sorry

**Comment by RustyDagger** [comment]
seems to be happening on attached commands too.
`/cmi attachcommand !limiteduse:1!;;msg! [playername] &aRemoved &61&a Death from your total, You now have &6%aoneblock_deaths%`
resulting in the placeholder being displayed with | after the first % and before the second %
https://gyazo.com/80d5a9accf13907f0a7a470f022934c7

https://gyazo.com/c7a61380ceb96af5e0505f5c99cdf92c

**Comment by Zrips** [comment]
Fixed with altest build
