### ISSUE TITLE
Armorstand name/ two lines

### ISSUE THREAD

**Issue by Kreon461** [Zrips/CMI#5686]
Hi i have quastion about armorstand name... 
I dont know how to write more then 1 line in there. If its even possible.
Thanks for answer :D

**Comment by CloudeLecaw** [comment]
Have u tried \n for new line? May not possible because its just a named item.

**Comment by Kreon461** [comment]
Yea i try it... didnt work. 
Yea holograms are made from more armorstands. I temporally made one hologram upon the armorstand but it cant be perfectly lineup with the armor stand so it looks wierd.

If it cant be done by the name, can i somehow lineup the hologram with the name of the armorstand?

**Comment by CloudeLecaw** [comment]
your right it might looks not perfectly.. but you have no choice.. other one just would be set a 2 line hologram over the head of your armorstand :3

**Comment by Zrips** [comment]
@Kreon461 
Not really possible. You could simply disable armor stand name plate and create hologram with 2 lines, then adjust it as best as you can with editor UI and that's that.
