### ISSUE TITLE
warp config/gui issue

### ISSUE THREAD

**Issue by assodibastoni** [Zrips/CMI#5691]
**Description of issue: the number of the slots (warp gui) don't coincide with the "Slot: (num)" in the warp config file. In the config the first is Slot: 0 but in the gui Slot: 1. This make the warp gui a little bugged.**

---

**Cmi Version (8.8.4.8):** 

**Server Type (Paper):** 

**Server Version (1.12.2):** 

![FgvYM6LDT_m6MevJWFp0BA](https://user-images.githubusercontent.com/85745410/121687629-db800b00-cac2-11eb-8f96-42366713aa44.png)

**Comment by Zrips** [comment]
Warps are made to be handled from ingame editor which shows slot number in more normal way where first slot is 1, while internally slot numbers start from 0 as a first one. Will make some changes to be more consistent with next update.
