### ISSUE TITLE
Bungee Portals don't work anymore

### ISSUE THREAD

**Issue by therealatsuga** [Zrips/CMI#5696]
**Description of issue:**
Bungee Portals don't work anymore. If I create a new Bungee Portal, change server and click the message to set the teleport position, I get a message that the portal doesn't exist.  
Portals on the same server do work without any issues. 

**Cmi Version (using`/cmi version`):** 
8.8.5.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper 1.16.5 version 777
**Server Version (using `/ver`):** 
Paper 1.16.5 version 777
**Relevant plugins (Delete if this isn't needed):**
Bungee is Waterfall

**Comment by Zrips** [comment]
What output do you have for /cmi serverlist ?

**Comment by therealatsuga** [comment]
There is no output - and  also no error in console. CMIBungee (latest) is installed.

**Comment by Zrips** [comment]
Do you see message like this 
![image](https://user-images.githubusercontent.com/10416201/122645677-dd2d7c80-d11b-11eb-82b8-851e737a771b.png)

**Comment by therealatsuga** [comment]
Yes
![image](https://user-images.githubusercontent.com/51722048/122645793-7066b200-d11c-11eb-914e-27a181fb4dfc.png)

**Comment by Zrips** [comment]
Will make a change to try and force teleport player to bungee server even if we cant really recognize it being online, this should eliminate issues when you have server running but its not being properly recognized. But as of some testing, servers did got recognized properly and everything seem to work properly. 
If issue persists after you went with 9.x transition, let me know.

**Comment by TyniCraft** [comment]
Sorry to necro this port but i do have the same issue
