### ISSUE TITLE
[CMI] Severe Save Error

### ISSUE THREAD

**Issue by Ew9304** [Zrips/CMI#57]
I have been getting this error randomly in my console.. I am pretty sure it started happening a few updates ago, I decided to report now after seeing someone else reported it but did not provide enough info. I am running Spigot 1.8.8 and am using MySQL storage.

![image](https://user-images.githubusercontent.com/34957646/36792866-cc844a4a-1c69-11e8-98ab-5d0f9707d7a5.png)

**Comment by Zrips** [comment]
Will add extra info to be outputed in case this happens again and will add some fail saves to prevent it from happening again. Check next update today.
