### ISSUE TITLE
issue with [playerDisplayName] on login in CMI 9.0.0

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5702]
![Snag_227a773](https://user-images.githubusercontent.com/12080017/121953353-bc50da00-cd5d-11eb-8bd5-e044e6119c45.png)
 looks like this placeholder is not working correct for now :3

**Comment by mrfloris** [comment]
I did report this before the release last night, it must have slipped through or maybe zrips wasn't unable at the time to dive into that. 

CMI 9

<img width="1055" alt="Screenshot 2021-06-15 at 05 52 35" src="https://user-images.githubusercontent.com/28841349/121990335-e3c79700-cd9d-11eb-8b1e-dfe0ec2b250c.png">

**Comment by CloudeLecaw** [comment]
Well dont worry we still have enough time and test a bit.:) The good point is that we can now see with our own configs what happens and what might went wrong.
Poor Zrips. He must have a burning head allready ;/

**Comment by mrfloris** [comment]
I haven't had time yet to see if there's another placeholder that's supposed to be used and I just need to update (Maybe it is now `[playerNickname]`?), or if it should work there and it need an update on CMI's side. Worth to report here so he can look into it when he has time. A temporary fix could be to try another placeholder like `[playerName]` or a global placeholder like `%cmi_user_name%`

**Comment by CloudeLecaw** [comment]
we are still on the testing on just our offline servers so it has time :-)
i will tried to see if an other placeholder might work too

**Comment by Zrips** [comment]
Will be fixed with next version
