### ISSUE TITLE
CMI v9 kits always have armor which cant be removed and new kits by default have armor

### ISSUE THREAD

**Issue by gooderzz** [Zrips/CMI#5703]
**Description of issue:**
When editing the kits in the GUI there was armor that couldn't be removed. The config also didn't show the armor so wasn't able to be removed from there either. 
When creating a new kit by default it adds armor that cant be removed.

---

**Cmi Version (using`/cmi version`):** 
CMI: 9.0.0.0 SqLite
CMILib: 1.0.1.0

**Server Type (Spigot/Paperspigot/etc):** 
Server: Spigot 1.17-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 
1.17-R0.1-SNAPSHOT

**Comment by mrfloris** [comment]
Hi there,

I think there's perhaps a bit of confusion. I will link you to a video to visualize what I mean.

I did a fresh install of CMI 9 and made a new kit, added something in the armor slots and was able to remove them. 

If that's not what you mean, and you meant that there are existing chainmail armor that you can not edit or remove, then this is correct. They are not things you can edit in the .yml file or remove. They are placeholders to indicate "your helmet goes to this helmet slot", so when someone gets the kit, and their helmet slot is empty, it will put the helmet there.

**Comment by Zrips** [comment]
@gooderzz 
I think you are talking about chainmail armor. Those are not preset armor items, those are just to visualize which type of armor goes where and player will not receive them. Its just a visual thing for you as editor. If you would do /cmi kit [kitName] -preview then you would notice that armors are not present.
