### ISSUE TITLE
Adding CMIPlayerWarn Event in API

### ISSUE THREAD

**Issue by RookieAND** [Zrips/CMI#5704]
There's an custom event like CMIPlyaerBanEvent or UnbanEvent in CMI-API. But I think it's much better to handle or notice when player get warn by other moderator. I try to make some connection between DiscordSRV and CMI but sadly there's no custom event belong to Warning Module.

**Comment by mrfloris** [comment]
Suggestions should be posted as a Discussion, https://github.com/Zrips/CMI/discussions

**Comment by Zrips** [comment]
Added.
