### ISSUE TITLE
Logon and logout meassage bypass seems to be ignored (cmi v9) 

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5705]
Even the owner and.me that usially had the bypass (irgnore) permission for login and logout get the login message from cmi.
We designed our owns with playernamechecks in eventcommande loginevent
Well..the result is now it looks like a "double" welcome and leave because login and logout from cmi are shown too.

**Comment by mrfloris** [comment]
Please provide additional information, can you do these commands and share the full output from console?

```
ver
ver LuckPerms (or whatever permission manager you use
cmi versions
```

On CMI 8.8.5.0 and Paper 1.16.5, I can turn off the default login/logout, and enable custom login/logout, and update the locale, and players can join and I have no double msgs. I am not using eventcommands.yml

Additionally, when I am in Vanish mode, I join silently, and it announces me when I am not in vanish.

I haven't run into double msgs yet. 

This is how I have it setup. <https://github.com/mrfdev/CMI/blob/master/Resources/FAQ/cmi-custom-joinleave.md>

**Comment by CloudeLecaw** [comment]
Oh i havebt thought we talk about 8.5.5.0 ;p

**Comment by mrfloris** [comment]
It is always handy as per the bug report template to include the version details so there's a better overview of what we're dealing with. :)

**Comment by CloudeLecaw** [comment]
i checked twice now
i have
    - cmi.messages.disablelogin
    - cmi.messages.disablequit

like you can see the custom login of CMI is still shown
![Snag_1d05f93](https://user-images.githubusercontent.com/12080017/122481889-d691ee80-cfcf-11eb-977a-1e13d87d9211.png)

**Comment by Zrips** [comment]
@CloudeLecaw 
Check your permission access with /cmi haspermission cmi.messages.disablequit
which should output message like
![image](https://user-images.githubusercontent.com/10416201/122581026-e7397780-d056-11eb-8449-f6d009977958.png)
You need it to be hard set and only having OP will not help you out here.

**Comment by CloudeLecaw** [comment]
cmi.messages.disablequit   and cmi.messages.disablejoin are permission of my group i am in!
but ok i will do it aggain for you with the screenshot give me a few mins to startup im
and i never beeing OP on the server . i thought today these are basic things.
The fakt is the login and logout is still shown.

Used Permissionsystem is PEX 1.23.5    the whole think was also working fine in the old 8.5.5.0 with Paper 1.16.5
It just apeared now in the CMI 9 Version  

i  did this
/cmi haspermission cmi.messages.disablequit
/cmi haspermission cmi.messages.disablelogin

the result...
![Snag_33d9ad8](https://user-images.githubusercontent.com/12080017/122611423-9ab76180-d081-11eb-86d5-d012ad1da331.png)

**Comment by CloudeLecaw** [comment]
i tried it and found the issue
with the new CMILib we now have to
give permission directly even we had the wild card before.

seems like this does not work anymore :3
So we gave our ranks the permsisions now
