### ISSUE TITLE
PWeather and Ptime reset when switching worlds

### ISSUE THREAD

**Issue by Skizzles** [Zrips/CMI#5707]
**Description of issue:**
Ptime and Pweather reset when switching worlds

**Cmi Version (using`/cmi version`):** 8.8.4.8

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** 1.16.5

**Relevant plugins (Delete if this isn't needed):**
N/A

**Comment by CloudeLecaw** [comment]
U should try version 8.5.5.0

**Comment by Skizzles** [comment]
Those notes state for night speedup, this has to do with /ptime and /pweather on world switch. those set the client to show specific values and revert once switching worlds.

**Comment by CloudeLecaw** [comment]
Still give it a try ;o

**Comment by Zrips** [comment]
@Skizzles 
CMI doesn't really manipulate your pweather or ptime when you change worlds, you might want to retest this without any other plugin and CMI only
