### ISSUE TITLE
Cannot Unglow

### ISSUE THREAD

**Issue by captainroach606** [Zrips/CMI#5708]
When I do /cmi glow i cannot unglow. Basically was messing around getting reacquainted with cmi di /cmi glow and cannot unglow after clearing. I've done /kill, dc, restarted the dev server, /effect clear, and /cmi effect clear. I also was able to replicate the issue by giving it to one of my builders.

---

**Cmi Version (using`/cmi version`):9.0** 

**Server Type (Spigot): 3108-Spigot-191e497-74575d4** 

**Server Version (using `/ver`):1.17** 

**Relevant plugins (Delete if this isn't needed):CMI, CMILib, World Edit, World Guard, Luck Perms, bosshoppro, placeholderapi, and vault**

**Comment by CloudeLecaw** [comment]
Simply use /cmi glow false

**Comment by captainroach606** [comment]
That doesnt work I already tried that. I also tried /cmi glow true then /cmi glow false

**Comment by CloudeLecaw** [comment]
Have u tried without cmi? Sounds like its not cmis glow then..

**Comment by captainroach606** [comment]
I enabled it with CMI's glow

**Comment by captainroach606** [comment]
When I enabled it on my builder he didnt have glow before now when I do false on him it doesnt go away.

**Comment by CloudeLecaw** [comment]
So you tried /cmi glow his name false  and still does not go off?  May tried with the gui?

**Comment by captainroach606** [comment]
yes tried with the gui. The weird thing is when I do /cmi glow then choose say red. Then if I do clear or false it just goes to white glow

**Comment by captainroach606** [comment]
im grabbing a gif for you

**Comment by captainroach606** [comment]
![Animation3](https://user-images.githubusercontent.com/70864628/122070500-053b7980-cdc4-11eb-9c9e-663ceb19f52d.gif)

**Comment by captainroach606** [comment]
Was able to unglow with NBTEditor. I believe it's a issue with spigot or 1.17 not CMI

**Comment by CloudeLecaw** [comment]
Tr so recompile the latest version, i tried it tonand it worked fine ..

**Comment by captainroach606** [comment]
Well Floris and I found a post in the snapshots where someone was complaining abt it. So I think it's a weird World issue with the game or server.

**Comment by CloudeLecaw** [comment]
![Snag_d3583f](https://user-images.githubusercontent.com/12080017/122120817-2c796180-ce2b-11eb-8998-34015ccfd5ad.png)

![Snag_d36a8f](https://user-images.githubusercontent.com/12080017/122120829-2f745200-ce2b-11eb-8f5e-dae963ea479c.png)

![Snag_d378b8](https://user-images.githubusercontent.com/12080017/122120840-31d6ac00-ce2b-11eb-8e41-dd94ae7b07ef.png)

![Snag_d39632](https://user-images.githubusercontent.com/12080017/122120851-3602c980-ce2b-11eb-87fb-2b058a69825b.png)

![Snag_d3ea3e](https://user-images.githubusercontent.com/12080017/122120891-43b84f00-ce2b-11eb-9d6a-5fae9e49c9f6.png)

Maybe its an other plugin that comes accoss there?
maybe a TAB one?

**Comment by Zrips** [comment]
@captainroach606 
What exactly did you modified in players NBT data to remove glow? Might give some idea what caused this to happen

**Comment by captainroach606** [comment]
I literally just ticked the "Glowing:1" to "Glowing:2" it doesnt do it with normal commands or spectral arrows I've found. Since then though I've installed Tabs. It wasnt installed at the time but now that it is its surely gonna give me conflicts.

**Comment by captainroach606** [comment]
my b turned Glowing:1 to Glowing:0

**Comment by Zrips** [comment]
@captainroach606 
Yea, that's strange as /glow false does same thing and sets NBT value to 0 which should have resulted in same thing. Well, as long as its resolved and issue doesn't repeat we can leave it at that. If it reappears let me know.
