### ISSUE TITLE
New Deathmeassages feature cant be set to other language

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5709]
In CMI 9.0 When i try to reload CMI
it sais cant load DE used EN instead..

Like u can see in the screenshot the DE file is created. so i apsected it will load it
But saidly...no
![Snag_ccc340](https://user-images.githubusercontent.com/12080017/122119999-2c2c9680-ce2a-11eb-9833-0f2d285d124f.png)

currently the DE file was just a renamed copy without changes of the EN file just to see that it changes the meassage. i wanted to make sure it loads the right file before i start with translations

**Comment by mrfloris** [comment]
From what i gather some info about death msg might be in cmi9, but it's a feature that's not introduced, it's certainly not finished; probalby why this is something you see.

**Comment by Zrips** [comment]
Will resolve this "issue", forgot to disable its loading on /cmi reload... Silly me...
