### ISSUE TITLE
When using Hex colour code for nick and then clicking on someone name to message them kick you for Illegal characters

### ISSUE THREAD

**Issue by jahangir6969** [Zrips/CMI#5710]
When you have hex colour code using /nick and then click on someone name to message them and send it. It kick you from the server with illegal characters in chat. 

This error in console after trying to send message: pokekhan lost connection: Illegal characters in chat

https://pastebin.com/NDVR3MKf

---

http://8.8.5.0/

paper-1.16.5-775

https://gyazo.com/b31c8315fdb647d456cd35b2de0546d1

I am also using Deluxechat for the Chat. Not sure if this maybe causing the issue or ezcolour for the chat hex colourcode.

**Comment by Zrips** [comment]
are you talking about public messages or private ones here? if its from messages handled by Deluxechat then its not really issue with CMI but more an issue with DeluxeChat. At current state CMI does strip out color codes from players displayname so it should not cause issues from this side.

**Comment by jahangir6969** [comment]
Can confirm it an issue with Deluxechat not supporting hex code........
