### ISSUE TITLE
Hex colour code does not work with Tab

### ISSUE THREAD

**Issue by jahangir6969** [Zrips/CMI#5711]
After you set an Hex colour code using /nick and then go into Tab. It does not show the colour and instead show the hex code instead. 

https://pastebin.com/NDVR3MKf

---

8.8.5.0

paper-1.16.5-775

https://gyazo.com/7e684fac320debea1cf1862bb358d70f

**Comment by CloudeLecaw** [comment]
are you sing the command correct?
can you reproduce it with /cmi nick
what is the placeholder your using in your TabList.yml?

**Comment by jahangir6969** [comment]
This is my tablist config; https://pastebin.com/veV2tzsr

That show playerDisplayname. It seems to be broken when using cmi nick or just /nick

**Comment by Zrips** [comment]
How does your feedback message look like when you change your nickname with hex color code? As it should straight away show it with new colors.

**Comment by jahangir6969** [comment]
So I have tested with just cmi and still having the same issue. Also When I do /cmi nick it pop up with this: https://imgur.com/a/9PKLAuK but it work fine in chat when you nick yourself: https://imgur.com/a/xjOYp3o. Only in tab and when you change the nick it does not show the colour and shows instead the hex colour code :  https://imgur.com/a/xjOYp3o

**Comment by Zrips** [comment]
Why does it look like your are using #5272FF instead of correct format as {#5272FF}. CMI uses this format to allow more complex expressions like named colors as {#cancan} or create gradients with {#edward>}SupaDJ{#red<>}Zrips{#6600cc<} or use short expressions like {#60c} which is the same as {#6600cc}

**Comment by jahangir6969** [comment]
I never knew about the (} for the Hex colour code. It seems like it an overlook that but can confirmed when using {} it fine. So as this got it working. Will just close the ticket down.
