### ISSUE TITLE
[API] CMIAnvilItemRenameEvent result itemstack is of type air when shift clicking the result + async

### ISSUE THREAD

**Issue by the456gamer** [Zrips/CMI#5716]
**Description of issue:**
when Listening to CMIAnvilItemRenameEvent, `event.getItemTo().getType().getKey()` = minecraft:air, not the source items type
when the event was triggered from shift right clicking on the source

**To reproduce:**
0. listen to CMIAnvilItemRenameEvent
1. log `event.getItemFrom().getType().getKey()` and `event.getItemTo().getType().getKey()`
2. observe how when renaming a item in an anvil, the even is triggered
3. observer how when just righ clicking, the material is the same
4. observe how when shift-right clicking, the material is different due to the result being `minecraft:air`
---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/42748092/122450624-1f7d7f00-cf9f-11eb-9724-7f650020e73b.png)
(9.0.0.0)

**Server Type (Spigot/Paperspigot/etc):** 
Spigot 1.17-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 
3147-Spigot-9472b09-d7ef1e9  (MC:1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Tried to reproduce this issue with 3149-Spigot-101ebb6-9122f5a spigot build, everything seam to work properly, shift or basic click produces correct results with correct materials. Can you confirm that this issue is still present of atleast point out at which EventPriority did you listen to this event?

**Comment by the456gamer** [comment]
ok, done some more testing, and this is partially my bad. the way i got the events data was through discordsrv's alert feature, which might run the event on another thread(?) (speculation)

using a dedicated event handler works fine
![image](https://user-images.githubusercontent.com/42748092/122592857-c07e3f80-d05c-11eb-8364-bbb942b7b80b.png)
vs
![image](https://user-images.githubusercontent.com/42748092/122592918-d5f36980-d05c-11eb-8000-8d29c607da77.png)

latest spigot does the same (in regards to normal use. not made a test case for broken use yet)
![image](https://user-images.githubusercontent.com/42748092/122593098-1521ba80-d05d-11eb-8bf5-48dc50ca7ee2.png)

**Comment by the456gamer** [comment]
Ok, got it. when asking it to run the event later with 
```java
Bukkit.getScheduler().runTaskAsynchronously(this, () -> {});
```
(or others), then the item is air

see video

https://user-images.githubusercontent.com/42748092/122594333-cc6b0100-d05e-11eb-84cd-14bb89be0b04.mp4

![image](https://user-images.githubusercontent.com/42748092/122594411-e1479480-d05e-11eb-8069-6aff7a071978.png)

**Comment by Zrips** [comment]
This event is not meant to be processed in async as you have option to modify it and give out different result or cancel event entirely. Will make some modifications to pass over correct item even if you would use it in async.
