### ISSUE TITLE
Ride command shows Giant slime between players

### ISSUE THREAD

**Issue by thunderlight411** [Zrips/CMI#5717]
Giant slime apares when you use /cmi ride on a player

https://imgur.com/a/fCSmRYO

---

**Cmi Version (using`/cmi version`):** 
18.06 22:01:46 [Server] Server thread/INFO --------------------------------------------------
18.06 22:01:46 [Server] Server thread/INFO CMI: 9.0.0.0 BungeeCord CMIB  MySQL
18.06 22:01:46 [Server] Server thread/INFO CMILib: 1.0.2.0 
18.06 22:01:46 [Server] Server thread/INFO Server: Spigot 1.17-R0.1-SNAPSHOT
18.06 22:01:46 [Server] Server thread/INFO CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Disabled 
18.06 22:01:46 [Server] Server thread/INFO Modules -> 55 enabled 1 disabled: votifier
18.06 22:01:46 [Server] Server thread/INFO --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
This server is running CraftBukkit version 3145-Spigot-9472b09-f992ce6 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Do you have any plugin which could be responsible for mob spawns or monster modifications?
