### ISSUE TITLE
Portals

### ISSUE THREAD

**Issue by niekmos** [Zrips/CMI#5719]
**Description of issue:**
When using portals feature, anything you click in GUI will display the commands linked to it in chat
**Cmi Version (using`/cmi version`):** 
9.0.0.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.17

![image](https://user-images.githubusercontent.com/36360115/122620008-25a05800-d092-11eb-83fd-b053405464e2.png)

**Comment by niekmos** [comment]
Editted, because it happens with everything in the GUI

**Comment by Zrips** [comment]
Confirmed, will get a fix with next version.
