### ISSUE TITLE
Teleport problem:

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#572]
Hi I was playing around with teleport settings and I have small problem as when when     SafeLocationDownThenUp: false or true some players get teleported into the void in normal world. This happens when player dies and types /dback or /back if they die close to bedrock they just teleport to void and die. Fun fact it doesn't even inform player that this  teleport is unsafe xD. My players are so angry at me and I have to give them their items back ahh. Think  you need to work more on teleport still. 

By the way I don't know 100% how some players done that I just got informed that they get teleport to void so I can only tell you of what I hear. I did not recreated that issue my self yet. 
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Teleport:
    # When true then while checking for safe location, we will try to determin it goind down and if it fails, then up from target location
    # When set to false, then first of all location above target location will be checked, then down
    SafeLocationDownThenUp: false
```

**Cmi Version (using`/cmi version`):** 
7.8.7.4
**Server Type (Spigot/Paperspigot/etc):** 
paperspigot
**Server Version (using `/ver`):** 
1.12.2

**Comment by CloudeLecaw** [comment]
could you try this with spigot 1.12.2?
i renember this bug was fixed Long ago for spigot 1.12.2 with cmi.
...

**Comment by arturek1666** [comment]
If i would have to test it on spigot it would mean I have to also change a lot of settings as server is optimized in a way that if i change to spigot water will not flow and other issues might show up so no I can't change to spigot :(. I am saying that because testing would be good on my main server as players play there. However because of I don't want to mess around with my settings i just can't use spigot xD.

**Comment by Zrips** [comment]
@arturek1666 You don't need to remake it on spigot, what i need is a way to reproduce this bug if there is any to have. Test it with regular player with same permission nodes as those who reported issue, if you can reproduce it more than twice in a row, then report back with some extra information how you reproduced it. At moment i can confirm and reproduce issue on my test server, i will fix it in a day or two.

**Comment by arturek1666** [comment]
Will try my best to find out the way it's happens. Not sure if i will be able to but will try

**Comment by arturek1666** [comment]
The teleport issue is mostly solved closing.
