### ISSUE TITLE
Custom Plugin don't read CMI Instances

### ISSUE THREAD

**Issue by AnonymousStar02Dev** [Zrips/CMI#5720]
I develop a plugin and it don't find the services. The problem is only with cmi and no with other Economy plugin as EssentialsX

The version of plugin is 8.8.5.0 and server version paperspigot 1.16.5
I try to solv with support on discord but nothing. The supporter says that CMI work fine!

**Comment by Zrips** [comment]
What code are you using in particular to access CMI methods?

**Comment by AnonymousStar02Dev** [comment]
I solved. I had vault dependency as compile and no provided
