### ISSUE TITLE
[Priority: LOW] Tabcomplete of /enderchest

### ISSUE THREAD

**Issue by jurajplayercze** [Zrips/CMI#5721]
**Description of issue: *When i try to tabcomplete nick that i started typing, it won't show list of players as it's shown on screens*
https://prnt.sc/161n5tz
https://prnt.sc/161n8fo

**Cmi Version (using`/cmi version`): *9.0.0.0*

**Server Type (Spigot/Paperspigot/etc): *Spigot* 

**Server Version (using `/ver`): *Build 3151, development*

**Comment by Zrips** [comment]
Is this default cmi alias or custom one? I mean, was /enderchest enabled in alias.yml (double check if you have tab complete enabled in there) or was it made with /customalias command
