### ISSUE TITLE
Improvement of custom recipe 

### ISSUE THREAD

**Issue by Slachy-Dot** [Zrips/CMI#5728]
Hi I am trying to switch my costum recipe plugin to cmi but atm it only does support recipes for crafting table and the regular furnace it would be great if we could use cmi also for the new blocks added in the villager and pillager update these blocks are the stonecutter, blastfurnace, campfire and smoker

**Comment by Zrips** [comment]
For time being we are utilizing basic minecraft recipe handling which is purely based on material type and amount without any extra criteria. To have more complex handling complete change of recipe handling should be done which is allot of work. There are more specialized plugins for this task if you want something more complex then current CMI system.

**Comment by Slachy-Dot** [comment]
The stonecutter is a basic recipe handling and is a replacement for the crafting table for many players since the 1.13 update 
i really don't understand why it would need extra criteria as they are shapeless recipes just not made in a crafting table but a stonecutter
