### ISSUE TITLE
Nickname BUG

### ISSUE THREAD

**Issue by LivingDarkness** [Zrips/CMI#5733]
I encountered a problem, which we cannot understand if it is due to CMI or another plugin, practically since I updated the plugin to the latest version I could no longer enter the server (I use the bungee) and in practice when I connect to the server it tells me that the server is offline, when instead it is online, in fact the other players could enter, (I was a week with this problem), today I have the idea of ​​deleting the cmi database since this problem also occurs with previous versions of CMI would not resolve, deleting the database let me in.  after a few hours I realized that the problem was with my nickname:
 {#e60000}L{#e65300}i{#e6a500}v{#d3e600}i{#81e600}n{#2ee600}g{#00e625}_{#00e677}D{#00e6ca}a{#00aee6}r{#005ce6}k{#0009e6}n{#4900e6}e{#9c00e6}s{#e600dc}s

in fact when I go to put this nickname it throws me off the server telling me that it is offline, I reset the nick again and let me in, so I do not understand what the problem is, if I change nick normally nothing happens, but if I put the modified nick that I had before (I had that nick for three months) he doesn't let me in anymore.  I tried to put the same CMI folder in my hub and the nick worked, so I just can't figure out what the problem is.

Cmi Version: 9.0.0.1

Server Type: Paperspigot

Server Version: 1.16.5 - Java 16

**Comment by Zrips** [comment]
As i cant reproduce this issue with your provided example it could be issue with another plugin or your setup in general. Could you try testing this with CMI only and provide your config.yml file? Or atleast try renaming CMI folder and check it out with default configurations. We have to determine what causes this issue.

**Comment by LivingDarkness** [comment]
checking all the plugins one by one i found the problem is luckperms, i don't understand what the compatibility problem is.

**Comment by Zrips** [comment]
It might fail to handle to long nicknames in some places. Each HEX color code gets translated into messy vanilla standard which inflates entire line by quite a bit. So there might be an issue with having too long line. 
Where exactly was the issue? Like what part of LuckPerms used players nickname which caused this issue?

**Comment by LivingDarkness** [comment]
the nickname is displayed in the tab and in the chat, but first function normally without any problem, I cannot determine if the problem was caused by the update of CMI or Luckperms.

**Comment by LivingDarkness** [comment]
the nickname is displayed in the tab and in the chat, but first function normally without any problem, I cannot determine if the problem was caused by the update of CMI or Luckperms.

**Comment by Zrips** [comment]
Would be interesting to know where exactly it failed and maybe I could fix it from my end or it might be needed to be fixed from luckperms side. Hard to say at this moment as this doesn't look to be popular issue

**Comment by LivingDarkness** [comment]
how do i know what the problem is?  does not give any kind of error.

**Comment by Zrips** [comment]
I'm that familiar with LP usage or code itself, so cant really give any advice where to look for pasiblės issue. But if issue got resolved then its fine for time being, maybe in future it gets more clear where actual cause is and we can fix it from ether end.
