### ISSUE TITLE
[playerName] permission error does not translate in console

### ISSUE THREAD

**Issue by levtey** [Zrips/CMI#5735]
**Description of issue:**
When permission feedback is given in the console, the [playerName] placeholder is not translated.
![image](https://user-images.githubusercontent.com/60494179/123031240-da8b8b00-d398-11eb-9ae2-3b39e4baa120.png)

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/60494179/123031194-c778bb00-d398-11eb-878a-de98202acf38.png)

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** Build 3159

**Comment by Zrips** [comment]
Got resolved in latest versions
