### ISSUE TITLE
/cmi mute does not work and customrecipe exp

### ISSUE THREAD

**Issue by EndlessLegends** [Zrips/CMI#5736]
**Description of issue:**
1. mute cmd does not work.
 /cmi zrips 1m -s testmessage
Usage: /cmi mute [playerName] (time) ..............................
2. You cannot set exp in furnace tab of custom recipe to be higher than 1.0.
In the 1.16 update, if you bake ancient_debris to get netherite_scrap, you get 2.0 experience, but cmi plugin cannot set it to 1.0 or higher even though it is version 1.17.
- https://minecraft.fandom.com/wiki/Smelting

!!!!!! It has been confirmed that Op players cannot use themselves. (The same goes for other commands, such as alarms.) !!!!!

- Tested with only 4 related plugins without any other plugins.
---

**Cmi Version (using`/cmi version`):** 
- 9.0.0.1 (cmi)
- 1.0.2.2 (lib)
- 1.0.2.3 (Inject)
**Server Type (Spigot/Paperspigot/etc):** 
- purpur
**Server Version (using `/ver`):** 
This server is running Purpur version git-Purpur-1179 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
Previous version: git-Purpur-1177 (MC: 1.17)
**Relevant plugins (Delete if this isn't needed):**
cmi, cmieinjector, cmilib, vault

**Comment by Zrips** [comment]
Will increase max exp gain to 2. For mute command, I dont know why would you want to mute yourself, i can enable that, but its a weird one.
