### ISSUE TITLE
[Request] Playtime Rewards- Toggling stacking

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#574]
An option to set whether a playtime reward will stack or not. Currently they do and there's no way to disable.

**Comment by CloudeLecaw** [comment]
well i try to find a useage for this on my written down schematics…

hmmm.. 
i want a user just can have an item once….ok then i give it him for playtime or playing after X,
and dont make it repeatabel,
i want that a user gets stacked reward then i give it to him in repeatable intervall

When does it make sense to have something "aggain" that does not got stacked
or better why should i get something aggain if i cant get the reward just once?

**Comment by Zrips** [comment]
None stacking will be added with next update
