### ISSUE TITLE
head database doesnt work

### ISSUE THREAD

**Issue by NightLife-SG** [Zrips/CMI#5741]
**Description of issue:**
head database not working, i know it working before because i used those head alot.
---
![image_2021-06-25_223618](https://user-images.githubusercontent.com/84533050/123440811-c26c7380-d605-11eb-9365-072fdd5dd329.png)

**Cmi Version (using`/cmi version`):9.0.0.1

**Server Type (Spigot/Paperspigot/etc):*paper* 

**Server Version (using `/ver`):*1.17*

**Comment by Zrips** [comment]
Gets a fix with next build.
