### ISSUE TITLE
CMILib Auto-downloads keeping ALL the old cmi Lib files, even though Im using CMI8.8.4.7.jar, breaking changes?

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#5746]
![Screenshot 2021-06-27 13 05 37](https://user-images.githubusercontent.com/144046/123543850-72e29080-d748-11eb-869e-f0eecbbedaef.png)

CMILib is auto-downloading itself, and has MULTIPLE versions without cleaning itself up, which means that Spigot/Paper complains when it boots as it doesn't know which one to load.

Also I haven't updated to CMI 9 yet as you said not to update as it's not stable, so why is it downloading a library for an older version of CMI? won't using the latest version of CMILib break things in the older version of CMI?

**Comment by SenseiMunchkin** [comment]
A solution mentioned in the #help channel by the mighty floris:
![image](https://user-images.githubusercontent.com/25995812/123670748-28721a00-d803-11eb-902e-fd3c159eaa2c.png)

You could also: 
![image](https://user-images.githubusercontent.com/25995812/123670788-32941880-d803-11eb-9186-11a11d2c1249.png)

**Comment by mrfloris** [comment]
8.8.4.x is fairly old for 1.16.5 even, I would at least upgrade to the latest stable of CMI , 8.8.5.0, and make sure the cmi lib 1.0.2.4 is in the plugins/ directory.

**Comment by mrfloris** [comment]
Let us know please when you upgrade to cmi 8.8.5.0 and use cmi lib 1.0.2.4 or use cmi 9.0.0.3 and cmi lib 1.0.2.4 that this is still happening?

**Comment by TomLewis** [comment]
Im running Paper 1.12.2 if that makes any difference.

**Comment by mrfloris** [comment]
Yes, CMI 8.8.5.0 is the latest stable and supports CMILib and 1.12.2, same with CMI 9.

**Comment by Zrips** [comment]
As of recent CMILib update old files gets automatically removed. In case you really dont want to have it there you could remove CMILib in general, you will lose /cmi solve command and placeholder relating to equation calculations. But if you are not using those you can just remove CMIlib and that's that.
