### ISSUE TITLE
bugcmi and deluxechat

### ISSUE THREAD

**Issue by QuickLight** [Zrips/CMI#5747]
**Description of issue:**
If I install CMI and DeluxeChat at the same time, DeluxeChat cannot modify the chat format, it will be fine if I delete the CMI

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by SenseiMunchkin** [comment]
In the config.yml of the CMI directory you can use CTRL + F to search `ModifyChatFormat:`, or it should be at or around line 709. Set this option to `false` to prevent CMI from modifying the chat format, therefore allowing DeluxeChat to take control over the chat format.

**Comment by Zrips** [comment]
@QuickLight 
You can only have one plugin modifying chat format, so as @SenseiMunchkin mentioned, you simply need to disable CMI chat modification and then ChatControl will take over
