### ISSUE TITLE
Incorrect permission node listed for armor stand torso in docs

### ISSUE THREAD

**Issue by AutismFather** [Zrips/CMI#5764]
Documentation for Armor Stands here: https://www.zrips.net/cmi/armor-stand-editor/

Permission node _cmi.command.armorstand.body_
Should be _cmi.command.armorstand.torso_

**Comment by CloudeLecaw** [comment]
why?
the part is allways called body... why torso?

**Comment by AutismFather** [comment]
Using cmi.command.armorstand.body didn't work. When I set the permission to cmi.command.armorstand.torso, then people could use it.

**Comment by CloudeLecaw** [comment]
ok thats strange so the error is that torso is wrong and it should be body ;)

Thanks for catching this ^^

**Comment by Zrips** [comment]
Actually both of those permissions are valid. Torso permission allows you to rotate just the torso part, while body allows you to rotate entire body around. Will add missing permission node to wiki page.
