### ISSUE TITLE
Chat Texthover

### ISSUE THREAD

**Issue by Baschounette** [Zrips/CMI#5767]
Hi

In locale translations files in 1.17 version of CMI, we dont have settings to change the texthovermessage when hovering the chat message.
Where is it ?

In old version of CMI running 1.16.5, this is present.

ty

**Comment by CloudeLecaw** [comment]
You might take a look into CMILib transaltion folder? many things moved there :)

**Comment by Baschounette** [comment]
Ty very much :) 
I think you should tell it on your wiki ^^

**Comment by Zrips** [comment]
Will update wiki to indicate that some locale line got moved to new location.
