### ISSUE TITLE
Anvil command not supported in 1.17 with 9.0.0.3?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5773]
**Description of issue:**
/cmi anvil      leads to.... the server version does not support this feature.....
![Snag_6aeb865](https://user-images.githubusercontent.com/12080017/123869488-5c4b5d80-d931-11eb-88f7-4b9b8dabc04e.png)

![Snag_6af5958](https://user-images.githubusercontent.com/12080017/123869571-74bb7800-d931-11eb-95d9-8626109a3944.png)

**Comment by Zrips** [comment]
Due to huge change in base code anvil got broken in 1.17 version. Working on solution.

**Comment by Zrips** [comment]
Will be fixed with next build
