### ISSUE TITLE
You can make yourself float with /sit and a piston.

### ISSUE THREAD

**Issue by DrakePork** [Zrips/CMI#5776]
**Description of issue:**
If you do /sit on a block on a piston, and then push the piston up, you will float above the piston. You can then put more pistons to move yourself further.
What happens when theres a block on the piston:
![2021-06-30_06 11 14](https://user-images.githubusercontent.com/29175884/123903636-5c6a4e00-d96f-11eb-92de-aef4a697ed56.png)
![2021-06-30_06 52 53](https://user-images.githubusercontent.com/29175884/123903896-d4d10f00-d96f-11eb-8dbf-f4e7253cea0d.png)
![2021-06-30_06 11 22](https://user-images.githubusercontent.com/29175884/123903644-5f653e80-d96f-11eb-8ea2-4aae5e399f8d.png)

And heres what happens when you do /sit directly on the piston:
![2021-06-30_06 52 14](https://user-images.githubusercontent.com/29175884/123903952-ec0ffc80-d96f-11eb-8f60-8b74386aa617.png)
![2021-06-30_06 52 21](https://user-images.githubusercontent.com/29175884/123903940-e61a1b80-d96f-11eb-9a3c-d2c507966c2a.png)
![2021-06-30_06 52 27](https://user-images.githubusercontent.com/29175884/123903963-ef0aed00-d96f-11eb-9de9-8c16d19a45cc.png)

---

**Cmi Version (using`/cmi version`):** 8.8.4.9

**Server Type (Spigot/Paperspigot/etc):** Purpur (Paper Fork)

**Server Version (using `/ver`):** 1.16.5

Ignore all of the comments underneath as Cloud somehow hasnt been able to understand what this issue is about.

**Comment by CloudeLecaw** [comment]
U can push the armorstand you sit on with Fishing rod too. Lol
For making the unpush u need to edit the armorstand and make it notninteractable and let isnpass gravity. Can be done with cmis armorstand editor

**Comment by DrakePork** [comment]
What I'm talking about is when you do /sit, an armourstand is made and you basically "ride it". You can use a piston to push yourself up from the ground (pushing the armour stand that has been generated to allow you to sit).

**Comment by CloudeLecaw** [comment]
Well..the next thing...is... Who wanne let.himself s it.on a stand... And even when.. why...someone should push him then with a piston? Trollfriend?...
Lets be behappy to fix all things that trolls might test out?..well the priority of fixing this should be, very very.. low.

**Comment by DrakePork** [comment]
I think you're confusing /ride with /sit. What I am talking about is the /sit command, which makes people /sit. If you hit someone whos /sit they'll go out of /sit, if you fishing rod someone whos /sit then nothing will happen, if you water someone who /sit nothing happens and if you lava someone whos /sit and if you lava someone whos /sit they will go out of /sit.

Now, if someone /sit on a block on a piston and they activate the piston, they will not go out of /sit but get pushed into the air and will appear as if they are floating and not sitting.

Yeah this is a low priority thing, but its a bug report nonetheless. This github isnt just for plugin breaking bugs.

**Comment by CloudeLecaw** [comment]
I know
And i ask you aggain

Why soneone should use a piston on ansitter when lava is more effectiv?

**Comment by DrakePork** [comment]
What the fuck are you talking about? What I am saying is that WHEN someone sits on a piston LIKE THIS:
![2021-06-30_06 11 14](https://user-images.githubusercontent.com/29175884/123901116-b1f02c00-d96a-11eb-96ee-204e55fc61bc.png)

and they flip the lever, instead of them either being just pushed up and down with the block or stop sitting, this happens:
![2021-06-30_06 11 22](https://user-images.githubusercontent.com/29175884/123901172-c8968300-d96a-11eb-9ffe-e3709d34508b.png)

I have no clue what you mean by "when lave is more effective". Does lava also push the sitter into the air?

**Comment by CloudeLecaw** [comment]
So why your doing this, is still the Questionen

**Comment by DrakePork** [comment]
I dont know the reason anyone would do this, I'm just pointing out that you can make yourself "fly" with /sit and a piston with a block ontop, since you know, this is a bug report area, and this clearly shouldnt be the expected outcome since when you just do /sit on just a piston you go up and down with the piston.

**Comment by CloudeLecaw** [comment]
You cant move if you do the magic is over

**Comment by DrakePork** [comment]
Yeah I know? I'm literally just reporting a small bug so I have no clue what point you're trying to make here.

**Comment by CloudeLecaw** [comment]
Just the fakt it was not nessesary to point this oit as a bug ;)

**Comment by DrakePork** [comment]
I dont think you know what a bug is. 
 
 If you do /sit on a piston, and you push it up and down you'll move up and down with the piston, but if you put a block ontop of the piston and do /sit on that, you'll just get pushed up. Since clearly being pushed up and down is the EXPECTED outcome I've reported this as a bug.

**Comment by CloudeLecaw** [comment]
Its a bug. But nothing that needed to benfix

**Comment by DrakePork** [comment]
Yeah and what is this Issues page for? Is it reporting bugs? No matter what size? I am literally just pointing it out.

**Comment by CloudeLecaw** [comment]
No grap some ice and beer and lets play yogioh cards aggain, last time you won the round ;D

**Comment by DrakePork** [comment]
What? Are you like 10 or some shit?

**Comment by CloudeLecaw** [comment]
And tommoror i will create a ticket where i will show you the bug, wher you destory players afk mode with a piston and a fishing rod ;).. and hope for cmi tonfix it.

**Comment by CloudeLecaw** [comment]
The fakt is you reported something that cant be fixed. So you should live with it. This is how the sit isnworking. You also could create this without sitting and just an armorstand ir just the arrow. Thats how its made and how we are able to sit. If you want to fix this you need to report to.mohjang they should fix arrows on armorstands should not be mobeable by pistons anymore.
Cmi cant do anything here, so its no cmi bug.

**Comment by DrakePork** [comment]
Can you please stop commenting and let the adults talk since you clearly dont know how anything works? Since it works as intended with just a piston and /sit but not with piston + block on top and /sit its most likely just some missing code. I would advice you to go learn how to spell correctly. This has jack shit to do with placing armour stands, it has to do with the  INVISIBLE armour stand not being brought down after you use a piston. Now maybe you should go learn how the plugin works before commenting on Issues, that might be a good idea.

**Comment by CloudeLecaw** [comment]
all right Mr Drake BugFinder xD

You wanne creat a ticket a bout the piston that pushes you out of afk too?

**Comment by DrakePork** [comment]
Still have no clue how you think this is related to trolling or pushing people out of afk.

**Comment by CloudeLecaw** [comment]
Well what ever.

This is no cmi Bug. o this ticket will be closed liek others that report minecraft bugs here ;)

**Comment by levtey** [comment]
You can make yourself float in the air by doing `/sit` on the edge of a block and then breaking it just the same... I personally think there are too many outside variables for there to be a simple fix, since methods like `Block#setType` call absolutely no events and the best way to account for all changes would be to run the checker on a timer. In fact, I think it's a unique thing to be able to do this, so if it is fixed, it should be toggleable in the config (both for lag and quirk purposes).

**Comment by DrakePork** [comment]
Well yeah there's probably more ways of making yourself float with /sit I'm just reporting the one I found. You can also keep pushing yourself upwards with this method like so:
![2021-06-30_07 05 16](https://user-images.githubusercontent.com/29175884/123904994-bec44e00-d971-11eb-9604-3dc3d8278e67.png)

I don't really know how Zrips has set up how CMI handles you sitting on a piston code-wise, but since sitting on a piston works as expected (with you being pushed up and down with the piston) I'd say it would probably just be to extend on that method to include a check for any blocks the piston is pushing.

And yeah sure why not make it toggleable in the config.

**Comment by CloudeLecaw** [comment]
Not impossible to add, any may for one piston fine... but coudlt this be a bit to intensive for the server regarding to the extra ticks it needs if more that one pistons work?

Well if there will be something added as temporary "fix" then please let it be a toggle "fix" so we can turn it off

**Comment by DrakePork** [comment]
Like I've said, I'm just pointing out that it exists, I have no clue how Zrips has set up his code so its up to them to see if theres an easy fix that wont cost a lot of server resources to implement.

**Comment by Zrips** [comment]
This gets resolved with next build. Will not have impact on servers performance.
