### ISSUE TITLE
spaming in my server console 

### ISSUE THREAD

**Issue by ProtoGhost** [Zrips/CMI#5777]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):*9.0.0.3* 

**Server Type (Spigot/Paperspigot/etc):*paper* 

**Server Version (using `/ver`):*1.17*
![lol](https://user-images.githubusercontent.com/67905221/123946119-7b430180-d9bc-11eb-9117-0fde244c5c61.jpg)
* 

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Gets a fix with next build
