### ISSUE TITLE
Task #570 for CMI v9.0.0.3 generated an exception

### ISSUE THREAD

**Issue by NightLife-SG** [Zrips/CMI#5780]
**Description of issue:**
some error spamming in my console

---

01.07 00:03:04 [Server] WARN [CMI] Task #570 for CMI v9.0.0.3 generated an exception
01.07 00:03:04 [Server] INFO java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
01.07 00:03:04 [Server] INFO at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
01.07 00:03:04 [Server] INFO at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
01.07 00:03:04 [Server] INFO at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
01.07 00:03:04 [Server] INFO at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
01.07 00:03:04 [Server] INFO at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
01.07 00:03:04 [Server] INFO at com.Zrips.CMI.Modules.Afk.AfkManager$1.run(AfkManager.java:290) ~[?:?]
01.07 00:03:04 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-66]
01.07 00:03:04 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-66]
01.07 00:03:04 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-66]
01.07 00:03:04 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-66]
01.07 00:03:04 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-66]
01.07 00:03:04 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-66]
01.07 00:03:04 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-66]

---

**Cmi Version (using`/cmi version`):*9.0.0.3* 

**Server Type (Spigot/Paperspigot/etc):* paper 1.17 build 66* 

**Server Version (using `/ver`):* 1.17
![image_2021-07-01_000609](https://user-images.githubusercontent.com/84533050/123994629-232dee80-da00-11eb-886f-59ce2433584c.png)
* 

**Relevant plugins (Delete if this isn't needed):**

**Comment by mrfloris** [comment]
<img width="394" alt="Screenshot 2021-06-30 at 22 04 35" src="https://user-images.githubusercontent.com/28841349/124024196-29679f00-d9ef-11eb-86f8-ffaf0616b693.png">

I see reports for 1.16 as well
https://paste.md-5.net/ikejugukoz.cs

**Comment by mrfloris** [comment]
Oh i was just informed that upgrading to 9.0.0.4 should fix this.

**Comment by Zrips** [comment]
This was resolved with 9.0.0.4 version
