### ISSUE TITLE
Homes Gui problem

### ISSUE THREAD

**Issue by MusicTW** [Zrips/CMI#5782]
![Problem photo](https://user-images.githubusercontent.com/52475422/124060307-5a7fb800-da5f-11eb-924b-46b9e17bdd06.png)
![Normal photo](https://user-images.githubusercontent.com/52475422/124060312-5c497b80-da5f-11eb-8cbe-4ce4f7dd98e4.png)

One of my player in the server just has this problem
She has 5 homes but the homes gui just appeared like this yesterday, and no error messages when the problem happened

**Cmi Version (using`/cmi version`): ![image](https://user-images.githubusercontent.com/52475422/124060414-93b82800-da5f-11eb-96c1-5809424c2bcb.png)** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`):
![image](https://user-images.githubusercontent.com/52475422/124060452-a92d5200-da5f-11eb-9074-48cce38d0ca6.png)
**

**Comment by Zrips** [comment]
Is this issue appears only for one player? If so, could you check database for home records for this player and provide it here for testing?

**Comment by MusicTW** [comment]
How to do

**Comment by Zrips** [comment]
You can send me sqlite file over discord Zrips#9691 if you dont want to dig around it yourself.

**Comment by MusicTW** [comment]
thx, i just sent that to you

**Comment by Zrips** [comment]
Gets fix with next build
