### ISSUE TITLE
-s for walkspeed and flyspeed shows feedback in console :3

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5789]
![image](https://user-images.githubusercontent.com/12080017/124120299-e8fe3480-da73-11eb-8b9f-c2fbd742328b.png)

> flyspeed [playerName] [amount] (-s)
> walkspeed [playerName] [amount] (-s)

We use this on EventCommands.yml
- cmi flyspeed [playerName] 1 -s

Ingame its ok
But the console gives the output 
[13:06:01 INFO]: Die Fluggeschwindigkeit von StellaMaus312 (Online) wurde auf 1.0 gesetzt.

Normaly this command should not output anything to console because of the -s useage

Same appears to walkspeed command. Thats why i added it here too

**Comment by Zrips** [comment]
Will fix.
