### ISSUE TITLE
NULL error when you use $ in pms

### ISSUE THREAD

**Issue by Tobi-Jakka** [Zrips/CMI#5792]
**Description of issue:**

Whenever I use "$" in pms I get an internal error. It throws a null error in console.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/25k2GubB
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
8.8.5.0
**Server Type (Spigot/Paperspigot/etc):** 
paperspigot
**Server Version (using `/ver`):** 
1.16.5 git-paper-778

**Comment by Zrips** [comment]
This should be fixed in 9.x version
