### ISSUE TITLE
cmi se - First lines missing if empty

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5799]
**Description of issue:**
When your looking on a sign and using /cmi se the suggested Editing like is missing the fist \n if the first line is empty
Same hallpen if the first, secound and thrid line is empty and the text is on the fourth line the empty once before are missing and you need to add the missing \n each time manually what makes this feaute a bit confomfortable

![Snag_15d75374](https://user-images.githubusercontent.com/12080017/124323361-7bd8c500-db81-11eb-8b54-a2a2b160e69b.png)

![Snag_16312b07](https://user-images.githubusercontent.com/12080017/124331190-30c5ae80-db8f-11eb-9f40-b5af0535a7b9.png)

![Snag_15d4e090](https://user-images.githubusercontent.com/12080017/124323150-1be21e80-db81-11eb-8d71-852a8fa1306a.png)

Note: This issue exists since a longer time allready.. i just forgot to report is earlier :3

**Comment by Zrips** [comment]
Confirmed, will fix with next build.
