### ISSUE TITLE
A command to follow a player

### ISSUE THREAD

**Issue by Ew9304** [Zrips/CMI#58]
Would be great if you can add a /follow command or similar for when players are going afk for a few minutes but don't want to be left behind. Would be a great addition for server donators. Would also be cool if we can set a max time per /follow before they need to reiniate /follow again. So if I did /follow Zrips it would say "You are following Zrips for the next 5 minutes"

... Just an idea for some future updates

**Comment by Zrips** [comment]
Well... This is not some static world, we are talking about movement across terrain where you can build or destroy blocks. So if player A starts climbing up by building 1 block tower, in what manear should player B follow him? Why not simply use teleport command or ask for player A to wait those couple minutes :)
