### ISSUE TITLE
REQUEST: Random Teleport

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/CMI#580]
can you add a Random Teleport? so we can make Random Teleport Signs in Worlds like Freebuild-World

**Comment by CloudeLecaw** [comment]
wer allready have this

> /cmi tppos (playerName) [x] [y] [z] (world) (pitch) (yaw) (-rng:[range]) - teleports player to defined location. If -rng is defined, then player get teleported to random location by x and z locations from target location.

x z y is your center point,
 pitch and yaw he location then head is looking to
 add -rng:[range]  for the random range

you can create a customalias for this now.
open your customalias.yml and creat a randomteleport command with permission

Example:
```
  randomteleport:
  - perm:cmi.command.customalias.randomteleport! asConsole! cmi tppos [playerName] 0 0 0 world 0 0 -rng:2000 -s
```

this examopel create a command called _/randomteleport_
the permission to use it is _cmi.command.customalias.randomteleport_
The comamnd in example teleports you to a random play accround the area 0 0 0 in world "world"
the -s is for beeing silent so the players get no output from CMI ;) - this is also optional
By the way. The variants pich yaw and world are optional too, if u use no world argument for the comamnd the currentl world would be taken for the command

Hmm does this look like what u needed?
**Yes it exactly does xD**

**Comment by HomeLandingsDE** [comment]
looks like an alternative - unfortunately this does not really work.

I typed the command as you wrote it. Of course, the values for [x] [y] [z] [world] [pich] [yaw] and [Range] changed but when I then execute the command

"No player with this name was found"


I then tried to omit the "perm" and "asConsole" to see if it works - nop same error message

**Comment by Zrips** [comment]
@HomeLandingsDE Actually tppos doesn't support -s currently, will make it work tho with next update. But with same next update you will get appropriate /cmi rt (playerName) (worldName) command

**Comment by CloudeLecaw** [comment]
i tried   /cmi tppos Cloude_Lecaw 16 77 -551 -174 7 -rng:2000    this one works as Teleport


when the var world is uses is does not work anymore, even if was written in the command

so your right the worldwar needs to be fixed

**Comment by CloudeLecaw** [comment]
Could you also add for an rtp the option to
- not land in caves (allways on the top of it)
- not land in the ocean
- not land on 2x2 blocks that are surrounded by ocean

this would be neded things for rtp

**Comment by Zrips** [comment]
2x2 block in a ocean? What chance of that happening? I can add check for water block, but small lands?... Hardly worth effort.
