### ISSUE TITLE
[bug] bossbarmsg doesn't take [playerName] in cmd:"" anymore.

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#5800]
**Description of issue:**

The website has an example: 
```
/cmi bossbarmsg all -a:1 Healing incomming in [autoTimeLeft]! -t:2 -p:1 -cmd:"msg [playerName] &2Some dude healed you!;;cmi heal [playerName] -s" -n:testing -c:red
```
This doesn't work, typing this in console to see the syntax and slightly updating the command to this also doesn't yield results:
```
/cmi bossbarmsg mrfloris -t:2 -n:testing -p:1 -c:red -cmd:"cmi heal [playerName]" -a:1 Healing incomming in [autoTimeLeft]!
```

I've tried a few variations but console always says: (the same for `cmi msg` and stuff like that.
```
Can't find player with this name! (heal -> [playerName])
```

The bossbar shoes up and animates and runs the commands, so that part works, it's the part of finding `[playerName]` (who should we msg/heal) it doesn't seem to get parsed.

<img width="442" alt="Screenshot 2021-07-03 at 00 25 20" src="https://user-images.githubusercontent.com/28841349/124333658-273f4500-db95-11eb-89b7-3d9de432083f.png">

**Comment by Zrips** [comment]
Updating/fixing with next version.

**Comment by mrfloris** [comment]
Thank you, looking forward to the pcmd addition.
