### ISSUE TITLE
Support vanish status in other plugin's TabMenu

### ISSUE THREAD

**Issue by rockbyo5** [Zrips/CMI#5802]
**Description of issue:**
I am using a plugin called tabs as a tab menu replacement. I love it but when i go in vanish using CMI, it doesn't hide me. The author of the plugin says the ball is in CMI's park since "it's not tabs' job to hide players". As such, it'd be great if you could implement that.

Here is the spigot page for the plugin (free version although i use the premium version)
https://www.spigotmc.org/resources/tab-1-5-x-1-17-free-version.57806/

---

CMI version: 9.0.0.4

Paper 1.17

git-Paper-63 (MCL 1.17)

Tabs (both free and premium)
https://www.spigotmc.org/resources/tab-1-5-x-1-17-free-version.57806/

**Comment by CloudeLecaw** [comment]
Its TABS job. When you use cmi tab and use vanish then use the command /cmi tabupdate (ifnyour tab update frequency is to low) and voila..your huden from tab.
So if it does not work with TAB plugin thia just means TAB needs tonadd Support

**Comment by Zrips** [comment]
@rockbyo5 
CMI vanish hides player in a generic way by using official bukkit API to do that. Additionally it adds some what "official" meda data to the player as "vanished" which could be used by any plugin to identify vanished plugin. 
On top of this, CMI isint controlling actual player visibility in tablist, this is done automatically by server, where again, this is where official API comes along. 
FYI Your links doesn't work, if i'm not mistaken plugin was taken down entirely.

**Comment by rockbyo5** [comment]
yea, after further testing, the vanished player is hidden in tab menu for other users but is not grayed out for the admins like they are in CMI's tab menu. So in other words everything works fine, that was my bad.
About the plugin, it seems to still be supported on the MC-Market, i dont know why its not on spigot anymore. I assume the author moved it to another platform.

Sorry for wasting your time.
