### ISSUE TITLE
flyspeed change still shown in console with -s

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5805]
https://github.com/Zrips/CMI/issues/5789

We use setting of flyspeed with -s on joiNEvent in EventCommands.yml
![Snag_1aa69db8](https://user-images.githubusercontent.com/12080017/124363748-5c06d700-dc3d-11eb-93dd-d6a0aa0d5ede.png)
like you can see the line flightspeed was changed is still shown in console

we noticed this was not fixed with latest CMI. The issues was descripted allready in #5789

![Snag_1aa5d056](https://user-images.githubusercontent.com/12080017/124363713-3c6fae80-dc3d-11eb-9e6b-909fbf9d934f.png)

**Comment by Zrips** [comment]
Will fix/update
