### ISSUE TITLE
[Minor] AFK Subtitles No Longer Show

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#5807]
**Description of issue:**
No errors, but as of the last couple updates, AFK Subtitles no longer show. The main "You are now AFK" is still good, but the subtitle itself is absent. No errors and not a big deal, just letting you know. 

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  afk:
    help:
      info: '&eToggle afk mode. A reason can be provided if desired.'
      args: (-p:playerName) (reason)
    info:
      # This only determines message in title message and not message shown in chat. For chat message check config.yml file
      afkTitle: '&eYou are now AFK'
      afkSubTitle:
      - '&2Don''t eat too many cookies!'
      - '&2Nice day for fishing.'
      - '&2AFK again!?'
      - '&2Where are you?'
      - '&2But not at a farm, right?'
      - '&2Your AFK farm isn''t that great.'
      - '&2Did you wash your hands?'
      - '&2I miss you. Come back.'
      - '&2Give the kids Benadryl already.'
      - '&2Get me a beer while you''re up?'
      - '&2Goddamn millennials.'
      - '&2Bladder aggro.'
      - '&2Timey wimey.'
```

---

**Cmi Version (using`/cmi version`):** 9.0.0.5, CMILib 1.0.2.6

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-Paper-777 (MC: 1.16.5)

**Comment by Sikatsu** [comment]
I can confirm this on tuinity 1.17 as well.

**Comment by Zrips** [comment]
Confirmed. Should be resolved with next update.
