### ISSUE TITLE
REQUEST: unlimit Money by command

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/CMI#581]
can you add unlimit money by command like /money set PlayerName unlimited

**Comment by CloudeLecaw** [comment]
why this should make sense?
If u wanne test something u can give yourself so much Money, that u feel like it never runs out....

if u plan to have a Group that does not need to pay - 
what About a permission to Bypass all types of Costs?
This permission u could give then to you, all your admins, or single Players or Special Special vips, or what ever..


So may think About, changing the request to a permission that Bypasses all Kinds of Costs.

**Comment by LogGits** [comment]
This is not a feature that we will be adding. As mentioned by @CloudeLecaw you can give yourself a large quantity of money using `/money give [playerName] [amount]`.
