### ISSUE TITLE
Tab complete not working after rejoin

### ISSUE THREAD

**Issue by recycie** [Zrips/CMI#5810]
**Description of issue:**

---

Tab Complate Not working after rejoin server with cmi
I try remove plugin cmi, Tab Complate it work.
![image](https://user-images.githubusercontent.com/46786536/124420116-16efbb80-dd89-11eb-8fda-46f8fa740e78.png)

Plugins
![image](https://user-images.githubusercontent.com/46786536/124420152-2969f500-dd89-11eb-8b20-f2afd66eda8d.png)

---

**Cmi Version (using`/cmi version`):** 
CMI: 9.0.0.5
CMILib: 1.0.2.6
Server: Purpur 1.17

**Server Type (Spigot/Paperspigot/etc):** 
Purple

**Server Version (using `/ver`):** 
Purpur-1215 1.17

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Its not working for every plugin? Every command or just specific ones? Have you tried to run only CMI and no other plugin just to rule out possible issue with another plugin interfering?

**Comment by recycie** [comment]
Not working for every command.

**Comment by recycie** [comment]
If install cmi only tab complate it work

**Comment by Zrips** [comment]
Then you have a cause, abstractmenus. If everything works as it should without it and brakes with it, then you will need to get in contact with that dev to fix this issue.
