### ISSUE TITLE
Extansion of smite command

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5811]
Currenty we can smite people or place we are looking at.

It would be nice to have the option to point a smite to some place

So an extansion of Y X Z world world be really nice

The command would be extrant to
`cmi smite (playerName) (x y z world) (-s)`

This would allow us to point the target of a smite that can be specialy good when using it in commandblocks

the minecraft command summon lightning bolt allready offers summon the lighning bolt at a position..

> summon lightning_bolt ~ ~ ~ 

this one just has no world argument...

or does strike work completly different?

well still would be great if it could be added somehow

**Comment by Zrips** [comment]
Okey
