### ISSUE TITLE
CMI worthlist bug

### ISSUE THREAD

**Issue by SkeletonAce** [Zrips/CMI#5817]
CMI worthlist is now completely randomised after updating to 9.0.0.6

**Cmi Version (9.0.0.6):** 

**Server Type (Purpur#1222):** 

**Server Version (1.17):**

**Comment by mrfloris** [comment]
Last night I've run the `cmi generateworth` command in console which is that new feature that lets you auto generate values based on raw materials. And just took a look at my worth.yml file. Which seems to be from a-z as before. It's not completely randomized for me. 

(just sharing my experience with the upgrade), the other server the file also looks as expected.

**Comment by Zrips** [comment]
Will make it more sorted with next version

**Comment by SkeletonAce** [comment]
> Last night I've run the `cmi generateworth` command in console which is that new feature that lets you auto generate values based on raw materials. And just took a look at my worth.yml file. Which seems to be from a-z as before. It's not completely randomized for me.
> 
> (just sharing my experience with the upgrade), the other server the file also looks as expected.

Yeah I'm not talking about the .yml file but the in game command /worthlist
