### ISSUE TITLE
Chat Being Duped

### ISSUE THREAD

**Issue by PretendBullet50** [Zrips/CMI#582]
Hey, I did have a case open for while no idea if it's still open! My OLD PC got a  virus, therefore, I was unable to do anything! Got a NEW PC and got things running again! Anyway, I was told to install the version of VAULT of the SPIGOT Page and I did that! However, the chat is still being duped!

Current Set Up
- Proxy 
+ No CMI

- Survival 
+ No CMI

- Hub 
+ CMI Version 7.8.10.0 
+ With Vault 1.6.10(+)
+ Server Version Spigot 1.10.2-R0.1-SNAPSHOT
![image](https://user-images.githubusercontent.com/29534385/42417899-a56c5b14-8249-11e8-9ee2-d1df16d8b4cf.png)

- Project 
+ CMI Version 7.8.0.0 
+ With Vault 1.6.10(+)
+Server Version Spigot 1.12.2-R0.1-SNAPSHOT
![image](https://user-images.githubusercontent.com/29534385/42417897-9b5da254-8249-11e8-9b87-bcaae2c5cf27.png)

I do Not have My SQL set up with CMI
However, they are all ran on 1 single CentOS 7 Server separated via Docker!

Now I cant UPDATE the Project Server because anytime I do it crashes within a user joining of 5 sec! IDK how to fix this! I have even made an entirely new server! Now anytime a user chats in Project there is no chat dupe! but when a user chat is Project its DUPES twice in HUB! This only happens when a user chats in the project regardless of their rank! IDK how to fix this! Please help me! I have provided pictures below!

PICS
When a user CHATS in HUB

Hub Chat
![image](https://user-images.githubusercontent.com/29534385/42417949-54e48bde-824a-11e8-8128-a029143608de.png)

Project Chat
![image](https://user-images.githubusercontent.com/29534385/42417952-630e7210-824a-11e8-8d47-bb693ec39414.png)

When a user chats in Project

Project chat
![image](https://user-images.githubusercontent.com/29534385/42417957-882fac44-824a-11e8-8d2a-28f40660a3db.png)

Hub Chat
![image](https://user-images.githubusercontent.com/29534385/42417959-925e45a4-824a-11e8-86f5-b02e21f7ef77.png)

**Comment by LogGits** [comment]
Do you still experience this issue?
