### ISSUE TITLE
The world needs Pictutes or images :D

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5829]
What i am missing in cmi is a Picture management

Mostly these are done by placing frames then create a picute with the name of the file and the size if its streched.
Also it should have the option to make the frames invisiable if a picture is placed

command could be
command: **cmi placepic [PICTURENAME.FORMAT|URLofPicture] (lenght in Frames) (width in Frames) (-invisible)**
then the left buttom frame should be clicked. and done.
invisible option should make the item frames invisiable
permission: **cmi.command.placepic**
Frames can be placed in all directions. so this should be possible with the pictures to.
When the Picutre is taken from the Internet with the URL then it should be saved in the Subfolder.

The pictures  might be saved in a Subfolder in CMI itself   CMI\Images
might vailed formates .... hmm png, pjg, gif ?

So lets start the dekoration of our servers pic Pictues :D

![image](https://user-images.githubusercontent.com/12080017/124965435-6d2b5b80-e022-11eb-916c-bd314b383ccb.png)

**Comment by strahil211** [comment]
Use ImageMaps or ImageOnMap plugin for this. It would be nice if CMI had it built in though!

**Comment by CloudeLecaw** [comment]
I know we are using CustomImages for it. But it would be much better to have this onboard with CMI also on most updated mc we have to wait about 3-4 weeks sometime before we can update because the image devs take their time.
CMI is mostly very vey fast with its updates. So having this onboard would also mean to be abe to get away from the other plugins.
Well its might me a dekoration part but may it will be added on time.

**Comment by strahil211** [comment]
I suggest just using a different images plugin, the one I use did not need a 1.17 update because it never broke like that!
