### ISSUE TITLE
Server freezes due to the CMI plugin

### ISSUE THREAD

**Issue by yraliya** [Zrips/CMI#5830]
Server freezes

---

The server stopped responding, restarting the server did not help.
The problem was solved after removing the CMI plugin
```

Everything is frozen in this log
https://pastebin.com/qnJ1KWGw

Here I tried to restart the server, after restarting the server did not start completely, did not let anyone in
https://pastebin.com/ussYKFVf

Here I removed the CMI plugin
https://pastebin.com/baAq4B9c

```

---

**Cmi Version (CMI9.0.0.8`):** 

**Server Type (paper1.12.2):** 

**Server Version (paper1.12.2`):** 

java 16

**Comment by Zrips** [comment]
Resolved
