### ISSUE TITLE
Disabling Alias doesn't work

### ISSUE THREAD

**Issue by Flashera** [Zrips/CMI#5833]
**Description of issue:**

I have attempted to disable the /pay alias, but the server still uses it.

---

**Cmi Version (using`/cmi version`):** 9.0.0.9  

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.16.5

**Comment by Zrips** [comment]
Disabling default alias from alias.yml file will require full server restart for it to take correct effect. After restart it should be properly disabled and CMI will not do anything with that command.
