### ISSUE TITLE
Tabcompletation sometimes show nick, some command playername, some both...

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5835]
![Snag_16488c4](https://user-images.githubusercontent.com/12080017/125122270-79341d80-e0f5-11eb-80d2-71ccba66cffa.png)

We noticed sometime we have invailed (also not existing) names in player suggestisons

Here on /money pay
You see a name J3lachcheese ..... this player does not exist..
![Snag_1adb02e](https://user-images.githubusercontent.com/12080017/125130064-a2a67680-e100-11eb-8437-02ff182979a2.png)

in this case it was like seen in the screenshot
the name of a player called Sir_Blackcheese  we think the other name was also suggested because of him

Well now we see what is was...
the player was nicked to Sir_Blackchese and changes his name to J3lackcheese

some tabcomplets command shows his realname, some his nicknamem... some both...... stange..

**Comment by Zrips** [comment]
This can include ether player name, original one, and players nickname if that one is set to be included. It cant really create none existing player names.

**Comment by CloudeLecaw** [comment]
It was his nickname + his playerName .
..
