### ISSUE TITLE
Random Teleportation does not work on extended worldheights ("1.18" datapack)

### ISSUE THREAD

**Issue by Idolized123** [Zrips/CMI#5836]
When using the Caves & Cliffs datapack from Mojang, random teleporation does not seem to be working with CMI. 

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[21:57:27 INFO]: Could not find correct teleport location, please wait 25 sec  and try again.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
world:
      Enabled: true
      MaxRange: 15000
      MinRange: 500
      CenterX: -145
      CenterZ: 137
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: -64
      maxY: 256
      
      ** Also tried with minY set to -64.
---

**Cmi Version (using`/cmi version`):** 
CMI: 9.0.0.9
CMILib: 1.0.2.10

**Server Type (Spigot/Paperspigot/etc):** 
Tuinity 1.17.1-R0.1-SNAPSHOT
**Server Version (using `/ver`):** 
 Tuinity version git-Tuinity-18 (MC: 1.17.1)

**Comment by Zrips** [comment]
Will include some changes relating to negative Y value. Tho data pack and increased world height isint really a thing we are supporting currently as its not official release of it and it will most likely brake sooner or later. 
Full support with increased world height will come out with 1.18 release, but we can start updating parts of code before hand.
