### ISSUE TITLE
FLY STILL DISABLING ON WORLD SWITCH, CAUSING PLAYERS TO FALL TO DEATH

### ISSUE THREAD

**Issue by Skizzles** [Zrips/CMI#5842]
Description of issue:
It worked for a long time but in a recent update it must've changed.

Using this config below, when a player was flying in the overworld and would teleport to any of the above worlds, fly would disable. When they would go back to the overworld, fly would still be enabled without having to use commands. However, now the player has to do twice /fly in order to be able to fly again in the overworld when coming from one of these 3 worlds.

CONFIG SECTION (DELETE IF NOT RELEVANT):

WorldLimits:
  Enabled: true
  Gamemode:
  - world2:Survival
  Fly:
  - world_nether:False
  - world_the_end:False
  - nogard:False
Cmi Version (using/cmi version): CMI: 9.0.0.5

Server Type (Spigot/Paperspigot/etc): Tuinity

Server Version (using /ver): Tuinity version git-Tuinity-7 (MC: 1.17)

**Comment by Skizzles** [comment]
#5808 is a duplicate but I wanted this to be seen as its causing players to fall to their death.

**Comment by strahil211** [comment]
I've tried a few versions of cmi and with worldlimits disabled/enabled and config on true/false and permissions with bypass and quite literally anything i can think of I have tried and can't get it to keep /fly enabled on world change so I think it's safe to say its a plugin bug.

Personally I don't use worldlimits and keep it disabled so its frustrating to see it still affecting fly

**Comment by Zrips** [comment]
It looks to be minecraft server itself disabling fly mode while changing worlds on 1.17 servers. Investigating.

**Comment by Zrips** [comment]
Should be working properly with next version.
