### ISSUE TITLE
Spawning the dragon does not add the dragon bossbar

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#5846]
**Description of issue:**
When spawning a dragon with /cmi spawnmob the dragon boss bar does not get shown for the dragon in the end.

**Cmi Version (using`/cmi version`):** 8.8.4.7 CMI Lib 1.0.0.2

**Server Type (Spigot/Paperspigot/etc):** Paper 1.12.2

**Server Version (using `/ver`):** 1.12.2 -1618

**Comment by Zrips** [comment]
Its issue with how ende dragon is handled in general. When you summon ender dragon with command then no bossbar gets shown. Its known issue with minecraft itself.
