### ISSUE TITLE
getActionBarManager unknown

### ISSUE THREAD

**Issue by Rocologo** [Zrips/CMI#5851]
Hi Zrips 

I have been offline for almost a year but have decided to update my plugin Mobhunting to MC 1.17 and update to latest versions og the plugins I hook into.

Im trying update from CMI 8.6.x.x to CMI 9.0.1.0, but I get compilation errors.

This is my code:
```
	public static void sendActionBarMessage(Player player, String text) {
		getCMIPlugin().getActionBarManager().send(player, text);
	}
	
	public static void sendBossBarMessage(Player player, String text) {
		CMIUser user = getCMIPlugin().getPlayerManager().getUser(player);
	    BossBarInfo bossBar = new BossBarInfo(user, "...");
	    bossBar.setSeconds(10);
	    bossBar.setTitleOfBar(text);
	    bossBar.setKeepForTicks(0);
	    user.addBossBar(bossBar);		
	}
```
but getActionBarManager and BossBarInfo is unknown? I guess you have changed something?

**Comment by Zrips** [comment]
As it was mentioned all over the place, as of 9.x version we split CMI into CMI and CMILib and quite few base things got moved over there. You will need to use CMILib instead of CMI as a base from now on. Its more centralized system

**Comment by Rocologo** [comment]
Thanks. 

I have added CMILib to MobHuting and I have found your getHologramManager() and getBossBarManager(), but I cant find getActionBarManager??? 

There is no "CMILib.getInstance().getActionBarManager()"?
