### ISSUE TITLE
[Bug] Purge one uid of same player name will purge another's inventory data

### ISSUE THREAD

**Issue by momoservertw** [Zrips/CMI#587]
**Description of issue or feature request:**
Command /cmi removeuser <uid> 
Purge one uid of same player name will purge another's inventory and ender chest.
For example.
Player name: robert881125
uid1: 8469a74b-81c7-38fe-9222-0fe934bab903  last seen: 6 days 4 hours 29 min 33 sec ago
uid2: 9e4c33b1-304b-34b1-8705-abd53dd0f5a5 last seen: 48 years 201 days 4 hours 29 min 33 sec ago
Besides, they have same inventory data before purged.
###############################
CMI Version: 7.8.10.0
Server Type: Spigot
Server Version: CraftBukkit version git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by CloudeLecaw** [comment]
one Question? your running a Server in offline mode?

i renember simmliar effect with the following Scenario:

I was running a Server for a test in offline mode:
 -> i logged in with my name

then i was running the Server aggain in online mode
-> i logged in with my account

what happend: both ways created different uuids.
So when i would serch for the name now i found find the two UUIDs with identical inventary
