### ISSUE TITLE
cant view Inventory/enderchest of many offline players + some join with empty enderchest+inventory in 9.0.1.1

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5870]
![Snag_2a431d5](https://user-images.githubusercontent.com/12080017/125515346-37fefb3e-a9ed-4b8a-98c2-9d1a1869a32d.png)

When a player is offline we cant view their inventories

This issue has been accoured since CMI Update 9.0.1.1

Player is online
![Snag_2a60492](https://user-images.githubusercontent.com/12080017/125515608-047b4cb4-0202-410f-9ce1-308b04eb12a4.png)

Player went offline
![Snag_2a6d129](https://user-images.githubusercontent.com/12080017/125515727-5f7032e2-6bde-40ad-b124-3dd464b1b1df.png)

We are using mysql as file database

**Comment by CloudeLecaw** [comment]
Edit: Some players also joined now with an empty invenoty after joining the first time since we changed to 1.17.1 with CMI 9.0.1.1

**Comment by CloudeLecaw** [comment]
Edit 2: In addition to this we cant view players enderchests no matter if they are online or not
we allways get empty enderchests shown

**Comment by Zrips** [comment]
Posted new version with a hot fix
