### ISSUE TITLE
Language text is missing

### ISSUE THREAD

**Issue by SheerYin** [Zrips/CMI#5872]
A lot of information cannot be found in the language text of the plugin folder
But you can find it through the EN language of github
Enter the plugin folder by copying the EN language of github, but the extra text is deleted after cmi reload 

CMI: 9.0.1.2 BungeeCord  SqLite-> 9.0.1.1
CMILib: 1.0.2.12 
 Server: Purpur 1.17.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 53 enabled 3 disabled: tablist, ranks, votifier
Checking version, please wait...
This server is running Purpur version git-Purpur-1265 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2824f64 on HEAD)
You are 2 version(s) behind
Previous version: git-Paper-103 (MC: 1.17.1)

**Comment by CloudeLecaw** [comment]
Tale a look into cmilib/Translation..
Many prases moved therr
