### ISSUE TITLE
[Request] permission to bypass on purging playerdata 

### ISSUE THREAD

**Issue by momoservertw** [Zrips/CMI#588]
**Description of issue or feature request:**
Can you add a permission to bypass on purging playerdata?
For example:
1. cmi.purge.bypass.playerdata - Allows to bypass on purging player data 
2.  cmi.purge.bypass.essentials - Allows to bypass on purging essentials data 

Thank you :)

**Comment by CloudeLecaw** [comment]
why CMI should dedice what essentials datas has to be purged or not? this is the Job of essentials itself not of CMI. Does a permission seems to be the Right way?
not purge when Player X is in a Special Group? so "anti purge permission"? Therefor we Need a hook aggain with the permission System.

For myself.. 
i use a private developed permissionsystem and Solutions like this "not purge on Startup by permisison" never will work for me, becaue i dont think CMI will lnever support my perm System ;)
(Why Zrips should develop a compatibility if just 2 People (me and the dev of it) use it?
so i would more like to see a list for  Antipurgedata where i can enter UUIDs or names, Also a command for adding/removing from the list. this would make it simple for owners with ranks
giving the rank - execute command to add Player to the list, removing the rank or other, removes Player from list - a realy simple to do Thing for most i think :-)

**Comment by momoservertw** [comment]
I would ask author to support it, because CMI already has a purge system, but no bypass way.
In CMI Config, it can purge playerdata, PlayerStats, Essentials...etc.
Maybe adding the features will make this plugin better. Don't you think so?

**Comment by LogGits** [comment]
I haven't read this whole thing yet but @CloudeLecaw as long as your plugin supports vaults permission system, CMI can hook into it to read permissions (Granted you are using CMI's vault build).

**Comment by CloudeLecaw** [comment]
i dont use vault

**Comment by SmallSansSerif** [comment]
Please add permission to bypass offline purge. Would like to allow purge but have paid ranks be able to avoid getting purged.
