### ISSUE TITLE
Meta increment does not work

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5882]
To Reproduce:
cmi usermeta [playerName] add TestMetaValue 1
cmi usermeta [playerName] increment TestMetaValue 1

you will see the output in console will be

[00:04:48 INFO]: Useage: /cmi usermeta [playerName] [add/remove/clear/list/increment] (key) (value) (-s)
is it increase the value.... it it increase and increment is just a spell error?

![Snag_315f261](https://user-images.githubusercontent.com/12080017/125864131-68d4f86c-9d53-4a1e-8eba-8da4552267e7.png)

i know i can currently simply add a value as it replaces the old one..  but would be nice if incremnt would work aggain too

**Comment by kassadGLA** [comment]
I think you must `+1`:
```
cmi usermeta [playerName] increment TestMetaValue +1
```

**Comment by CloudeLecaw** [comment]
ohh i see so + and - must be used :3Thank you<3
