### ISSUE TITLE
I cant find getActionBarManager ?

### ISSUE THREAD

**Issue by Rocologo** [Zrips/CMI#5885]
I have added CMILib to MobHuting and I have found your getHologramManager() and getBossBarManager(), but I cant find getActionBarManager???

There is no "CMILib.getInstance().getActionBarManager()"?

**Comment by Zrips** [comment]
Holograms remains in CMI, no changes there, BossBar messages got moved into CMILib and can be accessed with basic CMILib.getInstance().getBossBarManager() so its same path as previously, difference is origin and slight usage of it, action bar can be accessed with direct CMIActionBar.send(player, message) method from CMILib

**Comment by Rocologo** [comment]
Thanks. That helped.
