### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ArabianPandaMC** [Zrips/CMI#5889]
**Description of issue or feature request:**
Basically a "/sell [itemname]", instead of sell hand or sell all or sell blocks, add an command that sells specified item that when ran it will sell all that item from your inventory, hope it gets added.

**Comment by ArabianPandaMC** [comment]
Oh one more thing would be nice if it also included the amount (optional) like could be /sellall (itemname) or /sell (itemname) (amount)

**Comment by Zrips** [comment]
Will add option to define material you want to sell
