### ISSUE TITLE
[Bug] permision "cmi.command.ride.[entitytype]" is not working

### ISSUE THREAD

**Issue by momoservertw** [Zrips/CMI#589]
**Description of issue or feature request:**
Permission "cmi.command.ride" is not working
I set player permission to "cmi.command.ride" and "cmi.command.ride.sheep".
They still can't ride on a sheep.

1. only has permission "cmi.command.ride"
Displays "You cant ride (sheep) entity".
2. only has permission "cmi.command.ride.sheep"
Displays "no permission".
3. Has both permission "cmi.command.ride" and "cmi.command.ride.sheep"
Displays "Ride target entity".

###############################
CMI Version: 7.8.10.0
Server Type: Spigot
Server Version: CraftBukkit version git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by CloudeLecaw** [comment]
i know it sounds stranghe but do your Players have the permission **cmi.command** ?

**Comment by momoservertw** [comment]
Oh, Thank you :)
It works by looking at the entities feet.
Strangely, OP status can more easy to ride on an entity. 
For example, this picture OP can ride on it, but player can not.
![image](https://user-images.githubusercontent.com/38014059/42452415-81b9e44c-83bc-11e8-9cbc-68ae1119268c.png)
--
Still has a problem...
NoCheatPlus will kick player after using ride command.
I tried plugin Spartan AntiCheat, and it has not problem.
So sad... 
Because of Spartan always cause my server(i7-8700k) lag and misjudgment players, I would not preference using it. :(

[NoCheatPlus] *Player failed SurvivalFly: tried to move: 960.26, 69.00, 1015.30 -> 960.31, 70.00, 1012.50, d=2.98 (permchecks+hspeed+vdistrel). VL 641.
#################################
#### Server ####
git-Spigot-642f6d2-fbe3046 ~MC: 1.12.2~
detected: 1.12.2
 #### NoCheatPlus ####
Plugin: 3.16.1-SNAPSHOT-sMD5NET-b1147
MCAccess: 1.12-1.12.2 / Spigot-CB-1.12_R1
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12
checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
defaults: pvpKnockBackVelocity
packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
Hooks: Citizens2~cncp~ 2.0 | MyPet 1.0
#### Related Plugins ####
CompatNoCheatPlus v6.6.5-RC-sMD5NET-b90 | ProtocolLib v4.4.0-SNAPSHOT-b399

**Comment by CloudeLecaw** [comment]
sorry i have no idea About NPC, Maybe Zrips can help here :3

**Comment by LogGits** [comment]
Has this been resolved? Also the look at feet issue is related to minecraft's entity hitboxes. As you can see in this image:
https://gyazo.com/5a0da935aa03847b57c560463bad7aeb
typing `/cmi ride` on a sheeps head causes "Look at entity"

**Comment by momoservertw** [comment]
The problem has fix in new version.
Please close it :)

**Comment by CloudeLecaw** [comment]
ist your thread.. you should press the closebutton...

**Comment by momoservertw** [comment]
haha, I am not familiar with Github. 
Thank you.
