### ISSUE TITLE
head command doesn't name heads properly

### ISSUE THREAD

**Issue by Olexorus** [Zrips/CMI#5894]
**Description of issue:**
When using `/cmi head` the head isn't named after its owner, instead it's just called "Player Head", whereas if I generate it via `/give Olexorus minecraft:player_head{SkullOwner:"Olexorus"}` it's called "Olexorus's Head".

**Cmi Version (using`/cmi version`):**  CMI: 9.0.1.2, CMILib: 1.0.2.13

**Server Type (Spigot/Paperspigot/etc):**  Tuinity

**Server Version (using `/ver`):** git-Tuinity-21 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bdd7bb4 on HEAD)

**Comment by CloudeLecaw** [comment]
```
Cmi head [sourceName] (targetName) (-s) (amount)
Get players head
```

**Comment by Zrips** [comment]
Will be fixed with next CMILib update
