### ISSUE TITLE
Support for MineableSpawners

### ISSUE THREAD

**Issue by rmalca** [Zrips/CMI#5896]
Hi, I use the MineableSpawners plugin to put restrictions so that only certain players can mine spawners. MineableSpawners have more configuration options than CMI, for example being able to choose that players can only mine a spawner with a netherite pickaxe and that if they cannot mine it, the spawner will not break.

I have activated the CMI Charges option but what happens is that if MineableSpawners prevents the spawner from being mined then CMI still counts as a spent charge, is there any way that it will stop counting the charge if MineableSpawners does not allow the spawner to be mined?

**Comment by CloudeLecaw** [comment]
you know u can do that with cmi too?
Decide wh can mine spawners and who not?

**Comment by rmalca** [comment]
> you know u can do that with cmi too?
> Decide wh can mine spawners and who not?

Yes, but as I say with CMI I can't choose to only mine spawners with a netherite pickaxe. Furthermore, CMI destroys the spawner if the requirements are not met.

**Comment by CloudeLecaw** [comment]
but you need to decide
You cant have just the good peaced of each.
So no charges and your plugin or cmi

**Comment by rmalca** [comment]
> but you need to decide
> You cant have just the good peaced of each.
> So no charges and your plugin or cmi spawners

I can not? I don't think anyone should tell me what I can and cannot do.
