### ISSUE TITLE
Offhand flag for commands such as /cmi enchant

### ISSUE THREAD

**Issue by Seeroh** [Zrips/CMI#59]
Could there be a addition to commands like /cmi enchant, that with something like -o, will use the command on a player's off hand?

So for instance, I could do **/cmi enchant -o zrips efficiency 10**, and it'll try and enchant the item in zrips offhand?

Because at the moment, there is no way for me to enchant an item in a player's offhand.

**Comment by Zrips** [comment]
Next update
