### ISSUE TITLE
Fly turns on automatically

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#5900]
**Description of issue:**

After updating CMI all staff with fly permission gets their fly enabled by itself after teleportation and death.

Most likely related to the fly fix on 1.17.1

---
**Cmi Version (using`/cmi version`):** 
CMI 9.0.1.2 CMILib: 1.0.2.13
**Server Type (Spigot/Paperspigot/etc):** 
Purpur
**Server Version (using `/ver`):** 
git-Purpur-1280 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Some adjustments will be done with next version, if issue persists let me know.
