### ISSUE TITLE
Have Dragon Egg Respawn

### ISSUE THREAD

**Issue by FoxWithSox** [Zrips/CMI#5902]
A config option to be able to respawn the dragon egg again

**Comment by CloudeLecaw** [comment]
what you mean exactly? i can simply spawn you a dragonegg and with new servers you also can simply respawn the dragon as often as you want with 3 endcrstals.
What you wanne do? let your players farm xxxx dragoneggs?
Or simply a command that let a new egg drops if the next spawned enderdragon is killed? :3

**Comment by FoxWithSox** [comment]
Yes sorry for not specifying, I mean something to let a new egg drop each time the dragon is killed.

**Comment by CloudeLecaw** [comment]
Hm DropEdit2.. define a chance of 100% for a dragonegg in it ;)
Then kill the first Dragon by youself because the First would drop the vanilla egg + the additional one.

Its a good plugin and may a faster solution because i dont think zrips wanne add aditional drops for now.
