### ISSUE TITLE
[Feature Request] [Bug Report] Removehome command typo and feature request

### ISSUE THREAD

**Issue by ChiboYen** [Zrips/CMI#5904]
**Description of issue:**

When doing /cmi removehome <home> <playername> the "playername" tab complete has a typo in it
---
![Image](https://i.chibo.rocks/K922AECSf7.png)

Feature request
---
While you fix the bug, I want you to add the feature of `/cmi removehome all <playername>` so the console can wipe all a player's homes. Thanks!

**Cmi Version (using`/cmi version`):** 9.0.1.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.17.1 Build 112

**Comment by CloudeLecaw** [comment]
If you have the right its not really a bug that names of online players pop out.

Command Syntax is

>cmi removehome (homeName) (playerName)

**Comment by CloudeLecaw** [comment]
Great Catch :D

**Comment by Zrips** [comment]
Will fix it with next build.
