### ISSUE TITLE
command addition argument x% of total XP

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5906]
[The reason why i got this idea was an other ticket where a user asked for a feature to take x% money on death](https://github.com/Zrips/CMI/issues/5905)
(what allready can be done with cmi)

So i renembered on Hack&Slays and other RPGs, where you just reduce your XP by x% of your total (in some of current lvl, but hey this is minecraft!)  So i thought - hey why this simply cant bee added to cmi?

i tool a look on current command snytax of the XP command..

> exp [playerName] [add/set/take/clear] [amount][%rand/10-20%] (-s)

Take/give amount between min and max...
we can set/take directly
but we cant set/take x% of total..

So this is a little nice missing addition in my eyes...

What is the plan i would like to create:
- give players permission: keepxp so their XP stay
- define Evencommand on Death that take x% of their current total XP

currently its not possible because we cant
a nice sice effect: with x% we could define different amout for each world that would if wanted.

so a x% like we can do it with Moeny would be great!

How the command might could look after:
`exp [playerName] [add/set/take/clear] [amount|percentage%][%rand/10-20%] (-s)`

example:
for taking 10% of someones exp it would be
`exp [playerName] take 10% (-s)`

I hope you find a way toadd this little expansion of the xp command :-)

**Comment by Zrips** [comment]
Okey
