### ISSUE TITLE
Leave message question

### ISSUE THREAD

**Issue by MasonKidder345** [Zrips/CMI#5908]
Hello, I was just wondering if there is a way to stop showing the leave message? I turned it off in cmi's config to stop showing the join message but I can't seem to find that option for the leave message. Is it possible to disable it with cmi?

**Comment by CloudeLecaw** [comment]
You wanne stop it for you? Or for all?
For all then you can disable it in config to not show custom. If u want it just for you or a group then you can use the permission for it.

**Comment by MasonKidder345** [comment]
Okayy! I got it thank you so much for the help I appreciate it!
