### ISSUE TITLE
Home teleport does not work when cooldown is set

### ISSUE THREAD

**Issue by rmalca** [Zrips/CMI#5909]
**Description of issue:**
When a player only has one home set and there is a cooldown set "cmi home:10", waiting for the cooldown does not teleport the player. 

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Cooldowns:
  Enabled: true
  List:
  - cmi home:10
```

---

**Cmi Version (using`/cmi version`):**
```
Versión de CMI: 9.0.1.3 BungeeCord CMIB
Base de Datos: MySQL
Versión de CMILib: 1.0.2.14
Versión del Servidor: Tuinity 1.17.1-R0.1-SNAPSHOT
Economía de CMI: Habilitado | Vault: 1.7.3-b | Chat de CMI: Habilitado
Módulos: 34 activados y 22 desactivados (spawnerProximity, hpBossBar, customMessages, tablist, afk, skin, anvilRenameColor, spawners, cmiPlaytime, kits, flightCharge, deathMessages, disabledEnchants, worldLimitsElytra, ranks, firstJoinMessages, playerCombat, votifier, shulkerBackpack, headDrop, timedCommands, totemBehavior)
Archivo de Idioma: v21.07.09
Traducido por: C4BR3R4 (c4br3r4.es)
```

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):**
```
This server is running Tuinity version git-Tuinity-23 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: ce43ccd on HEAD)
```

https://user-images.githubusercontent.com/3759745/126215341-081eeaf4-f519-4590-9935-fbca2e3a0310.mp4

**Comment by Zrips** [comment]
There was a commented line just above cooldown list like
`  # ATTENTION! If you have command like "/cmi home" and you want to prevent teleportation to home but allow gui opening without restrictions, use space after command, in example "cmi home :10"`
your issue can be resolved by adding space before :
