### ISSUE TITLE
[Request] '/help' alias for '/cmi help'

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#591]
`/help` should be a default alias for `/cmi help` in `Alias.yml`

**Comment by CloudeLecaw** [comment]
no good idea pls design your customalias if u need this. but /help should be allowed to design by owner and not just list the cmi helps
many many servers /have different /helps that exaplains user commands and nothing from /cmi

**Comment by tmellen** [comment]
aliaseditor. help. cmi help

Personally, I have a menu book that pops up when someone types help. I don't want this overwritten!

**Comment by LogGits** [comment]
It wouldn't hurt to add this, It can be defaulted to `false`. This doesn't mean a server is forced to use the alias.

As @tmellen mentioned, this can be created using our build in aliaseditor using `/cmi aliaseditor new help-cmi help`

**Comment by TheWranger** [comment]
I am aware this can be done through the custom aliaseditor, I was merely suggesting that it should be added as one of the default toggleable aliases.

**Comment by CloudeLecaw** [comment]
we created a whole help with custom alias +  ctexts
