### ISSUE TITLE
CMILoadedEvent ?

### ISSUE THREAD

**Issue by Rocologo** [Zrips/CMI#5910]
Im having som problems cmi CMI holograms because CMI is loaded after MobHunting, and MobHunting cant use CMIHolograms until CMI is fully loaded.

Do you have an event that I can listen on? So I know when CMI is ready ?

/Rocologo

**Comment by CloudeLecaw** [comment]
Why dont add CMI to softdependencies in plugin.yml?

**Comment by Zrips** [comment]
@Rocologo 
You could simply add CMI as softdepend which would resolve your issue in correct way. Other than this, you can simply use
`CMI.getInstance().isFullyLoaded()` which will return True when its fully loaded.

**Comment by Rocologo** [comment]
I have added CMI and CMILib as softdepences on my laptop, where I do the testing, but this has not solved the problem.

**Comment by Rocologo** [comment]
Using CMI.getInstance().isFullyLoaded() would work but this is not a nice solution, because I would have to make a wait loop, which will slow down enabling MobHunting.

**Comment by Rocologo** [comment]
Antway - i will make wait loop and test CMI.getInstance().isFullyLoaded()
