### ISSUE TITLE
Placeholder %cmi_user_weatherduration% is showing... not understandable data

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5911]
So what this place holder shows?
![Snag_8b6e909](https://user-images.githubusercontent.com/12080017/126231610-b458aa78-b210-4633-8ea7-45287e4b42fc.png)

What kind of time is this?
when i set the weather without amount default is 1 hour but the placeholder shows 0sec

the other time it showed near 2 hours but 10 mins pasted tooo fast..

so what time is showing herE?
remaining minecraft time? (so i can watch at the minecraft clock to see when rain is over?)
and why it shows 0 in secounds case?
command used: /weather sun

![Snag_8b97b7c](https://user-images.githubusercontent.com/12080017/126231846-2be159aa-61d4-4419-927b-c6313ab89632.png)

**Comment by Zrips** [comment]
Small bug, will issue a fix for it
