### ISSUE TITLE
How to load player's warn count or totalplaytime by using OfflinePlayer obj?

### ISSUE THREAD

**Issue by RookieAND** [Zrips/CMI#5913]
I try to make profile system so I try to get some data from CMI either.
But when I get instance of CMIUser class by using OfflinePlayer. CMIUser#getTotalPlayTime() & CMIUser#getWarningPoints() returns 0.
But PAPI's placeholder result is working fine for me. How can I get these data? Can you show some example to using API?

**Comment by Zrips** [comment]
Player data is preloaded so that should still return correct values. You need to make sure that its a correct player object you are getting back by provided offline player. 
Basic example 
```
	CMIUser user = CMIUser .getUser(offlinePlayer);
	int points = user.getWarningPoints();
```
You most likely initialized new CMIUser object instead of getting old record of it with correct method.
