### ISSUE TITLE
Discord event

### ISSUE THREAD

**Issue by NightLife-SG** [Zrips/CMI#5920]
Make a option for discordsrv

When ever a player get banned,tempban,kick,mute,cuff all this kind of action

Get record into discord automatically with embed meassage whenever those action is being triggered with reason

:)

**Comment by Ultrasonic1209** [comment]
feel like it would be a better idea to simply add eventCommands for kicks, bans, mutes, etc and let the server admin bind `discord broadcast` to them

**Comment by CloudeLecaw** [comment]
You can do this allready
