### ISSUE TITLE
CMI publicmessage with DiscordSRV

### ISSUE THREAD

**Issue by TreeHD** [Zrips/CMI#5923]
**Description of issue:**

Hello
I'm using public message function to sync every server's chat

Is it possible to  hook every server chat with DiscordSRV?

I install DiscordSRV in A server
Player in A server chat could sync with Discord , but in B server couldn't sync with Discord,but could see in A server chatroom 

---

**Cmi Version (using`/cmi version`): 9.0.1.2** 

**Server Type (Spigot/Paperspigot/etc):PaperSpigot** 

**Server Version (using `/ver`):git-Paper-116 (MC: 1.17.1)** 

**Relevant plugins (Delete if this isn't needed):DiscordSRV**

**Comment by Zrips** [comment]
Jut make sure that you have discordsrv on both servers with same chat setups, then set CMI to use same channels for public messages and enable bungee public messages which should in general show message on all servers if messages comes from discord while show to all servers and discord if you sent it from ingame.
