### ISSUE TITLE
Voting with nick

### ISSUE THREAD

**Issue by Jaycidel** [Zrips/CMI#5926]
**Description of issue:**
There seems to be an issue with voting where if the user is nicked they can vote with an alternative IP with the nicked name, it will still go through and execute commandsonvote in the config

---

**Cmi Version (using`/cmi version`):** 
9.0.1.2

**Server Type (Spigot/Paperspigot/etc):** 
Tuinity

**Server Version (using `/ver`):** 
1.17.1

**Relevant plugins (Delete if this isn't needed):**
nuvotifier

**Comment by Zrips** [comment]
Will fix
