### ISSUE TITLE
/cmi baltop shows player coords!?

### ISSUE THREAD

**Issue by DarkCynicism** [Zrips/CMI#5928]
Any player using /cmi baltop can apparently see all manner of completely irrelevant and potentially dangerous information.

**Cmi Version (9.0.1.3
![baltop](https://user-images.githubusercontent.com/14790507/126806248-17806463-efd6-4ede-ba33-4b9a03fc6dde.png)
):** 

**Server Type (Paperspigot):** 

**Server Version (Purpur-1291 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0dad40a on ver/1.17.1):**

**Comment by CloudeLecaw** [comment]
have you tested this as player (without OP and in Playerrank) too

I think there u will have no hovers like that

**Comment by DarkCynicism** [comment]
Yes, it was a player who pointed it out. He IS ranked but it's mostly flavour and has no special perms which should reveal such info. I will test it with a completely vanilla player

**Comment by DarkCynicism** [comment]
![baltop 2](https://user-images.githubusercontent.com/14790507/126845751-3bbb4cc4-1f1f-42a4-a02c-ef7321e837c5.png)
![baltop 3](https://user-images.githubusercontent.com/14790507/126845754-24abcf5f-a4f4-43ca-86fb-19aefaeb4475.png)
This is what an almost completely vanilla player sees. And the perms she has, none of which have relation to the matter.

**Comment by strahil211** [comment]
I have never been able to get it to show this when I hover over baltop... I think another plugin is doing this to you not CMI

**Comment by DarkCynicism** [comment]
I did suspect it was another plugin as it seemed insane that it was a feature of the /baltop command.
Luckily today is Saturday...
Apologies for the erroneous report
