### ISSUE TITLE
Elevators doesn't work above 256 block

### ISSUE THREAD

**Issue by krfcm** [Zrips/CMI#5932]
Elevators doesn't work above 256 block - You can go down but can't back to upstairs.

**Cmi Version (using`/cmi version`):** 
9.0.2.0
**Server Type (Spigot/Paperspigot/etc):** 
Airplanepurpur
**Server Version (using `/ver`):** 
https://prnt.sc/1f9jkyw

**Comment by CloudeLecaw** [comment]
Maybe because cmi is normaly made to stop ar 256? You should wait for 1.18 and its compatible cmi version before reporting issues with y Higher then 256

**Comment by Zrips** [comment]
Increased world height isint officially supported until 1.18 is out. But while we are on this topic, will update code to be more suitable for this now.
