### ISSUE TITLE
Requesting Jail Event API

### ISSUE THREAD

**Issue by NightLife-SG** [Zrips/CMI#5934]
can i request for jail API?

**Comment by Zrips** [comment]
Will add CMIPlayerUnjailEvent and CMIPlayerJailEvent

**Comment by NightLife-SG** [comment]
i dont see the event in ur event file,can you update it?

**Comment by Zrips** [comment]
CMIPlayerJailEvent - Fired on player jail
CMIPlayerUnjailEvent - Fired on player unjail
Updated wiki page

**Comment by NightLife-SG** [comment]
can i get the getReason & getTime or something for it?

**Comment by Zrips** [comment]
All this information can be retrieved from user object, like user.getJailedReason()
