### ISSUE TITLE
Holograms spamming errors with async Chunk getEntities call

### ISSUE THREAD

**Issue by levtey** [Zrips/CMI#5935]
**Description of issue:**
Holograms spam errors when loading.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[13:58:05 INFO]:  ERROR!
     Error Message: Internal exception was thrown!
[Error Continued] java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
[Error Continued] org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)
[Error Continued] net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:2360)
[Error Continued] net.minecraft.server.level.WorldServer.getEntity(WorldServer.java:1791)
[Error Continued] com.denizenscript.denizen.nms.v1_17.impl.network.handlers.DenizenNetworkManagerImpl.getModifiedMetadataFor(DenizenNetworkManagerImpl.java:487)
[Error Continued] com.denizenscript.denizen.nms.v1_17.impl.network.handlers.DenizenNetworkManagerImpl.processMetadataChangesForPacket(DenizenNetworkManagerImpl.java:540)
[Error Continued] com.denizenscript.denizen.nms.v1_17.impl.network.handlers.DenizenNetworkManagerImpl.sendPacket(DenizenNetworkManagerImpl.java:198)
[Error Continued] net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2044)
[Error Continued] net.minecraft.server.network.PlayerConnection.sendPacket(PlayerConnection.java:2030)
[Error Continued] com.denizenscript.denizen.nms.v1_17.impl.network.handlers.AbstractListenerPlayInImpl.sendPacket(AbstractListenerPlayInImpl.java:111)
[Error Continued] com.denizenscript.denizen.nms.v1_17.impl.network.handlers.DenizenPacketListenerImpl.sendPacket(DenizenPacketListenerImpl.java:135)
[Error Continued] com.Zrips.CMI.NBT.v1_17_R1.makeFloatingIcon(v1_17_R1.java:932)
[Error Continued] com.Zrips.CMI.Modules.Holograms.CMIHologram$2.run(CMIHologram.java:982)
[Error Continued] org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[Error Continued] org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[Error Continued] com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[Error Continued] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[Error Continued] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[Error Continued] java.base/java.lang.Thread.run(Thread.java:831)
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 
![image](https://user-images.githubusercontent.com/60494179/126877293-d421baa0-8e91-4e1e-bf2d-6896f832366f.png)

**Server Version (using `/ver`):** `This server is running Purpur version git-Purpur-1291 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0dad40a on ver/1.17.1)`

**Relevant plugins (Delete if this isn't needed):** Citizens, possibly? I think Citizens just intercepts outgoing packets and adds their NPCs to them.

**Comment by Zrips** [comment]
Yea, entire issue originates from Citizens intercepting packet and doing some weird stuff with it while packet itself is been sent in async. Its directly originates from sendPacket method. I could ether make it being sent in sync or Citizens plugin could do it more properly on their end to avoid errors like that in the future. As there is no point for me to send packet in sync which only creates extra load on main thread when we can do it in async. 
You will need to get into contact with Citizens devs so they could fix it, if not, then i will have to do it in a crude way and make special fix for Citizens plugin. For now, closing ticket.
