### ISSUE TITLE
Rankset Progress

### ISSUE THREAD

**Issue by sunnydive** [Zrips/CMI#5942]
So for some unknown reason yesterday, 8 players in my server suddenly disconnected tgt and when they joined back their accounts have been resetted, they have the same rank but all their progress like "Travel,Kills,Block Mined etc etc" were resetted too. I was wondering is the is any way to manually set the progress back for them.

Require Help Asap.

**Comment by CloudeLecaw** [comment]
This statisics need to be done in their playerfiles.
So take their uuid /cmi info
Go into the folder of your mainworld
Look for data/stats and choose their uuid.file

Choose an ntb Editor of your joyce like to Edit their stats. Like [NTB Explorer](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac)

**Comment by sunnydive** [comment]
Oh Method 2 works! And it's efficient thank you! But could i can't seem to find some statistic
![image](https://user-images.githubusercontent.com/87953622/126949715-cd1662c9-b2b2-4fe6-a34c-82e628bfafca.png)
For example account age i can't find it.

**Comment by CloudeLecaw** [comment]
The Account age, hm does it mean the playtime?

**Comment by sunnydive** [comment]
> The Account age, hm does it mean the playtime?

Nope not play time , Its First time login, Playtime can be set as seen in the images above

**Comment by CloudeLecaw** [comment]
Hm i dont knwo if you can define the first login like a statisic. Usually this is a fixed value that never changes.

**Comment by sunnydive** [comment]
> Hm i dont knwo if you can define the first login like a statisic. Usually this is a fixed value that never changes.

Could i set that Account Age statistic through UIDD? not /cmi

**Comment by CloudeLecaw** [comment]
The account age is bases on cmi data or on playerfiles data (Uuid inthonk thats what you mean) you define innconfig what time is counted. inrecomment allways to use the playerfiles one.

**Comment by sunnydive** [comment]
> The account age is bases on cmi data or on playerfiles data (Uuid inthonk thats what you mean) you define innconfig what time is counted. inrecomment allways to use the playerfiles one.

I see, Gotcha, I'll test and try to see what i can do, thanks for the help! It's very helpful~!
