### ISSUE TITLE
Spawnmob llama colours

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#595]
**Description of issue or feature request:**
`/cmi spawnmob llama:brown` and `/cmi spawnmob llama:white` dont always spawn the correct colour.

**Comment by CloudeLecaw** [comment]
yeah if your Looking here:
https://www.spigotmc.org/wiki/cmi-commands/
under spawnmob. you see in the var list that llama Colors are not listed, just sheep

**Comment by Zrips** [comment]
Next update should work properly
