### ISSUE TITLE
RandomTeleportation

### ISSUE THREAD

**Issue by yuankun1** [Zrips/CMI#5954]
I'll take cmi's config
RandomTeleportation instead
instead   MaxRange: 3000  MinRange: 1000
Every time an instruction rt is input
Serious impact on TPS
Entering the instruction rt all the time will affect the more serious TPS

**Comment by Zrips** [comment]
Which CMI version are you running? 
Server version?

**Comment by yuankun1** [comment]
> Which CMI version are you running?
> Server version?

CMI 9.0.1.2

**Comment by Zrips** [comment]
Could you send timings for that? As with latest version it should not really create any load on server and majority of calculations went into async mode.

**Comment by yuankun1** [comment]
> Could you send timings for that? As with latest version it should not really create any load on server and majority of calculations went into async mode.

https://timings.pl3x.net/?id=76979de4d08c41b7938d0c881c267bf4
There seems to be nothing wrong with this report
But this problem will really affect TPS
But turning off timings off is no more serious at rt than on
Turning off timings off at rt is no more serious than turning it on
But it will still affect

**Comment by thecenters** [comment]
> I'll take cmi's config
> RandomTeleportation instead
> instead MaxRange: 3000 MinRange: 1000
> Every time an instruction rt is input
> Serious impact on TPS
> Entering the instruction rt all the time will affect the more serious TPS

If your world isn't pregenerated then your server will lag with random teleport

**Comment by Zrips** [comment]
From your report biggest load comes from generic chunk load while server tries to teleport player. If you dont have pregenerated map then this will trigger map generation too which is heaviest task on entire server and create lag spike. Pregenerate your world to avoid issues like this one.
