### ISSUE TITLE
[Request] -s for smite - or attached commands?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#596]
May u renember create Plugins like Thors Axe or other..

CMI can do simlier Thing ;)

Take an item of your choise: and use:
/cmi attachcommand cmi smite

Problem here: smit has no -s Option... 
so if u now starting spamming your Thunders and Lightnings with your new axe..then the console gets
a bit full after a while..

im not sure if this -s should be attach for the attached hor smite here.
Maybe both? There just should be an Option so i dont see it spammed in
console when using an item like this more then once…

Is this possible? :)

**Comment by Zrips** [comment]
Next update will be posible
