### ISSUE TITLE
Remove Enchant Cost not Working in 1.17

### ISSUE THREAD

**Issue by Xuwznln** [Zrips/CMI#5970]
**Description of issue:**
The feature that can remove the exceeding expense of anvil is not working in 1.17, but works in 1.12.2.

---

CMI Version ： 9.0.2.1 BungeeCord  SqLite
CMILib: 1.0.3.1 
Server: Tuinity 1.17.1-R0.1-SNAPSHOT
Modules -> 50 enabled 6 disabled: tablist, ranks, versionCheck, playerCombat, votifier, skin

**Comment by Zrips** [comment]
Unlimited repair costs got removed some time ago due to internal issues
