### ISSUE TITLE
Bug: Cant use spaces in names when using custom "Display Name" in Kits

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#5971]
**Description of issue:**
When you set a custom display name in kits, you cannot have a space!
We already have a "icon used" let us make custom items the same as warps! Let custom named items/lore be what is shown from the "icon used" not require a second option to write the custom name...

**Cmi Version (using`/cmi version`):** 8.8.47

**Server Type (Spigot/Paperspigot/etc):** Paper 1.12.2

**Server Version (using `/ver`):** 1.12.2

**Comment by Zrips** [comment]
Will enable spaces for kit display names with next update
