### ISSUE TITLE
Changing Color-Codes For [boolean] Values In locale.yml Files

### ISSUE THREAD

**Issue by gpop27** [Zrips/CMI#5974]
I am not sure if this is possible at all currently, hence the question. The variable [boolean] has set values for color codes "Enabled" (&6) and "Disabled" (&c) in Locale_EN.yml. Is there a way to change the color of both 'Enabled' & 'Disabled' ?

**Comment by CloudeLecaw** [comment]
Sure cmilib/Translation

Look in it for the lines you need inyour used language

**Comment by gpop27** [comment]
Oh, okay thank you! I didn't know.
