### ISSUE TITLE
Cmilib can't change local 

### ISSUE THREAD

**Issue by Genomc** [Zrips/CMI#5976]
I did a quick check and the problem is when I enter the game and exit the welcome game, it won't let me use the language I changed.

**Comment by CloudeLecaw** [comment]
- Have you Chosen the correct lang in config?
- What is the console telling you on reload of cmilib?
/Cmil reload
- Can you post your changes?
- can you post your config part about Join and leave from cmi?
- post an Output of your /cmi Version
