### ISSUE TITLE
Elevator Signs Not Working Above Nether Roof

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#5978]
**Description of issue:**
Hopefully this wasn't a result of the fix to my last report regarding random in the nether, but I'm not sure when this one started either. I've only recently had a report of it so I think it's kinda new. 

Elevator signs will work up to the roof itself (directly on top of the bedrock), but placing a sign on roof +1 block and we get the `Can't find suitable location` message. Elevator signs placed at **all** heights will still work going _down_, but not up.

No errors in console, just denied.

Thanks!

---

**Cmi Version (using`/cmi version`):** 9.0.2.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-Paper-137 (MC: 1.17.1)

**Comment by rockitseven** [comment]
I have the same issue.
