### ISSUE TITLE
%cmi_user_canrankup% placeholder not working

### ISSUE THREAD

**Issue by NyhmsQuest** [Zrips/CMI#5979]
**Description of issue:**
The placeholder %cmi_user_canrankup% doesn't seem to work, it will always return False even when I'm actually able to rankup.

![image](https://user-images.githubusercontent.com/3873370/127612849-548bcc65-a386-4302-9517-06ee5a94f861.png)

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/3873370/127612928-f8cf65f5-3a4b-4376-85c1-cdfdcb4e3801.png)

**Server Type (Spigot/Paperspigot/etc):** 
Paper Spigot
**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/3873370/127612969-c3cb10ac-49c5-482a-8aaf-77c0c0ab243d.png)

**Comment by Zrips** [comment]
Should get a fix with next build
