### ISSUE TITLE
Rankup block place is counting block break

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#5987]
**Description of issue:**
In rankup when you break a block it also counts for blocks placed. 

**Cmi Version (using`/cmi version`):**  9.0.2.2 

**Server Type (Spigot/Paperspigot/etc):** Tested on 1.16.5 paper spigot and 1.17.1 paper spigot

**Comment by Zrips** [comment]
Next update should resolve this issue. If it repeats let me know.
