### ISSUE TITLE
Tablistrank Order

### ISSUE THREAD

**Issue by AbgescammtYT** [Zrips/CMI#5993]
Add a Option to set the order of the ranks in the tablist, like ghet the weigts from luckperms and set the order then from that or an extra option in config. So user dont have to install an extra plugin for the tablist order because cmi have a tablist feature but not the tablist order feature.

**Comment by AbgescammtYT** [comment]
And the Rank and the name over the player would be nice for an extra option from the tablist :)

**Comment by CloudeLecaw** [comment]
one of the most often suggested features the last 3 years.
May it will come one day.

For not it will land in discusstion thread line the other xx requests where player asked for tablist sorting

**Comment by strahil211** [comment]
I requested this before it just got pushed somewhere into enhancements and probably forgotten about forever again.

**Comment by CloudeLecaw** [comment]
It will pushed to discussion aggain like the others the Last 3 years ;)
