### ISSUE TITLE
BUG essentials home in CMI

### ISSUE THREAD

**Issue by kedavlar** [Zrips/CMI#5996]
**Description of issue:**

I follow this guide for tranfer everything form essentials https://github.com/mrfdev/CMI/blob/master/Resources/FAQ/cmi-import.md but the home still dosent work with error ''dosent exist'' in every home. the other things are transferred successfully

UPDATE: i test on server without plugin, same thing.

ERROR: 
![2021-08-02_12 53 58](https://user-images.githubusercontent.com/85011614/127850909-c20cd4a6-e528-4f64-9ad1-531e78b15f85.png)

**Cmi Version: 9.0.2.2:** 

**Server Type: tuinity 1.16.5** 

**Server Version: tuinity 1.16.5 9f3435b**

**Comment by mrfloris** [comment]
Do you still have this when you have Tuinity on the latest version, cmi on version 9.0.2.7 and cmilib on 1.0.3.5 ?

**Comment by mrfloris** [comment]
Oh and which version of essentialsx are you importing from?

**Comment by kedavlar** [comment]
yes, same on lastest cmi , for essentials version is the essentialsx dev build 248

**Comment by Zrips** [comment]
Will get resolved with next update. This  became an issue after Essentials decided to change saved fileformat. By updating CMILib old imports should start working too without any need to re-import them.
