### ISSUE TITLE
CMI Command /pwarp causing problems 

### ISSUE THREAD

**Issue by Ew9304** [Zrips/CMI#60]
I am trying to tab complete the command "/pwarp <name>" and I am getting an error which is pointing to CMI for some reason? I use Welcome Warp Signs and Command Control to redirect /pwarp to /wwarp, but even without the alias setup, I still can't get an error both in-game and in console - when trying to tab complete /pwarp.... (and for some reason my /pwarp redirects to /help when no alias is setup for it? Shouldn't it just say command not found. o.o)

- If I just type /pwarp playername without tab complete it works fine, no errors. I would like to be able to tab complete just like the /wwarp command.

- If I just try and tab complete /pwarp without starting to type a name, I get a list of a bunch of CMI commands?

![3](https://user-images.githubusercontent.com/34957646/36799767-f542ebbe-1c7b-11e8-8b43-fef331c84753.png)
![1](https://user-images.githubusercontent.com/34957646/36799768-f554febc-1c7b-11e8-9a82-7817c4428e3e.png)
![2](https://user-images.githubusercontent.com/34957646/36799770-f575b1f2-1c7b-11e8-87c2-8860a4a821f5.png)

**Comment by Zrips** [comment]
Should be fixed with next build
