### ISSUE TITLE
setFirstspawn does not work properly

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/CMI#600]
I have in a defined world an area on which the new players spawn - unfortunately they spawn on Serverspawn ... :(

akutellste CMI Version 
Serverversion:  1.12, 1.12.1 & 1.12.2

**Comment by HomeLandingsDE** [comment]
edit: 
If the guest spawnt he enters the game on "Firstspawn" but is immediately ported to "ServerSpawn" ... how can I fix this problem will open the server in 3 days ...

**Comment by LogGits** [comment]
I am assuming this was resolved as there have been no responses. If you are still experiencing this, please open a new issue.
