### ISSUE TITLE
Option to disable updating /back teleport location when using Elevators

### ISSUE THREAD

**Issue by Jameshobbs21** [Zrips/CMI#6002]
### Discussed in https://github.com/Zrips/CMI/discussions/5975

<div type='discussions-op-text'>

<sup>Originally posted by **Jameshobbs21** July 29, 2021</sup>
Hello,

I've been loving the sign elevators a great deal. However, it unfortunately will update the last teleport location, so when my users run /back, it will teleport to the prior location from the elevator.

It would be nice to have an option to disable this feature. So when a player teleports using an elevator, it would not update the player's last teleport location.

Was wondering if this feature could be implemented? Or if you have suggestions on how I could implement it in my own plugin.

Thanks,
Jameshobbs</div>

**Comment by Zrips** [comment]
With next update elevators should not longer record previous location for /back
