### ISSUE TITLE
CMI Holograms are not being updated while in view distance

### ISSUE THREAD

**Issue by Tencryn** [Zrips/CMI#6004]
CMI Holograms are not being updated after creation, and after calling `CMIHologram#update()`. You can see the code [here](https://github.com/Rosewood-Development/RoseStacker/blob/master/Plugin/src/main/java/dev/rosewood/rosestacker/hologram/CMIHologramHandler.java)

Holograms updated without fault on CMI 9.0.1.3, but this is not the case on 9.0.2.3. Players need to move out of the view distance of the hologram before it will update.

Can contact the plugin author on Discord @ `Nicole#0001`, by joining their [discord](https://discord.gg/MgUsTBK) or they can contact CMI developers if necessary.

--

**Cmi Version:**
9.0.2.3

**Server Type:**
Paper 1.17.1

**Server Version:**
132

**Relevant plugins:**
RoseStacker

**Comment by Zrips** [comment]
Can you elaborate more on what you mean with "move out of the view distance"? Did some basic testing with that code, it looks to be working, hologram updates when update is called, so how exactly could I reproduce this issue?

**Comment by Tencryn** [comment]
I can confirm this was **fixed in CMI 9.0.2.5**, but here is a [yt video](https://www.youtube.com/watch?v=fOSAkzRD00k) for what happened prior to it being fixed, just incase you had no idea this was an issue to begin with.

In the video, I can be seen placing multiple spawners. The number of spawners on the hologram should update as I modify the spawner stack. This does not happen. I move away from the hologram so that it is no longer in view, and then I come back into view of it to see that it is now updated.

I had updated Paper, CMI and CMILib to the latest available at this current time to find that the holograms were updating correctly. Reverted to CMI 9.0.2.4 as I saw that there was a fix for "holograms being shifted down by one line" in 9.0.2.5, and lo and behold, the holograms would not update correctly.

**Comment by Zrips** [comment]
Strange, shift fix should not have had impact like that, maybe i have changed something else which resolved this issue. In any case, as long as its fixed we are good. Closing ticket for now.

**Comment by Tencryn** [comment]
Was showing that this was fixed to my partner, turns out... not quite. Holograms will update for me, but not for her. After I log out, it will update for her. So it seems to be updating for a single player only.

I cannot think of any reason why it would always prioritize me, apart from ping?
