### ISSUE TITLE
[Request] SupriceTicket

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#601]
WIt would nice to be able to create a "Supriceticket"

The Supriceticket has an itempool that can be defined by command (add this) or GUI.
Different rewards like Items, or money or specialcommands can be setup in this rewardpool, (and set a GetITChance (1:X  -> 1 to X)   to get it. Only get Thing of he rewardpool can be taken at once.
If this rewardpool is created it can be "called" by the surpiceticketcommand or something simlar like /cmi rewarditems Weeklylottery (Playername)
 - Playername is opional if u what to execute the command so give someone esle the ticket (or execute it from console or attached item)

Nice Bonusfeature here:  - Owner now could create a thing like LotteryTickets - 
a Surpcieticket getting by an attached command to an item (oneTimeUse) and is sold in a shop the owners has on his server

**Comment by LogGits** [comment]
Sounds interesting, however we will not be adding this as it is too specific and wont be utilised by a majority of CMI users. At the moment we are working on compatibility with 1.13, however, don't take this as a definite no, it could get added in the future 😉

**Comment by CloudeLecaw** [comment]
Well Maybe not, but if someone asked for a DoubleDoor Opener feature then ist added because many Protection Suites have it allready.. so just the one that does not use a protection tool will not have it.. i understand this <3 ^^
