### ISSUE TITLE
Changing warp slots does not save on plugin reload or server reboot

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#6014]
**Description of issue:**
Change the slot of warps to change their location, this is not being saved when the plugin is reloaded or the server is rebooted

**Cmi Version (using`/cmi version`):** 
9.0.2.4
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.12.2

**Comment by Zrips** [comment]
Will make some changes to save changes you made for warp slot in case you decide to reload plugin. Tho it should have still worked just fine with full server restart.
