### ISSUE TITLE
/give command Hex codes not converting correctly for names and lores

### ISSUE THREAD

**Issue by trickman325** [Zrips/CMI#6017]
**Description of issue:**
Using the /give command doesnt like hex codes with names AND lores

**These are the exact commands that was used** 

/cmi give {player} turtle_egg{display:{Name:"\"{#2ffbc8}E{#5efc96}a{#8dfd64}s{#bcfe32}t{#ebff00}e{#efcc31}r {#f76693}e{#fb33c4}g{#ff01f5}g\"",Lore:["\"&l \"","\"tt\""]},Enchantments:[{id:knockback,lvl:2}]} 3

**Also tried:**

/cmi give {player} turtle_egg{display:{Name:"\"{#2ffbc8>}Easte{#ebff00<>}r egg{#ff01f5<}\"",Lore:["\"&l \"","\"{#2ffbc8>}Easter{#ebff00<}\""]},Enchantments:[{id:knockback,lvl:2}]} 3

**Which gives this output:**
![Screenshot (262)](https://user-images.githubusercontent.com/58171146/128698390-a55fe8cb-6782-4856-ba5d-c1182670c75f.png)
![Screenshot (264)](https://user-images.githubusercontent.com/58171146/128698890-42862e76-8c33-4f59-b07c-3b15d57f7075.png)

---

**Cmi Version (using`/cmi version`):** 
9.0.2.4

**Server Type (Spigot/Paperspigot/etc):** 
Paper(154) 1.17.1-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 
1.17.1

**Comment by Zrips** [comment]
Its more of a minecraft bug which fails to process data like that. You will need to ether use full messy format like 
`{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FF0000","text":"E"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#5EFC96","text":"a"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#8DFD64","text":"s"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#BCFE32","text":"t"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#EBFF00","text":"e"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#EFCC31","text":"r"}],"text":""}`
for name alone or simply use CMI format like
`/cmi give Zrips turtle_egg n {#2ffbc8>}Easte{#ebff00<>}r_egg{#ff01f5<} l /n{#2ffbc8>}Easter{#ebff00<}` which produces correct results
