### ISSUE TITLE
CMI message and vanish

### ISSUE THREAD

**Issue by MasonKidder345** [Zrips/CMI#6019]
**Description of issue:**
When your in vanish and you go to your vanisheditor and then turn on the *Accepting private messages* it turns them on but if you turn it off to false it doesnt turn on and players can still message you while you are vanished. But if I become visibile and then revanish again, they won't be able to mesasge me.

---

**Cmi Version (using`/cmi version`):**  9.0.2.4

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** 1.16.5

**Comment by Zrips** [comment]
Will be resolved with next update
