### ISSUE TITLE
Having Trouble getting TownyChat to work

### ISSUE THREAD

**Issue by WalkingPixel1** [Zrips/CMI#602]
**Description of issue or feature request:**
Issue: TownyChat Won't use its own Format when using /tc texthere it just comes out as CMI format and not a TownChat Channel format. If I disable CMI the TownyChat works normal and shows its format for townychat. There are no errors in console either. Please if there is a fix or something I am doing wrong help would be greatful :) Thank you!
```

**Cmi Version (using`/cmi version`):  7.8.11.1

**Server Type (Spigot/Paperspigot/etc): Spigot 

**Server Version (using `/ver`): SPIGOT 1.12.2-R0.1-SNAPSHOT

**Comment by LogGits** [comment]
I am assuming this was resolved. If you are still experiencing this please make a new issue.
