### ISSUE TITLE
The cmi.dropspawner permission does not work

### ISSUE THREAD

**Issue by yngdrms** [Zrips/CMI#6020]
The cmi.dropspawner permission does not work. When you specify a certain type in the permission, it works.
---

**Cmi Version (using`/cmi version`):** 9.0.2.4

**Server Type (Spigot/Paperspigot/etc):** Airplane

**Server Version (using `/ver`):** 1.16.5

**Comment by Zrips** [comment]
Did you by any chance enabled RequiresExactPermission config option?
