### ISSUE TITLE
PAPI placeholders don't work in CMILib translations

### ISSUE THREAD

**Issue by RyanHoOo** [Zrips/CMI#6021]
**Description of issue:**
PAPI placeholders don't work in CMILib translations. Whenever triggered, it shows the placeholder itself.

![image](https://user-images.githubusercontent.com/81949291/128998860-5bc398bc-1cad-45bb-9542-d277b14d0b5e.png)

For example, for the first CMI message I used the same placeholder as the second CMI message. The first one is configured in CMI's translations and the second in CMILib's translations. The first one showed exactly what I wanted (the Multiverse alias of the world the player died in, with its corresponding colour) but the second one didn't work.

**CONFIG SECTION:**

plugins/CMILib/Translations/Locale_EN.yml
https://pastebin.com/L1JW5eyR
plugins/CMI/Translations/Locale_EN.yml
https://pastebin.com/65wwtYvM

---

**Cmi Version (using`/cmi version`): 9.0.0.5** 

**Server Type (Spigot/Paperspigot/etc): Purpur** 

**Server Version: 1.16.5** 

**Relevant plugins: PlaceholderAPI**

**Comment by Zrips** [comment]
Should be working more correctly with next CMILib update
