### ISSUE TITLE
Players in baltop

### ISSUE THREAD

**Issue by MasonKidder345** [Zrips/CMI#6024]
**Description of issue:**
When server is whitelisted a person tries and joins he gets added to /baltop. but not other commands like /cmi lastonline or /cmi info <player> etc...

**Cmi Version (using`/cmi version`):** CMI9.0.2.5

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** 1.16.5

**Comment by Zrips** [comment]
Should be resolved with next update
