### ISSUE TITLE
My Server will not load the plugin

### ISSUE THREAD

**Issue by JayZzCc** [Zrips/CMI#6045]
Visit https://github.com/Zrips/CMI/discussions/new to post question
Posting questions in ticket section could result in their removal.

Hi,

Just buyed the plugin and downloaded it, but when i stop my server (that runs on Spigot 1.17.1) and i put CMI9.0.2.7 in the plugins folder and i start the server, then the server says in the commandprompt: [16:51:53 ERROR]: Could not load 'plugins/CMI9.0.2.7.jar' in folder 'plugins'.
What can i do about this, why is it not working?
only have WorldEdit, WorldGuard and Multiverse on my server.

Thanks!

**Comment by ItLucifer-MRPG** [comment]
One, why are you running spigot, Id change to something more optimized, like paper, purpur, etc

Two, have you got CMILib installed aswell?
