### ISSUE TITLE
metadata increment from console does not work

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6046]
Metadata increment does not work from console..

i tested it with cmi usermeta Cloude_Lecaw increment Vote5Times 1 
as result you get the how to use the command feedback...
![image](https://user-images.githubusercontent.com/12080017/130022935-e2dec048-6951-486e-897d-c99a18290fc5.png)
.
.

will using add and the others work fine
![image](https://user-images.githubusercontent.com/12080017/130023012-7112cc66-7e5d-402e-8150-80bc78802384.png)

![image](https://user-images.githubusercontent.com/12080017/130023086-bc29efb1-8d57-4e48-bb76-75c4a2342f8b.png)

**Comment by Zrips** [comment]
Well you do need to provide + in case you want to add increment. Will make some changes to default to addition when you are not providing + sign in front of value
