### ISSUE TITLE
If you have time, please change the [editable content] in the language file to < required > (optional)

### ISSUE THREAD

**Issue by Zz-886** [Zrips/CMI#6047]
Because [variable] is very easy to cause errors in translation work

**Comment by CloudeLecaw** [comment]
Not really. [variable] is a good option and you should know that this never should be translated because its a plaveholder :)

**Comment by Zz-886** [comment]
In this case, you can change the non-variable [modifiable content] to
<Required> (optional)

**Comment by Zz-886** [comment]
In this case, you can change the non-variable [modifiable content] to <required> (optional)

**Comment by Zz-886** [comment]
In this case, you can change the non-variable [modifiable content] to < required > (optional)

**Comment by Zz-886** [comment]
It can be modified like this [modifiable content] is changed to < required > (optional)

**Comment by CloudeLecaw** [comment]
U can change it by youself simply open the Translation folder and change it in all lines where u want to change it. :)

**Comment by Zrips** [comment]
Changing variable format at this point in development would only introduce confusion and issues. Even if we had better solution to more stream line dynamic variables that would not really be and option to change them currently. We will have to stick with current format.
