### ISSUE TITLE
CMI portal problem

### ISSUE THREAD

**Issue by yuankun1** [Zrips/CMI#6048]
Create a Particle effect particle portal
Activationrange: 8 changed to 60
It will cause the player's customer service terminal to delay jamming

**Comment by Zrips** [comment]
What type of particles? How many of them? How big is portal? Server version? Without extra information like that i cant really debug it properly.

**Comment by yuankun1** [comment]
> 什么类型的粒子？他们中有多少人？传送门有多大？服务器版本？如果没有这样的额外信息，我就无法正确地调试它。

airplane 1.17.1
CMI 9.0.2.1 
portal 30x30
palyers 2
All particle effects
Includes some plug-ins for particle effects
It may also be a server problem

**Comment by Zrips** [comment]
Particles are shown in async which means that those will not lag out server itself. if you are having issues with particles in general then it can be issue with your client or your pc not handling them properly and struggling with that. Closing this ticket for now as this looks more as an issue with your server or your client and not with plugin itself.
