### ISSUE TITLE
[Request] Stop the jail timer when logging off

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#605]
I love the jail feature, and I use it on players that wont follow my rules. Everything is working perfectly :D But there is one little downside to it. If I jail a player for some amount of time they can escape the punishment by just logging off and wait for the time to pass by. I really want them to feel the frustration when I jail them. I dont want them to pick the easy way out. 

Is there a way to maybe make an option in config file to enable/disable time when logging off the server? I dont want the time to still count down if the player isnt there.

**Comment by RustyDagger** [comment]
I second this, it would really allow there to be some difference then between jail and a temp ban.

**Comment by CloudeLecaw** [comment]
it should be a chooseable option, i also know this problem
if you  jail someone for a hour, he loogs of and come later back after the hour
so this would be same liek tempban him

but if he needs to stay the time in playtime (afk time should not count too) then he has to keep the playtime in jail

This also needs a bit social skills of your adoms that can jail...this is out of sense if u jail a player for 2 weeks playtime if he needs to stay there

What is the difference then betweens jail and tempban?
Why jail him then and not simply tempban? while Jails the player still has the option to communicate with friends, staff etc.. also some server do some kind of "minigames" or other things that player can do in jail do not get to boring.   Jailing never should be a hornor or reward, it simply should not be too boaring (like sitting in a stoneblock without seeing anyhting..this is "not fair" for the jailed one^^)

**Comment by JohOply** [comment]
I like the idea! I also want to have a real difference between jail and temp ban features

**Comment by JohOply** [comment]
Hi @LogGits 
Do you think it could be added in next versions ("soon")?

**Comment by JohOply** [comment]
This issue should be closed I think so?
https://github.com/Zrips/CMI/issues/1308

**Comment by Meldiron** [comment]
Awesome idea, I also fully support that.

**Comment by JohOply** [comment]
I think it is now implemented. This issue has to be closed in my mind.

`Jail:
  # Defines in milliseconds how often to check if player leaves jail area
  # Bigger numbers can help slightly lower server load
  CheckInterval: 500
  # Defines default jail time when time is not povided with command
  DefaultTime: 600
  # Chat range in blocks while player is in jail
  # Set to 0 to allow talking
  # set to -1 to prevent talking in general while jailed
  ChatRange: -1
  # When set to true jail time will decreese while player is offline
  # When set to false jail time will only be counted while player is online
  CountWhileOffline: false
  # When set to true jail time will not decreese if player gets into afk mode while being jailed
  # When set to false, time will pass normally
  NoAfk: true`
