### ISSUE TITLE
Cant jump into the void when in creative mode

### ISSUE THREAD

**Issue by MarkinhosMLP** [Zrips/CMI#6055]
**Description of issue: Cant jump into the void when in creative mode**

---

**ERROR:**
```
When in creative mod, jumping into the void or going in a low coordinate (-4 for example)... u got teleported back to some random Y-coordinate position... or to the surface of your coordinate... ive been searching for a configuration where i can change this but... yeah, nothing
```

---

**Cmi Version (using`/cmi version`): 9.0.2.7** 

**Server Type (Spigot/Paperspigot/etc): Purpur** 

**Server Version (using `/ver`): 1.17**

**Comment by Zrips** [comment]
Could be PreventPlayersBelowBedrock which is by default set to false and when enabled will prevent you from flying under bedrock, still allows you to fall down but not flying. Or it could be ProtectFromVoid which is part of totem mechanic and would teleport you back up if you have totem in your hand when you experience void damage. But it looks to be first option most likely, disable it and it should be all good.
