### ISSUE TITLE
9.0.2.8 Sethome confirmation

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#6057]
**Description of issue:**
Version 9.0.2.8 introduces a confirmation for setting homes which is a great idea. However, it doesn't seem to work properly.
- Confirmation doesn't work. I can click endlessly to confirm but the home is not set.
- The config comment speaks of `-override`. This should be `-overwrite` (as mentioned in the language file)
- This change is not mentioned on the spigot page although it impacts most servers.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Homes:
  # When enabled we will require player to click on ingame chat to confirm hoime location override in case home with same name already exist
  # This can be dirrectly confirmed with /cmi sethome [homeName] -override
  Confirmation: true
```

---

**Cmi Version (using`/cmi version`):** 
9.0.2.8

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
1.17.1

**Comment by Zrips** [comment]
Sorry about that. Will fix with next update.
