### ISSUE TITLE
Portals

### ISSUE THREAD

**Issue by TheKlimoT** [Zrips/CMI#6059]
**Description of issue:**
Then what's wrong with the portals, I have 4 portals in one place, I want to make them turn on at different times, because they have different rights, but if 3 are turned off and 1 is turned on, you can't go in

To make the portal work, you need to enable all 4 portals. I repeat, they are located in 1 place, at the same coordinates.
CMI: 9.0.2.7
Purpur: 1.17.1

**Comment by TheKlimoT** [comment]
https://paste.helpch.at/wuzohezoni.css

**Comment by Zrips** [comment]
Well portals have never been made to handle multiple of them in one single place. Will make few changes, which should get it to your desired behavior with multiple portals in a single place even if its includes disabled ones.
