### ISSUE TITLE
Glow permission gives permission for others by default

### ISSUE THREAD

**Issue by levtey** [Zrips/CMI#6061]
**Description of issue:**
When a player is granted `cmi.command.glow`, they are also able to turn other players' glow off with `/glow (player)` unless the `cmi.command.glow.others` permission is set to false.

**Cmi Version (using`/cmi version`):**
![image](https://user-images.githubusercontent.com/60494179/130372239-f67c828d-1f79-4e2f-a885-fae1aea514e0.png)

**Server Type (Spigot/Paperspigot/etc):** Purpur-1329

**Relevant plugins (Delete if this isn't needed):** Using luckperms for permissions.

**Comment by mrfloris** [comment]
<img width="695" alt="Screenshot 2021-08-23 at 00 42 01" src="https://user-images.githubusercontent.com/28841349/130372311-3e2eb82b-fa2d-4c3d-b2d0-db6bb77287ea.png">
<img width="646" alt="Screenshot 2021-08-23 at 00 42 28" src="https://user-images.githubusercontent.com/28841349/130372323-db749575-3e51-4913-a5a4-ebb1061e4aae.png">
<img width="656" alt="Screenshot 2021-08-23 at 00 43 08" src="https://user-images.githubusercontent.com/28841349/130372344-e69dd908-b686-47d4-aed5-f2783b45b5b1.png">
<img width="695" alt="Screenshot 2021-08-23 at 00 43 27" src="https://user-images.githubusercontent.com/28841349/130372357-fdf7c650-1bc5-4f76-a5e2-eb5dbf2723c3.png">


I have the default group set to allow use of the command, but not .others.
I have the default group set to allow white, not other colors. And higher groups have other colors. 

If they dont have perm to use say 'cyan', it gives perm denied
if they have perm to use say 'white', it gives perm denied
... when used on another player.

cannot reproduce

<img width="1241" alt="Screenshot 2021-08-23 at 00 44 54" src="https://user-images.githubusercontent.com/28841349/130372377-9f263db2-7cc7-4c48-8a16-d7ff6bc99159.png">

**Comment by mrfloris** [comment]
Sooooo.. 

cmi.command.glow.*
to give all colors, which includes ".others" ????

**Comment by levtey** [comment]
Never mind, had the permission set to `cmi.command.glow.*` instead of `cmi.command.glow.color.*`.
