### ISSUE TITLE
After setting the world name in the CMIlib language file, the %cmi_user_world_formatted% variable has not changed

### ISSUE THREAD

**Issue by Zz-886** [Zrips/CMI#6062]
After setting the world name in the CMIlib language file, the %cmi_user_world_formatted% variable has not changed
![image](https://user-images.githubusercontent.com/55978588/130419613-d6c42d1a-7d3a-483b-9a0e-f43542d1d511.png)

**Comment by Zrips** [comment]
For changes to take place you will need to perform **/cmil reload** which is CMILib command to update its config files. But as you mention this one, will make some adjustments to reload it when you perform **/cmi reload** too. Just to be more convenient and avoid reports like this one in the future as it looks to be common inconvenience and confusion.
