### ISSUE TITLE
/cmi gamerule command whether to add translation for game rules in GUI

### ISSUE THREAD

**Issue by Zz-886** [Zrips/CMI#6063]
/cmi gamerule command whether to add translation for game rules in GUI

**Comment by CloudeLecaw** [comment]
These ganerules by world are comming from vanilla and are equal to minecraft:gamerule command. You find description of the gameruls in the normal Minecraft wiki

**Comment by Zrips** [comment]
@Zz-886 
No current plans to translate them as those directly represent actual meaning of that gamerule. Maybe later on we could add custom name and some explanation what those mean.
