### ISSUE TITLE
Add support to worldguard

### ISSUE THREAD

**Issue by G0nter** [Zrips/CMI#6064]
On some occasions, a player can escape combat by entering a protected area, this is usually quite annoying for a survival server.

**Comment by CloudeLecaw** [comment]
There is not only worldgaurd, Redprotect or even zrips own one residence.
Well its more part of your Region plugin to allow not escaping a pvp area.

**Comment by Zrips** [comment]
@G0nter 
Will add some what universal method to allow damage when you run into safe zone, might not be 100% bullet proofed but as of testing dint really encountered any issues so far with area protection plugins. 
Next update.
