### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by hankwu0501** [Zrips/CMI#6067]
**Description of issue:**

api is broken?

**ERROR (DELETE IF YOU HAVE NO ERROR):**

https://pastebin.com/9denFNwt 

CMI.getInstance().teleportations.getRandomLocation(Bukkit.getWorld("world")) doesnt work and have bugs

**Comment by Zrips** [comment]
CMI doesn't support official airplane purpur server version, so some issues might be seen in those custom versions. Cant really keep up with every single minecraft branch out there.
