### ISSUE TITLE
eventCommands when player use command  will triggered to something

### ISSUE THREAD

**Issue by HoYa-DaiBo** [Zrips/CMI#6068]
Can I set it?
If the player uses the /tpa command, an event is triggered to announce the player's coordinates?

Currently I use playerTeleport, but I don’t want to trigger an announcement event when the player uses the gate of hell or the end gate, the use of the end pearl, the ship, the horse... etc.

Is there any other way?

sorry my english...

**Comment by Zrips** [comment]
There isint any specific method to handle specific events like that. But There is some what work around. With next version you can use something like this
`      youAccepted: '!broadcast!&6[senderDisplayName] &eTeleporting to %player_x%:%player_y%:%player_z%'`
for tpaccept locale section which would broadcast message to everyone with players name who teleports and to what location

**Comment by HoYa-DaiBo** [comment]
> There isint any specific method to handle specific events like that. But There is some what work around. With next version you can use something like this
> ` youAccepted: '!broadcast!&6[senderDisplayName] &eTeleporting to %player_x%:%player_y%:%player_z%'`
> for tpaccept locale section which would broadcast message to everyone with players name who teleports and to what location

9.0.2.10 version released

Where do I add events such as CMIPlayerKickEvent?
I don't quite understand, sorry.

The following is the previous configuration
`playerTeleport:
  Enabled: false
  Commands:
  - delay! 0.3
  - cooldown:1! perm:cmi.nosrbcpos! cmi broadcast &cresourceteleport:&3player &e[playerName] &3Be detected!
    &7Location &8> &eWorld:&c%player_world%&7|&eX:&c%player_x%&7|&eZ:&c%player_z%`
    
   
   Should I make an additional one? Or use other events like CMIPlayerKickEvent to complete it?

I don't know how to use events like CMIPlayerKickEvent...
