### ISSUE TITLE
Semantics Issue "/tptoggle"

### ISSUE THREAD

**Issue by Raesak** [Zrips/CMI#6072]
Minecraft: 1.17.1
CMI: 9.0.2.8

This is more of a semantics issue with the wording for "/tptoggle". 

When using the command it prints "Teleport prevention: Enabled/Disabled"

When it shows "Teleport prevention: Enabled" it will let players teleport to that player. The problem is that it states prevention is ENABLED. If prevention = true, then teleport requests should be prevented.

https://i.postimg.cc/DyV946LP/zzzzzzzzzzzzzzzzzzz.jpg

EDIT:
In the image above it stated that the request was denied after I clicked the X. Not because the prevention was actually enabled.... which means that it's actually disabled....
Even I think it sounds confusing now.

**Comment by Zrips** [comment]
Yea, i can agree that its some what confusing looking one. Will update default locale to be more obvious what it does with more appropriate states being shown.
