### ISSUE TITLE
tpawarmup particle cannot be disabled

### ISSUE THREAD

**Issue by siulung201314** [Zrips/CMI#6075]
**Description of issue:**
When disable all particles or disable tpawarmup particle only, there is still particles near the player during tpawarmup.

**CONFIG SECTION:**
Particles:
  Enabled: false
  TotemHalo: circle;effect:reddust;c:255,255,10;twist;part:3;offset:0,2,0;pitch:90;radius:0.3;interval:2
  Healing: circle;effect:heart;dur:0.1;part:1;offset:0,1.7,0;radius:0.3
  GlyphHead: circle;effect:flying_glyph;dur:5;pitchc:15;part:10;offset:0,1.7,0;radius:0.5;yawc:12;color:rs;pitch:90
  tpaWarmup: ''
  GColumn: circle;c:0,255,0;twist;part:5;r:0.75;pitch:90;move:0,0.1,0;rc:-0.02
  SmallBoop: circle;effect:flying_glyph;yaw:[playerName];pitch:[playerName];r:0.1;part:3;rc:0.03;mr:0.3;twist
  HologramInteraction: circle;effect:flying_glyph;yaw:[playerName];pitch:[playerName];r:0.1;part:3;rc:0.03;mr:0.3;twist
  TpUp: circle;c:200,50,210;twist;part:5;r:0.5;pitch:90;move:0,0.33,0;offset:0,-0.2,0
  TpDown: circle;c:150,50,10;part:5;r:0.5;pitch:90;move:0,-0.33,0;offset:0,2.2,0

**Cmi Version (using`/cmi version`):9.0.2.9

**Server Type (Spigot/Paperspigot/etc): purpur

**Server Version (using `/ver`):1.17.1

**Comment by Zrips** [comment]
Will be fixed with next build
