### ISSUE TITLE
Blocks placed and mobs killed placeholders incorrect behavior

### ISSUE THREAD

**Issue by goldendoji** [Zrips/CMI#6077]
**Description of issue:**
The "BlocksPlaced" and "MobsKilled" placeholders are counting up at the same time when mobs are killed. The action is not the same if blocks are placed though. 
The blocks placed integer in the "/stats" command appears to not match the blocks placed integer being fed the scoreboard when using "%cmi_user_stats_BlocksPlaced%".
EDIT: Mining blocks appears to also increase both the mined blocks and the blocks placed integers.

---

CMI version: 9.0.2.9

Server type: Spigot

Server Version: 3226-Spigot-3c1fc60-a955f15 (MC: 1.17.1)

Relevant plugins: Placeholder API (possibly)

**Comment by Zrips** [comment]
Should be fixed with next build
