### ISSUE TITLE
Bug when eating while in god mode.

### ISSUE THREAD

**Issue by Tobi-Jakka** [Zrips/CMI#6083]
**Description of issue:**
When trying to eat (when not at full hunger) in god mode you dont recover hunger but still consume food

---

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/42676160/131194808-6409bb20-b36e-4942-82b9-554ec4b7ff46.png)

**Server Type (Spigot/Paperspigot/etc):** 
![image](https://user-images.githubusercontent.com/42676160/131194822-bfd36add-1047-4029-baee-9954a25a2a1d.png)
(paper fork) (this is /version)

**Comment by Zrips** [comment]
Should be resolved with next build
