### ISSUE TITLE
Can you add a variable to get the BungeeCord server name? I want to display it in TabList.

### ISSUE THREAD

**Issue by Beoo-666** [Zrips/CMI#6091]

**Comment by ItLucifer-MRPG** [comment]
I assume you have cmi set up on each server, why don't you just have a different tab for each server, and change the name depending on what server you're on

**Comment by WolverStones** [comment]
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#bungeecord ?

**Comment by Beoo-666** [comment]
@ItLucifer-MRPG 
I need all server players to be displayed in a TabList instead of being separate.
The official wiki has variables for getting online players. I think it should be easy to get the server name.
![image](https://user-images.githubusercontent.com/55978588/131422913-fb9ecb48-0ea7-4435-ad3a-7967a87212c3.png)
