### ISSUE TITLE
CMI SCAN --- { PURGE } Option not working well

### ISSUE THREAD

**Issue by klaidoshka** [Zrips/CMI#6095]
**Description of issue:**
If anyone is scanning a big world with an option to purge the wanted item, the purge only happens in loaded chunks, the chunks that weren't loaded (no people inside) are scanned, item is found, but not purged, it stays wherever it is. The chunk that someone stood in is scanned, item is found, item is removed (purged).
Worth to mention that I tried to purge elytras in whole End World 7500 x 7500 (minecraft border).

---

**Cmi Version (using`/cmi version`):** 8.8.5.0

(However I believe nothing has been touched about `/cmi scan` in new versions of CMI, so it probably is the same in new versions too. And I understand that after a fix I would need to update.)

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.16.5

**Comment by Zrips** [comment]
Should be fixed with next build
