### ISSUE TITLE
CMI config reset

### ISSUE THREAD

**Issue by SkeletonAce** [Zrips/CMI#6098]
Hi after updating to 9.0.2.9 some sections of the config have been reset to default;
the `kit` to give newbies,
the `timespeed` and `RandomTeleportation` sections,
these are what I have noticed so far.

Cmi Version (9.0.2.9)

Server Type (Purpur)

Server Version (1.17.1)

**Comment by CloudeLecaw** [comment]
Its pupur ;p

**Comment by CloudeLecaw** [comment]
No joking. What ever went wring onnyour Server its nonregular thing. I took a loook on our servers and test servers, there all configs are unchanged.

So might be an issue in your config or there was an server issue on saving(restarting maybe?)

**Comment by SkeletonAce** [comment]
ok thankyou for the advice, I'm also getting enchantment books with double up enchantments so a corruption is very possible, Just not sure the source of it.
![2021-08-31_09 41 41](https://user-images.githubusercontent.com/76664499/131570889-b32b7798-f9ac-4379-9e0a-b7187d29faab.png)

**Comment by SkeletonAce** [comment]
Yup this has been fixed after I restarted, Thankyou
