### ISSUE TITLE
Extra parameter for /tpa

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#61]
The command would have an optional parameter for /tpa. The command would look like `/cmi tpa [playerName] (playerName)`. The essence of this suggestion is that it would make it possible for an administrator to suggest a player tpa to someone. It would say the same tpa message with [playerName](not the sender of the command but the first argument). Therefore, working in the same way as /tp.

Permission node `cmi.command.tpa.other`

**Comment by Zrips** [comment]
Okei.
