### ISSUE TITLE
/cmi launch - Launch to location not work

### ISSUE THREAD

**Issue by Baterka** [Zrips/CMI#6104]
**Description of issue:**
`/cmi launch loc:x:y:z` is not working. Player only slightly "bumps"... Not working even for 10 blocks distance...

Plug feature request: Allow more than 5 power in `/cmi launch`... I must use another plugin because of this limitation in CMI

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
NO ERROR
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
NO RELEVANT CONFIG
```

---

**Cmi Version (using`/cmi version`): 9.0.2.9** 

**Server Type (Spigot/Paperspigot/etc): AirplanePurpur 1.17.1** 

**Server Version (using `/ver`): AirplanePurpur version git-AirplanePurpur-31 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2040bab on HEAD)**

**Comment by Zrips** [comment]
Should be working more properly with next update
