### ISSUE TITLE
Economy bound at 92q

### ISSUE THREAD

**Issue by zFrank03** [Zrips/CMI#6105]
**Description of issue:**
Each time the server is restarted, the players' balance returns to 92233720368547760 (92.23Q)

**Cmi Version (using`/cmi version`):** 
CMI 8.8.1.5

**Server Type (Spigot/Paperspigot/etc):** 
Yatopia 1.16.5-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 
1.16.5

**Comment by levtey** [comment]
Outdated, using a discontinued server software, no other info about `/cmi version`... don't know what you're expecting.

**Comment by CloudeLecaw** [comment]
I may wants more. (We dont even know what his setting for max values is + he may not know that currently he cant use shorts like qq

**Comment by Zrips** [comment]
@zFrank03 
Will issue update to allow such huge numbers. But you will need to update to latest version.
