### ISSUE TITLE
No way to show percent sign in chat formatting

### ISSUE THREAD

**Issue by levtey** [Zrips/CMI#6108]
**Description of issue:**
While trying to use a literal percent sign in `Chat.GeneralFormat`, it always disappears and tries to get processed. I have tried a Javascript expansion placeholder that returns a percent sign, I have tried the unicode equivalent, everything gets removed. It would be nice if there was a way to have a percent sign in the formatting, maybe with `\%` or something similar?

---
`  # Used for simple chat messages. Optional variables: {displayName} {world} {prefix} {suffix} {group} {shout} {message}. Supporting PlaceHolderAPI variables like %player_server%
  GeneralFormat: '&7[&e%&7]&f {displayName}&7:&r {message}'`

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/60494179/131569747-5ad47ee5-410b-4c22-b76f-d6a268b6e304.png)

**Server Version:** `Purpur version git-Purpur-1356 (MC: 1.17.1)`

**Comment by Zrips** [comment]
Should be resolved with next build
