### ISSUE TITLE
cmi reload reloads 2 times?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6112]
on reload we see the reload meassge two times with different timings
one in english - one in the language we use (de)

![Snag_20915d3](https://user-images.githubusercontent.com/12080017/131753349-543f7801-5705-4528-9e3b-99ef7d9eae92.png)

![Snag_20a111b](https://user-images.githubusercontent.com/12080017/131753440-b32aa993-7bd3-4909-811b-8b5ea07f5909.png)

Here u see the console where u can see the 2 meassages too..well in console its ok - but i think its an issue that you also see both ingame

![image](https://user-images.githubusercontent.com/12080017/131807220-9871f05e-787a-4159-838c-0e721a0a1766.png)

**Comment by Zrips** [comment]
First one is for CMILib plugin and second for CMI. With recent updates CMILib and CMI gets a reload just to avoid confusion why some things dint take effect when reloading. Will add better indication which plugins locale got reloaded with next update.
