### ISSUE TITLE
Players with /god can hit mobs.

### ISSUE THREAD

**Issue by rmalca** [Zrips/CMI#6113]
**Description of issue:**
Players with /god cannot hit players but can hit mobs. 

---

**Cmi Version (using`/cmi version`):** 9.0.2.9

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Paper-236 (MC: 1.17.1)

**Comment by Zrips** [comment]
Will add separate config option to control this with next update
