### ISSUE TITLE
cmi spawn bypass 

### ISSUE THREAD

**Issue by ItLucifer-MRPG** [Zrips/CMI#6119]
Hi, Ive tried to make a hub server for my bungeecord network, and I've noticed that when a players is OP'd or has the "*" permission that they ignore the cmi spawn command when its ran for them, or by console. I've looked through the website and cant see the permission that may be giving them a bypass to the command. Can anyone help?

**Comment by CloudeLecaw** [comment]
you need to negate the permission for the bypass for OPs and * ppl
Permission is **_cmi.spawnonjoin.bypass_**
