### ISSUE TITLE
warn bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#612]
![image](https://user-images.githubusercontent.com/5382252/42693213-f950d566-86e0-11e8-9ecf-6ed22565ef5e.png)

Use /cmi warn
Will cause ID judgment error

**Cmi Version (using`/cmi version`): 7.8.11.2

**Server Type (Spigot/Paperspigot/etc): paper

**Server Version (using `/ver`): 1.12.2

**Comment by p82183645** [comment]
and
/cmi sethome 家   ( bug)
show Invalid name 

Previous versions can use Chinese or other characters
not now
Can fix this problem

**Comment by LogGits** [comment]
@Zrips this could be `i18n` support.
