### ISSUE TITLE
Add clickable holograms to CMI's API

### ISSUE THREAD

**Issue by Raesak** [Zrips/CMI#6120]
Can clickable holograms be added to the API?

A recent update for the Lands plugin includes a clickable holograms feature. It supports HD but is stated that it doesn't with CMI because clickable holograms isn't in the API, even though CMI itself has interactable holograms.

**Comment by Zrips** [comment]
CMIHologram#setInteractable(boolean interactable)
Maybe dev looked for clickable and not for interactable. But this is what you need, simply set to true and refresh hologram and its clickable now. 
CMIHologram#setCommands(List<String> commands) 
would be second one to define commands we should perform when hologram is clicked.

**Comment by Angeschossen** [comment]
Would it be possible to implement a method where we can set for example a Consumer<Player> instead (something that gives us the ability to execute a runnable with the player that clicked as the parameter). Unfortunately commands is not what we need in this case.

**Comment by Zrips** [comment]
@Angeschossen 
With next update you can use this method
```
	    CMIHologram h = new CMIHologram(String, Location) {
		@Override
		public void onInteraction(Player player, CMIInteractType type) {

		}
	    };
```
So you will have player who interacted and interaction type which is triggered when player click on hologram. So no need to use commands.

**Comment by Angeschossen** [comment]
Awesome, thank you

**Comment by Angeschossen** [comment]
I'm using this code. The hologram appears, but is not clickable. Any idea why?

````
            hologram = new CMIHologram(getHoloId(id), new CMILocation(location)) {
                @Override
                public void onInteraction(Player player, CMIInteractType cmiInteractType) {
                    onClick.accept(player);
                }
            };

        hologram.setShowRange(16);
        hologram.setLines(lines);
        api.addHologram(hologram);
        hologram.update();
