### ISSUE TITLE
/fly enabled on teleport

### ISSUE THREAD

**Issue by elenyi** [Zrips/CMI#6122]
/fly is being enabled for players who travel from the nether/end and into the overworld. This can happen through portals or the use of /home or /warp as well. It does not happen when travelling from the overworld to the nether/end.

CMI Version 9.0.2.10

Paper server, version 234

**Comment by BambuiZepelin** [comment]
I think I might have fixed this issue assuming you are also using the Tempfly plugin.

In the config you might want to change this:
  fly_override_permissions:
    - 'essentials.fly'
    - 'cmi.command.fly'
    ........
    # If true a user will start flying again when they no longer have flight requirements so long as their flight is enabled.
    # Example;
    # - A user flies into a disabled region and loses flight.
    # - If auto_fly is true they will fly again automatically without needing to use the fly command.
    auto_enable: false
    
I am guessing that this happens because I have set a region in nether, but it might also not. For me, it seems to have fixed the issue.

**Comment by elenyi** [comment]
No, I'm not using Tempfly plugin. I found a way to disable it but its still inconvenient for my staff members to re-enable god/fly when changing dimensions

**Comment by levtey** [comment]
I have had the same issue on my server, and have seen quite a few people report it. I don't think it has anything to do with `/cmi flyc`, but I do know that players randomly gain fly when switching worlds.

**Comment by levtey** [comment]
> No, I'm not using Tempfly plugin. I found a way to disable it but its still inconvenient for my staff members to re-enable god/fly when changing dimensions

The workaround I've found for this for now is to use the following in `eventCommands.yml`:
```
playerWorldChange:
  Enabled: true
  Commands:
  - delay! 0.1
  - perm:cmi.command.fly@! cmi fly [playerName] false -s
```
This way only players without the permission to fly will have theirs disabled.

**Comment by Zrips** [comment]
Fly mode can be enabled by multiple plugins, most common ones are multiverse relating ones. I cant really debug this issue if its really not known to originate from CMI. You could have had world limits enabled which can enable/disable fly modes depending on into which world you are switching to, which would explain why in some situations its not an issue but in others it is. Will make some changes in code, but at this point will have to close this ticket. If issue persists with next update, please try testing it out with CMI only just to make sure that issue originates from it and not another plugin and report back.
