### ISSUE TITLE
$1 is ignored when part of a placeholder + used from console

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6123]
here my Example: 
```
  pingtest:
    Cmds:
    - perm:cmi.command.customalias.ping@! check:$1==null! cmi broadcast !&cDu musst einen Spielernamen als Ziel hinzufügen.
    - check:$1!=null#! asConsole! cmi usermeta $1 add pingponggewinn %cmi_random_1_3% -s
    - check:$1!=null! asConsole! cmi usermeta $1 list
    - check:$1!=null! asConsole! cmi broadcast !die letze Nummer ist %parseother_{$1}_{cmi_user_meta_pingponggewinn}%
    - cmi broadcast !1. %parseother_{$1}_{cmi_user_city}%
    - check:$1!=null! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%==1! cmi broadcast !1
    - check:$1!=null! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%==2! cmi broadcast !2
    - check:$1!=null! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%==3! cmi broadcast !3
    - check:$1!=null! asConsole! cmi usermeta $1 remove pingponggewinn -s
```

you should see some broadcasts 
- the metalist that shows the saved metas -> works
- the meta of $1 with parseother -> no result
- an other meta of $1 with parse other -> no result

 i also tried %cmi_lastrandom_$1% -> no result

may this happens just when got executed from Console?....
or is this a new general issues with $arg when used from console? :3

It looks like $1 cant be shown anymore from console when its part of a cmi placeholder

Result as picture:
![image](https://user-images.githubusercontent.com/12080017/131989105-a4187f17-7657-4240-8834-d70d92ac776b.png)

![image](https://user-images.githubusercontent.com/12080017/131989193-3eaa491c-99d7-40d6-aab4-ce4936b8006f.png)

**Comment by Zrips** [comment]
hard to say, but it seam to be working correctly for me. Getting correct results from your example when performed from console or ingame. make sure that %parseother_{Zrips}_{cmi_user_meta_pingponggewinn}% actually returns value when you try parse it with papi or CMI

**Comment by CloudeLecaw** [comment]
i found a no solution but we decied to just do it ingame, where it works fine.
the pharse check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}% was working fine but the,
check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%==1! was not working from the console

For now we only use this custom alias from ingame. then it works fine.
Maybe someone find a reason or solution why the check did not worked from console
(no matter if the value was 1 2 or 3 - the command was not executed no matter if it was 1 2 or 3

**Comment by Deimosssss** [comment]
Hello, I have the similar problem with parse placeholders and $1, $2 in them. But I have a little bit different problem. As you wrote, when command are triggered ingame, works fine. It also works fine for me, when I triggered command in console.
Problem is, when command triggering any third party plugin like MineBlocks or DeluxeMenus - that's not depend. In this case parseother placeholder with $X not working well. I didn't find any fix for this problem.

It must be a problem from CMI side.

**Comment by CloudeLecaw** [comment]
> Hello, I have the similar problem with parse placeholders and $1, $2 in them. But I have a little bit different problem. As you wrote, when command are triggered ingame, works fine. It also works fine for me, when I triggered command in console. Problem is, when command triggering any third party plugin like MineBlocks or DeluxeMenus - that's not depend. In this case parseother placeholder with $X not working well. I didn't find any fix for this problem.
> 
> It must be a problem from CMI side.
but thats problem of the thridparty plugin^^
the way how specilized commands work only counts for cmi itslef. we cant guarantee for the workage of other plugins
