### ISSUE TITLE
Wrong value in %cmi_worthc_sell_cobblestone%

### ISSUE THREAD

**Issue by rmalca** [Zrips/CMI#6125]
**Description of issue:**
%cmi_worthc_sell_cobblestone% and %cmi_worthc_buy_cobblestone% return the same value (15.0).

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
worth:
  COBBLESTONE: 3.0;15.0
```

---

**Cmi Version (using`/cmi version`):** 9.0.2.10

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Paper-243 (MC: 1.17.1)

**Comment by Zrips** [comment]
Will issue a fix with next build
