### ISSUE TITLE
/prewards not showing entries above 14 days

### ISSUE THREAD

**Issue by FrontierPixelmon** [Zrips/CMI#6127]
**Description of issue:**

Any entries in playtime rewards above _**PayFor: 1209600**_ or **14 Days** does not show in the list when running the command.

**Cmi Version (using`/cmi version`):** 9.0.2.10

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** git-Paper-233

**Comment by Zrips** [comment]
You might want to increase this value
```
PlaytimeRewards:  ​
 ​OneTimeAmount: 2
```
to something  more appropriate for your situation. We are not showing entire list at once by default, just to avoid overflowing entire chat with full reward list.
