### ISSUE TITLE
CMI Hologram error in plugin VoidChest

### ISSUE THREAD

**Issue by MrHarebug** [Zrips/CMI#6128]
**Description of issue:**
Plugin VoidChest use Hologram to display info. When player place chest plugin gives an error.
Developer of VoidChest told me it is bug in CMI.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Could not pass event BlockPlaceEvent to VoidChest v1.8.4
java.lang.NoClassDefFoundError: com/Zrips/CMI/Containers/CMILocation
```
---
**Cmi Version (using`/cmi version`):** 
9.0.2.10

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
git-Paper-786 (MC: 1.16.5)

**Relevant plugins (Delete if this isn't needed):**
VoidChest

**Comment by Zrips** [comment]
Its not CMI bug, its VoidChest using outdated API. Most things moved to CMIlib with 9.x version which caused this error.
