### ISSUE TITLE
[Suggestion]Could tp/warp/tpa/home command support bungeecord?

### ISSUE THREAD

**Issue by smartmadio** [Zrips/CMI#613]
**Description of issue or feature request:**
Could tp/warp/tpa/home command support bungeecord?That players could teleport between servers.

**Cmi Version (using`/cmi version`):** 
7.8.7.3
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.12.2-R0.1

**Comment by SeDark** [comment]
I was going to suggest this right now since I am currently using another plugin to teleport and create warps by bungeecord and it consume too many resources.

I would like you to add this to your already fantastic plugin.
