### ISSUE TITLE
Can't import plugin on server.

### ISSUE THREAD

**Issue by Sova1500** [Zrips/CMI#6130]
Hello, i can't import plugin on server. Version is 1.16.5 its not bungeecord

**Comment by Zrips** [comment]
What do you mean by "import"? You simply need to place plugin jar file into plugins folder and start your server

**Comment by CloudeLecaw** [comment]
> Hello, i can't import plugin on server. Version is 1.16.5 its not bungeecord

- [Place CMI into the pluginfolder](https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/)
- [Place CMILIB into the pluginfolder](https://www.spigotmc.org/resources/cmilib.87610/)
- [if your using Economy it would be good to use CMIEInjector](https://www.zrips.net/wp-content/uploads/2020/07/CMIEInjector1.0.2.3.jar) + [Vault ](https://www.spigotmc.org/resources/vault.34315/)   [or zrips modified vault version](https://www.zrips.net/wp-content/uploads/2020/07/Vault-1.7.3.jar)

plugin should run.
