### ISSUE TITLE
1.17 Shulker Backpack Client Inventory Desync

### ISSUE THREAD

**Issue by delbertina** [Zrips/CMI#6132]
**Description of issue:**

Seems like with 1.17 using the shulker backpack feature causes the client's inventory to become desynced. Did not experience this bug before updating to 1.17. This issue could also be causing mobs to be desynced for the player, but have not been able to reproduce this consistently.
[Video of Issue](https://drive.google.com/file/d/1YHqvBFVxl3HO0FPBYLmSBgT3VIqvRcuR/view)

---

**Steps to Reproduce**

- open shulker backpack by right clicking in inv or in hand
- close shulker
- then pick up items and desync may happen
- bug is experienced until reconnect
    - can be mitigated somewhat by updating inv via right click, move item, etc

---

**Cmi Version (using`/cmi version`):** 
9.0.2.10
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.17.1 Build#249
**Relevant plugins (Delete if this isn't needed):**
Luckperms 5.3.65 & Vault 1.7.3 (so the player has the permission to open the shulker backpack)

**Comment by Zrips** [comment]
There is some weird derping out in specific situations. It does work normally if you shiftclick while holding item, but would derp out if you did it from inventory directly. It does fix itself if you simply click inside inventory, but this looks more like internal minecraft issue as it still properly updates dropped items, it only fails to update inventory when you pick item, for some strange reason. 
Made some internal adjustments to resolve this issue for the moment from my end, but this needs to be properly fixed from minecraft side at some point.
