### ISSUE TITLE
GUI Minecraft Version: 1.12.2

### ISSUE THREAD

**Issue by MaxRubbel** [Zrips/CMI#6136]
**Description of issue:**

Hello, 
The most important first, I have no error or Configs!

In Minecraft version 1.12.2, the GUI's work only partially, especially the blocks have no naming and you have to guess what, what has a function. For example /warps. 

Sorry for my bad English and thanks for the effort and work :)

**Cmi Version (using`/cmi version`):** 
CMI Plugin Version: 9.0.2.10
CMILib: 1.0.3.7

**Server Type (Spigot/Paperspigot/etc):** 
Magma Hybrid Server (Bukkit/Forge)

**Server Version (using `/ver`):** 
Magma version 761933c-STABLE
API version 1.12.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Should be fixed with next CMILib release
