### ISSUE TITLE
[Request] Multiple pages for '/cmi getbook'

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#614]
`/cmi getbook` should support having multiple pages for long text files. Currently it just cuts off the text after it reaches the end of the first page.

**Comment by Zrips** [comment]
in general you should make custom text to properly fit books pages if its gonna be used in books. It more complicated to calculate where page end should be from the given text as we would need to calculate length of each line, how many lines it makes and at which point new page should start and then decide where to cut or transfer text to new page.
