### ISSUE TITLE
Jail Console Error

### ISSUE THREAD

**Issue by LucidAPs** [Zrips/CMI#6142]
Console error when trying to jail some users, it works fine when they are online but when offline it returns that error. For some users only.
https://nekobin.com/rumazesuga
This user for example gives me an error when I try to jail him when offline
![image](https://user-images.githubusercontent.com/42933023/132371805-109c0814-a234-4280-8768-8d8dc9f909e3.png)
I also get nothing when I do the command /info sophnkl when offline
![image](https://user-images.githubusercontent.com/42933023/132372191-32b8dea0-1b81-4c6c-9679-4c98dde58dde.png)
But when he is online it works fine
![image](https://user-images.githubusercontent.com/42933023/132372241-6e7333d3-6803-469d-9718-cd0ea7e3f96c.png)

![image](https://user-images.githubusercontent.com/42933023/132371188-4081e0ab-2cd3-4e66-ae96-b1e2c38d2b42.png)
![image](https://user-images.githubusercontent.com/42933023/132371232-61d0a951-8e34-444b-8d4e-0fdc09b2d683.png)

**Comment by Zrips** [comment]
Will be fixed with next CMI and/or CMILib update. Updating ether of those plugins will resolve this issue.
