### ISSUE TITLE
Bug on sell (infinite money)

### ISSUE THREAD

**Issue by rmalca** [Zrips/CMI#6147]
**Description of issue:**

By having any item in the offhand and using "/cmi sell item (for example emerald)" the player receives the money but the item is kept in the inventory allowing the player to sell the same item indefinitely. 

---

**Cmi Version (using`/cmi version`):** 9.0.2.10

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Paper-251 (MC: 1.17.1)

**Comment by Zrips** [comment]
Will be resolved with todays update
