### ISSUE TITLE
GUI Minecraft Version: 1.12.2

### ISSUE THREAD

**Issue by MaxRubbel** [Zrips/CMI#6148]
Hello,

I had already reported this [[BUG]](https://github.com/Zrips/CMI/issues/6136) 3 days ago. Unfortunately it is still present in the next version of CMIlib. 

Sorry for my bad English and thanks for the effort and work :)

Cmi Version:
CMI Plugin Version: 9.0.3.0
CMILib: 1.0.3.8

Server Type:
Magma Hybrid Server 1.12.2 (Bukkit/Forge)

Server Version:
Magma Version 761933c-STABLE
API Version Spigot 1.12.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
At this point i might need more details or maybe even actual server base files as i cant really reproduce this issue at this point so it could be caused by something else with your specific setup.

**Comment by MaxRubbel** [comment]
I found the error, my Magma version was the 761933c in this version it does not work. If I update it to the version: dd9991e7 it works fine now. 

Thank you anyway for the effort!
