### ISSUE TITLE
Error when use /cmi openbook

### ISSUE THREAD

**Issue by Mandress101** [Zrips/CMI#6158]
Error description:

When I use the command /cmi openbook in the console appear an error

---

Error immage: 
```
https://user-images.githubusercontent.com/67111984/132995658-854ff2be-ade2-468e-a6f2-353ab6713eb8.png


```

Cmi version: 9.0.4.1

Server Type: Spigot - 1.8.8 (git-Spigot-db6de12-18fbb24 (MC: 1.8.8))

Server version: git-Spigot-db6de12-18fbb24 (MC: 1.8.8)

**Comment by Zrips** [comment]
Will be fixed with next update
