### ISSUE TITLE
CMI New commands

### ISSUE THREAD

**Issue by Splashc** [Zrips/CMI#6159]
make command's to open work tables 
- smithingtable
- grindstone
- cartographytable
- loom
- stonecutter
- enchantingtable

this will be cool and usefull for server's that sell ranks!

and make its so if you use /glow and people have colord name's cus of luckperms they still can choose there glow color cus its just name color :|

**Comment by ItLucifer-MRPG** [comment]
I'm pretty sure, most if not all of those commands exist already, I know /loom and other were added recently

**Comment by Splashc** [comment]
what are these commands for it than ?

**Comment by ItLucifer-MRPG** [comment]
Check the changelog for version 9.0.4.0

**Comment by Zrips** [comment]
Commands got added but will only work with Paper type servers.
