### ISSUE TITLE
Claiming a kit with a full inventory causes items to be lost

### ISSUE THREAD

**Issue by rmalca** [Zrips/CMI#6167]
### Discussed in https://github.com/Zrips/CMI/discussions/6166

<div type='discussions-op-text'>

<sup>Originally posted by **rmalca** September 18, 2021</sup>
Please add an option so that when claiming a kit and the inventory is full, the items do not fall to the ground, instead show a message saying to free up space in inventory.</div>

Claiming a kit with a full inventory causes items to be lost without prior checking. 

https://user-images.githubusercontent.com/3759745/133896941-e960cdb5-dfb2-4e3e-b275-5c63e2cdddb8.mp4

PD:
Sorry for creating a discussion earlier but this must be a bug, the items should not be lost. CMI should check if there are enough slots and return an error message if there are not.

**Comment by mrfloris** [comment]
```yaml
# Handles kit listener, mainly to give out new player kit
# Applies for servers from 1.7.x and up
kits: true
```
in modules.yml, is kits set to true or false ?

Can you go to your console and type this and share the info?
```
ver
cmi version
```

I've tried to make a video but the size just goes over 10mb and can't include it, it showed me on 1.17.1 with latest cmi/cmilib and that just like forever that kits in survival mode and with the module turned on and a full inventory drop the items on the floor for me.

there's no perm that i know to disable this.

**Comment by rmalca** [comment]
/ver: git-Paper-263 (MC: 1.17.1)

/cmi version:
CMI: 9.0.4.0
CMILib: 1.0.3.9

As I show in the video I have disabled the option to drop the items to the ground in the hope that it will do a check of the available slots.

**Comment by Zrips** [comment]
Will issue a fix for this one with next build
