### ISSUE TITLE
Sleeping requirement not working

### ISSUE THREAD

**Issue by DarrienNN** [Zrips/CMI#6171]
**Description of issue: Sleeping requirement not working (Server have 30 players but when 1 player sleep dont need 50% players in server to sleep**

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## https://pastebin.com/mvbfK9bj  ##
#######################################
```

---

**Cmi Version (using`/cmi version`): https://pastebin.com/A9E58ayK** 

**Server Type (Spigot/Paperspigot/etc): PaperMC** 

**Server Version (using `/ver`): https://pastebin.com/ERL5rHyc**

**Comment by DarrienNN** [comment]
https://youtu.be/Sk5YghOCQ_k

**Comment by Zrips** [comment]
Will issue fix with next build
