### ISSUE TITLE
Placeholder for unclaimed kits

### ISSUE THREAD

**Issue by dwebeklint** [Zrips/CMI#6175]
Hello. 
I want to suggest adding a placeholder for the number of unclaimed kits. 
In example. Suppose a user has two out of four kits unclaimed. It will show the number two. 
If possible, add a variable to specify permission based. 
cmi_unclaimedkits_gold.rank
The good.rank is a permission for a rank in luckperms

**Comment by Zrips** [comment]
Will add with next update
