### ISSUE TITLE
Output modification of PlaceHolderAPI

### ISSUE THREAD

**Issue by FZDNSZYT** [Zrips/CMI#6186]
Can I modify the output of CMI's PlaceholderAPI? How should I modify it?

**Comment by FZDNSZYT** [comment]
I hope to realize the specific display of information, not just TRUE and FALSE

**Comment by FZDNSZYT** [comment]
This will be more intuitive in the display of tablist and player titles

**Comment by Zrips** [comment]
Returned values can be modified in locale file. Other than this you hardly will have any way to intercept translated placeholder and change that. When we have placeholder on CMI side then CMI will check if its internal CMI placeholder or should it be sent to PAPI for translation, if its internal then we simply translating it to correct value and returning to method which requested this. if its for PAPI to handle then it will send to the plugin which needs to translate it and sends returned value back to requester. I'm not aware of any simple way to actually intercept this and perform your own translation of already translated placeholder.

**Comment by FZDNSZYT** [comment]
> 
I searched many times, but did not find the value output by PlaceHolderAPI. And the items he can customize. Can you point it out specifically for me in the configuration file?

**Comment by FZDNSZYT** [comment]
> 
I searched many times, but did not find the value output by PlaceHolderAPI. And the items he can customize. Can you point it out specifically for me in the configuration file?

**Comment by FZDNSZYT** [comment]
> Returned values can be modified in locale file. Other than this you hardly will have any way to intercept translated placeholder and change that. When we have placeholder on CMI side then CMI will check if its internal CMI placeholder or should it be sent to PAPI for translation, if its internal then we simply translating it to correct value and returning to method which requested this. if its for PAPI to handle then it will send to the plugin which needs to translate it and sends returned value back to requester. I'm not aware of any simple way to actually intercept this and perform your own translation of already translated placeholder.

I searched many times, but did not find the value output by PlaceHolderAPI. And the items he can customize. Can you point it out specifically for me in the configuration file?

**Comment by FZDNSZYT** [comment]
> Returned values can be modified in locale file. Other than this you hardly will have any way to intercept translated placeholder and change that. When we have placeholder on CMI side then CMI will check if its internal CMI placeholder or should it be sent to PAPI for translation, if its internal then we simply translating it to correct value and returning to method which requested this. if its for PAPI to handle then it will send to the plugin which needs to translate it and sends returned value back to requester. I'm not aware of any simple way to actually intercept this and perform your own translation of already translated placeholder.

Thank you very much, I need it so much.
