### ISSUE TITLE
/fly and /god enabled on teleport

### ISSUE THREAD

**Issue by elenyi** [Zrips/CMI#6192]
Reopening a ticket as suggested when CMI was updated. /fly and /god are being issued when players teleport from the nether/end and into the overworld. It does not work the other way around. I only have CMI installed on the server I tested this on so it is not another plugin causing this issue.

**Cmi Version (using`/cmi version`):**   9.0.4.2

**Server Type (Spigot/Paperspigot/etc):**     Paper

**Server Version (using `/ver`):** Paper ver 234

**Comment by Zrips** [comment]
What world limits do you have set in cmi config file?

**Comment by elenyi** [comment]
WorldLimits:
  # By setting to true fly and gamemode limitations per world will be aplied for player on world change if they dont have appropiate permission node
  Enabled: false
  # World list with default game modes
  # If player will have cmi.worldlimit.gamemode.bypass permission node, game mode wont be changed
  # Possible modes: creative, survival, adventure, spectator,

**Comment by Impactic48** [comment]
I also have a problem with players randomly being put in god mode, it doesn't happen on teleport and I can't figure out what's triggering it. When I do /info [player] it shows them in god mode but when I do /god [player] it says Godmode enabled like they just got it for the first time... Not sure what could be causing this issue.

**Comment by nhanledev** [comment]
I am having this issue on all of my servers, with different mode and plugins, and it turns out to be CMI's problem

**Comment by elenyi** [comment]
Are there any updates to this? I have this set in my eventcommands.yml so it wouldn't affect my staff members, however, it doesn't seem to work anymore to prevent anyone from flying.

> playerWorldChange:
>   Enabled: true
>   Commands:
>   - perm:cmi.command.god@! cmi god [playerName] false -s
>   - perm:cmi.command.gm.spectator@! cmi fly [playerName] false -s

**Comment by Kapitowa** [comment]
I can confirm that, it need to be fixed.

**Comment by Kapitowa** [comment]
sorry, I found problem in server.properites 
![image](https://user-images.githubusercontent.com/62211966/143627769-89d17d8d-697f-4702-8765-1b5f69b600e0.png)

**Comment by jAvEE-fr** [comment]
hello same issue, but Fly only
"WorldLimits:
Enabled: false" (in CMI config.yml)
and
"allow-flight=false" (in server.properties)

and nothing unusual for My-World

Can you help me? only some people have fly reactivated when they go from world to another world

**Comment by Zrips** [comment]
Should be resolved with next update
