### ISSUE TITLE
NPE after update to CMI 9.0.4.3

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#6195]
**Description of issue:**

Not sure if this is a bug or question, but I'm getting some error spam roughly every 15-30 seconds, strangely on only one of my servers, after the update to CMI 9.0.4.3. Notably this is not the default server and is possibly getting it more because it's more popular at the moment. Thanks!

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://gist.github.com/mercurialmusic/9ddcb983579439802280ae9f51e235e9

---

**Cmi Version (using`/cmi version`):** 9.0.4.3, with CMILib 1.0.3.10 and CMIB 1.0.1.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-Paper-278

**Comment by Zrips** [comment]
Gets a fix with next build
