### ISSUE TITLE
Join server as vanished

### ISSUE THREAD

**Issue by Bloodlex** [Zrips/CMI#6198]
Hey,

Could you please add a feature to join server as vanished? Thank you 🙂 .

**Comment by Bloodlex** [comment]
Already found it, translation in Polish is not correct.

**Comment by mrfloris** [comment]
You can go to console and type: `cmi vanish playername` it will toggle between made visible, is now invisible. They won't see you join then.

**Comment by CloudeLecaw** [comment]
Also you can add this as JoinEvent with check if your in vanish or not. Or you can simply vanish and logout with a vanish fakelogg to let all think u logged off.

**Comment by Zrips** [comment]
If you are vanished then you will join as vanished. I can add a permission node which is set to the player would force vanish mode on them on join even if they dont have vanish enabled before logging of.
