### ISSUE TITLE
BUG: cmi.worldlimit.fly.bypass Not working,

### ISSUE THREAD

**Issue by RustyDagger** [Zrips/CMI#620]
**Description of issue or feature request:**
Every thing is explained and tested in the video below,
https://youtu.be/6QdeO5NP45k

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
In video,
```

**Cmi Version (using`/cmi version`):** 
[Wed, 18. Jul 2018 02:09:08 AEST INFO] --------------------------------------------------
[Wed, 18. Jul 2018 02:09:08 AEST INFO] CMI plugin version: 7.8.11.0-> 7.8.12.0
[Wed, 18. Jul 2018 02:09:08 AEST INFO] Server version: Paper(1470) 1.12.2-R0.1-SNAPSHOT
[Wed, 18. Jul 2018 02:09:08 AEST INFO] Vault version: 1.6.10(+)
[Wed, 18. Jul 2018 02:09:08 AEST INFO] --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Paper ( not really relevant can confirm it being an issue on Spigot also. )

**Server Version (using `/ver`):**
Again not relevant but here it is any way. 
[Wed, 18. Jul 2018 02:08:23 AEST INFO] This server is running Paper version git-Paper-1470 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by RustyDagger** [comment]
O hey so Just realized my Head admin reported this before and was ignored/swept away,
here is the ticket.
https://github.com/Zrips/CMI/issues/344

**Comment by LogGits** [comment]
We didn't ignore the issue, there wasn't a response for over a month.

Good catch with the worldlimits permission bug. Out of curiosity (as I don't have access to my comp for a while) when worldlimits disable your fly on rejoin, can you double tap space to fly again? or does it force you to turn it off and back on?

**Comment by RustyDagger** [comment]
yes its an annoying bug, seems like a quick easy fix to me.

**Comment by Zrips** [comment]
Will be addressed with next build. Tho could not successfully reproduce issue, but did some changes to possibly address this issue you are having currently.

**Comment by RustyDagger** [comment]
Not fixed. 

User logged in with the permission node cmi.worldlimit.fly.bypass Set to true and Fly was STILL Turned off Because of the WorldLimit the expected result is that the USER would be left flying where they logged out. 

I BET its still checking the wrong permission node for this feature. about to test.

From the looks of the change log you completely missed the cause of the issue.

The permission check is WRONG. its checking the WRONG permission node.

**Comment by RustyDagger** [comment]
`30/09/2018 10:39 AM: [MC]: [10:39:34 INFO]: [LP] Verbose logging enabled for checks matching RustyDagger & CMI.
30/09/2018 10:39 AM: [MC]: [10:39:48 INFO]: RustyDagger lost connection: Disconnected
30/09/2018 10:39 AM: [MC]: [10:39:48 INFO]: [*Console*] Rusty Has Logged out.
30/09/2018 10:39 AM: [MC]: [10:39:48 INFO]: [DiscordSRV] Player RustyDagger quit with silent quitting permission, not sending a quit message
30/09/2018 10:39 AM: [MC]: [10:39:48 INFO]: [LP] VB > RustyDagger - cmi.messages.disablequit - undefined
30/09/2018 10:39 AM: [MC]: [10:39:48 INFO]: [LP] VB > RustyDagger - cmi.messages.disablequit - undefined
30/09/2018 10:40 AM: [MC]: [10:40:04 INFO]: UUID of player RustyDagger is d4158f6b-0164-4ced-ae64-d95cf4539132
30/09/2018 10:40 AM: [MC]: [10:40:05 INFO]: [LP] VB > RustyDagger - cmi.worldlimit.god.bypass - true
30/09/2018 10:40 AM: [MC]: [10:40:05 INFO]: [LP] VB > RustyDagger - cmi.worldlimit.gamemode.bypass - true
30/09/2018 10:40 AM: [MC]: [10:40:05 INFO]: [LP] VB > RustyDagger - cmi.worldlimit.fly.bypass - true
30/09/2018 10:40 AM: [MC]: [10:40:05 INFO]: [Rusty] has joined the game.
30/09/2018 10:40 AM: [MC]: [10:40:05 INFO]: [LP] VB > RustyDagger - cmi.messages.disablelogin - undefined
30/09/2018 10:40 AM: [MC]: [10:40:05 INFO]: [LP] VB > RustyDagger - cmi.messages.disablelogin - undefined
30/09/2018 10:40 AM: [MC]: [10:40:05 INFO]: [LP] VB > RustyDagger - cmi.command.fly.safelogin - undefined
30/09/2018 10:40 AM: [MC]: [10:40:05 INFO]: [LP] VB > RustyDagger - cmi.seevanished - true
30/09/2018 10:40 AM: [MC]: [10:40:05 INFO]: [LP] VB > RustyDagger - cmi.versioncheck - undefined
30/09/2018 10:40 AM: [MC]: [10:40:05 INFO]: [DiscordSRV] Player RustyDagger joined with silent joining permission, not sending a join message
30/09/2018 10:40 AM: [MC]: [10:40:05 INFO]: RustyDagger[/121.45.190.51:56051] logged in with entity id 4220 at ([world]-3250.992392916333, 69.0, -647.413493370032)`

I logged out with fly mode on, When I logged back in I had both the gamemode bypass and the fly bypass I Still had my fly turned off and fell. The point of the bypass is so that it does not change my gamemode to the maps setting.  Its still doing that despite me having the bypass.
