### ISSUE TITLE
Interactive commands issue // CMI - Authme

### ISSUE THREAD

**Issue by SbirTeo** [Zrips/CMI#6200]
**Description of issue or feature request:**

I use interactive commands (armorstands) in my server hub. If a player is not logged in, he can click the interactive commands entity. They use cheats like Freecam or speed to click armorstands in very little time.

**Cmi Version (using`/cmi version`):** 
LATEST

**Server Type (Spigot/Paperspigot/etc):** 
paperspigot LATEST 1.17.1

**Comment by Zrips** [comment]
In general interactions like this one should be checked by anticheat plugin and ban should be given in no time. I cant ignore canceled interaction events. At best what i can do it add limitation in how often player can trigger interactable commands, but other than this you might want to look into some better anticheat plugins.
Next update.
