### ISSUE TITLE
NullPointerException: Cannot invoke "com.Zrips.CMI.Containers.CMIUser.isAfk()

### ISSUE THREAD

**Issue by archroot** [Zrips/CMI#6202]
---

https://pastebin.com/uTYz6t75

---
 CMI: 9.0.4.3 BungeeCord CMIB  SqLite
 CMILib: 1.0.3.10 
 Purpur 1.16.5-R0.1-SNAPSHOT

**Comment by LucidAPs** [comment]
I am having the same issue
https://nekobin.com/somatohuce

**Comment by CloudeLecaw** [comment]
> I am having the same issue
> https://nekobin.com/somatohuce

Your using 1.17.1 then you should change to latest paper instead of using the outdated puppur
With 1.17.1 Pupur has merged Into PaperMC so only PaperMC does exist anymore since 1-2 months

**Comment by levtey** [comment]
> With 1.17.1 Pupur has merged Into PaperMC so only PaperMC does exist anymore since 1-2 months

What? Tuinity merged with Paper, Purpur still exists.

**Comment by LucidAPs** [comment]
> > I am having the same issue
> > https://nekobin.com/somatohuce
> 
> Your using 1.17.1 then you should change to latest paper instead of using the outdated puppur
> With 1.17.1 Pupur has merged Into PaperMC so only PaperMC does exist anymore since 1-2 months

Lmao that info is so wrong on so many levels.

**Comment by CloudeLecaw** [comment]
Really? ..ok ;D

**Comment by Zrips** [comment]
Will issue fix with next release
