### ISSUE TITLE
/se command suggests existing text

### ISSUE THREAD

**Issue by Bloodlex** [Zrips/CMI#6203]
Hey,

/se command could suggest what is already written on this line in chat 🙂 like in EssentialsX with editsign

**Comment by mrfloris** [comment]
Already an option for ages
<img width="788" alt="Screenshot 2021-09-26 at 20 42 05" src="https://user-images.githubusercontent.com/28841349/134820188-a67898b4-2a07-4bc4-90ed-ddb91d13db34.png">
.

**Comment by CloudeLecaw** [comment]
Cmi does this allready. Look at a signnand do /cmi se you will se 1 to 4 for thw lines and if the sign isnwritten allready you see the full content of it in the chat.

**Comment by Bloodlex** [comment]
> Cmi does this allready. Look at a signnand do /cmi se you will se 1 to 4 for thw lines and if the sign isnwritten allready you see the full content of it in the chat. Your mistake was you started an other text allready. So do /cmi se (Tab) and u see its there allready.

Yes, you're right it works with /cmi se, but not with alias: /se 🙁

**Comment by CloudeLecaw** [comment]
Try alais.yml

**Comment by Zrips** [comment]
This is a thing already. You just need to enable alias for this command and you can tab complete ether entire sign text or specific lines if you provided line number. If that isint option for alias then it can be that another plugin which uses /se overrrides its tab complete. For now, its not a bug.
