### ISSUE TITLE
/nameplate Improvements

### ISSUE THREAD

**Issue by Raesak** [Zrips/CMI#6208]
Please give an easier option to reset the format when resetting all three fields.
In addition to: `/nameplate [playerName] -pref: -suf: -c:` we can also just use `/nameplate reset`

Add the ability to change the player's name the same way we set a prefix and suffix.

Add the ability to use hex color codes in the color part (or in the player name part if that feature is added).

Deny the command if invalid context is used:
For example when trying to use hex colors in the color part, it doesn't work or make any changes, but the command still runs. Or if the command format is just completely wrong after `/nameplate [playerName]`, it runs regardless.

EDIT:
Also make` /nameplate` display the player's current nameplate. At the moment there is no way for the player to see their own nameplate (except by using commands that players shouldn't have).

**Comment by Zrips** [comment]
Will add
