### ISSUE TITLE
"/nameplates" not resetting the name color.

### ISSUE THREAD

**Issue by Raesak** [Zrips/CMI#6209]
Minecraft: 1.17.1
Paper: 279
CMI: 9.0.4.4

When setting a prefix, suffix, and color (with for example: `/cmi nameplate [playerName] -pref:Test1 -suf:Test2 -c:&7`

When resetting the formatting using: `/cmi nameplate [playerName] -pref: -suf: -c:`

The prefix and suffix resets but the color does not.

**Comment by Zrips** [comment]
Will make a fix for it with next update
