### ISSUE TITLE
✌ [Bugs & Suggestions] ✌

### ISSUE THREAD

**Issue by Gasha666** [Zrips/CMI#621]
**@Zrips Please when you find free time in future you can fix and maybe add some of those things..Thanks** ❤

### Bugs:

- There is bug in last 30 version with furnace displaying players that they have limitation to set maximum 10 furnace and they are able to set infinity it displays example 79 / 10 , please fix that, it just giving them message not preventing them for placing new furnaces, you could also add for some other items that limitations its very useful

- There is problem is when attaching multiple commands on item when i do it shows multiple lores line
of usage, instead of one lore line that shows how much uses i still have, it displays like this 

You have 5 uses left
You have 4 uses left
You have 3 uses left
You have 2 uses left
....

it should remove previous lores, not show all previous after usage
i think you fixed it in past but it i test it now and there is problem 
maybe you fixed it when player using single attached command, i was testing with multiple commands 
i really need it, please i beg you try to fix it

- Vanish (when you are in vanish you get night vision) when you turn of vanish it turn also night vision
i type /cmi vanishedit and turned of nightvision but still after removing vanish also nightvision removes
i have on my whole server nightvision system for lightning and that vanish thing is causing little troubles

- Bug with armor stand legs i already send you few pictures on PM i can rotate torso,head,arms..but there is problems with legs.. (I wanted to make armorstand looks like laying)

- Not able to use symbols on /cmi editctext, in locale some of line are ListUpSymbol it have symbol in name but not really supporting usage of symbols, i am able to use symbols on other place in CMI, but not there (i tried all symbols, i wanted to use arrow up and down) like this something like ↑ ↓ 
now i must use text looks little bit wierd but no big problem

    For custom recipes i can only set amount of 1 if i put example that it requires stack, it will only accept it as 1..i would be much better if accept amount i actually set

- Bug with attach command displaying again lore multiple times
ability to open links when someone send in /cmi helpop and /cmi staffmsg

- When i place armorstand to hold example blazerod in hand and then look in armorstand and type /cmi armorstand it gets that blazerod from armorstand instead of opening amorstand editor, then after typing again without armorstand holding it, then it opens (it should open armorstand editor instead of getting item that armorstand is holding)

- i set auto messages with no prefix using /cmi msg %playername% !text but take start making issues
players are in conversation and that auto-broadcasting messages that i set displays and when they answering they buddy using /r or /reply it send message to server instead of player (i know why its happening because server send last message, but it would be cool and useful if you can do something about it)

- Bug related when using sit from CMI with your Mob Farm Manager plugin
example player limits is to place 10 armorstands, and if i create in region 10 armorstands or more they cannot use /cmi sit command, getting command that there is already 10 armorstands, they are getting very confused they don't know that armorstand system is used for siting..please make to not count /cmi sit on armorstand limitation by Mob Farm Manager

### **Suggestions:**

- When staff using /cmi mute it should require reason, now there is no ability to add reason for muting  player, please add abiltity to define reason when muting player, same for ipban

- Ability ingame command to send public message with hoverable text and (clickable) when player press to execute certain commands (that would be useful) here is explanation/example

- /cmi hm= hover message -ht=hover text -hc = hover command
- /cmi hm &cSpawn -ht:Click here to teleport to spawn -hc:cmi spawn [playerName];cmi msg [playerName] !&aYou are successfully teleported to spawn&c!

- Please add for socialspy to exlude certain users with permission
So when someone is chating with OP (owner) something privately in msg other staff team should not see it
Neither my messages neither that message that is send to me (is that possible for you to create?)
- Maybe ability to block/remove certain default minecraft recipes
- Ability for skins to use previous skin (i didn't meant on original player's skin) i think just on previous skin that player had
- Maybe ability to control player while riding him (move with W-A-S-D)
- Maybe Auto-Walk, or Auto-Jump or /lay command that would be fun and cool
- Ability to use more then 1 item when creating new recipes
- Anti-xray alert (it would be good since there is already /cmi stats where you can see all blocks you mined)
- Ability to keep certain chests visibly open
- Ability to execute punish command if player left during fight with other player
- Timer for actionbar, maybe for title/subtitle message too? (is that possible or its hardcoded)
-  Please add -f (force) for focing command on OP that bypass sudo by default
i create many commands where i use sudo, its working for everyone but not for me, only way that works if i negate permission, but that makes other issues
- Add in MobFarmManger limitation for hoppers,pistons,stickypistons,signs & shulker box

**Comment by TopCZE** [comment]
"You can only sleep at night" 36/5000 It's not from CMI but from vanilla minecraft

**Comment by Gasha666** [comment]
Okay, i don't know how i didn't saw that message earlier, i notice it recently i thought that's the message from CMI
But its actually from vanilla, everything is okay then..

**Comment by CloudeLecaw** [comment]
https://github.com/Zrips/CMI/issues/639
https://github.com/Zrips/CMI/issues/640

**Comment by Gasha666** [comment]
@CloudeLecaw I don't understand what with those two reported errors? i don't have them, those are on 1.13, i'm still using 1.12.2 don't have plans to upgrade on 1.13 for few more months since 1.13 is not very stable yet, but soon will be..so i will update for sure in few months when 1.13 become very stable

I don't have any errors by CMI, i still believe that CMI is by far the best plugin ever..
After Zrips find time to fix small bugs i mention and add few small things it will become even better..
He fixed/added almost all my suggestions in past i appreciate that very much!
I'm using 7 his plugins and i recommend his plugins everyday to everyone, thats at least what i can do..
I am also interested in donating for this plugin, there is no plugin outhere with more potential then CMI
I really hope that Zrips won't stop developing, cause his plugins are really something special :)
It would be awesome when developing would be his real full time job, i'm sure that there is alot of people on spigot that would pay him tons of money to keep working and working on his plugins!

i know that if i didn't already spend few thousands of dollars on minecraft i would rather hire someone very skilled like zrips and pay him example 2000$ to create all plugins for me (2-3 plugins like CMI could replace all plugins on any server)

**Comment by CloudeLecaw** [comment]
um sorry Gasha666, u have this thread no good title

u called it Bugs and Suggestions
So ist like a collecotrthread for Bugs and Suggetions of all Kinds,
so i posted two Bugs that exist with current release 🥉 

Sorry if i missunderstood it..my it would be good to Change the title more speciffic because
all owner here come to the GitHub to post their issues, Bugs, and give suggestions.

**Comment by LogGits** [comment]
Just for the future, could you please make a seperate issue thread per issue. This way it is easier for us to track and manage.

**Comment by Gasha666** [comment]
45 days later is there any news @Zrips? when you will be able to fix those well known reported bugs?

**Comment by CloudeLecaw** [comment]
Well coreext. Me, but i think the 1.13.1 support shout take first place now 😎

**Comment by Gasha666** [comment]
Okay, there is no problem with waiting, he just needs to give us more informations, how long do we need to wait for those bugs to be fixed

**Comment by Zrips** [comment]
Bunch of stuff going on in my real life which takes allot of time, will try to shuffle things around to find some time and address issues. They got piled up after 1.13 release which introduced crap load of them.
