### ISSUE TITLE
(not a bug, but it's confusing people) Move Command Filtering to ChatFilter.yml as well?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#6215]
Maybe there's a technical limitation why command filtering is still in config.yml, if that's the case, feel free to close this ticket. However, if it was possible to take away a bit of confusion and add consistency, could command-filtering be moved to chatfilter.yml and be put below message-filtering (before caps-filtering)? This would help, thank you. 
<img width="1121" alt="Screenshot 2021-09-29 at 13 22 49" src="https://user-images.githubusercontent.com/28841349/135259440-a8334a79-5773-41e0-ac93-35985b34b019.png">
<img width="1117" alt="Screenshot 2021-09-29 at 13 23 01" src="https://user-images.githubusercontent.com/28841349/135259451-c1d987ec-c975-421b-a71a-b1b8c3aed8ba.png">

**Comment by CloudeLecaw** [comment]
You know its a Suggestions ;D
.
But to be honest would be a nice idea to take this also to filters.

Only little eagle in my eyenisbthe word "ChatFilter".
 Does a Chatfilter means the same like a command filter?

Technicly then this is no chat filter anymore..
Then it would be a InputOutputFilter....
.

**Comment by mrfloris** [comment]
After not having it in the file for a year+, I don't feel like it's really needed, closing :)
