### ISSUE TITLE
Error on /cmi blockinfo

### ISSUE THREAD

**Issue by Raesak** [Zrips/CMI#6216]
Minecraft: 1.17.1
Paper: 282
CMI: 9.0.4.5

When I use the command `/cmi blockinfo`, this error prints to the console:
https://pastebin.com/jEvewKQm

**Comment by gecko10000** [comment]
_Everything is cave vines_ :P I'm sure he'll fix this soon.

**Comment by Zrips** [comment]
Will fix with next update
