### ISSUE TITLE
Launch Command issues

### ISSUE THREAD

**Issue by xmorose** [Zrips/CMI#6225]
**Description of issue:**
Launch command issues;
You cannot use Power 4.5. You CAN use 5.5 but not 4.5 and any other 4.x numbers. Also using loc: has a distance cap, no matter how high the distance is you set up, you always travel the same amount of blocks. If you reenter the command you travel further, but the firts one is, at least in my case like half the distance, ofc it varies how you test it.

Also, you cant use power / angle when you use loc: not sure whether thats a bug though. I was trying whether i could use loc and just a higher power since the distance is simply not enough but nope. 
Best would be if CMI could calculate the trajectory path to the block so you land exactly on the loc: block, not sure whether thats possible tho :p 
Thanks!
---

---

**Cmi Version (using`/cmi version`):**  CMI 9.0.4.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-Paper-188

**Comment by Zrips** [comment]
Will fix 4-5 values issue. For location jump, its more complicated as we have to calculate specific angle and specific power you need to be launched to fly to exact destination. on top of this game is hard limited to max power you can be launched without ending up with some custom handling like we currently have above power level 4.

**Comment by xmorose** [comment]
Ah so thats why it does these multiple pushes right? I always felt like power level 5 and 6 always had one push and then 3 smaller ones or something. Is that what youre talking about here?

**Comment by Zrips** [comment]
Currently wit power above 4 we will perform multiple pushes every 2 ticks, which is around 100ms intervals. Game is limited in how fast player can move, so we cant just launch player into orbit with one push, we need to perform multiple of those for some amount of time.
