### ISSUE TITLE
PlayerJoinEvent doesn't recognize player's vanish at joining

### ISSUE THREAD

**Issue by Bloodlex** [Zrips/CMI#6226]
**Description of issue:**

I write a plugin to add custom join and quit messages. I enabled lately added feature to enable vanish on join for moderators. I would like that a join message is not shown, when my moderators join with vanish enabled. I made a listener coupled with PlayerJoinEvent and I check if player has vanish using VanishManager from CMI.

I know I could achieve custom join messages using CMI, but I would like to have some other features like messages with click event which would write a nice greeting in a chat when other players click it for instance.

However, sometimes when one of moderators joins, event gets fired before vanish is executed (that is what I suppose that happens). This results in showing a moderator join message, although he has vanish and I checked in my listener that players should not receive this message if somebody has vanish.

Could you please fix it, so this listener works properly if that's possible? Or give me any hints how I can achieve not showing join messages when moderators join with vanish on join feature enabled?

Here is my listener:

```
public class WelcomePlayerJoinEvent implements Listener {

    @EventHandler
    public void onPlayerJoin(PlayerJoinEvent event) {
        event.joinMessage(Component.text(""));
        Player player = event.getPlayer();

        if (!isVanished(player)) {
            welcome(player);
        }
    }
}
```

And my Vanish class:

```
public static Set<UUID> getCmiVanished() {
        CMI cmi = CMI.getInstance();
        return cmi.getVanishManager().getAllVanished();
    }

    public static boolean isVanished(Player player) {
        return getCmiVanished().contains(player.getUniqueId()) && isMetadataVanished(player);
    }

    public static boolean isMetadataVanished(Player player) {
        Iterator<MetadataValue> var2 = player.getMetadata("vanished").iterator();

        MetadataValue meta;
        do {
            if (!var2.hasNext()) {
                return false;
            }

            meta = var2.next();
        } while (!meta.asBoolean());

        return true;
    }
```

Thank you very much.

---

**Cmi Version (using`/cmi version`):** 
9.0.4.5

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper 1.17

**Comment by CloudeLecaw** [comment]
Why dont simply work with cmis eventcommand.yml there you can define to just show measage if player is not vanished.

**Comment by Bloodlex** [comment]
> Why dont simply work with cmis eventcommand.yml there you can define to just show measage if player is not vanished. You can check there for placeholder if they are null (unvanished) or not ( vanished)
> 
> It look like this ` - check:%cmi_user_uuid%==f24df990-9c6b-4f32-938a-4c91a26d31f4! check:%cmi_user_vanished_symbol%==null! cmi ctellraw all <T> &6&l⚡ &e&l⚡ &6&l⚡ &e&l⚡ [playerDisplayName] &eis back. &6&l⚡ &e&l⚡ &6&l⚡ &e&l⚡</T>`
> 
> May u can use this logic for your plugin too..

Thank you for your answer. Can I also make this message clickable? Like this:

Player X joins [Click to welcome]

After clicking:

Clicking player says "Welcome, X"

And similar on quitting. And that's simply it what I would like to achieve, but take vanished players into account, that means show leave message when going vanish and join message when appearing and also consequently when joining in vanish on join mode not to show anything.

**Comment by CloudeLecaw** [comment]
Sure, if ctellraw you can make it clickable ;)
Like this 

```
<T>Text</T> - Defines text which will be shown
<H>Hover text</H> - represent text to be shown when hovering over text
<C>cmi heal</C> - represents command to be performed when clicking text. Performed by player.
<CC>cmi heal [playerName]</CC> - represents command (from console) to be performed when clicking text. Player can click this only once.
<CCI>cmi heal [playerName]</CCI> - represents command (from console) to be performed when clicking text. Player can click this as many times as he wants.
<SC>Suggested text</SC> - is replacement for command and it will paste text into chat field when clicked
<SI>Insertion text</SI> - differently than <SC> will not replace text but will add to existing one when shift+clicked
<URL>www.google.com</URL> - add url link
To have more than one raw message in one line separate them with <Next>
Raw message should always start with <T>Text</T>
```

So you can design a ctell raw like this
`cmi ctelltaw all <T>Welcome</T><H>click here to realld the welcome meassage</H><CC>/cmi cteext welcomemeassage [playerName]</CC>`
This requires to have custom meassage called welcomemeassage.txt in custom files. You also can use any other command here, use color codes and preform it as player used command just with c.
