### ISSUE TITLE
[Request] Better God Mode

### ISSUE THREAD

**Issue by Wows233** [Zrips/CMI#623]
I hope that CMI's god mode can protect players from the void damage and splash potion effects. Just like essentialsx.

**Cmi Version (using`/cmi version`):** 
7.8.12.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Next update
