### ISSUE TITLE
Adding home limit per world

### ISSUE THREAD

**Issue by GGWP-NewPlayer** [Zrips/CMI#6231]
Hi, I am running a multiverse server. I personally don't like players having more than 3-5 homes in one world and keep teleporting around. So I think it would be nice to have a feature that allows the owner to limit player homes for each world (Example: 3 homes in survival world, 3 homes in resource world, so 6 homes in total). Would be even better if we can group worlds together and set limit on homes per world group.

**Comment by CloudeLecaw** [comment]
I like this idea, this would allow us to define extra homes for spezial worlds. :)

**Comment by Zrips** [comment]
Will add some basic way to define home limits per world. Keep in mind that it will not have any effect on already existing homes. next update.
