### ISSUE TITLE
[BUG] elytra boost not working on 7.9.0.0

### ISSUE THREAD

**Issue by Wows233** [Zrips/CMI#624]
I can't use feather for elytra speed boost in this version, but in 7.8.12.0 it works fine

**Cmi Version (using`/cmi version`):** 
7.9.0.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Thanks for reporting. This will be fixed with next update.
