### ISSUE TITLE
[BUG] /cmi tp  online status bug 

### ISSUE THREAD

**Issue by WOo0W** [Zrips/CMI#628]
When using /cmi tp command to teleport who is not online, it still outputs "Online".
**Cmi Version (using`/cmi version`):** 
7.9.1.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
git-Paper-1500  MC:1.12.2

**Comment by TheTopCz** [comment]
I confirm the same problem, I have it to same..
