### ISSUE TITLE
DisableRiptide: true = infinity fly with elytra 

### ISSUE THREAD

**Issue by l3unnyAnoF4** [Zrips/CMI#6294]
**Description of issue:**

### When DisableRiptide: true = infinity fly with elytra 

---
**VIDEO:**

https://streamable.com/c4rdi8

**CONFIG:**
```
In config CMI
DisableRiptide: true
```

---

**Cmi Version (using`/cmi version`):** 
CMI 9.0.6.0
CMILib 1.0.4.1

**Server Type (Spigot/Paperspigot/etc):** 
Airplane-Purpur-1.17 Build 53

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/67956962/138588582-d0cdfa38-97ad-4aab-a2e7-cbf1097f44ec.png)

**Comment by Zrips** [comment]
Should be resolved with next build

**Comment by l3unnyAnoF4** [comment]
thx
