### ISSUE TITLE
disableebchant Disappeared

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#630]
![image](https://user-images.githubusercontent.com/5382252/43036184-0cf1946c-8d2f-11e8-9454-c2a4e87f1dcf.png)

Disappeared, still normal in the previous version

**Cmi Version (using`/cmi version`): 7.9.1.0

**Server Type (Spigot/Paperspigot/etc): paper

**Server Version (using `/ver`): 1.12.2

**Comment by Zrips** [comment]
Wait for today's update. This should be fixed.
