### ISSUE TITLE
HEX codes contribute to nameplate character limit

### ISSUE THREAD

**Issue by Raesak** [Zrips/CMI#6305]
Minecraft: 1.17.1
Paper: 353
CMI: 9.0.6.1
CMILib: Latest

I noticed that hex codes used in nameplate commands will contribute to the character limit (not tested with Minecraft format (&a, &b, ETC)).
It seems to be a bug because color codes aren't actually shown in the nameplate (they just change the color).
Please fix it so that hex codes won't contribute to the character limit.

**Comment by Zrips** [comment]
Will increase limit of it from current 64 to 256 with next version
