### ISSUE TITLE
CMI Bungee Custompayload spam causing kicks

### ISSUE THREAD

**Issue by iaxedu** [Zrips/CMI#631]
Using CMI v.7.9.1.0
TacoSpigot 1.8.8-R0.2

CMI BungeeCord messages are being spammed so hard that it constantly kicks due to the packet limiter. It looks like this: [https://hastebin.com/ezubixinok.cs](https://hastebin.com/ezubixinok.cs)

In a timeframe of not even a minute, I count 5174 incoming packets. This is tested on one of my test servers. All packets are coming from a server that also runs v7.9.1.0.

And yes I've disabled the bungee options.
BungeeMessages: false
BungeePublicMessages: false

**Comment by LogGits** [comment]
Hastebin is no longer available. Please provide a pastebin link or a just use the "insert code" button in a github reply.

**Comment by iaxedu** [comment]
Some additional information
