### ISSUE TITLE
Vanished players are still visible on Dynmap

### ISSUE THREAD

**Issue by Bloodlex** [Zrips/CMI#6314]
Cmi Version (using/cmi version):
9.0.4.6

Server Type (Spigot/Paperspigot/etc):
Paper

Server Version (using /ver):
Paper 1.17

Relevant plugins (Delete if this isn't needed):
Dynmap 3.2.1

**Comment by Zrips** [comment]
Looks to be working correctly with 3.2.1 version, latest CMI and latest paper build of 1.17.1. Would suggest to updated all of them and if issue persists, let me know, but cant detect any issues currently
