### ISSUE TITLE
The problem with filtering words through regex if sent to a chat with a random register in Russian  

### ISSUE THREAD

**Issue by archroot** [Zrips/CMI#6315]
It is not possible to filter words in Russian from the list through regex, since players distort words with random case of letters in words.

For example:
ПидОр, пИДОР, пИДоР, пиДор,  ПИдоР, пиДОр, ПИдОР, пИдОР, пИДор, ПидОр.

Writing all the variants of each word is a so-so task if there can be 1000 words and each has more than 15 variants of distortions.

CMI: 9.0.6.1
git-Purpur-1171 (MC: 1.16.5)

**Comment by CloudeLecaw** [comment]
So how your regex look?

**Comment by archroot** [comment]
![изображение](https://user-images.githubusercontent.com/41123605/140604489-1704da49-da36-42a8-9984-674554389de6.png)

**Comment by archroot** [comment]
> So how your regex look?
  - (?i)(пидор|мать в канаве|сын хуйни|pidor)

**Comment by archroot** [comment]
issue resolved :)
