### ISSUE TITLE
BungeeCod

### ISSUE THREAD

**Issue by OmegaGGONE** [Zrips/CMI#6318]
Hello I have set up a BungeeCord network and would like to use CMI there. The problem is that cmi is not recognized, let alone loaded. I would like to ask if I have to set something specific or if CMI does not work on a bungee cord server. I add below the error that the console outputs. (That's the only thing the console outputs with cmi.)

[14:19:18] [Server thread/INFO]: [CMI] Loading CMI v9.0.6.1
[14:19:18] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it

**Comment by Zrips** [comment]
CMI needs to be placed into normal server, like Spigot/paperspigot or similar thing, while into actual bungeecord server you need to use CMIB plugin which is a simple bridge plugin made for this task. 
CMI by itself isint made for bungeecord in mind, but it does have few features related to it.
