### ISSUE TITLE
/hat unintended interaction

### ISSUE THREAD

**Issue by SkeletonAce** [Zrips/CMI#6340]
When using `/hat` players can equip any armour without having the durability used (the enchantments on the armour are applied to the player) a blacklist for `/hat` would fix this issue.

**Comment by Zrips** [comment]
You will need to elaborate more on this one. Durability is not used when you equip armor by default, this is default game behavior. What enchants are being applied to the player? And what black list are you talking about here exactly? Do you simply want to prevent putting armor besides helmet on your hear slot?

**Comment by SkeletonAce** [comment]
Yes that is precisely what I would like the blacklist to do :)

And I mean that they get the protection buffs from the armour piece without it being exposed to durability wear.

**Comment by Zrips** [comment]
Well will add some what middle ground solution, option to prevent placing items in head slot which are not helmet type and contains any enchantment. So you can still put boots on your head but only if those doesn't have enchantment.
