### ISSUE TITLE
EnchantWorth 0 not considered by repaircost

### ISSUE THREAD

**Issue by rmalca** [Zrips/CMI#6342]
**Description of issue:**

When using /cmi repaircost the cost does not change if an item has unbreaking 4 and above.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
enchantWorth:
  durability:
  - 0-1000.0
  - 1-100.0
  - 2-250.0
  - 3-500.0
```

---

**Cmi Version (using`/cmi version`):** 9.0.6.1

**Server Type (Spigot/Paperspigot/etc):** Purpur (Paper fork)

**Server Version (using `/ver`):** git-Purpur-1423 (MC: 1.17.1)

**Comment by Zrips** [comment]
Will fix that with next build
