### ISSUE TITLE
Legacy Material support not being initialized on startup

### ISSUE THREAD

**Issue by promorrom** [Zrips/CMI#6349]
**Description of issue:**
Using CMI v9.0.6.2 and CMILib v1.0.4.2 Legacy Material support is initialized whenever I right click a slab (in this case I tested with a block in my hand, I'm not sure if it still initializes if my hand is null).
Legacy Material support should be initialized on server startup, otherwise it initializes on the main thread (freezing the server).
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**

[13:06:19 ERROR]: (org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy:259) Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!

---

**Cmi Version (using`/cmi version`):**  v9.0.6.2

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** This server is running Purpur version git-Purpur-1423 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6cbba00 on ver/1.17.1)

**Comment by promorrom** [comment]
Using this animations settings fixes the issue (with the cost of removing chairs): https://pastebin.com/rp4wX8BG

**Comment by Zrips** [comment]
Will issue fix with next build
