### ISSUE TITLE
Memory Leak/Issue

### ISSUE THREAD

**Issue by LucidAPs** [Zrips/CMI#6350]
![image](https://user-images.githubusercontent.com/42933023/141017961-2b2376cb-3758-4f61-b7d3-47aebb1eccb8.png)

This server is running Purpur version git-Purpur-1423 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6cbba00 on ver/1.17.1)

![image](https://user-images.githubusercontent.com/42933023/141079563-180c0692-ce4f-4659-8d6b-2249c6336300.png)
![image](https://user-images.githubusercontent.com/42933023/141079617-78b64779-f325-4be8-8be8-36b4ece92005.png)
![image](https://user-images.githubusercontent.com/42933023/141079791-e1857106-0ddf-4f9a-9944-fb789c76d44f.png)
![image](https://user-images.githubusercontent.com/42933023/141079838-d3bb80af-4ae5-462c-8804-c97022ddbc4f.png)
![image](https://user-images.githubusercontent.com/42933023/141080119-d98d6e6b-5159-4320-bb0d-37f7f0b6e53a.png)
![image](https://user-images.githubusercontent.com/42933023/141080217-d7f95a67-131c-44bd-addc-f9decc7b5ce6.png)

**Comment by LucidAPs** [comment]
![image](https://user-images.githubusercontent.com/42933023/141362123-656381cd-df36-4bfe-9f5a-b2b34b52748d.png)

**Comment by LucidAPs** [comment]
Bump!

**Comment by Zrips** [comment]
Under investigation

**Comment by Zrips** [comment]
Ok, found culprit, wasn't real memory leak but still introduced unneeded memory usage which can be avoided. Thanks for finding it and point out. Will issue fixed version today.
