### ISSUE TITLE
/cmi money ... Is it a bug or not?

### ISSUE THREAD

**Issue by 1Chaos71** [Zrips/CMI#6353]
GERMAN: 
bei eingeben von "/cmi money" im Client Chat erscheint in der Konsole die ErrorMeldung!
da ich nicht weiß wo der Fehler liegt verknüpfe ich mal die Konfig und die Fehlermeldung.

ENGLISH:
when entering "/cmi money" in the client chat appears in the console the error message!
Since I do not know where the error is, I link times the config and the error message.

[Errorlog](https://1chaos71.de/help/log.log) (extract)
[Config](https://1chaos71.de/help/config.yml)

**Versions: (Information retrieved from the "/cmi version" command) **
CMI Plugin Version: 9.0.6.2 SqLite
CMILib: 1.0.4.2
Server: Spigot 1.17.1-R0.1-SNAPSHOT
CMI economy: Enabled 
CMI Chat: Enabled 
Modules -> 55 enabled 1 disabled: votifier

P.S. Sorry if a few translation errors appear, but I know only "a little bit" of English

**Comment by CloudeLecaw** [comment]
Your using CMIE-Injector plugin + vault   or Zrips modofied fault Version?

**Comment by 1Chaos71** [comment]
English:
oh  ok! there I have times a line not read correctly on the plugin page. have just downloaded the linked VAULT plugin. 

German:
oh ok! da hab ich mal eine Zeile nicht richtig gelesen auf der Plugin Seite. habe eben das verlinkte VAULT Plugin heruntergeladen. 

note: I am a lucky guy? well I don't think so ;)
