### ISSUE TITLE
JailEvent time

### ISSUE THREAD

**Issue by NightLife-SG** [Zrips/CMI#6354]
Cant seem to find time event in jailevent

can you add them in?

**Comment by NightLife-SG** [comment]
what about getting the username who been jailed? event.getJailed().getUser() didnt work

**Comment by Zrips** [comment]
event.getUser() will return user which got jailed, which includes all the information about user, including his name

**Comment by NightLife-SG** [comment]
it return com.Zrips.CMI.Containers.CMIUser@9a44df46
instead of the playername

**Comment by Zrips** [comment]
It returns user object which contains allot more methods than this, including one like getName()

**Comment by NightLife-SG** [comment]
how can i only get the playername?

**Comment by Zrips** [comment]
event.getUser().getName()
