### ISSUE TITLE
launch command power

### ISSUE THREAD

**Issue by dan28000** [Zrips/CMI#6355]
When using launch command power between 4 and 4.9 behaves like power 4
also power 5 seems way too much for scaling and below 4 seems that scaling is off too when i try 3 and 3,5 the difference is 2 blocks in the landing i used angle 20 and power 3 and 3,5

Running latest verion of CMI and CMIlib

**Comment by Zrips** [comment]
Anything above 4 gets handled by different method due to minecraft having hard limit set to power of 4 as max value. Will investigate range between 4 and 4.9, but scaling might be some what different above 4 in any case due to usage of different method.
