### ISSUE TITLE
Ability to block `/back` into forbidden worlds

### ISSUE THREAD

**Issue by Baterka** [Zrips/CMI#6356]
On our server, we have separate world for events. Players can join this world by warp. When user die inside this event world, he is respawned at his respawnpoint (home, bed, spawn, etc.).

Problem is that players with /back permission can go back into this event world and are relocated back on death position. This is not great for some usecases.

Nice enhancement of /back should be that if player does not have permission in destination world, he cannot /back.

Or simple config blacklist/whitelist perworld, if permission based functionality is hard :)

I Can help with that btw...

**Comment by Zrips** [comment]
There is Optimizations.Teleport.BackBlackList in config file where you can define worlds where you don't want to allow players to go back to. No specific permission to bypass that one tho, but its on line what you want to achieve here
