### ISSUE TITLE
Parser with CommandPanels

### ISSUE THREAD

**Issue by RSLuke** [Zrips/CMI#6362]
**Description of issue:**

With the plugin CommandPanels with is a menu plugin, every time I use a cmi command with an imput that the player has to enter, the numbers 1 work wrongly, they just disappear from the command. It has been confirmed by commandpanels developpers that is an issue coming from CMI since I verified with them that the imput is well sent

For example If I enter : 
- cmi tppos -1035 60 -1339 world 
It will send me to -35 60 -339, somewhat the 1 are bugged

---

**Cmi Version (using`/cmi version`):** 9.0.6.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.17.1

**Relevant plugins (Delete if this isn't needed):** CommandPanels any build

**Comment by Zrips** [comment]
Could you give actual example of its usage or config file? I'm not familiar with this plugin, how it works or what it does in general or what you used in specific to get this

**Comment by CloudeLecaw** [comment]
Uf an other Plugin executes this you should try ```cmi tppos -p:[playerName] -1035 60 -1339 world```

**Comment by RSLuke** [comment]
`        has0:
          value0: '%cp-player-name% HASPERM'
          compare0: modo.niveau.1
          material: ELYTRA
          name: '&4► &6Téléportation &8| &aT&8/&21 &4◄'
          lore:
          - ''
          - '&3Clic gauche &7→ pour &6te téléporter&7 à un joueur.'
          - '&9Clic droit &7→ pour &6téléporter&7 un joueur à &6ta&7 position.'
          - ''
          commands:
          - left= msg= &c→ &eRentre le &6pseudo&e du joueur auquel te télépoter.
          - left= cpc
          - right= msg= &c→ &eRentre le &6pseudo&e du joueur à téléporter.
          - right= cpc
          player-input:
          - left= console= lp user %cmi_user_name% permission settemp cmi.command.tp true 1s
          - 'left= console= discord bcast #902189198872805416 `%cmi_user_name%` | Téléportation à  : `%cp-player-input%`'
          - left= delay= 1 sudo= tp %cp-player-input%
          - right= console= lp user %cmi_user_name% permission settemp cmi.command.tphere true 1s
          - right= console= lp user %cmi_user_name% permission settemp cmi.command.tphere.others true 1s
          - 'right= console= discord bcast #902189198872805416 `%cmi_user_name%` | Téléportation de  : `%cp-player-input%`'
          - right= delay= 1 tphere %cp-player-input%
`

**Comment by RSLuke** [comment]
> Uf an other Plugin executes this you should try `cmi tppos -p:[playerName] -1035 60 -1339 world

The problem isn't the player name, I've tried this with other commands, the number 1 is a problem

**Comment by Zrips** [comment]
@RSLuke 
This is not CMI issue. Basic test by only having Command Panels and entering into chat `10 20 30` as target location you can see in console 
![image](https://user-images.githubusercontent.com/10416201/141802287-84360c4e-ebad-451c-840c-d93f697c87a5.png)
So its Command Panels plugin which strips down 1 from input for some reason and not CMI.
Tested with 
![image](https://user-images.githubusercontent.com/10416201/141802548-9e920b10-40c2-40da-bb62-ccb707ab90e3.png)

**Comment by RSLuke** [comment]
As you can see in the config part file, I also broadcast the command to discord and it broadcasts correctly with the right numbers.
I reported this issue to them and they say it doesn't come from CommandPanels but it's a plugin conflict.

**Comment by RSLuke** [comment]
They're asking with commandpanels version you used and which minecraft version

**Comment by Zrips** [comment]
![image](https://user-images.githubusercontent.com/10416201/141804927-ed28409c-b2c3-4e20-988d-144f94c0e0a0.png)
![image](https://user-images.githubusercontent.com/10416201/141804964-4f552fa1-67b0-4733-9761-5fa3dadddf0b.png)
Aka both are latest versions
This cant be plugin conflict due to the fact that its still an issue without any other plugin besides CommandPanels

**Comment by RSLuke** [comment]
Alright, I don't know how you managed to have your problem with a simple typing, probably a mistake but they found the issue and there isn't any link with your example, I confirm the issue closed

**Comment by CloudeLecaw** [comment]
`  - left= delay= 1 sudo= tp %cp-player-input%`
  
Issue maybe? Cmis tp is to player not to Position.
If u want monecrafts vanilla tp use minecraft:tp to make sure u use Vanilla tp command
