### ISSUE TITLE
command /scan not working.

### ISSUE THREAD

**Issue by sakulmore** [Zrips/CMI#6364]
**Description of issue:**
Command /scan can't find any items.

(i posted this to Discussion, but i think it's a bug. I think i'm writing the command correctly.)

**Cmi Version (using`/cmi version`):** 
9.0.6.2

**Server Type (Spigot/Paperspigot/etc):** 
PaperMC

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-790 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Video here: https://youtu.be/x4akji0c2Bc

**Comment by Zrips** [comment]
Will be fixed with todays update
