### ISSUE TITLE
CMIPlayerUnjailEvent may only be triggered synchronously

### ISSUE THREAD

**Issue by TheNylox** [Zrips/CMI#6375]
Hello. I allready asked on discord but didnt get an answer. After updating CMI to the version 9.0.6.3 i got this error a lot ot times during the day

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
java.lang.IllegalStateException: CMIPlayerUnjailEvent may only be triggered synchronously

https://pastebin.com/9nsSjjPU
---

Cmi Version: 9.0.6.3

Server Type: Paper version git-Paper-384 (MC: 1.17.1)

**Comment by Zrips** [comment]
Will be fixed with next update
