### ISSUE TITLE
Modded item

### ISSUE THREAD

**Issue by TheKlimoT** [Zrips/CMI#6376]
Hi! Why is it that through Kit, a mod item is issued to the inventory, but through the give command, it is impossible to get it.

/cmi give nick IRONCHEST_COPPER_CHEST 1

don't work

` 
  Items:
    '28':
      v: 2586
      type: IRONCHEST_COPPER_CHEST
`

**Comment by CloudeLecaw** [comment]
Because give doesnt support yoir modded item?

**Comment by Zrips** [comment]
Without knowing server version or its type cant really say much about this issue. In general modded items should be supported even tho officially we are not supporting modded servers due to their complexity. Will make some changes for CMILib which might help out you here.
