### ISSUE TITLE
Inventory Save on Death

### ISSUE THREAD

**Issue by BirminghamBoy** [Zrips/CMI#6377]
**Description of issue:**
I have the _SaveOnDeath:_ variable set to TRUE in my CMI config.yml. However, upon dying, players' inventories save with no items, despite having items when they died. Using version 

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
inv:
  SaveOnDeath: true
  IgnoreEmpty: false
  RequiresPermission: false
  SavedInventories: 10
  restore:
    HP: true
    XP: true
    Food: true
    Saturation: true
    Potions: true
    Items: true
```

---

**Cmi Version (using`/cmi version`):** 
CMI: 9.0.6.3 SqLite
CMILib: 1.0.4.3
Server: Paper(381) 1.17.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled
Modules -> 47 enabled 9 disabled: spawnerProximity, schedule, hpBossBar, worldLimits, tablist, skin, spawnerCharge, bossBarCompass, totemBehavior

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-381 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: db0bff9)

**Relevant plugins (Delete if this isn't needed):**
All plugins:
AdvancedEnchantments, AlonsoTags, AnimatedFrames, AuctionHouse, BadlionClientModAPI, BanAnnouncer*, BannerMaker, CalendarEvents, ChatColor*, ChatFeelings, ChestSort, ChunkSpawnerLimit, CMI, CMILib, CoreProtect, CosmicVaults, DeathChestPro, DeathMessages, DeluxeMenus, DiscordSRV, DragonSlayer, DynamicShop, floodgate, GCore, Geyser-Spigot, GSit, HeadDatabase, HolographicDisplays, HoloRemove*, HorseTpWithMe, IllegalStack, ImageMaps, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, LagAssist, Lands, LightAPI, LiteBans, MarriageMaster, mcMMO, MobFarmManager, Multiverse-Core, NBTAPI, NerfPhantoms, NightVision*, OreAnnouncer, PermissionsEx*, Petting, PistonMOTD, PlaceholderAPI, PortableCraftingInvs, ProCosmetics, ProtocolLib, PvPManager, QuestCreator, QuickShop, SafariNet, Skript, SpecializedCrates, Spicord*, SponsoredSlots, TAB, TradePlus, UpgradeableHoppers, UpgradeableSpawners, Vault, VeinMiner, ViaBackwards, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldGuard

**Comment by Zrips** [comment]
Would suggest to test this without any other plugin, as it looks like players inventory gets cleared before CMI accesses it so it records empty inventories. You might start with DeathChestPro

**Comment by BirminghamBoy** [comment]
Thanks - was DeathChestPro. Strange, I've always had it installed and it never used to do this. Must have been an update, as AngelChest doesn't seem to cause this issue.

**Comment by BirminghamBoy** [comment]
Thanks - was DeathChestPro. Strange, I've always had it installed and it never used to do this. Must have been an update, as AngelChest doesn't seem to cause this issue.
