### ISSUE TITLE
Caps ChatFilter work only with latin symbols

### ISSUE THREAD

**Issue by NineTown** [Zrips/CMI#6379]
**Description of issue: Caps ChatFilter work only with latin symbols**

Caps ChatFilter works only with latin symbols. It cant catch cyrillic caps spam in chat.
For example: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF is blocked, ФФФФФФФФФФФФФФФ isn't.

---

**Cmi Version (using`/cmi version`): 9.0.6.3** 

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): git-Paper-386**

**Comment by Zrips** [comment]
Will issue fix with next update
