### ISSUE TITLE
Failed to retrieve image from URL (minepic.org/avatar/)

### ISSUE THREAD

**Issue by Strahilchu** [Zrips/CMI#6381]
Title says it all, the website seems to be down, is there an alternative? It's been a few days now.

CMI: 9.0.6.3 SqLite
CMILib: 1.0.4.3 
Server: Paper(388) 1.17.1-R0.1-SNAPSHOT

**Comment by Strahilchu** [comment]
Website actually loaded but very slowly.

Using BloomHost (not sure if relevant) 

Has anyone else gotten this issue?

**Comment by CloudeLecaw** [comment]
Why you think this is an cmu issues?
Cmi is downloaded from soigot.mc ...

**Comment by Zrips** [comment]
Will add extra fallback server in case we cant get image from first one we will try to get from extra one. In general you can ignore those messages as its more or less just informational ones. This originates from CMILib, so it will get resolved with next CMILib update
