### ISSUE TITLE
Command /invsee can't tab to find player name.

### ISSUE THREAD

**Issue by speccycy** [Zrips/CMI#6383]
**Description of issue:**
When using the /invsee command, press Tab to find the player's name.
will not be able to work

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
/invsee:
    Enabled: true
    Tab: true
```

---

**Cmi Version (using`/cmi version`):** 
CMI: 9.0.6.3
CMILib: 1.0.4.3

**Server Type (Spigot/Paperspigot/etc):** 
CatServer Hybrid Server

**Server Version (using `/ver`):** 
CatServer version git-CatServer-1.12.2-119130c (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2855)

**Comment by Zrips** [comment]
This usually caused by another plugin overriding tab complete for this command if you have one which has same command in use. Try testing this without any other plugin or simply check /cmi invsee command if that one tabcompletes so we will know where issue is
