### ISSUE TITLE
Recompiled Vault plugin on spigot CMI page has unreadable text in its version (plugin.yml)

### ISSUE THREAD

**Issue by Qveshn** [Zrips/CMI#6384]
**Recompiled Vault plugin on spigot CMI page has unreadable text in its version (plugin.yml)**
(_I do not know where is your recompiled Vault plugin support page located, therefore I'm writing here_)

https://www.zrips.net/wp-content/uploads/2020/07/Vault-1.7.3.jar

This is more of a warning than an error.
Recompiled Vault plugin has plugin.yml with:
`version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}`
When I use command '/vault-info' it shows:
`[Vault] Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER} Information`

Could you replace `b${env.TRAVIS_BUILD_NUMBER}` with something more readable?
For example `CMI` and we will see text like
`[Vault] Vault v1.7.3-CMI Information`

Thanks
😃

**Comment by Zrips** [comment]
Will do

**Comment by Qveshn** [comment]
Thanks

Also, why not make PR to @MilkBowl to add CMI in Vault?
Or MilkBowl supports only free plugins?
