### ISSUE TITLE
Random Teleportation worlds do not auto generate, `/setrt` not functional

### ISSUE THREAD

**Issue by gecko10000** [Zrips/CMI#6385]
**Description of issue:**
Reported in the Discord multiple times, worlds do not generate automatically in the RTP config no matter what the setting to auto generate is, and the `/setrt` command does not work.

**Cmi Version (using`/cmi version`):** 9.0.6.3

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** `This server is running Purpur version git-Purpur-1406 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 91d3e65 on ver/1.17.1)`

**Comment by Zrips** [comment]
Wil fix AutoGenerateWorlds
/setrt looks to be working correctly. What command you tried to use and what feedback message you got after that?

**Comment by gecko10000** [comment]
I'm not sure, haha, was just relaying the message from Discord. Thanks for fixing the AutoGenerateWorlds issue!
