### ISSUE TITLE
Import data with DeathMessages

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#6394]
Hi there!

Since the 9.0.7.0 update, **CMI** integrates custom death messages in the settings folder.

And since I'm currently using the **DeathMessages** plugin (_https://www.spigotmc.org/resources/deathmessages.3789/_), I had an idea;
Would it be possible to do like Essentials & HolographicDisplay, that CMI integrates the importfrom for this plugin!

**Comment by mercurialmusic** [comment]
I also use DeathMessages, and am so glad to see that CMI is integrating these since DeathMessages has been limping along for a while, now on its third dev in the last one year. While import might be a stretch especially since the current DeathMessages configs are highly variable/configurable, I still hope this feature is developed/expanded significantly!

**Comment by mrfloris** [comment]
Can you attach the msgs file from that plugin, so I have some sample data? I might try to see if a script that I use can be adjusted to help import this.

**Comment by NoltoxDev** [comment]
Hi Floris, and thanks for your answer!

I send you an example of my configuration on DeathMessages :
_[DeathMessages.zip](https://github.com/Zrips/CMI/files/7606857/DeathMessages.zip)_

**Comment by kelso6969** [comment]
I didn't realize this was a new thing in CMI. Guess I should read the updates more often. I too would love an import as I spent a lot of time customizing DeathMessages.

**Comment by NoltoxGit** [comment]
Hello @mrfloris, is this extension still planned?

**Comment by mrfloris** [comment]
> Hello @mrfloris, is this extension still planned?

Unfortn. offline has taken up more time than I like. I haven't been able to find a moment to sit and convert.

**Comment by NoltoxGit** [comment]
### Move this suggestion [here](https://github.com/Zrips/CMI/discussions/6966).
