### ISSUE TITLE
When is the plugin update under 1.18

### ISSUE THREAD

**Issue by Woodpecker123** [Zrips/CMI#6405]
A new version of the game has been released, and the plugin has stopped working. Please update it!

**Comment by mrfloris** [comment]
Spigot / Paper 1.17.1 servers should for the time being run CMI 9.0.x
Spigot / Paper 1.18 servers can now use an early dev build for 1.18, CMI version 9.1.0.0 (or newer)
Please note that 1.18 requires CMILib version 1.1.0.0 (or newer)

https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/updates
