### ISSUE TITLE
Homes GUI does not refresh dialog (or close) after deleting the home.

### ISSUE THREAD

**Issue by Qveshn** [Zrips/CMI#6412]
**Description of issue:**

When player is not op and opens "Homes" dialog (command `/home`), the GUI allows to delete homes via Shift+right click
When there are 2 homes or less, then deleting any home closes dialog.
When there are more than 2 homes, then deleting any home does not close the dialog but also **does not refresh it**.
It refreshes the dialog only when player is op.

I am not sure which method is good: always close dialog or always refresh dialog after deleting home via gui.
But as for me, I'd like that it will only refresh dialog and not to close it while deleting home even if 2 or less homes atm. This is useful when player wants to delete more than one home  or stay in dialog after deleting the last home (to be sure all is correct).

PS. Also when player is not op, he does not see the death home (location) in dialog.
And op also can not open another player homes dialog `/homes <player>` when the player does not have homes. Therefore op can not see the player's death location.

---

**Cmi Version (using`/cmi version`):** 
9.0.7.0
**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
CraftBukkit version 3284-Spigot-3892929-0ebef35 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):**
CMILib 1.1.0.0

**Comment by Zrips** [comment]
Will get fixed with next release, tho it might take few versions before 1.17 support comes back for nevest CMI version.
