### ISSUE TITLE
Flight Charges not blocked by "fly" flag

### ISSUE THREAD

**Issue by Mappors** [Zrips/CMI#6425]
With Flight Charges, players are able to fly in regions/worlds where `fly` has been set to `deny`. It seems that the WorldGuard fly flag does not block Flight Charges completely.
So the request is that a custom flag would be made to disable Flight Charges in certain regions.

---

**Cmi Version (using`/cmi version`):** 
CMI: 9.0.7.0 SqLite-> 9.1.0.1
CMILib: 1.1.0.0 -> 1.1.0.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper(391) 1.17.1-R0.1-SNAPSHOT
**Relevant plugins (Delete if this isn't needed):** 
WorldGuard 7.0.6+1cff55f

**Comment by CloudeLecaw** [comment]
why you thought cmi would add flags for Worldguard ? ;)
