### ISSUE TITLE
Tellraw [playerName] placeholder

### ISSUE THREAD

**Issue by MrApocalyptic** [Zrips/CMI#6426]
![cmi](https://user-images.githubusercontent.com/47505341/144749059-5fc84451-f455-41d7-a818-e220bcdfc18a.png)
When using the [playerName] placeholder in a /cmi ctellraw all message it chooses a certain person instead of doing it for each player online

**Comment by CloudeLecaw** [comment]
You wrote Argument `all` instead of `[playerName]` ?

**Comment by MrApocalyptic** [comment]
Yes ill give you an example
/cmi ctellraw all <T>Click to be healed</T><CCI>cmi heal [playerName]</CCI>

**Comment by Zrips** [comment]
Will be fixed with next release
