### ISSUE TITLE
Error with /tp or /tpall Command

### ISSUE THREAD

**Issue by Dijeung** [Zrips/CMI#6428]
**Description of issue:**

If you do /tp (A)Player (B)player when you are in another world, 
it appears in the (B)player chat like this.
( &cTeleport location is unsafe. 3rd party plugin )
Missing locale for command..info.feedback

When I'm in another world, I can't play tpall.
&cTeleport location is unsafe. 3rd party plugin
Missing locale for command..info.feedback

No errors are displayed on the console. It only appears in the chat room.

![image](https://user-images.githubusercontent.com/86919557/144793217-6485ff4e-8941-416c-8ed6-01e3a529b39a.png)
![image](https://user-images.githubusercontent.com/86919557/144793234-925fef83-2c99-444e-b3cd-b6e6b8541027.png)

---

**Cmi Version (using`/cmi version`):** 
CMI9.1.0.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
#52 paper 1.18

**Comment by Zrips** [comment]
Will make a fix with next release
