### ISSUE TITLE
bug /replaceblock y

### ISSUE THREAD

**Issue by Yukylyu** [Zrips/CMI#6433]
**Description of issue:**
Hi,
If I use the /replaceblock command, the Y in height hasn't been taken into account for a few versions, for example I want to put back a bedrock layer (my generator has a problem so I use cmi to put it back):

/replaceblock id stone,dirt,diorite,granite,andesite,air,lava w bedrock r 10 y 1

The height is not taken into account the CMI plugin will replace the whole stone in bedrock and not layer 1.

could you fix this problem please?

**Cmi Version (using`/cmi version`):** 
9.1.0.1 and old or new / cmi lib 1.1.0.1

**Server Type (Spigot/Paperspigot/etc):** 
1.17.1 spigot

**Comment by Zrips** [comment]
Will be fixed with next version
