### ISSUE TITLE
Chat filter issue

### ISSUE THREAD

**Issue by PrestonM20** [Zrips/CMI#6434]
When reloading the plugin it says an error occured and whenever I type in chat it outputs an error to console

. Cant load chat filter section from config file! Error:

[WARNING] .... java.util.NoSuchElementException

[WARNING] .... at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:758)

[WARNING] .... at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:778)

[WARNING] .... at CMI9.1.0.1.jar//com.Zrips.CMI.Modules.ChatFilter.ChatFilterManager.load(ChatFilterManager.java:407)

[WARNING] .... at CMI9.1.0.1.jar//com.Zrips.CMI.Config.load(Config.java:1457)

[WARNING] .... at CMI9.1.0.1.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1487)

[WARNING] .... at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)

[WARNING] .... at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)

[WARNING] .... at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)

[WARNING] .... at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563)

[WARNING] .... at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477)

[WARNING] .... at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)

[WARNING] .... at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)

[WARNING] .... at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)

[WARNING] .... at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)

[WARNING] .... at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)

[WARNING] .... at java.base/java.lang.Thread.run(Thread.java:833)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Have not even touched config.
```

---

**Cmi Version 9,1,0,1

**Paper

**1.18

**Comment by gecko10000** [comment]
Yes, this is because it no longer auto generates #6431

**Comment by Zrips** [comment]
Should be fixed with next release
