### ISSUE TITLE
Hide your own nickname when logging in

### ISSUE THREAD

**Issue by NoltoxDev** [Zrips/CMI#6435]
Hi!

I added a login message (via ctext) when players join, and I had a suggestion on my Discord where someone said, "Is it possible to hide our own nickname when we join, but other players see it?"

So, not knowing how to do this, I come to you!
![image](https://user-images.githubusercontent.com/75265787/145213306-b621c85d-0a08-4cb2-bace-7803e1432820.png)
So, in my example it would be to hide the **"Admin • Noltox**"

**Comment by Zrips** [comment]
Not possible with current setup. We are not really filtering out anything like that in ctext as its only replacing placeholders and returns output which is shown to all players i same way.
