### ISSUE TITLE
[1.17.1 / 1.18] Merchant window doesn't open.

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#6436]
**Description of issue:**

Walker reported on Discord that the merchant window doesn't open. We're both on CMI 9.1.0.1 and CMILib 1.1.0.1 and he's on 1.18 and I am on 1.17.1, i can reproduce the issue.

`/cmi merchant butcher` for example tells you it opened the window, it doesn't. There's no msgs in console.

<img width="655" alt="Screenshot 2021-12-08 at 14 31 22" src="https://user-images.githubusercontent.com/28841349/145216809-6ca472e7-0fd9-4bce-abaa-216a1ff6cef7.png">

**Comment by mrfloris** [comment]
<img width="655" alt="Screenshot 2021-12-08 at 14 32 10" src="https://user-images.githubusercontent.com/28841349/145216925-5722c0ac-f3bb-4906-baa3-74deaaa4f320.png"
<img width="679" alt="Screenshot 2021-12-08 at 14 32 25" src="https://user-images.githubusercontent.com/28841349/145216966-4f9c64f2-f0cc-47d5-a402-58d3dee76801.png">
>

**Comment by mrfloris** [comment]
Update, when i first got into server with low tps on 1.18, i see the window come up, the grey flashes, it's like .. with a bit of lag you can see it open and close super fast. i tried recording it, but tps was back to 20 and couldn't even see it in a single frame.

**Comment by w41k3r26** [comment]
^^

**Comment by Zrips** [comment]
Will get a fix with next update
