### ISSUE TITLE
/glow only shows white

### ISSUE THREAD

**Issue by PrestonM20** [Zrips/CMI#6439]
/glow doesnt change colors

**Comment by ItLucifer-MRPG** [comment]
Im assuming you're using TAB or another plugin that sorts tablist or uses minecraft teams.
as glow colours, teams, and tablist sorting are all directly connected. a plugin changes one. it tends to break the others

**Comment by Zrips** [comment]
This is usually caused by having compatibility issue with another plugin managing player teams, cant really do anything about it currently, there isint all in one solution at this moment.
