### ISSUE TITLE
[Request] Kits paging + Group kits cooldown

### ISSUE THREAD

**Issue by wingcwf** [Zrips/CMI#644]
Too many Kits, it started to get messy

I hope to do the paging function
Example:
![kit](https://user-images.githubusercontent.com/34314256/43072853-1a16cd7a-8eaa-11e8-9e49-ad7cbbd28b40.jpg)

![kit](https://user-images.githubusercontent.com/34314256/43072917-48b2b90a-8eaa-11e8-8bd6-39a8cae218ed.jpg)

![kit](https://user-images.githubusercontent.com/34314256/43072878-2c6b543c-8eaa-11e8-8061-0731b841daad.jpg)

![kit](https://user-images.githubusercontent.com/34314256/43072901-38238df8-8eaa-11e8-83d2-defc592e7800.jpg)

-------------------------------------------------------------------------------------------------------------------
Different permission groups have different cooldown times
Like default (7d) vip (5d) etc.

**Comment by CloudeLecaw** [comment]
i see u  wanted subgroups of kits, a nice idea :-P

**Comment by wingcwf** [comment]
I didn't want subgroups of kits = =...
I just want have paginate , The picture above is just a screenshot on other server..I am just using it for example

**Comment by CloudeLecaw** [comment]
You should post other screenshots then if u dont want a Grouping and Subgrouping
Your Screenshots Show Subgroups no Paging or other function; (and they are tin the middle so we could speak of some kind like  design)

Paging would be a listing of all Kits and in the last line two Buttons_ _Next Page/Prev Page_

Subgrousp what your Screenshot show's:
Group1:   Free ->  Kit1, Kit2, Kit3, Kit4- Kit5
Group2:   Donator  -> Kit6, Kit7, Kit8, Kit9- Kit10

Belive it or not but in the backgroup you have still this 10 Kits in your files and 1,2,3,4,5 are a Sub of Free and 6,7,8,9,10 a Sub of Donator.
