### ISSUE TITLE
Weird console spam

### ISSUE THREAD

**Issue by PrestonM20** [Zrips/CMI#6441]
**Description of issue:**

---

[WARNING] .... java.lang.NoSuchMethodException: net.minecraft.world.level.block.entity.TileEntityBeehive.getBeeCount()

[WARNING] .... at java.base/java.lang.Class.getMethod(Class.java:2227)

[WARNING] .... at CMI9.1.0.1.jar//com.Zrips.CMI.Reflections.getBeesInside(Reflections.java:413)

[WARNING] .... at CMI9.1.0.1.jar//com.Zrips.CMI.AllListeners.PlayerListeners.onInteractBeeHive(PlayerListeners.java:565)

[WARNING] .... at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor864.execute(Unknown Source)

[WARNING] .... at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)

[WARNING] .... at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)

[WARNING] .... at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)

[WARNING] .... at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)

[WARNING] .... at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)

[WARNING] .... at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:542)

[WARNING] .... at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1892)

[WARNING] .... at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)

[WARNING] .... at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)

[WARNING] .... at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)

[WARNING] .... at net.minecraft.server.TickTask.run(TickTask.java:18)

[WARNING] .... at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)

[WARNING] .... at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)

[WARNING] .... at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1437)

[WARNING] .... at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)

[WARNING] .... at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)

[WARNING] .... at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1415)

[WARNING] .... at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1408)

[WARNING] .... at net.minecraft.util.thread.IAsyncTaskHandler.bp(IAsyncTaskHandler.java:110)

[WARNING] .... at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1542)

[WARNING] .... at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1282)

[WARNING] .... at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)

[WARNING] .... at java.base/java.lang.Thread.run(Thread.java:833)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

9.1.0.1

Purpur

1.18

**Comment by Zrips** [comment]
Will be fixed with next update
