### ISSUE TITLE
death messages stacking

### ISSUE THREAD

**Issue by dan28000** [Zrips/CMI#6449]
sometimes are death messages stacking into one death message
in the images is /ver and how the death message looks in chat when stacked the file is death messages locale file

![image](https://user-images.githubusercontent.com/84990628/145635251-f010e451-6ea1-4b92-87d5-2b7d347a7f50.png)
[locale_EN.txt](https://github.com/Zrips/CMI/files/7695198/locale_EN.txt)
![image](https://user-images.githubusercontent.com/84990628/145635420-40b475d6-04e5-48c4-a154-3c2230c0ec27.png)

**Comment by Zrips** [comment]
Should be resolved with next update
