### ISSUE TITLE
[Request] Playtimetop placeholders

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#645]
Similar to the placeholders for `/cmi baltop`
%cmi_playtimetop_name_[1-10]% - Returns name
%cmi_playtimetop_time_[1-10]% - Returns playtime of player, similar to what you would see in `/cmi playtimetop`

**Comment by andramil** [comment]
bump

**Comment by Zrips** [comment]
Got implemented

**Comment by SbirTeo** [comment]
@Zrips is there a way to translate Hours, days, and min?
