### ISSUE TITLE
No damage to all mobs

### ISSUE THREAD

**Issue by mani1232** [Zrips/CMI#6456]
**Description of issue:**
**(Turn off the sound)**
https://www.dropbox.com/s/99dkowzsr3elk4w/java-runtime-beta-20211212-23234501_yEtTJXt0.mp4?dl=0

**No damage to all mobs**

All configs have been reset and re-configured

All plugins have been updated
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
no error in the console
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
[config.txt](https://github.com/Zrips/CMI/files/7699921/config.txt)

```

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/70480001/145731010-45bf9662-937a-4bb8-b1b9-983bdb6912d0.png)
**Server Type (Spigot/Paperspigot/etc):** 
Pufferfish
**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/70480001/145731026-34121ed6-b977-47e4-b7ad-59986ec4d87e.png)
**Relevant plugins (Delete if this isn't needed):**
![image](https://user-images.githubusercontent.com/70480001/145731082-b504073a-41d5-4675-90d2-827b336dab54.png)

**Comment by mrfloris** [comment]
Please provide the full output of /cmi version and /ver, as asked. It really helps answer more questions.

CMI Is made for Spigot and Paper, forks of forks of forks aren't officially supported, please try this with Paper 1.18.1, and let us know if that resolved it. 

If you clone your server and remove the other plugins and just have CMI, does it start working?

**Comment by mrfloris** [comment]
<img width="269" alt="Screenshot 2021-12-12 at 22 55 11" src="https://user-images.githubusercontent.com/28841349/145731092-f2c2fc38-755b-4643-a36a-e9f9f8ff13ee.png">

Go to modules.yml and turn on hpBossbar heal points in bossbar module is turned off

**Comment by mani1232** [comment]
Answer: the plugin on the guild is broken
https://www.spigotmc.org/resources/guilds-30-sale.66176/
13.12.2021

**Comment by mani1232** [comment]
Answer: the plugin on the guild is broken
https://www.spigotmc.org/resources/guilds-30-sale.66176/
13.12.2021
