### ISSUE TITLE
[1.18.1] /tppos command can only goes up to 256 blocks height

### ISSUE THREAD

**Issue by In77** [Zrips/CMI#6461]
**Description of issue:**
when using /tppos command in 1.18.1 server, it can only teleport up to 256 blocks height even when input a Y value larger than 256 (eg: 319).
---

**Cmi Version (using`/cmi version`):** 
9.1.0.2

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper version git-Paper-75 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 51d1687)

**Comment by Zrips** [comment]
Will be fixed with next update
