### ISSUE TITLE
[CMILIB] Middle click broken in GUIs

### ISSUE THREAD

**Issue by SkeletonAce** [Zrips/CMI#6479]
Middle click does not work properly in survival (In a GUI such as armour stand editor or warp editor).
Middle clicking does not register and it does not cause a prompt to show up.
Middle click does not work to leave jobs in `/jobs browse`
This issue is likely from an update to CMILIB as it effects all Zrips plugins.

This bug can be bypassed by using creative mode or holding the item you are clicking on with your cursor before middle clicking.

**Cmi Version (CMI9.1.0.3)**

**Server Type (purpur-1.18.1-1445)**

**Comment by Zrips** [comment]
Looks to be bug with 1.18.1 server itself, works just fine with older servers. Even isint fired at all when you use middle click in survival mode so i cant do anything about it at this point

**Comment by Zrips** [comment]
https://bugs.mojang.com/browse/MC-46584
Change done my Mojang itself. So i guess we lost middle mouse click for survival users

**Comment by Zrips** [comment]
Additional note that it does work if you hold item on your cursor while clicking. But this isint real solution at the moment for empty cursors which is usually the case.

**Comment by Zrips** [comment]
And one more addition, checked what packets are sent to server when player middle clicks, none, none at all, so i cant even use those to fix this one as its client sided issue at this moment.

**Comment by mrfloris** [comment]
shift left click to edit is the future
