### ISSUE TITLE
[BUG] Elytra boosting with trident when trident in left hand + right click

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#6480]
**Description of issue:**
I had noticed that even though the trident was fixed for right hand if you will hold it in your left hand the previous issue comes back and allows fast acceleration without rain just holding right click or left xD not sure with one it was
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  # 1.13+ servers. Do you want to disable riptide enchant usage while flying with elytra and trident which has riptide enchant
  # This combination is dangerous as player can reach extreme speed's if allowed to use it
  DisableRiptide: true
```

---

**Cmi Version (using`/cmi version`):** 
9.1.0.3
**Server Type (Spigot/Paperspigot/etc):** 
purpur
**Server Version (using `/ver`):** 
1.17.1

**Comment by SenPr** [comment]
This issue is still happening in 1.18.1

CMI Version 9.1.0.5

**Comment by Zrips** [comment]
Gets a fix with next version
