### ISSUE TITLE
/anvil not working in 1.18.1

### ISSUE THREAD

**Issue by PovilasLT** [Zrips/CMI#6496]
**Description of issue:**

/anvil command not working in 1.18.1, just shows message, that anvil was opened, but GUI won't open.

**Cmi Version (using`/cmi version`):** 

9.1.0.4

**Server Type (Spigot/Paperspigot/etc):** 

Paperspigot

**Server Version (using `/ver`):** 

3359-Spigot-dbf4938-4f5d59a

**Comment by mare-on** [comment]
Up

**Comment by WolverStones** [comment]
> Up

#6613

**Comment by WolverStones** [comment]
Fixed in 9.1.1.2

**Comment by Zrips** [comment]
Resolved.
