### ISSUE TITLE
CMI playtime error

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/CMI#65]
After running the /cmi playtime command, this spmam error appears in my console. But despite this, the information will be displayed.

https://pastebin.com/3XMLDPX8

AuthMeReloaded v5.4.0 b1877
Server version (Spigot) #201803020430, development | 1.12.2
CMI: 7.3.16.1

**Comment by Zrips** [comment]
Hard to say, works for me without any issue. This issue comes from AuthMe not wanting to properly handle offline player data load. You could try contacting AuthMe dev about this
