### ISSUE TITLE
Unable to get in game chat by discordsrv plugin

### ISSUE THREAD

**Issue by SeanWalk** [Zrips/CMI#650]
**Description of issue or feature request: when clickhovermessage enable , then discordchat disable**

  CMI has this feature and its work
  Enables support for DiscordSRV plugin
  DiscordSRVPublicChat: true

  I dont know  in game chat send to DiscordSRV is CMI problem or DiscordSRV,
  but when i use the feature, which make you can get info on chat.
  ClickHoverMessages: true
  All the chat thing wont show in discord.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  # When set to true, regular and private messages (excludes clean messages) will have aditional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
  # To change default hover over messages seen on sent message, go to your locale file to Chat section
  ClickHoverMessages: false
  # Enables support for DiscordSRV plugin
  DiscordSRVPublicChat: true
```

Cmi Version (using/cmi version): 8.0.0.2

Server Type (Spigot/Paperspigot/etc): Spigot

Server Version (using /ver):MC 1.13R0.1

**Comment by TheWranger** [comment]
It's been an issue for months now, waiting for Zrips to fix.
https://github.com/Zrips/CMI/issues/391
