### ISSUE TITLE
How to edit the names /playtimetop /baltop etc. into the user names instead of the nicknames

### ISSUE THREAD

**Issue by JelmerNL** [Zrips/CMI#6505]
I've got this issue with using HEX colored nicknames in /playtimetop and /baltop.
Is it possible to edit this to the player name instead of the nick name

![playtimetoo](https://user-images.githubusercontent.com/96489822/147419200-e5618a2b-cd92-4ceb-b01f-87594baaf909.png)

**Comment by CloudeLecaw** [comment]
You only can change the shown olaceholder in langfile.
Use there %cmi_user_cleannickname% 
`
%cmi_user_cleannickname% – Players nick name if set or players name otherwise. No color codes`
