### ISSUE TITLE
Confusion / inconsistency with new /cmi attachcommand

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#6508]
People seem to be confused as to what is now old or new, because of what they read in the recent changelog versus what the examples on the site say. 

The things like `!limiteduse:1!` goes not as a command? But needs to be part of the full command? `/cmi attachcommand !limiteduse:1!` and then we have to type `/cmi attachcommand` to add the commands?

Each command is their own + (new command) in the new menu, does that mean
01 !right!
02 !cooldown:5!
03 asConsole cmi heal [playerName]
?

A bit more clarification would help with discord questions. 

I have no concrete examples of complex things they ask, they dont always include their full screenshots or example outputs in console, etc.

**Comment by mrfloris** [comment]
_Resources:_
<https://www.zrips.net/cmi/commands/attached-commands/>
<https://www.zrips.net/cmi/commands/specialized/>

**Comment by mrfloris** [comment]
`/cmi attachcommand !limiteduse:15!;;!cooldown:60!`
![image](https://user-images.githubusercontent.com/28841349/147572562-a58f7e57-ed77-4982-9316-cb887efd9de0.png)

Going the old fashioned route adding !attach_stuff! then it adds it to the item, but not as a command which is what people are (also) doing. And then it wont' work. 

<img width="691" alt="Screenshot 2021-12-28 at 14 43 09" src="https://user-images.githubusercontent.com/28841349/147572603-c6e4e013-9e98-4b35-9a98-17bee7e7d1f5.png">

**Comment by Zrips** [comment]
Old format still aplies as it was before. Difference is that commands get auto split by ;; and put into its own line. So new line will be at same place where previously ;; was and wise versa.
