### ISSUE TITLE
[Bug] - Sitting seems not to work on slabs ;)

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#651]
Sitting on Slaps with rightclick seems not to work in the last Version.

Sitting on Stairs with rightclick works fine :)

**Comment by MCTyler** [comment]
@CloudeLecaw you need a better translator...Slabs...JS.

**Comment by CloudeLecaw** [comment]
i dont work with any Kind of translator *lol*
im just writing fast mostly..im my own translator ^^

**Comment by Zrips** [comment]
Should be working correctly with next build.
