### ISSUE TITLE
CMI cant hit random players

### ISSUE THREAD

**Issue by ReformedHooper** [Zrips/CMI#6513]
You can't hit random players, after typing / cmi afk and returning from this mode, players can hit, but if they don't pass AFK status they can't be hit, tried without CMI and without CMI it works fine

Version CMI: 9.1.0.4 (But it doesn't work in multiple versions)
Server version: 1.18.1

**Comment by Steev93** [comment]
See config for AFK.

`Afk:
  # Enable or disable auto afk system entirely
  Enabled: true
  # When enabled shows title message informing that player is in afk mode
  TitleMessage: true
  # When enabled shows random subtitle message
  SubTitleMessage: true
  # Prevents jumping in one place to avoid afk status
  PreventJumping: true
  # Prevents damage while afk
  PreventDamage: true
  # Defines how often in seconds plugin will check for afk players state
  CheckInterval: 10
  # When set to true, players playtime counter stops
  # As of nature how this system works you can see +-1second jumping up and down while checking players playtime
  StopPlayTime: true
  # Defines how long to wait after player stops moving to set him as afk
  # Player needs to have cmi.command.afk.auto permission node
  # Set to 0 if you want to disable it
  AutoAfkIn: 300
  # Defines commands to be performed when player enters afk mode automatically while addling
  # Supports specialized commands
  AutoAfkCmds:
  - cmi broadcast !&6[playerDisplayName] &eis now AFK
  - warp afk [playerName]
  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds:
  - cmi broadcast !&6[playerDisplayName] &eis now AFK
  - warp afk [playerName]
  # Defines commands to be performed when player leaves afk mode
  AfkLeaveCmds:
  - cmi broadcast !&6[playerDisplayName] &eis no longer AFK
  # Defines how long to wait after player stops moving to kick player
  # This is additional timer to AutoAfkIn and in case player entered afk mode manually he will get kicked after AutoAfkIn+AutoKickIn seconds
  # This can be used not only to kick but to perform repeating action every x seconds if needed
  # Keep it at -1 to disable auto kick
  # Can be bypassed with cmi.command.afk.kickbypass permission node
  # Additionally players kick time can be changed with cmi.command.afk.kickOutIn.[seconds] permission node where bigger value takes priority
  AutoKickIn: -1
  # This will define how long to wait before performing kick commands again
  RepeatingAutoKickInterval: 420
  # When set to true, kick command will be repeated each RepeatingAutoKickInterval seconds
  RepeatKickCommand: false
  # Defines commands to be performed when player can be kicked
  # If player is not kicked then commands will be repeated every RepeatingAutoKickInterval seconds
  AutoKickCmds:
  - cmi kick [playerName] &eYou have been kicked for idling more than [time]
  # Defines worlds where players will not be placed into afk mode after they idled for defined time
  DisabledWorlds:
  - oneTestWorld
  - secondTestWorld
  - adminworld
  # Disables afk on interaction
  DisableOnInteract: true
  # Prevents player from going bypassing afk mode while continuously holding one button with particular items or on particular blocks
  SmartInteractCheck: true
  # Prevents from players abusing afk by constantly moving in afk machine
  AntiAfkMachines: true
  # EXPERIMENTAL! Prevents players from being pushed around while player is in afk mode
  # Keep in mind that player can still be moved around the same block he is in
  PreventPushing: true
  # Disables afk on inventory click
  DisableOnInventoryClick: true
  # Disables afk on item drop
  DisableOnitemDrop: true
  # Disables afk on command usage
  DisableOnCommand: true
  # Disables afk on public chat message
  DisableOnPublicChat: true
  # Disables afk on private chat message
  DisableOnPrivateChat: false
  # Disables afk on move
  DisableOnMove: true
  # Disables afk on fishing
  DisableFishing: true
  # Disables item pickup while afk
  DisableItemPickup: true`

**Comment by ReformedHooper** [comment]
However, the error is not in AFK status, the error is in the CMI part, when the player comes to PVP immediately after connection, he cannot be hit until he has the status afk which teleports him to spawn and when he moves it teleports him back to PVP so it can already be hit, I don't think this causes the AFK system, it will help the player get hits.

**Comment by Steev93** [comment]
Hmm might need to install Plugman. Test each plugin might be conflicting plugins.

Upload the Config of CMI and all plugins so I can have a look see If I can help you out.

**Comment by Zrips** [comment]
@ReformedHooper 
Without having your config section relating to AFK cant test it properly. But its not some wide spread issue as no one else reporting it, so it could be compatibility issue, it could be some weird bug to, but hard to say if it is without option to reproduce it at the moment.
