### ISSUE TITLE
[Bug?] - Langfile - Dolphines Grace

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#652]
in the langfile i found this line
    unknown_effect_type_30:
    - unknown_effect_type_30
this effect normaly is called **dolphins_grace**
was this effect missing in Spigot 13.Pre7? or is this unknown Name the real Name spigot gave it?
im asking because in the Minecraft wiki ist called dolphins_grace

**Comment by Zrips** [comment]
Its seems that spigot dint set properly name for it and getName method returns this weird name. Interesting.

**Comment by MCTyler** [comment]
@CloudeLecaw You gonna report this to MD_5?

**Comment by CloudeLecaw** [comment]
Well i posted it here now
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-development-builds.328883/page-46

dont know if this is the Right place for this :3

**Comment by Zrips** [comment]
@MCTyler Will make a issue report ticket about this one.

**Comment by Zrips** [comment]
Ok, reported and its resolved, b1751 build should have correct name.
