### ISSUE TITLE
[Request] Permission node tablist sorting

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#653]
Sort players on the tablist depending on what permission node they have.
Something like `cmi.tablistsort.[number]`
The higher the number, the higher on the tablist they will be at. Higher numbers should override lower numbers if they have multiple permission nodes.

If people don't want to use this, they can just not give the permission nodes to people.

**Comment by CloudeLecaw** [comment]
uff did you really think all the day About crazzy stuff that CMi doesnt have?
why other Players should be listet higher?
To have admins on first place allways?
Why not working with ranks prefix or Color or other Things? ;)

> 
If people don't want to use this, they can just not give the permission nodes to people.

your forgot admins they would have all existing tablistsortnumbers even if u didnt gave them to them

so it would be better if a tablistsorting can be disabled in config if not used

**Comment by TheWranger** [comment]
> your forgot admins they would have all existing tablistsortnumbers even if u didnt gave them to them
Ops do not get all permissions by default. They only get a permission if a plugin says so, in this case Zrips can just set it so that OPs don't receive the permission by default, no big deal.

**Comment by CloudeLecaw** [comment]
Turn OFF and ON button still is the better choose!

**Comment by TheWranger** [comment]
@CloudeLecaw Could you mark this as an enhancement, it's sorta been forgotten and is still needed.

**Comment by CloudeLecaw** [comment]
Well i am just  a normal user i cant change the prioritit of other threads

**Comment by TheWranger** [comment]
Sorry, I tagged the wrong person
@LogGits
