### ISSUE TITLE
Add -s to Stonecutter, Smithing Table, and Loom

### ISSUE THREAD

**Issue by TheCashFire** [Zrips/CMI#6530]
Visit https://github.com/Zrips/CMI/discussions/new to post new idea or suggestion
Posting new suggestion in ticket section could result in their removal.

Title. Recent additions to the cartography table reminded me that I have need for the other profession benches to have a silence command as well.

Please add! :)

**Comment by TheCashFire** [comment]
Also opened in the discussions area, was not sure if I needed to do both.

**Comment by Zrips** [comment]
Will do
