### ISSUE TITLE
[Bug] Smite does not work

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#654]
to test - look at something and type /cmi smite
your will see Nothing will happen :§

![image](https://user-images.githubusercontent.com/12080017/43130528-2ba9f5de-8f37-11e8-9757-c41bc90c83a6.png)

**Comment by Zrips** [comment]
Works for me. I can smite hell of the chickens

**Comment by CloudeLecaw** [comment]
hmmm im really confused then _;3

**Comment by MCTyler** [comment]
![2018-07-24_05 02 52](https://user-images.githubusercontent.com/6390898/43131703-3d67138e-8eff-11e8-8f39-dea86ac3a4ea.png)

**Comment by CloudeLecaw** [comment]
:3  i closed it allready..tghe Problem is a RedProtect flag

**Comment by MCTyler** [comment]
I saw it was closed...Just thought that was a good timing on my Screen Shot!
