### ISSUE TITLE
Placeholders do not work for Alert inform in the lang file

### ISSUE THREAD

**Issue by t347549** [Zrips/CMI#6540]
**Description of issue:**

Nickname/displayname placeholders (both CMI and PAPI) do not work for the Alert inform line int he English lang file. Only [name] seems to register.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
      inform:
      - '&cALERT&7: &6[playerDisplayName] &cjust logged in!'

in locale_EN.yml
```

---

**Cmi Version (using`/cmi version`):** 
9.1.0.5
**Server Type (Spigot/Paperspigot/etc):** 
PurPur
**Server Version (using `/ver`):** 
PurPur-1462 (1.18.1)

**Comment by Zrips** [comment]
Will be updated with next release
