### ISSUE TITLE
/invsee and inventories

### ISSUE THREAD

**Issue by fortunatas1** [Zrips/CMI#6546]
On the server, players are increasingly complaining that items often disappear from the inventory, as well as taking items from each other in the inventory at the same time doubles the items. /invsee (/invsee only for moderators)

CMI Version 9.1.0.3
Server Type Purpur
Server Version 1.17.1

**Comment by fortunatas1** [comment]
Video: https://streamable.com/oxdys3

**Comment by Zrips** [comment]
Should be resolved now.
