### ISSUE TITLE
Gradients not working

### ISSUE THREAD

**Issue by ItLucifer-MRPG** [Zrips/CMI#6547]
**Description of issue:**
Group chat formats and maybe others dont work with gradients in a few recent versions.
When adding a gradient of two colours around prefix's or names, it doesnt work and sets your chat format back to vanilla

---

**Cmi Version (using`/cmi version`):** 
Most Recent, and I have tested on older versions and its the same

**Server Type (Spigot/Paperspigot/etc):** 
Purpur 1.18.1

**Comment by Zrips** [comment]
I need actual example of our prefix, chat format and so on. Cant debug it without so little information at the moment.

**Comment by ItLucifer-MRPG** [comment]
I would be hard to show without a bunch of screenshots.

But if I set the group chat format to "{prefix}{#fcef91>}{displayName}{#f4c2c2<}&f: {message}" and when giving a player the permission for that chat group, it sets their chat format to the vanilla format minecraft format

**Comment by Zrips** [comment]
Ok, should be fixed with next release.
