### ISSUE TITLE
Mob cannot go through nether portal

### ISSUE THREAD

**Issue by SenPr** [Zrips/CMI#6548]
**Description of issue:**
My players have been struggling to move mobs through the nether portal. I found out it has been CMI interfering, despite it not being described anywhere in the config.
I thought CMI only limit the portal sizes.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
modules.yml

Disabled handling of portals
```

---

**Cmi Version (using`/cmi version`):** 
9.1.0.4
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
Paper 1.18.1 Build 132
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
CMI isint limiting mob teleportation's to nether. Atleast it should not and as of some quick testing i can teleport mobs to nether and back without big trouble.

**Comment by SenPr** [comment]
Was my mistake or potential plugin conflict.
