### ISSUE TITLE
[issues] outdated itemworth

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#655]
i allready deleted the whole worth.yml but the console still shows these four cant get loaded.
![image](https://user-images.githubusercontent.com/12080017/43135960-6e9336ac-8f47-11e8-93f2-afa91cfcec93.png)

**Comment by Zrips** [comment]
You don't need to delete entire file, only update entries for those items. Like woodbutton should be oakbutton as of 1.13 change.

**Comment by Zrips** [comment]
Well that is correct. Will update default worth file then.
