### ISSUE TITLE
Failed to load death message (ES_ES) locale file

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#6550]
**Failed to load death message (ES_ES) locale file:**

I have replaced the file (/Settings/DeathMessages/locale_ES_ES.ym) content with the (/Settings/DeathMessages/locale_EN.yml) and it does not load the file.
---

**ERROR:**
```
######################
## [CMI] Failed to load death message (ES_ES) locale file. Trying to default to EN version ##
######################
```

---

**Cmi Version (using`/cmi version`):** 
Versión de CMI: 9.1.0.5
Base de Datos: SqLite
Versión de CMILib: 1.1.0.7 
Versión del Servidor: Paper(140) 1.18.1-R0.1-SNAPSHOT
Economía de CMI: Activado | Vault: 1.7.3-b | Chat de CMI: Activado 
Módulos: 54 activados y 2 desactivados (moneyCheque | skin)

**Server Type:** 
PaperMC v1.18.1 #140

**Server Version:** 
Paper version git-Paper-140 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: d9fb602)

**Comment by Zrips** [comment]
Will be fixed with next version

**Comment by C4BR3R4** [comment]
> Will be fixed with next version

The language file is not loaded until the pugin is restarted.
