### ISSUE TITLE
non-OP's does not get the afk title message

### ISSUE THREAD

**Issue by Villmarksjenta** [Zrips/CMI#6559]
Hello,

As title says, non-OP's does not get the afk title message. Immediately if I give myself * permission or OP, I get the message up. Are there any permissions the non-OP's are missing?

**Comment by Zrips** [comment]
There are no permissions relating to actual afk title message, it will be shown independent what permission or OP state you have. I might suggest to check if issue persists without any other plugin and only having CMI enabled. But at the end of day, i dint limited those messages with permission node just to be more efficient on that front and there was no need to do so.
