### ISSUE TITLE
[Request] Specific customrecipe

### ISSUE THREAD

**Issue by SeanWalk** [Zrips/CMI#656]
**Description of issue or feature request:** Want customrecipe can read lore or name or anydifferent

Now customrecipe can set result item with name or lore
like 9 stone get stone[lore compress stone]
but i get use it with  stone [lore compress stone] get 9 stone
it would become 1 normal stone can get 9 stone

Cmi Version (using/cmi version): 8.0.0.2

Server Type (Spigot/Paperspigot/etc): Spigot

Server Version (using /ver):MC 1.13R0.1

**Comment by CloudeLecaw** [comment]
this is allready suttested
