### ISSUE TITLE
The death message (ES_ES) language file is not loaded until the plugin is reloaded

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#6567]
**The death message (ES_ES) language file is not loaded until the plugin is reloaded.**

---

Cmi Version (using/cmi version):
Versión de CMI: 9.1.0.6
Base de Datos: SqLite
Versión de CMILib: 1.1.0.8
Versión del Servidor: Paper (140) 1.18.1-R0.1-SNAPSHOT
Economía de CMI: Activado | Vault: 1.7.3-b | Chat de CMI: Activado
Módulos: 54 activados y 2 desactivados (moneyCheque | skin)

Server Type:
PaperMC v1.18.1 #140

Server Version:
Paper version git-Paper-140 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: d9fb602)

**Comment by Zrips** [comment]
Will be fixed with next version
