### ISSUE TITLE
Using delay within statement is not working correctly

### ISSUE THREAD

**Issue by janiiik** [Zrips/CMI#6568]
Script filename
customalias.yml

Describe the bug
When using delay! together with statement commands after dalay are not executed. In the example down here. "test" is working as expected with 2sec delay and next command is performed. in "test2" no commands are executed after delay. in "test3" console responded with unknown commant. Type /help for help. both messages will be send with no delay.

To Reproduce
test:
Cmds:
- msg! [playername] First Text
- delay! 2
- msg! [playername] 2nd text after delay
test2:
Cmds:
- statement:check1! check:1=1!
- if:check1@! msg! [playername] First Text
- delay! 2
- if:check1@! msg! [playername] 2nd text after delay
test3:
Cmds:
- statement:check1! check:1=1!
- if:check1@! msg! [playername] First Text
- if:check1@! delay! 2
- if:check1@! msg! [playername] 2nd text after delay

Expected behavior
I would like delay to be warking also in statements.-

Desktop or Server

paper 1.18.1

**Comment by CloudeLecaw** [comment]
Delay does not work in combination with other things even ig its just a check.
