### ISSUE TITLE
Cant find world

### ISSUE THREAD

**Issue by Oskicz** [Zrips/CMI#6569]
**Description of issue:**
My console is getting spammed by "Can't find world with this name!"
I can disable all my plugins and let stay CMI only turned on and still getting error
My world na me is "world"
But when i delete my world and let server generate new one im not getting error
I builded lobby on "world" using multiverse, void generator now i move the world to new vps and i dont need to use now Multiverse and Void Generator World working normally i can join and run place block and everythink like normal so its CMI problem i think

Please help

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
Can't find world with this name!
![Zrzut ekranu 2022-01-13 164612](https://user-images.githubusercontent.com/28659747/149362231-9874964a-1ba0-4e2f-85a8-e9d502dea6bf.png)

######################
```
---

**Cmi Version (using`/cmi version`):** 
9.1.0.6
**Server Type (Spigot/Paperspigot/etc):** 
Purpur
**Server Version (using `/ver`):** 
git-Purpur-1496 MC: 1.18.1

**Comment by CloudeLecaw** [comment]
Not really ;) sounds more like issue with playerfiles that where localed in not existing world or oitdated entires

**Comment by Zrips** [comment]
@Oskicz 
Message like this is shown when we cant determine world name from given command, as this is printed out into console (I assume it is) that would mean that console is trying to perform some sort of command with invalid world name which gets triggered from time to time. It could be one of the /cmi sound /cmi time /cmi tpopos /cmi tppos /cmi weather
