### ISSUE TITLE
Server crashing upon entering

### ISSUE THREAD

**Issue by JuanChurrito** [Zrips/CMI#657]
The server appears to crash the exact same way every time, after starting up with no apparent issues.

Error:
"A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x000000000000a866, pid=33, tid=0x00007fa248a7dae8
JRE version: OpenJDK Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
Java VM: OpenJDK 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
Derivative: IcedTea 3.8.0
Distribution: Custom build (Wed Jun 13 18:00:32 UTC 2018)
Problematic frame:
C 0x000000000000a866"

Using spigot 1.13

**Comment by JuanChurrito** [comment]
You were absolutely correct. Everything is up and running now.

**Comment by k0nker** [comment]
Out of curiosity, what did you have to update to get it working? I am having the same issue when trying to use CMI.  The error log from Java points to CMI's and SQLite.

**Comment by MCTyler** [comment]
https://java.com/download
