### ISSUE TITLE
AFK idle kick & Chat Formats

### ISSUE THREAD

**Issue by SirLeezus** [Zrips/CMI#6571]
**Description of issue:**
Issue one:
When you enable ModifyChatFormat none of the fomats work, [item], @Player or formatting links. I have no other plugins installed handling chat but cmi.

Issue two:
Afk idle kick delay simply does not work, I put 300 as the value in key AutoKickIn.

**Cmi Version (using`/cmi version`):** 
9.1.0.6
**Server Type (Spigot/Paperspigot/etc):** 
Purpur 1.18.1
**Server Version (using `/ver`):** 
1.18.1

**Comment by Zrips** [comment]
Its not enough to only enable ModifyChatFormat if you want to have more complex features. Anything relating to hover over messages and similar will need ClickHoverMessages to be enabled, this includes [item] and links
Player gets a kick after define time starting from when he entered afk mode, in which case he needs to do that manually or have cmi.command.afk.auto which would put player into afk mode automatically after defined time.
