### ISSUE TITLE
BedInteraction disable respawn

### ISSUE THREAD

**Issue by Saintg0at** [Zrips/CMI#6574]
hi, I want to disable the respawn on the bed!
  there used to be a Bedinteraction setting, but now I can't find it...

**Comment by CloudeLecaw** [comment]
negate the permission for it.
In CMI/Settings You find a file called Homes.yml
Disable the Bedinteractions there.
![image](https://user-images.githubusercontent.com/12080017/234224188-fc2639d3-1484-4ca8-afcc-628b3dbac68f.png)

In Config.yml of CMI you also can set the RespawnOrder make sure bedLocation is not in the first positions ;)
![image](https://user-images.githubusercontent.com/12080017/234225122-e0b5e974-f934-4677-ac55-44e398b60345.png)
