### ISSUE TITLE
customrecipe

### ISSUE THREAD

**Issue by dan28000** [Zrips/CMI#6577]
cmi customerecipe command doesn't allow to edit recipes above id 127 in gui or cmd /cmi customrecipe edit <id>
there's no error just message that item with that id doesn't exist

![ver](https://user-images.githubusercontent.com/84990628/149630822-df568ace-da0b-429f-bab3-d294b6303671.PNG)

edit
also there's no death message for void fall it just shows default vannila death message

**Comment by Zrips** [comment]
You have 127 custom recipes?

**Comment by dan28000** [comment]
Yes if you create more then 127 recipes then any recipe after 127 becomes invalid for editing in GUI so you can only edit it in config.
The recipes are for example mob spawn eggs, corals, ores, saddles, etc.. you get the idea.
File of custom recipes is over 100KB in size.

**Comment by prototype464** [comment]
This seems like quite the limitation, I was planning on adding a plethora of custom items and recipes to my network which is well-over 127.
