### ISSUE TITLE
Wartungs modus

### ISSUE THREAD

**Issue by master861** [Zrips/CMI#6586]
**Description of issue:**
Whit out changed anything after some time my server get into the maintance mod

**Cmi version  (using`/cmi version`):**  9.1.0.6

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.18.1

plugins: luckperms,EasyPrefix-1.8.2,FastAsyncWorldEdit-Bukkit-2.0.1-SNAPSHOT-69,PlaceholderAPI-2.11.1, cmi

**Comment by CloudeLecaw** [comment]
may u created a sheduler?

**Comment by master861** [comment]
sorry my english is not the best but dint change anything i nthe config or any yml file cmi depends on

**Comment by Zrips** [comment]
Server wont enter maintenance mode without it being manually triggered with a command. Source of command is unknown and cant really say what triggered it, but something did at some point. Would simply try to see if there is any pattern when that happen, maybe specific amount of time passes after server start or at specific time of the day, but at at the end of day its simply issue with configuration of a plugin, CMI or another one.
