### ISSUE TITLE
Kit issue

### ISSUE THREAD

**Issue by NightLife-SG** [Zrips/CMI#6587]
**Description of issue:**
When a user inherit a group that has higher weight that the one that has the specific kit permission,it doesnt let them access that kit anymore

**Cmi Version (using`/cmi version`):9.1.0.5

**Server Type (Spigot/Paperspigot/etc):paper
**Server Version (using `/ver`):1.18.1

**Comment by Zrips** [comment]
Are we talking about 2 kits with same command name but different weights? Could you give actual example of those 2 kits?
