### ISSUE TITLE
Glow placeholder broken

### ISSUE THREAD

**Issue by OverBrave** [Zrips/CMI#6590]
I'm having trouble with the glow placeholder after switching to 1.18. Normally the placeholder would not rotate any color when the glow was not on. But now it turns white.

![image](https://user-images.githubusercontent.com/47111280/150013431-2fe7b1b3-b3f7-4a61-bb79-d44a189e35f2.png)

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/47111280/150013062-003af169-ecb6-487a-bb8a-12f6a8c06ae8.png)

**Comment by Zrips** [comment]
Good point, will make few changes to avoid including color code if player isint actually glowing.
