### ISSUE TITLE
BedEventOnLeave error

### ISSUE THREAD

**Issue by roggy666** [Zrips/CMI#6592]
![Screenshot_2022-01-20-11-30-04-952_com teamviewer teamviewer market mobile](https://user-images.githubusercontent.com/59109355/150314381-6670c90e-4f0b-4df5-a629-9fce7e789559.jpg)

Cmi version: 9.1.0.6

**Description of issue:**
Error

---
On screenshot

```
Screenshot
```

**Cmi Version (using`/cmi version`): 9.1.0.6

**Server Type (Spigot/Paperspigot/etc):**  purpur 1.17.1

**Server Version (using `/ver`):**  

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Will be fixed with next CMILib update
