### ISSUE TITLE
Player can /warp pvp without permission

### ISSUE THREAD

**Issue by fortunatas1** [Zrips/CMI#6593]
Player can /warp pvp without permission.
[Server thread/INFO]: Aiva1234 issued server command: /warp pvp Questas
Default permissions: [---](https://cdn.discordapp.com/attachments/526402563847880725/932704362990555186/unknown.png)

CMI Version: 9.1.0.6
Type: Purpur
Version: 1.17.1

**Comment by CloudeLecaw** [comment]
Look what went wrong on your server, by Default players cant use cmi xommands why have no permission for, they do not even see them in tabcomplete. If they does it means somewhere onnyour site is a permission leaks. So check on a Test server your purpur, cmilib, cmi  (no permission System) also check that ops.json is empty.   Then login and try to use /warp ;)

**Comment by fortunatas1** [comment]
> Look what went wrong on your server, by Default players cant use cmi xommands why have no permission for, they do not even see them in tabcomplete. If they does it means somewhere onnyour site is a permission leaks. So check on a Test server your purpur, cmilib, cmi (no permission System) also check that ops.json is empty. Then login and try to use /warp.. you will see your not able to warp

Yes. In test server if you want teleport other player with warp you need cmi.command.warp.others permissions, but in my server i don't know why and how, if you want teleport other player with warp you need only cmi.command.warp permissions, not warp.others

**Comment by CloudeLecaw** [comment]
> > Look what went wrong on your server, by Default players cant use cmi xommands why have no permission for, they do not even see them in tabcomplete. If they does it means somewhere onnyour site is a permission leaks. So check on a Test server your purpur, cmilib, cmi (no permission System) also check that ops.json is empty. Then login and try to use /warp.. you will see your not able to warp
> 
> Yes. In test server if you want teleport other player with warp you need cmi.command.warp.others permissions, but in my server i don't know why and how, if you want teleport other player with warp you need only cmi.command.warp permissions, not warp.others
..well thats wrong what u did. With thia permission you give Access to all warps. You can give just Access to certainnwarps with xmi.command.warp.warpname   or nage choosen this way. To need the permission you can design warps to need a permission.  Normaly to other ppayers they should use homes not warps.
