### ISSUE TITLE
/tpa autocomplete

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#66]
Can we get tab completion for /tpa and /tpahere?

**Comment by LogGits** [comment]
Tpa and tpahere should have tab complete capabilities. Can you please report what is occurring when using tab complete for you. What version of CMI are you using and does the tab complete work for ops?

**Comment by Zrips** [comment]
tpa and tpahere works for me. We will need more information on this

**Comment by Kbryst** [comment]
Will test more on Monday and provide everything for you (also on my other tickets too, sorry for the delay!)

**Comment by Kbryst** [comment]
It is actually somehow working now. I am so sorry ><

**Comment by Kbryst** [comment]
Sorry I know you closed this. Now it is not working again. I noticed this time it works for OP and not players. It looks like it only does this on some restarts. I can't find anything in the console, I did find one cmi error but I don't know if its related, its a player on join event. (I will post a bug report on it when I test it more). But I can't seem to recreate this on a test server with all the plugins consistently enough. 

On my main server I am able to restart the server and get it to work again, but then another restart it stops working. Can it possibly be conflicting with townyname updater or essentials? Shooting in the dark.

**Comment by Kbryst** [comment]
On a restart it stopped working again. 

I can't find what is conflicting with it. I copied the server fully over to another one and tab complete worked fine.

 I did notice if I do /cmi reload after startup the tab complete starts working again. The tab auto complete never stops working for OP, only for players.
