### ISSUE TITLE
Missing items when using /cmi condense

### ISSUE THREAD

**Issue by MysticalApple** [Zrips/CMI#6601]
**Description of issue:**
/cmi condense often gives slightly less items than it should. For example, I had 27 stacks of iron ingots in my inventory, used /cmi condense, and ended up with 2 stacks and 62 iron blocks and 7 iron ingots. The expected outcome should be 3 stacks of iron blocks and no iron ingots. The exact amount of iron that is missing seems to vary. Logging off and back in the server does not seem to fix this issue.

---

**Cmi Version (using`/cmi version`):** 
9.1.0.6

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
167

**Comment by Zrips** [comment]
You might want to check your recipes. If there is one which can result in less materials, then we are picking that one. Default vanilla converts 27 stacks into 3 full stacks of iron blocks

**Comment by MysticalApple** [comment]
The recipe for converting iron ingots to iron blocks is vanilla, and the exact amount that goes missing is different every time anyways. [Here is a video](https://www.youtube.com/watch?v=zv-gshV7sOQ) I've recorded of the issue occurring.

**Comment by Zrips** [comment]
Is there any chance for you to test this one out on a clean server or atleast disable other plugins and making sure that recipes.yml doesn't include any iron blocks in it? Did some testing with that already and it looks to be working correctly without any issues while converting in between on a clean server and we dont really have any extra feature which could randomize output of those commands and it doesn't look to be wide spread issue as no one else seemingly reporting issue like this, so most likely there is some specific conditions with your server which causes this behavior. Would be interesting to know what exactly derps out this so I could add a fix or it could be done from your side

**Comment by MysticalApple** [comment]
I can't seem to get it to happen when my ping is under about 80ms so I don't lose items when using a local server. It only seems to happen when I'm picking up the items as they're getting condensed, so I think it may have something to do with that. I'll keep trying to find a way to test it on a clean server though in case it's another plugin that's causing it.
