### ISSUE TITLE
Players spawn on roof instead of actual spawn location

### ISSUE THREAD

**Issue by Strahilchu** [Zrips/CMI#6607]
**Description of issue:**
Players spawn on the roof of spawn, in all servers that run CMI. 

**Cmi Version (using`/cmi version`):** 
Latest Latest Latest 9.1.0.6
**Server Type (Spigot/Paperspigot/etc):** 
Latest Paperbuild 1.18.1 #175

**Comment by Zrips** [comment]
Check your actual spawn point if its not obstructed by another block which could force a scan for new safe location. Updating spawn location might resolve that too.

**Comment by Strahilchu** [comment]
I trippled checked and reset spawns before even coming here so I have no idea what to do :/

**Comment by Zrips** [comment]
Could you show actual spawn area, with included spawn coordinates and Y coordinates of block where player spawns in? It all sounds more like safe location finder being triggered and sending players up, question would only be why. I need some way to debug this by reproducing issue.
