### ISSUE TITLE
Playtime problem

### ISSUE THREAD

**Issue by ZappySK** [Zrips/CMI#6608]
Hello, my /playtimetop are updating correctly, but when I use /playtime my playtime is stucked, and I have playtime placeholders in holograms, and in holograms it's not updating, can you please help me?
![image](https://user-images.githubusercontent.com/76651966/151313457-7fc49b10-6d86-404f-a317-15391321a30e.png)
![image](https://user-images.githubusercontent.com/76651966/151313497-b2f353ab-52dc-47cd-9861-38a5dd6162f1.png)

**Comment by ZappySK** [comment]
And I'm getting this error
https://pastebin.com/J03eer69
@Zrips

**Comment by ZappySK** [comment]
After restarting server, the /playtime get updated, but still stucked.. it is not counting the playtime

**Comment by ZappySK** [comment]
@Zrips

**Comment by ZappySK** [comment]
@Zrips can you help me?

**Comment by Zrips** [comment]
Should be fixed with next update.
