### ISSUE TITLE
Anvil on Paper: You need PaperSpigot branche type server for this to work

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#6611]
**Description of issue:**
Anvil command not working

Message: `You need PaperSpigot branche type server for this to work`

Grindstone, stonecutter and carthography are not affected.

(BTW: the name PaperSpigot is ancient. It's called Paper since a few years.)

---

**Cmi Version (using`/cmi version`):** 
CMI 9.1.1.1

**Server Type (Spigot/Paperspigot/etc):** 
Paper-177 (MC: 1.18.1)
Purpur-1537 (MC: 1.18.1)

**Server Version (using `/ver`):** 
1.18.1

**Comment by Zrips** [comment]
Ok, will fix anvil command not working. For naming thing, well, in general PaperSpigot is somewhat more obvious what it is than just saying "Paper" even tho that one is more accurate with current name.
