### ISSUE TITLE
Weird custom crafting bug

### ISSUE THREAD

**Issue by AlternativeSoap** [Zrips/CMI#6612]
**Description of issue:**

When I use "/customrecipe" and use a custom item to create another item, then it will be updated to it's originally item..

Example:
Changed "purple_dye" name to "Amethyst_Dust", you need to smelt amethyst to get dust in /customrecipe. Then I added "Amethyst_dust" to a new custom recipe, added it inside a shaped workbench around some armor , but whenever I do that it will replace " Amethyst_dust" with "purple_dye" again..
---

**Cmi Version (using`/cmi version`):** 
CMI: 9.1.1.1 SqLite
CMILib: 1.1.1.0
Server: Paper(163) 1.18.1

**Comment by Zrips** [comment]
You cant use custom data for recipes as this one utilizes Minecaft crafting engine which only recognizes items by material type and nothing else. Its a known limitation for time being.
