### ISSUE TITLE
/anvil still does not work despite being on Paper

### ISSUE THREAD

**Issue by SenPr** [Zrips/CMI#6613]
**Description of issue:**
I updated my Paper version and CMI recently and the anvil command stopped working

---

---

**Cmi Version (using`/cmi version`):** 
CMI: 9.1.1.1
CMILIb: 1.1.1.0

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
1.18.1 (Build 177)

**Relevant plugins (Delete if this isn't needed):**
The server is running behind BungeeCord, and there is a plugin on the BungeeCord that is called F3Name, which changes the server's name on F3.
Not sure if this is the issue and doubt it is.

**Comment by nhanledev** [comment]
I encoutered the same thing on Paper 1.17 build 177 and latest CMI

**Comment by CheckForUpdates** [comment]
Are you getting the "You need Paper branch type server" error when running /anvil ?

**Comment by Zrips** [comment]
This will get a fix with next version. Sorry for inconvenience.
