### ISSUE TITLE
/rankup from console

### ISSUE THREAD

**Issue by neokyle** [Zrips/CMI#6617]
Is it possible to run rankup commands when using setrank for players? Current as it is /setrank just changes the players rank unlike /rankup which runs the commands in the config that ser setup for the rank. /rankup doesn't work from console. I'm trying to force player rankups myself instead of letting them rankup on there own.

Optionally a solution would be to allow /rankup from console to force a player to rankup as if they were running the command themselves. Thanks.

**Comment by CloudeLecaw** [comment]
.....allow /rankup from console... good idea

bu for the whole rank commands if they do not work from console...

```
rankdown (playerName) (rankName) (confirm) (-cmd) (-cost)
rankinfo (playerName) (rankName)
ranklist
rankset (playerName) [rankName] (-cmd) (-cost)
rankup (playerName) (rankName) (confirm)
```

**Comment by Zrips** [comment]
Will add support for it with next update.
Tho as a reminder you do have option to autoRankup already
