### ISSUE TITLE
anvil command

### ISSUE THREAD

**Issue by andy3559167** [Zrips/CMI#6622]
Using cmi version 9.1.0.6 can use /anvil to open GUI normally. But using cmi version 9.1.1.1 can not open normally.

**Cmi Version (using`/cmi version`):** 
9.1.1.1
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
paper(177) 1.18.1-R0.1-SNAPSHOT

**Comment by WolverStones** [comment]
#6496  #6613
