### ISSUE TITLE
Horse Stats using CMI EntityInfo are slightly off in 1.18

### ISSUE THREAD

**Issue by horsecraft** [Zrips/CMI#6625]
the min/max horse stat values have been changed for 1.18, there's an approximate range of 4.86 - 14.57 b/s. The current multiplication value the CMI plug-in uses is ~42.16, which was correct for past versions, however, 42.16 does not honor the max value of 14.57 in 1.18 (0.3375*42.16=14.23).

https://minecraft.fandom.com/wiki/Tutorials/Horses#:~:text=To%20convert%20a%20horse%27s%20internal%20speed%20to%20blocks/second%2C%20multiply%20the%20internal%20value%20by%2043.17 
these guys use 43.17, I wonder if that could be looked into? 

---

**Cmi Version (using`/cmi version`): Latest

**Server Type (Spigot/Paperspigot/etc): Paper

**Server Version (using `/ver`):1.18.1

**Comment by horsecraft** [comment]
> Will update those values with next update.

What number did you multiply the internal value by to obtain the blocks per second number?
( when doing [0.32] * [set ratio] to get the final blocks per second, what set ratio did you use?)
I’m asking because the players on our server are very particular about their horse’s stats and they want to know how it compares with our other stats system.
Thank you!

**Comment by Zrips** [comment]
@horsecraft 
Get GENERIC_MOVEMENT_SPEED atribute from horse and multiply it by 43.17
