### ISSUE TITLE
Error in log by testing MC 1.13 

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/CMI#663]
here the logfile: https://pastebin.com/GP3AVEWT

**Comment by CloudeLecaw** [comment]
i cast paste full log file ist 3.25mb but it crashed my Server too over the Weekend.

here is the log - i cuttet it because it Looks foir me like the error is repeating and repteating:

https://pastebin.com/c74sK8KR

here the crashlog too may it helps..
https://pastebin.com/2eXLMDxM
