### ISSUE TITLE
Duplication with /inv

### ISSUE THREAD

**Issue by Bloodlex** [Zrips/CMI#6631]
**Description of issue:**

When taking out an item by /inv command, the item is transferred, but sometimes still exists in the source inventory of other player.

**Cmi Version (using`/cmi version`):** 9.1.1.2

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** git-Purpur-1547 (MC 1.18.1)

**Comment by Zrips** [comment]
Should be resolved
