### ISSUE TITLE
NamePlates disappear after re-log

### ISSUE THREAD

**Issue by Igzak** [Zrips/CMI#6648]
**Description of issue:**
I was faced an issue the nameplate suffix or prefix just disappear after re-log but on holograms all ok, I'm using a placeholder for it from /papi ecloud placeholders mcmmo - %mcmmo__party__name%

---

**Cmi Version (using`/cmi version`):9.1.1.2** 

**Server Type (Spigot/Paperspigot/etc):purpur** 

**Server Version (using `/ver`):git-Purpur-1541** 
Video:
(https://imgur.com/xRyO3kO)

**Comment by mrfloris** [comment]
You can add the command to eventcommands.yml so they're updated as well on loggin in.

**Comment by Igzak** [comment]
> You can add the command to eventcommands.yml so they're updated as well on loggin in.

This solution solved my problem

**Comment by Igzak** [comment]
> You can add the command to eventcommands.yml so they're updated as well on loggin in.

This won't work with placeholder %mcmmo_party_name%, it is just empty. 
If I perform command by myself from the console all works perfect, but if it does an event commands there is just empty string, i think the problem with that placeholder

**Comment by Igzak** [comment]
Also, I was trying asConsole!, I don`t know why but this won't update that specific placeholder

**Comment by Igzak** [comment]
Ok, i was test a lot of variants, bperm wont work with that placeholder but with other all ok, also i was change cmi.sqlite db default field of namepref and set that placeholder - same result

**Comment by Igzak** [comment]
I was tried to make a custom alias to run as sudo when the player joins - bperm:cmi.changeNamePlate! cmi nameplate reset but it says the user doesn`t have permission cmi.command.nameplate.admin O_o
