### ISSUE TITLE
I don't know if this is a bug

### ISSUE THREAD

**Issue by yuankun1** [Zrips/CMI#6659]
每日签到:
  Loc: world;214.58;69.42;-445.58
  Interval: 5.0
  Range: 8
  RangeExtra: 30
  Spacing: 0.25
  SpacingIcon: 0.5
  Lines:
  - '&f&l❆ &3&l[每日签到] &f&l❆'
  - 'ICON:head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGM1YWQ0M2NhODM2YTdlNTc3MmY4YmViNDJhZDBmZTFhYjNkZjRkYmExMWI4YWI4YjA4YmZhM2UxMzE3NmMifX19'
  - 
  - My holographic font is sometimes invisible
Input manually every time /cmi reload  It will show up
CMI version  9.1.1.1  Server Core mohist-1.12.2-307-server
Customer service core 1.12.2 2860

**Comment by yuankun1** [comment]
![image](https://user-images.githubusercontent.com/19505154/154485783-bd43974f-2517-44af-aa9b-39ceb46b3807.png)
![image](https://user-images.githubusercontent.com/19505154/154485901-758ba5f7-59f5-4323-a0d1-e6fdf5b460bd.png)
![image](https://user-images.githubusercontent.com/19505154/154485965-1b4b84ce-eece-4140-8cf3-35533fab5d9b.png)

**Comment by yuankun1** [comment]
It will disappear only when I reach this area

**Comment by Zrips** [comment]
At this point its hard to say without knowing more about this issue. But in any case, new version will come out soon with some changes relating to holograms and new handling. If that doesn't resolve your issue, let me know with a new ticket, tho you are using modded server and plugin doesn't officially support servers like that. Besides that there could be basic issue with head textures not loading in time. Some testing on your end might be needed to narrow down possible causes

**Comment by yuankun1** [comment]
> At this point its hard to say without knowing more about this issue. But in any case, new version will come out soon with some changes relating to holograms and new handling. If that doesn't resolve your issue, let me know with a new ticket, tho you are using modded server and plugin doesn't officially support servers like that. Besides that there could be basic issue with head textures not loading in time. Some testing on your end might be needed to narrow down possible causes

I know some reasons
I'm adjusting two options for display sight distance
For example, I created two holograms very close
Then adjust the sight distance to about 35 and switch the world back

There's a chance you won't be able to see
