### ISSUE TITLE
Issue with SignChangeEvent event

### ISSUE THREAD

**Issue by EpicPlayerA10** [Zrips/CMI#6663]
**Description of issue:**
When I try to change text of sign in `SignChangeEvent` with colored text and player does not have permission to colors (`cmi.colors.sign.[color]`) then text does not have color. In my opinion it should forcefully show color when text is set by plugin.

Code:
```java
@EventHandler
public void onSignChange(SignChangeEvent event) {
    event.setLine(0, ChatColor.GREEN + "[Test]");
}
```

Player without permission:
![obraz](https://user-images.githubusercontent.com/62206933/154766250-ce391e0f-721b-4edb-a84b-58316e3c7ad2.png)
 
Player with permission:
![obraz](https://user-images.githubusercontent.com/62206933/154766164-a1f76d01-9700-4754-b491-c8d3f11f41e6.png)

---

**Cmi Version (using`/cmi version`):** 
![obraz](https://user-images.githubusercontent.com/62206933/154766555-57349a73-c411-4bd8-901d-8e3cf60a1da0.png)

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 
![obraz](https://user-images.githubusercontent.com/62206933/154766589-d4fb7ff0-5254-4bdc-b4f3-aadc83591d4c.png)

**Comment by Zrips** [comment]
You can simply set
`@EventHandler(priority = EventPriority.HIGH)` if you want to change colors after CMI processed those ones.
