### ISSUE TITLE
Will be fixed with next update

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#6665]
> Will be fixed with next update
> 
> _Originally posted by @Zrips in https://github.com/Zrips/CMI/issues/6629#issuecomment-1041575349_

It's not fixed :/

**Comment by Zrips** [comment]
Players which can see vanished players will be able to see particles from those players. Other than its it seams to be working correctly as of quick test. Are you sure you can see particles coming from a player you can't see? And which plugin are you using to make players invisible to others?

**Comment by NoltoxGit** [comment]
> Players which can see vanished players will be able to see particles from those players. Other than its it seams to be working correctly as of quick test. Are you sure you can see particles coming from a player you can't see? And which plugin are you using to make players invisible to others?

I use PremiumVanish, with CMI's Vanish module enabled.

**Comment by Zrips** [comment]
Does player vanish mode gets properly indicated with /cmi info [playerName] command?

**Comment by NoltoxGit** [comment]
I don't know what change I made on my server, but the problem is solved.
Good day to you ^^
