### ISSUE TITLE
/cmi togglecompass enable - turns off the boss bar.

### ISSUE THREAD

**Issue by SlavkaCool** [Zrips/CMI#6669]
**Description of issue:**
Hello, there is a problem when using the command "cmi togglecompass". When I enter the command "cmi togglecompass enable" the bossbar is disabled, and when "cmi togglecompass disable" the bossbar is enabled
and it depends on PlaceHolders: %cmi_user_toggle_compass% %cmi_user_togglename_compass%

https://skr.sh/vCdHY778cAN?a
---

**Cmi Version (using`/cmi version`): 9.1.1.3** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`): 1.18.1_187**

**Comment by Zrips** [comment]
Should be fixed with next update

**Comment by SlavkaCool** [comment]
Thanks
