### ISSUE TITLE
/cmi toggletotem - it doesn't work properly

### ISSUE THREAD

**Issue by SlavkaCool** [Zrips/CMI#6670]
**Description of issue:**
when disabling "/cmi toggletotem", the bossbar strip does not disappear. And if it was initially disabled and the totem is triggered, after switching on the bossbar strip does not appear

https://skr.sh/vCd1Qf8exYB?a
https://skr.sh/vCdefuMYTMe?a
---

**Cmi Version (using`/cmi version`): 9.1.1.3** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`): 1.18.1_187**

**Comment by Zrips** [comment]
Should be resolved with next update

**Comment by SlavkaCool** [comment]
Thanks
