### ISSUE TITLE
Mirror can duplicate ShulkerBox

### ISSUE THREAD

**Issue by TheNylox** [Zrips/CMI#6672]
You are able to duplicate Shulker Box with mirror

**Cmi Version (using`/cmi version`):** 
https://i.imgur.com/pkHWeJZ.png

Paper git-Paper-404 (MC 1.17.1)

**Comment by Zrips** [comment]
Can you elaborate on this one? What is exactly duplicated? As contents of shulker box should not be copied over.

**Comment by TheNylox** [comment]
You can place shulker boxes with mirror without have it in inventory. Example i got 1 shulker box, place it with mirror (so i placed 4 shulker box) then break it and get x4 shulker boxes

**Comment by Zrips** [comment]
Players in creative mode will not spend blocks while placing them, in survival you should be required to have enough of those to be able to place it on ground.
is this only an issue with shulker boxes?

**Comment by TheNylox** [comment]
This happen in survival mode. I'm going to rec a video

**Comment by TheNylox** [comment]
Solved with the version 9.1.2.0
