### ISSUE TITLE
RT Portal Command Not Working

### ISSUE THREAD

**Issue by TenacityKrikkit** [Zrips/CMI#6673]
Hi! I am trying to add a command to a portal which will cause a player to be randomly teleported in a select world, named Tenacity 2 - take 2, but players are not being randomly teleported into the selected world.

Current portal command is written out as:

/cmi rt [playerName] Tenacity 2 - take 2

Thank you in advance for your help!

---

**Cmi Version (using`/cmi version`):** 9.1.1.3

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.18.1

**Comment by CloudeLecaw** [comment]
The the issues come with you worldname.
Tenacity 2 - take 2

The spaces in its worldname

Habe you tried:
/cmi rt [playerName] Tenacity__2__-__take__2 ?

**Comment by TenacityKrikkit** [comment]
Thanks for responding! Unfortunately, I have tried /cmi rt [playerName] Tenacity_2_-_take_2 and /cmi rt [playerName] Tenacity__2__-__take__2. Neither work.

**Comment by Zrips** [comment]
Will be fixed with next update, but you will still need to use command as @CloudeLecaw mentioned and try to avoid using spaces in world names, this only adds more situations where things could brake. Use _ for spaces in world names. But in any case, it should work properly with next update.
