### ISSUE TITLE
Skript economy Incompatibility

### ISSUE THREAD

**Issue by Arthful** [Zrips/CMI#6690]
**Description of issue:**

Skript is unable to retrieved the player's balance using CMI Economy  
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by CloudeLecaw** [comment]
Your using cmieinjector plugin with the normal vault?

Or Zrips mofifocated Vault Version?

In some cases one of the two Varriants might not work correctly.

Well you could try adding CMI to siftdependency in Plugin.yml of Skript. Habe you tried?

**Comment by Arthful** [comment]
I tried using both, and did not tried setting CMI as soft dependency in the
Skript's plugin.yml

**Comment by CloudeLecaw** [comment]
Try it. In case script might load before cmi then economy is not found. If you add it as softdependency then script will wait for cmi to be loaded on start if found on startup.

**Comment by Arthful** [comment]
I did tried it now but same result

**Comment by Arthful** [comment]
The player's balance from CMI is not reflecting in skript

**Comment by Zrips** [comment]
@Arthful 
Did you enabled CMIEconomy in CMI cofig file? What does CMI say on startup? As it should indicate economy type and you should get messages like
`Vault was found - Enabling capabilities. Economy: CMIEconomy`
`[Vault][Economy] CMI Economy hooked.`

**Comment by Arthful** [comment]
Yes it says that

**Comment by Zrips** [comment]
If even Vault detects CMIEconomy then entire issue will be with your script plugin or script itself.

**Comment by Arthful** [comment]
The skript is working fine with no errors or whatsoever

**Comment by Arthful** [comment]
I'm using the latest version of Skript and the needed addons for it.

**Comment by Zrips** [comment]
Looks to be that issue is resolved now. Closing.
