### ISSUE TITLE
Compatibility problems "/saveditems"

### ISSUE THREAD

**Issue by 849025143** [Zrips/CMI#6697]
I need to add - t:%player_name% when using other plug-ins to execute this command.
I found that if I enter ":", some plug-ins will not work properly.
Can you modify it？

**Comment by 849025143** [comment]
The full command is "/saveditems get xxx -t:%player_name%

**Comment by Zrips** [comment]
Having : in command isn't uncommon and plugin which fail to handle something like this should be fixed from their end. Making special exceptions for one variable will lead to special exceptions to all of them and then it will go out of hand.
