### ISSUE TITLE
warn bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#670]
use /cmi warn id
Trigger command /cmi jail id

When you use /cmi warn for two different people in a row
Will cause a bug

Example: 1. abc 2. bcc ( too player)

/cmi warn abc hack
Show jail abc 12h
Use /cmi warn for a short time

/cmi warn bcc hack
Show jail abc 12h ( <<<< BUG should be bcc will be jail

**Cmi Version (using`/cmi version`): 8.0.1.0

**Server Type (Spigot/Paperspigot/etc): paper

**Server Version (using `/ver`): 1.12.2

**Comment by p82183645** [comment]
and 

- Items into chat by simply using [item] variable. Chat handling and hover over messages should be enabled and handled by CMI for this to work.

no work
![image](https://user-images.githubusercontent.com/5382252/43303277-964e4e14-91a1-11e8-9a30-4a55ce3431bf.png)

**Comment by p82183645** [comment]
no any fix
![image](https://user-images.githubusercontent.com/5382252/43999336-06b79794-9e3d-11e8-877d-b1f3305fe851.png)

It should be Hensen_Zoe in jail
No kao71820

**Comment by Zrips** [comment]
Test out 8.0.5.0, if issue is fixed, close this ticket.
