### ISSUE TITLE
Startup problems with CMILib

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#6701]
**Description of issue:**
Hello, 
I just updated all my plugins including CMI & CMILib, but when I restart my server (I tried several times), it says that CMILib 1.1.1.1 is still running and not CMILib 1.1.1.2.

**ERROR:**
[Logs](https://mclogs.minestrator.com/ar56clM)

**Cmi Version (using`/cmi version`):** 
[CMI : 9.1.2.1 BungeeCord CMIB (MySQL)](https://prnt.sc/qNNIQ55ABO6W)
**Server Type (Spigot/Paperspigot/etc):** 
Purpur
**Server Version (using `/ver`):** 
Purpur-1565 (MC: 1.18.1)*

**Comment by CloudeLecaw** [comment]
the issues is inside plugin.yml Zrips forgot to update the version in it.
Use 7Zip (or Winrar)
Open the jarfile with it
Open the file plugin.yml
Change the version from  `version: 1.1.1.1` to version: 1.1.1.2
save the file. (may check if the changed where taken
restart the server

Now it should work as aspected

**Comment by NoltoxGit** [comment]
Okay thanks for your answer (I'll know if it happens for other plugins next time ^^).

But I have a little problem when I open the .jar with 7zip and I open the pluglin.yml and I modify it is not saved :/ (when I do ctrl+s or save in the menu "Files" of N++).

**Comment by NoltoxGit** [comment]
The problem has been solved in a private message on Discord. Thanks @CloudeLecaw 👍
