### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by Impactic48** [Zrips/CMI#6712]
**Description of issue:**
Locale_EN.yml in CMI
Typo:
CantUseCommand: '!actionbar!&cCan''t use command while in combat mobe. Wait: [time]'

Should be:
CantUseCommand: '!actionbar!&cCan''t use command while in combat mode. Wait: [time]'

**Cmi Version (using`/cmi version`):** 9.1.3.0

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** Purpur-1566 1.18.1

**Comment by Zrips** [comment]
Thanks, will fix it with next release
