### ISSUE TITLE
Hologram problem

### ISSUE THREAD

**Issue by TheWater1105** [Zrips/CMI#6718]
When the hologram is set to interval, that is, when the hologram is updated, the situation in the picture appears on the console.
CMI: 9.1.3.0, CMILib: 1.1.2.0, Server: paper-1.18.1-216
![QQ截图20220308020442](https://user-images.githubusercontent.com/101169147/157183851-3db7d1ef-10e9-407f-b012-6ce8115ac377.png)
![QQ截图20220308020450](https://user-images.githubusercontent.com/101169147/157183860-887d9060-736d-4128-9097-46c2b92d943e.png)
![QQ截图20220308020501](https://user-images.githubusercontent.com/101169147/157183868-42934195-55a7-49d0-87a7-48c62dda9326.png)

**Comment by mrfloris** [comment]
Could you perhaps include your hologram.yml and do you know when this triggers? like, when someone enters the chunk or when they join the server, or when they interact with a hologram?

**Comment by Zrips** [comment]
Please update to latest CMILib and issue should be resolved now.
