### ISSUE TITLE
Death message

### ISSUE THREAD

**Issue by dan28000** [Zrips/CMI#6729]
No death message for being pricked to death by berry bush
running 1.16.5 ver and CMI 9.1.2.0 tryed it on latest CMI also same thing
![image](https://user-images.githubusercontent.com/84990628/158016650-d9bfdac0-c3c5-4694-9a10-1e8a5808b264.png)
also i feel death messages are sometimes buggy
i found one example where CMI death message didn't show up
<player1> hit the ground too hard whilst trying to escape <player2>

**Comment by Zrips** [comment]
Will be fixed with next update
