### ISSUE TITLE
Request: Warp Groups

### ISSUE THREAD

**Issue by k0nker** [Zrips/CMI#674]
Warp Groups.

It would be great if we could group warps together and have them show that way and give the permission for each warp group so players can see them.

Example:
/setwarp Game1
/setwarp Game2
/setwarp Game3

/setwarp Store1
/setwarp Store2
/setwarp Store3

/editwarp Game1

From within the editor, or maybe via a slash command, assign Game1 to the warp group Games. If the player has the permission cmi.warpgroup.games then they can type /warps games and it will show the warps that are in the games group that they have access to. So if they have access to warpgroup.games they can pull up the games warp submenu, and then that will check which warps that are in the warp group Games the player has permission to access just like normal. If they have warp.game1 and warp.game2 but not warp.game3, they will only see game1 and game2 as options. 

The standard /warp command would still open the overall warp GUI with all warps you have access to. Maybe with a bar along the bottom to the groups that you have access to if you want to narrow the list that way.

**Comment by CloudeLecaw** [comment]
hmmm same for Portals pls :-D
