### ISSUE TITLE
Glow gui (config)

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#6742]
Hellow!

Would it be possible to add a boolean option for /glow gui (like for kits and warps) in `config.yml`?
*Edit: And disable the glowing module in `modules.yml`.

**Comment by ItLucifer-MRPG** [comment]
It would be nice to have an module option to completely disable it, but generally glow should do anything unless you actually do the /glow command and give a player a glow.

**Comment by NoltoxGit** [comment]
### Suggestion moved [here](https://github.com/Zrips/CMI/discussions/6967).
