### ISSUE TITLE
One time usage kits that cost money allways try to check your money even after you have already used them for the max times.

### ISSUE THREAD

**Issue by SleepyScallop** [Zrips/CMI#6745]
**Description of issue:**
Create a one time use kit that cost money, use it, and then restart your server. Afterwards when logging on type /kit kitnamehere and then it will say you dont have enough money for the kit even though you have already used the kit once. This should not happen.
---

**Cmi Version (using`/cmi version`):** 9.1.3.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.18.2

**Comment by Zrips** [comment]
Get a fix with next update
