### ISSUE TITLE
Tab completion cmi info not working

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#6746]
**Description of issue:**
The alias `whois` no longer suggests player names

A workaround could be to turn on the alias (and tab!) for `info` but this could collide with the `/info` command from WorldEdit.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  # /cmi info $1-
  /info:
    Enabled: false
    Tab: false
  /whois:
    Enabled: true
    Tab: true
```

---

**Cmi Version (using`/cmi version`):** 
9.1.3.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.18.2

**Comment by x1p** [comment]
Double checked: that doesn't solve it.
`Plugins (3): CMI, CMILib, LuckPerms`

**Comment by Zrips** [comment]
Looking into it

**Comment by Zrips** [comment]
Ok, found issue, should be resolved with next version
