### ISSUE TITLE
Tons of Errors shown on console

### ISSUE THREAD

**Issue by sunnydive** [Zrips/CMI#6748]
So there's a lot of ERRORS & WARNS that I do not understand in the console, It can be seen in the pastebin below. Recently there's a few times where server suddenly crash/server restart and many players lost their data, their account age, inventories, enderchest or anything, they just completely reset to a new player. Not sure what's going on.

---

**ERRORS:**
```
######################
https://pastebin.com/7BF923Sn
######################
```

---

**CMI 9.1.3.0:** 

**Airplane:** 

**1.17.1** 

Thank you very much for your time :D

**Comment by Zrips** [comment]
Check your scheduler file as it looks to have some formatting mistakes. 
Another thing "20.03 01:11:39 [Server] INFO java.lang.IllegalArgumentException: Newer version! Server downgrades are not supported!" which would indicate that you might downgraded your server from 1.18 to 1.17 which mainly broke custom recipes, so ether try to modify that file manually to fix format and match older one for those recipes or you will need to recreate those from scratch on 1.17 server.
