### ISSUE TITLE
Bossbar enabled/disabled status message is opposite

### ISSUE THREAD

**Issue by steven-archer** [Zrips/CMI#6749]
Bossbar compass says "enabled" when it is disabled, and says "disabled" when it is enabled.
![disabled](https://user-images.githubusercontent.com/23382181/159167700-f91d6305-a3e5-4334-b3c9-c9c798102702.gif)
![enabled](https://user-images.githubusercontent.com/23382181/159167707-29a39ed0-8eba-451c-b166-c4ba9969861e.gif)

Versions:
![image](https://user-images.githubusercontent.com/23382181/159166878-6c883ea8-c668-43c1-97e5-23c6961abb3a.png)

**Comment by Zrips** [comment]
Should be fixed with next update
