### ISSUE TITLE
Chunky/ChunkyBorder & SelectionVisualizer Warns in Console

### ISSUE THREAD

**Issue by rio-stars** [Zrips/CMI#6751]
I have made sure CMI, CMILIB, Paper, Chunky and ChunkyBorder were up to date. 
It still shows these warnings in the console: https://pastebin.com/Y7iVjfS8

CMI Version: 9.1.3.1 SqLite
CMILIB Version: 1.1.2.3

Server Type: PaperSpigot

Server Version: git-Paper-265 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Fixed and posted new version
