### ISSUE TITLE
custom text's <CC> console command doesn't recognize [playerName] within custom alias

### ISSUE THREAD

**Issue by notbike** [Zrips/CMI#6757]
**Description of issue:**
what i'm trying to do:
let the player click on a text to tp to a certain area and give him/her certain permission.

Since <CC> console command with in custom text doesnt take multiple commands, I created an custom alias named "gameover", and put my 2 commands in there. Then i insert my custom alias in btween <CC></CC>.

When i click on the text, I was teleported to my desired location, but the permission failed,
no error in the console, except luckperm stating that it doesn't recognize [payerName]

---
**Console**

```
[17:37:56 INFO]: Agreymeow issued server command: /cmil shadowcmd 1737537772 (gameover)
[17:37:56 INFO]: [LP] [playerName] is not a valid username/uuid.
```
---
**Custom Text file**
```
`<T>&aClick here &6to return to ManHunt lobby!</T><H>&bClick to Return!</H><CC>gameover</CC>`
```
**Custom alias**
```
  gameover:
    Cmds:
    - asConsole! lp user [playerName] permission unset gamestart
    - cmi tpallworld spawn spawn;-68.5;4;109.5 -a
 ```
---

**Cmi Version (using`/cmi version`):** 9.1.3.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 
```
This server is running Paper version git-Paper-409 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c53577e on ver/1.17.1)
You are running the latest version
Previous version: git-Paper-252 (MC: 1.18.2)
```

**Comment by CloudeLecaw** [comment]
The reason is simple because u run an other custom alais that no longer got triggered by the Player. Execute it as player. And use the asConsole paramters inside the custom alais
