### ISSUE TITLE
Cannot use most commands - Broken integration with Ultra Permissions

### ISSUE THREAD

**Issue by Guddina-tim** [Zrips/CMI#676]
**Description of issue or feature request:**

I updated Ultra Permissions (uperms) to the newest version. On my test server things seemed to be working fine so I went to the live server with it. That's when most CMI features broke. No one can use alias commands, and even when not using the aliases a number of CMI commands do not work.

I reported to the Ultra Permissions developer (TechsCode) and he said that CMI needs to be updated to properly accept the new Ultra Permissions version (3.0.1_1). He also said that he would be willing to help you update to fix the integration if you need assistance. 

I will gladly donate to the project if it helps push this bug up the priority list for fixing.

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**

I have many errors relating to this when different commands are used. Here are two of them:

- This happens when a player joins the server: https://pastebin.com/uZqiaBCY
- This happens when a player uses a cmi command: https://pastebin.com/uZqiaBCY
- Whenever an OP uses a command without using the alias, the attached screenshot shows up in game and some of the commands don't work at all, even for OPs.

![internalerror](https://user-images.githubusercontent.com/5891184/43360493-b95bd9dc-927b-11e8-9e68-0fdeab426751.PNG)

**Cmi Version (using`/cmi version`):** 8.0.1.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.12.2 latest build

**Comment by TechsCode** [comment]
The 3.x.x version of Ultra Permissions has gotten an entire new api. @Zrips would have to adapt to these GUI Changes. Ive you have any questions about the changes, just let me know

**Comment by Guddina-tim** [comment]
This is now resolved in the latest update. Thank you!
