### ISSUE TITLE
[item] and death message bug

### ISSUE THREAD

**Issue by hotspuraz** [Zrips/CMI#6761]
Colour bug when using [item] or killing a player

---
Players without permission to add colour to items can make colours show in [item] if their item has colour codes in it.
For example, this play does not have permission but his item still shows in chat as coloured:

![image](https://user-images.githubusercontent.com/38726257/160028803-ed0d7f0b-ed25-43e3-b08e-dad8316375a8.png)
---

**Cmi Version: 9.1.3.0** 

**Server Type: Paper 187** 

**Server Version: 1.18.1**

**Comment by Zrips** [comment]
Gets a fix with next version
