### ISSUE TITLE
Not fixed default config schedules.yml according to the latest update!

### ISSUE THREAD

**Issue by archroot** [Zrips/CMI#6762]
Not fixed default config schedules.yml according to the latest update!

https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-sentials-conomy-mysql-sqlite-much-more.3742/update?update=450165 
---
CMI: 9.1.3.2 BungeeCord CMIB  SqLite
CMILib: 1.1.2.4 
Server: Paper(790) 1.16.5-R0.1-SNAPSHOT

**Comment by therealatsuga** [comment]
Same issue here running purpur 1.18.2
