### ISSUE TITLE
bug report 

### ISSUE THREAD

**Issue by sedrftcvgybhun** [Zrips/CMI#6763]
**Description of issue:**

https://mclo.gs/gOeGR3h
---
line 1181
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## https://mclo.gs/gOeGR3h ##
######################
```

**Cmi Version (using`/cmi version`):** 

**Server Type (SpigotPaper* 

**Server Version (using `/ver`):*1.18.2* 

**Relevant plugins (Delete if this isn't needed):*cmi*

**Comment by Zrips** [comment]
Will fix it, but you do have issue with custom alias setup as informed in your error log
