### ISSUE TITLE
Console error with SpecializedCommands

### ISSUE THREAD

**Issue by Henriiig** [Zrips/CMI#6770]
https://pastebin.com/SjLhWGW1

**Cmi Version (using`/cmi version`):** 

9.1.3.2

**Server Type (Spigot/Paperspigot/etc):** 

Papermc 1.8.8

**Comment by nhanledev** [comment]
It is because of the delay command now accept 3 args, please do the null check Zrips.

**Comment by Henriiig** [comment]
Is there anything that I can do right now to fix this?

> It is because of the delay command now accept 3 args, please do the null check Zrips.

**Comment by nhanledev** [comment]
> 

Add the 3rd arg to your delay command, eg `delay !30 something`

**Comment by Henriiig** [comment]
I will try that thank you

**Comment by CloudeLecaw** [comment]
You should be able to use your old delays without any arg aggain in latest cmi Version :)
