### ISSUE TITLE
Entering in Combat mode

### ISSUE THREAD

**Issue by ohAleee** [Zrips/CMI#6772]
### Discussed in https://github.com/Zrips/CMI/discussions/6651

<div type='discussions-op-text'>

<sup>Originally posted by **Bart0o** February 14, 2022</sup>
Currently, the player only enters combat if the final damage of the bukkit event is > 0

New Feature:
The player should enter combat mode even if the damage is == 0 (it happens if you have resistance). (maybe configurable to not remove the previous feature)</div>

**Comment by Zrips** [comment]
Will get a fix with next update
