### ISSUE TITLE
[Request] Ability to use percentages in /cmi money and /cmi exp

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#678]
The ability to use percentages in `/cmi money` and `/cmi exp`. So we can do `/cmi money take TheWranger 5%`  where it takes 5% of the players money, `/cmi money set TheWranger 5%` where it sets your money to 5% of whatever your prior balance was, and `/cmi money give TheWranger 5%` where it gives you 5% of whatever your prior balance was.
Same for `/cmi exp`

**Comment by Zrips** [comment]
/cmi money does have option to give a percentage of money
