### ISSUE TITLE
Hologram click issue.

### ISSUE THREAD

**Issue by 849025143** [Zrips/CMI#6781]
Plugin version: 9.1.3.3
Server version: 1.12.2
After the command is executed, it can still interact with each other anywhere.
YouTube：https://youtu.be/8AUNJtOJFBA
And right click issue：https://github.com/Zrips/CMI/issues/6780

**Comment by Bart0o** [comment]
@Zrips I have Same problem

**Comment by Zrips** [comment]
Should get fixed with next update
