### ISSUE TITLE
CMI - ChatFormatError

### ISSUE THREAD

**Issue by FlopyCZ** [Zrips/CMI#6788]
**Description of issue:**
I have `ModifyChatFormat: true` enabled in the config and when a player types something into the console it makes an error
---

**![image](https://user-images.githubusercontent.com/16838522/161419678-3b7364ed-2ead-4a55-8372-9ef1862a6faf.png)**
```
![image](https://user-images.githubusercontent.com/16838522/161419465-7aa67116-b468-4d6c-a455-70a14999d80f.png)
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
CONFIG: https://pastebin.com/hkkh0HPc
```

---

**![image](https://user-images.githubusercontent.com/16838522/161419552-ce087328-5fa4-4f1f-8709-05c4d46102bc.png)** 

**Purpur** 

**1.18.2** 

**![image](https://user-images.githubusercontent.com/16838522/161419581-82663e5b-6df1-4893-88fc-1669b7be7669.png)**

**Comment by CloudeLecaw** [comment]
You should paste(or pastebin) your chat section of cmis config.
Its needed so we could see you may made an issue in its fornat.

**Comment by Zrips** [comment]
Could not reproduce issue with your setup, this could be caused by another plugin adding something into chat format which fails to be processed properly for some reason. Would be nice to know if this issues persists after disabling other plugins except CMI
