### ISSUE TITLE
/stats and /cmi stats

### ISSUE THREAD

**Issue by frank267195** [Zrips/CMI#6789]
請問如果我想把 /stats 這個簡寫指令去除要怎麼做

What if I want to cancel the shorthand command /stats

**Comment by CloudeLecaw** [comment]
cancel?......
you can take it out by using alias.yml and disable it..

what you mean by cancel?

**Comment by frank267195** [comment]
> 取消？...... 你可以打開 alias.yml 並禁用它..
> 
> ```
>   #  
>   # /cmi stats $1-
>   /stats:
>     Enabled: false
>     Tab: false
> ```
> 
> 你說的取消是什麼意思？

Because I have other plugins that will use /stats, I want to say cancel the shorthand command and leave only /cmi stats

**Comment by CloudeLecaw** [comment]
Tab mean nit shown in tab. And set this tobfalse disables /stats   of curse u need a restart if u anabke / disable aliases

Well i think you can close the thread now :)

**Comment by frank267195** [comment]
> 它的選項卡平均值顯示在選項卡完成中，作為建議的使用命令。例如，當您鍵入 /st 並按 Tabulator 鍵時，命令 /stats 通常是建議之一。好吧，如果您已經將 enabled 設置為 false 則沒有效果（因為 /stats 不存在，這也意味著您無法隱藏它。 請注意，如果您啟用/禁用別名，則需要重新啟動。 通常，如果禁用它不應該有對您其他插件的/stats 的影響。 如果需要並且您有權限，您總是可以使用/cmi stats。:)
> 
> 好吧，我想你現在可以關閉線程了 :)

OKay Thanks.
