### ISSUE TITLE
[Request] Add Support for Chinese Simplified Language

### ISSUE THREAD

**Issue by f0rb1d** [Zrips/CMI#679]
**Add i18n support for Chinese Simplified**
Hi, I'm currently making the Chinese Simplified translation file for such brilliant plugin. Would you like to put it in the plugin after I finish it?

**Comment by XiangChen888** [comment]
大佬 
这里 双引号 改成 单引号 就可以 在新版本里面使用了。。但是英文的原文的确用的是双引号。这个功能本人暂未使用过，所以不知道改动后是否正常。算暂时的解决方案吧。感谢翻译！

> [Tue, 4. Sep 2018 15:00:24 CEST INFO] [CMI] Updated (EN) language
> file. Took 141ms
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN] org.bukkit.configuration.InvalidConfigurationException: while scanning
> a double-quoted scalar
>      in 'string', line 523, column 31:
>           commandAddInformationHover: "[玩家名]可用于获取玩家昵称。\n要在\
>                                       ^
>     found unknown escape character 要(35201)
>      in 'string', line 524, column 6:
>             要在命令中包含延迟,请键入: \ndelay 5! \n ... 
>              ^
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at com.Zrips.CMI.FileHandler.ConfigReader.getyml(ConfigReader.java:210)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at com.Zrips.CMI.FileHandler.ConfigReader.<init>(ConfigReader.java:40)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at com.Zrips.CMI.Config.LoadLang(Config.java:400)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at com.Zrips.CMI.Config.reload(Config.java:2089)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at com.Zrips.CMI.commands.list.reload.perform(reload.java:21)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at github.scarsz.discordsrv.listeners.DiscordConsoleListener.lambda$onGuildMessageReceived$0(DiscordConsoleListener.java:93)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at java.lang.Thread.run(Thread.java:748)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN] Caused by: while scanning a double-quoted scalar
>      in 'string', line 523, column 31:
>           commandAddInformationHover: "[玩家名]可用于获取玩家昵称。\n要在\
>                                       ^
>     found unknown escape character 要(35201)
>      in 'string', line 524, column 6:
>             要在命令中包含延迟,请键入: \ndelay 5! \n ... 
>              ^
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarNonSpaces(ScannerImpl.java:1911)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1845)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1029)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchDouble(ScannerImpl.java:1011)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:396)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:585)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:133)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:437)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     ... 18 more
>     [Tue, 4. Sep 2018 15:00:24 CEST INFO] [CMI] Failed to load Locale_CN.yml! Backup have been saved into
> plugins/CMI/FileBackups/2018-09-04 15-00-24 Locale_CN.yml
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN] org.bukkit.configuration.InvalidConfigurationException: while scanning
> a double-quoted scalar
>      in 'string', line 523, column 31:
>           commandAddInformationHover: "[玩家名]可用于获取玩家昵称。\n要在\
>                                       ^
>     found unknown escape character 要(35201)
>      in 'string', line 524, column 6:
>             要在命令中包含延迟,请键入: \ndelay 5! \n ... 
>              ^
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at com.Zrips.CMI.FileHandler.ConfigReader.getyml(ConfigReader.java:210)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at com.Zrips.CMI.FileHandler.ConfigReader.<init>(ConfigReader.java:40)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at com.Zrips.CMI.Config.LoadLang(Config.java:400)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at com.Zrips.CMI.Config.reload(Config.java:2089)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at com.Zrips.CMI.commands.list.reload.perform(reload.java:21)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at github.scarsz.discordsrv.listeners.DiscordConsoleListener.lambda$onGuildMessageReceived$0(DiscordConsoleListener.java:93)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at java.lang.Thread.run(Thread.java:748)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN] Caused by: while scanning a double-quoted scalar
>      in 'string', line 523, column 31:
>           commandAddInformationHover: "[玩家名]可用于获取玩家昵称。\n要在\
>                                       ^
>     found unknown escape character 要(35201)
>      in 'string', line 524, column 6:
>             要在命令中包含延迟,请键入: \ndelay 5! \n ... 
>              ^
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarNonSpaces(ScannerImpl.java:1911)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1845)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1029)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchDouble(ScannerImpl.java:1011)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:396)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:585)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:133)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:437)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
>     [Tue, 4. Sep 2018 15:00:24 CEST WARN]     ... 18 more
>     [Tue, 4. Sep 2018 15:00:24 CEST INFO] [CMI] SEVERE LOCALE FILE READ ERROR. Check your spelling! Changes will not be applied until you fix it or perform server restart which can result in locale file reset to default


The error is caused by double quotation marks during the config loading in new version cmi 8.0.8.1, so just change them to single quotation marks. I have never used the relatived functions, so probably it just solves the loading error. Thanks for the translation! 

  

> commandAddInformationHover: '&e[玩家名]可用于获取玩家昵称。\n&e要在\
    \要在命令中包含延迟,请键入: \n&edelay 5! \n&e同时也支持特定指令。\
    \更多信息请参见\n&ewww.spigotmc.org/wiki/cmi-specialized-commands/'




But in english locate file it does use the double quotation marks. 

> commandAddInformationHover: "&e[playerName] can be used to get player name \n&eTo\
    \ include delay in commands: \n&edelay! 5 \n&eSpecialized commands are supported.\
    \ More info at \n&ewww.spigotmc.org/wiki/cmi-specialized-commands/"

**Comment by f0rb1d** [comment]
@XiangChen888 好滴 感谢提醒 有时间我来修改
Thanks for your suggestion. I will fix it in my spare time.
