### ISSUE TITLE
/give command

### ISSUE THREAD

**Issue by Duckhunterone** [Zrips/CMI#6790]
When using the /give command to give items that have a stack of 16 or unstackable items for example swords it will give you a stack of more than the vanilla stack size e.g. /give DuckHunterOne diamondsword 3 will give you a stack of 3 swords and not 3 separate swords or /cmi give duckhunterone honeybottle 20 will give a stack of 20 instead of the stack size of 16. No error is displayed and illegalstacks deletes the items.

CMI: 9.1.3.3 BungeeCord CMIB  SqLite
CMILib: 1.1.2.4 
Server: Paper(266) 1.18.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b(CMIEInjector) CMI Chat: Enabled 
Modules -> 46 enabled 10 disabled: spawnerProximity, hpBossBar, tablist, ranks, votifier, shulkerBackpack, skin, spawners, spawnerCharge, [playerChatTag]

[https://youtu.be/3lD_NZrRa1A](url)

**Comment by CloudeLecaw** [comment]
Wenn you want to give away 3 sword u not stacked because u have a plugin that deleta illigal stack then you need to execute the command correctly.   Means for 3 swords..execute it 3 Times wothout amount or 1.   With 20 bittles execute it onces with 16 and once with 4 ( or 10/10)   its your own fault if u give stacks of something that is invailed. It would be possible to get these with vanilla command to. So its no issues from cmi site.

**Comment by Duckhunterone** [comment]
We have ran the same commands within our server for over 2 years with no issues, until the latest update. Illegal stacks deletes any over stacked items any server operator knows that. The swords was used as an example to show what happens nothing more. This happens only with the items that have a full stack of 16 for example honey bottles and ender pearls or single stack items but every other block in the game works correctly. Why would i run multiple commands when one command should and always has worked?

**Comment by CloudeLecaw** [comment]
> do the /minecraft:give command instead, as this takes stack size into account.

correct or use the command multiple times with correct stack size for that item

**Comment by Duckhunterone** [comment]
Thank you for the input but im not interested in a workaround. Im reporting a bug not asking for help to run vanilla or essentials commands.

**Comment by Cheezelaweeze** [comment]
like i already stated, THIS IS NOT A BUG. cmi is meant to copy the essentialsX command. and the essentialsX give command also has this "bug". This is not a problem with cmi. therefore me and CloudeLecaw's workarounds are the only way to get the command to work the way you want it to work. this is not an issue and should not be reported.

if you want you can make a new feature request and maybe say they should add a "-s" arg to take stack size into account.

**Comment by CloudeLecaw** [comment]
> Thank you for the input but im not interested in a workaround. Im reporting a bug not asking for help to run vanilla or essentials commands.

Its not a bug. It was a bug if it was not behavr like this before on your server.

**Comment by Zrips** [comment]
@Duckhunterone 
Not a bug in particular, but i can definitely understand why it might be an issue in some situations. What I could add is extra variable which would avoid stacking items above their max stack size if defined which would allow you to give out unstacked items while keeping original behavior. Look for next patch notes.
