### ISSUE TITLE
command /cmi importdate essenatials missing warps 

### ISSUE THREAD

**Issue by Jeroen123TC** [Zrips/CMI#6791]
**Description of issue:**
i was converting the data from essentials to cmi with the command "/cmi importfrom essentials home warp nick logoutlocation money mail"
only I have the problem that not all data is transfers, like I have with essentials 119 warps, and cmi has after the convertion 37 warps. see configs.

---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**

[Essentail warps.zip](https://github.com/Zrips/CMI/files/8408950/Essentail.warps.zip)
cmi warps: https://pastebin.com/Sf6HPNRi
---

**Cmi Version:** 
CMI9.1.3.3
CMIlib1.1.2.4

**Server Type (Spigot/Paperspigot/etc):** 
paper.1.17.1

**Server Version (using `/ver`):** 
1.17.2

**Comment by Zrips** [comment]
Should be up and running with latest version. There was some changes in Essentials data file structure which caused this import to no longer work as it should.
