### ISSUE TITLE
GodMode not working

### ISSUE THREAD

**Issue by bigenergy** [Zrips/CMI#6792]
**Description of issue:**

God mode doesn't work on version 1.12.2
---
I turn on god mode and it doesn't work, fall and mob damage still works the same as without god mode
---

**Cmi Version (using`/cmi version`):**  9.1.3.3

**Server Type (Spigot/Paperspigot/etc):** BukkitForge

**Server Version (using `/ver`):** 1.12.2

**Relevant plugins (Delete if this isn't needed):** cmi lib 1.1.2.4

**Comment by bigenergy** [comment]
God mode seems to work on version CMI9.0.4.6

**Comment by CloudeLecaw** [comment]
Well like allways u ahould update to latest cmi and cmilib before reporting anythng.

Request with old versuon issues are mostly ignored.
Well tested godmode in newest cmi+ spigot 1.18.2
And it working like allways.

So please:
1. Update cmi and cmilib first
2. Redo your test with godmode
3. Dont write " its not working" - this helps noone - type what you have tried and how you tested the gamemode, and why you think its not working..

So we are waiting for your responce, after you did the 3 little steps :)

Little nerdy fun fact:
I could also enable godmode - jump into the void - and tell after "Godmode is not working".... ;)

**Comment by bigenergy** [comment]
> Well like allways u ahould update to latest cmi and cmilib before reporting anythng.
> 
> Request with old versuon issues are mostly ignored. Well tested godmode in newest cmi+ spigot 1.18.2 And it working like allways.
> 
> So please:
> 
> 1. Update cmi and cmilib first
> 2. Redo your test with godmode
> 3. Dont write " its not working" - this helps noone - type what you have tried and how you tested the gamemode, and why you think its not working..
> 
> So we are waiting for your responce, after you did the 3 little steps :)
> 
> Little nerdy fun fact: I enabled godmode - jumped into the void - and was wondering how the void can kill a god.... ;)

CMILib 1.1.2.4 - latest
CMI 9.1.3.3 - latest

we are talking about version minecraft 1.12.2

**Comment by bigenergy** [comment]
support for this version is also indicated in the description on the spigot (https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/)
