### ISSUE TITLE
/cmi attachcommand will attach multiple nbts

### ISSUE THREAD

**Issue by DreamMiu** [Zrips/CMI#6793]
**Description of issue:**
When I stack the item again and attach /cmi attachcommand times, he gives the item extra nbt every time I use it.

1. give Stone*64 use :cmi attachcommand !limiteduse:1!;;!cc!cmi money give [playerName] 100
![image](https://user-images.githubusercontent.com/30835281/161714938-b5a5aa15-ab31-447b-827b-645784c60b91.png)
2. Each use adds an nbt
![image](https://user-images.githubusercontent.com/30835281/161715149-80329570-d046-4a75-8f50-2260c7f3e42e.png)
3.Multiple use will generate additional nbt
![image](https://user-images.githubusercontent.com/30835281/161715434-d57a815f-58b4-46b5-b72b-08d596a8866a.png)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Null
```
---
**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/30835281/161713613-fbdfc63a-862f-423a-a389-8961ac482c63.png)
**Server Type (Spigot/Paperspigot/etc):** 
Pufferfish 1.18.2-R0.1-SNAPSHOT
**Server Version (using `/ver`):** 
This server is running Pufferfish version git-Pufferfish-60 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 1d94256 on HEAD)

**Comment by Zrips** [comment]
Quick fix from your end would be to change locale and remove that character at end which derps out locale removal from existing item. Will try to fix it from my end with next version.
