### ISSUE TITLE
Option for disabled to accept or deny command format

### ISSUE THREAD

**Issue by MCLaraTeam** [Zrips/CMI#6797]
When a request is sent, the user receives a check and a cross in the chat. On some of my servers the players do everything via interface and don't have access to tab any command other than /menu

I would like to request an option to be able to deactivate that users receive the check and the cross.

**Comment by CloudeLecaw** [comment]
speaking of tpa? well if they should only teleport to others without others get ask give them access to
cmi tp?
command structure of cmis tp is on /cmi tp playername (playername)
players needs **cmi.command.tp** permission then they can teleport theirself to other players with **/cmi tp PLAYER**  or if alias activated **/tp PLAYER**

Note: this tp command cant teleport to cords just to players

**Comment by MCLaraTeam** [comment]
I want to remove this 
![image](https://user-images.githubusercontent.com/91991267/162132806-5d983be0-bb14-472a-8500-727c30385c67.png)

**Comment by CloudeLecaw** [comment]
So you want your players to need to type /tpaaccept because your geyser client players cant click it?

**Comment by CloudeLecaw** [comment]
What you want allready exist in the config.

``    # When set to true adds accept and deny buttons when sending tpa or tpahere requests
    DenyConfirm: true``

**Comment by Zrips** [comment]
@MCLaraTeam 
As @CloudeLecaw mentioned, you can disable those button with provided config option. it might not have been to clear where you can find those.
