### ISSUE TITLE
[Request] Add Teleport with your mount support

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#680]
It would be nice to have an Option to TP a Player that is sitting on his horse together with the horse too.
it could be all Kind of mount (and the boat)

Currently i Need to use an extra Plugin for this. 
[HorseTpWithMe](https://www.spigotmc.org/resources/horsetpwithme.8186/)

i thought CMI had this abbility allready..but no it does not :(

without HorseTpWithme
![image](https://user-images.githubusercontent.com/12080017/43389113-3111c516-93eb-11e8-85fc-2d77dbe2ce40.png)

withHorseTpWithMe
![image](https://user-images.githubusercontent.com/12080017/43389251-8960bd08-93eb-11e8-843b-0454310de9e8.png)

Could CMI get a simliar fuction so this Plugin could get off? :)
Maybe handles with a permisison… or the abillity to disable it if not wanted
currently CMI seems to support just TP while sitting on mount (or boat)

**Comment by Zrips** [comment]
This is a thing, could be with some issues with some another plugin prevents entity teleportations or spawning in particular areas, but it does work.
