### ISSUE TITLE
Improvements for the /cmi server command

### ISSUE THREAD

**Issue by 1ntent1on** [Zrips/CMI#6802]
Hello, since theres nice command /cmi sendall, it would be nice to have option for only "/cmi send nick server". Theres currently option to you "/cmi server <server> <player>" but theres small problem. That command can be executed only when you are at same server as the person. I do think that adding "/cmi send" or not having to be at the same server as the targetted person when using "/cmi server <server> <player>" would be really nice, specially for velocity users.

**Comment by CloudeLecaw** [comment]
I see you want to send Player A from Server B to Server C while your on Server C.

Well i dont think this is possible, but hey github is also here for feature request wishes like this :)

**Comment by 1ntent1on** [comment]
Hello, it doesn't exactly have to be like that. The player executing that command could be on any server. Basically same as /send command from bungee.
