### ISSUE TITLE
partial loading messages when using setspawn

### ISSUE THREAD

**Issue by dan28000** [Zrips/CMI#6804]
issuing /cmi setspawn or /cmi setfirstspawn results into CMI printing out in console part of reload/loading messages
![image](https://user-images.githubusercontent.com/84990628/162589099-c3f50c90-fe9d-4176-b785-210b16d0f23e.png)
![image](https://user-images.githubusercontent.com/84990628/162589300-fd34ecd6-01b9-46b0-9ff5-aa5906f23c93.png)

**Comment by Zrips** [comment]
Its not a really a bug in particular, plugin simply reloads config file due to it being updated with new information relating to spawn and firstspawn locations. You can simply ignore this for time being until those sections get moved to their own dedicated file in the future.
