### ISSUE TITLE
disableenchant is not working properly

### ISSUE THREAD

**Issue by Derdzio** [Zrips/CMI#6805]
disableenchant does not work properly for me the enchant can be fished out and does not disappear when items are moved by shift, how can I fix it?

CMI9.1.3.3 BungeeCord 
CMILib 1.1.2.4

Purpur 1.18.1-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Enchant disabling works on server level where in general all handling is done by server itself and not CMI beside it simply removing record of specific enchant. Some items might still contain disabled enchants until you move those. This should not really be an issue with fully restarted server and newly caught items with disabled enchants.
