### ISSUE TITLE
CMIs Image feature in Tablist

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6809]
It would be nice to allow the cmi images we know from ctext in Chat in the Tablist header and footer

![image](https://user-images.githubusercontent.com/12080017/162910952-c5f3f222-f920-4c58-8480-8e55050cf042.png)

this would allow us to give nice animations to the tablist may with some icons or a server icon... etc
or simpyl show the players head ;D

**Comment by mrfloris** [comment]
-> https://github.com/Zrips/CMI/discussions/new

Hey, this isn't a bug, please repost it as a new discussion, thank you.

**Comment by CloudeLecaw** [comment]
i know i hoped it will be moved there like other discussions too..well and sometimes Zrips also answers with "ok" and its dne in its next patch..you never know *g*
