### ISSUE TITLE
Improvement of the sign spy [SPAM]

### ISSUE THREAD

**Issue by LucidAPs** [Zrips/CMI#6811]
Please make it so that when players write no text in signs, the spy notification doesn't appear. Otherwise staff are spammed with empty notifications like these.

![image](https://user-images.githubusercontent.com/42933023/163033746-807c354e-63af-4786-8114-ed396a3a42dd.png)

**Comment by CloudeLecaw** [comment]
I agree often players use empty signs for building. these get postet to at the moment too what could loolna bit spammy for the spyer

**Comment by Zrips** [comment]
Will prevent empty messages being shown with next update
