### ISSUE TITLE
Silent output does not work

### ISSUE THREAD

**Issue by Verzante** [Zrips/CMI#6812]
Silent output (-s) for /cmi clear does not work even tho, it's available in the commands list.

Please fix it.

CMI version: 9.1.3.3
CMILib version: 1.1.2.5
Server: Purpur 1.18.1

**Comment by mrfloris** [comment]
I checked, the syntax is indeed implying the `-s` is an option: `/cmi clear (playerName) (item(-amount)) (-s) (+clearType)`

When I start a fresh install server with the latest cmilib and cmi, and i give myself some items and deop myself, making sure i am also without perms, groups and all that stuff. 

And I do (from console) `> cmi clear mrfloris -s`, i get no msg in game, and the inventory is empty. It seems to work as expected for me.
<img width="1242" alt="Screenshot 2022-04-15 at 17 39 51" src="https://user-images.githubusercontent.com/28841349/163591010-b56c2752-25f0-4c98-a34c-6c6191c814b2.png">

Maybe try to upgrade to 1.18.2, and upgrade cmi to 9.1.4.1, and try again. Also make sure the /clear is from cmi, try with /cmi clear like i've done.

<img width="592" alt="Screenshot 2022-04-15 at 17 41 52" src="https://user-images.githubusercontent.com/28841349/163591236-c195faf3-ae8b-4540-b6cc-c412e625bcab.png">

**Comment by Verzante** [comment]
I get this message to console:

[00:25:04 INFO]: [LuckPerms] [Messaging] Sending user ping for 'verzante' with id: 3383c77f-e1a0-4b85-af1c-eacedebbb40a
[00:25:07 INFO]: Verzante issued server command: /Deop verzante
[00:25:07 INFO]: [Verzante: Made Verzante no longer a server operator]
[00:25:22 INFO]: de_dok issued server command: /res auto d
[00:25:43 INFO]: You have removed 1 items from Verzante inventory (Online).

Command was "cmi clear Verzante -s" and executed from console

So its just a case of version 1.18.1. Please fix

**Comment by Verzante** [comment]
> I checked, the syntax is indeed implying the `-s` is an option: `/cmi clear (playerName) (item(-amount)) (-s) (+clearType)`
> 
> When I start a fresh install server with the latest cmilib and cmi, and i give myself some items and deop myself, making sure i am also without perms, groups and all that stuff.
> 
> And I do (from console) `> cmi clear mrfloris -s`, i get no msg in game, and the inventory is empty. It seems to work as expected for me. <img alt="Screenshot 2022-04-15 at 17 39 51" width="1242" src="https://user-images.githubusercontent.com/28841349/163591010-b56c2752-25f0-4c98-a34c-6c6191c814b2.png">
> 
> Maybe try to upgrade to 1.18.2, and upgrade cmi to 9.1.4.1, and try again. Also make sure the /clear is from cmi, try with /cmi clear like i've done.
> 
> <img alt="Screenshot 2022-04-15 at 17 41 52" width="592" src="https://user-images.githubusercontent.com/28841349/163591236-c195faf3-ae8b-4540-b6cc-c412e625bcab.png">

I get this message to console:

[00:25:04 INFO]: [LuckPerms] [Messaging] Sending user ping for 'verzante' with id: 3383c77f-e1a0-4b85-af1c-eacedebbb40a
[00:25:07 INFO]: Verzante issued server command: /Deop verzante
[00:25:07 INFO]: [Verzante: Made Verzante no longer a server operator]
[00:25:22 INFO]: de_dok issued server command: /res auto d
[00:25:43 INFO]: You have removed 1 items from Verzante inventory (Online).

Command was "cmi clear Verzante -s" and executed from console

So its just a case of version 1.18.1. Please fix

**Comment by Zrips** [comment]
Will be fixed with next version
