### ISSUE TITLE
Bug/Suggest with lockip

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#6817]
### Description of issue:
Hello !

For some time I have been having problems with the *lockip* function on my server, let me explain:
"From time to time some players (even me) can't connect because the IP is not valid anymore, so I have to go through the console and do `cmi lockip add PSEUDO 1.2.3.4`, which is quite annoying.

#### Suggestion:
Add an option in the config.yml to disable the *lockip* feature or add a permission like `cmi.command.lockip.bypass` that would allow players who have this permission to no longer get the message that the IP is invalid.

---

**Cmi Version (using`/cmi version`): 9.1.1.3** 

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): This server is running Paper version git-Paper-409 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c53577e on ver/1.17.1)**

**Comment by CloudeLecaw** [comment]
Well the issue Stil can happen, an ip can change every 24 hours.

**Comment by NoltoxGit** [comment]
> Well the issue Stil can happen, an ip can change every 24 hours.

Yes, but it's quite annoying, especially when I already have a plugin that whitelists some players who are under vpn or other that do not have a "stable" ip.

**Comment by CloudeLecaw** [comment]
well best might be to whitelist uuids here, what requie a online more true too...

**Comment by Zrips** [comment]
@NoltoxGit 
If you have internet provider which uses dynamic ip's then you should NOT use lockip command as it will fail. This is ONLY for those who have same ip to prevent from anyone else joining with different one. Adding bypass permission only defeats entire purpose of that command. Ether remove access to this command from users entirely or get them know that it might prevent them from joining if they have dynamic IP.
Side thing, this is more for a staff members to have extra protection against some one trying to log in with their name, most commonly used in offline type servers as anyone can use your name to atleast try joining and guessing login password.
