### ISSUE TITLE
Server crashes completely

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#682]
Just bought the plugin to test it on a almost empty test-server. Uploaded both CMI and its suggested vault. Server starts fine, but when the first player joins, it completely crashes. Tried both vault solutions, even without. Problem stays
`
[22:50:29 INFO]: Player123[/123.123.123.123:43227] logged in with entity id 24 at ([world]966.5, 4.0, 226.5)
A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x000000000000a866, pid=65, tid=0x00007f9dac3a8ae8
JRE version: OpenJDK Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
Java VM: OpenJDK 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
Derivative: IcedTea 3.8.0
Distribution: Custom build (Wed Jun 13 18:00:32 UTC 2018)
Problematic frame:
C 0x000000000000a866
Core dump written. Default location: /home/container/core or core.65
An error report file with more information is saved as:
/tmp/hs_err_pid65.log
If you would like to submit a bug report, please include
instructions on how to reproduce the bug and visit:
http://icedtea.classpath.org/bugzilla
/entrypoint.sh: line 15: 65 Segmentation fault (core dumped) java -Xms128M -Xmx1024M -jar paperclip.jar
(Daemon) ---------- This server has crashed! ----------
(Daemon) Exit Code: 139
`
**Cmi Version (using`/cmi version`):**
8.0.2.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot 1.13 build 64

Active plugins:
PermissionsEx
Worldedit
Worldguard

**Comment by Zrips** [comment]
/tmp/hs_err_pid65.log would be nice to have

**Comment by CloudeLecaw** [comment]
hm may a good Point here for me to insert…

i cast paste full log file ist 3.25mb but it crashed my Server too over the Weekend.

here is the log - i cuttet it because it Looks foir me like the error is repeating and repteating:

https://pastebin.com/c74sK8KR

here the crashlog too may it helps..
https://pastebin.com/2eXLMDxM

Looking in the log i often see this one:
```
[12:30:13] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.0.1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238) ~[spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:451) ~[spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227) ~[spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Modules.SpawnerCharge.SpawnerActionsListener.onSpawnerInteract(SpawnerActionsListener.java:252) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-69774b3-3f9d7f7]
	... 17 more
```

**Comment by Zrips** [comment]
@CloudeLecaw Something related to chunk relight process. Will test it out. Do you have FixOnChunkGeneration set to true?

**Comment by CloudeLecaw** [comment]
```
lfix:
  # This is heavy on server resourses feature, enable if you have to spare some or pregenerating world
  # When set to true, plugin will try to fix light issues on chunk generation
  # This will remove most light gliches but its not 100% bullet prof and some bugs can still be seen
  # In some cases you will need to relog to see updated light's
  FixOnChunkGeneration: true
  # List of worlds where we need to fix light issues on chunk generation
  WorldsToFix:
  - Demantra
  - Demantra_nether
  - Demantra_the_end
  - Demantra_old
```

**Comment by CloudeLecaw** [comment]
ok i turned it of for now :)

**Comment by Zrips** [comment]
Will have to turn this feature off for time being. Some glitches happening with 1.13 and when considering that its not best way and most efficient way in fixing light glitches and we do have lfix which can fix light glitches from entire map.

**Comment by Floef** [comment]
I can't find the log in /tmp/hs_err_pid65.log

**Comment by x1p** [comment]
I'm sorry, but my hosting provider doesn't show me this directory.

**Comment by CloudeLecaw** [comment]
ieatea 3.80?...
/home/buildozer/aports/community/openjdk8/src/icedtea-3.8.0/openjdk/hotspot/src/share/vm/prims/jni.cpp, line 735]…..

**Comment by CloudeLecaw** [comment]
> I'm sorry, but my hosting provider doesn't show me this directory.
You find in in the Folder called crash-reports in the main direcotry of your spigot. sometime on hard crashed it can be that the crashreport is saved in the maindirectory too… why ever :3

**Comment by x1p** [comment]
As told above, the crashlog you've asked, is here: https://hastebin.com/tuhimuhere.makefile
If you would like the server log as well, her you go: https://hastebin.com/abezacazat.md

To be clear: I have not even start to edit the config files, this is just plain default.

**Comment by CloudeLecaw** [comment]
this Serverlog just Shows that your Server was booted up correct.. read my thread About how to get he last one with the Errors or reasons we would Need ;)

**Comment by x1p** [comment]
3 time: this is the hs_err_pid65.log
https://hastebin.com/tuhimuhere.makefile

**Comment by CloudeLecaw** [comment]
ok i give it up… u missed aggain the SERVERLOG (not the current or so,  just the log when your Server crashed Nothing else)

But ok, may for Zrips your CrashReport is enough….

**Comment by x1p** [comment]
There is no more server log. The server suddenly stops and the log stops exactly at the point where the player joins. More is not written to the log because the server crashes.

**Comment by x1p** [comment]
The only thing that is viewable in the console is the text I wrote in the first message and I will repeat it again more readable here: https://hastebin.com/najowicawo.coffeescript

**Comment by x1p** [comment]
Normally I always get readable java errors. If so, I would have written it here. But this one is really crashing bad.

Just ran the server again with the latest and the preferred Vault1.6.10.jar (option 1 on the plugin page)
CMI is not happy with all the suggested vault versions.

[CMI] Vault was found but economy engine is missing. Use one from list provided in https://dev.bukkit.org/bukkit-plugins/vault/
[CMI] Vault was found but not economy plugin, you will have limited economy support
[CMI] Can't determine sound name for tag. Trying to defaulting to BLOCK_NOTE_HARP

**Comment by CloudeLecaw** [comment]
About your Plugin your log told us:
Listed Plugins of your log:
```
AntiAFKPlus.jar
ChestCommands-3.1.4.jar
ChestShop-3.9.2.jar
CMI8.0.2.0.jar
CustomHelp-0.3.jar
CustomTime-1.3.3.jar
FeatherBoard-4.11.1.jar
GriefPrevention.jar
ImageOnMap-3.1-120.jar
ImageOnMap-3.1-120.jar
ItemJoin-4.8.jar
ItemJoin-4.8.jar
jpa_2_1_0.jar
Libs of MV?...Multiverse?
MVdWPlaceholderAPI.jar
NightVision-1.0.jar
ormlite_5.jar
ormlite_jdbc_5.jar
PermissionsEx-1.23.4.jar
Rankup-2.9.1.jar
SuperPickAxe-1.3.jar
Vault-1.6.7.jar
VotingPlugin-5.14.jar
worldedit-bukkit-7.0.0-SNAPSHOT-dist.jar
worldguard-legacy-7.0.0-SNAPSHOT-dist.jar
```

Listed Featherboard Modules of Your Log:
```
armor.jar
worldguard.jar
world.jar
vanillaevents.jar
unicode characters.jar
twitter.jar
tickspersecond.jar
statistics.jar
sound effects.jar
serverpinger.jar
redisbungee.jar
rankupcrayons.jar
previous names.jar
player.jar
permissions.jar
memory.jar
javainfo.jar
hotbar.jar
griefprevention.jar
geographical.jar
fireworkeffect.jar
facebook.jar
entities.jar
effects.jar
economy.jar
compass placeholders.jar
commandplaceholderpack.jar
```

So much Plugins...may you should check if one of them causing the Crash
On my Server for example an OreGenerationPlugin that does not work correct anymore in 1.13 was crashing the Server all time. (+the Lightning Problem of the Chunks - what is disabled now ;) )

**Comment by x1p** [comment]
That was only the first crash. After that, I removed all plugins and only CMI was present.
I'v done a few tests with other (fresh) test servers with only CMI present:
Paper 1.12.2 Crashes
Spigot 1.12.1 Crashes

**Comment by CloudeLecaw** [comment]
then you have an other Problem
if u just have Server + CMI and it crashed then u have an other Problem

**Comment by x1p** [comment]
Funny that only CMI has this problem and really no other (premium!) plugins has this kind of troubles

**Comment by CloudeLecaw** [comment]
then you have an other Problem
if u just have Server + CMI and it crashed then u have an other Problem
Why? Enough Owners use CMI in the latest Versions like me and our Servers  dont crash ;)

have your tried to clear the CMI Folder (make a backup fore)

i would test - Fresh Server (no Remaining files from old Server + CMI)

**Comment by x1p** [comment]
I said fresh test server ^^

**Comment by CloudeLecaw** [comment]
So your still making an error if it still crashes..have u disabled the LightChunkUpdated?

**Comment by x1p** [comment]
I really appreciate your effort. I've also made a support ticket for my hosting. I don't think the problem lies with them because they have many customers running MC servers just fine. I've done many premium plugins in the years I'm an admin and have never seen this behavior before.

**Comment by CloudeLecaw** [comment]
hm Fresh world, Fresh Server...what else could you try?
Maybe ist a Problem with the javaVersion your using? :3....
but the JRE version: OpenJDK Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)….
hm if setuped Right (and i thin your host is doing this nor yourself… then this should be fine..

Hm... Fresh.. Server + Fresh World + Fresh CMI without remaining carbage files from old ones… ,Nothing else...hmm And the same with Spigot 1.12.2..

Spigot 1.13 also?..

**Comment by x1p** [comment]
After we noticed our hosting at the existence of this problem, they changed something to their java. This time, the plugin runs normally. So this solved our issue.

Now the hard work can start: setting this up...  :slightly_smiling_face:
