### ISSUE TITLE
If the destination(block y) is -64~0, the command top cannot be used.

### ISSUE THREAD

**Issue by EndlessLegends** [Zrips/CMI#6828]
**Description of issue:**
If the height (y) of the block under the destination foot of the top command is 1 or more, the command is executed regardless of the player's height (y), but if the height (y) of the block under the destination foot is 0 ~ -64, the command is executed does not run.

**Cmi Version (using`/cmi version`):** 
cmi Ver 9.1.4.1 cmiL Ver 1.1.2.5

**Server Type (Spigot/Paperspigot/etc):** 
purpur

**Server Version (using `/ver`):** 
1.18.2-R0.1-SNAPSHOT(git-purpur-1606)

![2022-04-17_06 50 17](https://user-images.githubusercontent.com/60249708/163692508-8651ce25-cc57-4a7e-8697-3d00d3ff90e9.png)

**Comment by CloudeLecaw** [comment]
i can agree this behave of /cmi top

if The Top Block is below 0 then u get command useage info instead of the command
![Snag_1e2f014](https://user-images.githubusercontent.com/12080017/163734865-1e4d131f-b843-4f94-bef5-c56318233da1.png)

**Comment by Zrips** [comment]
Will be fixed with next version
