### ISSUE TITLE
Local_EN.yml Does not let you change nextPage/prevPage settings, they do not exist in EN!

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#6834]
**Description of issue:**
You can not customize this next/prev buttons in the main Local_EN.yml, I thought that the varaibles were just missing, so I copied them from another language file but they straight up do not work!

![2022-04-20_17 57 46](https://user-images.githubusercontent.com/144046/164285421-a6d13ced-6a6b-4085-b020-bf5696e8ebd9.png)

I assume its these from the DE file:
```
  prevPage: '&2----<< &6Zurück '
  prevPageGui: '&6Vorherige Seite '
  prevPageClean: '&6vorherigee Seite '
  prevPageOff: '&2----<< &7Zurück '
  prevPageHover: '&7<<<'
  firstPageHover: '&7|<'
  nextPage: '&6 Nächste &2>>----'
  nextPageGui: '&6Nächste Seite'
  nextPageClean: '&6 Nächste Seite'
  nextPageOff: '&7 Nächste &2>>----'
  nextPageHover: '&7>>>'
  lastPageHover: '&7>|'
  pageCount: '&2[current]&7/&2[total]'
  pageCountHover: '&2[totalEntries]'
```

**Cmi Version (using`/cmi version`):** 9.1.3.3

**Server Type (Spigot/Paperspigot/etc):** PurPur

**Server Version (using `/ver`):** 1.18.2

**Comment by dkalaxdk** [comment]
Try checking cmilib/translations

**Comment by TomLewis** [comment]
> Try checking cmilib/translations

This was it thanks!
