### ISSUE TITLE
Fly mode issue

### ISSUE THREAD

**Issue by siulung201314** [Zrips/CMI#6846]
There is an issue about fly mode. When a player teleports from nether/end and into the overworld, the fly mode of the player always turns to be true. The fly mode keeps to be true until I turn his fly mode to be false. It does not work the other way around. I have tried different way to fix the issue but I cannot fix it.

I think that the issue may be caused by this action. (not sure)
The gamemode of a player is changed to be spectator and he teleports from a world to another world in spectator mode.
After that, the gamemode of the player is changed back to be survival.
And then, the issue happens on that player forever.

Cmi Version (using`/cmi version`):9.1.4.2

Server Type (Spigot/Paperspigot/etc):Purpur

Server Version (using `/ver`):1.18.2

**Comment by Zrips** [comment]
You will have to test this without any other plugin besides CMI to know if this issue originates from it, if it does, then resetting config files can help out in determining if its related to any custom setup you might have. 
CMI should not change players game modes or fly mode on its own, so something is triggering this action.

**Comment by MC-MrBirdy** [comment]
Can confirm that this indeed seems to randomly happen.
I've not found a solid way to reproduce.

Using just paper with an un-configured CMI seems to randomly but rarely cause this issue.
From what I've seen it is indeed caused when teleporting between dimensions.
To temporarily disable it you can initiate "fly off" on the player who suddenly can fly.

On the server I run our staff team sees this happen more frequently when someone has hacked.
But on rare occasions it seems to happen out of the blue. (can even persist on restarts)

**Comment by mrfloris** [comment]
I once made this article that goes through some tips to check as server owner to help 'player stuck on x' , hopefully it helps in this case as well. 

Players are stuck on mode x: https://faq.cmi.support/mode-stuck  

If not, feel free to follow up.

**Comment by Rexmen1** [comment]
Happens on my server too... It turns on fly when changing world... Happening since last 2 years...

**Comment by arevindh** [comment]
@Rexmen1 can you list the plugins you use, may be the issues is caused when specific plugins installed together .

**Comment by Zrips** [comment]
Will make some adjustments relating to fly mode handling, especially while having worldlimits enabled. If issue persists with next update, let me know.
