### ISSUE TITLE
Kit newbie not given anymore since 9.1.4.1

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#6848]
**Description of issue:**

I noticed players were not getting the newbie kit.
So I started my test server to determine the default behavior of the default CMI
Since CMI version 9.1.4.1 the newbie kit is not given anymore

The CMI folder and player data is removed upon every test. So everything is default on each test.
Player is operator and has every possible permission. So permissions are ruled out.

![Screenshot 2022-04-26 131441](https://user-images.githubusercontent.com/28690790/165290279-ee5b4d00-61bc-4876-b49a-48a16a7afa89.png)
(CMI shows wrong version in 9.1.4.0)

![Screenshot 2022-04-26 131953](https://user-images.githubusercontent.com/28690790/165290304-ccab05b1-1a06-4d0d-8e99-3e7f4214d31e.png)

---

**Cmi Version (using`/cmi version`):** 
9.1.41 and higher
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.18.2

**Comment by amarcais53** [comment]
i got the same issue there

**Comment by SmallSansSerif** [comment]
Same issue for me. Help!

**Comment by mrfloris** [comment]
Just did a fresh install of latest cmilib and latest cmi, and can confirm the new players dont get the kit.

**Comment by Onionar** [comment]
I got the same problem

**Comment by Zrips** [comment]
Fixed with latest build
