### ISSUE TITLE
Importation is NOT WORKING

### ISSUE THREAD

**Issue by SaintGearz** [Zrips/CMI#6853]
**Description of issue:**
Hologram importing does not work. I have lot of holograms of HD, but when I do the import command, 0 gets sent to CMI. The import from essentials also only did 5 out of the 30 warps. Not happy with that since the conversion was the biggest reason why I bought CMI
---

**Cmi Version (using`/cmi version`):** 
9.1.4.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
310

**Comment by Zrips** [comment]
I will need more information on this issue. How many records do you have in essentials player data folder? Which versions of those plugins you used? Can you share file of your HD so that I could test it out to see what went wrong?

**Comment by SaintGearz** [comment]
https://pastebin.com/y0Yvuq7R < - HD database

and I've already manually transferred and deleted Essentials unfortunately

Versions:
Essentials - 1.19.4
HD - 3.0.0

**Comment by Zrips** [comment]
HD database file format changed for some strange reason which caused it to not be able to be imported. Will update internal code to account for this. Sorry for inconvenience.
