### ISSUE TITLE
emote usage on img tag login message

### ISSUE THREAD

**Issue by XxMr1234GamerzxX** [Zrips/CMI#6855]
**Description of issue:**
using helmet img on login message is dark this is due to a texture pack which corrects emotes in Minecraft 

you guys use black large square (⬛) which makes the image dark

possible fix is to use white large square (⬜) instead which will work with or without the texture pack

**Comment by Zrips** [comment]
Could you elaborate more on this one? Like actual image with what you are experiencing.

**Comment by XxMr1234GamerzxX** [comment]
# the problem when using black large square (⬛)
![image](https://user-images.githubusercontent.com/32730401/166437717-876b0c6c-f625-4754-b8a7-f6308cfa147a.png)

# how it should look (using white large square (⬜) instead)
![image](https://user-images.githubusercontent.com/32730401/166437797-75d2a226-16c3-4a1d-b50a-f94fdc4d2312.png)

**Comment by Zrips** [comment]
Interesting. In general color is determined by analyzing actual texture image and not what type of cube we are using. 
![image](https://user-images.githubusercontent.com/10416201/166453126-bca287ea-2379-48ca-8376-5d2567b4c50f.png)
getting correct colorization on my end. Which server version are you running? 
In general what i can do is simply add option for you to define filler box in CMILib config file, so in that case you can define it to your own liking and if its causing you issues you can simply change it to one which fixes it for you.

**Comment by XxMr1234GamerzxX** [comment]
that would work 

defaulting it to the white thing would still do what you need it to do and shouldnt create issues anyway which is why i presented that as a fix 

the fonts textures are making the cube black and all your going from there is adding a hue to the cube which if its black will always make the color darker than intended

**Comment by Zrips** [comment]
This will be added with next CMILib update
