### ISSUE TITLE
Player in ignorelist can still use command /minecraft:tell or /minecraft:w

### ISSUE THREAD

**Issue by siulung201314** [Zrips/CMI#6858]
Player(A) is in the ignorelist of Player(B) but Player(A) can still use command /minecraft:tell or /minecraft:w to send messages to Player(B).

Cmi Version (using/cmi version):9.1.4.2

Server Type (Spigot/Paperspigot/etc):Purpur

Server Version (using /ver):1.18.2

**Comment by CloudeLecaw** [comment]
Negate the permission minecraft.command.tell minecraft.command.say   these commands can nornaly used by players and use a format arround the Plugins because it triggers the vanilla commands

**Comment by CloudeLecaw** [comment]
Cmi usses it own commands and permission for msg (whisper with others) and me

**Comment by Zrips** [comment]
Ignore command will not block 3rd party plugins or vanilla commands from sending messages which got initialized by someone you have in their ignore list as there isint really simple way to get that information to verify that message should not be visible. Its not a bug, its just general issue with how things work and limitations in general.
