### ISSUE TITLE
[Request] Option to prevent picking up XP orbs while AFK

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#686]
An option to prevent picking up experience orbs while AFK.

**Comment by CloudeLecaw** [comment]
doesnt the normal Picup allready work?If not it must be fixed

**Comment by TheWranger** [comment]
It isn't a bug. That option is only intended to disable item pick ups, not experience orb pickups.

**Comment by CloudeLecaw** [comment]
expierients orb is an item :3
