### ISSUE TITLE
Hologram Bug Report (Important)

### ISSUE THREAD

**Issue by Bart0o** [Zrips/CMI#6869]
**Description of issue:**

https://youtu.be/7oKLBxypu74

**Cmi Version (using`/cmi version`):** 
Versione di CMI: 9.1.4.3 BungeeCord  MySQL
CMILib: 1.1.2.5

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-238 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 657d163)

**Comment by mrfloris** [comment]
Can you check in 9.1.4.5 of CMI if the hologram issues have been resolved for you?

**Comment by Bart0o** [comment]
Yes
