### ISSUE TITLE
CMI detected as Trojan

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#6871]
### Description of Issue

CMI started being detected as a Trojan since 9.1.4.3 specifically `Trojan:Script/Wacatac.B!ml`. In case this is a false positive, please provide clear evidences why this is so.

### Version Information

```shell
9.1.4.3 - 9.1.4.4
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
You can perform file scan will majority of antivirus by using something like this https://www.virustotal.com/gui/home/upload 
What Microsoft indicates to be a trojan is a false/positive. Some of those points towards generic Enum type classes which doesn't do anything at all. You can always dig around plugins code if you are not sure and check where this supposed Trojan was detected. 
Basic example of Microsoft "trojan" points towards 
![image](https://user-images.githubusercontent.com/10416201/166430541-7dbabaad-449d-4d7c-94d1-f3a2fcffb8a3.png)
which is
![image](https://user-images.githubusercontent.com/10416201/166430565-469f5908-3c09-42b5-b624-42300c6fffca.png)
If this counts as trojan then i have no idea what isint one.

**Comment by mrfloris** [comment]
<img width="1163" alt="Screenshot 2022-05-03 at 12 01 29" src="https://user-images.githubusercontent.com/28841349/166435476-42161815-f731-4488-8534-bb9f57f474be.png">
<img width="1168" alt="Screenshot 2022-05-03 at 12 01 36" src="https://user-images.githubusercontent.com/28841349/166435482-4ae08af2-e3c8-4b58-bf8d-5e6670108297.png">

same file, rescan, same file re-submit, and new jar from spigotmc, they all show okay for mysql and action classes.
