### ISSUE TITLE
Bug when parsing placeholders with console

### ISSUE THREAD

**Issue by Replaycchi** [Zrips/CMI#6879]
### Description of Issue

Hello,

For some time my custom alias to extend the world border does not work anymore, the console does not seem to parse the placeholder correctly every time and it return a vanilla error. 

![Screenshot_1](https://user-images.githubusercontent.com/85904547/167092102-a75ca53b-60e2-47d2-97ac-f11f1af8f618.png)

I have another custom alias who parse VotingPlugin's placeholder through DiscordSRV and it works when using the alias as a player but not as Console.
I used the first placeholder since more than 6 months so it worked before and i didn't change it.

When the command is executed by the console : 
![Screenshot_2](https://user-images.githubusercontent.com/85904547/167092267-8f29200a-f272-4347-9e3d-642ca4264b4a.png)

When the command is executed by the player : 
![Screenshot_3](https://user-images.githubusercontent.com/85904547/167092470-d6ac9407-007b-4f09-9268-1e3370dcabc2.png)

```
CustomAlias:
  dbcastvotes:
    Cmds:
    - 'asConsole! discordsrv bcast #902249473491755048 > **Classement des Votes**\n\n
      :medailleor: **%VotingPlugin_Top_Month_1%** - %VotingPlugin_Top_MonthVotes_1%\n
      :medailleargent: **%VotingPlugin_Top_Month_2%** - %VotingPlugin_Top_MonthVotes_2%\n
      :medaillebronze: **%VotingPlugin_Top_Month_3%** - %VotingPlugin_Top_MonthVotes_3%\n
      Top 4 **%VotingPlugin_Top_Month_4%** - %VotingPlugin_Top_MonthVotes_4%\n Top
      5 **%VotingPlugin_Top_Month_5%** - %VotingPlugin_Top_MonthVotes_5%\n Top 6 **%VotingPlugin_Top_Month_6%**
      - %VotingPlugin_Top_MonthVotes_6%\n Top 7 **%VotingPlugin_Top_Month_7%** - %VotingPlugin_Top_MonthVotes_7%\n
      Top 8 **%VotingPlugin_Top_Month_8%** - %VotingPlugin_Top_MonthVotes_8%\n Top
      9 **%VotingPlugin_Top_Month_9%** - %VotingPlugin_Top_MonthVotes_9%\n Top 10
      **%VotingPlugin_Top_Month_10%** - %VotingPlugin_Top_MonthVotes_10%'
    Perm: true
  expand:
    Cmds:
    - cmi broadcast !&r
    - cmi broadcast !&6Grand-Pahon&7 » J'ai repoussé les &alimites &7du monde &aRessource
      &7jusqu'à &3$1- blocs&7.
    - cmi broadcast !&r
    - cmi sound entity_evoker_prepare_summon -p:1.5
    - execute in minecraft:ressource run worldborder set %cmi_equationint_$1-*2%
    - execute in minecraft:ressource_nether run worldborder set %cmi_equationint_$1-*2%
    - execute in minecraft:ressource_the_end run worldborder set %cmi_equationint_$1-*2%
    Perm: true
```

### Version Information

```shell
>.... [10:12:11 INFO]: CMI: 9.1.4.5 BungeeCord CMIB MySQL
>.... [10:12:11 INFO]: CMILib: 1.1.2.5
>.... [10:12:11 INFO]: Server: Purpur 1.18.2-R0.1-SNAPSHOT
>.... [10:12:11 INFO]: CMI economy: Activé Vault: 1.7.3-b CMI Chat: Activé
>.... [10:12:11 INFO]: Modules -> 47 enabled 9 disabled: spawnerProximity, deathMessages, tablist, ranks, votifier, headDrop, spawners, spawnerCharge, namePlates
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update

**Comment by Replaycchi** [comment]
For some reasons there's still some placeholders who aren't parsed when using via console : 
```
  _boutiquebcast:
    Cmds:
    - 'asConsole! discordsrv bcast #1018975488942813265 %localtime_time_dd/LL HH:mm:ss%
      | **$1** a acheté **$2 Gemmes** en boutique.'
    Perm: true
```
If i try myself ig it works but when using this alias via the console it's broken
