### ISSUE TITLE
/killall Vehicle bug

### ISSUE THREAD

**Issue by EpicPlayerA10** [Zrips/CMI#6880]
### Description of Issue

When a mob is in vehicle (for example boat) and i do /killall (mob name) then it will kill all these mobs except that in the vehicle.

### Version Information

```shell
https://i.imgur.com/JnIx3bf.png
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
U know that kill all has extra Parameter?

```
[killall (-monsters/-pets/-npc/-animals/-ambient/-named/-f/-lightning/-list/-m:[mobType]) (-r:range) (-s) (-w:[worldName])](https://www.zrips.net/cmi/commands/)
Kill mobs around you
```

https://www.zrips.net/cmi/commands/kill-all/

**Comment by EpicPlayerA10** [comment]
Ah okay
