### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by FZDNSZYT** [Zrips/CMI#6887]
Can the MySQL database be shared between the sub-servers of the same bungeecord? Because I started from the second sub-server, the database created by the alias cannot write to the data table. Only the database with the default name can be used normally.

**Comment by FZDNSZYT** [comment]
It means that I can't create more databases under a bungeecord, and as soon as I create it, it reminds me that there is no such table or that table.

**Comment by FZDNSZYT** [comment]
For example, when I create a database named lobbycmi for a new child server, it will report the following error:
![2022-05-13](https://user-images.githubusercontent.com/86947716/168268742-1577aa50-58c2-496f-8b46-57ec0ecbb565.png)
![2022-05-13](https://user-images.githubusercontent.com/86947716/168268810-dbb6641c-ab12-493b-857d-320f9684c5db.png)

**Comment by FZDNSZYT** [comment]
I logged into MySQL to check the lobbycmi, which is the database I built for the second child server, and it was also blank.

**Comment by Zrips** [comment]
This should have been fixed in one of the latest builds, please update to latest CMI version
