### ISSUE TITLE
[FEATURE] Add /setwork hand ''price''

### ISSUE THREAD

**Issue by SkyDude0** [Zrips/CMI#6894]
I suggest to add a way to set custom item, like with different name,lore etc.. on the /worth list

With the command /setwork hand ''price'' or something like that

**Comment by Zrips** [comment]
Custom model data is being recognized currently, so you can use that as way to separate one item over the other and set different prices for it. Using items lore or name isint best solution as it can be modified by the user, especially name. 
You can modify items custom model data with **/cmi itemcmdata** or any other plugin made for this.
