### ISSUE TITLE
Chat Double Text Issue

### ISSUE THREAD

**Issue by Mark0es** [Zrips/CMI#6895]
### Description of Issue

When i type something in chat it type it double 
example

test this is howtest this is how
or
bugreport please fix quicklybugreport please fix quickly

### Version Information

```shell
CMI: 9.1.4.5
CMILib: 1.1.2.5
Server: Paper(401) 1.17.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled
Modules -> 55 Enabled 1 disabled votifier
```

### Errors

```shell
None
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
Well you might using secound plugin that handles chat too? 
Oray u could Post your chatpart of config?

**Comment by Zrips** [comment]
@MarkoesXD 
Would suggest to test this by disabling any other plugin which will show if you have another plugin duplicating chat messages or not. Which is most likely the case.
