### ISSUE TITLE
[feature request] book.txt

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#69]
Hej I have another suggestion. Coming from EssentialsX I would love to see a "book.txt". EssentialsX has a book file. In that file one could place the content he or she would like to be used ingame. In this file one can create a named section or chapter which starts with #. These can then be used in item meta using book:<name of section>. One line in the txt represents one line in the book. This feature is very useful to give book to newbies, to distribut vouchers or to do other amazing stuff with books. Of course you can generate a very long command which generates the same book for you. Unfortunatly that method is way more complicated, take way longer and it is so much harder to edit books using commands that are going on rows after rows.

**Comment by MCTyler** [comment]
Can you Merge this with my Request?

**Comment by Zrips** [comment]
I'm currently working on this and next update should have full support for conversion from ctext to books with hover over, click commands and so on. Basically custom text in a books.

**Comment by Zrips** [comment]
Will be added with next update

**Comment by TheoRetisch1** [comment]
Thank you, that will help a lot 👍
