### ISSUE TITLE
[Bug] - player keep items on respawn + Mo DeathMenue...

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#690]
i tool in permission that noone has:
      - cmi.keepinventory

but... all players keep their items on death since last CMI update

Also i noticed that player got repsawned automaticly without the Deathscreen...

![image](https://user-images.githubusercontent.com/12080017/43550475-f5ef4d00-95e3-11e8-86f6-4b67171a48d7.png)

Also the Deathmenue is overjumped like an instand respawn... without having cmi.autorespawn

When CMI is disabled i loose items and see the Screen after death.

these two are the only two permissions i know that effecing these... 

After i died as Player:
![image](https://user-images.githubusercontent.com/12080017/43780891-f655b0b4-9a5b-11e8-96bc-7d7fb5635005.png)

**Comment by CloudeLecaw** [comment]
really? the neagtion of it causes this error? ...Strengh...

**Comment by Zrips** [comment]
Hopefully will be ok with next update.
