### ISSUE TITLE
[BUG] missing bed for your location

### ISSUE THREAD

**Issue by kedavlar** [Zrips/CMI#6903]
### Description of Issue

After update the plugin at version 9.1.4.6 my player have ''missing bed for your location'' when they try to TP normally at your home location

### Version Information

```shell
9.1.4.6
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
What is the value set for RemoveBedLocationOnBedBreak in Settings/Homes.yml

**Comment by Blueeyestar** [comment]
All of our users who did /sethome had the same problem. Your home is no longer found. Because he says there is no bed. The name Home is set automatically when you do /sethome. I have reset to 9.1.4.5 now users can teleport back to their home

**Comment by Zrips** [comment]
Will issue rollback on previous change relating to missing beds fix which is the cause of this. Will need to think of another solution for that issue.
