### ISSUE TITLE
CMI msg not blocked when muting in different bans-systems

### ISSUE THREAD

**Issue by Snele** [Zrips/CMI#6904]
I'm trying to deny access to /cmi msg when a player get mute, but nothing helps (except to completely block cmi command)
It doesn't matter which ban-system is used.
What should I do? Which command should I block?

**Comment by Zrips** [comment]
Check config file, there is option DenyPrivateMessages which can prevent private messages while player is muted, this will only work when you use cmi mute command tho. Other than this you can simply take away access to cmi.command.msg command while player is muted.
