### ISSUE TITLE
Sign HEX color codes

### ISSUE THREAD

**Issue by S4IVin** [Zrips/CMI#6913]
**Description of issue or feature request:**

By default, without any permissions/OPs/modified config, players can use HEX color codes on signs

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

---

**Cmi Version (using`/cmi version`):** 9.1.4.7

**Server Type (Spigot/Paperspigot/etc):** Paper 1.18.2-312

**Server Version (using `/ver`):** 1.18.2

**Comment by Zrips** [comment]
Should be fixed with next version
