### ISSUE TITLE
Particle colors do not work properly.

### ISSUE THREAD

**Issue by baranshn** [Zrips/CMI#6917]
### Description of Issue

https://www.zrips.net/cmi/extra/particles/

I was trying the particles in this thread and decided to use this: circle;c:200,50,210;twist;part:5;r:0.5;pitch:90;move:0,0.33,0;offset:0,-0.2,0;target:[playerName]

Then I read the colors section in the link above and decided to change the color as a hex code. Like...
circle;c:{#9DADBC};twist;part:5;r:0.5;pitch:90;move:0,0.33,0;offset:0,-0.2,0;target:[playerName]
https://prnt.sc/y4qmAqaJ4Hb0 - https://prnt.sc/7jjZGfKhQTBZ  (image)

But the color I entered was not working. So it wasn't showing the color I wanted.

Then I tried something simple and made the color red. But the blue particle appeared.
circle;c:{#red};twist;part:5;r:0.5;pitch:90;move:0,0.33,0;offset:0,-0.2,0;target:[playerName]
https://prnt.sc/OyIyGE5djfmU (image)

Also i faced the same situation when i wrote in rgb code instead of hex codes.

### Version Information

```shell
https://prnt.sc/goxXOE4mS-xw (image) - latest version
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by baranshn** [comment]
My version: 1.18.2-Paper

**Comment by mrfloris** [comment]
Can reproduce on 9.1.4.7 on 1.18.2
Using c:123.123.123 they show, (hex), but directly {#red} or {#hexvalue} it shows blue to me

**Comment by baranshn** [comment]
Coloring using c:123.123.123 has the same issue. 

https://prnt.sc/QuID6rvc4A1e - https://prnt.sc/ToAn2krbG2un 

[06:40:04 INFO]: Pastoralize issued server command: /cmi panimation circle;c:157,173,188;twist;part:5;r:0.5;pitch:90;move:0,0.33,0;offset:0,-0.2,0;target:Pastoralize
