### ISSUE TITLE
help with shop signs and permissons

### ISSUE THREAD

**Issue by IPunchTrees** [Zrips/CMI#692]
**Description of issue or feature request:**

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
I have recently purchased your cmi plugin the one with all of the other plugins in it like 240 or something like that and I am loving it but I have a question when we set up servers using essentials there is a permission node modifyworld.* that allowed us to make certain groups no be able to edit a world we don't want our lower ranks to edit in the end how would we do that but still allow them to go to the end
Also looking around I cannot find a tutorial on how to set up shop signs how do I go about that?
```

**Cmi Version (8.0.1.0`):** 

**Server Type (Spigot):** 

**Server Version (1.13`):**

**Comment by CloudeLecaw** [comment]
Modifyworld.* is an old Plugin Long Long ago it was a poart of pex, now ist a own Plugin. 

You bought CMI not a protectionPlugin. If you want a protection Plguin then you should buy Residence frim Zrips :-)

PS: Your Modifyworld also was some Kind of protectionPlugin
