### ISSUE TITLE
How to fix Missing locale (modify.deleteSymbol, modify.listNumbers, modify.addSymbol. There are more and more

### ISSUE THREAD

**Issue by Ahuina** [Zrips/CMI#6921]
i need to know, how to fix it
Does someone know ?
How to fix

![image](https://user-images.githubusercontent.com/106108045/169879615-225efffa-cf88-4f50-8105-0e75330edcbe.png)
![image](https://user-images.githubusercontent.com/106108045/169879657-a87c708c-7fcd-4bfc-9cd4-9553329f890f.png)

**Comment by dan28000** [comment]
did you check CMILib also for translations?

**Comment by Ahuina** [comment]
yes

**Comment by CloudeLecaw** [comment]
If your used langfile is missing the lines u may need to add them manually.

**Comment by mrfloris** [comment]
/stop the server and backup your server, then try this:

You can back up your old cmi/translations/locale files, and the same for cmilib/translations/locale files.
And start the server, then try to run those commands again to try and see if that resolved it. if so, then diff the old + new files and see what customizations you wish to re-apply, (or the other way around, and add missing locale).

They generally during upgrade get added, but a very old custom locale file is harder to upgrade, if things go missing then it's a poorly not-yaml compliant translation probably causing more and more issues (or someone from staff is using in-game commands to delete locale from the file).

**Comment by Zrips** [comment]
Locale files get updated automatically with missing lines, check console for any errors during server startup. if you are using custom locale, then it would be nice to know it for general idea whats going on. Other than this, simple server restart should help to generate correct files and if you are using custom locale, try switching back to default EN and check if issue gets resolved. For time being closing this ticket.
