### ISSUE TITLE
Essentials + Luck Perms - Not working :(

### ISSUE THREAD

**Issue by Ahuina** [Zrips/CMI#6922]
![image](https://user-images.githubusercontent.com/106108045/169887573-5bd8869a-6e25-445b-9a05-1ba55ddbf1b7.png)
![image](https://user-images.githubusercontent.com/106108045/169887677-21e628d9-1fca-4e41-88f6-2a6603b92091.png)
As you can see, in the 1 picture, the characters <> are changed, and in the 2 pictures, they are. Do you know how to fix this? i need to change <> this, to >> this

**Comment by CloudeLecaw** [comment]
Looks like your chatformmater isnt working.
Why you came with this to cmi forum?
This is not the Essentials Forum...

**Comment by mrfloris** [comment]
Zrips didn't make Essentials(X) you have to ask them for support.

You can move away from Essentials + Chat addon, and use CMI with it's built-in Chat Manager, it supports bungee too, here are some articles that can help you get started;

Setting up CMI Chat: https://faq.cmi.support/chat 
CMI Chat + Bungee: https://faq.cmi.support/bungee 
CMI Chat + Join / Leave: https://faq.cmi.support/joinleave 
CMI Chat + Group Format: https://faq.cmi.support/format 
CMI Chat + LuckPerms Prefix: https://faq.cmi.support/prefix
