### ISSUE TITLE
Home gui display issue

### ISSUE THREAD

**Issue by MusicTW** [Zrips/CMI#6928]
### Description of Issue

![lXaLFiT - Imgur](https://user-images.githubusercontent.com/52475422/170449500-7aae1167-f5a8-43e9-8122-4a0a269a9027.png)

In the picture, there's air right off the bone
can't find it with /homes <tab>, either.

### Version Information

```shell
[Thu 16:31:18 INFO ] --------------------------------------------------
  [Thu 16:31:18 INFO ] CMI 插件版本: 9.1.4.7 SqLite
  [Thu 16:31:18 INFO ] CMILib: 1.1.2.5 
  [Thu 16:31:18 INFO ] Server: Purpur 1.18.2-R0.1-SNAPSHOT
  [Thu 16:31:18 INFO ] CMI economy: 啟用 Vault: 1.7.3-b131(CMIEInjector) CMI Chat: 禁用 
  [Thu 16:31:18 INFO ] Modules -> 47 enabled 9 disabled: customMessages, ranks, votifier, headDrop, jail, spawners, namePlates, playerChatTag, bossBarCompass
  [Thu 16:31:18 INFO ] --------------------------------------------------
```

### Relevant Plugins

Vault 1.7.3-b131

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Can you share the `Homes.yml` file you have now?
And when you open the .db or mysql database (whatever type you use) and under users table find the unique user, and check how many homes they have, does it list 4 or 5 homes? Can you share that db > users > user > homes field data as well with us?

Do you get teleported somewhere when you click on the grey empty field? (invisible icon?)

**Comment by MusicTW** [comment]
https://pastebin.com/vKGt0Yrv

**Comment by MusicTW** [comment]
Do you get teleported somewhere when you click on the grey empty field? (invisible icon?)
no

**Comment by MusicTW** [comment]
[chen1658's home.txt](https://github.com/Zrips/CMI/files/8789346/chen1658.s.home.txt)

**Comment by MusicTW** [comment]
> 

I just changed player's home name from 0$-0$ to 測試$,and its work

**Comment by Zrips** [comment]
@MusicTW 
Looks to be issue with slot being set to 0. Duno how that happen in your case as with default controls you should not be able to set to lower than #1, but will issue fix in ether case just to prevent from this issue happening again.
