### ISSUE TITLE
clear command

### ISSUE THREAD

**Issue by andy3559167** [Zrips/CMI#6929]
Can the clear command support custom items like the give command?
ex clear playername stone n &cstonea l &bstoneb

**Comment by mrfloris** [comment]
Visit https://github.com/Zrips/CMI/discussions/new to post new idea or suggestion
Posting new suggestion in ticket section could result in their removal.

When you create a new feature issue ticket, it says where to post it, please post it there. 

<img width="680" alt="Screenshot 2022-05-27 at 11 05 43" src="https://user-images.githubusercontent.com/28841349/170668470-d7f9818f-b042-4e3d-8c2e-18f9181f1c0c.png">
