### ISSUE TITLE
Hologram ICON floating up if underwater

### ISSUE THREAD

**Issue by GrimPod** [Zrips/CMI#693]
Holograms ICON:<itemName> floating up if under water

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
ICON:Ender_Pearl
#####################################
```

**Cmi Version (using`/cmi version`):** 
8.0.3.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.13-RO.1_SNAPSHOT

**Comment by Zrips** [comment]
It is due to how minecraft handles items in water, cant really do anything about this at this point. Can't find any workaround and prevent this one from happening.
