### ISSUE TITLE
Placeholders dont work in AFK title

### ISSUE THREAD

**Issue by 1ntent1on** [Zrips/CMI#6930]
### Description of Issue

Hello, for some reason AFK title cant handle CMI placeholder. They work normally if i use the title command.

### Version Information

```shell
CMI: 9.1.4.7 BungeeCord CMIB  SqLite
CMILib: 1.1.2.5 
Server: Purpur 1.18.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Enabled 
Modules -> 39 enabled 17 disabled: mirror, tablist, armorstand, versionCheck, moneyCheque, skin, holograms, jail, paintingEditor, bossBarCompass, coloredArmor, ranks, votifier, shulkerBackpack, attachedCommands, spawnerCharge, vanish
```

### Relevant Config Sections

```yaml
afk:
    help:
      info: '&7Toggle afk mode. Reason could be provided'
      args: (-p:playerName) (reason) (-s)
    info:
      # This only determines message in title message and not message shown in chat. For chat message check config.yml file
      afkTitle: '&cYou are now AFK'
      afkSubTitle:
      - '&7%cmi_user_afk_for%'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
That looks like the locale file, usually placeholders don't work in locale files unless specifically mentioned. 

In config.yml you can run commands on auto-afk, manual-afk, and return-from-afk under the `afk:` section. You can run nameplate, bossbarmsg, titlemsg, panimation, bungee broadcast, or whatever cmds you want. They support placeholders there.

**Comment by CloudeLecaw** [comment]
Well for me the afk labfpart for title and subtitle feel so unessary since you can define it all in the config. Also the afk/autoafl and unakf support multiple commands.  So i really see no reason why title and subtitle where added extra for afk in the langfile.

**Comment by Zrips** [comment]
Will add support for placeholders in title and subtitle for afk thing as its quite convenient thing to have and display more dynamic values
