### ISSUE TITLE
CMILib Usage High

### ISSUE THREAD

**Issue by AnunnakiSuma** [Zrips/CMI#6935]
Hey hope you are good! I was just wondering if you can please help me?

My server is having some issues with tps drops etc..
According to my timings report, cmi lib is plugin which uses the most resources, i just wanted to see if this is normal as its using more than plugins like Realistic Seasons etc. 
I am trying to figure out what this task is so i can see if there is an issue

CMILib::Task: net.Zrips.CMILib.BossBar.BossBarManager$1 (interval:2)count(19129)  total(5.40% 34.485s, 10.61% of tick)avg(1.80ms pe

Timings report: https://timings.aikar.co/?id=db2c10c98bda4a3db2554c9947c92a30#plugins

Crash: https://pastebin.com/Ca1A0AQi

Hope someone can help, thank you!

**Comment by Zrips** [comment]
Do you have any bossbar actions which are been shown or performed every 2 ticks or so? Cant really track back to actual cause from those timings, but you have something what updates on really rapid pace with higher than normal load on it.

**Comment by Zrips** [comment]
Compass could be a cause. What is the interval set for compass bar update rate? Or simply show me entire section relating to boss bar compass

**Comment by Zrips** [comment]
@AnunnakiSuma 
Interesting, by your config its not the one causing issues. Is there any other boss messages appearing while players are playing? Maybe Jobs plugin bossbar?

**Comment by AnunnakiSuma** [comment]
I start noticing it once we start getting to 8 players and above & thats
when i start running the timings so i will try doing a timings when there
are few people online. The server crashed last night, i added a pastebin
link from when i can see the issues started - https://pastebin.com/x7tKX6yi

Does CMI run save-all? Spoke to the guys at paper and they said there is
something running it but i checked my panel and its turned off.

**Comment by AnunnakiSuma** [comment]
hey, this is timings report with one player online -
https://timings.aikar.co/?id=c8a256b98b1d4b86863f90b4b7c1c141#timings

**Comment by AnunnakiSuma** [comment]
It did it again :( https://pastebin.com/UyP24weL

**Comment by AnunnakiSuma** [comment]
sorry not sure whats going on, it did it again, just wanna give u as much
info as possible https://pastebin.com/gXU71zDQ

**Comment by AnunnakiSuma** [comment]
Found this in schedules dunno if it could have been causing the issue?

saveMaps:
  Enabled: true
  Delay: 600
  Repeat: true
  Commands:
  - save-all
