### ISSUE TITLE
Head database integration

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#6941]
We like to work with the plugin CMI. Unfortunately, we always find out that you can't integrate heads from Head Database.
As an example, we noticed this with the holograms when we wanted to integrate a decorative head.

_ShooterLulugames:
  Loc: LuluGames;-1128.48;161.62;-1549.52
  LOSInterval: 0.1
  HoverParticles:
    count: 1
  Range: 16
  Range Extra: 32
  lines:
  ICON:head:ABigDwarf_

With Icon you can only include the head name. But 99.99% of heads have value. Or an ID.

It would be nice if you could integrate heads more easily if you used as an example:

ShooterLulugames:
  Loc: LuluGames;-1128.48;161.62;-1549.52
  LOSInterval: 0.1
  HoverParticles:
    count: 1
  Range: 16
  Range Extra: 32
  lines:
  **ICON:hdb:2598745**

could enter.

 or the ShooterLulugames:
  _Loc: LuluGames;-1128.48;161.62;-1549.52
  LOSInterval: 0.1
  HoverParticles:
    count: 1
  Range: 16
  Range Extra: 32
  lines:
  Value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGUxNjc1NTFlMjcxYTUwYjdjZTg1ZjcxNzU4MWY0M2ZmNzI0NWRmZTQyY2UwMjU1NWZkYWY3ZGJjZGE5OTE4NSJ9fX0=_

So you could easily integrate decorative heads

**Comment by Zrips** [comment]
To be fair, you can use something like
`ICON:head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGUxNjc1NTFlMjcxYTUwYjdjZTg1ZjcxNzU4MWY0M2ZmNzI0NWRmZTQyY2UwMjU1NWZkYWY3ZGJjZGE5OTE4NSJ9fX0=`
or 
`ICOn:head:e24de501-4293-3700-99b0-473674bb89a3`
Support for specific plugins to have expansion of specific feature isint CMI goal, its more of stand alone plugin. I might think about adding some basic way to save heads information for easy to use purposes.

**Comment by Blueeyestar** [comment]
awesome that works great with that

ICON:head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjNiNzEwYjA4YjUyM2JiYTdlZmJhMDdjNjI5YmEwODk1YWQ2MTEyNmQyNmM4NmJlYjM4NDU2MDNhOTc0MjZjIn19fQ==

That's exactly what I wanted but didn't know that it also works by entering the value
