### ISSUE TITLE
Silent output voteedit doesn't work.

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#6942]
### Description of Issue

Hello!

I noticed that the silent function of the command `/voteedit` was not working.
When I run for example `/voteedit Noltox add 1 -s` with the console I still get the message in the chat.

### Version Information

```shell
>....=>.... [17:33:12 INFO]: CMI: 9.1.4.7 BungeeCord CMIB MySQL
>.... [17:33:12 INFO]: CMILib: 1.1.2.5
>.... [17:33:12 INFO]: Server: Purpur 1.18.2-R0.1-SNAPSHOT
>.... [17:33:12 INFO]: CMI economy: Désactivé CMI Chat: Activé
>.... [17:33:12 INFO]: Modules -> 19 enabled 37 disabled: spawnerProximity, cuffed, mirror, tablist, versionCheck, moneyCheque, skin, noTarget, elytraBoost, elytraLaunch, bossBarCompass, playerCombat, votifier, shulkerBackpack, cooldown, headDrop, spawnerCharge, vanish, namePlates, timedCommands, homeInteractions, hpBossBar, launchPad, portals, spawners, dynamicSigns, durabilityLoss, kits, flightCharge, deathMessages, disabledEnchants, worldLimitsElytra, worldLimits, ranks, sitAnimation, warmup, totemBehavior
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will fix with next update

**Comment by NoltoxGit** [comment]
> Will fix with next update

Hello @Zrips!
This issues is not resolved with the last version.

Now when I want to use the `-s` it puts the usage message.
