### ISSUE TITLE
Limit warp per page bug

### ISSUE THREAD

**Issue by Rafalll1** [Zrips/CMI#6943]
### Description of Issue

There is a warp limit per page, when I have more than 20 warps, each additional warp is added to the next page, even if I set the warp to page one for some reason the warp is still on page two.
https://youtu.be/II37nRnSE-A

### Version Information

```shell
https://imgur.com/undefined
```

### Relevant Config Sections

```yaml
https://pastebin.com/tpnhT0JT
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Gets a fix with next update
