### ISSUE TITLE
Sicon head being wrongly oriented

### ISSUE THREAD

**Issue by dan28000** [Zrips/CMI#6945]
### Description of Issue

when using SICON:head the head is wrongly oriented
normal blocks are oriented fine
![image](https://user-images.githubusercontent.com/84990628/171719520-4285ee40-d3ab-41da-b046-f6cde90f6f31.png)

### Version Information

```shell
CMI: 9.1.5.0 SqLite
CMILib: 1.1.2.6 
Server: Purpur 1.16.5-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 40 enabled 16 disabled: spawnerProximity, hpBossBar, customMessages, tablist, afk, skin, jail, spawners, playerChatTag, bossBarCompass, flightCharge, ranks, firstJoinMessages, votifier, spawnerCharge, vanish
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Sadly there is no way to properly position head as it has limited orientation options in side like this one.
