### ISSUE TITLE
Chat tagging bedrock players

### ISSUE THREAD

**Issue by alfredcort** [Zrips/CMI#6947]
### Description of Issue

Hi there, when mentioning players using the bedrock client (with a . Before their name), the chat thinks you’re typing a link instead of tagging the user.
![F8108803-749B-45CA-9DF2-B841FD4147BF](https://user-images.githubusercontent.com/72607588/171958412-4506cb44-ed9d-4353-acc5-53d504f7b949.png)

### Version Information

```shell
uMortal
aT ausPIcIouSnu:I Can T
-
Tush] CMI: 9,1,5 0LLUshI MySQL
CMILib: 1.1.2.6
Lushl Server: Furpur 1.18.2-F0.1-SNAPSHOT
[Lush] CMI economy: Enabled CLush] Vault: 1.7.3-CMI CLushI CMI
Chat: Enabled
[Lush] Modules
-› 53 enabled 3 disabled: tablist, ranks
holograns
Open original
start grinding the naxt
for? a LI
```

### Relevant Plugins

CMI

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
U can disable Showing all link sure...
Use sonething else like other do..
Most people use a letter (nondot) or simply the * before.
If u still want your thing with the dot u need to edit your link capture regex
