### ISSUE TITLE
9.1.5.0: Days pass super fast

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#6956]
### Description of Issue

After updating to 9.1.5.0 after some uptime world time gets frozen at 5:30 AM and each tick new day starts. My world got 500k days old because of this bug. When I set time using `/time day` the time goes like 3-5 times faster and when reaches 5:30 AM the issue reappears.

https://user-images.githubusercontent.com/43506080/172271423-2b74371e-425f-40c2-a05c-d59ff70d3842.mp4

### Version Information

```shell
9.1.5.0 with bungeecord
CMILib: 1.1.2.6
Server: Purpur 1.18.2 build 1628
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
What Times u defined in config for this world?

**Comment by radiant-ai** [comment]
> What Timespeed u defined in config?
> 
> ```
>   # Allows you to change vanilla time speed to your own liking and needs
>   TimeSpeed:
>     # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
>     world:
>       Enabled: true
>       # Default value: 600 Starts from tick: 0 Ends at tick: 12000
>       day: 600
>       # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
>       sunset: 90
>       # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
>       night: 420
>       # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
>       sunrise: 90
>     # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
> ```

Irrelevant to the issue, the config section was not changed when updated

**Comment by radiant-ai** [comment]
`9.2.0.0` the issue persists. Had to rollback to `9.1.4.0`.
(PROBABLY) Looks like this starts to happen after someone slept and fast forwarded time.

**Comment by Zrips** [comment]
Should be fixed with next build. Tho this issue most likely relates to custom smooth time change setup which derped out for some reason. If issue persists, let me know, tho open new ticket and provide entire time section from config file.

**Comment by radiant-ai** [comment]
I did not touch config at all, it was a plugin update. The issue got fixed
after rollback to 9.1.4.7.
