### ISSUE TITLE
Add Recovery Compass for boss bar death location

### ISSUE THREAD

**Issue by sketrick** [Zrips/CMI#6971]
Currently we have options like this
Compass:
  BossBar: true
  RequireCompass: true
  UpdateInterval: 100
  ShowHome: true
  Home: ۩
  ShowSpawn: true
  Spawn: ⤋
  ShowDeath: true
  Death: ☠
  ShowCompassTarget: true
  CompassTarget: ꖴ

I would like another option or something similar to this:

#Requires recovery compass to enable death location in compass bossbar.

RequireRecoveryCompas: ture/false

**Comment by Zrips** [comment]
Will do, with next update
