### ISSUE TITLE
missing death message and not working death message

### ISSUE THREAD

**Issue by dan28000** [Zrips/CMI#6973]
### Description of Issue

missing death message 1.18.2 purpur
![image](https://user-images.githubusercontent.com/84990628/173627727-7fce55e7-93c9-46c4-bf51-fdac4820b9d2.png)
also still not working on 1.16.5 purpur
![image](https://user-images.githubusercontent.com/84990628/173628574-5d4036cd-8eea-40d9-a061-43ac8bbcd6f0.png)

### Version Information

```shell
CMI: 9.2.0.1 SqLite-> 9.2.0.0
CMILib: 1.2.0.2 
Server: Purpur 1.16.5-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will add missing death message and will fix that one for purpur, tho that one requires specific support as for some strange reason event which should return lava damaging block doesn't actually do it.
