### ISSUE TITLE
Missing translation in CMILib

### ISSUE THREAD

**Issue by Z1xus** [Zrips/CMI#6979]
### Description of Issue

There is a string for the Iron Golem, however it doesn't change anything.

### Version Information

```shell
--------------------------------------------------
CMI: 9.2.0.3 BungeeCord  SqLite
CMILib: 1.2.0.2
Server: Purpur 1.19-R0.1-SNAPSHOT
CMI Economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled
Modules -> 55 enabled 1 disabled: tablist
--------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Translated entity names are not being used everywhere, will add this one to spawner picker UI. I can add it to other places if there is one which still missing it.
