### ISSUE TITLE
[Small-Feature] Cooldowns between tpa

### ISSUE THREAD

**Issue by AntoineHrn** [Zrips/CMI#698]
Hi,
I would love to have cooldown supported by CMI for tpa commands so players can only use this very strong feature from times to times.
I have to download a whole other plugin to get this and this is sad.
Kind regards.

**Comment by AntoineHrn** [comment]
Okay thanks for your answer but I have trouble understanding what to do to get, for an example, a 3600secs cooldown on the tpa command.

**Comment by Gasha666** [comment]
Cooldowns:
  # You can enable any command cooldown to prevent instant usage of it
  # cmi heal:180 means that player can use /cmi heal command only once every 180 seconds
  # if cooldown set to -1 then this command can be performed only one time
  # Administration can bypass limitations with cmi.command.[comandName].cooldownbypass permission node
  # Always use full command name and not its alias
  Enabled: true
  List:
  - Heal:180
  - Feed:120
  - cmi warp:1
  - cmi tpa:3600

here it is..if you use this then players will have 3600 seconds (1 hour) cooldown on /tpa command

**Comment by AntoineHrn** [comment]
Thank you, I feel really poor not seing this config.
