### ISSUE TITLE
/saveditems get

### ISSUE THREAD

**Issue by MrJackcall** [Zrips/CMI#6982]
### Description of Issue

Command: **/cmi saveditems get 4 -t:MrJackcall -a:1 -c:AdminItem -s** will not work with **-a:1**
It works without **-s** (giving 1 item), but not works with both **-a:** and **-s**
In short: arguments -a and -s do not works together
(In the photo, I used the commands in this sequence: 
1) /cmi saveditems get 4 -t:MrJackcall -a:1 -c:AdminItem -s (Nothing)
2) /cmi saveditems get 4 -t:MrJackcall -c:AdminItem -s (Gives 64 items)
3) /cmi saveditems get 4 -t:MrJackcall -a:1 -c:AdminItem (Gives 1 item)

![image](https://user-images.githubusercontent.com/87709785/174146771-e3b50f7c-411b-4cf2-b492-4cad0457cd7d.png)

**YouTube:** https://youtu.be/TeG6eeihHpk

### Version Information

```shell
9.1.3.1
```

### Agreements

- [X] My server is supported by CMI.
- [ ] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
Habe u tried -c usung before -a?

**Comment by CloudeLecaw** [comment]
Have you rechecked this behave with 9.2.0.3?

**Comment by Zrips** [comment]
Gets fixed with next version
