### ISSUE TITLE
Can't delete the command of /powertool

### ISSUE THREAD

**Issue by Z1xus** [Zrips/CMI#6987]
### Description of Issue

I added the command to the sword, but now can't delete it. I'm trying to delete it, confirming it, and it shows like it's successfully deleted, but the powertool still works and the command appears again.

### Version Information

```shell
--------------------------------------------------
CMI: 9.2.0.3 BungeeCord  SqLite
CMILib: 1.2.0.2
Server: Purpur 1.19-R0.1-SNAPSHOT
CMI Economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled
Modules -> 55 enabled 1 disabled: tablist
--------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next build
