### ISSUE TITLE
Signs Section in Locale_EN.yml

### ISSUE THREAD

**Issue by iblacksheep** [Zrips/CMI#6990]
### Description of Issue

My Locale_EN.yml file generates without the necessary information under the Signs heading to create toplist signs. I've tried regenerating the file, and it regenerates that way. I am up-to-date on the version (7.0.0.3 for TryMe and 1.2.0.2 for CMILib). I've looked for a reference file and asked about it in the community discord. Not sure why it is generating this way, but it's rendered top signs useless. Please advise?

### Version Information

```shell
20.06 11:45:11 [Server] INFO CMILib version 1.2.0.2
20.06 11:45:11 [Server] INFO CMI library
20.06 11:45:11 [Server] INFO Website: https://www.spigotmc.org/resources/cmilib.87610/
20.06 11:45:11 [Server] INFO Author: Zrips

('cmi version' does not work for me, nor does 'cmil version'. I used 'ver cmilib')
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
Why postet in wrong github?
Close this one and reopen it here
https://github.com/Zrips/TryMe
