### ISSUE TITLE
Enhancement of invload command

### ISSUE THREAD

**Issue by DreamSky7** [Zrips/CMI#6991]
Add command **/invsave [slots]** save the items in the specified backpack slot

For example, if I want to save the items of 0,3,5 slots of quickbar in my backpack,
 I can use **/invsave 0,3,5** to save the items of the corresponding slots. 
I hope it can be adopted. Please

**Comment by CloudeLecaw** [comment]
If ever added you need to think about an other command snytax for your slots ;)
The current wasnt choosen very good and looked like u havent took a look hiw current invsave command works.

Currently structure is:
cmi invsave (playerName) (id) (-s)

So logical your slot idea can only come after the id if ever added. So your command syntax wiuld change to
**_cmi invsave (playerName) (id) (slot,slots) (-s)_**

**Comment by CloudeLecaw** [comment]
Pls move to discussion. :-)

**Comment by DreamSky7** [comment]
I have moved to discussion ！ 
Hope to adopt
**cmi invsave (playerName) (id) (slot,slots) (-s)**

**Comment by CloudeLecaw** [comment]
If u moved it to discussion by yourself allready pls close this issue :-)
