### ISSUE TITLE
GSON Error when pasting link and adding backslash

### ISSUE THREAD

**Issue by klaidosHka** [Zrips/CMI#6999]
### Description of Issue

This was seen, when one of the players was advertising certain link to other player, but added `\` at the end of the link accidently. Everyone who had spy-chat (and the user itself, who got the message) could see the raw Json message, which includes everything: [..all the stuff that is included in that certain message...], it takes around 15-20 lines to read.

**..my CMI version is not the latest, however, for some reason I think that it is not fixed in the latest version either and I can't take some time to test it out, so, still posting this. If this already is fixed in latest versions, it will take less time to close the ticket for you  than for me to test it out🙂**

### Version Information

```shell
9.1.1.0
```

### Errors

At the very first line can be seen which command was used to get the error, the backslash was the cause.
[Pastebin](https://pastebin.com/ewMkJZPQ)

### Agreements

- [X] My server is supported by CMI.

**Comment by Zrips** [comment]
Should be fixed with next CMILib release
