### ISSUE TITLE
Visual glitch when left clicking a kit you can not claim

### ISSUE THREAD

**Issue by samidont0817** [Zrips/CMI#7001]
### Description of Issue

When left clicking a kit you do not have access to, it takes you to the kit preview gui. In side kit preview gui however, it also keeps the block used to display the kit in the gui.
https://www.youtube.com/watch?v=Y0g3jt7GseQ
In the video, the first click was claiming the kit able to be claimed. 
The second click was left clicking a kit unable to be claimed, and it puts the wool block into the kit preview gui.
The third click is right clicking a kit to preview it.

### Version Information

```shell
CMI: 9.2.0.3 BungeeCord  SqLite
CMILib: 1.2.0.2 
Server: Purpur 1.18.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Disabled 
Modules -> 27 enabled 29 disabled: spawnerProximity, cuffed, mirror, tablist, moneyCheque, skin, noTarget, cmiPlaytime, bossBarCompass, coloredArmor, votifier, shulkerBackpack, spawnerCharge, vanish, namePlates, homeInteractions, hpBossBar, portals, holograms, jail, spawners, paintingEditor, dynamicSigns, durabilityLoss, flightCharge, schedule, disabledEnchants, worldLimits, totemBehavior
```

### Errors

```shell
There are no errors in console when this happens.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Skizzles** [comment]
@Zrips any update on this?

**Comment by Zrips** [comment]
Gets a fix with next version.
