### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by linkea131** [Zrips/CMI#7005]
### Description of Issue

Restarting the server or reloading the plugin to take effect after translation completion will cause the translation to be replaced with the default language file

### Version Information

```shell
[14:00:58 INFO]: --------------------------------------------------
[14:00:58 INFO]: CMI Plugin version: 9.2.0.4 SqLite
[14:00:58 INFO]: §eCMILib: 1.2.0.3 
[14:00:58 INFO]: server version: Mohist 1.12.2-R0.1-SNAPSHOT
[14:00:58 INFO]: CMI economy: Enabled economy: 1.7.3-b131 CMI to chat with: Disabled 
[14:00:58 INFO]: module -> 55 activated 1 disabled: votifier
[14:00:58 INFO]: --------------------------------------------------
```

### Errors

```shell
Restarting the server or reloading the plugin to take effect after translation completion will cause the translation to be replaced with the default language file
```

### Relevant Config Sections

```yaml
Restarting the server or reloading the plugin to take effect after translation completion will cause the translation to be replaced with the default language file
```

### Relevant Plugins

9.2.0.4

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by ZeromaniacMc** [comment]
**Errors** I'm pretty sure refers to 'console errors' aka copy paste your console log from `Logs/latest.log`. 
**Relevant Config Sections** would be the translated file, especially if the error mentions/points towards it. 
Besides all that, according to a message by Floris on Discord from 6/10/22, Mohist is not officially supported.

**Comment by Zrips** [comment]
If you have missformat in your locale file then it gets automatically saved into backup folder while default EN locale gets generated over it to atleast have some working version of locale. You can always check your backup folder and after fixing missformat replace appropriate file with it and you are good to go.
Using something like https://yaml-online-parser.appspot.com/ helps out to test your yaml files before applying it on the server
