### ISSUE TITLE
ArmorChangeEvent ignores some materials

### ISSUE THREAD

**Issue by FurkanZhlp** [Zrips/CMI#7009]
### Description of Issue

Armor change event is ignores this materials;
- Skulls
- Turtle Shell
- Netherite Armors

### Version Information

```shell
CMI 3.2.0.4
CMILib 1.2.0.3
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next CMILib update
