### ISSUE TITLE
manual Rank Up Feature

### ISSUE THREAD

**Issue by WalkingPixel1** [Zrips/CMI#701]
/rankset feature - I was wondering if it were possible to do the following when manually setting a rank to someone.

When setting a rank to someone manually it currently doesn't issue the commands you put in the config to execute so when making someone a rank manually could it work so it does the same as when you normally rank up? so for example

/Rankset WalkingPixel TestRank

Commands given: /pex user walkingpixel group add TestRank

Thank you! 💃

**Comment by Zrips** [comment]
This one was added and now you can add -cmd variable to rankset to perform commands attached to that rank.
