### ISSUE TITLE
CMI vanish feature "Playtime will stop increasing" not working anymore

### ISSUE THREAD

**Issue by bluestormhunter** [Zrips/CMI#7018]
### Description of Issue

Having "Playtime will stop increasing" set to "true" in vanishedit does not stop your playtime from increasing and can therefore be used to determine if a player is currently in vanish mode.

### Version Information

```shell
[15:12:09 INFO]: CMI Plugin Version: 9.2.0.4 SqLite
[15:12:09 INFO]: CMILib: 1.2.0.3 
[15:12:09 INFO]: Server: Purpur 1.19-R0.1-SNAPSHOT
[15:12:09 INFO]: CMI economy: Aktiviert Vault: 1.7.3-CMI CMI Chat: Aktiviert
```

### Errors

```shell
no errors can be seen in console
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Tested out and it looks to be working correctly, playtime does stop when you enter vanish mode. Are you using CMI vanish or another plugin for that?

**Comment by bluestormhunter** [comment]
Using CMI vanish and CMI stats for this. `PlaytimeFromStats` is set to "true". Could this be the cause?

**Comment by bluestormhunter** [comment]
Still occurs with `PlayTimeFromStats` set to false

**Comment by bluestormhunter** [comment]
Playtime still updates for vanished players even with the following options:

```
 PlayTimeFromStats: false
  # Do you want to run auto top playtime updater
  # This is responsible for providing players current top playtimes which gets updated on consistent intervals, useful for placeholders
  PlayTimeAutoUpdater: false
  # When set to true, playtimetop list will be loaded on server startup
  PreloadTopPlaytime: false
  # Do you want to use CMI playtime tracking
  # While this is enabled, player play time will be record for each hour he playied in server
  # This doesnt have effect on rankup or /playtime commands, it will only show more specific playtime by hours when using /cplaytime command
  CMIPlayTimeTracking: false
```

**Comment by bluestormhunter** [comment]
The following placeholders also update while vanished:

```
%cmi_user_playtime_dayst%
%cmi_user_playtime_hours%
%cmi_user_playtime_hoursf%
%cmi_user_playtime_hourst%
%cmi_user_playtime_minutes%
%cmi_user_playtime_minutest%
%cmi_user_playtime_seconds%
%cmi_user_playtime_secondst%
```

**Comment by Zrips** [comment]
Will be fixed with next update
