### ISSUE TITLE
Please help me I can't reload after reload Error after completing some translations

### ISSUE THREAD

**Issue by linkea131** [Zrips/CMI#7019]
### Description of Issue

Failed to load Locale_CN.yml! Backup have been saved into plugins/CMILib/FileBackups/2022-06-29 15-54-11 Locale_CN.yml
SEVERE LOCALE FILE READ ERROR. Check your spelling! Changes will not be applied until you fix it or perform server restart which can result in locale file reset to default

### Version Information

```shell
9.2.0.4
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
You can use https://yaml-online-parser.appspot.com/ site to check for any errors in your new locale file or check console error message which usually indicates where it failed and why. You can always redownload original file and use that until your modified one gets fixed
