### ISSUE TITLE
New Custom Recipes - Stonecutter not detecting CustomModelData

### ISSUE THREAD

**Issue by MarkinhosMLP** [Zrips/CMI#7026]
### Description of Issue

Im trying to make customrecipes where in the stonecutter, applying a shield you can select a lot of other shields usind CustomModelData, but i cant, it says the recipe already exists even if the custom model data is different 

### Version Information

```shell
CMI 9.2.1.0
CMILIB 1.2.0.4
Purpur 1.18.2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will fix general issue while using similar items with different meta data to produce same things, but for your situation in particular I would suggest to use basic crafting bench as there is issue with stone cutter including all recipes relating to material type in ingredient slot and not just particular ones you can craft with it, its client sided issue which cant really be fixed from my end and need Mojang attention.
