### ISSUE TITLE
Can CMI synchronize data?

### ISSUE THREAD

**Issue by PikaSama** [Zrips/CMI#703]
**Description of issue or feature request:**
CMI uses Mysql for storage. But why can't it synchronize data?
Please forgive me, my English is not very good

**Cmi Version (8.0.4.0)** 

**Server Type (Spigot)** 

**Server Version (git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**

**Comment by Zrips** [comment]
Because data save and data synchronization is completely different things. Especially when we need to keep preloaded data to avoid hiccups when checking players . This is something that will be done in future updates, but currently, there is no data sync.
