### ISSUE TITLE
/invsave date always 01/01/70 00:00:00

### ISSUE THREAD

**Issue by Z1xus** [Zrips/CMI#7034]
### Description of Issue

Whenever I use /invsave, it saves empty inventory with the date of 01/01/70. However, it is happening only to the players banned with AdvancedBan.
![image](https://user-images.githubusercontent.com/40185941/177039494-41455598-6da2-4d14-8677-9050ed36fe85.png)

### Version Information

```shell
CMI: 9.2.1.1 Bungeecord  Sqlite
CMILib: 1.2.1.0
Server: Purpur 1.19-R0.1-SNAPSHOT
CMI Economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled
Modules -> 55 enabled 1 disabled: tablist
```

### Relevant Plugins

AdvancedBan 2.3.0

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
these colors do not look like cmi.... 

you said you save inventorys of banned players so this means they are not online anymore
first could you check that their inventory is fine?

/cmi inv PLAYERNAME    then  /cmi invsave PLAYERNAME

make sure not just to use /invsave   - first it could be not CMI.  sound this would only save your inventory.
so use a playername after.

If it still not working correctly it might be a Purpur related issue.. 
could you retry it on testserver with spigot/paper?

**Comment by Z1xus** [comment]
you can change colors in the locale file.

I executed /cmi inv PLAYERNAME, it showed me the player's inventory. after I used /cmi invsave PLAYERNAME, It saved empty inventory.

also I'm using Geyser and Floodgate, It might be the UUID issue.

even after I unban the player and they will join the server, /cmi invsave PLAYERNAME still gives me empty inventory.
I will make a few tests. I'll let you know when I'm done 🤝

**Comment by CloudeLecaw** [comment]
hm thats interesting. i tried it today with paper and others and thete was no issur with it.
the only difference was im using just the  regular ban Features that using spigot defaults.

so what happens if you ban soneone with cmira ban and not using advanced ban?

**Comment by Z1xus** [comment]
no, there is no problems with /cmi ban

I think the problem is in AdvancedBan, because it is not updating for more than a year, and there are a lot of bug reports on their GitHub.

**Comment by Z1xus** [comment]
Also, it looks like there is a problem with reaching advancedban's database, because whenever I run /advancedban check PLAYERNAME it is says N/A in every string, even when the player just disconnected

**Comment by Zrips** [comment]
@Z1xus 
What do you have set for LongDateFormat2 in config file? As recorded time is taken directly from system clock and then simply by using provided time format converts it into output you see on screen.

**Comment by Zrips** [comment]
Ok, issue is in general with attempt to save inventory on a player who isint online, will fix this one with next update.
