### ISSUE TITLE
Custom recipe fatal error

### ISSUE THREAD

**Issue by surfishs** [Zrips/CMI#7038]
### Description of Issue

When using a custom synthesis recipe, only the first synthesized item meets our needs. If we use the shortcut "shift" and left-click to remove the item, the NBT tag of the subsequent items will change, which will affect subsequent use. .
Example:
{Count:4b,id:"minecraft:ink_sac",tag:{Enchantments:[{id:"minecraft:aqua_affinity",lvl:1s}],HideFlags:1,display:{Lore:['{"extra": [{"italic":false,"color":"green","text":"2"}],"text":""}'],Name:'{"italic":false,"extra": [{"text":""},{"color":"dark_green","text":"1"}],"text":""}'}}}

{Count:4b,id:"minecraft:ink_sac",tag:{Enchantments:[{id:"minecraft:aqua_affinity",lvl:1s}],HideFlags:1,display:{Lore:['{"italic": false,"color":"white","extra":[{"text":""},{"color":"green","text":"2"}],"text":""} '],Name:'{"italic":false,"extra":[{"text":""},{"color":"dark_green","text":"1"}],"text": ""}'}}}

### Version Information

```shell
9.2.1.1
1.2.1.0
parper(216)1.18.1-R0.1-SNAPSHOT
1.7.3-cmi
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Can you give actual example of recipe in question from recipes.yml file for testing with actual items used in recipes?
