### ISSUE TITLE
Narrator don't read chat..

### ISSUE THREAD

**Issue by BlindAdam23** [Zrips/CMI#7041]
### Description of Issue

'm visually impaired and I use the narrator to read chat, but on my server it don't read chat at all I have tried with a fresh install of cmi but still the same results..

### Version Information

```shell
cmi: 9.2.1.1 sqlite
cmilib: 1.2.1.0 -> 1.2.1.1, whisch I don't understand it's been updated and the old version is deleted
server:paper(387) 1.18.2- RO. 1 snapshot
cmi economy: disabled cmi chat: enabled
modules -> 55 enabled 1 disabled: votifier
```

### Relevant Plugins

I've taken cmi off and the narrator works for chat with all the other plugins still on the server, when I put cmi back on it stops working again..

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Could you elaborate more on which messages in particular are not being narrated for you?

**Comment by BlindAdam23** [comment]
Zips I'm sorry I made a mistake please watch it's only 7 minutes and explains it all..
https://www.youtube.com/watch?v=CS2wg_MYzOM

**Comment by BlindAdam23** [comment]
It's regular chat that it don't narrate.. It's strange because I only have problems on my server and other ones with cmi work fine.. I thought it was a setting issue but the discord said it sounded like a bug..

    On Tuesday, July 12, 2022 at 06:43:08 AM PDT, Zrips ***@***.***> wrote:  
 
 


Could you elaborate more on which messages in particular are not being narrated for you?
