### ISSUE TITLE
Items with hex codes in their names

### ISSUE THREAD

**Issue by hotspuraz** [Zrips/CMI#7046]
### Description of Issue

Players without permission to add colour to item names, can put the hex codes into the name and do [item], it will show in colours in chat. This also works in death messages 

https://i.imgur.com/eCWWRkO.png

### Version Information

```shell
This is in all the latest versions of cmi
```

### Errors

```shell
no errors in the console
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
is this with latest CMI builds? As this was addressed few versions back.
