### ISSUE TITLE
Recipe Permission

### ISSUE THREAD

**Issue by Rexmen1** [Zrips/CMI#7047]
### Description of Issue

- cmi.command.recipe
- cmi.command.recipe.admin:
    value: false

this the permission for default rank but still allowing players to disable the recipes....

### Version Information

```shell
CMI 9.2.1.1
CMILib 1.2.1.1
purpur 1.19
```

### Errors

```shell
No errors
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by dan28000** [comment]
Same issue here

**Comment by konsheng** [comment]
Same issue here

**Comment by huanym** [comment]
Same issue here

**Comment by konsheng** [comment]
Same issue here

**Comment by Shadows1102** [comment]
Same issue here

**Comment by Zrips** [comment]
Issued hotfix
