### ISSUE TITLE
Custom heads in worth list reset to human heads after /cmi reload

### ISSUE THREAD

**Issue by Bunnky** [Zrips/CMI#7049]
### Description of Issue

We use custom heads as a sellable resource. Sometime recently, reloading CMI breaks all of the model data, causing all heads to not be recognized when trying to use /cmi sell. This was working just fine prior to a fairly recent update to CMI/CMILib.

https://user-images.githubusercontent.com/6545569/178065211-bb459672-137b-46d8-bfc1-9a929264d842.mp4

### Version Information

```shell
CMI: 9.2.1.1 SqLite
CMILib: 1.2.1.0 -> 1.2.1.1
Server: Paper(50) 1.19-R0.1-SNAPSHOT
CMI economy: Enabled CMI Chat: Enabled
Modules -> 51 enabled 5 disabled: deathMessages, tablist, ranks, votifier, namePlates
```

### Errors

```shell
No errors are thrown, plugin seems to reload just fine.
```

### Relevant Config Sections

```yaml
worth:
  PLAYER_HEAD: '500.0'
  PLAYER_HEAD>WITHER: '7500.0'
  PLAYER_HEAD>BAT: '500.0'
  etc...

These are just heads with custom model data, custom names and lore, that we have set with /setworth.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

I have asked in Discord about this issue as well but I have not received any response
![image](https://user-images.githubusercontent.com/6545569/178065876-cd47c8f3-3bee-4830-a5f6-41d961069d65.png)

It was only today I discovered it was the reloading causing the bug.

**Comment by Zrips** [comment]
Should be resolved with next CMI and CMILib updates.
