### ISSUE TITLE
issues with !right! and !left!

### ISSUE THREAD

**Issue by Pan-nav** [Zrips/CMI#7051]
### Description of Issue

if I use the variable !right! or !left!, it just completely ignores it. we are still able to use it with other click, for more info ask Floris I had a convo with him about it, he knows how to reproduce...

### Version Information

```shell
CMI: 9.2.0.0 SqLite-> 9.2.1.1
CMILib: 1.2.1.0 -> 1.2.1.1
Server: Paper(40) 1.19-R0.1-Snapshot
CMI Economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
```

### Errors

```shell
Null
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Latest update should resolve this issue
