### ISSUE TITLE
TFLY.GIVE required to give to self

### ISSUE THREAD

**Issue by k0nker** [Zrips/CMI#706]
When using `/tfly` on yourself, it is requiring the permission `cmi.command.tfly.give` which is listed on the wiki as needed only needed if you wish to use `tfly` on others.

![image](https://user-images.githubusercontent.com/6345469/43648843-2ad5d200-9701-11e8-8c38-48e46562e64f.png)

![image](https://user-images.githubusercontent.com/6345469/43648945-6fca5d7c-9701-11e8-83df-5cdf7f96b1e0.png)

**Cmi Version (using`/cmi version`): CMI plugin version: 8.0.4.0** 

**Server Type (Spigot/Paperspigot/etc): PaperSpigot** 

**Server Version (using `/ver`): 1.13-#80**

**Comment by Zrips** [comment]
Will be changed to require generic cmi.command.tfly.others permission node and it fix your original issue
