### ISSUE TITLE
SQL ERROR

### ISSUE THREAD

**Issue by uploadx10** [Zrips/CMI#7062]
### Description of Issue

https://pastebin.com/40pYCTkY

### Version Information

```shell
https://pastebin.com/40pYCTkY
```

### Errors

```shell
https://pastebin.com/40pYCTkY
```

### Relevant Config Sections

```yaml
https://pastebin.com/40pYCTkY
```

### Relevant Plugins

-

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
How often does this error appear and what plugins do you have additionally to CMI?

**Comment by Zrips** [comment]
Do you have ForceSaveOnLogOut and/or ForceLoadOnLogIn enabled in dataBaseInfo.yml file?

**Comment by uploadx10** [comment]
yes

**Comment by Zrips** [comment]
Resolved
