### ISSUE TITLE
Kit menu doesn't go past two pages

### ISSUE THREAD

**Issue by GarchomPR0** [Zrips/CMI#7065]
### Description of Issue

Despite the fact that there are more than two pages worth of kits enabled, they are not all visible in the menu. The pages cap at 2/2 no matter what. It's also worth noting that as I disabled kits one by one, when I got to the point that it should've perfectly filled two pages, it automatically removed the second page. The rest of the kits were not shoved into a new menu, it just refused to show them. The page buttons also disappeared when this happened, only reverting when I enabled more kits.

### Version Information

```shell
CMI: 9.2.1.4 SqLite
CMILib: 1.2.1.2
Server: Paper(34) 1.19-R0.1-SNAPSHOT
CMI Economy: Disabled CMI Chat: Disabled
Mobules -> 55 enabled 1 disabled: votifier
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
https://github.com/Zrips/CMI/issues/7064

**Comment by Zrips** [comment]
Should be resolved with next build
