### ISSUE TITLE
Remove Cyclic dependency between CMILib & CMI

### ISSUE THREAD

**Issue by Owen1212055** [Zrips/CMI#7070]
### Description of Issue

CMI's plugin.yml currently **depends** on CMILib.

CMILib's plugin.yml currently **softdepends** on CMI AND **loadbefore** CMI.
This doesn't make much sense behavior wise, see: https://github.com/TechFortress/GriefPrevention/pull/1912

This causes a cycle where CMI is depending on CMILIB which is depending on CMI, and this causes some unexpected issues when loading plugins.

I recommend resolving this issue by removing CMI as a dependency for CMILib. As a result however you will need to make sure that they do not share code together and are correctly isolated. 

This behavior may not be supported in future versions of paper.

### Version Information

```shell
N/A
```

### Relevant Plugins

N/A

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be addressing this. To give some explanation why it is this way. CMILib generally originates from CMI itself, so basically CMI got split into Library component and general CMI plugin which specializes more into specific actions. This still has some left overs where CMILib can utilize some methods from CMI which provides extra features which are not present in CMILib itself. Will have to update internal code and try to completely separate those from each other.

**Comment by Zrips** [comment]
For time being I can just remove softdepend reference and loadbefore, as those basically irrelevant and has no real effect anymore.

**Comment by Owen1212055** [comment]
Thanks very much for your explanation and the quick fix. :)
