### ISSUE TITLE
PlayerInteractEvent Error

### ISSUE THREAD

**Issue by Henriiig** [Zrips/CMI#7084]
### Description of Issue

Error in console on 1.8.8 papermc

### Version Information

```shell
9.2.2.0
```

### Errors

```shell
https://pastebin.com/08c8LzcW
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next CMILib update
