### ISSUE TITLE
wrong using placeholders for aliaseditor

### ISSUE THREAD

**Issue by alisa12s** [Zrips/CMI#7090]
### Description of Issue

placeholders in aliaseditor have bad works

### Version Information

```shell
Version plugin CMI 9.2.2.0
CMILib 1.2.2.0
```

### Errors

```shell
hi. we have a problem. after last update cmi, broke using placeholders in aliaseditor.
if i`m create test alias
/al test
msg! [playerName] %math_$1+$2%

me send massage error
The provided value was invalid!
Reason: Unknown unary operator '$' at position 1

aliaseditor does not want to accept arguments of the alias itself, or a placeholder inside a placeholder.

also. the priority of using an alias within an alias has changed. now the main alias is executed to the end first, and then the others inside it, which also breaks the logic.

looks pls my video: https://www.youtube.com/watch?v=ECR3xE4u6b4
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Try using CMI equation solver as `msg! [playerName] %cmi_equation_$1+$2%` but this should be resolved now and works correctly. There might be issues with your setup if you are not providing any variables for this equation solver. 
More correct usage would be something like this
```
    Cmds:
    - check:$2==null! msg! [playerName] &2Enter 2 variables
    - check:$2!=null#!
    - msg! [playerName] %cmi_equation_$1+$2%
```
