### ISSUE TITLE
setspawn

### ISSUE THREAD

**Issue by FBDKPlus** [Zrips/CMI#7093]
Visit https://github.com/Zrips/CMI/discussions/new to post question
Posting questions in ticket section could result in their removal.

I want to set the main city through instructions. Although your CMI plug-in has coordinates and world setting instructions, they have not taken effect!

i use command：/setspawn true -g:sorth -rng:0 -w:YCraft_ 20V20 loc:YCraft_ 20V20; 0 l74;- 155;- 0.45004272;- two point seven zero zero zero nine three three

He told me the format was wrong

**Comment by thomaboehi** [comment]
-g:sorth

you mean north?

**Comment by CloudeLecaw** [comment]
your stuctue migt got formated stange..?

i aspect your permission group is called north right?

`[setspawn (playerName) (true/false) (-g:[groupName]) (-rng:[range]) (-w:world,world_nether) (loc:[world;x;y;z;yaw;pitch])]`

so it would be:

`/cmi setspawn true -g:sorth -rng:0 -loc:YCraft_20V20;0;174;-155;-0.45004272;-2.7000939`

i would recomment to move to the Position and use /cmi tpopps and then press TAB TAB TAB to check that you used the right cords, yaw and pitch

**Comment by FBDKPlus** [comment]
firist i very thanks u,no one others turn help me,i use your way commands it tell can't player with this name ,i think "-loc" not can't check with CMI lol，I thinks it is a bug，I wait he update

**Comment by CloudeLecaw** [comment]
ohh have you tried loc instead if -loc?

```
/cmi setspawn true -g:sorth -rng:0 loc:YCraft_20V20;0;174;-155;-0.45004272;-2.7000939```

**Comment by Zrips** [comment]
@FBDKPlus 
Your command format was incorrect which caused this issue. If you are not sure about commands usage you can always double check it with "/cmi setspawn ?" which will output general usage
