### ISSUE TITLE
actionbar doesn't work

### ISSUE THREAD

**Issue by dan28000** [Zrips/CMI#7098]
### Description of Issue

When using /back /home into residence actionbar doesn't show up or when using back into non residence area
first error non residence area
second error into residence area
anything that uses actionbar

### Version Information

```shell
9.2.3.0 CMI
1.2.3.0 CMILib
5.0.0.7 Residence
on purpur 1.18.2
```

### Errors

```shell
https://pastebin.com/FDJPynxs
```

### Relevant Plugins

5.0.0.7 Residence

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mercurialmusic** [comment]
I think this is what I'm seeing too:
https://gist.github.com/mercurialmusic/e668dcf8beed5523c65c5a605b16e399
https://gist.github.com/mercurialmusic/dedc6a4462445fa7af6f3da9d57a6005

CMI plugin version: 9.2.3.0 BungeeCord CMIB  SqLite
CMILib: 1.2.3.0 
Server: Paper(387) 1.18.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 54 enabled 2 disabled: ranks, skin

**Comment by YuanYuanOwO** [comment]
same issue   
https://paste.helpch.at/itinijojop.sql  
i just update cmi and cmilib yesterday
