### ISSUE TITLE
underscores not possible to suggest in tabcomplete

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7103]
### Description of Issue

a own created tab suggestion for custom alias shows a SPACE no matter if your using _  or __

So you cant choose tab suggestions like word_nether or world_the_end
they will be shown as  world nether   and   world the end

### Version Information
![Snag_2ee975](https://user-images.githubusercontent.com/12080017/182002125-43cb3999-e716-425c-809b-93fef62966d3.png)

### Errors
![Snag_2f1577](https://user-images.githubusercontent.com/12080017/182002130-f82ebcfe-16ba-411d-9982-b6fb62aef6d4.png)

the suggestion shows a SPACE no matter if your using _  or __

### Relevant Config Sections
Custom alias:
```
    Tab: true
    CustomTabs:
    - 10, Farmwelt,LuluGames,plotworld,testwelt,tutorial,world,world__nether,world__the__end
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Frozenbloo** [comment]
I am also having this issue on the version below

![image](https://user-images.githubusercontent.com/61006165/184461048-94838d62-4cb2-4d40-9283-4ce5ac0a0023.png)

Currently this is preventing me from tab completing Items, as they need to have underscores to register as their material.
![image](https://user-images.githubusercontent.com/61006165/184461100-937e268e-63b9-4947-bb95-5fb6476a6e7f.png)


It also causes internal errors
![image](https://user-images.githubusercontent.com/61006165/184461094-3be4fc75-e19c-43eb-b9ff-3cfd0453df96.png)

Relevant Config (Sorry i can't post the full thing as its over 1000 lines long)
` 
    CustomTabs:
    - STONE
    - GRANITE
    - POLISHED_GRANITE
    - DIORITE
    - POLISHED_DIORITE
    - ANDESITE
    - POLISHED_ANDESITE`

**Comment by Zrips** [comment]
Underscore identifies space, if you want actual underscore as a suggestion then you will need to use double, so it should be like
```
    CustomTabs:
    - 10, Farmwelt,LuluGames,plotworld,testwelt,tutorial,world,world__nether,world__the__end
    - STONE
    - GRANITE
    - POLISHED__GRANITE
    - DIORITE
    - POLISHED__DIORITE
    - ANDESITE
    - POLISHED__ANDESITE
```
Which said @CloudeLecaw setup should work just fine as it does as of some testing.
