### ISSUE TITLE
Using /clear  amount

### ISSUE THREAD

**Issue by natr566** [Zrips/CMI#7106]
### Description of Issue

When using /cmi clear it ignores the amount used after the command
Example: cmi clear Nathan bucket 1

Duplicating the bug required you to have more then one of the item your trying to clear

If you have more then one then it goes thought the clear all inventory warning and takes all of that item.

### Version Information

```shell
CMI: 9.2.3.0 SqLite
CMILib: 1.2.3.1
Server: Paper(81) 1.19-R0.1-SNAPSHOT
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Correct format is **/cmi clear Nathan bucket:1** as indicated in help page. 
Will add support for your format with next version for convenience

**Comment by natr566** [comment]
> Correct format is **/cmi clear Nathan bucket:1** as indicated in help page. Will add support for your format with next version for convenience

Ok, But it still clears all the inventory. If you have more then 1 of that item

**Comment by natr566** [comment]
Ok so update on this, it seems to work in the console consistently. But when done on game with the player it seems to be real inconsistent.
