### ISSUE TITLE
Custom alias error w/ [playerName]

### ISSUE THREAD

**Issue by GrimPod** [Zrips/CMI#711]
[playerName] isnt resolving in custom alias

**Cmi Version (using`/cmi version`):** 
8.0.4.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.13-RO,1-SNAPSHOT

**Comment by mobilephone2003** [comment]
+1

Broken since around 8.0.3.0.

Have been unable to upgrade since

**Comment by tmellen** [comment]
Same here.

**Comment by mobilephone2003** [comment]
Seems to be working as of 8.0.4.3

**Comment by CloudeLecaw** [comment]
hm i cant agree with you wie use the normal /w and the /w is just an customalais of /cmi msg... all fine here.
