### ISSUE TITLE
pweather doest work

### ISSUE THREAD

**Issue by punkydie** [Zrips/CMI#7110]
If I set pweather for a user it doesn't change anything. So if I then make global rain although I have made **cmi pweather user sun** for him it rains with him anyway.
---

CMI Version 9.2.3.0

Paper

1.12.2

**Comment by Zrips** [comment]
CMI uses generic API methods to change players personal weather, if that doesn't have desired effect then its most likely caused by another plugin interfering. Testing without any other plugin would indicate if this is actually CMI issue or some outside cause.
