### ISSUE TITLE
tptoggle setting is missing.

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7111]
### Description of Issue

when you gave staff member the permissions to use `/cmi tp `command. they get the meassage they cant teleport to player.

looking a bit arround and some testing shows me
they need the permission
**cmi.command.tptoggle.bypass** to be able to tp to a player.

so it means all players have this setting true/flase by default. (why?)

i was looking into cmi options, tried the command (that seems not to exist anymore), looked in cmi config and sadly saw that there is no setting to set a default setting for tptoggle for this.

so i see the need for may add this to the /cmi options commands, since i noticed it is no Part of cmi commands anymore.

so might you could add it to options of cmi options also with a default setting value like the other options have if no value was set by /cmi options

for now the issue only could be solved by giving all staff that is allowed to use the tp command also the permission:
cmi.command.tptoggle.bypass

### Version Information

```shell
[05:55:20 INFO]: --------------------------------------------------
[05:55:20 INFO]: CMI Pluginversion: 9.2.3.0 MySQL
[05:55:20 INFO]: CMILib: 1.2.3.1 
[05:55:20 INFO]: Server: Paper(81) 1.19-R0.1-SNAPSHOT
[05:55:20 INFO]: CMI Economy: Aktiviert Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Aktiviert 
[05:55:20 INFO]: Module -> 56 aktiviert 0 deaktiviert: 
[05:55:20 INFO]: --------------------------------------------------
```

### Errors

```shell
see issue description
no console errors
```

### Relevant Config Sections

```yaml
there are none for now :(
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
well we dont have set the options for many players so i will try to reset  this db field.

**Comment by Zrips** [comment]
You can check any new comers who recently joined your server for the first time and double check if their tpa acceptance is set correctly. This might only be issue with older accounts which might have experienced some conversion issues or they had their tpa acceptance disable some time ago manually or due to code issue.

**Comment by mrfloris** [comment]
By the way, tptoggle could be an alias you made ~ it's now `/cmi options acceptingtpa`, and alias.yml doesn't have tptoggle as alias (anymore). so it has to be an alias or from another plugin. 
(just some food for thought)

**Comment by CloudeLecaw** [comment]
i know that cmi doesnt has cmi tptoggle anymore
the bypass permission still exists.

**Comment by CloudeLecaw** [comment]
ticket is closed because the issue was solved from our site with deleting the filetable of options from database (we just had a few players, that had modfied options)
