### ISSUE TITLE
in PM prefixes don't work

### ISSUE THREAD

**Issue by dan28000** [Zrips/CMI#7114]
### Description of Issue

[sourceprefix] in /msg doens't work on same server
over bungee both [senderprefix] and [sourceprefix] don't work
![image](https://user-images.githubusercontent.com/84990628/182231271-8162f674-d989-4c31-b8ff-3816c327b7ba.png)
![image](https://user-images.githubusercontent.com/84990628/182231665-3174f850-a065-4a3e-b7e7-f60cb556c1ab.png)

### Version Information

```shell
9.2.3.1 CMI
1.2.3.2 CMILib
1.18.2 purpur
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Not all information is available over bungeecord, especially if player never joined target server. Will make some adjustments in CMILib to atleast prevent from this raw variable appearing.
