### ISSUE TITLE
CMI dye command not working with firework stars

### ISSUE THREAD

**Issue by MarkinhosMLP** [Zrips/CMI#7115]
### Description of Issue

coloring can be applied to leather items and it works perfectly, but coloring can also be applied in firework stars, but in the plugin, with the dye command, it doesnt works unfortunately 

### Version Information

```shell
tested it in a lot of versions, nowadays im using the last one
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
this is no bug report.

what you wanted is a feature to dye fireworks

**Comment by MarkinhosMLP** [comment]
> this is no bug report.
> 
> what you wanted is a feature to dye fireworks

Dye command is made so you can change dyable items colors with hex/pre-defined colors
firework star is the only dyable item you cant change with /dye command

**Comment by CloudeLecaw** [comment]
not really
its made ti change dye if leather items

**Comment by CloudeLecaw** [comment]
I belive, this ticket can be closed here now or may moved with an other title to discussion :)
