### ISSUE TITLE
Incorrect locale output

### ISSUE THREAD

**Issue by Rukes** [Zrips/CMI#712]
Using command `/tp <player>` outputs me wrong translation, in locale file I have this:

`feedback: '&7You have been teleported ([world],[x],[y],[z]) to &3[playerName]'`, but placeholder `[playerName]` sends me my nickname instand of target's player name.

**Comment by Rukes** [comment]
1.12.2, CMI latest

**Comment by Zrips** [comment]
Try using [sourcePlayerName] variable.
