### ISSUE TITLE
AsyncPlayerChatEvent does not work with CMILib v1.2.2.0+

### ISSUE THREAD

**Issue by deHasher** [Zrips/CMI#7126]
### Description of Issue

When Chat.ModifyChatFormat: true (in CMI config.yml) and CMILib v1.2.2.0+ in my plugin @EventHandler AsyncPlayerChatEvent (highest priority) event.setCancelled or event.setFormat do not work :/

### Version Information

```shell
Версия плагина CMI: 9.2.3.2 SqLite-> 9.2.3.1
CMILib: 1.2.3.2 
Версия сервера: Paper("e39995d21") 1.12.2-R0.1-SNAPSHOT
CMI Экономика: Enabled CMI Чат: Enabled 
Модули -> 22 включено 34 отключено: spawnerProximity, customMessages, mirror, tablist, versionCheck, moneyCheque, skin, noTarget, cmiPlaytime, rideAnimation, elytraLaunch, bossBarCompass, votifier, shulkerBackpack, attachedCommands, spawnerCharge, namePlates, timedCommands, launchPad, armorstand, jail, spawners, paintingEditor, flightCharge, deathMessages, schedule, disabledEnchants, worldLimitsElytra, worldLimits, ranks, firstJoinMessages, selection, silentChest, warmup
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Chat format gets modified at LOW and NORMAL priorities, there should not be any issues when it comes to HIGHEST. If you are using hoverover messages from CMI too then you might want to move your priority to HIGH instead
