### ISSUE TITLE
rankup sql

### ISSUE THREAD

**Issue by Chiquis2005** [Zrips/CMI#7127]
Is there a way to not save the rankup ranks in the database?

**Comment by CloudeLecaw** [comment]
well no...
but you could do two things..
add a scheduler that removed this database field all x hours
add a scheduler that removed this database field after server startup

command is
`cmi [resetdbfields [collumnName] (-w:[worldName]) (-p:[playerName])`
well in your chase -w and -p: are not needed ;)
u just need to find our how the columeName is called in your Database...
it might be rank, Rank, ranks or Ranks?

**Comment by Chiquis2005** [comment]
But isn't it a problem to do that if there are several players?

> well no... not really but...
> 
> you could do two things.. add a scheduler that removed this database field all x hours add a scheduler that removed this database field after server startup
> 
> command is `cmi resetdbfields [collumnName] (-w:[worldName]) (-p:[playerName])` well in your chase -w and -p: are not needed ;) u just need to find our how the columeName is called in your Database...
> 
> lets see..
> 
> ![image](https://user-images.githubusercontent.com/12080017/183007066-f83cc4c7-4739-4f23-82e7-f5a03984c6f8.png)
> 
> so try `cmi resetdbfields Rank`
> 
> You would have 2 scheduler option with this that you can use in schedules.yml
> 
> First - Repeating one (in this case all 5 minutes)
> 
> ```
> RepeatingCommandResetDB:
>   Enabled: true
>   FeedBack: false
>   Delay: 300
>   Repeat: true
>   Commands:
>   - cmi resetdbfields Rank
> ```
> 
> once after ServerRestart:
> 
> ```
> CommandsAfterServerstartResetDB:
>   Enabled: true
>   FeedBack: false
>   Delay: 150
>   Repeat: false
>   Commands:
>   - cmi cmi resetdbfields Rank
> ```

But isn't it a problem to do that if there are several players?

**Comment by CloudeLecaw** [comment]
not really. you just remove sma colum what is not much for a database and also not much for your server.

**Comment by Zrips** [comment]
Current rank gets saved for possible usage down the line. Originally have been based on actual saved rank and not your current permission, so its needed. You can reset database fields with **/cmi resetdbfields Rank** command which would remove all the records from all players but those will still get filled up in time.
One of the purposes is to know players rank when player is offline and we cant really use permission check due to it being mostly limited to player being online.
