### ISSUE TITLE
error Could not pass event PlayerBedEnterEvent to CMI v9.2.3.2 advancement

### ISSUE THREAD

**Issue by danyadanya2005** [Zrips/CMI#7128]
### Description of Issue

I don't know why it's an error. error for more than a month
Help me please

### Version Information

```shell
CMILib1.2.3.2.jar
CMILib1.2.3.2.jar
Paper version git-Paper-351 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: af3b377)
```

### Errors

```shell
https://pastebin.com/iXL5WFbZ
```

### Relevant Config Sections

```yaml
I don't know what to write here. forgive me
```

### Relevant Plugins

Vault-1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Gets a fix with next CMILib update

**Comment by danyadanya2005** [comment]
Thanks a lot
