### ISSUE TITLE
/cmi give hands out spawn eggs with 1 NBT tag, which vanish when changing spawner types with CMI spawners.

### ISSUE THREAD

**Issue by Flexxxxx** [Zrips/CMI#713]
As the title states. All spawn eggs given by /cmi give come with 1 NBT tag. Why is this a problem? Well these spawn eggs are incompatible with CMI’s spawner changing feature. These eggs disappear and DO NOT change the spawner type. 

**Cmi Version (using/cmi version):**
8.0.4.0
**Server Type (Spigot/Paperspigot/etc):**
Spigot
**Server Version (using /ver):**
1.13-RO,1-SNAPSHOT

**Comment by Zrips** [comment]
Should be fixed now.
