### ISSUE TITLE
Changing delay from seconds to ticks

### ISSUE THREAD

**Issue by Korinocho** [Zrips/CMI#7133]
It would be possible to change the specialized command delay! from seconds to ticks?
I have a very specific need but this could help other ones.

Thank you!

**Comment by Zrips** [comment]
You can use fractions. For example "delay! 0.5" will delay by 10 ticks, or something like "delay! 0.05" would be one tick delay

**Comment by Korinocho** [comment]
Oh. Didn't saw that on the website. Thanks!
