### ISSUE TITLE
Placeholders bug

### ISSUE THREAD

**Issue by Broascaa** [Zrips/CMI#7143]
### Description of Issue

The placeholder %world_time24_[worldname]% %world_time12_[worldname]% are not parsed in the scoreboard/tab/etc.. It's not hooked with placeholders api!
Proof:
![unknown](https://user-images.githubusercontent.com/86567732/183427617-ed3f305d-1c82-4294-ac51-4890707a02b9.png)

### Version Information

```shell
CMI: 9.2.3.2 BungeeCord  MySQL-> 9.2.3.3
CMILib: 1.2.3.3
```

### Errors

```shell
-
```

### Relevant Config Sections

```yaml
-
```

### Relevant Plugins

PlaceholderAPI 2.11.2

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be "fixed" with next version by introducing more dedicated placeholders like %cmi_world_time24_[worldname]% which will be parsed by CMI, PAPI or another plugin utilizing PAPI API. Old placeholders will still work, but we will fade those out as those will only work inside CMI.
