### ISSUE TITLE
[BUG] cmi home bug

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#715]
![image](https://user-images.githubusercontent.com/5382252/43713185-45a52f02-99ab-11e8-8fd8-0cfb58edab72.png)
![image](https://user-images.githubusercontent.com/5382252/43713299-b18eab12-99ab-11e8-877b-60c520fdb54f.png)

use happen

and some bug
can't use other Language
like /cmi sethome 測試
![image](https://user-images.githubusercontent.com/5382252/43713224-679de96e-99ab-11e8-8858-2cf9627152ef.png)

Can be used in previous versions
Hope to fix

**Cmi Version (using`/cmi version`): 8.0.4.2

**Server Type (Spigot/Paperspigot/etc): paper

**Server Version (using `/ver`): 1.12.2

**Comment by CloudeLecaw** [comment]
Pls try setting a home in latest cmi...

**Comment by Zrips** [comment]
This should work with latest builds.
