### ISSUE TITLE
cmi afk title settings aren't reseted

### ISSUE THREAD

**Issue by Ceddix** [Zrips/CMI#7153]
### Description of Issue

CMI has added a fade for the afk title with one of the last updates. However, the title settings are not reseted afterwards. So if I show a title to a player after he was in afk mode, it won't be shown for long if I don't manually reset the settings beforehand (`/title <player> reset`). So maybe CMI should reset that after the title is displayed 

### Version Information

```shell
[20:11:56 INFO]: --------------------------------------------------
[20:11:56 INFO]: CMI Plugin Version: 9.2.3.4 BungeeCord CMIB  MySQL
[20:11:56 INFO]: CMILib: 1.2.3.3
[20:11:56 INFO]: Server: Purpur 1.19-R0.1-SNAPSHOT
[20:11:56 INFO]: CMI economy: disabled CMI Chat: disabled 
[20:11:56 INFO]: Modules -> 47 enabled 9 disabled: spawnerProximity, worldLimits, tablist, votifier, moneyCheque, spawnerCharge, cmiPlaytime, vanish, homeInteractions
[20:11:56 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Show me your afk settings from config file.

**Comment by Ceddix** [comment]
Well, in itself this should be irrelevant, because in Vanilla it is for example the case that if you want to fade out a title *(as CMI does since one of the last updates, as soon as the afk mode goes off)*, you can use the command `/title <target> times <fadeIn> <stay> <fadeOut>`. This then changes the behaviour of the title when you then output it afterwards with `/title <target> title ...`. However, this value does not reset itself and is adopted for all future titles.

Of course, CMI does not work with commands, but I suspect something similar will happen here, only with plugin code.
Normally you should be able to reproduce this by going into afk mode (with title on) and after you go out, use `/title @s title "test"` to display a vanilla title to yourself. This will then *(unless I am wrong)* not be displayed for a long time as usual, but will be faded out directly (as CMI has "set" it beforehand).

I hope that is understandable. But of course it's also possible that I'm completely wrong.
Nevertheless, here are my current afk settings: https://pastebin.com/mzZXDjXE

**Comment by Zrips** [comment]
Hmmm, interesting discovery. Generally speaking this is how it works, i'm using official API at this point for title messages and it sends it with provided timers as it should. Vanilla title command on another hand sends without any timers which then uses previous ones by default. And trying to reset timer before title message is over would apply to currently visible message which on itself causes issues and more complex tracking of currently active timer would be needed, but if another plugin would send another title message with new timers that would mess things up even more.
Can't really do anything about it at the moment. You can simply use **/cmi titlemsg** command to send title messages with some preset timers or provide those inside command itself.
Did some testing, but no real solution at the moment.
