### ISSUE TITLE
Recipe menu

### ISSUE THREAD

**Issue by dan28000** [Zrips/CMI#7154]
### Description of Issue

when having custom recipe for example for gravel then the custom recipe isn't prioretized when used /cmi recipe gravel 
it was like that before update to recipes

### Version Information

```shell
[16:52:45 INFO]: CMI: 9.2.3.4
[16:52:45 INFO]: CMILib: 1.2.3.3 
[16:52:45 INFO]: Server: Purpur 1.16.5-R0.1-SNAPSHOT
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
