### ISSUE TITLE
equation solver placeholder cannot parse exponents

### ISSUE THREAD

**Issue by nomad1154** [Zrips/CMI#7155]
### Description of Issue

when attempting to parse a exp scaling equation in a placeholder CMI gives the below result. I have tested on both my servers CMI and a fresh jar.
![image](https://user-images.githubusercontent.com/71418086/184507386-ece85913-6d98-4f25-88f9-87e9ca8229bc.png)

using /cmi solve command the equation is solved perfectly fine

### Version Information

```shell
CMI: 9.2.3.3 SqLite 9.2.3.4
CMI Lib: 1.2.3.3
Server: Paper(387) 1.18.2-R0.1-Snapshot
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version
