### ISSUE TITLE
[Feature Request] TPO/Teleport Override

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#716]
**Description of issue or feature request:**
With today's change of tphere checking for tptoggle it brings up some previous frustrations with not having an admin override for TP, where if I need to TP a player to me or send them to a warp I've been stopped saying the player doesn't have permission or another plugin is interfering (usually Residence in our case). We really need a way around this, and I kinda miss the Essentials behavior where if an admin (or command block) performs the TP or warp command on behalf of the player it doesn't fail. With this new check, if the player is offline and has tp toggled off and I need to move them from their last location, will it now fail as well? 

If admin/op perms can't/won't override the regular tp commands, I would then like to request new /tpo & /tpohere (and maybe /tpoallhere ?) commands that will override all checks and will just straight up TP the player(s) where I need them to be.

**Comment by Zrips** [comment]
Well good point. Tho funk thing is that essentials not really doing anything special about teleportations, just using different teleportation cause which can be overlooked by some protection plugins and allow that teleportation. Will make something different and make it that you can bypass any plugin who would want to block teleportation and teleport player to target location. So next update /cmi tpohere and /cmi tpo will be available.
