### ISSUE TITLE
[Possibly BUG] Cannot spawn plural number of mobs

### ISSUE THREAD

**Issue by SteelsSystem** [Zrips/CMI#7165]
### Description of Issue

Can't spawn more than one mob while limit is being set to 100

### Version Information

```shell
[Fri 02:10:18 INFO ] --------------------------------------------------
  [Fri 02:10:18 INFO ] CMI: 9.2.3.5 SqLite
  [Fri 02:10:18 INFO ] CMILib: 1.2.3.3 
  [Fri 02:10:18 INFO ] Server: Purpur 1.19.2-R0.1-SNAPSHOT
  [Fri 02:10:18 INFO ] CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
  [Fri 02:10:18 INFO ] Modules -> 55 enabled 1 disabled: ranks
  [Fri 02:10:18 INFO ] --------------------------------------------------
```

### Errors

```shell
https://mclo.gs/9CKB6F4
```

### Relevant Config Sections

```yaml
Spawnmob limit is set to 100 although i can spawn only onbe mob
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
**/cmi spawnmob zombie q:100**
Will make some changes with next version to accept simplified format which you most likely used. **/cmi spawnmob zombie 100**

**Comment by SteelsSystem** [comment]
thanks for info i wouldn't figure this one
