### ISSUE TITLE
CMI ignoring permission nodes

### ISSUE THREAD

**Issue by Mrs-Feathers** [Zrips/CMI#7166]
### Description of Issue

All permission nodes seem to be ignored in the latest version of the cmi... players can /fly and /god even though they're not allowed to in the permission plugin and they're not OP which should mean they can't use it by default. even when putting the permission node to negate the permission for the command, users can still use the command. i've deopped myself and removed staff rank to verify this.. i can see people's enderchests and give myself money freely as if i had all permissions.

### Version Information

```shell
CMI 9.2.3.5 Bungeecord CMIB MySQL
CMILib: 1.2.3.3
Server Spigot 1.19.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
Modules -> 56 enabled 0 disabled:
```

### Errors

```shell
There are no errors that appear in the console for this issue.
```

### Relevant Config Sections

```yaml
I couldn't seem to find anything having to do with this issue in the configs. but i have checked for *.* in the configs among the most obvious of places to start. i've negated cmi.command.fly and cmi.command.god but they still work.

It seems to be CMI because luckperms seems to follow other plugins's permission nodes just fine.
```

### Relevant Plugins

LuckPerms v5.4.41

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
might check permission on a fresh testserver first?
also try it with clean lp,+cmi+cmilib  nothing else
You will see it should work ss aspected

**Comment by Mrs-Feathers** [comment]
i don't know if its my java which is version 18 or something but it didn't change. i'm still having the issue after running it alone. i'm looking into the server and digging through my luckperms database now.. luckly its small only 3 groups and 5 users.. but i'm still having this issue.. and i only noticed it after updating to the latest CMI. we don't have many plugins so i'm not sure what it could be. scouring the startup log, theres no error for this issue. all plugins we have, luckperms, CMI, CMILib, Lands, Slimefun, ReCount also by zRips, votifier and  Vault all work perfect aside from this issue.

**Comment by Mrs-Feathers** [comment]
i updated everything and the issue stopped. the OS, java, and all plugins. as of now i'm not able to say what was cuasing the issue and it seems maybe some of the other plugins' permissions could have been messed up too, but now work fine which means it could've been with how java was interpreting luckperms? probably not CMI's fault if so... but updating fixed everything.

**Comment by Mrs-Feathers** [comment]
happy to be able to fix it without having to redo anything.
