### ISSUE TITLE
Help! Plugin CMI

### ISSUE THREAD

**Issue by spikebam** [Zrips/CMI#7168]
Hello! How can I make sure that player messages from the local chat are not visible in the discord channel? I use the CMI plugin for the chat. P.S. I tried to add "!" to DiscordChatChannelPrefixRequiredToProcessMessage, but it doesn't help when I write !message, then the message is not duplicated from minecraft to discord, but when I write !!message, then a message with ! is duplicated from minecraft to discord, for example !message. P.S.S. I use the DiscordSRV plugin to write to the minecraft chat from discord and vice versa

**Comment by danyadanya2005** [comment]
I confirm. this is true. when is the fix?

**Comment by Zrips** [comment]
Should be resolved with next update. Only shout messages will appear in discord.
