### ISSUE TITLE
Add Custom recipes to fast recipes of Minecraft

### ISSUE THREAD

**Issue by OverBrave** [Zrips/CMI#7172]
![image](https://user-images.githubusercontent.com/47111280/185782393-3e43ae4c-1c27-480e-84a2-825bd2222164.png)
Custom recipes need to be added to this thing.

**Comment by Zrips** [comment]
When player crafts one item using custom recipe then this recipe will appear in recipe book automatically which can be used for quick crafting later on. This same thing applies to all recipes ingame, you need to craft it atleast once manually to have it there.

**Comment by OverBrave** [comment]
> When player crafts one item using custom recipe then this recipe will appear in recipe book automatically which can be used for quick crafting later on. This same thing applies to all recipes ingame, you need to craft it atleast once manually to have it there.

I just learned this, you can discover custom recipes with the game command. `/minecraft:recipe`

On the Bukkit side, we can discover these recipes with NamespacedKey. I just wanted to let someone else know if they view this thread.

For CMI:
```
key = new NamespacedKey(Bukkit.getPluginManager().getPlugin("CMILib"), "Recipe ID")
player.discoverRecipe(key)

```
