### ISSUE TITLE
CMI keeps freezing my server

### ISSUE THREAD

**Issue by DimaSergeew** [Zrips/CMI#7186]
### Description of Issue

CMI is constantly affecting my server. Because of which it can consume up to 45% of the ticks of my server in places. I don't know what the problem is, I have the latest version of this plugin

### Version Information

```shell
[12:12:35 INFO]: CMI plugin version: 9.2.3.6 BungeeCord SqLite
[12:12:35 INFO]: CMILib: 1.2.3.3
[12:12:35 INFO]: Server version: Mirai 1.19.2-R0.1-SNAPSHOT
[12:12:35 INFO]: CMI Economy: Enabled Vault Version: 1.7.3-CMICMI Chat: Disabled
[12:12:35 INFO]: Modules -> 55 enabled 1 disabled: votifier
```

### Errors

```shell
https://timin.gs/?id=9eaa3b3bcfdc4737ac5192cd19000f6a
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
What do you have set for world limits handling?

**Comment by DimaSergeew** [comment]
> What do you have set for world limits handling?

[config.zip](https://github.com/Zrips/CMI/files/9438005/config.zip)
My config

**Comment by DimaSergeew** [comment]
> What do you have set for world limits handling?

I've already tried everything. Install old versions. plugin. And restart the server. it still heavily loads my server. I can't understand why
![Screenshot_5](https://user-images.githubusercontent.com/75163645/187033199-a7b69f12-c797-4483-8749-0d70835bd3b3.png)
https://timin.gs/?id=66fc081951b14ba4bc868c4f7914fc7a

**Comment by DimaSergeew** [comment]
> What do you have set for world limits handling?
![Uploading Screenshot_2.png…]()

**Comment by DimaSergeew** [comment]
> What do you have set for world limits handling?

![Screenshot_2](https://user-images.githubusercontent.com/75163645/187035234-9b83bbe6-adfa-456f-991e-6236304647cf.png)
