### ISSUE TITLE
CMI can't detect of Resource pack sounds

### ISSUE THREAD

**Issue by OverBrave** [Zrips/CMI#7187]
### Description of Issue

![image](https://user-images.githubusercontent.com/47111280/187090694-0cb88f87-8b25-4416-9a11-055d7ab32384.png)
![image](https://user-images.githubusercontent.com/47111280/187090716-c1b500f4-e0ec-414b-a878-8657f28db197.png)

### Version Information

```shell
CMI: 9.2.3.6,
CMILib: 1.2.3.3
Server: petal 1.19.2-R0.1-SNAPSHOT
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
TabComplete list is being sent based on what server knows, while personal resource pack contents are not part of that information, so i'm not aware of a simple way to get this list from client which could be then included into this list.

**Comment by OverBrave** [comment]
> TabComplete list is being sent based on what server knows, while personal resource pack contents are not part of that information, so i'm not aware of a simple way to get this list from client which could be then included into this list.

What I wanted to show in the TabComplete section was that the command could not be executed. In other words, even if I typed the name of the sound, CMI could not detect it and could not play it. Couldn't at least a support be added for this?

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/187421923-e2eb3eea-964b-491b-9296-e845cddf2134.png)
