### ISSUE TITLE
convert sql server database to mysql online

### ISSUE THREAD

**Issue by 994AK** [Zrips/CMI#7195]
long-term use of sql database, I want to do web statistics,i need mysql！
I don't know, how to make him into mysql data.
this is important to me🥹

**Comment by mrfloris** [comment]
Migrate SQLite to MySQL db: https://faq.cmi.support/migrate

**Comment by Zrips** [comment]
@994AK Follow instructions provided by @mrfloris here. We have basic command as **/cmi migratedatabase** which provides quick conversion between database types when needed.
