### ISSUE TITLE
Cannot right click shop to edit signs

### ISSUE THREAD

**Issue by xpvtryanx** [Zrips/CMI#7196]
### Description of Issue

When trying to edit shop signs, I cannot right click and edit these signs. I am op and it still won't work. 

### Version Information

```shell
[13:01:10 INFO]: --------------------------------------------------
[13:01:10 INFO]: CMI: 9.2.3.7 SqLite
[13:01:10 INFO]: CMILib: 1.2.3.5 
[13:01:10 INFO]: Server: Paper(138) 1.19.2-R0.1-SNAPSHOT
[13:01:10 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[13:01:10 INFO]: Modules -> 55 enabled 1 disabled: headDrop
[13:01:10 INFO]: --------------------------------------------------
```

### Relevant Config Sections
```shell
Signs:
   # Defines in milliseconds how often to check if player entered Dynamic Sign trigger area
  # Bigger numbers can help slightly lower server load
  # This is not essential to keep in low numbers
  CheckInterval: 500
  # Defines list sign top lines which cant be edited with shift right click
  # Usually used for preventing shop sign modifications
  editBlackList: []

Optimizations:
  # When disabled we wont try to deop fake operator on server starup or unload while at same time disabling asFakeOp! specialized command usage
  UseFakeOperator: true
  # When this set to true any message sent to console will be strip out of any colors
  # In case you have mohochrome console, keep this at true
  MonochromeConsole: false
  # Time in seconds we want to give for playes who joins server a immortality state
  # Set this to 0 to disable
  # Max 60 seconds
  ImmortalityOnJoin: 3
  # Enables or disables maintenance mode
  Maintenance: false
  # Automatically kicks everyone from server when enabling maintenance mode who doesnt have cmi.command.maintenance.bypass permission node
  MaintenanceAutoKick: true
  # When enabled will show bossbar message informing about current maintenance mode being enabled
  MaintenanceBossBar: true
  # When this is set to true features like glow color, player collision, name plates will stop working and CMI will avoid doing anything related to player teams
  # Enable this if you are experiencing issue with other plugins which utilizes players teams for certain features
  DisableTeamManagement: false
  ArmorStands:
    # When set to true, plugin will check if player can manipulate armor stand by sending fake block place event and checking if any plugin would want to prevent this action
    # This can help out to minimize posibility for players to manipulate armor stands when they dont have build permission in area where armorstand is standing
    CheckBlockPlace: false
    Templates:
      # When set to true player will be required to have cmi.command.armorstand.template.[templatename] permission node to deploy saved template
      SpecificPermission: false
  AutoDownload:
    # In case you dont have GeoIP.dat it will be downloaded automatically on server start. Restart can be needed for it to take effect
    GeoIp: false
    # In case you dont have GeoLiteCity.dat it will be downloaded automatically on server start. Restart can be needed for it to take effect
    GeoLiteCity: false
  # When enabled you will see skull owner name in action bar when right clicking it
  ShowSkullOwner: true
  # When enabled you will see beeHive information in action bar when right clicking it
  ShowBeeHiveInformation: true
  # Sets indicator when creating elevator signs. Its case insensitive
  ElevatorIndicator: '[CMIElevator]'
  SignEdit:
    # Defines sign top line by which player will not be able to edit sign with /cmi se command
    BlackList: []
  # Defines elevator type. If this is used on second line of sing, then player will be teleported directly in front of it instead of keeping original players x and z coordinates
  ElevatorStaticIndicator: '[*]'
  # Used to show date in places like mail, checkban, infopage and similar locations
  LongDateFormat2: dd/MM/yy HH:mm:ss
  # Used to show date in places like inv gui and similar locations
  ShortDateFormat: dd/MM/yy
  # Do you want to record sell hand actions into file
  SellLog: true
  # When this set to true by using any command, requiring players name, in case plugin cant determine player by given full name, then partial matches from online players will be used. In example: /cmi heal rips can heal player Zrips 
  # Useful when you have players with complicated names
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
You need to provide relevant plugins name. Which shop plugin are you using?

**Comment by xpvtryanx** [comment]
> You need to provide relevant plugins name. Which shop plugin are you using?
ChestShop

https://www.spigotmc.org/resources/chestshop.51856/

**Comment by xpvtryanx** [comment]
```shell
AntiPopup
BetterRTP
BetterSleeping4
bStats
ChestShop
Chunky
CMI
CMILib
CoreProtect
CraftingStore
DiscordSRV
Factions (SaberFactions)
Graves
GriefPrevention
Jobs Reborn
LavaSponge
LiteBans
LuckPerms
mcMMO
Multiverse-Core
PicnicPlugin (made by us)
PL-Hide
PlaceholderAPI
PlayerParticles
ProtocolLib
SuperbVote
TAB
TabCompleteFilter
TabList
Vault
VaultChatFormatter
Votifier
VotingPlugin
WorldEdit
WorldGuard
```

**Comment by xpvtryanx** [comment]
Update, you can edit your own shop but you just cant edit admin or player shops. I am OP on this server.

**Comment by CloudeLecaw** [comment]
have you enabled the abillity to shift right click in /cmi options? 
in config a default options setting can be defined for all that cant use /cmi options  or never used it before.

**Comment by CloudeLecaw** [comment]
> Update, you can edit your own shop but you just cant edit admin or player shops. I am OP on this server.

op doesnt matter today anymore. an old relict of old times. today most is based on permission. op doesnt meant automaticly you got all permissions.  so check in you permissions plugin you also got the right permission.

**Comment by xpvtryanx** [comment]
> have you enabled the abillity to shift right click in /cmi options? in config a default options setting can be defined for all that cant use /cmi options or never used it before.

yes
![image](https://user-images.githubusercontent.com/36307438/189392430-fd0a7bfc-d223-47b2-80f1-0fdc283d8d68.png)
![image](https://user-images.githubusercontent.com/36307438/189393013-e2d10bde-2e32-48f4-b605-495ce1fa6f2a.png)
![image](https://user-images.githubusercontent.com/36307438/189393077-9c681987-bf4a-4623-bdb1-52e5ed743663.png)

I have all permissions. i have cmi.* and chestshop.admin as the admin permission nodes

I can do my signs and i can make any bodies sign. but i cannot edit specific players signs. so if CloudeLecaw or Zrips had a shop, I would not be able to edit theirs. Can't even do the admin sign

**Comment by CloudeLecaw** [comment]
then this is a rediction of ChestShop that protects aggainst this. you should check the chestshop config and also if chestshop might has a bypass.

**Comment by xpvtryanx** [comment]
> then this is a rediction of ChestShop that protects aggainst this. you should check the chestshop config and also if chestshop might has a bypass. from cmis side you just can check the Blacklist of sign edits you may made.
> 
> ```
>   SignEdit:
>     # Defines sign top line by which player will not be able to edit sign with /cmi se command
>     BlackList:
>     - '[Private]'
>     - '[More Users]'
>     - '[Everyone]'
>     - '[AdminShop]'
>     - '[ChestShop]'
>     - '[CMIElevator]'
> ```

what if I dont want it blacklisted. i did BlackList: [] 
That didn't change anything

**Comment by xpvtryanx** [comment]
![image](https://user-images.githubusercontent.com/36307438/189426980-2c6c473e-670b-405c-b5cb-062b74168882.png)
Fixed. it was this toggle.
