### ISSUE TITLE
Pagination broken in custom text

### ISSUE THREAD

**Issue by doitliketyler** [Zrips/CMI#7197]
### Description of Issue

Paging is not working as it should anymore. When a user hits "Next" it skips a page (So if I have 3 pages and I'm on the 1st page it takes me to the 3rd page, and if I click it again it takes me to the 2nd page). The text used to work fine and I'm not sure when it stopped working. I've also tested this with and without custom language file and the issue persists.

### Version Information

```shell
CMI: 9.2.3.7 BungeeCord CMIB  SqLite
CMILib: 1.2.3.5 
Server: Paper(111) 1.19.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled 
Modules -> 55 enabled 1 disabled: votifier
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by AbdulGhafoor01** [comment]
I am facing the same issue, It doesn't skip the page, It just consider next button as prev page, I have customtext with 10 pages and it go to previous page every time I click on <NextPage>. On the other hand if we use **/cmi ctext <file> <page>** it works fine but still we face same issue if click next button

**Comment by Zrips** [comment]
Will be fixed with next CMILib update
