### ISSUE TITLE
[feature request] near command

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#72]
Hej, I have another feature request. Coming from EssentialsX the near-command was a hidden but often used feature for staff member. The command allows one to receive a list of players that are near by (/near [radius]). The default radius was 200 blocks, but 50 blocks are more than enough in most cases. The command was very useful to „crowd control“ player during a event, you could always tell who and how many player want to participate. It was also very usefull to spot invisible or incredible curious player quickly. The command is maybe not one of those everybody want to use at the first glance but very useful for some purposes at the second. So I would love to use it again someday. Keep up your great work 😊

**Comment by Zrips** [comment]
Next update

**Comment by TheoRetisch1** [comment]
Awesome!
