### ISSUE TITLE
Pay command

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#720]
Since I'm used to essentials, I miss the pay command. There is no build in alias to enable.

**Request**: would be nice if a premade alias exists for all the players used to essentials.

So for now, I made my own custom alias:
`CustomAlias:
  pay:
  - cmi money pay $1-`

Now CMI starts with a warning:
`Duplicated alias found which could cause some strange behavior: pay`

I double checked but I can't find any duplicate. Why the warning?

**Comment by TheTopCz** [comment]
Yea i also started to get a warning Duplicated alias found which could cause some strange behavior: ...

**Comment by tmellen** [comment]
Check your alias.yml to see if "pay" is already an alias.

**Comment by TheTopCz** [comment]
Hmm, strange because I have only got / paytoggle there

**Comment by TheTopCz** [comment]
Hmm, strange because I have only  /paytoggle command in alias.yml

**Comment by x1p** [comment]
> Check your alias.yml to see if "pay" is already an alias.
Off course I checked the alias file, and there is no pay command. Otherwise I would not have to request to implement it as a default alias.

> **Request**: would be nice if a premade alias exists for all the players used to essentials.

**Comment by TheTopCz** [comment]
#725 duplicate....

**Comment by Zrips** [comment]
Warning could happen in case you performing /cmi reload. In general its informational warning message and should not impact plugin work. i did changed it to look more less threatening and i did added alias /pay to be by default there. 
If any alias are missing, make a github ticket with list of them like 
cmi pay-pay
and i can add them into default alias.yml file
