### ISSUE TITLE
/skin command not working on Bungee

### ISSUE THREAD

**Issue by rockit7** [Zrips/CMI#7205]
### Description of Issue

The /skin command does not work on network servers. I am not sure if this is intentional? But, we have always used velocity where it worked fine. Recently we updated to 1.19.2, and now it no longer works. The message received is "This feature will not work on bungee network based servers". I really don't want to have to look for a /skin plugin as this one has always worked perfectly. 

### Version Information

```shell
CMI 9.2.3.8
Purpur 1.19.2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Can you try the latest CMI version 9.2.4.x and latest CMILib and see if it still happens?

If so, please share the output of /ver and /cmi version - **in full**

**Comment by rockit7** [comment]
No change. Same error message after updating to latest version. "This feature will not work on bungee network based servers". 

![2022-09-15_22 10 45](https://user-images.githubusercontent.com/76574795/190509487-c8fb2eee-1ee5-4b11-b8df-6d739eb867d7.png)
![2022-09-15_22 02 20](https://user-images.githubusercontent.com/76574795/190509502-1f39eff6-1f6b-4c28-a7ae-ca775d5fa119.png)

**Comment by Zrips** [comment]
As stated in feedback message, this feature will not work on bungee network as it needs completely different handling. Not a bug.
