### ISSUE TITLE
Spawneggs vs Spawner interaction

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#721]
Situation:
Config:
`  Interact:
    # When set to true, players trying to change spawner with monster egg will require approrpiate permission node
    # In example: player should have cmi.egginteract.pig to change spawner into pig, or cmi.egginteract.zombie to change into zombie spawner
    EggRequiresPermission: true`

Problem:
when players want to use bought spawneggs, they need the permission node cmi.egginteract.[entitytype] which automatically give them the possibility to interact with spawners.

Request:
Give players the ability to spawn animal eggs, but not to interact with spawners.
Give staff the ability to change spawners into a couple of (predefined) types.

Suggestion:
Different permissions for interacting with spawners and a different setting to let players spawn animals with another permission or without any permission.

**Comment by Zrips** [comment]
This only controls interaction with spawners, player can still spawn mobs by clicking on ground. So confused with that request. For staff members, predefined types could be set by giving predefined permission nodes to them. So again, confused why you need something special for this one. If i'm missing something obvious here, slap me and call me Lucy...

**Comment by smartmadio** [comment]
@Zrips Player without cmi.egginteract.* permission can't use eggs with clicking on ground.

The console shows they are lack of cmi.egginteract.* permission.

**Comment by Zrips** [comment]
This was a bug which should be fixed with next build. Silly typo and forgot to place **!** in one place while doing 1.13 update.

**Comment by x1p** [comment]
Seems to work alright under 8.0.4.6

Thanks
