### ISSUE TITLE
Frog generator work according to your biome

### ISSUE THREAD

**Issue by Bardock31** [Zrips/CMI#7215]
Hi!

I would like to know if it would be possible to make frog spawners adapt to the respective biome.

The frog has a different color depending on the biome it is in, however, when creating a frog spawner it is only one color, orange, and does not spawn in any way in biomes that it should spawn, but in a different color. I would be very grateful if it is possible to do that!

(I apologize if something in my message was confused, I'm using the translator haha)

**Comment by mrfloris** [comment]
I think Mojang gives a default frog, because I believe it depends on the tadpole;
```
There are three frog variants, determined by the biome, in which the tadpole grew up
```

**Comment by Bardock31** [comment]
So would only these two types work for spawners?

**Comment by Zrips** [comment]
Its not really defined by internal block data and depends on where this spawner is looked at. So no real way to have those as separate specific spawners at this point.
