### ISSUE TITLE
helpop

### ISSUE THREAD

**Issue by rapofil** [Zrips/CMI#7216]
### Description of Issue

The player who writes the /helpop message sees both the feedback and the staffs message (other players not just him and the staffs). Correctly, only the staffs should see the staffs message and the player should only see the feedback.

The player does not have cmi.command.helpop.inform and the config is set to "feedbackMessage: true"

### Version Information

```shell
9.2.4.0
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Can you include the full output of 
```
/ver
/cmi version
```
instead of just a version number.

**Comment by rapofil** [comment]
![xxxxxxxx](https://user-images.githubusercontent.com/75930293/190575607-f17b2b95-6be8-43ad-ae39-03ef81cd7952.png)

**Comment by rapofil** [comment]
is that okay, or something else?

**Comment by Zrips** [comment]
Ok, should be fixed with next CMI update.
