### ISSUE TITLE
problems with cmi socialspy and cmi commandspy

### ISSUE THREAD

**Issue by pinuxio** [Zrips/CMI#7226]
Hi I'm using CMI9.2.3.7
but i noticed that cmi socialspy and cmi commandspy
they do not exist anymore
is there any remedy?

**Comment by Zrips** [comment]
Quite few commands got removed and their options went under one hood which is now /cmi options which still allows command based toggle or you can use provided UI. So to toggle those in particular you can simply use **/cmi options chatspy true** or **/cmi options cmdspy true**
