### ISSUE TITLE
Cmi vanishlistener Processing 

### ISSUE THREAD

**Issue by zino7** [Zrips/CMI#7227]
### Description of Issue

Hi, basically I run a timing in my server to check what is causing the server to be slow. I have checked and seen the vanishlistener is using a lot of resources than it should not. The timings report 
https://timings.aikar.co/dev/?id=6e158e1677044c8790e60f10bac478f6

### Version Information

```shell
https://gyazo.com/88e43dcdc38d22c55385c9d8ff661b82
```

### Agreements

- [X] My server is supported by CMI.
- [ ] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will add some optimizations for vanish login event, there have been some areas which could have been better optimized. If issue persists or if you will notice another area performing less efficiently let me know.
