### ISSUE TITLE
some ctext cant be found...?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7228]
### Description of Issue

When player tried to open some ctext by click on chat (added with cci customtext).. it results in cant find custom text with this name.
in our case may because the name of the ctext contains an ü or maybe because the name of the executer contains underscores in its name?

Console prints out:

When the player does **_/cmi ctext menü it_** it works fine too...

````
[13:13:50] [Server thread/INFO]: X_Der_BigMac_X issued server command: /cmil shadowcmd 1668680032i (cmi ctext menü X_Der_BigMac_X)
[13:13:50] [Server thread/INFO]: Cant find custom text by this name
````

here u seee menü,txt exists..
![Snag_9c74ba0](https://user-images.githubusercontent.com/12080017/190914756-0a0b7247-1558-4d1e-984c-f5c098f46151.png)

The issue seems to be new..it was working some cmi versions before

### Version Information
![Snag_9c8b1f7](https://user-images.githubusercontent.com/12080017/190914823-f38b5a2d-63fb-470f-a86b-47a8f64f307e.png)

### Errors
```
[13:13:50] [Server thread/INFO]: X_Der_BigMac_X issued server command: /cmil shadowcmd 1668680032i (cmi ctext menü X_Der_BigMac_X)
[13:13:50] [Server thread/INFO]: Cant find custom text by this name
```

### Relevant Config Sections
none

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
Edit: Ok it seem to realy has to be with the ü

`/cmi ctext menü` kannt be open anymore we need to typ
`/cmi ctext menÃ¼`

also this Ã¼ instad of ü is suggested in tab complete..

**Comment by mrfloris** [comment]
Unofficial answer, but, it might be possible that CMI requires a-z/Z-A/0-9 for filenames, to deal with spaces, unicode filtering, etc. 

I see you show it is possible in another plugin? Maybe that means CMI could perhaps update to support it for ctext, would be interesting for those international users. 

For now of course, a temporary fix is to use menu until it's possible.

**Comment by CloudeLecaw** [comment]
well 
it was working fine since long time with all ctext files we got

its a new now and only appears for the ctexts.... where the ctext fileas have the  ä ö ü

**Comment by CloudeLecaw** [comment]
> well it was working fine since long time with all ctext files we got
> 
> its a new now and only appears for the ctexts.... where the ctext fileas have the ä ö ü

Sometimes i think... you think we started using cmi one week ago
it was working fine since long time with all ctext files we got
aggain **it WAS working before like /cmi ctext menü  etc  and also in tabcomplete it was working fine!!!**

since a few versions updates the ctext command seems to no longer support the  ä ö ü when the ctext files contain these names. like menü.txt

**Comment by CloudeLecaw** [comment]
> Unofficial answer, but, it might be possible that CMI requires a-z/Z-A/0-9 for filenames, to deal with spaces, unicode filtering, etc.
> 
> I see you show it is possible in another plugin? Maybe that means CMI could perhaps update to support it for ctext, would be interesting for those international users.
> 
> For now of course, a temporary fix is to use menu until it's possible.

Sometimes i think... you think we started using cmi one week ago
it was working fine since long time with all ctext files we got
aggain **it WAS working before like /cmi ctext menü etc and also in tabcomplete it was working fine!!!**

since a few versions updates the ctext command seems to no longer support the ä ö ü when the ctext files contain these names. like menü.txt

**Comment by mrfloris** [comment]
Sorry, misunderstood what you wrote earlier, thank you for clarifying. 

Have you switch server engine jar? Startup params for the JVM changed? The OS had an update? 

I just tested on my macOS, and it seems to still work for me.

<img width="443" alt="Screen-Shot 2022-09-19 at 18 34 27" src="https://user-images.githubusercontent.com/28841349/191067815-44f0d2db-91d1-4e27-8f7a-4d7567a623e2.png">
<img width="405" alt="Screen-Shot 2022-09-19 at 18 34 31" src="https://user-images.githubusercontent.com/28841349/191067824-7f8de5a6-f57a-44ee-8247-40e2e44b405b.png">

**Comment by CloudeLecaw** [comment]
i downgraded to 9.2.3.0 to take a look
all fine there

![Snag_f30468f](https://user-images.githubusercontent.com/12080017/191067973-b2c79913-1484-4079-b5a5-d957ad7fdcca.png)

**Comment by mrfloris** [comment]
That is so strange. I don't know why it would be fine on my test system in the latest jar, but for you only on the older one. Interesting find.

**Comment by CloudeLecaw** [comment]
i will try to make some tests to see how far i need to go back in the version because the issue was reported from our users a week ago, but may i is in longer..

hm your right on my offline Testserver on my HDD it looks fine...
well there i use a Windows11 with Java 18.... may be a little difference to our live server...

**Comment by Zrips** [comment]
![image](https://user-images.githubusercontent.com/10416201/191234895-36e58669-3136-4d83-93d9-ce88bb07c884.png)
So its hard to say why it fails in your exact example, but everything seem to be working correctly with latest builds.
