### ISSUE TITLE
Error con /cmi dsign new

### ISSUE THREAD

**Issue by MechaYT** [Zrips/CMI#724]
**Description of issue or feature request:**

Esto sucede al colocar el comando /cmi dsign new

**ERROR (DELETE IF YOU HAVE NO ERROR):**

El error Qué arroja al colocar el comando es "An interna error occurred White attempting to perfora this command"

####################
####################

08.08 09:28:28 [Server] INFO Mecha_YT issued server command: /cmi dsign new
08.08 09:28:28 [Server] ERROR null
08.08 09:28:28 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.4.3
08.08 09:28:28 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
08.08 09:28:28 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
08.08 09:28:28 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
08.08 09:28:28 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
08.08 09:28:28 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
08.08 09:28:28 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
08.08 09:28:28 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
08.08 09:28:28 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
08.08 09:28:28 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
08.08 09:28:28 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
08.08 09:28:28 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
08.08 09:28:28 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
08.08 09:28:28 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
08.08 09:28:28 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
08.08 09:28:28 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
08.08 09:28:28 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
08.08 09:28:28 [Server] INFO Caused by: java.lang.ClassCastException: org.bukkit.material.Sign cannot be cast to org.bukkit.material.Dispenser
08.08 09:28:28 [Server] INFO at com.Zrips.CMI.Containers.CMIBlock.getFacing(CMIBlock.java:70) ~[?:?]
08.08 09:28:28 [Server] INFO at com.Zrips.CMI.Modules.DynamicSigns.CMISign.getArea(CMISign.java:96) ~[?:?]
08.08 09:28:28 [Server] INFO at com.Zrips.CMI.Modules.DynamicSigns.SignManager.addPlayersNearSign(SignManager.java:414) ~[?:?]
08.08 09:28:28 [Server] INFO at com.Zrips.CMI.Modules.DynamicSigns.SignManager.addSign(SignManager.java:81) ~[?:?]
08.08 09:28:28 [Server] INFO at com.Zrips.CMI.commands.list.dsign.perform(dsign.java:260) ~[?:?]
08.08 09:28:28 [Server] INFO at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222) ~[?:?]
08.08 09:28:28 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
08.08 09:28:28 [Server] INFO ... 15 more

**Cmi Version (using`/cmi version`):8.0.4.3

**Server Type (Spigot/Paperspigot/etc):Spigot 1.12.2-R1-SNAPSHOT

**Server Version (using `/ver`): This server is running Craftbukkit versión git-Spigot-4bd94dc-015bda4 (MC: 1.12.2) (Implementing API versión 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Should work correctly with latest builds.
