### ISSUE TITLE
[Request] Pay command

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/CMI#725]
Hello, it could be possible to add alias command /money pay (yes, it can be created using an aliaseditor)) but then transaction confirmation does not work .. :) thank you.

**Comment by tmellen** [comment]
Use an alias of "money pay $1-" that way it passes the rest of the command.

**Comment by Zrips** [comment]
Well i can add /pay if that helps out. Tho confirmation will still be processes in same way as it would be with custom alias.
