### ISSUE TITLE
Feature request - TopOffline for BalTop

### ISSUE THREAD

**Issue by BirminghamBoy** [Zrips/CMI#7250]
**Description of issue or feature request:**
Self-explanatory - love the TopOffline feature with /playtimetop, but would be really good to have this for baltop as well. :)

**Comment by CloudeLecaw** [comment]
well have you ever tried /cmi lastonline? ;)

This shows a last online one started with shortest time.
but if u show yourself the last pages u see the "top longest offline" ;)

**Comment by BirminghamBoy** [comment]
> well have you ever tried /cmi lastonline? ;)
> 
> This shows a last online one started with shortest time. but if u show yourself the last pages u see the "top longest offline" ;) To show the page look at the max page number and do `/cmi lastonline -p:XXX` (XXX is the number of your wished page)
> 
> Well it could take a while before you find the last page..
> 
> So a smarter soluion would be the adding of a **-r** argument as extansion for this command so it would be `/cmi lastonline (-r) (-p:XXX)` when -r is added then the last online list should simply start revered... means first place in the list would be the one that was longest time not online and on last page the last listed one would be the one with the shortest offline time.

Thanks for the response - I may not have been clear in my original post. What I'm wanting is to be able to exclude players who have been offline for a certain number of days from /baltop. Similar to the TopOffline variable that was recently added to config, just for /baltop instead of /playtimetop. :)

**Comment by mrfloris** [comment]
Balance top settings in config.yml already allows you to configure this. Because this new playtime top setting is a result of me asking zrips 'what we have in baltop, can we get that in playtimetop as well?'\

I even asked out community now if they're interested in us removing inactive players. 

<img width="652" alt="Screen-Shot 2022-09-25 at 16 59 57" src="https://user-images.githubusercontent.com/28841349/192150326-863f460f-b774-4425-8593-ff629389bce8.png">

config.yml
```yaml
# Time in days of a player being offline to exclude from being included in balance top list
ExcludeInactive: 0

**Comment by BirminghamBoy** [comment]
> Balance top settings in config.yml already allows you to configure this. Because this new playtime top setting is a result of me asking zrips 'what we have in baltop, can we get that in playtimetop as well?'\
> 
> I even asked out community now if they're interested in us removing inactive players.
> 
> <img alt="Screen-Shot 2022-09-25 at 16 59 57" width="652" src="https://user-images.githubusercontent.com/28841349/192150326-863f460f-b774-4425-8593-ff629389bce8.png">
> 
> config.yml
> 
> ```yaml
> # Time in days of a player being offline to exclude from being included in balance top list
> ExcludeInactive: 0
> ```

Thanks heaps! Didn't see that, oops.

**Comment by mrfloris** [comment]
Glad to hear that helped.
