### ISSUE TITLE
CMI cannot be loaded using spigot1.10

### ISSUE THREAD

**Issue by tdpclient** [Zrips/CMI#7253]
It does not support version 1.10, I used Spigot version 1.10 core and could not enable it regardless of loading detection, I even used Vault and CMIEInjector you sent, but still could not load...

**Comment by mrfloris** [comment]
The NBT class has a file for v1_10_R1, so make sure your server engine is that version, maybe 1.10.0 isn't supported but 1.10.2 is, for example https://api.papermc.io/v2/projects/paper/versions/1.10.2/builds/918/downloads/paper-1.10.2-918.jar
<img width="740" alt="Screen-Shot 2022-09-25 at 16 54 54" src="https://user-images.githubusercontent.com/28841349/192150122-c564d8ea-572b-4885-93d7-fea207855af8.png">

I did a quick test and it seems to run 1.10.2 paper on java 8 with latest cmi and cmilib, fine. 

If you have any specific issues with that, please be more specific.

**Comment by Zrips** [comment]
@tdpclient 
Outdated subversion are not supported and there is no reason to use one due to them having quite few bugs and issues. Use latest 1.10 server file, which should be atleast 1.10.2
