### ISSUE TITLE
Problem with plugin chat

### ISSUE THREAD

**Issue by Xylella** [Zrips/CMI#726]
**Description of issue or feature request:**
Hi, in our server we use a plugin named Feudal (link [here](https://www.spigotmc.org/resources/⭐-feudal-25-sale-⭐-kingdoms-gui-market-wars-professions-attributes.22873) ).
This plugin uses three types of chat (normal chat, chat between kingdom members and chat between allies) but since we installed CMI on our server only the normal chat is working. There are no errors and we don't have any clue on how to fix this problem.
Thank you for your time 

**Cmi Version (using`/cmi version`):** CMI 7.8.7.4

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** CraftBukkit version git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by mercurialmusic** [comment]
If you have another plugin running chat be sure you have "ModifyChatFormat: false" in the CMI config.yml. Two chat plugins will absolutely have conflicts. Note that this does not disable all CMI chat features and you can still modify nicknames, etc. as desired, but you do have to be careful in how you set them both up to make sure there isn't overlap.

**Comment by Xylella** [comment]
Thanks for the answer. The other plugin doesn't change the chat, it just adds two more chat channels (that aren't working even with ModifyChatFormat set to false). We use Cmi for chat formatting but for some reasons Feudal chat channels are not real channels, just normal chat.

**Comment by Xylella** [comment]
We found out that the problem is "ClickHoverMessages". If this is set to True the plugin's chats stop working, but if we set it to False the regular chat doesn't work.
