### ISSUE TITLE
Trigger check if multiple conditions not true

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7276]
I wanne to create a custom alias that trigger
when its
NOT NULL or NOT 1 or NOT 2 or  NOT 3

i tried some crazzy things like
`check:$1!=null|1|2|3! Do command  `

  like we know the OR from Regex.. its an |   but for specialzed commands i found no function for it

so my question how to trigger this?

**Comment by CloudeLecaw** [comment]
anymore any suggestion ?

**Comment by Zrips** [comment]
Some additional sub action for specialized commands will come out with next update. Its somewhat related to your question here, well atleast it will simplify alias commands which checks by multiple sub commands.
Additionally will add your suggestion to use | for separating different variable options.
