### ISSUE TITLE
Hologram Interaction Target is Above Holos

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#7281]
### Description of Issue

Had some issues with people complaining about clickable holograms not working and discovered that in order to get them to work we would have to click a couple lines above the holo for it to execute the commands. It hasn't been happening long, I believe since 9.2.4.3. This only happens with the "new method" enabled. The problem goes away if that is disabled.

### Version Information

```shell
CMI plugin version: 9.2.4.4 BungeeCord CMIB  SqLite
CMILib: 1.2.3.6 
Server: Paper(166) 1.19.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 55 enabled 2 disabled: ranks, skin
```

### Errors

```shell
No errors in console.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by NoltoxGit** [comment]
Helloww,

To add a detail about this bug, it does this only when the hologram is in a negative layer

**Comment by mercurialmusic** [comment]
Huh, yup. Didn't think of that, but all of the ones we were having issues with were below y=0.

**Comment by Zrips** [comment]
Will be fixed with next update
