### ISSUE TITLE
MSG BUG

### ISSUE THREAD

**Issue by uploadx10** [Zrips/CMI#7290]
### Description of Issue

When a player has a similar prefix, it will cause the system to respond to all that name. For example, a player named roll rollin roller rolling roll1 roll2 will see the same /msg message.

### Version Information

```shell
cmi 9.2.4.4
cmilib 1.2.3.6
```

### Errors

```shell
don't have
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Not really possible as message is being sent to only one player object, worst case it could have picked wrong recipient, but there is no real way for this message to be sent to more than one player unless there is another plugin interfering with that. Try testing this without any other plugin and CMI only. And i need to know your exact server version and type.

**Comment by Zrips** [comment]
Checking code can't see any part of the code which would send message to more than one recipient. Those who see messages, are they on same server as sender or different one?

**Comment by Zrips** [comment]
Should be fixed with next update, if issue repeats, let me know.
