### ISSUE TITLE
NoChatReports Issue

### ISSUE THREAD

**Issue by Envizar** [Zrips/CMI#7291]
### Description of Issue

![image](https://user-images.githubusercontent.com/87126318/195073311-d8499ab3-1a92-4ca1-bce8-7a2f7da07c65.png)

If I have working no chat reports plugin on server, HEX in messages doesen't work

Version:
![image](https://user-images.githubusercontent.com/87126318/195073430-8d9b9ee7-2df6-454c-836a-0713a877af01.png)

### Version Information

```shell
On screenshot
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
HEX color codes are being processed at different time, so this plugin NoChatReports takes unprocessed message and sends it to the players. Can't really do anything here. NoChatReports will need to add support for CMI, specifically support for CMILib and process hex color codes if there are any. This could be solved by simple setting CMI as softdepend in NoChatReports plugiun.yml file.
