### ISSUE TITLE
Bots saved

### ISSUE THREAD

**Issue by kiriles** [Zrips/CMI#7292]
### Description of Issue

So recently i've got bot attacks and they got saved into database and are now seen in /baltop even tho they never came into server and nothing was showed on console about them since its protected with an anti bot system

### Version Information

```shell
Version is latest plugin version always
```

### Errors

```shell
No errors only server crash even tho i have anti bot protection they somehow get saved into baltop without entering server
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update
