### ISSUE TITLE
Getting saveditems named when should be unnamed

### ISSUE THREAD

**Issue by ShiningIono** [Zrips/CMI#7297]
### Description of Issue

![2022-10-12_22 36 34](https://user-images.githubusercontent.com/115681408/195493624-da1090d2-0848-4e5b-acd3-857262938385.png)

When an item is saved but isn't named then spawned in using /cmi saveditems get, the spawned in item will have the actual name of the item itself as if it was named that way in an anvil.

### Version Information

```shell
CMI: 9.2.4.5 SqLite
CMILib: 1.2.3.6
Server: Paper(388) 1.18.2-R0.1-SNAPSHOT
CMI economy: Enabled CMI Chat: Enabled
Modules -> 57 enabled
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
