### ISSUE TITLE
The problem of the scan feature

### ISSUE THREAD

**Issue by mikesonchan** [Zrips/CMI#730]
The scan feature is able to scan the specific items I want. But it didn't remove all of them when I added the variable "purge".

**Cmi Version (using`/cmi version`):** 8.0.4.3

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.11.2

**Comment by Zrips** [comment]
Did you enabled purge in config file? as this is requirement to prevent some possible server destroying actions by staff members who has access to this command.
