### ISSUE TITLE
Double Bossbar

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#7324]
### Description of Issue

This has been going on for a while.
When joining in vanish, I sometimes see double bossbars telling me I'm in vanish. I don't why this is happening and I can't really reproduce it as it's quite random. Sometimes it's fine, sometimes it's double. it's pretty random.
![Screenshot-2022-10-24 163157](https://user-images.githubusercontent.com/28690790/197552139-57470a36-2dcf-4252-9ac0-282c0669761a.png)
It disappears when you switch /vanish 4 times.

### Version Information

```shell
CMI: 9.2.4.7 SqLite-> 9.2.4.8
CMILib: 1.2.3.7
Server: Purpur 1.19.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled
Modules -> 56 enabled 1 disabled: votifier
```

### Errors

```shell
None
```

### Relevant Config Sections

```yaml
Vanish:
  Defaults:
    ...
    bossbar: true
    joinVanished: true
```

### Relevant Plugins

CMI-9.2.4.7 CMILib-1.2.3.7

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Might have general idea what going on, even tho can't really reproduce this issue, as its really random one. Will make some changes with next build and if issue persists, let me know.
