### ISSUE TITLE
Can I put CMI plugin into my server and publish it?

### ISSUE THREAD

**Issue by 1233Ao** [Zrips/CMI#7331]

**Comment by CloudeLecaw** [comment]
why you thought your allowed to share the plugin with others?

your allowed to share the spogot link to cmis site to inforn or tell others about cmi.
your not allowed to share your jar file with other people if thy wanne use cmi on their own server. renember you just bought one license.
if its your server or your the admin of the server, or have other ways of file access to it, then your allowd to use your plugin on this server, as long as its still yours or as long your part of the server team. it still menas your jar is not allowed to be used on more then one server at once. (exept you use it on a bungee servet and want to use cmi on each bungee part of it  or if your using it onnyour local hdd for testings.
if you leave the server team on day and the owner desnt have bought cmi, then you need to remove it.
if the owner would decide to stay with your cmi and license, then you would need to buy a new one. so allways thing about in who you want to trust in to use your cmi and license together.

**Comment by 1233Ao** [comment]
I forgot that this plugin is paid, sorry
