### ISSUE TITLE
CMI Economy & Faction

### ISSUE THREAD

**Issue by Darkseno** [Zrips/CMI#7342]
### Description of Issue

Hello,

I have a problem with FactionUUID, when a player creates a faction CMI considers that the faction is also a player and therefore it gives the amount of money for a new player.

Except that it's a problem because a player has just created and deleted a faction repeatedly to make money.

How to fix the problem, I already saw with the support of FactionUUID they told me that the problem came from CMI

### Version Information

```shell
https://ibb.co/VwT3Pk8
```

### Errors

```shell
No errors
```

### Relevant Config Sections

```yaml
https://pastebin.com/P8V9zzpw
```

### Relevant Plugins

Purpur1.19.2 1833  |  Vault 1.7.3-C.M.I  |  FactionsUUID 1.6.9.5-U0.6.19-b304

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Darkseno** [comment]
UP ?

**Comment by mrfloris** [comment]
<img width="717" alt="Screen-Shot 2022-11-18 at 15 44 05" src="https://user-images.githubusercontent.com/28841349/202731001-090604c9-e5c0-4f49-aa1d-4f924f903c0c.png">


Can you type this in console and share the full results?

```
cmi version
ver FactionUUID
ver 
```

**Comment by Zrips** [comment]
@Darkseno 
Can you provide factions config file? If you don't want to share it here in a public area you can send it to Zrips#9691 over discord

**Comment by Zrips** [comment]
Should be fixed with next release.

**Comment by Darkseno** [comment]
https://ibb.co/MVsCVSL
