### ISSUE TITLE
Broken commands blocked by others plugins - /spawn, /home <home>, /anvil, etc.

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#7343]
### Description of Issue

Hello, some commands seem to be broken when blocked by other plugins.

I've already tried to block command like /spawn, /home <home>, /anvil, /ec, /craft, /repair, /top, etc...  **BLOCKING DO NOT WORK, confirmed for those commands**

BUT some of them work.. like single /home, /homes, /tpa, /tpaccept, and others... **WORK for those commands**

I've tried to block these commands in ChatControlRed, RandomEvents (this plugin should block all commands in events BUT mentioned commands above cannot be blocked from some reason even when all others are... and I've only set whitelist for few commands NOT these, and they're still allowed.... same for chatcontrolred. **So it seems that CMI overrides other plugin events for some mentioned commands**

Can it be due to command warmup / cooldown or something? But it seems to be issue of really just some commands like I've mentioned above, and commands special from the CMI, like /top, /repair, /craft.. I don't have another plugin with those cmds.

### Version Information

```shell
30.10 16:59:04 [Server] INFO --------------------------------------------------
30.10 16:59:04 [Server] INFO CMI: 9.2.4.7 MySQL-> 9.2.5.1
30.10 16:59:04 [Server] INFO CMILib: 1.2.3.7 
30.10 16:59:04 [Server] INFO Server: Purpur 1.19.2-R0.1-SNAPSHOT
30.10 16:59:04 [Server] INFO CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
30.10 16:59:04 [Server] INFO Modules -> 45 enabled 12 disabled: deathMessages, disabledEnchants, customMessages, mirror, tablist, ranks, firstJoinMessages, playerCombat, votifier, skin, namePlates, playerChatTag
30.10 16:59:04 [Server] INFO --------------------------------------------------

BUT I have new jar in the
```

### Relevant Plugins

ChatControlRed (latest), RandomEvents, and I believe other plugins that should whitelist only some commands when needed

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
You can have 5 plugins all try to have a "/command", but only 1 will be successful upon registration. Hence the conflicts that causes.

In CMI you can have /command instead of /cmi command, this is toggled via alias.yml

If you want "plugin-a" to use /command, and not use the /cmi command version of it, negate the cmi permission node of this cmi command, and in alias.yml set enabled: true to false, and then /stop and start the server, plugin-a can then properly register /command and use it.

**Comment by Zrips** [comment]
@bobhenl 
Having multiple plugins which handle same commands will cause issues. While CMI can dynamically change accepted commands, other plugins would still try to override this behavior with their own. You will need to limit plugin usage which utilizes same commands.
