### ISSUE TITLE
Block Command

### ISSUE THREAD

**Issue by BisognaAvereFede** [Zrips/CMI#7344]
Add a clickable command in a block in with specific coordinates.

**Example:** 
```
Block CMD:
  material: stone
  position: (x); (y); (z); (world)
  command: /fly
  
```

**Comment by T14D3** [comment]
That just sounds like InteractiveCommands with extra steps

**Comment by CloudeLecaw** [comment]
you can do this allready.
create an ic and attach it to a block and then
make your fly command.

**Comment by mrfloris** [comment]
You can achieve this using CMI's IC feature; more info here: https://www.zrips.net/cmi/commands/interactive-commands/
