### ISSUE TITLE
Specialized commands "check:==! is completely broken

### ISSUE THREAD

**Issue by T14D3** [Zrips/CMI#7349]
### Description of Issue

Kindof hard to explain, but for example doing "check:$1==test! msg! [playerName] TEST" will print TEST to the  executing player when executed without any arguments
As long as any argument is given it works as intended, but if there is no argument given, all checks return true
![Screenshot_422](https://user-images.githubusercontent.com/73843330/199592866-b10f1f08-ea44-4afa-8ca1-e94e237684c3.png)

I've done some more testing and more screenshots (and Floris too), but they all come down to the same idea

### Version Information

```shell
CMI Plugin Version 9.2.5.1 sqlite
CMILib 1.2.3.7
Server Pufferfish 1.19.2
```

### Errors

```shell
None
```

### Relevant Config Sections

```yaml
None
```

### Relevant Plugins

None

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
I've done some tests as well, can reproduce. It seems less of an issue with `!=` and it goes wrong in if statement as well. Haven't checked other SC yet, but it certainly affects check:

**Comment by mrfloris** [comment]
<img width="845" alt="Screen-Shot 2022-11-03 at 11 58 24" src="https://user-images.githubusercontent.com/28841349/199703948-2b0cbf58-28ff-47a0-aaf7-4546115e5ca3.png">

**Comment by Zrips** [comment]
Will be fixed with todays update
