### ISSUE TITLE
customrecipes and spawn eggs

### ISSUE THREAD

**Issue by GothkittyGirl** [Zrips/CMI#735]
**Description of issue or feature request:**

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**Cmi Version (using`/cmi version`): 8.0.4.6** 

**Server Type (Spigot/Paperspigot/etc): spigot** 

**Server Version (using `/ver`): git-spigot-417cfb3-50e6858 (mc: 1.13) (implementing api version 1.13-r0.1-snapshot**

**Comment by GothkittyGirl** [comment]
anyone? customrecipes with spawn eggs work first go then change to pig eggs when server restarts

**Comment by MCTyler** [comment]
Well at least finally you described your issue...No. Works fine for me.

**Comment by Zrips** [comment]
Should work correctly with latest build
