### ISSUE TITLE
Bug With Undcuff

### ISSUE THREAD

**Issue by rageyh** [Zrips/CMI#7351]
### Description of Issue

The /undcuff command completer tab is buggy

https://prnt.sc/KgV51JsQWklR

### Version Information

```shell
9.2.5.2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Fixed
