### ISSUE TITLE
Dicscord Chat Problem with ClickHoverMessages

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#736]
I found out if you set ClickHoverMessages to true you can not send discord messages to discord.

If you put ClickHoverMessages back on false everything will work again. Please fix. We needed

Thanks

**Comment by arturek1666** [comment]
That's not all if you you have ClickHoverMessages to false to allow the discord chat to work te [item] no longer works xD

**Comment by cdmvirt** [comment]
yes this is an issue... plus it takes the CHAT format from CMI and not my chatplugin Chatcontrol

**Comment by TheWranger** [comment]
https://github.com/Zrips/CMI/issues/391
this has been reported several times.
