### ISSUE TITLE
BUG: Rankup command generating invalid uuids in luckperms also in ultraperms

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#737]
**Description of issue or feature request:**

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```Using cmi rankup with luckperms 'tracks' generats wrong and invalid uuids. The command works, but is usless for promoting players via the lp track system with the rankup command. I use the track system for players to get their first rank ingame after verifing. I even tested the rankup command using ultraperms with the same results. Wrong / invalid uuids.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Branch2:
  Enabled: true
  DisplayName: "&2Verified"
  AutoRankup: false
  RankupConfirmation: false
  MoneyCost: 
  NextRanks:
  Commands:
  - "lp user %player_uuid% promote advance" 
  - "broadcast! &6[playerDisplayName] &eHas Verified!"
  - "cmi kit Verifier [playerName]"

**Cmi Version (using`/cmi version`):** 8.0.4.6

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** Spigot 1.13-R0.1-SNAPSHOT

**Comment by splops** [comment]
In commads try using [playerName] instead of  %player_uuid%  and report back :)

**Comment by CypherPhyre** [comment]
Using [playerName] seems to work correctly. That command line was a copy/paste from my old 1.12.2 config to the 1.13 config. It worked as %player_uuid% in 1.12.2 but generated wrong/invalid uuids in 1.13.
