### ISSUE TITLE
Issue with Tablist design when gradiant is ueses

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7373]
### Description of Issue

When we use the gradiant rainbow style an interesting isse happens

here is the format i tried
```
      Header:
        '1':
        - '{#994d4d>}•&l&m            {#333e66<>}&l&m            •{#994d4d<}'
```
 normaly this should look like ONE line but the &l/m after the `{#333e66<>}`  added a little extra line...
![Snag_1f03720](https://user-images.githubusercontent.com/12080017/201446373-ee1fb11c-b574-4628-bb04-a4473e924f12.png)

When i change the header and remove the secound &l&m to
```
      Header:
        '1':
        - '{#994d4d>}•&l&m            {#333e66<>}            •{#994d4d<}'
```
then the secound little scripe disapears but then the scripe is mssing for the rest..
![Snag_1feedf9](https://user-images.githubusercontent.com/12080017/201447216-9920b41b-ef9e-45eb-b6c8-c02ecfafea13.png)

So i aspect the issue comes because of a secound used &l&m in the gradiant bow..
```
      Header:
        '1':
        - '{#994d4d>}•&l&m            {#333e66<}{#333e66<}&l&m            •{#994d4d<}'
```
i also made a little try with two little bows but with same result.. after te secound &l&m was added
![Snag_2024060](https://user-images.githubusercontent.com/12080017/201447412-741eaa9c-bea8-4e83-b2de-297ee7040742.png)

Now i tied a bit different design of the header line..
```
      Header:
        '1':
        - '{#994d4d>}&l&m╔═══════════════{#333e66<>}&l&m═════════════╕{#994d4d<}'
```
The result is interestin.. you see the little extra stripe is also in the secounds line..
so i aspect this is bug.
![Snag_20803c7](https://user-images.githubusercontent.com/12080017/201447761-7109af83-ef4d-4794-af94-66314a0ea8b6.png)

### Version Information

![Snag_1f0f3ba](https://user-images.githubusercontent.com/12080017/201446417-11b16c20-8fc7-4262-8d54-5e654e9f7eb7.png)

### Errors
![Snag_1f3a462](https://user-images.githubusercontent.com/12080017/201446565-8191409f-380a-4049-a738-195ec6c93c9f.png)

### Relevant Sections in tablist.yml - header, footer

```
      Header:
        '1':
        - '{#994d4d>}•&l&m           {#333e66<>}&l&m            •{#994d4d<}'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
Edit i found an interesting solution but it still is a bug i think..
using &r at the end of line removed the extra strip..

```
      Header:
        '1':
        - '{#994d4d>}&l&m╔═══════════════{#333e66<>}&l&m═════════════╕{#994d4d<}&r'
```

![Snag_20a233c](https://user-images.githubusercontent.com/12080017/201447883-5f770649-32fe-4d76-b720-5daf0b1185c5.png)

**Comment by Zrips** [comment]
From what I have tested, this is most likely due to the fact that you have second line set as empty one and it inherits previous format as its not being reset if you never set any color for following lines. Will make some changes to address this, relating to empty lines. Colors will still be inherited down the line if you never set it for other lines, just to keep previous behavior, but we wont be including that space character which was adding text format from previous section.
