### ISSUE TITLE
CMI DROPSPAWNER

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [Zrips/CMI#7395]
### Description of Issue

Hello,
for A-team members, we have cmi.dropspawner permissions enabled. Spawners have always been able to be dug up and have not been a problem.

However, there is a problem with the players. There is a chance mostly around 1:100 when a player digs up a spawner even if he doesn't have the permission. It happens rarely, but I don't know how it could be fixed. So I want to ask you, can you look into this problem? Is there any way to fix it?
Thank you very much 

/cmi haspermission:
[AT]: Sh3r1ffCZ -> cmi.dropspawner
[18:57:25 INFO]: Set by plugin.yml to TRUE

[Player]: Thom19as -> cmi.dropspawner
[18:57:33 INFO]: Hard set to FALSE by some plugin

### Version Information

```shell
CMI-9.2.5.4
CMILib1.2.3.7
Purpur 1.19.2-R0.1-SNAPSHOT
LuckPerms v5.4.40.
Modules -> 46 enabled 11 disabled: spawnerProximity, flightCharge, disabledEnchants, mirror, tablist, skin, noTarget, elytraBoost, spawnerCharge, paintingEditor, playerChatTag
```

### Relevant Config Sections

```yaml
Break:
    Enabled: true
    RequiresExactPermission: false
    DropExp: true
    SilkTouchLevel: 0
    BaseDropChance: 100
```

### Relevant Plugins

Vault 1.7:3-b131

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Hopefully this should be resolved with next update. As this isint the one which can be easily debuged by reproducing issue, will have to more or less shoot in a dark to guess what's going on in those rare situations. If issue persists after next update, please let me know
