### ISSUE TITLE
Flight Charge Max Storage

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#74]
If I change the max storage of flightcharge from 1000 to 2000. When I do /flightcharge expcharge 2000, it says I added 1000. I can continue to do this without using any flight time and still get charged without it ever stopping as being "full". When I go to fly, it shows I only have 1000 of 2000 charged.

EDIT: I noticed that it will say (+1400) in the bossbar when you do the command above if you have around 600 in charge, but, the command line message updated 1000.

I also noticed that when I logged out and logged back in to fly, that I started out with around 1000 again, even after being much lower than that before disconnecting. I suspect it might be storing the extra charge, but now communicating it correctly to the player.

**Comment by digitalcrowd** [comment]
I think might be resolved in latest release as I guess I was a day or two behind. I'll check against another player account that I was doing the testing with.

**Comment by Zrips** [comment]
Should be fixed with next build
