### ISSUE TITLE
gradient doesn't work in chat

### ISSUE THREAD

**Issue by VINRED5** [Zrips/CMI#7402]
### Description of Issue

Starting from version 9.2.5.3. the gradient in the chat does not work
![2022-11-27_11 01 26](https://user-images.githubusercontent.com/74217586/204123446-566d7f34-1507-4242-95a1-c35fbcab848f.png)
I send {#e6000e>}Test{#4900e6<}

### Version Information

```shell
9.2.5.5
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [ ] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
