### ISSUE TITLE
Potential dupe bug with /ec (other)

### ISSUE THREAD

**Issue by therealatsuga** [Zrips/CMI#7403]
### Description of Issue

If a player opens the enderchest of another player before leaving the server, this (other) enderchest is loaded for him when he joins the server the next time. 

There is no error showing up in console. 

This mechanic can be used for duping items... 

We solved it temporarly by removing the cmi.command.ender.others from the player ranks. 

### Version Information

```shell
CMI Lib: 1.2.3.7
CMI: 9.2.5.5 CMI Bungee
It is a purpur server, 1.19.2, latest version
```

### Errors

```shell
No errors
```

### Relevant Config Sections

```yaml
None
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will make some adjustments with next version, is issue persists, let me know.
