### ISSUE TITLE
Freeze Effect only one Second

### ISSUE THREAD

**Issue by iCrafterCode** [Zrips/CMI#7404]
### Description of Issue

The freeze effect remains only a few seconds no matter if you specify 60 seconds or 190 seconds it does not remain.

### Version Information

```shell
CMI: 9.2.5.5
CMILib: 1.2.3.7
Server: Paper(298) 1.19.2-R0.1-SNAPSHOT
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
