### ISSUE TITLE
Random teleport problem

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/CMI#741]
Hello, I use the /cmi rt command for random teleportation but I have the problem we happen to command the player porting the player to the bottom of the ocean, please fix or add the settings ... thank you :) (I tried to increase the range but did not help it ...)

CMI 8.0.4.6
Spigot 1.13-R0.1-SNAPSHOT
Vault 1.6.10(+)

**Comment by x1p** [comment]
I can't even teleport random at all. I only get the message, that a location could not be found.
I removed all blocked biomes. These biomes are written with spaces and in the bukkit biome list, its 1 word. So I expect it would be this, but I'm not sure anymore since none seems to work.

**Comment by 0xC1A551C** [comment]
my rt is working completely fine. check the settings in your config

**Comment by x1p** [comment]
@TheTopCz Have you tried adding all possible biomes you don't want players to teleport to? There are a lot of biomes in 1.13 ;-)

**Comment by TheTopCz** [comment]
Thank you for the answer, I've already solved it!
