### ISSUE TITLE
The auto totem function does not work

### ISSUE THREAD

**Issue by Vector7979** [Zrips/CMI#7417]
### Description of Issue

The CMI has a function that allows you not to hold the totem in your hand, but it will be triggered from the inventory. But for some reason, when this feature is enabled, the skills in MythicMobs when they kill you, the totem is spent but does not save you and you die.

### Version Information

```shell
CMI version 9.2.5.6
```

### Relevant Plugins

MythicMobs-5.2.1-#4334

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Vector7979** [comment]
If you put the totem in the second hand and turn on the auto totem function in CMI, then you will spend 2 totems, one from the hand and the other from the inventory, but if you hold the totem in the main hand, it will not work

**Comment by Zrips** [comment]
I need your config section relating to totems

**Comment by Vector7979** [comment]
Totem:
  # When this set to true, on players death totem will be used even if he is not holding it in hand
  RemoveFromInventory: true
  Cooldown:
    # When this set to true player can use totem only every X second's
    Use: false
    Time: 600
  Warmup:
    # When this set to true player can use totem to have X amount of second's, during which he can die and be resurected
    # Totem will be consumed durring activation and wont be returned even if resurection is not used during warmup time
    Use: false
    Time: 10
  # If player falls into void while having totem, he will be teleported to respawn location and totem gets consumed
  ProtectFromVoid: true
  Effects:
    # Time in seconds effect needs to be applied to the player. Set it to 0 if you want to disable it
    Regeneration: 8
    FireResistance: 8
    Absorbtion: 8
 Here you go, I tried clean files by changing only "RemoveFromInventory" then there was still a problem
