### ISSUE TITLE
RandomTeleport didn't find multiverse-core worlds

### ISSUE THREAD

**Issue by DoZysGuy** [Zrips/CMI#7418]
### Description of Issue

I create two worlds with multiverse-core but cmi randomtp didn't detect them. I try to add them manualy on config.yml but it's not working too.

I use the last version of multiverse-core with paper 1.19.2 and Cmi 9.2.5.6.

![image](https://user-images.githubusercontent.com/119410319/205261876-f5797e94-7c9c-4162-a3c6-9894ff077af4.png)

### Version Information

```shell
Cmi 9.2.5.6
CMILib 1.2.3.7
Paper 1.19.2-R0.1-SNAPSHOT
Vault 1.7.3-CMI
```

### Relevant Plugins

Vault 1.7.3-CMI, CyberWorldReset-0.6.1

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Any error messages during startup? As it should report about missing randomtp worlds if world wasn't detected. And do you have AutoGenerateWorlds enabled for random teleportations in config file?

**Comment by DoZysGuy** [comment]
I tried both AutoGenerateWorlds and Manualy. With AutoGenerateWorlds there is no error on startup or reload and when I tried manualy, I set "minecraft:nether" and "nether" after and when I reload it say that world isn't recognized.
