### ISSUE TITLE
doubt economy

### ISSUE THREAD

**Issue by Sakanas** [Zrips/CMI#742]
Is there any possibility of separating the economy by world?

**Comment by mercurialmusic** [comment]
MultiWorldMoney (https://www.spigotmc.org/resources/multi-world-money.6231/) works with CMI's Economy (tested that it's also still working in 1.13), but there are some limitations. It's not a true multi-world economy and things like player shops act strangely when crossing worlds, but it works well enough if there isn't much risk of economic crossover.
