### ISSUE TITLE
CMI Scavenge

### ISSUE THREAD

**Issue by AlternativeSoap** [Zrips/CMI#7425]
### Description of Issue

![Udklip](https://user-images.githubusercontent.com/86206216/205755726-56a9689a-0b40-44bf-a9b9-a0bfa7e01759.PNG)
![2022-12-05_23 24 30](https://user-images.githubusercontent.com/86206216/205755898-3fc99942-f7cd-4248-9298-fde29fe44781.png)

Shouldn't it show that it gives 100% ingredients on 100% in the config?

### Version Information

```shell
CMI: 9.2.6.1
CMILib: 1.2.3.7
```

### Errors

```shell
No errors
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Good point... Will issue a fix with next version
