### ISSUE TITLE
Enderchest duping with /enderchest (other) after disconnect.

### ISSUE THREAD

**Issue by Skizzles** [Zrips/CMI#7426]
### Description of Issue

When using /enderchest (username) and you disconnect it replaces ur enderchest with theirs. Causing items to be lost and duplicated.

https://screenshots.skizzles.me/wAnA3/feYeqErI36.mp4

This goes along with #7403

### Version Information

```shell
CMI 9.2.6.1
Purpur 1.19.2 1856
```

### Errors

```shell
N/A
```

### Relevant Config Sections

```yaml
N/A
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Skizzles** [comment]
@Zrips a pretty major dupe / item loss issue.

**Comment by CloudeLecaw** [comment]
just cab tell you it does nit happen to vanilla cliebts with paper 1.19.2. (include your mainworld so you got access to your player files)

test it with a copy of your server offline and just cmi +cmilib (and may the permission plugin)  you will see the issue will not apear.

**Comment by Zrips** [comment]
@Skizzles 
That expanded ender chest isint part of CMI. What plugin are you using for it? And if you have custom ender chest plugin which expands inventory, you might want to stick with it only as in normal conditions ender chest is hard limited to its size and trying to mix multiple plugins which manage ender chest will cause issues.
And recent updates dint really touched ender chest handling, there was only changes in regular inventory editing handling

**Comment by Ste3et** [comment]
The Same error has been happend on my paper 1.19.2#307 Server with cmi 9.2.6.1 please Take a Look into it @Zrips 
That issue has been happend to all my supporteres These have been happend 8 Times before i revoke the perms for /ec for another Players.

**Comment by Ste3et** [comment]
https://www.youtube.com/watch?v=TUrdXEXlVB8&ab_channel=Dicecraft

**Comment by Zrips** [comment]
Will do more investigation

**Comment by CloudeLecaw** [comment]
have you tried this without viaversion and viabackwards ?...just for testing ...

**Comment by Ste3et** [comment]
After a long time i figured it out @Skizzles did you use that plugin: https://www.spigotmc.org/resources/shop-the-intuitive-shop-plugin.9628/ the plugin support enderchest shops and that is the reason for me.

**Comment by Skizzles** [comment]
> After a long time i figured it out @Skizzles did you use that plugin: https://www.spigotmc.org/resources/shop-the-intuitive-shop-plugin.9628/ the plugin support enderchest shops and that is the reason for me.
> And that is the reason for the duplication.

Okay first off you are an actual God for giving possible solutions ❤️

I do use that plugin so I will check it out, I assume you just updated it?

**Comment by CloudeLecaw** [comment]
@Skizzles might this plugin still contains this issue?

for next time. before letting us string and cook our brains... please try anything you feel like an issue with a clean install first.
what clean means:
- server + cmi + cmilib + permission (and may + vault and cmieinjector if its an economy issues)
- no other plugins

if the issues still accour it might be cmi
if not add your plugins little by little untill your issue starts to happen.

**Comment by Ste3et** [comment]
https://github.com/snowgears/shopbugs/issues/374 i thing these issue #7426 can be closed.

**Comment by Skizzles** [comment]
> @Skizzles might this plugin still contains this issue?
> 
> for next time. before letting us string and cook our brains... please try anything you feel like an issue with a clean install on a testservet first.
> what clean means:
> - server + cmi + cmilib + permission (and may + vault and cmieinjector if its an economy issues)
> - no other plugins
> 
> if the issues still accour it might be cmi
> if not add your plugins little by little untill your issue starts to happen.

I already did a lot of testing, thanks for assuming. I literally made an entire development server copy and had no issue so that left production environment. Can't just shut down a production environment at any given time. Clean installing is also absolutely bonkers when a plugin has thousands of options, this is clearly a weird incompatibility between cmi and the shop plugin which is possibly fixed with the shop update.

There is a reason I didn't respond to your comments, mostly because you state irrelevant things majority of the time.

**Comment by Skizzles** [comment]
Closing and will reopen if still an issue.

**Comment by CloudeLecaw** [comment]
> > @Skizzles might this plugin still contains this issue?
> > for next time. before letting us string and cook our brains... please try anything you feel like an issue with a clean install on a testservet first.
> > what clean means:
> > 
> > * server + cmi + cmilib + permission (and may + vault and cmieinjector if its an economy issues)
> > * no other plugins
> > 
> > if the issues still accour it might be cmi
> > if not add your plugins little by little untill your issue starts to happen.
> 
> I already did a lot of testing, thanks for assuming. I literally made an entire development server copy and had no issue so that left production environment. Can't just shut down a production environment at any given time. Clean installing is also absolutely bonkers when a plugin has thousands of options, this is clearly a weird incompatibility between cmi and the shop plugin which is possibly fixed with the shop update.
> 
> There is a reason I didn't respond to your comments, mostly because you state irrelevant things majority of the time.

you got it. testing takes time ;)
and no its not irrelevant to do testings. and no a testserver is usually a offline cooy of your server. never do these testings on the production server.
