### ISSUE TITLE
death messages not taking into account vanish state

### ISSUE THREAD

**Issue by Bibithom** [Zrips/CMI#7427]
### Description of Issue

When i'm vanish and death by accident (for example losing fly and dying in void), a death message is forwarded on server.

I think, death messages should not be send for vanished players.

### Version Information

```shell
cmi : 9.2.6.1 MySQL
CMIlib: 1.2.3.7
CMI economy enabled, Valut: 1.7.3-CMI
CMI Chat : enabled
Modules disabled : flightcharge, votifier, moneycheque, skin, spawnercharge,timedcommands, totembehavior
(else enabled)
```

### Errors

```shell
no errors
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will add new option into vanishedit to hide or show death messages, we will hide those by default now.
