### ISSUE TITLE
First Join and Account Age reset on Disconnect

### ISSUE THREAD

**Issue by AlphaMajora** [Zrips/CMI#7428]
**Description of issue:**

Hello, I have an issue with **First Join date** (and **Account Age**). When a player disconnect, the value changes to his logout date.

I tested disconnect, when I reconnect, First Login time is set to disconnected time (every time). But in rankup, Account Age randomly reset (also when player disconnect).

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  # When set to true, player play time will be grabbed from user stats file instead of from CMI user data file
  # This can help to get more accurate play time if you have older server and using players stats feature
  PlayTimeFromStats: true
```

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/64423271/206927187-8a54f9a7-6369-450b-a2ec-60f647d5d629.png)

**Server Type (Spigot/Paperspigot/etc):** Purpur 1858 (1.19.2)

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/64423271/206927196-214ad582-ecfd-4491-af10-0dd0d1688b23.png)

**Relevant plugins (Delete if this isn't needed):** 
![image](https://user-images.githubusercontent.com/64423271/206927238-d050c1cc-cb6b-4c0c-b84b-4075dd84d14a.png)

**Comment by Zrips** [comment]
This isint really related to CMI, atleast issue isint originating from CMI itself. Players age is determined by simply doing `System.currentTimeMillis() - player.getFirstPlayed()` where getFirstPlayed() is official method from actual server and not CMI. You might have another plugin overwriting this value or player data not being saved in general. Would recommend to test it without any other plugin except CMI to eliminate possible causes, but player statistics are not being recorded or collected by CMI

**Comment by AlphaMajora** [comment]
Thanks for your answer. I'll check that !
