### ISSUE TITLE
Lost interaction with armorstand

### ISSUE THREAD

**Issue by SkeletonAce** [Zrips/CMI#7444]
A player using more than 12 armorstands in a build cant access one of his armorstands

```/armorstand near``` 
only shows a list of 12 armorstands

Could maybe ```/armorstand near 2``` be added?
And show the next 12 armorstand near you?

**Comment by CloudeLecaw** [comment]
> A player using more than 12 armorstands in a build cant access one of his armorstands
> 
> `/armorstand near` only shows a list of 12 armorstands
> 
> Could maybe `/armorstand near 2` be added? And show the next 12 armorstand near you?

did you noticed when your useing the armorstand command the list u see are the stands next to you? same for Portals and ICs
