### ISSUE TITLE
Target world can't accessed anymore . Can't teleport you there!

### ISSUE THREAD

**Issue by Tealwen** [Zrips/CMI#7447]
### Description of Issue

i am on an Hybrid API : Mohist. that api can run Forge and Spigot together , and your plugin work verry fine but we have a mods  we have a tardis mod that allows each player to have the said tardis of doctor who. and this mod creates a new dimension at each new tardis when a player creates a new dimension. the hopme command, spawn, and other teleportation command of your plugin sends us all the same error message: Target world can't accessed anymore . Can't teleport you there!

### Version Information

```shell
[11:19:06 INFO]: --------------------------------------------------
[11:19:06 INFO]: CMI: 9.3.0.1 SqLite-> 9.3.0.2
[11:19:06 INFO]: CMILib: 1.2.4.1
[11:19:06 INFO]: Server: 1091 (MC: 1.16.5) 1.16.5-R0.1-SNAPSHOT
[11:19:06 INFO]: CMI economy: Disabled CMI Chat: Enabled
[11:19:06 INFO]: Modules -> 49 enabled 8 disabled: flightCharge, hpBossBar, tablist, ranks, votifier, shulkerBackpack, moneyCheque, headDrop
[11:19:06 INFO]: --------------------------------------------------
```

### Errors

```shell
no error in console , juste error in chat when we execute tp command of the plugin 
Target world can't accessed anymore . Can't teleport you there!
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by T14D3** [comment]
Mohist or any kind of Forge/Spigot hybrid is generally not supported in any way

**Comment by Tealwen** [comment]
the plugin is loaded all working great , juste the home or tp commande of the plugin bug when a new dimension is created . for me is supported the plugin work and no error in the console

**Comment by T14D3** [comment]
"Some parts of the plugin work" is not equal to "Server is supported by CMI"

The only officially supported Servers are Spigot and Paper (afaik) - If you can reproduce the issue on one of those, it's an actual issue.
If not - that's on you for using an "unsupported" server implementation

**Comment by Tealwen** [comment]
that is yout point of view , i think the plugin work , and i have a bug i send the bug is it fix the bug great if not i change the plugin :)

**Comment by T14D3** [comment]
> that is yout point of view , i think the plugin work , and i have a bug i send the bug is it fix the bug great if not i change the plugin :)

It's also the point of view of the official Zrips FAQ Page :)

![image](https://user-images.githubusercontent.com/73843330/208294847-03201773-9260-4715-bdd1-c8e0cf8252a2.png)

**Comment by Tealwen** [comment]
I don't know where your hatred against api hybrid comes from, but it doesn't say that you shouldn't open an issue if you have a bug x)
