### ISSUE TITLE
Nickname placeholder issue

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#745]
**Description of issue or feature request:**

When using {cmi_user_nickname} with a different chat like venturechat, it works & displays the users nickname; however, if the user has no nickname applied then it shows nothing & the user has no name.

Also, would it be possible to make {cmi_user_nickname} work with bungeetablist or no? Thanks

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

**Cmi Version (using`/cmi version`):**  latest 8.0.4.6

**Server Type (Spigot/Paperspigot/etc):**  spigot

**Server Version (using `/ver`):**  1.12.2

**Comment by splops** [comment]
Use {cmi_user_display_name} instead :)

**Comment by 0xC1A551C** [comment]
@splops I changed it to that, but unfortunately that only shows their username not their nickname

**Comment by mercurialmusic** [comment]
Just to double check, do you have CMI handling your nicknames or something else? I also use CMI with VentureChat but don't have this issue -- but I also use CMI's nick feature. I found VC's nicks didn't play well with other things, which might be what you're running into.

**Comment by 0xC1A551C** [comment]
Thanks for the reply @mercurialmusic 

I am using cmis nick names. what placeholder are you using for the nicks to work with venture chat? I tried {cmi_user_display_name}  but when i use /nick the nickname does not change.

**Comment by 0xC1A551C** [comment]
Sticking with the default venturechat nick & placeholderapi placeholders worked for everything, thanks.
