### ISSUE TITLE
ElytraListener may cause lag? Can it be disabled?

### ISSUE THREAD

**Issue by Guddina-tim** [Zrips/CMI#746]
**Description of issue or feature request:**
![elytra](https://user-images.githubusercontent.com/5891184/44188458-44f92880-a0e3-11e8-806b-2fa5d7150773.PNG)

On a brand new install of Paper 1.12.2 and CMI. No changes to the plugin's settings. I'm getting some high numbers for the ElytraListener. Is there something I can do to reduce this? I was looking at the settings and there wasn't anything clear there about disabling this. 

On my server, players very, very rarely use Elytra. I wouldn't mind disabling this entirely.

**Cmi Version (using`/cmi version`):** 

8.0.4.6

**Server Type (Spigot/Paperspigot/etc):** 

PaperSpigot

**Server Version (using `/ver`):** 

1.12.2
Version 1539

**Comment by Zrips** [comment]
Next version will have drastic improvement for this listener so it will no longer be an issue.
