### ISSUE TITLE
CommandSpy bug?

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/CMI#747]
I do not know whether I have anything wrong, or it is a bug but when I put into commanspy to block the type /login /register, etc. so i still see ...

Config:
https://hastebin.com/edohiyenej.coffeescript

--------------------------------------------------
CMI: 8.0.5.0
Server: Spigot 1.13-R0.1-SNAPSHOT
Vault: 1.6.10(+)
--------------------------------------------------

This server is running CraftBukkit version git-Spigot-2b0e71c-4a24108 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
You can still bypass those restrictions with cmi.command.commandspy.bypass permission node
