### ISSUE TITLE
CMI won't send ranged chat to DiscordSRV

### ISSUE THREAD

**Issue by PovilasLT** [Zrips/CMI#7472]
### Description of Issue

If chat mode is set to ranged, only messages from players with cmi.chat.rangebypass permission are sent to DiscordSRV. Before 1.19 update all messages was being sent.

DiscordSRV debug report: https://bin.scarsz.me/81b132b7-4fda-4454-b1de-a6bd704e4915#4NRv6HRfgiTxsMfn5zPl4dN5xoXkEGQu

### Version Information

```shell
9.3.0.2, Paper 1.19
```

### Errors

```shell
-
```

### Relevant Config Sections

```yaml
https://hastebin.com/ragoxesace.yaml
```

### Relevant Plugins

```
DiscordSRV
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by potatoru** [comment]
I don't even use Chat feature in CMI, but when GeneralRange is set to any positive value, DiscordSRV doesn't send any messages.

**Comment by Zrips** [comment]
This is actually not a bug but a feature. What I mean by this that messages with range will not be sent to discord, but shouts would. I can default back to previous behavior while adding config option to toggle this behavior for those who might want it. Next update.

**Comment by abhisantos** [comment]
I am having a problem with this actually.
I want to send only the global messages to Discord, when players type **!<message>**

But when i set the chat config to this:
    _# When disabled, only shouts and messages sent by players with cmi.chat.rangebypass permission node will be visible in discord
    RangedMessages: false_
    
global messages aren't sent. But I don't want to give the cmi.chat.rangebypass to everyone. The correct would be to send the global messages of players who have cmi.chat.shout.
