### ISSUE TITLE
Custom itemstack NBT (lore) changing in inventory via /invsee

### ISSUE THREAD

**Issue by Akeeru** [Zrips/CMI#7473]
### Description of Issue

When i check players inventory, i give, remove or checks items.
And here is a bug, when i took or place that item, item lore changes and item shop, villager shop and another plugin can't recognize that item.

Normal custom item nbt:
```
--------------------------------------------------
display (Compound)
  Name (String): {"text":"Zamieniacz","color":"blue","bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false}
  Lore (List)
    - {"text":"Automatycznie zamienia surowce na monety %player_displayname%"}
    - {"text":"- Wystarczy mieć w eq","color":"gold","bold":true,"italic":true}
HideFlags (Int): 1
Enchantments (List): [{id:"minecraft:blast_protection",lvl:1s}]
--------------------------------------------------
```

After using inventory viewer / editor (/invsee):
```
--------------------------------------------------
display (Compound)
  Name (String): {"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Zamieniacz"}],"text":""}
  Lore (List)
    - {"extra":[{"text":"Automatycznie zamienia surowce na monety akeeru"}],"text":""}
    - {"extra":[{"bold":true,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"- Wystarczy mieć w eq"}],"text":""}
HideFlags (Int): 1
Enchantments (List): [{id:"minecraft:blast_protection",lvl:1s}]
--------------------------------------------------
```

You can see above that NBT changes and broke my settings with shops and plugins.

### Version Information

```shell
--------------------------------------------------
CMI: 9.3.0.2 SqLite
CMILib: 1.2.4.1 
Server: Purpur 1.16.5-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
Modules -> 56 enabled 1 disabled: votifier
--------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Looks like items lore got its placeholder translated for one or another reason. But this cant really be done from CMI side. By any chance that same plugin you are using for those items automatically translates placeholders when you try to move items between containers?

**Comment by Akeeru** [comment]
I created new server, with only latest CMI, CMILib and my custom item.

Command `/give akeeru minecraft:brick{display:{Lore:['{"text":"test"}']}} 1` give me a item with nbt `{"text":"test"}` but after using `/invsee` command, item nbt change to `{"extra":[{"text":"test"}],"text":""}`

That above is simple, by my item has more data.

**Comment by prototype464** [comment]
^ Please fix this?

**Comment by Zrips** [comment]
This is done by the server as of something like 1.16 version it started to add extra data to text fields. Not much I can do here. And this has no impact on items visual representation, it might only be an issue if plugins tries to compare this specific item to its registered one with basic "equals" which will result in false, but this is incorrect way to determine items validity either way.
