### ISSUE TITLE
Small improvement for "/sit" command

### ISSUE THREAD

**Issue by 1ntent1on** [Zrips/CMI#7474]
Hi, having option to specify on/off for sit command would be really great. - "/cmi sit [player] on/off -s"

**Comment by mrfloris** [comment]
<img width="639" alt="Screen-Shot 2022-12-31 at 23 20 45" src="https://user-images.githubusercontent.com/28841349/210156639-d138c0c8-c7bb-4c95-a0e1-d63884fee4eb.png">

Hi there, when you create a new issue for feature, it now says that text, please respect that and post your requests for features under discussion so issues can be used for bug reports. 

That said, it would be nice if `/cmi shakeitoff` would be extended for that, with support for `[playerName]`. this way we can get players out of boats, off of /cmi ride or when they ride a pig or have players on themselves, and sit, and those other situations.

**Comment by Zrips** [comment]
I can add additional variables for sit command. Tho try to use discussion section for new feature requests
