### ISSUE TITLE
Option to disable kit previews

### ISSUE THREAD

**Issue by 1ntent1on** [Zrips/CMI#7475]
Hi, there seems not to be option to disable kit previews in chat list or GUI menu (setting perm cmi.kit.[kitname].preview to false doesnt work).

Config option to completely disable kit previews or just being able to disable it via negating its perm would be really great.

**Comment by mrfloris** [comment]
[kitname] has to be replaced with the name of the kit, if you used /cmi kiteditor to make a kit called `cat` then the perm will be `cmi.kit.cat.preview` which you can negate. This should work, if not, then they might have a wildcard permission overriding that allowing them to see preview of all kits for example. like an operator or someone with `*` perms or `cmi.kit.*`

From what I understand to globally disable it, you could negate `cmi.kit.*.preview`, I assume (but can't test right now) that this works. 

Anyway, that said:  when you create a new issue for a feature, it now says that text, please respect that and post your requests for features under discussion so issues can be used for bug reports.

**Comment by Zrips** [comment]
I can add simple option to fully disable kit preview, by default we are giving access to preview kits if you have access to them, so in general negating preview permission node wont have effect if you already can take this kit. So config option will solve this issue.
