### ISSUE TITLE
Improvement for Anti AFK feature - Prevent Crouching

### ISSUE THREAD

**Issue by 1ntent1on** [Zrips/CMI#7477]
Hello, as there is currently option to prevents jumping in one place to avoid afk status, it would be nice to have same option for crouching, as it can somewhat easily bypass AFK status. (for some reason when i look at a player, who has auto crouching mod,  via /cmi info <nick>, it will be showing me "afk in <time>" correctly, but once he enters AFK he will quit it immediately.)

Edit : Also apprently if players have mod that contantly moves their head up and down it will completely bypass anti AFK.

**Comment by mrfloris** [comment]
usually, those harder-to-detect things like head moving around automatically are something staff members are for, they manually check players who almost instantly come back from afk, who idle at farms, etc.

**Comment by Zrips** [comment]
I can add basic check for when player is standing still and just toggles sneak or moves camera around, but players can still use multiple actions at same time to bypass this, like pushing forwards and slightly turning to one side in some encloses place.
