### ISSUE TITLE
CMI's limiteduse feature addition proposal

### ISSUE THREAD

**Issue by geumu** [Zrips/CMI#7478]
With **!limiteduse!**, both right-click and left-click will consume the item.

**!limiteduse_right:[amount]!**, which consumes items only when right-clicking, 
and **!limiteduse_left:[amount]**, which consumes items only when left-clicking! I hope this feature is added.

Example)
/cmi attachcommand !limiteduse_right:1!;;!cc!cmi heal
/cmi attachcommand !left!cmi feed

**Comment by mrfloris** [comment]
That sounds like a pretty nice addition. I haven't run into the need for this yet, but I can see the use for this being handy.

<img width="639" alt="Screen-Shot 2022-12-31 at 23 20 45" src="https://user-images.githubusercontent.com/28841349/210156722-a5af22b5-95f7-4e7b-ab66-91b7f3028537.png">


Anyway, that said:  when you create a new issue for a feature, it now says that text, please respect that and post your requests for features under discussion so issues can be used for bug reports.
