### ISSUE TITLE
Cmi disable recipe dosent work

### ISSUE THREAD

**Issue by SkyDude0** [Zrips/CMI#7479]
### Description of Issue

After restart the server, all disabled recipe stop working.

On the file recipe.yml all il correct but i have to remove recipe every time i restart.

Ive also test with only CMI

### Version Information

```shell
CMI 9.2.5.6
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Server version and disabled recipe example could help out here in determining cause of the issue

**Comment by mrfloris** [comment]
> 1.18.2 pufferfish and the bug happend with every recipe

We mean, can you type this in your console and share the full output with us?
```
ver
cmi version
```
And share the `recipes.yml` file?

Can you confirm how you're disabling the recipes? You type /cmi recipe for the item you're holding like a wooden pickaxe, and top right, you click on the wool to disable it, then go to recipe.yml and see that it's listed in the yml file? Then you /stop the server and check the recipe.yml file, is it still there or already gone? And if it is still there as disabled item, you start the server and check the file when it's done loading the server, and the disabled item listing is removed? 

A bit more info can be really helpful to try and reproduce this.
