### ISSUE TITLE
[Feature] Afk reason, regenerating health, sitable blocks, and block /back world

### ISSUE THREAD

**Issue by Remski01** [Zrips/CMI#748]
I would like to see 3 things:

**Afk reason >** Enable to set an reason, example. /afk going eat, or /afk Need to check the potate's. 

This would change the command like:

/afk **to** /afk [reason] (if she/he want to use an reason, if not then just no [reason], and just /afk)

/afk [player] **to** /afk [player] [reason] (if she/he want to use an reason, if not then just no [reason], and just /afk [player]

The reason can be found back at /afkreason [player] **or** just the afk message, **aka**" [player] is now afk, reason [reason]"

============================================

Get you health regenerating when setting on a chair **if you have permission x**
Give an option to whitelist on what for chairs they can sit down.

=============================================

Add an option to block /back to world x, such as "cmi.noteleportback.[world]
And when he try he get the message that is not permitted.

=============================================

**PS:** I ask this because the current chairs plugin  does have this feature. (block whitelist, regerating health). and the afk reason also come from the current EssX what we replaced, and the last also.
**PS2:** I did not check %100 if it can be done with CMI, i just did not found it so far, and i'm on vacation with shitty internet, so even if CMI have it, you guys can just say it and i remove it from here.
**PS3:** Can the /removeuser cause chunk corruptions or can chunks brake? Because, we recently deleted a few, and later we found corrupted chunk. I did not test it fully because it was right before my vacation(CMI was one of the things that have been touched). But, CAN CMI cause this? This is the settings under the purge **>** https://pastebin.com/FRihjcKj **/** https://pastebin.com/6xFLmHEL**,** if yes. the  i make an other ticket about it, if no. Well. Nothing.

**Comment by CloudeLecaw** [comment]
Blocking /back by world is handled from your permissionsystem.
Simply just give the cmi.command.back permission is Worlds where u want it.

**Comment by DutchUser** [comment]
Thanks for letting me know about that AFK Reason en /afkcheck were added.

"Blocking /back by world is handled from your permissionsystem.
Simply just give the cmi.command.back permission is Worlds where u want it."

I dont mean to just block /block, i mean an permission or config setting that can block that /back goes in an specific world. As example, if player dies in world A, he can use /back. If player dies in World B, he cannot teleport back to that world.

**Comment by Drc-DEV** [comment]
You could make it so if they do not have the permission cmi.command.back in a world they can't go back in that world. @Zrips
