### ISSUE TITLE
cmi /glow ony white

### ISSUE THREAD

**Issue by AlphaAlphaAlpha** [Zrips/CMI#7483]
### Description of Issue

![7551687a417818e85761435907f7c4f2](https://user-images.githubusercontent.com/56409408/210183980-178f7afe-a79f-44ec-8364-86e3b743b480.png)

i have a problem the players or i are only displayed in white with /glow

### Version Information

```shell
[21:40:32 INFO]: --------------------------------------------------
[21:40:32 INFO]: CMI Plugin Version: 9.3.0.2 BungeeCord CMIB  MySQL
[21:40:32 INFO]: CMILib: 1.2.4.1
[21:40:32 INFO]: Server: Purpur 1.19.2-R0.1-SNAPSHOT
[21:40:32 INFO]: CMI economy: Aktiviert Vault: 1.7.3-CMI CMI Chat: Deaktiviert
[21:40:32 INFO]: Modules -> 55 enabled 2 disabled: tablist, votifier
[21:40:32 INFO]: --------------------------------------------------
```

### Relevant Plugins

https://gyazo.com/8e14500c1899276acbed8f4fd9186014

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Do you have opportunity to test this one with CMI only? As this is usually caused by interference from another plugin or you might have DisableTeamManagement set to true in config file which will disable glow colors and only leave white one

**Comment by AlphaAlphaAlpha** [comment]
![7c8d638a52552d4184ab70e3855daf09](https://user-images.githubusercontent.com/56409408/210407899-143dd5ce-0974-4076-aab2-9534aa00795c.png)
![ff8b70387243d8dd5725ce145b9af1ff](https://user-images.githubusercontent.com/56409408/210407914-2c84896c-cea1-4f6b-9c18-f9673012e15d.png)




I deleted all plugins but it still doesn't work

**Comment by mrfloris** [comment]
I have an article here that perhaps helps you go through some steps; 
<https://faq.cmi.support/glow> Might be handy to double check.

You mention you have no other plugins installed. I just checked 1.19.2 test instance, and it works for me on vanilla launcher and vanilla client. Can you confirm you're not using an unofficial client?

**Comment by AlphaAlphaAlpha** [comment]
I tested it with the original Mc version, the problem is the same, I read that TAB plugin has a conflict with CMI. I used the TAB plugin but on my bungee cord, so it doesn't work?

**Comment by AlphaAlphaAlpha** [comment]
Okey I removed the TAB plugin and now it works. how can i fix this?

**Comment by mrfloris** [comment]
Issue is with tab. Not cmi
Their wiki has a page explaining how to make it work

**Comment by AlphaAlphaAlpha** [comment]
thank you very much i found it <3
