### ISSUE TITLE
CMI 8.0.5.0 Error

### ISSUE THREAD

**Issue by Gasha666** [Zrips/CMI#749]
CMI elevators not working

and getting this error

https://hastebin.com/ogewumudag.cs

Just to ask are you planning to resolve issues thats been reported more then month ago, some of them are real serious --> https://github.com/Zrips/CMI/issues/621

My server version is PaperSpigot 1.12.2

i'm planing to update to PaperSpigot 1.13 when they release more stable version

**Comment by CloudeLecaw** [comment]
https://github.com/Zrips/CMI/issues/719
https://github.com/Zrips/CMI/issues/702

**Comment by LogGits** [comment]
Should be working in the latest version. Please let me know if you are still experiencing this issue. Regarding that issue it would be easier to have them in their own issues whereby we could assign specific issues to milestones e.g. update `8.0.18.0`. We will get to it eventually but if you are still having major issues and they aren't already reported please make separate issues for them and we will look into it asap 🙂
