### ISSUE TITLE
Damage NBT after /scavenge on normal materials

### ISSUE THREAD

**Issue by Bloodlex** [Zrips/CMI#7490]
### Discussed in https://github.com/Zrips/CMI/discussions/7460

<div type='discussions-op-text'>

<sup>Originally posted by **Bloodlex** December 22, 2022</sup>

**Description of Issue**

Hey,

Why scavenging for instance Chest returns Wood planks with some Damage NBT on it?

It can't be used in some recipes from other plugin respecting NBTs when they expect a normal item without any NBT on it.

Can I disable it somehow, so it doesn't add this NBT to materials?

Thanks for your help!

![image](https://user-images.githubusercontent.com/1086720/209098223-f084d548-ef14-4abf-874d-ce4c786da89c.png)</div>

**Version Information**

CMI: 9.3.0.5 MySQL
CMILib: 1.2.4.1 
Server: Purpur 1.19.3-R0.1-SNAPSHOT
CMI ekonomia: Enabled Vault: 1.7.3-b CMI Chat: Enabled 
47 activ 10 inactive: flightCharge, tablist, ranks, firstJoinMessages, votifier, sitAnimation, elytraBoost, vanish, elytraLaunch, kits

**Errors**
Not relevant

**Relevant Config Sections**
Not relevant

**Agreements**
 My server is supported by CMI.
 My version of CMI at the time of this report is up to date.
 I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Uhm, I can't seem to reproduce this on latest Paper build.
<img width="1566" alt="Screen-Shot 2023-01-04 at 14 51 31" src="https://user-images.githubusercontent.com/28841349/210569721-ae242fa2-ae68-442a-ab70-11b35c4a8b83.png">
<img width="1566" alt="Screen-Shot 2023-01-04 at 14 51 39" src="https://user-images.githubusercontent.com/28841349/210569738-fc67081e-0f95-4aec-b28f-565e0ea7c023.png">
<img width="569" alt="Screen-Shot 2023-01-04 at 14 51 49" src="https://user-images.githubusercontent.com/28841349/210569749-9e20eb71-3621-4fb2-a4b2-ab164d27b967.png">

Got any other examples for items that go wrong for you?

**Comment by Zrips** [comment]
Should be fixed with next build

**Comment by Bloodlex** [comment]
Sorry I haven't noticed the previous answer - yes, now it's all right, thank you very much! 🙂 👍
