### ISSUE TITLE
Fly Problems Again in 9.3.0.5

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#7493]
### Description of Issue

(Reposting this from my comment on #7464) I'm seeing something weird again as of the update to 9.3.0.5. Normal handling seems ok unless another plugin puts the players into spectator mode, in which case fly is removed and they fall endlessly. It's happening in the spectator modes for our minigames mostly, not really having trouble with world changes otherwise. The previous handling pre 9.3.0.5 (after the previous fixes) was ideal, but this is breaking all of our minigames in the meantime.

### Version Information

```shell
CMI plugin version: 9.3.0.5 BungeeCord CMIB  SqLite
CMILib: 1.2.4.1 
Server: Paper(368) 1.19.3-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 55 enabled 2 disabled: ranks, skin
```

### Errors

```shell
None
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mercurialmusic** [comment]
For additional context, this still happens when the player has the cmi.worldlimit.fly.bypass permission.

But! 
```
WorldLimits:
  # By setting to true fly and gamemode limitations per world will be aplied for player on world change if they dont have appropiate permission node
  Enabled: false
```
  That's false on this particular server to begin with, so not sure why it would mess with it at all.

**Comment by Rexmen1** [comment]
Same issue for me... world change, /back /home, etc disables the fly if they in diff worlds... and not even using world limits

**Comment by x1p** [comment]
Same. See also issue #7411 from late November.
Can @Zrips please fix this for once and for all?

**Comment by mercurialmusic** [comment]
I personally don't think these are quite the same. I'm only having the issue when another plugin changes the gamemode for the player, specifically in my case spectator mode for spectating mini games. The previous issues were (and remain) solved for me. I think this is something new in 9.3.0.5, although probably related. The gamemode and world switches were previously working as expected until 9.3.0.5.

**Comment by ZEROOblivious** [comment]
I'm experiencing the issue with Temp-Fly and not the actual Fly.  Actual Fly was fixed once disabling world-limits in config. 

Temp-Fly is constantly disabling via World-Switch. I do not think TFly is integrated into the World Limit Fly Configuration Settings.
Was given asConsole! ptarget:[playerName]! cmi tfly [playerName] %cmi_user_tfly% -s by a Moderator(?) in the discord? 

Even setting this up as a Custom Alias, its not resolving the issue with Temp Fly.

**Comment by ChimpGamer** [comment]
Same here. There are still issues with fly disabling on world change.

**Comment by Jeroen123TC** [comment]
Also here, samen bug!

**Comment by TiboOpGithub** [comment]
Yes, I have the same problem. Very annoying! 😕

**Comment by SkeletonAce** [comment]
Annoying bug please fix 🙏

**Comment by Zrips** [comment]
Will issue fix with today's update. Apologies for inconvenience.

**Comment by mercurialmusic** [comment]
Working perfectly now, thank you!

**Comment by Jeroen123TC** [comment]
> Will issue fix with today's update. Apologies for inconvenience.

Its still not working correctly

**Comment by Reaver87mc** [comment]
Getting same issue, is there a setting to fix this, have repeatedly asked in discord but never any answer?

On world change immediately says Flight is disabling in 3>2>1 "
