### ISSUE TITLE
Death chests / Graves / Tombstones

### ISSUE THREAD

**Issue by kemmeo** [Zrips/CMI#750]
I'd love it if we could have sealed chests or blocks placed where players die, that return a player's inventory to them when opened.

Also, havening the chests being "locked" for the first 10 minutes (so only the player whom the chest belongs to can open it) would be great to prevent raiding.

**Comment by MCTyler** [comment]
Unless it was in Lava......

**Comment by kemmeo** [comment]
@MCTyler very true, but I'm certain that can checked for.

**Comment by LogGits** [comment]
This is a great idea for a plugin, however, this isn't something that we would add to cmi.
