### ISSUE TITLE
Add event PlayerSellItems 

### ISSUE THREAD

**Issue by Igzak** [Zrips/CMI#7502]
Please add event PlayerSellItems with items list and player, need this event for a statistics of sell/buys items

**Comment by Igzak** [comment]
Will be perfect something like this one
https://github.com/Gypopo/EconomyShopGUI-API/blob/main/src/main/java/me/gypopo/economyshopgui/api/events/PostTransactionEvent.java

**Comment by Zrips** [comment]
Will add CMIPlayerItemsSellEvent event with next update which should provide some information about transaction.
