### ISSUE TITLE
Flight disabled on world change

### ISSUE THREAD

**Issue by mike3132** [Zrips/CMI#7503]
### Description of Issue

I have noticed that in the most recent version of cmi that when a player changes worlds they loose flight.

I would like to mention that I wrote my own flight plugin that uses fuel, however I do not specifically touch or handle the world change event in this plugin. Upon a player meeting the criteria to fly I simply set setAllowFlight(true) && setFlying(true) on the player. 

I know in the past I have seen a few issue about flight being lost upon world change with cmi and I was wondering if because I set them as flying if cmi is seeing them not as flying and thus is conflicting with my system.

### Version Information

```shell
[21:58:27 INFO]: --------------------------------------------------
[21:58:27 INFO]: CMI: 9.3.0.5 BungeeCord CMIB  SqLite
[21:58:27 INFO]: CMILib: 1.2.4.1 
[21:58:27 INFO]: Server: Paper(307) 1.19.2-R0.1-SNAPSHOT
[21:58:27 INFO]: CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Enabled 
[21:58:27 INFO]: Modules -> 56 enabled 1 disabled: tablist
[21:58:27 INFO]: --------------------------------------------------
```

### Errors

```shell
N/A
```

### Relevant Config Sections

```yaml
N/A
```

### Relevant Plugins

https://www.spigotmc.org/resources/dragon-fly.106102/

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will issue new version today and some bug fixes relating to this handling which should resolve your issue
