### ISSUE TITLE
"surface-only" setting for RandomTeleportation

### ISSUE THREAD

**Issue by mfnalex** [Zrips/CMI#7510]
Currently, when using /rt, players often get teleported into caves.

Adjusting the min-y setting is not an option, as different biomes have different surface levels. For example setting it to 80 would prevent players from being teleported into plains, while setting it to 60 would still make them be teleported into mountain caves (or basically, any caves in an amplified world).

I suggest do add an option `surface-only: true|false`. When set to true, /rt would only consider Locations where the Y is >= World#getHighestBlockYAt()

**Comment by Zrips** [comment]
Will add with next update
