### ISSUE TITLE
Cyrillic chat filter regex bypass

### ISSUE THREAD

**Issue by DarkyCat** [Zrips/CMI#7514]
### Description of Issue

You can't check case through regex because of this, there are a lot of bypasses. the (?i) flag only works with Latin characters.
Needed add toLowerCase to ChatFilterListener
![изображение](https://user-images.githubusercontent.com/50515714/212317551-7263b5f7-f13e-4309-bddf-6855d5a30bfd.png)

### Version Information

```shell
9.3.0.5
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update. This is good catch, tho solution isint case lowering but adding flag to actual pattern rule as Pattern.UNICODE_CASE which still allows you to filter out capitalized words if needed while allowing lower case ones.
