### ISSUE TITLE
How to turn off a Chat management 

### ISSUE THREAD

**Issue by GabStudioGamers** [Zrips/CMI#7522]
I have a question How to turn off a Chat management because i have one plugin and when i write a message it dupplicated in 2x (sorry for gramatic)

**Comment by Zrips** [comment]
Go to config.yml file and disable ClickHoverMessages if you want to avoid duplicated messages. You can keep ModifyChatFormat if that isint interfering with your setup or set it to false if you want to use only one plugin for char message formatting and handling, which is recommended to do.
