### ISSUE TITLE
/jump through worldborder

### ISSUE THREAD

**Issue by Dusten9752** [Zrips/CMI#7526]
### Description of Issue

A player has reported to me that they jumped through the worldborder using `/jump` and was requesting I refund their deathchest loot as its a server issue. I went on to tell them this was impossible. I've test this many times, and it turns out this is true.

https://user-images.githubusercontent.com/107232561/213011287-cf6ce06d-af44-4fe6-8fac-bf2fb27a98dd.mp4

### Version Information

```shell
9.3.0.5
```

### Relevant Plugins

1.7.3-b131

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next build

**Comment by Dusten9752** [comment]
This is also the same for barriers.
