### ISSUE TITLE
Translation of CMILib

### ISSUE THREAD

**Issue by norhu1130** [Zrips/CMI#7528]
Can't I extract it from Minecraft translation and apply it to CMILib?
Too many entities and items.

**Comment by CloudeLecaw** [comment]
> Can't I extract it from Minecraft translation and apply it to CMILib? Too many entities and items.
no you have a file in cmilib/ translations called items.yml there you need to translate them all.

**Comment by norhu1130** [comment]
> > Can't I extract it from Minecraft translation and apply it to CMILib? Too many entities and items.
> 
> no you have a file in cmilib/ translations called items.yml there you need to translate them all items. in the language file you translate all entities.
> 
> the Translation is not taken from your server or client automaticly.

Can't you extract the translation from Minecraft language files?

**Comment by CloudeLecaw** [comment]
no you cant ;)

**Comment by Zrips** [comment]
@norhu1130 
There are some ways to extract information like that from server files itself, but currently we are not utilizing this system, but will keep this in mind.
