### ISSUE TITLE
Don't let gradients and color codes count towards nick length

### ISSUE THREAD

**Issue by neokyle** [Zrips/CMI#7540]
### Description of Issue

In order to allow gradients with nicknames length needs to be set really high which can be misused, would like the option to not count color codes against nick limit. 

### Version Information

```shell
CMI: 9.2.5.2 BungeeCord CMIB  SqLite-> 9.3.0.6
CMILib: 1.2.4.1 
Server: Pufferfish 1.19.2-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Enabled 
Modules -> 54 enabled 3 disabled: tablist, firstJoinMessages, votifier
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Gredients are not being included into nickname length already, all color codes been removed before checking its length. For example `{#purple>}1234567890123456{#brown<}` is fine with 16 symbol limit even tho its like 240 symbols long with all of those colors added.
