### ISSUE TITLE
Commented out CustomAliases are being deleted

### ISSUE THREAD

**Issue by 1ntent1on** [Zrips/CMI#7542]
### Description of Issue

Hi, for some reason commented out aliases get deleted after doing /cmi reload (most likely also after server restart).

Steps to reproduce:
1) Make a custom alias, example in config section
2) Restart your server
3) Comment out newly made alias
4) Do /cmi reload
5) Take a look into CustomAlieses folder, commented out alias should be completely gone

### Version Information

```shell
19:47:22[INFO] CMI plugin version: 9.3.0.6 SqLite
19:47:22[INFO] CMILib: 1.2.4.1
19:47:22[INFO] Server: Pufferfish 1.19.3-R0.1-SNAPSHOT
19:47:22[INFO] CMI economy: enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: enabled
19:47:22[INFO] Modules -> 33 enabled 24 disabled: cuffed, mirror, launchPad, tablist, armorstand, versionCheck, armorEffects, moneyCheque, skin, noTarget, jail, paintingEditor, dynamicSigns, playerChatTag, bossBarCompass, coloredArmor, deathMessages, ran
ks, votifier, shulkerBackpack, attachedCommands, spawnerCharge, vanish, timedCommands
```

### Relevant Config Sections

```yaml
CustomAlias:
  rtp:
    Cmds:
    - asConsole! cmi rt [playerName] World
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version

**Comment by 1ntent1on** [comment]
Same problem also seems to be happening with commented out holograms after server restart.
