### ISSUE TITLE
Link formatting does not work in /staff chat

### ISSUE THREAD

**Issue by impmallet** [Zrips/CMI#755]
When you paste a link using the /staff command it does not format it into a truncated link.

There is no error associated with this, it just seems the code does not process staff messages for formatting. I am unsure if this is intentional or not. If it is, then I suppose this is a feature request.

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**Cmi Version (using`/cmi version`):** 
--------------------------------------------------
CMI plugin version: 8.0.5.0
Server version: Spigot 1.13-R0.1-SNAPSHOT
--------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-Spigot-2b0e71c-c0df4b8 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
This was added in latest builds
