### ISSUE TITLE
 The skin is broken to change the world

### ISSUE THREAD

**Issue by Ksewedo5** [Zrips/CMI#7552]
### Description of Issue

After use command ./cmi skin ksewedo5 
![Screenshot_4](https://user-images.githubusercontent.com/54962940/214863154-fc1d4140-a815-452c-bacc-795ac30b9d88.png) result, everything is correct

![Screenshot_5](https://user-images.githubusercontent.com/54962940/214863464-44530f89-b4cd-4bdf-b169-fd25fd798ca0.png) 
After teleporting to another world (using a command or teleporting to the nether via a portal) the skin's head layer is damaged

### Version Information

```shell
CMI 9.3.1.0, CMILib 1.2.4.3 
Paper(348) 1.19.3-R0.1-snapshot
```

### Errors

```shell
Only visual error
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by 1ntent1on** [comment]
Are you sure that its really caused by CMI?
It also happens on 1.19.3 Paper server (ofc without the /skin <nick> part)

https://github.com/PaperMC/Paper/issues/8689

**Comment by Zrips** [comment]
CMI doesn't really do anything with skins on world change, CMI will only modify that on player login or when you perform skin command. Try updating to latest paper build and retest it, if issue persists let me know, but this should not be caused by CMI and isint really reproducible at the moment.
