### ISSUE TITLE
Converting from Essentials doesn't convert all players

### ISSUE THREAD

**Issue by DuneSciFye** [Zrips/CMI#7556]
### Description of Issue

Converting from essentials doesn't seem to convert all players data.
I'm using MySQL purpur 1.19.3
![90692A06-E7BA-443E-A40F-555CE617A127](https://user-images.githubusercontent.com/65089425/215275930-dcc94658-1964-4f19-8044-46afeb4c51bd.jpeg)
![75E05E00-C10A-4FE8-A6BA-E9EAAF9E71B6](https://user-images.githubusercontent.com/65089425/215275931-225cbd05-474e-4cd9-a858-84ad9b7b9c20.jpeg)

### Version Information

```shell
[Sat 10:48:19 INFO ] --------------------------------------------------
  [Sat 10:48:19 INFO ] CMI: 9.3.1.2 MySQL
  [Sat 10:48:19 INFO ] CMILib: 1.2.4.3 
  [Sat 10:48:19 INFO ] Server: Purpur 1.19.3-R0.1-SNAPSHOT
  [Sat 10:48:19 INFO ] CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Disabled 
  [Sat 10:48:19 INFO ] Modules -> 43 enabled 14 disabled: spawnerProximity, cuffed, mirror, tablist, moneyCheque, holograms, jail, spawners, flightCharge, votifier, headDrop, attachedCommands, spawnerCharge, interactiveCommands
  [Sat 10:48:19 INFO ] --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by DuneSciFye** [comment]
![Uploading 109366FA-07F2-4FBE-8361-6668B39A2D74.jpeg…]()
And after some time it looks like it just does this for a while

**Comment by DuneSciFye** [comment]
![1732E768-59F5-44E6-B9F7-FFC055E333CF](https://user-images.githubusercontent.com/65089425/215276017-0679c17d-ee51-4e34-8a31-2aa8e76ecd57.jpeg)

**Comment by DuneSciFye** [comment]
14k files. I'll send some in a bit

**Comment by DuneSciFye** [comment]
[00000000-0000-0000-0009-01fe762c845a.txt](https://github.com/Zrips/CMI/files/1057475
[85dbcc53-1e88-4834-afe4-481607ac8bf3.txt](https://github.com/Zrips/CMI/files/10574755/85dbcc53-1e88-4834-afe4-481607ac8bf3.txt)
[47fe5d61-fe84-48f3-9aab-a5a6f7cc58ec.txt](https://github.com/Zrips/CMI/files/10574756/47fe5d61-fe84-48f3-9aab-a5a6f7cc58ec.txt)
[9ab70e49-f86e-461f-9678-717d4049d494.txt](https://github.com/Zrips/CMI/files/10574757/9ab70e49-f86e-461f-9678-717d4049d494.txt)
[00000000-0000-0000-0009-00000956ced0.txt](https://github.com/Zrips/CMI/files/10574758/00000000-0000-0000-0009-00000956ced0.txt)
[00000000-0000-0000-0009-000008168a13.txt](https://github.com/Zrips/CMI/files/10574759/00000000-0000-0000-0009-000008168a13.txt)
[00000000-0000-0000-0009-01fe775b1ffb.txt](https://github.com/Zrips/CMI/files/10574760/00000000-0000-0000-0009-01fe775b1ffb.txt)
3/00000000-0000-0000-0009-01fe762c845a.txt)

**Comment by Zrips** [comment]
Did you resaved it into .txt format or was it in one originally?

**Comment by Zrips** [comment]
Nvm, looks to be an issue with saving process, will make a fix with next version and if issue repeats after that, let me know.

**Comment by DuneSciFye** [comment]
CMI version 9.3.1.4
Checked essentials playerdata folder for playerdata files of me and a few other players. Did not appear.
Did conversion command /cmi importfrom essentials money
After it was done converting my money was set to 10k, even though my playerdata file wasn't there in essentials.
Checked MySQL database table and all the current players that were already in the table were reset to their original from essentials, and no new playerdata rows were added.
Now I have to spend a few hours fixing the current players money to their correct values.
