### ISSUE TITLE
The Scheduler function does not recognize the variables of third-party plug-ins

### ISSUE THREAD

**Issue by Mr-obbit** [Zrips/CMI#7557]
### Description of Issue

I want to use the Scheduler function to execute a series of commands every night. The content of the command is to give the top player a timing permission.

However, I found that the Scheduler function can normally recognize the built-in variables of cmi, but cannot recognize the variables of third-party plug-ins.

I use other plug-ins to test these error variables, which can be displayed. I can't load the variables of other plug-ins when I add them to the scheduled task.

### Version Information

```shell
[06:45:55] [Render thread/INFO]: [System] [CHAT] CMI version: 9.3.1.2 SqLite
[06:45:55] [Render thread/INFO]: [System] [CHAT] CMILib: 1.2.4.3 
[06:45:55] [Render thread/INFO]: [System] [CHAT] Server: Paper(386) 1.19.3-R0.1-SNAPSHOT
[06:45:55] [Render thread/INFO]: [System] [CHAT] CMI economy: on Vault: 1.7.3-CMI CMI Chat: on 
[06:45:55] [Render thread/INFO]: [System] [CHAT] Modules -> 56 enabled 1 disabled: votifier
```

### Relevant Config Sections

```yaml
The command is as follows: the first two commands are executed correctly, and the latter two commands cannot specify players

  - lp user %cmi_playtimetop_name_1% permission settemp time1 true 23h
  - lp user %cmi_baltop_name_1% permission settemp money1 true 23h
  - lp user %playerTop_mcMmo_1_name% permission settemp mcmmo1 true 23h
  - lp user %playerTop_playerGuildMoney_1_name% permission settemp plgm1 true 23h
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Do those placeholders properly parses while using **/cmi placeholder parse %playerTop_mcMmo_1_name%**

**Comment by Mr-obbit** [comment]
yes
![image](https://user-images.githubusercontent.com/42176007/216675663-a7df5b9b-9386-4710-89bd-0c71a1e6f0d8.png)

**Comment by Zrips** [comment]
Does this still parse when you perform from console? And which plugins are you using in particular for those placeholders?

**Comment by Zrips** [comment]
Did some testing and placeholders seam to be translated properly from different plugins over PAPI, so something weird is going on here.

**Comment by Mr-obbit** [comment]
Sorry, my fault, it was indeed a problem with the console.
