### ISSUE TITLE
CMI Glow don't work with Nametags.

### ISSUE THREAD

**Issue by PanetiX** [Zrips/CMI#7560]
### Description of Issue

We use plugin CMI and plugin NametagEdit for Nametags before playernames.

The Nametags will be showing before every username.
When a user activate a Glow effect with /cmi glow the Nametag dwill not be showing anymore.

I don't know if this is a CMI issue or a NametagEdit issue.

### Version Information

```shell
CMI: 9.3.1.2
NametagEdit: 4.5.14
```

### Errors

```shell
no error in log
```

### Relevant Plugins

NametagEdit 4.5.14

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
This is issue with how nametags work in general, aka issue with minecraft game limitations. Don't know at the moment for good solution for this as glow and nametags uses player teams which are somewhat messy to handle when you have more than one plugin managing those. No real solution at the moment.
