### ISSUE TITLE
Oraxen Placeholders in prefix create cmi error

### ISSUE THREAD

**Issue by jackboi03** [Zrips/CMI#7571]
### Description of Issue

I created some glyphs with oraxen for ranks and want to implement these.
But when I use the glyph placeholder using placeholderapi the console gives me this error every time I write something in chat: https://pastebin.com/yjE3UwmC and the prefix just vanishes.
The prefix I am trying to use is this: %oraxen_spielerrank%

### Version Information

```shell
[21:19:52 INFO]: --------------------------------------------------
[21:19:52 INFO]: CMI Plugin Version: 9.3.1.3 SqLite
[21:19:52 INFO]: CMILib: 1.2.4.5
[21:19:52 INFO]: Server: Paper(307) 1.19.2-R0.1-SNAPSHOT
[21:19:52 INFO]: CMI economy: Disabled CMI Chat: Enabled
[21:19:52 INFO]: Modules -> 56 enabled 1 disabled: votifier
[21:19:52 INFO]: --------------------------------------------------
```

### Errors

```shell
https://pastebin.com/yjE3UwmC
```

### Relevant Plugins

PlaceholderAPI 2.11.2 Oraxen 1.151.0

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Do you get the same error with the latest jenkins build? <https://ci.extendedclip.com/job/PlaceholderAPI/>

In the console of the server, can you try this on an online player, and share the full output with us?
`papi parse onlineplayernamehere %oraxen_spielerrank%`
and the same for
`cmi placeholders parse %oraxen_spielerrank% onlineplayernamehere`

And can you show some of the glyphs you've set, their unicode or the actual character as you've configured it in the other plugin?

**Comment by jackboi03** [comment]
I tried it with the latest jenkins build and the error persists. Here is a pastebin with the error the console gave out after installing the latest jenkins build: https://pastebin.com/LgduSzMm

The output for the first command: [17:31:51 INFO]: ꐞ
The output for the second command: [17:32:54 INFO]: %%oraxen_spielerrank%% von PAPI Ergebnis |ꐞ|

Here is the unicode for the %oraxen_spielerrank% glyph: ꐞ
and for %oraxen_adminrank% glyph: ꐣ

And this is the code for the spieler rank glyph:
spielerrank:
  texture: default/chat/spieler
  ascent: 30
  height: 30
  chat:
    placeholders:
      - "spieler"

**Comment by mrfloris** [comment]
Hey, it seems to be able to print the glyph with those two commands, I assume you edit cmi's config.yml to include that specific placeholder in the group chat format section and when they speak in the game in chat it creates that error in console?

If not, where is it trying to use cmi how to display it?

**Comment by jackboi03** [comment]
I am using pex for permissions and set a prefix for every group.
And yes I edited the cmi config.yml to include the prefix in the chat.
When using the unicode of the oraxen placeholder it works, but when I use the oraxen placeholder it gives me the error.
But why am I using the oraxen placeholders you may ask?
The problem is that the ranks do not have a unicode that stays the same.
Every time I add a glyph to oraxen every unicode changes and I have to update every group manually which is a real pain.
But the oraxen placeholders do not change so I can set them once as a prefix and they will persist even if I add new glyphs.

**Comment by Zrips** [comment]
Will make some adjustment with next update. If issue persists let me know.

**Comment by jackboi03** [comment]
After updating to CMI v.9.3.1.4 the error still persists.
The rank just vanishes and I get this error in the console:
https://pastebin.com/65ntknSk
PAPI version: 2.11.3-DEV-160
PEX version: 1.23.4
CMILib version: 1.2.4.5
