### ISSUE TITLE
Custom recipe bug 1.13

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/CMI#758]
--------------------------------------------------
CMI 8.0.5.0
Server version: Spigot 1.13-R0.1-SNAPSHOT
Version Vault: 1.6.10(+)
--------------------------------------------------
This server is running CraftBukkit version git-Spigot-2b0e71c-4a24108 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

https://youtu.be/XV2UTCpcbKs

**Comment by RustyDagger** [comment]
From watching the video it seems CMI is not saving the new 1.13 items when they are used as ingredients.

**Comment by Zrips** [comment]
Will be fixed with next build.
