### ISSUE TITLE
Incorrect work of prefixes in chat

### ISSUE THREAD

**Issue by samparotony228** [Zrips/CMI#7589]
### Description of Issue

After the release of the new update CMI (9.3.1.4) and CMILib (1.2.4.5), the colors of the player's prefix and nickname stopped working in the chat. This stopped working for both local chat and global chat.

Server version - git-Purpur-1858 (MC: 1.19.2)* last build

### Version Information

```shell
/cmi version - https://imgur.com/a/zsT1Ij1
```

### Errors

```shell
There are no errors in the chat or in the console.
```

### Relevant Config Sections

```yaml
Link to the code of my chat setup - https://pastebin.com/1nMNpm3q
```

### Relevant Plugins

LuckPerms 5.4.35, PlaceholderAPI 2.11.2, ProtocolLib 5.0.0-b606

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by nhanledev** [comment]
I have the same issue and have to rollback to 9.3.1.3.
My chat gets colors as HEX from placeholders `{#RRGGBB}` and after updating the color are all gone but format like bold still work.

**Comment by CloudeLecaw** [comment]
for now downgrade to 9.3.1.3 solved it
a simliar issue has been reported here too
https://github.com/Zrips/CMI/issues/7587

**Comment by LucidAPs** [comment]
Same issue here.

**Comment by SkeletonAce** [comment]
Also have this issue colours are not appearing properly, using 9.3.1.3 for now

**Comment by CloudeLecaw** [comment]
if you have this in 9.3.13 check your NOT using a plugin that cancels it like NoChatReports or Antipopup that are changing the chat to chancel the reporting..

**Comment by PanetiX** [comment]
> if you have this in 9.3.1.3 check your NOT using a plugin that cancels it like NoChatReports or Antipopup that are changing the chat to chancel the reporting..

but what when we want to use AntiPopUp Plugin? :D

**Comment by CloudeLecaw** [comment]
then use it;)
but in result the hexchat seem to be broken, thats how the plugin works it modifies the chat.

**Comment by Zrips** [comment]
Will issue fixed version today.
