### ISSUE TITLE
chatspy not working.

### ISSUE THREAD

**Issue by ghost** [Zrips/CMI#7590]
### Description of Issue

I haven't tested this feature since purchasing the plugin, but today I decided to tweak it and noticed that the /options feature called "Chat Spy" is not working. I tested command spy and sign spy - they work, but Chat Spy doesn't work.

Server version - git-Purpur-1858 (MC: 1.19.2)* last build

### Version Information

```shell
/cmi version - https://imgur.com/a/zsT1Ij1
```

### Errors

```shell
There are no errors in the chat or in the console.
```

### Relevant Config Sections

```yaml
I got acquainted with the plugin files and did not find a global setting for these functions that could create a problem in operation.
```

### Relevant Plugins

ProtocolLib 5.0.0-b606

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
cmi doesnt have spy, chatspy and cmdspy anymore as command you need to create own custom alias if you want them back or use the new command for these settings

> cmi options (playerName) (option) (enable/disable/toggle/status) (-s)](https://www.zrips.net/cmi/commands/)
> Modify personal options
> 
> Commands work individually. Without parameters will open a GUI where players can toggle to enable/disable certain features.
> As of CMI version 9.1.4.x these legacy commands have been moved into a newer more convinient single /options command: togglecompass, toggleshiftedit, toggletotem, tagtoggle, socialspy, commandspy, signspy, msgtoggle, tptoggle, paytoggle.
> 
> In the config.yml file you can further configure the /options’ GUI panel.
> 
> Permissions involved to allow modifying specific options: cmi.command.options.[visibleholograms/shiftsignedit/totembossbar/bassbarcompass/tagsound/chatspy/cmdspy/signspy/acceptingpm/acceptingtpa/acceptingmoney]. Players will also need the base command: cmi.command.options
> 
> Placeholders are grouped as well: %cmi_user_toggle_[msg|pay|tp|compass|sospy|sispy|cospy|schest|autoflightrecharge|totem|shiftedit]% %cmi_user_togglename_[msg|pay|tp|compass|sospy|sispy|cospy|schest|autoflightrecharge|totem|shiftedit]%

**Comment by samparotony228** [comment]
> cmi doesnt have spy, chatspy and cmdspy anymore as command you need to create own custom alias if you want them back or use the new command for these settings
> 
> > cmi options (playerName) (option) (enable/disable/toggle/status) (-s)
> > Modify personal options
> > Commands work individually. Without parameters will open a GUI where players can toggle to enable/disable certain features.
> > As of CMI version 9.1.4.x these legacy commands have been moved into a newer more convinient single /options command: togglecompass, toggleshiftedit, toggletotem, tagtoggle, socialspy, commandspy, signspy, msgtoggle, tptoggle, paytoggle.
> > In the config.yml file you can further configure the /options’ GUI panel.
> > Permissions involved to allow modifying specific options: cmi.command.options.[visibleholograms/shiftsignedit/totembossbar/bassbarcompass/tagsound/chatspy/cmdspy/signspy/acceptingpm/acceptingtpa/acceptingmoney]. Players will also need the base command: cmi.command.options
> > Placeholders are grouped as well: %cmi_user_toggle_[msg|pay|tp|compass|sospy|sispy|cospy|schest|autoflightrecharge|totem|shiftedit]% %cmi_user_togglename_[msg|pay|tp|compass|sospy|sispy|cospy|schest|autoflightrecharge|totem|shiftedit]%
> 
> so for example for cmdspy this would be playername and -s are optional`cmi options (playername) cmdspy [enable/disable/toggle/status] (-s)`
> 
> here an example how cmdspy customalias could look as toggleable command:
> 
> ```
> CustomAlias:
>   cmdspy:
>     Cmds:
>     - check:$1==null! asConsole! cmi options [playerName] cmdspy toggle
> 	- check:$1==-s! asConsole! cmi options [playerName] cmdspy toggle -s
>     - perm:cmi.customalias.cmdspy.others! check:$1!=null|-s! check:$2==null! asConsole! cmi options $1 cmdspy toggle
> 	- perm:cmi.customalias.cmdspy.others! check:$1!=null! check:$2==-s! asConsole! cmi options $1 cmdspy toggle -s
>     Perm: true
>     Tab: true
>     CustomTabs:
>     - '[playername],-s, -s'
> ```
> 
> useage: permission and `cmdspy (playername) (-s)``cmi.customalias.cmdspy``cmi.customalias.cmdspy.others`

I enable this feature via /options for the player and it doesn't work.

**Comment by CloudeLecaw** [comment]
so you enabled it for a player and made sure he has no bypass to not get spyed?

**Comment by samparotony228** [comment]
> so you enabled it for a player and made sure he has no bypass to not get spyed? Owner Admin and OP for example would have this permission to not get spyed if you enabled it and if others disabled their spy u also have a bypass permission.

I logged in from a second account that does not have OP and does not have rights to bypass listening. Still doesn't work.

**Comment by CloudeLecaw** [comment]
> > so you enabled it for a player and made sure he has no bypass to not get spyed? Owner Admin and OP for example would have this permission to not get spyed if you enabled it and if others disabled their spy u also have a bypass permission.
> 
> I logged in from a second account that does not have OP and does not have rights to bypass listening. Still doesn't work.

it doesnt work is no answer
descripe what you have done and what you think that doesnt work, also what you defined in configs options for player?

**Comment by samparotony228** [comment]
> 


I logged into my local server with two accounts, account N has no admin rights, no OP. And the second account B has OP rights. I turn on chat listening on account A, and from the second account N I write something to the chat, but on account A it is not displayed, it is not listened to, is that clear?

**Comment by samparotony228** [comment]
Defaults:
      visibleHolograms: true
      shiftSignEdit: true
      totemBossBar: true
      bassBarCompass: true
      tagSound: true
      chatSpy: false
      cmdSpy: false
      signSpy: false
      acceptingPM: true
      acceptingTPA: true
      acceptingMoney: true

**Comment by samparotony228** [comment]
Can someone help me solve this?

**Comment by samparotony228** [comment]
Ahhh, I thought chatspy was listening to local chat, but it turns out it's listening to chat which is /msg. Damn.... in /options it says 'chatspy' that confused me...

**Comment by samparotony228** [comment]
This ticket can be considered closed. Problem solved.
