### ISSUE TITLE
TryMe Update needed - new gamemodes aren't giving rewards

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#7593]
Hi, I want to notify you that on your Github is a ticket regarding the new game mode that is useless now cause the plugin isn't giving any rewards. Multiple people have this issue, so it seems to be confirmed & it will be nice if it can be fixed. https://github.com/Zrips/TryMe/issues/18

**Comment by Zrips** [comment]
Will issue fix tomorrow to address this one and will post new version
