### ISSUE TITLE
Oraxen Placeholders in prefix create cmi error

### ISSUE THREAD

**Issue by jackboi03** [Zrips/CMI#7594]
### Description of Issue

The issue I reported in #7571 still persists after updating. @

### Version Information

```shell
[01:31:06 INFO]: CMI Plugin Version: 9.3.1.4 SqLite
[01:31:06 INFO]: CMILib: 1.2.4.5
[01:31:06 INFO]: Server: Paper(307) 1.19.2-R0.1-SNAPSHOT
[01:31:06 INFO]: CMI economy: Disabled CMI Chat: Enabled
[01:31:06 INFO]: Modules -> 56 enabled 1 disabled: votifier
```

### Errors

```shell
see issue #7571
```

### Relevant Plugins

PlaceholderAPI 2.11.2 Oraxen 1.151.0

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by jackboi03** [comment]
updated to 1.19.3 and the issue still persists.
https://pastebin.com/XRB642p7
PlaceholderAPI version 2.11.3-DEV-160
oraxen version 1.152.3
CMI version 9.3.1.6
CMILib version 1.2.4.5
This server is running Paper version git-Paper-442 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 5cc78f2)

**Comment by CloudeLecaw** [comment]
Could you retry this with an updated CMI version?
Current one is CMI 9.5.0.6 and CMILIB 1.2.5.3

**Comment by jackboi03** [comment]
I updated CMI and CMIlib o the newest versions and the issue still persists.
Here is the error the console gives me and some more info:
https://pastebin.com/8xRDv2xa
@CloudeLecaw

**Comment by Zrips** [comment]
Should be resolved with next update.
