### ISSUE TITLE
Can /fly get -s argument? And may other cmds as well?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#7597]
Hi, just asking, I think it's quick addition, can you add -s for /fly cmd, and may for the others as well?

**Comment by T14D3** [comment]
Fly has "-s"
"/fly NAME true/false -s" (Need the "true/false" for "-s" to work

**Comment by CloudeLecaw** [comment]
> Hi, just asking, I think it's quick addition, can you add -s for /fly cmd, and may for the others as well?

fly allread has -s
if you think a command needs -s and doesnt has it. pls use the discussion for that.
best might be to check the wiki + cmi checkcommand COMMANDNAME  first

**Comment by bobhenl** [comment]
OH, thanks guys!
