### ISSUE TITLE
CMI custom recipes with smithing tables not working.

### ISSUE THREAD

**Issue by Lucky0888** [Zrips/CMI#7599]
### Description of Issue

I am trying to make a sword upgrade system with Custom Recipes, and it doesn't seem to be working. The result of the recipe is supposed to be an Basic Sword named Basic Sword (lvl. 2) and has more attack damage and attack speed, and that is what shows when doing /customrecipe and looking at the recipe, but when doing the recipe in a smithing table, the result comes out as a level 1 Basic Sword, what you put into the recipe before it becomes a level 2 sword. If that description didnt make sense, here is a video.

https://user-images.githubusercontent.com/75538010/218326734-f70e6914-cfee-4950-a3de-8dae40a5245f.mp4

### Version Information

```shell
--------------------------------------------------
CMI: 9.3.1.4 SqLite-> 9.3.1.4
CMILib: 1.2.4.5 
Server: Paper(386) 1.19.3-R0.1-SNAPSHOT
CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
Modules -> 56 enabled 1 disabled: votifier
--------------------------------------------------
```

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
uhmm.. may i am blind but i dont see the issue..
you defined in the recipe
Get Item A + Iron -> Recive Item A
After it you opened smithing table
Took in Item A + Iron and the Result showed - Item A
....

Well i aspect your recipe should result in a Upgraded Item A?

**Comment by Zrips** [comment]
@Lucky0888 
looks to be issue with minecraft itself not handling properly specific items as final results in smithing tables. You can still achieve same results with basic crafting tables which could be used as work around for time being until this gets addressed, but cant really do anything from my end at the moment and entire handling is being done by Minecraft itself, we are only creating custom recipes.
