### ISSUE TITLE
Add Citizens support to Interact Commands

### ISSUE THREAD

**Issue by doitliketyler** [Zrips/CMI#760]
**Description of issue or feature request:**
The interact commands are great but it would also be nice if they worked with NPCs from the Citizens plugin. Is there any chance you could add support for this?

**Comment by LogGits** [comment]
This was added in the latest updates.

**Comment by doitliketyler** [comment]
Ok I've checked the update notes and tried the last few updates and this hasn't been mentioned nor is it an option when creating an ic command. Whats going on here?

**Comment by LogGits** [comment]
Create an ic and assign it to an entity(citizen).

**Comment by doitliketyler** [comment]
Yep, that's exactly what I tried but it keeps saying "Look at entity" like it doesn't recognize it. There are no errors in the console either. Thoughts?

**Comment by doitliketyler** [comment]
The very latest update worked for me. Thanks.
