### ISSUE TITLE
> cmi placeholders Unable to display third-party plug-ins on the server

### ISSUE THREAD

**Issue by a1424** [Zrips/CMI#7602]
### Description of Issue

Sorry, I'm a machine translator

Variable problem
It cannot be displayed on the server, but can be displayed in the game
Variables cannot be used by third-party plug-ins
It is determined that variables can be displayed with papi

### Version Information

```shell
[10:36:02 INFO]: CMI version: 9.3.1.4 SqLite->
[10:36:02 INFO]: CMILib: 1.2.4.5
[10:36:02 INFO]: server version: Purpur 1.19.3-R0.1-SNAPSHOT
[10:36:02 INFO]: CMI 经济: 启用 经济: 1.7.3-CMI CMI chat: 禁用
[10:36:02 INFO]: 模块 -> 56 已启用 1 已禁用: votifier
```

### Errors

```shell
Displayable variable in the game: MEID

The server displays%xxxxx%
```

### Relevant Config Sections

```yaml
ok
  - lp user %cmi_playtimetop_name_1% permission settemp time1 true 23h
  - lp user %cmi_baltop_name_1% permission settemp money1 true 23h
no
  - lp user %playerTop_mcMmo_1_name% permission settemp mcmmo1 true 23h
  - lp user %playerTop_playerGuildMoney_1_name% permission settemp plgm1 true 23h
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by a1424** [comment]
cmi placeholders

**Comment by a1424** [comment]
schedules.yml

**Comment by a1424** [comment]
No reply

**Comment by Zrips** [comment]
Should be resolved with latest updates
