### ISSUE TITLE
SelectionVisualizer Locale_CN.yml file has many formatting issues

### ISSUE THREAD

**Issue by TWME-TW** [Zrips/CMI#7605]
### Description of Issue

SelectionVisualizer Locale_CN.yml file has many formatting issues

Hello, I'm the author of the SelectionVisualizer Locale_ZH.yml translation file ( https://github.com/Zrips/CMI/issues/7584 )

I would like to remind you that the current SelectionVisualizer Locale_CN.yml has various errors when I compare it (I mean the original Locale_CN.yml that has not been changed by the plugin, that is, the translation that is still in the jar), resulting in some translations not being loaded in the actual It will be removed by the plugin when it is entered, or it is not actually used)
![image](https://user-images.githubusercontent.com/65117253/219392803-2ace8c4d-92e3-4cd3-8776-56cd1fa57f34.png)

### Version Information

```shell
Selection Visualizer 3.2.1.0
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Some changes have been applied and structure of the file changed, you might want to look into latest EN version from plugins folder which will be more up to date. Will make small changes in your file to work more properly, but some things will be still missing. 
Main change was renaming of modePlaces into modeNames
