### ISSUE TITLE
Mentions/tag chat issue while using gradient colors like {#e60000}

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#7606]
### Description of Issue

It all started when I was informed that I should not use gradient in the GroupFormat however if I don't use gradent there but in the GroupMessageFormat, if I decide to Mention someone I will have colour as set in the GroupFormat not GroupMessageFormat, I am assuming that while doing mentions it just gets colour from GroupFormat but not GroupMessageFormat however I do want to use gradient.

To make sure that it's not other plugin I had limited myself and while testing I only used as following:
WorldGuardExtraFlags
worldguard-bukkit-7.0.8-SNAPSHOT-dist
LuckPerms-Bukkit-5.4.58
FastAsyncWorldEdit-Bukkit-2.5.2
And I had same issues.
Image: (The first message of me was when {#e60000} was set in the GroupFormat, as soon I as change to &c and reload it and had the:   GroupMessageFormat: set to '100': '{#e60000}{message}' it brake, if I message normal without the mention it works like it should.
![image](https://user-images.githubusercontent.com/1558228/219815711-f02f5576-8957-4f0e-87cd-f903b646f991.png)
I had tested version: 9.5.0.1 and it's same issue. 

### Version Information

```shell
[Sat 00:16:41 INFO] --------------------------------------------------
[Sat 00:16:41 INFO] CMI: 9.3.1.5 BungeeCord CMIB  MySQL
[Sat 00:16:41 INFO] CMILib: 1.2.4.5 
[Sat 00:16:41 INFO] Serwer: Purpur 1.19.3-R0.1-SNAPSHOT
[Sat 00:16:41 INFO] CMI ekonomia: Włączone Skrytka: 1.7.3-CMI CMI Chat: Włączone 
[Sat 00:16:41 INFO] Moduły -> 46 aktywne 11 nieaktywne: cuffed, disabledEnchants, ranks, versionCheck, moneyCheque, skin, noTarget, namePlates, timedCommands, homeInteractions, totemBehavior
[Sat 00:16:41 INFO] --------------------------------------------------
```

### Relevant Config Sections

```yaml
# ATTENTION! Dont use gradient colors for {message} variable, if you want to apply gradient for it, utilize GroupMessageFormat section
  GroupFormat:
    '100': '{suffix}{prefix}{displayName}&e: &c{message}'
    '99': '%marriagemaster_prefix%{suffix}{prefix}{displayName}&e: &c{message}'
    '98': '%marriagemaster_prefix%{suffix}{prefix}{displayName}&e: {message}'
    '97': '%marriagemaster_prefix%{suffix}{prefix}{displayName}&e: &a{message}'
    '96': '%marriagemaster_prefix%{suffix}{prefix}{displayName}&e: &b{message}'
    '95': '%marriagemaster_prefix%{suffix}{prefix}{displayName}&e: &b{message}'
    '94': '%marriagemaster_prefix%{suffix}{prefix}{displayName}&e: &b{message}'
    '21': '%marriagemaster_prefix%{suffix}{prefix}{displayName}&e: {message}'
    '20': '%marriagemaster_prefix%{suffix}{prefix}{displayName}&e: &6{message}'
    '19': '%marriagemaster_prefix%{suffix}{prefix}{displayName}&e: &6{message}'
    '7': '%marriagemaster_prefix%{suffix}{prefix}{displayName}&e: &d{message}'
    '6': '%marriagemaster_prefix%{suffix}{prefix}{displayName}&e: &e{message}'
    '4': '%marriagemaster_prefix%{suffix}{prefix}{displayName}&e: &e{message}'
    '3': '%marriagemaster_prefix%{suffix}{prefix}{displayName}&e: {message}'
    '2': '%marriagemaster_prefix%{suffix}{prefix}{displayName}&e: &6{message}'
    '1': '%marriagemaster_prefix%{suffix}{prefix}&e{displayName}&e: &f{message}'
  # Use numeric increments to separate groups from each other. If player has more than one, then line with higher number will be used
  # Add as many lines as you need too
  # cmi.chatmessagegroup.[id] permnission node to use
  # Permission example: cmi.chatmessagegroup.2
  GroupMessageFormat:
    '100': '{#e60000}{message}'
    '98': '{#8f9fdd}{message}'
    '21': '{#9968D3}{message}'
    '3': '{#e67c00}{message}'
```

### Relevant Plugins

vault 1.7.3

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update. There is still an issue with gradient usage as it causes more complications while handling player tagging and gradient messages at same time.
