### ISSUE TITLE
Delay in Custom Text files

### ISSUE THREAD

**Issue by CallMeSparky1911** [Zrips/CMI#7607]
I am using CMI to display a "welcome message" or "MOTD" when a player joins the server. However in the custom text file, I have placeholders from other plugins such as: Battlepass, lands etc. Some of the placeholders do not show a valid value due to when the server activates the welcome message it is before it registers the player user name.

If I am in the game and manually open the MOTD custom text file, the placeholders all show a valid value. Is there anyway to delay a placeholder value or just delay the welcome message by a number of ticks or seconds when a player joins?

**Comment by CloudeLecaw** [comment]
well if you need a delay i recomment not using the modt of config.
use EventCommand.yml
```
joinServer:
  Enabled: true
  Commands:
  - delay! 1
  - cmi ctext NameOfCText [playerName] ```
