### ISSUE TITLE
CMIPlayTime#getPlayTime always returns 0, even when in-game CMI's /playtime shows actual time

### ISSUE THREAD

**Issue by ItsTomKo** [Zrips/CMI#7617]
### Description of Issue

Hey!
Whenever I try to get Player's Playtime programmatically, it returns 0.

Test Command:
`@Override
    public boolean execute(@NotNull CommandSender sender, @NotNull String commandLabel, @NotNull String[] args) {
        Player p = (Player) sender;
        CMIUser user = CMIUser.getUser(p);
        CMIPlayTime pt = user.getCMIPlayTime();

        sender.sendMessage(String.valueOf(pt.getPlayTime(PlayTimeManager.PlaytimeRange.total)));
        return false;
    }`

![image](https://user-images.githubusercontent.com/87188560/220445735-0da3aee3-b828-4ad9-b5ac-2d271dc3ae2a.png)

Thanks for help!
TomKo

### Version Information

```shell
--------------------------------------------------
CMI: 9.3.0.2 BungeeCord CMIB  SqLite-> 9.3.1.5
CMILib: 1.2.4.5
Server: Paper(138) 1.19.2-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Disabled
Modules -> 56 enabled 1 disabled: votifier
--------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
CMIPlayTime is separate playtime tracking which tracks player activity by each hour, this feature is disabled by default as it does collect quite a bit of data. So it will return 0. 
What you are looking for would be user.getTotalPlayTime() which will return players playtime as recorded by statistics or player data file, depending on config option.
