### ISSUE TITLE
[Feature] Money transactions

### ISSUE THREAD

**Issue by MrMorganCz** [Zrips/CMI#762]
Odesílatel: (Sender:)
Příjemce: (Recipient)
Pohyb: (the amount transferred)
Zůstatek: (Balance)
Datum: (Date)
Popis platby: (Transaction description)

Sample here: https://imgur.com/a/jsnC6Q6

**Comment by LogGits** [comment]
If this is added, it should be added in a separate database table that logs transactions. This feature should also be optional and toggled off by default. Nonetheless, a great idea 👍
