### ISSUE TITLE
Money will not sync on 2 server

### ISSUE THREAD

**Issue by Leahcimkrob** [Zrips/CMI#7623]
### Description of Issue

how do I get it out that I have the CMI player data on 2 servers. I have our citybuild and want the same money on the farm server too. Both servers access the MySQL DB. If I switch servers, the money is only correctly synchronized after a restart. Why is it that the two servers on one account are not synchronizing? If I earn money on the CB and then go to the farm server, it's in the MySQL, but I don't have it in the farm server and vice versa.

If I give me 100 money on 1.st server and go to the 2.nd Server, the 100 money are in the MySQL-Database, but I get this not on the 2. Server. 

What is a MySQL database for if it is not at least read when entering the server?

### Version Information

```shell
[17:02:33 INFO]: --------------------------------------------------
[17:02:33 INFO]: CMI Plugin Version: 9.3.1.5 BungeeCord CMIB  MySQL
[17:02:33 INFO]: CMILib: 1.2.4.5
[17:02:33 INFO]: Server: Paper(383) 1.19.3-R0.1-SNAPSHOT
[17:02:33 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
[17:02:33 INFO]: Modules -> 55 enabled 2 disabled: tablist, armorstand
[17:02:33 INFO]: --------------------------------------------------
```

### Errors

```shell
NO error in Console
```

### Relevant Config Sections

```yaml
storage:
  # storage method, can be MySQL or sqlite
  # ATTENTION! DON'T USE SAME DATABASE TABLES FOR MORE THEN ONE SERVER, YOU WILL HAVE UNEXPECTED ISSUES. EACH SERVER SHOULD HAVE ITS OWN DATABASE TABLE SETUP
  method: MySQL
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
As stated near database type setup, you cant have same database on multiple servers. Data sync between servers will not work without having specialized economy bridge plugin. 
![image](https://user-images.githubusercontent.com/10416201/220698399-5cb30dd3-b774-4a6f-abbc-47270997e8c2.png)

**Comment by Leahcimkrob** [comment]
We use now mpdb, but got an other Problem with Money-Sync.
Why do we actually get deductions of money through the shop with the Quickshop, the MySQL-PlayerDatabridge and CMI, although this is handled by CMI according to the MPDB.
I've attached a screen for it.

![WhatsApp Bild 2023-02-25 um 17 59 48](https://user-images.githubusercontent.com/70509359/221373564-3bb3d058-dd20-4dc9-b6d4-3d8af3c7efdc.jpg)

**Comment by Leahcimkrob** [comment]
![Bild1](https://user-images.githubusercontent.com/70509359/221374470-e76ae5de-398e-4130-88f8-7aa086237a6e.jpg)
