### ISSUE TITLE
/cmi jump not working on nether roof.

### ISSUE THREAD

**Issue by TheBadshah** [Zrips/CMI#7627]
### Description of Issue

On doing /jump | /cmi jump while being on/above nether roof it doesn't lets you jump to the block you are looking at 
![image](https://user-images.githubusercontent.com/116473315/220971906-37694059-8589-476d-8a9b-2131b96d815a.png)
![image-1](https://user-images.githubusercontent.com/116473315/220971935-4d568315-dfb5-49a1-8b0e-0635433638c3.png)

### Version Information

```shell
{added image}
```

### Errors

```shell
{added image}
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version
