### ISSUE TITLE
Glow color sync between some players

### ISSUE THREAD

**Issue by LeFouTrolleur** [Zrips/CMI#7629]
### Description of Issue

Some players have their glow synced. Indeed if one changes color with the /cmi glow, the other will have the same color. 

### Version Information

```shell
CMi: 9.3.1.5
CMi Lib: 1.2.4.5
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
This can happen if you have another plugin which regulates player teams, CMI will default to one and will use players existing team which in some situations can be same one as another player. There is no good way to manage teams at the moment without creating issues with other plugins. In cases when you don't have another plugin managing teams then CMI will create dedicated team per player which will avoid creating issues like that.
