### ISSUE TITLE
[FEATURE] HologramClick Event

### ISSUE THREAD

**Issue by Ste3et** [Zrips/CMI#763]
**Description of issue or feature request:**
Can you please add a custom event to your holograms if a plyer rightclick it to suggest some own features. I worked with your holograms to make my shop look better ;D but the problem is my players cannot pay anything from the hologram shop.

Best regrads Ste3et_C0st

**Cmi Version (using`/cmi version`):** 
8.0.7.0

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.13-R01

**Comment by LogGits** [comment]
Cmi holograms are created at the packet level. Meaning it would only be rendered to the client.
