### ISSUE TITLE
Unjail Commands not get Triggered

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7630]
### Description of Issue
When we unjail someone the command defined in config for onUnjail dont get triggered

### Version Information
![Snag_1e7bfe4](https://user-images.githubusercontent.com/12080017/221300490-13e2c7bd-24c8-4886-84cf-e1bce110e476.png)

### Errors
```shell
None in Console
```

### Relevant Config Sections

```yaml
   # Commands to be performed when player gets unjailed
    OnUnJail:
    - asConsole! pex user [playerName] group remove Gefangener
    - check:%phc_[playerName]pexrang%==VIP|VIPV|VIPmini|TestVIP! asConsole! pex user [playerName] group add Spieler
    - delay! 1
    - asConsole! pex user [playerName] group add %phc_[playerName]pexrang%
    - asConsole! phc removesilent [playerName]pexrang
    - delay! 1
    - asConsole! cmi tablistupdate
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Hard to say, I would suggest to test it with custom alias feature to make sure that all those checks actually pass and I am not sure if this is correct format for your placeholder or just issue if paste in here, but is this correct placeholder format? `%phc_[playerName]pexrang%`

**Comment by CloudeLecaw** [comment]
na the placeholder is fine and saved the correct value also it was saved correct in my plugin and papi prases it correct to. 

i aslo tested just sending a msg in the unjail section ````
cmi msg [playerName] Test```
 but it was not working on unjail the player did not get the meassage test

**Comment by Zrips** [comment]
Checked code, looks to be a potential issue when you don't have unjail location set for that jail, basically location where player should have been teleported after unjail, if that one was not set then commands would have been skipped too. Will fix that one. If this fixes your issue then it's all good, if not, let me know with new ticket, for now closing this ticket.

**Comment by CloudeLecaw** [comment]
Issue is fixed <3

Thank you for fixing it
