### ISSUE TITLE
Flight problem with StrikePractice

### ISSUE THREAD

**Issue by kforbro** [Zrips/CMI#7637]
### Description of Issue

After death, the player turns on the flight for spectating the duel, after exiting spectating, it should turn off, but this does not happen and the players fly on spawn. There is no such problem in the old version of CMI 9.3.0.5, it appeared after upgrading to 9.3.1.5

In addition, I noticed that one player has a fly on the survival server, although he does not have the permissions to do so. It is after the CMI update. In this case, I do not know the bug algorithm

### Version Information

```shell
https://i.imgur.com/usdPerQ.png
```

### Errors

```shell
none
```

### Relevant Plugins

StrikePractice 3.7.0

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by kforbro** [comment]
maybe same #7625

**Comment by RouvbX** [comment]
i have the same issue as you

**Comment by Zrips** [comment]
Will be removing big chunk of fly handling introduced in recent versions as it seems to be causing more issues than it actually solved
