### ISSUE TITLE
mpdb got an Problem with Money-Sync

### ISSUE THREAD

**Issue by Leahcimkrob** [Zrips/CMI#7638]
### Description of Issue

We have confusing values in the database, the Databridge, which in turn adds or subtracts inexplicable balance values.
According to the QS shop and Databridge, you should do everything in economy, so I'll ask the question here.

We use now mpdb, but got an other Problem with Money-Sync.
Why do we actually get deductions of money through the shop with the Quickshop, the MySQL-PlayerDatabridge and CMI, although this is handled by CMI according to the MPDB.
I've attached a screen for it.
![221374470-e76ae5de-398e-4130-88f8-7aa086237a6e](https://user-images.githubusercontent.com/70509359/221421021-57c1e4ec-20e7-4ee1-b620-0d7b28e89099.jpg)
![221373564-3bb3d058-dd20-4dc9-b6d4-3d8af3c7efdc](https://user-images.githubusercontent.com/70509359/221421024-81385c1c-9b4e-40cc-bf22-c791eb18e11d.jpg)

### Version Information

```shell
[17:02:33 INFO]: --------------------------------------------------
[17:02:33 INFO]: CMI Plugin Version: 9.3.1.5 BungeeCord CMIB  MySQL
[17:02:33 INFO]: CMILib: 1.2.4.5
[17:02:33 INFO]: Server: Paper(383) 1.19.3-R0.1-SNAPSHOT
[17:02:33 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
[17:02:33 INFO]: Modules -> 55 enabled 2 disabled: tablist, armorstand
[17:02:33 INFO]: --------------------------------------------------
```

### Errors

```shell
no error in console
```

### Relevant Plugins

MySQl Player Data Bridge, Quickshop

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Maybe I am confused, but, CMI has no money sync between servers. If you use a third party plugin to make that happen, then THAT plugin has to support CMI and QuickShop both to properly make this happen, I assume? Not sure what CMI can do here for you.

**Comment by Leahcimkrob** [comment]
According to the Quickshop dev, everything about Economy runs through you. Since negative values appear in the data bridge, which appear to be faulty and often repeat themselves, I first assume an error in the economy system. So I put it here.

**Comment by Zrips** [comment]
CMI will handle economy requests as they should be handled, deducting or giving money to player will be done in basic arithmetic method, if 3rd party plugin wants to give negative amount then player will actually lose money at the end of transaction as its just basic arithmetics. Can't really say what exactly is going on here, but this looks to be an issue with Quickshop or PlayerDatabridge or both of them not cooperating properly.
