### ISSUE TITLE
Users with all number names do not work in commands

### ISSUE THREAD

**Issue by livelaughlemon** [Zrips/CMI#7642]
### Description of Issue

When running a command targeted at a user with all numbers in their name, it says no player is found. (ex /donate 37733333 results in “Player not found” when they are online)

https://cdn.discordapp.com/attachments/1015825972248969287/1079727442060640276/IMG_4425.png

https://media.discordapp.net/attachments/1015825972248969287/1079727442454925332/IMG_4424.png

### Version Information

```shell
CMI: 9.3.1.5 (SQLite)
CMILib: 1.2.4.3 -> 1.2.4.5
Server: Purpur 1.19.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI(CMIEInjector) CMI chat: Disabled
Modules -> 56 enabled 1 disabled: spawners
```

### Errors

```shell
Can’t find player with this name! (/donate 37733333)
```

### Relevant Plugins

Vault: 1.7.3-CMI(CMIEInjector)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version
