### ISSUE TITLE
Server Crash on Latest version of CMI

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#7650]
### Description of Issue

Server Crashes on latest version of CMI. Based on the latest logs and crash error reports, I thought it was Citizens2 that was the cause, but when I consulted with them, they said its a CMI Issue.

I have tried removing CMI and starting up the server works, which is odd.  Therefore, I believe it got to do something with CMI.

More info. Running latest version of:
PaperSpigot - Build 431 (1.19.3)
ProtocolLib - Build 614 (1.19.3)
Citizens 2 - Build 2.0.30-b2954
CMI - 9.3.1.6
CMI Lib - 1.2.4.5 

### Version Information

```shell
Unable to provide, as the server crashes on startup. But running `CMI 9.3.1.6`
```

### Errors

```shell
https://mclo.gs/AHpNs8K
```

### Relevant Config Sections

```yaml
Not at the moment.
```

### Relevant Plugins

Citizens-2.0.30-b2954

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will address with next CMI and CMILib updates, tho no idea why would FabledSkyBlock have dependency on CMIInjector which should generally not happen and this one loads way before any other plugin. This can be fully resolved by FabledSkyBlock removing dependency of CMIInjector or you can manually edit FabledSkyBlock file by opening it and editing plugin.yml file where you would only need to remove CMIInjector record from it to get this working.
