### ISSUE TITLE
Placeholders only work when coming from cmi

### ISSUE THREAD

**Issue by Amph1dian** [Zrips/CMI#7660]
### Description of Issue

For example, i have a customalias that does 'asConsole! discordsrv broadcast `%cmi_baltop_name_1%` - `%cmi_baltop_money_1%`' and it works just fine when using the command. BUT, if i do the exact same command in the console, the placeholders are blank. 

https://user-images.githubusercontent.com/64792971/223768640-2f346ae9-1467-4beb-bd6b-99c8fc31d57e.mp4

This is an issue for me because i have a plugin called "discordsrvutils" that has a feature where it updates a embed with the server stats. im trying to make a baltop inside of that embed, but when i use cmi placeholders, its just blank.

i know this is an issue with cmi because i can use other expansions from papi and they work fine in discordsrv. its only cmi placeholders that dont work when by themselfs.

### Version Information

```shell
CMI: 9.3.2.0 SqLite-> 9.3.1.6
 CMILib: 1.2.4.6 
 Server: Purpur 1.19.3-R0.1-SNAPSHOT
 CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
 Modules -> 32 enabled 25 disabled: spawnerProximity, cuffed, mirror, versionCheck, skin, elytraBoost, rideAnimation, elytraLaunch, bossBarCompass, votifier, headDrop, spawnerCharge, homeInteractions, launchPad, jail, spawners, paintingEditor, durabilityLoss, kits, flightCharge, worldLimitsElytra, ranks, sitAnimation, silentChest, totemBehavior
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Amph1dian** [comment]
accidentally closed

**Comment by Zrips** [comment]
Should be fixed with next update
