### ISSUE TITLE
bperm does not work for creating holograms

### ISSUE THREAD

**Issue by T14D3** [Zrips/CMI#7663]
### Description of Issue

Greetings,
The bperm:! specialized command does not work when trying to use it to create holograms.

Setup:
Custom Alias or AttachedCommand:
`bperm:cmi.command! cmi hologram new Test`

Alias can only execute when the player has `cmi.command.hologram` set to true, it does not work when he only has `cmi.command`, which is what bperm should allow

### Version Information

```shell
CMI: 9.3.2.0 SqLite
CMILib: 1.2.4.6 
Server: Paper(445) 1.19.3-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
Modules -> 56 enabled 1 disabled: votifier
```

### Errors

```shell
None
```

### Relevant Plugins

None

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by T14D3** [comment]
![image](https://user-images.githubusercontent.com/73843330/224135634-af4667a8-3400-4c00-b2c7-f53a28d5baf5.png)

Another example, #1 returns "No Permission"-Message, #2 works with no issues

**Comment by Zrips** [comment]
bperm allows you to bypass permission requirement for  following command, when you are using it for hologram command you need to bypass cmi.command.hologram permission requirement, this might not apply for ctellraw if player already has access to cmi.command.ctellraw
