### ISSUE TITLE
clear commands doesnt work correcly with its cleartypes

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7668]
### Description of Issue

The clear command offer different cleartypes. Well i tried it with mainhand type result was the item gets taken  from first found inventory slot instead of the mainhand.
```
cmi clear (playerName) (item(-amount)) (-s) (+clearType)
Clear Types:
+quickbar
+inventory
+partinventory
+weapons
+armorslots
+tools
+armors
+mainhand
+offhand
```

![Snag_177ca45](https://user-images.githubusercontent.com/12080017/224559595-6531f0f9-5e95-477c-a3e5-e0150347df00.png)

### Version Information
![Snag_16f7e9d](https://user-images.githubusercontent.com/12080017/224558953-6d505e67-f2a4-47d1-85ff-17104c857699.png)

### Errors

```shell
No errors in Console
```

### Relevant Config Sections

```shell
no relemvant connfig sections
```

### Relevant Plugins
```shell
none its the cmi command itself.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Clear types are on same level as clearling by material type, this means that you can only do one or the other. If you clear by type then defined inventory type will be completely cleared out, if you define material then this takes priority and defined material will be taken away without any priority from your defined inventory types. This would be more of a enhancement than a bug if behavior like this is really needed.
