### ISSUE TITLE
[Feature] Disable Entity Targeting

### ISSUE THREAD

**Issue by Feeriix** [Zrips/CMI#767]
**Description of issue or feature request:**

A permission/command to turn off entity targeting/following players.
This is useful for new players so that monsters don't target them (for a set time).

**Comment by CloudeLecaw** [comment]
Like friendly monsters or when your in gm1? Nice idea, specialy for worlds where u just want to build

**Comment by Zrips** [comment]
Next update /cmi notarget (playerName) (true/false) (-s)
