### ISSUE TITLE
LoginCustom: The message cannot be customized

### ISSUE THREAD

**Issue by yuankun1** [Zrips/CMI#7674]
### Description of Issue

  LogoutCustom: ' &6[playerDisplayName] &eleft the game'
This LoginCustom: ' &6[playerDisplayName] &ejoined the game' custom message
is useless 

### Version Information

```shell
CMI-9.3.2.0
```

### Errors

```shell
null
```

### Relevant Config Sections

```yaml
null
```

### Relevant Plugins

1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Here's my documentation on how to do it, and customizing works (using it live now)

https://faq.cmi.support/joinleave

**Comment by yuankun1** [comment]
> 这是我关于如何做到这一点和自定义作品的文档（现在使用它）
> 
> https://faq.cmi.support/joinleave

I mean.
 I changed the LoginCustom: prompt in the Locale_CN and it still shows &6[playerDisplayName] &ejoined the game
It doesn't prompt LoginCustom: '&7[&a+&7] &6[playerDisplayName] &e to join the game I modified the prompt

**Comment by yuankun1** [comment]
> 这是我关于如何做到这一点和自定义作品的文档（现在使用它）
> 
> https://faq.cmi.support/joinleave

OK
