### ISSUE TITLE
First Homepoint is missing in HomeGUI

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7683]
### Description of Issue

Wen you do /cmi home you normaly get the GUI where all Homes are listed.
Current all players miss the first homepoint they set.
To get them they can do /cmi home TAB

![Snag_26f8ebc](https://user-images.githubusercontent.com/12080017/226073054-d185ea62-c151-45d2-980e-6189c493d7b4.png)
![Snag_26f74db](https://user-images.githubusercontent.com/12080017/226073046-90632acc-e93a-4e41-a74e-a44f85cda043.png)
![Snag_270ab67](https://user-images.githubusercontent.com/12080017/226073115-8aa6e989-5fd0-4bbc-8880-c1234aee8cdf.png)
The GUI sais 13 - it are 13 but GUI just shows 12
the chatlist lists all 13correct

### Version Information
![Snag_26e418b](https://user-images.githubusercontent.com/12080017/226072980-5e08a36a-7633-4b8f-90e4-383060a2c8fa.png)

### Errors
none in console

### Relevant Config Sections
none

### Relevant Plugins
none

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by KageRyo** [comment]
The author has already fixed this issue in the latest version of CMI, #7678  .

**Comment by Zrips** [comment]
Fixed with latest versions, might have forgotten to mention it in patch notes.

**Comment by CloudeLecaw** [comment]
i also noticed that. i wasnt just sure if this was because of updating cmi or because of updating to paper 1.19.4 ;3
