### ISSUE TITLE
Sell GUI not return shulkerbox which has items inside

### ISSUE THREAD

**Issue by nhanledev** [Zrips/CMI#7684]
### Description of Issue

Shulkerboxes are not listed in `worth.yml` file, which means the server does not allow to sell any shulkerbox.

There is 2 cases:
1. If you put an empty shulkerbox into the sell GUI, when menu is closed that shulker box is returned (expected).
2. IF you put an shulkerbox that has items inside (not empty), when menu is closed that shulkerbox is deleted (bug).

### Version Information

```shell
CMI-9.4.0.2
CMILib1.2.5.2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version
