### ISSUE TITLE
Only english language in v9.4.0.0

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#7685]
### Description of Issue

The language files are not working since version 9.4.0.0

### Version Information

```shell
**CMI Version: 9.4.0.2**
**Server Type: PaperMC**
**Server Version: 1.19.3 #448**
**Vault Version: 1.7.3**
```

### Errors

```shell
Nothing
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
We did had some changes for locale handling which related to custom locales. Could you elaborate more on which locale are you using and does it not work in all places or just specific ones?

**Comment by Zrips** [comment]
Ok, this clarifies things, will address this issue with next update
