### ISSUE TITLE
Unable to allow for Login/Quit messages regardless of permissions

### ISSUE THREAD

**Issue by ParadiddlePride** [Zrips/CMI#772]
Hi there, I seem to be unable to allow myself to have a login/logout message pop up, despite (presumably) having set up the permissions correctly. I previously had the * permission for my "owner" group, but removed it and instead just gave myself cmi.*, then set cmi.messages.disablelogin and cmi.messages.disablequit to false. I still don't have login or logout messages, though.

It's likely I've done something wrong somewhere, so only provided a few things below, unsure what else is needed/relevant.

Printout from console to list the Owner group's permissions:
```
27.08 00:03:43 [Server] INFO ParadiddlePride issued server command: /cmi version
27.08 00:05:16 [Server] INFO [LP] owner's Permissions:  (page 1 of 1 - 6 entries)
27.08 00:05:16 [Server] INFO > cmi.* (true)
27.08 00:05:16 [Server] INFO > coreprotect.* (true)
27.08 00:05:16 [Server] INFO > herochat.force.leave.* (false)
27.08 00:05:16 [Server] INFO > luckperms.* (true)
27.08 00:05:16 [Server] INFO > cmi.messages.disablelogin (false)
27.08 00:05:16 [Server] INFO > cmi.messages.disablequit (false)
```
Copy of my CMI config:
https://pastebin.com/pG1yKWHF

**Cmi Version (using`/cmi version`): 8.0.7.0 ** 

**Server Type (Spigot/Paperspigot/etc): Spigot** 

**Server Version (using `/ver`): CraftBukkit version git-Spigot-fe3ab0d-ec86574 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT) **

**Comment by FoxWithSox** [comment]
Ive been having this issue too for about a month and im using PEX

**Comment by CloudeLecaw** [comment]
https://github.com/Zrips/CMI/issues/732
