### ISSUE TITLE
[Request] Open Shulker Box silently when vanished or /silentchest is True

### ISSUE THREAD

**Issue by WOo0W** [Zrips/CMI#773]
I found that /silentchest is not working for Shulker Box. Could you add support for this?

**Cmi Version (using`/cmi version`):** 
8.0.7.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
git-Spigot-fe3ab0d-f41aae4

**Comment by x1p** [comment]
I would like to be able to edit all chests in vanish. Even with interact on, it's not possible to take/put items in/out chests at this moment.

**Comment by x1p** [comment]
No it does not

> Even with interact on, it's not possible

**Comment by Zrips** [comment]
Support will be added with next build
