### ISSUE TITLE
Sit Bug

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#774]
**Description of issue or feature request:**
When players sit and stand up they will drop down 1 block.
It can use for escape

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**Cmi Version (using`/cmi version`):** 
8.0.7.0
**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
1.12.2

**Comment by Gasha666** [comment]
Yeah, this bug is confirmed, when player standup with shift it falls 1 block in floor and if its empty floor (whole in ground) he will fall into that and be able to die

i tested old version and latest, there is no bug in older version, only in latest

**Comment by Zrips** [comment]
Should be ok with latests builds.
