### ISSUE TITLE
Feed all / Heal all includes vanished players

### ISSUE THREAD

**Issue by destial** [Zrips/CMI#7742]
### Description of Issue

When I am in vanished, my donors can do /feed all or /heal all and see that I am online. Is this intended? If so, would like an option in the config to disable.

### Version Information

```shell
CMI: 9.5.0.1 BungeeCord CMIB  SqLite-> 9.5.0.2
CMILib: 1.2.4.5 -> 1.2.5.2
Server: Pufferfish 1.19.3-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Enabled 
Modules -> 57 enabled 1 disabled: tablist
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
