### ISSUE TITLE
GUI of /homes is bug

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#7754]
### Description of Issue

Since a few versions, I noticed that there was a hole at the bottom left of the `/homes' interface.
![image](https://user-images.githubusercontent.com/75265787/230720525-c1414c74-a22a-4378-9570-84011c438884.png)

### Version Information

```shell
CMI: 9.5.0.4 MySQL
CMILib: 1.2.5.2
Server: Purpur 1.19.4-R0.1-SNAPSHOT
CMI economy: Activée Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Activée
Modules -> 18 enabled 40 disabled: spawnerProximity, cuffed, mirror, tablist, versionCheck, armorEffects, moneyCheque, skin, noTarget, rideAnimation, bossBarCompass, playerCombat, votifier, shulkerBackpack, cooldown, headDrop, spawnerCharge, vanish, namePlates, timedCommands, homeInteractions, hpBossBar, launchPad, portals, anvilRenameColor, jail, spawners, dynamicSigns, durabilityLoss, kits, flightCharge, deathMessages, disabledEnchants, worldLimitsElytra, worldLimits, ranks, selection, sitAnimation, warmup, totemBehavior
```

### Errors

```shell
No errors.
```

### Relevant Config Sections

```yaml
https://pastebin.com/8c96Sb8Q
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
i checked out homes GUI today and didnt see any missing fillout fields... 
Could you retry this with CMI9.5.0.6 and CMILIB 1..2.5.3 + Recheck that you havent places an invailed icon in Homes.yml into that slot?

**Comment by Ergail** [comment]
Hi, I have tried the different manipulations suggested and others and I still have the problem. Using the latest versions of CMI and CMILib. When I have more than 33 homes the empty icon is replaced by a home, like a normal slot.

**Comment by Zrips** [comment]
Will be fixed with next update
