### ISSUE TITLE
[item] not displaying when you have cmi.chatmessagegroup perm

### ISSUE THREAD

**Issue by NightLife-SG** [Zrips/CMI#7756]
### Description of Issue

as describe with title

### Version Information

```shell
[Sun 03:37:56 INFO] --------------------------------------------------
[Sun 03:37:56 INFO] CMI: 9.5.0.4 SqLite
[Sun 03:37:56 INFO] CMILib: 1.2.5.2 
[Sun 03:37:56 INFO] Server: Paper(499) 1.19.4-R0.1-SNAPSHOT
[Sun 03:37:56 INFO] CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Enabled 
[Sun 03:37:56 INFO] Modules -> 52 enabled 6 disabled: spawnerProximity, tablist, skin, spawners, spawnerCharge, paintingEditor
[Sun 03:37:56 INFO] --------------------------------------------------
```

### Errors

```shell
no error in console
```

### Relevant Config Sections
![image](https://user-images.githubusercontent.com/84533050/230752911-30ebde81-3719-4b7e-997d-a8c5afd92f34.png)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
if no permission set the get your format from general format.
 might this happens because our using colors or gradiant?
waht happens if you set all to the original: {message} ?

Well but still then this would be a bug ;)

could you check the diffences of your   GeneralMessageFormat:   and     GroupMessageFormat:  ?

**Comment by mrfloris** [comment]
9.5.0.6 might have this resolved, let us know if you still have this issue.

**Comment by NightLife-SG** [comment]
issue still persist

**Comment by NightLife-SG** [comment]
[Sun 05:56:17 INFO] --------------------------------------------------
[Sun 05:56:17 INFO] CMI: 9.5.0.7 SqLite
[Sun 05:56:17 INFO] CMILib: 1.2.5.3 
[Sun 05:56:17 INFO] Server: Paper(511) 1.19.4-R0.1-SNAPSHOT
[Sun 05:56:17 INFO] CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Enabled 
[Sun 05:56:17 INFO] Modules -> 52 enabled 6 disabled: spawnerProximity, tablist, skin, spawners, spawnerCharge, paintingEditor
[Sun 05:56:17 INFO] --------------------------------------------------

**Comment by CloudeLecaw** [comment]
might have a plugin like AntiPopUp? Or NoChatReport?    Plugins like this mofy the chat output but sadly destory the gradiant meaasage output from cmi.

**Comment by Zrips** [comment]
Issue with gradient colors for chat messages itself. Fix is to add new regex expression while detecting this particular word in chat. Go to chat.yml and under ItemRegex section add this
`(([&§]\S)+)?\[(([&§]\S)+)?i(([&§]\S)+)?t(([&§]\S)+)?e(([&§]\S)+)?m(([&§]\S)+)?\]`
will add this to default config with next update, tho it will not update existing files.

**Comment by CloudeLecaw** [comment]
> Issue with gradient colors for chat messages itself. Fix is to add new regex expression while detecting this particular word in chat. Go to chat.yml and under ItemRegex section add this `(([&§]\S)+)?\[(([&§]\S)+)?i(([&§]\S)+)?t(([&§]\S)+)?e(([&§]\S)+)?m(([&§]\S)+)?\]` will add this to default config with next update, tho it will not update existing files.

is this regex missing a ) somewhere at the end? i was wondering because it started with (( but didnt finished with ]...
