### ISSUE TITLE
CMI Placeholders incorrect

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#776]
**Description of issue or feature request:**

Placeholders   {cmi_user_rank} and {cmi_user_nextranks} are wrong.

{cmi_user_rank} shows the previous rank.
{cmi_user_nextranks} shows your current rank.

This didn't happen before, so it must have been caused by a newer update.

**Cmi Version (using`/cmi version`):**  8.0.7.0

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):**  Spigot 1.12.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
CMI rank requirements are what you need to rank up to that particular rank so placeholders shows you accurate information as this is how it is working.
