### ISSUE TITLE
God mode is not stopping hunger

### ISSUE THREAD

**Issue by SnowBlitzz** [Zrips/CMI#7763]
### Description of Issue

God mode (/god) should be preventing players from getting hungry but it doesn't seem to be doing that. 

### Version Information

```shell
CMI: 9.3.2.0 SqLite-> 9.5.0.4CMILib: 1.2.4.6 -> 1.2.5.2Server: 1.16.5 1.16.5-R0.1-SNAPSHOTCMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: EnabledModules -> 41 enabled 16 disabled: spawnerProximity, mirror, armorstand, moneyCheque, jail, spawners, dynamicSigns, bossBarCompass, deathMessages, disabledEnchants, ranks, votifier, attachedCommands, spawnerCharge, namePlates, totemBehavior
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
could you reproduce this on CMI 9.5.0.6 and CMILIB 1.2.5.3?

**Comment by SnowBlitzz** [comment]
Since it was not mentioned in the changelogs, I would assume it's still bugged. 

Went ahead and tested it anyway, and yes I can reproduce it on CMI 9.5.0.6 and CMILIB 1.2.5.3

**Comment by Zrips** [comment]
While god mode is activated your food level should not change, this will not apply to saturation tho. Just double check if this is actually an issue as of testing hunger isint being lowered. You can check your current hunger with **/cmi info** command by hovering over Survival section, running around with spring and jumping would consume hunger quite rapidly.

**Comment by SnowBlitzz** [comment]
Why was this closed? 
God mode enabled (hunger at 11)
![image](https://user-images.githubusercontent.com/7488382/233013972-0ed2f852-07a9-4869-8cca-3b4e3ea4a9a7.png)
After running around for a bit (hunger at 9)
![image](https://user-images.githubusercontent.com/7488382/233014098-45a40f4b-f4d6-4970-9420-9fb7e83421a2.png)

**Comment by mrfloris** [comment]
Can you go to zrips.support:25565 and test if you can reproduce it there?

**Comment by mrfloris** [comment]
Can you do a "/ver" and share the full output with us?
`Server: 1.16.5 1.16.5-R0.1-SNAPSHOT` doesn't really say much, this could be forge.

**Comment by mrfloris** [comment]
<img width="711" alt="Screen-Shot 2023-04-19 at 10 41 01" src="https://user-images.githubusercontent.com/28841349/233019386-aabae348-df09-4fa1-8a45-9ed9db0b3305.png">

We need /ver, and i recommend to try an official server engine to figure out if that's the cause, if that doesn't fix it, then  clone the server and remove the other plugins, and try again.

**Comment by mrfloris** [comment]
<img width="885" alt="Screen-Shot 2023-04-19 at 10 43 57" src="https://user-images.githubusercontent.com/28841349/233020168-aa93ff0a-987d-4e17-a51a-4d721a65a089.png">

Ticket can remain closed, it's not a supported server engine, and I suspect this is caused by that. and it's not a cmi issue.

**Comment by Zrips** [comment]
@SnowBlitzz 
This bug is from archlight side as it's not handling properly FoodLevelChangeEvent. While there could be some work around for it from my end, this needs to be fixed by Archlight.
