### ISSUE TITLE
small reminder

### ISSUE THREAD

**Issue by TWME-TW** [Zrips/CMI#7764]
### Description of Issue

I'm not sure if you added this file to the package?  If it has been added to the package, please update to the latest version, because I accidentally deleted two letters when uploading to GitHub

https://github.com/Zrips/CMI/issues/7584

### Version Information

```shell
Nope
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Addressed.
