### ISSUE TITLE
/give @p diamond_sword{Enchantments:[{id:"minecraft:smite",lvl:2s} - error

### ISSUE THREAD

**Issue by KalviPL** [Zrips/CMI#7769]
### Description of Issue

I write: /give @p diamond_sword{Enchantments:[{id:"minecraft:smite",lvl:2s} and no give item

### Version Information

```shell
server version 1.19.4 
CMI: 9.5.0.6
CMILIB: 1.2.5.3
```

### Errors

```shell
https://mclo.gs/76ddmvm
```

### Relevant Plugins

Vault 1.7.3 - CMI

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
because of wrong syntax ;)

try your command with minecraft:give if you are using the vanilla syntax

**Comment by Zrips** [comment]
@KalviPL 
Most likely incorrect copy/paste as last 2 symbols have been missing from your command. Correct one would look like
**/give @p diamond_sword{Enchantments:[{id:"minecraft:smite",lvl:2s}]}** basically missing "]}"
