### ISSUE TITLE
Tablist sort and scoreboard

### ISSUE THREAD

**Issue by KalviPL** [Zrips/CMI#7773]
Suggests adding scoreboard and sorting ranks on the tablist
e.g., some permission

**Comment by KalviPL** [comment]
I guess that you would have to rework probably the tab, but I think that in such a plugin should be something like this because we pay for it, and yet it is worthwhile to improve older modules and not just add new ones. Why should server owners add a new plugin for TAB when CMI can have something like that.

**Comment by CloudeLecaw** [comment]
Well First Wrong Place here to suggest anything
The place for suggestions is here

**Comment by CloudeLecaw** [comment]
Ticket can be closed
Discussion was created allready
https://github.com/Zrips/CMI/discussions/7774
