### ISSUE TITLE
Could not pass event EntityDismountEvent to CMI v9.5.0.7

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#7776]
### Description of Issue

With [Citizen](https://www.spigotmc.org/resources/13811/) and [Denizen](https://www.spigotmc.org/resources/21039/) plugin and i make `/npc moveto 111.37 32.2 -83.48` for exemple, I have a error in my console because I think CMI to the impression that a player is sit while he is an NPC as a player.

### Version Information

```shell
CMI: 9.5.0.7 SqLite
CMILib: 1.2.5.3
Server: Purpur 1.19.4-R0.1-SNAPSHOT
CMI economy: Activée Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Activée
Modules -> 29 enabled 29 disabled: spawnerProximity, cuffed, mirror, tablist, versionCheck, armorEffects, moneyCheque, skin, elytraBoost, cmiPlaytime, elytraLaunch, bossBarCompass, chatBubble, votifier, shulkerBackpack, headDrop, spawnerCharge, vanish, namePlates, homeInteractions, hpBossBar, anvilRenameColor, spawners, dynamicSigns, disabledEnchants, worldLimitsElytra, ranks, sitAnimation, totemBehavior
```

### Errors

```shell
https://mclo.gs/RVKhwIj
```

### Relevant Plugins

Citizens #3034 and Denizens #1791

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version
