### ISSUE TITLE
Deluxe Combat x CMI

### ISSUE THREAD

**Issue by abenraged** [Zrips/CMI#7779]
### Description of Issue

CMI broken when i use Deluxe Combat with also playercombathandlin: false

https://pastebin.com/7fehTjXK   ( broke /invsee) 644line
https://pastebin.com/p9j1HSVc  (broke combat)

Also dev from DeluxeCombat tell me its ur fault
![image](https://user-images.githubusercontent.com/109480473/232524912-85c739e8-000f-4bf1-8d4e-03b4afff5fdc.png)

### Version Information

```shell
CMI: 9.5.0.7 MySQL
CMILib: 1.2.5.3
Engine: Purpur 1.19.3-R0.1-SNAPSHOT (latest build 1.19.3)
Modules off:
deathMessages, cuffed, launchPAD, world limits, tablist, ranks, playerCombat, votifier, afk, jail, bossbarCompass, totembehavior
```

### Errors

```shell
errors in descriptions
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next CMILib update
