### ISSUE TITLE
%cmi_user_rank_percent_rank% not working properly

### ISSUE THREAD

**Issue by titidelaff** [Zrips/CMI#7782]
### Description of Issue

%cmi_user_rank_percent_rank%  give random user % from DeluxeMenus.
Player 1 with /rankup get 78.18%, from menu get 74.09%.
Player 2 with /rankup get 58.55%, from menu get 31.19%.

### Version Information

```shell
[22:17:01 INFO]: --------------------------------------------------
[22:17:01 INFO]: CMI: 9.5.0.7 BungeeCord CMIB MySQL
[22:17:01 INFO]: CMILib: 1.2.5.3
[22:17:01 INFO]: Serveur: Paper(511) 1.19.4-R0.1-SNAPSHOT
[22:17:01 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
[22:17:01 INFO]: Modules -> 56 activs 2 dsactivs: tablist, spawners
[22:17:01 INFO]: --------------------------------------------------
```

### Errors

```shell
No error
```

### Relevant Config Sections

```yaml
%cmi_user_rank_percent_chevalier% in menu config where chevalier is id rank in Ranks.yml
```

### Relevant Plugins

PlaceholderAPI 2.11.3 DeluxeMenus 1.13.7

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Can you elaborate more on this with posible images what you mean exactly about "menu" showing you different results? As rank informational messages in chat should show same numbers as %cmi_user_rank_percent_rank% placeholder as both used same method to get data.

**Comment by titidelaff** [comment]
Number from command /rankup:
![image](https://user-images.githubusercontent.com/23405363/232989316-7f7c0076-53cd-4fc9-94e8-de40fe4f6d76.png)

Number from command /papi parse me %cmi_user_rank_percent_chevalier%:
![image](https://user-images.githubusercontent.com/23405363/232989455-b387e58c-5782-4c29-9f8f-0101ee304326.png)

Number from command /cmi placeholders parse %cmi_user_rank_percent_chevalier%: 
![image](https://user-images.githubusercontent.com/23405363/232989698-1a18fe80-0f2f-4b87-a99c-339fb971d816.png)

Number from placeholder in DeluxeMenus:
![image](https://user-images.githubusercontent.com/23405363/232989870-a0af3326-df15-418d-ac6a-83881ed43e65.png)

Item config that show placeholder in my menu:
  'chevalier':
    material: IRON_SWORD
    slot: 2
    priority: 91
    update: true
    display_name: "&r%img_chevalier%"
    lore:
      - "&aProgression&7: &6%cmi_user_rank_percent_chevalier%%"

**Comment by Zrips** [comment]
As PAPI returns correct value this would mean that DeluxMenu caches values and uses somewhat outdated ones. If you would not perform any actions relating to this rank which would change its progress, would that value eventually match between DeluxMenu and what placeholder returns?

**Comment by Zrips** [comment]
I cant really help out here much as PAPI returns correct value while parsing this placeholder but DeluxeMenus are not, so it should be issue with DeluxMenu and not CMI, you will need to get into contact with him to resolve this one on his end.
