### ISSUE TITLE
I hope CMI can support Folia

### ISSUE THREAD

**Issue by cat-catmiao** [Zrips/CMI#7784]
Visit https://github.com/Zrips/CMI/discussions/new to post new idea or suggestion
Posting new suggestion in ticket section could result in their removal.
I hope that CMI will soon support the Folia server, which is after all revolutionary!

**Comment by CloudeLecaw** [comment]
and why you asked for this in issue if you know about this? ^^

**Comment by CloudeLecaw** [comment]
might ticket can be closed

a disccussion allready exists
https://github.com/Zrips/CMI/discussions/7736
