### ISSUE TITLE
cmi.command.inv.preventmodify permission not working

### ISSUE THREAD

**Issue by TheBadshah** [Zrips/CMI#7785]
### Description of Issue

So i had "OP" as well the 'cmi.command.inv.preventmodify' permission as true [ luck perms ] but the player who dont even have 'cmi.command.inv.preventmodify.bypass' was able to modify my inv.
![image](https://user-images.githubusercontent.com/116473315/232719266-03d464a1-a004-47e2-a4fd-5ff013fb2581.png)
![image](https://user-images.githubusercontent.com/116473315/232719315-66ea3d81-bf16-477f-8561-e56ae847d7db.png)

### Version Information

```shell
latest version as i tested it on "zrips.support:25565" too
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by TheBadshah** [comment]
![image](https://user-images.githubusercontent.com/116473315/232719644-7f1965fe-d69a-43f5-9dd2-9e24e0f7da11.png)

**Comment by Zrips** [comment]
Should be fixed with next update
