### ISSUE TITLE
Players can /ignore anyone

### ISSUE THREAD

**Issue by hotspuraz** [Zrips/CMI#7792]
### Description of Issue

Players can use the /ignore command on anyone, including operators. This makes moderating on the server considerably more complicated when trolls and cheaters can essentially just mute all staff and it hides their chats. 

### Version Information

```shell
CMI-9.3.2.0
```

### Errors

```shell
None
```

### Relevant Config Sections

```yaml
None
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
could you update to CMI 9.5.0.7 and retry?

**Comment by Zrips** [comment]
@hotspuraz 
cmi.command.ignore.bypass permission node to bypass this ignore. If you are not sure about permission nodes you could use for specific feature, you can try using something like **/cmi checkperm ignore** which will output some suggestions
