### ISSUE TITLE
Hologram heads don't work

### ISSUE THREAD

**Issue by KalviPL** [Zrips/CMI#7795]
### Description of Issue

img:head:[playername]
img:head:%cmi_user_name%

Don't work, All the time displays herobrain head

### Version Information

```shell
CMI 9.5.0.8
CMILib: 1.2.5.3
```

### Relevant Plugins

Vault 1.7.3 - CMI

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Answered on Discord, feature currently doesn't support dynamic playernames due to limitations. You can close this bug report. Hopefully in the future there's time to complete this.

**Comment by Zrips** [comment]
This will be addressed with a shift towards new display method we are using for chat bubbles at the moment which will allow us to have dynamic heads displayed in it, for time being its limited due to how holograms are being handled.
