### ISSUE TITLE
hologram update

### ISSUE THREAD

**Issue by dan28000** [Zrips/CMI#7801]
### Description of Issue

when calling hologram.update() async it can create ConcurrentModificationException probably should go to CMIAPI but here it might be resolved faster

### Version Information

```shell
latest version 9.5.0.8
cmi lib 1.2.5.3
```

### Errors

```shell
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
        at com.Zrips.CMI.Modules.Holograms.CMIHologram.updatePages(CMIHologram.java:332) ~[CMI-9.5.0.8.jar:?]
        at com.Zrips.CMI.Modules.Holograms.CMIHologram.update(CMIHologram.java:584) ~[CMI-9.5.0.8.jar:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
One of obvious solutions would be to not call this method async, another thing is the actual cause, from error where it failed for you looks like you modify holograms lines constantly which causes this error to happen, again, calling it in sync would actually solve it.

**Comment by dan28000** [comment]
yes I know calling it in sync fixes it but there could be check for it if it's called async or not or just let if run sync if it's async
