### ISSUE TITLE
Jail cell bug

### ISSUE THREAD

**Issue by noty0723** [Zrips/CMI#7802]
### Description of Issue

create cell in game it will start from cell [0] and cant create more cell in that jail
and if i edit it in file start with [1] . it still only apear cell [0] in game.
[Video](https://youtu.be/Y1kwf6u2Vhk)

### Version Information

```shell
CMI version: 9.5.0.8 SqLite
CMILib: 1.2.5.3
Server: Paper(307) 1.19.2-R0.1-SNAPSHOT
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Mr200tt** [comment]
Up! Broke my cells updating the plugin, pls fix

**Comment by Zrips** [comment]
Will be fixed with next update.
