### ISSUE TITLE
Global tablist and global chat

### ISSUE THREAD

**Issue by sidboy55555** [Zrips/CMI#7804]
Hi,

I wasn't sure if these where bugs, so I post it as a question.

The tablist isn't showing the global players online on the network, only the ones on the local server, and yes I have CMIB installed on bungeecord.

And the global chat isn't working, I gave everyone the cmi.bungee.publicmessages.* permission, but messages send on one server aren't visible on the other, only private msg's are.

**Comment by Zrips** [comment]
TabList isint supporting players from other servers at the moment, so it will only show local players. If you really need this feature you might want to look around for more specialized plugin with this capability.

**Comment by sidboy55555** [comment]
Noted, will this feature be added in the future?

And about the global/public chat question? Only private messages are accross server, but the public chat isn't.
