### ISSUE TITLE
After the player's spawn point is destroyed, When the player dies in hell it will not respawn to the world spawn point, but in the hell 

### ISSUE THREAD

**Issue by aiaskaHirro** [Zrips/CMI#7807]
When the player's bed in the main world is destroyed and enters hell and dies, he will not return to the world rebirth point, but will be reborn at  hell 
     But the above problem did not appear after removing the CMI , CMILib  ,   I have tested without cmi and with CMi and only server (paper -592 & spigot )  All server core also have this  problems occur with cmi
     i also  tested vanilla   This problem does not appear in vanilla

---

**Cmi Version (using`/cmi version`):** 9.5.0.7  ;  9.5.0.8 

**Server Type (Spigot/Paperspigot/etc):**  Spigot  ;  Paperspigot 519 

**Server Version (using `/ver`):**  1.19.4

**Comment by CloudeLecaw** [comment]
have you set your spawn prioirty correct for the worlds?

**Comment by Zrips** [comment]
@aiaskaHirro 
Will need to see your Spawn and respawn setup. There are specific respawn priorities which can depend on world you die in, while  disabling CMI would "solve" this issue it might not be an issue as this might be what it should do by your current setup.

**Comment by aiaskaHirro** [comment]
@Zrips Thank you for the reply. I know that our problem wasn't a bug, because I didn't read the config clearly. Also I suggest that the default setting of spawn can be the position of server properties. And not giving each world a spawn location as the default setting to pervent someone have the same problem of me.
