### ISSUE TITLE
New kits won't show in GUI 

### ISSUE THREAD

**Issue by Corcustos** [Zrips/CMI#7809]
### Description of Issue

Is it possible to have too many kits for the GUI? Newly created kits won't appear in the GUI anymore while having cmi.kit.* unless I delete all others and reload/restart. Then I can undo my deletion to have all kits show again. The yml seems valid and severely reducing my kits prevents the issue. Using individual permissions appears to work as long as I remove cmi.kit.*  but is impractical for the amount of kits I have.

Testing on fresh config.yml, settings, and saves except Kits.yml. Figured I'd ask before making a ticket since it said to ask around first. 

### Version Information

```shell
CMI: 9.5.0.8 SqLite
CMILib: 1.2.5.3 
Server: Spigot 1.16.5-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Disabled 
Modules -> 57 enabled 1 disabled: votifier
```

### Errors

```shell
Nothing in console/logs.
```

### Relevant Config Sections

```yaml
Kits.yml: https://pastebin.com/y9Mb4TuP

The kits that aren't showing currently for me are fruit, starterbooster, zygardestuff, spawnerenderman, and worldhammer. Additional kits are the same thing. Reason for so many kits is that I use them to group up rewards to be given out via command npcs/event stuff/etc and for easy bulk editing.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
