### ISSUE TITLE
Cmi spawner proximity issue

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#782]
1.13 Paper spigot
CMI 8.0.7.0

I have spawner proximity set to true with a range of 6. I also made sure to have the full disable set to false. 

I can't seem to get this feature to work, I'm just guessing it doesn't work with silk spawners. 

I see no errors or issues in console.

**Comment by Zrips** [comment]
This should be working currently, atleast it does for me. Keep in mind that you can bypass range limitations with cmi.spawners.proximity.bypass permission node
