### ISSUE TITLE
unjail spam error

### ISSUE THREAD

**Issue by noty0723** [Zrips/CMI#7828]
### Description of Issue

unjail is working fine but
its spam this message to the player got unjail
![image](https://user-images.githubusercontent.com/107478024/236857570-ca294711-a451-498d-93d7-1c6c1437757c.png)

### Version Information

```shell
CMI version: 9.5.0.9 SqLite
CMILib: 1.2.5.3
Server: Paper(307) 1.19.2-R0.1-SNAPSHOT
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
itsnt this one fixed with latest version ?

**Comment by Zrips** [comment]
Should be fixed with latest builds
