### ISSUE TITLE
Bug/In need of help - Can't replace spider spawners using /cmi replaceblock

### ISSUE THREAD

**Issue by DrunkIrishPotato** [Zrips/CMI#783]
**Description of issue or feature request:**
Hey there having issues when using the /cmi replaceblock command on spawners. I've gotten it to work when targeting all spawner blocks in a chunk but can't seem to get it to replace just spider spawners.

Can anyone help me with this?

Thanks in advance.

CMI VER 8.0.7.0

SPIGOT SERVER

SERVER VER : Spigot 1.13-R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment]
Hm how spawners are defined in spigot? Its easy to locate the spawner block, but this does not help with replacing just one type of Block. 😊

**Comment by DrunkIrishPotato** [comment]
So it's an issue with spigot?

**Comment by CloudeLecaw** [comment]
I think so, the question is. How a spawner is defined in spigot and is it possible to also define this with CMI.

**Comment by DrunkIrishPotato** [comment]
Ah okay, maybe spigot will sort it out in the future. Thanks for your help <3
