### ISSUE TITLE
[tfly error]Can't fly after quit and rejoin server

### ISSUE THREAD

**Issue by minecraft-dripdrop** [Zrips/CMI#7832]
### Description of Issue

set tfly time to 1600
quit server,join server,and can't fly

but use /tfly will show my time:"Temporary fly mode enabled fo the next 26 min 13 seconds"
 

### Version Information

```shell
[17:02:16 INFO]: CMI: 9.5.0.9 SqLite
[17:02:16 INFO]: CMILib: 1.2.5.3
[17:02:16 INFO]: Server: Purpur 1.19.4-R0.1-SNAPSHOT
[17:02:16 INFO]: CMI economy: 禁用 CMI Chat: 禁用
[17:02:16 INFO]: Modules -> 57 enabled 1 disabled: votifier
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
i would add a check in event command for server join that if  remaining tflytime is not 0 or not null that tfly gets enabled then on login

This could look like this in EventCommands.yml for the Login of a player:

```
joinServer:
  Enabled: true
  Commands:
  - delay! 1
  - check:%cmi_user_tfly%!=0|null asConsole! cmi tfly [playerName] %cmi_user_tfly% -s```

**Comment by Zrips** [comment]
@minecraft-dripdrop 
Can happen if another plugin overrides fly mode after CMI enables it for the player. As @CloudeLecaw suggested here you can use event commands to toggle tfly for the player on join with that 1 second delay which should solve your issue.
