### ISSUE TITLE
CustomTab in aliaseditor don`t working

### ISSUE THREAD

**Issue by alisa12s** [Zrips/CMI#7833]
### Description of Issue

tab broke in alias editor if we create commands
/al
/al bp 
/al sumo

if I create an alias from one command, then the first tab will work, and the next ones won't
![изображение](https://github.com/Zrips/CMI/assets/110072561/09897a9c-2cfb-4216-ba4f-041f806f5c4c)

if I create an alias from one command, then tabulation works correctly, but I need all aliases to be prefixed with /al

### Version Information

```shell
Версия плагина CMI: 9.5.0.9. MySQL
CMILib: 1.2.5.3 
Версия сервера: Purpur 1.19.4-R0.1-SNAPSHOT
CMI Экономика: включено. Версия Vault: 1.7.3-b. CMI Чат: выключено
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by alisa12s** [comment]
this worked on version 9.5.0.4 yet. After switching to 9.5.0.8 it broke.

**Comment by CloudeLecaw** [comment]
it would help to see you customalias instead if saying "it broke" we also use customalias on 9.5.0.8 with paper 1.19.4 and the customalais tabs didnt broke.

**Comment by alisa12s** [comment]
Today after work I will send you my customalias file

**Comment by alisa12s** [comment]
https://www.youtube.com/watch?v=e2KHDV3fLvw

I thought that it would be better to see what is at stake. please watch my video

**Comment by CloudeLecaw** [comment]
> https://www.youtube.com/watch?v=e2KHDV3fLvw
> 
> I thought that it would be better to see what is at stake. please watch my video

i know that this happens. have you correct your tabcomplete? (and restarted after)?

**Comment by alisa12s** [comment]
this does not work

https://www.youtube.com/watch?v=vl37911U6Hg

**Comment by alisa12s** [comment]
i did 4 different tests, restarted the server and it still doesn't work

**Comment by CloudeLecaw** [comment]
tell the server to also use it

**Comment by alisa12s** [comment]
are you trolling me? it doesn't work, I've already posted some videos. I just copied your text, just pasted it and restarted the server 3 times. it didn't work. Have you checked this yourself?

https://www.youtube.com/watch?v=P2-S4lPo2D0

**Comment by alisa12s** [comment]
I can install 9.5.0.4 and show that it worked great. However, after updating to another 9.5.0.8 it stopped working

**Comment by CloudeLecaw** [comment]
The test like you make it is not good and is unnessesarry because you can use check for test1 and test 2 its unessary to creat test1 nd test2

do it like this:

CustomAlias:
  al:
    Cmds:
    - check:$1==null! msg! [playerName] You cant use the blank command. Use an Argument.
    - check:$1==test1! command.
    - check:$1==test2! command
    Perm: false
    Tab: true
    CustomTabs:
    - 'test1, arg1,arg2'
    - 'test2, arg3,arg4'

if you run into your issue because of loops or invailed syntax then its your own fault

**Comment by CloudeLecaw** [comment]
this is an old way you choose and its no longer vailed some with
al ? as custom alias make it with checks

**Comment by alisa12s** [comment]
You had to immediately write that this is the old way and it no longer works. Then the bug report is irrelevant. I'm going to rewrite all my 20 aliases. I don't understand why you removed support for this, but what can you do. The ticket can be closed.

**Comment by CloudeLecaw** [comment]
that doesnt matter

we have 189 aliases and it was needed. specialy the help.

**Comment by CloudeLecaw** [comment]
This ticket can be closed. the issue was solved, because the OP designed alias in a wrong away some versions before.

**Comment by alisa12s** [comment]
these aliases are more than a year old and they worked stably

**Comment by CloudeLecaw** [comment]
that doesnt matter

**Comment by alisa12s** [comment]
thanks for your suggestion, I think we can handle it ourselves ;)

**Comment by CloudeLecaw** [comment]
i think this ticket can be closed :3
