### ISSUE TITLE
CustomRecipe: Two of the same item but with different CustomModelData doesn't properly save the recipe.

### ISSUE THREAD

**Issue by prototype464** [Zrips/CMI#7843]
### Description of Issue

Trying to make a custom recipe with two items: "Tutorial Ingot" and "Tutorial Stick", both are the `paper` item with a rename and `CustomModelData` tags `16` and `17` respectively.

Upon saving the recipe, the "Tutorial Stick" is overwritten with two more of the "Tutorial Ingot".

Shouldn't the plugin be saving the item based on specific NBT?

Images in the Discord detailing the issue:
https://discord.com/channels/452792793631555594/526402563847880725/1107200940773216337

Video in the Discord showing the issue:
https://discord.com/channels/452792793631555594/526402563847880725/1107414782128160798

### Version Information

```shell
CMI: 9.5.0.6
CMILib: 1.2.5.3
Server: Paper(411) 1.17.1-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Disabled
Modules -> 56 enabled 2 disabled: votifier, dynamicSigns
```

### Errors

```shell
This one popped up when rebooting the server, unsure if it's significant.
[12:51:25 ERROR]: Tried to load unrecognized recipe: cmilib:9cb5727b-8f5e-3794-ae6b-0f29aa901227 removed now.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by prototype464** [comment]
_Related Issues_
#https://github.com/Zrips/CMI/issues/7844
#https://github.com/Zrips/CMI/issues/7509
#https://github.com/Zrips/CMI/issues/7473

**Comment by Zrips** [comment]
This is done by the server as of something like 1.16 version it started to add extra data to text fields. Not much I can do here. And this has no impact on items visual representation, it might only be an issue if plugins tries to compare this specific item to its registered one with basic "equals" which will result in false, but this is incorrect way to determine items validity either way.

**Comment by prototype464** [comment]
The issue here is the fact the recipe isn't being properly saved despite the items having different data, "this has no impact on items' visual representation" isn't even responding to the problem I addressed. CMI seems to just be checking the item ID, but not the actual data of the item, which is causing this issue.

**Comment by prototype464** [comment]
Please take another look at this?
