### ISSUE TITLE
Kit Editor: NBT data of items is not kept the same.

### ISSUE THREAD

**Issue by prototype464** [Zrips/CMI#7844]
### Description of Issue

For some reason, CMI Kits modifies the NBT data of items, even adding extra data that wasn't previously there. This makes it incredibly tedious to use for item currencies, as the item must be "washed" by throwing it into the kit editor and taken back out before it can be used as a currency or for anything else that requires the data be **exactly** the same.

Why isn't the NBT just kept exactly as-is?

Video in the Discord of the issue:
https://discord.com/channels/452792793631555594/526402563847880725/1107421330254602321

### Version Information

```shell
CMI: 9.5.0.6
CMILib: 1.2.5.3
Server: Paper(411) 1.17.1-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Disabled
Modules -> 56 enabled 2 disabled: votifier, dynamicSigns
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by prototype464** [comment]
_Related Issues_
https://github.com/Zrips/CMI/issues/7843
https://github.com/Zrips/CMI/issues/7509
https://github.com/Zrips/CMI/issues/7473

**Comment by Zrips** [comment]
This is done by the server as of something like 1.16 version it started to add extra data to text fields. Not much I can do here. And this has no impact on items visual representation, it might only be an issue if plugins tries to compare this specific item to its registered one with basic "equals" which will result in false, but this is incorrect way to determine items validity either way.

**Comment by prototype464** [comment]
This issue causes any items being handled through CMI to be incompatible with any plugins that check for exact NBT, such as Shopkeepers or literally anything related to markets that use item currencies. Enchants are often applied for glows and/or to prevent players from replicating the item normally.

It is possible to fix this, I would greatly appreciate if you would do that or get someone else to. "Not much I can do here" isn't satisfactory.

**Comment by prototype464** [comment]
This plugin has the exact functionality you say "not much I can do here" to
https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-21-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/
