### ISSUE TITLE
Error when using the /near command

### ISSUE THREAD

**Issue by yngdrms** [Zrips/CMI#7852]
### Description of Issue

When I use the /near command next to a player, I get an error in the chat and the console

### Version Information

```shell
https://imgur.com/a/3A95zY9
```

### Errors

```shell
https://pastebin.com/aUR9MqxH
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by 1ntent1on** [comment]
Also having this issue

**Comment by Zrips** [comment]
Will be fixed with next update
