### ISSUE TITLE
%cmi_user_toggle_chatbubble%

### ISSUE THREAD

**Issue by kforbro** [Zrips/CMI#7853]
### Description of Issue

You forgot to add a placeholder for chatbubbles option
%cmi_user_toggle_chatbubble%
https://i.imgur.com/ZEFf9Wb.png

### Version Information

```shell
9.5.1.1
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
this is more a feature request than a bug report..

**Comment by Zrips** [comment]
Will be added with next update
