### ISSUE TITLE
Cmi holograms don't support kingdoms placeholders 

### ISSUE THREAD

**Issue by Ksewedo5** [Zrips/CMI#7860]
### Description of Issue

%kingdoms_top:at pos=1, of=name% -> The hologram does not treat it as a placeholder, it is displayed as text 

Other plugins have no problem processing this placeholder. That's why I believe it's a CMI bug

### Version Information

```shell
CMI 9.5.11 / CMILib: 1.2.5.4
Engine: PufferFish+ (1.19.4)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
CMI will accept any placeholder which gets parsed by PAPI plugin, and valid placeholders should not contain spaces in them. So its not a bug with CMI, it simply specific placeholder which isint being processed due to its format and incompatibility with normal format.
