### ISSUE TITLE
Schedule - last day of month?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#7861]
Hello, is it possible to execute the schedule on the last day of the month?

Cause every month has a different amount of days... It would be nice if there's some way. For example, in February it will be on 28, in May it will be on 31, in April on 30, etc...

**Comment by MC-MrBirdy** [comment]
You can add multiple PerformOn options to a schedule.
>   PerformOn:
>    1:
>      Month: 1
>      Day: 31
>    2:
>      Month: 2
>      Day: 28
>    3:
>      Month: 3
>      Day: 31

Would that solve your question?
[https://www.zrips.net/schedule/](https://www.zrips.net/schedule/)

**Comment by bobhenl** [comment]
Yeah, thanks! @MC-MrBirdy
