### ISSUE TITLE
Shulker addition

### ISSUE THREAD

**Issue by alfredcort** [Zrips/CMI#7863]
I'd love for CMI to implement a way to open shulkers straight from the inventory by having it in your right hand and it opening up without placing. This is helpful for when players need access to items in their shulker when standing in protected/claimed areas.

**Comment by MC-MrBirdy** [comment]
This looks more like a feature request, and a feature like that is available in CMI:
- **cmi.openshulker** - Allows to use shulkerbox as backpack
- **cmi.openshulker.shift** - Allows to open shulkerbox while holding it in hand and shift+right mouse click

You will need to have the module enabled in "CMI\Settings\Modules.yml"
>\# Handles shulker box as backpacks
>\# Applies for servers from 1.11.x and up
>shulkerBackpack: true
