### ISSUE TITLE
/enchant feature

### ISSUE THREAD

**Issue by glorying16** [Zrips/CMI#787]
Im hoping you can implement a feature like what Essentials uses with the /enchant command. We have used Essentials forever, and currently have a ranking system that will give permission to specific enchantments individually. The permissions are like this: essentials.enchantments.knockback 

We want to make the change over to CMI but since this is not a current feature, it would demolish our ranking system. At this point I think we will have to hold off on the switch, because I dont see a way around this one. Im hoping its something you can add in fairly easy. I really enjoy this plugin, but I dont really wanna use both CMI and Essentials just for some enchantments and risk bogging the server down with the bulk.

**Comment by CloudeLecaw** [comment]
there is allready cmi enchant?.  you can enable it in the alais.yml of cmi

>   # /cmi enchant $1-
>   /enchant: true

**Comment by Someone-NEW** [comment]
I see there are a feature request and i will just suggest moere enchants than vanilla here too:
- Poison (can be poison player in pvp with Bow for example)
- Lightning (Self explanatory)
- Slow (can slow down player if hit you them with any custom item you selected)
- Blindness (Word say all and all enchants can be defined with I, II,III etc)
- ShotGun (Self explanatory)
- TNT (this will give a damage like a TNT, land destroy can be optional enabled/disabled)
- StormCaller (This option is supposed to send a storm or a stormy arrow over the player)
- AttackDeflector (Self explanatory)
- Speed (This mean that we can add a speed enchant to custom selected item and when player have this on hand give him a speed etc)
- Fly (This mean that we can add a Fly enchant to custom selected item and when player have this on hand give him a speed etc)

This can be just expanded feature for those who could use it, I hope that there are more of you who think that this could be useful

**Comment by glorying16** [comment]
@Zrips any chance of this being implemented in the future? Its one of 2 or 3 things I still use EssentialsX for, and would love to drop it.

**Comment by Zrips** [comment]
cmi.enchantments.[enchantname]
cmi.enchantments.[enchantName].[maxEnchantLevel]
With next update. You will need to enable those requirements in config file.
