### ISSUE TITLE
CMI schedules.yml doesn't incorporate changes with /cmi reload: must restart server.

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#7874]
### Description of Issue

When I edit events in the schedules.yml file, and then do /cmi reload, the schedule changes and/or additions do not take effect.  It requires a server restart.  It's been this way for a very long time.  It would be lovely if the changes could be incorporated without having to restart the server.  
If this should be a feature suggestion rather than a bug report, I'll be happy to move it to that section.

### Version Information

```shell
[16:00:09 INFO]: --------------------------------------------------
[16:00:09 INFO]: CMI plugin version: 9.5.1.3 MySQL
[16:00:09 INFO]: CMILib: 1.2.5.5 
[16:00:09 INFO]: Server: Paper(545) 1.19.4-R0.1-SNAPSHOT
[16:00:09 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[16:00:09 INFO]: Modules -> 50 enabled 8 disabled: spawnerProximity, flightCharge, disabledEnchants, mirror, ranks, moneyCheque, spawners, spawnerCharge
[16:00:09 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Could you elaborate more on this issue? As of testing scheduler will update with new information and will restart information as it should perform same actions as it does while starting server. Could you give exact example of scheduler and actions you take which results in scheduler not updating as it should?

**Comment by Momshroom** [comment]
Further debugging this: if I have a disabled schedule and enable it and then /cmi reload, it works.
If I have an existing active schedule and change the times, it works.

When I get the issue is when I change an existing command in an existing schedule w/o changing its times or enabled state.  Ie: we have a weekly contest which has winners announced via the schedules file, and I change the placeholders in the commands and the wording of what the contest was w/o changing anything else, then reload CMI:  the old message is sent out, not the edited one.

To test this to confirm, I edited the announcements to all include the word edited, saved, and reloaded, then waited... the messages show in their old form, without the word edited in them.

Top of the Announcer section:
`Announcer:
  Enabled: true
  MinPlayers: 1
  Repeat: true
  Delay: 300
  Randomize: true
  Commands:
  - ? broadcast! '                     &8&l»&7&l» &b&lTrek&7&lCraft&f&l✦&c&lAnnouncer    &7&l«&8&l«\n&f&l✦&bMember+
      &7comes with two kits
    : /kit member+ and /kit MiniMove!Edited'
  - broadcast! '                     &8&l»&7&l» &b&lTrek&7&lCraft&f&l✦&c&lAnnouncer
    &7&l«&8&l«\n&f&l✦&bPut an ! &7in front of your chat if you want to share it with
    Discord!Edited'`

**Comment by Zrips** [comment]
This doesn't look to be an issue. You might want to double check that your file you are editing actually gets updated on server side. Tested out by your provided steps on running scheduler, it does update its commands with new modified ones by performing basic /cmi reload, as it should from the code we have. So something different is going on with your setup which still grabs old information instead of updating it. Double check if you dont have two Announcer schedulers set in your config file which could mess things up.
Closing ticket for now.
