### ISSUE TITLE
CMI 9.6.0.0 Tablist Error Spam on Paper 1.19.4 (b550)

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#7878]
### Description of Issue

Happy update season! In case it's helpful, got some massive error spam only with players online, quiet with no one online. Rolled back without issue. 

https://gist.github.com/mercurialmusic/af617363ed16210b66d3f036d3bd322e

### Version Information

I noped out too quickly to grab the version command info but this was CMI 9.6.0.0 with CMILib 1.3.0.0 on Paper 1.19.4 b550. I rolled back both CMI and CMILib to the previous versions without issue.

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
New version is out, should resolve this issue.
