### ISSUE TITLE
[BUG] Didn't update sign's text when clicking on "Done" button

### ISSUE THREAD

**Issue by steven11304** [Zrips/CMI#7892]
### Description of Issue

All my players without cmi.signs.shiftedit permission wont update sign's text when first time create the sign and clicking on "Done" button."

Expected behavior:
player dont need to have cmi.signs.shiftedit  permission to create and update the sign's text.

### Version Information

```shell
CMI 9.6.0.4 CMIlib 1.3.0.3
    git-Paper-30
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Developers will have to wait for the server API to introduce an event so they can update their plugins for these particular features that are currently giving issues.
