### ISSUE TITLE
When killed by a crossbow, the [item] of the death message is not parsed correctly

### ISSUE THREAD

**Issue by SheerYin** [Zrips/CMI#7893]
### Description of Issue

When killed by a crossbow, the [item] section will read: MemorySection[path='CROSSBOW', root='YamlConfiguration']
The entire message can be viewed in the suspension, and the normal lore is displayed

### Version Information

```shell
Current: git-Purpur-1995 (MC: 1.20.1)*
Previous: git-Paper-4 (MC: 1.20)

CMI-9.6.0.4
```

### Relevant Config Sections

```yaml
§f[§c死亡§f] 玩家 §2[playerDisplayName] §f被 §c[mobName] §f使用 [item] §f击杀
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Could you provide image of message you receive? At this moment dont know what's going on in your particular situation, but it does work on git-Purpur-2000 (MC: 1.20.1)* version correctly.
