### ISSUE TITLE
/cmi enchant don't work

### ISSUE THREAD

**Issue by Weyl1** [Zrips/CMI#7894]
### Description of Issue

Error during tabulation in command, and another error when the command is executed.

### Version Information

```shell
CMI 9.6.0.4
CMILIB 1.3.0.3

purpur-1995 1.20.1
```

### Errors

```shell
https://pastebin.com/Hh4Q8ubQ
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Issue with EcoEnchant plugin and not CMI, you will need to get into contact with this plugin dev to address it, cant really do anything about this issue from my end.
