### ISSUE TITLE
Chat bugg issue

### ISSUE THREAD

**Issue by FruitMC** [Zrips/CMI#7907]
### Description of Issue

hello, im using a plugin called kingdomcraft for my kingdom server.
Now does this plugin also change the chat format so its with kingdom name and rank ect but now the problem is if cmi is installed and i send a message its sends my message twice with the kingdom format and de default minecraft format if i uninstall cmi this issue is fixed and its only send with the kingdom format and once so not also send with the default minecraft chat format to make it more clear:

It sends default chat message format in chat when cmi chat is disabled
![image](https://github.com/Zrips/CMI/assets/137414092/81378241-2d27-4c46-bb7a-fa6ebb4e2e38)

### Version Information

```shell
CMI: 9.6.0.0
CMILib: 1.3.0.3
Server: Paper(43) 1.20.1-R0.1-SNAPSHOT
Cmi economy: enabled
Vault: 1.7.3-CMI(CMIEInjector)
Cmi Chat: Disabled
```

### Errors

```shell
none
```

### Relevant Config Sections

```yaml
the config's are default
```

### Relevant Plugins

Vault 1.7.3 & Kingdomcraft plugin

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Disable ClickHoverMessages inside chat.yml file which should fix this issue for you.
