### ISSUE TITLE
/enchant issue

### ISSUE THREAD

**Issue by SkyLyfe** [Zrips/CMI#7908]
### Description of Issue

Using the `cmi.enchantments.[enchantname]` permission node, I am able to allow/deny players to use certain enchantments as expected. However, the issue is when a player types `/enchant` the list of "possible enchants" includes enchants that they don't have access to. Honestly wasn't sure if this was intended or if it's a bug, but it seems like a bug to me as it doesn't make sense to show players the enchantments they can't use.

This issue gets worse when combining CMI with a custom enchant plugin such as EcoEnchants. As this results in players seeing **all** of the custom enchants as well. Example below:
![image](https://github.com/Zrips/CMI/assets/129910496/2529b2d5-a848-4ec6-9723-c8e344015630)

### Version Information

```shell
CMI: 9.6.0.4 SqLite-> 9.6.0.5
CMILib: 1.3.0.3 
Server: Paper(10) 1.20-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 39 enabled 19 disabled: spawnerProximity, mirror, tablist, moneyCheque, jail, elytraBoost, spawners, playerChatTag, elytraLaunch, bossBarCompass, flightCharge, chatBubble, ranks, votifier, headDrop, spawnerCharge, namePlates, timedCommands, totemBehavior
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
