### ISSUE TITLE
[FEATURE] Per Custom Recipe Permissions

### ISSUE THREAD

**Issue by Cooperating** [Zrips/CMI#791]
**Description of issue or feature request:**
If this isn't already possible, could you add a way to assign a permission node to every custom recipe?  I was thinking of assigning various custom recipes to jobs and/or ranks for players to use.

**Cmi Version (using`/cmi version`): 8.0.8.0** 

**Server Type (Spigot/Paperspigot/etc): Spigot** 

**Server Version (using `/ver`): 1.13.1-R0.1-SNAPSHOT**

**Comment by impmallet** [comment]
2nd this.

**Comment by impmallet** [comment]
Dev is lame, closes tickets with no explanation.
