### ISSUE TITLE
Unable to toggle godmode in creative or spectator mode

### ISSUE THREAD

**Issue by Mikebbe** [Zrips/CMI#7910]
### Description of Issue

A recent change in CMI/CMILib has made it so you can no longer toggle godmode off when you're in creative or spectator mode.
It is still possible to enable godmode, but not disable it. This applies both to self and when trying to toggle /god on other players.

The message that displays is: "You can't do this in this game mode" and is listed under CMILib's Locale_EN.yml line 172 "`cantDoInGamemode`"

**Expected behavior:**
/god working regardless of current gamemode of player

/cmi version output:
![image](https://github.com/Zrips/CMI/assets/55026250/3a5abac5-36d6-453f-8e9f-52f339067677)

### Version Information

```shell
Look at attached picture
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
This was done intentionally to prevent issues relating to player being in creative mode while being damageable which causes few issues. Tho this change was made long time ago, to be exact it happen at 8.7.8.0 version, so it's almost 3 years old change by now. This isn't a bug, its prevention of a potential causes for bugs.
