### ISSUE TITLE
money set alloffline doesnt working as intented

### ISSUE THREAD

**Issue by NightLife-SG** [Zrips/CMI#7912]
### Description of Issue

wanted to reset money of everybody
used command in console it does work while you online

and the money return to original value after a server restart

### Version Information

```shell
https://prnt.sc/cC8TrENEGiO7
```

### Errors

console will spam this error after doing the command of set money for everyone
https://prnt.sc/ub88HnK3WvP_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Was fixed with latest versions.
