### ISSUE TITLE
I need a feature!

### ISSUE THREAD

**Issue by Jhesterccj** [Zrips/CMI#7919]
Visit https://github.com/Zrips/CMI/discussions/new to post new idea or suggestion
Posting new suggestion in ticket section could result in their removal.
Functions that prevent players from destroying, placing, etc
For example, ess's
essentials.build.destroy.*
essentials.build.drop.*
essentials.build.interact.*
essentials.build.pickup.*
essentials.build.place.*
essentials.build.use.*

**Comment by Zrips** [comment]
Stuff like that needs to be controlled by actual area protection plugins, its outside of CMI feature target.
