### ISSUE TITLE
MoneyLog NPE

### ISSUE THREAD

**Issue by yngdrms** [Zrips/CMI#7921]
### Description of Issue

After a new day, the plugin tries to write log information with the transfer of money to the file of the previous day, and therefore this error occurs

### Version Information

```shell
https://i.imgur.com/kLkdu7K.png
```

### Errors

```shell
https://pastebin.com/xggKmLSD
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should get resolved with next update
