### ISSUE TITLE
'/cmi saveditems' list argument doesn't works 

### ISSUE THREAD

**Issue by TheBadshah** [Zrips/CMI#7923]
### Description of Issue

on doing **'/cmi saveditems list'** it opens the gui of saveditems instead of a list and the gui opens even when you use any random argument like **'/cmi saveditems test'** 

on doing it from console it prints the usage of command  
**Usage: /saveditems [save/get/remove/list] (savedItemName) (-t:playerName) (-a:amount) (-c:category/all) (-s)
 Save or manage saved items**

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.0.6 SqLite
CMILib: 1.3.1.0 
Server: Purpur 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 44 enabled 14 disabled: tablist, versionCheck, moneyCheque, skin, elytraBoost, paintingEditor, dynamicSigns, elytraLaunch, bossBarCompass, coloredArmor, flightCharge, playerCombat, namePlates, homeInteractions
--------------------------------------------------
```

### Errors

```shell
no errors.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
To be fair it does what it should do, tho its name might be misleading. By default we are gonna show all saved items in a GUI, this same thing will happen when you use list variable, it "lists" saved items in a gui.
