### ISSUE TITLE
Delay in '/cmi attachedcommand'

### ISSUE THREAD

**Issue by TheBadshah** [Zrips/CMI#7924]
### Description of Issue

Currently if we use specialized command's **delay! [any positive number]** in **'/cmi attachedcommand'** it will not work as it should it will result as
![image](https://github.com/Zrips/CMI/assets/116473315/593b27b8-b595-4dbd-89ab-6144f91826e7)

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.0.6 SqLite
CMILib: 1.3.1.0 
Server: Purpur 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 44 enabled 14 disabled: tablist, versionCheck, moneyCheque, skin, elytraBoost, paintingEditor, dynamicSigns, elytraLaunch, bossBarCompass, coloredArmor, flightCharge, playerCombat, namePlates, homeInteractions
--------------------------------------------------
```

### Errors

```shell
no errors.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Somewhat known issue, due to how attached commands are being handled there are some restrictions with its usage in comparison to different places which uses specialized commands. Will revisit this one, tho at the moment its not really a bug, its just lack of full support for specialized command mechanics

**Comment by carboncraft** [comment]
Made an account just to say I would love this.

**Comment by Zrips** [comment]
Support was added with latest update. Tho some limitations are still present while using it.
