### ISSUE TITLE
Ranks AureliumRequirement not working

### ISSUE THREAD

**Issue by lDOREMIl** [Zrips/CMI#7925]
### Description of Issue

I tried to set Aurelium skill's total level(power) as rank up condition, but sadly it's not working.
I looked thru the CMI wiki but could not find any info about Aurelium skills there.
Aurelium condition is not even being shown on /rankup command

![image](https://github.com/Zrips/CMI/assets/99507374/44252e6e-6c58-4f0e-bf91-37e647e7a544)

### Version Information

```shell
[15:23:49 INFO]: --------------------------------------------------
[15:23:49 INFO]: CMI plugin version: 9.6.0.6 SqLite
[15:23:49 INFO]: CMILib: 1.3.0.3 -> 1.3.1.0
[15:23:49 INFO]: Server: Paper(511) 1.19.4-R0.1-SNAPSHOT
[15:23:49 INFO]: CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Enabled
[15:23:49 INFO]: Modules -> 56 enabled 2 disabled: votifier, namePlates
[15:23:49 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
stem:
  Enabled: true
  DisplayName: '&2줄기'
  AutoRankup: true
  RankupConfirmation: true
  NextRanks:
  - leaf
  MoneyCost: 500000
  JobsRequirement:
  - totallevel:100
  AureliumRequirement: 
  - "power:70"
  StatsRequirements:
  - PlayTime:518400
  Commands:
  - lp user [playerName] promote 등급
  - broadcast! &6[playerDisplayName] &e님께서 &2[줄기] &e등급이 되셨어요!
```

### Relevant Plugins

Aurelium skills - Beta 1.3.21

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by wlm1455925277** [comment]
Add the plugins.yml in the plugin of CMI to Aurelium skills, it seems that the author forgot to add it, and it can be used!

**Comment by Zrips** [comment]
Should get a fix with next version
