### ISSUE TITLE
sign colour not working

### ISSUE THREAD

**Issue by NightLife-SG** [Zrips/CMI#7927]
### Description of Issue

colour code not working for sign

example
when input &aTesting it will bceome <green>Testing
attached photo
https://prnt.sc/A30Rfnizg8BL

### Version Information

```shell
https://prnt.sc/2VvErp6R0pd7
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Color codes uses {#hex} format, for example **{#green}Text** or **{#660055}Text**
