### ISSUE TITLE
Limit /lastonline, as when you have a lot of players its very slow.

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#7928]
![2023-07-02_12 51 45](https://github.com/Zrips/CMI/assets/144046/0b610e8c-b66b-4196-9473-ff5aa8f4e243)

There is showing 33,033 players in the /lastonline, funny enough, im not going to need to look back to the 33 thousand players in this menu.

Can I suggest a limit be set in the config.yml so that its:
1) faster, its very slow with this many players
2) easier to navigate
3) allows me to give this command to players to use/search who was last online

even better if I can edit what clicking the command does.

**Comment by Zrips** [comment]
This should not affect its speed as it reads information from database sorted by specific criteria either way. Total amount is used by existing precached data, so changing its amount would have no real impact on its performance.

**Comment by Zrips** [comment]
Will optimize speed. Tho with navigation, can't say I know any good way to improve it as this is just a list of users by last login time, if someone wants to know state of the player they can just use /seen command for that purpose.

**Comment by TomLewis** [comment]
Super, that will make it useable then! thanks
