### ISSUE TITLE
Edit Offline Balance

### ISSUE THREAD

**Issue by AnimeDrache** [Zrips/CMI#7929]
Greetings,

so how can we check the offline players currency to edit and change it? That would be really nice to know! Sadly nobody knew it on the discord server so I ask here.

**Comment by Zrips** [comment]
Is this question about API or general plugin functionality?
For API you can just do CMIUser.getUser(@Player).getEconomyAccount() and perform actions you would want. Tho this can be dependent if its using CMI economy as other economy plugins might not work on offline players.

**Comment by AnimeDrache** [comment]
Well for some reason we do have ",00" currency. I want my users to have only FULL numbers. so "1 €", not "1,34". Therefor I wanted to edit the balance of all players that are whitelisted to make their numbers round. Thats why I ask cause I would really appreciate a solution for this =).

**Comment by Zrips** [comment]
If you just want to display balance in full numbers then simply use different currency format like
`    MoneyFormat: '###,##0'`
this will display full numbers only, additionally there is option to limit /pay command to full amounts with **Fractions** in config file. Tho keep in mind that balance remains saved with fractions for more accurate balance tracking as not all plugins could give out full amounts, but these 2 small changes would resolve most of your issues if not all of them

**Comment by AnimeDrache** [comment]
Thank you Zrips, you can close this ticket! Your suggestion fixed it! Sometimes it can be so easy hehe! Thanks ♥
