### ISSUE TITLE
Missing locale for info.Spawner

### ISSUE THREAD

**Issue by samparotony228** [Zrips/CMI#7934]
### Description of Issue

In the new CMI 9.6.0.9 and CMILib 1.3.1.1 update, when getting a spawner via the "/give spawner:cow" command, the name of the spawner looks like this "Missing locale for info.Spawner".

But if I put this spawner, and then I break it, then it will be called as it should be. But there is a nuance, the name of the mob in the name of the spawner item is again not taken from the localization file, it is always in English.

### Version Information

```shell
CMI 9.6.0.9
CMILib 1.3.1.1

https://imgur.com/a/x4J0p1f
```

### Errors

```shell
It doesn't throw errors in the console when starting the server/restarting the plugin/issuing a spawner.
```

### Relevant Config Sections

```yaml
In the previous version, in the CMILib localization file in the info category there was a spawner item, now it is not there, but it is present in the CMI localization file, perhaps this error occurs because of this.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Gets fixed with next CMILib update.
