### ISSUE TITLE
Can't Create DSigns

### ISSUE THREAD

**Issue by ValerianV** [Zrips/CMI#794]
Error when i use the commands /cmi dsigns new while looking a sign.

![image](https://user-images.githubusercontent.com/42415928/44960161-ec0afc00-aefa-11e8-8294-b264815ff055.png)

**Cmi Version (using`/cmi version`):**  8.0.8.0

**Server Type (Spigot/Paperspigot/etc):** Spigot 

**Server Version (using `/ver`):** 1.13

**Comment by CloudeLecaw** [comment]
Dont worry this is a double posted. We allready have an issues thread that the dsigns do not work. Look in your console they also spam an error ;)

**Comment by xion87** [comment]
Is not fixed
https://gist.github.com/xion87/4dfc07d2a7ac48f0e31a0526ceeb82ae
Using latest CMI and 1.12.2

**Comment by CloudeLecaw** [comment]
hm Maybe a 1.12.2 Problem with this CMI version 
on spigot 1.13.1 it is fixed and works fine :§


so the Question is why it is broken in older spiger versions?

**Comment by xion87** [comment]
Is broken also with 1.8.9, so i think he fixed it for only 1.13.x

**Comment by Zrips** [comment]
A secondary fix will be issued with next update which should fix this one and avoid any future errors related to this method.
