### ISSUE TITLE
Wrong mob name in spawner name.

### ISSUE THREAD

**Issue by samparotony228** [Zrips/CMI#7941]
### Description of Issue

When I got the spawner with the command "/give spawner:cow" I got the name of the mob in the name of the spawner - right, from the CMILib localization file. But when I put the spawner on the ground and then break it, the name of the mob on the spawner is displayed incorrectly, not from CMILib.

Video: https://youtu.be/yZzpVCC8zWk

### Version Information

```shell
CMI - 9.6.1.0
CMILib - 1.3.1.2
https://imgur.com/a/RYTQSDO
```

### Errors

```shell
It does not throw errors in the console when starting the server/restarting the plugin.
```

### Relevant Config Sections

```yaml
The configuration is visible in the video.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Good point, will use CMILib locale line entirely, no need to duplicate that one.

**Comment by samparotony228** [comment]
> Good point, will use CMILib locale line entirely, no need to duplicate that one.

With the new update this is not fixed again...
