### ISSUE TITLE
Home editing for non-oped players

### ISSUE THREAD

**Issue by FalityZ** [Zrips/CMI#7943]
### Description of Issue

I don't know exactly if it's a bug or if I'm just stupid and can't find how to activate it.. :D

Players without OP cannot see the home edit lores "Click Q to edit" , "Shift+Right Click to remove home" and cannot edit their homes. What permission does that thing need? I tried to search on the website, in the game with checkperm and searching for info in config but no luck x((

Here are the permissions I've added

cmi.command.home
cmi.command.homes
cmi.command.homes.range
cmi.command.removehome
cmi.command.sethome
cmi.command.sethome.2
cmi.command.sethome.customloc
cmi.command.sethome.iconpicker
cmi.command.sethome.overwrite

### Version Information

```shell
CMI: 9.6.1.0 MySQL
CMILib: 1.3.1.2 
Server: PufferfishPlus 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Enabled
Modules -> 55 enabled 3 disabled: tablist, playerCombat, headDrop
```

### Errors

```shell
none
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Small bug, will fix that one with next update
