### ISSUE TITLE
Players cannot put on mob heads

### ISSUE THREAD

**Issue by siulung201314** [Zrips/CMI#7946]
### Description of Issue

After updating from 9.6.0.9 to 9.6.1.0, players cannot put on mob heads by directly shift clicking the mob heads in their inventory.
They can only put on the mob heads by using command /hat.
I think the issue is caused by one of the changes in 9.6.1.0 - Updated inventory hat handling to more properly handle situations when you shift click items which should not be allowed to be used as hats.

### Version Information

```shell
CMI: 9.6.0.1.0
CMILib: 1.3.1.2
Purpur:2026 (MC: 1.20.1)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by XXY233** [comment]
Same issue, my players can't wear any player_head anymore.

**Comment by CloudeLecaw** [comment]
do they have the permission "cmi.inventoryhat." ?

**Comment by Zrips** [comment]
Will be fixed with next update. Will add additional option to require permission node (cmi.inventoryhat) or not for putting mob heads on.
