### ISSUE TITLE
ItemsAdder's nbt items are not supported as custom synthesis materials, but can be used as output items.

### ISSUE THREAD

**Issue by NEIKI19914** [Zrips/CMI#7947]
### Description of Issue

Other plug-in nbt items are supported as materials for custom synthesis, but the nbt items of ItemsAdder seem to be unable to be used as materials for custom synthesis. I don't know if this is a bug or cmi is not compatible with ItemsAdder.

### Version Information

```shell
[11:23:21 INFO]: CMI 插件版本: 9.6.1.1 BungeeCord CMIB  MySQL
[11:23:21 INFO]: CMILib: 1.3.1.2 
[11:23:21 INFO]: 服务器版本: Purpur 1.20.1-R0.1-SNAPSHOT
[11:23:21 INFO]: CMI 经济: 启用 经济: 1.7.3-b131(CMIEInjector) CMI 聊天: 启用 
[11:23:21 INFO]: 模块 -> 56 已启用 2 已禁用: tablist, votifier
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
where is the bug here?

it never was supported to use them as materials.
so its not a bug its a not exing support.
yoi need to ask in github discussion and request it.

**Comment by NEIKI19914** [comment]
> where is the bug here?
> 
> it never was supported to use them as materials. You can be lucky that name and lored vanilla items are supported now ;) so its not a bug its a not exing support. yoi need to ask in github discussion and request it.

However, nbt items generated by other plugins are supported as synthesis materials...

**Comment by CloudeLecaw** [comment]
that doesnt matter.
its offical stated that ItemAddder is not supported
