### ISSUE TITLE
The "Press X to standup again" translation does not exist

### ISSUE THREAD

**Issue by AnimeDrache** [Zrips/CMI#7948]
### Description of Issue

I wanted to change the text for when you sit on stairs. In german it says "Drücke umschalt links, um abzusteigen" but you can't find this text anywhere to change it. You can change other sit text messages like the "You stood up" but not the "press x to standup" text cause it is nowhere.

### Version Information

```shell
9.6.1.1
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by MrCrazys** [comment]
If you mean the `Press X to dismount` button, that's built in to Minecraft as far as I'm aware.

**Comment by AnimeDrache** [comment]
Ahhh I see. Cause we did use the Addon GSit before. There we were able to change that. It did also confuse me cause you can change everything like "Stand up" message or "Slot already taken" but you can't change the "Press x to standup"? Would be nice if it was possible cause GSit has it in (no front, seriously, I love CMI hehe but it would be nice <3).

**Comment by CloudeLecaw** [comment]
you will not find it, because technicly sitting is like riding.
the message is triggerted from your Client and its libe is baes on your using Client language.

you get the same measage when you sit on a pig or horse to ride it.

**Comment by Zrips** [comment]
Will add some work around, will not be excellent solution as there isint easy way to block vanilla message, but we can try to override it with different message. Next update.

**Comment by CloudeLecaw** [comment]
i hope this does not result in "we see both messages" like it was with the x players sleeping in world message ;)

**Comment by AnimeDrache** [comment]
Well as I said before, the Plugin "GSit" does have this inside. I totally get your explanation but I can tell you there is no double message in GSit. So they managed to do it somehow. I have NO CLUE at all for programming haha plus I can deal without that feature, but if possible, I would of course appreciate it a lot! ♥♥♥
