### ISSUE TITLE
Sleeping Bossbar/Title doesnt work

### ISSUE THREAD

**Issue by AnimeDrache** [Zrips/CMI#7949]
### Description of Issue

For some reason there is no bossbar or title when people sleep. Would be nice to see any information like "Enough people sleep so the night will be skipped".

This is the setting I do talk about that has no function at our server: https://prnt.sc/tG70JiQ96y8A

### Version Information

```shell
9.6.1.1
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
You should see message like this one when this is enabled 
![image](https://github.com/Zrips/CMI/assets/10416201/089095b2-507b-4fc8-ba67-828bf8664b75)
And I need output from **/cmi version** command to have better idea what I'm dealing here with

**Comment by AnimeDrache** [comment]
Here is what happens when I sleep: https://gyazo.com/ccd0dca11015b5caefeeb80aeadccf56
Here is my **config** with BOSSBAR inside: https://prnt.sc/x1FK2DUCrc9C
Here is my **/cmi version**: https://prnt.sc/q16UL-2pFBKr

**Comment by AnimeDrache** [comment]
I know you are probably busy with a lot of things (CMI is a huuuuge project). Still wanted to "push" this here as a little reminder, cause at the moment we still have to use another sleep plugin which I would really love to get rid off. But then the bossbar problem must be fixed please ♥.

**Comment by AnimeDrache** [comment]
So yes, this seems to be a bug that needs to be investigated. Some more discord user can't use the bossbar as well.

**Comment by Zrips** [comment]
In your case you have entire night being skipped, which can happen if all users in that world are sleeping or you are the only one. At the moment server takes full control over it and skips entire night automatically, so not much I can do about that one. In this case boss bar will not be shown. Is this an issue while you have more than one player online in same world? Keep in mind that separate worlds are separate, so its really based on the one you currently are in.

**Comment by AnimeDrache** [comment]
> In your case you have entire night being skipped, which can happen if all users in that world are sleeping or you are the only one. At the moment server takes full control over it and skips entire night automatically, so not much I can do about that one. In this case boss bar will not be shown. Is this an issue while you have more than one player online in same world? Keep in mind that separate worlds are separate, so its really based on the one you currently are in.

Sorry again for the second ticket but well I wait for over a month now so I did worry if my ticket was missed hehe =).

Well once the "limit of people that are needed to skip" is reached, the bossbar is not showing during the skip. Is the bossbar used different? Because I though tthe bossbar appears during the sleep process (we are currelty using the plugin "Harbor" which does that. it shows a boss bar during the skip process so I thought CMI would do the same so we could remove Harbor)

**Comment by Zrips** [comment]
it does show bossbar just like the one I showed in previous post. Tho keep in mind that it only appears if you dont have 100% of players sleeping in that world at one time. Boss bar should appear at the moment you enter bed at night. Hard to say what's going on in your situation without some testing.

**Comment by AnimeDrache** [comment]
Alright I will change the settings so 2 people are needed while 3 are online to see if it appears then. I thought the bossbar comes DURING the skip process (as in "Harbor") but if this here works different, then I know it still works and is no bug. I will tell you once I had 3 people for tests
