### ISSUE TITLE
Armor stand with armor trims are not saved in templates

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#7952]
### Description of Issue

When you equip an armor-stand with armor trim, and then want to save it as a template and retrieve it, you get back an armor-stand but without the armor trims.

### Version Information

```shell
Server: Purpur 1.20.1-R0.1-SNAPSHOT
CMI economy: Activée Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Activée
Modules -> 22 enabled 36 disabled: spawnerProximity, cuffed, mirror, tablist, versionCheck, armorEffects, moneyCheque, skin, noTarget, bossBarCompass, chatBubble, playerCombat, votifier, cooldown, headDrop, spawnerCharge, vanish, namePlates, timedCommands, homeInteractions, hpBossBar, launchPad, anvilRenameColor, jail, spawners, dynamicSigns, durabilityLoss, flightCharge, deathMessages, disabledEnchants, worldLimitsElytra, worldLimits, ranks, sitAnimation, warmup, totemBehavior
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Are you on latest CMILib version? And can you elaborate what you mean here exactly when you say that you cant retrieve it? Some pictures could help out here too, if possible.

**Comment by NoltoxGit** [comment]
> Êtes-vous sur la dernière version de CMILib? Et pouvez-vous préciser ce que vous voulez dire ici exactement quand vous dites que vous ne pouvez pas le récupérer? Quelques photos pourraient aider ici aussi, si possible.

Hello,
Yes i am on the latest build of CMILib, and here's a video, I think it's more illustrative than words 😅

https://github.com/Zrips/CMI/assets/75265787/add190b3-6127-4e8b-8264-de3029a8fde9

**Comment by Zrips** [comment]
Ok, that helped. Should be resolved with next CMILib update
