### ISSUE TITLE
Armorstand naming without creative mode

### ISSUE THREAD

**Issue by pacificminer** [Zrips/CMI#7954]
### Description of Issue

Players cannot click the "Middle mouse click to edit name" unless they are in creative mode.
This was possible in the past.

### Version Information

```shell
CMI Version 9.6.1.1
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
you may noticed that this is no bug.
its an issue with minecraft itself they have no evebt for middleclick anymore for gm2 and gm0

therefor zrips added a new option to press Q.
if you see an Informationen about pressing middle click you might should think about if it is usefull for you to change the teyt in cmis langfile to press Q, as Q can alao be used if your gm 1
