### ISSUE TITLE
/recipe candle is missing

### ISSUE THREAD

**Issue by rockit7** [Zrips/CMI#7955]
### Description of Issue

The /recipe for candle is missing. It shows if you do /recipe honeycomb, but not if you do /recipe candle. It shows how to dye, and undye the candles but not how to actually craft a candle. 

### Version Information

```shell
CMI version 9.6.1.1
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
As of testing all looks to be working, double check that you have latest CMILib in addition to CMI. if issue still there then let me know, but without knowing even version of your server its hard to determine cause of the issue. 
If issue persists give me output from **/cmi version** command
Closing ticket for now.
