### ISSUE TITLE
Portal Particles Break in CMILib 1.4.0.0

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#7957]
### Description of Issue

Particles on existing and new portals have all broken/stopped generating upon update to CMILib 1.4.0.0. Turning them off and on again, both the portal and particle controls, has no effect. I have not been able to get an error out of it - everything looks normal otherwise, both during startup and normal run.

### Version Information

```shell
CMI plugin version: 9.6.1.1 BungeeCord CMIB SqLite
CMILib: 1.4.0.0 
Server: Paper(72) 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 56 enabled 2 disabled: ranks, skin
```

### Errors

```shell
n/a
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next CMILib update
