### ISSUE TITLE
How to do this

### ISSUE THREAD

**Issue by Enkixp** [Zrips/CMI#7962]
hello
I wanna know if i can use the mentioned (playername) in command in custom text
Like if i use command
/ctext votes player2, i want so it gives me the data of player2
the votes custom text.txt has data of player votes
I want to make it so I can see the data other other players vote
In simple 
If i use the command 
ctext votes (I want the args mentioned player parsed placeholder in custom text
what would it be

**Comment by Zrips** [comment]
Things like that can utilize global variables like [playerName] and similar, you can find list of those inside locale file
