### ISSUE TITLE
CMI CRASHING SERVER

### ISSUE THREAD

**Issue by OndraCraft** [Zrips/CMI#7964]
### Description of Issue

CMI starts about 4,700 processes and crashes the entire server when the first players connect.

After the discussion with the hosting, the normal number of processes is around 100 to 250, however, we have 510 during a standard run.

We were advised to contact the author directly

### Version Information

```shell
CMI plugin version 9.6.1.2
LIB 1.4.0.1
Server - 1.19.4
```

### Errors

```shell
https://mclo.gs/oMFyXlJ
```

### Relevant Plugins

 CMIEInjector1.0.2.3.jar
 Vault-1.7.3.jar
 Residence5.1.2.0.jar

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by OndraCraft** [comment]
Btw

**[CMI] Checking... 11 502/399**

**Comment by Zrips** [comment]
Working on a fix, give me an hour or so and there should be new version

**Comment by Zrips** [comment]
Ok, will be fixed with today's small update
