### ISSUE TITLE
Players cannot wear player heads (mob heads are fine)

### ISSUE THREAD

**Issue by NightFuryStrike** [Zrips/CMI#7972]
### Description of Issue

Greetings, I am having an issue where players cannot equip player_heads without the cmi.inventoryhat permission.
Mob heads work fine, but you may have missed player heads in your recent update.
Thank you for your time.

### Version Information

```shell
[19:45:06 INFO]: --------------------------------------------------
[19:45:06 INFO]: CMI plugin version: 9.6.1.3 BungeeCord CMIB  SqLite
[19:45:06 INFO]: CMILib: 1.4.0.1 
[19:45:06 INFO]: Server: Paper(83) 1.20.1-R0.1-SNAPSHOT
[19:45:06 INFO]: CMI economy: Enabled CMI Chat: Enabled 
[19:45:06 INFO]: Modules -> 53 enabled 5 disabled: hpBossBar, disabledEnchants, customMessages, ranks, anvilRenameColor
[19:45:06 INFO]: --------------------------------------------------
```

### Errors

```shell
No Errors
```

### Relevant Config Sections

```yaml
Hat:
    # When enabled we will not allow to place items into head slot if item has custom lore
    IgnoreLored: false
    # When enable we wont allow to equip items which are not hat type and has enchantment on it
    # This will prevent from players having enchantment effects in head slots which should not be present there
    BlockArmorItems: false
    # When enabled we will allow player to put on mob head without cmi.inventoryhat permission node
    # When disabled player will need to have cmi.inventoryhat to put on mob heads as hats
    AllowMobHeads: true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
do they have the permission cmi.inventoryhat?

if you updated to last cmi version there should be a new extra options to allow the heads without this permission too if you defined it

**Comment by NightFuryStrike** [comment]
They don’t, and I don’t want to give my players the permission because it lets them wear everything.

If you look at my config in my report, I have that option enabled. It works for mob heads but not for player heads. I use player heads for custom armor/helmets and players can’t wear them anymore, even with the config option.

**Comment by siulung201314** [comment]
Same issue here.

**Comment by Zrips** [comment]
Should be resolved with latest versions.
