### ISSUE TITLE
Console Error: [Server] WARN in 'reader', line 55, column 1:

### ISSUE THREAD

**Issue by minercract** [Zrips/CMI#7973]
### Description of Issue

Console is showing these everytime I start the server.

17.07 07:27:03 [Server] WARN in 'reader', line 55, column 1:
17.07 07:27:03 [Server] WARN default: 1
17.07 07:27:03 [Server] WARN ^
17.07 07:27:03 [Server] WARN at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111)
17.07 07:27:03 [Server] WARN at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
17.07 07:27:03 [Server] WARN at CMILib1.4.0.0.jar//net.Zrips.CMILib.FileHandler.ConfigReader.getyml(ConfigReader.java:266)
17.07 07:27:03 [Server] WARN at CMILib1.4.0.0.jar//net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:49)
17.07 07:27:03 [Server] WARN at CMILib1.4.0.0.jar//net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:40)
17.07 07:27:03 [Server] WARN at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Homes.HomeManager.loadConfig(HomeManager.java:178)
17.07 07:27:03 [Server] WARN at CMI-9.6.1.3.jar//com.Zrips.CMI.Config.load(Config.java:1419)
17.07 07:27:03 [Server] WARN at CMI-9.6.1.3.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1527)
17.07 07:27:03 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
17.07 07:27:03 [Server] WARN at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
17.07 07:27:03 [Server] WARN at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
17.07 07:27:03 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
17.07 07:27:03 [Server] WARN at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:562)
17.07 07:27:03 [Server] WARN at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:473)
17.07 07:27:03 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
17.07 07:27:03 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
17.07 07:27:03 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
17.07 07:27:03 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
17.07 07:27:03 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
17.07 07:27:03 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
17.07 07:27:03 [Server] WARN Caused by: while scanning a simple key
17.07 07:27:03 [Server] WARN in 'reader', line 54, column 3:
17.07 07:27:03 [Server] WARN Groups
17.07 07:27:03 [Server] WARN ^
17.07 07:27:03 [Server] WARN could not find expected ':'
17.07 07:27:03 [Server] WARN in 'reader', line 55, column 1:
17.07 07:27:03 [Server] WARN default: 1
17.07 07:27:03 [Server] WARN ^
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:502)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:307)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:237)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:639)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:241)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:205)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575)
17.07 07:27:03 [Server] WARN at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104)
17.07 07:27:03 [Server] WARN ... 19 more
17.07 07:27:03 [Server] INFO Failed to load Homes.yml! Backup have been saved into plugins/CMILib/FileBackups/2023-07-17 07-27-03 Homes.yml
17.07 07:27:03 [Server] WARN org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
17.07 07:27:03 [Server] WARN in 'reader', line 54, column 3:
17.07 07:27:03 [Server] WARN Groups
17.07 07:27:03 [Server] WARN ^
17.07 07:27:03 [Server] WARN could not find expected ':'
17.07 07:27:03 [Server] WARN in 'reader', line 55, column 1:
17.07 07:27:03 [Server] WARN default: 1
17.07 07:27:03 [Server] WARN ^
17.07 07:27:03 [Server] WARN at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111)
17.07 07:27:03 [Server] WARN at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
17.07 07:27:03 [Server] WARN at CMILib1.4.0.0.jar//net.Zrips.CMILib.FileHandler.ConfigReader.getyml(ConfigReader.java:266)
17.07 07:27:03 [Server] WARN at CMILib1.4.0.0.jar//net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:49)
17.07 07:27:03 [Server] WARN at CMILib1.4.0.0.jar//net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:40)
17.07 07:27:03 [Server] WARN at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Homes.HomeManager.loadConfig(HomeManager.java:178)
17.07 07:27:03 [Server] WARN at CMI-9.6.1.3.jar//com.Zrips.CMI.Config.load(Config.java:1419)
17.07 07:27:03 [Server] WARN at CMI-9.6.1.3.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1527)
17.07 07:27:03 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
17.07 07:27:03 [Server] WARN at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
17.07 07:27:03 [Server] WARN at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
17.07 07:27:03 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
17.07 07:27:03 [Server] WARN at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:562)
17.07 07:27:03 [Server] WARN at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:473)
17.07 07:27:03 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
17.07 07:27:03 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
17.07 07:27:03 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
17.07 07:27:03 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
17.07 07:27:03 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
17.07 07:27:03 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
17.07 07:27:03 [Server] WARN Caused by: while scanning a simple key
17.07 07:27:03 [Server] WARN in 'reader', line 54, column 3:
17.07 07:27:03 [Server] WARN Groups
17.07 07:27:03 [Server] WARN ^
17.07 07:27:03 [Server] WARN could not find expected ':'
17.07 07:27:03 [Server] WARN in 'reader', line 55, column 1:
17.07 07:27:03 [Server] WARN default: 1
17.07 07:27:03 [Server] WARN ^
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:502)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:307)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:237)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:639)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:241)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:205)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157)
17.07 07:27:03 [Server] WARN at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575)
17.07 07:27:03 [Server] WARN at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104)
17.07 07:27:03 [Server] WARN ... 19 more

### Version Information

```shell
I'm using version 9.6.1.3
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Improperly formated file for homes. Double check for error in formatting or use something like this site https://codebeautify.org/yaml-parser-online to parse yaml files for possible issues before saving it
