### ISSUE TITLE
PAPI Placeholders for glow doesn't work

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#7977]
### Description of Issue

Hello,
While trying to create a menu with glow checks, I just noticed that the following two placeholders return nothing:
- `%cmi_user_glow_name%`
- `%cmi_user_glow_code%`

But I've already activated my glow.

### Version Information

```shell
CMI: 9.6.1.3 SqLite
CMILib: 1.4.0.1
Server: Purpur 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Enabled
Modules -> 22 enabled 36 disabled: spawnerProximity, cuffed, mirror, tablist, versionCheck, armorEffects, moneyCheque, skin, noTarget, bossBarCompass, chatBubble, playerCombat, votifier, cooldown, headDrop, spawnerCharge, vanish, namePlates, timedCommands, homeInteractions, hpBossBar, launchPad, anvilRenameColor, jail, spawners, dynamicSigns, durabilityLoss, flightCharge, deathMessages, disabledEnchants, worldLimitsElytra, worldLimits, ranks, sitAnimation, warmup, totemBehavior
```

### Relevant Config Sections

```yaml
Config: https://pastebin.com/MwQsnwnT
```

### Relevant Plugins

Vault 1.7.3-CMI & PlaceholderAPI 2.11.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
If they do not return something, then the player has no glow color set.

**Comment by NoltoxGit** [comment]
> If they do not return something, then the player has no glow color set.

I obviously tried it when I had glow activated on me. I wouldn't have created this issue otherwise x)

**Comment by NoltoxGit** [comment]
Hello @Zrips,
Do you have any news about this bug? There are several updates to fix the various bugs in your plugin but not this one :/
