### ISSUE TITLE
Armor stand editting and minions

### ISSUE THREAD

**Issue by abhisantos** [Zrips/CMI#7978]
### Description of Issue

Players with permission to edit armorstands can edit any minion from jetsminions.
This was not supposed to happen.
If you could please add a compatibility with jetsminions, that blocks the editting of minions.

### Version Information

```shell
9.6.13
```

### Errors

```shell
No error
```

### Relevant Plugins

JetsMinions

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Can't really do much here as jetsminions are not attacking generic metadata to armor stands to indicate that those are special ones which could be used by other plugins without having special direct call to their API. Get into contact with jetsminions dev and ask him to add metadata to armor stands, something like "minion" or even "npc" would work. If that gets added then I can create special exception for it without big trouble.
