### ISSUE TITLE
CMI High Consumption

### ISSUE THREAD

**Issue by SrT3ddy** [Zrips/CMI#7979]
### Description of Issue

CMI is consuming too much of my server.

### Version Information

```shell
[01:56:11 INFO]: CMI: 9.6.1.3 BungeeCord  MySQL
[01:56:11 INFO]: CMILib: 1.4.0.1 
[01:56:11 INFO]: Server: Mohist 1.12.2-R0.1-SNAPSHOT
```

### Errors

```shell
https://spark.lucko.me/VKVoYau8Ha
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by the456gamer** [comment]
This looks to be caused by loading a chunk to get the homeicon, which takes a while to fetch from disk.
im not sure if it takes longer than usual due to mohist?

**Comment by SrT3ddy** [comment]
Well it seems that the problem was GriefDefender, I don't know why but it has already been solved
