### ISSUE TITLE
A couple of questions and a feature request

### ISSUE THREAD

**Issue by Zethrus** [Zrips/CMI#798]
A quick feature request: Any chance you could add a way to convert balances from the Fe economy plugin (running via MySQL) over to CMI economy?

1st question I have is: Is it currently possible to share the economy balance across multiple servers using the MySQL storage method for CMI? I don't want to share everything such as inventories, etc. I only want to share the players balance across multiple servers.

2nd question: Is it possible to run command as the player right clicking the block with an interactive command or no?
I couldn't find anything on this in the documentation for interactive commands.
Right now, it only seems to be running the command as console.

**Comment by Zrips** [comment]
There is no importers for Fe economy plugin, not currently atleast.
1st. You can use some 3rd party plugins like economy bridge which utilizes Vault api to sync balances between servers, atleast until CMI gets it own sync method.
2nd. Interactive blocks/entities utilizes specialized commands, what means that you can perform commands as who clicked or as console with basic variables like asPlayer! or asConsole! at start of command.
