### ISSUE TITLE
LuckPerms prefix not being picked up

### ISSUE THREAD

**Issue by AuzziPuppy** [Zrips/CMI#7987]
### Description of Issue

I am using `  GeneralFormat: '{prefix}%deluxetags_tag%&f{displayName} &7» &r{message}'` to format the chat, both ModifyChatFormat and ClickHoverMessages are set to true at the beginning of the config file.

https://i.imgur.com/EtDIRqZ.png This is the outcome, it is not properly outputting the luckperms prefix.

I tried using %cmi_color_{prefix}% , %cmi_color_{luckperms_prefix}% and changing {prefix} in the original format to {luckperms_prefix} and %luckperms_prefix%, none of which worked.

No errors in console either. 

### Version Information

```shell
https://i.imgur.com/7nD9BTl.png
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Well you do have some weird hex color codes in your prefix, those are not being processed as those will not be recognized as valid ones. We are using either {#66ff66} format or if enabled in CMILib we can try to detect #662244 and/or &#662244 type ones. You have some of those which uses &#bb06fb format, so those will not be translated by default as its not official one we are using. Just visit CMILib config file and enable QuirkyHex
