### ISSUE TITLE
VAULT not detected.

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#799]
**Description of issue or feature request:**
After updating to the latest CMI version it seems like vault is no longer detected even though in the config economy is enabled. It works with the last version no problem. Using your compiled vault version. 1.6.10
EDIT***

It looks like CMI doesn't work on 1.13 anymore. Only 1.13.1?

**SECOND EDIT***
yeah something is not right. Vault is not loading at all on 1.13.1 either.**

**Cmi Version (using`/cmi version`):**  8.0.8.1

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):**  1.13

**Comment by MCTyler** [comment]
Close it then......

**Comment by 0xC1A551C** [comment]
@MCTyler no idea how.
