### ISSUE TITLE
Cooldown doesnt work if text too long (CustomAlias)

### ISSUE THREAD

**Issue by AnimeDrache** [Zrips/CMI#7992]
### Description of Issue

A weird issue: when the text of our cmds is too long, then the cooldown on it has no effect. Means: when we use the shorter version ( https://gyazo.com/4f40801cd4d0c62b3819a4f876000c65 ) then it all works fine. If we use the longer text version ( https://gyazo.com/5fb1b15fd3756004c0a1831f6006e066 ) then no message will be send but the "Player is live" text all the time, even when there should be a cooldown on that broadcast message.

### Version Information

```shell
9.6.1.3
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Can you provide actual alias example in a text format? Would be simpler to test it out and determine cause of the failure. In general length of text should not have effect as I have tested it with exponentially longer message, so something specific in your example causes this issue. Your placeholders could be source of issue too.

**Comment by AnimeDrache** [comment]
Sure, this is the text that causes this issue to me:

    - cooldown:300?! asConsole! lp user [playerName] meta removeprefix 110 Live
    - delay! 0.1
    - cooldown:300! asConsole! cmi broadcast !&d🎬 &a&l[playerName] &f&list &c&lnicht mehr &d&lLive &c● &f&o[&7&olocaltime_time_HH:mm:ss%&f&o] [%conditionaltext_ort_kursiv%&o]
    - cooldown:300! asConsole! cmi sound entity_illusioner_prepare_mirror -s
    
    
    If you say it can be the placeholder, then it would be difficult for u to test cause we do use even "custom made" placeholders with the plugin "Conditionaltext Placeholders"

**Comment by Zrips** [comment]
Can you test this with different placeholders in it to check if issue gets resolved? Or strip down everything else and only keep one of the placeholders to see if its still failing or not.

**Comment by AnimeDrache** [comment]
weird, for some reason it does work now. did you change something with the ne 9.6.2.1 version?

**Comment by Zrips** [comment]
Can't say I recall any changes relating to this in particular, it could have been issue with placeholder itself inserting some weird value before which broke things.
