### ISSUE TITLE
How to convert/insert bans from another plugin? Urgent

### ISSUE THREAD

**Issue by IvIurdoc** [Zrips/CMI#800]
I've recently switched over from CommandBook to CMI and was wondering if there was a way to convert or insert my bans.csv file into the plugin. I'm not sure if my bans carried over from the switch as ./banlist only shows about 7-8 bans from when we used to use Essentials back in 2014. Is there any way I could implement my ban list into the plugin or is there no need to? Thank you!

**Comment by CloudeLecaw** [comment]
I think this is not possible. As far as i knwo CMI works wind the banfile in the servers nainfolder. The fornattof it is this json format. So u would need a Formater from you csv file to this json Format.

**Comment by Zrips** [comment]
Well @CloudeLecaw is correct, CMI uses official API to ban and unban players, its not creating any extra files and this method is allot more compatible with another plugins which could access bans with basic API. So no, you cant convert bans from your old plugin, for this you would need that plugin dev to make converter to vanilla ban system.
