### ISSUE TITLE
cmi clear [playerName] ignoring  blocks

### ISSUE THREAD

**Issue by 7hatGuyAJ** [Zrips/CMI#8002]
### Description of Issue

/cmi clear [playerName] glowstone +armorslots and /cmi clear glowstone both ignore the head slot when a specific block is specified, In this case "glowstone" when the command is run without specifying glowstone as in /cmi clear [playerName]  the glowstone is removed from the head slot.

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.1.3 BungeeCord CMIB MySQL
CMILib: 1.4.0.1
Server: Paper(83) 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
Modules -> 55 enabled 3 disabled: tablist, votifier, vanish
--------------------------------------------------
```

### Relevant Plugins

Vault: 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next version
