### ISSUE TITLE
Can't use CustomModelData: to specify item when using /clear "item" 

### ISSUE THREAD

**Issue by 7hatGuyAJ** [Zrips/CMI#8008]
### Description of Issue

I'm currently trying to clear an item with "cmi clear [playerName] tripwire_hook{CustomModelData:2}:-10 -s"  /cmi clear, ignores CustomModelData: and takes from the first named item / stack in the inventory.  

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.1.3 BungeeCord CMIB MySQL
CMILib: 1.4.0.1
Server: Paper(83) 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
Modules -> 55 enabled 3 disabled: tablist, votifier, vanish
--------------------------------------------------
```

### Errors

```shell
No errors in console.
```

### Relevant Plugins

Vault: 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next CMILib and CMI updates. Tho keep in mind that correct format would look like
**tripwire_hook{CustomModelData:2}-10**
