### ISSUE TITLE
New Hologram size change on server restart

### ISSUE THREAD

**Issue by tomhmagic** [Zrips/CMI#8019]
### Description of Issue

On server restart, holograms that have their height scale more than 1 gets reset to 1. Width seems to be fine.

### Version Information

```shell
CMI: 9.6.2.0 BungeeCord CMIB SqLite
CMILib: 1.4.0.2
Server: Pupur 1.20.1-R0.1-SNAPSHOT
```

### Errors

```shell
N/A
```

### Relevant Config Sections

```yaml
N/A
```

### Relevant Plugins

CMI

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
This was fixed with 9.6.2.1 version
