### ISSUE TITLE
New feature suggestion: block entity spawn

### ISSUE THREAD

**Issue by beeng9** [Zrips/CMI#802]
**Description of issue or feature request:**

I wish that CMI has the ability to prevent entity spawning each species

It's a feature of Essentials.

And I think it's good feature. But, I can't find this in CMI

**Comment by CloudeLecaw** [comment]
You mean deny spawn if a mob in a choosen world? 😊

I know MobFarmManager is not ready for 1.13.1 at the Moment but may u wanne take a look in it if your using Lower Version of spigot..

**Comment by Zrips** [comment]
@beeng9 
You will need to elaborate on this feature request. What exactly do you mean by "prevent entity spawning each species"?

**Comment by LogGits** [comment]
I think he is referring to blocking the spawns of specific entities.

**Comment by CloudeLecaw** [comment]
i also think he means to block spawn of some entities variants like a brown horse, or a white bunny, etc...well in 1.14.x its solved that each variant has its own name..but for older versions...this may would be needed?
