### ISSUE TITLE
CMI Sound around a player doesnt work / not implemented yet

### ISSUE THREAD

**Issue by AnimeDrache** [Zrips/CMI#8024]
### Description of Issue

We played with the **/cmi sound** command. However it can play the specific sound for all player, for a specific player, for yourself or at a specific spot. But we are missing one feature: to play it around you, so people hear it when they are close to you but hear it less when they are far away from you. This way, we can simulate real ambient sounds (like fake zombies etc) around a player who is using a Zombie skin. But right now, that feature doesn't exist.

### Version Information

```shell
9.6.2.1
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by the456gamer** [comment]
So playing it at a specific spot, the location of the player?
This seems more like a feature request that a bug report

**Comment by AnimeDrache** [comment]
Whenever I open a ticket on github, I make sure to select the correct topic. So in this case "Future request" but it looks similar to the "isse" formular ( https://prnt.sc/UHc0PTU_F3oj ).

However yes, we are using a plugin to disguise as a mob. So it would be cool to play realistic creeper sounds at the "fake-mobs" location, instead on the whole server or fully loud to people when they see u are still too far away to sound so loud.

**Comment by Zrips** [comment]
This is more of a feature request and should have been posted at discussions section and not Issues one. In any case, will add extra variable as -l:[playerName] which will allow you to play sound at defined players location for everyone around. Next version.

**Comment by AnimeDrache** [comment]
Mega, thanks! It seems to work! Even though the -l doesn't apper in the chat: https://prnt.sc/3YJGEn2qv-js

**Comment by Zrips** [comment]
Good point, will add -l: into tab complete with next update

**Comment by AnimeDrache** [comment]
Cool! Can't wait for it! =D
