### ISSUE TITLE
command /give

### ISSUE THREAD

**Issue by samparotony228** [Zrips/CMI#8028]
Hi, could you tell me the full list of possible attributes for a command like /cmi give sponge a maxhealth:5:mainhand, where "maxhealth" is. For example, how to give speed? Damage, maybe the effect of a potion for a while, and so on...

**Comment by Zrips** [comment]
You can always use any minecraft give command generator to get extremely specific item. Something like this works https://www.gamergeeks.net/apps/minecraft/give-command-generator so any generic tag format will produce desired outcome. For that command in specific, there is a bug which will be resolved with next CMILib update, for time being you can use vanilla minecraft item tags to get what you want.
