### ISSUE TITLE
Spawner Egg changes for 1.13

### ISSUE THREAD

**Issue by glorying16** [Zrips/CMI#803]
The entity types for spawners have not yet been updated with the new eggs for 1.13. It will allow players to change the type with an egg without the permission for that specific type, while the older egg types act as they should when the permission is not granted.

**Cmi Version: 8.0.8.1** 

**Server Type: Spigot** 

**Server Version: 1.13.1**

**Comment by x1p** [comment]
Same in 8.0.9.0
Please fix

**Comment by Zrips** [comment]
With next update should be fixed.
