### ISSUE TITLE
On multiple servers, the money of cmi is not synchronized with each other

### ISSUE THREAD

**Issue by lipind** [Zrips/CMI#8031]
### Description of Issue

On one server use /money give *  123456

Players on the server will receive 123456 money, but they will not synchronize these to other servers

### Version Information

```shell
--------------------------------------------------
[02:29:55 INFO]: CMI 插件版本: 9.6.1.3 BungeeCord CMIB  MySQL-> 9.6.2.1
[02:29:55 INFO]: CMILib: 1.4.0.3
[02:29:55 INFO]: Server: Paper(1620) 1.12.2-R0.1-SNAPSHOT
[02:29:55 INFO]: CMI economy: true Vault: 1.7.3-CMI CMI Chat: Disabled
[02:29:55 INFO]: Modules -> 57 enabled 1 disabled: votifier
[02:29:55 INFO]: --------------------------------------------------
```

### Errors

```shell
not have
```

### Relevant Config Sections

```yaml
Economy:
 
  Enabled: true
  
  Confirmation: false
  
  LogEnabled: true
  log:
    Unknown: true
    Transfer: true
  Cheque:
   
   
    MaxValue: 1.0
    
    Paper: true
   
    Permission: true
  PaymentWithShorts:
  
  
    Allow: true

    values:
    - k-1000
    - m-1000000
    - b-1000000000
    - t-1000000000000
    - q-1000000000000000
  BalTop:
   
    Exclude:
    - abc
   
    DisplayWithShorts: false
    
    ExcludeStartingWith:
    - town_
    - town-
    - towny_
    - towny-
    - debt-
    - debt_
    
    IncludeFakes: false

    ExcludeInactive: 0
```

### Relevant Plugins

CMIEInjector1.0.2.3、CMILib1.4.0.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by MrCrazys** [comment]
This isn't an issue. Money isn't synchronized across servers with CMI. You need another plugin such as MySQLPlayerDataBridge for that to work.

**Comment by Zrips** [comment]
@lipind 
As database file indicates, you can't use same database on multiple servers as it will mess things up. You can use some dedicated plugins as @MrCrazys suggested here, to enable this capability.
