### ISSUE TITLE
FlightCharge Cannot use other economic purchases

### ISSUE THREAD

**Issue by lipind** [Zrips/CMI#8032]
### Description of Issue

Due to synchronization issues with multiple servers on Money（#8031）, so I config Economy:  Enabled: false

but FlightCharge still uses the internal money of CMI

### Version Information

```shell
--------------------------------------------------
[02:29:55 INFO]: CMI 插件版本: 9.6.1.3 BungeeCord CMIB  MySQL-> 9.6.2.1
[02:29:55 INFO]: CMILib: 1.4.0.3
[02:29:55 INFO]: Server: Paper(1620) 1.12.2-R0.1-SNAPSHOT
[02:29:55 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
[02:29:55 INFO]: Modules -> 57 enabled 1 disabled: votifier
[02:29:55 INFO]: --------------------------------------------------
```

### Errors

```shell
not have
```

### Relevant Config Sections

```yaml
Economy:
  Enabled: false
```

### Relevant Plugins

CMIEInjector1.0.2.3、CMILib1.4.0.3

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Remove CMIEInjector1.0.2.3 as it will force economy support. You can always double check what type of economy plugin uses at its startup, it should indicate exact type of it, for 
![image](https://github.com/Zrips/CMI/assets/10416201/e495f041-5d6c-4a6a-91db-116ab9334aa9)
