### ISSUE TITLE
`/tppos` is not affected by `cmi.safeteleport`

### ISSUE THREAD

**Issue by catter1** [Zrips/CMI#8038]
### Description of Issue

When using the `-rng` flag with `/tppos`, the safe teleport checks are not being activated. More specifically, there are no heightmap checks for the y-value.

For example, if you do `cmi tppos -p:[playerName] 0 64 0 world -rng:2000`, you will teleported within 200 blocks of `0 0`. However, it will force-teleport you to y=64, so if there's terrain there, you will start suffocating.

I have read #6794, which was closed due to it not needing to be intended, since that capability was reserved for `/cmi rt`. However, I believe that this functionality should be implemented: this is the closest way for a dynamic RTP. My goal is to create a command that uses PAPI coord variables from another plugin to RTP around certain coords per player.

As an alternative, I could create a Feature Request to implement center coords to the `/cmi rt` command (so it would either default to the config or get overriden by command arguments), if you would prefer that.

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.2.3 SqLite-> 9.6.2.2
CMILib: 1.4.0.3 
Server: Purpur 1.19.4-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 56 enabled 2 disabled: tablist, votifier
--------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by catter1** [comment]
This is still an issue.

**Comment by Zrips** [comment]
Will make it safer with next update, safer in a sense that it will check for possible suffocations and will try to check for valid location in 3 block range up/down

**Comment by catter1** [comment]
If it does not find a valid location within 3 blocks up/down, what will happen? Will it tp at the original y position, or fail? For my use-case:
- The former will only help reduce suffocation a small percentage of the time (if set to y=68, only would work for terrain between y=65 and 71)
- The latter technically works, but will vastly limits where the player will teleport (aka nowhere vaguely mountainous)

If either is the case, is it possible for there to be some sort of alternative in the future? Appreciate your time!
