### ISSUE TITLE
Spawners with HoverItems Problem

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#804]
**Description of issue or feature request:**
When hold a named spawner use hoveritem, it'll change name to the regular spawner.

```

**Cmi Version (using`/cmi version`):** 
8.0.7.0
**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
1.12.2

**Comment by Zrips** [comment]
Should be ok with latest build's

**Comment by coco0325** [comment]
Yeah! But there still has another problem is cmi won't display custom spawner's item name.
