### ISSUE TITLE
[config edit request] Add option to disable colors in books

### ISSUE THREAD

**Issue by envizar** [Zrips/CMI#8040]
I need something like this in `Settings/chat.yml`:
![img](https://github.com/Zrips/CMI/assets/87126318/cf848a88-4f26-46b7-acc5-1d55a4e43a31)

**Comment by CloudeLecaw** [comment]
you allready can clean up colors in books if you dont got permission...

**Comment by Zrips** [comment]
@envizar 
As Cloude mentioned here, you can already clean up color codes with that option, same cleanup process as it is for chat messages, without permission node to specific color codes will simply remove it preventing book from being colorized.
