### ISSUE TITLE
Unskin command

### ISSUE THREAD

**Issue by AnimeDrache** [Zrips/CMI#8048]
### Description of Issue

To turn off a **/skin** you normally use **/skin off**. I now wanted to create an alias so **/unskin** does that. However it turned out that **/unskin** is already coded to be **/skin** too. I think that shouldn't be, or? I mean, why would people be able to skin themself with **/unskin name**? Right now I can't create an custom alias to use **/skin off** when typing **/unskin**.

### Version Information

```shell
9.6.2.3
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
why you cant?

disable unskin in alias.yml and create a customalias then execute cmi skin off $1-
`/cmi aliaseditor unskin-cmi skin off $1-`

**Comment by AnimeDrache** [comment]
Well I don't know why but now it does work. Maybe the latest update?
