### ISSUE TITLE
Crashing Server when a player joins

### ISSUE THREAD

**Issue by AshiroKun** [Zrips/CMI#805]
**Description of issue:**
CMI is causing my minecraft server to crash everytime a player logs on. This causes an endless loop where the server is never stable.

List of plugins:
- FastAsyncWorldedit
- BlocksHub
- Chat Manager
- Coreprotect
- DeluxeMenus
- DivineItemRPG
- EasyBackup
- gobrush & gopaint
- iDisguise
- Multiverse
- Permissionsex
- Placeholderapi
- Plugman
- Protocollib
- Pyrcore
- Quests
- ServerListPlus
- Simplesit
- SkillAPI
- Vault
- Viaversion
- Viarewind
- Viabackwards
- Worldedit
- Voxelsniper
- Worldguard

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/UW8S69Gg
```

**Cmi Version (using`/cmi version`):** 8.0.8.1 (tried all versions)

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):** 1.12.2

**Comment by imhandmade** [comment]
I actually have this problem as well on 1.13. This plugin corrupts some player's profiles, causing them to crash the server when they join. ;c

**Comment by mercurialmusic** [comment]
Not sure if it's related, but my eventCommands for player joins were creating a good amount of lag every time someone joined, on 1.13.1, but I chalked it up to 1.13.1, not CMI. I disabled the join commands and it helped quite a bit (it was just a cmi sound command).

**Comment by Zrips** [comment]
@AshiroKun 
Full crash log would be nice to have as provided one doesn't really inform what exactly happen. Would recommend to default out all of your config file (make copy first) and then retest if that helps out. If it does, then some configuration causes this crash. Try to determine which one exactly.

**Comment by AshiroKun** [comment]
No worries. I have found the reason it was like that. There was no indication in the plugin that says it "must" use MySQL or SQLite to work. I just setup a MySQL and used that to store the CMI information and it worked.

Would be great if you add that in the spigot for anyone who doesn't know

Thanks.

**Comment by xion87** [comment]
i got the same issue, using clean spigot 1.13 and cmi, it crash 
# A fatal error has been detected by the Java Runtime Environment:
# SIGSEGV (0xb) at pc=0x000000000000a866, pid=64, tid=0x00007f3ebf88fae8
# JRE version: OpenJDK Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: OpenJDK 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.8.0
# Distribution: Custom build (Wed Jun 13 18:28:11 UTC 2018)
# Problematic frame:
# C 0x000000000000a866
# Core dump written. Default location: /home/container/core or core.64
# An error report file with more information is saved as:
# /home/container/hs_err_pid64.log
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
# http://icedtea.classpath.org/bugzilla
/entrypoint.sh: line 15: 64 Segmentation fault (core dumped) java -Xmx10142M -jar spigot.jar

**Comment by Zrips** [comment]
Updating java version to 8 build 181 or higher should resolve this issue
