### ISSUE TITLE
`/shoot dragonfireball` does not call detectable potion event

### ISSUE THREAD

**Issue by TheCashFire** [Zrips/CMI#8050]
I don't think this counts as a suggestion, more of a fix. The /shoot command currently allows for a Dragon Fireball to be shot, but when it lands, it does not call a potion event properly, and as such, the plugin Lands by Angeschossen cannot interpret it in order to protect entities against it. It should call this event (I'm not sure which one) in order for Lands to see it and protect entities appropriately.

If this does not make sense, please let me know!

**Comment by Zrips** [comment]
/shoot command simply launches projectile, it's not really controlling anything else besides this. 
Damage from that cloud and be detected by AreaEffectCloudApplyEvent or EntityDamageEvent and finally on hit you can just check ProjectileHitEvent.
As of some testing with real dragon and its projectiles, cant say that one fires up any additional events, so its behaving in same way.
Would suggest to simply avoid giving to the players this shoot projectile if its being abused by, other than it your Lands plugin will need to properly check events like that to properly block it if needed.
