### ISSUE TITLE
Seeing portals wand outline with no portals

### ISSUE THREAD

**Issue by moonies44** [Zrips/CMI#8051]
### Description of Issue

Hello. I logged in today and discovered that the outline particles used for the portals is showing in a area in my spawn. I have attached a video showing this issue. Where i also use the portals command to show there is no portals existing - i then created one for a test and deleted it then the portals particles vanished. This also vanishes when i don't create a portal. everytime i "find the particles" spawned, they seem to despawn 30 seconds later. is this a bug? No area's was selected with the shovel or the command was not used prior. bug is not reproduceable at will and happens randomly. (for example was working on my spawn npc's, and they suddenly was there when i turned around) but didn't have time to turn my recorder on prior.
Youtube video showing bug [https://youtu.be/Vmm_n3_oYUU](url)

### Version Information

```shell
CMI: 9.6.2.2 Bungeecord SQLite
CMILIB 1.4.0.3 > 1.4.0.4
server PurPur 1.20.1-R0-1.-SNAPSHOT
CMI economy enabled vault 1.7.3
chat : enabled
```

### Errors

```shell
Console does not produce any errors
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by moonies44** [comment]
Edit: Now seeing the box following me in different locations. Moved to a seperate area of my spawn to build, the box then re-appeared around me like in the video, and dissapeared 20 seconds later.

**Comment by Zrips** [comment]
Well this is unique issue you are having. It looks to be visualization of your current selection area which will appear at the moment you got 2 points selected for some period of time. It should never automatically turn on, so something is triggering it. Could be another plugin selecting areas with CMI API, could be some commands being performed which selects areas around you, but in general CMI will not show this without you selecting area with a tool or by performing command.
