### ISSUE TITLE
CMI Hoverboard

### ISSUE THREAD

**Issue by SirNecrosis** [Zrips/CMI#8054]
### Description of Issue

The CMI hoverboard doesn't support placeholders properly. They register with the amount of players but it doesn't live update to the correct amount of players when one leaves. For example, two players are online. You make the hoverboard with the placeholder api for %bungee_factions%. It doesn't work properly. If you do the %cmi_user_name% it saves as your username and doesn't show to others. Any fix?

### Version Information

```shell
9.6.2.0
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
What feature are we talking here exactly? There isint one named as Hoverboard, so some extra information on what it is would be nice to know just to narrow down possible issues.
