### ISSUE TITLE
Sleeping Bosbar still not working (to everyone)

### ISSUE THREAD

**Issue by AnimeDrache** [Zrips/CMI#8055]
### Description of Issue

This is a dublicate of my previous ticket from for many weeks ago. Many more people complain about this issue on the discord server but I worry my Ticket has not been seen anymore. So yea, the sleep bossbar doesn't work at all.

Previous ticket: https://github.com/Zrips/CMI/issues/7949

### Version Information

```shell
9.6.2.3
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Try to avoid duplicating tickets, check my answer to previous ticket.
