### ISSUE TITLE
Mail Tab Completer not working

### ISSUE THREAD

**Issue by AnimeDrache** [Zrips/CMI#8056]
### Description of Issue

When people try to /mail someone, they have no tab completer for player names. Weird thing his: I as admin do have a tab completer. So maybe it is inside a "wrong" permission.

### Version Information

```shell
9.6.2.3
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Tab completes are not really controlled by any type of permission nodes aside of your general access to that command. This is quite likely issue with different plugin using /mail command and overriding tab complete with its own values. 
You could try disabling mail alias in Aias.yml file from CMI and then create custom one with ingame command like `/cmi aliaseditor new mail-cmi mail $1-` which should create same alias, you will just have more customization options, which might or might not help out. Can't really do much here from my end.

**Comment by AnimeDrache** [comment]
I wonder which of my plugins uses mail. I will do some investigations but your suggesion could already be a workaround for us. I will let you know once I tested it about the result and then close the ticket if its solved.

**Comment by Zrips** [comment]
if you still have Essentials plugin, then that one will have /mail taken on its own. Otherwise you might need to disable few plugins and check if tab complete starts working.

**Comment by AnimeDrache** [comment]
No no I do not use essentials anymore since I have CMI. So yea I will test on my testserver my plugins step by step to see which it does. I start with just CMI to make sure it does work to me. I will inform you about the result.

**Comment by Zrips** [comment]
Ok, will reopen ticket then, just in case. Close it if solve it, just let me know what it was for future reference.
