### ISSUE TITLE
[bug] Failed to load item(wheat) in worth.yml - 1.12.2

### ISSUE THREAD

**Issue by momoservertw** [Zrips/CMI#806]
Failed to load item(wheat) in worth.yml.
-- Error message --
Failed to load worth for: 296
Failed to load worth for: WHEAT
###############################
CMI plugin version: 8.0.8.1
Server version: Spigot 1.12.2-R0.1-SNAPSHOT
Vault version: 1.6.10(+

**Comment by Zrips** [comment]
Should be ok with latest update now.
