### ISSUE TITLE
[BUG] langfile line command.tp.info.bad.plugin does not exists.

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#807]
```
  tp:
    help:
      info: '&eTeleports to player''s location'
      args: '[playerName] (playerName)'
    info:
      feedback: '&eYou have been teleported to &3[sourceDisplayName] &elocation (&3[offon]&e).'
      bad:
        msg: '&cTeleport location is unsafe. [reason]'
        extraMsg: '&eUse &6/tpbypass &eto bypass this. You have [time]'
        lava: '&cLava'
        void: '&cVoid'
        suffocation: '&cSuffocation'
        unknown: '&cUnknown'
```

![image](https://user-images.githubusercontent.com/12080017/45208409-cb3fff00-b28a-11e8-8213-af9dc6ccafe4.png)

the lang point in langfile for. command.tp.info.bad.plugin    does not exist :(

**Comment by Rukes** [comment]
Do you know what causes this? @CloudeLecaw

**Comment by CloudeLecaw** [comment]
a missing string in the langfile that you can add by yourself .... and yes i do

it is caused if u try to take yourself as targed ;3

**Comment by Zrips** [comment]
Will fix missing locale, tho it looks like some anticheat could block teleportation which would cause this message to appear.
