### ISSUE TITLE
Item sharing in chat: please, use item id if not possible to get the name of custom item

### ISSUE THREAD

**Issue by vgrynch** [Zrips/CMI#8073]
### Description of Issue

Tried CMI's item sharing on the hybrid server and it works great - none of the plugins do it that well! One minor thing though - see the image below. While the item itself is picked up correctly for displaying, the title says "Air" in the chat. Would be good to display at least an item ID instead (you surely have it ;) ). I understand it's a modded item and CMI might not have the means to get the correct name. But you probably always have an id. 

![image](https://github.com/Zrips/CMI/assets/46818018/bbdbea77-1e5b-4f2b-a878-92e4775ea510)

### Version Information

```shell
Server: hybrid Bukkit/Spigot server ArcLight 1.19.2 (Forge)
CMI: 9.6.2.3
```

### Errors

```shell
(No crashes, no warnings, and no other info in the logs related to this.)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by MC-MrBirdy** [comment]
You should be able to customize the text for that in the CMI\Translations.
It's under `Chat:` and `item:` with the default being `'&7[%cmi_iteminhand_realname%[amount]&7]'`.
See: [https://github.com/Zrips/CMI/blob/master/Translations/Locale_EN.yml#L319C1-L319C1](https://github.com/Zrips/CMI/blob/master/Translations/Locale_EN.yml#L319C1-L319C1)
You can use placeholders like `%cmi_iteminhand_displayname%`.

**Comment by vgrynch** [comment]
Works now! It shows IDs. Any way to add translations for them?
