### ISSUE TITLE
Custom Recipe

### ISSUE THREAD

**Issue by uploadx10** [Zrips/CMI#8078]
### Description of Issue

Before Create
https://i.imgur.com/GlX0R9w.png

After
https://i.imgur.com/4iHq9kM.png

custommodeldata unique

material: paper all custommodeldata 7/8

### Version Information

```shell
https://i.imgur.com/FAhokuL.png
```

### Errors

```shell
no
```

### Relevant Config Sections

```yaml
no
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should get fixed with next CMI and CMILib updates
