### ISSUE TITLE
AFK Timer increases playtime & /cplaytime command says feature not enabled ingame

### ISSUE THREAD

**Issue by ATRS04** [Zrips/CMI#8080]
I seem to be running into some issues relating to playtime, for one, even with the config "StopPlayTime" set to true, it still seems to be going up while players are AFK, this was with the /playtime and /playtimetop command

We also tried to get cplaytime command to run however it says ingame that the feature is not enabled, is it somewhere in the config to enable that command?

**Comment by ATRS04** [comment]
Minecraft version: 1.20.1
Paper version: git-paper-131
CMI version: 9.6.2.4
CMILib version: 1.4.1.0

**Comment by Zrips** [comment]
cplaytime is separate from general playtime. Cplaytime is fully by CMI and it will track players playtime in higher detail, tho it is disabled by default in config file. You can find it under CMIPlayTimeTracking section. 
For playtime still counting, which method are you using for player stats? This depends on your option under PlayTimeFromStats
