### ISSUE TITLE
New display methode in holograms does not support &u

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8082]
### Description of Issue
The New display methode of the hologramm settings in seems not be able to display the &u for the colorchaning format if used.

Here the old methode
![image](https://github.com/Zrips/CMI/assets/12080017/6b5e247c-36bc-45aa-81d7-d9523e582391)

and here the new desplaymethode one
![image](https://github.com/Zrips/CMI/assets/12080017/775a7518-04c0-4ca1-8c1c-445821164b79)

### Version Information
![image](https://github.com/Zrips/CMI/assets/12080017/add1faab-bd64-4df7-bb7b-d6a6a8ebb340)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version
