### ISSUE TITLE
Shift Edit Permission Overrides Protections

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#8089]
### Description of Issue

We've recently discovered that players with ```cmi.signs.shiftedit``` were able to edit signs in protected areas (basically the behavior was as if they had ```cmi.signs.shifteditbypass``` -- but I was very careful to ensure they did NOT have the bypass perm). I removed ```cmi.signs.shiftedit``` from everyone for now, which at least temporarily solves the issue. I'm afraid I'm not able to determine whether this is a new thing or a part of the old signs issue that slipped by.

### Version Information

```shell
CMI plugin version: 9.6.2.5 BungeeCord  SqLite
CMILib: 1.4.1.1 
Server: Paper(160) 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 57 enabled 2 disabled: ranks, skin
```

### Errors

```shell
No errors printed in console.
```

### Relevant Plugins

Residence 5.1.3.0; LuckPerms 5.4.102

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Well its ongoing thing, I guess your players have use flag in those areas which then enables option to edit signs. Will have to change it to something else or use multiple flags. Not an issue with CMI in particular, more of a Residence thing. Should be fixed with next update.

**Comment by mercurialmusic** [comment]
> Well its ongoing thing, I guess your players have use flag in those areas which then enables option to edit signs. Will have to change it to something else or use multiple flags. Not an issue with CMI in particular, more of a Residence thing. Should be fixed with next update.

This might also be a misunderstanding on my part - I was under the impression that the use flag was required for players to use shop signs, elevator signs, etc., which it did seem to fix for those since previously they couldn't use shop signs. I guess we just need to figure out a way where protected areas (where they don't have build permissions, for example) prevent sign editing but still allow for interactive signs.
