### ISSUE TITLE
[bug] Armor stand wouldn't disappear after leaving the seat

### ISSUE THREAD

**Issue by momoservertw** [Zrips/CMI#809]
![image](https://user-images.githubusercontent.com/38014059/45228188-155dca80-b2f5-11e8-990a-cb4645af57fd.png)
![image](https://user-images.githubusercontent.com/38014059/45228285-5eae1a00-b2f5-11e8-8d7a-39910d031860.png)
Because of the Armor Stand can't change any flags, so I can't remove it.
###############################
CMI plugin version: 8.0.8.1
Server version: Spigot 1.12.2-R0.1-SNAPSHOT
Vault version: 1.6.10(+

**Comment by Zrips** [comment]
Will add command (/cmi util remove) to remove any bugged out sits from worlds
