### ISSUE TITLE
Can't custom /recipe menu + title

### ISSUE THREAD

**Issue by Teyir** [Zrips/CMI#8094]
Hello,

We can't custom the /recipe menu and the title.

![image](https://github.com/Zrips/CMI/assets/60007549/f32bcdbf-8d0e-47b5-95f3-243994ea560b)

I use CMI 9.6.2.5 + latest CMILib version.

And I have a question, can we use PlaceholderAPI inside menu title ?

Thank you very much

**Comment by Zrips** [comment]
Will add option to localize those recipe type names with next update. And no, placeholders are not supported in UI title section at the moment.
