### ISSUE TITLE
Issue with privatemessages when beeing muted as admin

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8099]
### Description of Issue

Admins with the mute bypass can write in chat public what is fine..

but they also get effected by the block of private messages if this is set in config true for regular players.
.
i dont think this was wanted. if the admin is allowed to write in plublic while mutes why not to write private?

![Snag_85a30f](https://github.com/Zrips/CMI/assets/12080017/842640d2-4d94-4d07-a09d-f2480ab78b41)

Permission that handles it:
cmi.command.mute.bypass 

Well its description is truly "Bypass personal public chat mute"

But if it can also blocking of private messages as an option the question is why the bypass is not including private messages
bypass while muted?

So i dont requested it as a msising thing...its the reason for me to may report it as bug.. because i think its a not wanted behave..

### Version Information

![Snag_861a33](https://github.com/Zrips/CMI/assets/12080017/319ae1b6-28cf-4e8f-832b-41f4007fd706)

### Errors

```shell
none in console
```

### Relevant Config Sections

```yaml
Mute:
  # When set to true, player will not be allowed to send private messages while he is muted
  DenyPrivateMessages: true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will fix that.
