### ISSUE TITLE
CMI TMB COMMAND INVALID

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#810]
**Description of issue or feature request:**
/cmi tmb [title %subtitle% subtitle] - sends title message to all players online
Command doesn't exist

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

**Cmi Version (using`/cmi version`):**   8.0.8.1

**Server Type (Spigot/Paperspigot/etc):** spigot

**Server Version (using `/ver`):**  1.13.1

**Comment by Rukes** [comment]
Use `cmi titlemsg all`

**Comment by Baktus79** [comment]
Yes, the tmb command is changed to titlemsg
