### ISSUE TITLE
Incompatible enchantments using /enchant.

### ISSUE THREAD

**Issue by Rompepitas** [Zrips/CMI#8105]
### Description of Issue

Not long ago, I had created an Issue #8092 , but it appears that the initial problem wasn't fully grasped. As I had mentioned in that Issue, I use the `/enchant` command freely to create kits. The main issue is that you can enchant an item with "Protection," "Blast Protection," and "Fire Protection," but this should not be possible since you cannot do this in vanilla mode.

Here are the incompatible enchantments:

- Each enchantment conflicts with itself. (The player cannot obtain a tool with two copies of the Efficiency enchantment).
- All damage enchantments (Sharpness, Smite, and Bane of Arthropods) conflict with each other.
- All protection enchantments (Protection, Blast Protection, Fire Protection, Projectile Protection) conflict with each other.
- Silk Touch and Fortune conflict with each other.
- Depth Strider and Frost Walker conflict with each other.
- Mending and Infinity conflict with each other.
- Loyalty and Riptide conflict with each other.
- Channeling and Riptide conflict with each other.
- Multishot and Piercing conflict with each other.

So users with the `cmi.command.enchant` permission have this limitation.

I hope that the purpose of this report can be understood this time.

### Version Information

```shell
CMI: 9.6.2.6 BungeeCord SqLite
CMILib: 1.4.1.0 -> 1.4.1.1
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Ok, will make some adjustment and prevent conflicting enchants being applied with this command.
