### ISSUE TITLE
Issues at server startup when loading worlds

### ISSUE THREAD

**Issue by Rompepitas** [Zrips/CMI#8106]
### Description of Issue

Hello Zrips,

I have updated the CMI plugin to the latest version and started experiencing many broken plugins. I tried removing CMI from the plugins folder and noticed that everything worked correctly. Therefore, the issue is caused by CMI.

I also noticed that the loading of worlds using the WorldGuard plugin with CMI now occurs differently. Specifically, worlds named "world," "world_nether," and "world_the_end" load at the beginning, while worlds with different names like "warps" and others load at the end, causing plugins to break. This was entirely different from how it worked with the old CMI, where WorldGuard loaded all worlds simultaneously.

I hope you can resolve this issue as soon as possible.

Thank you.

### Version Information

```shell
CMI: 9.6.2.6 BungeeCord SqLite
CMILib: 1.4.1.0 -> 1.4.1.1
```

### Relevant Plugins

WorldGuard 7.0.9

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
There was no actual change relating to worldguard plugin, we dont really have dependency on it besides soft one which should try to load CMI after world guard was loaded in. 
What plugin you have for your custom worlds? Multiverse? And what exactly brakes in your case as we did had some change relating to multiverse plugin

**Comment by Rompepitas** [comment]
I have checked, and this is something that occurs with MultiverseCore, but it only happens if the CMI jar is inside. I should mention that this only happens starting from CMI version `9.6.2.6` and CMILib `1.4.1.1`.

I have made changes to my plugins regarding world loading waiting. However, it would still be good to get a direct solution from CMI.

**Comment by CloudeLecaw** [comment]
oh i was seeing this to late...
take a look here

https://github.com/Zrips/CMI/issues/8120

**Comment by Zrips** [comment]
@Rompepitas 
CMI should not brake, it might inform about missing worlds but it should still keep working as intended. If there will be actual issues with plugins work, let me know. Will do some changes relating to multiverse, but there are more of a fundamental issues with Paper type servers and we will have to live with those warning messages, or I could hide those, but in general you can just ignore as long as everything works.
