### ISSUE TITLE
PlayerAdvancementDoneEvent issue

### ISSUE THREAD

**Issue by Mox0001** [Zrips/CMI#8108]
**Description of issue or feature request:**

Typical any user gets an advancement this issue will be a repeat spam for console and log.
[18:39:16 ERROR]: Could not pass event PlayerAdvancementDoneEvent to CMI v9.6.2.6

I have latest version of paper(388) 1.18.2, cmi, cmilib
i did use /paper version output: You are running the latest version

---

####################
####################
```


**Cmi Version (using`/cmi version`):**  CMI: 9.6.2.6

**Server Type (Spigot/Paperspigot/etc):** Server Paper(388).

**Server Version (using `/ver`):** Server Paper(388) 1.18.2-R0.1-Snapshot

**Comment by SwagRee** [comment]
Me Too.

**Comment by SwagRee** [comment]
Me too.I got a same issue.

**Comment by Zrips** [comment]
Will resolve this issue with next update, once and for all.
