### ISSUE TITLE
Feature Request - /condense hand or /condense (name) for things like melon slices

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#811]
**Description of issue or feature request:**

Would it be possible to make it so /condense has a /condense hand  or /condense (blocktype) variant that would condense blocks that currently don't condense, such as melon slices, similar to the way the command behaves in EssentialsX?

Thank you.

**Comment by Zrips** [comment]
You can do this already. You simply need recipes from one to another block. Make it with recipe creator and make that couple slices of melon converts to melon and vise versa. Works for any type of recipes if they have backwards conversion.
