### ISSUE TITLE
Custom furnace synthesis reset issue

### ISSUE THREAD

**Issue by Bckey** [Zrips/CMI#8110]
### Description of Issue

Game version 1.20.1
Server Core PurPur/Paper
trouble:
Custom furnace recipes are available at setup, but will no longer work on every server restart.
Reloading the CMI plug-in cannot solve this problem. You must take out or replace the items again to run normally.
CMI version (latest): 9.6.2.6

### Version Information

```shell
CMI 9.6.2.6
CMILIB 1.4.1.1
Purpur 1.20.1-R0.1-SNAPSHOT
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Bckey** [comment]
[19:46:26 INFO]: --------------------------------------------------
[19:46:26 INFO]: CMI 插件版本: 9.6.2.6 SqLite
[19:46:26 INFO]: CMILib: 1.4.1.1
[19:46:26 INFO]: 服务器版本: Purpur 1.20.1-R0.1-SNAPSHOT
[19:46:26 INFO]: CMI 经济: 启用 经济: 1.7.3-CMI CMI 聊天: 禁用
[19:46:26 INFO]: 模块 -> 58 已启用 1 已禁用: votifier
[19:46:26 INFO]: --------------------------------------------------

**Comment by Zrips** [comment]
What type of recipes do you have? Can you provide your recipes file if its being properly saved for testing?

**Comment by Bckey** [comment]
> 你有什么类型的食谱？您能否提供您的食谱文件（如果正确保存以进行测试）？

I think you can take a look at this
[recipesd.zip](https://github.com/Zrips/CMI/files/12548371/recipesd.zip)

**Comment by Zrips** [comment]
Do you have option to test this one without any other plugin to rule out possible compatibility issue? As of testing with latest 1.20.1 pupur version (2052) everything looks to be working, recipe is registered on server load and works as intended

**Comment by Bckey** [comment]
I tested it myself and it seems to be caused by a plug-in conflict. If I find some reason, I'll post it here. Since my plugin has a lot of content, this may take some time. thank you very much for your help.
