### ISSUE TITLE
Suggestion:  Please add a way to /sell all of one type of item from your inv.

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#812]
**Description of issue or feature request:**
Right now, when we do /cmi sell and /cmi sell hand, it sells only what you are actually holding, /cmi sell (name) still tries to sell what's in your hand.  I'm not sure if this is a bug or if I'm suggesting a new feature, but please make it so you can /sell hand and have ALL of that type of item in your inventory sell, and/or add /sell (name) to sell all of one type of item from your inventory.

Thank you very much.

**Comment by Zrips** [comment]
Next update /cmi sell same

**Comment by Momshroom** [comment]
Thank you very much, but there is a small issue with the code.  It seems to be adding how many you have in your hand to the TOTAL number you have and selling that.  So if I have 64 diamonds total, and 63 of them in my hand, it sells 64+63 = 127.  If 32 of them are in my hand, it sells 64+32 =96 and pays me for that.
http://prntscr.com/kzyd7x
http://prntscr.com/kzyddi
http://prntscr.com/kzydk6
http://prntscr.com/kzydr6

**Comment by Momshroom** [comment]
Hi, I'm just wondering if you've seen this or if I should make a fresh ticket for it?
