### ISSUE TITLE
itemlore color permission seems not to work as intendet

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8125]
### Description of Issue

When you try to relore n item with colors the mentioned permission for this (**_cmi.colors.itemlore.[color]_**) does not work.
means even if i set this pemission (lets say cmi.colors.itemlore.red) then i cant use the color in itemlore.

What it seems to require is the permssion **_cmi.colors.itemname.[color]_**  (like: cmi.colors.itemname.red) to allow the editing of the lore in the color.

So i think this is a bug somewhere or made mistake with the permission check inside the code?

normaly - **_cmi.colors.itemname.[color]_** was mentioned to be used for using colors in the itemname command
and **_cmi.colors.itemlore.[color]_** for the useage of colors in the itemlore command.

How it should be:
If player has the **_cmi.command.itemname_** permission and the defined _cmi.colors.itemname.[color]_ permission
he shouldbe allow to use colors when using the itemname command

If player has the **_cmi.command.itemlore_** permission and the defined _cmi.colors.itemlore.[color]_ permission
he shouldbe allow to use colors when using the itemlore command

### Version Information
![image](https://github.com/Zrips/CMI/assets/12080017/a20f3cdb-e1ce-4cb2-b930-06237a00ca47)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will make a fix with next update
