### ISSUE TITLE
Social spy non esiste

### ISSUE THREAD

**Issue by pinuxio** [Zrips/CMI#8137]
I set up a server but I can no longer find the commands even though I am the founder:
spy, social spy

I use cmi 9.1.3.0

**Comment by CloudeLecaw** [comment]
make your own customalias for that or use /cmi options

**Comment by CloudeLecaw** [comment]
pls Update to cmi 9.6.4.0 for further Support.
Version 9.1.3.0 is from March 2022 so 1 1/2 years behind the current state of cmi.

**Comment by pinuxio** [comment]
Isn't there a command that shows me all the players instead of setting them one at a time?

**Comment by CloudeLecaw** [comment]
what you mean?
if we still take about cmi options. you got defaults you can define in config that count for everyone until you minimum changes an option once.

**Comment by pinuxio** [comment]
I would like to set it so that by enabling spy chat it reads all the players

**Comment by CloudeLecaw** [comment]
> I would like to set it so that by enabling spy chat it reads all the players

it does this by default ?  enable social by and commands soy and you got them all if they have no soy bypass permission

**Comment by Zrips** [comment]
@pinuxio 
Make sure that you have social spy enabled in options, you can do this by either opening GUI with /cmi options or by simply using /cmi options chatspy enable, on top of this players with cmi.command.socialspy.hide will be excluded from social spy
