### ISSUE TITLE
Lag related to rankup checks

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#814]
**Description of issue or feature request:**
Our server is lagging and the timings report is showing major issues with CMI: http://prntscr.com/ks9dy1 https://timings.spigotmc.org/?url=toxejejuyo
doing /cmi reload seems to temporarily stop the lag.
If I change the config to not check for rankups (from the default 60 seconds to 0) the lag is vastly improved.
http://prntscr.com/ks9fq1
https://timings.spigotmc.org/?url=movavirigi

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Ranks:
  AutoRankUp:
    # Defines how often in seconds plugin will check for posible player rankups
    # Set it to 0 or less to disable auto rankup checks
    Delay: 0
    # Defines how often in seconds each separate player will be checked for rankup
    # This is different than general check just to avoid couple players ranking up at same time
    # This also defines how often player will be notified about posible rankup and it will proportionaly increase with each time player get notification to avoid annoying spam in chat
    # Keep it longer or same as general delay time
    PlayerDelay: 120
    # Enable or disable progression bar in rank info window
    progressBar: true

**Cmi Version (using`/cmi version`):** 
http://prntscr.com/ks9g6t

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
http://prntscr.com/ks9gaw

**Comment by Zrips** [comment]
Which requirements are you having set for rankup system?

**Comment by LogGits** [comment]
I am assuming this was resolved due to the lack of reply. If you are still experiencing this please open a new issue.
