### ISSUE TITLE
When displaying items in chat with [item] it doesn't display custom enchants

### ISSUE THREAD

**Issue by applepi333** [Zrips/CMI#8140]
### Description of Issue

![image](https://github.com/Zrips/CMI/assets/145812945/b35f5dab-39fd-4b12-aa8f-d2da6fd46f3b)
![image](https://github.com/Zrips/CMI/assets/145812945/339f6c85-fcdb-4245-86fc-d768bcec79dd)

When displaying items in chat with [item] it doesn't display custom enchants from the EcoEnchants plugin while it still normally displays vanilla enchants.

I'm not sure if this helps but EcoEnchants does register it's enchants for cross plugin compatibility.

### Version Information

```shell
CMI: 9.6.4.0 SqLite
CMILib: 1.4.2.0 
Server: Paper(196) 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 56 enabled 3 disabled: chatBubble, tablist, votifier
```

### Relevant Plugins

EcoEnchants 10.36.0

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
As of testing it looks to be weird mix of client and server side thing. While enchant exists on server side, it doesn't on client side, so it gets completely skipped when its being shown in chat. Similar thing happens with its actual lore, it doesn't really exist and EcoEnchants injects this information with packets, so while client sees this information, server doesn't. It's a weird mix, server has name of enchant, client doesn't recognize it, while client has lore information which is not present on server side. Can't really do much about this without having some heavy dependency/hook into EcoEnchants. 
Not a bug.
