### ISSUE TITLE
Can not right click to edit hanging signs

### ISSUE THREAD

**Issue by thenullmatrix** [Zrips/CMI#8142]
### Description of Issue

When running CMI I get You can't edit this when I right click on the hanging sign to edit. When I remove CMI I am able to right click and edit the sign.  I am running Spigot latest 1.20.1 ver switching to paper is not an option for me. If this is still an issue with Spigot is there a way to disable sign editing on the CMI side so that I could use the native Mojang editor? The main issue is that users can not add text to the other side of the sign.

### Version Information

```shell
CMI 9.6.4.0 CMILib 1.4.2.0
```

### Errors

```shell
You can't edit this
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
You would simply need to give cmi.signs.shiftedit permission node to the players and make sure you have sign edit option set to be enabled by default in config file under Player.Options.Defaults.shiftSignEdit section and you should be good to go. 
At the moment we are blocking sign edit by default to mimic previous behavior and prevent players from editing signs without permission node, so you will need to give it for them to be able to use it without limitations.
