### ISSUE TITLE
Error on reload/start (java.lang.IllegalArgumentException: Cannot set to an empty path)

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#8150]
### Description of Issue

Hello,
When I start my server or reload the CMI plugin i have an error : 
`java.lang.IllegalArgumentException: Cannot set to an empty path`

### Version Information

```shell
INFO | CMI: 9.6.4.1 BungeeCord  SqLite
CMILib: 1.4.2.0 
Server: Purpur 1.20.1-R0.1-SNAPSHOT
CMI economy: Activé(e) Vault: 1.7.3-CMI CMI Chat: Activé(e) 
Modules -> 23 enabled 36 disabled: spawnerProximity, cuffed, mirror, tablist, armorEffects, moneyCheque, skin, noTarget, rideAnimation, bossBarCompass, coloredArmor, chatBubble, playerCombat, votifier, shulkerBackpack, cooldown, headDrop, spawnerCharge, vanish, namePlates, timedCommands, hpBossBar, armorstand, jail, spawners, dynamicSigns, durabilityLoss, kits, flightCharge, disabledEnchants, worldLimitsElytra, worldLimits, ranks, sitAnimation, warmup, totemBehavior
```

### Errors
Errors is here : https://mclo.gs/hsDs9yG#L270

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Looks to be an issue with armorStands.yml file, could you send it to me for testing? In general this error will only effect armor stand templates

**Comment by NoltoxGit** [comment]
> Looks to be an issue with armorStands.yml file, could you send it to me for testing? In general this error will only effect armor stand templates

Hello,
The problem is in the `armorStands.yml` file. By deactivating it, I no longer get errors in my console.

Here's the file in question: https://pastebin.com/f5FmDp42

**Comment by Zrips** [comment]
Last entry in you save file was broken for some reason. Duno if that happen due to invalid save process or was it result of manual modifications. But here the fixed version of it https://pastebin.com/7BugsT1B
