### ISSUE TITLE
Holo Interaction Instability on 9.6.5.1

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#8157]
### Description of Issue

Holograms seem to lose their interact ability if the player moves out then back in render distance. I'm having a hard time pinning it down, so not sure if even that's what's happening. But the particles disappear and it seems like they're just not active. These are static holos but I tried also adding a 5 second update interval to each (and tried messing with other settings) and nothing affected it. They work again briefly if I change any properties of the holo, but break again soon after.

### Version Information

```shell
CMI plugin version: 9.6.5.1 BungeeCord CMIB  SqLite
CMILib: 1.4.2.0 
Server: Paper(196) 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 57 enabled 2 disabled: ranks, skin
```

### Errors

```shell
None
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be posting new version today with few fixes relating to holograms, if issue persists after that, let me know.

**Comment by mercurialmusic** [comment]
Yes, all good, thank you!
