### ISSUE TITLE
Portal errors

### ISSUE THREAD

**Issue by JuergenUniVie** [Zrips/CMI#8159]
### Description of Issue

I have 7 portals next to each other. 
I set the same particle effect for everyone, but it only works for one portal. 
Once activated on one portal, the effect will end on another portal.

### Version Information

```shell
CMI 9.6.5.1
CMILib 1.4.2.0
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Could you provide save file for those holograms for testing?

**Comment by JuergenUniVie** [comment]
> Could you provide save file for those holograms for testing?

attached, it's very simple. Issue also with the latest build (9.6.5.2)

**Comment by Zrips** [comment]
You do have your activation range set to only 2 blocks, so portal will not be visible until you get closer to one

**Comment by JuergenUniVie** [comment]
> You do have your activation range set to only 2 blocks, so portal will not be visible until you get closer to one

no, tried all ranges....

**Comment by Zrips** [comment]
Which server version and type are you running? Output from /cmi version would be best

**Comment by Zrips** [comment]
At the moment as of testing, setting range to 64 I can get 4 portals showing their particles at once, so something else is going on with your setup

**Comment by Zrips** [comment]
And just FYI you have your portals like 40'ish block away from closest one, so you would need range of like 40-50 blocks to have more of those turned on. You can go all in and set it to 64 block range if you want for those portals to be visible from further away and show multiple at once

**Comment by Zrips** [comment]
All will not work as distance between furthest is around 120 blocks. Will increase max particle range to 128 with next update which should help out with your situation here, but everything else looks to be working correctly. If you can get particles from more than one portal at once then its all working, you might just be lacking extra range as you have your portals quite far apart from each other and range of 64 blocks isn't enough to get all those showing up

**Comment by Zrips** [comment]
Could you by any chance record video to be more clear what's going on?

**Comment by JuergenUniVie** [comment]
> Could you by any chance record video to be more clear what's going on?

yes.

![Screenshot 2023-10-10 155409](https://github.com/Zrips/CMI/assets/61051829/d803feed-7435-4afa-9a4b-8d1a21cb4dec)

**Comment by JuergenUniVie** [comment]
[> > Could you by any chance record video to be more clear what's going on?
> 
> yes.
> 
> ![Screenshot 2023-10-10 155409](https://user-images.githubusercontent.com/61051829/273934064-d803feed-7435-4afa-9a4b-8d1a21cb4dec.png)


https://www.youtube.com/watch?v=9-D5byz2JCc

**Comment by Zrips** [comment]
Ok, looks to be small bug relating to particlesByPermission option which was producing inconsistent results when you are trying to limit particle visibility by permission access. Will fix that with next update and if issue persists, let me know, just create new ticket as i'm closing this one for time being.
