### ISSUE TITLE
Placeholders returning "switched" values

### ISSUE THREAD

**Issue by kristouffe** [Zrips/CMI#8162]
### Description of Issue

Hi,

i'm facing some issues with following placeholders

%cmi_iteminhand_worth%
%cmi_iteminhand_worth_one%

When the worth is not set in the worth file: 
**%cmi_iteminhand_worth%** returns 0
**%cmi_iteminhand_worth_one%** returns the localFile value "worthless"

both should return same value when the worth is not set into worth file.

I also checked the unformatted version of the placeholders and you clearly can see that the values have been switched:

**%cmi_iteminhand_worthc%** returns the localFile value "worthless"
**%cmi_iteminhand_worthc_one%** returns 0

Shoudn't the formatted version return the same value ("**wortheless**") and the unformatted version return the same value ("**0**") aswell?

thanks

### Version Information

```shell
[16:02:36 INFO]: CMI: 9.6.5.2 SqLite
[16:02:36 INFO]: CMILib: 1.4.2.0
[16:02:36 INFO]: Server: Paper(217) 1.20.2-R0.1-SNAPSHOT
[16:02:36 INFO]: CMI economy: Activé Vault: 1.7.3-CMI CMI Chat: Activé
[16:02:36 INFO]: Modules -> 57 enabled 2 disabled: coloredArmor, votifier
```

### Relevant Config Sections

```yaml
in Local File 
  worth:
    info:
      worthless: '&eWorthless'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Good point, will make it to return locale line when using formattable placeholder and 0 when using clean ones.
