### ISSUE TITLE
Stevehead customhead drop and Steve GUI heads in paper 1.20.2

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8163]
### Description of Issue

The CustomHeads that can be droped in CMI are droping just Steveheads

I tried it with Magmacuves, Cows and Horses
all gave me stave head (names correctly from CMI.
![Snag_8d417f](https://github.com/Zrips/CMI/assets/12080017/76b69a98-7ae3-4b3d-9b79-b8c9a60a0bee)
![Snag_8f0d66](https://github.com/Zrips/CMI/assets/12080017/6f0a37c1-1003-4d11-b5b4-bd545f8009d0)

Also i noticed the Steaveheads in the Home GUI
![Snag_50486d](https://github.com/Zrips/CMI/assets/12080017/3112dedd-d50e-4843-99bf-6afa454c8866)

Inccheck:
![Snag_5468c3](https://github.com/Zrips/CMI/assets/12080017/fb4c4134-6868-430a-920f-e86a1650b895)

Well i aspect all playerheads in CMI Menues are effected....

Other plugisn like Deluxemenues and HEADDatabase heads are shown correct...
![Snag_534d41](https://github.com/Zrips/CMI/assets/12080017/722b49f0-7d92-43d8-b91a-dca90a9b8ca3)

### Version Information
![Snag_8d5e3f](https://github.com/Zrips/CMI/assets/12080017/32241675-77b8-4622-8004-7cf13afd3b67).2

### Relevant Config Sections
pastebin of my CustomHeads.yml
https://pastebin.com/Y4T9QnDK

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should get a fix with next CMILib update
