### ISSUE TITLE
Database useUnicode and characterEncoding

### ISSUE THREAD

**Issue by XiangChen888** [Zrips/CMI#817]
**Description of issue or feature request:**
If player's name includes the chinese characters, in database it will show '???' instead of the right name. Could you please add useUnicode=true and characterEncoding=utf-8?

**Cmi Version (using`/cmi version`):** 
 8.0.8.1
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.12.2

**Comment by LogGits** [comment]
This was added in the latest update.
