### ISSUE TITLE
cmi spawnmob hp-[amount] not working 

### ISSUE THREAD

**Issue by TheBadshah** [Zrips/CMI#8171]
### Description of Issue

- ### hp-[amount] – entities hp between 1 and 2048, if not defined, then the default entities hp will be used.

Don't seems to be working
![Screenshot 2023-10-14 153737](https://github.com/Zrips/CMI/assets/116473315/d3c678c5-c6e3-44f6-9a6b-b5d2ff3b48c7)

also tried with the example command in wiki

###  /cmi spawnmob skeleton_horse:`baby`:hp-50:n-{#brown}Death_Bringer:s-3
![Screenshot 2023-10-14 142035](https://github.com/Zrips/CMI/assets/116473315/34628807-f968-4b36-b6f5-487e5c9f1d9f)

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.6.0 BungeeCord CMIB  SqLite
CMILib: 1.4.2.1 
Server: Purpur 1.20.1-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Enabled 
Modules -> 46 enabled 13 disabled: tablist, versionCheck, moneyCheque, skin, elytraBoost, paintingEditor, dynamicSigns, elytraLaunch, bossBarCompass, flightCharge, playerCombat, namePlates, homeInteractions
--------------------------------------------------
```

### Errors

```shell
n/a
```

### Relevant Config Sections

```yaml
n/a
```

### Agreements

- [ ] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
