### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by linsaftw** [Zrips/CMI#8177]
### Description of Issue

High memory consumption. Shown in the heap dumps below.

![image](https://github.com/Zrips/CMI/assets/25271111/9b2df2ee-c616-46c4-8de6-8c742c4bf5a6)
![image](https://github.com/Zrips/CMI/assets/25271111/b04419bc-d7c6-4a34-899e-8ef4c6a40ef0)
![image](https://github.com/Zrips/CMI/assets/25271111/7bd0a3ad-9e58-46ba-8bb4-3fae904d537b)

Version information
![image](https://github.com/Zrips/CMI/assets/25271111/7f1d3cad-08db-4219-8f9a-7fc976ac8d9c)

### Version Information

```shell
Shown above
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
next update will introduce multiple optimizations relating to memory usage which should help out here.
