### ISSUE TITLE
OnDurabilityLoss - /cmi options

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [Zrips/CMI#8187]
Hello, I would like to ask if this option could be turned off in the settings - /cmi options. It's a great feature, but it annoys some people. 
  Thank you
  
  
 "OnDurabilityLoss:
    # Do you want to inform player when item durability gets lower than set threshold
    # Player should have cmi.informDurability
    Tools:
      Use: true
      Percentage: 15
    Armor:
      Use: true
      Percentage: 15"

**Comment by Zrips** [comment]
Will add with next update
