### ISSUE TITLE
CMI New Hologram display method makes hologram invisible

### ISSUE THREAD

**Issue by Yertled** [Zrips/CMI#8195]
### Description of Issue

After updating CMI, all our holograms using new display method disappeared and is now invisible.

https://github.com/Zrips/CMI/assets/12172847/3e705087-329b-4d34-830a-79d8e9af86ea

### Version Information

```shell
CMI: 9.6.7.1
CMILib: 1.4.2.2
Server: Purpur 1.20.2-R0.1-SNAPSHOT
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
From your example, while its hard to see, but it looks like you have fixed rotation enabled in which case this hologram could be facing away from you, so you either need to rotate it around or enable double sided option. If it actually disappears then let me know

**Comment by NyhmsQuest** [comment]
It's actually disapearing. All our holograms went invisible and where working just fine before.

**Comment by Zrips** [comment]
Which exact purpur version are you running?

**Comment by Zrips** [comment]
Just tested with latest purpur version, new hologram display method looks to be working correctly and shows it appropriately. Could you send me example of hologram from your holograms save file which isint showing up with new display method?

**Comment by NyhmsQuest** [comment]
> Just tested with latest purpur version, new hologram display method looks to be working correctly and shows it appropriately. Could you send me example of hologram from your holograms save file which isint showing up with new display method?

Replying from phone so it may not format correctly but here is an example hologram that stopped working.

    BColor: '{#Black}'
    BAlpha: 0
    ScaleW: 0.9
    SL: -1
    BL: -1
  Lines:
  - 'ICON: PAINTING'
  - 'ICON: PLAYER_HEAD (d0by)'
  - '&#daacfb&l&nA&#daacfb&l&nr&#daacfb&l&nt &#daacfb&l&nM&#daacfb&l&nu&#daacfb&l&ns&#daacfb&l&ne&#daacfb&l&nu&#daacfb&l&nm'
  - Showcase of Vanilly's Art Contest winners

**Comment by Zrips** [comment]
![image](https://github.com/Zrips/CMI/assets/10416201/8b5d3291-9347-41c4-ac04-995ee85bd8c1)
Looks to be working for me. By the way player head would be defined as `ICON:PLAYER_HEAD:d0by`
You might want to test this one without any other plugin, in case there is 3rd party interference with all of this

**Comment by NyhmsQuest** [comment]
Turns out it was an issue with Velocity needing to be updated.
