### ISSUE TITLE
Inv project configuration is invalid

### ISSUE THREAD

**Issue by FZDNSZYT** [Zrips/CMI#8198]
Under the inv project, I enabled the "SaveOnDeath: true" function. But it did not take effect. Do I need to do anything for this?
This is my configuration record:
[inv_config.txt](https://github.com/Zrips/CMI/files/13161062/inv_config.txt)

**Comment by Zrips** [comment]
Enabling it in config file and reloading plugin with /cmi reload should enable automatic inventory saving. You can check saved inventories with/cmi invlist and check for any with skull icon on the side which will indicate auto save

**Comment by FZDNSZYT** [comment]
Isn't his function actually to automatically restore the number of items configured in "SavedInventories: 5" in the player's backpack when the player dies and is reborn?

**Comment by FZDNSZYT** [comment]
> Enabling it in config file and reloading plugin with /cmi reload should enable automatic inventory saving. You can check saved inventories with/cmi invlist and check for any with skull icon on the side which will indicate auto save

What you mean is that this function is similar to the death chest, and the player needs to use /cmi invlist to select the items that need to be restored.

**Comment by Decent60** [comment]
> > Enabling it in config file and reloading plugin with /cmi reload should enable automatic inventory saving. You can check saved inventories with/cmi invlist and check for any with skull icon on the side which will indicate auto save
> 
> What you mean is that this function is similar to the death chest, and the player needs to use /cmi invlist to select the items that need to be restored.

It's kinda similar to death chest but they need permission to view and load it back. It can also be loaded unlimited amount of times (thus abusable). It can be done via the chatline (simple way: `/cmi invload last` and could be set as an alias with a cooldown or cost to reduce abuse; could also combine it with `/cmi invremove last` in an alias to also remove the last one after loading it). A GUI can show up (with the `invcheck` ) so a person with permission can see it and load it onto themselves or the person. 


See also: https://www.zrips.net/cmi/commands/

**Comment by Zrips** [comment]
@FZDNSZYT 
It's not restoring inventories, its saving entire inventory which can be restored later on if needed, via comand. That number defines how many inventories we should save.
