### ISSUE TITLE
[CMI 9.6.7.2] Riptide doesn't work underwater after fix.

### ISSUE THREAD

**Issue by Decent60** [Zrips/CMI#8199]
### Description of Issue

As of 9.6.7.2 update, if you try to use the Riptide ability on a Trident underwater, it will not work, even if the area that is allowed to rain, such as an ocean. 
This is directly due to the AntiCheat setting/config. Disabling this makes it work similar to the original.
Prior to the 9.6.7.0 fix, it worked similar to vanilla.
On vanilla, your trident works regardless with weather underwater. 
https://i.imgur.com/VHB5kFP.png

### Version Information

```shell
CMI: 9.6.7.2 SqLite
 CMILib: 1.4.2.2 
 Server: Paper(196) 1.20.1-R0.1-SNAPSHOT
 CMI economy: Disabled CMI Chat: Disabled 
 Modules -> 58 enabled 1 disabled: votifier
```

### Relevant Config Sections

```yaml
'# When enabled we will not allow usage of riptide while player has pweather set to rain while players world is in sunny state'
'  Riptide: true'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
