### ISSUE TITLE
how to use event commands

### ISSUE THREAD

**Issue by beeng9** [Zrips/CMI#820]
**Description of issue or feature request:**

I want to use CMIs event command

but there's no way to learn about event command

I can't find this on spigot over view, also on spigot CMI wiki.

who knows about it?

Exactly, I can't understand 

playerKick:
  Use: false
  List: []

This 'List' sector.

Sorry for my bad english skill, And thanks to your understand

**Comment by Zrips** [comment]
`joinServer:
  Use: true
  List:
  - delay! 1
  - cmi titlemsg [playerName] &8◆ &6&l&nPrison&r &8◆ %subtitle%&eWelcome back!
  - delay! 2
  - cmi titlemsg [playerName] &4Download our texturepack!! %subtitle%&6Check the chat
    for the link
  - msg! [playerName] &7&m----------------&d< &a&lMessage &d>&7&m------------------
  - msg! [playerName]
  - msg! [playerName] &4TexturePack download link >> Link
  - msg! [playerName]
  - msg! [playerName] &7&m--------------------------------------------`
Something like this
