### ISSUE TITLE
Holograms problem purpur 1.20.2

### ISSUE THREAD

**Issue by Rivers071** [Zrips/CMI#8212]
### Description of Issue

The old hologram works, but the new not, this begin to happen when I upgrade purpur 1.20.1 to 1.20.2
video detailed here: https://youtu.be/B83IRkFFgrE 

### Version Information

```shell
[00:12:21 INFO]: --------------------------------------------------
[00:12:21 INFO]: CMI: 9.6.7.3 SqLite
[00:12:21 INFO]: CMILib: 1.4.2.2 
[00:12:21 INFO]: Server: Purpur(2084) 1.20.2-R0.1-SNAPSHOT
[00:12:21 INFO]: CMI economy: Disabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[00:12:21 INFO]: Modules -> 58 enabled 1 disabled: votifier
[00:12:21 INFO]: --------------------------------------------------
```

### Errors

```shell
none
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
It might look silly question, but double check if hologram isn't facing away from you as that one would be invisible for you. You can try enabling double sided mode or disable fixed position one

**Comment by Rivers071** [comment]
> It might look silly question, but double check if hologram isn't facing away from you as that one would be invisible for you. You can try enabling double sided mode or disable fixed position one

I know, they worked in 1.20.1, but the vertical and fixed dont work, only the old

**Comment by Rivers071** [comment]
> It might look silly question, but double check if hologram isn't facing away from you as that one would be invisible for you. You can try enabling double sided mode or disable fixed position one

dkalaxdk in discord said theres a problem with viaversion

**Comment by Zrips** [comment]
Looks like, at the moment we are using generic Bukkit API for those new type of holograms, so looks like ViaVersion isint processing those properly at the moment.

**Comment by JustJP2K** [comment]
with the newest dev builds from viaversion/viabackwards the issue seems to have been solved

**Comment by Zrips** [comment]
@Rivers071 
As @JustJP2K pointed out here, you might try updating ViaVersion to the latest version and if issue will still be there then we can look at it again, but it looks to be resolved now. Closing ticket.
