### ISSUE TITLE
Unable to find lore text for invsee command

### ISSUE THREAD

**Issue by mario414x** [Zrips/CMI#8214]
### Description of Issue

![image](https://github.com/Zrips/CMI/assets/103279766/e4bdd7de-d9fc-4bd5-b364-aaf99e431be0)
For /invsee command, we have this potion thing that shows player current potion effect. However, if the player has no effects, it would return this message.
![image](https://github.com/Zrips/CMI/assets/103279766/728eb5b1-2647-405a-a86f-2ac58ff94711)

The "No Effects" from first screenshot will appear even if the player has active effects. 
![image](https://github.com/Zrips/CMI/assets/103279766/f4e65d4a-ac0a-4551-8dd0-40a643e673af)

### Version Information

```shell
latest
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update.
