### ISSUE TITLE
"ShowDamageNumbers" cannot display damage from mmoitem, such as skills, elemental, and critical damage.

### ISSUE THREAD

**Issue by QSPPPPW** [Zrips/CMI#8218]
### Description of Issue

The "ShowDamageNumbers" holographic numbers do not calculate any damage from mmoitem, such as skills, elemental, and critical damage. The "HpBarEnabled" damage display is working correctly, so this seems to be a bug that needs to be fixed.
![)RVP{1LPAT{W4GG%KD` 5R](https://github.com/Zrips/CMI/assets/104671234/3e2013dc-1df2-49d7-929e-091b1215606e)

### Version Information

```shell
[21:19:40 INFO]: --------------------------------------------------
[21:19:40 INFO]: CMI: 9.6.7.4 SqLite
[21:19:40 INFO]: CMILib: 1.4.2.2
[21:19:40 INFO]: Server: Purpur(2062) 1.20.1-R0.1-SNAPSHOT
[21:19:40 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled
[21:19:40 INFO]: Modules -> 55 enabled 4 disabled: tablist, votifier, namePlates, homeInteractions
[21:19:40 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by QSPPPPW** [comment]
It appears there are some other calculation errors, such as bonus damage from the EcoEnchants plugin increasing the damage for all ShowDamageNumbers, even though it didn't actually deal that much damage.
![} UN 40L8BNP)U8XN_HDO6X](https://github.com/Zrips/CMI/assets/104671234/3129d898-616f-4cb8-96c4-239005201f41)

**Comment by Zrips** [comment]
Should be fixed with next update

**Comment by QSPPPPW** [comment]
Thank you so much

**Comment by QSPPPPW** [comment]
Could you please add a health regeneration prompt if possible?
