### ISSUE TITLE
"DisableFishing: true" is not worked in afk section.

### ISSUE THREAD

**Issue by Ecilpse** [Zrips/CMI#8219]
### Description of Issue

although i set "DisableFishing: true" in afk section, player has became afk mode while fishing without any moves.

### Version Information

```shell
CMI: 9.6.7.4
CMILib : 1.4.2.2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Small bug, should be fixed with next update
