### ISSUE TITLE
Run commands as hologram

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#823]
**Description of issue or feature request:**

Is there a way to run a command as a hologram - for example: have /baltop ran so it shows the top balances in a hologram. Or is this not in CMI?

**Comment by Tazkee** [comment]
**Try with the CMI placeholders:** 
54. %cmi_baltop_name_[1-10]%
55. %cmi_baltop_money_[1-10]%
------------------------------------------------------------------------------------------------
You can find all CMI placeholders in: https://www.spigotmc.org/wiki/cmi-placeholders/
------------------------------------------------------------------------------------------------
