### ISSUE TITLE
Hologram background color not saving on plugin reload or server restart

### ISSUE THREAD

**Issue by ReasonFoundDecoy** [Zrips/CMI#8237]
### Description of Issue

Issue is the title. Make a hologram and change the background color to anything but black. Reload the plugin and see how it reverts to black. 

### Version Information

```shell
CMI: 9.6.7.5 SqLite-> 9.6.7.6
CMILib: 1.4.2.3 
Server: Paper(196) 1.20.1-R0.1-SNAPSHOT+
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled 
Modules -> 54 enabled 5 disabled: tablist, ranks, votifier, shulkerBackpack, namePlates
```

### Errors

```shell
[none]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Can you give exact example of color name/code you used which did not worked out for you? As of testing with same server version, everything looks to be working as it should, color codes/names gets saved and loaded in properly

**Comment by ReasonFoundDecoy** [comment]
Sure, I've tried with background colors &d, &3, and &4. Those ones for sure aren't saving, I haven't tried the other colors. The text colors I've used on them are &f, &0, and &7. Just a basic hologram with some text and then change the background color, reload plugin - that's all I do and it reverts back to black.

**Comment by Zrips** [comment]
Ok, will be fixed with next update. For time being you can just use regex color codes or just named one from /cmi colorpicker command. There is small issue with vanilla color codes at the moment, but should work just fine with new ones.

**Comment by Zrips** [comment]
By the way, usage would be something like `#red` or `#cc2500`

**Comment by ReasonFoundDecoy** [comment]
ohhh, okay thank you!
