### ISSUE TITLE
Items dropped from suspicious blocks vanishing from inventory

### ISSUE THREAD

**Issue by HGG590** [Zrips/CMI#8238]
### Description of Issue

Suspicious blocks (sand or gravel) created with a specific item drop (not the generic MC suspicious block linked to a loot table), will drop the item, however this item will vanish from the player inventory after opening a chest.

A restart of the server fixes the issue until the next time an Admin uses the CMI invsee command on a player.  From this point forward, any item brushed from a suspicious block, for any player on the server, will vanish from the inventory after opening a chest.

Investigating the NBT data of the dropped item shows additional NBT has been added:
tag:{CMIGUIIcon: “LIProtection”}

Was able to replicate the issue on a new Purpur server (2086) with only CMI (9.6.7.6) and CMILIB (1.4.2.3) installed. (alias “/invsee enabled: true” as the only config change from default)

Login to server with 2 players
Give a suspicious block using:
/give @p suspicious_sand{BlockEntityTag:{item:{id:"minecraft:stick",Count:1b}}} 1
Brush block to receive item then open chest – works as expected.

Use invsee on a player then close menu.
Give another suspicious block.
Brush block to receive item then open chest – item vanishes from inventory.

### Version Information

```shell
[CHAT] --------------------------------------------------
[CHAT] CMI: 9.6.7.5 SqLite-> 9.6.7.6
[CHAT] CMILib: 1.4.2.3 
[CHAT] Server: Purpur(2086) 1.20.2-R0.1-SNAPSHOT+
[CHAT] CMI economy: Disabled CMI Chat: Disabled 
[CHAT] Modules -> 58 enabled 1 disabled: votifier
[CHAT] --------------------------------------------------
```

### Errors

```shell
None
```

### Relevant Config Sections

```yaml
None
```

### Relevant Plugins

CMI (9.6.7.6), CMILIB (1.4.2.3)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Confirmed. Really weird bug in general as it looks to be combination of CMI and minecraft server in general performing actions on air item stacks which should not be done. In any case, will be fixed with next CMILib update
