### ISSUE TITLE
Armorstand template broke in last version

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8247]
### Description of Issue

cmis armorstandeditor templates are broken since the last version.
the head and also the colored leather data of the templatestand is wrong.
it was working fine 1-2 versions ago where i tested it last time.

![image](https://github.com/Zrips/CMI/assets/12080017/ffe2bf73-0833-4548-87fe-d20e4a23ddc4)

### Version Information
![image](https://github.com/Zrips/CMI/assets/12080017/b290ed2e-6a13-4947-adb3-c40879405ba6)

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next CMI and CMILib update
