### ISSUE TITLE
can't remove glow certain player

### ISSUE THREAD

**Issue by Ecilpse** [Zrips/CMI#8249]
### Description of Issue

![image](https://github.com/Zrips/CMI/assets/25452835/15600f2a-5a92-400c-a0c0-f64e199646ac)

i can't glow off to certain player  (808080_x). can you add -p: tags for glow?

### Version Information

```shell
9.6.7.4
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
wrong useage of command.

```
cmi glow (playerName) [true/false/color/gui]
Set players glow mode

Example: /glow Zrips red

Permissions: cmi.command.glow.[color] – allows to set particular glow color```

**Comment by Ecilpse** [comment]
> it was just a wrong useage of command syntax ;)
> 
> ```
> cmi glow (playerName) [true/false/color/gui]
> Set players glow mode
> 
> Example: /glow Zrips red
> 
> Permissions: cmi.command.glow.[color] – allows to set particular glow color
> ```
> 
> so to turn it off its
> 
> `cmi glow (playerName) false`
> 
> so in your case use: `cmi glow 808080_x false`

![image](https://github.com/Zrips/CMI/assets/25452835/f44baf80-e15a-420b-a2ac-d4bc6d314b91)

 i already tried. still not work.

**Comment by CloudeLecaw** [comment]
might this happens because the player starts with a number?

i recomment update to latest cmi.
there was a fix for when player name start with a number

**Comment by Zrips** [comment]
Will be fixed with next update. It was an issue with player name starting with valid hex color code.
