### ISSUE TITLE
Can some text, like /ctext or so, be edited through console?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#8250]
Hi, is it possible to edit some text from the console? I'd like to automatize one text and change it dynamically every hour or so. It's good that it can be done in holograms via hologram editline command, but can I change it somehow in some text block command? Like in the /ctext or /aliaseditor? Or is there some other way to achieve this?

Example:
I want command, for example /worldConditions, that will contain:
Mobs are spawning.
PvP is enabled.

And sometimes (I have done the chance system in schedule already), it will change:
Mobs are not spawning.
PvP is disabled.

This can be done via holograms, but can I achieve similar results in /ctext or /aliaseditor somehow? Or in something else?  Ideally with some editline subcommand? Thanks for response!

**Comment by CloudeLecaw** [comment]
at least no thats not possible.
you need to edit a ctext content manually and can use cmi reload after from console if that helps you...

**Comment by Zrips** [comment]
@bobhenl 
At the moment its limited to ingame editor as its heavily dependent on chat interactions by you clicking on appropriate "buttons".
