### ISSUE TITLE
Bug with HP from Mobs

### ISSUE THREAD

**Issue by PabloKateee** [Zrips/CMI#8251]
### Description of Issue

 /cmi spawnmob skeleton_horse:baby:hp-50n-{#brown}Death_Bringer:s-3 dont work he spawn with 15 HP
 a recent update stated that it had been fixed, but it still does not work .

### Version Information

```shell
CMI Plugin Version: 9.6.8.0
CMI Lib: 1.4.3.0
```

### Errors

```shell
dont have errors
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Missing : after hp definition
Should look like this `/cmi spawnmob skeleton_horse:baby:hp-50:n-{#brown}Death_Bringer:s-3`

**Comment by PabloKateee** [comment]
dont work, the Death Bringer has 15HP

**Comment by Zrips** [comment]
Double check console if you performed correct command with correct format. As of testing it looks to be working correctly, spawn in entity wit 50hp

**Comment by PabloKateee** [comment]
tested , dont work :(

**Comment by PabloKateee** [comment]
now its works :D 

can you maybe tell me what the new command is to spawn a mob at a position on a certain world ? my old command looked like this: - asConsole! cmi spawnmob warden:adult:rainbow:n-{#e62900}🔥ᴡᴀʀᴅᴇɴ🔥 q:1 hp:2048

but with the new update, the old command no longer works as it should :D
