### ISSUE TITLE
cmi ko lang file upload plz

### ISSUE THREAD

**Issue by mangchi57** [Zrips/CMI#8253]
Can I upload a CMI plugin lang Korean translation file? I have a translated file.

**Comment by mangchi57** [comment]
[Locale_KO.zip](https://github.com/Zrips/CMI/files/13334829/Locale_KO.zip)

**Comment by GcGoat** [comment]
Added to default download option which should be available with next CMI update

**Comment by Zrips** [comment]
Should be available with next CMI update

**Comment by mangchi57** [comment]
Do I need to rework and upload for the next update?

**Comment by Zrips** [comment]
It got uploaded to CMI github page from where we will download version for those who wants it when they set their locale to KO
