### ISSUE TITLE
Limiting Permission of Tpa is broken

### ISSUE THREAD

**Issue by JustJP2K** [Zrips/CMI#8254]
### Description of Issue

permission cmi.command.tpa.max.[blocks] does not work to override default setting.

### Version Information

```shell
CMI 9.6.8.0
CMLib 1.4.3.0
Paper(249) 1.20.2-R0.1-SNAPSHOT+
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
