### ISSUE TITLE
extra character in actionbarmsg

### ISSUE THREAD

**Issue by NigthDay** [Zrips/CMI#8255]
### Description of Issue

Hello, I want to inform you that there is a time to show an actionbarmsg and a . unwanted after each message, right now in my case it is important that it does not appear since I am making a placeholder show something specific and it does not show anything when x thing appears (I don't know if I understand myself), then when the placeholder appears empty shows me the point of the CMI and it is something that does not please the eye

### Version Information

```shell
1.7.3-CMI
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
might add the screenshot you sendet us on discord to make easier to understand what dot you mean ;)

i added it from your discord report

![image](https://github.com/Zrips/CMI/assets/12080017/1666561a-4867-46d6-b09a-b22304414e93)

**Comment by Zrips** [comment]
It would help out to know how this gets triggered and what exact message is being used for it.

**Comment by NigthDay** [comment]
> It would help out to know how this gets triggered and what exact message is being used for it.


/cmi actionbarmsg

**Comment by Zrips** [comment]
@NigthDay 
Give me output of /cmi version
And if anything, be sure to be up to date with CMILib and CMI

**Comment by NigthDay** [comment]
> @NigthDay Give me output of /cmi version And if anything, be sure to be up to date with CMILib and CMI

I just updated

![image](https://github.com/Zrips/CMI/assets/100812346/284e3947-8beb-4784-8ec1-df41d685de11)

**Comment by NigthDay** [comment]
> ¿Es este un problema con algún mensaje de texto que envíes usando el comando actualbarmsg o solo con ese en particular? Por cierto, puede usar la versión /cmi, que proporcionará información más relevante para CMI. Todavía necesito la versión y el tipo del servidor, aunque todo lo que se proporciona en la versión /cmi, por lo que si pudiera proporcionar una imagen de eso ayudaría aquí a reducir las posibles causas.

It only happens with that one (CMI actionbarmsg)

![image](https://github.com/Zrips/CMI/assets/100812346/102890ad-5e36-4af7-be84-5a98d460d0a1)

server purpur, version 1.20.2

**Comment by Zrips** [comment]
Was asking more of if it happens with this particular action bar message or with all action bar messages. As this could simply be an issue with translated placeholder at the end and not with command itself

**Comment by NigthDay** [comment]
> Was asking more of if it happens with this particular action bar message or with all action bar messages. As this could simply be an issue with translated placeholder at the end and not with command itself

with all bar messages

**Comment by Zrips** [comment]
By any chance your message format in your locale file is set to have dot at the end? 
```
  actionbarmsg:
    help:
      info: '&eSends action bar message to player'
      args: '[playerName/all] (-s:[seconds]) [message]'
    info:
      message: '&f[message]'
```
last entry, double check if yours doesn't have dot

**Comment by NigthDay** [comment]
![image](https://github.com/Zrips/CMI/assets/100812346/0dfd38f7-f2cb-429f-89e4-db718f31db4a)

**Comment by Zrips** [comment]
Why its in red? It should be plain why as defined and you did not provided any colors for it
![image](https://github.com/Zrips/CMI/assets/10416201/8614a555-fb6f-4a1f-b460-2631cf50d6d5)
By any chance you have another plugin dealing with action bar messages? Or modifying chat messages in general?

**Comment by Zrips** [comment]
Ok, its issue with locale file. Go into your locale Locale_ES.yml and change line 303 to `      message: '&f[messsage]'` and it should be good to go.

**Comment by CloudeLecaw** [comment]
![Screenshot_2023-11-23-19-24-45-012_com rhmsoft edit pro-edit](https://github.com/Zrips/CMI/assets/12080017/027e2db4-555e-401b-b4a7-c500e1098909)
