### ISSUE TITLE
Shulkers with more slots don't work

### ISSUE THREAD

**Issue by Leahcimkrob** [Zrips/CMI#8257]
I use Advanced Chest. Every time I create a 54 slot shulkerbox and open it with the sneak button and right mouse button, it is a normal shulkerbox and all the items are gone. So it must have something to do with miot CMI, otherwise I don't have any plugins installed that modify Shulker. Without CMi it works without any problems.
There are no errors in the log or in the console

**Comment by CloudeLecaw** [comment]
If your using a thrid plugin for your schuler backpacks it means you need to disable cmis backback feature

**Comment by CloudeLecaw** [comment]
shulker Boxes have NO extanted slots. if yours got then its not made by CMI and in this case you nees to think of if you wanne use an other plugin with extanted shulker Boxes or the cmi shulker.

**Comment by Leahcimkrob** [comment]
It's about AdvancedChest, not Chest. Of course you can prevent yourself from installing other plugins or APIs, but does that make sense? It's just a matter of having 54 slots in the Shulker backpack instead of 27, without using an additional backpack plugin.
I think she's slowly getting too big to think clearly and everything is rejected straight away, but the main thing is that you've paid for CMI.
