### ISSUE TITLE
Dback Cooldown doesnt work

### ISSUE THREAD

**Issue by JustJP2K** [Zrips/CMI#8259]
### Description of Issue

Dback cooldown doesnt get triggered on death. 

Other cooldown commands such as cmi back still seem to work.

### Version Information

```shell
CMI: 9.6.8.1
CMILib: 1.4.3.1
Paper(291) 1.20.2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Can you elaborate more on this one. How is cooldown setup? Dback is just a command you can perform to return to your death location, it will not trigger its cooldown before you use it. Tho it could be interesting new feature idea.

**Comment by JustJP2K** [comment]
that would be a nice feature yes :)

my original issue has been resolved
