### ISSUE TITLE
Causing the server to crash

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#826]
![image](https://user-images.githubusercontent.com/5382252/45591753-9409d600-b98d-11e8-80c9-0196a5ad5312.png)

**Cmi Version (using`/cmi version`): 8.0.9.0

**Server Type (Spigot/Paperspigot/etc): paper

**Server Version (using `/ver`): 1.12.2

**Comment by Zrips** [comment]
How many user entries do you have in your database?

**Comment by Zrips** [comment]
And test out new version which has some changes which can possibly fix this issue.

**Comment by p82183645** [comment]
About 5000

**Comment by cdmvirt** [comment]
8.0.12 still has the baltop issue just comfirmed

**Comment by Zrips** [comment]
Should be ok with 8.0.13.0 found a cause.
