### ISSUE TITLE
Some player heads in the GUIs are bugged

### ISSUE THREAD

**Issue by JustJP2K** [Zrips/CMI#8260]
### Description of Issue

![image](https://github.com/Zrips/CMI/assets/74447960/cdc03f57-33dc-475f-8317-baa825d155d9)

Some type of player heads are bugged in the GUIs using CMILib.

### Version Information

```shell
CMI: 9.6.8.1
CMILib: 1.4.3.1
Paper(291) 1.20.2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
That doesn't look like its bugged, its the correct one for showing your base home location information

**Comment by JustJP2K** [comment]
I see. it looked a bit odd, sry for the issue report
