### ISSUE TITLE
/Anvil = You need Paper branch type server (PurpurMC)

### ISSUE THREAD

**Issue by Strahilchu** [Zrips/CMI#8262]
### Description of Issue

As of a recent CMI update (unsure which) 
the /Anvil command stopped working and now displays red "You need Paper branch type server"

### Version Information

```shell
CMI: 9.6.8.1 SqLite
CMILib: 1.4.3.1
Server: Purpur(2090) 1.20.2
```

### Errors

```shell
"You need Paper branch type server"
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Slarof** [comment]
Also faced with this problem

**Comment by TheBadshah** [comment]
seems like this issue came back 😔

**Comment by x1p** [comment]
Same here :-(
This is also the case for `/grindstone`, `/loom`, `/smithingtable` and `/stonecutter`

**Comment by TheBadshah** [comment]
cmi lib 1.4.3.0 don't have this issue.

**Comment by Zrips** [comment]
All commands will be available with next CMI update. Will try to include all Paper branch servers as all of them should properly process those commands.
