### ISSUE TITLE
Holograms Still Broken on CMI 9.6.8.2

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#8275]
### Description of Issue

Holograms still seem to be broken on 9.6.8.2, unfortunately no errors this time, neither in startup or otherwise. I do see particles around the ones that have particles enabled and setting individual holos back to the old method does seem to fix them. 

Strangely they seem to be fine in one random world but I can't discern why they would work in that one and not others. I think the only difference between the one that works and others is that render difference is crazy high (like 20). Things like `keepspawninmemory` from Multiverse are varied among the ones that don't work. 

One additional thing is that even the ones that do work don't really seem to appear until the player is basically right on top of them, so the render distance even for the ones that work is borked.

### Version Information

```shell
CMI plugin version: 9.6.8.2 BungeeCord CMIB  SqLite
CMILib: 1.4.3.3 
Server: Paper(297) 1.20.2-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 57 enabled 2 disabled: ranks, skin
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Posted new version. There was issue relating to how far from world center you are, where holograms near 0,0 coordinates would be visible while rest of them would not.
