### ISSUE TITLE
CMI commands in commabdblocks bug (@p or @a)

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [Zrips/CMI#828]
Hi, Im using

CMI plugin version: 8.0.9.0
Server version: Spigot 1.13.1-R0.1-SNAPSHOT
Vault version: 1.6.11(+)

And i Have problem with all CMI commands like msg, broadcast or actionbarmsg in commmandblocks. All variables like @p or @a are not working.

Ex.
When i type
"broadcast @p won!" it says "[Broadcast] @p Won" <- It doesn't change variable into nickname
but when i set minecraft say
"say @p won!" it broadcasts normally "[@] Player won!"

same with "cmi msg" and "minecraft:msg" and all cmi commands

**Comment by Zrips** [comment]
Command blocks and @p variables only work with vanilla commands. Could not find any way in extracting and replacing those variables with correct values after command event been sent for process.
