### ISSUE TITLE
Give Command [Hybrido]

### ISSUE THREAD

**Issue by SrT3ddy** [Zrips/CMI#8281]
### Description of Issue

After the 9.6.8.0 update, the give command for my hybrid server (mohist) is the command that is configured on my systems, as an example: "give SrT3ddy PIXELMON:MASTER_BALL 1" It stopped working.

the command "give SrT3ddy PIXELMON_MASTER_BALL 1" works but I would have to modify all the rewards on my server

![image](https://github.com/Zrips/CMI/assets/82233732/33ec0bdd-bd77-4fd2-b7a3-2094e066b484)

CMI-9.6.7.7 Version:
![image](https://github.com/Zrips/CMI/assets/82233732/28a568a6-d642-4215-8599-ec14a42ba3f6)

### Version Information

```shell
[15:03:44 INFO]: CMI: 9.6.8.4 SqLite-> 9.6.8.3
[15:03:44 INFO]: CMILib: 1.4.3.4
[15:03:44 INFO]: Server: Mohist 1.12.2-R0.1-SNAPSHOT
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next CMILib update
