### ISSUE TITLE
player can walkaround ElytraFlight WorldLimits

### ISSUE THREAD

**Issue by Ecilpse** [Zrips/CMI#8291]
### Description of Issue

you can see reproduce video down below links.
https://youtu.be/yh8Ku1vflVk

### Version Information

```shell
CMI 9.6.7.5
CMILIB 1.4.2.2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will make some changes relating to this, if issue persists after next update, let me know.

**Comment by Ecilpse** [comment]
> Will make some changes relating to this, if issue persists after next update, let me know.

i updated 9.6.10.2, but still same
youtube: https://youtu.be/Bnx5jHoxu6E
