### ISSUE TITLE
Something's going on with offline player locations

### ISSUE THREAD

**Issue by FireML** [Zrips/CMI#8292]
### Description of Issue

Every offline player i check with /pos is in our Spawn world, I am also teleported to that location with /tp.
I have another plugin to make sure it's not the server so i figured this would be a CMI issue.

CMI output: Spawn,4258:-43:6803
Another plugin's output: Kingdoms,4258,-43,6803

### Version Information

```shell
[19:25:18 INFO]: CMI: 9.6.8.4 BungeeCord CMIB  MySQL
[19:25:18 INFO]: CMILib: 1.4.3.4 
[19:25:18 INFO]: Server: Paper(307) 1.20.2-R0.1-SNAPSHOT-
[19:25:18 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[19:25:18 INFO]: Modules -> 49 enabled 10 disabled: spawnerProximity, deathMessages, customMessages, chatBubble, tablist, firstJoinMessages, votifier, spawners, spawnerCharge, namePlates
```

### Errors

```shell
There are no errors
```

### Relevant Config Sections

```yaml
There is no relevant config section
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Is Kingdoms world loaded in at the moment you are checking players position?

**Comment by Zrips** [comment]
Looks to be an issue with minecraft server itself weirdly handling player world when we are loading it in while player is offline. Will work out some fix for it with next update.

**Comment by Zrips** [comment]
Just to add to this. Issue only happens with Paper spigot builds, still need to figure out what's going on exactly to fix this one.
