### ISSUE TITLE
Worldlimits in Homes.yml not working?

### ISSUE THREAD

**Issue by kristouffe** [Zrips/CMI#8295]
### Description of Issue

After hours of testing, I concluded that there must be a bug.

I can set whatever I want in worldlimits for homes, players will still be able to set their homes in the limited world, even if I set it to 0.
Players I tested with have the right permission: `cmi.command.sethome.test` and they are still able to set homes in Nether (my test world).

I also tested with 2 different group names, one for the global home group and one for worldlimit home group, same result.

Perhaps I completely misconfiged, if so I'm really sorry.

Thanks

### Version Information

```shell
[19:27:27 INFO]: --------------------------------------------------
[19:27:27 INFO]: CMI: 9.6.8.5 SqLite
[19:27:27 INFO]: CMILib: 1.4.3.4
[19:27:27 INFO]: Server: Paper(307) 1.20.2-R0.1-SNAPSHOT+
[19:27:27 INFO]: CMI economy: Activé Vault: 1.7.3-CMI CMI Chat: Activé
[19:27:27 INFO]: Modules -> 57 enabled 2 disabled: coloredArmor, votifier
[19:27:27 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
in Homes.yml

https://pastebin.com/q1ciCnYN
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
i can agree this issue the 0 setting does not work.
The Homes.yml sais:

```       # Amount of homes you can have in this world home group. Setting to 0 would basically disable home creation in this world. Setting to lower than 0 will ignore this world group entirely
```


what currently works as a worksarround is simply negating the sethome permission for the choosen world where you wanne have 0. 

But for further updates it would be nice if this could be fixed :-)

**Comment by Zrips** [comment]
If player has access to cmi.command.sethome.bypasslimit then he would bypass any limitations, so make sure that he doesn't have access to this one. Tho I might change this to specifically require it to be specifically set and will mention about it in comment section for limitations. Other than this as of testing it looks to be working properly, home amount gets limited by set amount as long as you don't have access to that bypass permission node
