### ISSUE TITLE
CMI head is always "Player Head" instead of name

### ISSUE THREAD

**Issue by ChimpGamer** [Zrips/CMI#8297]
### Description of Issue

When using /cmi head <name> the name of the head is always "Player Head" instead of the actual player name like it used to be.

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.8.5 Unknown SqLite
CMILib: 1.4.3.4
Server: Paper(307) 1.20.2-R0.1-SNAPSHOT-
CMI economy: Ingeschakeld Vault: 1.7.3-b CMI Chat: Uitgeschakeld
Modules -> 38 enabled 21 disabled: spawnerProximity, hpBossBar, tablist, armorstand, moneyCheque, skin, spawners, cmiPlaytime, paintingEditor, eventCommands, playerChatTag, flightCharge, schedule, ranks, playerCombat, votifier, headDrop, spawnerCharge, silentChest, vanish, namePlates
--------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next CMILib update
