### ISSUE TITLE
Teleport with horse Question and Bug

### ISSUE THREAD

**Issue by Ew9304** [Zrips/CMI#83]
Hey,

I tested with other locations and I noticed that it only tries to teleport the horse with me when I am OP, when I am just a regular player it doesn't even try to bring the horse with me, therefore not glitching the player out obviously. Am I missing a permission that I should give to players?

Trying as a regular player: 
https://www.youtube.com/watch?v=fqUC-P3fudg

I tested with OP and it tries to teleport the horse with me but bugs out, for close distance teleportations it seems to work great, but once the distance is further it will cause me to glitch out until I hit shift, even if i /suicide I will respawn glitched out until I hit shift, not to mention losing the horse?

Trying with OP permissions: 

https://www.youtube.com/watch?v=7Bn2zvM4Cm4

**Comment by LogGits** [comment]
> I tested with other locations and I noticed that it only tries to teleport the horse with me when I am OP, when I am just a regular player it doesn't even try to bring the horse with me, therefore not glitching the player out obviously. Am I missing a permission that I should give to players?

`/cmi checkperm teleport` reveals: `cmi.teleport.with.[entitytype]` 🙂 

> I tested with OP and it tries to teleport the horse with me but bugs out, for close distance teleportations it seems to work great, but once the distance is further it will cause me to glitch out until I hit shift, even if i /suicide I will respawn glitched out until I hit shift, not to mention losing the horse?

I have also noticed this.

**Comment by LogGits** [comment]
Question, do you notice the same behaviour when you are not opped and/or when you are in survival?
