### ISSUE TITLE
Problem in CustomHeads.yml with Player Heads name

### ISSUE THREAD

**Issue by smscentras** [Zrips/CMI#8303]
Hello,
how to change name "Player's Head" to "Player"?

In my language there is no " 's Head "
Can't find in translations file, can't find in CustomHeads.yml, just LORE configs...

**Comment by Zrips** [comment]
That player head lore gets added automatically by game client itself, it's basically inside your games client locale records. We could maybe have optional thing to add custom items name when getting players head, similarly to what we have with custom mob heads. Will add this option with next CMILib update which handles player and mob heads.
