### ISSUE TITLE
[ BUG ] RespawnEvent console error

### ISSUE THREAD

**Issue by kedavlar** [Zrips/CMI#8308]
### Description of Issue

On lastest version when a player die and respawn, there a console error.

### Version Information

```shell
9.6.9.0
```

### Errors

```shell
https://pastebin.com/kRZrAkdr
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will release new version today with a fix. Just for future reference, please include /cmi version output for simpler debugging when making report.
