### ISSUE TITLE
[Issues] checkban

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#831]
> /cmi checkban (playerName) - Checks banned players

currently this command just inters the name of players that are online. (what is nonsense...  a player that is online cant be banned...insted of this it would be usefull to see (and be able to click for baninfo) the baned players that are stored in minecraftes mainfolder...

can this be changed/fixed?

![image](https://user-images.githubusercontent.com/12080017/45601404-995a3580-ba0c-11e8-8e69-6dd5695a235c.png)

**Comment by LogGits** [comment]
Seems to be working for me. 

`/cmi ban playername`
`/cmi checkban playername` returns the correct player info /reason/time/user that banned them.

I would say @Zrips It would be nice if `/cmi checkban ` with no username just outputs a banlist.

**Comment by Zrips** [comment]
Next update it will properly tabcomplete from banned players
