### ISSUE TITLE
Request local file modification upload Korea

### ISSUE THREAD

**Issue by mangchi57** [Zrips/CMI#8315]
Visit https://github.com/Zrips/CMI/discussions/new to post new idea or suggestion
Posting new suggestion in ticket section could result in their removal.

An error has been identified in the previously uploaded file, so I request to upload the corrected version.
[Locale_KO.zip](https://github.com/Zrips/CMI/files/13632908/Locale_KO.zip)

**Comment by Zrips** [comment]
Got updated
