### ISSUE TITLE
[Question] - Bug? - CMIiconomy money format

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#832]
On our Server we changed to the CMI iconomysystem.

in the config i found this line
  # Format used for displaying money
  MoneyFormat: '###,###.###'
i changed ti to  MoneyFormat: '###.###,###'

The Problem we have now is that on our Homepage we see the Money stores in the database a bit wrong

![image](https://user-images.githubusercontent.com/12080017/45628023-758e0280-ba93-11e8-8f4c-0e2ae1057d80.png)

if the Player has x.0 Money and no numbers are behind like
 1.245,50 or 2,564.00 then it is shown as  1.245,5 or 2,564 (see screenshot above)

Also in the TABlist it is shown wrong
![image](https://user-images.githubusercontent.com/12080017/45628521-8ee37e80-ba94-11e8-9c7f-5ccfccc273d3.png)

with the Plugin iConomy it was shown correct.
is there a way to Show this correct ?
 Maybe Setting up an other Format for the maney? where can i find templates or something for this moneyformat?

When i use /cmi balance it is correct.
![image](https://user-images.githubusercontent.com/12080017/45628596-ade21080-ba94-11e8-8f9c-18e52d387a8f.png)

**Edit:**..Also a bug with the 0 On my Testserver

We are using a mySQL Database.
i tested the same on a SQLite database and there we have the same Problem (only the Money Format with . and , is  is shown correct but is has the same Problem with the Numbers)

9.999,84 is shown fine as 9.999,84$
![image](https://user-images.githubusercontent.com/12080017/45629394-a0c62100-ba96-11e8-84db-0515956ef6c8.png)

but
9.999,8 is shown as 9.999,8$
![image](https://user-images.githubusercontent.com/12080017/45629454-c7845780-ba96-11e8-86a0-663e633cea98.png)

Any ideas may could help, or is this a bug?

**Comment by Zrips** [comment]
It stores in full numbers, without rounding them up. So you can have 10.22201250125421012 but ingame for simplicity sake you will see only 10.22
This is due to how Java treats double values in some situations and sometimes creates long numbers while it should not really do that. We could round them up, if that is really necessary to have, but then how many decimals we want to keep.
