### ISSUE TITLE
2 Decimals Money

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#833]
CMI version 8.0.9.0

In addition to issue #449  the 2 decimal bug seems to be back.

If the standard  MoneyFormat: '###,##0.00' is changed to  '###.##0,00' then the economy format shows only 1 decimal.

/bal shows 5,0 instead of the expected 5,00

**Comment by CloudeLecaw** [comment]
In addition to issue #449 #533 the 2 decimal bug seems to be back.
https://github.com/Zrips/CMI/issues/832

**Comment by x1p** [comment]
Are you sure about 533? I rather think 833 :)

**Comment by CloudeLecaw** [comment]
Hmm i took a look in cmia config there is sais:
Default
MoneyFormat: '###,###.###'

How u got this
 MoneyFormat: '###,###.0.00' ¿

Is there somewhere a list?

**Comment by x1p** [comment]
I hope Zrips will implement a western European format which, imho, would more look like the following examples:
0,50
1
1.000 (as in 1000)
1.000.000,45

**Comment by CloudeLecaw** [comment]
You can use '###.###,00'

**Comment by x1p** [comment]
I would love to, but this does not work. Format  '###.###,00' as you stated, will result in 0.5 (mark the dot).
If I am correct I think  '###.###,00' will lead to always 2 decimals. But I rather have only 2 decimals if needed. So 5 would be stated as 5 and not 5,00 which might be confusing for players.

**Comment by x1p** [comment]
Mine definitely does not.

**Comment by Zrips** [comment]
Next update CMI will have support for this.
