### ISSUE TITLE
CMI Bungee Custompayload spam causing kicks

### ISSUE THREAD

**Issue by iaxedu** [Zrips/CMI#834]
Using CMI 8.0.9.0 (This issue has been here since Bungeecord was added to CMI)

I have the issue that players who join an empty server get kicked due to packet spam. After some debugging with protocolLib, I concluded that this was caused by CMI CUSTOM_PAYLOAD packages.

Example: [https://pastebin.com/z343iBZ3](https://pastebin.com/z343iBZ3)

Above is an example where I join an empty server and instantly send over 2000 packages caused by CMI resulting in a kick. This is a huge issue for game servers or servers that just restarted.

####################

I've done some testing in a test environment. One account named **aXed** is in a server named **skyblocktest**. The packet debug results are from this server.

1. When the second account joins the second server named **factest** it sends one packet to **skyblocktest**. (2 People are online in the entire network)

2. When the third account joins **factest** it sends 3 packets to **skyblocktest**. (3 people online in the entire network)

3. When the fourth account joins **factest** it sends 5 packets to **skyblocktest**. (4 people online in the entire network)

The debug log from protocolLib: [https://pastebin.com/TiARsjw9](https://pastebin.com/TiARsjw9)

4. So now I tried a fifth account who joined **skyblock**. It only sends one packet to **skyblocktest**. (5 people online in the entire network) When I join **factest** with this account it sends 7 packets to **skyblocktest**.

####################

When no one is online on a server these packages stack until someone joins. Now imagine if a server has 100 people online it will send 102 packages to each server in my network. This is a huge problem that needs to be fixed.

And yes I've the bungeecord messages on false.

**Comment by LogGits** [comment]
Interesting find. Thanks for reporting this 🙂

**Comment by Zrips** [comment]
Will post new version with initial changes which should solve this issue and will follow tomorrow with next version with improved new methods.
