### ISSUE TITLE
CMI kits doesnt give moneybags of a moneypouch plugin correctly...

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8343]
### Description of Issue

We use this plugin on our server
https://www.spigotmc.org/resources/moneypouch-1-8-1-19-packages-with-money-or-xp.21905/

it allows to give a away money bags.
since today we notices the when we give away moneybags that where saved in a cmi kit away then the kit does not work anymore...
when given by the comand its fine.
i checked the ntb tags so see if they are equal...they are
normaly the plugin checks them by name and lore.

i made you a little video
https://streamable.com/l51zx4

### Version Information
![Snag_153ba75](https://github.com/Zrips/CMI/assets/12080017/c54c65f8-2657-4904-850e-57b5649df6f3)

### Errors
```shell
none in console
```

### Relevant Plugins
MoneyPouch

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Looks like there is slight change in NBT data, hard to say why exactly, but as this plugin of yours is quite outdated it just fails to properly recognize item by trying to directly compare one item to the other even when actual display name is the same, NBT is tiny bit different. "bold":false got added to your kit item, this is done by server itself. Would say to just try changing your pounch setup and play around with color codes and format to get a result with works correctly on newer servers. Adding bold to item name should generally solve your issue, tho might not look like you want it. 
Can't really fix this issue from my end as all that conversation is done by the server automatically.
