### ISSUE TITLE
Placeholder for homes player

### ISSUE THREAD

**Issue by M0odi** [Zrips/CMI#8345]
I trying setting my CMI plugin (land) and i did see troubles with this.
Locale_RU file, string 1665 - not exists placeholder for homes. My server use template: \n&7  [Message] \n. Because of not existing placeholder i dont setting this correct. 

I want: list: '\n&7  Точки дома: &b[homes] \n'
I have: list: '\n&7  Точки дома: &b'

**Comment by CloudeLecaw** [comment]
this homes one can be used in cmi customalias to display cmi homes.

**Comment by Zrips** [comment]
List of homes is just output of prefix which is defined in locale and then followed with list of homes separate by basic separator. At the moment we only have placeholder to show amount of homes player own, but not a list of those. I can add %cmi_user_homelist% placeholder for you to use in a place where you want to include players home list, tho keep in mind that this is basic list and will not perform any commands while clicking them, contrary to what you have when performing /homes command.
