### ISSUE TITLE
MySQL database Displayname Incorrect string value

### ISSUE THREAD

**Issue by mitalnet** [Zrips/CMI#8346]
### Description of Issue

plugin keeps throwing me an error in the console and after restarting the server does not keep /nick and it kicks the player out after connects (he has to connect twice for it to work).
When it disconnects the player it says this* in the waterfall

### Version Information

```shell
--------------------------------------------------
CMI plugin version: 9.6.9.3 Unknown  MySQL
CMILib: 1.4.4.2 
Server: Purpur(2092) 1.20.2-R0.1-SNAPSHOT-
CMI economy: Zapnuté Vault: 1.7.3-CMI CMI Chat: Zapnuté 
Modules -> 56 enabled 3 disabled: spawnerProximity, spawners, spawnerCharge
--------------------------------------------------
```

### Errors

```shell
purpur console report: https://pastebin.com/X5zAqbUs 
*waterfall console report: https://pastebin.com/7CLk4vVL
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Waterfall error isint related to CMI, it looks to be related to some NPC plugin trying to create team.
For first error, looks to be issue with players display name not fitting into database field, which in general should not have happen as it should have plenty of room. Double check if its type is set to Text and not TinyText format.

**Comment by mitalnet** [comment]
I set color names with 
/nick playername {#color1>}playername{#color2<}
