### ISSUE TITLE
Scheduler - random delay?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#8348]
Hello, is random delay supported in the scheduler? I've tried %cmi_random_[from]_[to]% but it doesn't seem to work, is there some other workaround for it? Or like min & max delay? Like that I want to execute command from 1-5m randomly, or so.

**Comment by CloudeLecaw** [comment]
i requested this allready. current it does not exist

**Comment by Zrips** [comment]
Should be working with latest updates

**Comment by bobhenl** [comment]
Still seems to be a bit broken, 
When using this as delay:
  Delay: '%cmi_random_600_900%'

it still keeps triggering the scheduler like there's almost no delay. Any idea why?
@Zrips

**Comment by CloudeLecaw** [comment]
use it without the qoutes
