### ISSUE TITLE
[MFM] Console Spam on 1.20.4

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#8349]
### Description of Issue

Putting a bug in your ear here about [this issue](https://github.com/Zrips/MobFarmManager/issues/59) in case you don't check that one often. 

### Version Information

```shell
CMI plugin version: 9.6.9.3 BungeeCord CMIB  SqLite
CMILib: 1.4.4.2 
MobFarmManager version: 2.1.0.4
Server: Paper(318) 1.20.2-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 57 enabled 2 disabled: ranks, skin
```

### Errors

```shell
https://gist.github.com/mercurialmusic/905cede15c13d652b4aef376307ddd14
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
New version is out with a fix
