### ISSUE TITLE
Bug in ElytraBoostListener.class - Renamed Items Not Consumed on Elytra Boost

### ISSUE THREAD

**Issue by bilwjjsai0093** [Zrips/CMI#8357]
### Description of Issue

Hello, I've encountered an issue within the ElytraBoostListener.class. When a player uses a renamed item for elytra boosting, the item is not consumed.
On examining the related code, the issue might be because the newItemStack() method creates an ItemStack that only checks for the item's type while it ignores any renamed or meta data that might have been altered. As a result, as long as the item's type matches, regardless of whether the item has been renamed, it is considered acceptable for boosting. However, only original-named items get wiped during the boost consumption mechanism whilst renamed items are not consumed.
I believe this might be a bug and I am looking forward to its rectification. You might consider adding checks for item names and/or metadata in the item consumption code to ensure even renamed items are correctly consumed.
Thank you very much for your time and assistance.

### Version Information

```shell
CMI version 9.6.9.3
CMILib version 1.4.4.2
Server Purpur(2062) 1.20.1-R0.1-SNAPSHOT-
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by bilwjjsai0093** [comment]
if the set item is coal, the coal can be consumed normally without renaming, but it will not be consumed after renaming.

**Comment by Zrips** [comment]
Will be fixed with next update
