### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by w1th0utme** [Zrips/CMI#8362]
### Description of Issue

I did a profiler with --only-ticks-over 200 and noticed that only CMI causes a delay with the following output
![image](https://github.com/Zrips/CMI/assets/137961937/09cedc28-6d98-428f-890f-10f0933d72a5)
Is it possible to do something about it?

### Version Information

```shell
CMI: 9.6.9.3 MySQL: 9.6.9.4 CMILib: 1.4.4.2 Ver:1.20.1
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
This should have been fixed with 9.6.9.4 update
