### ISSUE TITLE
IncompatibleClassChangeError with Discord messages in CMI 9.6.9.5 

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#8370]
### Description of Issue

Getting a bit of error spam with CMI after updating to DiscordSRV 1.27.0 on player chat **from** Discord: https://gist.github.com/mercurialmusic/5b710b78e5d38e2262989fdb1fcfb26a 

We've been using CMI Chat while waiting for our usual chat plugin to update. The error doesn't seem to be affecting much, although I've noticed the [Discord] prefix doesn't print in chat (not a big deal - it didn't before this DiscordSRV update either -- that part could just as easily be a misconfiguration on my end).

### Version Information

```shell
[19:08:59 INFO]: CMI plugin version: 9.6.9.5 Velocity CMIB  SqLite
[19:08:59 INFO]: CMILib: 1.4.4.2 
[19:08:59 INFO]: Server: Paper(378) 1.20.4-R0.1-SNAPSHOT-
[19:08:59 INFO]: CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled 
[19:08:59 INFO]: Modules -> 57 enabled 2 disabled: ranks, skin
```

### Relevant Plugins

DiscordSRV 1.27.0

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
