### ISSUE TITLE
Sethome

### ISSUE THREAD

**Issue by Creeper2042** [Zrips/CMI#8371]
Hi, Is it possible to have the name distinction between bed and home, when you do the sethome command it is called home by default the home but the problem that when you use the bed it sets the home there and if you accidentally break the bed you lose the home.

**Comment by CloudeLecaw** [comment]
you can disable home removal on bedbreak in Homes.yml.

Also you can define the default /sethome and bed home name in Homes.yml

**Comment by Zrips** [comment]
@Creeper2042 
As @CloudeLecaw mentioned here, we do have few options relating to home setup, by default we will use "Home" name as default one when interacting with bed, you can change that to something else if its causing confusion for the people.
