### ISSUE TITLE
CMI IC Villager does not save

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#838]
**Description of issue or feature request:**

When you add an entity to a IC then reboot your server, the entity is no longer set, but the command is still paired to the IC name except right-clicking the enitity does nothing since it resets.

Using the latest 24 dev build of Citizens2
#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

**Cmi Version (using`/cmi version`):**  8.0.9.0

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  1.13.1

**Comment by 0xC1A551C** [comment]
Still having this issue even after the latest update.

**Comment by Zrips** [comment]
Issue with Citizens2 plugin as they are changing entities UUID by which CMI detects which IC is attached to which entities. 
Should be ok with next update. Not 100%, as there are some issues when adding direct compatibility with Citizens API.

**Comment by Zrips** [comment]
Should be ok with 8.0.14.0 release. I hope.
