### ISSUE TITLE
URLS from CustomText not clickable

### ISSUE THREAD

**Issue by PanetiX** [Zrips/CMI#8380]
### Description of Issue

Since latest update (CMI 9.6.9.6, CMILib 1.4.4.4) URLS from CustomTexts are not clickable in Chat.

### Version Information

```shell
--------------------------------------------------
CMI Plugin Version: 9.6.9.6 BungeeCord CMIB  MySQL
CMILib: 1.4.4.4 
Server: Paper(318) 1.20.2-R0.1-SNAPSHOT-
CMI economy: Aktiviert Vault: 1.7.3-b CMI Chat: Aktiviert 
Modules -> 56 enabled 3 disabled: deathMessages, tablist, votifier
--------------------------------------------------
```

### Errors

```shell
No errors in Chat or Server Log.
```

### Relevant Config Sections

```yaml
All CustomText files.
Code example:

<T>- &bVoteseite 1 &f- &eKlick mich!</T><H>&aVote Seite öffnen</H><URL>https://minecraft-server.eu/vote/index/221FE/[playerName]</URL>
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mercurialmusic** [comment]
Confirming. No errors that I notice. Tried playing around with format and noticed that any ctext with even a partially formed link (e.g. minecraft.net) inside the `<T>text brackets</T>` seems to break at some point as well. 

CMI plugin version: 9.6.9.6 Velocity CMIB  SqLite
CMILib: 1.4.4.4 
Server: Paper(381) 1.20.4-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled 
Modules -> 57 enabled 2 disabled: ranks, skin

**Comment by Zrips** [comment]
Will be fixed with next CMILib update which shoudl
 come out today
