### ISSUE TITLE
A simple check on if user is online as true or false integer

### ISSUE THREAD

**Issue by Zethrus** [Zrips/CMI#839]
Hello,

I am currently using CMI's MySQL backend to display statistics on my website on user profiles. However, I am wondering if it would be possible if you could add a "isOnline" column in the CMI_users table that is either 1 or 0 to indicate true or false as it would be nice to be able to check if the use his currently on the server via MySQL. 

Now, maybe the reason why you do not have such a thing is due to the fact it would cause server load. I noticed you already log the log off and log on times of users in the MySQL database so I don't see why I simple true/false check would cause any additional load with the already in process task.

Thank you for the great work,
    - Zethrus

**Comment by CloudeLecaw** [comment]
In cmi Info u have a true fall intrigger allready...

**Comment by Zethrus** [comment]
> In cmi Info u have a true fall intrigger allready... In the table you see if the player is online or not

Where in the MySQL database table of CMI_users do you see an integer stating that player is online? What is the column called?

**Comment by CloudeLecaw** [comment]
Ahh i see, you want a mySQL value for the database so you can show on the homepages the online Players.

**Comment by Zethrus** [comment]
> Ahh i see, you want a mySQL value for the database so you can show on the homepages the online Players.
Exactly. Well, online status on user profiles.

I use CMI for a backend link to my Minecraft server from the website.

**Comment by CloudeLecaw** [comment]
It is not stored, it simply asks "Player onlone?" and if he is online then you get a true else a false.

**Comment by Zethrus** [comment]
> It is not stored, it simply asks "Player onlone?" and if he is online then you get a true else a false.

That means nothing to me if it's not in a myself database as I use CMI as a backend for my website -> Minecraft link.

**Comment by LogGits** [comment]
CMI's MySQL database doesn't store online status. You will have to find alternative methods for this type of feature.

**Comment by Zethrus** [comment]
Figured so, just would be nice if it would that way I could eliminate another plugin with CMI :P
