### ISSUE TITLE
Old display method holograms cannot execute commands on interaction

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#8391]
### Description of Issue

Create a hologram with old display method:
![image](https://github.com/Zrips/CMI/assets/43506080/1c205a35-6489-4ec2-a097-6c6cad02dbd4)
Enable interactions:
![image](https://github.com/Zrips/CMI/assets/43506080/64c18bb9-d8a5-4373-be8b-67c3b3291bf4)
Add commands on interactions:
![image](https://github.com/Zrips/CMI/assets/43506080/80812651-2f59-4f32-b8a5-9b476bc7757c)
**Click on command - nothing happens.**

Try to use new display method:
![image](https://github.com/Zrips/CMI/assets/43506080/7718d26b-5528-4bc2-aa36-abd3193aae55)
Works as expected:
![image](https://github.com/Zrips/CMI/assets/43506080/52110e3f-d1e3-4f2a-bf40-aa1dfcc308bb)

The reason I cannot use new display method yet, because large portion of players still use older clients.

### Version Information

```shell
> cmi version
[20:51:53 INFO]: --------------------------------------------------
[20:51:53 INFO]: CMI: 9.6.9.8 SqLite
[20:51:53 INFO]: CMILib: 1.4.4.6
[20:51:53 INFO]: Server: Paper(385) 1.20.4-R0.1-SNAPSHOT-
[20:51:53 INFO]: CMI economy: Disabled CMI Chat: Disabled
[20:51:53 INFO]: Modules -> 58 enabled 1 disabled: votifier
[20:51:53 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by radiant-ai** [comment]
I can confirm this got fixed as of latest CMI update.

**Comment by radiant-ai** [comment]
Actually not fully fixed. Holograms which use tags for per-line interactions are still broken. E.g this hologram does not work:
![image](https://github.com/Zrips/CMI/assets/43506080/d228db5f-e3d6-4fb7-92e2-e6186df53887)

**Comment by Zrips** [comment]
Those commands are being performed from console by default, so you might want to add asPlayer! in front of it to trigger it from the player who clicked. Alternatively if command supports you can add [playerName] variable to insert players name
![image](https://github.com/Zrips/CMI/assets/10416201/a380488d-dd87-4ceb-bc3c-fc83441a6a02)
If issue persists, let me know.
