### ISSUE TITLE
Normal holograms don't execute commands

### ISSUE THREAD

**Issue by RickyLaChow** [Zrips/CMI#8398]
### Description of Issue

from 9.6.9.6 normal holograms don't execute commands
i have a lot of holograms with sudo commands
And don't work from 9.6.9.6
but if i use the newest hologram system work

### Version Information

```shell
[10:36:26 INFO]: --------------------------------------------------
[10:36:26 INFO]: Versione di CMI: 9.6.9.8 Velocity CMIB  SqLite
[10:36:26 INFO]: CMILib: 1.4.4.6 
[10:36:26 INFO]: Server: Paper(381) 1.20.4-R0.1-SNAPSHOT-
[10:36:26 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[10:36:26 INFO]: Modules -> 55 enabled 4 disabled: chatBubble, tablist, afk, homeInteractions
[10:36:26 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
motel-3-020:
  Loc: Prymacity;710.54;72.37;-17.46
  HoverParticles:
    Count: 1
  Range: 5
  RangeExtra: 8
  Spacing: 0.24
  Interactable: true
  Commands:
  - sudo [playername] motel buy motel-3-020
  Lines:
  - '%img_motel% &7020'
  - '&6Clicca per affittare'
  - '&7Stato: %almotel_motel-3-020_state%'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by RickyLaChow** [comment]
Nothing changes between sudo and asPlayer!
Are you sure you have everything the same as me to say that your server is not working?

**Comment by CloudeLecaw** [comment]
well could you try a simple 3 liner?

test1
test2
test3

and look if you can click on them?

**Comment by RickyLaChow** [comment]
> well could you try a simple 3 liner?
> 
> test1 test2 test3
> 
> and look if you can click on them?

Don't work

**Comment by ChimpGamer** [comment]
Same here. I did some more testing. When using CMI 9.6.9.3 it works fine but when using 9.6.9.4 or newer is stops working.

**Comment by Zrips** [comment]
@RickyLaChow 
Will be fixed with next update. Tho, I would strongly recommend to switch to new display method which look alot better and doesn't have this issue. Just open hologram editor and click top left icon. But in any case, this will be resolved with next update. Sorry for inconvenience.
