### ISSUE TITLE
CMI and Residence not interacting well.

### ISSUE THREAD

**Issue by Pyrite-Ace** [Zrips/CMI#84]
Hello! I have an issue that is popping up with two of Zrips's plugins. Normal players have their shulker boxes disappear if they try to place the shulker box with a shift + right click on a residence that they do not have "place" permissions to.

I have the most up to date versions of both CMI and residence as of this writing. For CMI, i have the cmi.openshulker permission set, but not the cmi.openshulker.shift   - Players complained too much that they couldn't place shulker boxes when that permission was active (I guess shift+right click is a common way to place shulker boxes?)

This issue does not occur if the player just normally tries to place the shulker box without shifting in a residence without place permissions. Also does not occur if they do have place permissions. The placement fails and the item is restored to the inventory.

**Comment by Zrips** [comment]
Confirmed, will be fixed with next build
