### ISSUE TITLE
When I use the trench enchantment from Advanced Enchantments on CMI heads, they duplicate

### ISSUE THREAD

**Issue by Joaofixe** [Zrips/CMI#8409]
When I use the smelt enchantment from Advanced Enchantments on CMI heads, they duplicate; however, if it's heads from other plugins, this doesn't happen. Is this an issue with the enchantment or with CMI? (no erros on console)

**Comment by Zrips** [comment]
Generally if you already have a head it should not do anything to it when you enchant with this 3rd party plugin. If you have a chance try testing this without CMI while still having CMI created head. You can alternatively check heads NBT data in case it contains something what causes this duplication error. Don;t have access to Advanced Enchantments, so can't really test it out and give better idea what's going on with it at this moment. Closing ticket for now. If you will have any extra information about this issue, let me know.

**Comment by lajnicek** [comment]
Hello,
It's only for mobheads stored in customheads.yml
Player heads is ok.
There is an issue in AdvancedEnchanments Github too. 
I have added some info there with NBT too
I don't know if its AE or CMI bug  :D


Link:
https://github.com/GC-spigot/AdvancedEnchantments/issues/3949
