### ISSUE TITLE
How can I remove the skin module?  If the above is not possible, how can I make it so that players can add skins with URLs?

### ISSUE THREAD

**Issue by erickterri** [Zrips/CMI#8415]
How can I remove the skin module?

If the above is not possible, how can I make it so that players can add skins with URLs?

**Comment by Zrips** [comment]
There is module file where you can disable things relating to specific behaviors. Just set it to false and reload server. Tho by default we are not modifying players skins if its not set with cmi skin command and AutoApply isn't enabled. 
At the moment you can only set players skin by provided players name or UUID, while url isint supported at this moment.
