### ISSUE TITLE
[totalUsers] placeholder seems to have broke?

### ISSUE THREAD

**Issue by alfredcort** [Zrips/CMI#8417]
### Description of Issue

I've been using this placeholder in my welcome message for years and it has worked fine. All of a sudden, without changing the welcome message at all, it has broke.

This is the line that handles it:
`FirstJoin: \n{#E7F5FA}Welcome {#A4E2FA}[playerDisplayName] {#E7F5FA}to the server! &8[{#A4E2FA}#[totalUsers]&8]\n&7`

In the screenshot linked there's an example of what this message now outputs. Before, it would show `[#xx]`, but not only shows `#`. I've asked several times in the Discord without getting a response. What am I doing wrong, has something changed?

<img width="409" alt="Screenshot 2024-01-20 at 07 58 11" src="https://github.com/Zrips/CMI/assets/72607588/002fa34e-3e1c-4db7-82a8-8c311a22df1f">

### Version Information

```shell
CMI: 9.6.9.9 SqLite
CMILib: 1.4.4.7 
Server: Purpur(2084) 1.20.2-R0.1-SNAPSHOT+
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 58 enabled 1 disabled: tablist
```

### Relevant Config Sections

```yaml
`FirstJoin: \n{#E7F5FA}Welcome {#A4E2FA}[playerDisplayName] {#E7F5FA}to the server! &8[{#A4E2FA}#[totalUsers]&8]\n&7`
```

### Relevant Plugins

CMI,CMILIB

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
By any chance your total player number in range of 3 or 6 digits? As it could be interpreted as a hex color code due to that # in front of it. Just add space between # and player count or use some alternative symbol for it to avoid this issue.
