### ISSUE TITLE
GUI hover text not displaying

### ISSUE THREAD

**Issue by ghost** [Zrips/CMI#8418]
### Description of Issue

GUI menus are not displaying any text, aside from the vanilla item name, in any CMI menu. (Image attached for reference.)
![image](https://github.com/Zrips/CMI/assets/157298490/bf9f61e6-a382-421c-a43f-14e4971e97bf)

This behaviour is not happening with other GUI menus running on the server (For example, in the Lands plugin.)

Attempts to resolve:

- Uninstalled all other plugins, running Paper with just CMI and CMILib.
- Completely reset my server (Reset all files and folders) - Fresh install of Paper, CMI and CMILib.
- Changes Java JRE from 17 to 21, 21 to 17.
- Installed CMILib on one restart, and CMI on another to ensure CMILib was running ahead of CMI.
- Deleted EN language files and restarted server.

None of the above have resolved the issue.

### Version Information

```shell
CMI: 9.6.9.9 SqLite
CMILib: 1.4.4.7
Server: Paper(392) 1.20.4-R0.1-SNAPSHOT+
Vault: 1.7.3-CMI
Modules: 58 enabled / 1 disabled (votifier)
```

### Errors

```shell
No errors on startup logs or whilst accessing GUI commands.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Tested with this setup 
![image](https://github.com/Zrips/CMI/assets/10416201/aa93c307-abfa-45d3-98e1-e8191927cfe2)
which produced expected results and item names in GUI was shown properly. Could you test it out without any other plugin to rule out possible compatibility issues?
