### ISSUE TITLE
chat formatting

### ISSUE THREAD

**Issue by pinuxio** [Zrips/CMI#8419]
good evening, I should set the chat prefixes with
%luckperms_prefix%
could someone help me?

**Comment by Zrips** [comment]
All chat related settings can be modified in chat.yml file, you can set GeneralFormat to something like this to get desired effect
`  GeneralFormat: '{#brown}%luckperms_prefix%&7{nicknameprefix}{displayName}&7: &r%cmi_user_chatcolor%{message}'` tho keep in mind that non CMI placeholders will need PlaceholderAPI plugin to be present for those to be translated
