### ISSUE TITLE
formatting of $ symbol in /cmi balance

### ISSUE THREAD

**Issue by malonnnn** [Zrips/CMI#842]
**Description of issue or feature request:**

To use a dollar symbol, you must enter it in the config like '\$'
When checking your balance, the backslash shows up

/cmi balance
Money: \$60.00

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

```
CurrencySymbol: \$
```

**Cmi Version (using`/cmi version`):** 

CMI plugin version: 8.0.9.0
Server version: Paper(273) 1.13.1-R0.1-SNAPSHOT
Vault version: 1.7.1-b91(CMIEInjector)

**Server Type (Spigot/Paperspigot/etc):** 

This can be determined using /ver, it is redundant

**Server Version (using `/ver`):** 

This server is running Paper version git-Paper-273 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
Previous version: git-Paper-271 (MC: 1.13.1)
Checking version, please wait...
You are running the latest version

**Comment by Zrips** [comment]
Well you do have backslash in your currency format, so would suggest to remove it if you don't want it in currency format.

**Comment by malonnnn** [comment]
@Zrips 

You can't use just $ in the config, it shows up as %vault_economy_placeholder% instead of "$"

ps I can't actually recall what placeholder it is, i just can tell you that $ by itself does not work in the config
