### ISSUE TITLE
Unknown CMI command source (Rcon) broadcast

### ISSUE THREAD

**Issue by Sm1leClock** [Zrips/CMI#8428]
### Description of Issue

i use "cmi broadcast" from RCON and it give me error

https://media.discordapp.net/attachments/526402563847880725/1199600307458560040/image.png?ex=65c321d8&is=65b0acd8&hm=3d857b7d5f1f2b4c0e8e7abfd574eca29c51c1a85e6072fce54eeb3e86db7e51&=&format=webp&quality=lossless

### Version Information

```shell
CMI: 9.6.9.9
CMI LIB: 1.4.4.7
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by MedvedEE** [comment]
https://github.com/Zrips/CMI/issues/8379
