### ISSUE TITLE
/cmi tmb [title %subtitle% subtitle] does not exist

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#843]
> /cmi tmb [title %subtitle% subtitle] - sends title message to all players online

this command does not exists but it would be needed by use for titlemease all Players..why there is no tmb? :(

Could this be because the comamnd is now implemented in
/cmi titlemsg [playerName/all] [title %subtitle% subtitle] - sends title type message to Player ???

the wiki may is outdated here becaus eit sais:

> /cmi titlemsg [playerName] [title %subtitle% subtitle] - sends title type message to player

**Comment by Baktus79** [comment]
'/cmi titlemsg' has replaced the old '/cmi tmb'. Use '/cmi titlemsg all' for all players on the server.

**Comment by CloudeLecaw** [comment]
I saw that, and replaced it allready in cmis wiki. :)  thank you anyway  :-)
