### ISSUE TITLE
Do deathmessages support [itemDisplayname] instead of [item]?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8430]
Do deathmessages support [itemDisplayname] instead of [item]?

It would be nice if named items if named (normal name if then have no name)

would be supported.. or is it allready included in [item] ?

**Comment by Zrips** [comment]
[item] should use items display name by default, this includes its colorized display name, so anything goes with that one, if one is present, if not it should default to materials name which on itself could be translated if possible. 
Will add extra variable to display items material name by default, in case someone wants it.
