### ISSUE TITLE
invetory rollback

### ISSUE THREAD

**Issue by pinuxio** [Zrips/CMI#8431]
good morning, among the commands I'm looking for a rollback inv to restore the players' inventories in case of need but I can't find anything about it, can you suggest something to me

**Comment by CloudeLecaw** [comment]
CMI doesn not Save inventories by itself.

You can save them on Death or by command.
You can check them by /cmi invlist PLAYERNAME
klick on desired entry in chat and a  gui pops up where you get information and see the inventory.

You can manually do this if you know the ID or wanne load the last without the list too.
with `icm invload (sourceName) (targetName) [id/last]` and save it with  `cmi invsave (playerName) (id) (-s)`.

**Comment by CloudeLecaw** [comment]
Eventcommand can be used... if you need that automatily.

**Comment by pinuxio** [comment]
grazie
________________________________
Da: CloudeLecaw ***@***.***>
Inviato: mercoledì 24 gennaio 2024 10:07
A: Zrips/CMI ***@***.***>
Cc: pinuxio ***@***.***>; Author ***@***.***>
Oggetto: Re: [Zrips/CMI] invetory rollback (Issue #8431)


if you may have 150 slots made for each player. and players die often and you want to restore their inventory the cmi invlist is one of the best options to get a good view what inventory you want to restart.
