### ISSUE TITLE
Balance is 0

### ISSUE THREAD

**Issue by dabuniu13** [Zrips/CMI#8444]
![QQ截图20240129192652](https://github.com/Zrips/CMI/assets/94603401/060b0e5d-443c-4815-b0c5-025153da4b77)
I sold an iron ingot, but my balance is still 0
This is the configuration file
![QQ截图20240130130151](https://github.com/Zrips/CMI/assets/94603401/48e0d03d-4174-4993-9401-90e71d9c3754)

**Comment by Zrips** [comment]
Do you have economy enabled? Show output from /cmi version

**Comment by CloudeLecaw** [comment]
why your checks and condition contain spaces?
