### ISSUE TITLE
what to use instead @p

### ISSUE THREAD

**Issue by wibonsue** [Zrips/CMI#8449]
hello i want my players to when they click a button that is on command block to make their hp reset so i did this

/cmi:maxhp clear @p

but on console it says
![Ekran görüntüsü 2024-02-02 110835](https://github.com/Zrips/CMI/assets/89047094/f5ba376c-f0a9-4ff0-8589-7fd14d2b14da)

so what should i use instead @p

**Comment by wibonsue** [comment]
@Zrips

**Comment by TheBadshah** [comment]
[playerName]

**Comment by TheBadshah** [comment]
Also instead of using the command block why bot use cmi's interactive command?

**Comment by wibonsue** [comment]
> Also instead of using the command block why not use cmi's interactive command?

what is that ?

**Comment by CloudeLecaw** [comment]
/cmi:maxhp clear @p?

insert in your commandblock 
`cmi maxhp clear [playerName] -s`

**Comment by wibonsue** [comment]
> /cmi:maxhp clear @p?
> 
> insert in your commandblock `cmi maxhp clear [playerName] -s`
> 
> but this means [playerName] is the command mmand trigger

it still says "Can't find player with this name! ([name]) (maxhp -> [playerName])"

**Comment by wibonsue** [comment]
this worked

cmi maxhp clear @p -s
