### ISSUE TITLE
KDRatio

### ISSUE THREAD

**Issue by osmanxdgn** [Zrips/CMI#8453]
Player kill to death ratio placeholder can be added

like %cmi_user_stats_player_kdratio%

**Comment by CloudeLecaw** [comment]
this is the wrong place for requests

make it here

https://github.com/Zrips/CMI/discussions/new?category=feature-requests

**Comment by Zrips** [comment]
@osmanxdgn 
You can use this  %cmi_equation_{cmi_user_stats_player_kills}/{cmi_user_stats_deaths}% to get your desired result
