### ISSUE TITLE
Bungeecord features are no longer work on CMI 9.6.10.1 CMIB 1.0.2.3

### ISSUE THREAD

**Issue by nhanledev** [Zrips/CMI#8454]
### Description of Issue

Bungeecord features like `/cmi serverlist` and its placeholders are no longer work. Permissions are not either. Only /cmi server works in my testing.

### Version Information

```shell
Bungeecord (latest - Because I use Flamecord 1.9.3)
Paper 1.20.4 build 407
CMI 9.6.10.1
CMIBungee 1.0.2.3
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by punkydie** [comment]
i have the same problem

**Comment by HandsomeshadowYT** [comment]
i have the same problem

**Comment by nhanledev** [comment]
this is fixed on recent version
