### ISSUE TITLE
Velocity features doesn't work on the latest version of CMI, CMILib, CMIV

### ISSUE THREAD

**Issue by Hakuyako** [Zrips/CMI#8455]
### Description of Issue

Almost all velocity features doesn't work in the latest/recent version of CMI.

Multi-server public messages cannot be sent, Tablist cannot display players from different servers, and when using tp and tpa command players cannot be teleported to other players on different server.

### Version Information

```shell
CMI 9.6.10.1
CMILib 1.4.5.0
CMIV 1.0.0.3
Paper 1.20.1-196
Velocity 3.3.0-346
```

### Errors

```shell
No error logged
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by punkydie** [comment]
Multiservermessages works. The rest not correct.
