### ISSUE TITLE
TryMe spamming error in console

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#8460]
Hi Zrips, I just wanted to let you know that there's regarding TryMe that spams the console. There are already 2 people who have this issue, and I believe there are more of them. It would be nice if it could be fixed. I'm just reminding you here cause I'm not sure if you read TryMe Github. https://github.com/Zrips/TryMe/issues/31

**Comment by Zrips** [comment]
Should be fixed with next update
