### ISSUE TITLE
velocity support

### ISSUE THREAD

**Issue by pinuxio** [Zrips/CMI#8462]
Having a bungee net created with velocity I wanted to know things:
1) is it possible to ban and unban via cmi having installed CMIV?
2) is it possible to send a chat alert to all servers?
![a](https://github.com/Zrips/CMI/assets/57964445/bc610ff0-3983-4a05-97bb-4b641a7ba5eb)

**Comment by Zrips** [comment]
at the moment cross server support is limited to chat messages and some teleportations. You can broadcast message across servers with /cmi bbroadcast, but we don't have ban/unban network wide at this moment.
