### ISSUE TITLE
Random not working in give command on 1.20.4

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [Zrips/CMI#8466]
### Description of Issue

When i use command `/cmi give <player> cobblestone %rand/1152-2304%` it gives only one item, when it should be randomized, as it was before.

### Version Information

```shell
11.02 01:56:24 [Server] INFO CMI plugin version: 9.6.10.4 Unknown  SqLite
11.02 01:56:24 [Server] INFO CMILib: 1.4.5.0 
11.02 01:56:24 [Server] INFO Server: Purpur(2138) 1.20.4-R0.1-SNAPSHOT-
11.02 01:56:24 [Server] INFO CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
11.02 01:56:24 [Server] INFO Modules -> 32 enabled 27 disabled: spawnerProximity, cuffed, customMessages, mirror, tablist, moneyCheque, skin, elytraBoost, elytraLaunch, bossBarCompass, votifier, shulkerBackpack, spawnerCharge, vanish, timedCommands, homeInteractions, portals, afk, holograms, spawners, dynamicSigns, playerChatTag, flightCharge, disabledEnchants, worldLimits, ranks, totemBehavior
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
use the new syntax :)

**Comment by Kryniowesegryderiusz** [comment]
Okay so: `/cmi give ?` shows wrong info:
![image](https://github.com/Zrips/CMI/assets/13908095/a1871bcf-a509-4726-86f3-c8315149214e)

Also `/cmi [playerName] Krynio cobblestone %cmi_random_1_5%` and `/cmi [playerName] Krynio cobblestone-%cmi_random_1_5%` doesnt work, so maybe somehow give command doesnt include random option anymore

**Comment by CloudeLecaw** [comment]
> Okay so: `/cmi give ?` shows wrong info: ![image](https://private-user-images.githubusercontent.com/13908095/304522364-a1871bcf-a509-4726-86f3-c8315149214e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NTQ0MjUsIm5iZiI6MTcwNzg1NDEyNSwicGF0aCI6Ii8xMzkwODA5NS8zMDQ1MjIzNjQtYTE4NzFiY2YtYTUwOS00NzI2LTg2ZjMtYzgzMTUxNDkyMTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE5NTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxOWQzY2YwMWI5OTBlOGE2ZDE1ODA2MmZhMTk0NDQzZmJhZjA5MjZjNTY3NWFlNzU3Mzk3YjIxYzlkMDU1MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zIzoOOKNdenL85qjt_0WY6POZVohZZ5c2BJ930fGTjI)
> 
> Also `/cmi [playerName] Krynio cobblestone %cmi_random_1_5%` and `/cmi [playerName] Krynio cobblestone-%cmi_random_1_5%` doesnt work, so maybe somehow give command doesnt include random option anymore

Yes

**Comment by Kryniowesegryderiusz** [comment]
> > Okay so: `/cmi give ?` shows wrong info: ![image](https://private-user-images.githubusercontent.com/13908095/304522364-a1871bcf-a509-4726-86f3-c8315149214e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NTQ0MjUsIm5iZiI6MTcwNzg1NDEyNSwicGF0aCI6Ii8xMzkwODA5NS8zMDQ1MjIzNjQtYTE4NzFiY2YtYTUwOS00NzI2LTg2ZjMtYzgzMTUxNDkyMTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE5NTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxOWQzY2YwMWI5OTBlOGE2ZDE1ODA2MmZhMTk0NDQzZmJhZjA5MjZjNTY3NWFlNzU3Mzk3YjIxYzlkMDU1MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zIzoOOKNdenL85qjt_0WY6POZVohZZ5c2BJ930fGTjI)
> > Also `/cmi [playerName] Krynio cobblestone %cmi_random_1_5%` and `/cmi [playerName] Krynio cobblestone-%cmi_random_1_5%` doesnt work, so maybe somehow give command doesnt include random option anymore
> 
> correct
> 
> by the way its NOT what i wrote. i said `/cmi give YOURNAME cobblestone-%cmi_random_1_5%` because the new format is item-amount
> 
> pls look here how give command, item! and hasitem! now work https://www.zrips.net/cmi/commands/icwol/

I know, but `/cmi give YOURNAME cobblestone-%cmi_random_1_5%` doesnt work. It always gives you 1 cobble.

**Comment by CloudeLecaw** [comment]
this placeholder is not made for inagme useage.
make  customalias where you use it.

**Comment by Zrips** [comment]
Should work properly with next CMILib and CMI updates. At the moment placeholders have been limited to items name and its lore

**Comment by mare-on** [comment]
The problem is still exists, I'm using CMI 9.6.10.9 and give function with random amount still doesn't work.
@Zrips

**Comment by CloudeLecaw** [comment]
> /cmi give YOURNAME cobblestone-%cmi_random_1_5

you tried `cmi give YOURNAME cobblestone-%cmi_random_1_5%`?

**Comment by mare-on** [comment]
Yes, everytime I still gets only one cobblestone.

@CloudeLecaw 
@Zrips

**Comment by Kryniowesegryderiusz** [comment]
> Yes, everytime I still gets only one cobblestone.
> 
> @CloudeLecaw @Zrips

Use `/cmi give YOURNAME cobblestone;%cmi_random_1_5%`. The command given by CloudeLecaw doesnt work for me either
