### ISSUE TITLE
CommandException with /cmi kill in recent Paper builds

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#8471]
### Description of Issue

Getting "An internal error occurred..." in game and console error when using /cmi kill (both main command and alias) in recent Paper builds. I didn't notice this over the weekend or immediately after updating to CMI 9.6.10.4 so I'm guessing it's a Paper thing.

Console error: https://gist.github.com/mercurialmusic/d9dc447531aba0953b827dbc31f45d0a

### Version Information

```shell
CMI plugin version: 9.6.10.4 Velocity CMIB (CMIV)  SqLite
CMILib: 1.4.5.0 
Server: Paper(423) 1.20.4-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 57 enabled 2 disabled: ranks, skin
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
