### ISSUE TITLE
Bossbarmsg does not update placeholders on interval update when called as console command

### ISSUE THREAD

**Issue by jcnp97** [Zrips/CMI#8478]
### Description of Issue

The bossbarmsg tick update works fine when called as player command (OP) but when it is called as console command (example, using the bossbarmsg command on schedule.yml), it doesn't update on every tick interval.

The following command is used: `cmi bossbarmsg all -p:100 -a:1 -s:1 -t:3 -cw:0.05,10,green,pink,662266 %cmi_server_time_S%` for replicating purposes.

How to replicate:
1. Initiate the command above as player command (OP). The bossbarmsg will update as intended. Changing the numbers on every tick update.
2. Add the following to CMI/Settings/Schedules.yml
```
bossbarbug:
  Enabled: true
  MinPlayers: 1
  FeedBack: true
  Repeat: true
  Delay: 8
  Commands:
  - cmi bossbarmsg all -p:100 -a:1 -s:1 -t:3 -cw:0.05,10,green,pink,662266 %cmi_server_time_S%
```
The number is stucked to whichever first value the placeholder is parsed and will not change on every tick interval. Adding `asConsole!` does not make any difference. 

I've only found out the bug when I used a similar command using another plugin that send out console commands and tried to replicate it using CMI only.

### Version Information

```shell
[21:25:36 INFO]: xGrd issued server command: /cmi version
cmi version
[21:26:29 INFO]: --------------------------------------------------
[21:26:29 INFO]: CMI: 9.6.10.5 SqLite-> 9.6.10.4
[21:26:29 INFO]: CMILib: 1.4.5.1 
[21:26:29 INFO]: Server: Purpur(2141) 1.20.4-R0.1-SNAPSHOT+
[21:26:29 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[21:26:29 INFO]: Modules -> 58 enabled 1 disabled: votifier
[21:26:29 INFO]: --------------------------------------------------
```

### Errors

```shell
No errors found in the console.
```

### Relevant Config Sections

```yaml
No relevant config section, purely commands only.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by nhanledev** [comment]
I can confirm that calling cmi bossbarmsg from event and schedule commands does not update the placeholders inside the message body.

**Comment by CloudeLecaw** [comment]
at least its a message like a chat message there are only a few exetption like the counter placeholder for counting down that update with it.

**Comment by jcnp97** [comment]
> at least its a message like a chat message there are only a few exetption like the counter placeholder for counting down that update with it. so currently its a static bossbarmessage not a dynamic one. So updating of placeholders there means making it a dynnamic bossbar would be a enchantment of a existing feature to a request for discussion :)
> 
> finaly a not exsting feature is not a bug. So it would be nice if this ticket could be closed and a new request would be made for it.
> 
> So feel free to request it here https://github.com/Zrips/CMI/discussions/new?category=enhancement

I'm pretty sure it exists already because updating placeholders works when it is RAN AS PLAYER COMMAND (OP) which I mentioned on this ticket but it doesn't work when RAN AS CONSOLE COMMAND. I wouldn't want to use player command as OP for scheduled events and stuff, heck, will not use it for anything.

Just so you know, dynamic bossbars were added on version [9.6.10.0](https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/update?update=530881) so clearly, this is a bug.

**Comment by nhanledev** [comment]
This is surely a bug because:
- If the bossbarmsg command is run by a player, the placeholders work correctly and constantly update.
- If the bossbarmsg command is run by CMI itself (via Schedule, EventCommands, etc..) the placeholders are parsed at execution time only and the bossbar look like a static one.

**Comment by nhanledev** [comment]
I am in the same boat and have to use other plugin for the persistent bossbar message. If the OP want to know it is https://www.spigotmc.org/resources/minibossbar.103581/ Let's wait until this issue is fixed

**Comment by Zrips** [comment]
Will add new optional setting to not translate placeholders before performing commands, by default placeholders are being translated before its being sent to be processes down the line, so it gets fixated at its original state, which can be handy in some situations, but not always as we have this issue right now. Just add new line with next update
`  DontTranslatePlaceholders: true`
