### ISSUE TITLE
I have already repaid 4 times. Is there any fix?

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#848]
https://www.dropbox.com/s/8d3jhqspj7vepdg/Minecraft%202018.08.23%20-%2013.31.37.01.mp4?dl=0
This video shows
When the player is next to the wall, use the left button to trigger the attachcommand
Will not consume usage

use cmi attachcommand !limiteduse:1!;;!cc!cc open 叢林寶箱 [playerName]
plugins: CrazyCrates

https://www.dropbox.com/s/76u57dvpa9c4hh6/Minecraft%202018.08.23%20-%2013.38.25.02.mp4?dl=0
This video shows
When you open the GUI, Keep pressing right click
Will cause repeated consumption
Consume multiple

use cmi attachcommand !limiteduse:1!;;!cc!cc open 叢林寶箱 [playerName]
plugins: CrazyCrates

I have already repaid 4 times. Is there any repair?

Cmi Version (using/cmi version): 8.0.10.0

Server Type (Spigot/Paperspigot/etc): paper

Server Version (using /ver): 1.12.2

**Comment by CloudeLecaw** [comment]
https://github.com/Zrips/CMI/issues/847

did you double posted your own post? ….

**Comment by Zrips** [comment]
@p82183645 Is this still an issue with nevest version? As of my testing with 8.0.11.0 version on 1.12.2 server all works as it should. If you still have issue, please provide crate config you used for that testing as basic one works just fine and cant confirm this bug.

**Comment by p82183645** [comment]
@Zrips  

test use 8.0.12.0 , use Left button still no fix
but use right no happen

**Comment by p82183645** [comment]
Use the left button against the air
Cause: consume and turn on crate
Some bug: When the GUI interface has not been closed
Repeated clicks will cause repeated consumption

Use the left button against the player
Cause: No consumption and turn on crate

**Comment by LogGits** [comment]
Hey, great news, we were able to reproduce this 👍 The rightclick consumed multiple items and this was resolved. I wasn't able to reproduce the left click not consuming though. Was this done by left clicking a player in a worldguard region? if so can we have the flags for the worldguard region, it would help us test it if you could provide this along with the item you used. Please test this when the next version is released and let us know if you still experience it 🙂

**Comment by LogGits** [comment]
This should be resolved in the next build. If you still experience issues with this please let us know.

**Comment by p82183645** [comment]
still bug

i make video 
look this
https://www.dropbox.com/s/hlz7gq9blen7e9t/Minecraft%202018.12.23%20-%2002.36.42.01.mp4?dl=0

If player against the wall
No consumption (BUG)
