### ISSUE TITLE
Dupe with CMI /invsee

### ISSUE THREAD

**Issue by fortunatas1** [Zrips/CMI#8482]
### Description of Issue

with cmi /invsee you can dupe items
1 player use /invsee on other player
and then player who use invsee pressing ant item with 6-7cps
and after 10 sec
other player press q
and it dupe
https://streamable.com/m5t0l1

### Version Information

```shell
Latest CMI version.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
If issue persists with next update, let me know. Will add some extra protections relating to rapid inventory edits with next CMI update

**Comment by fortunatas1** [comment]
@Zrips you need fix gui delay, not /invsee command.
