### ISSUE TITLE
some of CMI schedules placeholders are not working 

### ISSUE THREAD

**Issue by beeng9** [Zrips/CMI#849]
GiveDiamonds:
  Enabled: true
  PerformOn:
    1:
      Hour: 23
      Minute: 43
      Second: 20 
  Commands:
  - cmi give [randomPlayer] diamond %rand/1-5%
  - msg! [randomPlayer] &eYou just got diamonds!

I used this schedule. just enabled this example schedule.

but, console says Can't find player with this name!

I think both of [randomPlayer] and [allPlayers] are not working.

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## Can't find player with this name! ##
####################
```

**Cmi Version (using`/cmi version`):8.0.10.0

**Server Type (Spigot/Paperspigot/etc):spigot

**Server Version (using `/ver`):1.11

**Comment by Zrips** [comment]
cmi.scheduler.exclude permission node excludes players from [randomPlayer] variable, so if you are testing alone with OP, then you are automatically excluded from that list. 
Keep in mind that you can always double check permission issues with something like **/cmi checkperm schedule**

**Comment by ArkaNetwork-Civcraft** [comment]
> 
> 
> cmi.scheduler.exclude permission node excludes players from [randomPlayer] variable, so if you are testing alone with OP, then you are automatically excluded from that list.
> Keep in mind that you can always double check permission issues with something like **/cmi checkperm schedule**

I think its not just permissions problem.
I tested it with that permission, OP.
and, I used not only [randomPlayer] but also [allPlayers] too.
but every commands are said "Can't find player with this name!"

I just tested with example schedules.
[allPlayers] Do placeholders work honestly?

**Comment by beeng9** [comment]
> 
> 
> cmi.scheduler.exclude permission node excludes players from [randomPlayer] variable, so if you are testing alone with OP, then you are automatically excluded from that list.
> Keep in mind that you can always double check permission issues with something like **/cmi checkperm schedule**

I think its not just permissions problem.
I tested it with permissions, and OP.
And, I used not only [randomPlayer] but also [allPlayers] too.
But every commands are said "Can't find player with this name!"

I just tested with example schedules.
[allPlayers] Do placeholders work honestly?

**Comment by M0dii** [comment]
Gotta bump this up.

Not working for me either. 
CMI 8.6.5.4,
Paper 1.12.2-R0.1-Snapshot.
