### ISSUE TITLE
CMI Interactive Commands

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/CMI#85]
How to get the command to run the console but to get the player clicked on the block/item because I want to make it when a player clicks on a porting it to a residence but it does not work because the command runs from the console ...

**Comment by tmellen** [comment]
can the command run a TP on the player? like /TP [playername] coords, or whatnot?

**Comment by LogGits** [comment]
> How to get the command to run the console but to get the player clicked on the block/item because I want to make it when a player clicks on a porting it to a residence but it does not work because the command runs from the console ...

utilise `asPlayer!` & `asConsole!`, by default cmi runs commands as console. Additionally, `[playerName]` tag will get the players name.

> can the command run a TP on the player? like /TP [playername] coords, or whatnot?

Yes this is possible, `/cmi tppos [playerName] x y z`
