### ISSUE TITLE
AFK TNT

### ISSUE THREAD

**Issue by M4rtyn4** [Zrips/CMI#850]
Hi I had players reporting that while using afk farm tnt gets spawned out of nowhere and they are flushing it with water bucket basically getting free tnt. which makes fishing farm tnt farm :/ 
There is no config for it.
Is there possibility other way to stop players using afk farm after lets say 10-20 tries without killing or feeding them tnt?

CMI 8.0.10.0
Spigot 1.13-R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment]
Well have you thought About using a Plugin like this?
https://www.spigotmc.org/resources/noafkfishing.29634/

**Comment by Zrips** [comment]
@M4rtyn4 
TNT feature is a vanilla behavior, not a CMI one.

**Comment by Zrips** [comment]
@CloudeLecaw Open ticket for suggestion for better fishing farm detection method and we can implement that one if current doesn't work as it should work.
