### ISSUE TITLE
CMI 8.0.10.0 Stopped working?

### ISSUE THREAD

**Issue by DeadIntermediate** [Zrips/CMI#851]
**Description of issue or feature request:**
I have tried to type every single /cmi command and just says "Unknown Command. Type "/help" for help"

**Cmi Version (using`/cmi version`):** 
I could use that command but I ended using /version cmi and I got
CMI Version 8.0.10.0

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
git-Spigot-f823ac5-5cffeca (MC: 1.13.1) (Implenting API version 1.13.1-RC0.1 -SNAPSHOT)

**Comment by CloudeLecaw** [comment]
Well all works fine normaly

have you tried to give yourself the Right permission?

_**cmi.command**_ is needed to execute any of the cmi commands.
tale a look here :) https://www.spigotmc.org/wiki/cmi-permissions/

**Comment by DeadIntermediate** [comment]
I figured out the problem. it was a custom alias called cmi.

So I had to type: /cmi:cmi

**Comment by CloudeLecaw** [comment]
wow that is strange 🥉 
but good that you selved it.
you can force cmi to be used if needed :)
well you still can use the alias.yml and customalias.yml to creat own /commands :-)

what you also could try is to force /cmi to CMI with commands.yml in the main Serverdirectory
simply try to add in it.
```
  cmi:
  - cmi:cmi $$1-
```

this would force your Server to use /cmi:cmi when using /cmi
just dont know if this also will support the TabCompletation of CMI then...
