### ISSUE TITLE
HOLOGRAMS

### ISSUE THREAD

**Issue by capubara** [Zrips/CMI#8515]
### Description of Issue

When i want to place a hologram , i get an issue 
CMILIB requires a function!

### Version Information

```shell
the version of CMI is 9.6.10.6 
and issue is the same as CMI 9.6.9.3
CMILIB version is 1.4.5.2
```

### Errors

```shell
https://mclo.gs/ustaFyO#L1111
```

### Relevant Plugins

Vault 1.7.3 CMILIB 1.4.5.2 

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Start by updating CMILib as from the logs it says to use **CMILib v1.4.1.2** and not 1.4.5.2, which is quite out of date. If issue persists with latest CMIlib version then let me know, but updating it should resolve your issue.
