### ISSUE TITLE
Alias Commands?

### ISSUE THREAD

**Issue by DeadIntermediate** [Zrips/CMI#852]
I am trying to do the alias commands.

From /cmi spawn to /spawn

I have looked in alias.yml and see them, I have allied the permission node: cmi.command.spawn

But nothing is happening. Could I get a better explanation on how this alias works exactly? So I can get the players to do /spawn and /warp and etc, like how Essentials/EssentialsX was?

**Comment by CloudeLecaw** [comment]
Well you have to enable it in alias.yml then u have /spawn same for other commands.

Pls clise the issues if it is fixed now

**Comment by Zrips** [comment]
@DeadIntermediate 
Enable appropriate alias in alias.yml file, reload plugin or server and you have desired alias. In worst case scenario you can create one by yourself with something like **/cmi aliaseditor new spawn-cmi spawn** or **/cmi aliaseditor new warp-cmi warp $1-**
This should be working currently, if you will have issues, please reopen or repost issue.
