### ISSUE TITLE
TPS bar doesnt work correct

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8520]
### Description of Issue

You see the tps numbers and the green bow from cmi below.. you see the numbers are correct but the grahical one shows all green with 20.0 tps over all

![Snag_e6cc2a](https://github.com/Zrips/CMI/assets/12080017/50797898-826f-4558-8ddb-d1502ff13416)

### Version Information
![Snag_e86355](https://github.com/Zrips/CMI/assets/12080017/5226e1e5-753b-4ed3-abdd-b46bf11a7370)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should work better with next version
