### ISSUE TITLE
Cmi Kill bug

### ISSUE THREAD

**Issue by khoiangel** [Zrips/CMI#8523]
### Description of Issue

error why trying to use /cmi kill [player]

### Version Information

```shell
CMI: 9.6.10.7 SqLite
CMILib: 1.4.5.2
Server: Paper(20240220) 1.20.4-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-b(CMIEInjector) CMI Chat: Enabled
Modules -> 51 enabled 8 disabled: deathMessages, tablist, ranks, playerCombat, votifier, skin, holograms, spawners
```

### Errors

```shell
https://mclo.gs/Ce87QcL
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Try updating to the latest paper builds which should resolve your issue
