### ISSUE TITLE
kit giving question

### ISSUE THREAD

**Issue by aglarcz** [Zrips/CMI#8525]
Hello guys, i would like to let admins give specific kit to other players but only lets say once per week (for event) but if i set kit delay to 7 days, it only applies for self redeeming.. if admin wants to give the kit to others he can do so without any cooldown..

Is this doable without alias?
Also, is there any way to allow giving only specific kits? Also only via alias I guess?

**Comment by Zrips** [comment]
Not at the moment as there is specific check for kit conditional requirements which is only triggered when its you who is trying to get a kit for yourself. With nxt update you should be able to use -c additional variable to enforce this check while giving kit to another person.
And there is no way to allow to give specific kits besides players actual access to those specific kits. Giving kit to another player will depend on senders access to it, so maybe you could utilize that part if you don't want to allow for your staff members to give out kits which should not be given away at that time.
