### ISSUE TITLE
View local chat for admin

### ISSUE THREAD

**Issue by mab-ru** [Zrips/CMI#853]
Hi! Can you add please view the chat (as socialspy for local chat) to people with permissions (admins)?

**Comment by CloudeLecaw** [comment]
Why the local just should be a spychannel?.... Could you explain what u want?

**Comment by Zrips** [comment]
We do have command for that /cmi socialspy which will enable or disable chat spying. Tho this will enable to see everyones messages in public chat. No clue how would local chat spy should work as you can see it anyways if you are in rage for local chat. So clarification is needed in this case.

**Comment by mab-ru** [comment]
When you activate socialspy, you can see the players ' private messages, but you can't see the local chat, which is outside the set number of blocks

**Comment by Zrips** [comment]
@mab-ru 
My bad, was thinking about different thing. You can bypass local chat range limitations with **cmi.chat.rangebypass** permission node

**Comment by mab-ru** [comment]
Not it :) 
For example, as in the plugin essentials.
essentials.chat.spy | A permission designed for admins, to intercept all local messages (ignoring the chat-radius).

**Comment by Zrips** [comment]
Did you tested that permission node? As it should allow you to see messages from entire server despite your local chat range

**Comment by mab-ru** [comment]
cmi.chat.rangebypass? Yes. 
With this permissions I can write to the whole server. But I don't see the whole server.

**Comment by Zrips** [comment]
Interesting, then it will be bugged out, will have a look at it.

**Comment by Zrips** [comment]
Ok, all seems to work. Did you added permission directly to player as this one requires direct addition and only being OP will not allow you to see chat over range limit

**Comment by mab-ru** [comment]
Thank you, it works. But not very convenient when the secret correspondence of the administrators in the locale sees the server :)
