### ISSUE TITLE
When trying to create a /addhomes command it doesnt process it as a actual permission with the +1 

### ISSUE THREAD

**Issue by astomnll** [Zrips/CMI#8531]
### Description of Issue

It adds the actual thing you type(in this case from the zrips page the code below adds it as a permission instead of adding on to the homes they already have

"asConsole! ptarget:$1! lp user $1 permission set cmi.command.sethome.%cmi_equationint_{cmi_user_maxperm_cmi.command.sethome_1}+1%"
![image](https://github.com/Zrips/CMI/assets/79535818/e16fccf8-aa5b-4812-b84c-ebb504ece305)
![image_2024-03-08_163238669](https://github.com/Zrips/CMI/assets/79535818/362105cd-b3d2-4315-a9e3-0cebab4a5f59)

Me and someone else managed to get it working but only for yourself, And even that didnt work well. Dont have code anymore as its been deleted.
### Version Information

```shell
Picture in description
```

### Errors

```shell
Pictures in description
```

### Relevant Plugins

1.20.4

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update. This was made to only work when performed from console directly and was misbehaving while triggering it as a player
