### ISSUE TITLE
ItemNTB changed in saved items?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8533]
### Description of Issue

Our Server was on 1.20.1 we updated to 1.20.4 and noticed the itemNTB changed,
in Result players cant use the items with new format anymore. The Shops contain the items with the old format for trading.
so what should we do?

![Snag_9d972b9](https://github.com/Zrips/CMI/assets/12080017/5c0ec4e4-4e48-45d6-8c38-ef0626702e78)

### Version Information
![Snag_9d98065](https://github.com/Zrips/CMI/assets/12080017/7771ad78-3ded-4f92-a468-5cab25166891)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
All saving/loading is being done by server and its internal code, I don't have much control over that part. It does tend to change from time to time, in most cases it should not effect plugins work if those are properly using correct identifications of specific itemstacks and not simply compare with == one to the other. Would recommend to register that new item in your plugin whatever is being used to recognize item stack. Item data is somewhat mess and we should be getting complete rework of it with 1.21 version, by what mojang announced, so expect more breaking with next version, tho that might resolve some of the issues we are facing now.
