### ISSUE TITLE
Windows Defender considers the new version as a Trojan script

### ISSUE THREAD

**Issue by SamLam140330** [Zrips/CMI#8534]
### Description of Issue

Both two new versions of CMI (9.6.10.8 and 9.6.10.9) were marked as a Trojan script by Windows Defender
![Screenshot 2024-03-09 053601](https://github.com/Zrips/CMI/assets/48656764/faaf1e19-0cba-4ec8-a544-a52e986b748f)

Not only just me come with this issue but also other users
![Screenshot 2024-03-09 053947](https://github.com/Zrips/CMI/assets/48656764/7e7f2d47-a56e-4ada-9275-8c1f0983d1d8)

### Version Information

```shell
CMI (9.6.10.8 and 9.6.10.9)
```

### Errors

```shell
N/A
```

### Relevant Config Sections

```yaml
N/A
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
https://www.spigotmc.org/threads/windows-defender-false-positives.639507/
Windows defender doing windows defender thing. 
If you are not sure on how safe file is you can alway double check with https://www.virustotal.com/gui/home/upload which will use multiple antivirus programs and provide allot better results in how dangerous file actually is. 
In short: False positive report.
