### ISSUE TITLE
Incorrect display in /near

### ISSUE THREAD

**Issue by yngdrms** [Zrips/CMI#8537]
### Description of Issue

The /near command shows the same nickname even if there are several players nearby

### Version Information

```shell
CMI: 9.6.10.9
CMILib: 1.4.5.2
Server: 1.20.4
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
