### ISSUE TITLE
/cmi bossbarmsg timer doesn't work 

### ISSUE THREAD

**Issue by RegencySolid** [Zrips/CMI#855]
When using the bossbarmsg command and '-t:' the timer will always count down from 6 seconds
for example: 
"cmi bossbarmsg all -a:1 Server Restart in [autoTimeLeft]! -t:2 -p:1" time is set to 2 seconds but counts and lasts for 6 seconds. (the bar itself also counts up, not sure if this is a bug or feature as it shows on the main page counting down and I can't seem to figure out how to make it do that, so please tell me how)

Cmi Version: 8.0.9.0 

Server Type: Spigot 

Server Version: MC: 1.13.1

**Comment by Zrips** [comment]
As help page indicates, -t indicates for how long to keep boossbar visible, this is not indication for how long to count. Will add new variable -sec:[seconds] for simpler usage as this can be confusing.
