### ISSUE TITLE
private message doesn't work in bungeecord when server is in different computer 

### ISSUE THREAD

**Issue by aaa8881** [Zrips/CMI#8552]
### Description of Issue

#8347

### Version Information

```shell
#8347
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by aaa8881** [comment]
@Zrips

**Comment by aaa8881** [comment]
@Zrips , downgrading CMI & CMILib to previously working version 9.5.7.7 does not change. seems like problem of latest CMIB. 

idk why you're ignoring the issue - I am more than willing to silently wait for reply and action if you ever responded something and look into it, but not sure why you wouldnt do that. I believe I did wait for some significant amount of time before.

**Comment by CloudeLecaw** [comment]
aiaiai pls dont use old versions like 9.5.7.7
we are on 9.6.11.2 with cmilib 1.4.5.2

version 9.5.7.7 is a fake?
![Screenshot_2024-03-19-08-42-29-964_com android chrome-edit](https://github.com/Zrips/CMI/assets/12080017/fd5afdee-01a4-4637-a394-18daaccaf24f)

**Comment by aaa8881** [comment]
> aiaiai pls dont use old versions like 9.5.7.7 we are on 9.6.11.2 with cmilib 1.4.5.2 and latest cmib is 1.0.3.1
> 
> version 9.5.7.7 is a fake?, where you took this version from? i asume not from spigot? Even if its version 9.6.7.7 like in the other thread. there is no support if your using a version that is 30 versions behind.
> 
> here you see after version you see after 9.5.1.3 version 9.6.0.0 was coming. ![Screenshot_2024-03-19-08-42-29-964_com android chrome-edit](https://private-user-images.githubusercontent.com/12080017/313964799-fd5afdee-01a4-4637-a394-18daaccaf24f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzg3NTAsIm5iZiI6MTcxMDgzODQ1MCwicGF0aCI6Ii8xMjA4MDAxNy8zMTM5NjQ3OTktZmQ1YWZkZWUtMDFhNC00NjM3LWEzOTQtMThkYWFjY2FmMjRmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4NTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZWM3YjQxODdlMTQzYmVmOTIxODQ4YzgyNWIzYjU5Y2VlMDU4ZjNkYzg3MWQ5OTM1Y2FiMTljODRkNjA1MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uHrygzZ4IYmXTyGin0Zvaw8U9TwPIUjXW37kMSrYxYE)
> 
> so remove your cmi version and pls Update to latest cmi, cmib and cmilib pls.
> 
> if these issues accour for you in the latest versions of cmi, cmilib and cmib feel free to report aggain.

please read issue carefully before mocking at others.
I clearly understand what I'm doing  

1. 9.6.7.7. mistyped. it is correctly written in original issue comments. 
2. it is from spigot which I legitimately purchased and downloaded. 
3. I have upgraded FROM 9.6.7.7 TO 9.6.9.3 ( #8347 ) which was latest at that time. problem happened. 
4. issue still persists in 9.6.10.7 , which was latest version 2 weeks ago when I commented on the issue ( #8347 ). I do not think it will be any different in later version when issue has not been addressed here nor changelog. 
5
