### ISSUE TITLE
elevator problem

### ISSUE THREAD

**Issue by yngdrms** [Zrips/CMI#8559]
### Description of Issue

Sometimes it happens when you can't use the elevator on the plate to move down (by pressing shift). This problem does not occur when teleporting upwards. With what it can be connected, I do not know.

### Version Information

```shell
CMI: 9.6.11.1
CMILib: 1.4.5.2
Server: 1.20.4
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Can you provide image of elevator which causes this issue for you?

**Comment by yngdrms** [comment]
After updating `9.7.0.0` the problem disappeared.
