### ISSUE TITLE
Toast not working

### ISSUE THREAD

**Issue by xPoyraz** [Zrips/CMI#8563]
### Description of Issue

On my 1.16.5 server /cmi toast is not working, no matter what I did I could not solve the problem (I am currently using airplane as fork, I used purpur and paper to test, but the problem is not solved)

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.11.2 BungeeCord CMIB  MySQL
CMILib: 1.4.5.2
Sunucu: Paper(12) 1.16.5-R0.1-SNAPSHOT-
CMI ekonomisi: Devre dışı Kasa: 1.7.3-CMI CMI sohbeti: Etkin
Modüller -> 28 Etkin 31 Devre dışı: spawnerProximity, cuffed, customMessages, mirror, tablist, moneyCheque, skin, noTarget, elytraBoost, cmiPlaytime, bossBarCompass, playerCombat, votifier, shulkerBackpack, headDrop, spawnerCharge, namePlates, timedCommands, homeInteractions, launchPad, anvilRenameColor, jail, spawners, paintingEditor, kits, flightCharge, deathMessages, worldLimitsElytra, worldLimits, ranks, firstJoinMessages
 --------------------------------------------------
```

### Errors

```shell
https://pastebin.com/C9zpvQMR
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by xPoyraz** [comment]
error persists in the latest version

**Comment by Zrips** [comment]
Should be resolved with next CMILib update
