### ISSUE TITLE
[!] Infinity CMI HOLOGRAM

### ISSUE THREAD

**Issue by smscentras** [Zrips/CMI#8566]
### Description of Issue

Edit hologram(change something inside, in example - height) in Holograms.yml and reload it after with /cmi reload
Result:
![hologram](https://github.com/Zrips/CMI/assets/130366229/55157727-9edd-4e8e-9137-b834d2bd89c9)

### Version Information

```shell
CMILib1.4.6.0
CMI-9.7.0.0

```

### Errors

```shell
There is no errors
```

### Relevant Plugins

Vault 1.7.3-CMI

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update
