### ISSUE TITLE
ISSUE: can't interact with commandblocks

### ISSUE THREAD

**Issue by Xardas88** [Zrips/CMI#857]
**Description of issue or feature request:**
My staff (with OP permission) can't interact with commandblocks everytime they log-in the server.
If i deop and op them again they are able to use it until they disconnect.
When they connect it happens all over again.

**ERROR:**
No error

**MY CONFIG:**
https://pastebin.com/gwatEGt7

**Cmi Version:** 
8.0.11.0
**Server:** 
Spigot 1.13.1-R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment]
well this has Nothing to do with CMI.

you Need to be OP and you Need to be Gamemode 1 to have Access to them.
normaly CMI does not Interact with the Commandsblocks. 

Try to unload CMI and u may see you would have the same issues like now.

**Comment by Xardas88** [comment]
I tried to deactivate every plugin, one by one, but the problem appeared only when CMI was activated.

**Comment by CloudeLecaw** [comment]
Ok that is crazzy.
Well u tried it today on my Testserver. 
Spigot 1.13.1
CMI 8.0.12.0
PEX
oped me
Set me to gm1
Gave me a commandblock
Tried to use it...
Worked.. 

Sorry i cant reproduce this :(

**Comment by Xardas88** [comment]
I've tested with only CMI and the problem persists

**Comment by Xardas88** [comment]
Ok I think is the database.
I'm delete myself with /cmi removeuser uuid
log in and finally I can interact with commandblock
