### ISSUE TITLE
Hope to be authorized

### ISSUE THREAD

**Issue by LDS-XiaoYe** [Zrips/CMI#8573]
I am a CMI user. This plugin is awesome. I'd like to introduce it on KLPBBS(https://klpbbs.com), a Minecraft forum established in China. I won't provide the source file of plugin, only spigotmc link and the introduction of this plugin.

I hope to be authorized by you. Thank you.

**Comment by Zrips** [comment]
Hey, it's all good as long as you don't spread actual plugins file(s)
