### ISSUE TITLE
Kit command doesn't disable

### ISSUE THREAD

**Issue by P5ina** [Zrips/CMI#8575]
### Description of Issue

If you set `kits` to false in `Modules.yml` command `/kits` still be available in tabcompletion. If you use it, it opens up a gui menu with no kits.

### Version Information

```shell
Версия плагина CMI: 9.7.0.2 SqLite
CMILib: 1.4.6.1
Версия сервера: Paper(462) 1.20.4-R0.1-5NAPSHOT+
СМІ Экономика: Disabled СМІ Чат: Enabled
Модули -> 57 включено 2 отключено: votifier, kits
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
