### ISSUE TITLE
[BottledExp] give command can lead to dupe

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#8578]
### Description of Issue

Hello, when you try give command to yourselves like this it says you cannot give XP yourselves, BUT when you remove 1 letter from your name it gives you infinite XP & you can dupe with it

Try this:
/bottle give PLAYERNAME 20000 (for example Zrips)
-> Doesn't work, right?

And now try:
/bottle give PLAYERNAM 20000 (for example Zrip)
-> It works & doesn't even remove your XP

### Version Information

```shell
not related to cmi
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update
