### ISSUE TITLE
Server crash (com.Zrips.CMI.commands.list.baltop.perform)

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#858]
I have quite frequent server crashes
What notices me is that CMI baltop is often among the error lines. Is it possible that CMI is causing an error? Would you care to investigate?

2 Errors in this file: https://pastebin.com/gCcsj2Mu

Happens with all the cmi versions so far for the past weeks

**Comment by Morphiee** [comment]
This is happening to us as well... We have disabled the command for now.. I hope to see this resolved ASAP.

Also we are using SQlite.

**Comment by cdmvirt** [comment]
I can also confirm this on our server!

**Comment by arturek1666** [comment]
I already report that there, no point of duplicating the issue:
https://github.com/Zrips/CMI/issues/821

**Comment by Zrips** [comment]
Will make additional changes and will post new version today.

**Comment by Zrips** [comment]
This should be ok with 8.0.13.0 version.
