### ISSUE TITLE
Teleportation bugs with newest version

### ISSUE THREAD

**Issue by MedvedEE** [Zrips/CMI#8582]
### Description of Issue

In the newest version, 9.7.0.2, when people try to /spawn, nothing happens. They are not teleported anywhere. Also, with some warps, to warp there, you now need to write /tpbypass, even though there is nothing dangerous.

These work on 9.6.11.2. 
I also noticed, that the user, who has all permissions (LP *), can do /spawn and teleport to spawn. But when a normal user does /spawn, there is no error or whatsoever and the console is also clean.

### Version Information

```shell
https://imgur.com/a/EGTpmB9 Problem happens on newest verison (9.7.0.2)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Stoniasawsome** [comment]
i have the same issue, i downgraded back to previous versions and it works fine

**Comment by Zrips** [comment]
Should be resolved with next update
