### ISSUE TITLE
Chat Formats / Group Formats

### ISSUE THREAD

**Issue by Kalasky** [Zrips/CMI#859]
**Group Formats Not Displaying in Chat:**

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
    GroupFormat:
    '1': '&8{DISPLAYNAME} &8&l> &a{MESSAGE}'
    '2': '{prefix_vault}&f{displayName}&7 > &r{message}'
    '3': '{prefix_vault}&f{displayName}&8 > &r{message}'
#####################################
```

**Cmi Version (using`/cmi version`):** 
8.0.11.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper Spigot
**Server Version (using `/ver`):** 
Paper(297) 1.13.1-R0.1-SNAPSHOT

**Comment by astomnll** [comment]
what file is this in?
