### ISSUE TITLE
Homes set above the roof of the nether always teleport to y128

### ISSUE THREAD

**Issue by ArZorMC** [Zrips/CMI#8593]
### Description of Issue

When teleporting to a home set higher than y=128 in the nether a player will always be sent to the y=128 with the same x and y coordinates even if that puts them inside of other blocks

### Version Information

```shell
--------------------------------------------------
CMI: 9.7.0.2 SqLite
CMILib: 1.4.6.1 
Server: Paper(459) 1.20.4-R0.1-SNAPSHOT-
CMI economy: Disabled CMI Chat: Enabled 
Modules -> 52 enabled 7 disabled: tablist, playerCombat, votifier, afk, headDrop, vanish, playerChatTag
--------------------------------------------------
```

### Errors

```shell
None
```

### Relevant Config Sections

```yaml
N/A
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update
