### ISSUE TITLE
wrong math calculation of numerical usermeta values with decimal dots when increment or value is a negative number

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8598]
### Description of Issue
When the usermeta is saved with a negative numerical value with a decimal dot and/or the increment is a negative number with a decimal dot, then the resulted math calulation become wrong. in result a wrong value is saved in the usermeta.

Here some experiments to reproduce
```
1st test with some math calculations starting with a testvalue of 1.0:
cmi usermeta Cloude_Lecaw add testtest 1.0            ->  1.0    OK 
cmi usermeta Cloude_Lecaw increment testest 2.0       ->  3      OK
cmi usermeta Cloude_Lecaw increment testest -0.8      ->  2.2    OK
cmi usermeta Cloude_Lecaw increment testest -4.4      -> -2.4    NOT OK (should be -2.2  -> 2.2 (+)- 4.4 = -2.2)
cmi usermeta Cloude_Lecaw increment testest -2.5      -> -4.5    NOT OK (should be -4.9  -> -2.4 (+)- 2.5 = -4.9)
cmi usermeta Cloude_Lecaw increment testest 3.0       -> -1.0    NOT OK (should be -1.5  -> -4.5 + 3.0 = -1.5)

2nd short test with a math calculation starting with a testvalue of -0.3:
cmi usermeta Cloude_Lecaw add testtest -0.3           -> -0.3    OK 
cmi usermeta Cloude_Lecaw increment testest 2.4       ->  2.4    NOT OK (should be 2.1  -> -0.3 + 2.4 = 2.1)

3rd short test with a math calculation starting with a testvalue of 6.3:
cmi usermeta Cloude_Lecaw add testtest 6.3            ->  6.3    OK 
cmi usermeta Cloude_Lecaw increment testest -2.5      ->  3.5    NOT OK (should be 3.8  -> 6.2 (+)- 2.5 = 3.8)
```

here the command results in a picture of the test i wrote above
![image](https://github.com/Zrips/CMI/assets/12080017/ed533fd8-bf5d-41d7-bb85-97ddc731cbb5)

### Version Information
![image](https://github.com/Zrips/CMI/assets/12080017/94c5f071-7ea7-489a-b055-6630f14bdc0b)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
