### ISSUE TITLE
Random Teleportations

### ISSUE THREAD

**Issue by VISION6969** [Zrips/CMI#8600]
There is random teleportation in CMI which works flawlessly but there isnt permissions for specific world like 
For nether teleportation there is no permission 
if i give a player cmi.command.rt he can teleport to any world 
it wouuld be great to have permission wise world random teleports.

**Comment by SonnenPingu** [comment]
You can simply say, world xyz not.
Directly in the configs.
if you use Luckperms, you can set the world via the editor, but I don't know if CMI adheres to this.

**Comment by VISION6969** [comment]
bruh, luckperms cant achieve what i am trying to say. i believe i already told you that on discord 
cmi.command.rt already gives permission to all the world teleport
./rt world 
/rt world_nether
/rt world_the_end 
cmi.command.rt gives permissions for all of these 
i want it seprate like cmi.command.rt.world

**Comment by CloudeLecaw** [comment]
![Snag_d72238](https://github.com/Zrips/CMI/assets/12080017/f2f3c197-b1b6-47f9-9b29-12a08dd5791c)

Move it to discussion its no issues.

**Comment by CloudeLecaw** [comment]
> bruh, luckperms cant achieve what i am trying to say. i believe i already told you that on discord cmi.command.rt already gives permission to all the world teleport ./rt world /rt world_nether /rt world_the_end cmi.command.rt gives permissions for all of these i want it seprate like cmi.command.rt.world

by the way.  you might know you can create a custom alias that checks for $1 (arg1) after it called it it. and your free to do with it in the checks what you like in each world.

**Comment by Zrips** [comment]
Will add some extra options for random teleportations with next update. But as CloudeLecaw mentioned here, suggestions should go into discussion section.
