### ISSUE TITLE
underscores in Playergames are removed in Holograms

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8601]
### Description of Issue
If your show playernames with _ in name all the _ in their names got parsed with a space instead of the _ in cmi holograms
![image](https://github.com/Zrips/CMI/assets/12080017/54bba85b-ab34-4490-9a91-f27cd79f87cd)

### Version Information
![image](https://github.com/Zrips/CMI/assets/12080017/94c5f071-7ea7-489a-b055-6630f14bdc0b)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
