### ISSUE TITLE
Failed to load worth 296 wheat in 1.12.2

### ISSUE THREAD

**Issue by djacks6278** [Zrips/CMI#861]
**Description of issue or feature request:**

[02:49:42 INFO]: [CMI] Failed to load worth for: 296

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[02:49:42 INFO]: [CMI] Failed to load worth for: 296
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
worth.yml 296 is set

 296: 20.00

```

**Cmi Version (using`/cmi version`):** 

--------------------------------------------------
CMI plugin version: 8.0.13.0
Server version: Paper(1562) 1.12.2-R0.1-SNAPSHOT
Vault version: 1.7.1-b91(CMIEInjector)
--------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 

PaperSpigot

**Server Version (using `/ver`):** 

This server is running Paper 
version git-Paper-1562 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Good catch, will be fixed with next build.
