### ISSUE TITLE
decimal bug aggain with wrong money format???

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#862]
in relation to https://github.com/Zrips/CMI/issues/833
we still have this bug and now even the moneyformat does not help anymore :(

![image](https://user-images.githubusercontent.com/12080017/46104943-015f0780-c1d5-11e8-80f3-a9f090caa606.png)

tab:
![image](https://user-images.githubusercontent.com/12080017/46104971-18055e80-c1d5-11e8-8835-91ef8781bba1.png)

/cmi money
![image](https://user-images.githubusercontent.com/12080017/46105046-42571c00-c1d5-11e8-9f75-f21666a70e3f.png)

config:
```
  MoneyFormat: '###.###,00'
  # Replaces to western format where decimals are separated by , and thousands by . In example 1,000,000.00 changes to 1.000.000,00
  SwitchPlaces: true
```

may u can aspect i dont habve 2000.4 ... i have 2000.40 and it should be shown 

related to my format as 2.000,40

**Now the crazzy thing to fix it:**
  MoneyFormat: '###,###.00'
and it works all fine....
![image](https://user-images.githubusercontent.com/12080017/46105233-d5905180-c1d5-11e8-9e84-59af40107c29.png)
![image](https://user-images.githubusercontent.com/12080017/46105258-e3de6d80-c1d5-11e8-9bda-4e01b3c91669.png)

```
  # Format used for displaying money
  MoneyFormat: '###,###.00'
  # Replaces to western format where decimals are separated by , and thousands by . In example 1,000,000.00 changes to 1.000.000,00
  SwitchPlaces: true
```

so to work correct use the "false" money format and set the switch to true...
ok i got this.. so i am not allowed to change , and . in moneyformar anymore right?
was it wanted that way? :3

**Comment by Zrips** [comment]
@CloudeLecaw 
First of, there is specific format when determining decimals and thousands, so you have to keep that same format, always. 
Which economy system are you using? As this will only address CMI Economy format and in case you have another one which goes throw vault, then CMI will use Vault money format.

**Comment by x1p** [comment]
`
  # Format used for displaying money
  MoneyFormat: '###,##0.##'
  # Replaces to western format where decimals are separated by , and thousands by . In example 1,000,000.00 changes to 1.000.000,00
  SwitchPlaces: true
`
This works for me

**Comment by Zrips** [comment]
@x1p 
## will show decimals if there is any none zero ones, while 00 will always show 2 decimals even tho they are zero. You can mix and make something like 0# to show atleast one decimal and second one when needed.

**Comment by x1p** [comment]
Then it would be #0, but this does not work. Then it jumps back to 5.0.
```
  MoneyFormat: '###,##0.#0'
  SwitchPlaces: true
```

**Comment by CloudeLecaw** [comment]
well it seems to be solved <3
Thank you for all the work
