### ISSUE TITLE
Weather system not working? Command blocks broken? Please help!

### ISSUE THREAD

**Issue by jakeroy** [Zrips/CMI#864]
1.

/weather (anything) just displays (map) --> sunny for next (time)

I've disabled and enabled weather with worldguard. I've even removed worldguard, enabled weather in multiverse. And i can't set it to rain, toggle downfall nothing. I can't seem to have natural rain. Only thing that works is /pweather.

2.

Command blocks don't seem to work

It's enabled in my server.properties. And i've even tried /CMI:tp  @p (location).

7.9.1.9 (downgraded from newest version because i thought it'd fix it)

Spigot 1.12.2

**Comment by Zrips** [comment]
1. Can be issue with your personal weather setting. If you have pweather set to rainy or sunny, then adjusting weather with /weather will not have noticeable effect
What output do you have with /weather before using /weather sun/rain and after that?
2. CMI in general doesn't control command block behavior. Command block commands only work with vanilla commands, if we are talking about variables. If you want clickable block or intractable one, then use /cm ic command, or if you want some area to perform commands, you can use portal feature to create area of effect thingy

**Comment by jakeroy** [comment]
> 1. Can be issue with your personal weather setting. If you have pweather set to rainy or sunny, then adjusting weather with /weather will not have noticeable effect
>    What output do you have with /weather before using /weather sun/rain and after that?
> 2. CMI in general doesn't control command block behavior. Command block commands only work with vanilla commands, if we are talking about variables. If you want clickable block or intractable one, then use /cm ic command, or if you want some area to perform commands, you can use portal feature to create area of effect thingy

1.
I have thought of the pweather possibly being the problem. However i asked other friends on my server and it shows up for them. And ive even asked them to all do /pweather reset. The ouput is all the same ---> /weather just comes up with (world) --> sunny for the next (time)

2.
Oh true, i didnt think about using that feature. Thanks
