### ISSUE TITLE
CMI headDrop being completly ignored and using CMILibs 

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#8642]
### Description of Issue

I have been using the headdrop system in CMI for years, at some point in a recent update, all Lore stopped working in head drops, I found out the lore is instead comign from CMIlib message files and completly ignoring the `CustomHeads.yml` settings in CMI.

Modules
`headDrop: true`

CustomHeads.yml
```
useDefaultHeadLore: true
# Default lore used when head doesnt have defined head lore set
defaultHeadLore:
- '&fKilled by &a[playerName]'
- ''
- '&8⚑&o Mob Drop Treasure'
- ''
- '&f&lRARITY'
- '&a▌ ✪'
- ''
- '&f&lHOW TO OBTAIN HEAD'
- '&a▌ Kill Mobs!'
- ```

### Version Information

```shell
[15:05:14] [Server thread/INFO]: --------------------------------------------------
[15:05:14] [Server thread/INFO]: CMI: 9.7.0.4 Velocity CMIB  MySQL-> 9.7.0.6
[15:05:14] [Server thread/INFO]: CMILib: 1.4.6.1 -> 1.4.6.2
[15:05:14] [Server thread/INFO]: Server: Purpur(1632) 1.18.2-R0.1-SNAPSHOT-
[15:05:14] [Server thread/INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[15:05:14] [Server thread/INFO]: Modules -> 36 enabled 23 disabled: spawnerProximity, hpBossBar, customMessages, mirror, tablist, moneyCheque, skin, anvilRenameColor, noTarget, elytraBoost, dynamicSigns, playerChatTag, elytraLaunch, durabilityLoss, flightCharge, disabledEnchants, worldLimits, votifier, shulkerBackpack, attachedCommands, spawnerCharge, namePlates, homeInteractions
[15:05:14] [Server thread/INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by THEjpcello** [comment]
**mob heads:**

![Screenshot 2024-04-16 001327](https://github.com/Zrips/CMI/assets/133015548/c3a07a04-7ec8-426b-b43a-c92b8d0f583b)
old head named

![image](https://github.com/Zrips/CMI/assets/133015548/744543c4-0445-4a81-9d5d-59078f3c1a13)
new head name

![image](https://github.com/Zrips/CMI/assets/133015548/bde3b1e8-a0c5-43f1-80e1-7b58db8497ae)
mined with a piston seems to be the same format as it was back then when heads were mined with pistons



![image](https://github.com/Zrips/CMI/assets/133015548/95ab6063-9ba4-45c9-90b1-0f36bb8223ba)
this is how the heads look like when they drop after killing the mob (with the usual lore)

![image](https://github.com/Zrips/CMI/assets/133015548/e04c42a9-7a0b-4028-8811-1f86430a3f38)
also the one with lore changes to the new format after mining it



**player heads:**

![image](https://github.com/Zrips/CMI/assets/133015548/629d272f-0544-4dab-b521-6f004058e678)
old format

![image](https://github.com/Zrips/CMI/assets/133015548/694f1286-4fb7-4ba2-84bf-5f00333c6e29)
new format

**Comment by Zrips** [comment]
@TomLewis 
Check CMILib config file and try disabling these options
```
Heads:
  # When processing head item stack we will apply owners name instead of letting game client to use its own
  # This will change 'Zrips's head' to 'Head of Zrips'
  PlayerName: false
  # When processing head item stack we will apply monsters name instead of letting game client to use its own
  # This will change 'Zrips's head' to 'Head of Chicken' in case custom skin is applyed to it
  MobName: false
```

**Comment by Zrips** [comment]
Some changes will come with next CMI and CMILib updates
