### ISSUE TITLE
CMI 8.0.13.0 - /home alias not working

### ISSUE THREAD

**Issue by DeadIntermediate** [Zrips/CMI#865]
**Description of issue or feature request:**
I type ```/home``` and got in game a messgae: ```An internal error occurred while attempting to perform this command.```.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## https://pastebin.com/x4dxeUQr ##
####################
```

**Cmi Version (using`/cmi version`):** 
https://pastebin.com/GqNsNyD3

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):**
Doesn't show version for Spigot anymore. Looks like CMI took over that.

**Comment by Zrips** [comment]
Would be nice to see that error log

**Comment by x1p** [comment]
I believe it's in the description
`https://pastebin.com/x4dxeUQr`

**Comment by DeadIntermediate** [comment]
Yup, sorry.

**Comment by Zrips** [comment]
@DeadIntermediate 
Issue with homes in none existing worlds. Will add method to inform that location is not accessible as world no longer exists.
