### ISSUE TITLE
Jailed Players Take No Damage

### ISSUE THREAD

**Issue by TylorTurner** [Zrips/CMI#8654]
### Description of Issue

When damage is turned off in jail the player still does not take damage. 
Here is the player jailed not taking any damage
https://streamable.com/4uytgb
Here is the player unjailed and taking damage in the same area
https://streamable.com/qcaxrs

![image](https://github.com/Zrips/CMI/assets/133236597/b13a2c60-5fe2-4859-b335-853af1d102ca)

### Version Information

```shell
9.7.0.6
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Barpadzik** [comment]
Update your CMI and CMILib and check again

**Comment by TylorTurner** [comment]
> Update your CMI and CMILib and check again

Yes this is still an issue, It has existed since I originally purchased CMI.

**Comment by Zrips** [comment]
Should get a fix with next update
