### ISSUE TITLE
Multiverse Unload / Load breaks /cmi back & homes

### ISSUE THREAD

**Issue by Kirrasio** [Zrips/CMI#8657]
### Description of Issue

When unloading and reloading in a multiverse world, /cmi back becomes unusable with no feedback. I was trying to make an auto load and unload feature so that each world loads and unloads on players leaving and loading on players going to the world. Everything else works.

I'd be able to do a work around if the World, X, Y, Z were separate from one another. IE: %cmi_user_backloc[World]% %cmi_user_backloc[X]% %cmi_user_backloc[Y]% %cmi_user_backloc[Z]% <- which would be usable in the command to teleport with either cmi or worldguard. 

Thank you so much for your time <3

### Version Information

```shell
Cmi: 9.7.1.1
Lib: 1.4.6.3
Multiverse: 4.3.2-SNAPSHOT-b870
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Kirrasio** [comment]
Just noticed that homes also break when loading and unloading multiverse worlds.

**Comment by Zrips** [comment]
Should be fixed with next update
