### ISSUE TITLE
Elevator Teleport Problem

### ISSUE THREAD

**Issue by rockit7** [Zrips/CMI#8666]
### Description of Issue

When you place a mushroom Stem block under a [Elevator] with [*] sign you can't teleport as "Can't find suitable location" . Replace the Mushroom Stem with an Oak Log as an example, and it works fine.
![2024-04-28_15 32 00](https://github.com/Zrips/CMI/assets/76574795/ad5b771e-7174-4f85-9f7f-47e7ddc0a083)
![2024-04-28_15 32 26](https://github.com/Zrips/CMI/assets/76574795/e3fe7cd7-8e8c-4626-8831-300048101d18)

### Version Information

```shell
CMI 9.7.2.0
CMILIB 1.4.7.1
SERVER: Purpur 2174 1.20.4
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will make some changes relating to teleport location detection, tho full blocks like stem and logs should not have any difference when it comes to location detection part of the code. If issue persists with next update let me know. And if issue persists, check console for any error messages in case something fails.
