### ISSUE TITLE
v. 9.7.2.1 doesn't load properly on 1.8

### ISSUE THREAD

**Issue by Henriiig** [Zrips/CMI#8668]
### Description of Issue

As the title says

### Version Information

```shell
9.7.2.1 cant type the command because it is not loading

Yes, I am using java 17
```

### Errors

```shell
https://pastebin.com/dGqrgrSs
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
New version is out which should resolve your issue
