### ISSUE TITLE
Jail respawns player at Server Spawn?

### ISSUE THREAD

**Issue by TylorTurner** [Zrips/CMI#8670]
### Description of Issue

Jail respawns dead players at /setspawn
Instead I believe it should be respawning the player inside the jail. 
here is a video showing it. I apologize if I set it up wrong. 
https://streamable.com/mohr4m

### Version Information

```shell
9.7.2.2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update

**Comment by TylorTurner** [comment]
> Should be fixed with next update

This is not fixed with the newest update. Unless their is something I am required to do on the jail?
