### ISSUE TITLE
CMI Takes over spigots/other plugins /version

### ISSUE THREAD

**Issue by DeadIntermediate** [Zrips/CMI#868]
So, I am not sure if there is a way revert back. But when I type /version to get spigots version and see if I am behind any version. Also this applies to other plugins. So if I want to see what version I am running on a specific plugin, looks like CMI takes over please. 

Please help and thank you. 

**Cmi Version (using`/cmi version`):** 
8.0.14.0

**Server Type (Spigot/Paperspigot/etc):** 
Spigot 1.13.1

**Server Version (using `/ver`):** 
CMI Takes over, so can't see the whole thing

**Comment by Zrips** [comment]
Go to alias.yml file, disable this alias, reload server and you are good to go.
