### ISSUE TITLE
Время на сервере 

### ISSUE THREAD

**Issue by EdsonGreen** [Zrips/CMI#8707]
### Description of Issue

Как убрать /cmi autorealtime с сервера, время идёт как в реальном времени, убрать это невозможно, пробовал разные команды...

### Version Information

```shell
9.7.2.5
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
You can use `/cmi time autorealtime stop` which will disable auto real time updates in your world
