### ISSUE TITLE
Spawning/teleporting block down

### ISSUE THREAD

**Issue by M4rtyn4** [Zrips/CMI#871]
Hello. 
I get players reporting they glitch and after tpa/home/spawn or when respawn they are like stuck in the block they supose to be standing on. Sometimes when there is nothing below they fall down through it.
People rage quit because of this. 
They sometimes get stuck - like frozen for couple seconds after they use any kind of tp. 

CMI 8.0.16.0

Spigot 1.13.1-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Could you provide example of where exactly they have been teleported too? And do you have cmi.safeteleport set for players?

**Comment by M4rtyn4** [comment]
Its /spawn, /home, /tpa everything which changes your location really
Yes they have cmi.safeteleport permission set

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LogGits** [comment]
We have made some major improvements to teleportation handling recently. Are you still experiencing this issue on the latest cmi build?

**Comment by M4rtyn4** [comment]
I asked players and they've not experienced it for a while now. We also switched to Paper some time ago.
Thank you. You are the best! ❤️
