### ISSUE TITLE
effect is missing or got reenamed?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8712]
### Description of Issue
when i enter `/cmi effect Cloude_Lecaw strength 60 2` nothing happens but when i enter
`/cmi effect Cloude_Lecaw strength 60 2`  it tells me i got instead_damge 2 for 60 secounds (see screenshot)
Well strength is no part of the TAB-Complete while increases_stange is..
Well an other user in discord told me he got slow effect....? well...
At least increase_damge does not exist anymore? but strength does?.... im confused to this..

![10-05-2024_19-55-40](https://github.com/Zrips/CMI/assets/12080017/a30a18fa-bda0-4337-be58-6ceab7dc971a)

![10-05-2024_20-10-09](https://github.com/Zrips/CMI/assets/12080017/58bd06f6-f279-4f4f-9ffe-310acd6efd2d)

### Version Information
![10-05-2024_20-05-07](https://github.com/Zrips/CMI/assets/12080017/d22b17f5-3e14-4269-a5cd-e96e3cf756e3)

### Agreements
- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Some mix up, will fix feedback message to show appropriate name. It should be strength. Increase_damage is the name used internally by server, but just as a name for Strength enchant type. There are quite few things which have different names than it should have had, quite few of those got changed with 1.20.5+ server update to return appropriate value based on its actual variable name internally.
