### ISSUE TITLE
/armorstand unremovable option: "Open clone picker"

### ISSUE THREAD

**Issue by alfredcort** [Zrips/CMI#8713]
### Description of Issue

When i give the permission node 'cmi.command.armorstand' to a group, that player is able to run the /armorstand command but they don't have any options in the GUI, other than the "Open clone picker" piece of paper. The player has no other permission that has to do with armorstand.

I've asked in the CMI support chat via Discord and i haven't got a response. I asked a member that posted a similar question in 2023 but they didn't get a response either apparently.

I want to remove this "Open clone picker" paper completely, is there a way?

### Version Information

```shell
CMI: 9.7.2.6 SqLite-> 9.7.2.5
CMILib: 1.4.7.8 
Server: Purpur(2176) 1.20.4-R0.1-SNAPSHOT+
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 58 enabled 1 disabled: tablist
```

### Relevant Plugins

CMI or CMILib

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
All the icons in UI gets filled up based on players access to specific permission nodes. Remaining paper is a bug, will make a fix to properly hide remaining buttons (position button is visible too) with next update to resolve this
