### ISSUE TITLE
Sit command bug

### ISSUE THREAD

**Issue by RVSkeLe** [Zrips/CMI#8714]
### Description of Issue

As reported before, /sit commands are buggy, and allow players to go through blocks. I can replicate the bug less frequently, but still happens way too many times.
Proofs: https://youtu.be/iEAT1YkNdow

### Version Information

```shell
Versione di CMI: 9.7.2.5 SqLite
CMILib: 1.4.7.8 
Server: Purpur(2176) 1.20.4-R0.1-SNAPSHOT+
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 58 enabled 1 disabled: votifier
```

### Errors

```shell
//
```

### Relevant Config Sections

```yaml
//
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Noticed some weird inconsistencies to where player ends up when he sits which can vary by 0.06 block height on Y axis which could have been creating this issue. Will make small adjustments to make it more consistent at which height player is being teleported. If issue persists, let me know.
