### ISSUE TITLE
Teleports with warmups do not work on 9.7.2.6

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#8716]
### Description of Issue

Teleports **with warmups** do not work on CMI `9.7.2.6`, while `9.7.2.5` works fine. All players who have warmup bypasses do not experience such an issue.

### Version Information

```shell
CMI: 9.7.2.6
CMILib: 1.4.7.8
Server: Purpur(2111) 1.20.4-R0.1-SNAPSHOT
```

### Errors

```shell
N/A
```

### Relevant Config Sections

```yaml
N/A
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Upgrade CMI / CMIlib, latest CMI has Fix for commands with warmups failing to process it properly

**Comment by Zrips** [comment]
Fixed with latest builds
