### ISSUE TITLE
/sit armor stand editing.

### ISSUE THREAD

**Issue by Morphiee** [Zrips/CMI#872]
**Cmi Version (using`/cmi version`):** 
8.0.15.0

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
git-Paper-305 (MC 1.13.1)

**bug:**
Players can edit the invisible armor stands that are created when another player uses `/sit`

**Comment by Zrips** [comment]
Will be fixed with next update
