### ISSUE TITLE
CMILib1.4.7.6 and later versions cannot be clicked normally, such as digging blocks! Left-clicking or right-clicking will display the PrimaryPoint and SecondaryPoint prompts

### ISSUE THREAD

**Issue by polang233** [Zrips/CMI#8721]
### Description of Issue

For example, in the environment of paper1.12.2, the right and left keys in the game are invalid, and clicking will bring up the selection effect realized by the default shovel. I tried to delete all plug-ins, leaving only cmi and cmilib to troubleshoot the problem, and finally came to the conclusion that CMILib version 1.4.7.5 was normal before
![QQ截图20240512192425](https://github.com/Zrips/CMI/assets/104189797/edbcf011-6c43-4c06-aed1-9e160decb89c)
![QQ截图20240512192509](https://github.com/Zrips/CMI/assets/104189797/a00c384d-1c03-4da1-9fb8-43745c00b9f8)

### Version Information

```shell
[19:34:54 INFO]: --------------------------------------------------
[19:34:54 INFO]: CMI版本:9.7.2.6 SqLite
[19:34:54 INFO]: CMILib版本:1.4.7.8
[19:34:54 INFO]: 服务器版本:Paper(1620) 1.12.2-R0.1-SNAPSHOT-
[19:34:54 INFO]: CMI经济系统:启用CMI聊天系统:禁用
[19:34:54 INFO]: 模块 -> 58 已启用 1 已禁用:votifier
[19:34:54 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
Default
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Cannot reproduce this on 1.20.4 paper. Maybe issues with 1.12.2 ?

**Comment by polang233** [comment]
> Cannot reproduce this on 1.20.4 paper. Maybe issues with 1.12.2 ?

It is estimated that only 1.12.2 appears, and I have only tested 1.12.2, and it is based on the default configuration without any changes

**Comment by SonnenPingu** [comment]
Take a look at which tool is stored for the portal creation. I had that once because there was no tool entered there. 

Change it most sensibly to wooden_shovel

**Comment by polang233** [comment]
> Take a look at which tool is stored for the portal creation. I had that once because there was no tool entered there.
> 
> Change it most sensibly to wooden_shovel

Selection:
  # Tool id to use for selection actions
  Tool: wooden_shovel

This is my configuration, and it is obvious that the default configuration has not been changed, which is wooden_shovel. I tried to change it to stone , but the result was still the same. Clicking on anything with the left and right keys is a selection tool
