### ISSUE TITLE
Holograms Being Derpy Again

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#8733]
### Description of Issue

Holograms no longer load when a player approaches, at any distance. Using /cmi reload has varying results, as does turning the holo off and on again or changing between new method and old, but even reloading or fixing by turning it on and off only keeps it fixed as long as the player is in range. Going out of range and returning and the holo is gone again and does not reappear without another reload, etc.

No errors in console but from your Discord seems to be a general consensus.

### Version Information

```shell
CMI plugin version: 9.7.2.9 Velocity CMIB  SqLite
CMILib: 1.4.7.9 
Server: Paper(496) 1.20.4-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 57 enabled 2 disabled: ranks, skin
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Give me example of hologram (from holograms.yml file) which misbehaves for you

**Comment by Zrips** [comment]
Nvm, reproduced this issue, it was a derpy bug, should be ok with next update
