### ISSUE TITLE
Failed to download file

### ISSUE THREAD

**Issue by illyrius666** [Zrips/CMI#8736]
### Description of Issue

"Failed to download file 'https://raw.githubusercontent.com/Zrips/CMILib/master/Translations/Locale_AU.yml' to folder 'plugins/CMILib/Translations/'."

### Version Information

```shell
16.05 10:08:41 [Server] [INFO] --------------------------------------------------
16.05 10:08:41 [Server] [INFO] CMI: 9.7.2.9 SqLite
16.05 10:08:41 [Server] [INFO] CMILib: 1.4.7.9 
16.05 10:08:41 [Server] [INFO] Server: Paper 1.20.6-R0.1-SNAPSHOT+
16.05 10:08:41 [Server] [INFO] CMI economy: Disabled CMI Chat: Enabled 
16.05 10:08:41 [Server] [INFO] Modules -> 44 enabled 15 disabled: cuffed, hpBossBar, mirror, launchPad, moneyCheque, portals, jail, elytraBoost, cmiPlaytime, elytraLaunch, kits, bossBarCompass, flightCharge, ranks, votifier
16.05 10:08:41 [Server] [INFO] --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next CMILib update
