### ISSUE TITLE
Add %cmi_user_balance_shortmoney% placeholder

### ISSUE THREAD

**Issue by Ricozaur** [Zrips/CMI#8746]
It would be optimal if you could add:
%cmi_user_balance_shortmoney% 
as a placeholder to display someones cash in shorted format.

Thanks in advance,
Ricozaur

**Comment by CloudeLecaw** [comment]
please move it to https://github.com/Zrips/CMI/discussions

**Comment by Ricozaur** [comment]
Alrighty, i moved it
