### ISSUE TITLE
Baltop Still has issues

### ISSUE THREAD

**Issue by cdmvirt** [Zrips/CMI#876]
/baltop is still messed up the organization is off, they are not ordered by amount some players with higher bal are put into lower rank. for example we have a player with 5K yet they are put between two other players with 48k and 11K they should be at a lower spot yet they are at #16

![image](https://user-images.githubusercontent.com/6846286/46262913-695b6980-c4c5-11e8-9de3-850e6087edb3.png)

**Cmi Version (using`/cmi version`):** 
8.0.16.0
**Server Type (Spigot/Paperspigot/etc):** 
papaer 1.13.1

**Comment by Zrips** [comment]
Will fix it.
