### ISSUE TITLE
CMI does not respond to Rcon commands

### ISSUE THREAD

**Issue by Vovacr** [Zrips/CMI#8760]
Hi, I am running two commands via rcon
I set the time on the server and issue coins through the CMI plugin
All commands from other plugins work, but the CMI plugin does not work. What could be wrong?
![IMG_7047](https://github.com/Zrips/CMI/assets/114768108/fdf76bad-a33d-46fe-8865-175f0fe84575)

![IMG_7048](https://github.com/Zrips/CMI/assets/114768108/00965f90-2248-4042-9a2e-d9874b0fc2ca)

**Comment by Zrips** [comment]
Make sure that AllowRconCommands is enabled in config file and update CMI to the latest version if you are somewhat out of date as we had some changes relating to RCon messages in recent updates which could help you out.
