### ISSUE TITLE
cannot change the nickname of some offline players.

### ISSUE THREAD

**Issue by Ecilpse** [Zrips/CMI#8764]
### Description of Issue

cannot change the nickname of some offline players.
it says "Can't find player with this name!", can changes player name when online.
Oddly, i can change offline player nickname even when it's offline, but only a few players are like this.

### Version Information

```shell
9.6.10.2
1.4.5.0
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Can you give example of user names and their nicknames where it works and a case where it doesn't?
