### ISSUE TITLE
crafting bug

### ISSUE THREAD

**Issue by WhiteProject1** [Zrips/CMI#8766]
### Description of Issue

https://github.com/Zrips/CMI/assets/103301275/e1620b24-82d7-470a-a1a9-b73494be670e

![image](https://github.com/Zrips/CMI/assets/103301275/a7d5339d-6dc9-405d-a4cd-21fa88fd03bb)

### Version Information

```shell
![image](https://github.com/Zrips/CMI/assets/103301275/a7d5339d-6dc9-405d-a4cd-21fa88fd03bb)
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
this is no bug.
yoi only can use ONE material in each crafting slot.

**Comment by Zrips** [comment]
@WhiteProject1 
As Cloude here pointed out, due to minecraft limitations you can only have single item per slot as ingredient independent how many you will put into custom recipe
