### ISSUE TITLE
[Bug] Error with deleing ICs

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#877]
We got an error with CMI today when trying to use an ic
`>[2K [03:09:32 INFO]: Blueeyestar issued server command: /cmi ic tag delete >[2K [03:09:32 ERROR]: null org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.17.0 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-f6a273b-5ee1c18] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-f6a273b-5ee1c18] at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[minecraft_server.jar:git-Spigot-f6a273b-5ee1c18] at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[minecraft_server.jar:git-Spigot-f6a273b-5ee1c18] at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[minecraft_server.jar:git-Spigot-f6a273b-5ee1c18] at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[minecraft_server.jar:git-Spigot-f6a273b-5ee1c18] at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-f6a273b-5ee1c18] at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-f6a273b-5ee1c18] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101] at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-f6a273b-5ee1c18] at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [minecraft_server.jar:git-Spigot-f6a273b-5ee1c18] at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-f6a273b-5ee1c18] at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-f6a273b-5ee1c18] at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-f6a273b-5ee1c18] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101] Caused by: java.lang.IllegalAccessError: com/Zrips/CMI/Modules/InteractiveCommand/InteractiveCommandManager$1 at com.Zrips.CMI.Modules.InteractiveCommand.InteractiveCommandManager.save(InteractiveCommandManager.java:218) ~[?:?] at com.Zrips.CMI.commands.list.ic.perform(ic.java:377) ~[?:?] at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:244) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-f6a273b-5ee1c18] ... 15 more
`
MC-Version 1.13.1
CMI-Version 8.0.17.0

**Comment by Zrips** [comment]
Is this constant issue or one time thing?

**Comment by CloudeLecaw** [comment]
wel until today it is a constant one :(

**Comment by Zrips** [comment]
Strange, cant really reproduce this issue. Are you still on 1.13.1 or maybe you updated to 1.13.2 and this issue is gone after normal full server restart?

**Comment by CloudeLecaw** [comment]
No er updated to 1.13.2 Since this we never had this kind of problem aggain.
 For the moment i cant reproduce this anymore. so i will close the ticket for now and may reopen it if the error may appears aggain. :)
