### ISSUE TITLE
Options placeholders

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#8772]
Hello, if we want to show the current state of some option from /options via the placeholder, is it possible currently? I cannot find the placeholder on the https://www.zrips.net/cmi/placeholders/, for example if I'd like to show if player is accepting teleport requests etc. the same way as it's done in /options under the State: Enabled/Disabled

**Comment by Zrips** [comment]
%cmi_user_toggle_[msg|pay|tp|compass|sospy|sispy|cospy|schest|autoflightrecharge|totem|shiftedit|tagsound|chatbubble]% – Outputs 1 or 0 if defined feature is toggled on or off
%cmi_user_togglename_[msg|pay|tp|compass|sospy|sispy|cospy|schest|autoflightrecharge|totem|shiftedit|tagsound|chatbubble]% – Outputs formatted True or False if defined feature is toggled on or off

**Comment by bobhenl** [comment]
OH, thanks! I didn't see it there, sorry
