### ISSUE TITLE
Is it possible to specify the page of the recipe? + show recipe to other player?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#8775]
Hello, in case we don't want to show all the recipes for some item, only some (for example if we have custom GUI & then want to open the specific recipe page), is it possible somehow?

I noticed that we can use -c, but we can't set there the specific custommodeldata, or can we? Or the page?

Like /recipe name -c:XXX or /recipe name -c 11 (or without -c, for the page)

Also it looks like that /recipe command doesn't support player argument, it's not currently possible to specify there player? I saw it's missing permission cmi.command.recipe.others, so it looks like the cmd doesn't support it

**Comment by bobhenl** [comment]
And can we open it to another player as well somehow, or it's not supported? @Zrips

**Comment by Zrips** [comment]
Added support for target players with current (9.7.3.0) update
