### ISSUE TITLE
CMI giveall console error

### ISSUE THREAD

**Issue by illyrius666** [Zrips/CMI#8779]
### Description of Issue

giveall is throwing error in console

### Version Information

```shell
25.05 16:11:52 [Server] [INFO] --------------------------------------------------
25.05 16:11:52 [Server] [INFO] CMI: 9.7.2.12 SqLite
25.05 16:11:52 [Server] [INFO] CMILib: 1.4.7.14 
25.05 16:11:52 [Server] [INFO] Server: Paper(95) 1.20.6-R0.1-SNAPSHOT+
25.05 16:11:52 [Server] [INFO] CMI economy: Disabled CMI Chat: Enabled 
25.05 16:11:52 [Server] [INFO] Modules -> 44 enabled 15 disabled: cuffed, hpBossBar, mirror, launchPad, moneyCheque, portals, jail, elytraBoost, cmiPlaytime, elytraLaunch, kits, bossBarCompass, flightCharge, ranks, votifier
25.05 16:11:52 [Server] [INFO] --------------------------------------------------
```

### Errors

```shell
https://mcpaste.io/4cd3d4e4efcc8e3e
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be mitigated with next CMILib update, tho for time being avoid using minecraft item tags as those are not being properly processed on 1.20.6 until future updates.
