### ISSUE TITLE
Error in 8.0.17?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#878]
We found many issues in the CMI 8.0.17 with some commands

the money economy was not giving items,
the time was not able to set
the sun was haning very often
and we aspect that other function not working too.

We changed back to 8.0.16 and now it works fine! :)
So is it possible to check the 8.0.17 for some errors or something like that?

On my own testserver it seems to work fine.

**Comment by Zrips** [comment]
What you mean with "money economy was not giving items"?
What feedback are you getting after using /day /night commands and performing /time /ptime commands? As /time and /ptime should be same if player doesn't have personal day time set for them. 
Again, what you mean by "the sun was haning very often"? Frozen in place? Could this be issue with sun animation?
I need a way to reproduce those issues before i can address them. Currently everything seems to work correctly.

**Comment by CloudeLecaw** [comment]
the time with /cmi time night was ok, but the night was like froozen
and it didnt changed to day, sometime a reloging helped.

we tried also These commands on signs and for ptime it was working with 8.0.16
with 8.0.16 the day Argument wasnt.

Well this happend on our Life Server...
On my own Tester all works fine with the 8.0.17 so i am not sure was is causing it on the Lifeserver.
