### ISSUE TITLE
Random skinsCache Error with CMILib 1.4.7.14

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#8787]
### Description of Issue

Getting this error spammed seemingly randomly, can't really reproduce it and doesn't seem to affect anything, but I also have the skins module disabled, if that makes a difference. https://gist.github.com/mercurialmusic/6331f96b701450dcb7d67d531fb01099

### Version Information

```shell
CMI plugin version: 9.7.2.12 Velocity CMIB  SqLite
CMILib: 1.4.7.14 
Server: Paper(496) 1.20.4-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 57 enabled 2 disabled: ranks, skin
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Looks like your  plugins/CMILib/skinsCache.yml file is misformatted. Would recommend to reset it by simply deleting it. This should be resolved with next CMILib update, tho would still recommend to reset skinsCache.yml regardless.
