### ISSUE TITLE
[1.8.8] CMI Chat breaks MC chat

### ISSUE THREAD

**Issue by elythh** [Zrips/CMI#8793]
### Description of Issue

When installing CMI on my 1.8.8 Minecraft server, the chat is broken.
It doesn't matter if I enable or not chat formatting
![image](https://github.com/Zrips/CMI/assets/50964650/52bac150-cbd3-4e72-8faa-2b93056f33bf)

### Version Information

```shell
CMI: 9.7.2.12
CMILib: 1.4.7.15
Server: Spigot.1.8.8-R0-1-SNAPSHOT-
CMI Economy: Disabled CMI Chat: Disabled
```

### Errors

```shell
No error
```

### Relevant Config Sections

```yaml
Default config
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Make sure that you have ModifyChatFormat is disabled in chat.yml file. What chat plugin are you using for your general chat messages? As this should not happen with regular setup, so it looks to be 3rd party interference or compatibility issue
