### ISSUE TITLE
ShulkerBackpack module doesn't work when the shulker box is empty

### ISSUE THREAD

**Issue by Lia-LV** [Zrips/CMI#8799]
### Description of Issue

ShulkerBackpack module doesn't work when the shulker box is empty.
so I can't open empty shulker box with Shift + Right Click.

### Version Information

```shell
CMI: 9.7.2.12
CMILib: 1.4.6.14
Server: Paper(2218) 1.20.6-R0.1-SNAPSHOT+
and votifier module is disabled.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
can you try if you need to place and break it once before...it works?

i renember this old bug from older versions..

**Comment by Lia-LV** [comment]
> can you try if you need to place and break it once before...it works?
> 
> i renember this old bug from older versions..

It's the same after place and break it and using again. If the shulker box is empty, it never works.

**Comment by Zrips** [comment]
@Lia-LV 
Your provided server version doesn't match actual version, highest one for 1.20.6 is #131 while you provided #2218. Could you provide output from /cmi version?

**Comment by Lia-LV** [comment]
> @Lia-LV Your provided server version doesn't match actual version, highest one for 1.20.6 is #131 while you provided #2218. Could you provide output from /cmi version?

CMI: 9.7.2.12 SqLite
CMILib: 1.4.7.14
Server: Paper(2218) 1.20.6-R0.1-SNAPSHOT+
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
Modules -> 58 enabled 1 disabled: votifier

This is output from /cmi version, 2218 maybe cuz I'm using fork of paper, purpur.

**Comment by Zrips** [comment]
Ok, found an issue, should be resolved with next update

**Comment by CloudeLecaw** [comment]
> > @Lia-LV Your provided server version doesn't match actual version, highest one for 1.20.6 is #131 while you provided #2218. Could you provide output from /cmi version?
> 
> CMI: 9.7.2.12 SqLite CMILib: 1.4.7.14 Server: Paper(2218) 1.20.6-R0.1-SNAPSHOT+ CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled Modules -> 58 enabled 1 disabled: votifier
> 
> This is output from /cmi version, 2218 maybe cuz I'm using fork of paper, purpur.

awww not very nice if pupurs tells about hisself to be paper. its a fork that not is offical supported by cmi. so asume some bugs.

well lucky you zrips seems to found something so it might work on pupur too woth next Update.
