### ISSUE TITLE
Request: Bungee sync

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#88]
Is it possible to have the warps/spawns sync across some bungee servers? I don't see why mysql works, but cmi setup on a second bungee server doesn't see the cmi warps, so if I do /warp on server 2 it doesn't see the warps set on server1.

**Comment by mrfloris** [comment]
I see this feature being requested on almost a weekly basis on the CMI Discord server. Better Bungee support (economy, kits, warps, being the same on all connected servers).
