### ISSUE TITLE
Checkaccount feature

### ISSUE THREAD

**Issue by ConsoleGods** [Zrips/CMI#8812]
![2024-06-06_22-06](https://github.com/Zrips/CMI/assets/27227109/464a4758-34f4-4ba6-9a89-36c9a93bdf17)
When a players alt is banned  or muted it should show the username in red or a different color

**Comment by CloudeLecaw** [comment]
you might missed the information in the Text box

![image](https://github.com/Zrips/CMI/assets/12080017/e0cec05c-2721-4626-b9b8-766ac5469899)
So pls lose this one and open a disussion for the request
https://github.com/Zrips/CMI/discussions
