### ISSUE TITLE
Do custom alias check: support multiple words?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#8824]
Hello, do custom alias support multiple words in comparison, for example like this?
```
  rankduration:
    Cmds:
    - msg Renzotom %javascript_group_expiry%
    - check:%javascript_group_expiry%==Permanent rank! asConsole! cmi msg [playerName] !&c&lRanks &8» &fYour rank is &cPermanent&f!
```

Seems that it's not working even when it's returned, I tried to put around "" but it didn't work neither, so just want to check if it's intended to work or not

**Comment by CloudeLecaw** [comment]
the answer is no it does not.
