### ISSUE TITLE
Bug Report | Glow issue when you join vanished

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#883]
If you set your glow color and relog in vanish the glow color will change to white.

Could you also add a "update glow on login" option in the config. After the version change old players with cmi data dont have their glow until I update it.

**Cmi Version (using`/cmi version`):** 
CMI8.0.17.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.13.1

**Comment by Zrips** [comment]
Will fix it
