### ISSUE TITLE
SELECTION VISUALIZER (ok'd by floris to put here)

### ISSUE THREAD

**Issue by MikeHollisJr2021** [Zrips/CMI#8834]
### Description of Issue

Selection Visualizer does not correctly recognize the presence of Grief Defender, I talked with bloodmc of Grief Defender who said the file it checks doesn't get used anymore, he doesn't know why you're reading the file but said the file you're supposed to be looking for is global.yml not global.conf, apparently the string is referencing the incorrect file name.

I have touched global.conf but it gets replaced with global.yml on every boot.

`
7|MC - Survival  | [16:12:59 INFO]: [SV] CMI plugin was found!
7|MC - Survival  | [16:12:59 INFO]: Cant find GriefDefender config.yml file, function will be disabled
7|MC - Survival  | [16:12:59 INFO]: [SV] Jobs plugin was found!
7|MC - Survival  | [16:12:59 INFO]: [SV] WorldEdit plugin was found!
`

### Version Information

```shell
`
7|MC - Survival  | [16:34:09 INFO]: --------------------------------------------------
7|MC - Survival  | [16:34:09 INFO]: CMI: 9.7.3.2 BungeeCord CMIB  MySQL-> 9.7.3.3
7|MC - Survival  | [16:34:09 INFO]: CMILib: 1.4.7.16
7|MC - Survival  | [16:34:09 INFO]: Server: Paper(138) 1.20.6-R0.1-SNAPSHOT-
7|MC - Survival  | [16:34:09 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
7|MC - Survival  | [16:34:09 INFO]: Modules -> 63 enabled 1 disabled: votifier
7|MC - Survival  | [16:34:09 INFO]: --------------------------------------------------
`
```

### Relevant Plugins

GriefDefender 2.5.9

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with 3.3.0.3 version
