### ISSUE TITLE
/cmi reload will reset its annotation to english

### ISSUE THREAD

**Issue by RUYSUE** [Zrips/CMI#8835]
when i changed pre-translated file, save and performed /cmi reload, the whole annotation was reset to default, resulting my double checking config.yml. although this does not reset my setting, it still confused me a lot.
why? 
i wonder if i can disable this.
# before reload
<img width="586" alt="image" src="https://github.com/Zrips/CMI/assets/164722481/ed876026-c623-4664-96cd-858b881c541e">

# after reload
<img width="584" alt="image" src="https://github.com/Zrips/CMI/assets/164722481/09034c85-c79a-4914-849b-7c081679840e">

**Comment by mrfloris** [comment]
Correct, these are not the locale file, and when the expected values aren't detected it probably rebuilds it, trying to 'fix' the yaml file. I suspect that's what's going on here. Translations that you can translate are in the /translations/ folder

**Comment by polang233** [comment]
这个没办法，我以前也尝试过把注释改成中文，改一半时，重载发现都没了
所以我现在都是留一份改过的来对照，而不是直接改服务器里的config

**Comment by Zrips** [comment]
Comment/annotations will always be in English as its just additional information for the user. Any changes to that will be reset on each reload.
