### ISSUE TITLE
Stacked Items that normaly not Stackable are shows wong on inv command

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8837]
### Description of Issue
Whem a player has a normaly not stackable item that you stack by a plugin then the amount is shows as 1 if you lookat his inventory

![15-06-2024_21-06-31](https://github.com/Zrips/CMI/assets/12080017/d136f4b5-4c32-4abb-ae5a-eec36d3123be)
Here you see the bottles of an other player. Normaly he has 16 of each. i asked him and he said "yes their are 16 in each slot"
i gave him an other 16..and see.. its shows wrong as one bottle..

### Version Information
![15-06-2024_21-10-09](https://github.com/Zrips/CMI/assets/12080017/17b5f3a7-3482-44d6-a359-9786dc48fb50).3

### Relevant Plugins
PotionStacker_0.0.8

### Agreements
- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Not familiar with PotionStacker, but CMI inv command will show items as they are on server side, no actual modification of data will happen. If item stack if properly marked as one having over stack limit then it will show up like one. For example 
![image](https://github.com/Zrips/CMI/assets/10416201/2a64ec4f-9654-4c73-83e5-38fd8a6e400f)
So my suspicion is that PotionStacker sends custom packets which makes it look like you have more than you actually do. In this case can't do much without some specialized direct integration with this plugin which would ton of work for tiny gains for a plugin which does all of this in wrong way.

**Comment by CloudeLecaw** [comment]
i see. well the plugin actually does not work anymore for 1.21 so might it worth to suggest the option to stack same potions as player from inventory? would be a good feature, since the spigot site does only offer a handfull of potionsstacker that allow stacking without a command...
