### ISSUE TITLE
Bug Report | /sell gui price preview issue

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#884]
When you place stacked items in the sell gui the worth doesn't update, acts as if it was a single item.
https://gyazo.com/192f22971d0faa76e3e885825073ecec

**Cmi Version (using`/cmi version`):** 
CMI8.0.17.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.13.1

**Comment by Zrips** [comment]
Will fix it with next update
