### ISSUE TITLE
CMI Doesn't Handle All Death Messages

### ISSUE THREAD

**Issue by JaydenJinx** [Zrips/CMI#8844]
### Description of Issue

![Screenshot 2024-06-18 at 10 23 10 PM](https://github.com/Zrips/CMI/assets/37884702/18d94ca6-9f9a-4703-84fc-92bc9c416896)
![Screenshot 2024-06-18 at 10 25 05 PM](https://github.com/Zrips/CMI/assets/37884702/3a6f42bd-ed3e-4d9b-96fe-9d6e74fac071)

Some death messages are sent in chat as the vanilla messages are, without any formatting applied. 

### Version Information

```shell
22:27:36

--------------------------------------------------
CMI plugin version: 9.7.4.0 SqLite
CMILib: 1.5.0.1
Server: Paper(6) 1.21-R0.1-SNAPSHOT+
CMI economy: Disabled CMI Chat: Enabled
Modules -> 43 enabled 23 disabled: spawnerProximity, cuffed, mirror, armorEffects, moneyCheque, noTarget, jail, elytraBoost, elytraLaunch, kits, bossBarCompass, coloredArmor, flightCharge, disabledEnchants, worldLimits, ranks, votifier, cooldown, headDrop, spawnerCharge, warmup, timedCommands, totemBehavior
--------------------------------------------------

This server is running Paper version 1.21-6-master@126f6d7 (2024-06-18T20:03:56Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
```

### Errors

```shell
There are no errors.
```

### Relevant Config Sections

```yaml
Death Messages Locale_EN.yml: https://pastebin.com/raw/Tb82XckM
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update
