### ISSUE TITLE
Setting the point at home - the bed does not work correctly

### ISSUE THREAD

**Issue by kitovoi111** [Zrips/CMI#8846]
### Description of Issue

When I slept on the bed and set the home point, when I write /home it teleports me to the bed and I constantly get into it. Make me teleport +1 block higher to the bed or blocks next to it.

### Version Information

```shell
CMI 9.7.4.0
CMILib 1.5..0.1
Folia 1.20.6-R0.1
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by kitovoi111** [comment]
In short, the home Interaction Bed works very poorly. I get teleported to a bed and get stuck in it when I type /home , I would like you to make +1 block for /home when the bed is selected or use the closest available blocks next to the bed

**Comment by Zrips** [comment]
Should be fixed with next version
