### ISSUE TITLE
Portal particles resetting to default on /cmi reload or server restart

### ISSUE THREAD

**Issue by tomhmagic** [Zrips/CMI#8847]
### Description of Issue

Portal particles reset to the default redstone when doing /cmi reload or server restart.

### Version Information

```shell
9.7.4.0
```

### Errors

```shell
N/A
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Need output from /cmi version to have better idea with your setup

**Comment by Zrips** [comment]
Have you retested this with latest CMI and CMILib versions? As this should have been fixed with it and currently can't reproduce it.
If issue persists, could you provide example of particle name you tried to set too which got a reset

**Comment by tomhmagic** [comment]
I thought I am on the latest no? Any particle other than dust resets to dust. I have just changed in the Portals.yml then done a cmi reload and seems to have staid, not due a restart until tomorrow so I can see if it persisists

**Comment by Zrips** [comment]
You are on latest, was just asking in case you encountered this issue with slightly older version and reported this issue just now. And, you can use ingame portal editor to get correct particle names, as it can reset to default dust one in case you entered wrong name directly into portals.yml

**Comment by tomhmagic** [comment]
Oh yea it's been happening for a bit, but didn't have time to report. I get it resetting to default when using the in game editor, on older editions even editing the file was resetting but this version is fine.

**Comment by Zrips** [comment]
So does it work correctly now for you with ingame editor and direct file modifications while using latest versions?
