### ISSUE TITLE
Bug Report | basePrice: line issue in EN file

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#885]
You cant put a 2nd line for the worth value format in the EN file under worth "basePrice". Tried using \n and yml line spacing, when I did the plugin had errors.

**Cmi Version (using`/cmi version`):** 
CMI8.0.17.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.13.1

**Comment by Zrips** [comment]
Should work with \n in next update.

**Comment by SirGoldman-git** [comment]
unfortunately this was not fixed:
01.10 20:14:25 [Server] INFO Expected whitespace to end one argument, but found trailing data
01.10 20:14:25 [Server] INFO ...erEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"$2"}]}}}]<--[HERE]


basePrice: '&f[itemName]&e(&7[amount]&e) -> &6$[price] \n&e--------------------------------------'
