### ISSUE TITLE
Bug with the /seen and vanish 

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#8852]
### Description of Issue

Hi there,
I've just noticed an annoying bug with the command `/cmi seen (Player)`.

### Explanation:
When a staff goes into vanish, the time displayed in /seen is wrong.

### Example:
A staff member has been online for **1h 11min**. 
It goes into vanish and is then marked as having been offline for **1h 13min**.

### Solution:
Make it so that when a staff goes into vanish, it looks as if it is disconnecting, i.e. display "**offline since 1sec**".

Translated with DeepL.com (free version)

### Version Information

```shell
CMI: 9.7.4.0 Velocity CMIB MySQL
CMILib: 1.5.0.1
Server: Purpur(2176) 1.20.4-R0.1-SNAPSHOT-
CMI economy: Activée Vault: 1.7.3-CMI CMI Chat: Désactivée
Modules -> 33 enabled 33 disabled: spawnerProximity, cuffed, mirror, tablist, armorEffects, moneyCheque, elytraBoost, elytraLaunch, bossBarCompass, chatBubble, votifier, headDrop, spawnerCharge, vanish, homeInteractions, hpBossBar, anvilRenameColor, jail, spawners, nightSpeedup, dynamicSigns, playerChatTag, durabilityLoss, deathMessages, teleportWith, disabledEnchants, worldLimitsElytra, worldLimits, ranks, sitAnimation, silentChest, warmup, totemBehavior
```

### Errors

```shell
No errors.
```

### Relevant Config Sections

```yaml
I haven't tested this bug with CMI's "Vanish" module, as I use PremiumVanish to manage vanish on my server.
```

### Relevant Plugins

PremiumVanish 2.9.10

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Issue is that we don't really have reference point from when player went into vanish mode if you are using 3rd party vanish plugin, so our best bet is to just use players last login time. While using CMI vanish we are properly indicating offline time to be from the moment player enters vanish mode. As inconvenient it is, not much we can do about it at this point as it would need direct support for all vanish plugins out there, which is really not a good solution to have.
