### ISSUE TITLE
[Folia] CMI Teleports a player to a soul sand block and the player is rolled back by an anti-cheat

### ISSUE THREAD

**Issue by kitovoi111** [Zrips/CMI#8856]
### Description of Issue

Stand on a block of soul sand. Another player must write /tpa to you or you teleport him to yourself with a command /tp, the player will appear at the bottom of the sand of souls. (my anti-cheat rolls the player back)

### Version Information

```shell
CMI 9.7.4.1
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by kitovoi111** [comment]
CMI TELEPORT COMMAND

![image](https://github.com/Zrips/CMI/assets/147491823/6b32776b-869a-435e-b376-ca03bcf65842)

**Comment by kitovoi111** [comment]
/minecraft:teleport command
![image](https://github.com/Zrips/CMI/assets/147491823/62253f48-07ff-4341-ae10-4f02695ced63)

**Comment by kitovoi111** [comment]
The soil plowed with a shovel also teleports incorrectly
![image](https://github.com/Zrips/CMI/assets/147491823/6abf0f07-30da-4f30-b651-098234cc9ee3)

**Comment by Zrips** [comment]
Will be fixed with next update
