### ISSUE TITLE
[Folia] Chat Bubbles completely broken and the chat does not move with the player

### ISSUE THREAD

**Issue by kitovoi111** [Zrips/CMI#8857]
### Description of Issue

When a player writes a message, a message appears above his head, but it does not move behind him and remains in place

### Version Information

```shell
CMI 9.7.4.1
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
