### ISSUE TITLE
Suggestion - a Nice Symbol for IC empty lines

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#886]
Today i was Looking at an IC Example

![image](https://user-images.githubusercontent.com/12080017/46284463-358d4c00-c578-11e8-9e1b-6b13990afab9.png)

Well you see the place between the X and the UP aand DOWn button is empty… normlay u would Need to click the empty place to fill in a line..

it would be nice to have something in an empty line that showns you "You can interact there"

**Comment by Zrips** [comment]
Will add extra locale line to fill up empty lines like that one for convenience sake
