### ISSUE TITLE
Need help please 

### ISSUE THREAD

**Issue by LucasHervieu** [Zrips/CMI#8860]
I have some questions:
- how can i desactivate the message join and quit in vanish on and off ?
- how can I limit the number of sethomes for my players (it doesn't work: cmi.command.sethome.1) ? 
- it's possible to activate the tpa or any other commands for a period of time and then deactivate it or activated only each hour for example? 
- 
thank you for taking the time to help me :)

**Comment by Zrips** [comment]
1. There is **/cmi vanishedit** command which allows you to adjust all of the settings relating to vanish, including join/leave messages
2. **cmi.command.sethome.[anypositivenumber]** would be used to set players max home count. Keep in mind that biggest number will be used if player has multiple homes and OP players could bypass this limit. You can use **/cmi haspermission Zrips cmi.command.sethome.** to check min max values of this permission node, just to double check if player has access to more homes than he should. On top of this you can run things like **/cmi haspermission Zrips cmi.command.sethome.bypasslimit** to double check if player isint bypassing limits that way
3. Activation of commands for specific periods of times isint really possible at the moment, atleast not with CMI, but you could use your permission plugin to achieve that as most of them will have timed permissions
