### ISSUE TITLE
[Suggestion] - optional worldvar for time command

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#887]
i tried to creat a Testinteracting command coubles to a sime..

Test:
  Location:
  - ==: org.bukkit.Location
    world: NSD
    x: 482.0
    y: 74.0
    z: 90.0
    pitch: 0.0
    yaw: 0.0
  Commands:
  - asConsole! cmi time night NSD
  - asConsole! cmi gm Cloude_Lecaw 1
  SignLines:
  - Test
  - ' '
  - ' '
  - ' '
  Public: false

Well the gm1 Setting works.. but i cant get the time to night in my choosen world..because the console does not know in what world to eecute the command??
if u have more then one world normaly that itme command sets the time for the world you are in.
It would be nice to have a worldvar to be able to arange the time in other Worlds. + an Allvar if you want to Change the time in all Worlds.

**cmi time (time/state) <world/all>** 

if the worldname is not given then it chooses the world you are in now.

**Comment by LogGits** [comment]
This works for me, `/cmi time day <worldname>`.

**Comment by CloudeLecaw** [comment]
LogGifts?

...time has a worldvar???
have your tried this command from consone while being in an other world?....

**Comment by CloudeLecaw** [comment]
i am so sorry.... i havent seen that the all var is allready inside,,,im so sorry @.@
