### ISSUE TITLE
/repair all bug

### ISSUE THREAD

**Issue by Ryzz3nn** [Zrips/CMI#8870]
### Description of Issue

In the latest update, version 1.20.6, users have observed that the 'repair all' command is not functioning as expected. Specifically, it seems that the command fails to fully restore items to their maximum durability, leaving them partially repaired instead. This issue has been noted by multiple players and may require further investigation and a potential patch to resolve.
![image](https://github.com/Zrips/CMI/assets/47952472/513e697b-cafb-47fa-a162-aa3c0ded3467)

### Version Information

```shell
![image](https://github.com/Zrips/CMI/assets/47952472/daebe8c5-ef1c-4183-9d47-cb66f2bede4c)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Use F3+H key combination to enable advanced tooltips, and check items durability state, if it doesn't indicate any durability, then its at its max and that non full durability could be just a visual thing for your server setup specifically, if it shows something like 
![image](https://github.com/Zrips/CMI/assets/10416201/a0d077a3-f09d-4b36-8377-d3b21d8f4ab3) then there might be an issue
