### ISSUE TITLE
Teleport Command Waystones Issue

### ISSUE THREAD

**Issue by andersuk** [Zrips/CMI#8871]
### Description of Issue

The datapack Kawamoods Waystones uses the /tp command to operate. CMI takes over that command and prevents the datapack from accessing it. In something like Essentials, this is a matter of configuration, you simply open up the /tp command to all again. Previous users of the datapack have disabled the /tp alias in the alias.yml file and this has resolved the issue. This is apparently not the case with the latest version. 

### Version Information

```shell
CMI: 9.7.4.0 SQLite 9.7.4.1
CMILib 1.5.01
Server Paper(15) 1.21-R0.1-SNAPSHOT+
CMI Economy: Disabled CMI Chat: Disabled
Modules: 65 Enabled 1 Disabled: votifier

Server Host: Shockbyte
```

### Errors

```shell
No errors are reporting, because it is simply that the datapack is denied the use of the /tp command
```

### Relevant Config Sections

```yaml
The only config section relevant to teleporting relates to homes.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
There wasn't really any changes relating to alias command handling in recent updates. Keep in mind that disabling alias for /tp in alias.yml, for it to take full effect you will need to perform full server restart. After that's done CMI will no longer take any actions for that command
