### ISSUE TITLE
cmi openbook dont work

### ISSUE THREAD

**Issue by PabloKateee** [Zrips/CMI#8874]
### Description of Issue

just realized that cmi openbook no longer works

### Version Information

```shell
CMI Plugin Version 9.7.4.1
CMILib: 1.5.0.3
Server: Paper(2250) 1.21-RO-SNAPSHOT
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Dreadonator** [comment]
Yup its broken :(

**Comment by Zrips** [comment]
Should be fixed with next build
