### ISSUE TITLE
clickable  holograms not work properly

### ISSUE THREAD

**Issue by capubara** [Zrips/CMI#8877]
### Description of Issue

commands are not run in holograms when players click on it.

### Version Information

```shell
CMI:9.7.4.1
CMILIB:1.5.0.3
```

### Relevant Config Sections

```yaml
https://mclo.gs/uwceeAm i don't know can it help you or not(
```

### Relevant Plugins

VAULT 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Could you test this with CMI only? As you have quite few plugins with quite few error messages all over the place.

**Comment by capubara** [comment]
yeap, i have checked it

**Comment by Zrips** [comment]
What type of server are you running?

**Comment by capubara** [comment]
like a software?

**Comment by Zrips** [comment]
Going over your logs it looks like you are running some Forge fork as Ketting, which could be the cause of this issue you are having, as modded servers can be quite aways from what plugin was made to be able to handle.

**Comment by capubara** [comment]
other version of CMI like 9.6.10.6 works fine

**Comment by capubara** [comment]
due to this Ketting is not a cause of the problem

**Comment by capubara** [comment]
no

**Comment by Zrips** [comment]
Doing some testing, at the moment can't reproduce this issue on this server version of yours
![image](https://github.com/Zrips/CMI/assets/10416201/d9a063fa-b8f3-4fd0-bf16-c8c25bdbc429)
If you click F3+B, do you see white bounding box being drawn and following you around when you look at hologram? And are you using old or new display format for holograms?

**Comment by capubara** [comment]
![2024-07-03_16 18 40](https://github.com/Zrips/CMI/assets/161635835/7eccb2d6-a2e9-48ab-9ee1-8b921f1cb434)
this is with old version of CMI(9.6.10.6)

**Comment by capubara** [comment]
with 9.7.4.2
![2024-07-03_16 28 32](https://github.com/Zrips/CMI/assets/161635835/38599861-1aa6-4394-b47a-1d1f3567b597)

**Comment by Zrips** [comment]
Does that bounding box follow you around when you targeting hologram?
Additionally you could try setting hologram line to something like `<T>{#gray>}Line{#edward<}</T><H>{#edward>}&lHovered line{#gray<}</H>` to check if actual hovering is being detected.
And additionally try running some simple command when you clicking on that hologram, in case there is an issue with command processing. Some basic `cmi heal [playerName]` would do the trick
