### ISSUE TITLE
Issues cancelling chat messages

### ISSUE THREAD

**Issue by TheRealGriind** [Zrips/CMI#8878]
### Description of Issue

I use a separate plugin for punishments & staffchat (NetworkManager). This plugin has a dependancy called SignedVelocity to make the functions work properly (I think it's what cancels the messages or smth) With CMI & or CMILib Installed & enabled, public messages would still appear after a short sub-second delay from sending the message to the public message being sent. When I disable the CMI & CMILib plugins outright the issue goes away, but it still persists if I only disable the chat formatting setting.
(this issue is present on all servers on my bungeecord/velocity network)

![image](https://github.com/Zrips/CMI/assets/44880679/34fb7e29-6d5b-4c80-9e45-7839a5830a48)
![image](https://github.com/Zrips/CMI/assets/44880679/2a4c8d27-5c49-4a8d-aa40-4b7524e5debd)

### Version Information

```shell
CMI: 9.7.4.1 Velocity CMIB SqLite (had the same issues before installing CMIB)
CMILib: 1.5.0.3
Server: Paper 1.20.6-R0.1-SNAPSHOT-
CMI Modified Vault Installed.
```

### Errors

```shell
No errors shown in console either on startup or throughout affected functions (typing, etc)
```

### Relevant Config Sections

```yaml
Unsure what section would be relevant, lmk
```

### Relevant Plugins

Vault v1.7.3-CMI, NetworkManager v2.15.6, SignedVelocity v1.2.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
It's a question how chat message is being canceled, as it needs to remove recipients more than just attempting to cancel event itself. Hard to say what exactly is going on without knowing what plugin you are using and what its doing.
