### ISSUE TITLE
heads command on 1.21 does not work

### ISSUE THREAD

**Issue by jtwebhomer** [Zrips/CMI#8882]
### Description of Issue

when i do /cmi head playernamehere it doesnt give me a head of that player just the default steve head 

### Version Information

```shell
9.7.4.1
```

### Errors

```shell
no error in console
```

### Relevant Config Sections

```yaml
not applicable to this issue
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Retested and it looks to be working. Try changing your client launcher, if you are not using official one, then try using that one. If issue repeats, then I will need information reported from **/cmi version** to have better idea of what's going on

**Comment by Zrips** [comment]
Some additional changes will come with next CMILib which should help out with heads handling.
