### ISSUE TITLE
/armoreffect does not apply effects to armor

### ISSUE THREAD

**Issue by VimaMT** [Zrips/CMI#8885]
### Description of Issue

I have tried multiple types of items: leather helmets, gold helmets, iron helmets.
Command while holding item: /armoreffect NightVision
The effect is not added.
There are no error messages in the console for this.

### Version Information

```shell
CMI 9.7.4.2 SqlLite-> 9.7.4.1
CMILib 1.5.0.4
Server: Paper(2233) 1.20.6-R0.1-SNAPSHOT+
CMI economy:Enabled Vault: 1.7.3-CMI CMI Chat:Disabled
Modules -> 64 enabled 2 disabled: tablist, votifier

I am actually using the last version of Purpur, not Paper.
I am actually using version 1.7.4 of CMI's Vault, not 1.7.3 as the list suggests.
```

### Errors

```shell
No errors were seen
```

### Relevant Plugins

Vault-1.7.4

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by VimaMT** [comment]
I am using no custom enchants.

**Comment by alfredcort** [comment]
Can confirm this is the case for me too, it worked when I was on 1.20.4. The armor pieces that had an effect working before now don't apply the effect to the player, nor can we create new armor effects.

**Comment by Zrips** [comment]
Will be fixed with next build
