### ISSUE TITLE
Playerhead not showing name

### ISSUE THREAD

**Issue by alfredcort** [Zrips/CMI#8894]
### Description of Issue

Before 1.21, a player showed the name "xxx's head" as the title. Now, it only shows "'s head".
command: 'head %player_name% %player_name%'
<img width="132" alt="Screenshot 2024-07-03 at 15 48 08" src="https://github.com/Zrips/CMI/assets/72607588/8e8fed79-6ba6-41bd-af24-63c1761997a6">

### Version Information

```shell
CMI: 9.7.4.2 SqLite
CMILib: 1.5.0.4 
Server: Paper(2252) 1.21-R0.1-SNAPSHOT+
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 65 enabled 1 disabled: tablist
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next CMILib update
