### ISSUE TITLE
Applying enchants to Mace through /enchant applies wrong enchants

### ISSUE THREAD

**Issue by MaHl111** [Zrips/CMI#8914]
### Description of Issue

As stated in title, trying to enchant mace through `/enchant` applies wrong enchants to the mace. 
Lore shows these enchants:
- `density` -> `swift_sneak`
- `breach` -> `thorns`
- `wind_burst` -> `unbreaking`

`/iteminfo` shows the correct enchants, however, their mechanics are not applied. They can, however be applied using `enchanted_book` like **Density 5**. Applying **Density 5** in that way, results in `Protection_environmental -> 5` in `/iteminfo`, enchant works:
![obrázok](https://github.com/Zrips/CMI/assets/48538049/d317058c-9b84-4643-8c4f-0acd414c0812)
Reversing the process and trying to apply `/enchant Protectionenvironmental` to the item results in **Protection 1** and:
![obrázok](https://github.com/Zrips/CMI/assets/48538049/492a5164-4c12-48ec-95f7-64444853b5d0)

### Version Information

```shell
CMI: 9.7.4.4 SqLite
CMILib: 1.5.0.2 -> 1.5.0.5
Server: Paper(44) 1.21-R0.1-SNAPSHOT+
CMI economy: Disabled CMIChat: Disabled
Modules -> 65 enabled 1 disabled: votifier
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Rexmen1** [comment]
looks like enchants were not updated correctly for 1.21

**Comment by Rexmen1** [comment]
same issue on my server..

**Comment by MaHl111** [comment]
> looks like enchants were not updated correctly for 1.21

Neither was `/disableenchants`, but I think it was of minor importance, so it would be eventually fixed

**Comment by VISION6969** [comment]
I agree, enchants are not updated for 1.21 properly

**Comment by MaHl111** [comment]
**Update:** As of **CMILib 1.5.0.6** (Thanks @CloudeLecaw for pointing out the version in separate issue) `/enchant` applies proper enchants to the Mace and they work correctly. There is still minor bug with `/iteminfo` and incorrect text of the applied enchant, example for Density:
![obrázok](https://github.com/Zrips/CMI/assets/48538049/80bf4823-e012-439b-bdd0-ad45692f5bf6)

These however, are separate issues.

**Comment by CloudeLecaw** [comment]
wait...1.21 has new weapon? Mace?

**Comment by CloudeLecaw** [comment]
> looks like enchants were not updated correctly for 1.21

jup new weapon, new enchants. 
correct. 

currently cmi was made to run on 1.21, that doesnt mean it added all its new stuff.

**Comment by MaHl111** [comment]
> > looks like enchants were not updated correctly for 1.21
> 
> jup new weapon, new enchants. correct.
> 
> currently cmi was made to run on 1.21, that doesnt mean it added all its new stuff.
> 
> oh and yes the iteminfo shows wrong enchant names.. wasnt that fixed?

Nope, or at least, it wasn't in public release, I've updated CMILib to the latest version which fixed enchant applying and mechanics, but the image taken was with the latest version. So `iteminfo` just shows different enchant but it's still incorrect. They are however synced with `enchant` because they show the same name when applying.
