### ISSUE TITLE
[Request] Command Dye rainbow armor

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/CMI#892]
Hello, I know that's such a stupid thing, but if the add /cmi dye command was used to coloerd the leather armor, it would be possible to add the rainbow color option, basically it would be that the armor itself had a random color ... for example /cmi dye rainbow. .. Thanks

**Comment by Zrips** [comment]
Do you want it to change colors autocratically in specific intervals? Or simply dye it in random color? As we do have **/cmi dye random** command already.

**Comment by TheTopCz** [comment]
https://youtu.be/m_NBAhdX13c

**Comment by Zrips** [comment]
Next update
