### ISSUE TITLE
The original block interaction is not disabled when the player uses the interact command.

### ISSUE THREAD

**Issue by XXY233** [Zrips/CMI#8920]
### Description of Issue

If the furnace or workbench is bound to interactive commands, the player will first open the gui of the function block and then execute the interactive command. I think the original block interaction should be canceled.

### Version Information

```shell
--------------------------------------------------
CMI plugin version: 9.7.4.4 SqLite
CMILib: 1.5.0.6
Server: Paper(497) 1.20.4-R0.1-SNAPSHOT-
CMI economy: enable Vault: 1.7.3-CMI CMI Chat: enable
Modules -> 61 enabled 5 disabled: tablist, ranks, playerCombat, votifier,
--------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will add with next update
