### ISSUE TITLE
DeductOnFallMulti does not work when DamageOnFall is set to false.

### ISSUE THREAD

**Issue by XXY233** [Zrips/CMI#8921]
### Description of Issue

DeductOnFallMulti exists to punish players who evade fall damage. But if DamageOnFall is set to true, then the player will take damage and setting DeductOnFallMulti will not make sense. Instead, DeductOnFallMulti should work when DamageOnFall is set to false.

### Version Information

```shell
--------------------------------------------------
CMI plugin version: 9.7.4.4 SqLite
CMILib: 1.5.0.6
Server: Paper(497) 1.20.4-R0.1-SNAPSHOT-
CMI economy: enable Vault: 1.7.3-CMI CMI Chat: enable
Modules -> 61 enabled 5 disabled: tablist, ranks, playerCombat, votifier,
--------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Its an optional thing, you can always just set DeductOnFallMulti to 0 which will disable its functionality

**Comment by XXY233** [comment]
@Zrips  Sorry, my description may not be accurate. What I meant is that when DamageOnFall is set to false, setting DeductOnFallMulti to any number greater than 0 will have no effect. I don't want the player to take fall damage, but I want the player to lose flight charges.
