### ISSUE TITLE
Regarding the issue of the damage display limit on the BossBar

### ISSUE THREAD

**Issue by Probe4119** [Zrips/CMI#8922]
I checked the formula written in the `HpBarListener.class` via IDEA:
```java
"var6.setTitleOfBar(CMILC.BossBar_hpBar.getLocale(new Object[]{"[victim]", var12.getCustomName(), "[max]", (int)var7.getMaxHealth(), "[current]", var8, "[damage]", (double)((int)(var3 * 100.0)) / 100.0}));"
```

Can we change `(int)` to `(long)` or a formula that supports higher display numbers?
Because the display limit is locked at `2.147483647E7`, can it have a higher display number?

---

To modify the formula to support higher display numbers, you can replace `(int)` with `(long)` or use appropriate data types that can handle larger values.
This change should allow the values to be displayed correctly even if they exceed the limit of `2.147483647E7`.
![image](https://github.com/Zrips/CMI/assets/175127325/9397ee66-a31b-4b6b-9665-13ed0876e157)

**Comment by Zrips** [comment]
Will modify it to more properly process bigger numbers and more properly show them
