### ISSUE TITLE
[Request] Name in head player

### ISSUE THREAD

**Issue by minhthanh920** [Zrips/CMI#893]
show name in head player. config group,permission or anythings else
For examp : 
- player 1 with named : testplugin and has permission cmi.namedinhead.group1
-  config in group1 : %nametag% %displayname% %cmi_user_meta_tag%
- player 1 has %nametag% =  Dev , %displayname% = testplugin , %cmi_user_meta_tag% = Coffe is Free
Other players can see player 1 with new named is Dev testplugin Coffe is Free in that head player

**Comment by doitliketyler** [comment]
It wasn't exactly clear what you were asking for BUT I'm assuming this is about adding a name-tag before the players name in game with different group customization? If so then this would be great. I actually came here to request that myself.

**Comment by minhthanh920** [comment]
doitliketyler, u can check out here :
 https://www.spigotmc.org/resources/holomedals-donater-perk-reward-for-events-achievements-1-8-1-11-2.31223/
that plugin no longer update ,and hope it give Zrips come some ideals.

**Comment by doitliketyler** [comment]
Oh nice, yeah that's what I wanted but even better. Thanks for sharing.
