### ISSUE TITLE
/nick Does Not Obey the CMI Color Permissions When Using Hex Colors

### ISSUE THREAD

**Issue by Mikirae** [Zrips/CMI#8933]
### Description of Issue

/nick does not properly obey the coloring permissions when using hex colors. If you use a hex color, even with the cmi.command.colors.* set to false.
I'll include screenshots showing it to be bugged with &# hex colors, as well as the standard CMI {#} hex colors.
I'll also show that it does properly block Default Minecraft Color Codes
![image 1](https://github.com/user-attachments/assets/ee0544a0-7047-4c75-bef2-83273de71e26)
![image 1](https://github.com/user-attachments/assets/8ffab4bf-7175-4775-ba38-26db2b796e2e)
![image 1](https://github.com/user-attachments/assets/06c2aade-eaeb-4ddc-a364-e844d9e16f01)
![image 1](https://github.com/user-attachments/assets/fbf17dc9-bd43-490c-ae70-a87d37ce1f8c)
.

### Version Information

```shell
[22:38:28] [Server thread/INFO] [Console/]: CMI: 9.7.4.5 SqLite
[22:38:28] [Server thread/INFO] [Console/]: CMILib: 1.5.0.7
[22:38:28] [Server thread/INFO] [Console/]: Server: Arclight 1.16.5-R0.1-SNAPSHOT+
[22:38:28] [Server thread/INFO] [Console/]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
[22:38:28] [Server thread/INFO] [Console/]: Modules -> 45 enabled 21 disabled: spawnerProximity, cuffed, hpBossBar, tablist, armorstand, moneyCheque, afk, skin, spawners, kits, bossBarCompass, ranks, playerCombat, votifier, headDrop, spawnerCharge, silentChest, warmup, vanish, homeInteractions, totemBehavior
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
cmi.command.color is wrong.

take a look in Chat.yml

its

`cmi.colors.nickname.[colorName]`

**Comment by Mikirae** [comment]
I apparently stated it incorrectly in my description, but I provided
screenshots showing the actual permission node of cmi.colors.nickname.red
being false, yet still allowing it to go through.

**Comment by CloudeLecaw** [comment]
red = &c
darkred = &4

you changed it in your Screenshot toba darkred not a red..

**Comment by Mikirae** [comment]
I have quite literally shown the exact steps causing the issue in this
ticket. You can test it for yourself, and it will work. I have tested it on
live servers and test servers with a fresh setup. It works every single
time.
