### ISSUE TITLE
Server Shop Sign

### ISSUE THREAD

**Issue by BrandonShaunSutton** [Zrips/CMI#894]
CMI seems to realize that i am trying to use the essentails shop signs, but i am unable to make them work,
is there a way to create server shop signs, not for a chest shop, just a simple sign its self, layed out like:
[buy]
  32
Bread
$750

**Comment by CloudeLecaw** [comment]
Why simy dont use the Chestchop?
and no cmi does not have to relaise anything. your Essentials shop sign Needs to be able to relaise your used economy. normaly best why for this is using vault if the Plugin supports it

**Comment by CloudeLecaw** [comment]
https://github.com/Zrips/CMI/issues/260
