### ISSUE TITLE
Cooldown Command Error

### ISSUE THREAD

**Issue by PabloKateee** [Zrips/CMI#8942]
### Description of Issue

https://paste.jubyte.com/usorayonin.yaml

commands have no cooldown although i think i have entered everything correctly.

### Version Information

```shell
CMI Plugin 9.7.4.5
CMILib: 1.5.0.7
Server: Paper(2258) 1.21-R0.1-SNAPSHOT
```

### Errors

```shell
no errors
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by PabloKateee** [comment]
@Zrips do you have an idea or a solution ? :D have i made a mistake or does it generally not work?

SRY for Ping xD

**Comment by CloudeLecaw** [comment]
> ### Description of Issue
> https://paste.jubyte.com/usorayonin.yaml
> 
> commands have no cooldown although i think i have entered everything correctly.
> 
> ### Version Information
> ```shell
> CMI Plugin 9.7.4.5
> CMILib: 1.5.0.7
> Server: Paper(2258) 1.21-R0.1-SNAPSHOT
> ```
> 
> ### Errors
> ```shell
> no errors
> ```
> 
> ### Relevant Config Sections
> _No response_
> 
> ### Relevant Plugins
> _No response_
> 
> ### Agreements
> * [x]  My server is supported by CMI.
> * [x]  My version of CMI at the time of this report is up to date.
> * [x]  I have searched the github and asked around before making this report.

why dont use just the cooldown:time! feature if you allready use customalias ?

**Comment by PabloKateee** [comment]
it works nice xD thx haha
