### ISSUE TITLE
Bug on /cmi head

### ISSUE THREAD

**Issue by PabloKateee** [Zrips/CMI#8947]
### Description of Issue

if you create a player head with /cmi head, it says (head of ) Without name
However, it works with the mob head
![Unbenannt](https://github.com/user-attachments/assets/4fc4c6bc-311a-4ec9-afa1-90c845795356)

### Version Information

```shell
CMI Plugin Version: 9.7.4.5
CMILib: 1.5.0.7
Server: Paper(2258) 1.21-R0.1-SNAPSHOT
```

### Errors

```shell
no errors
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next CMILib update
