### ISSUE TITLE
Essentialsmigrated Home data incorrectly

### ISSUE THREAD

**Issue by HYDeath** [Zrips/CMI#8953]
### Description of Issue

After Essentialshomes migration, homes is not working, prompt: world does not exist.
![168116a776fae688a6f917cf1e83f3f1](https://github.com/user-attachments/assets/a1971a80-f4d7-432a-b0fa-c54a5a1abd6c)

After migration home database looks like this:
[a$-0%%9e9f319f-33e0-4db4-9a48-bcb3fece7009:18353.62:66.0:4221.7:30.72:65.16;dl$-0%%%b9f4bd01-464f-47f6-880d-a6872928b529:5658.47. 166.0:-507.55:90.0:120.41;b$-0%%9e9f319f-33e0-4db4-9a48-bcb3fece7009:38294.25:73.0:2610.33:13.65:155.7;c$-0%%9e9f319f-33e0-4db4- 9a48-bcb3fece7009:38294.14:73.0:2651.9:15.6:12.45](https://github.com/Zrips/CMI/issues/8953#issue-2413145726)

### Version Information

```shell
[17:38:40 INFO]: --------------------------------------------------
[17:38:40 INFO]: CMI 插件版本: 9.7.4.5 Unknown  SqLite
[17:38:40 INFO]: CMILib: 1.5.0.7
[17:38:40 INFO]: Server: Folia 1.20.4-R0.1-SNAPSHOT-
[17:38:40 INFO]: CMI economy: 启用 Vault: 1.7.3-CMI CMI Chat: 禁用
[17:38:40 INFO]: Modules ➦ 64 enabled 2 disabled: tablist, votifier
[17:38:40 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Have you modified your worlds? Like removed some which existed before? As this could have happen if home location was saved in a world which no longer exists and only record we have is its UUID which you can see it. In general this should be recognized and player should be teleported to that world, if world exists by this UUID
