### ISSUE TITLE
Broadcast "!"

### ISSUE THREAD

**Issue by geometrygames1029** [Zrips/CMI#8959]
### Description of Issue

Players can easily bypass the [Broadcast] prefix with an exclamation point

### Version Information

```shell
9.7.4.5
```

### Errors

```shell
Bypassing the [broadcast] prefix with a "!"
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Prefix would only be removed if player has access to cmi.command.broadcast.clean permission node. Recommended to avoid giving permission nodes with wild card to avoid accidental permission access they should not have too.
