### ISSUE TITLE
dupe bug

### ISSUE THREAD

**Issue by matteo00788** [Zrips/CMI#8962]
### Description of Issue

hi i'am here to warn you that there is a "dupe" with the /inv if you are like a staff lik an helper that you can do /inv you can do this think
[Uploading 20240714-2055-35.7546103.zip…]()

### Version Information

```shell
9.7.4.6
```

### Errors

```shell
no error
```

### Relevant Config Sections

```yaml
https://cdn.discordapp.com/attachments/1259559813436805232/1262172210315919410/20240714-2055-35.7546103.mp4?ex=6698ecb8&is=66979b38&hm=66825f19ff05f5ea03893160d3980952f68a35385053ef66341aace4f0d12ff7&
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by matteo00788** [comment]
https://discord.com/channels/@me/1063875542287400990/1262171773835935865

**Comment by Zrips** [comment]
Should be addressed with next build
