### ISSUE TITLE
You cannot kill an entity 

### ISSUE THREAD

**Issue by Vovacr** [Zrips/CMI#8968]
### Description of Issue

Hello, there was such a problem that when I try to kill a mob/player, I seem to hit them, but the hearts of the entities are not taken away. I can kill only with a trident (I don't know why with it). Everything else just does not apply damage
![IMG_20240722_095121_007](https://github.com/user-attachments/assets/1244393a-5463-440b-8287-1156cf7c1ea0)
![IMG_20240722_095121_747](https://github.com/user-attachments/assets/2b4e6313-ae51-4e58-a0fc-ce4f99611679)
![IMG_20240722_095121_127](https://github.com/user-attachments/assets/63bb7e12-62dc-471b-bcdb-19ed5c4b5663)

### Version Information

```shell
9.7.4.7
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Simplest approach is to test things with single plugin in question, if issue persists then resetting its config files could help out to determine if there was something with that. CMI in general doesn't really control your damage towards entities, so you might want to look into any protection plugins for possible cause of your issue.
