### ISSUE TITLE
Folia TextDisplay sometimes crash server

### ISSUE THREAD

**Issue by Galajus** [Zrips/CMI#8970]
### Description of Issue

Sometimes on folia server when player quit server crash when i have any CMI Hologram.
Server not use other TextDisplay

### Version Information

```shell
CMI: 9.7.4.7 SqLite
CMILib: 1.5.0.9 
Server: Folia 1.20.6-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-b0-folia(CMIEInjector) CMI Chat: Enabled 
Modules -> 65 enabled 1 disabled: votifier

This server is running Folia version 1.20.6-DEV-master@d797082 (2024-07-21T22:44:16Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
```

### Errors

```shell
https://pastebin.com/Vq1Y9BCF
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Error message doesn't mention CMI. Will close this ticket for now, but if you have error message with CMI in it then please let me know about it and I can fix it.

**Comment by Galajus** [comment]
Looks like chat booble (only this can use TextDisplay now from CMI without any holograms?) issue on player teleport on folia server, old trace with new additional logs. /spawn has 5 seconds 

https://pastebin.com/CD9P5hiP
