### ISSUE TITLE
Riptide disappearing from thrown tridents.

### ISSUE THREAD

**Issue by NyhmsQuest** [Zrips/CMI#8978]
### Description of Issue

When players throw a trident with Riptide enchant that's higher than level 3, the enchant will disappear and throw an error in console.

https://mclo.gs/imIzrYS

### Version Information

```shell
CMI: 9.7.4.5 Unknown  SqLite-> 9.7.4.7
CMILib: 1.5.0.9 
Server: Pufferfish(43) 1.20.4-R0.1-SNAPSHOT-
CMI economy: ᴅɪꜱᴀʙʟᴇᴅ CMI Chat: ᴅɪꜱᴀʙʟᴇᴅ 
Modules -> 63 enabled 3 disabled: customMessages, tablist, moneyCheque
```

### Errors

```shell
https://mclo.gs/imIzrYS
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
