### ISSUE TITLE
[Info request] Change a username manually from Mysql

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#898]
Hi, i was looking this plugin and i would to buy it, anyway i run a offline network bungee and i got a custom plugin that change the name/uuid on mysql (i support player who purchase plugin) but i noticed when testing this stuff, the name/uuid on mysql is overwriten by the plugin... there is any solution about it? (via api or setting).
P.S. i still don't have purchase the plugin (i just still testing on isolate server for myself) but i am gonna to buy it as soon this small obstacle will become fixable ^^ (i am Malachiel on spigot)

**Comment by xion87** [comment]
Since i started to get anoying, purchasing premium plugin and see the plugin is bad and no author support is pretty iritatting, so before i purchase a premium, i download it from, yes the black spigot, and test in on my local pc, before purchasing it, so i check if meet all needs, so if yes, i will buy it otherwise just delete it.
I will try to do that and if is working i will purchase the plugin imediatly :3

**Comment by Phyther** [comment]
I will tell you, it is a great plugin, and there is support here.

**Comment by CloudeLecaw** [comment]
normaly the CMI leak on blackspigot is forbitten. Dont do unallowed things ;)
Well i agree Phyther the plugin is worth each cent.
but dont aspect support before you bought it ;3

**Comment by LogGits** [comment]
Ok I feel stupid xD could you explain what is happening with cmi. maybe with steps to reproduce aswell. I'm sure this issue can be resolved and heads up black spigot leaks of plugins usually present false issues expecially with cmi.

**Comment by xion87** [comment]
> normaly the CMI leak on blackspigot is forbitten. Dont do unallowed things ;)
> Well i agree Phyther the plugin is worth each cent.
> but dont aspect support before you bought it ;3
> 
> Os,,it would be nice if this thread will be closed now xion87 can ask aggain if he really bought the plugin :) may we see us soon here <3

I just asking if is possible to do thing thing and change the name from database  for move all player data to new one. I tried it myself and database was keeping to be overwrite by the plugin, so all manually edit on database are cancelled

**Comment by LogGits** [comment]
Correct me if I am wrong, you are asking if cmi has the ability or will get the ability to change the name of its own database? Or are you talking about modifying the database via command ingame?

**Comment by xion87** [comment]
I tried to change from mysql manually the uuid and the name, but if i log the "new" player, it will create a new value instead using the edited data

**Comment by LogGits** [comment]
Ah ok I getcha. So basically the player is joining with a new offline uuid and therefore to prevent conflicts cmi creates a new user in the table.

**Comment by Zrips** [comment]
@xion87 
Basic code should look like
```
	// Removing user from cache and database by uuid
	CMIUser user = CMI.getInstance().getPlayerManager().softRemoveUser(uuid);
	// Setting new name, not essential as it will be updated when player logs into server anyways
	user.setName(name);
	// New uuid
	user.setUuid(newUUID);
	// Reseting database ID which will be updated with next save cycle
	user.setId(0);
	user.addForDelayedSave();
	// And lets add new user to cache
	CMI.getInstance().getPlayerManager().addUser(user);
```
CMI is not really made to properly handle UUID and name changes, as this is really specific thing to have, but this code should remove old entry from database and update with new copy just with new UUID and new name. Dint tested it, so if something is not working, give me a shout.

**Comment by xion87** [comment]
> @xion87
> Basic code should look like
> 
> ```
> 	// Removing user from cache and database by uuid
> 	CMIUser user = CMI.getInstance().getPlayerManager().softRemoveUser(uuid);
> 	// Setting new name, not essential as it will be updated when player logs into server anyways
> 	user.setName(name);
> 	// New uuid
> 	user.setUuid(newUUID);
> 	// Reseting database ID which will be updated with next save cycle
> 	user.setId(0);
> 	user.addForDelayedSave();
> 	// And lets add new user to cache
> 	CMI.getInstance().getPlayerManager().addUser(user);
> ```
> CMI is not really made to properly handle UUID and name changes, as this is really specific thing to have, but this code should remove old entry from database and update with new copy just with new UUID and new name. Dint tested it, so if something is not working, give me a shout.

Thank for the reply but deleting old values don't help, because i want the new  player use all old CMI data (like money, home, ecc..), so there is no way for now doing it?

**Comment by Zrips** [comment]
@xion87 
You will not remove old data, user data keeps unchanged, only data base entry gets removed as its not correct one and contains UUID which cant be changed. But cached User object contains all information which includes money, homes and so on, you will simply create duplicated entry in database with new UUID which will have new ID.

**Comment by xion87** [comment]
Thank you i gonna make my dev to do it, anyway i purchased your plugin right now ;) (Malachiel on spigot)
