### ISSUE TITLE
[Issue] Crash report

### ISSUE THREAD

**Issue by Phyther** [Zrips/CMI#899]
**Description of issue or feature request:**
Server stopped responding when I came out of AFK

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/qGWRHnJP
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
https://pastebin.com/PqZqALJC
```

**Cmi Version (using`/cmi version`):** 
8.0.18.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper(342) 1.13.1-R0.1-SNAPSHOT

**Comment by LogGits** [comment]
This looks like it's being caused by another plugin probably venturechat. Though I could be wrong.

**Comment by Zrips** [comment]
Seems to be caused by ventureChat while processing placeholders after chat message been sent by CMI plugin.

**Comment by Phyther** [comment]
@Zrips thank you. I'm waiting for a response from the author of Venturechat.
