### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by BrucePfeiffer** [Zrips/CMI#8993]
The plugin isnt working for me on version paper/spigot 1.21 I have installed the latest version of the plugin but when I do /plugins ingame it shows CMI as red color. Is the plugin updated to version 1.21?

**Comment by MaHl111** [comment]
I'm pretty sure you don't have CMILib. Manually download latest version of [CMILib](https://www.spigotmc.org/resources/cmilib.87610/).

**Comment by Zrips** [comment]
@BrucePfeiffer 
Make sure that you have CMILib installed, like @MaHl111 suggested here, as its required for CMI to work. For future reference, if something doesn't work you will need to check console for any error messages you can find there relating to the plugin in question, if plugin is red that would mean that it failed to load which means that in 99.99% instances there will be error message in console pointing out what went wrong which will not only give you better idea why it failed but provide better idea for plugin developers in determining how to fix it.
