### ISSUE TITLE
Custom death messages with tridents etc

### ISSUE THREAD

**Issue by BirminghamBoy** [Zrips/CMI#8996]
### Description of Issue

Using custom death messages and, when using weapon such as trident to kill a player, the death message doesn't show that the player was killed by trident. Instead, it shows the name of whatever item the player is holding after their trident is thrown.

### Version Information

```shell
[Tue 10:51:26 INFO ] --------------------------------------------------
  [Tue 10:51:26 INFO ] CMI: 9.7.4.8 Velocity CMIB  SqLite
  [Tue 10:51:26 INFO ] CMILib: 1.5.0.9 
  [Tue 10:51:26 INFO ] Server: Paper(109) 1.21-R0.1-SNAPSHOT-
  [Tue 10:51:26 INFO ] CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
  [Tue 10:51:26 INFO ] Modules -> 56 enabled 10 disabled: spawnerProximity, flightCharge, hpBossBar, tablist, playerCombat, votifier, holograms, spawnerCharge, namePlates, bossBarCompass
  [Tue 10:51:26 INFO ] --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
