### ISSUE TITLE
First spawn not working

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [Zrips/CMI#900]
**Description of issue or feature request:**
When i set /cmi setfirstspawn and /cmi setspawn (both on world "spawn") new players are not spawning there, but on default world - "world". 

version
8.0.18.0, paper 319

**Comment by M4rtyn4** [comment]
I have them spawning in air in The End
When I tied /spawn "player that joined" it says
Teleport location is unsafe. 3rd party plugin.
But I don't have other plugins that have to do with spawn.
Older CMI version spawn people fine.

**Comment by TheTopCz** [comment]
Maybe #879

**Comment by Kryniowesegryderiusz** [comment]
It was multiverse. Thank you <3
