### ISSUE TITLE
The Fruit of Horus stops functioning

### ISSUE THREAD

**Issue by jzxdx-java** [Zrips/CMI#9006]
Visit https://github.com/Zrips/CMI/discussions/new to post question

Hi again! I had a problem, I made sure that CMI did it, and now I am writing to you. The chorus fruit stops working for me, namely it stops teleporting, although not completely, it still works, but only with the opto.
When you disable Cmi via the PlugmanX plugin, the chorus starts working normally again. I don't really know why this is.

**Comment by mrfloris** [comment]
Can not reproduce on 1.20.4 and 1.21 servers. The chorus works fine; I can't even imagine how or why CMI would be intervening with chorus fruit teleportation.

**Comment by Zrips** [comment]
@jzxdx-java 
Be sure that you didn't negate cmi.chorusteleport permission node, which is given to everyone by default, so by default it behaves as vanilla server, but if you have it negated then chorus teleportation would be blocked. In case you didn't negate but your permission plugin failed to properly recognize it, you might need to manually add it to your players base permission group
