### ISSUE TITLE
Ptime Bug | Been there for 3+ years

### ISSUE THREAD

**Issue by Rexmen1** [Zrips/CMI#9007]
### Description of Issue

So this bug has been there for 3+ years and never fixed really.. Player's ptime needs resetting every now and then as when its day time they are showed night time and when night time they are showed day time. Players gets mobs in day time and night time is peaceful..

This is fixed when running /ptime reset command

### Version Information

```shell
[05:32:43 INFO]: --------------------------------------------------
[05:32:43 INFO]: CMI: 9.7.4.9 Velocity CMIB  SqLite
[05:32:43 INFO]: CMILib: 1.5.1.0 
[05:32:43 INFO]: Server: Paper(2278) 1.21-R0.1-SNAPSHOT-
[05:32:43 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[05:32:43 INFO]: Modules -> 56 enabled 10 disabled: spawnerProximity, mirror, elevator, tablist, ranks, skin, noTarget, elytraBoost, paintingEditor, elytraLaunch
[05:32:43 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Could you check database, users table and ptime collumn. What does it say for all of the players?

**Comment by Rexmen1** [comment]
used that command and its going on forever not stopping... been 5 minutes now and maybe even take 15-30 minutes to complete? is it normal?

**Comment by Rexmen1** [comment]
it is set to -1 for most but few playrs had 6000 etc...

**Comment by Rexmen1** [comment]
still going on and its been 30 minutes

**Comment by Rexmen1** [comment]
Should have given warning that it may take hours, and if server stops what would happen etc!!!

**Comment by Rexmen1** [comment]
still players needs /ptime reset to fix their time fixed...

**Comment by Zrips** [comment]
How many records did it updated? As it looks like every single player record had their ptime set to something over -1 if it took so long to save it all, where by default players receive -1 and this would only change if ptime is used on the player. 
And went over code once more, player time is being only set with ptime command which gets triggered only manually by default, so its either 3rd party plugin modifying things or there is some sort of setup on your server which triggers /cmi ptime command at some point.
You could try checking if player ptime gets set when he relogs or does particular actions after you used `cmi resetdbfields Zrips ptime` just this time you can use specific player name to reset record to -1, check if it gets saved into database which will have some delay, like up to 15 seconds before it gets recorded, after that check when this value changes to something else.
If there is ability to clone your server and test it out on test environment could help out in determining if this issue relates to another plugin, something with CMI plugin setup or something else entirely.
Maybe you have portal area setup with ptime command triggering in your spawn area or similar? 

Your issue with ptime looks to be isolated one so something different with your specific setup on your server which forces players ptime with /cmi ptime command or some other 3rd party plugin triggers specific CMI method
