### ISSUE TITLE
Could not pass event PlayerTeleportEvent to CMI v9.7.4.9

### ISSUE THREAD

**Issue by BerndPixel** [Zrips/CMI#9013]
### Description of Issue

As I have already opened a bug report, this error unfortunately still exists. (https://github.com/Zrips/CMI/issues/8994)
Now the problem is that the error no longer occurs via /cmi portals, but when you go through an end or nether portal. 

### Version Information

```shell
CMI Plugin Version: 9.7.4.9
CMILib: 1.5.1.0
Server: Paper(123) 1.21-R0.1-Snapshop+
Vault: 1.7.3-CMI
```

### Errors

```shell
https://pastebin.com/ETn2m5WG
```

### Relevant Config Sections

```yaml
No response
```

### Relevant Plugins

No response

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Did another pass over existing code to account for this potential issue. Will be resolved with next version.
