### ISSUE TITLE
Module - setHome bedInteract - When a bed is occupied by an entity or a player, the respawn point is not created correctly.

### ISSUE THREAD

**Issue by kitovoi111** [Zrips/CMI#9014]
### Description of Issue

If I put 2 beds and enable module: bedInteract, then I can get 2 spawn points. how to do it: when a resident sleeps on the bed - if I right-click on the bed - the home point is set, but the respawn point (vanillla) is not. Therefore, I can create 2 points this way (1 home point and 2 respawn point). That is, first I sleep on the bed without a resident and set (the respawn point and the home point) - then when the resident lies down on the 2nd bed - I just right-click and set the home point (the respawn point is not set) - thus I make myself 2 home points, roughly speaking.

The solution to the problem is very simple: if your bed is occupied by a player or entity (resident) - then you just need to disable bedInteract using the right mouse button so that the home point is set when the bed is free and not occupied.

### Version Information

```shell
CMI 9.7.4.9
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version
