### ISSUE TITLE
Baltop is broken showing only 1 player

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#902]
**Description of issue or feature request:**
The command /baltop only shows 1 random player's balance.
Every player sees only this 1 particular player starting with an "a".
On my test server, it will only display the wait for the recalculation message

**ERROR (DELETE IF YOU HAVE NO ERROR):**
No errors on the console

**Cmi Version (using`/cmi version`):** 
8.0.18.0

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
git-Paper-323 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Comment by x1p** [comment]
After a restart, it seemed to work for a while, but now it shows only the recalculation message. I never get to see the baltop at all.

**Comment by Zrips** [comment]
Any error messages in console on first /baltop?

**Comment by x1p** [comment]
Not at all. Otherwise: I would have said so immediately.

**Comment by Zrips** [comment]
Strange, how many entries do you have in your database?

**Comment by x1p** [comment]
My test server: probably around 5
Survival 115
Creative around 10
All do not work

**Comment by Zrips** [comment]
What economy plugin are you using? And what you see when performing **/cmi balance** command?

**Comment by x1p** [comment]
> Btw: I'm using vault-1.7.1 + CMIEinjector

/cmi balance shows my own balance: €1.561,97

**Comment by x1p** [comment]
Tried the other vault version (which does not need the injector).
Result is the same: It's recalculating and you can wait forever to show the baltop.

**Comment by Zrips** [comment]
Will add some extra changes, but its quite interesting why its failing for you in particular. Will post new version today, test it and come back if issue persists.

**Comment by x1p** [comment]
I'm probably the only one on the planet, so I've deleted my sqlite file on my test server. This does not solve it too. Baltop will never be shown anymore. RIP baltop
