### ISSUE TITLE
Player teleports under the block

### ISSUE THREAD

**Issue by RemForever0** [Zrips/CMI#9022]
### Description of Issue

When you teleport through /warp or portals (maybe /tp), you teleport under the block for 1 second, it’s very noticeable, I don’t know what the problem is

### Version Information

```shell
CMI - 9.7.5.0
CMILib - 1.5.1.0
Paper(1620) 1.12.2-R0.1-SNAPSHOT
```

### Errors

```shell
https://imgur.com/a/quSseBQ
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Could you test this while having F3 enabled to just get better idea to which location you are being teleported to

**Comment by RemForever0** [comment]
sure, when teleporting, I teleport to coordinates 22, and then to 23
https://imgur.com/a/YPDVNo3

**Comment by Zrips** [comment]
And what is the target location set to be for that portal?

**Comment by RemForever0** [comment]
y:23
