### ISSUE TITLE
[Tab Complete] Custom alias tab complete can not return real names

### ISSUE THREAD

**Issue by Valeoria** [Zrips/CMI#9023]
### Description of Issue

Both the [playername] and [nicknames] tags for tab auto complete inside custom alias return player nicknames.

There is currently no way to tab complete real usernames.

I am not 100% sure if this is an issue, but it seems odd that there would be two tags that return the same information, I feel that [playername] was meant to return playernames without nicknames.

### Version Information

```shell
[10:56:43]: --------------------------------------------------
>....
[10:56:43]: CMI: 9.7.4.9 SqLite-> 9.7.5.0
[10:56:43]: CMILib: 1.5.1.0 
>....
10/08/2024 [10:56:43]: Server: Paper(2280) 1.21-R0.1-SNAPSHOT+
[10:56:43]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
>....
10/08/2024 [10:56:43]: Modules -> 49 enabled 17 disabled: spawnerProximity, hpBossBar, tablist, moneyCheque, noTarget, spawners, paintingEditor, dynamicSigns,
playerChatTag, coloredArmor, flightCharge, disabledEnchants, chatBubble, ranks, spawnerCharge, vanish, namePlates
[10:56:43]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
`[allIGNPlayerName]` should give clean list of usernames, unlike [playername] in the tab-suggestions of cmi aliaseditor made commands
