### ISSUE TITLE
How to logs others Enderchests and others /invsee interactions/actions

### ISSUE THREAD

**Issue by Proemmis** [Zrips/CMI#9024]
Hello all ! sorry to bother you, I have a quick question, I want to make a mod to have logs on what my staff takes or puts in other players' ender chests with /ec <playername>, I wanted to know how TO DO ?

I can't find anything in the CMI API that can help me and when I try to get the name of the container, it only gives me `container.enderchest`

is the title managed? how can I do it?

Thank you in advance for your response, best regards!

![image](https://github.com/user-attachments/assets/ff62555a-e95d-4516-93e2-27de39f3433f)

**Comment by polang233** [comment]
Perhaps you can try it. When listening to InventoryClick Event, check if it is of type ENDER_CHEST

**Comment by Proemmis** [comment]
you can't get for enderchests, as i said I try to get the name of the container, it only gives me container.enderchest


 the problem is knowing who it belongs to! how do I do it?

cordially :)

**Comment by polang233** [comment]
> you can't get for enderchests, as i said I try to get the name of the container, it only gives me container.enderchest
> 
> the problem is knowing who it belongs to! how do I do it?
> 
> cordially :)

I'm sorry, there seems to be an issue with the translation, so I didn't understand what you meant by clearing it

**Comment by polang233** [comment]
> > you can't get for enderchests, as i said I try to get the name of the container, it only gives me container.enderchest
> > the problem is knowing who it belongs to! how do I do it?
> > cordially :)
> 
> I'm sorry, there seems to be an issue with the translation, so I didn't understand what you meant by clearing it

You can try using player. getInventory(). getHolde(), and I tested that it can obtain the player's information

**Comment by Proemmis** [comment]
I already tried thats « Null »

**Comment by Zrips** [comment]
@Proemmis 
There is no actual direct way to get owner of ender chest inventory at the moment.

**Comment by polang233** [comment]
> I already tried thats « Null »

If you don't mind the trouble, you can ask the player to right-click on the block and block it if it's a ENDER_CHEST, and then create a ENDER_CHEST for him, so you can fill in the Holder

**Comment by Proemmis** [comment]
@Zrips okay thank you ! Would it be possible to add it please ? Thank you very much :)
