### ISSUE TITLE
''ClickHoverMessages: false'' and Hover Text 

### ISSUE THREAD

**Issue by elmonomiguel** [Zrips/CMI#9027]
Hello, I have a problem:

I had to disable the ''ClickHoverMessages: false'' option in chat.yml because the cmi mute conflicted with the litebans mute and users were not penalized correctly. My problem is that the information that appeared when I placed the mouse over the players' nicknames was very useful to me and it was a function specific to this that I disabled. Is there a way to activate it without the other thing bothering me?

**Comment by Zrips** [comment]
What was the exact issue with litebans mute and cmi mute conflicting?

**Comment by elmonomiguel** [comment]
Well, from what I have been able to see, the problem lies in the following: 

- When I muted someone using the /mute command, the Litebans message came out in the chat saying that I had muted them but that wasn't the case since when the player wrote their message came out in the chat. All this after I disabled the CMI /mute alias and followed all the steps described in Discord.

- The only solution I found was to disable 'ClickHoverMessages' in chat.yml (settings), since that way the Litebans mute worked correctly. I think it may be related to the clickHover events, since I tried the InteractiveChat plugin together with CMI to put the HoverText and the /mute command does not work correctly either.

If you could solve this error in some way or put the Hover Text independently to Clicks (I don't know if it's possible) it would be very, very useful to me, since as I say, these messages that appear when you leave the mouse over the nickname seem to me very useful.

**Comment by elmonomiguel** [comment]
So Zrips, is there anything I can do to make the hoverText work without breaking the Litebans /mute function? And thank you very much for everything in advance

**Comment by Zrips** [comment]
is there specific reason why you use litebans mute command?

**Comment by elmonomiguel** [comment]
I only have CMI in one mode, so as Litebans I have it connected to the entire network database. I like to keep track of global sanctions with the same plugin. That's why I use Litebans otherwise... I would have used the CMI sanctioning system for a long time and there was a problem hahaha
