### ISSUE TITLE
Flight Bug?

### ISSUE THREAD

**Issue by DeadIntermediate** [Zrips/CMI#903]
**Description of issue or feature request:**
I have added the following permissions to enable flight charging by optional of money and exp:
- cmi.command.fly
- cmi.command.flightcharge
- cmi.command.tfly

I have type /tfly or /fly and yet, I am not fling. It does say "You have set fly to True for DeadIntermediate (Online). I have tried to double jump and yet I am not fly. I have deop'd my self to make sure this works as a player.

I am wondering if this is a bug or maybe I am not doing something right.

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## No Error ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## https://pastebin.com/CejAeRTXE ##
#####################################
```

**Cmi Version (using`/cmi version`):** 
http://prntscr.com/l1whjc

**Server Type (Spigot/Paperspigot/etc):** 
Spigot 1.13.1

**Server Version (using `/ver`):** 
http://prntscr.com/l1whm7

**Comment by Zrips** [comment]
Did you enabled FlightCharge in config file?

**Comment by DeadIntermediate** [comment]
Yes, I did. I can provide the config if you like me too.

**Comment by DeadIntermediate** [comment]
Just a heads up. The issue is still happening with CMI 8.0.21.3 on Spigot 1.13.2.

Here is proof of Current Verison of Spigot and CMI.

**Comment by DeadIntermediate** [comment]
Just so you know, This is still happening on 8.0.22.0.
