### ISSUE TITLE
Renaming Armorstands broken

### ISSUE THREAD

**Issue by Yertled** [Zrips/CMI#9030]
### Description of Issue

For the longest time, giving armorstands a name has worked with the permission cmi.command.armorstand.name
But after the 1.21 minecraft update, my players lost the ability to rename an armor stand.
Picture how it's supposed to look:
![image](https://github.com/user-attachments/assets/08773957-fe41-48db-8d5e-e4b2ce8528fe)

How it's currently looking: (No press Q to rename)
![image](https://github.com/user-attachments/assets/2ef337b2-f5f9-4e13-9e3d-81eabe1e5b0f)

### Version Information

```shell
CMI: 9.7.5.0 Unknown  SqLite
[08:26:03 INFO]: CMILib: 1.5.1.0 
[08:26:03 INFO]: Server: Paper 1.21-R0.1-SNAPSHOT-
[08:26:03 INFO]: CMI economy: ᴅɪꜱᴀʙʟᴇᴅ CMI Chat: ᴅɪꜱᴀʙʟᴇᴅ 
[08:26:03 INFO]: Modules -> 63 enabled 3 disabled: customMessages, tablist, moneyCheque
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
