### ISSUE TITLE
hunger override: false not work

### ISSUE THREAD

**Issue by NikolaJyun** [Zrips/CMI#9031]
### Description of Issue

In both 1.20 and 1.21, the same issue occurs where the hunger value is completely depleted even when hunger override: false is set.

### Version Information

```shell
--------------------------------------------------
[Server] [17:29:57 INFO]: CMI 插件版本: 9.7.5.0 SqLite
[Server] [17:29:57 INFO]: CMILib: 1.5.1.0 
[Server] [17:29:57 INFO]: 伺服器: Paper(46) 1.21-R0.1-SNAPSHOT+
[Server] [17:29:57 INFO]: CMI economy: 啟用 Vault: 1.7.3-CMI CMI 聊天: 禁用 
[Server] [17:29:57 INFO]: 模塊 -> 65 已開起 1 已關閉: votifier
[Server] [17:29:57 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Could you be more specific about which feature we are talking here in particular?

**Comment by NikolaJyun** [comment]
CMI Config Line1402
hunger:
  # Do you want to give more than 20 hunger for players
  overide: false

**Comment by Zrips** [comment]
This section would only handle limit of `/cmi hunger` command. Can you elaborate more on what you mean by "the hunger value is completely depleted"

**Comment by NikolaJyun** [comment]
When hunger override=false, the hunger value should stay at 1, but it’s currently not working. The hunger value still drops to 0, causing damage due to starvation.

**Comment by Zrips** [comment]
This section isn't controlling players existing hunger, its only for the command /cmi hunger which would allow you to set more than 20 hunger for the player. If you are talking about players losing hunger while being jailed then you should check PreventHunger  under jail section in config file. Other than this we don't have active hunger depletion prevention in place

**Comment by NikolaJyun** [comment]
Alright, because I remember that at 1.19, you wouldn't starve to death (I only play on hard mode), I thought it was due to this setting.
