### ISSUE TITLE
[Error] Rank system money Maximum is 21474836

### ISSUE THREAD

**Issue by djacks6278** [Zrips/CMI#905]
**Description of issue or feature request:**

There is a problem with the rank system.
The player's money
Not shown in 21474836 and above.

why 21474836...? not 2147483647 ?
we need change double

PS.
That's how the money looks.
Operation is done properly.

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
---Rank Info----
Money : 21474836(Max) / 10000000000
...

Real Player Money is 2000000000

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
No Config Set
```

**Cmi Version (using`/cmi version`):** 

--------------------------------------------------
CMI plugin version: 8.0.18.0
Server version: Paper(1562) 1.12.2-R0.1-SNAPSHOT
Vault version: 1.7.1-b91(CMIEInjector)
--------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 

PaperSpigot

**Server Version (using `/ver`):** 

Paper version git-Paper-1562 (MC: 1.12.2 R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will be fixed with next build.
