### ISSUE TITLE
CMI kits giving unlimited uses despite being set to a one time use

### ISSUE THREAD

**Issue by cookieclicker21** [Zrips/CMI#9053]
i have the Kits for CMI ranks set to only be able to be used one time but somehow players are able to use them an unlimited amount of times, their weight is also set correctly along with their group

The Server is 1.21.1 PaperMC, CMI: 9.7.5.3, CMILIb: 1.5.1.1 added CMIVelocity (1.0.1.2)  just in case maybe that was causing it since it uses a velocity proxy , any help would be appreciated

**Comment by Zrips** [comment]
Will need to see your actual kit setup which players are able to use more than one time as of testing

**Comment by cookieclicker21** [comment]
The only players capable of using the kits are players with OP privileges, the ones that can bypass the cooldown and the usage

**Comment by Zrips** [comment]
Yea, but I need actual kits save section from kits file to do some testing or just to check if its properly setup

**Comment by cookieclicker21** [comment]
https://paste.gecko.lol/KJCF

**Comment by Zrips** [comment]
@cookieclicker21 
Is there any particular kit which was taken more than one time or does this issue apply to all of them?

**Comment by cookieclicker21** [comment]
All of the kits are capable of being used more them once by operators, any one other then the operators does have access to the kits if they have the right rank, however they cannot use them as the cooldown is just stuck, and it says”you cant use this more then <usage limit> times!

**Comment by Zrips** [comment]
Well kits are one time use, while cooldown still being shown without valid usages is somewhat confusing but in any case kit should not be given to the people without bypass permission. So which group of players are able to use kits and what kit permission access do they have?

**Comment by cookieclicker21** [comment]
The groups that i sent in the code, all of them have access to their own individual kits with their own permissions set:
Each group has these kit permissions:
cmi.command
cmi.command.kit
cmi.kit.<kitName>
