### ISSUE TITLE
Kits are on permanent cooldown

### ISSUE THREAD

**Issue by cookieclicker21** [Zrips/CMI#9058]
### Description of Issue

Wanted to report something that i dont think is natural for the CMI kits, they are stuck on a permanent cooldown despite their cool down being set, players cooldowns are all stuck on their total time cooldown and they will only go down if a user that can bypass the cool down uses it, and thats only for players with that permission. All groups have their permissions set correctly- cmi.command, cmi.command.kit and cmi.ki.[kitName], have tried using /kitcdreset but its saying they are no cooldowns for anyone but the players cant use the kits because the cooldown is stuck, any help would be great, thank you for your time

### Version Information

```shell
CMI: 9.7.5.3 SqLite
CMIlLib: 1.5.1.1
Server:Paper(12) 1.211_R0-SNAPSHOT-
CMI economy:Disabled Vault: 1.7.3-b131 CMI Chat:Disabled
Modules -> 64 2 disabled: tablist, votifier
```

### Errors

```shell
No errors, just kits being frozen
```

### Relevant Plugins

CMI: 9.7.5.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update, if issue persists, let me know.
