### ISSUE TITLE
[Questions] A few questions

### ISSUE THREAD

**Issue by TheGamingChris** [Zrips/CMI#906]
After thinking a lot about your plugin, I have another few questions:

1. Is there any known bug with ViaVersion?
2. Can I disable the rank system?
3. Is there a test server to test the plugin?
4. Is there a command to watch a players inventory/enderchest?
5. Is it possible to watch a chest inventory without open the chest?
6. Is it possible to setup the count of enderchest rows (or compatible withe the plugin https://www.spigotmc.org/resources/custom-enderchest.8868/ )

Best wishes

TheGamingChris

**Comment by Zrips** [comment]
1. No reports related to ViaVersion until now
2. Ranks system is not enabled if you are not using it. Players needs to have appropriate permission nodes to get access to basic rank from which rest of them will be used.
3. No test servers.
4. Yes, its was first think added to this plugin and it was only one feature for some time. Option to edit offline player inventories too.
5. Silent chest, so yes.
6. Enderchest is vanilla one, CMI currently doesn't control its behavior.

**Comment by TheGamingChris** [comment]
What is the command to see a players ender chest? [Nothing found about it in wiki]
