### ISSUE TITLE
Get owner and inventory name of Enderchests :)

### ISSUE THREAD

**Issue by Proemmis** [Zrips/CMI#9065]
Hello, it would be super great to add the possibility of knowing the owner and the inventory of the enderchests.

I would like to create a log system allowing you to know what the staff takes and deposits in the enderchest players, this can be useful in the event of an attempt to steal from the enderchests of banned players for example.

Thank you so much if this is added!

i posted an issue here : https://github.com/Zrips/CMI/issues/9024

**Comment by CloudeLecaw** [comment]
https://github.com/Zrips/CMI/discussions
