### ISSUE TITLE
Custom recipe doesn't work

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#9071]
### Description of Issue

Hello,
I've just created some custom crafts with the `customrecipe` module, but they don't work after a restart.
![image](https://github.com/user-attachments/assets/96bc06b0-ab25-451b-bdf2-cb1443a48825)![image](https://github.com/user-attachments/assets/171a4bbc-5358-40f4-a028-26f201f895c3)

### Version Information

```shell
CMI: 9.7.5.4 Unknown MySQL
CMILib: 1.5.1.1
Server: Paper 1.20.6-R0.1-SNAPSHOT-
CMI economy: Activée Vault: 1.7.3-CMI CMI Chat: Désactivée
Modules -> 34 enabled 32 disabled: spawnerProximity, cuffed, mirror, tablist, armorEffects, moneyCheque, elytraBoost, elytraLaunch, serverLinks, bossBarCompass, chatBubble, votifier, headDrop, spawnerCharge, namePlates, homeInteractions, hpBossBar, anvilRenameColor, spawners, dynamicSigns, playerChatTag, durabilityLoss, deathMessages, teleportWith, disabledEnchants, worldLimitsElytra, worldLimits, ranks, sitAnimation, silentChest, warmup, totemBehavior
```

### Relevant Config Sections

```yaml
https://api.mclo.gs/1/raw/Eu9ch67
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
![image](https://github.com/user-attachments/assets/bd2b63d7-98fa-44a7-b146-39a697e12616)
Could you try to test this with CMI only in case there is an issue with another plugin overriding default behavior? As it seemingly works correctly with base setup on 1.20.6 paper server, unless you have custom server build which got misreported with /cmi version

**Comment by NoltoxGit** [comment]
> Could you try to test this with CMI only in case there is an issue with another plugin overriding default behavior? As it seemingly works correctly with base setup on 1.20.6 paper server, unless you have custom server build which got misreported with /cmi version

Hello,
Sorry for the late reply, but I think I know what the problem is.

It's because the item `TADPOLE_BUCKET` is different depending on the age of the dummy when it's retrieved. And so what's causing the craft not to work because the “Require exact ingredient” option is buggy, it always stays on **Enabled**.

So to fix the problem, you'd have to debug this parameter.

_( The problem still persists even with the latest version of Paper 1.21.1 at the time of writing.)_

**Comment by NoltoxGit** [comment]
Hello @Zrips,
Do you have any news about this bug?

**Comment by Zrips** [comment]
Will make a fix relating to that button, if you still experience any issues, let me know.
