### ISSUE TITLE
Please add the translation for these lines when opening a shulker box from the inventory. Thank you

### ISSUE THREAD

**Issue by MirMiksan** [Zrips/CMI#9076]
Hello, the CMI plugin has added the feature to open shulker boxes directly from the inventory. Could you please make it so that the shulker box name and its color are translatable? This is a very important feature for both me and other users whose first language is not English. Thank you in advance.

![image](https://github.com/user-attachments/assets/f52d069f-26bb-44e0-ad70-a906ec644a26)

**Comment by CloudeLecaw** [comment]
i dont know if the item can be translatelike this its at leadt a vanilla shulker bix and cmi just offers to open it. its not like cmi does modificate this Box.

but pls move your request to the right area
https://github.com/Zrips/CMI/discussions/new/choose

**Comment by Zrips** [comment]
Should be resolved with next update
