### ISSUE TITLE
/cmi toggleshiftedit is Not Working - Help Would Be Appreciated

### ISSUE THREAD

**Issue by Kalasky** [Zrips/CMI#908]
**Description of issue or feature request:**
Toggle shift edit command does nothing when I try to shift click a sign.

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**Cmi Version (using`/cmi version`):** 
8.0.17.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper Spigot
**Server Version (using `/ver`):** 
297

**Comment by LogGits** [comment]
Not able to reproduce this on build 8.0.18.0. When toggleshiftedit is enabled are you shift + rightclicking the sign (just to be sure)?

**Comment by Kalasky** [comment]
I upgraded CMI to the latest version recently, and yes I am shist + right-clicking the sign.

**Comment by Zrips** [comment]
Will be fixed with next build.
