### ISSUE TITLE
CMI is blocking teleportation of other plugins

### ISSUE THREAD

**Issue by ACluco1** [Zrips/CMI#9081]
### Description of Issue

CMI is somehow blocking teleportation of other plugins (SimpleElevators and our own warp plugin) - those are that i am aware of.

I also installed SimpleElevators and CMI on the test server (only those plugins and the required ones)..
and it really acts strange. After i join the server, elevators are working just fine, also our own warp plugin, but as soon as i type something into the chat, it just stops working.. The plugin (our one) actually sends the message about teleporting and so on, but i stay on the same place. The only fix that i discovered is relog or world change. But if you type again something, it breaks again.

You can try it on your own (https://www.spigotmc.org/resources/simple-elevators-1-8-1-20.44462/) 
Iam sure that the issue is caused by CMI because not only elevators doesnt work, also our warp system. It worked on 1.20 version but after updating, nop.

I can provide more info/video about it

### Version Information

```shell
CMI: 9.7.5.4 SqLite
CMILib: 1.5.1.1
Server: Paper(2297) 1.21.1-r0.1-SNAPSHOT+
CMI economy: Disabled CMI Chat: Disabled
Modules: 65 enabled 1 disabled: votifier
```

### Errors

```shell
NO errors
```

### Relevant Config Sections

```yaml
NO relevant config sections
```

### Relevant Plugins

Simple Elevators | [1.8 - 1.20] 3.13.0

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by ACluco1** [comment]
Also CMI warps and teleportations (/back, /spawn, /home and so on..) works just fine. The only issue is another plugins. After unloading CMI, the plugins start to work again.

**Comment by ACluco1** [comment]
`[Elevator] Task #401 for Elevator v3.13.0 generated an exception
java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.CMI.getPlayerManager()" because the return value of "com.Zrips.CMI.CMI.getInstance()" is null
at Elevator.jar/com.live.bemmamin.elevator.elevator.ElevationHandler.preTeleport(ElevationHandler.java:52) ~[Elevator.jar:?]
at Elevator.jar/com.live.bemmamin.elevator.elevator.ElevationHandler.elevate(ElevationHandler.java:32) ~[Elevator.jar:?]
at Elevator.jar/com.live.bemmamin.elevator.elevator.Elevator.elevate(Elevator.java:116) ~[Elevator.jar:?]
at Elevator.jar/com.live.bemmamin.elevator.elevator.Elevator.elevator(Elevator.java:69) ~[Elevator.jar:?]
at Elevator.jar/com.live.bemmamin.elevator.Events$1.run(Events.java:238) ~[Elevator.jar:?]
at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
`

This started to showing up recently

**Comment by Chevels** [comment]
Same issue here...

Since I put the version 9.7.5.4 of CMI (CMILib 1.5.1.1), my TP plugin does not work anymore. When we try to use a portal the TP plugin sends the message that we have been TP from point A to point B, but in reality we are not TP and at that moment, as long as we stay in the portal CMILib spams my console with this message in a loop:

```
[12:32:47 WARN]: [CMILib] Plugin CMILib v1.5.1.1 generated an exception while executing task 98709563
java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Display.CMITextDisplay.setWidth(double)" because "this.tDisplay" is null
        at CMI-9.7.5.4.jar/com.Zrips.CMI.Modules.Chat.CMIChatBubble.updateLooks(CMIChatBubble.java:159) ~[CMI-9.7.5.4.jar:?]
        at CMI-9.7.5.4.jar/com.Zrips.CMI.Modules.Chat.CMIChatBubble.lambda$2(CMIChatBubble.java:88) ~[CMI-9.7.5.4.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-124-df3b654]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:1.21-124-df3b654]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1595) ~[?:?]
```

Since I put the version 9.7.5.4 of CMI (CMILib 1.5.1.1), my TP plugin does not work anymore. When we try to use a portal the TP plugin sends the message that we have been TP from point A to point B, but in reality we are not TP and at that moment, as long as we stay in the portal CMILib spams my console with this message in a loop:

It is very annoying because none of our TP works anymore :/

**Comment by ACluco1** [comment]
> Same issue here...
> 
> Since I put the version 9.7.5.4 of CMI (CMILib 1.5.1.1), my TP plugin does not work anymore. When we try to use a portal the TP plugin sends the message that we have been TP from point A to point B, but in reality we are not TP and at that moment, as long as we stay in the portal CMILib spams my console with this message in a loop:
> 
> ```
> [12:32:47 WARN]: [CMILib] Plugin CMILib v1.5.1.1 generated an exception while executing task 98709563
> java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Display.CMITextDisplay.setWidth(double)" because "this.tDisplay" is null
>         at CMI-9.7.5.4.jar/com.Zrips.CMI.Modules.Chat.CMIChatBubble.updateLooks(CMIChatBubble.java:159) ~[CMI-9.7.5.4.jar:?]
>         at CMI-9.7.5.4.jar/com.Zrips.CMI.Modules.Chat.CMIChatBubble.lambda$2(CMIChatBubble.java:88) ~[CMI-9.7.5.4.jar:?]
>         at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-124-df3b654]
>         at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-124-df3b654]
>         at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:1.21-124-df3b654]
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
>         at java.base/java.lang.Thread.run(Thread.java:1595) ~[?:?]
> ```
> 
> Since I put the version 9.7.5.4 of CMI (CMILib 1.5.1.1), my TP plugin does not work anymore. When we try to use a portal the TP plugin sends the message that we have been TP from point A to point B, but in reality we are not TP and at that moment, as long as we stay in the portal CMILib spams my console with this message in a loop:
> 
> It is very annoying because none of our TP works anymore :/

Actually as i tried to fix that error which youve got (and i got it aswell), i disabled chatbubbles in config.yml, that way i ve got rid of that error.
but when i am looking at that again i tried to disable chatbubble module in modules.yml, after restart those TP plugins started working again. Hope it helps :)

**Comment by Chevels** [comment]
> > Same issue here...
> > Since I put the version 9.7.5.4 of CMI (CMILib 1.5.1.1), my TP plugin does not work anymore. When we try to use a portal the TP plugin sends the message that we have been TP from point A to point B, but in reality we are not TP and at that moment, as long as we stay in the portal CMILib spams my console with this message in a loop:
> > ```
> > [12:32:47 WARN]: [CMILib] Plugin CMILib v1.5.1.1 generated an exception while executing task 98709563
> > java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Display.CMITextDisplay.setWidth(double)" because "this.tDisplay" is null
> >         at CMI-9.7.5.4.jar/com.Zrips.CMI.Modules.Chat.CMIChatBubble.updateLooks(CMIChatBubble.java:159) ~[CMI-9.7.5.4.jar:?]
> >         at CMI-9.7.5.4.jar/com.Zrips.CMI.Modules.Chat.CMIChatBubble.lambda$2(CMIChatBubble.java:88) ~[CMI-9.7.5.4.jar:?]
> >         at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-124-df3b654]
> >         at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-124-df3b654]
> >         at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:1.21-124-df3b654]
> >         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
> >         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
> >         at java.base/java.lang.Thread.run(Thread.java:1595) ~[?:?]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Since I put the version 9.7.5.4 of CMI (CMILib 1.5.1.1), my TP plugin does not work anymore. When we try to use a portal the TP plugin sends the message that we have been TP from point A to point B, but in reality we are not TP and at that moment, as long as we stay in the portal CMILib spams my console with this message in a loop:
> > It is very annoying because none of our TP works anymore :/
> 
> Actually as i tried to fix that error which youve got (and i got it aswell), i disabled chatbubbles in config.yml, that way i ve got rid of that error. but when i am looking at that again i tried to disable chatbubble module in modules.yml, after restart those TP plugins started working again. Hope it helps :)

Oh thank you ! I'll do that while I wait for it to be fixed.

**Comment by Zrips** [comment]
Should be fixed with next update
