### ISSUE TITLE
No translation for death by TNT minecart

### ISSUE THREAD

**Issue by Woolyenough** [Zrips/CMI#9085]
### Description of Issue

When a player dies due to an explosion of a tnt minecart, only the death message prefix is sent, with the rest of the message being blank.

### Version Information

```shell
Paper 1.21.1 #40
CMI: 9.7.5.4
CMILib: 1.5.1.1
```

### Errors

```shell
No errors are printed.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
