### ISSUE TITLE
Baltop Duplicate Responce?

### ISSUE THREAD

**Issue by DeadIntermediate** [Zrips/CMI#909]
**Description of issue or feature request:**
When I type /baltop, I am getting duplicates.
http://prntscr.com/l218j2

**Cmi Version (using`/cmi version`):** 
 --------------------------------------------------
 CMI plugin version: 8.0.18.0
 Server version: Spigot 1.13.1-R0.1-SNAPSHOT
 Vault version: 1.7.1-b91(CMIEInjector)
--------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-Spigot-f6a273b-02518f9 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
You are running the latest version

**Comment by Zrips** [comment]
Will be fixed

**Comment by x1p** [comment]
Not solved for me. Baltop is still showing duplicate messages.
I'm probably the only one on the planet, so I've deleted my sqlite file on my test server. This does not solve it too.
