### ISSUE TITLE
Error in console on join relating to a placeholder

### ISSUE THREAD

**Issue by thewickening** [Zrips/CMI#9093]
### Description of Issue

Error in console on join relating to a placeholder

### Version Information

```shell
https://gyazo.com/c7f8d36e2025e13db7aeed6f2c6dbaf7
```

### Errors

```shell
https://pastebin.com/aUPcEVAU
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
