### ISSUE TITLE
Massive teleport glitching possiblity's

### ISSUE THREAD

**Issue by iaxedu** [Zrips/CMI#91]
Got an issue with the teleport system from CMI. When you /tphere or /tpahere someone they get placed below the door. This allows for glitching inside certain bases. The GIF shows how the teleport looks. The printscreen shows the required setup. I've also tested this with Essentials and there the player gets teleported like he should be teleported.

[https://gfycat.com/RipeRealisticCuckoo](https://gfycat.com/RipeRealisticCuckoo)
Player above does /tphere and the player gets teleported below.

[https://i.imgur.com/19WrtfA.png](https://i.imgur.com/19WrtfA.png)
This is where I stand.

[https://gfycat.com/HugeGiantBarbet](https://gfycat.com/HugeGiantBarbet)
This is how Essentials teleports.

**Comment by Zrips** [comment]
Should be fixed with next build
