### ISSUE TITLE
[BUG] money dupe using '/cmi sell same' command

### ISSUE THREAD

**Issue by user127001** [Zrips/CMI#911]
Money dupe using '/cmi sell same' command

If I set price 1 diamond=1$, then I hold 10 diamond in hand and 20 diamonds in any other slot of inventory.  Then using '/cmi sell same' command I will get 10x2+20=40$.
Regards,

CMI 8.0.18.0

Spigot

1.13.1

**Comment by Zrips** [comment]
Will be fixed with todays update
