### ISSUE TITLE
Chests opening silently even though /silentchest is off 

### ISSUE THREAD

**Issue by Zachezen** [Zrips/CMI#9118]
### Description of Issue

Upon updating to newest version of CMI & CMILib, chests are defaulting to opening silently. 

Upon opening any chest, the message in Chat is: "Opening chest, silently."

Doing /silentchest shows "You toggled silent chest mode to Enabled"

Doing /silentchest a second time shows "You toggled silent chest mode to Disabled"

Chests no longer say "Opening chest, silently." when being opened anymore. 

### Version Information

```shell
CMI: 9.7.5.9
CMILib: 1.5.1.3
Server: Paper (2283) 1.21-R0.1-SNAPSHOT+
CMI Economy: Enabled
Vault: 1.7.3-CMI
CMI Chat: Enabled
Modules -> 58 enabled 8 disabled: tablist, ranks, votifier, sitAnimation, jail, spawners, vanish, namePlates
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by xRedCrystalx** [comment]
Same issue here:

![image](https://github.com/user-attachments/assets/7480949c-807d-46b9-9ab1-58d0ca144f35)

**Comment by xRedCrystalx** [comment]
Also seems like players cant interact with items inside chests. Instantly teleporting them back. Same for enderchests.

**Comment by Zachezen** [comment]
> try disabling the silent chest module that worked for me
