### ISSUE TITLE
Setworth issue

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#912]
**Description of issue or feature request:**

---
**Bug** - `/cmi setworth diamond 1` doesn't work.

**Enhancement** - It would be nice to see a /cmi setworth hand [price] so the user can simply hold the item and use the command.

---
**Cmi Version (using`/cmi version`):** 8.0.18.0

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1525

**Comment by user127001** [comment]
Are you sure this syntax is possible?
It seems to work differently. You need to hold the diamond in your hand, and then just use the command '/cmi setworth'

**Comment by LogGits** [comment]
Check out `/cmi setworth ?` it says the syntax is `/cmi setworth (itemname) [price]`

**Comment by Zrips** [comment]
Locale is misleading, you cant provide items price, only item name if you want to set for something different then you are holding in your hand. Will remove that variable to avoid this in future.
