### ISSUE TITLE
Jail Does Not Tp Player Out/Players Can't Take Damage (Again)

### ISSUE THREAD

**Issue by TylorTurner** [Zrips/CMI#9125]
### Description of Issue

In jail players do not get teleported out properly and do not take damage even with PreventDamage: false

### Version Information

```shell
9.7.5.9
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Both issues will be fixed with next update
