### ISSUE TITLE
Custom death message

### ISSUE THREAD

**Issue by miselispa** [Zrips/CMI#9128]
### Description of Issue

If Player uses bow to kill himself he gets this type message:
```
Player:
  Item:
  - '&2[playerDisplayName] &7died by &2[sourceDisplayName] &7hand who used &2[item]'
```
Which would look like: 
**John died by John hand who used Bow.**

Instead of getting normal suicide message with this format:
```
Suicide:
    General:
    - '&2[playerDisplayName] &7took their own life'
```

### Version Information

```shell
CMI: 9.7.5.9 SqLite
CMILib: 1.5.1.1 -> 1.5.1.3
Server: Paper(2284) 1.21-R0.1-SNAPSHOT-
CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Enabled 
Modules -> 65 enabled 1 disabled: votifier
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
