### ISSUE TITLE
/warps cant be organised via slots (1.18.2 Purpur)

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#9129]
### Description of Issue

Not sure when this happened, but /warps can no longer be organized by their slots.
No matter where I set a slot, the warp is not moving in /warps.

Is there a way to also throw all unorganised warps into their own page, so they dont just randomly get sorted.

I have player accessible ones and staff ones, and I cant sort the order as slots not working.

### Version Information

```shell
Sorry not in game, im using 9.7.5.4 on PurPur 1.18.2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
If you have multiple warps which should occupy same slot then any additional one will be placed on next free slot, this could snowball if you have bunch of warps trying to occupy single slot while you would have warps which should specifically take slots after it. For example having 5 warps which wants slot 3 would make all those 5 warps to take slots from 3 up to 8, so any warp which has set specific warp between those would again be shifted to next free one.
That said, will make some changes to prioritize warps with set slots over the ones without any, just to place those where you want if you set its position while remaining can be placed in first empty slot, which should produce more consistent result

**Comment by TomLewis** [comment]
This update worked, this update is how I expected it would work when I made the ticket, so its perfect, thank you.

For backgorund in how we use warps, incase its helpful. I have about ~70 random warps for just staff POI that dont get sorted as its just there for our refreance if we need them, then we have a page of actual warps we want players to use in the GUI.

So now Ill just give all the actual warps we want players to see a slot, and the rest can just filter after!

**Comment by TomLewis** [comment]
Slight issue with whatever you did, a lot of the warps were duplicated... I will go through them all and delete, but, sigh.. thats gonna take a while.

**Comment by TomLewis** [comment]
![image](https://github.com/user-attachments/assets/a1632079-f7ce-43f1-a03e-771ec250e80d)
This is /warps, the page 1 that I set all the warp slots in.

This is the "next" page
![image](https://github.com/user-attachments/assets/1fa4b1eb-f076-4fb9-9ea0-2083a077894a)

The only differance is it puts that piston there, which is another warp set on a slot for page2.

its like the warps are being displayed twice that have slots on the first page and then in the same order for page2, which is weird, like the page number has been ignored and displayed twice.

**Comment by TomLewis** [comment]
@Zrips ping as this issue is closed, not sure if you get my later messages.

**Comment by Zrips** [comment]
Will be resolved with next update. And yea, it's just a visual duplication bug
