### ISSUE TITLE
MSPT 300+

### ISSUE THREAD

**Issue by GG-MD** [Zrips/CMI#9138]
### Description of Issue

https://spark.lucko.me/GXnYx3Hc50
This has never happened before, using the latest of all Zrips plugins. 

### Version Information

```shell
-
```

### Errors

```shell
Spark
```

### Relevant Config Sections

```yaml
-
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Try to run profiler for longer period to check if average stabilizes at generally low number, as that max is just a max, could have been one time hiccup. And check your set afk timer check interval, you can keep it relatively high, like every 15 seconds or even higher, as your profiler only points towards some weird spike when trying to get online player by provided UUID from a repeating scheduler, which generally takes negligible amount of time.
