### ISSUE TITLE
PotionSplashEvent error in console

### ISSUE THREAD

**Issue by Vehzx** [Zrips/CMI#9146]
### Description of Issue

Hi, randomly got this in my console, nothing seems broken though, just thought i'd report this.

https://pastebin.com/9gJk40X2

### Version Information

```shell
CMI 9.7.6.1 SqLite
CMILib 1.5.1.3
Server Paper(57) 1.21.1-R01-SNAPSHOT+
```

### Errors

```shell
https://pastebin.com/9gJk40X2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
