### ISSUE TITLE
Multi-server playtime synchronization(Bridge)

### ISSUE THREAD

**Issue by Probe4119** [Zrips/CMI#9148]
![image](https://github.com/user-attachments/assets/f9d93255-42fa-4e4c-a14c-1ef828d85aa0)
Hello CMI Advanced Plugin Author,

I currently manage multiple servers and need to synchronize player playtime across them. I have checked the TotalPlayTime data in the CMI database. Could you please explain why this data cannot be used as a basis for synchronizing playtime?
I am using MySQL as the database.

Thank you.

**Comment by Zrips** [comment]
This field is just basic reference when ti comes to offline players and their playtime, we are not using it as a main point of data, its secondary. And there is bigger complication in general to have data synchronized across multiple servers than just having it inside database. If you need playtime synchronization across multiple servers you will need more dedicated plugin for this task.
