### ISSUE TITLE
I can't sit! [latest CMI]

### ISSUE THREAD

**Issue by GG-MD** [Zrips/CMI#9150]
### Description of Issue

Unable to sit (/sit), in world “spawn”.
/sit etc..

### Version Information

```shell
latest
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by GG-MD** [comment]
and cmd /patrol not TABcomplete...

**Comment by Zrips** [comment]
Make sure that you don't have plugin in your spawn world which blocks armorstand spawning which can prevent sit animations.
For patrol command, its a command which randomly picks one of the online players, it doesn't have a player name support as you could just use teleport command for that. Additionally patrol picks one of the players while attempting to not repeat same player more than once before all players have been checked, so having specific player as patrol target defeats entire purpose of this command. 
Closing ticket for now as both issues are somewhat invalid. If you still experience issue with sit command in your spawn world and you don't have any plugin blocking armor stand spawning (test without any other plugin to be sure that its not interference from different plugin) then please make a ticket and include output from `/cmi version` command to get better idea what system you are running for better debugging.
