### ISSUE TITLE
TP protection interrupted by wind charges [CONTINUING]

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#9154]
### Description of Issue

Hello, I'd like to continue to this thread: https://github.com/Zrips/CMI/issues/9073

In the recent versions of WorldGuard they fixed the wind charges handling:
https://github.com/EngineHub/WorldGuard/issues/2097
https://github.com/EngineHub/WorldGuard/pull/2115
https://github.com/EngineHub/WorldGuard/commit/679b56948f41869bd545564a8c57562f157a6b66

But it still doesn't work when it comes to the grace mode, I thought it's because they check for the build flag, BUT knockback isn't enabled in pvp when using WorldGuard.

So I think that CMI doesn't properly set the worldguard pvp state, or maybe should disallow the knockback during the protection period like the worldguard does when the pvp is disabled?

The dev on these screenshots even recorded the video that wind charges can't be used when PVP is deny
![image](https://github.com/user-attachments/assets/88420a27-2e0c-45f1-916a-7e0150198a98)
https://github.com/user-attachments/assets/921cbfc0-1787-4275-84e1-dfc0f3bcfb05 #video
> yea...WG does prevent the knockback if pvp is denied...?

so I think that the issue is now within the CMI, as you previously mentioned in the comment that it should be solved by the area protection plugins in the previous thread.

Btw using the latest build of worldguard from here 
https://dev.bukkit.org/projects/worldguard/files/5707983
> Add wind-charge-burst flag which is checked along with `use` (for the interaction) or `pvp` (for the knockback).
Tested only with worldguard & CMI & tp protection after teleport and it's still happening, players can be knockbacked with the wind charge

### Version Information

```shell
[12:57:32 INFO]: --------------------------------------------------
[12:57:32 INFO]: CMI: 9.7.6.1 SqLite-> 9.7.6.2
[12:57:32 INFO]: CMILib: 1.5.1.0 -> 1.5.1.3
[12:57:32 INFO]: Server: Paper(2304) 1.21.1-R0.1-SNAPSHOT-
[12:57:32 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[12:57:32 INFO]: Modules -> 53 enabled 13 disabled: customMessages, mirror, tablist, skin, playerChatTag, disabledEnchants, chatBubble, ranks, firstJoinMessages, playerCombat, votifier, sitAnimation, namePlates
[12:57:32 INFO]: --------------------------------------------------
```

### Relevant Plugins

WorldGuard

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Well tested it with latest WG, basic region with pvp disabled, no knockback, warmup on teleportation is being processed correctly, you can shoot as many wind charges as you like, player remains in warmup state. CMI should not add knockback forces from wind charges, so maybe something else still allowing it to be triggered? I can't reproduce it at the moment. Best guess would be specific flag combination you have in your region which still allows that effect to be present.

**Comment by bobhenl** [comment]
Wait, but pvp shouldn't be disabled in region (it's just the classic basic global region without additional settings), I mean the player has PVP teleport invulnerability from CMI and can be attacked by this knockback


In fact I tested it without Worldguard & it happens even without it, when you just try to teleport & someone uses wind charge on you, you cannot teleport as it cancels warmup
![image](https://github.com/user-attachments/assets/768987f8-becb-4152-ac03-ac781ce5e4bd)


but the issue with teleport invulnerability is a bit bigger

Important settings:
```yml
    # Time in seconds player should be invulnerable after teleporting
    # This will prevent player who teleported to damage others for defined time
    # Set this to 0 if you want to disable it
    # Max 60 seconds
    Invulnerability: 15
```


and this under warmups list:
```yml
  - cmi spawn:5:false
 ```

@Zrips and you don't even need worldguard for this issue

**Comment by Zrips** [comment]
Not much I can do about this one. Wind charge creates push effect which doesn't trigger any special events which could be used to prevent player from being pushed around. While I could remove wind charge if it hits player directly in warmup mode, that doesn't resolve issue in general as you can still shoot at the foot of player. It doesn't even fire events like PlayerVelocityEvent, so I can't think of any actual real way to block wind charges at the moment without just out right removing them if those hit entity/block nearby someone in warmup mode. Its simpler to block with area protection plugins as you can actually check if wind charge can explode in area or not, but with warmup feature its left hanging. 
Closing ticket as I don't see any actual solution without server itself introducing special event or atleast including it into existing ones.
