### ISSUE TITLE
Money Take Alloffline

### ISSUE THREAD

**Issue by TylorTurner** [Zrips/CMI#9161]
### Description of Issue

/Money Take AllOffline amount
takes money from ONLINE players as well. 
All already takes it from online players

### Version Information

```shell
9.7.6.2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will make some changes relating to this variable usage with next update.
