### ISSUE TITLE
Players can use hex codes without permission

### ISSUE THREAD

**Issue by alfredcort** [Zrips/CMI#9165]
### Description of Issue

In chat, players are allowed to use a hex code to chat with colours, eg '#123456hello'. Players have no permission to use hex codes, so I believe this is a bug.

### Version Information

```shell
CMI: 9.7.6.2 SqLite-> 9.7.6.2
CMILib: 1.5.1.3 
Server: Paper(2304) 1.21.1-R0.1-SNAPSHOT+
CMI economy: Disabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 55 enabled 11 disabled: flightCharge, hpBossBar, tablist, ranks, votifier, headDrop, holograms, anvilRenameColor, jail, nightSpeedup, bossBarCompass
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update
