### ISSUE TITLE
Checkaccount is not working!

### ISSUE THREAD

**Issue by AshleyFOXXX** [Zrips/CMI#9167]
### Description of Issue

Whenever I do /checkaccount on the server with any players, it says "No information found!"

### Version Information

```shell
[12:35:01 INFO]: Server: Paper(149) 1.20.6-R0.1-SNAPSHOT-
[12:35:01 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[12:35:01 INFO]: Modules -> 64 enabled 2 disabled: tablist, ranks
```

### Errors

```shell
no errors
```

### Relevant Plugins

1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by AshleyFOXXX** [comment]
btw, no one is responding in your discord.

**Comment by Zrips** [comment]
Double check if you have IP recording (around line 304 in config.yml) enabled, as this will be needed to keep track who is who and what alternative accounts they might be using.

**Comment by AshleyFOXXX** [comment]
Thank you!
