### ISSUE TITLE
Custom Death Messages aren't sent to Discord using DiscordSRV

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#9170]
### Description of Issue

Hello, when using:
```yml
# Not all death situations might be included and future updates might be needed
# Report any missing death situation you encountered to github issue section with exact way to reproduce death situation
EnableCustom: true
```

then it doesn't send the Discord webhooks when using the DiscordSRV:
```yml
[22:50:26] [Craft Scheduler Thread - 8223 - DiscordSRV/INFO]: [DiscordSRV] [UNCATEGORIZED DEBUG] Not sending death message for XXX, the death message is null
```
as you see, it's null, the devs of the DiscordSRV told me:
> Whatever you're using to customize death messages is not compatible, they're improperly using the death event 

If you can at least allow sending the default MC messages to DiscordSRV it would be so good!

How to setup?
Use default configuration of DiscordSRV & just set the channel_id:
```yml
Channels: {"deaths": "CHANNEL_ID"}
```
in config.yml

### Version Information

```shell
[22:59:53 INFO]: --------------------------------------------------
[22:59:53 INFO]: CMI: 9.7.6.3 SqLite
[22:59:53 INFO]: CMILib: 1.5.1.0 -> 1.5.1.4
[22:59:53 INFO]: Server: Paper(2309) 1.21.1-R0.1-SNAPSHOT-
[22:59:53 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[22:59:53 INFO]: Modules -> 53 enabled 13 disabled: customMessages, mirror, tablist, skin, playerChatTag, disabledEnchants, chatBubble, ranks, firstJoinMessages, playerCombat, votifier, sitAnimation, namePlates
[22:59:53 INFO]: --------------------------------------------------
[22:59:54 INFO]: Cerebro2622 issued server command: /sethome a
```

### Relevant Config Sections

```yaml
# Not all death situations might be included and future updates might be needed
# Report any missing death situation you encountered to github issue section with exact way to reproduce death situation
EnableCustom: true
```

### Relevant Plugins

DiscordSRV

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
As of testing death messages looks to be working correctly with discordSrv, make sure that you have enabled 
```
  DiscordSRV:
    # Enables support for DiscordSRV plugin
    Enabled: true
```
in chat.yml file and that you have MinecraftPlayerDeathMessage setup in discordsrv messages.yml file. 
And to address `Whatever you're using to customize death messages is not compatible, they're improperly using the death event` cmi sets original death message to "" aka empty field as it needs to prevent showing vanilla message or any message in general and then sends new message to receivers in json format with hover over features and similar stuff which isn't supported by default PlayerDeathEvent, so we can't do it in a "correct" way, but we do have direct support for DiscordSRV plugin to trigger message manually.

**Comment by bobhenl** [comment]
Yeah it seems working, thanks. It just doesn't work with the https://www.spigotmc.org/resources/interactivechat-discordsrv-addon-show-items-and-invs-on-discord-preview-discord-images-in-game.83917/ to parse items there as well.

Do you think something like this can be fixed, too, please? @Zrips

**Comment by Zrips** [comment]
Well not at the moment, without direct support for specific plugin this would be pesky thing to resolve and I want to avoid having specific supports for specific plugins.

**Comment by bobhenl** [comment]
Mhm @Zrips and cannot it be added into CMI API? Maybe with it I can at least catch the event & resend it on Discord?
