### ISSUE TITLE
Holograms updates are not saved into the holograms.yml

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#9172]
### Description of Issue

Hello, it's been already a few months since this broken. I was using the CMI API to change the CMI hologram, and then it was automatically saved to the file, as well.

But now after the /cmi reload or restart, it's not saved & everything changed is lost.

Even when I use /hologram info <name>
it shows the updated hologram:
![image](https://github.com/user-attachments/assets/3df8ee63-e01c-40ef-8545-a9a51b3a77ff)
![image](https://github.com/user-attachments/assets/cb60a157-fab3-431c-8a8f-4cc932a689ed)

in the holograms.yml file is:
```yml
newsOnSpawn:
  Loc: world;0.5;128.09;5.5
  Range: 8
  RangeExtra: 16
  Lines:
  - '&b&lLatest News:'
  - '&r'
  - • Added reward for `/discord link`
  - • "Fixed issue where players were
  - loosing their original armor while using
  - PvPSword and joining Duels."
  - • Removed Dragon tag from tab
  - • Fixed broken placeholder in duels
  - • Added some missing special items
  - '&9> &fmore on our &9/discord'
  - '&r'
  - '&9> &fmore on our &9/discord'
```
and when I use /cmi reload then it loads the content from the file &  the progress made from API is lost. It started happening a few months ago with some holograms changes, it was working in the past.

Even the /hologram update doesn't work and it doesn't save the content to the file properly...

### Version Information

```shell
[14:04:29 INFO]: --------------------------------------------------
[14:04:29 INFO]: CMI: 9.7.6.3 SqLite
[14:04:29 INFO]: CMILib: 1.5.1.0 -> 1.5.1.4
[14:04:29 INFO]: Server: Paper(2310) 1.21.1-R0.1-SNAPSHOT-
[14:04:29 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[14:04:29 INFO]: Modules -> 53 enabled 13 disabled: customMessages, mirror, tablist, skin, playerChatTag, disabledEnchants, chatBubble, ranks, firstJoinMessages, playerCombat, votifier, sitAnimation, namePlates
[14:04:29 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
As indicated in `https://www.zrips.net/cmi/api/` do you trigger `CMI.getInstance().getHologramManager().save();` for it to actually save holograms into file? As it will not do it by default
