### ISSUE TITLE
Placeholder for rankups

### ISSUE THREAD

**Issue by Minichander** [Zrips/CMI#9173]
are a placeholder to show the rankup of the player?

**Comment by Zrips** [comment]
%cmi_user_rank%
%cmi_user_rank_displayname% – Current rank display name
%cmi_user_rank_name% – Current rank name
%cmi_user_nextranks% – List of next ranks
%cmi_user_nextrankpercent% – Percentage done for next rank
%cmi_user_nextvalidranks% – Rank list to which player can rank up to
%cmi_user_canrankup% – Returns true if player can rank up
These would be for base player rank information. You can always check available placeholders at [https://www.zrips.net/cmi/placeholders/](https://www.zrips.net/cmi/placeholders/)
