### ISSUE TITLE
Holograms: Line separators are being displayed as ␊ on older versions

### ISSUE THREAD

**Issue by CertifiedGlowie** [Zrips/CMI#9174]
### Description of Issue

I would like to make fancy modern holograms but i also want them to be compatible with players playing from older versions using ViaBackwards. However they can't see the holograms properly because new holograms use different line-encoding. Here's a visual demonstration:

**1.19.4+**
![image](https://github.com/user-attachments/assets/5dd3a29f-b915-40cb-8867-8ff99749a9e1)

**1.19.3-**
![image](https://github.com/user-attachments/assets/f69be7e8-f918-4398-bf17-9f1f668ef4f2)

### Version Information

```shell
CMI: 9.7.6.3 SqLite
CMILib: 1.5.1.4
Server version: Paper 1.21.1-R0.1-SNAPSHOT
```

### Relevant Plugins

ViaBackwards

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Holograms should be saved with, well, ingame editor, where each line contains single line in hologram, or appropriately saved manually in the file. While new line ␊ thing works few new display method, it will be shown as it is on the old one, so it would need appropriate adjustment from the user side based on which method is being used. While automated method could be made to account for things like that, it's really tiny benefit for extremely narrow use case with somewhat big chunk of the code to appropriately update data structure internally which could account for it. At the moment this won't get a fix unless there will be good point raised why it should be.
