### ISSUE TITLE
Disable chat module feature

### ISSUE THREAD

**Issue by kn-km** [Zrips/CMI#918]
**Description of issue or feature request:**

> I didn't see anything about disabling CMI's chat system in the config file.
> How to do that?
> I'm using other chat plugin.

---

From @LogGits: We should have:
```yaml
Enabled: true
```
This feature should be in cmi for all major modules. Particularly, cmi's chat module. This will make it easier to disable all the features within the chat module.

**Comment by 0xC1A551C** [comment]
yes I want this too
