### ISSUE TITLE
Custom text alias command opens the file list instead of the file itself

### ISSUE THREAD

**Issue by DarkKingKaan** [Zrips/CMI#9186]
### Description of Issue

When using `<AutoAlias>` (as described in the [documentation](https://www.zrips.net/cmi/custom-text/#:~:text=%3CAutoAlias%3E%20%2D%20If%20the%20filename%20is%20meow%2C%20automatically%20creates%20a%20/meow%20command%20that%20shows%20this%20document)) in a custom text configuration, trying to open the file with the alias command, the plugin displays a clickable list of custom text files instead of the file itself.

For example, here's my discord.txt file:
```
<AutoPage><AutoAlias><NoReqPermission>
&7Join our Discord: https://discord.myserver.com
```

When trying to use the `/discord` command in-game, I would expect it to open the discord.txt file and display the text, however, the plugin does this - it opens a list of all custom text files instead of the file itself:
![image](https://github.com/user-attachments/assets/0ee5828d-c41d-44f1-a897-36483f0482af)

### Version Information

```shell
9.7.5.4
```

### Errors

```shell
No errors.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
