### ISSUE TITLE
sometimes player can't send whisper message through server until restart.

### ISSUE THREAD

**Issue by Ecilpse** [Zrips/CMI#9187]
### Description of Issue

sometimes player can't send whisper message through server until restart.

### Version Information

```shell
cmi 9.7.6.3
cmilib 1.5.1.4
cmivelocity 1.0.1.2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Does /server list command correctly report player counts on both servers when trying to send message? As does sender or receiver needs to relog for whisper to start working?
