### ISSUE TITLE
[Issues] little missing TabComplet in dye

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#919]
![image](https://user-images.githubusercontent.com/12080017/46536367-8ec5ea00-c8ae-11e8-9a47-61f5ea34cab8.png)

**/cmi dye biome**

The Tabcompletation for biome is missing :)
![image](https://user-images.githubusercontent.com/12080017/46536414-b917a780-c8ae-11e8-89fb-9d6485b60392.png)

but you can use **/cmi dye biome** then it works as aspected :)

**Comment by LogGits** [comment]
Great catch 👍

**Comment by Zrips** [comment]
Fixed
