### ISSUE TITLE
itemcmdata delete does not remove custom model data from an item

### ISSUE THREAD

**Issue by MadeBySaints** [Zrips/CMI#9196]
### Description of Issue

As said in the title. The /itemcmdata delete command does not remove custom model data from an item. /itemcmdata set work to add custom model data to an item, but you cant remove it. Also when using /itemcmdata list, it does not list custom model data. You can only view it with /iteminfo or /itemnbt.
![{BCF49EC7-2D8A-4A9D-A333-95D63A86BDDD}](https://github.com/user-attachments/assets/8e91ce96-e685-43c8-b481-ed8c8b2d0df2)

### Version Information

```shell
[23:36:17 INFO]: CMI: 9.7.6.4 SqLite
[23:36:17 INFO]: CMILib: 1.5.1.4
[23:36:17 INFO]: Server: Paper 1.21.1-R0.1-SNAPSHOT+
[23:36:17 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
[23:36:17 INFO]: Modules -> 66 enabled 0 disabled:
```

### Errors

```shell
N/A
```

### Relevant Config Sections

```yaml
N/A
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next build
