### ISSUE TITLE
CMI PlayerCommandPreProcessEvent not working

### ISSUE THREAD

**Issue by BobbyZe1606** [Zrips/CMI#9198]
### Description of Issue

*Describe the bug*    
For any CMI commands, if I were to add in the chat quest to type a cmi command, it does not progress with the quest. But other non CMI commands such as /summon it works and the quest progresses. 

*Reproduction*
Create a quest that needs a cmi command to be typed in the chat

*Screenshots, error messages*
No error messages in console.
![image](https://github.com/user-attachments/assets/22d19749-775e-4edc-85b0-cde65cf272ad)

*Software*
BeautyQuests version: 1.0.3
Game version: 1.20.1
Server version: 1.20.1
Server type (e.i. PaperSpigot): Bukkit, Spigot
Are you using a protocol hack (like ViaVersion): No

*Additional context (optional)*

### Version Information

```shell
9.7.4.8
```

### Errors

```shell
No errors
```

### Relevant Plugins

BeautyQuests 1.0.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
This looks like to be caused by somewhat confusing usage. When it comes to alias commands you should use the full one instead of alias, so instead of checking for /rankup check for /cmi rankup which should solve your issue
