### ISSUE TITLE
Stainted Glass Pane in the GUIs on the new version and was not on the 9.7.6.4

### ISSUE THREAD

**Issue by marcelofrau** [Zrips/CMI#9206]
### Description of Issue

hello CMI team.. I just updated to the latest version of CMI, (was on 9.7.6.4) and I just noticed it broken some of my GUIs because now it is filling the empty blocks with stained_gray_glass and before it was empty, this ruined the custom guis I have added with ItemsAdder, can all the empty blocks be empty instead of putting a glass panel on them? let me put both guis here, with no change in any config, it got from the empty to the full of glass (attached both ./kits gui)

9.6.7.4:
![image](https://github.com/user-attachments/assets/22e3c4b8-6bbe-4b49-a1bb-bf0655ef6514)

9.6.7.5:
![image](https://github.com/user-attachments/assets/64c4f52e-01a7-4b2d-9532-29b54070c10b)

### Version Information

```shell
9.7.6.5
```

### Relevant Plugins

Vault 1.7.3, ItemsAdder_4.0.2-beta-release-12

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be addressed with next update
