### ISSUE TITLE
Cmi clear command

### ISSUE THREAD

**Issue by TylorTurner** [Zrips/CMI#9214]
### Description of Issue

/Clear command does not clear shield or off hand item. II am trying to clear an offline player 

### Version Information

```shell
9.7.6.3
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Using something like **/clear zhax +offhand** will clear off hand item from the player
