### ISSUE TITLE
SOS!🆘 KICKED ALL PLAYERS (homes)

### ISSUE THREAD

**Issue by GG-MD** [Zrips/CMI#9215]
### Description of Issue

Hi. There’s a terribly serious bug. When players teleport to their home point, the anti-cheat kicks them. Fix this problem urgently. This is a disaster. @zrip

### Version Information

```shell
Latest
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by GG-MD** [comment]
[13:44:22 INFO]: --------------------------------------------------
[13:44:22 INFO]: Версия плагина CMI: 9.7.6.6 SqLite-> 9.7.6.7
[13:44:22 INFO]: CMILib: 1.5.1.4 
[13:44:22 INFO]: Версия сервера: Purpur(2321) 1.21.1-R0.1-SNAPSHOT-
[13:44:22 INFO]: CMI Экономика: Вкл Версия Vault: 1.7.3-CMICMI Чат: Выкл 
[13:44:22 INFO]: Модули -> 32 включено 34 отключено: spawnerProximity, cuffed, customMessages, mirror, tablist, armorEffects, moneyCheque, skin, elytraBoost, rideAnimation, elytraLaunch, bossBarCompass, coloredArmor, elevator, chatBubble, votifier, shulkerBackpack, attachedCommands, spawnerCharge, interactiveCommands, namePlates, timedCommands, hpBossBar, anvilRenameColor, jail, paintingEditor, dynamicSigns, playerChatTag, durabilityLoss, deathMessages, disabledEnchants, worldLimitsElytra, ranks, silentChest
[13:44:22 INFO]: --------------------------------------------------


ℹ️ 

I’ve rolled the plugin back to the previous version, from the newest, current, latest one, but that doesn’t help either.

**Comment by GG-MD** [comment]
@Zrips 
![IMG_1738](https://github.com/user-attachments/assets/1bd855c2-c27b-4a45-8cea-dda2793f36e7)

**Comment by GG-MD** [comment]
@Zrips 

`c:
enabled: false
punishable: true
discord-alert-interval: 1
broadcast-punishment: false
max-violations: 2
alert-interval: 1
 dont-alert-until: 1
maximum-ping: 7500
minimum-tps: 19.0
punishment-commands:
 - minecraft:kick %player% §cНелегальное преимущество §7→ §8(BadPackets-C)
 d:`

**Comment by Zrips** [comment]
Without knowing what anticheat you have and what setup is present for the specific players its really hard to determine cause. Best guess would be to check if you have enabled this option in config.yml
```
    # When this set to true each time player teleports to any destination he will be teleported to spawn point
    # This is to prevent from people knowing to which direction you have teleported too
    # As everyone noticed, teleportation doesnt actually teleport you, but moves to targetdestination in short time
    ToSpawnBefore: false
```
which sends player, briefly, to spawn point and then sends him to his destination, other than this it should be generic teleportation

**Comment by GG-MD** [comment]
> Without knowing what anticheat you have and what setup is present for the specific players its really hard to determine cause. Best guess would be to check if you have enabled this option in config.yml
> 
> ```
>     # When this set to true each time player teleports to any destination he will be teleported to spawn point
>     # This is to prevent from people knowing to which direction you have teleported too
>     # As everyone noticed, teleportation doesnt actually teleport you, but moves to targetdestination in short time
>     ToSpawnBefore: false
> ```
> 
> which sends player, briefly, to spawn point and then sends him to his destination, other than this it should be generic teleportation

Vulcan anti cheat (latest.)

Yeah, it's set to true, but there were no issues before. Which is really strange.
<img width="953" alt="image" src="https://github.com/user-attachments/assets/b088f26d-2d1d-41d9-bb5a-098230fa6b00">

**Comment by Zrips** [comment]
Something could have happen with Minecraft server itself which caused it to start breaking that anticheat check, or anti cheat made some small changes which tipped over this check, but CMI didn't really done any changes relating to this specific option for some time now.
Will make some changes with next version, if issue persists, let me know. Closing ticket for now.
