### ISSUE TITLE
Problems with hat duping using CMI and cosmetic plugins.

### ISSUE THREAD

**Issue by Sculmix** [Zrips/CMI#9217]
### Description of Issue

I use MagicCosmetics(I also tried using alternatives, including...) and CMI. If I have CMI installed on my server, when wearing a helmet from MagicCosmetics, the regular helmet duplicates when I try to take it off. 

When using CMI alternatives like Essentials/SunLight, such problems do not occur.  
@FrancoBM12 - MagicCosmetics Dev

https://github.com/user-attachments/assets/73b0528f-511d-4438-bcf6-9f98e9e4074d

### Version Information

```shell
9.7.6.7
```

### Relevant Plugins

MagicCosmetics 3.0.8, CmiLib 1.5.1.4

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Sculmix** [comment]
> Tested version 2.9.8 on 1.20.4 as I don't have access to the latest version, but in any case, on this version even having only MagicCosmetics without any other plugin it will duplicate hat item in creative mode constantly. So there is a fundamental issue of some sorts going on here, duno if this was addressed with later versions, will need normal access to latest version to do more appropriate tests to be sure that its related to CMI and isn't general issue with MagicCosmetics as there is definitely one in 2.9.8


For some reason, the problem lies specifically in survival mode. When I have a cosmetic hat on my head and I put on a helmet, when I try to remove the helmet, it duplicates. This happens only when CMI is installed along with any cosmetic plugin with hats (HMCCosmetics, MagicCosmetics, CosmeticsCore). When CMI is absent, these plugins work correctly. Maybe this occurs due to how CMI handles the head slot in the inventory; is it possible to disable these 'handlers' somehow?

**Comment by Sculmix** [comment]
> What config option do you have set for hat handling in config file?

I apologize, I may not have expressed myself correctly.

What I meant was, in principle, the processing of the head slot in CMI. Is there a way to turn it off? So that CMI does not interact with this slot at all?

**Comment by Sculmix** [comment]
> Well now I apologize for not being clear. Was asking for your config.yml setup just to have same one for testing, in case its related to specific configuration. And to answer to your question, at the moment there isint specific one, but will add with next update where you will be able to switch it off in modules.yml, still, need to figure out whats causing this issue and if it can be fixed it needs to be fixed

My config.yml - https://pastebin.com/c9UbB08S

**Comment by FrancoBM12** [comment]
Hey @Zrips  I can give you access to the plugin with no problems so you can figure it all out with peace of mind!

I'll just need your Polymart or BuiltByBit username to give you access to download the plugin.

**Comment by FrancoBM12** [comment]
> @FrancoBM12 My username remains all the same Zrips in all places if its not taken, polymart or BuiltByBit, any will be fine as I have accounts on both of those with same user name

There you go, check your Polymart account please, I hope this.

**Comment by Sculmix** [comment]
Hi @Zrips. How's the progress?

**Comment by Zrips** [comment]
@Sculmix 
Sorry, was somewhat busy with 1.21.3 update. Reproduced issue, will do more debugging and new fixed version should come out today.
