### ISSUE TITLE
Interactive commands deletes location data in config.

### ISSUE THREAD

**Issue by vkolasa** [Zrips/CMI#9219]
### Description of Issue

Interactive Commands:
Commands bound to a block get deleted after use. It is deleting the location data in the config file but none of the other information.
please observe the attached video of incident. 
https://youtu.be/X6vZU6XqJuE

Refered to report here on GitHub by Floris

### Version Information

```shell
CMI: 9.76.7
CMI Lib: 1.5.1.4

Server: 1.21.1-120 Paper
```

### Errors

```shell
N/A
```

### Relevant Config Sections

```yaml
Interactive Commands Config:

"Location" of interactive command blocks removes itself on usage.
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mercurialmusic** [comment]
Confirming. Any sort of block state update seems to remove the location, I'm guessing after the changes in 9.7.6.6. We had lots of previously stable ICs suddenly break. 

CMI plugin version: 9.7.6.7 SqLite
CMILib: 1.5.1.4 
Server: Paper(120) 1.21.1-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
Modules -> 64 enabled 2 disabled: ranks, skin

**Comment by Zrips** [comment]
This will be fixed with next update.
