### ISSUE TITLE
Resetting random tickspeed?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#9220]
Hello, is it possible that gamerule for tickspeed is resetting? Cannot it be caused when the gamerule GUI changed or so? It's a bit strange as I haven't experienced it before, and now it happened for the second time, not sure if there can be the plugin affecting it.

**Comment by Zrips** [comment]
Does it happen while modifying game rules with GUI or with command or randomly at some moment in time? As CMI will not modify tickspeed in any case, it would only change doDaylightCycle for time command or time control in general, but this is the only thing which will be modified by CMI, so it would be triggered either by manually triggering cmi gamerule command or by another plugin entirely

**Comment by bobhenl** [comment]
Oh I think it would be caused by another plugin than. Thanks for response
