### ISSUE TITLE
Home teleportation error. [latest]

### ISSUE THREAD

**Issue by GG-MD** [Zrips/CMI#9223]
### Description of Issue

The issue is that the player is teleported to the correct coordinates, but the YAW is incorrect, and the player's head is constantly looking upwards.

### Version Information

```shell
-
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update, yaw and pitch got inverted

**Comment by GG-MD** [comment]
> Will be fixed with next update, yaw and pitch got inverted

not fixed..
