### ISSUE TITLE
Bug in /recipe [latest]

### ISSUE THREAD

**Issue by GG-MD** [Zrips/CMI#9226]
### Description of Issue

The crafting of the Enchanted Golden Apple was available in the game until version 1.8, but for some reason, it remained available in all subsequent versions as well. Moreover, if you disable the crafting of this item using `/recipe`, it will remain disabled only until the server restarts—after the restart, it becomes available and functional again. I request a review of this crafting recipe and for this bug to be fixed.

### Version Information

```shell
-
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Which server version are we talking about here? And recipe disabling would only apply to recipes which are registered by something, double check if you don't have custom recipe set for it or that there isn't another plugin adding it later on. At the moment on 1.21 only single recipe is being recognized as valid one for enchanted apples which would be paper and apple, resulting into special Mojang banner

**Comment by GG-MD** [comment]
> Which server version are we talking about here? And recipe disabling would only apply to recipes which are registered by something, double check if you don't have custom recipe set for it or that there isn't another plugin adding it later on. At the moment on 1.21 only single recipe is being recognized as valid one for enchanted apples which would be paper and apple, resulting into special Mojang banner

Thank you so much, it turned out to be the DeluxeCombat plugin, terrible! Thanks!
