### ISSUE TITLE
Denizen NPC chat triggers fire in public chat even when disabled

### ISSUE THREAD

**Issue by calaritooo** [Zrips/CMI#9228]
### Description of Issue

Denizen NPC chat triggers that would normally be cancelled and not sent in public chat **are** sent in public chat when CMI is activated. Upon removing CMI, the chat triggers work properly and do not display in public chat. Random example of dialogue:

"Hello <player>. Do you want to *rank up* or see the *shop*?"
Player: shop
"No problem. Here it is.."

Normally in this dialogue, and as disabled by my denizen scripts, the player's response would not display in public chat. Even with CMI's lowest priority set on its chat listener, this problem persists and is only resolved when removed entirely. I've notified the denizen team and it seems that CMI is creating the issue..

Thanks!

### Version Information

```shell
CMI: 9.7.6.8 SqLite
[07:01:05 INFO]: CMILib: 1.5.1.5 
[07:01:05 INFO]: Server: Paper(56) 1.21.1-R0.1-SNAPSHOT+
[07:01:05 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[07:01:05 INFO]: Modules -> 44 enabled 23 disabled: spawnerProximity, hpBossBar, mirror, elytraBoost, spawners, cmiPlaytime, paintingEditor, eventCommands, playerChatTag, elytraLaunch, durabilityLoss, bossBarCompass, flightCharge, deathMessages, schedule, chatBubble, ranks, votifier, shulkerBackpack, decoratedpot, spawnerCharge, warmup, timedCommands
```

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Have you tried disabling CMI chat handling? Go to chat.yml file and disable hoverOver or both options at the start of that file. Alternatively you could try shifting listener to HIGH or HIGHEST priority. Will do some testing to figure out exact cause, but message should not be sent to anyone if recipient list is empty, which should be done by Denizen plugin at LOWEST listener priority, in that case no one would receive any messages even with CMI chat enabled.

**Comment by calaritooo** [comment]
Resolved the issue with it displaying in public chat by setting the priority to HIGH. The messages are still sent to DiscordSRV however, I assume this is a problem I should take over there though?

**Comment by Zrips** [comment]
If you disabled DiscordSRV support and it still shows up in discord, then yes, it would be an issue on their side. Closing ticket for now.
