### ISSUE TITLE
[Bug] Importing warp from essentials, it will broke warp saving on yml

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#923]
I just runned /cmi importfrom essentials warp, and doin /warp i can see the warps, but when i restart the server all warps will gone. Also if save other warps after it.
This happen only after i execute that command.

**Cmi Version (using`/cmi version`):** 
8.0.19
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.8.8

**Comment by LogGits** [comment]
>  Also if save other warps after it.
What do you mean by this, do the newly created warps also get deleted? Also are you using mysql or sqlite?

**Comment by xion87** [comment]
nope i just imported the data from essentials, see the file warp yml still empy. restarting the server will stay empy and no warps

**Comment by CloudeLecaw** [comment]
https://github.com/Zrips/CMI/issues/923

**Comment by mrfloris** [comment]
This bug, together with a couple of others, prevents us from upgrading from 7 to 8, and ditching EssentialsX and finally upgrade to 1.13.2

So this is a friendly bump. I've tried various ways to run this successfully, but a lot of commands lately seem to actually lose the data when you /stop the server and start it again.
