### ISSUE TITLE
Logout message when entering the server in Vanish Mode.

### ISSUE THREAD

**Issue by MeisterVox** [Zrips/CMI#9236]
### Description of Issue

I have Vanish mode active when logging in and the fake notifications are on. Every time I enter the server it writes the message that I have left the server.
![Screen 01](https://github.com/user-attachments/assets/e9c87678-649b-442a-b179-d734157fee82)
![screen 02](https://github.com/user-attachments/assets/61f3be89-ffe7-4bc4-a090-ef8570a5afe9)

### Version Information

```shell
[20:28:44 INFO]: CMI Plugin Version: 9.7.6.10 SqLite-> 9.7.6.11
[20:28:44 INFO]: CMILib: 1.5.1.5 -> 1.5.1.6
[20:28:44 INFO]: Server: Paper(122) 1.21.1-R0.1-SNAPSHOT+
```

### Errors

```shell
Nothing
```

### Relevant Config Sections

```yaml
I don't know
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
This was fixed a bit ago, try upgrading. Check spigot for the latest cmi and cmilib, /stop and upgrade jars after a backup of your server and start it up, see if you still have the issue.

**Comment by MeisterVox** [comment]
I'll check it out and let you know.

**Comment by MeisterVox** [comment]
![fail](https://github.com/user-attachments/assets/33da8863-a618-41e3-b8af-77e0415fd96a)
![paper](https://github.com/user-attachments/assets/399baabf-2191-47ae-8e43-7be3a1b53740)

Unfortunately, the current status is that the logout message is written to Active Vanish when logging in. So the error still exists.

**Comment by mrfloris** [comment]
Bummer, thanks for testing. Hopefully, zrips has some extra info for you

**Comment by Zrips** [comment]
Should be fixed with next update
