### ISSUE TITLE
/head doesn't work for Bedrock players

### ISSUE THREAD

**Issue by alfredcort** [Zrips/CMI#9246]
### Description of Issue

giving a player their head with /head <playername> <playername> works fine for Java players, however trying to give a head to a bedrock player (GeyserMC, with the " . " prefix) simply doesn't work, they get the default Steve skin.

I've asked about it in the discord server several times without a response.

### Version Information

```shell
CMI: 9.7.6.11 SqLite
CMILib: 1.5.1.6 
Server: Purpur(2315) 1.21.1-R0.1-SNAPSHOT+
CMI economy: Disabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 57 enabled 10 disabled: flightCharge, hpBossBar, tablist, ranks, votifier, holograms, anvilRenameColor, jail, nightSpeedup, bossBarCompass
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Issue would be with players name, having . in their name makes it invalid and that breaks things, mainly lookup of their skin as valid minecraft names can't have . which results in error and nothing happens. Do you experience similar issues with other commands or is this only with skins?

**Comment by alfredcort** [comment]
> Issue would be with players name, having . in their name makes it invalid and that breaks things, mainly lookup of their skin as valid minecraft names can't have . which results in error and nothing happens. Do you experience similar issues with other commands or is this only with skins?

Pretty much all other commands work fine when it comes to Bedrock players (eg /pay, /tpa). So far I've only found this setback when it comes to Bedrock players. It's no massive issue but bedrockers do feel a bit left out not being able to retrieve their heads like java players can.

**Comment by Zrips** [comment]
Ok, should be resolved with next CMILib update which should come out today
