### ISSUE TITLE
Adding space after color in /itemlore causing bug

### ISSUE THREAD

**Issue by szarkans** [Zrips/CMI#9274]
### Description of Issue

1. Type `/itemlore &9 Any text`, specifically with space after color code
2. Notice that you have new 9 empty lines of lore and wrong color 

### Version Information

```shell
CMI: 9.7.7.5 SqLite
CMILib: 1.5.2.1
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
try `/cmi itemlore 1 &9 Any text`

**Comment by Zrips** [comment]
Doesn't look like a bug as of testing. Your provided example will properly insert new lore line and it will only apply those colors for that line. Closing for now. If you still experience some issues, please provide output from /cmi version and some images showing how it looks for you to have better idea of what's going on.
