### ISSUE TITLE
[URGENT] CMI 9.7.7.6 doesn't work in 1.21.1

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#9278]
### Description of Issue

Hello,
I've updated CMI & CMILib to the latest version, but the plugin crash in the 1.21.1 version.

### Version Information

```shell
-
```

### Errors

```shell
https://mclo.gs/CwnLOdz
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by NoltoxGit** [comment]
@Zrips

**Comment by Zrips** [comment]
Update which will resolve this issue. More work will be done to get better support with next one.
