### ISSUE TITLE
In translations, locale_xx.yml - not working [time], allways empty result

### ISSUE THREAD

**Issue by smscentras** [Zrips/CMI#9284]
### Description of Issue

In translations, locale_xx.yml - not working [time], allways empty there.

info:
  Cooldowns: '&eThis command is on cooldown for another &6[time]'

### Version Information

```shell
CMI 9.7.7.8
CMILib 1.5.2.2
Server: Purpur(2311) 1.21.1
```

### Errors

```shell
none
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Any errors in console? And are we talking about base EN translation file or custom one?

**Comment by smscentras** [comment]
> Any errors in console? And are we talking about base EN translation file or custom one?

No errors in console. Message in chat without time. LT translation file.
