### ISSUE TITLE
Missing locale for command.jailedit.info.collides

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#929]
I'm had trouble setting up the jails. I wanted to define 2 jails.
So I thought I could set up 2 separate jails.

When I tried to define the second jail, it gave the error:
`Missing locale for command.jailedit.info.collides`

So I figured out the solution was to define 1 jail with 2 cells.

Anyway: This line line is missing in the locale and this could help others to figure out how to properly set jails.

**Comment by x1p** [comment]
Btw: manually adding this line won't fix this, because this line is deleted every time.

**Comment by x1p** [comment]
Bump: Still not fixed
The description should be something like:
```
      collides: '&cConflicts with another jail area (&6[jail]&e)'
```

**Comment by Zrips** [comment]
Will be fixed with next build
