### ISSUE TITLE
CMI effects tab complete of commands for other plugins (MyWorlds)

### ISSUE THREAD

**Issue by jonathanpublic** [Zrips/CMI#9292]
I use a plugin called MyWorlds for my hub server for different worlds and game types. When I install CMI it seems to break tab autocomplete for the commands of that plugin.

Example command"
/mw spawn "nameofworld"     _(to allow me to manually tp to that worlds spawn)_

Before CMI install, I get a tab list of worlds that show up for autocomplete. After CMI install it breaks tab auto complete for that command. I don't know why CMI is affecting commands for other plugins. 

I looked on the CMI Wiki and doesn't seem to be any commands in CMI under /mw.

I also ran a test. I uninstalled the MyWorlds plugin and installed CMI on it's own and tested the commands to make sure CMI didn't have commands with that alias that were unlisted. I tried the following commands...

/mw
/mw spawn
/mw spawn "worldname"

All of those commands were completely unrecognized and denied with just CMI installed. Having just MyWorlds installed the commands work just fine as you'd expect. But when I installed CMI while MyWorlds is also installed, somehow CMI breaks auto complete for my MyWorlds commands.

Is there a way to fix this?

**Comment by jonathanpublic** [comment]
I tested this on a clean server, with clean installs of both plugins and I'm still running into the issue. Everytime I install CMI and MyWorlds together, CMI seems to break tab autocomplete for MyWorlds commands.

**Comment by Zrips** [comment]
Try disabling alias for `/cmi world` command in CMI alias.yml file as it looks like MyWorlds plugin uses /world command as its basis for /mw so alias gets overridden
