### ISSUE TITLE
tamed animal with tamer-rank

### ISSUE THREAD

**Issue by Leahcimkrob** [Zrips/CMI#9295]
I don't know what to do anymore, maybe someone here can help. As soon as we tame an animal and rename it, the rank of the person who tamed the animal appears before it. Does anyone know where this comes from and how we can avoid it?

**Comment by Zrips** [comment]
Its how vanilla minecraft handles tamed entities in general, if owner has prefix or suffix then those will be added to the animals name and its mostly happens client sided as entity itself (you can check with /cmi entitynbt command) doesn't contain information like that. CMI isn't related here and you might need special plugin with specific feature to change entities names to not include things like that
