### ISSUE TITLE
Major issue with /msg causes lag spike of 40/50 seconds

### ISSUE THREAD

**Issue by iaxedu** [Zrips/CMI#93]
I've been having major random lag spikes which makes everyone disconnect. At first, I couldn't find the cause but after running massivelag I was able to find it.

TacoSpigot-"bf023c7d" (MC: 1.8.8)
CMI v7.3.18.0

[https://hastebin.com/ijivuxivol.md](https://hastebin.com/ijivuxivol.md)

[https://hastebin.com/lewocovogo.md](https://hastebin.com/lewocovogo.md)
Another example without massivelag

**Comment by Zrips** [comment]
Will do some optimization, for time being try disabling bungeecord messaging in config file.

**Comment by iaxedu** [comment]
`  # Do you want to enable private messaging over bungeecord
  BungeeMessages: false`

You mean this? I already have that disabled :/

**Comment by Zrips** [comment]
Hmmm, so you are running bungeecord network? Are you using portals over bungeecord?

**Comment by Zrips** [comment]
And, do you running plugin like ViaVersion?

**Comment by iaxedu** [comment]
I don't use CMI portals if you mean that.

I do use ViaVersion and ViaBackwards both latest versions

**Comment by Zrips** [comment]
Well this narrows down possible issues, as there are quite few reports about packet limitations and errors you are getting while using ViaVersion. Try adjusting packet limits for ViaVersion in config file. Other than this, will do some optimizations, but as i don't really have a clue hat could directly cause this issue from CMI i will shoot in a dark hopping to help in fixing this issue.

**Comment by iaxedu** [comment]
Um, that packet thing is unrelated to the cause of the lag spike. They get kicked because of the packets coming all at once after the lag spike.

The first link show they timeout, it's that or the other.

Here it happens after using pay (I use this as an alias) [https://hastebin.com/imiqegixiy.md](https://hastebin.com/imiqegixiy.md)

And here there is one with messages again: [https://hastebin.com/utomivulez.md](https://hastebin.com/utomivulez.md)

**Comment by Zrips** [comment]
Will address lag spike, as there was some offline player requests from mojang servers in some situations what could cause lag spike.

**Comment by LogGits** [comment]
@iaxedu any news on this? Are you still having issues with /msg?

**Comment by iaxedu** [comment]
So far so good seems fixed 👍
