### ISSUE TITLE
When pressing Q to change the name of the armor stand, it causes that no message can be sent out.

### ISSUE THREAD

**Issue by yyhhkya** [Zrips/CMI#9304]
### Description of Issue

When pressing Q to change the name of the armor stand, it causes that no message can be sent out.

### Version Information

```shell
CMI版本:9.7.6.7 SqLite-> 9.7.7.10
CMILib版本:1.5.2.1-> 1.5.2.2
服务器版本:Folia 1.20.6-R0.1-SNAPSHOT-
CMI经济系统:已启用Vault版本:1.7.3-b0-folia(CMIEInjector)CMI聊天系统:已启用
模块 -> 63 已启用 3 已禁用:tablist, votifier, skin
```

### Errors

```shell
https://mclo.gs/nOLS1NL
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
