### ISSUE TITLE
Ordering groups in the tablist

### ISSUE THREAD

**Issue by Roy416** [Zrips/CMI#931]
**Description of issue or feature request:**

I couldn't find anywhere on how to order players by rank on the tablist. Would be super useful if you could add this, would save us adding another tab list plugin

**Comment by LogGits** [comment]
A feature like this would be awesome! Thanks for the suggestion :+1:

**Comment by Getblock** [comment]
Please implement this... i would hate adding another tab list plugin when cmi already has one.

**Comment by LuisGVE** [comment]
Please implement this

**Comment by ConfuseN** [comment]
Please add this!

**Comment by x1p** [comment]
Please please implement this sorting in any form, rank, permission, whatever.

**Comment by FestusDM** [comment]
This is a good feature, definitely. Hope it can be implemented soon.

**Comment by Skyfighter1** [comment]
Pls add this....

**Comment by Skyfighter1** [comment]
@Zrips pls this... so much people want see that feature since 8 month

**Comment by Zrips** [comment]
It is nice feature, but it is one of those more complex ones to handle. Its all based on packets and manipulations on player list to your own liking. I did some experimenting with it, got it working, more or less. Still need to find some time to sit down and finish it up to be in decent condition which will allow sorting and stuff. 
I'm one guy, don't expect from me to add every possible feature, i'm not a superman after all.

**Comment by FestusDM** [comment]
It is a nice feature and yes, understandable with complex tasks to handle. Complete understandable that you are waiting for completion before release. 

If you don't hear it enough, know that we appreciate the work you're doing. Thanks 😄

**Comment by bartyrealms** [comment]
We are also looking forward to this feature. Any updates on this?

**Comment by Skyfighter1** [comment]
Pls add this so much want this^^

**Comment by Skyfighter1** [comment]
Any news?

**Comment by Vehzx** [comment]
Any updates on this? Would love to be able to use this, sorting based off permissions would be great too

**Comment by 4c5458** [comment]
My advice: don't wait for this and look for a real alternative.
TAB reborn is a well maintained tab sorting plugin with all of the requested functionality. This plugin exist for quite a long time and is performing very well and uses very little resources.
CMI is not a "one size fits all" plugin. There are many requests, more than the dev can handle.

**Comment by Vehzx** [comment]
Will look into it, ty
