### ISSUE TITLE
[!] /kit - has armor slots calculation problem

### ISSUE THREAD

**Issue by smscentras** [Zrips/CMI#9311]
### Description of Issue

Plugin did not calculate Armor + shield slots(/kit). When player have no space in armor slots, plugin give items when there is no place. 
And that's how those other things disappear somewhere. Plugin calculate inventory slots only.

### Version Information

```shell
CMI 9.7.7.10
CMILib 1.5.2.2
Purpur(2329) 1.21.1
```

### Errors

```shell
No errors in console.
```

### Relevant Plugins

Vault 1.7.3-CMI

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Items should be dropped on the ground if they are not being added to players inventory. By any chance you have this one disabled in that kit? 
![image](https://github.com/user-attachments/assets/34547e55-ecf8-4174-8073-bec305108360)

**Comment by smscentras** [comment]
When "Drop item if full" is disabled - plugin must should not give items to player.
But not to hide things in space.
