### ISSUE TITLE
Bugged hologram - gradient?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#9315]
### Description of Issue

Hello, I believe there's bugged hologram gradient. It was working before, just not sure when

{#de00ff>}&lCRYSTAL ARENA PIT{#5e00ff<}
![image](https://github.com/user-attachments/assets/f0a14a4b-1112-44c9-8972-96a8af096f18)
as you see there's missing IT at the end
there's only P

### Version Information

```shell
00:02:47 INFO]: --------------------------------------------------
[00:02:47 INFO]: CMI: 9.7.7.10 SqLite
[00:02:47 INFO]: CMILib: 1.5.2.2 
[00:02:47 INFO]: Server: Purpur(2329) 1.21.1-R0.1-SNAPSHOT-
[00:02:47 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[00:02:47 INFO]: Modules -> 54 enabled 13 disabled: customMessages, mirror, tablist, skin, playerChatTag, disabledEnchants, chatBubble, ranks, firstJoinMessages, playerCombat, votifier, sitAnimation, namePlates
[00:02:47 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
- '{#de00ff>}&lCRYSTAL ARENA PIT{#5e00ff<}'
This line in hologram section
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
This isn't really a bug, its new minecraft limitation. Entity names got applied limit in their length which can be quite easily reached if you have names with bunch of color codes, gradients does that quite easily. 3 options here, either shorten text itself, remove gradient, or switch to new display mode as its supported in 1.21.1 which will allow to have way longer text lines with gradients and some additional options. 
Can't really fix this and there is no real point in even attempting it as new display mode should be used on newer server versions which only have this issue.
