### ISSUE TITLE
Boosbar double cmd execute

### ISSUE THREAD

**Issue by corrysamu** [Zrips/CMI#9324]
### Description of Issue

I have a problem that when I start a bossbar for like 60 seconds if a player enters when the time is running the command that will be executed when the time runs out will be double, for example if I put a say on completion it will do 2

### Version Information

```shell
[19:20:54 INFO]: --------------------------------------------------
[19:20:54 INFO]: Versione di CMI: 9.7.7.12 SqLite-> 9.7.7.12
[19:20:54 INFO]: CMILib: 1.5.1.3 -> 1.5.2.3
[19:20:54 INFO]: Server: Paper 1.20.6-R0.1-SNAPSHOT-
[19:20:54 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled
[19:20:54 INFO]: Modules -> 58 enabled 9 disabled: coloredArmor, chatBubble, tablist, votifier, moneyCheque, headDrop, spawners, nightSpeedup, paintingEditor
[19:20:54 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Give me exact example of command you are using

**Comment by corrysamu** [comment]
I use This 
/cmi bossbarmsg all &2&lGive della doccia tra [autoTimeLeft]! -cmd:"crates key giveall gold_key 2;;crates key giveall rankup_key 1" -sec:-60 -c:green

**Comment by Zrips** [comment]
You might want to include bossbar name to make it a unique single thing even if you trigger it multiple times before timer runs out, so for example ` /cmi bossbarmsg all &2&lGive della doccia tra [autoTimeLeft]! -cmd:"crates key giveall gold_key 2;;crates key giveall rankup_key 1" -sec:-60 -c:green -n:BossBarUniqueID` where you can have that ID whatever you like, but now repeated trigger of it will only reset timer instead of creating new bossbar.

**Comment by corrysamu** [comment]
I tried but it does the same thing

**Comment by corrysamu** [comment]
> You might want to include bossbar name to make it a unique single thing even if you trigger it multiple times before timer runs out, so for example ` /cmi bossbarmsg all &2&lGive della doccia tra [autoTimeLeft]! -cmd:"crates key giveall gold_key 2;;crates key giveall rankup_key 1" -sec:-60 -c:green -n:BossBarUniqueID` where you can have that ID whatever you like, but now repeated trigger of it will only reset timer instead of creating new bossbar.

Man?

**Comment by corrysamu** [comment]
I tried but it does the same thing

**Comment by corrysamu** [comment]
@Zrips are you still there?

**Comment by Zrips** [comment]
Should be resolved with next CMILib update, if issue persists, let me know. Closing ticket for now.
