### ISSUE TITLE
9.7.7.11 changed all alias commands to "Enabled: true" breaking existing configs

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#9328]
### Description of Issue

Major issue where updating CMI to 9.7.7.11 changed ALL the settings in my Alias.yml enabeling all commands or resetting itself, this in turn completly broke all basic commands on my server like /msg to /pay as I do not use CMI for these. I have seperate Eco and chat plugins.

Can you make sure you do not do this in the future, make sure you dont wipe configs when updating, or at least state in the changelog in giant bold warning that you are going to wipe settings or have some sort of migration automatically. 

### Version Information

```shell
1.18.2 / 9.7.7.11
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by TomLewis** [comment]
Updating, a reboot has again wiped the alias.yml AND its re-added slashes in front of all commands, the issue is that its enabled ALL of the alias again, therefor breaking a lot of basic server functionality as other plugins use these commands.

Alias.yml resets each reboot.

**Comment by Zrips** [comment]
Will make few adjustments for Alias.yml file saving with next update, if issue persists, please let me know. At the moment could not reproduce this issue to verify it, but as few reported similar issue will be making adjustments

**Comment by TomLewis** [comment]
An update on another issue its caused;

**Comment by TomLewis** [comment]
So another weird thing thats just happened with alias, even tho in the alias.yml its set to disabled its like its trying to use it?
```yaml
  # /cmi pay $1-
  pay:
    Enabled: false
    Tab: true
```

This is in the alias yml, but on the server, when anyone uses /pay it shows nothing in-game like the command was never sent

This is very odd, but if I use /epay to bypass the alias as I use essentails pay still

same with anything else like /msg which I use chatcontrol or /reply, all in the alias.yml, and even tho they are set to disabled atm, they are somehow still taking over, but doing nothing in-game, no feedback at all.
