### ISSUE TITLE
Turn off "players online" console spam.

### ISSUE THREAD

**Issue by jonathanpublic** [Zrips/CMI#9329]
Server: paper 1.21.1 (Apex hosting)
CMI 9.7.7.12
CMILib 1.5.2.3

![Screenshot 2024-12-03 094715](https://github.com/user-attachments/assets/91414f99-4272-4da7-af7b-f2ab5e9cc235)

How do I turn off this console spam? I know it's CMI because when I remove the .jar file for CMI it stops happening. But there isn't any obvious settings for it in the config.yml, schedule.yml, or module.yml.

**Comment by Zrips** [comment]
This is done by your host to check if server is still responding or not, its common thing to trigger /list command on regular intervals, for your case its every 4-5 seconds. Check your hosts settings for any mentioning of /list command or 5 second intervals to check if server is still responding. Not much to do from my end here as it's being triggered for a purpose by 3rd party.
