### ISSUE TITLE
Way to prevent replacing _ with space in customtabs?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#9331]
Hello, is there some way similar to some something! that can disable replacing spaces in custom tabs?

```yml
    CustomTabs:
    - '[playername] duels_celestial,duels_inferno,duels_woodland,duels_amusement,duels_oaken'
```

I have region names and it replaces it with space 😅 so like If there's not way to stop replacing it

But yeah it's useful to replace _ with spaces, but not always prob

**Comment by Zrips** [comment]
It behaves in same way as it does in quite few other places, single _ will translate into a space, if you want to have _ in that tabcomplete then simply use double __ like 
```yml
    CustomTabs:
    - '[playername] duels__celestial,duels__inferno,duels__woodland,duels__amusement,duels__oaken'
```

**Comment by bobhenl** [comment]
yeah, but in the Cmds section the _ is without space right?

It behaves like this in CustomTabs only in the CustomAlais?
Like:

```yml
  COMMAND:
    Cmds:
    - delay! 5
    - asConsole! something $1 duels_celestial
```

here it behaves without space right?

Or when it behaves like the space? just so I know

And thanks for the response!
