### ISSUE TITLE
[suggestion] Couple small /money questions

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#934]
Feature request: Small ones.

Could /money also support /money send, not just `/money pay`. A lot of servers I am on we've got `/money send` and I see quite a few players trying `/money send`. Keep pay, but support send as option as well?

The other suggestion, if the action for money isn't recognized, could it check if it's a player, so we can have `/money <playername>` to be the same as `/balance <playername>`? Or maybe at least `/money balance <playername>`

[edit] posted some additional questions few posts below ---v

**Comment by mrfloris** [comment]
Friendly bump:

[works] /money
(this show me my money balance)

[does not work] /money <player>
(shows balance of the other player, like /bal <player>)

[works] /money pay <player> <amount>
(sends amount to player)

[does not work] /money send <player> <amount>
(as used on a lot of servers)

Is there a way I can set this up that I don't realise perhaps?
Are you open to adding these additions to the /money command?

Additionally, it seems the help for money explains to players the set/give/take as well, which they don't have perms too, as well as all/alloffline, which they can't without perms or console access. 
Maybe it is nicer if they get a simplified version of this help command output?

Thank you in advance for considering this!

**Comment by mrfloris** [comment]
Would it also be possible to use /money <player> ? So we can basically get the same as . /bal <player> through this? I notice in our log files that loads fo players are typing : /money <player> and i think it would be nice if it could give a response.

**Comment by mrfloris** [comment]
*friendly bump*

**Comment by Zrips** [comment]
Yes yes yes, /money send and /money [playerName] will be added as supported things, for different args, this would require some changes to be made for base command handling to have option to define different args for different groups of people. In general you could simply update locale file and remove unneded information from args field if you dont want to show that info for the players. Its like one command (maybe two?) which has admin and regular args in one command, so its quite deprecated to make separate methods to handle things like that at this point.
