### ISSUE TITLE
New placeholders item in hand

### ISSUE THREAD

**Issue by sungurami** [Zrips/CMI#9342]
**%cmi_iteminhand_itemcdata%** - _It will return the number of the custom model of the item. It will allow you to make new functions for items exclusive to custom models in general._

**%cmi_iteminhand_customdurability%** - _Since version 1.21, it is possible to give custom durability to objects. %cmi_iteminhand_durability% - shows only the vanilla unaltered strength of the item._

**Comment by Zrips** [comment]
Will add %cmi_iteminhand_maxdurability% and %cmi_iteminhand_custommodeldata%, there is no need to have custom durability as that one overrides base items durability value
