### ISSUE TITLE
bossbarmsg performance?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#9369]
Hello, what is best for bossbar MSG performance? By the spark it looks like that it's a bit heavy:
https://spark.lucko.me/boNIyNUrkI
I guess this can be caused because I use commands like:
```yml
    - cmi bossbarmsg $1 &cDamage Protection &6ends in [autoTimeLeft]! &6Disable via
      &c/grace disable -a:20 -sec:-3600
```
that prob last a bit long and I'm worried it's not so good for performance. 
![image](https://github.com/user-attachments/assets/4c0a7f9f-09de-451f-a68f-0f3b1e972f36)

any idea how can I improve it, please? For example, would be -t usage better for performance in case I don't need [autoTImeLeft]? Or like can I make the countdown to update every 5s instead every 1s? -a:40 seems not affecting it (it's not updating every 2s, it still updates the [autoTimeLeft] every second)

As in some bossbar I think it will be enough to update like once per 10s or once per minute (but still I'd like to show the [autoTimeLeft] just do not show every 1s but every 10s for example), I don't need so frequent updates and it could probably help? Just not sure if I can do it right now?

![image](https://github.com/user-attachments/assets/2cb9db1f-c14d-47a3-841a-9fc9a4b813fa)
https://spark.lucko.me/cHMUbcS3uR

**Comment by Zrips** [comment]
Some performance improvements will come out with next CMILib
