### ISSUE TITLE
In-game chat navigation tweak (first one goes to end of list)

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#937]
**Suggestion:**

As posted here; 
https://www.spigotmc.org/threads/20-off-sale-cmi-240-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much.48111/page-263#post-3179558

It would be nice if when we type certain commands like /cmi aliaseditor, that the pagination that's like
< last | next > could not be gray, but would actually go to the end of the list. 

Or otherwise, have an option to list these entries from new to old, rather than chronologically. This way we don't have to go through x amount of pages just to edit a couple of the more recent ones. 

Thank in advance,

---

**Comment by mrfloris** [comment]
Since I posted this on October, I thought it would be nice to give this a friendly bump <3 
I work on the aliases on a daily basis, and having to cycle through 25+ pages just to re-edit something is a bit annoying ;) We could really use this.

**Comment by Zrips** [comment]
Ok, will do.
