### ISSUE TITLE
Invulnerability permission / cancelling / cooldown -> players abuse it

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#9372]
Hello, I got report that players just teleport back and forth to home and then when someone wants to attack them he can't because they're invulnerable.

So like person can just be invulnerable forever in case we have like 15-60s invulnerability time on teleport, 3-5s warmup, then he just walk, try to trap player with blocks in his claim, then go home again, and again and again and he cannot be attacked

Due to this I suggest adding one of these:
- Cooldown for invulnerability to prevent players teleporting back and forth
- Permission, so we can make cooldown somehow on our own, like add the false perm for 15s (but the first option may be better)
- Cancel it via the cmd (can be useful sometimes, but not sure if it can solve this issue)

**Comment by Zrips** [comment]
Will add extra options to disable teleport invulnerability if player interacts with something, places or breaks a block while having teleport invulnerability, this will prevent player from remaining untouchable while performing actions. Next update

**Comment by bobhenl** [comment]
Thanks! That's great solution
