### ISSUE TITLE
Stop /cmi cheque executing on opening chest

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#939]
**Suggestion:**

It seems if you have a cheque in your hand and right click a chest to store it, that it executes and get the money. Instead of opening the chest as if it's an open. 

It would be nice if this would stop, so players can stop accidentally opening (normal / trap / ender) chests, anvils, droppers, hoppers, etc.. and be able to place the item for storage, usage, etc.

Thank you.

**Comment by Zrips** [comment]
Next update we will ignore chests, ender chest, doors, trap door, buttons and gates while clicking cheque
