### ISSUE TITLE
Missing locale for command.kit.info.oneTimeUse

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#942]
This locale is missing when a user hovers over the clock symbol
The kit in which this is used is multiple times usable

Kit section:
```
  MaxUsages: -1
```

Cmi Version 8.0.19.0

**Comment by x1p** [comment]
How difficult can this be that this takes a month to fix ?!?

Btw: manually adding this line won't fix this, because this line is deleted every time.

**Comment by Zrips** [comment]
Next update will be fixed.

**Comment by x1p** [comment]
Please add 929 too:
command.jailedit.info.collides
