### ISSUE TITLE
[Bug] Baltop is not working

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#943]
**Description of issue or feature request:**
Baltop is not working correctly. Sometimes it displays all the players, but in the wrong order. For example 1 place has 5000 dollars and maybe the 3 place has 30000 dollars. Sometimes it doesnt display more than one player. Like the picture below.

![image](https://user-images.githubusercontent.com/19745447/46586761-490e4a80-ca83-11e8-9d7c-f03e188dd182.png)

---

**Cmi Version (using`/cmi version`):** 8.0.19.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper(343) 1.13.1-R0.1-SNAPSHOT

**Comment by Kryniowesegryderiusz** [comment]
I have same issue

**Comment by Baktus79** [comment]
#1020

**Comment by LogGits** [comment]
Some significant changes were made to how CMI handles baltop. Please test `8.0.21.3` and let us know if this issue persists.

**Comment by LogGits** [comment]
I am assuming this was resolved. If you are still experiencing this issue please let me know.
