### ISSUE TITLE
Villager Happy Particle - Portal Bug

### ISSUE THREAD

**Issue by doitliketyler** [Zrips/CMI#944]
**Description of issue or feature request:**
When using villagerhappy as a particle type for a portal after awhile it resets itself back to reddust. Not sure why this is happening but its been going on for at least a week now. Thoughts?

---

**Cmi Version (using`/cmi version`):** 
8.0.19.0

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.13.1-R0.1-Snapshot

**Comment by LogGits** [comment]
Do you still experience this on 8.2.2.0 on 1.13.2?
