### ISSUE TITLE
Name Change placeholder issue

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#945]
This was fixed before the 1.13 version of cmi but it looks like it became a issue again, not sure why but the placeholder did not work as you can see in the chat:

https://pastebin.com/MrLiWrMr

https://gyazo.com/8c47d6dfa38072b4571c156ad2fd4658

**Comment by LogGits** [comment]
U may have to try installing vault from placeholderapi.

E.g./papi ecloud download vault
Let me know if this helps

**Comment by LogGits** [comment]
I tested this out using that command and it works. If you are still experiencing this issue please let me know.
