### ISSUE TITLE
New special dye Rainbow/Light/Heath/Biome work only after you relog on server

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#949]
I noticed these cool stuff work only if you relog the server after you applied the special nbt to these leather, not sure if is normal :)

**Cmi Version (using`/cmi version`):** 
8.0.19.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
1.8.9

**Comment by CloudeLecaw** [comment]
on our Server and my testserver it works fine after using the command.
SPIGOT 1.13.1

so ist a PaperSpigot Problem

**Comment by xion87** [comment]
i will dont use the rank system, but the timedreward, hopeful that it work nice

**Comment by CloudeLecaw** [comment]
i like the timereward. worked nice on my testserver :)

**Comment by LogGits** [comment]
Are you still experiencing this issue on 8.2.2.0?

**Comment by xion87** [comment]
still same issue on 1.8.9

**Comment by Zrips** [comment]
Yea, next version will have this one fixed
