### ISSUE TITLE
[Question] Convert iconomy to cmi

### ISSUE THREAD

**Issue by Malachiel87** [Zrips/CMI#953]
Hi i want know if is possible to import iconomy data to cmi, i use offline mode, is possible?

**Comment by CloudeLecaw** [comment]
No it is not we also had this Problem. and the answer is easy
Change to CMI and manually Change the 100000 Players to your new mysql table or edit them in the SQLite database.

a convert command does not exists.

**Comment by xion87** [comment]
what if i use essentials for some weeks to take player data to hook to vaulteconomy and then use cmi import data?

**Comment by CloudeLecaw** [comment]
u asked for iconomy data Import not for Import of essentials data….

**Comment by xion87** [comment]
essentials can hook in any economy, importing cmi from essentials it will import also iconomy data? or i am wrong?

**Comment by xion87** [comment]
so i think i will do this, use cmi for some months and then move all data via custom migrator

**Comment by CloudeLecaw** [comment]
good try, wiuld be nice to hear the results :)

**Comment by xion87** [comment]
Yeah I done that you can close it
