### ISSUE TITLE
[Question] Is there a way to remove italic from gamemode 3 tablist

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#954]
Hey

Is there a way to remove italic from name on the tablist when someone goes into gamemode spectate?

**Comment by CloudeLecaw** [comment]
yes the answer is ..use vanish ;)
and no there is no way to hide this Little minecraft Default, therefore the whole tablist would Need a few changes :§

what you wanne do? Be as admin in gm3 without your Players know you may be near them?^^

**Comment by Baktus79** [comment]
Yes, that is correct :) Im used to use BungeeTablistPlus, and in that plugin its possible. Its no big deal but would be nice to be able to enter gm 3 without everybody knows
