### ISSUE TITLE
[Suggestion] Compatibility with LeaderHeads placeholder for holograms

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#957]
I would like to see the actually cmi holograms supporting LeaderHeads placeholder https://www.spigotmc.org/resources/leaderheads.2079/updates

**Comment by LogGits** [comment]
I could be wrong but I think it already supports placeholderapi placeholders. Try installing placeholderapi and then install leaderheads support using papi ecloud. After this it should work, I could be wrong. Just let me know if it isnt functional and I'll add the appropriate tags :+1:

**Comment by LogGits** [comment]
Yeah it does support placeholderapi

> It's supports PlaceholderAPI plugin to display any information you want and it can show different information for separate players.

**Comment by xion87** [comment]
No more use, because author rewrited the pl by using placeholders :)

**Comment by RobinDeBaets** [comment]
@xion87 
I find the [CMI documentation](http://www.zrips.net/cmi/holograms/) a little bit confusing and I don't have a copy of the plugin so I can't test it. I want to add this to the LeaderHeads documentation. Have you tried compatibility between [LeaderHeads PlaceholderAPI placeholders](https://panoply.tech/leaderheads#placeholderapi-and-mvdwplaceholderapi-placeholders) and CMI?

**Comment by LogGits** [comment]
@RobinDeBaets if it works using `/papi parse` it will work with cmi. Just use ur regular placeholder in a cmi hologram.

**Comment by RobinDeBaets** [comment]
@LogGits how frequently are the placeholders replaced? 
I could not find this information on your wiki. 
Could you also provide me with a sample file and filename of how the holograms are stored in the plugin folder?
I'd like to provide my customers with an example of how the CMI hologram integration works with my plugin through PlaceholderAPI.
