### ISSUE TITLE
[Request] Disable push for vanished players

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#959]
Vanished staff can still push players/mobs. This is extremely annoying when a staff teleports to a specific player, the player gets a push and knows he is being watched and the vanishing is useless.

I would like a to disable pushing. Preferable being able to switch on/off via the vanishedit gui.

**Comment by LogGits** [comment]
Well we do have a /cmi playercollision that you could use in the meantime. I would like to see this feature added into vanish/vanishedit by default as it decreases the rate of detection.
