### ISSUE TITLE
Rollback /reply modification made recently (or allow config setting to use old style of reply)

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#96]
Ref:
Now sending messages with /r will send to person to whom you had sent message before. In case you dint sent any, then this will respond to last one who sent you message. So you can keep conversation with same person while getting bunch of private messages from other players.

Note:
This changed pretty much how /r has been used for 6+ years in Essentials and what all players are used too. It is really confusing for players and myself. Yes, it is a pain when you hit /r to someone and you get another private message and hit send without paying attention, but that happens much less than getting a private message from someone and typing /r and have that response go to a player you talked to the day before.

**Comment by digitalcrowd** [comment]
How about a compromise third option...

When you do /r to someone, it will auto-fill in the players username you are reply too. This way if you get new messages in while you are typing it, it still goes to the same player you originally intended.

This would also mean that if a player sends you a message and you type /r, it would still work as the normal method we have all been used too for so long. 

Just an idea.

**Comment by LogGits** [comment]
Please ensure you have the latest versiion of CMI. Currently CMI is handling messaging exactly as you are describing:

3 players (A, B, C):
```
A /msg B hi
B /msg A hello
C /msg A heya
A /r ->B
```

**Comment by digitalcrowd** [comment]
> Do you want to have /r reply directly to the person who /msg'd you last?

Correct.

**Comment by Zrips** [comment]
Will add option to switch between new and old behavior throw config file.
