### ISSUE TITLE
[Feature Request] Lay command

### ISSUE THREAD

**Issue by Malachiel87** [Zrips/CMI#960]
An addition to sit command, would be like /lay command, it simulate a fake bed. amd  you lay yourself on floor, it would be possible? There is already a plugin that do it but is abandoned and lay work only for other players but you will see not layed.

**Comment by Baktus79** [comment]
That would be a great addition to the /sit command :D

**Comment by DragonisOmega** [comment]
/lay back and /lay stomach or /lay, /crawl
