### ISSUE TITLE
Typo issue on kit cooldown

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#961]
**Description of issue or feature request:**
On translation canUseIn: "&eCan use again in: \n[time]" it appaer like this
![image](https://user-images.githubusercontent.com/3611852/46724440-4de91f00-cc7a-11e8-99be-1a91f1987bc3.png)

**Comment by xion87** [comment]
i used ' ' in the file, here in github i write " " for reference it...

**Comment by CloudeLecaw** [comment]
oh..just wondering i tested this with the german langfile..and there this issues seems not to be..

your Using Spigot 1.13.1 + newest Version of CMI too?

ah /cmi Version  screen would help here fast to Show us what versions your using, then we dont Need to ask allways:)

**Comment by xion87** [comment]
i am used the english lang file, (default one), i am using 1.12.2, but the issue is present also with 1.8.9 and yes i am using CMI 8.0.19.0
