### ISSUE TITLE
Villagers IC resetting agian.

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#964]
This was fixed a version or two ago but villageres dont save their IC after a reboot or whatever.

**Cmi Version (using`/cmi version`):** 8.0.19.0

**Server Type (Spigot/Paperspigot/etc):**  paper
**Server Version (using `/ver`):**  1.13.1

**Comment by LogGits** [comment]
I also experience this issue, does this still happen in 1.13.2 + 8.2.2.0? (Also if you haven't already, I recommend updating paper to 1.13.2)
