### ISSUE TITLE
CMI /info - error

### ISSUE THREAD

**Issue by Rukes** [Zrips/CMI#966]
Executing `/cmi info <player>` prints me out this error. [Link](https://pastebin.com/3J8G6bR6)

**Comment by CypherPhyre** [comment]
It looks to me that you don't have the correct perms for it.

**Comment by Rukes** [comment]
Nice, but it should be compatible, lmao

**Comment by CypherPhyre** [comment]
What I am saying is that you may not have the correct permissions set for that command. Recheck that you have the correct permissions.
I have the following set for all players on my server:
cmi.command.info
cmi.command.info.others
cmi.command.info.deathlocation
I also have this set for my admins:
cmi.command.info.ip
The command works fine on my 1.13.1 server

**Comment by Rukes** [comment]
Its executed by console, but if I execute that command as OP, prints same error, but thanks 😄

**Comment by LogGits** [comment]
Try using LuckPerms. It's a far better alternative. @Zrips SuperPerms has an alternative way of handling permissions, thankfully, vault has a:
```java
Variables.permission.hasGroupSupport();
Variables.permission.hasSuperPermsCompat();
```

**Comment by Zrips** [comment]
This should be fixed with latest version
