### ISSUE TITLE
[Bug] command "/cmi dye" can't use from console

### ISSUE THREAD

**Issue by momoservertw** [Zrips/CMI#970]
1.  Command "/cmi dye" can't use from console.
![image](https://user-images.githubusercontent.com/38014059/46782185-d5589000-cd57-11e8-8413-0b3fa1f4e9f5.png)

2. The command help doesn't have "randow/rainbow/biome/health/day".
![image](https://user-images.githubusercontent.com/38014059/46782136-9c202000-cd57-11e8-9803-9ff357401f6f.png)

--
CMI plugin version: 8.0.19.0
Server version: Spigot 1.12.2-R0.1-SNAPSHOT
Vault version: 1.6.10(+)

**Comment by Zrips** [comment]
Thanks for report. Will be fixed with next update.
