### ISSUE TITLE
Hologram removal not working

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#979]
I have a &uHologram setup which I believe was converted from holographicdisplays. When I run /cmi hologram then click the X to delete it the color changing effect goes away, but the text of the whologram is still there - just in white.

**Cmi Version (using`/cmi version`):**  8.0.19.0

**Server Type (Spigot/Paperspigot/etc):**  paper

**Server Version (using `/ver`):**  1.13.1

**Comment by LogGits** [comment]
Are you still experiencing this in 1.13.2 on cmi 8.2.2.0?
