### ISSUE TITLE
(Request) /clearinventory with a confirmation (/ci confirm) 

### ISSUE THREAD

**Issue by Ew9304** [Zrips/CMI#98]
Would be great if you could add a command like Essentials to clear a players inventory, after doing /ci or /clearinventory it can popup in chat to type /ci confirm to clear all items from inventory

Thanks for all your work

**Comment by digitalcrowd** [comment]
I'll second that. I typed it by accident once. :/

**Comment by HomeLandingsDE** [comment]
I would not welcome this change - just disable the Alias Command - who then enters / cmi clearinventory knows his inventory will be cleared

**Comment by digitalcrowd** [comment]
Probably good idea to just disable alias. I think it was /clear that got me. If it had been the full command, I wouldn't have run it. Or perhaps make it a config option you can enable or not enable for the confirm.

**Comment by Sikatsu** [comment]
Config option sounds good.

**Comment by Royster0** [comment]
Im gonna bump this because just having a confirmation to clear your inv would be beneficial

**Comment by CaliDreams** [comment]
I use /ci and /clear often enough on purpose, I'd hate to disable the alias. An in-game toggle command for clearinventory confirmation or a config option to enable a confirmation message in game would be hugely beneficial to those of my staff/players new to the command.

**Comment by LogGits** [comment]
Thank you for the request, this was recently added 🙂
