### ISSUE TITLE
[Request] Money transfer log

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#982]
Could it be possible to add a log for everytime someone transfered money to someone or gained from other players or a plugin.

This feature should be optional.

**Comment by Rukes** [comment]
I would like to bump this issue!

**Comment by Rukes** [comment]
I would like to bump this issue, @Zrips

**Comment by TheoRetisch1** [comment]
Yeah, I agree with Rukes. It is not a nice-to-have feature but very important and useful in daily business. I would love to see this!

**Comment by Zrips** [comment]
Added. Some improvements can be done in future, but base mechanic is up and running.

**Comment by Rukes** [comment]
@Zrips where is the log? local file or database?
