### ISSUE TITLE
/baltop not recalculating i think

### ISSUE THREAD

**Issue by silvasky54** [Zrips/CMI#986]
/baltop doesn't seem to be working accurately. Only on a server restart do the correct balances show. In most cases only 1 and 2 show the correct balances. On top of that the placeholders in a hologram show different numbers to /baltop in chat.

---

**Cmi Version (using`/cmi version`):**  8.0.19.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.12

**Relevant plugins (Delete if this isn't needed):** CMi,Vault (from link cmi page), SellAll

**Comment by Morphiee** [comment]
I'm having this issue as well. On server restart, the baltop works properly. After some time the baltop only shows 1 user. Hope to see this fixed soon!

https://gyazo.com/98777835626bd7bf7a91b163128a8fce

**Comment by Kalasky** [comment]
Same here only 1 user pops up on my server as well.

**Comment by Baktus79** [comment]
#943

**Comment by Baktus79** [comment]
#1020

**Comment by silvasky54** [comment]
#1022 

Seems to be an issue many people are effected by. 

As an added suggestion could baltop be recalculated automatically upon a server restart?

**Comment by LogGits** [comment]
Duplicate of #943
