### ISSUE TITLE
[Bug] Placeholder not working in tab?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#989]
i tried to use a placeholder of the PlaceholderAPI in Tab %server_tps% this placeholder seems not to work
in result the tab shows me the word "%server_tps%"

Placeholder API and the server extansion is installed.
othes like %server_ram_used% work

![image](https://user-images.githubusercontent.com/12080017/47050905-5e315a80-d1a2-11e8-896e-6f0003d8b6d1.png)

**Comment by Melowelei** [comment]
Hello CloudeLecaw,
When I use "/papi parse me %server_tps%" it's returning "coming soon..", I think this placeholder don't work for now.

**Comment by CloudeLecaw** [comment]
So this is a placeholderAPI Bug?

**Comment by Melowelei** [comment]
We can't really say a bug, because the placeholder is parsing "coming soon..".

**Comment by LogGits** [comment]
This is unrelated to cmi. `%server_tps%` is broken on PlaceholderAPI's side.

**Comment by CloudeLecaw** [comment]
Just for a Little info..the developer allready sendet me a "fixed" (recompiled) Version of the Exüansion-Server.jar of PlaceholderAPI. if ist allready fixed in the download simply delet you old one inside PlaceholderAPI/expansions Folder and reinstall the Expansion. then it shoukld work. if he has not updated his source official allrready, here is the file for you  :) (as a zip becaus i cant upload jars here)
[Expansion-Server.zip](https://github.com/Zrips/CMI/files/2663713/Expansion-Server.zip)
