### ISSUE TITLE
BUG: One incorrect config file item and it all goes nuts

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#99]
CMI is a feature rich plugin (thank you, thank you, thank you), with a wealth of features. With one minor error in the config and a /cmi reload, all hell breaks loose. You either get a default config file (removing all custom settings, eco resets, homes are lost, players panic) or you get what seems like a random backup config file, which is all lost when you shutdown the server and start it back up.

The only safe way to do it is, shut down the server. Replace the config file with own backup or if you're lucky, one in the CMI backup folder, while offline, then bring the server back online.

It would nice if CMI would...

a) Check the config before allowing /cmi reload to work, and if there are errors, output the errors and leave it all untouched, allowing admin to fix his/her mistake and move on.

b) If starting the server and the config is messed up, load all that it can read or panic and shut down the server with line number of config error. By having the whole plugin messed up because of one line in the config file, and if someone like myself is using 80% of the features of this plugin, might as well just leave server shutdown because no custom settings are in place. 

I've had to MySQL DB cleanup from one error I made, because it inserted new lines in the DB for players online, "resetting" their money, but I was able to remove duplicate lines after shutting down the server.

**Comment by Zrips** [comment]
You do have FileBackups folder where files will be put in case there is some errors in any of files. Then you can fix file and copy over original one and reload server. Do we really need prevention for server to even start in case there is issue with config file format?

**Comment by digitalcrowd** [comment]
Maybe not so much on "startup", but most plugins will just error out and give you the location of the error. What is the purpose of over-writing the file anyway? I mean, the concept seems notable (bring it all back online anyhow, vs not at all), but in practice I don't think it's good. I make small tweaks all the time to many files in CMI and just reload in-game. This is pretty much a flawless process. However, when you do have a flaw, a quick 1 minute change, turns into a 30 minute WTF experience for everyone the server. Balances get zero'd out, it forgets the mysql DB location, and even if you correct in in-game and bring in the correct config, when you shut-down, it reverts to the previous not-current config, so when you startup your in the same boat. So you have to shut down again. Copy the config file over, and then startup again, then cleanup any damage, whether in the database or just with the players questions about all that transpired.

When it would be more simple to be like... "You idiot, why did you do that on line 122? Fix it" and either disable the entire plugin, or as mentioned in original post, to check config before reloading. Thus, I'd have a simple 30 seconds ordeal of commands not being available (if it just disabled the plugin) until I could correct the error and /cmi reload or /plugman reload cmi.
