### ISSUE TITLE
Soil teleport bug

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#997]
**Description of issue or feature request:**
Teleporting onto farmland in this configuration:
https://gyazo.com/35b723faab28a845622e3a60b469d58c
Causes you to fall through and get the obstruction message.

---

**Cmi Version (using`/cmi version`):** 8.0.19.0

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1568

**Comment by Zrips** [comment]
Next update will have this one fixed

**Comment by LogGits** [comment]
Still having this issue

**Comment by LogGits** [comment]
Resolved in latest.

**Comment by EpicJosch** [comment]
Still having this issue

**Comment by EpicJosch** [comment]
i have the latest version
